### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jordan-bravo** [carbon-design-system/carbon#10007]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

v7.44.2

### Description

When using DataTable with selection and isSortable, on hover over the left-most column header, the hover state effect appears to bleed into the selection column on the left side.  In the Carbon docs (https://www.carbondesignsystem.com/components/data-table/usage/), there is a live demo and if the “With selection” variant is selected and “isSortable” is checked, the same issue is reproducible.  This appears to be an issue with Carbon. 

### Screenshots

<img width="1792" alt="carbon data table hover bug" src="https://user-images.githubusercontent.com/62706808/139703609-ebc5b399-f293-4d9a-a224-4e536deb6aff.png">

### Steps to reproduce

Use DataTable component with selection and sortable.  Hover over the left-most column header.

Expected behavior:  Hover state effect should not bleed into selection column on left side.

Actual behavior: Hover state effect bleeds into election column on left side.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Closing as dup of https://github.com/carbon-design-system/carbon/issues/9837, which got fixed last week. Fix should be included in our next release. :)
