### ISSUE TITLE
Include distribution folder 

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#1002]
## Detailed description

Is there a reason why carbon-components doesn't include a distribution folder with minified/compiled CSS? This would allow the react carbon components library to work with create-react-app. Currently, you have to eject from create-react-app to support the node-sass loader. I think this would greatly improve the usability of the library for folks who don't want to run a separate build step.

**Comment by asudoh** [comment]
Hi @vpicone thank you for trying to report an issue? Did you want to take a look at [`css` directory in the NPM package](https://unpkg.com/carbon-components@9.5.2/css/)?

**Comment by vpicone** [comment]
Facepalm. Thanks @asudoh !
