### ISSUE TITLE
[Bug]: Button of `type="ghost"` with `hasIconOnly` prop renders icon with fill colour grey/black, instead of blue.

### ISSUE THREAD

**Issue by elewis06** [carbon-design-system/carbon#10026]
### Package

carbon-components

### Browser

Chrome

### Package version

10.35.0

### Description

```
<Button
    type="button"
    kind="ghost"
    renderIcon={Add32}
    onClick={...}
    hasIconOnly
/>
```
This button should render the desired icon with fill colour blue (#0F62FE). Instead, the icon is rendered with fill colour grey(#161616). This bug only appears to affect the icon itself within an icon-only button. Please see the CodeSandbox example for further detail.

Four buttons for illustration:

- Icon only, with `hasIconOnly` prop.
- Icon only, without `hasIconOnly` prop.
- Icon and text, with `hasIconOnly` prop.
- Icon and text, without `hasIconOnly` prop.

![Screen Shot 2021-11-01 at 3 35 52 PM](https://user-images.githubusercontent.com/37430212/139730642-dcf18f37-822e-4ed9-bdbd-7e6a58056e75.png)

### CodeSandbox example

https://codesandbox.io/s/tearsheet-example-forked-q4387?file=/src/ButtonExample.js

### Steps to reproduce

No steps required. Button code provided:

```
<Button
    type="button"
    kind="ghost"
    renderIcon={Add32}
    onClick={...}
    hasIconOnly
/>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by elewis06** [comment]
Turns out this is not a bug, but intentional by design.

**Comment by amilligan** [comment]
@elewis06 Could you please point me to where you found the justification for this design decision?  I'm curious, because the button is still an interactive element, so it seems it should have the interactive theme color.  But, I don't want to mess with it too much if there's a clear reason to use the non-interactive theme color.

**Comment by elewis06** [comment]
@amilligan @aagonzales, a senior visual designer for the Carbon design system, informed me of this.
From Anna: "The icon-only version is intentionally a neutral color and not blue. We never have standalone blue icons in the system."
Hope this helps!

**Comment by amilligan** [comment]
@elewis06 I see, thank you.
