### ISSUE TITLE
Filterable MultiSelect loses dropdown label.

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon#1003]
## Detailed description

> Is this issue related to a specific component? 

Filterable MultiSelect 
 
 
 
> What did you expect to happen? What happened instead? What would you like to see changed?

It's not currently in the designkit (as far as I could see). The multi-select behaviour is problematic and different when filterable, in that it removes the dropdown label.

This is fine when the user is actively typing to filter down results, but leaves it looking confusing once some items have been selected - with the component reading: "(1x) Filter"

What I'd like to see changed: The dropdown label is returned when focus is not applied, making the component semantically readable and consistent with the non-filterable variant. When focus is applied the label could be replaced with the 'filter' message.
 
 
 
> What version of the Carbon Design System are you using? 
9

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/30671949/43408244-b4374a60-9418-11e8-8cee-393aa903b171.png)

* Notes

**Comment by joshblack** [comment]
Hi @lukefirth! 👋 Thanks so much for taking the time to make this issue 😄 

Quick question, is this for the React.js implementation of this component?

**Comment by lukefirth** [comment]
Hey @joshblack thanks for getting back so soon. 👋 

This is indeed! [Link to the specific component in storybook](http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=filterable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by alisonjoseph** [comment]
Issue moved to [IBM/carbon-components-react #1143](https://github.com/IBM/carbon-components-react/issues/1143) via [**ZenHub**](https://www.zenhub.com/)
