### ISSUE TITLE
[Dropdown]: option to call itemToElement for selectedItem not just list of items

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon#10038]
### Summary

We've been highjacking the `itemToString` function in the Dropdown to create an IconDropdown component for selecting warning icons. We simply returned an object from `itemToString`, and this worked well until 10.43/7.43 when the title attribute was added to the button in the Dropdown. However, now, visually it still works, but we get `title="[Object object]"` in the output of the selected icon. Would it be possible to add a prop to determine which function (`itemToElement` or `itemToString`) is used to render the selected item in the dropdown?

CodeSandbox example: https://codesandbox.io/s/goofy-water-2o4d4?file=/src/index.js

<img width="619" alt="Screen Shot 2021-11-03 at 9 18 45 AM" src="https://user-images.githubusercontent.com/609466/140067671-c0680a98-377f-48a8-b930-684d7fcdb1de.png">
<img width="607" alt="Screen Shot 2021-11-03 at 9 22 25 AM" src="https://user-images.githubusercontent.com/609466/140067763-30924eea-2858-47da-8b38-ad0e66752552.png">
<img width="639" alt="Screen Shot 2021-11-03 at 9 18 54 AM" src="https://user-images.githubusercontent.com/609466/140067670-9d47e10f-be2e-4b20-9aae-06a148ff80bd.png">
<img width="601" alt="Screen Shot 2021-11-03 at 9 23 48 AM" src="https://user-images.githubusercontent.com/609466/140067937-79777164-2c88-47ff-89d0-a7e511314465.png">

### Available extra resources

I can write the PR.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @kevinsperrine! 👋  Thanks so much for taking the time to make this issue.

It would help out a ton if you could include a codesandbox link with steps to reproduce what you're running into 👀 will be happy to check out what's going on and what we can do to help out based on that 👍

**Comment by kevinsperrine** [comment]
@joshblack Sure thing: https://codesandbox.io/s/goofy-water-2o4d4?file=/src/index.js I added a bunch of comments to clarify.

**Comment by kevinsperrine** [comment]
Hi @josh, Will you all accept a PR for this. I'm happy to write it today if so. I think a `renderSelectedItem` callback that can render an element, but if it's not provided we fallback to the current `itemToString` output makes the most sense.

**Comment by TannerS** [comment]
> Hi @josh, Will you all accept a PR for this? I'm happy to write it today if so. I think a `renderSelectedItem` callback that can render an element, but if it's not provided we fallback to the current `itemToString` output makes the most sense.

The carbon team is always open for contributions 

https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md

(not carbon team member)

**Comment by dakahn** [comment]
Hey there! The example provided in the Codesandbox seems cool to me, accessibility wise (when contrasted with the original issues example especially). If you want to get the PR up for us to test make sure and include a Storybook example that illustrates your use case (for accessibility verification testing). Thanks! 👍🏾

**Comment by kevinsperrine** [comment]
Thanks, @dakahn. I'll be out a lot of this week, but I'll submit this next week. Thanks for accepting the proposal.
