### ISSUE TITLE
[Bug]: Managed Tooltip cannot close using interactive content

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#10040]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.47.0

### Description

A managed tooltip raises onChange events and expects the open property to be set. 

If a button in the tooltip is used to perform an action that closes the tooltip we would expect that clicking the button setting the open property to false would close the tooltip. However it triggers a focus which causes an onChange(evt, true).

### CodeSandbox example

https://codesandbox.io/s/hardcore-orla-yl9l0?file=/index.js

### Steps to reproduce

1.   Open the tooltip
2. Click the button 'create'
3. Note the tip is closed but immediately reopened.

NOTE: If the 'Create' button has focus this tooltip is not reopened.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Potentially related https://github.com/carbon-design-system/carbon/pull/9959
