### ISSUE TITLE
[Feature Request]: Cannot find Tag input component can be used

### ISSUE THREAD

**Issue by superman566** [carbon-design-system/carbon#10047]
### Summary

We need a component that allows our users to input text and convert it to a colored tag when pressing `enter`. it could be used with autocomplete or without it. And this is different from the Multiselect component in CarbonX.

### Justification

Some of the most popular UI frameworks have it and now we are needing it in an actual project but carbon does not have it implemented.

### Desired UX and success metrics

It's basically a text input in which we are going to type a word or phrase, press enter and a tag will be displayed inside that input, it could be on the same row of the input or display above it BUT it should be looking like it's inside the input, this input can be used with autocomplete or without it, you'll watch it in the design.

![image](https://user-images.githubusercontent.com/8649164/140194515-92b31be7-bdf6-469c-8839-27036f9b0bd7.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by superman566** [comment]
related to: https://github.com/carbon-design-system/carbon/issues/2422

**Comment by tay1orjones** [comment]
Hi @superman566 - As you've found, this general idea of tags in a field has been proposed a few times before. In this specific case, what you're proposing seems to be a variation of the ComboBox component. The most recent determination on this idea was in regards to MultiSelect https://github.com/carbon-design-system/carbon/issues/2571#issuecomment-577313072 -  placing tags inside fields carries design scalability issues. I believe the same problems would apply here.

**Comment by superman566** [comment]
@tay1orjones thanks for your reply, I am thinking of a scroll bar that could be applied for the scalability issue
![image](https://user-images.githubusercontent.com/8649164/140400102-11b08d26-fb0a-4dbf-bf9f-f9a150ce4d5b.png)

**Comment by aagonzales** [comment]
Hello @superman566! At the moment, this is a feature we are not pursing adding to our dropdown. We think the pattern as a whole needs some more research and testing around the interaction and scalability before we could add it into the core library. That said we are not discouraging you from using it, we just won't be building it and suggest that your team builds it on your own.
