### ISSUE TITLE
HeaderMenuButton not rendering when width is more than 1050px

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#10045]
Has anybody found a resolution for the issue below

> HeaderMenuButton not rendering on Chrome but I can see it when I open the CodeSandBox, any reason for this?
```
<HeaderMenuButton
    aria-label="Open menu"
    onClick={onClickSideNavExpand}
    isActive={isSideNavExpanded}
/>
```
make sure you have this added. also.. this appears only on low width pages. (max ~1050px)

_Originally posted by @ndite in https://github.com/carbon-design-system/carbon/issues/3666#issuecomment-629709845_

**Comment by GerhardMareeSMS** [comment]
Working as designed 

https://codesandbox.io/s/left-and-right-panel-jz7rz?file=/src/index.js

**Comment by granite83** [comment]
i encouter the same issue, the HeaderMenuButton is hidden until the width larger than 1055px , do you find the solution of the issue?

**Comment by RSamal** [comment]
I agree this issue still happens. If the screen resolution go beyond 1055px

Shows with 1055px
![Screenshot 2024-03-16 at 9 18 20 PM](https://github.com/carbon-design-system/carbon/assets/5267629/d24a5328-3854-42f5-b50d-c3bd8c61824e)



Does not shows with 1056px
![Screenshot 2024-03-16 at 9 19 01 PM](https://github.com/carbon-design-system/carbon/assets/5267629/3b4f9e1b-a156-473d-90ba-e1b7abc9b6c4)
