### ISSUE TITLE
[Bug]: Theme components/zones does not affect layer tokens

### ISSUE THREAD

**Issue by ishitatsuyuki** [carbon-design-system/carbon#10049]
### Package

carbon-components

### Browser

Chrome, Firefox

### Package version

v11 / Modules

### Description

The theme components fails to affect a portion of color tokens that uses the new layer convention. The layer tokens are defined and evaluated at :root, and since CSS custom properties points to the *value* at the scope of the evaluation and not the *reference*, they remain unaffected by inner theming zones.

### CodeSandbox example

https://codesandbox.io/s/vigilant-rosalind-vfp20

### Steps to reproduce

Upload something.

The `cds--file__selected-file` box's background color is white despite the theme being g100. It refers to `--cds-field` which is defined at `:root` and at `:root` the `--cds-field` value defaults to the white one.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi @ishitatsuyuki! 👋  Thanks so much for making this issue, definitely see what you mean. I think our selectors for the inline themes / zones need to include the layer values, as well 👍
