### ISSUE TITLE
[v11]: update $text-disabled and $text-placeholder values

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10054]
Thanks to some feedback from users we've discovered that $text-disabled doesn't work on $field-03 and is causing issues. I've laid out the full fall out of this problem in the image.

**TLDR solution:** is to use an opacity of the $text-primary color for `$text-placeholder` and `$text-disabled` so they can have an equal emphasis across layers. Neither needs to pass color contrast.

  | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme
-- | -- | -- | -- | --
$text-disabled | $text-primary@25%, Gray100@25%, rgba(22,22,22,0.25) | $text-primary@25%, Gray100@25%, rgba(22,22,22,0.25) | $text-primary@25%, Gray10@25%, rgba(244,244,244,0.25); | $text-primary@25%, Gray10@25%, rgba(244,244,244,0.25);
$text-placeholder | $text-primary@40%, Gray100@40%, rgba(22,22,22,0.40); | $text-primary@40%, Gray100@40%, rgba(22,22,22,0.40); | $text-primary @ 40%, Gray 10 @ 40%, rgba(244,244,244,0.40); | $text-primary@40%, Gray10@40%, rgba(244,244,244,0.40);

________

Based on conversation in Slack
https://ibm-studios.slack.com/archives/GSCEH4RSP/p1635962656038300

![input-text-style-v2](https://user-images.githubusercontent.com/11670886/144472619-8e73a06b-5e6f-4347-8c0a-eadcb2efca84.png)

**Comment by aagonzales** [comment]
Relate from https://github.com/carbon-design-system/carbon/issues/10004

Other v11 token values that need updates

  | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme
-- | -- | -- | -- | --
$button-disabled | Gray 30 | Gray 30 | Gray 50@ 30% opacity / rgba(141,141,141,0.30); | Gray 50 @ 30% opacity / rgba(141,141,141,0.30);
$text-on-color-disabled | Gray 50 | Gray 50 | $text-on-color @ 25% opacity / rgba(255,255,255,0.25); | $text-on-color @ 25% opacity / rgba(255,255,255,0.25);
$icon-on-color-disabled | Gray 50 | Gray 50 | $icon-on-color @ 25% / rgba(255,255,255,0.25); | $icon-on-color @ 25% / rgba(255,255,255,0.25);

**Comment by Eugeno** [comment]
Where is the correct data, in the table above or in the picture? Percentages differ in several places

**Comment by aagonzales** [comment]
The tables should be correct.

**Comment by aagonzales** [comment]
Ok double checked everything, update the tables and images so they should all have the same values now.

**Comment by Eugeno** [comment]
@aagonzales is it ok that new `$boder-disabled` is more visible (darker on light themes, lighter on dark themes) than `$border-subtle`? It looks strange on the accordion with a disabled item
