### ISSUE TITLE
[Bug]: bx--body--with-modal-open behaviour is incorrect when there are multiple <Modal>s

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon#10051]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.46.0

### Description

The `<Modal>` component has functionality in `componentDidMount`, `componentDidUpdate` and `componentWillUnmount` to add or remove the `.bx--body--with-modal-open` class to the `<body>` element. The idea is that if the `<Modal>` is open (*i.e.* its `open` prop is truthy), the class is added; if it is not open, the class is removed. The purpose of the class seems to be to suppress the `<body>` element's scrollbar and prevent scrolling.

This works fine when there is only one `<Modal>` on the page, but if there are two, it goes wrong. Suppose they are both closed at first. Then the first `<Modal>` opens. It adds the `.bx--body--with-modal-open` class to the `<body>` element. So far so good.

Now suppose the second `<Modal>` re-renders. It doesn't *open* - having two `<Modal>`'s open at the same time is frowned upon, as we know - it doesn't even need to change state or props. It just *re-renders*. This causes the second `<Modal>`'s `componentDidUpdate` to get hit. It discovers that its own `open` prop is closed - still - and it obediently removes the `.bx--body--with-modal-open` class from the `<body>` element... even though the first `<Modal>` is still open and the class should still be there.

In practical terms this has the effect of making a scrollbar on the overall page disappear and reappear at seemingly random times while the first `<Modal>` is open.

### CodeSandbox example

https://codesandbox.io/s/jolly-rui-d3bps?file=/src/index.js

### Steps to reproduce

Observe how the sandbox has one `<Modal>` which is closed, but its `modalHeading` prop is oscillating every few seconds. Meanwhile the other `<Modal>` is open. Notice the flickering scrollbar on the right, and also the class `.bx--body--with-modal-open` being repeatedly added to and removed from the `<body>` element of the demo frame.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by s100** [comment]
Note that any solution to this problem should also be able to handle the (frowned-upon, but entirely likely) case where multiple modals are open at once.

**Comment by tay1orjones** [comment]
[Here's an updated sandbox](https://codesandbox.io/s/dreamy-ishizaka-3v6m9q?file=/src/index.js) that pins the deps to the reported 7.46.0 - I'm unable to replicate the issue though. I see the devtools flagging that body class is being updated, but there's no visual impact of a scrollbar or otherwise.
