### ISSUE TITLE
background-color for select is transparent

### ISSUE THREAD

**Issue by TastyDucks** [carbon-design-system/carbon#10052]
https://github.com/carbon-design-system/carbon/blob/29f7380340f8824887c154a19e538cc8c1c58225/packages/styles/scss/components/select/_select.scss#L213
At least in my testing in Chrome, the transparent color here allows the browser chrome for the default selectlist items to show, rendering it unusable in dark (g90, g100) color themes.
Current behavior (example taken from Pagination component):
![image](https://user-images.githubusercontent.com/15849445/140316184-2d2ca6ac-6d1c-40bf-a6a8-cdbc93d9ce4c.png)
Expected behavior (made by removing the `background-color` property from the SCSS):
![image](https://user-images.githubusercontent.com/15849445/140316221-7f1ef903-3bb5-4ab8-aef3-2f9d534a5c34.png)

**Comment by TastyDucks** [comment]
The theming in my application is set by a `<Theme />` at the top of the DOM. At the moment I am only using the built-in themes, and I switch them out by changing the `theme` prop.

I import all of my CDS styles in SCSS like so:
```scss
@use '@carbon/react/scss/themes';
@use '@carbon/styles/scss/zone';
@use '@carbon/charts/styles-g100';
@use '@carbon/react'; // TODO: to reduce build size, only import specific component styles in the manner of `@carbon/react/scss/components/NAME`
```
Regardless of the theme I use, the background-color for `.cds--select-input` is `transparent`, when it should probably be using a color token. (Perhaps `theme.$background`?)
![image](https://user-images.githubusercontent.com/15849445/140377794-459c5807-3f2d-48c1-94bf-d39e2b8f0247.png)
Thank you for your quick reply and work on CDS as a whole!

**Comment by joshblack** [comment]
Perfect, thanks so much @TastyDucks! Really appreciate this, I'm glad you shared the packages because I totally did not realize you were using the beta 😂 

This is incredibly helpful and we'll definitely make sure this gets addressed 👍

**Comment by tay1orjones** [comment]
Potentially related? https://github.com/carbon-design-system/carbon/discussions/10306
