### ISSUE TITLE
[Bug]: TableToolbarMenu size and color incorrect

### ISSUE THREAD

**Issue by TastyDucks** [carbon-design-system/carbon#10058]
### Package

carbon-components

### Browser

Chrome

### Package version

@carbon/react@0.8.1

### Description

The element does not respect the size constraints when `<TableToolbar size="sm">`, causing the icon to be misaligned:
![image](https://user-images.githubusercontent.com/15849445/140418279-fb8e0654-0816-442b-b11c-2711db2b7457.png)
The parent to the svg element does not have a set `color` and thus the svg `fill` cannot correspond to the current theme:
![image](https://user-images.githubusercontent.com/15849445/140418271-53d369ef-b547-4ec8-88c8-648c1e72ec3e.png)
This should probably be `$icon-01`.

### CodeSandbox example

https://codesandbox.io/s/youthful-driscoll-vbjk5?file=/src/index.js

### Steps to reproduce

1. Using `@carbon/react@0.8.1`, create a TableTooblar with a TableToolbarMenu.
2. Inspect the SVG and note the `fill` property is set to `currentcolor`
3. Inspect the OverflowContainer and note that it does not conform to the height of the containing TableToolbarMenu

The icon fill can be fixed by adding `color: var(--cds-icon-primary)` to the `TableToolbarMenu`, although IMO it would be nice if every icon had the `fill` property defaulting to `$icon-01` instead of needing to inherit that from its parents color.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by TastyDucks** [comment]
Addendum: the scss rules for
```scss
th .cds--table-sort__flex {
    min-height
}

.cds--data-table--sort th, .cds--data-table th[aria-sort] {
    height
}
```
cause sortable headers to break out of the `xs`  TableHeader:
Actual:
![image](https://user-images.githubusercontent.com/15849445/140547982-4bcacf20-0000-4427-b2fe-cfa5746d871f.png)
Expected (with those properties `unset`):
![image](https://user-images.githubusercontent.com/15849445/140548191-e4a1f3e6-2834-4b86-81d0-3d945608047f.png)

**Comment by jnm2377** [comment]
@TastyDucks I'm keeping this PR to the scope of the original issue. If you are seeing another bug, please open an issue so we can track it in our backlog. :) thank you!
