### ISSUE TITLE
[Bug]: ExpandableTile chevron is unbounded

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#10063]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

latest

### Description

The chevron in an ExpandableTile uses an absolute positioning. Since the "position: relative" property was removed from `.bx--tile` in https://github.com/carbon-design-system/carbon/pull/9706, the chevron is now unbounded by its parent container.

### CodeSandbox example

https://codesandbox.io/s/wizardly-kapitsa-q0p8u?file=/src/index.js

### Steps to reproduce

1. Visit the codesandbox
2. Note how the chevron is located at the bottom right of the screen

<img width="1078" alt="Screen Shot 2021-11-06 at 11 29 33 AM" src="https://user-images.githubusercontent.com/10718366/140620200-76aacead-8f7e-474c-9b4c-cedcbb0b9880.png">
![Uploading Screen Shot 2021-11-06 at 11.29.33 AM.png…]()

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
FYI @abbeyhrt
