### ISSUE TITLE
Date picker - custom range focus state issue 

### ISSUE THREAD

**Issue by votiffany99** [carbon-design-system/carbon#10068]
## Overview
Date picker - custom range focus state issue: Currently, the focus (blue border) goes back to the start date after user finishes choosing their end date. 

## Detailed description

What version of the Carbon Design System are you using?
Carbon 10

What did you expect to happen?
Focus should stay on the end date after user chooses the end date 

What happened instead?
The focus goes back to the start date after user finishes choosing their end date

## Steps to reproduce the issue
Using [storybook](https://react.carbondesignsystem.com/?path=/story/components-datepicker--range) component as an example 

1. Select start date (focus starts on start date) 
2. Select end date (focus starts on end date and when end date is selected, focus ends on start date) 

## Additional information
This is the expected behavior after user chooses their start and end date. 

![image](https://user-images.githubusercontent.com/93011195/139329643-1c72df47-9e4d-44c8-b0ce-204f7aa5781a.png)

**Comment by jnm2377** [comment]
Hi @votiffany99 thanks for bringing this issue up. I can see how the focus state ending on the start date can be confusing and inconvenient. Adding this to our backlog, though as it's not breaking any functionality to the component this will likely be a low priority for us right now. If you'd like to see a fix sooner we would welcome a contribution, and would be more than happy to help get you set up! :)
