### ISSUE TITLE
[Bug]: Slider prop value change triggers onChange

### ISSUE THREAD

**Issue by mgolawski** [carbon-design-system/carbon#10065]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.46.0

### Description

The change of prop `value` in `Slider` component, calls `onChange` callback. It should not be called if the value comes from the outside of component, and be triggered only if component changed and needs to notify in parent, same as other components.

[This line](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Slider/Slider.js#L213) is responsible for that behaviour.

It is impossible right now to create a controlled `Slider` component as it was before. Is it possible to hotfix that in a near future?

Thanks.

### CodeSandbox example

https://codesandbox.io/s/pensive-hofstadter-5y41z?file=/src/index.js

### Steps to reproduce

1. Use `Slider` component.
2. Add handle for `onChange` method.
3. Change the passed `value` prop to `Slider` component.
4. Observe the call of `onChange` handler method.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by laurenmrice** [comment]
This will be addressed as a part of our v11 release. We are tracking the v11 component enhancements here https://github.com/carbon-design-system/carbon/issues/9712
