### ISSUE TITLE
[TableToolbarSearch]: handle passed onFocus/onBlur events without breaking expand behavior 

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon#10077]
### Summary

We would like to trigger a search callback to update the table data when the search field is blurred, however, this breaks the automatic expand/contract behavior of the search input when either of these events are passed. It would be nice if the internal onFocus/onBlur would perform their actions and then call the external onFocus/onBlur callbacks afterward.

Example reproduction:
https://codesandbox.io/s/weathered-feather-mh35x?file=/src/index.js

1. Click on the Search icon
2. click outside of the search box

Expected: The search box should collapse

### Available extra resources

Yes, I will happily write the PR if this behavior is acceptable.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Thanks for suggesting and providing CodeSandbox 👍🏾 Its in the proposal pipeline. Check back here for updates in the next week.

**Comment by dakahn** [comment]
This doesn't seem like a proposal for a new feature so much as a bug report, so I went ahead and removed the irrelevant tags 👍🏾

**Comment by theiliad** [comment]
Hi @kevinsperrine 

I found the line of code that might be causing this.

There is an `onBlur` in the component itself that calls `handleExpand`, now when you're passing your own `onBlur`, it's obviously not calling that.

I think the ideal behaviour I'd like to see is that **your** onBlur is called by the component, passing the `handleExpand` as some kind of argument/parameter (or some other way of giving you access to it, maybe through `ref`s?) where you can call it

https://github.com/carbon-design-system/carbon/blob/934d21f8a026d631e40ebde50af36ea814d2a540/packages/react/src/components/DataTable/TableToolbarSearch.js#L114

**Comment by kevinsperrine** [comment]
Thanks, @theiliad. That process makes sense.  I'll be out a lot of this week, but I'll submit a PR for this behavior next week.
