### ISSUE TITLE
How to get started with Carbon for Python Flask application 

### ISSUE THREAD

**Issue by afizs** [carbon-design-system/carbon#1007]
## Detailed description

I am new to Carbon and trying to use Carbon components in my Python Flask pages. I tried using CDN provided in the website, but alignment is not as expected and my page looks ugly now. 

```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Sample Flask</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" type="text/css" href="	https://unpkg.com/carbon-components/css/carbon-components.min.css">
</head>

<body>
        <div class="container">
                <!-- Replace "getting_started" with your code -->
                <div class="demo-content">
                  <a class="bx--link" target="_blank" href="http://www.carbondesignsystem.com/">
                    <h1 class="title">Carbon <br /><span>Design Systems</span></h1>
                  </a>
                  <p>A simple boilerplate for rapid UI prototyping with <a class="bx--link" target="_blank" href="http://www.carbondesignsystem.com/">Carbon</a>        components</p>
            
                </div>

  <script src="https://unpkg.com/carbon-components/scripts/carbon-components.min.js"></script>
  <app-root></app-root>
</body>

</html>
```
Any help will be really appreciated.

**Comment by asudoh** [comment]
Hi 👋 seems that above code does not contain significant content of your application - Do you want to post your application somewhere (unless your application contains confidential information) so people can help?

**Comment by afizs** [comment]
As I mentioned in earlier I just started with Carbon components. I have created a basic html page. I was expecting a clean page, but got page view as below. 

<img width="708" alt="screen shot 2018-08-01 at 5 54 58 pm" src="https://user-images.githubusercontent.com/5618143/43521521-155cad3e-95b4-11e8-8c43-38b3dd86aedd.png">

Here is my entire code: 

flask app.py: 
```
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def hello():
    return render_template('index.html')

if __name__ == '__main__':
    app.run()
```

Index.html:
```
<!doctype html>
<html lang="en">

<head>
  <title>Sample Flask</title>
  <link rel="stylesheet" type="text/css" href="	https://unpkg.com/carbon-components/css/carbon-components.min.css">
</head>
<body>
        <div class="container">
                <div class="demo-content">
                  <a class="bx--link" target="_blank" href="http://www.carbondesignsystem.com/">
                    <h1 class="title">Carbon <br /><span>Design Systems</span></h1>
                  </a>
                  <p>A simple boilerplate for rapid UI prototyping with <a class="bx--link" target="_blank" href="http://www.carbondesignsystem.com/">Carbon</a>        components</p>
            
                </div>

  <script src="https://unpkg.com/carbon-components/scripts/carbon-components.min.js"></script>
</body>

</html>
```
Let me know if you need any further information.

**Comment by asudoh** [comment]
My recommendation from your screenshot is starting with https://github.com/carbon-design-system/carbon-boilerplate, whose live demo can be found at http://carbon-boilerplate.mybluemix.net. Also our [components page](http://www.carbondesignsystem.com/components/overview) has lots of examples, which you may want to check out, too. Hope those helps!

**Comment by afizs** [comment]
I have seen the boilerplate application which is developed using JavaScript. I am not comfortable with Node, React or any JS frameworks. Is there any way to get started with Python web frameworks like Falsk or Django.

**Comment by asudoh** [comment]
From what I see https://github.com/carbon-design-system/carbon-boilerplate/blob/b1dfeac/app/views/home.html#L34-L35, it appears that `carbon-boilerplate` uses just Carbon vanilla JavaScript code and [one line of JavaScript code merely for demo purpose](https://github.com/carbon-design-system/carbon-boilerplate/blob/847911f/app/js/index.js) - Which means that it does not use any JavaScript frameworks, given Carbon vanilla JavaScript code has *no* dependency to any JavaScript frameworks.

In case I have to mention, most web applications we see today, including Carbon-based applications, requires client-side JavaScript code and you'd have no way without it. Hope those help.

**Comment by afizs** [comment]
I tried to open the page(https://github.com/carbon-design-system/carbon-boilerplate/blob/b1dfeac/app/views/home.html#L34-L35) in the browser but still I don't see the style. 
<img width="701" alt="screen shot 2018-08-02 at 2 19 25 pm" src="https://user-images.githubusercontent.com/5618143/43573526-842cecaa-965f-11e8-833d-3189b3d737ed.png">

**Comment by asudoh** [comment]
Looks that Carbon CSS is not applied there, which should be found out with Chrome DevTools, etc. That said, you may want to get help from your close colleagues before coming back here.

**Comment by tbs-heiss** [comment]
Hi, I am trying to get the carbon header to work in Flask with the navigation. Unfortunately the menu items in the header are not displayed correctly. It looks like the styles are not available. However, when I look in the ibm_carbon.css, they are listed there. The rest of the header works.

![image](https://user-images.githubusercontent.com/84387353/119645161-052c0780-be1e-11eb-87d7-cce0981e432a.png)

**Comment by e-monson** [comment]
h
