### ISSUE TITLE
[Feature Request]: add event handler for SideNavMenu expanding 

### ISSUE THREAD

**Issue by tomleah** [carbon-design-system/carbon#10078]
### Summary

It would be desirable to be able to call a function when a SideNavMenu opens or closes.

### Justification

I would like this to be able to show some extra information depending on what SideNavMenu was last "touched". This is specifically useful if you're grouping items and want to give an overview of the groups content.

Its possible to do the following as a workaround, however it goes against the `string` prop type for `title` and therefore can cause errors.

```
<SideNavMenu
  title={(
    <span
      onClick={() => {e.stopPropagation(); myHandler();}
    >
      My group
    </span>
  )}
>
...
</SideNavMenu>
```

### Desired UX and success metrics

Be able to call a function when the the SideNavMenu is opened or closed

### Required functionality

It could be an `onClick` (or similar) prop given to the component. It may be good to know if the click resulted in the menu being expanded or vice versa to use in the function.

`onClick={(expanded) => {...}}`

or `onChange`

`onChange={(expanded) => {...}}`

I think this would be a better DX than allowing objects/components in the `title` prop like the workaround mentioned earlier.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
@tomleah 
> This is specifically useful if you're grouping items and want to give an overview of the groups content
Could you explain a little more about what this means? Maybe provide a concrete example of what you're talking about here. THanks!

**Comment by theiliad** [comment]
> Could you explain a little more about what this means? Maybe provide a concrete example of what you're talking about here. THanks!

Hi @tomleah 👋🏻 
Just checking if you've seen that msg^^

Pls let us know

**Comment by tomleah** [comment]
Hi all, sorry for the delayed response! Thanks for the ping @theiliad 😄 

I've thrown something together on powerpoint, of what I'm trying to achieve overall. I hope it helps...

The idea is the the L0 menu in this case would be a group or category and then the L0 menu items would be resources related to that group/category.

Imagine a category "Horror films" which I could click on and find out more about the category on the right hand side. Then if this category sounds like it would contain the resources Im looking for I can then expand the group. A similar interaction then happens with the L0 menu items, i click them to find more information appears on the right. 

![image](https://user-images.githubusercontent.com/5465397/144899263-2b261ef4-46df-4d75-a3e2-18d1aa21729c.png)

Today the `title` for a `SideNavMenu` must be a string. I would like to be able to click this string without expanding the menu.

I've updated the description as the workaround I do today puts a `e.stopPropagation()` in the onClick to stop the menu from opening.

Let me know if the goal is unclear still, thanks!

**Comment by sstrubberg** [comment]
hey @tomleah, first off, apologies for the lack of communication here and thank you for brining up this feature request. 
 Unfortunately, due to constraints around our roadmap and available resources, we won't be able to take this work on. We are happy to accept a PR against it though. If you interested in contributing, let me know. Happy to re-open the issue!
