### ISSUE TITLE
[Bug]: Boolean type data shown as blank in the table cell

### ISSUE THREAD

**Issue by haku1bai** [carbon-design-system/carbon#10073]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.33.0

### Description

When I use some boolean data in my dataset and trying to show it in the data table, it shows nothing (blank) in the data cell. I expect to show 'true' or 'false' in the table instead.

please look at the following sandbox example, I use boolean data for column 'rule', but shows nothing.

### CodeSandbox example

https://codesandbox.io/s/epic-sunset-2gvjj?file=/index.js

### Steps to reproduce

Use a data set which include at least one column of boolean data.

Pass it as the rows to the data table component and watch.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
Nice avatar! Booleans wont be rendered by React. You'll need to be converted into a string 👍🏾 Closing this as solved. Let me know if there's something I missed and we can reopen.
