### ISSUE TITLE
[Feature Request]: Full width for text in accordion

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon#10083]
### Summary

We are using accordion in our AEM Marketing site, specifically for the Privacy Office pages. One minor issue is that the text inside of an accordion is not the full width of the accordion.
![image](https://user-images.githubusercontent.com/47429622/141159379-d87c4976-b556-4594-b6c4-615d6bf8ce5c.png)

https://www.carbondesignsystem.com/components/accordion/style/#margin-right
The margin-right is intended from the carbon core styles. But having the text fill the full width of the accordion is a feature we need for the Privacy Office pages.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Thanks for proposing a new feature for accordion. We review new proposals once a week. Check back here for more information 👍🏾

**Comment by dakahn** [comment]
@carbon-design-system/design any insight into the right margin in accordion?

**Comment by aagonzales** [comment]
The margin-right in accordion is to prevent excessive line lengths on the page which can cause legibility issues. We can maybe look refining it across widths, but the main goal of it is to prevent something like this happening (this is a bad reading experience) : 

![image](https://user-images.githubusercontent.com/11670886/142915176-39999768-cdae-47ae-9023-43b7f876988c.png)

**Comment by aagonzales** [comment]
Were are accepting this proposal but this issue needs a design review from carbon before any development can happen on it. Full width will _not_ be happening across all sizes (definitely not across the largest) but a new spec needs to be generated).

**Comment by sstrubberg** [comment]
hey @EAVilleda, after speaking with the team this morning during Backlog Cleaning, we decided that introducing the capability through the design system would introduce readability issues for the those Accordions. We would, perhaps, entertain an allowance based on a more full design spec when/if you'd like to show us one. In the meantime, if you're set on full-width, you can always override the CSS as you wish.
