### ISSUE TITLE
[Bug]: g10 theme button-secondary color change in new @carbon/styles intentional?

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon#10104]
### Package

@carbon/styles

### Browser

Chrome

### Package version

v0.9.0

### Description

While working on updating our scss for the `carbon-addons-iot-react` library, I noticed the default color for the secondary-button in the g10 theme in the @carbon/styles package is now #6f6f6f (gray60) when previously it was #393939 (gray80). Unless, I'm setting the configs incorrectly--which is possible all the sass modules stuff is brand new to me.

Commit where set:
https://github.com/carbon-design-system/carbon/commit/cbb8fa92200d5d8bc8b063026ba99398153f5b19#diff-23517302b34a4ec6176f21c6d14390fa3d5c71f48a53a6877b23e0191ce068a3R65

Currently in carbon-components it's using $interactive-02 (https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/button/_button.scss#L48) which is gray80 (https://github.com/carbon-design-system/carbon/blob/main/packages/themes/src/g10.js#L47)

### Screenshots

<img width="309" alt="Screen Shot 2021-11-12 at 12 01 59 PM" src="https://user-images.githubusercontent.com/609466/141505818-f1475c0c-5668-4496-b0a5-8dc8f503cfba.png">

### Steps to reproduce

https://codesandbox.io/s/priceless-gwen-cu5bf?file=/src/app.scss

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Good eye @kevinsperrine! Thanks for catching this.

**Comment by tay1orjones** [comment]
While we're in here making this fix it'd be good to double check the values for the other component tokens alongside this one.

**Comment by aagonzales** [comment]
Looks like the values for Gray 10 theme and the Gray 90 theme got mixed up.

![image](https://user-images.githubusercontent.com/11670886/141839484-06fae70e-73da-4f8b-b0e9-271e17325a16.png)
