### ISSUE TITLE
[Bug]: Not getting the selected value from row in datatable in React

### ISSUE THREAD

**Issue by midhun8454** [carbon-design-system/carbon#10101]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.25.0

### Description

Am just exploring react with carbon and got stuck with some trigger event. Here is my piece of code (ChildComponent)
```js
<DataTable rows={rows} headers={headers} size='tall' zebra>
      {({ rows, headers, getTableProps, getHeaderProps, getRowProps }) => (
        <Table {...getTableProps()}>
          <TableHead>
            <TableRow>
              {headers.map((header, i) => (
                <TableHeader key={i} {...getHeaderProps({ header })}>
                  <React.Fragment>{header.header}</React.Fragment>
                </TableHeader>
              ))}
            </TableRow>
          </TableHead>
          <TableBody>
            {rows.map((row, j) => (
              <div key={row.id}>
                <TableRow key={row.package} {...getRowProps({ row })}>
                  <>
                    {row.cells.map((cell) => (
                      <>
                        <TableCell key={cell.id}>{cell.value}</TableCell>
                      </>
                    ))}
                    <Button color='primary' id={row.package} onClick={this.props.redirectToDesigner(row.package)}>
                      Open
                    </Button>
                  </>
                </TableRow>
                <br />
              </div>
            ))}
          </TableBody>
        </Table>
      )}
    </DataTable>
```

This lies on child component and Parent component looks like below

```js
import React from "react";
import ChildComponent from "./ChildComponent";

class ParentComponent extends React.Component {
  redirectToDesigner = (id) => {
    alert(1);
    console.log("TRYYYY", id);
  };
  render() {
    return <ChildComponent redirectToDesigner={this.redirectToDesigner} />;
  }
}
export default ParentComponent;
```

Am getting the alert and the console as undefined for some reason

Here you can see one onclick event , its triggering but am not getting value(row.id) from it. I need the value for further development.

### CodeSandbox example

https://codesandbox.io/s/gifted-shirley-t8zcc?file=/src/index.js:63-240

### Steps to reproduce

Click on open button from any row ans its not poping up with name , coming as undefined

```js
<DataTable rows={rows} headers={headers} size='tall' zebra>
      {({ rows, headers, getTableProps, getHeaderProps, getRowProps }) => (
        <Table {...getTableProps()}>
          <TableHead>
            <TableRow>
              {headers.map((header, i) => (
                <TableHeader key={i} {...getHeaderProps({ header })}>
                  <React.Fragment>{header.header}</React.Fragment>
                </TableHeader>
              ))}
            </TableRow>
          </TableHead>
          <TableBody>
            {rows.map((row, j) => (
              <div key={row.id}>
                <TableRow key={row.package} {...getRowProps({ row })}>
                  <>
                    {row.cells.map((cell) => (
                      <>
                        <TableCell key={cell.id}>{cell.value}</TableCell>
                      </>
                    ))}
                    <Button color='primary' id={row.package} onClick={this.props.redirectToDesigner(row.package)}>
                      Open
                    </Button>
                  </>
                </TableRow>
                <br />
              </div>
            ))}
          </TableBody>
        </Table>
      )}
    </DataTable>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@midhun8454 You could use an arrow function to pass along the additional parameters. The `onClick` should pass an event as the first argument, you can add others as you see fit. [Here's a codesandbox example](https://codesandbox.io/s/prod-currying-bntjz?file=/src/components/CustomDataTable.js:7992-8308)

```js
<Button 
  color='primary' 
  id={row.package} 
  onClick={(event, rowPackage = row.package) => {this.props.redirectToDesigner(rowPackage)}}
>
  Open
</Button>
```

Another option - If you know the row data you'd like to pass along ahead of time and aren't interacting with any outside state, you can include components/nodes in the initial data passed to the table. [Here's an example](https://codesandbox.io/s/prod-currying-bntjz?file=/src/table-data.js:705-922) from the same codesandbox.

**Comment by midhun8454** [comment]
@tay1orjones  i had used same ( onClick={(event, rowPackage = row.package) => {this.props.redirectToDesigner(rowPackage)}} ) and updated sandbox , but still am getting undefined.

**Comment by tay1orjones** [comment]
> Here you can see one onclick event , its triggering but am not getting value(row.id) from it. I need the value for further development.

@midhun8454 Try double checking what data is available in the `row` object. I think you'll have to use the `value` from the first cell to get the `package`. You can view the structure of `row` by using `JSON.stringify()`. Here's a fork of your codesandbox passing the `row.id` through to the `alert()`: https://codesandbox.io/s/trusting-kirch-xeunl?file=/src/ChildComponent.js:2150-2218
