### ISSUE TITLE
[Bug]: HeaderMenu with `isCurrentPage` does not have a pointer cursor

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#10109]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v10.48.0

### Description

I'm expecting to see a "pointer" cursor when hovering over a `<HeaderMenu isCurrentPage>`.

Instead, it shows the default cursor, leading me to believe that it is not interactive.

### CodeSandbox example

N/A

### Steps to reproduce

Visit https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation

https://user-images.githubusercontent.com/10718366/141595880-122ce1d0-4f6a-4126-bcd6-dc67ab5b1e84.mov

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for the report @metonym. This was a small detail missed in https://github.com/carbon-design-system/carbon/pull/9785
