### ISSUE TITLE
pointing to font @ latest causes errors

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#1011]
## Detailed description

We use carbon in our application. We keep carbon locked to a specific version so that we can control when we get updates. Part of the testing we do involves visual regression testing (vrt), which can catch the most minor differences a styling change might have. We noticed our vrt tests we being inconsistent, but almost always due to typography. This error is caused by a non-locked version of plex.

in [_css--plex-core.scss](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_css--plex-core.scss) you create `$font-path` with this line:

`$font-path: 'https://unpkg.com/carbon-components@latest/src/globals/fonts' !default;`

But because you choose to use `@latest`, then any application that ingests Carbon is forced to always use the _latest_ version of plex. Recently there was an update to plex, but not an update to carbon, and now a majority of our vrt tests are failing.

## Additional information

![screen shot 2018-08-02 at 9 31 17 am](https://user-images.githubusercontent.com/216931/43586905-dd4948d4-9636-11e8-91c1-3aea5f815b40.png)
![screen shot 2018-08-02 at 9 32 05 am](https://user-images.githubusercontent.com/216931/43586932-f3e00dd0-9636-11e8-8ea3-cf071faaafa5.png)

## Solution

Lock your `$font-path` to a specific version of plex

**Comment by asudoh** [comment]
Hi @scottnath FWIW we do *not* recommend using the default `$font-path` in any production application, that default one is solely for demo/evaluation purposes. We instead recommend that hosting the Plex fonts in their CDN and adjust `$font-path` accordingly, which I know many Carbon consumers do. Hope this helps!

**Comment by joshblack** [comment]
As an interim solution, would it help to re-write `font-path` to a versioned version of unpkg? Would echo @asudoh's comment in that usage of unpkg is definitely not intended, but I understand that is not documented anywhere at the moment which is on us.

Let us know if you have any thoughts/suggestions on how to proceed! I think tying it to versions can get complicated given our reliance on `semantic-release`. This is also compounded by the fact that the default font-path is meant for development rather than for production environments. Will definitely take a note to call this out in our getting started docs that we're working on 👍

**Comment by scottnath** [comment]
The usage confusion is due to needing an example of what proper usage would look like. The `unpkg` url for the `@latest` plex font is part of your [minified css file on unpkg](https://unpkg.com/carbon-components@9.7.0/css/carbon-components.min.css). It's also imported into your [primary sass file](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/styles.scss#L24), which receives [plex via a sub-import](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_css--font-face.scss#L4). Both of these fonts files are pulling `@latest` fonts from unpkg. The carbon site [mentions that css--font-face is turned off by default](http://carbondesignsystem.com/getting-started/developers/vanilla), but it doesn't say why.

For a fix, my suggestion would be to target your font references to a specific version. This would allow ingesting applications to know they'll always get the same thing as long as they specify a specific version of Carbon. This is especially important for any apps that are pulling in your unpkg-based css files, as they may rely on a specific Carbon version for consistency, but their interface might break with a font change (it broke system wide for us, the above pics are 3 of 1200+).

For the fix on our side, thanks for the suggestion, we'll change `font-path`!

**Comment by joshblack** [comment]
I think @asudoh had the idea to warn out in console if the default value is used. That way we don't break anyone using it, but it can flag improper usage and provide guidance for how to rectify 👍
