### ISSUE TITLE
[Bug]: Form with FileUploader in a TableExpandedRow causing large empty space below page

### ISSUE THREAD

**Issue by pbp-at-ibm** [carbon-design-system/carbon#10116]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

v10.46.0, v7.46.0

### Description

When using a FileUploader inside a Form that is placed within a TableExpandedRow, the page has a large amount of empty space beneath the page content.

Here is an image demonstrating the empty space beneath our Carbon DataTable:

<img width="600" alt="Empty space below page" src="https://user-images.githubusercontent.com/94187356/141802891-effdbf3c-2cdf-4a7c-b1e8-dd859652b770.png">

After investigating the issue, it seems to be a CSS problem with a class named `bx--visually-hidden`. After setting `display: none`, or changing `position: absolute` to `position: relative`, the large amount of space disappeared without any other obvious changes to the page visuals.

Here is an image demonstrating the bottom of our DataTable after making this change:

<img width="600" alt="Empty space after fix" src="https://user-images.githubusercontent.com/94187356/141804863-3f897f13-aa8f-44b3-b031-96c71a805139.png">

In our app, the empty space exists whether you expand any rows or not. In the CodeSandbox example provided, the empty space below the DataTable is not that large until you expand one of the top three rows, at which point you can see that you can scroll down and see the empty space.

### CodeSandbox example

https://codesandbox.io/s/gifted-sara-00019?file=/src/index.js

### Steps to reproduce

1. You are able to scroll to the bottom of the page, despite the content not taking up the full height of the window.
2. Expand any row (except the last), and scroll to the bottom of the page to see a large amount of empty space below.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by pbp-at-ibm** [comment]
Forgot to add that `bx--visually-hidden` has `position` set to `absolute` in `carbon-components/scss/globals/scss/_css--helpers.scss`.

**Comment by sstrubberg** [comment]
Thank you for submitting this issue. We have triaged it and will be weighing it's priority against competing workstreams. Feel free to make a PR against this and we'll be happy to review it.
