### ISSUE TITLE
[Bug]: carbon-components-react 7.48 has next tag on npm not latest

### ISSUE THREAD

**Issue by salvoravida** [carbon-design-system/carbon#10119]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.48

### Description

[Bug]: carbon-components-react 7.48 has next tag on npm not latest

### CodeSandbox example

https://www.npmjs.com/package/carbon-components-react

### Steps to reproduce

https://www.npmjs.com/package/carbon-components-react

<img width="807" alt="Schermata 2021-11-16 alle 02 07 33" src="https://user-images.githubusercontent.com/20126259/141877332-dcaefae6-47ee-4f7c-b311-3b21d5ed9ad9.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @salvoravida! 👋  Thanks so much for taking the time to make this issue.

For background, we changed the `latest` tag when we received notice about a regression for Tabs in Safari last Friday. There is a PR with a fix over in: https://github.com/carbon-design-system/carbon/pull/10120 for this and we'll publish a hotfix and tag that as latest when it's merged.

Hope this helps!
