### ISSUE TITLE
Content Switcher: Adds micro-interaction 

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/carbon#10117]
### Summary

Our current Content switcher does not have motion. We will like to add the "Fade up" motion into the content switcher. 

🔗[Link to prototype](https://codesandbox.io/s/content-switcher-motion-carbon-vanilla-on16c?file=/src/index.js)🔗

https://user-images.githubusercontent.com/12755042/141836505-6705fc12-69db-4e45-9f1c-916a81ab06f2.mov

Motion designer contacts on Slack:
- Andrew Smith @ampersandrew

### Justification

As we all know, motion in our product gives the user a sense of control, engages the user, it allows for fluid flows which result in a better user experience. It is also a strong indicator that an action is in progress. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by johnbister** [comment]
@AlexanderMelox Thanks for submitting! The motion is nice and crisp.  I'll show this at Carbon's next design critique and see what the larger group thinks.  I'll follow-up soon and thanks again!

**Comment by AlexanderMelox** [comment]
@johnbister thank you for the speedy response. Meantime I will post the PR for the changes.

**Comment by AlexanderMelox** [comment]
PR for this issue https://github.com/carbon-design-system/carbon/pull/10148
