### ISSUE TITLE
Grouped Bar Graph Example is broken

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1012]
Grouped Bar Graph example isn't working on the website/codepen

https://codepen.io/team/carbon/pen/QaJYpg?editors=0010
http://www.carbondesignsystem.com/data-vis/bar-graph/code
<img width="872" alt="screen shot 2018-08-02 at 2 20 43 pm" src="https://user-images.githubusercontent.com/2753488/43605823-43b87dd8-965f-11e8-8e59-b953a7070505.png">

**Comment by shinytoyrobots** [comment]
Should this be in components repo or in one of the data viz repos, @alisonjoseph?

**Comment by alisonjoseph** [comment]
This lives in a codepen not any of the repos, so its probably fine where it is 🤷‍♀️
