### ISSUE TITLE
[Bug]: Checkbox onClick event firing twice not allowing checkboxes to be selected

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon#10122]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v10.48.0

### Description

The onClick event is being fired on both the label and the input causing the checkbox to check and immediately uncheck.

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-checkbox--playground
https://codesandbox.io/s/cool-lederberg-qwoc1?file=/src/index.js

### Steps to reproduce

Try to select a checkbox in the playground. https://react.carbondesignsystem.com/?path=/story/components-checkbox--playground

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hey @kevinsperrine! Sorry you ran into this. For implementing a controlled checkbox, the `onChange` is the intended way to catch updates and set local state.

```jsx
function ExampleComponent() {
  const [isChecked, setIsChecked] = useState(false);
  return <Checkbox checked={isChecked} onChange={setIsChecked} />;
}
```

The `onClick` was added recently in https://github.com/carbon-design-system/carbon/pull/9827 and admittedly makes the api more confusing for `Checkbox`. The intent of `onClick` was to provide a handler to control the bubbling of click events from `Checkbox` without having to implement your own wrapper component/element. 

I think this is something that would benefit being documented more thoroughly in the storybook. I'll put together a PR.

**Comment by bjornalm** [comment]
@tay1orjones or @sstrubberg
Can you reopen this one? The additional event from the click is still causing problems even when using `onChange` if the wrapping element also needs a click event. See https://codesandbox.io/s/stupefied-torvalds-cin6o?file=/src/index.js

In order to work around this I have to add an `onClick` handler to the Checkbox and call `stopPropagation` on the event just to stop the wrapping element from also firing twice.

**Comment by tay1orjones** [comment]
@bjornalm Sorry for the hassle with this. I think we can mirror Checkbox to have parity with recent changes to InlineCheckbox https://github.com/carbon-design-system/carbon/pull/10151 and only allow click events to propagate from the `input` and not the `label`.
