### ISSUE TITLE
[Question]: Carbon Datatable need value thats not present in any cells inside table , but need value for onclick

### ISSUE THREAD

**Issue by midhun8454** [carbon-design-system/carbon#10137]
### Question for Carbon

Guys,

I am having carbon datatable with one cell , that is name(package)

Here is working **SANDBOX URL** : **https://codesandbox.io/s/practical-cloud-5gqfu?file=/src/index.js** 
( when u click on open button , i need both name and type)

This is my data

`    const data = [
      {
        package: "complex__1.0",
        type: "assembly",
        lastModified: "2021-11-04T18:55:44.885Z"
      },
      {
        package: "core__1.0",
        type: "assembly",
        lastModified: "2021-11-04T18:55:44.885Z"
      },
      {
        package: "data-center__1.0",
        type: "flow",
        lastModified: "2021-11-04T18:55:45.309Z"
      },
      {
        package: "ecp__1.0",
        type: "resource",
        lastModified: "2021-11-04T18:55:46.245Z"
      }
    ];`
And this is my header(displaying only package
`const headers = [
      {
        key: "package",
        header: "Name"
      }
    ];`

i have an open button , when you click on open button , i need both package and TYPE (which am getting as undefined) and am no where showing type in my table ,as i dont want.only name is enough in table.

please find below the entire code `import React from "react";
import {
  Button,
  DataTable,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell
} from "carbon-components-react";
class ChildComponent extends React.Component {
  render() {
    const data = [
      {
        package: "complex__1.0",
        type: "assembly",
        lastModified: "2021-11-04T18:55:44.885Z"
      },
      {
        package: "core__1.0",
        type: "assembly",
        lastModified: "2021-11-04T18:55:44.885Z"
      },
      {
        package: "data-center__1.0",
        type: "flow",
        lastModified: "2021-11-04T18:55:45.309Z"
      },
      {
        package: "ecp__1.0",
        type: "resource",
        lastModified: "2021-11-04T18:55:46.245Z"
      }
    ];
    const rows = data.map(function (list, index) {
      const min = 1;
      const max = 100;
      const rand = min + Math.random() * (max - min);
      list.id = rand;
      return list;
    });

    console.log(`rows:`);
    console.log(rows);

    const headers = [
      {
        key: "package",
        header: "Name"
      }
    ];
    return (
      <div>
        {" "}
        <DataTable rows={rows} headers={headers} size="tall" zebra>
          {({ rows, headers, getTableProps, getHeaderProps, getRowProps }) => (
            <Table {...getTableProps()}>
              <TableHead>
                <TableRow>
                  {headers.map((header, i) => (
                    <TableHeader key={i} {...getHeaderProps({ header })}>
                      <React.Fragment>{header.header}</React.Fragment>
                    </TableHeader>
                  ))}
                </TableRow>
              </TableHead>
              <TableBody>
                {rows.map((row, j) => (
                  <div key={row.id}>
                    <TableRow key={row.package} {...getRowProps({ row })}>
                      <>
                        {row.cells.map((cell) => (
                          <>
                            <TableCell key={cell.id}>{cell.value}</TableCell>
                          </>
                        ))}
                        <div>{/* <div>{JSON.stringify(row)}</div> */}</div>
                        <Button
                          color="primary"
                          id={row.package}
                          onClick={() =>
                            this.props.redirectToDesigner(row.cells[0].value)
                            // need type value as well along with name
                          }
                        >
                          Open
                        </Button>
                      </>
                    </TableRow>
                    <br />
                  </div>
                ))}
              </TableBody>
            </Table>
          )}
        </DataTable>
      </div>
    );
  }
}
export default ChildComponent;
`

Here is working **SANDBOX URL** : **https://codesandbox.io/s/practical-cloud-5gqfu?file=/src/index.js** 
( when u click on open button , i need both name and type)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @midhun8454! 👋  If I understand correctly, you may need to use the value of the cell to look up the value in your `data` array. You can then use that value in the `redirectToDesigner` prop callback.

Here's a quick example that I put together based on your demo: https://codesandbox.io/s/withered-field-86uuf?file=/src/ChildComponent.js Let me know if it helps!

**Comment by midhun8454** [comment]
@joshblack  Thanks a lot for the speedy reply . Much appreciated.. I am closing the issue
