### ISSUE TITLE
DataTableSkeleton highlights row on hover

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1013]
@scottdickerson commented on [Thu Aug 02 2018](https://github.com/IBM/carbon-components-react/issues/1153)

## Detailed description

> Describe in detail the issue you're having.
The DataTableSkeleton highlights rows if you hover over them with your mouse.  I don't think we want to imply that the Skeleton Table is interactable.
> Is this a feature request (new component, new icon), a bug, or a general issue?
bug.  
> Is this issue related to a specific component?
DataTableSkeleton
> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
6.18
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
Simply hover over the DataTableSkeleton component

https://codesandbox.io/s/zw5p9ynrzl

---

@asudoh commented on [Thu Aug 02 2018](https://github.com/IBM/carbon-components-react/issues/1153#issuecomment-410092127)

@aagonzales @alisonjoseph Any thoughts on this topic...? Thanks!

---

@alisonjoseph commented on [Thu Aug 02 2018](https://github.com/IBM/carbon-components-react/issues/1153#issuecomment-410097740)

This is a bug, it shouldn't have a highlight on hover color. I'm moving this to the carbon-components repo since it is a css issue.

**Comment by alisonjoseph** [comment]
Looks like data table skeleton was missed when the color updates were made with `v9`

**Comment by aagonzales** [comment]
Agreed DataTable skeletons should NOT have a row highlight on hover.
