### ISSUE TITLE
I tried this solution and it does not work. Tried different versions on react-router-dom and the same issue. If I applied this fix I get

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#10138]
I tried this solution and it does not work. Tried different versions on react-router-dom and the same issue. If I applied this fix I get

  Line 20:29:  Parsing error: Unexpected token

  18 |         <SideNav aria-label="Side navigation" expanded={isSideNavExpanded} >
  19 |             <SideNavItems>
> 20 |                 <SideNavLink<LinkProps> element={NavLink} to={`Test`}>Test</SideNavLink>

_Originally posted by @GerhardMareeSMS in https://github.com/carbon-design-system/carbon/issues/5671#issuecomment-972968900_

**Comment by joshblack** [comment]
Hi there @GerhardMareeSMS! 👋  For issues or bug reports, it helps us out a ton to fill out a CodeSandbox: https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and provide some steps to reproduce. Once you share a link, I can see what's going on 👀

**Comment by GerhardMareeSMS** [comment]
I have created a sample to reproduce the error

https://codesandbox.io/s/sparkling-tdd-t2nzz

**Comment by GerhardMareeSMS** [comment]
I deleted my .eslintrc.yaml file and this resolved the issue
