### ISSUE TITLE
[Bug]: DatePicker range with calendar does not call onChange after blurring End date input

### ISSUE THREAD

**Issue by mgolawski** [carbon-design-system/carbon#10144]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.47.2

### Description

The DatePicker component does not trigger `onChange` event when we manually changes the second date input. However it does trigger it for the first input. It should behave consistent for both of them.

### CodeSandbox example

https://codesandbox.io/s/muddy-smoke-tq4gc?file=/src/index.js

### Steps to reproduce

1. Change the value in Start Date input
2. Observe the `onChange` callback triggered from `DatePicker` component.
3. Change the value in End Date input
4. The `onChange` callback does not trigger.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@mgolawski I'm having a hard time reproducing the issue. Looking at the codesandbox you provided I'm seeing `onChange` fire when the value changes in Start Date and End Date inputs. It also fires when focus moves away from the inputs. Could you share more info on how to reproduce? 


https://user-images.githubusercontent.com/3360588/142913429-092b8f17-4a82-4863-b37c-298c8681d3f5.mov

**Comment by tay1orjones** [comment]
I'm going to close this out as it's been over a couple weeks without more info. Please reach out if it needs to be reopened!
