### ISSUE TITLE
[Question]: How to set the theme of a single component or a single page？

### ISSUE THREAD

**Issue by liliangbo** [carbon-design-system/carbon#10158]
### Question for Carbon

How to set the theme of a single component or a single page？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @liliangbo! 👋 

This will be a feature in our v11 release that's slated for next year (Q1 2022) as we transition our tokens to be CSS Custom Properties. In v10, this is not currently available.

I hope this helps, let me know if you have any questions!
