### ISSUE TITLE
[Bug]: The dependencies of@carbon/icons-react include @carbon/icon-helpers@^10.25.0 which can't be found.

### ISSUE THREAD

**Issue by baoyuzhang** [carbon-design-system/carbon#10157]
### Package

@carbon/icons-react

### Browser

Chrome

### Package version

v10.43.0

### Description

The dependencies include @carbon/icon-helpers@^10.25.0 which can't be found. Version 10.42.0  has the same bug.

### CodeSandbox example

https://codesandbox.io/s/distracted-resonance-jz9vt?file=/package.json

### Steps to reproduce

Look at the dependencies in https://web.npm.alibaba-inc.com/package/@carbon/icons-react/v/10.43.0.
The latest version of @carbon/icon-helpers is 10.24.0. 
https://web.npm.alibaba-inc.com/package/@carbon/icon-helpers

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@baoyuzhang `@carbon/icon-helpers` v10.25.0 was [published to npm](https://www.npmjs.com/package/@carbon/icon-helpers) a month ago. Are you using an internal/enterprise instance of npm? It may need to be updated with the latest packages on public npm.

**Comment by baoyuzhang** [comment]
Sorry，it is the problem of our enterprise instance of npm. It has been updated. Thank you very much~
