### ISSUE TITLE
[a11y]: The 'headers' attribute value "expand" does not reference a valid 'id' in this document

### ISSUE THREAD

**Issue by betty7zhang** [carbon-design-system/carbon#10167]
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

v7.48.1

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker - Latest Deployment

### Description

The 'headers' attribute should refer to a valid cell in the same table. The 'headers' attribute specifies one or more header cells related to a table cell in a complex table. It has no visual effect on the table, but it provides a programmatic way for assistive technology such as screen readers to describe visual relationships between header and data cells. When a table has multi-level headers, it can become difficult to convey which header text applies to any one cell using only elements and 'scope' attributes. The 'headers' attribute allows for the concatenation of multiple text into an accurate descriptor for an individual data cell.

### CodeSandbox example

https://cloud.ibm.com/unifiedsupport/supportcenter

### Steps to reproduce

1. Open https://cloud.ibm.com/unifiedsupport/supportcenter
2. Login with IBM ID & password
3. Click View all
4. Check accessibility

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/43159536/143194066-3b7b2fb8-d4f7-43f7-a1bc-919da27363c8.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Looks like there was a fix contributed for this! Closing since it was resolved in #10214

**Comment by TannerS** [comment]
Let me take a look, the issue was fixed when passing in the proper props but i think a prop was missed in the story book demo

**Comment by TannerS** [comment]
@tay1orjones @betty7zhang here is a fix https://github.com/carbon-design-system/carbon/pull/10547/files
