### ISSUE TITLE
[Feature Request]: Column resizing support for Data Table

### ISSUE THREAD

**Issue by nikhil-isaac** [carbon-design-system/carbon#10166]
### Summary

Carbon data table currently does not all us to control the column width.
The column width needs to be resizable, so that the user can expand the column width for columns they want to expand and shrink the column width for columns they want to shrink. As shown in the video below.
![column-resizing](https://user-images.githubusercontent.com/37073895/143187622-b078fbc4-83a7-4cdb-9da7-640cfc1953f2.gif)

### Justification

User gets a better visualization of their data by expanding those columns which are very important to them and shrinking those which are not so important to them. Especially in cases when columns with additional information is taking up more space/grabbing more attention than the columns with primary/critical information.

### Specific timeline issues / requests

Asap, required in multiple places and products in Cloud Pak for Data

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by abbeyhrt** [comment]
Some relevant background info: 
https://github.com/carbon-design-system/carbon/issues/4751
https://github.com/carbon-design-system/carbon/pull/5084
