### ISSUE TITLE
[Feature Request]: To have carbon style tooltip for OverflowMenu icon

### ISSUE THREAD

**Issue by jillyj** [carbon-design-system/carbon#10173]
### Summary

Currently we only can set "iconDescription" to see the browser style tooltip when hovering on the overflowMenu icon. However, if we have more icon buttons with carbon tooltip, the hovering tooltip behavior of the OverflowMenu is not consistent with others. 

If we put render function in "renderIcon" prop to render "IconButton" or "IconTooltip", both of them introduce the "button in button" warnings in console.

**Current:**
![image](https://user-images.githubusercontent.com/47232763/143544825-199db126-7088-4759-a680-e541eb5479cc.png)

**Expect:**
![image](https://user-images.githubusercontent.com/47232763/143544945-c08e6c54-10b0-412d-a968-3f2f3bd51486.png)

![image](https://user-images.githubusercontent.com/47232763/143544894-771dc4f9-f079-401a-a13c-15e495c655b1.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jnm2377** [comment]
Hi @jillyj thanks for opening this issue. We're going to use https://github.com/carbon-design-system/carbon/issues/9208 as the umbrella issue for adding tooltip to components, so I'm going to close this issue. You can check the other issue for updates going forward. :)
