### ISSUE TITLE
[Bug]: Tag component doesn't respect custom theme colours

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#10174]
### Package

carbon-components

### Package version

10.48.0

### Description

I'm using carbon-components-react, but I doubt that really matters given that this is an issue with styling…
We are using two switchable themes based on two of your light/dark internal ones, and I just cannot convince the `Tag` component to respect our colours without going for dirty hacks (overwriting your styling in our thin wrapper or forking of the component code).

It seems to me that the issue is in the fact that the component doesn't use semantic colour variables from the global theme map, but instead has its own internal map of colours for your internal themes.

```scss
$tag-colors: (
  /// …trimmed for brevity
  'tag-hover-warm-gray': (
    fallback: $carbon__warm-gray-30,
    values: (
      (
        theme: $carbon--theme--white,
        value: $carbon__warm-gray-30,
      ),
      (
        theme: $carbon--theme--g10,
        value: $carbon__warm-gray-30,
      ),
      (
        theme: $carbon--theme--g90,
        value: $carbon__warm-gray-70,
      ),
      (
        theme: $carbon--theme--g100,
        value: $carbon__warm-gray-70,
      ),
      (
        theme: $carbon--theme--v9,
        value: $carbon__warm-gray-30,
      ),
    ),
  ),
);
```

### CodeSandbox example

---

### Steps to reproduce

---

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @jubiko! Thanks for making this issue! You’re spot on that you can't right now override those values right now without dirty hacks like you said. In v11, this will be supported by default but in v10 something we can do is make that `$tag-colors` variable `!default` in sass so that you are then able to override it with your own custom component tokens.
