### ISSUE TITLE
[Bug]: Volume icons potentially missing "Volume on"

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon#10180]
### Package

carbon-components

### Browser

Chrome

### Package version

carbondesignsystem.com

### Description

In the icon library, the set of Volume icons provide a number of states. However the mate for Volume mute (which could be "Volume mute" or "Volume on") does not seem to exist.

It is possible to use the "Volume up" icons for this, and maybe that is the intent. I'm not sure how it is implemented on any composite media controller, but wanted to flag the potential gap in the icon library.

### Screenshots

![image](https://user-images.githubusercontent.com/14298245/143627290-af5f1f05-4cb9-41f3-8960-79fa5b175f8d.png)

### Steps to reproduce

Navigate to https://www.carbondesignsystem.com/guidelines/icons/library/ and choose Controls from the dropdown menu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
cc @conradennis @laurenmrice if you all have a sec to weigh in 👀

**Comment by jnm2377** [comment]
Hey @mbgower thanks for bringing this up. The intent for unmuted volumed is to use `VolumeUp`. 👍🏽 Going to close this issue for now, but we can re-open if design wants to add any other volume icons.
