### ISSUE TITLE
Tooltip child div's getting overridden with selector css definition

### ISSUE THREAD

**Issue by vishalpurandare** [carbon-design-system/carbon#1018]
## Detailed description

Using:
`import { Tooltip } from 'carbon-components-react';`

We are rendering child div inside Tooltip like below:

```
        <Tooltip
            triggerClassName={styles.trigger}
            triggerText={someText}
            showIcon={false}
          >
            <div className={styles.myCustomStyles}>
              {someStuff()}
            </div>
          </Tooltip>
```

The CSS for div element will be overridden with below:
```
.bx--tooltip div {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: justify;
    justify-content: space-between;
    -ms-flex-align: end;
    align-items: flex-end;
    margin-top: 1rem;
}
```

This will override all the divs inside **bx--tooltip** which causes problems. Ideally, the consumer should have those definitions for the divs or any other element.

> Is this issue related to a specific component? 
Tooltip from carbon-components-react

> What did you expect to happen? What happened instead? What would you like to see changed?
This will override all the divs inside **bx--tooltip** which causes problems. Ideally, the consumer should have those definitions for the divs or any other element.

> What browser are you working in? 
Chrome, Firefox

> What version of the Carbon Design System are you using? 
"carbon-components": "9.6.1",
"carbon-components-react": "6.18.3",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IGC, Information Server
Next code freeze for release: Aug 17, 2018

## Steps to reproduce the issue
1. Import Tooltip from carbon-components-react
`import { Tooltip } from 'carbon-components-react';`

2. Render it on some element and have a div inside Tooltip component as a child
```
        <Tooltip
            triggerClassName={styles.trigger}
            triggerText={someText}
            showIcon={false}
          >
            <div className={styles.myCustomStyles}>
              {someStuff()}
            </div>
          </Tooltip>
```

3. Inspect on the child div. You will notice the CSS override for element as explained above.

**Comment by asudoh** [comment]
@vishalpurandare Thank you for reporting! I agree that a ruleset dictating styles all `<div>`s inside a tooltip is too intrusive. Given fixing it requires a breaking change (requiring application to change in markup), we’d consider fixing it in next major release.

Meanwhile, I’d recommend creating your own ruleset with higher specificity level of the selector, overriding Carbon’s styles there. Thanks!

**Comment by vishalpurandare** [comment]
@asudoh Thanks for the quick response. Can you tell me when the next major release is planned for Carbon? So I can get an idea of roughly when to expect the fix for this.

**Comment by asudoh** [comment]
Hi @vishalpurandare I don’t have a date, but I see that Carbon tends to have 6 month - 1 year release cycle. Stay tuned!

**Comment by shinytoyrobots** [comment]
@vishalpurandare - quick update on release dates - we are looking at the next major release for Carbon in December 2018.

**Comment by vishalpurandare** [comment]
Thanks for the update @shinytoyrobots @asudoh. One more question I had is around some of the components have overridden fonts. For example:
.bx--button {
   font-family: "ibm-plex-sans", Helvetica Neue, Arial, sans-serif;
   ...
} 
Isn't fonts should be inherited from parent? "ibm-plex-sans" is not picked up by components and it falls back to Helvetica Neue.

**Comment by asudoh** [comment]
@vishalpurandare Looks a separate issue - Would you try entering an issue at https://github.com/IBM/carbon-components/issues with a reduced case similar to https://codesandbox.io/s/503042p0n4? Thanks!

**Comment by dakahn** [comment]
@asudoh was this cleared up in v10? 😄

**Comment by asudoh** [comment]
@dakahn Unfortunately this hasn't been resolved yet: https://github.com/carbon-design-system/carbon-components/blob/v10.1.0/src/components/tooltip/_tooltip.scss#L83-L86

**Comment by tw15egan** [comment]
The div styling was removed in this PR, and now just adds basic text styling: https://github.com/carbon-design-system/carbon/pull/2781
