### ISSUE TITLE
Sprint 24: Grateful Gingerbread 🧸

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10183]
## ⚛️ React

- [ ] Organize RTL Mob Programming workstream @tay1orjones 
  - [ ] Create/organize issues
  - [ ] Document initial steps
  - [x] Schedule a share/workshop with the team Dec 13

## 🚢  Migration

- [ ] #9640 @jnm2377 @joshblack @tay1orjones 

## 🎨  Styles

- [x] #9705 @joshblack
  - [x] Get feedback from @vpicone on implementation
  - [x] Land changes in `@carbon/styles`
  - [x] Re-export changes in `@carbon/react`
  - [x] Create documentation in Storybook for IBM Plex, update Storybook to use new strategy
  - [x] Figure out if changes should live in `@ibm/plex` or `@carbon/styles`

## 📦  Components
- [ ] Progress bar designs @thyhmdo 

## 📝  Website
- [x] v11: Update style tab pages with layer token annotations @aagonzales 
- [ ] v11: Style tab: update all classnames to common element names (on going) @aagonzales 
- [ ] Toggletip docs @kingtraceyj 
- [x] https://github.com/carbon-design-system/carbon-website/pull/2613 [in review] @laurenmrice  
- [ ] Progress bar and disclosure gifs @johnbister 
- [ ] Status indicator bugs @thyhmdo 

## 🎨 Design Kit

**Sketch**
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/438 @kingtraceyj @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/426 (in progress) @laurenmrice 
- [ ] Tooltip and toggletip updates @kingtraceyj 

**Figma**
- [x] Planning for other 3 themes @aagonzales @laurenmrice 
- [x] Cleaning up white kit @aagonzales @laurenmrice 

## 🚀  Releases

- [x] v10.50.0 (holiday catch-up release in the first week) @dakahn @abbeyhrt 
- [ ] v10.51.0  @abbeyhrt @dakahn 

## 📣 Communication

- [ ] Publish beta 3 announcement with team @joshblack 
  - [ ] Sync with @thyhmdo on artwork for post
  - [ ] @aagonzales to write blurb on color updates

## 🧙‍♂️ Meeting facilitators
- Backlog Grooming @theiliad 
- Sprint Retro @joshblack 
- Sprint Planning
  - Dev/System: @tay1orjones

**Comment by alisonjoseph** [comment]
## 🐝  Brand
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1083 @aledavila 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/999 @aledavila 



## 🖥️ DPO
- [ ] EDT issues (Joe/Alison)
- [ ] Universal Experiences - Globalization section @alisonjoseph

**Comment by theiliad** [comment]
## 📈     Dataviz
- [ ] Heatmap (should be finally merged this sprint)
- [ ] Zoombar enhancements
