### ISSUE TITLE
Tooltip with focusable element is not accessible on React 17

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon#10204]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.48.1

### Description

We previously opened an issue where a tooltip within a Pal side panel, when it has focusable content like a link, would close the whole side panel when the escape key is pressed.

Carbon released the following fix:

https://github.com/carbon-design-system/carbon/pull/9875

This has fixed the issue for our App if we would be running on React 16. However, we are running on React 17 and it has made things worse:
1. a tooltip on a regular page (not on a side panel) that has focusable content will now NOT close when pressing escape key, it gets stuck.
2. The fix on react 17 does not solve the issue, the side panel still closes (the event escapes)

### CodeSandbox example

https://codesandbox.io/s/stupefied-surf-gtf4z

### Steps to reproduce

(To reproduce first problem)
1. press tab until tooltip icon gains focus, opening the tooltip
2. observe tooltip opening, with focus on the button
3. press ESCAPE key
4. Observe that tooltip does not close
(then for second problem:)
5. press TAB key again so that the button inside the tooltip no longer has focus, and tooltip still open
6. press ESCAPE key
7. Observe that while tooltip closed, key handler on the outside div is being called, when it shouldn't

Then, open this code sandbox, https://codesandbox.io/s/fast-butterfly-d8t4t
this code sandbox is IDENTICAL to the previous sandbox, except it has React version 16. You will see both problems are not present in this sandbox.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Related https://github.com/carbon-design-system/carbon/issues/8502, https://github.com/carbon-design-system/carbon/issues/9866

**Comment by amortiz** [comment]
Can this fix be included in a patch instead of waiting the usual 2+ weeks it takes for a new carbon release? it currently breaks our accessibility in the majority of our pages. Thanks for consideration.

**Comment by tay1orjones** [comment]
@amortiz Yep, for sure. I'm looking into this now.

**Comment by tay1orjones** [comment]
@amortiz This should be fixed in via #10220, just published in v10.49.1. 

Here's two identical sandboxes demonstrating the fix with tooltip <kbd>esc</kbd> working as intended with both React v16 and React v17:

React 16: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react16-l1ih9
React 17: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react17-pydv4
