### ISSUE TITLE
[Bug]: the carbon button cannot show the updated iconDescription text

### ISSUE THREAD

**Issue by yonghuay** [carbon-design-system/carbon#10200]
### Package

carbon-components, carbon-components-react

### Browser

Chrome, Firefox

### Package version

v10.48

### Description

the carbon button cannot show the updated iconDescription after we updated the Carbon lib from 10.45 to 10.48
v10.45:
![button_tooltip_carbon_10 45](https://user-images.githubusercontent.com/32554015/144202477-f006dd8c-8c4a-432f-9183-6b3b18ca3488.gif)
v10.48:
![button_tip_carbon_10 48](https://user-images.githubusercontent.com/32554015/144202483-baa8940d-8c7c-4cab-bf93-a714d3fde083.gif)

### CodeSandbox example

https://codesandbox.io/s/dazzling-blackwell-6wg5s?file=/index.js

### Steps to reproduce

click on the button to see the updated text.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Wanted to cross-post this from Slack, this was introduced in: https://github.com/carbon-design-system/carbon/pull/9882

Wanted to double-check on behavior with @aagonzales

**Comment by yonghuay** [comment]
found other way to solve this. 
Thanks.
