### ISSUE TITLE
UI Shell - large screen toggle left panel

### ISSUE THREAD

**Issue by Julie-Saurat** [carbon-design-system/carbon#10208]
In the UI shell left panel, there is a media query disabling the toggle button> Thus this part cannot be toggle anymore.
I get the fact that in big screen you would like the menu to be always visible.
But is there an easy way to keep the toggle function even in big screen and to avoid having the left panel cover the left part of the page content?
![image](https://user-images.githubusercontent.com/65171375/144298609-e338a73b-aa26-4382-a980-22776f1f1bea.png)

**Comment by joshblack** [comment]
Hi there @Julie-Saurat! Thanks so much for taking the time to make this issue. This may be a case of the UI Shell pattern being tied to patterns at IBM.

Specifically, the side nav at larger screens tended to either be always expanded or be present as a "rail". In addition, the menu would then be used for additional navigation.

I'm curious what you think about this case @aagonzales, if it makes sense we could definitely support this use-case 👍

**Comment by aagonzales** [comment]
Josh is correct, we didn't originally support this UI Shell pattern. I think its could be a valid use-case but may need some design work since it will involve moving parts since the menu would be a grid influencer and not just an overlay like it is by default in small screens. 

>  and to avoid having the left panel cover the left part of the page content?

The left panel should be acting as a [grid influencer](https://carbondesignsystem.com/guidelines/2x-grid/overview/#grid-influencers) and push any content over so its not hidden under the nav.

**Comment by jnm2377** [comment]
> The left panel should be acting as a grid influencer and push any content over so its not hidden under the nav.

@aagonzales we don't actually have this functionality on the sidenav out of the box. People have to add that logic themselves. Mostly bc we don't support this pattern rn (collapsable at all breakpoints). When we just collapse on smaller breakpoints, it has the overlay so it doesn't influence the grid. And the large breakpoints it's just always present, so we didn't add logic for the sidenav to be a grid influencer. That would be an enhancement.

**Comment by datamadic** [comment]
I've noticed the same thing when using v11, after a certain size (less than my laptop) the sidenav seems to cover the content no matter what with no option to close it, it looks like in prior versions this was not the case. See [this] v11 example (https://codesandbox.io/s/header-with-sidenav-forked-popv7h?file=/src/index.js) which I believe is taken from the carbondesignsystem.com site. 

Fine when smaller 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/4810751/192708958-3254828b-d73f-426d-91ba-68f1f5c2e2d7.png">

Covered  after screen size gets larger
<img width="961" alt="image" src="https://user-images.githubusercontent.com/4810751/192708829-280d33f5-eab2-424e-a64b-7fe3c9eee752.png">

This did not seem to be the case in prior versions see [here](https://codesandbox.io/s/jz7rz) (also an example from carbondesignsystem.com I believe)
<img width="963" alt="image" src="https://user-images.githubusercontent.com/4810751/192709222-5b637384-86cd-457a-a156-837e8d08c8b1.png">

Is there a way to use v11 and have the side nav behavior from the prior versions? Apologies if this has already been covered or I missed something (i.e making it a grid influencer somehow), I've just started playing with carbon design and haven't quite got the hang of it yet :)
