### ISSUE TITLE
[Bug]: DataTable Sticky Headers cannot be implemented via native CSS

### ISSUE THREAD

**Issue by Zenthrr** [carbon-design-system/carbon#10217]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v10.49.0

### Description

The carbon `<DataTable>` component has whitespace at the bottom. Therefore it is necessary to have overflow-y:hidden set in either a wrapper container or the `<Table>` element itself. If the `<Table>` element is set as overflow-y:hidden, then the whitespace will disappear but then attempting to set a sticky header via native css is not possible since there is an intermediate element with overflow:hidden set as a property. 

I am aware that there is a `stickyHeader` prop available for the DataTable. However, this prop will drastically affect the styling of the table. So this isn't always a viable solution for the user.

<img width="888" alt="Screen Shot 2021-11-30 at 3 56 23 PM" src="https://user-images.githubusercontent.com/51710532/144126721-85820600-76f7-4af4-bce9-e13c79f95aae.png">

![imageedit_2_9504856616](https://user-images.githubusercontent.com/51710532/144515496-9e4bf8e3-fcd4-46fd-a97f-661de5109f51.gif)

This is the whitespace in question. Since it is part of the component I am unable to remove the element in question. 

### CodeSandbox example

https://codesandbox.io/s/datatable-scrolling-qxoko?file=/src/index.js

### Steps to reproduce

1. Create a DataTable componet with a header and rows
2. Set the Table comopnent to have overflow: visible as a property
3. This will display the whitepsace mentioned above
This does not always appear. It is a hard issue to emulate.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@Zenthrr could you update the codesandbox to show the whitespace issue you describe? Currently I see the `stickyHeader` prop and the custom .scss, but no whitespace.

**Comment by jnm2377** [comment]
I responded to a slack thread about this, so just responding here for tracking:

> I worked on sticky header a long long time ago and had a really hard time with it. Most of the sticky header implementations I’ve seen **aren’t** using native browser table styles, which don’t work well with position: sticky . Which is why the only way I found to do it was to change the styles for it drastically. To be honest, I never felt it was truly a great solution but at the time, I did not come across anything that would work correctly with the native table styles. 

That being said, I've still yet to see any table that uses native browser/css table styles to implement sticky header. Most I've seen are either custom `divs` made to look like tables, or tables styled as `block` to work differently than native table styles.  I think we are open to better solutions if you have any examples you could point us to that successfully implement native table styles and sticky headers.

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment or create a new issue and we can re-visit this!
