### ISSUE TITLE
Update tag colors in Gray 100 and Gray 90 themes

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10213]
The current tags in the dark themes are a little too dark. We want to lighten them up by one step down on the color scale. They current use color-80 for the background and color-30 for the text but now we want them to use:
- background: color-70
- text: color-20
- background-hover: color-hover-70

This is only for the Gray 90 and Gray100 themes, the light themes have no update.

![image](https://user-images.githubusercontent.com/11670886/144495392-a1093cdd-d1b7-4ee0-a554-ec04a472797d.png)

**Comment by tay1orjones** [comment]
@aagonzales @joshblack should this be considered a breaking change and placed behind a flag for v11 or could it go out in a v10 minor?

**Comment by aagonzales** [comment]
I think its _not_ a breaking change since the component token names are staying the same and we're only updating the values. But correct me if I'm wrong Josh.

**Comment by joshblack** [comment]
@aagonzales @tay1orjones yeah, if the names are the same but the colors are changing then we should be good to go. Would be a great one for next sprint, I think, since it should be just editing what's already there.
