### ISSUE TITLE
[Bug]: Structured List component does not support dark theme

### ISSUE THREAD

**Issue by clarebyrne** [carbon-design-system/carbon#10210]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.48.1

### Description

Structured list component does not inherit the dark theme colours

### Screenshots

<img width="1525" alt="Screenshot 2021-12-02 at 12 18 19" src="https://user-images.githubusercontent.com/59689747/144422516-ed223159-1ada-4071-af4f-c5b9b5926b83.png">

### Steps to reproduce

Apply the dark theme to a page that contains the structured list component.
The structured list does not change colours

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @clarebyrne, thanks for reporting this issue. Could you provide a link to a reproduction using our [CodeSandbox template](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)?
