### ISSUE TITLE
[Bug]: SideNav contrast too high for dark themes

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#10227]
### Package

carbon-components

### Browser

Chrome, Firefox, Edge

### Package version

v10.48.0 (via carbon-components-svelte)

### Description

For dark themes the SideNav is still white. As it can take up a fairly large portion of the screen this can be a bit glaring.

The styles seem to [not apply any theming](https://github.com/carbon-design-system/carbon/blob/d724a266795b0c59666f48286bf5b788c7a03716/packages/styles/scss/components/ui-shell/side-nav/_side-nav.scss#L39).

### Screenshots

![image](https://user-images.githubusercontent.com/834235/144818399-828f96d2-31a2-453d-9d8d-5e07d70d78d8.png)

### Steps to reproduce

Svelte components has examples here:
- [white](https://carbon-components-svelte.onrender.com/framed/UIShell/HeaderNav?theme=white)
- [g80](https://carbon-components-svelte.onrender.com/framed/UIShell/HeaderNav?theme=g80)
- [g90](https://carbon-components-svelte.onrender.com/framed/UIShell/HeaderNav?theme=g90)
- [g100](https://carbon-components-svelte.onrender.com/framed/UIShell/HeaderNav?theme=g100)

[Interactive REPL](https://svelte.dev/repl/2f39ab687dbb4e7cbf006a263626fdb5?version=3.44.2) (viewport has to be a certain size to always show the side nav. panel)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
cc @aagonzales what is correct here for the side nav component? 👀

**Comment by aagonzales** [comment]
In v10 (old tokens), the shell does not support theming, the values are hard coded and don't use tokens. So all side nav no matter the theme you're using will be the light color by default. Do get a dark theme in v10 you have to use overrides. However, in v11 the UI Shell is themeable and you will be able to choose the appropriate theme.

**Comment by joshblack** [comment]
Going to close this out as it's something that is supported in v11 but we will be unable to support it in v10.
