### ISSUE TITLE
[Bug]: ComboBox.helperText should allow PropTypes.object as well as PropTypes.string

### ISSUE THREAD

**Issue by vladbalanescu** [carbon-design-system/carbon#10228]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.45.0

### React version

16.0.2

### Description

`ComboBox` component should allow `PropTypes.oneOfType([ PropTypes.string, PropTypes.object])` for `helperText` on [this line](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ComboBox/ComboBox.js#L437).

Bug:
---
![image](https://user-images.githubusercontent.com/16047402/144834716-c108bd50-e96e-4662-b047-2d8f72c57d9f.png)

Usecase:
---
I am providing a `ReactMarkdown` node to `ComboBox.helperText` which is very useful if instead of a string, a consumer would like to render some text markdown within the helper text prop of ComboBox, to achieve this usecase:
![image](https://user-images.githubusercontent.com/16047402/144834899-7ccc172b-415d-4a19-814d-3475b7f4a4e1.png)
 

### CodeSandbox example

N/A

### Steps to reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @vladbalanescu! 👋  Thanks so much for taking the time to make this issue.

Something that is tricky for `helperText` is that this value is used by the underlying `<input>` through `aria-describedby`. As a result, anything interactive that is contained in the node that `aria-describedby` points to would not be announced to a user (in this case, I believe it would be the link).

Let me know if I'm misunderstanding, I'd love to hear how you are tackling this challenge if this is something that your project is solving for already!

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment or create a new issue and we can re-visit this!
