### ISSUE TITLE
[a11y]: Should the clear button in the search component use a tooltip as per other icon buttons?

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#10233]
### Question for Carbon

Icon buttons typically use a tooltip and the internal design for inline edit specifies tool tips for the icon buttons used inside the edit

https://pages.github.ibm.com/cdai-design/pal/patterns/edit#inline-edit

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Its not necessary. The button has a programmatic name picked up by screen readers via aria and is technically redundant since the user can hit escape on the search to clear it.

**Comment by dakahn** [comment]
Closing this question as answered, but I can reopen if there's something I've missed. 👍🏾
