### ISSUE TITLE
[Bug]: radio button labels wrap on narrow screens

### ISSUE THREAD

**Issue by modean** [carbon-design-system/carbon#10246]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.47.2

### Description

Radio button groups incl. their labels of radio buttons look odd on narrow screens. The radio buttons label wrap onto multiple lines which make the radio button group look misaligned.

### Screenshots

![image](https://user-images.githubusercontent.com/659775/145087639-57b3e920-0810-43ff-b5c5-e34a844a10b7.png)

### Steps to reproduce

1. Create a radio button group
2. Create radio buttons with labels where the labels must contain more than one word.
3. Try to reduce the size of the screen.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
I agree this wrapping behavior could be improved.

@aagonzales would it be better if we gave the wrapper of each radio button, `.{prefix}--radio-button-wrapper`, a value of `align-self: flex-start` when in horizontal mode to ensure that radio buttons align to the top of the container and text wraps below?

| existing | proposed |
| - | - |
| ![Screen Shot 2021-12-07 at 2 38 16 PM](https://user-images.githubusercontent.com/3360588/145102737-e8959bdc-a430-47f1-a5b8-47346a361d9a.png) | ![Screen Shot 2021-12-07 at 2 37 46 PM](https://user-images.githubusercontent.com/3360588/145102733-b06a628d-7842-4aff-bcf7-a1df732e5c7c.png) |
