### ISSUE TITLE
DropdownV2 doesn't make it obvious user can scroll to see more items

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1027]
@showeimer commented on [Mon Aug 13 2018](https://github.com/IBM/carbon-components-react/issues/1185)

## Detailed description

> Describe in detail the issue you're having.

Testers for ICP opened an issue against our UI team because they assumed that there were no other choices in the dropdown aside from the first view/first three.  After informing them that they can scroll, they are saying that it should be more obvious that there are multiple items after the first three in the list.  Opening this issue to request some kind of enhancement to make it more apparent.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Enhancement

> Is this issue related to a specific component?

DropdownV2

> What did you expect to happen? What happened instead? What would you like to see changed?

UX enhancement to inform the user that more choices exist in the dropdown aside from those in the initial view.

> What browser are you working in?

Tester used Firefox and Chrome.  He says that in Firefox he can click the top level item and get a scroll bar to appear but this does not happen in Chrome.

> What version of the Carbon Design System are you using?

    "carbon-components": "^8.22.6",
    "carbon-components-react": "^5.51.5",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Private

## Steps to reproduce the issue

This issue can be seen on the Storybook:

http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by joshblack** [comment]
cc @aagonzales to see how/if we should tweak the design here. Just let us know!

**Comment by aagonzales** [comment]
@joshblack yeah I wonder if the `list-box` can show more than 3 items. Is there some way we can let people customize?

I think a nice fix though no matter what would be to show half of the next item as a hint that there's more content. 

<img width="342" alt="image" src="https://user-images.githubusercontent.com/11670886/44046437-12ca4e32-9ef1-11e8-944d-a96b95e8141a.png">

**Comment by joshblack** [comment]
Yes, and yes! Will do 👍

**Comment by showeimer** [comment]
@joshblack @alisonjoseph @aagonzales hey there, we have a customer bug now opened against us for this issue.  Unfortunately, we won't be able to upgrade to the latest version of Carbon even if this issue is fixed/updated before the end of our release cycle.  Is it possible to force the scroll bar to always show on this component?

**Comment by aagonzales** [comment]
Seems to be fixed in the react versions but not the vanilla. 

![image](https://user-images.githubusercontent.com/11670886/57101009-f24db400-6ce5-11e9-9c4c-ec96cbcb5436.png)

**Comment by aagonzales** [comment]
Fix still needed.
