### ISSUE TITLE
Sprint 25: Hall & Oatmeal Cookies 🍪 

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10271]
## 🧩 Project tables

| [Umbrella workstreams](https://github.com/orgs/carbon-design-system/projects/39/views/28) | [Current sprint](https://github.com/orgs/carbon-design-system/projects/39/views/12) |
| - | - |

## ⚛️ React

- Prep work for 2022 Sprint 26
  - Break down grid work into issues @tay1orjones @joshblack 
  - Break down prop change issues @joshblack @tay1orjones 
  - Break down RC0 work into issues**
  - Storybook prep @joshblack 

## 🎨 Design Kit

**Sketch**

**Figma**

## 🧙‍♂️ Meeting facilitators
- ~Backlog Grooming~
- ~Sprint Retro~
- EOY Retro?
- Sprint Planning
  - Dev/System: @tay1orjones 

## 🏖️ **Vacations**

- [Calendar for December](https://www.notion.so/carbondesignsystem/49154244d0414ed9b1cf9c16b607495f?v=cbaddd6c1abb4a339b7c48927439fdbd)

**Comment by alisonjoseph** [comment]
## 🐝  Brand
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1083 @aledavila 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/999 @aledavila 
- [ ] [Status indicator table / grid issue](https://github.com/carbon-design-system/carbon-website/issues/2435) @aledavila 


## 🖥️ DPO
- [ ] Universal Experiences - Globalization section @alisonjoseph 
- [ ] https://github.ibm.com/Design/w3-design/issues/1086 @alisonjoseph
