### ISSUE TITLE
Verify that `size` changes work as expected across components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10295]
In v11, we standardized how our `size` prop worked across components. This issue is for verifying that these work as intended across our components. The standard for the `size` prop is that it is defined as follows:

```
ComponentName.propTypes = {
  size: PropTypes.oneOf([/* sizes */]),
};
```

Where sizes contains a set of the following values:

- `sm`
- `md`
- `lg`
- `xl`

Specifically, we need to go through the following components:

- [x] [Accordion](https://github.com/carbon-design-system/carbon/pull/10509) @sstrubberg 
- [x] [Button](https://github.com/carbon-design-system/carbon/pull/10532) @sstrubberg 
- [x] [ButtonSkeleton](https://github.com/carbon-design-system/carbon/pull/10559) @sstrubberg 
- [x] ComboBox - https://github.com/carbon-design-system/carbon/pull/10640
- [x] ComposedModal
- [x] ContentSwitcher
- [x] ControlledPasswordInput `DEPRECATED`
- [x] [DatePickerInput](https://github.com/carbon-design-system/carbon/pull/10912) @sstrubberg 
- [x] DataTable @sstrubberg 
- [x] Dropdown https://github.com/carbon-design-system/carbon/pull/10640
- [x] DropdownSkeleton https://github.com/carbon-design-system/carbon/pull/10640
- [x] FileUploaderButton @sstrubberg 
- [x] FileUploaderDropContainer @sstrubberg 
- [x] FileUploaderItem @sstrubberg 
- [x] FileUploader @sstrubberg 
- [x] FilterableMultiSelect https://github.com/carbon-design-system/carbon/pull/10640
- [x] Link
- [x] ListBox https://github.com/carbon-design-system/carbon/pull/10640
- [x] OverflowMenu @sstrubberg 
- [x] Menu `Experimental`
- [x] Modal
- [x] MultiSelect https://github.com/carbon-design-system/carbon/pull/10640
- [x] [NumberInput](https://github.com/carbon-design-system/carbon/pull/10930)
- [x] [Pagination](https://github.com/carbon-design-system/carbon/pull/10971) @sstrubberg 
- [x] [PasswordInput](https://github.com/carbon-design-system/carbon/pull/10612) @sstrubberg 
- [x] [Search](https://github.com/carbon-design-system/carbon/discussions/10247#discussioncomment-1788152) @sstrubberg 
- [x] [Select](https://github.com/carbon-design-system/carbon/pull/10941) @sstrubberg 
- [x] Table @sstrubberg 
- [x] TableToolbar @sstrubberg 
- [x] Tag [Only supporting `sm` & `md`]
- [x] TagSkeleton
- [x] [TextInput](https://github.com/carbon-design-system/carbon/pull/10589) @sstrubberg 
- [x] [TimePicker](https://github.com/carbon-design-system/carbon/pull/10944) @sstrubberg 
- [x] Toggle [Only supporting sm & md]
- [x] ToggleSkeleton
- [x] [TreeView](https://github.com/carbon-design-system/carbon/pull/10970) @sstrubberg

**Comment by tay1orjones** [comment]
A note on `size` default values:

In https://github.com/carbon-design-system/carbon/pull/10532 it was brought up that v10's `md` is the same value as v11's `lg`. In these cases we can either update the defaults to be a conditional based off the feature flag or simply wait to redefine the defaults until v11.

**Comment by tay1orjones** [comment]
Note on file-uploader, we need to remove the `field` sizing from styles and from the props. Fileuploader doesn't have a `next` version yet to accompany this.
