### ISSUE TITLE
Sprint 26: Iggy Poptarts 🫐 🍿 🍞

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10316]
## 🛠 Project

- [x] https://github.com/carbon-design-system/carbon/issues/9790 @joshblack 

## ⚛️ React

- [ ] Prep work
  - [x] Break down grid work into issues @tay1orjones @joshblack 
  - [ ] Break down prop change issues @joshblack @tay1orjones 
  - [ ] Break down RC0 work into issues**
  - [x] https://github.com/carbon-design-system/carbon/pull/10290 @joshblack 
- [ ] New components
  - [ ] https://github.com/carbon-design-system/carbon/issues/10280 @joshblack 
  - [x] https://github.com/carbon-design-system/carbon/issues/10286
- [ ] Updated components
  - [ ] https://github.com/carbon-design-system/carbon/issues/9902 @dakahn 
  - [ ] https://github.com/carbon-design-system/carbon/issues/9519
  - [ ] Tabs
    - [x] https://github.com/carbon-design-system/carbon/issues/9991 @abbeyhrt 
  - [x] https://github.com/carbon-design-system/carbon/issues/10281 @joshblack 
  - [x] Refactor to functional components
    - [x] https://github.com/carbon-design-system/carbon/issues/10010 @jnm2377 
    - [x] https://github.com/carbon-design-system/carbon/issues/10009 @jnm2377 
  - [ ] https://github.com/carbon-design-system/carbon/pull/9510 @dakahn 
- [x] Prop changes
  - [x] https://github.com/carbon-design-system/carbon/issues/10317 @sstrubberg 
- [ ] Testing
  - [x] https://github.com/carbon-design-system/carbon/issues/10276 @jnm2377 
  - [ ] https://github.com/carbon-design-system/carbon/issues/10275 @abbeyhrt 
  - [x] https://github.com/carbon-design-system/carbon/issues/10274 @dakahn 
  - [ ] https://github.com/carbon-design-system/carbon/issues/10273 @tay1orjones 

## 🚢  Migration

- [x] https://github.com/carbon-design-system/carbon/issues/10190 @joshblack   
- [x] Reach out to PALs and collect adoption requirements (IBM Products, IBM Watson IoT) @joshblack 
- [x] Coordinate migration with PALs and product teams for RC0 @joshblack 

## 🎨  Styles

- [x] https://github.com/carbon-design-system/carbon/issues/10174 @abbeyhrt 

## Audits

Owners: @aagonzales, @abbeyhrt 

All of our components will need to be double-checked before we ship a stable v11 release. This audit work will verify that each component meets our "definition of done". Early on, this work will involve defining our approach to auditing components before moving into our team following the defined process to audit each component.

## IBM Plex

Our support for IBM Plex in Carbon v11 needs to be finalized. This includes adding in support for IBM Plex Sans JP/KR along with adding in support for our hosted option that exists in v10. We also need to figure out the solution for a unicode issue present in our current sets.

- [x] #10353

## 📦  Components

- [ ] Audit
  - [x] https://github.com/carbon-design-system/carbon/issues/10295
  - [x] https://github.com/carbon-design-system/carbon/issues/9805

## 📝  Website

- [ ] Component [usage docs](https://github.com/carbon-design-system/carbon-website/issues/2085) updates @thyhmdo 

## 🎨 Design Kit

**Sketch**
- V11 Sketch kit updates @aagonzales @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/482 @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/483 @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/439 @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/297 @laurenmrice 
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/430 @laurenmrice 

**Figma**
- TBD

## 💬 Support

- [x] https://github.com/carbon-design-system/carbon/issues/10293 @sstrubberg 
- [x] https://github.com/carbon-design-system/carbon/issues/10193
- [x] https://github.com/carbon-design-system/carbon/issues/10052
  - Related? https://github.com/carbon-design-system/carbon/discussions/10306
- [ ] https://github.com/carbon-design-system/carbon/issues/9895 @dakahn 
- [ ] https://github.com/carbon-design-system/carbon/issues/10058 @jnm2377

## 🚀  Releases

- [x] Release v10.51 @abbeyhrt @jnm2377 

## 🧙‍♂️ Meeting facilitators
- Backlog Grooming
- Sprint Retro
- Sprint Planning
  - Dev/System: @tay1orjones 

## 🏖️ **Vacations** - [📆 ](https://www.notion.so/carbondesignsystem/49154244d0414ed9b1cf9c16b607495f?v=cbaddd6c1abb4a339b7c48927439fdbd)

**Comment by alisonjoseph** [comment]
## 🐝  Brand
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1083 @aledavila 
- [ ] https://github.com/carbon-design-system/design-language-website/issues/999 @aledavila 
- [ ] [Status indicator table / grid issue](https://github.com/carbon-design-system/carbon-website/issues/2435) @aledavila
