### ISSUE TITLE
DropdownV2 label text overlaps icon

### ISSUE THREAD

**Issue by showeimer** [carbon-design-system/carbon#1031]
## Detailed description

Bug in the DropdownV2 where if the label text is too long it will overlap the svg icon.  This issue was opened against our UI team by ICP testers and is causing a defect with internationalized offerings of ICP.

> Is this issue related to a specific component?

DropdownV2

> What did you expect to happen? What happened instead? What would you like to see changed?

The text and the svg should never overlap.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

    "carbon-components": "^8.22.6",
    "carbon-components-react": "^5.51.5",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Private.

## Steps to reproduce the issue

I was able to reproduce this issue in a sandbox environment

<img width="1306" alt="screen shot 2018-08-15 at 3 59 46 pm" src="https://user-images.githubusercontent.com/26075187/44170150-6f77c100-a0a4-11e8-87e2-05f8465cde4e.png">

## Additional information

Screenshot from our issue:

![ce3fb4c4-9ca6-11e8-8477-1f96159fd185](https://user-images.githubusercontent.com/26075187/44170221-abab2180-a0a4-11e8-9afe-38b26ed7b525.jpeg)

**Comment by aledavila** [comment]
Hi @showeimer. Can you provide the sandbox link with the issue being reproduced please as I cannot reproduce it. We also would gladly accept PRs that fix this issue.

**Comment by showeimer** [comment]
@aledavila was piggybacking off another sandbox, can you provide another environment to reproduce?

**Comment by alisonjoseph** [comment]
@showeimer here is a blank codesandbox with carbon loaded in you can use to create a reduced test case https://codesandbox.io/s/r07q7p0pq

**Comment by showeimer** [comment]
@alisonjoseph @aledavila Sorry for how long it's been taking to update this issue, we've been approaching the end of a release cycle and it's been hectic to say the least.

I can't seem to exactly recreate this problem.  We have a `div` that wraps around the component that we have `width: auto` set, I'm wondering if that's the problem.  

I did notice that if a word was too long it did recreate the issue and overlapped the icon, I left that example in the sandbox.  Otherwise, I think it's probably safe to close this issue and I'll investigate further from our end.  Thanks for the patience!

**Comment by alisonjoseph** [comment]
Thanks for the update, feel free to reopen this in the future if needed.

**Comment by lewishadden** [comment]
@alisonjoseph Can this be re-opened please?
We are also experiencing this bug 
<img width="90" alt="screen shot 2018-11-14 at 13 54 11" src="https://user-images.githubusercontent.com/17049577/48487052-0162a780-e815-11e8-91ea-abdc8f345e9d.png">

**Comment by aledavila** [comment]
Could you reproduce the issue here. 

https://codesandbox.io/s/r07q7p0pq

**Comment by lewishadden** [comment]
@aledavila 
https://codesandbox.io/s/71rk9lkkmj

If you resize the browser, just before the label text breaks onto a new line, you will see the SVG overlap the text
