### ISSUE TITLE
[Bug]: Button padding is not using relative units

### ISSUE THREAD

**Issue by kgibb** [carbon-design-system/carbon#10318]
### Package

carbon-components

### Package version

10.50.0

### Description

The button’s left and right padding use pixel units while top and bottom use rem so they're not scaling correctly when changing the font size settings.

_Chrome’s font size setting: Very Large vs Medium_
![image](https://user-images.githubusercontent.com/12196391/146756499-bd2bc60f-f5e6-414f-82fc-b5861c8f878f.png)
![image](https://user-images.githubusercontent.com/12196391/146756506-932788b1-0988-4576-bc49-b04557ae0cb8.png)

https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/globals/scss/_theme-tokens.scss#L97-L130

### CodeSandbox example

https://codesandbox.io/s/7t5hz

### Steps to reproduce

Increase/decrease browser font size setting.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jsehull** [comment]
The solution might involved issue
- #9478

and the PR I put up for it that needs testing feedback from the Carbon team
- #13370
