### ISSUE TITLE
[Question]: Is there OOB support for text editor?

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon#10320]
### Question for Carbon

Does carbon provide the following component/pattern?
https://www.carbondesignsystem.com/patterns/text-toolbar-pattern/

Or the above article is more like a guideline to the designer?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jnm2377** [comment]
Hi @lordsfantasy thanks for opening this issue! To answer your question, we don't have a component for that. The pattern was actually contributed by a community member here: https://github.com/carbon-design-system/carbon/issues/2447 We were interested in the component for sure, but don't have the bandwidth/priority for it, so we just added it as a pattern. We'd love to have someone contribute the code for it.

**Comment by lordsfantasy** [comment]
Hey @jnm2377, thanks for sharing the #2247. It was super fun going through the backstory and how it evolved into the pattern that it is today.

We used draftjs in our project and modified its design as per the text toolbar pattern. I wouldn't say we achieved 100% design though. The carbon text toolbar pattern functionality seems so much more polished and thoughtfully designed.

If we have to contribute the code, how should we go about it? What should be the underlying editor?

**Comment by tay1orjones** [comment]
@lordsfantasy To my knowledge we don't have any data surrounding teams' usage of editor solutions. It would be a total shot in the dark. 

I think it would be ideal for the components to not be tied to any specific editor. We could potentially bring in an editor in the storybook environment to wire it all up as an example though.
