### ISSUE TITLE
Sprint 27: John Lemon 🍋 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10338]
[Design System Project Board - `@current` Sprint](https://github.com/orgs/carbon-design-system/projects/39/views/12)

## ⚛️ React

- [x] Storybook
  - [x] Verify all stories appear in v11 storybook
- [x] Components
  - [x] Toggletip
  - [ ] Tabs
  - [x] Tooltip 
  - [x] Popover
  - [ ] ContentSwitcher

## 🚢  Migration

- [ ] Do preliminary work to update Gatsby Theme and identify gaps in docs or processes that we need to address @aledavila @jnm2377
- [x] Add ability to run codemods to `@carbon/upgrade`
- [x] Author codemod to change `import ... from 'carbon-components-react` to `@carbon/react`
- [x] Deliver second draft of migration docs for `carbon-components` -> `@carbon/styles`, `@carbon/react` @joshblack 
- [x] Deliver first draft of migration docs for `@carbon/react` @joshblack 

## Audits

- [Component Audit Project Board](https://github.com/orgs/carbon-design-system/projects/44)
   - Designers: @laurenmrice @thyhmdo @johnbister @aagonzales 
- [x] [Color token value audit](https://github.com/carbon-design-system/carbon/issues/10292#issuecomment-1016631208) @aagonzales 
   
## 🧮 Grid

- https://github.com/carbon-design-system/carbon/issues/10392

## 🎨 Design Kit

**Sketch**

**Figma**
- [x] Start Theming project @laurenmrice @aagonzales 

## 💬 Support
- [ ] Organize info/assets for Carbon award submissions @laurenmrice 

## 🚀  Releases

- [x] #10468
- [x] #10245

## 📣 Communication

- [x] Draft RC0 announcement post
- [ ] Publish RC0 announcement post on 1/28 or 1/31
- [x] Create feedback post in GitHub Discussions

## 🧙‍♂️ Meeting facilitators
- Retro: @abbeyhrt 
- Backlog Grooming: @jnm2377

**Comment by alisonjoseph** [comment]
## 🐝  Brand
- [ ] v11 Theme migration
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1083 @aledavila (in PR)
- [ ] https://github.com/carbon-design-system/design-language-website/issues/999 @aledavila
