### ISSUE TITLE
Update to the Carbon “actions toolbar” to allow for dropdown-menu buttons.

### ISSUE THREAD

**Issue by TanB123** [carbon-design-system/carbon#10348]
Overview
The current toolbar pattern only allows for single-action buttons which limits the number of actions that can be used -- especially when considering translation and small-window formats. The proposed pattern would allow the number of actions to scale by using dropdown-menu buttons. Menus can also be divided into categories following the “overflow menu” pattern.

![AB1](https://user-images.githubusercontent.com/96617414/148364144-1eac3510-c463-41d6-8075-3ca4e100f531.png)
_Current pattern with action-buttons in the tool bar of a default window size_

![AB2](https://user-images.githubusercontent.com/96617414/148364202-4a8129b2-04dd-4053-8a19-229f4af48b0d.png)
_New pattern with menu-buttons in the tool bar of a default window size_

![AB3](https://user-images.githubusercontent.com/96617414/148364328-a488ad09-645e-4f49-9d50-f9adcdcd8e6d.png)
_New pattern with an open dropdown menu in the tool bar_

![AB4](https://user-images.githubusercontent.com/96617414/148364405-32efd5ac-3b47-455c-9a08-a937e29207ae.png)
_New pattern with use of mixed action-buttons and menu-button in the toolbar_

**When to use**
This pattern would be used when there isn’t enough space on the toolbar to accommodate the list of actions. This could be because -	
• there are too many actions (more than 5) -	
• one or more action labels are long (by default or when translated) 
• the design needs to respond to a narrow window size (overflow menu)

**When not to use** 
This pattern should not be used if there is enough space to accommodate the actions as buttons in a default window size. 

**Behaviors**
Button states : Enabled, hover, active, focus and disabled menu-button states should be the same as the action-button (also Carbon primary button and Cloud menu button)

**Menu states:**	
• Open and close behaviors should be consistent with the Carbon “overflow” menu behaviors (also Cloud menu button)
• Open and close motion of the menu should be consistent with the Carbon “overflow” menu (also Cloud menu button) 
• Enabled, hover, active, focus and disabled menu states should be the same as the overflow menu (also Cloud button menu)

![AB5](https://user-images.githubusercontent.com/96617414/148365173-b86bc35b-91fe-4b9d-8402-d1516468e133.png)
Example of “active” button state, divided menu

**Best practices** 
Limit the number of menu-buttons to the amount that can be accommodated in a default window size. 
Follow current Carbon standards for content:
• Button labels should be noun (not verb), and they should accurately describe the options contained in the menu 
• Menu options should be verb+noun and should be clear and concise. They should match the tear sheet, slide-in or confirmation window title.

**Keyboard Accessibility** 
Follow existing accessibility guidelines for the data table, actions toolbar and overflow menu.

**Comment by thyhmdo** [comment]
Will need to more research and look at more use cases and accessibility standards for this proposal.

**Comment by elycheea** [comment]
This is an extension that can be found in Carbon for IBM Products (C4P aka C4IBMP) [batch actions](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--batch-actions).
