### ISSUE TITLE
Structured List textbox alignment issue in Safari

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1035]
![image](https://user-images.githubusercontent.com/2753488/44345531-3e5b1000-a459-11e8-9d4f-c0c88a6ab411.png)

Fix seems to be adding `vertical-align: middle` to the structured list td. 

https://codepen.io/alisonjoseph/pen/WgNwPZ?editors=0110

**Comment by aledavila** [comment]
I'm not seeing the bug?

**Comment by alisonjoseph** [comment]
Thats because I added the fix in the codepen 😉  I just commented it out. Would need to check/test that it doesn't break anything esle adding that fix though. I was just looking at this specific use-case.
