### ISSUE TITLE
[Question]: Getting error Uncaught Error: Unable to find a feature flag with the name: `enable-v11-release` after deployment

### ISSUE THREAD

**Issue by charanIBM** [carbon-design-system/carbon#10360]
### Question for Carbon

<img width="576" alt="error_lb4" src="https://user-images.githubusercontent.com/91954064/148530144-30d2a334-d05c-431e-adb7-88dfd8735f7e.png">
Hi,

I'm getting Uncaught Error: Unable to find a feature flag with the name: `enable-v11-release` error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @charanIBM! 👋 

Could you provide some steps to reproduce this issue using our [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) template?

**Comment by charanIBM** [comment]
Hi @joshblack,
This error is happening after running npm run build:prod. not sure how to resolve it

**Comment by laurenmrice** [comment]
This issue was resolved on slack, going to close. 👍
