### ISSUE TITLE
Accordion: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10373]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by aagonzales** [comment]
## Visuals (in react)
- [ ] Accordion hover background should be using `$layer-hover` instead of `$background-hover`
- [ ] Disabled borders be using `$border-subtle` (ie no change from enabled).
- [ ] `p` paragraph is using the v10 type token. Should be using `$body-01`

**Comment by aagonzales** [comment]
## Website

### Style
- [ ] Color/Interactive: background hover = `$layer-hover` *
- [ ] Color/interactive: disabled border = `$border-subtle`

**Comment by aagonzales** [comment]
## Kit
- [ ] Disabled icon should be: `$icon-disabled` instead of `button-disabled`
- [ ] Border disabled should be `border-subtle` not `button-disabled`
- [ ] Border (across sizes) should be `$border-sublte` coming in as `layer-accent-01`

**Comment by jnm2377** [comment]
- Tested in our `example` directory using the latest `@carbon/react` and everything is working as expected.
- Story examples also look correct in different themes
- Prop tables are showing on storybook
- Only breaking changes in v11 are the size props, which are already documented in the migration guide.
- Tested a11y checker and there are no violations
- VoiceOver is working as expected
- Only thing to note, is playground stories don't have controls yet, but those are being added/tracked in a separate issue https://github.com/carbon-design-system/carbon/issues/10751

#### align start
<img width="540" alt="Screen Shot 2022-03-08 at 5 21 24 PM" src="https://user-images.githubusercontent.com/32556167/157342579-d3e157b1-0b43-4c54-a1c3-a743acd942c4.png">

#### lg
<img width="603" alt="Screen Shot 2022-03-08 at 5 20 47 PM" src="https://user-images.githubusercontent.com/32556167/157342582-9918bf2f-1973-4a38-b143-9d0efd2ea831.png">

#### md
<img width="598" alt="Screen Shot 2022-03-08 at 5 20 35 PM" src="https://user-images.githubusercontent.com/32556167/157342585-46ef46bb-d309-4201-8708-65357fd53d5c.png">

#### sm
<img width="598" alt="Screen Shot 2022-03-08 at 5 20 22 PM" src="https://user-images.githubusercontent.com/32556167/157342586-d7fb1aa6-9ab1-408b-8ca9-4642475e170b.png">
