### ISSUE TITLE
[Bug]: SolarPanel32 icon is missing

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#10378]
### Package

@carbon/icons-react

### Browser

Chrome

### Package version

10.32.0

### React version

16.14.0

### Description

The icon SolarPanel32 seems to be missing in the icons package. I receive an `not defined` error message and I can't find it in the packaged file.

I also searched in https://github.com/carbon-design-system/carbon/search?q=SolarPanel, with no useful results.
I also searched in https://github.com/carbon-design-system/carbon-icons/search?q=SolarPanel, with no results at all.

I went through release notes and dit not find anything about "solar" from the newest version until my version.

On code sandbox it works.

### CodeSandbox example

https://codesandbox.io/s/trusting-bassi-648f9

### Steps to reproduce

1. In https://www.carbondesignsystem.com/guidelines/icons/library type in "solar", then the icon "Solar panel" shows up. Copy the component markup `<SolarPanel32 />`.

2. Import the icon like other carbon icons `import {SolarPanel32} from '@carbon/icons-react';`, then following error comes `Uncaught ReferenceError: SolarPanel is not defined`. When looking into `node_modules/@carbon/icons-react/es/index.js` there is no icon starting with `Solar`.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @FabianPiconeDev! 👋  What version of `@carbon/icons-react` are you using? It seems to be available in v10.44.0:

https://codesandbox.io/s/condescending-wing-0senc?file=/src/App.js

**Comment by FabianPiconeDev** [comment]
Hi @joshblack, still the same version as described above 😄 `10.32.0`. You are right, when I upgrade to `10.44.0`, the Icon exists. But how did you found that out? I already went through the changelogs, and even on changelog of version `10.44.0` I can't find any entry describing something with `solar`.

**Comment by joshblack** [comment]
@FabianPiconeDev great point on the changelog, wish there was an easy way for us to handle the icon batches that come in. At the moment, we tend to get batches of icons submitted every month or so.

I'll look into if we can either update changelogs with this info or if we could update the site to include version information for the minimal version for an asset 👍 

Hope this makes sense! Going to close this out for now but happy to keep the conversation going, if needed.
