### ISSUE TITLE
PaginationV2 Item alignment Issue 

### ISSUE THREAD

**Issue by anupamsomani1** [carbon-design-system/carbon#1037]
Hi, 

When I am using PaginationV2 component the alignment was not properly aligned.

`<PaginationV2 totalItems={0} pageSize={10} pageSizes={[10, 20, 30]} />`

<img width="1121" alt="screen shot 2018-08-21 at 11 18 27 am" src="https://user-images.githubusercontent.com/35505922/44421512-98310800-a535-11e8-8fc0-568357872d27.png">

But when try on code sandbox Its worked So what I have done wrong.

[CodeSandBox](https://codesandbox.io/s/q9v5ovr1r9)

**Comment by asudoh** [comment]
Hi @anupamsomani1 it’d be great you can go to Elements tab in Chrome DevTools and select the DOM elements in question, and see Styles tab or Computed tab at the right to see what styles are in effect. You can compare those work working version. If you have any question wrt why a specific Carbon style done in the way you see, we can discuss here. Thanks!

**Comment by dakahn** [comment]
closing as resolved, but if this is still an issue i'm happy to reopen 👍🏽
