### ISSUE TITLE
DropdownV2 uses --webkit-apearence: button in chrome

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#1039]
## Detailed description

DropdownV2 is given a button appearance that breaks the style. The `[type="button"]` selector is overriding the class styling.

> Is this issue related to a specific component?

I believe so but presumably, it is breaking wherever `[type="button"]` is used when it maybe it shouldn't be.

> What did you expect to happen? What happened instead? What would you like to see changed?

The class styling should override and use `--webkit-appearance: none` instead of `--webkit-appearance: button`

> What browser are you working in?

Version 68.0.3440.106 (Official Build)

> What version of the Carbon Design System are you using?

9.5.2

## Steps to reproduce the issue

1.  Use a dropdown v2 component
2.  View the component in desktop chrome

## Additional information

- It seems to work fine when you use a mobile device/screen resolution
![dropdownv2 bug](https://user-images.githubusercontent.com/4078018/44425753-64b0a680-a552-11e8-973e-01a5e6f6903d.gif)

**Comment by joshblack** [comment]
Hi there @vpicone! 👋 It seems like the webkit-appearance for that selector is being set by styles in your project, is that the case? Here's how this component looks in the React storybook:

![screen shot 2018-08-21 at 3 00 34 pm](https://user-images.githubusercontent.com/3901764/44425958-ff10ea00-a552-11e8-979b-dd31b6a9eab0.png)

**Comment by vpicone** [comment]
@joshblack Woops! You're correct, that came from normalize.css false alarm. Thanks!
