### ISSUE TITLE
[Bug]: Data table stickyHeader prop hides button tooltips

### ISSUE THREAD

**Issue by kenguo573** [carbon-design-system/carbon#10396]
### Package

carbon-components-react, @carbon/icons-react

### Browser

Chrome

### Package version

7.50.0, 10.44.0

### React version

17.0.2

### Description

tooltips from the table's toolbar are hidden when positioned at bottom
disabling `stickyHeader` fixes the issue

### CodeSandbox example

https://codesandbox.io/s/wonderful-poincare-o7hjd?file=/index.js

### Steps to reproduce

1. enable `stickyHeader`
2. set a toolbar button's `tooltipPosition` to `bottom`
2. hover over toolbar button, no tooltip is shown

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @kenguo573! I'm sorry you're running into this bug! `stickyHeader` is experimental and can definitely run into some oddities. I think for now, we would recommend setting the tooltip position to 'top' to ensure that the tooltip remains visible when used with `stickyHeader`
