### ISSUE TITLE
Breadcrumb: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10408]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by thyhmdo** [comment]
## Website 

### Live demo 

- [ ] Missing all the states
- [ ] Missing the overflow content

**Comment by thyhmdo** [comment]
## Visual (react)

Not sure what `$caret-size` means? 

![image](https://user-images.githubusercontent.com/77697351/152228450-67d24f03-1327-4bab-9f60-7b6dfcb9fb7d.png)

**Comment by laurenmrice** [comment]
## Design kit

**Overflow (master files):**
- [ ] Hover state: underline should be $link-primary-hover. Dots should be $link-primary-hover.
- [ ] Overflow dots need state for focus

**Comment by tw15egan** [comment]
@thyhmdo in that code sample, if you look at the first line we set a local variable called `caret-size`, and just reference it in the block. It's not a token that will appear anywhere else. Hope that clears that up 👍🏻 

Going to take a look at the rest of the dev audits now

**Comment by thyhmdo** [comment]
@tw15egan thanks!

**Comment by tw15egan** [comment]
The rest of the dev checks are complete and it looks good to me 👍🏻

**Comment by aagonzales** [comment]
Looks like this component is complete. Going to close this issue. @thyhmdo let me know if anything else needs to be done that I don't see and we will re-open. 

Live demo updates will be dealt with later. See https://github.com/carbon-design-system/carbon/issues/10889
