### ISSUE TITLE
Dropdown: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10415]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Default
- Multi-select
- Combo-box

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [ ] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by laurenmrice** [comment]
## Visual bugs

### scss code

**Dropdown**
- [ ] The `label` `type-style` should be type token `body-compact-01`.
- [ ] The `dropdown-text` `type-style` should be type token `body-compact-01`.
- [ ] The `dropdown-list` `type-style` should be type token `body-compact-01`.
- [ ] Check to make sure all spacing tokens use the format `$spacing-` instead of having to prefix the token with `$carbon--`.

- [ ] `dropdown-item` active state `background-color` should be color token `$layer-active`.

- [ ] `dropdown--show-selected` `background-color` should be color token `$layer-selected`.

>   .#{$prefix}--dropdown--show-selected .#{$prefix}--dropdown--selected {
>     display: block;
>     background-color: **$layer-hover**;
>     color: $text-primary;

- [ ] Skeleton state: Should be using color token `$skeleton-background`.

**Comment by laurenmrice** [comment]
## Design kit

- [ ] Update layer styles to use `$layer` logic for menu in all themes. https://github.com/carbon-design-system/carbon-design-kit/issues/429

**Comment by laurenmrice** [comment]
## Website

### Live demo
*Updating the Live demo with our current code should fix most of these bugs.
 - [ ] Light modifier needs to be taken off the live demo.
 - [ ] Needs to display size props
 - [ ] Needs to display states for invalid and warning.
 - [ ] Filterable multiselect option gets rid of the side panel. I feel like the side panel should still be there with the same options as the rest of the dropdown variants get.
 - [ ] The dropdown container should not shrink in width size when a new option is selected if it has a shorter amount of text than the previous selected option.
