### ISSUE TITLE
Date-picker: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10414]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme

_Update: bugs found, see comments below_

- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop - partially checked. The size prop and className prop have been documented but there is no documentation for the component moving from a class to a function

**Comment by aagonzales** [comment]
## Visuals (React)
- [ ] Disabled state should be using `$field` not `$field-disabled` (which we're removing)

- [ ] [_flatpickr.scss](https://github.com/carbon-design-system/carbon/blob/next/packages/components/src/components/date-picker/_flatpickr.scss) is still using v10 tokens. Follow [migration guide](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/11.x-color.md) for updates.

**Comment by aagonzales** [comment]
## Storybook
- [ ] Size are not available on storybook
- [ ] Disabled state is not available on storybook

**Comment by aagonzales** [comment]
## Website

### Live demo
- [ ] Remove `light` prop
- [ ] Update size name

**Comment by abbeyhrt** [comment]
@aagonzales I unfortunately don't have a sketch license (I applied but haven't heard back yet) so I can't confirm if this is the intent but it looks like the hover for the arrows and dates in the date picker is different in v10 and v11. 

In v10: 
![Screen Shot 2022-02-22 at 2 57 52 PM](https://user-images.githubusercontent.com/17281178/155218171-2b86390a-2f22-45f2-b604-d72352240d41.png)

in v11: 
![Screen Shot 2022-02-22 at 2 58 14 PM](https://user-images.githubusercontent.com/17281178/155218206-bacf6c91-9ba5-4a55-bc44-6ebd94dc764b.png)

would you be able to confirm if this is intended when you get to this audit?

**Comment by abbeyhrt** [comment]
I'm not sure what token they are supposed to be but the little arrows next to the month and year have a different hover state than in v10 across all themes and browsers.

In v11: 
![Screen Shot 2022-02-25 at 5 34 33 PM](https://user-images.githubusercontent.com/17281178/155817095-4feda399-bb35-400c-a242-bebdbfe15648.png)


In v10: 
![Screen Shot 2022-02-25 at 5 36 14 PM](https://user-images.githubusercontent.com/17281178/155817136-a63e754a-b502-43f8-ac87-1c1a5c37df12.png)

**Comment by aagonzales** [comment]
Here is the spec for date picker
![Date Picker - White theme](https://user-images.githubusercontent.com/11670886/156011882-793f5714-0584-48a8-b6a1-dd10dffb8d76.png)

**Comment by abbeyhrt** [comment]
As far as development review goes, this audit is complete! 🎉  Summary of findings: 

- Fixed incorrect token for hover on dates and arrows #10854
- Updated token used for hover of littler arrows next to year in picker #10932
