### ISSUE TITLE
Content switcher: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10412]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [ ] Develop

**Comment by aagonzales** [comment]
## Visual
- [ ] Should be using new name `body-compact-01` 
 ```
.#{$prefix}--content-switcher-btn {
    @include reset;
    @include type-style('body-short-01');
```
- [ ] sm and lg size are label correctly in code. Couldn't see the default on defined as 'md'. Sizes also weren't present in storybook to test.

**Comment by aagonzales** [comment]
## Website

### Style tab
- [ ] Color: update unselect background = transparent
- [ ] Color: add border = `$border-inverse`
- [ ] Color: update hover background = `$layer-hover`
- [ ] Color: add `focus-inset`

**Comment by aagonzales** [comment]
## Kit
- [ ] No color tokens attached to the borders (future enhancement?)

**Comment by tay1orjones** [comment]
Closing since all items are addressed, we'll make a pass at updating size controls in storybook through https://github.com/carbon-design-system/carbon/issues/10751
