### ISSUE TITLE
Inline loading: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10417]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by thyhmdo** [comment]
## Visual (react) 

- [ ] Small loading circle stroke/width is 16px instead of 12 
Website

![image](https://user-images.githubusercontent.com/77697351/152042108-0bdd6051-a13f-4a69-b666-d7b81010e402.png)

SCSS
![image](https://user-images.githubusercontent.com/77697351/152041979-4c703895-5333-4657-9c43-f9ee31e0afb0.png)

Storybook

<img width="252" alt="image" src="https://user-images.githubusercontent.com/77697351/152042041-7307e258-2ad7-4044-bf2f-8f69efb41961.png">

**Comment by thyhmdo** [comment]
## Sketch kit
- [ ] No documentation of stroke width, text, spacing, and color

**Comment by tw15egan** [comment]
I believe the `stroke-width` is referring to the `Loading` component and is to offset the animation not the actual size of the icon. `InlineLoading` is rendering at 16px

![Screen Shot 2022-03-01 at 2 26 09 PM](https://user-images.githubusercontent.com/11928039/156235761-4afc8b5d-2083-449a-822f-ff7faed96012.png)


Everything else looks good 👍🏻

**Comment by tw15egan** [comment]
The size of the `small` Loading, as well as `InlineLoading`, is `16px`. I believe the `stroke-width` and `stroke-dashoffset` are used to improve the animation and don't affect the actual size of the components, so I think these are fine as is. Everything else looks good to me 👍🏻
