### ISSUE TITLE
File-uploader: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10416]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Default
- Drag and drop

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [x] Develop

**Comment by thyhmdo** [comment]
**Website (v11)**
_Design checks_

Small detail, but wondering if we should change the order from Small to Large

![Screen Shot 2022-01-18 at 4 11 01 PM](https://user-images.githubusercontent.com/77697351/150212068-b4d00577-dde2-4dc5-b9d0-9ab30de659d6.png)

**Comment by thyhmdo** [comment]
**Variants**
Purpose? Instead of Way it works? 

![image](https://user-images.githubusercontent.com/77697351/150213879-50294778-150b-4bce-8c51-cf8f8dc59157.png)

**Comment by thyhmdo** [comment]
**Live demo**

Should upload states under the variant? 

![image](https://user-images.githubusercontent.com/77697351/150222413-54768e68-91c4-40b8-af40-19abddd1bcbe.png)

Multiple doesn't change anything. Seems to miss:
- Sizes: Small, Medium, Large
- States: loading, success, uploaded

![image](https://user-images.githubusercontent.com/77697351/150222741-431da13b-638a-4559-adb9-6d3eb5a8f687.png)

**Comment by thyhmdo** [comment]
## Visual (react)

- [ ] file__selected-file--invalid__wrapper /  background color should be `$layer` instead of `$filed`
- [ ] checkmark contrast should be `$icon-inverse`
![image](https://user-images.githubusercontent.com/77697351/152040182-84dc0cf2-1d94-4a66-8b1d-686cc22b1ff0.png)
<img width="731" alt="image" src="https://user-images.githubusercontent.com/77697351/152040237-258c5a52-0bc1-4b57-9094-1b9ed6371aaa.png">

**Comment by aagonzales** [comment]
## Sketch kit
- [ ] Update "field" to "layer
