### ISSUE TITLE
Overflow-menu: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10424]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [ ] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [ ] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by laurenmrice** [comment]
## Visual bugs

### scss
- [ ] Hover state: `background-color` should be color token `$layer-hover`
- [ ] Enabled state for menu: `background-color` should be color token `$layer` not field-02. Example below.
>   .#{$prefix}--overflow-menu--light.#{$prefix}--overflow-menu--open,
>   .#{$prefix}--overflow-menu--light.#{$prefix}--overflow-menu--open
>     .#{$prefix}--overflow-menu__trigger {
>     background-color: **$field-02**;
>   }
- [ ] All references to "light" `background-color` should be color token `$layer`.

### Storybook
- [ ] Sizes are missing.
- [ ] Flipped direction is missing.
- [ ] Menu direction is missing.

**Comment by laurenmrice** [comment]
## Design kit

- [ ] Danger hover button: Text should be using type token `$body-compact-01` and color token `$text-on-color`.
- [ ] Icon enabled background: Use the `$transparent` color token.
- [ ] Active state for icon button should use `$layer-active` color token.
- [ ] Dark themes: danger hover button should be using `$danger-primary-button` color token.

**Comment by jnm2377** [comment]
Note about "playground" stories that show the:
- flipped
- sizes
- menu direction

These are being covered in this epic https://github.com/carbon-design-system/carbon/issues/10751 which works on adding the playground stories to all the components that need them.
