### ISSUE TITLE
Notification: v11 audit 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10422]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Low contrast
- High contrast
- Inline
- Toast

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [ ] Safari
    - [ ] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [ ] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [ ] Correct design tokens (type and color) are used
- [ ] Component using the correct size prop names
- [ ] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [ ] Confirm that there are no violations in Accessibility checker - _One violaiton found:_ 
![Screen Shot 2022-03-08 at 2 37 59 PM](https://user-images.githubusercontent.com/17281178/157320812-ec1f9855-cc4b-446b-a643-569936c7f84c.png)

PR to potentially fix: #10939 

- [ ] Confirm that component works as expected with VoiceOver

Close notification was not being announced. 

PR to potentially fix: #10939

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by abbeyhrt** [comment]
Hey @laurenmrice, do you have more context around the new Notification changes? It looks like there is no longer the bolded title and regular font subtitle, the content is all the same font type, do you know if that change is intended?

**Comment by laurenmrice** [comment]
## Visual bugs

### scss

**All variants of notification**
- [ ] We should be showing the two different type tokens in the header area for the title (`$heading-compact-01`) and subtitle (`$body-compact-01`). 

**Inline notification (low contrast)**
- Question: I notice for the inline notification (low contrast) the background-color is set to color token `$notification-background-[support type]` (For example: $notification-background-error). In our kit and on the website style tab guidance the token says its `$notification-error-background-color`. I am just wondering which one is correct?

**Toast notification (actionable)**
- [ ] The below should be `$focus-inverse`.
>  .#{$prefix}--actionable-notification a:focus {
>     outline: 1px solid **$link-inverse**;
>   }
- [ ] The padding below the action button and the container of the notification should be `$spacing-05`.
- [ ] Margin-top padding before the action button and the bottom of text should be `$spacing-06`.

**Comment by abbeyhrt** [comment]
@laurenmrice making those updates now!

 For your question about `$notification-background-error` vs `$notification-error-background-color`, it looks like we were inconsistent with naming here. In code, the tokens follow that `$notification-background-{modifier}` convention, like `$notification-background-info`, `$notification-background-warning`, etc but the site and I assume the kit have the `$notification-{modifier}-background-color` . 

Code-wise, `$notification-background-{modifier}` follows a convention we use for tokens and classnames called BEM(Block, Element, Modifier) so I assume that's why we named it that way but I don't know.  

I have a personal preference `$notification-background-{modifier}` but I don't feel too strongly. Either way, I definitely think they should be consistent and I'm down to take on renaming them, whether it be in the css or on the site!

**Comment by laurenmrice** [comment]
## Website

### Usage tab
- [ ] Add new variant called "Actionable" and add guidance.
- [ ] Update images for the actionable notification to remove semi-bold text.

### Style tab
- [ ] Update notification component specific tokens to correct naming convention.

### Live Demo
- [ ] Needs to be updated with the latest changes to code.

**Comment by laurenmrice** [comment]
## Design kit
- [ ] Add variant called "Actionable" to house actionable toasts and inline notifications.
