### ISSUE TITLE
Number input: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10423]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [x] Safari
    - [x] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by laurenmrice** [comment]
## Visual bugs

### Scss code

- [ ] Number input field text should use type token `$code-01`.
- [ ] Check to make sure all spacing tokens use the format `$spacing-01`, etc. instead of having to prefix the token with `$carbon--`.
- [ ] Could not find the different sizes that should be available. (large 48px, medium 40px, and small 32px)

### Storybook
- [ ] Enabled state: There should be a rule divider between the subtract and add buttons. Currently it is not showing up.
- [ ] Could not find the different sizes that should be available. (large 48px, medium 40px, and small 32px)

**Comment by laurenmrice** [comment]
## Website

### Style tab
- [ ] Color/image: Image needs to be fixed. Number text in the input is the wrong size and misaligned.
- [ ] Interactive/error message: Error message should be color token`$text-error`.

**Comment by laurenmrice** [comment]
## Design kit

**Disabled state**
   - [ ] The subtract icon and add icon should be color token `$icon-disabled`.
   - [ ] The rule divider should be color token `$border-disabled`.

**Comment by aledavila** [comment]
dev is checked

**Comment by tay1orjones** [comment]
Closing, live demos will be part of https://github.com/carbon-design-system/carbon/issues/10889
