### ISSUE TITLE
Loading: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10420]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [ ] Safari
    - [ ] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by thyhmdo** [comment]
## Sketch kit 

- [ ] No documentation of tokens. Probably open the inline loading for tokens

**Comment by thyhmdo** [comment]
## Visual (React)

- [ ] Can't find these token values  `$loanding gap` and `loading small gap` . Can a dev help check on this? 
![image](https://user-images.githubusercontent.com/77697351/153671467-8bf3a5ce-04d2-406f-8581-88e254abace0.png)

**Comment by thyhmdo** [comment]
## Website 

Style tab 
- [ ] Small spinner background should be `$layer-alt`

![image](https://user-images.githubusercontent.com/77697351/153672724-f34086b0-d9dc-4368-8e4b-171a0c600648.png)

**Comment by thyhmdo** [comment]
## Sketch kit

- [ ] Missing `overlay` token for page overlay
