### ISSUE TITLE
Progress indicator: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10427]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [ ] Safari
    - [ ] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [ ] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [ ] Confirm that there are no violations in Accessibility checker
- [ ] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by thyhmdo** [comment]
**Storybook** 

Default (broken for all themes)
- Text is larger on the second and third step
- Missing the complete step
- Text does not meet accessibility on g90 and g100
<img width="726" alt="image" src="https://user-images.githubusercontent.com/77697351/150407213-e34b5198-24e8-4663-b24e-045676c3ba59.png">

Interactive (broken for all themes)
- Text is larger on the third step 
- Text does not meet accessibility on g90 and g100

<img width="459" alt="image" src="https://user-images.githubusercontent.com/77697351/150408028-e447a05d-58c9-4e91-aa8a-dbc90898c9cd.png">

**Comment by thyhmdo** [comment]
**Live demo**
- Not yet updated. See this close [PR](https://github.com/carbon-design-system/carbon/issues/8104#issuecomment-992870275)

![image](https://user-images.githubusercontent.com/77697351/150408645-f15f6585-9864-4f85-804d-8df93d679792.png)

- Demo is not showing up when selecting modifiers on the right 

![image](https://user-images.githubusercontent.com/77697351/150410289-f7077d37-a73d-47c9-a63d-bdcc33378c14.png)

**Comment by thyhmdo** [comment]
## Visual (React)

- [ ] Progress line height should be 2px instead of 1px
![image](https://user-images.githubusercontent.com/77697351/152045362-89b1c1f2-72ed-4674-93a4-d8eaf943da26.png)

- [ ] Unsure about this token
![image](https://user-images.githubusercontent.com/77697351/152045570-b7c6a39b-3679-4f1b-aa6e-35a64e666994.png)

- [ ] hover state should be `$link-primary-hover` instead of `$link-primary`
![image](https://user-images.githubusercontent.com/77697351/152046329-ead05d3a-148c-42a1-bf15-7d8271867e82.png)

![image](https://user-images.githubusercontent.com/77697351/152046350-e9409ada-22ed-4bc1-bbe0-594314de2bf6.png)

- [ ] label active state should be `$text-primary` instead of `$background-brand`
![image](https://user-images.githubusercontent.com/77697351/152047439-96f361c3-784a-43c6-9502-95c80be502b3.png)

![image](https://user-images.githubusercontent.com/77697351/152047570-aee68c93-a10a-4d6a-a561-51de4422a748.png)

**Comment by thyhmdo** [comment]
## Website (Style tab) 

- [ ] hover text color is `$link-primary-hover` instead of `$link-primary`

![image](https://user-images.githubusercontent.com/77697351/152057563-4b6e2a13-89ae-4fd2-a740-3a714252d12d.png)

**Comment by laurenmrice** [comment]
## Design kit

**Master files**
Current and Complete states: progress line should be using color token $border-interactive.
