### ISSUE TITLE
Radio button: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10428]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [ ] Safari
    - [ ] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [ ] Develop

**Comment by thyhmdo** [comment]
**Storybook**

Default – Nitpicky, but should one of the radio buttons selected when first coming to this page?

![image](https://user-images.githubusercontent.com/77697351/150572089-d4210b57-4889-431f-8030-89a267544f3a.png)

**Comment by thyhmdo** [comment]
**Live Demo** 

Should we add Focus and Disabled state?

**Comment by thyhmdo** [comment]
## Visual (React) 

- [ ] label and icon should be `$text-disabled` and `$icon-disabled` . `$disabled` is not a correct token

![image](https://user-images.githubusercontent.com/77697351/152186016-92169215-fb11-4d7e-9189-8c7fb2ae7b1b.png)

**Comment by laurenmrice** [comment]
## Design kit

**Master files**
- [ ] Focus state: should be color token `$focus`.

**Comment by abbeyhrt** [comment]
@thyhmdo I think that might be from the stylesheet for the v10 components. Thankfully it looks like the v11 stylesheet is using the right tokens 🙂
![Screen Shot 2022-03-10 at 6 26 47 PM](https://user-images.githubusercontent.com/17281178/157778179-cb653466-2c4f-4e22-a8bc-03eb7755192e.png)

**Comment by abbeyhrt** [comment]
@thyhmdo Definitely agreed about the storybook! I'll make those changes 👍

**Comment by abbeyhrt** [comment]
https://github.com/carbon-design-system/carbon/pull/10960 Makes the storybook change and updates the background-color value for `cds--radio-button__appearance` !
