### ISSUE TITLE
Text input: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10435]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Text input
- Password input
- Text area

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [x] Live Demo has applied v11 changes
   - [x] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [ ] Confirm that there are no violations in Accessibility checker
- [ ] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by thyhmdo** [comment]
**Live Demo** 

Modifiers side needs to update:
- Still has the `light` prop
- Invalid -> Error? 

![image](https://user-images.githubusercontent.com/77697351/150853293-e6b24dce-4f3b-49a5-8b8d-e8dcb990cb2a.png)

Password input variant has a bug and missing all the modifiers 

![image](https://user-images.githubusercontent.com/77697351/150854476-77777d96-b80f-4d43-b746-16cc4af689ad.png)

**Comment by sstrubberg** [comment]
https://github.com/carbon-design-system/carbon/issues/10588

Icon placement for ReadOnly Variant

**Comment by sstrubberg** [comment]
Re: Size Props:

Currently, it's set for `['sm', 'md', 'lg', 'xl']`, but the design guidance says it should be [`['sm', 'md', 'lg']`](https://v11.carbondesignsystem.com/components/text-input/style#sizes)

**Comment by thyhmdo** [comment]
## Sketch kit 

- [ ] No token documentation at all 
- [ ] All themes are named "Slider"

**Comment by thyhmdo** [comment]
> Re: Size Props:
> 
> In v10, it's set for `['sm', 'md', 'lg', 'xl']`, but the design guidance says it should be [`['sm', 'md', 'lg']`](https://v11.carbondesignsystem.com/components/text-input/style#sizes). Are we OK with leaving the XL in there or should that be taken out?

Yeah, we would take the `'XL'` size out. It was named wrong in v10 and in v11 we correct the name back to just large - Anna

**Comment by thyhmdo** [comment]
## Visual (react) 

- [ ] Will deprecate the `light` prop
![image](https://user-images.githubusercontent.com/77697351/153461773-01053477-9a88-4a40-be88-bb67d6aa1206.png)

- [ ] `$field` instead of `$field-disabled `
![image](https://user-images.githubusercontent.com/77697351/153468039-4fb68cd4-4cbe-4103-a9d6-946a0056d69f.png)

**Comment by aagonzales** [comment]
## Design kit
- [ ] Using field layer component
   - [ ] W
   - [ ] G10
   - [ ] G90
   - [ ] G100
