### ISSUE TITLE
Toggletip: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10438]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] ~Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))~ NA

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] ~Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)~ NA
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] ~Size props are named correctly~ NA
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] ~Component using the correct size prop names~ NA
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [ ] Confirm that there are no violations in Accessibility checker
- [ ] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by laurenmrice** [comment]
## Visual bugs
### scss
- [ ] There is currently no scss file for the component Toggletip.

### Storybook
- [ ] Link in toggletip: Known issue to make color tokens for the hover and active state for inverse-links. Just need to make the issue and will post it here.
- [ ] Button in toggletip: Known issue to about the inset color during the focus state. Just need to make the issue and will post it here.

**Comment by laurenmrice** [comment]
## Website

### Usage tab
- [ ] Content (main elements) section: second paragraph should say "toggletip", not tooltip.
- [ ] Relate section (Disclosures): take out "Further guidance on the disclosure pattern coming soon." sentence.

### Style tab
- [ ] Question for dev: The toggletip text appears to be `$body-01`. Is it possible if the text is on one line for it to be `$body-compact-01` and it can transition into `$body-01` if it goes to multiple lines? Or does it always need to be one token or the other? We need to align on this for Popover, Tooltip, and Toggletip.

**Comment by tay1orjones** [comment]
Closing since we've got everything remaining tracked in #2624, #2623, #2622, #10973
