### ISSUE TITLE
Request to make Radio Button default be vertical, not horizontal

### ISSUE THREAD

**Issue by williamjdai** [carbon-design-system/carbon#1044]
Currently, the Carbon Component Radio Buttons are horizontal, next to each other, by default in the codepen. 

This is strange because most of the radio buttons encountered on websites are vertical, and only in cases where there isn't sufficient space (or if the site needs to display a high density of information/options to the user) will the radio buttons need to be horizontal.

If the buttons were vertical by default, it would be much easier for the end user to grab the component from the codepen and go, instead of having to fiddle around and change the orientation throughout.

**Comment by aagonzales** [comment]
Approved change by Carbon Design 👍 
Slack converstation: https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1534976637000100

**Comment by williamjdai** [comment]
If at all possible, could the CodePen include code for both orientations? On second thought, horizontal is good if you only need "Yes/No" instead of many options.

**Comment by alisonjoseph** [comment]
I updated the codepen, https://codepen.io/team/carbon/pen/YErXNB?editors=1100

@aagonzales are you ok with 1rem spacing below each radio button in the example? If so I can also update the website example.

**Comment by williamjdai** [comment]
Thank you very much!
