### ISSUE TITLE
UI Shell: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10440]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Header
- Left panel
- Right panel

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- ~Live Demo has applied v11 changes~
   - ~Themes are rendering correctly~
   - ~Size props are named correctly~
   - ~No `light` props included~

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by aagonzales** [comment]
## Visual (react)
- [ ] In [_header.scss](https://github.com/carbon-design-system/carbon/blob/next/packages/components/src/components/ui-shell/_header.scss) Header name: update type style to `$body-compact-01`
- [ ] [_navigation-menu.scss](https://github.com/carbon-design-system/carbon/blob/next/packages/components/src/components/ui-shell/_navigation-menu.scss) still is using raw IDL colors and not using the new tokens. (let anna know if you need a spec to fix)
- [ ] [_product-switcher.scss](https://github.com/carbon-design-system/carbon/blob/next/packages/components/src/components/ui-shell/_product-switcher.scss) is still using raw IDL colors and old shell tokens. Needs to use new theme tokens. (let anna know if you need a spec to fix)

**Comment by aagonzales** [comment]
## Storybook 
- [ ] The story [SideNav Rail w/ header](https://carbon-react-next.netlify.app/?path=/story/components-ui-shell--side-nav-rail-w-header&globals=theme:g100) should only have one item selected not three.

**Comment by aagonzales** [comment]
## Website

### Style
- [ ] Update blurb at the top of the color section

Header
- [ ] Missing Link:selected states

Left panel
- [ ] missing icon specs in link section
- [ ] Add states to "icon" section

Right panel
- [ ] Intro blurb is wrong
- [ ] Images are using incorrect color for the backgrounds

**Comment by aagonzales** [comment]
## Kit

- [ ] Update "UI Shell template"
- [ ] Update symbols to use theming tokens

**Comment by abbeyhrt** [comment]
Throwing this here since I just noticed it but the UISHell docs for the storybook are pretty broken. It looks like it's trying to render all UI Shells on the 
![Screen Shot 2022-03-11 at 3 28 00 PM](https://user-images.githubusercontent.com/17281178/157972029-af8d6b31-282d-45fd-b87e-096cd0f54646.png)
docs page.
