### ISSUE TITLE
Create Grid API Design doc

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10472]
## Pre-existing work

```tsx
// Grid
type Props = {
  as?: React.ReactNode,
  condensed?: boolean,
  narrow?: boolean,
  fullWidth?: boolean,
  columns?: number,
  className?: string,
  children: React.ReactNode,
  // ...rest
};

// Row
type Props = {
  as?: React.ReactNode,
  condensed?: boolean,
  narrow?: boolean,
  className?: string,
  children: React.ReactNode,
  // ...rest
};

// Column
type Props = {
  as?: React.ReactNode,
  children: React.ReactNode,
  className?: string,
  sm?: ColumnSpan,
  md?: ColumnSpan,
  lg?: ColumnSpan,
  xlg?: ColumnSpan,
  max?: ColumnSpan,
  // ...rest
};

type ColumnSpan = 
  | boolean
  | number
  | { span: number, offset: number };
```

## Ideal API

**Goals**

- Minimize the amount of CSS Grid exposed through the API
- Make it simple to construct robust pages built on a grid

```tsx
// Column
// GridItem
type ItemPosition =
  | number                          // grid-column: span <number> / span <number>
  | 'full'                          // grid-column: 1 / -1
  | 'auto'                          // grid-column: auto
  | { start: number, end: number }  // grid-column-{start,end}
  | { start: number, span: number } // grid-column: start / span number
  | { end: number, span: number }   // grid-column: span number / end
  | { span: number }                // grid-column: span <number> / span <number>
```

**Observations**

- Defer row support
- It's hard to see how this interop with grid areas
- We can use inline styles + CSS Custom Properties to interact with classes that we've made
  - `<GridItem row="sample-row" />` Could become `style: --column-span: 'sample-row'`
- We can offer `span <number>` but things like `span <name>` or `<line>` are more challenging
- The way we want to use `Row` is similar to starting an item on the second row

**Questions**

- Does it make sense to keep calling it a `Column`?
  - Is a `Column` a special case that sits in one grid track?
  - Should it expand to work across rows?
- How much of the CSS Grid API should be exposed versus not?

**Deferred**

- Grid Areas
- Grid Container alignment
- Grid Item alignment (self)
- `grid-template-rows: masonry`
- auto-flow, auto-columns

## Links & Resources

- [Bootstrap CSS Grid](https://getbootstrap.com/docs/5.1/layout/css-grid/)
- [Tailwind](https://tailwindcss.com/docs/grid-column)
- [MUI](https://mui.com/components/grid/)

**Terminology (CSS Grid)**

- Grid Container
- Grid Item
- Alignment
  - `grid-column-start`
  - `grid-column-end`
  - `grid-row-start`
  - `grid-row-end`

**Comment by joshblack** [comment]
**Responsive Props**

- Array-based style `[sm, md, lg, xlg, max]`
- Object-based style `{ sm: 4, md: 4 }`
- Prop-based style `smColumn`, `mdColumn`
- Hook-based style (bad for CSS layouts)

**Comment by tay1orjones** [comment]
I like the object-based style. It's a little fuzzy for me in the comment above, but this informs a hierarchy where the responsive `sm`, `md`, etc props each accept the `span` prop type enabling things like offsets only at certain breakpoints.

```jsx
<GridItem column={{ xs: {start: 4, end: 6}, md: 4 }} />
```

Are there any blockers if percent span was just a string? Feels important to separate its type from a number.

```jsx
<GridItem column={{ xs: "100%", md: "50%" }} />
```

**Comment by joshblack** [comment]
@tay1orjones shouldn't be a problem, I think!

**Comment by joshblack** [comment]
## CSS Grid Support

Based on supported properties from: https://css-tricks.com/snippets/css/complete-guide-grid/#aa-properties-for-the-grid-container

**Grid container**

| CSS Property          | Supported | Prop | Context                                                                                   |
| :-------------------- | --------- | :--- | :---------------------------------------------------------------------------------------- |
| display               | 🚫        |      | By default, grids are `display: grid`. There is no use-case for inline-grid at the moment |
| grid-template-columns | 🚫        |      | This value is pre-determined by the IBM Design Language                                   |
| grid-template-rows    | 🚫        |      | No suitable JavaScript-based API available, use CSS directly                              |
| grid-template-areas   | 🚫        |      | No suitable JavaScript-based API available, use CSS directly                              |
| grid-template         | 🚫        |      | No suitable JavaScript-based API available, use CSS directly                              |
| grid-column-gap       | 🚫        |      | This value is pre-determined by the IBM Design Language                                   |
| grid-row-gap          | ⚠️        |      | This could be provided from the spacing scale, overlaps with `Stack` component            |
| grid-gap              | 🚫        |      | Unable to override column gap, row gap may be set in CSS                                  |
| justify-items         | ✅        |      |                                                                                           |
| align-items           | ✅        |      |                                                                                           |
| place-items           | ✅        |      |                                                                                           |
| justify-content       | ✅        |      |                                                                                           |
| align-content         | ✅        |      |                                                                                           |
| place-content         | ✅        |      |                                                                                           |
| grid-auto-columns     | 🚫        |      | This value is not valuable with a pre-determined grid                                     |
| grid-auto-rows        | ⚠️        |      | This could be helpful in specific contexts, overlaps with `Stack`                         |
| grid-auto-flow        | ⚠️        |      | This could be helpful for layouts                                                         |
| grid                  | 🚫        |      | This shorthand should be set in CSS directly                                              |

**Grid item**

| CSS Property        | Supported | Prop | Context                                                      |
| :------------------ | --------- | :--- | :----------------------------------------------------------- |
| `grid-column-start` | ⚠️        |      | Limited support, available if value aligns with grid         |
| `grid-column-end`   | ⚠️        |      | Limited support, available if value aligns with grid         |
| `grid-row-start`    | 🚫        |      | Unable to offer meaningful support out-of-the-box            |
| `grid-row-end`      | 🚫        |      | Unable to offer meaningful support out-of-the-box            |
| `grid-column`       | ⚠️        |      | Shorthand could be helpful                                   |
| `grid-row`          | ⚠️        |      | Shorthand could be helpful                                   |
| `grid-area`         | 🚫        |      | No suitable JavaScript-based API available, use CSS directly |
| `justify-self`      | ✅        |      |                                                              |
| `align-self`        | ✅        |      |                                                              |
| `place-self`        | ✅        |      |                                                              |

**Comment by joshblack** [comment]
I think we ended up with a good style for v11, going to close this out for now 👀
