### ISSUE TITLE
[Bug]: Can't pass children to styled(Button) (Typescript)

### ISSUE THREAD

**Issue by imp-dance** [carbon-design-system/carbon#10479]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

7.51.0

### React version

16.13.1

### Description

I've recently upgraded to version 7.51.0, (and `@types/carbon-components-react@7.49-0`) and in doing so I gained a bunch of compile errors. Some seem to be related to prop-updates, which is fine but I'm getting a new strange bug that I did not have in my project previously.

We use `styled-components`, and a common pattern when using the package is to extend the styles of react components like such:

```typescript
import { Button } from "carbon-components-react";
import styled from "styled-components";
 
const StyledButton = styled(Button)`
   color: red;
`
```

This worked perfectly fine in the previous version I was running (7.34 @types/7.33), but now - I for some reason get a compile error on all styled components that are based on carbon's Button component. The compile errors look something like this, and all point to instances of styled buttons:

```
This JSX tag's 'children' prop expects a single child of type 'never', but multiple children were provided.
```

 ```
 This JSX tag's 'children' prop expects type 'never' which requires multiple children, but only a single child was provided.
  ```
  
  ```
  No overload matches this call.
Overload 2 of 2, '(props: StyledComponentPropsWithAs<{ (props: ForwardRefProps<HTMLButtonElement, ButtonDefaultProps & ButtonKindProps>): ReactElement<any, any>; (props: ForwardRefProps<...>): ReactElement<...>; <T extends keyof IntrinsicElements, R extends HTMLElement = HTMLElement>(props: ForwardRefProps<...>)...
```

You can see the prop invalidation when hovering `StyledButton` in the CodeSandbox example. 

I'm not sure if this is something for you to fix, or if it's an issue with how styled-components work or something, but I figured since this surely must be a common pattern (styled-components + carbon-components-react) you'd like to know about it. For us, this is a pretty big issue that will block us from updating for now. 

This might be a similar issue to [this one](https://github.com/geist-org/geist-ui/issues/34) that I found on another component library, so I'll leave that link here just in case you find it helpful. 

### CodeSandbox example

https://codesandbox.io/s/react-typescript-forked-st1rs?file=/src/App.tsx

### Steps to reproduce

1. Setup typescript/react carbon-components & styled-components
2. Create a "styled" component out of carbon's `Button` component (`styled(Button)`)
3. See Typescript compile error (or hover over the button to see type error)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there, @imp-dance! 👋  Unfortunately, our group does not maintain the TypeScript types over on DefinitelyTyped. I'm not sure what support we can offer for this at the moment, as a result.

In the future, we're hoping to look into shipping official types for our packages but this is not currently a priority for our team.

Let me know if you have any questions!
