### ISSUE TITLE
[Question]: Usage mode option for the vanilla library to mimic the web components responsiveness

### ISSUE THREAD

**Issue by danbaghilovici** [carbon-design-system/carbon#10480]
### Question for Carbon

Hello, 

I was exploring the components section from the website and I have come across this [header example](https://web-components.carbondesignsystem.com/?path=/story/components-ui-shell--header)

![image](https://user-images.githubusercontent.com/47480841/150195388-1c666da1-5206-47b9-8086-8c98d69d932c.png)
with this particular configuration, the header nav disappears on smaller screens and the side nav appears instead, which is what I was looking for.

But my issue is that I want to use the [vanilla library](https://www.carbondesignsystem.com/developing/frameworks/vanilla/) which has its own [ui shell component](https://the-carbon-components.netlify.app/?nav=ui-shell) and from the examples the page I don't see any options to configure the vanilla ui header to behave like the one that it's made from web components.

I tried to look at the source code of the vanilla library but I haven't seen any properties to change that behavior. Does the vanilla version include those options or it's only available for the other frameworks?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there, @dntzbgh! 👋  Thanks so much for taking the time to write out this issue.

Unfortunately, the vanilla library for our work is in maintenance mode at the moment. As a result, new functionality is unlikely to be introduced by our team. We've been recommending teams who are introduced in Vanilla JavaScript to switch over to the Web Components library as a result.

I'm so sorry about this situation. I wish we could offer better support for the use case you described as I think it's an incredibly valid one. Let me know if you have any follow-up questions about this.

**Comment by dntzbgh** [comment]
Oh so it's in maintenance mode, I see. That explains why some of the builds failed when I tried to compile the styles.

Unfortunately, I can't switch to Web Components for now but I will keep it in mind. I will fix my issues with some custom styles and I think that for now it might work.

I will join watch this repo and join the discord server in order to be up to date with the changes on the library.

Keep up the good work!
