### ISSUE TITLE
sass: Incorrect font-face rules generated when using non-default font-path

### ISSUE THREAD

**Issue by subinpc** [carbon-design-system/carbon#1049]
## Detailed description

I'm reporting a bug in one of the sass files.
When I set `$font-path: <custom value>`, the generated font-face rules look like the following -
```
@font-face {
  else {
    font-family: 'ibm-plex-mono';
    font-style: normal;
    font-weight: 600;
    src: url("/mypath/assets/fonts/IBMPlexMono-SemiBold-Latin3.woff2") format("woff2");
    unicode-range: "U+0102-0103, U+1EA0-1EF9, U+20AB"; } }
```
These rules are invalid and are not honoured by the browser. (Note: sass compiler does not throw any error.)

This is happening because there is a typo in the invocation of `@else` directive  in the mixin `check-default-font-path` (in https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_css--plex-core.scss)

Observed in latest version (v9.8.4).

## Add labels
`bug` `Severity 2`

**Comment by asudoh** [comment]
Thank you for reporitng @subinpc! Dup of: https://github.com/IBM/carbon-components/issues/1047
