### ISSUE TITLE
Any plans to add a skeleton state for the Tile component?

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#1050]
## Detailed description

I'd like to request that skeleton states be added for the Tile component.  We have a usecase with several graph tiles that are loading data, and I'd like for them to skeleton out like the other carbon components.  Here's what they look like rendered, you can imagine the skeleton state.

![image](https://user-images.githubusercontent.com/6663002/44746315-9df79200-aacf-11e8-8dd6-c7cd2ddae80b.png)

> Is this issue related to a specific component?

Tile
> What did you expect to happen? What happened instead? What would you like to see changed?

Requesting an enhancement request to support skeleton state to the tile component.  Would also like to see this ported to the React component.
> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

9.7.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Add labels

Enhancement request

**Comment by alisonjoseph** [comment]
Hey Scott, glad to hear you are using the skeleton components. I think the decision not to build one originally for the tile was because it is a wrapper element. The thinking was that you would use the skeleton state on whatever specific components are placed inside of it. (since that varies for everyone)

**Comment by scottdickerson** [comment]
on second thought, I understand there's no structure to the Tile component so how could you make skeleton text look like the possible contents...
