### ISSUE TITLE
Need to understand the why validation error message looks different for number input compared to other input elements

### ISSUE THREAD

**Issue by subinpc** [carbon-design-system/carbon#1051]
## Detailed description
I would like to understand why the style for number-input validation error is different from the style for other form field validation errors?
    ![image 5](https://user-images.githubusercontent.com/30194618/44775821-2b9cb580-ab94-11e8-8c14-5ba68a3d3dee.png)

> Is this issue related to a specific component?

form input components

## Add labels
`discussion`

**Comment by asudoh** [comment]
@subinpc Thank you for reporting - For better manager the issues, could you please split those two…? Thanks!

**Comment by subinpc** [comment]
@asudoh, I've moved my second question to a separate issue - #1052.

**Comment by alisonjoseph** [comment]
Hi, thanks for pointing this out. Looks like bug, they should look the same and not have the extra red line below.
