### ISSUE TITLE
[Bug]: CopyButton needs tooltipAlignment and tooltipPosition functionality

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/carbon#10518]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.51.0 (latest)

### React version

v17.0.2

### Description

When using the `CopyButton` component, the `feedback` tooltip seems to always be set to the bottom position, and center alignment. 

Example of issue:
If we use the `CopyButton` near the right-side of the page, after clicking the Copy button, a scrollbar appears because of the feedback tooltip being centered and pushing text even farther to the right side. 
<img width="626" alt="Screen Shot 2022-01-25 at 11 10 07 AM" src="https://user-images.githubusercontent.com/37594705/151014383-48620801-a296-4318-817a-c79c5f2afad3.png">
A horizontal scrollbar appears because of the feedback tooltip. 

Request is to allow developers using this component to pass-in the `tooltipAlignment` and `tooltipPosition` fields so that we can avoid this from happening.

Additional Request: It would also be nice to have a built-in tooltip for the hover-over as well

### CodeSandbox example

https://codesandbox.io/s/nifty-sky-g5083?file=/src/index.js

### Steps to reproduce

- Simply create a `CopyButton` component near the right side of the page
- Set the `feedback` text to be fairly long
- Click the Copy button, and the feedback tooltip will always be bottom and centered and unconfigurable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
This functionality was implemented in this [PR](https://github.com/carbon-design-system/carbon/pull/14653) with the prop `align`

![Screenshot 2024-01-09 at 17 29 49](https://github.com/carbon-design-system/carbon/assets/52183462/499f6a88-3493-458d-a3ac-c8fcbb349339)

**Comment by David-Yuen** [comment]
@guidari was this delivered to carbon v10? 

I think i saw the PR delivered to v11, but not sure about v10. Please confirm

**Comment by guidari** [comment]
> @guidari was this delivered to carbon v10?
> 
> I think i saw the PR delivered to v11, but not sure about v10. Please confirm

Ohh, you are right @David-Yuen it was only delivered on v11 not in v10.
I'll reopen the issue! Sorry for the misunderstanding
