### ISSUE TITLE
[Bug]: CopyButton tooltip wrong styles and inconsistent

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/carbon#10524]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.51.0 (latest)

### React version

v17.0.2

### Description

When hovering over the `CopyButton`, the tooltip that appears on the icon is different from the one from `Button`. 
Both are considered "Buttons" (but implemented differently) and with icons, and it would be expected that the `iconDescription` should operate the same.

But instead, when hovering over a `CopyButton`, it uses i think the html version of a tooltip.. It should be using carbon's tooltip instead.
<img width="303" alt="Screen Shot 2022-01-25 at 2 54 05 PM" src="https://user-images.githubusercontent.com/37594705/151049535-c4822c90-272f-4506-aaec-c17f5b552e7f.png">
I am not able to do a screenshot of this tooltip in windows, so this screenshot is from mac instead. On my mac, it is currently set to Dark mode possibly why this tooltip has a darker background. But in windows, this version of the tooltip has a background color that is more white.
So within this version of the tooltip, it is already inconsistent to our web application, because it depends on the OS/browser instead. 
The feedback tooltip is correct, but the hover-over tooltip uses the wrong version and creates inconsistencies.

When using `Button` (`hasIconOnly` flag on), you can set the `iconDescription` and it will use the carbon's tooltip.
<img width="231" alt="Screen Shot 2022-01-25 at 2 50 19 PM" src="https://user-images.githubusercontent.com/37594705/151048965-1c885dbe-f6f4-48ed-ac6a-9dd9d94b3005.png">

The tooltip design, padding, color, etc.. all styles, timing, functionality are different here, but both `CopyButton` and `Button` (with hasIconOnly) is still a button with an icon. It should be consistent

Simply, `CopyButton` should re-use carbon's tooltip version (and allow tooltip configurations like `position` and `alignment`) would resolve all the above inconsistencies.
 

### CodeSandbox example

https://codesandbox.io/s/modest-ishizaka-ovn5p

### Steps to reproduce

Create a `CopyButton` component, and add a string value to `iconDescription`.
Run application and mouse hover over the button. The tooltip will appear

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sstrubberg** [comment]
Looks like this was taken care of in a different issue. Feel free to re-open if I got that wrong.
