### ISSUE TITLE
[Bug]: v11 grid lacks padding on sm and overflows if narrow is used

### ISSUE THREAD

**Issue by ishitatsuyuki** [carbon-design-system/carbon#10540]
### Package

carbon-components-react, @carbon/grid

### Browser

Firefox

### Package version

grid 10.40.0 (v11/modules)

### React version

v0.13.0-rc0

### Description

v11 grid lacks the padding on small viewports (in v10 there was a 16px padding for mobile as opposed to 32px on desktop) and narrow columns overflows the root container.

![image](https://user-images.githubusercontent.com/12389383/151321637-8a18436d-746e-4781-8fcd-d442308ea149.png)

### CodeSandbox example

https://carbon-react-next.netlify.app/?path=/story/elements-grid--mixed-grid-modes

### Steps to reproduce

Press "Change the size of the preview" in toolbar, select "Small".

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
cc @tay1orjones

**Comment by tay1orjones** [comment]
Thanks for reporting this @ishitatsuyuki. The narrow grid mode is going to be removed from the CSS Grid implementation for now as we explore the issues related to it (like this one you found here! 😄 ), #10620

Could you share what type of layouts you're trying to make with the narrow grid mode? It would help inform our further experiments with narrow grid mode using CSS Grid.

**Comment by tay1orjones** [comment]
Closing per the above, but happy to continue the conversation about layouts you're trying to achieve below. Thanks!

**Comment by ishitatsuyuki** [comment]
My issue is the lack of padding that has existed before, and I'm not using narrow grid. It was used as an argument for how this behavior change could be problematic.

I'm using the grid as a top-level container: I expect any text inside it (actually, inside a column) to be padded against the edge of the screen. As I described, this works properly on desktop, but not on mobile.

It is a behavior change from the v10 grid, which had 16px padding on mobile. You can check this behavior in the v10 storybook: https://react.carbondesignsystem.com/?path=/story/components-grid--mixed-grid-modes. That storybook version doesn't have responsive design mode, so you need to use your browser's one instead.
