### ISSUE TITLE
[Bug]: Search only in DataTable toolbar causes overflow (scroll bar)

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#10554]
### Package

carbon-components

### Browser

Chrome

### Package version

10.50

### React version

16

### Description

The expandable search, used in the table, reserves padding left and right (2 x height) when not expanded. With only search in the toolbar and the table full screen it overflows causing a scroll bar.

### CodeSandbox example

https://codesandbox.io/s/carbon-issue-10554-4k83l

### Steps to reproduce

Load up codesandbox

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I believe this was recently fixed in https://github.com/carbon-design-system/carbon/pull/10520 (https://github.com/carbon-design-system/carbon/issues/10519). Going to close this as resolved, but let me know if this doesn't fix your issue
