### ISSUE TITLE
Document Tooltip/Popover, migration path

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10564]
**Checklist**

- [x] Capture prop types of impacted components in v10
- [x] Determine replacement or changes for v11
- [ ] Add content to v11 migration guide

**Comment by joshblack** [comment]
## Tooltip

| v10 | Type | v11 | Type |
| :-- | :--- | :-- | :--- |
| `align` | `PropTypes.oneOf(['start', 'center', 'end'])` | | |
| `autoOrientation` | `PropTypes.bool` | | |
| `children` | `PropTypes.node` | | |
| `className` | `PropTypes.string` | | |
| `defaultOpen` | `PropTypes.bool` | | |
| `direction` | `PropTypes.oneOf(['bottom', 'top', 'left', 'bottom'])` | | |
| `focusTrap` | `PropTypes.bool` | | |
| `iconName` | `PropTypes.string` | | |
| `menuOffset` | `PropTypes.oneOfType([PropTypes.shape({ top: number, left: number }), ProPTypes.fun])` | | |
| `onChange` | `PropTypes.func` | | |
| `open` | `PropTypes.bool` | | |
| `renderIcon` | `function` | | |
| `selectorPrimaryFocus` | `PropTypes.string` | | |
| `showIcon` | `PropTypes.bool` | | |
| `tabIndex` | `PropTypes.number` | | |
| `tooltipBodyId` | `PropTypes.string` | | |
| `tooltipId` | `PropTypes.string` | | |
| `triggerClassName` | `PropTypes.string` | | |
| `triggerId` | `PropTypes.string` | | |
| `triggerText` | `PropTypes.node` | | |
| `iconDescription` | `PropTypes.string` | | |

**Comment by dakahn** [comment]
@joshblack updated your comment with the results of prop audit pass 🏄🏾
