### ISSUE TITLE
Document Sass API for each elements package

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10566]
| Package | Audit | Docs |
| :------ | :------- | :--- |
| `@carbon/colors` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028371790) | ✅ |
| `@carbon/elements` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028373069) | ✅ |
| `@carbon/grid` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028373198) | |
| `@carbon/layout` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028379813) | ✅ |
| `@carbon/motion` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028389332) | ✅ |
| `@carbon/styles` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028415020) | ✅ |
| `@carbon/themes` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028414842) | ✅ |
| `@carbon/type` | [Link](https://github.com/carbon-design-system/carbon/issues/10566#issuecomment-1028414898) | ✅ |

**Template**

```md
# `@carbon/package-name`

> Sass documentation for `@carbon/package-name`

_Note: this documentation is used with the next version of `@carbon/themes`
which uses Sass Modules. It will not work in the current stable version of this
package_

<!-- prettier-ignore-start -->
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
## Table of Contents

<!-- END doctoc generated TOC please keep comment here to allow auto update -->
<!-- prettier-ignore-end -->

## Usage

## API

## FAQ

```

**Checklist**

- Does the package have documentation at `docs/sass.md`?
- In the documentation:
  - Does it have a usage section?
  - Does it have an exports section?
- Has anything changed for this package between v10 and v11?
  - If so, has it been documented in `v11.md`?

**Comment by joshblack** [comment]
## @carbon/colors

**Checklist**

- [x] Does the package have documentation at `docs/sass.md`?
- [x] In the documentation:
  - [x] Does it have a usage section?
  - [x] Does it have an exports section?
- [x] Has anything changed for this package between v10 and v11?
  - [x] If so, has it been documented in `v11.md`?

**Changes**

- There is no longer an `scss` folder, there is only a single `index.scss` file
  - `scss/index.scss` (brings in mixins)
  - `scss/colors.scss` (brings in mixins)
  - `scss/mixins.scss`
    - `$ibm-color__*`
    - `$carbon--*`
    - `$<swatch>-<grade>`
    - `$<swatch>-<grade>-hover`
    - `$ibm-color-map`
    - `$carbon--colors`
    - `@mixin ibm--colors`
    - `@mixin carbon--colors`

**Comment by joshblack** [comment]
## @carbon/elements

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?

**Changes**

**Comment by joshblack** [comment]
## @carbon/grid

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?

**Changes**

**Comment by joshblack** [comment]
## @carbon/layout

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?

**Changes**

**Comment by joshblack** [comment]
## @carbon/motion

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?

**Changes**

**Comment by joshblack** [comment]
## @carbon/themes

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?
  - [ ] Are there any changes that need to be made in the `carbon-components` package?
  - [ ] Are there any changes that need to be made in the `@carbon/styles` package?
  - [ ] Are there any changes that need to be made in the `@carbon/react` package?
  - [ ] For things that have been removed, have we specified a replacement?

**Next steps**

**Comment by joshblack** [comment]
## @carbon/type

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?
  - [ ] Are there any changes that need to be made in the `carbon-components` package?
  - [ ] Are there any changes that need to be made in the `@carbon/styles` package?
  - [ ] Are there any changes that need to be made in the `@carbon/react` package?
  - [ ] For things that have been removed, have we specified a replacement?

**Next steps**

**Comment by joshblack** [comment]
## @carbon/styles

**Checklist**

- [ ] Does the package have documentation at `docs/sass.md`?
- [ ] In the documentation:
  - [ ] Does it have a usage section?
  - [ ] Does it have an exports section?
- [ ] Has anything changed for this package between v10 and v11?
  - [ ] If so, has it been documented in `v11.md`?
  - [ ] Are there any changes that need to be made in the `carbon-components` package?
  - [ ] Are there any changes that need to be made in the `@carbon/styles` package?
  - [ ] Are there any changes that need to be made in the `@carbon/react` package?
  - [ ] For things that have been removed, have we specified a replacement?

**Next steps**
