### ISSUE TITLE
Refactor usage of `Button` `hasIconOnly` to `IconButton`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10561]
Components using icon buttons:

- [x] Pagination
- [x] PaginationNav
- [x] UI Shell (HeaderGlobalAction)
- [ ] Data Table (TableBatchAction)

Open questions
- Could Button return Iconbutton w/ the appropriate props?
- Could we codemod this?
- How do the new tabs build their "icon only" variant?

Next steps

- These components are using their own button and should be refactored
  - [x] CodeSnippet (uses CopyButton)
  - [x] CopyButton (uses Copy)
    - #10519
    - #10524
  - [ ] TooltipIcon -> (IconButton)
  - [ ] Modal, ModalHeader
  - [ ] Notification
  - [ ] NumberInput
  - [ ] Search, SearchFilterButton
  - [ ] ProgressIndicator
  - [ ] OverflowMenu
  
- Run the codemod from mob programming (discord voice chat) against the codebase
- Include the codemod as part of the upgrade cli

**Comment by tay1orjones** [comment]
If this isn't delivered as part of v11, we need to reinstate button tooltip trigger styles as identified in https://github.com/carbon-design-system/carbon/issues/10483#issuecomment-1024691843

**Comment by tay1orjones** [comment]
Here's a link to the codemod I've been gnawing on https://astexplorer.net/#/gist/20b31441b64ba59160f38b00a38d4c58/0c5f710c628aeb47183dbd6d057683a132bb389b

**Comment by jnm2377** [comment]
Rel https://github.com/carbon-design-system/carbon/issues/10717
