### ISSUE TITLE
Audit data-table styles

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10571]
High level steps to take for each component are outlined in the [parent issue](https://github.com/carbon-design-system/carbon/issues/9805#issuecomment-1026166086).

If there's no actionable items to PR, just close this issue without a linked PR

**Comment by joshblack** [comment]
## Files

| components | styles | Checked |
| :--------- | :----- | :------ |
| `_data-table.scss` | | |
| `_data-table-action.scss` | | |
| `_data-table-core.scss` | | |
| `_data-table-expandable.scss` | | |
| `_data-table-sort.scss` | | |
| `_data-table-inline-edit.scss` | | |
| `_data-table-skeleton.scss` | | |
