### ISSUE TITLE
feat(text-input): Add Show/hide password for password inputs

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#1058]
I'm currently working on adding password visibility toggle to the text input component, first adding it to the vanilla component before porting it to the React component (related: https://github.com/IBM/carbon-components-react/issues/1033)

While previewing my changes, I noticed this:

In the documentation page, there is a style rule which places `min-width: 20rem` on `.component-example__live .text-input .bx--text-input`, but within [`text-input.hbs` there is an inline style rule that forces one of the examples to have a width of 300px (or 18.75rem)](https://github.com/IBM/carbon-components/blob/master/src/components/text-input/text-input.hbs#L22). What happens then is that the text input field will actually extend beyond the width of its container. I've highlighted how this affects the placement of my password visibility toggle in the screenshot below, but I just wanted to know if the `min-width` of the text input was meant to conflict with the inline styles on the example in the docs.

<img width="742" alt="screen shot 2018-08-31 at 10 30 50 am" src="https://user-images.githubusercontent.com/8265238/44921736-01b8cf80-ad09-11e8-8c78-58a33e90f440.png">

**Comment by alisonjoseph** [comment]
The width in the doc example was added to show how text could wrap, would probably be good to update this however so the width and min-width don't interfere with each other. Feel free to include that in your PR if you would like.

**Comment by emyarod** [comment]
hi @alisonjoseph thanks for the explanation. I think setting the inline width in the example to 320px/18rem would solve the problem since the text will still wrap, if that's alright. I just wanted to know if that 300px inline width had to be 300px exactly

**Comment by alisonjoseph** [comment]
Yes, that should be fine 👍
