### ISSUE TITLE
Audit overflow-menu styles

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10587]
High level steps to take for each component are outlined in the [parent issue](https://github.com/carbon-design-system/carbon/issues/9805#issuecomment-1026166086).

If there's no actionable items to PR, just close this issue without a linked PR

**Comment by joshblack** [comment]
- [Source](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/overflow-menu/_overflow-menu.scss)
- [Target](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/overflow-menu/_overflow-menu.scss)

## Selectors

| Selector                                                                                               | Original | Next |
| :----------------------------------------------------------------------------------------------------- | :------- | :--- |
| `html`                                                                                                 | ✅       | 🚫   |
| `body`                                                                                                 | ✅       | 🚫   |
| `div`                                                                                                  | ✅       | 🚫   |
| `span`                                                                                                 | ✅       | 🚫   |
| `applet`                                                                                               | ✅       | 🚫   |
| `object`                                                                                               | ✅       | 🚫   |
| `iframe`                                                                                               | ✅       | 🚫   |
| `h1`                                                                                                   | ✅       | 🚫   |
| `h2`                                                                                                   | ✅       | 🚫   |
| `h3`                                                                                                   | ✅       | 🚫   |
| `h4`                                                                                                   | ✅       | 🚫   |
| `h5`                                                                                                   | ✅       | 🚫   |
| `h6`                                                                                                   | ✅       | 🚫   |
| `p`                                                                                                    | ✅       | 🚫   |
| `blockquote`                                                                                           | ✅       | 🚫   |
| `pre`                                                                                                  | ✅       | 🚫   |
| `a`                                                                                                    | ✅       | 🚫   |
| `abbr`                                                                                                 | ✅       | 🚫   |
| `acronym`                                                                                              | ✅       | 🚫   |
| `address`                                                                                              | ✅       | 🚫   |
| `big`                                                                                                  | ✅       | 🚫   |
| `cite`                                                                                                 | ✅       | 🚫   |
| `code`                                                                                                 | ✅       | 🚫   |
| `del`                                                                                                  | ✅       | 🚫   |
| `dfn`                                                                                                  | ✅       | 🚫   |
| `em`                                                                                                   | ✅       | 🚫   |
| `img`                                                                                                  | ✅       | 🚫   |
| `ins`                                                                                                  | ✅       | 🚫   |
| `kbd`                                                                                                  | ✅       | 🚫   |
| `q`                                                                                                    | ✅       | 🚫   |
| `s`                                                                                                    | ✅       | 🚫   |
| `samp`                                                                                                 | ✅       | 🚫   |
| `small`                                                                                                | ✅       | 🚫   |
| `strike`                                                                                               | ✅       | 🚫   |
| `strong`                                                                                               | ✅       | 🚫   |
| `sub`                                                                                                  | ✅       | 🚫   |
| `sup`                                                                                                  | ✅       | 🚫   |
| `tt`                                                                                                   | ✅       | 🚫   |
| `var`                                                                                                  | ✅       | 🚫   |
| `b`                                                                                                    | ✅       | 🚫   |
| `u`                                                                                                    | ✅       | 🚫   |
| `i`                                                                                                    | ✅       | 🚫   |
| `center`                                                                                               | ✅       | 🚫   |
| `dl`                                                                                                   | ✅       | 🚫   |
| `dt`                                                                                                   | ✅       | 🚫   |
| `dd`                                                                                                   | ✅       | 🚫   |
| `ol`                                                                                                   | ✅       | 🚫   |
| `ul`                                                                                                   | ✅       | 🚫   |
| `li`                                                                                                   | ✅       | 🚫   |
| `fieldset`                                                                                             | ✅       | 🚫   |
| `form`                                                                                                 | ✅       | 🚫   |
| `label`                                                                                                | ✅       | 🚫   |
| `legend`                                                                                               | ✅       | 🚫   |
| `table`                                                                                                | ✅       | 🚫   |
| `caption`                                                                                              | ✅       | 🚫   |
| `tbody`                                                                                                | ✅       | 🚫   |
| `tfoot`                                                                                                | ✅       | 🚫   |
| `thead`                                                                                                | ✅       | 🚫   |
| `tr`                                                                                                   | ✅       | 🚫   |
| `th`                                                                                                   | ✅       | 🚫   |
| `td`                                                                                                   | ✅       | 🚫   |
| `article`                                                                                              | ✅       | 🚫   |
| `aside`                                                                                                | ✅       | 🚫   |
| `canvas`                                                                                               | ✅       | 🚫   |
| `details`                                                                                              | ✅       | 🚫   |
| `embed`                                                                                                | ✅       | 🚫   |
| `figure`                                                                                               | ✅       | 🚫   |
| `figcaption`                                                                                           | ✅       | 🚫   |
| `footer`                                                                                               | ✅       | 🚫   |
| `header`                                                                                               | ✅       | 🚫   |
| `hgroup`                                                                                               | ✅       | 🚫   |
| `menu`                                                                                                 | ✅       | 🚫   |
| `nav`                                                                                                  | ✅       | 🚫   |
| `output`                                                                                               | ✅       | 🚫   |
| `ruby`                                                                                                 | ✅       | 🚫   |
| `section`                                                                                              | ✅       | 🚫   |
| `summary`                                                                                              | ✅       | 🚫   |
| `time`                                                                                                 | ✅       | 🚫   |
| `mark`                                                                                                 | ✅       | 🚫   |
| `audio`                                                                                                | ✅       | 🚫   |
| `video`                                                                                                | ✅       | 🚫   |
| `button`                                                                                               | ✅       | 🚫   |
| `select`                                                                                               | ✅       | 🚫   |
| `input`                                                                                                | ✅       | 🚫   |
| `textarea`                                                                                             | ✅       | 🚫   |
| `input[type=text]::-ms-clear`                                                                          | ✅       | 🚫   |
| `main`                                                                                                 | ✅       | 🚫   |
| `blockquote::before`                                                                                   | ✅       | 🚫   |
| `blockquote::after`                                                                                    | ✅       | 🚫   |
| `q::before`                                                                                            | ✅       | 🚫   |
| `q::after`                                                                                             | ✅       | 🚫   |
| `*`                                                                                                    | ✅       | 🚫   |
| `svg`                                                                                                  | ✅       | 🚫   |
| `.ds--assistive-text`                                                                                  | ✅       | 🚫   |
| `.ds--visually-hidden`                                                                                 | ✅       | 🚫   |
| `.ds--body`                                                                                            | ✅       | 🚫   |
| `.ds--body *`                                                                                          | ✅       | 🚫   |
| `.ds--body *::before`                                                                                  | ✅       | 🚫   |
| `.ds--body *::after`                                                                                   | ✅       | 🚫   |
| `.ds--text-truncate--end`                                                                              | ✅       | 🚫   |
| `.ds--text-truncate--front`                                                                            | ✅       | 🚫   |
| `.ds--overflow-menu`                                                                                   | ✅       | ✅   |
| `.ds--overflow-menu__trigger`                                                                          | ✅       | ✅   |
| `.ds--overflow-menu *`                                                                                 | ✅       | ✅   |
| `.ds--overflow-menu *::before`                                                                         | ✅       | ✅   |
| `.ds--overflow-menu *::after`                                                                          | ✅       | ✅   |
| `.ds--overflow-menu__trigger *`                                                                        | ✅       | ✅   |
| `.ds--overflow-menu__trigger *::before`                                                                | ✅       | ✅   |
| `.ds--overflow-menu__trigger *::after`                                                                 | ✅       | ✅   |
| `.ds--overflow-menu::-moz-focus-inner`                                                                 | ✅       | ✅   |
| `.ds--overflow-menu__trigger::-moz-focus-inner`                                                        | ✅       | ✅   |
| `.ds--overflow-menu:focus`                                                                             | ✅       | ✅   |
| `.ds--overflow-menu__trigger:focus`                                                                    | ✅       | ✅   |
| `.ds--overflow-menu:hover`                                                                             | ✅       | ✅   |
| `.ds--overflow-menu__trigger:hover`                                                                    | ✅       | ✅   |
| `.ds--overflow-menu--sm`                                                                               | ✅       | ✅   |
| `.ds--overflow-menu--xl`                                                                               | ✅       | ✅   |
| `.ds--overflow-menu--lg`                                                                               | ✅       | ✅   |
| `.ds--overflow-menu__trigger.ds--tooltip--a11y.ds--tooltip__trigger:focus`                             | ✅       | ✅   |
| `.ds--overflow-menu__trigger.ds--tooltip--a11y.ds--tooltip__trigger:focus svg`                         | ✅       | ✅   |
| `.ds--overflow-menu.ds--overflow-menu--open`                                                           | ✅       | ✅   |
| `.ds--overflow-menu.ds--overflow-menu--open .ds--overflow-menu__trigger`                               | ✅       | ✅   |
| `.ds--overflow-menu--light.ds--overflow-menu--open`                                                    | ✅       | ✅   |
| `.ds--overflow-menu--light.ds--overflow-menu--open .ds--overflow-menu__trigger`                        | ✅       | ✅   |
| `.ds--overflow-menu__icon`                                                                             | ✅       | ✅   |
| `.ds--overflow-menu-options`                                                                           | ✅       | ✅   |
| `.ds--overflow-menu-options *`                                                                         | ✅       | 🚫   |
| `.ds--overflow-menu-options *::before`                                                                 | ✅       | 🚫   |
| `.ds--overflow-menu-options *::after`                                                                  | ✅       | 🚫   |
| `.ds--overflow-menu-options::after`                                                                    | ✅       | ✅   |
| `.ds--overflow-menu.ds--overflow-menu--open:hover`                                                     | ✅       | ✅   |
| `.ds--overflow-menu-options--light`                                                                    | ✅       | ✅   |
| `.ds--overflow-menu-options--light::after`                                                             | ✅       | ✅   |
| `.ds--overflow-menu.ds--overflow-menu--light.ds--overflow-menu--open:hover`                            | ✅       | ✅   |
| `.ds--overflow-menu-options[data-floating-menu-direction=bottom]::after`                               | ✅       | ✅   |
| `.ds--overflow-menu-options[data-floating-menu-direction=top]::after`                                  | ✅       | ✅   |
| `.ds--overflow-menu-options[data-floating-menu-direction=left]::after`                                 | ✅       | ✅   |
| `.ds--overflow-menu-options[data-floating-menu-direction=right]::after`                                | ✅       | ✅   |
| `.ds--overflow-menu-options--sm.ds--overflow-menu-options[data-floating-menu-direction=bottom]::after` | ✅       | ✅   |
| `.ds--overflow-menu-options--sm.ds--overflow-menu-options[data-floating-menu-direction=top]::after`    | ✅       | ✅   |
| `.ds--overflow-menu-options--sm.ds--overflow-menu-options[data-floating-menu-direction=left]::after`   | ✅       | ✅   |
| `.ds--overflow-menu-options--sm.ds--overflow-menu-options[data-floating-menu-direction=right]::after`  | ✅       | ✅   |
| `.ds--overflow-menu-options--xl.ds--overflow-menu-options[data-floating-menu-direction=bottom]::after` | ✅       | ✅   |
| `.ds--overflow-menu-options--xl.ds--overflow-menu-options[data-floating-menu-direction=top]::after`    | ✅       | ✅   |
| `.ds--overflow-menu-options--lg.ds--overflow-menu-options[data-floating-menu-direction=bottom]::after` | ✅       | ✅   |
| `.ds--overflow-menu-options--lg.ds--overflow-menu-options[data-floating-menu-direction=top]::after`    | ✅       | ✅   |
| `.ds--overflow-menu-options--xl.ds--overflow-menu-options[data-floating-menu-direction=left]::after`   | ✅       | ✅   |
| `.ds--overflow-menu-options--xl.ds--overflow-menu-options[data-floating-menu-direction=right]::after`  | ✅       | ✅   |
| `.ds--overflow-menu-options--lg.ds--overflow-menu-options[data-floating-menu-direction=left]::after`   | ✅       | ✅   |
| `.ds--overflow-menu-options--lg.ds--overflow-menu-options[data-floating-menu-direction=right]::after`  | ✅       | ✅   |
| `.ds--overflow-menu--flip.ds--overflow-menu-options[data-floating-menu-direction=top]::after`          | ✅       | ✅   |
| `.ds--overflow-menu--flip.ds--overflow-menu-options[data-floating-menu-direction=bottom]::after`       | ✅       | ✅   |
| `.ds--overflow-menu--flip.ds--overflow-menu-options[data-floating-menu-direction=left]::after`         | ✅       | ✅   |
| `.ds--overflow-menu--flip.ds--overflow-menu-options[data-floating-menu-direction=right]::after`        | ✅       | ✅   |
| `.ds--overflow-menu-options--open`                                                                     | ✅       | ✅   |
| `.ds--overflow-menu-options__content`                                                                  | ✅       | ✅   |
| `.ds--overflow-menu-options__option`                                                                   | ✅       | ✅   |
| `.ds--overflow-menu-options__option *`                                                                 | ✅       | 🚫   |
| `.ds--overflow-menu-options__option *::before`                                                         | ✅       | 🚫   |
| `.ds--overflow-menu-options__option *::after`                                                          | ✅       | 🚫   |
| `.ds--overflow-menu-options--sm .ds--overflow-menu-options__option`                                    | ✅       | ✅   |
| `.ds--overflow-menu-options--xl .ds--overflow-menu-options__option`                                    | ✅       | ✅   |
| `.ds--overflow-menu-options--lg .ds--overflow-menu-options__option`                                    | ✅       | ✅   |
| `.ds--overflow-menu--divider`                                                                          | ✅       | ✅   |
| `.ds--overflow-menu--light .ds--overflow-menu--divider`                                                | ✅       | ✅   |
| `a.ds--overflow-menu-options__btn::before`                                                             | ✅       | ✅   |
| `.ds--overflow-menu-options__btn`                                                                      | ✅       | ✅   |
| `.ds--overflow-menu-options__btn *`                                                                    | ✅       | 🚫   |
| `.ds--overflow-menu-options__btn *::before`                                                            | ✅       | 🚫   |
| `.ds--overflow-menu-options__btn *::after`                                                             | ✅       | 🚫   |
| `.ds--overflow-menu-options__btn:hover`                                                                | ✅       | ✅   |
| `.ds--overflow-menu-options__btn:focus`                                                                | ✅       | ✅   |
| `.ds--overflow-menu-options__btn::-moz-focus-inner`                                                    | ✅       | ✅   |
| `.ds--overflow-menu-options__btn svg`                                                                  | ✅       | ✅   |
| `.ds--overflow-menu-options__btn:hover svg`                                                            | ✅       | ✅   |
| `.ds--overflow-menu-options__option-content`                                                           | ✅       | ✅   |
| `.ds--overflow-menu-options__option:hover`                                                             | ✅       | ✅   |
| `.ds--overflow-menu-options__option--danger .ds--overflow-menu-options__btn:hover`                     | ✅       | ✅   |
| `.ds--overflow-menu-options__option--danger .ds--overflow-menu-options__btn:focus`                     | ✅       | ✅   |
| `.ds--overflow-menu-options__option--danger .ds--overflow-menu-options__btn:hover svg`                 | ✅       | ✅   |
| `.ds--overflow-menu-options__option--danger .ds--overflow-menu-options__btn:focus svg`                 | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled:hover`                                                   | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled .ds--overflow-menu-options__btn`                         | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled .ds--overflow-menu-options__btn:hover`                   | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled .ds--overflow-menu-options__btn:active`                  | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled .ds--overflow-menu-options__btn:focus`                   | ✅       | ✅   |
| `.ds--overflow-menu-options__option--disabled .ds--overflow-menu-options__btn svg`                     | ✅       | ✅   |
| `.ds--overflow-menu--flip`                                                                             | ✅       | ✅   |
| `.ds--overflow-menu--flip::before`                                                                     | ✅       | ✅   |
| `.ds--overflow-menu__container`                                                                        | ✅       | 🚫   |
| `.ds--overflow-menu svg`                                                                               | ✅       | ✅   |
| `.ds--overflow-menu html`                                                                              | 🚫       | ✅   |
| `.ds--overflow-menu__trigger html`                                                                     | 🚫       | ✅   |
| `.ds--overflow-menu body`                                                                              | 🚫       | ✅   |
| `.ds--overflow-menu__trigger body`                                                                     | 🚫       | ✅   |
| `.ds--overflow-menu code`                                                                              | 🚫       | ✅   |
| `.ds--overflow-menu__trigger code`                                                                     | 🚫       | ✅   |
| `.ds--overflow-menu strong`                                                                            | 🚫       | ✅   |
| `.ds--overflow-menu__trigger strong`                                                                   | 🚫       | ✅   |
| `.ds--overflow-menu-options html`                                                                      | 🚫       | ✅   |
| `.ds--overflow-menu-options body`                                                                      | 🚫       | ✅   |
| `.ds--overflow-menu-options code`                                                                      | 🚫       | ✅   |
| `.ds--overflow-menu-options strong`                                                                    | 🚫       | ✅   |
| `.ds--overflow-menu-options__option html`                                                              | 🚫       | ✅   |
| `.ds--overflow-menu-options__option body`                                                              | 🚫       | ✅   |
| `.ds--overflow-menu-options__option code`                                                              | 🚫       | ✅   |
| `.ds--overflow-menu-options__option strong`                                                            | 🚫       | ✅   |
