### ISSUE TITLE
TextInput Readonly Variant - Icon placement

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#10588]
Using Chrome

v11 storybook is doing this:

![image](https://user-images.githubusercontent.com/15822070/151870869-02effddb-f699-4e7e-a67c-82a0214df6aa.png)

I expect it to behave like this: v10 storybook

![image](https://user-images.githubusercontent.com/15822070/151871204-684de043-7819-489e-907d-968990423e47.png)

**Comment by aledavila** [comment]
this has been fixed
