### ISSUE TITLE
Grid: v11 audit

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#10594]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

**_Document the process you go through while auditing when checking off the list._** 

The idea here is that anyone could look at this issue and understand the process you went through to audit the component from the comments below.

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [ ] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [ ] White theme
    - [ ] Gray 10 theme
    - [ ] Gray 90 theme
    - [ ] Gray 100 theme
- [ ] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [ ] Firefox
    - [ ] Safari
    - [ ] Chrome
- [ ] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [ ] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [ ] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [ ] Correct design tokens (type and color) are used
- [ ] Component using the correct size prop names
- [ ] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [ ] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [ ] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [ ] Confirm that there are no violations in Accessibility checker
- [ ] Confirm that component works as expected with VoiceOver
- [ ] Confirm that the component looks and works as expected when zoomed 200%
- [ ] Confirm that the component is keyboard accessible. Ensure that everything you do with a mouse can be done with a keyboard and document in the comments how to interact with the component through a keyboard (not applicable to component with no interactive elements like Grid) 

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [ ] Develop

**Comment by joshblack** [comment]
@tay1orjones I believe this should be addressed, going to close this out but feel free to re-open if that's not the case
