### ISSUE TITLE
Update sass dependency version in v11

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10600]
Mentioned in https://github.com/carbon-design-system/carbon/issues/9857#issuecomment-945894019, `@carbon/styles` v11 will support `sass@>=1.33.0`

For this we need to:
- [x] Update the peer dep range for the package
- [x] Remove any conditionals around `math.div` usage inside `packages/styles`
- [x] Add a note to migration guidance specifying this sass dependency version is a requirement and how to update

**Comment by joshblack** [comment]
Should be closed in #11061, files can be removed later on and aren't release-specific
