### ISSUE TITLE
[Bug]: initialSelectedItem in dropdown component does not update when the updating the list

### ISSUE THREAD

**Issue by sparikh1594** [carbon-design-system/carbon#10601]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

10.49.0

### React version

7.35.0

### Description

When using `initialSelectedItem` , if you update the list passed to the dropdown component, the initial value does not get updated

### Steps to reproduce

Create a dropdown component with a list of items
use `initialSelectedItem` and set to an item from the list
Update the list

Notice that the initialSelectedItem does not get updated

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@sparikh1594 For `initialSelectedItem`, the hope with the prop name is that it reveals that what is passed to the component only represents what is selected on the initial render - it's not meant for after-creation updates. For full control you'll need to use the `selectedItem` prop and can subscribe to changes via the `onChange` prop.
