### ISSUE TITLE
[a11y]: Weird typeahead behavior in Dropdown

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#10628]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Operating System

Windows

### Package version

10.51

### React version

7.51

### Automated testing tool and ruleset

keyboard

### Assistive technology

keyboard

### Description

Steps for vanilla:
- https://www.carbondesignsystem.com/components/dropdown/usage/#live-demo
- focus on the example Dropdown (the one with label "Dropdown title")
- type the letter O slowly 3 times - this selects Option 1, Option 2, Option 3, as expected
- now refresh the page
- focus the example Dropdown and quickly type Op 3 times - this unexpectedly selects Option 2, Option 4, Option 2
- I would have expected the same result as above: Option 1, Option 2, Option 3

Steps for react:
- https://react.carbondesignsystem.com/?path=/story/components-dropdown--default
- repeat the same steps as above, except that now if you keep typing Op quickly, you can actually select the disabled item

### CodeSandbox example

see description

### Steps to reproduce

see description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by carmacleod** [comment]
PS: Not a fan of this issue template. Too many required fields that aren't relevant for some issues.

**Comment by tay1orjones** [comment]
@carmacleod Let me know which required fields you felt shouldn't be required, we can probably make them optional instead.

I'm not able to reproduce this on mac in chrome. Totally possible it's isolated to Windows OS. In mac the typeahead behaves as expected - pressing <kbd>o</kbd> every ~.5s-1s or so iterates through the options. I think repeatedly pressing <kbd>o</kbd> faster is effectively configuring typeahead to search based on "ooooooo", which doesn't match any options.

It doesn't appear that the cutoff timeout delineating a new "word" is configurable from our end with downshift unfortunately.

https://user-images.githubusercontent.com/3360588/152884521-fa8876d7-1341-4d1e-ac7b-ffbadfc67418.mov

**Comment by sstrubberg** [comment]
Closing for now due to inactivity. Let me know if we should re-open @carmacleod
