### ISSUE TITLE
[a11y]: Dropdown typeahead needs to handle space key differently

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#10634]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Operating System

Windows

### Package version

10.51

### React version

7.51

### Automated testing tool and ruleset

keyboard

### Assistive technology

keyboard

### Description

Steps for vanilla:
- https://www.carbondesignsystem.com/components/dropdown/usage/#live-demo
- focus the example Dropdown and quickly type Option 4
- this should select Option 4, but the space opens the Dropdown and Option 2 is actually selected (because of #10628)

Steps for react:
- https://react.carbondesignsystem.com/?path=/story/components-dropdown--default
- focus the example Dropdown and quickly type Option 4
- space opens the Dropdown and Option 1 is selected

If the Dropdown is open, then typing Option 4 closes the Dropdown because that's the normal behavior of the space key.

I would expect [space to be added to the search string when using typeahead](https://github.com/openui/open-ui/issues/171#issuecomment-686016533), and not used to open/close the Dropdown.

### CodeSandbox example

see description

### Steps to reproduce

see description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This feature is available in the 7.x version of downshift. From [the docs](https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#toggle-button):

> <kbd>Space</kbd>: If the menu is closed, opens the menu. If the menu is opened and there is an item highlighted, it will select that item. If the user has typed character keys before pressing Space, the space character will concatenate to the search query. This allows search for options such as `Republic of ...`

We're on v5.2.1 of downshift right now, and there is [no mention I can find](https://github.com/downshift-js/downshift/tree/v5.2.1#default-handlers) of this feature or a way to extend how the typeahead/search works. I think in order to fix this we may need to upgrade our downshift dependency version.

**Comment by tay1orjones** [comment]
The PR https://github.com/carbon-design-system/carbon/pull/13744 confirms this - even if we properly gate the <kbd>space</kbd> keypresses from downshift, downshift v5.x still isn't properly concatenating it to the typeahead "search"
