### ISSUE TITLE
Cannot use use a dropdown inside a Modal

### ISSUE THREAD

**Issue by meganwalker-ibm** [carbon-design-system/carbon#1064]
## Detailed description

> Describe in detail the issue you're having.

When you try to place a dropdown component onto a modal component the Z-Indexes at https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_layout.scss#L64 mean that when you open the dropdown the dropdown options are hidden *behind* the modal making it effectively impossible to have a dropdown ontop of a modal.

I can't think of a situation when you'd have a dropdown open in the background with a modal ontop taking focus, so it seems like the dropdown should have a higher z-index than the modal.

> Is this issue related to a specific component?

Modal + Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

The dropdown menu should render ontop of the modal

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components@9.10.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Appconnect

## Steps to reproduce the issue

See description above, or check out my fork of carbon-components-react where I've put a story on the Modal storybook to demonstrate the problem
https://github.com/meganwalker-ibm/carbon-components-react/tree/dropdown-on-modal

## Additional information
<img width="579" alt="screen shot 2018-09-05 at 13 42 21" src="https://user-images.githubusercontent.com/20321922/45093837-92304f00-b111-11e8-882e-6bc5188adc6c.png">
Here you can see that the dropdown menu appears behind the modal the dropdown is on.

**Comment by asudoh** [comment]
@meganwalker-ibm Thank you for reporting! I guess the initial author did the current way considering drop downs in the main content, and making a change there will break existing applications. That said, feel free to change `z-index` in app-land. Also, non-floating kinds of drop downs require `overflow:visible` in container element (seems in `.bx--modal-content` in above case), and I suggest to be sure you add that style.

**Comment by cal-smith** [comment]
Bump.

Given that dropdowns close when focus moves to a different element (i.e. opening a modal) there should be no issues with giving the dropdown a higher z-index than the modal.

**Comment by cal-smith** [comment]
I can make a PR with a corrected `z-index` if we know where in the scale it should be :+1:
