### ISSUE TITLE
[Bug]: Issue related to OverflowMenu and OverflowMenuItem.

### ISSUE THREAD

**Issue by swapnilga24** [carbon-design-system/carbon#10654]
### Package

carbon-components

### Browser

Chrome, Edge

### Package version

10.52.0

### React version

17.0.2

### Description

**Issue related to OverflowMenu and OverflowMenuItem.**
**Description** : (Using version v10.50.0 and v10.52.0)
In the below table I am using OverflowMenu to display two items clicked 1 and clicked 2.
![image](https://user-images.githubusercontent.com/39656416/152825473-3bbafc88-3d4a-4a92-840e-8325e19b601f.png)
When i clicked on (clicked 1) item. I am calling another react component. you can see in the below SS.
now, active modal is "Testing Background OverflowMenu". now, clicked 1 and clicked 2 should be disabled. but the issue is both item (clicked 1 and clicked 2) are active. This items should be disabled. OverflowMenuItems should disappear when Modal gets focus.
![image](https://user-images.githubusercontent.com/39656416/152824969-5f792270-2d50-4c40-9731-6819f0dacd62.png)
**Old Version** :  
For old Version v10.32.0  This items are disabled. you can see the below SS.
![image](https://user-images.githubusercontent.com/39656416/152825261-288024f2-e33a-416c-8a66-0918ddd09362.png)
So, this issue is for latest version v10.50 and v10.52.
**Way to fix this issue :**
In scss you have set same z-index value. please see below SS.
![Screenshot (210)](https://user-images.githubusercontent.com/39656416/152831252-6943e84e-24ff-4bb3-a2eb-d57a4f723348.png)
we need to disabled the z-index value. then we can see OverflowMenuItems are disappear.
![Screenshot (209)](https://user-images.githubusercontent.com/39656416/152831256-68712d90-8bc4-4910-a5e3-8d810cd48b4b.png)
**Note** : Issue is only for latest version for old version it is working fine.

### CodeSandbox example

https://codesandbox.io/embed/distracted-thompson-d4075?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

I had reproduce this issue on codeSandbox. check that for more details.
also, on codesandbox if we downgrade the version then it working fine.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
I think the relevant change causing this is https://github.com/carbon-design-system/carbon/pull/8694

**Comment by tay1orjones** [comment]
The `PermissionRequired` wrapped around the `OverflowMenuItems` appears to be the problem. To function properly, the `OverflowMenu` requires direct children of `OverflowMenuItem` or a component that matches its signature exactly.  This warning is present in the console of your sandbox link:

```
Warning: `<OverflowMenuItem>` detected missing `closeMenu` prop. `closeMenu` is required to let `<OverflowMenu>` close the menu upon actions on `<OverflowMenuItem>`. Please make sure `<OverflowMenuItem>` is a direct child of `<OverflowMenu>. 
```

This should fix the issue, but respond here if not and we can reopen. Thanks!
