### ISSUE TITLE
[Bug]: Inconsistent Checkbox

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#10668]
### Package

@carbon/elements

### Browser

Chrome

### Package version

^10.33.0

### React version

^16.8.6

### Description

According to https://www.carbondesignsystem.com/components/checkbox/usage/ , checkboxes should look like

![good](https://user-images.githubusercontent.com/4472725/153176462-b07b9981-91be-4e31-9fa3-156f0b52d2af.PNG)

On https://www.carbondesignsystem.com/components/checkbox/code , checkbox is not rounded and the icon is not centered

![bad](https://user-images.githubusercontent.com/4472725/153176624-9334feff-c661-4a40-a232-c62f1ab4a4e1.PNG)

On https://www.carbondesignsystem.com/components/checkbox/usage#live-demo , checkbox is not rounded

![not rounded](https://user-images.githubusercontent.com/4472725/153177895-be0c47c6-094c-4fd0-9733-2b2084bf8d62.PNG)

When implementing it, its not rounded

![impl](https://user-images.githubusercontent.com/4472725/153177904-8bfc0d8e-ae35-4461-ae17-10673bcd4d9d.PNG)

The implementation should be the same as on the first screenshot, since the designer expect such implementation.

### CodeSandbox example

https://codesandbox.io/s/weathered-cdn-d5nju?file=/src/index.js

### Steps to reproduce

Read description.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
cc @carbon-design-system/design can you take a look at this and see if either the code or documentation needs to be updated?

**Comment by laurenmrice** [comment]
@tw15egan There is a visual difference because in code the checkbox is drawn and is not using the icon asset, which has straight corners. In design the Sketch kit and images on the website use the checkbox icon asset, which has rounded corners.

I believe this was originally drawn in code because it is not actually possible to use an icon with the native checkbox component. What we could do to align the drawn checkbox in code is to edit it to round the corners of it. Alison may have some insight on how to do this because she originally worked on it.

**Comment by alisonjoseph** [comment]
I believe this component has been refactored since I last worked on it many years ago. 😅 However I don't see any reason why we couldn't add a border radius to match the icon if that is what is expected?

**Comment by fabpico** [comment]
I want to remind that the issue is not only about the corners, but also the alignment of the check-icon. Now on both mentioned examples, the icon is vertically too much down (previously it was only on the first example).

https://carbondesignsystem.com/components/checkbox/code/
https://carbondesignsystem.com/components/checkbox/usage/#live-demo

<img width="113" alt="check" src="https://user-images.githubusercontent.com/4472725/170244940-b15f5b67-5bb7-431b-8ab3-728def20956d.PNG">

Chrome Version 101.0.4951.67 (Official Build) (64-bit)
Windows 10

**Comment by sstrubberg** [comment]
hey @fabpico, thanks for submitting the issue. This has been triaged and we'll be weighing it's priority against competing work-streams. If you're feeling up to it, and would like to submit a PR based on @alisonjoseph's recommendation with the border-radius, we'd be happy to review it.
