### ISSUE TITLE
Disabled FIleUploader has flash of inccorect styling on mouse out of drag and drop zone

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#10663]
![Peek 2022-02-08 18-05](https://user-images.githubusercontent.com/40970507/153096665-4a0e760b-8a5b-4d11-8739-2525abe423c9.gif)

Found on Firefox latest in Ubuntu

**Comment by TannerS** [comment]
Hey @dakahn I wanted to look into this, but I cant see the issue. I am looking at the storybook locally on latest main branch (pulled) on firefox dev edition and chrome on osx but I cannot re-create this

**Comment by guidari** [comment]
If you test this issue with the VO in any browser with [storybook](http://localhost:3000/?path=/story/components-fileuploader--drag-and-drop-upload-container-example-application&args=disabled:!true), you will notice that the drag and drop container is recieving focus, even being disabled.

In the code what is being disabled is the `input` only, but the button should also be disabled to avoid being focused. This might cause confusion for screen readers.

If this `button` is also disabled the flicker with styling will go away and also the VO announcement.

https://github.com/carbon-design-system/carbon/blob/cb2a38f9b5294526d644b0419b46d647ed00e661/packages/react/src/components/FileUploader/FileUploaderDropContainer.tsx#L200-L211
