### ISSUE TITLE
Checkbox appearance looks off when using standard CSS reset

### ISSUE THREAD

**Issue by ollie-o** [carbon-design-system/carbon#1066]
## Detailed description

> Describe in detail the issue you're having.

Checkbox renders incorrectly when the app has a global CSS reset like this.
```css
  *,
  *::before,
  *::after {
    box-sizing: border-box;
  }
```

While you could make the argument that it's not really a bug, my team talked about it and we think:
- `carbon-components` is probably supposed to work no matter what the global CSS is
- A CSS reset like this is very common, so fixing this might improve the experience for other users

> Is this issue related to a specific component?

Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?

We expected the checkbox to render with the checkmark in the center, like this:
![screen shot 2018-09-05 at 6 45 36 pm](https://user-images.githubusercontent.com/5886107/45127014-ef40fa80-b13b-11e8-9738-8a95b839c0c7.png)

But it actually rendered like this:
![screen shot 2018-09-05 at 6 44 26 pm](https://user-images.githubusercontent.com/5886107/45126981-c1f44c80-b13b-11e8-9255-e523aabeaa8c.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

`~9.8.4`, but we noticed the bug even on the latest version (`9.10.0`).

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Compare & Comply. Not pressing - we have solved the problem on our end already.

## Steps to reproduce the issue

1. Render a checkbox normally
2. Add global CSS reset code
```css
  *,
  *::before,
  *::after {
    box-sizing: border-box;
  }
```
3. See that the reset code causes the checkbox to be weirdly sized and positioned

[Here is a CodeSandbox link replicating the bug](https://codesandbox.io/s/k9qqpo2xjv).

**Comment by tw15egan** [comment]
> we have solved the problem on our end already.

@oliverodaa mind contributing back the fix for this?

**Comment by ollie-o** [comment]
@tw15egan sure. PR is here: https://github.com/IBM/carbon-components/pull/1070

**Comment by tw15egan** [comment]
Thank you! We really appreciate you taking the time to contribute the fix back 😄
