### ISSUE TITLE
Data Table, TableHeader, sortDirection

### ISSUE THREAD

**Issue by DusanSmutny** [carbon-design-system/carbon#10676]
Hi, 
When onClick() on header calls server for data (Rest API) and response is already sorted & paged, how can I only set sortDirection in render (without any additional data manipulation on client)? 
Thx

**Comment by joshblack** [comment]
Hi there @DusanSmutny! 👋  This is a great question, I'm curious if you could share more information about your specific problem so we can help out better. Here's a codesandbox template that might make this easier, if that helps: [Link](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)

**Comment by joshblack** [comment]
Just following up, going to close this out since we haven't heard back from you. If you could follow-up with some specifics we'd be more than happy to help out!
