### ISSUE TITLE
ERROR TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by nkdweb** [carbon-design-system/carbon#10677]
## Summary
ERROR TypeError: Cannot read property 'add' of null
## Relevant information

> ERROR TypeError: Cannot read property 'add' of null
>     at FileUploader.onFilesAdded (carbon-components-angular.js:12743)
>     at FileUploader_ng_container_0_Template_input_change_8_listener (carbon-components-angular.js:916)
>     at executeListenerWithErrorHandling (core.js:21915)
>     at wrapListenerIn_markDirtyAndPreventDefault (core.js:21957)
>     at HTMLInputElement.<anonymous> (platform-browser.js:976)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:399)
>     at Object.onInvokeTask (core.js:41762)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:398)
>     at Zone.runTask (zone-evergreen.js:167)
>     at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)

As i got this issue today when i try to add files using ibm-file-uploader. Now i can't able to add any files to the fileuploader, it just open the file dialog window and no further action can be performed.

Please let me know, If anyone faced this issue

**Comment by joshblack** [comment]
Hi there @nkdweb! 👋 

This looks like a question related to Angular, for that project we recommend making an issue over on their repo: https://github.com/ibm/carbon-components-angular

Hope this helps! I'm going to close this out here, feel free to comment if you have any questions.
