### ISSUE TITLE
React Carbon Stacked icons[Question]: 

### ISSUE THREAD

**Issue by CynthiaKamau** [carbon-design-system/carbon#10671]
### Question for Carbon

Hi,

I am implementing two stacked icons that look like this : 
<img width="97" alt="Stacked Icon" src="https://user-images.githubusercontent.com/19533785/153237846-063f8a2d-9610-48da-bb20-d270024dffc2.PNG">
 
I am having a hard time styling the user icon inside, because the icon on the inside presumes the style of the icon on the outside. Is there a recommended way to handle stacked icons or should i add a style to the svg in the icon?

Any tips or links to read will be aprreciated.

My code sandbox [https://codesandbox.io/s/stacked-icon-gzp3i?file=/src/index.js](here)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @CynthiaKamau! 👋  Thanks for taking the time to put this together.

When we were taking a look at your codesandbox, it seemed like the styles / classes were not rendering as expected. Below is a screenshot of what we are seeing:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/3901764/154994317-282b2956-706d-42d0-a39c-acc0601282f9.png">

Could you share more information about how to get the linked codesandbox up-and-running to make the behavior that you're reporting? Thanks!
