### ISSUE TITLE
Popover release readiness

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#10680]
A popover is a piece of UI that _pops over_ or renders on top of other UI on the
page. It's a component "primitive" meaning it can be used to help make more
complex components that utilize this behavior.

## Popover Behaviors

- popovers are invoked/shown by interacting with some other UI element either
  through click, hover, key press, or focus
- popovers can be dismissed either through blur, <kbd>esc</kbd> keypress, or by
  having a different popover be triggered and shown
- popovers are displayed on top of other UI and out of the normal page flow
  typically anchored to a triggering element

## Usage
- `<Popover/>`...
  + can be placed in several directions directions, including: `top`, `bottom`, `left`, `right` (etc) via the `align` prop
  + accepts a custom `className`
  + can be rendered in three stylistic variants: `highContrast`, `light`, and default
  + accepts a `string` or `elementType` to render as a custom top level node
  + can be rendered with or without a caret via the `caret` prop
  + can be rendered with or without drop shadow via the `dropShadow` prop
  + accepts a `<PopoverContent>` sub component 
- `<PopoverContent>`... 
  + accepts elements for rendering via the `children` prop
  + takes a custom class name with the `className` prop

## Migration
Popover was previously only available as _unstable_ in previous versions of Carbon. So no migration guidance is necessary

## Testing 
![image](https://user-images.githubusercontent.com/40970507/153299792-f44f22e2-74aa-4e5f-814f-f967d419993c.png)

## Further Reading

- [Open UI Popup documentation](https://open-ui.org/components/popup.research)

>**Release readiness**
> What is this?
> It means that this thing is ready to release, be publicly available. It's stable.
> 
> - Feature coverage
>   - Does the component do everything we say it does?
>   - Does the component look correct across states?
> - For components that have changed between v10 and v11...
>   - Is there a migration guide?
> - Documentation
>   - Is it clear that a user could learn how to use the component to accomplish the features laid out above?
> - Testing
>   - RTL, is the behavior tested in Jest?
>   - Is the API tested in Jest?
> - Audits
>   - Visual
>     - Responsive
>     - Themes
>     - Layers (??)
> - Strategy
>   - What are we shipping in v11?
>     - Are there any issues remaining with the implementation that need to be addressed?
>   - What are we shipping post-v11?

**Comment by dakahn** [comment]
@joshblack lemme know if this is what we're looking for here 🏄🏾

**Comment by tay1orjones** [comment]
@dakahn @joshblack Are there any actionable items from here to populate into separate issues for this sprint?

**Comment by joshblack** [comment]
@tay1orjones I think we're good to go with this, only thing missing is auto alignment but I don't think that's a stop-ship issue 👍
