### ISSUE TITLE
[Feature Request]: Possibillity to hide any element on desktop, tablet or mobile

### ISSUE THREAD

**Issue by seriouz** [carbon-design-system/carbon#10687]
### Summary

It would be nice to hide certain elements on some devices or show elements on a specific device like mobile.
In [Bootstrap there was the `display` property that enabled such behavior](https://getbootstrap.com/docs/4.0/utilities/display/).
Currently a smiliar behavior found in Carbon only exists on the grid columns where we can set the `lg`, `md`, `sm` property to 0 to hide the column on the specific device.

### Justification

Hiding and showing elements should be covered by the framework with its own breakpoints for the different devices.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jnm2377** [comment]
@seriouz it sounds like you're asking for utility classes. What bootstrap is offering is utility classes that basically apply whatever styles you want without you having to write those styles, which is different than the props that we have for our `Grid` components, where the prop is doing some js logic as well. We actually had a lot of interests in something like this a while back, discussion here: https://github.com/carbon-design-system/carbon/pull/7295 which led to developing a Tailwind Carbon preset: https://github.com/carbon-design-system/tailwind-preset-carbon. 

Alternatively, this behavior can be achieved by using our `breakpoint` [mixins](https://github.com/carbon-design-system/carbon/blob/ff7418e115708635cf4936b6e7f999824af1bc57/packages/layout/scss/_breakpoint.scss#L134-L243) to add styles (hide or show components) for different breakpoints. Something like:

```css

.component {
    display: inline;

    /* applies styles inside mixin on md breakpoint or below, like max-width */
    @include carbon--breakpoint-down('md') {
        display: none; 
    }
}
```

the breakpoint mixins include:
- `carbon--breakpoint-down()`
- ` carbon--breakpoint-up()` || `breakpoint()`
- `carbon--breakpoint-between()` this takes 2 args, to apply styles in between 2 breakpoints i.e. md - lg
- `carbon--largest-breakpoint()`

**Comment by tay1orjones** [comment]
Utility/helper classes were delivered in https://github.com/carbon-design-system/carbon/pull/11786
