### ISSUE TITLE
[Feature Request]: Optimize TableHeader naming

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#10707]
### Summary

I ran in to https://github.com/carbon-design-system/carbon/issues/2531 .
`TableHeader` seems to confuse people, including me. I suggest to rename `TableHeader` in `HeaderCell`, or to be consistent with current subcomponents, `TableHeadCell`/`TableHeaderCell`.

### Justification

To avoid confusion.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by abbeyhrt** [comment]
We can definitely see how this could be confusing but as this is a breaking change for our design system, this is not something we will be pursuing at this time. Feel free to let us know if you would like this re-opened or explored further.
