### ISSUE TITLE
[Bug]: FilterableMultiSelect not collapsing when selecting another FilterableMultiSelect

### ISSUE THREAD

**Issue by riley-goodling** [carbon-design-system/carbon#10712]
### Package

carbon-components-react

### Browser

Firefox

### Package version

v7.5.3

### React version

v17.0.2

### Description

When multiple MultiSelects are on a page and one is opened, it will collapse when you open a different MultiSelect. I expected this behavior to be the same with a FilterableMultiSelect, but it is not. With the FilterableMultiSelects, they will all continue to stay open until clicked away from all of them. I have included two videos, one that shows the MultiSelect collapsing when selecting another, and the other video showing the FilterableMultiSelects staying open even when selecting another. 

https://user-images.githubusercontent.com/99508375/153663184-13a56a84-85ea-4815-b0cc-af5e6b8f6d35.mov

https://user-images.githubusercontent.com/99508375/153663188-09d6cd4a-647a-47e1-8c81-42d7550ab03a.mov

 

### CodeSandbox example

https://codesandbox.io/s/romantic-leavitt-hqist?file=/src/App.jsx

### Steps to reproduce

Create a page with multiple FilterableMultiSelects to see that they do not collapse when selecting another FilterableMultiSelect.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Here's another stripped down sandbox where you can see the difference https://codesandbox.io/s/stoic-panna-jfxfp

**Comment by hrshtpnt** [comment]
Is any fix added for this issue or a workaround? I see that the issue exists when the user clicks on the chevron up icon to open the dropdown.
