### ISSUE TITLE
Replace  usages of old `Tooltip` with new `Toggletip`, `Tooltip`, `Popover`, etc.

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10717]
In relation to the new Popover/Toggletip, we need to find internal usage of the old Tooltip and replace it with the new one. Alternatively we can document the existing usages to be refactored later.

**Comment by jnm2377** [comment]
- Tabs (IconTab)
- Icon button
- CodeSnippet (copy btn feedback tooltip)
- CopyButton
- Pagination (next page buttons)
- PaginationNav
- UI Shell actions btns
- UI shell switcher btn
- stories:
    - FormLabel
    - Modal
    - ProgressIndicator
    - Tooltip?

**Comment by abbeyhrt** [comment]
Just a small update: Tabs(IconTab) is using the new Tooltip. @jnm2377 I'm down to do 

- UI Shell actions btns
- UI shell switcher btn
- stories:
  - FormLabel
  - Modal
  - ProgressIndicator
  - Tooltip?

If you want to take on the top half?

**Comment by dakahn** [comment]
Jumped in and updated the UIShell for us! Tried to see if you had something up already @abbeyhrt and I couldn't see a PR 🏄🏾 🌈
