### ISSUE TITLE
[Bug]: Radio button selected dot misalignment

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#10746]
### Package

carbon-components-react

### Browser

Chrome (Windows)

### Package version

^7.34.0

### React version

^16.8.6

### Description

Windows Chrome: The black dot in the radio button is noticeable not centered in the middle. Also it is randomly too high or to low.
Mac (browser unknown): It looks fine.

Too high
![black point too high](https://user-images.githubusercontent.com/4472725/153841140-aa240124-3718-4570-95f6-a1faff822643.PNG)

To low
![black point too low](https://user-images.githubusercontent.com/4472725/153841149-4b899039-b8a1-4261-b8e4-472682e63140.PNG)

### CodeSandbox example

https://codesandbox.io/s/peaceful-easley-i3gx6?file=/src/index.js

### Steps to reproduce

Go to CodeSandbox url.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ayesha-firdaus** [comment]
Can you assign me this

**Comment by TannerS** [comment]
@ayesha-firdaus  are you still doing this one?

**Comment by ayesha-firdaus** [comment]
yes
