### ISSUE TITLE
Define v11 migration migration path for: $carbon--ease-in, $carbon--ease-out, etc.

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10758]
- Do we want to keep these, or should these go away? Gather alignment on this across the disciplines.
- Make a call, document the outcome

**Comment by joshblack** [comment]
## As-is

| Name | Value |
| :-- | :--- |
| $duration-fast-01 | 70ms |
| $duration-fast-02 | 110ms |
| $duration-moderate-01 | 150ms |
| $duration-moderate-02 | 240ms |
| $duration-slow-01 | 400ms |
| $duration-slow-02 | 700ms |
| $carbon--ease-in | cubic-bezier(0.25, 0, 1, 1) |
| $carbon--ease-out | cubic-bezier(0, 0, 0.25, 1) |
| $carbon--standard-easing | cubic-bezier(0.5, 0, 0.1, 1) |
| $transition--base | 250ms |
| $transition--expansion | 300ms |
| $duration--fast-01 | 70ms |
| $duration--fast-02 | 110ms |
| $duration--moderate-01 | 150ms |
| $duration--moderate-02 | 240ms |
| $duration--slow-01 | 400ms |
| $duration--slow-02 | 720ms |
| $carbon--ease-in | cubic-bezier(0, 0, 0.38, 0.9) |
| $carbon--ease-out | cubic-bezier(0.2, 0, 1, 0.9) |
| $carbon--standard-easing | cubic-bezier(0.2, 0, 0.38, 0.9) |
| $transition--base | $duration--fast-02 |
| $transition--expansion | $duration--moderate-02 |


```scss
$easings: (
  standard: (
    productive: cubic-bezier(0.2, 0, 0.38, 0.9),
    expressive: cubic-bezier(0.4, 0.14, 0.3, 1),
  ),
  entrance: (
    productive: cubic-bezier(0, 0, 0.38, 0.9),
    expressive: cubic-bezier(0, 0, 0.3, 1),
  ),
  exit: (
    productive: cubic-bezier(0.2, 0, 1, 0.9),
    expressive: cubic-bezier(0.4, 0.14, 1, 1),
  ),
);
```

**Comment by joshblack** [comment]
## To-do

- [ ] Make sure website token table is up-to-date
  - [ ] https://www.carbondesignsystem.com/guidelines/motion/overview/#duration-tokens

**Comment by joshblack** [comment]
@jnm2377 just a heads up, was in this part of the codebase anyways and updated the docs in the v11 migration docs 👀
