### ISSUE TITLE
Discussion on widget for showing, clearing multi-select

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon#1076]
Hey y'all. Got some random micro feedback for you.

Two questions/comments re: the indicator on the multi select dropdown on this page... (http://www.carbondesignsystem.com/components/dropdown/code)

<img width="564" alt="screen shot 2018-09-10 at 4 28 29 pm" src="https://user-images.githubusercontent.com/1547834/45325482-947e1900-b516-11e8-8a49-8bbb02c467a4.png">

1) **What do you think about making the pill a separate reusable component?** We're currently hoping to use it in a slightly different context around filtering...

(initial pass on the code, not final)
<img width="247" alt="screen shot 2018-09-10 at 4 27 10 pm" src="https://user-images.githubusercontent.com/1547834/45325514-ac559d00-b516-11e8-81a3-439f3c91fe8c.png">

2) **We're not sure the pill itself reads as an interactive component, and/or whether users will get that clicking it means clearing the filter.** Maybe the hover state can somehow draw attention to the X in the pill, to indicate that clicking performs a 'clear' operation? Just a first idea. Alternatively, maybe only the internal 'X' is the interactive component, and the pill itself is read-only.

**Comment by asudoh** [comment]
Thanks @mlinnem for bringing this up! The 1st one makes sense to me technically, but reading the 2nd one - Wondering if this is more of a design question?

**Comment by mlinnem** [comment]
@asudoh Yeah, #2 is definitely a design question. Is there a better place to bring that up?

**Comment by asudoh** [comment]
@IBM/carbon-designers What do you think? Thanks!

**Comment by designertyler** [comment]
Thanks @mlinnem I agree this design could be a little more _clear_. Here's a quick idea.

The cloud dashboard's filter behaves like this:

When there is one filter is shows the value of the filter "AI"
<img width="164" alt="screen shot 2018-09-11 at 1 51 34 pm" src="https://user-images.githubusercontent.com/19270502/45381061-dddb7080-b5c9-11e8-95b4-bca23c190369.png">


When there are multiple options it Changes to "Categories 2" 
<img width="311" alt="screen shot 2018-09-11 at 1 34 16 pm" src="https://user-images.githubusercontent.com/19270502/45381004-b71d3a00-b5c9-11e8-8407-fb3b001df574.png">

What I like about that is that it's almost saying "Categories = 2" to make it clear what the number represents. But, the X, label, and number aren't really working together.

What are your thoughts on this? It's more obvious what the clear button does, how many filters are applied, and relieves the pill from trying to play two roles.
![filter sketch](https://user-images.githubusercontent.com/19270502/45381793-f5b3f400-b5cb-11e8-802a-14cd35c6ccca.png)


Another thing to consider if you have a lot of filter options is a summary at the top so you don't have to search for which ones are on and can quickly clear individual ones.
<img width="473" alt="screen shot 2018-09-11 at 1 44 36 pm" src="https://user-images.githubusercontent.com/19270502/45381919-50e5e680-b5cc-11e8-9c20-ce6c10d71201.png">

**Comment by aagonzales** [comment]
@mlinnem maybe sync up with Virginia. I think she's done a lot of work around interactive tags for the console dashboard. But I think to your original question it would be ok to make the tag its own thing so it can be re-used.

I wish Tayler was still here she's the one that did a bunch of research into the the mutli-select dropdowns... there's a lot of functionality in a small area.

**Comment by mlinnem** [comment]
Ok y'all. So after exploring this entirely too much, we are liking option E on this chart, which happens to be what you already have :) Only one we think might be slightly better is L, which is just E with a pixel or two more space between the number and the X. But really we're just splitting hairs at this point.

<img width="1006" alt="screen shot 2018-09-14 at 11 36 30 am" src="https://user-images.githubusercontent.com/1547834/45563281-749a6e00-b812-11e8-8d5e-1ba7e0148452.png">

I'll go ahead and close this unless y'all want to chew on it more.
