### ISSUE TITLE
[Feature Request]: Remove `overflow-y: hidden` from `StructuredList` styles

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#10794]
### Summary

`.bx--structured-list` sets `overflow-y: hidden` which hides vertically overflowing content.

This impacts `carbon-components-svelte`, where tooltips are implemented using relative positioning. This causes tooltip menus in the bottom row to be clipped (see https://github.com/carbon-design-system/carbon-components-svelte/issues/1106).

Is there a specific reason for this CSS rule? Can it be safely removed?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hey @metonym! 👋 This is a great point. When looking at the styles, @tay1orjones pointed out that this is one of the older styles in the library and probably is something that could be removed as a result.

**Comment by metonym** [comment]
@joshblack Awesome – thank you!
