### ISSUE TITLE
Date Picker reset

### ISSUE THREAD

**Issue by morengab** [carbon-design-system/carbon#10796]
## Summary
We're incorporating a date picker into our design and would like to provide the ability to "clear" or "reset" whatever a user has selected. Right now, we have a clear button show up below the date picker but this pushes the items down. We're wondering if this is the best solution or if there are other ways with icons or something inline with the date picker to better support this action.

## Relevant information

Example
<img width="308" alt="image" src="https://user-images.githubusercontent.com/565634/89950247-d7f3cd00-dbee-11ea-9e7f-28bd62692407.png">

**Comment by joshblack** [comment]
This came up in our backlog cleaning session. It seems like there could be a clear way of communicating how to "clear" a date input.

cc @aagonzales @thyhmdo to see the best way to get involved to figure out, if relevant.
