### ISSUE TITLE
[Bug]: How do you use the `appendTo` prop on DatePicker?

### ISSUE THREAD

**Issue by PSzy90** [carbon-design-system/carbon#10800]
### Question for Carbon

What is the proper way to use the appendTo property on the DatePicker component? I'm trying to append to a container element but the calendar is still rendered in the body. My code does not provide any console errors and otherwise seems to function as expected.

    <div  id="container">
        <DatePicker
          // ... other props ...
          appendTo={document.getElementById('container') as HTMLElement}
        >
          <DatePickerInput
             // ... other props ...
          />
        </DatePicker>
    </div>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @PSzy90! 👋 Thanks for taking the time to make this issue.

When looking into this, it does seem like `appendTo` is not working as expected. Here is a codesandbox that demonstrates this: https://codesandbox.io/s/kind-wave-26wepo?file=/src/index.js

On our end, we'll take a look at this in a future sprint to make sure we can clarify usage of this prop
