### ISSUE TITLE
[Question]: Should the Layer component set the background?

### ISSUE THREAD

**Issue by ishitatsuyuki** [carbon-design-system/carbon#10806]
### Question for Carbon

I appreciate the work on v11 and the layer component looks great for a more structured representation of the widget tree.

I didn't manage to find any concrete usage examples of `<Layer>`, though. Pardon me if I missed something, but I wonder what is the intended way to set background when using layers?

Right now, the Layer and other stories set the background through a custom class:

https://github.com/carbon-design-system/carbon/blob/3e83dd81379ea6af3ebb7696b81c5b1f28c5ae58/packages/react/src/components/Layer/next/Layer-story.scss#L10-L14

But from the naming of "layer", I kinda expected it to set background on its own. Writing a helper class just to set the background of layer feels a bit weird.

What does the Carbon team think of putting background as a part of layer?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
@ishitatsuyuki great question! And thanks so much for taking the time to make this issue, we really appreciate it 🙏 

If I remember correctly, the anticipated usage for Layer has been that it is rendered inside of a component which sets `background: $layer`. We could definitely look into combining these two ideas into one, either in the `Layer` component directly or even a `LayerBackground` component if that would make sense 👀 

In this case, the component would set `background` to `$layer` and then any children would automatically be on the next layer level.

**Comment by btepe** [comment]
@joshblack Just came across this issue, because we are trying to make more use of the "magic" Carbon already offers. It would be really helpful if the `Layer` component already set `background-color: $layer` like you suggested. It seems like a simple addition that simplifies the usage a lot.
