### ISSUE TITLE
[Feature Request]: Allow TooltipDefinition to stay visible when hovering over Tooltip Text

### ISSUE THREAD

**Issue by ask-42** [carbon-design-system/carbon#10851]
### Summary

This was previously the case many versions ago - we upgraded to a newer release of carbon recently and this functionality changed, however I'm not sure specifically when. I'm unsure if it was an intentional design decision (and thus, bringing back the old behavior would be a feature request), or if its a bug introduced by an update.

### Justification

Interactive tooltips that appear on `:hover` instead of only appearing on click. I understand this might not be desirable in every case, so perhaps it can be an optional prop.

- Imagine you have an error icon, or error code, that when you hover, shows more detailed information about the error, and you want the user to be able to select/copy/paste the contents of the tooltip. This was previously possible; however, now when the user hovers over the tooltip text, it disappears. They can click the trigger to force it to stay open, but this requires an extra click from the user, as opposed to being able to just hover over the content. The "Definition" from this tooltip has value to the user that they should be able to interact with. The user also may not know that clicking the trigger forces it to stay open; they likely just want to hover over the content and select it - this is a poor user experience.

- Imagine you want to have an interactive tooltip, but do not want the user to have to click an extra time to open/close it, allowing for an easier user experience (hover only to show the tooltip, click interactive element inside the tooltip).

### Desired UX and success metrics

Success: User hovers over tooltip trigger, and tooltip is shown. User can now hover over tooltip text and allow it to stay visible, without having to click the trigger to force it to stay open

Failure: The user hovers over the tooltip text, and thus away from the trigger, and the tooltip text disappears, not allowing the user to interact with it.

### Required functionality

The tooltip text stays visible when hovered over

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hey @ask-42! Totally agreed, tooltips should stay persistent if you hover over the tooltip itself and you should be able to copy its content.

I'm not 100% sure if this will be backported into v10, but this is 100% the approach that we're taking in v11 for this component (and tooltips in general).
