### ISSUE TITLE
Update website to include new content from the elements packages

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10875]
eg https://www.carbondesignsystem.com/guidelines/color/code 

Related https://github.com/carbon-design-system/carbon/issues/10566

- new content from the readme
- update the docs
- pass from design to ensure headings etc are correct

**Checklist**

- [x] https://www.carbondesignsystem.com/guidelines/color/code
- [x] https://www.carbondesignsystem.com/guidelines/motion/code
- [x] https://www.carbondesignsystem.com/guidelines/spacing/code
- [x] https://www.carbondesignsystem.com/guidelines/themes/code
- [x] https://www.carbondesignsystem.com/guidelines/typography/code
- [ ] https://www.carbondesignsystem.com/guidelines/2x-grid/implementation

**Comment by joshblack** [comment]
**Process**

- Update the inline notification to read `@carbon/react` instead of `carbon-components`
- Remove the first line of the usage section
- Replace the sass usage section with the content from the sass docs of the package
  - Note: don't include the API section if it is too long
