### ISSUE TITLE
Create `v11` branch

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10879]
To support the efforts of the release, a new public `v11` branch needs to be created. It will hold all future development leading up to the v11 release.

- [x] Create the branch
  - Will/How does this impact our release process? Document the answer
- [x] Make it the default branch for PRs?
  - Do we want this branch to become the default PR branch at this point? 
  - It could be beneficial to have as little as possible reconciliation to do between `main` and `v11`. 
  - What would the workflow be for bugfixes to v10 during this time?
- [x] Set up `carbon-components` and `carbon-components-react` to correctly re-export from `@carbon/styles` and `@carbon/react`, respectively.

**Comment by joshblack** [comment]
Going to close this out as I believe it's been addressed, feel free to re-open if that's not the case @tay1orjones
