### ISSUE TITLE
[Bug]: Inconsistency between Select and Dropdown component

### ISSUE THREAD

**Issue by hnjoshi** [carbon-design-system/carbon#10883]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.52.0

### Description

In Dropdown component we can see the tip is displayed on mouse hover. Whereas in Select component we don't see the tip when mouse hover.

### Screenshots

Dropdown component
![Dropdown](https://user-images.githubusercontent.com/8787607/156064679-a835efc3-9847-4386-8fa6-3ce27806b95f.png)

vs

Select component
![image](https://user-images.githubusercontent.com/8787607/156064882-db2a4957-214b-46b4-82a3-eb4a9b986279.png)

### Steps to reproduce

1. Go to storybook for dropdown component and select any option and then hover over the dropdown you will see the tip pop up
https://react.carbondesignsystem.com/?path=/story/components-dropdown--default

2. Go to storybook for select component and select any option and then hover over the select component, you will see that no tip is shown
https://react.carbondesignsystem.com/?path=/story/components-select--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Thanks for taking the time to open this @hnjoshi! We really appreciate it 🙏 

Note to implementors: this browser tooltip (or really any tooltip) may be needed when the value of the control is longer than the width so that the user can see the full option text.

**Comment by torresga** [comment]
Hi there, I would like to take this issue.

**Comment by tw15egan** [comment]
We'd welcome a PR @torresga!
