### ISSUE TITLE
UI Shell: Header menus

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1089]
# Header menu
**Sketch file:** https://ibm.box.com/s/ckhiqk41nacbqgvkml6w3qikblixjlo3

Notes:
- Optional menu that can be used instead of a link.
- Menu label is NOT a destination just a label
- Menu is fixed width
- Menu should align to the left side of the element
- Max 6 items inside of a menu, shouldn't ever scroll

*** Items in menu should say `L1 Item` not `L2 menu item` ***
![image](https://media.github.ibm.com/user/380/files/f247f670-a493-11e8-9866-a20f54a38892)

## In header context
![image](https://media.github.ibm.com/user/380/files/7202e6d2-a493-11e8-965a-c4c09a489674)

## Item states
![image](https://media.github.ibm.com/user/380/files/11486b40-a494-11e8-8683-ac38dba97de3)

**Comment by shinytoyrobots** [comment]
@aagonzales, can this go to dev now?

**Comment by joshblack** [comment]
@shinytoyrobots the dev task is in: https://github.com/IBM/carbon-components/issues/1095 so we can close, I believe
