### ISSUE TITLE
[Question]: Tokens to use to override UI-shell header background color. 

### ISSUE THREAD

**Issue by matt-jordan-1** [carbon-design-system/carbon#10891]
### Question for Carbon

We are attempting to update the color of the ui-shell header background color `.bx--header` with our own internal color styling; however, we keep getting the default color (#161616) despite our styling properly taking effect in the other components. Currently, we're overriding the token `$ui-05` with the color we want. From the documentation/source code, it seems like `$ui-o5` is the token we should be using.  

Can you confirm this is the token we should be using or if another token is more appropriate?

Also, FYI, the documentation (https://www.carbondesignsystem.com/guidelines/themes/overview/#customizing-a-theme) says that `$ui-05` is actually equal to #171717 instead of #161616.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi @MJordanMilliman! 👋 Thanks so much for taking the time to make this issue. If I remember correctly, in v10 the UI Shell has a custom set of component tokens that are used for theming. However, in v11 the UI Shell will use our tokens to offer theming.

In the interim, you may be able to override the component-level tokens for UI Shell but unfortunately the overall tokens and changing them may not map cleaning while theming this component.

Let me know if you have any other questions! Would love to help out.

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/blob/1069a16ffb50905034b9ef3640fd4d098a37437f/packages/components/src/components/ui-shell/_header.scss#L31

**Comment by MJordanMilliman** [comment]
I will test this today and then close the ticket.

**Comment by jnm2377** [comment]
Hi @MJordanMilliman were you able to customize the UI Shell tokens with the solution provided above?

**Comment by MJordanMilliman** [comment]
@jnm2377 Thanks for following up! I got sidetracked with another project the past few days but had a chance to test it out tonight  with no luck, unfortunately. 

I made a code sandbox to illustrate: https://codesandbox.io/s/header-base-forked-38gvg8?file=/src/style.scss 

Can you take a look to see where this is going awry?

**Comment by jnm2377** [comment]
Hey @MJordanMilliman unfortunately, since our styles are added thru a CDN in codesandbox, none of our sass (tokens, mixins, functions) will work on that platform (just pure css). So the token and theme styles don't work on codesandbox bc of that. Is this also not working in your source code?

**Comment by MJordanMilliman** [comment]
Hey @jnm2377 , unfortunately, yeah the token override doesn't seem to flow through upon compilation in that setup. I'd be happy to show someone live if need be but that is the setup we currently have. For the time being, I overrode the specific properties for the class directly via css but that's definitely not a long-term solution for us.

**Comment by tay1orjones** [comment]
@MJordanMilliman Yeah, I agree it's not ideal. As Josh said, we have improvements coming in v11 to make this easier that required a breaking change. For now, overriding the class directly is probably the best way to approach this.

**Comment by joshblack** [comment]
Going to close this out as this has not been active for several weeks. Feel free to comment and we can re-open the issue!
