### ISSUE TITLE
Update v11 Notification live demo & storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10894]
Live Demo:

- [ ] Add the new variant, ActionableNotification
- [ ] Reflect changes in props and the new variant

Storybook

- [ ] Inline story could use some cleanup (margin?)
- [ ] MDX docs need a pass - follow the template
  - [ ] Provide good getting started information - level set on how to use these things

**Comment by fabpico** [comment]
> Live Demo needs updated to include the change in props and the variant

I just wanted to try out https://www.carbondesignsystem.com/components/notification/code but when changing the kind, nothing happens.
However, changing the kind on your Storybook works https://react.carbondesignsystem.com/?path=/docs/components-notifications--toast .
