### ISSUE TITLE
[a11y]: Invalid Role "Listbox" and invalid label "downshift-n-label"

### ISSUE THREAD

**Issue by kush-singh-chb** [carbon-design-system/carbon#10909]
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

7.54.1

### React version

17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

Can see the following accessibility issues with custom dropdown.
<img width="794" alt="Screenshot 2022-03-04 at 9 37 04 a m" src="https://user-images.githubusercontent.com/12840419/156738475-82fd1774-ac23-4951-baa4-efee518104a1.png">

<img width="796" alt="Screenshot 2022-03-04 at 9 38 14 a m" src="https://user-images.githubusercontent.com/12840419/156738600-feca455d-536b-4e79-a625-561e7e31be84.png">

### CodeSandbox example

https://codesandbox.io/embed/immutable-haze-3bt1vo?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

Just scan using IBM Equal Access Accessibility Checker.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kush-singh-chb** [comment]
![image (6)](https://user-images.githubusercontent.com/12840419/156739360-2a6d22ed-b382-4b23-a941-1ca35601ca7b.png)

![image (7)](https://user-images.githubusercontent.com/12840419/156739373-47a7478b-ccfb-412d-b539-0ca5cbb779d2.png)

**Comment by tw15egan** [comment]
Hi! You need to add a label to the Dropdown via the `titleText` prop. You can then hide that label (but keep it available to screenreaders) via the `hideLabel` prop. Here is an example: https://codesandbox.io/s/nice-heisenberg-bghlqp?file=/src/index.js

Hope that helps!
