### ISSUE TITLE
Experimental Component: Accordion

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1090]
A designer can discover the experimental component on the System site and understand why and how to use it.

**Design**
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

A developer can discover and install the experimental component by following accessible documentation.

**Development**
- [ ] Write a description for this issue

**Website**
- [ ] When work is complete, development adds a design reviewer to verify work through a staging link
- [ ] create code guidance
- [ ] create usage guidance
- [ ] create style guidance
- [ ] add component to Component Status page
- [ ] publish updated page

**Comment by jeanservaas** [comment]
[Experiemental_Components_WIP.zip](https://github.com/IBM/carbon-components/files/2389825/Experiemental_Components_WIP.zip)

This is the same file I sent in Link. As per Security and the Carbon site, I've only included the Fixed Accordion (rules only) component in this file, all you will see here is the white theme only. Also, this is our component with the chevron on the right. If this is a problem, I can reorient it.

@chrsfshr Here's the first batch, it includes:
— Primary Link
— Accordion
— Breadcrumb
— Text Input
