### ISSUE TITLE
[Feature Request]: Warning icon in `TextArea`

### ISSUE THREAD

**Issue by Addeuz** [carbon-design-system/carbon#10910]
### Summary

I would really like the `TextArea` component to have a warning option similar to the `warn` and `warnText` prop on `TextInput`.

### Justification

We use `TextArea`s quite a lot in our system at work but feel like the `invalid` prop sometimes is too "aggressive". And sometimes the text is not invalid but should give a warning.

### Desired UX and success metrics

Same ux and metrics for the `warn` and `warnText` props on `TextInput` basically.

### Required functionality

See desired UX and success metrics.

### Specific timeline issues / requests

ASAP as we plan to release a beta for a reference group late march.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

https://github.com/carbon-design-system/carbon/issues/10910#tasklist-block-9bd6a09d-06f9-496e-a86e-3834196eab50

**Comment by joshblack** [comment]
Hi there @Addeuz! 👋 Thanks for taking the time to put this proposal together 🙏 

On our end, I've added this issue to our proposal backlog. This backlog gets triaged every other week and is where we talk about feature requests and decide the next best action on them.

Let me know if you have any additional questions about this process! I'd love to help out.

**Comment by jnm2377** [comment]
Hi @Addeuz thanks for bringing this up. We will look into adding this for `TextArea`!

**Comment by aagonzales** [comment]
## Final spec
[Figma file](https://www.figma.com/file/LJUJE0T30u5et33qnGLKI6/Fluid-input_Text-area_v11?node-id=0%3A1&t=CPEXE9gCtTW5OPbn-1)

<img width="704" alt="image" src="https://user-images.githubusercontent.com/11670886/221995747-ec5c3746-c229-431d-bd70-5a022f62eee2.png">
