### ISSUE TITLE
[Bug]: Tab Skeleton is broken

### ISSUE THREAD

**Issue by alexandertrefz** [carbon-design-system/carbon#10926]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

0.15.0

### React version

v17.0.2

## Expected

Tab Skeleton looks roughly like the design Documentation indicates.

## Actual

It looks broken like you can see here: https://carbon-react-next.netlify.app/?path=/story/components-tabs--skeleton

### CodeSandbox example

https://carbon-react-next.netlify.app/?path=/story/components-tabs--skeleton

### Steps to reproduce

Go to the docs here: https://carbon-react-next.netlify.app/?path=/story/components-tabs--skeleton and look at the broken Tab Skeleton.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
cc @tay1orjones @abbeyhrt for Tabs
