### ISSUE TITLE
[Bug]: Windows Environment Setup

### ISSUE THREAD

**Issue by NashJames** [carbon-design-system/carbon#10949]
1) `yarn build` error on Windows:
```
carbon-components: ./tools/copy-vendor-styles.sh: 2: ./tools/copy-vendor-styles.sh:
carbon-components: : not found
carbon-components: ./tools/copy-vendor-styles.sh: 11: ./tools/copy-vendor-styles.sh:
carbon-components: : not found
carbon-components: ./tools/copy-vendor-styles.sh: 12: set: Illegal option -
lerna ERR! yarn run build exited 2 in 'carbon-components'
```

2) GitHub Desktop error when commiting:
```
.husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)
```

Environment:
- Windows 10
- Node v16.14.0
- WSL (Ubuntu 18.04 LTS)

**Comment by NashJames** [comment]
Error 2 has proven to be difficult. I've had little success fixing it. I tried all of the suggestions listed [here](https://github.com/typicode/husky/issues/912) and a couple others. It does not currently seem possible to commit via git or GitHub Desktop on Windows with this issue.

**Comment by dakahn** [comment]
Hey @NashJames thanks for reporting! Couple of questions I had:
- How did you install Node? Is it via nvm, fnm or just from their packages? 
- Are you using Github Desktop installed in Windows or in WSL? If in Windows what's the interop like between WSL and Windows apps other than VS Code? The reason I ask is because it seems like that error isn't aware of your Node install -- which I assume is in your subsystem where you'd have access to `npx`

**Comment by NashJames** [comment]
No problem.

I am using `nvm`. And I haven't tested other apps interacting with WSL, I had no reason for it before Carbon.

`npx` works fine in WSL.

I had seen those docs beforehand but it was not an available option in the shell dropdown which I thought was odd. I saw [this](https://github.com/desktop/desktop/issues/7891) and noticed they have a beta version of the app, which I tried this morning and does have WSL as an available option. The error did change, but it is still not any significant help.

```
/bin/bash: D:/Program Files/nodejs/npx: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

I also found a few other issues with suggestions, but some didn't work at all, and others only created different errors. [Here](https://github.com/desktop/desktop/issues/12562) had a few good ones. The `npx` -> `npx.cmd` gave this:
```
/c/Users/james/AppData/Roaming/npm/npx: line 5: cygpath: command not found
/c/Users/james/AppData/Roaming/npm/npx: line 11: exec: node: not found
husky - pre-commit hook exited with code 127 (error)
```

There seems to be a lot of issues around on this topic, it may be that Windows is not an option until Husky or GitHub Desktop propose a fix.

**Comment by tay1orjones** [comment]
@NashJames For committing via `git`, does it work if you avoid the hooks via `--no-verify`? 

```
git commit -m "message" --no-verify
```

This should bypass the hooks altogether. CI status checks will still be ran against any PR, so it's not a huge risk other than it being cumbersome from a developer experience point of view.

**Comment by NashJames** [comment]
That did it. Cheers @tay1orjones.

Tested it with the add-contributor stuff on my open PR.

I suppose I should add some text to the windows doc about commiting? Seems there's a few open issues on github desktop about adding a --no-verify option, but it hasn't been picked up in over a year so could be a while.
