### ISSUE TITLE
compose event handlers in Combobox prop `onStateChange`

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#10964]
The Downshift prop `onStateChange` is used to observe changes in the component's internal state. It's currently unavailable to our users because its used internally by Combobox for the filter functionality.

We compose the users event handler with our own and allow users to observer internal state changes for debugging if possible 🏄🏾

**Comment by jnm2377** [comment]
For maintainers, more context in this slack thread: https://ibm-studios.slack.com/archives/C046Y0YUD/p1646822355901109
