### ISSUE TITLE
[Bug]: Module not found: Can't resolve 'window-or-global' in .. carbon-components-react\es\internal

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#10961]
### Package

carbon-components-react

### Package version

^7.34.0

### React version

^16.8.6

### Description

This happened after I updated an own dependency. Maybe was a patch applied in one of your packages in the dependency tree? Maybe one of that removed `window-or-global` from the dependencies?

When I want to start my react app, it fails to compile:

```
Failed to compile.

./node_modules/carbon-components-react/es/internal/FloatingMenu.js
Module not found: Can't resolve 'window-or-global' in 'C:\Users\...\node_modules\carbon-components-react\e
s\internal'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
```
I also tried to remove node_modules and yarn.lock, and reinstalled all packages.

Due to the chokidar errors I tried to clean the yarn cache and rebooted the pc. Problem persists.

**EDIT**
In yarn.lock I see several minor version updates were applied to carbon packages. Also I see that the `window-or-global@^1.0.1:` block was completely removed without a replacement of its version.

### CodeSandbox example

-

### Steps to reproduce

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for the heads up @fabpico! I just ran into it myself, sorry about this. I've got a PR up and will cut a new patch version as soon as it's in.

**Comment by sbohner14335** [comment]
We are getting the same issue failing a build on our cf toolchain, thank you.

**Comment by tay1orjones** [comment]
I've moved the `latest` dist-tag on npm back to the previous release.

- 10.54.0 for `carbon-components`
- 7.54.2 for `carbon-components-react`

**Comment by tay1orjones** [comment]
Going to reopen this until we get the patch cut shortly.

**Comment by tay1orjones** [comment]
Resolution in [v10.55.1](https://github.com/carbon-design-system/carbon/releases/tag/v10.55.1) has been published.
