### ISSUE TITLE
Create standalone panel components for UI Shell

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1096]
This issue is for implementing the panels found in:

![image](https://media.github.ibm.com/user/841/files/89b50cae-b741-11e8-9ac3-aa5a4da0750b)
![image](https://user-images.githubusercontent.com/825457/45569161-49207f00-b824-11e8-8788-aa99ae83b9c8.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy

**Comment by shinytoyrobots** [comment]
@aagonzales, can this go to dev now?

**Comment by shinytoyrobots** [comment]
@aagonzales, can this go to dev now?

This is not needed to be built for Q3 milestone, but we do require website guidance on panels for then.  @jeoffw - do you think that might benefit from a different issue?

**Comment by joshblack** [comment]
This should be good to go for dev next sprint 👍

**Comment by joshblack** [comment]
I think we might want to try and de-prioritize this till we start working on individual panel types. Adding this in now without a clear path forward for why we would use them might result in code that doesn't hit the actual requirements here.
