### ISSUE TITLE
Add initial Platform Navigation component

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1097]
This issue is for introducing the platform nav component as seen in:

![image](https://user-images.githubusercontent.com/825457/45569224-7e2cd180-b824-11e8-9d8e-16339ab3ef5b.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy (internal)

**Comment by shinytoyrobots** [comment]
Is there a PR related to this, given it is dev and in review?

**Comment by joshblack** [comment]
Sorry, the PR references the old issue. Leaving here for reference and closing: https://github.com/IBM/carbon-components/pull/1082
