### ISSUE TITLE
Update v11 ContentSwitcher usage content

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10979]
- [ ] Website
    - [ ] Usage Tab
    - [ ] Style Tab
    - [ ] Code Tab
    - [ ] Accessibility page
  - [ ] Storybook
    - [ ] Default story
    - [ ] Playground story
    - [ ] Use-case stories
    - [ ] Docs page

**Comment by joshblack** [comment]
No changes are being made to `ContentSwitcher` so this should be no longer relevant 👍
