### ISSUE TITLE
Provide automated migration(s) for v11 style changes

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10984]
This issue is to track the exploration and delivery of providing automated code migrations for styles (`.scss`) in relation to the v11 change set.

At a high level:
- Explore what's possible
  - Build on the initial exploration https://github.com/carbon-design-system/carbon/pull/10658
    - First tackle automatically rewriting `import`s
    - Then work with sponsor users (Cloud PAL?) on a token migraton codemod. 

In the cases of multiple migration paths for a single token, it might make sense to surface those paths through the CLI: 

```
> $token usage has been split into multiple options in v11.
> Which of these do you want to replace $token with?
> ⦾ $new-token1
> ⦾ $new-token2
> ⦿ $new-token3
```

Related reading:
- https://www.codeshiftcommunity.com/docs/css-codemods/

**Comment by sstrubberg** [comment]
Closing in favor of https://github.com/carbon-design-system/stylelint-plugin-carbon-tokens
