### ISSUE TITLE
[Release Partner] Luca

### ISSUE THREAD

**Issue by Lc0rE** [carbon-design-system/carbon#10983]
**What is your team's name?**

Luca. I'm by myself :)

**Why would you like to join the Release Partner Program?**

I'm using Carbon for more than two years now, in Vanilla, React and Angular. I'm thrilled to explore the new v11 release, and I'm willing to give my feedback and report possible bugs. I'm using it heavily for my personal and professional projects.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

Reach me by @Lc0rE on Github or Discord (I'm on the Carbon discord server already).

**Comment by jnm2377** [comment]
Hi there Luca @Lc0rE 👋

Thanks for your interest in release partners. Unfortunately, this group is no longer accepting additional participants. You are still completely free to provide feedback through our GitHub discussions and issues. We would love to hear your experience.

Let me know if you need help getting started with that, thanks again for your time and interest here! We really appreciate it 🙏
