### ISSUE TITLE
Update v11 Theming usage content

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10980]
- [ ] Website?
    - [ ] Are there changes necessary here for `@carbon/themes`? Interface with any Layer documentation in https://github.com/carbon-design-system/carbon/issues/10978?
  - [x] Storybook
    - [x] Default story
    - [x] Playground story
    - [x] Use-case stories
    - [x] Docs page

**Comment by joshblack** [comment]
Closed by https://github.com/carbon-design-system/carbon/pull/11053
