### ISSUE TITLE
[Feature Request]: Truncation support for SideNav

### ISSUE THREAD

**Issue by CassidyJensen** [carbon-design-system/carbon#10996]
### Summary

SideNav should be updated to either have a hover state for long titles or allow multiple lines for long titles. This requires a design decision and development to support it.

### Justification

Although most titles are kept short, during the process of translation to other languages titles can become too long the SideNav component. The current behavior truncates the text, but does not allow a way to read the full title. 

### Desired UX and success metrics

If the text is too long for the SideNav title, the user should have a way to read the full title. 

### Available extra resources

I have created a css override in my code to allow for text-wrapping for multiple lines. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jnm2377** [comment]
Hi, we will work on adding a `title` attributed on truncated SideNav item in the mean time. If there are further design explorations you think would be a good idea, please share some of your research and designs so our team can look into it. Thank you. :)

**Comment by sstrubberg** [comment]
Per @tw15egan's suggesting during Backlog Cleaning. Add the title prop to SideNavMenu to afford the title to be shown on hover. Great for Hactoberfest or a Good First Issue 👋 !

**Comment by kaustubhpDev** [comment]
Hey, i would like to work on this issue.
Is anyone working on this ?

**Comment by tw15egan** [comment]
@kaustubhpDev we would gladly welcome a PR to fix this

**Comment by ariellalgilmore** [comment]
This looks like a duplicate with [6116](https://github.com/carbon-design-system/carbon/issues/6116) and looks like Andrew's PR has already been merged. 

cc: @tw15egan @sstrubberg
