### ISSUE TITLE
Adds shift click functionality to data table checkbox

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#10995]
Ref #6942 PR that didn't get finished, got de-prioritized bc of v11

View PR (above) for thread/info

implementation ideas: https://github.com/carbon-design-system/carbon/pull/6942#issuecomment-734202748

> @davidmenendez unfortunately no updates on our end for this 😞 . Looking back, I think the work stalled around figuring out the correct behavior and then was not picked up again. 
As of right now, this is not being addressed. The earliest we're going to begin delivering new work into stable will be Q2 2022 after our v11 release which would be the soonest we could revisit this. Sorry that I couldn't offer better news about this, I can't imagine how frustrating trying to get functionality like this landed has been.

_Originally posted by @joshblack in https://github.com/carbon-design-system/carbon/issues/6942#issuecomment-1021566427_

**Comment by davidmenendez** [comment]
thanks for opening this up. if i can offer any assistance with this please let me know.

**Comment by sstrubberg** [comment]
Pinged @davidmenendez on Slack. Looking to re-sync on this and possibly get it re-prioritized.

**Comment by sstrubberg** [comment]
Dupe https://github.com/carbon-design-system/carbon/issues/4084
