### ISSUE TITLE
Add support for mixed content in Side-nav

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1099]
This task is for adding support for different types of content in Side-nav as seen in:

![image](https://user-images.githubusercontent.com/825457/45570536-bb935e00-b828-11e8-88fb-4f8b036fab58.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy

**Comment by shinytoyrobots** [comment]
Is this likely to be updated in this sprint, or would we be better putting into Backlog in preparation for next sprint planning on Monday?

**Comment by joshblack** [comment]
@shinytoyrobots was planning on tackling it today but I can defer till next week as well

**Comment by shinytoyrobots** [comment]
Do we consider this to be necessary within the Q3 milestone?

**Comment by joshblack** [comment]
I think this could be considered a part of the core functionality of this component, but it can definitely be deferred.

**Comment by joshblack** [comment]
Going to go ahead and move it back to the backlog for next sprint 👍
