### ISSUE TITLE
Add support for title bar and sub-menu to Side-nav

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1100]
This task is to allow support for a standalone title bar and a title bar with a sub-menu to Side-nav as seen in:

![image](https://user-images.githubusercontent.com/825457/45570600-e8e00c00-b828-11e8-9c32-c3d8a81d02ae.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy (internal)

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/45775998-1b1daf00-bc17-11e8-95a0-a0d9ca5d1f2a.png)

Latest spec we're working from

**Comment by joshblack** [comment]
@aagonzales for the sub-menu variant, how should we think about the spacing? Seems like the image and the section title are aligned, but then the select kind of bleeds into the space a little bit.

**Comment by designertyler** [comment]
@joshblack it looks like the intent might be to align the text in the dropdown with the text in the title and links. That's something Duo emphasizes. 

> Whenever possible, left align copy with other copy, even when it’s in a container element. This create a strong vertical alignment with the text adding in legibility, organization and clarity for a user.

@aagonzales was that the intent there? Here's a screenshot from the example [linked here](http://carbon-dev-environment-nonlacteous-lich.mybluemix.net/component/ui-shell--side-nav-with-title-bar-and-sub-menu)
<img width="315" alt="screen shot 2018-09-20 at 8 20 20 am" src="https://user-images.githubusercontent.com/19270502/45821385-b57d0180-bcae-11e8-85c7-26cd5f23ac3e.png">

**Comment by aagonzales** [comment]
@designertyler If its a select which is browser native I'm not sure if we have that kind of alignment control. But yes if possible the text should vertically align.
