### ISSUE TITLE
Create fixed variant of Side-nav

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1101]
This task is to implemented the fixed variant of Side-nav seen in:

![image](https://user-images.githubusercontent.com/825457/45570663-175de700-b829-11e8-87e4-446ecfad8636.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy (internal)

**Comment by dakahn** [comment]
Working on this.
