### ISSUE TITLE
How to create password TextInput component at run time

### ISSUE THREAD

**Issue by AbhishekShrivastava** [carbon-design-system/carbon#11031]
**Description:** 
I am trying to create password input fields uisng html elements but using TextInput.create() creates a regular input field not a password input field with show/hide password toggle button. Can you please helpt me how to create password TextInput component at run time..

**Code:**
```
import { TextInput } from 'carbon-components';
const passwords: HTMLCollectionOf<Element> = document.getElementsByClassName('--password-input',);
for (let i: number = 0; i < passwords.length; i++) {
	TextInput.create(passwords.item(i));
}
```

**Screenshot:**
<img width="391" alt="image" src="https://user-images.githubusercontent.com/4821466/155144654-3e704ad7-a9c6-4f82-b432-17e5a03f4850.png">

**Comment by tay1orjones** [comment]
Hey @AbhishekShrivastava 👋 unfortunately the vanilla components lag behind the feature set offered in the react implementation and documented on the website.

In this case, the TextInput has likely not yet been updated to include the PasswordInput styling and features. We'll gladly accept a PR for this if you're interested in contributing.

**Comment by joshblack** [comment]
Going to close this out as this has not been active for several weeks. Feel free to comment and we can re-open the issue!
