### ISSUE TITLE
[Bug]: Modals are too wide when browser is stretched on large displays

### ISSUE THREAD

**Issue by bradelectro** [carbon-design-system/carbon#11043]
### Package

carbon-components

### Browser

Chrome

### Package version

v11

### React version

v17

### Description

**Expected**
A designer creates a large modal in Sketch (large (960px width modal on 1312px wide artboard):
![download](https://user-images.githubusercontent.com/222230/159716883-99b91f89-3a67-49b7-a9d1-6de0aea6d330.png)

**Result**
When rendered on wide browser on a large screen, the "proper ratio" is questionable:
![box-image](https://user-images.githubusercontent.com/222230/159719793-cce9cf1d-ca9c-410b-8a39-930b0aaf6c2f.png)

### CodeSandbox example

NA

### Steps to reproduce

Open a modal in a stretched out browser on a large display.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@bradelectro could you elaborate on what you'd like to see changed? This is how the modals are designed to behave with the size of `lg`. 

I can see how the visuals are not ideal in the screenshot, does configuring a different size modal not work for this use-case?

**Comment by tay1orjones** [comment]
I'm going to close this out as it's been over a couple weeks without more info. Please reach out if you think we should reopen!
