### ISSUE TITLE
[Question]: ListBox Copmonent icons-react/es size too large

### ISSUE THREAD

**Issue by mango906** [carbon-design-system/carbon#11058]
### Question for Carbon

<img width="2229" alt="image" src="https://user-images.githubusercontent.com/38802280/159892569-ffe16605-ab12-4f20-a91c-9fd4d1734978.png">

When I Use ListBox with carbon-components-react component, There are Too large amount of size of react-icons/es

I've reported this issue before and I got an answer like
> To address this issue, you will need to only import from the entrypoint as that will contain the ESM exports needed to support tree-shaking.

https://github.com/carbon-design-system/carbon/issues/9111

so, I import like this

```typescript
import ListBox from 'carbon-components-react/lib/components/ListBox/ListBox';
import ListBoxField from 'carbon-components-react/lib/components/ListBox/ListBoxField';
import ListBoxMenu from 'carbon-components-react/lib/components/ListBox/ListBoxMenu';
import ListBoxMenuIcon from 'carbon-components-react/lib/components/ListBox/ListBoxMenuIcon';
import ListBoxMenuItem from 'carbon-components-react/lib/components/ListBox/ListBoxMenuItem';
```

but, my problem not solved. 

Can you tell me which file occupies such a large size?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey @mango906, sorry for the confusion - `lib` is the commonjs export location. `/es` is the location of the ESM exports.


```js
import ListBox from 'carbon-components-react/es/components/ListBox/ListBox';
import ListBoxField from 'carbon-components-react/es/components/ListBox/ListBoxField';
import ListBoxMenu from 'carbon-components-react/es/components/ListBox/ListBoxMenu';
import ListBoxMenuIcon from 'carbon-components-react/es/components/ListBox/ListBoxMenuIcon';
import ListBoxMenuItem from 'carbon-components-react/es/components/ListBox/ListBoxMenuItem';
```

**Comment by mango906** [comment]
@tay1orjones 
Thank you for your reply! Thanks to you, our project bundle has decreased a lot.
I have an additional question. Are you interested in using the ListBox that is being exported by default? Like this
```typescript
import { ListBox } from 'carbon-components-react'
```
