### ISSUE TITLE
Overflow menu icon should rotate when embedded inside a breadcrumb

### ISSUE THREAD

**Issue by markewallace** [carbon-design-system/carbon#1105]
## Detailed description
When I add an overflow menu inside a breadcrumb I expect the overflow menu icon to rotate 90 degrees (as it does in a table).

![screen shot 2018-09-17 at 10 57 09](https://user-images.githubusercontent.com/3009737/45616811-75c4d880-ba68-11e8-86ec-8fcf49e3c9a1.png)

> Is this issue related to a specific component? Overflow Menu

> What did you expect to happen? What happened instead? What would you like to see changed? Icon should rotate by 90 degrees

> What browser are you working in? Chrome

> What version of the Carbon Design System are you using? Can reproduce using latest code

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Assess

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
@IBM/carbon-designers Do the use case and the proposed solution make sense to you...? Thanks!

**Comment by claycrenshaw** [comment]
@markewallace Can you please provide a little more context? Is the image you posted the as-is or your desired to-be? Thanks!

**Comment by chrisconnors-ibm** [comment]
Thanks for this submission. The as-is behavior is expected and desired - truncated breadcrumb items are collapsed into an _ellipsis_ rather than the overflow menu control.

**Comment by aagonzales** [comment]
Jumping in, just to clarify the original intent was to have the ellipse icon oriented horizontally and not vertically as per the [usage guidelines](http://www.carbondesignsystem.com/components/breadcrumb/usage) on the website (referenced below).   


<img width="659" alt="image" src="https://user-images.githubusercontent.com/11670886/45702656-54e4ac00-bb6a-11e8-9704-ee85c1d2ff99.png">

**Comment by chrisconnors-ibm** [comment]
It's not the 'ellipsis' glyph though, it's an actual ellipsis character (or should be)

**Comment by chrisconnors-ibm** [comment]
the only thing this should share with Overflow Menu is *styling of the Dropdown*
