### ISSUE TITLE
Re-enable storybook percy integration

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11051]
In addition to the manually configured e2e tests that provide percy snapshots, we can enable the storybook integration to automatically snapshot stories. This will immediately provide a much higher level of coverage in regards to visual regressions.

- [ ] Add integration for v11 in `main`
- [ ] Create new percy project for v10 based off `v10` branch
  - [ ] Add the storybook integration for the v10 branch/project
- [ ] Explore how we can configure knobs/controls to snapshot variants
- [x] #11252

**Comment by tay1orjones** [comment]
This could either augment or replace the existing plan to add percy visual snapshots to all components https://github.com/carbon-design-system/carbon/issues/8911

**Comment by joshblack** [comment]
I believe this was closed by the work completed in #11252! Instead of enabling the storybook percy integration, we are explicitly snapshotting stories through Playwright
