### ISSUE TITLE
[Feature Request]: OverflowMenu disable option

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon#11057]
### Summary

It would be good to be able to disable the overflow menu so it is not clickable and appears to not be clickable.

### Justification

See: https://github.com/carbon-design-system/carbon-components-svelte/issues/1141

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Thanks for the suggestion @pjebs! Could you share a bit of your use case for needing a disabled OverflowMenu?

The component spreads `...other` onto the `button`, so `<OverflowMenu disabled="disabled" />` will functionally disable the component.

The lacking piece here is that there aren't styles to accompany the disabled state, so it looks the same but doesn't function.

@carbon-design-system/design do we have a spec for OverflowMenu in a disabled state? This would be a small change to styling to enable this.

**Comment by aagonzales** [comment]
Yeah we could easily add this. I'm curious though what the use-case is for disabling the whole menu itself versus disabling the options inside the menu. @pjebs

**Comment by pjebs** [comment]
If you go to PETERSIR.com, you will see a play button on the right hand side of the Notting Hill script. It use to be implemented with an overflow menu but I changed it due to this limitation.

I want to disable the playbutton entirely if the browser does not support text-to-speech functionality.

**Comment by pjebs** [comment]
You will notice that on a smaller screen, if the text for the UIShell (in this case "bookstore") is too long, it squeezes away the toolbar buttons instead of truncating the text.
