### ISSUE TITLE
[Feature Request]: Touch screen support

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon#11068]
### Summary

It would be good if standard touch screen events were supported such as long-press.

### Justification

My app https://petersir.com is designed for desktop and mobile use. For mobile use, I needed to program different events because desktop based events didn't make sense.
For example, for ClickableTile, i couldn't use dblclick. I had to program my own long-press.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@pjebs To ground this a bit, could you expand on the use cases you ran into where click events weren't sufficient? Were there specific components that needed this more-so than others?

**Comment by pjebs** [comment]
In my web-app, I have ClickableTile which provide information. When you click on it, it does a specific action.
Another operation is to edit the information in the tiles.
On mobile, the standard "way" is to long-press. That is not viable for desktop, so I made it double click.

**Comment by tay1orjones** [comment]
@pjebs Thanks for the additional info!

> On mobile, the standard "way" is to long-press.

For these cases we'd recommend providing an explicit edit icon or interaction that would be discoverable by non-sighted users. To provide touch events we would likely need to also provide a visual indication or signal that those events are available. This is something outside the scope of the system right now and we don't have plans to add.
