### ISSUE TITLE
Hidden menu items in banner should not take focus

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#1107]
Please see [Bluemix #6571](https://github.ibm.com/Bluemix/core-dev/issues/6571) for background.

Steps (I am using Chrome on Windows, but this probably happens in all browsers on all platforms):
1. Go to any IBM Cloud page that has a banner. For example, [this dashboard page](https://console.bluemix.net/dashboard/apps/). 

2. **Important:** Refresh the page (`F5` or `ctrl+r` on Windows, `cmd+r` on Mac).

3. Starting with focus in the URL address bar (ctrl+L on Windows, cmd+L on Mac), type the tab key through the following elements: Skip to Content, Menu, IBM Cloud, Catalog, Docs, Support.

4. Now type the tab key several more times. Where is the focus? It is going through the invisible menu items in the Support menu.

5. After typing 6 "invisible" tabs, you will see focus finally go to the Manage menu. It takes 5 more "invisible" tabs to finally get to the Search field.

Expected: Typing tab always gives focus to visible elements.

The fix is to give `tabindex="-1"` to all hidden menu item anchors, even right after the page is refreshed, as in the following screen snapshot:

![image](https://media.github.ibm.com/user/3876/files/4ce48ca2-b780-11e8-8785-b4c18b3c99f4)

**Comment by alisonjoseph** [comment]
Hi, what component is this issue referring to? I don't believe this is anything that Carbon controls but maybe I am mistaken?

**Comment by flannanl** [comment]
It's https://github.com/IBM/carbon-components/blob/master/src/components/dropdown/dropdown.js. We need to fix in both carbon v8 and v9.

**Comment by carmacleod** [comment]
Thank-you! :)
