### ISSUE TITLE
[Bug]: @carbon/icons-react : icon import error

### ISSUE THREAD

**Issue by JWLK** [carbon-design-system/carbon#11079]
### Package

@carbon/icons-react

### Browser

Chrome

### Package version

10.49.0 & 10.48.0

### React version

17.0.2

### Description

There is a problem that icons that do not require size specification (ex. status shap icon) are not imported properly. 

Am I using it wrong?

`import { CircleFillGlyph } from '@carbon/icons-react'
`

<img width="560" alt="Screen Shot 2022-03-26 at 11 45 40 PM" src="https://user-images.githubusercontent.com/3753282/160244838-5f5e7aaf-16e3-453c-bf78-c5a0182a9562.png">

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox?file=/src/index.js

### Steps to reproduce

There is no error in the code above.

However, there is a problem that the import does not work properly in my current project.

This is my package.json dependencies
<img width="362" alt="Screen Shot 2022-03-26 at 11 59 32 PM" src="https://user-images.githubusercontent.com/3753282/160245198-ead6d843-f352-4141-a1d4-5fdc6ac821c6.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @JWLK! 👋  Thanks so much for taking the time to make this issue.

I was trying to re-create the issue over in: https://codesandbox.io/s/inspiring-ellis-ok5p0d?file=/src/App.js but I couldn't find any issues that came up.

Could you share more information to help reproduce the problem?

**Comment by joshblack** [comment]
@JWLK ah okay, thanks so much for the link! It may be that this icon is unavailable in the types for the package that come from DefinitelyTyped. Unfortunately, the TypeScript types for this package are community-maintained and are not something that we support at the moment.

**Comment by JWLK** [comment]
Are there any plans for package support for TypeScript?
Currently, it is confirmed that V11 does not support TypeScript.
Will V11 support TypeScript in the future?

**Comment by joshblack** [comment]
Great questions, the latest for TypeScript will come up in this discussion: https://github.com/carbon-design-system/carbon/discussions/10752

At the moment, we definitely are relying on community contributions over in DefinitelyTyped. I believe that there is interest in maintaining TypeScript types in the future but there is no clear roadmap or plan for that at the moment.

Hope this helps!
