### ISSUE TITLE
Fix `Tile` storybook docs page

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#11097]
The following are not showing previews in the doc section:

- [x] Breadcrumb
- [x] DataTable
- [x] Loading
- [x] OrderedList
- [x] Pagination
- [x] Slider(missing props)
- [x] StructuredList (missing props)
- [x] Tile
- [x] Toggle (missing props)
- [x] Tooltip Icon
- [x] Unordered List
- [x] Heading

**Comment by tay1orjones** [comment]
I just looked through all these and the only one not working currently is Tile.

![Screen Shot 2022-04-06 at 11 51 54 AM](https://user-images.githubusercontent.com/3360588/162026889-702d2595-0de8-483a-803a-2767d2b11925.png)
