### ISSUE TITLE
Pressing Escape key in a Modal closes side nav as well

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#1109]
Steps:
- Go to the [Modal example page](http://www.carbondesignsystem.com/components/modal/code)
- Open any modal
- Close it by typing the Escape key
- The Modal closes (good), but the left side nav also closes (not good)

The Escape key event handler needs to have `event.stopPropagation();`.
(Not sure if it also needs `event.preventDefault();`, but it can't hurt to have that as well).

**Comment by asudoh** [comment]
@carmacleod Thank you for reporting! Will see how we can fix the problem.

**Comment by tw15egan** [comment]
Fixed in #1114
