### ISSUE TITLE
[Feature Request]: Add option to supress ref error for component using downshift

### ISSUE THREAD

**Issue by gcattan** [carbon-design-system/carbon#11107]
### Summary

We have the following downshift error in the console:

![image](https://user-images.githubusercontent.com/6229031/160785811-57cfe5f7-bfb2-425c-acfc-a68f7cd9bc67.png)

This issue seems well documented in the downshift repo:

https://github.com/downshift-js/downshift/issues/604
https://github.com/downshift-js/downshift/issues/1272

I would like to know if it is possible to add a `supressRefError` option in the component based on downshift:

![image](https://user-images.githubusercontent.com/6229031/160786104-fd50dd5b-c1ff-4fbe-84b2-3e1d06657a37.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Can you give a link to reproduce this? Possibly in a [codesandbox](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx)? Thanks!

**Comment by tay1orjones** [comment]
@gcattan Thanks for providing more info. I know how hard it can be to get a working repro up and going. 

Our testing setup uses `react-test-renderer` as well and we've not hit this issue before that I'm aware of. Unless we've got a really solid reason as to why this is happening, I don't want to blindly set `suppressRefError: true` across all usages of `getMenuProps`, it leaves a big hole for other potential issues. From the [downshift docs](https://github.com/downshift-js/downshift#getmenuprops):

> In some cases, you might want to completely bypass the `refKey` check. Then you can provide the object `{suppressRefError : true}` as the second argument to `getMenuProps`. **Please use it with extreme care and only if you are absolutely sure that the ref is correctly forwarded otherwise Downshift will unexpectedly fail.**

**Comment by gcattan** [comment]
If we log the current reference on the `componentDidMount`, the error is now reproducible:

![image](https://user-images.githubusercontent.com/6229031/176128086-319ee8b1-3c90-4184-b3f5-9a1bc6aabc95.png)

My understanding is that refs takes a variable amount of time to be set when testing, even when mounted by the react-dom.
This does not happen in production code.

Do you think we can expose `suppressRefError` at the carbon components' level?

**Comment by tay1orjones** [comment]
> Do you think we can expose `suppressRefError` at the carbon components' level?

Yeah, providing this as an option via `downshiftProps` or as a new prop on the component makes sense. It's unlikely the core team will take this on anytime soon, but PRs are always welcome! 🙏

**Comment by tay1orjones** [comment]
This can now be done via `downshiftProps` as it is now spread last: https://github.com/carbon-design-system/carbon/pull/17089

**Comment by gcattan** [comment]
Thanks @tay1orjones! @fbarroso24 FYI
