### ISSUE TITLE
UI Shell style updates

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#1111]
I made some style change updates based off of what security and .com were doing with their shell to try and get better alignment on the details. Most of it has to do with styling of states, ie `:active`/selected

**Sketch file:** https://ibm.box.com/s/5t33bkuvfk0c3dj61nyyb9vqv0rk25gp

## Changes

- [x] Remove full bar highlight on category expanded. Only highlight on the selected item now.
- [x] All Selected link text weight: now semi-bold/600
![image](https://user-images.githubusercontent.com/825457/45643494-d4964c00-ba80-11e8-8bcb-03f83352e972.png)
- [x] All Selected link text color: now #ffffff 
- [x] L1 / Left navigation menu: no longer has background color on selected. Just bar and semi-bolded text
![image](https://user-images.githubusercontent.com/825457/45643522-e24bd180-ba80-11e8-9831-54128d841b1f.png)
- [x] L1 / Left navigation menu variation _without_ icons
![image](https://user-images.githubusercontent.com/825457/45643541-f1328400-ba80-11e8-9569-65a94595382b.png)
- [ ] ~Side-nav title bar now has a circle background container for icon.~ #1100
![image](https://user-images.githubusercontent.com/825457/45643557-f98abf00-ba80-11e8-8d00-2ce5c56aa7c0.png)
- [x] Side-nav panel now has a 1px (gray-80) border at the top
![image](https://user-images.githubusercontent.com/825457/45643573-014a6380-ba81-11e8-9f70-ce9566d01e83.png)
- [x] L0/header links now start 24px from the edge of the platform/product name. No longer a fixed width distance. 
![image](https://user-images.githubusercontent.com/825457/45643593-0c9d8f00-ba81-11e8-8e21-d0e9dc3131f1.png)
- [x] "IBM" in header should be regular weight 400 and not bold. The product/platform name (ie Cloud) should remain semi-bold/600
![image](https://user-images.githubusercontent.com/825457/45643609-158e6080-ba81-11e8-8471-4184558b18e3.png)

cc: @joshblack, @claycrenshaw, @designertyler

**Comment by joshblack** [comment]
cc @aagonzales

**Comment by shinytoyrobots** [comment]
comment from @claycrenshaw:

> Looking good! I'm thinking we could make this even simpler / cleaner by changing "Category Label" to just "Category" and both "Nested Link" and "Item Link" to just "Link." Since we explicitly say that Categories are not clickable, we don't really need that kind of specificity in the diagrams. And the "nested" nature of a "nested link" is already evident because it always appears under a Category. This could also avoid any confusion about potential differences in behavior between an "item link" and a "nested link" -- which in reality do the exact same thing.

**Comment by aagonzales** [comment]
@claycrenshaw yeah I can change the text to say just "link" but I think from a Sketch symbol name perspective I still need to call the one "nested" just so the user knows which symbol to pick. 

And in our components if something is label we say "Component-name label" like for `text-input`. I was just following that method but can remove it if its easier. 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/11670886/45691780-260e0c00-bb51-11e8-8f65-e9a45aff30b1.png">

**Comment by claycrenshaw** [comment]
Awesome, thanks Anna!

**Comment by joshblack** [comment]
Going to bring:

>  Side-nav title bar now has a circle background container for icon.

Under #1100 👍
