### ISSUE TITLE
[Bug]: carbon-components.min.css fails to load in Safari, causes broken UI.

### ISSUE THREAD

**Issue by anuravar** [carbon-design-system/carbon#11129]
### Package

carbon-components

### Browser

Safari
Chrome
Firefox

### Package version

10.50.0

### Description

Facing issue in accessing the carbon-components.min.css from the URL: https://unpkg.com/carbon-components@11.0.0/css/carbon-components.min.css, due to which our Angular app is failing to load properly and have broken UI.
Our carbon component version is 10.50.0 however in the URL its pointing to carbon-components@11.0.0.

### Screenshots

<img width="1206" alt="Screenshot 2022-04-01 at 7 42 40 PM" src="https://user-images.githubusercontent.com/34158763/161290915-691453f0-8393-406a-86b6-1be291777cc7.png">

### Steps to reproduce

Visit https://unpkg.com/carbon-components@11.0.0/css/carbon-components.min.css from any browser.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by mjabbink** [comment]
@sstrubberg  @jeffchew  I believe this issue requires some urgency. I’ve been pinged by several people. Can someone look into this? Much thanks.

**Comment by mjabbink** [comment]
![image](https://user-images.githubusercontent.com/32881239/161294667-ea482111-b722-443a-ae56-d2333ed16a4d.png)

Broken page here:
https://w3.ibm.com/developer/appservices/publish/catalog

**Comment by jeffchew** [comment]
Hi @mjabbink @anuravar ,

We probably will not be able to look at this until early next week the earliest. In the meantime, the team can point to v10 until this is resolved:

https://unpkg.com/carbon-components@10.56.0/css/carbon-components.min.css

And in general, it is recommended to not use a tag version of a CDN artifact for production use. It is better to use versions then bump up after doing regression testing on a lower test environment before upgrading. 

This artifact in question also is considered as the "kitchen sink" of Carbon Components, which is relatively large and not recommended for performance reasons. It is better to choose specific components then compile into the application for better performance. 

Carbon vanilla components are not available as individual components though via CDN. However, the Web Component versions are available if considering to use those instead:

https://www.carbondesignsystem.com/developing/frameworks/web-components#using-cdn

**Comment by rubinthomas** [comment]
It seems odd that v11 was released but the documentation on this page:
https://www.carbondesignsystem.com/developing/frameworks/vanilla 
for vanilla CDN still shows v10 documentation

`Carbon vanilla components are not available as individual components though via CDN. However, the Web Component versions are available if considering to use those instead:`

which is ironic no where does it mention that v11 is not supported as vanilla or that CDN support is not present considering the page was updated on 
```
Styles version 
React Components version ^1.0.0
Last updated 31 March 2022
```

**Comment by anuravar** [comment]
We fixed our part of the issue by pointing it to v10

**Comment by tay1orjones** [comment]
@rubinthomas Sorry for the confusion on the website docs. We'll update them shortly.
