### ISSUE TITLE
 Accordion component is not working after upgrade from Carbon 10.50 to 10.51

### ISSUE THREAD

**Issue by luizas** [carbon-design-system/carbon#11132]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.51.0

### React version

v16.13.1

### Description

We have a query in relation to Carbon 10.51. We upgraded to Carbon 10.51 and we are observing an issue with the Accordion component. The issue is that it will not expand or collapse. We have our own development environment here where we build on top of Carbon, although we haven’t customised the Accordion component. Our environment, currently support Node v14 and Webpack v4. We were just looking at the release notes for 10.51 and have observed that Node v16 support was introduced. We are wondering if this is could be the source of the issue we are experiencing, that we should now should support Node V16 and this would resolve the issue for us?

### CodeSandbox example

can't reproduce

### Steps to reproduce

We think the issue is with our version of node and webpack builds our bundle and latest Carbon. Accordion component stoped working immediately after we upgrade Carbon to 10.51. This issue is blocking us. Are the changes made in PR https://github.com/carbon-design-system/carbon/pull/10346 can affect us? @joshblack ?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and we can re-open!
