### ISSUE TITLE
[Bug]: tooltipicon visually incorrect

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#11147]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

v11

### Description

- The TooltipIcon stories in react do not visually look correct in the examples shown. They should visually look like one of our button variant stylings. 

- _Also a question for dev:_ Is the Filter icon button supposed to show a different button style than the info icon button? In our usage docs we show the filter example as a primary icon button and we show the info example as a ghost icon button. We can also do that here in this example as well if that makes sense.

----

### Info example:
![info icon](https://user-images.githubusercontent.com/43969356/161779947-71a343e4-1932-4d7b-9a86-aaf82b47cc40.png)

----

### Filter example:
![filter icon](https://user-images.githubusercontent.com/43969356/161779962-8f30168c-6f19-43c1-a047-3b7aa29cab49.png)

### Screenshots

- The Default and Playground stories show incorrect visuals for TooltipIcon.

<img width="662" alt="Screen Shot 2022-04-04 at 2 36 18 PM" src="https://user-images.githubusercontent.com/43969356/161609474-7b3cc2c1-bfba-4786-bde8-139c350f7175.png">

<img width="667" alt="Screen Shot 2022-04-04 at 2 35 06 PM" src="https://user-images.githubusercontent.com/43969356/161609442-8f338039-ec4a-4dd3-b252-1ef7788094b9.png">

### Steps to reproduce

- Go to https://react.carbondesignsystem.com/?path=/story/components-tooltipicon--default
- Look at the Default and Playground stories and notice that the visuals do not follow any of our button variant styles.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by TannerS** [comment]
I am glad theres an issue for this. I seen this and thought it was weird it was changed to this lol I guess it was a bug haha

**Comment by abbeyhrt** [comment]
`TooltipIcon` has been removed from the Carbon Design Library due to it being inaccessible, it's been replaced with a new component `IconButton`. Here's some more information about that in our [v11 doc](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#tooltipicon). It looks like we forgot to remove it from storybook,  we made a PR to fix it! 🙂  #11226
