### ISSUE TITLE
Structured list: alignments

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#11149]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

v11

### Description

- The structured list component should only offer the `flush` alignment for the `simple` variant. The states for the selectable variant with flush alignment start to get tricky visually. We need to update structured list to only support the flush alignment for the simple variant.

---

### Structured list
This is an outline of what the modifiers should be per variant:
- **Simple variant**
  - Hang alignment
    - Default size
    - Condensed size
  - Flush alignment
    - Default size
    - Condensed size
- **Selectable variant**
   - Hang alignment
      - Default size
      - Condensed size

### Screenshots

 In the newest React storybook, I do not see the props anymore.

### Steps to reproduce

Currently I do not see the props in React for the different alignments, so those should be added in. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sstrubberg** [comment]
- [ ] Remove the flush from Selectable and make sure it doesn't do anything if the consumer turns it on.
- [ ] Update storybook so you don't see it.
