### ISSUE TITLE
[Bug]: Icons import has grown massively in v11

### ISSUE THREAD

**Issue by spacemolly** [carbon-design-system/carbon#11146]
### Package

@carbon/react

### Package version

v1.0.1

### React version

v17.0.2

### Description

After updating to v11 of Carbon the icons import has ballooned in size. Going from about 50KB in V10 to 1.3MB in V11 with no changes to the number of icons used. It seems likely that this is related to issues with three shaking. 

Think this is a big enough change that it could be called a meaningful regression. As it stands now it's a big enough increase that it'd mean we can't use the new icons package.

V11
<img width="991" alt="v11" src="https://user-images.githubusercontent.com/82213431/161725964-3ef458db-3267-4e50-a15f-d442b06c56e6.png">

V10
<img width="193" alt="v10" src="https://user-images.githubusercontent.com/82213431/161725972-03bfc725-5aa3-436e-8275-ee1e00a4e57e.png">

### CodeSandbox example

Not relevant

### Steps to reproduce

import { Close } from '@carbon/react/icons'

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
@spacemolly thanks for taking the time to write this up, can definitely confirm the issue and can reproduce it. I'll be looking into this today and will get out a patch release as soon as possible with a fix

**Comment by spacemolly** [comment]
Thanks for your quick reply, appreciate your work on this!
