### ISSUE TITLE
[Google Analytics]: Migrate DPO properties

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#11140]
All DPO websites require the following:

- The required [common.js](https://github.com/carbon-design-system/design-language-website/blob/master/gatsby-ssr.js)
- Move common.js to [the footer](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/src/gatsby-theme-carbon/components/Footer/index.js#L59-L68)
- Configure Google Analytics [#google-analytics-360](https://ibm-studios.slack.com/archives/CLYU5UY8P) or https://w3.ibm.com/w3publisher/google-analytics.
- Ensure proper legal links exist in their respective footer a-Terms of use, b-Privacy, c-Accessibility are all required in the footer of an IBM page.  (Cookie preferences link gets added via the common.js.)

https://pages.github.ibm.com/digital-behavior/docs/tms-instrumentation.html

### List of effected websites
- [x] #11460
- [x] https://www.ibm.com/design
- [x] https://www.ibm.com/design/language
- [x] https://www.ibm.com/design/research
- [x] https://www.ibm.com/design/ai
- [x] https://www.ibm.com/design/racial-equity-in-design

**Comment by jeffchew** [comment]
Thank you for creating this @sstrubberg !

The `Cookie Preferences` link functionality is auto-injected by `ibm-common.js`, which looks for an empty element with the stable selector:

`<li data-autoid="dds--privacy-cp">` (I think any element type is fine, it looks for the specific data attribute on the page to inject into)

Here is what we have done for the Carbon for IBM.com website:

Footer: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/src/gatsby-theme-carbon/components/Footer/index.js

Adding ibm-common.js: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/gatsby-ssr.js

**Comment by joshblack** [comment]
Super random, but was wondering after our Google Fonts situation if we need to do anything in particular for Google Analytics and GDPR compliance?

**Comment by ljcarot** [comment]
Correct @sstrubberg @joshblack GA is via an enterprise license agreement.
