### ISSUE TITLE
[Bug]: Carbon/type readme has dead url 

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#11155]
### Package

@carbon/type

### Package version

N/A

### React version

N/A

### Description

The link under this url `https://github.com/carbon-design-system/carbon/tree/main/packages/type#type-styles` for this sentence 'You can find a full reference of the type styles that are available on the Carbon Design System website).' to carbon is broken. the site `https://www.carbondesignsystem.com/guidelines/typography/productive` doesn't exist 

### CodeSandbox example

N/A

### Steps to reproduce

The link under this url `https://github.com/carbon-design-system/carbon/tree/main/packages/type#type-styles` for this sentence 'You can find a full reference of the type styles that are available on the Carbon Design System website).' to carbon is broken. the site `https://www.carbondesignsystem.com/guidelines/typography/productive` doesn't exist 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aagonzales** [comment]
Good spot, below is the correct link and I've opened a PR to fix the readme.
https://carbondesignsystem.com/guidelines/typography/type-sets
