### ISSUE TITLE
[Bug]: Possible missing tokens

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#11157]
### Package

@carbon/react

### Package version

v11

### React version

16

### Description

I may be missing something, or very new to sass and carbon 11, but I been grabbing tokens of the `@carbon/styles` as such 

```
@use '@carbon/styles';
...
.someClass {
  //  background-color: $interactive-01; <----carbon v10 with import
   background-color: styles.$button-primary; <-----carbon 11 using use
}
```

but for some reason, I cannot find the replaced tokens for 

```
interactive-01 
interactive-02 
interactive-03 
interactive-04 
```
<img width="739" alt="image" src="https://user-images.githubusercontent.com/8866319/161900435-403d5ab6-5f78-455c-8619-25f206eab9e5.png">

using `@use '@carbon/styles';` or `@use '@carbon/colors;`

I been able to find other colors/styles tokens but not these ones. 

### CodeSandbox example

N/A

### Steps to reproduce

See description 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aagonzales** [comment]
@TannerS the button color tokens are no longer part of the core set but are now considered "component tokens" and are included with the button code. (I'm just a designer but a @carbon-design-system/developers could probably clarify more).

**Comment by TannerS** [comment]
Ok that probably make sense, if so you can close this :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
@aagonzales  one question real fast, if these were moved to the component and not the core colors, then maybe there should be some explanation here in the docs

![image](https://user-images.githubusercontent.com/8866319/162084284-deb1daae-69f7-477b-a41d-3e9d1b0af512.png)


Because the above here `https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#design-tokens` says for updated tokens 

```
Updated: From v10 to V11 the number suffix has been replaced with an adjective that reflects it's usage. This is just a name change, the role remains the same between v10 and v11.
```

so my assumption was, `$interactive-0*` was updated there names to whats in that chart in the screen shot, however, in reality, what happened was that token was completely removed so there is no 1-to1 updates token for `$interactive-01/2/3/4` anymore? or am I wrong?

**Comment by jnm2377** [comment]
@TannerS there are 1:1 tokens name changes for all the `interactive-0*` tokens. I don't think I'm quite understanding correctly the issue you're bringing up. What you see in the chart in the screen shot is the correct updated token names. Are you having an issue being able to use these?

**Comment by TannerS** [comment]
Hey @jnm2377 , for me, I been able to find and use every replacement except the `interactive-0*` ones, I think mostly the -01, -02. I forgot if -03 and -04 was problematic. 

Like, the way i am importing the tokens so far has worked for everything except those so Im wondering if its a bug, are they imported through another source or something.

I was using `@use '@carbon/styles'` for the tokens and I dont remmeber if the /colors import had same issue, but using that import every token was found except for the oens I tried, `button-primary`, `button-secondary`

**Comment by jnm2377** [comment]
@TannerS does something like this work for you?

```scss
@use '@carbon/react/scss/components/button/tokens';

.my-selector {
  background: tokens.$button-primary;
}
```

**Comment by TannerS** [comment]
hey @jnm2377 thanks that appears to work, but I have some comments.

What works 

1) Webpack builds using this
2) Styles work the way they should

issues

1) Unlike the other `use` imports for tokens/styles/ etc, my IDEs cant resolve this path so it comes up as invalid and is a bit misleading unless i wait for the compiling and find the UI element and see if the color reflects
2) The docs mention the change between the the `interactice-0*` tokens to  the button-primary and button-secondary, but theese docs are listed under the theme import, meaning, if we have to use `'@carbon/react/scss/components/button/tokens';` for these updated tokens, i think the docs should be updated (unless I missed something)

:)

**Comment by jnm2377** [comment]
@TannerS yes, it definitely makes sense to update the docs to reflect this import change. Alternatively, I'm wondering if maybe these could be forwarded to the theme import since people are expecting them to be there @joshblack?

**Comment by TannerS** [comment]
you can close this, thank you!

**Comment by TannerS** [comment]
unless @joshblack  says anything about the above
