### ISSUE TITLE
[Bug]: Carbon 11 Button's renderIcon does not position correctly for functions

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#11168]
### Package

@carbon/react

### Browser

Firefox

### Package version

v11

### React version

v18

### Description

With Carbon 11, you can pass in a size to an icon such that instead of doing this in v10

```
import { Add24 } from '@carbon/icons-react';
```

you can do this in v11

```
import { Add } from '@carbon/react/icons';
...
<Add size={24} />
```

So here is my issue, before I could pass a Icon object into the `renderIcon` of a `Button` component as such 

```
 <Button renderIcon={Add24} />
```    

But if we wanted to use the new carbon 11 way passing in a size as such, you have to use a function for this to work 

```
 <Button renderIcon={() => <Add size={24}>} />
```    

Now I noticed these two different ways the icon position is off. 

Using an object (passing in something like `Add24`)

![image](https://user-images.githubusercontent.com/8866319/162104232-0d408fac-ef47-4acd-8f6c-6d4f94898142.png)

Passing in a function (`() => <Add size={24}>`)

![image](https://user-images.githubusercontent.com/8866319/162104423-c35c59ff-b952-4acb-bfda-17df25e816a9.png)

The pos is off. I know we can just import bot h`Add` and `Add24` to solvethis , but wanted to ask if I was doing something wrong or if this was ab ug?

### CodeSandbox example

N/A

### Steps to reproduce

See Description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by TannerS** [comment]
Actually, it looks like I have to do the function route for this case 

```
WARNING in ./src/client/components/Support/MoreHelps.js 87:16-21
export 'Add24' (imported as 'Add24') was not found in '@carbon/react/icons' (possible exports:
```

**Comment by rwibm** [comment]
@TannerS This is due to missing classes on the SVG element, it can be fixed by passing the props to the function component, like this:

renderIcon={props => <Add size={24} {...props}/>}

**Comment by TannerS** [comment]
> @TannerS This is due to missing classes on the SVG element, it can be fixed by passing the props to the function component, like this:
> 
> renderIcon={props => <Add size={24} {...props}/>}

Yup, this worked. I also learned that, even with the `size` prop, it doesn't matter. It appears with a function rendering an icon with a fixed size prop gets ignored and the icon gets set to the size of what the component chooses.

if a function is used, the props appears to be needed as you said. 

can this be added in docs somewhere? maybe storybook? I seen others with this issue and no where does it mention passing in props as the functions call back for the `renderIcon prop`. I feel this would help others, but with that said, my issue has been resolved, thanks @rwibm !

**Comment by rwibm** [comment]
I agree this should be added to the documentation, unfortunately the carbon v11 release seems to be riddled with bugs and lacklustre documentation. I don't work on the Carbon team, I'm just trying to use the latest release and hitting the same brick walls as everybody else.

Things that used to work fine don't work as expected anymore, components have props removed or changed without it being documented anywhere, some components simply don't work at all, and other components chuck out console errors with basic usage, its a bit of a mess really; I expected better considering v11 was delayed so much, there is a clear lack of testing before this release, its rather disappointing.

Hopefully the carbon team will see the number of v11 issues and initiate another round of testing.


Anyway, complaints aside, I'm glad you got your problem fixed! Happy coding!

**Comment by tay1orjones** [comment]
@TannerS sorry you ran into this! Thanks for bringing it to our attention.

> I agree this should be added to the documentation

@rwibm I agree as well. We've attempted to cover everything in the [expanded migration document](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md) in the repo, but in some cases we haven't caught it all. I'll put up a PR for this usage update.

Sorry to hear you've ran into what sounds like a ton of issues. We've never stopped testing. The team is fully committed to furthering the v11 release and working daily to improve the documentation, fix bugs, and continue hardening the v11 release. We'd very much welcome your feedback through creating issues or the [v11 discussion](https://github.com/carbon-design-system/carbon/discussions/11184) so we can rectify the problems you've found whether it be usage docs, migration info, or bugs.

**Comment by TannerS** [comment]
Thanks Taylor! From a technical aspect, can someone explain what these props are that is needed for these to work? Are they styles?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
ok, thats my bad, is there anyway the storybook can maybe ref this ? other then that ya my bad, feel free to close this @tay1orjones

**Comment by tay1orjones** [comment]
@TannerS No I totally agree, just wanted to surface that here for reference. I'll have a PR up for the storybook in a few minutes
