### ISSUE TITLE
[Bug]: Carbon styles are broken (prefix cds vs bx)

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon#11176]
### Package

@carbon/react, carbon-components-react

### Browser

Chrome

### Package version

11.0.0

### React version

1.0.1

### Description

With new Carbon version the class name prefixes seem to be differ in css (`bx`) vs js (`cds`) and this causes all components to be broken. Also all of the react codesandboxes (on carbondesignsystem.com) are broken.
 
This also happens in older versions, at least I had it with version `^8.0.3` in a Gatsby site.
Not sure how many other experience this and its only happening in the react packages, but this seems quite severe.

I don't really see any documentation to switch the components back to use `bx--` because the sandbox is using the precompiled css version.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/3808948/162269165-b3e6831d-b7e4-4a2e-b82f-a7fffe991264.png">

### CodeSandbox example

https://codesandbox.io/s/tcredf?file=/index.js

### Steps to reproduce

1. Install carbon-components and and `carbon-components-react` or `@carbon/react`
2. @import 'carbon-components/scss/globals/scss/styles.scss';
3. import { TextInput } from "carbon-components-react";

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hi @ConradSchmidt, thanks for making an issue! We've released v11 of Carbon Design System, and with that has come some breaking changes. Specifically, we have switched our prefix from `bx` to `cds`. Due to this, `@carbon/react` on v1 and `carbon-components` on v10 are incompatible. Here is a new sandbox link for [v11](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/examples/codesandbox) and one for [v10](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v10/packages/react/examples/codesandbox), if you need it.

**Comment by ConradSchmidt** [comment]
Got it. But all the samples on the carbondesignsystem.com site are broken, which I don't think is good.
And I also got this issue without using Carbon 11, as mentioned in the issue, I got the same issue with a Carbon v10/8 `carbon-components-react` release so - not sure whats going on there. Somehow there is a default set for `cds` even though the css is compiled with `bx`.

**Comment by abbeyhrt** [comment]
We are definitely working on getting those links updated! 

Sorry for misunderstanding earlier! For v10/8 issue you are mentioning, v10 `carbon-components` and v8 of `carbon-components-react` are also incompatible. V8 of `carbon-components-react` is a new major version, it contains all of the breaking changes that we introduced as a part of our v11 release. If you don't want to migrate to the new versions then, you will need to stay on v10.56 and below of `carbon-components-react` and v7.56 and below of `carbon-components-react`

**Comment by ConradSchmidt** [comment]
Okay, maybe I have to check again more detail. I'm just worried that this happend without me changing anything in my repo (didn't touch the `package.json` at all) the whole application broke. I guess I used

**Comment by ConradSchmidt** [comment]
Okay, maybe I have to check again more detail. I'm just worried, because this happend without me changing anything in my repo (didn't touch the `package.json` at all) and the whole application broke. I used `^`  so it should automatically update to the next major version without me changing it. But maybe I just configured something else wrong.

**Comment by abbeyhrt** [comment]
That is definite cause for concern! I'm really sorry that happened and I would love to help figure out what's going on.

I have no idea if this is applicable to your application, but the only time we've run into something breaking with the release where nothing was deliberately updated was if someone was using either of these cdn links https://unpkg.com/carbon-components/css/carbon-components.min.css or https://unpkg.com/carbon-components/scripts/carbon-components.min.js,  without specifying a version. Could that be relevant here?

**Comment by dntzbgh** [comment]
> That is cause for concern, for sure! I'm sorry that happened, that's so frustrating! We would love to help figure out what's going on. Pinning it that way, as far as I know, definitely should have prevented an update to a major version.
> 
> I have no idea if this is applicable to your application, but the only time we've run into something breaking with the release where nothing was deliberately updated was if someone was using either of these cdn links https://unpkg.com/carbon-components/css/carbon-components.min.css or https://unpkg.com/carbon-components/scripts/carbon-components.min.js, without specifying a version. Could that be relevant here?

What would be the correct import link?
I tried using the version but it does not seem to find the files.

**Comment by bewards** [comment]
How can $prex be overriden using @carbon/styles package? I need to use the styles only for a single svelte component (multiselect). I tried using **with** on the component itself:

```scss
@use '@carbon/styles/scss/components/multiselect' with (
    $prefix: 'bx'
);
```

**error:**
![image](https://user-images.githubusercontent.com/3927169/170551118-c9f97202-3d5d-469f-8e0d-fdd8eeb440af.png)

**Comment by tay1orjones** [comment]
@dntzbgh unpkg versioned links use the `@`. The url below will only bring in the latest minor release of `v10.x`

```
https://unpkg.com/carbon-components@10/css/carbon-components.min.css
```

**Comment by tay1orjones** [comment]
@bewards `$prefix` isn't declared in the component, you'll need to configure the `config` module

```
@use '@carbon/styles/scss/config' with (
  $prefix: 'bx'
);
@use '@carbon/styles/scss/components/multiselect';
```

**Comment by tay1orjones** [comment]
All the above issues appear resolved. Closing
