### ISSUE TITLE
[Bug]: OverFlowMenu's iconDescription text is overlays the itemText of the first OverflowMenuItem

### ISSUE THREAD

**Issue by dsav-eng** [carbon-design-system/carbon#11170]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.35.0

### Description

Can be seen in the storybook example: https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--default

In case when the `OverFlowMenu` is opened, and user hovers over on the icon, the `iconDescription` text gets displayed. Since there is no way to offset the position of the `iconDescription` text, it would overlay the `itemText` of the first `OverflowMenuItem`.

### Screenshots

![Screen Shot 2022-04-07 at 9 36 28 AM](https://user-images.githubusercontent.com/61568562/162212533-8dc53a94-34c7-4245-9665-c1859d766d99.png)

### Steps to reproduce

Can be reproduced using the storybook example: https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--default
- user clicks on the 3-dotted icon ---> menu is displayed
- user hovers over the icon while the menu is displayed --> after waiting for about 2 seconds `iconDescription` will be displayed on the UI which means the first menu option wold be partially hidden. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Hi @dsav-eng we appreciate you opening this issue, but unfortunately we don't feel this warrants any changes on our behalf for a few reasons:
- the title tooltip is browser controlled and not something we override
- the title tooltip appears when you're hovering on the three dots `...` to open the menu, and that interaction is very brief to open and close the menu, so users can move their mouse to avoid the title tooltip if it blocks their view
- you can also choose not to include the icon description so the title tooltip doesn't pop up

Given those course of actions, we're gonna close this issue for now. 🙂
