### ISSUE TITLE
[Feature Request]: Include counter for TextInput

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#11179]
### Summary

I would like to proposal adding a text counter to `TextInput` the same way `TextArea` has one

### Justification

I feel like, that even thought text inputs dont exact large amounts of text as text areas do, theres still services (like ours) that have limits and would be awesome to show that so the styling of the page could match.

Here is a page for our service. the data for all fields has text limits that could extend outside the components view if screen is small enough and would be nice to let the user know of the length.

It is also nice to make it consistent across the page since we have multiple pages of mixture of text areas and text inputs where we use carbons text counter, our own, or mix them but that kind defeats the purpose

![image](https://user-images.githubusercontent.com/8866319/162287345-ee4738c9-12d2-40c7-ae1f-343397f8db4c.png)

### Desired UX and success metrics

I feel like the main thing of this is it will help more helpful than not, and consistent with the inputs 

### Required functionality

This would require some mimics code form the textarea component 

### Specific timeline issues / requests

N/A

### Available extra resources

I dont mind doing a PR for this as I was the one who added it for text area I just need the go ahead 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by TannerS** [comment]
@abbeyhrt @joshblack @jnm2377 @tay1orjones can I get some feedback? I am ready to put a PR in when ever you guys allow metoo if you think it is reasonable :)

**Comment by tay1orjones** [comment]
@TannerS Sorry for the lack of movement here, we've been working to revisit the pipeline for how we evaluate and address enhancement requests so things like this happen less.

I'd like to make sure we loop in design to review the idea - @aagonzales what do you think for this request?

**Comment by aagonzales** [comment]
In general, I think it's a good idea to add. But I think it may need some design exploration (it's been a while since we've looked at it). Is this the best way to surface character count? 

[uk.gov](https://design-system.service.gov.uk/components/character-count/) does it as help text under the field and in more of a sentenced format.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/11670886/178346721-de3d87cc-44ca-4b77-b620-53afa22a8093.png">

Characters remaining vs characters used ... maybe there's a need for both

**Comment by aagonzales** [comment]
Seems like its pretty common to count down instead of up
https://designsystem.digital.gov/components/character-count/

**Comment by aagonzales** [comment]
Material uses a ratio though ... like the original design. This is why some design research/exploration might be helpful before moving forward/

<img width="654" alt="image" src="https://user-images.githubusercontent.com/11670886/178347497-50f1f342-962c-4c22-a0d6-78f9920c4f00.png">

**Comment by thyhmdo** [comment]
Spectrum has [another approach ](https://spectrum.adobe.com/page/text-field/)that is similar to our Text fields or text areas. The only concern is if the label gets long, it may get into the character count. 

![](https://spectrum.adobe.com/static/images1x/text-field_anatomy_1645653349638.png)

**Comment by TannerS** [comment]
I can do any design that is chosen I just feel both text input and text area should match

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sstrubberg** [comment]
Hey @TannerS, @jeanservaas will bring this idea to the [DSAG](https://pages.github.ibm.com/cdai-design/pal/contributing/contribution-framework/iterate) and assess the appetite of this proposal to validate whether it's worth taking on. Please reach out to her for when that will be taking place. We'll also be looking for designers, that can spare some cycles to bring this over the line for you and harden the design spec, after which, it'll be back to you to contribute back to Carbon. We can help guide you through this process in dev office hours.

**Comment by sstrubberg** [comment]
Sweet. @TannerS Would you be open to coming to [design office hours]([https://ibm.biz/carbon-design-office-hours](https://ibm.ent.box.com/notes/660977053477?s=sr66djycn0u35a3yj34s3pse6wglya1q)) so we can hash this out? @aagonzales @jeanservaas

**Comment by TannerS** [comment]
@sstrubberg sure (no access to that box note) feel free to invite me hahehe

**Comment by jeanservaas** [comment]
For some reason that link above isn't working for me, here it is again.

https://ibm.ent.box.com/notes/660977053477?s=sr66djycn0u35a3yj34s3pse6wglya1q

**Comment by TannerS** [comment]
Hey Anna, I'm just trying to piggy back off how the TextArea is currently doing it. I believe the TextArea has it on top with the label due to conflicting with the helper text but I could be wrong. With that said, if the design for the text input differs based off these suggestions, I feel the TextArea should follow so both should be consistent

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
