### ISSUE TITLE
Further automate releases

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11188]
Currently the release process takes a bit of time and impacts dev productivity. This can easily be reduced by taking time to further automate the process.

Ideal to-be process could look like:

1. GitHub Action is automatically activated at a regular interval (or via manually starting the action)
2. Action bumps versions for packages that need a bump based on conventional-commit format
3. New tags are created based on the version bumps
4. Packages are published to npm 

Checklist

- [ ] Determine lerna commands/options that can be used in an automated environment to achieve the proper version bumps (`--conventional-prerelease`, `--conventional-graduate`, etc.)
- [ ] Update the release action with these commands
- [ ] Test via manual invocation for a minor release and patch release
- [ ] Add automatic interval for rc versions every other tuesday following the release schedule
- [ ] Add automatic interval for stable/latest versions every other thursday following the release schedule

Open questions
- Do hotfix patch versions fit into this strategy? Maybe we continue to cut those manually since they're typically a cherry-pick of a single commit off `main` onto the patch release branch.
- Should the action create a release PR to approve before the release is cut?

**Comment by joshblack** [comment]
Going to close this one out for our sprint as we tackled our minor release flow 👍
