### ISSUE TITLE
[Bug]: DatePicker (range) always returns undefined onChange

### ISSUE THREAD

**Issue by spacemolly** [carbon-design-system/carbon#11181]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.0.3

### React version

v17.02

### Description

The date range picker does no longer return any output on change. `onChange={(dates, datesString, self) =>` returns undefined on all three variables. Before these returned a Date array, formatted string and the Flatpickr object.

### CodeSandbox example

https://codesandbox.io/s/hungry-pike-dg6294?file=/src/App.js

### Steps to reproduce

Check outputs of onChange on DatePicker.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by spacemolly** [comment]
I've checked with the latest version (1.1.0) and this is still not working.

**Comment by abbeyhrt** [comment]
@spacemolly you're right, thanks for looking into it! Sorry about that, our internal hook wasn't passing along the arguments. Made a PR to fix it: https://github.com/carbon-design-system/carbon/pull/11253
