### ISSUE TITLE
Experimental Component: Checkbox

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1118]
Here's the checkbox. I feel like I'm supposed to write more shit in here.
[Checkbox.zip](https://github.com/IBM/carbon-components/files/2394548/Checkbox.zip)

**Comment by alisonjoseph** [comment]
Hi @jeanservaas can I get exact measurements for the checkbox. We aren't using icons for this, we are building with pure css. 

- box width/height
- checkmark width/height when turned on its side (we rotate it with css)
- space between the checkbox and the text
- should checkmark be 1px or 2px thick 

This is what I have so far, just want to be sure the measurements are correct! thanks 
![Screen Shot 2018-09-19 at 2.52.20 PM.png](https://images.zenhubusercontent.com/5667369b638e718c995f3b3e/43a261ac-63ae-405f-8950-7cb4fa278650)

**Comment by jeanservaas** [comment]
Hi Alison,

Sorry for the late reply, I wasn't checking my gmail! only looking at slack and work mail. 

- When I go into the symbol, the checkbox actually sits on a half pixel. It's 15px x 15px wide on a 20px canvas and the stroke technically measures 1.25 px.

Not pretty. I will ask Chris Connors / Conrad about the logic, but that's how the symbol's composed. 

-  6.51px  x 8.75px is the measurements of the check on its side

- If you're measuring from the actual checkbox, minus the padding, the distance from the type is 10px.



<img width="555" alt="screen shot 2018-09-19 at 6 30 00 pm" src="https://user-images.githubusercontent.com/43144260/45787371-9d6b9a80-bc3a-11e8-8a7f-aa994e3a1af4.png">

**Comment by alisonjoseph** [comment]
Ah ok, yea I opened the file in sketch and nothing seemed to be a standard distance/length. 

The border will need to be either 1px or 2px, and will make the check mark as close as possible to the icon design. 

Let me know if any of the spacing changes.

_ps- you can add your ibm email to github as a secondary email and set it up to get notifications there so it doesn't blow up your personal email._

**Comment by jeanservaas** [comment]
Hey Alison,

Yeah, we'll go with 1px. I know Connors is having a meeting about the way the icons are being dealt with (with the padding on the canvas etc.) I'm going to talk to him later. It makes spacing confusing unless they're symbols or you're pulling them from a library.

I transferred my Github notifications to my ibm email!

**Comment by alisonjoseph** [comment]
Thanks! the checkbox is a weird one because while the design is using the actual icon, the code isn't. 😸
