### ISSUE TITLE
Export as PNG and PDF is showing all hovers and table batch action 

### ISSUE THREAD

**Issue by Ankita-Jaiswal** [carbon-design-system/carbon#11224]
I have tried multiple packages like html2canvas, use-screenhot, react-component-export-image ,jspdf ,html-to-image etc etc.

All these packages are working perfectly fine if used with material, bootstrap, and simple HTML(title property ). But with carbon, it captures hover, table batch action if the body contains a data table.

is there any way to hide those from exported files (png/pdf) or any package that carbon provides which will not have such issues

![image](https://user-images.githubusercontent.com/16722905/163205869-6fc5cc53-ae24-40a9-bbc1-c65ea38ae563.png)

**Comment by theiliad** [comment]
Pls feel free to reopen @Ankita-Jaiswal with additional comments 🙂
