### ISSUE TITLE
[Question]: is `$prefix` configurable for typographic tokens?

### ISSUE THREAD

**Issue by jeppetn** [carbon-design-system/carbon#11221]
### Question for Carbon

Hi,

We have a blazor application where we use carbon design system version 11.

We have defined a custom prefix to be "boy-cds".

This works fine when using your classes and mixins for all components. For example a button gets this css property `color: var(--boy-cds-text-on-color, #ffffff);`

However our headings have these css properties:
`font-size: var(--cds-heading-07-font-size, 2.625rem);
    font-weight: var(--cds-heading-07-font-weight, 300);
    line-height: var(--cds-heading-07-line-height, 1.19);
    letter-spacing: var(--cds-heading-07-letter-spacing, 0);`

It seems our custom prefix, "boy-cds" is not used for headings(we have not tested other typographies). 

Is it supposed to not have the custom prefixes for headings?

Thanks,
Jeppe

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @jeppetn! 👋 

Thanks so much for bringing this up, when taking a look at this it seems like there is an issue with correctly forwarding along the prefix to the type package. I made a PR over in #11228 in order to address this.

Let me know if this captures the use-case you're describing or if your question was related to something else!

**Comment by jeppetn** [comment]
Hi joshblack,

Yes I think this answers my question well and it seems it will be solved by this.

Do you have a rough idea of when it will be a part of a release for version 11?

Thanks,
Jeppe
