### ISSUE TITLE
[Feature Request]: A new component: AutoComplete 

### ISSUE THREAD

**Issue by draccagni** [carbon-design-system/carbon#11236]
### Summary

A dropdown component with the ability to filter selectable items by typing the initial letters of the item's label. 

### Justification

This component is used in many projects that I am developing, particularly when the filtered elements are retrieved through a REST service, especially if there are many results available. A practical example: the list of municipalities of a nation.

### Desired UX and success metrics

The user types a configurable number of characters the items' label could start with. The component responds opening a popup containing the filtered items. The user can select the desidered item by clicking on item, or typing the up/down keys and then enter key.  

### Required functionality

The list of selectable items has to be build dynamically on the base of the filter typed by user.

### Specific timeline issues / requests

The availability of the component is binding for the choice of Carbon technology in the next projects. I'm developing it in my [carbon-components-svelte](https://github.com/draccagni/carbon-components-svelte) fork.

### Available extra resources

Myself

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> how can I solve the problem of a dynamic set of items retrieved by a REST service using as query parameter the filter value?

@draccagni `onInputChange` is intended to provide support of changing the available items based on the text. Change events within the input are passed to this callback function, where you could make an API call or other logic and then provide a new `items` array to the component.
