### ISSUE TITLE
[Bug]: The specified padding for modal dialogs differs from the refrence implementation

### ISSUE THREAD

**Issue by smaclagaibm** [carbon-design-system/carbon#11235]
### Package

carbon-components

### Package version

11

### Description

The specification calls for 20% right margin for body copy within the dialog.
The diagram indicates that this 20% is measured from the edge of the container, which overlaps with 16px standard padding.
![](https://www.carbondesignsystem.com/static/78b566592912c237b8ca9a5bd7ec5b82/3cbba/modal-style-2.png)

The reference implementation has a 20% right padding measured from the left edge of the standard 16px padding

### CodeSandbox example

https://react.carbondesignsystem.com/iframe.html?id=components-modal--default&args=&viewMode=story

### Steps to reproduce

Inspect the paragraph styling showing the 20% right padding:
.cds--modal-content p, .cds--modal-content__regular-content
padding-right: 20%;

And the padding for the outer div container:
.cds--modal-content
padding-right: 1rem;

Assuming a 1000px wide dialog.
The specification indicates that there should be 200px (20%) padding between the right of the text and the right edge of the dialog.
Assuming the same 1000px wide dialog with the reference implementation:
Inner Content Width = 1000 - 16px (left) - 16 px (right) = 968 px
Inner Content padding = 20% of the Inner Content Width = 20% of 968px = 193.6px
The padding between the right of the text and the right edge of the dialog would be 193.6px + 16 px = 209.6px

Please resolve if the specification or the reference implementation is "correct"

If I get a vote, the reference implementation would be easier for us to adopt into our product's usage.
:)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
[Here's the original slack thread](https://ibm-studios.slack.com/archives/C046Y0YUD/p1649874262475109) that initiated this issue. 

@aagonzales I'm not sure if the image is wrong or the implementation is wrong, but the implementation doesn't calculate the 20% from the edge of the container. It's from the edge of the 16px padding.

**Comment by smaclagaibm** [comment]
The reference implementation shown below has 20% padding-right (in purple) based on the width of the inner content. It excludes the 16px left/right when calculating the 20%. Compare that to the diagram from the specification in the original post.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/103686632/165766700-5d5af02d-15d7-494b-8cd5-95ac68237213.png">

**Comment by smaclagaibm** [comment]
@tay1orjones 
The calculation would need take into account the full width of the dialog, correct?
In which case it'd need to account for the 16px from the left-padding and the 16px from the right-padding.

I was hoping this would go the other way (problem in the spec), but it's good to have an answer.
Thanks

**Comment by tay1orjones** [comment]
> The calculation would need take into account the full width of the dialog, correct?

@smaclagaibm Yeah you're right, that's a good distinction. 

It's worth noting that overall this being out of spec is a very minuscule visual difference. Probably should not be a stop-ship for anyone.
