### ISSUE TITLE
[Bug]: Outdated typescript definations for @carbon/icons-react

### ISSUE THREAD

**Issue by 0xHexE** [carbon-design-system/carbon#11248]
### Package

@carbon/icons-react

### Package version

11.1.0

### Description

Type definitions at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/carbon__icons-react/index.d.ts are outdated.

### CodeSandbox example

NA

### Steps to reproduce

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
See https://github.com/carbon-design-system/carbon/discussions/10752
