### ISSUE TITLE
[Question]: v11 -  Unable to change prefix @carbon/react

### ISSUE THREAD

**Issue by ferdelamad** [carbon-design-system/carbon#11245]
### Question for Carbon

Hi team, when upgrading to use @carbon/react (to get v11 enhancements), I'm trying to update the prefix back to 'bx' since I have custom styles on my project.

I'm trying:
```
@use '@carbon/react/scss/config' with ($prefix: 'bx');
```
Which does not add the prefix to the classnames and it also does not apply the carbon styles to the components.

When I only do:
```
@use '@carbon/react';
```
The components load when the proper carbon styles but obviously with the new 'cds' class that I need to change.

Any help is extremely appreciated!
Thanks

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @ferdelamad! 👋  Thanks so much for raising this issue, definitely see what you mean. In our beta/RC phase we had exposed the React Context value for this use-case and did not correctly introduce this functionality for the GA release.

I made a PR over at: https://github.com/carbon-design-system/carbon/pull/11254 to correct this and it should be included in the next release. This will allow you to use a component called `ClassPrefix` to set the prefix value inside of React that you set in your styles.

Would love your feedback on the documentation in that PR to see if that makes sense / aligns with your use-case, by the way 🙏

**Comment by ferdelamad** [comment]
Hey @joshblack thanks for updating this! I do think this new wrapper will be very useful.

Just to make sure I understand this correctly, in order to have a custom prefix, I will need to update the scss:
```scss
@use '@carbon/react' with (
  $prefix: 'custom'
);
```
And also **wrap every** component using the new **ClassPrefix** component?

In my company we are extending the carbon components, so basically we are importing most of them, it seems like we will probably need to update every component and use this approach for new additions as well if we want to preserve the 'bx' prefix.

**Comment by joshblack** [comment]
Great questions!

> And also wrap every component using the new ClassPrefix component?

You should only have to do this once at the top of your app. `ClassPrefix` will then update the prefix for every component that is rendered as a child to it using context.

> Last question, when does carbon usually publishes these kind of updates?

Our release cadence right now is every other week for a minor release and as-needed for patches/hotfix.

You can follow along over at: https://github.com/carbon-design-system/carbon/wiki/Release-radar if that's helpful!
