### ISSUE TITLE
Research VRT with storybook's playwright runner

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11252]
This issue is to explore and document the findings of using Storybook's new test runner feature. It uses playwright and would be interesting to determine how we could use it to enhance our test coverage. 

Open questions:
- Is it possible to use Percy to snapshot during a storybook test run?
- Could we step through components using storybook's test runner and then snapshot along the flow?
- Can we use this without having to write one-off stories that are only used for testing?
- Can this integrate with `accessibility-checker`?
- Is it possible this could replace our usage of cypress?

The outcome here will influence the overall direction for the parent issue: Using storybook for VRT, #11051.

**Comment by joshblack** [comment]
Going to close this out as done now that the VRT PR has been merged in!
