### ISSUE TITLE
[Feature Request]: A new component: Rich Text Editor

### ISSUE THREAD

**Issue by draccagni** [carbon-design-system/carbon#11272]
### Summary

An editor component that allows you to type rich text containing images, videos, links, etc.

### Justification

This component is used in many projects that I am developing, where the users need to include images, videos, links, etc. in specific fields.

### Desired UX and success metrics

The user types rich text that can contain images, videos, links, etc, to be rendered inside the current page. 

### Required functionality

The component has to permit to type rich text that includes images, videos, links, etc. that can be saved within a data object.

### Specific timeline issues / requests

The availability of the component is binding for the choice of Carbon technology in the next projects. I'm developing it in my [carbon-components-svelte](https://github.com/draccagni/carbon-components-svelte) fork.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by shixiedesign** [comment]
FYI an older contribution exist for this feature. I thought the design is good and can be reused: 
https://github.com/carbon-design-system/carbon/issues/2447

![image](https://user-images.githubusercontent.com/15144993/164742540-9874f0b3-6a10-4104-9d81-2a499518ce39.png)

**Comment by sstrubberg** [comment]
Hey @draccagni, can you tell us a little more about yourself. Like what team, PAL, or Product you work on? Have you seen the editor used by Carbon for IBM Products? As we determine whether or not to take this component on, it would be helpful to know more about where this would be used at IBM along with whether you have used existing patterns developed by other teams. Thanks! Feel free to hit me up on Slack as well @sstrubberg

**Comment by sstrubberg** [comment]
Closing this for now. Hit me up if you want to have a conversation about this and re-open the issue.
