### ISSUE TITLE
[Bug]: Popover not working as expected

### ISSUE THREAD

**Issue by pmweeks98** [carbon-design-system/carbon#11281]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.1

### Description

Following example from https://react.carbondesignsystem.com/?path=/docs/components-popover--playground
Popover not displaying as expected , PopoverContent is always displayed even if prop open is explicitly set to false. It is also displayed to the right of the element instead of a tooltip

![image](https://user-images.githubusercontent.com/56260662/165093962-ae691875-b3e3-4013-ac60-7e3dfb6b5749.png)

### CodeSandbox example

https://codesandbox.io/s/fervent-torvalds-tu49yb

### Steps to reproduce

Above code sandbox has issue

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there, @pmweeks98! 👋 I think the challenge is that you're including styles from the v10 `carbon-components` package instead of the v11 package. If you pull styles directly from `@carbon/react` using Sass then I believe you'll see Popover render as intended.

Let me know if you have any questions!

**Comment by joshblack** [comment]
Great questions @pmweeks98! In v11, you can use `@carbon/react` directly and it will contain all the styles and React components that you need. `carbon-components-react` is also available but is more so of a compatibility option for teams going from v10 to v11. The intent is to use `@carbon/react` directly.

For the demo that you're sharing, I think the biggest thing is to make sure to include the reset from the styles. It also seems like the environment is a little out of date (react-scripts is set to 1.0.0) and that could also be causing some challenges.

I tried to download the codesandbox and tweak it to get it to work, let me know if this helps!

[bhv2uq.zip](https://github.com/carbon-design-system/carbon/files/8603985/bhv2uq.zip)

**Comment by joshblack** [comment]
Hi there! 👋 Going to close this out due to inactivity. Feel free to comment and we can re-open!
