### ISSUE TITLE
Color.scss is missing the colors text-01, text-02.

### ISSUE THREAD

**Issue by astha-jain** [carbon-design-system/carbon#1129]
This is the list of colors in CDS webpage. 
http://www.carbondesignsystem.com/style/color/swatches

These colors are missing from _colors.scss file which were previously available.
https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_colors.scss

Updated carbon-components version from 9.5.0 to 9.18.0 today.

**Comment by tw15egan** [comment]
Seems like they were moved from `_vars.scss` to `_theme.scss`

https://github.com/IBM/carbon-components/pull/1045/files

**Comment by astha-jain** [comment]
@tw15egan will this be reverted back to _vars.scss or going to stay on _theme.scss?

**Comment by asudoh** [comment]
@AsthaJain1 It's the latter. Sorry for the inconvenience that causes. You can adjust the imports to cope with that, but let us know if there are any reasons which makes it hard for you to do so. I guess we can make `_vars.scss` import `_theme.scss` if it's the case. Thanks!

**Comment by tw15egan** [comment]
Added the import back to `_vars`, so it shouldn't break anyone anymore
