### ISSUE TITLE
[Bug]: React Tabs storybook could be improved

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon#11291]
### Package

@carbon/react

### Browser

Chrome

### Package version

https://react.carbondesignsystem.com/?path=/story/components-tabs--manual

### Description

If you go to https://react.carbondesignsystem.com/?path=/story/components-tabs--manual
the Example button  is _always_ showing up. However, it is supposed to appear _only_ when the second tab is selected.
<img width="909" alt="Screenshot 2022-04-26 at 7 41 46 AM" src="https://user-images.githubusercontent.com/14298245/165327368-6b5dad96-398d-456b-8c59-8c2a9c263535.png">

Here's what it should look like....
The non-manual with tab 1 selected:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/14298245/165326933-b4c63920-232d-4a2d-8c9d-b487863d428d.png">

And then non-manual when the second tab is selected
<img width="919" alt="image" src="https://user-images.githubusercontent.com/14298245/165327549-d186d658-1294-4f9a-bf0d-1311cf0436c3.png">

--- 

BTW, in addition to it appearing when it shouldn't on the manual example, in all examples, I'd like to suggest that this Example button should be located underneath the "Tab Panel 2" text. it's pretty awkward/non-sensical where it is.

If you agree its position is odd, it needs to be repositioned across all Tabs examples.

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-tabs--manual

### Steps to reproduce

It's probably better to list the steps for what it's supposed to be.
Expected behaviour:
1. navigate to the tab example
2. confirm that Example button does not appear on tab panel 1
3. Navigate to tab 2 (and activate if necessary)
4. Confirm the Example button appears on tab panel 2
5. Navigate to tab 3, activating if necessary
6. Confirm the Example button does not appear on tab panel 3.

Carry this out with https://react.carbondesignsystem.com/?path=/story/components-tabs--contained and it will pass.
 Carry it out with https://react.carbondesignsystem.com/?path=/story/components-tabs--manual and it will fail.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @mbgower! For the "Manual" story, the example button _is_ the content for the first Tab, not the second tab, so I believe it is showing up when it is supposed to. This is different than the some of the other examples, where the Button is in the second TabPanel, so I'm down to change the stories to be more consistent.

And totally agreed that it is visually odd! The button was chucked in to show what the TabPanel does when it has interactive content in it. I would love to brush up the examples when I have some time.

**Comment by mbgower** [comment]
Oh, I see! You changed which panel it's under on the Manual example! Okay, that confused the hell out of me PLUS I forgot to actually activate on the manual one to update content (which of course doesn't happen on the automatic one). So partially user error, partly inconsistent examples :)

If you can make the button always be on the 2nd one (and make it look better!) I'll endeavour to operate thing properly :)

**Comment by mbgower** [comment]
> The button was chucked in to show what the TabPanel does when it has interactive content in it. I would love to brush up the examples when I have some time.

I think putting a link inside the text in the Control panel is probably a less jarring way of getting same thing. i.e.
Tab panel 2
A [link](url) inside panel content.

**Comment by spraguejdev** [comment]
Hey, @mbgower. I'm looking to pick up my first issue. Would you be willing to have a noob take care of this for you?

**Comment by aledavila** [comment]
issue has been fixed closing
