### ISSUE TITLE
UI Shell: Header Nav links font weight 

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#1130]
UI Shell: Type Font Weight bug. 

Font weight should be 400. The Link and Dropdown both appear to have 400 when inspecting the elements but are not showing the right weight on the screen. 

The dropdown seems to not be inheriting the font styles.

<img width="608" alt="screen shot 2018-09-20 at 1 30 40 pm" src="https://user-images.githubusercontent.com/12533409/45839239-6d270900-bcd9-11e8-8cb0-b9afc67f0ff5.png">

**Comment by dakahn** [comment]
I'll take this!
