### ISSUE TITLE
[Bug]: The NumberInput component's field actual font-weight is different from what is mentioned in the style definition section

### ISSUE THREAD

**Issue by baraaabdelsalam** [carbon-design-system/carbon#11301]
### Package

carbon-components-react

### Package version

v10.41.0+

### Description

The font-weight for the input field element is supposed to be 400 as mentioned in the style section in the [carbon design system webpage](https://carbondesignsystem.com/components/number-input/style), but when using the component or even looking at the [story book](https://react.carbondesignsystem.com/?path=/story/components-numberinput--default), there you can find that a different font-weight is used (300) which is also different than the TextInput field font-weight.

Is it supposed to be 300 like how it is implemented right now or 400 similar to whats documented in the component's style definition page?

### CodeSandbox example

https://codesandbox.io/s/number-input-font-weight-966o64

### Steps to reproduce

https://codesandbox.io/s/number-input-font-weight-966o64

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@baraaabdelsalam Good eye! Yes, this should be updated to be 400 font weight.
