### ISSUE TITLE
What is the desired behavior for labels when their associated input is focused?

### ISSUE THREAD

**Issue by cwgorman** [carbon-design-system/carbon#1131]
## Summary

We noticed an inconsistency with labels on the carbon site. 

Labels for inputs change color sometimes when their associated input is focused. What is the intended design here? Should the label only change color for inputs that are part of forms? But the CSS is more generic than that.

Here's a screenshot showing two inputs that have focus. One of them is on the [text input page](http://www.carbondesignsystem.com/components/text-input/code), the other is on the 
[form page](http://www.carbondesignsystem.com/components/form/code):

![image](https://user-images.githubusercontent.com/8108669/45887855-aa979f00-bd8a-11e8-8198-5f1340b93ac6.png)

**Comment by alisonjoseph** [comment]
The intended design is for the labels to change color, however, we had to change the order of the label and input in the html for an a11y fix to get it to pass DAP, so the labels are no longer changing color. The sample html on the form page has the incorrect order of the html elements. There is an open issue to fix this. #1052
