### ISSUE TITLE
[Feature Request]: Allow DataTable to filter and sort by enclosed string in a link

### ISSUE THREAD

**Issue by bpeicher** [carbon-design-system/carbon#11327]
### Summary

This is a development request. Adding a column of links to a TableCell seems to break sorting and filtering. Your own [documentation](https://react.carbondesignsystem.com/#sorting) doesn't appear to work when sorting on the "status" column. Ideally just the value between the open and close would be evaluated instead of the entire tag.

`<a href="https//cloud.ibm.com">Only search by me!</a>`

### Justification

We shouldn't lose filter and sort capabilities when adding links to a DataTable. Sorting and filtering by the displayed string in a link is just as valuable and logical as any other string.

### Desired UX and success metrics

If I can sort and filter a column of links, great success!

### Required functionality

Sorting and filtering a column of links.

### Specific timeline issues / requests

No specific timeline.

### Available extra resources

None at the moment.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Done! ✅ 

https://react.carbondesignsystem.com/?path=/story/components-datatable-sorting--default
