### ISSUE TITLE
[Feature Request]: FileUploaderButton with icon only

### ISSUE THREAD

**Issue by pjebs** [carbon-design-system/carbon#11320]
### Summary

It would be good if `FileUploaderButton` component had option to allow for icon only.

Workaround for svelte:
**FileUploaderButton.svelte**
```
<script>
  import { FileUploaderButton, Button, FileUploaderSkeleton } from 'carbon-components-svelte';
  import { Upload20 } from 'carbon-icons-svelte';
  import { onMount, createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  function forward(event) {
    dispatch('change', event.detail);
  }

  let uploadButton;
  let newButton;
  let show = false;
  onMount(async () => {
    // https://www.javascripttutorial.net/dom/manipulating/replace-a-dom-element/
    // https://stackoverflow.com/questions/2855589/replace-input-type-file-by-an-image
    let label = uploadButton.previousElementSibling;
    label.parentNode.replaceChild(newButton, label);
    show = true;
  });
</script>

<div style={(show) ? 'display: inline':'display: none'}>
<Button bind:ref={newButton} kind="secondary" hasIconOnly tooltipAlignment="end" icon={Upload20} iconDescription="Upload Scenes from Fountain File" on:click={uploadButton.click()} />
<FileUploaderButton kind="ghost" accept={[".fountain", ".fou", ".jpeg"]} style="display: none" bind:ref={uploadButton} labelText="" on:change={forward}/>
</div>
```

### Justification

For my UI I have a toolbar at the top. It affects the look and feel of the toolbar to have "text" based button and then once you have selected a file, for more ugly text of the file name.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Hey @pjebs thanks for making this feature request! I can see how having an iconOnly fileuploader button would be super useful. Unfortunately, at this time, we are unable to take the work-stream on as our backlog of requests is taking us well through the EOY, but we'd love to connect with you during office hours and talk about community contributions for this effort. Thanks again!

**Comment by pjebs** [comment]
@sstrubberg 
You can see the button in operation on my site: https://petersir.com/scripts/e6537f5c0c40---Notting%20Hill/

It works beautifully.

I am happy to help anytime.
