### ISSUE TITLE
[Question]: Is it possible to still use FilterableMultiSelectClassic?

### ISSUE THREAD

**Issue by ferdelamad** [carbon-design-system/carbon#11334]
### Question for Carbon

Hey Team 👋 ,
I'm trying to use the `FilterableMultiSelectClassic` in the latest release of @carbon/react.

Based on this line. it should be still available thought `Multiselect.Filterable`:
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/MultiSelect/index.js#L16

But I'm getting `undefined`.

Any help is appreciated, thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Hey there! None of those feature flags are used in v11 so there wont be any 'classic' for you to import. That file seems a little misleading, sorry. Depending on why you needed classic I might be able to help you out though.

**Comment by ferdelamad** [comment]
Hey @dakahn , thanks for the quick reply. The thing is that we are adding our own custom functionality on top of the filterable like this:
```
class FilterableMultiSelect extends MultiSelect.Filterable {
  constructor(props) {
    super(props);
    if (props.inputValue) this.state.inputValue = props.inputValue;
  }

  // hook setState so we can keep track of state changes
  setState = (newState, callback) => {
    const { onStateChange } = this.props;
    super.setState(newState, () => {
      typeof callback === 'function' && callback();
      typeof onStateChange === 'function' && onStateChange(this.state);
    });
  };
}
```
If we don't have access to the classic one we will need to refactor our current filterable to work with the newly refactored functional version de carbon.
