### ISSUE TITLE
[Bug]: Warning shown is console "React does not recognize the `openCalendar` prop on a DOM element"

### ISSUE THREAD

**Issue by bvhrs213** [carbon-design-system/carbon#11342]
### Package

@carbon/react

### Browser

Chrome

### Package version

v8.2.0

### React version

v17.0.2

### Description

A Warning is shown in webcosole when the DatePicker is used. I did not use the openCalendar prop.

"React does not recognize the `openCalendar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `opencalendar` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

### CodeSandbox example

_

### Steps to reproduce

Add the DatePicker with two DatePickerInputs for select a Date range.
<DatePicker
datePickerType="range"
className="date-picker-range-classname"
 size="md"
locale="en"
dateFormat="d M Y"
>
<DatePickerInput
id="date-picker-input-id-start"
labelText=""
 placeholder="dd/mm/yyyy"
size="md"
/>
<DatePickerInput
 id="date-picker-input-id-finish"
labelText=""
placeholder="dd/mm/yyyy"
size="md"
/>
</DatePicker>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This should be fixed by https://github.com/carbon-design-system/carbon/pull/11416
