### ISSUE TITLE
[Feature]: DatePicker escape key does not close the calendar when the focus is in the input field

### ISSUE THREAD

**Issue by vmukhachev** [carbon-design-system/carbon#11349]
### Package

@carbon/react

### Package version

v17.0.2

### Description

use single DatePicker, open the calendar, keep focus in the input element, press Esc on the keyboard, nothing happens.

### CodeSandbox example

https://codesandbox.io/s/silly-surf-jjp31o?file=/src/App.js

### Steps to reproduce

see description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@vmukhachev could you share the version of Carbon that this was last working in? When did you notice this change?

**Comment by vmukhachev** [comment]
@tay1orjones I don't know if it was working in some of the previous versions.

**Comment by tay1orjones** [comment]
It's unclear to me if this was ever supported by us, or flatpickr. I think this is new behavior that needs to be implemented.

**Comment by omkarajagunde** [comment]
@tay1orjones @sstrubberg I see this is working perfectly, checked in npmjs `@carbon/react: 1.40.0`, if the input is focused and Esc key is pressed, the calendar is closing correctly

**Comment by tw15egan** [comment]
Thanks for confirming this @omkarajagunde
