### ISSUE TITLE
[Feature Request]: TimePicker to work like native <input type=time> (dropdown + value should accept number of seconds, not formatted string)

### ISSUE THREAD

**Issue by vmukhachev** [carbon-design-system/carbon#11362]
### Summary

Hello,
it would be nice for the TimePicker to work like native <input type=time />
as it has a nice dropdown,
another thing is that right now the value is just a formatted string, would be nice if it can be a number of seconds for the simplicity of use.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
For this, one recommended pattern for input of seconds is [outlined on the website](https://carbondesignsystem.com/components/date-picker/usage/#related)

> Another acceptable form of a time or date experience would be using individual inputs for each factor. Using an individual field for each factor of a date or time can help reduce formatting errors. This is especially beneficial when localization cannot be used to reformat dates.
> Instead of having one input for an exact date (month/day/year), you could have three separate inputs and a clear label for each.

Essentially a single input for seconds that has a clear button. TextInput does allow you to override the `type` prop to what you'd desire.

Closing as we're not going to extend TimePicker for this use case, but let me know your thoughts on the workaround above. Thanks!
