### ISSUE TITLE
[Feature Request]: no way to attach Tooltip to OverflowMenu trigger icon button

### ISSUE THREAD

**Issue by vmukhachev** [carbon-design-system/carbon#11364]
### Summary

see the title

Don't know if it might work like below:
```jsx
            <Tooltip triggerText='test'>
                <OverflowMenu>
                    <OverflowMenuItem itemText='test'></OverflowMenuItem>
                </OverflowMenu>
            </Tooltip>
```
or if OverflowMenu might have an attribute...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Tooltips on OverflowMenus aren't supported in v10. Related https://github.com/carbon-design-system/carbon/issues/9208

In v11 you can wrap the OverflowMenu in a Tooltip with something like this

```
import { Filter } from '@carbon/icons-react';

<Tooltip label="Tooltip contents">
  <OverflowMenu renderIcon={Filter}>
    <OverflowMenuItem itemText="Filter A" />
    <OverflowMenuItem itemText="Filter B" />
  </OverflowMenu>
</Tooltip>
```
