### ISSUE TITLE
[Feature Request]: Workaround for TileGroup legend styling

### ISSUE THREAD

**Issue by samuel-jessee-ibm** [carbon-design-system/carbon#11376]
In the Code Engine project, we are facing an accessibility issue with the `TileGroup` component because we use our own heading as a legend for the tile group instead of using the component's `legend` prop. The reason we do this is because there does not seem to be an easy way to override the component's legend styling with carbon classes, and our design calls for a more prominent legend than what comes with the component. There also does not seem to be a way to assign our own component as the legend for the tile group to satisfy accessibility requirements. I know there are other components that can take the id of another component to use as a legend; would it be possible to add this option to the `TileGroup` component as well? Thank you!

**Comment by dakahn** [comment]
In Carbon v11 you should be able to override like you'd expect
![image](https://user-images.githubusercontent.com/40970507/167945925-2bab308a-0cb1-414a-afea-0e50ed9200ff.png)

do you find this isn't the case?

**Comment by joshblack** [comment]
Hi there! 👋 Going to close this out due to inactivity. If you're still running into this issue, let us know!
