### ISSUE TITLE
[Bug]: DatePicker Crashes when datePickerType="single"

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#11378]
### Package

@carbon/react

### Browser

Safari

### Package version

1.2.0

### Description

When adding datePickerType="single" to a date picker the component throws and crashes.

Basic example:

```
        <DatePicker
          datePickerType="single"
          size="md"
        >
          <DatePickerInput
            id="date-picker-single"
            labelText="Date Picker label"
            placeholder="mm/dd/yyyy"
            size="md"
          />
        </DatePicker>
```

Error:

```
TypeError: start.addEventListener is not a function. (In 'start.addEventListener('keydown', handleArrowDown)', 'start.addEventListener' is undefined)
(anonymous function) — DatePicker.js:316
```

### CodeSandbox example

CODE SANDBOX IS NOT WORKING WITH CARBON 11

### Steps to reproduce

Crashes on app load. after trying to comment out each part found that datePickerType="single" is the line that will trigger it.

Issue started with Carbon 11 migration.

![re](https://user-images.githubusercontent.com/8028956/167522167-a565b687-5f2c-4dab-b8df-13f3be074b8c.gif)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
Im unable to recreate in either my local testing environment or [CodeSandbox](https://codesandbox.io/s/carbon-v11-x5pmsg)

(CodeSandbox seems to be sporadically working for me right now ymmv)

Could you potentially give me some more context as to how you're using the component, a code example?

**Comment by dabrad26** [comment]
Just including the code snippet from the site causes the error for us.

```
    <DatePicker dateFormat="m/d/Y" datePickerType="simple">
      <DatePickerInput
        id="date-picker-default-id"
        placeholder="mm/dd/yyyy"
        labelText="Date picker label"
        type="text"
      />
    </DatePicker>
```

If I take out datePickerType it works fine. As soon as that is added we get the error.  The GIF above is just a page with the above code snippet in render().

**Comment by dakahn** [comment]
Gotcha, yeah.That code snippet causes no error for me in either my local testing area or on CodeSandbox (when i can get it to load 😓). Could you provide some more information about how your app is using Carbon v11 so we can try and recreate? 

Does it mostly follow this example:
https://codesandbox.io/s/carbon-v11-x5pmsg?file=/src/index.js

**Comment by dabrad26** [comment]
Pretty straight forward I think.  We had no issue with this with React 18 and Carbon 10.  Carbon 11 migration introduced this.

Current related packages:

```
    "@carbon/charts": "0.58.0-latest-carbon-v11-beta.0",
    "@carbon/charts-react": "^0.57.0",
    "@carbon/pictograms-react": "^11.26.2",
    "@carbon/react": "^1.2.0",
    "core-js": "^3.22.2",
    "react": "^18.1.0",
    "react-app-polyfill": "^3.0.0",
    "react-dom": "^18.1.0",
    "react-router-dom": "^5.3.1",
    "react-scripts": "^5.0.1",
    "typescript": "^4.6.3"
```

Overall every component except DatePicker and Tabs works fine.  But those two are throwing different errors on load.

**Comment by tay1orjones** [comment]
@dabrad26 Sorry again about the codesandbox issues. If it helps for reproductions, the vite example we have in the repo [works well on stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx).

I made [a specific one](https://stackblitz.com/edit/github-4nannp?file=src%2FApp.jsx) configured to use the snippet from the website and react v18.

**Comment by tay1orjones** [comment]
@dabrad26 looking at your GIF - `start` is a `ref.current`, and the `addEventListener` call is behind a conditional

https://github.com/carbon-design-system/carbon/blob/c62220c5c03d4056b50ed5558abb6a929ebc2419/packages/react/src/components/DatePicker/next/DatePicker.js#L386-L387

Could you share the value of `start` from your environment and/or what might cause the check to be truthy, then fail the `addEventListener` call?

**Comment by dabrad26** [comment]
Thanks for the Vite thing.  With that I debugged more.  The issue seems to be the component does not like being wrapped and returned...


For example for our TypeScript usage (to load our own types so we can migrate to Carbon 11 without official types from) we use:

```
export class DatePickerInput extends React.Component<DatePickerInputProps> {
  render(): React.ReactNode {
    return <CarbonComponents.DatePickerInput {...this.props} />;
  }
}
```


This is done for every Carbon component we use.

If I just use `export const DatePicker = CarbonComponents.DatePicker;` it works fine... So not sure why it is unhappy in the render wrapping.  

Since it seems to be an issue with our usage I will close the issue. But not sure why this is happening as passing components through a wrapped component should work.

**Comment by tay1orjones** [comment]
After looking into this more, I think I've got a fix. Reopening
