### ISSUE TITLE
[a11y]: TableToolbarSearch - aria labels are not applied to the proper HTML element

### ISSUE THREAD

**Issue by samuel-jessee-ibm** [carbon-design-system/carbon#11374]
Hello. We are getting an accessibility error from Carbon in the Code Engine project. The component causing the error is `TableToolbarSearch`.

When multiple instances of the component are present at once, we get the accessibility error `Multiple elements with "search" role do not have unique labels`, but when I try to add an `ariaLabel` prop to the component, the aria label is applied to the underlying `input` with the `searchbox` role, rather than the `div` with the `search` role that is causing the error.

I have included a screenshot that shows the error and HTML in Chrome. In the HTML you can see the `div` that is causing the error highlighted first, followed by the `input`, highlighted second. The `input` has the aria label `This is my aria label!`, which is what I passed to the `TableToolbarSearch` component via the `ariaLabel` prop.

We are on `"carbon-components-react": "7.54.2"`. Thank you.

I also started a slack thread in the carbon-components channel, if there are questions: https://ibm-cloudplatform.slack.com/archives/C046Y0YUD/p1651669205467109.

![Screen Shot 2022-05-03 at 4 21 04 PM](https://user-images.githubusercontent.com/52468942/167468694-e9901692-c005-40c9-a361-684994ff947a.png)
!

**Comment by dakahn** [comment]
Providing something unique to the `labelText` prop of the search should solve your problem if I'm not mistaken. I think the first search underneath should probably be inert/aria-hidden for screen reader accessibility anyway

**Comment by dakahn** [comment]
going to close this as resolved, but I'm happy to reopen if there's something ive got wrong/missed 🏄🏾

**Comment by samuel-jessee-ibm** [comment]
@dakahn I will try the aria-hidden workaround when I get a chance. Thank you!

**Comment by samuel-jessee-ibm** [comment]
@dakahn I have had a chance to try your `aria-hidden` suggestion, which not only doesn't fix the original AVT error, but creates additional ones as well.

I know that adding `labelText` would fix the error, but this would also require a change in our design. Adding visible labels for the search boxes would be redundant because the purpose of each search box is implicit; a label is only needed for screen readers. If I'm not mistaken, the `ariaLabel` prop is intended to be a workaround for scenarios like these, in which case adding aria labels should address the AVT error without changing the design. Since adding the `ariaLabel` prop does not fix the AVT error, it would seem that the prop is not working as intended/expected for the component. When I directly edit the HTML in Chrome and add the aria-labels myself, the error is fixed, but they do not seem to be added properly by the component's own `ariaLabel` prop.

**Comment by samuel-jessee-ibm** [comment]
This issue is resolved now. I figured out the fix on our end with help from the slack thread.
