### ISSUE TITLE
Add migration examples based on feedback

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#11371]
We've received some questions/feedback around moving to v11 and it would be helpful to have examples in the monorepo to demonstrate how teams can approach some of the following topics:

https://github.com/carbon-design-system/carbon/issues/11371#tasklist-block-23842a59-2f61-4c13-9276-a1469cc5c701

- [ ] ~Using the compatibility theme to use both v10 and v11 tokens~ Defer for now, not seeing a big need for this one

**Comment by sstrubberg** [comment]
from an adopter on Slack 👉 A codesandbox that shows v11 with custom a theme, including component tokens would be great. We are in the process of migration an app to v11 that has a custom theme and was a bit difficult for me to figure out. I'm not sure I have done it in the simplest way either tbh.

**Comment by tay1orjones** [comment]
@sstrubberg Just that type of example was recently delivered in https://github.com/carbon-design-system/carbon/pull/12244 🎉

**Comment by andreancardona** [comment]
🌮 🔥 🎉
