### ISSUE TITLE
text-input--toggle-password-visibility is missing light version & codepen

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1137]
Hi @emyarod ! Went to start adding this to the new website and realized we need the light version defined in the handlebar template and config in order to display both versions on the website.

**Comment by emyarod** [comment]
hi @alisonjoseph thanks for letting me know, I can take a look at this issue

**Comment by alisonjoseph** [comment]
Thanks! Feel free to reach out with any questions here or on slack.

**Comment by emyarod** [comment]
@alisonjoseph do we want a new section for visibility toggle with light theme like the screenshot below, or do we want it all under the existing visibility toggle section?

![screen shot 2018-09-25 at 8 35 12 am](https://user-images.githubusercontent.com/8265238/46017803-fa81a900-c09d-11e8-8d16-70c36f14252e.png)

**Comment by alisonjoseph** [comment]
Separate section the way you have it is perfect. When I add to the website it will be one section with a radio button toggle underneath Text Input http://www.carbondesignsystem.com/components/text-input/code

Although thinking outloud now, I wonder if it makes sense to just have one example in the same block as Text input instead of an entirely new section/block. So underneath disabled we would just show the example with the password visibility toggle? 

*we also need to make sure all the ID/for attributes are unique since they will be sitting on the same website page.

**Comment by emyarod** [comment]
While password input is probably not different enough from text input to have its own page like other input types like `<Checkbox>` or `<RadioButton>`, I think that the password input with visibility toggle is different enough to warrant its own section like textarea. What do you think?

**Comment by alisonjoseph** [comment]
works for me 👍

**Comment by emyarod** [comment]
great! then if I understood the original issue correctly, #1145 should add the missing examples
