### ISSUE TITLE
[Question]: How to show more items in dropdown?

### ISSUE THREAD

**Issue by pmweeks98** [carbon-design-system/carbon#11382]
### Question for Carbon

How to increase the number of items shown in dropdown menu? Cant see any props that control the amount of items shown

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by abbeyhrt** [comment]
Hey @pmweeks98 Just to clarify, are you wanting to change the default amount of items that are shown when you open the Dropdown?

**Comment by pmweeks98** [comment]
Yes

**Comment by dakahn** [comment]
This isn't a prop we offer because to my knowledge this isn't something Downshift allows you to customize.

**Comment by pmweeks98** [comment]
Will raise an issue with downshift so
