### ISSUE TITLE
[Bug]: Carbon modal component's content is hidden/truncated on zooming to 400%

### ISSUE THREAD

**Issue by jagadeeshg5** [carbon-design-system/carbon#11383]
### Package

carbon-components

### Browser

Chrome, Firefox

### Package version

10.35.0

### Description

As per the IBM accessibility core considerations, content can be zoomed up to 400 % without horizontal scroll bars appearing.
When the modal component is zoomed, it is working fine until 250%. After it crosses 250%, the content inside the modal (except buttons and header label) has become hidden/unreadable as shown below. 

https://angular.carbondesignsystem.com/?path=/story/components-modal--basic

Without zoom : 
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/75171749/167637214-3f3a1886-80b4-4115-bbb8-41d82761d8de.png">

With zoom to 300% or above : 
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/75171749/167636985-4a20d3e4-6971-41fa-8c13-9488892291fc.png">

### CodeSandbox example

Issue can be reproduced directly from https://angular.carbondesignsystem.com/?path=/story/components-modal--basic

### Steps to reproduce

1. Go to https://angular.carbondesignsystem.com/?path=/story/components-modal--basic from any browser
2. Click on Open Modal button
3. Zoom to 400 %
Note : In the website, make sure Canvas is in focus instead of sidebar (Attached image in the description)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @jagadeeshg5! It looks like this component is for Carbon Angular and this repository is for the React implementation fo Carbon. To get this issue addressed, I would go and make this issue over in https://github.com/IBM/carbon-components-angular 🙂

**Comment by dakahn** [comment]
closing as resolved--we can reopen if theres something we missed, friend 👍🏾
