### ISSUE TITLE
[Question]: Guidance on best practise for implementing a wizard

### ISSUE THREAD

**Issue by timothydilbert** [carbon-design-system/carbon#11380]
### Question for Carbon

I am developing multiple micro-services, all of which are web forms in a wizard format (i.e. next, back, etc.). I am looking for advice based on what IBM does for your various wizards built using carbon.

How does IBM develop your wizards? Are you just using `TabPanels` with no `TabList`? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
This guidance over at Carbon for IBM Products for using WalkMe sounds like what you're looking for 
https://pages.github.ibm.com/cdai-design/pal/walkme-guide/main/overview/

If this doesn't match your use case let me know and we can reopen 🏄🏾

**Comment by timothydilbert** [comment]
Hi Dakahn,

That link looks to be protected and only accessible by IBMers. Is there any documentation/guidance available for public consumption?
