### ISSUE TITLE
[Question]: Guidance on how to use the `Tearsheet` component

### ISSUE THREAD

**Issue by timothydilbert** [carbon-design-system/carbon#11381]
### Question for Carbon

Is there any documentation on how to utilise the `Tearsheet` component that the public can reference?

Trying to figure out how to make a multi-step form using the `Tearsheet` component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Tearsheet is a component maintained by _Carbon for IBM Products_ and not part of this repository.

You can find documentation on their storybook [here](https://carbon-for-ibm-products.netlify.app/?path=%2Fdocs%2Fibm-products-components-tearsheet-tearsheet--tearsheet)
