### ISSUE TITLE
Migrate dev tutorial sketch file to v11

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#11387]
Duplicate and migrate the Dev tutorial [Sketch file](https://github.com/carbon-design-system/carbon-tutorial/blob/v11-react-step-2/design.sketch) to v11.

**Comment by jnm2377** [comment]
rel: https://github.com/carbon-design-system/carbon-website/issues/2950

just want to clarify that that the tutorial website images also need to be updated - they are screenshots of the sketch file but they show v10 tokens, etc.

**Comment by aagonzales** [comment]
I've updated the Sketch asset but it has not been added to the tutorial repo yet. 
File can be found here: https://ibm.box.com/s/3ekwlqwr6rh0vdk9f9ia02m3hjm03k2k

**Comment by aagonzales** [comment]
PR for the image update here: https://github.com/carbon-design-system/carbon-website/pull/2957

**Comment by aagonzales** [comment]
Closing because design part is finished. File still has not be updated/added to the tutorial repo yet though.
