### ISSUE TITLE
[Bug]: Combobox menu not open on clear with 'x'

### ISSUE THREAD

**Issue by pmweeks98** [carbon-design-system/carbon#11397]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

7.4.1

### React version

17.0.2

### Description

When combobox has a selected item and the 'x' is used the combobox dropdown is not opened. The dropdown should be open with no filtering applied to it (input is null)

### CodeSandbox example

https://codesandbox.io/s/ibm-carbon-combobox-issue-forked-nloh9b?file=/src/index.js

### Steps to reproduce

Sandbox shamelessly copied from another issue

1. Select an item for either of the two comboboxes
2. Click the 'x' on the combobox

Combobox is focused but the dropdown is not opened. This is different to when using `Ctrl + a` and deleting the text manually

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aledavila** [comment]
Hi @pmweeks98 could you explain a bit further. Do you mean that the combo box should stay open when clearing the input with the X ?

**Comment by pmweeks98** [comment]
Hey,
yeah I believe that pressing the X should either keep the combo box open or open it if it is not already open

**Comment by pmweeks98** [comment]
@aledavila created a pr with how I think the combo box should act

**Comment by aledavila** [comment]
@pmweeks98 sorry for the late reply thank you for the contribution. We will take a look at the PR !

**Comment by aledavila** [comment]
@pmweeks98 Hi again. After speaking with the designers this is not something we want to add into the component library. The intended functionality is simply to clear the input on click. Checking examples in the real word or other system's it does not look like they have this suggested behavior. Thanks again.

cc: @aagonzales
