### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jccorralesIBM** [carbon-design-system/carbon#11408]
### Package

@carbon/grid

### Package version

11.1.0

### React version

16.14.0

### Description

I am currently experiencing difficulties trying to update carbon/Grid from version 10.43.0 to version 11.1.0. When I install the new version and update the package calls from @import to @use, the columns and row class extensions stop working, and replacing the bx prefixes with cds prefixes didn't work.
I'm unsure if additional changes are required, the documentation provided in
https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md
and
https://github.com/carbon-design-system/carbon/blob/main/packages/grid/docs/sass.md
Don't explain too much.

The error message>
"
SassError: The target selector was not found.
Use "@extend .bx--col-lg-4 !optional" to avoid this error.
  ╷
6 │     @extend .bx--col-lg-4;
  │     ^^^^^^^^^^^^^^^^^^^^^
  ╵
(filepath and name).scss 6:5  root stylesheet

"

If these class names were deprecated, what are their new equivalents?

Unfortunately, the CodeSandbox example is unable to properly replicate the issue. It should be showing a compilation error similar to:
"
SassError: The target selector was not found.
Use "@extend .bx--col-lg-4 !optional" to avoid this error.
  ╷
11 │     @extend .bx--col-lg-4;
  │     ^^^^^^^^^^^^^^^^^^^^^
  ╵
  (...)styles.scss 6:5  root stylesheet
"

### CodeSandbox example

https://codesandbox.io/s/vigilant-edison-gxz9y6?file=/package.json:349-350

### Steps to reproduce

1. Have a project that uses @carbon/grid in the version 10.43.0
2.  In the .scss file of a component, create custom classes by extending existing carbon classes, focusing on Column or row classes.
3. Test the project.
4. Upgrade the version to 11.1.0 and update the @import to @use in the .scss files
5. Run the project, it should show an error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aledavila** [comment]
Hi there in v11 we now have 2 grids. Our v10 grid has now become flexbox grid and we now have a new css grid as well. you can continue using the previous grid heres and explanation on how to migrate that. It also contains are full migration guide as well. Let me know if that is helpful

https://carbondesignsystem.com/migrating/guide/develop#step-7:-enable-flexbox-grid

**Comment by jccorralesIBM** [comment]
Good morning,

I see now.
I was able to get it to work, I had to put this in the use and import area of the .scss file:
`@use '~@carbon/grid';
@include grid.flex-grid();`

And replace the row, column and grid classNames that previously used the prefix "bx--" to now use "cds--" instead.
With this, the bug was solved.
