### ISSUE TITLE
[Bug]: DatePicker not populating correct date value

### ISSUE THREAD

**Issue by Divya123Spec** [carbon-design-system/carbon#11414]
### Package

carbon-components-react

### Browser

Safari, Firefox

### Package version

 "carbon-components-react": "^7.47.2"

### Description

Hi Team, Date component is
for Chrome browser able to selected the different date so , it's working fine , whereas in Firefox browser whatever date we are selecting in date, it's not populating same value ,it's populating different date value , also facing issue with Safari browser.

### Reproduction/example

https://codesandbox.io/s/broken-smoke-f7yu5v?file=/src/index.js:0-587

### Steps to reproduce

In Safari or Firefox open date picker component and select date after selecting one date it is selecting some other date this is issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
couldn't reproduce on latest firefox on my machine @Divya123Spec can you confirm your version number and operating system?

**Comment by aledavila** [comment]
For context this is what we are seeing on our end and are unable to reproduce. 

https://user-images.githubusercontent.com/12533409/168374454-b0576658-ee5a-4b2d-a73a-4692e569d983.mov

**Comment by Divya123Spec** [comment]
Hi,
operating system is Chrome,OS

**Comment by dakahn** [comment]
Ok, since we can't reproduce we need more information from you to move forward. Can you provide some code or better yet a working example of your implementation, for reference [here's our React Storybook](https://react.carbondesignsystem.com/?path=%2Fstory%2Fcomponents-datepicker--single-with-calendar) working as expected

also what version number of your browser--are you using latest?

**Comment by Divya123Spec** [comment]
I will update my example with code

**Comment by dakahn** [comment]
still unable to repro. going to close as a false report. i can reopen if there's something we're missing. 
![image](https://user-images.githubusercontent.com/40970507/178335844-133e7b1a-39a0-46a7-a8de-e0cdd925f15e.png)
