### ISSUE TITLE
Move the assistive text in the Progress indicator component

### ISSUE THREAD

**Issue by peredwall** [carbon-design-system/carbon#11422]
## Summary
According to WCAG 2.1 Success Criterion 2.5.3 Label in Name, best practice is to have the visual text of the label at the start of the name. But with the Progress indicator component, the hidden text is before the visual text.

## Relevant information
According to WCAG 2.1 Success Criterion 2.5.3 Label in Name, best practice is to have the visual text of the label at the start of the name. But with the Progress indicator component, the hidden text (Complete/Current/Incomplete) is before the visual text, making it more difficult for example users with voice control to navigate in the interface. One easy and good solution would be to move the hidden text to after the visual text in the HTML code.

**Comment by peredwall** [comment]
Hi @dakahn,
That's exactly what we are referring to. Do you think this is something that will be updated in the next version?

**Comment by dakahn** [comment]
It reads, just not _optimally_. Relatively low severity to other accessibility issues we have triaged, but it's in the backlog. Keep an eye here for more updates 👍🏾
