### ISSUE TITLE
[Bug]: Pagination produces inconsistent border

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#11425]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.35.0

### React version

16.14.0

### Description

Very similar to https://github.com/carbon-design-system/carbon/issues/11424 .

This is reproducible in https://carbondesignsystem.com/components/pagination/code/ .

Reproducible in Chrome on Windows.
Not reproducible in Firefox on Windows.

<img alt="pagination line" src="https://user-images.githubusercontent.com/4472725/168782194-41b46a4a-de62-4f18-8d29-026ec6b08ff5.PNG">

The dropdown feels disconnected on hover due to the line. It is not consistent between different browsers.

### Reproduction/example

https://carbondesignsystem.com/components/pagination/code/

### Steps to reproduce

Go to https://carbondesignsystem.com/components/pagination/code/ with Chrome on Windows.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
Thanks for reporting--confirmed on Chromium latest on PopOS

**Comment by tw15egan** [comment]
Thanks for confirming @jsehull 👍
