### ISSUE TITLE
[Bug]: Table produces inconsistent line thickness

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#11424]
### Package

carbon-components-react

### Browser

Chrome, Edge

### Package version

7.35.0

### React version

16.14.0

### Description

This is reproducible in https://react.carbondesignsystem.com/?path=/story/components-datatable-dynamic--example .

Reproducible in Chrome and Edge on Windows.
Not reproducible on Firefox on Windows. Tested this a few months ago on Safari (Mac), and it was also not reproducible.

<img width="262" alt="carbon" src="https://user-images.githubusercontent.com/4472725/168773764-0e72c2fe-6220-4709-aef3-4741dc4ce6ce.PNG">

The issue is very noticeable on tables with more rows than in the official example. And it is sporadic, sometimes the lines are all the same, sometimes not.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datatable-dynamic--example

### Steps to reproduce

Go to https://react.carbondesignsystem.com/?path=/story/components-datatable-dynamic--example with on Chrome (Windows)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
Im unable to see this on Chrome on Linux--this is potentially a Windows issue, but need to confirm
![image](https://user-images.githubusercontent.com/40970507/168833490-09088afc-f4f3-4e73-8e77-044ea52310e1.png)

**Comment by joshblack** [comment]
bump @dakahn when you get a sec to confirm on windows!

**Comment by jnm2377** [comment]
I tested on Parallels using Windows 10, I checked both Edge and Chrome, but I am also not seeing the issue. I checked in both our v10 and v11 storybooks (though nothing changed in that component). Here are some screenshots. I'm going to close this since we can't recreate. If other devs can recreate the issue, we can open it back up. 
<img width="1706" alt="Screen Shot 2022-06-23 at 2 15 24 PM" src="https://user-images.githubusercontent.com/32556167/175379742-21337509-832c-46d9-8ef3-4bfc42e31fd5.png">
<img width="1706" alt="Screen Shot 2022-06-23 at 2 12 48 PM" src="https://user-images.githubusercontent.com/32556167/175379754-d709823f-52c5-474e-9c25-30ab05a5622d.png">

**Comment by fabpico** [comment]
@jnm2377 I would like to let reopen since the problem persists. I assume the test was based on Mac machine with virtualized Windows 10. Can anybody from the Carbon project test it on a real windows machine?

On IBM's storybook, the same component results in different line rendering:

Canvas view: https://react.carbondesignsystem.com/?path=/story/components-datatable-dynamic--example
![table-canvas](https://user-images.githubusercontent.com/4472725/184657045-0212a9bd-721c-49c7-ae7e-c5401bde1fab.JPG)

Docs view: https://react.carbondesignsystem.com/?path=/docs/components-datatable-dynamic--example
![table-docs](https://user-images.githubusercontent.com/4472725/184657162-c510cb78-3f38-45df-ac29-d532c0dfac58.JPG)

On my storybook, the same component also results in different line rendering. On more rows, the same row line thickness issue happens. But **also the head** shows inconsistent borders.

![multiple-different](https://user-images.githubusercontent.com/4472725/184657563-d3c0dd0d-de03-4222-a259-82f3e779e77c.JPG)

**Comment by jsehull** [comment]
I found this reference from #11425

As requested above, I tested on Windows specifically (with Chrome, Edge, and Firefox) and did NOT find any of the previous errors.

Now that we are on v11 @carbon/react@1.25.0, it seems like the issue has been resolved somewhere along the development path.
