### ISSUE TITLE
[Feature Request]: user removal

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon#11441]
### Summary

I am no longer with IBM, please remove me from all carbon and related repositories, thank you in advance

### Justification

I did quit and really, was the best thing to do. Suggest you to follow me. But first please remove me from the repos. 

### Desired UX and success metrics

None

### Required functionality

Remove this user

### Specific timeline issues / requests

Now? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @kyjak! 👋  What repos/projects/teams were you previously involved in and would like to be removed from?

**Comment by kyjak** [comment]
Carbon and carbon for ibm are what i know of

**Comment by tay1orjones** [comment]
@kyjak From what I can see, you're not a member of the organization or any subsequent teams. 

We're unable to do anything like erase contribution history on GitHub, if that's what you're after. Here's some links on the topic of account details/visibility:

- https://github.community/t/remove-history-from-profile/138363
- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/viewing-contributions-on-your-profile
- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/publicizing-or-hiding-your-private-contributions-on-your-profile

Cheers to your next adventure after IBM 🍻
