### ISSUE TITLE
[a11y]: table header sort description is incorrect if table header child is an element instead of text

### ISSUE THREAD

**Issue by hlyang397** [carbon-design-system/carbon#11455]
### Package

carbon-components-react

### Browser

Firefox

### Operating System

MacOS

### Package version

v10.57.1

### React version

v16.8.6

### Automated testing tool and ruleset

No

### Description

When you set a pure text header in <TableHeader>, the sortDescription is correct like 
"Click to sort rows by [object Object] header in descending order"
However, if you use an element (ex:<div>) as header, the sortDescription becomes something like 
"Click to sort rows by [object Object] header in descending order"

I feel we should get the text from header children before setting it as translation parameter.
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/TableHeader.js

### Reproduction/example

https://stackblitz.com/edit/github-dsrmky?file=src%2FApp.jsx

### Steps to reproduce

In a <DataTable>, set the custom <TableHeader>, and use an element (not a pure text) as the header children.
Check the sort description, the message is incorrect.

ps. please let me know if the sort description is not for the accessibility.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
> I feel we should get the text from header children before setting it as translation parameter.

Not quite sure I understand the suggestion here. Could you elaborate?

**Comment by hlyang397** [comment]
> > I feel we should get the text from header children before setting it as translation parameter.
> 
> Not quite sure I understand the suggestion here. Could you elaborate?

In translateWithId(), the `header` is embedded in the message directly.
If `header` is a string, it would be fine.
If `header` is an object (ex, JSX element), `[object Object]` will be embedded in that message, which is not expected.
I recommend to get text content of `header` and embed the text content into message (instead of embedding `header` object directly)
https://github.com/carbon-design-system/carbon/blob/2a42de420115756fde93cba786292e9bc5f23b6b/packages/react/src/components/DataTable/TableHeader.js#L23

Hope I answer your question.

**Comment by hlyang397** [comment]
@dakahn Any comment on this issue ?

**Comment by jnm2377** [comment]
Hey @hlyang397 the `TableHeader` component accepts a prop `translateWithId` which takes a function returning a string for the description. You can set a custom description using this prop for a reasons such as this. Here's an example of what that would look like:
<img width="564" alt="Screen Shot 2022-06-23 at 2 56 09 PM" src="https://user-images.githubusercontent.com/32556167/175386499-dce377d9-29f9-40ef-86b9-96dafe147855.png">
