### ISSUE TITLE
Carbon v11 mini-series: logistics

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#11462]
- [ ]  Get a list of front-end devs to be notified of the sessions.
- [ ] ~Send out invites.~ Decided on prerecorded sessions, share out strategy is TBD
- [x] https://github.com/carbon-design-system/carbon/issues/11810
- [x] https://github.com/carbon-design-system/carbon/issues/11809

**Comment by jnm2377** [comment]
- [ ] decide on medium for talks: live or pre-recorded curriculum
    - [ ] if live, decide on dates
    - [ ] if pre-recorded, decide how to split up work among devs
- [ ] write up marketing plan
