### ISSUE TITLE
[Bug]: ParserError in  index.scss 

### ISSUE THREAD

**Issue by alainrobert** [carbon-design-system/carbon#11476]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.3.0

### React version

16.10

### Description

Building a using a scss including @use 'carbon/react'  project fails 

# yarn build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
https://github.com/carbon-design-system/carbon-tutorial/tree/v11-react-step-2Failed to compile.

./src/index.scss
ParserError: Syntax Error at line: 1, column 31

### Reproduction/example

 https://github.com/carbon-design-system/carbon-tutorial/tree/v11-react-step-2

### Steps to reproduce

git clone -b v11-react-step-2  https://github.com/carbon-design-system/carbon-tutorial.git
cd carbon-tutorial
yarn install
yarn build

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there! 👋 Going to close this out as I believe it's being addressed over in Slack. Feel free to comment if that's not the case and I can re-open!

**Comment by alainrobert** [comment]
I need a solution to the problem, discussion on slack have not provided answer I would like to keep this open until resolution. 
 Distribution of the application is blocked because the build does not work.,

**Comment by alainrobert** [comment]
@joshblack Please reopen, I am stuck with the application that does not build. I have made changes for V11 and don't want to revert them to go back to v10.
I have tested with 11.4 recently released with the same result.

**Comment by alainrobert** [comment]
the problem was due to v11 requiring react-scripts  v5.0.0  (newer node.js installation)
