### ISSUE TITLE
[Bug]: "icon only danger button" is throwing an error to the console 

### ISSUE THREAD

**Issue by caltrevizam** [carbon-design-system/carbon#11484]
### Package

@carbon/react

### Browser

Edge

### Package version

1.1.0

### React version

17.0.2

### Description

Hi,

Rendering a button with `hasIconOnly` and `kind="danger"` attributes set throws an error to the console

```
Warning: Failed prop type: Invalid prop `kind` of value `danger` supplied to `ForwardRef(IconButton)`, expected one of ["primary","secondary","ghost","tertiary"].
        at IconButton (@carbon\react\lib\components\IconButton\index.js:26:21)
        at Button (@carbon\react\lib\components\Button\Button.js:32:17)
...
```

### Reproduction/example

https://stackblitz.com/edit/carbon-button-issue?file=src%2FApp.jsx

### Steps to reproduce

Just render a button adding `hasIconOnly` and `kind="danger"` attributes

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aledavila** [comment]
Closing as we do not support danger for icon only button.

**Comment by kkckkc** [comment]
If danger is no longer supported for icon only buttons, then I suggest you update https://react.carbondesignsystem.com/?path=/docs/components-button--icon-button

It says

> Icon-only Buttons
Icon buttons allow users to take actions, and make choices, with a single tap. Icon buttons can take the form of any of the seven types (Primary, Secondary, Tertiary, *Danger, Danger tertiary, Danger ghost and Ghost*) but most commonly will be styled as primary or ghost buttons.
