### ISSUE TITLE
Add prebuilt CSS to `@carbon/styles`

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#11489]
It would be helpful if the `@carbon/styles` package had a `css` folder with prebuilt styles. Specifically:

- `styles/css/styles.css`
- `styles/css/styles.min.css` (minified)

This ticket is to introduce another step to the build task in `@carbon/styles` to generate a bundle from the root `index.scss` file.

**Comment by theiliad** [comment]
+1
