### ISSUE TITLE
Use RTL for testing in all UI Shell components

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11558]
Full list is in https://github.com/carbon-design-system/carbon/issues/10184, update checklist once complete

**Checklist**

- [x] Content
- [x] Header
- [x] HeaderContainer
- [x] HeaderGlobalAction
- [x] HeaderGlobalBar
- [x] HeaderMenu
- [x] HeaderMenuButton
- [x] HeaderMenuItem
- [x] HeaderName
- [x] HeaderNavigation
- [x] Link
- [x] SideNav
- [x] SideNavDetails
- [x] SideNavFooter
- [x] SideNavHeader
- [x] SideNavIcon
- [x] SideNavItem
- [x] SideNavItems
- [x] SideNavLink
- [x] SideNavLinkText
- [x] SideNavMenu
- [x] SideNavMenuItem
- [x] SideNavSwitcher
- [x] SkipToContent

**Comment by joshblack** [comment]
These components currently do not have tests and do not need to be updated (but should have tests added in a future task)

- [ ] HeaderPanel
- [ ] HeaderSideNavItems
- [ ] SideNavDivider
- [ ] Switcher
- [ ] SwitcherDivider
- [ ] SwitcherItem
