### ISSUE TITLE
[Bug]: `copyText` property for CodeSnippet component is not recognized by React

### ISSUE THREAD

**Issue by keithcha** [carbon-design-system/carbon#11555]
### Package

carbon-components, carbon-components-react, @carbon/colors, @carbon/icons, @carbon/icons-react, @carbon/themes

### Browser

Chrome

### Package version

v10.56.0

### React version

v17.0.2

### Description

I see the following error from my project's Jest test and the browser console:

`Warning: React does not recognize the `copyText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `copytext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div
          at CodeSnippet (/root/ibm/samwise/node_modules/carbon-components-react/lib/components/CodeSnippet/CodeSnippet.js:70:24)`
          
The `CodeSnippet` component seems to work though, so this bug is to address the console.error output (at least for now).

### Reproduction/example

https://codesandbox.io/s/flamboyant-joliot-qfluz6?file=/src/index.tsx

### Steps to reproduce

Just use the `CodeSnippet` component.  It appears the `copyText` property is not understood.  I couldn't get the CodeSandbox to reproduce it exactly, but the errors I get point to a similar issue - React doesn't understand the properties that should be there according to the docs - https://react.carbondesignsystem.com/?path=/story/components-codesnippet--multiline

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @keithcha Thanks for making the issue! Were you able to recreate this warning in a sandbox? 

I am not able to see the warning you are talking about in the sandbox link you provided or on our storybook so unfortunately, there's not a way for us to resolve it if we can't reproduce it.

**Comment by keithcha** [comment]
> Hey @keithcha Thanks for making the issue! Were you able to recreate this warning in a sandbox?
> 
> I am not able to see the warning you are talking about in the sandbox link you provided or on our storybook so unfortunately, there's not a way for us to resolve it if we can't reproduce it.

I can't reproduce it either.  I'll close this so it's at least searchable if someone else runs in the same issue
