### ISSUE TITLE
Maintenance: Upgrade WebPack

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1155]
### Summary

This issue is for tracking a maintenance effort to upgrade to WebPack4.

### Justification

For continuous effort for us to maintain our toolstack up-to-date.

### Desired UX and success metrics

Ensuring our code work with the latest toolstack.

### "Must have" functionality

WebPack4 and code changes associated with that.

**Comment by vividh** [comment]
I'd like to take this on. I recently upgraded from webpack v1 to v4 for one of my projects, so probably upgrading from v3 should be relatively easier.

**Comment by asudoh** [comment]
Sounds good, thanks @vividh! - Let us know if you need any help!
