### ISSUE TITLE
[Data table] Add option to render Overflow visible by default

### ISSUE THREAD

**Issue by youda97** [carbon-design-system/carbon#1156]
## Detailed description

> Describe in detail the issue you're having.

The Overflow menu icon is only focused when it is open and not actually visible (`opacity: 1`), so In repos that support navigation through arrow keys, the menu item will disappear.

> Is this issue related to a specific component?

Data Table

> What did you expect to happen? What happened instead? What would you like to see changed?

There seems to be a `"bx--overflow-menu--open"` class being applied when the menu is open but no styling exists for it. Maybe this issue can be fixed by applying the necessary styles here.

**Comment by asudoh** [comment]
@IBM/carbon-designers Currently the overflow menu trigger button in data table is shown only for hover/focus states. Do you think it'll make sense to show it always while the menu is open? Thanks!

**Comment by asfordmatt** [comment]
We've had feedback from several users that they completely miss the overflow menus in the table. We've decided to override the styling to make them always visible, it would be really good if that was the Carbon default behaviour.

**Comment by asudoh** [comment]
Refs: https://github.com/IBM/carbon-components/pull/1528#pullrequestreview-184755382 https://github.com/IBM/carbon-components/pull/1642#issuecomment-454872274

**Comment by shixiedesign** [comment]
Keeping overflow menu visible all the time is one of the options we have thought about! See below. (Please note that if there are more than 3 icon buttons, they should fold into the overflow menu, so we don't have row full of icons.) 

We will work on making them visible by default an option in our data table soon. But @youda97 if you can contribute this styling via a PR, you can get this feature in our core library sooner! We would really appreciate it! 

![image](https://user-images.githubusercontent.com/15144993/57558367-10995c80-7343-11e9-9b50-7c2be8c8f126.png)

### :book: Guideline to add

Overflow menus on data table are hidden by default to adhere to a more modern web experience, were only minimum amount of interactions are displayed, and contextual information are revealed on further interactions. This to some extend compromises accessibility of keyboard users, so Carbon offers the option to keep overflow menu buttons visible by default. Keep in mind turning this on could complicate data presentation and reduce general usibility.

**Comment by emyarod** [comment]
before we merge https://github.com/carbon-design-system/carbon/pull/2782, is there any reason why

```css
.bx--data-table td.bx--table-column-menu .bx--overflow-menu .bx--overflow-menu__icon {
  opacity: 1;
}
```

doesn't work here? am I misunderstanding this issue?
