### ISSUE TITLE
[Bug]: Data table CodeSandbox takes very long to transpile

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#11578]
### Package

carbon-components-react

### Package version

You know

### Description

In https://carbondesignsystem.com/components/data-table/code by clicking on the [CodeSandbox link](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPgyQAAQxp-AIwoB6eRhEbJTAL53ZEcmwAexBMhA1GDSwB1yAAQBECoopPy0AQBKQhYBYPyqAQDk5rTJANz-QSFhEQHAAYJOMPwBNvGJKilpSqqZ2cGh4ZHJBCaOLgRwGHBwDYFNeZGFACISaAAqaIaw0gHTszAAwnRojqXzi3MLM7AAEkIsW3swUaQA7idLh2hs_NewAEKkLACejyswUFDllUnJPQGYzkMyxdJZQa5FoFAIACyOpXGtDQ80SF2RaD-CQB7TgaFCsExA0aXikAQAgigUAEALwBAAUAEo6QA-RmNAA8mO2MCKlzgtOA6MxFQRd1KguA4vuotZjWADMK6Lg8xlkvm-Fot3uAAVEihVQEtbz9aRDeUWbT2QzGkFObzVox1uRSgFaBBaLBab4QDzTr75YMgvbeQUCBGTaczYbmTYgyHEwEHacdQmk4mU0tzhd0xnE9LEfw4AQVGgUAyGer-FabXb85neTq3cAIwQtc3-DG4Er4UXLfH6w2C9WCNWbEPh5yTE2i3nh0ymRPg_np7yc_PMzPU0dNyGs89Xm89wWVaXy5X0bWOSuGwezpcAlgYG8heiCBAWIPb8PhZcCBg3xQCWZYVgygE_Neto_sOyaOkBT4vkKEFQB-X6ssAKEEAAbmgUAAK4wDYa6nMsQEnvmi7LrB9rbtmlwUUEVGTrRvIvO8e4kUs85cbAToohs_Dpku_jTv63GNEykKNMU9wMpyVI0iYrLzMoGD4SoPjtjAtAAKKwJpjBPG8ACSLAMqkpCkOki6QiANgOCUrhwrQKhQMwXj0Iw6iciwEDYcELA-nIVm0IG05-dhrL2Y5XQ9H0Hl0D46g6PhcB8oC-hGKYaSZDFID4oSMCYm4iXeN5ogwM4wwBGSkQihMdIBAA2gq9afogKRoMk0j1uQBIwJ1yQADKkHcARPHhaDcG6ADMPX1igiS0KQNBQEN-yTJMuoLSuwydbNAAMx29Su_D4bAQ3nPhTj8oYji7YmEgohgCIsAA-rgiT4YaQ0ANIwNhjiAJgEcABAAagAsgEADi32Go9IZSBIaVDaMED4ksLCIw5bUrh1KSGIjQT9ZpQ2jeNk3iDNZQAIzEwES3WatpDrSkm3bQz-0BAALDzs2nYm52XSk123Yk93kAzz2YG9n3w3AQ2Q2g-GCAwoMQ9DcOkD9_SC0jKK0KjKQAMoohEji4Dj-vAO1LBDRgDOk4NKQUywE1TTTAQAExc8tLNs8kHM7frQTcwAHIdodFBdLvJKMAByJsBGwsC4BIEAUNLtAvXLX0679KQUk4ggXBrUOwwrDPI0bitFxY_kwNbeOJgTyTY9Hzvk2N7tU9NgFlAAbH7zNrRtW0h4tLQHcdUf1sLcdi-7EsPdHMuvTAH357rSsGBg5da1X0c18b8cY6cHeNLjgy2_j9spE3ncDd3lOewPvMjytY_sxPXPT7z_No4LyujrcWpBJbZ1zpveWBc67JEht8A-ldYHV0NqfM2BgPTkCtvra-QRb6t3vskMATtn6ux7h7am78ACsn8A7j05tHCOc8zqxzRknFO3wYDpw9FnNeOdZbQO3oXZI5xyBEDQEg7WutUEozgRSBu2FH5X1OgAXWkq6aqMI6p9glPwTETVWo33rM-N4Q1nYM2rENBOA1m7GJXKYoaTMv6s0sUWIaZoXFQDsfgkxL4nEtDcXojxgTcE2z8WYmoscgn3CutEsJLcQyOK6gIjeW8j71isUXVJb1kEyISfYxMyTkgnz1pk9xps0FlMGNfdR_h7J2CAA), the preview takes very long to transpile (sensed 5-10min+), even with removed SCSS import (which is known to be slow).  
This hinders me on creating a CodeSandbox example to show another potential bug.

### Reproduction/example

[Link to codesandbox](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPgyQAAQxp-AIwoB6eRhEbJTAL53ZEcmwAexBMhA1GDSwB1yAAQBECoopPy0AQBKQhYBYPyqAQDk5rTJANz-QSFhEQHAAYJOMPwBNvGJKilpSqqZ2cGh4ZHJBCaOLgRwGHBwDYFNeZGFACISaAAqaIaw0gHTszAAwnRojqXzi3MLM7AAEkIsW3swUaQA7idLh2hs_NewAEKkLACejyswUFDllUnJPQGYzkMyxdJZQa5FoFAIACyOpXGtDQ80SF2RaD-CQB7TgaFCsExA0aXikAQAgigUAEALwBAAUAEo6QA-RmNAA8mO2MCKlzgtOA6MxFQRd1KguA4vuotZjWADMK6Lg8xlkvm-Fot3uAAVEihVQEtbz9aRDeUWbT2QzGkFObzVox1uRSgFaBBaLBab4QDzTr75YMgvbeQUCBGTaczYbmTYgyHEwEHacdQmk4mU0tzhd0xnE9LEfw4AQVGgUAyGer-FabXb85neTq3cAIwQtc3-DG4Er4UXLfH6w2C9WCNWbEPh5yTE2i3nh0ymRPg_np7yc_PMzPU0dNyGs89Xm89wWVaXy5X0bWOSuGwezpcAlgYG8heiCBAWIPb8PhZcCBg3xQCWZYVgygE_Neto_sOyaOkBT4vkKEFQB-X6ssAKEEAAbmgUAAK4wDYa6nMsQEnvmi7LrB9rbtmlwUUEVGTrRvIvO8e4kUs85cbAToohs_Dpku_jTv63GNEykKNMU9wMpyVI0iYrLzMoGD4SoPjtjAtAAKKwJpjBPG8ACSLAMqkpCkOki6QiANgOCUrhwrQKhQMwXj0Iw6iciwEDYcELA-nIVm0IG05-dhrL2Y5XQ9H0Hl0D46g6PhcB8oC-hGKYaSZDFID4oSMCYm4iXeN5ogwM4wwBGSkQihMdIBAA2gq9afogKRoMk0j1uQBIwJ1yQADKkHcARPHhaDcG6ADMPX1igiS0KQNBQEN-yTJMuoLSuwydbNAAMx29Su_D4bAQ3nPhTj8oYji7YmEgohgCIsAA-rgiT4YaQ0ANIwNhjiAJgEcABAAagAsgEADi32Go9IZSBIaVDaMED4ksLCIw5bUrh1KSGIjQT9ZpQ2jeNk3iDNZQAIzEwES3WatpDrSkm3bQz-0BAALDzs2nYm52XSk123Yk93kAzz2YG9n3w3AQ2Q2g-GCAwoMQ9DcOkD9_SC0jKK0KjKQAMoohEji4Dj-vAO1LBDRgDOk4NKQUywE1TTTAQAExc8tLNs8kHM7frQTcwAHIdodFBdLvJKMAByJsBGwsC4BIEAUNLtAvXLX0679KQUk4ggXBrUOwwrDPI0bitFxY_kwNbeOJgTyTY9Hzvk2N7tU9NgFlAAbH7zNrRtW0h4tLQHcdUf1sLcdi-7EsPdHMuvTAH357rSsGBg5da1X0c18b8cY6cHeNLjgy2_j9spE3ncDd3lOewPvMjytY_sxPXPT7z_No4LyujrcWpBJbZ1zpveWBc67JEht8A-ldYHV0NqfM2BgPTkCtvra-QRb6t3vskMATtn6ux7h7am78ACsn8A7j05tHCOc8zqxzRknFO3wYDpw9FnNeOdZbQO3oXZI5xyBEDQEg7WutUEozgRSBu2FH5X1OgAXWkq6aqMI6p9glPwTETVWo33rM-N4Q1nYM2rENBOA1m7GJXKYoaTMv6s0sUWIaZoXFQDsfgkxL4nEtDcXojxgTcE2z8WYmoscgn3CutEsJLcQyOK6gIjeW8j71isUXVJb1kEyISfYxMyTkgnz1pk9xps0FlMGNfdR_h7J2CAA)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hey @fabpico, yes this is a frustrating one. Sorry you're running into it. We've seen the slow compile times as well as some other issues with codesandbox. We've engaged the codesandbox team on this and other issues in hopes we can improve the performance, https://github.com/codesandbox/codesandbox-client/issues/6684

If this persists, we can look at updating all the links on the website to be Stackblitz instead of codesandbox.

In the meantime, we've found that using Stackblitz is significantly faster. We've got [a template you can try out](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx). Let me know what you think!

**Comment by fabpico** [comment]
@tay1orjones today CodeSandbox it took only ~17 seconds. Stackblitz took ~22 seconds.
So if CodeSandbox can keep this stable then it is ok. I didn't use Stackblitz until now, but I think the more stable and more easy-to-use provider should be used.

**Comment by tay1orjones** [comment]
@fabpico I think we've found a way to make things more performant in codesandbox:

- https://github.com/carbon-design-system/carbon/pull/11611
- https://github.com/carbon-design-system/carbon-website/pull/2986
