### ISSUE TITLE
[Bug]: Need to update styles to work with custom HTML elements

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon#11579]
### Package

@carbon/styles, carbon-components

### Browser

Chrome, Safari, Firefox, Edge

### Package version

@carbon/styles - v1.4.0, carbon-components - 10.56.0

### React version

v17

### Description

This issue can also be considered as a feature request/suggestion. I'm currently working on [carbon-components-angular](https://github.com/IBM/carbon-components-angular) to add support for carbon v11. The table wrapper class `.bx--data-table-content` & `cds--data-table-content` don't have `display: block` properties. This results in horizontal scrolling not working, normally we would bind the class to the custom element created (In this case `<ibm-table></ibm-table>`). But in this case, we ALSO have to explicitly go in & set the style for display to block.

The downside of this is that we have to maintain this style and make changes to it if newer versions of @carbon/style effect the component. This can possible cause version mismatch issues for some of the consuming teams.  There are other approaches that we can take to address this, but pollutes the DOM with unnecessary elements.

**There are other components as well where we had to explicitly set the style for the component.**

If you think this is something that we can address, I can contribute to this issue.

### Reproduction/example

https://angular.carbondesignsystem.com/?path=/story/components-table--with-dynamic-content

### Steps to reproduce

1. Go to the angular storybook
2. Click the `Add columns` button 25 - 30x. 
3. Observe the horizontal scrolling.
4. Inspect element & find `<ibm-table>` element (There should only be 1)
5. Add following class `bx--data-table-content` to the element (May need to Edit as HTML in some browsers)
6. Notice that this doesn't fix horizontal scrolling
7. Add `display: block` style to class `bx--data-table-content` after selecting `<ibm-table>`  with `.bx--data-table-content` class

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aledavila** [comment]
Hey @Akshat55 this is the Carbon React repo. We don't maintain Angular however heres the link to the angular repo. https://github.com/IBM/carbon-components-angular to open up an issue. Thanks!
