### ISSUE TITLE
Support TypeScript in our Storybook to set a baseline for types

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#11587]
This issue is connected to our TypeScript Working Group. As part of this group, we would like to support TypeScript in the React storybook of the project in order to establish a baseline for types. The storybook itself was chosen due to its coverage of usage scenarios for the components in the system which would be helpful for making sure types are correct.

**Checklist**

- [ ] Update Storybook to support compiling stories with TSX
- [ ] Bring in initial set of types and verify TS can be run against the storybook stories

**Comment by mbarrer** [comment]
The initial set of types would be coming from https://www.npmjs.com/package/@types/carbon-components-react. I anticipate after the second task is done we should be in a pretty broken state. However at this point it should be easier to divide and conquer the typings

**Comment by nagermen** [comment]
@mbarrer is there any updates on typings? Or any workaround advices?

**Comment by brian316** [comment]
any update on roadmap to get TS types? How can we contribute effectively to that end?

**Comment by tay1orjones** [comment]
> How can we contribute effectively to that end?

@brian316 Once #12222 is in we'll organize an effort to update each component to have type definitions added. Keep an eye on #10752, it contains the most up to date info on the typescript effort. I'll try to make note of it here as well though.
