### ISSUE TITLE
[Bug]: Tabs component - maximum update depth exceeded

### ISSUE THREAD

**Issue by mateBe95** [carbon-design-system/carbon#11591]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

v10.54.0 / v7.54.0

### React version

v16.12.0

### Description

When resize too fast view which contains Tabs component the UI is crashing. Probably goes into infinity loop in ComponentDidUpdate as below:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/23103157/173053896-9b4b1402-6eff-42eb-b379-cbf1eaf56112.png">

### Reproduction/example

https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx

### Steps to reproduce

1. Load view which has Tabs component.
2. Try to resize fast the view

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @mateBe95! 👋 I'm unable to reproduce this issue on our v10 storybook, could you share a link to a codesandbox or stackblitz with steps to reproduce?

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity. Feel free to comment and we can re-open this issue 👍
