### ISSUE TITLE
[Bug]: Composed Modal onClose not working correctly

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#11590]
### Package

@carbon/react

### Package version

v1.5.0

### Description

The ComposedModal `onClose` prop isn't firing as intended. Modal isn't closing. The current work around is adding the `closeModal` prop to the `ModalHeader` 

Link to workaround: 
https://stackblitz.com/edit/github-rju2gt-zqwkzk?file=src/MyModal.jsx

### Reproduction/example

https://stackblitz.com/edit/github-rju2gt?file=src%2FApp.jsx

### Steps to reproduce

Add `onClose` to `ComposedModal` doesn't fire or even console.log anything.

Add `closeModal` to `ModalHeader` and the Modal does close. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by keenanpayne** [comment]
I was also having difficulty getting the close icon (x) to close modals with `<ComposedModal>`. 

I worked around this by adding the following code to my `<ModalHeader>`:

```jsx
<ModalHeader 
  // ...
  buttonOnClick={() => close()}
/>
```

I found this prop after finding `ModalHeader` exported from [ComposedModal.js](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ComposedModal/ComposedModal.js#L331). 

It would be great if there was more thorough documentation specific for `<ModalHeader>`. I've cloned the repo and will take a stab at writing some basic documentation to help flesh out how this can be configured.
