### ISSUE TITLE
[Bug]: breadcrumb overflow displayed incorrectly

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#11616]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

 v11.5.0

### Description

The [Breadcrumb overflow](https://react.carbondesignsystem.com/?path=/story/components-breadcrumb--breadcrumb-with-overflow-menu) variant is displaying the overflow ellipsis incorrectly.
  - It is currently showing a vertical overflow menu icon, but the overflow should be horizontal and it should also be in text format, not an icon.
  - Also I think we should be showing the truncation after the first breadcrumb and have two breadcrumbs following after it like we do in our images and content.
<img width="758" alt="Screen Shot 2022-06-14 at 3 14 13 PM" src="https://user-images.githubusercontent.com/43969356/173670327-24029d39-3670-4ec4-92f8-9b1d48658f1d.png">

### Screenshots

<img width="555" alt="Screen Shot 2022-06-14 at 2 26 48 PM" src="https://user-images.githubusercontent.com/43969356/173670157-ff5efd8b-3709-49d9-a034-18ee23d1068c.png">

### Steps to reproduce

- Go to the [Breadcrumb storybook with Overflow menu](https://react.carbondesignsystem.com/?path=/story/components-breadcrumb--breadcrumb-with-overflow-menu)
- Notice the vertical icon for truncation and that it appears after two breadcrumbs and before two breadcrumbs.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Doesn't show up when testing locally 🤔 

<img width="814" alt="Screen Shot 2022-06-16 at 9 55 09 AM" src="https://user-images.githubusercontent.com/11928039/174085894-fa00b9a1-6dea-4bd6-8aaa-86888c48a7b9.png">

**Comment by abbeyhrt** [comment]
I'm not sure what is going on in our storybook but thankfully this works in a sandbox on the latest release so it seems like just an issue with storybook, not the actual component.  https://stackblitz.com/edit/github-hhgymi?file=src/App.jsx

I'm going to downgrade the severity a bit since it seems like a docs issue
