### ISSUE TITLE
[Bug]: File Uploader is not working on React 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#11626]
### Package

@carbon/react

### Browser

Safari

### Package version

V11 

### React version

v1.5.0

### Description

File Uploader Drop Container is not working when uploading files

![image](https://user-images.githubusercontent.com/77697351/174137463-1da413dc-0955-4c49-bf0e-6a283b353432.png)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-fileuploader--file-uploader-drop-container

### Steps to reproduce

1. Go to the File Uploader Drop Container 
2. Upload a file or drag and drop it to the container 
3. Nothing shows up 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @thyhmdo We should maybe consider removing this story, it just isn't fully configured to have the files show up. It is more a visual of what the Drag and Drop container looks like. The full working example is that "Drag and Drop Upload Container Example Application" story
