### ISSUE TITLE
Datatable size doesn't work if row contains button

### ISSUE THREAD

**Issue by Ankita-Jaiswal** [carbon-design-system/carbon#11633]
DataTable size = sm,xs, compact, does not work if the table contains buttons, tags, etc.

first image, datatable contains buttons, tags, so only header of the table changed (size="sm")
![image](https://user-images.githubusercontent.com/16722905/173555645-34649097-3bfa-421c-9b59-d8e0dd7c0ee0.png)

Now when i remove columns which contain buttons , tags. Size works

![image](https://user-images.githubusercontent.com/16722905/173555932-3e427f2e-ccff-4048-b14e-45da027d7cba.png)

**Comment by joshblack** [comment]
Hey @Ankita-Jaiswal! 👋 Thanks so much for taking the time to make this issue and include screenshots. That's definitely odd to see happen, I'm not sure why. Could you share a stackblitz or codesandbox with an example of the layout issues you're seeing? I can help to debug from there!

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity. Feel free to comment or update the original post with the steps to reproduce and we can re-open this issue 👍
