### ISSUE TITLE
[Bug]: DatePicker appendTo prop blocks arrow key keyboard input

### ISSUE THREAD

**Issue by clouria** [carbon-design-system/carbon#11640]
### Package

carbon-components-react

### Package version

8.5.0

### Description

When the `appendTo` prop is set on the `DatePicker` component, the arrow keys do not work.

### Reproduction/example

https://codesandbox.io/s/carbon-components-react-forked-2now8x?file=/src/index.js

### Steps to reproduce

Load up the code sandbox https://codesandbox.io/s/carbon-components-react-forked-2now8x?file=/src/index.js. Use the arrow keys to navigate through the Radio buttons. When you press the Enter key, the DatePicker component will appear. Notice that the arrow keys no longer work to navigate the Radio buttons.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by clouria** [comment]
@tay1orjones Thank you for looking into this but I am not sure I explained the error well enough so I will try again. [Here is an updated sandbox](https://codesandbox.io/s/clever-flower-o1xcsp?file=/src/App.js) where I have two examples of the issue I'm running into. 

To start from the beginning. You can use the left and right arrow keys to select a Radio Button in the group. You can also use left and right arrow keys to move the cursor when you are focused on the Input. Now rendering the DatePicker by clicking the show DatePicker button, now that it is rendered, you are unable to do either of these items with the arrow keys. This is an accessibility issue because if I can only use the keyboard, I am unable to select a different Radio Button or move the cursor in the input. BUT this is only the functionality when the `appendTo` prop is set. If you remove it from the DatePicker in the sandbox, notice how you get all of the keyboard functionality back. 


In the new sandbox I removed the keydown event handler to show that it wasn't an issue and you don't need to use tab at all in this example going off of your comment about the default tabindex behavior. You can click on everything to ensure focus is correct.  I believe when the `appendTo` prop is set, the default action is being suppressed (ex. event.preventDefault()) which is prevent the arrow keys from having any functionality besides inside of the DatePicker itself.  

I don't believe that this is the intended functionality of appendTo. I know that in this scenario I wouldn't use the appendTo prop but in other scenarios where I would, the arrow key functionality is the same.

**Comment by tay1orjones** [comment]
@clouria Thanks for providing more detailed information! Looking at it again, I think this is happening because you're appending the DatePicker directly to `document.body`. If it is [appended to a different, empty element](https://codesandbox.io/s/elastic-booth-u71jjx?file=/src/App.js), keyboard navigation works as expected. 

Would this work for you? If not, could you share why it needs to be appended to `document.body` specifically?

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity. Feel free to respond based on what @tay1orjones responded with above and we can re-open this issue 👍

**Comment by clouria** [comment]
No need to open back up. His comment worked. The documentation on a appendTo was confusing to me at first and I wasn't aware that it worked that way. Thanks for the explanation.
