### ISSUE TITLE
Experimental component feedback - links

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1165]
@tomlroach
Links visited state. 

http://www.carbondesignsystem.com/experimental/link/code
Visited links can provide a good visual history for a user for where in a website they have been. For web applications, having a visited state for links is less common and I question whether it's the right choice for Carbon. For a web application users visit and interact with regularly they can expect the majority of links to eventually become visited thus providing no useful history. Is it the right choice to have a visited state? When should/shouldn't it be used? Is it appropriate for a breadcrumb when often the purpose of that component is to indicate I've already visited the previous pages?

**Comment by alisonjoseph** [comment]
@jeanservaas @aagonzales thoughts on this? In a product UI I could see where most of the  links/breadcrumbs would end up being purple/visited and not providing any information.

**Comment by aagonzales** [comment]
Yeah this is a good point. Especially with the purple color. I would like to get a little more validation or see what some other systems do for this.

**Comment by jeanservaas** [comment]
Talked to @tw15egan and he also made a good case against the purple here. For now, he's going to map visited to Brand-01 and this is another thing that we can circle back to when we deal with our color tokens.

**Comment by tw15egan** [comment]
Fixed in https://github.com/IBM/carbon-components/pull/1261

**Comment by aagonzales** [comment]
We need a "circle back to" board 😆
