### ISSUE TITLE
[Bug]:  Impossible to create height of Filterable Select

### ISSUE THREAD

**Issue by WojciechMichalowski** [carbon-design-system/carbon#11658]
### Package

@carbon/react

### Package version

currect

### React version

v17.02

### Description

![Zrzut ekranu 2022-06-22 o 09 59 51](https://user-images.githubusercontent.com/102224763/174976550-e6c50107-7552-4bed-8c0e-c830481e3199.png)
height is equal 180px -> should be possible to change it

### Reproduction/example

https://carbon.sage.com/?path=/docs/select-filterable--default-story

### Steps to reproduce

just look on carbon storybook into devtools and avaiable props

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @WojciechMichalowski - the screenshot and link you provided are for a different project named Carbon, https://github.com/Sage/carbon. Hope this helps!

**Comment by WojciechMichalowski** [comment]
@tay1orjones this ss is from carbon :)

**Comment by WojciechMichalowski** [comment]
https://carbon.sage.com/?path=/docs/select-filterable--default-story#new-designs-validation

**Comment by WojciechMichalowski** [comment]
@tay1orjones och I understand -> you are right sorry :)
