### ISSUE TITLE
[Bug]: Using appendTo with DatePicker causes carriage returns to not work in sibling textarea

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#11672]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.57.1

### React version

16.14.0

### Description

Some time ago, I reported an issue that when the calendar popup was open, it didn't scroll with the input field.  https://github.com/carbon-design-system/carbon/issues/4158.  The appendTo prop had been broken, and when it was fixed, I set it to the immediate child of the scroll element per the suggestion given for https://github.com/carbon-design-system/carbon/issues/4818.

At some point later, we realized that the TextArea that was in the same "appendTo" as the DatePicker was getting it's carriage returns swallowed by flatpickr.  Flatpickr had a PR that at first looked like it might fix it https://github.com/flatpickr/flatpickr/issues/2054 but it has since been merged and it doesn't help.

I started to write a defect against Flatpickr but found that I couldn't reproduce the scrolling issue when there's no appendTo, and it doesn't have the carriage return issue when the appendTo is set to a child of the scroll container.

Note that my teammate wrote a similar issue here.  https://github.com/carbon-design-system/carbon/issues/11640 However, I think this is a more straight-forward use case.  

### Reproduction/example

https://9qiwkg.csb.app/

### Steps to reproduce

Put your cursor in the text area field and hit Enter.  The cursor does not move to the next line.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi @kglickman! 👋 Thanks for taking the time to make this issue with a super helpful codesandbox 🙏 Could you share more about your use-case for appending to an element in this way? If I remember right, `appendTo` is generally meant to be an empty element that flatpickr can sit in and isn't intended to have other children elements.

Let me know if I'm misunderstanding anything!

**Comment by tw15egan** [comment]
Awesome! Going to close this as resolved, but let me know if there are any other questions you have
