### ISSUE TITLE
Improve styles docs based on feedback

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#11671]
After the Charts v11 release, we wanted to collect feedback from Iliad around his experience using `@carbon/styles` and how we could better document that library.

**Checklist**

- [x] Schedule meeting for sync
- [ ] Translate notes from meeting into documentation

**Comment by theiliad** [comment]
> @theiliad Correct, Sass modules don't tree shake - any module `@use`d will be included exactly once in the compiled CSS output, no matter how many times those styles are loaded.
> 
> You can opt to instead `@use` subsections of a module to bring in only certain pieces if you prefer, like `@use "@carbon/styles/scss/components/tooltip/";`

Yes, this seems like a disadvantage as I think the carbon styles CSS bundle adds up to some ~600kb
