### ISSUE TITLE
[Bug]: UI Shell menu button became squashed on `sm` breakpoint

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11687]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.6.0

### React version

1.6.0

### Description

Menu button became squashed at `sm` breakpoint (320px). Expecting the menu button to stay square: 

<img width="427" alt="image" src="https://user-images.githubusercontent.com/15144993/175978963-74822a62-2f70-4f08-b255-43de0141cdcb.png">

### Reproduction/example

https://react.carbondesignsystem.com/iframe.html?args=&id=components-ui-shell--side-nav-rail-w-header&viewMode=story

### Steps to reproduce

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by asamaiya00** [comment]
Hi @shixiedesign, is this issue still open? 
May I work on this?

**Comment by tw15egan** [comment]
@asamaiya00 we would love a PR to fix this, thanks!

**Comment by asamaiya00** [comment]
Sure @tw15egan, you can assign it to me. I'll work on this.
