### ISSUE TITLE
Further define acceptance criteria for moving components to `stable`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11688]
ContextMenu has been unstable for quite some time. We need to:
 
- [ ] Revisit what steps/criteria are required to move a component from unstable to stable. 
   - [ ] Storybook stories need playground, controls, etc.
- [ ] Document the unstable -> stable process in repo
- [ ] Validate the process by going through it with a currently unstable component:
  - [x] #11770

**Comment by tay1orjones** [comment]
I made [this codesandbox example](https://codesandbox.io/s/smoosh-flower-o3oftk?file=/src/App.js) if it's helpful in your efforts.

**Comment by joshblack** [comment]
**Draft**

Moving a component to stable

- [ ] All components exported in `src/index.js` and should not be `unstable_` prefixed
- [ ] All components have a test written using RTL
- [ ] All components are documented in storybook
