### ISSUE TITLE
[Bug]: Tertiary and ghost button styles "white on white" when disabled

### ISSUE THREAD

**Issue by ChrisSchneider** [carbon-design-system/carbon#11684]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.2.0

### Description

Tertiary and ghost button styles are "white on white" for disabled buttons

Or do we always need a black background for g100 Theme & have to set the background manually?

### Reproduction/example

https://stackblitz.com/edit/github-6qxskd?file=src%2FApp.jsx

### Steps to reproduce

```
      <Theme theme="g100">
        <Button kind="primary" disabled>
          Hello world
        </Button>
        <Button kind="secondary" disabled>
          Hello world
        </Button>
        <Button kind="tertiary" disabled>
          Hello world
        </Button>
        <Button kind="ghost" disabled>
          Hello world
        </Button>
      </Theme>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi @ChrisSchneider! That's an incredibly fair assumption for this component (that the background and text colors should be set). We'll see what we can do to make this the behavior by default. In the interim, the expectation would be to set the background and text color explicitly for the zone.
