### ISSUE TITLE
[Bug]: When Page size is changed to 20 or more and move from page 1 to 2 in the pagination. the scroll bar is not going to the top of the table.

### ISSUE THREAD

**Issue by PritiGaikwad2** [carbon-design-system/carbon#11683]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.52.0

### React version

17.0.2

### Description

After moving from page1 to page 2 user suddenly sees the scroll bar is going to bottom of the page because page focus is not moved to the top of the tables.

### Reproduction/example

https://codesandbox.io/s/green-currying-m6tq9o?file=/src/App.js

### Steps to reproduce

1. Create a datatable with 25 or more data list.
2. Change page size to 20.
3. Scroll to the bottom of the list and move from page 1 to page 2. 
4. After moving from page1 to page 2 user suddenly sees the scroll bar is going to bottom of the page because page focus is not moved to the top of the tables.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi @PritiGaikwad2! 👋 I think for this use case you might need to use the `onChange` handler to see when the page changes and implement the scroll logic that you're expecting.

I'm not sure if this is behavior that can be baked into the component as there are different expectations (like scrolling into view versus staying in the same area) but I hope this workaround can help you implement something that meets your needs.

Let me know if you have any questions!
