### ISSUE TITLE
Add "Component Builder" to website

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11703]
A 'component builder' was demoed at the most recent IDL playback, it would be a great thing to add  to the website as a resource!

Design Checklist:

- [x] Determine appropriate naming, "component builder" may not be the most correct description.
- [x] Write blurb outlining what it is, how it can be used, etc
- [x] Add links via resource cards

Dev Checklist:
- [ ] Assist in implementing the above on the website

**Comment by mjabbink** [comment]
descriptions — corrected “allow” to “allows” also added `layout modules` for maybe some additional clarity—one option with it and one without it. 

FYI @jeanservaas



A.
Carbon UI Builder is a visual builder tool that allows users to build product pages and layout modules using Carbon Components in a fraction of the time it usually takes.

B.
Carbon UI Builder is a visual builder tool that allows users to build layouts using Carbon Components in a fraction of the time it normally takes.

C.
Carbon UI Builder is a visual builder tool that allows users to build layouts using Carbon Components in a fraction of the time it normally takes.
