### ISSUE TITLE
[Bug]: Spacing issue between icon and text on disabled invalid inline multiselect 

### ISSUE THREAD

**Issue by ccwilson-us-ibm-com** [carbon-design-system/carbon#11726]
### Package

@carbon/react, @carbon/styles

### Browser

Chrome, Firefox

### Package version

1.6.0

### React version

^17.0.0

### Description

When setting a multiselect component with the properties inline, disabled and invalid, the label text overlaps with the red invalid icon.

### Reproduction/example

https://stackblitz.com/edit/github-dtyxsd?file=src/App.jsx

### Steps to reproduce

Here's how the component is configure to display this issue: 
```
<MultiSelect
        ariaLabel="MultiSelect"
        id="carbon-multiselect-example"
        items={items}
        label="Multiselect menu options"
        titleText="Multiselect title"
        type="inline"
        disabled="true"
        invalid="true"
 />
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @ccwilson-us-ibm-com! 👋 

I believe that `invalid` and `disabled` at the same time is not currently an intended state for the component. Could you share more about the use-case for having the control be `invalid` and `disabled` at the same time?

**Comment by ccwilson-us-ibm-com** [comment]
Hi.  I am part of the team developing carbon components for salesforce.  And while implementing our multiselect component, I've just been testing as many property value combinations as I can.  If disabled and invalid is not an intended state, so it doesn't matter how it renders, then that could satisfy my testing.  I'll discuss this with the rest of my team.

Just one additional question:  Is there a priority among mutually exclusive properties like `disabled` and `invalid`? If `disabled` is true, should the value of `invalid` be ignored (or treated as false)?
