### ISSUE TITLE
[Question]: Does Progress Step support tooltips in Carbon v11? If so, is there any example code?

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon#11720]
### Question for Carbon

Hello, how can I add a tooltip to a [progress indicator step](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ProgressIndicator/ProgressIndicator.js) in Carbon V11? Is this supported? I see overflowTooltipProps & tooltipId proptypes for progress step, but I'm not sure what kind of object it accepts.

Also in [@carbon/styles](https://github.com/carbon-design-system/carbon/blob/8c24a2b10b0a97bef8d15e2764bd15b5b9ab9c77/packages/styles/scss/components/progress-indicator/_progress-indicator.scss#L151) the visibility is set to hidden for `.#{$prefix}--tooltip`. That isn't the case for `.#{$prefix}--tooltip_multi` which I don't see any reference to it in code.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by Akshat55** [comment]
Is there a way I can add a tooltip to a progress indicator step or is that not a pattern supported by carbon?

**Comment by dakahn** [comment]
That pattern is unsupported. That said, you could potentially [open a feature request](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&template=FEATURE_REQUEST_OR_ENHANCEMENT.yaml&title=%5BFeature+Request%5D%3A+l) and see if there's support for the idea as an enhancement though. 🏄🏾

**Comment by Akshat55** [comment]
Thanks. Just FYI, [CarbonDesignSystem](https://carbondesignsystem.com/components/progress-indicator/usage/) has examples with `tooltip` which should be removed or updated.

![image](https://user-images.githubusercontent.com/38994122/178542399-b06b6486-b9f0-4233-b991-c633b2faffa4.png)
