### ISSUE TITLE
Use RTL for testing in `OverflowMenu/next/OverflowMenu-test.js`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11731]

**Comment by tay1orjones** [comment]
@abbeyhrt is this one in `next` covered by https://github.com/carbon-design-system/carbon/pull/11867?

**Comment by abbeyhrt** [comment]
@tay1orjones No, there aren't any tests in `OverflowMenu/next` so I guess we can close this one?
