### ISSUE TITLE
Export token metadata from `@carbon/themes`

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#11748]
**Background**

There are several use-cases for publishing metadata for themes and tokens, including:

- Generating pages on the website instead of manually authoring sections
- Authoring tools (like stylelint plugins) to help with usage

At the moment, token metadata is internal to the `@carbon/themes` package. It would be helpful to make this metadata available in the package itself (potentially first under `unstable`) to be used for these use-cases.

If possible, it would be helpful for tools to also access v10 token information as a part of these changes.

**Checklist**

- [ ] Export token metadata as a part of `@carbon/themes`
- [ ] Include component tokens in the output
  - [ ] Button
  - [ ] Notification
  - [ ] Tag

**Comment by lee-chase** [comment]
@joshblack scraping the website and inspecting the current tokens listed in @carbon/theme I see the following.

These button colors are not currently exported from @carbon/themes outside of the v10 theme.
```
button-danger-active
button-danger-hover
button-danger-primary
button-danger-secondary
button-disabled
button-primary
button-primary-active
button-primary-hover
button-secondary
button-secondary-active
button-secondary-hover
button-separator
button-tertiary
button-tertiary-active
button-tertiary-hover
```

These colors exported from @carbon/theme are not on the website.
```
linkInverseActive
linkInverseHover
shadow
supportCautionMajor
supportCautionMinor
supportCautionUndefined
```

**Comment by joshblack** [comment]
Hey @lee-chase! Just opened up a draft PR for this at: https://github.com/carbon-design-system/carbon/pull/11767

This PR adds in an `unstable_metadata` export to `@carbon/themes`. It contains token info for v10 and v11, each one is a flat list of tokens with the name and type. Would love your feedback on this draft PR to see if this is what you were expecting and if there would be any changes you would suggest or other capabilities you would like to see shipped as a part of that PR 👍

**Comment by joshblack** [comment]
@lee-chase thanks for that! I really appreciate it.

I think in #11767 we can help out with design tokens specifically, is the format introduced in that PR something that you could work with or is there any changes that you'd recommend?

For some of the other items, in particular Sass stuff like functions/mixins, we may need to hard code these lists as I'm not sure of a good way to get infer these kinds of things automatically

**Comment by lee-chase** [comment]
The format is good. Not sure I have a use for reading v10 tokens from v11, although a mapping would be interesting. I am currently implementing '--fix' for the linter and will in the first instance be putting my own color mapping, v10 to 11 together.

Agree, that functions is harder and in theory, I could read them from SCSS but have opted for a manually curated list as the number is of functions is low.

**Comment by joshblack** [comment]
@lee-chase great point, let me add another group to that PR that has all the contextual tokens
