### ISSUE TITLE
[NumberInput]: new props ltMax and gtMin 

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#11757]
### Summary

I would like to propose two new props for NumberInput...
- `ltMax: true`.. to allow a number up to but not including max
- `gtMin: true`.. to allow a number down to but not including min

### Justification

We have a dialog to allow grouping of data values.
Each groups has a upper and lower range, such that one's group lower is another groups upper.

ie:
GroupValues = Higher, 100, 75, 50, 25, 0, Lower
GroupLabels = "100 and Higher", "75 to < 100", "50 to < 75", "25 to < 50", "0 to < 25", "less than 0"

Each GroupValue is a NumberInput that can be changed (and reflected in the GroupLabel).
Each GroupValue is limited by the GroupValues above and below it.

ie:
The GroupValue 50 can be increased to anything < 75, and decreased to anything > 25.

With integers this is pretty easy, we could write... `<NumberInput max="74" min="26" >`.
For non-integers this is more complicated... `<NumberInput max="74.9999999999999..." min="25.00000000001" >`.

And of course this gets more complicated when the GroupValue are not integers to start out with.

### Desired UX and success metrics

No UX, just a new prop and behaviour change of NumberInput

### Required functionality

The prop will need to contend with integers and non-integer values and prop inputs(min/max values).

A message will need to be displayed when the value is out of range.
Similar to the message already shown for the min/max range.

There is an enhancement for a 'scale' prop... https://github.com/carbon-design-system/carbon/issues/8690
If/when the scale prop is added this will need to take scale into account.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Hey @guigueb, thanks for the feature request. I really like this idea, however, this starts to push NumberInput into non-standard behavior that goes beyond the scope of the core component's base offering. After discussing it in our backlog cleaning meeting, we discovered that this can also currently be done through listening events.
