### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by unidevel** [carbon-design-system/carbon#11755]
### Package

carbon-components, @carbon/type

### Browser

Chrome, Safari, Firefox, Edge

### Package version

10.51.0

### React version

16.14.0

### Description

There are many errors if I enabled the font face in an enterprise env which prevent external access.
![image](https://user-images.githubusercontent.com/1028723/177460394-db6ca93c-666a-4033-8aa0-a7bc78ccc78f.png)

So I set these flags to disable the font import from external sites, that works
```
$chart-feature-flags: (
  enable-font-imports: false
) !default;
$css--font-face: false !default;
```

But it will not generated some font related classes which cause the UI not same when the flags are enabled. 

Is there are way to use local plex fonts instead of from CDN?

### Reproduction/example

NA

### Steps to reproduce

Please reference description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> Is there are way to use local plex fonts instead of from CDN?

@unidevel Yes, there are some docs for this [here](https://github.com/carbon-design-system/carbon/blob/v10/docs/guides/ibm-plex.md). Note that as of [v10.56.0](https://github.com/carbon-design-system/carbon/releases/tag/v10.56.0) Plex is no longer served by Google Fonts due to GDPR concerns and is instead served via an IBM-controlled Akamai CDN.

As of v11, Plex is served locally by default with the option to use the Akamai CDN or another CDN you control. Hope this helps!

**Comment by unidevel** [comment]
Thanks @tay1orjones

**Comment by marco-mengelkoch-ibm** [comment]
We had some similar issue in our system. Our CSP also prevented loading the fonts. Our system was already tested without loading google fonts, so we probably will disable the google fonts for now and re-add them later, probably when switching to the new carbon / plex version.

Just a few questions:
- is the scss code above the recommended way to disable loading external fonts in Carbon 10? It was somehow hard to find some documentation for it.
- for the current / latest carbon version, there is nothing to do, right? So this issue "has been fixed" for Carbon 11+.
