### ISSUE TITLE
Tabs: Remove max-width from Tab

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#11766]
This issue is for simply removing the max-width property from Tab to allow them to flow to 100% the width of their content.

**Comment by tay1orjones** [comment]
Is this resolved by the `automatic` prop addition?

**Comment by tay1orjones** [comment]
@aagonzales should this be an _option_, or should it be that all tabs no longer have a max width and will never truncate?

**Comment by abbeyhrt** [comment]
If it helps @tay1orjones, here's the comment that I made this issue from https://github.com/carbon-design-system/carbon/pull/11765#pullrequestreview-1032027269

**Comment by aagonzales** [comment]
hmm I want to say let's kill max width completely, mostly for the sake of translation etc. Hopefully, designers and content designers are creating tab names with intentions. 

My one hesitation around removing it altogether would be in regards to user or system generate tab names that could become excessively long. I'm not sure how likely this use-case would be, its probably not common. If we remove it, would a team be able to easily place a max-width if this happened to be a recurring problem in their product?

**Comment by tay1orjones** [comment]
Thanks @abbeyhrt!

@aagonzales Yes, if we remove it altogether it could be a significant visual change in apps where they're relying heavily on truncation. It would be very easy for them to add it back in within their own app's stylesheet though.
