### ISSUE TITLE
[Bug]: Progress indicator focus style outline wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11773]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

Latest

### Description

Progress indicator > Interactive variant is showing wrong focus state styling: 
https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive
![Jul-11-2022 19-27-07](https://user-images.githubusercontent.com/15144993/178254452-165c6789-8840-4dff-a62b-2d409f75f124.gif)
Expecting below based on [Style tab spec](https://carbondesignsystem.com/components/progress-indicator/style#interactive-states): 
<img width="234" alt="image" src="https://user-images.githubusercontent.com/15144993/178254636-59d868d0-2a09-4f35-87be-5db4921a72a3.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive

### Steps to reproduce

Go to link, use keyboard to focus the steps.
https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by hannelevaltanen** [comment]
Hi! I would have a fix for this. Could I contribute?
