### ISSUE TITLE
[Bug]: Progress indicator vertical, skeleton text miss aligned 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11784]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.7.0

### Description

Progress indicator, vertical style, when set to skeleton state, the skeleton text is slightly too low next to the dotted circles. Expecting the text to middle align with the circles: 

<img width="119" alt="image" src="https://user-images.githubusercontent.com/15144993/178540731-44f32bdf-6a55-47b8-a670-37bfac00251b.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--skeleton

### Steps to reproduce

Build it locally to check because React storybook currently do not have functional knobs/controls. 
This error is in Angular storybook demo too: https://angular.carbondesignsystem.com/?path=/story/components-progress-indicator--skeleton

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
I think this is due to errant padding on the label. The vertical modifier class on the parent could be used to reconfigure the padding to be removed when configured as vertical.
