### ISSUE TITLE
Tooltip component requires an 'id' property to function correctly

### ISSUE THREAD

**Issue by susancline** [carbon-design-system/carbon#11787]
## Detailed description

> Add two tooltips to a page
Click one open
Click the other one open
Watch the second tooltip content briefly open then close
You need to click on the second tooltip a second time in order for it to stay open
Here is a code sandbox URL that shows this behavior:
https://codesandbox.io/s/heuristic-cloud-fcbgn?file=/src/index.js

> What did you expect to happen? What happened instead? What would you like to see changed?
Here is a codesandbox where the behavior is correct:
https://codesandbox.io/s/wonderful-haze-8tfzl
What I want changed: change the documentation and code to require a unique 'id' on the tooltip
> What browser are you working in?
Chrome

**Comment by abbeyhrt** [comment]
@susancline Tooltip does require an id, I don't think we view this as a bug. Are you running into any complications when providing an id? Unfortunately we can't change the ID to be required as that is a breaking change and would require a major release. The new tooltip in Carbon v11 does not require an id if you would like to try using that component.
