### ISSUE TITLE
[Bug]: onOpen Prop Prematurely Closes Menu

### ISSUE THREAD

**Issue by qbi11y** [carbon-design-system/carbon#11781]
### Package

carbon-components, carbon-components-react

### Package version

carbon-components 10.57.2; carbon-components-react 7.57.2

### React version

16.14.0

### Description

When using Overflow Menu, an issue arises when trying to use onOpen. When clicking the icon on the button the menu fails to open. If you click off the icon the menu opens. I am expecting the menu to open when you click anywhere within the button and the chevron to update. Chevron should update again when the menu is closed. The Overflow Menu works as expected when onClose is called. When we created a test in the sandbox everything seemed to work fine. I was when we ran on localhost that issues presented. It seems the handleClickOutside method is being called when you're still inside. But only for onOpen.
@matthewgallo 

### Reproduction/example

CodeSandbox was unable to reproduce the issue.

### Steps to reproduce

On a localhost install, Introduce logic to swap chevrons based on open or closed. Us the onOpen method to swap the chevron. Clicking the icon the menu should not open, click outside of the icon but inside the button and the menu should open.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
I was able to recreate this issue in this sandbox: https://codesandbox.io/s/unruffled-brattain-ktpzxl?file=/src/index.js
Note: this appears to only be happening when switching icons based on open state

**Comment by qbi11y** [comment]
@jnm2377 that is the same I issue I was having. It should be open but the menu closes. Do you need anything from me to move forward?

**Comment by qbi11y** [comment]
@jnm2377 I have been investigating this issue and have run into something that might be helpful in resolving. I am attaching my notes. Please let me know if you have questions.

Troubleshooting notes

switching to a single chevron down icon, the component works as expected.
adding onClick attr to toggle isOpen, icons toggle, but menu no longer opens. It is at this point that the handleClickOutside method is being called and is closing the menu prematurely.
handleDocumentClick fires as expected, this looks to be the cause of the onClickOutside firing.

This seems strange: this.element.contains && !this.element.contains(ClickListener.getEventTarget(evt))
Shouldn't there be something in the contains to compare it to? Is it just ANY element if nothing is passed?

If onClick is added as a prop then onClickoutside fires, if no onClick, it doesn't fire

Place the breakpoint at lines 59/60 in ClickListener.jss to recreate

**Comment by jnm2377** [comment]
@qbi11y I looked into this, and couldn't recreate in our storybook. It works as expected. I tried messing with the sandbox again and realized it works fine if `react-dom` is updated to a least the `17.0.0` version. https://codesandbox.io/s/overflow-menu-chevron-toggle-wqhd9e?file=/src/index.js`
