### ISSUE TITLE
DataTable: Stop using <div> inside <thead>

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#11794]
### Question for Carbon

The DataTable's header has a `<div>` inside a `<th>`, which is apparently invalid HTML.  It can be seen on https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--default.

```html
<thead>
   <tr>
      <th scope="col">
         <div class="cds--table-header-label">Name</div>
     </th>
...
```

Can/should it be changed to a `<span>`?

It gives us spurious console errors and errors running our unit tests (which is bad because it masks any real errors that might occur):

```
    Warning: validateDOMNesting(...): <div> cannot appear as a child of <thead>.
        in div (created by DatagridHead)
        in thead (created by TableHead)
        in TableHead (created by DatagridHead)
        in DatagridHead (created by Datagrid)
        in table (created by Table)
        in div (created by Table)
        in Table (created by Datagrid)
```

Note: it's the same problem in both Carbon 10 and Carbon 11.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Interesting, where are you seeing this error? I don't think there would be any downsides to changing this to a `span`, but just wanted to verify for myself that it would fix the issue

**Comment by tay1orjones** [comment]
`validateDOMNesting` expects children of `thead` to be one of these per the html spec

https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/client/validateDOMNesting.js#L240-L248

**Comment by wkeese** [comment]
PS: Should also consider the sortable-column case.  It's got a `<div>` in there too although I'm not sure why, since it's display:none.

```html
<th aria-sort="none" scope="col">
   <div id="table-sort-7" style="display: none;">Click to sort rows by Name header in ascending order</div>
   <button type="button" aria-describedby="table-sort-7" class="cds--table-sort">...</button>
</th>
```

**Comment by tay1orjones** [comment]
@wkeese I'm not able to reproduce it with our storybook locally either.

I see in the stack trace of the error that there are some custom components in addition to the ones provided by Carbon, like DatagridHead. Is it possible these are adding divs as direct children to the `thead`?

My understanding of validateDOMNesting and the [html parsing spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable) it's based on would indicate the "content model" (allowed children elements) in a `th` is [any flow content elements](https://html.spec.whatwg.org/multipage/tables.html#the-th-element).

| Structure | Validity |
| - | - |
| `thead > div` | 🚫 invalid |
| `thead > th > div` | 🚫 invalid |
| `thead > tr > div` | 🚫 invalid |
| `thead > tr > th > div` | ✅ valid |
