### ISSUE TITLE
[Bug]: MeterChart generates error in the console

### ISSUE THREAD

**Issue by samantha-kw-chan** [carbon-design-system/carbon#11833]
### Package

carbon-components

### Package version

v11.0

### Description

When using a meter chart on a page, the console produces the following error:

Error: Invalid value for <circle> attribute cy="calc(1em / 2)"

I have to remove the chart from my design, because we have quite a few of these charts on the page.  It produces many errors.

### Reproduction/example

https://carbondesignsystem.com/data-visualization/simple-charts/#meter

### Steps to reproduce

Please open example page.
Inspect
Switch to the console... and you will see the error message.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by falsepopsky** [comment]
I think you should open this issue in the chart repo, also the code comes from here:

[title-meter.ts](https://github.com/carbon-design-system/carbon-charts/blob/923ce40b2d5ef25756af281a5b8d4a81aeccb69e/packages/core/src/components/essentials/title-meter.ts)

**Comment by abbeyhrt** [comment]
@samantha-kw-chan This issue would need to be made over in the charts repo, like mentioned above. You can make an issue [here](https://github.com/carbon-design-system/carbon-charts/issues/new?assignees=&labels=bug+%F0%9F%90%9B&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+) to get this addressed!
