### ISSUE TITLE
[Feature Request]: Add month year picker 

### ISSUE THREAD

**Issue by sathishkumarssk** [carbon-design-system/carbon#11849]
### Summary

Add month year picker for different formats like mm/YYYY, YYYY-mm, etc.

### Justification

Here is the sample view of month year option

![month-year-design](https://user-images.githubusercontent.com/28381202/180473203-b3991ac0-62ab-4b00-96a6-e053690b15e4.png)

### Desired UX and success metrics

It would be helpful for certain reasons where user could be enter or pick the value from the picker 

### Required functionality

Require with various locale supported formats like mm/YYYY, YYYY/mm, YYYY-mm, etc.

### Specific timeline issues / requests

it will be good if this feature released asap.

### Your team

carbon team

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
hey @sathishkumarssk, thanks for submitting an issue for your feature request. Based on how you describe your problem, we think this could be solved by using to separate inputs, one for month and one for the date. This could also be solved by two drop-downs with date fields. For these reasons, we won't be taking on this work-stream at this time. Thank again for the submission!
