### ISSUE TITLE
[Bug]: Custom component button token has errors

### ISSUE THREAD

**Issue by lidongyang-Ethan** [carbon-design-system/carbon#11853]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.8.0

### React version

17.0.2

### Description

As this doc 
https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#components 
I use this code custom button token, but this has errrors. 
```code
@use '@carbon/react/scss/components/button' with (
 $button-primary: #017f75
);
```

errors
```code 
This module was already loaded, so it can't be configured using "with".
  ┌──> node_modules/@carbon/styles/scss/components/button/_index.scss
10│   @forward 'tokens';
  │   ^^^^^^^^^^^^^^^^^ new load
  ╵
  ┌──> node_modules/@carbon/styles/scss/components/button/_mixins.scss
17│   @use 'tokens' as *;
  │   ━━━━━━━━━━━━━━━━━━ original load
  ╵
  ┌──> stdin
1 │ ┌ @use '@carbon/react/scss/components/button' with (
2 │ │   $button-primary: #017f75,
3 │ │ );
  │ └─^ configuration
  ╵
  node_modules/@carbon/styles/scss/components/button/_index.scss 10:1  @forward
  node_modules/@carbon/react/scss/components/button/_index.scss 9:1    @use
  stdin 1:1                                                            root stylesheet
```

### Reproduction/example

https://stackblitz.com/edit/github-bqtelk?file=src/index.scss

### Steps to reproduce

only use 
@use '@carbon/react/scss/components/button' with ($button-primary: #017f75);
has errors. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/11912
