### ISSUE TITLE
Link to React tab component is broken from Tabs' Code page

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon#11857]
## Detailed description

When one presses on the React button on the [Code page of the Tab component](https://carbondesignsystem.com/components/tabs/code)
<img width="621" alt="image" src="https://user-images.githubusercontent.com/14298245/165325683-3f39c434-5c94-4fa6-821c-a74c8c4577b5.png">

it opens the library but errors out on the page

> Couldn't find story matching 'components-tabs--default'.
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/14298245/165325432-c0174e6d-d2a6-4ace-a884-8112880b6de2.png">

**Comment by abbeyhrt** [comment]
@mbgower I'll look into this! While the site is impacted, the solution is going to be in this repo so I transferred the issue here!
