### ISSUE TITLE
Update design kits with new type tokens

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11863]
**Checklist**

- [x] Update layer styles in **v10** kits (Sketch, Figma, XD?)
   - [x] Sketch
      - [x] White theme
      - [x] Gray 10 theme
      - [x] Gray 90 theme
      - [x] Gray 100 theme
   - [x] Figma
      - [x] (v10) Text Styles - IBM Design Language

- [x] Update layer styles in **v11** kits (Sketch, Figma, XD?)
   - [x] Sketch
      - [x] White theme
      - [x] Gray 10 theme
      - [x] Gray 90 theme
      - [x] Gray 100 theme
   - [x] Figma
      - [x] (v11) Text Styles - IBM Design Language
   - [x] XD

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon/11863?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by laurenmrice** [comment]
- Type tokens have been updated in Sketch, Adobe XD, and Figma for v10 and v11. ✅
- I will close once the updates have been pushed after the changes in code get merged. 👍
