### ISSUE TITLE
[Bug]: Tabs component does not support forwarding a ref

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon#11869]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

v1.6.0

### Description

I am using the Tabs component and found that I was unable to pass a ref to this component, maybe this component is not using `forwardRef`. A [temporary work around](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/carbon-v11/packages/cloud-cognitive/src/components/ModifiedTabs/ModifiedTabs.js#L64) I've used is to just wrap my component in another element and pass the ref to that element. I was also not able to pass a custom class to this component either.

Attempts to pass the ref also result in the following console error:
![image](https://user-images.githubusercontent.com/10215203/181286635-8f78ca49-8aa8-4278-ab53-e59619e6f928.png)

### Reproduction/example

https://stackblitz.com/edit/github-n1zkrz?file=src%2FApp.jsx

### Steps to reproduce

Attempt to pass a ref to the `Tabs` component, you will see that the value of the ref is always undefined.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @matthewgallo! The `Tabs` component is just a context provider for its children so if you need to add a ref or a className, you would  put it on one of the sub-components (`TabList`, `Tab`, `TabPanel`, etc)  instead of on `Tabs` to more directly change whatever you are customizing with the className or the ref.

**Comment by matthewgallo** [comment]
Ohh ok I see! Thanks for clarifying @abbeyhrt
