### ISSUE TITLE
[Bug]: aria label is only applied to modal if modelLabel is passed

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/carbon#11868]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

@carbon/react 1.8.0

### React version

17.0.2

### Description

https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Modal/Modal.js#L158

The logic is wrong, it should be `rest['aria-label']` as the remaining props are put into the rest variable, what's happening now is if you do not provide the `modalLabel ` prop then it tries to use `['aria-label']` which will just pass in `aria-label`

### Reproduction/example

n/a

### Steps to reproduce

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for the report @tkolanko! Agree that the bracket notation should be used with `rest` so it uses the `aria-label` key off `rest`.
