### ISSUE TITLE
Update websites with new type tokens

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11862]
Full change list for each version in the [parent issue](https://github.com/carbon-design-system/carbon/issues/11813)

**Checklist**

- [x] v10 carbon website
  - https://v10.carbondesignsystem.com/guidelines/typography/productive
  - https://v10.carbondesignsystem.com/guidelines/typography/expressive
  - [JSON to update](https://github.com/carbon-design-system/carbon-website/blob/v10/src/components/TypesetStyle/TypesetStyle.js)
- [x] v11 carbon website
  - https://carbondesignsystem.com/guidelines/typography/type-sets
  - [JSON to update](https://github.com/carbon-design-system/carbon-website/blob/main/src/components/TypesetStyle/typeScale.js)
- [x] v11 IDL (default, is not versioned, don't need to update for v10)
  - [JSON to update](https://github.com/carbon-design-system/design-language-website/blob/master/src/components/TypesetStyle/typeScale.js)

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon/11862?planning-poker) with ZenHub @laurenmrice @thyhmdo
