### ISSUE TITLE
[a11y]: Use tab key can't jump out form the information window on Add tags page

### ISSUE THREAD

**Issue by zhanttbj** [carbon-design-system/carbon#11878]
### Package

@carbon/icons

### Package version

Latest

### Automated testing tool and ruleset

Manual

### Description

Press the tab key, the focus should jump out the info window, move to the under textbox field.

### Reproduction/example

none

### Steps to reproduce

1. Click on Add tag icon on the top beside instance name
2. Tap to icon beside User tags field
3. Press the tab key
===== EXPECTED RESULT =====
Press the tab key, the focus should jump out the info window, move to the under textbox field.
<img width="826" alt="图片" src="https://user-images.githubusercontent.com/110212663/181675461-7dac9e35-68a4-41e8-b75d-67dde0d12e0f.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey! @zhanttbj 👋  That is actually the intended experience. When a tooltip has interactive content inside of it, the expectation accessibility-wise is that a user uses the `esc` key to dismiss the tooltip to ensure that the interactive elements inside the tooltip are accessible. We have improved this pattern in the v11 versions of our Tooltips if you would like a different and more customizable experience.

**Comment by zhanttbj** [comment]
@abbeyhrt thanks， so this is by design, will close this one, thanks
