### ISSUE TITLE
[Bug]: Incorrect red border on invalid inline filterable multiselect

### ISSUE THREAD

**Issue by ccwilson-us-ibm-com** [carbon-design-system/carbon#11875]
### Package

@carbon/react, @carbon/styles

### Browser

Chrome, Firefox

### Package version

v1.8.0

### React version

^17.0.0

### Description

When setting the invalid state on an inline filterable multiselect component, two overlapping red borders are rendered.  This occurs when at least one option is selected and the dropdown listbox is closed.  I believe there should only be a single border.

### Reproduction/example

https://stackblitz.com/edit/github-yxfgii?file=src/App.jsx

### Steps to reproduce

Here's how the component is configure to display this issue: 
```
<FilterableMultiSelect
          ariaLabel="Filterable MultiSelect"
          id="filterable-multiselect-example"
          items={items}
          label="Filterable multiselect options"
          titleText="Filterable multiselect title"
          type="inline"
          invalid="true"
        />
```

And then select at least on option in the component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ccwilson-us-ibm-com** [comment]
Screen shot for reference:
![Screen Shot 2022-07-28 at 10 57 53 AM](https://user-images.githubusercontent.com/68961008/181587683-39ba8804-4020-4f5a-8a9a-0ec3862186a8.png)

**Comment by tay1orjones** [comment]
Thanks for the report @ccwilson-us-ibm-com, you're right the intent is for only a single red outline to be present. We'll work on a fix.
