### ISSUE TITLE
[Bug]: Data table selectable variant's focus outline on checkbox looks too big

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11889]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.8.0

### Description

[Data table selectable](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--usage) variant has checkboxes in front of every row, and the checkboxes' focus outline appears too big: 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/15144993/182091390-01652e6a-85b4-401a-8848-21d5b81bb873.png">

Expecting checkbox focus style same as: https://react.carbondesignsystem.com/?path=/story/components-checkbox--checkbox-story

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--usage

### Steps to reproduce

Go to link, press `tab` to focus on checkboxes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by pmweeks98** [comment]
@tay1orjones can this be closed - looks like its fixed
