### ISSUE TITLE
[Bug]: Form helper-text margin should be 8px

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#11905]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v1.8.0

### Description

The helper text for the form component is wrong. The margin-top is coming in at 4px but it should be **8px**.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/11670886/182637196-6cabba5e-25c3-43d8-8780-d03524e81c7b.png">

### Reproduction/example

n/a

### Steps to reproduce

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by falsepopsky** [comment]
Can i work on this?, also this "bug" comes from the `styles` package.

**Comment by tw15egan** [comment]
@falsepopsky definitely, looking forward to the PR!
