### ISSUE TITLE
[Bug]: NumberInput steppers do not work when onChange is provided

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/carbon#11926]
### Package

@carbon/react

### Browser

Chrome

### Package version

@carbon/react 1.9.0

### React version

17.0.2

### Description

Add a numberinput and provide an onChange then try to use the steppers, it fails because the onChange is being called from the click action which has a target of the stepper

### Reproduction/example

https://codesandbox.io/s/upbeat-sinoussi-wgmqg1?file=/src/App.js

### Steps to reproduce

Add a numberinput and provide an onChange then try to use the steppers, it fails because the onChange is being called from the click action which has a target of the stepper

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/issues/11925#issuecomment-1208546160

> In this case it looks like we intended to ship this breaking change in the initial v11 release, but it was missed due to a misconfigured feature flag.
> 
> Sorry for the inconvenience and confusion on this, but the signature of the onChange event is slightly different now, though you can sill access the value to do what you did before.
> 
> The signature for onChange now looks like this:
> ```
> onChange(event, {value, direction})
> ```
> 
> I've put up a PR https://github.com/carbon-design-system/carbon/pull/11929 to update all docs for this.
> 

[Here’s a sandbox](https://codesandbox.io/s/cocky-antonelli-nivuqy?file=/src/App.js) I put together that shows how to use the value returned in the second parameter to update local state and fully control the NumberInput.
