### ISSUE TITLE
[Feature Request]: Modal to allow full width & full height content

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11933]
### Summary

This feature request is to add an option to remove the margin left, right and bottom and give the creative freedom to team using it. This should give us a modal content area with no styles. This would allow proper usage of container components inside modal, such as data table, tabs, fluid text input, etc, to look edge to edge, and achieve text alignment.

### Justification

Current Carbon Modal has margin left right and bottom built in, making it impossible to achieve these following designs documented on [Carbon Modal page](https://carbondesignsystem.com/components/modal/usage/) and [Carbon for IBM Products](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage/)
![image](https://user-images.githubusercontent.com/15144993/183602028-b93c1826-c4b5-43e1-b515-66bc1e0aa6e4.png)
![image](https://user-images.githubusercontent.com/15144993/183602243-4f46b5ec-24d2-4985-b50e-0d6544d13cf3.png)

The column customization modal actually looks like this in implementation. Notice how margin left, right and bottom is limiting the data table inside to reach full width.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/15144993/183602667-7e63ec31-6a0e-4177-9cf8-aff4d9149235.png">

This feature request is to add an option to remove the margins and give the creative freedom to teams to implement contained components inside modal in the expected way. We are going to be adding it for Carbon for Salesforce to ensure Column customization modal look as expected. You can reference [our implementation here](https://github.ibm.com/carbon-for-salesforce/carbon-for-salesforce/pull/109#pullrequestreview-11056373).

### Your team

Carbon for Salesforce / EPX (Ecosystem Platform Experiences)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
@carbon-design-system/developers 

Make a prop that overrides the margin. Maybe a day's worth of work per @tw15egan. Looking to add this the next sprint.
