### ISSUE TITLE
[Feature Request]: Export color codes (hex/rgba) for Component colors

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#11949]
### Summary

For theme colors it is possible to get the hex/rgba colors used by the SCSS via JavaScript modules. This is handy for using these items in other setups. Like React Native.

We currently get theme colors from `@carbon/themes/src/[g100/g10].js` which provides an object of tokens to hex/rgba syntax (camelCase version of the kebab style mixing found on Carbon website).

Would be nice to be able to get the component colors as well (button-, tag-, notification-...)

Currently we can get the main theme but not the components which forces us to hardcode them in our app. But ideally we could get all from Carbon project and keep Carbon as source of truth without having to upgrade in parallel.

### Justification

For the React Native library we are working on we would like to get theme color data from Carbon directly instead of duplicating items and missing changes in Carbon not propagating into our library.

### Desired UX and success metrics

People using Carbon React Native library in future won't have to wait on us if colors change in Carbon as updating `@carbon/themes` would do the work for them.

### Your team

Carbon Mobile Design and IBM Aspera

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
After discussing with the team, we can duplicate the values from the sass into the js for now. 

At a later date we can automate the creation of component tokens in sass from the js.
