### ISSUE TITLE
[Bug]: TableSelectRow & TableRow methods disable intended UI

### ISSUE THREAD

**Issue by enigmatikme** [carbon-design-system/carbon#11953]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.55.2

### React version

17.0.48

### Description

Trying to use the _onSelect onChange_ methods to do something with the data. However, it disables the intended UI. You will be unable to click the checkbox to "select all" -- this issue also exists for the <TableSelectRow /> component. If you call the onSelect/onChange to add an event listener it will disable the UI

(copied from your storybook example)

` <TableContainer
13        title="DataTable"
14        description="With selection"
15        {...getTableContainerProps()}>
16        <Table {...getTableProps()}>
17          <TableHead>
18            <TableRow>
19              <TableSelectAll {...getSelectionProps()} **onSelect={()} => console.log("do something with all selectedItems")/> (this will break the UI)**
20              {headers.map((header, i) => (
21                <TableHeader key={i} {...getHeaderProps({ header })}>
22                  {header.header}
23                </TableHeader>
24              ))}
25            </TableRow>
26          </TableHead>
27          <TableBody>
28            {rows.map((row, i) => (
29              <TableRow key={i} {...getRowProps({ row })}>
30                <TableSelectRow {...getSelectionProps({ row })} />
31                {row.cells.map((cell) => (
32                  <TableCell key={cell.id}>{cell.value}</TableCell>
33                ))}
34              </TableRow>
35            ))}
36          </TableBody>
37        </Table>
38      </TableContainer>`

### Reproduction/example

na

### Steps to reproduce

add an onSelect, onChange on the TableSelectAll element 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi! Thanks for reporting this issue. To help us debug further, could you provide a link to a reproduction using our [CodeSandbox template](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)?

**Comment by enigmatikme** [comment]
Hi! yes [https://codesandbox.io/s/lingering-surf-mcy7w8?file=/src/index.js](url)

To recreate issue try selecting the "select all" checkbox, you will see it is disabled because I added an onSelect method on the <TableSelectAll /> component which I believe does accept a function call to add an event listener. I was hoping to be able to get the same UI but just capture the data (of all the items selected). 

This is also true for the TableSelectRow

**Comment by aledavila** [comment]
@enigmatikme Hey you didn't send your forked example could you try sending your codebox example again please.

**Comment by jnm2377** [comment]
hey @enigmatikme could you share an updated sandbox link? The one you shared seems to be broken

**Comment by gromon42** [comment]
I can confirm that the bug is still there in 1.37 as I am experiencing it as we speak

**Comment by tw15egan** [comment]
Hey there @gromon42 can you throw some code in a [StackBlitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=README.md) so we can take a look at what's going on?
