### ISSUE TITLE
[Bug]: Font IBM Plex error 404 using vite. 

### ISSUE THREAD

**Issue by achilesmatheus** [carbon-design-system/carbon#11970]
### Package

@carbon/react

### Browser

Chrome

### Package version

vite 3.0.7

### React version

18.2.0

### Description

Hi, my name is Achiles. I'm having problems using carbon design system with react + vite. The development server cannot find the fonts. How can I resolve this?

See image
https://ibb.co/rGCcqgc

Thanks. 

### Reproduction/example

https://codesandbox.io/embed/cool-bird-gqjyfm?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

Use @react/carbon and vite. 

React 18.2.0
Vite 3.0.7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@achilesmatheus the default path includes a tilde, `~` 

https://github.com/carbon-design-system/carbon/blob/6b57099f46a734c7642b77093ff937e23f79be40/packages/styles/scss/_config.scss#L44

If you don't need it, you can redefine the path

```scss
@use '@carbon/react' with (
  $font-path: '@ibm/plex'
);
```

Going to close this out but let us know if it doesn't resolve your issue
