### ISSUE TITLE
[Bug]: Rendering issue of line chart in Chrome

### ISSUE THREAD

**Issue by JuhiSharma2** [carbon-design-system/carbon#12002]
### Package

@carbon/react, carbon-components

### Browser

Chrome

### Package version

1.5.0

### React version

17.0.2

### Description

The Line chart should be coming proper with the data .The line chart has elongated line which does not render data properly and it gets rendered properly after second refresh..This issues is only faced in Chrome and no other [[browser]](https://github.com/highcharts/highcharts/issues/17631) is

### Reproduction/example

https://codesandbox.io/s/wlbj6s

### Steps to reproduce

I'm running this charts on Chrome with the same code . There is a resisability issue present in chrome, the data is not rendering in it and in the first load it's giving me an error but in the second render it's working fine. 
In all the other browsers its working fine.
This is the correct render image : 
<img width="815" alt="Correct image" src="https://user-images.githubusercontent.com/111729812/186311488-01110e35-c628-4dda-b356-5ee075377150.png">

This is the bug faced:
<img width="830" alt="Screenshot 2022-08-23 at 10 02 55 AM" src="https://user-images.githubusercontent.com/111729812/186311566-8f3ebba1-2324-4019-9a6d-a70ee5027bf4.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Hi @JuhiSharma2 looks like this issue is for the charts library which lives in this repo: https://github.com/carbon-design-system/carbon-charts

Unfortunately, I can't transfer the issue to that repo, so I'm going to close this issue, but please re-open it in the charts repo. 🙂
