### ISSUE TITLE
[Question]: Update latest tag for `carbon-components`?

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#12001]
### Question for Carbon

The latest [`carbon-components` version](https://www.npmjs.com/package/carbon-components) on NPM is 10.56.0.

There have been a couple of minor releases since then (10.57, 10.58), but the latest is still 10.56.0.

Should the tag be updated or is this intentional?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@metonym Thanks for bringing this up! The intent is that `latest` should correspond to the latest v11.x release. The `v10-next` tag should correspond to the latest v10.x release. These must've accidentally gotten switched around. I'll get this fixed.

**Comment by tay1orjones** [comment]
Should be fixed now!
