### ISSUE TITLE
[Bug]: Sass variables not wrapped causing warning on react build

### ISSUE THREAD

**Issue by wwwju** [carbon-design-system/carbon#12017]
### Package

@carbon/react

### Package version

1.11.0

### React version

17.2.0

### Description

I have warnings at application build caused by sass variables.

```
static/css/main.59a21da1.css from Css Minimizer plugin
postcss-calc: C:\Users\Julie\Documents\wikit\wikit-v2\wikit-console-v2\static\css\main.59a21da1.css:7353:421986: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100% + $popover-offset
^.........^
```

After some research it seems that some variables are not wrapped in calc functions. 

Affected sass files:

- In popover.scss file :
$popover-offset should be wrapped in calc functions . 
For example: `transform: translate(calc(-1 * $popover-offset + 100%), -50%);` 
should be: `transform: translate(calc(-1 * #{$popover-offset} + 100%), -50%);`

- modal.scss
variable spacing-07 should be wrapped in calc functions too

### Reproduction/example

-

### Steps to reproduce

- Create a react project with create react app and last react scripts version (5.0.1)
- import carbon react css (@use '@carbon/react';)
- build project (npm run build)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @wwwju! Could you reproduce the issue in a [codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v11.9.0/examples/codesandbox)? It’s hard to know exactly what might be going wrong without seeing the issue first-hand.

**Comment by wwwju** [comment]
Hi,

Yes i can : [codesandbox](https://codesandbox.io/s/97ks2g) but my problem comes from build deployment

First, the toggletip component doesn't display like it should be. I correct the css in my own project but when i try to build my React application, it shows errors in toggletip and modal scss files. 

![image](https://user-images.githubusercontent.com/112385200/187448093-9ee8ec3f-4c42-489a-a984-f960d2463d36.png)

I tested a solution that seems to work by wrapping variables in calc functions with #{$variable-name} in files : [popover.scss](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/popover/_popover.scss) and [modal.scss](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/modal/_modal.scss)

**Comment by wwwju** [comment]
OK, yes of course i am using sass. For the moment i found a solution to bypass react-scripts checks on calc. I don't know why sass does not compile variables correctly in my case :/

**Comment by tay1orjones** [comment]
You might try updating your version of the `sass` dependency? From there I'm not sure what else specific to your configuration is different than a stock CRA that we found to be working fine.

Going to close this out, but happy to continue the conversation further with you here.
