### ISSUE TITLE
Experimental Component - Select - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1204]
**Design**
Create final design specification that are ready for production. Functionality and variations should match as is Carbon components. 

- [x] confirm Security design matches duo intent
   - Duo did not create a select
   - Security only had the basic select version, Carbon has two additional variations (small & inline)
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
# Select 
Sketch file: https://ibm.box.com/s/rugnplkv1wn4gpktcn13vbflwwhtc4ep

## Default & Small Select
![select_white](https://user-images.githubusercontent.com/11670886/46835897-16ab6880-cd75-11e8-816f-c842a55dd9b7.png)
![select_specs](https://user-images.githubusercontent.com/11670886/46835905-19a65900-cd75-11e8-86a2-5d9fe221d827.png)


## Inline Select
![select-inline_white](https://user-images.githubusercontent.com/11670886/46835914-1f03a380-cd75-11e8-97ea-a3126e27aa38.png)
![select-inline_spec](https://user-images.githubusercontent.com/11670886/46835916-2165fd80-cd75-11e8-8528-cdf437838a35.png)

**Comment by joshblack** [comment]
@aagonzales are we using the native select window for the dropdown itself? Hard to tell from the images, but I assume so. Just wanted to double-check 😄

**Comment by aagonzales** [comment]
The native select menu. The example is from Chrome.

**Comment by aagonzales** [comment]
Design good to go 👍 
Dev issue: https://github.com/ibm/carbon-components/issues/1211
