### ISSUE TITLE
Experimental Component - Toggle -Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1205]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
https://github.com/IBM/carbon-components/issues/1212
