### ISSUE TITLE
[Feature Request]: Add a bot to comment on PRs/issues when they are released that includes the version to pick up

### ISSUE THREAD

**Issue by leximarie** [carbon-design-system/carbon#12066]
### Summary

Add a bot or some sort of standard for adding a comment to PRs/issues when the bug/feature is released, including the version that the change is picked up in.

### Justification

When I’m trying to fix a bug with carbon, I often find that it is already an issue that was fixed and released, but then I have to search through pages of release notes and search for the exact issue/PR number to find what version the change was picked up in.

### Screenshots

Currently to find the release that a PR/issue is included in you have to do some digging, and it's not easily accessible for developers. 

### Your team

Cloud Pak for Data

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey, I think this is a great idea. I know of some other projects that do this and I've personally found it very helpful in the past.

I think this could consist of updating our release workflow to have an additional step to gather all relevant issues and PRs included in the release (or git tag) and then post a comment on them via the `gh` cli with something like

```
Hey there! vX.Y.Z was just released that references this issue/PR.
```

We might be able to gather the relevant issues and pull requests via the `gh` cli too. We'll have to investigate.

I'll place this in the backlog for now though it's unlikely we'll tackle it soon. Will gladly accept PRs if anyone is interested in contributing!

**Comment by tay1orjones** [comment]
I also want to share here the workaround I mentioned in slack earlier:

> In the meantime, there is a slightly easier way to determine what release something was included in. For any PR, if you click the merge commit at the bottom it will show you the version it was first tagged in as well as the most current tag that commit is included in.

https://user-images.githubusercontent.com/3360588/188709986-05d1501c-b72c-4943-84df-50ff11eabfd5.mov

**Comment by Shankar-CodeJunkie** [comment]
I am working on this, and currently exploring the way to have the information either via gh cli or github API's .

**Comment by Shankar-CodeJunkie** [comment]
I've built  a script, that inputs the message `Hey there! vX.Y.Z was just released that references this issue/PR.` . 


<img width="1000" alt="image" src="https://user-images.githubusercontent.com/56068832/194549918-a8fd5720-1826-4bb2-8916-d23ace1f9249.png">
