### ISSUE TITLE
Experimental Component - Tooltip - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1206]
**Design**
A designer can discover the experimental component on the System site and understand why and how to use it.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
@tw15egan not sure this goes to you -- just didn't want to leave it unassigned. Also, we talked about the use of the small Primary Button in this situation and how the right padding would have to be adjusted.

Again, wouldn't really use Security as a reference here, they don't have a tooltip component per se, but they have a tooltip pattern for the Text Input component... but our default sizing and spacing is different.

[Tooltip.zip](https://github.com/IBM/carbon-components/files/2466325/Tooltip.zip)

**Comment by jeanservaas** [comment]
Bounced this to dev:
https://github.com/IBM/carbon-components/issues/1213
