### ISSUE TITLE
Experimental Component - Date Picker - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1207]
**Design**
Create final design specification that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
   - Security did not have one
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
## Simple date picker
![date picker--single-date](https://user-images.githubusercontent.com/11670886/46883103-858cce00-ce16-11e8-9601-cb594a2a22a9.png)

**Comment by aagonzales** [comment]
# Date Picker

**Sketch file:** https://ibm.box.com/s/uigy7mp2afjjpaystflhqc573vyrrmq2

![date picker white fixed](https://user-images.githubusercontent.com/11670886/47048359-cc086280-d15f-11e8-9f87-aad180a3e174.png)

## Specs
![date picker-measurements](https://user-images.githubusercontent.com/11670886/47048368-d1fe4380-d15f-11e8-9bce-63f0f7d310f7.png)

**Comment by aagonzales** [comment]
@IBM/carbon-developers ready for dev 👍 
Dev issue: https://github.com/IBM/carbon-components/issues/1271
