### ISSUE TITLE
[Feature Request]: Is it possible to add customized rule for sort in DataTable

### ISSUE THREAD

**Issue by GraceeFlower** [carbon-design-system/carbon#12073]
### Summary

Hi team, I found `DataTable` in `carbon-components-svelte` can sort some column by customized rule like:

```
const headers = [
 {
    key: "expireDate",
    value: "Expire date",
    display: (date: string) => new Date(date).toLocaleString(),
    sort: (a: string, b: string) => new Date(a) - new Date(b),
  }
]
```
Is there any way that I can use like this? Since I only found `sortBy` and `sortRows`, THX!

### Justification

I wanna implement that sort one role in my customized rule.
Like some tasks status, ordering by the first character doesn't make sense to it. 

### Screenshots

N/A

### Your team

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@GraceeFlower Thanks for bringing this up! There's not yet a way to pass in an initial sort for the table. There's an open issue for it though with some ideas of an implementation, https://github.com/carbon-design-system/carbon/issues/11580

**Comment by tay1orjones** [comment]
Duplicate of https://github.com/carbon-design-system/carbon/issues/11580
