### ISSUE TITLE
Should I use `@carbon/react` or `carbon-components-react`?

### ISSUE THREAD

**Issue by jt-helsinki** [carbon-design-system/carbon#12076]
### Question for Carbon

It is not clear from the docs which library should we use: 

* @carbon/react 
* carbon-components-react

Both seem to be active and both seem to come out of this repository. `carbon-components-react` has TS types. `@carbon/react ` does not (AFAIK). 

Are the two libraries essentially the same? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@jt-helsinki `@carbon/react` is new for v11. It houses all the components, styles, and icons within a single package. It replaces the need for `carbon-components`, `carbon-components-react`, `carbon-icons`, `@carbon/icons`, and `@carbon/icons-react` packages.

It also includes the bulk of everything you should need from other Carbon packages including `@carbon/styles`, `@carbon/grid`, `@carbon/layout`, `@carbon/themes`, `@carbon/type`, etc.

We recommend starting with `@carbon/react` and not installing other Carbon packages until you find it necessary.

Full details are available in the [migration guide](/migrating/guide/develop) and the [v11 changelog](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md).

Typescript support for `@carbon/react` is in progress, for updates check out this discussion 
- #10752

**Comment by tay1orjones** [comment]
- https://github.com/carbon-design-system/carbon/discussions/12179

**Comment by craigyu** [comment]
@tay1orjones 

Hi, do you know if there's a typescript types package to use with @carbon/react? the only one I can find is this one https://www.npmjs.com/package/@types/carbon-components-react

**Comment by jt-helsinki** [comment]
@craigyu AFAIK, no there is not. However if you update to the latest version many of the components have been converted to typescript. This seems to be an ongoing effort so it gets better with each new release. 

HTH
