### ISSUE TITLE
[Feature Request]: icons

### ISSUE THREAD

**Issue by jamesTh23** [carbon-design-system/carbon#12083]
### Summary

Addition of 3 new icons

Requestor name and email or GitHub ID: James Thompson (james@4dstudio.com)
Business unit: Merative
Name of the UI icon batch: Image Availability Status
Description of each of the UI icons in the batch:
Local - the images of the exam are available locally, i.e. on the local system (as opposed to needing to be retrieved before the exam can be opened locally).

Retrieving - the images of the exam are being retrieved (transferred from a remote system to the local system).

Unavailable - the location (local or remote) of the images of the exam is unknown/unavailable.

Alias(es) for each of the UI icons in the batch (required):
Local: here, internal, location
Retrieving: fetching, transferring to this location
Unavailable: unknown, unknown location
Images: screenshot provided below
Box link: https://app.box.com/folder/172098218505
Due date: Sept 15 - 23

### Justification

A set of icons that will be utilized for a web based application (Merge Workflow Orchestrator) leveraged directly from the Carbon library.

### Screenshots

<img width="805" alt="Screen Shot 2022-09-09 at 12 47 18 PM" src="https://user-images.githubusercontent.com/113133839/189431844-58ef54ca-9463-486f-8ece-5a7d9e0eebe1.png">

### Desired UX and success metrics

Consistency with dozens of other icons leveraged from the library.

### Required functionality

Basic addition to the Carbon icon library.

### Specific timeline issues / requests

Sept 15 - 23, 2022

### Your team

Merative > Imaging > Merge Workflow Orchestrator

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by conradennis** [comment]
@jamesTh23 I made minor adjustments to each icon:

<img width="1289" alt="Screen Shot 2022-09-12 at 2 06 10 PM" src="https://user-images.githubusercontent.com/16782944/189725406-be53ab9e-2dfa-4b3d-a7d5-6eff265cd537.png">
<img width="1294" alt="Screen Shot 2022-09-12 at 2 06 21 PM" src="https://user-images.githubusercontent.com/16782944/189725417-e41f0627-0554-4e9b-82c0-0409fe50aad6.png">
<img width="369" alt="Screen Shot 2022-09-12 at 2 06 44 PM" src="https://user-images.githubusercontent.com/16782944/189725429-d79251b6-2a5f-4101-8c26-4099fd702ec9.png">

**Comment by jamesTh23** [comment]
perfect, thx!

**Comment by conradennis** [comment]
@jamesTh23 here are the final SVGs, I'll include them with the next batch of icons I submit to the Carbon repo.
[image availability icons.zip](https://github.com/carbon-design-system/carbon/files/9557585/image.availability.icons.zip)

**Comment by jamesTh23** [comment]
thx @conradennis! would you know roughly when these will show up in the public library?

**Comment by conradennis** [comment]
@jamesTh23 I'll most likely submit another batch at the end of September/early October

**Comment by conradennis** [comment]
@jamesTh23 PR submission: https://github.com/carbon-design-system/carbon/pull/12242

closing this issue
