### ISSUE TITLE
Experimental Component - Dropdown - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1208]
**Design**
A designer can discover the experimental component on the System site and understand why and how to use it.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Dropdown
Sketch file: https://ibm.ent.box.com/file/329975017065
![Dropdowns_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/47a3b618-f177-47ce-b366-27da523b3466)
![Combobox_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/8639cea4-76b5-44c6-a06d-26f36b894978)
![Multi-select Dropdowns_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/8abf934a-0f08-4d8c-875c-279643d2642c)
![Dropdown_Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/3dc7132d-65f6-4407-ab7f-86eec770e142)

*Notes:
- Specified dropshadow for drawers and Animation.
- Design added a bottom border line to dropdown closed states to meet 3:1 accessibility ratio.
- For Multi-select dropdown, Duo has checkboxes on the right, but Security is keeping them on the left. Carbon will be keeping them on the left as well.

**Comment by laurenmrice** [comment]
[https://app.zenhub.com/files/84835535/4870dca2-5ecd-4aaf-bef3-45ce252335ac/download](https://app.zenhub.com/files/84835535/4870dca2-5ecd-4aaf-bef3-45ce252335ac/download)

**Comment by laurenmrice** [comment]
Dev issue: https://app.zenhub.com/workspace/o/ibm/carbon-components/issues/1215
