### ISSUE TITLE
[Bug]: Disabled OverflowMenuV2 fires onClick 

### ISSUE THREAD

**Issue by ColRad** [carbon-design-system/carbon#12099]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.11.0

### React version

v18.2.0

### Description

When using the `unstable_OverflowMenuV2` and `unstable_MenuItem` I noticed that the MenuItem calls `onClick` even if it is set to `disabled`. 

Is this behavior intended?

### Reproduction/example

https://stackblitz.com/edit/github-unirk3?file=src/App.jsx

### Steps to reproduce

Open the Menu, click on the MenuItem

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@ColRad Good question! After looking into it, this appears to be appropriate that onClick would fire even when set to `disabled`. This is because the MenuItem ultimately renders a `li`, for which the browser still fires `onClick` events. I believe this is because `li` is not a form element.
