### ISSUE TITLE
[Bug]: Issue with ProgressStep component's onClick handler.

### ISSUE THREAD

**Issue by krab7191** [carbon-design-system/carbon#12093]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.11.0

### React version

18.2.0

### Description

Adding the onClick prop to a ProgressStep component results in nothing happening when the step is clicked, and an error when enter is pressed.

### Reproduction/example

https://github.com/krab7191/progress-indicator-onclick

### Steps to reproduce

Clone repo, run `npm i`, and then `npm run start`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there, @krab7191. To create an interactive Progress Indicator, you must pass an `onChange` prop to the `ProgressIndicator` element. Here is an [example](https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive)

Here is a little bit more info: https://react.carbondesignsystem.com/?path=/docs/components-progressindicator--interactive#overview


Let me know if we can clarify anything a bit better to improve the documentation 👍🏻

**Comment by krab7191** [comment]
@tw15egan thanks! I guess it was just a bit confusing since I was reading the docs for `ProgressStep` and not the indicator. I should have read more of the docs.
