### ISSUE TITLE
[Bug]: `DatePicker` does not use `forwardRef` in v11

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon#12116]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

17.0.1

### Description

I have a component that I'm updating from v10 to v11 and noticed that in v11 I am not able to pass a `ref` to the DatePicker component, likely because it appears that the v11 DatePicker is not using `forwardRef`.

For example, our library relies on the date picker ref to return the same values so that certain interactions can function as they do in v10. We've been able to work around this by [using querySelector](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/carbon-v11/packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js#L114-L119) to find the date picker input element that was previously part of the `ref`.

### Reproduction/example

https://stackblitz.com/edit/github-ndeemc?file=src%2FApp.jsx

### Steps to reproduce

Attempt to pass `ref` to DatePicker component

<img width="903" alt="image" src="https://user-images.githubusercontent.com/10215203/191157736-f1ceb197-193f-4f35-b6bc-797ec24f3f1e.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @matthewgallo! Thanks for pointing this out! We'll update DatePicker to forward a ref this week!
