### ISSUE TITLE
Experimental Component - Select - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1211]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by aagonzales** [comment]
Designs are ready: https://github.com/IBM/carbon-components/issues/1204
Sketch file: https://ibm.box.com/s/rugnplkv1wn4gpktcn13vbflwwhtc4ep

@IBM/carbon-developers
