### ISSUE TITLE
[Bug]: create-react-app . --template redux-typescript giving conflicts with React 18

### ISSUE THREAD

**Issue by GRawhideMart** [carbon-design-system/carbon#12113]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

latest, but can't install it

### React version

v18.2.0

### Description

I am trying to install @carbon/react through npm install, on a project boilerplated through `create-react-app . --template redux-typescript`.
Whenever I try to install @carbon/react, I get the following error message:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nuovo-membri@0.1.0       
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.1" from @carbon/react@1.13.0
npm ERR! node_modules/@carbon/react
npm ERR!   @carbon/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\PRODUZIONE\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PRODUZIONE\AppData\Local\npm-cache\_logs\2022-09-19T16_37_43_774Z-debug-0.log
```

### Reproduction/example

Just try to install @carbon/react on a brand new create-react-app typescript boilerplate

### Steps to reproduce

* Create a project with `npx create-react-app . --template redux typescript` 
* `cd` into the project folder 
* try `npm install @carbon/react`.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
We are in the process of migrating to React 18; as such, this is a known issue and is currently being tracked in https://github.com/carbon-design-system/carbon/issues/11308. Please follow that issue for further updates
