### ISSUE TITLE
[Bug]: Toggle click behavior

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12117]
### Package

@carbon/react

### Browser

Chrome

### Package version

Storybook

### Description

![toggle busted](https://user-images.githubusercontent.com/15822070/191292632-6e265434-9446-4889-b1d0-cc7aea6c6830.gif)

Checkout [storybook](https://react.carbondesignsystem.com/?path=/story/components-toggle--default). You can toggle it from anywhere in the white space

### Reproduction/example

n/a

### Steps to reproduce

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This [surfaced in slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1663683126896249).

This isn't a defect with the component itself, just with the story. We need to make the containing element that houses the label and toggle not span the entire width of the story so it behaves as you would expect - only clicking on the toggle or label makes the toggle switch.

**Comment by renmaddox** [comment]
I believe this is only partly true. If the label is appreciably longer than the toggle control, including the state label, then the problem still exists regardless of container.
