### ISSUE TITLE
Fluid inputs: FluidDatePicker

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12125]
This issue is for the primary implementation and design of the FluidDatePicker component.

**Checklist**

- [x] https://github.com/carbon-design-system/carbon-website/issues/3190
- [x] https://github.com/carbon-design-system/carbon-design-kit/issues/579
- [x] #12403
- [x] #12404

## Spec

[Sketch file]() | [Figma file]()

![DatePicker - White](https://user-images.githubusercontent.com/11670886/194885938-ab220f17-5162-4114-8e04-541ccc8973e7.png)

**Comment by tw15egan** [comment]
@aagonzales do you have a spec image for this component?
