### ISSUE TITLE
[Question]: How to dynamically render the expanded row content based on row? 

### ISSUE THREAD

**Issue by AnanthiPonnusamyAlfahive** [carbon-design-system/carbon#12132]
### Question for Carbon

I see in the given examples there are hardcoded values for expanded row like this.
```
{row.isExpanded && (
                <TableExpandedRow colSpan={headers.length + 1}>
                  <h1>Expandable row content</h1>
                  <p>Description here</p>
                </TableExpandedRow>
)}
```

The requirement is I need to pass the data for expanded row as part of rows. like
```
const rows = [
  {
    id: 'a',
    field1: 'Field 1a',
    expand: 'Value for Expanded row 1'
  },
{
    id: 'b',
    field1: 'Field 1b',
    expand: 'Value for Expanded row 2'
  }
];
```

Is this possible?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@AnanthiPonnusamyAlfahive Yes, it's possible - you'll need to manage this yourself though.

I'd recommend pulling the content you want rendered in the expanded area off of `rows` and place it in a separate object/array that can be used to dynamically render the content. This should be keyed by the row id so you can reference it when you render the TableExpandedRow.

Something like this might work

```
const rows = [
  {
    id: 'a',
    field1: 'Field 1a',
    expand: 'Value for Expanded row 1'
  },
{
    id: 'b',
    field1: 'Field 1b',
    expand: 'Value for Expanded row 2'
  }
];

const expansionContent = rows.map(row => return {parentRowId: row.id, content: row.expand});

// pull `expand` off so it's not rendered
const rows = rowData.map(({expand, ...rest}) => rest);


...

{row.isExpanded && (
  <TableExpandedRow colSpan={headers.length + 1}>
    {expansionContent.find((item) => item.parentRowId === row.id).content}
  </TableExpandedRow>
)}
```

**Comment by AnanthiPonnusamyAlfahive** [comment]
Thank you @tay1orjones . It works
