### ISSUE TITLE
Experimenta Component - Dropdown - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1215]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
- Specified dropshadow for drawers and Animation.
- Design added a bottom border line to dropdown closed states to meet 3:1 accessibility ratio.
- For Multi-select dropdown, Duo has checkboxes on the right, but Security is keeping them on the left. Carbon will be keeping them on the left as well.

https://ibm.ent.box.com/file/329975017065
