### ISSUE TITLE
[Bug]: NumberInput Steppers are behaving odd

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#12165]
### Package

@carbon/react

### Browser

Safari

### Package version

1.13.0

### React version

18.2.0

### Description

When using steppers on Number props. Sometimes I get string addition ('3' + 1 = 31) when I hit plus.  Sometimes I get it returning the MAX or NaN.

Going down seems fine.

This also seemed like a breaking change. Prior we used event to get the data even for step clicks.  But now I don't see value coming back on the stepper when the component is first initiated (it works after second try. But first one (like if set to 5; pressing sets to empty no usable event data).  Because of this moved to second param to get the value from it.

![android2](https://user-images.githubusercontent.com/8028956/192392471-a6d1ee08-09ec-4730-9975-a36a11b3726c.gif)

For now in house we are hiding steppers due to this bug.

To note; We are only using controlled components.

### Reproduction/example

https://codesandbox.io/s/4kmjci?file=/index.js

### Steps to reproduce

- Type in number `4`
- Press plus Get `41`. Expect 5

Weirder results with more complex usages.  See GIF above.  But most likely fix basic and will be good.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@dabrad26 Sorry you ran into this, thanks for reporting! I've got a fix up in a PR.
