### ISSUE TITLE
[Cloud Foundry] Migrate react.carbondesignsystem.com

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#12169]
#### User Story
> As a `[user role below]`:
Carbon developer

> I need to:
migrate react.carbondesignsystem.com from Cloud Foundry to Github Pages

> so that I can:
ensure the application is still running after Cloud Foundry is sunset

#### Additional information
- Login to IBM Cloud account and Cloudflare available via 1Password team account
- CF app name `carbon-storybook`
- Example website repo setup: https://github.com/carbon-design-system/carbon-website-v9

#### Acceptance criteria
 - [ ] Use the monorepo GH pages for publishing
 - [ ] Update the deploy workflow to deploy to Gh pages in addition to cloud foundry
 - [ ] Cloudflare DNS configuration is reconfigured to `carbon-design-system.github.io`
 - [ ] Cloud Foundry application is disabled and/or deleted
 - [ ] Pipelines no longer publish to Cloud Foundry

**Comment by tay1orjones** [comment]
I think instead of using a new repo we can just use the monorepo. It doesn't have github pages configured right now.
