### ISSUE TITLE
Custom created design tokens usage in a new theme

### ISSUE THREAD

**Issue by fahadahmed** [carbon-design-system/carbon#12166]
### Question for Carbon

How should I create a custom new theme based on the updated tokens?

We have created a new token variables based on the new designs but there is no documentation on how to apply these tokens inside a new theme.

Example:

```scss
// _variables.scss
$white: #ffffff;
$ey-off-black: #2e2e38;
$ey-yellow: #ffe600;
$ey-grey-1: #747480;
$ey-off-white: #f4f4f4;

$gray-10: #f4f4f4;
$gray-10-hover: #e5e5e5;
$gray-20: #e0e0e0;
$gray-20-hover: #cacaca;
$gray-30: #c6c6c6;
$gray-40: #a8a8a8;
$gray-50: #8d8d8d;
$gray-60: #6f6f6f;
$gray-70: #525252;
$gray-80: #393939;
$gray-80-hover: #4c4c4c;
$gray-100: #161616;
```

We have then used these base colour tokens here:

```scss
$ui-background: base.$white;

$interactive-01: base.$ey-off-black;
$interactive-02: base.$ey-yellow;
$interactive-03: base.$ey-grey-1;
$interactive-04: base.$ey-grey-1;

$danger-01: base.$red-60;
$danger-02: base.$red-60;

$ui-01: base.$ey-off-white;
$ui-02: base.$ey-off-white;
$ui-03: base.$gray-20;
$ui-04: base.$gray-50;
$ui-05: base.$gray-100;

$button-separator: base.$gray-20;

$decorative-01: base.$gray-20;
```

We are creating a custom theme as below:
```scss
@use './tokens/_variables.scss' as base;
@use './tokens/fonts' as fonts;
$custom: (
  // Background
  // background: #000066,
  // button-primary: #000066,
  interactive: #009d9a,
  focus: base.$ey-yellow,
  
);
```

We are then using the following to use the custom theme:

```scss
// Setup theme
@use '_themes' as app;
@use '@carbon/styles/scss/config' with (
  $use-akamai-cdn: true
);
@use '@carbon/react/scss/type' as *; // Needed to compile build the theme :/
@use '@carbon/themes/scss/themes';
@use '@carbon/styles/scss/theme' with (
  $fallback: themes.$white,
  $theme: app.$custom
);
```

The question we have is how to use the tokens we have created for fonts, spacing etc to be used in the theme?

If we include custom tokens as advised in the documentation here: https://carbondesignsystem.com/guidelines/themes/overview/

we get the following error:

![Screen Shot 2022-09-27 at 8 51 39 am](https://user-images.githubusercontent.com/1190340/192404194-e551b50b-690e-4646-90dc-58b452d3cc7a.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by abbeyhrt** [comment]
Hey @fahadahmed! We are in the process of creating more docs and usage examples of how to do custom theming in v11, in the meantime we do have this documentation around theming our styles packages, https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#themes, hopefully that helps! We will post the examples we make here in the future as well!

**Comment by tay1orjones** [comment]
@fahadahmed Following up here - @jnm2377 just put up a PR https://github.com/carbon-design-system/carbon/pull/12244 with a fully functioning example showcasing how to add custom tokens, configure existing tokens, and a few other use cases.

In looking at your examples, the thing that stands out most is that you're mixing packages quite a lot, when you should instead be able to get most everything you need from `@carbon/react` alone.

This example you posted:
```scss
// Setup theme
@use '_themes' as app;
@use '@carbon/styles/scss/config' with (
  $use-akamai-cdn: true
);
@use '@carbon/react/scss/type' as *; // Needed to compile build the theme :/
@use '@carbon/themes/scss/themes';
@use '@carbon/styles/scss/theme' with (
  $fallback: themes.$white,
  $theme: app.$custom
);
```

I think this could probably be rewritten as
```scss
@use '_themes' as app;
@use '@carbon/react/scss/themes';
@use '@carbon/react/scss/theme' with (
  $fallback: themes.$white,
  $theme: app.$custom
);
@use '@carbon/react' with (
  $use-akamai-cdn: true
);
```

Check out the PR though, it's got this plus a bit more that you might find helpful. Once it's merged I can update you with a link to it running in a stackblitz instead of having to start it up locally.
