### ISSUE TITLE
[Type token updates]: Fix discrepancies between code and specs in v10 and v11

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#12174]
## [Type token updates]: Fix discrepancies between code and specs

**Problem:** When Olivia and I were working on the weight changes in the packages to support brand, @aagonzales found a few discrepancies between the type specs and the type in code. Here I'm both making those fixes and also, reverting some of the weight changes Olivia and I made, since they're a little awkward even in the variable fonts.

**v11**
$fluid-heading-03
$fluid-heading-04
$fluid-heading-05
$fluid-heading-06
$heading-05

**v10**
$expressive-heading-03
$expressive-heading-04
$expressive-heading-05
$expressive-heading-06
$productive-heading-05

### $expressive/fluid-heading-06 
(updates in bold)

SM
Size: 2rem/32px
Weight: 600, semiBold
lineHeight: 1.25/40px
letterSpacing: 0

MD
Size: 2.25rem/36px
Weight: 600, semiBold
lineHeight: 1.22/44px
letterSpacing: 0

LG
Size: 2.625rem/42px
Weight: 600, semiBold
lineHeight: 1.19/50px
letterSpacing: 0

XLG
Size: 3rem/48px
Weight: 600, semiBold
lineHeight: 1.17/56px
letterSpacing: 0

MAX
Size: 3.75rem/60px
Weight: 600, semiBold
**lineHeight: 1.17/70px**
letterSpacing: 0

### $expressive/fluid-heading-05 
(updates in bold)

SM
Size: 2rem/32px
**Weight: 400, regular**
lineHeight: 1.25/40px
letterSpacing: 0

MD
**Size: 2.25rem/36px**
Weight: 300, light
lineHeight: 1.22/48px
letterSpacing: 0

LG
Size: 2.625rem/42px
Weight: 300, light
lineHeight: 1.19/50px
letterSpacing: 0

XLG
Size: 3rem/48px
Weight: 300, light
lineHeight: 1.17/56px
letterSpacing: 0

MAX
Size: 3.75rem/60px
Weight: 300, light
**lineHeight: 1.17/70px**
letterSpacing: 0

### $heading-05/productive-heading-05

(update in bold)

Size: 32px / 2rem
Line height: 40px / 2.5rem
**Weight: 400 / Regular**
Letter spacing: 0px

### $expressive/fluid-heading-04

(changes in bold)

SM
Size: 1.75rem/28px
Weight: 400, Regular
lineHeight: 1.28572/36px
letterSpacing: 0

MD
Size: 1.75rem/28px
Weight: 400, Regular
lineHeight: 1.28572/36px
letterSpacing: 0

LG
Size: 1.75rem/28px
Weight: 400, Regular
lineHeight: 1.28572/36px
letterSpacing: 0

XLG
Size: 2 rem/32px
**Weight: 400, Regular**
lineHeight: 1.25/40px
letterSpacing: 0

MAX
Size: 2rem/32px
**Weight: 400, Regular**
**lineHeight: 1.25/40px**
letterSpacing: 0

### $expressive/fluid-heading-03

(changes in bold)

SM
Size: 1.25rem/20px
Weight: 400, Regular
lineHeight: 1.4/28px
letterSpacing: 0

MD
Size: 1.25rem/20px
Weight: 400, Regular
lineHeight: 1.4/28px
letterSpacing: 0

LG
Size: 1.25rem/20px
Weight: 400, Regular
lineHeight: 1.4/28px
letterSpacing: 0

XLG
Size: 1.25rem/20px
Weight: 400, Regular
**lineHeight: 1.4/28px**
letterSpacing: 0

MAX
Size: 1.5rem/24px
Weight: 400 Regular
lineHeight: 1.334/32px
letterSpacing: 0

**Comment by tw15egan** [comment]
@oliviaflory @jeanservaas PRs are up to bring this to both v10 and v11

https://github.com/carbon-design-system/carbon/pull/12284
https://github.com/carbon-design-system/carbon/pull/12327
