### ISSUE TITLE
[Cloud Foundry] Migrate vue.carbondesignsystem.com

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#12171]
#### User Story
> As a `[user role below]`:
Carbon developer

> I need to:
migrate vue.carbondesignsystem.com from Cloud Foundry to Github Pages

> so that I can:
ensure the application is still running after Cloud Foundry is sunset

#### Additional information
- Login to IBM Cloud account and Cloudflare available via 1Password team account
- CF app name `carbon-storybook-vue`
- Example website repo setup: https://github.com/carbon-design-system/carbon-website-v9
- Existing workflow: https://github.com/carbon-design-system/carbon-components-vue/blob/main/.github/workflows/deploy-vue-storybook.yml

#### Acceptance criteria
 - [x] Storybook deployment workflow/action is updated to publish to github pages on the vue repo
 - [x] Cloudflare DNS configuration is reconfigured to `carbon-design-system.github.io`
 - [x] Cloud Foundry application is disabled and/or deleted
 - [x] Storybook deployment workflow/action is updated to no longer publish to Cloud Foundry
 - [ ] Branch protection added to the gh-pages branch

**Comment by tay1orjones** [comment]
Just moved the DNS over and everything's resolving as expected 👍
