### ISSUE TITLE
[Feature Request]: 64px size for icons

### ISSUE THREAD

**Issue by chimericdream** [carbon-design-system/carbon#12176]
### Summary

It would be helpful if we had an additional size beyond the current max of 32px for the icon components.

### Justification

I am working on a site whose design calls for social icons larger than the max of 32px allowed by Carbon. My current options are to duplicate the icons and use my own version or push back on the design to limit the icon size to 32px.

### Screenshots

n/a

### Your team

@SeanGroff @igorlanko

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
@chimericdream We have [Pictograms](https://carbondesignsystem.com/guidelines/pictograms/library/) that you could use that are intended to be larger in size than our Icons.

**Comment by chimericdream** [comment]
Perfect. I didn't realize there was a separate component for that. Thanks!

**Comment by chimericdream** [comment]
After a little more digging, I am going to re-open this. The specific icons we are wanting to use at 64px are some of the social media logos, which do not appear to have a corresponding pictogram. Is there a way to pass an icon into the `Pictogram` component?

**Comment by tay1orjones** [comment]
> Is there a way to pass an icon into the Pictogram component?

No, they'd need to be added to the pictograms library/package.

**Comment by chimericdream** [comment]
I had a feeling that would be the case. Is there another alternative to achieve the same goal (in this case, larger social icons), or have I fallen into an edge case that may or may not find its way into Carbon?

**Comment by jnm2377** [comment]
Going to close this issue based on design input https://github.com/carbon-design-system/carbon/issues/12176#issuecomment-1259896041
If you're interested in contributing new pictograms, please open a new design issue w/ more detail about the pictograms themselves. thanks!
