### ISSUE TITLE
[Question]: May I replace the sort icon and pagination dropdown by my own icon/component?

### ISSUE THREAD

**Issue by GraceeFlower** [carbon-design-system/carbon#12194]
### Question for Carbon

I'm building a sortable table with pagination using `DataTable` and `Pagination` component by`carbon-components`.
Is it possible to:
1. replace the sort icon by my own icon;
2. replace the select page/pageSize dropdown by my component;

since the UI designer has some preference, hope team can give some suggestions, thank you!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Hey there, @GraceeFlower; there is no built-in way to change the icons as they are standardized across the Design System. If you wanted to override them, you could set their display to hidden and find a way to render them differently.

As far as replacing the dropdowns in `Pagination`, you can take a look at `unstable_Pagination` and replace the `PageSelector` with your own component. Hope that helps!

**Comment by GraceeFlower** [comment]
Thank you so much for giving these ideas so quickly, that looks like a plan, I'll have a try.
