### ISSUE TITLE
Button hasIconOnly bug with Modal

### ISSUE THREAD

**Issue by NotEntirelySure** [carbon-design-system/carbon#12205]
There is a bug when using the following Carbon components: Button, DataTable, and Modal. Loading a Button that utilizes the hasIconOnly property into the DataTable seems to be what creates the bug. When the Modal is opened in this configuration, the Button in the DataTable row that utilizes the hasIconOnly is still clickable and has a higher z index than the Modal and the Modal overlay. If the still accessible Button opens a different Modal with its onClick event, opening and then closing the other Modal, will cause the Buttons with the hasIconOnly property to then operate as expected (becoming inaccessible and having a lower z index than the Modal). When the Button is changed to hasIconOnly={false}, the Button then responds as expected (becomes inaccessible and has a lower z index than the Modal). Another thing that causes the Buttons to operate as expected is to change the DataTable property of stickyHeader={false} to stickyHeader={true}. For some reason, when the DataTable is set to having a sticky header, the Buttons loaded into the DataTable rows operate as expected when the Modal opens.
![Has_Icon_Only_False_With_Sticky_Header](https://user-images.githubusercontent.com/72530241/193337351-f7862f9c-93d6-446a-a545-f04f00184f64.png)
![Has_Icon_Only_No_Sticky_Header](https://user-images.githubusercontent.com/72530241/193337353-315e3e32-3e8d-4470-94ed-55f079e2a823.png)
![Has_Icon_Only_With_Sticky_Header](https://user-images.githubusercontent.com/72530241/193337354-ca8c7d56-2355-4752-be18-3a185356fd85.png)
![HigherZindex](https://user-images.githubusercontent.com/72530241/193338103-2917d8d9-73c7-427d-ac99-7593b29e0fc6.png)

**Comment by NotEntirelySure** [comment]
Forgot to mention: this bug occurs when Carbon version 11. It does not occur with Carbon version 10.

**Comment by abbeyhrt** [comment]
Hey @NotEntirelySure! Thanks for reporting this bug! This is definitely something we will look into! Would you mind providing more information about the bug you're running into? Like what version of Carbon are you using?

**Comment by tw15egan** [comment]
Confirmed, `Modal` styles are leaking out

<img width="795" alt="Screen Shot 2022-10-04 at 9 17 53 AM" src="https://user-images.githubusercontent.com/11928039/193829354-376c9d05-0840-49fb-9532-39fb307cd01a.png">

**Comment by NotEntirelySure** [comment]
> Hey @NotEntirelySure! Thanks for reporting this bug! This is definitely something we will look into! Would you mind providing more information about the bug you're running into? Like what version of Carbon are you using?

@abbeyhrt The version of Carbon I'm using is v11. I was migrating my project from v10 when I noticed this bug with my modals.
