### ISSUE TITLE
[Bug]: Modal with `NumberInput` renders incorrectly

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#12229]
### Package

@carbon/styles

### Package version

Latest

### Description

<img width="756" alt="Screen Shot 2022-10-04 at 12 16 09 PM" src="https://user-images.githubusercontent.com/11928039/193872042-6475e3cb-8de0-4058-8a04-7bca3aa080b8.png">

<img width="697" alt="Screen Shot 2022-10-04 at 12 21 05 PM" src="https://user-images.githubusercontent.com/11928039/193872864-225ef40e-4a02-4240-ab0c-f5af4589b19d.png">

`NumberInput` dividers need to be updated to use correct tokens

### Reproduction/example

See above

### Steps to reproduce

Add a `NumberInput` to `Modal`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by nelsonchen90** [comment]
@tw15egan @tay1orjones 
i created https://github.com/carbon-design-system/carbon/pull/13806 to pick the change to v10, please take a look
