### ISSUE TITLE
Data table not supporting "short" style?

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon#1223]
Data table component doesn't seem to support the "short" style. We use React so it might be specific to that. This is reported by a dev on our team (Justin Pomeroy) so I would follow up with him for any further clarification.

**Comment by tw15egan** [comment]
Do you have an example of the `short` style? Not sure what that means

**Comment by mlinnem** [comment]
Here's a reference to the style on the website:
<img width="800" alt="screen shot 2018-10-09 at 12 05 14 pm" src="https://user-images.githubusercontent.com/1547834/46685653-9c83b400-cbbb-11e8-9811-3f4a412eb0e7.png">

Here's the style in the kit:
<img width="1426" alt="screen shot 2018-10-09 at 12 04 57 pm" src="https://user-images.githubusercontent.com/1547834/46685672-a3aac200-cbbb-11e8-8dd0-b0dfd298747f.png">

**Comment by tw15egan** [comment]
Issue moved to [IBM/carbon-components-react #1408](https://github.com/IBM/carbon-components-react/issues/1408) via [**ZenHub**](https://www.zenhub.com/)
