### ISSUE TITLE
[Question]: What is the correct way to implement a Progress Modal?

### ISSUE THREAD

**Issue by fahadahmed** [carbon-design-system/carbon#12233]
### Question for Carbon

Trying to implement the Progress Modal variant, I am unable to find anything in the Modal component API that can keep track of the Form progress inside the Modal component.

References:
- [Modal variants](https://carbondesignsystem.com/components/modal/usage/#modal-variants)
- [Component API Docs](https://react.carbondesignsystem.com/?path=/docs/components-modal--default)

Would it be upto the developer to create a Progress Form and add it inside the Modal component and manage the state of the form ourselves? If yes, how can we manage the action button at the Modal Footer section?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@fahadahmed Hi! Yes, that's correct. You'll provide the content, a form, etc. with whatever state management you need for your application. Then to manage the action button you can set the `primaryButtonDisabled` prop to disable the action button until the form is complete/valid. If your use case calls for it, you can also use `onRequestClose` to provide a warning to the user if they're closing out of a form with a lot of progress that it will be lost on close.

**Comment by fahadahmed** [comment]
Hi @tay1orjones, thanks for the follow-up. I have implemented something similar. 

Is there a storybook repo where I can share what I have come up as an example of how a Progress Modal can be implemented?
