### ISSUE TITLE
Read-only Inputs: Checkbox Implementation

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12243]
### Reference #12241 

<img width="990" alt="image" src="https://user-images.githubusercontent.com/15822070/194140730-c52d06fc-a65f-4435-bf8d-d94a7a52bfe6.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/15822070/194140798-f65e6768-5a8d-44e2-ba4f-db59e3f1c04b.png">

#### Acceptance Criteria

- [ ] Coded component in `/package/react`
- [ ] Add a prop for read-only, add styles for said prop
- [ ] Controls for each state in playground
- [ ] Default story for easy copy and paste
- [ ] RTL tests for the read-only class on the prop

**Comment by lee-chase** [comment]
Personally prefer a control to a story, a disabled story would be odd.

Perhaps also read only specific color tokens e.g. $border-readonly

**Comment by lee-chase** [comment]
- MDX file update?

**Comment by lee-chase** [comment]
Q: A little concerned elsewhere we are using `readOnly` as opposed to the standard attribute `readonly`. Will this not cause confusion?

**Comment by tay1orjones** [comment]
@lee-chase I'll jump in and try to answer some of these questions.

> Personally prefer a control to a story, a disabled story would be odd.

We apply VRT to each story in the storybook. By having a dedicated story titled "readonly" we can ensure there are no visual regressions over time.

> Perhaps also read only specific color tokens e.g. $border-readonly

My guess is no, we won't add these as tokens. Adding tokens has lots of implications across the system. Ultimately this is a question for design though, @aagonzales what are your thoughts?

> MDX file update?

Story files should import an .mdx file that corresponds to the "docs" tab in storybook. This .mdx file will need updated to include the readonly story as well as light docs on how/when to use the readonly prop/variant.

> Q: A little concerned elsewhere we are using readOnly as opposed to the standard attribute readonly. Will this not cause confusion?

Yeah I think the standard attribute should be used here where possible, following convention of how we use other standard attributes like `title`. I think it should be listed as a prop and probably just have a proptype of `bool`.
