### ISSUE TITLE
[Bug]: Mifration to carbon v11, error after import component

### ISSUE THREAD

**Issue by artem1551** [carbon-design-system/carbon#12258]
### Package

@carbon/react

### Browser

Chrome

### Package version

@carbon/react v1.13.0

### React version

v17.0.2

### Description

 There was a problem during the transition from carbon version 10 to version 11. I connected all styles the imports, after which all the variable colors and sizes were applied 

![Screenshot 2022-10-07 at 16 04 05](https://user-images.githubusercontent.com/69159017/194560452-de893dcb-c378-489d-97b1-7f331e14df1c.png)

In this case compiled okay but without components

then the imports of the components were applied to the general file, after which there was an error
![Screenshot 2022-10-07 at 15 42 41](https://user-images.githubusercontent.com/69159017/194558115-90c5102b-ef9c-4d4c-9f59-a34213845f5b.png)

![Screenshot 2022-10-07 at 15 43 53](https://user-images.githubusercontent.com/69159017/194558135-2009f815-2055-4e9c-b5b9-429d30aa32f3.png)

Made changes in web pack something like this
 
![Screenshot 2022-10-07 at 15 45 12](https://user-images.githubusercontent.com/69159017/194558160-f8db458b-d2ec-456d-91ff-be442dde859b.png)

Installed ony sass-loaded , don't have node-sass below package
![Screenshot 2022-10-07 at 15 53 27](https://user-images.githubusercontent.com/69159017/194558385-2d1691d1-fdfa-4a09-b140-cbe73c9f27c2.png)

### Reproduction/example

Tried to use @carbon/react example scss with style use, but it is not working on local environment

### Steps to reproduce

all problem i was wrote in description , i think main problem with webpack.config.  The main idea need import components seperately to style.scss global file

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@artem1551 Could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite)? It’s hard to know exactly what might be going wrong without seeing the issue first-hand.

**Comment by tay1orjones** [comment]
> In this case compiled okay but without components

`@use '@carbon/react';` will include all the component styles. You shouldn't need to `@use` a component's styles/module unless you have a specific reason to do so.

**Comment by artem1551** [comment]
https://stackblitz.com/edit/github-sgg4df?file=src/assets/scss/custom-carbon.scss 
this maximum what i can reproducer, but this only one error now i have something new error 
<img width="867" alt="Screenshot 2022-10-10 at 14 58 43" src="https://user-images.githubusercontent.com/69159017/194861532-9541b264-1d9e-40b0-a3b0-a6336e2ce284.png">

**Comment by tay1orjones** [comment]
@artem1551 One thing that stands out is on your stackblitz, you're including `custom-carbon.scss` twice. Also you're importing component style files (accordion, etc.) and you shouldn't need to if you have `@use '@carbon/react';`


Searching your error message, I found this that might be helpful. https://github.com/webpack-contrib/sass-loader/issues/867 It's possible your sass-loader needs a change to it's config.

**Comment by artem1551** [comment]
1.It is important for me that it is possible to connect several elements of the library, not all at once, since the project is small, there is no need for this
2. need use variables without prefix: theme or layout
https://stackblitz.com/edit/github-4tftft?file=src%2Findex.scss,src%2FApp.jsx
and interesting thing, i comment bc: $button-danger-primary , his not work i dont undestand becasuse this variables from v11, and 'link-primary' too, but link work.

**Comment by tay1orjones** [comment]
Gotcha, that makes sense. `$button-danger-primary` is a component token and isn't provided through the theme module. [Here's full docs](https://github.com/carbon-design-system/carbon/blob/acead26eeb6f15ec6d39970e4af08aa23ee48cdc/packages/styles/docs/sass.md?plain=1#L393), but in short you just need to `@use` the button component tokens module

```
`@use '@carbon/styles/scss/components/button/tokens';`

...

.selector {
  background-color: tokens.$button-danger-primary
}
```

I modified your stackblitz as an example: https://stackblitz.com/edit/github-4tftft-pskfzj?file=src%2Findex.scss,src%2FApp.jsx

**Comment by tay1orjones** [comment]
Going to close this out, but let me know if there's more we can help with here. Thanks!
