### ISSUE TITLE
[Bug]: OverflowMenuItem title text not shown when disabled

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#12257]
### Package

carbon-components-react

### Browser

Chrome

### Package version

10.53.0

### React version

17.0.2

### Description

An OverflowMenuItem with disabled, title, and requireTitle props does not show its title text on hover.

I believe the problem is that `pointer-events: none;` is set on disabled menu items, preventing them from getting the hover state - https://github.com/carbon-design-system/carbon/blob/v10.53.0/packages/styles/scss/components/overflow-menu/_overflow-menu.scss#L313

Overriding the rule to apply `pointer-events: unset;` and `cursor: not-allowed;` appears to fix the issue.

### Reproduction/example

https://codesandbox.io/s/overflowmenuitem-title-not-shown-when-disabled-tv56bo

### Steps to reproduce

Create an OverflowMenuItem with disabled, title, and requireTitle props.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting! I've just put a PR up to fix this.
