### ISSUE TITLE
[Question]: Tabs not showing correctly (styles missing)?

### ISSUE THREAD

**Issue by i-n-g-o** [carbon-design-system/carbon#12253]
### Question for Carbon

Hello.

I bootstrapped a fresh project basically following the react tutorial step 1:

- bootstrap project with react@17.0.1, react-dom@17.0.1, react-scripts@5.0.1
- installing carbon: `npm install -S @carbon/react`
- installing sass: `npm install -S sass`
- adding `@use '@carbon/react';` to index.scss, ...

Creating simple <Tabs> Element only shows the content, not the tab-buttons.
A simple <Button> looks like it should.

Are there any styles missing?
What did i do wrong?

The project is attached.
[CDS_Tabs-test.zip](https://github.com/carbon-design-system/carbon/files/9725497/CDS_Tabs-test.zip)

Thanks,
Ingo

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@i-n-g-o Hey there! 👋 It looks like you're not composing the tabs properly. Check out [the storybook and API docs](https://react.carbondesignsystem.com/?path=/story/components-tabs--default) for Tabs. It shows the story source and how to compose `Tabs`, `TabList`, `Tab`, `TabPanels`, and `TabPanel`.

**Comment by i-n-g-o** [comment]
Thanks for pointing this out!
I think i am confused when i am using v10 and when v11.

Using the code as documented for version 1.14.0 works.
