### ISSUE TITLE
Experimental tile: final design spec

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#12279]
Create a final detailed design specification for the new experimental tile variation. Include all states and tokens. When complete, add an image and a link to design files to this issue.

New experimental tile for
- Base
- Clickable
- Expandable
- Selectable (Radio)
- Selectable (Multi)

Related: [New color token + values](https://github.com/carbon-design-system/carbon/issues/12343#issuecomment-1284584601)

**Comment by thyhmdo** [comment]
[Figma file ](https://www.figma.com/file/9ETOwILkTbvUErWUR4PTIg/Tiles_v11?node-id=1%3A2)

![Tiles - Color themes](https://user-images.githubusercontent.com/77697351/197224474-281fd238-a0d9-44d7-a2df-20de7211db05.jpg)
![Tiles - Gray 10](https://user-images.githubusercontent.com/77697351/197225777-58c2bb93-9b96-41a0-8e14-4b600df55732.jpg)
![Tiles - Gray 90](https://user-images.githubusercontent.com/77697351/197225790-4096bfab-503e-4995-993d-3a387b2c1862.jpg)
![Tiles - Gray 100](https://user-images.githubusercontent.com/77697351/197225797-8e5e1455-76b8-43ec-9ff3-6236032da548.jpg)
![Tiles - White](https://user-images.githubusercontent.com/77697351/197225808-eeee90c7-560a-4cf1-bb8a-2d57cc294b66.jpg)
