### ISSUE TITLE
Contained List: Final design edits

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#12277]
## Contained list
- [x] Align with Diana Tran on Contained list 
- [x] [Revise docs with any edits](https://github.com/carbon-design-system/carbon-website/issues/3198)
- [x] [Put in Figma libraries](https://github.com/carbon-design-system/carbon-design-kit/issues/583) (waiting to merge)

**Comment by kunderwoodatadaptive** [comment]
Is the Contained List going to be included in the V11 Figma library any time soon? So far, I only see 'Structured List.'

**Comment by laurenmrice** [comment]
@kunderwoodatadaptive We will be pushing these updates to the Contained List component to the Public Carbon libraries in the next couple of weeks so you will have them in the v11 libraries.
