### ISSUE TITLE
[Question]: Datepicker Component, flatpickr value doesn't reset 

### ISSUE THREAD

**Issue by GiacomoP99** [carbon-design-system/carbon#12270]
### Question for Carbon

![phase_1](https://user-images.githubusercontent.com/84136671/194850149-3e3445f0-86a4-4ae7-95c9-5f3a971cbaf3.png) selecting some dates
![phase_2](https://user-images.githubusercontent.com/84136671/194850156-88bf4551-e6ba-4670-98b2-719727de4090.png) reset values through button
![phase_3](https://user-images.githubusercontent.com/84136671/194850158-a8a9b6c0-40bd-41c6-9726-7fa162752ed7.png) the value resets only in the input but the calendar still memorize the old one 

codesandbox example : https://codesandbox.io/s/sleepy-solomon-fk61c3?file=/index.js

How can i reset the value of the date selected in the flatpickr calendar ? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hi @GiacomoP99! You might try providing `value=null` or `value=""`. This might work to reset the component, but I'm not 100% sure how flatpickr will handle that. 

A better bet would be to place a `key` on the DatePicker and change the value of it when the reset button is clicked. This will instruct react to discard the existing component and re-render a new one. This should fully reset any lingering internal state in regards to flatpickr.

**Comment by GiacomoP99** [comment]
None of those soultions worked

**Comment by GiacomoP99** [comment]
i've also tried to remove the flatpickr calendar from the DOM and change the key of the datepicker after, but still it keeps the previous date

**Comment by GiacomoP99** [comment]
![image](https://user-images.githubusercontent.com/84136671/194899889-d1e98245-3f57-4746-a62b-6a731b38cd72.png)
we menaged to fixed it even tho it gives error on typescript by passing a date for the min/maxDate instead of undefined, we think the solution is to avoid controlling the value if it is defined.
