### ISSUE TITLE
Tree view: Designs and spec for Multi-select keyboard hotkey variant

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#12276]
- [x] Conduct design research
- [x] Iterate on different design concepts
- [x] Review with team and incorporate any feedback

**Comment by laurenmrice** [comment]
**Design**
- No more design work is needed for the Multi-select keyboard hotkey variant.

**Dev**
- There are a couple more dev items that need to be finished before bringing this to stable in code.
