### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by gnietof** [carbon-design-system/carbon#12274]
### Question for Carbon

Hi!

We are developing an application using Carbon and React. We are using tooltips in a menu component to provide additional information about each of the options. These tooltips are automatically displayed when the user hovers over each of the menu options.
The problem we are having is that, probably due to the animations used when displaying each of these tooltips, they  are overlapping (more than one visible at the same time). Specially when moving the cursor quickly between the different entries.
![tooltips](https://user-images.githubusercontent.com/18265633/194887443-7c47060b-db55-41c4-b6ce-8003ca80d9cd.png)
We know that the obvious solution might be having our code take control of when they are shown / hidden. But we were wondering if there is some kind of configuration setting we might use to remove or customize those animations. 
Whether the problem is related with animations or not, any suggestions / comments are more than welcome.

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Hey there @gnietof Do you happen to know which version of the components you are using? Are you able to put together a quick repo on [codesandbox](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx) so we can better understand the situation this problem is occurring?

**Comment by sstrubberg** [comment]
Closing for now. Hit us up with that codesandbox repo and we'll be happy to re-open :)
