### ISSUE TITLE
[Bug]: `DefinitionTooltip` issue with `align` property

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#12287]
### Package

@carbon/styles

### Browser

Chrome

### Package version

@carbon/react v1.14.0

### React version

v16

### Description

When working on https://github.com/carbon-design-system/carbon-website/issues/3104 I noticed that the `align` property was not calculating the `caret` position properly. `Popover` and `Tooltip` do not seem to have this issue

![2022-10-11 13 08 34](https://user-images.githubusercontent.com/11928039/195162453-76787a88-e274-4415-ad26-056607009cab.gif)

### Reproduction/example

See above

### Steps to reproduce

Go to `DefinitionTooltip` and try changing the `align` property, and compare it with `Popover` and `Tooltip`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
All yours, @FionaDL 👍🏻

**Comment by FionaDL** [comment]
Hello, we were only able to reproduce this bug in the playground, but the default seemed to be working. We think it has something to do with binding the arguments to the Playground story, as that is the only difference we could find. We were not able to solve this though. If someone else wants to work on this, please allow them, otherwise we will keep poking around.

**Comment by riddhybansal** [comment]
It works as intended, The caret position depends upon the size of the base word. If the user wants to make it more customise or more precise , they can override the classes as per there usage.

Moreover, The Caret positioning can be improved with the usage of floating UI. This will position the floating tooltip element at the position based on the alignment attribute.
