### ISSUE TITLE
[Bug]: The title attribute of OverflowMenu icon "open and close list of options" should be proper cased or should be in sentence case. 

### ISSUE THREAD

**Issue by kavyaprem** [carbon-design-system/carbon#12293]
### Package

carbon-components-react

### Package version

7.37.0

### React version

16.14.0

### Description

The title attribute of OverflowMenu icon (the 3 dots menu icon) "open and close list of options" should be proper cased or should be in sentence case. We can use iconDescription attribute to override the hover text however, as this is a generic issue we would require some default setting in this carbon component for the proper casing of the text.

### Reproduction/example

https://codesandbox.io/s/magical-glitter-03v3mk

### Steps to reproduce

Please hover on the 3 dot icon (OverflowMenu icon). The hover text "open and close list of options" is in small case. It should be either proper cased or sentence cased.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by vishalpurandare** [comment]
@tay1orjones How do I figure out the carbon-components-react version that the fix went into? We are currently on Carbon 10, so carbon-components-react 7.37.0.

**Comment by vishalpurandare** [comment]
The latest at this point in time seems to be 7.59.5 which should have the fix but was just wondering how trace the version from the commit/PR.
