### ISSUE TITLE
Move `ContainedList`, `ContainedListItem` to stable

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12319]
`ContainedList` and `ContainedListItem` have been flagged as ready for a review to move to stable. Based on [the docs](https://github.com/carbon-design-system/carbon/blob/main/docs/experimental-code.md), the following criteria need to be met when moving a component from experimental to stable:

- [x] All files have a copyright banner
- [x] All components exported in `src/index.js` and should not be `unstable_`
      prefixed
- [x] Component has a label in the github repository
- [ ] Component should be documented on the website
  - [x] Component should have a usage tab
  - [x] Component should have a style tab
  - [x] https://github.com/carbon-design-system/carbon-website/issues/3198
  - [x] https://github.com/carbon-design-system/carbon-website/issues/3153
  - [x] https://github.com/carbon-design-system/carbon-website/issues/3152
- [x] For each component exported:
  - [x] Component is written as a function declaration or uses `forwardRef`
  - [x] Component has `propTypes` defined
    - [x] Each prop type has a comment (used in storybook)
    - [x] Prop types are as specific as needed, prefer `PropTypes.shape` over
          `PropTypes.object` if possible
  - [x] Default props are listed as default args in the function definition (not
        in defaultProps)
    - [x] Note: default props should be stable, in other words props like
          `onClick = () => {}` can cause re-renders since the function identity
          is not stable
  - [x] Component has a story in `<ComponentName>.stories.js`
    - [ ] Component has an mdx document that follows our outline
    - [ ] mdx document coverages at least common use-cases and provides a prop
          table
    - [x] Stories cover at least common use-cases
    - [x] Stories may include a `Playground` story for controls
    - [x] Stories should mirror intended usage of the component
  - [x] Component has unit/integration tests written in RTL for testing the
        component API
  - [ ] Component is tested via VRT for at least the initial render state
  - [ ] Component is tested via AVT for at least the initial render state
 

Most of these above are complete already from the initial delivery in https://github.com/carbon-design-system/carbon/pull/11969 🎉 

---

Additionally I think we need to address the following in the storybook:
- [x] On the playground story, hide `className`, `actions`, and `children` from the controls table
- [x] Suggestions for updated story names
  - [x] Following the storybook convention, it needs a "Default" story
    - [x] Rename `On page` -> Default
  - [x] Disclosed 
  - [x] With actions
  - [x] With icons
  - [x] With interactive items
  - [x] With interactive items and actions
  - [x] With list title decorator
  - [x] Playground
  - [x] would it be worthwhile to have a `with layer` story? I figure that might be a common use case
  - [x] Could we reduce the repetition/duplication in the stories down to a single `ContainedList` with `ContainedListChildren` in each story?

**Comment by tay1orjones** [comment]
@janhassel let me know what you think about this 👀 

cc @laurenmrice

**Comment by janhassel** [comment]
@tay1orjones Thanks for setting this up!

> On the playground story, hide className, actions, and children from the controls table

#12346

---

> Suggestions for updated story names [...]

#12347

---

> Could we reduce the repetition/duplication in the stories down to a single ContainedList with ContainedListChildren in each story?

Up to you! 😄 Whenever I contributed storybook generators in the past (e.g. with Menu), issues or PRs were created to remove them and build the story out for better documentation through the "Story" panel. Therefore I thought I'll have everything static this time but happy to change it if you'd prefer!

**Comment by janhassel** [comment]
@tay1orjones I was thinking it would be useful to show both variants ("On Page" and "Disclosed") in all stories but we can also remove the "Disclosed" variant from the individual demos and keep it in the "Disclosed" story only. The Playground allows for switching anyways.

**Comment by tay1orjones** [comment]
@janhassel Ah, I now see that the second one was configured as `disclosed`. Sorry I missed that. 

Yeah I agree - I think removing the disclosed variant from individual demos makes sense since it's got it's own story.

**Comment by janhassel** [comment]
@tay1orjones 👍 Sounds good. I'll open a PR removing these as soon as the other PRs are merged in order to avoid conflicts.

**Comment by janhassel** [comment]
@tay1orjones Just opened a PR removing the `disclosed` variant demos from the sample stories: #12371

With this, I believe the list of storybook updates should be completed, correct?

**Comment by tay1orjones** [comment]
@janhassel Yeah this looks awesome! I just put up one final PR https://github.com/carbon-design-system/carbon/pull/12387 knocking out the rest of the checklist items (sans docs) and move it to stable 🎉
