### ISSUE TITLE
[Question]: how to use carbon with react 18 and typescript

### ISSUE THREAD

**Issue by tliliAbdelmonem** [carbon-design-system/carbon#12325]
### Question for Carbon

how to use carbon with react 18 and typescript

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hi @tliliAbdelmonem - React 18 and typescript support are both in the works

- https://github.com/carbon-design-system/carbon/issues/11308
- https://github.com/carbon-design-system/carbon/discussions/10752
