### ISSUE TITLE
@carbon/telemetry 0.1.0 have "Sensitive Authentication(Basic) Information Leak" vulnerability issue

### ISSUE THREAD

**Issue by Decretum-Wu** [carbon-design-system/carbon#12324]
Hi team,
During a DAST scan, we found that there is a "Sensitive Authentication(Basic) Information Leak" issue in @carbon/telemetry 0.1.0

Just as below
`if (options.auth && !("authorization" in this[kHeaders])) {
  this[kHeaders].authorization = "Basic " + Buffer.from(options.auth).toString("base64");
}`

Would you mind please kindly remediating this vulnerability?
Thanks.

**Comment by jdharvey-ibm** [comment]
https://github.ibm.com/carbon/ibm/issues/130 Has been resolved/closed.
