### ISSUE TITLE
Variables in 'theme' need to move back to 'vars'

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1232]
We released a breaking change when working on the experimental theme by moving the color variables out of `vars` and into `theme` instead.

Need to revert this and move them back into the `vars` file.

<img width="318" alt="screen shot 2018-10-10 at 8 38 43 pm" src="https://user-images.githubusercontent.com/2753488/46775357-80236c80-cccc-11e8-9509-edc4e1e8439e.png">

Related PR that wasn't merged https://github.com/IBM/carbon-components/pull/1132
Related Issue https://github.com/IBM/carbon-components/issues/1129

cc @AsthaJain1

**Comment by alisonjoseph** [comment]
@asudoh any ideas on best approach here? Is there a different/better way for us to turn on the experimental theme? We can't move the mixin inside of vars without causing an import loop or it not working. I can also dig in to this more tomorrow.

**Comment by asudoh** [comment]
@alisonjoseph Probably this? https://github.com/IBM/carbon-components/compare/master...asudoh:include-theme-tokens-back-in-vars

(Assuming that `_helper-mixins.scss` import in `_theme.scss`, which is causing the import loop, is merely for using `feature-flag-enabled()`)

**Comment by alisonjoseph** [comment]
Yes, that seems like it will work. Will open a PR from your branch and test.
