### ISSUE TITLE
Carbon modal default css is visibility:hidden and opacity:0

### ISSUE THREAD

**Issue by zeynepuyyanik** [carbon-design-system/carbon#12334]
### Question for Carbon

I'm trying to open a modal, but it is not visible. 
tested with   "carbon-components": "10.20.0" and "carbon-components-angular": "4.13.2".

```
{
  visibility: hidden;
  opacity: 0; 
}
```

why shall we write custom CSS here? if not, what am I missing? 

I just used the example modal definition from [the official documentation](https://github.com/IBM/carbon-components-angular/blob/317d7776b23d7b4d10a36bbf1c9917fc6caa6e00/src/modal/modal.component.ts#L34)

<img width="919" alt="bug" src="https://user-images.githubusercontent.com/75336267/196689762-98fcbf54-b797-4f31-ad12-0749e1f9c6ed.PNG">

and even if I overwrite the CSS, it still doesn't work. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@zeynepuyyanik The modal should be given a class of `.is-visible`. This is something the `carbon-components-angular` component should be doing. I can't transfer this issue to that repository unfortunately, so you'll have to [open this issue on their repo separately](https://github.com/IBM/carbon-components-angular/issues/new).
