### ISSUE TITLE
[Bug]: TextArea component doesn't update counter label after value is changed

### ISSUE THREAD

**Issue by renato-souzaf** [carbon-design-system/carbon#12348]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.59.0

### React version

v16.14.0

### Description

When setting the TextArea component's value without triggering the `onChange` event, the characters counter is not updated.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/angry-kalam-4lrr3h

### Steps to reproduce

Type any random text in the TextInput.
Check the TextArea.

Expected: the value **and the counter label** to be updated.
Result: the value is updated, but the counter label still displays 0.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@renato-souzaf Thanks for reporting this, great catch! It probably just needs a `useEffect` to update the counter state when the value changes.

**Comment by TannerS** [comment]
@tay1orjones  i added that code, would something like this due

```
  useEffect(() => {
    setTextCount(defaultValue?.length || value?.length || 0);
  }, [defaultValue, value]);
```

if so, i have no idea how to properly test this

**Comment by TannerS** [comment]
So i gave this a try, adding a fake story for textarea based on the sandbox above. I cannot figure it out

useEffect doesnt work with the prop, i tried a useRef for the textarea element and that doesnt work either when changing via .value, i tried event listeners, and etc with no luck. I am wondering if this is possible

**Comment by emyarod** [comment]
rather than changing the `value` DOM property, wouldn't this be the more "Reactlike" way to achieve this be something like:

```jsx
export const App = () => {
  const [text, setText] = useState('');
  return (
    <>
      <TextInput
        labelText="TextInputLabel"
        placeholder="Type something here"
        onChange={(e) => setText(e.target.value)}
      />
      <br></br>
      <br></br>
      <TextArea
        id="text-area"
        labelText="TextAreaLabel"
        maxCount={500}
        enableCounter
        placeholder="Counter should be updated when value is changed by typing something in the TextInput"
        value={text}
      />
    </>
  );
};
```

if I'm not mistaken, I think you would need the useEffect to use a vanilla `onchange` event listener (instead of React `onChange`) which seems like a React antipattern

**Comment by TannerS** [comment]
> rather than changing the `value` DOM property, wouldn't this be the more "Reactlike" way to achieve this be something like:
> 
> ```js
> export const App = () => {
>   const [text, setText] = useState('');
>   return (
>     <>
>       <TextInput
>         labelText="TextInputLabel"
>         placeholder="Type something here"
>         onChange={(e) => setText(e.target.value)}
>       />
>       <br></br>
>       <br></br>
>       <TextArea
>         id="text-area"
>         labelText="TextAreaLabel"
>         maxCount={500}
>         enableCounter
>         placeholder="Counter should be updated when value is changed by typing something in the TextInput"
>         value={text}
>       />
>     </>
>   );
> };
> ```
> 
> if I'm not mistaken, I think you would need the useEffect to use a vanilla `onchange` event listener (instead of React `onChange`) which seems like a React antipattern

i kinda understand, can u provide example?

**Comment by emyarod** [comment]
> i kinda understand, can u provide example?

were you able to try the example I provided in the previous comment?

**Comment by TannerS** [comment]
hey @emyarod  i missed this, i prob need a tag to know its for me, you know i messed with this back then and couldnt get it to work, even with useState, but that was a while back, i can try again soon

**Comment by TannerS** [comment]
@emyarod  sorry im catching up on my though process, I did find a solution

What i did locally, is, the solution is correct what you said, its better to do it a react way to trigger a re-render, and the second part of the solution is what @tay1orjones  said, some useffect to detect a change in `value` right now it sets an initial value for the text size which doesnt change on re-render (my bad) so im do a pr for it and let yall think its an ok fix

**Comment by TannerS** [comment]
this should have been merged so i think its worth trying again with some help of suggestions above
