### ISSUE TITLE
[Question]: Contributor License Agreement process

### ISSUE THREAD

**Issue by javatlacati** [carbon-design-system/carbon#12367]
### Question for Carbon

In the [CONTRIBUTING section](https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md) there's nothing regarding the Contributor License Agreement process, kindly add some documentation so IBMers and external contributors know what the process is

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@javatlacati Thanks for pointing this out - we can add a section in the contributing.md about how first time contributors will need to "sign" the DCO via commenting on a PR, etc.

**Comment by kcprevatt** [comment]
@tay1orjones Hello! I'd like to start getting involved with and contributing to this project, so this is something I actually need to figure out anyway. Could this task to update documentation be assigned to me?

**Comment by tay1orjones** [comment]
@kcprevatt sounds good!
