### ISSUE TITLE
[Bug]: Grid md offset linebreak is applied to lg, despite no offset is specified for lg

### ISSUE THREAD

**Issue by DaopingWang** [carbon-design-system/carbon#12372]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.15.0

### React version

v18.3.0

### Description

We are trying to create a Grid with Columns with offset. The columns should be arranged

- Horizontally when in lg
- Vertically when in md and smaller

The issue is reproduced in the following code snippet ([codesandbox](https://codesandbox.io/s/hungry-meadow-i3b4ht?file=/index.js:154-712))

```html
<Grid fullWidth>
  <Column lg={{ offset: 1, span: 7 }} md={{ offset: 1, span: 3 }}>
    First column
  </Column>
  <Column lg={{ span: 8 }} md={{ offset: 1, span: 3 }}>
    Second should be same row if lg, new row if md
  </Column>
</Grid>
<Grid fullWidth>
  <Column lg={{ offset: 1, span: 7 }} md={{ offset: 1, span: 3 }}>
    First column
  </Column>
  <Column lg={{ span: 8 }} md={{ span: 3 }}>
    Second should be same row if lg, new row if md
  </Column>
</Grid>
```

You can see in the first Grid that despite not giving the second column an offset in lg, the linebreak from the md offset still gets applied in lg.

Could you have a look on this issue? Thank you so much!

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/hungry-meadow-i3b4ht?file=/index.js:154-712

### Steps to reproduce

Render the two Grids and you can see that in the first Grid, the columns are affected by the described issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by DaopingWang** [comment]
Hi @tay1orjones 
thanks for responding! We now can understand that applying configurations upwards to larger sizes is intentional.
However when we try to implement your suggestion:
```html
- <Column lg={{ span: 8 }} md={{ offset: 1, span: 3 }}>
+ <Column lg={{ offset: 0, span: 8 }} md={{ offset: 1, span: 3 }}>
  Second should be same row if lg, new row if md
</Column>
```

We found out that giving lg a different offset (=0 in our case) does not override the offset of md.
We still see the one offset column in lg, plus there is a linebreak applied in lg between the columns.
Please check out the updated [sandbox](https://codesandbox.io/s/stupefied-euler-evux3h?file=/index.js)

Our goal is to create a layout that displays the two columns in the same row in lg,  two rows in md.

**Comment by DaopingWang** [comment]
Could you reopen the issue? thanks

**Comment by jpsorensen** [comment]
Observed the same - offset of 0 results in no offset rule being set for that size, so the css selector for the smaller size is applied.
