### ISSUE TITLE
[Bug]: SkeletonText has an inline style that breaks CSP in SSR

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/carbon#12386]
### Package

carbon-components-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v7.59.4

### React version

v17.0.2

### Description

In SkeletonText, there is a `width` property that you cannot nullify it. It is default to `100%` if not specified. This `width` prop turns out to be an inline style. When using in SSR, I will then see this violation.

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-1ab3c34441e11a4377e7b34384251a01'". Either the 'unsafe-inline' keyword, a hash ('sha256-Q5Zbi1HJmWC2e721HDLiKbPwTXmvBEI2Dttcb1cd/1w='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

Can we have a way to avoid setting the `width` prop which will NOT add an inline styling?

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

N/A

### Steps to reproduce

Render this piece of code:

```
                            <div className="details-page-cluster-container">
                                <div className="createArtifactFlexGroupRow form-row half-width">
                                    <SkeletonText />
                                </div>
                            </div>
```

You will see an inline style of `width: 100%` added to the DOM. When turning on CSP, this will violate the rule if it's coming from SSR because the DOM contains an inline style.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @flannanl - the `width` prop on SkeletonText is optional and defaulted to `100%`. It looks like the `width` is always rendered though, even if you were to pass in a null/`0`/etc.

Updating this component to not render the `width` inline style when `width` is falsey seems reasonable. We will want to allow `width="0"` though.

**Comment by flannanl** [comment]
@tay1orjones yes, all I want is to be able to not pass the width prop so that the inline styling will not be generated. The skeleton text styling already has a rule to set the width to 100%. So it is not necessary to default the width prop to 100% if not specified.

**Comment by TannerS** [comment]
Hello, i created issue that also includes this component and few others https://github.com/carbon-design-system/carbon/issues/12580
