### ISSUE TITLE
Show exact value in multi-select dropdown when 1 item is selected rather than showing just the number 

### ISSUE THREAD

**Issue by risehgal21** [carbon-design-system/carbon#12391]
## Summary

Just wanted to share feedback on Multi-select dropdown from users via usertesting session on App Configuration--
They get confused when the tag says 1 item selected, they expect to see what item has been selected and not just a number. And this is consistent feedback from multiple users and design/dev teams as well.

**Comment by tay1orjones** [comment]
@risehgal21 Thanks for reporting this as a suggested feature! We explored this previously and found it to be unscalable from a design perspective https://github.com/carbon-design-system/carbon/issues/2571#issuecomment-577313072

**Comment by tay1orjones** [comment]
Duplicate of #2571
