### ISSUE TITLE
Experimental Component - List - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1240]
**Design**
A designer can discover the experimental component on the System site and understand why and how to use it.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
https://github.com/IBM/carbon-components/issues/1277
