### ISSUE TITLE
[Read-only inputs]: Toggle implementation

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12407]
### Reference #12241 

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/15822070/198120621-95b3528c-8200-40a6-831e-5b691dc953df.png">

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/15822070/198120666-f49fa393-50b8-4ac4-8ff6-1f4f80020e77.png">

#### Acceptance Criteria

- [ ] Coded component in `/package/react`
- [ ] Add a prop for read-only, add styles for said prop
- [ ] Controls for each state in playground
- [ ] Default story for easy copy and paste
- [ ] RTL tests for the read-only class on the prop
- [ ] When a toggle is `readonly` and not disabled, the field is read by screenreaders while not allowing the value to be changed.

**Comment by laurenmrice** [comment]
Just noting here: For the `Off` read-only state, the text color of the Off label should be $text-primary and not $text-placeholder because it still needs to pass 4.5:1.
