### ISSUE TITLE
Issue creating inline actions with data table

### ISSUE THREAD

**Issue by koolsush** [carbon-design-system/carbon#12417]
I need to add inline actions as documented here.

When the overflow menu contains less than three options, keep the actions inline as icon buttons instead. This reduces 1 click and makes available actions visible to users at a glance.

But there is no documentation on how to add custom actions for each row. I need to add two actions in every table row. Could you please help me how to achieve it in Datatable?

Thanks

**Comment by sstrubberg** [comment]
Hey, here is an [example of passing links](https://react.carbondesignsystem.com/?path=/story/components-datatable-filtering--default). You can probably do the same with icon buttons. Let us know!
