### ISSUE TITLE
Using a DataTable, what is the best way to make a TableCell a Link?

### ISSUE THREAD

**Issue by StephenLerch** [carbon-design-system/carbon#12416]
## Summary
I have created a generic DataTable component. I want to be able to reuse this component. An important requirement is to provide drill down using a Link. The linked column varies. For one table the linked column might be id and for a second table the linked column might be device-name.

Is there an existing mechanism or an easy way to pass the column name and a path (url for Link) to the DataTable?

## Relevant information
At present the generic data table maps over the rows collection then the cells collection to create the table cells. It could check the cell.id for a value to determine if the table cell child needs to be a Link.

**Comment by sstrubberg** [comment]
Check out [this story](https://react.carbondesignsystem.com/?path=/story/components-datatable-filtering--default) in our Storybook that uses links.
