### ISSUE TITLE
[Bug]: RadioButton checked prop not working

### ISSUE THREAD

**Issue by stepoibm** [carbon-design-system/carbon#12425]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

17.0.0

### React version

17.0.0

### Description

`<RadioButton checked={true}  />` doesn't do anything, despite being documented as controlling which radio is checked.

https://react.carbondesignsystem.com/?path=/story/components-radiobutton--default

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-px87be?file=src%2FApp.jsx

### Steps to reproduce

See stackblitz

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
You're right; it seems like that prop is unused and should be removed from the documentation. If you want to control which RadioButton is selected, you can use the `valueSelected` prop on `RadioButtonGroup`. Here is a simplified example:
https://stackblitz.com/edit/github-px87be-cxepck?file=src%2FApp.jsx

**Comment by mgueyraud** [comment]
Hi @tw15egan, I'll like to take this issue, I think what we can do is, only when one of this two props: `defaultSelected` or `valueSelected` are passed to the RadioButtonGroup component, then we override the `checked` prop for the RadioButton components, if none of those props are passed, then we don't override the `checked` prop of the children.

**Comment by tw15egan** [comment]
@mgueyraud makes sense to me, I'll keep an eye out for a PR
