### ISSUE TITLE
Experimental Component - Structured List - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1242]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Structured List
Sketch file: https://ibm.ent.box.com/file/332823096737
![Structured List_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/9043f84b-db80-4fff-86b4-dcb36db17e8b)

**Comment by laurenmrice** [comment]
@IBM/carbon-developers ready for dev 👍
Dev issue: #1275
