### ISSUE TITLE
Experimental Component - Overflow Menu - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1243]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
   - Security didn't have one
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
# Overflow Menu Designs

**Sketch:** https://ibm.box.com/s/8tfz3alb5hajjk5q8zyyiizk4sty1sj6

![overflow-menu_white](https://user-images.githubusercontent.com/11670886/47321992-1421fc00-d61c-11e8-92b2-8f9491592ab7.png)
![overflow-menu_specs](https://user-images.githubusercontent.com/11670886/47321999-197f4680-d61c-11e8-9221-63ecb7f34402.png)

**Comment by aagonzales** [comment]
Designs are ready for dev ✅ 
Dev Issue: https://github.com/ibm/carbon-components/issues/1292
