### ISSUE TITLE
Restore Modal three button example

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12443]
The three button example was removed from the modal in this PR https://github.com/carbon-design-system/carbon/pull/12013, we need to add it back in.

https://github.com/carbon-design-system/carbon/issues/12443#tasklist-block-044bfeb8-8fc6-462a-9d1b-328b3008485c

**Comment by Djunnni** [comment]
i want try this

**Comment by tw15egan** [comment]
@Djunnni all yours!

**Comment by Djunnni** [comment]
i have a question about that.

modal three button means footer three button?

**Comment by Djunnni** [comment]
thanks :)
