### ISSUE TITLE
Experimental Component - Code Snippet - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1244]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
   - Security does high contrast with inline and single line, Carbon is doing subtle/default colors
   - Security does not next icon to edge of box in multi-line.
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
# Code Snippet

Sketch File: https://ibm.box.com/s/29467ot2hiew5vxr8kk0dsqb2lnim0sw

## Variations:
![code-snippet white](https://user-images.githubusercontent.com/11670886/47586071-b4319b00-d924-11e8-80a7-883e6fad0463.png)

## Specs & measurements 
![code-snippet_spec](https://user-images.githubusercontent.com/11670886/47586073-b4319b00-d924-11e8-8712-0faad60793b3.png)

**Comment by aagonzales** [comment]
Designs done ✅ 
Dev issue: https://github.com/IBM/carbon-components/issues/1350
