### ISSUE TITLE
Experimental Component - Notification - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1245]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
https://github.com/IBM/carbon-components/issues/1295

**Comment by jeanservaas** [comment]
## Notification

Sketch File: https://ibm.box.com/s/wlqdd8ayfcvf4omy7616ldzs2elei9bv
- Mike and Chiu wanted to explore more color in the Notification component; so it deviates from the DL master component file. They approved the colors and all should be contrast compliant. Digital heads up on this one @eraymond25
- Security does not reflect the color change and does not have the toast notification; they also do a double line format in their line notification (they break after their title)

![notification_default](https://user-images.githubusercontent.com/43144260/47737573-367cd080-dc3f-11e8-9386-9e5206b8a9e9.png)
![notifications_specs](https://user-images.githubusercontent.com/43144260/47737574-367cd080-dc3f-11e8-8920-ab1ac233a340.png)
