### ISSUE TITLE
Experimental Component - Data Table - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1246]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by designertyler** [comment]
### Row sizes
## Tall 64px
![default - 64 tall](https://user-images.githubusercontent.com/19270502/48579664-bfa03280-e8e2-11e8-989d-88d40a8ab166.png)

## 48px
![default - 48px row](https://user-images.githubusercontent.com/19270502/48579681-c9c23100-e8e2-11e8-923a-aacb03e2a2c7.png)

## 32px Short
![default - 32 short](https://user-images.githubusercontent.com/19270502/48579692-d34b9900-e8e2-11e8-98e0-a4cc4394c1a8.png)

## 24px Compact
![default - 24 compact](https://user-images.githubusercontent.com/19270502/48579707-dcd50100-e8e2-11e8-9046-5d0a209f91fa.png)


## Expandable and Selected

![expandable rows](https://user-images.githubusercontent.com/19270502/48579740-f0806780-e8e2-11e8-87dd-b0be5fa97e18.png)

![expandable selectable](https://user-images.githubusercontent.com/19270502/48585006-eb2a1980-e8f0-11e8-9add-58c8079ff66f.png)

**Comment by aagonzales** [comment]
## Column headers + sort
![column header bar-v2](https://user-images.githubusercontent.com/11670886/48793318-3317ba80-ecbc-11e8-97de-1c4cbbd76738.png)


## Row states + Overflow menu
![row states](https://user-images.githubusercontent.com/11670886/48584792-57f0e400-e8f0-11e8-9196-4fd80b36dd4a.png)
![overflow menu](https://user-images.githubusercontent.com/11670886/48584791-57f0e400-e8f0-11e8-8b5b-e70b9a0df97e.png)

## Tool bar + search
![toolbar](https://user-images.githubusercontent.com/11670886/48584794-57f0e400-e8f0-11e8-854f-5f11923237fa.png)
![search-v2](https://user-images.githubusercontent.com/11670886/48793508-c5b85980-ecbc-11e8-8f35-a31d37786a01.png)



## Batch action + multi-select
![multi-select](https://user-images.githubusercontent.com/11670886/48584803-5e7f5b80-e8f0-11e8-8a11-b227d72266f8.png)

**Comment by aagonzales** [comment]
# Final Data Table Designs

**Sketch File**
https://ibm.box.com/s/cbuttz4st6rt6a53visehc8t3s26b2um

## Row sizes & states
![row size - 24 compact](https://user-images.githubusercontent.com/11670886/49041607-ad03e400-f193-11e8-9adb-6ae18a7240f2.png)
![row size - 32 short](https://user-images.githubusercontent.com/11670886/49041608-ad03e400-f193-11e8-9ae8-7f46da376d07.png)
![row size - 48px default](https://user-images.githubusercontent.com/11670886/49041609-ad03e400-f193-11e8-9cc6-a08bc10f5dab.png)
![row size - 64 tall](https://user-images.githubusercontent.com/11670886/49041610-ad03e400-f193-11e8-89eb-706a5f6083e4.png)
![row states](https://user-images.githubusercontent.com/11670886/49041612-ad9c7a80-f193-11e8-86b9-f1698dfc3e1b.png)

## Row Interactions and styles
### Multi-select / Batch action
![multi-select](https://user-images.githubusercontent.com/11670886/49041783-2ef40d00-f194-11e8-891c-d095d5fd8556.png)
### Expandable 
![expandable selectable](https://user-images.githubusercontent.com/11670886/49041603-ac6b4d80-f193-11e8-8a72-870b4324e421.png)
![expandable rows](https://user-images.githubusercontent.com/11670886/49041604-ac6b4d80-f193-11e8-92c5-601532da97cf.png)

### Icons & overflow menu
![icons overflow menu](https://user-images.githubusercontent.com/11670886/49041605-ac6b4d80-f193-11e8-80ea-206c41654aa6.png)
![overflow menu](https://user-images.githubusercontent.com/11670886/49041606-ad03e400-f193-11e8-9c19-8588d0ca7890.png)

### Zebra stripes
![zebra stripes - hover](https://user-images.githubusercontent.com/11670886/49041618-ad9c7a80-f193-11e8-81b6-2a073ad3e076.png)
![zebra stripes](https://user-images.githubusercontent.com/11670886/49041619-ad9c7a80-f193-11e8-98c3-f7f604db8eee.png)

## Column headers and sort
![column header bar](https://user-images.githubusercontent.com/11670886/49256970-5a763200-f3f6-11e8-99e1-44646b1845ea.png)


## Toolbar & title bar
![titler bar toolbar](https://user-images.githubusercontent.com/11670886/49041617-ad9c7a80-f193-11e8-8088-7b1f0c840d02.png)
![search](https://user-images.githubusercontent.com/11670886/49041614-ad9c7a80-f193-11e8-9fb2-dde194ddb29f.png)

**Comment by eraymond25** [comment]
@aagonzales the toolbar & title bar hover state on icons should match the change that we made to the overflow menu hover state in the row elements examples above
