### ISSUE TITLE
Experimental Component - Tile - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1247]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Tile
Sketch file: https://ibm.box.com/s/4dbnlkp94m4s03ckc6bkqk1nh51xi0d6
- I took off all dropshadows from Carbon tiles and followed styling from Duo that matches the rest of the components we have been making
![tile_light_theme_white](https://user-images.githubusercontent.com/43969356/47171492-77372a00-d2ce-11e8-8f18-a8f8b054d814.png)

**Comment by laurenmrice** [comment]
Ready for dev ✅ @IBM/carbon-developers 
Dev issue: #1282
