### ISSUE TITLE
Fluid inputs: FluidTimePicker

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12475]
https://github.com/carbon-design-system/carbon/issues/12475#tasklist-block-b5fb7b8c-69a9-4516-9023-9dc0c2cf80c3

## Spec

[Sketch](https://ibm.box.com/s/658frh5yaeyzh6ymrplqtbrllwp7vbdw) | [Figma](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=329%3A1710)

![Time-picker - White](https://user-images.githubusercontent.com/11670886/200693481-f3248aa0-e5fb-4ce0-87bc-3a107da7f6c6.png)

**Comment by aagonzales** [comment]
Spec update after development concerns.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/11670886/202216378-bc36968f-b662-4da9-8874-58cbe7b1f75f.png">
