### ISSUE TITLE
Experimental Component - Breadcrumb - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1248]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
[Breadcrumb.zip](https://github.com/IBM/carbon-components/files/2488185/Breadcrumb.zip)
