### ISSUE TITLE
Is there the avatar/persona component with status into carbon react component v11+?

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#12481]
### Question for Carbon

Is there the avatar/persona component with status into carbon react component v11+?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
There is also a recommended "Profile" pattern within the recommended guidance of the Disclosure pattern: https://carbondesignsystem.com/patterns/disclosures-pattern/#profile-menu

This is not something provided in code, but can serve as a guideline for your own implementation.
