### ISSUE TITLE
[Bug]: Theme is not applied to OverflowMenuItem

### ISSUE THREAD

**Issue by stepoibm** [carbon-design-system/carbon#12499]
### Package

@carbon/react, @carbon/icons-react

### Browser

Chrome, Firefox

### Package version

1.16

### React version

18.3.0

### Description

Theme set by <Theme theme="g10"> is not applied to OverflowMenuItem as they are rendered as sibling to the Theme container in body.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-px87be-vz2q7d?file=src%2FApp.jsx

### Steps to reproduce

Click on Filter OverflowMenu, see that the Item is in theme g90 (or similar) wheres Theme is set to g10.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by stepoibm** [comment]
That's exactly what I need. Thank you.

And it's even in the documentation. 
https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--default#data-floating-menu-container

Sorry, my bad and thanks again!

**Comment by tw15egan** [comment]
No worries! Glad it's all working 🎉 💪🏻
