### ISSUE TITLE
Experimental Component - Accordion - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1249]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
@jeanservaas can you post the final designs here or link to the issue and close this one?

**Comment by aagonzales** [comment]
@jeanservaas can you post the final designs here or link to the issue and close this one?

**Comment by jeanservaas** [comment]
[Accordion.zip](https://github.com/IBM/carbon-components/files/2488202/Accordion.zip)
