### ISSUE TITLE
Experimental Component - Link - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1250]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
@jeanservaas can you post the final designs here or link to the issue and close this one?

**Comment by jeanservaas** [comment]
[Link_Revised_Focus 2.zip](https://github.com/IBM/carbon-components/files/2488201/Link_Revised_Focus.2.zip)
