### ISSUE TITLE
Add TypeScript types to DataTable

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12515]

**Comment by mbarrer** [comment]
Starting work on this one

**Comment by mbarrer** [comment]
After working through this one a bit, its probably better to start with the smaller table components first as this component will reference types found in these smaller components

**Comment by djragsdale** [comment]
There's only a few related components yet to be upgraded to TS. I went ahead and took a go of it in #14149, attempting to change as little as possible within the actual code. Not having the renderProps defined was getting particularly frustrating.
