### ISSUE TITLE
Experimental Component - Tags - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1254]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
# Tags
- **Sketch file:** https://ibm.box.com/s/2awci8spqzx0re4jqwujxuqo3f9w82m1
- I've included additional functionality in the Sketch file but wasn't sure if we'd add it in for these updates. Security does have the dismissible version.
- The color versions should be pulled from the Duo palette. 

![tag](https://user-images.githubusercontent.com/11670886/47114247-eb1af900-d220-11e8-955a-f558a523608c.png)

**Comment by aagonzales** [comment]
Ready for dev ✅@IBM/carbon-developers 
Dev issue: https://github.com/IBM/carbon-components/issues/1279
