### ISSUE TITLE
Add TypeScript types to Search

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12553]

**Comment by alberteddu** [comment]
[This](https://github.com/carbon-design-system/carbon/pull/13533) one seems to close this?

**Comment by ljcarot** [comment]
@tay1orjones ^ see last comment.  True or no?

**Comment by tay1orjones** [comment]
Yes, sorry we missed this! Closed via https://github.com/carbon-design-system/carbon/pull/13533
