### ISSUE TITLE
Experimental Component - Form - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1256]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
## Form

Sketch File: https://ibm.box.com/s/3mdq5to6fugtm07ne8i09krfzw6mk87q
- Form pulls in field components; Carbon provides some usage for the larger pattern, but mostly approaches it as a kit of parts.
- Included an example of multi-column pattern at every breakpoint
- Security has no Form component

![form_white_theme](https://user-images.githubusercontent.com/43144260/48099268-a9a8b880-e1e4-11e8-9f45-91f894458f57.png)

![form_specs](https://user-images.githubusercontent.com/43144260/48099276-b0373000-e1e4-11e8-8b0e-c7c52a103c5f.png)

![form_scaling usage](https://user-images.githubusercontent.com/43144260/48099287-b7f6d480-e1e4-11e8-982f-d24838e9b73f.png)
