### ISSUE TITLE
Experimental Component - Loading - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1257]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
# Loading design

**Sketch file:** https://ibm.box.com/s/57ncx15w6t8o290jf04i33gtw3vx9sll

![loader](https://user-images.githubusercontent.com/11670886/47323416-569a0780-d621-11e8-8ba8-35f78e08cafe.png)

**Comment by aagonzales** [comment]
Ready for dev ✅ https://github.com/ibm/carbon-components/issues/1298
