### ISSUE TITLE
Provide a Create React App template

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12598]
It would be nice if a [custom Create React App template](https://create-react-app.dev/docs/custom-templates/) was available so that it's easy for someone to spin up an app with everything you need to start building with Carbon.

https://github.com/carbon-design-system/carbon/issues/12598#tasklist-block-49af797d-07de-4411-b72a-73d917372f3d

Ideas of what to include the template:
- Model the design off the carbon tutorial
- Include theme switching example as part of it
- UIShell with a basic CSS Grid layout
- Use a Stack within Grid
- Provide basic unit tests
  - Could we use this CRA template and it's tests as a way to smoke test new releases?
- Include some different examples of Popover usage

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : I would like to work on this issue.

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : 

- I used the tutorial design and content to create a template. 
- I included an option to switch themes on the header component. 
- I've also written unit test for the components. 

Let me know, if you want me to include any other features as part of the CRA template

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/56068832/210359245-a464b7b2-d057-4b9c-864d-d6951aac07cb.png">

**Comment by tay1orjones** [comment]
@Shankar-CodeJunkie Looks like a great place to start! Could you put it up in a PR for a more thorough review by the development team and design team?

It will need to be in it's own package folder, `packages/cra-template`, and added to the workspace. I can collaborate on the PR with you to ensure it's hooked into our release flow so we can publish it to `@carbon/cra-template` on npm.

**Comment by sstrubberg** [comment]
@Shankar-CodeJunkie this is spectacular! Let us know how we can support you. Amazing contribution :)

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones :  I don't find packages/cra-template in the codebase.  I find one cra-template folder  in the path `packages/react/examples/create-react-app`.

Should I replace that folder with my template folder contents.

**Comment by tay1orjones** [comment]
Yeah since this is a new package the `packages/cra-template` directory will need to be created.
