### ISSUE TITLE
Experimental Component - Inline Loading - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1259]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by aagonzales** [comment]
## Inline loading designs

**Sketch:** https://ibm.box.com/s/57ncx15w6t8o290jf04i33gtw3vx9sll

![inline-loader](https://user-images.githubusercontent.com/11670886/47323460-81845b80-d621-11e8-9482-512930420a24.png)

**Comment by aagonzales** [comment]
Ready for dev ✅https://github.com/IBM/carbon-components/issues/1299
