### ISSUE TITLE
[Feature Request]: request to add "Select all" to `TableBatchActions` component

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon#12595]
### The problem

Hello! The DSAG group/Carbon for IBM Products team has data table designs that call for including a "Select all" button next to the `totalSelected` prop (`x items selects`) text within the TableBatchActions component. We are hoping that this could potentially be an optionally included piece to the TableBatchActions component.

Here is some design guidance provided by @marion-bruells:
> When dealing with large amount of data, users sometimes require to select items across all pages, not only the current one. We added this button as extension, so when the user clicks on Select all, all items in this table are selected (across all pages). When the user performs an action now, all pages are affected. The default is that only items on the current page are selected. To exit or escape the batch action mode, the user can cancel out or deselect the items with the checkbox in the column header. See guidance [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/batchactions/usage/#actions-across-multiple-pages
). You probably know a similar behaviour from gmail and other tools.

### The solution

_Being able to optionally include a select all button to render next to the `totalSelected` text inside of the TableBatchActions component_
![Screenshot 2022-11-10 at 10 49 18 AM](https://user-images.githubusercontent.com/10215203/201132531-da1e71a8-93bd-4331-8693-26aef1edb104.png)

### Examples

Here is another example, from gmail.
![Screen Shot 2022-11-10 at 10 16 00 AM](https://user-images.githubusercontent.com/10215203/201133679-939b8da2-5505-4130-aa06-6626cfda0a73.png)

### Application/PAL

Carbon for IBM Products

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

https://pages.github.ibm.com/cdai-design/pal/components/data-table/batchactions/usage

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by matthewgallo** [comment]
Our team was hoping to also have this included as part of v10 and v11, if possible.

**Comment by sstrubberg** [comment]
@matthewgallo you wouldn't happen to be available to contribute.. would ya? ;)

**Comment by matthewgallo** [comment]
We'd be happy to contribute but it will likely have to be in the new year. Thanks @sstrubberg!

**Comment by sstrubberg** [comment]
> Our team would be happy to contribute but it will likely have to be in the new year. Thanks @sstrubberg!

Excellent! Let's get together and talk Acceptance Criteria after the holidays.

**Comment by sstrubberg** [comment]
From DataTable backlog grooming call:

Design needs to weigh in on this pattern. It needs specs. Core Carbon should own, but anyone could contribute it.

**Comment by tay1orjones** [comment]
@matthewgallo Just to clarify - is this request to just better support rendering the button, or are you asking for the actual Select All functionality to be built into DataTable?

**Comment by elycheea** [comment]
On a call with @matthewgallo right now — I think we just need to support the rendering. We already have the logic for select all on our side. @matthewgallo may have some time to contribute this soon though. 🤞

**Comment by matthewgallo** [comment]
Would love to contribute this as our designs still require this approach, see `[here](https://github.com/carbon-design-system/ibm-products/issues/3365)`.
