### ISSUE TITLE
[Bug]: open prop in OverflowMenu component is not working

### ISSUE THREAD

**Issue by erzhan-temir-mamyrov** [carbon-design-system/carbon#12611]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.56.0

### React version

v16.14.0

### Description

`OverflowMenu` component has a prop `open` that renders menu by default. However, if this prop is set to `true` the component throws an error.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPgyQGNPwBGFBTRUoKDWnAXyMIjZO26DRk2fIWEo8Q5Cynh8gUIGnJPey0QAF9o2QhyNgAPYk9qOgt1AB1yAAJsiFNSflpsgCUhW2ywflVsgHIbWlqAbizc_LMi7OBswXiYfmzIyuqVOoalVWbWvILO2v8XVTcPAHoMODg1vQDjJfNGOAIVOIJ1uCmcmY7i7oB5ADd-sChSAHcAWQYAV2lsh6eXh9vgBJeijIZVGrzbaLAruA7WcqNFqXLLTEJSbIAQRQKGyAF5sgAKACUBIAfMTptNcgAef78Z5vT7kL403LZFgSNAKJkSOK4BQqb67RhoOL9dm5OAwWC2QoABX4-T0AE8AGKkDBfOD44C1AikFC0CAUW7uWqRdnkqXZemPRmAllfUEwFS23IYcQbAByaGF-IyICNJrN7iDHryYIAKjAErRAyBbsbTTkAIwRy4c7IrG1Zjn2gHMkFgyNetC-_0wRMh1PR16kTPZ7MQGNxhNB5OhnIAJjycGyaBycf9KFg2VIYEHPSEUCgquyL3IuGyUmVy8H8WyAAs3tlXjAZyZhVvt0OWFABdlaNuIHAm83coIAI5fCCCaOt2C23O2wuO4tWVdUZWzdWN40TLtU2yABmIMczzR9_yZIEgLBKMwPbSCUwobIABZ4LPOAABEIHuCA2H4X981pFYGRQ51EOyaYSRRaZekoolaRxPFc1-ZRtRPWgCHwWgAFFYCEgAhVVgRYIl6lIUhGhJVisiiWI-iSbdaBUKBmBCehGHUWkWDIvIWETaplKDclaLM-5ySiaIgA

### Steps to reproduce

- Go to [this CodeSandbox](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPgyQGNPwBGFBTRUoKDWnAXyMIjZO26DRk2fIWEo8Q5Cynh8gUIGnJPey0QAF9o2QhyNgAPYk9qOgt1AB1yAAJsiFNSflpsgCUhW2ywflVsgHIbWlqAbizc_LMi7OBswXiYfmzIyuqVOoalVWbWvILO2v8XVTcPAHoMODg1vQDjJfNGOAIVOIJ1uCmcmY7i7oB5ADd-sChSAHcAWQYAV2lsh6eXh9vgBJeijIZVGrzbaLAruA7WcqNFqXLLTEJSbIAQRQKGyAF5sgAKACUBIAfMTptNcgAef78Z5vT7kL403LZFgSNAKJkSOK4BQqb67RhoOL9dm5OAwWC2QoABX4-T0AE8AGKkDBfOD44C1AikFC0CAUW7uWqRdnkqXZemPRmAllfUEwFS23IYcQbAByaGF-IyICNJrN7iDHryYIAKjAErRAyBbsbTTkAIwRy4c7IrG1Zjn2gHMkFgyNetC-_0wRMh1PR16kTPZ7MQGNxhNB5OhnIAJjycGyaBycf9KFg2VIYEHPSEUCgquyL3IuGyUmVy8H8WyAAs3tlXjAZyZhVvt0OWFABdlaNuIHAm83coIAI5fCCCaOt2C23O2wuO4tWVdUZWzdWN40TLtU2yABmIMczzR9_yZIEgLBKMwPbSCUwobIABZ4LPOAABEIHuCA2H4X981pFYGRQ51EOyaYSRRaZekoolaRxPFc1-ZRtRPWgCHwWgAFFYCEgAhVVgRYIl6lIUhGhJVisiiWI-iSbdaBUKBmBCehGHUWkWDIvIWETaplKDclaLM-5ySiaIgA)
- Add `open` prop to `<OverflowMenu />` component
- See an error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@erzhan-temir-mamyrov I can't reproduce the issue in the sandbox you linked, but I was able to reproduce here https://codesandbox.io/s/cool-fire-isc7uk?file=/src/index.js

This is also an issue in v11 https://stackblitz.com/edit/github-4n2wef?file=src%2FApp.jsx

**Comment by tay1orjones** [comment]
It looks like it's isolated to initial render only. A workaround for now would be to render the component without `open`, then placing `open` on as this seems to work within the sandboxes.
