### ISSUE TITLE
[Bug]:: Change role on calendar container to 'application' in DataPicker missing from npm registry

### ISSUE THREAD

**Issue by luizas** [carbon-design-system/carbon#12618]
### Package

carbon-components-react

### Package version

v7.57.4

### Description

 Change role on calendar container to 'application' in DataPicker missing from npm registry.  We are using carbon-component-react  v7.57.4. /Carbon  v10.58.0 and role is equal region in DataPicker.js in our node_modules/carbon-components-react. I checked plain package with the same result (screenshoot)
<img width="1611" alt="Screenshot 2022-11-14 at 17 20 55" src="https://user-images.githubusercontent.com/18647438/201881784-386a62b5-86ae-4e35-852f-668b9893ee54.png">
<img width="1226" alt="Screenshot 2022-11-15 at 09 26 46" src="https://user-images.githubusercontent.com/18647438/201882160-2634a35b-d1be-4a14-b0c3-f8bcdd05ec42.png">

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

-

### Steps to reproduce

1. npm i carbon-components-react@7.57.4
2. check role in DataPicker.js file 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Is it possibly resolving to a different version? I see that the change was backported to v10 [here](https://github.com/carbon-design-system/carbon/pull/11838), and I can see the change when inspecting the codebase locally. I also see the change when inspecting the `v10` [branch in GitHub](https://github.com/carbon-design-system/carbon/blob/v10/packages/react/src/components/DatePicker/DatePicker.js#L475)

**Comment by luizas** [comment]
Hi @tw15egan I also can see changes in branch and in release zip, but not in npm registry version. what version I can use to resolve that problem ? We can't upgrade to Carbon 11 and all v10 above 10.58 have tag pre-release

**Comment by tw15egan** [comment]
It's [showing up](https://unpkg.com/browse/carbon-components-react@7.59.5/es/components/DatePicker/DatePicker.js#:~:text=_this.cal.calendarContainer.setAttribute(%27role%27%2C%20%27application%27)) on the latest version of `v10`, I would try updating to `7.95.5` (react) and `10.58.5` (carbon-components). Hope that helps!

**Comment by tay1orjones** [comment]
> all v10 above 10.58 have tag pre-release

`v10-next` is the intended tag to track if you're wanting to follow v10/v7 releases. We will not be marking these as `latest` because v11/v8 is truly the `latest`.

> `npm i carbon-components-react@7.57.4`

this will install that specific version, instead make sure to use a caret range:

`npm i carbon-components-react@^7.57.4`

This should allow you to take on new minor versions within the v7.x scope by running `npm update <packagename>`. You can alternatively manually change the caret range in your package.json to `^7.59.5` and then run `npm install` to get the new version.
