### ISSUE TITLE
Data table should provide option of server side pagination and server sorting,filtering

### ISSUE THREAD

**Issue by adangar99** [carbon-design-system/carbon#12620]
Current data table not provide server side pagination and sorting/filtering facility, Data should also accept as function and provide params like (limit, sortCol, sortDirection, and filter options ) also pagination should work on server side to improve performance. 

Also if you are able to add cursor pagination option that will help a lot to developers

**Comment by sstrubberg** [comment]
@adangar99 Would you be open to creating an issue using our [template for bugs](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9B&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+)? It will help us greatly in triaging your issue. Closing this one for now :)
