### ISSUE TITLE
Experimental Component: Primary Link — Development (Focus state revision)

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1263]
Digital / Brand Teams noticed problems with the focus state of the Primary Link. It was previously and underline that was causing problems for them if the link was breaking to two lines.

They redesigned the focus state to fix. See attached.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/6cec01a4-44cf-4b6b-a182-4b950122bc2a)

[https://app.zenhub.com/files/84835535/3283db76-c104-4513-82d0-185c0b70507b/download](https://app.zenhub.com/files/84835535/3283db76-c104-4513-82d0-185c0b70507b/download)

**Comment by joshblack** [comment]
@jeanservaas are they sure they want this as the focus state? As a heads up, it will appear when a user is interacting with the link, not just with keyboard focus. So any time they click on it this box will appear.

**Comment by jeanservaas** [comment]
@joshblack @aagonzales Let's hold on this and discuss Monday... we have a few other things to hash out Monday morning too. I want to ask Erica more about the change and I want to run it by Anna. 

ps, are you talking about Chrome when you say this "...it will appear when a user is interacting with the link, not just with keyboard focus." ?

**Comment by jeanservaas** [comment]
FYI this focus state change would also affect Breadcrumb

![image](https://user-images.githubusercontent.com/43144260/46895355-a1579a80-ce3d-11e8-8ccc-87572f929b42.png)

**Comment by jeanservaas** [comment]
@joshblack -- is this issue just a Northstar (Drupal) thing? If so maybe it won't affect us... and then we won't need this update. Can we double check this with them?

**Comment by joshblack** [comment]
@jeanservaas just wanted to note that when we say focus indicators that they will appear when someone uses a keyboard or mouse to interact with the component.

Example link: https://codepen.io/joshblack/full/aREqaw

If you press tab the outline will appear, in addition to when you click it.

**Comment by aagonzales** [comment]
I think we all agree the underline is a better solution but it sounded like Northstar was having some technical difficulties with the style which is why they changed it. We just changed it to stay consistent. @joshblack were you running into any issues with it (the underlined version). Or would you know what could be their problem?

**Comment by joshblack** [comment]
Definitely no issues! Just wanted to make sure folks were aware 👍

**Comment by jeanservaas** [comment]
@joshblack @aagonzales Apparently it's not a Drupal thing. Here's the issue from the Digital team about the focus state:
https://github.ibm.com/webstandards/digital-design/issues/48

Scroll down to this comment by @santelia on Aug 24:

![image](https://user-images.githubusercontent.com/43144260/47159150-d2f3ba00-d2b2-11e8-97a0-fa0afca8780d.png)

and the subsequent link showing the problem:

http://jsfiddle.net/ecumike/bq5zn8wc/1/

**Comment by tw15egan** [comment]
Link to the article, FYI. Helps point out the technical restraints

https://css-tricks.com/styling-underlines-web/

**Comment by joshblack** [comment]
@IBM/carbon-designers is this focus state ready to go?

**Comment by asudoh** [comment]
CC @dakahn
