### ISSUE TITLE
[Feature Request]: unavailable icons, Telegram and WhatsApp, programming languages, payment icons

### ISSUE THREAD

**Issue by a1y-ir** [carbon-design-system/carbon#12660]
### The problem

hi, in the website of [carbon-design-system/carbon-icons-svelte](https://github.com/carbon-design-system/carbon-icons-svelte) repository, which is [this](https://carbon-icons-svelte.onrender.com) I can't find Telegram and WhatsApp logo icons. is it something about svelte repository or its not included in carbon design system icons? also there is Python icon, but other programming languages icon are not available (go, C++, rust, php, Js, Ts, dart, etc...). payment icons (money, bill, wallet, gateway, bank, shop, etc...) are also unavailable.

### The solution

it will be nice if we have these on next versions.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by sstrubberg** [comment]
@laurenmrice's reply: https://github.com/carbon-design-system/carbon-design-kit/issues/599#issuecomment-1317235067
