### ISSUE TITLE
[Bug]:  NumberInput error if min or max props are not present

### ISSUE THREAD

**Issue by darioplatania** [carbon-design-system/carbon#12695]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.17.0

### React version

17.0.1

### Description

Using the NumberInput component, the onChange function doesn't work, it returns the following error 'Warning: Received NaN for the value attribute. If this is expected, cast the value to a string'.

I looked at the following issue #11926, where a user had the same problem and in the CodeSandbox posted as a solution, it seems to work. However, I realized that in the working solution min & max props are present and are missed in the non-working solution.

Looking closely at your code, I noticed that in the NumberInput.js component if the min and max are not passed as props, they are not assigned any default value. In my case, I didn't have a value of max and so this causes the onChange to fail.

Looking at the documentation, the min and max props are optional and therefore this causes the user this error, without being able to understand the reason for the NaN.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/upbeat-sinoussi-wgmqg1?file=/src/App.js

### Steps to reproduce

The error occurs if either min or max is not set.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by vasharma05** [comment]
Hi team, 
I am working on the OpenMRS 3.0 and I am facing the same issue as is opened by @darioplatania. Thanks @darioplatania for opening up the issue.

I wanted to ask, is there any progress on the issue here?
Thanks!

**Comment by tw15egan** [comment]
No progress has been made, but the team would welcome a PR to fix this. EIther need to make the `min` and `max` props `required` or give them a sane reasonable default value.

**Comment by darioplatania** [comment]
Thanks @tw15egan for the reply. An idea could be this: leave `min` and `max` as optional props and give the min value to _0_ and max value to _100_.  

This solution also produces a change in the component documentation, to inform the user of the assigned default values.

**Comment by tay1orjones** [comment]
Resolved via https://github.com/carbon-design-system/carbon/pull/12768

**Comment by tay1orjones** [comment]
Reopened due to https://github.com/carbon-design-system/carbon/pull/13244 - the original PR had to be reverted

As discussed in https://github.com/carbon-design-system/carbon/pull/12768#issuecomment-1346878358, NumberInput should not assign any default props to min and max and instead handle the undefined case in the clamp function.
