### ISSUE TITLE
[Bug]: Data Table - Sorting and null

### ISSUE THREAD

**Issue by JOwens818** [carbon-design-system/carbon#12696]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.15.0

### React version

17.0.2

### Description

DataTable component with 'isSortable' = true...  Sorting works as expected as long as there are no null values in a given column.  However if there are null values present in the column an error gets thrown in the console and sort functionality does not do anything.  See attached for error and reproduction example.  In the Stackblitz example I tried with both 1.15.0 and 1.17.0.  

![dataTableError](https://user-images.githubusercontent.com/36175299/202724456-bbefa168-bb84-44f2-a8ce-5727ad3d3d0b.png)

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-9h9nvq?file=src/App.jsx

### Steps to reproduce

Run the app and try to sort on a column that has null values (DEPTNAME).  You will notice that sorting on DEPTCODE still works.

Interestingly enough, if I remove the TableSelectRow functionality the sort appears to work again on DEPTNAME...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I see the bug as well. As a workaround, it seems to work if you pass in an empty string: https://stackblitz.com/edit/github-9h9nvq-lvtpgo?file=src%2FApp.jsx

**Comment by jsehull** [comment]
Hey team - I've been working on a fix and would like to be assigned to this issue

**Comment by tw15egan** [comment]
@jsehull excellent, we would welcome any PR to fix this. Thanks for taking this on

**Comment by jsehull** [comment]
@tw15egan my PR is mentioned above this comment, but do I need to manually link the PR to the Issue or the Issue to the PR under Development (right sidebar)?
