### ISSUE TITLE
[Question]: Divergent values from documentation and implementation

### ISSUE THREAD

**Issue by mgaseta** [carbon-design-system/carbon#12710]
### Question for Carbon

Hi folks!

I'm working in a project that is using Carbon V11 as the base for our Design System and I noticed a thing related to the typography.

Our design team is creating the screens and components on Figma using a Carbon V11 template, so they are basing everything on the typography values there (which are the same as the [documentation](https://carbondesignsystem.com/guidelines/typography/type-sets)).

But when implementing the values are different, for instance the `h1` tag:

It maps to the `heading-06`, so the line should have the value 3.125rem for height.
As in: 
![image](https://user-images.githubusercontent.com/105936322/203381552-48ebeba1-b326-4748-9221-e48203cde802.png)

But, in reality, it has a height of 1.199rem as defined on @carbon\type\scss\_styles.scss:
![image](https://user-images.githubusercontent.com/105936322/203381973-982726cc-deb7-4b87-9906-b16fa27c2358.png)

Also, this 1.199 value doesn't come from any other fluid typography token.

This is just an example to bring attention to the problem.

So, my question is: am I using something wrong here? Maybe left something behind on the documentation? Is there someone who can help me?

If this is a real issue, it either needs to update the documentation or the code, to avoid wrongly designed pages (i. e. design team designs a page expecting typography to behavior a certain way and when the dev team implements it, it will be off).

Thanks so far!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
>But, in reality, it has a height of 1.199rem as defined on https://github.com/carbon\type\scss_styles.scss:

Hey there, @mgaseta , we use unitless `line-height` values. If you inspect the code, you can see that it is computing to the correct value (the browser rounds down to the nearest pixel). That 1.199 is not set in `rems` but is a unitless value that the line-height should scale on, e.g `2.625rem --> (42px) * 1.199 = 50.358 (3.15rem)`


<img width="806" alt="Screenshot 2022-11-22 at 1 03 29 PM" src="https://user-images.githubusercontent.com/11928039/203388316-9a052502-5d54-4a41-948b-b5b7b409b956.png">


[type token site](https://deploy-preview-12603--carbon-elements.netlify.app/type/examples/preview/)

Here are some articles with some more information regarding this:
http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/

https://allthingssmitty.com/2017/01/30/nope-nope-nope-line-height-is-unitless/

**Comment by mgaseta** [comment]
Hey @tw15egan , thanks for the clarification! 

It helps a lot!

May I suggest adding simple mention on the documentation (maybe on the read.me, which is more technical) saying that Carbon uses unitless height to avoid any future confusions?

Thanks again!

**Comment by tw15egan** [comment]
Definitely, glad this cleared some things up 👍🏻
