### ISSUE TITLE
[Bug]: Notification (Inline+Toast) text color issue

### ISSUE THREAD

**Issue by FZilli** [carbon-design-system/carbon#12718]
### Package

@carbon/styles, carbon-components, @carbon/colors

### Browser

Chrome

### Package version

v11

### Description

Text is not readable when using "Low contrast" notifications with theme "g100"

### Screenshots

![image](https://user-images.githubusercontent.com/50174433/203570970-0277aba2-36ba-4e51-9e0b-6b714320bba7.png)

### Steps to reproduce

1. Visit one of the following story books
2. Access either inline or toast notifications
3. Set "low contrast"
4. Set theme "g100"

Text won't be seen unless a selection is performed

https://web-components.carbondesignsystem.com/?path=/story/components-notifications--inline
https://vue.carbondesignsystem.com/?path=/story/components-cvinlinenotification--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Seems like it is working in this repo: https://react.carbondesignsystem.com/?path=/story/components-notifications-inline--playground&args=lowContrast:true&globals=theme:g90

Is this issue isolated to the web-components or vue repos? If so, I would create an issue there

**Comment by FZilli** [comment]
Moved issue to dedicated repo, thanks!
