### ISSUE TITLE
[Bug]: Carbon-Components-React: Select component doesn't seem to return anything onChange

### ISSUE THREAD

**Issue by TimErdmann87** [carbon-design-system/carbon#12739]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.10.3

### React version

16.8.6

### Description

**Expected:**
- onChange returns information about the change made, especially the selected SelectItem

**Observed:**
- only returns a synthetic event in the browser but no information about the change/component which renders this component useless to integrate in responsive web apps based on React (thus, pretty much every React app) -> really frustrating for developers
- better documentations are also needed in general for (almost) all components (see other React UI libraries)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

See description, it's a very basic issue.

### Steps to reproduce

See description, it's a very basic issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there, @TimErdmann87; it would be helpful if you included a reproduction via [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v10/packages/react/examples/codesandbox) or [Vite](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx) and I'd be happy to take a look. 

That being said, version `7.10.3` is over three years old, so a good first step would be to upgrade to a newer version ([7.59.5](https://www.npmjs.com/package/carbon-components-react/v/7.59.5) if you are still on v10) and see if the issue still occurs. Thanks!
