### ISSUE TITLE
Datatable expandable rows don't update on sort

### ISSUE THREAD

**Issue by cyrusfurtado** [carbon-design-system/carbon#1273]
## Detailed description
On sorting a Datatable with expandible rows. The markup for the inner expandible child rows do not get updated upon calling `refreshRows()` on the table instance.

> Is this issue related to a specific component? Yes, http://www.carbondesignsystem.com/components/data-table/code

> What did you expect to happen? Expected the markup within the expandable rows to get updated with all angular bindings working
What happened instead? I see the same old markup within expandable rows before the sort in the UI
 What would you like to see changed? The table should get updated with the sorted expandable row markup as well.

> What browser are you working in? firefox, chrome

> What version of the Carbon Design System are you using? "carbon-components": "^9.8.4"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? BDS dashboard

## Steps to reproduce the issue

1.  Instantiate the table with an array of data with `expandible` rows
2.  Sort the array
3.  Call tableInstance.refreshRows() to update the UI

## Additional information
Added link here. This is an angular 5 app btw.

- https://codesandbox.io/s/pkpvmwvrwj

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by cyrusfurtado** [comment]
Have made a temporary fix for this. Since i need to modify files installed directly by npm might probably need to have the entire `carbon-components` repo locally available in my `src` folder for now.

**Comment by asudoh** [comment]
Hi 👋 thank you for the update - You don't need to modify Carbon code directly for your temporary fix. You can do something like below instead:

```javascript
import { DataTableV2 } from `carbon-components`;

class MyDataTableV2 extends DataTableV2 {
  refreshRows() {
    (Your code for refreshRows())
  }
}

...

MyDataTableV2.create(myTableElement);
```

Hope this helps!

**Comment by cyrusfurtado** [comment]
Thanks for the update.

**Comment by cyrusfurtado** [comment]
@asudoh .Does this work with typescript.
