### ISSUE TITLE
[Bug]: Tailwind classes not affected

### ISSUE THREAD

**Issue by fegyi001** [carbon-design-system/carbon#12733]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.17.0

### React version

v18.2.0

### Description

I try to combine Carbon React components with some Tailwind. 
My problem is: if I add any Tailwind classes to e.g. a Button component, it does not affect it at all.

Here is my React button with added Tailwind classes:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/4125222/204300341-beec5f6f-9973-4c08-93dc-0fe2348fde3f.png">

Here is the result:
<img width="164" alt="image" src="https://user-images.githubusercontent.com/4125222/204300446-d214c234-c9a7-4ee1-b2f0-53df798396ee.png">

If I add manually these css selectors in the browser (the equivalents of the Tailwind classes):

```css
{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    width: 12rem;
    padding: 1rem;
}
```

It looks like this which is the desired output:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/4125222/204301168-80a82577-92f2-4832-ae23-147061d694ef.png">

I'm quite new to Carbon React and Tailwind as well. Any help is much appreciated!

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

see in the example above

### Steps to reproduce

see in the example above

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I'm guessing our CSS selectors have higher specificity over Tailwinds selectors and are overwriting their styles
