### ISSUE TITLE
Experimental Component - Structured List - Development

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1275]
##### Development
A developer can discover and install the experimental component by following accessible documentation.

- [x] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
##### Development
A developer can discover and install the experimental component by following accessible documentation.

-[ ] Add to carbon-components
-[ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
Design issue: #1242
Sketch file: https://ibm.ent.box.com/file/332823096737

**Comment by aledavila** [comment]
linked the wrong one to tag. have closed tag
