### ISSUE TITLE
UX specs for character counter in TextInput

### ISSUE THREAD

**Issue by sibendudey** [carbon-design-system/carbon#1278]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Please describe your request in one or two sentences.

I would like some reviews on this solutions regarding UX specs for displaying a character count in TextInput component. 

1. 
![image 1](https://user-images.githubusercontent.com/4667493/47129708-6eaa0980-d264-11e8-954b-d2861252eea8.png)

**Comment by asudoh** [comment]
@IBM/carbon-designers I guess we need more info, such as color, font size, padding, etc... for this kind of review. Is it correct...? Thanks!

**Comment by designertyler** [comment]
Hi @sibendudey when I first saw this I wondered if we could use the helper text (validation message) we use when the field has an error. [Here](http://carbondesignsystem.com/components/text-input/code)

This way when the character limit is exceeded the type treatment and location is consistent with other error messages. 

I mocked this up real quick to show the valid and invalid states. 

Any thoughts or feedback? Carbon designers? 

<img width="367" alt="screen shot 2018-10-18 at 9 54 52 am" src="https://user-images.githubusercontent.com/19270502/47164172-1b17da00-d2bd-11e8-867b-ccc81607c841.png">
<img width="383" alt="screen shot 2018-10-18 at 9 58 33 am" src="https://user-images.githubusercontent.com/19270502/47164173-1b17da00-d2bd-11e8-89dd-c3d468bb951d.png">

**Comment by sibendudey** [comment]
@designertyler Well my requirement is not allowing the user to type any more characters once the limit is reached. If I show the user, any message such as "The maximum number of characters is 128" with the red colored bar, it kind of creates an impression to the user that he has entered an input with invalid length, even though he is under the character limit.

**Comment by emyarod** [comment]
related https://github.com/IBM/carbon-components/issues/1672

**Comment by asudoh** [comment]
Let's track the effort in #1672 for now.

**Comment by karl-sandbach** [comment]
Hi, I'm looking add in a comment field into my design with character count included (Similar to the one designed by IBM), with so much focus on accessibility, how do you expect the voiceover/talkback to work with the character count outside of the text input?
