### ISSUE TITLE
[Feature Request]: Dark teal color for tags

### ISSUE THREAD

**Issue by cjcarpen** [carbon-design-system/carbon#12785]
### The problem

We allow users to add a tag to content in the IBM Cloud docs. A main use case for the tags is to tag paragraphs of content to provide additional explanation for content within an architecture diagram. 

Architecture diagrams follow the guidance from the IBM IT Architecture Diagrams project https://github.com/IBM/it-architecture-diagrams. For consistency across products, there's a recommended color scheme for categories of architecture diagram components that's based on the IBM Design Language (e.g. Compute = Green, Network = Cyan, etc.). Because the colors are based on the IBM Design Language, in general the existing tag colors align well for users to use a tag of the same color to reference content in their architecture diagram. However, the problem is that the color scheme uses the teal family twice; a medium teal for "Management" and a dark teal for "Virtual Private Cloud". The existing teal tag color aligns well with the "Management" color recommendation, so we need a new dark teal tag color for VPC.

### The solution

Create a dark teal tag to align with the IT Architecture Diagrams recommendation. The following specs were provided by design:

Light mode (Gray 10)
- Teal 70 
- Teal 80 (hover)

Dark mode (Gray 100)
- Teal 20
- Teal 10 (hover)

### Application/PAL

IBM Cloud documentation framework

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
hey @cjcarpen, i checked with @carbon-design-system/design and we won't be able to do this at the system level. If we did, we would need to make a whole suite of high contrast tags for each theme and not just one dark teal tag.

We have a light teal tag that matches the rest of the tag colors already. If your team needs this feature for your release, we encourage you to extend Carbon as you see fit. Let us know if you need anything else!
