### ISSUE TITLE
[ContainedList]: Persistent search: Have a persistent search bar above list rows.

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12801]
This issue is for implementing search functionality in the contained list.

Design spec: https://github.com/carbon-design-system/carbon/issues/12330

### Acceptance criteria
- [x] Search bar is persistent, below title and above items
- [x] Typing in the search bar would filter the children list items based on a simple text match search (like FilterableMultiSelect)
- [x] Removing/clearing the value from the search bar would "reset" the component to show all children rows
- [ ] Provide `onChange` handlers for search so async actions can be taken
- [ ] Support search initial state - render filtered items based on initial search value
- [ ] Should it provide a `filterItems` type of function to allow for overriding the search behavior? What if it's not a simple text node in the list item? Do we allow non-text nodes as children items/rows?

**Comment by tay1orjones** [comment]
@laurenmrice @janhassel I just added some initial acceptance criteria to this issue. Let me know your thoughts - anything missing, or things we don't need?

**Comment by laurenmrice** [comment]
If `filterItems` makes it more flexible and easier for teams to improve the search functionality for their use cases within contained list, then I would say we should include that. But I will defer to dev.
