### ISSUE TITLE
[Bug]: Fluid Input labels should scroll when text is long instead of breaking to new line

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#12825]
### Package

@carbon/styles

### Browser

Chrome

### Package version

Latest

### Description

Refs https://github.com/carbon-design-system/carbon/pull/12737#pullrequestreview-1211952102

WRONG: 
![image](https://user-images.githubusercontent.com/11928039/206760272-27a47226-2b85-4e50-a8ca-b6c9db383d01.png)

Components that need to be updated:

- [ ] FluidComboBox
- [ ] FluidDatePicker
- [ ] FluidDropdown
- [ ] FluidMultiSelect
- [ ] FluidNumberInput
- [ ] FluidSelect
- [ ] FluidTextArea
- [ ] FluidTimePicker

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

Storybook

### Steps to reproduce

Add text to label

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Pulled this down to a sev2 since they're all still experimental
