### ISSUE TITLE
[Bug]: Update number input type token

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#12826]
### Package

@carbon/react

### Package version

current version

### Description

We want to change number input from using the monospaced `$code` token to just the regular `$body-compact-01`

### Screenshots

<img width="341" alt="image" src="https://user-images.githubusercontent.com/11670886/206779981-1114db44-f760-4834-93eb-edb706d60621.png">

### Steps to reproduce

Go to https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
This change has been bundled as part of https://github.com/carbon-design-system/carbon/pull/12737
