### ISSUE TITLE
Tabs: provide dismissable tabs with descriptive icon tab layout helper/component

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12845]
This issue is for ensuring that the presentational/descriptive icon (delivered in https://github.com/carbon-design-system/carbon/issues/12844) and dismissible feature (delivered in https://github.com/carbon-design-system/carbon/issues/12813) for tabs work together as shown in [the spec](https://github.com/carbon-design-system/carbon/issues/8487#issuecomment-1020664248)

This probably needs to be completed after dismissable and presentational icons are both delivered.

**Comment by francinelucca** [comment]
Currently blocked by design considerations on https://github.com/carbon-design-system/carbon/pull/13529
