### ISSUE TITLE
TextArea warning state: update website docs

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12869]
Confirm that warning state is in the fluid branch

**Comment by aagonzales** [comment]
Warning state is already a part of the text input docs. Text area currently does not have its own dedicated state section but shares one with text-input.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11670886/223238715-91b22c46-1d0f-4cb1-ac66-be6b1d7ac0f4.png">
