### ISSUE TITLE
[Question]: How to change carbon colors ? 

### ISSUE THREAD

**Issue by jbwaring** [carbon-design-system/carbon#12889]
### Question for Carbon

Dear Carbon Community, 
I would like to change colors that are used throughout the design system for example when using: 
`@use '@carbon/react';`.
For example, for a blue button, I do not want to change `--cds-button-primary`, rather, the definition of `blue60`.
That is, I do not want to change the _theme_, I would like to change the main color swatches. 

How can I achieve this ?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Interesting question! Unfortunately the swatches from `@carbon/colors` are not configurable, only the tokens are. If you want to change the root color definitions you could look into monkey patching `@carbon/colors` or fork `@carbon/colors` and override the dependency in `@carbon/react` to your version/fork.
