### ISSUE TITLE
[Bug]: Toggle ignores labelA and labelB and uses labelText if hideLabel is specified

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#12896]
### Package

@carbon/react

### Package version

1.19.0

### React version

16.14.0

### Description

We don't want to use the Carbon label for the toggle because we are providing our own label that includes a tooltip.  We have set hideLabel to true but now it is using our labelText next to the toggle instead of using the labelA and labelB.

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-shdz33

### Steps to reproduce

Set the values of labelA, labelB, labelText, and set hideLabel to true.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Refs https://github.com/carbon-design-system/carbon/pull/12094
Refs https://github.com/carbon-design-system/carbon/pull/12810

cc @janhassel

**Comment by janhassel** [comment]
Hi @kglickman!

Would passing your custom label as `props.labelText` work for your use case?

```jsx
<Toggle
  id="toggle-1"
  hideLabel
  labelText={(
    <>
      Label
      <Tooltip label="Helper text">
        <button>
          <Information />
        </button>
      </Tooltip>
    </>
  )}
/>
```

**Comment by kglickman** [comment]
It does work for the use case I mentioned in the defect.  However, we also have use cases where the label must be displayed outside the component.

**Comment by tw15egan** [comment]
I agree. The second option seems like a more predictable solution for this scenario
