### ISSUE TITLE
[Bug]: Number input field accepts 'e' character but no other alpha characters

### ISSUE THREAD

**Issue by petergramenides** [carbon-design-system/carbon#12899]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.19.0

### Description

If you go to the Number component in IBM carbon and type an `e` character then it will allow the user to enter `e` as a number. This will show up as an `undefined` value in the onChange event and, therefore, it becomes difficult to implement generic validation. As a workaround, I checked `event.target.validity.badInput`, whereas normally I would assume it would not accept an alphabetic letter. Is it accepting `e` because it is a one character mathematical constant?

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/4kmjci

### Steps to reproduce

1. You go to the NumberInput component using the latest version of IBM Carbon on Code Sandbox (link above)
2. Type an `e` and see that it accepts it. It won't allow you to type any other character. You can also type numbers followed by `e`.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> Is it accepting e because it is a one character mathematical constant?

@petergramenides Yes, that's correct. https://stackoverflow.com/a/31706796/3023348

If you want to avoid this character from being entered, you can use NumberInput as a controlled component and use `onKeyUp` to trigger your own validation and remove invalid characters from the `value`. Hope this helps!
