### ISSUE TITLE
[Bug]: NumberInput empty input results in "The specified value "NaN" cannot be parsed, or is out of range."

### ISSUE THREAD

**Issue by ferdelamad** [carbon-design-system/carbon#12897]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.19.0

### React version

16.13.1

### Description

Currently, on the new version of @carbon/react for the `NumberInput`, if you delete the content of the input and then use the + or - buttons, you get the following warning:
`The specified value "NaN" cannot be parsed, or is out of range.`

I think this is happening because `parseInt` is called on an empty string:
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/NumberInput/NumberInput.js#L220

The previous version (prior to Carbon v11) didn't have this issue. You could clear the input and click the + button and it will treat the empty input as having a value of 0 while rendering an empty input, meaning that it will just increment the value by 1.
Right now if you try to force the value to 0 on an empty string this solves the buttons issue but creates a bad user experience since it inserts a 0 on the input when you might want just an empty input.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/numberinput-i2lvtg?file=/src/App.js

### Steps to reproduce

1.- Clean the number input

2.- Open the browser console

3.- Click on either the + or - buttons

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@ferdelamad Thanks for reporting - it looks like it's related to the invalid state of the component. Something within the validation logic is different when the input is invalid and causes the NaN console warning. I can reproduce in storybook, though it's listed as a console warning of type info, not an actual error within the component.

![image](https://user-images.githubusercontent.com/3360588/214101975-a08e13fa-d550-4e44-bc72-dd05b6bf16e3.png)


Is this behavior blocking for you?

**Comment by hanzlahabib** [comment]
@tay1orjones I encountered the same issue in one of our projects; we use Formik. When +/- is clicked, it sends the SVG element as a target to the onChange handler, which then tries to get value out of this SVG element which is undefined always, which causes the field to get reset to an empty string because of NaN

**Comment by ferdelamad** [comment]
Hey @tay1orjones apologies for the late reply, it is not blocking but it's odd that you can't increment with the + when the input field is empty.
Adding `allowEmpty` didn't seem to make any difference.

**Comment by ferdelamad** [comment]
Thank you very much for fixing this 🚀
