### ISSUE TITLE
[Feature Request]: Reorder column in tables

### ISSUE THREAD

**Issue by Jp-Lynch** [carbon-design-system/carbon#12920]
### The problem

Systems and storage administrators learned to expect that they can reorder the content of their data tables to match their wants and needs, but the Carbon system's tables do not allow users to re-order columns.

### The solution

Enable users to reorder columns in data tables.

### Application/PAL

Systems Storage, Fusion Platform > We use the CloudPAL system:
https://github.ibm.com/ibmcloud/pal

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
@Jp-Lynch Thanks for the request. Do ya'll have dev capacity on your team that we can work with to bring this to life? Our roadmap is packed pretty tight at the moment.

**Comment by elycheea** [comment]
We have [column customization (reorder columns)](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story) in Carbon for IBM Products.
