### ISSUE TITLE
Delete icon missing under nodemodules

### ISSUE THREAD

**Issue by spraju92** [carbon-design-system/carbon#12931]
### Package

@carbon/icons

### Package version

11.13.0

### Description

I could not find Delete icon under nodemodules and I'm currently using version "@carbon/icons": "^11.13.0".

![image](https://user-images.githubusercontent.com/28562890/211030407-fac52c92-62f7-44b1-8387-ef77f3b04ce1.png)

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

npm i @carbon/icons

### Steps to reproduce

Just try to install @carbon/icons latest version 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
Hi 👋  Carbon no longer has an icon named delete, it was replaced with `TrashCan` in v11
https://github.com/carbon-design-system/carbon/blame/14599f008d46a624d98750c2a3a6a4b8a51b0224/docs/migration/v11.md?plain=1#L1393
