### ISSUE TITLE
[Bug]: Using button styles corrupts modal button styles

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#12945]
### Package

@carbon/react

### Package version

1.20.0

### React version

16.14.0

### Description

Under normal circumstances, the buttons at the bottom of a modal take up the full width of the modal.

However, we have a component whose scss requires button tokens and when we include 
`@use '@carbon/react/scss/components/button';` at the top of that component in order to use `$button-outline-width`, button is somehow being imported again, overriding the max-width button style that was set for the modal and setting the width back to 12.25rem.  (I tried doing `@use '@carbon/react/scss/components/button/vars';` in order to avoid getting the button styles and just get the tokens but the file is not found, even though we do something similar with `@use '@carbon/react/scss/components/button/tokens';` elsewhere.)

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Reproduction/example

https://stackblitz.com/edit/github-8pcu3g

### Steps to reproduce

Run the sample as written and see that the buttons at the bottom of the modal do not take up the full width of the modal.

Comment out the CustomButton and see that the buttons do take up the full width of the modal.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
To use button tokens correctly, you'll need to `@use` the CustomButton.scss as a partial within  index.scss, rather than importing it in the CustomButton.jsx. This will ensure that both files share the same sass execution context and the button module is not duplicated. [Here's an example](https://stackblitz.com/edit/github-8pcu3g-bp6six?file=src%2Findex.scss,src%2FCustomButton.scss)

**Comment by kglickman** [comment]
I'm missing something.  In your example, I'm not seeing any buttons on the modal at all.
![image](https://user-images.githubusercontent.com/30597411/213253833-e381c7a8-a3d2-4977-99d3-efaca7ed6283.png)
