### ISSUE TITLE
Platform indexing: validate carbon.yml against the storybook - ensure no discrepancies

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12948]
This issue is ensure that content available on the storybook has parity with what's consumed and available on Platform.

https://github.com/carbon-design-system/carbon/issues/12948#tasklist-block-82ab63df-49dd-4970-9161-0784dc729908

**Comment by francinelucca** [comment]
Content-Sync:
- https://github.com/carbon-design-system/carbon-platform/issues/1565: Add `Accessibility` tab to toggletip

**Comment by francinelucca** [comment]
TODO:
> Do we need classPrefix? https://react.carbondesignsystem.com/?path=/docs/components-classprefix--default
> De we need DefinitionTooltip? https://react.carbondesignsystem.com/?path=/docs/components-definitiontooltip--default
	> Tooltip Definition: Rename to Definition Tooltip, add docs, are there any other comps using this?
> What to do about FormLabel? https://react.carbondesignsystem.com/?path=/story/components-formlabel--default
> idPrefix: https://react.carbondesignsystem.com/?path=/docs/components-idprefix--default
> modal wrapper https://react.carbondesignsystem.com/?path=/story/deprecated-modalwrapper--default
> Fluid combobox https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluidcombobox--condensed
> Fluid datepicker https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluiddatepicker--playground
> Fluid dropdown https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluiddropdown--condensed
> Fluid multi select https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluidmultiselect--condensed
> Fluid number input https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluidnumberinput--default
> Fluid search https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluidsearch--default
> Fluid select https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidselect--default
> Fluid text area https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidtextarea--default
> Fluid text input https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidtextinput--default
> Fluid time picker https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidtimepicker--default
> usePrefix https://react.carbondesignsystem.com/?path=/story/hooks-useprefix--page — add this one
> need to add read only pattern https://carbondesignsystem.com/patterns/read-only-states-pattern/

REMOVE or Add SB? 
> indexed hooks: useTheme, unstable_useLayoutDirection, unstable_useFeatureFlags, unstable_useFeatureFlag, unstable_useContextMenu
> layout direction // useLayoutDirection: https://github.com/carbon-design-system/carbon/blob/main/packages/react/carbon.yml
> section https://github.com/carbon-design-system/carbon/blob/main/packages/react/carbon.yml
> textDirection https://github.com/carbon-design-system/carbon/blob/main/packages/react/carbon.yml

**Comment by francinelucca** [comment]
TODO:

- [ ] thumbnails
- [ ] angular/svelte DefinitionTooltip pr
- [ ] confirm tags with Aubrey
- [ ] confirm fluid variants with Anna
- [ ] test content parity
