### ISSUE TITLE
Experimental Component -Content Switcher - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1294]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
Final designs: #1253
Sketch file: https://ibm.box.com/s/osmvf7zqm6c3vxmv5euhqqmwvbf46fsx
@IBM/carbon-developers
