### ISSUE TITLE
[Bug]: OverflowMenuItem doesn't take focus if disabled

### ISSUE THREAD

**Issue by pre-ska** [carbon-design-system/carbon#12942]
### Package

carbon-components

### Package version

10.52.0

### React version

17.0.2

### Description

if Overflow menu has disabled items, it doesn't close previously opened menu

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/naughty-thunder-7p6n40?file=/index.js

### Steps to reproduce

there are two overflow menus  on codesanbox, top and bottom
the bottom one has menu items disabled

1) click top menu icon - it shows menu
(don't close top menu by clicking somewhere on the page)
2) click bottom menu icon- it shows bottom menu but top menu didn't close

if it's other way around, first bottom then top, top menu will take focus and close bottom one

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Thanks for reporting, @pre-ska! You're right; The issue is that there are no focusable items when the second menu is opened, so the previous menu does not close properly.  It seems to work when at least one item is not disabled.
