### ISSUE TITLE
[Bug]: Light prop not working on dropdowns

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#12956]
### Package

@carbon/react

### Package version

1.20.0

### React version

16.14.0

### Description

We are using the "light" prop on many fields and are not ready to deal with `<Layer>` yet.  However, "light" isn't working on DropDown, ComboBox and MultSelect fields.  The styles used to reference field02 and now they are referencing field01 instead.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Reproduction/example

https://stackblitz.com/edit/github-r4v9a1

### Steps to reproduce

Note that the ComboBox and the DropDown input boxes should have a gray background.  The TextInput and TextArea work correctly.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting! The `light` prop is also not working for Tiles, and Select it seems

https://stackblitz.com/edit/github-uy9avp-mg1evl?file=src%2FApp.jsx
