### ISSUE TITLE
[Bug]: ExpandableTile onClick being called twice

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#12963]
### Package

@carbon/react

### Package version

1.20.1

### React version

16.14.0

### Description

We have logic to call when expanding the tile but the onClick is being called twice, both when clicking and when hitting the Enter key.

I'm making this a Sev 4 because we could implement a workaround but I'd really rather not implement that complexity.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Reproduction/example

https://stackblitz.com/edit/github-odxajz

### Steps to reproduce

In the StackBlitz, click the Open in New Tab button so that you can open the dev tools to see the console panel.

Click on the tile.  Note that 'onclick" is printed twice to the console.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kglickman** [comment]
I'd like to lobby for raising the severity on this one.  While I can probably create a workaround to ignore every other onClick, as soon as you fix the bug, my workaround will break it.

_Some more detail about our use case:_
We have a table that shows two rows when not expanded.  When expanded, we need to show more rows.  If we implement it as two different tables, one in the 'above' section and one in the 'below' section, the columns don't line up between the two tables.  We solve this by implementing a single table in the above section and adding more rows to it when they click the expand button.  The 'below' section has no content.

**Comment by Lc0rE** [comment]
I also noticed that we have a very odd behaviour of the Expandable Tile component in it's default state. Even in the Storybook (React) we have this initial state (https://react.carbondesignsystem.com/?path=/story/components-tile--expandable-with-interactive)

![image](https://user-images.githubusercontent.com/7023628/214015676-452d7b41-e789-49d2-b141-7fbec292065a.png)

When expanded and then reduced, the Tile layout goes back to normal:

![image](https://user-images.githubusercontent.com/7023628/214015822-afeb2f49-f804-466d-8dc0-72132f9e2b63.png)

I'm sure this is a regression, and it was working on v < 1.20.1, so it could be related to your bug.

**Comment by tw15egan** [comment]
Pushed up a quick fix for this, please take a look here: https://github.com/carbon-design-system/carbon/pull/13028. Should resolve both of these issues.
