### ISSUE TITLE
Experimental Component - File Uploader - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1296]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [x] Add to carbon-components
- [x] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
Designs are ready: https://ibm.box.com/s/jvywa1198xk4lrwri8oe64qtg2wtbc8d
Design issue: #1255

**Comment by aledavila** [comment]
opening for website
