### ISSUE TITLE
Add ability to hide dev-only stories from the production storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12971]
In some instances, it's helpful to add a story to the storybook for development and testing purposes. These stories are not helpful to the consumer though, and would promote confusion if included in the production site/build.

For these cases, it would be nice if there was a way to add these stories, but have them in a special section that is not included in the production build.

https://github.com/carbon-design-system/carbon/issues/12971#tasklist-block-ce3faa63-639a-433c-98d1-7e9479ec4a5f

<details>
  <summary><h3>A few potential approaches</h3></summary>
  
  ### Use a [environment flag](https://storybook.js.org/docs/react/configure/environment-variables) to turn on/off dev mode
  - This dev mode would need to be applied in the netlify deploy preview environment. It is currently considered a 'production' environment, but we would want to show the dev stories for testing.
  - Ideally our CI and e2e tests would run against all these stories as well. This could be a good way to increase our visual snapshot coverage without introducing a bunch of stories that are only there for snapshotting purposes (e.g. input variants - readonly, disabled, etc.)
  
#### Author stories in `*.dev.stories.js` files, and exclude these from the build in `.storybook/main.js`
  - Benefits: clear separation from production stories
  - Cons: does not live alongside other stories, more difficult to copy paste and maintain as component APIs change

#### Author stories in the same file as production stories, but add a flag/prefix to their names, e.g. `DEV_ReadOnlyInputExamples`
  - We could use this prefix to exclude these stories from the build in via the [`excludeStories` option](https://storybook.js.org/docs/react/api/csf#non-story-exports)
  - https://github.com/storybookjs/storybook/discussions/15134
  - Maybe something like `excludeStories: process.env.DEV_MODE ? /.*DEV$/ : [],` in each story file
  - Benefits: dev stories live alongside production ones, maintenance is easier
  - Cons: less clear separation, but would be easy to find/identify dev stories with an all-caps `DEV_` (or similar) prefix
  
I think ultimately the best approach right now could be to add the environment flag, and use option B
</details>

### Concerns
- This could become a wasteland dumping ground of unhelpful stories that are only used once for bug-repo/resovle.
  - To address, could we define some parameters around why/when we add a dev-only story vs not?
- Visually snapshotting production and dev-only stories could quickly run up our snapshot count, exceeding the quota.
  - To address, could we provide a way for stories to be exempt from snapshotting to avoid running up our snapshot count?

### Examples of stories that would be nice to have in a dev-only mode
- [Read only input comparison story](https://deploy-preview-12601--carbon-components-react.netlify.app/?path=/story/experimental-readonlycomparisons--all) (from https://github.com/carbon-design-system/carbon/pull/12601), mainly for snapshot purposes
- ...

**Comment by sstrubberg** [comment]
Due to some recent work @francinelucca had done to our Storybook the need for dev-only stories has diminished. Will revisit in the future if needed.

**Comment by tay1orjones** [comment]
Since this was opened, a separate idea was delivered that meets a lot of the use cases outlined here. We can now pass control/args configuration parameters on playground stories to the `visitStory()` function in e2e tests. It takes some of the wind out of the sails of this idea, and may outright eliminate it.

Are there other use cases where having dev-only stories would be helpful?
