### ISSUE TITLE
[Bug]: Carbon React Text Area breaks ForwardRef

### ISSUE THREAD

**Issue by akhandsi** [carbon-design-system/carbon#12975]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.20.0

### React version

17.0.2

### Description

In `@carbon/react` v1.20.0, TextArea overrides the dom reference internally rather than using the provided. This breaks our existing implementation of passing dom references.

<img width="1234" alt="Screen Shot 2023-01-12 at 11 30 28 AM" src="https://user-images.githubusercontent.com/8444514/212125064-143eb400-dbaf-4475-9e29-94405a211cd2.png">

This blocks us from upgrading to v1.20.0.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-odxajz-c8pwce?file=src/App.jsx

### Steps to reproduce

Text Area Ref Broken v1.20.0
https://stackblitz.com/edit/github-odxajz-c8pwce?file=src/App.jsx

Text Area Ref Working v1.19.0
https://stackblitz.com/edit/github-odxajz-s6bxhh?file=src/CustomTextArea.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting - this is related to https://github.com/carbon-design-system/carbon/pull/12784.

I think we'll need to merge the `ref` with `textAreaRef` as we do in other components so consumers can still apply and use a ref on the `textarea`.
