### ISSUE TITLE
Platform indexing: Audit existing component taxonomy/organization

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#12985]
#### Acceptance Criteria

- Aubrey's notes from parent issue.
- Final deliverable as an Airtable

#### Notes
- Website (whether true or not 😉 ) is the source of truth

**Comment by aubrey-oneal** [comment]
https://airtable.com/appxMKemRNcvqz6MF/tblkxUvSftTLuA49S/viwqwsP13hyTuCFRe?blocks=hide

This audit documents anything that might be considered a variants, including items under other names such as type, kind, instance, or style. The audit covers the following properties:

- The Carbon website variant table

![Image](https://user-images.githubusercontent.com/47198241/214385509-3a323387-2d5e-42f3-b4e5-9ac07ec1df95.png)


- Storybook navigation file structure

![Image](https://user-images.githubusercontent.com/47198241/214385590-7326f5c5-3fa1-4c19-880e-11e76a2b2438.png)


- Storybook kind or type properties

![Image](https://user-images.githubusercontent.com/47198241/214385639-b7382374-c270-4c4a-b1af-662f7403f258.png)


- Figma instances

![Image](https://user-images.githubusercontent.com/47198241/214385725-83357eeb-e98c-4037-9268-d921bbdcc22f.png)


![Image](https://user-images.githubusercontent.com/47198241/214385746-24acc2b7-5103-4639-9e8a-3e120a137c22.png)


- Figma type or style properties

![Image](https://user-images.githubusercontent.com/47198241/214385781-c9493f98-782a-4ad7-bda2-cefeddd2435a.png)
![Image](https://user-images.githubusercontent.com/47198241/214385782-8393a59b-3aea-4cdb-82b7-dc002fe87ac1.png)

**Comment by aubrey-oneal** [comment]
See our conclusions and next steps in the airtable interface: https://airtable.com/appxMKemRNcvqz6MF/paggHyR3r0OY2qEDR/edit
