### ISSUE TITLE
[Bug]: SideNavMenu crashes when no children defined.

### ISSUE THREAD

**Issue by gcattan** [carbon-design-system/carbon#12986]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.20.0

### React version

16.14.0

### Description

`SideNavMenu` crashes when it has no children (https://github.com/carbon-design-system/carbon/discussions/12981).

![image](https://user-images.githubusercontent.com/6229031/213173432-309916e2-4476-44f3-bd5f-dfd90b56f94f.png)

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-q53twd?file=src%2FApp.jsx

### Steps to reproduce

- Create a `SideNavMenu` with no children.

```
import { SideNavMenu } from '@carbon/react';
import React from 'react';

function App() {
  return <SideNavMenu key={'groupJumpTo'} title={'title'} />;
}

export default App;
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Just curious, what is the use case for rendering a `SideNavMenu` without children? I would expect it not to be rendered at all if there are no children, rather than rendering an empty menu that is clickable (and will show no items when expanded)

**Comment by gcattan** [comment]
Hi,
It is rather how it looks like in the UI. Before, we had something like this:

![image](https://user-images.githubusercontent.com/6229031/213437459-12374b79-c8cf-4e7c-aee2-df7dd57d1da5.png)

And now, if we include the children links in the `SideNavMenu`:

![image](https://user-images.githubusercontent.com/6229031/213437545-feae4e6f-617c-4b93-8de5-e665637e94fd.png)

![image](https://user-images.githubusercontent.com/6229031/213437627-b51b2ddf-c82e-4230-9534-2257d56b48b3.png)

The first version looks better to me. It is possibly not the best way to do so, but it was allowed by the previous version of the component.

**Comment by gcattan** [comment]
Super, I think it is working as expected with the `defaultExpanded` option. Thanks!
