### ISSUE TITLE
[Table Column Resizing]: ability to resize table column to ease looking at column data when number of columns are more

### ISSUE THREAD

**Issue by vinitagit** [carbon-design-system/carbon#12991]
### The problem

Ability to resize table column to ease looking at column data when number of columns are more in table.

In neutrino, there was table feature to allow resizing of columns, so when there is a column that is shrunken due to adjustment in table when there are more number of columns, user was able to drag and increase the column width  and hence able. to view the content properly.

In carbon,  we don't have this resizing feature available for table columns, due to which in cases when the number of columns are more and the width of column is less, user needs to hover over on each data to see what is the full name of data which is very frustrating.

We are the team migrating from neutrino to carbon, the moment we push the carbon screens in Production, we started receiving questions from customers ( Ceva, Petco etc) on this. Here is one such question:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/29124639/213467035-d96ef8d1-2253-44d6-bbb3-dc4298e9b8e7.png">

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/29124639/213596657-384b4b86-ce50-4f38-81a8-56e9d675ca47.png">

Customers are not happy with not  being able to resize the columns.

### The solution

To have resizing ability added in carbon table columns.

### Examples

Resizing ability similar to how it was supported in Neutrino.

### Application/PAL

Configuration HUB( SCBN)

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by vinitagit** [comment]
@tw15egan Hi, can we get an ETA on this feature availability? Lots of our customers are unhappy due to absence of this in carbon. As soon as we pushed the Migrated carbon screens in Productions, we started getting multiple customers request to have that resizable feature back on UI.
It will be really helpful if we get to know, if this feature is going to be available with carbon, if yes, any approximate ETA for that?

**Comment by sstrubberg** [comment]
@elycheea to post when ready!

**Comment by vinitagit** [comment]
@sstrubberg looks like this enhancement request has been closed and pushed to not pursuing. Does that mean there is No plan for implementing this column resizing usecase?

**Comment by elycheea** [comment]
The column resize use case is being pursued in `@carbon/ibm-products` instead. The work is currently still in draft but is on our roadmap.

https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1923
