### ISSUE TITLE
[Bug]: Popover align left top/bottom not aligning

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#12990]
### Package

@carbon/react, @carbon/styles

### Package version

Latest

### Description

See component here: 
https://react.carbondesignsystem.com/?path=/story/components-popover--playground
Expecting left-top and left-bottom alignment option to be top and bottom aligned to the trigger button, like how the right-top and right-bottom currently is.
![Jan-19-2023 21-05-11](https://user-images.githubusercontent.com/15144993/213450683-fab785fa-546b-42a2-9119-d8346131798c.gif)

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-popover--playground

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-popover--playground
2. Play with Align options left-top and left-bottom, and compare that with right-top and right-bottom

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/12287, possibly a storybook playground-only issue. The first step should be to try and reproduce this issue in a CodeSandbox

**Comment by tay1orjones** [comment]
> The first step should be to try and reproduce this issue in a CodeSandbox

Yeah, [here's a link to the vite stackblitz template](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite)

**Comment by tay1orjones** [comment]
I created a repro here https://stackblitz.com/edit/github-fb6475?file=src%2FApp.jsx

It does look like the caret being on or off slightly impacts the positioning of the element. @laurenmrice could you confirm the positioning looks correct when the caret is on and off in the above stackblitz?
