### ISSUE TITLE
[Question]: how to change between two custom themes in carbon?

### ISSUE THREAD

**Issue by ArthurEncr** [carbon-design-system/carbon#13007]
### Question for Carbon

Hi, we are working in a project with carbon design and we have two custom themes to use (dark and light). 

We are wondering if there's a way we can change between the two themes.
 
Looking at carbon's documentation there's only instructions between carbon's own themes (g10, g100 and etc..) and we tried overwriting the tokens with our own themes, examples bellow:
```
[data-carbon-theme='g100'] {
  @include react.theme(dark.$dark-theme);
}

[data-carbon-theme='g10'] {
  @include react.theme(light.$light-theme);
}
```
and we're trying to change the themes like this:
```
if (theme === 'g10') {
    setTheme('g100');
    localStorage.setItem('mode', 'dark');
}
if (theme === 'g100') {
    setTheme('g10');
    localStorage.setItem('mode', 'light');
}
```

and using also the ThemePreferenceContext, like the example in the documentation.

Our changes are actually been applied in the html tag, image bellow:
![Screenshot from 2023-01-23 16-53-21](https://user-images.githubusercontent.com/117835311/214136395-6b9689b4-f6a5-4c01-8f9b-316077b92ffd.png)

But, when we change the themes, the div "bcgov--g100" overrides our changes:

![Screenshot from 2023-01-23 16-54-15](https://user-images.githubusercontent.com/117835311/214137459-a49c5ac5-5307-4443-96b6-9b4e08fd3c5e.png)

![Screenshot from 2023-01-23 16-54-26](https://user-images.githubusercontent.com/117835311/214136645-6c30ffb3-2a0c-4452-9cc8-53b2fd4562a8.png)

Is there a way we can use both custom themes in our project? 
Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by mgaseta** [comment]
Is someone investigating this? I have a similar issue here...

**Comment by tay1orjones** [comment]
Hi! Could you reproduce your setup in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite)? It’s hard to know exactly what might be going wrong without seeing the issue first-hand.

**Comment by sstrubberg** [comment]
@ArthurEncr hit us up with a repro using stackblitz or codesandbox and we'll be happy to take a look!

**Comment by ArthurEncr** [comment]
Hello, when we went to reproduce the error on stackblitz, we went through it again step by step to demonstrate and we found the problem. We were using the "Theme" component on the page in question, as shown in the carbon documentation example, but this made carbon's theme override our custom one. Thank you for your attention.
