### ISSUE TITLE
Experimental Component - Progress Bar - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1300]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
Designs are ready: https://ibm.box.com/s/sa6ertotoju480evtur8cid926jcz9q8
Design issue: #1252
