### ISSUE TITLE
[Feature Request]: Combobox interaction audit—filtering

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon#13026]
### The problem

Related: https://github.com/carbon-design-system/carbon-components-svelte/issues/1635

In carbon-components-svelte, the Combobox has a filtering capability, while in the React library it does not.

- Svelte: https://carbon-components-svelte.onrender.com/components/ComboBox#filterable
- React: https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### The solution

Assuming Comboxes are allowed to be filterable, is it acceptable to have the Dropdown show all items after an option has been selected? There's a video demonstration of the desired behaviour here: https://github.com/carbon-design-system/carbon-components-svelte/issues/1635#issuecomment-1399543307

**Given** there is a Combobox with filtering enabled
**When** the user types a value
**Then** the dropdown is properly filtered based on the matches and you can selected the item.
**And** subsequent interactions with the dropdown should show all items
**And** when collapsing the dropdown by clicking outside or other means, the previous value is maintained.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> Assuming Comboxes are allowed to be filterable

@aagonzales can probably expand on this, but the design spec does not specify this behavior. 

Combobox will highlight the first item that is likely to match the current text in the input, but it does not filter the list to hide items that do not match. 

This has been the case for quite some time. Searching briefly, this has been the behavior all the way back to [v10.8.0](https://deploy-preview-4251--carbon-components-react.netlify.app/?path=/story/combobox--default), perhaps earlier.

**Comment by theetrain** [comment]
Thanks for that background; it sounds like we'll need to remove the filtering capability in the Svelte version of Combobox since that isn't to spec. I'll await the final word before proceeding.

**Comment by tay1orjones** [comment]
I confirmed with the team that filtering is out of spec for combobox. Looking at it made us realize that it's silly to have `Filter...` as the placeholder text though in storybook. We'll remove it so it's more clear, https://github.com/carbon-design-system/carbon/issues/13122

**Comment by tay1orjones** [comment]
@theetrain I actually overlooked something here - there is not filtering _by default_.

There is a prop option though where you can pass in a function to filter items out https://github.com/carbon-design-system/carbon/blob/2233e1edf1a6d51b83aa34dabf1c9463a7b25d7f/packages/react/src/components/ComboBox/ComboBox.tsx#L211-L216
