### ISSUE TITLE
[Bug]: Tooltip text within CreateTearsheet being moved when scrolling

### ISSUE THREAD

**Issue by renato-souzaf** [carbon-design-system/carbon#13021]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.59.0

### React version

v16.14.0

### Description

When I have a `tooltip ` within a `CreateTearsheet`, the tooltip text is moving in the screen when scrolling.

Expected behavior: When scrolling, the tooltip text should keep its position below the icon.
Result: When scrolling, the tooltip text is moving across the screen.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/createtearsheet-with-tooltip-tpm63r?file=/src/app.scss

### Steps to reproduce

1- Open the sandbox provided
2- Focus/click the tooltip icon so the tooltip text is displayed
3- Scroll the tearsheet content
4- Check the tooltip text

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aledavila** [comment]
This has been fixed in v11 with the overhaul of Tooltip now using Popover
