### ISSUE TITLE
Support for Node 18

### ISSUE THREAD

**Issue by luan-dang-techlabs** [carbon-design-system/carbon#13024]
### Question for Carbon

Is Node 18.13.0 supported?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@luan-dang-techlabs We have not explicitly tested Node 18 yet or included it in our CI matrix.

**Comment by squidjam** [comment]
Would you consider doing so?
EOL for Node 16 is just [8 months away](https://github.com/nodejs/release#release-schedule).

**Comment by tay1orjones** [comment]
@squidjam Yes, absolutely. I've added this one to our backlog to address.
