### ISSUE TITLE
Component - Data Table - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1303]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1.  Step one
2.  Step two
3.  Step three
4.  etc.

## Additional information

- Screenshots or code
- Notes

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by aagonzales** [comment]
Designs are done, ready for dev: https://github.com/IBM/carbon-components/issues/1246
@carbon-design-system/ui

Ask @designertyler and @aagonzales questions and PR approval

**Comment by shinytoyrobots** [comment]
@jnm2377 - is this the issue that comprises all of the Data Table work (and thus closed by various PRs when complete)? Or is those closable by a specific PR?

**Comment by jnm2377** [comment]
@shinytoyrobots this compromises all of Data Table work so it's being closed by several PRs. I've been referencing it in my PRs and was planning on closing it with the last PR.

**Comment by elizabethsjudd** [comment]
This issue was closed by stalebot.  Did all of the modifiers get added through the various linked PRs?
