### ISSUE TITLE
[Read-only Inputs]: Update border-bottom color

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#13032]
After our final review with Devin and team we decided to make a final adjustment to input field's border-bottom color. It originally used `$border-strong` but should now be using `$border-subtle`. 

Components to update:
- [x] Date picker
- [x] Dropdown
- [x] Combo Box
- [x] Multi-select
- [x] Number input
- [x] Select
- [x] Text area
- [x] Text input
- [x] Time picker

## Spec

<img width="662" alt="image" src="https://user-images.githubusercontent.com/11670886/214860183-78b7f301-bf55-48c4-9fad-adddf00b549d.png">

**Comment by tw15egan** [comment]
Two things I've run into:

There is no `readonly` variant for `Search`.

FluidCombobox has some issues when setting `readOnly` (it is still active). All others look OK
