### ISSUE TITLE
[Bug]: FilterableMultiSelect - selectionFeedback not working

### ISSUE THREAD

**Issue by Tomahaawk** [carbon-design-system/carbon#13040]
### Package

@carbon/react, carbon-components-react

### Browser

Chrome

### Package version

7.59.5

### React version

16.13.1

### Description

I noticed that in the [MultiSelect](https://v7-react.carbondesignsystem.com/?path=/story/components-multiselect--default) component the selected items are shown at the top of the list and in the [FilterableMultiSelect](https://v7-react.carbondesignsystem.com/?path=/story/components-multiselect--filterable) they are not. Even after explicitly setting `selectionFeedback` to `top-after-open`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-tea6zb?file=src%2FApp.jsx

### Steps to reproduce

1. Create a FilterableMultiSelect and set `selectionFeedback` to `top-after-reopen`
2. Select a couple of items at the bottom
3. Close the multiselect and open again

Items are not shown at the top.

Similar issue #12788 

Some aditional info: if you open the options dropdown by clicking in the arrow at the right, the selectionFeedback works.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tomleah** [comment]
Hi @tay1orjones - could I take a look at fixing this one?
