### ISSUE TITLE
[Question]: Should Button Sets wrap, or render as any element?

### ISSUE THREAD

**Issue by theetrain** [carbon-design-system/carbon#13045]
### Question for Carbon

This is related to https://github.com/carbon-design-system/carbon-components-svelte/pull/1642 since we're transitioning all components to v11 styles.

My questions are:

1. Should Button Sets wrap when the viewport is small? See below image from the [react storybook](https://react.carbondesignsystem.com/?path=/story/components-button--set-of-buttons): 
![image](https://user-images.githubusercontent.com/12798751/215368172-2c426e44-d560-4d92-a242-5c82c933992d.png)
2. Button has an `as` prop, allowing it to render as any HTML element. Is this an intentional feature, or should we remove it? 

Thanks for your help!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey there! 

> Should Button Sets wrap when the viewport is small?

No. There is a `stacked` prop that flips it to vertical orientation though.

> Button has an as prop, allowing it to render as any HTML element. Is this an intentional feature, or should we remove it?

It's intentional to provide flexibility if a different element needs to be used.

Hope this helps! I'm happy to continue the discussion below if you have follow up questions
