### ISSUE TITLE
[Bug]: DatePicker with initial value 

### ISSUE THREAD

**Issue by Harelazimtas** [carbon-design-system/carbon#13058]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.20.0

### React version

17.0.2

### Description

I try to use date picker with initial value(date)
but i think there is bug with select date , it select many dates (19,27,28,29)

<img width="1428" alt="Screenshot 2023-01-29 at 16 52 33" src="https://user-images.githubusercontent.com/48510673/215793493-e704a8fc-7932-4889-870f-a8e24b609c8a.png">

`<DatePicker
    placeholder="m/d/Y"
    labelText="Date picker label"
    datePickerType="range"
    key="dateRangePicker"
    value={["2022-10-28T21:00:00.000Z", "2023-01-28T22:00:00.000Z"]}
    dateFormat="m/d/Y"
  >
    <DatePickerInput
      id="date-picker-range-start"
      key="startDate"
      placeholder={"01/29/2023"}
      labelText="Start date"
    />
    <DatePickerInput
      id="date-picker-range-end"
      key="endDate"
      placeholder={"10/29/2022"}
      labelText="End date"
    />
  </DatePicker>`
  
  

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-pps2pn?file=src/App.jsx

### Steps to reproduce

insert the below code and select 27 and 28 and 29..

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@Harelazimtas The stack blitz you provided seems to be selecting the correct dates. 

<img width="1073" alt="Screenshot 2023-01-31 at 10 06 48 AM" src="https://user-images.githubusercontent.com/11928039/215797531-2570a486-1666-479d-91c9-d158fbf6ad64.png">

**Comment by tw15egan** [comment]
I believe you need to supply an array of date objects to the `value` prop, like so:

```jsx
value={[
      new Date('2022-10-29T21:00:00.000Z'),
      new Date('2023-01-28T22:00:00.000Z'),
    ]}
```

https://stackblitz.com/edit/github-pps2pn-erqkd5?file=src%2FApp.jsx

For more `flatpickr` docs,[ see here](https://flatpickr.js.org/examples/#supplying-dates-for-flatpickr). It does say it accepts ISO Date Strings, but the `dateFormat` needs to match

**Comment by galamo** [comment]
@Harelazimtas  can you please validate if this solution fits us?

**Comment by Harelazimtas** [comment]
@tw15egan  Thanks , but it didn't working 
<img width="1274" alt="Screenshot 2023-01-31 at 18 42 01" src="https://user-images.githubusercontent.com/48510673/215824622-5c2b835e-0907-40cd-9372-dc5eed2e8018.png">

please try to select 11/02/2022

**Comment by tw15egan** [comment]
It is rendering correctly for me 🤔 

<img width="1124" alt="Screenshot 2023-01-31 at 12 40 58 PM" src="https://user-images.githubusercontent.com/11928039/215840344-78c729e5-1582-4a3d-974a-fbc29c99859c.png">


Could be an intermittent issue with the `value` not matching the specified `dateFormat`, but I am unable to reproduce it.

**Comment by Harelazimtas** [comment]
@tw15egan  how you select '11/02/2022' ? by edit the text ?

**Comment by tw15egan** [comment]
I opened the end date input field  and selected the 2nd

**Comment by Harelazimtas** [comment]
please try this : opened the start date input field and selected the 2nd

**Comment by tw15egan** [comment]
Hmm, I see some weird issues as well, not sure what's going on! Trimming the date string seems to resolve the issue, however, so I'd recommend sanitizing the dates a bit before setting them as the value. Does that work for you?

See here: https://stackblitz.com/edit/github-pps2pn-erqkd5?file=src%2FApp.jsx

```jsx
value={[new Date('2022-10-29'), new Date('2023-01-28')]}
```

**Comment by tw15egan** [comment]
I see it as well, though it happens intermittently. It should close the menu after selecting a date, but it doesn't seem to be doing that
