### ISSUE TITLE
Dropdown has some style issues in IE11

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#1306]
As pointed out by @joshblack in #1269 

Looks great! Noticed a couple style quirks (potentially):

![screen shot 2018-10-18 at 4 38 41 pm](https://user-images.githubusercontent.com/3901764/47185927-84ffa600-d2f4-11e8-956d-53907aeb609f.png)

In IE11, it looks like the background color bleeds down. This could be a remnant of the previous implementation, in which case might be better to file as a bug ticket that we could fix separately. Also noticed it in the disabled styles:

![screen shot 2018-10-18 at 4 37 33 pm](https://user-images.githubusercontent.com/3901764/47185968-a6609200-d2f4-11e8-9ba1-9e59ef0d3e5b.png)

**Comment by ghost** [comment]
Hello, @tw15egan . Is this still an issue? Would love to help.

**Comment by emyarod** [comment]
I believe this was addressed in https://github.com/IBM/carbon-components/pull/1994 and https://github.com/IBM/carbon-components/pull/2181

testing in https://the-carbon-components.netlify.com/?nav=dropdown on IE11
