### ISSUE TITLE
[Bug]: eslint-config-carbon requires TypeScript from 2.18.0

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/carbon#13071]
### Package

carbon-components, carbon-components-react, @carbon/colors, @carbon/elements, @carbon/grid, @carbon/icons-react, @carbon/layout, @carbon/motion, @carbon/themes, @carbon/type

### Package version

eslint-config-carbon@2.19.0

### React version

16.14.0

### Description

Starting from eslint-config-carbon@2.18.0, which introduced TypeScript, we now need to add a TypeScript plugin even though our package is not using TypeScript at the moment.

https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/3589380345/jobs/6041746926

Spoke with @tay1orjones about this briefly back in December (right before the holidays, of course) about options for how give more control over the config so we can hopefully avoid a totally custom config just to exclude TypeScript.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Reproduction/example

https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/3589380345/jobs/6041746926

### Steps to reproduce

Here’s the [latest failed action](https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/4060835285/jobs/6990299191) and where/how we include [`eslint-config-carbon`](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/update-packages-1252a4x/package.json#L104-L108).

```
Run yarn ci-check:lint
  yarn ci-check:lint
  shell: /usr/bin/bash -e {0}
Running audit using: yarn npm audit --groups dependencies --level moderate

Oops! Something went wrong! :(

ESLint: 8.[3](https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/3589380345/jobs/6041746926#step:6:3)1.0

ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/home/runner/work/ibm-cloud-cognitive/ibm-cloud-cognitive".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint/eslint-plugin@latest --save-dev

The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in "package.json » eslint-config-carbon » /home/runner/work/ibm-cloud-cognitive/ibm-cloud-cognitive/node_modules/eslint-config-carbon/plugins/react.js#overrides[0]".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for opening this issue! I think we can either
1. Include `@typescript-eslint/eslint-plugin` as a dependency of `eslint-config-carbon`
2. Or, remove this from `eslint-config-carbon` to instead be used only locally within the Carbon monorepo so users of `eslint-config-carbon` don't inherit these typescript rules.

I think `#2` might be more appropriate, but projects who _are_ using typescript might benefit from typescript rules being applied to their project.

If this is left in `eslint-config-carbon` can we provide a way for users to turn off that ruleset if they don't need it?
