### ISSUE TITLE
[Bug]: Actionable Notification has "caption" propType validation, but is not implemented

### ISSUE THREAD

**Issue by kimsjason** [carbon-design-system/carbon#13075]
### Package

@carbon/react

### Package version

1.1.0

### React version

latest

### Description

The @carbon/react Notification component declares caption as a propType, but it is never passed as a prop & implemented in ActionableNotification.

![image](https://user-images.githubusercontent.com/84881481/216384047-d850fb80-1982-4e04-91c1-51e19cb0fa88.png)

Consequently, while the Carbon component documentation suggests that caption can be passed as an attribute to ActionableNotification, nothing renders when the user inputs a string value.

![image](https://user-images.githubusercontent.com/84881481/216383903-399fe792-fbc5-4b1b-b6df-b86b930c4164.png)
![image](https://user-images.githubusercontent.com/84881481/216383802-8fa5e2b2-f433-48ce-8758-ff04132ea777.png)

This prevents the user from implementing a caption like timestamp in an ActionableNotification component.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-8akq7x?file=src/App.jsx

### Steps to reproduce

Input any value into the caption attribute. No value will render in the ActionableNotification component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@kimsjason Yes, thanks for catching this, `caption` is not used in ActionableNotification. It was part of the experimental API during v11 development and we forgot to remove it.
