### ISSUE TITLE
[Bug]: Modal on Safari

### ISSUE THREAD

**Issue by zybjcdl** [carbon-design-system/carbon#13084]
### Package

carbon-components-react

### Browser

Safari

### Package version

^8.13.0

### React version

^16.13.1

### Description

We found the Modal sometimes won't show up in the front in Safari browser, it works find in Chrome and Firefox.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/21072683/216483995-d7353e0c-a400-44b4-9c09-2527d7bbe63c.png">
We are using Modal, nothing special:
import { Modal } from "@console/pal/carbon-components-react";
<img width="500" alt="image" src="https://user-images.githubusercontent.com/21072683/216484104-0df50a46-58b0-434a-afb5-e9771dee8d1c.png">
Just like in the picture, when click one of the item in combobox, the modal will show up .

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

It is reproduced occationally

### Steps to reproduce

When click one of the item in combobox, the modal will show up , sometimes, it is not on the top

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @zybjcdl , can you provide a [stack blitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx) with a simple reproduction of the issue you are running into? Thanks!

**Comment by zybjcdl** [comment]
Close the issue, could be fixed by some workaround
