### ISSUE TITLE
TreeView: Increase horizontal and vertical hit area of twistee

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13114]
The TreeView needs to be updated - the twistee hit area/padding needs to be updated to match the new spec delivered in #12800

-----
### 8px padding between icons

<img width="1342" alt="Design" src="https://user-images.githubusercontent.com/43969356/206217028-56ea49ef-53e0-40e9-a206-371c8f00d311.png">

<img width="1342" alt="Specs" src="https://user-images.githubusercontent.com/43969356/206216415-79db2bfc-3e43-4ac5-b4c3-dffbcb93954a.png">

### Final decision
- Going with 8px padding between icons. 
  - *Note: reopen issue if there are changes based on the [a11y touch target](https://github.com/carbon-design-system/carbon/issues/12769) solution.

<img width="1342" alt="Frame 2" src="https://user-images.githubusercontent.com/43969356/207102819-aeac174f-e809-482b-94b7-3a1c86152776.png">

**Comment by aagonzales** [comment]
Re-opening this issue as the code still does not match the spec. The original PR did not have a design review on it.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/11670886/232144266-fd4e4531-7a85-4525-973a-10fde9d0b842.png">

**Comment by alisonjoseph** [comment]
Sorry my fault for not getting a design review, I wrongly assumed nothing was visually changing and it was just the hit area size.

**Comment by aagonzales** [comment]
@alisonjoseph Yeah no worries, some padding on the other items had to shift by 8px as well. Its not super obvious in the spec, I can put together a clearer changelog.

**Comment by aagonzales** [comment]
@alisonjoseph The alignment is only off in the "with icon" variants. The changes in padding needed are indicated in purple.

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/11670886/232606195-2b66df7b-764e-406b-a3a3-858e9b5f4a45.png">
