### ISSUE TITLE
[Bug]: small Loading spinner wobbles when line height is not 1rem

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon#13121]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.21.0

### React version

18.2.0

### Description

The small `Loading` spinner might not be centred, depending on the computed `line-height` property. This makes it wobble or spin wildly out of control.

I think this should fix it:
```
.cds--loading--small {
  width: 1rem;
  height: 1rem;
  line-height: 1rem;   // <--- add
}
```

### Reproduction/example

https://stackblitz.com/edit/github-9cxysl?file=src%2FApp.jsx

### Steps to reproduce

Stare intently at the Loading spinner.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by andreancardona** [comment]
@TheophileMot thanks for catching this - adding it to our backlog :)
