### ISSUE TITLE
NumberInput: Misalignment of number controls

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1312]
@Joseph-Hitchcock moved from https://github.com/IBM/carbon-components-react/issues/1468

When a NumberInput's invalidText wraps onto another line, it causes the number controls to no longer be centered in the input field.

![image](https://user-images.githubusercontent.com/40905872/47236615-8d59ee80-d391-11e8-9c0d-3c46b23fe198.png)

![image](https://user-images.githubusercontent.com/40905872/47236617-8fbc4880-d391-11e8-8563-3b0b46a37456.png)

This [code sandbox](https://codesandbox.io/s/wqwmxpo435) illustrates this behavior.

**Comment by vividh** [comment]
I would like to work on this!

**Comment by asudoh** [comment]
Sounds good, thanks @vividh - Please make sure getting in sync with @tw15egan on this.

**Comment by tw15egan** [comment]
@vividh Looks like we need to position this off the `top`, rather than `bottom`, and add an extra class for when no label is present like we do for Date Picker:

https://github.com/IBM/carbon-components/blob/master/src/components/date-picker/_date-picker.scss#L125

**Comment by vividh** [comment]
@tw15egan Sounds good! Will give an update once I have a working solution, which might be sometime this weekend. Thanks!

**Comment by vividh** [comment]
@tw15egan Created PR with the changes. Adjusted the number input position based on label as well as helper text. Let me know if I missed anything.
