### ISSUE TITLE
[Question]: How to programmatically close a Tooltip

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#13131]
### Question for Carbon

Is there a way to programmatically close (or disable) a Tooltip? Or the only available option would be playing with conditional rendering?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@marcellobarile There is not a way to programmatically close a Tooltip, other than conditional rendering.
