### ISSUE TITLE
[Question]: How to apply a ToggleTip to an element that is not a button?

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#13134]
### Question for Carbon

Reading the documentation, the `ToggletipButton` wrapping component makes clear that only buttons can be used as children. Is this true? What if, for example, I want to add a Toggletip to a Tabs navigation?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey there 👋 Yes, right now it's not possible to put a ToggleTip on a Tab, but it has been suggested that this (or a Tooltip) be added to improve accessibility, https://github.com/carbon-design-system/carbon/issues/13029.

You may be able to use a Popover or Tooltip with the Tab though. I don't believe it's been directly tested though, so it might require some additional styling. I'm not sure if/how it could impact accessibility of the tabs either.

I hope this helps! Happy to continue the conversation here if you have further questions.

**Comment by marcellobarile** [comment]
Thanks @tay1orjones, the intermediate solution was actually using the regular Tooltip component :)
