### ISSUE TITLE
[Bug]: Destructuring DataTable in v11 breaks the application

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/carbon#13159]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.23.0-rc.0

### React version

17.0.0

### Description

When using DataTable and importing it counterparts by destructuring it breaks the whole app.

```js
import { DataTable } from '@carbon/react'

const {
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
} = DataTable;
```

<img width="2141" alt="Screenshot 2023-02-15 at 1 06 20 PM" src="https://user-images.githubusercontent.com/12755042/219115317-5f2a2a1d-f77b-4cf5-ab98-bea1d5918684.png">

The solution was importing everything directly from the import statement.

```
import {
  DataTable,
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
} from '@carbon/react';
```

<img width="2119" alt="Screenshot 2023-02-15 at 1 07 49 PM" src="https://user-images.githubusercontent.com/12755042/219115629-769392f4-406a-4a5f-8fa6-91c872c15652.png">

### Reproduction/example

https://stackblitz.com/edit/github-yg1k54?file=src%2FApp.jsx

### Steps to reproduce

1. Notice the console errors. 
2. Comment out the desctructure statement, and uncomment the import statement
3. It works

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

Carbon for IBM Products

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Ah, I'm sorry you've had to refactor all these usages in your project! At a glance I don't see any difference in how DataTable and the fields on it are exported between v10 and v11. I'm not sure why this is happening and will need to take a deeper look.

Since the exports are still usable via named imports I'm going to categorize this as a lower severity issue.

**Comment by francinelucca** [comment]
Worth noting: switching to v1.21.0 works, anything over that breaks https://codesandbox.io/s/carbon-datatable-xn7rkp?file=/src/App.js

**Comment by tay1orjones** [comment]
Yeah, I assume it's related to some of the files' types being added and converted to `.tsx`

**Comment by mbarrer** [comment]
Seems like we need to convert the DataTable index.js to TS in order to be able to destructure the newly converted table components
