### ISSUE TITLE
[Bug]: Tooltip won't show in pagination

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon#13153]
### Package

@carbon/react

### Browser

Chrome

### Package version

V10, V11

### React version

@carbon/react@1.22.0

### Description

In a pagination, if I hover on the disabled "Back" button first, then move the mouse to the "Next" button on the right, the tooltip will not show.
<img width="918" alt="image" src="https://user-images.githubusercontent.com/40870771/218907069-da64aa88-53c6-4df4-ab06-29413d63e8d5.png">

### Reproduction/example

n/a

### Steps to reproduce

To reproduce this issue in pagination:
1. Hover the disabled "Back" button,
2. move the mouse to the "Next" button on the right, the tooltip will not show unless you move the mouse out of the toolbar then move back.

We have a code editor in Netezza which contains both enabled and disabled buttons:
![image](https://user-images.githubusercontent.com/40870771/218906619-a3def467-30be-4b5c-9186-46ce063be1f3.png)
When user hovers on the disable "Cut" button first, then move to other enabled buttons, the tooltips won't show. Similar to what happens in pagination. We believe these two cases are related.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I can confirm also appears in our storybook. The `Popover` component does not seem to fire an `onMouseEnter` event when traversing a `disabled` button element.

**Comment by tay1orjones** [comment]
I can't reproduce this in v1.38.0, it looks to be resolved.


https://github.com/carbon-design-system/carbon/assets/3360588/b654befe-c8cf-47a7-91d7-2d2b7daaa54a
