### ISSUE TITLE
[Question]: Module '"@carbon/react"' has no exported member DataTable (or any other)

### ISSUE THREAD

**Issue by valyagolev** [carbon-design-system/carbon#13154]
### Question for Carbon

My app is created using create-react-app. I installed `@carbon/react` using `yarn add`, I also installed the `sass` package. I couldn't understand the "`node_modules` in sass config" step, but after googling I tried setting `SASS_PATH=node_modules` env var, which didn't seem to help. Perhaps I missed a step? What else should I have done?

VS Code Typescript plugin highlights the following line as full of errors, each of them says something like `Module '"@carbon/react"' has no exported member DataTable`. I can still open `node_modules/@carbon/react/lib/index.d.ts` using "Go to definition", so the file exists (though, "Go to definition" from that file to the components doesn't work). I couldn't find such an error anywhere in the issues of this project.

```
import {
  DataTable,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
} from "@carbon/react";
```

Also if I run:

``` SASS_PATH=node_modules yarn start```

I still get warnings like:

```
TS2305: Module '"@carbon/react"' has no exported member 'TableHeader'.
```

But most fascinatingly, the app seems to compile and work and show a DataTable.

Versions are:

```
    "@carbon/react": "^1.22.0",
    "sass": "^1.58.1",
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> VS Code Typescript plugin highlights the following line as full of errors

Yeah, this is somewhat of a false error due to only some components having types provided right now. They're slowly being added by the community #12513. This has been reported before and some workarounds listed: https://github.com/carbon-design-system/carbon/issues/13091

**Comment by valyagolev** [comment]
Thank you!
