### ISSUE TITLE
[Bug]: Link component does not break across lines

### ISSUE THREAD

**Issue by catdragon** [carbon-design-system/carbon#13177]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.22.0

### React version

v18.2.0

### Description

I expected to see the text in a Link break across lines.  You can see what I mean by comparing the two attachments (excluding of course the non-blue and non-underlining of the <a> tag in the Carbon style).
![Screenshot 2023-02-16 at 2 18 34 PM](https://user-images.githubusercontent.com/7491314/219478173-70f38892-8f02-4bfa-acee-cb68b6a54100.png)
![Screenshot 2023-02-16 at 2 20 31 PM](https://user-images.githubusercontent.com/7491314/219478178-2e51b0f0-5fe9-44df-af4f-bc0f3d4a163b.png)

### Reproduction/example

https://stackblitz.com/edit/github-lya3fv?file=src/App.jsx

### Steps to reproduce

Simply create a page with the Link tag.  According to Taylor Jones (taylorjones@us.ibm.com), this was introduced in https://github.com/carbon-design-system/carbon/pull/8361/files, but I am taking his word for that.  Taylor also said that it works when along, not bracketed by tags, ⁣⁣ but I can not confirm this.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting this - I think this was introduced quite a while ago in https://github.com/carbon-design-system/carbon/pull/8361

I believe we can just set `display: inline` on the inline modifier class to resolve this, but we should document the outcome in a storybook story so it's easier to see this in action.
