### ISSUE TITLE
Carbon Accordion component width issue

### ISSUE THREAD

**Issue by reshmpk1** [carbon-design-system/carbon#13187]
We have an issue [on](url) carbon accordion component. When we have wider column content in the accordion section, there is always a right padding of 25% space by default. Will it be possible to make it without that white space? I tried overwriting the class on our own .scss file, but that important class has not been taken.

![image](https://user-images.githubusercontent.com/29655795/219677645-ecce251b-3b0d-460e-8e0e-3522492a420a.png)

**Comment by tw15egan** [comment]
This is working as intended by design and should not be overridden. See https://carbondesignsystem.com/components/accordion/style
