### ISSUE TITLE
Modal loading state: design spec for inline

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13180]
#### Acceptance Criteria

- [ ] Start and success loading states- The final interaction. How does the load state begin and how does it finish.
- [ ] Error states.
- [ ] Using the appropriate tokens.

@aagonzales to find Loading component in Figma and get a reference spec.

**Comment by Shankar-CodeJunkie** [comment]
@sstrubberg :  I would like to work on this issue .

**Comment by sstrubberg** [comment]
@Shankar-CodeJunkie that's great! we're still looking for design specs from ... But when we have them, you should collaborate with lucasfeol@ibm.com. He also expressed interest in developing this once we have a design. Let's keep in touch!

**Comment by aubrey-oneal** [comment]
I'd like to volunteer to help with this issue.

**Comment by aubrey-oneal** [comment]
I'll volunteer to help with this issue!

**Comment by aubrey-oneal** [comment]
I'd like to help with this issue.

**Comment by Surya-kv** [comment]
@sstrubberg - It is done
Please check the below ticket for your reference. [https://github.com/carbon-design-system/carbon/issues/10495]

**Comment by sstrubberg** [comment]
> @sstrubberg - It is done Please check the below ticket for your reference. [https://github.com/[/issues/10495](https://github.com/carbon-design-system/carbon/issues/10495)]

You rock @Surya-kv!! Just to confirm, you're talking about [this comment](https://github.com/carbon-design-system/carbon/issues/10495#issuecomment-1674614130) you left, correct?

**Comment by sstrubberg** [comment]
Also, @Surya-kv did you notice that @Tomahaawk appears to have completed the inline loading state [here](https://github.com/carbon-design-system/carbon/pull/14490)?

**Comment by Surya-kv** [comment]
> Also, @Surya-kv did you notice that @Tomahaawk appears to have completed the inline loading state [here](https://github.com/carbon-design-system/carbon/pull/14490)?

Yes @sstrubberg

**Comment by Tomahaawk** [comment]
Hello @sstrubberg 
the work for inline loading on modals is complete.
