### ISSUE TITLE
Platform indexing: Document final proposal

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#13190]
We've had several sessions to work through the details of a new proposal for our file structure between Storybook, Figma, and Platform. Now it's time to look at our holistic results so that we can discuss any final issues and have a clear changelog for dev to work with.

#### Acceptance Criteria

- [x] Final playback to the team 
- [x] Changelog for the team
- [x] Alignment on naming convention

**Comment by aubrey-oneal** [comment]
Airtable: https://airtable.com/appxMKemRNcvqz6MF/tblbs5neolk8xtvrw/viwjW7S67EwcqekU0?blocks=hide
Playback walkthrough: https://www.figma.com/file/rahF7ZFUm2of5Wc0mWTOTy/Variant-Proposals-(Github-13035)?node-id=0%3A1&t=8rN52FJ6vmv5DJF7-0
