### ISSUE TITLE
Add TypeScript types to Button, ButtonSkeleton, DangerButton, ButtonSet

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#13229]

**Comment by tay1orjones** [comment]
@DavidChristiansen You’ll need to add a `// @ts-ignore` above the line where you import the component

**Comment by lewandom** [comment]
@tw15egan @tay1orjones I'd like to take this one next on my plate.

**Comment by lewandom** [comment]
Waiting on https://github.com/carbon-design-system/carbon/pull/13735 before pushing a PR for this one.
