### ISSUE TITLE
[Bug]: FileUploader does not clear value when file is deleted

### ISSUE THREAD

**Issue by herrnate** [carbon-design-system/carbon#13267]
### Package

@carbon/react

### Browser

Chrome, Safari

### Package version

1.23.1

### React version

17.0.1

### Description

FileUploader: When uploading a file, deleting it, and trying to upload the same file it does not work. It seems to be an issue with the delete functionality not clearing the value, and hence Chrome and Safari do not trigger the onChange event.

NOTE: If you upload a different file, it will work, since the value will change and the onChange will trigger. 

### Reproduction/example

https://stackblitz.com/edit/github-94x55y?file=src/App.jsx

### Steps to reproduce

(1) Upload a file.
(2) Delete the file.
(3) Upload the same file.
(4) See that it does not work.

NOTE: If you upload a different file, it will work, since the value will change and the onChange will trigger. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by andreancardona** [comment]
Just tested and confirmed the bug, thank you for reporting @herrnate!
