### ISSUE TITLE
[Feature Request]: Improve ContextMenu to provide a safe triangle area

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13271]
### The problem

When using ContextMenu with submenus via mouse, a user must keep their pointer strictly on the item selected to navigate to the submenu. See here attempting to select the last option "Company"

https://user-images.githubusercontent.com/3360588/222243722-76b69f64-1215-4883-bb12-340575b27457.mov

### The solution

The problem is in sharp contrast to how a user would navigate to items within the list. Instead ContextMenu should take into account a 'safe triangle area' to where the existing submenu stays open even when the pointer is not directly on the selected item or the submenu.

### Examples

Here's an example from [this excellent article](https://height.app/blog/guide-to-build-context-menus):

https://user-images.githubusercontent.com/3360588/222243902-8cc2f910-e2a4-4f03-8e48-1ab237633e7c.mp4

This approach was initially popularized by Amazon with their megamenu back in 2013: https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown/amp

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Great example here: https://floating-ui.com/docs/usehover#safepolygon

**Comment by tay1orjones** [comment]
Fixed via https://github.com/carbon-design-system/carbon/pull/16466 though the solution was a simple timeout instead of this calculation idea

**Comment by metonym** [comment]
For the Svelte implementation, the safe triangle was added via https://github.com/carbon-design-system/carbon-components-svelte/pull/2221
