### ISSUE TITLE
[Bug]: padding-right of modal-header is different to the guidance

### ISSUE THREAD

**Issue by jan-christensen1** [carbon-design-system/carbon#13288]
### Package

@carbon/react

### Browser

Chrome

### Package version

v10

### Description

In the [guidance](https://v10.carbondesignsystem.com/components/modal/usage/#alignment) it is stated that modal header and description should have 20% padding-right. The actual code component does have 20% padding for the description but not for the header.

I guess either the guidance or the padding needs to be updated.

### Screenshots

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/65981991/222769544-6d278c3e-d272-4eb2-9e4d-3eb1acb73366.png">

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/65981991/222769593-65c6368d-fb19-4078-9265-08faab827a58.png">

### Steps to reproduce

See guidance on alignment on [carbondesignsystem.com](https://v10.carbondesignsystem.com/components/modal/usage/#alignment) 
Inspect modal in the [storybook](https://react.carbondesignsystem.com/?path=/story/components-modal--playground)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Yeah this is a continuation of https://github.com/carbon-design-system/carbon/pull/11618 where the `p` tags were updated, but we missed the header evidently.
