### ISSUE TITLE
[Tabs] Add a secondary style

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon#1329]
### Summary

My project requires an alternative styling for the Tabs component which looks like this:

![image](https://user-images.githubusercontent.com/1253469/47453344-7acd2400-d79a-11e8-97a2-3cc5191ad66d.png)

I can make the style updates this or next week and contribute it back if that new design is deemed to be useful to Carbon. Any notes from Design to make the above style compliant with the Carbon are very much welcome.
(https://ibm-studios.slack.com/archives/C0M053VPT/p1540402619000100?thread_ts=1540400543.000100&cid=C0M053VPT)

**Comment by alisonjoseph** [comment]
@IBM/carbon-designers fyi

**Comment by jeanservaas** [comment]
@stanislavgeorgiev 

This is what's coming down the pipe for Carbon v11. Like I said, these guys are spec'd but are not going to make the Carbon X release. Also note, they're in the new design language style... and we're still hammering out our color tokens for the light theme.

If you want to contribute something back to Carbon, it would make sense to use this structure. @aagonzales suggested you could just use the existing Carbon colors in the meantime... 

![tabs_light_theme_1](https://user-images.githubusercontent.com/43144260/47462217-524c2680-d7a8-11e8-908a-1643b63e23d7.png)
![tabs_specs_2](https://user-images.githubusercontent.com/43144260/47462218-524c2680-d7a8-11e8-915e-13779473f86c.png)

**Comment by stanislavgeorgiev** [comment]
Thanks @jeanservaas, that's going to be very helpful!
When would those changes end up in `master` if I make them?

**Comment by jeanservaas** [comment]
There's no reason a tab variation couldn't go into the Experimental components right away. The reason we're not doing it is that we have limited resources so we have to focus just on matching what's in Carbon right now for the X release. If your team develops it to spec we could try to include it for X.

**Comment by tw15egan** [comment]
@stanislavgeorgiev you can take a look at our other components that have experimental versions to see how we are going about it:

https://github.com/IBM/carbon-components/blob/master/src/components/list/_list.scss

**Comment by aagonzales** [comment]
This is something we will need. I've already seen teams like Cloud using this in their designs. Not stale.

**Comment by shixiedesign** [comment]
Hi @stanislavgeorgiev ! Just wanna check in to see if you've got to create the secondary style for Tabs. Keep us posted and lemme know if you need any additional info/spec. Thanks!

**Comment by stanislavgeorgiev** [comment]
@shixiedesign No, I haven't had a chance to work on it yet. I may get some time in several week to work on this.

**Comment by laurenmrice** [comment]
not stale

**Comment by stanislavgeorgiev** [comment]
Still active

**Comment by jeanservaas** [comment]
Also, like @aagonzales we've seen these designs from Intratstructure and Containers teams -- I know Erica Raymond was taking about contributing it back to Carbon. I'll follow up with her on it too.

**Comment by stanislavgeorgiev** [comment]
Still active

**Comment by asudoh** [comment]
@jeanservaas @aagonzales Looking at [the spec image](https://user-images.githubusercontent.com/43144260/47462217-524c2680-d7a8-11e8-908a-1643b63e23d7.png), which has several IBM color references. Do we have mappings of those to our theme tokens? (My apologies if I'm missing something) Thanks!

**Comment by aagonzales** [comment]
Nope, we didn't have the tokens on there. Here's the spec with color tokens

![tabs](https://user-images.githubusercontent.com/11670886/67034826-0a6f8f00-f0de-11e9-90b6-db98ef4b8f1d.png)

**Comment by asudoh** [comment]
Super 🎉 - Thanks a lot @aagonzales!
