### ISSUE TITLE
Interactive tag: audit, research, design iterations

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13305]
### Audit
- [x] Audit what Carbon currently has for the Tag component
  - [Consider all states](https://github.com/carbon-design-system/carbon/issues/13145#issuecomment-1450764094) that may need to be added for clickable tag usability.
  - Consider truncation

### Research
- [x] Research where this use case exists in IBM product and externally
  - Look at different implementations/usecases outside of just Cloud to consider.
  - Watson is missing visual indication when you hover (reach out to Zak Crapo).

### Playback to a11y and Carbon design team
- [x] Playback audit, research, and design iterations to carbon design team.
- [x] Playback audit, research, and design iterations to a11y sme Michael Gower (around state interactions).

### Content review
- [x] Contact Aubrey O'Neal on the naming structure of clickable tag.

### Design iterations
**Figma files**
- [Audit and Research](https://www.figma.com/file/ORkjLMu6gxZLTHmsBJkYDM/Interactive-Tag-Specs?type=design&node-id=69%3A13664&mode=design&t=2RY4ZR4L25OHDJRN-1)
- [Hi fi iterations WIP](https://www.figma.com/file/59CvsdnSHvtvcCmHhfiVEk/Clickable-Tag?type=design&node-id=0%3A1&mode=design&t=TzuTNk4rWQhQXbkn-1)

**Comment by laurenmrice** [comment]
**Cloud team**
- [x] Design research
- [x] Design iterations
- [ ] Review with Carbon and a11y team
- [ ] Finalize spec

**Comment by laurenmrice** [comment]
Closing this since the audit, research, and design iterations are finished. Next issue to tackle is creating a final design spec in [#15527](https://github.com/carbon-design-system/carbon/issues/15227)
