### ISSUE TITLE
[Feature Request]: Mastodon Icon

### ISSUE THREAD

**Issue by pReya** [carbon-design-system/carbon#13307]
### The problem

The year is 2023 – Twitter suffered a big hit in terms of popularity, and many users have move to the decentralized, federated "Fediverse" with Mastodon as its biggest representative. Unfortunately Carbon does not offer a Mastodon icon.

Having a Mastodon icon among the social media icons (like Facebook, Twitter, LinkedIn) would be very helpful and appropriate.

### The solution

The original icon as a vector can be found here: https://commons.m.wikimedia.org/wiki/File:Mastodon_Logotype_(Simple).svg

Whether the icon can be included as-is or needs some kind of visual overhaul/modification is a question for designers, which I really can't answer (I'm a developer)

Mastodon is Open Source Software and therefore I assume there will be no legal complications to include a Mastodon icon.

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by conradennis** [comment]
Hi @pReya we can definitely add Mastodon to the UI icon library. Can you please make an issue in the [UI icon repo](https://github.ibm.com/brand/ui-icons/issues) and we can get the ball rolling on that, thanks.

**Comment by pReya** [comment]
> Hi @pReya we can definitely add Mastodon to the UI icon library. Can you please make an issue in the [UI icon repo](https://github.ibm.com/brand/ui-icons/issues) and we can get the ball rolling on that, thanks.

Thanks for your reply. The link you posted requires me to login with some IBM specific credentials. I assume this is an internal GitHub instance? Any chance I can post a feature request without signing up for some IBM-specific account?

**Comment by conradennis** [comment]
@pReya no that repo is internal only but I can handle the request from here. I'll include the Mastodon icon in the next batch of ui icons I push to Carbon.

**Comment by tw15egan** [comment]
Thanks @conradennis 🎉

**Comment by conradennis** [comment]
here's the final SVG in the mean time: 
[logo--mastodon.svg.zip](https://github.com/carbon-design-system/carbon/files/10991504/logo--mastodon.svg.zip)
