### ISSUE TITLE
[Feature Request]: Investigation of a stable selector model for components

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#13300]
### The problem

Access to the DOM currently is based on classes and other means, which ultimately may have things like unit tests, e2e tests, a/b tests, personalization campaigns, etc, become brittle when UI code changes occur.

### The solution

The Carbon for IBM.com team has adopted early on a `stable selector` approach, which has since been heavily adopted as a model even outside of the `Carbon for IBM.com` library by the digital insights team in Marketing. 

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/docs/stable-selectors.md

This issue (which may ultimately become an epic) will explore a way of adding stable selector identifiers within the code base for the benefit of testing and campaigns.

### Examples

Carbon for IBM.com storybooks:

Web Components:
https://www.ibm.com/standards/carbon/web-componensts

React:
https://www.ibm.com/standards/carbon/react

### Application/PAL

Head of Engineering, Carbon Design System

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jeffchew** [comment]
@tay1orjones @sstrubberg we should align the contract between Carbon React and Carbon Web Components when looking into this. Issue created on that board:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10198

**Comment by tay1orjones** [comment]
The bulk of the previous conversation on this is in https://github.com/carbon-design-system/carbon/issues/9648
