### ISSUE TITLE
[Bug]: Modal button label wraps with incorrect alignment

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#13319]
### Package

@carbon/styles

### Browser

Chrome

### Package version

1.24.0

### Description

When text inside the modal buttons are long and wraps to two lines, the alignment of text labels are thrown off. Currently seeing below. Please note this bug is happening on modal size `xs` and `sm` as well so the button labels are really not that long, so the error is obvious. 

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/15144993/224026900-4577d86c-585e-4cc7-9a85-c5046cccc5f8.png">

Expecting button labels to be 16px from top of button:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/15144993/224027507-7335cf4b-18c7-4d1b-98fc-75e036dab4bc.png">

### Reproduction/example

This is what the modal looks like in Partner Portal right now:

![image](https://user-images.githubusercontent.com/15144993/224028315-b151bd2c-6cb9-4c39-8961-090744726d78.png)

### Steps to reproduce

1. Go to: https://react.carbondesignsystem.com/?path=/story/components-modal--playground
2. Type in a longer text in any footer button label in inspect

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Partner Portal / Carbon for Salesforce

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@shixiedesign pushed up a PR to fix this by setting all button text to align with the baseline. It will push all text down about `1px` even when not wrapping to align to the button baseline content box
