### ISSUE TITLE
Action-enabled unstructured lists

### ISSUE THREAD

**Issue by ceci-work** [carbon-design-system/carbon#1332]
### Summary

Unstructured lists have some in very handy to manage configuration information for an object (service, bucket, user, object. etc)

For that reason we would like to introduce the capability of adding ghost buttons at the top of the tables to help manage the creation and bilk items within it so the behavior is consistent with data tables.

### Justification

IBM cloud has a high need for data-dense configuration areas where a user can manage 'sub-items' within the context of a parent object, in he past this has led to the overuse of modals and branched-workflows that take the user out of context. 

We consider this capability will streamline content and allow users a global view of an items components and details in a clean and clear manner that also allows for editing in a very natural manner (tabbing between tables for example)

### Desired UX and success metrics

Describe the full user experience for this feature. 
The option to have ghost buttons to manage the items in a unstructured list will simply allow a user to add these on the top right area before the table begins:
![screen shot 2018-10-24 at 2 05 01 pm](https://user-images.githubusercontent.com/36859772/47454851-d9dc6a00-d795-11e8-9742-064f7650099f.png)

Also define the metrics by which we can measure success/failure for the user.
A good way to gauge success is by how much this pattern is adopted by other designers that had similar needs. (Can this be measured)

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

- Must have: ability to add action buttons that create an item in an unstructured list
(removed bulk actions--when needed use data tables)

### Specific timeline issues / requests

Whenever possible

_NB: The Carbon team will try to work with your timeline, but it's not guaranteed. The earlier you make a request in advance of a desired delivery date, the better!_

### Available extra resources

I can provide examples of the application of unstructured lists for this and variations to the design--there are samples in production of the unstructured listb being used for configuration data but none with the desired ghost button addition

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! I don't think any code in Carbon prevents you putting ghost buttons above structured list, but let us know if you think otherwise. CC'ing @IBM/carbon-designers just to ensure doing that is not is a no-no pattern.

**Comment by joshblack** [comment]
This is starting to feel very similar in scope to our Data Table, not sure if structured lists are meant to be used this way.

**Comment by aagonzales** [comment]
@ceci-work I didn't realize you were trying to take bulk action against the items in the structured list. I thought the buttons were just to add items to the structured list which I think is acceptable. 

If you're going to be doing editing and bulk action then I think you should be using a data table.

**Comment by ceci-work** [comment]
@aagonzales @joshblack  We can keep it scoped to adding items as thats the immediate need but i figure if there were a handful of items and a user eventually wanted to delete a small bunch it would be helpful to do in bulk--that said I don't mind individual deletion via an action menu on the row or an icon as the whole idea is for these to have no more than maybe 10 rows at the very most. Will adjust the request to only include addition :-)

One of the benefits of this  is to be able to have different types of items in each row so its a good point.

**Comment by ceci-work** [comment]
we can close this issue--the component was changed to a data table
