### ISSUE TITLE
[Bug]: datatable state manager not updating with new `rows` values such as `isSelected`

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/carbon#13326]
### Package

carbon-components, carbon-components-react, @carbon/colors, @carbon/icons-react, @carbon/motion, @carbon/themes, @carbon/type

### Browser

Chrome, Safari, Firefox, Edge

### Package version

colors: 10.33.0, icons-react: 10.49.0, motion: 10.25.0, themes: 10.48.0, type: 10.39.0, carbon-components-react: 7.50.0, carbon-components: 10.50.0

### React version

16.12.0

### Description

We also use 
"@carbon/ibm-cloud-cognitive" version being "0.87.3"

We are trying to make it so user can add a column above the column selected 
![Screenshot 2023-03-09 at 2 37 05 PM](https://user-images.githubusercontent.com/10100397/224176132-9a0a6b48-e4eb-4f45-932c-356f394a1efa.png)

But the issue is when we update our code properly with the new `isSelected` value it doesn't get updated on the state manager for datatable. I left a more thorough explanation video in the carbon slack repo https://ibm-analytics.slack.com/archives/C2K6RFJ1G/p1678392304145939 please use this video for understanding the issue as it's hard to explain in text. If needed, feel free to message me on slack and we can webex to go over issue more. 
The slack link should explain most of the issue and I hope a carbon dev can understand what I mean. 

Select column
![Screenshot 2023-03-09 at 2 37 05 PM](https://user-images.githubusercontent.com/10100397/224176178-598ad85c-4026-4b20-8e34-bf10e658f404.png)

add new column for above, this is what we see from carbon
![Screenshot 2023-03-09 at 2 38 08 PM](https://user-images.githubusercontent.com/10100397/224176272-e4e99762-dc5b-4cbc-8934-ef1b74646f07.png)

issue - new column is being selected 
expected display
![Screenshot 2023-03-09 at 2 38 47 PM](https://user-images.githubusercontent.com/10100397/224176367-27249fa9-636a-4e3b-81f6-664120428597.png)

I go more into detail on steps to reproduce on why this is carbon issue. Everything from our end in the code appears to all be correct for the `rows` render of DataTable, I verified this numerous times and the conclusion I ended up with that this is an issue with the state manager for the `isSelected` property and how it is handled in `DataTable.js`

I checked this issue 
https://github.com/carbon-design-system/carbon/issues/6241 although it looks similar, I believe it is actually different than what I am going over. Also not duplicate because I go a bit more into detail for my scenario and usecase, thanks!

I saw this reply https://github.com/carbon-design-system/carbon/issues/6241#issuecomment-643283008 and I am hoping that this isn't the same for this scenario because it doesn't make sense to why the user would have to set up their own state manager than the one built into `DataTable` when this is carbon code having this issue. Just hoping this can be fixed and addressed, let me know if any questions. Thanks!

### Reproduction/example

- 

### Steps to reproduce

 I spent some time trying to get a sandbox set up and I couldn't get it and I also don't have a lot of time to spend on trying to do so since there is some custom parts that we have in our code that I would need to try to re-create on sandbox and I don't have the time to do all of this currently. But the issue remains to be on carbon end and I can't resolve the issue on my end due to this blockage. I'll do my best to explain without a sandbox, if more info is needed please contact me on slack. 

Essentially though

- Have a datatable, have it be able to add rows
- select a row. on the data table and have a custom batch action to appends a new row
- The new row should be appended above the selected row (which is per design on our issue) 
- The value `isSelected` should remain on the row selected and not on the newly appended row. 

So if I have 

<table>
<tr>
<th> Id </th>
<th> Column </th>
</tr>
<tr>
<td> 1 </td>
<td> row 1 </td>
</tr>
<tr>
<td> 2 </td>
<td> row 2 </td>
</tr>
<tr>
<td> 3 </td>
<td> row 3 </td>
</tr>
</table>

Say I select row 2 and add a new row
Step 1
<table>
<tr>
<th> Id </th>
<th> Column </th>
</tr>
<tr>
<td> 1 </td>
<td> row 1 </td>
</tr>
<tr>
<td> 2 </td>
<td> row 2 (isSelected set to true)</td>
</tr>
<tr>
<td> 3 </td>
<td> row 3 </td>
</tr>
</table>

Step 2 - add new row
<table>
<tr>
<th> Id </th>
<th> Column </th>
</tr>
<tr>
<td> 1 </td>
<td> row 1 </td>
</tr>
<tr>
<td> 2 </td>
<td> row 4 (New row) </td>
</tr>
<tr>
<td> 3 </td>
<td> row 2 (Should still have `isSelected` set to true in the rows)</td>
</tr>
<tr>
<td> 4 </td>
<td> row 3 </td>
</tr>
</table>

The output I am seeing is 

<table>
<tr>
<th> Id </th>
<th> Column </th>
</tr>
<tr>
<td> 1 </td>
<td> row 1 </td>
</tr>
<tr>
<td> 2 </td>
<td> row 4 (New row) - has `this.state.rowsById` for `isSelected` set to true, but this shouldn't be the case </td>
</tr>
<tr>
<td> 3 </td>
<td> row 2 (No longer has `isSelected` set to true visually, but in the data for `this.props.rows` it does)</td>
</tr>
<tr>
<td> 4 </td>
<td> row 3 </td>
</tr>
</table>

I put breakpoints on DataTable.js and went through, here is the first instance that we see `this.state.rowsById` get the new row added using the same scenario provided above
![Screenshot 2023-03-09 at 2 26 29 PM](https://user-images.githubusercontent.com/10100397/224174492-50023d8f-ae03-4d21-a803-5b1ec5d2c57b.png)

Now this doesn't make sense (to me at least) why for index `1` why `isSelected` is being set to `true` because this doesn't reflect accurately to the data being sent and no where through the various breakpoints does this `isSelected` ever gets updated. 

See `this.props.rows`
![Screenshot 2023-03-09 at 2 29 28 PM](https://user-images.githubusercontent.com/10100397/224174870-4b1cf614-3a83-42aa-97a2-57f7cff10e69.png)

`column_4` at index 1 says `isSelected` is false, but for index 2, column_2 `isSelected` is set to true as it should be. This is correct. 
The state manager never updates with this new info as `isSelected` is not correct. 

This is the best example I can give, if more info is needed. Please slack me (slack is on that thread) and we can webex or discuss further on the issue. 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM DataStage

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by AustinGitHub** [comment]
Adding on more info
When we hit the `+` for the new column, this is the new rows we pass through 
![Screenshot 2023-03-09 at 3 07 44 PM](https://user-images.githubusercontent.com/10100397/224181030-12670f55-36a0-44d6-addc-21ebbfcafac4.png)

See how `isSelected` is set for both with the proper info 
![Screenshot 2023-03-09 at 3 08 58 PM](https://user-images.githubusercontent.com/10100397/224181091-05bcab20-bd64-4940-b9f8-3e45ec508196.png)


like mentioned above, datatable state manager doesn't update with this new info properly for `isSelected`

**Comment by tay1orjones** [comment]
Thanks for the extensive details in this report. Do you have an idea of where in the Carbon DataTable source the issue is stemming from? A minimal reproduction would be helpful in that regard to narrow down what exactly the issue is.

**Comment by AustinGitHub** [comment]
Hi, just saw this. the source of this issue seems to step from DataTable.js as when I was debugging everything was pointing towards this file where the changes occurred. If you follow the slack thread I have videos in there trying best to explain the situation, I couldn't get a sandbox set up for this unfortunately because it partially relies on some of the code we have for adding columns and batch action functions, but the core issue still coming from carbon though. The `isSelected` doesn't update properly in dataTable.js on the `this.state.rowsById`. It only gets updated on `this.props.rows` when the `isSelected` is different. If we need to, I can set up a webex meeting to go over this, let me know. Thanks!

**Comment by tay1orjones** [comment]
I created a sandbox to illustrate what I think you're running into.

https://stackblitz.com/edit/github-wlryhj?file=src%2Fdata.jsx,src%2FApp.jsx

The issue is row id's need to be treated as unique, they're essentially a `key`. You're passing in new rows, some of which use the same id as rows in the previous render. There's no way for the state manager to know which row to apply the `isSelected` state to other than to use the `id`, so it's applying it to the row with that same id.

You can see in the sandbox example that if I add new rows with duplicate id's, the state is shared amongst all of them. This same principle applies to rows that reuse id's from previous renders. If I instead create rows with a new random/unique `id`, there is no problem.


https://user-images.githubusercontent.com/3360588/226729385-cc8f90a4-be01-4c2d-b2d8-6059a29210e1.mov

I'd primarily recommend not using index values as row ids. You probably could bypass the issue by concatenating the existing id with other data in the row (column name, data type, description, etc.) and using that value for `id` on each row.

If you're unable to use unique ids for rows, you can instruct react to throw away the previous rendered DOM by placing a `key` on the DataTable and changing it's value when you want to discard the old state/DOM.
