### ISSUE TITLE
[Question]: is it possible to change position alignment for the "copy button"'s tooltip in the CodeSnippet component?

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#13329]
### Question for Carbon

On certain occasions, the tooltip appearing below the "copy" button in the CodeSnippet goes off the screen, hence it would be nice to align it in such a way to avoid it. Is it currently possible? Or could it be considered an improvement?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Yep, the props are spread all the way down to the Tooltip so it works by putting `align` on the CodeSnippet. [Here's an example](https://stackblitz.com/edit/github-737hdm?file=src%2FApp.jsx). Hope this helps!

**Comment by marcellobarile** [comment]
@tay1orjones thanks for the quick response, but this does not seem the case for the `type="multi"`. Could you confirm?
