### ISSUE TITLE
Platform indexing: Broaden storybook feedback circle

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#13325]
Meet with dotcom squad to playback our work and gather feedback and ideas on storybook variants.

**Comment by aubrey-oneal** [comment]
Guiding questions:
- Do you find renaming default useful?
- Would you benefit from an examples folder?
- What would make the most sense to a designer?
- Do you find it helpful to have a distinction between variants and prop configs?


Notes:
- Example folder: Overall support of this idea when there are multiple examples. "I don’t know that the generic 'example' story name helps. What can we do in the canvas, docs to help guide people. We could go beyond the variants. Without the folder it implies there is a set number of things you can do. But maybe playground helps. 
- ‘With’ - it makes sense in Basic list, but I can’t see it in Progress bar. A combo of naming conventions?
- Common question: “Can I do this” Yup it’s right here in the storybook. 
- Naming convention: Names could get long for dotcom. i.e. horizontal and vertical. The names do wrap, so they are down to try out our longer naming convention.
- Nesting: The new component sets and additional example folders is a lot of nesting but at least it’s all together. Better discoverability.
- I wonder if Patterns needs to go through this organizational work as well. Do examples have patterns? 
- You have to have a separate environment outside of storybook for integration patterns testing in an isolated way. 
- Rich: recently re-configured booleans to save space on the library in terms of memory. Might clash with
