### ISSUE TITLE
[Question]: Issues accessing flatpickr calendar instance

### ISSUE THREAD

**Issue by jeanbu** [carbon-design-system/carbon#13333]
### Question for Carbon

**Package**
@carbon/react

**Browser**
Chrome

**Package version**
@carbon/react: 1.19.0

**React version**
16.2.0 and 18.2.0

**Description**
Following [#12864](https://github.com/carbon-design-system/carbon/pull/12864) I have tried to open the calendar when clicking a button, but it's not working. 

`<Button onClick={() => datePickerRef.calendar.open()}>
        Open calendar
      </Button>
      <DatePicker
        dateFormat="d/d/Y"
        datePickerType="single"
        ref={datePickerRef}
        onClick={() => datePickerRef.calendar.open()}
        className="custom-datepicker"
        locale={{ firstDayOfWeek: 1 }}
      >
        <DatePickerInput
          id="date-picker"
          labelText="Select a date"
          placeholder="mm/dd/yyyy"
        />
      </DatePicker>`

How could this be achieved?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@jeanbu I think your call needs to be on `ref.current.calendar.open();`. [Here's an example](https://stackblitz.com/edit/github-seprey?file=src%2FApp.jsx)

Hope this helps!
