### ISSUE TITLE
[Bug]: Not able to add isActive for the element <SideNavLink> in carbon react v10. 

### ISSUE THREAD

**Issue by sivagurunathan-thangaraj-ibm** [carbon-design-system/carbon#13336]
### Package

carbon-components-react

### Browser

Chrome

### Package version

V7.25.0

### React version

v18.2.0

### Description

In the component sideNav, I am not able to add the isactive property for the element <SideNavLink>. While adding, getting the issue as mentioned in the image.

![image](https://user-images.githubusercontent.com/127757549/224717948-d1dc98e4-a57c-479e-ad5e-affa242563b0.png)

### Reproduction/example

n/a

### Steps to reproduce

Mentioned in the screenshot

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi, thanks for reporting this. In this case `isActive` is used within `SideNavLink` but is not defined in the proptypes. We need to provide this prop in the proptypes to get rid of this warning. This should be just a warning though and not block you.
