### ISSUE TITLE
[Bug]: FileUploader allows uploading the same file twice

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#13341]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.24.0

### React version

17.0.2

### Description

FileUploader is currently allowing the user to upload the same file twice
<img width="582" alt="image" src="https://user-images.githubusercontent.com/40550942/224832161-a4d9f088-f2c3-4af6-9f15-0d20040cfc64.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-fileuploader--default

### Steps to reproduce

Using FileUploader:

1 - Upload File A
2 - Uploade File B
3 - Upload File A again
4 - Notice the component now displays file A twice, I believe it should ignore an uploaded file if it is being uploaded for the second time and it hasn't been deleted

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by modaslam** [comment]
Is anyone looking into this issue?

**Comment by tw15egan** [comment]
Is this a Carbon issue or end user issue? Does the native `input type="file"` allow multiple uploads?

**Comment by francinelucca** [comment]
@tw15egan  we're  using a separate state in the component to concatenate what gets uploaded to the input, I think we just have to do a check for existing files before merging the states.
<img width="487" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/6f1ea1ce-b300-4ea6-a548-0a863e8d88ec">
