### ISSUE TITLE
[Bug]: Copy to clipboard tooltip truncated with type=multi CodeSnippet component

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#13346]
### Package

@carbon/react

### Browser

Chrome

### Package version

^1.24.0

### Description

When the `CodeSnippet` component is configured with `type=multi`, the "Copy to clipboard" tooltip gets truncated and it's not possible to change its alignment.

See: https://stackblitz.com/edit/github-737hdm-eih3ir?file=src%2FApp.jsx

### Screenshots

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1809476/225067810-69da3480-0fd6-4f66-9e52-2521f89f02d0.png">

### Steps to reproduce

- Implement a CodeSnippet component with `type=multi`
- Make sure that this component gets the 100% of the window's width (or simulate other cases like placing it at the right side of the screen)
- Note that the tooltip appearing on the mouse over the copy button gets truncated

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
This is working in the latest version of @carbon/react https://stackblitz.com/edit/github-737hdm-evnbzc?file=src%2FApp.jsx
