### ISSUE TITLE
[Bug]: ExpandableTile does not forward a ref

### ISSUE THREAD

**Issue by phtoussaint** [carbon-design-system/carbon#13340]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.17.0

### React version

v18.2.0

### Description

 Looks like ExpandableTile, and maybe Tile too, does/do not forward a ref:
 
 I set ref={ref}, on ExpandableTile (also tried on Tile) but ref.current is still "null" 

### Reproduction/example

https://stackblitz.com/edit/github-5hp6sj?file=src/App.jsx

### Steps to reproduce

1. get a ref with React useRef: const ref=useRef(null)
2. set Component's ref like ref={ref}
3. debug and check ref.current (i.e in a button handler function)
4. ref.current is always null

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by pratikkarad** [comment]
Hi, I would like to try my hands at this.
