### ISSUE TITLE
Tabs: Aligning to the Grid design guidance

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13351]
### Acceptance criteria

- Finalize design spec and guidance.
  - [x] Explore left UI shell implications (non-grid influencers and grid influencers)
  - [x] Define main design guidance rules (Responsive behavior / Truncation / etc.)

**Comment by laurenmrice** [comment]
## Design specs and guidance

**Implications of UI shell**
- Decision to have the same design guidance for UI shell grid influencer and non-grid influencer situations.

**Breakpoints**
- Max, XLG, LG: Use 8 grid-aware tabs or less.
- MD, SM: Grid-aware tabs will be automatically changed to auto-width tabs.

**Responsive behavior**
- Tabs should not wrap to multiple lines and stack.
- Include truncation of tab labels with ellipsis (...).
- Horizontal scroll containers when needed.

-----

<img width="1181" alt="Screen Shot 2023-04-07 at 12 47 04 PM" src="https://user-images.githubusercontent.com/43969356/230646162-4a340464-21a6-448d-9f6e-0ff3789a2f23.png">



<img width="1121" alt="Screen Shot 2023-04-07 at 12 46 30 PM" src="https://user-images.githubusercontent.com/43969356/230646074-28856df5-278e-4b78-8ec5-5020233c7588.png">
