### ISSUE TITLE
Form field components - superfluous border sometimes appearing under Microsoft Edge

### ISSUE THREAD

**Issue by sjhowell** [carbon-design-system/carbon#1336]
Sometimes, but not always, extra borders are appearing in form field components (such as select, text input, and text area) when used under Microsoft Edge. 

The following screenshots were taken from the Carbon website, and show the issue. In all cases the components should only have a bottom border, and yet sometimes show a left-hand and/or right-hand border:

![image](https://user-images.githubusercontent.com/40432849/47515257-4af54d80-d87a-11e8-9694-938e0139d1d8.png)

![image](https://user-images.githubusercontent.com/40432849/47515277-5cd6f080-d87a-11e8-9635-75719babd87b.png)

To reproduce the issue, go to the Carbon website using Microsoft Edge, and if the components look okay, try resizing the width of the browser a few times, and eventually the bad border styling should appear.

Doing some investigation, it looks like it might be something to do with how Edge handles the `box-shadow` CSS class. Maybe it's an Edge defect. However, it would be nice if it could be worked around in Carbon if possible.

**Comment by sjhowell** [comment]
What kind of activity are you after? If this is a defect, then shouldn't it be worked on? I don't think simply closing it is the right way to handle defects.

**Comment by dakahn** [comment]
Too right @sjhowell we definitely want to capture all our defects 👍 

This issue is triaged and in our backlog now -- though it is priority low, but if you'd like to submit a PR that'd be swell.

**Comment by sjhowell** [comment]
Thanks @dakahn. Sure - if I can find the time (not sure how likely that is mind you!) and I can come up with a fix I'll create a PR.
