### ISSUE TITLE
Storybook 7: Explore update

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13379]
Storybook v7 [has been released](https://github.com/storybookjs/storybook/releases/tag/v7.0.2). This issue is for updating the monorepo to v7. We should defer as many optional migrations as possible so we can get on v7 as quick as possible and then iterate from there.

```[tasklist]
- [x] View and use the [migration guide](https://storybook.js.org/docs/react/migration-guide#page-top)
- [x] Run the migrator script from the docs
- [x] Fix/report/mitigate any issues
- [x] Can we defer mdx2 update? Is mdx2 update large?
- [x] Remove reactOptions, legacyRootApi: false in main.js
```

**Comment by francinelucca** [comment]
Subcomponent tables: 
<img width="673" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/aa9f1438-422b-428b-9b08-6a5cdd2ac149">
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-docs-changes
