### ISSUE TITLE
[Bug]: Clicking on file uploader hangs browser 

### ISSUE THREAD

**Issue by number-00** [carbon-design-system/carbon#13376]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.56.0

### React version

16.14.0

### Description

When I am uploading a file of type .jar with file uploader, the browser hangs while trying to open the file explorer right after clicking 'Add file' button
https://carbondesignsystem.com/components/file-uploader/usage/

it works fine after a while.

### Reproduction/example

https://codesandbox.io/s/relaxed-shockley-meglr0?file=/index.js

### Steps to reproduce

1. Download a file of type jar 
2. Immediately click on the add file button while it is being downloaded or right after it completes
3. browser hangs
4. after a while it opens file explorer

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sstrubberg** [comment]
hey @number-00! Thanks for submitting this issue. Three of us have tried to repro and can't seem to make this bug happen. You are welcome to drop by our [dev office hours](https://ec.yourlearning.ibm.com/w3/event/10322733) and we can take a look together. Closing for now!

Ref:
https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1678829445438889
