### ISSUE TITLE
Grid docs: Dev audit of "implementation" grid docs page

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13387]
#### Acceptance Criteria

- What's missing?
- What's confusing?
- What could we remove/change/add to help?
- Touch base with Design about their audit of the 'overview' page
- Playback findings at the end of the sprint

**Comment by alisonjoseph** [comment]
- Add new "Code" page, follow structure from other element & component pages
- Rename "Implementation" to be "Usage"
  - remove code samples from this page
  - see design audit for details https://github.com/carbon-design-system/carbon/issues/13388
