### ISSUE TITLE
ContainedTabs Secondary Label: Update website docs

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13389]
With the secondary label now available via a prop https://github.com/carbon-design-system/carbon/pull/13366, the docs page on the website needs updated

![image](https://user-images.githubusercontent.com/3360588/226711274-8fcd694a-3e8d-4af2-8aef-5ba7beb8b543.png)

There may be other content that needs updated as well.

**Comment by kingtraceyj** [comment]
@tay1orjones working on the content currently for this and i noticed that our notification as well as the docs content use the term `line tabs` but the storybook is using the term `default` for line tabs. is there a discrepancy there?

![image](https://user-images.githubusercontent.com/20582179/235763280-5fc0e3dc-2254-4777-a169-fa639b2b83a6.png)

**Comment by tay1orjones** [comment]
Hey sorry for the delay - I'll put my half of our slack conversation in here for posterity!



> Yeah secondary labels and icons are available as props and no longer require manually composing components together. We can remove that language from the website.
> 
> For the line tabs question - there’s no explicit “line tabs” mode in the code. It’s just the default state of TabList. Contained tabs are configured via the contained prop, that can be true or false/omitted
> 
> We’re also going to revisit the concept of “default” stories in the storybook once we’ve updated to storybook v7. https://github.com/carbon-design-system/carbon/issues/13225
> 
> 
> It’s similar to the situation with ProgressBar, it’s “indeterminate” by default and then becomes “determinate” when you provide it a value prop.
> 
> ```js
> <ProgressBar label="Progress bar label" /> // indeterminate
> <ProgressBar label="Progress bar label" value={75} /> // determinate at 75%
> ```
> 
> Here’s how that looks in the storybook right now with “default”  - [link](https://react.carbondesignsystem.com/?path=/story/components-progressbar--default)
> 
> After working with @aubrey-oneal on the variant exploration stuff, here’s how we’d like it to look (this was from a [WIP PR](https://github.com/carbon-design-system/carbon/pull/13259) we had to close without merging due to the storybook v7 upgrade) - [link](https://deploy-preview-13259--carbon-components-react.netlify.app/?path=/story/components-progressbar--default)
