### ISSUE TITLE
[structured list] selection variant border is missing a piece

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#13383]
There is a section on the right side of the structured list where the border is wrong, also visible on hover. Border should extend all the way across. 

<img width="830" alt="Screenshot 2023-03-21 at 12 22 53 PM" src="https://user-images.githubusercontent.com/2753488/226691353-ee2eedf3-484e-4453-913f-221b7517fa8a.png">

**Comment by cknabe** [comment]
I'm not seeing this on the master branch? 
I also see the entire bottom-border is hidden on hover.

![image](https://user-images.githubusercontent.com/13582620/227586695-6a104669-4067-492f-88d1-6f5629dea7a5.png)

**Comment by cknabe** [comment]
Brave [Version 1.48.164 Chromium: 110.0.5481.100 (Official Build) (64-bit)](https://brave.com/latest/)
