### ISSUE TITLE
<AVT>The 'headers' attribute value "expand" does not reference a valid 'id' in this document

### ISSUE THREAD

**Issue by zhanttbj** [carbon-design-system/carbon#13393]
### Package

carbon-components

### Browser

Chrome

### Package version

V10.*.*

### Description

Problem: The 'headers' attribute value "expand" does not reference a valid 'id' in this document

### Reproduction/example

carbon-components

### Steps to reproduce

===== ENVIRONMENT =====
IBM CI 162 Checkpoint Violation: IBM 4.1.2 Name, Role, Value
https://www.ibm.com/able/requirements/requirements/#1_3_1

Test Tool Type: IBM Accessbility Checker

===== DEFECT DESCRIPTION ===== 
Problem 1 : The 'headers' attribute value "expand" does not reference a valid 'id' in this document
Problem 2: Multiple elements with "region" role do not have unique labels
Problem 3: Accessible name does not match or contain the visible label text

=====STEPS TO REPRODUCE =====

Go to https://dev.console.test.cloud.ibm.com/
Open a CIS service.
Go to 'Metrics' page
Go to 'Firewall' tab
===== EXPECTED RESULT =====
 Pls check the followed link for detail:
https://www.w3.org/WAI/tutorials/tables/multi-level/
https://www.w3.org/TR/wai-aria-1.2/
https://www.ibm.com/able/requirements/requirements/#2_5_3
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA13

Problem 1
<img width="822" alt="图片" src="https://user-images.githubusercontent.com/110212663/227101670-321459fb-fa6d-4901-b633-b8075477afcd.png">
Problem 2:
<img width="821" alt="图片" src="https://user-images.githubusercontent.com/110212663/227101713-72a874fb-40ee-4cf7-93aa-e400d5c312a4.png">
Problem 3:
<img width="825" alt="图片" src="https://user-images.githubusercontent.com/110212663/227101740-4df30a86-2c99-4a76-8f84-da4b578bbe10.png">

This issue is from https://github.ibm.com/Bluemix/core-ui-cdl/issues/4170, but should be related to Carbon, pls help to check and fix, thanks

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

CIS service

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This has been fixed in v11 https://github.com/carbon-design-system/carbon/pull/12262

I think it could be backported to v10, but I'm not 100% sure.
