### ISSUE TITLE
[Bug]: Visited links inside `Toggletip` don't receive inverse color token

### ISSUE THREAD

**Issue by btepe** [carbon-design-system/carbon#13400]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.25.0

### Description

Links inside a `Toggletip` have a low contrast after they have been visited compared to the inverse background they are displayed on. They seem to receive the default color of the active theme, although the `Toggletip` component uses an inverse background color. Therefore the color of the visited link should be adjusted to the inverse color as well. This has already been done for the link in the default state, but the visited state seems to have been missed.

### Screenshots

Default visited link:
<img width="482" alt="Screenshot 2023-03-23 at 18 13 35" src="https://user-images.githubusercontent.com/24353185/227283659-685c1181-4316-4c7c-be69-545c83ed7c5e.png">

Visited link when hovering:
<img width="482" alt="Screenshot 2023-03-23 at 18 12 33" src="https://user-images.githubusercontent.com/24353185/227283119-5c90a7fe-681c-437c-9cea-d37cc4361165.png">

### Steps to reproduce

1. Visit [React Storybook - Toggletip example](https://react.carbondesignsystem.com/?path=/story/components-toggletip--default&globals=theme:g10)
2. Click on Toggletip to open
3. Open link inside Toggletip panel to get visited state

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
<img width="526" alt="Screenshot 2024-02-14 at 8 38 46 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/61f8772e-2f13-42d5-b1e6-e07775bdb99d">
We are running into this issue on the website.

**Comment by alisonjoseph** [comment]
This is only broken on `:visited` links inside of tooltip
