### ISSUE TITLE
[Combobox unique value]: Research the landscape

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13412]
Research task to determine what other design systems are doing in the space of adding unique or new values to combobox.

```[tasklist]
- [x] Review other external implementations and guidance (spectrum, chakra, canvas, seek, mui, polaris, etc.)
- [x] Review internal implementations (Cloud PAL, IBM for Products PAL, etc)
- [x] Document findings
- [x] Playback findings to team to determine next steps and path forward (spec creation)
```

**Comment by thyhmdo** [comment]
ComboBox enhancements include:
- Accept new value users type in the text box (without adding it to the option list)
- Make sure props work for Filtering with the first initial letter and Autocomplete
- Add OnBlur so that it takes out the focus
