### ISSUE TITLE
[Bug]: dropdown stay open when sidebar retract 

### ISSUE THREAD

**Issue by broulaye** [carbon-design-system/carbon#13426]
### Package

@carbon/react, carbon-components, carbon-components-react

### Browser

Chrome, Safari, Firefox

### Package version

v1.2.0

### React version

v17.0.2

### Description

I've been using the sidenav carbon component https://react.carbondesignsystem.com/?path=/story/components-ui-shell--side-nav-rail and noticed that when you hover over it and open a drop down, when you move the mouse away the sidenav retract but the dropdown stay open, giving it a weird look. 
<img width="1726" alt="Screenshot 2023-03-28 at 4 18 42 PM" src="https://user-images.githubusercontent.com/13936493/228653108-812cd8b8-c407-470b-9e1a-2dae3d37ac8c.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-ui-shell--side-nav-rail

### Steps to reproduce

hover over the sidenav and open a drop down, when you move the mouse away the sidenav retract but the dropdown stay open

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Fax-ofJax** [comment]
Can i work upon this issue if no one else does?

**Comment by tay1orjones** [comment]
Yeah I can repro this on the current storybook. Not sure if this is a styling regression or not but it does need fixed.
