### ISSUE TITLE
MultiSelect (select all option): final design spec

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#13434]
##  MultiSelect (select all option) final design spec

- Create a final design spec for development. 
- Post the image of the specs in this issue.

**Comment by benjamin-kurien** [comment]
Use the following design spec for multiselect dropdown - default style

![Image](https://github.com/carbon-design-system/carbon/assets/158569631/bd2617e7-debd-40cb-8ec2-820a8445c7e8)

**Comment by benjamin-kurien** [comment]
PROTOTYPE: https://www.figma.com/proto/AWUdP82euUmLSLW7uOXusI/Multiselect---All?page-id=&type=design&node-id=2031-19117&viewport=-13008%2C-1511%2C0.28&t=epmpr698P76RsPLU-8&scaling=scale-down&starting-point-node-id=2031%3A19117&hide-ui=1
