### ISSUE TITLE
[Bug]: File name casing issue when cloning the project

### ISSUE THREAD

**Issue by webpro** [carbon-design-system/carbon#13431]
### Package

@carbon/react

### Package version

latest

### Description

File name casing issue when cloning the project, might be problematic elsewhere too:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'packages/react/src/components/Skeleton/Docs/overview.mdx'
  'packages/react/src/components/Skeleton/docs/overview.mdx'
```

### Reproduction/example

N/A

### Steps to reproduce

```
git clone git@github.com:carbon-design-system/carbon.git
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@webpro are you on windows or mac?

**Comment by webpro** [comment]
Mac. Not an issue for me.
