### ISSUE TITLE
[Bug]: <FilterableMultiSelect>  Selection pill does not clear when item state changes

### ISSUE THREAD

**Issue by EllenBinZhang** [carbon-design-system/carbon#13437]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v10.50

### React version

17.0.2

### Description

When change the item state for FilterableMultiSelect with external button, the dropdown list updated , but the pill remains unchanged.

### Reproduction/example

https://stackblitz.com/edit/github-gxe1r6?file=src%2Fmain.jsx

### Steps to reproduce

Please follow the example at : https://stackblitz.com/edit/github-gxe1r6?file=src%2Fmain.jsx

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment]
Confirmed issue can be reproduced. Adding `needs refined` tag to discuss what the desired behavior would be here...

**Comment by tay1orjones** [comment]
@EllenBinZhang `selectedItems` is internal state derived from the initialSelectedItems and/or interaction with the component. If you want to switch out `items` and also reset the adjacent state of the pill, use a `key` on the FilterableMultiSelect and change the value of the key to instruct React to throw away the existing component tree and rebuild a new one.

Here's an example https://stackblitz.com/edit/github-gxe1r6-askj7v?file=src%2FApp.jsx
