### ISSUE TITLE
[Bug]: Hardcode for help instructions 

### ISSUE THREAD

**Issue by wlinacdl** [carbon-design-system/carbon#13455]
### Package

carbon-components

### Package version

Latest version

### Description

In IBM Cloud DNS CLI the string: "Help about any command", "help for zones" could not be translated. According IBM Cloud DNS Dev team response it is carbon issue. 

![image](https://user-images.githubusercontent.com/16383295/229428465-a1513826-ee28-412b-aa8b-d15899c8dd59.png)

### Reproduction/example

NA

### Steps to reproduce

1. Install IBM DNS CLI plugin 
2. ibmcloud api https://test.cloud.ibm.com/
3. ibmcloud login –sso
4. Enter any command with help instruction. For example:
- bx dns help
- ibmcloud dns custom-resolver-location-reorder
- ibmcloud dns permitted-networks -h

The string: "Help about any command", "help for zones" could not be translated. 

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@wlinacdl I'm not sure how this could be an issue stemming from Carbon. Could you elaborate and provide an isolated reproduction in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), and post the link back here?

**Comment by tay1orjones** [comment]
Let us know if you can reproduce this in stackblitz and we can reopen
