### ISSUE TITLE
ToggleSkeleton: Broken Visuals 

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#13459]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.26.0

### React version

^17.01.1

### Description

ToggleSkeleton looks broken when rendered:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/40550942/229530113-3599fc77-cc0d-41bc-836e-c6b8591833c4.png">

### Reproduction/example

https://stackblitz.com/edit/github-g7t3qu?file=src/App.jsx

### Steps to reproduce

Open Stackblitz and issue will be apparent on render

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sstrubberg** [comment]
Add story for ToggleSkeleton component inside Toggle folder
https://react.carbondesignsystem.com/?path=/story/components-toggle--default

**Comment by sstrubberg** [comment]
REF: [design spec](https://github.com/carbon-design-system/carbon/issues/13485)

**Comment by modaslam** [comment]
Can this issue be taken up?

**Comment by sstrubberg** [comment]
Absolutely @modaslam. See the design spec above for reference.
