### ISSUE TITLE
Slider validation: Design spec

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#13477]
- [x] Initial design research and design iterations: [Slider validation figma](https://www.figma.com/file/xpihYl4zeol2feuLO68zR1/Slider-validation?node-id=0%3A1&t=8zwWG13doJGHnnqU-1)
- [x] Play back to design team
- [x] Finalize spec [General slider figma](https://www.figma.com/file/hDWsXH5qnARQmW5pxFR8D3/Slider?node-id=203%3A27298&t=VP61wvYLAswNJOVz-1)

**Comment by kingtraceyj** [comment]
Final specs ([Figma file](https://www.figma.com/file/hDWsXH5qnARQmW5pxFR8D3/Slider?node-id=203%3A27298&t=VP61wvYLAswNJOVz-1))

No changes in the UX—Slider track and thumb act as they do currently, adjusting when typing
<img width="688" alt="Screen Shot 2023-04-14 at 2 33 21 PM" src="https://user-images.githubusercontent.com/20582179/232139116-465b9492-c9ce-4f9c-b175-cab5a5503e89.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/20582179/232139312-13725f99-7ddc-40bd-9683-28ab500b25a9.png">

**Comment by kingtraceyj** [comment]
@laurenmrice and I think it would be valuable to add the warning state as well:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/20582179/232647789-42083ee1-cd42-43d2-b006-603f8124ccbc.png">
