### ISSUE TITLE
[Bug]: Checkbox click event with modifier key

### ISSUE THREAD

**Issue by stanley-regnard** [carbon-design-system/carbon#13484]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.24.0

### React version

18.2.0

### Description

Context: we are using the Checkbox component to select items, where shift+click can be used to select multiple items at once.

Using Firefox, clicking on a Checkbox while pressing any modifier key (ctrl, alt, or shift) will not fire the onClick event.
Works fine with Chrome and Edge.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-checkbox--default

### Steps to reproduce

Click on a Checkbox while pressing any modifier key.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment]
Confirmed issue can be reproduced

**Comment by tay1orjones** [comment]
Yeah I think for now adding a wrapper isn't feasible as it would modify the DOM. Since we can't otherwise control how the browsers treat this behavior, I think we'll consider this blocked by the browser implementation.
