### ISSUE TITLE
[Bug]: IconButton enter/leave tooltip delay is longer in v11

### ISSUE THREAD

**Issue by glapadre** [carbon-design-system/carbon#13487]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.15.0

### React version

18.2.0

### Description

When using IconButton in Carbon V11 the tooltip on hover is delayed/lagging compared to V10. 
This was first noticed in a IBM PAL [ticket](https://github.ibm.com/CDAI-design/pal/issues/1141) in the Productive card v2 section. 

V10 Example shows snappy tooltip (https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-cards-productivecard--supplemental-bottom-bar)
V11 Example shows delayed tooltop: (https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-cards-productivecard--supplemental-bottom-bar)

### Reproduction/example

https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-cards-productivecard--supplemental-bottom-bar

### Steps to reproduce

Follow the link above and quickly hover over the edit and delete Button Icon back and forth. 

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@glapadre The delay is intentional to improve accessibility of the tooltip. It is configurable via the `enterDelayMs` and `exitDelayMs` props. It's documented [here in storybook](https://react.carbondesignsystem.com/?path=/docs/components-tooltip--default#customizing-the-duration-of-a-tooltip). Hope this helps, let us know if you have other concerns or questions.

**Comment by glapadre** [comment]
Thanks for the clarification @tay1orjones!
