### ISSUE TITLE
[Feature Request]: Notification support for multiple errors/values

### ISSUE THREAD

**Issue by CassidyJensen** [carbon-design-system/carbon#13486]
### The problem

There is an occasional case where a user has multiple errors return. Current notifications do not support multiple values for errors, it only shows one "title" "subtitle" pair. Creating a bunch of separate notifications does not make for a good user experience. 

### The solution

Ideally I would like a navigator attached to the Notification component that allows for the user to flip through different errors. This will also require an additional (optional) prop or maybe a change to the current props that would allow for an array of title subtitle pairs instead of just one. 

Example implementations:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/45407808/230192349-e991aa3c-047d-4dbd-9476-ddd5cbfd37d0.png">
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/45407808/230192906-228b771f-62dd-435c-a95b-6ec44cacd0f0.png">

Neither of these examples are the ideal design, but workarounds that have been used. I think the navigator arrows would ideally be placed to the left of the X, though that is open to discussion and what fits best with design standards.

### Application/PAL

Security Verify

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Thanks for opening this @CassidyJensen. I just pinged the design team to get their thoughts. I'll keep you posted on when/if we can take this one on.

**Comment by sstrubberg** [comment]
Have you tried using our [Notification panel](https://carbondesignsystem.com/patterns/notification-pattern/#notification-panel)?

**Comment by sstrubberg** [comment]
@CassidyJensen Hit me up if the comment I left doesn't address your request. Happy to take another look. Closing for now.

**Comment by CassidyJensen** [comment]
Hi @sstrubberg! Sorry for not getting back sooner. 

I have looked at the notification panel before - but our product is currently unable to support the requirements to use it. I think it would be nice to add, but unfortunately it would be low priority. 

That being said I think there is still something unique about having a notification with multiple values. It is not multiple items that have returned errors, it is one item that has returned several errors. Since stacking these items isn't ideal and I still want it to keep its identity and association with one specific action, I think there is a potential benefit to having multiple values. 

Example case: There is a large CSV that is being uploaded. Our API identifies 4 sections with invalid values. The API returns four errors with information that provides details on what sections are invalid and why. Rather than stacking the errors, I think it would make sense to have one Notification that allows you to switch between them. This allows us to provide specific feedback to the user. Even with the notification panel it looks like that would be returning 4 unique notifications rather than 1 related item. 

I am not sure how common it would be to have cases where this would be useful, but our product currently uses it in two locations.

**Comment by aagonzales** [comment]
@CassidyJensen I understand what you're getting at but I'm not sold on the solution yet (to be a core component enhancement). I would like to see more research on this solution. How are notifications like this done out in the industry? Is this a standard solution? Can you provide examples?

I also have accessibility concerns. If only one is shown, how are the hidden ones presented to keyboard and screenreader users? Also, visually, it's not super obvious either and there isn't a way to view them all at once. What if the messages were similar and needed to be compared? Can these notifications be validated in real-time, and if so, how does the user know which issue is currently being addressed?

To that end, I think it's valid if this is the solution your team builds to solve your problem, but before adding it as a universal pattern, I would like some further research, validation, and accessibility reviews on it. You are welcome to come to our [office hours](https://ec.yourlearning.ibm.com/w3/event/10323408) to explain the concepts and answer further questions. We also have an accessibility expert on those calls.

**Comment by CassidyJensen** [comment]
After further investigation, I have decided against the necessity of having this available. Although it would be a nice to have temporary feature, I think it is just that: Temporary. The best case seems to be transitioning our UI to use the notification panel to display these messages or more real-time implementation. There are currently several things preventing our ability to implement these items in our existing UI at the moment, but it is clear that they are the best solution. 

Thank you for your feedback.
