### ISSUE TITLE
[Bug]: DataTable renders twice when rows change

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#13489]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.26.0

### React version

18.2.0

### Description

When `props.rows` or `props.headers` of a DataTable is updated, the component re-renders twice.

The first render is initiated by React as it notices the props changed, the second re-render apparently happens because the DataTable uses `componentDidUpdate` to detect if the rows or headers changed. If so, it uses `this.setState` to sync the updated props with the internal state.

This causes the component to re-render first with the old state and then again with the new state.
It can lead to problems when within the render function of the DataTable one tries to access more meta information about a row, for example for additional styling or interactivity.

More concrete illustration: if I pass 6 rows into the DataTable and want to reference the original entry like so:

```jsx
// <DataTable rows={data} header={headers}>…

rows.map((row, index) => {
  const reference = data[index];

  return (
    <TableRow key={row.id}>…</TableRow>
  );
})
```

the reference would be undefined if I remove one row from the `data` array as the DataTable would render once with the old 6 rows, and only then with the new 5 rows. Obviously I can build fallbacks to ignore the issue the first time but that doesn't seem very elegant and can cause confusion when debugging.

### Reproduction/example

https://codesandbox.io/s/musing-cache-hmi9jq?file=/index.js

### Steps to reproduce

1. Click the "Include last row" button
2. A new row appears
3. Click the "Exclude last row" button
4. Error is thrown

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by pmweeks98** [comment]
I'll take this if thats ok
