### ISSUE TITLE
[Bug]: Default tabs do not have a hover state change

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#13490]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.26.0

### React version

^17.0.2

### Description

Default tabs do not have a visual change on hover (hover state)

https://user-images.githubusercontent.com/40550942/230505814-3d191e92-4ee6-468e-8b06-dcc0980da074.mov

Note: this may need a design spec (what should the hover state look like?)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-tabs--default

### Steps to reproduce

1. Hover over an unselected Tab
2. Notice no visual change indicating hover state

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by laurenmrice** [comment]
Design spec:
<img width="842" alt="Frame 1" src="https://user-images.githubusercontent.com/43969356/230620518-29e76326-4b1c-43f0-8366-48f2f785b80b.png">

**Comment by laurenmrice** [comment]
- I also noticed that Contained tabs have a hover state bug. 

**Contained tabs design spec**
<img width="842" alt="Frame 2" src="https://user-images.githubusercontent.com/43969356/230621668-b1e48277-9ae3-495a-99c3-f49b645c0ea7.png">
