### ISSUE TITLE
[Feature Request]: Storybook composition support

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#13506]
### The problem

I would like to use [storybook-composition](https://storybook.js.org/docs/react/sharing/storybook-composition) in our storybook instance to be able to seamlessly browse your reference instance.

When I, however, try that by adding the following section to our storybook config…

```js
module.exports = {
    ...config,
    refs: {
        'design-system': {
            title: 'Carbon Design System',
            url: 'https://react.carbondesignsystem.com',
            expanded: false,
        }
    }
}
```

…I only get this error

![image](https://user-images.githubusercontent.com/11244314/231219519-f587c411-2923-4f3b-8b4e-c38bc0d3f0c4.png)

- Clicking on the first entry in the popup takes me to your storybook instance and it renders fine
- Our storybook version is `7.0.2`

### The solution

I would like the feature to work as described in https://storybook.js.org/docs/react/sharing/storybook-composition

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by kubijo** [comment]
For what it's worth, I have noticed that when I do that setup, it tries to load the following files, so it might just be about enabling the json catalog build & possibly some CORS related tweak…
- `https://react.carbondesignsystem.com/index.json`
- `https://react.carbondesignsystem.com/stories.json`

![image](https://user-images.githubusercontent.com/11244314/231221406-9613ad34-aedd-4777-8f9f-ae73e582cd5d.png)

**Comment by tay1orjones** [comment]
@kubijo Interesting, do you know if composition supports different storybook versions? We're still on v6.5, I see you're on v7.
