### ISSUE TITLE
[Bug]: Checkbox's indeterminate prop is not working for controlled false value.

### ISSUE THREAD

**Issue by kunalphaltankar** [carbon-design-system/carbon#13516]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.19.0

### React version

17.0.2

### Description

I want have control on indeterminate prop of Checkbox.
If I set indeterminate={true} it is showing indeterminate state but I can't toggle it back to clear state by indeterminate={false}

### Reproduction/example

https://stackblitz.com/edit/github-gavh7p?file=src%2FApp.jsx

### Steps to reproduce

1. Set the indeterminate prop of Checkbox to true.
2. Try to reset indeterminate to false programmatically.

Result: Once checkbox is in indeterminate state you can't reset it.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Rishav1707** [comment]
The reason why the indeterminate prop is not working for the controlled false value in this code is that the handleIndeterminate function is not setting the indeterminate value correctly.

Shall I work on this issue? @kunalphaltankar

**Comment by Rishav1707** [comment]
I am unable to find the required file, can anyone help me?

**Comment by kunalphaltankar** [comment]
@Rishav1707 If you remove the and condition on line number 163 of [this file](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Checkbox/Checkbox.tsx), the issue will be resolved.

**Comment by francinelucca** [comment]
Confirmed bug can be reproduced

**Comment by Rishav1707** [comment]
> @Rishav1707 If you remove the and condition on line number 163 of [this file](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Checkbox/Checkbox.tsx), the issue will be resolved.

What should I use instead of `&&` in line number 163?

**Comment by pedesen** [comment]
> What should I use instead of `&&` in line number 163?

@Rishav1707 It should be removed like this:

```js
if (el) {
  el.indeterminate = indeterminate;
}
```

otherwise false and undefined values are not updated.
