### ISSUE TITLE
[Bug]: MultiSelect - items are not using `title` attribute

### ISSUE THREAD

**Issue by jakubfaliszewski** [carbon-design-system/carbon#13511]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.26.0

### React version

18.2.0

### Description

`title` attribute is not being added to the items of `MultiSelect` component.
As this works correctly for dropdown which items has only one children - `div` with a text - MultiSelect uses more complex structure with checkboxes, pseudo-elements etc. This causes calculation in [ListBoxMenuItem:L14  ](https://github.com/carbon-design-system/carbon/blob/e3eff64f219b16993ef6594a4c4b72416003097a/packages/react/src/components/ListBox/ListBoxMenuItem.tsx#L14) to always return `false`. Because of this `title` attribute is never being added.

I suppose that fixing this is not urgent, but I couldn't find any workaround.

Example of `Dropdown` and `MultiSelect` with the same items:
![multselect](https://user-images.githubusercontent.com/25402419/231404588-74364d0b-23e1-4b42-8599-68d920201a81.gif)

### Reproduction/example

https://codesandbox.io/s/silly-snyder-r2p4c5?file=/index.js

### Steps to reproduce

Use link with example or:
1. Create a new `MultiSelect` component:
```
<MultiSelect
      ariaLabel="MultiSelect"
      id="carbon-dropdown-example"
      items={items}
      label="MultiSelect menu options"
      titleText="MultiSelect title"
    />
```
2. Define items, one of them should use label long enough to be truncated:
```
const items = [
  "Item 1",
  "Item 2",
  "Item with a very long label that should be truncated and `title` attribute should be added"
];
```

_____

With this setup defined open the MultiSelect and hover over item with truncated text. With `title` attribute there should be browser tooltip.
Currently - as attribute is not there - nothing happens which makes it impossible to read full item's label.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment]
Confirmed issue can be reproduced
