### ISSUE TITLE
Use table elements for structured list component

### ISSUE THREAD

**Issue by hessendscher** [carbon-design-system/carbon#1352]
### Summary

While the name of the component has "list" in it, to me it's more a table, but somehow the existing HTML elements for a table are not used, instead regular non-semantic `div`s are used and then via CSS table properties are re-applied, like e.g. `display: table-row`. Even the used class names have e.g. "…-th", "…tbody" in it so to me this approach seems a bit weird.

### Justification

Using table elements would be the semantically correct way to display this kind of information and would help also accessibility IMO

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! An effort to understand the history led to an interesting read of #140 - Which seems to have started with `<table>` and switched to `display:table`. Therefore I guess the author had a reason, though I don't know what exactly it was, which prevents us from just making the switch. Good point, though, and may be a good future consideration.

**Comment by hessendscher** [comment]
I forked this repo and fiddled a bit with getting that table structure back in: https://github.com/hessendscher/carbon-components … still some issues with labels not occupying the available space in a table cell so if anyone has some ideas…
