### ISSUE TITLE
[Bug]: Unable to test @carbon/react derived components in storybook or to be used inside web apps

### ISSUE THREAD

**Issue by fahadahmed** [carbon-design-system/carbon#13531]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.27.0

### React version

v18.2.0

### Description

Unable to use storybook created components in an nx workspace that imports the @carbon/react components like Button, Tile etc as importing the created components results in `invalid hooks call` error. These components are also not testable due to the same hooks error within the storybook environment.

### Reproduction/example

Cannot replicate this in CodeSandbox or Stackblitz since the repo uses `nx` workspaces

### Steps to reproduce

- Clone the following [repository](https://github.com/fahadahmed/st-web)
- Install all packages in the repo
  - run `npm install` in root, apps/space-for-earth, libs/components
- Run `nx test components` from root to run the test suite
  - All test suites for components that import `@carbon/react` components will fail for various invalid hooks calls` 

When importing a Tile component that is dependant on `@carbon/react` Tile component:
<img width="1144" alt="Screen Shot 2023-04-17 at 12 18 06 pm" src="https://user-images.githubusercontent.com/1190340/232377169-abbe56d8-b180-4b11-8039-fd805652eeb3.png">

Unit tests failing inside nx components library with storybook implementation
![Screen Shot 2023-04-17 at 1 52 56 pm](https://user-images.githubusercontent.com/1190340/232377092-c1f720b7-d341-4566-90a8-0733ae1bcfde.png)

Button Component implementation inside the components library:
![Screen Shot 2023-04-17 at 2 21 50 pm](https://user-images.githubusercontent.com/1190340/232377369-fbb252bd-e245-4099-8eb6-a6d7a2e9fa1d.png)

Component working properly inside storybook implementation:
![Screen Shot 2023-04-17 at 2 23 09 pm](https://user-images.githubusercontent.com/1190340/232377474-e6be7dd9-e7a7-4541-81db-4f624c1d0e2f.png)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Space Technologies

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by fahadahmed** [comment]
Hi @tay1orjones, thanks for having a look into the issue. I will try and create the monorepo with a packaged based approach and a standalone approach for a remix app and see if that resolves the issue. The multiple react implementation is more from using the nx generators to create the scaffolding of the monorepo, however the version of react is tied to `18.2.0`.

I will look into implementing npm workspaces as well. We have opened an issue with `nx` as well so hopefully they can assist us with the config - https://github.com/nrwl/nx/issues/16358

**Comment by tay1orjones** [comment]
I don't think there's any action that we could take here to resolve this. I'll close this for now but if there's something actionable from the bug report on `nx` or otherwise we can always reopen.
