### ISSUE TITLE
Add TypeScript types to IconTab

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13559]

**Comment by varunagarwal007** [comment]
Hey @tay1orjones, Can you assign this to me? I can work with implementing it

**Comment by varunagarwal007** [comment]
@tay1orjones just verified that typescript has already been added to this component. You can verify it and assign the appropriate state to the issue

**Comment by nadine-krista** [comment]
Hello @tay1orjones: Can you assign an issue to me? I would like to contribute
