### ISSUE TITLE
Add TypeScript types to Pagination, PaginationSkeleton

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13566]

**Comment by Tresau-IBM** [comment]
I will work on this.

**Comment by Tresau-IBM** [comment]
This issue depends on IconButton being typed, which is being handled in #15057, draft PR (#15399) created as we wait for dependency

**Comment by wkeese** [comment]
Hi @Tresau-IBM, #15057 was merged in January, can you switch #15399 out of draft status?

**Comment by Tresau-IBM** [comment]
> Hi @Tresau-IBM, #15057 was merged in January, can you switch #15399 out of draft status?

Yes @wkeese I will update the draft shortly. Thank you.
