### ISSUE TITLE
Add TypeScript types to PaginationNav

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13567]

**Comment by mattborghi** [comment]
I will take this!

**Comment by mattborghi** [comment]
This issue depends on IconButton being typed, which is being handled in https://github.com/carbon-design-system/carbon/pull/15057, draft PR (https://github.com/carbon-design-system/carbon/pull/15407) created as we wait for dependency.

**Comment by mattborghi** [comment]
Sent for review!
