### ISSUE TITLE
Add TypeScript types to RadioTile

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13572]

**Comment by jesnajoseijk** [comment]
Hi @tay1orjones 
Can I take this up?

**Comment by tay1orjones** [comment]
@jesnajoseijk Yes! I think this should be resolved by a PR that's already up https://github.com/carbon-design-system/carbon/pull/14901

but it's gone stale. If you'd like to issue a new PR with those changes but include the fixes asked for we could close that PR in favor of yours.
