### ISSUE TITLE
Add TypeScript types to TreeView, TreeNode

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13581]

**Comment by imp-dance** [comment]
I'll grab this one!

**Comment by tay1orjones** [comment]
@imp-dance Hey! That existing PR was put together before the TreeView controllable api and after resolving the merge conflicts many of the tests were failing. I just closed it to focus on making a new PR. If you still have those changes, we'd be up for collaborating on a new PR with you.

**Comment by imp-dance** [comment]
@tay1orjones  Cool, I'll sync up my branch and do some more work before I submit a PR. 👍

**Comment by imp-dance** [comment]
@tay1orjones Got distracted with some other work for the last few days but finally got to take a second look at this. Set up a PR @ https://github.com/carbon-design-system/carbon/pull/17038
