### ISSUE TITLE
Add TypeScript types to SideNavMenu

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13606]

**Comment by Nirajsah** [comment]
i can do this

**Comment by Nirajsah** [comment]
umm, i am already done with work.

**Comment by Nirajsah** [comment]
<img width="1439" alt="Screenshot 2023-10-06 at 1 57 47 PM" src="https://github.com/carbon-design-system/carbon/assets/51414373/89264ecc-4d0a-49e1-aa05-a08ba3a2ae5e">

i ran yarn install and was running yarn build when i got this error
i tried installing an npm packgage '@types/carbon__icons-react'
can anyone help me with this

**Comment by Nirajsah** [comment]
TypeScript is throwing errors because the icons-react components lack type definitions, and TypeScript requires types for compatibility. It appears that the entire icons-react component library needs to be converted to TypeScript to resolve this issue.
