### ISSUE TITLE
Add TypeScript types to SideNavLink

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13604]

**Comment by OddDev** [comment]
Will do :)

**Comment by Nirajsah** [comment]
Hey @tay1orjones, several individuals have commented on the issue concerning TypeScript adoption. Although they mentioned they're working on it, it has been weeks now. Therefore, I've taken the initiative to address the issue and create a PR.

**Comment by Nirajsah** [comment]
<img width="1439" alt="Screenshot 2023-11-01 at 8 17 40 PM" src="https://github.com/carbon-design-system/carbon/assets/51414373/4418d096-a791-4911-88c5-72b10d0d9fe3">

facing type error with ref
