### ISSUE TITLE
[Feature Request]: Improve and clarify how FlexGrid styles can be emitted via `$use-flexbox-grid`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13617]
### The problem

The styles for FlexGrid are not emitted by default. To emit them consumers must do one of the following:

- Turn on the `$use-flexbox-grid` feature flag (this consequently turns off CSS Grid)
- Explicitly `@use` the flexbox module `@use @carbon/styles/scss/grid/flexbox`
- `@use '@carbon/react/grid';` and call the `flex-grid()` mixin

Here's how the feature flag is set up currently:

https://github.com/carbon-design-system/carbon/blob/36685a0be5e62db11a60d938c76b1c49a402c99a/packages/styles/scss/grid/_index.scss#L13-L17

None of this is documented in the [storybook docs for FlexGrid](https://react.carbondesignsystem.com/?path=/docs/elements-flexgrid--auto-columns#grid) that I can see.

### The solution

I think we should modify the feature flag to only impact the emitting of flex-grid code and always include CSS Grid code.

```
@if config.$use-flexbox-grid == true {
  @include grid.flex-grid();
}

@include grid.css-grid();
```

```[tasklist]
- [x] Update the feature flag conditional
- [x] Update the documentation
```

--- 

### Why not emit FlexGrid styles by default?

- FlexGrid is a less-complete implementation of the Grid specification
- FlexGrid doesn't support nesting
- FlexGrid requires the use of extra markup via `Row`
- While FlexGrid has it's uses, the CSS Grid implementation is the intended entrypoint for new projects. 

For these reasons, I believe the FlexGrid styles should continue to require an explicit opt-in.

**Comment by komplexb** [comment]
The [code](https://github.com/carbon-design-system/carbon/pull/13618/files#diff-2b6a0eb3d147c2aade9750b8f404c5455736e15c5e70318270f1f755a5c68ee4L13) seems to indicate both grid styles can be used concurrently without conflicts.

Is that supported? Should I expect any conflicts?
![image](https://github.com/carbon-design-system/carbon/assets/3874813/9e2416a7-4288-40f8-b726-fcb0de5f3843)
