### ISSUE TITLE
[Feature Request]: Add `external` prop to `<Link />` component

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/carbon#13633]
### The problem

This features adds a boolean prop to Links called `external`. This would streamline the `target="_blank"`and `rel="noopener noreferrer"`

### The solution

Add the following to the carbon `Link` component.

```
<a 
     target={external ? '_blank' : undefined)}
     rel={external ? 'noopener noreferrer' : undefined} 
  >
    I'm a link
</a>
```

  

### Examples

```
<Link href="www.carbondesignsystem.com" external>Go to carbon</Link>
```

### Application/PAL

Instana

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Hi @AlexanderMelox chatted with @tay1orjones and some of the other Carbon devs offline about this issue. We've decided to close this issue/PR as you are already able to achieve this functionality without adding additional complexity to the component; it forwards all the props to the <a> tag already.

**Comment by AlexanderMelox** [comment]
@alisonjoseph Totally agree with you guys! Thanks
