### ISSUE TITLE
[Bug]: TreeView labels not properly aligned

### ISSUE THREAD

**Issue by AlanGreene** [carbon-design-system/carbon#13640]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.27.0 (latest)

### Description

[As discussed on Slack](https://my.slack.com/archives/C0M053VPT/p1682082992294569)

Labels for expandable items in the TreeView are indented further than other items.

### Screenshots

Notice the labels for 'Business automation' and 'Cloud computing'
![image](https://user-images.githubusercontent.com/2829095/233682627-8fc84d84-0c3d-4797-91e5-cea0add2731c.png)

I expect the labels to be aligned like this instead:
![image](https://user-images.githubusercontent.com/2829095/233682698-9d07d496-4e7a-4b84-8f44-61616922a01b.png)

### Steps to reproduce

See the TreeView stories: https://react.carbondesignsystem.com/?path=/story/components-treeview--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by emyarod** [comment]
possible regression from #13354 (#13114,  #12769)

**Comment by aagonzales** [comment]
This is a known issue, we re-opened the original issue. There were some cascading spacng effects that were not accounted for. See the spec [here](https://github.com/carbon-design-system/carbon/issues/13114#issuecomment-1512059569) for intended changes.
