### ISSUE TITLE
Button: text wrap specs

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon#13644]
Design exploration and specs needed for #13406 refactor(Button): align icon top for wrap alignment

Dev will most likely implement: 

> Idea 3 (static): find a static distance for top since icons have absolute positioning
> I tried matching top spacing of icon with button padding, but that did not align properly.
> using pixel values for now because padding had calculations (below)
> SIZE = padding-top = CLASS
> sm = calc(0.375rem - 3px) = .cds—btn—sm
> md = calc(0.675rem - 3px) = .cds—btn—md
> lg = calc(0.875rem - 3px) = .cds—btn
> xl = 1rem = .cds--btn--xl:not(.cds--btn--icon-only)
> 2xl = 1rem = .cds--btn--2xl:not(.cds--btn--icon-only)

icon and text alignment get slightly off though and we will need to visually adjust especially for the small button. 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/20582179/233716723-76bc4cde-bfff-47de-b953-24e7e5a5389b.png">

**Open UX/Visual questions:**

- Do we need documentation about text wrapping?
- What happens when buttons are close to each other and one wraps and the other doesn't? Can we even control something like this?
- XL button padding is a little strange with more padding on top than bottom. usually, when there is different padding, there is more on the bottom than top.

**Comment by laurenmrice** [comment]
Related #13406
