### ISSUE TITLE
[Feature Request]: From Scratch Refactor of DataTable

### ISSUE THREAD

**Issue by naderalmogazy** [carbon-design-system/carbon#13657]
### The problem

The DataTable Component is in a great working state, but highly confusing and lacking a level of intuitive use.
I find it frustrating to import so many separate components to get the functionality I expect from one component.

### The solution

I am proposing a new version that is a bit more opinionated, but much faster to set up and customize.

This component takes in an array of objects as its 'Data' and maps the data automatically, one object, one row. 

In addition to the 'data' it takes a mapping of key's expected in those objects, to column labels, along with other useful things like what share of the width that column should take up.

Other functionality is built on top of that like row onClick handler, which expects to take a handler function, and passes the row clicked to that function on invocation.

### Examples

Basic example:
<img width="1030" alt="Screen Shot 2023-04-24 at 5 01 06 PM" src="https://user-images.githubusercontent.com/131716986/234117389-135ce40f-f2a1-4daf-9d33-7b3933c2af6f.png">
Search Functionality:
<img width="1025" alt="Screen Shot 2023-04-24 at 5 01 27 PM" src="https://user-images.githubusercontent.com/131716986/234117404-312e95e2-cfeb-4996-9038-0ccc3f217e59.png">
Inline functions:
<img width="1039" alt="Screen Shot 2023-04-24 at 5 02 12 PM" src="https://user-images.githubusercontent.com/131716986/234117414-2d8423b4-100b-4d28-ad4d-9203722686df.png">
Dropdown options:
<img width="759" alt="Screen Shot 2023-04-24 at 5 02 54 PM" src="https://user-images.githubusercontent.com/131716986/234117422-3ae6dfb0-ebc5-4c12-a6e4-32891a5709d5.png">
Dropdown expanded:
<img width="752" alt="Screen Shot 2023-04-24 at 5 03 14 PM" src="https://user-images.githubusercontent.com/131716986/234117433-9c5b7776-d66c-4a4f-8b0f-0870f0dde3b1.png">

### Application/PAL

App & Data Modernization

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Available extra resources

Personal Repos where I use this component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by naderalmogazy** [comment]
My take on this refactor definitely sounds a lot like the `carbon-addons-iot-react`  [StatefulTable](https://carbon-addons-iot-react.com/?path=/docs/1-watson-iot-table--playground#getting-started). 
It takes in a list of props. All the data and functions(fired by user events), are provided as input to the component. I hear that the current DataTable doesn't deal with state well, and that just sounds like all the more reason to go back to the drawing board.

It has most if not all the functionality I've seen from the current data table. And of course you could replenish any missing functionality over time.

I do see the benefits being significantly decreased learning curve, and significantly better state management. Not to say that the con's aren't there, I'm sure this being such a heavily collaborated work, my work is far less documented, and the accessibility level is probably lagging behind as well.

**Comment by sstrubberg** [comment]
Thanks for bringing this to our attention @naderalmogazy and I hope you got some good resources to work from. Closing this issue for now as Taylor pretty much covered our POV on DataTable. Have a good one!
