### ISSUE TITLE
[Feature Request]: Icon Input for ibm-structured-list selectable row

### ISSUE THREAD

**Issue by Brenofil** [carbon-design-system/carbon#13654]
### The problem

Currently i am trying to emulate a filter like the one from the image below:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/6520050/234027297-3e21bf4c-a106-4607-a3cc-18e3344cf7a9.png">

For a better result i started using the ibm-structured-list component along with the [selection]="true" property, so i could have the hover effect and selection event. Although the selection is working fine, i would like to ask for a way to change the icon displayed when a row is selected, it seems there is no other option besides de check icon
<img width="230" alt="image" src="https://user-images.githubusercontent.com/6520050/234027954-b3cb7b8b-9105-4e0f-9a4b-eeb857206af6.png">

### The solution

Implementing an Input property just like the [selection] for ibmIcon so anyone could change the select icon when needed.

### Examples

Here i used de ::ng-deep to force a display: none property so i could show what it would look like if i could change to the chevron right icon when selected.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/6520050/234028520-8db63442-ccf5-42e8-9283-3435b438f4de.png">

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@Brenofil You can provide whatever icon you'd like, just give it the proper class as shown in the storybook example

https://github.com/carbon-design-system/carbon/blob/36685a0be5e62db11a60d938c76b1c49a402c99a/packages/react/src/components/StructuredList/StructuredList.stories.js#L162-L168

Although for your use case you might consider using the [`ContainedList` with actions](https://react.carbondesignsystem.com/?path=/story/components-containedlist--with-actions) instead. It might have more of what you're looking for.

Hope this helps!

**Comment by Brenofil** [comment]
It helped! Thank you! In the carbon-components-angular [documentation](https://angular.carbondesignsystem.com/documentation/globals.html) i couldn't find a reference for a Contained List with actions and the link you suggested refers to the react documentation. The application i am currently working on is based on angular, is there such a list for the framework?
