### ISSUE TITLE
[Bug]: overflowmenuv2 is not working correctly when inside a modal

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/carbon#13669]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.27.0

### React version

18.2.0

### Description

When unstable_OverflowMenuV2 is added inside a modal you cannot dismiss the overflowmenu by clicking off of it

Note: in this example I am using a modal but in my app this is happening from a tearsheet component which uses the carbon modal classes

### Reproduction/example

https://codesandbox.io/s/fancy-rgb-8bwkwl?file=/index.js:90-113

### Steps to reproduce

Open the code sandbox
Click launch modal
Click the Modal heading text
The menu does not close

If you close the modal and click the overflow menu that is outside of the modal then clicking off the menu causes it to close

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by andreancardona** [comment]
@tkolanko thank you for opening this issue!

**Comment by 2nikhiltom** [comment]
This bug is closed as part of https://github.com/carbon-design-system/carbon/pull/15889
