### ISSUE TITLE
Carbon Grid RTL Support for Offset

### ISSUE THREAD

**Issue by sgurin** [carbon-design-system/carbon#13719]
### Question for Carbon

Hi.

We use Carbon Grids https://github.com/carbon-design-system/carbon/tree/main/packages/grid and faced with problem in offset property. It seem to not support RTL because not use logical property. Right?

![image](https://user-images.githubusercontent.com/25930200/235881592-45000d28-6db7-4378-903b-4cab8cb5cce7.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@sgurin Our current recommendation for RTL styling is to use [RTLCSS](https://rtlcss.com/) in your build pipeline to generate the necessary styling for BiDi/RTL environments.

We do plan to migrate the codebase to use logical properties #13619 but there's no concrete plans or timeline atm. PRs are welcome if you'd like to jumpstart it and update the grid styling.

**Comment by tay1orjones** [comment]
Duplicate of #13619
