### ISSUE TITLE
[Bug]: DatePicker onChange callback not being called

### ISSUE THREAD

**Issue by FranzFernandes** [carbon-design-system/carbon#13726]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.28.0

### React version

16.8.6

### Description

In the Carbon DatePicker (https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar) the `onChange` callback on the `DatePicker` component never gets called whenever a user selects a date. This happens on all three types of datePickers, i.e. "range", "single" and "simple". 

Example of bugged behavior:

https://user-images.githubusercontent.com/20014987/236139350-d9e95a26-4a08-4190-a741-fc5b3c48ed56.mov

The expected behavior can be found in @carbon/react version 1.27.0. Here the `onChange` callback does get called and the selected dates can be used to showcase which date has been selected. 

Example expected behavior **on version 1.27.0**:

https://user-images.githubusercontent.com/20014987/236139939-eda30dfa-5ef2-4962-b070-c40388ddaf55.mov

### Reproduction/example

https://stackblitz.com/edit/github-jj5nb2?file=src/App.jsx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/github-jj5nb2?file=src/App.jsx
2. Open the datepicker by clicking on the input
3. Select a date
4. Notice that the `selectedDates` hasn't been updated and the console.log in the `onChange` didn't get called

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@FranzFernandes If you place `onChange` on the DatePickerInput does it work as you would expect?

**Comment by FranzFernandes** [comment]
Hi @tay1orjones thanks for taking the time to take a look at this. 
Unfortunately, placing an `onChange` on the DatePickerInput instead of the DatePicker, doesn't work as expected. The `onChange` on the DatePickerInput only gets called on keyboard type events. 
Furthermore the `onChange` on the DatePickerInput only exposes the keyboard event as the first parameter, instead of the `selectedDates` the `dateString` and the datePicker instance that the `DatePicker` onChange used to.

Due to not having the `onChange` available, it makes using the DatePicker component as a controlled component much harder.

**Comment by FranzFernandes** [comment]
On further inspection, I noticed that the `onClose` callback on the `DatePicker` component does expose the `selectedDates`, `dateString` and Datepicker instance. While I don't think this is the preferred behavior, it is now possible to make the `DatePicker` component controlled with a workaround. 

Now that there is a workaround I will update the issue to have severity 3 instead

**Comment by hsu022210** [comment]
@tay1orjones 

We on IBM team are also experiencing the bug, I see a PR has been linked to resolved this, any time soon you guys can have it merged so we can upgrade to be unblocked by this? Thanks.

**Comment by tay1orjones** [comment]
@hsu022210 @FranzFernandes [`v11.29.1`](https://github.com/carbon-design-system/carbon/releases/tag/v11.29.1) was just published containing this fix.
