### ISSUE TITLE
Design Audit: C4IBMP and Sustainability Components

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#13736]
### The problem

This Away Misson will conduct an extensive audit of existing components in the Carbon for IBM Products and Carbon for Sustainability PALs. These would most likely include Carrie Lloyd from C4IBMP and Chris Hammond from Sustainability for support. From this audit, it will determine the list of components that should be deemed “stable” and should be considered for extensive long-term maintenance/enhancement support and more robust documentation.

Tentatively, a new hub and spoke approach for the PAL ecosystem can introduce a new “stable” layer of Carbon for Products, and the existing repository for the Carbon for Products can remain a more rapid “experimental” delivery layer that will contribute to the “stable” layer.

### The solution

Design delvierables: 
- [x] Determine list of components that should be deemed “stable” from the IBM Carbon for Products and IBM Carbon for Sustainability PAL
- [x] Identify any duplication of components/patterns in the PALs
- [x] Identify components from Carbon for Sustainability PAL that are core, bespoke to Sustainability, or universal to all products
- [x] Identify components/patterns in Carbon for Products that are bespoke to Cloud/Security
- [ ] Re-assess contribution model and evaluate a “stable” + “experimentation” layer approach.
- [ ]  _Re-assess hub and spoke model of Carbon for IBM Products and other PALs and codify/document (need clarity on this one)_

### Examples

REF

This artifact from @oliviaflory 's audit of the Gatsby/.com component delta is the perfect format to use for this exploration.

https://www.figma.com/file/XXIhC6kFHqvQf5jYiQ7GZx/Component-delta?node-id=0%3A1&t=bwI1R9Q7WfD6kTzz-1

### Application/PAL

Carbon Core

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

This workstream will rely on Carrie Lloyd, Chris Hammond and potentially Keven Weaver (Diana Tran's replacement)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
@jeffchew @jeanservaas Next time we hang out and talk about this work-stream, I'd like to better understand the relationship between the experimental and stable layer approach.

**Comment by aagonzales** [comment]
[Box-folder](https://ibm.box.com/s/73676nshez0pvu0141fip9aqmk67mbgj) with final assets
