### ISSUE TITLE
Update downshift

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13749]
We're two major versions behind on our downshift dependency. We attempted to update to v6 [a few times before](https://github.com/carbon-design-system/carbon/pulls?q=is%3Apr+update+downshift+is%3Aclosed) and hit major roadblocks - https://github.com/carbon-design-system/carbon/pull/9839, most recently https://github.com/carbon-design-system/carbon/pull/11331.  

Primary drivers for this update include:
- Ensure we avoid any future CVEs related to outdated transient dependencies of v5.x 
- There are features and fixes included in the update that will resolve some issues we have

```[tasklist]
### Related issues blocked by downshift being outdated
- [ ] https://github.com/carbon-design-system/carbon/issues/10634
- [ ] https://github.com/carbon-design-system/carbon/issues/14102
```

Something else related to this is an idea [mentioned here](https://github.com/carbon-design-system/carbon/pull/8211#issuecomment-809459238), to expose our ListBox internals https://github.com/carbon-design-system/carbon/issues/6177 so consumers can directly use them with downshift. This could be part of the path to upgrading downshift and/or deprecating existing parts of our API. I'm not 100% sure, but it's something to consider and explore.

**Comment by francinelucca** [comment]
This will be a research issue first to gauge the possibility/size of this effort and we can re-discuss and move from there
