### ISSUE TITLE
[Bug]: Combobox documentation issue

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#13767]
### Package

@carbon/react

### Package version

1.23.0

### Description

The doc for Combobox talks about an onStateChange prop that is passed to Downshift.  However, it doesn't work.  When I looked at the code, I could see that downshiftProps.onStateChange is what is being passed to Downshift, not the onStateChange prop itself.

This documentation should be fixed.   The doc for the onStateChange should be moved under the downshiftProps definition.

### Reproduction/example

NA

### Steps to reproduce

NA

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@kglickman thanks for reporting this - I agree this needs to be updated. If you're up for submitting a PR we would appreciate it.
