### ISSUE TITLE
[Question]: Are read-only components accessible / can they be read be screen-readers?

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [carbon-design-system/carbon#13761]
### Question for Carbon

For any and all _read-only_ states of Carbon components, like the Text Input, are the values read by screen-readers? I have the same question for _disabled_ states as well.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Yes, `read-only` components are ready by screen readers, and are announced as `clickable`. Normal, editable text inputs would read as `Edit text`.

Disabled inputs are not read by screen readers, as they are not included in the tab order of the DOM. Hope that helps.

**Comment by kunderwoodatadaptive** [comment]
Very helpful, thank you!
