### ISSUE TITLE
[Bug]: TypeScript: TableToolbarMenuProps.iconDescription is required

### ISSUE THREAD

**Issue by lewandom** [carbon-design-system/carbon#13778]
### Package

@carbon/react

### Package version

1.28.0

### Description

When using TableToolbarMenu component in a TypeScript project, the iconDescription prop must be provided:

```
Type error: Property 'iconDescription' is missing in type '{ children: Element[]; }' but required in type 'TableToolbarMenuProps'.
```

While it is really a required prop in PropTypes, it does have a default value in defaultProps. Therefore, to keep same usage of this component between JS and TS, it'd be better to make it optional in `TableToolbarMenuProps` and set a default value when destructuring functional component props.

Raising this as a bug despite this probably would be covered by https://github.com/carbon-design-system/carbon/issues/13424, because it actually errors out in real life usage.

### Reproduction/example

See below

### Steps to reproduce

Simply create use the component in a TypeScript project without any props:

```
<TableToolbarMenu>
   ...
</TableToolbarMenu>
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by lewandom** [comment]
A similar problem exists for TableHeader.scope property.

**Comment by tay1orjones** [comment]
@lewandom thanks for catching this, I agree. Anywhere a prop is marked required but has a default like this should not be required and the default provided through default function params.
