### ISSUE TITLE
[Bug]: ExpandableSearch doesn't honor defaultValue

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#13782]
### Package

@carbon/react

### Package version

1.23.0

### React version

16.4

### Description

I'm specifying the defaultValue attribute for ExpandableSearch but when I click on the magnifying glass to open it, the defaultValue is not set.

This is a serious problem because the component doesn't really work as a controlled component with value.  It is too slow to handle fast typing, even with a debounce.

### Reproduction/example

https://stackblitz.com/edit/github-a6ym8m?file=src%2FApp.jsx

### Steps to reproduce

Click on the magnifying glass in the Stackblitz.  The search expands but does not show the defaultValue.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@kglickman thanks for reporting, I'm not sure why this is happening. `ExpandableSearch` passes all props down to `Search`, and the default is working there. It could potentially be an errant onChange being called setting the input value to empty? I'm not really sure.

https://github.com/carbon-design-system/carbon/blob/3058efececd18e539795f0ec2ff1f2864e42df7d/packages/react/src/components/ExpandableSearch/ExpandableSearch.tsx#L43

**Comment by kglickman** [comment]
Also, it doesn't matter much with defaultValue not working, but there should also be an "expanded" prop so we can control the initial expansion.  The use case for both is when the user does a search, leaves the page, and then comes back.  We want to be able to restore their state.
