### ISSUE TITLE
[Bug]: <HeaderMenu> does not close when clicking <HeaderMenuItem>, using next.js <Link>s

### ISSUE THREAD

**Issue by akqa-julietbenjamin** [carbon-design-system/carbon#13795]
### Package

@carbon/react

### Browser

Chrome

### Package version

v^1.20.0

### React version

18.2.0

### Description

Hello! I'm experiencing issues with navbar dropdowns not closing when expected. I'm using [next.js Link](https://nextjs.org/docs/pages/api-reference/components/link)s for routing, and the entire navbar is wrapped in a framer-motion div for page fade-in animations. (Also, the styles are overridden so that it's a footer and not a header).

To be fair, I'm not using `<HeaderName>` like outlined in the [Storybook](https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation), but attached is code below and a screenshot of the behavior. The expected behavior is when clicking on "The Technology Roadmap" header name or the circle logo icon to the left of the header name, any open navs will close. Please advise, thank you!

Similar bugs: https://github.com/carbon-design-system/carbon/issues/5351 & https://github.com/carbon-design-system/carbon/issues/4930

Screen recording of issue:

https://github.com/carbon-design-system/carbon/assets/3360588/4264f79c-4d4b-4a6c-a554-01e854e5e344

Code:
```js
<motion.div
  initial="hidden"
  animate="visible"
  exit="clear"
  variants={navbarAnimation}
  className={styles.text}
>
  <Header
    className={styles.headerWrapper}
    aria-label="IBM Technology Atlas"
  >
    <HeaderNavigation aria-label={sanitizeContentAsString(content?.Navbar_Homepage)}>
      <Link className={styles.logoWrapper} href='/'>
        <div className={styles.logoCircle} />
      </Link>
      <Link href='/' passHref legacyBehavior>
        <HeaderMenuItem
          className={styles.navMenuItem}
          isCurrentPage={router.pathname === "/"}
        >
          {sanitizeContent(content?.Navbar_Homepage)}
        </HeaderMenuItem>
      </Link>
      <HeaderMenu
        className={styles.navMenuDropdownWide}
        aria-label="Explore the roadmaps"
        menuLinkName="Explore the roadmaps"
        isCurrentPage={router.pathname === "/[...slug]"}
      >
        <Link href={`/${AI.slug}`} passHref legacyBehavior>
          <HeaderMenuItem
            className={cx(
              router.asPath.includes(`/${AI.slug}`) &&
                styles.navMenuDropdownListItemSelected
            )}
          >
            {sanitizeContent(content[AI.slug])}
          </HeaderMenuItem>
        </Link>
        {/* other <HeaderMenuItem> elements */}
      </HeaderMenu>
      {/* other <HeaderMenu> elements */}
      </HeaderNavigation>
    )}
  </Header>
</motion.div>
```

### Reproduction/example

see attached video & code

### Steps to reproduce

See attached video & code

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for providing the screencapture and code snippet @akqa-julietbenjamin. Could you repro it in a [codesandbox](https://codesandbox.io/p/sandbox/vigilant-platform-x25btt) by chance? It's difficult to deduce what could be the issue or how you might work around it without being able to debug through the component source. If you debug into the component source, do you see a reason why this might be happening?

**Comment by akqa-julietbenjamin** [comment]
@tay1orjones  thank you for the reply!! figured out a fix just a bit ago -- instead of wrapping next.js `Link` with `passHref` (which essentially creates `<a>` around the whole component) around `HeaderMenuItem`, swap them:

```js
<HeaderMenuItem
  className={styles.navMenuItem}
  isCurrentPage={router.pathname === "/"}
>
  <Link href='/' passHref legacyBehavior>
    {sanitizeContent(content?.Navbar_Homepage)}
  </Link>
</HeaderMenuItem>
```
