### ISSUE TITLE
Grid docs: Implementation page imagery (more recent, actual product)

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13813]
The grid docs implementation tab needs to be rewritten and renamed the the Grid "Usage" tab.

- [x] First past at a draft of the page up to Mixing gutter modes
- [x] Add Using grid influencers section (about the shell in product)
- [x] Add Layout gallery section that links to [Security UI Screens](https://pages.github.ibm.com/security/security-design/teams-gallery/product-screens/) (at the end of the page) 

@alisonjoseph will take a stab at a rough draft for the Mixing gutter modes section here [#3529](https://github.com/carbon-design-system/carbon-website/issues/3529)

Update relevant images:

- [x] Basic scaffolding image
- [x] Four columns image (need to rebuild)
- [x] Denser layout image (need to rebuild)
- [x] Thinking across an experience image
- [x] Layout modules image
- [x] Using grid influencers animation (repurpose)
- [x] Using grid influencer side panel image
- [x] Contrast Do/Don't
- [x] Aspect ratio image
- [x] Adaptive aspect ratio image
- [x] Wide gutter mode update
- [x] Narrow gutter mode update
- [x] Condensed gutter mode update
- [x] Clean up file for review

**Comment by jeanservaas** [comment]
Figma file for review

https://www.figma.com/file/ROcIS7OFtP42sXqH7VODhV/Grid_docs?type=design&node-id=0%3A1&t=cDX5h8qxK3Z7aHKp-1
