### ISSUE TITLE
[Bug]: RadioButton checked not changing when selection is changed

### ISSUE THREAD

**Issue by youda97** [carbon-design-system/carbon#13822]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.19.0

### React version

17.0.2

### Description

The `checked` html attribute is not changing when you change the radio selection. The checked is staying on the first radio button. See screenshot:

<img width="1271" alt="Screenshot 2023-05-17 at 4 33 04 PM" src="https://github.com/carbon-design-system/carbon/assets/25139161/6274be9b-99b2-4ad0-87e2-1983e1ba621c">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-radiobutton--default

### Steps to reproduce

1. Change radio button selection
2. Open dev tools and check the html
3. Notice the checked has not changed

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Turbonomic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by youda97** [comment]
Any updates on this bug?

**Comment by tay1orjones** [comment]
In this case, `checked` is only intended to denote the default state. It's not intended to be updated per the HTML spec. 

More on this from [MDN here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#additional_attributes)

> checked
> A Boolean attribute which, if present, indicates that this radio button is the default selected one in the group.
