### ISSUE TITLE
[Feature Request]: Allow selection on just the dropdown button instead of the wrapper while setting the tabIndex props

### ISSUE THREAD

**Issue by meygaalex08** [carbon-design-system/carbon#13832]
### The problem

While filling out forms , we require the tab index to be set on the form fields in a certain way, such that it makes it easier for the end user/customer while filling it. This becomes a blocker while setting the tabindex field on the Dropdown field, IT selects the entire thing including the labelText while tabbing,
<img width="1033" alt="Screenshot 2023-05-19 at 12 21 02 PM" src="https://github.com/carbon-design-system/carbon/assets/133948123/c066aea4-d424-4f31-ae53-78f3d776437a">
 FYI: This is how it's selecting currently.

Instead we want the selection just on the drop-down button, like how it behaves for the other form fields like TextInput etc.

### The solution

We require the selection to be on the dropdown button, instead of the whole wrapper div. Like this: 
<img width="477" alt="Screenshot 2023-05-19 at 12 24 34 PM" src="https://github.com/carbon-design-system/carbon/assets/133948123/d2607a2d-0840-4143-919d-ee3feb097ec2">

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@meygaalex08 Hi, could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), and post the link back here? It's hard to know exactly what's going wrong without seeing the issue firsthand.

**Comment by meygaalex08** [comment]
@tay1orjones here is the sandbox reproducing the issue - https://stackblitz.com/edit/github-wgvs1p?file=src/App.jsx  .

**Comment by tw15egan** [comment]
@meygaalex08 it seems like the `tabIndex` is being spread onto the `Dropdown` wrapper, but I guess the bigger question is this: why are you creating a custom tab order inside your form? Creating an unexpected pattern for keyboard users that sends them to an input they are not expecting could cause frustration, and may be a tab order violation. On top of this, this forced user flow would be ignored by a user navigating this form with their mouse. Perhaps I am missing something, but if you simply remove the `tabIndex` from your example the focus works as expected.  https://stackblitz.com/edit/github-wgvs1p-3g9afk?file=src%2FApp.jsx
