### ISSUE TITLE
[Bug]: Data Table component - Sorting is not happening as expected 

### ISSUE THREAD

**Issue by TubaMizaj** [carbon-design-system/carbon#13845]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

7.25.0

### React version

17.0.2

### Description

I am using DataTable from carbon-components-react package in my React application to display the rows returned by a search API call. When the result set returned by the search API is displayed on the UI in the DataTable and user tries to perform a sort on an column that has a mix of numeric and alpha-numeric values, the sorting is not happening correctly.

### Reproduction/example

https://codesandbox.io/s/xenodochial-nova-vece3p?file=/src/App.js

### Steps to reproduce

Open the sandbox link provided (https://vece3p.csb.app/) and click on **IBMC_ISU** column header to perform sorting.
Check the values in IBMC_ISU column and it still shows random arrangement of values instead of sorted arrangement.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by TubaMizaj** [comment]
Hi,
This bug has been marked as Done, but I would like to report that the issue is still reproducible.
If I go to my sample application in Code Sandbox accessible at the following url: https://vece3p.csb.app/, I am still not able to sort the IBMC_ISU column correctly in ascending or descending order.

![image](https://github.com/carbon-design-system/carbon/assets/133873397/55d26b00-a4e0-4ae8-b13c-a630de4c4a67).

Please let me know the steps that I would need to take to this bug in my application.

**Comment by ljcarot** [comment]
I removed your screenshot @TubaMizaj .  Reminder we are open repo.

**Comment by tay1orjones** [comment]
@TubaMizaj Your example isn't using the latest release. The fix in https://github.com/carbon-design-system/carbon/pull/13855 was published as part of [v11.30.0](https://github.com/carbon-design-system/carbon/releases/tag/v11.30.0). This would be `carbon-components-react@v8.30.0` for your storybook example.
