### ISSUE TITLE
[Question]: Search pattern: Are Figma components included for Search Results and for 'Scope Filter'

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [carbon-design-system/carbon#13854]
### Question for Carbon

I was getting familiar with the 'Search Pattern' on the Carbon website:
https://carbondesignsystem.com/patterns/search-pattern/#best-practices

In here, I noticed that there is a mega component described for 'Scope Filter':
<img width="750" alt="Screen Shot 2023-05-22 at 11 53 57 AM" src="https://github.com/carbon-design-system/carbon/assets/120414992/88154eb4-6bcd-41f1-a3d6-dee047587f40">

This is a feature that would be useful to the product I'm designing. However, I don't see it included in any of the variants for the Search component in Figma:
<img width="842" alt="Screen Shot 2023-05-22 at 11 55 45 AM" src="https://github.com/carbon-design-system/carbon/assets/120414992/2b8c4148-f750-4f7b-88de-8627a2acba5f">

How would you recommend building this in Figma, or is this component coming soon?

I have the same question for the Search results functionality:
<img width="751" alt="Screen Shot 2023-05-22 at 11 57 17 AM" src="https://github.com/carbon-design-system/carbon/assets/120414992/8951a416-ab72-4fee-8526-cc13dac90e56">
(How would you recommend building this in Figma, or is this component coming soon?)

Thank you for your guidance!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@carbon-design-system/design is there guidance for this situation?
