### ISSUE TITLE
[Bug]: Data table can select all when using radio buttons, misconfigured story

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon#13857]
### Package

@carbon/react

### Browser

Chrome

### Package version

canary

### Description

![Screenshot 2023-05-22 at 4 23 56 PM](https://github.com/carbon-design-system/carbon/assets/24970122/92177cc4-8af1-46bc-9334-07f607c824fc)

The radio buttons are able to all be selected when clicking on the header checkbox

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datatable-batch-actions--playground&args=isSortable:false;stickyHeader:false;useStaticWidth:true;locale:;radio:true

### Steps to reproduce

1. Visit the link above
2. Enable `radio` boolean
3. Select the checkbox on the header row
4. All rows are being selected

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@IgnacioBecerra Thanks for catching this! It looks like this is just isolated to storybook - that playground story doesn't seem to properly respond to the `radio` control. When it's `true`, the header shouldn't render the select-all checkbox.

[This story](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--with-radio-selection) is properly configured and shows how it should be configured.
