### ISSUE TITLE
Unprefixed OverflowMenu styles are overriding default OverflowMenu styles

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#1386]
Seems to be coming from https://github.com/IBM/carbon-components/blob/master/src/components/ui-shell/_product-switcher.scss#L136

<img width="477" alt="screen shot 2018-11-02 at 1 54 48 pm" src="https://user-images.githubusercontent.com/11928039/47935016-0b94b580-dea7-11e8-8b8b-4f5113171c33.png">

This needs to be prefixed with a scoped selector so that the default OverflowMenu is not affected

**Comment by asudoh** [comment]
Fixed by: #1395
