### ISSUE TITLE
Remove the sketch plugin from the codebase

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13863]
Now that we've [gone all in on Figma](https://github.com/carbon-design-system/carbon/discussions/13862), we will no longer be maintaining the sketch plugin and it can be removed from our codebase.

```[tasklist]
- [ ] Remove `packages/sketch` from the codebase
- [ ] Remove references to `@carbon/sketch` throughout the codebase (workflow files, eslintconfig, prettierconfig, build, `.md` documentation, etc). Do a find all for "sketch" and you'll find them all.
```

**Comment by falsepopsky** [comment]
I'm already working on this, but I'm not sure about these files:

https://github.com/carbon-design-system/carbon/blob/4cac8294088d1047a9eeda81ae75a1b668a187b2/.github/CONTRIBUTING.md?plain=1#L266-L267

Are there any proposed changes here?

---

https://github.com/carbon-design-system/carbon/blob/4cac8294088d1047a9eeda81ae75a1b668a187b2/packages/styles/carbon.yml#L8-L18

What about these keys with the sufix `sketch` ?

**Comment by tay1orjones** [comment]
The Sketch kit still exists, it's just the sketch plugin we're removing

**Comment by tay1orjones** [comment]
Completed
