### ISSUE TITLE
[Bug]: [Modal] Text seems to have unnecessary whitespace

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/carbon#13861]
### Package

carbon-components-react

### Browser

Chrome, Safari, Firefox

### Package version

v7.59.6

### React version

v17.0.2

### Description

![Screenshot 2023-05-23 at 10 50 00 AM](https://github.com/carbon-design-system/carbon/assets/60585804/d94f3475-c49e-4097-8e67-370e08356fed)

screenshot above is from https://react.carbondesignsystem.com/?path=/story/components-modal--default 

(occurs on all browsers)

the text cuts off at a awkward length unlike other components in the model, providing a whitespace on the right. could this be extended to the full length of the modal just like all other components in the screenshot such as text input?

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-modal--default

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/story/components-modal--default

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @youngjunekoh ! This is actually working as the design intended. For more information, you dig into the docs on our [website](https://carbondesignsystem.com/components/modal/usage/#alignment)
