### ISSUE TITLE
[Feature Request]: advocate data table component support sticky columns

### ISSUE THREAD

**Issue by dybxin** [carbon-design-system/carbon#13874]
### The problem

advocate data table component support sticky columns, as a solution for displaying large amounts of data with long columns.

### The solution

[datatable.webm](https://github.com/carbon-design-system/carbon/assets/14888437/644c6223-da75-4fc2-ada0-1ef874e6d939)

### Examples

https://ant.design/components/table#components-table-demo-fixed-columns-header

### Application/PAL

sveltekit

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@dybxin Thanks for suggesting this! Unfortunately this request falls outside the scope of what we intend to support within DataTable.

It's been discussed a couple times before https://github.com/carbon-design-system/carbon/issues/1814, https://github.com/carbon-design-system/carbon/issues/4748

This feature is available in the `@carbon/ibm-products` library though. It's a companion library supported by a subset of teams within IBM and has an advanced "DataGrid" built atop the DataTable with this functionality (plus a lot more) [demo here](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--frozen-columns). The DataGrid workstream specifically is supported by an internal working group. Issues and future plans can be found on the [`ibm-products` repository](https://github.com/carbon-design-system/ibm-products)
