### ISSUE TITLE
[a11y]: port a11y fixes to v10

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#13870]
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

v7.59.7

### Automated testing tool and ruleset

IBM Equal Accessibility Checker, Latest Deployment

### Description

FileUploader & CodeSnippet have a11y issues in v10 that are not present in v11, we need to backport those fixes.

https://codesandbox.io/s/mutable-frost-m7nzh2?file=/src/index.js FileUploaderDropContainer component  https://codesandbox.io/s/dazzling-jackson-6r2vjj?file=/src/index.js -> CodeSnippet component
https://codesandbox.io/s/charming-mendeleev-fx4jy4?file=/src/index.js -> FileUploaderItem component

The potential PRs that fixed those issues are:
https://github.com/carbon-design-system/carbon/issues/12498
https://github.com/carbon-design-system/carbon/pull/13310
https://github.com/carbon-design-system/carbon/pull/12105/files

### Reproduction/example

Provided above

### Steps to reproduce

Run a11y checker against provided examples

<img width="612" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/7b9fb37b-063f-4f2e-be9f-69f3f2a2a71f">
<img width="615" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/f0964e60-3609-40da-8fec-58de55b0313a">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sunnyanand17** [comment]
I see the below issue for FileUploaderItem:
https://v7-react.carbondesignsystem.com/iframe.html?id=components-fileuploader--file-uploader-item&args=&knob-Filename%20height%20(size)=default&knob-Label%20text%20(labelText)=Drag%20and%20drop%20files%20here%20or%20click%20to%20upload&knob-Form%20item%20name%20(name)=&knob-Supports%20multiple%20files%20(multiple)=true&knob-Accepted%20MIME%20types%20or%20file%20extensions%20(accept)[0]=image/jpeg&knob-Accepted%20MIME%20types%20or%20file%20extensions%20(accept)[1]=image/png&knob-ARIA%20role%20of%20the%20button%20(role)=&knob-Tab%20index%20(tabIndex)=0&knob-Filename%20(name)=README.md&knob-Status%20for%20file%20name%20(status)=complete&knob-Close%20button%20icon%20description%20(iconDescription)=Clear%20file&knob-Error%20subject%20(errorSubject)=File%20size%20exceeds%20limit&knob-Error%20body%20(errorBody)=500kb%20max%20file%20size.%20Select%20a%20new%20file%20and%20try%20again.&knob-FileUploaderItem%20height%20(size)=default&viewMode=story

<img width="1710" alt="Screenshot 2023-06-14 at 10 40 55 AM" src="https://github.com/carbon-design-system/carbon/assets/16520944/300e3a0c-5d34-4ada-801b-d2a756cbdd93">

**Comment by francinelucca** [comment]
The FileUploaderItem also needs to be updated to remove the `focusable=true` and `tabIndex=0` property. Compare v10 to v11:

v10:
 
<img width="446" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/79ae53a8-c10a-4424-99bc-da184445c9c9">

v11:
<img width="446" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/3cd5e411-00a5-4fe8-bcc5-21cb5145ef49">
