### ISSUE TITLE
[Bug]: TooltipDefinition and TooltipIcon's color overrides an icon's color

### ISSUE THREAD

**Issue by laukf** [carbon-design-system/carbon#13876]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v10

### Description

When I add a tooltip using the Carbon TooltipDefinition component, the color of the icon is overrided by the color of the tooltip.

### Reproduction/example

https://codesandbox.io/s/polished-glade-trdkbh?file=/src/index.js

### Steps to reproduce

1. Go to the above link
2. You will see that the Add16filled icon is filled with a grey color, which is the background color of the tooltip. However, the icon should be red as defined in the css rule 'tooltip'.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@laukf You just need to increase the specificity of your selector doing the override, and also override the hover colors. We specify both of those values by default to match the design spec, so I'm not sure what else we could do on our end to assist with overriding the colors. 

Here is an example of the styling needed: 

https://codesandbox.io/s/zen-jackson-prm1rz?file=/src/index.css
