### ISSUE TITLE
[Bug]: cannot have link in InlineNotification

### ISSUE THREAD

**Issue by craigyu** [carbon-design-system/carbon#13880]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.29.1

### React version

^18.2.0

## Detailed description

> Describe in detail the issue you’re having.

Adding link to InlineNotification component will throw the following error: 
`useNoInteractiveChildren.js:20 Uncaught Error: Error: component should have no interactive child nodes.`

> What did you expect to happen? What happened instead? What would you like to see changed?

An error was thrown and the page crashed. I would like to see it works as the example shown [here](https://carbondesignsystem.com/components/notification/code/#example).
![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25162561/e317cf95-57ab-4156-b162-45e1db3d76ce)

> What browser are you working in?

Chrome Version 113.0.5672.126 
## Additional information

- Screenshots or code
![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25162561/9651d0e6-56eb-4907-8182-24d0d6283a53)

![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25162561/b1c09ea5-566e-4e35-ab6d-fc9c7c46718a)

### Reproduction/example

https://stackblitz.com/edit/github-xnm85t?file=src%2FApp.jsx

### Steps to reproduce

1. Import InlineNotification from `@carbon/react`
2. Add `<a>` or `<Link>` tag as a child node of `<InlineNotification>`
3. An error is thrown and app crashes 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

https://github.com/bcgov/nr-spar

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @craigyu, interactive elements can only be placed in ActionableNotification. It has an `inline` prop which alters the styling to look like an InlineNotification.

The reason for this is InlineNotification can only have a `role` of `alert`, `log`, or `status` (default), which cannot contain interactive elements. ActionableNotification always has `role="alertdialog"` which can contain interactive elements and has additional props and functionality to support the extra accessibility requirements of having that role.

**Comment by craigyu** [comment]
> Hi @craigyu, interactive elements can only be placed in ActionableNotification. It has an `inline` prop which alters the styling to look like an InlineNotification.
> 
> The reason for this is InlineNotification can only have a `role` of `alert`, `log`, or `status` (default), which cannot contain interactive elements. ActionableNotification always has `role="alertdialog"` which can contain interactive elements and has additional props and functionality to support the extra accessibility requirements of having that role.

Thank you for your reply. 
However, it does not align with the documentation here: https://carbondesignsystem.com/components/notification/code/#example 
It demos a link inside an InlineNotification component. 
![image](https://github.com/carbon-design-system/carbon/assets/25162561/9bc31ace-fa77-45a3-b6ca-5f1c634b6321)

Using ActionableNotification requires a `actionButtonLabel` prop, and a button will be generated and that is not the desired usage in some cases. What's the best way to hide the action button in this case?
