### ISSUE TITLE
Release action `deploy-packages.yml` fails to create PRs to update dependencies for related projects

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon#13890]
### The problem

With our current release process the action that creates the website PR is currently failing. 

See failure here: https://github.com/carbon-design-system/carbon/actions/runs/5072131973/jobs/9109426520#step:6:543

From @tay1orjones:  "It looks like dependabot updated the action to v5 a couple months ago. Due to the node 18 snafu we might've missed updating some usage or something that we would've caught if the node 18 update wasn't blocking these from passing" 

See slack thread here for more info: https://ibm-studios.slack.com/archives/C0590RQ4XJR/p1684956548993249

### The solution

We found this thread that seems could be identifying a similar issue: https://github.com/peter-evans/create-pull-request/issues/1763

As well as this thread: https://github.com/peter-evans/create-pull-request/issues/1459

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
[`sync-platform-branch.yml` is also failing](https://github.com/tay1orjones/carbon-website/actions/runs/5152514319) with the same error.

**Comment by tay1orjones** [comment]
@kennylam This workflow to update carbon deps in the website is broken right now, but if you're interested, we could loop dotcom/web components into this workflow when we fix it to automatically open a PR on your repo to update carbon versions when they're available. 

We'd just need to nail down what commands to run on your repo to update the deps before issuing the PR.

**Comment by tay1orjones** [comment]
This is blocked by https://github.com/carbon-design-system/carbon-website/issues/3599

**Comment by francinelucca** [comment]
Fixed! https://github.com/carbon-design-system/carbon/actions/runs/5486818132
