### ISSUE TITLE
[Combobox unique value]: Design spec pass 2 (dev and a11y)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#13903]
### Acceptance criteria
- [x] Get feedback from the dev and a11y.
- [x] Refine spec if needed.
- [x] Finalize spec for implementation.

**Comment by thyhmdo** [comment]
After the discussion with the design team, accessibility, and devs, here are the enhancement suggestions: 

- [ ] **Allow users to input a new value in the ComboBox and accept it as a new value (without adding this new value to the option list).** 
   - Review this [basic flow in Figma ](https://www.figma.com/proto/l55GgCYsCLzIyNiPXz3nNr/Combobox?page-id=7%3A14043&type=design&node-id=59-24733&viewport=-1585%2C921%2C0.35&scaling=min-zoom&starting-point-node-id=59%3A24733&show-proto-sidebar=1)

1. Click on the chevron icon to open the list 
2. Click in the Combo Box
3. Start typing "Candies" (you can delete or go back to the previous screen) 
4. Use keyboard :Enter to accept the new value 

      
- [ ] **Provide users with Filter and Autocomplete capabilities when typing the value** 
     - Maybe provide Controls/Props under the playground 
     - Review this [filter function in Figma](https://www.figma.com/proto/l55GgCYsCLzIyNiPXz3nNr/Combobox?page-id=7%3A14043&type=design&node-id=59-27568&viewport=-1585%2C921%2C0.35&scaling=min-zoom&starting-point-node-id=59%3A27568&show-proto-sidebar=1) (same steps as the basic flow above)
     - Review this [Autocomplete function in Figma](https://www.figma.com/proto/l55GgCYsCLzIyNiPXz3nNr/Combobox?page-id=7%3A14043&type=design&node-id=59-28544&viewport=-1585%2C921%2C0.35&scaling=min-zoom&starting-point-node-id=59%3A28544&show-proto-sidebar=1) (same steps as the basic flow above)
     - Consider adding OnBlur to take the focus out and still accept the value
