### ISSUE TITLE
Experimental: review and finalize error states for components

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#1390]
We've had multiple issues with error/validations states in the new Duo system. We need to evaluate and finalize the style across the board.
- states: enabled, focus, active, hover
- icon or not icon
- what happens with small inputs?
- what happens with multi-line

**Comment by aagonzales** [comment]
@designertyler If you get bored and want to take a stab this be my guest 😆 
Link to components here: https://ibm.box.com/s/wjx23mseagc2air9l50j3p38katmptsk

**Comment by laurenmrice** [comment]
## Audit
- Consistently keep the Red 60, 2px, inside border and error message below. 
- Error message will be getting type style label-01 (12/16, .32)
- Changed alert icon in progress indicator to error icon.

- **Still need to figure out whether to keep or omit icon in fields. 
 - 2px Border paired with an error message displayed for color blindness is good however, an icon would be an even better visual cue.
 - Having an icon inside a field could cause potential issues for mobile.
 - Aria labels used to identify errors.
 - Will try to finalize this issue in Design review Friday.

![Artboard Copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/3b28d84c-f883-410f-86fe-b598380c64a8)

**Comment by laurenmrice** [comment]
-*In the future we may will may need an error icon indicator in tables for errors and display error message in tooltip, because the message can not go below the row.

![Screen Shot 2018-11-15 at 9.40.54 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/680468bf-be61-406e-a116-849eed217c39)

**Comment by laurenmrice** [comment]
## Exploration

![Artboard Copy 2.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/3ba899ea-7a3d-48b3-9e20-7dd489ae2669)

**Comment by aagonzales** [comment]
**Sprint 25**: pick final direction and submit dev issue with changes.
@laurenmrice

**Comment by laurenmrice** [comment]
## Final error message

Fields:
-Icon within field to the right
-2 px border
-error message below
![Artboard Copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/52fd93ce-ba51-4e95-b9ac-4d427c2f2c6c)
