### ISSUE TITLE
[Bug]: Number input accepts `e` in the input

### ISSUE THREAD

**Issue by herleraja** [carbon-design-system/carbon#13912]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.56.0

### React version

16

### Description

Number input field we should not allow the character `e`

### Reproduction/example

https://codesandbox.io/s/funny-wozniak-qd0gqw?file=/src/index.js

### Steps to reproduce

Go to https://v7-react.carbondesignsystem.com/?path=/story/components-numberinput--playground&knob-%22Hide%20password%22%20tooltip%20label%20for%20password%20visibility%20toggle%20(hidePasswordLabel)=Hide%20password&knob-%22Show%20password%22%20tooltip%20label%20for%20password%20visibility%20toggle%20(showPasswordLabel)=Show%20password&knob-ARIA%20role%20(role)=alert&knob-Accepted%20MIME%20types%20or%20file%20extensions%20(accept)=image/jpeg,image/png&knob-Action%20(NotificationActionButton%20%3E%20children)=Action&knob-Caption%20(caption)=00:00:00%20AM&knob-Close%20button%20icon%20description%20(iconDescription)=Clear%20file&knob-Default%20value%20(defaultValue)=twerte&knob-Duration%20in%20milliseconds%20to%20display%20notification%20(timeout)=0&knob-Error%20body%20(errorBody)=500kb%20max%20file%20size.%20Select%20a%20new%20file%20and%20try%20again.&knob-Error%20subject%20(errorSubject)=File%20size%20exceeds%20limit&knob-Field%20size%20(size)=sm&knob-FileUploaderItem%20height%20(size)=sm&knob-Filename%20(name)=README.md&knob-Filename%20height%20(size)=sm&knob-Form%20control%20type%20(type)=text&knob-Form%20item%20name%20(name)=dffd&knob-Form%20validation%20UI%20content%20(invalidText)=A%20valid%20value%20is%20required&knob-Helper%20text%20(helperText)=Optional%20help%20textretert&knob-Hide%20close%20button%20(hideCloseButton)=true&knob-Icon%20description%20(iconDescription)=describes%20the%20close%20button&knob-Invalid%20(invalid)=true&knob-Label%20text%20(labelText)=Text%20input%20label&knob-Light%20variant%20(light)=true&knob-No%20label%20(hideLabel)=true&knob-Show%20form%20validation%20UI%20(invalid)=true&knob-Show%20warning%20state%20(warn)=true&knob-Skeleton%20text%20at%20a%20larger%20size%20(heading)=true&knob-Status%20for%20file%20name%20(status)=edit&knob-Status%20icon%20description%20(statusIconDescription)=describes%20the%20status%20icon&knob-Subtitle%20(subtitle)=Subtitle%20text%20goes%20here.&knob-Supports%20multiple%20files%20(multiple)=true&knob-Tab%20index%20(tabIndex)=0&knob-The%20notification%20kind%20(kind)=info&knob-The%20number%20of%20lines%20in%20a%20paragraph%20(lineCount)=3&knob-Title%20(title)=Notification%20title&knob-Tooltip%20alignment%20(tooltipAlignment)=center&knob-Tooltip%20position%20(tooltipPosition)=bottom&knob-Use%20multiple%20lines%20of%20text%20(paragraph)=true&knob-Warning%20state%20text%20(warnText)=This%20will%20overwrite%20your%20current%20rtw&knob-Width%20(in%20px%20or%20%)%20of%20single%20line%20of%20text%20or%20max-width%20of%20paragraph%20lines%20(width)=100%

Remove the invalid flag and set the allow empty flag like below

![image](https://github.com/carbon-design-system/carbon/assets/18572477/945acfe3-59b7-4c7e-b1bb-f64cb13b34d4)

Now type `e` in the number input field. Its number input field we should not allow the character `e`

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

I'm working on Maximo asset monitor and Maximo Edge Data Collector

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
The E stands for the exponent, and it is used to shorten long numbers. This is part of the spec for the native HTML `input type="number"` , [here is an example](https://codesandbox.io/s/new-flower-m28k5j?file=/src/index.js). `e` is considered a valid floating point number. There are some workarounds in [this thread](https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in) if you would like to prevent this



<img width="805" alt="Screenshot 2023-06-02 at 11 56 03 AM" src="https://github.com/carbon-design-system/carbon/assets/11928039/d309a6f7-70d2-4df6-8dc2-e85e1dd62bee">

Info: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#a_simple_number_input

https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number

**Comment by herleraja** [comment]
Thanks @tw15egan
