### ISSUE TITLE
[Bug]: Tooltip does not render when inside TableHeader

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#13918]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.30.0

### React version

18.2.0

### Description

Cannot see tooltip when hovering over TableHeader

### Reproduction/example

https://stackblitz.com/edit/github-9tf2bv-nk1cpf?file=src%2FApp.jsx,package.json

### Steps to reproduce

1 - Hover over header
2 - notice no tooltip is displayed

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by andreancardona** [comment]
Currently the tooltip only supports children as buttons as can be seen here: https://stackblitz.com/edit/github-9tf2bv-tev6uw?file=package.json

We will clear this up by updating the documentation. :)
