### ISSUE TITLE
DataTable sort arrows stay selected, making no-sort state confusing. Also unwanted box displays.

### ISSUE THREAD

**Issue by tellis1** [carbon-design-system/carbon#1393]
## Detailed description

> Describe in detail the issue you're having.

A bug was filed about the 3rd click of the sort appearing to do nothing, which is true if descending and no-sort order are the same. This is a result of a few uI issues. Essentially while selected, the no-sort state shows a down arrow, while it shouldn't show anything. This disappears if you click away, but also why is there a selected state for the arrow showing an outline in the first place? The selected state has no obvious purpose, and the box clashes with our UI. Either way there should be no arrow for the no-sort state before clicking away, as it makes the sort confusing and difficult to follow what order you're sorting in.

> Is this issue related to a specific component?

DataTable

> What did you expect to happen? What happened instead? What would you like to see changed?

No weird box, no-sort state should never appear with an arrow.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

9.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM SPM ICM

## Steps to reproduce the issue

1. Create a Datatable with sorting
2. Click sort arrow 3 times back to no-sort state

## Additional information

No-sort state before changing sort:
<img width="1465" alt="screen shot 2018-11-05 at 2 25 34 pm" src="https://user-images.githubusercontent.com/12686531/48021577-f027e580-e106-11e8-8c9f-d020d0e83898.png">

No-sort state after changing sort, implies descending sort until click away. 
<img width="1482" alt="screen shot 2018-11-05 at 2 25 58 pm" src="https://user-images.githubusercontent.com/12686531/48021588-f61dc680-e106-11e8-8343-164d7bec908f.png">

**Comment by joshblack** [comment]
@tellis1 thanks for taking the time to make this issue! 😄 Before getting started, just wanted to make sure that when making issues and engaging here that we stay respectful of the work that contributors have done for this library. A lot of work has gone into these components, and often times things are the result of constraints that the system needs to adhere to and may not have an obvious answer. As a result, calling certain aspects of work ugly or purposeless without understanding the background of the work will most likely result in unproductive conversations.

For this specific issue:

> The selected state has no obvious purpose, and the box is ugly.

The primary purpose here is accessibility for focus interactions. The outline appears when the button has a focus state and is a necessary aspect of the design. The other issue is that this sort is currently a tri-state sort. We should 100% come up with a better design (and if you have suggestions would love to hear them!) but in the meantime this state and appearance signals that the control is interactive for keyboard users.

If you have any suggestions for design or component API changes, let us know!

**Comment by tellis1** [comment]
@joshblack Hi Josh, apologies. My intention was not to demean any work, just to state the issues I'm trying to work around in my use case. I assumed the box existed for accessibility reasons, but it only displays before clicking away. Essentially we have no need for the focus state, and therefore it isn't helpful to our UX. I'm also noticing it doesn't appear in the react carbon components storybook, instead the arrow shows on hover and the box doesn't display at all. Though I don't see a prop that would directly relate to it, is there a way to disable it? This is how our wrapper uses the table header if it helps you spot anything suspicious:

``` 
import CarbonDataTable from "carbon-components-react/lib/components/DataTable";
...
return (
      <CarbonDataTable.TableHeader
        isSortable={isSortable !== false}
        isSortHeader={isSortable !== false}
        onClick={this.onClick}
        sortDirection={sortDirection}
      >
        {header}
      </CarbonDataTable.TableHeader>
);
```

So the issue I'm experiencing is really that on hover the same arrow is displayed to indicate inter-activeness, and we somehow have enabled this behavior to be on focus instead, requiring a click away instead of a move away to identify current state. I suppose this is inherently a problem in the tri-state sort as you say as I'm not sure there's an accepted no-sort symbol. So if there's a way to disable that behavior, that would be our fix for the time being.

**Comment by joshblack** [comment]
Agreed, the tri-state sort causes some confusion here. Might be helpful for us to just specify the first header as sortable by default 👍 

If the case is the tri-state issue, then we should use this issue to continue this conversation: https://github.com/IBM/carbon-components-react/issues/1122

If not, let me know what specifically you would like to see changed and I can see what we can do!

**Comment by tellis1** [comment]
@joshblack The DataTable here doesn't have the focus state,, instead showing the arrow on hover when there is no sort:
http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20sorting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

If there is a way we can have this behavior instead I don't think we actually need a change. Is that possible? Is it a side-effect of how we've set up our wrapper?
