### ISSUE TITLE
[Bug]: The wrong page of page list will be displayed when navigated from one page to another through the left navigation panel

### ISSUE THREAD

**Issue by lavarajallu** [carbon-design-system/carbon#13955]
### Package

@carbon/react, @carbon/styles, carbon-components, carbon-components-react

### Browser

Chrome, Safari, Firefox

### Package version

v10.48.0

### React version

v17.0.2

### Description

The wrong page of page list will be displayed when navigated from one page to another through the left navigation panelthe 

### Reproduction/example

@carbon/react

### Steps to reproduce

1. Install  "@console/pal": "1.558.7" and install  EnhancedDataTable from console/pal
2. import { EnhancedDataTable } from '@console/pal/Components';
3. After that check on the bottom pagination there If you change from page 1 to page 2 keep page 2 then go to another data table from another page there also shows page 2 not getting page 1. 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

EnhancedDataTable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@lavarajallu this seems like an issue with the `@console/pal` package, I would suggest creating an issue there as that is not managed by this team
