### ISSUE TITLE
[Feature Request]: Add property for Tag to specify html tag to be rendered

### ISSUE THREAD

**Issue by kapetr** [carbon-design-system/carbon#13959]
### The problem

We need to render `Tag` as an inline element in text of documentation pages created by Markdoc from .md files. The problem is that `Tag` renders into `<div>`,  and text paragraph rendered by Markdoc is always wrapped in `<p>` element, so react throws hydration error, because `<div>` is not allowed in `<p>`.

Example of code, that throws hydration error:
```
import { Tag } from '@carbon/react';
const ParagraphWithTag = () => {
  return <p>Paragraph with <Tag>tag content</Tag> inside.</p>;
}
```

### The solution

Add `as` property to `Tag` component, where html tag can be specified, to which component is then rendered.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
That makes sense, `p` only accepts [inline text elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#inline_text_semantics) as children, and changing the `Tag` markup in my browser from `div` to `span` doesn't seem to cause any a11y / styling issues.

**Comment by sstrubberg** [comment]
@tulivlk are you open to making a PR against this?

**Comment by sstrubberg** [comment]
@tulivlk hit me up if you need any support.
