### ISSUE TITLE
Combobox unique value: implementation

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#13975]
Ref link for implementation https://github.com/carbon-design-system/carbon/issues/13903

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/14006
- [x] Filter https://github.com/carbon-design-system/carbon/pull/13904
```

**Comment by tay1orjones** [comment]
We should probably update downshift before we start work on these: https://github.com/carbon-design-system/carbon/issues/13749
