### ISSUE TITLE
Tree view component functionality problems

### ISSUE THREAD

**Issue by Hayley-l-williams** [carbon-design-system/carbon#13970]
## Summary

This is a request for the [Tree view component](https://carbondesignsystem.com/components/tree-view/usage/) to define additional keyboard interaction. 

The product I work on would like to associate actions with each item. View the image below for example.

Currently, as development has implemented this component in our product, it is not possible to reach these actions by keyboard. It be nice to include this use case in the component itself - how to reach the buttons by keyboard 

<img width="1605" alt="Screenshot 2023-06-08 at 2 54 44 PM" src="https://github.com/carbon-design-system/carbon-website/assets/102319049/fc21e715-3436-4fc7-96e9-6ad66d91f199">

**Comment by alisonjoseph** [comment]
Hi, can you provide more details on the keyboard interactions you are looking for, the Treeview component follows the keyboard interactions recommended by the w3 spec. https://www.w3.org/WAI/ARIA/apg/patterns/treeview/

**Comment by alisonjoseph** [comment]
@Hayley-l-williams you can open an enhancement request [here](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&projects=&template=FEATURE_REQUEST_OR_ENHANCEMENT.yaml&title=%5BFeature+Request%5D%3A+). This will drop it into our enhancements pipeline, where the team will evaluate if its needed in Carbon, and then see where it falls priority-wise in our backlog. If you have designers/devs who can help contribute it to the system that would help expedite the [process](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#type-enhancement-).

**Comment by Hayley-l-williams** [comment]
@alisonjoseph I opened the enhancement[ here ](https://github.com/carbon-design-system/carbon/issues/14116)and plan on making a mockup to help expedite the process. This can maybe be closed then? Thanks!
