### ISSUE TITLE
Closing Overflow menu with Esc key closes side nav

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#1398]
1. Go to the [Overflow Menu page](http://www.carbondesignsystem.com/components/overflow-menu/code)
2. Drop down an Overflow menu (using Space key or Enter key)
3. Now type ESC to close the menu
4. Notice that the Side Nav closes as well

The key handler for Esc needs to call event.stopPropagation();
and possibly also event.preventDefault();

**Comment by carmacleod** [comment]
The Dropdown has the same problem. See point 2 of https://github.com/IBM/carbon-components/issues/1147.

**Comment by emyarod** [comment]
if I'm not mistaken this issue has been resolved by #1527
