### ISSUE TITLE
[Bug]: $tokens is defined in multiple places in scss

### ISSUE THREAD

**Issue by Kilian-Collender** [carbon-design-system/carbon#13987]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.31.0

### React version

17.0.2

### Description

Looks like some changes have been made to https://github.com/carbon-design-system/carbon/commit/a1a528224476cfe00316ff83582fb2859bc09dea

Which include defining the variable $tokens in _layout
 https://github.com/carbon-design-system/carbon/blame/ec85fb2920f2921cbd5194fceaf7efcd7608aaf9/packages/styles/scss/utilities/_layout.scss#L15

This is causes issues now as type forwards the variable $tokens https://github.com/carbon-design-system/carbon/blob/ec85fb2920f2921cbd5194fceaf7efcd7608aaf9/packages/styles/scss/type/_index.scss#L83

This is causing our scss not to compile

### Reproduction/example

https://stackblitz.com/edit/github-vwvzgk?file=src%2Findex.scss

### Steps to reproduce

We use a global style sheet that imports the key parts of carbon styles that are required. This global file looks something like this
```
@forward '@carbon/react/scss/config' with (
  $css--font-face: false,
  $css--body: true,
  $css--default-type: false,
  $css--reset: true
);
// Reset
@use '@carbon/react/scss/reset';
// Grid
@forward '@carbon/react/scss/grid';
// Theme helper
@use '@carbon/react/scss/compat/themes' as compat;
@use '@carbon/react/scss/themes';
@forward '@carbon/react/scss/theme' with (
  $fallback: compat.$g10,
  $theme: themes.$g10
);

// Helpers
@forward '@carbon/react/scss/spacing';
@forward '@carbon/react/scss/type';
@forward '@carbon/react/scss/colors';
@forward '@carbon/react/scss/motion';

@forward '@carbon/react/scss/utilities'; 
```

When we try to use this global file in other places, the build fails when it hits `@forward '@carbon/react/scss/utilities'; `

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Pak WAIOPS

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@janhassel is this addressed with https://github.com/carbon-design-system/carbon/pull/13984?

**Comment by janhassel** [comment]
@tw15egan If this came from the layout module, then yes. When I moved the tokens from `scss/utilities/layout` into `scss/layout` I ran into the same issue and hence renamed them to `$layout-tokens` in #13984 

@Kilian-Collender could you verify this issue is resolved with v1.31.3?

**Comment by Kilian-Collender** [comment]
Will do, looking at the changes you made that would fix the problem I was seeing

**Comment by tw15egan** [comment]
Thanks for reporting back!
