### ISSUE TITLE
NumberInput: Misalignment of number controls

### ISSUE THREAD

**Issue by GabrieleBarboni** [carbon-design-system/carbon#1399]
When a NumberInput's helperText is used, it causes the number controls to no longer be centered in the input field.

![image](https://user-images.githubusercontent.com/33227921/48077913-b0392f00-e1e8-11e8-8bf3-c2e30f37c8fb.png)

This code illustrates this behavior: https://codesandbox.io/s/j3173kr319

**Comment by tw15egan** [comment]
Closing in favor of https://github.com/IBM/carbon-components/issues/1391, which is being fixed in https://github.com/IBM/carbon-components/pull/1392

In the meantime, ensure your number input wrapper looks like this:

`<div data-numberinput class="bx--number bx--number--helpertext">`
