### ISSUE TITLE
[Bug]: v11 migration experience

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13999]
<img width="877" alt="image" src="https://github.com/carbon-design-system/carbon/assets/15822070/75bea9ba-52ce-4cc9-8c11-d772b48c7e9f">

<img width="950" alt="image" src="https://github.com/carbon-design-system/carbon/assets/15822070/7219c91e-aa79-4f89-8b77-488db9f49cac">

No haz codemodz?

**Comment by tay1orjones** [comment]
Duplicate of https://github.com/carbon-design-system/carbon/issues/14001
