### ISSUE TITLE
[ComboBox] Autocomplete implementation

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#14007]
Ref link for implementation https://github.com/carbon-design-system/carbon/issues/13903

Example: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx
Repo for ComboBox https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx

This looks like it's not an easy update and going to take some time

**Comment by sstrubberg** [comment]
Blocked by https://github.com/carbon-design-system/carbon/issues/13749

**Comment by tay1orjones** [comment]
Might be blocked by needing to refactor ComboBox off of `<Downshift/>` and over to `useCombobox`.

**Comment by tay1orjones** [comment]
After more discussion, the dev team feels that this is blocked by the refactor:
 
* https://github.com/carbon-design-system/carbon/issues/14684

**Comment by tay1orjones** [comment]
In addition to the existing behavior spec for this, we should consider the [APG example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/) for this that includes some nice functionality that uses the selection range

**Comment by tay1orjones** [comment]
#14684 is complete

**Comment by thyhmdo** [comment]
> In addition to the existing behavior spec for this, we should consider the [APG example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/) for this that includes some nice functionality that uses the selection range


Very similar to what Taylor referred here:
- Click on the input
- Start writing out the first letter 
- All options match the typed letter(s) will be filtered out
- It highlights and spells out all the options
- The first option (following the typed letters)

https://github.com/user-attachments/assets/68b1c388-c9db-4562-85ac-063145701499
