### ISSUE TITLE
Table: Add support for group headers

### ISSUE THREAD

**Issue by stanislavgeorgiev** [carbon-design-system/carbon#1400]
### Summary

We have a requirement to show group table headers and I was wondering if there are any plans to adding something like this:

![image](https://user-images.githubusercontent.com/1253469/48109998-d0ccad80-e217-11e8-8e44-469723191773.png)

We already have this implemented in Dojo but we're moving over Angular and we now use the Carbon Angular components library. It looks like Carbon itself doesn't have support for group headers though.

### Justification

Commercial use in an IBM Application Delivery Intelligence

### Specific timeline issues / requests

2019 Q1

### Available extra resources

We have 4 front end developers who could potentially provide usage guidance or help with code.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Any chance you can show a bigger screenshot so we better understand the bigger context and discuss with our designers? Thanks!

**Comment by stanislavgeorgiev** [comment]
I think that's the extend of what I can share in the public space. The key functionality for us is not having to repeat the group header name for each column as that would take too much space.

![image](https://user-images.githubusercontent.com/1253469/48138143-a3145280-e271-11e8-9ea1-e08d751b811e.png)

**Comment by joshblack** [comment]
cc @IBM/carbon-designers

**Comment by aagonzales** [comment]
Could you elaborate on what a group header is? What is its functionality? What is it grouping? What are the question mark icons doing?

**Comment by stanislavgeorgiev** [comment]
@aagonzales A group header is label that applies to multiple columns. In the above example, "Executable Lines" applies to all the columns that it's positioned above and really translates to "Executable Lines Covered", "Executable Lines Total", etc. If we didn't have it then we would've had 3 line column header labels and a lot of repetition. Grouping columns is a very common pattern in reporting applications.

You can ignore the (?) icons, it's for showing description tooltips about what data that column is trying to show.

**Comment by aagonzales** [comment]
I haven't seen this before but I can see how it might be beneficial. There will need to be some exploration done around how we'd want to do this in the v10 styling.

I'm also curious how this works functionally. Is this only ornamental/labeling or does it actually group those items in the database (or where ever the info is kept)?

**Comment by jeanservaas** [comment]
Not stale for now... interesting, this is the issue Nicole Roppel brought up the last two fridays in the design review and we were not sure how to handle it. This may be somewhat of a blocker for multiple teams.
