### ISSUE TITLE
[Feature Request]: Multiselect add new item

### ISSUE THREAD

**Issue by rahulrkr08** [carbon-design-system/carbon#14005]
### The problem

Our current application is using react-select for the dropdown options. And we are migrating to a carbon design system. We found that a feature to add new items to a dropdown/select is not available currently with carbon-react.

### The solution

A new feature to add items to the dropdown on filtering if it does not exist in the items.

### Examples

<img width="572" alt="Screenshot 2023-06-15 at 1 00 05 AM" src="https://github.com/carbon-design-system/carbon/assets/2932484/15540dfc-ec46-4328-b8ee-a7bac75a860d">

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
dupe https://github.com/carbon-design-system/carbon/issues/6102
