### ISSUE TITLE
[Combobox unique value]: New value dev implementation

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#14006]
Ref link for implementation https://github.com/carbon-design-system/carbon/issues/13903

#### Acceptance Criteria

Allow users to type in a new value in the ComboBox and accept it as a new value

- [x] Add a new prop to enable the behavior
- [x] Typing and hitting enter should no longer clear the input as described in the spec: https://github.com/carbon-design-system/carbon/issues/13903#issuecomment-1577463748
- [x] Evaluate if we need to modify the selectedItem state, but users could probably get the value without this even using target.value in the onChange callback if we have a ref on the input

**Comment by tay1orjones** [comment]
For this it seems the primary piece is to update the component to not clear the input after hitting enter if there is not a matched element in the listbox.

There was a question of if we needed to wait on this until we refactored ComboBox off of <Downshift/> to instead use `useComboBox` https://github.com/carbon-design-system/carbon/issues/14684, but after some discussion we think the refactor shouldn't be necessary for this.
