### ISSUE TITLE
NumberInput: Misalignment of number controls

### ISSUE THREAD

**Issue by GabrieleBarboni** [carbon-design-system/carbon#1401]
Still not working with latest carbon components version 9.46.1 (which should have fix for #1399 -> #1392 )

When a NumberInput's helperText is used, it causes the number controls to no longer be centered in the input field.

![image](https://user-images.githubusercontent.com/33227921/48122930-06ee4980-e279-11e8-8dd5-38888866366a.png)

This code illustrates this behavior: https://codesandbox.io/s/z28qj59kp4

**Comment by tw15egan** [comment]
Issue moved to [IBM/carbon-components-react #1533](https://github.com/IBM/carbon-components-react/issues/1533) via [**ZenHub**](https://www.zenhub.com/)
