### ISSUE TITLE
[Bug]: Datepicker - Cannot close calendar on keyboard interaction

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#14025]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.31.0

### React version

18.2.0

### Description

https://github.com/carbon-design-system/carbon/assets/40550942/7f695c5d-d551-4ac7-817c-3ffbc7d1a43d

### Reproduction/example

https://stackblitz.com/edit/github-3wiety?file=package.json

### Steps to reproduce

Use keyboard navigation, enter 2022-01-01 as the first date, tab to second date and enter 2022-01-07.
Try to close the calendar, both via keyboard or outside click does not work

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tongyy** [comment]
Hi @francinelucca 

PR created [14028](https://github.com/carbon-design-system/carbon/pull/14028)

I am new to the community. I am interested in being a contributor as a coder.
by any chance, can you also review my other minor PR ? [14018](https://github.com/carbon-design-system/carbon/pull/14018)
