### ISSUE TITLE
[Question]: Modals and visibility

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#14031]
### Question for Carbon

Why is the `visibility` property used to drive the modal existence on the page, rather than conditional rendering?

This is causing so much pain for automated tests (e.g. RTL) where none of `not.toBeVisible` or `not.toBeInTheDocument` are working.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Hey there @marcellobarile, it could just be a legacy implementation thing, `Modal` is one of the older components in the repo. One thing I'm seeing that relies on the `Modal` to stay in the `DOM` is the "slide-in" animation, which would need to be reworked if it were to be conditionally rendered. We'd be happy to look at any PR you could provide that explores changing the component to be conditionally rendered, or to assist with better modal testing (maybe adding `aria-hidden="true"` when `open == false`).

**Comment by marcellobarile** [comment]
@tw15egan, while I was looking for a solution I stumbled upon the `ComposedModal`, what's the difference between that one and the `Modal`?

**Comment by tw15egan** [comment]
@marcellobarile `Modal` is the legacy implementation, and constructs the `ModalHeading` + `ModalFooter` via props like `modalHeading` and `primaryButtonText`, and renders all children inside of `ModalContent`. On the other hand, `ComposedModal`  exposes the `ModalHeading`, `ModalFooter`, and `ModalBody` components for a bit more flexibility.

**Comment by marcellobarile** [comment]
@tw15egan thanks!
From a developer perspective the experience is not the best; `ModalWrapper` is marked as deprecated, but not `Modal`, though having two similar implementations living together without any mention in the documentation (as far as I saw, if I didn't miss something) is quite confusing.

Talking about the mentioned improvement, would make sense in your opinion to invest time in the `Modal`? 

Thank you again for your time :)

**Comment by tw15egan** [comment]
The underlying markup should be the same, so we should be able to make the change in both places without much more effort. You can focus on `Modal` and we can look into porting the changes over to `ComposedModal`
