### ISSUE TITLE
Long accordion titles wrapping on a second line are not left justified

### ISSUE THREAD

**Issue by natmasse** [carbon-design-system/carbon#1403]
Long accordion titles wrapping on a second line are not left justified

## Detailed description

> Describe in detail the issue you're having.
When accordion title doesn't fit on one line, it is centered instead of being left justified
<img width="261" alt="screen shot 2018-11-07 at 1 06 32 pm" src="https://user-images.githubusercontent.com/40840777/48150943-090ed300-e28e-11e8-853d-c3ab954f110c.png">

> Is this issue related to a specific component?
Accordion

> What did you expect to happen? What happened instead? What would you like to see changed?
Expecting all titles to be left justified

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components 9.46.1
carbon-components-react 6.46.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud console

## Steps to reproduce the issue

1. Create accordion with longer item titles
2. Resize window until title doesn't fit and wraps on a second line

**Comment by joshblack** [comment]
cc @IBM/carbon-designers what's the intended spec here for text truncation in an accordion title?

**Comment by designertyler** [comment]
Text should definitely be left aligned.

In that example I would expect the row's height to increase so the second line of text isn't cropped. I'm not sure if that's part of the question though.

**Comment by natmasse** [comment]
Can the left alignment be fixed soon? We're going to production on Nov 19th.

**Comment by emyarod** [comment]
not sure why the text is cropped in the original screenshot and I can't replicate that behavior, but the alignment issue should be addressed in #1425
