### ISSUE TITLE
[Bug]: DatePicker - Range calendar does not close on lose focus

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#14033]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.31.3

### React version

18.2.0

### Description

When using keyboard to select dates in a range calendar, the calendar can only be closed via `Escape` key, would expect the calendar to close on tab out

https://github.com/carbon-design-system/carbon/assets/40550942/75d60272-50b6-477d-9ebe-47dbadfa50c8

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

Use keyboard to select a date range on calendar and then tab out of the calendar, notice calendar stays open. Focus calendar again and press `escape` key, notice calendar closes

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/12594

**Comment by tay1orjones** [comment]
Duplicate of https://github.com/carbon-design-system/carbon/issues/12594
