### ISSUE TITLE
[Bug]: App crashes when using arrow keys to navigate OverflowMenu

### ISSUE THREAD

**Issue by adamalston** [carbon-design-system/carbon#14046]
### Package

carbon-components-react

### Browser

Edge

### Package version

v7.59.8

### React version

v17.0.2

### Description

When attempting to navigate through overflow menu items using keyboard arrow keys (both up and down), the app crashes if the items are wrapped inside a React Fragment.

I think this issue warrants severity 2 because of the crash. However, I have assigned it a severity 3 because a user can click the overflow menu item. If that behavior is considered inaccessible, feel free to increase the severity.

### Reproduction/example

https://codesandbox.io/s/amazing-sutherland-fhfk2c?file=/src/index.js

### Steps to reproduce

1. Click on the overflow menu to open it
2. Press the down arrow on the keyboard 2 times
3. See crash (`Cannot read properties of undefined (reading 'overflowMenuItem')`)
5. Reload the page
6. Click on the overflow menu to open it
7. Press the up arrow on the keyboard 2 times
8. See crash (`Cannot read properties of undefined (reading 'overflowMenuItem')`)

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

DataPower

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tongyy** [comment]
It seems this is by design. Please take a look at the console. 

![image](https://github.com/carbon-design-system/carbon/assets/24784725/a07b1bac-6e6d-47b6-802a-801800c4b910)

**Comment by tay1orjones** [comment]
Good eye @tongyy, that's correct. OverflowMenuItems need to be direct children of OverflowMenu in order to work properly.
