### ISSUE TITLE
Lack of Property Hints for Components Like Button

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#14055]
## Summary
We are currently contemplating the use of the Carbon Design System for our future React/TypeScript project. In order to enhance our development experience, we are looking for a way to access autocomplete features for the props of components like Button. However, it appears that some components like Button do not come with TypeScript definitions.

Additionally, when using standard JSX buttons, we are able to access standard props. This is not the case when working with custom Buttons. Could you shed some light on why this is the case, and if there is a way we could achieve the same experience with custom Buttons?

Thank you for your assistance in this matter!

**Comment by tay1orjones** [comment]
Hey @philipp-merk-neuravity, adding typings for components in `@carbon/react` are in progress, #12513, and about halfway complete. 

Typings for Button specifically were delivered last week, https://github.com/carbon-design-system/carbon/pull/13811. This should go out in our next minor version, planned for release today. Hope this helps!
