### ISSUE TITLE
[Bug]: Date picker has multiple optional props marked as required in documentation and in types

### ISSUE THREAD

**Issue by cvikram21** [carbon-design-system/carbon#14078]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.32.0

### Description

allowInput, appendTo, children, className, invalid, invalidText, warnText

All the above props are marked as required in the documentation and the types for the DatePicker component.

Documentation and types should be fixed to have only required props marked as required.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-datepicker--single-with-calendar

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/docs/components-datepicker--single-with-calendar

Can be seen in storybook

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tongyy** [comment]
fixed in https://github.com/carbon-design-system/carbon/pull/14080

**Comment by guidari** [comment]
Fixed in the issue #14080
