### ISSUE TITLE
Discord invite link in `README` not working

### ISSUE THREAD

**Issue by chartgerink** [carbon-design-system/carbon#14086]
Hi 👋 Love the carbon system!

I wanted to join the Discord to see what's up and whether I could get some informal help with a TypeScript issue, but the one in the readme is not working for me. Maybe the link expired, I don't know? 

I only see that the invitation cannot be accepted.

<img width="718" alt="Screenshot 2023-06-26 at 14 28 33" src="https://github.com/carbon-design-system/carbon/assets/2946344/df55d9c2-bb88-4e93-9b76-e0bf8a4ace09">

If this is a non-issue, of course feel free to close this without answering - I won't be offended 😊

**Comment by tay1orjones** [comment]
@chartgerink Hey sorry about that, does this link work for you? https://discord.gg/J7JEUEkTRX It's the same link in the readme that should never expire. Discord won't regenerate it.

This alternate invite link should be live for the next 7 days: https://discord.gg/6ZqazTYv

**Comment by chartgerink** [comment]
Thanks @tay1orjones - the first link you provided works for me now :-) Sorry if this was a fluke and I did something wrong. 

Appreciate the help 🙌
