### ISSUE TITLE
[a11y]: FileUploaderDropContainer component is not accepting file type other than images in Firefox browser

### ISSUE THREAD

**Issue by ShubhamKale31** [carbon-design-system/carbon#14095]
### Package

carbon-components

### Browser

Firefox

### Operating System

MacOS

### Package version

v10.58.3

### React version

v18.14.0

### Automated testing tool and ruleset

Latest deployment

### Description

 I am using FileUploaderDropContainer of react 10.x version. On Chrome it is working fine and able to upload files of all types, but on Firefox not able to select application/pdf or htmls, csv or text files. Why is there a different behavior on Firefox. 

Code logic used:
```
<FileUploaderDropContainer
    {...props}
    onAddFiles={onAddFiles}
    accept={[
        "image/*",
        "application/*",
        "text/*",
        "audio/*",
        "video/*",
    ]}
    labelText={intl.formatMessage(messages.upload_file_text)}
    disabled={hideDropContainer()}
    multiple={false}
/>
```

### Reproduction/example

Yes

### Steps to reproduce

Use FileUploaderDropContainer component in Firefox browser. When uploading the file it is not allowing other than images files type. But it is working fine in Chrome .

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Issue seems to occur even when just using the browser native `input type="file"` so this may be a Mozilla bug: https://stackblitz.com/edit/github-odf4xg?file=src%2FApp.jsx

**Comment by ShubhamKale31** [comment]
So any solution or alternative for this issue to make it work in Mozilla @tw15egan

**Comment by tw15egan** [comment]
What files are you trying to _exclude_ from the file uploader? Seems like you are accepting all types, so why not just pass in no `accept`? Or be more specific with the filetype extensions you accept, it seems like Firefox does not like the MIME type wildcard selectors, but [handles specific filetypes fine](https://stackblitz.com/edit/github-odf4xg-t3bezt?file=src%2FApp.jsx)

**Comment by ShubhamKale31** [comment]
It worked when I removed `accept` parameter

**Comment by tw15egan** [comment]
Glad that worked 👍
