### ISSUE TITLE
Alternate CSS class prefix support for markups

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1409]
This issue is for tracking the effort to support alternate CSS class prefix support for our markups (`.hbs` files).

### Justification/"Must have" functionality

Currently we are discussing the possibility to switch `bx` CSS class prefix to something else, e.g. `ibm`.

### Specific timeline issues / requests

TBD

### Preferred approach

`button.hbs`:

```handlebars
<button
  class="{{prefix}}--btn {{prefix}}--btn--{{variant}}{{#if small}} {{prefix}}--btn--sm{{/if}}"
  {{#if danger}} aria-label="danger" {{/if}} type="button">Button</button>
...
```

`button.config.js`:

```javascript
const { prefix } = require('../../globals/js/settings');

...

module.exports = {
  ...
  variants: [
    {
      ...
      context: {
        prefix,
        ...
      },
    },
    ...
  ],
  ...
};
```

### Alternate approach

Cutting a branch and making hard-coded changes (to the CSS prefix) there. We'll have to sync branches between stable vs. next release that tends to cause frequent merge conflict as we saw in `v9` and earlier experimental theme effort.

**Comment by asudoh** [comment]
CC @IBM/carbon-developers

**Comment by alisonjoseph** [comment]
I like the approach you've outlined above, it also allows us to make that update now and then easily swap to the new prefix before v10 launch.
