### ISSUE TITLE
[Question]: Complaining about `__docgenInfo` being present in `HeaderPanel`

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#14096]
### Question for Carbon

While bumping  `@carbon/react` from `1.31.3` to `1.32.0`, all our tests are failing with the following error. Any hint?

EDIT: this is affecting not only tests but also the real deal

![image](https://github.com/carbon-design-system/carbon/assets/1809476/b4a9a671-952e-4fea-97e6-b37dcb7359e3)

![image](https://github.com/carbon-design-system/carbon/assets/1809476/6db72076-e9bb-4a99-8f47-dbd65e5c6463)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by marcellobarile** [comment]
and this is the source code: 
![image](https://github.com/carbon-design-system/carbon/assets/1809476/0c9d5448-d7d6-4372-8156-10c37d1aacb4)

is it expected to be used here?

**Comment by marcellobarile** [comment]
this is the commit that introduce the change, I also saw that is not used anywhere else in the codebase.
https://github.com/carbon-design-system/carbon/commit/e3df4a6446b301141b1423c4564330718a470193#diff-ca39321cb666082bc3622dfee47de033229fc34c843e25b43be583322a499905R74

**Comment by marcellobarile** [comment]
EDIT: this is not affecting only Cypress, but also the real deal:
![image](https://github.com/carbon-design-system/carbon/assets/1809476/ad85f4f1-2a1c-4a47-ba48-622c11278ca7)

**Comment by tw15egan** [comment]
@marcellobarile thanks for catching this, pushing up a fix now. Sorry about that!
