### ISSUE TITLE
Coded examples - provide build instructions 

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#14098]
### Package

@carbon/react, @carbon/styles

### Package version

N/A

### Description

The example apps do not work unless a build has been ran on the root of the project, which isn't on the readme instructions (at least not for all). This issue is to revise the readmes on all the examples and make sure they have build/running instructions.

### Reproduction/example

N/A

### Steps to reproduce

1 - clone carbon repo (need to clone from 0 so that a build is not present)
2 - cd to a carbon example (e.g. light-dark-mode)
3 - `yarn install`
4 - `yarn dev`
See error
<img width="1792" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/0c1eea96-05cb-44a0-8b46-3ed9c6672cad">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This would potentially be ~34 examples if we include the root examples, per-package examples, and elements examples
