### ISSUE TITLE
Update downshift: research sprint

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#14102]
Acceptance Criteria:

- Attempt to update to latest.
- Review all 4 components for defects resulting from the update. (may not be possible in one sprint, might need to defer this into another sprint)
- Collect and categorize the defects, generate a plan of action to address everything.
- Playback findings to the dev team if needed.
- Create new issues or tasklists for all the items, we probably won't be able to incrementally deliver this. It'll be a draft PR that lives for a few sprints.

**Comment by tay1orjones** [comment]
Calling this one closed as we got the update researched and a PR up #14276, mostly complete just need to finalize testing
