### ISSUE TITLE
[Bug]: TextInput - Display the character count for Fluid style - implementation

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#14100]
Link: https://react.carbondesignsystem.com/?path=/story/components-textinput--playground

Currently, there is no way to review how `enableCounter` and `maxCount` work on Fluid style for TextInput 

Waiting on specs. https://github.com/carbon-design-system/carbon/issues/13991

**Comment by alisonjoseph** [comment]
Viewable here: https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidtextarea--playground
