### ISSUE TITLE
DataTable with SSR: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#14107]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.32.0

### React version

18.2.0

### Description

Hi, there's a bug in DataTable/Table.tsx, when server-side rendering is used, `document` is not defined, this should probably be moved to `useLayoutEffect`, or there needs to be check on `typeof document !== 'undefined'` added, these lines:
![image](https://github.com/carbon-design-system/carbon/assets/40550942/b2a0e165-2b03-46a5-82ba-0c4028eb4817)

### Reproduction/example

https://stackblitz.com/edit/github-mc6w78?file=src%2Fpages%2Findex.tsx,src%2FExampleDataTable.tsx

### Steps to reproduce

Click on reproduction link, notice error

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/blob/0c73f612d0d71dc0c9a88ddc913eee44eb6b0ba4/packages/react/src/components/DataTable/Table.tsx#L189-L193

Probably the most straightfoward thing to try is modifying 189 to check for the existence of `document`
```jsx
if (document && document?.fonts?.status && document.fonts.status !== 'loaded') {
```

**Comment by tongyy** [comment]
maybe shorten it to `if (document?.fonts?.status !== 'loaded') {...}`
