### ISSUE TITLE
[Bug]: DatePicker allowInput prop doesn't work

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#14111]
### Package

@carbon/react

### Package version

1.32.0

### React version

v18.2

### Description

The `DatePicker` component has a prop called `allowInput` which by the description it provides should avoid the user to be able to type in the Input. The prop should restricts all input when set to false.

Reference issue: https://github.com/carbon-design-system/carbon/issues/7007
Reported on [Slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1687958132849259)
FlatPickr example: https://flatpickr.js.org/examples/ (first item)

Maybe we should switch the prop to the `DatePickerInput` and take care of that feature there instead of `DatePicker`

### Reproduction/example

https://stackblitz.com/edit/github-qqiayn?file=src%2FApp.jsx

### Steps to reproduce

Set the prop to false and try to type something.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by omkarajagunde** [comment]
Hey @tay1orjones @guidari can I take up this issue?

**Comment by guidari** [comment]
> Hey @tay1orjones @guidari can I take up this issue?

Hey @omkarajagunde For sure! Thanks
