### ISSUE TITLE
[Bug]: Changing Carbon 11 prefix from `cds` to a custom prefix does not work properly when using Module Federation

### ISSUE THREAD

**Issue by wfdcfs** [carbon-design-system/carbon#14126]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

^1.15.0

### React version

^18.2.0

### Description

Using Module Federation and lazy load code/styling when user clicks on relevant section of UI.
Want to isolate the styling from styling using in main UI (which also uses Carbon). When code is lazy loaded into the main UI, some styling over-writing is occurring. 

Using Webpack 5 to build the JS/CSS artifacts. 
``` js
...
        {
          test: /\.s[ac]ss$/i,
          use: [
            stylesHandler,
            'css-loader', 
            'postcss-loader',
            {
              loader: 'sass-loader',
              options: {
                implementation: require.resolve("sass"),
                sassOptions: {
                  includePaths: ['node_modules'],
                },
              },
            }
          ],
        },
        {
          test: /\.css$/i,
          use: [
            stylesHandler,
            'css-loader', 
            'postcss-loader'
          ],
        },
...
      isProduction && new MiniCssExtractPlugin({
        filename: 'static/css/[name].[contenthash:8].css',
        chunkFilename: 'static/css/[name].[contenthash:8].chunk.css',
        ignoreOrder: true 
      }),
```

Viewing the built React artefacts locally (e.g. http://localhost:4000) looks fine in a browser.  
The React artefacts are served to the local browser via an express server.

When I look to pull the same artefacts, and using the same express server, into the main UI (running locally as well, but on a different port), via Module Federation, then losing a lot of styling - `OverflowMenu`, `Table`, `Button`:
![image](https://github.com/carbon-design-system/carbon/assets/25774547/e391509f-233c-4271-b4d9-da30b624030f)
should look like:
![image](https://github.com/carbon-design-system/carbon/assets/25774547/752748e6-c005-4cbe-a708-60f3b9ade7ab)

Table/OverflowMenu styling loss example:
![image](https://github.com/carbon-design-system/carbon/assets/25774547/68a2bbd3-ec87-4dc2-a5e1-d28290316fc1)
should look like:
![image](https://github.com/carbon-design-system/carbon/assets/25774547/7a3cdc5e-ee5c-4773-b74f-e8b95e6312ab)

However, if I manually do a search to replace `.cds` with `.governance-cds` in the webpack built css styling files that are served to the main UI via Module Federation, then the code renders properly.  

For example, sample entry of built styling artefacts:
``` css
.cds--layout--size-xs{--cds-layout-size-height-context:var(--cds-layout-size-height-xs, 1.5rem);--cds-layout-size-height:var(--cds-layout-size-height-context)}.cds--layout-constraint--size\:default-xs{--cds-layout-size-height:var(--cds-layout-size-height-context, var(--cds-layout-size-height-xs, 1.5rem))}.
...
```
When I search and replace `.cds..` with `.governance-cds...` and serve those modified files via the express server to the main UI via module Federation  everything looks like it should look.  I can attach the styling files to the git issue if this is helpful...please let me know, or I can DM them via slack.

### Reproduction/example

https://stackblitz.com/edit/github-p3lrrc?file=src%2Findex.scss,src%2FApp.jsx

### Steps to reproduce

**This issue is not reproducible in CodeSandbox as you need to import the code in another project via Module Federation**

Setup Carbon 11 as follows to change the prefix:
``` css
// Configuration
@use '@carbon/react/scss/config' with (
    $css--default-type: true,
    $css--reset: true,
    $prefix: 'governance-cds'
  );
```
in `_vars.scss`:
``` css
$carbon-prefix: 'governance-cds'; 
```
and in JS: 
``` js
export const GOVERNANCE_NAMESPACE_PREFIX = 'governance-cds';
```
Then in entry React file, wrap code with: 
``` js
import React, { Suspense } from 'react';
import { GOVERNANCE_NAMESPACE_PREFIX } from '../../carbon-config';
import { ClassPrefix } from '@carbon/react';
import { Main } from '../Main'

const MainWrapper = () => {
  return (
    <ClassPrefix prefix={GOVERNANCE_NAMESPACE_PREFIX}>
      <Suspense fallback="Loading">
          <Main  />
      </Suspense>
    </ClassPrefix>
  );
};
export default MainWrapper;
```

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
With module federation I think each style file will be compiled in it's own execution context. Anytime you `@use` `@carbon/react` you'll need to specify the custom prefix.

```scss
@use '@carbon/react' with (
  $prefix: 'governance-cds',
);
```

Beyond this, calling `@use '@carbon/react';` in every component style file may lead to a lot of duplication across all the css files loaded in. You may want to just `@use '@carbon/react';` in a global module loaded once, and then in component style files just `@use` the individual modules you might need (spacing, colors, etc).

The best way to take advantage of the new [sass module system](https://sass-lang.com/blog/the-module-system-is-launched/) and avoid all duplication is to execute sass once against a central .scss file that includes partials to every other style file and load the output once at the root of your app.

**Comment by wfdcfs** [comment]
@tay1orjones Thank you for your inputs and the improved way to organise our styling. I have removed the individual `@use '@carbon/react';` entries and placed this in a global module loaded once. 

We compile our React JS/styling sheets once (using webpack), and then serve them on an 'as-needed' basis to whomever needs them.  When I compile the React artefacts I can see the compiled files in my 'build' folder. When I examine these, I can see a mixture of classNames that start with `.cds-` and `.goverance-cds-`.  
Doing an inspect when these React artefacts are rendered shows that the classNames have changed to `governance-cds-*` but there are styling issues with many Carbon components. 
If I do a search for `.cds-` in the React minified styling artefacts that my webpack generates and change these to `.governance-cds-`, then the React code renders correctly when loaded via Module Federation.

I will send you the CSS files to see if you can spot any issues in them.

**Comment by tay1orjones** [comment]
@wfdcfs If the css output doesn't have the configured prefix, somewhere the prefix config isn't being set. Could be in your component files or elsewhere, I'm not sure. but that sounds like the root of your issue

**Comment by tay1orjones** [comment]
With this appearing to be a configuration issue, I don't think there's anything for us to fix here but we're happy to help take a closer look if you'd like to come to our biweekly office hours, full details here: https://ibm.biz/carbon-dev-office-hours
