### ISSUE TITLE
[Bug]: tooltips render under icons

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#14137]
### Package

@carbon/styles

### Package version

?

### Description

Reported in slack https://ibm-studios.slack.com/archives/C0M053VPT/p1687360867441669

![image](https://github.com/carbon-design-system/carbon/assets/2753488/d528cf5b-bf0b-403c-94a0-a62e492a681f)

We’re having a weird layering issue where tooltips are appearing under icons that are in a data table.

Two issues in the example:
tooltip text can only displayed in one line.
icon in table header displayed over tooltip for action button

workaround is to add a z-index to `.cds--batch-action `

### Reproduction/example

https://codesandbox.io/p/sandbox/optimistic-river-sd3q2p?file=%2Fsrc%2Fapp%2Fapp.component.html%3A28%2C59

### Steps to reproduce

See codesandbox

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
We could revise the styling for the batch action bar to set a higher z-index than what it gets currently. or update the styling for the batch action bar so that it creates a new stacking context to ensure it renders above the datatable elements later in the dom

On a larger scale, this contributes to the list of reasons why we need to consider revising how we render and place tooltips, https://github.com/carbon-design-system/carbon/issues/14139

**Comment by bianca-c-melo** [comment]
<img width="935" alt="Captura de Tela 2023-07-09 às 15 27 04" src="https://github.com/carbon-design-system/carbon/assets/81665351/212d53db-97b0-4d2e-8e2b-7d12f966cf2d">


I'm facing the same issue where the popover doesn't overlay other elements. I've tried modifying the existing z-index values, but I haven't had any success. The only thing that worked was changing the overflow property of the modal body to "visible", but it's not an ideal solution. Is there any workaround to solve this problem for now?

**Comment by alisonjoseph** [comment]
Also reported via slack and this example here, where toggles are showing up above popover. Fixed with adding a z-index to the toolbar.

https://codesandbox.io/s/stupefied-marco-5xgt2d?file=/index.js
