### ISSUE TITLE
[Bug]: ComboButton broken in storybook

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/carbon#14152]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.33

### Description

the storybook story for `ComboButton` is broken

![Screenshot 2023-07-07 at 10 54 23 AM](https://github.com/carbon-design-system/carbon/assets/6370760/a0d34424-7410-4056-8923-09417e842603)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobutton--default

### Steps to reproduce

go to https://react.carbondesignsystem.com/?path=/story/components-combobutton--default

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Potential solution: https://github.com/storybookjs/storybook/discussions/21525#discussioncomment-5737578

Looks like UIShell stories are broken as well

**Comment by tay1orjones** [comment]
Resolved by https://github.com/carbon-design-system/carbon/pull/14155
