### ISSUE TITLE
[Question]: Current step in Progress Indicator is not clickable

### ISSUE THREAD

**Issue by VikaBondareva** [carbon-design-system/carbon#14154]
### Question for Carbon

Hello, 

How to make the current step clickable in ProgressIndicator ? (https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive) There is no any option to do it

```javascript
 const [currentIndex, setCurrentIndex] = useState(0);

  const handleClickMenu = (menuIndex: number) => {
    history.push(menu[menuIndex].path);
    setCurrentIndex(menuIndex);
  };

return (
    <ProgressIndicator
      vertical
      currentIndex={currentIndex}
      onChange={handleClickMenu}
    >
      {menu.map((item) => {
        return (
          <ProgressStep
            complete={item.complete}
            invalid={item.status === 'error'}
            label={item.label}
            disabled={item.disabled}
          />
        );
      })}
    </ProgressIndicator>
``` 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
After discussing as a team we feel this is acting as intended
