### ISSUE TITLE
[Feature Request]: GitLab Icon

### ISSUE THREAD

**Issue by pReya** [carbon-design-system/carbon#14184]
### The problem

There's already a good set of social media / platform icons in the Carbon icon set. GitHub is present, however it's biggest alternative GitLab is still missing. It would be very nice, if the GitLab logo could be added as well.

The GitLab logo can be found here: https://about.gitlab.com/press/

### The solution

Create a GitLab logo component.

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
Hi @pReya 👋

Could you please add an issue for this in the [brand / ui icons repo](https://github.ibm.com/brand/ui-icons/issues/new?assignees=&labels=&template=single-ui-icon-approval.md&title=%5Bui-icon%5D&_gl=1*wkvy6d*_ga*ODYwODQ2NTA1LjE2ODU1NTQzNDQ.*_ga_FYECCCS21D*MTY4OTcwNDE0MS42Ny4wLjE2ODk3MDQxNDguMC4wLjA.&_ga=2.37074272.1714073076.1689603121-860846505.1685554344)? The people who monitor that repo are the ones that help with the icon contribution process. Thank you!

**Comment by pReya** [comment]
> Hi @pReya 👋
> 
> Could you please add an issue for this in the [brand / ui icons repo](https://github.ibm.com/brand/ui-icons/issues/new?assignees=&labels=&template=single-ui-icon-approval.md&title=%5Bui-icon%5D&_gl=1*wkvy6d*_ga*ODYwODQ2NTA1LjE2ODU1NTQzNDQ.*_ga_FYECCCS21D*MTY4OTcwNDE0MS42Ny4wLjE2ODk3MDQxNDguMC4wLjA.&_ga=2.37074272.1714073076.1689603121-860846505.1685554344)? The people who monitor that repo are the ones that help with the icon contribution process. Thank you!

As this is an internal IBM GitHub instance, I'm afraid I can't.

**Comment by pReya** [comment]
Thank you! Much appreciated!

**Comment by pReya** [comment]
@sstrubberg @conradennis Is the icon available in a new release, yet? Wasn't able to find it via https://carbondesignsystem.com/guidelines/icons/library/

**Comment by laurenmrice** [comment]
@pReya Looks like it has been added to code and the Figma library. It will be added to the website soon as well.
<img width="852" alt="Screenshot 2023-08-28 at 11 17 47 AM" src="https://github.com/carbon-design-system/carbon/assets/43969356/1d8fc1b6-4eb5-428e-998d-c15c230019e0">
