### ISSUE TITLE
[Bug]: Popover with interactive trigger causes tooltip layout issue

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon#14195]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

Latest

### Description

Hello! :wave:

I am looking to build something very similar to the settings menu found on the [Carbon disclosure pattern guidance page](https://carbondesignsystem.com/patterns/disclosures-pattern/#settings-and-filter-menus). This is for the row settings menu that we have for the Datagrid in Carbon for IBM Products which can be [seen here](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--empty-state). Our current implementation uses the `ToggleTip`. We received some design feedback that it should actually use the Popover so that there is no caret and it is placed directly below the trigger/settings gear icon.

The examples for Popover in the react storybook do not show an interactive element for the Popover trigger, only an icon. After attempting to include an `IconButton` as the `Popover` trigger, I noticed that the placement of the tooltip for the `IconButton` is not quite right.

```jsx
<Popover>
  <IconButton {...props}>
  <PopoverContent>
    content here
  </PopoverContent>
</Popover>
```
<img width="305" alt="image" src="https://github.com/carbon-design-system/carbon/assets/10215203/fe3fccd1-9df3-485e-bbf0-c3628274c52c">

I was wondering if there might be an example of Popover with an interactive trigger so that it can be opened via keyboard. If not, is there a way to utilize IconButton as the Popover trigger or potentially even the possibility of removing the caret via a prop for the ToggleTip.

Thanks so much!

### Reproduction/example

https://stackblitz.com/edit/github-ndeemc-6aqjyv

### Steps to reproduce

Include an `IconButton` as the Popover trigger element so that it can be opened via keyboard.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Carbon for IBM Products

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@matthewgallo Hey we actually have that as a variant of `Popover` with the `isTabTip` prop(https://react.carbondesignsystem.com/?path=/story/components-popover--tab-tip), but this is just using a plain button with no tooltip. 

Here is an example using `IconButton`: https://stackblitz.com/edit/github-ndeemc-wjns93?file=src%2FApp.jsx,src%2Findex.scss

Looks like there might be some styling issues with the icon button tooltip causing some alignment issues

**Comment by janhassel** [comment]
ref https://github.com/carbon-design-system/carbon/discussions/13836

**Comment by matthewgallo** [comment]
😱 Sorry I don't know how I missed the `Tab tip` story or the `isTabTip` prop, thank you! @jan I am also seeing some similar spacing issues with the placement of the icon button tooltip. It is working now with the `isTabTip` prop however you can see below the spacing still appears somewhat off.
<img width="261" alt="image" src="https://github.com/carbon-design-system/carbon/assets/10215203/8bd61eac-5695-4686-803c-213876b2196b">


@tw15egan so it sounds like the removal of the caret cascading down to the `IconButton` is a bug, is that correct?

**Comment by tw15egan** [comment]
Just put up a PR that scopes the styles a bit better so that the positioning styles don't leak down to `IconButton`, hopefully that fixes this issue
