### ISSUE TITLE
[Bug]: toggletip type token bug

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#14190]
### Type token bug:
The Toggletip component should be using the `$body-01 `type token. Right now its using the $body-02 type token. 

<img width="608" alt="Frame 3" src="https://github.com/carbon-design-system/carbon/assets/43969356/77701ef2-3a69-4420-ae1d-6948c61f9b8d">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
@laurenmrice Seems like the `body-01` is being set on `toggletip-content`, but the `p` tag inside has a global type style set of `body-02`. We can do something like `.#{$prefix}--toggletip-content p` to fix this scenario, but there may still be edgecases where the type styles don't cascade down

**Comment by laurenmrice** [comment]
Ok, that is fine lets go with that, I just want us to be showing what we recommend by default.
