### ISSUE TITLE
Bug: button text alignment

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#142]
![image](https://cloud.githubusercontent.com/assets/11670886/26594241/87c7f4f2-452c-11e7-89af-12c87653d476.png)

Text alignment in the button is off. Chris says to fix it in `.bx--btn` change/add `line height: 0`

**Comment by tw15egan** [comment]
Looking at this now, but this seems to only affect small buttons without icons? If I add a `line-height: 0` to the buttons, they are even more misaligned.

Before: **Equal distance from icon, 30px**
![screen shot 2017-05-30 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/11928039/26598385/ad0ac7ea-453a-11e7-8791-56135b25bf83.png)

![screen shot 2017-05-30 at 1 14 22 pm](https://cloud.githubusercontent.com/assets/11928039/26598396/ba6900fa-453a-11e7-9836-375ed12bd992.png)

After: **Different distance from icon, 25px on top 31px on bottom**
![screen shot 2017-05-30 at 1 16 10 pm](https://cloud.githubusercontent.com/assets/11928039/26598406/c8ef6d44-453a-11e7-8714-a72fe26ce4d2.png)
![screen shot 2017-05-30 at 1 17 09 pm](https://cloud.githubusercontent.com/assets/11928039/26598415/cdf05d6c-453a-11e7-985d-775a36a29182.png)

![screen shot 2017-05-30 at 1 18 46 pm](https://cloud.githubusercontent.com/assets/11928039/26598425/d3253e88-453a-11e7-9887-9158a1922567.png)

**Comment by tw15egan** [comment]
Found a fix by simply setting the `line-height` to `16px`. Will be closed via #96
