### ISSUE TITLE
[a11y]: Modal [all variants] - identifies visually hidden controls

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#14203]
### Package

@carbon/react

### Browser

Safari

### Package version

1.32.0

### React version

18.2

### Description

VO is reading "Focus sentinel" when arrow down after the "Add" button in all `Modal` variants

This [PR](https://github.com/carbon-design-system/carbon/pull/14156) fixed `ComposedModal`. It might be good taking a look.

### Reproduction/example

https://react.carbondesignsystem.com/iframe.html?args=&id=components-modal--with-state-manager&viewMode=story

### Steps to reproduce

Arrow down the `Modal` with the VO active

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Close via https://github.com/carbon-design-system/carbon/pull/15868
