### ISSUE TITLE
Decide focus style for tri-state in DataTable

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1421]
As noted in @lovemecomputer's review here: https://github.com/IBM/carbon-components-react/pull/1535#pullrequestreview-173513207 we need a clearer focus indicator for our tri-state sort in Data Table. This issue is for deciding on the visual behavior of this state and implementing this as a quick CSS change.

**Comment by joshblack** [comment]
cc @IBM/carbon-designers if you have a sec!

**Comment by lovemecomputer** [comment]
this is an example of a current issue:

![sorting01](https://user-images.githubusercontent.com/3846271/48279328-de4f8680-e415-11e8-8dd4-69ca0dffd7e8.gif)
in the gif, note that when the header is clicked to go from **Default > Ascending > Descending > Default**, when it returns to **Default** sort state, the `:focus` remains, **and will not disappear until the user clicks elsewhere.** 

so, ideally the "returned to default sort" focus state will look sensible to match the **Default** sort state, and will also still communicate that the element has keyboard focus.

**Comment by aagonzales** [comment]
Can we talk about this in person? Its a little hard to grasp what's going on in the gif and what exactly it is we need changes on.

**Comment by chrisconnors-ibm** [comment]
I would really like to constrain the set of components that display focus state when clicked, this is great example where it probably shouldn't.

**Comment by joshblack** [comment]
@chrisconnors-ibm I believe we have to display an outline for focus states for accessibility, unless you're speaking about something else? Let me know!

**Comment by chrisconnors-ibm** [comment]
yes. in this very edit field for example, if I click on the "Write" or "Preview" tabs, there is no focus ring. ditto all of the styling buttons.

if I _Tab_ between the Write and Preview tabs, they do get the focus ring.

Not all controls should display the focus ring on click. I would argue most of them.

**Comment by joshblack** [comment]
Totally! GitHub chooses to use the default focus styles which means browsers like Chrome will not show them if the focus is initiated by a click. However, if we override the focus styles then they will always be applied.

Eventually, this will be a property called `:focus-visible` https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible but it doesn't have browser support yet 😞

**Comment by chrisconnors-ibm** [comment]
> I believe we have to display an outline for focus states for accessibility
I bet the rule means "when the control has focus" ie when the user tabbed to it.

Clicking (as in the example) doesn't change focus.

**Comment by paschalidi** [comment]
@joshblack I would love to open a PR for this issue. Let me know what you people have decided! :D

**Comment by joshblack** [comment]
Hi @paschalidi! 👋 I believe this was updated in our v10 release to make things more clear: https://www.carbondesignsystem.com/components/data-table/code

Closing this as a result!
