### ISSUE TITLE
[Developer Experience]: 2Gb transfer for repo clone is out of proportion

### ISSUE THREAD

**Issue by dbrugger** [carbon-design-system/carbon#14235]
### The problem

As a developer who uses the library I sometimes stumble on issues, that I typically workaround with `patch-package` but also like to submit PRs for it. Even if it's just a small fix, using the GitHub editor alone is not sufficient because I have to run the `format` script on it. So I have to clone the repo (fork), but this is a 2Gb transfer, which is kind of out of proportion.

I am on gigabit fiber myself, and am still annoyed by this. I can imagine that this is a turn off for developers with less bandwidth, and can impact attracting new potential contributors.

### The solution

Somehow get rid of the yarn cache.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Yeah I agree it would be nice for these types of use cases if the repo size could be smaller. Most contributors clone and only pay this price once, issuing further updates from their local clones. If we ever want to take advantage of codespaces or similar virtual coding environments this might be of more concern, I'm not sure.

We're not way out of bounds though. [Github recommends](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits) under 1GB, we're at 2GB, and the max allowed is 5GB. 

> Somehow get rid of the yarn cache.

From our testing this is only about ~500mb and ensures dependency integrity locally and in CI. Beyond this it would be interesting to use [`github/git-sizer`](https://github.com/github/git-sizer) to try and see where the problems are contributing to the size. My guess is it's just raw history as the project has been around for quite some time.

**Comment by sstrubberg** [comment]
@dbrugger Thanks for bringing this to our attention. Unfortunately, it isn't a high priority for us at the moment. We'd welcome any research or PR that might help though. Closing for now.
