### ISSUE TITLE
Create a NextJS example to reside in the NextJS repository

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14245]
It would be beneficial for our users and maintainers if there was an easy way to spin up a NextJS app with the latest Carbon deps included and set up.

If we create an example and submit it to the [examples folder in the next.js repo](https://github.com/vercel/next.js/tree/canary/examples) under the name `carbon-design-system`

This will enable users to use a command like this to spin up a NextJS project using `@carbon/react`:

```sh
npx create-next-app --example carbon-design-system carbon-design-system-app
```

We may want to reuse some of the assets, layout, etc from the tutorial if/after it's updated to NextJS instead of `react-scripts`, https://github.com/carbon-design-system/carbon-tutorial/issues/10994

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : Is this request still open ? Can I work on this issue

**Comment by tay1orjones** [comment]
Hey, I so appreciate your willingness to take this on! We just spoke about this as a team earlier today and right now we're actually going to place this idea on hold. There's lots of additional follow-on considerations that we're not able to handle right now.

**Comment by sstrubberg** [comment]
Hey @Shankar-CodeJunkie, i'm curious, what did you have in mind when the user ran the npx command to create a next app with Carbon bundled in? As in, what would the landing page look like?

**Comment by Shankar-CodeJunkie** [comment]
Hi @sstrubberg !  Apologies for late response and   we can have the same landing page like what we had on Create React Template. We can also point to something different as well, may be we can come up with something very new as well.  


![](https://user-images.githubusercontent.com/56068832/210359245-a464b7b2-d057-4b9c-864d-d6951aac07cb.png)

**Comment by sstrubberg** [comment]
> Hi @sstrubberg ! Apologies for late response . We can have the same landing page like what we had on Create React Template. We can also point to something different as well, may be we can come up with something very new as well.
> 
> ![](https://user-images.githubusercontent.com/56068832/210359245-a464b7b2-d057-4b9c-864d-d6951aac07cb.png)

This is great @Shankar-CodeJunkie. Let's use the same template you used for the CRA template as a starting point. Thank you for contributing to not only Carbon, but to NextJs as well! 🎉

**Comment by Shankar-CodeJunkie** [comment]
@sstrubberg !  Thanks for your response.   I will start working on this item, and keep you informed on the progress. Can you please assign this story to me . Thanks

**Comment by Shankar-CodeJunkie** [comment]
I'm working for this issue, with the goal of completing it within the next two weeks. However, the holiday season has caused it to take a backseat for the time being.

**Comment by Shankar-CodeJunkie** [comment]
Hi @sstrubberg @tay1orjones 

I've completed creating the nextjs-starter using javascript and mainly re-used code from the [tutorial repository ](https://github.com/carbon-design-system/carbon-tutorial-nextjs/tree/v11-next-step-5), also added a theme switcher for user to explore themes provided by Carbon.  We used the very same template for create-next-app as well. 

`npx create-next-app@latest project-name --example https://github.com/Shankar-CodeJunkie/carbon-design-system-nextjs-starter`

Can I myself upload the repository under the name [carbon-design-system] on [vercel repo examples](https://github.com/vercel/next.js/tree/canary/examples)

I'am also working to create a typescript starter under the name [carbon-design-system-with-typescript]

<img width="2053" alt="image" src="https://github.com/carbon-design-system/carbon/assets/56068832/8e2e1ffd-ae21-4fc4-b32e-1e6f1eb6e1c4">

**Comment by Shankar-CodeJunkie** [comment]
Hi @sstrubberg @tay1orjones 

I've also created a starter for typescript as well.  You can find the repositories here 

- https://github.com/Shankar-CodeJunkie/carbon-design-system-nextjs-typescript-starter
- https://github.com/Shankar-CodeJunkie/carbon-design-system-nextjs-starter

We can upload these two separate starter projects under the names [carbon-design-system] and [carbon-design-system-with-typescript] in vercel example directory.

**Comment by tay1orjones** [comment]
@Shankar-CodeJunkie sounds good to me, thank you!

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : Can I upload those templates using my ID and if so , when can I upload it ?

**Comment by tay1orjones** [comment]
@Shankar-CodeJunkie Yes your ID is fine. You can add them to the vercel example directory/repo right now. Post the PR link to this issue and when it's merged we can close this issue. Thank you again

**Comment by Shankar-CodeJunkie** [comment]
Thanks @tay1orjones 

I've created a pull request [60394](https://github.com/vercel/next.js/pull/60394) in the nextjs repository and awaiting for their review comments.  I will keep you informed in the updates of that pull request. 

Thank you
