### ISSUE TITLE
[Bug]: HeaderMenuButton is not show when the width is more than 1055px

### ISSUE THREAD

**Issue by granite83** [carbon-design-system/carbon#14279]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.33.2

### React version

18.2.0

### Description

i am new guy to the carbon design system . when i add the HeaderMenuButton to the Header element, the HeaderMenuButton is not shown when the width is more than 1055px in my pc. i try the same the code in stackblitz, if i open the result page in a new tab(the page become larger) ,the HeaderMenuButton is hidden.i don`t know it is a bug or is my mistake, help me please ,thanks very much.

### Reproduction/example

https://stackblitz.com/edit/github-vvnkhg?file=src%2FApp.jsx,src%2Fmain.jsx

### Steps to reproduce

import { Header, HeaderMenuButton } from '@carbon/react';
import React from 'react';

export default function App() {
  return (
    <div>
      <Header>
        <HeaderMenuButton></HeaderMenuButton>
      </Header>
    </div>
  );
}

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

browser

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@granite83 that is working as expected. WHen there is enough screen space, the items inside the header menu button are displayed in the Header itself. Compare your code to this story, that should help: https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation

**Comment by granite83** [comment]
@tw15egan thank you very much for your help , Through this question, I further understand the design concept of the carbon design system !
