### ISSUE TITLE
[DatePicker]: Default date is not up to date

### ISSUE THREAD

**Issue by Julie-Saurat-Sia** [carbon-design-system/carbon#14281]
### Package

@carbon/react, carbon-components-react

### Browser

Test in Chrome

### Package version

"carbon-components": "^10.45.0", "carbon-components-react": "^7.45.0"

### React version

v16.13.1

### Description

I am using the React Carbon component Date Picker in single type on my web application for a client. 
The default date of the Date Picker is not up to date if the application stay open in the browser (test in Chrome) for more than 1 day 

To reinitialize it, we need to close the browser tab and reopen it 
 A simple refresh of the page is not sufficient, we have to **close the browser and re-open**

### Steps to reproduce

To reproduce it in real we could create a new CodeSandbox today, put a Date Picker in single type and leave it, then tomorrow lok at the default date of this component and we will notice that the default date will be the day before 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@Julie-Saurat-Sia The default date is what's given to `value`. If this becomes stale, you'll need to pass in a new value for `value` and/or regenerate the component tree by placing a `key` on the component and changing the value of it when you'd like to instruct React to throw away and rebuild the component tree.

**Comment by tay1orjones** [comment]
Let us know if the above works, if not we can reopen. Thanks!

**Comment by Julie-Saurat-Sia** [comment]
@tay1orjones Thanks for your answer.
But I'm not talking about the input `value` but about the default date in blue in the calendar when the user click on the Date Picker with calendar - sorry for the lack of clearness above :) 
Here is a screenshot of what happened: 
![image](https://github.com/carbon-design-system/carbon/assets/140177393/32f6da4b-3b94-4085-9852-fe42ca3c7bd9)
