### ISSUE TITLE
[Bug]: danger--ghost icon button has incorrect alignment

### ISSUE THREAD

**Issue by annatomka** [carbon-design-system/carbon#14295]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.34.0

### React version

17.0.1

### Description

Using the `Button` component with the `kind="danger--ghost"` and `hasIconOnly={true}` properties results in incorrect icon alignment. I expected the icon to be centered but in reality, the icon is aligned left.

Expected alignment:
<img width="312" alt="image" src="https://github.com/carbon-design-system/carbon/assets/2573711/20833666-47fe-4ffd-9f8b-833f6a1a94e4">

Actual alignment:
<img width="330" alt="image" src="https://github.com/carbon-design-system/carbon/assets/2573711/ed5de111-41e1-4e92-bed7-e355df7a88d9">

### Reproduction/example

https://stackblitz.com/edit/github-tjccdz?file=src%2FApp.jsx

### Steps to reproduce

Open the storybook Button page: https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=hasIconOnly:true;kind:danger--ghost

Change the following controls:
```
hasIconOnly = true
kind = danger--ghost
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@annatomka Sorry, but `danger` is not a supported option for icon only buttons. This includes `IconButton` and `<Button hasIconOnly/>`. I know this is confusing because previous documentation stated otherwise, but this is the current state. I've opened an issue to address this, #14300
