### ISSUE TITLE
UIShell: Header menu does not close if I click on HeaderName. App routing is implemened via BrowserRouter.

### ISSUE THREAD

**Issue by skuratiov** [carbon-design-system/carbon#14311]
## Summary
Seems like an underlying issue with the handleOnBlur inside HeaderMenu not setting state properly when using the BrowserRouter. Might be best to create an issue on the repo with a link to the reproduction so someone can take a deeper look.

Here is a demo:
https://stackblitz.com/edit/github-phe11d?file=src%2FComponents%2FAppHeader%2FAppHeader.jsx,src%2FApp.jsx

To reproduce this error: Click on any of the Menu 1 (2) and while it opened, click to the HeaderName. Routing occurs, but menu stays opened: 
![image](https://github.com/carbon-design-system/carbon-website/assets/140519543/182852dd-0bbf-4980-9cfd-211d29d49c33)

## Relevant information

[github-phe11d(2).zip](https://github.com/carbon-design-system/carbon-website/files/12163056/github-phe11d.2.zip)

**Comment by skuratiov** [comment]
I use Link from from from '@carbon/react'
, instead of from 'react-router-dom'; - It close menus as expected but no routing occurs.

**Comment by tay1orjones** [comment]
It looks like `handleOnBlur` doesn't set the internal state to false 

https://github.com/carbon-design-system/carbon/blob/e33e8d3c886c27ae7ad3270465a5c2e386e38142/packages/react/src/components/UIShell/HeaderMenu.js#L118-L139

Based on this, I think it relies on the HeaderMenu being re-rendered on navigation. This could be accomplished on your end by placing a `key` on the HeaderMenu component(s) and changing the value when navigation happens. 

I'm not sure how we could improve the existing code to check for if the HeaderName is clicked to close them. These components could `useContext` to communicate that state to one another but I'm not sure if that's the best solution given the amount of different ways these components are used and composed.

**Comment by tw15egan** [comment]
@tay1orjones looks like one issue with this is that we are not allowing users to set any `onClick` or `onBlur` handlers. One thing we could do is refactor this to use the `composeEventHandlers` internal tool to allow user event handlers to be passed down to the menu

**Comment by tw15egan** [comment]
Here is an example of the idea @tay1orjones suggested: https://stackblitz.com/edit/github-phe11d-jjv3xh?file=src%2FComponents%2FAppHeader%2FAppHeader.jsx

**Comment by skuratiov** [comment]
> Here is an example of the idea @tay1orjones suggested: https://stackblitz.com/edit/github-phe11d-jjv3xh?file=src%2FComponents%2FAppHeader%2FAppHeader.jsx

Checked. Now routing happens but menu still does not disappear.

**Comment by tay1orjones** [comment]
@skuratiov If you reuse the `handleClick` on the `HeaderMenuItem`s `onClick` it seems to work correctly

https://stackblitz.com/edit/github-phe11d-yv7ukc?file=src%2FComponents%2FAppHeader%2FAppHeader.jsx

**Comment by skuratiov** [comment]
@tay1orjones Hi Taylor, now it seems working ok. Please let me know if you eventually integrate it to the fwk code.
