### ISSUE TITLE
[Question]: it is not working in scss file "@use '@carbon/react';"

### ISSUE THREAD

**Issue by LalitAssetOne** [carbon-design-system/carbon#14322]
### Question for Carbon

not working while i am importing in index.scss file showing error like : "SassError: Can't find stylesheet to import.
  ╷
1 │ @use '@carbon/react';
  │ ^^^^^^^^^^^^^^^^^^^^"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Can you please fill out the issue template along with a reproduction so we can better help debug whats going on? Closing until more information is provided.
