### ISSUE TITLE
[Feature Request]: Make it possible to override the 'Cancel' button label in batch action toolbar

### ISSUE THREAD

**Issue by huygur** [carbon-design-system/carbon#14349]
### The problem

Batch operation toolbar has a Cancel button which closes the toolbar. But it is [hardcoded](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/TableBatchActions.js#L75) so we are not able to modify the button label in our project. 
In our use case, we have an action button called 'Cancel' which is the same as this label so its confusing for the users. We would like the opportunity to change this label to 'Discard'.

### The solution

Would be nice to have a cancelButtonLabel prop which gives the chance to override this button label

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Please see this discussion on how to translate this text properly: https://github.com/carbon-design-system/carbon/discussions/14340#discussioncomment-6576295
