### ISSUE TITLE
Dropdown Multi-select component wrong size on the website. 

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#1434]
https://www.carbondesignsystem.com/components/dropdown/code
![2018-11-13 16 53 48](https://user-images.githubusercontent.com/6569324/48448511-e6385f00-e764-11e8-99eb-823ea5725d65.gif)

The example of a multi select dropdown on the public carbon website is the wrong width, the dropdown overlaps the placeholder label. 

Google Chrome Version 70.0.3538.102

**Comment by asudoh** [comment]
Seems that the issue has been solved on our website.
