### ISSUE TITLE
DropdownV2 able to highlight 2 dropdown items at the same time

### ISSUE THREAD

**Issue by lewishadden** [carbon-design-system/carbon#1437]
## Detailed description

> Describe in detail the issue you're having.
When you hover over one of the dropdown items, it gets highlighted
<img width="336" alt="screen shot 2018-11-14 at 14 16 51" src="https://user-images.githubusercontent.com/17049577/48488131-f8bfa080-e817-11e8-9414-c6ed7009c563.png">
If you then scroll the dropdown so that the mouse hovers a different dropdown item, they both become highlighted at the same time
<img width="331" alt="screen shot 2018-11-14 at 14 18 26" src="https://user-images.githubusercontent.com/17049577/48488230-2d335c80-e818-11e8-9d9f-02d7c63d2257.png">

> Is this issue related to a specific component?
DropdownV2
> What did you expect to happen? What happened instead? What would you like to see changed?
Only the item which is currently being hovered should be highlighted.
> What browser are you working in?
Firefox & Chrome
> What version of the Carbon Design System are you using?
 "carbon-components": "^9.3.0",
 "carbon-components-react": "^6.13.2",
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Client project being released in 5 weeks.

> Steps to reproduce the issue

1. Navigate to [http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel](url)
2. Expand the dropdown
3. Hover the mouse over Option 2
4. Scroll the mouse down so that the mouse is hovering over Option 3

**Comment by alisonjoseph** [comment]
What browser are you seeing this in? I am unable to reproduce.

**Comment by asudoh** [comment]
Hi @lewishadden are you still seeing the issue...? Thanks!
