### ISSUE TITLE
[Question]: How can I set the $base-font-size property with theming?

### ISSUE THREAD

**Issue by fegyi001** [carbon-design-system/carbon#14392]
### Question for Carbon

I'm trying to fine-tune carbon styles in my (angular) app. However, I'm unable to override the default 16px font size. I would like to set it to 14px.

When I try to use `@carbon/layout` and modify it like so (as mentioned in the docs):

```scss
@use 'carbon-components/scss/themes';
@use 'carbon-components/scss/theme' with (
  $fallback: themes.$g10,
  $theme: (),
);

@use '@carbon/layout' with (
  $base-font-size: 14px
);
```

I get the following error: `This module was already loaded, so it can't be configured using "with"`.

<img width="1068" alt="image" src="https://github.com/carbon-design-system/carbon/assets/4125222/d61688fc-6e45-40b8-91b7-00b73a66080f">

Is it possible to set the theme so that it accepts my overridden value?

Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Can you do `@use '@carbon/layout/scss/convert' with ($base-font-size: 14px);` before the `theme` import? Any Stackblitz example would also help debugging

**Comment by Yaren-IT** [comment]
Based on the code snippet you shared, it appears that you're on the right path. However, since a previous @use directive has already imported @carbon/layout, there's a conflict that needs to be addressed. To tackle this, you should adjust the order of your code like this:
```sass
// Import the @carbon/layout directive before @carbon/themes
@use '@carbon/layout' with (
  $base-font-size: 14px
);

@use 'carbon-components/scss/themes';
@use 'carbon-components/scss/theme' with (
  $fallback: themes.$g10,
  $theme: (),
);

// Continue with your previous @use directives and other styling rules...

```

**Comment by tay1orjones** [comment]
Additionally, the layout module can be accessed through `carbon-components` itself which can help with these config issues.

```
@use 'carbon-components/scss/layout' with (
  $base-font-size: 14px
);
@use 'carbon-components/scss/themes';
@use 'carbon-components/scss/theme' with (
  $fallback: themes.$g10,
  $theme: (),
);
```

These options should resolve the issue, please open a new issue if not. Thank you
