### ISSUE TITLE
Update icons in experimental components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1441]
After going through an audit of our existing icon usage, we noticed some of the following components that might need their icons updated with our handlebars helpers:

- Button
  - AddSolid
- Dropdown
  - Caret should be chevron
- Notification
  - Pulling in 16s
  - Close 10x10
  - InformationSolid
  - ErrorFilled - SOlid?
  - CHeckmarkFilled - Solid?
  - WarningAlt 16
- Number Input
- Overflow Menu
  - Put glyph (3x15) on 16x16 for Overflow Menu
- Select
  - Chevron, not caret
- Structured LIst check
- Text Input
  - Error icon
- Selectable Tile
  - Check
  - Chevron
- Tooltip
  - information
- Code Snippet
  - Copy
- Modal
  - Close
- File Uploader
  - Close
- Search
  - Search
- Pagination
  - Chevron
- Time Picker
  - Chevron
- In general, we should make sure these icons are updated:
  - Close

**Comment by joshblack** [comment]
cc @chrisconnors-ibm if you have the chance, would be great to direct link the icon for the developer to use from our demo site.

**Comment by chrisconnors-ibm** [comment]
**Experimental Component Inventory**

- [x] **Accordion:** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--down
- [x] **Button:** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fadd--solid
- [x] (Not yet done?) **Code Snippet**: https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcopy
- [x] **Content Switcher:** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fadd--solid
- [ ] **Date Picker**
  - [ ] **Single:** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcalendar
  - [ ] **Range:** 
    - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcalendar
    - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--left
    - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--right
    - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--up
    - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--down
- [ ] **Data Table**:
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fdownload
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fedit
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fsettings
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--right
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--down
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--sort
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--sort--up
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--sort--down
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fdelete
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fsearch
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Ffilter
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Foverflow-menu--vertical
- [x] **Dropdown:** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--down
- [ ] **Form**: https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--down
- [x] **modal**: https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fclose
- [x] **Notification:**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Finformation--filled
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Ferror--filled
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcheckmark--filled
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fwarning--filled
- [x] **Number Input**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--up
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--down
- [ ] **Overflow Menu**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Foverflow-menu--vertical
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Foverflow-menu--horizontal
- [x] **pagination**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--up
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--left
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--right
- [x] **search** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fsearch
- [x] **select**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcaret--down
- [x] **structured list**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcheckmark--filled
- [ ] **text input**
  - [ ] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Ferror--filled
- [x] **tile**
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcheckmark--filled
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--down
  - [x] https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fchevron--up
- [x] **tooltip** https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Finformation--filled

**Comment by chrisconnors-ibm** [comment]
notes: many of these items displace bespoke-sized glyphs; we'll need to position the new assets to accomodate the 16x16 art board size. (if we have to rebuild glyphs using the new IDL2 style we can do that, but would rather have fewer odd sized assets) _work with the original spec designers if you need help/verification on asset placements_

@aagonzales @designertyler @laurenmrice @jeanservaas @shixiedesign
