### ISSUE TITLE
[Bug]: Unable to click SideNav inside HeaderContainer

### ISSUE THREAD

**Issue by RMCampos** [carbon-design-system/carbon#14414]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.35.0

### React version

v18.2.0

### Description

The issue also happen on storybook: https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-side-nav

Take a look the reproduction/example bellow!

PS: Sorry for the horrible example. But you can confirm this issue also on the storybook. 

### Reproduction/example

https://stackblitz.com/edit/stackblitz-starters-cfsg13?file=src%2FApp.tsx

### Steps to reproduce

Try to click a `SideNavLink`.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Ced-Sharp** [comment]
While this gets fixed, for those who would like a dirty temporary fix, you can use a media query to update the "expanded" attribute, for example:

```tsx
const [sideNavOpen, setSideNavOpen] = useState(false);
const toggleSidenav = () => setSideNavOpen(!sideNavOpen);

useEffect(() => {
  const media = matchMedia('(min-width: 1056px)');
  setSideNavOpen(media.matches);
  media.addEventListener('change', ev => setSideNavOpen(media.matches));
}, []);

return <>
  <SideNav aria-label="Navigation" expanded={sideNavOpen} isPersistent={true}>
    ...
  </SideNav>
<>;
```
