### ISSUE TITLE
[Feature Request]: Need a way to clear the selection of rows upon performing Batch action.

### ISSUE THREAD

**Issue by k02pradeep** [carbon-design-system/carbon#14412]
### The problem

Need a way to clear the selection of rows upon performing Batch action.

### The solution

Datatable should expose ways to clear the selection programmatically from the parent component. 

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@k02pradeep The default functionality for `onCancel` deselects all rows already, see here

https://github.com/carbon-design-system/carbon/blame/fa9c18c6bc77f27096e1b9fc4a5f1ed4c8573f0f/packages/react/src/components/DataTable/DataTable.tsx#L787-L798

Does this not work for you? If you're implementing your own onCancel functionality, there is an option to call the `selectAll()` function returned from the render as [described here for programatic selection](https://react.carbondesignsystem.com/?path=/docs/components-datatable-batch-actions--overview#programmatic-selection). This should toggle the selection of all rows.
