### ISSUE TITLE
[Bug]: Tabs content should have $layer-01 background

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#14443]
### Package

@carbon/styles

### Package version

1.35.0

### Description

I noticed tabs being used with tab content having no background, which makes the $layer-01 background of selected tab not really work as selected when there are 2 tabs. I believe the original design intent is the selected tab's content has $layer-01 background so it matches that of the tab above it, creating a visual connection: 

<img width="1201" alt="image" src="https://github.com/carbon-design-system/carbon/assets/15144993/9427fa78-3d9b-44ae-a02d-38ada217319a">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-tabs--contained

### Steps to reproduce

Go to https://react.carbondesignsystem.com/?path=/story/components-tabs--contained

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Carbon for Salesforce

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@carbon-design-system/design could you confirm? It looks like this is just contained tabs.

There is no background style applied to `.cds--tab-content`, so this doesn't respond to being wrapped in a `Layer` component.

**Comment by shixiedesign** [comment]
Sorry I don't seem to be getting email notification on the pings here except when issue closes. 

So @kingtraceyj the layers aren't working because of what @tay1orjones said, I suppose:
> There is no background style applied to .cds--tab-content, so this doesn't respond to being wrapped in a Layer component.

There's `.cds-tabs-content` div as part of the Tabs component. This is good because users are expected to put content inside it. But because there's no background, contained tabs will always take the background of the Page, not the background of the selected tab which is a layer. So it's like an extra step needed to use an out-of-the-box component correctly, and from my observation it's a common mistake. That's why I think ideally we add that background to Contained tabs.

**Comment by tay1orjones** [comment]
> from my observation it's a common mistake to put contained tabs on non-matching background

It's hard to know how pervasive this is. If we add the background, I think adding it behind a feature flag would be needed so that users don't pull a new minor and see visual changes in their app that they didn't have before. We can make it the default behavior in the next major.

**Comment by kingtraceyj** [comment]
Updated documentation to reflect tab panel layering model 

Tab panel is updated in[ storybook](https://react.carbondesignsystem.com/?path=/story/components-tabs--contained)
