### ISSUE TITLE
[Question]: Can we remove the screen jump when modals are shown?

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#14442]
### Question for Carbon

When displaying a modal, the scroll bar on `<body>` is hidden by the following CSS:

```css
.bx--body--with-modal-open {
 overflow: hidden;
}
```

Since this affects the width of the browser window (at least on Windows), it causes either:

* Paragraph content to reflow.
* Columns in tables etc. to shift to the left.

Modal.js and ComposedModal.js both toggle this CSS class. Or at least, they both have code to toggle the class; there seems to be a bug in Modal.js where that code doesn't run correctly.

You can see it clearly from the "Launch modal" button on https://react.carbondesignsystem.com/?path=/docs/components-composedmodal--overview, especially if you add content to the `<body>` that will reflow on browser width change.

This CSS was obviously added intentionally... it traces back to https://github.com/carbon-design-system/carbon/commit/15d5fc88dad77c5b43fc8d8e208744703c9a7bda and is still there today (https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/modal/_modal.scss#L436).

However, it's unclear why it was added and whether or not it's still needed.

Given the negative side effects of hiding the scrollbar, do we need that CSS?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@wkeese This was added in https://github.com/carbon-design-system/carbon/pull/3237 to fix the defect of content behind the modal being scrollable.

Is there a reliable way to get the scrollbar width on a given browser and/or OS? If so we could apply a margin-right of that value to avoid the reflow. You could do this in your application with custom styles for now. It may be complicated to support platforms that allow hiding the scrollbars, such as MacOS.

**Comment by wkeese** [comment]
I think this is one of those problems that can't be solved just by CSS.   You can do this in Javascript:

```
const scrollBarWidth = element.offsetWidth - element.clientWidth;
```

Note also that the scrollbar might be on the left side instead of the right side.  Ideally, you would use a selector the `:dir(rtl)` selector but [that's not widely supported yet](https://caniuse.com/css-dir-pseudo) so the best you could do is


```
body[dir="rtl"]
```

**Comment by tay1orjones** [comment]
Right, but I don't know if there's a way to detect if the user agent is including the scrollbar as part of the clientWidth or not. IIRC on mac it only does if the setting for "always show scrollbars" is selected in the system settings.

If there's not a reliable way to detect this, we may not be able to add a solution that works for all platforms.
