### ISSUE TITLE
No correct focus after Modal is opened

### ISSUE THREAD

**Issue by wangweiu** [carbon-design-system/carbon#14452]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.59.10

### React version

17.0.2

### Description

Windows 10 Enterprise
Chrome 116.0.5845.97

Open https://v7-react.carbondesignsystem.com/iframe.html?id=components-modal--with-state-manager&viewMode=story

Click "Launch modal". The Modal is opened. but no focus on the Modal. You need to tab several times to get focus on Modal.

I only see this on Windows+Chrome.  My Mac+Chrome is fine.

### Reproduction/example

https://v7-react.carbondesignsystem.com/iframe.html?id=components-modal--with-state-manager&viewMode=story

### Steps to reproduce

Windows 10 Enterprise
Chrome 116.0.5845.97

Open https://v7-react.carbondesignsystem.com/iframe.html?id=components-modal--with-state-manager&viewMode=story

Click "Launch modal". The Modal is opened. but no focus on the Modal. You need to tab several times to get focus on Modal.

I only see this on Windows+Chrome.  My Mac+Chrome is fine.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I'm unable to reproduce on both Windows 11 and Mac OS in Edge and Chrome. One possible solution is to ensure no extension is affecting the tab order
