### ISSUE TITLE
Component Accessibility Status: JSON output

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#14480]
- Get the designers some JSON! (Using a playwright reporter).
- Create an automated workflow to push any updates to the website.

**Comment by tay1orjones** [comment]
Running notes from our explorations in implementation:

- results.json will be updated as part of the release workflow
  - this will work automatically for normal biweekly minor releases
  - the manual patch process will need to be updated to run `yarn playwright test --grep=@avt` after `yarn install`

**Comment by tay1orjones** [comment]
Closed by #14538
