### ISSUE TITLE
[Bug]: Utility components do not forward ref

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#14499]
### Package

@carbon/react

### Package version

1.36.0

### Description

Currently, some utility components such as `Heading`, `Section`, `Theme` and `Layer` don't forward a ref which results in additionally needed markup when animating etc.

Note: other utility components, such as `Stack` and `Layout` already do forward a ref.

### Reproduction/example

-

### Steps to reproduce

```jsx
<Section ref={contentRef}>
  <Heading ref={headingRef}>Heading</Heading>
</Section>
```

```
⚠️ Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Yeah this should be standard for every component. _Technically_ this could be considered a breaking change, but we've made changes like this before across minors with little to no issue.

**Comment by janhassel** [comment]
@tay1orjones @guidari Any chance we can also get `Grid` and `Column` to accept a ref?
