### ISSUE TITLE
[Enhancement]: FilterableMultiSelect component clears the entire input filter text, when backspace/delete is pressed.

### ISSUE THREAD

**Issue by Jayateerth13** [carbon-design-system/carbon#14516]
### The problem

The FilterableMultiSelect component clears the **entire input filter** text, when backspace/delete is pressed. This leads to an issue, when a user intends to just remove the last character or a few characters, to obtain more filter results to select from, but the whole input gets cleared. (Also leads to diminish the user experience)
The functionality can be observed in Carbon React Storybook.
[https://react.carbondesignsystem.com/?path=/story/components-multiselect--filterable](url)

Below is a preview, where "option" is typed, followed by pressing backspace. As noticed the entire text gets cleared, instead of clearing the last character "n" only (making the input "optio"), which would be more ideal.

https://github.com/carbon-design-system/carbon/assets/40992344/9598652c-8ddd-41b7-97c7-7956c951ef69

### The solution

The ideal functionality for the filter text in FilterableMultiSelect should be similar to that of a text input component, where upon pressing backspace/delete, only the last input character entered should be cleared/deleted.

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by mbgower** [comment]
This seems to make sense to me. Once a user is typing in the input, if they make a typo, it seems reasonable that they can backspace to clear the last typed character.
