### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShucheendraTM** [carbon-design-system/carbon#14510]
### Package

@carbon/react, carbon-components, carbon-components-react

### Browser

Chrome, Firefox, Edge

### Package version

V10.3.0

### React version

V17.0.2

### Description

Unable to sort the date format column  in the carbon datatable.

### Reproduction/example

https://codesandbox.io/s/ecstatic-stallman-pmkdzx?file=/src/App.js

### Steps to reproduce

1.Go to the attached link code sandbox,
2. Click the sort icon for date format column name as created on(Click to sort rows by Created On header in descending order).
3. Perform the ascending and descending order by clicking the icon.
4. To get the sorted dates with date month and years.
5. Cross check the sorted dates.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @ShucheendraTM! For sorting complex values in table cells, like dates, you'll need to implement your own [custom sort](https://react.carbondesignsystem.com/?path=/docs/components-datatable-basic--overview#custom-sorting) via the `sortRow` function prop.

**Comment by ShucheendraTM** [comment]
ok thanks
