### ISSUE TITLE
[Bug]: CodeSnippet copy button obscures portion of content

### ISSUE THREAD

**Issue by silvaDominic** [carbon-design-system/carbon#14550]
### Package

@carbon/react, carbon-components-react

### Browser

Chrome, Firefox

### Package version

1.19.0

### React version

17.0.38

### Description

The copy button obscures the last few characters of text in the CodeSnippet component when it is configured to multiline.

https://github.com/carbon-design-system/carbon/assets/12387334/37a99e0c-ad4a-4c79-8d11-4a963edfc1c7

### Reproduction/example

https://stackblitz.com/edit/github-bjipqk?file=src%2FApp.jsx

### Steps to reproduce

1) Configure the CodeSnippet as 'multi'.
1) Provide enough text to exceed the width of the CodeSnippet component with the last few characters being something distinct.
1) Scroll all the way to the right and observe how the last few characters are obscured.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Turbonomic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @silvaDominic ! Looks like this issue is fixed on the new version.

Now you can see the whole content with a blur in the end.

![Screenshot 2023-08-31 at 10 14 38](https://github.com/carbon-design-system/carbon/assets/52183462/14300fcc-2d12-444f-ad6b-04d803280257)
