### ISSUE TITLE
[Feature Request]: Improve types for ComboBox component

### ISSUE THREAD

**Issue by misiekhardcore** [carbon-design-system/carbon#14572]
### The problem

Current types for the `ComboBox` component are really incomplete. They are assuming many `any` and `unknown` types. There is no good type provided for the item used by this component.

### The solution

Improve types for this component (e.g. provide generic type for an item)

### Examples

Follow the solution already implemented in [`Dropdown.tsx`](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Dropdown/Dropdown.tsx)

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Looks like there is a PR about to merge that will resolve this issue. Thanks!
