### ISSUE TITLE
[Bug]: IconButton doesn't support props.isSelected

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#14594]
### Package

@carbon/react

### Package version

1.37.0

### Description

`IconButton` doesn't support `props.isSelected`.

The alternative way of using `<Button hasIconOnly>` supports it as expected.

### Reproduction/example

https://stackblitz.com/edit/github-goaxgp?file=src%2FApp.jsx

### Steps to reproduce

Try applying `props.isSelected` to both `<IconButton kind="ghost">` as well as `<Button hasIconOnly kind="ghost">`.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by azizChebbi** [comment]
@janhassel I would like to work on this one, can I get assigned ?
