### ISSUE TITLE
[Bug]: TableToolbarSearch doesn't support props.autofocus

### ISSUE THREAD

**Issue by salzpate** [carbon-design-system/carbon#14601]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.37.0

### React version

18.2.0

### Description

TableToolbarSearch doesn't support props.autofocus. It was possible in the versions before 1.37.0.

### Reproduction/example

-

### Steps to reproduce

Try applying props.autofocus to <TableToolbarSearch >.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
This still seems to work as expected. Beware though, that I get a a11y warning from eslint by using this property.  
https://stackblitz.com/edit/github-eyn3dc?file=src%2FApp.jsx


<img width="662" alt="Screenshot 2023-09-08 at 9 23 13 AM" src="https://github.com/carbon-design-system/carbon/assets/11928039/b72b64d9-8336-465d-a1b4-115f5527b65f">


Happy to reopen if you can provide an example that shows this feature not working 👍🏻
