### ISSUE TITLE
[Feature Request]: DatePicker and TimePicker input mask

### ISSUE THREAD

**Issue by peerpalo** [carbon-design-system/carbon#14604]
### The problem

Currently both DatePicker and TimePicker requires end user to properly format date and time. 

If you try to enter 12:30 AM inside [TimePicker](https://react.carbondesignsystem.com/?path=/story/components-timepicker--playground), you are required to put manually hour minute separator (in this case `:`). It's not smooth.

Same for [DatePicker](https://react.carbondesignsystem.com/?path=/story/components-datepicker--simple), you need to format date _manually_.

### The solution

DatePicker and TimePicker should follow component format value and apply automatically a mask. Guiding users to enter correct time or data, without forcing them to put separators.

### Examples

Here is a really simple JavaScript library which does that:

https://github.com/RobinHerbots/Inputmask
https://robinherbots.github.io/Inputmask/#/demo

### Application/PAL

IBM Process Mining

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Hey there @peerpalo! Thanks for the idea, but we are not planning to add this functionality to the components themselves at this time. As you said, there are libraries that can be used to handle this on the end-user side, or you can edit the string via the `onChange` prop.
