### ISSUE TITLE
Button focus state is not showing in Firefox

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon#1461]
The focus state is not showing up in Firefox correctly.
http://www.carbondesignsystem.com/components/button/code

**(Chrome)**

<img width="114" alt="screen shot 2018-11-20 at 2 12 35 pm" src="https://user-images.githubusercontent.com/45213839/48800873-9a3f6a00-ecd0-11e8-9a8a-bbec0810a9d3.png">

**(Firefox)**

![screen shot 2018-11-20 at 2 12 45 pm](https://user-images.githubusercontent.com/45213839/48800878-9d3a5a80-ecd0-11e8-99d7-b688a0192ce2.png)

**Comment by emyarod** [comment]
Which operating system and version of Firefox are you using? I believe this behavior is found in specific browser and OS combinations, like Firefox on Mac OS, and can't be avoided without some JavaScript workarounds

**Comment by JennySanchez** [comment]
Hi @emyarod 
**Operating system:** MacOS High Sierra Version 10.13.6
**Firefox:** Quantum version 60.3.0esr

**Comment by emyarod** [comment]
thanks for the information @JennySanchez ! yeah I think this is just due to differences in browser and OS, and probably isn't worth the effort to try and make consistent on our side before seeing if/how the browser vendors address this

**Comment by JennySanchez** [comment]
Got it and thank you for looking into it @emyarod !
