### ISSUE TITLE
[Carbon components]: Radio-button and Checkbox implementations differs from figma

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon#14628]
### Package

@carbon/react

### Package version

1.37

### Description

Reference issue for web-components: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10911#issuecomment-1714142260

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the [Figma file](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=11555-314421&mode=design&t=3iPwUr1InFX1Tcbq-4), I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| radio margins  | vector image  | top 0.0625rem, right: 0.5rem, bottom: 0.125rem, left: 0.125rem |
| Spacing between label-text and radio  |  8px (0.5rem) | none (uses radio button right margin but it is 8px and it should be 8+2px because of the extra margin  |
| total height | 20px | 21px |
| screen capture |  ![Captura de pantalla 2023-09-05 a las 19 36 10](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/cf8bea73-64c6-4e51-8efc-5b36c405f326) | ![Captura de pantalla 2023-09-05 a las 19 38 02](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/85ca675c-4735-4ba0-97e4-cb1a67990c0c) |

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the [Figma file](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=11555-314711&mode=design&t=3iPwUr1InFX1Tcbq-4), I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| Padding between label-text and checkbox  |  8px (0.5rem) | 6px (0.375rem)  |
| Checkbox margins  | all: 0.125rem  | left: 0.1875rem  the rest: 0.125rem |
| <label> tag  | none (the min-height can be inferred if the checkbox is not `absolute`) | `min-height: 1.5rem; padding-top: 0.1875rem; padding-left: 1.25rem;`  |
| host margin-bottom | none | 0.25rem |
| screen capture | ![Captura de pantalla 2023-09-05 a las 18 54 52](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/1bb4b812-4447-40b3-b288-c1131a0e2d86) | ![Captura de pantalla 2023-09-05 a las 19 02 54](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/40ec4edd-6282-48d4-82a6-125716891930) |

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-radiobutton--overview

### Steps to reproduce

Use it

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Quantum Learning

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Is there a specific layout issue this is causing? cc @carbon-design-system/design can you confirm what changes need to be made to the React implementation

**Comment by korgan00** [comment]
I have to create a multiple choice question that can be single answer (radio) or multiple answer (checkbox). I spent more time than expected trying to make them look the same because of this issue. Most of the implementation looks like patches on one side or the other.
There is a workaround as I suggested in the severity, but I think that the Design document and the implementation should look the same to prevent incoherences.
I forgot to create a link to the [figma design](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=11555-314711&mode=design&t=3iPwUr1InFX1Tcbq-4)

**Comment by tw15egan** [comment]
Do you have a link to a screenshot or [StackBlitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite) that you could share to clearly illustrate the issue you are running into? That would help clearly demonstrate the issues you are facing

**Comment by korgan00** [comment]
https://stackblitz.com/edit/github-81xkqc?file=src%2FApp.jsx

**Comment by korgan00** [comment]
This issue is a copy of the web-components issues: 

 - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10910 
 - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10911.

Looking at the react implementation. It is better because of a `box-sizing`. 
Anyway, the total height should be 20 in both (by the Figma file) and they are 24px in the checkbox and 21px in the radio-button.

**Comment by tw15egan** [comment]
Some of the spacing is needed to make sure the focus outline on the components does not render off the screen / hidden, see here: https://stackblitz.com/edit/github-81xkqc-ejqgaq?file=src%2FApp.jsx,src%2Findex.scss

Chatting with @laurenmrice to come up with a possible solution to improve the alignment differences

**Comment by tw15egan** [comment]
Current solution exploration: https://stackblitz.com/edit/github-81xkqc-bkl4li?file=src%2FApp.jsx,src%2Findex.scss
