### ISSUE TITLE
[Bug]: TextInput & TextArea no longer shows error message when input length exceeds 'maxCount' prop

### ISSUE THREAD

**Issue by fbarroso24** [carbon-design-system/carbon#14634]
### Package

@carbon/react

### Package version

1.33.2

### React version

v16.14.

### Description

Previously, in `@carbon/react: 1.23.0` if the input length of a [TextInput](https://react.carbondesignsystem.com/?path=/story/components-textinput--playground&addons=1&args=enableCounter:!true;inline:!false;maxCount:11&panelRight=0&selectedKind=TextInput&selectedStory=Default&stories=1) or [TextArea](https://react.carbondesignsystem.com/?path=/story/components-textarea--playground&addons=1&args=maxCount:4&panelRight=0&selectedKind=TextInput&selectedStory=Default&stories=1) exceeded the `maxCount`  value then the field became invalid and an error message was displayed (see below).
![image](https://github.com/carbon-design-system/carbon/assets/8657768/31ff00e8-688f-40c6-b6b2-4cd651016a41)

However, after upgrading to `@carbon/react: 1.33.2`, we're no longer seeing the invalid message and therefore it appears as if nothing is wrong.    If `enableCounter: true` at least you may see that the input length exceeds the `maxCount` limit (see below). 
![image](https://github.com/carbon-design-system/carbon/assets/8657768/66ecd6a3-1e60-44a4-a144-bead6af11f9d)

However, if it's not showing the count then there is no way for the user to know (see below). 
![image](https://github.com/carbon-design-system/carbon/assets/8657768/da1ebd31-5af4-4fbd-af87-e3cae7c08610)

In addition, sometimes it won't let you input any more chars than the limit whereas other times it does?  It seems like the `maxCount` feature is completely broken now.

### Reproduction/example

See steps to reproduce on storybook below

### Steps to reproduce

This is reproducible in the storybook.  Simply set `maxCount` to something low (e.g. 5) on either [TextInput](https://react.carbondesignsystem.com/?path=/story/components-textinput--playground&addons=1&args=enableCounter:!true;inline:!false;maxCount:11&panelRight=0&selectedKind=TextInput&selectedStory=Default&stories=1) or [TextArea](https://react.carbondesignsystem.com/?path=/story/components-textarea--playground&addons=1&args=maxCount:4&panelRight=0&selectedKind=TextInput&selectedStory=Default&stories=1) and then enter in a value with length 10.  Notice that sometimes it won't let you exceed 5 (e.g. behavior change) or if it does it no longer shows the invalide text.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by azizChebbi** [comment]
@fbarroso24 when the enableCounter is true and the maxCount prop is passed, then we have two cases: 
1) if u passed a default value which exceeds the maxCount then nothing happens, and this behavior comes with the textarea HTML tag by default, its not a bad implementation of the TextArea component.
2) if u don't pass a default value, then u get the expected behavior. 
otherwise, can u please provide a reproduction link?

**Comment by tw15egan** [comment]
@fbarroso24 I'm not able to replicate that behavior in `1.23.0`. It trims the value to the max allowed length: https://stackblitz.com/edit/github-wydakc?file=package.json,src%2FApp.jsx

That behavior seems the same in `1.33.2` https://stackblitz.com/edit/github-wydakc-ntsxtv?file=package.json,src%2FApp.jsx



Textarea seems to behave the same: 
`v1.33.2`: https://stackblitz.com/edit/github-wydakc-mosibn?file=package.json,src%2FApp.jsx
`v1.23.0`: https://stackblitz.com/edit/github-wydakc-vxdf93?file=package.json,src%2FApp.jsx



Let me know if I'm missing something. Keep in mind, both `enableCounter` and `maxCount` need to be set in order for it to limit characters.
