### ISSUE TITLE
[Bug]: Dropdown does not have tick on the option selected when onChange is used.

### ISSUE THREAD

**Issue by abelzach** [carbon-design-system/carbon#14645]
### Package

carbon-components-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v7.59.8

### React version

v16.14.0

### Description

The Dropdown component is used to create a dropdown menu with selectable options, and it includes a built-in feature where a tick symbol should be displayed next to the currently selected option to provide visual feedback to the user.

```
<Dropdown
  id="default"
  initialSelectedItem={items[3]}
  label="Choose a timeframe"
  items={items}
  itemToString={(item) => (item ? item.text : '')}
/>
```
<img width="690" alt="Screenshot 2023-09-13 at 5 44 32 PM" src="https://github.com/carbon-design-system/carbon/assets/59882990/b3ab4f65-6214-4c56-a958-6794b307a498">

With this configuration, the tick symbol appeared correctly next to the initially selected item. However, after adding an onChange event handler to the Dropdown, the tick symbol is no longer displayed as expected:

<img width="690" alt="Screenshot 2023-09-13 at 5 43 38 PM" src="https://github.com/carbon-design-system/carbon/assets/59882990/2e8f8617-c7e5-4b0c-ac11-984cc7721515">

```
<Dropdown
  id="default"
  selectedItem={selectedOption}
  onChange={({ selectedItem }) => handleDropdownChange(selectedItem)}
  label="Choose a timeframe"
  items={items}
  itemToString={(item) => (item ? item.text : '')}
/>
```

Despite efforts to ensure that the selectedItem or selectedOption state is updated correctly within the onChange event handler, the tick symbol is no longer displayed as expected. This results in a loss of the visual indication of the selected option.

### Reproduction/example

https://codesandbox.io/s/dry-framework-fpfk79?file=/src/App.js

### Steps to reproduce

Just change the different options from the dropdown and see if the tick symbol is visible along the selected option.

Code:
```
import React from "react";
import "./App.scss";
import {
  Dropdown
} from "carbon-components-react";
export default function App() {
const items = [
  {
    id: 1,
    name: "One",
  },
  {
    id: 2,
    name: "Two",
  },
  {
    id: 3,
    name: "Three",
  },
];
const handleDropdownChange = (event) => {
  setSelectedOption(event);
  console.log(event)
}
const [selectedOption, setSelectedOption] = React.useState(items[3]);
  return (
    <div className="app">
      <h1>Carbon React Sandbox</h1>
      <Dropdown id="default" selectedItem={selectedOption}  onChange={({ selectedItem }) => handleDropdownChange(selectedItem)} label="Choose a timeframe" items={items} itemToString={item => item ? item.name : ''} />
    </div>
  );
}
```

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting, I too can see some issues in this repro I cooked up with Carbon v10 and react 16 https://stackblitz.com/edit/github-udw93u?file=src%2FApp.jsx&preset=node=

@abelzach could you confirm 

* Which version of `carbon-components-react` you're using? v1.563.23 isn't a valid version.
* Which version of `react` you're using? This issue says 16 but your repro uses 17. It probably isn't the reason why this isn't working, but good to make sure we're on the same page.

**Comment by abelzach** [comment]
@tay1orjones 

- carbon-components-react: v7.59.8
- react:v16.14.0

These are the configurations of the project I am working on.

**Comment by tw15egan** [comment]
It seems like the issue was because the `items` array was placed inside the `App` function. I figured this out by spinning up the v10 storybook and creating a test story using the example code and couldn't reproduce the issue. The only difference was that the `items` declaration was at the top of the file.  

https://codesandbox.io/s/new-hill-p3gynt?file=/src/App.js

I hope that helps!
