### ISSUE TITLE
[a11y]: The ARIA attributes "aria-label" are not valid for the element <label> with ARIA role "none"

### ISSUE THREAD

**Issue by lavarajallu** [carbon-design-system/carbon#14650]
### Package

@carbon/react, carbon-components, carbon-components-react, @carbon/icons

### Browser

Chrome, Safari

### Operating System

Windows, MacOS

### Package version

v10.48.0

### React version

v17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

In Toggle By default its getting aria-label but still its getting error 

### Reproduction/example

@carbon/react, @console/pal/carbon-components-react

### Steps to reproduce

I am using Toggle from console pal component under carbon react
I am getting errors like this when I run the accessibility checker,
The ARIA attributes "aria-label" are not valid for the element <label> with ARIA role "none"

Here is my code,
````
import {Toggle} from '@console/pal/carbon-components-react';
<Toggle
        id={'label_id'}
        toggled={label_id}
        aria-label={'label_name'}
        labelText={'label_name'}
        labelA={t('shared.off')}
        labelB={t('shared.on')}
        size={'sm'}
        onToggle={(value) => {
          _setParentInput( value);
        }}
      />
````

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I believe you can simply remove the `aria-label`, as it is not needed. I am not seeing it in the latest v10 storybook: https://v7-react.carbondesignsystem.com/?path=/story/components-toggle--default

**Comment by lavarajallu** [comment]
If I remove aria-label still its getting error

**Comment by tw15egan** [comment]
You may need to update your version of Carbon V10
