### ISSUE TITLE
[Link] Add inline link variant

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon#1465]
### Summary

Currently the experimental link component looks to be only for a stand-alone link. We may need to develop a second version of link that is for inline, per accessibility and color can't be the only thing differentiating an inline link. Design + Dev

### Justification

 If in experimental you're only mimicking Carbon current functionality, then you'll need two version because of the new styling: in-line and stand alone. The current Carbon link seems to be for both situations.

### Desired UX and success metrics

Similar to how link works today.

### "Must have" functionality

Will we be able to have a link with an icon? This is pretty highly used in Marketing. If it's not on your timeline we will need to contribute.

### Specific timeline issues / requests

Before Carbon X release

### Available extra resources

Digital team to help Design!

**Comment by eraymond25** [comment]
I see this a ton in product and would still like to see it as a component. Right now, links aren't accessible inline

**Comment by asudoh** [comment]
@eraymond25 Would you be interested in elaborating what the link your proposed is, probably from design perspective, so we can see if there is a @carbon-design-system/design's interest? Thanks!

**Comment by eraymond25** [comment]
@asudoh for sure! It's not a big difference, just underlined when enabled so that it's visually different from the text around it

Stand alone links don't need this underline though, so 2 types would be great!

**Comment by aagonzales** [comment]
Yeah agreed. I think we need both options.

**Comment by shixiedesign** [comment]
We have 2 additional components designed previously: **Secondary** link, and **Inline** link. Does this spec for Inline link look good for your usage @eraymond25 ? Adding these components will be enhancement work and we can add them to the queue of to-dos. 

![Link white](https://user-images.githubusercontent.com/15144993/58201361-8635ee80-7c9a-11e9-8b34-d17c371d2cb5.png)

**Comment by eraymond25** [comment]
Yes, exactly @shixiedesign! thanks 👍 

Secondary links should probably be in that queue as well

**Comment by emyarod** [comment]
just to clarify, does "inline link" only mean that the link must have the underline decoration by default? and is the default color the only difference between secondary and primary links?

**Comment by shixiedesign** [comment]
Yep @emyarod that's correct!

**Comment by shixiedesign** [comment]
note stale

**Comment by emyarod** [comment]
this depends on the possible changes to Link hover/focus/active spec right?

**Comment by shixiedesign** [comment]
Yep... https://github.com/carbon-design-system/carbon/issues/3059

**Comment by shixiedesign** [comment]
This issue needs new spec. To clean up the thread, I will close and open an new one, see: https://github.com/carbon-design-system/carbon/issues/3228
