### ISSUE TITLE
Experimental Checkbox label incorrect color

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon#1466]
## Detailed description

> Describe in detail the issue you're having.

using hex #152935 and should be using gray 100 I believe

> Is this issue related to a specific component?

checkbox

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

experimental

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Digital -- vX release

## Steps to reproduce the issue

1. Seen on carbon site

**Comment by emyarod** [comment]
this seems to be fixed in the current codebase, so it looks like the current production website build just needs to be updated

**Comment by alisonjoseph** [comment]
confirmed this is correct
