### ISSUE TITLE
MultiSelect `sortItems` prop not showing on storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14674]
The `sortItems` prop is missing from MultiSelect's storybook documentation.

![image](https://github.com/carbon-design-system/carbon/assets/3360588/68f01a3a-c4fc-4c05-8c2a-fec0a755a2c8)

It's also not documented in the `MultiSelect.mdx`. It would be nice if we provided a bit of supplemental information about the prop and it's usage, specifically how it works with `selectionFeedback`

```[tasklist]
- [ ] Update MultiSelect prop table in storybook to include `sortItems`
- [ ] Update MultiSelect.mdx to document how to override `sortItems`
```

**Comment by tay1orjones** [comment]
This should mention that it's modeled after the [native array sort method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

> The return value should be a number whose sign indicates the relative order of the two elements: negative if a is less than b, positive if a is greater than b

**Comment by cknabe** [comment]
Please assign to me
