### ISSUE TITLE
[Bug]: non-deterministic slider rendering for value={undefined}

### ISSUE THREAD

**Issue by valente** [carbon-design-system/carbon#14696]
### Package

@carbon/react

### Package version

1.38

### React version

18.2

### Description

Slider initially allows an undefined / empty value. However, once initialized, it cannot go back to this state.

We need to have a deterministic output when value is undefined, irrespective of wether slider had previously a non-undefined value or not.

### Reproduction/example

https://stackblitz.com/edit/github-kdxgwv?file=src%2FApp.jsx

### Steps to reproduce

- Click Set 3 and Set 5. Slider gets new values.
- Click reset to go back to initial state.
- Observed: Slider doesn't change.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by valente** [comment]
Thanks. Yes, that might work.

**Comment by valente** [comment]
One note though: I notice the initial movement to set the slider becomes glitchy. The slider is first drawn with the slider to the left, then when I try to move it with the mouse, the drag behavior suddenly stops (due to the component being rebuilt, now that the value is not undefined anymore, and thus its key changed), and I have to start dragging again.

**Comment by tay1orjones** [comment]
@valente Could you share a screencap of what you mean? I'm not seeing any glitchy behavior from the example I posted. Maybe your usage is slightly different?


https://github.com/carbon-design-system/carbon/assets/3360588/0ca9c3bb-a1e6-4344-b7eb-24e4db42e847

**Comment by valente** [comment]
I [modified your example](https://stackblitz.com/edit/github-kdxgwv-3teskk?file=src%2FApp.jsx) to be closer to what I have. The slider state is held by an entity in the context. I simulated it in the example by adding a parent-child relationship with a wrapper containing the slider.

Since the reset procedure is controlled outside of the component drawing the slider, generating a new key only when the value changes TO undefined, like you have, is a bit cumbersome, but probably can be done.

**Comment by preetibansalui** [comment]
Hey, I just checked the issue with latest build and it seems to be fixed now. 
Please check the [Stackblitz link](https://stackblitz.com/edit/github-b165bw?file=src%2FApp.jsx&preset=node=) for working example. 
Closing the issue as fixed.
