### ISSUE TITLE
UIShell HeaderMenu puts "# in URL when drop-down is clicked

### ISSUE THREAD

**Issue by rafael-nogueras** [carbon-design-system/carbon#14708]
When the user clicks on the UIShell's drop-down component, before selecting anything, the URL gets set to `#`. This is because the `HeaderMenu` component injects an `<a>` element with `href="#"`:

![image](https://user-images.githubusercontent.com/19580576/158654138-54ee4078-6da8-4a49-a420-dc622000d9d9.png)

It seems to be that if the click handler invoked `event.stopPropagation()`, then the URL would not be changed and it would work as desired.

The issue that originally describes this issue [is this one](https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/51777).

**Comment by guidari** [comment]
Hey @rafael-nogueras 
I was checking this issue and looks like have been fixed. I couldn't reproduce in the [storybook](http://localhost:3000/iframe.html?id=components-ui-shell-header--header-w-navigation&viewMode=story). The "#" is not being placed in the URL.

If the error persists, could you reproduce it on [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), please?

**Comment by guidari** [comment]
We will close this, but if you find this issue is not actually resolved, please [open a new issue](https://github.com/carbon-design-system/carbon/issues/new/choose) and include a link back to this issue.
