### ISSUE TITLE
[Bug]: ToggleTip: Link active color wrong

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#14732]
### Package

@carbon/styles

### Package version

1.38.0

### React version

1.38.0

### Description

Active state for links inside ToggleTip are showing up as the base theme color for $text-primary so aren't readable

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-toggletip--playground

### Steps to reproduce

View in storybook

<img width="367" alt="Screenshot 2023-09-28 at 9 11 56 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/39cc0c30-890e-48d6-8f19-66f75267de98">
<img width="351" alt="Screenshot 2023-09-28 at 9 12 04 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/8cfa5e13-ac24-4b5d-843c-41b100e48977">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by JaswanthJeethu18** [comment]
hey @alisonjoseph , I can work on this 👍

**Comment by alisonjoseph** [comment]
duplicate https://github.com/carbon-design-system/carbon/issues/13400
