### ISSUE TITLE
[Bug]: Cannot pass ref to ComboBox after typings update

### ISSUE THREAD

**Issue by a88zach** [carbon-design-system/carbon#14756]
### Package

@carbon/react

### Package version

1.39.0

### React version

18.2.0

### Description

After https://github.com/carbon-design-system/carbon/pull/14576, the ComboBox component no longer takes a ref prop.

![Screenshot 2023-10-03 at 9 44 51 AM](https://github.com/carbon-design-system/carbon/assets/1724822/909c2ca3-dc1a-4a5e-947e-4c94323567ea)

![Screenshot 2023-10-03 at 9 45 04 AM](https://github.com/carbon-design-system/carbon/assets/1724822/5e22fec0-ea58-455f-93ad-41608f3ebc57)

cc: @misiek

### Reproduction/example

none

### Steps to reproduce

Pass a React ref to the ComboBox Component

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hello,
I would like to work on this issue. May I?
