### ISSUE TITLE
[Selectable Components] Research: Audit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#14763]
#### Audit our system for selectable components
- [x] Checkbox
- [x] Radio button
- [x] Tiles (Single and Multiple-select)
- [x] Structured list ([Selection](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--selection))
- [x] Data table ([with Radio selection](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--with-radio-selection))
- [x] For alignment purposes also look at Accordion.

Also Ref[ this discussion](https://github.com/carbon-design-system/carbon/discussions/11506)

#### External research
- [x] Research what other systems are doing

----
- [x] Playback Audit to team

**Comment by utsavsheth** [comment]
If I want to audit, what's the process of auditing the existing system?

Thank you @laurenmrice

**Comment by laurenmrice** [comment]
Hi @utsavsheth 👋. Thank you for your interest in contributing!

This issue is going to be taken on by someone from the Carbon team. Any issues in our repo that have the label `good first issue` are open for people to contribute to.
