### ISSUE TITLE
[Feature Request]: Filterable Dropdown similar to Filterable Multiselect

### ISSUE THREAD

**Issue by jbrisbin-ipipeline** [carbon-design-system/carbon#14760]
### The problem

Our customers have requested our Dropdowns have similar text-based Filterable functionality, which exists in Multiselect but not single Dropdown selects.  

### The solution

Please add 'filterable' attribute to Dropdown, or a new FilterableDropdown, similar to corresponding FilterableMultiselect.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Would [Combobox](https://react.carbondesignsystem.com/?path=/story/components-combobox--default) fit the bill?

**Comment by jbrisbin-ipipeline** [comment]
Unfortunately no.  While Combobox appears to allow you to type in a value, it doesn't appear to automatically filter the list by options that include the searched text, as FilterableMultiselect does.
