### ISSUE TITLE
Broken Links in Pie Chart page on carbon design system site

### ISSUE THREAD

**Issue by alohr51** [carbon-design-system/carbon#1476]
## Detailed description

> Describe in detail the issue you're having.

On http://www.carbondesignsystem.com/data-visualization/pie-chart/usage an image link returns a 404 `imagesusage-pie-char.gif:1 GET http://www.carbondesignsystem.com/data-visualization/pie-chart/imagesusage-pie-char.gif 404 (Not Found)`

also on 

http://www.carbondesignsystem.com/data-visualization/pie-chart/style the [Data Vis overview page](http://www.carbondesignsystem.com/data-vis/overview/style) link guides you to a 404

> Is this issue related to a specific component?

 Pie Chart

> What did you expect to happen? What happened instead? What would you like to see changed?

 images to load and link to redirect to a valid url

> What browser are you working in?

 Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by joshblack** [comment]
Hi @alohr51! 👋 Opened this over on our website repo: https://github.com/carbon-design-system/carbon-website/issues/521
