### ISSUE TITLE
[Selectable Components] Design Solutions & Final Specs 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#14766]
### Acceptance criteria
 - This issue is a follow-on to what came out of the [Audit](https://github.com/carbon-design-system/carbon/issues/14763).
 - We need to take the insights found from the audit and research and create design solutions for how we display selectable controls in components.

----

### Design solution
- Create design solutions for the following components below of how to display selectable controls in components in different states. (particularly looking into the visuals of how we treat this in the enabled, hover, and selected states)

#### Tile
- [x] Single select
- [x] Multi-select 

#### Structured list
- [x] Single select
- Researching on whether Multi-select can be added or not (will research separately)

#### Data table
- [x] Single select
- [x] Multi-select 

----

#### Icon 
- [x] Decide on single & multi-select `icon` 
  - Should it be the actual radio button or whether it can have circular checkmark?
  - Should the icon be on all the options or should it be only on the selected one?
  - Should it be already there or should it only shows up when it is selected?
- [x] Decide on `alignment` rationale
  - Should selections controls always be on the left? on the right?
  - Is this alignment dependent on the component of what makes the most logical sense?
  - Would this be an option on having the control on the left or right depending on the use-case?

#### Cell selection 
- [x] Decide on `cell selection` rationale
  - Should it be filled without strokes or just the strokes?
  - Consider the hover scenario also

#### Pre-selection decisions
- [x] Determine if we should have or should not have one option pre-selected (in tile, radio button, structured list, etc.)
  - Should it be an option depending on the usecase? (Ex: legal requirements?) This could just be a prop in code and written guidance on our website if we decide to do this.

#### Disabled state 
- [x] Decide on whether the helper & warning text should get removed or disabled when the component is `disabled`

----

#### In context examples
- [x] Show recommended design solutions in context of where components that have selectable controls might live close together in one flow, like in a form or provisioning page. (@laurenmrice will give you examples to work with).
- Maybe get in touch with Juan about his explorations for w3 just so we are aware of his work.

 
----

### Playback and finalize specs

- [x] Playback in a crit to Carbon designers and A11y rep
- [x] Align on a direction to move forward with

**Comment by laurenmrice** [comment]
We can size this once the [Audit](https://github.com/carbon-design-system/carbon/issues/14763) is completed.

**Comment by Kritvi-bhatia** [comment]
### Final Design Solution

1. **Tiles**
[Figma file link](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=389-955&mode=design&t=zS0hyNhwq4lAOXTs-4)
![image](https://github.com/carbon-design-system/carbon/assets/148799271/195d6775-d40c-42f4-8295-f481cf3382b0)

------

2. **Structured List**
[Figma file link](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=389-2062&mode=design&t=zS0hyNhwq4lAOXTs-4)
![image](https://github.com/carbon-design-system/carbon/assets/148799271/a4defe43-9911-4985-8517-103ffdafbee3)

------

3. Data Table
[Figma file link](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=389-4264&mode=design&t=zS0hyNhwq4lAOXTs-4)
![image](https://github.com/carbon-design-system/carbon/assets/148799271/d3c5687f-f067-489c-b93e-1914b85bb48c)
