### ISSUE TITLE
Add LTS notification prominently to v10 react storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14765]
This issue is for exploring how we can add a notification to the v10 react storybook highlighting that v7(v10) is going away.

- ~Could we add a banner across all of storybook? Would this require us making an addon, or could we do it a different way?~
- Add it to the welcome page
- Add it to the docs pages
- **Probably the easiest thing to do is make a new global decorator and inject the notification into the top of the canvas for every single story**

There's more details and a list of open questions on the [parent issue](https://github.com/carbon-design-system/carbon/issues/14736)

**Comment by alisonjoseph** [comment]
we could just insert a div / banner [here](https://github.com/carbon-design-system/carbon/blob/v10/packages/react/.storybook/Container.js#L30) and it would show at the top of each story.  https://github.com/carbon-design-system/carbon/blob/v10/packages/react/.storybook/Container.js#L30

<img width="1050" alt="Screenshot 2023-10-03 at 12 38 03 PM" src="https://github.com/carbon-design-system/carbon/assets/2753488/62977fe2-12fc-4ac9-9bdd-f964f164b4da">

**Comment by guidari** [comment]
The PR was merged
