### ISSUE TITLE
[Feature Request]: 4 handle slider

### ISSUE THREAD

**Issue by ayman3011** [carbon-design-system/carbon#14774]
### The problem

The current Carbon [Slider](https://carbondesignsystem.com/components/slider/usage/) component allows the user to change a single value. In other cases such as with setting multiple thresholds at once, this is not possible. The only current solution to this is to repeat the slider a number of times depending on how many thresholds the user would need to configure. Even with that, the problem is each threshold would need 2 values to decide on the threshold range (i.e. the minimum value and the maximum value). While I understand there is a 2 values slider being developed, the use case I have is the user would need to set up 4 different thresholds (Low, Medium, High, and Creitical).

### The solution

To offer multiple threshold configurations in the same pattern/component, where the user would use a slide handler to drag it right or left to set the maximum value for the lower threshold which is the same minimum value for the higher threshold.

So for example, If I have 4 thresholds (Low, Medium, High, and Critical) I would have 3 handlers, one between each 2 thresholds. By dragging the handlers (one at a time), the user would be able to configure all of the thresholds in the same pattern.

The overall threshold is based on a percentage from 0% to 100% with 5% step intervals, however, this is not mandatory.
![image](https://github.com/carbon-design-system/carbon/assets/146368905/92f40ea6-4fef-468e-8d48-ab93f65d80c2)

### Examples

The last example of this page:
https://developergovindgupta.github.io/multi-range-slider-react-ts/

![image](https://github.com/carbon-design-system/carbon/assets/146368905/6f01d168-59e2-4c96-b0a0-b7218edb2b7a)

### Application/PAL

IBM Security Guardium Insights

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

 I would be more than happy to provide any necessary help around implementing it into Carbon's Figma libraries.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by t-trafer** [comment]
Hey, i would like to work on this issue

**Comment by tay1orjones** [comment]
@ayman3011 Thanks for proposing this idea! Could you outline the anticipated use case a bit more as well as the reusability of this pattern, specifically:

* How many teams/projects do you anticipate will use this? 
* Have you explored alternative design options to provide the user this configurability of multiple thresholds?

With this info, we as a team can look at this and determine if this pattern is scalable, and also provide a design spec to implement against. If you're interested, a good way to get some momentum behind this would be to attend the [designer office hours](https://ec.yourlearning.ibm.com/w3/event/10323408) and discuss this proposal with the team.

**Comment by ayman3011** [comment]
> @ayman3011 Thanks for proposing this idea! Could you outline the anticipated use case a bit more as well as the reusability of this pattern, specifically:
> 
> * How many teams/projects do you anticipate will use this?
> * Have you explored alternative design options to provide the user this configurability of multiple thresholds?
> 
> With this info, we as a team can look at this and determine if this pattern is scalable, and also provide a design spec to implement against. If you're interested, a good way to get some momentum behind this would be to attend the [designer office hours](https://ec.yourlearning.ibm.com/w3/event/10323408) and discuss this proposal with the team.

Thank you so much @tay1orjones Sure here are my answers:

**How many teams/projects do you anticipate will use this?**
I know that our team "IBM Guardium Insights" Design Team needs it for a story we're currently working on. I also know another team within IBM Security Design org is also looking for a similar solution. I can get in touch with that other team and get more info, if that is necessary.

**Have you explored alternative design options to provide the user this configurability of multiple thresholds?**
Yes I have explored other ways to provide that including multiple numeric boxes. You may take a look at those exploration and more at the following Figma [file](https://www.figma.com/file/U6EDE4ujk3xYhrCiFCL304/System-Health?type=design&node-id=6527%3A174438&mode=design&t=uLGlJaHhhtiE5CmC-1). Basically, please look at all of the proposed flows in that Figma page.

I'd be more than happy to join the Designer Office Hours next week to discuss this further.

Thank you so much! Really appreciate it a lot :)
