### ISSUE TITLE
New component - Nag modal

### ISSUE THREAD

**Issue by nicoleroppel** [carbon-design-system/carbon#1478]
### Summary

Hi! Diana and I would like to contribute a nag modal design back into the new system. We've used the message banners and block notification design provided in the sketch file as reference. 

This is just providing the design.

### Justification

Watson Customer Engagement currently supports and will need:

- Error nag modals
- Warning nag modals
- Confirmation nag modals

We may use them to:

- Draw attention to immediate, important pieces of information.
- Confirm actions that are not reversible.

Screenshot of the design below:

<img width="468" alt="screen shot 2018-11-26 at 2 56 52 pm" src="https://user-images.githubusercontent.com/43546639/49044947-5b605700-f19d-11e8-8fed-d1f998853c2c.png">

<img width="446" alt="screen shot 2018-11-26 at 2 56 57 pm" src="https://user-images.githubusercontent.com/43546639/49044948-5b605700-f19d-11e8-8df4-521859eb45b2.png">

<img width="402" alt="screen shot 2018-11-26 at 2 57 03 pm" src="https://user-images.githubusercontent.com/43546639/49044949-5b605700-f19d-11e8-9d38-ec7d7daa50bc.png">

Link for the sketch file: https://ibm.box.com/s/f3hahv4sdkk6fdejj5j0wsbmco9hrsta

### Contributing designers

Diana Tran - dianatran18
Cooper Sanborn - coopersanborn
Nicole Roppel - nicoleroppel

Let us know if you have any questions!

Thanks!

**Comment by asudoh** [comment]
Moved to: carbon-design-system/carbon-contribution#15.

**Comment by aagonzales** [comment]
Re-opening in mono-repo, we're trying to remove the "contributors" repo because issue get lost/forgotten there. Instead we have a new label `type: contribution`

**Comment by joshua-vaughn** [comment]
nag

**Comment by joshua-vaughn** [comment]
I'm nagging stalebot about the nag modal

**Comment by connor-leech** [comment]
We're accepting this as a variant of modal. Guidance should be included for modal and the variant should be referenced in the notification docs.

**Comment by andreagmann** [comment]
@connor-leech could you provide an update on the guidance for this?
