### ISSUE TITLE
[Feature Request]: icon only MenuButton

### ISSUE THREAD

**Issue by misiekhardcore** [carbon-design-system/carbon#14796]
### The problem

In our team we are migrating to use carbon/react components. We had an dropdown component which had an animated icon as a label to show auto refresh timer.
As a replacement we decided to use `MenuButton` as it seems to be the closest component to what we had before.
The problem is that when we pass the button label of type `ReactNode` we get an error in the console that prop `label` of underlying `Menu` component 
Old component:
![Screenshot from 2023-10-05 16-49-56](https://github.com/carbon-design-system/carbon/assets/58469680/786da9f4-db00-4496-bb12-aa38ce414c17)
New component:
![Screenshot from 2023-10-05 16-40-53](https://github.com/carbon-design-system/carbon/assets/58469680/b5d0afc2-9937-4729-928b-1ae1f4b0f075)
Console error:
![Screenshot from 2023-10-05 16-43-05](https://github.com/carbon-design-system/carbon/assets/58469680/8af60457-3c84-4e6e-8fce-82b3174905e9)

### The solution

We can add `menuLabel` prop to the `MenuButton` to specify separate label for the underlying menu component

### Examples

that is what I made as a temporary solution:
```typescript
type MenuButtonProps = {
  children?: ReactNode;
  className?: string;
  disabled?: boolean;
  label: ReactNode;
  menuLabel: string;
  size: 'sm' | 'md' | 'lg';
  kind: 'primary' | 'secondary' | 'ghost';
  iconDescription?: string;
  hasIconOnly?: boolean;
  fullScreenTarget?: Element | null;
};

export default forwardRef<HTMLDivElement, MenuButtonProps>(function MenuButton(
  {
    label,
    menuLabel,
    size,
    kind,
    children,
    className,
    disabled,
    iconDescription,
    hasIconOnly,
    fullScreenTarget,
  },
  forwardedRef
) {
  const menuRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLDivElement>(null);
  const ref = useMergedRefs<HTMLDivElement>([triggerRef, forwardedRef]);
  const [width, setWidth] = useState(0);
  const {
    open,
    x,
    y,
    handleClick: hookOnClick,
    handleMousedown,
    handleClose,
  } = useAttachedMenu(triggerRef);
  const id = useId();

  function handleClick() {
    if (triggerRef.current) {
      const {width} = triggerRef.current?.getBoundingClientRect();
      setWidth(width);
      hookOnClick();
    }
  }

  function handleOpen() {
    if (menuRef.current) {
      menuRef.current.style.width = `${width}px`;
      menuRef.current.style.maxWidth = 'unset';
    }
  }

  return (
    <Tooltip
      label={hasIconOnly ? iconDescription : undefined}
      className={classnames('MenuButton cds--icon-tooltip', className, {hasIconOnly})}
      leaveDelayMs={50}
    >
      <div className="MenuButton" ref={ref}>
        <Button
          className={classnames('cds--menu-button__trigger', {
            'cds--menu-button__trigger--open': open,
          })}
          ref={triggerRef}
          size={size}
          kind={kind}
          renderIcon={ChevronDown}
          iconDescription={hasIconOnly ? iconDescription : undefined}
          disabled={disabled}
          aria-haspopup
          aria-expanded={open}
          onClick={handleClick}
          onMouseDown={handleMousedown}
          aria-controls={open ? id : undefined}
        >
          {label}
        </Button>
        <Menu
          ref={menuRef}
          target={fullScreenTarget}
          id={id}
          label={menuLabel}
          open={open}
          onClose={handleClose}
          onOpen={handleOpen}
          x={x}
          y={y}
          size={size}
        >
          {children}
        </Menu>
      </div>
    </Tooltip>
  );
});
```

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by janhassel** [comment]
Hey! An icon-only MenuButton would be the OverflowMenu in V12. You can try it out with the `enable-v12-overflowmenu` feature flag:

```jsx
import React from 'react';
import {
  unstable_FeatureFlags as FeatureFlags,
  OverflowMenu,
  MenuItemRadioGroup,
} from '@carbon/react';
import { Renew } from '@carbon/react/icons';

export default function App() {
  const items = [0, 1, 5, 10, 15, 30, 60];

  return (
    <div style={{ margin: '3rem' }}>
      <FeatureFlags
        flags={{
          'enable-v12-overflowmenu': true,
        }}
      >
        <OverflowMenu
          label="Refresh interval"
          renderIcon={Renew}
          size="sm"
          tooltipAlignment="right"
        >
          <MenuItemRadioGroup
            label="Refresh interval"
            items={items}
            defaultSelectedItem={items[0]}
            itemToString={(item) => {
              if (item === 0) {
                return 'Off';
              }

              return `${item} minute${item > 1 ? 's' : ''}`;
            }}
          />
        </OverflowMenu>
      </FeatureFlags>
    </div>
  );
}
```

https://stackblitz.com/edit/github-vspt1w?file=src%2FApp.jsx

---

The only difference from your mockup is that there is no chevron icon next to the main icon. There is a current discussion going on here: #14593

**Comment by misiekhardcore** [comment]
hey @tay1orjones! sorry for a late response but I was sick for quite some time. I was originally thinking about using the `OverflowMenu` but the problem with that component is that there is no indication (like the chevron icon I mentioned in the issue) that indicates that this is a menu. From the user perspective, I think, it's not really clear that the `OverflowMenu` isn't just a normal button
