### ISSUE TITLE
Travis CI:  es6.object.to-string.js 'default' is not exported 

### ISSUE THREAD

**Issue by hellobrian** [carbon-design-system/carbon#148]
## Overview

```
START:
commonjs-proxy:/home/travis/build/carbon-design-system/carbon-components/node_modules/core-js/library/modules/es6.object.to-string.js (1:219) 'default' is not exported by 'node_modules/core-js/library/modules/es6.object.to-string.js'
```

☝️ Is anyone aware of why our Travis CI is logging this out before running tests? Not sure how to resolve this myself. cc: @asudoh

**Comment by asudoh** [comment]
@hellobrian Good catch, I suspect it's because `rollup-plugin-commonjs` is not applied to `core-js` for tests. The roll up config for tests can be found in karma.conf.js. Would you want to fix it? If not let me know and I can go ahead and fix it.

**Comment by hellobrian** [comment]
Hey @asudoh, sorry for the late reply. If it's okay, might be better if you fix it. Thanks for offering!
