### ISSUE TITLE
[Bug]: config prefix hardcoded to 'cds' in zone.scss for background and color properties

### ISSUE THREAD

**Issue by JakeMetz8** [carbon-design-system/carbon#14827]
### Package

@carbon/styles

### Package version

11.33.0

### Description

Lines 39 and 40 set the background and color properties scoped to given zone class. However, they are hardcoded with the `cds` prefix rather than dynamically using the prefix from config. This break when a user of your system sets a different prefix.

```
    39: background: var(--cds-background);
    40: color: var(--cds-text-primary);
```

suggested:
```
background: var(--#{config.$prefix}-background);
color: var(--#{config.$prefix}-text-primary);
```

### Reproduction/example

https://github.com/carbon-design-system/carbon/blob/release/v11.33.0/packages/styles/scss/_zone.scss

### Steps to reproduce

Set the prefix to something other than `cds`. Check zoned styles to see if background and color are broken

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@JakeMetz8 Thanks for reporting this, I've got a PR up to fix

**Comment by JakeMetz8** [comment]
@tay1orjones thank you so much. Once I get a bit more confident I'll try to raise PRs for these easy ones ;)
