### ISSUE TITLE
[Bug]: Incorrect typescript for renderSelectedItem property of the Dropdown component

### ISSUE THREAD

**Issue by petermoogk** [carbon-design-system/carbon#14847]
### Package

@carbon/react

### Browser

Firefox

### Package version

v9.6.5

### React version

v17.0.2

### Description

The intention for the renderSelectedItem property of the Dropdown component is specified in PR   https://github.com/carbon-design-system/carbon/pull/10188.  It allows the user to specify a function that returns JSX element instead of the default string.  However, the typescript for this property is currently defined as a function that returns string instead of a JSX element.  This causes my React code to give an error since it specifies a function that returns a JSX element.  I propose that the typescript be changed to:
renderSelectedItem?: React.JSXElementConstructor<ItemType>;

This is similar to what is being done for the itemToElement property

### Reproduction/example

NA

### Steps to reproduce

The Dropdown below will cause a typescript error, since the renderSelectedItem property is expecting a function that returns a string.
<Dropdown
      id="someid"
      titleText=""
      hideLabel={true}
      size="sm"
      items={someItems}
      label=""
      renderSelectedItem={(item: { id: string; label: string }) => {
        return <div>some text</div>
      }}
      itemToElement={(item: { id: string; label: string }) => {
        return <div>some text</div>
      }}
    />

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for opening this! 

> I propose that the typescript be changed to:
> renderSelectedItem?: React.JSXElementConstructor;

I think that's a reasonable approach, feel free to put that into a PR and we can get it reviewed and merged.

**Comment by parthrc** [comment]
hey @tay1orjones can I work on this?

**Comment by sojinantony01** [comment]
I am still getting type error for `renderSelectedItem` in the latest versions. 

Carbon Version - @carbon/react : 1.48.0
React version - 17.0.2

Error message 
```
 Type '(item: ITableSchemaPath) => JSX.Element' is not assignable to type '(item: ITableSchemaPath) => JSXElementConstructor<ITableSchemaPath>'.

  Type 'Element' is not assignable to type 'JSXElementConstructor<ITableSchemaPath>'.ts(2322)

Dropdown.d.ts(105, 5): The expected type comes from property 'renderSelectedItem' which is declared here on type 'IntrinsicAttributes & Omit<DropdownProps<ITableSchemaPath> & { children?: ReactNode; } & RefAttributes<HTMLButtonElement>, "ref">' 
```

Element or ReactNode is not supporting.

**Comment by EAlexRojas** [comment]
Looks like the fix done was not correct, the `renderSelectedItem` is being declared as 
```
  renderSelectedItem?(
    item: ItemType
  ): React.JSXElementConstructor<ItemType> | null;
```

This is saying that `renderSelectedItem` is a function that takes `item` as parameter an returns a JSXElementConstructor... which is not correct. It should be a function that returns a ReactNode.

`React.JSXElementConstructor` is ok for the case of `itemToElement` in that same file because it's saying that `itemToElement` is a `JSXElementConstructor`, which is correct as it's a function that returns a ReactNode.
