### ISSUE TITLE
Ghost button padding changes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1484]
-We need to make a change to the padding of the ghost button to always be a fixed 16px on left and right sides.

-Reason for this change is that after designing data table we have run into issues where the ghost button spacing looks offset/like a mistake when there are multiple of them together, which creates awkward spacing relationships.

**Comment by laurenmrice** [comment]
@IBM/carbon-developers

**Comment by tw15egan** [comment]
@laurenmrice is this still a problem?

**Comment by laurenmrice** [comment]
just checked and this has been fixed ! 🎉

**Comment by tw15egan** [comment]
🎉
