### ISSUE TITLE
[Bug]: Accordion Component: Not possible to collapse items of nested accordion components

### ISSUE THREAD

**Issue by anton-tsymuk-viacomcbs** [carbon-design-system/carbon#14840]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.39.0

### React version

18.2.0

### Description

Actual: 
- items of a nested accordion component are expanded by default
- items of a nested accordion component can not be collapsed

Expected:
- items of a nested accordion component are collapsed by default
- items of a nested accordion component can be expanded/collapsed

### Reproduction/example

https://stackblitz.com/edit/github-h6yxfu

### Steps to reproduce

- expand the parent accordion item
- try to collapse the child accordion item

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @anton-tsymuk-viacomcbs, Nested accordions are not a supported pattern in the design system. We recommend flattening your information architecture as much as possible. 

https://github.com/carbon-design-system/carbon/issues/7328
https://github.com/carbon-design-system/carbon/issues/5666
https://github.com/carbon-design-system/carbon/issues/5765
