### ISSUE TITLE
[Bug]: ComboBox input, numpad 1(End)  and 7(Home) moves cursor before number is inserted

### ISSUE THREAD

**Issue by aaanttila** [carbon-design-system/carbon#14887]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.37.0

### React version

v17.0.2

### Description

When using numpad keys '1' (alternate 'End') or '7' (alternate 'Home') on ComboBox input, cursor moves to home/end before number is inserted.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-combobox--overview

### Steps to reproduce

- Use keyboard with numpad 
- Press numlock ON
- Place cursor on ComboBox input field 
- Using numpad, type '7' once. '7' appears. Type '7' again. Cursor stays in place , and seven appears after cursor.
  Type '1', first cursor moves to the end of input then '1' is inserted.
  Type '7' again cursor moves to beginning of input

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@aaanttila I'm not sure this will matter, but are you seeing this on windows or mac?

**Comment by tay1orjones** [comment]
I can confirm this using an apple wired keyboard with numpad on MacOS. I did not have to turn numlock on (it doesn't look like numlock is a feature available on MacOS)

Pressing <kbd>7</kbd> (keyCode `103`) or <kbd>1</kbd> (keyCode `97`) on the numpad results in odd insertion into the input. 

Normal non-numpad character keys <kbd>7</kbd> (keyCode `55`) or <kbd>1</kbd> (keyCode `49`) work as expected.


https://github.com/carbon-design-system/carbon/assets/3360588/e46ba62a-bd1b-444a-b44f-8605d3dc5581

**Comment by aaanttila** [comment]
> @aaanttila I'm not sure this will matter, but are you seeing this on windows or mac?

ubnutu and windows
