### ISSUE TITLE
[Bug]: Large SideNavMenu unable to display children when expanded

### ISSUE THREAD

**Issue by andresilva7** [carbon-design-system/carbon#14888]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.32.0

### React version

18.2.0

### Description

When creating a SideNavMenu with the large property set to true, the children are not displayed when the menu is expanded. Children should be displayed when menu is expanded and hidden when the menu is not expanded.

### Reproduction/example

https://stackblitz.com/edit/github-bkw3uy-jjtxca?file=src%2FApp.jsx

### Steps to reproduce

- Click on "Test Expandable" for an example of how it should behave.
- Click on "Test Large Expandable" for an example of the issue.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

GOAT

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by shivam-singh-negi** [comment]
https://github.com/carbon-design-system/carbon/assets/56045882/5ae86391-65a5-4bb9-bbc4-a2b17f2c6760

**Comment by shivam-singh-negi** [comment]
with bug:
.cds--side-nav__item--large{
height:3rem;}
corrected:
.cds--side-nav__item--large{
height:auto;}
