### ISSUE TITLE
[Feature Request]: Update react-router example to use v6

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon#14897]
### The problem

[This documentation](https://carbondesignsystem.com/developing/react-tutorial/step-1/#add-routing) is for `react-router-dom@5`. Version 6 has been out for 2 years and most React projects moved to it. There are no examples in the documentation (or elsewhere on the Internet) showing how to use `react-router-dom@6` with `@carbon/react`.

### The solution

Update [the documentation](https://carbondesignsystem.com/developing/react-tutorial/step-1/#add-routing) to show clear examples with the latest router.

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@nstuyvesant Thanks for bringing this up! We're in the process of updating the tutorial right now, though it's going to be based on Next.JS. Right now I don't think we plan on providing specific documentation for the other various router/framework options out there (Remix, react-router, tanstack-router, etc.) though we'd welcome the community to contribute this type of information if you'd be interested in that. 

Are you encountering a specific bug or usage issue with the latest react-router-dom?

**Comment by nstuyvesant** [comment]
Hi @tay1orjones - Thanks for the quick reply. Interesting to know about the updated tutorial focusing on next.js. While trying to use react-router-dom@6, had a few challenges like ClickableTile doesn't have an `as` property so I can pass in a `<Link>` from react-router. Another issue I saw was `<SideNavMenuItem>` disappearing after interacting with anything in an `<Outlet>` unless the parent `<SideNav>` had `expanded` set to `true`.

Mostly, there was a lot of trial and error as I am working to rebuild a docs site for `@carbon/charts` that I originally created using `carbon-components-svelte`. The team preferred react with vite over SvelteKit or react with next.js.

**Comment by tay1orjones** [comment]
@nstuyvesant Thanks for the additional info! Sorry to hear you ran into those issues. If you think there's things that could be done to fix or smooth over those issues, please let us know. We could probably spin those out into multiple/individual bugs if it's across multiple components as you mentioned.

Moving forward we probably won't house framework-specific documentation outside of the tutorial, but if you're interested, you could update the [existing react-router example](https://github.com/carbon-design-system/carbon/blob/4fec5335fb25f61fbb86738822744ccc0689eda2/packages/react/examples/react-router/README.md) in the repo to show some of the patterns you uncovered. I think it could help a good portion of folks, particularly relating to the UIShell configuration. That example hasn't been updated in ~2 years.

**Comment by ychavoya** [comment]
Hi, I opened a PR to update the react-router example with some usages of react-router v6 with the UI Shell. I'm open to any suggestions!
