### ISSUE TITLE
[Bug]: need to click twice for RadioButton to get correct fill

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon#14891]
### Package

@carbon/react

### Browser

Chrome,  117.0.5938.149
I am not observing this in FF or Safari

### Package version

"@carbon/react": "^1.37.0",

### React version

18

### Description

I have recently noticed that the fill of the radio button isn't applied until I click twice on the radio button or the label. The behavior can also be seen in the Carbon react storybook.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-radiobutton--default

### Steps to reproduce

Click RadioButton, you'll notice that upon the first click it only receives a focus outline. And upon the second click, it receives the fill.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Carbon for IBM Products

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
What browser / OS are you using? I don't seem to be seeing it, but I may be missing something.

![2023-10-12 13 21 28](https://github.com/carbon-design-system/carbon/assets/11928039/9637c45b-2c2c-49a7-a4bc-93a0ae33e23e)

**Comment by matthewgallo** [comment]
I looked at this again in an incognito chrome browser tab, and don't see the issue anymore. 🤔 Maybe there is something cached in my browser that is causing this, I'll close this issue.

**Comment by tw15egan** [comment]
Super weird, I know I've had some glitches with both the Grammarly / 1Password extensions before. Thanks for reporting back
