### ISSUE TITLE
Bug: Data Table component not working with AngularJS

### ISSUE THREAD

**Issue by hemanth-avs** [carbon-design-system/carbon#149]
## Overview

Data Table component not working with AngularJS. 
Without AngularJS, component is working as Expected.

```gherkin
Feature: Data Table component
  As a Developer,
  I want to Use Data Table component with AngularJS
  So that I can populate the Table with  Dynamic table content
```

# **Data Table + Angular JS - Non Working Version**

Gist - https://gist.github.com/hemanthavs/15ae05436868ba2a4d633af50d1e0a41

<div class="bx--responsive-table-container" data-responsive-table>
  <table class="bx--responsive-table" data-table>
    <thead class="bx--table-head">
    <tr class="bx--table-row">
      <th class="bx--table-header"></th>
      <th tabindex="0" class="bx--table-header" ng-repeat="header in tabledata.thead"> {{header}} </th>
    </tr>
    </thead>
    <tbody class="bx--table-body">
    <tr ng-repeat-start="tr in tabledata.tbody" tabindex="0" class="bx--table-row bx--parent-row" data-parent-row>
      <td tabindex="0" class="bx--table-expand" data-event="expand">
        <svg class="bx--table-expand__svg" width="8" height="12" viewBox="0 0 8 12" fill-rule="evenodd">
          <path d="M0 10.6L4.7 6 0 1.4 1.4 0l6.1 6-6.1 6z"></path>
        </svg>
      </td>
      <td ng-repeat="td in tr">{{td}}</td>
    </tr>
    <tr ng-repeat-end class="bx--table-row bx--expandable-row bx--expandable-row--hidden">
      <td> Display only when Expanded</td>
    </tr>
    </tbody>
  </table>
</div>

**Data Binding :** 

$scope.tabledata = {
                      "title" : "Title",
                      "thead" : [ "Column1", "Column2", "Column3" ],
                      "tbody" : [ [ "1", "2", "3" ], [ "11", "22", "33" ] ]
 };

# **Data Table + Non Angular JS - Working Version**

Gist - https://gist.github.com/hemanthavs/3a047bfb627aa695e2fd8ac73b111859

<div class="bx--responsive-table-container" data-responsive-table>
  <table class="bx--responsive-table" data-table>
    <thead class="bx--table-head">
    <tr class="bx--table-row">
      <th class="bx--table-header"></th>
      <th tabindex="0" class="bx--table-header"><span>Last Name</span></th>
      <th tabindex="0" class="bx--table-header"><span>House</span></th>
    </tr>
    </thead>
    <tbody class="bx--table-body">
    <tr tabindex="0" class="bx--table-row bx--parent-row" data-parent-row>
      <td tabindex="0" class="bx--table-expand" data-event="expand">
        <svg class="bx--table-expand__svg" width="8" height="12" viewBox="0 0 8 12" fill-rule="evenodd">
          <path d="M0 10.6L4.7 6 0 1.4 1.4 0l6.1 6-6.1 6z"></path>
        </svg>
      </td>
      <td>Granger</td>
      <td>Gryfindor</td>
    </tr>
    <tr class="bx--table-row bx--expandable-row bx--expandable-row--hidden">
      <td> Display only when Expanded</td>
    </tr>
    </tbody>
  </table>
</div>

## Other

Below is screenshot of code comparison of Angular vs Non Angular Data Table component code

![image](https://cloud.githubusercontent.com/assets/5846263/26710164/a3aadb10-471d-11e7-9cfb-b840dbd97c49.png)

Error I am seeing in console

![image](https://cloud.githubusercontent.com/assets/5846263/26710493/d66133b8-471f-11e7-8470-cb0334af36a7.png)

**Comment by asudoh** [comment]
Wondering what happens if `.refreshRows()` is called after Angular completes stamping out `ng-repeat` template. CC @chrisdhanaraj

**Comment by hemanth-avs** [comment]
@asudoh , solved the issue
