### ISSUE TITLE
[Bug]: UIShell / Header / Header with SideNav Storybook example does not display SideNavMenuItem items when viewport > 1058px

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon#14902]
### Package

@carbon/react

### Browser

Safari 17, Chrome 119, FireFox 120

### Package version

1.44.0

### React version

18.2.0

### Description

When the viewport width is less than 1058px, the hamburger menu displays. Clicking on it reveals **SideNavMenu** and **SideNavMenuItems** correctly.

When the viewport width is greater than 1058px, `isSideNavExpanded` from the **HeaderContainer** is `false` even though the **SideNav** is displayed (without needing to click the hamburger menu button). When `expanded={isSideNavExpanded}` is set on the **SideNav** component AND `isSideNavExpanded` is `false`, **SideNavMenuItem** items are not displayed and **SideNavMenu** does not respond to clicks. 

The [`@carbon/react` Storybook example UIShell / Header / Header with SideNav](https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-navigation-actions-and-side-nav) shows this bug - no **SideNavMenuItem** components are displayed and clicking "Category title" does not cause them to be displayed.

Note: FireFox 120 behaves badly as well but in a different way. When the hamburger menu is displayed, the SideNav is visible and cannot collapse.

### Reproduction/example

https://stackblitz.com/edit/stackblitz-starters-bbn15a?file=src%2FApp.tsx
and
https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-navigation-actions-and-side-nav

Sub-menu items are missing in the default Storybook view here...

<img width="903" alt="image" src="https://github.com/carbon-design-system/carbon/assets/5770938/32eb05ba-4349-4dbe-a1a0-cb8a83fb5700">

Here, the submenu items are shown because the viewport is narrower:

<img width="404" alt="image" src="https://github.com/carbon-design-system/carbon/assets/5770938/d2291cef-2d9c-40b3-88d9-4a9403a62d38">

### Steps to reproduce

1. Open the [StackBlitz repro](https://stackblitz.com/edit/stackblitz-starters-bbn15a?file=src%2FApp.tsx). By default, it will likely display at a viewport width of less than 1058px.
2. Click the hamburger menu and see the **SideNavMenu** and **SideNavMenuItems**.
3. Widen the viewport for the right frame so it is wider than 1058px then click the StackBlitz **Reload** button (you may not even need to reload to see the **SideNavMenuItem** components disappear).

**SideNavMenuItem** components disappear. Clicking the **SideNavMenu** does not display them.

It appears to be related to the management of the state of `isSideNavExpanded` (render prop from **HeaderContainer**). When the viewport is wider than 1058px, the value is set to `false` but should be `true` since the SideNav is displayed by default.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Carbon Charts

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by nayakswadhin** [comment]
I would like to work on this issue, Kindly assign this issue to me

**Comment by nstuyvesant** [comment]
@tay1orjones - any chance this could be addressed? Noticed you are releasing the update for the latest Storybook but the Storybook content for the UIShell is broken because of this bug.

**Comment by tay1orjones** [comment]
@nstuyvesant It looks like this was introduced in 11.35.0 (`@carbon/react@1.35.0`). I think it stems from one of two changes made to UIShell in that time:

1. https://github.com/carbon-design-system/carbon/pull/14353
2. https://github.com/carbon-design-system/carbon/pull/14251

I think it's probably the second one. We'll work on a fix. Thanks for reporting this, and sorry for the delay!

**Comment by nstuyvesant** [comment]
@tay1orjones - thank you!

**Comment by nstuyvesant** [comment]
@tw15egan - the PR from @guidari does not appear to have been merged to main and included in a release. Would it be possible to create a release?
