### ISSUE TITLE
C4AI: Explore dev feasibility of initial AI gradient requirements

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14929]
This issue is for exploring the feasibility of early designs, collaborate with designers to determine limits of dev implementation, and overall answer the many questions surrounding the existing design specifications for Carbon for AI.

Existing delivered explorations:
* https://stackblitz.com/@tw15egan/collections/ai-explorations
* https://codepen.io/lee-chase/pen/MWZdZxo/78d436c84ea15d00094fcb878188c4cf

**Comment by mattrosno** [comment]
Going to split the aura into a separate issue.
