### ISSUE TITLE
Ghost buttons usage and dropdown filters (cloud design checkin feedback)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1492]

**Comment by laurenmrice** [comment]
When opening a modal within a page to view more items of something, should a link style be used or a ghost button style? 
![image (1).png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/597ff266-214b-4931-bba1-e2eb0809ac0b)

  - Links tend to link out to another navigational destination, but this would remain on the same page.
  - If a ghost button is used, the background will be triggered on hover which overlaps the lines of the row.

**Comment by laurenmrice** [comment]
Should dropdowns for filters align the text in the dropdown with the above label, or should the border outline be flush with the label.
![Pasted Graphic 1.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/a9df9892-8dd8-46e1-b011-1184b732cff4) 

  - If the text is aligned to the label, the dropdown active border will creep outside of alignment.

**Comment by janellearita** [comment]
Our services also use the ghost button component within our structured lists. Rollover view within our structured list has the button height fill the row. Are there any recommendations here when using within structured lists?

![image.png](https://images.zenhubusercontent.com/5bfec9215cb43a45a18ad97f/c0a509dd-6d7c-4881-ba1f-0ba19af3c6ad)

@laurenmrice

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
1. Use a link style to open a modal instead of a button style.
2. The dropdown to filter above a data table should always align the text. Below is an example of this in v9 and v10 using inline and default dropdowns.
![Artboard](https://user-images.githubusercontent.com/43969356/62076495-6f1cfb00-b20d-11e9-9e6f-53cc4733c2b7.png)

3. We don't recommend to use buttons within structured lists but if you are using one in a structured lists below are ways to use them in v9 and v10 using different pixel height rows. I know that cloud is looking for a component between a structured list and a data table, this would be a great way to contribute back to Carbon. 
![Artboardw](https://user-images.githubusercontent.com/43969356/62076610-b60af080-b20d-11e9-87e8-08d9ee46e9f5.png)
