### ISSUE TITLE
C4AI Slug: Implement the interactive Slug component in `@carbon/react`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14947]
I think we can run this in tandem with the spec work in https://github.com/carbon-design-system/carbon/issues/14948

At the very least we could begin to scaffold out the component with an initial take on the design with room for interpretation as the spec firms up.

**Comment by mattrosno** [comment]
@tw15egan are you working on this right now?

**Comment by tw15egan** [comment]
@mattrosno yeah initial PR is up here: https://github.com/carbon-design-system/carbon/pull/14998
