### ISSUE TITLE
[Feature Request]: Update Twitter (X) Logo

### ISSUE THREAD

**Issue by SteffenAuer** [carbon-design-system/carbon#14997]
### The problem

Twitter changed their name to X some time ago and with it the logo. Would be good to be able to use the new logo as well.

### The solution

Please change the twitter logo from the iconic blue bird to the new X. The svg file on wikipedia: https://en.m.wikipedia.org/wiki/File:X_logo_2023_original.svg

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by SteffenAuer** [comment]
I closed this by accident. Still open.

**Comment by npenin** [comment]
Any ETA for this rather simple implementation ?

**Comment by Brandon-Huu** [comment]
The logo should not be updated.

**Comment by npenin** [comment]
why not ? what is the rationale ?

**Comment by conradennis** [comment]
Hi, we can close this issue. The new X logo has been added to library in late 2023. The old twitter logo has also been kept in the library.

<img width="543" alt="Screenshot 2024-01-12 at 1 39 56 PM" src="https://github.com/carbon-design-system/carbon/assets/16782944/78770b04-8715-4320-8fb9-519dce8ab31b">
