### ISSUE TITLE
[Bug]: warnings from SideNav in console log from inert prop

### ISSUE THREAD

**Issue by ecrvich** [carbon-design-system/carbon#14990]
### Package

@carbon/react

### Package version

1.40

### React version

17 and 18 both show the warning

### Description

I believe **_any_** usage of SideNav in one's app will produce this console warning now. Ren Maddox reported this 22 days ago in the Slack carbon-react channel (search for "inert"). Looks like Guilherme reproduced it in StackBlitz, but I don't believe he ever opened an Issue. I have removed the inert prop on the offending line in SideNav.js to keep my log from blowing up with this.

```
Warning: Received `false` for a non-boolean attribute `inert`.

If you want to write it to the DOM, pass a string instead: inert="false" or inert={value.toString()}.

If you used to conditionally omit it with inert={condition && value}, pass inert={condition ? value : undefined} instead.
    at nav
    at SideNavRenderFunction (c:\GitClones\CDD-Hub\node_modules\@carbon\react\lib\components\UIShell\SideNav.js:38:15)
```

### Reproduction/example

see description

### Steps to reproduce

see description

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hello,
I would like to work on this issue. May I?
