### ISSUE TITLE
Modal titles - should they include icons, and are they supposed to be so tight to the text?

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#150]
## Overview
In the web documentation for the Transactional and Passive modals, is there supposed to be  an icon in the modal title, and should it be so close to the title?
http://www.carbondesignsystem.com/components/modal/code#

![image](https://cloud.githubusercontent.com/assets/6569324/26736633/948a4cf0-478c-11e7-866e-ee399f878efd.png)

I can't see anything in either the documentation, or the code snippet to suggest this icon should be there. And it links to the code, which again makes me think it's not intentional. 

Icon appears in Chrome

**Comment by hellobrian** [comment]
Nope, modals are not meant to display icons in that way. This is a bug on the website that we will revert by Monday. Those icons were only intended to appear next to [page section titles](http://www.carbondesignsystem.com/style/grids) on the website but they were accidentally added in some places where they shouldn't be. 

Sorry for the confusion and thanks for pointing this out.
