### ISSUE TITLE
Redundant tooltips that repeat the tab label

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon#15000]
### Package

carbon-components

### Browser

Chrome

### Package version

V10, V11

### Description

The Carbon website states that a tooltip is used to provide additional or explanatory information. However, tab components display tooltips that simply repeat the label, which adds no value for the users.
![image](https://github.com/carbon-design-system/carbon/assets/40870771/e041c24a-4a98-49dd-830d-c8df65d5f526)

### Reproduction/example

https://carbondesignsystem.com/components/tabs/usage/#live-demo

### Steps to reproduce

https://carbondesignsystem.com/components/tabs/usage/#live-demo

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting this! I agree, and I think we can simply remove the `title` to avoid this redundant description.

**Comment by mateus037** [comment]
Hi @tay1orjones, I would like to work on this issue. :D
