### ISSUE TITLE
[Feature Request]: Add `disableOverflow` option to PaginationNav to support high page counts

### ISSUE THREAD

**Issue by radarfox** [carbon-design-system/carbon#15014]
### The problem

We would like to migrate from our custom pagination component to PaginationNav. We have the publications catalogue, that has over 1600 pages. Our custom component has no problems navigating it, but as I'm trying the PaginationNav playground, it looks like it tends to freeze the browser just for thousands of pages. I'm using Chrome 118.

- [Setting `totalItems: 2500` will freeze my browser for about 5 seconds after the pagination is displayed.](https://react.carbondesignsystem.com/?path=/story/components-paginationnav--playground&args=totalItems:2500)
- [Setting `totalItems: 10000` will freeze my browser for about 45 seconds, during which Chrome warns twice that the page is not responding](https://react.carbondesignsystem.com/?path=/story/components-paginationnav--playground&args=totalItems:10000)

### The solution

I'm not sure where exactly the problem is, so it's complicated to propose something. I suppose the problem might by in the select associated with "..." button. It lists thousands of items, which is a bit hard to navigate for the user. So, maybe allow to disable the select to prevent this? Or limit the select to some finite number of items? Maybe something like this:

```
<PaginationNav maxSelectItems={10} />
```

### Examples

https://research.ibm.com/publications

### Application/PAL

https://research.ibm.com/

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
The performance issue is probably related to this bit of the code and could be rewritten to be more optimized for high page counts:

https://github.com/carbon-design-system/carbon/blob/7ef9cb984bc08b3735515e450c1b12ea01e85293/packages/react/src/components/PaginationNav/PaginationNav.js#L302-L318

Also note that Chrome [limits](https://chromium.googlesource.com/chromium/blink.git/+/master/Source/core/html/HTMLSelectElement.cpp#77) the total amount of `option`s inside a `select` to 10000

**Comment by sstrubberg** [comment]
Connected to the UX in https://github.com/carbon-design-system/carbon/issues/15012

**Comment by tay1orjones** [comment]
Do you see that there's an actual use case for jumping to the middle within the overflow when you have that many pages? I ask because one option to eliminate this issue would be to add a new prop to disable the overflow at high page counts, like GitHub does:
![image](https://github.com/carbon-design-system/carbon/assets/3360588/e20128b1-0804-4944-946e-bc73d7c20c7a)

The `...` is not operable in that screenshot.

**Comment by radarfox** [comment]
@tay1orjones I have mentioned that problem in the issue description:

> I suppose the problem might by in the select associated with "..." button. It lists thousands of items, which is a bit hard to navigate for the user. So, maybe allow to disable the select to prevent this? Or limit the select to some finite number of items?

If you would add a new property like `maxSelectItems?: number` or `disableSelect?: boolean` it would solve the problem for us.

**Comment by tay1orjones** [comment]
@radarfox Yep, we just discussed as a team and agree, adding a `disableOverflow` prop to allow disabling the overflow (select) is a good option. It should still render the three dots `...`, but not be operable. 

This will fall lower on our list of priorities so we may not be able to get to it in a timely fashion. If you're keen to contribute this enhancement, we'd so appreciate it! I'm happy to answer any questions to help get you started on a PR, just let me know.
