### ISSUE TITLE
[a11y]: Focus not working in ClickableTile when no href passeed

### ISSUE THREAD

**Issue by ShiriKremer** [carbon-design-system/carbon#15024]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.35.0

### React version

1.35.0

### Automated testing tool and ruleset

saw in sandbox as well

### Description

I am using a group of ClickableTiles to display clickable information. 
I do not set the optional  "href"  property for them (a click is expected to open in the future a side panel).
In this setting I do not see the tiles getting "focus" when hitting tab. 

While investigating this we noticed that if we do specify a "href"  property value, we do get the expected "focus" behavior.

[We are using 
 version: "1.35.0" - but did a test in pure sand box for this test code also using 1.40.0 and see the same.

### Reproduction/example

<div className="container">       <ClickableTile         data-auto-id="clickable-tile-1"         id="clickable-tile-1"         value="1"         clicked       >         Tile 1       </ClickableTile>       <ClickableTile         data-auto-id="clickable-tile-2"         id="clickable-tile-2"         value="2"         onClick={clickAction}       >         Tile 2       </ClickableTile>       <ClickableTile         data-auto-id="clickable-tile-3"         id="clickable-tile-3"         value="3"         onClick={clickAction}       >         Tile 3       </ClickableTile>     </div>

### Steps to reproduce

Add few ClickableTile instances to a div
Don't specify a href property
Once running click tab -> they are not passed through

(if u do place an href property value - doing the above will pass through the tiles)

e.g.:
<ClickableTile
        data-auto-id="clickable-tile-1"
        id="clickable-tile-1"
        value="1"
        clicked
      >
        Tile 1
      </ClickableTile>
      <ClickableTile
        data-auto-id="clickable-tile-2"
        id="clickable-tile-2"
        value="2"
        onClick={clickAction}
      >

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alewitt2** [comment]
Im seeing the same behavior.

Side Note: I was trying to find a workaround and noticed another bug i think.
- if you add `tabIndex="0"` to clickableTile - `<ClickableTile tabIndex="0">`
- set `onKeyDown` prop for clickableTile - `<ClickableTile tabIndex="0" onKeyDown={()=>console.log('event fired')}>`
- on the webpage, tab to the tile and press `Enter` or `Space`
- The callback gets called 2 times.

i think its this line that is duplicating the call https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tile/Tile.tsx#L167
