### ISSUE TITLE
[Feature Request]: IBM AfroHacks at AfroTech Participation

### ISSUE THREAD

**Issue by jritten** [carbon-design-system/carbon#15056]
### The problem

IBM AfroHacks at AfroTech Hackathon starts on Monday, and the Carbon project repo(s) are not properly labeled to indicate to participants wanting to contribute to Carbon during the 2-day hackathon which projects/issues to work on. 

### The solution

Add “afrohacks” to Settings  => Topics on any Carbon repos, and add "afrohacks" to issue Labels, to indicate the repos/repo issues Carbon would like to have participants work on during the 48-hour AfroHacks at AfroTech Hackathon starting on Monday. Please feel free to connect with me with any questions. Thank you!

### Business priority

High Priority = pressing release

### Available extra resources

https://ibm.biz/afrohacks-hackathon

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Done 👍 Thanks for the heads up!
