### ISSUE TITLE
[Bug]: sass loading warning about deprecated use of `/`

### ISSUE THREAD

**Issue by alewitt2** [carbon-design-system/carbon#15062]
### Package

@carbon/react

### Browser

Chrome

### Package version

11.41.1

### React version

16.14.0

### Description

![image](https://github.com/carbon-design-system/carbon/assets/48691328/0f142611-5f4f-46a6-bbd4-39dac5d2c51b)

offending line https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/slider/_slider.scss#L149

because the `/` is wrapped in a `#{}` it doesnt count as being inside the calc

### Reproduction/example

na

### Steps to reproduce

try to pull in the latest 11.41.1 into a repo and include `@use '@carbon/react';`

### Suggested Severity

Severity 3 = workaround

You can use the --quiet-deps and/or --quiet option to tell sass not to emit these warnings
https://sass-lang.com/documentation/cli/dart-sass/#quiet

### Application/PAL

Satellite-UI

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by urbanisierung** [comment]
I was experiencing the same `warning` - thanks for opening the bug and thanks for the quick fix! Upgrading to `1.41.2` solves the issue. I think the bug can be closed now.

**Comment by tw15egan** [comment]
Thanks for confirming 🙏🏻
