### ISSUE TITLE
[Bug]: Radio Button group error

### ISSUE THREAD

**Issue by Harelazimtas** [carbon-design-system/carbon#15064]
### Package

@carbon/react

### Package version

1.41.1

### React version

17.0.2

### Description

I try to upgrader carbon react to version 1.41.1 but i get this error
 
![Screenshot 2023-10-30 at 9 46 17](https://github.com/carbon-design-system/carbon/assets/48510673/cefe51a1-7c20-44fe-a233-0e71183f8737)
![Screenshot 2023-10-30 at 9 48 11](https://github.com/carbon-design-system/carbon/assets/48510673/679f5d66-3cdc-496f-91fa-e452d83fff21)

### Reproduction/example

https://stackblitz.com/edit/github-pps2pn?file=src/App.jsx

### Steps to reproduce

try to use this component 

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting this @Harelazimtas, we'd welcome a PR to update the types if you're able.

**Comment by kuri-sun** [comment]
Hello!! I would love to work on this issue!
May I take a look at this?

**Comment by tw15egan** [comment]
Not seeing any errors when testing these two components running latest in a [StackBlitz](https://stackblitz.com/edit/vitejs-vite-hbsijs?file=src%2Findex.scss,src%2Fmain.tsx,src%2FApp.tsx&terminal=dev), feel free to reopen if you are still encountering any issues
