### ISSUE TITLE
[Feature Request]: Publish storybook addon to allow visual testing of RTL, theme etc outside of Carbon

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#15076]
### The problem

Many teams use Storybook and it would save them time with visual testing of theme, RTL etc 

### The solution

Publish a storybook addon for theme and RTL as a package

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@lee-chase just to be clear, you're asking for these two toggles that are available in our storybook, but published as an addon for others to consume?


https://github.com/carbon-design-system/carbon/assets/3360588/8431e38b-f313-4ec9-bdb7-ceb2d71c6b2f

**Comment by tay1orjones** [comment]
@lee-chase We discussed this again as a team and the main concerns that limit how eager we are to take this on is the initial development time to stand up a new package and then the maintenance/upkeep cost compared with overall benefit.

Additionally, right now these options are pretty simple to implement. I'm happy to help get these over into the ibm-products storybook to solve the initial need you have right now. It would mostly be a copy and paste and some small tweaks to the storybook config.

If we add more of these types of things to storybook and it reaches a critical mass, we could absolutely revisit this. We just think right now the cost/benefit is too great to swallow right now.
