### ISSUE TITLE
C4AI Gradient: Figure out the list of components that will need an AI gradient

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15071]
```[tasklist]
### Tasks
- [x] Evaluate all core components, not just the 8-10 in the AI Essentials Figma library
- [x] Deliverable is a complete list of core components that need the gradient, to be spec'ed in a different issue
```

**Comment by mattrosno** [comment]
@tw15egan - @aagonzales's working Figma file for this audit:

https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=127-11718&mode=design&t=biXjw7jX5M8I91Fb-0

**Comment by mattrosno** [comment]
@aagonzales would you say this issue is complete because of your Figma audit?

**Comment by aagonzales** [comment]
Yes, this issue is now complete with the audit
