### ISSUE TITLE
[Bug]: typescript error for InlineNotification

### ISSUE THREAD

**Issue by petermoogk** [carbon-design-system/carbon#15079]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.41.1

### React version

v17.0.2

### Description

In the recent 1.41.1 version of @Carbon/react the InlineNotification component is now giving an error that it wasn't giving before.  Typescript is now requiring a value for the role attribute and the onCloseButtonClick attribute.  The documentation for InlineNotification indicates that these attributes have default values.  https://react.carbondesignsystem.com/?path=/story/components-notifications-toast--default
For role the docs indicate that the default is "status".  For onCloseButtonClick  the default is suppose to be a noop.  Thanks!

### Reproduction/example

NA

### Steps to reproduce

Create in InlineNotification component without role or onCloseButtonClick .  Typescript will give a compilation error, preventing the application from starting.  

The work around is to add these attributes to the component.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

React app

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting this @petermoogk, we'd welcome a PR to update the types if you're able.

**Comment by tw15egan** [comment]
Fixed via https://github.com/carbon-design-system/carbon/pull/15068
