### ISSUE TITLE
[Illustration]: C4IBMP Banner image illustration

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#15101]
### The problem

Carbon for IBM Products recently updated the design of their homepage and we need another dedicated rev on illustrations and a proper design review with Mike and Jeannie to ensure adherence to design quality and brand standards.

The current illustration:
 https://pages.github.ibm.com/cdai-design/pal/
 
The current illustration is loud and distracting and the type hierarchy doesn't match any of the other PAL layouts. With so many Gatsby sites out there there's no need to deviate from an existing pattern.
 
<img width="1522" alt="image" src="https://github.com/carbon-design-system/carbon/assets/43144260/35a1075e-676a-47c2-a12d-249515e86ec8">

### The solution

Let's mirror the layout on the IBM Security Software Design site (there's currently an issue open for the missing type on the left of the paragraph, so ignore that)

https://pages.github.ibm.com/security/security-design/

<img width="1562" alt="image" src="https://github.com/carbon-design-system/carbon/assets/43144260/51512bcb-0133-4c5e-9f4a-06a3eaadead5">

### Application/PAL

Carbon Core

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by thyhmdo** [comment]
Original issue: https://github.ibm.com/CDAI-design/pal/issues/1391

Figma file: https://www.figma.com/file/Fu9rOdSFQyIGTdn4UgOXFp/branch/mExjVIjp3sxU7HKuQejkn0/DSAG-PAL-Enhancement-Nav-research?type=design&node-id=0%3A1&mode=design&t=MoHf7LTAgv92WJIj-1

Illustration file 
[Carbon for IBM Products illustration cards.zip](https://github.com/carbon-design-system/carbon/files/13920876/Carbon.for.IBM.Products.illustration.cards.zip)

**Comment by thyhmdo** [comment]
Suggestion Final 

![1903](https://github.com/carbon-design-system/carbon/assets/77697351/ce8fdb00-c500-4a67-a275-04439616650a)
