### ISSUE TITLE
[Bug]: Tooltip handleClickOutside is buggy in OverflowMenu component with React 17

### ISSUE THREAD

**Issue by sandeshdarde** [carbon-design-system/carbon#15107]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

v7.48.1

### React version

v18.16.1

### Description

Encountered an issue with the behavior of tooltips within our OverflowMenu component.

### Reproduction/example

https://codesandbox.io/s/patient-tdd-vqv2cq

### Steps to reproduce

Install latest carbon-components-react
Install React 17
Implement a page with at least two Tooltip components on it
Click on one of the tooltips to open it
Open the other tooltip

### Expected result:
The first Tooltip closes immediately when I click the other one

### Actual result:
The first Tooltip still open after click the other one

### Note:
It is working with React 16. So possibly be related to the event delegation change in 17.

![image](https://github.com/carbon-design-system/carbon/assets/69839532/848a6e30-676a-495f-a356-e407b8f76b87)

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I don't believe `OverflowMenu` supports `Tooltip` as children. In `V11`, it would be recommended to use `Popover`, as that can render any children in a popover container. Does updating to the latest version of V10 resolve this issue?
