### ISSUE TITLE
[Bug]: Style division warning

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#15113]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.41.1

### React version

17

### Description

getting this warning when compliing my styles from carbon 
```
 css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/app.scss 1.18 MiB [built] [code generated]

LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/app.scss
<w> Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
<w> 
<w> Recommendation: math.div(convert.to-rem(2px), 2) or calc(convert.to-rem(2px) / 2)
<w> 
<w> More info and automated migrator: https://sass-lang.com/d/slash-div
<w> 
<w> node_modules/@carbon/styles/scss/components/slider/_slider.scss 149:39  slider()
<w> node_modules/@carbon/styles/scss/components/slider/_index.scss 4:1      @use
<w> node_modules/@carbon/styles/scss/components/_index.scss 60:1            @use
<w> node_modules/@carbon/styles/index.scss 22:1                             @use
<w> src/client/app.scss 17:1                                                root stylesheet
<w> 

webpack 5.89.0 compiled successfully in 36680 ms

```

### Reproduction/example

N/A

### Steps to reproduce

When building webpack

### Suggested Severity

None

### Application/PAL

Support Center / IBM Cloud

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Should be fixed via https://github.com/carbon-design-system/carbon/pull/15063 and included in `v11.41.2` https://github.com/carbon-design-system/carbon/releases/tag/v11.41.2
