### ISSUE TITLE
[Question]:  I want to persist the selected rows after moving to new page and come back to same page in datatable 

### ISSUE THREAD

**Issue by kish0rpawar1** [carbon-design-system/carbon#15119]
### Question for Carbon

[Question]:  I want to persist the selected rows after moving to new page and come back to same page in datatable. 

We can access all the selected rows through the selectedRows property. Here I am storing selected rows in checked state to maintain a list of checked rows even after moving to next page, I want to sync checked state with the selectedRows Property, How to use selectRow action to achieve this behaviour?

https://github.com/carbon-design-system/carbon/assets/138873837/04a0b86b-aa61-487f-9665-259c8b86da0a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Hi, anything outside the normal flow of state for DataTable will require implementing your own custom data table state manager. Here is an [example template](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager-vite) that may help
