### ISSUE TITLE
[Bug]: @carbon/icon-helpers imports react and cannot find a declaration file

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon#15114]
### Package

@carbon/icons-helper

### Browser

NA

### Package version

v10.45.1

### Description

Recent typescript migration for `@carbon/icons-helper` introduced a breaking change for non-react apps consuming the package. `React` is imported in `getAttributes.ts`, this causes non-react apps/libs using this _helper_ library to break.

Additionally, type declaration for the following files cannot be found:
* ./toString
* ./toSvg

![image](https://github.com/carbon-design-system/carbon/assets/38994122/6778d005-cf42-4b01-a478-b00a48940f4c)

### Reproduction/example

NA

### Steps to reproduce
Following errors are noticed in carbon-components-angular project.

1. Install latest version of `@carbon/icon-helpers` (1.41.1)
2. Import exported helper
3. Errors show up in terminal 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

For the time being, I've notified users to use icon-helper version prior to the typescript migration.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Adding react as a dependency to icon-helpers will solve the first issue. It's probably debatable if react should be a necessary dependency for this package, but I'm not sure how to avoid it. @lewandom you headed up that refactor, what do you think about trying to keep `@carbon/icon-helpers` framework agnostic, even from a typing perspective?

For the other two errors, `toString` and `toSVG` haven't been converted to TypeScript yet, so you'll need to `//ts-ignore` those imports for now to suppress the warnings.

**Comment by lewandom** [comment]
@tay1orjones thanks for marking me here. I agree icon-helpers should be framework-agnostic. I guess I just went the shortest path to use the ready React type for SVG props. I'll try to find some time to find a better platform-agnostic alternative. You can assign me this bug.

**Comment by tay1orjones** [comment]
Thanks @lewandom! Let me know if you'd like to pair up. This one swirled my brain a bit when I briefly dug into it.

**Comment by huineng** [comment]
I'm using carbon with angular. It's a kind of blasphemy to add react as a dependency. And if you add it as a dependency, please do it somewhere i cannot see it :). Anyway i have to stick to 10.44.00 for now. Thanks

**Comment by lewandom** [comment]
@tay1orjones I did an attempt at solving this in https://github.com/carbon-design-system/carbon/pull/15542. Please check when you get some time. I wasn't able to figure out how to make TS and JS code in this project to co-live, so just migrated everything in there to TS. It wasn't much ;)
