### ISSUE TITLE
[Bug]: Sorting function differs between Chrome and Firefox

### ISSUE THREAD

**Issue by molyholy** [carbon-design-system/carbon#15117]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

v^1.x

### Description

We're using the `<DataTable>` component and depending on what browser you're using, the Sort column feature does not work as intended

### Reproduction/example

https://stackblitz.com/edit/github-anzvxd?file=package.json,src%2FApp.jsx

### Steps to reproduce

1. Open the stackblitz with Firefox. Navigate to App.jsx
2. Notice on Line 15 the variable `filteredHeaders` and how some headers have `isSortable: false`
3. Sort the columns and note how even the `isSortable: false` columns will still sort
4. Repeat Steps 1-3 in Chrome and note how the `isSortable: false` columns work properly and won't sort

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

@console/pal": "^1.579.7"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@molyholy Hey! I'm not sure why this is behaving differently across browsers, but to disable sorting on individual headers, you'll need to pass in the `isSortable` prop

```diff
 <TableHeader
   id={header.header || 'links'}
   {...getHeaderProps({
     header,
   })}
+  isSortable={header.isSortable}
 >
```

This works consistently across browsers and also is the intended solution as the TableHeader will no longer render a button or be focusable for those with `isSortable="false"`. Hope this helps!

**Comment by tay1orjones** [comment]
Related https://github.com/carbon-design-system/carbon/issues/11139
