### ISSUE TITLE
Sept-Nov '23 Icon Dump for Scott

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#15126]
https://github.com/carbon-design-system/carbon/pull/15125

Can I get an image collecting all these for my playback?

**Comment by laurenmrice** [comment]
**Issue:** https://github.com/carbon-design-system/carbon/pull/15125

![Image](https://github.com/carbon-design-system/carbon/assets/43969356/6c511a8c-2205-46ca-b0e3-be87fc6fbb51)

-----

**Issue 1:** https://github.com/carbon-design-system/carbon/pull/15116
**Issue 2:** https://github.com/carbon-design-system/carbon/pull/15135

![Image](https://github.com/carbon-design-system/carbon/assets/43969356/b3336c09-1bf0-48eb-8d7c-52c57617d9d1)
