### ISSUE TITLE
[Bug]: Inconsistent helper text behavior when Checkbox and RadioButtonGroup are disabled

### ISSUE THREAD

**Issue by John30013** [carbon-design-system/carbon#15123]
### Package

@carbon/react

### Browser

Chrome

### Package version

v10.41.2

### React version

v18.2.0

### Description

When a `Checkbox` with helper text is disabled, the helper text continues to be displayed in the `$text-helper` color rather than the `$text-disabled` color:
![carbon-11-checkbox-states](https://github.com/carbon-design-system/carbon/assets/11495877/71e39290-ddc7-434d-84db-c46754a44f55)

When a `RadioButtonGroup` with helper text is disabled, the helper text disappears entirely.
![carbon-11-radio-button-group-disabled](https://github.com/carbon-design-system/carbon/assets/11495877/7842b31a-af74-4fc2-a3ab-95aae27c2393)

(Both screenshots above are from the react.carbondesignsystem.com site.)

The `ComboBox`, `Dropdown`, `MultiSelect`, `Select`, `TextArea` and `TextInput` work as expected: the helper text is displayed in the `$text-disabled` color when the component is disabled.

### Reproduction/example

https://stackblitz.com/edit/github-zqgoyx?file=src%2FApp.jsx

### Steps to reproduce

Add a `Checkbox` and/or `RadioButtonGroup` to your app, and set its `disabled` prop to `true`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
I just checked storybook and it appears to be displaying as intended. The screen shot you shared above only one of the items is disabled, so the label and helper text wouldn't change. If you set the CheckboxGroup to disabled it displays as below. 

<img width="240" alt="Screenshot 2024-03-29 at 1 23 42 PM" src="https://github.com/carbon-design-system/carbon/assets/2753488/bbefd75a-f274-435e-b040-5beb35877204">

Please reopen if I'm missing something here. thanks!
