### ISSUE TITLE
Add TypeScript types to next/OverflowMenu

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#15179]
This issue is for adding TypeScript types to the new menu-based implementation of OverflowMenu that is currently behind a feature flag at `packages/react/src/components/OverflowMenu/next/index.js`

This may need to be implemented alongside adding types for the existing/stable implementation of OverflowMenu, https://github.com/carbon-design-system/carbon/issues/13237

Please review the information in the parent issue, and read and follow the steps outlined in the [adding component types documentation](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/adding-component-types.md#steps-to-provide-baseline-type-definitions-for-components).

**Comment by Tresau-IBM** [comment]
I will work on this!

**Comment by Sam-Wool** [comment]
I'll pick this up along with [#13237](https://github.com/carbon-design-system/carbon/issues/13237)
