### ISSUE TITLE
Add TypeScript types to ComboButton

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#15178]
This issue is for adding TypeScript types to the ComboButton.

This relies on types being available for the underlying Menu and MenuItem components, https://github.com/carbon-design-system/carbon/issues/15177

Please review the information in the parent issue, and read and follow the steps outlined in the [adding component types documentation](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/adding-component-types.md#steps-to-provide-baseline-type-definitions-for-components).

**Comment by yumin2002** [comment]
Hello, I want to take this issue. Is this issue is only for react?
