### ISSUE TITLE
Add TypeScript types to Menu, MenuItem

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#15177]
This issue is for adding TypeScript types to the Menu and MenuItem components.

Please review the information in the parent issue, and read and follow the steps outlined in the [adding component types documentation](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/adding-component-types.md#steps-to-provide-baseline-type-definitions-for-components).

**Comment by mattborghi** [comment]
I will take this one!
