### ISSUE TITLE
Create design spec for AI `Tag`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15185]
Explore possible directions for placing an AI slug into a Tag. Once a direction if determined, create a design spec for development, including details of color (themes), structure, and spacing.

**Comment by aagonzales** [comment]
Initial AI tag concept from Mike 

<img width="178" alt="image" src="https://github.com/carbon-design-system/carbon/assets/11670886/653f228b-5919-42b5-bb4d-22d0df78d9db">

**Comment by RichKummer** [comment]
[Figma design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=780%3A84587&mode=design&t=kkjGPiJlGYVkqIKJ-1)

`tag` uses an inline AI slug (16px) that trails the tag label, but sits in front of the close button. The inline slug also adopts the same color token as the icon for each color option:

![Image](https://github.com/carbon-design-system/carbon/assets/15643582/bf74e782-9465-4e26-8584-384cfa996f75)
