### ISSUE TITLE
Create design spec for AI `Tile`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15181]
Create a design spec for basic, clickable, expandable, and selectable tile for both AI light and dark flavors.

**Comment by aagonzales** [comment]
## Deliverables 
[Figma file](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=480%3A155908&mode=design&t=fBJtuUy5OHPCZyeF-1)

Notes: Currently, only delivering on layer style of tile. This may change in the future to fit better with the core layering theme but at the moment all AI tiles will look the same and not change per layer. 

<img width="1312" alt="Tiles - White" src="https://github.com/carbon-design-system/carbon/assets/11670886/3f692873-9966-4c9d-8b49-763ad82dd656">

<img width="1312" alt="Tiles - Gray 100" src="https://github.com/carbon-design-system/carbon/assets/11670886/ae7df0bb-eed1-453e-9799-3d086efbc8ce">
