### ISSUE TITLE
Create design spec for AI `RadioButton`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15183]

**Comment by aagonzales** [comment]
[Figma file](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=482%3A159758&mode=design&t=fBJtuUy5OHPCZyeF-1)



![Image](https://github.com/carbon-design-system/carbon/assets/11670886/e45f772b-511f-4689-8161-5c1cf43b4f99)
