### ISSUE TITLE
Add AI enhancements to React `Dropdown`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15186]
This effort also includes adding the slug and gradient to:

```[tasklist]
### Tasks
- [ ] Dropdown
- [ ] ComboBox
- [ ] MultiSelect
- [ ] FilterableMultiSelect
```

**Comment by mattrosno** [comment]
@tw15egan did I get this right? How the Dropdown AI enhancements also includes the other components specified in the tasklist?

**Comment by tw15egan** [comment]
@mattrosno yes looks correct!
