### ISSUE TITLE
Create design spec for AI `Checkbox`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15182]

**Comment by aagonzales** [comment]
[Figma file 
](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=480%3A158599&mode=design&t=fBJtuUy5OHPCZyeF-1)


![Image](https://github.com/carbon-design-system/carbon/assets/11670886/fbe8fb5c-6b9f-4503-bddc-c03a3333bd88)
