### ISSUE TITLE
Add AI enhancements to React `Tag`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15193]
> [!WARNING]  
> **Blocked by**
>
> - #15185

**Comment by tw15egan** [comment]
Spec has been provided by @RichKummer in https://github.com/carbon-design-system/carbon/issues/15185

[Figma design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=825%3A110429&mode=design&t=kkjGPiJlGYVkqIKJ-1)

`tag` uses an inline AI slug (16px) that trails the tag label, but sits in front of the close button. The inline slug also adopts the same color token as the icon for each color option:


![Image](https://github.com/carbon-design-system/carbon/assets/15643582/6e9f7a14-f96b-4ba4-a2f5-025b28be0599)
