### ISSUE TITLE
Add AI enhancements to React `Modal`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15192]
> [!WARNING]  
> **Blocked by**
>
> - #15184

**Comment by tw15egan** [comment]
Spec has been provided by @RichKummer in https://github.com/carbon-design-system/carbon/issues/15184

[Figma design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=211%3A162656&mode=design&t=kkjGPiJlGYVkqIKJ-1)


![Image](https://github.com/carbon-design-system/carbon/assets/15643582/da07672d-49ab-44cc-97ba-31b36a401898)
![Image](https://github.com/carbon-design-system/carbon/assets/15643582/34b19abf-919f-49e5-a45d-d0dd26004a6c)
