### ISSUE TITLE
Please add a Vertical Navigation Menu toolbar

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#152]
Many IBM web applications sport an intuitive vertical navigation menu on the left-side of the screen.
It would be great if this pattern could be extracted into a reusable component.

**Comment by bsonefeld** [comment]
Hi @gmosx , thanks for that suggestion. Could you post some screenshots or examples so we can get a better understanding of what this component could look like?

**Comment by gmosx** [comment]
Something like the left-side  navigation element here:

![screen shot 2017-06-08 at 10 47 05 am](https://user-images.githubusercontent.com/37342/26917665-d7b66b26-4c37-11e7-9bba-79f4efbed563.png)

**Comment by gmosx** [comment]
i.e. a vertical toolbar

**Comment by hellobrian** [comment]
Although it's not exactly what you're asking for, the closest thing we have is the [Interior Left Nav](http://carbondesignsystem.com/components/interior-left-nav/code) component, which is mainly for use in product.

**Comment by marijohannessen** [comment]
@tsaitsaitsai @bsonefeld  is this something we can look into or is it a request for a different team?

**Comment by bsonefeld** [comment]
So far we haven't heard this request. I imagine you can customize the Interior Left Nav to only show icons. 

There are currently no future plans to support this type of navigation, but if we do, I will reopen this issue.
