### ISSUE TITLE
[token]: add $link-inverse-hover and $link-inverse-visited color tokens

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15204]
## Acceptance criteria
- We currently use the `$link-inverse` color token  for link text that are placed on a high contrast background, like`$background-inverse` in the [Toggletip component](https://react.carbondesignsystem.com/?path=/story/components-toggletip--playground). While this token works correctly in the enabled state, the hover state and visited state looks visually broken, and is either too dark or too light depending on which theme you are using. 

- We need 2 new color tokens for `$link-inverse-hover` and `$link-inverse-visited`to resolve the color contrast problems within toggletips.

----

### New color tokens

`$link-inverse-hover`
| White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
|--------|--------|--------| --- |
| Blue 30 | Blue 30 | Blue 70 | Blue 70 |

`$link-inverse-visited`
| White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
|--------|--------|--------| --- |
| Purple 40 | Purple 40 | Purple 60 | Purple 60 |

<img width="1477" alt="Frame 11" src="https://github.com/carbon-design-system/carbon/assets/43969356/7d933d86-0583-4a98-aaae-cd2511002e54">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Related issue https://github.com/carbon-design-system/carbon/issues/14732

I also think we may need a `$link-inverse-visited` token
Reported on [slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1701781765870069)

| White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
|--------|--------|--------| --- |
| Purple 40 | Purple 40 | Purple 60 | Purple 60 |
