### ISSUE TITLE
[Bug]: Datepicker `closeOnSelect` prop is not working

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#15215]
### Package

@carbon/react

### Package version

1.42

### React version

18.2

### Description

The prop `closeOnSelect` is not working as expected. It is suppose to avoid the close action when the user select a date in the calendar if the prop is set as `false`.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--playground&args=closeOnSelect:!false

### Steps to reproduce

- Go to the Datepicker playground and set the `closeOnSelect` to false;
- Open tge calendar and select a date;
- (Expected) Calendar should NOT close 

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by AdityaPimpalkar** [comment]
Hey @guidari Mind if I take this up? Thanks! :)

**Comment by guidari** [comment]
Hey @AdityaPimpalkar 
Definitely! I'll will assign you to the issue!
