### ISSUE TITLE
[Bug]: Column span prop with percentage unit

### ISSUE THREAD

**Issue by JakeMetz8** [carbon-design-system/carbon#15223]
### Package

@carbon/react

### Browser

Chrome

### Package version

11.38.0

### React version

1.38.0

### Description

Pass a percent to the span property on the `Column`.

```
<column span="25%" />

// expected output
<div class="cds--col-span-50">

// actual output
<div class="cds--col-span-50%">
```

The span property isn't stripping the **%** suffix resulting in no styles being attached. % unit works fine when passed to breakpoint props (_sm_, _md_, etc) but doesn't work when span prop is utilized. Moreover, the type on span has to be a percent according to `ColumnSpanPercent` type

### Reproduction/example

https://stackblitz.com/edit/github-5bdwvv?file=src%2FApp.jsx

### Steps to reproduce

Create a grid with at least 1 column and pass `span="25%"` to column as a prop.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
I would like to take a look at this issue!

**Comment by guidari** [comment]
Awesome @kuri-sun !
I'll assign the issue to your user.
