### ISSUE TITLE
Components z-index not following Carbon Design System

### ISSUE THREAD

**Issue by idohu** [carbon-design-system/carbon#1523]
## Detailed description

> Describe in detail the issue you're having.
When using DataTable the batchActions header has z-index of 6000 which causes it to overlap the service header.
![image](https://user-images.githubusercontent.com/9638128/49421328-0d001900-f798-11e8-8991-e708e8f37b6d.png)

> Is this issue related to a specific component?
Not necessarily - According to the [layout map](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_layout.scss#L81-L90) there might be other components that are not following the [design system layout guidelines](http://www.carbondesignsystem.com/guidelines/layer/overview)

> What browser are you working in?
I'm using Chrome - but this will affect all browsers

> What version of the Carbon Design System are you using?
V9

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
I'm part of Certificate Manager team.

**Comment by joshblack** [comment]
Hi @idohu! 👋 Thanks for reporting this. Would you want to try submitting a PR with the fix? Should just be updating one line in order to fix this 🙂

**Comment by paschalidi** [comment]
@joshblack 👋  can I take this over ?

**Comment by paschalidi** [comment]
@idohu its my first time trying to reproduce an issue here. can you please explain how one can reproduce it?

**Comment by dakahn** [comment]
@idohu 👋 was this resolved, friend?

**Comment by tw15egan** [comment]
Closing this as it has been a few months without a response. If there is still a problem, feel free to reopen the issue with more steps to reproduce.
