### ISSUE TITLE
 Doc state that css--font-face is set to false but is set to true

### ISSUE THREAD

**Issue by besteman** [carbon-design-system/carbon#1524]
## Detailed description

The docs state that all variables are all set to false except for _css-font-face_ but in the _styles.scss_ it is set to true. The docs can be found [here](http://www.carbondesignsystem.com/getting-started/developers/vanilla#scss)

> These variables are used to configure which parts of the SCSS get compiled, where each variable controls a SCSS file of the same name. All variables are set to true by default, except for _css--font-face.scss

**Comment by alisonjoseph** [comment]
This will go live with next website deploy
