### ISSUE TITLE
[Toggle] change toggle content for headings and labels

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15240]
### Acceptance criteria

- As part of an a11y review, we should change the terminology for how we label parts of the Toggle component in the storybook example.
  - The Toggles label above the toggle should be called `Label` not Toggle element label.

<img width="608" alt="Frame 1872" src="https://github.com/user-attachments/assets/47ba821c-9baf-48d8-b92e-5f880b6d7160">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
This is just a storybook change. The code is right, just the words in storybook are wrong.

**Comment by mbgower** [comment]
I think the best way to get clarity on this is to have an anatomy section for the toggle.
There is (as far as I know) no real heading, although I guess a set of toggles could have a heading. What is called a heading here is actually the toggle's label. The label and the toggle control are sometimes aligned in rows, I believe.
What is called a label above is actually a text-version of the toggle's state (on or off).
