### ISSUE TITLE
[Bug]: Downshift replacing `id` prop in Dropdown

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#15241]
### Package

@carbon/react

### Package version

v1.42.0

### React version

18.02

### Description

The `id` from Dropdown is not being set as expected. In the storybook example we set an array of item with `ids`, but when you check in the DOM what's being rendered it's actually the `ids` from Downshift.

It should be this `id` to be rendered: https://github.com/carbon-design-system/carbon/blob/ab4ca8a2b6fbdc557ccd090567383cdeae838570/packages/react/src/components/Dropdown/Dropdown.stories.js#L56

`<li aria-disabled="false" aria-selected="true" id="downshift-:rb:-item-1" role="option" class="cds--list-box__menu-item cds--list-box__menu-item--active">...</li>`

Reported on slack: https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1700650953038419

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-dropdown--default

### Steps to reproduce

- Inspect the option inside the `Dropdown` component.
- Check the `id`

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
May I take a look at this issue? Thank you:)

**Comment by kuri-sun** [comment]
Hi @guidari ,
I have a question about this issue,
Currently <Dropdown> component `items` props accepts `string[]`, `number[]`, `object[]`, and etc.
So Should this behavior be happening only when a user passes down the `id` inside of the item object?
ThX!!!
