### ISSUE TITLE
[Feature Request]: Add basic tests for `slug` prop on components

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#15273]
### The problem

We should ensure the `slug` is being rendered properly in the components we have implemented it in

### The solution

We should have basic tests to check for the existence of the `slug` inside these components, as well as basic AVT and keyboard naviagtion tests.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by mattrosno** [comment]
@tw15egan given the slug will remain experimental for the foreseeable future, is this something that we want to do in phase 1 (12/15/23)?

**Comment by mattrosno** [comment]
@tw15egan @sstrubberg C4AI phase 2 milestone date is 2/23/24. If this won't get done by then, can we remove it from the phase 2 milestone?
