### ISSUE TITLE
Dividers in components: Work on Solutions and final specs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15286]
## Acceptance criteria
 - This issue is a follow-on to what came out of the [Audit](https://github.com/carbon-design-system/carbon/issues/14101).
- With the insights from the audit and research, propose new design specs of how to move forward with applying vertical dividers across our components.

---

#### Defining a rule
- From the audit and research findings we have decided to move forward with the approach that components should have vertical dividers between icons or sections in components when they are interactive (ex: they have background color changes)

#### Applying vertical dividers to components
- [x]  Layout all of the components that would need vertical dividers together in one view.
- [x] Show how the states of these components would work with the vertical dividers. (ex: do dividers disappear during hover and focus? do more appear in invalid or warning states?)
  - Do not include AI solutions for now, since this work is still WIP.
- [x] Make of note of what components need to be changed in code. (ex: changed spacing, added dividers, etc.)

#### In context examples
- [x] Show how some of these components with vertical dividers show up in one view in a product screen or in context example. (@laurenmrice will give you examples to work with)

-----

### Playback and finalize specs
- [x] Playback in a crit to Carbon deisgners and A11y rep
- [x] Align on a direction to move forward with

**Comment by alina-jacob-ibm** [comment]
Inferred Guidelines and Solutions based on the [Audit](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=50-23570&mode=design)

![Dividers in Carbon Components Changes](https://github.com/carbon-design-system/carbon/assets/148988115/33384249-70b7-4dbe-883b-edefdc9c00d1)

![Dividers in Carbon Components Guidelines](https://github.com/carbon-design-system/carbon/assets/148988115/e4eca4eb-b42c-4c7d-b387-9968301f5108)

![Specs for Dividers in Combobox and Filterable Multiselect](https://github.com/carbon-design-system/carbon/assets/148988115/024650f6-0adb-4841-a5d1-d78ca25abe12)

**Comment by alina-jacob-ibm** [comment]
https://github.com/carbon-design-system/carbon-design-kit/issues/745#issuecomment-1920568962

![Dividers in Carbon Components (Input fields)](https://github.com/carbon-design-system/carbon/assets/148988115/e4f4843c-f3d8-425a-8627-8e971fb03c85)
