### ISSUE TITLE
Bug: Data Table component not working with AngularJS Advanced Tags

### ISSUE THREAD

**Issue by hemanth-avs** [carbon-design-system/carbon#153]
## Overview

Data Table component not working with AngularJS Advanced Tag like ng-repeat-start / ng-repeat-start 
I do see component working fine with standard tags like ng-repeat

```gherkin
Feature: Data Table component
  As a Developer
  I want to Use Data Table component with AngularJS
  So that I can populate the Table with  Dynamic table content

```

# **Data Table Html + Angular JS = Working**

In Plunker, I implemented the use case.  Based on the Flag, I would like to use same HTML to have expandable and non expandable behavior.  
Plunker link has Datable Html and Input structure as well.

http://plnkr.co/edit/3iu9f2HHO4sfiY5gFj1y?p=preview

##  **Data Table Html + Angular JS + Carbon Design System Libraries - Not Working**

When the same Datable Html  used along with Carbon Design System Libraries, it is not working.

 Below is the output
![image](https://cloud.githubusercontent.com/assets/5846263/26756746/4dcbf2da-486f-11e7-84c8-6a4be61a3803.png)

**Comment by hemanth-avs** [comment]
I did try .refreshRows() but no luck

**Comment by asudoh** [comment]
The screenshot shows that the Angular template is not property bound to the data model, where carbon-components does nothing. You may want to try removing carbon-components stuffs from your template/application and see what happens.

**Comment by hemanth-avs** [comment]
I will check it
