### ISSUE TITLE
[Bug]: Module parse failed: Export 'Infinity' is not defined (2620:1241) |     WatsonHealthLaunchStudy_1.propTypes = iconPropTypes; | }

### ISSUE THREAD

**Issue by edumorlom** [carbon-design-system/carbon#15306]
### Package

@carbon/icons-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

11.31.0

### React version

18.2.0

### Description

After upgrading to 11.31.0, I now see the following error when doing `npm run dev`:

```
./src/app/Dashboard/layout.tsx
 ⨯ ./node_modules/@carbon/icons-react/es/generated/bucket-8.js
Module parse failed: Export 'Infinity' is not defined (2620:1241)
|     WatsonHealthLaunchStudy_1.propTypes = iconPropTypes;
| }
> export { IbmCloudPakIntegration, IbmCloudPakMantaAutomatedDataLineage, IbmCloudPakMulticloudMgmt, IbmCloudPakNetezza, IbmCloudPakNetworkAutomation, IbmCloudPakSecurity, IbmCloudPakSystem, IbmCloudPakWatsonAiops, IbmSecurity, IbmSecurityServices, IbmWatsonAssistant, IbmWatsonDiscovery, IbmWatsonKnowledgeCatalog, IbmWatsonKnowledgeStudio, IbmWatsonLanguageTranslator, IbmWatsonMachineLearning, IbmWatsonNaturalLanguageClassifier, IbmWatsonNaturalLanguageUnderstanding, IbmWatsonOpenscale, IbmWatsonOrders, IbmWatsonQuery, IbmWatsonSpeechToText, IbmWatsonStudio, IbmWatsonTextToSpeech, IbmWatsonToneAnalyzer, IbmWatsonxAssistant, IbmWatsonxCodeAssistant, IbmWatsonxCodeAssistantForZ, IbmWatsonxCodeAssistantForZRefactor, IbmWatsonxOrchestrate, IbmZCloudModStack, IbmZCloudProvisioning, IbmZEnvironmentsDevSecOps, IbmZOs, IbmZOsAiControlInterface, IbmZOsContainers, IbmZOsPackageManager, IbmZProcessorCapacityReference, IceAccretion, IceVision, IdManagement, Idea, Identification, Image, ImageCopy, ImageMedical, ImageReference, ImageSearch, ImageSearchAlt, ImageService, ImportExport, ImproveRelevance, InProgress, InProgressError, InProgressWarning, Incomplete, IncompleteCancel, IncompleteError, IncompleteWarning, IncreaseLevel, Industry, Infinity, Information, InformationDisabled, InformationFilled, InformationSquare, InformationSquareFilled, InfrastructureClassic, Insert, InsertPage, InsertSyntax, Inspection, InstanceBx, InstanceClassic, InstanceCx, InstanceMx, InstanceVirtual, Integration, IntentRequestActive, IntentRequestCreate, IntentRequestHeal, IntentRequestInactive, IntentRequestScaleIn, IntentRequestScaleOut, IntentRequestUninstall, IntentRequestUpgrade, Interactions, Intersect, IntrusionPrevention, InventoryManagement, IotConnect, IotPlatform, Ip, Iso, IsoFilled, IsoOutline, JoinFull, JoinInner, JoinLeft, JoinOuter, JoinRight, Jpg, JsError, Json, JsonReference, JumpLink, KeepDry, Keyboard, KeyboardOff, Kubernetes, KubernetesIpAddress, KubernetesPod, Label, Language, Laptop, Lasso, LassoPolygon, Launch, QID, WatsonHealthICa_2D, WatsonHealthImageAvailabilityLocal, WatsonHealthImageAvailabilityRetrieving, WatsonHealthImageAvailabilityUnavailable, WatsonHealthInteractiveSegmentationCursor, WatsonHealthLaunchStudy_1 };
| 

Import trace for requested module:
./node_modules/@carbon/icons-react/es/generated/bucket-8.js
./node_modules/@carbon/icons-react/es/index.js
```

### Reproduction/example

Usnure

### Steps to reproduce

Unsure

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by vasharma05** [comment]
Hi @edumorlom!
Is there any fix/ workaround brought up to resolve this issue? We at OpenMRS are also facing the same issue and is a blocker on our side.
Thanks!

CC: @ibacher @denniskigen

**Comment by edumorlom** [comment]
i was able to just downgrade to the previous version and everything works.

**Comment by edumorlom** [comment]
@denniskigen this works for me:

```├── @carbon/icons-react@11.30.1
├── @carbon/react@1.42.1
├── @types/carbon__icons-react@11.29.0
├── @types/node@20.10.1
├── @types/react-dom@18.2.17
├── @types/react@18.2.39
├── eslint-config-next@14.0.3
├── eslint@8.54.0
├── next@14.0.3
├── react-dom@18.2.0
├── react@18.2.0
├── sass@1.69.5
└── typescript@5.3.2
```

Make sure you delete node_modules, otherwise it won't work.

**Comment by Kynato** [comment]
Both newest and legacy
    ("@carbon/icons-react": "11.29.0",
    "@carbon/react": "1.42.1",)
versions doesn't work for me.
They worked for like an hour and then stopped. Can't fix it for a while now.

**Comment by tay1orjones** [comment]
Hi, we're having a hard time reproducing this. Could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/main/react/latest/react-18-vite/?file=src%2Findex.scss,src%2FApp.jsx&preset=node=) with your specific configuration, and post the link back here? It's hard to figure out exactly what could be going wrong without seeing the issue firsthand.

**Comment by Yaren-IT** [comment]
> Hi, we're having a hard time reproducing this. Could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/main/react/latest/react-18-vite/?file=src%2Findex.scss,src%2FApp.jsx&preset=node=) with your specific configuration, and post the link back here? It's hard to figure out exactly what could be going wrong without seeing the issue firsthand.

Hi, I have the same problem.
Yesterday I had this issue on another bug request of mine and so I have the basis to reproduce this in codesandbox.
I made a new repo for this bug and you can see the bug here:
https://codesandbox.io/p/github/Yaren-IT/carbon-nextjs-infinity/main

My current workaround with npm is to set overrides in package.json like this:
```json
,
  "overrides": {
    "@carbon/icons-react": "11.30.1"
  }
```

hth

**Comment by dbryan17** [comment]
@tay1orjones You can check the codesandbox. I have for this [issue](https://github.com/carbon-design-system/carbon/issues/15351). Currently showing this error. 
https://codesandbox.io/p/devbox/headermenu-issue-88wg4c?file=%2Fapp%2Fnavbar.js%3A26%2C47

**Comment by alisonjoseph** [comment]
Thanks for the reproductions, I'm also able to reproduce locally. I believe this may be related to adding the `Infinity` icon in this [PR](https://github.com/carbon-design-system/carbon/pull/15231). I think we need to rename it because `Infinity` is a global property.
https://www.w3schools.com/jsref/jsref_infinity.asp
