### ISSUE TITLE
Create design spec for AI `Progress indicator`

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15302]
Create a design spec for an AI flavor of progress indicator, incorporating the slug and aura gradient where appropriate. Design a solution for both light and dark themes.

**Comment by RichKummer** [comment]
[Figma design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1162%3A117461&mode=design&t=WkRI8iVXBee5iBRP-1)

![Image](https://github.com/carbon-design-system/carbon/assets/15643582/89f456c6-39cf-4e2f-acbc-3b3acfddc8a2)
