### ISSUE TITLE
♿ AVT3 ♿ Accordion - on activation of control focus is lost

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#1530]
User tested with latest version of JAWS 2018, Windows 7, Chrome latest version

## Detailed description
"Expand and collapse works and speaks, but when activating any of the buttons the focus moves away from the control."

**Comment by asudoh** [comment]
Hi @dakahn tried https://deploy-preview-1679--the-carbon-components.netlify.com/ that contains accordion code from latest `master`, it appears that the problem you mentioned doesn't reproduce there. Please don't hesitate to speak up if you see otherwise - Thanks!

**Comment by dakahn** [comment]
Thanks for checking back in on this. I'll line up some user testing and see if this has resolved itself 🤞🏼

**Comment by tombabinszki** [comment]
Windows 7
JAWS 19.1810.64
Chrome: 71.0.3578.98 (Official Build) (64-bit)
Keyboard navigation is working properly.

**Comment by dakahn** [comment]
Great! Looks like we can close this. Happy to re-open if I need to though. 🏄‍♀️
