### ISSUE TITLE
Review and update the content for Accessibility and Accessibility status tabs

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#15326]
Objective: Ensure the information is correct and update if needed for A11y content in Accessibility and Accessibility status tabs (in the Prototype section)

Figma file: https://www.figma.com/file/tNo5wiP7cBMAMOWMkJLMHq/A11y-Component-Design?type=design&node-id=775-47381&mode=design

**Comment by tay1orjones** [comment]
I made some edits over in https://github.com/carbon-design-system/carbon-website/pull/3866 for this. I think it covers everything, but we can discuss further next week to make sure it all sounds good and I didn't miss anything.
