### ISSUE TITLE
[Bug]: Accordion items with default open state have a wrong height

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#15340]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.44.0

### React version

v18.2.0

### Description

When `AccordionItems` with long content have `open` as the default state, their height is messed up.

![image](https://github.com/carbon-design-system/carbon/assets/1809476/8203f553-460e-4df3-bda9-f29173c6da39)

Can be solved by adding this:
```
.cds--accordion__item--active {
    .cds--accordion__wrapper {
      max-block-size: fit-content;
    }
  }
```

### Reproduction/example

https://stackblitz.com/edit/github-aoabhq?file=package.json,src%2FApp.jsx

### Steps to reproduce

1. Create an `Accordion` with many AccordionItem elements
2. Use a long content
3. Set `open` as default state for each `AccordionItem`

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Thanks for catching that @marcellobarile, and providing the fix! Just pushed up the changes.
