### ISSUE TITLE
Workflow to update `design-language-website` is failing

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#15356]
Investigate failute and update workflow to ensure IDL site is getting latest version of Carbon.

https://github.com/carbon-design-system/carbon/actions/workflows/deploy-packages.yml

https://github.com/carbon-design-system/carbon/actions/runs/7132036319/job/19421756943
```
yarn upgrade v1.22.21
[1/5] Validating package.json...
error design-language-website@1.0.1: The engine "node" is incompatible with this module. Expected version "18.x". Got "20.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by guidari** [comment]
FYI @alisonjoseph 
PR to fix it: https://github.com/carbon-design-system/design-language-website/pull/1352

**Comment by guidari** [comment]
Release for v11.60.0 working as expected
![Screenshot 2024-06-20 at 15 06 07](https://github.com/carbon-design-system/carbon/assets/52183462/186acddc-568c-44e9-8b91-b47c5769de7c)
