### ISSUE TITLE
[Bug]: @Carbon/react not working properly with latest Remix version

### ISSUE THREAD

**Issue by fahadahmed** [carbon-design-system/carbon#15352]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.44.0

### React version

18.2.0

### Description

Cannot use @carbon/react package within a remix app after setting up sass. We get a message for unable to find a stylesheet to import.
![Screenshot 2023-12-08 at 5 09 59 pm](https://github.com/carbon-design-system/carbon/assets/1190340/e0ac7bb1-cf41-4d04-98d5-bd5a9aa827a7)

### Reproduction/example

https://stackblitz.com/~/github.com/fahadahmed/fhdamd-1-remix-dynamic-form

### Steps to reproduce

- Create a new repository for remix using the command `pnpm create remix <repository-name>`
- add and configure sass
- add `@carbon/react` to the project
- create a new `styles/ globals.scss` file and setup the file to use the styles from @carbon via `use '@carbon/react'`

the dev command to generate css files for sass styles for carbon will fail.
![Screenshot 2023-12-08 at 5 09 59 pm](https://github.com/carbon-design-system/carbon/assets/1190340/e0ac7bb1-cf41-4d04-98d5-bd5a9aa827a7)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by fahadahmed** [comment]
Here is an example setup that does work but that is for an older version of remix and @carbon/react. https://stackblitz.com/edit/remix-carbon?file=app%2Froot.tsx

Based on the issue above, it seems that I need to install `@carbon/grid` npm package which technically I shouldn't need to if I am installing `@carbon/react` as a whole.

**Comment by tay1orjones** [comment]
Hey, thanks for reporting this. Updating the working stackblitz to the latest version of `@carbon/react` shows it still working. https://stackblitz.com/edit/remix-carbon-a8jujb?file=package.json

The initial/broken repro you linked doesn't have a .scss in it. Could you provide a broken reproduction of the issue? You're correct you shouldn't need to install `@carbon/grid` to use styles in `@carbon/react`. It includes all the necessary dependencies.

**Comment by fahadahmed** [comment]
Hey @tay1orjones ,

thanks for looking into this. This is what I am getting when I am trying to run the sass command to generate the styles and trying to import the `@carbon/react` package within the `global.scss` file.

![Screenshot 2024-01-07 at 8 14 02 pm](https://github.com/carbon-design-system/carbon/assets/1190340/4c515702-2ae6-47be-9a22-085a431e1aca)

![Screenshot 2024-01-07 at 8 12 36 pm](https://github.com/carbon-design-system/carbon/assets/1190340/460424b3-858b-41b0-a087-ed17f9a5d7d5)

**Comment by tay1orjones** [comment]
@fahadahmed I think you're running into this issue: https://github.com/sass/dart-sass/issues/1765, specifically https://github.com/sass/dart-sass/issues/1765#issuecomment-1699525576 

pnpm symlinks dependencies, so the `--load-path` you have defined in your example doesn't contain the source for the files sass is looking for/needing, like `@carbon/grid`. Based on the comment I linked above, adding another `--load-path` could solve it.

```
 --load-path=node_modules --load-path=node_modules/.pnpm/@carbon+grid@11.21.0/node_modules
```

You might need a load path entry for each package used by `@carbon/react` that loads sass styling.

**Comment by tay1orjones** [comment]
I think [`public-hoist-pattern`](https://pnpm.io/npmrc#public-hoist-pattern) could also be used to avoid the issue altogether. Would be something like `public-hoist-pattern[]=*@carbon*` I think. That should put these dependencies in `node_modules` so the single `--load-path=node_modules` would work.

Try it out and let us know how it goes, this would be a good thing to document if we can validate this fixes your issue.

**Comment by anneyxa** [comment]
Do you know if there's any workaround for this if I'm using `scss` package with Rollup? Also cannot move to Carbon 11 because of this.

Sorry but I'm not using command line to load sass styles, so I don't quite understand how to apply it in Rollup config. I.e. using 'rollup-plugin-scss' or 'rollup-plugin-sass'.

**Comment by anneyxa** [comment]
Okay I've updated all my packages in `package.json` (`npm outdated` and `npm update` command) - and it seems to be working with following imports (+ same rollup config as in above comment):
```
@use '@carbon/react/scss/spacing' as *;
@use '@carbon/react/scss/type' as *;
```

Surprisingly, it still doesn't work when I try with `@use '@carbon/react';`, but the two imports above are enough for me right now.

If anyone else is struggling with it, I'd suggest upgrading all possible packages and try to import specific carbon packages in scss file instead of `@use '@carbon/react';`

**Comment by anneyxa** [comment]
Okay I've updated all my packages in `package.json` (`npm outdated` and `npm update` command) - and it seems to be working right now. So - I guess nevermind. ;)
