### ISSUE TITLE
Experimental components: Update final error states

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1535]
## Final error states for experimental components
Sketch file: https://ibm.ent.box.com/file/362479776343
![Artboard Copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/b2847f2b-a24f-496e-aaac-c7b3efab854a)

![Artboard Copy 2.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/97667355-2003-4ad9-9c6b-f38feb249f1d)

**Comment by laurenmrice** [comment]
@IBM/carbon-developers


(Linked to previous issue #1390 for more information)

**Comment by emyarod** [comment]
tracking progress here:

* [x] dropdown https://github.com/IBM/carbon-components/pull/1733
* [x] file uploader (may want to combine this with https://github.com/IBM/carbon-components-react/pull/1105 when we have the opportunity to reopen that PR) https://github.com/IBM/carbon-components/pull/1772
* [x] text input https://github.com/IBM/carbon-components/pull/1074 https://github.com/IBM/carbon-components/pull/1735
* [x] number input https://github.com/IBM/carbon-components/issues/1621
* [ ] form (this is probably just a combination of the other ones)
* [x] progress indicator https://github.com/IBM/carbon-components/pull/1506
* [x] select https://github.com/IBM/carbon-components/pull/1756

**Comment by asudoh** [comment]
Closing as most major issues reported here has been addressed and the remainders are tracked in separate issues (e.g. #1885). Anybody please don't hesitate to speak up in case this should be kept open. Thanks!
