### ISSUE TITLE
[Bug]: Accordion element covering other parts of page even when closed leaving below elements not clickable

### ISSUE THREAD

**Issue by IsobelMGoddard** [carbon-design-system/carbon#15357]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.44.0

### React version

v18.2.0

### Description

Accordion items are covering the rest of our UI even when closed preventing users from clicking on menu tiles in our product - issue does not occur with same code in v1.42.1

https://github.com/carbon-design-system/carbon/assets/44289949/e401db4f-f997-4a91-a9e2-119824f98ada

### Reproduction/example

https://stackblitz.com/edit/github-uwvc4t?file=src%2FApp.jsx

### Steps to reproduce

Inspect paragraph of text outside of accordion and under where the expanded accordion would be coveringv- it selects the paragraph of text within the accordion

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM API Connect

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Will be fixed via https://github.com/carbon-design-system/carbon/pull/15423
