### ISSUE TITLE
[Bug]: Inline dropdown has bottom border in readOnly variant

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#15367]
### Package

@carbon/react

### Package version

1.45.0

### Description

Usually, inline dropdown don't have a bottom border. However, when they're marked as `readOnly`, a bottom border appears. This emphasizes the readonly dropdown more than the interactive one, leading to a confusing visual hierarchy.

### Screenshots

<img width="229" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/98217890-7c0b-4e00-befd-2d2d4d3454be">

### Steps to reproduce

https://stackblitz.com/edit/github-jy2sgy?file=src%2FApp.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by SatyaPrakashPalai** [comment]
Hello maintainers, Could you please confirm if this issue currently assigned or available for me to take on?
