### ISSUE TITLE
How to change width for Slider with two handles?

### ISSUE THREAD

**Issue by VikaBondareva** [carbon-design-system/carbon#15379]
![Untitled](https://github.com/carbon-design-system/carbon-website/assets/26714345/16313495-6ec2-40b6-9239-3f9fd4f6ca7d)

## Summary

How to change the width of a slider to display text inputs with a fixed width of the parent container?

**Comment by laurenmrice** [comment]
@VikaBondareva Is the screenshot you are sharing above a real use case, or is this a stress test against the two handle slider? If this is a real use case, we would recommend using a text input instead of a range slider if there is a very small min in contrast to a very large max.
