### ISSUE TITLE
[Bug]: How to change width for Slider with two handles?

### ISSUE THREAD

**Issue by VikaBondareva** [carbon-design-system/carbon#15374]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.45.0

### Description

How to change the width of a slider to display text inputs with a fixed width of the parent container?

### Screenshots

![image](https://github.com/carbon-design-system/carbon/assets/26714345/c6db5824-71f1-48ee-b8a1-b77e486f2fb4)

### Steps to reproduce

I have a fixed lock container and a slider (with two handles) with inputs. So I need to change the slider width to not hide the elements. https://react.carbondesignsystem.com/?path=/story/components-slider--two-handle-slider 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi, could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/main/react/latest/react-18-vite/?file=src%2Findex.scss,src%2FApp.jsx&preset=node=), and post the link back here? It's hard to know exactly what's going wrong without seeing the issue firsthand.
