### ISSUE TITLE
[Bug]: AccordionItem - content height is not being set on initial open

### ISSUE THREAD

**Issue by joker23** [carbon-design-system/carbon#15388]
### Package

@carbon/react

### Browser

Chrome

### Package version

11.44.0

### React version

18.x.x

### Description

When you set an accordion item to initially `open`, the accordion item will not expand to the height of the content.

This issues seems to be caused by https://github.com/carbon-design-system/carbon/pull/14776 where the height of the content is only set after the user closes and reopens the accordion item.

### Reproduction/example

https://stackblitz.com/edit/github-zc3uap-nxnkth?file=src%2FApp.jsx,package.json

### Steps to reproduce

Create an accordion with an accordion item set to `open` as the default state eg
```
<Accordion>
        <AccordionItem title="opened tab" open>
....
```

Make sure the content inside the accordion item has multiple lines

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joker23** [comment]
One "safer" workaround here is to add:
```
.cds--accordion__item--active .cds--accordion__wrapper {
  max-block-size: initial;
}
```
to override the style in https://github.com/carbon-design-system/carbon/blob/36ec3822ecee9458dd41ccd986463fa406337db5/packages/styles/scss/components/accordion/_accordion.scss#L149 if and only if the accordion item is active. Thoughts?

**Comment by tw15egan** [comment]
I believe this was fixed in https://github.com/carbon-design-system/carbon/pull/15344, let me know if that is not the case 👍🏻

**Comment by joker23** [comment]
ah that seems right! We'll wait for a new version then, thanks!
