### ISSUE TITLE
[Question]: Type mismatch in secondaryButtons prop in Modal component

### ISSUE THREAD

**Issue by htndev** [carbon-design-system/carbon#15392]
### Question for Carbon

Hi. I've encountered an issue with type mismatch using the `Modal` component. The `Modal` component has a `secondaryButtons` prop that accepts string based on its TypeScript annotation. However, under the hood, it treats the prop as a node. I've shared all annotations below.
The `secondaryButtons` prop: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Modal/Modal.tsx#L185C31-L185C31
The `ModalSecondaryButton` type: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Modal/Modal.tsx#L34
The `secondaryButtons` actual validation: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Modal/Modal.tsx#L721C8-L721C8

Therefore, I have a reasonable question it is an intentional change or just a mistake?
Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@htndev Hey! Yep, looks like it was probably just an oversight. A PR to correct it would be welcome if you're interested

**Comment by htndev** [comment]
@tay1orjones Thanks for the response! Could you tell me, what type exactly should be there? I can prepare a fix for that.

**Comment by tay1orjones** [comment]
@htndev Probably just `React.ReactNode`, I think? Though maybe ideally it would be `string | React.ReactNode` to inform users the easiest thing to do is just pass a string. Ultimately they can still pass an entire custom component if they'd like. It's eventually just passed as a child of `Button`.

https://github.com/carbon-design-system/carbon/blob/384f35bc7f2673e852e288ddacc26262a3ba28bd/packages/react/src/components/Modal/Modal.tsx#L492-L511

**Comment by htndev** [comment]
@tay1orjones [The fix PR](https://github.com/carbon-design-system/carbon/pull/15519) for this issue has been created.
