### ISSUE TITLE
[Bug]: The left navigation icon of the TabList component is rendering correctly

### ISSUE THREAD

**Issue by petermoogk** [carbon-design-system/carbon#15402]
### Package

@carbon/react

### Browser

Firefox

### Package version

v9.6.5

### React version

v17.0.2

### Description

I'm using the TabList component.  When the screen is too small there are left and right navigation icons that appear to navigate through the tabs. The right navigation tab seems to render correctly.  However, the left navigation icon gets mixed in with the tab text.  This make the icon difficult to see and to click on.  I was able to work around this issue by overriding the .cds--tab--overflow-nav-button--previous class and setting the z-index to 100.  I have included an example of the code I'm using to reproduce this issue.

### Reproduction/example

NA

### Steps to reproduce

Run the following code:
import { Tabs, Tab, TabList, TabPanel, TabPanels } from "@carbon/react";
import { Help } from "@carbon/icons-react";
import styled from "styled-components";

const HelpIcon = (props: {}) => {
  return <Help size="16" onClick={() => console.log("Clicked")} />;
};

//const StyledTabList = styled(TabList)`
//  .cds--tab--overflow-nav-button--previous {
//    z-index: 100;
//  }
`

const TestTabs = (props: {}) => {

  return (
    <Tabs>
      <TabList aria-label="">
        <Tab renderIcon={() => <HelpIcon />}>Test panel 1</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 2</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 3</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 4</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 5</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 6</Tab>
        <Tab renderIcon={() => <HelpIcon />}>Test panel 7</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <div>Panel1</div>
        </TabPanel>
        <TabPanel>
          <div>Panel2</div>
        </TabPanel>
        <TabPanel>
          <div>Panel3</div>
        </TabPanel>
        <TabPanel>
          <div>Panel4</div>
        </TabPanel>
        <TabPanel>
          <div>Panel5</div>
        </TabPanel>
        <TabPanel>
          <div>Panel6</div>
        </TabPanel>
        <TabPanel>
          <div>Panel7</div>
        </TabPanel>
      </TabPanels>
    </Tabs>
  );
};

export default TestTabs;
 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Web app

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @petermoogk can you please provide a reproduction via [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=README.md) so we can take a look?
