### ISSUE TITLE
[Bug]: NumberInput with hideSteppers set as true adds unnecessary padding when in invalid state

### ISSUE THREAD

**Issue by Tomahaawk** [carbon-design-system/carbon#15414]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.45.0

### React version

16.13.1

### Description

When using a `NumberInput` with `hideSteppers` set as `true` and this input becomes invalid, it adds a padding that hides the input value if the width of the input is not large enough.

![image](https://github.com/carbon-design-system/carbon/assets/12561157/d741a1c6-280e-4ca8-910b-a0142693313b)

### Reproduction/example

https://stackblitz.com/edit/github-cldk9i-yzpm36?file=src%2FApp.jsx

### Steps to reproduce

Create a NumberInput
Set its width to a small value, like 100px
Set it as invalid
Input value should be visible but end up being hidden because of the padding

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM RPA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by raphyluke** [comment]
Trying to patch the bug actually.

To solve the problem temporarly, please add to your component : style={{paddingInlineEnd: '10px'}}

```js
import { NumberInput } from '@carbon/react';
import "./style.sass"
export default function App() {
  return (
    <div style={{ margin: '15px', width: '100px' }}>
      <NumberInput
        invalid
        invalidText="too much!"
        label="Amount"
        style={{paddingInlineEnd: '10px'}}
      />
    </div>
  );
}
```

**Comment by raphyluke** [comment]
Problem detected : The problem is actually the css of the invalid property, will patch it soon.

**Comment by raphyluke** [comment]
Full report : 

The input was like this before
![image_2023-12-18_183825308](https://github.com/carbon-design-system/carbon/assets/82550120/9eeceea6-6f43-4f15-a07b-e8848fdaab17)

Right now it will be like this :
![image_2023-12-18_183903376](https://github.com/carbon-design-system/carbon/assets/82550120/8bb666e0-4dea-44ee-8e62-2ea71d009061)

Changes did on styles/scss/components/number-input/_number-input.scss:91

Please note that it seems that the bug appeared only with invalid property and container under 150px and that the natural min-width of the NumberInput is 150px, which mean that you will have bug under that container size.

**Comment by Tomahaawk** [comment]
Problem still happens on 150px, I guess it will depend on number size. In my specific case the field max value is 1000.
I expected the padding to have a lower value when `hideSteppers` is true, if possible. Visually it looks like there is a lot of space available and the value is cutoff. 
I'll override it for now like you suggested.

![image](https://github.com/carbon-design-system/carbon/assets/12561157/2e7b8396-8c67-4367-ae26-d43988e7fda5)

**Comment by raphyluke** [comment]
My patch will patch even 150px look : 
![image](https://github.com/carbon-design-system/carbon/assets/82550120/51d01fd2-c903-4e0e-b419-d640b8367eaa)
