### ISSUE TITLE
[Bug]: IBM Telemetry postinstall script breaking CI on OpenShift, Jenkins

### ISSUE THREAD

**Issue by jharvey10** [carbon-design-system/carbon#15426]
### Package

`@carbon/react`

### Package version

v1.46.0, eventual carbon v10 release with telemetry onboarding

### React version

n/a

### Description

When using npx to install @ibm/telemetry-js in certain CI environments such as Jenkins and OpenShift, or when working with a private package manager (such as Artifactory), the IBM Telemetry installation and execution can fail, blocking dependency installation.

### Steps to reproduce

install `@carbon/react` in thse environments. Observe the install command fails due to @carbon/react's postinstall script.

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

IBM Telemetry

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment]
Fixed in next tag: https://www.npmjs.com/package/@carbon/react/v/1.46.1 , will be promoted to latest on 12/19
