### ISSUE TITLE
[Bug]: Carbon Components: Radio button centered when width differs from default

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon#15436]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.45.0

### Description

If you set the width of a radio button to 100%, instead of growing the label to fill the new space, it becomes centered.
This is important for example if you want to highlight the line of the selected option. Also, in my case using web-components, I want to have a complex label and I need the whole width.
The behavior with the checkbox is the expected.

### Screenshots

![Captura de pantalla 2023-12-21 a las 11 53 59](https://github.com/carbon-design-system/carbon/assets/4138279/028e5f64-0c25-44f2-9548-ba8380a38fee)

### Steps to reproduce

Create a radio button and change the width to 100%.

https://stackblitz.com/edit/github-81xkqc-kqlub8?file=src%2FApp.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abdonrd** [comment]
@tw15egan I see you self-ssigned here. Any ETA to fix it? Thanks! 🙏

**Comment by tw15egan** [comment]
@abdonrd just pushed up a fix [here](https://github.com/carbon-design-system/carbon/pull/15514)
