### ISSUE TITLE
[Bug]: Accordion with attribute open don't open content

### ISSUE THREAD

**Issue by PabloAznarez** [carbon-design-system/carbon#15438]
### Package

carbon-components

### Browser

Chrome

### Package version

2.0.1

### Description

When I add the open attribute to the accordion item the content does not expand correctly

### Reproduction/example

https://jsfiddle.net/pasblin/4s9tpgum/5/

### Steps to reproduce

See in reproduccion example

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
hi @PabloAznarez, This is @kuri-sun from the other issue!
If you report this issue in that repository, I will be so happy to work on this issue!
Thanks! 🎄

**Comment by guidari** [comment]
Hey @PabloAznarez 
I'll close the issue in this repo. 

Feel free to open an issue in the [carbon-for-ibm-dotcom](https://github.com/carbon-design-system/carbon-for-ibm-dotcom)
