### ISSUE TITLE
[Bug]: SwitcherItem types. "onClick" prop does not exist

### ISSUE THREAD

**Issue by amercury** [carbon-design-system/carbon#15440]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

v1.45.0

### React version

v18

### Description

Since I updated my carbon/react package from ver. 1.40.0 to ver. 1.45.0, typescript started complaining about the "onClick" prop in the SwitcherItem component. 

### Reproduction/example

https://codesandbox.io/p/github/Yaren-IT/carbon-nextjs-sidenav/csb-5mffqr/draft/inspiring-poincare?file=%2Fapp%2Fpage.tsx%3A24%2C26

### Steps to reproduce

![Screenshot 2023-12-22 at 11 41 19](https://github.com/carbon-design-system/carbon/assets/17834588/5912f80e-15fa-49a2-ad19-bbbb8e694e45)

1. open Codesandbox
2. open page.tsx
3. you can find typescript complaining on lines 37 and 44

The error message is 

> Type '{ children: string; key: number; "aria-label": string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & (SwitcherItemProps & RefAttributes<ElementType<any, keyof IntrinsicElements>>)'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & SwitcherItemWithAriaLabel & RefAttributes<ElementType<any, keyof IntrinsicElements>>'.typescript(2322)

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by amercury** [comment]
I can fix it

**Comment by guidari** [comment]
@amercury Feel free to open a fix! We appreciate it

**Comment by guidari** [comment]
> I can fix it

@amercury  Feel free to open a fix! We appreciate it
