### ISSUE TITLE
[a11y]: datatable: The tabbable element's role 'none' is not a widget role

### ISSUE THREAD

**Issue by charis24** [carbon-design-system/carbon#15448]
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

v1.46.0

### React version

v18.2.0

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

Issue : Carbon React DataTable component

In DataTable component , if the table is scrollable then it has tabindex '0' else tabindex is not present. If tabindex is 0 then appropriate role has to be specified

![image](https://github.com/carbon-design-system/carbon/assets/66507461/17f5b808-85d1-48d9-8f14-2641c6a0a473)

![image](https://github.com/carbon-design-system/carbon/assets/66507461/2ce7d05e-3fd0-4872-8c8e-35463503351c)

### Steps to reproduce

Go to https://dev.console.test.cloud.ibm.com/
Go to VPC Infrastructure service
Go to any page with table and table needs to be horizontally scrollable
For eg:
https://dev.console.test.cloud.ibm.com/vpc-ext/compute/sshKeys
https://dev.console.test.cloud.ibm.com/vpc-ext/network/privatePathServices

About this requirement

[4.1.2 Name, Role, Value](https://www.ibm.com/able/requirements/requirements/#4_1_2)
[ARIA specification - Widget role definition](https://www.w3.org/TR/wai-aria-1.2/#widget)
[CSS overflow:](https://www.w3schools.com/css/css_overflow.asp)
[Unit test - check tab order](https://www.ibm.com/able/toolkit/develop/considerations/unit-testing/#check-tab-order)
[Unit test - confirm component keyboard interaction](https://www.ibm.com/able/toolkit/develop/considerations/unit-testing/#confirm-component-keyboard-interaction)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
Can you provide a simplified reproduction in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2Findex.scss)?

**Comment by tay1orjones** [comment]
Can't repro
