### ISSUE TITLE
[Bug]: `FluidDropdownSkeleton` `className` is being added to wrong element

### ISSUE THREAD

**Issue by ind1go** [carbon-design-system/carbon#15442]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.46.1

### React version

v18.2.0

### Description

I'm using `FluidDropdown` in a `FluidForm`, and it's in a `flex` layout where I'd like it to grow equally with its peers to fill the available width in the row. This is working well, because I can apply styles via a `className` to the `FluidDropdown` and it gets put on the top-level DOM element of the dropdown i.e. the one that also has `cds--dropdown__wrapper cds--list-box__wrapper cds--list-box__wrapper--fluid`.

While the data for the dropdown is loading I'm using a `FluidDropdownSkeleton` but this is failing to grow equally with its peers because the styles are not applied to the right place, but to a child element.

For demonstration here's the moment where one dropdown has loaded but not the other. Note that `big-input` is applied at the top level to the top one (`FluidDropdown`), but applied at the second level of the bottom one (`FluidDropdownSkeleton`):

<img width="674" alt="Snapshot of DOM when one dropdown has loaded but not the other" src="https://github.com/carbon-design-system/carbon/assets/1038350/bd2dd069-021f-45cd-993c-ac3799ab7d2b">

### Reproduction/example

https://stackblitz.com/edit/github-tymoau?file=src%2FApp.jsx

### Steps to reproduce

1. Use a `FluidDropdownSkeleton`.
1. Apply styles to the `FluidDropdownSkeleton` via `className` to influence its position in its parent, such as `flex-grow` or `flex-basis`.
1. Notice that the `FluidDropdownSkeleton` does not lay out as expected because the styles are not applied at the top level of the `FluidDropdownSkeleton`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hi @ind1go!
Thanks for the report! I will take a look at this issue ASAP! 
Thank you! 🎅 🎄
