### ISSUE TITLE
[Bug]: slider pointer styles

### ISSUE THREAD

**Issue by PabloAznarez** [carbon-design-system/carbon#15441]
### Package

carbon-components

### Browser

Chrome

### Package version

2.0.1

### Description

Pointer styles are not sowing correctly the size of pointer

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-slider--default

### Steps to reproduce

not steps needed

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hi @PabloAznarez!
Thank you for reporting! I will take a look at this one! 👍

**Comment by kuri-sun** [comment]
hi @PabloAznarez, 
web-component library seems like migrated to [this repo](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues)!
Maybe you can report this issue there!
Thanks! 🎅

**Comment by PabloAznarez** [comment]
i do it now thx!

**Comment by guidari** [comment]
I'll close this issue in this repo

New issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11272
