### ISSUE TITLE
[Bug]: IconButtons have reiterate classNames in a button HTML element.

### ISSUE THREAD

**Issue by harukikuri** [carbon-design-system/carbon#15459]
### Package

@carbon/react

### Browser

Chrome

### Package version

^1.46.1

### Description

Icon buttons have duplicate classNames in their button HTML element. (the picture below)
In this example, this IconButton's className is `"cds--btn--icon-only cds--btn cds--btn--primary cds--btn-
-icon-only cds--btn cds--btn--primary"`.
As you can see, we iterating className twice.

![249D1C93-9E44-4C2E-9630-F0555CF90CC4_1_201_a](https://github.com/carbon-design-system/carbon/assets/62743644/b67d304e-f714-438d-a3a1-69981b461396)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-button--icon-button

### Steps to reproduce

Go to the storybook, we will see this example that I attached in the description.
https://react.carbondesignsystem.com/?path=/story/components-button--icon-button

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hi! I am going to work on this issue, Thank you!

**Comment by tay1orjones** [comment]
My guess is this is because there's a circular dependency - Button depends on IconButton and IconButton depends on Button. There's probably a way to intelligently de-dupe these in these situations. Would appreciate a PR for this one if you're up for it!

**Comment by kuri-sun** [comment]
@tay1orjones I will give it a shot for it! Thank you!
