### ISSUE TITLE
[Bug]: Wrong alignment with button icon only and danger--ghost kind

### ISSUE THREAD

**Issue by migatt** [carbon-design-system/carbon#15452]
### Package

@carbon/react

### Browser

Safari, Firefox, Edge

### Package version

"^1.46.1"

### React version

"^18.2.0"

### Description

The icon is misplaced for buttons with icon only and `danger--ghost` kind. The alignment should be the same as for the other kinds.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=kind:danger--ghost

### Steps to reproduce

See storybook example https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=kind:danger--ghost

Set the kind to `danger-ghost`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hello @migatt, 
I will work on this issue! Thank you!

**Comment by kuri-sun** [comment]
Hello maintainers,

I want to ask a question about this issue, I found a different CSS between the `danger-ghost` icon button and other icon buttons, which is creating this wrong alignment for the `danger-ghost` icon button.
https://github.com/carbon-design-system/carbon/blob/3f70e1dea

This code makes padding on the left side of the `danger-ghost` icon button.
![Screenshot 2023-12-31 at 12 50 01 PM](https://github.com/carbon-design-system/carbon/assets/62743644/cc2abfc0-66e1-4b2b-91e7-d30a97589b05)
![Screenshot 2023-12-31 at 12 40 08 PM](https://github.com/carbon-design-system/carbon/assets/62743644/e71d0990-b916-4109-b2ec-b67900183ac1)
b402402dfb18dcc3ae4c7057818ab82/packages/styles/scss/components/button/_button.scss#L280-L282

After I removed these lines of code, I successfully saw the same CSS as other icon buttons. But it seems like some intention behind that, but I could not figure that out. So, could you assist me in understanding these lines of code? 
Thank you! ❤️

**Comment by tw15egan** [comment]
@laurenmrice, is it allowed to have an icon-only ghost danger button?

**Comment by laurenmrice** [comment]
@tw15egan We do not allow having an icon-only for the danger button.

**Comment by tw15egan** [comment]
Thanks for clarifying! @kuri-sun, thanks for your initiative, but this is working as expected and is not an allowed variant. Going to close this as not planned.
