### ISSUE TITLE
[Bug]: Bug in UI Shell SideNav

### ISSUE THREAD

**Issue by migatt** [carbon-design-system/carbon#15450]
### Package

@carbon/react

### Browser

Safari, Firefox, Edge

### Package version

"^1.46.1"

### React version

"^18.2.0"

### Description

The SideNav component exhibits unusual behavior. When I open the example using a desktop viewport, the navigational submenus cannot be opened. However, when I decrease the viewport size to hide the navigation behind the burger menu, the submenus can be opened. This behavior persists even if I reset the viewport to its initial value where the problem initially occurred. However, upon reloading the page, the problem reoccurs.

### Reproduction/example

Demo Story in React Storybook https://react.carbondesignsystem.com/iframe.html?viewMode=story&id=components-ui-shell-header--header-w-navigation-actions-and-side-nav&args=

### Steps to reproduce

1. Open the storybook example https://react.carbondesignsystem.com/iframe.html?viewMode=story&id=components-ui-shell-header--header-w-navigation-actions-and-side-nav&args=
3. Verify that the submenus cannot be opened.
5. Use your browser's developer tools to set viewport to a width of about 800px. Now the submenus should be openable.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @migatt!
This fix was delivered in this [PR](https://github.com/carbon-design-system/carbon/pull/15349). It will be live on the next release in Jan 04, 2024.

Demo: https://deploy-preview-15349--v11-carbon-react.netlify.app/?path=/story/components-ui-shell-header--header-w-navigation-actions-and-side-nav

**Comment by migatt** [comment]
Great. Thank you very much, @guidari! The PR was already merged, so I could not find the corresponding issue.
