### ISSUE TITLE
Update V10 Experimental Components with correct type tokens from @carbon/type

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1546]
Type tokens weren't finalized when we started building components. All experimental components will need to be updated.

Type tokens can be found here
https://next.carbondesignsystem.com/guidelines/typography/productive

**Comment by asudoh** [comment]
@joshblack Any updates? Thanks!

**Comment by joshblack** [comment]
Still working through namespace updates. This is my task this week though for integration 👍
