### ISSUE TITLE
Create design spec for `ProgressIndicator` AI enhancements

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#15467]

**Comment by mattrosno** [comment]
@aagonzales can you triage to make sure this enhancement should be done (accepted)?

**Comment by aagonzales** [comment]
@mattrosno this is a duplicate issue, I made some design issues before the holidays.
Here's the one Rich has been working from: https://github.com/carbon-design-system/carbon/issues/15302

**Comment by mattrosno** [comment]
Duplicate
