### ISSUE TITLE
[Selectable Components: Structured List] Dev Implementation

### ISSUE THREAD

**Issue by Kritvi-bhatia** [carbon-design-system/carbon#15479]
## Acceptance criteria

- [x] Update the Structure List with the below changes
- [x] By default, no option will be preselected. 

[Final design solution](https://github.com/carbon-design-system/carbon/issues/14766#issuecomment-1874852921)

----

`_Radio button items will not be preselected by default_`

### Specs
_Here are the updates:_
> Both icon placements, i.e., the proposed icon on the left and the current icon on the right, will coexist for now. The proposed placement (icon on the left) will be placed under a feature flag. [Figma file solution](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=548-4530&mode=design&t=K)
> <img width="1883" alt="Without Background_icon on right" src="https://github.com/carbon-design-system/carbon/assets/43969356/34d81181-b354-44a6-af35-907eafbf503a">
> <img width="1883" alt="without background icon left" src="https://github.com/carbon-design-system/carbon/assets/43969356/19ec59b8-4cad-4d01-be1d-93b25a596543">

---

> Additionally, we need to support an option for structured list when it has a a background applied. This is how the states look when there is a background applied to the structured list. [Figma file solution](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=548-4530&mode=design&t=KpyfeZDgqaFCYOZu-4)
> <img width="1883" alt="with background icon right" src="https://github.com/carbon-design-system/carbon/assets/43969356/f0c79f9c-ef80-43a0-b26f-bdd660cf4783">
> <img width="1883" alt="with background icon left" src="https://github.com/carbon-design-system/carbon/assets/43969356/7e319e05-7efa-4580-b0e2-5622df517018">

---

### Padding

![image](https://github.com/carbon-design-system/carbon/assets/148799271/ab564ce4-e30c-4c28-8e91-ab381eeaa5a7)

---

**Comment by sstrubberg** [comment]
waiting for crit
