### ISSUE TITLE
Add https to next.carbondesignsystem.com

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1547]
lets enncypt docs here https://github.com/carbon-design-system/carbon-website/blob/master/docs/lets-encrypt.md

**Comment by joshblack** [comment]
If it helps, I think our current cert supports wildcards at `*.carbondesignsystem.com` so I think it's just uploading the cert for `next.carbondesignsystem.com`

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/49744106-bdbb5c00-fc61-11e8-9beb-11fa656ce927.png)

Actually, just noticed this when I went to upload the cert

**Comment by alisonjoseph** [comment]
How do you get to that screen? I can't find it? 

What else do we need to do here to get https working? 😸

**Comment by alisonjoseph** [comment]
just realized this is in the wrong repo and can't easily transfer since website isn't in IBM org 🤦‍♀️

**Comment by geoffdavis92** [comment]
For what it's worth, [carbondesignsystem.com](http://www.carbondesignsystem.com/) does not appear to have HTTPS-enabled when I visited it today.

![screenshot of a URL bar showing carbondesignsystem.com without an HTTPS or other secured message](https://image.prntscr.com/image/08xaYfQCRHaCpcC8YLj0zQ.png)

**Comment by asudoh** [comment]
Hi 👋 we have https://www.carbondesignsystem.com, may be worthwhile doing HTTP -> HTTPS redirect.

**Comment by alisonjoseph** [comment]
@asudoh any ideas on getting this working?

**Comment by alisonjoseph** [comment]
this is working 🎉  

Had to add the CNAME for `next.` and not just `*`
