### ISSUE TITLE
AP - Publish DSPM migration story

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon#15481]
Publish the DSPM migration story

- [ ] Get feedback from Rybn Johnson, design lead
- [ ] Select images and any resources
- [ ] Complete final draft

**Comment by kingtraceyj** [comment]
https://w3.ibm.com/w3publisher/migrate-to-carbon/stories/8c77efb0-aa75-11ee-8af1-2d3c337dc564
