### ISSUE TITLE
[Feature Request]: JSON Viewer component with collapse/expand of nested key-values and search functionality

### ISSUE THREAD

**Issue by omkarajagunde** [carbon-design-system/carbon#15495]
### The problem

Developers always have the need to show JSON data, but big nested JSON data are hard to navigate hence expand/collapse, search options are given in JSON editors, Carbon currently doesn't has a dedicated JSON data preview. The CodeSnippet component was created for showing short code snippets and commands, hence the requirement for a JSON preview is out of its scope

### The solution

The new component for developers to easily preview JSON data. A new JSON preview component is needed with specific features:
1. **Expand/Collapse Icons:** For better visibility of nested properties in the JSON data.
2. **Search Functionality (Ctrl + F):** To find and highlight specific text within the JSON.
3. **Edit Capability:** Enabling direct editing of the JSON content.

I would be more than happy if I can contribute this new component, for which need to talk to one of the design member for design guidance

### Examples

Uploading Screen Recording 2023-12-28 at 8.03.30 PM.mov…

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> * **Expand/Collapse Icons:** For better visibility of nested properties in the JSON data.
> * **Search Functionality (Ctrl + F):** To find and highlight specific text within the JSON.
> * **Edit Capability:** Enabling direct editing of the JSON content.

This sounds a lot like a code editor. Have you considered using something like [monaco](https://microsoft.github.io/monaco-editor/)?

@carbon-design-system/design Has anyone explored a more extensive code editor solution for use cases like these? Would a code editor be considered out of scope for an addition Carbon?

**Comment by tay1orjones** [comment]
Another option potentially still [in use in at least one IBM product](https://ibm-studios.slack.com/archives/C0M053VPT/p1628583495147400?thread_ts=1628538432.138800&cid=C0M053VPT) is [CodeMirror](https://codemirror.net/).

With these options available, I'm not sure how or if it makes sense for us to approach this as a contribution to Carbon. 

There is a question of proper theming. IIRC we have a prismjs theme in use on our website that could be lifted as rough guidance for implementing Carbon colors for syntax highlighting. I don't think we've ever formally codified a Carbon-esque code editor theme though.

**Comment by omkarajagunde** [comment]
Currently we are using react-json-view package for the same, still wondering either it be CodeMirror or monaco, these are not consistent with carbon design, hence the preview looks inconsistent with other web app design
