### ISSUE TITLE
2 Overflow Menus showing in example

### ISSUE THREAD

**Issue by mven** [carbon-design-system/carbon#155]
In the [Overflow Menu page](http://www.carbondesignsystem.com/components/overflow-menu/code), there are 2 Overflow Menus that are showing and one seems to have an item with unfinished text: `Edit routes and access, use title when`

![screen shot 2017-06-05 at 3 53 36 pm](https://cloud.githubusercontent.com/assets/940113/26802798/81293ffe-4a07-11e7-9b6b-74ac862114e1.png)

![screen shot 2017-06-05 at 3 53 41 pm](https://cloud.githubusercontent.com/assets/940113/26802801/8255ba9c-4a07-11e7-89ff-46311673e6ab.png)

![screen shot 2017-06-05 at 3 53 46 pm](https://cloud.githubusercontent.com/assets/940113/26802821/929d6ae4-4a07-11e7-8cab-27acc8252d20.png)

**Comment by hellobrian** [comment]
Hey @mven! We can definitely fix the extra text. I don't think that's supposed to be there.
But I can explain why we're intentionally showing 2 overflow menus.

The second overflow menu uses an extra class to flip the positioning of the menu:

```html
<ul class="bx--overflow-menu-options bx--overflow-menu--flip">
```

**Comment by mven** [comment]
Ahhhh. That would make sense. 👍
