### ISSUE TITLE
missing left/right padding on bx-grid when width >= 1600px 

### ISSUE THREAD

**Issue by unidevel** [carbon-design-system/carbon#1550]
Seems fix for this issue https://github.com/IBM/carbon-components/issues/546 cause another issue.

When width>=1600px, the padding of left/right is only set to 10px, which is very small on large screen.

![image](https://user-images.githubusercontent.com/1028723/49844718-0eb48700-fdff-11e8-964e-612d965f8820.png)

![image](https://user-images.githubusercontent.com/1028723/49844728-15db9500-fdff-11e8-9e16-4e1d12e1b530.png)

I think it make sense to set the padding left/right to 3% or 5% on large screen.

**Comment by dakahn** [comment]
@unidevel hello there -- circling back on this -- could you provide the information requested in the issue template.

**Comment by joshblack** [comment]
Labelling this `wontfix` as we moved over to our new grid package 👍
