### ISSUE TITLE
[Bug]: Modal hover test is incorrect. Hover text is modal title instead of default or closeButtonLabel text.

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#15502]
### Package

@carbon/react

### Browser

Safari

### Package version

1.46.1

### React version

18.2

### Description

The hover text on the X for a modal panel is showing the modal title. 

According to the docs, it should be showing 'Close' by default.

I then added closeButtonLabel property and it is still showing the modal title instead of the specified text.

It happens on other browsers as well. Not just Safari.

<img width="1696" alt="image" src="https://github.com/carbon-design-system/carbon/assets/87548653/78b95564-66fc-4837-878c-f1ab0d9a8b77">

Below is a sample code.

import { Button, Modal, Row } from '@carbon/react';
import React from 'react';

export default function App() {
  return (
    <Modal
      open={true}
      danger
      modalHeading={'Modal Title'}
      primaryButtonText={'Disable'}
      secondaryButtonText={'Cancel'}
      closeButtonLabel={'Close'}
      preventCloseOnClickOutside={true}
    >
      <Row className="body-01 padding-left-05 padding-right-07 padding-bottom-06">
        <span> {'Description'} </span>
      </Row>
    </Modal>
  );
}

### Reproduction/example

Code shared

### Steps to reproduce

Hover over the X close icon on the modal.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Power Hardware Management Console

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@armtx Thanks for reporting. Could you package up the code into a [stackblitz](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/main/react/latest/react-18-vite/?file=src%2FApp.jsx)?

**Comment by guidari** [comment]
Hey @armtx the fix was delivered in this [PR](https://github.com/carbon-design-system/carbon/pull/15057). It's on the main branch and soon it will released.

![Screenshot 2024-01-16 at 11 28 20](https://github.com/carbon-design-system/carbon/assets/52183462/b0e6b536-e8da-4ab7-8c0c-84f71d000037)
