### ISSUE TITLE
[Bug]: TS error: href prop does not exist in SwitcherItem type

### ISSUE THREAD

**Issue by ecrvich** [carbon-design-system/carbon#15510]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.47

### React version

18.2

### Description

See screenshot below. Existing code still works at runtime. Worked around by moving the `href` prop up one line so it could be ignored with `@ts-ignore`.

![image](https://github.com/carbon-design-system/carbon/assets/19415464/a92fea3b-4fab-46d4-8baa-265c730a5a5c)

### Reproduction/example

Any use of SwitcherItem with the href prop will show this.

### Steps to reproduce

Any use of SwitcherItem with the href prop will show this.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

CDD Hub

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ecrvich** [comment]
Perhaps worth mentioning that the SwitcherItem API doc no longer shows that prop either.

![image](https://github.com/carbon-design-system/carbon/assets/19415464/a8be499c-f98d-4267-91f0-5d5514f56ee7)

**Comment by 2nikhiltom** [comment]
Hey @ecrvich  , could you share more, potentially a screen recording, of how you observed this bug? I am unable to  reproduce on the storybook.

https://github.com/carbon-design-system/carbon/assets/63502271/775852c6-4da3-4aae-b94e-a2c37cb10111

`Sandbox` [link](https://codesandbox.io/p/sandbox/zen-architecture-j3rxkj?file=%2Findex.js)

**Comment by ecrvich** [comment]
This is a **TypeScript** compiler error. i.e., you need to be coding with .ts and .tsx files, and preferably have strict set to true in your tsconfig file.
