### ISSUE TITLE
Interactive tag: Operational Tag Implementation

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15529]
## Acceptance criteria

- Add the Operational tag variant to the Tag component.

----

**New Tag variants**
- Add the Interactive tag umbrella under the existing Tag component
  - Add Operational tag variant

**Colors**
- Operational tags should not be available in the `outline` or `high contrast` color options.

**New color token (tag component level)**
- Add a `$tag-border-[color]` token to be used for the Operational tag variant border colors.
- Note: This token will always be the 40 step color in the light themes, and 50 step color in the dark themes. Provided an example below.

Example for Gray tag:

`$tag-border-gray`
| White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
|--------|--------|--------| --- |
| Gray 40 | Gray 40 | Gray 50 | Gray 50 |

----

### Operational Tag Design Spec

![Uploading Operational tag.png…]()

**Comment by tay1orjones** [comment]
Related info for this about skeleton states and tooltip examples in storybook: https://github.com/carbon-design-system/carbon/issues/13337#issuecomment-1888055860
