### ISSUE TITLE
Builds failing with version v9.61.2+

### ISSUE THREAD

**Issue by akim316** [carbon-design-system/carbon#1552]
## Detailed description

> Describe in detail the issue you're having.

Builds are failing with `carbon-components` versions 9.61.2 and up.
Believe it is due to fixing something related to rollup: https://github.com/IBM/carbon-components/releases/tag/v9.61.2

![image](https://user-images.githubusercontent.com/9680155/49897047-a83d6200-fe1a-11e8-9a4c-1626fdff029d.png)

**Comment by joshblack** [comment]
cc @asudoh seems related to https://github.com/IBM/carbon-components/pull/1549 potentially, any thoughts?

**Comment by loganmccaul** [comment]
We're experiencing the same issue on some other builds as well.

**Comment by asudoh** [comment]
@joshblack 🙏 My hunch is on Babel7 upgrade from the log, given they doesn't seem to be using our Bundle and the error is not at the file we go through Rollup's CJS->ES converter. Tried to reproduce the issue at two of the repos @akim316 and @loganmccaul are involved with (it's of my team last year), but no luck. Contacting them for understanding specific repos they hit the problem with.

**Comment by asudoh** [comment]
Saw silent build failure in our Travis log, which I could in my local environment. Created #1554 as the fix.
