### ISSUE TITLE
[Bug]:  ⨯ Menu.js ⨯ Internal error: ReferenceError: document is not defined 

### ISSUE THREAD

**Issue by edumorlom** [carbon-design-system/carbon#15531]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

@carbon/react@1.47.0

### React version

react@18.2.0

### Description

``` ⨯ node_modules/@carbon/react/es/components/Menu/Menu.js (33:13) @ document
 ⨯ Internal error: ReferenceError: document is not defined
    at Menu (./node_modules/@carbon/react/es/components/Menu/Menu.js:40:99)
    at ai (/Users/edumorales/dpr/ix-events-dpr/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
```

The following code causes the an error:

```
      <MenuButton label="Actions" kind={"tertiary"}>
      <MenuItem label="Option 1" />
      <MenuItem label="Option 2" />
      <MenuItem label="Option 3" />
      <MenuItem label="Option 4" />
    </MenuButton>
```

### Reproduction/example

None

### Steps to reproduce

Any time I compile my code with NextJS/Typescript, I get the error above.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by edumorlom** [comment]
FYI: This is NextJS 14 + TypeScript, its `client side rendering`.

```├── @carbon/icons-react@11.33.0
├── @carbon/react@1.47.0
├── @types/carbon__icons-react@11.29.0
├── @types/node@20.11.0
├── @types/react-dom@18.2.18
├── @types/react@18.2.47
├── dotenv@16.3.1
├── eslint-config-next@14.0.4
├── eslint@8.56.0
├── next@14.0.4
├── react-dom@18.2.0
├── react@18.2.0
├── sass@1.69.7
└── typescript@5.3.3
```

**Comment by tay1orjones** [comment]
Menu's `target` prop defaults to `document.body`

https://github.com/carbon-design-system/carbon/blob/abff3a5b12dee8edef8c81b4e935562293e8e545/packages/react/src/components/Menu/Menu.js#L38

**Comment by tay1orjones** [comment]
@janhassel do you think it makes sense to guard against this by moving this out of the default function parameter and instead have it in a useEffect?

**Comment by tay1orjones** [comment]
@edumorlom it would be helpful to have a concrete reproduction of this issue, could you put together a sandbox of it on codesandbox?

**Comment by janhassel** [comment]
@tay1orjones I have to admit I'm not super familiar with how Next.js handles the rehydration, so let me know if this makes sense or not.

Having the `target` set by a `useEffect` for this case feels a bit overkill and I'm concerned about code readability down the line. Couldn't we use optional chaining for the default value?

```js
function Menu({
  target = document?.body,
}) {
```

or alternatively remove the default value and add a nullish coalescing operator when creating the portal (also with optional chaining)?

```js
createPortal(rendered, target ?? document?.body)
```

I'm leaning towards the first option though (provided it works as I assume) for a more transparent API.

**Comment by lukababu** [comment]
I'm also getting this error, maybe I didn't implement it correctly, but I just have the following:
```
            <MenuButton
              label="Actions"
              kind="primary"
              menuAlignment="bottom-start"
            >
              <MenuItem label="View submissions" />
              <MenuItem
                label="Send"
                disabled={ isSent }
              />
              <MenuItem label="Download" />
            </MenuButton>
```

**Comment by tw15egan** [comment]
A good first step would be to implement @janhassel's first suggestion and seeing if this resolves the issue 👍

**Comment by DoaaRadwan** [comment]
Any updates on this? a similar issue was reported to the @carbon/ibm-products team and was fixed here https://github.com/carbon-design-system/ibm-products/issues/4966 if this could be of any help .
