### ISSUE TITLE
Dividers in AI components: Dev Implementation AI Slug

### ISSUE THREAD

**Issue by alina-jacob-ibm** [carbon-design-system/carbon#15552]
### **Developer implementation**

_Important Links_
[Design Solutions and Guidelines for Dividers in Components - Figma (**WIP for AI Slug**)](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=164-35044&mode=design)
[Design Solutions and Guidelines for Dividers in Components - GitHub](https://github.com/carbon-design-system/carbon/issues/15286)

---

**Tasks:**
- [x] #15861
- [x] #15862
- [x] #15863
- [x] #15864
- [x] #15859
- [x] #15860
- [x] Subsequently Update Input Components in [Form](https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-slug-form--overview) (this should happen automatically when the above PRs are merged)
- [x] Subsequently Update Input Components in [Modal](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--modal) (this should happen automatically when the above PRs are merged)

---

**Visual Context to the Solutions**
- [General Specs (Carbon Components)](https://github.com/carbon-design-system/carbon/issues/15492)
![Specs for Dividers AI](https://github.com/carbon-design-system/carbon/assets/159760598/5e3d6d9e-1154-4231-a515-dfb8aa8fd19f)

- [AI Combobox](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--combobox)

<img width="1104" alt="Combobox" src="https://github.com/carbon-design-system/carbon/assets/159760598/1afff1b3-d69c-4053-9edb-2e02fc1bb5d5">

- [AI Dropdown](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--dropdown)
<img width="1104" alt="Dropdown" src="https://github.com/carbon-design-system/carbon/assets/159760598/65949b16-343f-4341-8dcd-2ec592c93774">

- [AI Filterable Multi-select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect)
<img width="1104" alt="Filterable multi-select" src="https://github.com/carbon-design-system/carbon/assets/159760598/bb402e5c-7aa2-4fea-8f7a-b692ea1f159f">

- [AI Multi-select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--multiselect)
<img width="1104" alt="Multi-select" src="https://github.com/carbon-design-system/carbon/assets/159760598/ec5c81d8-a036-4c94-9256-bb79bff59b6d">

- [AI Number Input](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--number-input)
<img width="1104" alt="Number input" src="https://github.com/carbon-design-system/carbon/assets/159760598/a7c9c2e5-7b04-4858-86aa-1a126683795f">

- [AI Select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--select)
<img width="1104" alt="Select" src="https://github.com/carbon-design-system/carbon/assets/159760598/6eb414d2-5d1f-49d1-9e42-07abf93bb623">

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon-design-kit/issues/745#issuecomment-1910657153

**Comment by alina-jacob** [comment]
> I believe we also need to add this to `TextInput` since it could be both invalid and have the `Slug`, possibly `Textarea` as well?

hi @tw15egan, that's a good question! 
As per the guidelines, we won't be introducing a divider between an interactive and a non-interactive item. 
Pasting a screenshot with some Do and Don'ts (for vertical divider in input fields)
![image](https://github.com/carbon-design-system/carbon/assets/159760598/5bcf9e78-b0fe-4df4-b03f-5fcadc8d3f70)

---

( Also, just a headsup, as per my last conversation in Carbon Design crit and with Michael Gower, error states should always be the leftmost. However this is yet to be confirmed by Anna and the C4AI team. I can update latest by Tuesday after the crit regarding the same or sooner if possible. )

![image](https://github.com/carbon-design-system/carbon/assets/159760598/9c9a36cb-ee66-45cc-9b92-c264ca52ec17)

**Comment by tw15egan** [comment]
@alina-jacob ah right! Thanks for pointing that out 😄

**Comment by alina-jacob** [comment]
**AI SLUG UPDATE**

- There won't be two types of AI Slugs (standard and hollow)
- The hollow slug is now the standard slug with all its associated features.

---


- [General Specs (Carbon Components)](https://github.com/carbon-design-system/carbon/issues/15492)
![Specs for Dividers AI](https://github.com/carbon-design-system/carbon/assets/159760598/77efc7b9-602f-4ec8-93f1-dfbdd9b43698)


- [AI Combobox](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--combobox)
<img width="1104" alt="Combobox" src="https://github.com/carbon-design-system/carbon/assets/159760598/8729a60a-af74-4f6b-8a82-34c45bab781c">


- [AI Dropdown](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--dropdown)
<img width="1104" alt="Dropdown" src="https://github.com/carbon-design-system/carbon/assets/159760598/efc52f35-0e80-4e1e-97dd-c79ce0f81646">


- [AI Filterable Multi-select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect)
<img width="1104" alt="Filterable multi-select" src="https://github.com/carbon-design-system/carbon/assets/159760598/8bb68500-2fdf-46a2-9d65-601ade302b47">


- [AI Multi-select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--multiselect)
<img width="1104" alt="Multi-select" src="https://github.com/carbon-design-system/carbon/assets/159760598/5a1fca55-6bba-4a1f-91c4-9f9aaf1e99b6">


- [AI Number Input](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--number-input)
<img width="1104" alt="Number input" src="https://github.com/carbon-design-system/carbon/assets/159760598/31891813-39a7-46e0-855c-9c0f2b8f537c">


- [AI Select](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--select)
<img width="1104" alt="Select" src="https://github.com/carbon-design-system/carbon/assets/159760598/ac3bc706-bc92-4e38-865f-f6ce53e4a087">

**Comment by alina-jacob** [comment]
**UPDATE**

I did a closer inspection and realised that the spacing that works for the chevron and dismissible icon in the dropdown variants won't work for number input, because in this component the plus and minus items are **buttons**. 

Even though, the icons of these buttons are of 16px, the click area for the button is 48px and that's the same spacing pattern we will have to provide for all subsequent elements coming to the left of the buttons.

Pasting an **updated** screenshot of the spacing just for the number input component, you can also check out the spacing relation for error and invalid states in the default component [here](https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground&args=invalid:!true).

[Figma ref link](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=368-12162&mode=design&t=6UQz4ZVsysahCPAj-4)

<img width="708" alt="Specs for Dividers in Number input" src="https://github.com/carbon-design-system/carbon/assets/159760598/11de869d-d329-46ca-a0e6-a11c8a88187b">

**Comment by tw15egan** [comment]
All components should have the divider implemented
