### ISSUE TITLE
Create design spec for AI `Tearsheet`

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15555]
Create a design spec for an AI flavor of C4IP Tearsheet, incorporating the slug and new aura gradient where appropriate. Design a solution for both light and dark themes.

**Comment by RichKummer** [comment]
@lee-chase 


[Tearsheet (narrow) with AI design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1636%3A142495&mode=design&t=LUEIAwqQ2r2EltzN-1)


Went through a first pass on the design specs for `narrow`, now moving to speccing out the `wide` variant.
![Image](https://github.com/carbon-design-system/carbon/assets/15643582/46d51abf-9e85-4090-a119-237aded04b16)

**Comment by mattrosno** [comment]
@RichKummer @lee-chase what's the update on this issue? Is the design spec complete? If so, can you close this issue?

**Comment by RichKummer** [comment]
@mattrosno – the tearsheet design specs are cleaned and updated in the comment above based on modal. We can close this one out.
