### ISSUE TITLE
[Bug]: When `autoAlign` prop is set, and the viewport is too small, caret / popover positioning is off

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#15566]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### Description

<img width="401" alt="Screenshot 2024-01-18 at 10 26 42 AM" src="https://github.com/carbon-design-system/carbon/assets/11928039/05976ce1-a7c8-44c1-9830-0939c8169fdc">

This was causing issues with the `Slug` callout, which is using additional pseudo elements off the popover caret.
![image](https://github.com/carbon-design-system/carbon/assets/11928039/927aae8e-280c-43ba-8eb5-398a0c3d6212)

For now, I've hidden the `Slug` popover caret when the viewport is too small and no alignment is set

### Reproduction/example

Open a `Popover` with a very small screen size

### Steps to reproduce

Open a `Popover` with a very small screen size, and notice the popover is aligned directly on top of the opening trigger, and there is no caret. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Should be addressed via https://github.com/carbon-design-system/carbon/issues/14139

**Comment by guidari** [comment]
Tested after adding floating UI to the `Popover` and it is working fine in small screens
