### ISSUE TITLE
[Bug]: status='indeterminate' is missing from ProgressBar.d.ts in TypeScript

### ISSUE THREAD

**Issue by edumorlom** [carbon-design-system/carbon#15564]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

@carbon/react@1.47.0

### React version

react@18.2.0

### Description

TypeScript type exists for this component but it's missing one of the statuses that exists.

### Reproduction/example

https://stackblitz.com/edit/github-zcis9s?file=src%2FApp.jsx

### Steps to reproduce

```Type '"indeterminate"' is not assignable to type '"active" | "finished" | "error" | undefined'.ts(2322)
```

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by OmarSherif96** [comment]
@edumorlom the example you shared on Stackblitz isn't working

**Comment by janhassel** [comment]
Hey @edumorlom! 👋 
In order to render an indeterminate `ProgressBar` all you need to do is leave out `props.value` or set it explicitly to either `null` or `undefined`.

**Comment by edumorlom** [comment]
thank u!
