### ISSUE TITLE
[Inline status] Create design spec

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#15561]
### Final design spec
1. Create a design spec for an inline status to be used by teams in their products. Ref the [Status indicator pattern](https://carbondesignsystem.com/patterns/status-indicator-pattern/)
  - [x] An inline status should consist of a status icon / shape indicator and text.
  - [x] Determine what the spacing should be between the icon and text
  - [x] Determine what the type token should be for the text
  - [x] Will the specs for this differ when text is paired with an icon or a shape indicator?
  - [x] Review

---

### Shape indicator and text pairing (re-spec)
2. We re-opened this issue to further investigate the size of the shape indicator and its relationship and spacing when paired with text. Make sure these aspects are both correct.
- [ ] Consider this [Inline loading has been updated to 14px text](https://github.com/carbon-design-system/carbon/pull/17259)
- [ ] Determine the asset size of the shape indicator when paired with 12px and 14px text.
- [ ] Determine the spacing between the shape indicator when paired with 12px and 14px text.
- [ ] Review
- [ ] Post image of updated spec if it has changed

**Comment by aubrey-oneal** [comment]
Notes
- This will be a spec for development
- Make a file in Carbon components and patterns space for now. Once ready to add it to file we can add a branch.

**Comment by aubrey-oneal** [comment]
[Figma design spec here](https://www.figma.com/file/rXWkXn89PUOsKedonrAiSf/Inline-status?type=design&node-id=11-9364&mode=design&t=ljUC71W0dvmB0NLP-0)

**Comment by aubrey-oneal** [comment]
![Image](https://github.com/carbon-design-system/carbon/assets/47198241/82f430be-dc90-4a12-b91e-9a370186ab34)

**Comment by laurenmrice** [comment]
Need to review the spec for the shape indicator size in relation to the type.

**Comment by thyhmdo** [comment]
Refer to these issues for final specs https://github.com/carbon-design-system/carbon/issues/17539 and https://github.com/carbon-design-system/carbon/issues/17540
