### ISSUE TITLE
C4IA: Add new `Chat` color tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15573]
These tokens are needed for the AI Chat design. Not sure if this goes into the core package or the C4AI package

| Token name | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
| -------------|---------------|---------------|-----------------|-----------------|
| chat-prompt-background | White | White | Gray 100 | Gray 100 |
| chat-prompt-border | Linear-gradient: Gray 10 100% to 0% | Linear-gradient: Gray 10 100% to 0% | Linear-gradient: Gray 90 100% to 0% | Linear-gradient: Gray 90 100% to 0% |
| chat-bubble-user | Gray 20 | Gray 20 | Gray 80 | Gray 80 |
| chat-bubble-agent | White | White | Gray 90 | Gray 90
| chat-bubble-agent-border | Gray 20 | Gray 20 | Gray 70 | Gray 70 |
| chat-avatar-bot | Blue 60 | Blue 60 | Blue 50 | Blue 50 |
| chat-avatar-agent | Gray 100 | Gray 100 | Gray 10 | Gray 10 |
| chat-avatar-user | Gray 100 | Gray 100 | Gray 10 | Gray 10 |

**Comment by tw15egan** [comment]
Just one note, the chat border has been broken into two tokens:

```scss
$chat-prompt-border-start
$chat-prompt-border-end
```
