### ISSUE TITLE
[Feature Request]: Multi-line text input

### ISSUE THREAD

**Issue by cate-wilcox** [carbon-design-system/carbon#15575]
### The problem

When designing form-based experiences, for certain inputs it can be unclear how much information will be entered.

- Truncated text inputs make it difficult to confirm and correct information
- For these scenarios, the text area is often more space than is necessary and requires the user to manually adjust the height.

![image](https://github.com/carbon-design-system/carbon/assets/26073075/a06601f8-b67d-459f-9336-ba1465050b12)

### The solution

Provide a multi-line text input option that dynamically adjusts as the user types.
![image](https://github.com/carbon-design-system/carbon/assets/26073075/6d49642c-f8a8-4507-aff5-fea1e065becd)

### Examples

**Design system examples**
- [Google Material Design](https://m3.material.io/components/text-fields/guidelines#caf14aa9-26ce-48cc-9076-3a383a9ad679)
- [Shopify Polaris ](https://polaris.shopify.com/components/selection-and-input/text-field?example=text-field-multiline)

### Application/PAL

watsonx Orchestrate

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

Possible design support if needed. Unsure about dev support atm.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Have you tried using the TextArea component for this? It should be able to accommodate for resizing. As far as the elegant resizing, this might be something we'd consider having ya'll contributing. Let me know!
