### ISSUE TITLE
[Typescript]: Property 'href' does not exist on type 'IntrinsicAttributes & SideNavMenuItemProps & RefAttributes'.

### ISSUE THREAD

**Issue by murphylan** [carbon-design-system/carbon#15580]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Operating System

Windows, MacOS

### Package version

v1.48.0

### Automated testing tool and ruleset

 "@carbon/react": "^1.48.0",

### Description

`<SideNavMenuItem href="/diagram-add">Link</SideNavMenuItem>`

Type '{ children: Element; href: string; "aria-current": "page" | undefined; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & SideNavMenuItemProps & RefAttributes<HTMLElement>'.
  Property 'href' does not exist on type 'IntrinsicAttributes & SideNavMenuItemProps & RefAttributes<HTMLElement>'. Did you mean 'ref'?ts(2322)

It seem that there is not "href" attribute in the SideNavMenuItem.d.ts.

And, I also want to add element attribute in it. In Next.js 14, 

AppLink: 
`
export const AppLink = ({ href, children = undefined, ...rest }: LinkProps) => (
  <Link href={href!} {...rest}>
    {children}
  </Link>
);
`

SideNavMenuItem:
`<SideNavMenuItem
            element={AppLink}
            href="/diagram-list"
            aria-current={(pathname === '/diagram-list') ? 'page' : undefined}>`

### Reproduction/example

no

### Steps to reproduce

`<SideNavMenuItem href="/diagram-add">Link</SideNavMenuItem>`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@murphylan Thanks for reporting this, we'd appreciate a contribution to get a fix in place if you or anyone else is able.
