### ISSUE TITLE
[Bug]: broken link to carbon for ibm.com

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon#15587]
### Package

@carbon/react

### Browser

Chrome

### Package version

n/a

### Description

A page on carbondesignsystem.com contains a broken link

### Reproduction/example

https://carbondesignsystem.com/all-about-carbon/the-carbon-ecosystem/

### Steps to reproduce

Activate the tile called Carbon for IBM.com
![image](https://github.com/carbon-design-system/carbon/assets/14298245/3af9c388-7720-412c-b81f-ce8231b0deaa)

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/carbon-website/pull/3883
