### ISSUE TITLE
[Feature Request]: Add a Select/Deselect all option for Multiselect Dropdowns

### ISSUE THREAD

**Issue by darenhrelic** [carbon-design-system/carbon#15599]
### The problem

Currently when using the Dropdown (https://carbondesignsystem.com/components/dropdown/usage/), there is an option to transform the component into a multiselect, which fits our use case perfectly.  We need to be able to select multiple (and many) options from the dropdown.

However, we also need to be able to select/deselect all options quickly.  We often hear from our customers that 'unnecessary clicks' can ruin the user experience, which I completely agree with.

Our particular use case here, can involve selecting or deselecting up to hundreds of values from the dropdown.  A single option to do this automatically would save a significant amount of time and effort for our users.

### The solution

Add an option at the top of the list of values in a multiselect dropdown to select/deselect all options in the component.  This would save time and clicks.

For example, our data sets can include selecting 10s to hundreds of values from thousands in the dropdown (VERY large datasets), as seen in the following picture:
![Screenshot 2024-01-24 at 1 36 44 PM](https://github.com/carbon-design-system/carbon/assets/157621986/b9482cca-ab70-4a66-a134-c2c2f6764048)

### Examples

We've implemented this in the previous iteration of our application - not with dropdowns - but with checkboxes, to help with the user experience.  Examples in screenshots below:

![Screenshot 2024-01-24 at 1 37 14 PM](https://github.com/carbon-design-system/carbon/assets/157621986/9fddfd52-bf93-43c7-a1ba-7a3f56ea085d)

![Screenshot 2024-01-24 at 1 37 18 PM](https://github.com/carbon-design-system/carbon/assets/157621986/40f5510a-0f0c-4d55-9a4c-0fd5365a6a57)

### Application/PAL

IBM Sterling - B2Bi SaaS InFlight Web

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

none.  cannot spare due to application development effort.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Thanks for opening this! Totally agree - we've got an issue open for this one already with some plans lined out, https://github.com/carbon-design-system/carbon/issues/4593. I'm not sure when we'll be able to take it on but this is definitely a feature we'd like to see added to MultiSelect

**Comment by darenhrelic** [comment]
I looked for duplicates but must have missed it.  Thanks!
