### ISSUE TITLE
[Feature Request]: Date Picker / Time Picker should support 'seconds'.  Currently it does not.

### ISSUE THREAD

**Issue by darenhrelic** [carbon-design-system/carbon#15597]
### The problem

Date/Time pickers include hour and minute, but do not go granular down to seconds.  For our application we _need_ these widgets to include ways to manipulate seconds as well.  Our customers require this functionality.

Seconds can be granular, but are required for specificity in our (and likely other) applications.

### The solution

The solution here would be to have a toggle on all date/time widget varieties, which would allow the developer to choose whether or not to include seconds on the widget.  This would leave the functionality up to the application, and meet different use cases as required.

When seconds are included, the seconds could be input as text `HH:MM:SS` (or however the time format is set), and there would be graphical options in the widget(s) similar to the hour/minute that exist today.

### Examples

![Screenshot 2024-01-24 at 1 05 54 PM](https://github.com/carbon-design-system/carbon/assets/157621986/7b82ecb0-f731-4d36-8462-8b5a464d79b4)
  
Above is a screenshot of the current implementation in our application (before rewriting in carbon).

### Application/PAL

IBM Sterling - B2Bi SaaS InFlight Web

### Business priority

High Priority = pressing release

### Available extra resources

none.  cannot spare due to application development effort.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@darenhrelic Is there something specific blocking you from configuring the component this way? 

I think it should be possible with a combination of the `pattern`, `placeholder`, `maxLength` props and overriding `.cds--time-picker__input-field` to have a larger width via `inline-size`.

**Comment by darenhrelic** [comment]
Our team will give this a shot and report back. Thank you for the feedback!

Daren

**Comment by sstrubberg** [comment]
Closing for now. Let us know how it goes!

**Comment by sushant-kumar9** [comment]
> @darenhrelic Is there something specific blocking you from configuring the component this way?
> 
> I think it should be possible with a combination of the `pattern`, `placeholder`, `maxLength` props and overriding `.cds--time-picker__input-field` to have a larger width via `inline-size`.

@sstrubberg - I have implemented the above issues, now the **second** is available in the **TimePicker** Components
but I am facing few challenges
1- Spinner toggle is not available to  increase and decrease the particular HH:MM:SS time.
2- The validation also require for : as of now if user clear the input and after the type 12345678 ,its allowed to enter but i want something like this , if user type 11 auto : will appear like this for minutes.

so can you please help me on this.

cc @darenhrelic
