### ISSUE TITLE
[Bug]: violate HTML specification for tiles

### ISSUE THREAD

**Issue by captainkovalsky** [carbon-design-system/carbon#15607]
### Package

@carbon/react

### Package version

11

### Description

Non HTML Semantic issue for Tiles

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-tile--overview

### Steps to reproduce

Inspect HTML output

https://react.carbondesignsystem.com/?path=/docs/components-tile--overview

div is inside span

<img width="420" alt="image" src="https://github.com/carbon-design-system/carbon/assets/845156/1bf8c846-2b8b-4b9d-a63e-46be9e79835b">

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Yep, needs to be changed to a `div`. Once changed, the associated `display: block` styling for that element can be removed, but we'll need to leave the classname on there so folks don't see a regression if they're testing or using that selector for override styling in their apps.

PRs are open if you or anyone else would be willing to submit a fix, thanks for reporting this!

**Comment by slokhande310** [comment]
Hi @tay1orjones, I tried to fix the issue as you suggested, I am new to open-source contribution I hope i fixed it.
