### ISSUE TITLE
[Bug]: AccordionItem does not adjust to dynamic contents (regression)

### ISSUE THREAD

**Issue by pmwals09** [carbon-design-system/carbon#15608]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.48.1

### React version

18.2.0

### Description

If an accordion has dynamic content, the latest version of AccordionItem does not adjust its size to fit the new content. I believe this was introduced [here](https://github.com/carbon-design-system/carbon/commit/448c0efd73d9d31cac1857bd41887a749b5a2a2a#diff-37245a44b5854889cc06c94785763513f263caaa71a1043891d649b482449d0aR155). If I remove the `max-block-size` CSS property that is set here, then the AccordionItem container resizes to the dynamic content appropriately. The only way I could come up with to do so is with some CSS below, but I have to imagine this isn't the intended developer experience and if Carbon opts to change classnames, this will break.

```css
.classname-on-actionitem.cds--accordion__item--active {
  .cds--accordion__wrapper {
    max-block-size: unset !important;
  }
}
```

### Reproduction/example

https://stackblitz.com/edit/github-qiow5x?file=src%2FApp.jsx

### Steps to reproduce

1. Expand the accordion. The visible text should be "Short"
2. While the accordion remains expanded, click the "Swap between text length" button
3. Observe that the text now overflows the accordion container

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@pmwals09 Hey, thanks for opening an issue on this with such solid detail. 

The code you linked is definitely a side effect and needs to be handled appropriately. In addition to being ran onClick, the content ref probably should be re-measured anytime the content/children change. Might require the use of a [callback ref](https://tkdodo.eu/blog/avoiding-use-effect-with-callback-refs) to know when the content ref changes/updates.

As far as workarounds go, the one you outlined should work. I think you could also put a `key` on the AccordionItem and change it's value when you update the content. This will instruct react to throw away that portion of the component tree and rebuild it.

This somewhat intersects with https://github.com/carbon-design-system/carbon/pull/15589
