### ISSUE TITLE
[Link] Adding an underline on the focus state and active state

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#15613]
**Ref issue**: https://github.com/carbon-design-system/carbon-website/issues/3537

**PROBLEM**
The focus state of the [Standalone Link](https://react.carbondesignsystem.com/?path=/story/components-link--playground)  needs to have an underline. There's only padding to differentiate it from the focus state of the Ghost button. 

### Standalone link (default and focus state)
<img width="81" alt="image" src="https://github.com/carbon-design-system/carbon/assets/77697351/7dd788c6-fec8-42d0-9be7-66fa95402f6f">

<img width="74" alt="image" src="https://github.com/carbon-design-system/carbon/assets/77697351/7fb55aa5-5ed2-4ca3-bd56-0df215d246e1">

### Ghost button
<img width="90" alt="image" src="https://github.com/carbon-design-system/carbon/assets/77697351/d762cd85-87e2-4906-891b-4a400a6c8473">

<img width="97" alt="image" src="https://github.com/carbon-design-system/carbon/assets/77697351/d6c6a343-fc82-45c9-8b26-770abbdca8b2">

----

**INCONSISTENCY**
Active state:  When you hold the click over the [inline link](https://carbondesignsystem.com/guidelines/2x-grid/usage), there's no underline. But when you hold the click on the [Standalone link](https://react.carbondesignsystem.com/?path=/story/components-link--paired-with-icon), there's an underline

------

**SOLUTION**

- [x] Need to add design specs here - Need a review from @laurenmrice 

![4_3_608x456px](https://github.com/carbon-design-system/carbon/assets/77697351/b6330013-f51d-4049-91be-e42f11e13ad4)

**Comment by thyhmdo** [comment]
Specs provided for devs

<img width="672" alt="Link specs" src="https://github.com/carbon-design-system/carbon/assets/77697351/6e6413d4-8a93-43be-9192-1ba75cb2ad58">

**Comment by tay1orjones** [comment]
It would be interesting to try and see if we could VRT these changes so that we have a snapshot for each state of both standalone and inline.

We could augment the VRT tests to use the keyboard to navigate and get the links into the various states (active, hover, etc) and then do a percy snapshot for each of those.
