### ISSUE TITLE
Implement more Search component features

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1564]
Questions have come up from other product teams about what our current search component capabilities are:

-What do we do to show applied search terms?
-Can we show tags (like pinterest?)
-Show X of X results (like amazon?) 0 results message guidelines/illo examples?
-Do we have guidelines on what a loading state looks like?
-How do we account for search limitations? (technical)

These kinds of things would be helpful to either implement and/or update content wise in our guidance.

**Comment by asudoh** [comment]
We are still keeping researching on this.

**Comment by asudoh** [comment]
Seems that we are not putting this in our imminent roadmap yet, we may put this in "help wanted" mode depending on what others think.

**Comment by laurenmrice** [comment]
not stale
