### ISSUE TITLE
Create design spec for AI v2 `modal`

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15661]
Create a design spec with the v2 AI styles for Modal.

The direction will likely be similar to the [tearsheet](https://www.figma.com/file/tfTsx02uDtoJEHzvl6ODPf/SANDBOX?type=design&node-id=2515%3A100289&mode=design&t=lTwCWFaq4KmWgXwg-1) and [side panel](https://www.figma.com/file/4aMIX5zjux2LhbW1aI3xgD/Carbon-for-AI---AI-Essentials-Kit?type=design&node-id=1235%3A134918&mode=design&t=khPDQGdxy7csE1xK-1).

**Comment by mattrosno** [comment]
These are primarily updates to border and drop shadow treatment? And using the updated linear gradient?

**Comment by RichKummer** [comment]
[Figma: design spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1886%3A81284&mode=design&t=82KUpNdJhzeLkuNR-1)

![Image](https://github.com/carbon-design-system/carbon/assets/15643582/096d402d-4646-4d92-bb19-20aeaad9d46b)

**Comment by mattrosno** [comment]
@tw15egan @ariellalgilmore @lee-chase once you've reviewed the new spec above, let us (@RichKummer) know if this issue can be closed. Thanks!
