### ISSUE TITLE
[AI Slug] Create design spec for translation of "AI"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15667]
[Slack thread](https://ibm-studios.slack.com/archives/C05EQ4KJH70/p1706129896580829) Also see Mike's comment below

`AI` in CN, ID, IT, JA, KO, ESLA,. (Chinese, Indonesia, Italian, Japanese, Korean, Spanish LA)
`IA` in ESES, BRPT, FR (European Spanish, Brazilian Portuguese, France French)
`KI` in DE (German)
`NN` in Ukrainian, Bulgarian

![image](https://github.com/carbon-design-system/carbon/assets/11670886/6dc27b07-1853-4347-9038-2380fcecc0f4)

**Comment by mjabbink** [comment]
`Good to know for the future.`
Although Maximo Application Suite does not support bidirectional languages, Maximo Manage provides language support for bidirectional languages.

The following languages are supported:
Arabic
Brazilian Portuguese
Croatian
Czech
Danish
Dutch
English
Finnish
French
German
Hebrew
Hungarian
Italian
Japanese
Korean
Norwegian
Polish
Russian
Simplified Chinese
Slovak
Slovenian
Spanish
Swedish
Traditional Chinese
Turkish


<img width="496" alt="Screenshot 2024-01-31 at 10 54 15 AM" src="https://github.com/carbon-design-system/carbon/assets/32881239/3172a9a4-05b1-478d-8caf-b056293b596d">

**Comment by tw15egan** [comment]
2 letter translations should already be supported by passing in the desired translation to the `aiText` prop on `Slug`. 

Can test out variants here in the storybook by changing the `aiText` control at the bottom: https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug--playground&args=aiText:NN

**Comment by mjabbink** [comment]
@tw15egan That’s a nice feature. It works like a charm. I tested all of them (even potential future ones), and they all worked. Well done!

**Comment by mjabbink** [comment]
I reckon we can close this issue then. no?

**Comment by aagonzales** [comment]
Yeah, I can just unlock the text layer in Figma and then people can update in Figma as needed as well.

**Comment by mattrosno** [comment]
@aagonzales I added to phase 2, as it seems like this is a small change to the Figma library?

**Comment by aagonzales** [comment]
Ok this has been added to the slug and will be available in the next kit publish 
<img width="521" alt="image" src="https://github.com/carbon-design-system/carbon/assets/11670886/ca037325-9d68-4265-a8a3-dd109de4e1d8">
