### ISSUE TITLE
Progress indicator - error state vs current step

### ISSUE THREAD

**Issue by AkosKovacs077** [carbon-design-system/carbon#15666]
We have a recurring issue related to the [progress indicator](https://carbondesignsystem.com/components/progress-indicator/usage/). The “error state” is overwritten by the “current step” icon as users sliding through the provision page. The component misses the state when I’m currently on that very section where the alert should be indicated.
We can fix this locally on VMware by subordinate the current step to the error indication, but I just think about if there’s any plan to update this component.

https://github.com/carbon-design-system/carbon/assets/73703420/baf0f668-c2cf-4972-b177-0e977c68fa67

**Comment by alisonjoseph** [comment]
Are you able to provide an example in [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2Findex.scss) and exactly what functionality you're expecting to be added to the component.

**Comment by sstrubberg** [comment]
Closing for now. Let us know when you get around to a repro!
