### ISSUE TITLE
[Bug]: Typescript signature for TableToolbarSearch onChange seems wrong

### ISSUE THREAD

**Issue by tom-youd** [carbon-design-system/carbon#15664]
### Package

@carbon/react

### Browser

Chrome, Safari

### Package version

1.48.1

### React version

16.14.0

### Description

The event signature for the event when onChange is called using the TableToolbarSearch is currently `React.ChangeEventHandler<HTMLInputElement>`. This means you cannot target `event.target` the compiler says it doesn't exist within this type.

![Screenshot 2024-01-31 at 13 24 00](https://github.com/carbon-design-system/carbon/assets/56865994/0be6ceab-91b5-4460-96ae-baf276983b35)

Changing to `React.ChangeEvent<HTMLInputElement>` seems to address the problem but the compiler then complains the types do not match.

### Reproduction/example

none

### Steps to reproduce

I couldn't get CodeSanbox to use typescript so here is an example

```tsx
import {
  TableToolbarSearch
} from '@carbon/react'

const ResourceTableToolbar = (): JSX.Element => {
  const onSearchChange = (event: Partial<React.ChangeEventHandler<HTMLInputElement>>) => console.log(event.target?.value )

  return (
     <TableToolbarSearch size='lg' persistent placeholder='Search' onChange={onSearchChange} />
  )
}
```

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
> Changing to React.ChangeEvent<HTMLInputElement> seems to address the problem but the compiler then complains the types do not match.


Ohh, I just saw this comment, sorry
@tom-youd if the compiler still complaing about it, try to put together a Stackblitz so we can debug to undersantd what is going on, please.

**Comment by guidari** [comment]
I'll close this issue. Feel free to re-open or create a new one, if the error still up.
