### ISSUE TITLE
[Question]: How to animate the exit of a ToastNotification if clicking on the "x" removes the element from the DOM?

### ISSUE THREAD

**Issue by marcellobarile** [carbon-design-system/carbon#15699]
### Question for Carbon

As the title says, it seems that clicking on the "x" button immediately removes the ToastNotification from the DOM. Which makes it impossible to animate its exit phase.

This causes also confusion about the Carbon guidelines: https://carbondesignsystem.com/components/notification/usage/#toast-notifications

```
Toast notifications slide in and out from the top right of the screen.
``` 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Hi there, unfortunately we don't have an example of this in code however you should be able to create a custom [onClose](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L423) to handle the animation and then closing of the notification.

**Comment by marcellobarile** [comment]
hi @alisonjoseph 
I'm not sure that would be possible, I remember that by pressing the "X" button, the notification was immediately removed from the DOM, without any delay hence without any concrete way to animate it.
I'll double-check though.

**Comment by albert-schilling** [comment]
@marcellobarile is right. There is still currently no way to stop the Toast from immediately closing when the user clicks the close button. The `onClose` and `onCloseButtonClick` properties in the component's interface can be used to implement further functionality but they do not stop the Toast from immediately vanishing.

As @marcellobarile stated this is a bug and contradicts the design system.
