### ISSUE TITLE
Update AI Chat tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15710]
Update AI Chat token values to:

| Token name | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
| -------------|---------------|---------------|-----------------|-----------------|
| chat-avatar-bot | Gray 60 | Gray 60 | Gray 50 | Gray 50 |
| chat-avatar-agent | Gray 80 | Gray 80 | Gray 30 | Gray 30 |
| chat-avatar-user | Blue 60 | Blue 60 | Blue 50 | Blue 50 |

**Comment by aagonzales** [comment]
| Token name | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
| -------------|---------------|---------------|-----------------|-----------------|
| chat-prompt-background | White | White | Gray 100 | Gray 100 |
| chat-prompt-border | Linear-gradient: Gray 10 100% to 0% | Linear-gradient: Gray 10 100% to 0% | Linear-gradient: Gray 90 100% to 0% | Linear-gradient: Gray 90 100% to 0% |
| ~chat-bubble-user~ chat-bubble | Gray 20 | Gray 20 | Gray 80 | Gray 80 |
| ~chat-bubble-agent~ | ~White~ | ~White~ | ~Gray 90~ | ~Gray 90~ |
| ~chat-bubble-agent-border~ | ~Gray 20~ | ~Gray 20~ | ~Gray 70~ | ~Gray 70~ |
| chat-avatar-bot | Gray 60 | Gray 60 | Gray 50 | Gray 50 |
| chat-avatar-agent | Gray 80 | Gray 80 | Gray 30 | Gray 30 |
| chat-avatar-user | Blue 60 | Blue 60 | Blue 50 | Blue 50 |

**Comment by tw15egan** [comment]
Should we reopen this if these token names need to be changed/removed? Also, the border one is broken into two, so a user would need to add the tokens to a `linear-gradient`. They are`chat-prompt-border-start` (`gray10` in light) and `chat-prompt-border-end` (`gray10`  at 0 opacity)

**Comment by aagonzales** [comment]
@tw15egan Not yet, I'm still coordinating with Vora and Juan on the final token list. But I think we will have some token updates coming soon.
