### ISSUE TITLE
[Bug]: Dropdown itemToElement isn't working anymore (regression)

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#15724]
### Package

@carbon/react

### Browser

Safari

### Package version

1.49.0

### Description

The Dropdown's `itemToElement` prop doesn't seem to be called anymore. Interestingly enough, `itemToString` can be used as a substitute for this (though based on the console outputs I don't think this is the intended use).

I couldn't find anything in the documentation or issues regarding a deprecation so I assume this is a regression?

### Reproduction/example

https://stackblitz.com/edit/github-jxltcv?file=src%2FApp.jsx

### Steps to reproduce

1. Pass a function to `itemToElement`: `(item) => <em>{item.toLowerCase()}</em>`
2. It's not used when rendering

`itemToElement`:

<img width="384" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/8dab28f3-f0bc-4b7e-99db-b303638518ca">

`itemToString` (results in expected result):

<img width="376" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/d441b265-3b74-4d81-ab40-444f0298dafe">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @janhassel 
itemToElement only work with objects. I was checking your example and the `typeof` is a string.

Here it is an [Stackblitz](https://stackblitz.com/edit/github-jxltcv-1krsdh?file=src%2FApp.jsx) example using an object.

Below you can check the logic in carbon:

```jsx
 {typeof item === 'object' &&
    ItemToElement !== undefined &&
    ItemToElement !== null ? (
      <ItemToElement key={itemProps.id} {...item} />
    ) : (
      itemToString(item)
    )}
```

**Comment by janhassel** [comment]
@guidari Interesting, I didn't know that. So if I only have strings and need to display them as elements I need to wrap them in dummy objects, like `{ id: 'my-value' }`?

Could you elaborate on the reasoning for this constraint?

**Comment by guidari** [comment]
@janhassel I'm not sure the reason behind that. I know that `itemTostring` is a props from Downshift and the `itemToElement` is a prop we created.
