### ISSUE TITLE
[Question]: How to customise theme. 

### ISSUE THREAD

**Issue by pociej** [carbon-design-system/carbon#15723]
### Question for Carbon

Im trying to go described in docs and seems that some tokens works as expect and other doesnt. I didnt check all of them but lets look at example : 

```
@use '@carbon/react/scss/theme' with ($theme: (
    background: #e2e2e2,
    text-primary: green,
    button-primary: red,
    button-danger-primary: blue,
  ))
``` 

while `background` and `text-primary` works as expected and relarted css classes are changed buttons stays untouched. What Im missing? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Hi, here is an example showing how to override/update the component level tokens.
https://github.com/carbon-design-system/carbon/blob/main/examples/custom-theme/src/index.scss
```
@use '@carbon/react/scss/components/button/tokens' as button-tokens with (
  $button-primary: #3f51b5
);
```
and a simplified [stackblitz](https://stackblitz.com/edit/github-olgjy6?file=src%2Findex.scss)
