### ISSUE TITLE
'Loading' component spins off centered @2x screen resolutions

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#1574]
## Detailed description

in Safari Version 12.0.2 (14606.3.4), macOS 10.14.2 (18C54), when a display is set to a @2x (Retina) resolution, the 'Loading' component spins off center, making it wobbly

This is true for either
https://next.carbondesignsystem.com/components/loading/code
or
https://www.carbondesignsystem.com/components/loading/code

## Steps to reproduce the issue
1. Using Safari Version 12.0.2 (14606.3.4), macOS 10.14.2 (18C54), with at least 1 display @2x resolution
2. navigate to https://next.carbondesignsystem.com/components/loading/code
3. observe the loading spinner

![wobbly loader 2x](https://user-images.githubusercontent.com/35537391/50242350-0b3d7480-0398-11e9-923f-007093964ca7.gif)

1. Using Safari Version 12.0.2 (14606.3.4), macOS 10.14.2 (18C54), with at least 1 display @1x 
x resolution
2. navigate to https://next.carbondesignsystem.com/components/loading/code
3. observe the loading spinner

![wobbly 1x](https://user-images.githubusercontent.com/35537391/50242395-29a37000-0398-11e9-9ed9-efbc8863ee16.gif)

The dimensions @2x might not be round:
![image](https://user-images.githubusercontent.com/35537391/50243041-0974b080-039a-11e9-925e-8d831333673e.png)

**Comment by asudoh** [comment]
@carbon-design-system/design @carbon-design-system/developers Do anybody see this issue still happening? Thanks!

**Comment by alisonjoseph** [comment]
This seems like it was fixed. [loading.mov.zip](https://github.com/carbon-design-system/carbon-components/files/3138450/loading.mov.zip)

![Screen Shot 2019-05-02 at 9 24 04 AM](https://user-images.githubusercontent.com/2753488/57082315-18f6f500-6cbc-11e9-95f8-e44b4e721335.png)
