### ISSUE TITLE
[Enhancing Awareness] Poster ☂️

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#15749]
## Background
The Carbon Initiative Project aims to encourage IBMers `to participate in Carbon Design and Development Office hours`. This initiative underscores the importance of integrating Carbon Office hours into IBM's design processes to enhance the quality and effectiveness of IBM products.

## Problem
There is a lack of awareness among IBMers regarding the initiatives undertaken by the Carbon team, such as Carbon Office hours and the [carbon-design-system](https://ibm.enterprise.slack.com/archives/C0M053VPT) slack channel. This lack of awareness deprives them of valuable opportunities for learning, collaboration, and enhancing the user experience of IBM products.

---

**Important Links** 
- [Figma File](https://www.figma.com/file/Btw3gqRmgPE4RtYSI2cZpq/POSTER?type=design&node-id=15-4&mode=design&t=qJDlYbC1zy5LhQmY-0) 
- [Slack Discussion](https://ibm.enterprise.slack.com/archives/C06JKAQLDL2)

**Comment by thyhmdo** [comment]
- Review with Mike and Jeannie 
- Aim to print and finish this work in one sprint

**Comment by laurenmrice** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/15761
