### ISSUE TITLE
Create an controlled Accordion stories

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#15757]
A lot of users have been asking questions regarding the Accordion usage when it comes to the controlled state from `AccordionItem`.
Here it is an example of what you are gonna build: https://stackblitz.com/edit/github-trp7pj-sgzpfm?file=src%2FApp.jsx

- [x] Create a new story called `Controlled`
- [x] Add testing using Playwright:
   - Add ACViolations checker
   - Add keyboard navigation testing

**Comment by Kritvi-bhatia17** [comment]
Solution: [PR #15827](https://github.com/carbon-design-system/carbon/pull/15827)

<img width="1202" alt="Screenshot 2024-03-06 at 12 24 26 AM" src="https://github.com/carbon-design-system/carbon/assets/158570656/fd4965e7-9e22-43d6-8624-f4714b3720ed">
