### ISSUE TITLE
A handler required for caret icon expansion in tree view component

### ISSUE THREAD

**Issue by PriyaTawate** [carbon-design-system/carbon#15760]
### The problem

In tree view component, we want to load data dynamically on click of a particular node.

### The solution

We want to load a list inside a particular folder when clicking on the caret icon. We need to get the name of the folder in that handler.

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
@PriyaTawate can you share some in-context examples or screen grabs of what you're going for here?

**Comment by PriyaTawate** [comment]
![screenshot](https://github.com/carbon-design-system/carbon/assets/70186152/f2575953-f1e6-4ed9-b582-1fd0922fb5c5)
What we are trying to achieve is load the list inside a particular folder dynamically so we need to call an api when a particular folder is expanded (caret icon before that folder name is clicked). And we need a handler for this purpose.

**Comment by tay1orjones** [comment]
Recently an experimental controllable API for TreeView was implemented, #15397 

This feature flag is [documented in storybook](https://react.carbondesignsystem.com/?path=/docs/experimental-feature-flags-treeview--overview) - check it out and let us know what you think. The goal with it being experimental is to get usage feedback to ensure it meets everyone's needs.

**Comment by tay1orjones** [comment]
@PriyaTawate Recently an experimental controllable API for TreeView was implemented, #15397. It added an `onActivate` that I think you can use for the purpose you describe.

This feature flag is [documented in storybook](https://react.carbondesignsystem.com/?path=/docs/experimental-feature-flags-treeview--overview) - check it out and let us know what you think. The goal with it being experimental is to get usage feedback to ensure it meets everyone's needs.
