### ISSUE TITLE
[Bug]: Nothing happen when I clicked on "Show more"  in <CodeSnippet> component.

### ISSUE THREAD

**Issue by gayatri2023** [carbon-design-system/carbon#15774]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.49.0

### React version

v17.0.2

### Description

The `Show more` button does not cause the windows to enlarge when the string is sufficiently short. The `Show more` button functions when the string is longer. It appears that there is a calculation error with the `Show more` button.

### Reproduction/example

https://stackblitz.com/edit/github-kjuqye?file=src%2FApp.jsx

### Steps to reproduce

Create a multiline code snippet with sufficiently short string and try to click on `Show more` button. We noticed this in Windows Chrome environment. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@gayatri2023 can you explain the issue a bit more? The `Show More` button will only expand the content area of the `CodeSnippet`; it will not make the browser window any larger. In your example, there is only 1 line of whitespace to expand to, so it just expands so that you do not need to scroll to see the whitespace at the end.

**Comment by gayatri2023** [comment]
Hi @tw15egan 
To understand the issue clearly, could you please run the code snippet in Windows - Chrome and Mac - Chrome environments. You will be able to see the difference of `CodeSnippet` component performance.

**Comment by gayatri2023** [comment]
FYR, Issue in Windows - Chrome environment. 

https://github.com/carbon-design-system/carbon/assets/125148169/8a8b91d1-3cab-40c2-8b6d-f2ed6c162e6a

**Comment by markfarkas-camunda** [comment]
I also encountered this bug, and I can reproduce this on Windows 11 using Chrome 121. 
Package version: v1.50.0, React version: v18.2.0
Example code: https://stackblitz.com/edit/github-aoabhq-pwfhgb?file=src%2FApp.jsx
