### ISSUE TITLE
Tabs: update story example to include correct color for the panel

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15787]
In the storybook examples for contained tabs the content panels need to are not showing the correct color and are causing confusion for users. The panel should be using `layer-01` and appear connected to the tabs. We especially need this for the examples being used in the live demos on the website.

This is more what we want the story to look like:

<img width="1029" alt="image" src="https://github.com/carbon-design-system/carbon/assets/11670886/c8a0734c-0b6a-4daa-9458-fa36f20f5b1e">

---
Original comment from @mjabbink 
<img width="723" alt="image" src="https://github.com/carbon-design-system/carbon/assets/11670886/a31cebc1-051b-4aea-8f51-41e3c6661ee6">

**Comment by mjabbink** [comment]
Thanks for creating this @aagonzales. The M2 Carbon AI product teams are in need of this to be corrected since most are all pretty much using tabs.
