### ISSUE TITLE
Data Table - Stroke

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#158]
Data Table stroke should only be `1px `not `2px`.

**Comment by tw15egan** [comment]
@aagonzales we were running into problems with the stroke and the hover outline. If we go to 1px, the data-table hover outline disappears on the left and right of a data cell item. 

@hellobrian do you have any ideas on how to fix this?

**Comment by hellobrian** [comment]
Yeah, I tried doing the same thing as @tw15egan and simply changing it to `1px` causes other unwanted side-effects. Resolving this issue is going to require a deeper dive into the code for some refactoring.

**Comment by aliciahickman** [comment]
@aagonzales @hellobrian I may have an easy css fix for this! Going to attempt to test in IE (seems to be working well in chrome and FF so far) and will submit a PR hopefully soon :D

**Comment by tw15egan** [comment]
@aliciahickman that would be awesome, thanks for taking a look!
