### ISSUE TITLE
[Bug]: OverflowMenuItems inside a modal appear behind the modal

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#15816]
### Package

@carbon/styles

### Browser

Chrome

### Package version

1.51.0

### React version

18

### Description

[Surfaced in slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1706717420334319). When an OverflowMenu and it's OverflowMenuItems are placed inside a Modal, the OverflowMenuItems appear behind the modal instead of atop it. 

![image](https://github.com/carbon-design-system/carbon/assets/3360588/97bf2eb4-1b46-47c9-94ab-ca8ae8708aee)

The z-index is 6000 when it should be 9000. We have styles intended to fix this defect but the selector isn't right.

https://github.com/carbon-design-system/carbon/blob/de4793c1f54602da619ddff6b2c6f62243643392/packages/styles/scss/components/modal/_modal.scss#L439-L444

The floating menu is rendered via a portal and is not a descendant of .cds---modal, so the style is not applied.

This is a regression of https://github.com/carbon-design-system/carbon/issues/8693, I think caused by https://github.com/carbon-design-system/carbon/pull/12221

One workaround would be to apply a higher z-index value via your own styles in your application.

### Reproduction/example

https://stackblitz.com/edit/github-u4hjak?file=src%2FApp.jsx

### Steps to reproduce

Click to open the OverflowMenu and observe that it is behind the modal.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Just to be clear, this is happening in the current implementation of OverflowMenu that uses FloatingMenu, not the new "V2" implementation behind a feature flag that uses the new Menu primitive(s).

**Comment by tay1orjones** [comment]
I'm actually going to mark this as a severity 2 because it prevents the user from selecting any of the options.

**Comment by mranjana** [comment]
@tay1orjones Can I pick this?
