### ISSUE TITLE
[Bug]: Adjacent ellipses in PaginationNav

### ISSUE THREAD

**Issue by cmarcink** [carbon-design-system/carbon#15830]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.50.0

### React version

v17.0.2

### Description

Should not have adjacent ellipses in pagination.
![image](https://github.com/carbon-design-system/carbon/assets/23342726/9354af05-c808-4720-9263-24b942182824)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-paginationnav--playground&args=itemsShown:4;totalItems:10

### Steps to reproduce

1. Render with props itemsShown = 4, totalItems = something >= 10
2. Select a page from the ellipses
3. Select the first page
4. Notice the adjacent ellipses

![image](https://github.com/carbon-design-system/carbon/assets/23342726/b5de1cd4-eba7-4a6c-81b8-7e10d6fe3942)

### Suggested Severity

None

### Application/PAL

Cloud Pak for AIOps

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting, can confirm this looks off. I think something's off within this logic here: https://github.com/carbon-design-system/carbon/blob/754ff7965e3693bd445e8a4d46b4b31bc7e91417/packages/react/src/components/PaginationNav/PaginationNav.tsx#L454-L466

**Comment by tay1orjones** [comment]
It's clear we don't want the overflows next to one another, but this brings up an interesting question for me: what do we _want_ to happen? Should overflows be limited in certain cases beyond what we already have? What should we be aiming for when we fix this? 

@carbon-design-system/design do you have any thoughts?

**Comment by janhassel** [comment]
When my design team was originally working on this we prototyped a few approaches, including the one outlined by @hollyos.

What we noticed during internal user testing was that it is extremely distracting / confusing to users when the width of the component changes while flipping through the pages. It also defeated the reason why we needed such a compact component since if there is enough space to show another item, why not show it initially.

I'm referring to these examples:
```
◂ 1 2 … 9 ▸
◂ 1 … 3 … 9 ▸
◂ 1 … 8 9 ▸
```

```
◂ 1 2 3 … 9 ▸
◂ 1 … 3 4 … 9 ▸
◂ 1 … 7 8 9 ▸
```

That's why we opted to include the overflows in the number of items shown when contributing the implementation.

**Comment by laurenmrice** [comment]
I feel like Holly and Jan's approach for this makes sense, to try to keep the page list visually consistent for visible pages regardless of the selection method for each active page, and this solution would resolve the problem of having the double ellipsis appearing next to each other in the pagination.

Adding this as props is also a good idea, so people can use this if they need more control for their pagination needs.

**Comment by thyhmdo** [comment]
Please [review the design specs here](https://github.com/carbon-design-system/carbon/issues/17628) for this fix

**Comment by riddhybansal** [comment]
Completed by #17628
