### ISSUE TITLE
[Bug]: Modal fade effect applied without setting `hasScrollingContent` prop

### ISSUE THREAD

**Issue by btepe** [carbon-design-system/carbon#15890]
### Package

@carbon/react

### Package version

1.52.0

### Description

The storybook docs on composed modals state that a visual fade effect can be applied to the modal content by setting the `hasScrollingContent` prop to `true` (see [storybook docs page](https://react.carbondesignsystem.com/?path=/docs/components-composedmodal--overview#overflow-content)). 

In fact, the styling is applied without setting the prop, see [`ComposedModal` code](https://github.com/carbon-design-system/carbon/blob/2e8523541f0509dee7f30a1a08947a326ade14f2/packages/react/src/components/ComposedModal/ComposedModal.tsx#L61). This broke one of our modals, because content is hidden at the top and bottom of some elements.

The CSS property `mask-image` should only be applied, if the prop is specified imo. This behaviour right now rpevents our teams to upgrade to any Carbon version above `1.50.0`.

### Reproduction/example

https://stackblitz.com/edit/carbon-v11-prxvfh?file=src%2FApp.jsx

### Steps to reproduce

Look at the modal in the example link, the prop is not set, but the `mask-image` property is applied anyways

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
@btepe it looks like the spacing that should be there is missing, has to do with how we are applying it. Just opened a PR to fix.
