### ISSUE TITLE
Didn't see a date picker in the components

### ISSUE THREAD

**Issue by antonmc** [carbon-design-system/carbon#159]
Was using sketch to create a form view that required date inputs. Didn't see a date picker, though this could well be user error :)

**Comment by bsonefeld** [comment]
Hey @antonmc ! We're working through some final tests for the Date Picker right now, you can track it's progress in this PR: #143 . Once we get it merged in, it'll be available in the code. The latest version of the [Carbon Design Kit](https://github.com/carbon-design-system/carbon-design-kit) should have Date Picker in there 👍

**Comment by antonmc** [comment]
great, thanks @bsonefeld :)
