### ISSUE TITLE
[Bug]: SideNavMenu remains expanded, when Rail SideNav collapses

### ISSUE THREAD

**Issue by Kreynar** [carbon-design-system/carbon#15900]
### Package

@carbon/react

### Browser

Edge

### Package version

1.51.0

### React version

18.2.0

### Description

SideNavMenu remains expanded, when Rail SideNav collapses

![image](https://github.com/carbon-design-system/carbon/assets/13556960/e7f2423c-855e-423d-9937-31e079511fd6)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-ui-shell-sidenav--side-nav-rail-w-header

### Steps to reproduce

1. Hover cursor over SideNav for it to expand
2. In expanded SideNav expand first SideNavMenu
3. Move cursor away from SideNav for it to collapse into rail
4. Now you should see that there is additional empty space between first item and second item in SideNav

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by lowsky** [comment]
We noticed we have the same issue, as documented in #16061.

**Comment by tay1orjones** [comment]
It looks like this was introduced in 11.47.0, I think it might've been this PR: 
* https://github.com/carbon-design-system/carbon/pull/15349
