### ISSUE TITLE
Code Snippet adds newline when copying and pasting manually

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon#1594]
This prevents users from pasting the command to the CLI, if they don't use the copy button.

Steps to reproduce:

Double-click any code snippet. (The snippet at https://www.carbondesignsystem.com/components/code-snippet/code will do.)

Paste it into the CLI (or text editor).

Error:

If it's a CLI command, you'll see the following error:
"-bash: syntax error near unexpected token `newline'"

If it's into a text editor, you'll notice that it adds a newline that you didn't put there yourself.

**Comment by cal-smith** [comment]
>Double-click a command in the registry quickstart, and copy it.

Do you have any more info? I'm not sure what the registry quickstart is.

I'm assuming this is with the single or multiline code snippets? I don't see anything in the source that would introduce newlines, and I could only repro it in the stories by manually including a newline in the source string.

Does `someCodeString.trim()` or similar help? Could you create a [minimal repro in codesandbox](https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox)? Could you share the relevant segment from your template?

Thanks!

**Comment by mlinnem** [comment]
<img width="702" alt="screen shot 2019-01-11 at 11 20 57 am" src="https://user-images.githubusercontent.com/1547834/51049294-1056a380-1593-11e9-8244-50800505f3ef.png">

Here's the two GIFs:

https://gph.is/2CfQHoK
https://giphy.com/gifs/4WFEfKzGIxRucYIKJe

**Comment by mlinnem** [comment]
In the second GIF, I'm not hitting enter, it's just auto-entering my command because of the newline.

**Comment by mlinnem** [comment]
So it seems that other CLI snippets online have this same issue: https://cloud.google.com/sdk/docs/quickstart-macos

Seems to be a result of the user agent as oppose to something we're doing in particular. It's not great but not necessarily worth pursuing further imho. As such I'm going to close this.
