### ISSUE TITLE
[AI] Phase 3: update tile component to new visuals

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#15946]
[Figma files](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=2302%3A103910&mode=design&t=CmPCQCPF6fEpnGDA-1)
<img width="1312" alt="Tiles - White v3" src="https://github.com/carbon-design-system/carbon/assets/11670886/992708cc-0f40-455f-9a15-9f81608833b2">
<img width="1312" alt="Tiles - Gray 100 v3" src="https://github.com/carbon-design-system/carbon/assets/11670886/9f91af11-7fca-4799-b774-31af35017d19">

**Comment by tay1orjones** [comment]
@tw15egan is this one finished?

**Comment by tw15egan** [comment]
@tay1orjones I never was assigned so it looks like this one slipped by - most of the updates should be taken care of with the token updates, but I'll check go through this component and ensure its to spec
