### ISSUE TITLE
[Bug]: <Loading />. component: Issue with Typescript declaration for the `withOverlay` prop

### ISSUE THREAD

**Issue by nkn2022** [carbon-design-system/carbon#15947]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.52.0

### React version

17.0.2

### Description

Noticed that the `Loading` component is not allowed to be defined without the `withOverlay` prop which is different from the [doc](https://react.carbondesignsystem.com/?path=/docs/components-loading--overview )
Expected to default `true` when not specified.

The PropTypes shows that `withOverlay` is optional, so likely an oversight in the TypeScript [type declaration](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Loading/Loading.tsx#L44).

### Reproduction/example

https://stackblitz.com/edit/github-9bhxhq?file=src%2FApp.tsx

### Steps to reproduce

Just using the Loading component in a typescript file shows this compile error. You can see this in the editor here: https://stackblitz.com/edit/github-9bhxhq?file=src%2FApp.tsx

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Thanks for opening that @nkn2022 
We just have to set the prop as optional in the interface

packages/react/src/components/Loading/Loading.tsx
```
- withOverlay: boolean;
+ withOverlay?: boolean;
```
