### ISSUE TITLE
[Tile] Update the border on Expandable with interactive tiles

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#15940]
Storybook link: https://react.carbondesignsystem.com/?path=/story/experimental-feature-flags-tile--expandable-with-interactive

Since the entire tile is not clickable, the border should be around the button instead of being around the tile

![Expandable tiles](https://github.com/carbon-design-system/carbon/assets/77697351/0a85ebc7-d6b1-46b1-8499-a1d677fc2438)

**Comment by tay1orjones** [comment]
This should be a pretty simple style-only change for the ExpandableTile with interactive elements
