### ISSUE TITLE
[Bug]: `CarbonIconType` is not exported from `@carbon/react/icons`

### ISSUE THREAD

**Issue by cuppajoey** [carbon-design-system/carbon#15974]
### Package

@carbon/react, @carbon/icons-react

### Package version

1.52.0

### Description

Since upgrading to `@carbon/react` ~~v1.52.0~~ v1.41.0 (or later), `CarbonIconType` cannot be imported from `@carbon/react-icons` (or directly from `@carbon/icons-react`).

<img width="643" alt="image" src="https://github.com/carbon-design-system/carbon/assets/14837881/64712d7e-85d4-4bc1-9c64-026dce1841d0">

I think the issue is that before ~~v1.52.0~~ v1.41.0 type definitions for `@carbon/icons-react` came from DefinitelyTyped which exported `CarbonIconType`. Now that `@carbon/icons-react` ships its own types<sup>1</sup>, DefinitelyTyped removed their support for that package<sup>2</sup>. 

Reference:
1. Types added to `@carbon/icons-react`: carbon-design-system/carbon#14714
2. Types removed from `@types__icons-react`: DefinitelyTyped/DefinitelyTyped#67176

### Reproduction/example

https://stackblitz.com/edit/github-qo3ucm?file=src%2FApp.tsx

### Steps to reproduce

1. Install `@carbon/react` v1.52.0.
2. Try to import `CarbonIconType` from `@carbon/react/icons`.
3. Hover over import and view error: `Module '@carbon/react/icons' has no exported member 'CarbonIconType'`.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by lluisrojass** [comment]
Small workaround, unsure if this impacts the `sev2` status 

```ts
import * as Icons from '@carbon/react/icons';

export type CarbonIconType = (typeof Icons)[keyof Omit<typeof Icons, 'Icon'>];

```

**Comment by tay1orjones** [comment]
@cuppajoey @lluisrojass I've got https://github.com/carbon-design-system/carbon/pull/15979 up with a potential fix, let me know what you think

**Comment by cuppajoey** [comment]
> @cuppajoey @lluisrojass I've got #15979 up with a potential fix, let me know what you think

@tay1orjones It works great for me. Thanks for the quick work 🙌 !

**Comment by keithcha** [comment]
Could this fix be ported to v10?

**Comment by cuppajoey** [comment]
> Could this fix be ported to v10?

@keithcha I don't think this issue existed in v10 because Carbon didn't export its types directly. They came from `@types/carbon-components-react`.
