### ISSUE TITLE
[Feature Request]: HeaderContainer should either treat its render children as a function or expose a props pass-through

### ISSUE THREAD

**Issue by lluisrojass** [carbon-design-system/carbon#15975]
### The problem

The UI Shell `<HeaderContainer />` component expects `render` to be a React component. Using the render props pattern (shown in the official storybook example [here](https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-side-nav&globals=theme:white)) will trigger un/re-mounting, [which also remounts all children, dumping all state](https://legacy.reactjs.org/docs/reconciliation.html#elements-of-different-types). 

An effective solution might be to hoist state above `<HeaderContainer />`, however this promotes poor organization, and does not handle for all issues (e.g. child `img` sources are re-fetched causing visual jitter). A user could also provide a React component for `render`, with the limitation that it be severed from accessing any local parent state or depend on any external prop, which would only leave room for trivial use cases, or require convoluted workarounds.  
  

### The solution

We could treat `render` as a function and not a component, however it would represent a non-backwards compatible change which would require a major version upgrade according to semver. 

A simple, backwards compatible solution would be to expose a props pass-through object in `HeaderContainer` which is spread onto the child component. 

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> Using the render props pattern (shown in the official storybook example [here](https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-side-nav&globals=theme:white)) will trigger un/re-mounting, [which also remounts all children, dumping all state](https://legacy.reactjs.org/docs/reconciliation.html#elements-of-different-types).

@lluisrojass Hey I'm just a bit confused here, let me see if I can clarify. You're suggesting that any prop changes you provide to the stuff within `render` is going to cause a rerender - and if we had a prop passthrough it would avoid this due to the shallow prop comparison react does to determine if a re-render is necessary?

Wouldn't a more robust solution be for you to use `useMemo` or `useCallback` on what you pass to `render`?

**Comment by lluisrojass** [comment]
Nope, sorry maybe I can produce an example in a bit, but re-renders to HeaderContainer will produce an unmount/remount to everything being rendered inside the render prop. That is the core issue.

**Comment by lluisrojass** [comment]
Hello, here is a repro. You can see the re-mounts with both the log and the image refetching: https://stackblitz.com/edit/github-gab1sd-clhl35?file=src%2FDiceRoll.jsx. 

We could define a whole Component to pass into `render`, but we would loose access to dice state. 

Your `useMemo`/`useCallback` suggestion would also be subject to re-mounts because we would need to re-generate when dice state changes. Also reasonable heads disagree about whether this is an anti-pattern or not (not saying it is / isn't) (source: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md#disallow-creating-unstable-components-inside-components-reactno-unstable-nested-components
).

**Comment by tay1orjones** [comment]
> A simple, backwards compatible solution would be to expose a props pass-through object in HeaderContainer which is spread onto the child component.

Let's try it! 👍 A PR would be awesome if you're interested

**Comment by lluisrojass** [comment]
Ok great, seeing this now, will spend some time on this tomorrow
