### ISSUE TITLE
[Enhacement]: Dropdown should be auto scrolled to the focused item 

### ISSUE THREAD

**Issue by nachom12** [carbon-design-system/carbon#15978]
### The problem

An item is being focused in the dropdown but the user is not seeing it.

### The solution

If an item is focused, then the dropdown scroll should be set automatically to it.

### Examples

Combobox component already has this behavior implemented.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
```[tasklist]
### Tasks
```

**Comment by tay1orjones** [comment]
@nachom12 are you meaning when you open the dropdown and type something, it moves the focus ring to an item that matches what you type? and that newly focused item could be below the currently visible area, so it needs a `scrollIntoView()` or something similar called on it?

**Comment by nachom12** [comment]
With arrow keys it works fine, but I need autoscroll when typing something.

For example: When I open the dropdown and type something It changes the focus to a matching item, but scroll doesn't set automatically.




https://github.com/carbon-design-system/carbon/assets/39068356/b94e97aa-ee27-4073-a317-0ff1faf008fa

**Comment by BeWild-ui** [comment]
Hello there, may I ask the Carbon team to raise the business priority of this topic to high or even highest?
Actually this is a real regression from carbon v10 and as a result for end users having to use arrow keys to select among long drop-down lists it just discredits the whole application based on Carbon components.
May I please ask to provide an ETA for the resolution of this regression?
Thanks you so much for your understanding.

**Comment by tay1orjones** [comment]
I agree, this was working in v10 and is technically a regression.

**Comment by tay1orjones** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/16935
