### ISSUE TITLE
[Bug]: [TextInput.PasswordInput] showPasswordLabel and hidePasswordLabel not working

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#15986]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.0

### React version

18.2.0

### Description

In TextInput.PasswordInput component `showPasswordLabel` and `hidePasswordLabel` not working. 

### Reproduction/example

https://stackblitz.com/edit/github-pe88wq?file=src%2FApp.jsx

### Steps to reproduce

https://stackblitz.com/edit/github-pe88wq?file=src%2FApp.jsx

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by hollyos** [comment]
@nmgokhale It looks like the `TextInput.PasswordInput` was deprecated in [c62b520](https://github.com/carbon-design-system/carbon/commit/c62b5206cd176860ae8921dcae634bd7c848018a). It throws a warning in the console but doesn't really seem to be well documented anywhere else.

<img width="394" alt="Screenshot 2024-04-01 at 12 44 34" src="https://github.com/carbon-design-system/carbon/assets/4097509/b940f53c-f4a5-4cd7-a8fe-49de7f4dc3cd">

@preetibansalui Not sure if deprecated components are maintained. But an update to the docs, storybook, etc. would help alleviate the confusion. Should call out `TextInput.PasswordInput` is deprecated and point to the `PasswordInput` component. Is there a scheduled EOL for the sub-component?

**Comment by nmgokhale** [comment]
@hollyos As per` @carbon/react@1.54.0` docs https://react.carbondesignsystem.com/?path=/docs/components-textinput--overview
`TextInput.PasswordInput` is a valid component.

When I search for `PasswordInput` in docs, it shows experimental unstable component which doesn't look correct -
![Screenshot 2024-04-01 at 11 40 14 AM](https://github.com/carbon-design-system/carbon/assets/25124000/e19171a6-3b52-436e-ac06-99cc685281cc)

**Comment by hollyos** [comment]
> As per` @carbon/react@1.54.0` docs https://react.carbondesignsystem.com/?path=/docs/components-textinput--overview `TextInput.PasswordInput` is a valid component.
> 
> When I search for `PasswordInput` in docs, it shows experimental unstable component which doesn't look correct

@nmgokhale Absolutely! Based on the docs, I understand your confusion. I am just getting back to this codebase after 8 years away. I was trying to ask @preetibansalui or someone from the @carbon-design-system/developers-system team (@tay1orjones or @sstrubberg ?) if deprecated components should even be worked on.

If the plan is to EOL the component rather than continue support, It would seem like it's a better use of time and effort to update the docs to:

1. More clearly, mark the `TextInput.PasswordInput` sub-component as deprecated. Sharing details of EOL for migration off the component for current users (unless it needs to remain backward compatible).
2. Add a link to the `TextInput.PasswordInput` docs and code to the new `PasswordInput` component instead so that people no longer try to use the deprecated and no longer supported component.

**Comment by preetibansalui** [comment]
Hi @nmgokhale, @hollyos : As I can see in V11 migration docs, It is mentioned that TextInput.PasswordInput will be replaced with PasswordInput. Please check the doc [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/docs/migration/11.x-namespaced-exports.md) However, I tried and found that we can still use it in the old way. 
I am able to reproduce the issue for showPasswordLabel and hidePasswordLabel in chrome browser. Will update once it is fixed.

**Comment by tay1orjones** [comment]
Yeah `TextInput.PasswordInput` is deprecated in v11, to be removed in v12. It's actually the same singular component source behind both exports, so @preetibansalui's fix should populate to both no matter which one you're using.

I agree we need to improve documentation in the storybook around the deprecation. It's even more confusing wrt the experimental "fluid" inputs, which is basically a new visual variant of the same component. imo PasswordInput needs it's own section in the storybook, and the passwordinput story removed from the TextInput section. Same thing for the Fluid text input section. I opened https://github.com/carbon-design-system/carbon/issues/16213 for this
