### ISSUE TITLE
[Bug]: HeaderMenuButton not rendering when width is more than 1050px

### ISSUE THREAD

**Issue by RSamal** [carbon-design-system/carbon#15987]
### Package

@carbon/react

### Browser

Chrome

### Package version

latest

### React version

latest

### Description

UI does not show the HeaderMenuButton once it cross 1055px. Also reported here https://github.com/carbon-design-system/carbon/issues/10045#issuecomment-2002302367 . screen dimension screenshots are added below for reference. Hamburger icon does not show after 1056px. Also in the below example try to resize the preview window to reproduce it(drag to the left)
https://stackblitz.com/edit/github-3rmcjk?file=.vscode%2Fsettings.json

Aslo same issue happens with SideNav 
Shows with 1055px
![Screenshot 2024-03-16 at 9 18 20 PM](https://github.com/carbon-design-system/carbon/assets/5267629/af98555a-7029-4173-8eba-cfc8e04c0ef9)

Does not Show with 1056px
![Screenshot 2024-03-16 at 9 19 01 PM](https://github.com/carbon-design-system/carbon/assets/5267629/35acdffe-04c1-47b0-9218-2e290b71dbda)

### Reproduction/example

https://stackblitz.com/edit/github-3rmcjk?file=.vscode%2Fsettings.json

### Steps to reproduce

Jsut follow the IBM carbon react tutorial. It does not work at the moment. please resize the preview windows https://stackblitz.com/edit/github-3rmcjk?file=.vscode%2Fsettings.json here to see .

### Suggested Severity

None

### Application/PAL

UI

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @RSamal 
That is an intentional behaivour. We have set a breakpoint that causes this action.

https://github.com/carbon-design-system/carbon/blob/abff3a5b12dee8edef8c81b4e935562293e8e545/packages/styles/scss/components/ui-shell/header/_header.scss#L133-L137

https://github.com/carbon-design-system/carbon/blob/8e788402b319f29b27187a7e4e3e903ae37c9511/packages/grid/scss/_config.scss#L50-L54
