### ISSUE TITLE
[Bug]: Tooltips broken when used inside DataTable

### ISSUE THREAD

**Issue by FFahrenheit** [carbon-design-system/carbon#15981]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.47.0

### React version

18.2.0

### Description

When using Tooltips inside a Table the tooltip message breaks

<img width="614" alt="image" src="https://github.com/carbon-design-system/carbon/assets/21372626/5ba1500e-051b-4045-8398-37470e0142bc">

### Reproduction/example

https://stackblitz.com/edit/github-hpqkqe?file=src%2FApp.jsx

### Steps to reproduce

1. Inside a table add a Tooltip close to the borders (top, bottom, left, right) and hover the tooltip

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by FFahrenheit** [comment]
As a note, I fixed the issue in the project I'm working on by overriding `cds--data-table-content`: 

```
.dataList-container {
    .cds--data-table-content {
        overflow: visible;
    }
}
```

**Comment by guidari** [comment]
Hey @FFahrenheit, thanks for oppening that!

Probably this can be solved if we add this code inside the `cds--data-table-content `. That way all components that uses Popover will be visible.

packages/styles/scss/components/data-table/_data-table.scss
```
    &:has(.#{$prefix}--popover-container) {
      overflow-x: visible;
    }
```

**Comment by mranjana** [comment]
@guidari , Can I pick this up?

**Comment by FFahrenheit** [comment]
Thanks @guidari , I tested it and it works perfectly! 👍🏽 

Can I be assigned to this issue so I can submit the PR?

**Comment by tay1orjones** [comment]
This was fixed via 
* https://github.com/carbon-design-system/carbon/pull/14654

https://stackblitz.com/edit/github-hpqkqe-uynpqz?file=src%2FApp.jsx,package.json

Tooltip with `autoAlign` attempts to place the tooltip within the viewport and is no longer clipped by the table


https://github.com/carbon-design-system/carbon/assets/3360588/2198d265-bf3f-483c-889c-288ea47ba3a8
