### ISSUE TITLE
[Bug]: [NumberInput] Can't enter negative numbers

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#15985]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.0

### React version

18.2.0

### Description

I can't type negative numbers (eg. -1) in the NumberInput field. Also when I want to remove all digits, number input is set to `0`. Even after setting `allowEmpty`.

Following screen recording from v10 (https://v10.carbondesignsystem.com/components/number-input/code/#live-demo) no longer works in v11 - 

https://github.com/carbon-design-system/carbon/assets/25124000/5fec90a3-69a6-4ec1-a7fc-9381659c37bb

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground

### Steps to reproduce

Please see description

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by afkoziol** [comment]
I was just looking into an e2e test failure of ours and it was a result of not being able to empty the input to enter a new number.  The zero gets in the way, probably not desirable UX.  I believe this was introduced with #15739 

Thanks

**Comment by ecrvich** [comment]
I discovered myself today that `allowEmpty` has no effect. Maybe consider only zero-filling if the input is empty _**after**_ focus is lost? Kind of annoying to do it while the user is still typing, and leading zeros suggest octal format to plenty of folks. FWIW in form use, that leading zero DOES of course get passed to the back end intact, so how it's interpreted depends on how the string is converted to a number on that end.

**Comment by hollyos** [comment]
@nmgokhale I tested this in the [live demo](https://v10.carbondesignsystem.com/components/number-input/code/#live-demo) and Storybook. It works in both instances. This issue was likely due to the min value equaling 0. The input allows for negatives when `min` is updated to a negative value. The empty input is fixed in my PR (#16100)

@2nikhiltom, here's a heads-up that I put up a PR (#16100) for this issue (since you're self-assigned).
