### ISSUE TITLE
[Bug]: Datepicker & Datepicker range calendar icon in disabled state

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#15983]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.0

### React version

18.2.0

### Description

Calendar icon doesn't look disabled in Datepicker & Datepicker range components -

Datepicker -
![Screenshot 2024-03-15 at 3 55 31 PM](https://github.com/carbon-design-system/carbon/assets/25124000/de6eee6f-d00d-4e72-8293-2efc8d7190c8)

Datepicker range - 
![Screenshot 2024-03-15 at 3 54 39 PM](https://github.com/carbon-design-system/carbon/assets/25124000/37dd260d-0e77-4dae-830a-1a1264529f2a)

### Reproduction/example

https://stackblitz.com/edit/github-vvajoh?file=src%2FApp.jsx

### Steps to reproduce

Please see reproduction example above.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by anjaly0606** [comment]
Hi @nmgokhale 
Can i take up this issue ?
