### ISSUE TITLE
Update menu component to be ssr friendly

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#16004]
eslint-plugin-ssr-friendly was added https://github.com/carbon-design-system/carbon/pull/15903

- Update [menu component](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Menu/Menu.tsx) to be ssr friendly and remove ignore comment

**Comment by atasmohammadi** [comment]
any updates on this? :)
