### ISSUE TITLE
Properly deprecate PopoverAlignment type values

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#16009]
In https://github.com/carbon-design-system/carbon/pull/14654 all Popover-based components were unified to use new values for the `align` prop.

The old values need to be properly deprecated so we can ensure consumers know to stop using them.

Pull the old values out into their own type, mark it as deprecated via jsdoc
Update PopoverAlignment to be a union of the new values and the new deprecated type
Write a custom validator function for proptypes that pops a warning when a deprecated value is used
Refactor all usages where  `PopoverAlignment` is used to normalize `tooltipPosition` with `tooltipAlignment` such as in Button

```[tasklist]
- [ ] https://github.com/carbon-design-system/carbon/issues/16326
```

**Comment by 2nikhiltom** [comment]
closed via https://github.com/carbon-design-system/carbon/pull/16346
