### ISSUE TITLE
[Bug]: Tearsheet influencer, span used to contain label to determine current stage selected 

### ISSUE THREAD

**Issue by adamlsmith981** [carbon-design-system/carbon#16017]
### Package

carbon-components

### Browser

Chrome

### Package version

10.57.2

### React version

17.0.0

### Description

Tearsheet (from @carbon/ibm-products) Influencer has `<span class="bx--assistive-text">Current</span>` in the DOM that indicates which stage of the influencer is currently selected. 

Writing a test to identify this tag, I was unable to use Cypress steps to get the span element that contains the "Current" label in the DOM. I have had to use the following code instead:

```
cy.findByRole("button", { name: new RegExp(stage) }).within(() => {
      cy.findByText("Current").should("exist");
    });
```

Image to describe the elements in the DOM, highlighting where the "Current" label appears in the tearsheet influencer.

<img width="795" alt="image" src="https://github.com/carbon-design-system/carbon/assets/67642683/765e609e-6697-4e17-a56b-a76cdc199ebc">

Is this label subject to translation? 

### Reproduction/example

https://codesandbox.io/p/devbox/gracious-meadow-wbhg78?file=%2Fpackage.json%3A22%2C31-22%2C37

### Steps to reproduce

- Look at the Influencer in dev tools and you can see that the labelling added to determine the "Current" stage of the influencer is in a span. 

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> Is this label subject to translation?

Yes, via the `translateWithId` prop

https://github.com/carbon-design-system/carbon/blob/484ac26f59b03b1a9a13f646a91f4994c603ea80/packages/react/src/components/ProgressIndicator/ProgressIndicator.tsx#L21-L26
