### ISSUE TITLE
[Education] Clean up and remove old slides

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#16024]
### Get started
Create a duplicate of the current [Client Engineering deck](https://ibm.ent.box.com/file/1178199975561?s=ol0ixsjzndvga3d2qmjhwgugo3b2e868) to get started. We will use this as the deck that we want to clean up.

Reference and become familiar with [Olivia's deck for AEM](https://ibm.ent.box.com/file/1475834202161). Her deck has been updated most recently and can help guide us on how to cut our deck down in length to allow for more Q&A at the end.

**Things to consider changing**
Olivia worked on a version of this deck for AEM where she cut down several sections.
- [x] Can the upfront of the Client Engineering deck be cut where we explain the ecosystem? (look at Olivia's upfront).
- [x] How much time do we need to spend on the elements? Where can we consolidate?

----

### Update old slides
Look at the following old slide content:

* Ecosystem slides need updating (10, 14)
* Website slides often need updates (17, 18, 19, 20, 58, 87)
* Grid modes are now called gutter modes (24)
* Check if token pages need to be changed out. (52, 59)

- [x] First, decide what old slides above are still relevant and worth keeping to tell the story. 
- [x] Next, update the old slide content we want to keep.

----

### Remove or check these slides 

**De-emphasize hero brands**
- [x] We don't emphasize hero brands anymore, so we need to remove this content. Instead, see if we could show AI work here which could be more interesting. (61-65)

**Remove slide**
- [ ] Kill v11 slide, it is old news. (90)

**Comment by thyhmdo** [comment]
Jeannie will refine this issue more
