### ISSUE TITLE
Accordion as OL when needed (instead of always a UL)

### ISSUE THREAD

**Issue by bdanbury** [carbon-design-system/carbon#16040]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@carbon/react@1.53.1` for the project I'm working on.

We are using Accordion to display a list of items which are best contained within an OL rather than a UL. We have patched v1.53.1 to allow wrapping items in either ul (default) or ol. Please consider carrying this work into the main branch.

I've attached the diff that solved my problem:

[@carbon+react+1.53.1.patch](https://github.com/carbon-design-system/carbon/files/14728988/%40carbon%2Breact%2B1.53.1.patch)

**Comment by tay1orjones** [comment]
Thanks for attaching that patch file, it confirms there's no styling changes necessary to support this. Is the reasoning for using an OL in your case just improved semantics?

Docs on the website state that a list is necessar

**Comment by tay1orjones** [comment]
Sorry, hit the wrong button 🙃

**Comment by tay1orjones** [comment]
For this we'd want to avoid an `as` prop. Instead this should be something like an `ordered` boolean prop that toggles `ol` instead of the `ul` default.

**Comment by Tresau** [comment]
I can work on this @tay1orjones
