### ISSUE TITLE
Implement auto-complete textfield allowing for selection of existing value (like ComboBox) or specifying a new value

### ISSUE THREAD

**Issue by mpauser** [carbon-design-system/carbon#1605]
### Summary

https://v0.material-ui.com/#/components/auto-complete
material-ui provides an auto-complete component which shows a user a simple textfield. The user can then enter text and any matches are then shown in a simple list. The user can select one of these values or continue to enter their own value. It also allows for the initial click in the textfield to automatically display the list.

I see no component in carbon-ui that provides the same features. Close, but not complete. Design and development.

### Justification
While several carbon components implement different aspects of the material-ui autocomplete, there isn't a single component that does it all.
* The existing ComboBox does provide a textfield and displays a list, but it requires that the user select a value in the list -- versus being able to enter a new value. Using your ComboBox example, if I enter "Option 1a" the X to clear the field and the list of existing values remains visible. I can't simply use "Option 1a" is the value.
* The existing FilterDropdown shows a [ ] checkbox and allows for multiple selection of existing values (not needed in this usecase) and does not allow a user to roll their own value.

### Desired UX and success metrics
The UI component has a list of existing values (such as parameter names) from which the user can select from -- but also allows them to enter their own value. As there could hundreds of existing values, the auto-complete selection filtering allows the user to quickly narrow down existing values which contain the provided string. If a value isn't found or the user simply wants to use their own value, they can then enter that text.

### "Must have" functionality
* Ability to enter text and have it show a list of existing values which contain that text.
* Ability to enter a value which is new and not in the existing list.
* (nice to have) flag to support the initial click displaying a list of values

### Specific timeline issues / requests
1Q/2019. Yes -- related to release.

### Available extra resources
Contact me -- can put you in touch with development manager.

Many thanks!

**Comment by mrsideshowjack** [comment]
+1 especially as its not uncommon for a autocomplete dropdown to be present with search 

![](https://i.imgur.com/5KUo4o5.png)

**Comment by vpicone** [comment]
I definitely agree that there should be a well documented solution for this problem. 

However, for the sake of discussion, I want it to be clear that material-ui is removing support for this component in v1 

https://material-ui.com/demos/autocomplete/

The solutions documented in their current docs are appropriate for our circumstances as well.

**Comment by robbysamtech** [comment]
Hi,

We really need this for our product as we are moving to Carbon. Can this be given some attention (or) a time frame?

Thanks.

**Comment by asudoh** [comment]
@sampudhuvai For "migration to Carbon" case I'd suggest re-styling your existing component for now, but if you have got a dependency-free component with serving-general-purpose/solid API please be sure to contribute back to us. Thanks!
