### ISSUE TITLE
[Bug]: Crash in MultiSelect with undefined selectedItems

### ISSUE THREAD

**Issue by finken2** [carbon-design-system/carbon#16052]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.53.0

### React version

v18.2.0

### Description

This is admittedly user error, but it seems like it would be a good idea to protect against it. 
If `selectedItems` has an array with `undefined` in it, [this PR](https://github.com/carbon-design-system/carbon/pull/15633) will try to read `text` from undefined and crash with the stack below:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at @carbon_react.js?v=72b18db9:100065:90
    at Array.map (<anonymous>)
    at @carbon_react.js?v=72b18db9:100065:71
```

I hit it b/c we had some bad test code, but figured it would be a good idea to just add some optional chaining in that MultiSelect code so it doesn't crash. 

### Reproduction/example

https://stackblitz.com/edit/github-caiwsw?file=src%2FApp.jsx

### Steps to reproduce

Create a multiselect
in `selectedItems`, have an item that is undefined or null.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

IBM Cloud Satellite

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jesnajoseijk** [comment]
@finken2 Can I take this up?
