### ISSUE TITLE
Inline loading design fix

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#1607]
- [ ] Inline loading implemented design is not the same as spec. 

**Current implementation on next.carbon site**
![image](https://user-images.githubusercontent.com/15144993/50876706-19c5ed00-1394-11e9-802b-994d4dbb7a1f.png)

**Spec**
![image](https://user-images.githubusercontent.com/15144993/50876731-2e09ea00-1394-11e9-951d-27619898ca46.png)

- [ ] Design spec is missing finished states (both success and error)
Current implementation on next.carbon site
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/61c02554-225d-4c19-b687-2c61bbe0bba4)
Shixie propose: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/09bcef86-08c8-462d-a1d8-12582f0ea660)
Some explorations on this state: 
![image](https://user-images.githubusercontent.com/15144993/50876774-5691e400-1394-11e9-9c35-898d48b951a7.png)

- [ ] Guideline says inline loader replaces button. This feels weird to me based on below implementation. Button is too big / prominent and our inline loader type is only 12px G70.
![motion_inline-loading_v10](https://user-images.githubusercontent.com/15144993/50876805-77f2d000-1394-11e9-8d59-42c3968cf9fd.gif)

**Comment by laurenmrice** [comment]
I also like the check you propose @shixiedesign ^

**Comment by asudoh** [comment]
Refs IBM/carbon-components#1749

**Comment by asudoh** [comment]
CC @dakahn

**Comment by shixiedesign** [comment]
### Spec & Sketchfile 
https://ibm.box.com/s/quzwd4vj94mj6i8wjbxdjuxn1xt6wret
![image](https://user-images.githubusercontent.com/15144993/53369032-db6a9a00-390f-11e9-8482-d5aeaebba741.png)

**Comment by shixiedesign** [comment]
Closing because fixes mentioned in this issue are now consolidated in issue https://github.com/IBM/carbon-components/issues/1906
