### ISSUE TITLE
Video intro to using Carbon Sketch components

### ISSUE THREAD

**Issue by antonmc** [carbon-design-system/carbon#161]
I'm quite new to Sketch - and I was able to make a few views in a day, so it wasn't bad, but I'm not sure I'm using it correctly. This may not be for everyone - but a 20 minute, no nonsense screencast overview of creating an app view with the Carbon template would be great.

For instance - I just copy and paste with it - is there a more integrated way of using the components on an artboard?

What's a typical flow? No more than 20 minutes - no personal intro, no system background - just looking over the shoulder of a designer making something with the sketch components.

**Comment by hellobrian** [comment]
This is really good to hear. We've had other ideas for videos that were more dev focused but having intro content like this for designers using sketch sounds good too.

**Comment by joshblack** [comment]
Can definitely help out with this if needed 😄  I've done a lot of screencasts over for Egghead.io ([example](https://egghead.io/courses/build-a-graphql-server))

**Comment by tay-aitken** [comment]
Issue moved to [carbon-design-system/carbon-design-kit #15](https://github.com/carbon-design-system/carbon-design-kit/issues/15) via [**ZenHub**](https://www.zenhub.com/)
