### ISSUE TITLE
<AVT> While hovering on ghost button, the background contrast changes making the text not clear.

### ISSUE THREAD

**Issue by ManikaGupta23** [carbon-design-system/carbon#16109]
### Package

carbon-components

### Browser

Chrome

### Operating System

MacOS

### Package version

V11

### Automated testing tool and ruleset

Manual

### Description

While hovering on ghost button, the background contrast changes making the text not clear.
<img width="1720" alt="Screenshot 2024-04-02 at 10 23 44 AM" src="https://github.com/carbon-design-system/carbon/assets/165246567/edf5ec10-c212-4ae9-830a-2e3a744d380c">
<img width="866" alt="Screenshot 2024-04-02 at 10 23 58 AM" src="https://github.com/carbon-design-system/carbon/assets/165246567/952e0d13-78b2-41e2-a1b0-1fe7f8a593eb">

### Reproduction/example

carbon-components

### Steps to reproduce

Test Tool Type: Manual

=====STEPS TO REPRODUCE =====

1. Go to [https://staging.apps.giriskcockpit2.cp.fyre.ibm.com/asset-inventory/rulebuilder/policy_1]
2. Hover on the 'add a tagging rule' button or the 'add a tagging override rule' button.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @ManikaGupta23 
The reproduction example is not opening. Can you reproduce it on [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), please?

**Comment by laurenmrice** [comment]
@ManikaGupta23 The background color change on hover and the color of the button label does pass color contrast and is working as expected.
