### ISSUE TITLE
[Bug]: FilterableMultiSelect titleText does not render title in release 1.53.x

### ISSUE THREAD

**Issue by v2rinku** [carbon-design-system/carbon#16108]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.53.0

### React version

v18.2.0

### Description

On creating a FilterableMultiSelect with titleText provide, titleText in not displayed

### Reproduction/example

-

### Steps to reproduce

1. Create a component:
<FilterableMultiSelect  label="somelabel" id="someid" name="somename"    titleText="this is title"  />
2. titleText in not displayed.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @v2rinku 
Can you try to upgrade to v1.54.0. The `titleText` it's been displayed correctly here: https://react.carbondesignsystem.com/?path=/story/components-multiselect--filterable

**Comment by tay1orjones** [comment]
We did notice that the titleText isn't in proptypes - we'll add it in https://github.com/carbon-design-system/carbon/pull/16147
