### ISSUE TITLE
Tile: Expandable height doesn't account for dynamic content below the fold

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#1610]
## Detailed description

> Describe in detail the issue you're having.

The computed inline height of the Expandable Tile component does not account for dynamic content.

> Is this issue related to a specific component?

`<ExpandableTile>`

> What did you expect to happen? What happened instead? What would you like to see changed?

When the user clicks to expand the tile, maybe use maxHeight: none. When the user clicks to close the tile, revert to the computed height.

> What browser are you working in?

Chrome 70.0.3538.77

> What version of the Carbon Design System are you using?

Latest

Codesandbox
https://codesandbox.io/s/8ll6k38989

These may be helpful:
https://github.com/IBM/carbon-components-react/pull/679
https://github.com/IBM/carbon-components/pull/635

## Additional information
<img width="996" alt="screen shot 2019-01-09 at 11 10 08 am" src="https://user-images.githubusercontent.com/7707326/50912112-5844c180-13ff-11e9-8fca-8902ab47dbac.png">

**Comment by asudoh** [comment]
Hi @rob-richards thank you for filing this issue! Seems that this issue is about our React variant ([`carbon-components-react`](https://github.com/IBM/carbon-components-react)), is it correct?

**Comment by rob-richards** [comment]
My apologies! Yes, this was intended for the react variant. I opened a new issue here: https://github.com/IBM/carbon-components-react/issues/1736
