### ISSUE TITLE
MultiSelect (select all option): dev implementation

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#16117]
## Acceptance criteria
- [x] Add the Select all option enhancement to the Multiselect component. 

### Design spec

![Image](https://github.com/carbon-design-system/carbon/assets/158569631/bd2617e7-debd-40cb-8ec2-820a8445c7e8)

**Comment by andreancardona** [comment]
@Gururajj77 @preetibansalui Feel free to work with design to iron out any details / questions on this. :)

**Comment by preetibansalui** [comment]
As discussed with @benjamin-kurien , We are providing a prop to user if they want 'All' option in Multiselect or not.

**Comment by Creakyinertia** [comment]
Has feature been added?

**Comment by laurenmrice** [comment]
@Creakyinertia No, there is currently an [open PR](https://github.com/carbon-design-system/carbon/pull/16236) for this feature that is still in review.

**Comment by silverclaru** [comment]
Hi. I assume it's not possible to extent the current work to include the `FilterableMultiSelect` component? We need the ability for users to filter the list of options and then select everything the filter applies to with a single click.
