### ISSUE TITLE
[Bug]: Multiselect is no longer programmatically controllable

### ISSUE THREAD

**Issue by ychavoya** [carbon-design-system/carbon#16124]
### Package

@carbon/react

### Package version

v1.53.1

### React version

v18.2.0

### Description

The MultiSelect component is no longer controllable programmatically, meaning that its selected items can no longer be controlled by outside state.

See working version in @carbon/react v1.52.0

https://stackblitz.com/edit/github-vdfyj4?file=src%2FApp.jsx

Versus v1.53.1

https://stackblitz.com/edit/github-vdfyj4-yeae6d?file=src%2FApp.jsx

### Reproduction/example

https://stackblitz.com/edit/github-vdfyj4-yeae6d?file=src%2FApp.jsx

### Steps to reproduce

1. Add a Multiselect that gets its state from `selectedItems`
2. Modify the value of the prop passed to the `selectedItems`

Using the reproduction example I provided:
1. Click the "Clear" button
2. Check that in v1.53.1 it does not clear the Multiselect while in v1.52 it does

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ychavoya** [comment]
Hello, I have been experimenting to find a fix for this bug and I have found one, it's due to a missing `useEffect` now that controlled items are managed from an initial value in `useState`. I would like to provide a PR if you deem this issue as valid. Thanks!

**Comment by alisonjoseph** [comment]
@ychavoya Hi, thanks for reporting this, would appreciate a PR/fix. thanks!
