### ISSUE TITLE
[Bug]: Datepicker in range mode fires onChange handler when clicking outside, leading to unexpected dates

### ISSUE THREAD

**Issue by fdrcslv** [carbon-design-system/carbon#16125]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.53.1

### Description

When clicking outside a DatePickerInput (after having already set a date previously) the on Change handler fires with unexpected dates in the payload of the handler.

The calendar cannot be closed if the focus is on the second input

### Reproduction/example

The behaviour is present on the online storybook

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar-with-layer

### Steps to reproduce

1) set two dates with the datepicker.

2) click again on one of the inputs to open the calendar

3) click outside or click on another form element or tab away, the onChange will be fired and the date (or both) will change.

If the calendar is open with the click on the second input, it can never be closed clicking outside, and the date will keep change untl it settles to some date in the year 2001

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Here in this issue: https://github.com/carbon-design-system/carbon/issues/16144 has a video from the bug using a keyboard

**Comment by AdrianApan** [comment]
👋 Hey, experiencing the same issue, some more context in case it helps:

**Minimal usage example**
```tsx
<DatePicker
   dateFormat="d/m/Y"
   datePickerType="range"
   onChange={handleChange}
   value={formattedDate}
>
   <DatePickerInput
      id="start-date"
      labelText="Start date"
      placeholder="dd/mm/yyy"
      type="text"
      size="md"
   />
   <DatePickerInput
      id="end-date"
      labelText="End date"
      placeholder="dd/mm/yyy"
      type="text"
      size="md"
   />
</DatePicker>
```

As described above, clicking outside the date picker input, it will reset the value.

https://github.com/carbon-design-system/carbon/assets/69169115/c949c043-6ae8-4505-8218-c4c56354dc86

ℹ️ Only workaround I could find for now is to set the `allowInput` prop on `DatePicker` to `false`:

```jsx
<DatePicker allowInput={false} />
```
