### ISSUE TITLE
[Feature Request]: Inline menu capability integration with datagrid

### ISSUE THREAD

**Issue by aryananand5** [carbon-design-system/carbon#16138]
### The problem

While working on one of the use cases involved with '**_Integration data sources for IBM Qradar suite_**', we were required to have a capability where the user was supposed to select a few option against certain values presented in a datagrid format. 

Currently the **[Datagrid](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--basic-usage&globals=carbonTheme:g100)** component that we have in Carbon for IBM Products doest support the feature of having inline menus which allows selection from a predefined set of menu items.

### The solution

_I propose the feature of having selectable inline menus which allows selection from a predefined set of menu items to be embedded directly in the table. 
Inline menu could be_
**Single select/multi-select as per the default behavior of the dropdown having all the functionality.**
**We can have the following categories for the datagrid:**
- Without the inline menu
- Single column
- Double/ multiple column

**This will provide more control over the datagrid and the respective boxes.**
<img width="915" alt="Screenshot 2024-04-06 at 12 28 33 AM" src="https://github.com/carbon-design-system/carbon/assets/166104673/2c8c7bf1-cc43-4b5e-bbae-85ad97992a12">

_Positioning of the menu is just for reference, we as team can give it a thought to re-position it._

### Examples

Referring to the Material design website, they have similar inline menu capability with available with the datagrid
https://m2.material.io/components/data-tables#behavior
<img width="761" alt="Screenshot 2024-04-05 at 12 55 35 PM" src="https://github.com/carbon-design-system/carbon/assets/166104673/f3cee728-0f1d-43c7-9247-68510784dcd4">

### Application/PAL

IBM Qradar Suite

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by ljcarot** [comment]
Apologies, but we are not taking on new Feature Requests for DataGrid at this time due to prioritization with other issues.
