### ISSUE TITLE
[Bug]: Slider component does not handle "0" value correctly when the slider has a negative minimum value

### ISSUE THREAD

**Issue by rwibm** [carbon-design-system/carbon#16141]
### Package

@carbon/react

### Package version

1.54.0

### Description

When the slider component has negative values it is impossible to slide it to 0 as a 0 value causes the slider to be on the very left hand side i.e. the lowest negative value.

In the storybook example given the slider should be in the middle, but it goes to the very left hand side whenever the value is 0, regardless of the min/max values set.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-slider--playground&args=min:-100;value:0

### Steps to reproduce

The storybook link above is enough to reproduce, I have also found the cause of the issue so a fix should be easy/quick for the carbon team to implement.

The following file (inside the calcLeftPercent function):
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Slider/Slider.tsx#L1039

```
else if (value && range) {
  // Prevent NaN calculation if the range is 0.
  return range === 0 ? 0 : (value - this.props.min) / range;
}
```

The above code snippet shows the problem code, it uses a boolean check `value &&` to check for undefined/null, this will cause the value `0` to show as undefined, causing the slider to be on the left hand side, instead of the middle as it should be when the range is -100 to 100.

```
else if (((value ?? null) != null) && range) {
  // Prevent NaN calculation if the range is 0.
  return range === 0 ? 0 : (value - this.props.min) / range;
}
```

I have coped the code into a local component and changed the check to the one above i.e. coercing undefined/null to null with ?? then checking if it's null, rather than using a boolean check (this could also just check if its null/undefined directly, but that's a little messier). This causes the slider to work as expected when using negative values.

There are other parts of this file where `value &&` is used to check the value which probably need reviewing too as they will all fail when the value is 0, which is a valid value and should be treated as such.

![image](https://github.com/carbon-design-system/carbon/assets/85178678/e8f68b17-8133-45a2-9d26-996daa4e8e52)

The screenshot above shows my updated component on top with the correct behaviour, and the original broken carbon component underneath.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM Internal

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aninaantony** [comment]
Hello team, Can I work on this?

**Comment by guidari** [comment]
Hey @aninaantony sure!!
