### ISSUE TITLE
[Bug]: Closing ActionableNotification with closeOnEscape throws an error when typing

### ISSUE THREAD

**Issue by FFahrenheit** [carbon-design-system/carbon#16153]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.47.0

### React version

v18.2.0

### Description

Closing an `ActionableNotification` with `closeOnEscape` property with scape button closes the notification, but then every keystroke  an  error is thrown, and in dev environment crashes the app

Dev environment:
<img width="1493" alt="image" src="https://github.com/carbon-design-system/carbon/assets/21372626/d13cf11a-11bc-463a-96c0-553ed696ca3b">

Stackblitz:
<img width="1512" alt="image" src="https://github.com/carbon-design-system/carbon/assets/21372626/51776abb-533c-4929-92da-fc5b9399c817">

Deployed application:
<img width="352" alt="image" src="https://github.com/carbon-design-system/carbon/assets/21372626/798a16d8-2e85-4d16-9f9e-ff3848a31bd6">

### Reproduction/example

https://stackblitz.com/edit/github-3sw6vk?file=src%2FApp.jsx

### Steps to reproduce

1. Add an ActionableNotification with closeOnEscape property
2. Make sure the Notification is focused, so you can close the notification with the scape key (I reload in case I focus another component)
3. Press esc key to close the notification
4. Press any key and check the error logs

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
My guess here is that the keydown event listener calling handleKeyDown isn't being cleaned up properly for some reason. 

We can't just add more guards here
https://github.com/carbon-design-system/carbon/blob/2e4d9fac95fd4d421042ce669004325c8b36c2a0/packages/react/src/components/Notification/Notification.tsx#L57

Whoever works on this needs to identify why handleKeyDown is being called, determine if it _should_ be being called, and if not, how to prevent it from being called.
