### ISSUE TITLE
[Bug]: `OverflowMenuItem` hidden behind `HeaderMenu` and `SideNav`

### ISSUE THREAD

**Issue by btepe** [carbon-design-system/carbon#16178]
### Package

@carbon/react

### Package version

1.55.0

### Description

When including an `OverflowMenu` in a `SideNav` or a `HeaderPanel`, the expanded menu items are underneath the nav panel due to a lower `z-index`.

The `z-index` of the sidebars is `8000`, while the one of the overflow menu is `6000`. 

This is the same problem as recently mentioned and fixed in https://github.com/carbon-design-system/carbon/issues/15816 for the `Modal` component.

### Reproduction/example

https://stackblitz.com/edit/carbon-v11-gus87t?file=src%2FApp.jsx

### Steps to reproduce

1. Click on overflow menu
2. Inspect menu items = hidden
3. Replace HeaderPanel with SideNav element and repeat = same result

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
@btepe Can you try setting `data-floating-menu-container="cds--header-panel"` on `OverflowMenu`? This seems to resolve it, as it then places the `OverflowMenu` inside the `SidePanel`, rather than at the end of `document.body` and allows it to inherit the correct `z-index`

https://stackblitz.com/edit/carbon-v11-zpendg?file=src%2FApp.jsx

**Comment by btepe** [comment]
@tw15egan This works, thank you!
