### ISSUE TITLE
Lock heights of components

### ISSUE THREAD

**Issue by antonmc** [carbon-design-system/carbon#162]
Maybe it is because I'm new to sketch, but I found that the components stretched whenever I changed the height of the artboard they were on.

I learned that there is a checkbox to keep height fixed, and learned to click that when resizing the artboard. I wonder if that should be defaulted for the Carbon components.

**Comment by bsonefeld** [comment]
Interesting find, @antonmc ! Could you post a screenshot or a GIF example of what's happening when you resize your artboard? Almost sounds like a Sketch bug to me, but in order to troubleshoot I want to make sure I understand the problem correctly :)

**Comment by hellobrian** [comment]
This issue should be moved to carbon-design-kit
