### ISSUE TITLE
[Bug]: Individual component import isn't allowing reset/default configuration

### ISSUE THREAD

**Issue by somasri-git** [carbon-design-system/carbon#16209]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.27.0

### React version

Next version: 12.3.4 React:18.2.0

### Description

- while importing individual component, default and reset styles are not configurable. Giving SASS error. Application is using // @use '@carbon/react'; at global scope. Instead of using all carbon components, if individual components to be imported, carbon is not allowing default/reset style configuration i.e. the 'with' keyword given below. Error screenshot attached.
![image](https://github.com/carbon-design-system/carbon/assets/123064851/6a4f3c15-f44d-4c4f-aa68-2a103aefbec1)

### Reproduction/example

Use this in your sass file [eg. abcd.scss] @use '@carbon/react/scss/components/text-input' with (     $css--default-type: false,     $css--reset: false, ) ;  This is not working.

### Steps to reproduce

Use this in your sass file [eg. abcd.scss]
@use '@carbon/react/scss/components/text-input' with (
    $css--default-type: false,
    $css--reset: false,
) ;

This is not working.
![Screenshot 2024-04-16 200132](https://github.com/carbon-design-system/carbon/assets/123064851/35138579-53fe-49dd-bed9-9ff7b42345f7)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Macy's Knowledge Management 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@somasri-git Thanks for reporting this. Could you share more of the use case surrounding this? This is the first request we've seen asking to make the component-level reset configurable for individual components. Both `$css--default-type` `$css--reset` are meant to be configured at only a global level through `@carbon/react` or `@carbon/react/scss/config`
