### ISSUE TITLE
[CIOH] Create YourLearning event & agenda website

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16204]
This is a recurring task for every event. Tasks include

Pre Event
- [x] Updating your learning page with physical venue details 
- [x] Updating Agenda on the website

Post Event
- [x] Reseting Agenda on the website for next event
- [x] Adding Playback to website and your learning page
- [x] Split playback to chapters - for future convinience
- [x] Add links shared to website

### Event dates
| S. No. | Event date | 
| ------ | ----------- | 
| 1.         | 30/04/24    | 
|2.         | 15/05/24     |

### Important links
- [Your Learning page](https://ec.yourlearning.ibm.com/w3/meeting/10430986)
- [Agenda (website)](https://w3.ibm.com/w3publisher/carbon-india)

**Comment by benjamin-kurien** [comment]
Your Learning Page: https://ec.yourlearning.ibm.com/w3/meeting/10430986

**Comment by 2nikhiltom** [comment]
Hey @benjamin-kurien :  [Yourlearning's](https://ec.yourlearning.ibm.com/w3/meeting/10430986) content is amazing ! Thanks for your meticulous documentation  🚀

**Comment by riddhybansal** [comment]
Hey Amazing work Benji !!🥳🥳🥳

Just a small thing, Can correct the spelling of my name :(

**Comment by Kritvi-bhatia17** [comment]
Nice work Benjamin! 🎉
Just a few points:

  1.  Adding Preeti as a speaker
  2.  Should we be adding “Call-in info” too, the Webex link or maybe later? 🤔

[Screens screenshot of a computer  Description automatically generated]

  1.  The event description is kinda getting repeated..
  2.  Not sure about the “Not recommended” thing

[A white text with black text  Description automatically generated]



We can send in the carbon system squad channel to get their opinion as well!
From: Benjamin Kurien ***@***.***>
Date: Monday, 15 April 2024 at 7:39 PM
To: carbon-design-system/carbon ***@***.***>
Cc: Kritvi ***@***.***>, Assign ***@***.***>
Subject: Re: [carbon-design-system/carbon] [Enhancing Awareness] Carbon India - Office hours (Issue #16204)

Your Learning Page: https://ec.yourlearning.ibm.com/w3/meeting/10430986

**Comment by Kritvi-bhatia17** [comment]
Nice work Benjamin! 🎉
**Just a few points:**
 
1.  Adding Preeti as a speaker

2.  Should we be adding “Call-in info” too, the Webex link or maybe later? 🤔

> <img width="1449" alt="Screenshot 2024-04-16 at 12 09 23 AM" src="https://github.com/carbon-design-system/carbon/assets/158570656/44a14493-0059-4cb2-baa0-87b49f938c39">

3. The event description is kinda getting repeated...

4. Not sure about the “Not recommended” thing
> <img width="594" alt="image002" src="https://github.com/carbon-design-system/carbon/assets/158570656/df0e6d98-6431-4857-9e2b-962d6b3874c6">
