### ISSUE TITLE
Revise Renovate and Dependabot configuration

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#16214]
Lately we've been getting duplicate PRs for upgrading dependencies. Anecdotally it appears to me that dependabot opens PRs that fix CVE's immediately, whereas Renovate opens those later. For regular non-CVE-related dependency updates Renovate often opens the first PR and dependabot opens one later.

We need to revise the configs of these two tools to

1. Stop the duplication
1. Prefer Renovate as much as possible
1. Keep dependabot around for anything Renovate doesn't handle as well (this will require some comparative research between the two tools)

Related reading:
* https://www.jvt.me/posts/2024/04/12/use-renovate/
* [Internal slack convo](https://ibm-studios.slack.com/archives/GCQ5R263T/p1712944933349319)

**Comment by guidari** [comment]
@tay1orjones 

We can ignore certain dependencies in Dependabot or Renovate:
* [Dependabot Ignore Options](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)
* [Renovate Ignore Options](https://docs.renovatebot.com/configuration-options/#ignoredeps) 

Renovate's [bot comparison guide](https://docs.renovatebot.com/bot-comparison/) has a good example that highlights the differences between Renovate and Dependabot.

We can configure Dependabot to run once a week and schedule Renovate to run on "every weekday". This way, Dependabot will run updates in case Renovate misses something. However, there is no way to avoid duplication if we keep all settings open for both bots. Ignoring dependencies might be an option, but it would require manual work to determine which dependencies we should ignore in each bot.

From my research and readings, the ideal approach to avoid duplication would be to discontinue using Dependabot. Renovate seems to offer more features and customization, and it is more widely adopted by developers. I guess Dotcom is only using Renovate. Might be worth to ask them their thoughts after disabling Dependabot. 
_______________________
What I think would be the best approach after this research? 
Keep both bots running and only change the time it runs. Then we analyze what it’s being ran in Dependabot to make a decision in keeping or removing (probably removing).

That would be the change:

![Screenshot 2024-06-11 at 12 27 41](https://github.com/carbon-design-system/carbon/assets/52183462/0468543d-a314-4c7c-b6db-49720569d334)
