### ISSUE TITLE
[Bug]: DatePicker type is range and inline is true cannot update month correctly

### ISSUE THREAD

**Issue by oyv1cent** [carbon-design-system/carbon#16216]
### Package

@carbon/react, @carbon/styles

### Browser

Chrome

### Package version

v1.55.0

### React version

v18.2.0

### Description

DatePicker type is range and inline is true cannot update month correctly.

I debugged the source code and found that this [updateCurrentMonth](https://github.com/carbon-design-system/carbon/blob/6236d6e6fa7c5c895dd6c757cdd27ca77539397e/packages/react/src/components/DatePicker/DatePicker.tsx#L98) function only triggers when the startDateInput on blur (will trigger [on ValueUpdate hook](https://github.com/carbon-design-system/carbon/blob/6236d6e6fa7c5c895dd6c757cdd27ca77539397e/packages/react/src/components/DatePicker/DatePicker.tsx#L125)), not when the endDateInput on blur. Regardless of whether startDateInput or endDateInput is focused, this [updateCurrentMonth](https://github.com/carbon-design-system/carbon/blob/6236d6e6fa7c5c895dd6c757cdd27ca77539397e/packages/react/src/components/DatePicker/DatePicker.tsx#L98) function  won't execute. Consequently, the behavior persists where only the month of the startDate is displayed.

I think that when inline is set to true, the updateCurrentMonth function should be triggered when either the start or end date input is focused.

### Reproduction/example

https://codesandbox.io/p/devbox/nostalgic-firefly-gzf43w?file=%2Fsrc%2FApp.jsx%3A21%2C11

### Steps to reproduce

1. Select a start date and end date from different months.
2. Click outside the calendar.
3. Click on the start date; the calendar should display the month of the start date.
4. Then, click on the end date; however, the calendar continues to display the month of the start date instead of switching to the month of the end date.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
[When `inline` was added](https://github.com/carbon-design-system/carbon/pull/9702) it's only purpose was as a passthrough prop to flatpickr. There are no design specs for it and it wasn't really meant to be a fully supported functionality of the component.

The storybook documentation doesn't really reflect this though. It needs updated:

- Remove it as a control from the controls pane
- Leave it in the prop tables though
- Update the comments on the prop and type to reflect that this feature is just a passthrough and doesn't have full support

---

Solving both this initial issue you pointed out, as well as the documentation items are great candidates for the community to fix/implement.

**Comment by oyv1cent** [comment]
> [When `inline` was added](https://github.com/carbon-design-system/carbon/pull/9702) it's only purpose was as a passthrough prop to flatpickr. There are no design specs for it and it wasn't really meant to be a fully supported functionality of the component.
> 
> The storybook documentation doesn't really reflect this though. It needs updated:
> 
> * Remove it as a control from the controls pane
> * Leave it in the prop tables though
> * Update the comments on the prop and type to reflect that this feature is just a passthrough and doesn't have full support
> 
> Solving both this initial issue you pointed out, as well as the documentation items are great candidates for the community to fix/implement.

Thanks for your answer!
