### ISSUE TITLE
Remove helvetica mixin usage in X

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1624]
In `_css--font-face.scss` we currently use the `helvetica-font-face` mixin:

```scss
@include exports('css--font-face') {
  @if not global-variable-exists('css--font-face') or $css--font-face == true {
    @if global-variable-exists('css--plex') and $css--plex == true {
      @include plex-font-face;
    } @else {
      @include helvetica-font-face;
    }
  }
}
```

We should put this behind the `breaking-changes-x` flag.

**Comment by asudoh** [comment]
@joshblack No - We are _not_ using `helvetica-font-face` by default. If we want to drift away from `helvetica-font-face` we first deprecate this and then remove.

**Comment by joshblack** [comment]
@asudoh I don't think I suggested that it was used by default, just that it is in use when `$css--font-face` is true and `$css--plex` is false.

With respect to removal, I believe we're not licensed to use the Helvetica Neue typeface anymore. Will ping @kuehndaniel to confirm 👍

**Comment by asudoh** [comment]
Good thank you for clarifying @joshblack, sounds that it’s better worded making Plex switch always effective for `v10`.
