### ISSUE TITLE
[Bug]: Unable to disable TimePickerSelect within TimePicker

### ISSUE THREAD

**Issue by houhoucoop** [carbon-design-system/carbon#16246]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.56.0-rc.1

### React version

v18.2.0

### Description

There seems to be an issue with disabling the `TimePickerSelect` when it's nested within the `TimePicker`. 
it does work fine when we use `TimePickerSelect` on its own.

### Reproduction/example

https://stackblitz.com/edit/github-glse7v?file=src%2FApp.jsx

### Steps to reproduce

1. Put a `TimePickerSelect` inside the `TimePicker`
2. Add props `disabled` to the `TimePickerSelect`
3. The `TimePickerSelect` stays clickable

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
Thanks for highlighting this concern. The problem lies within the Parent component, where the disabled prop of the `TimePicker` overrides the disabled prop of the Child component, `TimePickerSelect`, despite our explicit assignment. Your attention to this is much appreciated!
