### ISSUE TITLE
[Filterable Multi-Select] Inconsistency in Accessing Default and Fluid Options

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16257]
### The problem

Inconsistency in accessing the [default](https://arc.net/l/quote/vqrwreth) and [fluid](https://react.carbondesignsystem.com/?path=/story/experimental-fluid-components-unstable-fluidmultiselect--playground) filterable multi-select options

![image](https://github.com/carbon-design-system/carbon/assets/158570656/64060d15-ed3e-4b61-b43a-adac0621a926)

### The solution

Adding consistent example stories/ sub section to the Fluid version in storybook similar to the Default one.

**Comment by tw15egan** [comment]
@Kritvi-bhatia17 I'll make this fix alongside the changes in #16252

**Comment by Kritvi-bhatia17** [comment]
Thank you @tw15egan!! 🙌🏻
