### ISSUE TITLE
Project clean-up and refactor for X

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1625]
## Changes

- [ ] Add `.npmignore` for files
  - dotfiles should be ignored
  - fractal files should be ignored
- [ ] `globals`
  - [ ] Remove `globals/assets`
    - Seems like an outdated/unused folder
  - [ ] Remove `globals/data`
    - Seems outdated/unused
  - [ ] Remove `globals/fonts`
    - We should not be hosting fonts
  - [ ] Remove `globals/grid`
    - Grid now lives in elements
- [ ] Top-level, published folders
  - [ ] Remove `scripts` output
    - Seems like the CommonJS version of `carbon-components`? Doesn't seem used in package
  - [ ] ~~Remove `html` output~~
    - ~~I think we're moving away from shipping `html` as it doesn't provide value to consumers~~

## Questions

- Do we want to ditch the `globals` folder? After the changes above, we have `scss` and `js` left. We could move `globals/scss` to the top-level and have `js` just live at the `src` level, potentially?
  - Benefit would be shorter paths when using scss files
  - Drawback would be that consumers would need to update import paths

**Comment by alisonjoseph** [comment]
We're still using the `html` on the website right now for the component pages. We can definitley move away from this in the future, but not sure if we have time to come up with something before the launch. Unless anyone has ideas?

**Comment by joshblack** [comment]
Updated @alisonjoseph!

In the future, if we use React for rendering could we do `ReactDOM.renderToString` on the component?

**Comment by alisonjoseph** [comment]
For sure!

**Comment by alisonjoseph** [comment]
In regards to removing globals, my only worry is it being annoying for people to upgrade and have to change paths. It shouldn't be a big deal, but it is one more thing they have to do.

**Comment by alisonjoseph** [comment]
In regards to removing globals, my only worry is it being annoying for people to upgrade and have to change paths. It shouldn't be a big deal, but it is one more thing they have to do.

**Comment by asudoh** [comment]
Thanks @alisonjoseph for jumping in, makes sense for both. Re `scripts`, JavaScript bundles are in there: https://unpkg.com/carbon-components@9.66.3/scripts/

**Comment by joshblack** [comment]
@asudoh should we update our `main` in `package.json` to point to them then? Or change the folder for the bundle type?

**Comment by asudoh** [comment]
`main` points to `umd`, which is more natural fit for the purpose than the bundled one (`scripts`).

**Comment by joshblack** [comment]
Right, I understand. Which bundle type are we supporting with `scripts`?

**Comment by asudoh** [comment]
It's IIFE.

**Comment by joshblack** [comment]
Okay, seems like we could remove it then since we have UMD?

**Comment by asudoh** [comment]
They are different animals - Contents in `umd` is _not_ bundled, contents in `scripts` is bundled.

**Comment by joshblack** [comment]
Gotcha, should we have UMD be the bundled one and the CJS one be not bundled? Or move towards all output being bundled anyways to help out with tree-shaking and other optimizations?

**Comment by asudoh** [comment]
`umd` directory is a counterpart of `es` for where ESM is not supported. `carbon-components` does _not_ have CJS build output (as UMD covers CJS).

**Comment by joshblack** [comment]
So you don't want to do a rollup build for each of our bundle targets? If not, why?

**Comment by asudoh** [comment]
We don't bundle `umd`/`es` to support imports of specific path.

**Comment by joshblack** [comment]
Cool! What paths are we exposing for folks to import specifically?

**Comment by asudoh** [comment]
It's not about specific paths. Consumers can choose what specific ESM/UMD file to import. Some examples I'm aware of are Carbon vanilla base class, a utility library for event handling, dropdown component, and more.

**Comment by joshblack** [comment]
Sounds good 👍 Could an alternative be named exports on the entrypoint bundle? For es/cjs/umd etc. Like in:

```js
import { dropdown, createComponent } from 'carbon-components';
```

**Comment by asudoh** [comment]
We support your syntax with `es` directory. `import dropdown from 'carbon-components/es/components/dropdown/dropdown` are also in use, and we still need to support it until we have full-blown tree-shaking support (Flatpickr is one of the blockers). `umd` serves the same purpose for `lib` directory in `carbon-components-react`.
