### ISSUE TITLE
[Bug]: Server-side rendering broken on Menu and OverflowMenu 

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#16251]
### Package

@carbon/react

### Package version

v1.55.0

### React version

18.02

### Description

Reported on [Slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1713886926867289)

When using NextJS with `Menu` and `OverflowMenu` with server-side rendering the following error shows up: 
_**Internal error: ReferenceError: document is not defined**_

This might be solved by using this helper:

https://github.com/carbon-design-system/carbon/blob/71c553cb9d162d3bfc32885f5d0234d048322b3c/packages/react/src/internal/useEvent.js#L68-L94

### Reproduction/example

https://stackblitz.com/edit/stackblitz-starters-vavqe5?file=app%2Fpage.tsx

### Steps to reproduce

Open Stackblitz example and check the console log

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by janhassel** [comment]
Related: #15531

**Comment by DoaaRadwan** [comment]
Any updates on this? a similar issue was reported to the @carbon/ibm-products team and was fixed here https://github.com/carbon-design-system/ibm-products/issues/4966 if this could be of any help .
