### ISSUE TITLE
[Status Indicator] General discussion around it

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16253]
### The problem

1. [New status indicator icons are available in the Figma kit](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=49975-12573&mode=design&t=vvqNhZaMwYgDirYs-4), but they are not present in our documentation or code.

2. The padding differs between [the two icons](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/eEftar142RW69BRQO9g5wM/(v11)-All-themes---Carbon-Design-System?type=design&node-id=61472-2720&mode=design&t=rAKUfaaQcxCDxlCr-11). Why wasn't the size reduced instead of altering the design?

![image](https://github.com/carbon-design-system/carbon/assets/158570656/0913c744-c737-45ef-ab97-c3a48443e4ea)

---

### To be discussed

1. **Existence in Code:** These don't exist in code (beyond the icons that should all be in our icons package). Carbon for IBM Products has a component, its definitely come up before about either creating or moving to core.

2. **Guidance for Icons (for dev):** The status indicators were contributed to Figma, and users can use the guidance to configure the icons themselves in code. 

3. **Icon Design and Sizing:** The shape indicator pulls icons from the icon library without altering the size or design. It might be worth revisiting some of the icon designs to standardize the sizing and SVG naming convention.

---

Ref: 
- [Discussion thread](https://ibm-studios.slack.com/archives/GSCEH4RSP/p1713896129137459)
- [Figma kit](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=49956-1564&mode=design&t=BsvVIk1kRIXHwRqa-4)

**Comment by Kritvi-bhatia17** [comment]
Hey @Shobhith-Sridhar! Following our last discussion, I've talked with the team and we've had several conversations since then. Just wanted to keep you in the loop and you can keep an eye on this issue for further updates.

**Comment by Shobhith-sridhar** [comment]
@Kritvi-bhatia17 Can you please tag me in this issue?

**Comment by Shobhith-sridhar** [comment]
I have a few more questions @Kritvi-bhatia17 : 
So these are some status icons one of our dev teams is using in their deployment environment. We are currently changing these to comply with Carbon colors.

![image](https://github.com/carbon-design-system/carbon/assets/168063928/3b8f5779-e49e-4499-ba84-12f5aca5ccd8)
![image](https://github.com/carbon-design-system/carbon/assets/168063928/a193873d-b940-4036-bed8-1a5eca4c6fc6)

**Comment by Shobhith-sridhar** [comment]
If these are available (2nd picture above), then I can use this icon (screenshot below) instead of the one currently in issue (incomplete)

![image](https://github.com/carbon-design-system/carbon/assets/168063928/7f721f5c-76ab-4a56-a140-d1055078f3c9)

Alternatively I could also use these two (bottom screenshot) to represent Paired and Unpaired, but I'm not sure if we can change the color from yellow to green? and if this icon is available for the devs to use right now.

![image](https://github.com/carbon-design-system/carbon/assets/168063928/c6fa35e9-f6fe-4c18-9a43-76f0198fc5cc)

**Comment by aubrey-oneal** [comment]
A few more resources:
- [Naming convention audit](https://airtable.com/app8E3u3LlUbMNVwt/tblvAZwRc3KdGHZqO/viwKP8PIBayWSwa5y?blocks=hide)
-[ Docs on how to use status indicators vs shapes](https://carbondesignsystem.com/patterns/status-indicator-pattern/)

**Comment by Kritvi-bhatia17** [comment]
Hey @Shobhith-sridhar, thanks for bringing this up. Developers can use status shapes and icons them via SVG for now. Here are the steps:

1. [Download the the SVG](https://carbondesignsystem.com/elements/icons/library/) you need if it isn't already in your code
2. [Add the color tokens documented here](https://carbondesignsystem.com/patterns/status-indicator-pattern/) and read the usage guidance as needed
3.  Reach out if you have any questions!

We have an item on our roadmap to code these up as full components and fix some confusion, but this is probably coming in Q3. As for understanding the disparity between status indicators and shapes, as mentioned by 
[@aubrey.oneal](https://ibm-studios.slack.com/team/WFS956D47), you can find more details [over here](https://arc.net/l/quote/krmadggl).

**Comment by Kritvi-bhatia17** [comment]
> 1. If these are available (2nd picture above), then I can use this icon (screenshot below) instead of the one currently in issue (incomplete)
> 
> 2. Alternatively I could also use these two (bottom screenshot) to represent Paired and Unpaired, but I'm not sure if we can change the color from yellow to green? and if this icon is available for the devs to use right now.



Hi @Shobhith-sridhar! In response to your questions:

1. I noticed that the gray-colored icon used here doesn't seem to align with the standard, as typically gray indicates [draft or disabled status](https://arc.net/l/quote/nosfrnbh).
         <img width="926" alt="image" src="https://github.com/carbon-design-system/carbon/assets/158570656/e21f73f0-a529-4891-a89b-42282d1bd3d6">


2. It's crucial to opt for colors that closely adhere to the recommended usage guidelines. Therefore, it's advisable to refrain from introducing new color and shape combinations not specified [here](https://carbondesignsystem.com/patterns/status-indicator-pattern/#shape-indicators).




Moreover, you can join our [office hours session](https://ibm.box.com/s/sr66djycn0u35a3yj34s3pse6wglya1q) if you'd like to discuss and review your designs with input from multiple designers!

**Comment by Shobhith-sridhar** [comment]
@aubrey-oneal @Kritvi-bhatia17 Thank you so much for your inputs. I'll talk to our devs to decide the best plan of action. 

Please keep me posted if any update is being made to this issue 💫

**Comment by alexandrutatarciuc** [comment]
@Kritvi-bhatia17 Thanks for the prompt reply! It makes sense why it is `black` or `white`. I hope there'll be a solution that would align better with the rest of CDS' design practices.
Thanks for considering my feedback!
