### ISSUE TITLE
Handle SCSS Deprecations for X

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1626]
- [x] `_colors.scss`
  - Deprecate and pull from colors
- [x] `_css--body.scss`
  - Use type and color tokens
- [x] `_css--font-face.scss`
  - Remove helvetica, use new plex from type
- [ ] `_css--helpers`
  - What is the difference between these and helper-classes?
- [x] `_css--plex-core.scss`
  - Use type package in X?
- [x] `_css--reset.scss`
  - Should this include resets from elements?
- [x] `_css--typography.scss`
  - ~~Replace with comparable values?~~ Remove?
- [x] `_feature-flags.scss`
- [x] `_functions.scss`
- [x] `_helper-classes.scss`
- [x] `_helper-mixins.scss`
- [x] `_import-once` replace with upstream? breaking change?
- [x] `_layer.scss`
- [x] `_layout.scss`
  - `$breakpoints` - #2044
  - `$padding`
  - `padding` function
  - `breakpoint` mixin
  - `max-breakpoints` mixin
  - `grid-container`
  - ~~`z-indexes` refactor?~~
  - ~~`z` refactor?~~
- [x] `_spacing.scss` - #2044
- [x] `_typography.scss`
  - `line-height`
  - `font-size-map` - #2044
  - `typescale-map` - #2044
  - `typescale`
  - `helvetica` - #2146
  - `font-family-*` variables - #2044
- [x] `_vars.scss`
  - `$carbon--ease-*` variables
  - `$bx--ease*` variables
  - `$transition--*` variables

**Comment by asudoh** [comment]
Complete - We'll reopen if we found anything remaining accidentally.
