### ISSUE TITLE
[Bug]: FileUploader - can't upload a file with a dash in the file type

### ISSUE THREAD

**Issue by Aviv-Yaari** [carbon-design-system/carbon#16263]
### Package

carbon-components-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

7.57.4

### React version

16.8.0

### Description

In FileUploader component

1. Set the prop "accept" to ".some-file" (or any other name with a dash).
2. Try to upload a file with this type. For example: "example.some-file".
The file will be marked as invalid. This happens because of the regex check [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/FileUploader/FileUploaderDropContainer.tsx#L135)

### Reproduction/example

https://codesandbox.io/p/sandbox/fileuploader-bug-92yrk7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvf12uey00063b6mv7e8qm7t%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvf12uey00023b6m2pzezm3l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvf12uey00033b6mw6kw1o07%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvf12uey00053b6m9mxpokh2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvf12uey00023b6m2pzezm3l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvf12uex00013b6mlp3glno9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvf153gp00023b6l0p1wo52v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvf12uey00023b6m2pzezm3l%2522%252C%2522activeTabId%2522%253A%2522clvf153gp00023b6l0p1wo52v%2522%257D%252C%2522clvf12uey00053b6m9mxpokh2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvf12uey00043b6m2oqqz6b4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvf12uey00053b6m9mxpokh2%2522%252C%2522activeTabId%2522%253A%2522clvf12uey00043b6m2oqqz6b4%2522%257D%252C%2522clvf12uey00033b6mw6kw1o07%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvf12uey00033b6mw6kw1o07%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

In FileUploader component

1. Set the prop "accept" to ".some-file" (or any other name with a dash).
2. Try to upload a file with this type. For example: "example.some-file".
The file will be marked as invalid. This happens because of the regex check [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/FileUploader/FileUploaderDropContainer.tsx#L135)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by preetibansalui** [comment]
Hey @Aviv-Yaari, can you please provide a valid file extension which has a dash in it?

**Comment by preetibansalui** [comment]
Hey @Aviv-Yaari, I checked the existing functionality in detail and found that you can pass your own value of 'pattern' as a prop for what type of ext you want it to accept. Please check the[ reference issue here](https://github.com/carbon-design-system/carbon/issues/9919).
