### ISSUE TITLE
[Bug]: DataTableSkeleton not matching all forms of DataTable

### ISSUE THREAD

**Issue by pekeler** [carbon-design-system/carbon#16270]
### Package

@carbon/react

### Browser

Chrome

### Package version

latest Carbon Svelte

### Description

A DataTable can be used without a title, but the Skeleton always assumes that a title is part of the layout. This is causing an unfortunate vertical shift for the viewer when transitioning from Skeleton to DataTable. Setting showToolbar to false is not a fine enough setting. 

### Screenshots

https://github.com/carbon-design-system/carbon/assets/42363/c8626253-1873-4943-b65d-06533916835c

### Steps to reproduce

Show skeleton while data is slowly loading, then switch to DataTable.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by pekeler** [comment]
If the DataTable was structured such that the skeleton just replaced the table's body, it would solve this problem but also enable use cases such as allowing the user to use the search or press a toolbar button while the data is loading (something we should allow users in a modern SPA).

**Comment by thyhmdo** [comment]
Hi @pekeler 
So it's hard to predict what information is in the data table, so the skeleton would often not match the exact data in that data table. The skeleton state can't be aware of the data table format. However, you can customize the skeleton to match the data if you know what it'll be. 

We don't recommend this and it's not the purpose of the skeleton state.
