### ISSUE TITLE
[Feature Request/Question]: Enable to override button colour

### ISSUE THREAD

**Issue by walec51** [carbon-design-system/carbon#16275]
### The problem

I'm trying to override the primary buttons color somehow

but it does not seem to be possible 

```
@use "@carbon/styles/scss/config" with (
	// Use flexbox for grid - stick to CSS Grid or Flexbox
	// CSS Grid has become the default grid system in v11
	$use-flexbox-grid: true
);

@use '@carbon/styles/scss/themes';
@use '@carbon/styles/scss/theme' with (
  $fallback: themes.$white,
  $theme: (
    text-primary: #3b2314,
		focus: #8d563b,
		icon-interactive: #8d563b,
		interactive: #8d563b,
		background-brand: #8d563b,
		border-interactive: #8d563b,
		chat-avatar-user: #8d563b,
		chat-button: #8d563b,
		link-primary: #8d563b,
		button-primary: #8d563b
  )
);

@use "@carbon/styles";
```

I still get

<img width="341" alt="image" src="https://github.com/carbon-design-system/carbon/assets/738484/e104777b-39e8-468a-bf25-c8b28157e367">

### The solution

button-primary should work

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
Hi, the button tokens are component level tokens, docs can be found here on how to override. 
https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#component-tokens

```
@use '@carbon/react/scss/themes';
@use '@carbon/react/scss/components/button/tokens' with (
  $button-primary: #3f51b5
);

@use '@carbon/react';
```
