### ISSUE TITLE
[dropdown]: invalid html

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon#1627]
The dropdown component's down arrow is an svg element that is a child of the main ul element. I believe this violates the HTML spec as seen here: https://www.w3.org/TR/html52/grouping-content.html#the-ul-element

Valid work arounds include making the svg a child of the first li or using CSS to insert it similar to ul > li:first-child :after. Also possible would be moving the svg to be the first sibling to the ul so that ul + svg an position it properly.

**Comment by elizabethsjudd** [comment]
FYI, WH is working on this component now and we'll provide a `migrate-to-11.x.md` file for the changes we made.

**Comment by elizabethsjudd** [comment]
Dropdown still has this issue. But i noticed React has Dropdown V2. Are there plans to move this over to the vanilla implementation?

**Comment by asudoh** [comment]
@emyarod I think this issue is fixed in `v10`, is it correct? Thanks!

**Comment by emyarod** [comment]
yes @asudoh addressed in https://github.com/carbon-design-system/carbon-components/pull/1846 I believe

**Comment by asudoh** [comment]
Thanks @emyarod - Closing as resolved.
