### ISSUE TITLE
[Feature Request]: PasswordInput property doesn't exist in TextInput type

### ISSUE THREAD

**Issue by martinscooper** [carbon-design-system/carbon#16290]
### The problem

Using Carbon in a Typescript nextjs project, I am using the `PasswordInput` component and the `tsc` throws this error:

```
Type error: Property 'PasswordInput' does not exist on type 'ForwardRefExoticComponent<TextInputProps & RefAttributes<unknown>>'.
```

I am using the code from [here](https://react.carbondesignsystem.com/?path=/story/components-textinput--toggle-password-visibility):

```
<TextInput.PasswordInput id="text-input-1" labelText="Text input label" helperText="Optional help text" autoComplete="true" />
```

### The solution

The `PasswordInput` should be added to the `TextInput` types or made available separately. I would like to be able to perform the following import statement:

```
import { PasswordInput } from '@carbon/react'

```

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by martinscooper** [comment]
The console shows the following warning when using `PasswordInput` by accesing it through `TextInput`:

```
Warning: The PasswordInput field has been deprecated on the TextInput object. Please import and use PasswordInput directly.
```

But when I import it directly from `@carbon/react` the ts compiler shows the following error: 

```
Module '"@carbon/react"' has no exported member 'PasswordInput'
```

**Comment by guidari** [comment]
Hey @martinscooper 
Are you still experiencing the error? I just imported the component in `.tsx` file and it is working fine with no errors in the console or code.  
Can you open a StackBlitz if you are still having the issue, please?

![Screenshot 2024-06-07 at 09 31 12](https://github.com/carbon-design-system/carbon/assets/52183462/e5da8f2c-4f0f-433a-825a-100fc1d7a353)

**Comment by martinscooper** [comment]
@guidari Thanks for taking a look and sorry for my delayed response. We actually chose to not to use that component. The main reason of this was that we couldn't find a way to stop the browser from asking the user to remember the password.
