### ISSUE TITLE
[Bug]: <DatePicker> hosted inside of <Modal> or <ComposedModal> does not close calendar when clicking outside

### ISSUE THREAD

**Issue by liunate** [carbon-design-system/carbon#16337]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.56.0

### React version

v18

### Description

When a <DatePicker> is hosted inside of either <Modal> or <ComposedModal>, click on the <DateInput> and the calendar popover can not be dismissed by clicking outside of the calendar.

https://github.com/carbon-design-system/carbon/assets/38996291/6623e372-5dfe-441c-a2c4-028c886c1848

### Reproduction/example

https://stackblitz.com/edit/github-datbmn?file=src%2FApp.jsx

### Steps to reproduce

1. The example already has the modal opened by default. Click on the date input, and no matter where you click inside the `<ComposedModal>` and outside of the calendar, the calendar just does not close. It can only be closed by tab away or select the date.
1. Close the modal by clicking the close button.
2. There is another `<DatePicker` outside of `<ComposedModal>`. It has no problem closes its calendar popover by clicking elsewhere in the page.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by liunate** [comment]
I have looked into the `<ComposedModal>` source and the root cause is the `onMouseDown` event is stopped by the component:
https://github.com/carbon-design-system/carbon/blob/ad1362cd4603ef5a63886ad91af9b7471ad52093/packages/react/src/components/ComposedModal/ComposedModal.tsx#L292
```jsx
    function handleMousedown(evt: React.MouseEvent<HTMLDivElement>) {
      const target = evt.target as Node;
      evt.stopPropagation();
```

I believe the underlying `flatpickr` calendar library attaches the eventhandler to close calendar on click at higher element in the DOM hierarhcy, maybe `document` or `body`, and the `<ComposedModal>` component just stops the event from bubbling up.

I haven't found `flatpickr` API to specify the element to listen to the click event, but I can work around this issue by listening to `MouseDown` event when the event is triggered from element other than the `<DateInput>` or `<DatePicker>` elements, and call the `flatpickrInstance.close()` imperative API.

Something like this should work around the issue:

```jsx
// in the rendering body of the component rendering `<Modal>`

  function closeCalendarWhenClickingOutsideOfDateSection(e) {
    if (dateSectionRef.current.contains(e.target)) {
      return;
    }

    flatpickrInstanceRef.current.close();
  }

return (
    <div onMouseDown={closeCalendarWhenClickingOutsideOfDateSection} >
         <div ref={dateSectionRef}>
              <DatePicker onOpen={ (...args) => flatpickrInstanceRef.current = args[2] }>
                     <DateInput>
```

**Comment by 2nikhiltom** [comment]
fixed via https://github.com/carbon-design-system/carbon/pull/17154
