### ISSUE TITLE
[CIOH] Design stickers

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16352]
## Acceptance criteria

Designing stickers for the CIOH event to help spread awareness about the Carbon design system.

_These stickers can serve as versatile promotional materials for the Carbon design system, suitable for various purposes in the future._

---

**Tasks**
- [ ] Shipping (in progress)
- [ ] Create design iterations [Figma file](https://www.figma.com/file/lTGxQ76YgRjGUPDFrd2tjm/Stickers---Carbon?type=design&node-id=0-1&mode=design&t=addGQpR2Fqw4cHIJ-0) (in progress)
- [ ] Get a review

**Comment by laurenmrice** [comment]
Matt mentioned we could leverage the stickers he has already? Someone could sync with him on this.

**Comment by alina-jacob** [comment]
Update:
The shipping related follow-up is in progress, meanwhile we're also trying to create few more design options and have them locally printed post approvals.  

Once it all comes around, this would hopefully become a fun souvenir for the carbon community! 🧁

**Comment by Kritvi-bhatia17** [comment]
I have added a total of 4 story points to this task: 3 for @Kritvi-bhatia17 and 1 for @alina-jacob (post confirming with Alina).
