### ISSUE TITLE
Presentation of experimental pagination <Select> menu content is inconsistent

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#1638]
Based on the spec for the experimental pagination component, we are assuming that the `'items per page'` text should appear *only* on the trigger button rather than within the options of the listbox.

```
|     10 ITEMS PER PAGE      v  |
|-------------------------------|
|              10               |
|              20               |
|              30               |
|              40               |
|              50               |
|-------------------------------|
```

as opposed to the current implementation where text is appended to the selected menu item

![image](https://user-images.githubusercontent.com/8265238/51153866-5cc20d80-1837-11e9-8276-b441e26c9a62.png)

If this assumption is correct, then a number of technical issues arise, the primary one being that the native `<select>` element does not support this behavior of showing differing content between the trigger button and the list items contained within it.

There are a number of possible workarounds for this issue:

* one would be removing the appended text from the selected menu option
* another would be converting the native `<select>` element to a custom dropdown

This issue could potentially be a ship stopper for the v10 release as it appears to be a regression in functionality for the component consumer

**Comment by emyarod** [comment]
@laurenmrice would be great to have your input due to your involvement on these related tickets!

https://github.com/IBM/carbon-components/issues/1251

https://github.com/IBM/carbon-components/issues/1304

https://github.com/IBM/carbon-components/pull/1518

**Comment by laurenmrice** [comment]
![screen shot 2019-01-16 at 3 52 32 pm](https://user-images.githubusercontent.com/43969356/51281075-ffe56500-19a6-11e9-8731-08efba14f3d0.png)

Another way we could work around this is to rearrange where the numbers and arrows go. I would like to propose this design change to the pagination.^

@emyarod

**Comment by emyarod** [comment]
I think this proposal would be great to implement and avoids all of the problems mentioned initially. Thanks for the quick update @laurenmrice!

**Comment by laurenmrice** [comment]
![pagination_specs](https://user-images.githubusercontent.com/43969356/51282193-12ad6900-19aa-11e9-9377-01efed64bc97.png)

Here are also spacing specs for reference 👍
