### ISSUE TITLE
Export typescript props for TabProps

### ISSUE THREAD

**Issue by riddhybansal** [carbon-design-system/carbon#16380]
linking issue for #16154

**Comment by Gururajj77** [comment]
closed as this is completed previously.

**Comment by kenneth-nguyen1** [comment]
Hi @Gururajj77, where was this task completed?

I do not see `TabProps` (https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tabs/Tabs.tsx#L739) being imported and exported from [/components/Tabs/index.tsx](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tabs/index.tsx) nor [/components/Tab/index.tsx](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tab/index.tsx) on the carbon main branch and can't find an open or closed PR for this being completed.

**Comment by Gururajj77** [comment]
Thank you, @kenneth-nguyen1, for pointing that out! I appreciate your attention to detail. I'll make sure to export `TabProps` as well. Initially, I had excluded the component since `TabsProps` was already being exported. Your feedback is very helpful!

**Comment by kenneth-nguyen1** [comment]
Thank you, much appreciated!

**Comment by Gururajj77** [comment]
Hey @kenneth-nguyen1 , have added export for `TabProps` now, you can track the progress on this PR, #16448.

**Comment by Gururajj77** [comment]
closed with #16448
