### ISSUE TITLE
[Bug]: Menu component does not protect access to refs in focusItem

### ISSUE THREAD

**Issue by Kilian-Collender** [carbon-design-system/carbon#16395]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.49.0

### React version

v18.2.0

### Description

In the findIndex function here https://github.com/carbon-design-system/carbon/blob/e70f08d867fc276f7a77e2d703a0462afae545ab/packages/react/src/components/Menu/Menu.tsx#L237

It tries to use `contains` against the current ref value without checking that the ref value is not null. 

During our automations this is throwing the following error `Cannot read properties of null (reading 'contains')`  as `item.ref.current` is null .

This requires just a simple check to ensure that the value is not `null` before calling `contains`

### Reproduction/example

NA

### Steps to reproduce

Hard to reproduce consistently manually as it only really happens when the interaction is very fast, but it has been possible to see this consistently in automations.

The key part to the issue is that the submenu items are being created in async manner, so the refs are not being maintained.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> The key part to the issue is that the submenu items are being created in async manner, so the refs are not being maintained.

Short of fixing that issue we could at least avoid the error with some optional chaining.

**Comment by Kilian-Collender** [comment]
I'm happy to add the optional chaining @tay1orjones
