### ISSUE TITLE
Login/Logout component

### ISSUE THREAD

**Issue by antonmc** [carbon-design-system/carbon#164]
Maybe I missed an approach for it - I did look around, but forgive me if I missed it guidance, or ideally a whole template for login/logout/new account/lost account ...

... I know that all the individual components for that are available ... it just seems such a common thing that a premade template view might speed people along

**Comment by hellobrian** [comment]
Hey! Long time no see @antonmc! We used to have very large templates that were beyond our scope to maintain. But I like the idea of having smaller patterns that we can showcase using a small combination of components. It may be something we can provide in the future based on UX guidelines and available components in our system.
