### ISSUE TITLE
[Bug]: Multiselect typings are incorrect for onchange event

### ISSUE THREAD

**Issue by a88zach** [carbon-design-system/carbon#16433]
### Package

@carbon/react

### Package version

1.57.0

### React version

18.3.1

### Description

The typings are incorrect for the Multiselect onchange event.
![Screenshot 2024-05-10 at 9 41 01 AM](https://github.com/carbon-design-system/carbon/assets/1724822/59eb4539-3a53-4373-a014-f17811c7170f)

### Reproduction/example

https://stackblitz.com/edit/github-1ithgj?file=src%2FApp.tsx

### Steps to reproduce

Load the stackblitz and inspect the compiler error

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by a88zach** [comment]
Caused by https://github.com/carbon-design-system/carbon/pull/16147

cc: @guidari

**Comment by ggdawson** [comment]
Could be as simple as a local `OnChangeData`. WIP PR here -> https://github.com/carbon-design-system/carbon/pull/16440

Not yet clear if that type needs to be exported for broader use.
