### ISSUE TITLE
[Illustration]: Carbon for AI: Scaling new ways of working Medium Article

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#16432]
I'd like a banner image for this article on our process around the Carbon for AI work. It would be great if we could put it into the next sprint and try to get it done before the end of May!

https://medium.com/@jeannieservaas/8f3e2610ff11

**Comment by laurenmrice** [comment]
Published article: https://medium.com/carbondesign/carbon-for-ai-scaling-new-ways-of-working-fc6913624667
