### ISSUE TITLE
[Bug]: Calendar icon in Datepicker input got displaced when providing the prop inline to true

### ISSUE THREAD

**Issue by jagathgj** [carbon-design-system/carbon#16446]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.57.0

### React version

18

### Description

When providing prop `inline= true`, the calendar icon which appears over date picker input got displaced over the calendar. This is because the svg(.cds--date-picker__icon) is in absolute position.

<img width="1513" alt="image" src="https://github.com/carbon-design-system/carbon/assets/29351394/180299b0-3b23-4360-baf8-525b9f7aa32b">

### Reproduction/example

https://stackblitz.com/edit/github-y7mu2g?file=src%2FApp.jsx

### Steps to reproduce

```
<DatePicker
            dateFormat="m/d/Y"
            datePickerType="single"
            onChange={() => {}}
            inline={true}
            altInputClass="invisible"
            allowInput={false}
          >
            <DatePickerInput
              id="datePickerinput"
              placeholder="mm/dd/yyyy"
              labelText="Date picker"
              hideLabel={true}
            />
</DatePicker>
```

### Suggested Severity

None

### Application/PAL

WxO

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hey, there was a similar issue opened recently, https://github.com/carbon-design-system/carbon/issues/16216

There I mentioned:

> [When `inline` was added](https://github.com/carbon-design-system/carbon/pull/9702) it's only purpose was as a passthrough prop to flatpickr. There are no design specs for it and it wasn't really meant to be a fully supported functionality of the component.
> 
> The storybook documentation doesn't really reflect this though. It needs updated:
> 
> - Remove it as a control from the controls pane
> - Leave it in the prop tables though
> - Update the comments on the prop and type to reflect that this feature is just a passthrough and doesn't have full support
> 
> ---
> 
> Solving both this initial issue you pointed out, as well as the documentation items are great candidates for the community to fix/implement.

I think we can leave this issue open for making these updates to documentation

**Comment by tay1orjones** [comment]
@carbon-design-system/design are there any outstanding specs for this? should there be? If we're interested in fully supporting this feature we could take a look at how to accomplish this.

**Comment by laurenmrice** [comment]
@tay1orjones I agree with your response above. If we are not fully supporting this because it's a passthrough to flatpicker, the prop should be removed from the control pane and only listed in the prop tables. 

Since this use case of using an inline date picker input (instead of our default input with a background) is not a frequent need or ask from our community within and outside of IBM, I don't feel we need to fully support this feature and it can continue to be used as a passthrough to flatpicker.

**Comment by NabeelAyubee** [comment]
Hi @tay1orjones , I have resolved the calendar icon issue. Can you please review and merge the PR.
Link: [https://github.com/carbon-design-system/carbon/pull/17127](https://github.com/carbon-design-system/carbon/pull/17127)

PS: This is my first time. Please help me if I missed something.

**Comment by NabeelAyubee** [comment]
Hi, I have tried to resolved the above issue. I have updated the CSS which is causing calendar icon alignment issue. I have added the story for inline true props.
Tested in local. It is working as expected. 
Please review my PR and let me know if there's anything I missed.
