### ISSUE TITLE
[Bug]: Multiselect Controlled state is selecting disabled items

### ISSUE THREAD

**Issue by preetibansalui** [carbon-design-system/carbon#16445]
### Package

@carbon/react

### Package version

v11.57.0

### Description

In MultiSelect Controlled state, there is an example of selecting all items by clicking the 'Select all' button. On click to this button, it select all the items of list, including the **disabled ones**.
I understand that it's just an example to show user that they can pass their custom actions as a prop to select/deselect items, but selecting disabled items is wrong as an example to be present in storybook. 

Please check my comment in original PR: 

### Reproduction/example

https://github.com/carbon-design-system/carbon/pull/16139#issuecomment-2098302658

### Steps to reproduce

Go to Storybook > Multiselect > Controlled
On click to Select all button selects all items including disabled ones.
<img width="782" alt="image" src="https://github.com/carbon-design-system/carbon/assets/146315451/aa551907-c15f-4cc2-adc2-97da23e866a1">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ychavoya** [comment]
Hello, if you agree, I am willing to help with a PR to change this example I added. It should be simple, just filter out the disabled options when clicking the select all button:

```js
setSelectedItems(items.filter(item => !item.disabled))
```
