### ISSUE TITLE
Coordinate migration guides for v10 release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1644]
This might end up being an umbrella issue for writing and verifying migration content for:

- Individual components
- Styles

**Comment by joshblack** [comment]
_Issue Grooming 1/18_

We should do this for anything that is production ready in the next sprint.

**Comment by asudoh** [comment]
### Components

- [ ] Accordion - Markup change for icon
- [ ] Button - Markup change for icon
- [ ] Code snippet - Markup change for icon
- [ ] Combo box - Markup change for icon
- [ ] Content switcher - Markup change for icon
- [ ] Copy button - Markup change for icon
- [ ] Dropdown - Markup change for icon
- [ ] File uploader - `.bx--file--label` vs. `.bx--label`?
- [ ] Form - Makup changes for `<label>` vs. `<input>` positioning as well as for icon
- [ ] Inline loading - Markup change for background `<circle>`, `.bx--loading__stroke`?
- [ ] List box - Markup change for icon
- [ ] Loading - Markup change for background `<circle>`, `.bx--loading__stroke`?
- [ ] Modal - Markup change for icon
- [ ] Multi select - Markup change for icon
- [ ] Notification - Markup change for icon, etc.
- [ ] Number input - Markup change for icon as well as better support for label and form validation state
- [ ] Overflow menu - Markup change for icon
- [ ] Pagination - Markup change for icon, etc.
- [ ] Progress indicator - Markup change for icon as well as for overflow/optional labels support?
- [ ] Search - Markup change for icon
- [ ] Select - Markup change for icon
- [ ] Slider - Markup change for better visual/DOM element order matching?
- [ ] Structured list - Markup change for icon as well as for selection style change?
- [ ] Tabs - Markup change for icon
- [ ] Tag - Change in the list of `.bx--tag--xxx`
- [ ] Text input - Markup change for icon
- [ ] Tile - Markup change for icon
- [ ] Time picker - Markup change for icon, going away from `.bx--select--inline`?
- [ ] Toolbar - Markup change for icon
- [ ] Tooltip - Markup change for icon

**Comment by asudoh** [comment]
### Components React

- [ ] Slider - Value change via props no longer fires `onChange` event
- [ ] Tag - List of strings supported by `type` prop has been changed

**Comment by asudoh** [comment]
Closing as initial set of migration guide has been created and devs are adding/updating the guide as necessary. Anybody don't hesitate to speak up if this should be kept open - Thanks!

**Comment by asudoh** [comment]
Reopening so we don't lost track of the effort as a whole.
