### ISSUE TITLE
Add type styles to components for Carbon X

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1645]
With our new type styles ([Reference](https://next.carbondesignsystem.com/guidelines/typography/productive)) defined in https://github.com/IBM/carbon-elements, and our migration table created in: https://github.com/IBM/carbon-elements/issues/229, we should bring in our type styles for our components in X.

**Comment by asudoh** [comment]
@joshblack Does this connect to #1546? Thanks!

**Comment by joshblack** [comment]
Good call, marking as a duplicate. Thanks!
