### ISSUE TITLE
[Bug]: ComboBox not showing the correct highlighted

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/carbon#16474]
### Package

@carbon/react, @carbon/styles, carbon-components, carbon-components-react, @carbon/colors

### Package version

 "@carbon/charts-react": "1.15.6",         "@carbon/colors": "11.21.0",         "@carbon/feature-flags": "0.19.0",         "@carbon/ibm-products": "2.36.0",         "@carbon/icons-react": "10.49.0",         "@carbon/layout": "11.21.0",         "@carbon/react": "1.56.0",         "@carbon/styles": "1.56.0",         "@carbon/themes": "11.34.0",         "@carbon/type": "11.26.0",   "carbon-components": "10.50.0",         "carbon-components-react": "7.50.0",

### Description

The highlight is not on the selection even though it knows it is selected 

### Screenshots

https://github.com/carbon-design-system/carbon/assets/10100397/686db91b-7641-4cb1-8971-5df9eedfcc43

I am able to replicate this on the storybook. Looks like when there is an alteration to the name when it has a common name type in the dropdown list it breaks the highlight selection

https://github.com/carbon-design-system/carbon/assets/10100397/0b468459-17e9-421b-a2ab-87d2ff0d2bd7

### Steps to reproduce

Go here https://react.carbondesignsystem.com/?path=/story/components-combobox--with-layer

Then select `Option 2`.

Remove the 2, then click out of the ComboBox. It will default back to `Option 2`

When we click back into the ComboBox and it re-opens, the highlight selection is off. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@preetibansalui could you look into this and determine what we intend the ux of the highlightedIndex should be in this case?

**Comment by tay1orjones** [comment]
There's a few pieces here worth parsing out. When `allowCustomValue="false"`:

1. When you remove the `2` and the blue highlight ring goes to the first item in the list, this is intended behavior. `Option` loosely matches the 
2. When you then click away from the control and it resets the input value to be what it was previously, that is also intended behavior
3. When you re-open the dropdown, the blue highlight ring should be on the selected item. It's currently placing the blue highlight ring on the first item, which is not correct.

So really it boils down to anytime the dropdown is open (and `allowCustomValue="false"`), the blue highlight ring should be placed on the currently selected item, if there is one. If there isn't a selected item, it should be on the first item.

I found another example where this isn't working correctly:


https://github.com/carbon-design-system/carbon/assets/3360588/5ac1adee-c423-4722-9624-509c9529f5bf
