### ISSUE TITLE
[Bug]: DatePicker Range has unintended behavior when selecting dates

### ISSUE THREAD

**Issue by jackpronske** [carbon-design-system/carbon#16473]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.57.0

### React version

16.14.0

### Description

This bug is in 1.57.0, but not in any previous versions. (currently downgraded to >=1.56.0 and bug was not present)
When selecting first date in date range, calendar closes instead of staying open for user to pick second date in date range.
When selecting second date range, the first date range contains BOTH first and second dates in selection. 
We're using calendar as controlled component, with onChange functions and value properties. Again, this has worked until the recent update in 1.57.0. 

### Reproduction/example

https://stackblitz.com/edit/github-sf1rjr?file=src%2FApp.jsx,src%2Fmain.jsx

### Steps to reproduce

-click start date, select date (note that calendar closes, this is not correct calendar function)
-select end date
-user can see that start date contains string "05/13/2024 to 05/14/2024", which is not correct calendar function

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jackpronske** [comment]
Good morning. 

My link apparently didn't save the correct reflection of the bug. I have recreated and here (hopefully) the correct link
https://stackblitz.com/edit/github-sf1rjr?file=src%2FApp.jsx

**Comment by bendiggle** [comment]
I still don't think all of the above issues have been fixed after updated to 1.59.0. As you can see from the screenshot, we can still see that the start date input displays the "to" text with the end date.
<img width="171" alt="Screenshot 2024-06-14 at 08 59 27" src="https://github.com/carbon-design-system/carbon/assets/11047071/731b3662-7873-48b5-a983-5fddde367395">
