### ISSUE TITLE
[Bug]: Dropdown scrollbar click issue inside Modal

### ISSUE THREAD

**Issue by kironvk** [carbon-design-system/carbon#16485]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.1

### React version

18.2.0

### Description

When we try to scroll the dropdown list by clicking the scroll bar, dropdown list getting dismissed. This issue happens only when dropdown placed inside a Modal. Otherwise there is no issue with dropdown scrollbar.

### Reproduction/example

https://stackblitz.com/edit/github-pssigk?file=src%2FApp.jsx

### Steps to reproduce

Create a Modal. Place a dropdown component inside the Modal. Click on the scrollbar of dropdown list. Not able to scroll and the dropdown list will get closed automatically.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM Open pages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment]
Can reproduce on `Package version : 1.57.0` as well

**Comment by guidari** [comment]
Reported on Slack in the Combobox also:
https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1717413631187769

**Comment by riddhybansal** [comment]
Hey there , this issue I can replicate in Package version : 1.57.0 for both comboBox and dropdown.
Here is the link https://stackblitz.com/edit/github-pssigk-7d5j7p?file=src%2FApp.jsx


This issue doesnt persist in latest version by now i.e, Package version : 1.62.0 
Here is the link https://stackblitz.com/edit/github-pssigk-gfjwb6?file=package.json,src%2FApp.jsx
