### ISSUE TITLE
CheckboxGroup missing horizontal variant

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#16486]
Figma has horizontal variant, missing from React. Need to confirm spec/spacing with @carbon-design-system/design 

<img width="442" alt="Screenshot 2024-05-16 at 8 30 01 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/9e0d5f82-a497-4ef0-9cca-b73330b2f84b">

**Comment by laurenmrice** [comment]
Design spec for horizontal checkbox group. For reference this is also on our [Checkbox Style tab](https://carbondesignsystem.com/components/checkbox/style#structure) on the website.

<img width="977" alt="Screenshot 2024-05-20 at 12 30 33 PM" src="https://github.com/carbon-design-system/carbon/assets/43969356/d524b8d1-e64f-47fd-94c2-b0371ab7500e">
