### ISSUE TITLE
[Bug]: Extra Arrow is Visible in Tabs Component on resize

### ISSUE THREAD

**Issue by preetibansalui** [carbon-design-system/carbon#16484]
### Package

@carbon/react

### Browser

Chrome, safari, firefox

### Package version

V11.57.0

### Description

An extra arrow is visible in Tabs component on window resize.

https://github.com/carbon-design-system/carbon/assets/146315451/159e88d0-44a7-4762-bf83-8532481e6669

Additionally there is a second related bug [[1](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1715860665973839), [2](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1715863307911929)] where

> There is an unnecessary left arrow (nav button) that is appearing when you click on the last item of the tabs. This appears only in firefox browser.
This is reproducible in the carbon storybook playground. https://react.carbondesignsystem.com/?path=/story/components-tabs--playground

https://github.com/carbon-design-system/carbon/assets/3360588/527bdea2-d500-446f-b988-6c3f7f88259a

### Reproduction/example

Both are reproducible in storybook

### Steps to reproduce

Resize the Tabs window to a small size so that it should display an arrow for the tabs. Now resize the window to original size, Tab will not disappear.

**Comment by alisonjoseph** [comment]
Possibly related issue reported in slack.https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1717057488338139

 https://stackblitz.com/edit/github-aryg3b-bah5mt?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

![image](https://github.com/carbon-design-system/carbon/assets/2753488/7ad0a4b3-0c8f-468c-bd1c-18d1778bc41f)
