### ISSUE TITLE
The glossary guidance regarding the term "doc" is ambiguous.

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon#165]
On the **Carbon Design System > Content > [Glossary]**(http://carbondesignsystem.com/guidelines/content/glossary) page there is the following entry: 

> **Docs**
> (noun) documentation.
> Context: View docs.

This glossary entry shows the term both capitalized and not capitalized. Is this term meant to have standard capitalization (i.e. a lowercase "d") or always have a capital letter? 

As "docs" is just an abbreviation for "documentation" it would seem odd to me for it to be arbitrarily given a capital letter - however, I did notice that on the **Content > [General]**(http://carbondesignsystem.com/guidelines/content/general) page, there is an instance of it having such a capital letter: 

> When you create content – whether its introductory text on the UI, an error message, or a topic in the Docs – you are essentially a storyteller. 

Perhaps you could clarify.

**Comment by bsonefeld** [comment]
Updates have been made to the glossary.
