### ISSUE TITLE
[Feature Request]: Make the ContentSwitcher component controllable

### ISSUE THREAD

**Issue by martinscooper** [carbon-design-system/carbon#16509]
### The problem

The `ContentSwitcher` isn't controllable. Only the initial index can be set. In my case, when the user clicks on a `Switch` child they may have to accept a confirmation dialog first. Thus, I would like to change the index of the selected switch only once the user accepted the confirmation dialog an not when they click the `Switch`child. 

### The solution

Make the `ContentSwitcher` controllable by exposing a `value` or `index` attribute. 

### Application/PAL

LLM as a Judge

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
Hi @martinscooper Could you provide some more examples of your use case when the user may have to accept a confirmation dialog first before switching the switch? We do provide a `disabled` state on individual switches if that would help your use case.
