### ISSUE TITLE
[Feature Request]: Improve ContentSwitcher documentation

### ISSUE THREAD

**Issue by martinscooper** [carbon-design-system/carbon#16511]
### The problem

I think that both the name and the description of the `selectionMode` attribute of the `ContentSwitcher` component can be improved. Currently, it is:

```typescript
/**
    * Choose whether or not to automatically change selection on focus
*/
selectionMode?: 'automatic' | 'manual';
```

This is not totally true because the selection won't change on mouse focus. This attribute, based on a quick look at the [component's code](https://github.com/carbon-design-system/carbon/blob/23f19271f964a10a9fbc4616a43b05f5cc14e7d1/packages/react/src/components/ContentSwitcher/ContentSwitcher.tsx#L152), seems to be intended to determine whether the arrow left/right shortcuts should changethe selection index or just focus the left/right `Switch` child.

### The solution

Add a more descriptive attribute name and description, like: 

```typescript
/**
    * Choose whether or not to automatically change selection on left/right arrow pressed. Default: 'automatic'
*/
arrowShortcutSelectionMode?: 'automatic' | 'manual';
```

### Application/PAL

LLM as a Judge

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
I'm 50/50 on if the prop should be renamed. If we do, I'd suggest `keyboardSelectionMode`. I agree that at the very least the description for this prop could be improved.
