### ISSUE TITLE
[CIOH] User survey / feedback form

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#16514]
**Objective**

- [x] 1. Create a [form](https://airtable.com/appTjZQkBH46X5xwd/pagAIjwYcefF5mgDv/form) to receive valuable feedback from the audience after each office hours. 
- [x] 2. Make action items out of aspects which can have room for improvement.

**Comment by Kritvi-bhatia17** [comment]
I have added a total of 4 story points to this task: 3 for @Kritvi-bhatia17 and 1 for @alina-jacob.
