### ISSUE TITLE
Extra styles needed to support onClick prop for ProgressStep to allow updating the state if the user clicks the step

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#1652]
### Summary

Our users are clicking on the Progress Step of the ProgressIndicator and surprised when it's readonly.  This request is to add an onClick event handler to the ProgressStep so we can listen and update our state accordingly.

### Justification

To improve usability.

###  Functionality description

Clicking on a Progress Step invokes a callback to the component with the index of the step that was clicked on, so we can update our local state and update the Progress Indicator

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Did you mean to file this against [`our React repo`](https://github.com/IBM/carbon-components-react/issues)?
