### ISSUE TITLE
Typescript : SelectProps interface is not exported

### ISSUE THREAD

**Issue by mamantor** [carbon-design-system/carbon#16545]
### Package

@carbon/react

### Package version

V1.57.0

### React version

V18.3.0

### Description

The `selectProps` interface of the `<Select>` component is not exported. 

This means that to wrap the component with third-party libs (Formik for example) we need  to redeclare the interface. 

### Reproduction/example

Create a tsx component that wraps a `<Select>`  component

### Steps to reproduce

```
export function SelectField({ id, ...props }: MyFieldProps<SelectProps>) { // <- can't Access SelectProps
    return (
        <Field name={[props.name](http://props.name/)}>
            {({ field, meta }: FieldProps) => (
                <Select
                     invalidText={meta.error}
                    {...field}
                    {...props}
                />
            )}
        </Field>
    );
}
```

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kubijo** [comment]
Out of abundance of explicitness ... please do make sure other `xxxProps` interfaces are exported too.
