### ISSUE TITLE
[a11y]: the aria-label property on Combobox is ignored and the aria-labelledby property is automatically generated

### ISSUE THREAD

**Issue by oartigue** [carbon-design-system/carbon#16557]
### Package

@carbon/react, carbon-components

### Browser

Chrome, Firefox

### Package version

1.58.0

### Automated testing tool and ruleset

IBM Accessibility checker

### Description

if You add the aria-label property on Combobox, the property is ignored and the aria-labelledby property is automatically generated. When I use the IBM accessibility Checker, I get this error:
The 'id' "downshift-86-label" specified for the ARIA property 'aria-labelledby' value is not valid for combobox

### Reproduction/example

See Steps to reproduce

### Steps to reproduce

* Create a combobox with an aria-label
* => The aria-label is not generated and aria-labelledby property is automatically generated with an invalid id

Note: This issue https://github.com/carbon-design-system/carbon/pull/7777 has been closed but not fix this problem.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by LUCROFT** [comment]
Hi ! Sorry to hassle, but for our AVT deviation it would be great to have a timeframe for a fix on this. Thanks.
