### ISSUE TITLE
[Bug]: Fully controlled ComboBox (with selectedItem and onChange provided) does not properly update value

### ISSUE THREAD

**Issue by pedesen** [carbon-design-system/carbon#16565]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.58.0

### React version

18.3.1

### Description

There are issues when ComboBox is used as a fully controlled input (meaning with `selectedItem` and `onChange` props provided):

- onChange is not called in some situations
- ComboBox is not cleared when selectedItem changes to `null`

(see steps to reproduce for details)

This worked with v1.57.0 and stopped working with v1.58.0

### Reproduction/example

https://stackblitz.com/edit/github-w7mkre?file=src%2FApp.jsx

### Steps to reproduce

Given: a fully controlled ComboBox component (meaning with `selectedItem` and `onChange` props provided):

**Bug 1**
- change selectedItem prop programmatically to null (click separate "Reset" button in [example](https://stackblitz.com/edit/github-w7mkre?file=src%2FApp.jsx))

Problem:
- combo box value is not cleared

**Bug 2**
- Provide selectedItem prop
- Click the "clear selected item" button (x) inside the ComboBox

Problem:
- onChange is not triggered (no console output in [example](https://stackblitz.com/edit/github-w7mkre?file=src%2FApp.jsx))

**Workarounds**

For bug 1 there might be a workaround by providing a "key" prop which forces the ComboBox to re-render when selectedItem changes to null. But for bug 2 I wasn't  able to find a workaround.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by H31nz3l** [comment]
We encountered the same issue, specifically with the 'ComboBox' not clearing when the selectedItem is set to null. After updating to version @carbon/react ^1.67.1, the problem seems to be resolved."
