### ISSUE TITLE
[Bug]: Not able to see selected dropdown item's full name on first hover over.

### ISSUE THREAD

**Issue by shrvr** [carbon-design-system/carbon#16575]
### Package

@carbon/react

### Browser

Chrome

### Package version

^10.58.10

### React version

^7.57.1

### Description

When we hover over the selected item in the dropdown, the full name does not show in the tooltip right away. However, it does show when we hover over it again.

https://github.com/carbon-design-system/carbon/assets/65063487/58384dc2-719c-42e5-ad61-645a5a7c2198

### Reproduction/example

[Sandbox](https://codesandbox.io/p/sandbox/dreamy-thunder-r7cwyk?file=%2Fsrc%2Findex.js%3A18%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwl64nmd00063b6meeo5yq49%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwl64nmd00023b6mrearrwni%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwl64nmd00033b6mcc5q2o51%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwl64nmd00053b6m66kn5dlz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwl64nmd00023b6mrearrwni%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwl64nmc00013b6mxvotz1ga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwl64nmd00023b6mrearrwni%2522%252C%2522activeTabId%2522%253A%2522clwl64nmc00013b6mxvotz1ga%2522%257D%252C%2522clwl64nmd00053b6m66kn5dlz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwl64nmd00043b6m3tbnv3m4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwl64nmd00053b6m66kn5dlz%2522%252C%2522activeTabId%2522%253A%2522clwl64nmd00043b6m3tbnv3m4%2522%257D%252C%2522clwl64nmd00033b6mcc5q2o51%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwl64nmd00033b6mcc5q2o51%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
### Steps to reproduce

1. Create Dropdown
2. Give one item a long name
3. select that item from dropdown
4. now open the dropdown again and hover over the selected item. The tooltip does not appear.
5. Move out hover over and try again, tooltip appears

See video in description for more.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
[PR](https://github.com/carbon-design-system/carbon/pull/16576) to backport
