### ISSUE TITLE
[Bug: IBM Style guide implementation]: Content change request for unit of measurement of files (example 500kb to 500 KB)

### ISSUE THREAD

**Issue by anaghakarwa** [carbon-design-system/carbon#16579]
### Package

carbon-components

### Package version

v11

### Description

There is a misalignment for the unit of measurement used in carbon components and [IBM Style guide](https://ibmdocs-test.dcs.ibm.com/docs/en/ibm-style?topic=measurement-units)
Carbon components read as 500kb should be 500 KB. This change is crucial as many teams trust and rely on carbon design system language where teams don't have a content designer. For teams with content designers, it's a continuous effort to change this measurement style for every review. 

### Screenshots

<img width="1440" alt="Screenshot 2024-05-27 at 11 52 55 AM" src="https://github.com/carbon-design-system/carbon/assets/170917146/a43cada0-e5e1-4e8a-a331-c5133cdcff90">

### Steps to reproduce

Changing the unit of measurement to align better with the IBM content style guide

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Thanks for oppening that!

Here it is the description in IBM style guide mentioned in the issue
![Screenshot 2024-05-28 at 14 10 40](https://github.com/carbon-design-system/carbon/assets/52183462/a5ffb6c4-0031-449b-9252-8f7b57d0c4e2)
