### ISSUE TITLE
CDN for Carbon-Components CSS no longer working

### ISSUE THREAD

**Issue by exsqzme** [carbon-design-system/carbon#1658]
## CDN for Carbon-Components CSS no longer working

Using the CDN provided in the Getting Started section no longer works ([carbon-components-css](https://unpkg.com/carbon-components/css/carbon-components.min.css)). It appears that it is no longer available as of v9.68.0

**Comment by joshblack** [comment]
Hi @michaelaldave! 👋 Thanks for the report, we currently have a fix in #1657 for this. Sorry about the issue here!
