### ISSUE TITLE
[Feature Request]: Inline copy snippet in Carbon components

### ISSUE THREAD

**Issue by MichalDahanIBM** [carbon-design-system/carbon#16592]
### The problem

Users found it frustrating when trying to copy a specific part of a text.

### The solution

Adding the copy snippet capability into Carbon components will help the users have an easier, quicker, and more accurate copy experience.

### Examples

Please review the design in Figma, for the Text input helper text and the list components-
https://www.figma.com/design/IqGUOFmG1jXQlRYMm5ICUw/Carbon-components?node-id=0-1&t=UmPgxFYbl5LjwchN-1
An implemented solution for the text input helper text exists in the IBM Cloud Code Engine.

The code snippet inline was used in the solution-
https://react.carbondesignsystem.com/?path=/story/components-codesnippet--inline

### Application/PAL

IBM Cloud Code Engine

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Available extra resources

Figma file + implemented code

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by alisonjoseph** [comment]
@MichalDahanIBM You should be able to add the CodeSnippet into the helperText. I put together a quick example here, please re-open if I'm missing something. https://stackblitz.com/edit/github-kzrngk?file=src%2FApp.jsx
