### ISSUE TITLE
Ambiguity on the Content > Guidelines page

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon#166]
On the **Carbon Design System > Content > [Guidelines]**(http://carbondesignsystem.com/guidelines/content/guidelines) page (under the "Do use simple tense" section) there is the following guidance:

> If you need to use past or future tense, avoid verb tenses with the words have, has, had, been, should, would, and will.

But then the positive example provided for some past tense text **does** have the word "has" in it:

> "The limit has been exceeded."

Are the two examples for past tense the wrong way around?

**Comment by bsonefeld** [comment]
That's correct, seems we have mixed up those 2 terms and they should in fact be the other way around. 

Thanks for finding that content bug! We'll work on getting it updated on the site.

**Comment by bsonefeld** [comment]
Updated in Content Guidelines.
