### ISSUE TITLE
[a11y]: Password Input - Playground - JAWS is not announcing the Label text

### ISSUE THREAD

**Issue by 2nikhiltom** [carbon-design-system/carbon#16603]
### Package

@carbon/react

### Browser

Safari

### Package version

v1.58.0

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

JAWS

### Description

From the Password input - playground : set the labelt ext to "Enter your password"/ or any other string and observe the JAWS announcement.
JAWS is not announcing the label text when visiting the input field.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-passwordinput--playground&args=labelText:Label+text+one+to+three;hideLabel:!false

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
I just tested JAWS on my end and it is working as expected now.
