### ISSUE TITLE
[a11y]: Select - Playground - JAWS is announcing the name of the label even after hiding the label from playground

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#16613]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.58.0

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

JAWS

### Description

From the Select - playground, set the hide label Boolean to "True" and observe the JAWS announcement.
JAWS will announce the name of the label which is visually hidden.

### Recommend Fix
Ensure that visually hidden label is hidden from screen reader as well

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-select--playground&args=hideLabel:!true;readOnly:!false

### Steps to reproduce

none

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment]
Visually hidden `label` are expected to be announced by Screen readers - [reference](https://github.com/carbon-design-system/carbon/pull/18080)
