### ISSUE TITLE
[Bug]: Multiselect - Selected value not updated as per latest passed value

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#16615]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.58.1

### React version

v18.2.0

### Description

Not sure how to recreate this in Code Sandbox. We're calling carbon's Multiselect component like this -

```
<MultiSelect
					
	id={`${ControlUtils.getDataId(this.props.propertyId)}-multiselect`}
	disabled={this.props.state === STATES.DISABLED}
	translateWithId={(id) => listBoxMenuIconTranslationIds[id]}
	items={this.multiSelectDropdown.options}
	selectedItems={this.multiSelectDropdown.selectedOptions}
	onChange={this.handleOnChange}
/>
```

For multiselect control, we're passing `selectedItems={multiSelectDropdown.selectedOptions}`.
And when I logged `multiselectDropdown` object, it does show `multiselectDropdown.selectedOptions = [] `empty array as expected. Also I can see `None selected` text in the multiselect control which means we are passing an empty array. After passing an empty array in `selectedItems` prop, multiselect component still shows cached value.

https://github.com/carbon-design-system/carbon/assets/25124000/db1ac10c-1e70-4e5f-8d06-2248629d2760

### Expected Behavior - 
Initially `selectedItems` has 1 value selected. Later we pass `selectedItems=[]`. Multiselect component should clear the previously selected value after passing an empty array. 

### Reproduction/example

Please see the screen recording

### Steps to reproduce

- Steps to recreate the issue in Elyra canvas are given here - https://ibm-analytics.slack.com/archives/C598XEX8S/p1714174800857299?thread_ts=1713987591.343319&cid=C598XEX8S
Unfortunately this can only be reproduced in dev environment. Please feel free to contact me or @srikant-ch5.

- Please contact @tanvimehta10 for recreating this issue in DataStage. 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by srikant-ch5** [comment]
Hi @tay1orjones, I hope you're doing well. I just wanted to touch base and see if there have been any updates on above issue. Thanks.

**Comment by tay1orjones** [comment]
This was fixed via https://github.com/carbon-design-system/carbon/pull/16139

There is now a [controlled multiselect example](https://react.carbondesignsystem.com/?path=/story/components-multiselect--controlled) in storybook as well
