### ISSUE TITLE
[Bug]: ComboBox - allowCustomValue no longer fires change event with custom value

### ISSUE THREAD

**Issue by a88zach** [carbon-design-system/carbon#16624]
### Package

@carbon/react

### Browser

Chrome

### Package version

^1.58.0

### React version

18.3.1

### Description

Before version 1.58.0, a ComboBox with `allowCustomValue` set to true would fire the onChange event with an inputValue property after custom text is entered and the enter key is pressed

That event is no longer fired after https://github.com/carbon-design-system/carbon/pull/16283

### Reproduction/example

https://stackblitz.com/edit/github-1ithgj-dpiqwg?file=src%2FApp.tsx

### Steps to reproduce

1. Load the Stackblitz and enter a custom value.  Notice the Value label does not update with the custom entered text.
2. Stop the dev server and change the version back to 1.57.0
3. Restart the dev server and notice the ComboBox is working as expected

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by a88zach** [comment]
cc @preetibansalui

**Comment by a88zach** [comment]
@preetibansalui any chance someone can get some eyes on this one since it's a breaking change with a reproducible example?

**Comment by preetibansalui** [comment]
> @preetibansalui any chance someone can get some eyes on this one since it's a breaking change with a reproducible example?

Hey @a88zach , let me take it on priority. Thanks for pointing this out.

**Comment by preetibansalui** [comment]
Hey @a88zach , The stackblitz link you shared is not working properly, can you please check and fix it.

**Comment by a88zach** [comment]
@preetibansalui,  I just loaded the Stackblitz in an incognito window and it is working properly to reproduce the issue.  In what way was it not working properly for you?

**Comment by a88zach** [comment]
@preetibansalui this one is related and caused by the change in https://github.com/carbon-design-system/carbon/pull/16283

https://github.com/carbon-design-system/carbon/issues/16856

**Comment by a88zach** [comment]
@preetibansalui @sstrubberg anyway to push that PR through?  It's been open for almost a month now
