### ISSUE TITLE
[Bug]: Pagination - incorrect display when there are no items

### ISSUE THREAD

**Issue by a88zach** [carbon-design-system/carbon#16625]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.58.0

### React version

18.3.1

### Description

Pagination control shows incorrect/invalid messaging when `totalItems=0`

Currently it shows `1-{pageSize} items` for the current page items
Currently it show `_ of NaN pages` for the current page

![Screenshot 2024-05-30 at 3 02 47 PM](https://github.com/carbon-design-system/carbon/assets/1724822/f74985a6-e994-41f5-a500-96fc3a742be7)

### Reproduction/example

https://stackblitz.com/edit/github-1ithgj-5v2k2k?file=src%2FApp.tsx

### Steps to reproduce

Load the Stackblitz and expand the preview window to a resolution that displays the full control

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by riddhybansal** [comment]
Hi @laurenmrice , I have few questions here should we even display pagination when total items is 0 ? And if yes, what should be the design spec for the same. What messages should we display ??

**Comment by laurenmrice** [comment]
@tay1orjones @riddhybansal Yes, like Taylor said above we can keep the pagination there for now even when the total items is 0. Design has some website guidance discrepancies between our Empty state pattern and the Carbon for IBM Products Empty state component of when to display pagination for empty tables. But the products guidance is more up to date than ours and teams are currently using it this way so I think it is valid to keep it.
