### ISSUE TITLE
carbon grid is not as expected on MAC and windows 7,where the same is working in windows 10

### ISSUE THREAD

**Issue by anusha801** [carbon-design-system/carbon#1664]
carbon grid: the elements are getting placed according to the grid col values in windows 10 but they getting overlapped on each other in mac and windows 7 I see that happening for components like carbon buttons and dates.Do we need to add something to make it work at OS level as well?

**Comment by asudoh** [comment]
Hi :wave: our apologies for being late on this - Would you try creating a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox? Thanks!

**Comment by dakahn** [comment]
@anusha801 👋🏽
