### ISSUE TITLE
[Icon] 'Square solid' icon is empty svg

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#16697]
## Detailed description

The preview svg of the icon 'Square solid' does not exist in the Library on the Carbon Website.

Chrome browser

## Steps to reproduce the issue

https://carbondesignsystem.com/elements/icons/library/
Search for icon 'Square solid'

## Additional information

<img width="1395" alt="Screenshot 2024-05-29 at 11 47 41" src="https://github.com/carbon-design-system/carbon-website/assets/115161875/71ea89a5-9e6d-488c-9124-57edecd36f88">

Related issue (ui-icon-batch contribution): https://github.ibm.com/brand/ui-icons/issues/288

**Comment by alisonjoseph** [comment]
The source svg renders, however the component does not.

source
```
<?xml version="1.0" encoding="UTF-8"?>
<svg id="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
  <defs>
    <style>
      .cls-1 {
        fill: none;
      }

      .cls-1, .cls-2 {
        stroke-width: 0px;
      }
    </style>
  </defs>
  <rect class="cls-2" x="4" y="4" width="24" height="24" rx="2" ry="2"/>
  <rect id="_Transparent_Rectangle_" data-name="&amp;lt;Transparent Rectangle&amp;gt;" class="cls-1" width="32" height="32" transform="translate(0 32) rotate(-90)"/>
</svg>
```

**Comment by alisonjoseph** [comment]
duplicate, fixed here will be in next release https://github.com/carbon-design-system/carbon/pull/17560
