### ISSUE TITLE
On prem or on-prem? (Content > Glossary)

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon#167]
On the **Carbon Design System > Content > [Glossary]**(http://carbondesignsystem.com/guidelines/content/glossary) page, the introductory paragraph states the following:

> Users rely on consistent labels for common actions to predict how to interact with an interface.

But then I noticed you have the following term listed:

> **on prem, on-prem**
(adjective) on premises, on-premises.
Context: Incrementally port application features across on-prem platforms and clouds with consistent services.

From my experience, this is a term that designers/developers are often unsure about how to write, so having it included in the glossary is great, but why list two variations of the term? If the stated intent behind the glossary is to help us all use consistent labels, why not pick one variant (hyphenated or not) and standardize on that?

**Comment by bsonefeld** [comment]
@TomWaterton Thanks for pointing that out, Tom. The Glossary section content came directly from our ID (Information Design) team, so I'll sync up with them on which terminology is correct.

**Comment by bsonefeld** [comment]
Updated in the Content Glossary.
