### ISSUE TITLE
Accordion - experimental component (feedback from review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1671]
- [x] hover needs to completely go over the rule lines
- [x] focus needs to be on the whole row, not the chevron (safari doesnt have focus indicator)
- [x] motion updates
- [x] row height is 35px and should be 32px
- [x] line height needs to be 20 not 21px
- [x] fix content padding for mobile view to take up full width up until 16px from svg instead of 75%

**Comment by asudoh** [comment]
Got quick fix for some, @laurenmrice the light height seems font size (`14px`) times 1.5, do we want it non-relative to the font size? Also wondering what you meant by the first item. Thanks!

**Comment by laurenmrice** [comment]
@asudoh Yes the type size is 14px but the line height of spacing should be set at 20px (1.25 rem). The type token for this is body-long-01. 

For the first item about hover, currently when you hover over rows, the lines between the rows are showing up ontop of the hover. We want to cover these lines on the row when the hover is activated

<img width="1334" alt="screen shot 2019-01-22 at 10 00 04 am" src="https://user-images.githubusercontent.com/43969356/51548017-06536100-1e2d-11e9-946d-0d9903215a95.png">

**Comment by asudoh** [comment]
Thanks @laurenmrice for clarifying! Addressed the latter. The former seems to depend on #1546.

**Comment by asudoh** [comment]
From @laurenmrice (https://github.com/IBM/carbon-components/pull/1674#pullrequestreview-196104387):

> Looks good. But one thing I did notice on the focus states is that the blue outline is within the two line dividers of each row. When the focus is activated, the lines for that row should not be visible.
<img width="1276" alt="screen shot 2019-01-24 at 9 46 55 am" src="https://user-images.githubusercontent.com/43969356/51690214-dc7d7400-1fbd-11e9-908b-902423569c2c.png">
