### ISSUE TITLE
[Bug]: Multiselect component intermitant display clitch 

### ISSUE THREAD

**Issue by nedkeny** [carbon-design-system/carbon#16716]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.59.0

### React version

v18.2 

### Description

Selecting multiple items lead to a display clitch behaviour. The selection count tag and chosen items flicker between selected and deslected states. Affects all variants of the component intermitantly. 

This is visible and can be replicated on the live carbon react library, the issue is does not appear when trying to Gif cap the screen.  

https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Steps to reproduce

Open the component and interact with the menu items for a couple of minutes the display bug will occur. 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
closed in #16793
