### ISSUE TITLE
[Code Enhancement]: export reusable typescript interfaces and types

### ISSUE THREAD

**Issue by makafsal** [carbon-design-system/carbon#16714]
### The problem

This issue is derived from #16548 

While migrating Carbon for IBM Products to typescript, we've noticed we could reuse many typescript types and interfaces from Carbon in C4IP components. However, few of these types and interfaces are not exported from Carbon components.

### The solution

Export all typescript interfaces and types.

As I have mentioned in #16548, we can export these through a short and readable path like `import { ... } from '@carbon/react/types` or `import { ... } from '@carbon/react`.

And still, I'm happy to contribute ☺️

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by Gururajj77** [comment]
Hey @makafsal , the root `index.d.ts` contains the wildcard exports from the components, which means you should be able to get the exported props from the `@carbon/react`.

We are working on getting the props exported for all the components in this issue, #16154.

Could you verify that you are able to find that you can import the props for `Tab` component directly from `@carbon/react`?

**Comment by makafsal** [comment]
Hi @Gururajj77, I've gone through the above-mentioned issue. I think that will address the issue currently I'm facing. So we can close this issue for now, I hope we can reopen it if necessary.
