### ISSUE TITLE
[Bug]: `NumberInputSkeleton` doesn't support helper text or sizes

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#16717]
Compare `NumberInputSkeleton` to Figma.

- Add size props
- Add show/hide helpertext

Question for @carbon-design-system/design do we want to add the the +/- buttons to the coded skeleton state?

**Comment by riddhybansal** [comment]
Hey @laurenmrice @alina-jacob  Could you help with this ?

**Comment by alina-jacob** [comment]
Hi @riddhybansal, in Figma, the skeleton state has the +/- button for default component across all sizes but the skeleton state doesn't have the +/- button in the fluid component.


There are similar inconsistencies across Figma and storybook in other components and their skeleton states as well, so not sure what the correct representation is in a larger context.
