### ISSUE TITLE
[Bug]: Issue with RadioButtonGroup Selection in Wrapper Components

### ISSUE THREAD

**Issue by mrxnn** [carbon-design-system/carbon#16715]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.59.0

### React version

v18.2.0

### Description

We are using the Carbon Design System as the base for our component library. We've encountered an issue with the RadioButtonGroup component when it is wrapped in our custom wrapper components.

When using our wrapper components, selecting one radio button works fine, but selecting another does not unselect the previous selection. This behavior is observed only with our wrapper components and not when using the components directly from @carbon/react.

Is this the expected behavior when wrapping these components, or are we missing something in our implementation? Any guidance would be appreciated.

Thank you!

### Reproduction/example

https://codesandbox.io/p/sandbox/carbon-radiobutton-selection-y4vp6g

### Steps to reproduce

1. Create wrapper components for RadioButtonGroup and RadioButton.
2. Use these wrapper components in an application.
3. Attempt to select multiple radio buttons.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
A radio group is defined by giving each of radio buttons in the group the same [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name). Looks like you are missing that in your custom implementation.
