### ISSUE TITLE
[Text input] Add character limit/counter

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#1672]
### Summary

Text fields and text areas may have a maximum number of characters. This character limit might need to be communciated: 
1. to users ahead of time, so they can format their input,
2. Whilst a user is entering their input so they know how many characters remain
3. In the form of a validation error when the user reaches the limit

Design usage guidelines and/or enhancements to the components to support that design would be desirable. 

### Justification

It's a common pattern which you can see on a number of IBM products and tools and would be good to standardise. 

### Desired UX and success metrics

When a user is typing into a form field which has a maximum value, that value is communicated to the user, and if the limit is reached, they are informed whilst typing. 

### "Must have" functionality
Tell the user ahead of time what the value is
Tell the user clearly when they have hit the limit (and stop them entering text) 

Might also include a "x characters remaining" indicator so users know how many more they can enter.

**Comment by emyarod** [comment]
cc @IBM/carbon-designers for a spec or mockup on text input and textarea character limit UX

**Comment by jeanservaas** [comment]
@tomlroach this is great added functionality and we'll need to explore and possibly text a pattern before settling on a final spec for this:

- settling on a max
- how to deal with characters remaining
- whether to actually limit the characters or colorize the overflow as a warning

After the v10 release, we will start prioritizing opportunities to expand on existing functionality and get stuff like this into the pipeline. 

good discussion of this here and I really like the text colorization example at the bottom:
https://ux.stackexchange.com/questions/13055/character-limits-on-fields-pros-and-cons-and-best-practices

**Comment by aagonzales** [comment]
Adding general text area for devs. I'd be open to doing the character count in a different way. I know some times people prefer it counting down instead up. I know Andy Nelson had some [ideas/opinions](https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1519839354000302) on it 

![text area - white theme](https://user-images.githubusercontent.com/11670886/51865526-25119600-230c-11e9-9a7c-4ed7840217c5.png)

**Comment by aagonzales** [comment]
Could put it all in the helper text area? 
![image](https://user-images.githubusercontent.com/11670886/51865847-2099ad00-230d-11e9-8843-e48705df0765.png)

**Comment by connor-leech** [comment]
https://github.com/carbon-design-system/carbon-website/issues/1477 I made an issue about the same thing, added to website repo for site guidance

**Comment by emyarod** [comment]
has the spec for this been finalized?

**Comment by asudoh** [comment]
I have an impression that we need a bit more discussion on this, but @IBM/carbon-designers please don't hesitate to correct me if some of the links/images referred from this series of issues are something dev should start implementing. Thanks!

**Comment by asudoh** [comment]
High priority item among post-`v10` UX enhancements.

**Comment by ethangeyer** [comment]
👀

**Comment by emyarod** [comment]
reopening due to #3106

**Comment by fxfeiyi** [comment]
> Could put it all in the helper text area?
> ![image](https://user-images.githubusercontent.com/11670886/51865847-2099ad00-230d-11e9-8843-e48705df0765.png)

Could anyone give me a demo about how to use this Character counter?
The carbon version I use is as follows:
    "carbon-components": "^9.73.5",
    "carbon-components-react": "^6.91.4",
    "carbon-icons": "^7.0.7",

**Comment by jimmydyer** [comment]
Have there been any updates to added the `Character count` feature? I'm interested in adding this to our product but wanted to know if there design guidance on either using `helper text` to count down or using the `0/100` count-up method...

**Comment by TannerS** [comment]
I would also like to know if there is any update to this, I wouldn't mind a go of attempting to code this but I am not sure if this is a design that has been chosen or anyone actively working on it already @joshblack  maybe?

**Comment by Mikadv** [comment]
In our team we would also love to hear if this would finally make it. I saw dozens different implementations of this over the last years and a reinvention of the wheel over and over again. A simple an clean carbon component would be just superb!

**Comment by chrisconnors-ibm** [comment]
> In our team we would also love to hear if this would finally make it. I saw dozens different implementations of this over the last years and a reinvention of the wheel over and over again. A simple an clean carbon component would be just superb!

@Mikadv if there are multiple implementations out there, maybe in PALs, shouldn't one of those teams either contribute that effort back, or surface it broadly enough for reuse across the business?

**Comment by joshblack** [comment]
Sorry about the delay on my end @TannerS! I'd be happy to sync up on this with you, want to chat over Slack about this?

**Comment by TannerS** [comment]
@joshblack sure!

**Comment by abbeyhrt** [comment]
Hey @aagonzales! Quick question about this, would it be okay if we don't allow users to type past the allotted character count? `textarea`, the HTML element we use in `TextArea` has an attribute `max-length`, that sets the max character count and it prevents the user from typing passed the character count. I would need to look into it more but I'm assuming we get some accessibility wins if we use the element's native character limiter.

**Comment by TannerS** [comment]
in response to what abbey said, basically it would look like this and just stop the input once it hits the max without any error state 
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/8866319/148839491-6618ce4e-3aef-4d5a-9aac-00f6c5e5dcb2.png">

**Comment by TannerS** [comment]
Bumping for a response

**Comment by TannerS** [comment]
issue has been merged

**Comment by tw15egan** [comment]
Going to close this since @TannerS has successfully added this enhancement to the repo! It will be available in the next release. Thanks for all your hard work, Tanner!
