### ISSUE TITLE
[Bug]: hovering over close `x` in the `ComposedModal` shows 2 tooltips

### ISSUE THREAD

**Issue by joker23** [carbon-design-system/carbon#16724]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.59.0

### Description

When hovering over the close `x` in the modal we get 2 tooltips that say the same thing eg
![image](https://github.com/carbon-design-system/carbon/assets/2494686/30ce05ab-722f-41ef-b43d-adfb22fe88ee)

relates to https://github.com/carbon-design-system/carbon/issues/16623

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-composedmodal--default

### Steps to reproduce

Hover over the close `x`

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

IBM Cloudpak for AIOps

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by nandininarayanofficial** [comment]
@joker23 , @alisonjoseph  May I take this? I have applied a fix for this.
