### ISSUE TITLE
[Bug]: Child accordion's expand/collapse not working

### ISSUE THREAD

**Issue by soumen-roy-001** [carbon-design-system/carbon#16732]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.1

### React version

18.2.0

### Description

In nested accordions any child accordion's expand/collapse not working.

### Reproduction/example

https://stackblitz.com/edit/github-tb1sze

### Steps to reproduce

Create any nested accordions. Click on any child accordion to expand/collapse and that's not working.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM OpenPages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@soumen-roy-001 Hi there, nested accordions [aren't a supported use case](https://carbondesignsystem.com/components/accordion/usage/#when-not-to-use)

> When organizing large amounts of information that can be nested, consider using [tree view](https://carbondesignsystem.com/components/tree-view/usage) instead.

**Comment by tay1orjones** [comment]
@soumen-roy-001 @fbarroso24 Following up after our discussion during office hours just now - if you could share here the workaround you've made, I'd be up for reopening this to evaluate if we could add the fix to accordion.

It wouldn't be a formal endorsement of supporting nested accordions, but I'd love to at least unblock your use case.

**Comment by tay1orjones** [comment]
Thanks! I think the general concern with the pattern is usability regarding information overload for those using assistive technologies, particularly screenreaders. [Here's a good explainer](https://www.nngroup.com/articles/accordions-on-desktop/#:~:text=When%20the%20content%20has,nature%20of%20the%20content) on this from Nielsen Norman Group:

> When the content has a deep hierarchy with multiple sublevels, it can be too complex to be displayed in a flat-hierarchy format like accordions. Users may feel confused and lose track of where they are within the accordion structure. In such cases, consider alternatives such as tabs or vertical local navigation to better accommodate the hierarchical nature of the content.

That said, this functionality isn't something that should be disallowed or blocked by the system.[^1] We won't recommend or document it for reasons like the one above, but getting your workaround (or a similar one) baked into the accordion and adding a unit test for it makes sense. 

[^1]: Based on a [brief internal team discussion](https://ibm-studios.slack.com/archives/GD8JG6JR3/p1718118822708299)
