### ISSUE TITLE
[Feature Request]: Add Icon for Scala and Spark in the Carbon Icons Library

### ISSUE THREAD

**Issue by Sparker0i** [carbon-design-system/carbon#16739]
### The problem

The [Scala Programming Language](https://www.scala-lang.org/) and the [Spark framework](https://spark.apache.org/) do not have an icon in the Carbon Design System icon library

### The solution

Make the icons for the same available in the icon library.

### Examples

SVGs are available here:
Scala: https://www.svgrepo.com/svg/306700/scala
Spark: https://www.svgrepo.com/svg/372952/spark

### Application/PAL

IBM CIO Internal offering

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Thanks @conradennis closing now!
