### ISSUE TITLE
[Bug]: DatePicker startValue is coming as a combination of both start and end dates 

### ISSUE THREAD

**Issue by Geethkadali** [carbon-design-system/carbon#16734]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.57.0

### React version

v18.3.1

### Description

When passing value to the Datepicker then start value is showing a combination of both start and end date

![image](https://github.com/carbon-design-system/carbon/assets/45656474/698dd6c2-cf88-482a-920d-89f306f1ae78)

If we remove value to Datepicker and select the dates using keyboard, with the keyboard interaction always the onChange function is getting triggered and not moving to the next elements. This is especially challenging when trying to select the dates using only a keyboard.

### Reproduction/example

https://stackblitz.com/edit/github-pjo2fh?file=src%2FApp.jsx&preset=node=

### Steps to reproduce

1. If we pass value in Datepicker select the start and end dates, then startValue is coming as a combination of start and end date, with keyboard interaction it's going to the next element.
2. If we remove value in Datepicker and select the dates with keyboard and pressing tab not going to the next element, after end date always onChange function is getting triggered.  

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by marcinmotNB** [comment]
There is also problem with clearing values in inputs - when you'll provide [null, null] array to DatePicker snd date is not cleared.
