### ISSUE TITLE
[Bug] [DatePicker]: End Date Calendar in Range variant remains Open on click away

### ISSUE THREAD

**Issue by 2nikhiltom** [carbon-design-system/carbon#16740]
### Package

@carbon/react

### Package version

v1.58.0

### React version

18.02

### Description

When using the `datepicker` with a `range` selection, the `end date` calendar does not close when the user clicks away, causing it to always stay open. 

In contrast, the `start date` calendar closes correctly when the user clicks away. 

https://github.com/carbon-design-system/carbon/assets/63502271/4d34a330-1ea1-4bec-9f9c-9c601243d14c

Surfaced while debugging : https://github.com/carbon-design-system/carbon/issues/16337__

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

1.`datepicker` with a `range`
2. Select start and end date
3. Open end date calendar, do not select any date and click outside of calendar (Notice that calendar does not close)  

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
This bug was introduced in 1.58
