### ISSUE TITLE
[a11y]: Breadcrumb - With Overflow Menu - JAWS is not announcing the current breadcrumb

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#16749]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.58.1

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

JAWS

### Description

While navigating through the arrow keys, JAWS is not announcing the current breadcrumb.

### Recommended Fix
aria-current is not implemented for the current breadcrumb.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-breadcrumb--breadcrumb-with-overflow-menu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by elycheea** [comment]
@sstrubberg looks like this one is a blocker for https://github.com/carbon-design-system/ibm-products/issues/5764.
