### ISSUE TITLE
Review elements pages resource cards

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#1675]
Need to think about what are the best links/resources to include on the top of every elements page. For example, one current link (Carbon Design Kit) should be removed because this resource is always available on the left nav. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ecf9b49f-7262-442b-9ce3-4f07efd53e16)

**Comment by asudoh** [comment]
Moved to: carbon-design-system/carbon-website#916
