### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by willragan** [carbon-design-system/carbon#16764]
### The problem

The error icon in dark mode doesn't maintain a contrast ratio that will make it viewable by people with visual impairments this illustration needs to be more accessible in dark mode.

<img width="470" alt="Screenshot 2024-06-12 at 10 03 06 AM" src="https://github.com/carbon-design-system/carbon/assets/77511036/f28f5f88-7bc9-4f34-87d3-4b9bbf54ad4d">

### The solution

This is our solution: changing the color of the illustration.

<img width="363" alt="Screenshot 2024-06-13 at 12 40 51 PM" src="https://github.com/carbon-design-system/carbon/assets/77511036/80a01ee6-10f1-47de-aa78-aa476691ee67">

### Examples

this is an example of the dark theme "empty state" pattern with Ripasso

<img width="506" alt="Screenshot 2024-06-13 at 12 47 57 PM" src="https://github.com/carbon-design-system/carbon/assets/77511036/4e1bfcd7-a488-4258-8cbc-f29f11ff9642">
<img width="773" alt="Screenshot 2024-06-13 at 12 47 46 PM" src="https://github.com/carbon-design-system/carbon/assets/77511036/c4d99bb4-3bc3-471e-b367-01dbe048e7ab">

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Hey @willragan thanks for submitting this issue. Unfortunately, the Carbon team doesn't maintain that illustration. This is most likely an implementation issue on your end. Thanks!
