### ISSUE TITLE
[CIOH] Task rotation board

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon#16775]
- [x] Create a task rotation board to evenly distribute various task pre-during and post CIOH sessions among team members.
   >  - [Draft](https://ibm.ent.box.com/notes/1503473637372)
   >  - [Final iteration](https://ibm.box.com/s/cgb1w65zrflg9l3lt21qqxya7qqmwqdi)

- [x] Find a software that can auto-assign tasks to owners in a rotational basis.
  >  Found a few softwares: 
  >  (Ref: [Thread](https://ibm-studios.slack.com/archives/C0631BBKVCM/p1718595000696039))
  >  - [Picker Wheel website](https://pickerwheel.com/tools/random-team-generator/)
  >  - [Keamk](https://www.keamk.com/cxtej5ioc4cqx7al8vuci2lv)
  >  - https://en.ajakteman.com/p/group.html)

        But ended up incorporating via SLACK WORKFLOW.

**Comment by Kritvi-bhatia17** [comment]
I have added a total of 3 story points to this task: 1 each for @alina-jacob, @benjamin-kurien, and @Kritvi-bhatia17.
