### ISSUE TITLE
[Feature Request]: UI component for text selection

### ISSUE THREAD

**Issue by niranjanibm** [carbon-design-system/carbon#16774]
### The problem

While using Carbon Design system for a Figma prototype, I came across a representation that is not available in the library. Text selection: The use case is to highlight the searched text within the populated search result. The solution could be used in scenarios where representations of selected text is necessary.
<img width="1728" alt="Currently used in Figma" src="https://github.com/carbon-design-system/carbon/assets/169025099/9897dd53-98df-4b9e-8f85-3c0bf911fccf">

### The solution

The proposed solution is to use a coloured auto layout bounding on text box with exact same width and length, effectively representing that the text is selected.

<img width="790" alt="Search highlight" src="https://github.com/carbon-design-system/carbon/assets/169025099/3bc80793-b1ff-4865-a6b6-1c7e3519d97f">

### Examples

<img width="643" alt="Search Highlight using autolayout" src="https://github.com/carbon-design-system/carbon/assets/169025099/b8a38cc6-41ce-4012-8471-5c52a3a51c1d">
<img width="1330" alt="Search Highlight Figma" src="https://github.com/carbon-design-system/carbon/assets/169025099/b8769a6d-ab6f-474f-93bc-141337aaebbd">

### Application/PAL

WatsonX Code Assistant

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
Hi @niranjanibm, this is a pattern that we do not have right now in our system. You can implement and customize this on your own and make sure it still follows the IBM Design Language and is also accessible.
