### ISSUE TITLE
Update Copy icon in base Code Snippet component and React component

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1680]
## Update Copy icon in base Code Snippet component and React component

Mike and Conrad reverted back to the Copy-20 icon for all the code snippet copy icons. The code snippet component on the Carbon website also relies on the Carbon code snippet component. 

- [ ] update copy icon in Carbon code snippet base component (terminal and block) to Copy 20 icon

- [ ] update copy icon in Carbon React code snippet to Copy 20

- [ ] also noticed that the tooltip the copy icon is pulling in is not our tooltip component, can we update that to pull in ours?

**Here's what the the code snippet looks like now:**

<br>

Component display window

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/639f0889-6d57-4c75-ad46-feb7f2dcf7bb)

terminal
![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/8ac9c3a2-199a-4250-ac37-39197704e979)

<br>

**It needs to be this guy:**

![copy.svg](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/f5391a1e-4942-47d4-9dde-bf26f8ba62cd)

<br> 

**this is what's happening with tooltip now:**

![image](https://user-images.githubusercontent.com/43144260/51628573-f3af5980-1f0a-11e9-8cc7-fa185eb2a523.png)

**Comment by asudoh** [comment]
It looks resolved already.
