### ISSUE TITLE
Depreciated prop 'bottom-left' is not updated in the DefinitionTooltip align prop

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/carbon#16810]
When we try to update @carbon/react to latest, testcases fails with error `Warning: "bottom-right" is a deprecated value for the "align" prop on the "Popover" component.` But when I update it , Definition tooltip testcase fails with error `Invalid prop align of value bottom-start supplied to DefinitionTooltip`

@carbon react version : v1.59.0

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/16737
