### ISSUE TITLE
[Bug]:  Search and select the value from Combobox control not displaying the selected value.

### ISSUE THREAD

**Issue by ambrishsinghibm** [carbon-design-system/carbon#16829]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.60.1

### React version

v18.2.0

### Description

Hi Team, 
Unable to search and select the value in combo box control after the latest upgrade of the carbon react library. Please provide the solution/ fix for this as soon as possible. Due to this issue not able to complete my User story and it's blocker for me.

I appreciate any help you can provide.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobox--allow-custom-value

### Steps to reproduce

1. Open this URL: https://react.carbondesignsystem.com/?path=/story/components-combobox--allow-custom-value
2. Search "App" string into the search text area 
![image](https://github.com/carbon-design-system/carbon/assets/160111531/ca9d7ea3-430a-49ae-b37a-f57b145ea068)

3. After a search, select the value, for example, "Pineapple" from the drop-down
4.
**Expected:** It should select the "Pineapple" value into the combo box drop-down
**Current behaviour:** It's selecting the other value, for example "Orange" in combo drop down
![image](https://github.com/carbon-design-system/carbon/assets/160111531/20e0d4de-085b-439d-9ad6-bcb510633259)

Note: This issue is reproducible in the carbon storybook

in

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting, this is related to https://github.com/carbon-design-system/carbon/issues/16630
