### ISSUE TITLE
[Bug]: Focus on FilterableMultiSelect always persists once click on the control

### ISSUE THREAD

**Issue by ambrishsinghibm** [carbon-design-system/carbon#16830]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.60.1

### React version

18.2.0

### Description

Hi Team, 

I have upgraded the carbon library in my application and replace the Multiselect drop down to FilterableMultiSelect. I am observing one issue while using this control.

After the page loads, If click on the control, the focus always persists,  if we move to another control by clicking through the mouse or moving one control to another control using tab button

Please look into this issue and provide a solution on this.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect

### Steps to reproduce

1. Open this URL: https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect
2. Click on the control
3. Next click outside of the control
4. The focus of the control remains there. it should be removed from the control
![image](https://github.com/carbon-design-system/carbon/assets/160111531/1e205171-be83-4fdd-a821-914d61fc9ca6)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting, I'm seeing the same on https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-form--form-example

**Comment by ambrishsinghibm** [comment]
@guidari Integrated with the latest and working as expected. Thank you 👍

**Comment by ambrishsinghibm** [comment]
Thank you for a quick fix. Issue fix for one scenario but control still focusable when 
1. Select some value from the control
2. Single or Double-click the control text area
3. Next click outside the control. 

Expected: If the user clicks outside the control, the Control should not be focusable and the blue border should not be visible.

Current behaviour: Control is still focused

You can verify the above scenario in the story book
https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect



Please look into this issue and provide the solution.
Thanks

**Comment by riddhybansal** [comment]
Hey @ambrishsinghibm we have another issue opened for this https://github.com/carbon-design-system/carbon/issues/16877 as sev-3
