### ISSUE TITLE
[Bug]: `OverflowMenu` styles overridden by `Button`

### ISSUE THREAD

**Issue by cuppajoey** [carbon-design-system/carbon#16836]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.60.0

### React version

v18.2.0

### Description

When importing component-level stylesheets, rather than the full carbon stylesheet, `Button`'s styles will override `OverflowMenu`'s if the button stylesheet is imported later.

<img width="900" alt="image" src="https://github.com/carbon-design-system/carbon/assets/14837881/5ba3d28f-8340-45e0-8991-81bf06a637e1">

This is because `OverflowMenu` does not set the rendered `IconButton`'s `kind` prop which defaults to primary and the style selectors have an equal specificity (`.cds--btn--primary` vs `.cds--overflow-menu`).

#### 💡 Possible solution
The documentation for `OverflowMenu` states that it [_should_ only render a ghost button style](https://carbondesignsystem.com/components/menu-buttons/usage/#overflow-menu). If that's true, we should set the `kind="ghost"` which would prevent primary button styles from overriding it.

At the very least, we should set "ghost" as a default value and allow consumers to change it.

### Reproduction/example

https://stackblitz.com/edit/github-utkywz?file=src%2FApp.jsx,src%2Fbutton.scss,src%2Foverflow.scss

### Steps to reproduce

1. Render a `Button` and an `OverflowMenu` with default values.
2. Import `@carbon/styles/scss/components/overflow-menu`.
3. Later import `@carbon/styles/scss/components/button`.
4. Observe the `OverflowMenu` adopt `Button`'s primary styles.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
Hi @cuppajoey , can you please check this stackblitz? I just added the `index.scss` with `use @carbon/react`. 
https://stackblitz.com/edit/github-utkywz-ag6nfs?file=src%2FApp.jsx,src%2Findex.scss,src%2Fmain.jsx

**Comment by cuppajoey** [comment]
> Hi @cuppajoey , can you please check this stackblitz? I just added the `index.scss` with `use @carbon/react`. https://stackblitz.com/edit/github-utkywz-ag6nfs?file=src%2FApp.jsx,src%2Findex.scss,src%2Fmain.jsx

@Gururajj77 I understand that it works if you import Carbon's entire stylesheet, but that's not the issue. Carbon supports importing individual component stylesheets for consumers who don't want the entire bundle. For those consumers the import order causes an issue, as demonstrated in the original StackBlitz.

**Comment by tay1orjones** [comment]
Yep, I think we should do both:

1. Update OverflowMenu to set kind="ghost"
2. Fix the specificity issue when not using the central entrypoint so this is less likely to happen in other framework variants. Using `:not()` might be helpful.
