### ISSUE TITLE
Tab: content class name without prefix

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#1684]
## Detailed description

> Describe in detail the issue you're having.

The `Tab` component has styles for a class name selector that is `.tab-content` I expect all class names in the design system to be prefixed.

> Is this issue related to a specific component?

Yes, `Tab`

> What did you expect to happen? What happened instead? What would you like to see changed?'

I expect the all tab related class names to include the set prefix (ie `bx--`)

> What version of the Carbon Design System are you using?

9-something

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Security

**Comment by joshblack** [comment]
Hi @diego-codes! 👋 Definitely agreed, all selectors should have the prefix. Mind submitting a PR to fix? 😉

**Comment by diego-codes** [comment]
Sure thing! I just realized it's only a React component issue. Should I move this story over or can I reference this one in my PR?

**Comment by emyarod** [comment]
it looks like this issue was transferred https://github.com/IBM/carbon-components-react/issues/1790 and should be resolved in https://github.com/IBM/carbon-components-react/pull/1799
