### ISSUE TITLE
[Bug]: DatePicker with type range renders value property incorrectly 

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon#16848]
### Package

@carbon/react

### Package version

v1.60.1

### React version

v18.3.1

### Description

I use a DatePicker in our product very similar to this:
 ```
  const [start, setStart] = useState();
  const [end, setEnd] = useState();

  const onPeriodChanged = (range) => {
    setStart(range[0]);
    setEnd(range[1]);
  };

  return (
    <div>
      <DatePicker
        datePickerType="range"
        value={[start, end]}
        onChange={onPeriodChanged}
      >
        <DatePickerInput
          id="date-picker-input-id-start"
          placeholder="mm/dd/yyyy"
          labelText="Start date"
          size="md"
        />
        <DatePickerInput
          id="date-picker-input-id-finish"
          placeholder="mm/dd/yyyy"
          labelText="End date"
          size="md"
        />
      </DatePicker>
    </div>
  );
```

When selecting a range, the first input contains start & end date. This shouldn't be, right?

![Screenshot 2024-06-24 at 08 37 06](https://github.com/carbon-design-system/carbon/assets/50624181/7d805a2e-1d24-43a7-b35f-60a276aa998d)

Note: With previous versions (Carbon 10) this worked...

### Reproduction/example

https://stackblitz.com/edit/github-7ujtwx?file=src%2FApp.jsx

### Steps to reproduce

- Select a date range
- Expected: The first input shows the start date only
- Actual: The first input contains start & date

![Screenshot 2024-06-24 at 08 37 06](https://github.com/carbon-design-system/carbon/assets/50624181/9f68c7bd-fcea-4636-bbd3-f76205a821bf)

Note: With previous versions (Carbon 10) this worked...

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by bendiggle** [comment]
I have also been seeing the same and left a comment on a [previous closed issue](https://github.com/carbon-design-system/carbon/issues/16473#issuecomment-2167474188)
<img width="171" alt="Screenshot 2024-06-14 at 08 59 27" src="https://github.com/carbon-design-system/carbon/assets/11047071/001c9862-c15a-41b1-b52b-0145b376100a">

**Comment by riddhybansal** [comment]
Hey @KJaspers @bendiggle We already have any raised [issue](https://github.com/carbon-design-system/carbon/issues/16826) for this and added in our sprint.

**Comment by riddhybansal** [comment]
#16734

**Comment by sstrubberg** [comment]
Dupe https://github.com/carbon-design-system/carbon/issues/16734
