### ISSUE TITLE
[Bug]: FileUploaderItem not working in ShadowDOM

### ISSUE THREAD

**Issue by wfdcfs** [carbon-design-system/carbon#16844]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

1.60.1

### React version

18.3.1

### Description

We use the shadowDOM.
When I update beyond `1.39.0` (`1.39.0` works for us), I have an issue with the `FileUploaderItem` component - this component works fine if not using shadowDOM.
The issue is with line https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/FileUploader/FileUploaderItem.tsx#L111
```
const element = document.querySelector(`[title="${name}"]`);
```
In the shadowDOM, `element` returns as `null `and later the Carbon component tries to do `setIsEllipsisApplied(element.offsetWidth < element.scrollWidth);` - this is where it bombs out with the error: 
```
TypeError: Cannot read properties of null (reading 'offsetWidth')
    at isEllipsisActive (FileUploaderItem.js:72:34)
    at eval (FileUploaderItem.js:77:5)
    at commitHookEffectListMount (react-dom.development.js:23184:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23302:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24722:9)
    at commitLayoutEffects_begin (react-dom.development.js:24708:7)
    at commitLayoutEffects_begin (react-dom.development.js:24690:11)
    at commitLayoutEffects (react-dom.development.js:24646:3)
    at commitRootImpl (react-dom.development.js:26857:5)
    at commitRoot (react-dom.development.js:26716:5)
```

### Reproduction/example

https://stackblitz.com/edit/react-ts-mss5gp?file=index.tsx

### Steps to reproduce

Just open the stackblitz link and you will see the error message.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by s100** [comment]
Seeing a similar issue while testing using Mocha and JSDOM. You should be [using refs for this purpose](https://react.dev/learn/manipulating-the-dom-with-refs), not `document.querySelector`.

**Comment by s100** [comment]
We have an extremely hacky workaround:

```js
const originalQuerySelector = document.querySelector
document.querySelector = function (query) {
  if (query === '[title="yourNameHere"]') {
    return {
      offsetWidth: 0,
      scrollWidth: 0
    }
  }
  return originalQuerySelector.apply(this, arguments)
}
```
