### ISSUE TITLE
[Bug]: the icon inside `IconButton`  with `kind` prop `danger--ghost` is not aligned to center

### ISSUE THREAD

**Issue by Gururajj77** [carbon-design-system/carbon#16841]
### Package

@carbon/react

### Package version

v11.60.1

### React version

v18

### Description

The icon inside the `IconButton` is not center aligned when the `danger--ghost` is used with `kind` prop

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=kind:danger--ghost;tooltipAlignment:center;tooltipPosition:bottom

### Steps to reproduce

Go to the above storybook link and hover on the `IconButton`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
the user has managed to fix it using below css, this might help:

```
.cds--btn--danger--ghost {
  -webkit-padding-end: unset;
  padding-inline-end: unset;
}
```

**Comment by alisonjoseph** [comment]
This isn't a supported variant combination per design docs.
https://carbondesignsystem.com/components/button/usage/#danger-button-variations
https://ibm-studios.slack.com/archives/C0M053VPT/p1692220573334289

**Comment by Gururajj77** [comment]
Closing this as its not supported variant as per design

**Comment by tay1orjones** [comment]
Related https://github.com/carbon-design-system/carbon/issues/14300
