### ISSUE TITLE
[Bug]: Unexpected Increment Behavior in NumberInput Component with Step Prop

### ISSUE THREAD

**Issue by mohakgemini** [carbon-design-system/carbon#16865]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.60.2

### React version

v20.15.0

### Description

When using the NumberInput component with a step prop, the increment behavior is not as expected. Specifically, when the default value is set to "1000" and the step prop is set to 1000, pressing the "+" button should increment the value to "2000". However, the value first increases to "1001" instead. Upon pressing the "+" button again, the value increments to "2001".

Also, the storybook crashes when trying to replicate the same in storybook

**Expected Behavior:**

- Default value: 1000
- step prop value: 1000
- First press of the "+" button should set the value to 2000.
- Subsequent presses should continue to increment the value by 1000.

**Actual Behavior:**

- Default value: 1000
- step prop value: 1000
- First press of the "+" button sets the value to 1001.
- Second press sets the value to 2001.

### Reproduction/example

https://stackblitz.com/edit/github-mrrrn4-kvfdxe?file=src%2FApp.jsx

### Steps to reproduce

1. Set up a NumberInput component with a default value of "1000".
2. Add a step prop with a value of 1000.
3. Press the "+" button.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
It looks like is using a lot of memory in the browser also
