### ISSUE TITLE
[Bug]: MenuItem is not correctly focused when expanded within ComposedModal

### ISSUE THREAD

**Issue by fred104** [carbon-design-system/carbon#16861]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.60.0

### React version

v18.2

### Description

We are trying to use MenuButton within ComposedModal and found a strange bug. When you click the MenuButton to expand the menu, it should focus on the first menu item. However, the other button is being focused which is triggered by ComposedModal.

See the call stack below. (handleBlur and wrapFocus are from ComposedModal.)
![image](https://github.com/carbon-design-system/carbon/assets/1077859/8e907566-dd74-4a57-a58a-f712cb4c1228)

### Reproduction/example

https://stackblitz.com/edit/github-yzyrus?file=src%2FApp.jsx

### Steps to reproduce

Click the MenuButton (Click me and you will see above button being focused!) and you will see the above button is focused. The console prints out the call stack too.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM SOAR

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment]
This will be tracked via
Issue : https://github.com/carbon-design-system/carbon/issues/16882
PR: https://github.com/carbon-design-system/carbon/pull/17145
