### ISSUE TITLE
Floating UI: Add `detectOverflow` configurable collision boundary

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#16879]
In certain situations consumers may need to customize the boundary/element used to detect collisions. One example of this might be the modal - components like Popover may need to reflow based on the bounds of the modal content container, and not the viewport. 

To this we can implement the [detectOverflow](https://floating-ui.com/docs/detectoverflow) as a middleware 

Eventually we could also
* add props for consumers to pass in their own padding
* add this prop to other components using floating-ui autoAlign
* ensure this is configurable from anywhere in their react tree #17003

**Comment by riddhybansal** [comment]
@tay1orjones the issue is in menuButton as well most probably with comboButtons too 

https://github.com/user-attachments/assets/60cec959-60be-4ad7-8f6d-57a6e1cba135

Here is the [stackblitz](https://stackblitz.com/edit/github-f6aces?file=src%2FApp.jsx,package.json) also. 
I guess this comes in collision detection only

**Comment by preetibansalui** [comment]
Hi @tay1orjones , Just realised, do we need to add `hide from Floating UI` in tooltip as well? Its hiding itself when tooltip icon is not visible in viewport because its no more hoverable.

**Comment by tay1orjones** [comment]
The first phase of this will be delivered through: 
* https://github.com/carbon-design-system/carbon/pull/17139 
* and then this followup to fully close this issue:
* https://github.com/carbon-design-system/carbon/pull/16995
