### ISSUE TITLE
[Bug]: Onfocus of Combo box it is  showing red and blue border both when field is invalid, It should show only blue when field is invalid and it is on focus 

### ISSUE THREAD

**Issue by anoopjaiswal903** [carbon-design-system/carbon#16878]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.45.0

### React version

18

### Description

On the focus of Combo box it is showing red and blue border both when the field is invalid, It should show only blue when the field is invalid and it is on focus.

Expected behavior - 
1 -When the field is **invalid** and **not focused**, the border should be **red**
2 - When the field is invalid and focused, the border should be **blue**

Current behavior-
 When the field is **invalid** and **focused**, two borders are coming, **red and blue**.
 
NOTE -  The above-expected feature works fine for text input and dropdown, But not for the combo box.

### Reproduction/example

https://githubziqwj8-1k1x--5173--dc4d7514.local-credentialless.webcontainer.io

### Steps to reproduce

step1 - Set invalid props true in the combo box
step2 - Focus or click on the combo box to search 
step3 - It will show an error border (red) and active border(blue) together

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
Hey @anoopjaiswal903 , thanks for bringing this issue into light! could you please reproduce in this the [sandboxes](https://github.com/carbon-design-system/sandboxes/blob/main/README.md) here? the link you provided seems to be broken.

**Comment by anoopjaiswal903** [comment]
Hi @Gururajj77 kindly follow the below link
https://stackblitz.com/edit/github-axcnwb?file=src%2FApp.jsx

**Comment by anoopjaiswal903** [comment]
Hi @Gururajj77 In case if link got broke again , kindly follow the below code
import { ComboBox } from '@carbon/react';

**export default function App() {
  return (
    <div>
      <ComboBox items={[1, 2, 3, 4, 5]} invalid={true} />
    </div>
  );
}**


Issue - When fields have an error (invalid ={true}) and if focusing on a field, two input field borders are showing (red and blue) .

**Comment by anoopjaiswal903** [comment]
Hi @riddhybansal,

Thank you for resolving the issue mentioned above.
