### ISSUE TITLE
[Bug]: The `subtitle` prop should be `node` type rather than `string` type

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/carbon#16909]
### Package

@carbon/react

### Package version

v1.53.1

### React version

v17.0.2

### Description

The `subtitle` prop in `InlineNotification` in Carbon 11 is now a `string` type. In Carbon 10, the prop is a `node` type. This creates React warning all over the places when we upgrade from Carbon 10 to 11. Can you change the `subtitle` prop back to a `node` type?

### Reproduction/example

N/A

### Steps to reproduce

Here is an example of my code snippet:

```
                    <InlineNotification
                      kind="error"
                      role="alert"
                      lowContrast
                      hideCloseButton
                      title={t('Failed to fetch')}
                      subtitle={
                        <>
                          {t(
                            'An error occurred when fetching secrets. Try again later.'
                          )}
                          {errorGuid && (
                            <span className="cpc--secret-input__error-guid">{` (${errorGuid})`}</span>
                          )}
                        </>
                      }
                    />
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Closing based on the rationale explained in https://github.com/carbon-design-system/carbon/pull/16911#pullrequestreview-2161008750
