### ISSUE TITLE
[Carbon X] Implicit height on Button can sometimes render as zero height

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#1691]
## Detailed description

Button height for Carbon X version is implicit:
https://github.com/IBM/carbon-components/blob/master/src/components/button/_mixins.scss#L84

This usually doesn't cause issues for most buttons, since they typically have content within.

However, the `ButtonSkeleton` from `carbon-component-react` renders with a zero height due to this implicit `height: auto` setting.  

## Suggested Fix

Adding a pixel value for height resolves in the Carbon X button base mixin resolves this issue.

**Comment by jendowns** [comment]
I'm happy to propose a fix to this; it would be a short PR 😅 

However I've noticed on some of our mockups that buttons are typically 48px. Whereas the current Carbon version has `$button-height` set to 40px.

So do you mind if I set `height: rem(48px);` in the `button--x` mixin, if that's the ultimate intention?

**Comment by asudoh** [comment]
CC @IBM/carbon-designers to see which one would be the correct height. Thanks!

**Comment by aagonzales** [comment]
Carbon X button heights are 48px. But V9 they are 40px.

**Comment by asudoh** [comment]
Thanks @aagonzales for your response!
