### ISSUE TITLE
[Bug]: Blank screen when viewing systems icons on web page

### ISSUE THREAD

**Issue by SmevSmevson** [carbon-design-system/carbon#16919]
### Package

@carbon/icons, @carbon/icons-react

### Browser

Chrome, Firefox

### Package version

@latest

### Description

This issues is on the web page https://carbondesignsystem.com/elements/icons/library/ 
React error #62;

### Reproduction/example

n/a

### Steps to reproduce

Go to https://carbondesignsystem.com/elements/icons/library/
Select "Systems" from the dropdown.
The screen goes black.

https://github.com/carbon-design-system/carbon/assets/13863349/923ca1f6-6405-4482-938a-8bea524f51e4

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alina-jacob** [comment]
Hi there @SmevSmevson, thank you for raising this bug!
We are aware of this issue and are working towards a resolution for it, which is documented [in this PR](https://github.com/carbon-design-system/carbon-website/pull/4158).
Thanks again!
