### ISSUE TITLE
Storybook's long scroll screenshot not working correctly

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#16926]
## Detailed description
I tried capturing a long screenshot using a [Chrome plugin](https://chromewebstore.google.com/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en-GB&utm_source=ext_sidebar) (GoFullPage), but it didn't work as expected. Instead of capturing the main page scroll, it's capturing the left navigation scroll. I'm uncertain about the reason behind this issue, but this plugin has been working fine for the Carbon website.

(The video demonstrates the Chrome plugin on Storybook, while the image shows the screen capture output.)

https://github.com/carbon-design-system/carbon/assets/158570656/ac77d14c-1efe-40c8-9848-5e0eb8f42197

![image](https://github.com/carbon-design-system/carbon/assets/158570656/c6b47498-da9a-476a-a86d-bf4108afa7c9)

**Comment by alisonjoseph** [comment]
I believe this doesn't work because the content in Storybook is within an iframe. I would recommend either viewing the story full screen, or opening the canvas in a new tab to capture the full scrolling content in an image if needed.


<img width="129" alt="Screenshot 2024-07-10 at 11 31 33 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/3e144791-b874-4eb7-a79c-f06f49959bd8">

**Comment by Kritvi-bhatia17** [comment]
> I believe this doesn't work because the content in Storybook is within an iframe. I would recommend either viewing the story full screen, or opening the canvas in a new tab to capture the full scrolling content in an image if needed.
> 
> <img alt="Screenshot 2024-07-10 at 11 31 33 AM" width="129" src="https://private-user-images.githubusercontent.com/2753488/347493343-3e144791-b874-4eb7-a79c-f06f49959bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzI5MjAsIm5iZiI6MTcyMDYzMjYyMCwicGF0aCI6Ii8yNzUzNDg4LzM0NzQ5MzM0My0zZTE0NDc5MS1iODc0LTRlYjctYTc5Yy1mMDZmNDk5NTliZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTczMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ5MjdiMWIzMDg4ODExODEwMjAwYjlkODI4NDhlOWU3OThiOTZkZmZkOWM5ZjViZjcxMTdkZjRiZjllMGQzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SsD-n1lKFmsHPaSU1h_Ah80YwzMAKIveDwEuM71J43I">

Wow, this worked. Thanks Alison!
