### ISSUE TITLE
[Bug]: ComboBox should be auto scrolled to the focused item

### ISSUE THREAD

**Issue by Meenakshi34-lab** [carbon-design-system/carbon#16935]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.61.0

### React version

v18.3.1

### Description

 ComboBox component when are many items, while using keyboard focus reaches the element on press (up/down) keys the focus reaches to that Item but Item is not visible and it scroll to that elements , here is the slack conversation
https://ibm-cio.slack.com/archives/C2K6RFJ1G/p1720449567444139

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/15978
