### ISSUE TITLE
[Bug]: Datepicker range shows both dates in first dat 

### ISSUE THREAD

**Issue by josiahhk** [carbon-design-system/carbon#16960]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.61

### React version

18.3.1

### Description

When using the DatePicker range with calendar and passing in the selected date array as a value, the first datepicker displays "[startDate] to [endDate]" instead of just the startDate

![image](https://github.com/user-attachments/assets/815da7b4-4155-43b4-ac1c-790df2d03e6a)

This is the same issue as: https://github.com/carbon-design-system/carbon/issues/4803
It appears to have started occurring again around version 1.56. 

### Reproduction/example

https://codesandbox.io/s/datepicker-issue-pc8ktz?file=/src/index.js

### Steps to reproduce

1. Use the code from the storybook to set up a date picker range with calendar. 
2. Save the value of the onChange to state and pass that state in as a value (I don't think the value strictly needs to be saved in state. Just as long as you can get two values in an array passed in
3. When the code is running, select a range of dates. It does not matter which dates.
4. Notice that the first of the two date picker boxes in the range displays "[dateOne] to [dateTwo]" instead of just "[dateOne]"

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
This was just fixed and will be included in our release this week. https://github.com/carbon-design-system/carbon/pull/16936
