### ISSUE TITLE
[Bug]: Tabs component doesn't export TabsVertical and TabListVertical

### ISSUE THREAD

**Issue by preetibansalui** [carbon-design-system/carbon#16964]
### Package

@carbon/react

### Package version

1.61.0

### Description

Tabs component doesn't export TabsVertical and TabListVertical

### Reproduction/example

https://stackblitz.com/edit/github-3he5b6?file=src%2FApp.tsx

### Steps to reproduce

<img width="768" alt="image" src="https://github.com/user-attachments/assets/a6706ffd-6d82-42e6-8578-5139e934731d">

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
duplicate https://github.com/carbon-design-system/carbon/pull/16950
