### ISSUE TITLE
[Bug]: SelectableTile: deprecated `value` prop

### ISSUE THREAD

**Issue by shoqcia** [carbon-design-system/carbon#16977]
### Package

@carbon/react

### Package version

1.61.0

### React version

18.0.0

### Description

The value prop is marked as `deprecated` despite being required.

### Reproduction/example

https://stackblitz.com/edit/vitejs-vite-dbavtk?file=src%2FApp.tsx

### Steps to reproduce

1. Use the SelectableTile component with TypeScript,
2. Add value prop
3. Have it marked as deprecated

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by niveamartins** [comment]
Hey, guys! Can I have a look on this issue?

**Comment by wkeese** [comment]
I didn't know about this ticket but I fixed this in #18096.   Please close this.
