### ISSUE TITLE
[Callout] Explore ways of adding this feature into our current system structure

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17024]
## Acceptance criteria
- In this issue, we need to look at our current [Notification component](https://react.carbondesignsystem.com/?path=/docs/components-notifications-actionable--overview) (Actionable, Inline, Toast) and explore ways of how we could currently incorporate the Static Notification feature parameters without making a net new component.
- Note: Alternatively to the approach in this issue, we are exploring an additional option of creating a net new component for this work, which is being explored in this separate issue: https://github.com/carbon-design-system/carbon/issues/16984

**Tasks**
- [x] Explore how we could leverage our current structure of the Notification component and incorporate the needs of StaticNotification.
  - For example:
    - Could we add a new variant to Notification that would solve these needs?
    - Could we adjust one of our current Notification variants to solve these needs?
    - Could it just be an added prop on a current variant?
    - Other ideas?
    
- [x] Playback to Design / Dev / A11y

**Comment by benjamin-kurien** [comment]
[Multiple ways of documenting the component ](https://www.figma.com/design/NizIyBLaWztxQDnsBzOKbY/Callout%2FStaticNotification?node-id=63-36963)within our current system was explored and discussed with the team. For the current scope it was decided to explore the component as a 4th variant within or notification component.
