### ISSUE TITLE
[Bug]: Title attribute for Tag component contains all children

### ISSUE THREAD

**Issue by clouria** [carbon-design-system/carbon#17033]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.62.1

### React version

^17.0.0

### Description

According to the docs, https://react.carbondesignsystem.com/?path=/docs/components-tag--overview, the Tag component can have a children prop of type `node`. When given any type other than string as a child, the Tag component acts incorrectly. It adds all of the children to the Title attribute 
![Screenshot 2024-07-24 at 8 18 22 AM](https://github.com/user-attachments/assets/48646897-49e7-420d-9cf7-c4fd2dffea71)
![Screenshot 2024-07-24 at 8 24 32 AM](https://github.com/user-attachments/assets/39c02897-657b-40bb-9b96-56a46cc6d546)
This was added in this PR https://github.com/carbon-design-system/carbon/commit/96524a7144715cc012c3dd8327279d014d67e1e3#diff-bf61738276a5e024a5901f050aa6781f38a21104524c5fcfdf84c9bd8248e8ef

I believe the code is expecting the children to only be a string and in that case this works properly. A fix for this would be to allow a custom title to be passed down as a prop for these scenarios where the title can not be inferred from the child. 

### Reproduction/example

https://stackblitz.com/edit/github-ynms4h-zd7ufe?file=src%2FApp.jsx

### Steps to reproduce

1. Hover over the Tag and wait for a couple seconds for the Title text to show

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by emyarod** [comment]
the issue seems to be resolved via https://github.com/carbon-design-system/carbon/blob/7f9d9b71a535b6211c578774813f6baf08abfb34/packages/react/src/components/Tag/Tag.tsx#L243-L251 so it is recommended that you upgrade your project's version of Carbon to capture this bugfix!
