### ISSUE TITLE
Notification: deprecate alternative status inline notifications

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17034]
## Acceptance criteria

- [ ] Deprecate the `warning-alt` and `info-square` alternative status inline notification options since they are not being used and it will streamline our notification status options. 
- Refer to the telemetry metrics in [this issue](https://github.com/carbon-design-system/carbon-design-kit/issues/812#issuecomment-2236853495)

**Comment by tay1orjones** [comment]
We can use the `deprecateValuesWithin()` helper for this

**Comment by thyhmdo** [comment]
Close the issue because we'll make them official instead.
