### ISSUE TITLE
Button: Update types to be a conditional proptype (or a union in TS) of `if hasIconOnly, kind !== "danger"`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17036]
`danger` is not a valid `type` of `IconButton` or `<Button hasIconOnly/>`, we need to update the proptypes and TS interfaces to state this.

**Comment by Gururajj77** [comment]
This article could give more insight on this issue:
https://typeofnan.dev/conditional-component-props-react/
