### ISSUE TITLE
[Bug]: Gray tag does not have expected color in dark theme

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#17040]
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest --- actually using @console/pal (was not an option)

### Description

Gray tag does not have expected color in dark theme in code, does not match figma or react [storybook](https://react.carbondesignsystem.com/?path=/story/components-tag--playground&globals=theme:g90). Is problematic because tag becomes invisible.

### Screenshots

Actual vs expected

<img width="1267" alt="Screenshot 2024-07-23 at 4 10 33 PM" src="https://github.com/user-attachments/assets/a5bfa586-e78b-40e7-80a5-3b9a7a0c9299">

### Steps to reproduce

Might need to check in a sandbox as this particular code is not pushed to staging yet

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
Can you reproduce this in a Stackblitz, the gray tag is displaying correctly with the color of Gray 70 for g90 and g100 from what I can see in Storybook.
