### ISSUE TITLE
[Bug]: Multiselect and Filterable multiselect dropdown does not have tooltip

### ISSUE THREAD

**Issue by mariusd-ibm** [carbon-design-system/carbon#17067]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.62.1

### React version

17.0.2

### Description

Multiselect and Filterable multiselect dropdown does not have tooltip, while simple dropdown has.
when one of the dropdown items has long text its not possible to read full text

### Reproduction/example

none

### Steps to reproduce

try hover on lorem ipsum option in [storybook](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--filterable-multiselect) 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by riddhybansal** [comment]
Hey there I was totaly debugging it in the wrong direction. Finally found that Multiselect and filterable Multiselect has a prop called useTitleInItem that is off by default and hence we are not getting the tooltip . You can check in playground by turning it on from controls. 
![Image](https://github.com/user-attachments/assets/ec555471-c282-4ebf-b0d6-283e75b9269e)
