### ISSUE TITLE
Replace `isEqual` with `react-fast-compare`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17061]
In https://github.com/carbon-design-system/carbon/pull/17056 a performance fix was added for DataTable by replacing lodash isEqual with react-fast-compare. This should be done for all other instances in the codebase as it supports both React element comparison and general-purpose deep comparison.

[Usages](https://github.com/search?q=repo%3Acarbon-design-system%2Fcarbon+lodash.isEqual&type=code)

**Comment by riddhybansal** [comment]
Ref https://www.npmjs.com/package/react-fast-compare how react-fast-compare is much much better than lodash
