### ISSUE TITLE
[Callout] Create final design spec

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17083]
## Acceptance criteria

- [x] Create the final design spec
  - Provide interaction behaviors, accessibility considerations, color tokens, and spacing annotations in the spec 
  - Here are some recent examples: [Menu button](https://www.figma.com/design/NquLNYk3Ay4wJZihDksFAy/Menu-and-Combo-Button?node-id=886-8650&t=WvwgVwVzXrJ38GIp-1), [Tabs](https://www.figma.com/design/qGVzyBMsr4nR7clX6rnZOe/Tabs?node-id=5-20993&t=Y66kVsiLx6L5WfVl-1)
  - Here is an [old notification spec](https://ibm.box.com/s/4tpwuvj1feyipqrulz6jqsnzhv8l2fh1) for reference (it's in Sketch but you can import it into Figma to view it.
- [x] Provide an image of the final design spec in this issue
- [x] Determine final name for component
- [x] Review final spec with the team

**Comment by benjamin-kurien** [comment]
Callouts are designed to highlight to critical information on a page. They load with the page's content, and placed contextually for relevance. 

- Status: Info, Warning. (Unlike notifications which are reactive in nature and provided as feedback after a task has been completed, Callout is intended to highlight critical information provided to help with a user journey. It hence does not include success and error statuses, that are present in other notifications)

- Type: Inline long & short variants (As per the current scope)

- Style: Low and high contrast (As per the current scope)

- Optional Props: Heading, Hyperlinks 

- No dismiss button: Unlike notifications, callouts are non-dismissible, ensuring that the highlighted information remains visible to the user.

- No action button: Unlike notifications that are provided at the end of a journey, callouts are intended to helps users focus on their current journey, without distracting them to an alternate journey. 

![Callout - Design spec](https://github.com/user-attachments/assets/c767802b-92be-4d21-ba6c-15ed7d219119)

**Comment by benjamin-kurien** [comment]
This variant behaves differently from other notifications, hence a need to differentiate it by naming was considered. Naming the component as "Callout" was [discussed](https://www.figma.com/design/NizIyBLaWztxQDnsBzOKbY/Callout%2FStaticNotification?node-id=379-1967) and agreed with the team, as this was the commonly used name across other design systems, products and community discussions.
