### ISSUE TITLE
[Bug]: Carbon 11 Pagination component next button is not enabled when using `pagesUnknown` prop

### ISSUE THREAD

**Issue by vishalpurandare** [carbon-design-system/carbon#17091]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

1.63.0

### React version

17

### Description

Between Carbon 10 and Carbon 11 version Pagination component seems to have regressed (behavior is changed), looks like we need to provide prop totalItems all the times even when we are using pagesUnknown , pages would be unknown in case we don’t know the total number of items. The next button is always disabled if we don’t provide totalCount 

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-pagination--overview#unknown-pages-and-items

### Steps to reproduce

Doc has same issue 

https://react.carbondesignsystem.com/?path=/docs/components-pagination--overview#unknown-pages-and-items

- While using Pagination component, provide prop `pagesUnknown`
- When we provide the prop `pagesUnknown` the next button is always disabled
- This has regressed between carbon-components-react previous Carbon 10 varient and new way of Carbon 11, @carbon/react

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This may have been introduced in https://github.com/carbon-design-system/carbon/pull/16876

**Comment by vishalpurandare** [comment]
@Gururajj77  The issue very visible and simple to understand, it is already visible in doc here - https://react.carbondesignsystem.com/?path=/docs/components-pagination--overview#unknown-pages-and-items, if you still need in stackblitz, here https://stackblitz.com/edit/github-xqggol?file=src%2Fmain.jsx,src%2FApp.jsx&preset=node=, its just copy over of same code from doc :)

**Comment by vishalpurandare** [comment]
Is there an ETA for fix on this one? thank you.

**Comment by vishalpurandare** [comment]
Thanks for the fix. Is this published already, if so, with what version?
