### ISSUE TITLE
[Bug]: Pagination: "Items per page" clipped on Firefox

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#17100]
### Package

@carbon/react

### Browser

Firefox

### Package version

1.63.1

### React version

18

### Description

After selecting a three (or more) digit number from the "Items per page" dropdown, the number is clipped and displayed with an ellipsis.

<img width="930" alt="clipped pagination" src="https://github.com/user-attachments/assets/4199fd6d-6d12-4ec1-b811-f10f2e8dad55">

### Reproduction/example

https://stackblitz.com/edit/carbon-pagination?file=src%2FApp.jsx

### Steps to reproduce

1. Make the browser wide enough to see the "Items per page" dropdown.
2. Select "100" from the dropdown.

### Suggested Severity

None

### Application/PAL

IKC

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by riddhybansal** [comment]
Duplicate #17012
