### ISSUE TITLE
[Question]: What is expected behavior of the Button component's tooltip?

### ISSUE THREAD

**Issue by ilyas-sov** [carbon-design-system/carbon#17111]
### Question for Carbon

Hello Carbon Team,
The behavior I will describe was reported as a bug in my project. When we click on the button and it becomes focused and active we don't see the tooltip of this button, but if we click on the button then switch the browser's tab and then switch back we will see the tooltip appears. This works with the last focused button. Was tested it Chrome browser.

`"@carbon/react": "^1.60.3",`

Could you tell me please is it expected behavior or this is a bug?

Sincerely

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by guidari** [comment]
Hey @ilyas-sov is that something that changed after an specific carbon version update? 

Because I'm testing the component here in this [storybook](https://react.carbondesignsystem.com/?path=/story/components-button--icon-button) and seems to be working fine, it is expected that the Tooltip goes away after the user click.

**Comment by ilyas-sov** [comment]
Here is an example

https://github.com/user-attachments/assets/96bc8a73-fbfe-4c05-b6dc-f9cfca6f544c

**Comment by guidari** [comment]
Ohh I see what you mean now!
I don’t think this is a bug because when you come back to the tab you were previously on, the focus returns to the component it was last focused on, so I would label that as expected behavior, and not a bug.

**Comment by ilyas-sov** [comment]
I see, thank you
