### ISSUE TITLE
Research and decide code coverage tooling

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17123]
Research each of the following and prepare a short list of pros/cons. Schedule a meeting to discuss and we'll decide which to implement in https://github.com/carbon-design-system/carbon/issues/17124

- [ ] [Codecov](https://about.codecov.io/)
- [ ] [SonarCloud](https://sonarcloud.io/welcome)
  - [ ] [SonarQube](https://www.sonarsource.com/products/sonarqube/)
- [ ] [Coveralls](https://coveralls.io/)
- [x] ~[Karma](https://karma-runner.github.io/latest/index.html)~

**Comment by tay1orjones** [comment]
@preetibansalui @Gururajj77 @guidari I've removed Karma from the list. The goal here is to decide on tooling for surfacing coverage collection reports provided via the existing toolchain we have - Jest (and hopefully Playwright, too).

**Comment by preetibansalui** [comment]
Please check the detailed report comparing different code coverage tools [here](https://ibm.box.com/s/1dncli1ua5laatwj5riu6v731hx62iz8).
