### ISSUE TITLE
[Bug]: ComboBox组件在使用的时候 无法输入中文

### ISSUE THREAD

**Issue by liuruil** [carbon-design-system/carbon#17129]
### Package

@carbon/react

### Browser

Chrome

### Package version

"@carbon/react": "^1.58.1",

### React version

18

### Description

so error 

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Combobox by default clears any value that does not match an item in the listbox. Setting the `allowCustomValue` prop disables this behavior and allows a new, non-matching value to be entered.


https://github.com/user-attachments/assets/0155d4b0-05f9-43a2-bbf2-209f2fc7efc4

I hope this helps!
