### ISSUE TITLE
Missing .d.ts definitions for TreeView and TreeNode components in @carbon/react@1.63.2 NPM package

### ISSUE THREAD

**Issue by jacobodeharo** [carbon-design-system/carbon#17137]
### Package

@carbon/react

### Package version

@carbon/react@1.63.2

### Description

I recently forked and built the carbon project (`main` branch, v1.63.2) and I could see that `TreeView` and `TreeNode` components are generating correctly the `.d.ts` files under `/lib/`  and `/es/` folders, but for some reason, the published NPM package `@carbon/react@1.63.2` does not include them when I install it as dependency:
- https://unpkg.com/@carbon/react@1.63.2/es/components/TreeView/TreeView.d.ts
- https://unpkg.com/@carbon/react@1.63.2/es/components/TreeView/TreeNode.d.ts

The build is generating them correctly since https://github.com/carbon-design-system/carbon/pull/17038 was merged, so I suspect it has to be something wrong with the packaging or publishing.

<img width="598" alt="Screenshot 2024-08-10 at 18 25 03" src="https://github.com/user-attachments/assets/2e037ae1-189a-403a-9e9a-d356a5c06cb8">

Other components are including the TypeScript definitions (index.d.ts, ComponentX.d.ts, etc.) in the package, for example:
- https://unpkg.com/@carbon/react@1.63.2/es/components/TileGroup/index.d.ts
- https://unpkg.com/@carbon/react@1.63.2/es/components/Text/TextDirection.d.ts

What could be the problem?
Regards.

### Reproduction/example

https://stackblitz.com/edit/react-ts-wgeica

### Steps to reproduce

1) Install `@carbon/react@1.63.2` in your project.
2) Try to import `TreeView` or `TreeNode`.

The module `"@carbon/react"` has no exported member `TreeView`, and same for `TreeNode`.

The build is generating correctly the TypeScript definitions but for some reason they are not included in the published NPM package.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@jacobodeharo Hey sorry for the confusion, https://github.com/carbon-design-system/carbon/pull/17038 was only first published today in `11.64.0-rc.0`. They're there now: https://unpkg.com/browse/@carbon/react@1.64.0-rc.0/es/components/TreeView/TreeView.d.ts

Merged PRs aren't immediately published. They "queue" in `main` for up to two weeks to then be included in our [biweekly minor releases](https://github.com/carbon-design-system/carbon/wiki/Release-radar). Patch releases like `11.63.2` only contain cherry-picked hotfixes from `main`, not the whole current branch. 

I'll close this but please let us know if you're still seeing any issues with these types!
