### ISSUE TITLE
Icon-only button

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#1714]
## Summary
I'd like to propose that icon-only buttons become a use-case of the Button component. This UX pattern is currently used by other components (overflow menu, data table, tooltip) but having it be part of Button will allow for more consistent [re-]use within applications.

Currently I've only seen this used with the ghost and primary variants by our design guidelines for compact UIs but we don't limit which variant could be used.  With Carbon 9 it didn't create an issue but the  Carbon X's extra padding/min-width creates an odd visual style.  

### Examples from Watson Health
By default icon-only buttons are not very accessible for cognitive disabilities, so Watson Health has added a textual description when the button is hovered/focus for users to get more information about what the button does. See demo here: https://pages.github.ibm.com/Watson-Health/components/preview/button--icon-only.html

**Screen shots from our design guidelines**
Different variants
<img width="175" alt="screen shot 2019-01-30 at 1 09 39 pm" src="https://user-images.githubusercontent.com/1275779/52002566-5f0ba500-2490-11e9-8c5c-b63a4b205939.png">
Different sizes
<img width="88" alt="screen shot 2019-01-30 at 1 09 45 pm" src="https://user-images.githubusercontent.com/1275779/52002567-5f0ba500-2490-11e9-8db7-7e5808b81786.png">

### Slack conversation in `carbon-components`

**Liz Judd:** Does Carbon provide Icon only button code?  When I use the Carbon X button styles, it looks odd with the space to the left of the icon

**Josh Black:** AFAIK we don’t provide an icon button

**Liz Judd:** Is that something that’s being considered?  Should I make an issue for it or keep it custom to our setup

**Josh Black:** It’s not on any roadmap for components, I believe. Might be worth bringing up to see if this is a UX pattern that is supported or not

**Liz Judd:** It’s used by overflow menu and the toolbar for data tables which is why I’m surprised that it’s not something that’s available.  I’ll create an issue to start the conversation

**Josh Black:** I think the style for those aren’t coming from the underlying button component though, right? Which is why they might be distinct stylistically

**Liz Judd:** I just mean that it’s a practice that is used by other components so why it wouldn’t be offered stand-alone seems odd so consumers could use them in other locations other than those specific components

**Alessandra Davila** What is your use case for a icon button. I think overflow menu work differently than how a button works

**Liz Judd** Compact UIs

**Liz Judd** We deal a lot with big data and can have very overwhelming layouts so the use of icon-only buttons help clean up the space

**Josh Black** I believe Cloud would have a similar use-case for compactness, right? Particularly around data density.

**Liz Judd** It’s also used by tooltip and data table so it’s not just a one off for overflow menu

**Josh Black** I think we need to distinguish between an icon used in a button semantically and a button icon styled by the primary button styles, right?

**Josh Black** We definitely use the former in widgets :thumbsup: The latter is what I thought we were referring to here but let me know if I’m wrong

**Liz Judd** i don’t know if i understand what you mean by a `icon used in a button` and `button icon`. They should all be in button elements as they perform an action

**Josh Black** An icon used in a button: `<button><svg>...</svg></button>`
A button icon: `<button class="bx--btn">...</button>`
Is all I meant

**Josh Black** Right, but it seemed like you were asking about a button styled like the button components

**Liz Judd** oh yes, we primarily use the ghost button variant. we don’t technically limit our users though and they could use any button variant

**Josh Black** Right, we should sync on if that’s consistent UX behavior then. In cloud I believe that pattern isn’t used which is why this isn’t currently supported, most likely.

**Liz Judd** I’ll create a discussion issue vs feature request

**Comment by joshblack** [comment]
cc @IBM/carbon-designers

**Comment by emyarod** [comment]
I believe this is a duplicate of https://github.com/IBM/carbon-components/issues/1667

**Comment by elizabethsjudd** [comment]
@emyarod I did see that issue but took it as the code was there but there wasn't documentation since it uses the `documentation` label.   I'm looking for the actual implementation of this work so that's my bad since once I actually read further down the thread it mentions it's not implemented.  Maybe update the labels on #1667 to be more clear that it's not just documentation but actual implementation.

FYI, the slack thread has continued on since my initial post: https://ibm-studios.slack.com/archives/C046Y0YUD/p1548870081200400

**Comment by dakahn** [comment]
While the icon-only button is definitely prevalent (especially in native software design) it introduces into any user interface compelling usability challenges. I don't think the design system should formally support this pattern -- _though it is already used in some of our existing components._

There is an enlightening discussion on the User Experience Stack Exchange about precisely [why the icon-only-button design is an accessibility/usability anti-pattern](https://ux.stackexchange.com/a/1803).

Although an icon-only button can be made satisfactorily accessible in implementation even a carefully coded icon-only button that passes testing in isolation can create an accessibility/usability issue for the end user who we can't assume will match some minimalist icon to some abstract concept (like say, _submit this form to our company_).

There doesn't seem to be any reason apart from aesthetics to use symbols in lieu of clear labeling.

**Comment by elizabethsjudd** [comment]
If we follow @dakahn direction, I feel there needs to be issues created in Carbon to prioritize the removal of usage from overflow menus, navigation/headers, tooltips, data tables, etc. It's not fair to Carbon users to say they shouldn't use this [common] use-case and then do it within carbon components. We should be leading by example. I would rather have a more accessible implementation used globally than the current one that's implemented in Carbon components that doesn't add any textual description for sighted users.

**Comment by asudoh** [comment]
As far as I see, icon is used for its intuitiveness and its simplicity. Some design systems prefers icons over text, while some doesn't. OTOH @dakahn has a good point with his reference that icon sometimes cause confusions - I guess more traffic signs in the US are in text than ones in Japan from that reason, which is, multi-cultural nature of the US tends to have multiple perceptions of a single icon.

That said, I see this topic is a designers' choice. That's why input from our designers is important here, as @joshblack solicited for earlier. A response from our designer can be found at: 
https://github.com/IBM/carbon-components/issues/1667#issuecomment-458273025

**Comment by asudoh** [comment]
Closing for the sake of #1667, don't hesitate to speak up if anybody thinks this ticket should be separate - Thanks!
