### ISSUE TITLE
[Feature Request]: Add `autoAlign` to Button for IconButton's tooltip

### ISSUE THREAD

**Issue by kurtwaldowski-b** [carbon-design-system/carbon#17168]
### The problem

In a recent update, autoAlign was added to tooltips, which allows them to take advantage of floating-ui and always render the tooltip on top. This prevents it from being cut off by surrounding elements, and was a great improvement.

However, most of our tooltips are baked into Buttons and Icon Buttons, and this issue is still persistent for them. There is no way to use autoAlign and prevent tooltips inside of Buttons from being cut off.

### The solution

We should align the behavior of the Tooltip component and the baked in tooltip component within buttons and icon buttons.

### Examples

Here is a stack blitz demonstrating the issue and current workaround

https://stackblitz.com/edit/vitejs-vite-nwjb3v?file=src%2FApp.tsx

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by kurtwaldowski-b** [comment]
I am not positive if this should be opened as a bug or a feature request

**Comment by tay1orjones** [comment]
Thanks for opening an issue for this! There's a PR up for adding it to CopyButton, CodeSnippet and IconButton https://github.com/carbon-design-system/carbon/pull/17138

We can refocus this issue towards just adding it to Button.

**Comment by tay1orjones** [comment]
This also could be solved by https://github.com/carbon-design-system/carbon/issues/17003. I'm 50/50 if this should be an explicit prop drilled down to each of these components or if it should be more generally configured with something like what's proposed there. Maybe the best solution is both, I'm not sure. If you have any thoughts on it, please share.

**Comment by tay1orjones** [comment]
Update: I think adding this as an experimental prop on Button for now makes sense
