### ISSUE TITLE
[Bug]: Accordion items do not animate

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17197]
### Package

@carbon/react

### Browser

Chrome

### Package version

11.64.0

### React version

18

### Description

Regression caused by https://github.com/carbon-design-system/carbon/pull/16933, the accordion does not animate when opening and closing items.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-accordion--default

### Steps to reproduce

Go to the story and click to open an item. It does not smoothly transition as it did before in 11.63.0: https://deploy-preview-17079--v11-carbon-react.netlify.app/?path=/story/components-accordion--default

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
Regression actually seems to be caused by this https://github.com/carbon-design-system/carbon/pull/17120 adding `hidden` removes the element before it can animate.
