### ISSUE TITLE
[Bug]: Treeview - opened node do not remain open even when parent is collapsed and then opened again

### ISSUE THREAD

**Issue by rcsatheeshkumar** [carbon-design-system/carbon#17221]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.63.2

### React version

18.2.0

### Description

Have my opened nodes remain open even if their parent is collapsed and then opened again. The nodes should remain in the same open or closed state.

### Reproduction/example

https://stackblitz.com/edit/github-3xhbda-38shez?file=src%2FApp.jsx,package.json

### Steps to reproduce

1. Expand node "A"
2. Then collapse it's parent node "One"
3. Expand node "One" and node "A" would be in collapsed state. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @rcsatheeshkumar 
Can you check the [storybook code](https://github.com/carbon-design-system/carbon/blob/53be4cbcfaa3b8d0d4d7db35159200577f77ebe1/packages/react/src/components/TreeView/Treeview.stories.js#L12-L13) to see if you are missing any configuration. Here in the [storybook Default](https://react.carbondesignsystem.com/?path=/story/components-treeview--default) variant works as expected.

**Comment by p-szalast** [comment]
> Hey @rcsatheeshkumar Can you check the [storybook code](https://github.com/carbon-design-system/carbon/blob/53be4cbcfaa3b8d0d4d7db35159200577f77ebe1/packages/react/src/components/TreeView/Treeview.stories.js#L12-L13) to see if you are missing any configuration. Here in the [storybook Default](https://react.carbondesignsystem.com/?path=/story/components-treeview--default) variant works as expected.

Hey @guidari. In the link that you provided opening parent node also opens previously collapsed sub nodes:

https://github.com/user-attachments/assets/058c02b0-55c6-45a0-aa48-e53686c8e621

**Comment by guidari** [comment]
You are right. 
I'll check with the team to understand what is the expected behavior! I guess they should always collapse if the parent node is collapsed like it happens in the UIShell, but I'll confirm that.

**Comment by jakubkloc** [comment]
Can you estimate when this issue will be resolved?

**Comment by p-szalast** [comment]
Is there any significant progress in this issue?
