### ISSUE TITLE
[Bug]: Odd Cursor Behaviour While Using ComboBox Component

### ISSUE THREAD

**Issue by vishnuIbmPub** [carbon-design-system/carbon#17222]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.63.2

### React version

v18.3.1

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobox--default

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Data Replication

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by bmsq** [comment]
We just discovered the same issue, keen to see the linked pull request merged 👍
