### ISSUE TITLE
Ensure all components have types and an `index.ts`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17233]
This includes CopyButton, MultiSelect, PasswordInput, TileGroup, among others.

if there are any outstanding, make tasklist/issue items in the parent issue https://github.com/carbon-design-system/carbon/issues/16360

**Comment by ariellalgilmore** [comment]
I came up with the following list of components missing types and index.ts files. Not sure if all apply, so wanted to double check before adding to the parent issue

- Checkbox group (missing index.ts)
- Context menu
- Disclosure
- Feature flags
- idPrefix
- inlineCheckbox
- LayoutDirection
- Portal
- ToggleSmall
