### ISSUE TITLE
[Feature Request]: Property for Grid to change the alignment

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon#17245]
### The problem

Currently the grid is centered by default. [Guidelines for product pages](https://carbondesignsystem.com/elements/2x-grid/usage#style-models) require them to be left aligned. In order to comply with the requirement devs need to override the CSS for the grid from `margin-inline: auto;` to `margin-inline: 0;`.

### The solution

Add a property for the grid which will allow to change the alignment in React. `centered="false"` for example.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Do you want it to extend forever or stop at a certain point?
Max-width discussion?
Carbon website is currently doing exactly what he's asking through overrides. We could do this, but it's also one line of CSS to override.

Idea: align=start, align=end.

**Comment by mariuszmickiewicz** [comment]
@sstrubberg 
`fullWidth` is a separate existing property, doesn't have to be touched here I feel.

This indeed can be done with CSS override… but hundreds of products have to do it independetly. I understand this is not the highest priority request, so I leave the final decision to you.

The name of the property I leave for Carbon to define too. `align` looks good to me. `start` for left aligned (or right if grid should also follow rtl rules). The default one should be `center` or `middle` then?

**Comment by sstrubberg** [comment]
@mariuszmickiewicz After talking it over with the dev's we're going to try and get this in this quarter.

**Comment by mariuszmickiewicz** [comment]
Thanks a lot!
