### ISSUE TITLE
[Carbon X] DatePicker inner container clips content when date range selected

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#1724]
## Detailed description

If you select a date range & then reopen either the start or end date picker, the content within is clipped. Here's a screenshot (NOTE: this is a g100 theme with some color overrides, but everything else remains unchanged from Carbon X) --

![screen shot 2019-02-04 at 11 46 30 am](https://user-images.githubusercontent.com/9057921/52226580-feef7700-2872-11e9-8f2a-8ab4204215d2.png)

I think the problem area is this line:
https://github.com/IBM/carbon-components/blob/master/src/components/date-picker/_date-picker.scss#L852
```
.flatpickr-innerContainer,
  .flatpickr-rContainer {
    width: 100%;
    height: rem(336px);
  }
```

When I experimented with setting `height: auto`, it seems to resolve the problem. But I'm not sure if that's an ideal solution. 🤔 

## Steps to reproduce the issue

1. Open Carbon X date picker
2. Use start/end range picker to select a start and end range (try to include the first week of the month in the selected range to better notice the defect)
3. Reopen the end range date picker
4. Note the clipped content

**Comment by asudoh** [comment]
@jendowns Thank you for spotting. Your proposed solution sounds fine to me, great if you can run some tests so the change won't accidentally break other in date picker. Thanks!

**Comment by jendowns** [comment]
We updated to the latest `carbon-components` & we no longer see any clipping. Closing out this issue 🎉
