### ISSUE TITLE
Control on TextInput for clearing the field

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#1729]
### Summary

ComboBox has a nice inline "clear" (the "x") feature that would be beneficial to be replicated in TextInput.

![image](https://user-images.githubusercontent.com/3360588/52296218-6b39ab80-2943-11e9-8c4b-0bf34952689e.png)

### Justification

Watson IoT has design requirements for a table filtering mechanism where ComboBox components are used alongside TextInputs. The mechanism to 'clear' needs to be consistent.

You can see the WIP implementation of this [filtering mechanism in our storybook](https://ibm.github.io/carbon-addons-iot-react/?selectedKind=Table&selectedStory=filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

### Desired UX and success metrics

Any time the user has inputted text into the input, an "x" mark would appear allowing them to clear the input. This would be an optional prop of TextInput, with the callback optional as well.

### "Must have" functionality

listed above

### Specific timeline issues / requests

This month we're building out a modified DataTable for use in Watson IoT in our addons repo.

### Available extra resources

I can submit a PR this week. I'm unsure how this should be propogated through the entire carbon system. Can I just start here in the react components repo?

**Comment by asudoh** [comment]
Hi 👋 @tay1orjones thank you for entering this issue! This kind of UX enhancement requires designers' review and need to be consistent across framework variants.

**Comment by asudoh** [comment]
CC @IBM/carbon-designers

**Comment by aagonzales** [comment]
I'm not sure if this is a normal pattern for TextInputs. We would want some pretty clear guidance around when you'd use it and we you wouldn't. Could you elaborate a little on when it would be beneficial to have it vs not? As the design system we want to make sure we are driving consistency across products.

**Comment by tay1orjones** [comment]
I'd agree with you that this isn't a normal pattern for TextInputs.

Looking at this again I'm realizing our requirement falls more in line with using a `Search` component as it already contains the clear function via the `iconClose` on the right.

We'd still need to remove the eyeglass icon and add a bottom border focused state, like TextInput has. 
Would those be an option to bring into core? 
1. Search eyeglass icon visible by default, with option to hide
2. Search Focus state matches TextInput, 2px blue bottom border/box-shadow

**Comment by dakahn** [comment]
@carbon-design-system/design 👋

**Comment by laurenmrice** [comment]
Hey @tay1orjones ! Thanks for taking the time to make this issue, unfortunately this is not going to be a use-case we will support in our main carbon library but you can feel free to use it for your product if you want to develop it.
