### ISSUE TITLE
[Low contrast content switcher] Final design specs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17329]
## Acceptance criteria

- [x] Create the final design specs for the low contrast content switcher with the updated visuals and color tokens. 
- [x] Add an image of the spec here.

## Deliverables:
- [Spec in issue](https://github.com/carbon-design-system/carbon/issues/17329#issuecomment-2566710362)
- [Spec in Figma](https://www.figma.com/design/3h9TcywkocMGZpEsvGYTzQ/Content-Switcher?node-id=1853-53433&t=JZGOENhKf81Hbszr-1)

**Comment by aagonzales** [comment]
# Low contrast content switcher

### New component level color tokens 
Question for dev: Can we nest layer token inside of a component level token?

<img width="925" alt="Image" src="https://github.com/user-attachments/assets/765d32ae-9d85-4cf3-b306-91b02dbabca7" />


### Spec

![Image](https://github.com/user-attachments/assets/5264b719-1bef-4c34-92d8-3dd3140c333f)
![Image](https://github.com/user-attachments/assets/f049a226-5441-45de-8dbd-83fa92a60196)

**Comment by kiran-ravindra-ibm** [comment]
Updates being made in [this Figma branch](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/branch/aj2AEofucmDdeX9wqQPi0c/(v11)-Carbon-Design-System?m=auto&node-id=68-3091&t=0z1RTRkJm8b1KXET-1). 

- Corner radius modified on all variants incl. as-is/Default (high contrast)
- Selected, unselected, focus, disabled states created for Subtle
- A blend mode issue that was causing darkened unselected states has been resolved
- After discussion with @aagonzales, @laurenmrice, we are proceeding with rounded focus states for now

Hover states are still in discussion. Need to determine what new color tokens need to be added, if any. Subtle switcher with as-is (Default/high contrast) hover values shown below: 
![Image](https://github.com/user-attachments/assets/efbde9d5-872f-4f83-b09b-a53a7aabdbe4)

Added to schedule for discussion tomorrow 1/28 at design crit
