### ISSUE TITLE
Clean up the issues relating to v10, update the issue templates no longer include these packages

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#17374]
- Craft a reliable filter to gather v10-related issues
- Write a boilerplate comment: why it's being closed, open a new issue if still relevant and reference previous issue, etc.
- Use GH cli to add comment to all applicable issues
- Lock the issue threads?

**Comment by tay1orjones** [comment]
All issues with https://github.com/carbon-design-system/carbon/labels/version%3A%2010 ([link](https://github.com/carbon-design-system/carbon/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22version%3A%2010%22%20label%3A%22type%3A%20bug%20%F0%9F%90%9B%22![Image](https://github.com/user-attachments/assets/fa91dd4c-9400-4fb8-8de0-c94e015bab4d)
)) have been closed with a canned comment.
