### ISSUE TITLE
[a11y]: Treeview overview on documentation does not load properly, shows error

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/carbon#17379]
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

1.65.0

### React version

N/A

### Automated testing tool and ruleset

N/A

### Description

![Screenshot 2024-09-06 at 1 49 26 PM](https://github.com/user-attachments/assets/ee3699f1-8575-4601-b805-446f29024ee0)

### Reproduction/example

N/A

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/docs/components-treeview--overview

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alina-jacob** [comment]
Closing this as a duplicate issue: https://github.com/carbon-design-system/carbon/issues/17356 exists.
