### ISSUE TITLE
[Carbon X] Component token colors are hardcoded

### ISSUE THREAD

**Issue by j1mie** [carbon-design-system/carbon#1738]
## Detailed description

Component token / variable values in in [src/globals/scss/_theme-tokens.scss](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_theme-tokens.scss#L134) use some hardcoded values for colors, and do not make use of the values in `theme-white`, `theme-g100` etc.

Example:
```scss
  // Link
  $link-visited: $ibm-colors__purple-60 !default !global;
  $link-inverse-color: #6ea6ff !default !global;

  // Tooltip
  $tooltip-background-color: #3d3d3d !default !global;
```

**Comment by asudoh** [comment]
@IBM/carbon-designers:

* Is there a global theme token for `$link-inverse-color`?
* Can `$inverse-02` be used for `$tooltip-background-color`?

Thanks!

**Comment by aagonzales** [comment]
These should be calling ibm color palette tokens, like what the $link-visited is doing.

**Comment by joshblack** [comment]
This should be resolved! Going to close this, feel free to comment and we can re-open if I missed something :eyes:
