### ISSUE TITLE
Tab should allow styling tab content

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#1739]
### Summary

Both `Tabs` and `Tab` accept `className` to style the navigation part of the component. But when it comes to styling the tab content area, the only way is to style elements within the content area, not on the content area.

Clarify if you are asking for both design and development, or just design, or just development.
**just Development**

### Justification

unless there is specific reason not to allow changing the styles of `.tab-content` element, we should allow consumer/application to specify what they want.

one use case is scrolling only on the content area by using `flex`. we should be able to just add `overflow-y: auto` to the content div.
![image](https://user-images.githubusercontent.com/10108576/52424329-c72d3d00-2ac7-11e9-9d5a-b6124010d8fc.png)

### "Must have" functionality

allow adding css class to the content area `div`

**Comment by nelsonchen90** [comment]
@lovemecomputer FYI

**Comment by asudoh** [comment]
HI @nelsonchen90 our vanilla/React tabs/tab components themselves doesn't define any markup for tab panels. It's app up to application. Please see https://github.com/IBM/carbon-components/blob/v9.62.0/src/components/tabs/tabs.hbs#L20-L27 and https://github.com/IBM/carbon-components-react/blob/v6.74.0/src/components/Tabs/Tabs-story.js#L44 for more details. Thanks!
