### ISSUE TITLE
[Feature Request]: Modal - Disable close button

### ISSUE THREAD

**Issue by rahulrkr08** [carbon-design-system/carbon#17410]
### The problem

Allow users to disable/hide the close button on the modal. This will be useful when the modal's open status is managed by the state, like when the users cannot close or skip the modal without completing the functions (validations, forms, etc.) within it.

### The solution

new prop `disableClose`

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
We'd be curious to see your user flow regarding this enhancement. I feel like this would raise serious accessibility concerns if we removed the ability to close for users. Happy to re-open when you can supply this additional context. @mbgower
