### ISSUE TITLE
[Bug]: Data table border-subtle is off by a layer

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#17454]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.66.0

### Description

The layer structure for the border-subtles in data table is off by one. It should start at `$border-subtle-01` instead of `$border-subtle-02` Similar problem to what was fixed in https://github.com/carbon-design-system/carbon/pull/13879.

<img width="1544" alt="image" src="https://github.com/user-attachments/assets/411c8c92-50af-4754-9a16-c943384aba44">

### Reproduction/example

n/a

### Steps to reproduce

Open up the data table example in storybook and switch to the Gray 10 theme. The border color that appears on the white table is too dark.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Core but Cloud brought this to my attention 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ziyadzulfikar** [comment]
Hi @alina-jacob,

If this issue is still open, I’d like to work on it. Could you please assign it to me. Thanks!

**Comment by ziyadzulfikar** [comment]
@alina-jacob @guidari Could you please have a look on the PR that I have raised?

**Comment by ziyadzulfikar** [comment]
@alina-jacob @guidari The fix has already been implemented in the above PR. Could someone please review it?
