### ISSUE TITLE
Increase `Dropdown` unit test coverage

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17477]

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : I would like to work on this issue. Can you please assign this to me. . Thanks

**Comment by Shankar-CodeJunkie** [comment]
When I run the test now, I see the below output..  I will try to make the 75 % to 100 % and add test for missing lines 


```
react/src/components/Dropdown                        |   77.27 |    70.42 |   70.58 |   77.27 |                                                                   
  Dropdown.Skeleton.tsx                               |     100 |      100 |     100 |     100 |                                                                   
  Dropdown.tsx                                        |    75.9 |       70 |   68.75 |    75.9 | 62,72,292,307-315,464-498                                 
```

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : I have now improvised / increased the test coverage to 87.5 % .    This is the yarn test output now 


--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   88.09 |    77.14 |    87.5 |   88.09 |                   
 Dropdown.tsx |   88.09 |    77.14 |    87.5 |   88.09 | 477-499          


It looks, those 2 are probably uncovered

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : I  have now improvised / increased the test coverage to 97.59 % . This is the yarn test output now

--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   97.59 |    82.85 |   93.75 |   97.59 |                   
 Dropdown.tsx |   97.59 |    82.85 |   93.75 |   97.59 | 489,493           
--------------|---------|----------|---------|---------|-------------------
