### ISSUE TITLE
Increase `ListBox/next/ListBoxSelection` unit test coverage

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17471]

**Comment by divya-281** [comment]
@tay1orjones I would like to work on this issue

**Comment by emil-ep** [comment]
@alisonjoseph , I'd like to work on this issue. Please assign it to me . Thanks!

**Comment by ariellalgilmore** [comment]
closing this already covered:
![Image](https://github.com/user-attachments/assets/50c8d948-1aa3-44fb-b385-29bd7b5bf567)
