### ISSUE TITLE
Buttons on Number Input shouldn't submit forms

### ISSUE THREAD

**Issue by StephenHogsten** [carbon-design-system/carbon#1747]
## Detailed description
When putting a Number Input within a form, clicking on either of the arrow buttons appears to bubble an event that submits the form.  This seems almost identical to [Carbon Component React #358](https://github.com/IBM/carbon-components-react/issues/358) except that this is not specific to react.  

> Describe in detail the issue you're having.
View [this codepen](https://codepen.io/anon/pen/WPdZZN).  This is forked from the Carbon Component example of Number Input except wrapped in a form element.  Observe that clicking any of the arrows immediately submits the form.

> Is this issue related to a specific component?
Number Input

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/myl42mq94y

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Unlike our React code, the markups in this repo is merely examples, and app can change the markup to meet their needs. PR to change the example markup is nice, too.
