### ISSUE TITLE
Search component close icon incorrect class name 

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#1750]
Relevant: https://github.com/IBM/carbon-components/issues/1616

Website has incorrect close icon. Has magnifying glass instead

**Comment by asudoh** [comment]
Hi @aledavila are you looking at https://next.carbondesignsystem.com/components/search/code or anywhere else...? Thanks!

**Comment by aledavila** [comment]
@asudoh Yes sorry not the class name in components. I was seeing an older version only the website. I should move this issue.

**Comment by asudoh** [comment]
Thank you for clarifying @aledavila! Seems the same one as #1740.
