### ISSUE TITLE
[Empty States] Synthesize + Meet the work group 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17554]
## Acceptance criteria

- [x]  **Audit Empty states in both Product and Carbon core**
Familiarize yourself with the current structure of the Product empty state content that lives in the website documentation, code, and figma kit. The links are provided below of where we have empty states in the Core and Product part of the system. This will be good knowledge to have before meeting with the empty state work group in the follow-on issue to this to see how they are making changes to the current product documentation.

**Website docs**
[Product docs](https://pages.github.ibm.com/cdai-design/pal/patterns/empty-state/usage)
[Core docs](https://carbondesignsystem.com/patterns/empty-states-pattern/)

**Code**
[Product code (Stable)](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-empty-state-emptystate--docs)
[Product code (Experimental)](https://carbon-for-ibm-products.netlify.app/?path=/docs/experimental-patterns-empty-state-emptystatev2--docs)

**Figma kit**
[Product kit](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11-Beta)-IBM-Products-%E2%80%93-Carbon-Design-System?node-id=203-1321&t=HIOxM7B4R7k1Yc5U-1)

-----

- [x] **Meet with the “Empty states workgroup”** 
To understand what the to-be is of the current PAL docs. 
- Contact: Diana Sanborn, Marion Hekeler, Ashley Bock, and Sam Ting
  - We need a high-level list of what they are proposing and changing with the v2. 
  - How complete is this workstream? What else needs to be done to get it across the finish line?
  - Need to clarify with the workgroup that we want this to eventually live on Carbon Core.
  - Document what came out of the meeting from the workgroup and create next steps.

**Comment by thyhmdo** [comment]
- Understand / Audit the Empty state 
- Meet up with the group 
-  Playback with the team your findings 
- Define the Empty state as the component or pattern

**Comment by laurenmrice** [comment]
### Next steps
- The Empty States Workgroup says they are in a good place to hand off the work to Carbon so we can bring it to the finish line. They also think that the Carbon Design System website if the appropriate place to keep this documentation.

**Consolidation**
- Diana, Marianne, Ashley, and Sam will be organizing all of their files and research to provide a more consolidated view of what has been finalized and what yet still needs to be finished. I am joining their Empty States workgroup next week to go over what has been consolidated and the files and work will be handed off to our team. 

**Definition**
- Next we need to define if an Empty State is a Pattern or a Component. This will help inform what we do with the code and the website documentation, and Figma asset.

**Illustration style (TBD)**
- There was talk about revising the current illustration style and coming up with new guidelines. I am proposing we should do this, but as a Phase 2. Phase 1 needs to be updating and consolidating all of the PAL and Core guidance and hosting it on our site.

**Code**
Where will code be hosted? Will things break for teams if we move it to Core? What is this process going to look like? We need to speak to some devs to investigate this.

**Comment by Kritvi-bhatia17** [comment]
> The Empty States Workgroup says they are in a good place to hand off the work to Carbon so we can bring it to the finish line. They also think that the Carbon Design System website if the appropriate place to keep this documentation.

Additionally, just FYI, the [Sustainability Software Design website](https://pages.github.ibm.com/ai-applications/design/components/empty-states/usage) mentions: "The Empty States component will be consolidated with the Carbon Design System Empty States pattern and will no longer be separately maintained by the Sustainability PAL." (image below). Therefore, it seems logical to host this documentation on the Carbon Design System website.

![Image](https://github.com/user-attachments/assets/4f41b932-a750-44a3-ae21-c3c7bc1a9b43)

**Comment by laurenmrice** [comment]
Yep, Diana Sanborn is part of the workgroup initiative to revise and consolidate the Empty States content and she came specifically from Sustainability.
