### ISSUE TITLE
Tabs focus outline color for g90 and g100 is incorrect

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#1757]
## Detailed description

We are in the process of verifying Carbon X components against our dark UI (using g100 theme, specifically) and with the `Tabs` component our designers flagged some colors that needed attention.

### Here are some screenshots with the `Tabs` in a g100 theme (though g90 would be similar):

<img width="786" alt="screen shot 2019-02-08 at 10 38 46 am" src="https://user-images.githubusercontent.com/9057921/52492205-5ac94100-2b8e-11e9-9595-654069ddcc1f.png">
<img width="792" alt="screen shot 2019-02-08 at 10 38 37 am" src="https://user-images.githubusercontent.com/9057921/52492206-5ac94100-2b8e-11e9-8687-98419d81c5e1.png">
<img width="508" alt="screen shot 2019-02-08 at 10 39 19 am" src="https://user-images.githubusercontent.com/9057921/52492204-5ac94100-2b8e-11e9-9171-bde80f87a862.png">

### And here's a table showing which colors were flagged (note: these are for g100 but g90 would be similar):

| Desc |  Current color in g100  | Expected color in g100 |
| ------------ | ------------ | ------------ |
| Highlighted blue line for active | blue60 (`$interactive01`) | blue50 |
| Focus outline | blue60 (`$interactive01`) | blue50 |
| Non active underline | blue60 (`$interactive01`) | blue50 |
| Tab item text | gray30 (`$text02`) | gray10 |

So do these expected colors make sense to you all? (cc @IBM/carbon-designers)? And if so, what should the tokens be changed to to look better for g100 (and likely g90) themes? Looking at the `@carbon/themes` preview, nothing immediately stands out to me https://carbon-elements.netlify.com/themes/examples/preview/  Thank you!

**Comment by aagonzales** [comment]
Off the top of my head, I think the $focus in the darker themes is supposed to be `$white` and use the token `$focus`. I'll have to deep dive on the other bits.

**Comment by aagonzales** [comment]
## Tabs in G100
This is what tabs should look like in the G100 theme:

![image](https://user-images.githubusercontent.com/11670886/52732650-58982580-2f86-11e9-8b55-0444ba9bfc65.png)


Property | V10 token | G100 Theme 
-- | -- | -- 
text -- selected | `$text-01` | G10 `#f3f3f3`
text -- unselected | `$text-02` | G30 `#BEBEBE`
underline -- unselected | `$ui-02` | G80 `#3D3D3D`
underline -- selected | `$interactive-01` | Blue 60 `#0062ff`
hover -- text | `$text-01` | G10 `#f3f3f3`
hover -- underline | `$ui-04` | G60 `#6F6F6F`
focus | `$focus` | White `#ffffff`
disabled -- text | `$disabled-02` | G80 `#3D3D3D`
disabled -- underline | `$disabled-01` | G60 `#6F6F6F`

**Comment by aagonzales** [comment]
At the moment we have `$interactive-01` as `Blue 60` in both dark themes. I think we'll need to talk to Mike and Sadek about changing it to `Blue 50`

**Comment by shixiedesign** [comment]
So Mike and Sadek didn't want to change Blue 60 to Blue 50. So we are adding two new tokens:

`$interactive-04`

White | G10 | G90 | G100
--- | --- | --- | --- 
Blue 60 | Blue 60 | Blue 50 | Blue 50

`$link-01`

White | G10 | G90 | G100
--- | --- | --- | --- 
Blue 60 | Blue 60 | Blue 40 | Blue 40

Tabs highlight bar should now use `$interactive-04` to be accessible in all themes.

**Comment by joshblack** [comment]
Tracking in: https://github.com/IBM/carbon-elements/issues/366 should I PR the update or do one of you want to take it on @shixiedesign @aagonzales?

**Comment by shixiedesign** [comment]
I can add it 👍 @joshblack

**Comment by aagonzales** [comment]
@jeanservaas make update with component audit.

**Comment by jendowns** [comment]
Reopening because it looks like in `v10.3.1` the focus color does not match what is posted in this screenshot: https://github.com/carbon-design-system/carbon/issues/1757#issuecomment-468451264 (focus color should be white, but appears as blue60)
