### ISSUE TITLE
[Bug]: CodeSnippet suggests align value that isn't available yet

### ISSUE THREAD

**Issue by ev-codes** [carbon-design-system/carbon#17585]
### The problem

I currently use the component `<CodeSnippet>` with `align` property "bottom-right".

However, during test runs, `<CodeSnippet>` logs a console warning to use `align` property "bottom-end" instead. However, `<CodeSnippet>` does not currently support this align property.

Unnecessary/unaddressable warnings make it harder to see fixable errors and slow down CI workflows.

### The solution

Either:
- Support the "bottom-end" property in `<CodeSnippet>`
- Do not log the warning until `<CodeSnippet>` supports "bottom-end"

### Examples

Code sample:
```
<CodeSnippet
        wrapText
        align="bottom-right"
        type="multi"
        onClick={() => {
          copyDetail(value);
        }}
      >
        {value}
      </CodeSnippet>
```

Logs from test running this code:
```
console.warn
    Warning: "bottom-right" is a deprecated value for the "align" prop on the "Popover" component. Use "bottom-end" instead. "bottom-right" will be removed in the next major release.

```
      

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Can we get a repo using stackblitz?

**Comment by ev-codes** [comment]
Thanks for your responses! And I'm glad to see this works in the stackblitz.

[In the `CodeSnippetProps`](https://github.com/carbon-design-system/carbon/blob/4a7d9356b37b8bb53e19abc9316885e56ffc61fd/packages/react/src/components/CodeSnippet/CodeSnippet.tsx#L37), I don't see `bottom-end` as an option for the `align` property.

Since `CodeSnippet` supports `bottom-end`, may you please update the interface to reflect this? Or perhaps I'm missing something 🤔 

Thank you 😄

**Comment by sstrubberg** [comment]
Add `bottom-end` to the `align` prop, as suggested.

**Comment by tay1orjones** [comment]
We'll need to make sure all the options for `align` are updated to the new values. This is really similar to what we had to do for DefinitionTooltip https://github.com/carbon-design-system/carbon/issues/16810

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : Can you assign this issue to me ?  Thank you

**Comment by Shankar-CodeJunkie** [comment]
@tay1orjones : I've updated the `packages/react/src/components/CodeSnippet/CodeSnippet.tsx` align props with the new values. However the yarn build command asked me to update the similar changes in the below files as well. The CodeSnippet inturn uses the Copy and CopyButton components, where I need to replicate the similar changes. 

```
        modified:   packages/react/src/components/CodeSnippet/CodeSnippet.tsx
	modified:   packages/react/src/components/ComboButton/index.tsx
	modified:   packages/react/src/components/Copy/Copy.tsx
	modified:   packages/react/src/components/CopyButton/CopyButton.tsx
	modified:   packages/react/src/components/IconButton/index.tsx
	modified:   packages/react/src/components/OverflowMenu/next/index.tsx
	modified:   packages/react/src/components/Pagination/Pagination.tsx
```
