### ISSUE TITLE
[Bug]: Storybook for carbon-design react is broken (https://react.carbondesignsystem.com)

### ISSUE THREAD

**Issue by jmar1998** [carbon-design-system/carbon#17596]
### Package

@carbon/react

### Browser

Chrome

### Package version

any

### React version

any

### Description

The site of the story book is down
https://react.carbondesignsystem.com
![image](https://github.com/user-attachments/assets/35031909-b5dc-4ea2-8c28-fc5c775d2647)

### Reproduction/example

https://react.carbondesignsystem.com

### Steps to reproduce

https://react.carbondesignsystem.com

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
This issue has been fixed and [storybook](https://react.carbondesignsystem.com/?path=/docs/getting-started-welcome--welcome) is up.
