### ISSUE TITLE
Number Input: arrows position for default input is off

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#1760]
Related: https://github.com/carbon-design-system/carbon-website/issues/1006

<img width="1346" alt="screen shot 2019-02-08 at 1 06 55 pm" src="https://user-images.githubusercontent.com/12533409/52500185-011f4180-2ba3-11e9-9dc3-19a3996c09e3.png">

**Comment by emyarod** [comment]
is the website's version of `carbon-components` up to date? this should have been resolved in https://github.com/IBM/carbon-components/pull/1622 if I'm not mistaken

**Comment by aledavila** [comment]
This is for the component itself. I pulled down from master and it was what I was seeing
