### ISSUE TITLE
[Bug]: Dynamically added rows to DataTable don't get checked by the header's 'check all' checkbox

### ISSUE THREAD

**Issue by dave-wood** [carbon-design-system/carbon#17660]
### Package

@carbon/web-components

### Browser

Firefox

### Package version

v2.10.0

### Description

If you dynamically add a new row to an existing DataTable, and then use the 'check all' checkbox in the header, any new rows are not selected, only the existing rows have the checkbox checked.
You can see this in the example given in the Storybook for DataTable--Dynamic--Default: https://web-components.carbondesignsystem.com/?path=/story/components-datatable-dynamic--default
Looks like the tableRows never gets updated when adding a new row

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-datatable-dynamic--default

### Steps to reproduce

Using the Storybook example, click the gear icon top right of the table, select Add Row. Then click on the checkbox in the table's header to the left of the first column heading. All rows will then be checked apart from the new row just added.
https://web-components.carbondesignsystem.com/?path=/story/components-datatable-dynamic--default

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ariellalgilmore** [comment]
closing this with PR: https://github.com/carbon-design-system/carbon/pull/17895
