### ISSUE TITLE
[Bug] [DatePicker]: Firefox- focus fails to move to the next element after selecting a date range in the DatePicker range variant

### ISSUE THREAD

**Issue by 2nikhiltom** [carbon-design-system/carbon#17663]
### Package

@carbon/react

### Browser

Firefox

### Package version

v11.67.0

### React version

v18

### Description

after selecting a date range using the DatePicker (range variant), the focus remains on the DatePicker instead of moving to the next focusable element. This issue is specific to Firefox

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

Select the dates using keyboard and on press of tab key focus not going to the next element. (Issue in firefox)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
I tested in the previous version of Firefox 129.0.2 and in the lastest (131.0.3) and the issue still happens on both version. Probably it is something we can fix in the code.
