### ISSUE TITLE
Floating UI not working as expected for popovers

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/carbon#17670]
When we try to use floating UI for popover in Datagrid or Tagset , popover is being wrongly positioned.
We have passed `autoAlign={true}` to the `<Popover`

![Image](https://github.com/user-attachments/assets/a8981d56-0a28-4210-b935-59a66805c68f)

![Image](https://github.com/user-attachments/assets/6bfc7ebe-4f5f-4dc8-9d37-b988d86119f9)

**Comment by preetibansalui** [comment]
Hey @amal-k-joy , I believe the issue is similar to #17450 and it's fixed. It will be available in next release.
