### ISSUE TITLE
[Bug]: Sortable data table with the size prop set to "sm", header row doesn't respect the "sm" size

### ISSUE THREAD

**Issue by rsimpso1** [carbon-design-system/carbon#17680]
### Package

@carbon/web-components

### Browser

Chrome

### Package version

2.13.1

### Description

I'm trying to use a sortable data table with the size prop set to "sm". However, it seems using sortable causes the header row to stay larger than other table rows. Current behavior I'm seeing on v 2.13.1
![Image](https://github.com/user-attachments/assets/8abad9d7-5180-451f-8f6f-35fdb0cc5b53)

### Reproduction/example

https://stackblitz.com/edit/github-kbd9xw-8msd1g?file=index.html

### Steps to reproduce

1) Open the link
2) View the code in index.html
3) View the output that has a taller header row than the rest of the rows.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

watsonx Assistant

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Zoe-Gathercole** [comment]
Hi, I'd like to work on this issue after chatting to @ariellalgilmore and @kennylam last week. Please could this issue be assigned to me and please could you also add the "hacktoberfest" label 😄
