### ISSUE TITLE
Sync code connect with Figma update

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon#17682]
The following components have been updated on Figma kit, and needs to be synced with code connect.

- [x] 1. [Code Snippet](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?m=auto&node-id=1880-4089&t=BcFzxIp0ZHMVELkH-1): Disabled states added
- [x] 2. [Date-picker](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?m=auto&node-id=17544-266981&t=BcFzxIp0ZHMVELkH-1): Warning and error states added, Boolean property added for label
- [x] 3. [Search](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?m=auto&node-id=1880-6213&t=BcFzxIp0ZHMVELkH-1): Skeleton state added for fluid style

**Comment by alisonjoseph** [comment]
Date picker updates blocked by https://github.com/carbon-design-system/carbon-design-kit/issues/875
