### ISSUE TITLE
Rename `slug` classes to `ai-label`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17714]
When Slug was renamed to AILabel(https://github.com/carbon-design-system/carbon/pull/16803), the props and classnames were not included in the rename. This issue is to fix that.

This rename needs to be backwards compatible. The approach we could take could be:

- [ ] Add new duplicate classname selectors to the `ailabel.scss` styles
  ```diff
  - .#{$prefix}--slug .#{$prefix}--slug__button {
  
  + .#{$prefix}--slug .#{$prefix}--slug__button,
  + .#{$prefix}--ai-label .#{$prefix}--ai-label__button { 
  ```
- [ ] Update classnames within AILabel components to use the new `#{$prefix}--ai-label` names
- [ ] Create a new sub-issue/tasklist item on https://github.com/carbon-design-system/carbon/issues/15803 for removing these classes as part of v12

> [!NOTE]
> **On casing:** for situations like react where we have to use PascalCase we decided on `AILabel`
> 
> For non-pascalcase situations like classnames I think the codebase convention would be "sausage-case" (or whatever you like to call it :upside_down_face: ): `ai-label`

**Comment by ariellalgilmore** [comment]
we decided on using `decorator` as a general term

**Comment by alisonjoseph** [comment]
Related issue: https://github.com/carbon-design-system/carbon/issues/17303#issuecomment-2444485469

We also want to update the styles so that the AI styles only apply when the child of decorator is the AILabel component.
