### ISSUE TITLE
[Feature Request]: Drop per-method lodash dependencies

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#17731]
### The problem

You are using several [single-method lodash package dependencies](https://github.com/search?q=repo%3Acarbon-design-system%2Fcarbon+lodash.&type=code) in your codebase, which is [discouraged even by the authors](https://lodash.com/per-method-packages).

The reason I came up to this is that we have an app where size is a pretty big issue and inspection of the built artifact shows duplication of lodash code... (where the per-method ones are also needlessly big).

![Image](https://github.com/user-attachments/assets/ef16082d-5055-43dd-a637-2d2a06d25839)

### The solution

- drop all dependencies [where native ECMAScript methods exist](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore)
- consider if other methods could be much simplified by using a simplified and project-shared utility that only uses the aforementioned ES6 methods
- replace the rest with a tree-shake-able import from (`lodash-es`)[https://www.npmjs.com/package/lodash-es]… ideally with a very permissive range on `lodash` version to make it more likely that it will get deduplicated.

They also have some kind of code mod in the linked docs page, but I have not used it, so I cannot vouch for it.

### Business priority

High Priority = pressing release

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@kubijo Thanks for bringing this up! I agree with all points, though I think we could first migrate existing usages to use lodash-es really easily and then later work on refactoring those to native methods. 

I don't think the codemod is what we want because it refactors to the main lodash package:

```diff
- import get from 'lodash.get'
+ import get from "lodash/get"

- import mapValues from 'lodash.mapvalues'
+ import mapValues from "lodash/mapValues"

- require('lodash.get')
+ require("lodash/get")

- const sortBy = require('lodash.sortby')
+ const sortBy = require("lodash/sortBy")
```

Whereas we'll instead be aiming for 

```diff
- import get from 'lodash.get'
+ import { get } from "lodash-es"
```

**Comment by kubijo** [comment]
@tay1orjones I see ... yeah, that does not look great ... the only utility I see would be that it primes your code with changes you would then rewrite, but a pretty simple regex-based search&replace does that too...

**Comment by kubijo** [comment]
I've also bumped into this thing: https://es-toolkit.slash.page/ through https://storybook.js.org/blog/storybook-8-4/#we-cut-bundle-size-in-half

I did not hear about it previously, but it seems pretty cool if all they say is true...
