### ISSUE TITLE
[Carbon X] OverflowMenu colors are inaccessible for g90 and g100 themes

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#1773]
## Detailed description

@IBM/carbon-designers Hey there, it looks like the `OverflowMenu` is very dark for g90 and g100 themes, which makes it hard to see/interact with. 

Here are some screenshots from my environment. **I had to make the container background hotpink so you could see the component in these screenshots; otherwise, it would be almost invisible**. In reality, our UI background is gray80-gray100ish, depending on the situation.

![screen shot 2019-02-11 at 1 29 11 pm](https://user-images.githubusercontent.com/9057921/52588219-9ddf1a80-2e01-11e9-8bab-cf8a55acf439.png)
![screen shot 2019-02-11 at 1 29 05 pm](https://user-images.githubusercontent.com/9057921/52588220-9ddf1a80-2e01-11e9-9645-b2a0e2f94161.png)
![screen shot 2019-02-11 at 1 28 59 pm](https://user-images.githubusercontent.com/9057921/52588223-9ddf1a80-2e01-11e9-8bc6-c6929d3c50dc.png)

I noticed that the color token for [the background of the menu is `$inverse-01`](https://github.com/IBM/carbon-components/blob/master/src/components/overflow-menu/_overflow-menu.scss#L234), which is almost white for light UIs and then very dark for dark UIs. An alternative here could be `$inverse-02`? 🤔 https://carbon-elements.netlify.com/themes/examples/preview/

Anyway, just let me know what you'd prefer to see here & I'm happy to propose a change. Thanks!

**Comment by aagonzales** [comment]
## G100 theme
You are right its super subtle, just one step down in the darker colors isn't as contrast-y as the lighter ones. We're going to have to evaluate those assigned values in the dark theme from a higher level. Below are listed the correct tokens for the overflow menu though.

Currently we're saying `$ui-01: G90` in G100 theme (examples on the right of image below). G80 is better but we'll have to see how it plays out in other components that use `$ui-01` like tile backgrounds

![image](https://user-images.githubusercontent.com/11670886/52738186-b1ba8600-2f93-11e9-8b03-561a38dd5d7f.png)

Property | V10
-- | --
Icon -- fill | `$icon-01`
icon:hover -- background | `$hover-ui`
icon:hover -- fill | --
icon:focus -- border | `$focus`
menu:open -- item text | `$text-02`
menu:open -- border-top | `$ui-03`
menu:open -- background | `$ui-01`
item:hover -- text | `$text-01`
item:hover -- background | `$hover-ui`
item:focus -- focus | `$focus`
item:active -- background | `$active-ui`
item:disabled -- text-disabled | `$disabled-02`

**Comment by aagonzales** [comment]
Other components that use `$ui-01` 
- background-color (content switcher)
- background (Tags)
- menu:open -- background (overflow menu) 
- background ( File uploader)
- background (Tile)
- enabled -- bg (Code snippet)
- calendar -- bg (Date picker)
- open items background (Dropdown)
- background -- container (Modal)

**Comment by jendowns** [comment]
Quick update: I can propose a fix to apply most of the tokens you suggested above @aagonzales, as a quick fix until this is explored more, but it looks like the icon class is not being applied correctly to the React version of the component. See: https://github.com/IBM/carbon-components-react/issues/1877 (this means I wouldn't be able to see icon fill changes reflected in our React environment)

Once that issue gets fixed I can more easily test & propose a PR for this 👍

**Comment by jendowns** [comment]
On our end it looks like this issue has been resolved, so I'm going to close this out 👍
