### ISSUE TITLE
[Bug]: Popover is clipping in a modal

### ISSUE THREAD

**Issue by georgespano** [carbon-design-system/carbon#17749]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.68.0

### React version

18.3.1

### Description

Opening a popover inside a modal results in the content being clipped. The alignment setting is also not being respected most likely due to the underlying issue causing the clipping.

![Image](https://github.com/user-attachments/assets/a9cc50c0-f73a-4ffb-8959-e86fe41b5fe6)

Using a toggle tip, I do not see the same issue.

![Image](https://github.com/user-attachments/assets/7b51a31e-f95a-47ca-b4ed-d83b79d3fed9)

**Hacky work-around:**
On the element with the `cds-popover` class if you add a css style` position: fixed` it forces the popover to break out of the clip.
However, it doesn't truly fix the underlying issue and popover positioning based on the parent does not work (ie. align: left).

### Reproduction/example

https://stackblitz.com/edit/github-ukeceq?file=src%2FApp.jsx

### Steps to reproduce

1. Open the reproduction example
2. Click the open modal button
3. In the modal, click the "Popover" button.

Result: the popover which appears is clipped in the modal - notice the red border which encloses the "I am some content" popover is clipped
Expected: the popover is not clipped.

Notice clicking the toggle tip text shows the same popover as expected (ie. not clipped).

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Automation Builder Workflow Designer

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@preetibansalui do you have any thoughts on why the Toggletip is working correctly in this situation whereas the Popover does not? The HTML between the two does not have much of a diff other than a couple classes and an extra div around the content div in Toggletip.

![Image](https://github.com/user-attachments/assets/c49eb49a-afa9-4278-8fb6-89961e7c2b89)

**Comment by georgespano** [comment]
Thanks @preetibansalui for fixing this so quickly!
Will this make it into 1.69.0 release?
