### ISSUE TITLE
[component / date picker]: broken in mobile Safari

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1775]
Copied from: carbon-design-system/carbon-website#1052

## Detailed description

> Describe in detail the issue you're having.

Date picker has a problem with Mobile Safari, shown below:

![img_2348](https://user-images.githubusercontent.com/32881239/52522367-1b602a80-2c4a-11e9-8d4a-97a25c4230bf.jpg)

![img_2347](https://user-images.githubusercontent.com/32881239/52522375-2b780a00-2c4a-11e9-9a6a-3b3b8ba1547a.jpg)

> Is this issue related to a specific component?

Date picker

> What browser are you working in?

Mobile Safari

> What version of the Carbon Design System are you using?

Latest `9.x`, assuming experimental

**Comment by emyarod** [comment]
refs https://github.com/IBM/carbon-components-react/issues/1965 as the website uses the React component I believe

**Comment by shinytoyrobots** [comment]
Poss won't fix specifically this issue, as reassessing underlying date-picker options.
