### ISSUE TITLE
UI Shell: Research & Audit

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#17761]
# Acceptance Criteria

We need to conduct some initial research and audit our UI Shell as well as other PAL UI Shells to understand the current status of what exists

-----

# Carbon UI shell
Understand our current anatomy of the UI Shell (Header, Left panel, Right panel). Identify the variants, props, etc of this component that we currently have. 

**Contacts:** Carbon team

### Code
- [UI Shell header](https://react.carbondesignsystem.com/?path=/docs/components-ui-shell-header--overview)
- [Panels](https://react.carbondesignsystem.com/?path=/docs/components-ui-shell-sidenav--overview)

### Website docs
- [UI Shell header](https://carbondesignsystem.com/components/UI-shell-header/usage/)
- [UI Shell left panel](https://carbondesignsystem.com/components/UI-shell-left-panel/usage/)
- [UI Shell right panel](https://carbondesignsystem.com/components/UI-shell-right-panel/usage/)

### Figma kit
- [UI Shell header](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?node-id=539-0&t=zslRqzQrSN85nxUT-1)
- [UI shell left panel](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?m=auto&node-id=2258-13866&t=zslRqzQrSN85nxUT-1)
- [UI Shell right panel](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?m=auto&node-id=2258-13915&t=zslRqzQrSN85nxUT-1)

-----

# PAL UI shells
Document what the current state of the UI shells are in the following PALs

Note: Scott has connected with Robert Uthe and will track down assets to add to this issue to reference.

## MCSP

**Contacts:** Randa Salem
Reached out to Arunsai T (visual designer) 

### Code
Confirm this is the correct link with Scott.

- [Header](https://pages.github.ibm.com/ibm-saas-platform/mcsp-react-components/?path=/story/header--unauthenticated-context)
- [Trial banner](https://pages.github.ibm.com/ibm-saas-platform/mcsp-react-components/?path=/story/trial-banner--default)
- [User profile](https://pages.github.ibm.com/ibm-saas-platform/mcsp-react-components/?path=/story/user-profile--menu)

### Website docs
- Looks like it follows the Carbon for IBM products PAL. Here is the[ Slack thread in 2023](https://ibm-studios.slack.com/archives/C05CV7T8J72/p1701122951124749). They were considering creating their own website but haven't yet
- They used the Carbon UI shell as a guide and then created extra stuff to support their needs within MCSP

### Figma kit
- [Figma kit](https://www.figma.com/design/gZJlVmeEDmMdvzLF18vJHX/MCSP-Design-Library?node-id=11-29596)

## Cloud Pak

**Contacts:** Dejan Glozic and Rhonda S (these people don't know about the design resources) 
Marion Heckler is a good contact

### Code
- [Header](https://pages.github.ibm.com/ibm-saas-platform/mcsp-react-components/?path=/story/header--unauthenticated-context): It says on the website that Cloud Pak leverages the MCSP repo for the header components.

- It does NOT leverage MCSP (that was a mistake on the website, we are working to remove it)

### Website docs
- [Header](https://pages.github.ibm.com/carbon/ibm-products/cloud-pak/header/overview/)

### Figma kit
- [Navigation](https://www.figma.com/design/CM4zdLTKxvSZhEEd5CoaHb/Carbon-for-Cloud-(All-Themes-V11)?node-id=12-10626). Looks like it's pointing to Carbon for Cloud?

## Carbon for IBM Products

**Contacts:** Olivia Carson, Aubrey O'Neal, and Linda Carotenuto
We're probably deprecating:
- [Nav](https://carbon-for-ibm-products.netlify.app/?path=/docs/experimental-components-nav--docs)
- [Filter panel](https://carbon-for-ibm-products.netlify.app/?path=/docs/experimental-components-filter-panel-filterpanel--docs) 

### Code
- [Notifications panel](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-patterns-notifications-notificationspanel--docs)
- [Side panel](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-side-panel-sidepanel--docs)
- Question: Do we need to account for what is in `Experimental`? There are things like Filter panel and Nav in there.

### Website docs (components)
- [Side panel](https://pages.github.ibm.com/carbon/ibm-products/components/side-panel/usage/)

### Website docs (patterns)
- [Notifications panel](https://pages.github.ibm.com/carbon/ibm-products/patterns/notifications/usage/)
- [Profile and settings](https://pages.github.ibm.com/carbon/ibm-products/patterns/profile-and-settings/usage/)
- [UI navigation](https://pages.github.ibm.com/carbon/ibm-products/patterns/ui-navigation/usage/)

### Figma kit
- [Notifications panel](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-BETA-Carbon-for-IBM-Products?node-id=1-1329&t=wUWtBnjeXvPsa09V-1)
- [Side panel](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11)-BETA-Carbon-for-IBM-Products?node-id=1-1317&t=wUWtBnjeXvPsa09V-1)

## Cloud PAL

**Contacts:** Jeeyoung Yang is the design lead (probably closest to Carrie's role),  Stephanie Cree is the UXE lead, and Kevin Camelo is the visual/UX designer.

### Code
- [Side nav](https://pages.github.ibm.com/ibmcloud/cloud-pal-community/?path=/docs/basic-components-sidenav--docs)
- [Side panel](https://pages.github.ibm.com/ibmcloud/cloud-pal-community/?path=/docs/basic-components-sidepanel--docs)
- [Word level nav](https://pages.github.ibm.com/ibmcloud/cloud-pal-community/?path=/docs/basic-components-worldlevelnav--docs)

### Website docs
- [Navigation](https://pages.github.ibm.com/ibmcloud/design-operations/carbon-for-cloud/components/navigation/usage)
- [Side panel](https://pages.github.ibm.com/ibmcloud/design-operations/carbon-for-cloud/components/side-panel-on-cloud/usage)
- [Worlds](https://pages.github.ibm.com/ibmcloud/design-operations/carbon-for-cloud/patterns/worlds)

### Figma kit
- [Navigation](https://www.figma.com/design/CM4zdLTKxvSZhEEd5CoaHb/Carbon-for-Cloud-(All-Themes-V11)?m=auto&node-id=12-10626&t=l4jPFZuAmu2ZsK1J-1)
- [Side panel](https://www.figma.com/design/CM4zdLTKxvSZhEEd5CoaHb/Carbon-for-Cloud-(All-Themes-V11)?m=auto&node-id=131-2&t=l4jPFZuAmu2ZsK1J-1)

**Comment by thyhmdo** [comment]
## Chat with Marion Hekeler | Nov 5

**Shared components across platforms**
There's a focus on ensuring components work across both On-Premise (Cloud PAK) and SaaS platforms (MCSP). This requires building components in a way that they’re adaptable and function consistently across both environments. 

**Components structure**
The foundation of these components is Carbon components. But these components' functions expand for product's needs. 

**Future website plan**
Currently, there’s no set plan for a website related to these components, but Marion plans to discuss this possibility with Linda, which could suggest a more organized, accessible way to document or showcase components in the future.

**Team collaboration and maintenance**
The Common Core Service is maintained by various teams, but the individual experiences (or how these components appear in the product) are the responsibility of specific dev and design teams.

**Comment by thyhmdo** [comment]
### Team meeting with Marion | Nov 6

Team: Alison, Anna, Olivia, Matt, and Sam Ting were on the call
Intent: Learning the landscape of MCSP(SaaS) and Cloud Pak (on-prem) from the perspective of on-prem 
Goal: Need to understand our involvement from the Carbon team. Both teams should have one common place to share the guidance with a few specific guidances for each.
