### ISSUE TITLE
[Feature Request]: cds-pagination should expose a way to change the formatSupplementalText

### ISSUE THREAD

**Issue by rsimpso1** [carbon-design-system/carbon#17766]
### The problem

I want to be able to translate the strings related to the formateSupplementalText property mentioned here: https://web-components.carbondesignsystem.com/?path=/docs/components-pagination--overview#cds-pagination-attributes-properties-and-events

However the property is not exposed as an attribute of the component so I'm unable to change the function / its corresponding strings.

### The solution

Expose an attribute for each string, or an attribute to override the function so we can provide our own string depending on state.

### Application/PAL

watsonx Assistant

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Thanks @rsimpso1 for bringing this to our attention. We're going to take a look at this when we tackle Pagination in this [epic](https://github.com/carbon-design-system/carbon/issues/17992).

**Comment by rsimpso1** [comment]
Thanks Scott! I was actually just going to close this issue. I've been working in React for awhile and forgot that you're suppose to use `.propName` syntax to set a property on html / web components. So doing something like `.formatSupplementalText=${getTablePaginationPagesLabel}` actually does work for the pagination component and this issue can be resolved. 

I did find myself wondering why carbon sometimes seems to have just properties for a piece of functionality, and sometimes has both attributes and properties. It looks like this is because properties can take js and be set by js where as attributes can only be strings, which makes sense in this case that it would only be a property.
