### ISSUE TITLE
[Bug]: Clickable Tile icon is 16px in Storybook and 20px in Figma

### ISSUE THREAD

**Issue by skcele** [carbon-design-system/carbon#17776]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.68.0

### Description

This is such a minor visual bug, but I noticed while fixing a similar visual issue with one of our components.

Clickable Tile's icon in the lower right is 16px in code (in Storybook at least) and 20px in Figma.

### Screenshots

Figma
![Image](https://github.com/user-attachments/assets/eb6d431c-aa7a-44c8-8ea1-ebea793bb874)

Storybook
![Image](https://github.com/user-attachments/assets/d2b69e9b-6ffc-4d6e-8499-687707d7261d)

### Steps to reproduce

Use the Figma Component, set to Clickable, inspect in dev mode

Use the coded component in React and inspect.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alina-jacob** [comment]
Thanks for opening the issue @skcele, as per the [design spec](https://carbondesignsystem.com/components/tile/style/#clickable-tile-structure) for clickable tile, the icon should be 20px
![Image](https://github.com/user-attachments/assets/e67d8513-e4fc-470b-97f6-5b1f2defd6bc)


So the code needs fixing!
