### ISSUE TITLE
List-box looks too small on carbon component demo

### ISSUE THREAD

**Issue by ramin-ahmadi** [carbon-design-system/carbon#1778]
## Detailed description

> Listbox component width is too small and listbox menu items are not properly visible

> list-box component

> I expect to see a wider listbox.

> Chrome, Firefox and IE

> using version 9

> working on carbon components. deadline N/A

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

![image](https://user-images.githubusercontent.com/5785195/52612427-c0466600-2edd-11e9-8c8f-ed838445986a.png)

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Being addressed as part of: #1752

**Comment by ramin-ahmadi** [comment]
Thanks Akira san
