### ISSUE TITLE
[Bug]: Readonly state in Multiselect and FilterableMultiselect has hover interaction on the close button.

### ISSUE THREAD

**Issue by Gururajj77** [carbon-design-system/carbon#17820]
### Package

@carbon/react

### Browser

Chrome

### Package version

v11

### React version

v18

### Description

from the comment in this [PR](https://github.com/carbon-design-system/carbon/pull/17662#pullrequestreview-2367110367), we found out that the hover state is still present on the button when in readonly state. This is from the components `ListBox.Selection` and `ListBoxSelection` (which is in the next folder). 

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-multiselect--playground&args=readOnly:!true

### Steps to reproduce

go to the above link and hover on the 'X' button.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by laurenmrice** [comment]
The Read-only state for the Multiselect and Filterable Multiselect needs to look like the design specs below: 

![Image](https://github.com/user-attachments/assets/368c808e-b685-4d13-b8e1-d67cd0ac7e1c)
