### ISSUE TITLE
[Carbon X] Notification text color token does not work on dark themes

### ISSUE THREAD

**Issue by j1mie** [carbon-design-system/carbon#1783]
## Detailed description

The color variable assigned to notification text is `$text-01`, [link](https://github.com/IBM/carbon-components/blob/master/src/components/notification/_inline-notification.scss#L123).

In dark themes like theme-g100, the color will render as Gray 10 - #f3f3f3, making this text illegible. We may need a new token for this @aagonzales ?

![screenshot 2019-02-12 at 15 59 04](https://user-images.githubusercontent.com/12685163/52648934-41eac380-2edf-11e9-9955-1c671ee18baa.png)

**Comment by laurenmrice** [comment]
We are currently changing all notifications to high contrast moments on every theme to solve issues like this ^. Currently being worked on by dev. https://github.com/carbon-design-system/carbon-components/issues/2354

**Comment by laurenmrice** [comment]
not stale

**Comment by shixiedesign** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/2814
