### ISSUE TITLE
[Bug]: Dropdown props.titleText is marked as optional in typescript but required in prop-types

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#17843]
### Package

@carbon/react

### Package version

1.68.0

### Description

In typescript, the `titleText` prop is marked as optional while in the propTypes it's defined as required. This causes a warning in the console even if TS validation succeeds.

https://github.com/carbon-design-system/carbon/blob/b5430795bc444c65e3561b6c64c5566cadc6906c/packages/react/src/components/Dropdown/Dropdown.tsx#L222

https://github.com/carbon-design-system/carbon/blob/b5430795bc444c65e3561b6c64c5566cadc6906c/packages/react/src/components/Dropdown/Dropdown.tsx#L799

### Reproduction/example

-

### Steps to reproduce

```tsx
import { Dropdown } from '@carbon/react';

function MyComponent() {
  return (
    <Dropdown
      id="id"
      label="Label"
      items={['Lorem', 'ipsum', 'dolor']}
    />
  );
}
```

This passes TS validation but fails propTypes validation.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Thamjith** [comment]
Could you please assign this to me? @alisonjoseph
