### ISSUE TITLE
[Bug]: onChange fires twice when selecting item on ComboBox

### ISSUE THREAD

**Issue by teresamonahan** [carbon-design-system/carbon#17847]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.68.0

### Description

When selecting an item on a combobox, the onChange function is called twice.

### Reproduction/example

https://stackblitz.com/edit/github-yb3are?file=src%2FApp.jsx%3AL34-L34,package-lock.json

### Steps to reproduce

Run the slackblitz sample with devtools open so you can see the console logs.
Select an item on the ComboBox
Problem: The onChange function is called twice. You can see the debug log printed 2 times to the console

### Suggested Severity

None

### Application/PAL

IBM Cloud - IAM UI

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by flannanl** [comment]
In addition, I also see the `onChange` fires if I re-render the component with an updated `selectedItem` prop. I would expect the `onChange` only fires if there is a user interaction to pick an option from the dropdown, which is the behaviour before v1.68.

**Comment by adamalston** [comment]
Adding onto https://github.com/carbon-design-system/carbon/issues/17847#issuecomment-2438912689, the changes from `1.67.1` to `1.68.0` result in infinite loops being run in a UI I'm working on. There are three `ComboBox` changes mentioned in https://github.com/carbon-design-system/carbon/releases/tag/v11.68.0. For now, I've downgraded to `1.67.1`.

**Comment by flannanl** [comment]
Can we have a fix sooner? This bug is preventing us from moving up to 1.68.0 or later.

**Comment by flannanl** [comment]
Hi @guidari, any update? We start seeing this issue in many places we use ComboBox component.

**Comment by k02pradeep** [comment]
+1
