### ISSUE TITLE
[Bug]: Responsive breakpoints not working in PaginationNav

### ISSUE THREAD

**Issue by smith558** [carbon-design-system/carbon#17880]
### Package

@carbon/react

### Browser

Chrome

### Package version

v11.69.0

### Description

The responsive breakpoints for the `PaginationNav` component don't seem to be working. I tested this in my local code as well as your Storybook.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-paginationnav--playground&globals=viewport:sm

### Steps to reproduce

1. open https://react.carbondesignsystem.com/?path=/story/components-paginationnav--playground&globals=viewport:sm
2. the component is not responsive in `sm` viewport

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by smith558** [comment]
@guidari Thanks for having reviewed this!

**Comment by thyhmdo** [comment]
One of the bug issues (for the itemsShown) has been already fixed by Jan https://github.com/carbon-design-system/carbon/pull/18015

These design specs help document the changes for the design. 

![Image](https://github.com/user-attachments/assets/2a8321f5-9cd4-4701-b8d8-d8b0849719c2)
