### ISSUE TITLE
[Bug]: Community assets component index not accessible

### ISSUE THREAD

**Issue by smith558** [carbon-design-system/carbon#17905]
### Package

@carbon/react

### Package version

N/A

### Description

The Community assets component index linked from https://carbondesignsystem.com/community/component-index/ doesn't seem to be accessible. https://next.carbondesignsystem.com/ returns "page not found".

![Image](https://github.com/user-attachments/assets/5a167e24-d656-41a0-9010-b47ebda32b66)

### Reproduction/example

https://next.carbondesignsystem.com/

### Steps to reproduce

1. Go to https://next.carbondesignsystem.com/

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
The community index is only available for IBMers at this time.

**Comment by smith558** [comment]
> The community index is only available for IBMers at this time.

Why is that? I was under the impression that the Carbon Design System is open source.

**Comment by alisonjoseph** [comment]
@smith558 Unfortunately, the project ([next.carbondesignsystem.com](http://next.carbondesignsystem.com/)) was de-prioritized, it was put behind a login to prevent access to outdated materials that no longer reflect the latest work. We hope to revisit and update this project in the future when priorities allow.

**Comment by smith558** [comment]
> [@smith558](https://github.com/smith558) Unfortunately, the project ([next.carbondesignsystem.com](http://next.carbondesignsystem.com/)) was de-prioritized, it was put behind a login to prevent access to outdated materials that no longer reflect the latest work. We hope to revisit and update this project in the future when priorities allow.

Thanks for your reply. That is unfortunate. Hopefully, it may get open again. 🤞
