### ISSUE TITLE
[BUG]: Need to set display styling for listbox wrapper to allow fluid styling in Angular without manually setting style

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon#17953]
### Package

@carbon/styles

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.68.0

### React version

_NA_

### Description

Similar to issue #11579 - We are looking to release fluid form in Angular. In this process, we found out that we had manual `display` property set for dropdown and combobox to `block`. To remove this, we are proposing to add a `display: block` property to `cds--list-box__wrapper` property which exists in both components and their fluid states. 

A possible workaround we have is to export custom styles with the carbon-components-angular package, which is NOT ideal.

### Reproduction/example

_NA_

### Steps to reproduce

_NA_ We haven't released the fluid state for Combobox/Dropdown components as of yet.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ismaildasci** [comment]
Hey! 👋

Thanks for bringing this up! It sounds like a useful enhancement for fluid forms in Angular. Adding display: block to cds--list-box__wrapper makes sense, as it would ensure consistent layout without the need for manual adjustments.

For now, if you need a workaround, exporting custom styles with carbon-components-angular seems viable, though I understand it's not ideal. We’ll check if we can get this update prioritized in a future release.

Appreciate your feedback and suggestion! 😊
