### ISSUE TITLE
Improve build time: Research to determine if there's new info/configuration we can use, form recommendation on next steps

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#17986]
This issue will provide all the information on what all features that are available for us to opt in when we bring in NxCloud for cache distribution.

**Comment by Gururajj77** [comment]
After going through their docs regarding the "NX Replay" and "Share your cache". The steps remain the same for implementing Nx Replay in our Monorepo
- Request for an OSS account
- run the command `npx nx connect-to-nx-cloud`, this will generate the `nx.json` file in the root
- update the `lerna.json` to use Nx.
- lerna will automatically use the Nx commands for this feature.
