### ISSUE TITLE
Interior Left Nav transition

### ISSUE THREAD

**Issue by hellobrian** [carbon-design-system/carbon#180]
@jzhang300 commented on [Tue Jun 13 2017](https://github.com/carbon-design-system/carbon-components-react/issues/20)

**Context:**

When you toggle the Interior Left Nav component, the selected menu item has background white
![fb9f4ef6-4d34-11e7-902b-79e5bc4c9c79](https://user-images.githubusercontent.com/1449523/27094575-1c3ee5b0-5030-11e7-8d9d-f049c4c413d3.gif)

---

- [ ] Make active menuitem `background-color: transparent`

---

@hellobrian commented on [Tue Jun 13 2017](https://github.com/carbon-design-system/carbon-components-react/issues/20#issuecomment-308266804)

Can you override the background-color with your own styles? 
Also, if you want a change to the SCSS, we should submit a new PR to carbon-components repo.

Going to move this issue to carbon-components.

**Comment by jzhang300** [comment]
@hellobrian Continuing from previous discussion, I'm overriding that right now, which is a relatively simple fix.
