### ISSUE TITLE
[Bug]: `TableToolbarSearch` `onChange` `value` is always `undefined`

### ISSUE THREAD

**Issue by adamalston** [carbon-design-system/carbon#18008]
### Package

@carbon/react

### Package version

1.67.1

### Description

Although the TypeScript types for `TableToolbarSearch`'s `onChange` event handler indicates it may return a value, it doesn't seem to.

https://github.com/carbon-design-system/carbon/blob/cdc8db7fcd0085f344e8f3942c5f8f48eb24ab5a/packages/react/src/components/DataTable/TableToolbarSearch.tsx#L89-L95

### Reproduction/example

https://stackblitz.com/edit/github-4gatub?file=src%2FApp.tsx

### Steps to reproduce

1. Open the reproduction.
2. Open the browser console.
3. Enter <kbd>123</kbd> in the search bar.
4. Notice that nothing appears to change and that `undefined` is logged to the console.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

DataPower

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @adamalston 
You can return a value if you do that:

```
<TableToolbarSearch
        onChange={(event) => {
          console.log('event',event.target.value);
          setTerm(event.target.value ?? '');
        }}
```
