### ISSUE TITLE
[Bug]: ConditionBuilder issues

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon#18032]
### Package

@carbon/react

### Browser

Chrome

### Package version

V11

### React version

v17

### Description

Following issues found with [ConditionBuilder](https://carbon-for-ibm-products.netlify.app/?path=/story/experimental-components-conditionbuilder--condition-builder&globals=viewport:basic)

- Cannot type in to the search box to filter the list.
![Image](https://github.com/user-attachments/assets/df38b2de-659f-4fe8-b7ca-2d9b1925863a)

- When `is one of` is selected and try selecting multiple values from drop down. Dropdown auto closes after every time a checkbox is selected. It should instead remain open until all selections are done
![Image](https://github.com/user-attachments/assets/beda8ece-5233-482e-a9d6-f631350553c7)

### Reproduction/example

https://carbon-for-ibm-products.netlify.app/?path=/story/experimental-components-conditionbuilder--condition-builder&globals=viewport:basic

### Steps to reproduce

- Try using `is one of` operator and try typing text to search field.
- Try clicking on the check boxes.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment]
Could you please raise this issue in the [Carbon for IBM Products](https://github.com/carbon-design-system/ibm-products/issues/new/choose) repository???

**Comment by kalyanixraut** [comment]
As suggested created new issue created in ibm-products https://github.com/carbon-design-system/ibm-products/issues/6402
