### ISSUE TITLE
[Bug]: Opening dropdown should not scroll to selected item

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#18089]
### Package

@carbon/react

### Browser

Chrome

### Package version

"1.67.0

### React version

18.3.1

### Description

We upgraded from 1.53.1 to 1.67.0.  The behavior of the dropdown changed to scroll down to the currently selected item.  This is not desirable behavior.  I opened the dropdown because I want to change the value.  Therefore, there's no reason to scroll down to see the selected one.  Often, it means I just have to scroll back up.

For example, 
- Go the the story book and select Option 8.  
- Open the dropdown again and scroll all the way to the top and then close the dropdown.  This is to simulate coming to the page for the first time, where the scrollbar will be at the top.
- Now open the dropdown again and try to select Option 1.  Since the dropdown autoscrolled Option 8 into view, I now have to scroll all the way back up to Option 1 to select it.

Now it could be that I only wanted to select Option 7, so the behavior isn't as annoying.  But the scroll into view is really jarring and there's really no good reason I can think of that I would want to scroll the current value into view when I'm about to change it to something else.

QE has reported a bug on this and I had found it very annoying even before then.

### Reproduction/example

see description above

### Steps to reproduce

see description above

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by rajat153** [comment]
Hi I am new to open source, I'm willing to do this , can you suggest me how to move forward.

**Comment by guidari** [comment]
Hey @kglickman 
The fact that the `Dropdown` was not scrolling to the selected item before in this v11 version is a regression, because it used to work on v10 before.
Here a couple conversation so you can get more context regarding when was fixed: https://github.com/carbon-design-system/carbon/issues/15978 https://github.com/carbon-design-system/carbon/issues/16935
This is an expected behavior in Carbon.

@rajat153 We have a Contributing guide for you to get started [here](https://github.com/carbon-design-system/carbon?tab=readme-ov-file#-contributing)

**Comment by kglickman** [comment]
@guidari Are would not say that those two defects are the same.  They are talking about when you are focused on an item.  I'm not focusing, not typing, not using the arrow keys.  I'm just opening the dropdown.

**Comment by guidari** [comment]
The issues might not be clear, but this [PR](https://github.com/carbon-design-system/carbon/pull/17074) introduced the `scrollIntoView` functionality for the dropdown when it opens. This was an expected feature that was missing after the migration from v10 to v11, which might explain why it seemed like a bug when we addressed it.

**Comment by alisonjoseph** [comment]
This is working as intended
