### ISSUE TITLE
@carbon/react uses lodash.findlast@4.6.0 which has security issues

### ISSUE THREAD

**Issue by k02pradeep** [carbon-design-system/carbon#18097]
Summary
@carbon/react uses lodash.findlast@4.6.0  which has security issues

Details
Criticial and High priority security issues
https://github.com/advisories/GHSA-jf85-cpcp-j695 (BDSA-2019-2112)
https://github.com/advisories/GHSA-p6mc-m468-83gw (BDSA-2020-1674)
https://github.com/advisories/GHSA-35jh-r3h4-6jhm (BDSA-2021-0392)

Impact
Because the dependency of the @carbon/react v1.70.0 has dependency on lodash v4.6.0, we are not to release the product

**Comment by k02pradeep** [comment]
https://github.com/carbon-design-system/carbon/issues/17731

**Comment by alisonjoseph** [comment]
@k02pradeep This fix should be available in version [1.71.1](https://www.npmjs.com/package/@carbon/react/v/1.71.1) of @carbon/react.

**Comment by k02pradeep** [comment]
Thank you @carbon/react team
