### ISSUE TITLE
[Bug]: Columns in subgrid in narrow grid are not aligning properly

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#18111]
### Package

@carbon/react

### Package version

1.70.0

### Description

While columns in a sub grid in wide and condensed modes are aligning as intended, the extra margin-inline-end of the narrow mode isn't being accounted for. This breaks the subgrid usage in narrow mode as demonstrated below:

![Image](https://github.com/user-attachments/assets/eec2327d-5262-4ae5-8392-18013d808217)

![Image](https://github.com/user-attachments/assets/7f7bd6f5-608b-4375-bba8-0051f74fb853)

### Reproduction/example

https://stackblitz.com/edit/github-s8l8ea?file=src%2FApp.jsx

### Steps to reproduce

```jsx
<Grid narrow>
  <Column sm={2} md={4} lg={8}>Lorem ipsum</Column>
  <Column sm={2} md={4} lg={8}>Lorem ipsum</Column>

  <Column sm={4} md={8} lg={16}>
    <Grid narrow>
      <Column sm={2} md={4} lg={8}>Lorem ipsum</Column>
      <Column sm={2} md={4} lg={8}>Lorem ipsum</Column>
    </Grid>
  </Column>
</Grid>

```

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
Was able to duplicate this locally in storybook
<img width="1369" alt="Image" src="https://github.com/user-attachments/assets/23fc533c-f37c-4eea-aa08-4d28204c655a" />
