### ISSUE TITLE
need an option for some columns to be sticky in tables

### ISSUE THREAD

**Issue by rpenny125** [carbon-design-system/carbon#1814]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Some tables can end up in situation where not all columns can be visible due to lack of horizontal space, and a large number of columns. This feature would allow the table designer to cause some number of columns on the left to remain visible when scrolling to the right.

This requires both design and development

### Justification

 When scrolling to the right to see the remaining columns there can be (at least) two reasons why it helps the user to have the first N columns be "sticky" (i.e. not scroll off):
1. One or more columns are useful in "identifying" a row (e.g. a "name" column), and, if those columns are scrolled off, the user can no longer tell what item the row represents.
2. One of the columns is an "action" column of some sort. e.g., a checkbox column for selection, but the "action" column could provide other options such as "drill down" or "perform some action on the item represented by the row"

While it is generally desirable to limit the number of columns, this is not an option in all cases, e.g., where the end user gets to implicitly set the number of columns by writing their own SQL query with a large number of columns.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by which we can measure success/failure for the user.

Here is an example of an existing table with this functionality. First picture unscrolled, second picture scrolled (areas highlighted in red rectangles are to draw attention to areas that hopefully show the "interesting" changes between pictures):
unscrolled:
![image](https://user-images.githubusercontent.com/34149172/52745221-87c18d80-2fac-11e9-956d-2b09104a7a71.png)

scrolled:
![image](https://user-images.githubusercontent.com/34149172/52745263-990a9a00-2fac-11e9-8280-a5c76065466a.png)

### "Must have" functionality

1. The number of columns to be "fixed" is a parameter
2. The specified number of columns do not move during horizontal scrolling
3. screen readers can read a whole row without being confused when progressing from a fixed cell to a movable cell. It is OK if the screen read reads cells that have been scrolled off (I believe)

### Specific timeline issues / requests

Ideally this feature would be GA by mid Q2 2019

### Available extra resources

We can offer a part-time developer if someone can point to the specific points in the code and the preferred architectural choices for these changes.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! My knee-jerk reaction to this is that the requirement goes beyond the purview of data table core component library, but CC @IBM/carbon-designers to see what they think.

**Comment by chrisconnors-ibm** [comment]
This seems to be the equivalent of 'freeze columns' functionality in spreadsheets.

As an open source development effort, @rpenny125 _your development team_ is empowered to **build this functionality according to your urgency and submit it back as a Pull Request**. Is something blocking your team from doing this?

**Comment by rpenny125** [comment]
We understand this. Unfortunately, we don't have the resources right now, but when we get back on track we will take a look at adding this ourselves.

Our first question, however, is:
Do you consider this as acceptable for the future of the core table (which as I understand it, would mean making a pull request against the experimental table?) or only in an add-on?

**Comment by asudoh** [comment]
Refs our `v10` plan: 
https://github.com/IBM/carbon-components/issues/1587#issuecomment-467554639

**Comment by aagonzales** [comment]
Not stale.

**Comment by jeanservaas** [comment]
Not stale

**Comment by akongole** [comment]
Can this be looked at ?

**Comment by tay1orjones** [comment]
This has been closed for some time, but I want to mention that this feature is available in the @carbon/ibm-products library. 

It's a companion library supported by a subset of teams within IBM and has an advanced "DataGrid" built atop the DataTable with this functionality (plus a lot more) [demo here](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--frozen-columns). 

The DataGrid workstream specifically is supported by an internal working group. Issues and future plans can be found on the [ibm-products repository](https://github.com/carbon-design-system/ibm-products)
