### ISSUE TITLE
[Bug]: Cannot toggle a `SideNavMenu` inside a `SideNavMenu`

### ISSUE THREAD

**Issue by atar9500** [carbon-design-system/carbon#18149]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.71.0

### React version

v18.3.1

### Description

When rendering a nested menu (a `SideNavMenu` inside a `SideNavMenu`)  inside the `SideNav` component, a menu of a menu does not open up on click.

A current workaround that work is:

```jsx
import React from 'react';
import { SideNavMenu } from '@carbon/react';

const WorkaroundNavMenu = ({ ...rest }) => {
  const ref = React.useRef();

  React.useEffect(() => {
    const callback = () => {
      const expanded = ref.current.getAttribute('aria-expanded');
      ref.current.setAttribute(
        'aria-expanded',
        expanded === 'true' ? 'false' : 'true'
      );
    };
    ref.current.addEventListener('click', callback);
    return () => {
      ref.current?.removeEventListener('click', callback);
    };
  }, []);

  return <SideNavMenu ref={ref} {...rest} />;
};

export default WorkaroundNavMenu;
```

### Reproduction/example

https://stackblitz.com/edit/github-1p4yd4

### Steps to reproduce

1. Render a side nav as follows:

```jsx
export default function App() {
  const [isSideNavExpanded, setSideNavExpanded] = React.useState(false);
  return (
    <div>
      <Header>
        // ...Some Header components
        <SideNav
          expanded={isSideNavExpanded}
          aria-label="Side navigation"
          href="#main-content"
          isRail
        >
          <SideNavItems>
            <SideNavMenu title="L0 menu">
              <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                Link
              </SideNavMenuItem>
              <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                Link
              </SideNavMenuItem>
              <SideNavMenu title="This submenu doesn't work">
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
              </SideNavMenu>
            </SideNavMenu>
          </SideNavItems>
        </SideNav>
      </Header>
    </div>
  );
}
```

2. Open `SideNav`.
3. Open a `SideNavMenu` inside of `SideNavMenu`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by swapanmandi** [comment]
Change SideNavMenu to WorkaroundNavMenu like: 

<WorkaroundNavMenu title="This submenu doesn't work">
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
                <SideNavMenuItem href="https://www.carbondesignsystem.com/">
                  Link
                </SideNavMenuItem>
</WorkaroundNavMenu>

**Comment by tay1orjones** [comment]
Hi @atar9500 the left panel [does not support](https://carbondesignsystem.com/components/UI-shell-left-panel/usage/#:~:text=The%20left%20panel%20does%20not%20support%20three%20tiers%20of%20navigation.%20If%20you%20have%20additional%20content%20to%20display%20beneath%20a%20sub%2Dmenu%2C%20use%20tabs%20within%20the%20page) three tiers of navigation.

We've had recent explorations to improve this though and may make this improvement in the future.

To fix your usage you're welcome to submit a bugfix for this if you're interesting in contributing a PR. We generally accept fixes for usages that may not be officially supported or recommended.
