### ISSUE TITLE
[Bug]: Incorrect visual alignment for clear search button in search component for size='lg' & 'md'

### ISSUE THREAD

**Issue by ruchika777** [carbon-design-system/carbon#18144]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.64.0

### Description

Hi team,

For size= 'md'  search component the close button does not align with search bar height. 

Please refer the screenshot. 

![Image](https://github.com/user-attachments/assets/2834b255-b2a4-460b-9c7e-3f3b3c3dedf1)

But only it works for size = 'sm' 

![Image](https://github.com/user-attachments/assets/b959430e-1a68-4ed7-9857-7545386f962e)

### Screenshots

![Image](https://github.com/user-attachments/assets/9958c229-d849-4edf-bbd1-890f68634392)

![Image](https://github.com/user-attachments/assets/0373bd9e-b14a-492a-9b30-2c7a4bc389b2)

### Steps to reproduce

1. Render the search component in container of width 496 px 
2. use size = 'lg' / 'md' (issue)
3. use size = 'sm' (expected)

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment]
[stackblitz ](https://stackblitz.com/edit/github-hukcxb?file=src%2FApp.jsx)

**Comment by 2nikhiltom** [comment]
Can not repo on storybook, and there is an open bug for "artifact" that appears on close button
