### ISSUE TITLE
need ability to drag resize columns in tables

### ISSUE THREAD

**Issue by rpenny125** [carbon-design-system/carbon#1815]
### Summary

Need the ability to drag resize a column in a table.

This involves both design and code

### Justification

Some data is naturally long. To make the column large enough to display the longest possible content can make the table unwieldy, depending the available screen real estate. Allowing a user to dynamically resize a column allows them to easily override whatever size choice was made initially. For example, one might design a table for a medium size screen, but a user with a larger screen may wish to see more of the column's contents, and therefore resize a column.

The table component should communicate this information so that the containing/calling environment can be informed of the change and therefore be able to respond in some way (for example, by saving the new column width as a preference)

### Desired UX and success metrics

1. As the user moves the mouse over the divider between two column headers, the cursor changes (typically to some form of let-and-right arrow) to indicate that a click-and-drag from this point will result in column resizing.
1. If the user clicks and drags, a vertical line appears. This vertical line covers the height of the visible part of the table, and moves left and right to follow the mouse movement.
1. When the user ends the drag (by releasing the mouse button), the column separator moves from its original location to the new location, and all the cells in the column resize accordingly
1. The table component communicates the change (which column changed, and the values for the old and new widths) to the "calling environment". E.g., this could be by issuing an event.

What follows is three screenshots

Indication of drag resize possibility
![image](https://user-images.githubusercontent.com/34149172/52746279-2b13a200-2faf-11e9-8c50-ea87cef71da0.png)

during dragging, showing the vertical line that follows the mouse:
![image](https://user-images.githubusercontent.com/34149172/52746424-7af26900-2faf-11e9-820a-ccd7a13cddea.png)

end of drag, column has been resized:
![image](https://user-images.githubusercontent.com/34149172/52746516-affebb80-2faf-11e9-9ae6-3d42a334446a.png)

### "Must have" functionality

I can't think of any of the above aspects that can be left out, but maybe I'm wrong about that.

### Specific timeline issues / requests

Early Q2 2019

### Available extra resources

We can offer a part-time developer if someone can point to the specific points in the code and the preferred architectural choices for these changes.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! While it looks a neat feature, I think it goes beyond the purview of data table in core component library, especially considering the balance of complexity/benefit. CC @IBM/carbon-designers to see what they think.

**Comment by chrisconnors-ibm** [comment]
As an open source development effort, @rpenny125 _your development team_ is empowered to **build this functionality according to your urgency and submit it back as a Pull Request**. Is something blocking your team from doing this?

**Comment by rpenny125** [comment]
We understand this. Unfortunately, we don't have the resources right now, but when we get back on track we will take a look at adding this ourselves.

Our first question, however, is:
Do you consider this as acceptable for the future of the core table (which as I understand it, would mean making a pull request against the experimental table?) or only in an add-on?

**Comment by asudoh** [comment]
Weighing in @rpenny125 - Thank you for asking! I think if a reasonable way to make the feature fully optional and code associated with that feature won't be in application's bundle unless the feature in use, there would be a high possibility for us to include the feature in core data table. Otherwise, it'd be good to keep it as an add-on.

**Comment by elvis1994** [comment]
Still needed

**Comment by aagonzales** [comment]
@elvis1994 please follow this issue for updates on resizing data table columns:
https://github.com/carbon-design-system/carbon/issues/4751
