### ISSUE TITLE
Component Design Audit v1.2

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1816]
## Button

- Should use tokens for colors, not call out to `ibm-color` variables directly

## Checkbox

- Inside needs to be block versus rounded (is this do-able?)
- Investigate using SVG for checkbox icon (is this do-able?)
- The stroke weight of the check is fatter than the dash
- Vertical distance between checkbox groups should be `8px`

![image](https://user-images.githubusercontent.com/3901764/52748229-96f40b80-2fab-11e9-91ab-f8e8665db0ae.png)

- remove margin-top from checkbox when placed below a label

![image](https://user-images.githubusercontent.com/3901764/52748512-4a5d0000-2fac-11e9-8a26-279ef8c9f3a2.png)

![image](https://user-images.githubusercontent.com/3901764/52748523-51840e00-2fac-11e9-829f-bf261f655823.png)

## Modal

- No drop shadow on modal

![image](https://user-images.githubusercontent.com/3901764/52749118-e5a2a500-2fad-11e9-8f8f-e415f3d61a15.png)

- Should have max-width set at 768px, but verify with design that this works 👍 

- Should have margin-bottom set to 1rem in form

![image](https://user-images.githubusercontent.com/3901764/52749518-06b7c580-2faf-11e9-960c-00a3b55ad52a.png)

- Should be calling light field inside of a form (field 02), background should end up being gray10

## Notifications

- Height should be 64px with one line of text
- Icon for warning should match circle icon in kit, needs to get added to icon library first (variant of https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fwarning--filled with filled !)
- Icon should be 20x20 variant
- success icon color should be support-02

**Comment by asudoh** [comment]
@joshblack Thank you for writing this up! Any chance for @emyarod to join the audit so that he can get the handle on those kind of component issues? Thanks!

**Comment by asudoh** [comment]
- [ ] Button #1840
- [x] Checkbox #1841 #1842
- [x] Modal #1843 #1844
- [x] Notifications #1845

**Comment by emyarod** [comment]
do all the button color values have tokens associated with them? I desperately need a crash course on tokens to get everything sorted out

**Comment by asudoh** [comment]
CC @IBM/carbon-designers @tw15egan to see if they know - Thanks!

**Comment by jeanservaas** [comment]
@emyarod 

yes, i'm pretty sure all button colors / interactive states have tokens attached to them... color tokens are definitely the ones that have the steepest learning curve. @shixiedesign is this correct?

**Comment by shixiedesign** [comment]
Yep here's the boxnote that hopefully will help you @emyarod. I suggest doing a `cmd+f` and just quickly see if the component is mentioned: 

https://ibm.ent.box.com/notes/346571079971

Please note there's been a couple of tweaks since this document is made, but it's largely correct..sorry this must be frustrating! Design should definitely get together and make an update to component specs that reflects tokens soon. Meanwhile feel free to let me or Anna know if you have any question with tokens.

**Comment by emyarod** [comment]
all comments addressed in https://github.com/IBM/carbon-components/issues/1816#issuecomment-463419295 or superseded by [Feb/Mar 2019 audits](https://github.com/IBM/carbon-components/milestone/14)
