### ISSUE TITLE
Overflow Menu always opens downward regardless of viewport

### ISSUE THREAD

**Issue by priyanksabhaya** [carbon-design-system/carbon#182]
When clicking on the overflow menu which is at bottom edge of the viewport, It gets hidden as it is rendered downward outside the viewport and you need to scroll down to see the overflow menu options.
For Ex:
Current Behavior:
![9f4bb0ca-0dbc-11e7-87c5-37915fd1454d](https://user-images.githubusercontent.com/19478454/27154197-26743f56-5122-11e7-8c42-d89f5add06e0.gif)

Expected Behavior:
![c689201e-0dbc-11e7-8275-4970f1ecba35](https://user-images.githubusercontent.com/19478454/27154227-487d07a4-5122-11e7-8dbc-0fe6e31fa1b2.gif)

**Comment by tw15egan** [comment]
@chrisdhanaraj this could probably be bundled with Data Table updates

**Comment by tay-aitken** [comment]
@chrisdhanaraj was this change made in the tables update or not?

**Comment by chrisdhanaraj** [comment]
Heyo no, it wasn't added with the tables - this should actually be a feature add to the overflow in general; doesn't matter if it's attached to a table or not

**Comment by marijohannessen** [comment]
This is also needed for `Dropdown`

**Comment by tw15egan** [comment]
Related: https://github.com/IBM/carbon-components/issues/966
