### ISSUE TITLE
AVT 3 - Carbon X Text Input alerts are static on the page and can not be tested

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon#1828]
## Environment
macOS Mojave version 10.14.2
Chrome version 72.0.3626.96 (Official Build) (64-bit)

## Detailed description
AVT 3 The expectation is that there would be a form validation that identifies an incorrect text input has been entered and the screen reader would read the validation warning.
[See WCAG Guidelines 3.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error.html)

**Comment by dakahn** [comment]
Form validation is out of the scope of this example component. We're working on better surfacing our a11y expectations as well as suggested implementation (which would include _form validation_). Closing this out.
