### ISSUE TITLE
globals/settings aren't getting bundled correctly

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#1830]
## Detailed description

Haven't totally nailed down what's going on, but essentially import { settings } from carbon-components instead imports the entire project.

Perhaps the global files aren't getting included properly in the regular build?

<img width="651" alt="screen shot 2019-02-14 at 3 41 00 pm" src="https://user-images.githubusercontent.com/4078018/52822747-367ed000-3078-11e9-8bf1-e11a97c849f4.png">

<img width="809" alt="screen shot 2019-02-14 at 4 04 38 pm" src="https://user-images.githubusercontent.com/4078018/52822390-2d413380-3077-11e9-80bf-544e40baae35.png">

**Comment by vpicone** [comment]
Here's the build output from the react repo before and after all of the imports are changed to use the second strategy. Note the size from carbon-components.

<img width="562" alt="screen shot 2019-02-14 at 4 06 38 pm" src="https://user-images.githubusercontent.com/4078018/52822787-5c0bd980-3078-11e9-8157-826c376bcb45.png">

<img width="449" alt="screen shot 2019-02-14 at 4 04 04 pm" src="https://user-images.githubusercontent.com/4078018/52822790-5dd59d00-3078-11e9-960c-e4c8833fa3a8.png">

**Comment by asudoh** [comment]
@vpicone Thank you for reporting! One question - Does the tool account for DCE done with `/*#__PURE__*/` annotations, etc.?

**Comment by vpicone** [comment]
Hmm good question. I don’t know about the import add on, but I believe the tool that reports the final bundle size of the react repo (second comment) does so after it’s been compiled. So after all of the code elimination has taken place. And that tool shows the total bundle size going down ~45kb before gzip.

**Comment by asudoh** [comment]
Thank you for more thoughts @vpicone! Comparing [`carbon-components-react.js`](https://unpkg.com/carbon-components-react@6.94.0/umd/carbon-components-react.js) and [`carbon-components-react.min.js`](https://unpkg.com/carbon-components-react@6.94.0/umd/carbon-components-react.min.js) now - e.g. Searching for `selectorInit` (it's a property found in most of `carbon-components` JavaScript classes) in those files revealed that it's found in non-minified version (the former) and _not_ found in minified version (the latter). Also, we have [a test exactly for this area](https://github.com/IBM/carbon-components/pull/1570/files#diff-b6cab6c868b18031e083972865cb812b).

However, please don't hesitate to speak up if there are any specific concerns. Thanks!

**Comment by vpicone** [comment]
@asudoh After looking at this further I think it actually might have to do with the React UMD build not declaring carbon-components as external. It looks like that's intentional, so I don't think there's an issue, thanks for looking into this with me!
