### ISSUE TITLE
Number input fixes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#1837]
Two fixes needed: 

- [ ] Mobile support https://github.com/carbon-design-system/carbon-contribution/issues/3#issuecomment-464099688 
![image](https://user-images.githubusercontent.com/15144993/52975876-cf6d5e00-338c-11e9-8797-fff483116f7f.png)

- [ ] Mike found forced italic!  
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/c56b47d3-59e8-4781-95fd-29d6cc8775ae)

**Comment by emyarod** [comment]
regarding the forced italic text: it looks like this is a style rule that's applied to all form components with helper text (probably carried over from v9). Just to confirm, are we going to remove italic font style for all form components with helper text or is this specific to number inputs?

**Comment by shixiedesign** [comment]
@emyarod we want italic, but proper correct italic. There's a difference in proper italic and forced italic.  See below image. Pay attention to letter "e" for example. Proper italic is curvey: 
![image](https://user-images.githubusercontent.com/15144993/52968628-704f1f80-3373-11e9-9617-bd486cf93d0b.png)
Does that make sense? 🙏

**Comment by emyarod** [comment]
@shixiedesign I see, so it looks like we are not pulling in the italic font. I guess this is dependent on integration with the new `@carbon/type` package (https://github.com/IBM/carbon-components/issues/1546, #1857)

**Comment by shixiedesign** [comment]
I see. So we should just wait on those issues getting resolved right? Thanks for letting me know. I will pass it on to Mike. 
How about the mobile design? Is that a possible fix?

**Comment by emyarod** [comment]
yes I can create the mobile variant
