### ISSUE TITLE
Date Picker shouldn't show "invalid date format" before receiving focus

### ISSUE THREAD

**Issue by jlengstorf** [carbon-design-system/carbon#184]
Immediately upon loading the page, the Date Picker shows an error message:

<img width="205" alt="screencap-by-jlengstorf 51" src="https://user-images.githubusercontent.com/163561/27231402-1fa3915c-5278-11e7-824e-a93d0fa9d510.png">

This could be confusing/alarming to people; maybe the format check could be delayed until after the input has received focus?

**Comment by marijohannessen** [comment]
Hey, so the reason it's showing invalid is just to show an example of how it would look with the form requirement displayed. Removed the attribute `data-invalid` from `bx--form-item` removes it - it does not use any javascript as is.
