### ISSUE TITLE
Accordion arrow is highlighted after mouse click in Chrome

### ISSUE THREAD

**Issue by Tal-Daniel** [carbon-design-system/carbon#1849]
## Environment
macOS 10.14.3
Chrome 71.0.3578.98

## Detailed description

> What version of the Carbon Design System are you using?

7.2.1, but happens also on carbon-components site. 

> What did you expect to happen? 

Clicking with the mouse on the accordion's heading or arrow should not show any focus highlight  (AKA outline, ring) around the arrow. 
Tabbing with the keyboard shows a focus highlight, as intended, though.

> What happened instead?

Clicking the accordion's heading or arrow highlights the arrow SVG in Chrome (but not in FireFox).
The behavior of the arrow should be similar to that of the heading (no highlight on mouse click); it works only for heading now. 

## Steps to reproduce the issue

1. Create a simple accordion (include JS; accordion styles are not enough).
2. Click with a mouse on one of the accordion panes. Notice how in Chrome a rectangle highlight around the arrow is shown.

## Additional information

See _accordion.scss: 
`.bx--accordion__item:focus .bx--accordion__arrow`

**Comment by asudoh** [comment]
Hi @Tal-Daniel thank you for reporting! As you may have imagined, this goes beyond the purview of a specific component (accordion). And while differentiating focus outline behavior between mouse vs. keyboard would definitely desirable in many contexts, doing so requires [newer web standard](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) to make the implementation straight-forward, and we are not going with non-straightforward solution for now. Hope this makes sense to you!
