### ISSUE TITLE
Using classList in JavaScript breaks in IE11

### ISSUE THREAD

**Issue by ryan76** [carbon-design-system/carbon#185]
IE11 has limited support for `classList` and what it does support is spotty at best. Several of the carbon-component JS files make use of `classList`, which breaks in IE11. You can add the classlist-polyfill (https://www.npmjs.com/package/classlist-polyfill) to fix this problem, or remove the use of `classList` from JS files.

**Comment by asudoh** [comment]
HI @ryan76 beginning in 7.x, carbon-components is no longer shipped with polyfills. Your application need to include polyfills of your choice. The list of polyfills needed for carbon-components can be found in: https://github.com/carbon-design-system/carbon-components/blob/master/demo/polyfills/index.js

@chrisdhanaraj Is “no polyfill” change in 7.x documented somewhere? I could find migrate-to-7.x.md files only of per-component basis.

**Comment by iangfleming** [comment]
see #186

**Comment by chrisdhanaraj** [comment]
Duplicate issue of #186
