### ISSUE TITLE
Capitalization standard is unclear for the Accordion component 

### ISSUE THREAD

**Issue by scanlana** [carbon-design-system/carbon#1850]
## Detailed description

The standard to use for capitalization of an Accordion element is unclear.  The Usage tab does not name an explicit standard for capitalization. The example on the Usage tab shows all proper names, so there's no way to infer for sure based on the example. And the Code tab has "Section 1 title, Section 2, title, etc", which again doesn't provide actionable information for the capitalization standard to use. 

> Is this issue related to a specific component?

Accordion

> What did you expect to happen? What happened instead? What would you like to see changed?

I would like the Usage tab to state explicitly which standard to use. And ideally, the example would clearly reflect the standard. 

> What version of the Carbon Design System are you using?

I checked both v9 and v10. 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I work on IoT and Maximo Asset Management products. 

## Steps to reproduce the issue

No issue to reproduce but here's a link to the relevant page in the design standard:
https://www.carbondesignsystem.com/components/accordion/code

## Additional information

- Screenshots or code
- Notes

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment]
Hi @scanlana thank you for reporting! First thing I can mention is that accordion component itself does not dictate any content. `Section 1 title`, etc. are merely examples.

But capitalization standard itself a good question, CC @IBM/carbon-designers to see if there are relevant standards/links, especially are they recently conducted audits in this area. Thanks!

**Comment by jeanservaas** [comment]
Hi @scanlana you bring up a great point... our current Carbon standard is sentence case... i.e. capitalization of only the first word of a sentence, heading etc. unless it's a proper noun. 

We do talk about capitalization here: 
https://next.carbondesignsystem.com/guidelines/content/guidance

But:
1) we're punting the user to look to the specific usage guidelines for each component (so you were right to expect that kind of guidance in the Accordion documentation)

and

 2) I don't think the guidance on this page is particularly clear

We're doing our best to achieve consistency on our site in this regard too, but we're not there yet. We will work towards improving this moving forward. Thanks so much for taking the time to feedback!

**Comment by scanlana** [comment]
Hi @asudoh and @jeanservaas 
Thanks for the speedy response! If I am understanding you correctly, we should use title case for Accordion components. Is this correct? 
Thank you!

**Comment by scanlana** [comment]
@jeanservaas
Sorry, I just re-read your response - Title case is capitalization of every major word
Server Status History

Do you mean that for the Accordion component or do you mean sentence style (first word capitalized + any proper nouns)
Server status history 

Thanks in advance for the clarification.

**Comment by jeanservaas** [comment]
@scanlana waaaaaa sorry! Didn't have my coffee. SENTENCE CASE, you are right! I meant to say sentence case:

Server status history

ps also went up there an edited it too.

**Comment by claycrenshaw** [comment]
@scanlana For future reference, capitalization rules are often listed under the Style tab (as opposed to Usage) for components. We are aware that this information architecture can be confusing, and the Carbon team is working on improving that. Thanks so much for the feedback!

**Comment by scanlana** [comment]
@claycrenshaw Thanks for the information. I always click on the Style tab, thinking that is where I should find style information, and then when I see all the CSS stuff, I decide the tab is more technical style info and isn't for me and won't have what I'm looking for. I will scroll down further next time!
I'm a technical editor, so capitalization standard is the main thing I'm typically looking for.

@jeanservaas Thanks for the quick confirmation! :)

**Comment by asudoh** [comment]
Thanks @jeanservaas and @claycrenshaw for your response and again @scanlana for bringing this up! Given it appears that code is our repo is our way to go and content in our website needs change, moved this to carbon-design-system/carbon-website#1147. Anybody please don't hesitate to speak up if this issue should be kept open.
