### ISSUE TITLE
Document public Sass API for v10

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1856]
In the past, we've exposed our Sass API in general for folks to use. As we are guarding against breaking changes, this has been causing troubles when it comes to build breakage. As a result, we should document our public Sass API in `src/globals/scss/README.md` (at least initially) as a point of reference for people to understand what we support from the Sass perspective.

**Comment by asudoh** [comment]
@joshblack Thank you for entering this! Another thing that's great to have is [`@access private` in SassDoc](http://sassdoc.com/annotations/#access) - Many consumers tend to look at our code and try to use our Sass features, because they are looking for efficient ways to reuse our style guide features (Bluemix style guide, IBM Design Language).

**Comment by joshblack** [comment]
Good call! Do you know of a stylelint rule like we have in eslint for JSDoc that we could use?

**Comment by asudoh** [comment]
Good question - My quick googing for forcing SassDoc for StyleLint didn't seem to reveal any, but good to monitor for that.

**Comment by joshblack** [comment]
That's a bummer 😞 definitely agreed though, this would help out a lot. Will make sure to add it to elements as well 👍

**Comment by joshblack** [comment]
Next steps:

- [ ] Document the current API that we need to support in v10 (#1626)
- [ ] Define the public API based off of the full API
- [ ] Add annotations for public variables, mixins, and functions
- [ ] Create README for talking about our public API strategy

**Comment by jnm2377** [comment]
Sass doc example: https://github.com/JLammeer/bootstrap-sassdoc/blob/master/documented-items/_variables.scss#L2490

**Comment by joshblack** [comment]
Primer CSS: https://github.com/primer/css

**Comment by asudoh** [comment]
The first-round research:

# Variables

## Public

* Theme tokens
* Spacking tokens
* Setting variables
  * `$css--body`
  * `$css--font-face`
  * `$css--plex`
  * `$css--helpers`
  * `$css--reset`
  * `$css--typography`
  * `$feature-flags`
  * `$css--use-experimental-grid` (Deprecated)
  * `$css--use-experimental-grid-fallback` (Deprecated)
  * `$css--use-layer`
  * `$prefix`
* Most of type settings
  * `$font-family-mono` (Deprecated)
  * `$font-family-sans-serif` (Deprecated)
  * `$font-family-serif` (Deprecated)
  * `$font-family-helvetica` (Deprecated)
  * `$base-font-size`
  * `$font-size-map`
* Special temporary variables
  * `$imported-modules` - exports mixin is brittle esp. when it's used in selectors, requiring control of "already imported" list from * application code
* Others
  * `$deprecations--entry`
  * `$deprecations--reasons`

## Private

Most of temporary variables (e.g. for functions/mixins):

* `$unicodes`
* `$families`
* `$fallbacks`
* `$weights`
* `$default-feature-flags`
* `$did-warn-diverged-feature-flags`
* `$box-shadow*`
* `$layer-shadows`
* `$breakpoints` (Deprecated - Do we want control of breakpoint list from application code BTW?)
* `$padding`
* `$z-indexes`
* `$deprecations-message`

# Mixins

## Public

Most of them:

* `css-body`
* `helvetica-font-face` (Deprecated)
* `css-helpers`
* `plex-font-face` (Deprecated)
* `reset`
* `typography`
* `text`
* `placeholder`
* `box`
* `focus`
* `rotate`
* `hidden`
* `button`
* `deprecate`
* `skeleton`
* `light-ui` (Deprecated)
* `exports`
* `layer`
* `padding`
* `breakpoint` (Deprecated)
* `max-breakpoint` (Deprecated)
* `typescale` (Deprecated?)
* `helvetica` (Deprecated?)
* `font-family` (Deprecated?)
* `line-height`
* `font-smoothing`
* `letter-spacing`
* `font-size` (Deprecated?)
* `type-style`

## Private

* Experimental theme mixins

# Functions

## Public

Most of them:

* `feature-flag-enabled()`
* `z()`
* `rem()`
* `em()`

## Private

Temporary functions:

* `merge-feature-flags()`
