### ISSUE TITLE
Update font family usage from elements in v10

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1857]
We currently are defining our own Plex strategy for `@font-face` blocks, this issue is for migrating to the elements approach which pulls from google fonts. The general strategy for integration should follow this pattern:

- Identify file where font-face is being included
- Add tests to prevent regression and document public API
- Add elements feature behind X feature flag
- Add tests for experimental features behind flag

The `@font-face` approach from `@carbon/type` is documented [here](https://github.com/IBM/carbon-elements/tree/master/packages/type#font-family)

**Comment by emyarod** [comment]
Related: #1837

it seems we still aren't pulling in the italic font unless I am overlooking something

**Comment by joshblack** [comment]
Should be pulled in, mixin itself is: https://github.com/IBM/carbon-elements/blob/master/packages/type/scss/font-face/_sans.scss with italic for light, normal, and semibold. Is it using the type styles? If not, then might not be referring to the correct font family.

**Comment by emyarod** [comment]
yeah I thought this was a global import https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_css--font-face.scss#L78

does it need to use a specific type style to be using that font though? I figured anything with `bold` or `italic` for example should be using the correct font face

**Comment by asudoh** [comment]
@emyarod Looking at https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.32/packages/type/scss/font-face/_sans.scss#L61-L226 - Would you want to articulate why you got an implression that italic fonts are not pulled in...? Thanks!

**Comment by emyarod** [comment]
@asudoh it doesn't seem to be rendering properly (ref https://github.com/IBM/carbon-components/issues/1837#issuecomment-464826640) but it could be that I was not correctly using the mixin

**Comment by asudoh** [comment]
Got it @emyarod - Don't hesitate to create a reduced case if you see the issue again!

**Comment by emyarod** [comment]
@asudoh I think [this](https://github.com/IBM/carbon-components/issues/1944#issuecomment-468055824) is another example of our italic fonts not being used, or am I missing a type related mixin?

**Comment by asudoh** [comment]
@emyarod Debugging your link revealed that the culprit is [`.bx--form-item`](https://github.com/IBM/carbon-components/blob/v9.80.0/src/components/form/_form.scss#L116), which uses deprecated `@include font-family`. `@include carbon--font-family()` seems the direct successor, and I see many of our codebase have migrated to `@include type-style()`. That said, it's likely that we need to collaborate with our designers to figure out the right type token. CC @joshblack to see if it's correct. Refs #1916 and #1945.
