### ISSUE TITLE
Using Object.assign in JS code breaks in IE11

### ISSUE THREAD

**Issue by ryan76** [carbon-design-system/carbon#186]
The use of `Object.assign` in JS code without a polyfill breaks in IE11. The object-assign polyfill was removed from the bluemix-components code before changing to carbon-components in: https://github.ibm.com/Bluemix/bluemix-components/commit/9fe93fcc9cf6c94166efdf93da789ff36be2f984#diff-cdb22c353cb80d123893d9f188477d1b

Components using the older code with the polyfill worked correctly.

**Comment by asudoh** [comment]
HI @ryan76 beginning in 7.x, carbon-components is no longer shipped with polyfills. Your application need to include polyfills of your choice. The list of polyfills needed for carbon-components can be found in: https://github.com/carbon-design-system/carbon-components/blob/master/demo/polyfills/index.js

@chrisdhanaraj Is “no polyfill” change in 7.x documented somewhere? I could find migrate-to-7.x.md files only of per-component basis.

**Comment by chrisdhanaraj** [comment]
@asudoh I... thought we wrote this but looking now we didn't actually. I'll add it to our sprint this week to document

**Comment by iangfleming** [comment]
Also just a ntoe @ryan76's issue is actually with the React components. We discussed it last week and we're working on a fix.

**Comment by asudoh** [comment]
Great thanks @chrisdhanaraj and @iangfleming for the follow-up!
