### ISSUE TITLE
Date Picker - experimental component (feedback from review)

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1862]
From @laurenmrice on Nov 15, 2018 - Not sure if it's still valid, though:

- [x] Take off blue hover on all calendar icons in input fields. There should be no hover.
- [ ] ~Change weight of header (month) to 600 from 700.~

**Comment by asudoh** [comment]
Refs [IBM/carbon-components#1749](https://github.com/IBM/carbon-components/issues/1749)

**Comment by laurenmrice** [comment]
@asudoh These are still valid ^. Josh may have some more updates on Date picker from our last component review.

**Comment by emyarod** [comment]
I believe the points from the latest component review were addressed in https://github.com/IBM/carbon-components/pull/1789 but I was not aware of the November review feedback so I'll take a look at it

**Comment by tw15egan** [comment]
I don't think we are utilizing 700 font-weight?

**Comment by tw15egan** [comment]
Question for @IBM/carbon-designers, why are we pulling in 700 font weight in the components, but on the next site, we are saying we only use 600? 

https://next.carbondesignsystem.com/guidelines/typography/overview

<img width="747" alt="screen shot 2019-02-21 at 1 27 57 pm" src="https://user-images.githubusercontent.com/11928039/53196034-99beb400-35dc-11e9-8303-011f0d5f5a5d.png">

**Comment by aagonzales** [comment]
I'm not sure what's happening there. The font family is also `IBM Helvetica` which isn't right. Those look like really old styles.

**Comment by tw15egan** [comment]
Whoops my bad, that's the old path...

Here is the correct one 😅 
<img width="257" alt="screen shot 2019-02-22 at 10 03 30 am" src="https://user-images.githubusercontent.com/11928039/53254531-23c45680-3689-11e9-986e-9b2abaa1dcfa.png">

The point is, referencing 700 in the code will just use the 600 weight, so is the change from 600 - 700 correct?

**Comment by aagonzales** [comment]
Yup!
