### ISSUE TITLE
Text flows outside modal window

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#187]
What was the reasoning behind removing the `overflow-y` on the modal content in this commit? It caused a regression in my project.

Commit: https://github.com/carbon-design-system/carbon-components/commit/2612b2da591d7840c17bc9ad705e693a2ed70c8a#diff-d662c14c5dcd7e4b41028bf60b9bc77bL94

For example:
![screen shot 2017-06-19 at 2 10 30 pm](https://user-images.githubusercontent.com/17085131/27299110-324cadce-54f9-11e7-9938-532a775f8abd.png)

**Comment by hellobrian** [comment]
Sorry about this regression, at the time it looked like `overflow-y: auto` wasn't needed and was removed but I didn't resize the browser drastically enough to see it was preventing that text flow from happening. I'll have a patch out really soon.

**Comment by hellobrian** [comment]
Merged the fix. Should be available in `v7.10.3` once master branch is done with Travis CI build
