### ISSUE TITLE
Update focus outline color token for v10 in "focus-outline" mixin

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#1887]
When function is used in v10 components it's calling deprecated tokens. We need to add a conditional to use v10 tokens if feature flags is true.

```
@mixin focus-outline($type: 'border') {
  @if ($type == 'border') {
    outline: 1px solid $brand-01;
  }

  @if ($type == 'blurred') {
    box-shadow: 0 0 0 3px $focus;
    outline: 1px solid transparent;
  }

  @if ($type == 'outline') {
    outline: 2px solid $brand-01;
    outline-offset: -2px;
  }

  @if ($type == 'invalid') {
    outline: 2px solid $support-01;
    outline-offset: -2px;
  }

  @if ($type == 'reset') {
    outline: 2px solid transparent;
    outline-offset: -2px;
  }
}
```

**Comment by asudoh** [comment]
@shixiedesign Any ideas on what the corresponding `v10` color tokens for above, especially `$brand-01`? Thanks!

**Comment by shixiedesign** [comment]
@asudoh We've got a `$focus` token for only focus outlines! 

| White | G10 | G90 | G100 |
| --- | --- | --- | --- |
| Blue 60 | Blue 60 | White | White|
