### ISSUE TITLE
bug(dropdown): unexpected width change

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#1889]
Dropdown changes width suddenly when user pick an option. This shouldn't happen. Dropdown width should stay constant before and after a selection: 

![dropdown-gif](https://user-images.githubusercontent.com/15144993/53289973-6d816f80-3763-11e9-8704-1b05cdfc3a01.gif)

**Comment by asudoh** [comment]
Hi @shixiedesign thank you for reporting! Moved to carbon-design-system/carbon-website#1191 as this issue happens on our website but not on our vanilla dev env.

**Comment by emyarod** [comment]
should we add a minimum width to the dropdown component?
