### ISSUE TITLE
adding a href to the Tab component does not change the url when the tab is clicked

### ISSUE THREAD

**Issue by allison-palum** [carbon-design-system/carbon#1892]
## Detailed description

When I add a 'href' to the Tab component, the href shows up when I inspect element, but clicking on the tab in the web page does not update the url

> Is this issue related to a specific component? Tab (https://www.carbondesignsystem.com/components/tabs/code)

> What did you expect to happen? What happened instead? What would you like to see changed? I expected the tab to update the url when clicked, but it does not. 

> What browser are you working in? Chrome

## Steps to reproduce the issue

1.  Create an instance of the Tabs component
2.  Inside that Tabs component, add a Tab component with a desired 'href' and 'label'. 
3.  run project and go to web page. click on on the tab you created and see if it updates the url

**Comment by tw15egan** [comment]
Tabs are supposed to be used "to quickly navigate between views within the same context". Navigating via a tab does not seem like it fits the UX pattern for this component. What is your use case for this functionality?

**Comment by cwgorman** [comment]
For example, something like the behavior on the Carbon documentation site:

![image](https://user-images.githubusercontent.com/8108669/53502927-15a57a00-3a7d-11e9-93c5-1b653cdcb1b3.png)

These tabs change the URL.

**Comment by dakahn** [comment]
👋 Closing this as resolved. If that's not the case I'm happy to reopen 🏄
