### ISSUE TITLE
Button: Secondary button hover state does not match design specs

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#1894]
## Detailed description

When hovering over the secondary button there is a border that does not match the background color of the button

> Is this issue related to a specific component?

Button

> What did you expect to happen? What happened instead? What would you like to see changed?

Based on the design spec there should not be a visible border

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Assets Library (PAL)

## Steps to reproduce the issue

1. Hover over a secondary button

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox

## Additional information

![image](https://user-images.githubusercontent.com/1275779/53351074-8d916a00-38ee-11e9-8103-3bb1bb3dc9ce.png)

**Comment by asudoh** [comment]
Hi @elizabethsjudd 👋 thank you for reporting! @IBM/carbon-designers Would you agree with the point raised here...? Thanks!

**Comment by jeanservaas** [comment]
Thanks for reporting @elizabethsjudd! This is a known issue an we are working on a fix!

@asudoh I'm going to close this and track all button issues including this one here
https://github.com/IBM/carbon-components/issues/1928
