### ISSUE TITLE
Accordion missing layout global dependency

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#1899]
## Detailed description

I recently updated to the latest version of `carbon-elements@9.81.1` on NPM with `components-x` set to `TRUE`. This update gives me a `ModuleBuildError: Module build failed`

![image](https://user-images.githubusercontent.com/3793636/53357901-80777980-38f4-11e9-8ea2-b662f1006cfd.png)

It appears to be missing a reference to the `max-breakpoint()` mixin.

## Steps to reproduce the issue

0. Download latest `carbon-components`
1. Import accordion `SCSS`
2. Set `component-x: true`
3. Build `SCSS`

Reduced test case in CodeSandbox
https://codesandbox.io/s/5339km19x4?fontsize=14

## Possible solution
I can quickly put a pull request in for this (see #1901), but I believe the `src/components/accordion/_accordion.scss` is just missing the following line...

```scss
@import '../../globals/scss/layout';
```

**Comment by joshblack** [comment]
Hi @photodow! 👋 ~Do you also have the grid flag turned on?~ Nevermind, saw there was a codesandbox 😄
