### ISSUE TITLE
Separate the "Menu" part of the overflow menu into its own component

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#1903]
### Summary

Currently there is an "Overflow menu" component, but there are lots of situations to need a menu without necessarily wanting the overflow icon or having an overflow use case. 

For example, a menu attached to another kind of text, icon or dropdown, in a toolbar (File menu), attached to a combo-button or multi-select button and so on. Or other potential on-click or on hover behaviour. See for example the array of use cases supported by the Material Design menu component: 
https://material.io/design/components/menus.html#anatomy

### Justification

By providing just the menu component separately to the overflow, designers and developers would have more flexibility to add menus where it makes sense and innovate on interactions. 

### Desired UX and success metrics

Provide a menu component, without the associated overflow icon. 

### "Must have" functionality

A Design Library component comprised of the menu component without the overflow icon. Keep all the existing capability of the existing menu - dividers, delete actions etc.

Might also include the ability to have a second or third level of hierarchy, for example 
![image](https://user-images.githubusercontent.com/6569324/53361082-dea85a80-38fc-11e9-98bd-b8c9d5a2295a.png)

But this is not the main thrust of this request. 

### Specific timeline issues / requests

No specific timeline

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Overflow menu as of today does't contain much code that is specific to its menu body - Only code for keyboard navigation as the matter of fact. Also, overflow menu has its own specific requirement, which is, locating menu body distant from the trigger button.

Given that, it doesn't make much sense to just extract out the code of menu body. From what I read the issue description, I see one possible underling requirement, which is, more flexibility of creating the trigger button.

The content of the trigger button, as well as multiple-level menu, would be a discussion of how it fit into the design scheme of Carbon, and thus it's likely that discussion with our designers is needed. Also you may be interested in our [UI shell](http://react.carbondesignsystem.com/?selectedKind=%5BExperimental%5D%20UI%20Shell&selectedStory=Header), which has a menu that may be closer to what you desire.

**Comment by tomlroach** [comment]
Thanks @asudoh 
Where is the git repo to suggest a feature to the designers? I assumed this was it.

**Comment by asudoh** [comment]
You are correct that you can discuss a feature addition here unless:

* It's specific to a specific [React](https://github.com/IBM/carbon-components-react)/[Angular](https://github.com/IBM/carbon-components-angular), etc. variants
* It's with a full-spec'ed suggested design but not with any code (https://github.com/carbon-design-system/carbon-contribution is the right repo if so)

Given yours doesn't seems to be either of above, I guess this repo is still the right place. Given you seem to agree that your issue no longer is a technical discussion extracting out our overflow menu body and reusing it, would you mind creating another issue that more describes the feature you desire? Thanks!

**Comment by aagonzales** [comment]
Related issue: https://github.com/carbon-design-system/carbon/issues/2447
Toolbar could potentially use this other type of menu.

**Comment by aagonzales** [comment]
We'll need to define:
- what the types of menu triggers will be (I think it should always include a trigger and not just the menu bottom part). 
- how its different than a dropdown and when something like this would be appropriate. 
- what types of content can go inside of it (toolbar example would imply more than just text, but other icons as well, it also has different orientations and sizes as well as grid as well as lists).

**Comment by aagonzales** [comment]
Slack converstation: https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1562005419053700

**Comment by asudoh** [comment]
Good points @aagonzales - Wrt the 2nd bullet there is a dev-perspective difference, which is, dropdown is non-floating and overflow menu is floating. "Floating" is our word for a technical meaning, to make it a plain wording, floating menu works for `<table>` but more (again technically) complex.

**Comment by aagonzales** [comment]
Split button / contextual menu also potentially related: https://github.com/carbon-design-system/carbon-contribution/issues/18

**Comment by joshua-vaughn** [comment]
still needed, stalebot

**Comment by joshua-vaughn** [comment]
still needed, stalebot

**Comment by joshua-vaughn** [comment]
still needed, stalebot

**Comment by joshua-vaughn** [comment]
Someone should unplug stalebot

**Comment by joshua-vaughn** [comment]
hey

**Comment by aagonzales** [comment]
Next steps:
- Research type of menu component this could be
- Design and create spec (either through contribution or Carbon)

Related issue:
- Text toolbar https://github.com/carbon-design-system/carbon/issues/2447

**Comment by carmacleod** [comment]
See also https://github.com/carbon-design-system/carbon/issues/3371

**Comment by laurenmrice** [comment]
Also related #6830

**Comment by aagonzales** [comment]
@tomlroach this has finally been added! it is in experimental right now but will soon be stable with the v11 release. 

See https://github.com/carbon-design-system/carbon/pull/7350
