### ISSUE TITLE
fix[Loading Component]: both loading and inline loading component tweaks

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1906]
## fix[Loading Component]: small loading and inline loading

- [x] Get rid of clunky toggle state button and try a timer Loading...loading... success 

- [x] Convert button to `sm` variant

- [x] Check small loader (both loading and inline loading) stoke weight looks narrower than spec (it should be 3px wide in spec and 16px square in total)
![image](https://user-images.githubusercontent.com/43144260/53366078-68115a00-3908-11e9-98e8-59f08cd2087a.png)

- [x] Small loader is missing the gray section at the start, then gray section suddenly appears.
![gif](https://user-images.githubusercontent.com/15144993/53371042-e07e1800-3914-11e9-9bd2-eedadc5bf983.gif)

- [x] Don't we need a failure state beside success state? See failure state design below:
![image](https://user-images.githubusercontent.com/15144993/53371378-b0834480-3915-11e9-940d-5a5d179b0bc7.png)

**Comment by dakahn** [comment]
Hey, I'll pick this up again if nobody's jumped on it yet. Looks like @jeanservaas had a question about adding a new error state to the loader? @shixiedesign

**Comment by dakahn** [comment]
In hindsight a timer on the success state would make the page less usable for screen reader users. We could alter our implementation to not have the success state called out, but that would make that component a do as we say not as we do situation in terms of a11y implementation.

So I've gone with the alternate suggestion of using a smaller button in the example. Linked in [this PR here](https://github.com/carbon-design-system/carbon-website/pull/1264). @jeanservaas Let me know if that's sufficient or if you want to go in a different direction. ☮️

**Comment by dakahn** [comment]
@alisonjoseph Reaching the edges of my Gatsby knowledge here as far as the `bx--loading__background` circle getting onto the page after the `bx--loading__stroke` (referencing the 3rd checkbox). And ideas about why that's happening?

**Comment by alisonjoseph** [comment]
This is a weird one, I believe this is an issue with the css animation. I made the `.bx--loading__stroke` transparent and the `bx--loading__background` red so I could see what was going on with the background, and the background is animating at the beginning at the same speed as the stroke, so it looks like it isn't there. 
![loading](https://user-images.githubusercontent.com/2753488/53778588-eb135100-3ec2-11e9-9e56-c447b340a278.gif)

**Comment by dakahn** [comment]
That's so funny -- cool I'll look into the animations and debug from there.

**Comment by shixiedesign** [comment]
> Looks like @jeanservaas had a question about adding a new error state to the loader?

I realize adding an error state would be an added feature. @dakahn Let's not worry about for v10!
