### ISSUE TITLE
[Audit] Link Component

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1909]
- [ ] Active style needs to be updated to underline variant https://github.com/IBM/carbon-components/issues/1900

**Comment by emyarod** [comment]
is the link active style not currently showing as an underline?

**Comment by joshblack** [comment]
I believe there is a black box that appears, according to @laurenmrice in #1905. Is this not in newer versions?

**Comment by joshblack** [comment]
cc @dakahn hope you don't mind but I made this issue for part of breadcrumb work 👍 Feel free to re-use for your audit with @laurenmrice!

**Comment by emyarod** [comment]
I can't replicate that behavior, so it might be based on an older version of the component (we need to make sure we're checking the latest versions)

but on the latest version there is a blue box (from `:focus`) and an underline (from `:active`). I'm assuming we want the `:active` styles to be identical to the `:focus:active` styles then?

**Comment by laurenmrice** [comment]
can you link me to the latest version? @emyarod

**Comment by emyarod** [comment]
~~I don't believe we build the latest versions automatically, so using recent netlify link is probably the closest we can get to building locally~~

I lied we have this link https://the-carbon-components.netlify.com/ @laurenmrice

**Comment by joshblack** [comment]
Yeah, looks like I was on a stale one! Sorry about the confusion, updated the original checklist with the PR 😄 Will update breadcrumb accordingly 👍

**Comment by asudoh** [comment]
Thanks @joshblack! Do you think we are all set with this issue...? (I have that impression as I see the updated issue description shows everything is done)

**Comment by joshblack** [comment]
Sure, we can close and folks can follow up with further ones 👍

**Comment by joshblack** [comment]
Actually, wait, it seems like the issue still occurs in link right?

![image](https://user-images.githubusercontent.com/3901764/53369823-b545f980-3911-11e9-99a6-4bf2216fc4f1.png)

**Comment by joshblack** [comment]
It's when the `a` has `focus` and `active` at the same time, I believe, that's causing this. Most often this occurs on mouse click, I believe.

**Comment by joshblack** [comment]
Related: https://github.com/IBM/carbon-components/issues/1900

**Comment by laurenmrice** [comment]
Yes, just reviewed the updated link and it is still happening in Firefox and Chrome. Safari looks fine though.

**Comment by emyarod** [comment]
strange, this is what I'm seeing on Chrome, Firefox, and Safari for `:focus:active` state

![image](https://user-images.githubusercontent.com/8265238/53372934-c4c94080-3919-11e9-9511-441a427bf5e5.png)

![image](https://user-images.githubusercontent.com/8265238/53372985-e9bdb380-3919-11e9-92c6-fdf55e9e0cd5.png)

![image](https://user-images.githubusercontent.com/8265238/53373021-fd691a00-3919-11e9-820a-0d2cd299662e.png)

**Comment by asudoh** [comment]
@joshblack Where did you see the issue? Website, our dev env, or anywhere else...? Thanks!

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/53373553-60a77c00-391b-11e9-8ab6-75122fa9a5d0.png)

From the link provided above that's publishing from master, using Chrome, toggling active/focus using dev tools. Also verifying with mouse click

**Comment by laurenmrice** [comment]
For context on this issue: this is how I am seeing both Focus and Active across Chrome, Firefox and Safari currently:
![artboard](https://user-images.githubusercontent.com/43969356/53373714-e0cde180-391b-11e9-8cca-3e615fda3b00.png)

**Comment by emyarod** [comment]
strange that we are performing the same test in the same environment and getting different results, is there some weird caching going on? I have cache disabled and test in private browsing/incognito

**Comment by asudoh** [comment]
@emyarod I'm seeing the issue with hover/active enabled (using `:hov` feature at the top right in Chrome DevTools' Elements) tab, at https://the-carbon-components.netlify.com/component/link--default.html, even in Incognito with cache disabled. Would you try the same? Thanks!

**Comment by emyarod** [comment]
yes @asudoh all of my screenshots were from triggering the pseudo classes in browser devtools at that link. I thought the feedback was about `focus` and `active` states and not `hover`, though

**Comment by asudoh** [comment]
@emyarod What I meant by `:hov` is a button icon (for forcing `:focus`/`:active` state, etc.) - Does it make sense to you?

**Comment by emyarod** [comment]
yeah that's how I have been applying pseudo classes to test, but I was just referring to your mention of hover/active vs focus/active earlier in this thread

**Comment by jeanservaas** [comment]
Captured in 
https://github.com/IBM/carbon-components/issues/1900
