### ISSUE TITLE
[Audit] Toggle Component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1911]
#### Off state
- [x] background should be `$ui-04`
- [x] circle should be `$ui-03`

#### On state
- [x] background should be `$support-02`
- [x] circle should be `$icon-03` (white)

#### Disabled state
- [x] background should be `$disabled-01`
- [x] circle should be `$disabled-02`

#### Mini toggle
- [x] Missing green check mark

<img width="502" alt="screen shot 2019-02-25 at 4 17 20 pm" src="https://user-images.githubusercontent.com/2753488/53372589-dd852680-3918-11e9-94a8-04bcc4e27daa.png">

fyi @shixiedesign

**Comment by shixiedesign** [comment]
Color token assignment for Toggle has updates! See https://github.com/IBM/carbon-components/issues/1731
![image](https://user-images.githubusercontent.com/15144993/53425682-179f0880-39ab-11e9-999c-205241e99d3e.png)
