### ISSUE TITLE
[Audit] Tile Component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1912]
- [x] Selected: on-click border should be gray 100, `$ui-05` or `$interactive-02` token
- [x] Selected: hover icon color should be `$icon-02`

<img width="861" alt="screen shot 2019-02-25 at 4 28 31 pm" src="https://user-images.githubusercontent.com/2753488/53373189-68b2ec00-391a-11e9-8184-646e7c0d674b.png">

fyi @laurenmrice

**Comment by emyarod** [comment]
related https://github.com/IBM/carbon-components/issues/1749
