### ISSUE TITLE
[Audit] Radio Button: component audit

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1926]
## Radio button audit

- [x] check focus state width ( it looks like 3px and it should be 2px)

- [x] check distance from label to radio button; should be 8px (looks like more)

- [ ] vertically center radio buttons in component display window (they're riding high now -- this is a website display issue, not a component issue

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/afccd0f0-011a-4eb5-85be-d9f9e1b2bfd8)

- [x] @aledavila to be consistent can we say "Radio button label" instead of the word "heading?" We don't use that anywhere else.

- [x] Also, I'm sorry, this is my bad... but looking at the spec... the focus state IS 3px, it's just that the black outline overlays the 3px stroke... in yours, the outline just becomes a 2px blue 60 stroke... but that's not the spec

<img width="351" alt="image" src="https://user-images.githubusercontent.com/43144260/53666722-8773f400-3c34-11e9-8567-fa67927a5a90.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/43144260/53664875-75438700-3c2f-11e9-9779-382b721c99b4.png">

- [ ] Not sure if it's just me, but I don't see a focus state in Safari

- [x] Also, we're not offering this to anybody right? It's whack.
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/43144260/53665032-e08d5900-3c2f-11e9-9f10-8af14c5bbf4f.png">

- [ ] One last point, and this applies to most of the components... can we vertically center them in the component display window? So many of them ride high (not just here but on next)

**Comment by asudoh** [comment]
Reopening due to remaining designers' comments: https://github.com/IBM/carbon-components/pull/1962#issuecomment-468804994

**Comment by aledavila** [comment]
Editing to add comments to this issue. Will look at it today
