### ISSUE TITLE
[Audit] Date picker

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#1927]
![date picker - white theme](https://user-images.githubusercontent.com/11670886/53443571-9c9d1880-39d1-11e9-9bca-ea61f50f9dee.png)

![date picker - specs - white theme](https://user-images.githubusercontent.com/11670886/53443570-9c048200-39d1-11e9-956d-d8dace05a3da.png)

**Comment by aagonzales** [comment]
**Changes needed:**
- [x] use Plex mono `$code-02` for input fields
- [x] `.#{$prefix}--date-picker__icon` should have `fill: $icon-01`
- [x] `span.flatpickr-next-month` and `previous-month` need background on hover `$hover-ui`
![image](https://user-images.githubusercontent.com/11670886/53444061-cefb4580-39d2-11e9-90e2-921d7d80207c.png)
- [x] year arrows should be `$icon-01` by default and then `interactive-01` on hover
![image](https://user-images.githubusercontent.com/11670886/53444147-ffdb7a80-39d2-11e9-98dd-17ccba9397fb.png)
- [x] `bx--date-picker__day endRange` should have 2px  `$interactive-01` border
As-is:
![image](https://user-images.githubusercontent.com/11670886/53444331-7d06ef80-39d3-11e9-83ef-c92de9a15450.png)
To-be: 
![image](https://user-images.githubusercontent.com/11670886/53444376-9c058180-39d3-11e9-8a1e-316f791d18e1.png)
- [x] `today` should be using `font-weight: 600`

**Comment by andreagmann** [comment]
The [documentation](https://www.carbondesignsystem.com/components/date-picker/style#typography) is not updated to reflect that Plex mono `$code-02` is being used 

Similarly, the documentation for Slider and Number input are not updated.

<img width="1288" alt="Screen Shot 2020-05-20 at 6 53 51 PM" src="https://user-images.githubusercontent.com/14081333/82514796-7af2ea00-9acb-11ea-849b-fdcfac18b41d.png">
