### ISSUE TITLE
fix[button]: component audit

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1928]
## fix[button]: component audit

- [x] Buttons should use tokens for colors, not call out to `ibm-color` variables directly 

- [x] Ghost button needs to have 16 px in these areas as speced; remove the minimum width rule from only our ghost buttons to acheive this (See spec)

![image](https://user-images.githubusercontent.com/43144260/53445295-da03a500-39d5-11e9-96fa-d525c5d3a0c7.png)

- [x]  Remove dark boarder around secondary button on hover (there should be no visible boarder based on design spec) 

- [x] Fix small secondary button hover state too, it has the same problem as the large one with the dark boarder on hover

![image](https://user-images.githubusercontent.com/43144260/53452817-06282180-39e8-11e9-8952-0438fee0075d.png)

**Comment by emyarod** [comment]
progress from orphaned PR https://github.com/IBM/carbon-components/pull/1880 has been moved to https://github.com/IBM/carbon-components/pull/1930

**Comment by emyarod** [comment]
related: #1935

**Comment by emyarod** [comment]
do we still have primary danger buttons in v10? or is that for v9 only?

**Comment by jeanservaas** [comment]
we still have primary danger buttons yes, only the secondary danger buttons have been removed

**Comment by emyarod** [comment]
@jeanservaas is this the right document for tokens https://ibm.ent.box.com/notes/356863403068? I'm not sure which tokens to use for primary danger buttons

also for the secondary button hover border, I'm not able to replicate it (unless I'm looking at the wrong part)

![image](https://user-images.githubusercontent.com/8265238/53840150-003dbd80-3f5f-11e9-8632-3a86ea3f0442.png)

**Comment by jeanservaas** [comment]
Quick spec fix for ghost button -- @laurenmrice has also updated it in the kit

![image](https://user-images.githubusercontent.com/43144260/53841969-ce7b2580-3f63-11e9-9523-172c6b063bca.png)

- [x] there is 8px of space between the 16px icon and the type (not 4px)

- [x] remove extra right padding on ghost button hover... it only has 16px of padding after the icon

![image](https://user-images.githubusercontent.com/43144260/53841270-f7022000-3f61-11e9-9f98-bb04dfeaf99f.png)

**Comment by jeanservaas** [comment]
@emyarod Danger button tokens:

$text-04

(if there's an icon, it would be $icon-03)

core background color:
$support-01

hover color:
$hover-danger

active state:
$active-danger
