### ISSUE TITLE
feat: Expose Sass Utilities

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon#194]
## Overview

```gherkin
Feature: Compile a list of all Sass Utilities to Carbon Design System site
  As a UI Dev who uses Carbon
  I want to quickly access all available Sass Utilties from Carbon Components
  So that I am consistent with Carbon Design principles
```

## Other

There should be a way to see a compiled list of Sass Utilities on the www.carbondesignsystem.com.  Currently we document everything in a markdown file: https://github.ibm.com/Watson/watson-console-ui/blob/develop/docs/shortcuts/sass-shortcuts.md.  That file doesn't include component-specific utilities, but those are also really good to have as well.

It would be really cool if the content is automated with every new update to the codebase.

## Requirements

- [ ] Make a page on Carbon Design System site that includes a list of all Carbon Sass utilities from everywhere in the library.  Wherever there's a compiled list of reference works
- [ ] Each utility could also display their code implementation, usage, reference to file name or anything that could be relevant to know for a developer
- [ ] The Sass utilities page automatically updates its content for each new release, so users always know latest utilities to use

**Comment by marijohannessen** [comment]
Going to close this as I think we're exposing the most important CSS variables now in the Getting Started docs.
