### ISSUE TITLE
[Audit] Text input

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#1944]
![text input - white theme](https://user-images.githubusercontent.com/11670886/53527358-5c5e9880-3aac-11e9-8b20-637ae42f34a6.png)

**Comment by aagonzales** [comment]
**Changes:**
- [x] error icon should be 16px on the right
![image](https://user-images.githubusercontent.com/11670886/53524316-b196ac00-3aa4-11e9-9015-8cceedfd3e3e.png)
- [ ] margin-bottom between label with helper text should be 2px
![image](https://user-images.githubusercontent.com/11670886/53524376-db4fd300-3aa4-11e9-81a1-2ebfe35bff61.png)
![image](https://user-images.githubusercontent.com/11670886/53524402-eacf1c00-3aa4-11e9-8c36-4762cc86f6cc.png)
- [ ] make sure helper text is using the `$helper-text-01` type token. Line height is wrong here, also not pulling in the true italic
![image](https://user-images.githubusercontent.com/11670886/53525012-81e8a380-3aa6-11e9-880d-b7c0bc550b30.png)
- [x] Remove icon from disabled state
![image](https://user-images.githubusercontent.com/11670886/53525299-089d8080-3aa7-11e9-888a-0b4356aeff4c.png)

**Comment by emyarod** [comment]
> * margin-bottom between label with helper text should be 2px

~~@aagonzales is this change for all form elements or is this only for text inputs? also, does it include labels without helper text?~~

never mind it looks like the remaining two changes were also requested for text area, so those are probably a form-level change. Can we move these points to a new issue for the Form audit?

**Comment by aagonzales** [comment]
There was no existing issue for form on the airtable so I made one. Looks like you're the assigned dev on that one too @emyarod 

https://github.com/IBM/carbon-components/issues/1966
