### ISSUE TITLE
Experimental components: Complete transition to v10 mixins, functions and variables

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1945]
## Summary

#1943 sends us a signal that some of our experimental components implementations still use mixins, etc. in `v9` era. This issue is for tracking an effort of migrating those to `v10` ones.

## Detailed description

> Describe in detail the issue you're having.

Some of our experimental components implementations still use mixins.

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

Experimental component styles don't use `v9` Sass features, unless there is no `v10` counterpart.

**Comment by asudoh** [comment]
To migrate away from `@include font-family` and `@include typescale()`, we need to undefstand what type token should be applied to below places. Found those by searching through the codebase referring to `v9` type mixins. @IBM/carbon-designers can we have up-to-date info for those...? My apologies if it's communicated to dev (e.g. for some components), or there should be an easy way to see them in specs already:

* Code snippet (`.bx--btn--copy__feedback`)
* Date picker (`.bx--date-picker__month .flatpickr-current-month`, `.flatpickr-month .flatpickr-current-month`, `span.bx--date-picker__weekday`, `span.flatpickr-weekday`, `.bx--date-picker__day`, `.flatpickr-day`)
* Dropdown (`.bx--dropdown`, `.bx--dropdown-list`)
* Form (`.bx--form-item`, `.bx--label .bx--tooltip__trigger`, `.bx--form__helper-text`)
* Combo box, React dropdown, multi select (`.bx--list-box__label`, `.bx--list-box__selection--multi`, `.bx--list-box__menu-item`)
* Modal (`.bx--modal`, `.bx--modal-header__heading`)
* Number input (`.bx--number input[type='number']`)
* Pagination (`.bx--pagination`, `.bx--pagination-nav`, `.bx--pagination-nav__page`)
* Progress indicator (`.bx--progress`)
* Radio button (`.bx--radio-button__label`)
* Search (`.bx--search-input` for small/large/extra-large variants)
* Select (`.bx--select-input`, `.bx--select--inline .bx--label`)
* Structured list (`.bx--structured-list`)
* Tabs (`.bx--tabs`, `.bx--tabs__nav`, `.bx--tabs__nav-item`)
* Tag (`.bx--tag`)
* Text area (`.bx--text-area::-webkit-input-placeholder`)
* Toggle (`.bx--toggle__text--left`, `.bx--toggle__text--right`)
* Click-to-open tooltip (`.bx--tooltip p`)
* Definition tooltip (`.bx--tooltip--definition`, `.bx--tooltip--definition__bottom p`, `.bx--tooltip--definition__top p`, `.bx--tooltip--definition .bx--tooltip__trigger`)
* Icon tooltip (`.bx--tooltip--icon__bottom`, `.bx--tooltip--icon__top`, `.bx--tooltip--icon__bottom:before`, `.bx--tooltip--icon__top:after`)
* UI shell (various places)
* Various buttons in components (`@mixin button-reset`, used e.g. for `.bx--accordion__heading`, `.bx--tooltip__trigger`)

Thanks!

**Comment by aagonzales** [comment]
We have a type migration doc set up, both with a direction migration of style and what should be in the components:
 https://ibm.box.com/s/b87gaanauy23o7ko321cohoarq07u0rj

**Comment by joshblack** [comment]
@asudoh they should be in the specs that folks are using for review too 👍 

![image](https://user-images.githubusercontent.com/3901764/53582064-6502ad80-3b44-11e9-849b-6b77a0000100.png)

In this case, you can see it in the appearance panel with `body-long-01`

**Comment by asudoh** [comment]
Thanks @aagonzales and @joshblack for pointing these out! Very helpful and created #1965 for areas that recent audits don't cover.
