### ISSUE TITLE
[Audit] Text area

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#1946]
![text area - white theme](https://user-images.githubusercontent.com/11670886/53527545-e27adf00-3aac-11e9-8286-4dd7a319b622.png)

**Comment by aagonzales** [comment]
**Changes:**
- [x] Missing error icon in `invalid` state
![image](https://user-images.githubusercontent.com/11670886/53527642-25d54d80-3aad-11e9-8d96-567bdfa61838.png)
- [ ] `margin-bottom` between label with helper text should be 2px
![image](https://user-images.githubusercontent.com/11670886/53527701-4c938400-3aad-11e9-889b-a01883900be1.png)
- [ ] make sure helper text is using the `$helper-text-01` type token. Line height is wrong here, also not pulling in the true italic

**Comment by emyarod** [comment]
> * Missing error icon in `invalid` state

how should the content behave around the error icon? I'm not sure we can have the text wrap around the icon like the mockup is doing. If I'm not mistaken, we would probably have to apply right side padding down the whole input field.

![image](https://user-images.githubusercontent.com/8265238/53598448-5fb85980-3b6a-11e9-8694-b90009db6680.png)

Would we want to do that or is there a different behavior we can implement?

> * `margin-bottom` between label with helper text should be 2px
> * make sure helper text is using the `$helper-text-01` type token. Line height is wrong here, also not pulling in the true italic

let's move these changes to a Form component audit issue if that hasn't been created yet
