### ISSUE TITLE
Change to _css--reset.scss is invasive / overreaching

### ISSUE THREAD

**Issue by ctcpip** [carbon-design-system/carbon#195]
Upgrading to the latest version today has effectively broken our application.  

I've pinned it down to the following change from #76 

commit 636bf25d64dfbdc086b01aeb8540c62f995eb6e5

```diff
-  @if global-variable-exists(css--reset) == true and $css--reset == true {
+  @if global-variable-exists(css--reset) == false or $css--reset == true {
```

This is overriding our styles due to specificity.  While this can be fixed by specifying `$css--reset: false;` in a file that is imported before any of the carbon imports, I don't think this should be necessary.

I would argue that best practices for components would be to have their styles namespaced and to not pollute the global namespace with style overrides like this.  Moreover, breaking changes in upgrades should be communicated and workarounds should be documented.

While I did find a workaround, this gives me pause as to whether our team should bother using these components directly at all, and just rely on the assets from the design kit.

**Comment by ctcpip** [comment]
This also contradicts the documentation which states:

> When the variable is not declared at all, then nothing gets included from that SCSS file.

**Comment by ctcpip** [comment]
and...

> Namespacing
> Carbon Components are built to be included individually and not clobber global styles - all class attributes are prefixed by the bx-- moniker.

**Comment by chrisdhanaraj** [comment]
@ctcpip - this was a error in the original communication of what the variable was supposed to do, sorry! The system is designed to give the majority of people out of the box functionality - i.e., include a css reset. If you don't want that functionality, simply declare `$css-reset: false` (as I've seen you already do). We'll update the documentation to ensure to clarify this.
