### ISSUE TITLE
Footer: Deprecate for v10?

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1950]
## Summary

Seems that [`_footer.scss`](https://github.com/IBM/carbon-components/blob/v9.80.0/src/components/footer/_footer.scss) does not have any code for `v10`. Wondering if this means that footer is being deprecated for `v10`. CC @IBM/carbon-designers

**Comment by aagonzales** [comment]
I believe so. I think this is the footer for the Cloud configuration pages. I'm not even sure its used anymore and if it is it should be a cloud add-on.

**Comment by tw15egan** [comment]
I say we remove it 💀
