### ISSUE TITLE
Unclear capitalization standard for table titles

### ISSUE THREAD

**Issue by scanlana** [carbon-design-system/carbon#1951]
## Detailed description

The Usage tab for the Data Table component has the following guidance:

**Column headers should be in title case. All other table text should be sentenced case.**

What about the Table title? The example on the Code tab seems to imply that it should be sentence case, but I'm not sure that everyone is going to think about the title as falling under "all other table text". Also, there's a tendency to want to use title capitalization for titles. 

Plus, "sentenced" should be changed to "sentence.

**Comment by asudoh** [comment]
Moved to carbon-design-system/carbon-website#1227 - Thanks you for reporting!
