### ISSUE TITLE
Disable editing of the year in the calendar?

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon#1952]
To disable/not allow user to type-in invalid/junk characters in the year field.

I have raised an issue with flatpickr.js and they confirmed that this was a bug which its fixed a day ago and its pending release.
https://github.com/flatpickr/flatpickr/issues/1672
So want to understand that once flatpickr releases how and when it will be available in carbon datepicker?

<img width="309" alt="image" src="https://user-images.githubusercontent.com/22093326/53561620-613b4f00-3b75-11e9-82f2-a674a970952b.png">

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Once Flatpickr release a fix you can try creating a PR updating [the version of Flatpickr dependency](https://github.com/IBM/carbon-components/blob/v9.80.0/package.json#L37). Hope it clarifies things!

**Comment by abbeyhrt** [comment]
Closing this issue! It is fixed via #2947! 🎉
