### ISSUE TITLE
[Audit] Tooltip

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1954]
## Interactive Tooltip

- [x] Button should not have vertical padding

Expected:

![screen shot 2019-02-28 at 10 23 39 am](https://user-images.githubusercontent.com/3901764/53581307-f113d580-3b42-11e9-8711-f714da4b4707.png)

Actual:

![screen shot 2019-02-28 at 10 23 42 am](https://user-images.githubusercontent.com/3901764/53581311-f3762f80-3b42-11e9-935d-7e3c3079e086.png)

- [x] Label should be label-01, #565656

- [x] Icon should use #565656, what's the token @jeanservaas?

- [ ] What should the vertical distance be between the tooltip box and the icon? Seems like it's 13px in the spec but 16px in the implementation cc @jeanservaas 

- [ ] Test needs to use `body-long-01`

## Icon Tooltip

- [x] Direction of tooltip seems flipped, should go down but is going up
- [x] Height should be 24px, right now it's 32px
- [x] Text should use `body-short-01` token

## Definition Tooltip

- [x] Tooltip background should not have right padding

Expected:

![screen shot 2019-02-28 at 10 30 33 am](https://user-images.githubusercontent.com/3901764/53581825-edcd1980-3b43-11e9-9474-5983bf33e020.png)

Actual:

![screen shot 2019-02-28 at 10 30 37 am](https://user-images.githubusercontent.com/3901764/53581831-f0c80a00-3b43-11e9-9220-3d7b15b6de08.png)

- [ ] Tooltip text should be centered

- [x] What type style should this use @jeanservaas? `body-short-01`? In spec it's IBM Type C

**Comment by jeanservaas** [comment]
@joshblack 

- Icon token for (#565656) should be $icon-02


Also, I reuploaded the spec, but I noticed another discrepancy in the spec and the changelog i think, 

- definition tooltip and interactive tooltip should be calling $label-01 ( you can see all type tokens spec'd in the file now... everything inside the tooltip is $body-short-01 any type outside the tooltip... we're going to go with $label-01 right now, even for the definition tooltip. Sorry for the confusion!

![image](https://user-images.githubusercontent.com/43144260/53598341-0f40fc00-3b6a-11e9-9013-c2daa223a135.png)


![image](https://user-images.githubusercontent.com/43144260/53598450-60e98680-3b6a-11e9-8c3a-c53b2234874e.png)

- Also, is this the distance you were asking about?

![image](https://user-images.githubusercontent.com/43144260/53598618-d6555700-3b6a-11e9-862d-b4918b923220.png)
