### ISSUE TITLE
[Audit] Content Switcher

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#1956]
**States:**
- default
- Content Switcher
- Content Switcher with Icon

🖼 **Sketch file:** https://ibm.ent.box.com/file/336719415945

![content switcher - white theme](https://user-images.githubusercontent.com/43969356/53840608-2e6fcd00-3f60-11e9-8e49-5120c9205396.png)

**Comment by laurenmrice** [comment]
**Changes:**
- [x]  dev: needs to be 40px in height
- [x]  dev: 4px corner radius
- [x]  dev: text should be left-aligned, 16px padding

![content switcher - specs - white theme copy](https://user-images.githubusercontent.com/43969356/53841066-69263500-3f61-11e9-98a0-84e82dbb10c2.png)

- [x]  dev: update color & type tokens / verify we're using latest tokens. color `text-02` default / `text-01` hover for default tab
- [x]  ~dev: arrow keys not working to change focus—should it remain as is, or sync with tabs/etc and support arrow key navigation?~ 
    - _arrow keys to change focus not expected/required from a11y standpoint here. unless from a UX perspective we want to make the decision to add it in (to sync with how Tabs does it), we aren't going to implement it here in ContentSwitcher._ 
- [ ]  design & dev: section widths
    - check github issue: https://github.com/IBM/carbon-components/issues/1863 discussion around tab & component width
