### ISSUE TITLE
[Audit] Pagination

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#1957]
**States:**
- default

🖼 **Sketch file:** https://ibm.ent.box.com/file/348603408615

![pagination - white theme](https://user-images.githubusercontent.com/43969356/53896572-e2716680-3ff9-11e9-8fa2-5825d14e8c71.png)

**Comment by laurenmrice** [comment]
**Changes**
- [x]  design: spec out hover state for arrow buttons
- [x]  dev: implements hover state on arrow buttons
![screen shot 2019-03-06 at 10 24 15 am](https://user-images.githubusercontent.com/43969356/53896634-02a12580-3ffa-11e9-927f-93cb70991b4c.png)

- [x]  dev: all text should be body-short-01 (14px)
- [x]  dev: verify appropriate color tokens
- [x]  dev: double-check spacing (should equate to `rem(16px)`)
![pagination - specs - white theme](https://user-images.githubusercontent.com/43969356/53896674-16e52280-3ffa-11e9-921f-a0580505f092.png)

- [x]  design: spec out larger click targets for select component
- [x]  dev: implement larger click targets for select element (see updated spec)

**Comment by lovemecomputer** [comment]
fixes up for review at https://github.com/IBM/carbon-components/pull/2076

**Comment by asudoh** [comment]
Closing as #2076 has been merged. @lovemecomputer don't hesitate to speak up if this shouldn't have been closed yet. Thanks!
