### ISSUE TITLE
Multi select: Color of trigger button right when the dropdown gets open

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1964]
At https://github.com/IBM/carbon-components/pull/1752#pullrequestreview-207647237 from @laurenmrice:

When the dropdown is open, the top row is still getting a selected color. It needs to be background field-01 and have an underline of ui-03
![screen shot 2019-02-25 at 1 27 23 pm](https://user-images.githubusercontent.com/43969356/53370405-479acd00-3913-11e9-93a1-518050ba7bdb.png)

**Comment by asudoh** [comment]
Follow-up question from @asudoh:

> Hi @laurenmrice the darker background color seems to be associated with hovering over, instead of the open state. That makes me wonder if the hover over color should be eliminated, or you are suggesting the hover over color should be gone as soon as the menu is open - What do you think? Thanks!

**Comment by laurenmrice** [comment]
@asudoh We still need the hover color (hover-ui, #E5E5E5) when hovering over options inside of the dropdown. The top field needs to always remain the field color (field-01, #F3F3F3) regardless if it is open or closed.

**Comment by asudoh** [comment]
@laurenmrice Thank you for clarifying! It appears that latest style for multi select has already removed the hover-over style for the top field. You can see it at: 
https://deploy-preview-1962--carbon-components-react.netlify.com/.
