### ISSUE TITLE
Pagination: Documentation and real-world example

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1971]
### Summary

This issue is for tracking an effort of providing more documentation and a real-world example of how pagination should work.

### Justification

Pagination demo in carbondesignsystem.com does not move the page forward/backward by clicking arrow buttons. It tends to give visitors there an impression that the demo is not working (e.g. #1591).

### Desired UX and success metrics

* More "working demo" of pagination
* User of our pagination code fully understands how to use our API

**Comment by paschalidi** [comment]
@asudoh 👋 🕊 hey thanks for the amazing job you people do here! I would love to get involved and help you have better working demos for the pagination components so that visitors can have a better understanding of the use cases and api of that component. 
Can you please let me know how I could help? 
🌳

**Comment by asudoh** [comment]
Hi @paschalidi I'm late on this, but here's some more background; Pagination component itself does _not_ dictate how paging itself is done, given it involves some application-specific context. This issue is for creating a better demo.

Creating a better demo may involve creating a demo-only component like https://github.com/IBM/carbon-components/blob/v10.1.0/demo/js/inline-loading-demo-button.js. I'd imaging such component maintains row/column data for data table for each page, receiving events from pagination component, and populate DOM for table rows.

Hope this gives some ideas!
