### ISSUE TITLE
[Audit] Search

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1975]
![Large search - White theme.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/191f297b-389c-4ec3-a618-d275780aa38a)

**Comment by laurenmrice** [comment]
**Changes:**

- [x] When typing in the search field, the close icon should appear on the right handside and it should be color token icon-01 (#171717). Right now the icon that appears is a duplicate search icon.
![Screen Shot 2019-03-04 at 9.53.24 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/39a41d9e-b144-4d83-9c58-169699c17fe6)

- [x] For small search, The close icon should be 14px away from the right side so it fits directly in the focus square. ![Screen Shot 2019-03-04 at 10.20.41 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/e01adefa-23ff-4ec0-bbe0-932143050956)

- [x] The search close icon should be getting different states. These should be outlined in the specs. https://ibm.ent.box.com/file/341322158560

**Comment by alisonjoseph** [comment]
the search on the website is updated here https://github.com/carbon-design-system/carbon-website/pull/1265 the website was just pulling outdated files 

https://deploy-preview-1265--carbon-website.netlify.com/components/search/code

can you confirm it looks ok in the above link @laurenmrice

**Comment by laurenmrice** [comment]
The close icon and focus looks correct now !

**Changes:**

- [x] There should be no full hover color on the entire search or when you type in the search.
- [x] The active state for the close icon should be selected-ui color token .
