### ISSUE TITLE
Please add an autocomplete component.  This would be very useful for input/dropdown fields.

### ISSUE THREAD

**Issue by Rolando77** [carbon-design-system/carbon#198]
## Overview

Convert this issue to an **Epic** if there are multiple `Scenarios`.
Each `Scenario` should be it's own issue that belongs to this **Epic**.

{{ long description }}

```gherkin
Feature: {{feature}}
  As a {{persona}}
  I want {{need}}
  So that {{rationale}}

  Scenario: {{scenario}}
    Given {{thing}}
    When {{action}}
    Then {{result}}
```

## Other

{{ Other notes here about this User Story that does not fit within `Feature` or `Scenario` }}

**Comment by marijohannessen** [comment]
Can you please open a new issue with more information (please follow our issue template), thank you!
