### ISSUE TITLE
Long string in left nav is hidden, can not show a long word totally

### ISSUE THREAD

**Issue by Noodles006** [carbon-design-system/carbon#199]
![image](https://user-images.githubusercontent.com/8025633/27469961-5cc208e6-5824-11e7-8b0b-7453e1c57de7.png)

**Comment by hellobrian** [comment]
I'm testing this out in our vanilla and react components. I'm seeing that by default, long strings in the interior-left-nav component will wrap. Can you double-check to make sure there aren't any additional CSS styles preventing the long string to wrap?
