### ISSUE TITLE
Add option to display tabs at the bottom of the content

### ISSUE THREAD

**Issue by sbologescu** [carbon-design-system/carbon#1993]
### Summary

Currently, tabs are rendered above the content. Add an option to the Tabs component to allow rendering of the tabs below the content.

### Justification

Having the option to render tabs at the bottom of content will allow to distinguish between different types of tabbed content that is nested. That is, I can have a first level of tabs (where the tabs are rendered at the bottom of the content) and their content will have another set of tabs that are rendered above the content.

### Desired UX and success metrics

Tabs component should have a new optional property that specifies if the tabs are to be rendered at the top or bottom of the content. If not specified, it should default to the top.

### "Must have" functionality

none

### Specific timeline issues / requests

No specific deadline

### Available extra resources

none

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by emyarod** [comment]
@IBM/carbon-designers can anyone confirm that we will support this use case before development begins?

**Comment by jeanservaas** [comment]
Hi @sbologescu,  Thanks for opening a dialogue about this!

Could we get some more clarity around where this component would be used and possibly some visuals or a design spec?

1) I just want to determine if tabs are really the appropriate component to use in the scenario that you're describing 

2) Apart from just switching the orientation, we'll also have to consider the position of the blue 60 highlight bar on the selected tab as well

**Comment by sbologescu** [comment]
Hi @jeanservaas ,

Thank you for looking into this.
This requirement is driven by the need to have a way to display nested tabular content. An example of that would be a top level group of tabs that represent workspaces and the content of each workspace tab contains another set of tabs that represent a set of reports. Having the top level tabs at the bottom will help with visually distinguishing between the two types of tabs (workspaces vs reports).
Here is a sandbox (based on the one originally built by @jnm2377 ) to exemplify the usage:
https://codesandbox.io/s/km4vpq14po

Best regards,
Seb
