### ISSUE TITLE
component audit [form]: Form fixes

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#1997]
### 1. Show correct container background color for form light

- [ ] Form light white fields needs to be displayed on the correct gray 10 container background, otherwise it looks like we're suggesting that you use white fields on a white background

<br>

**Problem:**
Form Light is currently confusing because it is not displayed on a Gray 10 background (See below)

<br>

**Current state on netlify:**

<br>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c70f4967-7e63-41b2-b57e-ca5220d7dc2f)

###  **Fix:**

Both of these variations of form are available on in Carbon's White theme because both of them are technically on a white UI background.

**1. Form spec**

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/447ea101-8e47-4d85-8025-376724916930)

**2. Form light spec**

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/8dfb29c1-1f54-43e9-b749-6a47c64a9340)

<br>

### 2. Remove right padding on helper text in mobile

**Problem:**
Right padding is correct at all other breakpoints... we want to keep it, but allow helper text to go full screen at mobile. Otherwise we lose too much real estate. This fix needs to be made on Text Input component @aagonzales 

- [x] Remove right padding on helper text in mobile

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c33c478d-949c-4aac-89b3-c39b5a7c2bff)

<br>

### 3. Check Safari mobile... field bottoms seem to have a radius

- [x] Remove radius, or find out what's causing it (this will also relate to input components @aagonzales 

<br>

![IMG_9862.PNG](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/ce05726f-8610-4f2a-806a-1eec8bd89a7a)

**Comment by emyarod** [comment]
this would be a sitewide change since I assume we want to show the correct background color for all light theme component examples

**Comment by emyarod** [comment]
extracted point 2 to https://github.com/IBM/carbon-components/issues/2000 and point 3 will be contained in #2001

**Comment by asudoh** [comment]
Seems safe to close this issue given #2000 and #2001 has been fixed.
