### ISSUE TITLE
React version of the components

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#20]
React is a rather popular web app framework (especially for 'single-page' web apps).
It would be great if you provided a React version of the components library.

**Comment by chrisdhanaraj** [comment]
Heyo @gmosx - we actually do have one, we're working on getting it open-sourced now :) I'll message you when it clears legal

**Comment by nordangaard** [comment]
Any update on when we can expect this? :)

**Comment by chrisdhanaraj** [comment]
It's been submitted, unfortunately the process is not always the quickest. I'll check in again though

**Comment by timrbula** [comment]
Hey @chrisdhanaraj, did you hear anything back?

**Comment by hellobrian** [comment]
Hey @trb727, we just open-sourced the react components today: https://github.com/carbon-design-system/carbon-components-react

**Comment by chrisdhanaraj** [comment]
Yep, literally today! Still doing some migration things, but it'll be operational soon

**Comment by timrbula** [comment]
@hellobrian @chrisdhanaraj Awesome, great news!!
