### ISSUE TITLE
hover style incorrectly applied to a data-table-v2 nested into expandable-row-v2

### ISSUE THREAD

**Issue by marcosimioni** [carbon-design-system/carbon#2006]
## Detailed description

> Describe in detail the issue you're having.

When a data-table-v2 is nested into an expandable-row-v2, the hover styles are incorrectly applied to the nested one.

See the following codepen: https://codepen.io/marcosimioni/pen/bZqKxN (forked from https://codepen.io/team/carbon/full/gXGabM/ found here https://www.carbondesignsystem.com/components/data-table/code under the Expandable data table example)

Move your mouse on one of the "HOVER HERE" labels and observe the styles applied to the nested table.

<img width="1208" alt="wrong behaviour" src="https://user-images.githubusercontent.com/22682005/53970062-d5d03980-40f1-11e9-95bb-80e35b280e5b.png">

> Is this issue related to a specific component?

data-table-v2

> What did you expect to happen? What happened instead? What would you like to see changed?

Hover styles should be correctly applied as per this old example -> http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Nested%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

<img width="658" alt="expected behaviour" src="https://user-images.githubusercontent.com/22682005/53970182-0b752280-40f2-11e9-97eb-362845a45bf0.png">

> What browser are you working in?

Google Chrome Version 72.0.3626.121 (Official Build) (64-bit) on macOS Mojave 10.14.3 (18D109)

> What version of the Carbon Design System are you using?

v9

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! It appears that the first question is if we should support nested table. CC @IBM/carbon-designers so we can discuss for future.

**Comment by dakahn** [comment]
@carbon-design-system/design ⚡️

**Comment by laurenmrice** [comment]
Hey @marcosimioni, thanks for making this issue but Carbon will not be supporting nested data tables. If you want to implement this it will have to be managed from your side.
