### ISSUE TITLE
Bug: CSS `initial` not supported on IE11

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon#201]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/initial, `initial` is not supported at all on IE

We have the issue on IE that the pagination text are always hidden and never shown because initial is not recognized. 

https://github.com/carbon-design-system/carbon-components/blob/master/src/components/pagination/_pagination.scss

```  
.bx--pagination__text {
    @include font-size('12');
    color: $text-02;
    display: none;

    @include breakpoint('530px') {
      display: initial;
    }
  }
```
![screen shot 2017-06-23 at 10 51 53 am](https://user-images.githubusercontent.com/17915105/27489964-1a8ff928-5802-11e7-9a1f-a4f20b672093.png)

**Comment by mven** [comment]
Looks like it was "By design" for IE 11 to not support `initial` 😕 

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9528179/#comment-0
