### ISSUE TITLE
Component Sass public mixins

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2014]
### Summary

If each component had a public mixin, then those components could be included in inline theme definitions.

### Justification

Most, but not all, components have private mixins used by the feature flag, e.g. `button()` and `button--x()`.

Here's an example of defining inline themes where you'd want to call component mixins.

```scss
@import '../node_modules/carbon-components/scss/global/styles.scss';

.my-inline-theme {
  $interactive-03: pink;
  @include accordion--x;
  @include button--x;
}
```

But, since the `--x` mixins are private because they are temporary, this would cause a future breaking change.

This issue originated from the RFC to better support inline (zoned) theming where one theme can live inside another theme. https://github.com/IBM/carbon-components/pull/1872

### Desired behavior

It'd be nice to have public entry points like:

```scss
@import '../node_modules/carbon-components/scss/global/styles.scss';

.my-inline-theme {
  $interactive-03: pink;
  @include accordion;
  @include button;
}
```

Instead of authoring a component like:

```scss
// private
@mixin accordion {}

// private
@mixin accordion--x {}

@include exports('accordion') {
  @if feature-flag-enabled('components-x') {
    @include accordion--x;
  } @else {
    @include accordion;
  }
}
```

Move the feature flag inside a public entry mixin.

```scss
// private
@mixin accordion--stable {}

// private
@mixin accordion--x {}

// public
@mixin accordion {
  @if feature-flag-enabled('components-x') {
    @include accordion--x;
  } @else {
    @include accordion--stable;
  }
}

@include exports('accordion') {
  @include accordion;
}
```

If a component doesn't have experimental changes, all good. You'd keep the public mixin and have no private mixins. E.g.:

```scss
// public
@mixin accordion {
  // styles here
}

@include exports('accordion') {
  @include accordion;
}
```

There have also been requests to move all mixins to dedicated mixin files so when you `import` and use these mixins without the automatic `include`ing the component. That means each component's "index" SCSS file imports its mixins and provides the `@include exports` declaration so you could use the mixins without generating CSS from the export.

### To do

1. Every component to have a public entrypoint mixin
1. All mixins live in separate files from where they are initially included
1. Also create public mixins for where colors are set (e.g. body background color, default type colors) so you can also safely redefine those in inline themes

**Comment by asudoh** [comment]
Thank you for entering this @mattrosno!

> Also create public mixins for where colors are set (e.g. body background color, default type colors) so you can also safely redefine those in inline themes

I think this would worth another RFC.

Also from https://github.com/IBM/carbon-components/pull/1872#issuecomment-470391246 so below won't be lost:

> Should the component mixin take a theme token map as an optional argument, defaulting to the one of the applied theme?

**Comment by mattrosno** [comment]
@asudoh see PR. The `body` mixin is only non-component place that we'd want a public mixin for inline theming purposes.

> Should the component mixin take a theme token map as an optional argument, defaulting to the one of the applied theme?

@asudoh components use variables that come from many sources: global variables, component variables, `@carbon/colors`, `@carbon/themes`, etc. If this question is about creating inline themes - I wouldn't want to limit inline themes to just include `@carbon/themes` token map changes. I don't see the need to pass a theme token map into component mixins.

**Comment by asudoh** [comment]
> @asudoh components use variables that come from many sources: global variables, component variables, @carbon/colors, @carbon/themes, etc.

I'm kind of late here (my apologies), but I think you brought up a great point here; Less reliance on global variables, for example, an argument being a source of truth instead of having an unlimited possible sources, makes the code more maintainable/testable. That's why I brought up this topic. Such pattern can be found e.g. at https://github.com/IBM/carbon-elements/blob/v0.0.1-beta.1/packages/layout/scss/_breakpoint.scss#L181-L185.

**Comment by elizabethsjudd** [comment]
This is not stale.  The ability for inline-theming blocks WH from upgrading to Carbon X

**Comment by mattrosno** [comment]
Not stale.

**Comment by elizabethsjudd** [comment]
Not stale
