### ISSUE TITLE
CSS pseudo-class :not() used in multiple CSS files, but not supported in IE11

### ISSUE THREAD

**Issue by ryan76** [carbon-design-system/carbon#202]
The use of the pseudo-class :not() should be removed from all styles if IE11 is supposed to be supported, as IE11 does not support this pseudo-class.

![screen shot 2017-06-23 at 11 19 47 am](https://user-images.githubusercontent.com/3375289/27491042-5bac89c2-5806-11e7-8bd1-3abb6236a602.png)

**Comment by chrisdhanaraj** [comment]
Hey @ryan76 - that's actually only for the extended `:not` capabilities - the `:not` selector (basic, which is all we use) is supported down to IE9. 

https://developer.mozilla.org/en-US/docs/Web/CSS/:not

**Comment by chrisdhanaraj** [comment]
This is the caniuse for the spec we're using

http://caniuse.com/#feat=css-sel3
