### ISSUE TITLE
Accessibility (A11y) Improvement: enable the Enter keystroke on the IBM w3ID authentication page

### ISSUE THREAD

**Issue by jthurne** [carbon-design-system/carbon#203]
## Overview

If a user is logging into Bluemix, and that user should be authenticated with w3ID, they are first shown this page where they have to click `Sign in to IBM w3ID` in order to initiate the authentication process:

![image](https://user-images.githubusercontent.com/484822/27495913-e585eef2-5821-11e7-85fd-cb7b7d8466d2.png)

Currently, there is no accessible keyboard shortcut assigned to that button. Ideally, users could just hit Enter. Unfortunately, they must actually use the mouse to click the button. This makes authentication inaccessible to some users (and annoying to others who just want to quickly move past this page).

```gherkin
Feature: {{feature}}
  As a Bluemix console user
  I want to use the Enter key to move beyond the "Sign in with w3ID" page when authenticating
  So that I can authenticate even if I am unable to use a mouse (due to a disability or a technical problem with the mouse) and so that I can move quickly past this often-accessed screen.
```

## Other

Apologies for using IBM-specific terms. I'm sure there are generic carbon component terms for everything above, but I don't know them. Feel free to modify to make more "generic".

**Comment by chrisdhanaraj** [comment]
Hey @jthurne - while I completely agree with you, we / this repo doesn't have any say over that page unfortunately :(. Not entirely sure who the contact is for that, but I'll ask around

**Comment by jthurne** [comment]
Thanks @chrisdhanaraj. I suspected this wasn't the right place, but I don't really know where to go with it, so I'm 🤞 that you'll learn where I should take this request. :)

**Comment by hellobrian** [comment]
@jthurne The user can hit enter on that button but the user must tab to focus on the button first.
