### ISSUE TITLE
Create CHANGELOG for v10 Release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2033]
This issue is for creating the information that will be present in our CHANGELOG for the release tagged v10.0.0. Example from [v9](https://github.com/IBM/carbon-components/releases/tag/v9.0.0)

**Comment by joshblack** [comment]
# Draft

## Overview

We're excited to announce the v10 release of `carbon-components`! Please refer to [our migration guide](https://github.com/IBM/carbon-components/blob/master/docs/migration/migrate-to-10.x.md) for specific details on how to migrate to v10 for the affected components.

### Global Updates

- All components have been updated to reflect the new IBM Design Language, including updates to color, typography, motion, icons, and layout
- IBM Helvetica Neue support has been removed, please use IBM Plex instead
- Browser support for latest versions of Chrome, Safari, Firefox, and Edge.

### Components

| Component          | v10                                                                   |
| ------------------ | --------------------------------------------------------------------- |
| Accordion          | [Migrate](../../src/components/accordion/migrate-to-10.x.md)          |
| Breadcrumb         | [Migrate](../../src/components/breadcrumb/migrate-to-10.x.md)         |
| Button             | [Migrate](../../src/components/button/migrate-to-10.x.md)             |
| Carousel           | Removed                                                               |
| Checkbox           | No breaking changes                                                   |
| Code Snippet       | [Migrate](../../src/components/code-snippet/migrate-to-10.x.md)       |
| Combobox           | No breaking changes                                                   |
| Content Switcher   | [Migrate](../../src/components/content-switcher/migrate-to-10.x.md)   |
| Copy Button        | [Migrate](../../src/components/copy-button/migrate-to-10.x.md)        |
| Data Table V2      | TODO                                                                  |
| Data Table         | Removed                                                               |
| Date Picker        | TODO                                                                  |
| Dropdown           | [Migrate](../../src/components/dropdown/migrate-to-10.x.md)           |
| Fab                | Removed                                                               |
| File Uploader      | [Migrate](../../src/components/file-uploader/migrate-to-10.x.md)      |
| Footer             | Removed                                                               |
| Form               | [Migrate](../../src/components/form/migrate-to-10.x.md)               |
| Inline Loading     | [Migrate](../../src/components/inline-loading/migrate-to-10.x.md)     |
| Interior Left Nav  | Removed                                                               |
| Lightbox           | Removed                                                               |
| Link               | No breaking changes                                                   |
| List Box           | No breaking changes                                                   |
| List               | No breaking changes                                                   |
| Loading            | [Migrate](../../src/components/loading/migrate-to-10.x.md)            |
| Modal              | [Migrate](../../src/components/modal/migrate-to-10.x.md)              |
| MultiSelect        | No breaking changes                                                   |
| Notification       | [Migrate](../../src/components/notification/migrate-to-10.x.md)       |
| Number Input       | [Migrate](../../src/components/number-input/migrate-to-10.x.md)       |
| Overflow Menu      | [Migrate](../../src/components/overflow-menu/migrate-to-10.x.md)      |
| Pagination         | [Migrate](../../src/components/pagination/migrate-to-10.x.md)         |
| Progress Indicator | [Migrate](../../src/components/progress-indicator/migrate-to-10.x.md) |
| Radio Button       | [Migrate](../../src/components/radio-button/migrate-to-10.x.md)       |
| Search             | [Migrate](../../src/components/search/migrate-to-10.x.md)             |
| Select             | [Migrate](../../src/components/select/migrate-to-10.x.md)             |
| Slider             | [Migrate](../../src/components/slider/migrate-to-10.x.md)             |
| Structured List    | [Migrate](../../src/components/structured-list/migrate-to-10.x.md)    |
| Tabs               | [Migrate](../../src/components/tabs/migrate-to-10.x.md)               |
| Tag                | [Migrate](../../src/components/tag/migrate-to-10.x.md)                |
| Text Area          | TODO                                                                  |
| Text Input         | [Migrate](../../src/components/text-input/migrate-to-10.x.md)         |
| Tile               | [Migrate](../../src/components/tile/migrate-to-10.x.md)               |
| Time Picker        | [Migrate](../../src/components/time-picker/migrate-to-10.x.md)        |
| Toggle             | No breaking changes                                                   |
| Toolbar            | [Migrate](../../src/components/toolbar/migrate-to-10.x.md)            |
| Tooltip            | [Migrate](../../src/components/tooltip/migrate-to-10.x.md)            |
| UI Shell           | New, experimental                                                     |
| Unified Header     | Removed                                                               |

### Styles

- The styles that we export from `carbon-components` are now only supported from the top-level `scss` folder

| `scss` path         | v10                                                                           |
| ------------------- | ----------------------------------------------------------------------------- |
| `src`               | Deprecated in v10, use `scss` instead [Migrate](../../src/migrate-to-10.x.md) |
| `scss/globals`      | [Migrate](../../src/globals/scss/migrate-to-10.x.md)                          |
| `scss/globals/grid` | [Migrate](../../src/globals/scss/grid/migrate-to-10.x.md)                     |

#### Theming (colors)

Our theming tokens have been updated to match the new IBM Design Language colors. We've also added several new tokens to handle more use-cases, and have also deprecated our `brand-*` variables in preference of our `interaction-*` variables.

For a full set of changes, please see our [v10 color migration guide](https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-color.md)

#### Icons

#### Motion

#### Layout

**Comment by shinytoyrobots** [comment]
At minimum, https://github.com/carbon-design-system/carbon-website/pull/1375 is sufficient for changelog  for release (when that .md file is complete)

**Comment by asudoh** [comment]
Our migration guide is basically complete, can be see at: https://github.com/carbon-design-system/carbon-components/blob/v10.2.0/docs/migration/migrate-to-10.x.md

Let's track specific issues in our migration guide in new issues, if there are.
