### ISSUE TITLE
 [Audit] Dropdown error state icon

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2041]
This should be pulling the 16 icon. I think this is the old icon.

![Screen Shot 2019-03-11 at 10.08.58 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/c1df16e3-764b-4f46-95d8-f011c2fcea62)

**Comment by emyarod** [comment]
does this need to be a separate issue from #1955?

e: if it's specific to this component we can contain it within #1955 but if this is an issue that affects multiple components then we should determine which components are affected

**Comment by chrisconnors-ibm** [comment]
(looks like we still haven't quite closed the gap on clearly knowing what resource a component is using, if only in pre-GA stages.)

**Comment by laurenmrice** [comment]
@emyarod The icon is looking correct in other components like text input, progress indicator, etc. This seems to be just a dropdown issue. I will make this comment in #1955 then.

**Comment by asudoh** [comment]
Seems that the consensus if merging this to #1955 - Let's reopen if this item should be triaged separately. Thanks @laurenmrice for clarifying!
