### ISSUE TITLE
[Carbon X] Search button styles not present in search--x mixin

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#2042]
## Detailed description

The optional buttons that can be added to a `Search` component have no styles in the `search--x` mixin for Carbon X. In the React library, those buttons are referring to as `SearchFilterButton` and `SearchLayoutButton`

(See React storybook for example for the buttons I'm referring to: http://react.carbondesignsystem.com/?selectedKind=Search&selectedStory=custom%20buttons&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)

These are styles for v9 (https://github.com/IBM/carbon-components/blob/master/src/components/search/_search.scss#L113):

```
  .#{$prefix}--search-button {
    @include reset;
    border: 0;
    transition: $transition--base;
    height: rem(40px);
    width: rem(40px);
    min-width: rem(40px);
    margin-left: $spacing-2xs;
    background-color: $ui-01;
    position: relative;
    padding: 0;
    outline: 1px solid transparent;
    order: 2;
  }

  .#{$prefix}--search-button svg {
    position: relative;
    top: -1px;
    box-sizing: border-box;
    vertical-align: middle;
    transition: $transition--base;
    fill: $hover-primary;
    height: 1rem;
    width: 1rem;
}
```

However there are no equivalent styles for v10 & the buttons currently render as un-styled.

**Comment by asudoh** [comment]
Missing style for `v10`, fix will be non-breaking.

**Comment by asudoh** [comment]
Seems still valid.
