### ISSUE TITLE
Show example of Loading component with reversing animation

### ISSUE THREAD

**Issue by rororoross** [carbon-design-system/carbon#205]
## Overview

The loading spinner in the Code tab does not seem to match the .gif in the Usage tab. If you look closely you see that the spinner on the Code tab does not "reverse" like the .gif in Usage. It simply keeps spinning in the same way forever.

http://www.carbondesignsystem.com/components/loading/code

**Comment by rororoross** [comment]
Also, as far as I can tell, this is the only component that is teal, not really sure why. It's hard to see on the light background.

**Comment by hellobrian** [comment]
The reversing animation is controlled by toggling the `active` prop. 
We can probably just add an additional story that shows this animation getting toggled on and off using `setTimeout`

**Comment by hellobrian** [comment]
> Also, as far as I can tell, this is the only component that is teal, not really sure why. It's hard to see on the light background. - @rossfenrick 

☝️ Maybe @aagonzales or @tay-aitken can chime in on the color.

**Comment by aagonzales** [comment]
It's purposefully a different color so it stands out. We use blue as an "active" color. Teal is for loading and other transitional states. We used to use teal more than we do now. Teal is part of our official color palette as brand-03. Though admittedly its currently the wrong teal. Brand-03 should be #00b4a0. The correct teal should help to not blend into the background.

**Comment by tay-aitken** [comment]
@rossfenrick are you using the loader with the opacity overlay?

**Comment by rororoross** [comment]
@hellobrian not sure i fully understand, why even allow for it to be toggled off?

**Comment by rororoross** [comment]
@aagonzales yeah, using the correct teal looks much better

**Comment by hellobrian** [comment]
> @hellobrian not sure i fully understand, why even allow for it to be toggled off?

It was a really long time ago when we brought it into the library.
At the time, our understanding was that the reverse animation would be the ending animation for the Loading spinner. 

I think this is still true but technically we want to see the Loading spinner do alternating spins instead of spinning in one direction forever as you pointed out.

Here's a **demo of a Loading component with the alternating spin animation**: 

[![Edit Loading - alternating spin animation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/OY7G9x8LY)

**Comment by rororoross** [comment]
@hellobrian 💯

**Comment by hellobrian** [comment]
@rossfenrick Let me circle-back with @aagonzales to verify my assumptions about the Loading component. We can close this issue once we add an example to react storybook on how to do this.

**Comment by tay-aitken** [comment]
@iangfleming is going to write code documentation and I am going to write UX documentation for the animation.

Hoping to have these changes in a PR by the end of the [sprint 16 ](https://github.ibm.com/Bluemix/carbon-issues/issues/209)

**Comment by rororoross** [comment]
any update on this?

**Comment by tay-aitken** [comment]
hey @rossfenrick sorry I did not get to it last sprint (things were a little hectic on our team these last 2 weeks). Will address this, this sprint.

**Comment by marijohannessen** [comment]
@tay-aitken any update on this?

**Comment by tay-aitken** [comment]
@marijohannessen Nope. Hasn't been a priority so it keeps getting pushed to backlog

**Comment by tay-aitken** [comment]
Going to look into adding this to our hacktime project or making CodePen examples of all the components.

**Comment by tay-aitken** [comment]
@rossfenrick Going to look into adding this to our hacktime project of making CodePen examples of all the components. I tagged you on the issue in our internal repo.
