### ISSUE TITLE
Website Content: add information on when to use Select vs Dropdown

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#2066]
**addition request:**
- add content to advise when to use `Select` vs `Dropdown`

**reasoning:**
avoid confusion. there is currently a lot of design parity between `Dropdown` and `Select`, but the underlying code makes implementation and behavior slightly different (particularly in regards to the Inline variants). 

there is some concern that this may lead to confusion. since we hope many people that we'll never talk to will use this codebase, hopefully we can clear up any confusion in advance 😇

--- 

related:
- https://github.com/IBM/carbon-components/issues/2063
- https://github.com/IBM/carbon-components/issues/1958

**Comment by chrisconnors-ibm** [comment]
Shouldn't this be in https://github.com/carbon-design-system/carbon-website/issues

**Comment by asudoh** [comment]
Moved to: carbon-design-system/carbon-website#1584.
