### ISSUE TITLE
IE11: Icons in number input component are misaligned

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2069]
> Describe in detail the issue you're having.

The validation icon and up/down arrows are sitting too low.

> Is this issue related to a specific component?

Number input

> What did you expect to happen? What happened instead? What would you like to see changed?

Here's IE11:

![image](https://user-images.githubusercontent.com/1691245/54227092-2f0ee300-44cd-11e9-92b8-098edaff0aea.png)

Here's Chrome (expected):

![image](https://user-images.githubusercontent.com/1691245/54227111-3afaa500-44cd-11e9-9c5f-00aac43a9773.png)

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10

**Comment by asudoh** [comment]
@emyarod Would you want to look into this? Removing `position:absolute` from `.bx--number__controls` made it look a bit better, but wanted to see what the best solution would be with you. Thanks!

**Comment by emyarod** [comment]
sure @asudoh, I will take a look on IE when I have a chance

**Comment by mattrosno** [comment]
Not stale.
