### ISSUE TITLE
IE11: Tiles in grid are all collapsed

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2074]
> Describe in detail the issue you're having.

Should render in a grid.

> Is this issue related to a specific component?

Tile

> What did you expect to happen? What happened instead? What would you like to see changed?

IE11:

![image](https://user-images.githubusercontent.com/1691245/54228285-d9880580-44cf-11e9-81cc-fd87a9e7bc0c.png)

Chrome (expected):

![image](https://user-images.githubusercontent.com/1691245/54228312-e4db3100-44cf-11e9-95cc-8a359541f957.png)

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10

**Comment by aledavila** [comment]
@joshblack So my temporary proposed fix is setting a width to the .bx--grid on ie11 but I think this is an issue that extends outside of tile and is how ie11 is reading our grid.

**Comment by joshblack** [comment]
@aledavila something that may have happened is that the tile grid demo is using the old grid markup. It seems that way based on usage of the `xs` breakpoint. This was replaced by `sm` in the newer grid: https://github.com/IBM/carbon-elements/blob/master/packages/layout/scss/_breakpoint.scss#L16

**Comment by aledavila** [comment]
Oh I see I'll look into it

**Comment by mattrosno** [comment]
Not stale.

**Comment by joshblack** [comment]
Going to close this one out, seems like it's good in the React preview!
