### ISSUE TITLE
[Date Picker] Drop shadow not to spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2079]
Our date picker dropshadow is very dramatic. I inspected it, looks like we have 2 box-shadow effects. Could this be a quick fix? **Not a stop-ship** but it should be fixed at some point. 

![Mar-12-2019 23-46-30](https://user-images.githubusercontent.com/15144993/54254260-2647fc80-4521-11e9-88b7-b17eb13bc908.gif)

### Spec'ed box-shadow should just be: 

`box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);`

![image](https://user-images.githubusercontent.com/15144993/54254116-8a1df580-4520-11e9-946c-a02d698aa5fe.png)

**Comment by shixiedesign** [comment]
Not stale. Still need to fix!

**Comment by jendowns** [comment]
Hey @shixiedesign! I was curious about the proposed box shadow for this (`box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);`). 

When I was looking at the available box shadow values in this file https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/_layer.scss#L24, here's what I found:

```scss
/// Raised box shadow
/// @access private
/// @type Value
/// @group global-layer
$box-shadow--raised: 0 1px 2px 0 $box-shadow;

/// Overlay box shadow
/// @access private
/// @type Value
/// @group global-layer
$box-shadow--overlay: 0 4px 8px 0 $box-shadow;

/// Sticky nav box shadow
/// @access private
/// @type Value
/// @group global-layer
$box-shadow--sticky-nav: 0 6px 12px 0 $box-shadow;

/// Temporary nav box shadow
/// @access private
/// @type Value
/// @group global-layer
$box-shadow--temporary-nav: 0 8px 16px 0 $box-shadow;

/// Pop out box shadow
/// @access private
/// @type Value
/// @group global-layer
$box-shadow--pop-out: 0 12px 24px 0 $box-shadow;
```

So would this proposed `box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);` be a new variable in this layer file? (And if so, what should it be called?)

Or if it's not a new variable... would any of the existing variables above fit in this case?

EDIT: also the variables above use `rgba(0, 0, 0, 0.1)` (that `$box-shadow` variable), but I noticed the proposed box-shadow rule uses `rgba(0, 0, 0, 0.3)`

Thanks!

**Comment by joshblack** [comment]
Would you all have any guidance for @jendowns' comments above @aagonzales @laurenmrice ?

**Comment by aagonzales** [comment]
Those are old "layer" styles, and should have been depreciated with v10. We weren't supposed to be using them with the new design language. The forbid drop-shadow except in a few select places, like menu drawers. Otherwise we're supposed to you overlays to convey depth. That may be changing in the future, I believe Sadek is looking into this topic.


This is the one approved drop-shadow. We use it on list-box and other similar components.
`box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);`

**Comment by tw15egan** [comment]
@aagonzales taking a look, we are using `@include layer('overlay')` in components like Dropdown, Tooltip which is  

`0 4px 8px 0 rgba(0, 0, 0, 0.1)`.

 Should this be changed to `0 2px 6px rgba(0, 0, 0, 0.3);`? 

Would DatePicker then also use the new value? It is currently using `0 12px 24px 0 rgba(0, 0, 0, 0.1);`

**Comment by aagonzales** [comment]
Yup, DatePicker, Dropdown, Tooltip should all be using `0 2px 6px rgba(0, 0, 0, 0.3)`. We could make it a token or update one of the layer ones if that's better. I think it does have a greater opacity in the dark themes (.5).

Its the only drop-shadow style currently being used (in design specs) for the components.

**Comment by tw15egan** [comment]
@aagonzales Posted a PR here if you want to take a look: https://github.com/carbon-design-system/carbon/pull/5126
