### ISSUE TITLE
File uploader: Remainder of audit fixes

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#2088]
From @laurenmrice at #2048:

- [ ] For the error state, the input text needs to be disabled-02 (#bebebe). Make sure the error message text is calling caption-01 (support-01, #da1e28). ~The warning icon is pulling in the old icon, but this seems to be a global issue for components.~ The icon is correct disregard this.

- [x] So we can show a success example but we need to pull in the 16/checkmark and it should be color token interactive-01 (#0062ff) https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fcheckmark

- [x] Also make sure the loading spinner is pulling in the one that is being used on the inline loading page.

- [x] The close icon, checkmark icon and loader need to be 16px away from the right. 
![File uploader - Specs - White theme Copy 2](https://user-images.githubusercontent.com/43969356/54312597-546f2000-45a5-11e9-9dd8-3950742b2535.png)

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by emyarod** [comment]
also related https://github.com/carbon-design-system/carbon/issues/2962

**Comment by emyarod** [comment]
> For the error state, the input text needs to be disabled-02 (#bebebe)

regarding this point, is disabled-02 text on disabled-01 background enough contrast?

**Comment by emyarod** [comment]
> For the error state, the input text needs to be disabled-02 (#bebebe)

@laurenmrice regarding this point, is disabled-02 text on disabled-01 background enough contrast?

**Comment by laurenmrice** [comment]
@emyarod yes, This is how we are treating disabled input fields.

**Comment by laurenmrice** [comment]
not stale
