### ISSUE TITLE
Select: See if we can use ellipsis for truncation

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#2091]
From @joshblack at #1978:

![image](https://user-images.githubusercontent.com/3901764/54292256-d8acad80-457b-11e9-8dc5-ee3ec8d1a11b.png)

Should this have truncation styles? e.g. the ellipsis for text overflow

Note (@asudoh) - Dev's feedback is `text-overflow: ellipsis` does not seem to work there. Creating this issue just to continue the discussion.

**Comment by emyarod** [comment]
adding what I wrote in the original discussion:

I don't believe truncation styles can be implemented without hacky JavaScript. This is a native `<select>` under the hood (as opposed to our custom dropdown #1994), so we are already quite limited in what we can do to style the element, on top of the custom styles and behaviors imposed by browser vendors and operating system defaults

it's worth nothing that for example, native `<select>` on mobile platforms are more like a modal than a dropdown and that can affect how we override styling. one suggestion that was briefly discussed with @asudoh was the possibility of applying a blur effect or some kind of filter as a replacement for an ellipsis
