### ISSUE TITLE
Pagination component not displayed correctly in IE11

### ISSUE THREAD

**Issue by ryan76** [carbon-design-system/carbon#210]
Since updating to latest of carbon-components, the Pagination component is displayed incorrectly. It looks like the main change is that the `bx--pagination__left` element used to have a `bx--select` child, but now has a `bx--form-item` child.

Screenshot of older code that displayed correctly:
![pagination-with-bx--select](https://user-images.githubusercontent.com/3375289/27709040-5a468284-5ce0-11e7-9caa-298e340e8246.png)

Screenshot of new code that no longer displays correctly:
![pagination-with-form-item](https://user-images.githubusercontent.com/3375289/27709062-689d4462-5ce0-11e7-83b9-43075742cef0.png)

**Comment by tw15egan** [comment]
@ryan76 this is for the React version, correct? I don't see `bx--form-item` wrapping the select in this repo

**Comment by tw15egan** [comment]
React issue, but fix will be done in here. Thanks for catching that!
