### ISSUE TITLE
Add ms high contrast support for icons

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2104]
In https://github.com/IBM/carbon-elements/pull/388 we landed support for high contrast mode for icons when being used in a Microsoft browser. This issue is to integrate the mixin available in the latest versions of elements.

**Comment by icemanlily** [comment]
@joshblack Any update for this issue?

**Comment by shinytoyrobots** [comment]
Will need to do a patch release in elements.

**Comment by joshblack** [comment]
First part: https://github.com/IBM/carbon-elements/pull/461

Will trigger a minor release for elements, `10.1.0`.

**Comment by johnsteinbacher** [comment]
@shinytoyrobots - would you please have someone add an ETA to resolving this issue.  This is holding up AVT exit.

**Comment by shinytoyrobots** [comment]
@dakahn - you're putting [this](https://github.com/carbon-design-system/carbon/blob/master/packages/icons/scss/mixins.scss#L13-L17) into the reset file for v9 today and pushing today, correct?

**Comment by dakahn** [comment]
@shinytoyrobots Donezo! v9[ has received the relevant changes here ](https://github.com/carbon-design-system/carbon/commit/20735b4729ad6720eaa051946c6d8cec496bfe3b)🤠

**Comment by icemanlily** [comment]
@dakahn Is the new Carbon version for V9 ready to verify this issue?

**Comment by nicoxxie** [comment]
looks like I'm still not seeing the icon in the latest v9 `<Icon description={this.props.t('locked')} name='locked'/>`

![Screen Shot 2019-05-30 at 11 16 29 AM](https://user-images.githubusercontent.com/17915105/58647092-68850c80-82cc-11e9-8183-e2475b7d84cd.png)
![Screen Shot 2019-05-30 at 11 16 12 AM](https://user-images.githubusercontent.com/17915105/58647093-68850c80-82cc-11e9-9459-7a0b45ae336a.png)

this is the theme I'm using https://github.com/m-khvoinitsky/dark-background-light-text-extension

**Comment by icemanlily** [comment]
@joshblack @dakahn Could you help look at it. The issue is not resolved in the latest v9.

**Comment by joshblack** [comment]
@icemanlily are you all using the CSS reset from carbon? It was included in that block.

File: https://unpkg.com/carbon-components@9.91.3/scss/globals/scss/_css--reset.scss

At the bottom:

![image](https://user-images.githubusercontent.com/3901764/58750200-4bcc0e80-845d-11e9-9d00-da9933db95a5.png)

**Comment by nicoxxie** [comment]
@joshblack yes we have imported `@import '../../node_modules/carbon-components/scss/globals/scss/css--reset';`

here is the compiled css file running on  https://dev.console.test.cloud.ibm.com/iam/
<img width="687" alt="Screen Shot 2019-06-03 at 2 48 27 PM" src="https://user-images.githubusercontent.com/17915105/58829926-a9ec2380-860e-11e9-9f03-ca081e42feb3.png">

this icon specifically can be found on https://dev.console.test.cloud.ibm.com/iam/apikeys page

"carbon-components": {
      "version": "9.91.3"...}

FF 67.0 (64-bit) theme https://github.com/m-khvoinitsky/dark-background-light-text-extension

**Comment by dakahn** [comment]
@icemanlily Testing [IBM Cloud login flow](https://dev.console.test.cloud.ibm.com/iam/apikeys) in high contrast mode on Windows 10 using latest build of Firefox:
![2019-06-11_10_40_52-IBM_Cloud_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/40970507/59286767-f26e9700-8c35-11e9-8aec-71a49fd7b554.png)
![2019-06-11_10_42_38-IBM_Cloud_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/40970507/59286788-fa2e3b80-8c35-11e9-9519-f9d1eb63e2b7.png)

As you can see _most iconography_ seems to be taking the reset, but notably not the arrow on our Dropdown component.
<img width="378" alt="Screen Shot 2019-06-11 at 10 54 14 AM" src="https://user-images.githubusercontent.com/40970507/59287521-6cebe680-8c37-11e9-91a2-49888dbac4fb.png">

Compare to the Dropdown in [Carbon Design System v9](https://v9.carbondesignsystem.com/) in high contrast mode:
![2019-06-11_10_51_11-Carbon_Design_System_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/40970507/59287353-1aaac580-8c37-11e9-8f64-eccbc74391c2.png)

The problem seems to not be on the library side. 👍🏽

**Comment by icemanlily** [comment]
@dakahn I think the login page didn't update to the latest Carbon v9. I tried it in IAM and the arrow should be OK.
![image](https://user-images.githubusercontent.com/6970471/59318527-f49a2980-8cf9-11e9-9933-fbf562becfed.png)

But in https://dev.console.test.cloud.ibm.com/iam/apikeys . The lock icons are still missing.
![image](https://user-images.githubusercontent.com/6970471/59318607-227f6e00-8cfa-11e9-8470-052abaef4774.png)
![image](https://user-images.githubusercontent.com/6970471/59318687-6e321780-8cfa-11e9-9344-5fab2d3ef946.png)

**Comment by nicoxxie** [comment]
@joshblack sorry, maybe a dumb question, why is the compiled css file not a hex but a string? in the scss file it's `fill: ButtonText` but not `$ButtonText` if it's a variable?

**Comment by joshblack** [comment]
Hi @nicoxxie! 👋 As far as I understand (@dakahn discovered it) this is a system color variable defined in CSS2. This value is used to help with rendering the icons in high contrast mode on windows (I believe).

**Comment by emyarod** [comment]
on a side note, the `ButtonText` system color is [deprecated](https://www.w3.org/TR/css-color-3/#css-system). it seems to be supported by the major OSes still but it may cause issues on some systems

**Comment by icemanlily** [comment]
@joshblack @dakahn Seems it doesn't work for the radio button. Could you help check it?
![image](https://user-images.githubusercontent.com/6970471/59574374-94d0c380-90e9-11e9-98a5-b3bab5f2c72e.png)
