### ISSUE TITLE
[Multi select] Light variant not to spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2107]
Fix multi select, light variant, styling: 
- [ ] dropdown portion's background color should be `#fff` White, 
- [ ] dropdown portion should not have blue outline
![image](https://user-images.githubusercontent.com/15144993/54405792-9b443f00-46a5-11e9-9a4f-9b47ffcff84f.png)

**Comment by asudoh** [comment]
Thank you so much @shixiedesign for reporting! Given this is not a `v9` functional regression moving this to `v10-update` milestone, but please don't hesitate to move it work anytime you feel like we should address this before `v10` ship!

**Comment by shinytoyrobots** [comment]
Related to @emyarod's work on this component. Closing this ticket but tagging for reference.
