### ISSUE TITLE
[Toolbar] styling and interaction bugs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2108]
### Toolbar has several bugs:
![toolbar-bug](https://user-images.githubusercontent.com/15144993/54408067-507af500-46ae-11e9-8159-533baaaf990b.gif)

**Search**
- [ ] Search icon shrinks when clicked on

**Filter**
- [x] Checkmarks outside the checkbox should be removed
- [x] Dropdown of filter should be wider, or change copy to avoid line breaks. Eg. change "Filter option 1" to "Filter 1", "Filter 2"
- [x] Clicking on a checkbox should not close the dropdown. Dropdown should remain open, and reflect the result of the clicking on a checkbox, and closes when user clicks outside the dropdown or the filter button again.

**Overflow**
- [x] Clicking on the radio button inside dropdown menu should not close the dropdown. Only close dropdown when user clicks outside the dropdown, or click on overflow button again.

**Comment by asudoh** [comment]
Thanks @shixiedesign for reporting! To me shrinking icon is minor, wrapped text is middle, but everything else looks major.
