### ISSUE TITLE
[Tabs] incorrect motion with dropdown opening

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2110]
Mobile dropdown variant:
- [ ] The dropdown drawer opens without transition, but the shadow behind does! Closing animation appears fine.
- [ ] Currently chevron and drawer animates sequentially. It should be simultaneous. 
![Mar-15-2019 14-00-46](https://user-images.githubusercontent.com/15144993/54455898-d8064980-472a-11e9-90a6-415e0bd435e9.gif)

**Comment by asudoh** [comment]
@shixiedesign Thank you for reporting! Double-checking - Does this happen only with mobile?

**Comment by shixiedesign** [comment]
@asudoh Yep I believe so. No dropdown behavior at desktop size, so this is only with mobile.

**Comment by shinytoyrobots** [comment]
@emyarod - I think this will be capture by dropdown work. Closing this issue but tagging for reference.

**Comment by emyarod** [comment]
dropdown changes have already been merged in but does this issue still persist? @shixiedesign

**Comment by asudoh** [comment]
Reopening as the dropdown UI in tab code is different from our dropdown code.

**Comment by shixiedesign** [comment]
Just checked. This is still an issue in our current tab component!

**Comment by joshblack** [comment]
Closing as I believe the dropdown will be going away with the tab updates in #4758 👀
