### ISSUE TITLE
Incorrect notification icon size

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2118]
we need to refactor the vanilla component. In the [vanilla HTML](https://github.com/IBM/carbon-components/blob/master/src/components/notification/notification.hbs#L14), we are using icon helpers for 16px icons in both toast and inline notifications, but we have some [CSS rules only on the inline notification icons](https://github.com/IBM/carbon-components/blob/master/src/components/notification/_inline-notification.scss#L170-L173) which upscale the icon to 20x20. This is fine because they are SVGs, but it might be less confusing to just directly use the 20x20 icon helpers in the markup and remove those style rules, especially since they are [different in the current toast notifications](https://github.com/IBM/carbon-components/blob/master/src/components/notification/_toast-notification.scss#L151-L154) when they should be the same

Related: https://github.com/IBM/carbon-components-react/pull/2020

**Comment by chrisconnors-ibm** [comment]
@IBM/carbon-developers:
*upscaling* is always a bug; if scaling is involved it should be downscaling from the 32x32;
We created 20x20 assets for this use, so this using the right asset both corrects the bug and makes this component with its peers
