### ISSUE TITLE
[Checkbox] Disabled state color wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2123]
Checkbox disabled color not to spec. Should be `disabled-02`, not 03 which is used here:
![image](https://user-images.githubusercontent.com/15144993/54561787-70066c00-4993-11e9-9058-25f8f0961dec.png)
Spec: 
![image](https://user-images.githubusercontent.com/15144993/54561808-7eed1e80-4993-11e9-9adb-ea5d05fbcbf1.png)

Also, please double check disabled indeterminant state is also using `disabled-02` fill. It showed up in react that it's taking G100.

**Comment by photodow** [comment]
Thanks @shixiedesign I was just coming to create an issue for this. To add to this issue this is what we're seeing in ways of the disabled checkbox. While the labels look disabled, and we clearly can't interact with it the checkbox itself still looks like it can be interacted with.

![image](https://user-images.githubusercontent.com/3793636/54624601-b44d4700-4a3b-11e9-8b74-83dbd75dcb85.png)

**Comment by shixiedesign** [comment]
@photodow nice catching bug! I noticed it in React https://github.com/IBM/carbon-components-react/issues/2039 Did you see this in vanilla too?

**Comment by photodow** [comment]
Yes
