### ISSUE TITLE
[Code snippet] single line doesn't scroll to the end

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2124]
### Sngle line: 
- [ ] Cannot scroll to the end to see all of the code. Need a larger padding right I imagine. 
![Mar-18-2019 15-42-11](https://user-images.githubusercontent.com/15144993/54562206-83660700-4994-11e9-8c02-023e4004b2ed.gif)

**Comment by asudoh** [comment]
Quick look at https://the-carbon-components.netlify.com/?nav=code-snippet didn't reproduce the issue, but let's reopen if anybody sees otherwise.
