### ISSUE TITLE
Content Switcher: Remainder of audit fixes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2131]
Ref: https://github.com/IBM/carbon-components-react/pull/2038

Post v10 change:
- [ ] Clicking on each section of the content switcher in Chrome activates the focus state. Audrey said we may have to implement some kind of javascript to get this aligned across all browsers.

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
Not stale

For Chrome: this is happening in both Vanilla and React.
For Firefox: this is only happening in React, vanilla seems to be fine. Is there a fix for this?

**Comment by tw15egan** [comment]
This seems to be standard browser behavior differences for `button` elements on click, not sure if there is much use in overriding them as they could be changed in the future. Might be best to use the browser default behavior so our users have the intended experience. 

For reference: https://gist.github.com/cvrebert/68659d0333a578d75372

**Comment by laurenmrice** [comment]
ok this is fine with me,  i can close
