### ISSUE TITLE
Date picker range: clicking right icon does not open second calendar

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2137]
![image](https://user-images.githubusercontent.com/1691245/54642448-a52dbf80-4a62-11e9-8265-22f3d27615f5.png)

In both `carbon-components` and `carbon-components-react`, you can click the first icon to open the first calendar, but clicking the second icon does *not* open the second calendar.

Logging here in case it's a styling bug, or a bug from shared JS.

This appears to be a bug with v10 as v9 range picker only had one icon.

**Comment by mattrosno** [comment]
Bump?

**Comment by jendowns** [comment]
Hey @mattrosno I believe this issue was fixed in this PR: https://github.com/carbon-design-system/carbon/pull/4325

**Comment by joshblack** [comment]
Closing due to @jendowns comment above!
