### ISSUE TITLE
User Avatar component with associated menu

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#214]
How about adding a user-avatar component, that displays e.g. a photo in a roundel.
It would be great to have an associated menu, maybe similar to the overflow menu.

**Comment by bsonefeld** [comment]
Hi @gmosx , could you provide a screenshot of the intended design? And do you have design guidelines, tested outcomes of this requested pattern?

**Comment by gmosx** [comment]
Something like that:

http://hig.autodesk.com/web/components/avatars

**Comment by bsonefeld** [comment]
Gotcha! The team has talked about adding in an icon component, which may fit this need. 

We will keep this noted for future releases, but since there is no user research or to support this claim, closing this issue for now.
