### ISSUE TITLE
Select arrow needs bottom positioning

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2140]
See screenshot. "carbon-components": "9.84.12". The select's caret (happens to be inside 3rd accordion item) is higher than expected.

Notice how the `bx--select__arrow` has no bottom positioning:
![image](https://user-images.githubusercontent.com/1691245/54645745-ea55ef80-4a6a-11e9-8c69-8f3af7626b2c.png)

But it used to:
![image](https://user-images.githubusercontent.com/1691245/54645762-f80b7500-4a6a-11e9-93d0-1dd32cfb2b03.png)

This could cause migration issues.

**Comment by mattrosno** [comment]
Closing this to open as a React but, needs `bx--select-input__wrapper` class.

**Comment by emyarod** [comment]
just a heads up it should also be resolved in React https://github.com/IBM/carbon-components-react/pull/2030, but let me know if it isn't after you've updated your dependencies

**Comment by mattrosno** [comment]
@emyarod rad. I see that PR is using `bx--select-input__wrapper` class so probably good, thanks!
