### ISSUE TITLE
Syntax error in styles.scss

### ISSUE THREAD

**Issue by lirui-andy** [carbon-design-system/carbon#2143]
## Detailed description

> Describe in detail the issue you're having.
Syntax error in styles.scss

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to see changed?
Should can process by `sass` CLI

## Steps to reproduce the issue

1. npm install --save carbon-conponents
2. npm install --save-global sass
3. create a scss file `my.scss` and import the `./node_modules/carbon-components/scss/globals/scss/styles.scss`
4. run `sass my.scss my.css` and there will be an error like
```shell
sass my.scss my.css
Error: Expected '.
    $deprecations--message: '#{$deprecations--message}
                                                      ^
  node_modules/carbon-components/scss/globals/scss/styles.scss 129:55  root stylesheet
  my.scss 9:9                                                          root stylesheet
```

## Additional information
```
node -v
v10.13.0
```

- my.scss
```scss
$css--font-face: false !default;
$font-family-mono: 'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', Courier, monospace !default;
$font-family-sans-serif: 'IBM Plex Sans', Helvetica Neue, Arial, sans-serif !default;
$font-family-serif: 'IBM Plex Serif', 'Georgia', Times, serif !default;
$font-family-helvetica: 'IBM Helvetica', Helvetica Neue, HelveticaNeue, Helvetica, sans-serif !default;
@import './node_modules/carbon-components/scss/globals/scss/styles.scss';

```

If you check the source file https://github.com/IBM/carbon-components/blob/master/src/globals/scss/styles.scss , Do you think line 129 and 130 should be in one line?

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! The Sass tool for `carbon-components` is `node-sass` instead of Ruby one - That said, would you try with `node-sass`? Quickly tried the code with our toolstack and didn't see a compile error.

**Comment by lirui-andy** [comment]
Hi @asudoh , thank you for responding.  You're right, `node-sass` works well 👏

**Comment by lirui-andy** [comment]
But it's strange that `Dart Sass` really can not process the styles.scss .. But there has been an approach, let's close this thread. Thank you again.

**Comment by asudoh** [comment]
Great to hear that you saw a solution! 🎉
