### ISSUE TITLE
The data picker component incorrectly interprets dates typed in

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#2163]
## Detailed description
When I use the data picker, such as the range date picker, and I type in a value, the field incorrectly interprets my value. 

For example if I type in 09021985 (Sept 2nd 1985(, the field interprets it as 09211985 (Sept 21st 1985). See gif:

![2019-03-20 17 03 25](https://user-images.githubusercontent.com/6569324/54722458-91ea2500-4b32-11e9-983b-0a790d8a1ac8.gif)

> Is this issue related to a specific component?

The **simple date picker** doesn't seem to format dates at all (which is an inconsistency) but all the ones which do - **Single Date Picker** and **Range Data Picker** incorrectly interpret the value. 

> What did you expect to happen? What happened instead? What would you like to see changed?

In general, when I type a date into the fields, I would like it to be autoformatted correctly. currently the simple data picker doesn't format it at all

![2019-03-20 16 58 41](https://user-images.githubusercontent.com/6569324/54722617-de356500-4b32-11e9-807b-78b83fafb36a.gif)

whilst the other date pickers format it incorrectly. 
![2019-03-20 17 03 25](https://user-images.githubusercontent.com/6569324/54722638-e9889080-4b32-11e9-9dae-d8f2be286269.gif)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Specifically it's the next.carbondesignsystem.com website version. 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Go to the next.carbondesignsystem.com website and open the component page for a date picker. 
2. Type a value into the picker (rather than using the calendar UI) such as 09021985
3. The date picker will attempt to format the value, but do it incorrectly 09/21/1985

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Currently our date picker requires user to type the exact date format shown as the hint. Adding some heuristic there would be a nice addition, but we need to scope well considering different date formats in different locales, etc.

**Comment by tomlroach** [comment]
It's unusual to me that the two date pickers behave differently. 
The simple data picker doesn't try to format the date. The others (single and range) attempt to format it, but introduce _subtle_ errors users may not notice.
