### ISSUE TITLE
[Tabs] Need solution for content overflow

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2178]
When tab label is long, text just run out side tab. We should **truncate add ellipses** like how we are handling in Content Switcher:

Current:
![image](https://user-images.githubusercontent.com/15144993/54785132-6d09b680-4bf3-11e9-87db-2f26c5b62d48.png)
Should be: 
![image](https://user-images.githubusercontent.com/15144993/54785701-e7870600-4bf4-11e9-9281-8c6886692091.png)

**Comment by asudoh** [comment]
@jnm2377 Does `text-overflow: ellipsis` along with `overflow: hidden` make sense to you...? Thanks!

**Comment by jnm2377** [comment]
Yes, this works 👍
