### ISSUE TITLE
iPhone 5 Endless loading

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon#2185]
## Title: 
Endless loading in iPhone 5 when open https://www.carbondesignsystem.com

## Description: 
When I open https://www.carbondesignsystem.com page is reloading after 1 second, it is impossible to do something.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! One question - What Safari version are you using?

**Comment by chrisconnors-ibm** [comment]
@reinisg could you please provide:

Device Model Identifier: (iPhone 5-GSM North America = iPhone5,1)
Device Model Number: (iPhone 5-GSM North America = A1428)
iOS Version: (highest supported v of iOS for this device is iOS 10.3.3 (14G60))

If it is a **iPhone 5** (and not an **iPhone 5c** or **iPhone 5s**), the maximum OS is iOS 10.3.3 (14G60), and xCode no longer provides a simulator for this device. There are Simulators for iOS 10.3.1, but this is an almost 2 year old iOS version (iOS 10.3.3 was released on July 19, 2017), and likely falls outside our Safari/browser version support footprint.

**Comment by reinisg** [comment]
It is iPhone S5
iOS Version: 11.2.6 (15D100) 
Model: ME337J/A 

So, on this version will not work? 
But I will upgrade to 12.2 version and check page.

**Comment by asudoh** [comment]
Thanks @reinisg for more info! A couple of additional questions:

1. What happens if you turn on: Settings - Safari - Advanced - Experimental Features - ServiceWorkers?
2. Does the-carbon-components.netlify.com work well in that iOS environment?

Edit: Nice to see if https://gatsby-netlify-cms.netlify.com, https://gcn.netlify.com, etc. works, too.

**Comment by reinisg** [comment]
1. 'ServiceWorkers' option isn`t Experimental Features (there are 'constant properties', 'viewport fit' in green, but all other options are disabled (CSSdisplay: contents, CSS Spring Animations, Link Preload, Remove Legacy, Secure Contexts API, SubresourceIntegrity, Web Animations, WebGPU, Async Frame Scrolling))

2. the-carbon-components.netlify.com is working without reloads, but immediately I found some list of bugs (E.g. 'view full render' is over on side navigation, default tooltip is not opening - example demo video https://gofile.io/?c=Xz7y6c)
https://gatsby-netlify-cms.netlify.com, https://gcn.netlify.com - are working well.


PS - here is demo video with https://www.carbondesignsystem.com/ page endless reloading - https://gofile.io/?c=cOdXAj

**Comment by asudoh** [comment]
Thanks @reinisg! Given the-carbon-components.netlify.com does not show the problem created carbon-design-system/carbon-website#1388 to track the issue.

Quickly tried tooltip with my iPhone and it seems to work. While [our support targets latest version](https://www.carbondesignsystem.com/getting-started/faq/#which-browsers-are-supported) wrt Safari, if you still want support for your iOS version don't hesitate to create issues per-component/issue basis to track them (to see if contributors/maintainers. can make quick/reasonable fix)! Great if you can gather console log, etc if so, by something like: https://developer.apple.com/library/archive/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html#//apple_ref/doc/uid/TP40007874-CH2-SW8

**Comment by reinisg** [comment]
Thank you for information.

**Comment by chrisconnors-ibm** [comment]
I can't replicate in the iOS Simulator, Device = iPhone 5s, ios 12.2
https://ibm.box.com/s/kzsu032ywpidmz02sreskdvajasmim1m

**Comment by reinisg** [comment]
> 
> 
> I can't replicate in the iOS Simulator, Device = iPhone 5s, ios 12.2
> https://ibm.box.com/s/kzsu032ywpidmz02sreskdvajasmim1m

Yes, on 12.2 version all working fine. The bug was on 11.2.6
