### ISSUE TITLE
Tabs CSS does not cope with use of dropdown component for narrow version

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2190]
## Detailed description
The tabs component when narrower than 768px (42rem in v10) shows a dropdown like replacement. Use of an actual dropdown makes component implementation simpler as dropdown functionality only needs defining in one place.

> When using a real dropdown component for the narrow version the styling of the dropdown is compromised. Producing this effect.

> tabs component

> Use of a dropdown component should be supported.

> Chrome

> 9.87.2

> carbon-components-vue

## Additional information
Tabs issue before, with standard behaviour CSS hidden for demonstration purposes.

https://codepen.io/lee-chase/pen/aMPGNW

Tabs after fix
https://codepen.io/lee-chase/pen/MxZGpe

NOTE: The fix could be achieved by only applying bx--tabs-trigger classes when bx--dropdown is not also a class.

**Comment by asudoh** [comment]
Hi @lee-chase thank you for bringing up this topic! The idea for reusing dropdown style for narrow-mode tabs is interesting, several things comes up on this topic here:

* Would applications really like doubled markup?
* Need to get JS implementations (Vue, React, vanilla, etc...) in sync, with their API in consideration (e.g. event models, tab panel integration)
* Possible future change in narrow mode UX (If our designer comes up with a different UX for narrow mode, would we want to rip/replace the dropdown portion and probably make another component work as narrow mode tab UI?)

**Comment by lee-chase** [comment]
Good questions @asudoh 

To your first point, the double markup is a bit of a pain but a relatively small one as we're looking at a maximum of six tabs. Alternatively, we could use javascript to control the switch allowing us to refine how tabs behave when users have sidebars or other width constraints.

With regards to the API I would not expect the user of a tab component to make any changes, so the same events are raised. (This happens in the current Vue implementation). 

Yes, I would expect to replace the component based on future changes. It would be a surprise if the alternative we designed was not a component in its own right.

In general, I would like to see us re-use our components where ever possible. That includes the handlebars where it would be nice to see us use partials.
