### ISSUE TITLE
Minor bug in html on Slider component page

### ISSUE THREAD

**Issue by jarusso** [carbon-design-system/carbon#2192]
## Detailed description

In this item - https://www.carbondesignsystem.com/components/slider/code, there is a minor html "flaw"

![image](https://user-images.githubusercontent.com/8137296/54849585-1bc4fa00-4cbb-11e9-9da5-d21503e72cf6.png)

There is a "0" prefacing the label for the slider - it looks a little odd in the display (maybe it's intentional?)...anyway, this line of code

```
<label id="slider-input-box_bottom-range-label" class="bx--slider__range-label">0</label>
```

should be
```
<label id="slider-input-box_bottom-range-label" class="bx--slider__range-label"></label>
```
right?

**Comment by emyarod** [comment]
hi @jarusso thanks for reporting this. I believe this was resolved in https://github.com/IBM/carbon-components/pull/1985, but the website has not been updated to the latest version of the library

**Comment by asudoh** [comment]
https://the-carbon-components.netlify.com/?nav=slider, moving to website repo.
