### ISSUE TITLE
[Search] type should be 16 & remove zoom on safari mobile

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2200]
### 2 style bugs to Default Search

- [ ] Search bar zooms in when tapped on (Safari mobile), originally documented https://github.com/carbon-design-system/carbon-website/issues/1132 I verified it happens to the component

- [x] Currently the type size is 20px, should be 16px or `$text-01`
Current:
![image](https://user-images.githubusercontent.com/15144993/54942776-d04e5e00-4efd-11e9-9bf8-d2557c73e217.png)
Should be 
![image](https://user-images.githubusercontent.com/15144993/54942893-13103600-4efe-11e9-90b6-74a5940f7ade.png)

**Comment by dakahn** [comment]
@shixiedesign is the proposal that the user not be able to magnify their screen on safari? Does this bug not show up on other mobile browsers? What should it do?

**Comment by shixiedesign** [comment]
@dakahn sorry just saw this comment (thanks to stale bot). So the zooming issue is specific to safari mobile. User can still pinch and zoom, but tabbing into search bar alone should not change view of the page. Currently tabbing into search bar zooms in to the page, and it crops out header and other important info on the page. This behavior is not seen in other browsers. I think it's just Safari trying to have a fancy default.

**Comment by dakahn** [comment]
Oh weird. I'll look into this

**Comment by shixiedesign** [comment]
> Currently the type size is 20px, should be 16px or $text-01

@carbon-design-system/developers  Can we get at least type size bug to be fixed? It makes our "normal" search look kinda ridiculous. :pray:

**Comment by emyarod** [comment]
since #2868 resolves the text size issue, the zoom in on focus behavior should be resolved as well. I'm not seeing this on iOS Safari anymore, can you confirm this is the case on your end as well?
