### ISSUE TITLE
[Pagination] Replace the hyphen with the “en dash"

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2225]
### the hyphen between 1-10 should be 1–10 
![image](https://user-images.githubusercontent.com/15144993/55176218-bb1c3e00-514e-11e9-8b17-0bf780a58c74.png)

**Comment by emyarod** [comment]
I believe this is addressed in https://github.com/IBM/carbon-components/pull/2231, feel free to reopen the issue if the issue persists!
