### ISSUE TITLE
Design for data tree variation of the accordion

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#2230]
Rocket previously used an accordion as a type of data tree navigation. The v10 accordion moved the arrows to the right side which makes it more difficult to navigate and use as a data tree. 

This issue is to design a way to navigate similar to a typical data tree. 

v10 accordion component
![Screen Shot 2019-03-28 at 1.06.22 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/4b964b1c-1df0-4db0-9c8b-d24b07eb7b17)

data tree example
![image.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/1190af99-b124-47d8-a994-6973cbd756a3)

**Comment by emyarod** [comment]
the primary use case would likely be for displaying any sort of hierarchical organization

![image](https://user-images.githubusercontent.com/8265238/55910353-dd2cac00-5ba3-11e9-9b89-5631338952a5.png)

we could likely include things like searching/filtering and selection for parts of the tree as well

**Comment by sbologescu** [comment]
Thank you for looking into adding a tree component. This would be very useful for us.
Here is an additional requirement that would be awesome if could be added to this new component:
Ability to edit the tree structure
  1. move nodes (folders/leaves) around
  2. add/delete/rename nodes

**Comment by tdayton** [comment]
The Sun Web Application Design guidelines have a section on Tree Details: https://pages.github.ibm.com/CloudIntegrationDesign/sun-guidelines/05-navigation.html#5.4

**Comment by cal-smith** [comment]
We have a fairly basic tree-view built out in WCE addons: https://github.ibm.com/peretz/carbon-addons-wce/tree/master/src/tree-view

https://pages.github.ibm.com/peretz/carbon-addons-wce/#/tree-view

![image](https://user-images.githubusercontent.com/1744185/56918561-5a08c280-6a8c-11e9-96a3-1c653caf9720.png)

**Comment by cal-smith** [comment]
bump?

**Comment by asudoh** [comment]
Reopening given I see multiple people asking in this area recently.

**Comment by mjabbink** [comment]
This would be good addition

**Comment by JordanWSmith15** [comment]
My product (Maximo) also requires this, although not strictly a tree view. It really is an accordion inside of an accordion. The accordion allows us to place the components we need at each level (not just text), but also have the entire tree collapsed on page-load.

**Comment by asudoh** [comment]
^ Feel free to add comments with desired UX/visual to #4768. As #4768 states, nested accordion is not supported in design level, and discussion with our designer will be needed to see if there is a use case we need to accommodate around nested accordion and guidance on how to solve the problem area.

**Comment by joshblack** [comment]
Closing in favor of: https://github.com/carbon-design-system/carbon/issues/5180 👀

**Comment by tw15egan** [comment]
@joshblack has this issue been solved with https://react.carbondesignsystem.com/?path=/story/unstable-treeview--default ?

**Comment by joshblack** [comment]
@tw15egan I _think_ there is overlap with tree view but there still seems to be a use-case that was raised back in October when I re-opened it that came up in Slack (but I could be misremembering, can't find the thread now)

**Comment by emyarod** [comment]
there is a planned variant of the tree view that requires more exploration but is currently on hold. It should resolve this issue when I'm able to implement it but I believe the issue can remain open until then

**Comment by sstrubberg** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/5180
