### ISSUE TITLE
fix[component]: Overflow menu

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#2248]
## fix[component]: Overflow menu

<br>

**issue:** This is just a display example issue; Add+ in the overflow menu is not an accurate example of how we would treat text and an icon in a dropdown menu so let's remove from both React and Vanilla examples

- [x]  remove Add+ example from both React storybook and Vanilla example in component display window

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/306c1d68-84b1-43d1-b3b8-d08634ca46ac)

**Comment by asudoh** [comment]
Hi @jeanservaas thank you for reporting! It appears that a contributor (@psachs21) wanted icon support in a menu item (IBM/carbon-components-react#770). Which makes me wonder - Is there any correct way to put an icon in overflow menu item? Thanks!

**Comment by jeanservaas** [comment]
@asudoh So I just chatted with the @aagonzales and there would never be an instance where there would be just one item with an icon in the menu; which is why we don't really want to portray it that way.

Also, the item is not spaced correctly, this is the example of what icons would look like in an overflow menu from the standalone data table.

![image](https://user-images.githubusercontent.com/43144260/55352296-28e5a400-5486-11e9-8901-d70de0b2a221.png)

**Comment by jeanservaas** [comment]
This issue is not stale, just needs to be prioritzed.

**Comment by tw15egan** [comment]
@jeanservaas I'll remove this now

**Comment by jeanservaas** [comment]
Noice!
