### ISSUE TITLE
Add styles for focus class on SideNav

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon#2260]
### Summary

Need focus styles applied when a SideNav menu item is in focus similar to add styles applied on hover or when expanded. 

### Justification

Currently you are able to navigate by keyboard and even open subnav items which are not visible when focused. This is buggy behavior and not accessible. 

### Available extra resources

I have submitted a [PR](https://github.com/IBM/carbon-components/pull/2261) for this work

**Comment by joshblack** [comment]
Hi @davidicus! 👋 Thanks so much for taking the time to make this issue, we'll make sure to include this update in our UI Shell pass!
