### ISSUE TITLE
[Notification] background & dropshadow error

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2263]
**Problems:**
1. Tinted notification backgrounds are not working on G10 themes
2. Missing drop shadow

### Tinted notification backgrounds are not working on G10 themes

![image](https://user-images.githubusercontent.com/15144993/55572493-4fe1e700-56cd-11e9-9348-d2b31aa251f8.png)

Relevant discussion:

![image](https://user-images.githubusercontent.com/15144993/55572514-5c663f80-56cd-11e9-8626-f29a91885acb.png)

### Missing drop shadow
![image](https://user-images.githubusercontent.com/15144993/55572479-46f11580-56cd-11e9-839c-30e63aece3dd.png)

**Comment by emyarod** [comment]
has there been a resolution on which background colors to use for the g10 theme? also is there a box shadow mixin that we want to reuse for the notifications or are we creating a new one? I'm assuming the shadow will only apply to toast notifications and not inline notifications as well

**Comment by laurenmrice** [comment]
All notifications are changing to high contrast moments on every theme to solve these issues.^

**Comment by shixiedesign** [comment]
We still need the drop shadow though.

**Comment by emyarod** [comment]
alright I can address the drop shadow in https://github.com/carbon-design-system/carbon-components/pull/2367 as well

**Comment by shixiedesign** [comment]
Resolved!
