### ISSUE TITLE
🐛SideNav Footer is pushed off screen 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon#2268]
## Detailed description

> Describe in detail the issue you're having.

The sidenav footer is pushed off screen due to the height being set to 100% and a top margin of 3rems being applied. 

> Is this issue related to a specific component?

SideNav.js

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

1. Look at the UIShell storybook
2. See that sidenav footer is pushed off screen.

## Additional information

![image](https://user-images.githubusercontent.com/1590966/55642653-124d8e80-579f-11e9-9217-37281f78b78c.png)

**Comment by emyarod** [comment]
hi @davidicus thanks for reporting this! Just to clarify, this is only found in the React side nav right?

**Comment by davidicus** [comment]
@emyarod that is the only place I have seen it but if they are all getting the same styles I imagine it will be in the vanilla components as well.

**Comment by abbeyhrt** [comment]
Hi @davidicus! Are you still encountering this problem? I was not able to reproduce so it's possible that this has been inadvertently addressed in later versions of Carbon, let me know if that's not the case!
