### ISSUE TITLE
Breadcrumb usage lists a space efficient design, no source example given

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2274]
## The v10 breadcrumb component usage page refers to a space-efficient design, but no coded example is given.

> Not able to implement the space-efficient design.

> Breadcrumb

> Space-efficient example or documentation correction.

> Chrome

> 10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
None

## Additional information

![image](https://user-images.githubusercontent.com/15086604/55793864-ce6aca00-5abb-11e9-8477-ba4f68f1c12d.png)

**Comment by lee-chase** [comment]
Carbon components vue issue https://github.com/carbon-design-system/carbon-components-vue/issues/310

**Comment by joshblack** [comment]
@lee-chase I don't believe this is implemented yet for v10 👍 It's going to be a part of our new feature push in a minor release.

**Comment by Potato-W** [comment]
Sorry to disturb here. But I want to ask this function has been implemented now ?
@joshblack  @lee-chase  Could you please give me some help? Thanks.

**Comment by lee-chase** [comment]
@changshunwang This is still an issue and should be re-opened @joshblack @dakahn @asudoh

**Comment by Potato-W** [comment]
@lee-chase Thanks. So far I have write some code for this, I want to know is there a UX design or can be made a quick design? @carbon-design-system/design (should I @design team like this?) and then maybe I could push a contribution.

**Comment by asudoh** [comment]
@carbon-design-system/design Any quick thoughts on:

1. If this use case is valid, or long list of breadcrumbs should be avoided
2. If 1. is the former (valid), would https://angular.carbondesignsystem.com/?path=/story/breadcrumb--model be an acceptable design, or is it something design team needs to mull it over?

Thanks!

**Comment by tay1orjones** [comment]
I've opened #4815 - I didn't find this issue before I created it
