### ISSUE TITLE
Allow data table search when the user is in batch action mode

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#2275]
We currently lose the ability to search in the batch action mode when the action bar covers the search field.

How can we enable search and batch actions at the same time? 

![Screen Shot 2019-04-09 at 8.05.05 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/6c6e4378-0b6d-4447-bfed-14914ac40fff)

**Comment by asudoh** [comment]
Ping @carbon-design-system/design to see if there still is the team's interest.

**Comment by jeanservaas** [comment]
Still interested. @designertyler said that this was a product team request too -- he can't remember who. It should be in the list of pre-think Data Table enhancements

**Comment by aagonzales** [comment]
Need to figure out how to potentially show filters at the same time as batch action bar as well.
Reference: Diana Tran

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by tw15egan** [comment]
@carbon-design-system/design any updates to this?

**Comment by aagonzales** [comment]
This isn't a quick fix so we'll need to put some thought into it. I'll had it to planning for component enhancement work.

**Comment by sstrubberg** [comment]
From DataTable Backlog Grooming call:

Not particularly urgent. Seems like a low priority. Should live with core Carbon.

Needs a design spec.

**Comment by sstrubberg** [comment]
Dupe:
https://github.com/carbon-design-system/carbon/issues/11856
