### ISSUE TITLE
[Carbon 10: List] Nested item issues

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#2282]
## Detailed description
There are multiple issues with the List component specifically with nested items

> Describe in detail the issue you're having.

1. Nesting an unordered list in an ordered list (or vise versa) does not display the correct list type
1. Beyond the 2nd level of nested lists in ordered lists do not reset the counter
1. (not sure if this is intended or not) when the list item wraps to a new line it is not indented to align with the text above it (it's aligned with the item marker)

> Is this issue related to a specific component?

List

> What did you expect to happen? What happened instead? What would you like to see changed?

1. I should be able to mix and match list types when nesting lists and the user would understand what type of list it is
1. The marker for nested lists would reset the counter/be denoted differently
1. The text aligns with the text when it wraps instead of the marker

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

1. Use the HTML from the screen shot below
1. view the issues

## Additional information

Unordered list test
![Screen Shot 2019-04-10 at 11 17 56 AM](https://user-images.githubusercontent.com/1275779/55891775-24ef0b80-5b83-11e9-9fa0-f9ca617efca1.png)

Ordered list test
![Screen Shot 2019-04-10 at 11 18 06 AM](https://user-images.githubusercontent.com/1275779/55891777-24ef0b80-5b83-11e9-8475-214765e7740b.png)

**Comment by elizabethsjudd** [comment]
Not stale.  These issues are bugs not an enhancement since as users we can not properly nest lists.

**Comment by dakahn** [comment]
@elizabethsjudd Seems to me this is both a bug report and a enhancement request. But sorry if I'm missing something you're saying here. I'll ping @carbon-design-system/design so they can comment on this use case and maybe offer a solution. 👍

**Comment by elizabethsjudd** [comment]
@dakahn The main issues we are having is (1) if you nest a `ul` in an `ol` (or vise versa) they should show up as their correct list.  Right now nested lists inherit the list style of the parent despite the semantic tag and (2) having more than 2 levels in a list does not reset the counter for the list style markers for ordered lists.  Let me know if you need more clarification and we can set up a chat and I can point out the problems specifically within the screen shots.

**Comment by shixiedesign** [comment]
At least these items are bug fixes:
- [x] resetting counter on nested ordered list
- [x] indent wrapped lines

Mixing list types is okay thing to do from a design standpoint. It's not in the original spec'ed behavior, but can be added to our functionalities if development can figure out how to do it.
