### ISSUE TITLE
Vanilla tooltip content is not read by screen reader

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#2284]
Windows 7, Chrome/FF, NVDA/JAWS (did not try Mac/VO).

Run the screen reader.
Using the keyboard, tab to the [Carbon Vanilla tooltip](https://www.carbondesignsystem.com/components/tooltip/code).
"Tooltip label" is spoken, but not the content of the tooltip.

The text content is correctly spoken in the Carbon React Tooltip.

So the Vanilla tooltip needs to more closely mirror the React one.

**Comment by carmacleod** [comment]
Please do this work after fixing [this React issue](https://github.com/IBM/carbon-components-react/issues/2193), to ensure that the React markup is is clean before it is copied into the Vanilla component.

**Comment by carmacleod** [comment]
Dear stalebot,
If an issue's flags are `Severity 1`, `priority: high`, then don't mark it stale.
Thank-you.

**Comment by elizabethsjudd** [comment]
@carbon-design-system/developers do you want to assign this issue to me. I just had some HTML changes merged in to the vanilla version of Tooltip and planned on making the JS changes needed as well.

**Comment by jnm2377** [comment]
Thanks for taking this on @elizabethsjudd 🎉

**Comment by elizabethsjudd** [comment]
@carbon-design-system/design I need this question answered before I can continue... I think this is why it's been difficult getting tooltip to work with screen readers: https://github.com/carbon-design-system/carbon/issues/3100#issuecomment-504550259

**Comment by elizabethsjudd** [comment]
@carbon-design-system/developers I could use some help understanding how the events are attached to the DOM.  Everything looks like it's being triggered via focus and I need it to be on click.  Can I get someone that I can set up a meeting with.

**Comment by asudoh** [comment]
@elizabethsjudd Do these links help?

https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/components/tooltip/tooltip.js#L158-L186
https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/components/tooltip/tooltip.js#L111-L122
https://github.com/carbon-design-system/carbon/tree/v10.3.0/packages/components/src/globals/js/mixins#lazily-instantiating-a-component-upon-an-event-on-a-root-element-init-component-by-eventjs

We can do a meeting in your late afternoon if you feel you still need it. Thanks!
