### ISSUE TITLE
Create each component in CodeSandbox

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon#2285]
At the moment, whenever we request a user open an issue, we ask them to recreate their issue in CodeSandbox. We only provide a pre-built CodeSandbox for button.

This creates friction for those looking to create issues for our components, potentially discouraging community contributions.

We should create a CodeSandbox for each of our components to make recreating bugs easier.

Component list:

- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code Snippets
- [ ] Content Switcher
- [ ] DataTable
- [ ] Date Picker
- [ ] Dropdown
- [ ] File Uploader
- [ ] Form
- [ ] Link
- [ ] List
- [ ] Loading 
- [ ] Modal
- [ ] Notification
- [ ] Number Input
- [ ] Overflow Menu
- [ ] Pagination
- [ ] Progress Indicator
- [ ] Radio Button
- [ ] Search
- [ ] Select
- [ ] Skeleton states
- [ ] Slider
- [ ] Structured List
- [ ] Tabs
- [ ] Tags
- [ ] Text Area
- [ ] Text Input
- [ ] Tile
- [ ] Toggle
- [ ] Tooltip

**Comment by vpicone** [comment]
This a great idea, whoever came up with it is a genius. Excited to make some snippets for sharing in github/slack.

**Comment by asudoh** [comment]
Second to @vpicone - I think it'll make sense a lot and will e.g. make creating bug reports much easier.

**Comment by asudoh** [comment]
Keeping with maintainer's interest.
