### ISSUE TITLE
[FileUploader] Drag and drop support in file uploader

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#2288]
### Summary

This issue tracks dev effort for implementing drag and drop-based file uploader and possibly beefing up design spec (some if there) from carbon-design-system/carbon-contribution#4.

### Justification

Drag and drop-based file uploader UI has been popular these days, often provides a better user experience than letting user choose file.

**Comment by shixiedesign** [comment]
According to comment thread, Cynthia's team will build it. Just followed up to check the status on this: 
https://github.com/carbon-design-system/carbon-contribution/issues/4#issuecomment-448741476

**Comment by shixiedesign** [comment]
According to comment thread, Cynthia's team will build it. Just followed up to check the status on this: 
https://github.com/carbon-design-system/carbon-contribution/issues/4#issuecomment-448741476

**Comment by shixiedesign** [comment]
According to comment thread, Cynthia's team will build it. Just followed up to check the status on this: 
https://github.com/carbon-design-system/carbon-contribution/issues/4#issuecomment-448741476

**Comment by laurenmrice** [comment]
not stale?

**Comment by shixiedesign** [comment]
We should go ahead and add this to our to-do since contribution thread is 1 year old, and likely stale. We definitely want to include this feature in our core component set. Reposting spec from contribution issue: 

## Drag and drop file uploader spec, ready for dev 🤖(Updated Sept 3rd)

![File uploader—white](https://user-images.githubusercontent.com/15144993/64193881-69858700-ce43-11e9-9c2d-0420a8c7c254.png)

**Comment by shixiedesign** [comment]
We will look at it more next month. Here's some potential **Usage** tab content for Drag and Drop component once it merges. FYI @connor-leech 

https://pages.github.ibm.com/ide-design-guidelines/ide-design-guidelines-v2/patterns/uploading/usage

**Comment by asudoh** [comment]
@emyarod FYI

**Comment by vikkipaterson** [comment]
I have come across this issue and see that the file upload usage pattern we submitted is referenced above in it.  Is the drag drop component being created for your Aug release?   Is it specced out somewhere so we can see the details as we are keen to use this component (and also the proposed usage details)
Thanks :)

**Comment by shixiedesign** [comment]
Replied in Slack. Lemme know if you have suggestions for Usage guidance!
