### ISSUE TITLE
Improved a11y for icon only buttons

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2293]
Suggestion for improved a11y for icon only buttons: tooltip with icon button description which renders on hover and focus

Refs:

https://github.com/IBM/carbon-components/issues/1667#issuecomment-460348001

https://github.com/IBM/carbon-components/issues/1667#issuecomment-461562074

**Comment by shixiedesign** [comment]
@emyarod Add tooltip to Icon button to satisfy A11y requirement. 
- Should use icon tooltip: tooltip show on hover & focus
- triangle is center aligned
![image](https://user-images.githubusercontent.com/15144993/56508702-98313f80-64ea-11e9-8813-4e6bf19cdd27.png)

**Comment by elizabethsjudd** [comment]
I specifically asked for this issue to NOT be closed via #2366. There are still missing items: https://github.com/carbon-design-system/carbon-components/pull/2366#discussion_r281357778

**Comment by emyarod** [comment]
since left/right tooltip positioning is not currently supported, could we capture it in a new issue?

**Comment by elizabethsjudd** [comment]
As long as the issue is created and prioritized I'm fine with that.  It's something that is blocking WH from adopting Carbon 10 buttons.

Please add a reference to the new issue in this issue for our tracking.

**Comment by shixiedesign** [comment]
Hi @elizabethsjudd we've had left-right tooltiop request before and due to limited resources, we decided to not implement it. I reopened the issue (https://github.com/carbon-design-system/carbon-components-react/issues/1306) so you can see the discussion in the past and track it. 

Feel free to make a contribution if this is an important issue for WH to adopt. Thanks!

**Comment by asudoh** [comment]
Just to add a note here - #2581 (React 1306) now tracks for left/light alignment instead of left/right positioning. @shixiedesign please don't hesitate to correct me if I'm wrong here - Thanks!

**Comment by shixiedesign** [comment]
Due to monorepo migration changes, the issue numbers all changed 😂 Here's the issue tracking left-right tooltip: 
https://github.com/carbon-design-system/carbon/issues/2604
and Akira's lightning fast PR to address it:
https://github.com/carbon-design-system/carbon/pull/2663
