### ISSUE TITLE
Data table ascending arrow points in the wrong direction

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2296]
## Detailed description

Ascending order 'A-Z' is in a table is typically shown with an arrow pointing down. This is because the point of a chevron or caret was small and the opposite side wider. Using full arrows makes this somewhat less clear but is inconsistent with products like MS Office.

> Data table

> Arrow to point down for ascending and up for descending

> What browser are you working in? Chrome

> What version of the Carbon Design System are you using? 10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Open the data table exmaple on the carbon design systme website.
2. Click on the sort button, note set's a class ...ascending

## Additional information

![image](https://user-images.githubusercontent.com/15086604/56034614-aed3db80-5d1f-11e9-8025-c4666c12566d.png)

MS Office 
![image](https://user-images.githubusercontent.com/15086604/56034640-c90db980-5d1f-11e9-9583-4a4a5051143e.png)

**Comment by asudoh** [comment]
Ping @carbon-design-system/design to see the arrow should direct to bigger items, instead of smaller items.

**Comment by laurenmrice** [comment]
Hey @lee-chase , thanks for making this issue! I have seen data tables being sorted in many different ways, using different icons to depict ascending or descending whether it is a caret, chevron, arrow etc. We do have an ascending state (up arrow), descending state (down arrow) but we also have a third state when there is no sorting for that column (up and down arrow). We will keep this issue in mind in case other problems arise with this decision.
