### ISSUE TITLE
About ui-shell and grid (carbon 10)

### ISSUE THREAD

**Issue by elymatos** [carbon-design-system/carbon#2297]
Hi,
I'm in process to adopting Carbon for the corporate system at my work (a Federal University at Brazil). I'm in testing phase, but I have some doubts (let me know if the right place for them is not here):
- As the site says "The shell is perhaps the most crucial piece of any UI built with Carbon." I'd like to beg you to provide a functional example for ui-shell. I'm programming PHP7 and I was able to create a template for ui-shell, but some of CSS classes doesn't work as expected (at least as I expected). As you have a functional site (the Carbon site itself) I think it's not so complicated. I've trouble with the 'hamburger' menu, the responsiveness, the L0 actions and the design of sidenav, because I don't have any functional examples for that. I've used the *.hbs files in distributions as a guide, but some CSS classes seems to work slightly different at Cabon site from the distribution. I think it would be a great incentive to use Carbon in legacy applications (as my case).
- The site is not clear about the status of Grid component. To layout the site it (or some like it) is very handy. I'd like to use small tiles (like those in the IBM Cloud site) - maybe it's possible to build from scratch using Tile component, but it is so common that an example would be valuable.
- I think you have a exhaustive and great job creating the SASS files - it's handy to use not only to customize themes, but to use in different CSS (as in my case I need to adapt the existing CSS and I'd like to use the vars from Carbon). But I missed a small documentation for the other gems beyond the vars, like the functions, for example.
Thanks for the great job!
Ely

**Comment by joshblack** [comment]
Hi @elymatos! 👋 Thanks so much for taking the time to make an issue 😄 

With respect to your questions,

> I'd like to beg you to provide a functional example for ui-shell.

The UI Shell is currently in experimental status, as it moves to stable we will add documentation and other support items to help out!

> The site is not clear about the status of Grid component

Our grid is built based on the [IBM Design Language](https://www.ibm.com/design/language/elements/2x-grid-ui) and will have expanded documentation and guidance, including a role in our developer essentials work that we're putting out over the next couple of months 👍 

We do offer this interim page for folks wanting to try out grid before official docs are shared: https://carbon-elements.netlify.com/grid/examples/preview/

> But I missed a small documentation for the other gems beyond the vars, like the functions, for example.

Definitely agreed! We will 100% be adding more reference for these variables both locally through SassDoc and through other publications like Medium 😄
