### ISSUE TITLE
Code snippet visual bug with scroll bars on

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2303]
When scrollbars are turned to always on, the single line code snippet renders as follows:

![Screen Shot 2019-04-13 at 3 38 02 PM](https://user-images.githubusercontent.com/3901764/56085017-372aad00-5e02-11e9-8301-75e6cb49cfb4.png)

This seems consistent across browsers on a Mac with a mouse attached, or scroll bars set to always on.

**Comment by asudoh** [comment]
Let merge this with: #2060
