### ISSUE TITLE
Scroll bar issue with multi-line Code Snippet

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2305]
If a computer has a mouse attached, or has scroll bars set to always on, the multi line text snippet renders as follows when expanded:

![Screen Shot 2019-04-13 at 3 42 33 PM](https://user-images.githubusercontent.com/3901764/56085060-d6e83b00-5e02-11e9-86c0-c3a4398fb742.png)

This is despite not having any overflow-x content. When the content overflows, it renders as:

![image](https://user-images.githubusercontent.com/3901764/56085068-f4b5a000-5e02-11e9-9530-c32198655acc.png)

Which seems to obscure part of the ending line.

**Comment by asudoh** [comment]
Let's merge this with #2060 for now. Can re-open if team finds tracking them separately makes more sense.
