### ISSUE TITLE
Do not use/style links like buttons

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2310]
In the current implementation of the Carbon Design Language, we show examples of buttons, links and paragraphs as buttons. This is can be misleading to screen readers and certainly an issue for anyone expecting an action instead of navigation on click.

Further, this opens up the possibility of links or other being used to act as if buttons when the two are functionally different.

NOTE: 
- Links are pure navigation elements
- Buttons have special features. They perform actions which may be followed by navigation.

## Environment

> Operating system
Mojave

> Browser
Chrome

## Detailed description

> What version of the Carbon Design System are you using?
10.1.0

> What did you expect to happen?
Only buttons to be used for actions. 

> What happened instead?

Almost any  control can be used as a button

## Steps to reproduce the issue

1. On this page https://www.carbondesignsystem.com/components/button/code
2. Select the first button
3. Press space and hold space, note the button is active.
4. Release space, a click happens
5. Select a link
6. Press space, note the page jumps as links do not process space. The same is true of 'alternative' root elements.

**Comment by dakahn** [comment]
I can't quite understand what you're saying here. You mention that the way we're _styling_ our links is an issue, but then talk about screen readers. Sorry, but maybe a few questions can help clarify.

On that component page we have examples of paragraphs as buttons?
When you click a link what did you expect to happen?
When you click the button what did you expect to happen?

Is this critique/commentary on the example page itself or the component(s) implementation?
