### ISSUE TITLE
Carbon X Toggle Vertical Text Alignment in IE11

### ISSUE THREAD

**Issue by vincentsnagg** [carbon-design-system/carbon#2311]
## Detailed description

> Describe in detail the issue you're having.

In IE11, the vertical position of the label text is off between the different states of the toggle. **See image below**

> Is this issue related to a specific component?

Toggle

> What did you expect to happen? What happened instead? What would you like to see changed?

The text should be in the same place

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern and Asset Library

## Steps to reproduce the issue

1. Switch the state in IE11

## Additional information

![Screen Shot 2019-04-16 at 1 45 07 PM](https://user-images.githubusercontent.com/3158307/56232473-d643e480-604e-11e9-8194-325011463446.png)
![Screen Shot 2019-04-16 at 1 44 57 PM](https://user-images.githubusercontent.com/3158307/56232476-d9d76b80-604e-11e9-98e7-8bb98cb13ad4.png)

**Comment by elizabethsjudd** [comment]
not stale
