### ISSUE TITLE
Modal traps keydown event for `esc` key for the whole document

### ISSUE THREAD

**Issue by jeffhem** [carbon-design-system/carbon#2312]
## Detailed description
Other elements are not able to add keydown event for the escape key

The keydown event should not add to the document level and stop it from propagating

## Steps to reproduce the issue
Add a event listener for the escape keydown event to any element in the document, and it's not response to the escape key

## Additional information
the line of code doing that 
https://github.com/IBM/carbon-components/blob/master/src/components/modal/modal.js#L139

**Comment by jeffhem** [comment]
Update: The event listener was attached to the `document`

![image](https://user-images.githubusercontent.com/1653150/56240684-b960de80-6059-11e9-8cfc-9ca8a5030e4e.png)

**Comment by flannanl** [comment]
@asudoh Can you port this change to v9? I think we still have a long way to move to v10.
