### ISSUE TITLE
Data table toolbar styling broken

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2320]
## The data table toolbar styling is broken see images

> Describe in detail the issue you're having.
See images

> Is this issue related to a specific component?
Data table wtih 10.1 styling

> What did you expect to happen? What happened instead? What would you like to see changed?
Toolbar to be styled

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
React and Vue 10.0 versions with 10.1 styling.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Carbon/Vue

## Steps to reproduce the issue

1. View http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--default or build carbon-components-react against 10.1 

## Additional information

![image](https://user-images.githubusercontent.com/15086604/56346736-b92c2480-61ba-11e9-880f-7d7a59578d79.png)
![image](https://user-images.githubusercontent.com/15086604/56346770-c6491380-61ba-11e9-9995-3f11594d3254.png)

**Comment by asudoh** [comment]
Hi 👋 took a quick look at https://the-carbon-components.netlify.com/?nav=data-table, but the tool bar style doesn't seem to be broken. That made me wonder your markup matches the one in `the-carbon-components.netlify.com`? Thanks!

**Comment by lee-chase** [comment]
You would appear to be correct @asudoh looks like confusion with Carbon 9 switched code.
