### ISSUE TITLE
[Carbon X: Modal]: footer supports only 2 buttons

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#2325]
## Detailed description
> Describe in detail the issue you're having.

We need the modal styles to support a various number of buttons in the footer.  We often have modals with only 1 button (and am not sure if it's intended that it's left align in relation to the modal) and we have some scenarios where we need 3 buttons/actions in the modal footer which causes them to overflow the edge of the modal.

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to see changed?

The modal footer can support 1 - 3 buttons/actions

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library

## Additional information
Modal with 1 button
<img width="998" alt="Screen Shot 2019-04-18 at 2 12 05 PM" src="https://user-images.githubusercontent.com/1275779/56381857-fbb62700-61e3-11e9-8e58-e0889320b6b1.png">

Modal with 3 buttons
<img width="1582" alt="Screen Shot 2019-04-17 at 9 28 13 AM" src="https://user-images.githubusercontent.com/1275779/56381744-babe1280-61e3-11e9-9199-b660accfba82.png">

Use-case from actual IBM offering
<img width="1637" alt="Screen Shot 2019-04-17 at 10 51 39 AM" src="https://user-images.githubusercontent.com/1275779/56381871-096bac80-61e4-11e9-8c91-5bfb7a779e24.png">

**Comment by asudoh** [comment]
@IBM/carbon-designers Any thoughts on this...? An interesting thing I see here is that the third button in the above screenshot won't fit in the group of other two.

**Comment by aagonzales** [comment]
If a modal only has one button, the button should take up 100% of the container. 
**Side-note**: modals that have no real action to take (like ok) should be using the passive modal if its just informing the user and not asking the user to take an action.

![image](https://user-images.githubusercontent.com/11670886/56439532-0f2cc500-62ac-11e9-83c4-5cafe5882768.png)

Modal should not have 3 buttons. The "help" or other 3 non-primary action should be added as a link in the content of the modal. 

![image](https://user-images.githubusercontent.com/11670886/56439550-1653d300-62ac-11e9-813b-15d22d50c936.png)

**Comment by elizabethsjudd** [comment]
@aagonzales Thanks for the input.  We're okay at the moment to not support 3 buttons but if Carbon could still update to support the 1 button that is full width that would be greatly appreciated.

**Comment by aagonzales** [comment]
Not stale

**Comment by shixiedesign** [comment]
q: @carbon-design-system/developers do we already support 1 button modal?
