### ISSUE TITLE
DataTable: Visual bugs 

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#2330]
This is a collection of several visual bugs that have been building up in datatable.

1. Expansion and Selection icons misaligned when sorting is disabled
When both selection and expansion are enabled, and sorting is disabled, the select all header does not align with the row selection column.

### With sort (normal)
![Screen Shot 2019-04-22 at 11 23 21 AM](https://user-images.githubusercontent.com/4078018/56511136-74252c80-64f1-11e9-9c83-4af28ce68ac8.png)

### Without sort (bx--data-table--sort class removed from table)
![Screen Shot 2019-04-22 at 11 18 42 AM](https://user-images.githubusercontent.com/4078018/56511096-58ba2180-64f1-11e9-8db8-d2f5f038144d.png)

2. Toolbar button padding is incorrect, svg's butting up against adjacent button's container
![Screen Recording 2019-06-28 at 2 07 36 PM](https://user-images.githubusercontent.com/4078018/60379217-a755d180-99f4-11e9-8432-0f44068a027b.gif)

3. Search input focus too narrow (see below)

4. Action menu cast's a shadow that feels out of place, is this correct @designertyler?
![Screen Recording 2019-06-28 at 2 07 55 PM](https://user-images.githubusercontent.com/4078018/60379227-d79d7000-99f4-11e9-875a-23dd67e64b6e.gif)

5. Border bottom shows up under some header items see first and last headers of batch actions

![Screen Shot 2019-06-28 at 2 08 24 PM](https://user-images.githubusercontent.com/4078018/60379233-ef74f400-99f4-11e9-8216-cf2a37bf8c81.png)

**Comment by asudoh** [comment]
Let's keep this unless we determine this as a non-issue.

**Comment by asudoh** [comment]
Seems that the issue still exists.

**Comment by vpicone** [comment]
This is still an issue.
