### ISSUE TITLE
Add a default implementation of type tokens

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#2332]
[The v9 implementation as a reference](https://github.com/IBM/carbon-components/blob/v9/src/globals/scss/_css--typography.scss#L65-L128)

Providing a default implantation of the type tokens, targeting the "standard" type styles, would ease bootstrapping an application and could be used as a reference for implementing an application specific type hierarchy.

The v10 [migration guide for typography](https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-type.md) could also use a more complete example of how to make the transition - sample code, trade offs being made, defaults provided, etc.

**Comment by cal-smith** [comment]
bump 🤦‍♂

**Comment by cal-smith** [comment]
We'll get to it ... Eventually

**Comment by ericlowry** [comment]
Hey Folks,
  I am rendering Markdown content as part of my application.  The rendering library emits pretty plain vanilla html - `<h1>`, `<h2>`, `<ul>`, `<hr>`, etc...  It would be really nice to have a reasonable starting point for rendering "plain vanilla" html content.  I wouldn't mind wrapping the content in a div with a parent class name... `<div class="carbon--standard-html"> ... html ... </div>`

**Comment by asudoh** [comment]
CC @alisonjoseph to see how the team coped with this problem space in their MDX content.

**Comment by alisonjoseph** [comment]
We are using the type tokens https://github.com/carbon-design-system/carbon-website/blob/master/src/components/markdown/markdown.scss#L33

**Comment by cal-smith** [comment]
My bad ... can I get a re-open?

**Comment by ericlowry** [comment]
Thanks for the re-open, I am still hoping to see this added at some point soon...

**Comment by cal-smith** [comment]
Yeah ... I've been pretty busy lately, so I haven't had a chance to dig into implementation ... It should be pretty straightforward if you (or anyone else) wanted to pick it up :+1:

**Comment by cal-smith** [comment]
just bumping to keep this alive a little while longer 🙂
