### ISSUE TITLE
*EPIC* UI Shell MVP for GA

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2333]
@shinytoyrobots update to description.

This is the top level `Epic` issue for UI Shell MVP for GA. This will be scoped to what is realistic for completion and deployment with our `v10.2` release.

It might include (and these can be broken down into issues, which can be attached to the project board)

- [ ] Header component
- [ ] Top level navigation sidebar
- [ ] Product switcher
- [ ] Documentation on the Carbon Design System website

The team assigned to UI Shell for the v10.2 release will, however, conduct the final breakdown of issues.

**Comment by tw15egan** [comment]
Not stale
