### ISSUE TITLE
Design Spec for Left Panel

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2335]

**Comment by aagonzales** [comment]
## Original shell pieces:
Updating for scallop

![Left Navigation Menu - icons](https://user-images.githubusercontent.com/11670886/57636572-00fe5b80-756f-11e9-8d41-8d32108373c3.png)
![Left Navigation Menu + icons](https://user-images.githubusercontent.com/11670886/57636573-00fe5b80-756f-11e9-8588-db51636ed95f.png)
![Categoory list   Nested items](https://user-images.githubusercontent.com/11670886/57636592-09569680-756f-11e9-9598-7374130e4971.png)

**Comment by aagonzales** [comment]
Left/side nav for scallop:

- [x] panel geometry 

- [x]  panel behavior (including responsive) 
-  [x] panel 1: full panel show/hides from hamburger
- [x]  panel 2: panel collapses into side rail (triggered by hamburger)
- [x]  Links 
   -  optional icon 
   -  interactive states
- [x]  Menu/sub-menu item 
   -   optional icon 
   -  interactive states

**Comment by designertyler** [comment]
## Sketch file

https://ibm.box.com/s/sa3snlwnodsokuqg6j8imyxw64vhbp3o

## Left panel pieces 
![Left Panel Pieces](https://user-images.githubusercontent.com/19270502/58051466-de90b300-7b17-11e9-8b9e-7a4dee3ca505.png)



## Left panel behavior

![Left Panel Behavior](https://user-images.githubusercontent.com/19270502/58051457-da649580-7b17-11e9-8143-3ae39cf19fd9.png)

**Comment by chrisconnors-ibm** [comment]
in the prior version did we adjust the spacing of the items so that the rail icons had square aspect hit areas?
![image](https://user-images.githubusercontent.com/35537391/57974540-e7527f00-7987-11e9-9c89-b80d0ac00344.png)

Should the bottom chevron/pinning button be there? I thought we landed @ option 2 (hover expands over, but hamburger expands pinned/grid influencer)

**Comment by aagonzales** [comment]
Yes, we did but its too large and it would be inconsistent with the other variations. 48px row heights are just too large for general purpose, so the options are either the collapsible rail version either has a different row size than the others or its not squared.

**Comment by aagonzales** [comment]
Design spec complete for 10.3

**Comment by ghost** [comment]
We are starting to look at this for our project, specifically the secondary side (left) navigation.  Looking for some guidance whether to look at the  black or white version (default theme is white)?

**Comment by aagonzales** [comment]
@dayzed007 its only available in white for the 10.3 release. We're working on theming capabilities for 10.4.
