### ISSUE TITLE
Design Spec for Right Panel (Scallop)

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2336]

**Comment by aagonzales** [comment]
Right panel = panels that are triggered by header icons on the right.

**Define**: 
- [x] Types content that can live in the right panels of the header (user/avatar, notifications, help, docs, search results) and their order, placement. (we are not defining specific aspects of those patterns for scallop)
- [x] States of icon in header (icon triggers panel)
- [x] Right header panel geometry and behavior
   - panel open from side
   - ~is the panel full page or can it hang? both?~ full page for scallop, hanging variation in future version. 
   - Overlay content?
- [x] App Switcher 
   - geometry clean up (match what we're doing on website)
   - Just list for scallop

**Comment by aagonzales** [comment]
## Right panel
**Sketch file:** https://ibm.box.com/s/ae4j3xx8h3we9zk7ocogzyz9gjnwdd60

![Right-panel](https://user-images.githubusercontent.com/11670886/57736590-29b94a80-766e-11e9-99af-f9fdb9a7b5f5.png)


#### Icon order
- A: Search
- ...: product determined icons
- W: Help
- X: Notifications
- Y: Account
- Z: Switcher

![image](https://user-images.githubusercontent.com/11670886/57794812-1a87da80-770a-11e9-91b7-d952188de13f.png)

**Comment by aagonzales** [comment]
Future iternations to include/explore:
- inline floating panels
- grid influencer right panels
- proscribed content for some of the global patterns.

**Comment by aagonzales** [comment]
Dev issue: https://github.com/carbon-design-system/carbon/issues/2403

**Comment by chrisconnors-ibm** [comment]
should this order be expressed right to left?
![image](https://user-images.githubusercontent.com/35537391/57973649-21b51f80-797a-11e9-9a97-bd1f84035615.png)

**Comment by chrisconnors-ibm** [comment]
(adding a note so we remember to express the "If you have them" content for the guidance cc @connor-leech )

**Comment by ghost** [comment]
When working with the sketch file I noticed the the color value for the text item in the right nav is #bebebe.  When comparing to the carbon colors I notice this is pulles from the gray 90 theme.  Isn't the baseline for this work the white theme?  Is mixing colors from various themes acceptable, and if so how does theme switching work?  How would the base code know what values to use if they come from different themes?

**Comment by aagonzales** [comment]
@dayzed007 the UI shell currently has its own set of theme tokens: https://github.com/carbon-design-system/carbon/blob/6b808726c5a094cd59c3d6341dfb8c4b4ce453e4/packages/components/src/components/ui-shell/_theme.scss

We are currently working on developing component level theming that would allow us to integrate the UI Shell components with the current core theme tokens.

**Comment by aagonzales** [comment]
@dayzed007 would you also mind editing your GitHub profile to include your real name or a photo? Not sure who you are or what team at IBM you work on and it would help with context. Thanks!

**Comment by ghost** [comment]
Ha, OMG I didn't realize that this wasn't on the [GiT enterprise](https://github.ibm.com/) and kicked me off to my personal account.  Ya I'll fix that as soon as possible, but still need to figure out a way to balance private from professional.

In the mean time you are confirming that the UI shell currently doesn't follow any particular (published) theme (yet?)?  Hard to make progress is we can't rely on the already known sections as simple as the colors.

**Comment by aagonzales** [comment]
All colors being used by the UI Shell are official IBM Design Language colors. The UI Shell is not currently call the core color tokens from carbon but it is using a unique set of color tokens. Those values however are official IDL color values and mostly reflect what you see within the official themes. We've changed some of the interactive states that will also get update in the core carbon tokens once inline/component theming work is complete.

**Comment by aagonzales** [comment]
10.3 release done
