### ISSUE TITLE
UI Shell Documentation

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2338]

**Comment by aagonzales** [comment]
## Design guidelines:

**Website:**
- ~~separate pages for each UI Shell (experimental) component~~ Only updating single experimental page for Scallop. 
   - Header
   - Left panel
   - Right panel
- UI Shell pattern page (experimental?)
   - Overview of how the shell works
   - Shell geometry and zones
   - Configuration examples
   - In context examples.
- Kit: tracked in https://github.com/carbon-design-system/carbon/issues/2337

**Comment by tw15egan** [comment]
Also refs https://github.com/carbon-design-system/carbon/issues/2742

**Comment by designertyler** [comment]
Outline of docs can be found here. Feel free to leave comments or suggest changes https://ibm.box.com/s/qiws0lpc4bkd8topca5w2uuhrlh6eytu

**Comment by josh-tt** [comment]
@aagonzales Does any developer documentation exist for implementing the UI Shell and it's responsive behavior using Vanilla CSS? Thanks
