### ISSUE TITLE
Data table search input expand/collapse behavior

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2339]
![output](https://user-images.githubusercontent.com/8265238/56563348-44613d80-6560-11e9-8c7d-f7cb76abc2ce.gif)

Right now the collapased search bar can be seen moving from left to right across the action bar. Do we want this movement alongside the width change or should the search bar collapse while remaining aligned to the right side of the bar?

**Comment by asudoh** [comment]
@emyarod Would you be able to elaborate on the alternate option? Thanks!

> or should the search bar collapse while remaining aligned to the right side of the bar?

**Comment by emyarod** [comment]
@asudoh having the search bar collapse instead of the whole icon moving across from left to right i.e. reversing the opening animation. currently the toolbar is immediately shrinking in size and then moving from left to right instead of remaining in the same position and just shrinking

**Comment by asudoh** [comment]
Hmm... Not sure if I understand what you are proposing while I see your point wrt the pain. CC @carbon-design-system/design to see if somebody gets the idea.

**Comment by shixiedesign** [comment]
@emyarod do you mean the search icon staying put and the box of search bar expand/collapse without affecting search icon?

**Comment by emyarod** [comment]
@shixiedesign I mean something like this when collapsing, as opposed to the gif in the first post

![ezgif com-reverse](https://user-images.githubusercontent.com/8265238/58488413-f0351480-812e-11e9-9641-893b90a238d6.gif)

**Comment by shixiedesign** [comment]
@emyarod oh the focus outline! Yes your above gif☝️ is correct. Sorry I didn't even notice. Thanks!

**Comment by chrisconnors-ibm** [comment]
@shixiedesign while it not retaining focus WOULD BE FANTASTIC (that's a broader problem) I'm not sure that's what @emyarod is pointing out here. biggest difference I see is that the magnifying glass does not animate from its position on the left of the search box in the active state to the right in its resting state - it instantly appears on the right (the resting state position). 

@shixiedesign @aagonzales @jeanservaas is that what we want as the transition here?

@emyarod have I described the choreography of the desired transition correctly?

**Comment by emyarod** [comment]
sort of @chrisconnors-ibm. what I mean is the search box's position is changing as opposed to its dimensions

just as the width of the element changes from square to rectangular when the user focuses on the search box, I expected the width to shrink (from rectangular to square) when losing focus. however the width is instantly reduced when the search box loses focus, and then the entire (now square instead of rectangular) element moves across the screen

**Comment by tw15egan** [comment]
@emyarod it looks like the current functionality matches your proposal in https://github.com/carbon-design-system/carbon/issues/2339#issuecomment-496553489

Are we good to close this?

**Comment by emyarod** [comment]
it would be nice to be able to reference the PR which resolved this issue especially since I'm pretty sure I fixed it, but it may be lost in our move from carbon-components-react to the monorepo since early netlify previews after the move do not have this issue

**Comment by tw15egan** [comment]
Yeah, I searched through a bunch of PR's and couldn't find the specific one. I leave it up to you to determine what you'd like to do with this issue.
