### ISSUE TITLE
Has structured list border been removed?

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2340]
## Summary
The example for a structured list still includes the border class
bx--structured-list--border

Should this be removed or is this a missing feature?

**Comment by asudoh** [comment]
@aledavila Any insights...? Thanks!

**Comment by aledavila** [comment]
@asudoh Seems to be left over class. 

Removed in https://github.com/IBM/carbon-components/pull/2349

**Comment by asudoh** [comment]
@aledavila Thank you for your quick fix!
