### ISSUE TITLE
SHA-1 Certificate error

### ISSUE THREAD

**Issue by JessNah** [carbon-design-system/carbon#2341]
My team has created an app using carbon-components and carbon-components-react. 
I just heard from a tester that they encountered the following issue:

NOTE:  This happens with environment that has no access to public internet. 

This site makes use of a SHA-1 Certificate; it’s recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] configuration
This site makes use of a SHA-1 Certificate; it’s recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] current_user
Source map error: request failed with status 404
Source Map URL: carbon-components.css.map[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/carbon-components@latest/src/globals/fonts/IBMPlexSans-Regular-Latin1.woff2. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/carbon-components@latest/src/globals/fonts/IBMPlexSans-Light-Latin3.woff2. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/carbon-components@latest/src/globals/fonts/IBMPlexSans-Regular-Latin3.woff2. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/carbon-components@latest/src/globals/fonts/IBMPlexSans-SemiBold-Latin3.woff2. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/carbon-components@latest/src/globals/fonts/IBMPlexSans-Regular-Pi.woff2. (Reason: CORS request did not succeed).[Learn More]

I do not directly import or include these files, so I suspect that the carbon-components module is somewhere importing and referring to these files... wherein causing the issue.
To me, it looks like the problem is related to the certificate of  https://unpkg.com/carbon-components/... site./

Looking for any help in resolving this issue. Thanks!

-----

Is there any way to get the file contents of for example: https://unpkg.com/carbon-components@latest/src/globals/fonts,
without needing to at run time, access this public url?
Is there perhaps another setup path, where all these kinds of files are downloaded and cached so that the module can look at the downloaded/saved files instead of needing to go and request the resource through public URL during run time?

**Comment by asudoh** [comment]
Hi 👋 thank you for bring this topic up - Please be advised that the default `@font-face` is merely for quick try or demonstration purposes. We recommend compiling Carbon Sass code with `$css--font-face: false` for production case and create `@font-face` rule by your own. In `v9` there is an alternate way to change the font URL, which is, changing `$font-path`. Hope this helps!

**Comment by JessNah** [comment]
Thanks soo much @asudoh ! You're comment really helped me a ton. Very appreciated
