### ISSUE TITLE
Show example of field Help text

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon#2346]
### Summary

Please provide a design example of field Help text on the Form page, Format image here: [https://www.carbondesignsystem.com/components/form/usage](url)

<img width="649" alt="Screen Shot 2019-04-24 at 11 12 13 AM" src="https://user-images.githubusercontent.com/12902530/56675517-e2005e00-6681-11e9-8bf8-0b07293a85d7.png">

### Justification

The other features on the Form page, such as Labels and Inputs, are included in the example image. To make it easier for designers and developers to know where to place the field Help text and what it looks like, please provide an example in the existing Form page, Format image.

### Desired UX and success metrics

The success metric is the Help text example appears in the image.

### Specific timeline issues / requests

No hurry. This addition would fix a small oversight on the page.

**Comment by asudoh** [comment]
Moved to: carbon-design-system/carbon-website#1548
