### ISSUE TITLE
File uploader close has not keyboard interaction or focus state

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2347]
## Detailed description

File uploader close has not keyboard interaction or focus state

> To close a removable file in the file uploader list the user has to click, no keyboard interaction available.

> I'd expect to be able to navigate via keyboard

> Chrome

> 10.1

## Steps to reproduce the issue

1. view https://www.carbondesignsystem.com/components/file-uploader/code

**Comment by dakahn** [comment]
Tested on Windows 10, in latest Firefox 

there is a focus state applied to the button, the button is a tab stop, but it is inoperable using enter or spacebar.

![2019-05-03 11_51_21-Carbon Design System](https://user-images.githubusercontent.com/40970507/57152695-ca1f8d00-6d99-11e9-9533-bc390d513f71.png)

**Comment by lee-chase** [comment]
I meant the X as shown here to remove the file.
![image](https://user-images.githubusercontent.com/15086604/57153763-0de0b980-6dcf-11e9-9a3c-0077973fd747.png)

The Issue @dakahn refers to is because the control is not a button. 

A non-button needs to process:
- click
- enter key down as click
- space key down to mimic button state active and stop propagation.
- space key up as click

**Comment by dakahn** [comment]
What you were saying is crystal clear in hindsight -- just skipped over words while reading or something 😆

**Comment by emyarod** [comment]
I believe file uploader items should now support keyboard interactions ref https://github.com/carbon-design-system/carbon/pull/3872

**Comment by asudoh** [comment]
Thanks @emyarod - Closing as I can see what he says.
