### ISSUE TITLE
Overflow menu for last column is not visible in data table.

### ISSUE THREAD

**Issue by cristiboariu** [carbon-design-system/carbon#235]
## Detailed description

> Is this issue related to a specific component? 

Yes.

> What did you expect to happen? What happened instead? What would you like to see changed?

When clicking on the overflow menu on last column of the datatable its not displayed. It should be visible, like the rest of the menus from the other columns. 

> What browser are you working in? 

Chrome.

> What version of the Carbon Design System are you using? 

Latest.

I have applied some padding to the datatable in order to prove that its hidden.
<img width="1401" alt="screen shot 2017-07-19 at 2 31 58 pm" src="https://user-images.githubusercontent.com/2500147/28365023-84939f90-6c8f-11e7-9546-5ff91c7e630a.png">

And this is without padding (default behaviour - you can see a small arrow which indicates that its open but being hidden under the margins of the datatable).
<img width="1294" alt="screen shot 2017-07-19 at 2 32 20 pm" src="https://user-images.githubusercontent.com/2500147/28365024-84951168-6c8f-11e7-92cb-289667281fa3.png">

**Comment by cristiboariu** [comment]
Anybody can look into this? It is a blocker on our DEV flow.

**Comment by hellobrian** [comment]
Hey, looking at this now. 

You might be missing a prop on OverflowMenu called `floatingMenu` that should get it to appear. Without it, then it won't appear exactly where it should.

```jsx
<OverflowMenu floatingMenu>
  ...
</OverflowMenu>
```

I made a quick demo on codesandbox to try replicating your issue, hopefully this helps: 

[![Edit React Table](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g52NW01mZ)

**Comment by hellobrian** [comment]
Hey @cristiboariu, we'll be looking at this soon. Sorry that this is blocking you right now. I've pinged this issue to devs on the Carbon team and someone will start troubleshooting asap

**Comment by iangfleming** [comment]
@cristiboariu  Hey! Sorry for the late response. 

Looks like you're using this with Angular, right?

With the latest version of the Overflow Menu it uses an internal component called FloatingMenu to append the menu to the body outside of any elements that might cut it off or overlap it. My guess is that this bug has something to do with how your Angular app works with this FloatingMenu component. 

Do you have the example you screenshoted above hosted anywhere? I'd like to take a look at it.

**Comment by cristiboariu** [comment]
@iangfleming Right, we're using it with angular: https://pages.github.ibm.com/cloudMatrix-CAM/cb-carbon-angular-components/#/components/overflow-menu

I'd like to refine our angular implementation to take in consideration this FloatingMenu but I don't find any example with this in doc: http://www.carbondesignsystem.com/components/overflow-menu/code

**Comment by iangfleming** [comment]
@cristiboariu well the Overflow Menu at the link you shared is definitely not the newest version. Do you have a link to the github repo where these angular components are?

You shouldn't have to do take Floating Menu into consideration since it's an internal component that Overflow Menu consumes. It should just work 🙂

**Comment by cristiboariu** [comment]
Yes, here it is: https://github.ibm.com/cloudMatrix-CAM/cb-carbon-angular-components/tree/master/src/overflow-menu

**Comment by iangfleming** [comment]
@cristiboariu I'm getting a 404 on that link. Is the repo private?

**Comment by cristiboariu** [comment]
@iangfleming Right we need to give you repo, are you with IBM or IDEAN? Because we can't find you on github.ibm.com

**Comment by iangfleming** [comment]
@cristiboariu https://github.ibm.com/ianfleming

**Comment by cristiboariu** [comment]
Thanks, can you please check it now?

**Comment by iangfleming** [comment]
@cristiboariu yep! just to clarify is this repo using the carbon-components js? or just the styles and class names?

**Comment by cristiboariu** [comment]
@iangfleming Good question... Its using only styles and class names. So I should add js file too (we didn't added it because we had to add/remove specific classes using angular). Can you please let me know in which version of carbon lib this FloatingMenu  was added so I can test js integration with it?

**Comment by iangfleming** [comment]
@cristiboariu Floating Menu was introduced in 7.0.0. It was introduced to solve the exact problem you are having. Since this isn't actually a bug with the component library I'm going to close this issue. Are you on Slack? That's the easiest way to reach me if you have questions.
