### ISSUE TITLE
Global font size is smaller after migrating to v10

### ISSUE THREAD

**Issue by gin-nader** [carbon-design-system/carbon#2350]
## Detailed description

> Describe in detail the issue you're having.

We recently updated our carbon-components package from 9.76.5 to v10.0.0, and we are seeing some significant differences relating to font size. We are also seeing some issues with checkboxes, for example, where the icon is smaller and off center compared to what it used to be.

> Is this issue related to a specific component?

The font size issue is a general issue. The checkbox issue is related to Checkbox.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the font size to have stayed the same size as it was in 9.x. I am now seeing significantly smaller font size that is hard to read. I would like to see the same sized font size or an option to globally increase it.

> What browser are you working in?

Google Chrome primarily, but I see the same issue in Firefox.

> What version of the Carbon Design System are you using?

10.0.0

## Additional information

We are also using carbon-components-react v7.1.0.

This is what it looks like now:
![image](https://user-images.githubusercontent.com/19754122/56743639-f5283200-6744-11e9-9a8d-693edf210cdb.png)

This is what it looks like on the Carbon Components website:
![image](https://user-images.githubusercontent.com/19754122/56743689-0bce8900-6745-11e9-95eb-41c11a0712e4.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! I suggest you compare [our development environment](https://the-carbon-components.netlify.com/component/data-table--default.html) with your application to see what styles are in effect. My guess is that some application-specific style is in play that made the font smaller, or the data table has different style from ours (our `v10` style puts a specific font size to `<thead>`/`<tbody>`, etc.). Or you can create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox it'll help us see what's going on.

**Comment by gin-nader** [comment]
Ah, okay. I did a compare, and I think we might be missing some styles in our project. In our `application.scss` file we use this statement to import carbon component styles `@import 'node_modules/carbon-components/scss/globals/scss/styles.scss';`. Is this no longer valid in v10, or are we missing some extra imports?

**Comment by gin-nader** [comment]
I think I figured it out. I was including bootstrap css in our index.html, and that was conflicting with carbon components. With that removed, the checkboxes look normal again. As for the font, it sounds like I can use type tokens to increase the font size. This can be closed out, then. Thanks.
