### ISSUE TITLE
Trying to use UIShell with css from CDN

### ISSUE THREAD

**Issue by yanilkr** [carbon-design-system/carbon#2358]
Hi There, 

Thanks for Carbon components. I had a simple developer question, looking for directions. 

## Summary
I made a very simple page to try out Carbon Design Components especially UI shell.

A simple index.html page as shown below, includes CDN links for css and js. Copy pasted code from https://www.carbondesignsystem.com/experimental/ui-shell/code

I was hoping this will render a stylized UI with navbar but for some reason the styles for navbar are not being applied and also there does not seem to be a separate css for UI shell. 

## Relevant information
Here is the sample index.html page. I tried running this from a webserver. http://localhost:8080/index.html 

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Carbon Design</title>
  <link rel="stylesheet" href="https://unpkg.com/carbon-components/css/carbon-components.min.css">
    <script src="https://unpkg.com/carbon-components/scripts/carbon-components.min.js"></script>
</head>

<body class="bx--body">
   Copy paste code from https://www.carbondesignsystem.com/experimental/ui-shell/code
</body>

</html>
```

I noticed this codepen which uses extra css from https://unpkg.com/carbon-addons-bluemix@0.3.0/css/carbon-components.min.css
https://codepen.io/team/carbon/pen/LedzoM

Is there a better example that shows how to use UI shell properly?

**Comment by asudoh** [comment]
Hi 👋 our shell is still experimental and thus not distributed as a pre-built CSS. You need to build CSS by your own to get the style of shell. Hope this helps!
