### ISSUE TITLE
How to change the default font? 

### ISSUE THREAD

**Issue by vignesarul** [carbon-design-system/carbon#2359]
## Changing IBM Plex font to a different font

Hi There,

I'm trying to change the font-family to different font altogether. I couldn't find relevent information in typography section of documentation. Can anyone please help?

**Comment by asudoh** [comment]
Looks that overriding type tokens at https://github.com/IBM/carbon-elements/blob/v10.1.0/packages/type/scss/_styles.scss#L11-L429 is the quickest. CC @joshblack  to see if he knows a better approach.

**Comment by dakahn** [comment]
Looks resolved to me! If not, I'm happy to reopen.

**Comment by amandakoster** [comment]
@vignesarul  Were you able to figure it out? I am trying the same thing.

**Comment by mgaseta** [comment]
@amandakoster I'm trying the same aswell, do you have any tips?

**Comment by scottagt** [comment]
I had this same question; I don't want to use Plex Sans. The documentation is completely missing/misleading on this. The theming page says the typography tokens that can be customized are on the Typography page but then the Typography page never defines these tokens. 
![image](https://github.com/carbon-design-system/carbon/assets/25912784/faa34c6f-bec4-4012-8116-aedbeb583800)

**Comment by kehrazy** [comment]
Still no documentation on this. Unfortunate :(

**Comment by walec51** [comment]
@dakahn issue is not resolved - no one has any idea how to do it

@asudoh no everything but the font-family is set there

**Comment by thom-as-thom** [comment]
The only solution I found was the one mentioned by @asudoh. this is how my style.scssfile ended up looking 

`@use '@carbon/styles/scss/config' with ($use-flexbox-grid: true,
	$font-path: '@ibm/plex',
);

@use '@carbon/type' with (
	$caption-01: (
		font-family: unquote('Roboto, "Helvetica Neue", sans-serif')
	),
	$label-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$helper-text-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')
	),
	$body-short-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$body-long-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$body-short-02: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$body-long-02: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$code-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$code-02: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$heading-01: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$heading-02: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$productive-heading-03: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$productive-heading-04: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$productive-heading-05: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')

	),
	$expressive-heading-03: (font-family: unquote('Roboto, "Helvetica Neue", sans-serif')
	) 
);

@use '@carbon/themes/scss/themes' as *;
@use '@carbon/styles/scss/theme' with ($fallback: $white,
	$theme: (layer-01: red),
	$background: #F0F0F0,
	$border-subtle-00: transparent,
	$border-subtle-01: transparent,

);
@use '@carbon/styles';`
