### ISSUE TITLE
Data Table: batch action button & icon colors are not properly themed

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#2371]
## Detailed description

The batch action icon fill colors are set to `$ui-01`. Whereas that color looks correct in lighter themes, for gray90 and gray100 themes that color is too dark and inaccessible.

Ideally the batch action icon fill colors should be `$icon-03`, which is always white and would therefore look good against the blue60 button background color + work with all themes.

**Comment by asudoh** [comment]
Ping @carbon-design-system/design to see if they have any input - Thanks!
