### ISSUE TITLE
Data Table: does not include reset mixin, therefore breaks if global box-sizing not used

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#2373]
## Detailed description

Similar to idea to what @j1mie suggested fixing in https://github.com/carbon-design-system/carbon-components/pull/2370

Without `@include reset` in this component, consumers who don't use the globals (with `* { box-sizing: border-box; }`) get interesting results. For example, the search icon in batch actions looks like this in our environment 😅 --

![Screen Shot 2019-05-01 at 11 48 06 AM](https://user-images.githubusercontent.com/9057921/57029439-59486b80-6c07-11e9-9ac9-ab02b36b63a8.png)

It would be very helpful if `@include reset` could be added to the Data Table component. This would require a couple small changes (for example, I believe fixing the example shown in my screenshot above would involve deleting this width and height: https://github.com/carbon-design-system/carbon-components/blob/master/src/components/data-table/_data-table-action.scss#L55).

**Comment by dakahn** [comment]
Totally seems like something we need to do. Great catch! 🏄

**Comment by jendowns** [comment]
Oops didn't mean to let this close. 😬 It's still an issue for us. @dakahn could you help me reopen this?

**Comment by jendowns** [comment]
This is still an issue 👍
