### ISSUE TITLE
Add custom text input to combo box component

### ISSUE THREAD

**Issue by scottmarcella** [carbon-design-system/carbon#2377]
### Summary
The current iteration of the Carbon combo box component includes selection capabilities and filtering capabilities, however, the traditional combo box component that is understood across design and development includes not only selection capabilities, but custom text input capabilities.

The traditional combo box functionality with selection and custom text input is desired.

### Justification

Existing experiences that have not yet been migrated to Carbon currently implement a traditional combo box in certain flows. Keeping this consistent is ideal due to the fact that some of these existing implementations will not be moving to Carbon at the present time. 

### Desired UX and success metrics

This field will both allow users the option to make a dropdown selection or allow the user to enter a custom input. Upon successful submission, the custom input will be saved to the dropdown list for future selection. 

Please see traditional combo box definition: https://en.wikipedia.org/wiki/Combo_box

### "Must have" functionality

Dropdown with two options:
   - Select from a list of pre-populated options
   - Enter a custom value (will then be saved to list of options)

### Specific timeline issues / requests

It would be great to have this before August 1st, 2019.

### Available extra resources

Currently, there are no available extra resources.

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by scottmarcella** [comment]
Missed the close by the stale bot. Commenting to hopefully open this back up. 

Is there anything else the team would need to move forward on this?

**Comment by asudoh** [comment]
Moved #3534 - Wrt the contribution, the first step would be design proposal for our designers to review. Thanks!

**Comment by scottmarcella** [comment]
> Moved #3534 - Wrt the contribution, the first step would be design proposal for our designers to review. Thanks!

Hi Akira, thanks for the reply! Is there a template that I should use for a design proposal? If not specifically, what type of proposal would the designers need?

**Comment by asudoh** [comment]
Not sure about the formal one, but I was imagining a Sketch file and/or a screenshot. CC @carbon-design-system/design
