### ISSUE TITLE
Write guidelines for monorepo

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2387]
While converting over to a monorepo, we will need to edit our contributing and issue processes to reflect the project's increased scope and change in structure. These documentations should include:

- [ ] Steps to contribute to the monorepo
- [ ] The issue writing process
- [ ] The release process

**Comment by mattrosno** [comment]
@joshblack can we add release cycle documentation to this issue? E.g. version cadence, how minor versions stay in lock-step.

**Comment by joshblack** [comment]
Sounds good @mattrosno 👍

**Comment by joshblack** [comment]
Brief outline:

- Carbon ships major updates every 6 months, around end of Q1 / start of Q2 and end of Q3 / start of Q4
- Carbon works in iteration plans each month
- Each iteration results in a minor bump with updates (although minors can occur in-between if needed)
- Patches are grouped on a weekly basis (can extend or shorten depending on frequency updates are needed)
- Hotfixes are published as-needed and don't have to wait to align to any of the above time periods

Specific details:

- The core design system is essentially operating as a fixed version (outside of `carbon-components-react`)
- However, this doesn't mean that all packages have to sit on the same exact version. Packages will still be updated related to semantic versioning, however if they have no updates they will not be bumped to match the new latest version

How this might work:

```
package-a@10.2.0
package-b@10.2.0
package-c@10.1.0
package-d@10.1.0
```

If packages a, b, and c have changed under a PATCH then the packages will be updated to:

```
package-a@10.2.1
package-b@10.2.1
package-c@10.2.1
package-d@10.1.0
```

So all changed packages are bumped to the latest version (and corresponding tag) while `package-d` remains unchanged since no updates have occurred.

Grouped patches and hotfixes are built by taking the most recent git tag and cherry picking commits from `master` into the branch. These are grouped under a Pull Request that is reviewed by the team before releasing and tagging as the new version. The goal here is that we should be publishing artifacts from CI builds as pre-releases and then promoting these pre-releases to stable after manual and automated verification.

**Comment by mattrosno** [comment]
@joshblack thanks! If working on something that will result in a breaking change, do we have a branching strategy to defer those breaking changes until a later point in time? Or how will those scenarios be handled?

Do breaking changes get deferred until the next major release? What about minor releases?

**Comment by joshblack** [comment]
Good catch! Breaking changes will be under feature flags till next release.

**Comment by scottnath** [comment]
@joshblack - this sounds like a given package might be available in multiple releases at once, is the following breakdown correct?

## current release (month 1, week 1)
1. react-component-a@10.2.0
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.2.0
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.0
    * branch: master

## unrelated patch (week 2)
1. carbon-components-react@10.2.1
    * contains react-component-a@10.2.0
    * branch: master

## related patch (week 3)
1. react-component-a@10.2.1
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.2.2
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.1
    * branch: master

## unrelated minor, unrelated patch (week 4)
1. react-component-a@10.2.1
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.2.2
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.1
    * branch: master
1. carbon-components-react@10.3.0
    * `npm i carbon-components-react@next`
    * contains react-component-a@10.2.1
    * branch: next

## related minor, unrelated patch (month 2, week 1)
(assumes a release at _start_ of week and component-a's `minor` release was not complete before main package `minor` release)
1. react-component-a@10.2.1
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.3.0
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.1
    * branch: master
1. carbon-components-react@10.4.0
    * `npm i carbon-components-react@next`
    * contains react-component-a@10.3.0
    * branch: next
1. react-component-a@10.3.0
    * `npm i react-component-a@next`
    * branch: next

## unrelated breaking change, related patch (month 2, week 2)
1. react-component-a@10.2.2
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.3.1
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.2
    * branch: master
1. carbon-components-react@10.4.0
    * `npm i carbon-components-react@next`
    * contains react-component-a@10.3.1
    * patch applied, version bump
    * branch: next
1. react-component-a@10.3.1
    * `npm i react-component-a@next`
    * branch: next
1. carbon-components-react@11.0.0
    * `npm i carbon-components-react@11`
    * contains react-component-a@10.3.1
    * branch: next
    * feature-flag: `carbon-xi`

## related and structure-changing breaking change, related patch (month 2, week 3)
1. react-component-a@10.2.3
    * current release received with `npm i react-component-a`
    * branch: master
1. carbon-components-react@10.3.3
    * current release received with `npm i carbon-components-react`
    * contains react-component-a@10.2.3
    * branch: master
1. carbon-components-react@10.4.1
    * `npm i carbon-components-react@next`
    * contains react-component-a@10.3.2
    * patch applied, version bump
    * branch: next
1. react-component-a@10.3.2
    * `npm i react-component-a@next`
    * branch: next
1. react-component-a@11.0.0
    * `npm i react-component-a@next`
    * branch: next
    * feature-flag: `carbon-xi`
    * question: what if the breaking change is so big it's impractical to put under a feature-flag?
      * solution? branch: carbon-xi
1. carbon-components-react@11.0.0
    * `npm i carbon-components-react@11`
    * contains react-component-a@11.0.0
    * branch: next -or- carbon-xi (without feature flag)
    * feature-flag: `carbon-xi`

## questions: 

* Team plans on a release in 2020 Q1 and wants to build with Carbon 11, could they point to a carbon 11 release (@carbon-xi) that would not have setting of a feature flag required?
    * Since this would really be just _everything_ new, would it be possible to have continuous, automatic releasing of this branch?
* External team submits a patch-level fix on a Monday, but patch releases happen on Thursdays, is there a release-channel they could point to before the patch-release happens?
* Hotfix bug is a breaking change, but it is a critical bug that causes a user-impacting error - which channel(s) is this fix sent to? Is there different version numbering for hotfixes?

**Comment by joshblack** [comment]
@scottnath I think the big thing that we won't do from is maintain separate branches (`master`/`next`). There will only be `master`. Patches are created by using the last release git tag and cherry-picking commits from master onto it. It then will be tagged and published.

This is 100% an experiment though for this next cycle, so we'll see how it works. If it makes things harder then it should, it may move to an alternative strategy like multiple git branches.

To answer your questions:

> Team plans on a release in 2020 Q1 and wants to build with Carbon 11, could they point to a carbon 11 release (@carbon-xi) that would not have setting of a feature flag required?

I believe we would publish alpha/beta/rc channels leading up to the official release that will function as if one was using v11 directly (e.g. no need to set feature flags)

> Since this would really be just everything new, would it be possible to have continuous, automatic releasing of this branch?

Possibly, I think right now our current plan is to start doing `canary` publishes in CI. I don't think this would include the next major though, but it would contain latest code published using the `canary` tag but versioned with the commit hash. e.g. `carbon-components@11.0.0-alpha.ABCDEF`

> External team submits a patch-level fix on a Monday, but patch releases happen on Thursdays, is there a release-channel they could point to before the patch-release happens?

We will distinguish patches as either a `hotfix` or a general patch. General patches will be grouped up as much as possible, a `hotfix` can be published at any point in time.

> Hotfix bug is a breaking change, but it is a critical bug that causes a user-impacting error - which channel(s) is this fix sent to? Is there different version numbering for hotfixes?

My gut tells me this would be done on a case-by-case basis. Typically things that are fixes that are breaking changes can be wrapped around feature flags (had a case last release with slider, as an example) but could definitely change up our strategy to best mitigate the problem.
