### ISSUE TITLE
Create component specification directory structure

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2390]
As an extension of https://github.com/carbon-design-system/carbon-spec/issues/6, determine what a component spec directory should look like. Determine what information goes in what files, and document this component anatomy somewhere. It could look like:

![image](https://user-images.githubusercontent.com/1691245/57156481-b416ca00-6da3-11e9-9573-c2c55c68bd54.png)

**Comment by elizabethsjudd** [comment]
Not stale
