### ISSUE TITLE
Create component spec demo objects

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2392]
If all component implementations are using Storybook as a dev and/or demo environment, we should author the stories in the component specifications so we can help all Storybooks be consistent.

Storybook aside, we need demo content to use in component spec tests.

E.g., `button-spec` package has a `demo.js` file that defines button stories and the knobs available in each story. `button-react` consumes the spec and in doing so, uses the demo object to structure the React storybook.

**Comment by scottnath** [comment]
relevant discussion: https://github.com/carbon-design-system/rfcs/pull/7

**Comment by scottnath** [comment]
@mattrosno is this story still relevant?

**Comment by scottnath** [comment]
@mattrosno @joshblack @shinytoyrobots  is this story still relevant?

**Comment by joshblack** [comment]
@scottnath great question, I think we definitely still need content consolidation for sure 👍
