### ISSUE TITLE
Create spec test format

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2393]
As an extension of https://github.com/carbon-design-system/carbon-spec/pull/10 and https://github.com/carbon-design-system/carbon-spec/pull/11, determine how we specify component requirements and how we test against those requirements. Do so with a handful of initial components (e.g. button, checkbox, icon, modal).

**Comment by elizabethsjudd** [comment]
Not stale

**Comment by elizabethsjudd** [comment]
Not stale
