### ISSUE TITLE
Multiselect design feedback

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2399]
reported by @laurenmrice in https://github.com/carbon-design-system/carbon-components-react/issues/2322

- [x] Is the checkbox 16px away from the left side? The label text and the line dividers align vertically but the checkbox still seems pushed the right . Is it because of the padding around the checkbox?
<img width="438" alt="misalignment" src="https://user-images.githubusercontent.com/43969356/57235863-7e632280-6fe9-11e9-8ee4-aadab17fbe1a.png">

- [x] When hovering over a selected option in a row, the text color changes to text-02 it should not be changing.
<img width="367" alt="hover text-02 color" src="https://user-images.githubusercontent.com/43969356/57235891-8cb13e80-6fe9-11e9-8fca-39d22165a6bf.png">

- [x] If you have the dropdown open and click the disabled knob, you can still interact with hover on the options in the rows. Don’t know if its possible to auto close the dropdown in this case? or take off hover interactions from the rows if its open.

- [x] tooltip on hover knob hasnt been implemented?
<img width="344" alt="disabled interactions" src="https://user-images.githubusercontent.com/43969356/57235909-93d84c80-6fe9-11e9-9c7c-52ee3d97bdf7.png">

- [x] The alert icon needs to come over to the left if the filterable knob is activated because the close icon shows up and is currently overlapping the alert icon.
<img width="393" alt="Screen Shot 2019-05-06 at 10 29 14 AM" src="https://user-images.githubusercontent.com/43969356/57236213-24af2800-6fea-11e9-99f1-c1bda7add6aa.png">

**Comment by jendowns** [comment]
Hey @emyarod @laurenmrice, I noticed this in our dark UI environment & wanted to verify -- should this focus state of the checkboxes be blue60? Seems the trajectory has been to make these dark UI focus states white... though that wouldn't necessarily work here given that the checkbox is white when selected. 🤔 Just wondering if you have any guidance?

![Screen Shot 2019-05-06 at 1 47 34 PM](https://user-images.githubusercontent.com/9057921/57247649-fe978100-7005-11e9-9b2b-ee9675b855a8.png)
![Screen Shot 2019-05-06 at 1 47 45 PM](https://user-images.githubusercontent.com/9057921/57247650-fe978100-7005-11e9-96b5-3102605fcc26.png)

**Comment by laurenmrice** [comment]
Hey @jendowns, no the focus state should not be blue 60 in dark themes, it should be white. Thanks for catching this !
