### ISSUE TITLE
Development of standalone Shell Header

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#2401]
Design issue: https://github.com/carbon-design-system/carbon-components/issues/2334

**Comment by aagonzales** [comment]
## Final designs

**Sketch file:** https://ibm.box.com/s/i45sfzlwg4u4hwh8xskwwg66yiz4fwmn

![Header pieces](https://user-images.githubusercontent.com/11670886/57656546-46864d00-759e-11e9-9564-38354bb15108.png)
![header patterns ](https://user-images.githubusercontent.com/11670886/57656630-936a2380-759e-11e9-923d-2fae1994d879.png)
