### ISSUE TITLE
Development of standalone Right Panel 

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#2403]
Design issue: https://github.com/carbon-design-system/carbon-components/issues/2336

**Comment by aagonzales** [comment]
## Final designs
**Sketch file:** https://ibm.box.com/s/ae4j3xx8h3we9zk7ocogzyz9gjnwdd60
![Right-panel](https://user-images.githubusercontent.com/11670886/57879890-14b1f800-77e3-11e9-87d4-7ba22ce3aa16.png)

**Icon order:**
![image](https://user-images.githubusercontent.com/11670886/57879919-1e3b6000-77e3-11e9-9972-e68172029453.png)

**Comment by aagonzales** [comment]
Addition: the panel should have a dropdown shadow.
`box-shadow: 0 2px 8px rgba(0,0,0,.2)`

Motion should be:
`transition: transform .24s cubic-bezier(0,0,.38,.9),-webkit-transform .24s cubic-bezier(0,0,.38,.9)`
