### ISSUE TITLE
title for card component is not expanding on mouse hover

### ISSUE THREAD

**Issue by solomonliberta** [carbon-design-system/carbon#241]
When we use the card component, if the title is long text, it got clipped and an ellipsis is added at the end. This is good to show that there is remaining text in the title, but it will be good if the whole title got displayed when we hover our mouse in the title. 
Example:
<h3 id="card-title-2" class="bx--about__title--name" title="Card Name">This is a very long long title</h3>

The currently displayed text will be, like
This is a very long ...

On mouse hovering the title, I was expecting it will show me the full title text. It would be great if that feature got added into the carbon card.

**Comment by hellobrian** [comment]
For whoever fixes this issue, you should add `title` attribute to the Card. Someone will assign themselves to this soon.
