### ISSUE TITLE
Angular component

### ISSUE THREAD

**Issue by isummation** [carbon-design-system/carbon#242]
We are planning to implement carbon-component and design in our project which will be angular 4 project. 

I am looking for any angular 4 module available like you have for React. If not, any plan for development. 

Also, is there sample example to bind component's event binding. I have tried for notification's eventBeforeDeleteNotification but didn't call it. If someone can provide examples of binding component's event with and without selector will be a great help?

Thanks,
Pritesh

**Comment by hellobrian** [comment]
Our team doesn't support Angular components but we've pinned a message to our slack channel (#carbon-components) that explains how you can proceed with using Angular: 

![image](https://user-images.githubusercontent.com/4185382/28835807-49ca6e12-76ac-11e7-82a4-47b398f3374f.png)

https://ibm-cloudplatform.slack.com/archives/C046Y0YUD/p1496355402423024

**Comment by niralmunjariya** [comment]
@hellobrian 
https://ibm-cloudplatform.slack.com/archives/C046Y0YUD/p1496355402423024
Above link is not accessible without a login.
Is there any other way to check that?

**Comment by asudoh** [comment]
Hi @niralmunjariya a similar one can be found at: https://codepen.io/asudoh/pen/OOOMdB

**Comment by niralmunjariya** [comment]
@asudoh Thanks!
