### ISSUE TITLE
pre-factor: Separate existing shell component into separate parts

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2424]
## Separate existing shell component into separate parts

-->

separate the Header, Left Panel, Right Panel into 3 individual components that teams could theoretically use alone but will be part of the Shell as a pattern

**Comment by tw15egan** [comment]
This pattern is already achievable as is. If a user wanted to simply use the `SideNav` component, they could import just that component by doing:

```js
import { SideNav } from '../UIShell';
```
