### ISSUE TITLE
Carbon bundler not properly creating directories on Windows

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2434]
When building the monorepo on Windows, the Carbon Bundler is not creating output directories correctly, causing missing import errors in the other Carbon packages. The regex `.replace` operation on the output folder path was not correctly replacing the directory names

This was the output of `outputOptions`, all of the formats are pointing to the `es` directory

```
{ format: 'esm',
  file:
   'E:\\Users\\PC\\Documents\\GitHub\\carbon-components\\packages\\colors\\es\\index.js' }
outputOptions { format: 'cjs',
  file:
   'E:\\Users\\PC\\Documents\\GitHub\\carbon-components\\packages\\colors\\es\\index.js' }
outputOptions { format: 'umd',
  file:
   'E:\\Users\\PC\\Documents\\GitHub\\carbon-components\\packages\\colors\\es\\index.js' }
```

**Comment by sichangi** [comment]
Hi @emyarod 👋, seems this issue is still alive, are there any plans to fix it?
If none, I'd like to take it on, I managed to fix it on a local version of the repo.

**Comment by emyarod** [comment]
@sichangi feel free to open a pull request!
