### ISSUE TITLE
Generate elements sketch library from carbon-elements

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2438]
**Is your feature request related to a problem? Please describe.**
Current IBM Design Language Sketch library is not maintained and requires manual creation/revision. For example it's currently hundreds of icons behind the /icons package. Designers and developers now see icons on https://www.carbondesignsystem.com/guidelines/iconography/library that don't exist in the IBM Design Language Sketch library Library, and are engaged in work arounds (downloading individual icons, orphaning them) to get the complete set.

**Describe the solution you'd like**
Automatically build a `carbon-elements` Sketch Library from the contents of carbon-elements including type, type styles, icons, colors, etc.

**Describe alternatives you've considered**
Right now we tell designers to download the IBM Design Language sketch library to get Type symbols, spacing, colors and icons. this library was created by hand and is currently wildly (perhaps 50%) out of date from just the icons in carbon elements/icons. fixing it by hand would be a significant undertaking, and will soon get out of date from the repo again.

**Additional context**
This is high priority work

**Comment by lovemecomputer** [comment]
task for tracking specs on output file format: https://github.com/carbon-design-system/carbon-components/issues/2436

**Comment by chrisconnors-ibm** [comment]
the specification for how to lay out/structure the library: #2436

**Comment by joshblack** [comment]
Re-opening with the following TODOs:

- Group icons by category information
- Verify symbols are updated instead of replaced

**Comment by chrisconnors-ibm** [comment]
thanks @joshblack

**Comment by joshblack** [comment]
Closing in favor of #3406
