### ISSUE TITLE
Create codemods for migration carbon-icons to @carbon/icons-* variants

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2446]
We're most likely going to want to put out a couple of codemods depending on the use-case:

- One migration strategy in carbon-upgrade for the `carbon-icons` dependency, in it we do:
  - Check for React, if so apply migration for `@carbon/icons-react`
  - Check for Angular, if so apply migration for `@carbon/icons-angular`
  - Check for Vue, if so apply migration for `@carbon/icons-vue`
  - Otherwise, run migration for `@carbon/icons` directly

Most likely the core team can help with React and Vanilla, and we will need to rely on contributions for Angular and Vue.

## React

The current `<Icon>` component has been showed to be used in the following ways:

```jsx
import { addSolid } from 'carbon-icons';
import { Icon } from 'carbon-components-react';

<Icon name="add--solid" />
<Icon icon={addSolid} />
```

References:

- [`#carbon-react`](https://ibm-front-end.slack.com/archives/C2K6RFJ1G/p1550777332018700)
- [`#carbon-components`](https://ibm-front-end.slack.com/archives/C046Y0YUD/p1550777335013200)

## Vanilla

So far, we haven't heard back from individuals using this only in Vanilla.js. Most likely we'll need to inform these individuals of:

- Name changes
- New code to help with rendering to DOM and to string (for handlebars)
- Handlebar helper

**Comment by elizabethsjudd** [comment]
@joshblack FYI, the WH team is using the handlebars icon helper
