### ISSUE TITLE
Contribution: Text toolbar

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon#2447]
**Is your feature request related to a problem? Please describe.**
The usage of an old widget in a new UI to write runbooks or messages directly.
<img width="1134" alt="screen shot 2019-02-20 at 11 21 29" src="https://user-images.githubusercontent.com/47557215/53085153-8fc88280-3502-11e9-891c-d6e67ce293a7.png">

**Describe the solution you'd like**
I have designed a new component with the Carbon styleguide to type guided tasks easily (runbook automation) while improving the collaboration among teams.

All files here: https://ibm.box.com/s/4rv1jw7xwuv8c8rvqbxp9057qzlydkva

Screenshot details:
<img alt="screen shot 2019-02-12 at 10 47 18" width="1238" src="https://user-images.githubusercontent.com/47557215/52626558-bc055300-2eb3-11e9-8e77-758208e915ed.png">

<img alt="screen shot 2019-02-12 at 10 47 57" width="1238" src="https://user-images.githubusercontent.com/47557215/52626577-c32c6100-2eb3-11e9-8110-c2fe64321bda.png">

Some redlines:
<img width="1240" alt="screen shot 2019-02-20 at 12 08 45" src="https://user-images.githubusercontent.com/47557215/53087857-6f032b80-3508-11e9-95a9-a54b2a020ddb.png">

Different color background:
<img width="1216" alt="screen shot 2019-02-20 at 12 09 11" src="https://user-images.githubusercontent.com/47557215/53087882-7fb3a180-3508-11e9-8c46-8aef669ba263.png">

**Comment by m-battelli** [comment]
Create symbols on sketch on my plan 💪

**Comment by chrisconnors-ibm** [comment]
@aagonzales as a step towards this component as a contribution, do we need a separate issue articulating the as resolved design? ie @joshblack do we need some cleanup here so any dev in the world could pick up this spec and develop it?

thinking here is this will be an experimental component with a design spec, a sketch symbol, and usage/style documentation until we get a building team to code it.

**Comment by aagonzales** [comment]
@chrisconnors-ibm @m-battelli Yeah I think we could make a new clean issue with the final design specs in it and then maybe a list of the different contribution points, like:

### Component contribution

**Design:**
- [x] Design spec
- [x] Carbon approval (link to this issue)
- [ ] Sketch symbols for Kit
- [ ] Website guidelines (experimental usage and style)

**Dev:**
- [ ] Vanilla
- [ ] React
- [ ] Documentation

**Comment by asudoh** [comment]
For code perspective, given how compound the component is, great to see the code is maintained in a separate repo from https://github.com/carbon-design-system/carbon. Still be in `carbon-design-system`, though, and I think we can provide a link so such separate library is easy to find.

**Comment by m-battelli** [comment]
@aagonzales @chrisconnors-ibm 
Skecth with all symbols is here: https://ibm.ent.box.com/file/475636979327
It is a work in progress :-)
Thank you @laurenmrice for the support 👍

**Comment by m-battelli** [comment]
Skecth with all symbols is here: https://ibm.ent.box.com/file/475636979327
It is an updated of the work in progress. I have included Lauren feedback and I'm proceeding with custom dropdowns for text color and text alignment.

**Comment by m-battelli** [comment]
I'm continuing to design the sketch symbols for this component.

**Comment by m-battelli** [comment]
I’m creating Sketch symbols related to responsiveness.

***Pending issues (or new contributions):**
- Medium search bar (40 px) to integrate to text bar;
- Interaction pattern related to search & highlight text
<img width="598" alt="Screenshot 2019-08-30 at 18 32 14" src="https://user-images.githubusercontent.com/47557215/64036888-8cb6ea80-cb54-11e9-96cc-763777607010.png">

Thanks @laurenmrice for you constant and precious support!

**Comment by m-battelli** [comment]
I'm designing the Sketch symbols for responsiveness.

**Comment by m-battelli** [comment]
@laurenmrice Updates
Done:
1. Replaced undo/redo, mini-chevron, checkbox icons (as new IDL icons);

2. Inserted new search (40 px) 
<img width="1505" alt="Screen Shot 2019-10-14 at 17 01 05" src="https://user-images.githubusercontent.com/47557215/66762419-402a3300-eea6-11e9-89c7-989e4cc50459.png">
I have changed the color of bottom border to hide the gray line. Make sense?


3. I can't hide the same line for typeface/size dropdowns because that symbol is locked. For this reason, I have adopted the selection approch used in the pagination bar. Make sense?

4. I have created new symbols for the entire text bar based on width size, advanced and simple.
I have designed 2 different resize behaviours for "Advanced / 1 row" symbol. Which one is correct?
<img width="1308" alt="Screen Shot 2019-10-14 at 17 26 30" src="https://user-images.githubusercontent.com/47557215/66763232-c8f59e80-eea7-11e9-83af-31fa1b00a084.png">
So I can apply the same for "Advanced / 2 rows" and "Simple" symbols.


5. I have uncluded the overflow menu for this latest symbols. Have I design the opened menu?
<img width="650" alt="Screen Shot 2019-10-14 at 17 30 51" src="https://user-images.githubusercontent.com/47557215/66763575-6650d280-eea8-11e9-9855-7d89ae48bae4.png">

6. I have re-organized all the file with Rename-it :-)
The latest sketch file is here: https://ibm.ent.box.com/file/475636979327

Pending: Organizing idea for experimental section (content & images).
🐢 

Thanks!

**Comment by m-battelli** [comment]
@laurenmrice 
All updated stuff related this contribution is here:
https://ibm.ent.box.com/folder/66697964510

Documentation for Experimental section (Work in progress):
https://ibm.ent.box.com/folder/90602971210

**Comment by laurenmrice** [comment]
@m-battelli  Thank you Myriam !! Will get to this next week :)

**Comment by m-battelli** [comment]
@mjabbink 
The textual content for Text bar experimental section is ready!

Usage: https://ibm.ent.box.com/notes/549429666421
Style: https://ibm.ent.box.com/notes/549446327433

A facsimile of Carbon website layout is here: https://ibm.ent.box.com/file/549427944650

All hi-resolution images are here: https://ibm.ent.box.com/folder/90602971210

**Comment by mjabbink** [comment]
This is an open issue to have this component/pattern contributed by end of year

**Comment by m-battelli** [comment]
@mjabbink thanks for the update!

**Comment by m-battelli** [comment]
Related design variations here #4948 
@aagonzales any feedback/updates on that?

**Comment by creckling** [comment]
Is this being delivered into Carbon? I can't tell where it is falling in the backlog. Thanks.

**Comment by mjabbink** [comment]
@janchild @connor-leech @jeanservaas @aagonzales What will it take to get this added to the Patterns section? It seems so close it’s a shame to not take it to the finish line. If Carbon too busy can @creckling team maybe help polish it off so we can get it added?

**Comment by chrisconnors-ibm** [comment]
@mjabbink - generating and publishing the usage guidance and a design kit asset is probably possible now, but I bet @creckling is likely referring to is an actual coded component.

@creckling what this effort has gone begging for is a developer resources. Any chance your folks can pitch in here against this design spec?

**Comment by mjabbink** [comment]
Yes. Carbon team should get this guidance/kit asset and agree it would be magic to get developer resources!

**Comment by creckling** [comment]
Yes, I was looking for code - right now they use a third party editor, so likely will just re-theme it rather than build one.

**Comment by m-battelli** [comment]
@chrisconnors-ibm @mjabbink I have generated all the documentation for the usage and style guidance (Experimental section for Carbon website) last year. Just a reminder if this can still be useful to you: https://ibm.ent.box.com/folder/90604183280

**Comment by mjabbink** [comment]
@m-battelli thanks for sending. I think the team is backed up on some other urgent priorities but have your content on the back burner to finish up soon. I’ll let @Lauren or @connor-leech chime because I think they’re on the case. We are eager to get it into the patterns page so it’s only because there is way too much work for our little tiny team.

**Comment by laurenmrice** [comment]
@m-battelli  Yes, this is something we definitely need to pick up, it is just the matter of prioritizing it, dedicating a design resource to it (which we are limited on right now) and finding someone to implement code. Our main priority at the moment is revamping our documentation for component usage and code tabs on the Carbon website. Having the documentation you wrote around textbar is very helpful and we just need to transfer it over to our new template. Since we are already in documentation mode I would hope we could extend our efforts to get this in soon.

**Comment by janchild** [comment]
@mjabbink I'm adding this to the list so it's considered in the next planning session.

**Comment by m-battelli** [comment]
Ok, thanks for the update  @mjabbink @laurenmrice
