### ISSUE TITLE
PaginationV2 select '-webkit-appearance: none' missing

### ISSUE THREAD

**Issue by MikeyZat** [carbon-design-system/carbon#2451]
## Brief description
The black arrow isn't supposed to be visible. It seems that '-webkit-appearance: none ' in .bx--select-input is missing

![select-bug-view](https://user-images.githubusercontent.com/41756225/57456564-1113f380-726e-11e9-98f6-907e88623fb0.png)

## Detailed description

While using PaginationV2 component the select with class 'bx--select-input' should have property '-webkit-appearance' set to 'none' in order to hide black arrows and let the Icon be the only one.

![select-missing_property](https://user-images.githubusercontent.com/41756225/57457529-fe022300-726f-11e9-8300-6b866fd9899e.png)

 It has 'appearance' set to 'none' but it is not enough, -webkit and -moz prefixes should also be included. Potential fix on screen below:
![select-potential-fix](https://user-images.githubusercontent.com/41756225/57457547-03f80400-7270-11e9-844c-b5055681f9ef.png)

Moreover, the purple arrow isn't vertically centred but that issue is already opened here:

https://github.com/carbon-design-system/carbon-components-react/issues/2128

> Is this issue related to a specific component?

Yes, PaginationV2

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect black arrows of select to be hidden, they are visible instead. I'd like to see '-webkit-appearance: none' and '-moz-appearance:none' added to class 'bx--select-input'

> What browser are you working in?

Mozilla Firefox, Google Chrome, Edge

> What version of the Carbon Design System are you using?

9.84.3

## Steps to reproduce the issue

1. Use PaginationV2 component with more than 10 elements of data in Table
2. Look for Select element with class 'bx--select-input'
3. Inspect that element

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Let me explain how Carbon works with the original issue you reported - To compile Carbon Sass code, it has to involve `autoprefixer` to translate [our `appearance: none` code](https://github.com/carbon-design-system/carbon/blob/v9.90.0/src/components/select/_select.scss#L36) to `-webkit-apperance: none`. Hope this makes sense to you - Don't hesitate to let us know otherwise!
