### ISSUE TITLE
Radio button selection in the Carbon data table should support table actions

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2455]
[Originally reported by Tom Ginader in IBM Slack](https://ibm-cloudplatform.slack.com/archives/C2K6RFJ1G/p1556634610314900):

>Hello. How would I use radio buttons in DataTable to have actions? I was able to get regular selection with batch actions working properly, but we realized that we only want our users to select one item at a time. I'm not seeing any examples that combines radio button selection with some kind of action.

**Comment by chrisconnors-ibm** [comment]
This patterned has not been evaluated for inclusion in our master branch

**Comment by emyarod** [comment]
the team has decided not to implement this behavior at this time, but if you believe that this use case should be part of the core Carbon library feel free to provide your thoughts below

as a workaround the structured list may be a better component for this use case
