### ISSUE TITLE
Missing descriptive text in label elements for toggle component.

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon#2465]
## Environment

> Operating system
MacOS Mojave

> Browser

Chrome

> Automated testing tool and ruleset

> Assistive technology used to verify

## Detailed description

> What version of the Carbon Design System are you using?

  "carbon-components": "9.57.0",
    "carbon-components-react": "6.54.1",
    "carbon-icons": "7.0.7",

> What did you expect to happen?

> What happened instead?

> What WCAG 2.1 checkpoint does the issue violate?

<AVT> Provide descriptive text in label elements

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/46310374/57198877-c7898700-6f95-11e9-843f-e18342d708dc.png)

- Notes
I tried to add some text in  label  here...., that pass the test(DAP violation)

**Comment by reeteshsingh93** [comment]
Issue still persists...
![image](https://user-images.githubusercontent.com/46310374/60663722-a3ef9980-9e7d-11e9-888c-1097d7894c7c.png)

**Comment by reeteshsingh93** [comment]
Issue still persists...
![image](https://user-images.githubusercontent.com/46310374/60663854-00eb4f80-9e7e-11e9-9bca-8ee6613029da.png)

**Comment by reeteshsingh93** [comment]
I created a sandbox and found descriptive text is not available in label element.
I have tested this manually don't have any option to perform accessibility test.

https://codesandbox.io/s/cc4k4

![image](https://user-images.githubusercontent.com/46310374/60664485-b10d8800-9e7f-11e9-97c6-0bb0ab8988ea.png)

**Comment by emyarod** [comment]
@reeteshsingh93 this appears to be resolved by https://github.com/carbon-design-system/carbon-components-react/pull/1771 in v6.81.4. are you able to upgrade your dependencies?
