### ISSUE TITLE
DataTable with batch actions, search bar positioning.

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/carbon#2471]
## Detailed description
![data-table](https://user-images.githubusercontent.com/12755042/57474592-123a2600-7258-11e9-84ee-52b6cadb5d20.gif)
When using the DataTable with batch actions, after searching and selecting an item from the data table, the search box overflows with the blue selected items div.

**Component:** http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20batch%20actions&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected the selected items and action bar to be out of the way of the search field.

> What browser are you working in?
Google Chrome: Version 74.0.3729.131

> What version of the Carbon Design System are you using?
Version 10

## Steps to reproduce the issue

1. Click search
2. Type the number "3"
3. Click on any item in the table

## Additional information
<img width="726" alt="Screen Shot 2019-05-09 at 12 48 22 PM" src="https://user-images.githubusercontent.com/12755042/57474889-cdfb5580-7258-11e9-85ec-2966cf8e2222.png">

**Comment by aledavila** [comment]
Seems like this has been resolved. Can't reproduce in Chrome Version 79.0.3945.130 and Carbon React v7.9.3. If you feel this is still an issue feel free to comment here with a code sandbox example. Thanks!
