### ISSUE TITLE
dropdown text overflow

### ISSUE THREAD

**Issue by anvesh1305** [carbon-design-system/carbon#2472]
## Detailed description

> Describe in detail the issue you're having.

select the CloudGuard version dropdown the text in the selected dropdown overflows the container

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the text to fit in the container but instead the text came out the box. I would like to see the text within the container

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components: "9.x",
carbon-components-react": "6.x",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

GCAT team - application already in production

## Steps to reproduce the issue

1. Select CloudGuard version dropdown
2. You should be able to see the text going out the box

![CP_dropdown](https://user-images.githubusercontent.com/31553959/57163296-c94d2200-6dbe-11e9-859e-40ee13b61873.jpeg)

**Comment by dakahn** [comment]
Closing as resolved. Happy to reopen if that's not the case 👍
