### ISSUE TITLE
Support custom links in UI shell

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2473]
We should make our UI shell header links more flexible to support rendering custom links e.g. wrapping React Router `<Link>`s. Currently when we use `<HeaderMenuItem>` with React Router `<Link>`s the styling is broken, it would be a great enhancement to support this type of use case

(related https://github.com/carbon-design-system/carbon-tutorial)

**Comment by mattrosno** [comment]
Instead of wrapping, is it acceptable/supported to `<HeaderMenuItem element={Link} to="/foo">` (`Link` coming from `react-router-dom`)?

**Comment by emyarod** [comment]
to directly replace the element that will be fine, the question now is whether or not we want to support the added flexibility of rendering your own header menu item content (similar to our icon and menu content rendering strategy in react

**Comment by pedrosimao** [comment]
So, how was this solved? I am facing the same issue

**Comment by emyarod** [comment]
in this case for the UI shell it's handled by the element prop https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L27

**Comment by pedrosimao** [comment]
@emyarod I have tried this, but it seems the `element` is not recognized as a valid prop by typescript, which I am using in my project... maybe the `@type/carbon-components-react` package should be updated?

**Comment by pedrosimao** [comment]
Just correcting. It seems on typescript definitions `element` is expected to be a string. Which in this case it is obviously not a string. So, I am not sure if changing `string` to `any` would be a good idea. Please take a look here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9883c74ed7aa382d68fdf3e3b67a9d2c40f523f9/types/carbon-components-react/lib/components/UIShell/Link.d.ts

**Comment by KunalSolanke** [comment]
A workaround for the time being is , just ignore the href prop and add onClick to HeaderMenuItem with history.push("/foo")
