### ISSUE TITLE
[RFC] TypeScript migration 

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#2479]
# Summary

TypeScript is a superset of Javascript – all Javascript is valid Typescript. However, once a project has typescript enabled, you can annotate your code to provide type hints to your users and other developers.

Just as _shared styles_ between Carbon frameworks improves user experience, so to would _shared behavior_. Typesafety allows us to ship components that perform and behave as expected.

Related issues: #1296, #727, #1103, #580

# Motivation

End users, product developers, as well as Carbon developers would all benefit from the addition of type safety to Carbon products

* **End Users** – by shipping more resilient, bug free components end users will encounter fewer unexpected edge cases
* **Product developers** – developers would be guided towards proper API usage and would be alerted to new or changed apis.

![JS Example One](https://ts-rfc-vpicone.tagteam1.now.sh/js1.gif)

![JS Example Two](https://ts-rfc-vpicone.tagteam1.now.sh/js2.gif)

* **Carbon developers and Typescript developers** –

- Fewer `Uncaught TypeError(Cannot read x of undefined` or spelling errors means more time on real issues.
- Fewer undefined refs and instance properties
- Reduce reliance on `null` and `undefined` guards means more resiliant APIs
– Alerted to misuse of props, state, third-party library, and dom errors while writing your code.

![TS Example](https://ts-rfc-vpicone.tagteam1.now.sh/ts1.gif)

# Design

There are currently to main ways to compile typescript into javascript(the typescript compiler, and through babel. Since our project is already using Babel, switching to typescript would be unnecessary. 

Namespaces and const enums are not supported by the babel compilation, however, this can be mitigated with compiler configuration.

As we look toward migrating codebases to a mono-repo, typesafety will offer a means to share types between projects and permit large scale refactors with confidence.

# Drawbacks

- Time spent onboarding carbon devs to typescript
  - I volunteer as tribute
- Friction to carbon contributors new to the project
  - would empower them to make more meaningful changes
  - would _reduce_ friction for folks onboarding to product teams

# Alternatives

## Non-Typescript
- FlowType
  - call-site type checking is nice
  - Lots of projects switching to TS(Jest, Expo, Atlassian, Yarn.
  - Far fewer third party integrations 1/10th of the questions on SO
- JSDoc
  - some bugs around object types
  - errors in jsdoc means no warnings/errors it just won't get annotated

## TypeScript without migration
These solutions offer some of the benefits of TypeScript types with different drawbacks. While the core library would still be standard JavaScript maintaining types would be a manual effort. 

The main issue with these strategies is that they require a much more manual effort up front and the types would be of lower quality than those generated natively from the project in situ.

### Definitely-typed
  - Types published using the DefinitelyTyped repo https://github.com/DefinitelyTyped/DefinitelyTyped
  - Recommended solution from TS team for no TypeScript projects
  - Rely on community involvement
  - Issues keeping types in parity with new library features and changes
  - We don't benefit from the types internally
### Internal `.d.ts` files
  - Less opportunity for community engagement, relies more on project maintainers to maintain types
  - Types are version tied to the actual code, making updating types an imperitive with each PR.
  - Example: https://github.com/mui-org/material-ui/tree/next/packages/material-ui

# Adoption strategy

At no point will typescript migration stop or prevent work on the project. TypeScript can get out of the way when necessary (`@ts-ignore` and `any` or `unknown` types). **It will never break builds unless we chose to enable that behavior.**

While each of the Carbon javascript projects would benefit from the addition of types. I believe the most valuable library at this time would be carbon components react (CCR).

Since we already have some run-time type checking through `prop-types`, we already have a starting point. In addition, thanks to `prop-types` CCR developers are already at least slightly familiar with the constraints imposed by types.

### A – [Just rename everything to `.ts` and `.tsx`](https://twitter.com/jamonholmgren/status/1089241726303199232)

1. The first pass at converting the project will rename the files and add babel, storybook, and jest configuration to handle these new file types.

1. The initial config will have the loosest possible config. Separate PR's will be made to turn on each of the strict-mode rules separately resolving issues as they come up.

1. Any objective errors uncovered as a result of the conversion will be resolved as part of the same PR.

1.  Prop types will be defined at the same level of specificity as the `prop-types`. No unnecessary types added.

1. Types can be shipped from day one

### B – Leave the files as `.js` config enable `allowJS` and `checkJS`
1. Recommended by TypeScript team for large projects using the TypeScript compiler (likely not us)
1. All new code should be written as `.ts`
1. Gradually migrate files to `.ts`
1. Types can be shipped once all `.js` files are converted to TypeScript

## [Migration stories from others](https://github.com/sw-yx/react-typescript-cheatsheet/blob/master/MIGRATING.md#links)

- [hootsuite](https://medium.com/hootsuite-engineering/thoughts-on-migrating-to-typescript-5e1a04288202): Thoughts on migrating to TypeScript
- [clayallsop](https://medium.com/@clayallsopp/): Incrementally-migrating-javascript-to-typescript-565020e49c88 'Incrementally Migrating JavaScript to TypeScript
- [pleo](https://medium.com/pleo/migrating-a-babel-project-to-typescript-af6cd0b451f4): Migrating a Babel project to TypeScript
- [mstsreactconversionguide](https://github.com/Microsoft/TypeScript-React-Conversion-Guide): TypeScript React Conversion Guide
- [entria](https://medium.com/entria/incremental-migration-to-typescript-on-a-flowtype-codebase-515f6490d92d): Incremental Migration to TypeScript on a Flowtype codebase

**Comment by vpicone** [comment]
NOT STALE

**Comment by JSoet** [comment]
Just wanted to mention my support for moving to typescript! Our team also uses typescript, and of course I would love having types when using carbon.... 

But also I think in the long run switching to typescript will improve the quality of the carbon code... Our team also struggled with the decision to decide whether or not to adopt typescript, whether it was worth the effort for our developers to deal with the extra overhead of learning typescript and typing everything, but overall I think everyone on our team is now happy that we did it. 

Of course there's some times still when we are struggling with the typing even though the code itself works, and some times where there can be bugs that typescript didn't catch because the types are only as good as you make them... But it has allowed us to be a lot more confident in doing refactorings, and allowed us to confidently make some big changes and improvements to our codebase that we were usually too timid to do before...

**Comment by vpicone** [comment]
Totally agree, even in partially implementing typescript I found some issues that I wouldn’t have detected otherwise. I feel like for a top level component library those sorts of issues should be air tight.

**Comment by spgill** [comment]
Here to voice my support for TypeScript typings for Carbon.

I work on a team _within IBM_ with a codebase written almost entirely in TypeScript. With the big push for us to adopt the new Carbon/IDL styles into our product, it's been a really hard decision for us to pull in the `carbon-components-react` package given its lack of TS support and what that would mean for our code integrity. In the interim we're going to have to rely on creating our own rudimentary typings to get by. Contributing our typings to definitely typed is an option, but it would take a back seat to our business priorities.

Inclusion of a full suite of TS typings into the official codebase (or through definitely typed) would be a huge boon to my team, and I'm sure several others that are looking to adopt Carbon.

**Comment by kalbert312** [comment]
Moved my typings to a definitelytyped PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37442

**Comment by michaeljota** [comment]
Do you have any updates on this? I think moving into TS will really improve the developer experience, including your own.
