### ISSUE TITLE
A11y: The selected icon is missed with radio button in Windows high contrast model - *version 9 support*

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#2485]
We fixed for v10 in https://github.com/IBM/carbon-components-react/issues/1850

But support is required for v9, as per https://github.ibm.com/Bluemix/Bluemix.UnifiedSupport/issues/1873. @dakahn, could you take a look at this and scope effort of fix?

**Comment by tw15egan** [comment]
Closing in favor of #6748
