### ISSUE TITLE
Explore strategies for enabling fully controlled components

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#2489]
### Summary

Problem: We want to give developers as much control as possible over the state of their application. However, we don't want to require developers to totally manage the state of each component.

I believe we should explore patterns that allow a component to be uncontrolled by default, but permit developers to use them in a controlled fashion should they so choose.

[Info on controlled & uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html).

### Justification

Some components can operate simultaneously as both controlled and uncontrolled in a single instance. This causes conflicting states and buggy components behavior.

Currently, for fully controlled components, developers must use a key to force re-renders. This works, and is a recommended alternative to the issue mentioned above, however a new/random key might not always be available and using one results in a hacky developer experience.

To get around this, we've been using `getDerivedStateFromProps`. While this works in some instances, the implementation is often tough to reason about and can greatly complicate component logic especially if there are multiple controlled props. `getDerivedStateFromProps` is a static method that shouldn't care about a specific instance's state.

The React team covered our exact work around/implementation [here](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#2-compare-incoming-props-to-previous-props-when-computing-controlled-values) and discussed it's buggy nature.

More info: [You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html)

### Desired UX and success metrics

* Establish a pattern for using a component in both a controlled and uncontrolled fashion.

### "Must have" functionality

* The component should be uncontrolled by default with the ability to use it in a controlled manner.
* The component should never be both controlled _and_ uncontrolled

### Milestone: Tech Debt Q2/Q3

PR incoming

**Comment by zachhardesty7** [comment]
Ran across this issue and it seems like with the latest update to 7.3.1 include #3015 fixes a similar bug seen in #3013. You can combine using defaultValue and value to cover my use case of trying to populate fields programmatically with API data.
