### ISSUE TITLE
Expose icon-only button in Carbon React documentation

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2490]
Related: https://github.com/IBM/carbon-components/pull/2287, https://github.com/carbon-design-system/carbon-components/pull/2366

**Comment by emyarod** [comment]
also dependent on https://github.com/carbon-design-system/carbon/pull/2781

**Comment by asudoh** [comment]
@emyarod Is this still of your interest...? Thanks!

**Comment by emyarod** [comment]
yes this is not stale
