### ISSUE TITLE
FileUploader component should provide props to show already uploaded file

### ISSUE THREAD

**Issue by geet** [carbon-design-system/carbon#2494]
## Summary
FileUploader component should provide a way to show filename of existing file and a clear button to delete the file
## Relevant information
If we have already uploaded a file in the server, based on the filename, is there a way to show the filename in the FileUploader label and a delete button to delete the already uploaded file.

**Comment by asudoh** [comment]
#2916 may be a good candidate to cover this use case, CC @emyarod
