### ISSUE TITLE
[Data Table] Table select All problem after searching some items

### ISSUE THREAD

**Issue by Junstar17** [carbon-design-system/carbon#2496]
I found one strange thing when I use Data table. I'm not sure it's bug or just your policy.
After searching some items by using search toolbar , I can't select only those items at once by using Select All checkbox.

The detail situation is blow.

step.
There are 3 items in data table.
![스크린샷 2019-04-09 오전 11 20 03](https://user-images.githubusercontent.com/29361653/55772983-99657400-5ac9-11e9-8077-296806bb4512.png)

1. Search some ID by using search toolbar 
![스크린샷 2019-04-09 오전 11 20 29](https://user-images.githubusercontent.com/29361653/55772993-a71af980-5ac9-11e9-8c58-2fd359e664c1.png)

2. Click the checkbox in the head of the table ( "Check All box " )
![스크린샷 2019-04-09 오전 11 20 42](https://user-images.githubusercontent.com/29361653/55773005-b306bb80-5ac9-11e9-8807-5301233f19ea.png)

At this time, you can see all of items are checked not only searched item but also the others
 - expectation : Selected 1 item
 - result : Selected 3 items (All)

**Comment by pkrisz0** [comment]
Hi guys, any progress on this?
