### ISSUE TITLE
AVT 3 - Select, Accordion, Form Component, and Timepicker: Arrow key SVG image should not receive focus.

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon#2497]
## Environment
macOS Mojave version 10.14.2
Chrome version 72.0.3626.96 (Official Build) (64-bit)
## Detailed Description
SVG Arrow can be read by VoiceOver and used to select an option, but it is not in the tab order and it announces the user still needs to select an option, which makes it confusing to a screenreader user. 
To reproduce:
1. Tab to the Select box and select an option
2. Click Control-Option Right Arrow to the Arrow icon and VO announces the alt, "open list of options", which is the same list the user just made a select from. 
<img width="291" alt="Screen Shot 2019-04-08 at 2 40 38 PM" src="https://user-images.githubusercontent.com/21676914/55753552-4085d500-5a10-11e9-86eb-9621cf802bec.png">
Note: The Arrow icon should not receive focus and include aria-hidden="true", similar to the [Vanilla Select component](https://www.carbondesignsystem.com/components/select/code).

**Comment by snidersd** [comment]
@dakahn I retested this on the Carbon v10 React Component both against the example in the React documentation and locally. VoiceOver must be active to reproduce it. As you can see in the screen shot below, the arrow and focus and is read by VO. 
<img width="661" alt="Screen Shot 2019-05-10 at 12 18 11 PM" src="https://user-images.githubusercontent.com/21676914/57546516-82ad7980-7322-11e9-8fd7-3f24d8e310ce.png">

Also note: I tested it on the Vanilla Select Component and it works as expected.

**Comment by dakahn** [comment]
Fixed! Nice
