### ISSUE TITLE
Input value will move when hover on it

### ISSUE THREAD

**Issue by Jaorji** [carbon-design-system/carbon#2499]
Steps to reproduce it:

1) create a carbon react input
2) set an input value
3) set the input to `disabled`

hover on the input value text, and it will move.

OS:
mac

Browser:
Chrome

**Comment by dakahn** [comment]
@Jaorji could you give us a case to test against so we can validate and debug? 😄

**Comment by joshblack** [comment]
Hi there! Looks like there hasn't been any activity in a while. If you have a chance to add steps to reproduce, we'd be happy to open this up again!
