### ISSUE TITLE
Min and Max dates in calendar  of datapicker are not updated upon component update

### ISSUE THREAD

**Issue by rcsatheeshkumar** [carbon-design-system/carbon#2500]
## Detailed description

Let's assume that minDate, maxDate of datepicker are 2nd April 2019 and  From DatePickerInput and To DatePickerInput's value are also 2nd April 2019. Those values are passed as props to the datepicker. Now it renders and works perfectly fine for the initial rendering. Now, when  the props  are changed and the component gets updated, the from and to value of the datepickerinput changes correctly but once any of the input is clicked to see the  calendar, it still shows the old min and max dates for range.

> Is this issue related to a specific component?
 Date picker

> What did you expect to happen? What happened instead? What would you like to see changed?
The max and min range  displayed in the visual calendar should get updated when the props for the same are changed

> What browser are you working in?
Chrome 73.0.3683.86

> What version of the Carbon Design System are you using?
   V7.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
--Internal Product development

## Steps to reproduce the issue

1. Initially Datepciker will be displayed
2. Click on the button on the top to change the max and  min passed as props to the datepicker.
3. Now the input value in the datepicker would have changed
4. Now click on the input to see the calendar. The min and max range won't be changed and will show the same dates, passed during initial rendering

> Please create a reduced test case in CodeSandbox
>https://codesandbox.io/s/5z7j8w3lvk

## Additional information

- Screenshots or code
- Notes

**Comment by figfofu** [comment]
@asudoh 
I am facing the same problem as @rcsatheeshkumar .
I have a DatePicker component and I want to restrict the max/min date when users click on the range-calendar. (meaning that it if the user clicks on the "From" calendar, I want to set the maxDate to not over the value in the "To" calendar and versa vice).
```
<DatePicker
			{...ATTRS.datePicker()}
			datePickerType="range"
			minDate = {this.state.minDate}
			maxDate = {this.state.maxDate}
		>
</DatePicker>
```
I have a function to update the minDate and maxDate like
```
...
this.setState({
			maxDate: toDateString,
			minDate: null,
		});
...
```
However, minDate and maxDate do not get reflected to the flatpickr component.

A quick look into the DatePicker.js

The minDate and maxDate do get initialized in the componentDidMount function.
```
if (this.inputField) {
          this.cal = new _flatpickr.default(this.inputField, {
            defaultDate: value,
            appendTo: appendToNode,
            mode: datePickerType,
            allowInput: true,
            dateFormat: dateFormat,
            locale: _index.default[locale],
            minDate: minDate,
            maxDate: maxDate,
            plugins: datePickerType === 'range' ? [new _rangePlugin.default({
              input: this.toInputField
            })] : '',
            clickOpens: true,
            nextArrow: this.rightArrowHTML(),
            leftArrow: this.leftArrowHTML(),
            onChange: function onChange() {
              if (_onChange) {
                _onChange.apply(void 0, arguments);
              }
            },
            onReady: onHook,
            onMonthChange: onHook,
            onYearChange: onHook,
            onOpen: onHook,
            onValueUpdate: onHook
          });
          this.addKeyboardEvents(this.cal);
        }
```
but there is no update in the render function
![スクリーンショット 2019-07-18 17 17 29](https://user-images.githubusercontent.com/5977961/61441148-f81b7300-a97f-11e9-8299-bdad379adf59.png)

I can explain more if you are comfortable with the IBM email.

**Comment by asudoh** [comment]
@figfofu Do you change `minDate`/`maxDate` after initialization? I'm asking this because `minDate`/`maxDate` are [Flatpickr creation options](https://flatpickr.js.org/options/) and thus does not seem to support change after initialization. If you are not changing `minDate`/`maxDate` after initialization, would you be able to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox? Thanks!

**Comment by figfofu** [comment]
@asudoh 
Yes, I want to change `minDate/maxDate` on the fly.
I think Flatpickr does support this feature by using
`set('minDate', dateStr)`
`set('maxDate', dateStr)`
Maybe we can use it for our `this.cal` variable?
See: (https://github.com/flatpickr/flatpickr/issues/1380)

**Comment by asudoh** [comment]
> Maybe we can use it for out `this.cal` variable?

Makes sense to me.
