### ISSUE TITLE
Overflow menu - Support for dynamic menu content in top direction

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#2501]
### Summary

If menu content changes after initialization with `<OverflowMenu direction={top}>`, the menu position gets stale. This issue is for tracking an effort to see how we can address this use case.

### Justification

One of such use cases is putting skeleton in overflow menu, which sounds reasonable.

**Comment by asudoh** [comment]
Just mulling it over... Floating menu specifying bottom position instead of top position may be a quick workaround.

**Comment by designertyler** [comment]
@asudoh Can we get more info or description for this?

**Comment by asudoh** [comment]
@designertyler Thank you for asking, I think below movie explains the problem:

![overflow-direction-top](https://user-images.githubusercontent.com/1259051/76196389-7d180d00-622d-11ea-8b24-790d40fd2905.gif)

<details>
    <summary>The code (Can be used in place of <a href="https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/components/OverflowMenu/OverflowMenu-story.js#L46-L69"><code>OverflowMenuExample</code> in <code>OverflowMenu-story.js</code></a>)</summary>
<div class="highlight highlight-source-js"><pre><span class="pl-k">const</span> <span class="pl-c1">OverflowMenuExample</span> <span class="pl-k">=</span> ({ overflowMenuProps, overflowMenuItemProps }) <span class="pl-k">=&gt;</span> {
  <span class="pl-k">const</span> [<span class="pl-c1">items</span>, <span class="pl-c1">setItems</span>] <span class="pl-k">=</span> <span class="pl-en">useState</span>([<span class="pl-s"><span class="pl-pds">'</span>option 1<span class="pl-pds">'</span></span>]);
  <span class="pl-en">useEffect</span>(() <span class="pl-k">=&gt;</span> {
    <span class="pl-c1">setTimeout</span>(() <span class="pl-k">=&gt;</span> {
      <span class="pl-en">setItems</span>([<span class="pl-s"><span class="pl-pds">'</span>option 1<span class="pl-pds">'</span></span>, <span class="pl-s"><span class="pl-pds">'</span>option 2<span class="pl-pds">'</span></span>, <span class="pl-s"><span class="pl-pds">'</span>option 3<span class="pl-pds">'</span></span>]);
    }, <span class="pl-c1">3000</span>);
  }, []);
  <span class="pl-k">return</span> (
    <span class="pl-k">&lt;&gt;</span>
      <span class="pl-k">&lt;</span>div style<span class="pl-k">=</span>{{ height<span class="pl-k">:</span> <span class="pl-s"><span class="pl-pds">'</span>200px<span class="pl-pds">'</span></span> }} <span class="pl-k">/</span><span class="pl-k">&gt;</span>
      <span class="pl-k">&lt;</span>OverflowMenu {<span class="pl-k">...</span>overflowMenuProps} direction<span class="pl-k">=</span><span class="pl-s"><span class="pl-pds">"</span>top<span class="pl-pds">"</span></span><span class="pl-k">&gt;</span>
        {
          <span class="pl-smi">items</span>.<span class="pl-en">map</span>(<span class="pl-smi">item</span> <span class="pl-k">=&gt;</span> (
            <span class="pl-k">&lt;</span>OverflowMenuItem
              {<span class="pl-k">...</span>overflowMenuItemProps}
              key<span class="pl-k">=</span>{item}
              itemText<span class="pl-k">=</span>{item}
            <span class="pl-k">/</span><span class="pl-k">&gt;</span>
          ))
        }
      <span class="pl-k">&lt;</span><span class="pl-k">/</span>OverflowMenu<span class="pl-k">&gt;</span>
    <span class="pl-k">&lt;</span><span class="pl-k">/</span><span class="pl-k">&gt;</span>
  )
};</pre></div>
</details>
