### ISSUE TITLE
PaginationV2 arrow icon misalignment

### ISSUE THREAD

**Issue by tozhangkai** [carbon-design-system/carbon#2502]
## Detailed description

> The arrow icon after the page number in PaginationV2 doesn't align correctly. I believe this is a regression introduced recently. I didn't see it in the previous versions. See here:
http://react.carbondesignsystem.com/?selectedKind=Pagination&selectedStory=v2&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
![image](https://user-images.githubusercontent.com/11453713/55261690-0105fe80-5242-11e9-8c0f-e61760286dc7.png)

> Is this a feature request (new component, new icon), a bug, or a general issue? 
This is a bug

> Is this issue related to a specific component?
Yes, `PaginationV2` in `carbon-components-react`

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected the icons align to the vertical center of the component.

> What browser are you working in?
Firefox, Chrome and Safari. The problem happens on all of them and doesn't seem to be related to a specific version of the browsers.

> What version of the Carbon Design System are you using?
`carbon-components-react:  6.114.0`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
I am working on an IBM product that has a quarterly release cycle, and we're moving to React with extensive use of carbon components.  

## Steps to reproduce the issue
The problem can be reproduced in the carbon-components online storybook:
http://react.carbondesignsystem.com/?selectedKind=Pagination&selectedStory=v2&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

## Additional information
See the screenshot above in the description section

**Comment by joshblack** [comment]
Going to close this out as it seems like there hasn't been any activity and may have a workaround. Feel free to comment if this isn't the case and we can re-open!
