### ISSUE TITLE
DatePicker range calendar only lets you edit start date

### ISSUE THREAD

**Issue by bkrissIBM** [carbon-design-system/carbon#2510]
## Detailed description
When the inputs for the DatePicker range are empty, selecting the start and end date via the calendar works as expected. The calendar remains open after clicking the start date so you can choose an end date as well. However, once there are dates set, if you click the calendar icon again to make a change, the calendar will close as soon as you choose a new start date, so you can't update the end date unless you click on the input itself. Having a calendar icon to the right of the end date input that only updates the start date input is confusing. It would be ideal if it allowed you to edit both start and end dates before closing the calendar.

> What browser are you working in?
Chrom 72.0.3626.119
Firefox Developer Edition 67.0b4 (64-bit)

> What version of the Carbon Design System are you using?
carbon-components: 9.89.0
carbon-components-react: 6.111.4
carbon-icons: 7.0.7

## Steps to reproduce the issue

1. Click calendar icon
2. Select start and end dates
3. Click calendar icon again
4. Select start date
5. Notice that the calendar closes before you can update the end date

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/6wo08vr8rn

**Comment by joshblack** [comment]
Hi there! :wave: Looks like there hasn't been any activity in a while. If you have the time to offer steps to reproduce we'd be happy to re-open this and help address this!
