### ISSUE TITLE
Tabs Component Dropdown does not close when clicking outside of the dropdown on the XS breakpoint

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2526]
Originally reported by @electrostaticfleece in https://github.com/IBM/carbon-components/issues/1919

> ## Detailed description
> 
> On the `XS` breakpoint, the Tabs component does not close when clicking outside of the dropdown when it is opened. This happens on both Carbon Components and Carbon Components React.
> 
> ![2019-02-26 09 55 07](https://user-images.githubusercontent.com/16194732/53426491-b0825380-39ac-11e9-9e63-88c7432f956a.gif)
> 
> 
> > What did you expect to happen? What happened instead? What would you like to see changed?
> 
> Upon clicking outside of the dropdown the Tabs component should close, similar to how it closes on the Dropdown component below: 
> 
> ![2019-02-26 10 03 08](https://user-images.githubusercontent.com/16194732/53427088-df4cf980-39ad-11e9-8026-eae0d57c71ae.gif)
> 
> 
> > What browser are you working in?
> 
> Chrome Version `72.0.3626.119 (Official Build) (64-bit)`. Though this happens in Firefox and I'm assuming all major browsers.
> 
> > What version of the Carbon Design System are you using?
> 
> Carbon Components `9.77.1` & Carbon Components React `6.97.0`
> 
> > What offering/product do you work on? Any pressing ship or release dates we should be aware of?
> 
> IBM Cloud
> 
> ## Steps to reproduce the issue
> 
> 1. Visit either the Carbon Components or Carbon Components React repository.
> 2. Select the Tabs Component
> 3. Reduce the size of the viewport to less than `768px`.
> 4. Open the Tabs component by selecting the visible Dropdown
> 5. Click outside of the Tabs component elsewhere on the screen. 
> 5. The open Tabs Dropdown should not close. 
>

**Comment by joshblack** [comment]
Related conversation for this: https://github.com/carbon-design-system/carbon/issues/4758
