### ISSUE TITLE
IE11 :: Any Modal component :: content overflows

### ISSUE THREAD

**Issue by elbrus** [carbon-design-system/carbon#2532]
## Detailed description

> Describe in detail the issue you're having.

Only in IE11 if you have enough components (or text) rendered inside modal body so that scroll bar should appear, then somehow it doesn't appear and content overflows.

> Is this issue related to a specific component?

Modal, ModalWrapper, ComposedModal

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v9

## Steps to reproduce the issue

1. Go to http://react.carbondesignsystem.com/
2. Go to 1st ModalWrapper example `transactional/passive modal`
3. Launch modal

## Additional information

<img width="1680" alt="screenshot 2019-02-18 at 16 27 21" src="https://user-images.githubusercontent.com/2395165/52960165-d8682a80-33a0-11e9-8b1e-4051bf614285.png">

p.s. I didn't check is it carbon-components-react or carbon-components issue

**Comment by elizabethsjudd** [comment]
We did extensive testing with this and unfortunately could not find a consistent way to achieve the desired behavior with CSS only but we have a fix that only gets triggered in IE11 in our JS that will set the height explicitly if needed: [function that applies the height for IE11](https://github.ibm.com/Watson-Health/design-library/blob/75446f69c546c0c273b118a01c0175dda46c9fb2/packages/pattern-library/src/components/modal/interactions.js#325) and [Remove the height on close]( https://github.ibm.com/Watson-Health/design-library/blob/75446f69c546c0c273b118a01c0175dda46c9fb2/packages/pattern-library/src/components/modal/interactions.js#L365)

**Comment by st004547** [comment]
Can be reproduced on https://react.carbondesignsystem.com/?path=/story/modal--default and turning on scrolling content via knobs.

I believe it's the `display: grid;` in the css that is not fully supported by IE.

UPDATE: 
Based on https://create-react-app.dev/docs/post-processing-css/
adding `/* autoprefixer grid: autoplace */` to the beginning of your css will allow autoprefixer to do it's thing for the grid.

For Sass, `/*! autoprefixer grid: autoplace */` seems to work.

And for completeness, there's an env var option in here: https://stackoverflow.com/questions/54505882/autoprefixer-doesnt-work-in-create-react-app-while-using-sass
