### ISSUE TITLE
Fileuploader component: Multiple prop set to false but all selected files are accepted.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon#2537]
## Detailed description

Hello Team,
We are using Fileuploader component, even though *multiple* prop is set to false one can select files one by one and all selected files are accepted.

## Steps to reproduce the issue

[http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploader&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs](url)

## Additional information

<img width="825" alt="image" src="https://user-images.githubusercontent.com/22093326/52634072-38b42380-2eec-11e9-9965-1afc26adc6ed.png">

**Comment by PAnilReddy** [comment]
@emyarod , We are also facing the same problem. Can we know when the fix can come.
Also can you give me the slack channel for this repo.

**Comment by emyarod** [comment]
this should be addressed in #3175, and we may look into backporting the fix for the legacy file uploader

**Comment by elhagin** [comment]
hi, are there any updates on this issue? the same thing is occurring to me and I can't find any solution. I see that it should be fixed in FileUploaderV2 but I'm not sure if that has been merged or not.

TIA!
