### ISSUE TITLE
ModalWrapper: Properly unused prop `handleOpen`?

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#2540]
## Summary

I'm not sure if I just don't see the use of the prop `handleOpen`.

The component uses a class method `this.handleOpen`, but the prop `handleOpen` seems not to be used in any way. I don't even see the prop passed down to a defined prop of the component `Modal`.

Maybe someone can have a look at this to check my supposition.

If I'm right, I would fix this issue together with a new feature I had in mind, when opening the source code.

## Relevant information

Here's the line of the prop definition:
https://github.com/IBM/carbon-components-react/blob/0e2f293fc1731b1a848aae090a5d530e9deac369/src/components/ModalWrapper/ModalWrapper.js#L17

**Comment by tw15egan** [comment]
Is there any action we want to take on this issue?

**Comment by asudoh** [comment]
@tw15egan Just my thoughts; Probably not. New modal doc in the work that explains how to implement a state manager for modal (instead of using `<ModalWrapper>`) would be the ultimate solution.
