### ISSUE TITLE
ComboBox: Filter Behavior Issue

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#2541]
## Detailed description
Allow the user to effectively filter the `ComboBox` list by entered text.

For example, if I have a `ComboBox` with the following list:

- `Red Apple`
- `Green Apple`
- `Green Onion`

And the user types `green` in the combo box input, the list would reduce to `Green Apple` and `Green Onion`.

I've found the `shouldFilterItem` prop which almost brings us to the functionality that we want.  However, not quite.  The issue is that the list always filters on the current selection.

For example, in the above scenario, if I select `Green Apple`, the list of choice is now reduced to a single item, `Green Apple`, because the current value becomes the filter.

I've set up a sandbox to illustrate (kudos for setting up the sandbox thing):

1. See https://codesandbox.io/s/045p9w40xp
2. Select one of the drop items
3. Now drop down the list again and you'll find that the list is now filtered by the current selection (which will be a single item).  The only way to get back to the list is to clear the current value, which is clunky.

## Potential Solution 1
I've played with other combo box widgets that had similar functionality and I came to the conclusion that the smallest change we could make that would improve the user experience is to only apply filtering when the input is changed (e.g. if I start typing in the input).  Once an item is selected and the drop list goes away, filtering is shut off until the next time I type into the input box.

Best case scenario is that I can simply do this, without any changes to the carbon code, but I've fiddled around and couldn't figure it out.

## Potential Solution 2
Another, more drastic approach, would be to separate the filter input from the current value input.  GitHub, for example, uses this approach.

![image](https://user-images.githubusercontent.com/32196820/52281876-6c63dc00-2935-11e9-9825-68224f507279.png)

Personally, I like this approach.  I've seen it in a few web apps and I've never fumbled on it.

**Comment by tay1orjones** [comment]
@milosKomiRajkovic94 Sorry there wasn't more info in this issue. The ComboBox intentionally behaves this way to follow the WAI-ARIA guidance for [Editable Combobox With Both List and Inline Autocomplete](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/)

The entire list is not shown until the current selection/search is cleared.
