### ISSUE TITLE
DatePicker: Error updating value in IE11

### ISSUE THREAD

**Issue by jared-schwalbe** [carbon-design-system/carbon#2542]
## Detailed description

> Describe in detail the issue you're having.

In IE11 when the prop "value" is updated on the DatePicker component, two errors crash the page. The errors are "Object doesn't support property or method 'setDate'" and "Object doesn't support property or method 'destroy'". These errors come from calling this.cal.setDate() and this.cal.destroy() in componentWillUpdate and componentWillUnmount respectively. This may be a bug with flatpickr seeing as this.cal is set to new flatpickr(...) in componentDidMount. EDIT: Inspecting in the browser shows this.cal coming back as [];

> Is this issue related to a specific component?

DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the DatePicker to work. Instead the page crashed in IE11. I would like to see the page not crash.

> What browser are you working in?

IE11 (11.2724.14393.0)

> What version of the Carbon Design System are you using?

6.28.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Firewalls

## Steps to reproduce the issue

1. Use the DatePicker component and control the value prop through the parent's state
2. Load the page in IE11
3. Watch the page crash

**Comment by tw15egan** [comment]
Using the fully controlled version of the component doesn't seem to cause any errors for me in IE11, so I'm going to close this.

If it is still broken, could you please provide a CodeSandbox link showing a way to replicate the problem? Thanks!

**Comment by Annmary12** [comment]
Hi, I am having the same issue. I am using the DatePicker from the carbon-component-react library. It works fine on Chrome but fails on IE 11.

<img width="688" alt="Screen Shot 2020-07-10 at 12 49 38 PM" src="https://user-images.githubusercontent.com/14803275/87151530-ee370200-c2ab-11ea-8992-4aa7d5d2a776.png">

**Comment by tw15egan** [comment]
Do you have a link to a CodeSandbox with an example of this behavior? 

I'd ensure you've got the proper polyfill configured for IE11

https://www.carbondesignsystem.com/get-started/develop/react/#getting-started

https://github.com/carbon-design-system/carbon/blob/master/packages/react/.storybook/polyfills.js

**Comment by Annmary12** [comment]
Hi, this question might sound stupid but I would like to ask.

Concerning this statement
`For older browsers (e.g. IE11), polyfills listed in the carbon-components-react/.storybook/polyfills.js file are required.`

I have not understood how I can include that in my project given that the components I am using are `carbon-components-react carbon-components carbon-icons`
