### ISSUE TITLE
console warning message when using ComboBox 

### ISSUE THREAD

**Issue by konghu** [carbon-design-system/carbon#2543]
We are seeing this error message when using ComboBox component
![001ab120-de91-11e8-83df-a19af63abfc5](https://user-images.githubusercontent.com/21697034/51944138-3da3ae00-23e9-11e9-9792-4ec0a1605669.png)

An example of our use:
```					
<ComboBox
						className="bx--select-input"
						autoFocus={autoFocus}
						placeholder={placeholder ? placeholder : ''}
						light
						onChange={this.handleChange}
						onBlur={this.handleBlur}
						items={this.visibleOptions || []}
						selectedItem={this.selectedOption || { label:'', value: '' }}
						{...attr}
					/>
```

**Comment by emyarod** [comment]
hey @konghu thanks for submitting this ticket! would you mind creating a reduced test case in [Code Sandbox](https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox)? it would help a lot with testing any potential fixes

**Comment by asudoh** [comment]
Seems to be same as: #3637
