### ISSUE TITLE
Exponential Number support in Number Input component

### ISSUE THREAD

**Issue by toroc** [carbon-design-system/carbon#2550]
### Summary

The NumberInput component supports entering exponential number like 2e2, but the step of up/down does not leave the number in exponential form.

The step of up and down should modify the exponent and the number should be left in exponential form.

### Justification

We need to switch to Carbon for our statistical analysis software and some of the statistical procedures we support require that users enter an exponential number to set certain criteria. 

### Desired UX and success metrics

User can modify exponent with up and down arrows on NumberInput component.

The most common values for users would be something like 1e-6, 1e-8, etc.

### Specific timeline issues / requests

We will need this for our release in April 2019.

### Available extra resources

What resources do you have to assist this effort?

**Comment by chrisconnors-ibm** [comment]
how will users edit the base of an exponential?
