### ISSUE TITLE
Tab label overflows when screen size is smaller

### ISSUE THREAD

**Issue by schhimw** [carbon-design-system/carbon#2551]
## Detailed description

> Describe in detail the issue you're having.

Tab label text overflows in smaller screen sizes.

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to see changed?

Tab label should show `...`  instead of entire string. 

> What browser are you working in?

Chrome
Firefox

> What version of the Carbon Design System are you using?

"carbon-components": "~9.8.4",
"carbon-components-react": "6.32.4",

- Screenshots or code

<img width="614" alt="screen shot 2018-12-19 at 9 40 37 am" src="https://user-images.githubusercontent.com/46010031/50253681-d9c8a700-039f-11e9-80c6-b07fb588513b.png">

**Comment by tw15egan** [comment]
This issue is fixed on latest

<img width="238" alt="Screen Shot 2020-06-12 at 11 10 48 AM" src="https://user-images.githubusercontent.com/11928039/84517521-49151380-ac84-11ea-8490-1972b58d67b2.png">
