### ISSUE TITLE
No "loading/saving" state in Modal

### ISSUE THREAD

**Issue by ethanwinters** [carbon-design-system/carbon#2555]
### Summary

In a modal when someone pushes save there is no pattern built into the Modal component to show a loading state (like the loading state in this PR https://github.com/IBM/carbon-components-react/pull/1012)

### Justification

We save many items from inside a modal, there is no nice way to provide feedback to a user that we are processing

### "Must have" functionality

1) Ability to let the modal know it should be in a "saving" state
2) Ability to pass (optional) text to accompany inline-loading
3) Ability to mark primary and secondary buttons as disabled while in "saving" state... or perhaps in a form invalid state (not primary issue, but seems reasonable)

### Available extra resources

We can dedicate resources to work on this issue with Carbon team approval

**Comment by brunoalano** [comment]
Any news?

**Comment by billdevmaster71** [comment]
Now I am having same problem.
I hope anybody to help me.

**Comment by emyarod** [comment]
does customizing the ComposedModal fit your use case here?
