### ISSUE TITLE
Virtualized list support in Carbon components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2556]
We've seen this request come up a couple of times so wanted to create an issue around it to help consolidate these requests. Most notably, it seems that we should provide examples around how to do proper list virtualization (or windowing) alongside some of our components. Most notably, how to use libraries like `react-virtualized` or `react-window` alongside:

- List Box components
- Data Tables

Might help to also tackle how to introduce asynchronous states to these components, or at least consider this while crafting guidance around this topic.

**Comment by damaon** [comment]
@joshblack I would like to refresh on this topic. 

I tried to connect `DataTable` with `react-virtualized` or `react-window` and there were some obstacles (don't remember already). I ended up implementing my own virtual table to make it work but it's not ideal yet. 

Is there already some recommended approach or should I dig into this topic a little more and share results?

**Comment by damaon** [comment]
FYI - did another attempt at composing it with these virtualisation libraries and didn't manage to do that, so improved my custom virtualisation lib.

**Comment by penx** [comment]
This would be great, perhaps it could be reopened?
