### ISSUE TITLE
`HeaderMenuItem` should use Link prop types for external link components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2558]
In other UI Shell components, we use the underlying `<Link>` component to abstract away `<a>` usage versus `<Link>` usage with libraries like React Router, Reach Router, and Gatsby. We should do the same with `HeaderMenuItem`.

Might help to also add a `HeaderNavigationLink` or just `HeaderLink` component to make it more intuitive to use this as a link in the navigation.

**Comment by dakahn** [comment]
Closing as resolved 🤠
