### ISSUE TITLE
Export stories as components

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#2570]
This issue is for tracking the effort of exporting Storybook story code as React components.

CC @jendowns 

### Summary/Justification

Some business units have created a design system based on Carbon. For such Carbon-based design systems, they have their own storybook but want to use some stories from Carbon.

### Detailed design and usage example

This effort introduces modules like:

```javascript
export default ({ ...props }) => (
  <div>
    <Button {...props} className="some-class">
      Button
    </Button>
    <Button {...props} href="#" className="some-class">
      Link
    </Button>
  </div>
);
```

Using that, Carbon-based design system can create a story like:

```javascript
import ButtonStory from '/path/to/button-story';

storiesOf('Buttons', module)
  .add(
    'Default',
    () => (<ButtonStory data-foo="Foo" />));
```

### Specific timeline issues / requests

N/A

**Comment by jendowns** [comment]
Could we keep this open please? Would love to be able to import stories into our addons library 🤩

**Comment by tay1orjones** [comment]
We'd also like to see this for use in our Watson IoT addons. 

Instances where we are simply wanting to render the story as-is, I have found that we can import the story from `node_modules` and then re-export it from a story file in our project. There's some oddities with story source rendering and prop tables, but gives us a starting point.

Something we'd like to do in our storybook is divide "stock" carbon components (re-exported components without modifications) from "extended/custom" components via the `hierarchySeparator`. This currently isn't possible as there isn't a way to modify the story name.

**Comment by jendowns** [comment]
Please keep this open 🙏

**Comment by tay1orjones** [comment]
Storybook's new [Component Story Format](https://medium.com/storybookjs/component-story-format-66f4c32366df) should provide a path to portable stories once v5.2 is stable.

**Comment by jendowns** [comment]
Please keep this open 🙏

**Comment by tw15egan** [comment]
Keeping an eye on https://github.com/storybookjs/storybook/releases for a stable `5.2` 👀

**Comment by tay1orjones** [comment]
[5.2](https://github.com/storybookjs/storybook/releases/tag/v5.2.0) is out! 🎉

**Comment by tay1orjones** [comment]
Please keep this open 🙏

Storybook was recently updated to 5.2 in #4192. Are there any required items beyond refactoring stories to CSF and exporting them?

**Comment by asudoh** [comment]
Weighing in; I've been under an impression that CSF is designed for static stories. Most of our stories OTOH are parameterized via knobs.

**Comment by tay1orjones** [comment]
Everything in the `storiesOf` API has a direct equivalent in CSF. It works with all the official addons, including knobs. [Example from the react storybook](https://storybookjs.now.sh/official-storybook/?path=/story/addons-knobs-withknobs--tweaks-static-values)

**Comment by tay1orjones** [comment]
I can help refactor some stories if there's an agreed upon direction. Storybook also has some codemods we could take advantage of to assist with the process.

**Comment by asudoh** [comment]
Hi 👋 thank you for your willingness for contribution! The biggest thing is making story exports don't run knob code, so those reused stories can run without knobs. While I still don't find any official direction from Storybook team on this front, [putting knob setup code in story parameters](https://github.com/carbon-design-system/carbon-custom-elements/blob/14a1d52/src/components/button/button-story.ts#L39-L49) and [evaluating such knobs in story parameters in a decorator](https://github.com/carbon-design-system/carbon-custom-elements/blob/14a1d52/.storybook/config.ts#L54-L67) would be one idea.

**Comment by joshblack** [comment]
Closed by https://github.com/carbon-design-system/carbon/pull/6663
