### ISSUE TITLE
MuliSelect with labeled selections

### ISSUE THREAD

**Issue by geforcelive** [carbon-design-system/carbon#2571]
### Summary

We need a replacement for well known select2 component. We are using it while filtering in terms of in-set clause. The proposition is to extend the MultiSelect component, so we could see the list of options that we currently choosed, not only its count.

### Justification

We started transision of UI to new look and feel using react and carbon components. In case of replacing filtering we have found that our one component have no equal replacemnt in react carbon components.

### Desired UX and success metrics
On the picture below one can see the desired behavior on the UI:
![image](https://user-images.githubusercontent.com/37561177/47794359-99926400-dd20-11e8-9caf-d056dbbea88c.png)

We would like to either choose by selecting a option or type a option to narrow down the list of results.

Each option should contain a pair of id and value. Under the hood we would like to pass the ids to the backend for further filtering.

### "Must have" functionality
Displaying currently choosed elements is a must have.

### Specific timeline issues / requests
It is on our near roadmap. We plan to deliver first increment this year.

### Available extra resources
We could organize some extra resources based on the cost of the enhancment.

**Comment by designertyler** [comment]
I'd suggest detaching the selected tag and dropdown areas rather than trying to build all that functionally in a small area. This would also give you the space you need to show tags with longer names and could be possible with the tag and multi select components today.

**Comment by geforcelive** [comment]
Any chance or plans to have such component in future carbon components?

**Comment by dakahn** [comment]
@carbon-design-system/design This has come up a few times recently in our internal slack and it seems like a few people are interested in contributing this to Carbon. Is this something we intend to work on and support?

**Comment by shixiedesign** [comment]
Let's discuss as a group next week @dakahn

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by jeanservaas** [comment]
not stale

**Comment by drewdistefano** [comment]
Can some progress be made on this? This would be very useful for the Product Discovery team.

**Comment by joshblack** [comment]
stop

**Comment by aagonzales** [comment]
@geforcelive @drewdistefano 
Sorry for the very delayed response. Carbon has reviewed your proposal and think that the [MultiSelect dropdown](http://react.carbondesignsystem.com/?path=/story/multiselect--default) is the correct component to use here and that the added functionality of raising the full tags to be in the field is not scalable (what would happen if the user select 20 items?). As Tyler suggested a more scalable solution would need to be designed that doesn't include the bounds of the field and perhaps served more as a filter control than a dropdown.

We will not be pursuing this design as it currently is spec-ed for a Carbon enhancement but if this is something you team feels it still needs you of course can build it on your own. Please feel free to submit alternate designs and we will re-open the issue.
