### ISSUE TITLE
ComboBox and DropdownV2 cut off by bx--modal-content

### ISSUE THREAD

**Issue by bjones526** [carbon-design-system/carbon#2573]
## Detailed description

When a ComboBox or DropdownV2 component is placed inside of a modal, the bx--modal-content container will clip any dropdown items that extend past its bottom edge when the elements are expanded. You can still scroll down to see them, but on the initial click to expand the element, some or all of the items will appear to be missing. (Tested on Chrome)

## Steps to reproduce the issue
1. Nest a Dropdown or ComboBox component inside of a Modal. Expand the nested component. Unless the expanded component happens to be shorter than the height of  `bx--modal-content`, some or all of its dropdown items will be clipped. See sample code here: https://codesandbox.io/s/2p2w3zpmyr

This dropdown has three elements, but unless you scroll down after opening it, only the first two are visible.

<img width="1133" alt="screen shot 2018-10-23 at 10 14 16 am" src="https://user-images.githubusercontent.com/8770483/47367062-ed5fd600-d6ac-11e8-8b74-102259c8a3b3.png">

This ComboBox also has three items. It appears empty because it is positioned as the very last element inside of bx--modal-content. The items are still there, but there's no visual indication that you need to scroll, and none of the items become visible after you click on the combo box. 

<img width="1137" alt="screen shot 2018-10-23 at 10 20 39 am" src="https://user-images.githubusercontent.com/8770483/47367308-7119c280-d6ad-11e8-9e19-f30994d1c986.png">

**Comment by bjones526** [comment]
@alisonjoseph Would it be possible to add another absolutely positioned div around `bx--list-box__menu`? A positioned wrapper should allow the div to break out of the flow within the modal content.

**Comment by dakahn** [comment]
Closing this one out as resolved. Let me know if that's not the case and I can reopen yall 🤠
