### ISSUE TITLE
[DatePicker]: Fully controlled Range DatePicker

### ISSUE THREAD

**Issue by gdelory** [carbon-design-system/carbon#2574]
## Detailed description

> Describe in detail the issue you're having.

When using a Ranged DatePicker as fully controller component (I need a Clear Filter button resetting all filters I have), settings the value only affects the first DatePickerInput, but not second. I've tried to set the value to null, [], and [new Date(2018, 4, 4), new Date(2018, 4, 10)]

> Is this issue related to a specific component?

DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the when setting the value to `null` or `[]`, for the field to be set as empty, instead the second field stays filled: With values `[]`
![image](https://user-images.githubusercontent.com/9974707/47254776-df207880-d466-11e8-8ac8-1622d099da7f.png)

In motion:

![controlleddatepicker](https://user-images.githubusercontent.com/9974707/47255073-5952fc00-d46b-11e8-913a-5ae81f838dc1.gif)

> What browser are you working in?
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

"carbon-components": "^9.9.0",
"carbon-components-react": "^6.39.1",
"carbon-icons": "^7.0.5",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

End of year release for an internal IBM product.

## Steps to reproduce the issue

1. Select two dates using the Range DatePicker
2. Click the Clear filters button.

Both DatePickerInput should be empty, instead only the first one is.

Using Sandbox I cannot really reproduce, it's not even managed at all and no input is reset.

> Please create a reduced test case in code sandbox

https://codesandbox.io/s/w0qyzkv4v8

## Additional information

* Screenshots or code
* Notes

I'm really not sure why the behavior is different in the sandbox, I'm using the same versions and the same browser.

For people in the same boat as me, work-around for the time being using ugly javascript hack:
`document.querySelectorAll('.bx--date-picker__input').forEach(e => e.value = '')`
in the clear filter method

**Comment by matias-quezada** [comment]
Cosed without any comment?
