### ISSUE TITLE
Add support to scroll content of DataTable with fixed table header

### ISSUE THREAD

**Issue by qi-min** [carbon-design-system/carbon#2577]
### Summary

DataTable does not support scroll with fixed header, so user can not see the header information after scroll. Is it possible to support this feature, scroll content only with header fixed

development.

### Justification

Provide the business reasons for this request.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by which we can measure success/failure for the user.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not guaranteed. The earlier you make a request in advance of a desired delivery date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by aledavila** [comment]
@IBM/carbon-designers Tagging the designers to see what is their take on this.

**Comment by asudoh** [comment]
Let's close for the sake of #1587.
