### ISSUE TITLE
Request for overflow menu with hint popup with icon tooltip

### ISSUE THREAD

**Issue by tymekg** [carbon-design-system/carbon#2578]
## Detailed description

On the other issue (#1440) I was told:

> Wrt overflow menu, I don't see <TooltipIcon> would support overflow menu put in there. If you have particular use case that led you do that, please file another issue. Thanks!

so here we go, this is my use case:

I have a kind of toolbar above a table with two icons for most common actions and a dropdown menu for the other of actions. See a sample screenshot below, in screenshots section.

I want to be able to hint users about purpose of each icon using tooltips (e.g. with text "search data", "maximize view" and "other options"). According to http://www.carbondesignsystem.com/components/tooltip/code#interactive-tooltip the best type of tooltip for this purpose should be Tooltip Icon.

> Is this issue related to a specific component?

`TooltipIcon` & `OverflowMenu`
> What did you expect to happen? What happened instead? What would you like to see changed?

I expect to be able to create a toolbar with clickable icons in and a dropdown for the less commonly used actions - all with tooltips and consistent look and feel.
> What browser are you working in?

Firefox Quantum 60.2.2esr on Windows
> What version of the Carbon Design System are you using?

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/16018298/46999699-b6c31200-d126-11e8-95c2-27b90d9cf2d1.png)

**Comment by shixiedesign** [comment]
Icon button (with tooltip on hover) is merged! So this issue should be resolved. Feel free to re-open if I've missed anything.
