### ISSUE TITLE
MultiSelect-Dropdown: number of selected checkbox needs to reset from change in other component

### ISSUE THREAD

**Issue by Yashwanth8** [carbon-design-system/carbon#2582]
## Detailed description

> Suppose In Multi-Select dropdown with checkbox, I have selected 2 items. 
<img width="352" alt="bug-1" src="https://user-images.githubusercontent.com/44077205/46844136-c5ff3400-cda3-11e8-9a99-b59448276674.png">

And now I want to reset the status flag of 2 selected items on change in the location component like below(This is the end goal):
<img width="360" alt="bug-03" src="https://user-images.githubusercontent.com/44077205/46844185-ed560100-cda3-11e8-8c20-951ecb65e991.png">

But right now, I'm getting like this (Currently this is happening):
<img width="351" alt="bug-2" src="https://user-images.githubusercontent.com/44077205/46844317-82f19080-cda4-11e8-86cc-35883a2ffc14.png">

> This issue is related to Multi-select Component.

> What did you expect to happen?
<img width="360" alt="bug-03" src="https://user-images.githubusercontent.com/44077205/46844185-ed560100-cda3-11e8-8c20-951ecb65e991.png">
> What happened instead?
<img width="351" alt="bug-2" src="https://user-images.githubusercontent.com/44077205/46844317-82f19080-cda4-11e8-86cc-35883a2ffc14.png">
> What would you like to see changed?
I believe there should be some props/flag that I can send to multi-select component, based on that component can decide reset or not.
Right now I think, on the selection of checkbox, we are pushing the selected object to selectedItems array. I have tried to reset this property on the change of location component, but there is no luck. 

> What version of the Carbon Design System are you using?
`"carbon-components-react": "^5.19.1"`

**Comment by helenhayley** [comment]
> 
> 
> I already upvoted this, but meanwhile if that an help others, the only ugly way I found to rest the MultiSelect is to programmaticly click the reset button:
> `document.querySelectorAll('.bx--multi-select .bx--list-box__selection--multi').forEach(e => e.click())`
> add a first class properly to your component to make sure you just reset the one you want to.

Hi gdelory, 
I'm having the same issue and TypeScript is giving the error "property 'click' does not exist on type 'element'". How did you get around this?
