### ISSUE TITLE
Feature Request: A dashboard component

### ISSUE THREAD

**Issue by guoweihua** [carbon-design-system/carbon#2584]
Lots of applications need a dashboard as a container for multiple widgets. There are some open source implementation for react, like: dazzle, etc. IBM IoT Maximo group developed a UI library called lightning, which has a dashboard container. But that library does not support react.

**Comment by dakahn** [comment]
I'm going to close this out @guoweihua since we've got the wrong template going here. Feel free to re-open as as feature request though 👍
