### ISSUE TITLE
Feature request: Add national islamic calendar support for flatpickr

### ISSUE THREAD

**Issue by wajnberg** [carbon-design-system/carbon#2585]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
Support for Hijri calendar as supported in other date picker such as Dojo:
https://dojotoolkit.org/reference-guide/1.10/dojox/date/islamic.html

### Justification

We need Hijri calendar in the Watson Assistant product

### "Must have" functionality

Yes
### Available extra resources

What resources do you have to assist this effort?

I already added the support for Hijri calendar in my repo: https://github.com/wajnberg/national-flatpickr

@tonydiaz FYI

**Comment by dakahn** [comment]
We're dependent on Flatpickr for this kind of feature -- we can track the progress on developing this plugin over there. 👍
