### ISSUE TITLE
Create Platform Navigation Menu component

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2588]
This issue is for implementing the navigation menu component found in:

![image](https://user-images.githubusercontent.com/3901764/46694362-2f2f4d80-cbd2-11e8-98ee-882c7ae30e57.png)

Latest sketch file: https://ibm.box.com/s/4e4zrz6mlo0jpr8lw4vimwlxn4vc59cy

**Comment by dakahn** [comment]
I think we're tracking this work in #2401 👍🏽

**Comment by chrisconnors-ibm** [comment]
specifically here: https://github.com/carbon-design-system/carbon/issues/2335
