### ISSUE TITLE
Support for click one row for selection in DataTable

### ISSUE THREAD

**Issue by hongcbjch** [carbon-design-system/carbon#2591]
DataTable already supports selection with check box ahead of the rows, 
![image](https://user-images.githubusercontent.com/42921827/46610414-48d28580-cb3d-11e8-84fb-18368d9b840e.png)

but there is a requirement from our team, we don't want the check box, but want to click one row for selection. I would like to know if DataTable supports such case? if not, do you have plan to add it? Thanks!
![image](https://user-images.githubusercontent.com/42921827/46610492-78818d80-cb3d-11e8-9b6e-4937e3998fe0.png)

**Comment by jeanservaas** [comment]
@hongcbjch we have no plans to add this functionality, I don't see it represented as a variation in the new design language master component file either. Feel free to add this functionality and contribute.

The Open Source model we're operating under assumes teams out in the world who need specific deviations from existing components design, develop, and submit them back for consideration to include in our master branch. It's the only way we can scale our system to accommodate the breadth of needs in our organization. so if there are immediate needs by external teams, they are encouraged to create issues, design and build what they need, and submit them back to us in a pull request. 

Also, like @designertyler mentioned... I worry about the usability implications without the checkbox.
