### ISSUE TITLE
All SVG tags are focusable in IE11 (Icon component)

### ISSUE THREAD

**Issue by JohnWColby** [carbon-design-system/carbon#2592]
## Detailed description

> Describe in detail the issue you're having.

IE11 does not handle SVG's properly and allows all of them to be focusable. In most cases, SVG's should not be focusable (either because they are not interactive or the button around them should be the part gaining focus).

> Is this issue related to a specific component?

Yes, the Icon component, which is used to display SVG's

> What would you like to see changed?

If I'm not mistaken, this should be fixable by adding a `focusable="false"` attribute to the `svg` tag here: https://github.com/IBM/carbon-components-react/blob/master/src/components/Icon/Icon.js#L135

(Based on this SO article: https://stackoverflow.com/questions/29393144/how-to-prevent-svg-elements-from-gaining-focus-with-tabs-in-ie11)

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

6.32.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Compare & Comply Tooling UI

**Comment by joshblack** [comment]
@dakahn I believe this should be addressed in our latest icon components with `focusable="false"`. Let me know if this isn't the case!
