### ISSUE TITLE
ExpandableTile tileMaxHeight property is overwritten.

### ISSUE THREAD

**Issue by lekterable** [carbon-design-system/carbon#2594]
## Detailed description

> Describe in detail the issue you're having.

`tileMaxHeigh` property that is passed to ExpandableTile components gets overwritten by other values after clicking on the Tile.

> Is this issue related to a specific component?

ExpandableTile

> What did you expect to happen? What happened instead? What would you like to see changed?

I'm not entirely sure as the purpose of tileMaxHeight prop is not very clear but I would expect somewhat respecting this passed height by either TileAboveTheFoldContent or TileBelowTheFoldContent or both.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

6.33.4

## Steps to reproduce the issue

1. Use official storybook
2. Go to the Tile/Expendable
3. Change the tileMaxHeight knob
4. After clicking on the tile twice maxHeight gets reset.

> Please create a reduced test case in code sandbox

https://codesandbox.io/s/n7891xom4 < = What's interesting here is that I was not able to reproduce It anywhere else than storybook, using codesandbox tileMaxHeight property has no effect on the component at all (which is also not that good).

## Additional information

I would love to make a PR for this as a Tile component seems very useful but I need more clarification of what is the exact purpose of the tileMaxHeight prop.

**Comment by asudoh** [comment]
@lekterable My apologies again for being late on this - As far as I see the original code (which didn't have prop -> state sync feature), the `tileMaxHeight` property seems to have been merely for setting tile height before being mounted. As it's what you may be looking for, we can change it for allowing full programmatic control of tile height. An idea I can rattle off is detecting if there is a programmatic control of `tileMaxHeight` and cancel the DOM geometry calculation logic if so. What do you think? Thanks!
