### ISSUE TITLE
Revert DropdownV2 requirements, support both signatures for Dropdowns

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2597]
Related to #1228, we want to revert the requirements of DropdownV2 from requiring a data structure of items to render and bring back the ability to render DropdownItem's inside of DropdownV2.

**Comment by joshblack** [comment]
@justinpurcell1 sounds good! `itemToElement` seems like a great strategy for now, especially with your PR 😄

**Comment by ZacharyStair** [comment]
its available in version 6.59.0 https://github.com/IBM/carbon-components-react/pull/1608#issuecomment-445427436, there was a slight hiccup with the delivery
