### ISSUE TITLE
MultiSelect performance with large lists

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#2598]
The `MultiSelect` component doesn't handle large lists well. The performance degrades to the point where it's unusable.

Rendering the same list with `ComboBox` doesn't affect the performance as much.

Maybe we can have built-in "[windowing](https://reactjs.org/docs/optimizing-performance.html#virtualize-long-lists)" using [react-window](https://github.com/bvaughn/react-window) for example?

## Detailed description

> Is this issue related to a specific component?

`MultiSelect` & `MultiSelect.Filterable`

> What browser are you working in?

`Chrome` latest

> What version of the Carbon Design System are you using?

```
"carbon-components": "9.18.0", 
"carbon-components-react": "6.32.4",
"carbon-icons": "7.0.7",
```

## Steps to reproduce the issue

https://codesandbox.io/s/xrjy36l1pz

## Additional information

You can also activate the `FPS Meter` where you can see the frame rates drop significantly once the dropdown is clicked or use the `Performance Monitor` to see the `CPU Usage`. On my computer, once I click on the dropdown, the usage jumps to 100%.

**Comment by vpicone** [comment]
Another minimal replication of this issue using static data: https://codesandbox.io/s/frosty-shape-gzdku

A cloud team reached out with 4000 items in their list. At that amount, the component becomes unusable. The UX is improved by using `Multiselect.Filterable` (which is a wild and hard to find API) but the performance issues are still very real.

**Comment by tvelingkar** [comment]
@laurenmrice any updates on this issue? This issue is affecting our application.

**Comment by laurenmrice** [comment]
Adding this slack convo in here for visibility on this topic:
<img width="1097" alt="Screen Shot 2020-04-15 at 10 27 02 AM" src="https://user-images.githubusercontent.com/43969356/79355710-a6e6e280-7f03-11ea-8ece-804c006590de.png">

**Comment by Yohanna** [comment]
Are there any updates on this issue? 

Note: I've just updated the CodeSandbox to the latest Carbon versions.

**Comment by ganisback** [comment]
I am also facing this issue

**Comment by dezkareid** [comment]
The problem with this kind of issue is take a lot of time to render a lot of items.

Maybe adding react-virtual to component this can be solved but I don't know how can impact the multiselect implementation or a better approach is create a new component to handle heavy data
