### ISSUE TITLE
Radio Button - shape bug

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#260]
The circles for radio buttons are an oval shape. Noticed it several times today. The dot in the middle is also off center due to the "new" shape. 
<img width="435" alt="screen shot 2017-08-07 at 10 04 58 pm" src="https://user-images.githubusercontent.com/29312997/29054666-18e40892-7bbd-11e7-9cad-6b848bbf483a.png">

**Comment by hellobrian** [comment]
Can you confirm that your browser is zoomed at 100% - radio button shapes can look weird when set at other sizes

**Comment by hellobrian** [comment]
Welp, it might still be worth it to try and refactor this so that it works when zoomed in or not. I could try using SVG instead of `<span>` elements for the radio button shapes.

**Comment by theoshu** [comment]
This also happens with checkboxes when the text wraps.
![carbondesignsystemcheckboxwrap](https://user-images.githubusercontent.com/4643524/29343713-901c99d8-81f8-11e7-83b7-2c9607508d0d.png)
