### ISSUE TITLE
Unexpected behavior in keyboard navigation in DropdownV2

### ISSUE THREAD

**Issue by JohnWColby** [carbon-design-system/carbon#2600]
## Detailed description

> Describe in detail the issue you're having.

When using keyboard navigation, the DropdownV2 component gets focus twice. It also does not open the menu on an enter press.

> Is this issue related to a specific component?

Yes, DropdownV2.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

6.28.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Compare & Comply Tooling UI, no extremely pressing deadline

## Steps to reproduce the issue
1. Navigate to the DropdownV2 > default Storybook story. (http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Dropdown%20type%20%28type%29=default&knob-Label%20%28label%29=Label&selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
2. Press "tab" key. Note that element `div.bx--dropdown.bx--list-box` receives focus. Note that pressing enter or using the arrow keys seem to do nothing. (Not expected, pressing enter or the down key should open the menu.)
3. Press "tab" key again. Note that element `div.bx--list-box__field` receives focus. (Not expected, as this essentially focuses on the same button.) Note that pressing enter seems to do nothing. (Not expected, pressing enter should open the menu.) Note that pressing the down key _does_ open the menu, and that further navigation from this point is straightforward / intuitive. (This is as expected.)

**Comment by dakahn** [comment]
Just chiming in here. Doing an AVT2 test and dropdown v10 _does not open_ on enter in the latest Firefox on Windows :hurtrealbad: 

I'll escalate the severity and priority 👍

**Comment by joshblack** [comment]
@dakahn I believe this should be resolved now with @aledavila latest fix! Or, at the very least, things like enter and double VO focus seem to be resolved.
