### ISSUE TITLE
Performance Issues for DataTable

### ISSUE THREAD

**Issue by yhjyang1** [carbon-design-system/carbon#2601]
## Title line template: [Title]: Brief description
If there are too many rows rendered in `DataTable`, displaying that many rows is causing the browser's rendering engine to slow down, so is there a way to improve the performance of `DataTable` when rendering large data?
-->

## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue?
`Feature request`

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected:
Displaying a certain amount of data at a time，and updating the displaying data when the vertical scroll bar is scrolling.

> What browser are you working in?

> What version of the Carbon Design System are you using?
`6.28.2`
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by yhjyang1** [comment]
Thanks @NateMoeller :)

**Comment by robertmylne** [comment]
If the pagination drop down it turned off this improves the performance. As that is what was lagging for me, rendering a drop down of 10,000 items.
