### ISSUE TITLE
Add left/right direction to tooltipIcon

### ISSUE THREAD

**Issue by filipmadej** [carbon-design-system/carbon#2604]
### Summary

I would like to have an option left/right added for TooltipIcon

### Justification

I have a problem with TooltipIcon as it’s getting cut by the window. I could solve it by moving tooltip to the left but supported direction are only top and bottom. Regular tooltips support left/right.

![screen shot 2018-09-10 at 16 33 37](https://user-images.githubusercontent.com/19649061/45433235-00de5100-b6ac-11e8-8b6a-77799d156d0c.png)

**Comment by filipmadejIBM** [comment]
@asudoh You've provided solution for definitiontooltip, not TooltipIcon
