### ISSUE TITLE
[IE11] DataTable expansion rows have minor CSS issue

### ISSUE THREAD

**Issue by dawang021** [carbon-design-system/carbon#2608]
## Detailed description

> Describe in detail the issue you're having.

DataTable expansion rows have minor CSS issue .

http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&selectedKind=DataTable&selectedStory=with%20expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

![datatable-expansion-rows](https://user-images.githubusercontent.com/42695523/44977463-b289cd80-af9a-11e8-9e72-15e032b0bc6c.PNG)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?
```
    "carbon-components": "^9.5.0",
    "carbon-components-react": "6.21.4",
```
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**Comment by dawang021** [comment]
@joshblack Sorry, this is also an IE11 issue.

Reproducing steps:
1. Use IE11 browser open [Carbon storybook DataTable](http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&selectedKind=DataTable&selectedStory=with%20expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel);
2. Expand whatever row;
3. You'll see the left border not reaching the row bottom.

**Comment by tw15egan** [comment]
Tested on IE11, does not seem to be an issue anymore

**Comment by tw15egan** [comment]
Tested on IE11, does not seem to be an issue anymore
