### ISSUE TITLE
[RFC] Form Components Refactor

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2609]
Hi all! 👋 Wanted to take a stab at suggesting some Form-related improvements we could make for Carbon X. These don't represent anything that we'd need to commit to, just are suggestions for where we could take some of these components in the future. Curious what you all thing 😄 

For Forms, I figured we could focus initially on some of the wrappers around some of the more primitive input types. These could include text inputs, Checkbox & Radio, Textarea, etc. The way we could improve some of these is by introducing the following types on top of these inputs:

- Inline input component (`InlineCheckbox`)
  - These would be wrappers around the input itself, and for associating a label to it. They would not be wrapped in a form item, and would be ideal for incorporating an input inside of another component. For example, checkboxes for selection in a DataTable
  - These components would support forwarding refs to the underlying `<input>`
- Input component (`Checkbox`)
  - Similar to what we have now, but would be a stateless variant that would be wrapped in a form item. Would forward refs to underlying `<input>` node
  - Also should support the render logic for displaying validation state, but not handling the validations themselves
- Controlled input component (`ControlledCheckbox`)
  - Would control the underlying stateless inputs and provide an `onChange` hook for folks to register. Also could provide a `validate` method, as well, to help folks hook in and show validation status

Looking forward, consumers would use these alongside our existing `Form` or `FormGroup` components. We could also, down the line, provide aliases for popular form libraries if we wanted to help out more with this use-case.

Anyways, that's it! Curious to hear what everyone thinks 😄

**Comment by joshblack** [comment]
@asudoh for the bullets you mentioned:

- Inline components allow us to share the same base input code with both the normal field component (e.g. `Checkbox`) and that component defined in other places, like selection in Data Table. The summary is that Inline is an input element that is not expected to be in a form, whereas the plain variant (like `Checkbox`) would be expected to be found in a form
- Controlled components make it easier to apply the right styles by allowing consumers to pass in custom logic for validation, if needed, or just makes it easier to use the component since they'd only need to pass in an `onChange` to get the value of the input instead of having to write their own logic for this. If they need the custom logic, then they can drop down to either variant that isn't controlled

**Comment by joshblack** [comment]
Controlled components would just be (at a very high-level):

```js
import PropTypes from 'prop-types';
import React from 'react';
import Checkbox from '../Checkbox';

export default class ControlledCheckbox extends React.Component {
  static propTypes = {
    onChange: PropTypes.func.isRequired,
  }

  constructor(props) {
    super(props);
    this.state = {
      checked: props.initialValue || false,
    };
  }
  
  handleOnChange = () => {
    this.setState(state => ({ checked: !state.checked }), () => {
      this.props.onChange({ value: this.state.checked });
    });
  }

  render() {
    // Will also need to pass in other input props like disabled, aria-label, etc.
    const { checked } = this.state;
    return <Checkbox checked={checked} onChange={this.handleOnChange} />;
  }
}
```

Could also add support for custom `validate` hooks that would allow folks to verify the input and have the component control whether the invalid state is shown. The signature for `validate` could look like:

```js
// Supports the name of the input and it's current value to validate
// Function can return a promise or return synchronously, they can throw an error that
// would contain the value they'd want displayed in the error message
type Validate = (name, value) => Promise<void> | void
```

**Comment by asudoh** [comment]
Thanks @joshblack for clarifying. The inline version makes sense, as long as it's implemented in an as simple manner as `<Checkbox>`/`<InlineCheckbox>` we have today.

For the controlled one - Controlled components tend to involve many application-specific logic in play, and those in Carbon has caused issues, like ones against missing prop -> state sync, request for better control over inner-components, request for additional event handlers, and so on.

From that reason, Carbon has let controlled versions implemented in user-land for form elements. I'd suggest we keep that approach. If we really want to implement the controlled versions we need to be very careful defining the API.
