### ISSUE TITLE
DataTable should not show BatchActions after batch action

### ISSUE THREAD

**Issue by lukawendy** [carbon-design-system/carbon#2621]
## Detailed description
I met a problem that if I have a batch action to delete rows, after I deleted the rows, the batch action bar still show up and says `0 item selected`, that is weird.

```
  getBatchActionProps = (props = {}) => {
    const { shouldShowBatchActions } = this.state;
    const totalSelected = this.getSelectedRows().length;
    return {
      ...props,
      shouldShowBatchActions,
      totalSelected,
      onCancel: this.handleOnCancel,
    };
  };
```
I think the `shouldShowBatchActions` should change according to `totalSelected`. If there is 0 item selected, we don't show batch action bar.

What's more, if we are not deleting, after we do a batch action like download or something, should we clear the select status for the rows and not show batch action bar?

**Comment by iff133** [comment]
I am facing the same issue, has this been addressed? Or if not can someone share how they have closed the batch action bar after an action.

Thank you
