### ISSUE TITLE
Combined Date/Time Selector

### ISSUE THREAD

**Issue by Kyle-Cooley** [carbon-design-system/carbon#2622]
## Detailed description

> Describe in detail the issue you're having.

For the project I am working on, we need a combined dropdown selector for date and time. As far as I can tell, this does not appear to exist in carbon. This seems like something that could be useful for multiple projects. Just wondering if there was an interest in adding/amending a component for this use case.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

APM

## Additional information

The DatePicker component could enable this, since flatpickr has properties for this. They just need to be exposed to the users of carbon. There are a couple of css issues that would need resolved, but it is an option. I'm just not sure whether or not it would fit with the carbon design.

![image](https://imgur.com/HEByquy.png)

**Comment by imp-dance** [comment]
Bumping to show interest. I'm also in need for this for a project. Could be especially helpful for circumstances involving date-ranges, since currently it's really difficult to get a good looking layout to work this way without separating the time-fields and date-fields entirely.
