### ISSUE TITLE
MultiSelect - clear selected items from button outside of component

### ISSUE THREAD

**Issue by okstaticzero** [carbon-design-system/carbon#2623]
## Detailed description
Is there a way to clear selected items from an action outside of the component?

> Describe in detail the issue you're having.

Use case is this: I have multiple MultiSelect components on the screen and I have one button that when clicked, clears all selected items in the MultiSelect components so none are selected. It this possible? Or could some kind of prop be added like: clearAllSelectedItems ?

> Is this a feature request (new component, new icon), a bug, or a general issue?

Generel question

> Is this issue related to a specific component?

MultiSelect

**Comment by nithinbabusage** [comment]
Hi All,
@cal-smith @carbon-bot @joshblack @slaytanic 
Is there an option to add button Icon inside the Error message of the Multiselect carbon component means after the Medium-warning 
Message below the Message add the Refresh or Home icon for example is there a way in the carbon component not much example found in the google
