### ISSUE TITLE
Although sort order is none on DataTable, arrow shows until clicking other area.

### ISSUE THREAD

**Issue by blbird** [carbon-design-system/carbon#2624]
## Detailed description
> Describe in detail the issue you're having.

Current DataTable show the arrow until clicking other area although there is no sorting. In this case, user could think that the sorting does not work. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

I think it is a bug.

> Is this issue related to a specific component?

DataTable

> What did you expect to happen? What happened instead? What would you like to see changed?

Arrow icon should disappear when rows are not sorted.

## Steps to reproduce the issue
1. Go to story book page  for DataTable : https://pages.github.ibm.com/cloud-integration-design/ap-carbon-theme/?selectedKind=DataTable&selectedStory=with%20sorting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

2. Click the name on header three times. 

3. You can see the arrow icon like below image although rows are not sorted.
![image](https://user-images.githubusercontent.com/6425614/43119555-d037c800-8f51-11e8-83d4-5987c0ee9f42.png)

**Comment by aagonzales** [comment]
Hmm I'm not sure what's happening there. It should just sort up or down on click. I'm not sure what that third click is doing.

**Comment by lovemecomputer** [comment]
@joshblack yeah that would be best for keyboard accessibility! i find the current implementation to be confusing though. aside from a more refined design update, we could do a small fix by doing something along the lines of setting the SVG fill to transparent, so that the focus border would still appear but the icon wouldn't be confusing?
