### ISSUE TITLE
DataTable TableRow onClick passed in through getRowProps does not trigger

### ISSUE THREAD

**Issue by iamgollum** [carbon-design-system/carbon#2627]
Using the recommended `getRowProps` does not allow for `onClick` behavior to function.
```  
<TableRow
                   key={row.id}
                    {...getRowProps({
                      row,
                      onClick: () => this.props.handleOnRowClick(row.id)
                    })}
                  >
```
The current solution is to apply a `onClick` event handler directly on the TableRow component.

**Comment by joshblack** [comment]
This _should_ be addressed over by: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/DataTable.js#L272 so am going to close this out for now. Let us know if this is not the case and I'll be happy to re-open!
