### ISSUE TITLE
DatePicker - Date seems to update to a value not selected at times 

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon#2632]
## Detailed description

> Describe in detail the issue you're having.

When selecting various start and end dates on the DatePicker at some point it will update the end date value when you are only updating the start date

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

DatePicker and DatePickerInput

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the end date would stay the same and only the start date would be changed. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v5.50.0 but I reproduced this on Codesandbox using v 6.5.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Assistant

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/moz711vo09)

1. Begin with the start date as 6/18/2018 and end date to 6/20/2018
2. Select the end date date 06/17/2018
3. Select the end date to 06/20/2018
4. Notice the start date updates to 6/18/2018 and end date get updated to 6/20/2018 when only the end date should have been updated

![carbondatepicker](https://user-images.githubusercontent.com/7145340/41694701-904cc8cc-74d9-11e8-9e92-0c552d5a16f0.gif)

Another way:
1. Begin with the start date as 6/18/2018 and end date to 6/20/2018
2. Select the end date date 06/11/2018
3. Select the end date to 06/19/2018
4. Notice the start date updates to 6/18/2018 and end date get updated to 6/19/2018 when only the end date should have been updated.

![carbondatepicker1](https://user-images.githubusercontent.com/7145340/41694801-15690066-74da-11e8-9c6a-70d41d347cdf.gif)

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Just stumbled at this as I looked at other date picker issues. This is the same behavior as what is seen at https://flatpickr.js.org/plugins/. Basically, here's what happens:

* If user selects a date that is smaller than the starting date, the former starting date turns to the new end date and the one user selects becomes the new starting date (The one seen in step 2. in the issue description)
* If user selects a date that is bigger than the end date, the former end date turns to the new starting date and the one user selects becomes the new end date (The one seen in step 3./4. in the issue description)

The above behavior happens regardless of which `<input>` the date picker dropdown is launched from. Given those, closing as working as designed, but may worth discussing the desired UX, probably at https://github.com/flatpickr/flatpickr/issues.
