### ISSUE TITLE
feat:(Pagination): Stand alone Small pagination

### ISSUE THREAD

**Issue by okstaticzero** [carbon-design-system/carbon#2634]
The design files show a secondary pagination example (shown below). Any plans to add this?
![comp](https://user-images.githubusercontent.com/209432/41430017-120526c4-6fcc-11e8-9a2e-4731f18584f0.png)

**Comment by asudoh** [comment]
Let's enqueue this for feature enhancement bucket.

**Comment by aagonzales** [comment]
I think some has previous worked on this pagination pattern. I reviewed the code for him but I'm having trouble tracking down the issue. It was a contribution outside of our team.

**Comment by aagonzales** [comment]
For the record the image shown in the first comment is NOT the approved v10 styling. The styling is correct in the https://github.com/carbon-design-system/carbon/pull/1812 issue.

**Comment by shixiedesign** [comment]
To do
- ~Update style to v10~ (coded version has v10 style see PR https://github.com/carbon-design-system/carbon/pull/1812) - AG
- [ ] Need react version
- [x] Documentation update on website https://github.com/carbon-design-system/carbon-website/issues/275

**Comment by aagonzales** [comment]
Vanilla versions has been added to the [website](https://github.com/carbon-design-system/carbon-website/issues/275). The outstanding task here is to make the react version.

**Comment by emyarod** [comment]
is this component meant to be a 1:1 drop-in replacement for the regular pagination component? if so, I would need some additional clarification for certain scenarios like when the total number of items is unknown for example

**Comment by aagonzales** [comment]
@emyarod No, it's a new variation. It's essentially a non-table pagination version. Something you'd see at the bottom of a search results page for example. 

Like at the bottom of a google search page:
![image](https://user-images.githubusercontent.com/11670886/65985080-bc545d80-e446-11e9-9d2e-838cd967a805.png)



Can you show me an example of pagination with the total number of items is unknown?(ie what's the industry standard for handling this?) Is this something we address with our current data table version of pagination?

**Comment by aagonzales** [comment]
For google it looks like it just keeps counting pages and wouldn't present the ellipse feature. The only controls the user would have are the set of 10 number in the range and a backward/forward function. 

![image](https://user-images.githubusercontent.com/11670886/65984809-30423600-e446-11e9-8b7a-accb0abf4d86.png)

So ours would looks like:
![image](https://user-images.githubusercontent.com/11670886/65985158-ddb54980-e446-11e9-805f-af38725ea7e5.png)

**Comment by emyarod** [comment]
@aagonzales it looks like we currently have a prop called `pagesUnknown` (introduced in https://github.com/carbon-design-system/carbon/commit/c2de95aac2888b17084d7c51042d2c6865eec318), you can see it in action in the [story](http://react.carbondesignsystem.com/?path=/story/pagination--pagination) after selecting the knob for it. I'm assuming we will carry that feature over to this variation and we would just remove the ellipses selection menu in this case as you mentioned

**Comment by emyarod** [comment]
I have a few more questions for clarification

have we created a spec for this pagination variation including disabled/hover/focus styles, theme variants etc? some of these details aren't currently shown in the live component example but I'll need to add them

is there a default/minimum/maximum number of pages we want to show in the component (in the cases with and without `<select>` menu overflow too)?

and based on the mockups in the first post in this issue, will we always show the first and last page numbers?

**Comment by aagonzales** [comment]
@emyarod as per this comment https://github.com/carbon-design-system/carbon/issues/2634#issuecomment-505590559 the image in the first comment is not the final design. The code was contributed to us and we made a lot of decisions on the fly in the PR. https://github.com/carbon-design-system/carbon/pull/1812

All the state you mention are already part of the vanilla component [here](https://the-carbon-components.netlify.com/?nav=pagination-nav), they are also available in the design kit under "pagination/standalone". 

Enabled & selected
![image](https://user-images.githubusercontent.com/11670886/66070264-9eeec480-e516-11e9-87b0-c1ce6a086c7c.png)

Hover:
![image](https://user-images.githubusercontent.com/11670886/66070300-aada8680-e516-11e9-8079-4166cfeeb738.png)

Focus: 
![image](https://user-images.githubusercontent.com/11670886/66070332-b928a280-e516-11e9-84fc-1f2179d175a1.png)

Overflow:
![image](https://user-images.githubusercontent.com/11670886/66070359-c5acfb00-e516-11e9-8091-276f415d4738.png)
![image](https://user-images.githubusercontent.com/11670886/66070382-cfcef980-e516-11e9-929f-d83dc5aa6a8b.png)

Disabled:
![image](https://user-images.githubusercontent.com/11670886/66070608-410eac80-e517-11e9-83d0-f8703bb8b517.png)

From the sandbox here, it looks like the themes are already rendering properly with the correct tokens: https://the-carbon-components.netlify.com/?nav=pagination-nav

**Comment by aagonzales** [comment]
Min number of pages: 2
Max number of pages before overflow: 10

**Comment by emyarod** [comment]
@aagonzales cool, I was already referring to the resources that you linked. WRT disabled state, I meant a scenario when the entire component is disabled (including the caret buttons and current page indicator) instead of a couple of individual pages like in the image

**Comment by aagonzales** [comment]
![image](https://user-images.githubusercontent.com/11670886/66074967-1aa13f00-e520-11e9-845a-b06e446bff12.png)
For disabled all numbers and the arrows should use the color token `$disabled-02`

**Comment by lukefirth** [comment]
Adding a 2¢ to this from some exploration on my team where we're using this as part of a larger 'tile catalog' type component. 

I wanted to keep the simplicity of the interactions googles search used for paging back and forth, but I didn't want to lose the versatility of the overflow, even while deep in the pages. In the end I landed here:

![image](https://user-images.githubusercontent.com/30671949/76361939-0bec5e80-62ee-11ea-84c1-65a1095fe9c6.png)

Note: The overflows would simply let you jump directly to the given page, which would make the pagination assume the appropriate step.

**Comment by laurenmrice** [comment]
closing as this was merged into react with this pr: https://github.com/carbon-design-system/carbon/pull/6199
