### ISSUE TITLE
Pagination native support in the DataTable 

### ISSUE THREAD

**Issue by gaurav-ketkar** [carbon-design-system/carbon#2639]
## Pagination native support in the DataTable
Pagination is one of the most important aspects of having a data table where there are 100s of rows to be shown. Bringing pagination into the Data Table will make using DataTable + Pagination much easier. 

## Detailed description

A quick search in the #carbon-react Slack channel yields Pagination + Data Table as a relatively popular request. Creating this issue so the team can prioritize this when they get the chance.
 
> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request.

> Is this issue related to a specific component?

DataTable and Pagination components.

> What did you expect to happen? What happened instead? What would you like to see changed?

Pagination should be a part of DataTable (just like search is)

> What version of the Carbon Design System are you using?

5.49.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

The Unified Support micro-service. We are currently using the table and pagination components but they are talking with each other in a roundabout way.

**Comment by DivergentEuropeans** [comment]
Please re-open this, having a working example would be greatly appreciated seeing as you guys actually developed this feature to work with the DataTable apparently?

**Comment by GreenRobot777** [comment]
Any solutions?

**Comment by emyarod** [comment]
you can implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc. rather than using the built in state manager in `DataTable`, if that makes sense
