### ISSUE TITLE
[New Component]: Tag List

### ISSUE THREAD

**Issue by bellsworth13** [carbon-design-system/carbon#2640]
## Detailed description

We want to create a component which will manage a list of tags. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a feature request for a new component. 
- It should have the following properties: 
- [ ] items (tags)
- [ ] limit/overflow (a number of tags that should show before showing overflow)
- [ ] condense (when the list should be shown as just a number - might not have to be separate form overflow)
- [ ] sort (function will decide how to order the tags)
- [ ] isEditable (will contain icon button) 

## Additional information

![image](https://user-images.githubusercontent.com/17937450/39721524-73c594b4-5205-11e8-805b-e75a4c04f1db.png)
------------
![image](https://media.github.ibm.com/user/17674/files/161348d2-486b-11e8-9e9f-633e86fada26)

**Comment by joshblack** [comment]
cc @carbon-design-system/design just so you all are aware about this pattern. Feel free to comment if you feel like this is better served in an add-on or if it's valid to be brought into core 👍 

For right now, I believe the work is going into adding it into core, right @bellsworth13? But we can always easily transition over into an add-on if the work is more appropriate there 🙂

**Comment by aagonzales** [comment]
If we're adding it to the core, we should probably do a design review to make sure its not breaking any rules. Is this the work Virginia has been working on? Because I think @tay-aitken has been involved in that work.

We'll need to get the native design assets so we can our Carbon resources.

**Comment by aagonzales** [comment]
Ideally, it would be done before you started coding it but we can review it in the PR if you already have it. We just need to make sure it fits a common usecase and follow are styles and patterns.

**Comment by akulo** [comment]
Hi there. Is there any established design to render multi-select component like this 
![image](https://user-images.githubusercontent.com/10637035/58177780-d3de3700-7c59-11e9-91c2-a428956b6c38.png)

**Comment by ulvidamirli** [comment]
> 

@akulo  Did you find a solution for this?
