### ISSUE TITLE
A11y - Keyboard support for Overflow menu inside Datatable

### ISSUE THREAD

**Issue by asfordmatt** [carbon-design-system/carbon#2642]
Similar to https://github.com/carbon-design-system/carbon-components-react/issues/792
but this issue is about keyboard support.

Can be reproduced using the same sample:
https://codesandbox.io/s/xpn8yl3qpz

1. Use tab key to reach an Overflow menu
2. Press Enter to display the menu
3. Pressing Tab should move focus to the first menu item
4. Pressing Enter should then drive the click action of the menu item

Steps 3 & 4 do not work, as pressing Tab causing the menu to disappear.

v5.43.1

**Comment by dakahn** [comment]
We've implemented arrow key functionality. Closing this as resolved -- let me know if that's off base.

http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
