### ISSUE TITLE
Discussion: Add typescript types

### ISSUE THREAD

**Issue by paul-sachs** [carbon-design-system/carbon#2647]
## Detailed description

This is more of a discussion rather than an issue itself. We've started using typescript over many of our apps and I'm trying to identify what we can do to add more documentation wherever we can. I've found a library [react-to-typescript-definitions](https://www.npmjs.com/package/react-to-typescript-definitions) that provides some ability to generate types from prop types. However, the library doesn't fit to some of our setup and we have a few exceptions that aren't supported by the tool. We would need to manually edit the output somewhat.

How do people feel about supporting type definition files? I was thinking that each component would have a type file (`types.d.ts`) within the directory to explain it's exports. We would need to do some processing on those files to combine in to a single types definition.

Thoughts?

**Comment by Yohanna** [comment]
I'd also be interested to help contribute to this! :)
