### ISSUE TITLE
MultiSelect dropdown:  CheckBox is not working properly.

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [carbon-design-system/carbon#2648]
## Detailed description
MultiSelect CheckBox is not working when we provide a function to onChange e.g. `onChange={(value) => { setMinute(value.selectedItems) }} ` checkbox is not getting checked on clicking how ever callback function is able to grab the value. Help needed to understand how to use this component if i am using it in wrong way.

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
MultiSelect 

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?

    "carbon-components": "^8.5.0",
    "carbon-components-react": "^5.8.1",
    "carbon-icons": "^6.2.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code

   `import MultiSelect from 'carbon-components-react/lib/components/MultiSelect';`
  
          <MultiSelect
              className='hour-setMinute'
              label="Minute"
              items={Array(59).fill().map((e, i) => {return { text:(i+1).toString(), value:i+1 }})}
              itemToString={item=>(item ? item.text : '')}
              onChange={(value) => { setMinute(value.selectedItems) }}
           />

         Function attached to onChange

          setMinute (value) {
               const minuteValue=value.map((data)=>{return data.value}).toString();
               console.log("value",minuteValue);
               this.setState({minute: minuteValue})
               this.props.generateCronExp({
               calendar: {
                   cronExp: minuteValue + ' ' + this.state.hour + ' ' + this.state.date + ' ' + this.state.month 
                  + ' ' + this.state.day,
                  runOnceOncheck: this.state.isRunOnceOncheck,
                 timeZone: this.state.timezone,
                  every: this.state.scheduleType
                     }
               })
          }

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20160628/35036326-02c9b0e0-fb9a-11e7-96be-c92f362a6ee3.gif)

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment]
Thanks for sharing! Mind creating a separate issue to help us track what's going on here?
