### ISSUE TITLE
Data Table: Inline Editing

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2649]
This issue is to add in the inline editing behavior for `DataTable` and includes the following:

- [ ] Create initial API design for Inline editing
- [ ] Gather feedback from sponsor teams on API design
- [ ] Initial implementation of inline editing
- [ ] Create corresponding storybook story for feature
- [ ] Add corresponding tests for feature
- [ ] Conduct self-audit on any potential a11y or i18n hiccups we might run into

[Spec](https://github.ibm.com/Bluemix/carbon-issues/issues/385)

**Comment by theetrain** [comment]
Hi I'm very much interested in an inline editing feature for the data table (I'm impressed with Carbon Svelte, which is what I'm using). Is there still an appetite for this?
