### ISSUE TITLE
Tooltip content not accessible 

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/carbon#266]
Tooltip content is not accessible with the cursor.

![tooltip1](https://user-images.githubusercontent.com/6370760/29134193-898168b2-7cfb-11e7-99f8-29d5cc3bc602.gif)

In this implementation we are using a tooltip to show information that is being shortened by ellipses. The link in the tooltip isn't accessible because it hides as soon as the cursor leaves the trigger area. The tooltip should be accessible to the cursor. If not be default than it should at least optional functionality.

![tooltip2](https://user-images.githubusercontent.com/6370760/29134207-946a6030-7cfb-11e7-894c-7adb1e219b17.gif)

**Comment by hellobrian** [comment]
According to our [usage guidelines on Tooltip](http://carbondesignsystem.com/components/tooltip/usage), they're meant to be short and read-only. Are you trying to allow the user to copy-paste a lengthy subdomain URL? 
Highlighting, right-clicking and copying the text should still be able to allow users to capture the entire URL.

**Comment by hellobrian** [comment]
Another option is to use `tooltip--simple`, which is CSS only, unfortunately isn't on our website (It's likely that we haven't updated the page for this component to surface):

```html
<div class="bx--tooltip--simple">
  <p class="bx--tooltip__trigger">CSS Tooltip</p>
  <div tabindex="0" class="bx--tooltip--simple__top" data-tooltip-text="This is some tooltip text">
    <svg width="16" height="16" viewBox="0 0 16 16" fill-rule="evenodd">
      <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm0 4c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1zm2 8H6v-1h1V8H6V7h3v4h1v1z"></path>
    </svg>
  </div>
</div>
```

**Comment by iangfleming** [comment]
I'll second what @hellobrian said. The content of a tooltip is meant to be read only. You could probably modify it to work in this situation but I would recommend it. @davidmenendez is there a designer working on this part of the UI?

**Comment by davidmenendez** [comment]
@hellobrian @iangfleming I'm working with Spencer Reynolds and Micah Linnemeier. After trying to implement the tooltip in the second screenshot we agreed that it would make sense in that context to have the tooltip be interactive. I'm not saying that tooltips need to be an element that contains a lot of interactivity or functionality, but I can absolutely see the benefit in allowing information inside the tooltip to be highlighted at the very least.

Take https://atomiks.github.io/tippyjs/ for example. They have a tooltip under "interactivity" that has the exact sort of functionality that I'm looking for.

**Comment by iangfleming** [comment]
@davidmenendez oh okay! That makes sense. Unfortunately adding this functionality would require a significant refactor of both Tooltip and the internal Floating Menu component that drives it. 

@chrisdhanaraj this should be added to sprint planning! Basically, we need an option that can be set on Tooltip called "interactive" or something. It would extend the mouseover/mouseout listeners to the body of the tooltip as well as the trigger.

**Comment by SpencerReynolds18** [comment]
^sweet, we definitely want the user to be able to highlight & Copy-paste. We have considered even putting a hyperlink into a tooltip. Thanks for picking this one up.

**Comment by hellobrian** [comment]
Yeah, I'm all for making Tooltip more flexible. 

We also suggest [using a Modal as an alternative to Tooltip](http://carbondesignsystem.com/components/tooltip/usage) when you need more real-estate or more flexibility for interactions. Have you all tried this already? Maybe it was overkill for what you wanted?

**Comment by davidmenendez** [comment]
@marijohannessen status?

**Comment by tw15egan** [comment]
This has been implemented on the React side, just need to mirror it on the vanilla side

**Comment by davidmenendez** [comment]
@tw15egan i see that's the case with the "click to open" variety, but not the hover
![tooltip](https://user-images.githubusercontent.com/6370760/36225905-d5df2b1a-1191-11e8-9d6d-4fd66ffbdb0c.gif)
This was taken from http://react.carbondesignsystem.com/?selectedKind=Tooltip&selectedStory=default%20%28bottom%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by tw15egan** [comment]
What would you expect the behavior to be for a hover interaction? Would you expect it to stay on the screen after mouse out for `x` amount of seconds?

**Comment by marijohannessen** [comment]
I think he's talking about hovering over the tooltip icon AND the tooltip content should keep the tooltip open - not just by hovering over the tooltip icon.

**Comment by tw15egan** [comment]
Is there a large enough path between the icon and the tooltip content so that it would not trigger a mouseout?

**Comment by marijohannessen** [comment]
I think we just need to add the invisible padding that we added to the unified header back in the day that allows for a bit extra room for the mouse so it doesn't trigger a mouseout

**Comment by davidmenendez** [comment]
I personally would expect it to interact in a way that the tooltip content is an extension of the tooltip trigger. The way https://atomiks.github.io/tippyjs/ under interactivity handles it is exactly what I would expect.
![tooltip_good](https://user-images.githubusercontent.com/6370760/36226587-dd67838a-1193-11e8-9967-cdb136b5fcb1.gif)

**Comment by tw15egan** [comment]
This makes sense

**Comment by tw15egan** [comment]
We just need to make sure it works like ^, because I thought we removed all flyouts from the unified header because accidental closing of menus
