### ISSUE TITLE
Commit / PR naming conventions for 

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2666]
Now that we have vanilla components, React components, and elements... many packages... how can our PRs use conventional commit syntax to generate package-specific changelogs?

E.g. I'm using the `@carbon/react` package for all React core components. How do I see what's new?

E.g. I'm just using `@carbon/button-react` package, how can I see what's new in each release?

Acceptance criteria:

- [ ] Consistent commit and PR naming for all packages
- [ ] Just root-level package Husky config or however we enforce conventional commit messages
- [ ] Document this in `/docs`

P.S. I wonder if we should pull "contributing" content (syntax style, commit messages, sassdoc annotation style, etc) out of the .github directory and into `/docs` because the docs directory is much more discoverable.

**Comment by mattrosno** [comment]
Not stale

**Comment by mattrosno** [comment]
@joshblack I can add these type definitions to our `docs/developing.md`: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

**Comment by mattrosno** [comment]
@joshblack any guidance that we want to give on conventional commit scope? Is it a component? Is it a package? What if the commit spans multiple commits. What's best for our changelog generation?

**Comment by kinueng** [comment]
Could we add the PR/commit convention to a `CONTRIBUTING.md` file in carbon instead of the `docs/developing.md`?  

The `CONTRIBUTING.md` has a step[1]  that mentions briefly the commit message convention.  

[1] https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#8-make-a-pull-request

**Comment by joshblack** [comment]
@mattrosno yeah that would make sense, I think. For scopes that's a great question, and it might help if we set allowed scopes. When looking at larger projects, it seems like the scope tends to be the package name so might help just to stick with that.
