### ISSUE TITLE
AVT violation on modal of close button

### ISSUE THREAD

**Issue by jacklotusho** [carbon-design-system/carbon#267]
Using URL http://carbondesignsystem.com/components/modal/live

Click Passive button and popup the modal, run the DAP test, and getting AVT violation of close button on the modal.

![image](https://user-images.githubusercontent.com/12465435/29143499-6c58a822-7d23-11e7-96e1-1bf45550bab4.png)

**Comment by hellobrian** [comment]
This is fixed in the latest release of `carbon-components`. The website just needs to update to the latest release and get redeployed.
