### ISSUE TITLE
Update sync task to handle markdown

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2673]
This issue is to update our `tasks/sync.js` task to synchronize markdown across our packages. There is existing work for this under: https://github.com/carbon-design-system/carbon/tree/master/tasks/remark that was removed during the migration, we can reference: https://github.com/carbon-design-system/carbon-elements/blob/master/tasks/sync.js#L131 for how this was done over in elements.

In general, the goal of this update will handle:

- [ ] Synchronize `README.md` files in each `package.json` file
- [ ] Handle any discrepancies with these updates by adding, remove, or updating automatically generated sections

It would also be great if we could handle generating the table in the root `README.md` file, as well, so that the table wasn't manually created.

**Comment by mattrosno** [comment]
Not stale
