### ISSUE TITLE
Resolve layer tokens & add guidance on usage

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2674]
> Layer tokens is currently removed from v10 so I'm not sure what the game plan is for z-index applications. When we took out "Layers" guidance we didn't know this is still alive on the dev's side (duh!). Making an issue for future to resolve.

_Originally posted by @shixiedesign in https://github.com/carbon-design-system/carbon/pull/2660#issuecomment-491363130_

**Layers** page was removed from website because DL is moving towards a "flatter" look and feel. This doesn't mean layers are out of the equation. Layer tokens still exist in code base and we need to propose a reasonable update to it, and surface updated guidance on how layers are used in the new DL. 

This is related to my **Spatial modals** work early last year.

**Comment by asudoh** [comment]
Ping @shixiedesign to see if there still is her interest in this.

**Comment by shixiedesign** [comment]
Need to be resolved. Just not high priority at the moment.

**Comment by shixiedesign** [comment]
not stale
