### ISSUE TITLE
[Text input] Dynamic list

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2679]
### Feature description

Design & feature contribution from Andrew Nelson: https://github.com/carbon-design-system/carbon-contribution/issues/10

> The goal was to allow a user to quickly build a list of items. I'm personally using this pattern in a couple of places to allow a user to type a list of emails and make a binary admin/not-admin selection for each one. This would not have been possible as a csv list in a text area, and the table component is far too heavy visually for such a simple list.

> Cyrus Furtado (@cfurtado on Slack & IBM Github) on my team built it, and I designed it.

Demo: https://codesandbox.io/s/523355y4l

### Design spec

After conversation in contribution issue, we arrived at the following design for this item:

![image](https://user-images.githubusercontent.com/15144993/57552455-957b7a80-7331-11e9-803a-dfde18f00d84.png)

**Comment by asudoh** [comment]
One UX question @shixiedesign - The CodeSandbox demo keeps the entered text after addition. Should we do the same or should we clear the text box after addition? Thanks!

**Comment by shixiedesign** [comment]
Good catch! Yes I believe that's a bug. Text field should be cleared in anticipation of different content to be entered.

**Comment by werdnanoslen** [comment]
Yep, I just quickly made that codesandbox.io demo code. The input should clear.

**Comment by werdnanoslen** [comment]
For the entered items, would it make sense to use the readonly variant from https://github.com/carbon-design-system/carbon/issues/2177?

**Comment by shixiedesign** [comment]
@werdnanoslen I had the same thought, though Read-only variant gets the `not-allowed` cursor, which would be confusing and user could miss the fact that the button is still clickable. We might remove the `not-allowed` cursor in our specification. It might be an overkill to demonstrate the field is not editable. Thoughts?

**Comment by werdnanoslen** [comment]
Yeah, definitely don't think that cursor should be used here. We're also not using the `border-bottom` on the entered items, so it's more like a tile component than an input component, right?

**Comment by shixiedesign** [comment]
We needed the underline to show that it's still a `text-input` and not a button, even though read-only. 
Agreed, might make more sense as a tile varian.

**Comment by werdnanoslen** [comment]
not stale

**Comment by werdnanoslen** [comment]
not stale

**Comment by shixiedesign** [comment]
Still keeping an eye on this. Component enhancements are not high on the prioritization list recently. @werdnanoslen Could you provide a few full page screenshots of this component in context?

**Comment by werdnanoslen** [comment]
@shixiedesign They only exist in Sketch/Invision right now, but it will go into development soon. It's also for an unreleased product, so I'll share on internal channels...

**Comment by werdnanoslen** [comment]
not stale

**Comment by werdnanoslen** [comment]
@shixiedesign we have a locally deployable version that I'll DM you

**Comment by aagonzales** [comment]
@shixiedesign @werdnanoslen where do we stand with this issue? What are the next steps? What else is needed (doing some planning so what if anything does Carbon need to do for this)?

**Comment by werdnanoslen** [comment]
@aagonzales I'm not sure what next steps are, but just keeping this issue open until we figure it out...

**Comment by designertyler** [comment]
Thanks for the proposal! It looks like we've had some good conversations around this request.

We thank this is more suitable in a PAL or sub-system library. We'll close this issue for its addition to the core Carbon library. Please reopen is you think this is something that needs to be reconsidered.
