### ISSUE TITLE
Tooltip in form label with clickToOpen never opens

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#2686]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If you use Tooltip with clickToOpen in a TextInput with an id, the Tooltip never opens.  This is because the click on the Label forces a second click event on the Field contents.  We need to put a evt.preventDefault on this line of code to stop the default redirect to the Form Field from firing

> Is this issue related to a specific component?

Tooltip
> What did you expect to happen? What happened instead? What would you like to
> see changed?
I need to be able to use Tooltips in the Labels of form elements like this:
![image](https://user-images.githubusercontent.com/6663002/57581466-fb920a00-74b7-11e9-9f57-c6e233f5a9b9.png)

> What browser are you working in?

> What version of the Carbon Design System are you using?
6.111.0
```
 handleMouse = evt => {
    const state = {
      mouseover: 'over',
      mouseout: 'out',
      focus: 'over',
      blur: 'out',
      click: 'click',
    }[evt.type];
    const hadContextMenu = this._hasContextMenu;
    this._hasContextMenu = evt.type === 'contextmenu';
    if (this.props.clickToOpen) {
      if (state === 'click') {
        evt.stopPropagation();
      /* Need this extra line of code to prevent the default form event from firing */
  evt.preventDefault();
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/mrp45kj3x

Note that if you remove the "id" attribute of the TextInput it will work.  This is because the default label to Form field click doesn't happen.

**Comment by cx0der** [comment]
I would like to give this issue a try.
