### ISSUE TITLE
Remove hardcoded css prefix

### ISSUE THREAD

**Issue by deblasis** [carbon-design-system/carbon#2694]
### Summary

There's a number of hardcoded `bx--` css prefixes referenced here and there. It would be great to have them replaced with the corresponding variable from **carbon-components**

I believe the issue affects only development.

### Justification

We are considering carbon for some of our products and we really like it so far, it's maybe not super straight-forward to whitelabel/customize and perhaps we can help with that starting with a PR to address this issue.

### Desired UX and success metrics

Since the framework offers the ability to customize the css-prefix, I believe that in order to be consistent, all the hardcoded references to `bx--` should be replaced. Even in tests.

Perhaps the main advantage/success metric could be the fact that storybook as well uses the variable instead of the hardcoded value.

The user would just have to override the SCSS and a settings.js file to obtain a real-life scenario.

### "Must have" functionality

No more hard coded prefixes? :)

### Specific timeline issues / requests

I already have a PR that fixes this 😄 that I will reference for your convenience.

### Available extra resources

Nope

**Comment by asudoh** [comment]
Seems that we can close this - Thanks @deblasis for reporting and fixing!
