### ISSUE TITLE
Slider: `onRelease` sometimes doesn't fire

### ISSUE THREAD

**Issue by clawisan** [carbon-design-system/carbon#2695]
## Detailed description

When changing the slider value, the `onRelease` event doesn't fire sometimes. This happens inconsistently, but usually every 20 or so attempts. I can reproduce this by starting at any position on the slider (0-100%), dragging, and finally releasing at any other point on the slider, but it seems to happen more often when I release at 0%. 

My expectation is that every time I release the handle, `onRelease` is fired and should be the last event to be fired (after all the `onChange`s that occurs during the drag).

__Component version:__ carbon-components-react@6.107.0 and the version currently running on Carbon Storybook

__Browser:__ Chrome 74.0.3729.108 (Official Build) (64-bit)

## Steps to reproduce the issue

1. In the slider component in Storybook http://react.carbondesignsystem.com/?selectedKind=Slider&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Drag the handle from anywhere on the slider (eg. 50%) to a different position (eg. 0%)
3. Release the handle

## Additional information
Video reproducing the problem in Storybook
[carbonslider_onrelease.mp4.zip](https://github.com/carbon-design-system/carbon-components-react/files/3170831/carbonslider_onrelease.mp4.zip)

Would it be possible to get a fix for v9 urgently as we need to meet our timeline for May?

**Comment by mattrosno** [comment]
@dakahn can you make sure this issue makes it to the correct triage project?

**Comment by dakahn** [comment]
Thanks for submitting! The issues is in our backlog, but for an expedited resolution consider contributing a PR to the project.

**Comment by jharvey10** [comment]
I can reproduce this issue consistently on the storybook by dragging the slider and releasing it while I'm still moving my mouse to the side. If I stop moving for a moment and then release my mouse, typically the onRelease event will fire, but if the mouse is still moving, it almost never fires.

Also, this is much more noticeable on mobile because the touch point of my finger tends to move a bit as I adjust the pressure I'm using to hold/release the slider.

**Comment by joshblack** [comment]
Removing the v9 label as this also applies to latest!
