### ISSUE TITLE
TileGroup never renders the legend attribute

### ISSUE THREAD

**Issue by zgrossbart** [carbon-design-system/carbon#2696]
Look at the TileGroup example here:  http://react.carbondesignsystem.com/?selectedKind=Tile&selectedStory=Selectable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

The example has a `legend` attribute with a value of `Selectable Tile Group`, but that attribute is never added to the `fieldset` element for the TileGroup.  This means there's no way to set a legend for the TileGroup and that results in the following accessibility issue:

![Screen Shot 2019-05-10 at 7 40 26 AM](https://user-images.githubusercontent.com/664044/57524811-f0dc4700-72f6-11e9-96ae-72de9d1658ad.png)

**Comment by dakahn** [comment]
@zgrossbart I see you put up some work against this issue! ❤️ did you want to open a PR?

**Comment by zgrossbart** [comment]
@dakahn, this is already fixed.  What would you want the extra PR to do?

**Comment by abbeyhrt** [comment]
Nothing, thanks for getting back to us!  We  just weren't sure that this was fixed since we couldn't find a PR that addressed it.
