### ISSUE TITLE
[Dropdown, react] Missing drawer animation

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2697]
Dropdown is missing the drawer opening and closing animations. This should match vanilla's dropdown: https://the-carbon-components.netlify.com/component/dropdown--default.html

Motion spec: 
easing: `motion(entrance, productive)`
durration: `$duration--fast-02`

**Comment by lovemecomputer** [comment]
looks like this the `ListBox` used in react doesn't share al the same classnames, thus is missing the transition rules. looking into best solution (adding class rules to `components`, or adding additional classnames to the react component)
