### ISSUE TITLE
Update project tasks and packages to work on windows

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2700]
We're running into a couple of issues when developing Carbon on windows that need to be fixed. This issue will serve as a reference for what we've encountered so far:

- [ ] #2434 
- [ ] `stylelint` staged task incorrectly cannot find paths

**Comment by asudoh** [comment]
CC @emyarod

**Comment by emyarod** [comment]
not stale, but haven't had a chance to do additional work on Windows yet
