### ISSUE TITLE
[Icon package] Add not-editable icon

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2708]
Adding an icon for `not-editable`. This is needed in Read-only text input fields: https://github.com/carbon-design-system/carbon/issues/2177

![image](https://user-images.githubusercontent.com/15144993/57653002-73cefd00-7596-11e9-8755-51a7ff3e9949.png)

**Comment by chrisconnors-ibm** [comment]
I see `packages/icons/src/svg/32/edit--off.svg` - does this need an actual (rather than scaled from 32) 16x16 asset in `packages/icons/src/svg/16/`?

**Comment by chrisconnors-ibm** [comment]
(just in case) https://github.com/carbon-design-system/carbon/pull/2778
