### ISSUE TITLE
[Bug, react]: Tile component does not pass a valid event object to callbacks

### ISSUE THREAD

**Issue by matthew-chirgwin** [carbon-design-system/carbon#2713]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

The Carbon React `Tile` component offers the ability to provide a callback on click and keypress which passes an event object to the callback to consume. I went to use this event object to check the type of the event, but instead saw all values on the event were `null`. In addition, a warning about trying to use a React `synthetic event` post release was present in the devtools console.

Looking at the code, both `handleClick` (https://github.com/carbon-design-system/carbon-components-react/blob/927e2a1e9b09b91844e4d70c70bcf5f594ec5d92/src/components/Tile/Tile.js#L80) and `handleKeyDown` (https://github.com/carbon-design-system/carbon-components-react/blob/927e2a1e9b09b91844e4d70c70bcf5f594ec5d92/src/components/Tile/Tile.js#L92) call the callback post `setState` callback. 

Being a callback, React will cleared the event, meaning the event when passed to my callback via props will be in this cleared state. In each case, if a copy of the event was made prior to `setState` being called, and that copy passed instead, my code would then get the event's values on call.

I am working on a side project as a part of Event Streams development, so there is no time pressure for a change to be made.

## Steps to reproduce the issue

See code sandbox: https://03knn0o0lw.codesandbox.io/

Click or use the keyboard to interact (either click or keypress) with the tile, the following warning will appear:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `type` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

Code: https://codesandbox.io/s/03knn0o0lw

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! And PR with `evt.persist()` fix is much appreciated.
