### ISSUE TITLE
[FileUploader/FileUploaderButton, react, bug?]: FileUploader & FileUploaderButton component in react adds `bx--btn--sm` CSS style to the button which is not present in VanillaJS implementation

### ISSUE THREAD

**Issue by rraavi** [carbon-design-system/carbon#2715]
Packages being used :-
- carbon-components v10.2.0
- carbon-components-react v7.2.0

Issue might be localized to following packages :- 
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Looking at the documentation [here](https://www.carbondesignsystem.com/components/file-uploader/code), the button for FileUploader should be normal sized and not a small variant button type which is what the current react package has as shown [here](http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploaderButton&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) 

Poking around the source code, looks like `bx--btn--sm` CSS class is being added for FileUploader & FileUploaderButton, which is causing the button to be a small button.

Wondering if this is expected behavior or a bug..? 🤔 

> Is this issue related to a specific component?
 It's limited to FileUploader & FileUploaderButton component

## Steps to reproduce the issue
- React story book for FileUploader -> http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploaderButton&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by asudoh** [comment]
@emyarod From carbon-design-system/carbon-components-react#1645 I'm getting an impression that the small file uploader button came from `v10` design spec, but #1255 gives me an opposite impression. Do you remember anything...? Thanks!

**Comment by emyarod** [comment]
@asudoh I believe we want to remove the small button class from https://github.com/carbon-design-system/carbon/pull/2048. My guess is this change was never ported into the React codebase?

**Comment by emyarod** [comment]
This issue is no longer present in the component (ref #5166)
