### ISSUE TITLE
[Number input, sketch kit] Remove input hover background changes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2716]
No input should have hover styling beside the cursor type change. I only checked White and G100 themes (haven't checked the others).

![image](https://user-images.githubusercontent.com/15144993/57712809-da0b5c80-7636-11e9-811c-426b22e4275b.png)

**Comment by laurenmrice** [comment]
Pushed change in all kit themes 🎉:
Removed hover background color on Number input, and added appropriate cursor.
![Artboard](https://user-images.githubusercontent.com/43969356/57716893-979a4d80-763f-11e9-9b1f-3cb3facc4d9b.png)
