### ISSUE TITLE
[All inputs, vanilla & react] Remove hover states 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2717]
No inputs should have hover state styling except the cursor type change. Currently noticing **text input, text area, and number inputs** have background color change. Should be removed. Date picker is correct. 
- [x] text input
- [x] text area
- [x] number input
- [x] date picker
- [x] slider
- [x] search

### Correct spec for all inputs' hover states:

![image](https://user-images.githubusercontent.com/15144993/57713383-fc51aa00-7637-11e9-8159-8e2358256bd6.png)

**Comment by emyarod** [comment]
just to confirm, is this the correct hover behavior for the search input clear button?

![Kapture 2019-05-28 at 9 36 27](https://user-images.githubusercontent.com/8265238/58486773-1c02cb00-812c-11e9-8b74-efc4e90693e1.gif)

**Comment by shixiedesign** [comment]
@emyarod nope lol! Should be this: 

![image](https://user-images.githubusercontent.com/15144993/58488251-a9471f00-812e-11e9-8e9b-a46ede5a999d.png)
