### ISSUE TITLE
DatePicker clicking on label doesn't open date picker calendar

### ISSUE THREAD

**Issue by austinbruch** [carbon-design-system/carbon#2718]
## Detailed description

> Describe in detail the issue you're having.

Clicking on the labels for Date Picker inputs (DatePicker with range, for example) does not open the date picker calendar. You have to click on the input field itself to open the date picker calendar.

> Is this issue related to a specific component?

Yes, `DatePicker`.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the date picker calendar to open when clicking on the corresponding label. Instead, clicking on the label does not open the date picker calendar.

> What browser are you working in?

Chrome 73

> What version of the Carbon Design System are you using?

"carbon-components-react": "7.2.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Identity

## Steps to reproduce the issue

1) Render a `DatePicker` component
2) Click on the label
3) See that the calendar did not open.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

https://codesandbox.io/embed/q937w4r65w

## Additional information

- Screenshots or code
- Notes

**Comment by dakahn** [comment]
@carbon-design-system/design 👋 Are labels throwing open forms a supported pattern?

**Comment by shixiedesign** [comment]
It is! And it is the behavior of single date pickers and are supported in v9. This is a bug we should fix.

**Comment by asudoh** [comment]
I see this is fixed in https://react.carbondesignsystem.com/?path=/story/datepicker--single-with-calendar.
