### ISSUE TITLE
Duplicate event listeners are attached by moving around DOM element in watch mode

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#272]
## Detailed description

`CarbonComponents.watch()` introduced in [this PR](https://github.com/carbon-design-system/carbon-components/pull/213) automatically creates components whenever DOM node with `[data-component-name]` attribute is attached to render tree, unless the corresponding component instance is there already.

Moving around DOM element is treaded as deleting and then adding such DOM element from/to render tree. `CarbonComponents.watch()` releases and then re-creates component instance in such scenario.

Some event listeners are not released when those components are released, and re-creation of component in such scenario causes duplicate event listeners. Here’s an example in accordion, the section is not expanded upon clicking because one event listener expands and then another event listener collapses:

![move-dom-with-watch](https://user-images.githubusercontent.com/1259051/29152498-afa8734c-7dc2-11e7-8bf5-89d691504c14.gif)

> Is this issue related to a specific component? 

No

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

Latest master

**Comment by chrisdhanaraj** [comment]
For my education, doesn't the `.on` method handle this on release already? @asudoh

**Comment by asudoh** [comment]
@chrisdhanaraj You are right, but there still are many event listeners that is attached not by `on()`, though - That's what this issue is all about.
