### ISSUE TITLE
[React] Data-table: expandable row border missing

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2723]
The bottom border of the child row `td`'s are missing when it's expanded, and the bottom border of the parent row `td`'s when it's expanded are also missing. These are used as dividers for each expanded row, so it's a bit odd to look at when there's a missing border which makes it seem like 3 rows are connected. 

The hover styles on expand are also incorrect. The border disappears if you hover on the child but re-appears if you hover on the parent (parent hover is correct). See gif below.

`As is`
<img width="1116" alt="Screen Shot 2019-05-09 at 12 28 15 PM" src="https://user-images.githubusercontent.com/32556167/57728525-c3c2c800-7659-11e9-8ef4-470e28ee126c.png">

`As is: hover`
<img width="1107" alt="Screen Shot 2019-05-09 at 12 28 29 PM" src="https://user-images.githubusercontent.com/32556167/57728526-c3c2c800-7659-11e9-9b68-0682f84ba654.png">
![react-dt](https://user-images.githubusercontent.com/32556167/57729106-fae5a900-765a-11e9-986e-6ad9fb46115e.gif)

`Should be: (vanilla)`
<img width="847" alt="Screen Shot 2019-05-09 at 12 30 23 PM" src="https://user-images.githubusercontent.com/32556167/57728527-c45b5e80-7659-11e9-8d9e-fb674f75cd3d.png">
<img width="753" alt="Screen Shot 2019-05-14 at 3 08 41 PM" src="https://user-images.githubusercontent.com/32556167/57729190-31bbbf00-765b-11e9-9c07-14a4792e5549.png">

**Comment by jmcguire23** [comment]
Any indication of when this bug will be fixed?

**Comment by kimberlyandersson** [comment]
@hshockley at Rocket has a fix for this issue in our fork, working on contributing it upstream.
