### ISSUE TITLE
[React] Data-table: first selected row is missing top border

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2724]
When selected, the first row should have a border that divides the row and the table header since they become the same color. Right now it doesn't add the border, so it looks weird.

<img width="720" alt="Screen Shot 2019-05-09 at 12 32 12 PM" src="https://user-images.githubusercontent.com/32556167/57729331-88c19400-765b-11e9-88cc-57bd95853fd7.png">

`Vanilla example`
<img width="803" alt="Screen Shot 2019-05-14 at 3 19 25 PM" src="https://user-images.githubusercontent.com/32556167/57729396-ae4e9d80-765b-11e9-8109-4b49fc819742.png">

**Comment by joshblack** [comment]
I believe this is addressed now in latest!

![image.png](https://images.zenhubusercontent.com/5618bf72638e718c995dadc6/fe1d85b6-1586-4a68-8268-23afc89d2166)
