### ISSUE TITLE
AVT 3 - Modal React Component: Android does not restrict focus to the modal

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon#2740]
**Environment**
Android 9 w/Talkback
Chrome: 73.0.3683.103 (Official Build) (64-bit)

**Issue:**

1. With Talkback on, swipe left or right or use the Alt+arrow keys until you find the button to activate the modal.
2. Double-tap on the button or press alt+enter to launch the modal.
3. The close modal button will be announced and will have focus.
4. Swipe left and right to explore the modal, you can read the text and focus on the cancel and save buttons.
5. The issue is that navigation is not restricted to the modal only, once it is open there is no way to know if there is an open modal present, the user needs to remember it.
6. Double-tap or press alt+enter on the close or cancel buttons to close the modal.

**Comment by snidersd** [comment]
@dakahn Please add the react label to this issue. Thx!

**Comment by emyarod** [comment]
testing with Talkback/the voice assistant on Android 10 and Chrome 80.0.3987.132, the focus sentinel appears to be working as expected and restricting navigation to the modal only (ref #5260). can you confirm that this issue is no longer present?

**Comment by emyarod** [comment]
closing as this issue no longer appears to be present
