### ISSUE TITLE
Documentation for using IBM Plex with Carbon

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2744]
There are multiple ways to incorporate IBM Plex into ones project when using Carbon, however we want to make sure we're covering everyone's use-cases to make sure we're offering the best guidance.

This issue will serve as an umbrella for feedback/use-cases that teams might have for using/distributing IBM Plex. We'll take the feedback here and create docs and tooling to better support these use-cases 👍

**Comment by nictownsend** [comment]
Is there any update on this issue? I have a use case where there is no network access so will need to host and serve plex locally - current documentation is not clear on how to do this via `@carbon/type` for the font faces.
