### ISSUE TITLE
FileUploader with multiple files

### ISSUE THREAD

**Issue by elymatos** [carbon-design-system/carbon#2747]
## What package(s) are you using?
carbon-components - 10.2.0 - Vanilla Javascript

## Summary
When selecting multiple files with FileUploader, the filenames are shown inside container, but just the last file inserted is sent.

## Relevant information
- The backend is PHP7 and the $_FILES show just one file.
- Submission is done by browser (not via Ajax)

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! You are right that our file uploader has only one `<input type="file">`. You can hook for its `onchange` event and grab the file blob via [`.files` property of the `<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#files). That said, you need to do AJAX call, e.g. upon form submission event, or perhaps move the `<input type="file">` to somewhere in your form, make it invisible, and put an new one to the original location. Hope this helps!
