### ISSUE TITLE
[Tooltip] More universal tooltip positioning rules

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2748]
Tooltip positioning is currently based on arbitrary values and depends on the dimensions of the parent element. We can refactor the tooltip positioning rules to be more universal and avoid magic numbers

ref https://github.com/carbon-design-system/carbon/pull/2731

**Comment by emyarod** [comment]
additional proposal:

rather than aligning the edge of the tooltip body to the edge of the tooltip trigger button like we do currently, could we align the edge of the tooltip content to the center of the tooltip caret?

current

![image](https://user-images.githubusercontent.com/8265238/57894451-a08c4a00-780c-11e9-80ce-e61ec005216d.png)

![image](https://user-images.githubusercontent.com/8265238/57894469-b6017400-780c-11e9-8dc9-edcb3430ce71.png)

proposal

![image](https://user-images.githubusercontent.com/8265238/57894481-bdc11880-780c-11e9-8d81-1dd159089605.png)

![image](https://user-images.githubusercontent.com/8265238/57894489-c31e6300-780c-11e9-8cd0-df2044869f9e.png)

**Comment by shixiedesign** [comment]
Having a bit more space on the narrow end looks better, though the trouble is the tooltip can get cut off if the trigger button is already at the edge of the window.

**Comment by emyarod** [comment]
yeah I thought this is why we are providing new tooltip position options as well

**Comment by emyarod** [comment]
after further discussion, we came to this conclusion:

Definition tooltip:

* tooltip box will be aligned to the trigger button edge
* tooltip caret will be center aligned to trigger

Icon tooltip:

* tooltip box will be aligned with the trigger button edge
* tooltip caret will be center aligned to trigger button

![image](https://user-images.githubusercontent.com/15144993/58039650-f60c7380-7af8-11e9-9bc3-a4f05a165359.png)

**Comment by shixiedesign** [comment]
### 📖 Guidelines to add 
**Definition tooltip usage:** @connor-leech 

Definition tooltips should be used on proper nouns, technical terms, or acronym with 2 letters or more. Do not use definition tooltip on words less than 2 letters.
