### ISSUE TITLE
Add character count feature for Text input component in kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2750]
![Screen Shot 2019-05-16 at 10.42.34 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/012e91f9-f3d4-4275-86bb-089ea52f12fe)

**Comment by shixiedesign** [comment]
FYI @laurenmrice! We just merged text input & area inputs character counter. https://github.com/carbon-design-system/carbon/pull/2745 so whenever you can, kit can be updated now.

**Comment by laurenmrice** [comment]
Character counter in all kits 🎉
