### ISSUE TITLE
[Button, sketch kit] Add 40px Button component variation

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2752]
- [ ] Add 40px Button to accompany 40px height of fields.
![Screen Shot 2019-05-16 at 10.25.20 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/18da7c59-b490-4e4c-b1c5-60da8751abc8)

**Comment by gulyasbence** [comment]
This is amazing. I was just recently scratching my head while designing an input inline with a button... Is there an approx timeline when this is gonna get released?

**Comment by laurenmrice** [comment]
@gulyasbence I will be adding this to the kit once it has been developed in code. You can follow the dev #2365 that relates to this design kit issue. :)

**Comment by gulyasbence** [comment]
Perfect, thanks!

**Comment by laurenmrice** [comment]
Updated in all kits ! 🎉
