### ISSUE TITLE
Modal: Button state overrides unavailable

### ISSUE THREAD

**Issue by janedepgen** [carbon-design-system/carbon#2756]
## Detailed description

> What version of the Carbon Design System Kit are you using?

https://sketch.cloud/s/JaVzz – updated Apr 22

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Transactional and danger modals

> What did you expect to happen? What happened instead? What would you like to see changed?

The Modal Symbol does not allow the user to override the **states** of the primary and secondary buttons within the modal. Ideally, the Sketch user should be able to override each button to reflect hover, focus, and disabled states. As shown in the screenshot below, the user is currently only able to change the text on each button.

<img width="879" alt="Screen Shot 2019-04-25 at 2 38 37 PM" src="https://user-images.githubusercontent.com/37704490/56760028-45fd5200-6768-11e9-99a2-a85446c5ce22.png">

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health, no pressing dates! 🙂

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by laurenmrice** [comment]
fixed in all kits 🎉
