### ISSUE TITLE
[Data table, sketch kit] Update to have Expand all chevron

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2771]
Dev issue: https://github.com/carbon-design-system/carbon/issues/679

Improving Data table symbol in sketch kit to support turning on the Expand all function. 

Expandable data table with expand-all-chevron 

![image](https://user-images.githubusercontent.com/15144993/57668928-b9a7b780-75ce-11e9-899c-626283d6fbe8.png)

Expandable & selectable data table with expand-all-chevron 

![image](https://user-images.githubusercontent.com/15144993/57672204-c92dfd00-75dc-11e9-8c10-0201559b58ac.png)

**Comment by laurenmrice** [comment]
expandable in all kits  for 10.3 release. Going to close this issue and make a new one for only the selectable + expandable symbol, this will take some more time because we will have to make new cell symbols and headers.
