### ISSUE TITLE
AVT3(Tab with JAWS) can't open menu using enter.

### ISSUE THREAD

**Issue by jacklotusho** [carbon-design-system/carbon#278]
AVT3(Tab with JAWS) can't open menu using enter.(It is working fine on AVT2 Tab/Enter without JAWS)

Our menu is unified carbon menu, but it can't be opened by Tab/Enter with JAWS active.
The below screen is AVT2 using Tab and Enter.
![image](https://user-images.githubusercontent.com/12465435/29275676-e21b37a0-80d9-11e7-8778-11149beaf0b6.png)

**Comment by tw15egan** [comment]
This is no longer a Carbon component and must be addressed by the product team
