### ISSUE TITLE
ToastNotification and InlineNotification subtitle and caption should not be required

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#2780]
The Carbon Design System usage for Notifications (https://www.carbondesignsystem.com/components/notification/usage#format) indicates Notification titles are required ("All notifications have subject titles"). It makes no such statement for Notification subtitles or messages. Though it does imply that both subtitles and messages should be optional ("When possible, communicate the main message using just the title.")

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

carbon-components-react InlineNotification requires subtitle props, defaults its value to "subtitle", and always the subtitle . The only way to "hide" the subtitle is to set its text to " " or override its styling.

The same is true for ToastNotification subtitle and caption

> Is this issue related to a specific component?

Yes, carbon-components-react's InlineNotification  and ToastNotificiation

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the subtitle and caption props to be optional, have no default value, and not be rendered when undefined

> What browser are you working in?

Chrome 74

> What version of the Carbon Design System are you using?

carbon-components@10.2.0
carbon-components-react@7.2.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

System Z Hardware Management Console. Release date has not be made public yet.

## Steps to reproduce the issue

https://codesandbox.io/embed/vigorous-williams-r9v1w (Note InlineNotification failed to render in codesandbox)

## Add labels

package: react

**Comment by asudoh** [comment]
@carbon-design-system/design Is the subtitle required or optional...? Thanks!

**Comment by laurenmrice** [comment]
The subtitle can be optional depending on the content of the message. @asudoh
