### ISSUE TITLE
X (close) icon needs mulitple size versions (per size)

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#2791]
X (close) icon needs mulitple size versions (per size)

As per conversation in slack;
https://ibm-studios.slack.com/archives/CDT9TSUAJ/p1558103999003800

It appears a decision was make to use the X icon at 50% size compared to it's peers in an icon size set.  IOW if the set is 32x32px, the X icon will be 16x16 within it's 32x32 canvas/artboard.  My understanding from the thread was that it looks better on a modal (which imho should have simply introduced a smaller icon for modals)

Now the problem is when used with other icons from it's size category, the X icon looks out of place since it is half size from the others:

![image](https://user-images.githubusercontent.com/24781332/58112160-ef493380-7bc0-11e9-9f9b-e6b5e1918170.png)

Granted I could swap it out for a larger one, but this breaks the intent of the carbon system when using pre-build components, in this case an icon button – which is a 32x32 button containing a 16x16 icon (which ends up being only 8x8!).  I'd have to customize/code this one simply because a smaller icon looks better on a modal?

Instead I suggest offering two instances of icons in such situations.  One which is 16x6, and the icon is actually 16x16 (or ~14x14 if looks better), the other 16x16 with inside 8x8 or whatever makes sense for the modal edge case. (or just size the edge case from a properly sized icon)

**Comment by laurenmrice** [comment]
We are using the 16px close icon in multiple components that are used for `forms`. The 16px close icon is usually paired next to the 16px chevrons. For these situations we are also planning to add a rule in between multiple icons inline to help divide them (as Anna mentioned as a possible solution in the slack thread).

![form](https://user-images.githubusercontent.com/43969356/79010070-c0b0b000-7b26-11ea-92d2-53a4cd312893.png)

We now use the 20px close icon in Modals and Notification.

From a system perspective, we can only have one 16px close icon asset present at a time and will not be providing multiple size variations of it inside of the 16px container. This could lead to usage inconsistencies and cause some confusion if there were only internal size variations for one icon. 

There has been discussion in the past about exploring our 16px icon sizes as a whole, but no further decision has been made. If this change comes into play in the future, I will reopen and reference this issue to keep it into consideration. 👍🏻
