### ISSUE TITLE
Structured list header isn't resizable

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon#2793]
In the latest Sketch Library (from Cloud), the `Theme: white / structured list / item / header / 2 column offset` symbol's left column label breaks at 6 columns on the large grid size, which means it can't be used at different widths without detaching it from the symbol.

![May-02-2019 13-35-52](https://user-images.githubusercontent.com/764090/57094776-5751db80-6cdf-11e9-80cb-167c8447b4c2.gif)

**Comment by werdnanoslen** [comment]
latest release LGTM 👍

**Comment by laurenmrice** [comment]
awesome !
