### ISSUE TITLE
Content switcher - disable option

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon#2794]
## Detailed description

Would be great if you guys can add a disable option as I need one :)

> What version of the Carbon Design System Kit are you using?
10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

<img width="412" alt="Screen Shot 2019-05-16 at 12 52 11 PM" src="https://user-images.githubusercontent.com/12818623/57872398-96048d00-77d9-11e9-9011-d4301a13ae49.png">

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
for Watson Health product

**Comment by laurenmrice** [comment]
added to all kits 🎉
