### ISSUE TITLE
Overflow menu is not working in a Modal

### ISSUE THREAD

**Issue by kiddove** [carbon-design-system/carbon#280]
I'm using an overflow menu inside a modal, but it didn't show up when I clicked. I noticed that overflow menu has a z-index value of 7000, and modal's z-index is 9000. But even I've set large enough z-index to overflow menu, it still won't show up.
![image](https://user-images.githubusercontent.com/2195199/29279189-10ed4220-80e5-11e7-9482-ca5b5e9dfec5.png)

**Comment by theoshu** [comment]
This also happens with regular tooltips in modals.

**Comment by tay-aitken** [comment]
Hi @theoshu what tasks does the overflow menu contain? We do not recommend using an overflow menu in a modal. That is also not the proper use of the icon. Please tag your designers in this issue if they have further questions on the usage.

**Comment by theoshu** [comment]
I was commenting on the tooltips also doing this. Perhaps @kiddove can elaborate.

**Comment by kiddove** [comment]
Hi @tay-aitken, we are using the overflow menu as shown in the picture(the icon is different), to show a list of known servers when user is signing in. Could you please advise us what is the proper way of doing that in the modal if the overflow menu is not recommended?

**Comment by tay-aitken** [comment]
@kiddove could you please upload screen shots of the whole flow/interaction, so I can better understand what you are trying to achieve?

**Comment by kiddove** [comment]
@tay-aitken , here is the screen shot from our designer's demo site, we are looking for a proper way to show a list of servers within a modal. Now we are using overflow menu.
![image](https://user-images.githubusercontent.com/2195199/32330850-c58758c2-bfb7-11e7-9969-e493a320521c.png)

**Comment by aagonzales** [comment]
I think this is actually interaction will be replace by a combo box once it its release (it allows for typing and also selection from a dropdown menu). This was not the intended usecase for an overflow menu.

@tay-aitken can share the latest version with you. Tayler I think this is similar to Matthew's usecase.
