### ISSUE TITLE
May 2019 Endgame

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#2804]
This is the endgame schedule for our May 2019 iteration, which includes the following projects:

- [UI Shell](https://github.com/carbon-design-system/carbon/issues/2426)
- [Component enhancements](https://github.com/carbon-design-system/carbon/issues/2416)
- [Component architecture](https://github.com/carbon-design-system/carbon/issues/2376)

## Schedule

- Endgame leader: TBD
- Endgame partner: TBD
- 05/30: Code freeze for projects cutting releases
- 05/31: Endgame done
- 06/03: Expected release date

### Tuesday 05/28

- [x] Initial Release Candidate is cut: `v10.3.0-rc.0`

### Wednesday 05/29

- [x] Second Release Candidate is cut (if any code changes): `v10.3.0-rc.1`

### Thursday 05/30

- Code freeze for release by **5pm CST**
- [ ] Manual and automated verification of Release Candidate packages
- [ ] Collect final lists of changelogs for packages and coordinate with communications

### Friday 05/31

- Last chance for code submissions that include bug fixes, no additional functionality is included
- [ ] Final go/no-go call for release
- [ ] Finalize changelogs for packages

### Monday 06/03

- [ ] Promote latest RC candidate to stable, release `v10.X.0`
- [ ] Twitter announcement
- [ ] Slack announcement
- [ ] Medium announcement
- [ ] Push kit updates (UI shell)
- [ ] Push website updates (UI shell)

**Comment by joshblack** [comment]
# Tuesday 05/28

The following RCs were published:

 - browserslist-config-carbon@10.3.0-rc.0
 - carbon-components@10.3.0-rc.0
 - @carbon/elements@10.3.0-rc.0
 - @carbon/icons-angular@10.3.0-rc.0
 - @carbon/icons-handlebars@10.3.0-rc.0
 - @carbon/icons-react@10.3.0-rc.0
 - @carbon/icons-vue@10.3.0-rc.0
 - @carbon/icons@10.3.0-rc.0
 - carbon-components-react@7.3.0-rc.0
 - @carbon/themes@10.3.0-rc.0

**Comment by joshblack** [comment]
# Wednesday 05/29

The following RCs were published:

 - carbon-components@10.3.0-rc.1
 - @carbon/elements@10.3.0-rc.1
 - @carbon/grid@10.3.0-rc.1
 - @carbon/icons-angular@10.3.0-rc.1
 - @carbon/icons-handlebars@10.3.0-rc.1
 - @carbon/icons-react@10.3.0-rc.1
 - @carbon/icons-vue@10.3.0-rc.1
 - @carbon/icons@10.3.0-rc.1
 - carbon-components-react@7.3.0-rc.1
 - @carbon/themes@10.3.0-rc.1

**Comment by aagonzales** [comment]
Well have some kit pushes and website updates for Monday as well @joshblack

**Comment by joshblack** [comment]
Nice @aagonzales! Would you have a second to add it to the outline? Should be able to edit 👍 If not, I can totally tackle it too!
