### ISSUE TITLE
Allow styling of trigger text of a  <TooltipDefinition>

### ISSUE THREAD

**Issue by gmoehler** [carbon-design-system/carbon#2816]
### Summary

Currently `TooltipDefinition` only allows text as trigger text, but we need the trigger text to be stylable.

### Justification

A text that we want to enhance with a `TooltipDefinition` e.g. might come in different stylings (font styles being the most obvious). It is not enough to offer a fixed style for the trigger text in `TooltipDefinition`. In our case we need to change font properties as well as line-height.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

Either instead of 

```
  /**
   * Specify the tooltip trigger text that is rendered to the UI for the user to
   * interact with in order to display the tooltip.
   */
  children: PropTypes.string.isRequired,
```
we could open up the children for all kind of objects (Variant 1) or we allow a style i.e. `className` attribute on the `TooltipDefinition` to style the text (Variant 2):

#### Variant 1:
```
<TooltipDefinition>
  <div className="mytriggerclass">
    somewording
  </div>
</TooltipDefinition>
```
#### Variant 2:
```
<TooltipDefinition triggerClassName="mytriggerclass">
    somewording
</TooltipDefinition>
```

It might be a deliberate design decision to not allow other elements (e.g. buttons would generate a DOM with buttons included in buttons), therefore, the second option is possibly preferred. 

### Specific timeline issues / requests

It is very hard to find a workaround. I am currently using 
```
button[aria-describedby="idOfTooltip"] {...}
```
Since this is quite ugly i would hope for a fast solution (10.3?)

**Comment by emyarod** [comment]
if I understand correctly, you are looking to add custom styles to text inside `<TooltipDefinition>` right? does selecting `.bx--tooltip--definition .bx--tooltip__trigger` not fit your use case? you can also add your own `className` to `<TooltipDefinition>` already and select that for custom styles

```jsx
<TooltipDefinition className="customClassName">
  somewording
</TooltipDefinition>
```

```css
.customClassName .bx--tooltip__trigger {
  // your styles here
}
```

**Comment by gmoehler** [comment]
That made the trick! thanks very much for pointing it out 👍
