### ISSUE TITLE
[Data table] Implement horizontal scrolling

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2824]
Currently our data table doesn't scroll horizontally, with or without first column fixed. Header and pagination bar are fixed while data rows scroll horizontally. 

## Horizontal scrolling designs

![image](https://user-images.githubusercontent.com/15144993/58278754-55b98780-7d62-11e9-8ece-5f1d4b3d37a5.png)

**Comment by shixiedesign** [comment]
not stale.

**Comment by shixiedesign** [comment]
Not stale

**Comment by jc8futao** [comment]
Have we done this?

**Comment by tw15egan** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/4748
