### ISSUE TITLE
Theming ability for IBM.com

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#2825]
### Summary

As we've discussed in a couple of meetings, we will need the ability to create an overall theme that adjusts attributes across multiple components, which include typography size and spacing.

The digital design team has already composed an audit of the adjustments needed in regards to existing carbon components we are looking to utilize for the upcoming IBM digital design system. We will need development support from the Carbon team to see this through.

### Justification

This is a high priority request as there will be various groups that will be integrating with the new digital design system later this year.

### Desired UX and success metrics

An IDL based digital design system with Carbon at its core. The success would be the adoption rate of the design system for all teams (Drupal, product, commerce, etc)

### "Must have" functionality

Ability to create an overall theme that would encompass the desired dotcom visuals. This would more than likely entail a combination of element level plus component level theming.

### Specific timeline issues / requests

This dovetails with various teams' roadmaps across 2019 into mid 2020.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

The digital design team would be available for support as needed, but hope this would be a more collaborative working relationship.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by oliviaflory** [comment]
Example of digital design theme
- 16px type size
- 20px icon
![button structure-and-measurements](https://user-images.githubusercontent.com/45692622/58282430-b8ffe580-7d73-11e9-9bb5-77620f7b054c.png)


Additional attributes will include:
- height
- width
- padding
- margin

**Comment by jeffchew** [comment]
@mattrosno missed this one, do you still need this ticket open?
