### ISSUE TITLE
SVG icons don't show up in IE 11

### ISSUE THREAD

**Issue by dsuwirya** [carbon-design-system/carbon#2826]
Hello,

I've been using this for my project: https://github.com/carbon-design-system/carbon-elements/tree/master/packages/icons-angular.

But in IE 11, none of the icon is getting displayed. When inspected, the `<path>` is not getting rendered.

Thanks.

**Comment by dakahn** [comment]
Hi! Could you provide a reduced test case where we can reproduce? Thanks!

**Comment by dsuwirya** [comment]
Yes, I believe this issue is related: https://github.com/IBM/carbon-components-angular/issues/567 and they have a storybook showing the problem here: https://angular.carbondesignsystem.com/?path=/story/code-snippet--basic

**Comment by dsuwirya** [comment]
I have a blocker defect raised on my product due to this issue. Is it possible to prioritize this fix and provide ETA? Or if someone can help to give me pointers how to workaround, troubleshoot and fix this? Thanks.

**Comment by dakahn** [comment]
@carbon-design-system/developers can anyone assist with an IE11 workaround?

**Comment by joshblack** [comment]
cc @cal-smith 

@dsuwirya the icons-angular package is not a core offering, it's a community-supported project by the Watson Customer Engagement team 👍

**Comment by cal-smith** [comment]
I guess I'll consolidate on this issue ... missed the ping here, my bad!

**Comment by cal-smith** [comment]
from: https://github.com/carbon-design-system/carbon/issues/2942#issuecomment-500091795
> Seems like the actual SVG content isn't rendering. My guess is these lines are at fault: https://github.com/carbon-design-system/carbon/blob/14fdd5c64b3250c43ecef455b7fbb3527bf795a2/packages/icons-angular/src/templates.js#L63-L65
> 
> On further research it appears that IE11 doesn't support `innerHTML` on SVG nodes. Because of course it doesn't.

**Comment by cal-smith** [comment]
from: https://github.com/carbon-design-system/carbon/issues/2942#issuecomment-500092142

> Based on the work done in [innerSVG](https://code.google.com/archive/p/innersvg/), it seems like some messing around with [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) will sort it out.

**Comment by dsuwirya** [comment]
@asudoh, @cal-smith, Thanks much for the fix. Which release version of `@carbon/icons-angular` should I pull which will have this fix included ? Thanks.

**Comment by asudoh** [comment]
@dsuwirya We have monthly-ish release process. Given we just released `v10.3` some days ago we may do a release to contain critical fix for `v10.3`. Stay tuned.

**Comment by dsuwirya** [comment]
@cal-smith, I pulled the @carbon/icons-angular v.10.3.1 and now icons are broken even on Chrome ( shows the same in IE11 ). Works fine up till v.10.3.0.

**Before:**
![image](https://user-images.githubusercontent.com/5710527/59444410-773aeb80-8dc3-11e9-923e-fcbe2c0e2095.png)

![image](https://user-images.githubusercontent.com/5710527/59444535-abaea780-8dc3-11e9-862c-b3ac15402458.png)

![image](https://user-images.githubusercontent.com/5710527/59444577-bcf7b400-8dc3-11e9-8218-32fa7dcec86f.png)


**After:**
![image](https://user-images.githubusercontent.com/5710527/59444449-89b52500-8dc3-11e9-818c-d1fc9bf21e14.png)

![image](https://user-images.githubusercontent.com/5710527/59444557-b36e4c00-8dc3-11e9-9997-b78625ed076d.png)

![image](https://user-images.githubusercontent.com/5710527/59444598-c8e37600-8dc3-11e9-9e50-c234b8ea9faa.png)
