### ISSUE TITLE
Radio buttons in overflow menu incorrectly aligned in Firefox

### ISSUE THREAD

**Issue by rileyrellis** [carbon-design-system/carbon#283]
Adding radio buttons to an overflow menu in Firefox causes the buttons to be aligned horizontally instead of vertically.  This seems to happen both when the buttons are dynamically added or hard coded into the HTML file.  Adding a br tag after each element, as well as forcing a new display style doesn't fix the issue.  The radio buttons are aligned correctly in Chrome.

![image](https://user-images.githubusercontent.com/31012087/29282072-0c041732-80e7-11e7-9633-3bb53b80a960.png)

**Comment by hellobrian** [comment]
I'm seeing this too when viewing [our website on Firefox](http://carbondesignsystem.com/components/data-table/code)..

**Comment by tay-aitken** [comment]
Just checked the component on our site in Firefox and it seems to be working fine. Closing.
<img width="1193" alt="screen shot 2017-10-30 at 11 50 30 am" src="https://user-images.githubusercontent.com/29312997/32183899-8ff8c976-bd68-11e7-8b7a-395471233019.png">
