### ISSUE TITLE
Toolbar search

### ISSUE THREAD

**Issue by youda97** [carbon-design-system/carbon#2831]
### Summary

To have a stand-alone toolbar search component in carbon v10. (outside of data-table)

### Justification

There are issues open in [carbon-components-angular](https://github.com/IBM/carbon-components-angular/issues/535), so we were wondering if we should still support it.

### Current UX

Trying to use carbon v10 on our current toolbar search looks like this:

<img width="271" alt="Screen Shot 2019-05-23 at 4 58 57 PM" src="https://user-images.githubusercontent.com/25139161/58286143-18fa8a00-7d7c-11e9-8849-90331525ed09.png">

**Comment by asudoh** [comment]
@carbon-design-system/design Wondering if http://react.carbondesignsystem.com/?selectedKind=Toolbar (still) is valid `v10` design, given http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20toolbar has different set of tool bar icons. Any thoughts? Thanks!

**Comment by youda97** [comment]
@asudoh @carbon-design-system/design any update on this?

**Comment by shixiedesign** [comment]
Hi! Sorry for the delayed response. A stand alone search toolbar currently exists in v10: https://www.carbondesignsystem.com/components/search/code
![image](https://user-images.githubusercontent.com/15144993/62076459-544a8680-b20d-11e9-9662-f3d13d797654.png)

**Comment by youda97** [comment]
Hey @shixiedesign, by toolbar search I meant the one that was used in the toolbar in v9. See image below:
![Screen Shot 2019-07-31 at 11 25 52 AM](https://user-images.githubusercontent.com/25139161/62225305-2e94bd00-b386-11e9-9479-ba6335dc16ed.png)
Here is the link: https://v9.carbondesignsystem.com/components/data-table/code

**Comment by laurenmrice** [comment]
not stale

**Comment by aagonzales** [comment]
@youda97 Looks like this exist already, as part of our new data table tool bar. Are you looking for as a stand alone option (not within a toolbar)?
http://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar
