### ISSUE TITLE
[Data table, sketch kit] Add the expand all data table symbol

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2832]
We just merged the option for users to expand all rows for Expandable data table https://github.com/carbon-design-system/carbon/pull/2688 

This issue is to update sketch kit to include a data table symbol with Expand all option. Visually this is just an additional chevron in the header row. 

- [x] Create a variation of a data table with "Expand All" chevron in header row

![image](https://user-images.githubusercontent.com/15144993/58287561-ee5a0280-7d76-11e9-8886-7b44727284fe.png)

**Comment by laurenmrice** [comment]
in kits !🎉
