### ISSUE TITLE
w3c Web Components Library

### ISSUE THREAD

**Issue by anthumchris** [carbon-design-system/carbon#2833]
I'd like to open a discussion for creating a Web Components (W3C) library for Carbon.  Has this been discussed before?  What are everyone's thoughts?

A Web Components library would be a great addition to (or foundation of) the current Vue, React, and Angular libraries that Carbon provides.  Web Components would also provide framework-agnostic projects with the same level of UI component reusability while providing better guarantees of visual/behavioral consistency when implemented into projects using other libraries or frameworks (Shadow DOM encapsulation prevents collisions with other CSS/JS).

Web Components is now a W3C browser standard that offers native component-driven development in all browsers. It's also a future-proof foundation for integration with current or future frameworks.

For those new to Web Components, here are some great intros:
- https://www.webcomponents.org/introduction
- https://developer.mozilla.org/en-US/docs/Web/Web_Components
- https://hacks.mozilla.org/2018/11/the-power-of-web-components/

**Comment by asudoh** [comment]
Hi @AnthumChris 👋 great to hear that you are interested in this area! We recently started [discussing this area](https://github.com/carbon-design-system/issue-tracking/issues/121) and started experimenting stuffs at https://github.com/carbon-design-system/carbon-custom-elements. Feedback/contributions will be highly appreciated!

**Comment by asudoh** [comment]
Let's continue the discussion at https://github.com/carbon-design-system/issue-tracking/issues/121. Thanks again @AnthumChris for your interest!
