### ISSUE TITLE
Add min/max support for `Number Input` 

### ISSUE THREAD

**Issue by gian1200** [carbon-design-system/carbon#2843]
### Summary

Add min/max limits support for `Number Input` component on Carbon Vanilla code

### Justification

A user shouldn't be able to set very low or high values in some cases, only certain accepted values within a range or specific criteria.

### Desired UX and success metrics

Default html5 code should be enough to avoid entering numbers less than 0 or more than 100.
`<input id="number-input0" type="number" min="0" max="100" value="1">`
https://www.carbondesignsystem.com/components/number-input/code

### "Must have" functionality

Use default min/max attributes and behaviour from input tag.
`<input id="number-input0" type="number" min="0" max="100" value="1">`

### Specific timeline issues / requests

Nice to have date Aug 1st, 2019

### Available extra resources

What resources do you have to assist this effort?

**Comment by asudoh** [comment]
Hi @gian1200 thank you for reporting! One thing I wanted to let you know is that the vanilla number input code is as simple as hooking event listener to up/down buttons to increase/decrease the number: https://github.com/carbon-design-system/carbon/blob/v10.2.0/src/components/number-input/number-input.js - Feel free to create your own.
