### ISSUE TITLE
Explicitly make `border-radius: 0` on buttons

### ISSUE THREAD

**Issue by mven** [carbon-design-system/carbon#285]
Not sure if it's a bug on Chromium side, but it looks like they're applying a `border-radius: 4px` to ALL buttons in their baked-in browser stylesheet and since Carbon isn't resetting `border-radius`, it's inheriting this property. If you're not familiar with Canary, it's the testing grounds for what's to eventually come to the Chrome browser, so this might present a design defect if not explicitly set.

I dig the rounded corners (maybe 2px would be better), but I'm not sure if this is something the team would consider to apply to the whole system.

Left: Chrome 60.0.3112.101
Right: Canary 62.0.3118.0

![screen shot 2017-08-17 at 11 58 38 am](https://user-images.githubusercontent.com/940113/29424173-4f569e42-8344-11e7-9eb7-a3bea2277fc1.png)

**Comment by hellobrian** [comment]
Thanks for the heads up! Let me try this out in a branch and a PR

**Comment by hellobrian** [comment]
Okay, so we actually do set the `border-radius` to `0`. 
First it's set in a [mixin](https://github.com/carbon-design-system/carbon-components/blob/e4edb0c0dffe40dddd32ce34070da7655f8f3792/src/components/button/_mixins.scss#L15) that's used in all buttons and the mixin is used in the [`.bx--btn` class selector](https://github.com/carbon-design-system/carbon-components/blob/e4edb0c0dffe40dddd32ce34070da7655f8f3792/src/components/button/_button.scss#L31-L33) so as long as the `bx--btn` class is on the HTML, the border-radius will always be set to `0` by default.

The only way I can see this changing is either through simple CSS overrides of `border-radius` or someone resets the value of the SCSS variable `$button-border-radius`

**Comment by mven** [comment]
Interesting -- thanks for confirming.

Here's the link in case you wanted to test it on Canary: https://console.bluemix.net/catalog/infrastructure/bare_metal?env_id=ibm:yp:eu-de&taxonomyNavigation=apps

**Comment by hellobrian** [comment]
Yeah, this is super weird...do you know which version of the react components this page is using? Or what version of `carbon-components` is being used? @mven

**Comment by mven** [comment]
I think they're using the latest of v6. Slacking you the links now..
