### ISSUE TITLE
Adding Eyeglass support

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#286]
It was removed, but the components [used to have eyeglass support](https://github.com/carbon-design-system/carbon-components/blob/067a4ad57d896a3579e14d2aa47e2a23a1059a41/package.json#L137) to allow easy importing of the sass files. [What is Eyeglass?](https://github.com/sass-eyeglass/eyeglass/)

Could eyeglass support please be added back in to Carbon? This will allow inclusion as a dependency in sass without the need to create a relative link to the specific file. With eyeglass a user would just need to use this in their sass vendor file:

`@import 'carbon-components';`

thank you!

**Comment by hellobrian** [comment]
I think this was removed accidentally when we migrated from GitHub Enterprise to Public, I can add this back in.

**Comment by hellobrian** [comment]
Here's the PR: https://github.com/carbon-design-system/carbon-components/pull/293
@scottnath, do you mind taking a look at the PR and see if this change works for you? I don't have too much experience with eyeglass setup.

**Comment by scottnath** [comment]
reviewed. looks great!
