### ISSUE TITLE
React DataTable column header padding/alignment is off when sorting is enabled

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#2860]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

DataTable column header padding is off when sort feature is enabled

> Is this issue related to a specific component?

yes, DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected column headers to align with column cells

> What browser are you working in?

Chrome 74 Win10, Firefox 67 Win10

> What version of the Carbon Design System are you using?

carbon-components 10.2.0
carbon-components-react 7.2.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM System Z Hardware Management Console. Yes, ship date not announced

## Steps to reproduce the issue

1. Create a DataTable, with sort enabled

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox

## Additional information

https://codesandbox.io/s/zk15lzln6m

**Comment by lovemecomputer** [comment]
thanks! just to verify, is this issue specifically about the extra padding/space beneath the hover state of sort header columns?
<img width="319" alt="Screen Shot 2019-07-07 at 8 27 32 PM" src="https://user-images.githubusercontent.com/3846271/60777028-baa02580-a0f5-11e9-8592-4b58952b3924.png">
assuming yes and starting on it, but just wanted to verify that i'm capturing it all  :)

**Comment by lovemecomputer** [comment]
under local testing, it looks like this alignment issue has been resolved for our next release, tho i haven't yet been able to track down when/which PR that happened in. will look into this more, but will close this if issue if this issue is not still present when next release launches

**Comment by justindm234** [comment]
Sorry for the late reply. The issue was that header text did not left-align with cell text:

![image](https://user-images.githubusercontent.com/15637876/61536002-9c91c980-aa01-11e9-85b7-fed4614b3266.png)

![image](https://user-images.githubusercontent.com/15637876/61536037-b501e400-aa01-11e9-8a40-40935cc0dd58.png)

**Comment by justindm234** [comment]
The problem appears to still exist with carbon-components@10.4.1 and carbon-components-react@7.4.1: https://codesandbox.io/s/datatable-5imlu

**Comment by lovemecomputer** [comment]
oh! @justindm234 thank you for putting together that codesandbox link to illustrate the issue.

i may be able to look into this later in the week, but perhaps @asudoh / @emyarod know more about the context/cause of this issue?

**Comment by asudoh** [comment]
Hi 👋 the `<Table>` needs `isSortable` prop.

**Comment by justindm234** [comment]
🤦‍♂ Thanks, @asudoh
