### ISSUE TITLE
[Grid]: Can't override gutter size in Sass build

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2866]
Let's say you want your Carbon grid to have a 16px gutter instead of the 32px default. After all Sass has imported, you want to

```scss
.my-16gutter-grid {
  @include carbon--grid(
    $carbon--grid-breakpoints,
    carbon--rem(16px),
    $carbon--grid-gutter--condensed
  );
}
```

to apply the non-default grid via a namespace class, `my-16gutter-grid` in this example.

https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss#L78

The `carbon--make-grid-columns` mixin passes in gutter size. That mixin calls the `carbon--make-col-ready` mixin three times, but the `$gutter` param is never passed through to `carbon--make-col-ready` like it's supposed to.

That means the custom gutter that I passed in (`1rem` in this example) never gets used in the lowest-level mixins and the default gets used instead.

**Comment by tw15egan** [comment]
@mattrosno is this still an issue?
