### ISSUE TITLE
Custom link element styling bug inside HeaderMenuItem

### ISSUE THREAD

**Issue by dkuku** [carbon-design-system/carbon#2869]
I'm using hookrouter which uses an anchor tag as link - the problem is that HeaderMenuItem wraps children in a span and my link has default html blue/purple styling instead of the nice white 
I'm using it like that:
```
   <HeaderMenuItem>
     <A href={props.link}>
       {props.title}
     </A>
   </HeaderMenuItem>

```
![image](https://user-images.githubusercontent.com/904179/58512768-cbc05300-8195-11e9-8d78-613273409261.png)
And that's the generated html
```
<li>
    <a class="bx--header__menu-item" role="menuitem" tabindex="0">
        <span class="bx--text-truncate--end">
            <a href="/users">
                Users
            </a>
        </span>
    </a>
</li>
```
In semanticUI I could pass as prop the component, something like `<HeaderMenuItem href="#" as="A">` How can this be solved ?

**Comment by emyarod** [comment]
would the [`element` prop](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L23-L27) fit your use case here?

```jsx
<HeaderMenuItem element={A} href={props.link}>
  {props.title}
</HeaderMenuItem>
```
```

**Comment by emyarod** [comment]
would the [`element` prop](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L23-L27) fit your use case here?

```jsx
<HeaderMenuItem element={A} href={props.link}>
  {props.title}
</HeaderMenuItem>
```

**Comment by dkuku** [comment]
@emyarod Thats exactly what I was looking for. Closing.

**Comment by ilievZlatko** [comment]
I have issues with typescript, when I pass element prop ``element={NavLink}`` and I got the following error:

<img width="831" alt="Screenshot 2020-03-20 at 11 15 39" src="https://user-images.githubusercontent.com/18635490/77160356-100f3d80-6a9f-11ea-8fc5-162d42ee24e3.png">
