### ISSUE TITLE
Default DatePicker date selection event didn't get caught by onClick and wrong default date when minDate was specified

### ISSUE THREAD

**Issue by codeYuyuan** [carbon-design-system/carbon#2874]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When user open the calendar first time, but click somewhere else, the date would be set to current by default. However, the onChange function didn't catch this event.
Also, if minDate is specified, the default date will be minDate instead of the current Date.

> Is this issue related to a specific component?
DatePicker

> What did you expect to happen? What happened instead? What would you like to
> see changed?

onChange function caught the event, so user's corresponding handling function can be called.

> What browser are you working in?
Chrome, 74

> What version of the Carbon Design System are you using?

v9

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Voice agent with Watson. Hope this could be fixed asap.

## Steps to reproduce the issue

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox

## Additional information

- Screenshots or code
- Notes
1. Open the calendar:
![image](https://user-images.githubusercontent.com/26753671/58569199-a79b5b00-8203-11e9-8ac5-16f40e7e9e23.png)
2. click somewhere else:
![image](https://user-images.githubusercontent.com/26753671/58569233-b550e080-8203-11e9-8c05-15260ff4ecb6.png)
onChange function, which is used to grab the selected date, didn't get called.

Code Sandbox:https://codesandbox.io/s/k9lkzr6nmo

**Comment by asudoh** [comment]
Hi 👋 it appears that there is no actual "change" date happening just by click-outside. And thus I see there is no need to fire `onChange` by click-outside. Let us know if you feel otherwise and please add more detailed reason if so!

**Comment by codeYuyuan** [comment]
@asudoh 
Hi Akira, I agree! By click outside, user didn't expect any date got picked. But right now if you click outside, the date will be selected as current date,(if minDate was specified, it will show min date) which is confusing. Is there any way to disable it? Thus if user click outside, the input filed will remain what it is. 
![image](https://user-images.githubusercontent.com/26753671/58597297-485e3a80-8245-11e9-9917-21f3ad2c25ed.png)

**Comment by asudoh** [comment]
OK are you talking about empty input field filled with current date? If so, we can make a change to let you pass along `onClose` to Flatpickr so you can capture the event of "input field filled with current date".

**Comment by codeYuyuan** [comment]
@asudoh 
It would be nice disable the feature which autofills the calendar with current date when user didn't choose a date.
But having an onClose function also works for me!
Thanks!
