### ISSUE TITLE
Multiselect pattern with selected options shown

### ISSUE THREAD

**Issue by Ashley-Johnson28** [carbon-design-system/carbon#2878]
**Summary:**
 We need a component that allows our users to select multiple options from a dropdown search and show what they have selected.

**Justification:**
 Our users must feel confident that they know the exact selections they’ve made and be able to edit/delete those items with ease. Selecting very technical data can be difficult and requires a second confirmation by showing the user what they’ve selected.

**Desired UX and success metrics:**
 In the prototype below you can see the desired behavior of the components in a small version as well as a large.

v10 example: https://ibm.invisionapp.com/share/WQNYXVC2H45

**“Must have” functionality:**
Show selected options
Need to select multiple options at once

**Specific timeline requests:**
 Would like to use this in our next release in September.

**Resources:**
 Contributing developer: (currently working on the react build)
@Alexander-Melo - Alexander.Melo@ibm.com

Contributing designers:
@rtonev  - rtonev@ibm.com
@Ashley-Johnson28 - Ashley.Johnson@ibm.com

**Comment by asudoh** [comment]
Hi 👋 thank you for writing this up! Is it close to filterable variant of http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=default? You can go to KNOBS tab at the bottom and check off "filterable" knob to see that.

**Comment by Ashley-Johnson28** [comment]
@asudoh Yes this is close. It is a filterable dropdown. But the difference is they need to see what they have selected. We would like to add a component that uses this pattern but allows the user to view all they selected.

**Comment by emyarod** [comment]
seems related https://github.com/carbon-design-system/carbon/issues/2422 https://github.com/carbon-design-system/carbon/issues/2571 https://github.com/carbon-design-system/carbon/issues/2640

**Comment by Ashley-Johnson28** [comment]
@emyarod I definitely think these examples show similar features but none solve our problem. We do feel strongly that a variety of teams could benefit from our example. Let me know what you think!

**Comment by asudoh** [comment]
@Ashley-Johnson28 Great that you came up with a component that you think would be beneficial for multiple teams! Looking forward to seeing the prototype. One question from dev perspective - Would it be a trivial addition/modification to our `<MultiSelect>`? Another question, from design perspective this time - Is there a quick screenshot that shows the selection stuffs?

**Comment by Ashley-Johnson28** [comment]
@asudoh The prototype is actually attached in the ticket! Please use the link below to click through and see our design....

https://ibm.invisionapp.com/share/WQNYXVC2H45#/screens

**Comment by Ashley-Johnson28** [comment]
@asudoh I labeled it 'v10 example' in the ticket but should have been more clear and labeled 'prototype'

**Comment by asudoh** [comment]
@Ashley-Johnson28 Thank you for the link. The link seems to show an integration pattern of multi-select and data table, correct me if I'm wrong here.

**Comment by creckling** [comment]
In Watson IoT we have the same request and feedback about the current component. It is more typical to show the selection in the chip.
![image](https://user-images.githubusercontent.com/50208035/59120651-f5127900-8923-11e9-99fc-6b446fbd5a53.png)

**Comment by Ashley-Johnson28** [comment]
Thanks @creckling - Yes that is definitely the  preferred pattern. The issue is our content could be text strings of technical data the user needs to see. So the real estate won't allow it. That's why our solution needs the second part to the component.

**Comment by Ashley-Johnson28** [comment]
@asudoh Yes for the 'large' option we tried to use established designs to limit the redesign effort and to stay consistent. The 'small' pattern uses a variation of the multi select but allows for your selection to be shown to the right of the dropdown.

**Comment by designertyler** [comment]
@creckling would it be acceptable for your use case if the selected tags appeared outside the dropdown or did it require the selection to be inside? It makes sense outside to allow for longer tag names and to not limit text input.

@Ashley-Johnson28 are you proposing to have the selected tags only appear to the right or could it be configured above or below? 

![image](https://user-images.githubusercontent.com/19270502/59126982-0c556480-892c-11e9-81aa-109e2b7cf29c.png)

**Comment by Ashley-Johnson28** [comment]
@designertyler My issue with putting it below is that the dropdown will then 'hide' the information (we played around with this option) and putting in above can change the height of the page if it is in a form for example. With the selected state to the side the content that might be below will stay in place. If you see our 'large' example we do put the table below. This option if for the extremely detailed data you may be selecting.

**Comment by creckling** [comment]
It is taking up horizontal space if the selection is next to the dropdown. Let me see if I can find some real examples in our products.

**Comment by creckling** [comment]
not a real product yet but a mockup where the field width is pretty wide and can handle more text.
![image](https://user-images.githubusercontent.com/50208035/59301938-c6b4d680-8c60-11e9-8aaa-77fe80688d17.png)

**Comment by Ashley-Johnson28** [comment]
@creckling What happens when you fill the dropdown space in this example? The reason I liked the secondary input space was because it could get longer (in height)  if needed but when you change the height on a dropdown it gets a little wonky.

**Comment by creckling** [comment]
In this case, it is okay for the field to expand vertically (like a to: field in the inbox).

**Comment by naythanwilliams** [comment]
Hi. I'm working on a similar issue for Songtrust - where we're using Carbon as our base component library. I'd love to contribute to a solution to this issue, since I'm currently trying to rewrite some of the MultiSelect logic to support showing deletable tags outside of the select dropdown.

**Comment by creckling** [comment]
I wonder if your use case works with this type of list building pattern. You have a list on left and the selected items on the right.
![image](https://user-images.githubusercontent.com/50208035/59783289-d39f7e80-928d-11e9-90ad-20f34d2f13e4.png)

**Comment by naythanwilliams** [comment]
I'll run it by our designers and see if this is something we could work with.

**Comment by Yuanwwwwww** [comment]
To follow up on Naythaniel's comment. 
Is there any technical reason for the smaller version to have max 10 selected items? 
If we could take out the container for the selected items, and display the selected results in either chip and list item form as below, would that be feasible? 

![image](https://user-images.githubusercontent.com/46761294/59790558-300a9a00-929e-11e9-9e53-2dca9fffb6b0.png)

**Comment by iozzyi** [comment]
I am also looking for this feature - named items once selected and limited options. I know other libraries do it but it would be nice to have a single component library.

**Comment by keehun** [comment]
I would like to +1 on this component.

**Comment by DenisCor** [comment]
2023 and they still didnt add this to MultiSelect...
