### ISSUE TITLE
Separate metadata file for icon categories

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2890]
### Summary

Right now categories are set per icon resource (and variants) in `metadata.yml`; it's time consuming, doesn't really support mass changes, and errors are likely and hard to catch (other than after kit generation).

Issue is proposing a second .yml file that enumerates all of the categories, and per category, enumerates all of the icons (and variants?) in that category.

**Comment by chrisconnors-ibm** [comment]
related to #2672, #2438

**Comment by joshblack** [comment]
Closed by #2934
