### ISSUE TITLE
[Bug]: Filterable for Multiselect is not found by React

### ISSUE THREAD

**Issue by cknabe** [carbon-design-system/carbon#29]
## Detailed description
When using MultiSelect.Filterable in React I am seeing an error in the console:
```
372:1 Uncaught Error: Module build failed: Error: C:/Users/IBM_ADMIN/git/Gen1.VSI/src/client/containers/Network/index.js: [babel-plugin-transform-carbon-imports] encountered the following imports that are not currently exported by `carbon-components-react`: [FilterableMultiSelect]
    at PluginPass.ImportDeclaration (C:\Users\IBM_ADMIN\git\Gen1.VSI\node_modules\babel-plugin-transform-carbon-imports\index.js:53:17)
```
My implementation is using:
```
import {
  Icon,
  Accordion,
  AccordionItem,
  MultiSelect,
} from 'carbon-components-react';

...

    return (
      <MultiSelect.Filterable
...
```

> Is this issue related to a specific component?

MultiSelect.Filterable

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

    "carbon-components": "8.16.8",
    "carbon-components-react": "5.31.0",
    "carbon-icons": "^6.1.0",

I did update to the newest and still saw the issue.

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components-react #961](https://github.com/carbon-design-system/carbon-components-react/issues/961) via [**ZenHub**](https://www.zenhub.com/)
