### ISSUE TITLE
[Inline Loading] renders "error message" and "in field" symbols  

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#2901]
Does  **InlineLoading** component render following two Carbon Design Tool Kit symbols:

**loading / inline loading / in field**
**loading / inline loading / error message**

Don't see samples for them.

**Comment by asudoh** [comment]
@carbon-design-system/design Does this issue indicate that our inline loading component does not implement some stuffs in the latest design?

**Comment by laurenmrice** [comment]
These seem to be in the design kit but not in code as apart of our v10 release we may have backlogged it. I can make an issue for an enhancement for inline loading component.

**Comment by asudoh** [comment]
Yes having one will be great - Thanks @laurenmrice!

**Comment by aagonzales** [comment]
Issue moved to [carbon-design-system/carbon-design-kit #207](https://github.com/carbon-design-system/carbon-design-kit/issues/207) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tw15egan** [comment]
@laurenmrice just wondering if there is anything that needs to be done here? I don't see any linked issues. We have https://react.carbondesignsystem.com/?path=/story/inlineloading--ux-example in the storybook.

**Comment by laurenmrice** [comment]
I think we are good to close. We have the loading error message now in code. 👍🏻 For the loading field input, people can add the inline loading component into the input on their end.
