### ISSUE TITLE
Dropdown (inline) - incorrect vertical alignment 

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon#2909]
In Design Kit these symbols below have text and icon not aligned vertically.

- gray 10 / dropdown / 01 default / 03 inline / closed / 01 enabled
- gray 100 / dropdown / 01 default / 03 inline / closed / 01 focus
- white / dropdown / 01 default / 03 inline / closed / 01 focus
- I don't have gray 90 theme to check

**Comment by laurenmrice** [comment]
Fixed! Available in next kit update.

Add to v10.5 release notes
