### ISSUE TITLE
Call JS function on elements

### ISSUE THREAD

**Issue by leondroidgeeks** [carbon-design-system/carbon#291]
Could someone please explain how to call a JS function on an element?
For example, I tried to change the Progress Indicator using JS but I wasn't able to do this by using example in the [documentation](http://carbondesignsystem.com/components/progress-indicator/code)

`const instance = ProgressIndicator.init();`
Gets me an undefined, that's why
`instance.setCurrent(0)`
doesn't work.
I already tried initializing ProgressIndicator at the beginning with
`CarbonComponents.Tooltip.init();`

**Comment by chrisdhanaraj** [comment]
Hey there! While we really recommend you use a module bundler to save some of the verbosity, you can call specific elements like this. CodePen has some load time oddities, so I've taken the most verbose route (disabled the auto-init, initialized all ProgressIndicators on the page, grabbed the element, got the instance of ProgressIndicator for that element. 

The trick is that ProgressIndicator.init() initializes all ProgressIndicators on the page, but doesn't actually return them to you (that might be an improvement we can do though). Check out this codepen for a how to

https://codepen.io/team/carbon/pen/EvLzdZ

**Comment by asudoh** [comment]
As @chrisdhanaraj’s codepen shows `CarbonComponents.Tooltip.components.get(element)` is the way to get the instance. We also have “create instance and return the instance” API, which is, `CarbonComponents.Tooltip.create(element)`. OTOH, `.init()` is a higher-level API to create multiple instances (under document or the given element) and thus does *not* return an instance.

**Comment by chrisdhanaraj** [comment]
Yeah good point - although (tangentially), I think it would be easier for users to only have to use one API (especially since you can of an element into `init` anyways)

**Comment by asudoh** [comment]
@chrisdhanaraj Good point that simplicity is great thing. `.init(element)` works differently from `.create(element)`, where `.init(element)` works with any elements matching `[data-progress-indicator]` vs. `.create(element)` requires the `element` matches `[data-progress-indicator]`. Are you thinking that `.init(element)` should return the instance when the `element` matches `[data-progress-indicator]`?

**Comment by leondroidgeeks** [comment]
Thank you both for your answers! I am building an Angular 2 application. As you know there are a index.html and multiple components. @chrisdhanaraj's codepen only works when I put the code into the index.html in a script tag. When I want to use the code in the component where I want to use the Progress Indicator, I need to `import { ProgressIndicator } from 'carbon-components';` and change the code and put it into ngInit()

```
const element = document.querySelector('[data-progress]');
const instance = ProgressIndicator.components.get(element);
instance.setCurrent(3);
```
Can you tell how to use the components properly in an Angular 2 Application? The whole init() stuff is a bit confusing.

Btw, I would really like to use the module bundler, but as I described in #282 the elements won't work, so I need to import the whole js file and activate each item in index.html:

```
<script>
  CarbonComponents.settings.disableAutoInit = true;
  CarbonComponents.InteriorLeftNav.init();
  CarbonComponents.Tooltip.init();
  CarbonComponents.Modal.init();
  CarbonComponents.ProgressIndicator.init();
  CarbonComponents.OverflowMenu.init();
  CarbonComponents.FileUploader.init();
</script>
```

**Comment by asudoh** [comment]
Given @leondroidgeeks wants to use Carbon component in Angular component - The best way to do this is making your component a "wrapping component" described in the corresponding section in http://www.carbondesignsystem.com/getting-started/developers.

The approach works with `CarbonComponents.Loading` global ref replaced with `Loading` from `import Loading from 'carbon-components/es/components/loading/loading'`, too. Same thing applies to progress indicator even.

**Comment by hellobrian** [comment]
Closing for now but if you still have additional questions re: JS init, then we can re-open, @leondroidgeeks

**Comment by leondroidgeeks** [comment]
Sorry for my delayed response, I was on vacation. The wrapping component was a good idea! But again I don't get it how I should use this component..
Accordingly to [this article](https://medium.com/@dee_bloo/custom-element-inter-op-with-angular-2-ed75f013a9ba) I created a wrapping component and included it into my ng2 project.
```
import { ProgressIndicator } from 'carbon-components';

class BXProgressIndicator extends HTMLElement {
  progress;
  connectedCallback() {
    this.progress = ProgressIndicator.create(this.querySelector('[data-progress]'));
  }
  disconnectedCallback() {
    this.progress.release();
  }
}

customElements.define('[data-progress]', BXProgressIndicator);
```
But now I don't know how to call a the function `.setCurrent(3)` on. I tried it with @ViewChild and `document.querySelector('[data-progress]').setCurrent(3)` but both times nothing happens.

**Comment by asudoh** [comment]
@leondroidgeeks Quicker answer - One thing that’s missing in `BXProgressIndicator` class in your example is a method delegating `.setCurrent()` from the custom element to Carbon component instance:

```javascript
setCurrent(n) {
  this.progress.setCurrent(n);
}
```

More deep dive - While Custom Elements - Angular2+ interop is an interesting topic, I thought you wanted to create Angular2+ component instead.

Though I have never used Angular2+ (and thus below code is *never* tested), several Angular documentations give me an impression that a wrapping component for Angular2+ should look something like:

```javascript
@Component({
  selector: 'bx-progress',
  template: `<ul #elem data-progress data-progress-current class="bx--progress">
      <li class="bx--progress-step bx--progress-step--complete">
        <svg width="24px" height="24px" viewBox="0 0 24 24">
          <circle cx="12" cy="12" r="12"></circle>
          <polygon points="10.3 13.6 7.7 11 6.3 12.4 10.3 16.4 17.8 9 16.4 7.6"></polygon>
        </svg>
        <p class="bx--progress-label">Label 1</p>
        <span class="bx--progress-line"></span>
      </li>
      <li class="bx--progress-step bx--progress-step--current">
        <svg>
          <circle cx="12" cy="12" r="12"></circle>
          <circle cx="12" cy="12" r="6"></circle>
        </svg>
        <p class="bx--progress-label">Label 2</p>
        <span class="bx--progress-line"></span>
      </li>
      <li class="bx--progress-step bx--progress-step--incomplete">
        <svg>
          <circle cx="12" cy="12" r="12"></circle>
        </svg>
        <p class="bx--progress-label">Label 3</p>
        <span class="bx--progress-line"></span>
      </li>
      <li class="bx--progress-step bx--progress-step--incomplete">
        <svg>
          <circle cx="12" cy="12" r="12"></circle>
        </svg>
        <p class="bx--progress-label">Label 4</p>
        <span class="bx--progress-line"></span>
      </li>
    </ul>`,
})
class BXProgress {
  @ViewChild('elem') elem: ElementRef;

  ngOnInit() {
    this.progress = ProgressIndicator.create(this.elem);
  }

  ngOnDestroy() {
    this.progress.release();
  }

  setCurrent(n) {
    this.progress.setCurrent(n);
  }
}
```

**Comment by leondroidgeeks** [comment]
Thanks @asudoh that makes sense. I will test again
