### ISSUE TITLE
Initialize Overflow Menu

### ISSUE THREAD

**Issue by leondroidgeeks** [carbon-design-system/carbon#292]
How do you initialize the Overflow Menu? It's the same behavior I explained in #282.

**Comment by asudoh** [comment]
Hi @leondroidgeeks every component but check box has the same `create()` API as well as higher-level `init()` API. You can refer to them in https://github.com/carbon-design-system/carbon-components/blob/master/src/globals/js/mixins/create-component.js and https://github.com/carbon-design-system/carbon-components/blob/master/src/globals/js/mixins/init-component-by-search.js.
