### ISSUE TITLE
IE11:  DataTable batch actions render over column headers

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#2920]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

DataTable BatchActions are vertically misaligned in IE11 - they render on top of or under the column header

## Steps to reproduce the issue

The problem is seen in the "with batch actions" storybook: 
http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20batch%20actions&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

## Additional information

![image](https://user-images.githubusercontent.com/15637876/58897062-70c2ba80-86c5-11e9-9ec2-acfde3156efb.png)

**Comment by ritablchiu** [comment]
This is reproducible in Edge as well, tested with Microsoft Edge 44.17763.1.0.

**Comment by asudoh** [comment]
Refs #4638

**Comment by joshblack** [comment]
I believe this is addressed in latest carbon, let me know if this isn't the case!
