### ISSUE TITLE
stale[bot] is too aggressive, fails to detect activity

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2921]
14 days is too short a window to determine 'stale'

if an issue had a PR opened that linked to an issue _yesterday_, that issue should not be perceived as 'stale'

**Comment by dakahn** [comment]
@carbon-design-system/developers didn't we up the stale-o-clock to like 30 days?

**Comment by jnm2377** [comment]
Yes we did

**Comment by jnm2377** [comment]
https://ibm-studios.slack.com/archives/GCPF37GEB/p1559666727021400
<img width="938" alt="Screen Shot 2019-06-04 at 3 37 30 PM" src="https://user-images.githubusercontent.com/32556167/58911996-b770de80-86de-11e9-998b-7820e39b79c0.png">

**Comment by chrisconnors-ibm** [comment]
I love `stale-o-clock` and would like that on a shirt
