### ISSUE TITLE
Modal discussion follow up

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#2922]
Conclusion from slack thread:
https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1559587807036800

**Investigate/look-into:**
- [ ] Modals with multiple actions +2 
   - with equal weight buttons (ie find and replace)   
   - Progress modal variant (cancel, previous, next)
   - (cancel, previous, next) will by defacto become  (cancel, previous, create/add system/finish etc)
- [x] Single button “acknowledgment” modal
   - Is passive modal still relevant with “acknowledgment” variant?
- [ ] Modal consistency, in concern with introducing new button pattern behavior. (?)
- [ ] Modal buttons dependent on modal size/width (%)
   - should there be a max modal size?
   - should there be a separate full page (or larger) version?
- [ ] Smaller max-width option (define set modal sizes, not a %?)

**Related to buttons:**
- [ ] Fixed button size with overflow content.
   - Buttons with a lot of content (internationalization) / no-truncation that have a fixed/constrained width. 
- [ ] Button pairing behavior, more than 2 (outside of modal context)
- [x] Update button style tab structure content.

**Comment by marceltrautmann** [comment]
Adding some screen shots from the discussions related to some of the above (mostly progress modal);
![image](https://user-images.githubusercontent.com/51379566/58900422-247b7880-86cd-11e9-84ea-37afe23fdff4.png)

![image](https://user-images.githubusercontent.com/51379566/58900465-39f0a280-86cd-11e9-8879-5884b46cef64.png)

It's worth mentioning, that with the progress modal variant, form elements are often par for the course, So longer modals are typical (sometimes wider)

**Comment by cragun47** [comment]
Added detail request for Single acknowledgement modal:  https://github.com/carbon-design-system/carbon/issues/2924

<img width="480" alt="Single Modal Button" src="https://user-images.githubusercontent.com/4914849/58900555-99928200-86bc-11e9-9a02-0b290ed8509d.png">

Video of use case where we would benefit from a single button "Continue" at the end of progress modal.
[Progress.mov.zip](https://github.com/carbon-design-system/carbon/files/3253721/Progress.mov.zip)

**Comment by elizabethsjudd** [comment]
Here's WH's requirements around modal behaviors: [requirements.txt](https://github.com/carbon-design-system/carbon/files/3291021/requirements.txt)

**Comment by aagonzales** [comment]
Additional investigate smaller modal max-width, for "dialogs" or "message boxes"
https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1562701030157400

**Comment by marceltrautmann** [comment]
keepalive-bot

**Comment by aagonzales** [comment]
![image](https://user-images.githubusercontent.com/11670886/62878960-bfa55580-bcef-11e9-9117-d54bc2c0b9bd.png)

**Comment by amortiz** [comment]
Is there any discussion of providing a more traditional modal footer where buttons do not take the whole width of the dialog? It is quite different than the Carbon 9 modal or any other modals that i've seen from several applications / websites, wondering if there has been any user testing or reasoning behind going this way rather than the common approach.

**Comment by marceltrautmann** [comment]
keepAlive[bot]

this one has garnered a lot of debate.  potentially a good candidate to prioritize?

**Comment by aagonzales** [comment]
Its top of our component enhancement list, the team just hasn't prioritized that project. Hopefully we get to it soon. Design's trying to get enhancements prioritized.

**Comment by creckling** [comment]
also see #3509

**Comment by aagonzales** [comment]
Related: Nag Modal
https://github.com/carbon-design-system/carbon/issues/1478

**Comment by marceltrautmann** [comment]
keepAlive[bot]

**Comment by aagonzales** [comment]
Closing as modal have been updated in v10.8 and resolves many of this topic. Any items not covered my the modal updates can be opened as individual issues. 

https://www.carbondesignsystem.com/components/modal/usage
