### ISSUE TITLE
issues for TooltipIcon component

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#2925]
1.  direction name is not consistent  between document and Sketch
The document in Carbon Components React web page:
[http://react.carbondesignsystem.com/?selectedKind=TooltipIcon&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs](url)

If Tooltip direction (direction) is "bottom", and filter label is rendered under the icon.   
In Sketch, the symbol name with "bottom" word is  **tooltip / icon tooltip / group / arrow bottom / left** , but the filter is above the icon.
please see the attached file.

2. TooltipIcon component does not render correctly if the direction property is set to "left": when moving the mouse over on the icon, filter text does not show up. Please see the second attachment for the rendered React code

![tooltipIcon](https://user-images.githubusercontent.com/14806866/58886038-db193200-86a8-11e9-8a68-785c328d131c.png)
![TooltipIcon left direction](https://user-images.githubusercontent.com/14806866/58890364-19feb600-86b0-11e9-9508-92cf0d793c20.png)

**Comment by asudoh** [comment]
@carbon-design-system/design  I'm guessing that "arrow bottom" in the sketch means arrow placed under the tooltip, instead of tooltip placed under the trigger button. Is it correct?

@zhenwan Cannot reproduce the 2nd issue. Great to have the details. BTW great to have one problem per issue. Thanks!

**Comment by laurenmrice** [comment]
@asudoh yes arrow bottom refers to the arrow of the tooltip being placed at the bottom of the tooltip.

**Comment by abbeyhrt** [comment]
@zhenwan with the current version of Carbon, are you able to reproduce the 2nd issue? I'm not able to in v7.9 of carbon-components-react.

**Comment by zhenwan** [comment]
I am good now. Please close this issue.
