### ISSUE TITLE
[Notification] Usage guidance & images fixs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2926]
### Update to [webpage](https://www.carbondesignsystem.com/components/notification/usage) needed following component enhancemen: https://github.com/carbon-design-system/carbon/issues/2354

1. All these images need to be replaced to feature High contrast styling

2. Should inline notification ever be at the bottom of the form? I think I usually see inline notifications at the top. 
![image](https://user-images.githubusercontent.com/15144993/58914210-8ba42780-86e3-11e9-8f16-9a4fc90aa247.png)

3. Toast notification missing drop shadow
![image](https://user-images.githubusercontent.com/15144993/58914261-aeced700-86e3-11e9-838f-66d6b24516c5.png)

4. Add documentation of Low contrast styling, which is our current colored background style.

**Comment by asudoh** [comment]
Leaving a comment to see if there still is a team's interest in this.

**Comment by shixiedesign** [comment]
not stale

**Comment by shixiedesign** [comment]
not stale
