### ISSUE TITLE
[Notification] Update low contrast styling

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2927]
## Design spec done. Ready for dev: 

Please note: low contrast notification on light themes have an outline. The color of the outline is `$support-01 – $support-04` at `30% opacity`. On dark themes they do not have outlines.

## Tokens

| | Light themes | Dark themes | 
| --- | --- | --- | 
| outline | `$support` at 0.3 opacity | none | 
| background | `$field-01` | `$field-01` |

![Low contrast notifications](https://user-images.githubusercontent.com/15144993/62250134-c065ef80-b3b1-11e9-8471-7fe360d78450.png)

![image](https://user-images.githubusercontent.com/15144993/60303931-6c24a700-98fd-11e9-9651-9b1034af1199.png)

**Comment by shixiedesign** [comment]
## Ready for dev: 

![image](https://user-images.githubusercontent.com/15144993/60303859-29fb6580-98fd-11e9-8367-f02722703fce.png)

**Comment by shixiedesign** [comment]
not stale

**Comment by asudoh** [comment]
@shixiedesign Just wanted to double-check if we have any remaining work items in this space - Thanks!

**Comment by shixiedesign** [comment]
Hi @asudoh there are still several design updates outstanding with low contrast. At a glance, these are what I noticed: 

### Inline low contrast notifications
The Inline low contrast in vanilla is actually showing Toast, so I cannot review inline low contrast notifications: 

![image](https://user-images.githubusercontent.com/15144993/64186933-49e76200-ce35-11e9-9e1a-b1227ee595b3.png)

### Toast low contrast notifications
Clearly broken here, and I realize the issue might be on tokens. If any developers have bandwidth, we can have a quick chat about how this can be made.

![image](https://user-images.githubusercontent.com/15144993/64187028-713e2f00-ce35-11e9-95fe-67e65c76d1b9.png)

**Comment by asudoh** [comment]
I believe it's fixed by #3899. @shixiedesign Please don't hesitate to speak up otherwise - Thanks!
