### ISSUE TITLE
[ui-shell] Sidenav icons don't move with parent container on mobile

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#2928]
You can see here, when a sidenavmenu is opened, the icons of sibling sidenavmenus stay put on ios safari

![shell-sidenav](https://user-images.githubusercontent.com/4078018/58915861-95c82500-86e7-11e9-9742-8b62ec2afa39.jpeg)

Steps:
1. go to [the sidenav storybook](http://react.carbondesignsystem.com/?selectedKind=%5BExperimental%5D%20UI%20Shell&selectedStory=SideNav%20w%2F%20Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) on mobile.
2. Expand a Sidenav Menu Item
3. Notice how the icons don't move with their parent containers

**Comment by vpicone** [comment]
This also happens on https://www.carbondesignsystem.com and the gatsby theme as well.

**Comment by tw15egan** [comment]
Interesting, it seems the vanilla version doesn't have this problem... Regardless, removing the expansion animation, for now, should resolve this issue

**Comment by vpicone** [comment]
@tw15egan do you mean the shelf expanding animation or the svg icon/carat rotation? I think @jnm2377 might have done some digging into the cause as well.

**Comment by tw15egan** [comment]
Shelf expanding animation, that's what seems to be causing the issue based on @jnm2377's research and is superfluous. The Chevron rotating is part of the core UX and I wouldn't want that removed

**Comment by vpicone** [comment]
@tw15egan Nice, it seems like the shelf animation would need to be dymanic based on the distance covered anyway. Long lists have visible animation while short ones appear to have none. Maybe something worth considering if we ever add it back.

**Comment by tw15egan** [comment]
Yeah, would need to dynamically set the `max-height` on expansion to whatever the height of the drawer is. Currently, always going to `1500px`

**Comment by jnm2377** [comment]
Yeah, definitely agree that we can remove the animation for now, until we have time to figure out how to dynamically set the max-height.

**Comment by lee-chase** [comment]
@here This appears to be caused by the use of style="will-change: transform" on the SVG icon. Presumably a bug with Safari, not that I can find a reference to it anywhere.

We appear to use "will-transform" liberally throughout our components, which is possibly very naughty. See here https://developer.mozilla.org/en-US/docs/Web/CSS/will-change where it states 

![image](https://user-images.githubusercontent.com/15086604/60009357-a1b36100-966d-11e9-8e89-e3979fab112a.png)

That page goes even further to warn against the liberal use of will-change as it allocates resources and can slow a page down!!!

**Comment by lee-chase** [comment]
NOTE: This also happens on Safari desktop, on Mojave.

**Comment by tw15egan** [comment]
Interesting, I always thought `will-change` would help performance when used liberally. Good find! Perhaps we should create an issue to remove `will-change` throughout and use the animation FPS meter to track performance gains/losses
