### ISSUE TITLE
[Tooltip] Check if implementation supports usage in product walkthroughs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2933]
Interactive tooltip is designed for product walkthroughs or on-boarding tours. Current implementation assumes a more limited use case. We should investigate & do if any changes to implementation is required to support the product walkthrough use case. 

See example of tooltip used in product walkthroughs: https://www.reallygoodux.io/blog/ghost-cms-editor-user-onboarding

> Do you think the build/implementation of interactive tooltip doesn't allow it being used on product walkthroughs or on-boarding tours? If so, we should open an issue to address it – sorry because I realize this info wasn't in the original spec. Walkthroughs & on-boarding are the main use cases for this component, at least today. If you've seen it in other situations, let us know!

Yes it'll be a good idea to track it an issues. In this way we can create live examples and can ensure interactive tooltip works in those scenarios. The current tooltip code almost assumes limited scenarios wrt trigger link/buttons, so good to gather the use cases.

_Originally posted by @asudoh in https://github.com/carbon-design-system/carbon-website/pull/1688#issuecomment-499037709_

**Comment by asudoh** [comment]
Thanks @shixiedesign for writing this up! Technically the current constraint of interactive tooltip is what triggers tooltip to be open, currently it's limited to an icon or link-ish text. Above link seems to have a regular button. Great to have list of other possibilities.

**Comment by shixiedesign** [comment]
Adding **Enhancement** label and we can circle back next in July!

**Comment by shixiedesign** [comment]
From discussion, looks like our tooltip does support this function. Closing.
