### ISSUE TITLE
[Modal] review behaviors and guidance

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2935]
Need to review and fix a behaviors of modals overall across the 3 variants we have: 

> transactional probably shouldn't have the "click anywhere to close" function

_Originally posted by @aagonzales in https://github.com/carbon-design-system/carbon-website/pull/1696_

**Comment by elizabethsjudd** [comment]
@shixiedesign @aagonzales There is a coordination between Carbon, IBMa, and WH right now is working on how some of the behaviors and guidance is documented.  WH is actually currently working on the Modal component right now.  I'd really like to get more people involved in this effort, so if you want, I can set up some time with you to go over what we have.

**Comment by elizabethsjudd** [comment]
Specifically we have a variant that is similar to what @aagonzales is proposing in the main issue comment quote called `Required Action` that we are hoping to contribute.  I have a meeting with our designer today to see where we are at on the design side for this variant specifically.

**Comment by shixiedesign** [comment]
@elizabethsjudd 100% support the idea! We are happy to review any content you've got and we can align / combine. Feel free to set a time up when you are ready to share. We've got a couple components (eg. notification) that need guidance review, but no resources to tackle them this month.

**Comment by aagonzales** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/2922

**Comment by shixiedesign** [comment]
Pass a prop to prevent modal from closing when clicking outside modal.

**Comment by shixiedesign** [comment]
not stale

**Comment by elizabethsjudd** [comment]
not stale

**Comment by elizabethsjudd** [comment]
not stale
