### ISSUE TITLE
Support custom loading SVG titles

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2954]
Currently the loading component takes a `description` prop but it is only used for `aria-label`. We should allow custom loading SVG titles and match it to the `description` prop

**Comment by joshblack** [comment]
If we have `aria-label` being defined, do we need `title`?

**Comment by emyarod** [comment]
we were hard coding the `title` in the loading components, so this issue was about making it configurable

if we want to remove `title` that would be a slightly different discussion I think, but for now, since we are already passing in a description for the loading components, we should either align the two attribute values or remove the `title` entirely across the library

`aria-label` makes the content visible to screen readers while `title` doesn't impact them, but `title` has the benefit of a visual tooltip on hover
