### ISSUE TITLE
[File uploader] Update default file uploader error state style

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2962]
We've reached a consensus! Let's stick to below styling for error state for both drag & drop and the default file uploader. 

![image](https://user-images.githubusercontent.com/15144993/59378990-2ff92000-8d1b-11e9-8dc5-30a8124ab143.png)

![image](https://user-images.githubusercontent.com/15144993/59378949-1a83f600-8d1b-11e9-9bb3-77a347ced1bc.png)

_Originally posted by @shixiedesign in https://github.com/carbon-design-system/carbon/pull/2848#issuecomment-499683994_

**Comment by emyarod** [comment]
@shixiedesign how should the component look when the user uploads multiple files and more than 1 is invalid?

**Comment by shixiedesign** [comment]
@emyarod  Below shows 2 errors: The gray error text is optional.

![image](https://user-images.githubusercontent.com/15144993/59376494-d6dabd80-8d15-11e9-9890-a8d99fce6052.png)

The rationale for picking the left is - the left design uses better type alignment so overall it is easier to read and stays as a nice block. Right side version obvious is more consistent with input field & dropdown, but we thought in the case of a "file list" (which already is different because it doesn't have 1px underline for accessibility), it's not necessary to treat it the same.

**Comment by emyarod** [comment]
ok got it. since this is for both the existing file uploader and the drag and drop file uploader, it seems like there is some conflict/overlap with the audit feedback in #2088

**Comment by shixiedesign** [comment]
@emyarod thanks for pointing that out! I just discussed it with Lauren and she will reach out to you soon with our spec changes. I'll close this issue so all the spec changes can be tracked in https://github.com/carbon-design-system/carbon/issues/2088
