### ISSUE TITLE
Data Table: Column header - resizing issues

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon#2969]
Across all the themes (White seems to be less affected than the other ones)
 **Selectable** and **Expandable** Column header for the Data Table symbol isn't resizing correctly - checkbox and chevron icon aren't pinned and constrained in size. 

Please check all the sizes (24, 32, 48, 64).

Example:
![image](https://user-images.githubusercontent.com/12408951/59111171-c8b92580-8940-11e9-9d05-0d1c7836b4bb.png)

**Comment by dakahn** [comment]
Hello! Thanks for submitting. Can you please fill out the template provided for a bug report 🙏

**Comment by laurenmrice** [comment]
@mariuszmickiewicz I fixed all of the table headers in every theme in the kits. Let me know if that works with the most recent update you get.
