### ISSUE TITLE
[UI Shell] June Iteration Plan

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2972]
# June Iteration Plan

This plan captures our work on the UI Shell project for **June**. This work will contain design and development updates to the existing UI Shell, taking it from experimental to stable.

## Endgame

• *July 8th, 2019*: Code freeze for the endgame
• *July 12th, 2019*: Endgame done 

The endgame details for this iteration are tracked below:

## Issues to be handled as part of June release cycle
💻 - dev
🎨 - design

#### Priority Goals
0. 🎨 UI Shell Patterns guidance #3001 

1. 🎨 Shell Sketch Template with the header/etc. symbols in place per artboard/breakpoint
and a tutorial to publish using it before the 10.4 timeframe. #2337 

2.  💻🎨Expand the Left panel component to accommodate the other local navigation types we supported in experimental: Icons+Menu, Rail among them. 
     - header + nav links (go into sidenav in responsive view) #2994
     - header + nav links + sidenav #2995 
     - header + rails #2996 
     - Design specs for UI Shell rail #3003 

3. 💻extend the specificity of the Right Panel Component for switcher, notifications, and possibly user panel types. App switcher and notification design specs. https://github.com/carbon-design-system/carbon/issues/2997

4. Expand and refine the Documentation for the pattern as well as the individual components iteratively based on direct and solicited feedback, as well as observed use during the _patterns classes in July. 

#### Stretch Goals
1. 💻 Theming #2998

2. We will explore various footer types (for apps, not web properties) assuming we find a need for them among our constituents. 

3. 💻 Skeleton States #2999 

#### Deferred Items (stuff moved from primary/stretch to another iteration)
1. 💻 Vanilla Shell - #2659 #2658

**Comment by elymatos** [comment]
I have noticed that the code examples are gone. Is there some plan to get some code examples to UI shell? I think they are very important as a start point.
Thanks.

**Comment by jnm2377** [comment]
Hi @elymatos if you're referring to the code examples we had on our website, we just removed them temporarily while updating our website to `carbon-components: 10.3.0` and `carbon-components-react: 7.3.0` since the stable variations depend on those versions and we didn't want to display broken components. We will be adding them back in once this PR has been merged: https://github.com/carbon-design-system/carbon-website/pull/1716 In the meantime you can view them in our React [Storybook](http://react.carbondesignsystem.com/?selectedKind=UI%20Shell&selectedStory=Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel).

One thing to note, the components that we'll be adding on our website will be the React version of the UI Shell only. We've been focusing on the getting the React components to stable before moving on to Vanilla, so you won't see the code for those components the way you usually see for Vanilla JS components, unless you go to the Storybook.

**Comment by elymatos** [comment]
Ok! Thanks for clarify!

**Comment by aagonzales** [comment]
This looks good to me! Just a side note about the footer, I think Jeoff’s expectations for this is much like the right panel. Just defining the general size / geometry / placement of where a product footer would go and behave. We don’t have to create content for it at the moment.
