### ISSUE TITLE
[Header, SideNav] - Development - UX for rails pattern

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2996]
- [ ]  Develop UX for header with rails
    - sidenav collapses into visible icons
    - expands on hover, but on `HeaderMenuButton` click expands indefinitely
- [ ] Update component readme if needed (will also help update readme on website)
- [ ] Add any necessary new documentation to website (style page for new classes, component status page, other)
- [ ] Add story for `SideNav Rails w/ Header`

cc: @designertyler  for design specs/review

**Comment by designertyler** [comment]
Design specs are available here https://github.com/carbon-design-system/carbon/issues/3003#issuecomment-504172976
