### ISSUE TITLE
Layer Types Seem Mis-labeled

### ISSUE THREAD

**Issue by lconnolly** [carbon-design-system/carbon#3]
## Overview

In the Carbon Design System one or two of the "Layer Types" samples are mis-labeled. The card labeled "12 Sticky Nav" is actually getting the drop shadow styles of "24 Pop Out" (and vice-versa)... which is a bit confusing when trying to convey the "depth" of the various cards in order.

Should be a quick fix. I hope this is helpful.
<img width="1204" alt="screen shot 2017-03-30 at 5 09 22 pm" src="https://cloud.githubusercontent.com/assets/1553705/24526340/d14b51be-156b-11e7-924c-d7b9414b7cdc.png">

**Comment by hellobrian** [comment]
Thanks for catching this bug for us, someone from our team will have a fix on the website soon!

**Comment by lconnolly** [comment]
Happy to help!

**Comment by marijohannessen** [comment]
This fix is merged into master, will be updated on the website by EOD.

**Comment by marijohannessen** [comment]
The fix is now live.
