### ISSUE TITLE
Provide the icons as an 'icon-font'

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#30]
It would be very convenient to have an 'icon-font' made out of the carbon icons.

**Comment by hellobrian** [comment]
Hey @gmosx, when we started writing code for Carbon, we made a conscious decision to align around SVG icons. Most of the reasons for using SVGs can be summed up here in this [CSS-Tricks](https://css-tricks.com/icon-fonts-vs-svg/) article sums it up pretty well. 

We have two options: 
- Use Inline SVG via [carbon-icons](https://github.com/carbon-design-system/carbon-icons): located in [dist](https://github.com/carbon-design-system/carbon-icons/tree/master/dist) 
- Use carbon-icons.svg, which is a sprite containing refs to all the SVGs.
