### ISSUE TITLE
misleading aria-label for search icon 

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#3000]
## Environment
all
> Operating system
all
> Browser
all

## Detailed description

This issue is about : 
[DataTable with toolbar component](http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20toolbar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)

 The Search Icon in the search field is not an Interactive element, role and aria-label attributes are not required. It will mislead the Screen reader users.

> What version of the Carbon Design System are you using?
7.1.0
> What did you expect to happen?
remove aria-label 
![Screen Shot 2019-06-10 at 12 30 40 PM](https://user-images.githubusercontent.com/14806866/59214295-7401ee80-8b7c-11e9-9522-61e0da6f1ecb.png)

**Comment by lovemecomputer** [comment]
thanks for reporting this! it looks like the unexpected behavior is at least partially inherited from the Search component, so we're looking into the best fix!

**Comment by aledavila** [comment]
Fixed
