### ISSUE TITLE
Design specs for UI Shell rail

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#3003]
Design specs for the left panel when it collapses to the rail.
Design specs for left panel with icons. 
Update website with new usage and style images.

Example image for reference
![image](https://user-images.githubusercontent.com/19270502/59216852-356f3280-8b82-11e9-8548-cf5e12f48222.png)

**Comment by shinytoyrobots** [comment]
This needs a confirmed design (for a current iteration) in order to allow #2996 to progress.

**Comment by designertyler** [comment]
### Sketch File
https://ibm.box.com/s/pucnelli7pamtw48iouzbqkvqk6n4mgc

## Left Rail Specs

![Rail_Pieces](https://user-images.githubusercontent.com/19270502/59879677-dde67900-9370-11e9-9f5b-2bb420fb7a48.png)


## Left Rail Behavior
![Rail_Behavior](https://user-images.githubusercontent.com/19270502/59879694-e6d74a80-9370-11e9-9cf1-ec189b2e8672.png)
