### ISSUE TITLE
[Data table] Need mobile experience

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3006]
### Data table mobile experience design

Current enhancement proposals: 
- implement horizontal scrolling https://github.com/carbon-design-system/carbon/issues/2824
- add a mobile variant that transposes columns to expanded rows and allow only vertical scrolling (originally proposed by Andrew Nelson in https://github.com/carbon-design-system/carbon/pull/2992) 
![image](https://user-images.githubusercontent.com/15144993/59223801-75d6ac80-8b92-11e9-882c-3316e947a4d5.png)

I think we can include both.

**Comment by werdnanoslen** [comment]
Not stale

**Comment by werdnanoslen** [comment]
Not stale, see https://github.com/carbon-design-system/carbon/pull/2992 for updates

**Comment by werdnanoslen** [comment]
not stale
