### ISSUE TITLE
Missing type package import (font-family)

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#3007]
We have a top-level `_typography.scss` Sass partial that provides unit conversion functions, imports the type package, and offers a mixin to use type tokens.

When building an application, I expect that I can import Carbon's typography, and then use it like:

```scss
@import 'carbon-components/scss/globals/scss/typography.scss';

.foo {
  @include carbon--font-weight('semibold');
}
```

This worked in 10.2.0. It no longer works in 10.3.0. This was found by numerous people doing the Carbon tutorial.

---

`_typography.scss` imports:

```scss
@import '../../globals/scss/vendor/@carbon/elements/scss/type/styles';
```

`_styles.scss` used to import the type package `_font-family.scss`. It no longer does. I can't find why this was removed.

The diff: https://github.com/carbon-design-system/carbon/commit/16a4ba63b103f53eaef506674a8d9ca8952ed3ea#diff-6895f06c6166f58586cebe3d2b7278e2L9

In `_typography.scss`, should we be importing a different type package entrypoint, like `index.scss` or `styles.scss`?

(I don't think this was a noticeable breaking change in 10.3.0 because `_css--reset.scss` imports the type package `_reset.scss` which imports the type package `_font-family.scss`.)

**Comment by asudoh** [comment]
@joshblack Any thoughts?

**Comment by mattrosno** [comment]
Easiest fix for the tutorial is to lock in 10.2.0 so 10.3.0 doesn't get installed. Or, I could instruct people to:

```scss
@import 'carbon-components/scss/globals/scss/vendor/@carbon/type/scss/font-family.scss';
@import 'carbon-components/scss/globals/scss/typography.scss';

.foo {
  @include carbon--font-weight('semibold');
}
```

Either way, it's a workaround for the time being.

**Comment by joshblack** [comment]
I bet we could just import the type entrypoint without having to worry, but we can also include `font-family` directly in `_typography.scss` too 👍

**Comment by joshblack** [comment]
Should be closed by https://github.com/carbon-design-system/carbon/pull/4795 ! Let us know if not 🙂
