### ISSUE TITLE
Read only text input

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#3018]
ref: https://github.com/carbon-design-system/carbon/issues/2177 by @shixiedesign 

A read only variant of Text input is suggested here: https://github.com/carbon-design-system/carbon-contribution/issues/13#issue-421692303

> The “Disabled” option is not viable, as the label and entered data is not accessible. Proposal is to simply remove the line at the base of the "Filled" version of the component, so that it closely matches with the Disabled component, but passes accessibility.

## Overview of component (updated May 13)
- Read-only variant will be keeping underline and dropping the background of the field. We need the underline for low-vision users to recognize this as a text field. Also loosing the underline makes the element a button-style, which would be confusing. 
- Not moving the text position after all. Keeping text 16px away from left of border helps with preserving the form structure. 
- Regular text cursor and allows text selecting
- Add `not-editable` icon, icon in PR https://github.com/carbon-design-system/carbon/pull/2710
- Optional tooltip when hovering `not-editable` icon, to provide reason for the field being read-only 
- Overflow text in the field will show in tooltip on hover
- Should be considered a state, possible `readonly` attribute
- Follow the standard readonly attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-readonly

## Design spec (updated May 13)

![image](https://user-images.githubusercontent.com/15144993/57665202-9970fc00-75c0-11e9-9a3f-b628d7b168a9.png)

## In context explorations: 
![image](https://user-images.githubusercontent.com/15144993/57496411-6fee6280-7298-11e9-82cc-71f2b96e0255.png)
![image](https://user-images.githubusercontent.com/15144993/57496415-75e44380-7298-11e9-8397-3a79fb5e9a75.png)

## Finalized design spec. Ready for dev 🤖 updated May 23

![Read-only 1](https://user-images.githubusercontent.com/15144993/58283670-77b90700-7d6e-11e9-8207-fab575af77fb.png)

### Light variant spec
Only difference from default is changing field background to `$field-01` so it is the same as background color. 

![Read-only 2](https://user-images.githubusercontent.com/15144993/58283648-6a038180-7d6e-11e9-8a04-f77b83f590c4.png)

**Comment by kaylarakower** [comment]
@shixiedesign @emyarod Another proposal to consider (I created this issue prior to seeing @shixiedesign 's, so just some food for thought). The design was created for a slightly use case as none of the fields would be editable.

https://github.com/carbon-design-system/carbon-contribution/issues/17

**Comment by kaylarakower** [comment]
@shixiedesign do you have an example of how this would look in "Review and order" and then once purchased?

As I'm working through #3125 I'm wondering if they need to be separate patterns

**Comment by shixiedesign** [comment]
not stale

**Comment by kaylarakower** [comment]
Not stale @shixiedesign

**Comment by asudoh** [comment]
Reopening this to restart some discussion - @aagonzales You had a question why tooltip is needed for read-only text input. I think @shixiedesign put this for overflow text, presumably it's difficult (or impossible) for user to go to non-editable text (input) box and move the cursor to see the whole content.

That said, if we have an alternate design to go without tooltip for read-only text input, I think it'll be a good idea. What do you think?

**Comment by aagonzales** [comment]
@asudoh where's the other issue this was mentioned in? (I couldn't find it again)

**Comment by asudoh** [comment]
@aagonzales Sorry I may not have been clear enough - It's #4015. The latest spec for read-only text input requests for a tooltip (presumably for overflow text). Definition tooltip is the closest, but definition tooltip (technically) cannot be activated by focus on `<input>`. #4015 is for supporting such use case in definition tooltip.

**Comment by dianasanborn** [comment]
Hi! Just wanted to follow up and see if there are any updates or changes to the design spec for this, regarding the last few comments about the tooltip. 

I know a handful of teams on our end need this, so I want to make sure I'm pointing them to the right place for design guidance unless there have been any changes. 

Is there an update on the implementation of this as well, or should our own teams start building this out?

**Comment by emyarod** [comment]
the design should be set already, but currently the implementation has been put on hold until further notice. when this is reprioritized I can update my previous PRs like https://github.com/carbon-design-system/carbon/pull/3054

**Comment by bertrandmartel** [comment]
Is there a readonly option for textinput at this time ? I think It's quite important for such a library

**Comment by godivareisen** [comment]
@emyarod @shixiedesign **Does anybody have updates on the status of this effort?** The DataStage team on Cloud Pak for Data has a requirement for showing read-only fields in our connector properties panel.

![read-only fields in connector properties](https://user-images.githubusercontent.com/13739755/104765697-279a6f80-571e-11eb-873c-9b861d2f88b5.png)

We consume the **Elyra common canvas**, so this would ideally be something that other teams using the canvas can leverage as well.
