### ISSUE TITLE
Change in Modal behavior - Links embedded in Tooltips no longer work.

### ISSUE THREAD

**Issue by JoeAdamski** [carbon-design-system/carbon#3021]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Inside of Modals where we use tool-tips with links - the link fails to open when clicked.

This appears to be a regression starting in 6.114.0 - it worked in 6.113.1.

I suspect that it is related to this commit that introduces a focus-trap.
https://github.com/carbon-design-system/carbon-components-react/commit/b9f5d9e92dd81dce104dea313a7de9989de9910c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to happen?

Expect link to open in new window. Would like to see this fixed in the V6.* branch as we have breaking changes preventing us from upgrading to V7+ at this time.

> see changed?
Started in V6.114.0 - clicking link was ignored.

> What browser are you working in?

Chrome.

> What version of the Carbon Design System are you using?

    "carbon-components": "^9.91.3",
    "carbon-components-react": "6.114.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

VPC UI

## Steps to reproduce the issue

We have this Tooltip inside of a Modal:

```
    const renderTooltip = (
      <div className={styles.publicKeyTooltip}>
        <Tooltip
          showIcon={false}
          triggerText={publicKeyHelperText}
          dataToolTip={'publicKey'}
        >
          <p>
            <Link
              to="/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-ssh-keys#ssh-keys"
              target="_blank"
            >
              Link-text
            </Link>
          </p>
        </Tooltip>
      </div>
    );
```

**Comment by JoeAdamski** [comment]
@asudoh , @dakahn - mentioning to raise awareness.

**Comment by asudoh** [comment]
@JoeAdamski Given you believe focus trap introduction is the culprit, would you want to turn it off? (`focusTrap={false}`)

**Comment by JoeAdamski** [comment]
Thanks Akira. I actually already did that and it's working now.

However, is this a good overall solution? What if others who want this functionality have tool tips with links? Should there be some other solution?

**Comment by asudoh** [comment]
Actually `<Modal>` has had focus-wrap behavior, with or without `focusTrap={true}`. `focusTrap={true}` was introduced so it's a bit more perfect.

**Comment by JoeAdamski** [comment]
@asudoh - I agree its nice to have this option, but should it be disabled by default?

- This would preserve backwards compatibility and behavior
- The current default behavior seems a little unexpected now. Meaning, if someone sees a link in a pop-up is not working - they might not realize that its the fault of focusTrap being enabled for them. Where if they needed a stronger focus control then ( focusTrap  ) being added a as an attribute makes sense.

**Comment by asudoh** [comment]
@JoeAdamski I tend to agree with you - Flipping the switch back causes another breaking change, though...

**Comment by JoeAdamski** [comment]
I think the long standing behavior is more important to not break - as there are unlikely many people taking advantage of the newer functionality yet. Don't you think?

Also, I always prefer boolean attributes to have default value false. Then we never have to say `focusTrap={false}`. We just leave it out for false and add it `focusTrap` to enable it.

Mine is working now though, by using `focusTrap={false}`.

I think my suggestion would make this a little better, but if you think its better the way it is, I'm ok with closing the issue.

And...  I do think the focusTrap is a nice feature to add.... Thanks for that.

**Comment by asudoh** [comment]
Yeah got your point. I'm reluctant with making another change, though given there is a workaround. Thank you @JoeAdamski for sharing your thoughts!

**Comment by JoeAdamski** [comment]
Ok, Akira. 👍
