### ISSUE TITLE
wrong css class is used for ToggleSmall React component

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#3023]
[ToggleSmall.js](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ToggleSmall/ToggleSmall.js) code line 75 uses a class which does not exist. 

<span className={`${prefix}--assistive-text`}>{ariaLabel}</span>

Guess the correct code might be( two '-' between 'assistive' and 'text' :

<span className={`${prefix}--assistive--text`}>{ariaLabel}</span> 

-
<img width="906" alt="ToggleSmall" src="https://user-images.githubusercontent.com/14806866/59308564-eea73880-8c66-11e9-81b6-50d69dab5db9.png">

**Comment by asudoh** [comment]
Would you ensure having https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/globals/scss/_css--helpers.scss#L17 in your style? Thanks!

**Comment by zhenwan** [comment]
I see this problem from your doc web page: 
http://react.carbondesignsystem.com/?selectedKind=ToggleSmall&selectedStory=toggled&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by asudoh** [comment]
Not sure where in your link you are referring to, but opening DOM inspector in your link shows:

![image](https://user-images.githubusercontent.com/1259051/59392937-69319e80-8db4-11e9-8f3b-9f23f29640c2.png)
