### ISSUE TITLE
Progress Bar component

### ISSUE THREAD

**Issue by joshua-vaughn** [carbon-design-system/carbon#3025]
### Summary

I would expect Carbon to have a Progress Bar component. Carbon has a Progress Indicator component to illustrate the steps in a process like a wizard. In contrast, a Progress Bar component is used to illustrate the percent-complete status of a long running process. 

### Justification

The Cloud Pak for Data UX team needs a Progress Bar to illustrate the percent-complete status of an installation process. This seems like a common UI component in several other design systems.

### Desired UX and success metrics

A user can easily see the percent-complete status of a long running process with a colored bar graph and a number.

### "Must have" functionality

A user can easily see the percent-complete status of a long running process with a colored bar graph and a number.

Additional information may appear above or below the progress bar, such as:
- Estimated time remaining (e.g., 2 min remaining)
- Speed of the process (e.g., 206 Mb/s)
- The current step of the process (e.g., Checking CPU on host 9.76.63.174)

### Specific timeline issues / requests

The Cloud Pak for Data UX team is currently designing a new installer for potential release in August 2019. 

### Available extra resources

We have a proposed design for the component in Sketch. A screenshot is attached.

![Progress Bar](https://user-images.githubusercontent.com/51725782/59313874-8c9b0300-8c67-11e9-97a0-d8089da7a190.png)

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if there is an interest in the team. I thought we had some discussions around it, but completely slipped off my mind wrt where.

**Comment by aagonzales** [comment]
There is interest in this. We would need to take the component through a review process.

**Comment by joshua-vaughn** [comment]
Still necessary, it's just on the backburner for now

**Comment by mariuszmickiewicz** [comment]
My team is interested in this component too. Meanwhile we came with a slightly different style.
https://ibm.invisionapp.com/share/GRNZ3Q843A2#/319182290_list

I would be happy to update to the thicker version presented above if this becomes the standard. I think it is worth checking is the text supporting the progress bar should be part of it or not or how to deal with text positioning for different contexts etc. It would be great if the color of the progress bar in the component wasn't locked to one color -  for example we need to differentiate between upload and processing phase.

Thank you,
Mariusz

**Comment by jillbyra** [comment]
I need this type of component currently as well. For now Im using something very similar to the screenshot attached in this issue

**Comment by shixiedesign** [comment]
We can definitely prioritize this as one of the next components to build out. Meanwhile, we are short on resources so if anyone is willing to contribute design & code, we would really appreciate it!

**Comment by joshua-vaughn** [comment]
Still needed, stale bot

**Comment by chrisconnors-ibm** [comment]
KeepAliveBot

**Comment by laurenmrice** [comment]
not stale

**Comment by joshua-vaughn** [comment]
nope

**Comment by sharpcodepro** [comment]
Hi all. Is there any progress on the progress bar component?

**Comment by rlclaar** [comment]
I am also interested in this progress bar component.  I would like to use it in a situation where something is happening in the background, and the user needs to know the status while continuing to work in the foreground.

**Comment by janhassel** [comment]
Since this is quite a common component and I think many teams (including ours) would need it, could this be a candidate to bring over from Cloud PAL and add to the external core library?

**Comment by fangshih** [comment]
Hey, Any progress on this component? I am also interested in this progress bar component. Our product needs to use it for system updates. It usually takes a long time and will happen in the background, so it will be very helpful for them to come back and able to see the progress is moving forward and still working. Thanks!

**Comment by matthewchivers** [comment]
Extremely interested in this component. What's the status please?
[edit] 
I saw it's mentioned in projects. https://github.com/orgs/carbon-design-system/projects/8 
Good to see it being progressed! 
[/edit]

**Comment by tw15egan** [comment]
Just did some research on this, and it seems like there are two native HTML elements that could be used. See here for a working example: https://codesandbox.io/s/stoic-cloud-3t5fz?file=/src/index.js

A) `meter` which is defined by the w3c as 
> The meter element represents a scalar measurement within a known range, or a fractional value; for example disk usage, the relevance of a query result, or the fraction of a voting population to have selected a particular candidate. This is also known as a gauge.
[w3c docs](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element)

or

B) `progress` which is defined by the w3c as 
> The progress element represents the completion progress of a task.
[w3c docs](https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element)

The biggest issue is `meter` is fully unsupported in IE11 (https://caniuse.com/meter)
However, `progress` is fully supported with the caveat that `indeterminate` is not supported in Safari (https://caniuse.com/progress)

There are some styling tweaks that could be made to each of these components to align with the Carbon standard
- [Meter](https://css-tricks.com/html5-meter-element/#styling-the-meter-element)
- [Progress](https://css-tricks.com/html5-progress-element/#styling-progress-bars)

**Comment by janhassel** [comment]
@tw15egan It seems that only Safari on iOS 7 doesn't support the`indeterminate` variant, while Safari on macOS and iOS 8 and higher fully support it. That would make `progress` the better candidate imo, what do you think?

Is there design guidance on this? I could probably find some time to work on the implementation.

**Comment by tw15egan** [comment]
@janhassel I agree 👍🏻 

@carbon-design-system/design do we have any guidance for this?

**Comment by janhassel** [comment]
@tw15egan I started a draft over in #8720

**Comment by aagonzales** [comment]
About the name? No, but we do have a `progress indicator` component so we'd want to make sure this name was distinct enough from that. Maybe `progress bar` is enough.

Other options:
- Progress loader
- Progress loading bar

**Comment by aagonzales** [comment]
FYI there's already a `meter` component in the data viz section as well https://carbondesignsystem.com/data-visualization/simple-charts/#meter

**Comment by wailingwombat** [comment]
My team is interested as well for survey completion.
