### ISSUE TITLE
Overflow menu position is not taking effect

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3026]
I'm new to React and Carbon components.
BTW,
I couldn't find this channel!
#carbon-react for questions about our React components

![image](https://user-images.githubusercontent.com/26740851/59330011-f2839b00-8cf8-11e9-8ac8-c5d43c091845.png)

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I'm trying to use an overflow menu inside a toolbar, and it was located on the top-right corner. But when opening it it doesn't align automaticlly acording to it position and cause a horizintal scroll because it's opened to the right!

I tried changing the direction inside the properties but it didn't help!

> const menuProps = {
  menu: () => ({
    direction: select('Menu direction (direction)', directions, 'top'),
    ariaLabel: text('ARIA label (ariaLabel)', ''),
    iconDescription: text('Icon description (iconDescription)', ''),
    flipped: boolean('Flipped (flipped)', true),
    onClick: action('onClick'),
    onFocus: action('onFocus'),
    onKeyDown: action('onKeyDown'),
    onClose: action('onClose'),
    onOpen: action('onOpen'),
  }),
  menuItem: () => ({
    className: 'some-class',
    disabled: boolean('Disabled (disabled)', false),
    requireTitle: boolean(
      'Use hover over text for menu item (requireTitle)',
      false
    ),
    onClick: action('onClick'),
  }),
};

> class App extends Component {
  render() {
    const regularProps = props.regular();
    return (
      <div className="App">
        <header className="App-header">
          <Toolbar {...toolbarProps} className="Toolbar1">
            ...
            <ToolbarItem >
              <OverflowMenu {...menuProps} renderIcon={ChevronDown}>
                < OverflowMenuItem itemText="Sign out"/>
                < ToolbarDivider />
              </ OverflowMenu>
            </ ToolbarItem>
          </ Toolbar>

## Relevant information

![image](https://user-images.githubusercontent.com/26740851/59329981-e13a8e80-8cf8-11e9-83aa-eccfd3fcae26.png)

Link to my css file:
https://gofile.io/?c=izQdJ7

**Comment by asudoh** [comment]
Hi 👋 have you tried `<OverflowMenu floatingMenu flipped>`?

**Comment by zbeedatm** [comment]
That helped... thanks a lot.
Where can I find a full documentation about each component? To help figure out such issues.

The ReadMe tab is empty for all components, and  general example is not giving so much information.

**Comment by asudoh** [comment]
In react.carbondesignsystem.com, you'll find KNOBS Storybook tab at the bottom. It shows the list of properties that you can change to see how the component behaves with such change in prop. Hope it helps!

**Comment by savalemilind6984** [comment]
How to change direction of overflowmenu component dynamically based on available viewport height?
