### ISSUE TITLE
How to use a Split Panel?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3027]
## What package(s) are you using?

- [ ] `carbon-components`
- [ x] `carbon-components-react`

## Summary
I searched for a split panel in carbon components but I couldn't find any1
However,
I can see that it's in use from your carbon design system site:
http://react.carbondesignsystem.com/

![image](https://user-images.githubusercontent.com/26740851/59330648-b4877680-8cfa-11e9-80c5-a1e0307c30e5.png)

**Comment by asudoh** [comment]
Hi 👋 the splitter UI is from Storybook, instead of our Carbon library.
