### ISSUE TITLE
[DataTable] Add support for column alignments (e.g. align-right)

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#303]
When displaying numerical data we often need 'right-alignment' in columns. 
I don't see any support for this.

Also, it would be great to provide some relates suggestions, usage instructions in the DataTable docs.

**Comment by hellobrian** [comment]
You should be able to do this with CSS, `style` or one of the many CSS-in-JS libraries out there to apply `text-align: right;` to the columns you need to change.
