### ISSUE TITLE
Text is not centred in buttons

### ISSUE THREAD

**Issue by HoltMansfield** [carbon-design-system/carbon#3031]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the carbon-components-react button component I expect the text to be centred.

> Is this issue related to a specific component?

Many components have this issue.  Tabs for example.  

This text is centred as it should be (http://themes.carbondesignsystem.com/)

![image](https://user-images.githubusercontent.com/1058627/59359053-aa19ac80-8cfb-11e9-87d1-a02531e10b4f.png)

This is what your react library looks like on your demo site:

![image](https://user-images.githubusercontent.com/1058627/59359150-d2a1a680-8cfb-11e9-851c-7a477aa1bf08.png)

The button text is not centred.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the carbon-components-react to look like carbon design system.  From what I've seen from carbon the text should be centred.

> What browser are you working in?

Issue verified in Chrome, Safari and Firefox

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.3.0",
    "carbon-components-react": "^7.3.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

I was asked to evaluate the carbon-design-system.  I found several issues in the first hour. I will log them all here.

## Steps to reproduce the issue

1. Step one
run CRA
2. Step two
npm i carbon-components carbon-components-react
3. Step three
drop any button in a template and observe the text alignment

> Please create a reduced test case in CodeSandbox

Here is a CodeSandbox, unfortunately, the latest version of carbon-components-react has an issue that prevents it from rendering.  I have logged this other issue as: https://github.com/carbon-design-system/carbon/issues/3030

https://codesandbox.io/s/carbon-components-react-9ghr5

## Additional information

- Screenshots or code

the repo I tested with: https://github.com/HoltMansfield/carbon-cra-2

The misalignment:

![image](https://user-images.githubusercontent.com/1058627/59359550-89058b80-8cfc-11e9-8da6-ad19f851c782.png)

**Comment by emyarod** [comment]
it looks like the page you are referencing (http://themes.carbondesignsystem.com/) is using an older version of Carbon. the left-aligned text was implemented based on design changes for the current version

you can center your button text with CSS by modifying the padding of the button

**Comment by HoltMansfield** [comment]
@emyarod can you please direct me to a page that demonstrates what these components are meant to look like?

**Comment by emyarod** [comment]
yeah @HoltMansfield https://www.carbondesignsystem.com/ and http://react.carbondesignsystem.com/ hope this helps

**Comment by HoltMansfield** [comment]
@emyarod thank you!

Sorry I hadn't dug deeper into your main site...I see now that is all left aligned...it's so unusual it struck me as a bug

**Comment by danramac** [comment]
Wow I thought this was a bug too, someone designed it like this?
