### ISSUE TITLE
Update DataTableSkeleton component to v10

### ISSUE THREAD

**Issue by dallashudgens** [carbon-design-system/carbon#3032]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

I'm using the DataTableSkeleton component as a loading pattern before the data from my DataTable renders. The difference in styles is creating a lot of jumping and repositioning. 

> Is this issue related to a specific component?

DataTableSkeleton component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see the v10 styles on the skeleton component. It still had v9 which caused the header styles and rows to be a bit different, and it didn't include the table title and description.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This was discovered while working on the Developer Essentials tutorial

## Steps to reproduce the issue

1. Run the 3rd Tutorial step (completed) to see the DataTableSkeleton load in with different styles. 

## Additional information

**Comment by asudoh** [comment]
CC @carbon-design-system/design just in case they have any insights wrt where we are at.

**Comment by aagonzales** [comment]
http://react.carbondesignsystem.com/?path=/story/datatableskeleton--default

Yeah looks like it wasn't updated in the code, entire skeleton table looks like its still in the V9 style. Good catch. This is what it should look like and should be using the new skeleton tokens:

![image](https://user-images.githubusercontent.com/11670886/59524356-46c58100-8e99-11e9-9144-c5554400b52b.png)

@carbon-design-system/developers let me know if you need more specs to update.

**Comment by aagonzales** [comment]
@asudoh actually it looks like none of the Skeleton states in the react story book have been updated to v10

**Comment by asudoh** [comment]
Thanks @aagonzales for your insights - Yes, having specs will be great!

**Comment by aagonzales** [comment]
![xlg-1312px-16 column](https://user-images.githubusercontent.com/11670886/59631040-792ae480-910c-11e9-910c-e3bd4e756474.png)

**Comment by aagonzales** [comment]
React data table skeleton is still doesn't match intended design list above:

**As-is:**
![image](https://user-images.githubusercontent.com/11670886/66221420-8b696800-e694-11e9-8f93-855c6a5d30d9.png)

**To-be:**
![image](https://user-images.githubusercontent.com/11670886/66221437-93c1a300-e694-11e9-8bbc-8687d6a3c00a.png)

**Comment by tw15egan** [comment]
Still has not been updated (http://react.carbondesignsystem.com/?path=/story/datatableskeleton--default)

**Comment by nictownsend** [comment]
Can this be conditional via props? I don't want to have a header or buttons but now I'm forced to, which has broken the loading state UX for my tables...

**Comment by richardpilot** [comment]
We also need this to be optional. This component seems to have regressed in function, as it is missing the headers, which we were providing so shouldn't be a skeleton and also add the top header title which we don't use. We now have to hide it in css or use the old version of this component as our own which is not very future proof.
