### ISSUE TITLE
[Grid] No easy way to create a 2-column grid

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#304]
I want to create a simple 2 column grid, each column should take 50% of the row width.
Tried this:

```
    <div class="bx--grid">
        <div class="bx--row">
            <div class="bx--col-xs-12 bx--col-md-6">
                ..
            </div>
            <div class="bx--col-xs-12 bx--col-md-6">
                ..
            </div>
        </div>
    </div>
```

But this two columns are rendered vertically even on `md` screens.
Second try:

```
    <div class="bx--grid">
        <div class="bx--row">
            <div class="bx--col-xs-12 bx--col-md-5">
                ..
            </div>
            <div class="bx--col-xs-12 bx--col-md-5">
                ..
            </div>
        </div>
    </div>
```

Now, I get the two columns but obviously the don't cover 100% of the row's width.

Is there a way to setup a standard 2-column layout (50% - 50%) using the Carbon Grid styles?

**Comment by chrisdhanaraj** [comment]
Can you try the latest version? This issue should be resolved

**Comment by gmosx** [comment]
Just tried version `0.21.0` the problem is ***not*** fixed, i.e. using `bx--col-md-6` renders the 2 columns in separate rows (not side-by-side) as expected.

**Comment by chrisdhanaraj** [comment]
I just checked in a CodePen - seems to be working fine https://codepen.io/team/carbon/pen/eEXoXO. Looks like you probably don't have our reset included, so `box-sizing: border-box` settings aren't applied, see this on how to add it to your own CSS

https://www.paulirish.com/2012/box-sizing-border-box-ftw/

**Comment by gmosx** [comment]
You are right, I had this in the top of my `.scss` file:

```
$css--reset: true !default;
```

Most probably I copied it from some example (that should be changed)

Thank you!
