### ISSUE TITLE
[Inline loading] Update checkmark icon and loader size

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3040]
**Checkmark icon**

Current:
![Screen Shot 2019-06-12 at 3.02.37 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/d87f4ed0-60b4-47f9-826e-fa247c5ac96e)

New:
-Replace current check with `16/checkmark--filled`. Fill: `interactive-01` and Check: `icon-03`
-8px between icon and text
![Screen Shot 2019-06-12 at 3.02.42 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/1bfdcd46-f5ba-41ca-83e8-1f819c4fe7f8)

**Comment by laurenmrice** [comment]
**Loader**

Current:
![Screen Shot 2019-06-12 at 3 07 31 PM](https://user-images.githubusercontent.com/43969356/59382662-e103b880-8d23-11e9-871c-e67b5a4e1fbc.png)

New:
-16x16px container with a 14x14px loader.
-8px between loader and text
![Screen Shot 2019-06-12 at 3 07 41 PM](https://user-images.githubusercontent.com/43969356/59382665-e5c86c80-8d23-11e9-9ecb-a5f23852f407.png)

**Comment by laurenmrice** [comment]
Changes to match file uploader (Ref PR: #3016 )

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by asudoh** [comment]
@laurenmrice A question; The spinner seems to have approximately 2.56 pixels for its stroke and 6.4 pixels for its radius (based on the center of the stroke). Any guidance wrt how these should change? I'm guessing that we are shrinking (only) the radius, but not fully certain. Any info would be nice. Thanks!

**Comment by laurenmrice** [comment]
Hey @asudoh The current spinner 16px spinner takes up the full 16px x 16px box. Our 16px icons usually have some padding around the icon so that the actual icon is a little smaller than 16px but sits within a 16px bounding box. We want to change the current spinner to have this padding like the other icons. The stroke should stay the same, but it should just get smaller to accommodate the padding.

Ex: We want the one on the right with padding
![Screen Shot 2019-10-17 at 12 47 57 PM](https://user-images.githubusercontent.com/43969356/67034161-c92aaf80-f0dc-11e9-8f37-ce3081c96c04.png)

**Comment by asudoh** [comment]
Thanks @laurenmrice for clarifying!
