### ISSUE TITLE
Select elements are using system-ui font, not Plex

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#3043]
## What package(s) are you using?

```
    "@carbon/colors": "^10.1.0",
    "@carbon/grid": "^10.3.0",
    "@carbon/icons-react": "^10.3.0",
    "@carbon/import-once": "^10.1.0",
    "@carbon/layout": "^10.1.0",
    "@carbon/themes": "^10.3.0",
    "@carbon/type": "^10.2.0",
    "carbon-components": "^10.3.1",
    "carbon-components-react": "^7.3.1",
```

## Browser

Latest Chrome

## Detailed description

`<select />` elements in `Select` and `Pagination` components appear to be using the system-ui font. We can see this in our environment & also in [react.carbondesignsystem.com ](http://react.carbondesignsystem.com/).

Here are screenshots from our storybook:

<img width="1032" alt="Screen Shot 2019-06-12 at 3 43 58 PM" src="https://user-images.githubusercontent.com/9057921/59384967-0810b900-8d29-11e9-9590-6e056919fa73.png">

<img width="1031" alt="Screen Shot 2019-06-12 at 3 44 47 PM" src="https://user-images.githubusercontent.com/9057921/59385055-28407800-8d29-11e9-8231-5429ef8a9f1c.png">

**Comment by emyarod** [comment]
seems related to the [regression in input fields](https://github.com/carbon-design-system/carbon/issues/2871) that was fixed by https://github.com/carbon-design-system/carbon/pull/2879
