### ISSUE TITLE
Update theme sandbox

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3046]
Update the theme sandbox http://themes.carbondesignsystem.com/ to have: 
- [x] v10 components
- [x] updated list of tokens (still only color tokens)
- [x] update the theme options to White, G10, G90, G100 themes
![image](https://user-images.githubusercontent.com/15144993/59460228-343d4000-8de4-11e9-86c6-824d74cd8ba8.png)

**Comment by shixiedesign** [comment]
## Updated sandbox preview link from Akira 🎉 
http://carbon-dev-environment-hippest-flaccidness.mybluemix.net/?nav=button

Left to-do is only to push preview site to the `themes.carbondesignsystem.com` url.

**Comment by shixiedesign** [comment]
### New sandbox is now live on original URL! 
http://themes.carbondesignsystem.com/?nav=accordion
