### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#306]
Please provide a 'Carousel' component, it would be very useful for 'marketing' sites.

As an example, please see the carousel here:

http://www.almaden.ibm.com/laborday/index.shtml

Btw, I am not sure, Carousel is the best name for such a component.

**Comment by tw15egan** [comment]
Currently in the works. See #296

**Comment by gmosx** [comment]
Cool, thanks :)

**Comment by BerengarWLehr** [comment]
Does anyone know, why this component was removed in v10?
