### ISSUE TITLE
Forms with required field indicators for more technical applications

### ISSUE THREAD

**Issue by joshua-vaughn** [carbon-design-system/carbon#3065]
### Summary

The current Carbon form component assumes that the majority of form fields are required, and optional fields are called out with "(optional)" appended to their labels. 
- https://www.carbondesignsystem.com/components/form/usage

While we agree that this design pattern is correct for less technical applications, in more technical applications like Cloud Pak for Data it is common to have have forms where the majority of fields are optional and required fields are the exception.

![Required fields](https://user-images.githubusercontent.com/51725782/59455224-95efb100-8dc8-11e9-96df-1a7e42121c27.png)

Our request is that Carbon provide an option for a form to highlight required fields instead of optional fields, perhaps with a red asterisk as is common practice.

For comparison, forms in Salesforce Lightning indicate required fields, while forms in Google Material allow designers to choose whether to indicate required fields or optional fields.

![Salesforce](https://user-images.githubusercontent.com/51725782/59455304-ba4b8d80-8dc8-11e9-8864-eb57cbc904c7.png)
- https://lightningdesignsystem.com/components/form-element/

![Material](https://user-images.githubusercontent.com/51725782/59455317-c20b3200-8dc8-11e9-9654-9379f05162ab.png)
- https://material.io/design/components/text-fields.html#anatomy

### Justification

Cloud Pak for Data intends to migrate to Carbon 10, but with the current design pattern the vast majority of form fields throughout the platform would have the "(optional)" indicator, which looks incorrect and unsightly.

### Desired UX and success metrics

The Carbon form component allows application designers to select whether to highlight required fields or optional fields, depending on the needs of their application.

When required fields are highlighted, they should be highlighted in a way that is accessible and does NOT make users think that empty required field contain errors.

### "Must have" functionality

The Carbon form component allows application designers to select whether to highlight required fields or optional fields, depending on the needs of their application.

When required fields are highlighted, they should be highlighted in a way that is accessible and does NOT make users think that empty required field contain errors.

### Specific timeline issues / requests

This request is important for Cloud Pak for Data to migrate to Carbon 10

### Available extra resources

The Cloud Pak for Data UX team can contribute design, research, and possibly development resources towards this effort. If there are concerns with this request, please set up a meeting with Arin Bhowmick, Joshua Vaughn, and Sam Ting to discuss.

**Comment by joshua-vaughn** [comment]
This is on the backburner, but still very relevant for Cloud Pak for Data.

**Comment by joshua-vaughn** [comment]
Still needed, stalebot.

Some progress: Sam Ting has published design guidelines for the Cloud Pak for Data platform's current AP++ style (based on Carbon 9) on IBM's internal GitHub:
https://github.ibm.com/Sam-Ting/icpd-visuals/blob/gh-pages/Components/optional-required/_optional-required.md

Cloud Pak for Data is starting to plan how we will migrate to Carbon 10, and a workshop is being planned. We hope to start contributing to Carbon 10 soon!

**Comment by joshua-vaughn** [comment]
still needed, stalebot

**Comment by joshua-vaughn** [comment]
Someone should unplug stalebot

**Comment by joshua-vaughn** [comment]
hey

**Comment by jeanservaas** [comment]
We are closing this because it directly contradicts our best practice form guidance — we directly advise against soliciting an excessive amount of Optional information from users. So it's be design that we assume that the majority of information is required.

https://www.carbondesignsystem.com/patterns/forms-pattern#building-a-form
