### ISSUE TITLE
Determine custom property strategy

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#3070]
How can custom properties be used for inline theming? Runtime changes? Which polyfills are available?

**Comment by shixiedesign** [comment]
## Beginning with a digital audit to Carbon components
James has offered to help with conducting an audit of Carbon components to see how type size change affects any box model changes. 
https://ibm.box.com/s/qc30lvnirgrypdidm7rx9bjgwehlkz8m

**Comment by shixiedesign** [comment]
Not stale.
