### ISSUE TITLE
Contribution: Axure kit [Experimental]

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3071]
## General Information
- **Tool**: Axure
- **Status**: Experimental
- **Contributors**: Csaba Sipos 
- **Maintainers**: Csaba Sipos  
- **Distribution location**: Box & GitHub Enterprise 
- **Open-sourced**: No, internal only (atm)?
- **Repo**: https://github.ibm.com/Budapest-Studio/carbon-axure-kit
- **Kit docs**: https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/
- [More info](https://ibm.enterprise.slack.com/files/W4CEWG46B/FJCEGUPLN/carbon_axure_kit.boxnote)

## Assets
- [x] Library: https://ibm.box.com/v/carbon-axure-library
- [x] Template: https://ibm.ent.box.com/v/carbon-axure-template

## Kit Asset requirements: 
- [x] Elements included 
   - [x] Type tokens
   - [x] Color ~tokens:~ _no palettes available in Axure, but color is applied correctly to components_
   - [x] Spacing tokens
   - _Note: Axure is not a visual tool and handles styling different than Sketch. Most styling is applied to the components themselves and not set up as layer or typestyle like Sketch._
- [x] Grid 
   - ~[ ] Templates: N/A~
   - [x] Tutorial on how to set up a grid: [see grid widget](https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/spacing.html)
- [x] Components: [Kit component status](https://docs.google.com/spreadsheets/d/1YHfQt_coJH7BomEnkqzYQTco0-XPx9kt800LpuQRoko/edit?usp=sharing)
   - [x] 01 Accordion
   - [x] 02 Breadcrumb
   - [x] 03 Button
   - [x] 04 Checkbox
   - [x] 05 Code Snippet
   - [x] 06 Content Switcher
   - [x] 07 Data table
   - [x] 08 Date Picker
   - [x] 09 Dropdown
   - [x] 10 File Uploader
   - [x] 11 Form
   - [x] 12 Link
   - [x] 13 List
   - [x] 14 Loading
   - [x] 15 Modal
   - [x] 16 Notification
   - [x] 17 Number Input
   - [x] 18 Overflow Menu
   - [x] 19 Pagination 
   - [x] 20 Progress Indicator
   - [x] 21 Radiobox
   - [x] 22 Search
   - [x] 23 Select
   - [x] 24 Slider
   - [x] 25 Structured List
   - [x] 26 Tabs
   - [x] 27 Tags
   - [x] 28 Text Input
   - [x] 29 Tile
   - [x] 30 Toggle
   - [x] 31 Tooltip
- [x] Component states
- [ ] Themes (only 1 needed for experimental) 
   - [x] White theme
   - [ ] Gray 10 theme
   - [ ] Gray 90 theme
   - [ ] Gray 100 theme

## Documentation
- [x] About the tool (overview and pro/cons)
  - https://ibm.box.com/s/uzm4e8chhsm1nbn25rdw2q8ysjkvbf57
- [x] Getting started content
   - https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/getting_started.html 
- [x] How to use the tool overview (high level features, etc)
   - [Axure element](https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/introduction.html)
   - [Component documentation](https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/accordion.html)
- [x] Website page/section (not for trial phase)

## Support
- [x] Slack channel: #carbon-axure-kit (IBM Studios)
- [x] Repo: https://github.ibm.com/Budapest-Studio/carbon-axure-kit

## Approval
- [x] Kit design review
- [x] Carbon approved 
- [x] Released

## Contribution status
✅  Ready for trial phase

**Comment by aagonzales** [comment]
Review feedback here: https://github.ibm.com/Budapest-Studio/carbon-axure-kit/issues/2

**Comment by aagonzales** [comment]
## Next steps: Internal trial phase
Release date: Next week ~6/17/19

- Need slack post announcement 
- Not adding it to the website for the trial phase, only announced through slack. We can pin the post to the #carbon-design-system channel, so it can easy be foudn.
- Include in post: link to document, repo for feedback, and Axure slack channel. 
- Include blurb about Axure having a free 30 day trial if people want to test the tool out.

## Experimental release
- After feedback and some internal testing we can release it as experimental on the website.
- This phase will need website section or page added, as well as a link on the resource page.
- Move the assets to a publicly available link (not on GHE and Box). Add them to: https://github.com/carbon-design-system/carbon-design-kit

## GA Release:
- TBD

**Comment by connor-leech** [comment]
Taking a look at this. Reopening!

**Comment by csabasipos** [comment]
The Axure kit has been updated for the latest version of Axure (Axure RP 9) and it is ready to be published after review by Carbon team.

**Comment by lnajjar** [comment]
I have had numerous, very significant problems with using the Carbon Design System on Sketch. Sketch support is quite poor (constant backlog, no phone number, weeks to get back on urgent request, requirement for submitter to take videos then create a Dropbox account and load them there). 

So, I am very happy you are working on an Axure Carbon Design System library. My experience with Axure has been very positive -- stable, mature, handles large enterprise app files well, large community, responsive support.

**Comment by lnajjar** [comment]
@csabasipos , I am looking forward to using your Axure version of the Carbon Design System Sketch library. Do you think you could share a status update?

**Comment by csabasipos** [comment]
@lnajjar You can start using the library if you visit the internal IBM link: https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/

(Please note that this is not the Axure version of the Sketch library, doesn't have the exact same elements. It is more Axure-specific, it includes interactive widgets and has been created based on the Carbon documentation and the Sketch library.)

**Comment by csabasipos** [comment]
@lnajjar At the moment, we are preparing the content for the Carbon website (Getting started), as I see it will be published in a few days.

**Comment by lnajjar** [comment]
@csabasipos , I don't have access to the internal IBM Github page you referenced. But I am looking forward to seeing your work published on the Carbon website. Congratulations! Will it include all the Carbon icons and components?

**Comment by csabasipos** [comment]
@lnajjar I'm sorry, I realized that, this is why I changed my comment. 

No, it will be an Axure-specific library with all components, but not the exact same elements as in the Sketch library. It was designed for prototyping in Axure, and elements are interactive. These widgets were created based on Carbon documentation and the Sketch library, but adopted for practical use in Axure RP.  

Icons are not included (except the ones in widgets), but you can paste SVGs of Carbon icons into an Axure document and convert them into Axure shapes to use for your projects. It is more effective than duplicating and maintaining the same icon library in Axure.

**Comment by lnajjar** [comment]
Ooh, your Axure work sounds very promising, @csabasipos !

On the [Carbon Design System site](https://www.carbondesignsystem.com/guidelines/icons/library/), I can copy and paste the icons as .png. I'm not sure how to paste SVGs of Carbon icons into an Axure document, then convert them into Axure shapes to use for my projects.

Other users of your Axure Carbon Design System library will need that information.

Do you think you could write the steps here? Then you could add them to the Getting Started Carbon website.

Thanks for doing this work, @csabasipos . I'm looking forward to designing my Carbon Design System user interfaces using your Axure library.

**Comment by csabasipos** [comment]
@lnajjar I will add these steps to the documentation, until then, [this Chrome extension](https://chrome.google.com/webstore/detail/svg-grabber-get-all-the-s/ndakggdliegnegeclmfgodmgemdokdmg?hl=en) will help you.

**Comment by lnajjar** [comment]
@csabasipos , thank you, and thank you for thinking like the users of your Axure tool.

**Comment by tw15egan** [comment]
Has this been added / completed, or is there still work to be done on this ticket?

**Comment by aagonzales** [comment]
Yup this live on the site now! 
https://www.carbondesignsystem.com/get-started/design/axure/

**Comment by lnajjar** [comment]
Does the Axure kit include the Carbon Design System icons?

**Comment by csabasipos** [comment]
@lnajjar No, the Axure kit does not contain the icons. Please see this documentation about how to use icons copied from Sketch or downloaded as SVGs from the carbon-icons GitHub repository: https://ibm.github.io/design-kit/axure/icons.html

**Comment by csabasipos** [comment]
For further questions about the Carbon Axure Kit, please [open an issue here](https://github.com/IBM/design-kit/issues/new?assignees=csabasipos&labels=kit%3A+axure&template=-axure--carbon-kit.md&title=%5Bcomponent%5D+description+of+issue).

**Comment by lnajjar** [comment]
@csabasipos , this is not a technical question or bug. 

I was hoping to not be the first designer to adopt your very helpful Carbon Design System Axure Kit.

Do you know how many other designers are using it?

**Comment by csabasipos** [comment]
@lnajjar No, I don't have a number for that.
