### ISSUE TITLE
Sass compile error w/ Angular 8.0.1

### ISSUE THREAD

**Issue by NickVanderPyle** [carbon-design-system/carbon#3077]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

An error during sass compilation from Angular:

```console
  &.#{$prefix}--btn--field {
 ^
      Top-level selectors may not contain the parent selector "&".
    ╷
215 │   &.#{$prefix}--btn--field {
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/carbon-components/scss/components/button/_button.scss 215:3                                         button()
```

## What version of the Carbon Design System are you using?
carbon-components 10.3.1
Error appeared **after** updated Angular from 7.x to **8.0.1**.

## Additional information

Full error output:

```console
ERROR in ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  &.#{$prefix}--btn--field {
 ^
      Top-level selectors may not contain the parent selector "&".
    ╷
215 │   &.#{$prefix}--btn--field {
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/carbon-components/scss/components/button/_button.scss 215:3                                         button()
  node_modules/carbon-components/scss/components/button/_button.scss 229:3                                         @content
  node_modules/carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/import-once/import-once.scss 23:5  exports()
  node_modules/carbon-components/scss/components/button/_button.scss 228:1                                         @import
  node_modules/carbon-components/scss/globals/scss/styles.scss 112:9                                               @import
  stdin 8:9                                                                                                        root stylesheet
```

## Workaround

Install `node-sass`, which Angular is moving away from, as mentioned here https://github.com/angular/angular-cli/issues/14497#issuecomment-494716297

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - At this moment `node-sass` is the only Sass compiler we support.

**Comment by cal-smith** [comment]
I'm not sure that only supporting `node-sass` is a viable strategy. the angular cli is defaulting to `dart-sass` and, as far as I'm aware, the plan is to eventually deprecate the `node-sass` module.

I'll look into contributing the fixes to enable `dart-sass` support since it's something we absolutely require.

**Comment by asudoh** [comment]
Cool, looking forward to seeing what you come up with for your #3163 work @cal-smith! And my apologies for not being aware of moves in the Angular/Sass communities.

**Comment by cal-smith** [comment]
No worries, I just wanted to make sure it got addressed 😀
