### ISSUE TITLE
TableToolbarSearch component  with persistant={true} issue

### ISSUE THREAD

**Issue by geechia** [carbon-design-system/carbon#3079]
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description
Using persistant property in  TableToolbarSearch component, setting persistant={true} initially, and set it to {false} after user takes an action on a row.
There is format issue when search box active via persistant set to true verse from clicking the magnifier glass icon, and inconsistent behavior.

> Describe in detail the issue you're having.
1. With persistant={true},  the search box was not formatted properly (appears that bx--toolbar-search-container-persistant referenced does not exist
2. Inconsistent behavior: With persistant={true}, the Search box open as expected, the magnifier icon is not clickable;  however, when persistant property is false or not set, the search box is not active as expected; then clicks the magnifier icon, the search box opens. The magnifier icon is clickable, which present different behavior - what  behavior was intended for a clickable magnifier icon ?  

> Is this issue related to a specific component?
TableToolbarSearch with persistant={true} is passed.
> What did you expect to happen? What happened instead? What would you like to
> see changed?
TableToolbarSearch with persistant={true} should be format correctly and behavior consistently  when searchbox is active triggered by clicking the magnifier icon for TableToolbarSearch with no persistant property or false. 

> What browser are you working in?
Chrome, Firefox, IE 11, I Edge

> What version of the Carbon Design System are you using?
 "carbon-components": "10.2.0",
   "carbon-components-react": "7.2.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Identity. 
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox
https://codesandbox.io/s/codesandbox-p94zn

## Additional information

- Screenshots or code
- Notes
See sandbox attached.

**Comment by asudoh** [comment]
Wondering this is similar to #2339 - CC @emyarod

**Comment by emyarod** [comment]
I don't think so @asudoh, #2339 is mostly a visual bug, although I don't fully understand this issue yet. could you clarify the steps on how to reproduce the issue @geechia ?

on a side note we should probably fix the `persistant` prop to be `persistent`

**Comment by geechia** [comment]
For the TableToolbarSearch, we need a prop like 'open' or 'active' to trigger to expand/activate or close/deactivate  the search input box. The existing persistant prop seem serving this purpose.  
We need a prop to trigger the open and close of search box input.

How  I used TableToolbarSearch:
 I used the  persistant={this.state.active} where it was set to true initially,  the  Magnifier icon and search input box was displayed (See the sandbox here: https://codesandbox.io/s/codesandbox-p94zn),   then I set the this.state.active  to false,  then the searh box was closed i.e. displays the magnifier icon as expected. 

Here are the two issues: 
1.  When   I opened the magnifier icon, the search box is opened with proper styling, and this is the behavior and styling   expected when    persistant={true} was passed initially.  I see  the class styling it attempted to apply is missing, I think the active  search box  triggered in both cases should use the same working scss classes.
2. The magnifier icon was not clickable when persistant was passed, and clickable in later case.

**Comment by geechia** [comment]
Also, one more note, for better user experience, we want to render the TableToolbarSearch in active state initially.

**Comment by geechia** [comment]
Essentially, when persistant={true} should be consistent visually and also the magnifier icon should behave consistently  in the case when user trigger search box to open when persistant={false}

**Comment by tw15egan** [comment]
It seems like this issue has been resolved (use `persistent` prop, rather than `persistant`). Feel free to reopen if this issue if needed.
