### ISSUE TITLE
Broken pages on carbondesignsystem.com

### ISSUE THREAD

**Issue by tokidoki11** [carbon-design-system/carbon#308]
Component version 7.20.0

Website last updated on August 24, 2017 at 12:00 AM

So far I found 2 broken pages cannot be accessed:
- http://carbondesignsystem.com/components/data-vis/code
- http://carbondesignsystem.com/style/grids

**Comment by hellobrian** [comment]
If you're looking for grid page, use this link: http://carbondesignsystem.com/style/grid/design

Can you let us know where you found these links? Can't seem to find any reference to them on our website.

**Comment by bsonefeld** [comment]
Hi @tokidoki11 , our Data Vis pages are in Beta right now and not ready for public consumption. They should be up within the next few days.

**Comment by tokidoki11** [comment]
@hellobrian If you search grid from left nav, you would given the link http://carbondesignsystem.com/style/grids
@bsonefeld I see, since I found the reference to Data Vis in the component overview and the link to it is broken

**Comment by hellobrian** [comment]
Issue moved to [carbon-design-system/design-system-website #15](https://github.com/carbon-design-system/design-system-website/issues/15) via [**ZenHub**](https://www.zenhub.com/)
