### ISSUE TITLE
[Tabs] Write specification

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3081]
**Create content structure**
- [x] Define the component 
- [x] Structure of component
- [x] Visual images of spec
- [ ] Keyboard interactions
- [ ] Compliant rules

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale , need to be open for future work on component spec project

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Going to close this for now since we're not really pursuing spec work actively, feel free to re-open Lauren if this is incorrect!
