### ISSUE TITLE
Is there a "Selected" property for combobox? how to bind it grammatically? 

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3083]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I want to set the selected value of combobox programmaticlly when loading the component... couldn't find a "Selected" property in knobs, how it can be done?

**Comment by asudoh** [comment]
For programmatic control of our combo box, the suggestion is using the underlying presentational components you can find at https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/react/src/components/ComboBox/ComboBox.js#L294-L361 - Hope this helps!

**Comment by zbeedatm** [comment]
Will try it.
But aren't you interested on adding the selected property to knobs as enhancement? It's essential!

**Comment by zbeedatm** [comment]
Can you please more specific, what do you suggest? to take the component, customize it and use it out of carbon-components package? Or using it as is, but try to access inner implementation? How it can be done?
It's not clear to me!

**Comment by asudoh** [comment]
In the link, you find several components like `< ListBox>`, `<ListBox.Field>`, etc. You can use them instead of using `<ComboBox>` to construct the UI.
