### ISSUE TITLE
Modal - ability to customize the primary/secondary button props

### ISSUE THREAD

**Issue by NickMele** [carbon-design-system/carbon#3089]
### Summary
When using the `<Modal />` component it would be great if developers had the ability to pass props to the primary and secondary buttons. Even if it was just 2 extra props on the modal that were `primaryButtonProps` and `secondaryButtonProps`.

This case came up because when the user clicks on the primary button and we do some async processing, we wanted to be able to disable the primary button. Currently there is no way to do that.

I understand that we could use `<ComposedModal />` to build our own custom modal, however with the ability to define buttons using `<Modal />`, we should be able to customize more than just the text on those buttons.

### Justification
Based on the carbon patterns for deleting, a "danger" modal should be shown when removing anything. In our case, when the user wants to delete something we need to wait for that action to complete once they confirm it. We currently show a spinner within the modal, but the button itself is still active and can be clicked again.

**Comment by asudoh** [comment]
Hi @NickMele thank you for reporting! I see your point on `<Modal>`'s flexibility, but for future `<ComposedModal>` is the way to go. Contribution will be welcome for `<Modal>` maintenance, though.
