### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by tokidoki11** [carbon-design-system/carbon#309]
Please add definition file for typescript. Since the documentation didnt really specify what class (module) name can be imported using 
`import {} from 'carbon-components'`

as for now I import all of them, and see what are available.

**Comment by marijohannessen** [comment]
Hi! This is a great idea, and we would love to help out. We, unfortunately, don't have enough resources right now to get to this, so feel free to contribute back any work you do. Thank you!

**Comment by asudoh** [comment]
Hi @tokidoki11 trying to see if you want what components are available on this repo (as you said) or lack of full type information is hardly blocking you. If it’s the former, here’s another way that would help you:

```sh
> git clone git@github.com:carbon-design-system/carbon-components.git
> cd carbon-components
> npm i
> gulp jsdoc
> open docs/js/index.html
```

If you click on Classes menu at the top in the launched browser, you’ll see the list of Carbon component classes. Thanks!

**Comment by joshblack** [comment]
Closing in favor of: https://ibm.biz/BdZgj9

**Comment by murbanowicz** [comment]
@joshblack What's that? The access is restricted.
I found out this library and it is so nice and I'd love to use it but my project is typescript based so I cannot use lib without types...

**Comment by tokidoki11** [comment]
@murbanowicz 
I dont follow this thread for a long time now but I see there is angular support
https://www.carbondesignsystem.com/getting-started/developers/angular

@joshblack the link requires w3id ;)

**Comment by joshblack** [comment]
Hey all! Sorry about the lost link, it redirected to an internal backlog that has since moved to public GitHub 😄 

With respect to typescript, we most likely will not add type bindings for Vanilla JavaScript in the core repo, but will gladly partner with anyone wanting to submit community ones to definitely typed 👍

**Comment by asudoh** [comment]
Yeah and if you google for "typescript use javascript library" you can see how even without `.d.ts` - Hope this helps!
