### ISSUE TITLE
Button: Regression bug: disabled button icon color

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3092]
## What package(s) are you using?
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

After upgrading from Carbon 10.2 to 10.3.1, the icon color for disabled buttons is no longer correct.

> Is this issue related to a specific component?

Button (primary, secondary, and danger variants affected)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The icon for disabled buttons should be the same color as the text

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.3.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. Disable a button that has an icon
2. View icon color

## Additional information
Reference is 10.2.0 and Test is 10.3.1

<img width="748" alt="Screen Shot 2019-06-17 at 6 17 04 PM" src="https://user-images.githubusercontent.com/1275779/59640571-82c44480-912c-11e9-99b7-2cc828100d09.png">

- Screenshots or code
- Notes

**Comment by abbeyhrt** [comment]
Fixed via #3287!
