### ISSUE TITLE
Data Table: Regression Bug: Table headers aren't bolded

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3093]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Updated to Carbon 10.3.1 and the table headers are no longer bolded

> Is this issue related to a specific component?

Data Table

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Table headers would still be bold

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.3.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. Have static table headers in a span (to create correct spacing)
2. view the table header styling

## Additional information
Reference is 10.2.0 and Test is 10.3.1

<img width="859" alt="Screen Shot 2019-06-17 at 6 25 34 PM" src="https://user-images.githubusercontent.com/1275779/59641046-15191800-912e-11e9-92a9-e0ba1c132bbe.png">

**Comment by tw15egan** [comment]
The issue seems to be resolved 👍
