### ISSUE TITLE
customize onClick() event of Accordion to get elements by demand.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3096]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I want to use the Accordion component to display a first level, and only when opening one item to bring it's nested items (by demand) and to display them on another nested accordion.

Tried to use the onClick method:

> const propsAccordion = {
    onClick: action('showNextLvl'),
    onHeadingClick: action('onHeadingClick'),
};

> function showNextLvl(level) {
    alert('Hi');
    console.log("------------------------------");
}

But the method is not firing! How can I customize it?

## Relevant information

And I noticed that when using nested Accordion (or AccordionItems) the collapse/expand button is not functioning!

`const lvl1Items = [];
        const lvl2Items = [];
        const lvl3Items = [];

        elementsLevel3.forEach(function(item){
            lvl3Items.push(
                <li>{item.Name}</li>
            );
        });

        elementsLevel2.forEach(function(item){
            lvl2Items.push(
                <AccordionItem
                    title={text('The title (title)', item.Name)}
                    open={boolean('Open the section (open)', false)}
                    {...propsAccordion}
                >
                    <ul>
                    {lvl3Items}
                    </ul>
                </AccordionItem>
            );
        });

        elementsLevel1.forEach(function(item){
            lvl1Items.push(
                <AccordionItem
                    title={text('The title (title)', item.Name)}
                    open={boolean('Open the section (open)', false)}
                    {...propsAccordion}
                >
                    <Accordion>
                        {lvl2Items}
                    </Accordion>
                </AccordionItem>
                );
        });`

`<Accordion>
                                    {lvl1Items}
                                </Accordion>`

**Comment by asudoh** [comment]
Hi :wave: currently nested accordion is not supported, which is discussed at: #2230
