### ISSUE TITLE
Maybe `Breadcrumb` should be called `Beadcrumbs` ?

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#31]

**Comment by chrisdhanaraj** [comment]
We basically standardized around the singular version of the word for all the components - while agreed that Breadcrumbs in particular is probably a good candidate for the plural, for consistency we stuck with the singular.

**Comment by tw15egan** [comment]
Should we update `tabs` to `tab` for consistency

**Comment by bsonefeld** [comment]
I think the discussion around this was to keep Tabs plural because there will always be more than 1 tab, whereas with Breadcrumb, there _could_ be an instance where there will only be one Breadcrumb.

**Comment by gmosx** [comment]
I think Breadcrumbs with one item is a degenerate case (just like `Tabs` with one tab) and it should be pluralized, just like `Tabs`.

**Comment by hellobrian** [comment]
A single Breadcrumb is more common than a single Tab. 

In our usage docs for [Breadcrumb](http://localhost:3000/components/breadcrumb/usage)

> Breadcrumbs enables users to quickly see their location within a path of navigation and move up to a parent level if desired. Each tier of the Breadcrumb should be clickable.

☝️  In other words, we use Breadcrumbs for nested location paths for navigation.

Navigating through a set of nested paths ensures that you're always going to hit the first Breadcrumb, which would exist as a single Breadcrumb.

![image](https://cloud.githubusercontent.com/assets/4185382/25145455/dda54d78-2436-11e7-9d5e-fdd8f47f1834.png)

Then, navigating deeper into the nested paths will result in multiple Breadcrumbs.

![image](https://cloud.githubusercontent.com/assets/4185382/25145465/e2d0172e-2436-11e7-9059-d86dc7c89f2d.png)

And so on, and so on.

Therefore, it should just be named Breadcrumb.

**Comment by tw15egan** [comment]
>Breadcrumbs ~enables~ enable users to quickly see ...

I'll make that grammar fix 😄

**Comment by gmosx** [comment]
I think there is always a collection of breadcrumbs tiers, even if there is one tier only, it still is a collection and should be called `Breadcrumbs` (plural).
