### ISSUE TITLE
More documentation on javascript (examples)

### ISSUE THREAD

**Issue by tokidoki11** [carbon-design-system/carbon#310]
## Detailed description

I found it is quite documented on every single component (javascript props, public method, etc.) but to use the code is another different thing.

So Far, I'm struggling to do pagination and even just a modal popup. 

Example of the code would be pretty much appreciated.

**Comment by asudoh** [comment]
I’ll defer to the team wrt more documentation in general, meanwhile you’ll get (slightly) more documentation wrt JavaScript API if you do:

```sh
> git clone git@github.com:carbon-design-system/carbon-components.git
> cd carbon-components
> npm i
> gulp jsdoc
> open docs/js/index.html
```

Also, please make sure checking out how to get existing components instance in http://www.carbondesignsystem.com/getting-started/developers and README files in src/components/{componentname}.

**Comment by hellobrian** [comment]
+1 to http://www.carbondesignsystem.com/getting-started/developers

Closing for now, but let us know if you're still having issues with using the JS.
For most people, the docs on the website apply to all our vanilla components.
