### ISSUE TITLE
MS Edge: Moving back and forth for ProgressIndicator distorts ProgressStep icon

### ISSUE THREAD

**Issue by ljitendra** [carbon-design-system/carbon#3113]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react` v6

## Detailed description

The issue is with Microsoft Edge browser, even with the sample link below, try changing the `currentIndex` from 0,1,2 and back and you will notice that the icons distort. Attaching screenshot below. The more ProgressStep components are, the more distortion of the icons. In this example, only the middle icon gets distorted, but try with 6 and all icons get distorted.

http://v6-react.carbondesignsystem.com/?selectedKind=ProgressIndicator&selectedStory=interactive&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
ProgressIndicator and ProgressStep components

> What browser are you working in?
Microsoft Edge

> What version of the Carbon Design System are you using?
V6

## Additional information
<img width="1431" alt="Screen Shot 2019-06-14 at 11 41 26 AM" src="https://user-images.githubusercontent.com/15458935/59778025-b36ac200-9283-11e9-9b28-345f872e63d4.png">

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

**Comment by ljitendra** [comment]
Unable to add label as bug.

**Comment by tw15egan** [comment]
@ljitendra Is this still an issue? Going to close this for now, but feel free to reopen if you are still experiencing issues.
