### ISSUE TITLE
System test suite updates

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3126]
This issue is an umbrella issue for testing updates we should make to the system for the various packages. This is broken down into a couple of categories, namely by package and by experiment.

## React

- [ ] Remove all warnings and console output from our test suite
- [ ] Update the `requestAnimationFrame` from a synchronous version to an asynchronous version to align with expected implementation in browser
- Experiments
  - [ ] Investigate `react-testing-library`, or something equivalent, to use instead of enzyme

## Vanilla

- Experiments
  - [ ] Investigate feasibility of porting tests from Karma to Jest

## Experiments

- [ ] Investigate using jest projects for per-package configuration instead of one root object

**Comment by asudoh** [comment]
Leaving a note; Vanilla is using Jasmine, the same underlying assertion engine as Jest. Vanilla is not using Jest on purpose, though, but using Karma from two reasons, one is cross-browser testing, another is debug-ability of DOM.

**Comment by joshblack** [comment]
We should still look into consolidating test suites. If we need access to browsers, that is also do-able in Jest.

**Comment by asudoh** [comment]
Issue# 848 at the Jest repo shows that this still is a problem. Other search shows that some people are working it around by using Chrome debugging protocol, but it seems sub-par to the experience with Karma.

**Comment by joshblack** [comment]
@asudoh seems like that issue is old? Can always use puppeteer: https://jestjs.io/docs/en/puppeteer

It also includes a custom example that shows how it is implemented, I'm sure similar plugins exist. There is also exploration in that issue using Karma directly, so seems like this would be worth looking at?

**Comment by asudoh** [comment]
Seems that https://jestjs.io/docs/en/puppeteer runs browser via Chrome debugging protocol rather than running test cases directly in browser, and thus the experience is sub-par to one with Karma.

**Comment by joshblack** [comment]
What's the difference? The code ends up being evaluated in the headless (or optionally visible) window either way. I'm just confused why you don't think we should at the very least explore this? Could be that we find something that works. It's not like the issue is saying this will happen, just that we should explore it.

**Comment by asudoh** [comment]
> The code ends up being evaluated in the headless (or optionally visible) window either way.

Seems not with https://jestjs.io/docs/en/puppeteer, given the link has an example that seems to evaluate page title in non-DOM way.

**Comment by asudoh** [comment]
I recall I read the link, and determined that that's won't be a viable replacement of Karma, due to the difference in where the test spec code runs.

**Comment by shinytoyrobots** [comment]
@joshblack, can you define in the top level purpose of such an investigation (i.e. what problem are we trying to solve), so that's clear in the issue?

@asudoh, if this is an exploration on the team then it needs discussion rather than just a "no". i.e. is there a reason to not consolidate? Or, if the problem is with the suggested solution to consolidation, what alternatives are there?

**Comment by joshblack** [comment]
@shinytoyrobots in this case, consolidating test runners so that there aren't multiple in the same project seems like a clear value add. In other words, we don't have to jump between two testing libraries and their associated toolchains. There is just one. This has the side-effect of less dependencies to install, less domain knowledge to collect in order to contribute, less surface area to cover, etc.

This is only one point of the broader issue, though, most of the bullet points provide direct value in either fixing something that is broken or correcting the behavior of something to be more inline with how it is intended to function.

**Comment by asudoh** [comment]
@shinytoyrobots Though tooling consolidation is worthwhile in general, we need to be careful not blindly doing "one size fits all". We need careful evaluation to avoid such consolidation effort having negative impact to the efficiency, etc. of our development effort. Jest is runs the test case in node.js, which is not suitable to test DOM-intensive code like vanilla/Angular codebase - Instead we need an environment where the test case code runs in browser so that the test case code and the DOM can be debugged in a single environment.

**Comment by joshblack** [comment]
@asudoh this specific part of the issue is for exploring/investigating. There is no work item to change things. I think if we agree on the ideal (a test runner that can handle all of our use-cases), then it seems worth the time to investigate?

**Comment by asudoh** [comment]
We can continue our journey to investigate possible options. Though I don't see Jest is a viable option for vanilla/Angular testing even with the links brought up in this PR, but something new may come up in future.

**Comment by joshblack** [comment]
Would it be productive to highlight what features are missing that you feel like are required? It looks to be being able to test in multiple browsers? As far as I'm aware, in CI this would most likely only be chrome/firefox? If these are the only ones we can reliably test in CI, what's the difference between that and JSDOM? Or between using equivalent environments in Jest? Similarly, if FB doesn't seem to have a need for browser testing should we also look to see if this invariant holds true for our efforts?

**Comment by asudoh** [comment]
Not just actual/multiple browsers. We need to have a single environment where test case runs and see the DOM change as soon as it happens, with the associated call stack associated with the DOM change. It's more of debuggability than of CI. That said, don't be confused of "actual browser" with E2E testing (like Cypress). Just in case with the acronym above, we shouldn't pick a single company as the benchmark BTW. Different companies pick a testing strategy (or does not pick) based on their different needs.

**Comment by joshblack** [comment]
This can feel like you're suggesting JSDOM is not a suitable environment, could you explain why? If the goal is actual browsers and the experience of testing within them, should we invest time in using: https://www.cypress.io/ ?

As the related Jest issues suggest, Facebook doesn't seem to see this as a need in their unit testing. What confidence does being able to run these unit tests in multiple browsers on a developer's machine give us?

The reason I bring up CI is that it is the form of automatic checking in this situation, as we can't assume contributors will run all changes across all browser environments on their local machine. This could be a problem for things like IE11 if running on a Mac, or Safari if running on Windows. As a result, not being able to automatically check and fail the CI build feels like a drawback of this approach.

**Comment by joshblack** [comment]
> Just in case with the acronym above, we shouldn't pick a single company as the benchmark BTW.

For sure, I hope it didn't come across as the only benchmark. The exact quote is:

> Similarly, if FB doesn't seem to have a need for browser testing should we also look to see if this invariant holds true for our efforts?

Which doesn't assume this is the only way, but as a prompt to explore what conditions this invariant holds for that company. Clearly they are full of talented/smart engineers working on similar spaces in a similar tech stack, I'm only suggesting that we can learn from them or explore why they find something unhelpful to better improve our own process.

As you noted, this is separate from e2e testing for which they totally have a different setup.
