### ISSUE TITLE
Make sure sketch plugin syncs across symbol ids

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3128]
Currently, our Sketch plugin will delete and replace symbols/shared styles. Instead, we should have the plugins find the relevant shared style or symbol and update all instances of it.

**Comment by joshblack** [comment]
cc @lovemecomputer I have some work setup for this, did you want me to try and wrap it up and PR it or would you want to take this on and finish it?

**Comment by lovemecomputer** [comment]
@joshblack if your work is viewable anywhere, i'd love to see it! i know you've found some solutions, but if it make sense to start fresh i'm happy to do that as well

**Comment by joshblack** [comment]
@lovemecomputer ended up picking back work on this yesterday actually! Sorry for not updating this issue 🤦‍♂️

**Comment by joshblack** [comment]
Will PR hopefully EOD today or tomorrow 👍

**Comment by lovemecomputer** [comment]
awesome thank you @joshblack !
