### ISSUE TITLE
Why the color of the react button does not depend on the brand colors

### ISSUE THREAD

**Issue by bymoe** [carbon-design-system/carbon#3138]
## What package(s) are you using?
[Button]  `carbon-components-react`

## Relevant information

So I used the [carbon theme generator](http://themes.carbondesignsystem.com/) to get a pallete for my new carbon react system, Turns out it's a little bit different, The [Button] colors - primary & secondary - depends on the `$interactive-01` and `$interactive-02` sass variables rather than `$brand-01` and `$brand-02`, am I missing something?

**Comment by tw15egan** [comment]
Hey sorry about that! The theme generator is a bit out of date, but it is currently being worked on by @asudoh

**Comment by bymoe** [comment]
@tw15egan Oh, Thanks for the info ^

**Comment by asudoh** [comment]
Closing as themes.carbondesignsystem.com has been updated.
