### ISSUE TITLE
Data Table: animation clips batch actions toolbar when selecting/de-selecting rows

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#3145]
## What package(s) are you using?

I'm using the latest in my project, but for this example I'm just looking directly at the storybook: http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions

## Detailed description

Gif below shows what I mean (parts of the batch action toolbar are clipped in the animation as you select/deselect rows):

![output](https://user-images.githubusercontent.com/9057921/59935902-610cdb00-9414-11e9-9c39-236ce8a302da.gif)

**Comment by tw15egan** [comment]
Is this fixed with this PR? https://github.com/carbon-design-system/carbon/pull/3095

**Comment by jendowns** [comment]
@tw15egan do you know if the storybook was updated? I can see that it is fixed in the react deploy in #3095 (https://deploy-preview-3095--carbon-components-react.netlify.com/?path=/story/datatable--with-batch-actions) but it still behaves the same in the published storybook (http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions)

**Comment by jendowns** [comment]
Closing because I don't see this issue anymore in our environment after upgrading versions 👍
