### ISSUE TITLE
Scrollable body using StructuredList and/or Data Table

### ISSUE THREAD

**Issue by WilliamHolmes** [carbon-design-system/carbon#315]
## Detailed description

General issue/question.

StructuredList
Data Table

Is it possible to use any carbon-components magic  and enable the body elements to be scrollable, if a set height/width it paced on the parent?

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 
```
    "carbon-components": "7.17.1",
    "carbon-components-react": "3.7.0",
```

**Comment by aagonzales** [comment]
@WilliamHolmes yes were are going to look into universal patterns for truncating and scrolling content patterns inside of components. Hopefully we will be able to do some magic around this topic.

**Comment by marijohannessen** [comment]
@aagonzales are we covering this in our Utilities section so it's okay to close this issue?

**Comment by WilliamHolmes** [comment]
Apologies thought you said it was covered. Feel free to close it is.

**Comment by asudoh** [comment]
Closing - @WilliamHolmes feel free to enter another issue or reopen as needed!
