### ISSUE TITLE
Modal messes up when placed inside TableToolbarContent in DataTable

### ISSUE THREAD

**Issue by jikkujj** [carbon-design-system/carbon#3153]
The modal looks messed up when I click the "Show Modal-Inside Datatable" button in the DataTable. But if i put the button for the modal launch outside the datatable, it  displays the modal correctly
https://codesandbox.io/s/carbon-components-react-wt5pb

> TJ Egan  [9 minutes ago]
Hmm, seems to a problem with `TableToolbarContent`, and specifically the `translate3d` moving it to another layer. If you move it adjacent the `TableToolbarContent`, it renders correctly (although the styles of the button are off)

> TJ Egan  [3 minutes ago]
It seems to work if the transforms are switched to `translate` as opposed to `translate3d`. Could you create an issue so we can properly track this?

**Comment by asudoh** [comment]
Hi @jikkujj two things I can see in your CodeSandbox:

1. `<ModalWrapper>` virtually is demonstration-purpose-only component. You can use your own button that sets `open` prop of `<Modal>` or `<ModalWrapper>`
2. It appears that the place you tried to put the modal launcher button collides with our batch actions. Please work with your designer to see where would be the best place to put the launcher button that fits best in Carbon ecosystem. One guess I have is in `<TableToolbarContent>`.

**Comment by jikkujj** [comment]
I replaced the modalwrapper with a combination of modal and button.
And placed it in the tableToolbarContent but the modal is still messed up.
https://codesandbox.io/s/carbon-components-react-k15kd?from-embed

**Comment by asudoh** [comment]
Seems that the issue with modal launcher button is fixed in your latest sandbox. Your `<Modal>` in your latest sandbox doesn't seem to have any content, though. Note that you won't need `<ModalWrapper>` if you are using `<Modal>`.
