### ISSUE TITLE
Unable to customize styling using tokens ?

### ISSUE THREAD

**Issue by mohit61** [carbon-design-system/carbon#3154]
I tried using carbon components in my react app. I am facing trouble customizing the components. I have installed node-sass.

This is my **app.js** file

`import React, { Component } from "react";`
`import "./App.scss";`
`import { Button } from "carbon-components-react";`

`export default class App extends Component {`
  `render() {`
 `   return (`
     ` <div>`
      `  <h1>Carbon components</h1>`
      `  <Button className="bx--btn bx--btn--secondary">Secondary Button</Button>`
   `   </div>`
   ` );`
`  }`
`}`

This is my **App.scss** file
`@import "~carbon-components/scss/globals/scss/styles.scss";`
`$interactive-02: #bada55 !default;`

But it does not change the background color of button.

**Comment by asudoh** [comment]
Hi 👋 you should do the following instead:

```scss
$interactive-02: #bada55 !default;
@import "~carbon-components/scss/globals/scss/styles.scss";
```

**Comment by mohit61** [comment]
@asudoh  I invested lot of time figuring out what is wrong and I have never imagined that using import at the top is the problem. I should have asked earlier. Thanks a lot.
