### ISSUE TITLE
Move from node-sass to dart-sass

### ISSUE THREAD

**Issue by spankyed** [carbon-design-system/carbon#3158]
## Brief description
Dart Sass is the primary implementation of Sass. 
https://sass-lang.com/dart-sass

I am unable to use carbon with parcel, because parcel uses dart sass by default.

**Comment by asudoh** [comment]
Hi 👋 from the issue# 1847 in Parcel repo, I have an impression that `node-sass` will just work as long as you have `node-sass` installed in your project (putting `node-sass` issues they are pointing out aside). Let us know if you think it's not the case.

**Comment by asudoh** [comment]
Related: #3174. I think we'll keep `node-sass` the default, though.
