### ISSUE TITLE
Monospaced Font

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#316]
Please provide guidance re using a monospaced font.

E.g. a monospaced font would be useful in the DataTable component, especially for numeric and/or monetary values (that may need to be right-aligned for easier 'scanning').

**Comment by bsonefeld** [comment]
Hey @gmosx , I would recommend using a font similar to the one used in our [Code Snippet ](http://carbondesignsystem.com/components/code-snippet/code) component.

**Comment by gmosx** [comment]
Nice suggestion thanks, maybe you should add this advice to the 'Typography' section of the site?

**Comment by gmosx** [comment]
And maybe even add some SCSS mixins/variables for monospaced fonts in _typography.scss?

**Comment by bsonefeld** [comment]
Thanks @gmosx  that's a great suggestion!
