### ISSUE TITLE
defaultValue props in TextInput component doesn't work!!

### ISSUE THREAD

**Issue by ashwintastic** [carbon-design-system/carbon#3168]
## What package(s) are you using?

- [ ] `carbon-components`:  10.1.0
- [ ] `carbon-components-react`:  7.3.1

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
1.  set an initial for  defaultValue props of `TextInput` in the constructor
2. Mimic an api call in `componentDidMount and change the value for  defaultValue text
3. The updated value of defaultValue  won't reflect in the `TextInput` component.
 

> Please create a reduced test case in CodeSandbox
>   [Bug is reproduced in this link](https://codesandbox.io/s/codesandbox-i56p4)

**Comment by asudoh** [comment]
Thank you for reporting @ashwintastic - Fixed by: #3106
