### ISSUE TITLE
How to make a new component for react in carbon ?

### ISSUE THREAD

**Issue by mohit61** [carbon-design-system/carbon#3177]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

**Comment by asudoh** [comment]
Hi 👋 given this subject would have multiple possible interpretations, would you want to provide some more context?

**Comment by mohit61** [comment]
@asudoh  I want to build a card component for carbon, I am finding it hard to figure out the structure,  how the components are built in carbon for react?  Can u guide me please ?

**Comment by emyarod** [comment]
I believe this step of our new tutorial may be useful to you https://www.carbondesignsystem.com/tutorial/react-step-4

**Comment by asudoh** [comment]
In addition to the great reference from @emyarod - Carbon's React components, one provided by us as well as ones applications create, are either regular React components with some Carbon styling or React components using Carbon ones in it. For the former, you can go to components page in carbondesignsystem.com site and how Carbon CSS classes are applied to the markup. For the latter, you can go to react.carbondesignsystem.com to see the API of our components. Hope these help!
