### ISSUE TITLE
Data table header unable to expand in height

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon#3180]
Data table header symbol can't expand in height to accommodate increased text lines.  Additionally the symbol doesn't allow text to wrap naturally.

![image](https://user-images.githubusercontent.com/51379566/60181584-858bfd00-97f0-11e9-948e-2631959a328d.png)

**Comment by emyarod** [comment]
this is only related to the design kit right?

**Comment by marceltrautmann** [comment]
I suppose so.  it's the symbol in sketch that I'm working with.  can't adjust without detaching from library/symbol.

![image](https://user-images.githubusercontent.com/51379566/60271197-e59da480-98bf-11e9-9f32-1523ed8c215d.png)

**Comment by emyarod** [comment]
in that case I'll transfer this issue over to the relevant repo

actually it may be best to reopen the issue yourself over at https://github.com/carbon-design-system/carbon-design-kit/issues/new since the issue templates are different

**Comment by marceltrautmann** [comment]
apologies, I normally put them in the design-kit repo, but this time I was given a direct link to here for some reason
