### ISSUE TITLE
[Theme] Highlight token value doesn't work in dark themes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3182]
## Token value

Dark themes `$highlight` has wrong values. Currently using `blue-90` on both Gray 90 and Gray 100 themes. 

Current values for `$highlight` token: 

| White | Gray 10 | Gray 90 | Gray 100 |
| --- | --- | --- | --- |
| `blue-20` | `blue-20` | `blue-90` | `blue-90` |

Should be changed to below values for `$highlight` token: 

| White | Gray 10 | Gray 90 | Gray 100 |
| --- | --- | --- | --- |
| `blue-20` | `blue-20` | `blue-70` | `blue-80` |

![image](https://user-images.githubusercontent.com/15144993/60195519-d4da2980-9800-11e9-862c-4daecd10c671.png)

### Related bug

We never caught this bug because our dark theme Date picker is not using dark theme values – issue made https://github.com/carbon-design-system/carbon/issues/3183

![image](https://user-images.githubusercontent.com/15144993/60192671-e40aa880-97fb-11e9-9cc3-542d02d0cc07.png)

**Comment by jendowns** [comment]
Hey @shixiedesign I went ahead and updated these tokens in #3248 -- let me know what you think 👍 Thanks!
