### ISSUE TITLE
[Date picker] Dark theme's dropdown is wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3183]
## Multiple styling bugs

- [ ] Calendar icon getting wrong focus outline. 
- [ ] Need dark theme dropdown

### Calendar icon getting wrong focus outline. 

![image](https://user-images.githubusercontent.com/15144993/60300171-05e75680-98f4-11e9-8789-67ebedde9991.png)

### Need dark theme dropdown

**Current**

![image](https://user-images.githubusercontent.com/15144993/60195637-0ce16c80-9801-11e9-9aeb-aba84a7a56be.png)

**Should be**

![image](https://user-images.githubusercontent.com/15144993/60201746-a400f100-980e-11e9-8f0d-003a71cb966e.png)

**Comment by abbeyhrt** [comment]
I'm gonna tackle this one!

**Comment by abbeyhrt** [comment]
After looking at this, it seems like the code is right but that the vanilla dev environment isn't updating the theme correctly for the DatePicker menu, specifically datepicker, the dropdown calendar portion,  renders outside of the examples so it doesn't have the live theme, it only has the default theme. @asudoh is this a known issue or is there something I should be doing instead?

**Comment by asudoh** [comment]
@abbeyhrt Oh I forgot that Flatpickr uses a floating menu 🙇 - I think applying a similar fix to #3444 will solve this issue. Would you want to try that? Thanks!

**Comment by abbeyhrt** [comment]
Yeah of course, I'll get that done today!

**Comment by aagonzales** [comment]
This is also happening with other floating menus like overflow menu and tooltip 
![image](https://user-images.githubusercontent.com/11670886/61737550-0ede1300-ad4e-11e9-9ef4-cb0b81748abd.png)

Tool tip should be a high contrast moment (inverse tokens)
![image](https://user-images.githubusercontent.com/11670886/61737629-3e8d1b00-ad4e-11e9-8ab0-6054d9c79e6c.png)

**Comment by asudoh** [comment]
@aagonzales I believe @abbeyhrt has fixed them already - Just need to update themes.carbondesignsystem.com.
