### ISSUE TITLE
TextInput  component defaultValue not working?

### ISSUE THREAD

**Issue by ashwintastic** [carbon-design-system/carbon#3185]
## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

Step to reproduce 
 pass blank props say defaultValue = '' to `TextInput component`
 after data get loaded from server pass defaultValue = 'some name'  as a prop to `TextInput`
`TextInput component` still showing blank value
> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
- Notes

**Comment by vpicone** [comment]
You should be using the `value` prop to dynamically change a text-inputs value. The defaultValue controls the value when the component is first rendered

**Comment by asudoh** [comment]
Also, could you please describe the Carbon version as requested in the issue template? Thanks!
