### ISSUE TITLE
[Modal] When the modal is open, should we disable body(or parent element) scrolling?

### ISSUE THREAD

**Issue by doublepithre** [carbon-design-system/carbon#3187]
What package(s) are you using?

- [ v10.3.2] `carbon-components`
- [ v7.2.0] `carbon-components-react`

## Summary
When a Transactional/Passive modal is open, what is the expected behavior of the background element when the user initiates a scrolling action?

Currently, the background element scrolls which might not be a preferable option for many. If Carbon Design System requires to have this current behavior, is there any way we can disable scrolling? For example, with Bootstrap we had a `modal-open` class added to the body element when the modal is open which helped to disable the scrolling.

![modal-carbon-design](https://user-images.githubusercontent.com/40420828/60198449-3fba4d80-985f-11e9-896b-09ec707cb629.gif)

**Comment by asudoh** [comment]
@alisonjoseph The screenshot seems to refer to our website. Though the idea of adding a class to `<body>` is plausible, wanted to double-check with you to see what the desired behavior would be with the screenshot. Thanks!

**Comment by alisonjoseph** [comment]
I would agree that we don't want the body to scroll when a modal is open, just want to confirm with @carbon-design-system/design that it is the intended behavior.

**Comment by designertyler** [comment]
I agree with that. Let's add it!

**Comment by doublepithre** [comment]
Yes, that would be great.
