### ISSUE TITLE
[Button] Dark themes disabled state wrong & icon btn has extra border

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3190]
### 1. Disabled states showing wrong color & hover state

- [ ] Disabled button should use `$disabled-02` for background and `$disabled-03` for text & icon. 

**Current:** 

![Jun-26-2019 14-30-32](https://user-images.githubusercontent.com/15144993/60208908-12e64600-981f-11e9-9157-2526ac96a1cd.gif)

![image](https://user-images.githubusercontent.com/15144993/60209110-8ee08e00-981f-11e9-9497-8334def19de0.png)

![image](https://user-images.githubusercontent.com/15144993/60209747-e4696a80-9820-11e9-8f24-fc18f3583360.png)

**Should be**

`$disabled-02` for background and `$disabled-03` for text & icon.

### 2. Icon button has double border on focus

- [ ] Inside focus border around icon itself should not be there. Only focus border around the button needed.

![image](https://user-images.githubusercontent.com/15144993/60210091-a91b6b80-9821-11e9-8379-4b2c3e6d6540.png)

**Comment by aagonzales** [comment]
### 3. ghost button color token is wrong
Currently in code its using `$interactive-04` but the text and icon should be using ~$icon-01~ `$link-01`

![image](https://user-images.githubusercontent.com/11670886/60351528-9755d780-998b-11e9-852d-811b82bb8e47.png)

**Comment by jeanservaas** [comment]
Focus boarder on icon looks and hover issue on disabled looks fixed! Thumbs up!

**Couple issues still**

$disabled-03 token (applied to the text and the icon) value is #6f6f6f

![image](https://user-images.githubusercontent.com/43144260/60918681-8a719780-a259-11e9-9e2f-93f9ce292ff0.png)

But all of the disabled icons in the dark themes on the carbon-components netlify link look like they're pulling Gray 10 (they appear to be the same color as the enabled icons right next to them)
![image](https://user-images.githubusercontent.com/43144260/60918557-3ebeee00-a259-11e9-8742-626aada8e79a.png)

Not sure what's happening but the icons don't appear to be taking the $disabled-03 token



____

Also, our bad, but I believe ghost button (text and icon) should be using the $link-01 token NOT the $icon-01 token 

so the text and icon will be 6ea6ff

<img width="255" alt="image" src="https://user-images.githubusercontent.com/43144260/60920371-9f502a00-a25d-11e9-89a8-8dcb63bcb62d.png">
