### ISSUE TITLE
Data table header mismatch (firefox)

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3191]
@marceltrautmann commented on [Tue Jun 25 2019](https://github.com/carbon-design-system/carbon-design-kit/issues/131)

https://www.carbondesignsystem.com/components/data-table/code

Note that the column headers are all 47px except for the status column (far right) which is correct at 48px per the design spec.

![image](https://user-images.githubusercontent.com/51379566/60129053-267fa700-9762-11e9-9e79-bc5f399a66e6.png)

**Comment by asudoh** [comment]
@jnm2377 Do you know/remember what [`position:relative` in `.bx--data-table th:last-of-type`](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/components/data-table/_data-table-core.scss#L103) is for? I'm wondering if such style should be applied to all `<th>`s or to no `<th>`, and I think such decision would depend on the original intent. Thanks!

**Comment by tw15egan** [comment]
Issue no longer seems to be present, feel free to reopen if you are still seeing this 🙂
