### ISSUE TITLE
carbon-components NPM page has broken build link

### ISSUE THREAD

**Issue by kinueng** [carbon-design-system/carbon#3198]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

On the carbon-components npm page [1], there is a broken link to TravisCI.  
![image](https://user-images.githubusercontent.com/31117513/60277006-55149380-98c2-11e9-8edc-9a19cded41c5.png)

My understanding is that the carbon team now uses CircleCI here [2].  I am not sure how to submit a change to the npm page to update the build link.  I would be happy to contribute with some guidance to managing the npm page.

[1] https://www.npmjs.com/package/carbon-components
[2] https://circleci.com/gh/carbon-design-system/carbon

**Comment by emyarod** [comment]
it's pulling from the [README](https://github.com/carbon-design-system/carbon/blob/master/packages/components/README.md) so we can just edit that file
