### ISSUE TITLE
Search (react) component—`light` prop not applying style for light theme

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#3199]
http://react.carbondesignsystem.com/?path=/story/search--default

the `light` knob does not seem to change the component. it didn't work when using in `carbon-website` either. i had to manually add the `bx--search--light` as a classname to get the light bg color.

**Comment by asudoh** [comment]
Seems that we have removed `light` prop in April 24th, as part of larger change. Such "larger change" thing made me unsure if the change was intentional or not. CC @carbon-design-system/design to see if we should bring it back.

**Comment by shixiedesign** [comment]
No designers have not made a decision to remove light variant. We are all still waiting for inline theming to be set up. Does anyone in @carbon-design-system/developers know about this change? I don't know the specific impact here, but I suspect this affects our current users significantly.

**Comment by alisonjoseph** [comment]
My hunch is that it was removed on accident, but I'm not 100% sure.
