### ISSUE TITLE
Need the font for an accurate view the Sketch file

### ISSUE THREAD

**Issue by adeysalyards** [carbon-design-system/carbon#32]
Thanks!

**Comment by bsonefeld** [comment]
Hey @adeysalyards ! We're in discussion right now with IBM Legal in regards to being able to distribute the IBM Helvetica Neue font files. 

This is an active issue we're working on as we realize it causes font rendering issues within the Sketch file. We'll keep you posted with any updates that occur moving forward. 

You can find the font hosted on IBM Northstar's webpage (style guide for IBM Digital products)
https://www.ibm.com/standards/web/attachments/HelvNeueforIBM_v1_Nov2015.zip

**Comment by chrisdhanaraj** [comment]
Unfortunately we're legally barred from distributing the font file - however, there's a newer font that IBM will be open-sourcing in the near future, we'll include that one when we update!
