### ISSUE TITLE
Remove internationalisation blocked in table and pagination

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#3203]
# Summary

Pagination and Table include constructed text in carbon-components-react which is a blockage to internationalisation. Provide a way for the user to construct these pieces of text. Specifically "start-end of items", "of N pages" in pagination and "N items selected" in table.

This issue was first raised in @carbon/vue https://github.com/carbon-design-system/carbon-components-vue/issues/453
 
Here a fix has been provided for pagination using scoped slots. I believe the equivalent of "Render props" in React.

### Justification

Allows Carbon components to be used in translated products.

### "Must have" functionality

The ability for the user to specify all text in components.

**Comment by varatep** [comment]
There's no documentation regarding this and I don't see a straightforward solution, can we re-open this issue?
