### ISSUE TITLE
[Combo box] all themes hover & select style wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3204]
Noticed in vanilla, double checked in react: 

### All theme's hover & select styling on the dropdown is wrong. 

Hovered option **background** be using color token `$hover-ui`
Selected option **background** should be using color token `$selected-ui`
Selected options **border bottom** should be using color token `$active-ui`

![image](https://user-images.githubusercontent.com/15144993/60283118-1258b880-98ce-11e9-9549-192dfaa09da3.png)

![image](https://user-images.githubusercontent.com/15144993/60283139-1e447a80-98ce-11e9-80ea-9ea38c0840de.png)

**Comment by abbeyhrt** [comment]
@aagonzales I believe that the styles for this are coming from the ListBox, which we use for MultiSelect and Dropdown, do you know if those components have the wrong colors too?

**Comment by laurenmrice** [comment]
in the latest pr i reviewed https://github.com/carbon-design-system/carbon/pull/4753#event-2952626553 these seemed to be correct

On the current live react link the colors are wrong.

**Comment by tw15egan** [comment]
The deployed version may not be updated as of yet? Not sure how often we update it

**Comment by abbeyhrt** [comment]
@laurenmrice thank you for looking into it! That PR should be included in the next minor release so if it's alright with you, we can close this issue?

**Comment by laurenmrice** [comment]
yeah i think this is fine to be closed ! i think its been resolved
