### ISSUE TITLE
[inline-loading] component depends on styles of `loading`

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#3205]
## What package(s) are you using?

- [x] `carbon-components` `v10.3.2`
- [ ] `carbon-components-react`

## Detailed description

The classnames inside the loading circle svg of `inline-loading` refer to styles of the `loading` component. I was wondering, why the inline loading spinner didn’t show up, because I’ve imported the `inline-loading.scss` only. Then I’ve realized, that I have to import the `loading.scss` to get the right styles for the inline-loading spinner. In my opinion, the inline-loading component should get independent styles.

## Steps to reproduce the issue

1. Use ´inline-loader`
2. Import `inline-loader.scss` only (not `loader.scss`)

https://github.com/carbon-design-system/carbon/blob/8a199fbac3ea0740dd37f5d5fd6e05209bbd3c07/packages/components/src/components/inline-loading/inline-loading.hbs#L12-L15

**Comment by asudoh** [comment]
Thank you for reporting @IOIO72 - Yeah the spinner used in inline loading is exactly same as the loading. So it's working as designed.
