### ISSUE TITLE
[Content switcher] Dark themes disabled states style wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3207]
### Component might not be using correct tokens for disabled states: 

Default disabled state background: `$disabled-01`
Default disabled state text: `$disabled-02`
Selected disabled state background: `$disabled-03`
Selected disabled state text: `$disabled-02`

**Current:** 

![image](https://user-images.githubusercontent.com/15144993/60284416-1c2feb00-98d1-11e9-91e3-d2b6f5af3957.png)
![image](https://user-images.githubusercontent.com/15144993/60284447-29e57080-98d1-11e9-88d9-55d4c7d054ba.png)

**Should be:** 

![image](https://user-images.githubusercontent.com/15144993/60284391-07ebee00-98d1-11e9-8552-d9796f84d2f0.png)

**Comment by abbeyhrt** [comment]
I'm gonna work on this one and see if I can fix what's going on! 🙂
