### ISSUE TITLE
[Copy button] Tooltip style wrong, icon wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3208]
### Two bugs found

- [ ] tooltip styling is wrong. Ref https://github.com/carbon-design-system/carbon/issues/3202 for spec
- [ ] icon in button is v9. should be updated even if we don't expose this component in website
- [ ] it should be using the `copy` icon instead of `add`
- [ ] it should be an icon only style button (no text)

![image](https://user-images.githubusercontent.com/15144993/60285206-0b807480-98d3-11e9-9a23-9133fda89155.png)

**Comment by aagonzales** [comment]
Looks like the color issues may have been resolved already.

![image](https://user-images.githubusercontent.com/11670886/66220859-6cb6a180-e693-11e9-8ec0-030ad918f949.png)
