### ISSUE TITLE
[Data table] Multiple styling bugs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3210]
#### 1. Header row has extra border bottom. No border until the row immediately underneath header is selected.

![image](https://user-images.githubusercontent.com/15144993/60292022-d4658f80-98e1-11e9-8631-0957d54a0f84.png)

#### 2. Zebra row has wrong color 

Correct zebra row background colors are: 
Odd row background: `$field-01` at 40% opacity
Even row background: `$field-01`

**Current**

![image](https://user-images.githubusercontent.com/15144993/60294096-388a5280-98e6-11e9-8f32-6acaec4108cc.png)

Current dark theme zebra is all row colors wrong ⚠️ 

![image](https://user-images.githubusercontent.com/15144993/60294871-feba4b80-98e7-11e9-984a-acf121bce3b4.png)
![image](https://user-images.githubusercontent.com/15144993/60294962-2b6e6300-98e8-11e9-8c4f-c6b12f17ff88.png)

**Should be**
![image](https://user-images.githubusercontent.com/15144993/60294314-af275000-98e6-11e9-9f60-6242a263c00d.png)

#### 1. Overflow menu hover background wrong

Should be using token `$hover-selected-ui` which is gray 70 hover in G90 theme

| White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
| --- | --- | --- | --- |
| gray-20 hover `#cacaca` | gray-20 hover `#cacaca` | gray-70 hover `#656565` | gray-80 hover `#4c4c4c` |

Current: 

![image](https://user-images.githubusercontent.com/15144993/60298467-34633280-98f0-11e9-8617-b68c1d58e7a5.png)

Should be: 

![image](https://user-images.githubusercontent.com/15144993/60298857-0af6d680-98f1-11e9-9f52-4118c7f732e4.png)

![image](https://user-images.githubusercontent.com/15144993/60298837-fe727e00-98f0-11e9-8c44-cd1126d10f8d.png)

#### 2. Overflow menu not using correct theme

For token spec, reference : https://github.com/carbon-design-system/carbon/issues/3213

Current:

![image](https://user-images.githubusercontent.com/15144993/60298892-1e09a680-98f1-11e9-8bb4-35a9be9a5807.png)

Should be: 

![image](https://user-images.githubusercontent.com/15144993/60298935-34176700-98f1-11e9-87fc-c7e6c76ac9d0.png)

#### 3. Setting (dependent on overflow?) menu is not getting the token assignment too

![image](https://user-images.githubusercontent.com/15144993/60299829-3f6b9200-98f3-11e9-818f-3e1b2893d5c7.png)

**Comment by asudoh** [comment]
1. The latest `master` has border on header row removed unless sticky header feature is enabled
2. Updating zebra color requires component-specific theme token (CC @emyarod), applying alpha channel to theme token (CSS custom properties) is hacky
3. #4270 fixes the color of overflow menu's trigger button and #3444 fixes the color of overflow menu body

@aagonzales Wrt 1. does it (the current behavior in `master`) sound good? Wrt 2., should we track the issue separately? Thanks!

**Comment by tw15egan** [comment]
Closing this as most of the issues have been fixed, and the zebra style fixes are being tracked in https://github.com/carbon-design-system/carbon/issues/3143
