### ISSUE TITLE
[DatePicker] Manually entering date does not update month in calendar

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#3212]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When manually typing a date in a `DatePickerInput`, pressing the <kbd>Enter</kbd> updates the year and day on the calendar UI, but the month does not change.

> Is this issue related to a specific component?
Yes the `DatePicker` component

> What did you expect to happen? What happened instead? What would you like to
> see changed?
When manually typing a date in a `DatePickerInput`, the `DatePicker` requires that user presses the <kbd>Enter</kbd> key for it to register the new date, display it on the calendar UI, and call the `onChange` event. Pressing the <kbd>Enter</kbd> updates the year and day on the calendar UI, but the month does not change.
It is expected that the month is also updated. 

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
`carbon-components-react@7.3.2`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Security Connect

## Steps to reproduce the issue

1. Go to the DatePicker single with calendar [story](http://react.carbondesignsystem.com/?path=/story/datepicker--single-with-calendar)
2. Type a valid date value so the month, day, and year numbers are different from today
3. Press <kbd>Enter</kbd>
4. Notice that the calendar updates the day and year, but not the month

## Additional information
![Kapture 2019-06-27 at 14 54 09](https://user-images.githubusercontent.com/5973294/60296323-79389a80-98eb-11e9-9e1a-cf008dd9daed.gif)

**Comment by lovemecomputer** [comment]
looking into this! at first glance it looks like the date is changing (the days in the month update properly), but the text displayed in the header is not updated. thanks for the super clear bug reporting!

**Comment by nilooy** [comment]
is this issue still exist? I'm facing the same issue. When i enter the date manually, calendar doesn't update.I used **onInput** to listen for the change because **onChange** is not updating the state as well

**Comment by asudoh** [comment]
Hi 👋 is #5855 close to what you are saying?
