### ISSUE TITLE
[Overflow] dark themes fail. styling not using tokens

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3213]
It appears our overflow menu is not changing colors when switched to dark theme. 

Current:

![image](https://user-images.githubusercontent.com/15144993/60299303-07178400-98f2-11e9-95a2-6e5cfd748bc8.png)

Should be: 

![image](https://user-images.githubusercontent.com/15144993/60299498-78573700-98f2-11e9-877a-546c2c20fcca.png)

### Correct token assignment is documented on website: 
https://www.carbondesignsystem.com/components/overflow-menu/style

![image](https://user-images.githubusercontent.com/15144993/60299410-4219b780-98f2-11e9-9c70-3be0834d215f.png)

**Comment by abbeyhrt** [comment]
Looks like this has been addressed!
