### ISSUE TITLE
WarningFilled16 React does not recognize the `dataIconPath` warning

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon#3234]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the WarningFilled16 component, a warning is shown in the console: 
React does not recognize the `dataIconPath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataiconpath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

This also occurs in the NumberInput component as it also uses the WarningFilled16 component.

> Is this issue related to a specific component?

WarningFilled16 is the perpetrator, but NumberInput also uses the WarningFilled16 which is where I am seeing the error

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I did not expect to get a warning when using the WarningFilled16 or NumberInput component. The full warning is:
```
Warning: React does not recognize the `dataIconPath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataiconpath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in path (created by WarningFilled16)
    in svg (created by WarningFilled16)
    in WarningFilled16 (at SurveySelectView.jsx:79)
    in div (created by Container)
    in Container (at SurveySelectView.jsx:78)
    in SurveySelectView (at ViewController.jsx:39)
    in div (at ViewController.jsx:35)
    in ViewController (created by Context.Consumer)
    in Route (at DashboardPage.jsx:28)
    in Switch (at DashboardPage.jsx:27)
    in main (created by Content)
    in Content (at DashboardPage.jsx:26)
    in div (at DashboardPage.jsx:20)
    in DashboardPage (at App.jsx:40)
    in Route (at App.jsx:34)
    in DashboardRoute (at App.jsx:77)
    in Switch (at App.jsx:74)
    in div (at App.jsx:73)
    in App (at src/index.js:18)
    in Router (created by HashRouter)
    in HashRouter (at src/index.js:17)
    in Provider (at src/index.js:16)
```

> What browser are you working in?

Mozilla Firefox

> What version of the Carbon Design System are you using?

10.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Survey Tool in z Systems. This is not a pressing issue for my project

## Steps to reproduce the issue

1. `import WarningFilled16 from '@carbon/icons-react/es/warning--filled/16';`

2. 
```
return (
    <div>
      <WarningFilled16 />
    </div>
  );
```

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi @sstone2423! It seems like you may be using an older version that has this issue present. What specific versions of each package are you using? When using latest versions, this issue seems to have been resolved: https://codesandbox.io/s/summer-dream-eym51

**Comment by sstone2423** [comment]
Hello! I am using 
```
"carbon-components": "^10.3.2",
"carbon-components-react": "^7.3.2"
```
according to my package.json.

**Comment by joshblack** [comment]
Thanks! Would you mind sharing a codesandbox that reproduces the issue then? Will definitely take a look 👀

**Comment by sstone2423** [comment]
Scratch that. Didn't have my icons updated. I'm no longer getting the warning. Thanks!
