### ISSUE TITLE
Is the search component binded to some search algorithm behind?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3238]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I can filter my list by writing some search based on regular expression but it will be primitive.
Is the search component binded to some search algorithm behind? If not will search for such a one and fire it with onChange event of the search field I guess.

**Comment by asudoh** [comment]
@zbeedatm Thank you for asking! The answer is no, the search component focuses on search UI, instead of search logic. Your application can detect change in user input in the UI and do the search for the application.
