### ISSUE TITLE
yarn build failing on fork of repo

### ISSUE THREAD

**Issue by hshockley** [carbon-design-system/carbon#3243]
## What package(s) are you using?

- [x] `carbon-components`

## Summary
yarn build spits out the following error after cloning and running yarn install on a fork of the monorepo.

![2019-07-01 14_26_17-Window](https://user-images.githubusercontent.com/30321326/60458575-fd04c680-9c0c-11e9-9b31-8565a526da03.png)

Is there a step that I am missing in the setup of the monorepo?

**Comment by emyarod** [comment]
looks like you are on Windows right? possibly related #2434

**Comment by hshockley** [comment]
Yeah, on Windows. Any ETA on the PR to fix this then?

**Comment by joshblack** [comment]
Hey @hshockley! 👋 We aren't currently working on addressing the issues in Windows, but would love any help to get it working there. I believe @emyarod was hoping to tackle it in our next project cycle, but if you have any knowledge or expertise in the meantime to help out that would be greatly appreciated!

When evaluating this initially, it seems like how we are doing paths is not platform-agnostic, and so we would need to update things to support filesystem patterns for Windows/Mac/Linux.

**Comment by emyarod** [comment]
just made some updates to https://github.com/carbon-design-system/carbon/pull/2453, would like some additional testing

**Comment by emyarod** [comment]
@hshockley have you had a chance to check out the fixes made in #2453? it seems to hang (with no errors) when building `icons-angular`, but the errors that occur prior to building `icons-angular` should be resolved

**Comment by hshockley** [comment]
@emyarod I was able to check out the fixes and I am getting the same behavior. I took a look in icons-angular for any places where .replace was used but did not find any. My guess is that it might have something to do with how the paths are written in `fs.writeFile(`. Not 100% sure though.

**Comment by emyarod** [comment]
@hshockley thanks for confirming! I will dig around the `icons-angular` codebase and see what's going on. I want to make this a priority for our next release (10.5) now that we're wrapping up 10.4

**Comment by joshblack** [comment]
Hey all! :wave: We've just recently merged in more support for building on Windows, I believe it will help to address this so definitely give it a shot! If not, feel free to comment again and I can re-open this!
