### ISSUE TITLE
Sass themes mixin default value not being overwritten

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon#3246]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> When using the `carbon--theme` mixin, theme styles are not being overwritten as expected. So the directions found on the Carbon site are not working. 

>Not working

![image](https://user-images.githubusercontent.com/1590966/60467032-67c0fc80-9c23-11e9-98e1-24b45dbfa37c.png)

but works if you overwrite the value for the default variable and call the mixin with no argument like so:

>this works

![image](https://user-images.githubusercontent.com/1590966/60467094-93dc7d80-9c23-11e9-9e07-2e17fee7cd87.png)

I believe this may stem from using a variable as the default value that is not defined in the file where the mixin is defined. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see theme applied by using the mixin with argument and it was not. I would like to see the mixin use the value passed as an argument. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

**Comment by joshblack** [comment]
Good catch @davidicus! Thanks so much for reporting this. Thinking about this now, it does feel like we should update the documentation as it suggests that the mixin is overriding that global `$carbon--theme` variable. Would you agree?

**Comment by davidicus** [comment]
Agreed. It does sound that way.

**Comment by elizabethsjudd** [comment]
I'm running in to issues with themes as well, see this slack conversation: https://ibm-front-end.slack.com/archives/C046Y0YUD/p1562005131241900

**Comment by joshblack** [comment]
Should be updated in our docs over at: https://www.carbondesignsystem.com/guidelines/themes#default-theme let us know if you would expect it documented elsewhere!
