### ISSUE TITLE
docs: Reference Link Issue

### ISSUE THREAD

**Issue by virkt25** [carbon-design-system/carbon#325]
## Detailed description

Answer for this question: http://www.carbondesignsystem.com/getting-started/FAQ#q4

has a link to `angular-carbon-components` which is an internal link not accessible by the public and neither is the project itself.

**Comment by tay-aitken** [comment]
Hi @virkt25, yes that link is for our internal users only. We will update the copy to make that more clear. Thank you for letting us know.

**Comment by tay-aitken** [comment]
This issue is fixed in [PR #76]( https://github.com/carbon-design-system/design-system-website/pull/76)
