### ISSUE TITLE
NumberInput: When nesting in Form component, enter a floating point number, then press the Enter key will get an error hint.

### ISSUE THREAD

**Issue by uboa3774** [carbon-design-system/carbon#3251]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When the NumberInput component is nested in the Form and it has a required attribute, enter a floating point number and press the Enter key, there will get an error hint reminding me to enter an integer.

> Is this issue related to a specific component?

Form NumberInput

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I hope NumberInput can support floating point number input in this case.

> What browser are you working in?

Chrome  75.0.3770.100

> What version of the Carbon Design System are you using?

v10.2.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Nest the NumberInput in Form, and set the required attribute.
2. Enter a floating point number.
3. Press the enter key.

> Please create a reduced test case in CodeSandbox
>
> - React:
>   https://codesandbox.io/s/codesandbox-wd3vn

## Additional information

- Screenshots 
![image](https://user-images.githubusercontent.com/26167094/60477385-9f768580-9cb1-11e9-9fa1-7b89682367de.png)

- I noticed when the NumberInput is created, the input tag will have a pattern attribute to limit the type of value is an integer. In this case, I could create another component to support the floating point, but I also hope we could have a prop to set the type of number.

**Comment by asudoh** [comment]
Hi 👋 you can override `pattern` as well as `step` props to achieve what you want. You may need to track `onChange` to cope with precision error in JavaScript number and adjust the value, though.
