### ISSUE TITLE
AVT 2 (webkit) - React Transactional Modal & Input Modal -  Keyboard users can't scroll content 

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon#3261]
## Environment
macOS Mojave version 10.14.5
Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React

## Detailed Description
Tab to the Launch Modal button 
Arrow keys do not scroll the content

**Comment by elizabethsjudd** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/3196.  I can contribute the change to the Vanilla version but we need @carbon-design-system/design input for focus styles.

**Comment by emyarod** [comment]
unless I am misunderstanding, I'm not able to reproduce #3196 or the current issue. I can change focus to the overflowing content container and scroll using arrow keys for both vanilla and React **on Firefox 69

edit: actually this may be browser dependent, seems to be present in Chromium browsers

**Comment by aagonzales** [comment]
I think it would just get our standard focus style, 2px outline with `$focus` color token. 

![image](https://user-images.githubusercontent.com/11670886/60550112-83440a00-9cec-11e9-82ff-6cf782f6116f.png)

**Comment by snidersd** [comment]
@emyarod FYI... I just retested React, and see the issue in Chrome and Safari, but it is not present with Firefox Quantum.

**Comment by emyarod** [comment]
@snidersd yep it seems to be present only in webkit browsers

**Comment by elizabethsjudd** [comment]
not stale. I'll be working on the vanilla implementation hopefully next week.  Waiting to hear back from carbon developers to the questions in the vanilla issue
