### ISSUE TITLE
June/July 2019 Endgame

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3262]
This is the endgame schedule for our June/July 2019 iteration, which includes the following projects:

- [Component Enhancements](https://github.com/carbon-design-system/carbon/issues/2963)
- [Icons](https://github.com/carbon-design-system/carbon/issues/2970)
- [UI Shell](https://github.com/carbon-design-system/carbon/issues/2972)
- [Support](https://github.com/carbon-design-system/carbon/issues/2974)
- [Component Architecture](https://github.com/carbon-design-system/carbon/issues/2976)
- [Contribution](https://github.com/carbon-design-system/carbon/issues/2977)
- [Theming](https://github.com/carbon-design-system/carbon/issues/2978)

## Schedule

- Endgame leader: @joshblack 
- Endgame partners: @designertyler (design) @jnm2377 (dev)
- 07/09: Code freeze for projects cutting release (EOD)
- 07/12: Endgame done
- 07/15: Expected release date

### Monday 07/08

- [x] Coordinate delivery or resolution of the following items:
  - [x] Component Enhancements
    - [ ] ~https://github.com/carbon-design-system/carbon/pull/3175~
    - [ ] ~https://github.com/carbon-design-system/carbon/pull/3124~
    - [ ] ~https://github.com/carbon-design-system/carbon/pull/3054~
  - [x] Icons
    - [x] https://github.com/carbon-design-system/carbon/pull/3307
    - [x] https://github.com/carbon-design-system/carbon/pull/3308
  - [x] UI Shell
    - [ ] ~https://github.com/carbon-design-system/carbon/issues/3001~
  - [x] Support
    - [ ] ~https://github.com/carbon-design-system/carbon-website/issues/1754~
  - [x] Spec
    - Spec work is exploratory and not tied into the endgame
  - [x] Contribution
  - [x] Theming

### Tuesday 07/09

- [x] Code freeze for release by **5pm CST**
- [x] First Release Candidate cut

### Wednesday 07/10

- [ ] Manual verification of Release Candidate Package (repeated after each RC)
  - [x] Smoke tests
  - [x] Insider tests
  - [x] Deploy updates to website through staging PR
  - [ ] Deploy staging environments for docs sites
    - [ ] Storybook

### Thursday 07/11

- [x] Collect feedback from Insider tests
- [x] If hotfixes have been made, cut third release
- [x] Release demo

### Friday 07/12

This is the last chance for hotfixes, no additional functionality may be included

- [x] Make go/no-go call on release
- [x] Collect list of changes and draft initial changelog
- [x] If hotfixes have been made, cut final release
- [ ] ~Get site working with latest Release Candidate~
- [ ] ~Get Gatsby Theme working with latest Release Candidate~
- [x] Push kit updates

### Monday 07/15

- [x] Get site working with latest Release Candidate
- [x] Get Gatsby Theme working with latest Release Candidate
- [ ] Finalize changelog for all packages
- [ ] ~Promote latest RC candidate to stable, release `v10.X.0`~
- [ ] ~Twitter announcement~
- [ ] ~Slack announcement~

### Tuesday 07/16

- [ ] Promote latest RC candidate to stable, release `v10.X.0`
- [ ] Twitter announcement
- [ ] Slack announcement

**Comment by joshblack** [comment]
```
Successfully published:
 - browserslist-config-carbon@10.4.0-rc.0
 - @carbon/bundler@10.3.0-rc.0
 - @carbon/cli-reporter@10.3.0-rc.0
 - @carbon/cli@10.4.0-rc.0
 - @carbon/colors@10.3.0-rc.0
 - carbon-components@10.4.0-rc.0
 - @carbon/elements@10.4.0-rc.0
 - @carbon/grid@10.4.0-rc.0
 - @carbon/icon-helpers@10.3.0-rc.0
 - @carbon/icons-angular@10.4.0-rc.0
 - @carbon/icons-handlebars@10.4.0-rc.0
 - @carbon/icons-react@10.4.0-rc.0
 - @carbon/icons-vue@10.4.0-rc.0
 - @carbon/icons@10.4.0-rc.0
 - @carbon/import-once@10.3.0-rc.0
 - @carbon/layout@10.3.0-rc.0
 - @carbon/motion@10.3.0-rc.0
 - carbon-components-react@7.4.0-rc.0
 - @carbon/test-utils@10.3.0-rc.0
 - @carbon/themes@10.4.0-rc.0
 - @carbon/type@10.3.0-rc.0
 - @carbon/upgrade@10.4.0-rc.0
```

**Comment by aagonzales** [comment]
### 10.4 Kit updates:

**Bugs:**
- Icon button: added disabled state [#121](https://github.com/carbon-design-system/carbon-design-kit/issues/121)
- Dropdown: 
    - overrides enabled [#125](https://github.com/carbon-design-system/carbon-design-kit/issues/125)
    - drop-shadow background color fix (G90 and G100 theme) [#127](https://github.com/carbon-design-system/carbon-design-kit/issues/127)
- Checkbox: missing indeterminate state (G90 and G100 theme) [#128](https://github.com/carbon-design-system/carbon-design-kit/issues/127)
- Data table: 
    - Corrected pinning in icon symbols (G10 theme) [#129](https://github.com/carbon-design-system/carbon-design-kit/issues/129)
- Overflow menu: duplicated symbols removed (G100 theme) [#137](https://github.com/carbon-design-system/carbon-design-kit/issues/137) 
- Skeleton states: updated to use new tokens [#138](https://github.com/carbon-design-system/carbon-design-kit/issues/138)
- Tooltip: re-organized symbol structure [#140](https://github.com/carbon-design-system/carbon-design-kit/issues/140)
- Pagination: updated symbol structure for standalone variation, add number states [#130](https://github.com/carbon-design-system/carbon-design-kit/issues/130)

**Enhancements:**
- Modal: added footer symbol and single action option [#116](https://github.com/carbon-design-system/carbon-design-kit/issues/116)
- Progress indicator: added vertical variation [#123](https://github.com/carbon-design-system/carbon-design-kit/issues/123)
- Color tokens: added [#138](https://github.com/carbon-design-system/carbon-design-kit/issues/138) 
    - hover-selected-ui
    - skeleton-01
    - skeleton-02
    - inverse-support-01
    - inverse-support-02
    - inverse-support-03
    - inverse-support-04
- Text style: added "body-short-02/text-03" [#136](https://github.com/carbon-design-system/carbon-design-kit/issues/136)

**New:**
- UI Shell templates
- UI Shell rail component

**Comment by mattrosno** [comment]
### Theming updates:

Enhancements:

- Added color theme dropdown in vanilla development environment (https://the-carbon-components.netlify.com) https://github.com/carbon-design-system/carbon/pull/3073
- Updated theming sandbox with v10 components and color themes (http://themes.carbondesignsystem.com)

Fixes:

- Button disabled state background color in dark themes
- Ghost button text/icon colors in dark themes
- Danger button border color in dark themes
- Disabled checkbox to show check in dark themes
- Content switcher to use `$disabled-0*` color tokens for dark themes
- Inline dropdown background and disabled colors in dark themes
- Skeleton color tokens to work in all themes
- Theme `$highlight` token in dark themes
- Theme `$hover-primary-text` token in dark themes
- Theme `$hover-ui` token in g90 theme

Features:

- Emit custom properties for `@carbon/themes` color tokens

**Comment by joshblack** [comment]
## Icons

### Bug fixes 🐛 

- The following icons have been tweaked
  - battery--low.svg
  - ibm-security.svg
  - logo--slack.svg
  - logout.svg
  - mobile--add.svg
  - mobile--check.svg
  - mobile--download.svg
  - mobile.svg
  - popup.svg
  - text--strikethrough.svg
  - mammogram.svg

### Enhancements 🛠 

- Bespoke icons added at the following sizes:
  - 20/time.svg
- `@carbon/icons-react` now supports an entrypoint `index.js`, you no longer are required to specify the path for an icon

### New ✨ 

- Support for the following icons:
  - language.svg
  - laptop.svg
  - account.svg
  - branch.svg
  - enterprise.svg
  - fog.svg
  - help-desk.svg
  - no-image.svg
  - no-ticket.svg
  - pause--filled.svg
  - play--filled--alt.svg
  - service-desk.svg
  - skip--back--filled.svg
  - skip--forward--filled.svg
  - stop--filled--alt.svg
  - audio-console.svg
  - battery--empty.svg
  - battery--quarter.svg
  - carbon.svg
  - category--add.svg
  - category--and.svg
  - category--new-each.svg
  - category--new.svg
  - category.svg
  - concept.svg
  - fork.svg
  - hurricane.svg
  - mobile--landscape.svg
  - partly-cloudy.svg
  - sunny.svg
  - sunset.svg
  - tablet--landscape.svg
  - tablet.svg
  - term.svg
  - text-link--analysis.svg
  - text-link.svg
  - text-mining--applier.svg
  - text-mining.svg
  - tree-view--alt.svg
  - type-pattern.svg
  - types.svg

### Removed ☠️ 

- The following icons have been removed:
  - mammogram--stacked.svg

**Comment by designertyler** [comment]
### UI Shell

**New**
- Guidance for UI Shell Navigation patterns
- UI Shell Sketch template and symbols added to the Sketch kit.
- Rail functionality for UI shell left panel.
- Responsive behavior for the header with nav links.

**Comment by jnm2377** [comment]
## Support / Bug fixes

**Notable fixes**

#2885 - Make toggle labels accessible
#2923 - Change tooltip content width
#2936 - New class for ListBoxSelection
#3112 - Fix overflow menu and modal failing tests
#3139 - ListBox a11y violation fixes
#3230 - Support "light" search bar

**Comment by emyarod** [comment]
## Support and enhancements

## notable fixes and enhancements
* add icon-only button to React library (#3368)
* inline-notification action button with click handler (#3283)
* `<Search>` component `light` variant
* DatePicker `onClose` handler (#3300)
* support CSS class on `body` when using modals (#3237)
* data table merge sticky header style (#2965)
* apply persistent styles to data table (#3311)
* fix data table clear input button functionality (#3285)
* reset expand button height in short table (#3057)

We also have some major a11y updates for our components with much help from the community

## a11y fixes and updates
* overflow menu html a11y updates (#3181)
* definition tooltip WCAG 2.1 compliance (#3151)
* interactive tooltip html updates for a11y (#3148)
* make toggle labels accessible (#2885)
* fix overflow menu icon color for danger items (#3147)
* address ListBox DAP violations (#3139)
* set tooltip width to content max (#2923)
* require modal ARIA attributes (#2851)
* require default ARIA attribute knob values for slider (#3064)
* add roles to tag list and wrap in container (#3017)

and more which can be found in the full changelog
