### ISSUE TITLE
Separate the Interactive Tooltip component from the info icon

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#3277]
### Summary

Similar to the request in #1903 there are use cases for wanting an interactive tooltip component, without necessarily wanting it tied to an info icon.

### Justification
Current component in the Carbon v10 library: 
![image](https://user-images.githubusercontent.com/6569324/60601760-402f7880-9d78-11e9-8bf4-e76ef13e6e80.png)

My request is to provide it without the info icon by default. 
![image](https://user-images.githubusercontent.com/6569324/60601813-550c0c00-9d78-11e9-9493-537d8647f80f.png)

It's true that in the meantime it's relatively simple to just override the icon to make it disappear. But my argument is that the proposed use case for the interactive tooltip component is too narrow. It's beig thought of as just "The thing which appears when you click an info icon" when the use cases are really much broader. 
For example a feature tour similar to what is shown here would be possible to support with the interactive tooltip component
![image](https://user-images.githubusercontent.com/6569324/60601450-c13a4000-9d77-11e9-86e4-1b9a0fda944a.png)

Carbon should think of the component in a broader way - of providing guidance throughout the UI in a progressive way, rather than solely about the information icon behaviour. In that way, it encourages designers to use it in a wider array of ways and gives more flexibility and freedom. 

### Desired UX and success metrics
Ideally this would be provided both in the Sketch library, and in the code libraries. 

### "Must have" functionality
Make available in the sketch library an interactive  tooltip component which doesn't have an information icon associated with it by default.

### Specific timeline issues / requests
No timeline. It's possible to override the icon in the meantime to remove it, so there is a simple workarround. But  I think there is a philosophical point here about if the interactive tooltip is only triggered from clicking an icon - if the info icon is the primary use case, of if Carbon should be thinking  of the components in a more flexible, use case agnostic, way.

**Comment by asudoh** [comment]
The screenshot seems to largely diverge away from our UX pattern of our interactive tooltip. I'd suggest just take the markup/styles of our interactive tooltip and implement show/hide logic by your own. In most cases it can be implemented by some additional CSS. For some edge cases we have a primitive called "floating menu".
