### ISSUE TITLE
How to use white carbon-icons?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3278]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I was using carbon-icons on top of white header of my page, then I switched to black header and now need white icons.

I noticed that when using the icons as part of the renderIcon property of Button, it's rendered as white if the color property inside the button className is configured to white.

But if locating the icon without a button (to avoid hover), then it's not.

**Comment by emyarod** [comment]
you should be able to style the icons with CSS. can you create a [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) that shows the issue?

**Comment by zbeedatm** [comment]
https://codesandbox.io/s/codesandbox-gypl7

**Comment by abbeyhrt** [comment]
Using the code sandbox you gave, here's one way to style the icons' color. Give a class name to the element that is rendering the icon and then target the svg in css and use the fill property, instead of the color property, to set the icon color to be whatever you want! I hope this helps! https://codesandbox.io/s/codesandbox-shten?fontsize=14

**Comment by zbeedatm** [comment]
Thanks.
I added the following:

.rendered-icon svg {
  fill: white;
}

.rendered-icon:hover {
  background-color: black;
}

to get rid of the gray background when hovering the menu arrow, but still need to handle it after it's clicked as well.

**Comment by emyarod** [comment]
you can target the `.bx--overflow-menu:hover` selector for styling the overflow menu trigger button on hover
