### ISSUE TITLE
Inline Notification: add secondary action button

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#3282]
### Summary

We'd like to add an "action" button to the `InlineNotification` component, like this:

![Screen Shot 2019-07-03 at 3 14 47 PM](https://user-images.githubusercontent.com/9057921/60622207-530c7200-9da5-11e9-993f-e61ee47f7838.png)

### Justification

In our product, there are situations where we want to provide an action to our users when a notification comes up.

### "Must have" functionality

- Button label text prop
- Click handler for the action button

### Specific timeline issues / requests

ASAP 😅 

### Available extra resources

I can help!
I have a suggested way to do this & will submit a PR for feedback shortly.

**Comment by asudoh** [comment]
Hi 👋 I think it'll depend on the design @carbon-design-system/design would give you, but my suggestion is simply adding `actions` prop with `PropTypes.node`. In this way you can add any content you want as the action buttons. (An alternative is `children`, though it's placed in an undesirable place for an action button)
