### ISSUE TITLE
v9 to v10: Color is deprecated, causing compilation errors

### ISSUE THREAD

**Issue by David-Choksi** [carbon-design-system/carbon#3291]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Summary
We're migrating from V9 to V10 and are following the migration guide. However, it doesn’t say what to do if you’re using a color that is deprecated, for example `color__navy-gray-*`, which we use in a few places, and are now getting compilation errors since the color doesn’t exist.

What do we do here? Is there a fix or workaround? Also, is there documentation on v9 to v10 for color changes? I’ve only found this https://github.com/carbon-design-system/carbon/blob/master/docs/migration/10.x-color.md

Is there anymore documentation or links? And any other links that may help for migrating, aside from the official v9 to v10 guide, would be appreciated, as we're bound to encounter more issues.

**Comment by asudoh** [comment]
https://github.com/carbon-design-system/carbon/blob/master/docs/migration/10.x-color.md#color-variables seems to show that there is no migration path for your specific color. I wish there had been some guidance for such deprecated colors, but I recall of two ways we have done in `v10` component work - One is working with designers on alternate colors, another is just searching for a close color. Hope this helps!

**Comment by David-Choksi** [comment]
Thanks @asudoh, appreciate the help.
