### ISSUE TITLE
Click of search icon in Search component should have a function associated with it

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon#3310]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
There is no function associated with the search icon in the component. The user should have an option to click on the search icon as well and have a function associated with it

> Is this issue related to a specific component?
Search component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?
6.115.4

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
I don't believe the icon is meant to be a button but I may be mistaken, cc @carbon-design-system/design

**Comment by laurenmrice** [comment]
yes, the search icon is not meant to be a button. you can press enter to search.

**Comment by asudoh** [comment]
Just wondering - Is this request similar to #3489?

**Comment by chrisconnors-ibm** [comment]
@laurenmrice I understand that it wasn't specified to behave as a button, but is there any reason we couldn't have it behave that way too? ie a if a submit is required, submit happens on enter key _or_ clicking the magnifying glass?

Historically the enter key submit was meant as a shortcut for the primary button event - the "Search" or "Enter" or "Go" that triggered the submit.

**Comment by tw15egan** [comment]
FWIW [Google](https://www.google.com/) doesn't have any click events on the search icon either

**Comment by chrisconnors-ibm** [comment]
I know, but at least in Firefox their web search field doesn’t even retain focus as you enter the search string, it bounces focus up to the url bar. 

But I’d still say, is there anything preventing the search icon in the field from taking a click event and sending a submit?

**Comment by tw15egan** [comment]
There is nothing hooked up to it currently, but it could be added if we wanted to. Right now it is just rendering a search icon with `pointer-events: none` so we are specifically disabling click events.

**Comment by jeanservaas** [comment]
I think @asudoh is right in that this relates to #3489 

We originally had two alternate specs for search in our master file, one with the icon on the left, in which it was not a button and one on the right where the search icon was intended to take a click event and act like a button. The two designs may of had something to do with whether a user was implementing type-ahead functionality or not.

The only weird thing about having it operate as a button now is that it's not very intuitive to have the search button to the left of the search terms in the field.

**Comment by chrisconnors-ibm** [comment]
@jeanservaas can we clarify both the icon placement and functionality in a specification? 

Keyboard enter (or any shortcuts) are meant to accelerate on screen calls to action (even though GOOG and others have moved to a model where enter is the presumed action). If the icon is on the right in certain circumstances, we should clarify when and why, and in that case, clicking on the icon should be the same as hitting 'enter'.

**Comment by arnajdas1992** [comment]
Any final decision on this?

**Comment by arnajdas1992** [comment]
Any final decision on this?

**Comment by chrisconnors-ibm** [comment]
After reviewing this with the team we are not going to pursue this.
1) our icon is on the left side of the entry field.
2) many of our searches don’t even require a submit (per char search)
3) in the case of our website header search or the table search, clicking the magnifying glass exposes the search input, so having it do something different when the search is active adds inconsistency

**Comment by kalai001** [comment]
If the search icon is just rendered as a place holder, it has to disappear when the user focuses on it (like the text placeholders disappear on focus). Having a search icon which doesn't respond on click creates a confusion. We already have customers reported it thrice.

Can we have one of these as a solution?
1. Handle click on the search icon, treat is same as enter action
2. Hide the icon on focus, so that user would have a clue that some action has to be done. Enter would be the natural choice.

**Comment by chrisconnors-ibm** [comment]
>Having a search icon which doesn't respond on click creates a confusion. **We already have customers reported it thrice.**

Can you provide some additional detail here?

This assumes a user has entered a term and clicks an icon to the left of the term, which doesn't seem to be either a common pattern or behavior. The world most used search UI (google.com) does not have either of the proposed behaviors.
![search](https://user-images.githubusercontent.com/35537391/67716818-dd0ac700-f9a2-11e9-9f57-37f4bc3d612f.gif)

**Comment by kalai001** [comment]
@chrisconnors-ibm , 
In your sample, the icon is on the left, unlike the Carbon search bar, where the icon is at the right.

The general pattern that I have seen on the search bars is.
- Left most - a suggestive icon, like a label to text field (optional)
- Center - area to enter search text
- Right most - clickable icon with hover message

Below are samples, including Google

**Firefox home page:**
![image](https://user-images.githubusercontent.com/46040341/69048986-d3fe9a00-0a24-11ea-8b80-790276a8035a.png)

**Google search:**
![image](https://user-images.githubusercontent.com/46040341/69049007-de209880-0a24-11ea-80b2-6c7323f5d106.png)

**Comment by chrisconnors-ibm** [comment]
[Component Icon](https://www.carbondesignsystem.com/components/search/code) is on the left:
![image](https://user-images.githubusercontent.com/35537391/69068863-83227d80-09f3-11ea-9813-32e9c0f0a277.png)

Header component is on the left: 
![image](https://user-images.githubusercontent.com/35537391/69068955-ab11e100-09f3-11ea-8d89-eb83c5402931.png)

**Comment by chrisconnors-ibm** [comment]
[google.com](https://www.google.com/) does not have a clickable icon button on the right that submits: 
![image](https://user-images.githubusercontent.com/35537391/69069256-2bd0dd00-09f4-11ea-8489-20eba590c2ef.png)

…but their results page does, so that's a push. 
![image](https://user-images.githubusercontent.com/35537391/69069394-6175c600-09f4-11ea-8636-0f0b0bffc02b.png)

**Comment by chrisconnors-ibm** [comment]
>In your sample, the icon is on the left, unlike the Carbon search bar, where the icon is at the right.

@kalai001 can you show us where you are encountering this?

**Comment by kalai001** [comment]
@chrisconnors-ibm , Below is the screen capture of the Search component with search icon to the right. But I do see from the carbon components page (http://react.carbondesignsystem.com/?path=/story/search--default) that its on the left. Let me investigate the difference further and get back.

**From our product:**
![image](https://user-images.githubusercontent.com/46040341/69078792-a6cedd80-0a5e-11ea-9692-f27c92ba6cbc.png)

**Comment by chrisconnors-ibm** [comment]
Our components have the desired and expected behavior.
