### ISSUE TITLE
Tag filter doesn't honor type knob

### ISSUE THREAD

**Issue by xpander53** [carbon-design-system/carbon#3318]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

type is not being honor on a filter (tag variant)

> Is this issue related to a specific component?

Yes the Tag component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect the color to change to the color I picked. For example "gray"

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "^10.3.0",
"carbon-components-react": "^7.2.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson for Clinical Trial Matching

## Steps to reproduce the issue

Change the type knob and see it works for Tab but NOT for the filter variant.
http://react.carbondesignsystem.com/?path=/story/tag--filter

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
not sure if we support different colored filter tags, but if we want to add support for that we'll need hover and focus color tokens for the close button background

**Comment by xpander53** [comment]
The story book for filter shows support for color.
http://react.carbondesignsystem.com/?path=/story/tag--filter

**Comment by emyarod** [comment]
yeah it can be unintended, in which case the storybook knob would just be removed

**Comment by elizabethsjudd** [comment]
@emyarod I know WH is in the process of creating an issue to support interactive tags in all of the colors for tags. It's common that tags can be used as a button or link (e.g. tag clouds, labels in GH, etc) so our issue will provide hover, focus, and disabled states for each individual color.

**Comment by emyarod** [comment]
cool, once we are aligned on spec I can resolve this issue. just need confirmation from design about those tokens

refs https://github.com/carbon-design-system/carbon/pull/2129

**Comment by xpander53** [comment]
Bump - still valid

**Comment by xpander53** [comment]
Bump - still valid. Just because this isn't fixed in a couple of weeks doesn't make it not valid. My team needs this fixed.

**Comment by xpander53** [comment]
@emyarod Can you reopen this defect or should I open a new issue with the same issue?

**Comment by xpander53** [comment]
@emyarod Thanks!

**Comment by emyarod** [comment]
got confirmation from design that this is a desired feature, awaiting updated spec

**Comment by laurenmrice** [comment]
Yes, we definitely want this feature for Filterable Tag. Design currently has the specs for the background and text/icon color. But we currently are still working on values for the hover colors on the icon.

**Comment by janhassel** [comment]
Hey, just wanted to check on the status of this one since we are facing the same issue.

@laurenmrice What do you think about a temporary solution where we say the hover color is always the next darker (or lighter) step of the respective color. So if the tag is teal and therefore using Teal20 as the background color, the hover would be Teal 30.
And then once the design team has created the hover values for the colors, we can change them.

**Comment by janhassel** [comment]
Still relevant

**Comment by xpander53** [comment]
Still relevant

**Comment by janhassel** [comment]
Are there any updates on this one?

It is crucial for us and at least a temporary solution like I described here: https://github.com/carbon-design-system/carbon/issues/3318#issuecomment-553808398 would already help us a lot.

**Comment by emyarod** [comment]
currently still awaiting finalized spec from design

**Comment by laurenmrice** [comment]
Sadek and Vince are currently working on a solution for this, but I am not sure what the timeline is for it. We still do need the filterable tag color options in react though.

I think we can go ahead with Jans temporary solution of stepping the hover down one grade for the light themes (ex: Gray 30) and stepping the hover up one grade for the dark themes (Ex: Gray 70) and then we can change it once we have Sadek and Vinces solution (hopefully soon).

**Comment by emyarod** [comment]
may be related https://github.com/carbon-design-system/carbon/pull/5269

**Comment by vpicone** [comment]
@emyarod that issue is only for interactive tokens, it isn't used to generate a hover color for every color token we have. The same tool could be used to generate those values though maybe.

**Comment by janhassel** [comment]
I opened a PR implementing the temporary solution described earlier in this issue: #5382

**Comment by janhassel** [comment]
@emyarod Do you think this issue can be closed now since #5382 is merged or should it remain open to track the long-term solution @laurenmrice [mentioned](https://github.com/carbon-design-system/carbon/issues/3318#issuecomment-584341167)?

**Comment by laurenmrice** [comment]
This can be closed, I can make a new issue to transfer hover colors for components when they have a solution. 👍🏻
