### ISSUE TITLE
[Pagination] Fix spacing of number of pages dropdown

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3328]
The current spacing of the dropdown for number of pages has too much spacing compared the the dropdown on the left for items per page. It may be inheriting something from select?

Current:
![Screen Shot 2019-07-10 at 9.58.20 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/44ef3eee-ad24-4ee2-a69e-c9d668a182ab)

Redlines:
![Screen Shot 2019-07-10 at 10.08.13 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/b7ed9c9e-ac9e-4684-b5bb-0d1c0780c996)

**Comment by emyarod** [comment]
@laurenmrice it looks like these are pagination specific styles and they're overriding select styles (https://github.com/carbon-design-system/carbon/pull/2076)

one thing to note is that the space between the "1" and the chevron depends on the max number of pages in the menu (it automatically leaves space for the 2nd digit in "10" and "11"). I can fix the other values though
