### ISSUE TITLE
[Tokens]: investigate skeleton values

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3335]
From @jeanservaas:

I read @shixiedesign's issue and it does seem like the token change is to spec. However, I'm noticing some discrepancies in the values for the skeleton tokens.

- I searched Git and I can't find Shixie's design/animation spec for the skeleton state. I wanted to double check it because I noticed that incorporating the @skeleton-02 token in the light themes seems very dark. I wanted to make sure this was intentional.

- This may not be a token issue... it may just be a value issue, in which case we could merge this PR and open another issue... but I want to make sure. I will ask @laurenmrice when she's in too, because she probably has more insight.

**$skeleton-02 value is very dark in light themes**
![image](https://user-images.githubusercontent.com/43144260/60900252-7fa30c80-a231-11e9-88e0-9c8d416ca4e4.png)

**skeleton token values (at least for G90) are incorrect on the Carbon site**
![image](https://user-images.githubusercontent.com/43144260/60902432-381e7f80-a235-11e9-8de7-5555cbc5c410.png)

**Netlify elements preview is showing different values for G90 skeleton tokens then the website, which one is right?**
![image](https://user-images.githubusercontent.com/43144260/60902523-5edcb600-a235-11e9-9b7a-df8a892c6a0d.png)

**Comment by aagonzales** [comment]
Original spec here: 
https://github.com/carbon-design-system/carbon/issues/1824

![image](https://user-images.githubusercontent.com/11670886/61008227-9da56580-a334-11e9-975a-4312f5deb144.png)

**Comment by aagonzales** [comment]
**Gray 90 skeletons** are going darker with as-is tokens
![image](https://user-images.githubusercontent.com/11670886/61063257-469ba100-a3c5-11e9-93d2-bca9c5ccb909.png)


**Gray 100 goes lighter:** with as-is tokens
![image](https://user-images.githubusercontent.com/11670886/61065686-cd527d00-a3c9-11e9-90a3-515358c3505a.png)

**Comment by tw15egan** [comment]
It looks like this is also an issue with `loading` as pointed out in this PR: https://github.com/carbon-design-system/carbon/pull/7679#pullrequestreview-578637308

**Comment by tw15egan** [comment]
> I think you're right it needs to be a different color. The `skeleton-02` in the gray 100 theme should use `#525252` Gray70

https://github.com/carbon-design-system/carbon/pull/7679#issuecomment-769423292

I will update this
