### ISSUE TITLE
[@carbon/cli] WSL - ⚠️ Packages "Not Found", broken emojis ⚠️

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#3337]
### Environment
Windows 10 latest, using Hyper Terminal, WSL running Ubuntu 18.04.2 LTS, Node 10.16

### Issues
- broken emojis 😢 
- all three package options fail, throwing an error message

![2019-07-10 12_45_21-Window](https://user-images.githubusercontent.com/40970507/60991717-b2700200-a310-11e9-9d8c-823f68c3de8f.png)

**Comment by emyarod** [comment]
refs #2434 #2700 #3243

**Comment by dakahn** [comment]
@emyarod This is actually an Ubuntu environment (although embedded in Windows); not sure those refs are up the same alley necessarily.

**Comment by emyarod** [comment]
meant it as a reference to path issues on both Windows and WSL but it actually seems this issue is present in all environments including macOS and pure Ubuntu and Debian

**Comment by joshblack** [comment]
Going to close this out since we never really pursued this experiment for setting up folks' machines. Feel free to re-open if you think we should keep pursuing it!
