### ISSUE TITLE
Carbon Style: Sass is taking too long to compile

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#3348]
Currently, I am using carbon component style sass.
When i include them inside my styles scss. It increasing the build time rapidly.

For eg. If I add only component data-table.scss in my common sass, it increases build time by about 2 seconds.

So, Without styles.scss, Live reload build time is around 1.8 seconds and after including styles.scss it is around 40 seconds.

"carbon-components": "^10.3.1"

**Comment by asudoh** [comment]
Hi 👋 this kind of issues tend to have many factors in play, so great to see you articulate your environment. One known issue is with custom Sass importer (and thus WebPack), written in issue# 857 in https://github.com/sass/node-sass, and issue# 296 in https://github.com/webpack-contrib/sass-loader.

**Comment by R4VANG3R** [comment]
Any update on this? I'm also seeing build times of 40s+ with a basically clean storybook project

**Comment by bitforcesrl** [comment]
I am also experiencing a very long time (about 1 minute) when compiling
~carbon-components/scss/globals/scss/styles

I created a custom scss import in order not to import all the components scss, and I manage to save some seconds per component. Still it doesn't seem a good solution, just a patch.

I also installed fibers to speed up the process, but it didn't change much.

Any update?

**Comment by baeharam** [comment]
This is very serious problem... I don't know it is the problem of Carbon or sass-loader, but must be improved

**Comment by bitforcesrl** [comment]
The problem is still there and i slowing down a lot our development process.
We've updated Angular to 9.1 and the carbon lib too. But it is still very slow!
