### ISSUE TITLE
Quick guide for initializing components with Javascript

### ISSUE THREAD

**Issue by markphd** [carbon-design-system/carbon#336]
The docs show example for initializing a Modal component calling `Modal.init()` but this isn't trivial to someone new in Carbon. For example, initializing Interior left nav doesn't  say which selector to use and which method to call. It would be nice if each component has a quick guide / how-to initialize component. 

This was my code to initialize the Interior Left Nav:
```
CarbonComponents.settings.disableAutoInit = true;
var leftNav = document.querySelector('[data-interior-left-nav]');
CarbonComponents.InteriorLeftNav.init(leftNav);
```

I had to dig the [code](https://unpkg.com/carbon-components@7.23.0/src/components/) to make the interior left nav work which could've been easier if the above code is already in docs.

**Comment by asudoh** [comment]
@markphd Seems that our developer guide confused you, sorry! For your use case, you needed just:

```javascript
CarbonComponents.settings.disableAutoInit = true;
CarbonComponents.InteriorLeftNav.init();
```

Above code automatically searches for elements matching `[data-interior-left-nav]` and instantiates the components.

Another thing to mention is that `[data-interior-left-nav]` selector is defined as `CarbonComponents.InteriorLeftNav.options.selectorInit` static property.

Documentation update for both is on the way.

**Comment by markphd** [comment]
@asudoh I didn't know that the `selector` is unnecessary. Good thing I asked here. 
Thanks for the help! Looking forward to see the updated docs.
