### ISSUE TITLE
[MultiSelect]: aria-labels React prop

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#3373]
# Summary
I am requesting for the ability to replace the `aria-label` on the main listbox button for the `MultiSelect` component. I need to be able to replace the generic “Open menu” label with one that is more descriptive in multiple languages.

### Justification

This is both an accessibility and a globalization requirement for IBM Security.

### "Must have" functionality
A documented prop on the `MultiSelect` component to replace `aria-label` with our own string. 

Additionally, a way to use the same label string from this prop for the multi-select chevron icon `aria-label` and `<title>`

### Specific timeline issues / requests

Yes, we need this before the end of Q3.

**Comment by jendowns** [comment]
hey @diego-codes would you be able to use `translateWithId` to change that "Open menu" default in for the `ListBox` / `MultiSelect` icon? https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ListBox/ListBoxMenuIcon.js#L56

**Comment by diego-codes** [comment]
It would be nicer to have a prop for each label, but the `translateWithId` prop would be fine.

**Comment by diego-codes** [comment]
Hello there, has the bug fix been for this been released? Is there a way I could check this myself?

**Comment by asudoh** [comment]
@diego-codes You can see our release dates, commit hashes, etc. at here: https://github.com/carbon-design-system/carbon/releases
