### ISSUE TITLE
(Mobile only) When UI Shell Side Nav is open, body content should not scroll

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#3383]
Related Fix: https://github.com/carbon-design-system/carbon/pull/3237
Related Issue: https://github.com/carbon-design-system/carbon/issues/3187

**Comment by asudoh** [comment]
@tw15egan Modal has a nature of preventing all user interactions but modal itself while it's open. OTOH, it appears that the issue for side nav is about undesired bouncing effect, is it correct? If so, we need a different technical approach to tackle this.

**Comment by tw15egan** [comment]
We want to eliminate scrolling while the side nav is open and the overlay is present (mobile). Basically, we want the exact behavior we have on the website

**Comment by asudoh** [comment]
I'm looking at the website now - The side nav seems stick open, and body is scrollable. Even when I open right-side nav the body seems scrollable. Therefore wondering what website behavior you are referring to @tw15egan? Is it specific about mobile?

**Comment by tw15egan** [comment]
Yes this is specific to mobile

**Comment by asudoh** [comment]
Thanks @tw15egan for clarifying - Sounds that the fix not affecting desktop (or probably better wording is mouse-based interaction) is important. Changed the title as such.
