### ISSUE TITLE
UI issue: Modal "cancel" button

### ISSUE THREAD

**Issue by kaylarakower** [carbon-design-system/carbon#3387]
When a background is dark against a modal, there is no differentiation between the "Cancel" button in the modal and the background.

![image__1_](https://user-images.githubusercontent.com/48567372/61150948-b045a900-a4b2-11e9-8a9b-dee8759f8329.png)

**Comment by emyarod** [comment]
in the meantime a quick workaround would be to adjust the values for the background or the cancel button on the application side

**Comment by asudoh** [comment]
Another possible user-land solution (unless @carbon-design-system/design disagrees) is applying `overlay-01` token from one of our dark themes to the background color of `.bx--modal.is-visible`.

**Comment by kaylarakower** [comment]
@asudoh we are using overlay-01 in the screenshot adove.

**Comment by shixiedesign** [comment]
If user knows what image goes there, user may simply choose to use our dark theme modal to avoid this problem: 

![image](https://user-images.githubusercontent.com/15144993/61969379-07ae4380-afa0-11e9-9f1b-8641cf075472.png)

If the image is dynamic or not controlled by the user, then no solution will really work. There will always be some combination of background image color and modal overlay where something blends into each other...

**Comment by kaylarakower** [comment]
@shixiedesign in that case, should I propose concepts to update the modal ui to avoid this from happening given the likelihood of black on black, instances this is not controlled by the designer, and to decrease time to solution for designers?

**Comment by shixiedesign** [comment]
We are open to suggestions!

**Comment by laurenmrice** [comment]
not stale

**Comment by kaylarakower** [comment]
Not stale

**Comment by kaylarakower** [comment]
![color](https://user-images.githubusercontent.com/48567372/65618113-c4665600-df8b-11e9-944d-efb248bbfdf7.jpg)


Unfortunately changing the color still wouldn't meet accessibility requirements. Given that I am a UX Designer rather than a visual designer, my suggestion to the Carbon team is to have a visual designer seek alternative designs. If pursued, here is a sketch file with some basic concepts to get them started: https://ibm.box.com/s/yo9o8d20rrg8lhxpmovn3fmkq933aua4

**Comment by chrisconnors-ibm** [comment]
@dakahn can you comment on our accessibility compliance across the different criteria for buttons in particular for this context.

**Comment by dakahn** [comment]
@kaylarakower Thank you so much for bringing this to our attention again. So where we are now is we have buttons that meet Web Content Accessibility Guidelines v2.0 contrast criteria in terms of label against button background, but as you've pointed out that's not good enough for Web Content Accessibility Guidelines v2.1 compliance (coming as a requirement for our team in January). 

[With the contrast requirement broadening to include "non text contrast"](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) or button background against adjacent colors (page background for example) we do have work to do in terms of meeting compliance for sure and will be exploring solutions in upcoming work cycles. 

That said, Many thanks as well for jumping in with a proposal 😄. If you'd like to get a formal discussion started around your designs in particular [consider opening up an enhancement ticket](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&template=feature-request-or-enhancement.md&title=) That references this issue. We definitely are open and appreicative to any suggestions 🙏.

**Comment by chrisconnors-ibm** [comment]
@kaylarakower in the meantime - don't let this be a blocker! Specify the component now as it is (which is WCAG 2.0 compliant) so your team's builds/projects will get any fix we deliver in future iterations.
