### ISSUE TITLE
Getting Started > Developers > #a11y contrast issue

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#339]
http://carbondesignsystem.com/getting-started/developers
The hover color of the blue hyperlinks on this page do not meet AA requirements for contrast. It would be a poor user experience if this text disappeared on hover for users with poor contrast distinction.

**Comment by bsonefeld** [comment]
Hi @arbydev , we've updated our color to meet WCAG AA color contrast guidelines. You can see the change reflected here: http://carbondesignsystem.com/getting-started/developers
