### ISSUE TITLE
Finalize Elements Plugin output

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3406]
Based on the output of #3405, this issue is for resolving the discrepancies with naming conventions in code for all of the Sketch commands. The end result of this will be the final plugin that will be used by design to generate the Elements Kit.

- [ ] Sync subcategories for icons

**Comment by joshblack** [comment]
cc @lovemecomputer did you want to take this on?

**Comment by lovemecomputer** [comment]
@joshblack yes!
