### ISSUE TITLE
Card status mixin does not support stopped and limited

### ISSUE THREAD

**Issue by theoshu** [carbon-design-system/carbon#342]
## Detailed description

Card status mixin used to support stopped and limited status by displaying an appropriate colored circle to the left of the status text. With carbon, the mixin no longer has these options.

## Steps to reproduce the issue

1. Create a component with the following code. Notice the colored circles do not display for stopped and limited.
```
<div class="bx--card-footer" id="ext-gen1158">
  <div class="bx--card-footer__app-status">
    <div class="bx--card-footer__app-status--running active">
      <div class="bx--running__text">
        Running
      </div>
    </div>
  </div>
  <div class="bx--card-footer__app-status">
    <div class="bx--card-footer__app-status--not-running active">
      <div class="bx--not-running__text">
        Not Running
      </div>
    </div>
  </div>
  <div class="bx--card-footer__app-status">
    <div class="bx--card-footer__app-status--stopped active">
      <div class="bx--stopped__text">
        Stopped
      </div>
    </div>
  </div>
  <div class="bx--card-footer__app-status">
    <div class="bx--card-footer__app-status--limited active">
      <div class="bx--limited__text">
        Limited
      </div>
    </div>
  </div>
</div>
```

## Additional information

There are references to the limited and stopped statuses in _card.scss, but not associated background colors in _mixins.scss

**_card.scss**
```
  .bx--card-footer__app-status--running {
    @include app-status('running');
  }

  .bx--card-footer__app-status--not-running {
    @include app-status('not-running');
  }

  .bx--card-footer__app-status--stopped {
    @include app-status('stopped');
  }

  .bx--card-footer__app-status--limited {
    @include app-status('limited');
  }
```

**_mixins.scss**
```
  @if ($status == 'running') {
    &::before {
      background-color: $support-02;
    }
  }

  @else if ($status == 'not-running') {
    &::before {
      background-color: $support-01;
    }
  }
```

**Comment by marijohannessen** [comment]
Hi @theoshu ! This sounds like something we should add back in. We're a bit short on resources right now, so is this something you wouldn't mind contributing back to us by adding the statuses you're missing to the mixin and submitting a PR? If not, we can get to it next sprint but we would need more information about what color each status has, etc.

**Comment by theoshu** [comment]
@marijohannessen I can do that. Should I create a PR in carbon-addons-bluemix or here?

**Comment by marijohannessen** [comment]
`carbon-addons-bluemix` please! 🙂
