### ISSUE TITLE
TooltipDefinition no longer supports Nodes for tooltipText prop

### ISSUE THREAD

**Issue by austinbruch** [carbon-design-system/carbon#3420]
TooltipDefinition no longer supports Nodes for tooltipText prop

## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `TooltipDefinition` component no longer supports Node objects for the `tooltipText` prop. It now only supports strings. This is a breaking change within major version 10. It came in here: https://github.com/carbon-design-system/carbon/commit/2571ed5051a45a335796365fe09f74e419d07192#diff-916183444c3885c676548407d734df75R74

We were using the Node structure to allow multiple DOM nodes within the tooltip, so we could apply alignment and styling to the text. This is no longer possible with only being able to supply strings.

For example, this is how we used TooltipDefinition's support of Node objects in the `tooltipText` prop previously:
![image](https://user-images.githubusercontent.com/3361835/61324456-7b05c780-a7e0-11e9-9b67-c944c270d245.png)

Note the bold formatting, and alignment of the tooltip text content.

> Is this issue related to a specific component?

`TooltipDefinition`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected continued support of `PropTypes.Node` for the `tooltipText` prop.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components: 10.4.1
carbon-components-react: 7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Identity

## Steps to reproduce the issue

Render a `TooltipDefinition` using a Node object for the `tooltipText` prop instead of a string.
> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
@emyarod Do you recall any background wrt the move from node to string? Thanks!

**Comment by elizabethsjudd** [comment]
For a11y, this type of setup for tooltip only supports strings. To support rich text users should use the Interactive Tooltip setup.

**Comment by asudoh** [comment]
@elizabethsjudd Interesting, would you think of an approach where we provide graphical interface for non-screenreader users while we provide screen-reader features? Labels possibly?

**Comment by elizabethsjudd** [comment]
I'm not sure I'm following what you are suggesting here.  From my experience most a11y tooltips end up using the interactive tooltip setup because they rarely only contain only a string.  Semantically the tooltip role is meant to only be when there is a string. With anything else it's a "dialog"

**Comment by asudoh** [comment]
My apologies for my poor wording, I was simply thinking if there is a way to satisfy the issue author's needs while we meet the screen reader requirements.

**Comment by elizabethsjudd** [comment]
they would want to migrate to the interactive tooltip. I would say if they do not need a11y support at the moment we could keep the support in v10 with a deprecation warning and remove it in v11.  But if they need to be a11y compliant then they need to switch versions of the tooltip.

**Comment by asudoh** [comment]
I see your point @elizabethsjudd. One thing that's interesting in above screenshot is that there is no interactive content like what our interactive tooltip intends. @carbon-design-system/design Does bold text like above screenshot makes sense for our definition tooltip?

**Comment by austinbruch** [comment]
> I would say if they do not need a11y support at the moment we could keep the support in v10 with a deprecation warning and remove it in v11.

This would me by preference. a11y support is not an immediate requirement, and if the prior implementation of the component didn't have it, it's not like we're losing anything by continuing to use it as it was. As suggested, I would have expected a deprecation warning on the prop type change, seeing as it's a breaking change within a major release. I realize our use case is atypical and likely not how this component was intended to be used, but it was within the realm of possibility based on the prior implementation, so I expected continued support until warned otherwise.

> Does bold text like above screenshot makes sense for our definition tooltip?

I'd like to also point out the alignment, in addition to the bolding. Both were made possible by the Node prop type, as we were able to apply CSS to specific child nodes within the tooltip's content.

**Comment by elizabethsjudd** [comment]
I agree with @austinbruch that the behavior should not have been removed within a major release but instead use a depreciation warning to inform users they should switch.

Following Carbon's usage documentation the definition tooltip is for "brief read-only text" where definition tooltip is for "rich text" (https://www.carbondesignsystem.com/components/tooltip/usage).  WCAG's documentation on role="tooltip" also follows this same structure stating that it should be a string of text.  Because this example has additional markup within the contents of the tooltip it would be classified as rich text.

**Comment by emyarod** [comment]
@asudoh IIRC the move from node to string is in line with the recommended use case for definition tooltips as @elizabethsjudd pointed out. that being said I believe we can reimplement support for nodes in `tooltipText` for the time being and flesh out migration paths to interactive tooltip for this kind of use case

**Comment by austinbruch** [comment]
>...I believe we can reimplement support for nodes in tooltipText for the time being...

@emyarod Any chance of such a reimplementation making it into a patch release e.g. 10.4.2 in the near future?

**Comment by asudoh** [comment]
Makes sense @emyarod - Also please make sure getting in sync with our designers on text decoration thing. Thanks!

**Comment by joshblack** [comment]
cc @tw15egan @asudoh is this something that support project could take on this iteration? Not sure what the backlog is but @austinbruch is in the process of migrating to the updated security and this is currently a blocking issue for them so any steps to address/resolve would be super appreciated 🙏

**Comment by austinbruch** [comment]
Friendly bump. Any update on when we might see restoration of the previous functionality in an upcoming release?

**Comment by emyarod** [comment]
I think we can address this after https://github.com/carbon-design-system/carbon/pull/3739 is merged in

the current React tooltips don't include the latest spec changes, but this can be more easily resolved once the two versions are consistent with each other
