### ISSUE TITLE
[Link: Regression styling bug] states colors overwrite disabled color

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3428]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

if a previously visited link is now disabled the visited color is overwriting the disabled color

> Is this issue related to a specific component?

Link

> What did you expect to happen? What happened instead? What would you like to
> see changed?

disabled links should always be the disabled color not matter it's state

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. Visit a link
2. Now disable the link
3. view the color of the link

## Additional information
The disabled selector needs more weight

<img width="1286" alt="Screen Shot 2019-07-17 at 9 32 08 AM" src="https://user-images.githubusercontent.com/1275779/61379782-3167bc00-a876-11e9-9a22-eb784853b055.png">

**Comment by asudoh** [comment]
After mulling over all of the review comments of #3445, and @emyarod's clarification that disabled link uses non-`<a>` element (where `<span>` seems the consensus). I re-ran my local test against what's reported here, and turned out that there is no scenario where the problem reproduces.
