### ISSUE TITLE
FileUpload component fileStatus uploading spinner issue

### ISSUE THREAD

**Issue by Incarnation** [carbon-design-system/carbon#3436]
## What package(s) are you using?

- [ x] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
when the FileStataus is uploading
the spinner looks weird

> Is this issue related to a specific component?
FileUploader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.3.2",
    "carbon-components-react": "^7.3.2",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

<img width="1677" alt="Screen Shot 2019-07-17 at 4 02 58 PM" src="https://user-images.githubusercontent.com/5199303/61407811-9fc77100-a8ac-11e9-8b8f-d101d2a3bdb6.png">

![image (2)](https://user-images.githubusercontent.com/5199303/61407972-f6cd4600-a8ac-11e9-95dc-1958c71e4b26.png)

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hey there! Going through older issues today, so sorry about the delay in receiving a response. I don't believe this issue exists in latest, but if you have steps to reproduce I can definitely figure out what's going on here!

Going to close this out for now, feel free to comment and I can re-open!
