### ISSUE TITLE
API Icons

### ISSUE THREAD

**Issue by ritch** [carbon-design-system/carbon#3447]
Hey @joshblack and @jnm2377 - we've spoken a few times over IBM slack and webex about adding some API related icons into Carbon. I was hoping we could continue that discussion here and put together any related TODOs to get the icons in.

As far as I'm aware there are three major items to discus / do:

1. Figure out where these API icons should live
2. Create or update the actual icon assets (illustrator files I beleive?)
3. Update `@carbon/icons` (assuming this is well documented)
4. Update `@carbon/icons-react`
5. Update `@carbon/icons-angular`

If there's anything else to add to this list LMK.

**Comment by jnm2377** [comment]
@ritch is there a current library where we can view the specific icons that are missing? 
cc: @chrisconnors-ibm 

I think the next steps for tackling no.1 would be knowing the exact icons that are needed. If there's no library, perhaps a design file or image?

**Comment by jnm2377** [comment]
I'm not sure how many icons are needed, either, so if it's a lot, perhaps a box link with a folder that contains the icons would be easier.

**Comment by joshblack** [comment]
Hi @ritch! 👋 When it comes to adding icons into these projects, we'll need to involve @chrisconnors-ibm on the design side. He can help us understand if these icons are appropriate in these core packages (which tend to be used for IBM Design Language icons) or if we should find another option here that makes sense 👍 

Like @jnm2377 brought up, identifying which icons are needing to be added and their asset source will help out a ton with this process.
