### ISSUE TITLE
Tooltip doesn't work on click in labelText of select component 

### ISSUE THREAD

**Issue by codeYuyuan** [carbon-design-system/carbon#3448]
## What package(s) are you using?

- [x] `carbon-components` 10.4.1
- [x] `carbon-components-react` 7.4.1

## Detailed description

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When user click tooltip icon, tooltip contents should show up.

> What browser are you working in?
Chrome 75

> What version of the Carbon Design System are you using?
10.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Voice agent with Watson. 

![image](https://user-images.githubusercontent.com/26753671/61472362-46198200-a952-11e9-8bc1-5443efbcb5be.png)
Even set the pointer-event to auto in bx--lable, it still doesn't work. 

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/lrmxz8lqr9

**Comment by mattchapleau** [comment]
I'm seeing the same issue when I try to add a ToolTip element as a child of a div containing class "bx--label". User is unable to click the tooltip.

**Comment by tw15egan** [comment]
Until a new release is published, you can set `.bx--label { pointer-events: auto; }`

**Comment by codeYuyuan** [comment]
Hi @tw15egan,
This didn't work, the event somehow got blocked by the input. 
Can you take a look at this code sandbox example?
https://codesandbox.io/s/lrmxz8lqr9
