### ISSUE TITLE
close Interior Left Nav on blur

### ISSUE THREAD

**Issue by kyogom** [carbon-design-system/carbon#345]
> Is this issue related to a specific component? 
Interior Left Nav

> What browser are you working in? 
chrome

>Question 
![question carbon](https://user-images.githubusercontent.com/23183700/31107369-e948b5e6-a82c-11e7-9140-7bf35175f222.gif)

**Comment by aagonzales** [comment]
@kyogom Could you explain the issue a little more specifically?

**Comment by asudoh** [comment]
@kyogom Are you expecting a non-sticking kind of interior left nav, like non-interior left nav (one you see by clicking on the hamburger menu on the top left in https://console.bluemix.net/dashboard/apps page)?

**Comment by kyogom** [comment]
@asudoh 
yes. I expected that kind of nav. Is sticky nav demanded by someone? I think it's not user friendly. no offense.

**Comment by aagonzales** [comment]
@kyogom I don't disagree with that statement. However, this pattern came from a particularly weird use-case of already having a main hamburger left nav which operates as you would expect and then a second level of navigation from this _Interior_ left nav. We don't recommend this for uses outside that particular scenario. We've actually recently moved this component out of our main repo into the add-ons section for that reason.

**Comment by kyogom** [comment]
@aagonzales I got. thanks.
