### ISSUE TITLE
[Search] add 40px search size

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3457]
Spec:

![search 40px.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/e10f0771-3554-4234-a6bc-84bedc7f3599)
We have a 48px and 32px search but we want to also have a 40px search so it will align if its sitting next to 40px field heights.

We have seen some usecases where this would be a valuable size to add to our existing component. There have been instances where it could be useful when filtering content on a page or a data table and having a search inline with the filter field.

**Comment by asudoh** [comment]
CC @laurenmrice to see we still have an interest in this enhancement.

**Comment by laurenmrice** [comment]
@asudoh  yes we still need this
