### ISSUE TITLE
[Theme sandbox]: assorted bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3460]
I've found a few different bug with the internal [theme sandbox](http://carbon-dev-environment-hippest-flaccidness.mybluemix.net/?nav=accordion).

- [ ] Disabled buttons not updating in preview
   -  I doubled checked the tokens in the code itself and they're correct but for some reason the sandbox isn't rendering the update.
![image](https://user-images.githubusercontent.com/11670886/61498771-4c2b5500-a98a-11e9-9cc8-c3619ba94c6a.png)
- [ ] Disabled content switcher not updating in preview
![image](https://user-images.githubusercontent.com/11670886/61498784-5a797100-a98a-11e9-9691-2ae65638a957.png)
- [ ] “Menus” in sandbox, not changing themes with switcher
    - ~Date picker~ fixed
    - Overflow menu
    - Tooltip
(still the white theme menu)
- [ ] Not exporting correct values for output:
    - export const hoverUI
    - export const activeUI
    - export const selectedUI 
    - export const hoverSelectedUI
- [ ] Notification: inline (low contrast) is showing `toast` notifications instead of `inline`

**Comment by aagonzales** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/3183

**Comment by asudoh** [comment]
Discussion ongoing wrt where further changes to theme sandbox should be hosted. CC @shixiedesign

**Comment by joshblack** [comment]
Going to close this out, it seems like this effort will be moved towards enhancing abilities on the site from the work Vince has been doing 👍 cc @alisonjoseph

**Comment by alisonjoseph** [comment]
Agreed, we will no longer need the theme sandbox with the website updates on component pages.

**Comment by alisonjoseph** [comment]
@aagonzales would the work @vpicone has done on the website to add the themes per component be a replacement for the sandbox? Or do we still need the sandbox as a place to have all components in one spot??

**Comment by aagonzales** [comment]
@alisonjoseph The nice part about the sandbox is that users can make custom themes and see how the tokens work. Vince's component demo only shows the components as they are in the four set themes. You can also export your custom theme here so I guess it is nice to see all the components together. I think this sandbox would still be a nice tool to have. 

I thinks its a handy design system tool, it would be nice to get the type tokens in it as well.

**Comment by alisonjoseph** [comment]
Makes sense, will leave this open and figure out when we can prioritize it

**Comment by aagonzales** [comment]
@alisonjoseph if we're going to invest in this tool it would be nice if we can also take a design pass at it and get it up to v10 standards. But I guess that would be a different issue than just fixing these bugs.

**Comment by joshblack** [comment]
Going through old issues today and am going to close this out since I think we aren't working on this any more? Feel free to re-open if I'm mistaken!

**Comment by aagonzales** [comment]
@joshblack @alisonjoseph so the theme sandbox is still live. If we dont want to clean it up then I think we should take down the site. https://themes.carbondesignsystem.com/?nav=accordion

It would be nice to build a new fancy theme sandbox sometime in the future. Especially if we switch to building more tooling instead of components.

**Comment by aagonzales** [comment]
Closing since we're not really supporting this theme Sandbox anymore. Maybe in future we'll build a new one.
