### ISSUE TITLE
[PasswordInput]: Toggle text styles

### ISSUE THREAD

**Issue by trusinaj** [carbon-design-system/carbon#3462]
## Detailed description
Text under toggle in `PasswordInput`, with class`bx--text-input--password__visibility::after`, is extending from input outside of his size. Its fine if we have padding above 3rem from left and right.

This is mostly problem on my login page,  when screen size gets smaller for mobile users and my padding is only 1.5rem around form. I was looking for some information, if its required to have at least 3rem padding, but couldnt find any.
U can see it in codesandbox exmaple. Scroll shouldnt be there, I think? Thanks :)

> Carbon Version
latest

> CodeSandbox
https://codesandbox.io/s/codesandbox-2dxtk

> Web browser 
Edge
Chrome

**Comment by emyarod** [comment]
this is likely caused by the tooltip, we should allow the direction of the tooltip to be configured
