### ISSUE TITLE
Create Elements Sketch Kit

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3472]
This issue is to create the Elements Sketch Kit using the Sketch Plugin built as part of our Icon project to create pages for:

## Cover ##
- Lauren will copy the one that exists in current idl kit.

## Color ##
**Color Page:**
- Follow the same layout structure by color, spacing, and symbol naming convention as current idl kit.
- Get rid of hover colors.

**Color Library:**
- Follow same naming convention as current idl kit (all lowercase)
- Section by `color / token type / color type / color grade`
Ex. `color / blue / blue-60`

## Themes ##

**Themes page:**
- Have each theme color blocks in its own column vertically.
- Have each token in rows horizontally.
- Maybe include labels above each row and columns, for scanability? (Lauren could do this manually?)

**Themes library:**
- Lauren will manually add a `transparent` style to the core tokens.
- Section by themes / theme type / token type / token name
Ex: `themes / white theme / core tokens / ui-01`

## Icons ##
- Had to split into two different libraries because of sketch cloud limitations, and for scalability reasons.
- Follow same naming convention as current idl kit (all lowercase)
- Section by category / subcategory / icon name / icon sizes
Ex: `actions / controls / dashboard / 16`

**Icons Library 1**
- All icons
- Sizes: 16px, 20px

**Icons library 2**
- All icons
- Sizes: 24px, 32px

## Type ##

**Type page:**
- Show the type styles 
- Group by supporting styles, productive, expressive, paragraphs and quotes, and display
- Lauren will manually do type styles for expressive.

**Type styles:**
- Lauren will manually make type styles for expressive.

---------------------------------------------------------------------------------------------------

The intent of this kit is to replace the IBM Design Language Sketch Kit. As a result, it needs to support the following features that currently exist in the IDL Sketch Kit:

- Have all colors in palette
- Have all type styles
- Have all icons from existing idl kit + all of the ones in our elements

Replacing the IDL kit means that we have to notify individuals about the following issues or ways to migrate to the updated kit:

- We are doing this so that the idl kit/library is automatically updated with what exists in code and will no longer be a manual process to update.

- We will not be updating or maintaining the old idl kit/library (This means, people will not have access to the full list of icons, or color palette updates, etc. if they do not eventually switch over to our new maintained kit/library)

- We will have both the old and new idl kit/libraries coexist for a period of time for people to get acquainted with using the new one.

- Symbols may break and have to be reattached

**Comment by joshblack** [comment]
cc @chrisconnors-ibm or @laurenmrice do you have a chance to help fill out the sketch kit requirements? 🙏

**Comment by laurenmrice** [comment]
~~Question for @chrisconnors-ibm at the end of this release are we going to be actively making the IDL kit replacement public? Or are we testing it out first for this release.~~

Talked to him about this and will have both existing IDL kit and ours available for use for this release.
