### ISSUE TITLE
Data table content is not vertically aligned within a row.

### ISSUE THREAD

**Issue by AlexisMaeLandis** [carbon-design-system/carbon#3475]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The sketch data table component appears to have the correct alignment for content within a row, but when brought into react, the data table content is not vertically aligned anymore. 

> Is this issue related to a specific component?

The data table. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The content aligned vertically. 

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Hardware Management Console for Z, GA1 (September 23)

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox

 - Style and vanilla JS:
  https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
- React:
  https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code

<img width="1271" alt="Screen Shot 2019-07-19 at 2 20 22 PM" src="https://user-images.githubusercontent.com/41640763/61556673-5dc73800-aa30-11e9-8625-235b6b0cf213.png">

- Notes

**Comment by emyarod** [comment]
> Please create a reduced test case in CodeSandbox
> 
> React:
> https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by joshblack** [comment]
Hi @AlexisMaeLandis! 👋 Thanks so much for taking the time to make an issue, going to close this as it's been inactive for a couple of months but feel free to re-open if you have a reduced test case!
