### ISSUE TITLE
AVT violations of Slider

### ISSUE THREAD

**Issue by kiddove** [carbon-design-system/carbon#348]
Hi there, I'm using slider in our product and I found 2 AVT violations. It also exists on Carbon Design System site(http://www.carbondesignsystem.com/components/slider/live). Attached please find the screen shot.

![avt_slider](https://user-images.githubusercontent.com/2195199/31280037-090575ce-aa79-11e7-8114-4504e07dedb5.jpg)

**Comment by tw15egan** [comment]
Quickly looking at this, but this error seems to be coming from the fact that your label's `for` attribute is looking for an id of `slider`, and your slider input has an id `slider-input-box`. These need to match

**Comment by tw15egan** [comment]
Hey @kiddove, did this resolve your issue?

**Comment by marijohannessen** [comment]
Closing this issue due to lack of response from issue creator. Please feel free to re-open if needed.
