### ISSUE TITLE
Search component is missing a CTA

### ISSUE THREAD

**Issue by kosruben** [carbon-design-system/carbon#3489]
## Detailed description

The [Search component](https://www.carbondesignsystem.com/components/search/code) does not have a button to perform the search. I understand it can work by pressing the `Enter` key after typing the query but this is not accessible. So far we have been adding a button next to the search field to solve this case but it would be great if we can just make the icon in the Search component clickable so that the designs are looking clean as well.

We are currently using Carbon V9 on a released product for IBM Talent Management Solutions and are planning to re-design the product and move to V10 soon.

## Steps to reproduce the issue

1. Type content in the input field of the Search component
2. Confirm search by clicking somewhere

## Additional information

- Some use cases might open a suggested drop-down list while typing which would mean any of those results could be clickable but it still doesn't allow the user to search for the typed query.
- If we are meant to add an additional Button component to allow for the described use case it would be great if an example can be added to the documentation

Thanks for reading!

**Comment by asudoh** [comment]
@carbon-design-system/design I'm imagining search-as-you-type, but not sure - Any insights? Thanks!

**Comment by jeanservaas** [comment]
@asudoh we should have both patterns, incremental search and one that's triggered on clicking the icon... @chrisconnors-ibm I feel like we talked about this a while ago.

I did find these alternate designs, but maybe it was not developed:

( Image removed to avoid confusion, refer to below)

**Comment by asudoh** [comment]
@jeanservaas Got it, makes sense - Thank you for clarifying!

**Comment by kosruben** [comment]
Thanks everyone for replying to this. 

@jeanservaas Are these designs final? As my development team is using Carbon for Angular, we could potentially develop the Angular version and contribute back to Carbon for Angular.

**Comment by jeanservaas** [comment]
@kosruben -- here is the final spec -- there were some old out of date things in that previous one. I also updated this file with the color tokens.

![alternate_search_spec](https://user-images.githubusercontent.com/43144260/62223588-d3110200-b37a-11e9-8b16-6f3ed2e46215.png)



Sketch file:

[Alternate_Search_spec.zip](https://github.com/carbon-design-system/carbon/files/3452542/Alternate_Search_spec.zip)

**Comment by asudoh** [comment]
Thanks @jeanservaas! Looking at this with #2831 now... We seem to have magnifier icon at the left in latest `v10`, but seems that we should move it to right. Is it correct...? CC @shixiedesign

**Comment by jeanservaas** [comment]
@asudoh yes we do currently have the magnifier on the left in v10. The above design was an alternate version of search for a situation in which you click on the icon button to trigger the search. It doesn't seem intuitive in this situation to keep the icon button on the left...

But I'm curious to see what @shixiedesign thinks. She's out today but will be back online tomororow.

**Comment by shixiedesign** [comment]
Security team is also looking for a variant of the Search component with CTA. Use case being a more "intentional" search where user will be taken to a separate page / tear sheet. The current search experience aligns better with filter, or on-page search, where users can get real time search results while typing. 
Let's keep this issue alive for further investigation.

**Comment by aledavila** [comment]
Needs design revisions
