### ISSUE TITLE
Coordinate requirements for pictogram delivery

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3497]
Some questions that need to be answered:

- What is a pictogram in the context of the Carbon Design System?
- Where are we surfacing pictograms for Design?
- How should we surface pictograms for development?
- Should we offer anything for pictograms on the website?
- Is there any content that needs to be written around when and how to use pictograms?

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
>What is a pictogram in the context of the Carbon Design System?

Like icons, they’re svg assets categorized (by a similar metadata mechanism?) but not bounded by size nor extant in explicit sizes.

>Where are we surfacing pictograms for Design?

1. `elements` derived IBM Design Language Kit, (matching existing kit - when in doubt _look at the existing IDL kit, that's what we have to functionally replicate 1:1_)
2. on the DL and CDS websites, in a component similar to the icon one?
3. unlike icons, they are less likely to have a lifecycle of iteration, so _I believe_ we care much less about them being orphaned, so direct dl or pointer to git repo as a first class UI embodiment is probably ok and desirable here

>How should we surface pictograms for development?

not sure if there's a need to, but open to suggestion here. on one hand we care a lot less about orphaning them, but on the other hand it would be nice if we didn't force people to use them standalone.

>Should we offer anything for pictograms on the website?

yes, above

>Is there any content that needs to be written around when and how to use pictograms?

yes definitely.

I'll get with @conradennis and @peter-garvin to see if there are more requirements for pictograms beyond our focal length

**Comment by peter-garvin** [comment]
@chrisconnors-ibm I think youre right in that there's less of a concern of them being orphaned. 
Also, we have seen a high demand for pictogram PNGs as well – many want to use them in ppt decks. Michael Dudley has more information on this. I think theres plans to export them out in common colors

**Comment by peter-garvin** [comment]
Not sure what to do for usage guidance. I'd think either use the same page from IDL or have a brief section in the carbon iconography page that links out to IDL

**Comment by conradennis** [comment]
we do recommend incremental sizes for pictos when they're used in product. smallest would be 32px and they can increase in size by intervals of 16px so 32, 48, 64, 80, 96 and anything above that is more or less fair game. Though I think we'd recommend trying to keep their sizes in some relationship to the base mini unit/grid of where they're applied whether in a digital or physical space.

**Comment by conradennis** [comment]
Peter is right we've been getting PNG and SVG requests from teams looking for assets to drop into slides etc.

**Comment by chrisconnors-ibm** [comment]
we could probably add a "convert svg to png" but then sizing becomes a parameter

**Comment by chrisconnors-ibm** [comment]
> we do recommend incremental sizes for pictos when they're used in product. smallest would be 32px and they can increase in size by intervals of 16px so 32, 48, 64, 80, 96 and anything above that is more or less fair game. Though I think we'd recommend trying to keep their sizes in some relationship to the base mini unit/grid of where they're applied whether in a digital or physical space.

but we're not planning to _generate_ additional sizes, right @conradennis

**Comment by conradennis** [comment]
@chrisconnors-ibm definitely not going to generate anything beyond the original 32px and people can size accordingly
