### ISSUE TITLE
Floating action buttons

### ISSUE THREAD

**Issue by skalmadka** [carbon-design-system/carbon#35]
Have you guys considered adding "Floating action buttons" similar to https://material.io/guidelines/components/buttons-floating-action-button.html# , I find it very useful under many circumstances especially for the responsive UI sites.

**Comment by tw15egan** [comment]
Hey! We actually had a Fab component before our 7.0 release, but it was deprecated from the product. 

If you're interested in taking a look at it, you can switch to the v6 branch
