### ISSUE TITLE
Table header height issue of 'sm' size

### ISSUE THREAD

**Issue by nitishjain07** [carbon-design-system/carbon#3503]
Hi Team,

There is a CSS bug when using 'sm' size table with no selectionColumn. In this case height of first element remains 3rem instead of 1.5rem.

You can replicate the issue at - https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu. Go to knobs tab, select size='small' and uncheck showSelectionColumn property.

We are using this in our project. Can we please expect the fix soon.

Thanks in Advance!

We are using the below versions of carbon:
"carbon-components": "^10.4.1",
"carbon-components-angular": "^3.13.1"

**Comment by cal-smith** [comment]
![image](https://user-images.githubusercontent.com/1744185/61721261-30cb9b80-ad36-11e9-8ee6-61bc26a42204.png)

The issue seems to be with `bx--date-table--sort` not playing nice with the smaller size headers, and no checkbox column

**Comment by cal-smith** [comment]
If I enable a checkbox column, and sorting, it all works

![image](https://user-images.githubusercontent.com/1744185/61721528-97e95000-ad36-11e9-890d-a178df6b3f79.png)

**Comment by nitishjain07** [comment]
<img width="1071" alt="Screenshot 2019-07-23 at 8 30 07 PM" src="https://user-images.githubusercontent.com/18714593/61723092-1cfd5500-ad89-11e9-98b0-48d01e356b65.png">

Please find issue in the attached image
