### ISSUE TITLE
Button - tooltipAlignment not properly handled - one line fix required

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#3504]
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js
Line 52, tooltipPosition used instead of tooltipAlignment in class name:

![image](https://user-images.githubusercontent.com/17591704/61723634-bff3a600-ad6c-11e9-982a-22944d347a98.png)

    "carbon-components": "10.4.1",
    "carbon-components-react": "7.4.1",
    "carbon-icons": "7.0.7",

https://codesandbox.io/embed/codesandbox-3ro4i

@emyarod

**Comment by tomkdgun** [comment]
@emyarod @asudoh How to get this fix ? It seems version of module doesn't changed. When this will be released ?

**Comment by asudoh** [comment]
We have a monthly-ish release cycle. Stay tuned!
