### ISSUE TITLE
[Theme sandbox] add version control for v9

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3505]
Need to a v9 version to the [theme sandbox](http://themes.carbondesignsystem.com) like we do with our website in order to support previous versions.
v9.carbondesignsystem.com

**Comment by mattrosno** [comment]
Do we simply need to host the previous theming sandbox at a domain like http://themes-v9.carbondesignsystem.com?

**Comment by mattrosno** [comment]
Hyphenated subdomain `themes-v9`?

**Comment by aagonzales** [comment]
Yes, i think its that simple.
