### ISSUE TITLE
[Theme sandbox] Update designs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#3508]
## MVP
Can we update the page structure and style of the theme sandbox to look like the v10 website. It current is structured like the old v9 website, besides the colors. 

![image](https://user-images.githubusercontent.com/11670886/61728031-fcf27500-ad39-11e9-8a1f-f9e1c7085fad.png)

## Cupcake

- use shell / Gatsby theme
- if the right panel could be a grid influencer and push the content when it is open so it doesn't overlay the page content. 
- have the right panel default open
- Add page header that says "Carbon **Themes** "
- component links in the left nav be anchor links and not individual pages, whole sandbox be one scrollable page.
- page background is `#e5e5e5`

![image](https://user-images.githubusercontent.com/11670886/61739769-bb21f880-ad52-11e9-8e85-bbd9f4e75790.png)

![image](https://user-images.githubusercontent.com/11670886/61739874-f3293b80-ad52-11e9-870e-e78b0a5f79f4.png)

**Comment by mattrosno** [comment]
Instead of investing in our vanilla demo environment, could we switch to Storybook? The upcoming component spec effort possibly includes standardizing Storybook stories so vanilla and React stories in Storybook would be the same.

For a theming sandbox, how can we use something like https://codesandbox.io that has all components on one page and you could modify the Sass variables? That way you could theme for colors, typography, spacing... a lot more than just colors.

**Comment by aagonzales** [comment]
Yeah something like https://codesandbox.io would definitely be a wedding cake version of the theme sandbox. At a minimum I'd like to get the styles update asap to look/feel more like part of the V10 family.

We can add a wedding cake issue to the next release cycle maybe?

**Comment by asudoh** [comment]
Theme editor in Storybook has a couple of things, one is having to get our feet wet with Storybook add-on development, another is communicating theme edits to the demonstration UI (called "preview"). In short, the demonstration UI (preview) has a separate frame (`<iframe>`) from the storybook UI. For theme switcher that's do-able as we need to simply [communicate the theme ID user selects](https://github.com/asudoh/carbon-custom-elements/blob/3b0beb2661b7df3bbad92eb067a24a22a6a44964/.storybook/addon-carbon-theme/components/Panel.js#L12), but for theme editor it's more.
