### ISSUE TITLE
Recommend Adding Components: Divider and Scrollbar

### ISSUE THREAD

**Issue by JessicaGentry** [carbon-design-system/carbon#3510]
### Summary

We recommend adding a simple divider line and the visual design and style of scrollbars as elements to Carbon.

The divider is a horizontal or vertical rule used in forms and dashboards for indicating grouping (see the line below KPIs label):

Example:
<img width="624" alt="Screen Shot 2019-07-23 at 11 47 21 AM" src="https://user-images.githubusercontent.com/52802834/61731088-59589300-ad40-11e9-8689-8d852e6cda38.png">

The component scrollbar specifies the design and style of scrollbars within:
Data Tables (shown below)
Forms
Lists
Dropdowns
Comboboxes
Search

Example:
<img width="394" alt="Screen Shot 2019-07-23 at 11 47 54 AM" src="https://user-images.githubusercontent.com/52802834/61731097-5e1d4700-ad40-11e9-9da2-1d8523f1afe9.png">

### Source Files:

https://ibm.box.com/s/bneyyjiqgp0w7jr8zbgdxkwgb0qnbw2t

### Resources

This recommendation is made in part of the Watson IoT Enterprise Design System Effort being carried out by Guidea working with:
Erin Buonomo (ebuonomo@us.ibm.com)
and Chris Reckling (chris_reckling@us.ibm.com) @creckling

**Comment by designertyler** [comment]
We chose to leave the native browser scroll bar to be defined by the OS. This helps with consistency when users move between UI's not using our custom scroll bar. The mockup looks similar to a Mac scroll bar but could feel out of place on a Windows or another OS machine. Using the native OS scroll bar also allows us to maintain any user scrollbar preferences.

![image](https://user-images.githubusercontent.com/19270502/62325626-b3103a00-b471-11e9-8ea0-4badfe8abf56.png)

We've talked about defining rules for our own site, but it doesn't seem to justify its own component. It would be great to see how you guys are using it and we can start to form basic guidelines about how to apply it: color, thickness, number of columns it expands, do's and don'ts, examples of it in use, etc.

**Comment by JessicaGentry** [comment]
This is probably fine as is - but deferring further discussion as we are currently organizing and concatenating all components & issues on our side and determining ownership of ongoing conversations.

**Comment by aagonzales** [comment]
I agree with Tyler. We can look into adding guidance around rules/dividers in the future but seems a low priority at the moment

**Comment by aagonzales** [comment]
Closing for now, but @JessicaGentry please feel free to re-open if your teams has further asks around this.
