### ISSUE TITLE
Recommended Enhancements to Carbon Structured List Component

### ISSUE THREAD

**Issue by JessicaGentry** [carbon-design-system/carbon#3511]
### Summary

We recommend expanding the current Carbon Stuctured List component to include the following features that are required by many patterns:
- List with Search
- Editable List (to add, edit,and delete list items)
- List with Reordering
- Lists with Icons
- Grouped List

Recommendation:
Structured lists can usually benefit from search functionality, so that is a consideration for adding. Almost as common is the need to edit list content including reorder. Consider adding this functionality as an option for structured lists.

Example List with Search:

![Screen Shot 2019-07-23 at 12 06 54 PM](https://user-images.githubusercontent.com/52802834/61732110-873ed700-ad42-11e9-8613-ac86b051c523.png)

Example Simple List Edit Mode:

![Screen Shot 2019-07-23 at 12 07 02 PM](https://user-images.githubusercontent.com/52802834/61732137-9160d580-ad42-11e9-8fb5-f294f7266fc8.png)

Example Hierarchical List in Default (non-edit) Mode:

![Screen Shot 2019-07-23 at 12 07 09 PM](https://user-images.githubusercontent.com/52802834/61732142-94f45c80-ad42-11e9-956d-dc1d77117d0c.png)

### Source Files:

https://ibm.box.com/s/tzafaqapd375v3liqpxzp26z38ou78f0

### Resources

This recommendation is made in part of the Watson IoT Enterprise Design System Effort being carried out by Guidea working with:
Erin Buonomo (ebuonomo@us.ibm.com)
and Chris Reckling (chris_reckling@us.ibm.com) @creckling

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if they have an interest in this. One thing that comes to my mind is a discussion IIUC we had wrt whether this kind of rich feature should be done with data table instead of structured list.

**Comment by shixiedesign** [comment]
Hi @JessicaGentry our design team doesn't have the resources to work on expanding Structured List functionalities at the moment. Please let us know if you'd be able to contribute design / development resources for it. 

**Community components (coming soon)** 

We are working on a strategy to surfacing these incoming design / code as community components. This will be a great entry. We still need a bit more time as the community components framework is a new proposal and still being implemented, more on this in the next minor release.

**Initial feedback**

The attached file is great and provide well organized states and variants of the component. However it doesn't contain any product examples and flows where this component is embedded and used. While for community components, we don't require any of those. If you are hoping to expand Carbon core components, we would need to see any research and audit of alternative solutions, and all explorations made during the design process. 

Let us know if you have more questions! Thank you!
