### ISSUE TITLE
Recommend Adding a Password Field to Carbon

### ISSUE THREAD

**Issue by JessicaGentry** [carbon-design-system/carbon#3512]
### Summary

Carbon does not appear have a password input field. 

Recommendation:
Provide password input field as well as the password modernization guidelines shared with the team (included in Source Files below) 

Example:
<img width="419" alt="Screen Shot 2019-07-23 at 12 19 38 PM" src="https://user-images.githubusercontent.com/52802834/61733198-da198e00-ad44-11e9-8634-9cfd15e331b0.png">

### Source Files:

Sketch Source:
https://ibm.box.com/s/cuaxg2tu4me4l03rawvgisk5qdwizoih

Password modernization guidelines:
https://ibm.box.com/s/okd2n9usyflqp3n80ctsshltu5b9enm6

### Resources

This recommendation is made in part of the Watson IoT Enterprise Design System Effort being carried out by Guidea working with:
Erin Buonomo (ebuonomo@us.ibm.com)
and Chris Reckling (chris_reckling@us.ibm.com) @creckling

**Comment by emyarod** [comment]
do these components meet your requirements?

https://carbon-components-react.netlify.com/?path=/story/textinput--toggle-password-visibility

https://the-carbon-components.netlify.com/component/text-input--password.html

**Comment by JessicaGentry** [comment]
Yes - those do meet our requirements.
The only states we had that are not shown there are a success state (in addition to the error state) that looks like this:
<img width="319" alt="Screen Shot 2019-07-25 at 4 49 06 PM" src="https://user-images.githubusercontent.com/52802834/61911137-2c50df80-aefc-11e9-8b62-bdf7c8515d57.png">

And the optional "i" information icon. 
<img width="311" alt="Screen Shot 2019-07-25 at 4 49 11 PM" src="https://user-images.githubusercontent.com/52802834/61911148-307cfd00-aefc-11e9-8f98-86b108948f8f.png">


But neither are absolutely necessary.

Will this component be added to Carbon in the near future? Thanks!

**Comment by emyarod** [comment]
@JessicaGentry this component was introduced in v9.17.0 for vanilla (ref https://github.com/carbon-design-system/carbon/pull/1060) and v7.3.0 for React (ref https://github.com/carbon-design-system/carbon-components-react/pull/2323)

**Comment by JessicaGentry** [comment]
Sorry, I meant: Is this going to be added to the Carbon Design System so designers can add to screens? Thank you!

**Comment by emyarod** [comment]
I will defer to our designers on design kit questions cc @carbon-design-system/design ?

**Comment by aagonzales** [comment]
@emyarod  Is it a variation of text input or its own component? If we have production code for it then we need to document it on our website as well as adding it to the kit. (Design kit issue should be added to the kit repo: https://github.com/carbon-design-system/carbon-design-kit) 

### Bugs

I'm also seeing some inconsistencies in the two samples you showed. The icons should not be blue, its should be using `$icon-02`

![image](https://user-images.githubusercontent.com/11670886/61963198-b185d400-af90-11e9-82e3-f78a8474407d.png)
![image](https://user-images.githubusercontent.com/11670886/61963248-c8c4c180-af90-11e9-90cc-805b5f692c5a.png)

The placement of the icons in the invalid state is also wrong. I eye should stay on the right and the error/status icons should be on the left

![image](https://user-images.githubusercontent.com/11670886/61967528-31b13700-af9b-11e9-923f-728e8c413e58.png)

This will match what we do for other components that have a persistent icon in the field.
![image](https://user-images.githubusercontent.com/11670886/61967794-e51a2b80-af9b-11e9-8b14-9025b5da14b6.png)


### Success state

The success field would be something like below, without the green outline or success text. I think an always present green outline would be excessive, it doesn't need to draw the users attention like an error does. Its focus would be the normal component `$focus` color (blue in the light themes, white in the dark themes)

![image](https://user-images.githubusercontent.com/11670886/61967457-f6af0380-af9a-11e9-8336-5fe64731b113.png)

**Comment by tw15egan** [comment]
Seems like it's been a component since 11/2018, as just a variation of Text Input. May have been missed in the update to v10. 

Related PR:  https://github.com/carbon-design-system/carbon/pull/1060

All (mostly) related PRs: https://github.com/carbon-design-system/carbon/pulls?utf8=%E2%9C%93&q=is%3Apr+password

**Comment by emyarod** [comment]
@aagonzales it's a variation of text input. as @tw15egan and I mentioned, it was first introduced in Sept 2018 and ported to v10 shortly afterwards. I opened #3552 and #3553 to address the issues you found. we currently don't have a success state but we can add that once the spec is updated/finalized

**Comment by creckling** [comment]
there is an open issue in the design kit repo: https://github.com/carbon-design-system/carbon-design-kit/issues/143

**Comment by jeanservaas** [comment]
Once this spec is updated for the success state and we code it we will add it to the design kit. @aagonzales is working on adding the password field variation to design kit now.

**Comment by JessicaGentry** [comment]
Sorry for the delay - we are working on centralizing our list of updates/changes and determining who is responsible for managing these conversations. We'll get back to this asap.

**Comment by laurenmrice** [comment]
not stale

**Comment by tw15egan** [comment]
Closing this as it seems to be a documentation issue now (https://github.com/carbon-design-system/carbon-website/issues/92), and it has already been added to the kit (https://github.com/carbon-design-system/carbon-design-kit/issues/143)
