### ISSUE TITLE
'yarn' code not working in terminal

### ISSUE THREAD

**Issue by jwsese** [carbon-design-system/carbon#3514]
## What package(s) are you using? I've gone through most of the steps for contributing to Carbon but I did the Yarn step out of order and now, when I run the 'yarn' command from terminal, I get a `command not found` error.

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
See above

> Is this issue related to a specific component?
Yarn

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
I am working from these directions and I'm on step 3. https://github.com/carbon-design-system/carbon-website/wiki/Updating-content-on-carbondesignsystem.com#step-1-get-a-local-version-of-the-github-repo-on-your-computer

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Did you install `yarn`?

**Comment by jwsese** [comment]
thanks @asudoh i did, but not in the right order. does that matter?

**Comment by asudoh** [comment]
Not sure what you meant, but `yarn` itself is not our project and you can google for setup instructions of `yarn`. Let us know if you have any other Carbon questions.
