### ISSUE TITLE
CI failing on icons-angular build step: Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#3519]
## Detailed description

> Describe in detail the issue you're having.

Our CI test runner is failing with the error: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

I'm unable to reproduce this error locally, it likely has to do with just the CircleCI test runner

here is an example stack trace: https://circleci.com/gh/carbon-design-system/carbon/4254

**Comment by lovemecomputer** [comment]
in case this little  bit of extra context helps, i'll just point out that in my branch for PR #3501 , i'm getting slightly different errors in github-connected circleci, as opposed to local build errors.

[**circleci results in github**](https://circleci.com/gh/carbon-design-system/carbon/4226?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link): 
```
…
@carbon/icons-angular: Aborted (core dumped)
@carbon/icons-angular: error Command failed with exit code 134.
@carbon/icons-angular: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@carbon/icons-angular'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
…
```

**local:**
```
…
@carbon/icons-angular: error Command failed with signal "SIGABRT".
@carbon/icons-angular: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@carbon/icons-angular'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
…
```

(sorry if that's not relevant/related to issues in my branch!)

**Comment by lovemecomputer** [comment]
in pr #3501 i commented out the build step for `icons-angular`, to allow circleci to pass.

created a specific issue to fix the issue in `icons-angular` here: https://github.com/carbon-design-system/carbon/issues/3522 , and cross-referenced this issue.

thanks @emyarod !

**Comment by cal-smith** [comment]
I can't reopen, but this isn't actually fixed 🙂

**Comment by joshblack** [comment]
Closing this as the project has been moved out of the repo 👍
