### ISSUE TITLE
MIT License ?

### ISSUE THREAD

**Issue by vilbht** [carbon-design-system/carbon#352]
Hello

Is the open source license an MIT license? Couldn't find any specific mention to it.
Could you kindly clarify?

Thanks

**Comment by asudoh** [comment]
Hi @vilav It’s Apache-2 instead, please see:
https://github.com/carbon-design-system/carbon-components/blob/ab384e5a6721c06052bb971ce688b46eff50c9b9/package.json#L143
https://github.com/carbon-design-system/carbon-components/blob/master/LICENSE.md
