### ISSUE TITLE
Color Black is showing with grey outline

### ISSUE THREAD

**Issue by yumeforever** [carbon-design-system/carbon#3521]
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

Color bug in the libraries:
`Grey 10`
`Grey 90`
`White` 

The color `Black` swatch come with a grey outline:

## Screenshots

<img width="635" alt="image" src="https://user-images.githubusercontent.com/3612533/61748544-c0a62f80-ada0-11e9-80ec-3a2b0f411664.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/3612533/61748612-fb0fcc80-ada0-11e9-8cf5-98657beceb46.png">

**Comment by laurenmrice** [comment]
fixed !
