### ISSUE TITLE
icons-angular: memory issues causing circleci fail. build is currently deactivated.

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon#3522]
icons-angular failing at build, likely due to memory issues with the extremely-large number if icons we have.

`packages/icons-angular/tasks/build.js` has been commented out to prevent `icons-angular` from building, until a fix is found.

ref issues:

- https://github.com/carbon-design-system/carbon/pull/3501#discussion_r306563648 
  - this is the PR which comments out the `icons-angular` build step
- https://github.com/carbon-design-system/carbon/issues/3519
  - this is another reporting of this error with some detail and specifics of stack trace

**Comment by cal-smith** [comment]
I can't reopen, but this isn't actually fixed 🙂

**Comment by tw15egan** [comment]
@cal-smith any idea if this is still an issue?

**Comment by cal-smith** [comment]
This can be closed! We moved `icons-angular` out so any new memory/build issues will be handled in the new repo
