### ISSUE TITLE
ProgressIndicator - strange default look, steps are separated and cut off - Carbon v10

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#3526]
ProgressIndicator - strange default look, steps are separated and cut off (ellipsis) even there is enough space.
![image](https://user-images.githubusercontent.com/17591704/61780693-435fd680-ae03-11e9-8105-593fc92fbf96.png)

https://codesandbox.io/embed/codesandbox-tj9on

@emyarod 

    "carbon-components": "10.4.1",
    "carbon-components-react": "7.4.1",
    "carbon-icons": "7.0.7",

**Comment by emyarod** [comment]
looking to see why this rule was included/if it's needed, but for now it looks like a workaround would be to override the `flex: 1` rule on `.bx--progress-step`

**Comment by tomkdgun** [comment]
@emyarod How to get this fix ? It seems it was merged but version of the package doesn't changed.

**Comment by asudoh** [comment]
We have a monthly-ish release cycle. Stay tuned!
