### ISSUE TITLE
[Dropdown] Change default selection behavior

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3531]
We need to change the default selection behavior of dropdown to include the current selection in place in the dropdown drawer with a checkmark inline.

Currently we do this two different ways. In Vanilla we take the option that is selected out of the dropdown drawer. In React we leave the option that is selected inside of the drawer with a selection state (the option that is selected does not move up to the top of the list, it stays in place inside the drawer.) It would be good to keep these consistent and include the checkmark in the drawer selection so it is more obvious and visible.

Ref conversation in #1936

**Current:**
![Current default.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/18db465e-7d87-42f3-97f2-f748883debfc)

**New:**
![New default.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/dc62e012-c766-427e-a9f9-fd730c09c77b)

**Comment by laurenmrice** [comment]
not stale this needs to be implemented

**Comment by laurenmrice** [comment]
not staleeeeeeeeee 😭

**Comment by laurenmrice** [comment]
not stale

**Comment by asudoh** [comment]
Same as #3988 and addressed by #4753.
