### ISSUE TITLE
SelectableTile - fix failed prop type warning for checked for v9

### ISSUE THREAD

**Issue by astha-jain** [carbon-design-system/carbon#3537]
SelectableTile - fix failed prop type warning for checked for v9

## Detailed description

> Describe in detail the issue you're having.
failed proptype warning message showing up.

> Is this issue related to a specific component?
SelectableTile

> What did you expect to happen? What happened instead? What would you like to
> see changed?
do not show any warnings

> What browser are you working in?
Chrome

Please port the changes done in PR #3431 for V10 to V9 a well. 
@emyarod

**Comment by emyarod** [comment]
@astha-jain the v9 component doesn't appear to have the errors described in #3431. can you create a Code Sandbox showing the errors you see with the v9 SelectableTile?

**Comment by astha-jain** [comment]
Hey @emyarod, do you know when these changes will be moved over to v9? 
![Screen Shot 2019-08-06 at 12 02 16 PM](https://user-images.githubusercontent.com/21059894/62556076-21724500-b842-11e9-85a9-53e845f924e4.png)

**Comment by emyarod** [comment]
#2401 is still open/in review but whenever it's merged in and a new release is created

**Comment by emyarod** [comment]
https://github.com/carbon-design-system/carbon-components-react/pull/2401
