### ISSUE TITLE
Dropdown: please use visibility:hidden when hiding

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#3539]
The Dropdown component uses `opacity: 0` to hide items in the dropdown list.
This is a problem for accessibility because the items are still in the reading order, and screen reader users can see them if they are using virtual cursor navigation.

The DAP catches this - sort of - by complaining about the color contrast when the list items are transparent:

![image](https://user-images.githubusercontent.com/3331913/61887939-9c497080-aed0-11e9-88a4-efcbe2976285.png)

To fix this without affecting the animation of the list, please add visibility: hidden (and visibility: visible) to the hide/show code for the dropdown list. (not sure if adding it to the list itself or to the list items is "better").

Here are some blog posts that may be helpful in this area:
- https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/
- https://medium.engineering/five-goofy-things-medium-did-that-break-accessibility-3bc804ae818d

Also: not sure if there are other components that also use opacity: 0 to hide stuff? please search the Carbon codebase for the pattern to ensure that all are using visibility: hidden as well.

**Comment by jendowns** [comment]
@carmacleod I agree with this! I proposed a little fix here: https://github.com/carbon-design-system/carbon/pull/3541 🤔 I'm curious what the maintainers think, but it should cover the a11y need you noted.
