### ISSUE TITLE
Update @carbon/icons-vue with new icon strategy

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3542]
We've currently updated our strategy for icons in `@carbon/icons-react`, this issue is for:

- [ ] Mirroring the setup in `@carbon/icons-vue`
- [ ] Making sure we can provide a solid storybook showing how to use the iconography assets
- [ ] Updating the README.md file where appropriate

**Comment by dakahn** [comment]
ref #3477 

Some high level TODOs:
1. set up an ESM `index.js` with all the icons (so that `import { Add16 } from '@carbon/icons-vue'; works)
2. update all ESM aliases (/es/add/16.js) to import the entrypoint
3. make sure CJS aliases still alias module directly
