### ISSUE TITLE
[DataTable] Invalid readme link in storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#3544]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

In the DataTable story info.text, the `readmeURL` is pointing to the old repo, not the monorepo.

http://react.carbondesignsystem.com/?path=/story/datatable--default

Looks to be a short url: https://goo.gl/dq6CEK

## Steps to reproduce the issue

1. `Show info` on the datatable default story (and others)
2. See that the link near the top points to the wrong spot

![image](https://user-images.githubusercontent.com/3360588/61899945-2cdc7c80-aee2-11e9-82c1-2c075fb5f5e4.png)

**Comment by tw15egan** [comment]
Nice catch! Just pushed up a fix
