### ISSUE TITLE
UI Shell Header Nav not showing Menu Items

### ISSUE THREAD

**Issue by Heather-Fin** [carbon-design-system/carbon#3546]
Navigation bar no longer showing Repositories tab in Carbon Tutorial. Works when using a previous version of carbon components (10.3.0 and 7.3.0).
@mattrosno 

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The Header Menu Items no longer show up when wrapped inside the Header Navigation in the Carbon React tutorial step 1.

> Is this issue related to a specific component?
Header Navigation

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components: 10.4.1
carbon-components-react: 7.4.1

## Additional information
Without being wrapped in Header Navigation:
<img width="1047" alt="Screen Shot 2019-07-25 at 4 01 38 PM" src="https://user-images.githubusercontent.com/43322948/61910865-68d00b80-aefb-11e9-8b32-04db60f25595.png">
With being wrapped:
<img width="1040" alt="Screen Shot 2019-07-25 at 4 02 23 PM" src="https://user-images.githubusercontent.com/43322948/61910871-6c639280-aefb-11e9-9c47-68ad167d80aa.png">

**Comment by tw15egan** [comment]
Just ran through the tutorial using the latest Carbon `"carbon-components": "^10.9.2"` and this doesn't seem to be an issue anymore. Going to close this for now, feel free to reopen if you are still seeing this.

**Comment by fe01134** [comment]
I hit this as well.    I think a response explain how this works would be helpful please? I haven't been able to figure this out using the doc.
