### ISSUE TITLE
Icon size issue - 32/error--filled

### ISSUE THREAD

**Issue by nicholas-davis** [carbon-design-system/carbon#3548]
The error--filled is NOT rendering at 32x32

error--filled icon:
https://carbon-elements.netlify.com/icons/examples/preview/#32%2Ferror--filled

Screenshot # 1:
![image](https://user-images.githubusercontent.com/7907039/61955139-65369600-af88-11e9-934e-0b513fa09959.png)

Screenshot # 1:
![image](https://user-images.githubusercontent.com/7907039/61955268-9a42e880-af88-11e9-8c38-9f76b8e8e1d7.png)

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by joshblack** [comment]
A fix was merged in, expect it in our next patch release next week!
