### ISSUE TITLE
<ibm-date-picker cannot show in <ibm-tabs, please fix issue

### ISSUE THREAD

**Issue by klower** [carbon-design-system/carbon#3557]
![image](https://user-images.githubusercontent.com/4176873/61957361-b4fd7780-aff1-11e9-957e-5ff4c73044d4.png)

![image](https://user-images.githubusercontent.com/4176873/61957384-c050a300-aff1-11e9-9983-404532e13c17.png)

click calendar input, nothing happened

**Comment by asudoh** [comment]
Hi @klower do you want to report this at https://github.com/IBM/carbon-components-angular/issues?

**Comment by joshblack** [comment]
Hi @klower! 👋 Thanks so much for taking the time to make an issue. I'm going to close this because it's been open for a couple of months, feel free to comment if you'd like to talk about this more!
