### ISSUE TITLE
[Toast] Getting: Attempted import error: 'NotificationActionButton' is not exported from 'carbon-components-react'.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3559]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I'm trying to follow the example of Toast from StoryBook but I'm getting this error:
Attempted import error: 'NotificationActionButton' is not exported from 'carbon-components-react'.

What is the Action button in inlineNotification stands for?

I was expecting to see a button that triggers the add/remove to/from toast, are there such hooks for adding removing?

For now I used a Tooltip to display the notifications inside:
![image](https://user-images.githubusercontent.com/26740851/62010076-b607e380-b16e-11e9-8198-322b8c9789fb.png)

But I'm facing some issues with that. For example when clicking on the close button of one notification the tooltip is closed and the notification does not disappear when opening the tooltip again.
If I putt the notification outside the tooltip, the close button works. But I don't want to have notifications floating on the screen, I need to put them all in one drawer and handling it as a state array that I can add/remove from. 
I'll try to use the onCloseButtonClick event to remove from the list, and push to the state array to add new ones... 

1) Is it a good approach or there is something more acceptable?
2) Is there a way to prevent the tooltip window auto close when removing a notification. To be closed only when pressing on the tooltip icon for example.
3) Is there a max-height property that makes the opened window with scroll bar if there are many notification?

this. what happens if I set max-height:
![image](https://user-images.githubusercontent.com/26740851/62025700-9fe73b00-b1e1-11e9-83e6-455e0a380433.png)

## Relevant information

Please check this sandbox:
https://codesandbox.io/s/brave-voice-bdrx0

4) How to make the tooltip icon with white color
I tried making the Tooltips icons white by adding :

> .bx--tooltip {
  max-width: none;
  /*width: 100%;*/
}

> .bx--tooltip-icon svg {
  fill: white;
}

But it didn't work for me.

Sorry for listing more than one item in the same thread, if needed will split.

**Comment by asudoh** [comment]
Hi 👋 `<NotificationActionButton>` is something that was introduced in our recent release. That said, would you want to upgrade `carbon-components-react`?

**Comment by zbeedatm** [comment]
I'll do the upgrade soon. But anyway I didn't use the inline notification at the end and implemented a solution with the ToastNotitification as I described.

Can you please try to help me with issues 2, 3 & 4?
I still don't know how to solve them.

Regards.

**Comment by asudoh** [comment]
I don't think notification in tooltip is something our design team intends. CC @carbon-design-system/design just in case.

**Comment by shixiedesign** [comment]
Hi, toast notification should be free floating and triggered by system and goes away either via user action or after a short delay. If you want to display notifications in a panel, I think you'd need a custom component, or styled version of structured list.

**Comment by asudoh** [comment]
Thanks @shixiedesign for your feedback! @zbeedatm Please make sure working with your designers to figure out the design that fits well with Carbon design ecosystem. If your designer still comes back with the design seen in the screenshot above, please follow what @shixiedesign suggested.

**Comment by toshakamath** [comment]
Similar issue with TableCell as well. Getting "Attempted import error: 'TableCell' is not exported from 'carbon-components-react'."

**Comment by asudoh** [comment]
^ Sounds a different one, if you have a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox feel free to enter an issue. Thanks!
