### ISSUE TITLE
React does not recognize the `dataIconPath` prop on a DOM element.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3562]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Getting this warning:

> Warning: React does not recognize the `dataIconPath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataiconpath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in path (created by WarningFilled16)
    in svg (created by WarningFilled16)
    in WarningFilled16 (created by ForwardRef(TextInput))
    in div (created by ForwardRef(TextInput))
    in div (created by ForwardRef(TextInput))
    in ForwardRef(TextInput) (at ProjectsList.js:221)
    in div (created by ModalBody)
    in ModalBody (at ProjectsList.js:199)
    in div (created by ComposedModal)
    in div (created by ComposedModal)
    in ComposedModal (at ProjectsList.js:190)
    in td (at ProjectsList.js:182)
    in tr (at ProjectsList.js:171)
    in tbody (at ProjectsList.js:170)
    in table (at ProjectsList.js:169)
    in div (at ProjectsList.js:168)
    in td (at ProjectsList.js:166)
    in tr (at ProjectsList.js:165)
    in tbody (at ProjectsList.js:164)
    in table (at ProjectsList.js:163)
    in ProjectsList (at App.js:44)
    in body (at App.js:39)
    in div (at App.js:34)
    in App (created by Context.Consumer)
    in Route (at src/index.js:15)
    in Switch (at src/index.js:14)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:13)
    in div (at src/index.js:12)
console.<computed> @ index.js:1446
warningWithoutStack @ react-dom.development.js:520
warning @ react-dom.development.js:2752
validateProperty$1 @ react-dom.development.js:7610
warnUnknownProperties @ react-dom.development.js:7653
validateProperties$2 @ react-dom.development.js:7676
validatePropertiesInDevelopment @ react-dom.development.js:7720
setInitialProperties @ react-dom.development.js:7996
finalizeInitialChildren @ react-dom.development.js:9158
completeWork @ react-dom.development.js:17644
completeUnitOfWork @ react-dom.development.js:20108
performUnitOfWork @ react-dom.development.js:20315
workLoop @ react-dom.development.js:20326
renderRoot @ react-dom.development.js:20406
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
scheduleRootUpdate @ react-dom.development.js:21610
updateContainerAtExpirationTime @ react-dom.development.js:21636
updateContainer @ react-dom.development.js:21704
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:22017
(anonymous) @ react-dom.development.js:22169
unbatchedUpdates @ react-dom.development.js:21492
legacyRenderSubtreeIntoContainer @ react-dom.development.js:22165
render @ react-dom.development.js:22240
./src/index.js @ index.js:11
__webpack_require__ @ bootstrap:781
fn @ bootstrap:149
0 @ RestService.js:373
__webpack_require__ @ bootstrap:781
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 5 more frames

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No warning should be thrown.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^10.2.0",
    "carbon-components-react": "^7.2.0",
    "carbon-icons": "^7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Declare an icon and use it!
`import Warning20 from '@carbon/icons-react/lib/warning/20';
<Warning20 />`

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
#3234 seems to tell us that the issue has been resolved. Would you want to upgrade `@carbon/icons-react` and possibly `carbon-components-react` as well?

**Comment by zbeedatm** [comment]
Upgraded:

![image](https://user-images.githubusercontent.com/26740851/62111919-50c10900-b2ba-11e9-8950-b40b8e72b02d.png)

But now I'm getting:

>index.js:1446 Warning: React does not recognize the `floatingMenu` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `floatingmenu` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ClickListener)
    in ClickListener (created by OverflowMenu)
    in OverflowMenu (created by ForwardRef(OverflowMenu))
    in ForwardRef(OverflowMenu) (at TDFToolbar.js:179)

And:

>The prop `small` for Button has been deprecated in favor of `size`. Please use `size="small"` instead.

despite I'm not setting the size property for the button!

And: 

> Warning: Failed prop type: Invalid prop `aria-hidden` of type `boolean` supplied to `Icon`, expected `string`.

despite I'm not setting that property as well!

**Comment by asudoh** [comment]
Would you create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox? Also please make sure looking at react.carbondesignsystem.com to see how to use our components.

**Comment by zbeedatm** [comment]
Reduced in:
https://codesandbox.io/s/codesandbox-s4osh

**Comment by asudoh** [comment]
Could you please provide the link? My one cannot be directly edited and thus you should have a new link.

**Comment by zbeedatm** [comment]
Sorry, https://codesandbox.io/s/codesandbox-s4osh

**Comment by asudoh** [comment]
Here's what I see by accessing the CodeSandbox link:

![image](https://user-images.githubusercontent.com/1259051/62350456-bcff6f00-b53d-11e9-8f97-ecfea4e47250.png)

**Comment by zbeedatm** [comment]
seems that you attempt to access it at the same time that I updated it with other component.
I used it for other issue with DataTable (https://github.com/carbon-design-system/carbon/issues/3621).

To avoid confusion I created a new one based on the first:
https://codesandbox.io/s/reverent-firefly-pyc03

![image](https://user-images.githubusercontent.com/26740851/62420279-27c4bd80-b698-11e9-932f-ab54d4ccf664.png)

**Comment by asudoh** [comment]
https://codesandbox.io/s/reverent-firefly-pyc03 does not seem to yield the warning described in this issue. The issue author seems to be reusing a single CodeSandbox for multiple issue, which seems to have caused the confusion.

**Comment by zbeedatm** [comment]
Nope, I separated the sandboxes.
The main issue was opened for:

> React does not recognize the `dataIconPath` prop on a DOM element.

Then you asked me to upgrade, so I did that and replied that now I'm getting other warnings (the orginal one gone), one of these warnings is:

> Warning: React does not recognize the `floatingMenu` prop on a DOM element.

If needed I'll edit the issue title or open a new one and close this one!

**Comment by asudoh** [comment]
Yeah, one problem for one GH issue please. Also if I search for `reverent-firefly-pyc03` in this repo I see two issues already.

**Comment by zbeedatm** [comment]
Opened a new one (https://github.com/carbon-design-system/carbon/issues/3656)
You can close it

**Comment by asudoh** [comment]
Cool thanks @zbeedatm!
