### ISSUE TITLE
TableToolBarSearch overlaps the TableBatchActions when the search bar is active

### ISSUE THREAD

**Issue by gin-nader** [carbon-design-system/carbon#3566]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Since we have upgraded to carbon-components 10.4.0 and carbon-components-react 7.4.0, we are seeing an issue where if the DataTable TableToolBarSearch component has text in it, then the TableBatchActions will not show up. TableBatchActions works as intended if the TableToolBarSearch 
does not have any text in it.

> Is this issue related to a specific component?

TableBatchActions, DataTable, and TableToolBarSearch 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect TableBatchActions to take precedence over TableToolBarSearch  even if there is text in the search bar. I would like that to be the case.

> What browser are you working in?

Google Chrome.

> What version of the Carbon Design System are you using?

10.4.0

## Steps to reproduce the issue

1. Have a DataTable that uses both TableBatchActions  and TableToolBarSearch  
2. Type text in TableToolBarSearch  
3. Click on a checkbox in the DataTable
4. Notice that the TableBatchActions  don't appear.

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/codesandbox-0rbvh?fontsize=14

Notice that when you type in the search bar and click on the checkbox, the options do not show up.

**Comment by asudoh** [comment]
Hi 👋 your `<TableToolbarSearch>` should be wrapped in `<TableToolbarContent>`. Please refer to the [corresponding story](https://github.com/carbon-design-system/carbon/blob/v10.4.1/packages/react/src/components/DataTable/stories/with-batch-actions.js) for the details.
