### ISSUE TITLE
[Dropdown] Disabled text & icon should be $disabled-02

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3571]
I think I have made a mistake in  #3217 . The disabled text and icon (in both inline and default dropdowns) should be `$disabled-2` so the disabled body copy & label are always the same color. I will make a new issue out of this comment and please go ahead to merge this PR! Thanks! 

![image](https://user-images.githubusercontent.com/15144993/62078650-b6f25100-b212-11e9-9168-ab1b736eb1b8.png)

_Originally posted by @shixiedesign in https://github.com/carbon-design-system/carbon/pull/3411#issuecomment-516143143_

**Comment by jendowns** [comment]
Hey @shixiedesign! I just opened a quick PR for this here: #3575 

I also updated the disabled text & icon fill for the `ListBox` as well, since it was part of the changes in #3217 (is that correct?)
