### ISSUE TITLE
Need an indeterminate state for checkbox component

### ISSUE THREAD

**Issue by niralmunjariya** [carbon-design-system/carbon#358]
## Need an indeterminate state for checkbox component

**Is this issue related to a specific component?** 
Yes, Checkbox.

**What did you expect to happen? What happened instead? What would you like to see changed?**
I need an indeterminate state in carbon checkbox component.

**What browser are you working in?**
Google Chrome

**What version of the Carbon Design System are you using?**
7.22.0

Similar like this:

![indeterminate-state](https://user-images.githubusercontent.com/6047431/31493097-5e03b10c-af6b-11e7-9a50-775097b808f5.PNG)

**Comment by aagonzales** [comment]
Yup, we're working on it. We have it as a to-do.

**Comment by tay-aitken** [comment]
## Proposed designs
![checkbox](https://user-images.githubusercontent.com/29312997/33327470-8f7be7e8-d425-11e7-879c-914c1003de67.png)
@aagonzales @bsonefeld thoughts?

**Comment by bsonefeld** [comment]
Looks good to me. @niralmunjariya can you explain your use case / user flow behind needing this so we can better understand how to design for it?

**Comment by tay-aitken** [comment]
@bsonefeld this also links into an issue we have on the internal repo. I know one of the cases is on a table with checkboxes.

**Comment by aagonzales** [comment]
Yes, it normally indicates when some items are checked but not all. It appears only as the top checkbox in the header row. And checkmark in this position normally indicates all items are checked.

**Comment by niralmunjariya** [comment]
@bsonefeld I want it for the same use case mentioned by @aagonzales

**Comment by marijohannessen** [comment]
This is in a PR https://github.com/carbon-design-system/carbon-components/pull/465

**Comment by marijohannessen** [comment]
Closing this one as the vanilla version is done 🎉
