### ISSUE TITLE
[File uploader] Several bugs in style & behavior 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3587]
Several bugs in File uploader: 

_Vanilla_ 

- [x] Where is the normal file uploader? I only see drag and drop?

_React_ 

- [x] Button should be our default 48 button, not small
- [x] File that is uploaded should be 40px not 32px.
- [x] Close icon wrong
- [x] There shouldn't be a `Clear file` button.

![image](https://user-images.githubusercontent.com/15144993/62151341-b961b300-b2c5-11e9-9d31-6bbddc39a32f.png)

- [ ] This `File uploader button` is a new thing. I don't think it should be a component, and its behavior is not something we want.

**Comment by laurenmrice** [comment]
In Vanilla:
The `close` icon is not showing up when you add a file.

![Screen Shot 2019-07-31 at 3.03.07 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/f6c9f4f9-ae8f-40c6-aab4-e346cd2b9769)

**Comment by laurenmrice** [comment]
Ref #4330 . Need bug fixes before starting theming
