### ISSUE TITLE
Vanilla JS Tooltip and React Tooltip components have inconsistent behavior

### ISSUE THREAD

**Issue by MarkFalconbridge** [carbon-design-system/carbon#3601]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When experimenting with the tooltip component here - https://www.carbondesignsystem.com/components/tooltip/code if you tab through the tooltip components they each display the popup when they receive focus.

Looking at the react component here - http://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom, it doesn't behave in the same way.

Also, looking at the code for the React tooltip there is a lot of code that looks as though it's meant to be handling hover events but those event handlers aren't hooked up to anything, certainly no popup appears on hover in the storybook example.

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I'd expect consistency between the two implementations.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by elizabethsjudd** [comment]
Related PR: #3476 to make a11y updates to Vanilla Tooltip component.
