### ISSUE TITLE
[Dark theme, Input Modal/Form, Sketch kit] Input fields background is not correct

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3605]
**Dark theme, Form/Input Modal** Input fields background is currently darker than background. Should be using `field-02` token, which is lighter than background.

_Current kit Gray100 & Gray90 theme **Form modal** component_

![image](https://user-images.githubusercontent.com/15144993/62228231-df00c200-b382-11e9-8f3a-7707aa687bd1.png)

_Should be_ 

![image](https://user-images.githubusercontent.com/15144993/62228557-841b9a80-b383-11e9-98d9-7353f62acb39.png)

**Comment by aagonzales** [comment]
Issue moved to [carbon-design-system/carbon-design-kit #164](https://github.com/carbon-design-system/carbon-design-kit/issues/164) via [**ZenHub**](https://www.zenhub.com/)
