### ISSUE TITLE
[Themes] inline theme mixins reset global theme outside of mixin scope

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#3619]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Bug identified here: https://github.com/carbon-design-system/carbon/issues/3570

Whenever the following theme mixin...

```scss
// Styles that have global theme applied 
// ...
@include carbon--theme(THEME) {
    // Styles that use scoped / inline theme
}
// ...
// Styles that should have global theme applied
```

... is used to apply a specific theme in a scoped situation, it ends up reseting the theme for all styles that follow outside of the scope of the mixin.

The documentation for the mixin is here: https://github.com/carbon-design-system/carbon/blob/master/packages/themes/README.md#sass

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect this inline theme mixin to stay scoped. If I set a Theme A outside of this mixin and then apply Theme B inside this inline mixin, I would expect everything outside of this scope to remain Theme A.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Security

## Steps to reproduce the issue

Apply a style rule using a different theme within the scope of `@include carbon--theme([THEME-NAME])` to see tokens that follow it be switched to the theme used in the scope of the mixin, not the "global" theme you set.

**Comment by asudoh** [comment]
[The reset logic](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/themes/scss/_mixins.scss#L93) seems to tell that it'll work as long as theme A is set to `$carbon--theme`. @jendowns Please let us know if you think otherwise.

**Comment by tw15egan** [comment]
If you have a custom theme it will reset it to the default values, however. In the original issue, the user was trying to set `$focus` to red and after the inline theme call, `$focus` was set to the default theme behavior.

**Comment by joshblack** [comment]
@jendowns are you still running into this? Surprised that this bug is occurring 🤔

**Comment by jendowns** [comment]
@joshblack Personally I never saw this issue myself, I just reported it based on that comment in #3570 😅 

But since reporting this issue here, I haven't come across this bug in my work at all. And it has indeed been QUITE some time since this issue was created 🤔 

I'm going to go ahead and close this one out. Can't replicate/see it happening myself.
