### ISSUE TITLE
DataTable Warning: Failed prop type: Invalid prop `rows[0]` of type `array` supplied to `DataTable`, expected `object`.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3621]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
Getting this warning when using DataTable:

> Warning: Failed prop type: Invalid prop `rows[0]` of type `array` supplied to `DataTable`, expected `object`.

And I'm facing a problem with refreshing the content of the data table.
I have a state variable (rows) that is attached to the data table, but I'm not fetching all the records at once and I have 2 buttons: next/prev.

I can see that the data that is coming from api when calling next/prev page is different and doing this.setState{rows: data}, but the data table is not refreshed and keep showing the first page only!

## Relevant information

Sandbox: https://codesandbox.io/s/codesandbox-s4osh

**Comment by tw15egan** [comment]
When I try running your CodeSandbox, it is not able to compile. Can you create a reduced test case so we can try to isolate the issue?

**Comment by zbeedatm** [comment]
It's up and running:

![image](https://user-images.githubusercontent.com/26740851/62420234-7a51aa00-b697-11e9-83bf-7ffb96d764b3.png)

**Comment by asudoh** [comment]
I'm seeing the error, too. Would you want to fix?

**Comment by zbeedatm** [comment]
Sure! is it related to my code or your component?

**Comment by asudoh** [comment]
Would you reduce your test case more to see that?

**Comment by zbeedatm** [comment]
reduced as much as I can to have the data table only, please take a look now

**Comment by asudoh** [comment]
You have:

```javascript

{
  id: 0,
  ...
},
```

Did you mean below instead, given the row ID in data table should be a string? (As the console warning literally tells)

```javascript

{
  id: '0',
  ...
},
```

**Comment by zbeedatm** [comment]
The warning says: "expected object", and numbers in javascript are objects as I know (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)... but any way that helps, thanks.

I'm still facing a serious problem with refreshing the table, I have the rows attribute of the data table assigned with a state variable called rows, and when calling the api to get next page this state variable is changed and includes the new results but the data table still show the first page all the time!

Maybe it's related to the fact, that the table itself has a column called "ID" that conflicts with the "id" that we add as identifier for each row?!

![image](https://user-images.githubusercontent.com/26740851/62453331-ce818a80-b77a-11e9-8117-93147b165595.png)


**Actually I added Next/Prev to my sandbox and it seems working right with "id". I'll try to figure out what's wrong with my code.**

**Comment by zbeedatm** [comment]
I found the issue, I had to reset the state rows variable (to empty array []) each time i call Next/Prev before filling it with the new values coming from api.

Last thing (it's also related to my code and not to the component), setting the id still giving this warning:
Invalid prop `rows[0]` of type `array` supplied to `DataTable`, expected `object`.

in Sandbox I assigned it with hardcoded string ("<value>"), in my code I'm building it dynamically, I tried .toString() but didn't fix it!

`buildRows(data) {
        console.log("Data: ", data)
        this.setState({rows: []})

        let rows = [];
        let k = 0;
        data.forEach(function(row)
        {
            //console.log("Row ", row)
            let jsonData = []
            jsonData["id"] = k.toString();
            k++;`

**Comment by asudoh** [comment]
^ Do you have your latest code in CodeSandbox?

**Comment by zbeedatm** [comment]
Yes, I used i.toString() there for rows with id 0.
But it's not reproducible... will try to find out what is different in my code!

**Comment by matias-quezada** [comment]
@zbeedatm don't use arrays as dictionaries.

In your screenshot we can see 20 arrays with 0 length and named properties. That might be the root of the issue.

**Comment by zbeedatm** [comment]
Thanks a lot for your advice. yes, that was the issue.
