### ISSUE TITLE
Unable to identify tile selection when the background is dark in the Selectable Tile

### ISSUE THREAD

**Issue by niralmunjariya** [carbon-design-system/carbon#363]
## Detailed description

In the Selectable Tile component, when the background is not light then it's difficult to identify whether the tile is selected or not.

**Is this issue related to a specific component?** 
Yes, Selectable Tile.

**What did you expect to happen? What happened instead? What would you like to see changed?**
I think the check sign should be white instead of transparent so that it should be visible regardless of background color.

**What browser are you working in?**
Google Chrome

**What version of the Carbon Design System are you using?** 
7.22.0

**Screenshots**

![tile-selection2](https://user-images.githubusercontent.com/6047431/31533399-a4f5f9ae-b00f-11e7-8349-49097603a629.PNG)
- Check sign is visible.

![tile-selection1](https://user-images.githubusercontent.com/6047431/31533400-a530bd46-b00f-11e7-81fe-5d8c4cefa48d.PNG)
- Check sign is invisible.

Thanks in advance.

**Comment by bsonefeld** [comment]
Hey @niralmunjariya , thanks your question! 

You can modify the Selectable Tile `_tile.scss` file to override the checkmark's existing styles. I would recommend using `$inverse-01` against a photo background.

**Comment by niralmunjariya** [comment]
@bsonefeld 
I've already tried that but that didn't resolve the issue.
In the checkmark SVG, I have access to change the fill color from the `_tile.scss` but the inner part is transparent and which is the actual thing that causing the issue.

Let me know if there is any other way to fix this.
Thanks!

**Comment by tw15egan** [comment]
This should be fixed on the component side. I'll take a look and update when fixed 😄
