### ISSUE TITLE
Ghost button text changing colors to black

### ISSUE THREAD

**Issue by aradhikaIbm** [carbon-design-system/carbon#3634]
## What package(s) are you using?

- [ x] `carbon-components`
- [ ] `carbon-components-react`
- [ x] `carbon-components-angular`

## Detailed description

> Describe in detail the issue you're having.
In the latest v10.4, we noticed the ghost text is changing to black when you hover over them. Per the guidelines it should be blue. 

> Is this issue related to a specific component?
Ghost buttons

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Stay blue per the spec: https://www.carbondesignsystem.com/components/button/code

> What browser are you working in?
Chrome, FF

> What version of the Carbon Design System are you using?
v10.4

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IWR

## Additional information

adding the button scss where I see  different color being setting on focus or hover.

.#{$prefix}--btn--ghost {
   @include button-theme(
     transparent,
     transparent,
     $link-01,
     $hover-ui,
     currentColor,
     $active-ui
   );
   padding: $button-padding-ghost;
   .#{$prefix}--btn__icon {
     position: static;
     margin-left: $carbon--spacing-03;
   }
   &:hover,
   &:active {
     color: $icon-01;
     .#{$prefix}--btn__icon path {
       fill: $icon-01;
     }
   }
   &:active {
     background-color: $active-ui;
   }
   &:disabled,
   &:hover:disabled,
   &:focus:disabled,
   &.#{$prefix}--btn--disabled,
   &.#{$prefix}--btn--disabled:hover,
   &.#{$prefix}--btn--disabled:focus {
     color: $disabled;
     background: transparent;
     border-color: transparent;
     .#{$prefix}--btn__icon path {
       fill: $disabled;
     }
   }
   &.#{$prefix}--btn--sm {
     padding: $button-padding-ghost-sm;
   }
 }

**Comment by tw15egan** [comment]
Can you try updating to `10.4.1`? Looks like this issue was fixed with this PR https://github.com/carbon-design-system/carbon/pull/3396

**Comment by aradhikaIbm** [comment]
Yes moving to 10.4.1 resolved it

**Comment by tw15egan** [comment]
👍

**Comment by Samstar10** [comment]
How can I change the ghost button color to black from blue?
