### ISSUE TITLE
[DatePicker] React calendar control not keyboard accessible

### ISSUE THREAD

**Issue by ryshah** [carbon-design-system/carbon#3638]
When calendar control (React version) is focused, it is not able to navigate to specific dates using Keyboard keys. Issue can be recreated at http://react.carbondesignsystem.com/?path=/story/datepicker--single-with-calendar after pressing down arrow key to focus the calendar.

The Carbon calendar control (non-react) works as expected. https://www.carbondesignsystem.com/components/date-picker/code

## Environment

> Operating system
Mac OS

> Browser
Chrome
Mozilla

**Comment by asudoh** [comment]
Saw the same problem with Flatpickr itself, and found: flatpickr/flatpickr#1329
