### ISSUE TITLE
[Tile] Not collapsing the expandable tile on link click or text select

### ISSUE THREAD

**Issue by keithkade** [carbon-design-system/carbon#3642]
### Summary

If the expandable tile's below the fold content contains links or text, then if the user clicks a link / selects some text, then the tile should not collapse. 

### Justification

Users are annoyed when they try to copy/paste from below the fold content and the tile collapses. Similarly for clicking links. In those cases, they probably didn't want the tile to collapse. 

### Desired UX and success metrics

Clicking a link or selecting text does not collapse the expandable tile. 

### "Must have" functionality

Clicking a link or selecting text does not collapse the expandable tile. 

We'd be happy with this being either default behavior or something that is toggled by a property. 

### Specific timeline issues / requests

No specific timeline. in particular we would like to use this enhancement on the IBM Cloud deploy toolchain page: https://cloud.ibm.com/devops/setup/deploy?repository=https%3A%2F%2Fgithub.com%2Fopen-toolchain%2Fsecure-kube-toolchain&env_id=ibm:yp:us-east

### Available extra resources

If we agree to add this enhancement, I can make the PR.

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if the enhancement proposal makes sense to them. Thanks!

**Comment by shixiedesign** [comment]
If described behavior can be reproduced, we should definitely address it. We can look at this component in more detail during the enhancement cycles.

**Comment by keithkade** [comment]
Here's an example. I'm just trying to copy that text, but when I release the mouse it counts as a click so the tile collapses. 

![Aug-05-2019 13-38-28](https://user-images.githubusercontent.com/2426829/62487069-7cdefd00-b786-11e9-9ea2-fba74330f1b0.gif)

**Comment by keithkade** [comment]
Still valid

**Comment by tw15egan** [comment]
UX questions - How would a user close an expandable tile in this scenario:

Would any click in the Above the Fold section close? 
Could a user click the chevron at the bottom of the Tile to close?

**Comment by keithkade** [comment]
IMO behavior would stay the same any click on the tile would close unless 1) it was part of text selection 2) it was clicking a link

**Comment by tw15egan** [comment]
Do you have ideas on how we could achieve this (specifically part 1)? Any PR would be appreciated 👍

**Comment by keithkade** [comment]
I was thinking something along the lines of this adjustment to the click handler
```
  handleClick = evt => {
    // ignore clicks that were part of text selection
    if (window.getSelection && window.getSelection().toString().length) {
      // maybe call this.props.handleClick(evt)? not sure if we still would in this case
      return;
    }
    evt.persist();
    this.setState(
      {
        expanded: !this.state.expanded,
      },
      () => {
        this.setMaxHeight();
        this.props.handleClick(evt);
      }
    );
  };
```

I'll start writing up a full PR

**Comment by keithkade** [comment]
@tw15egan opened up a PR https://github.com/carbon-design-system/carbon/pull/4059
