### ISSUE TITLE
Issue building V9 Select component scss. Breaks page style.

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon#3651]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

This line is causing style build failure.
https://github.com/carbon-design-system/carbon/blob/v9/src/components/select/_select.scss#L101

![Screen Shot 2019-08-05 at 2 50 46 PM](https://user-images.githubusercontent.com/17915105/62492735-05fd3080-b795-11e9-89fb-d19fbe720c5e.png)

> Is this issue related to a specific component?

Select component, this also breaks other Pagination who imports this style

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Style compiles

> What browser are you working in?
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
v9.91.5

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Should be closed by: https://github.com/carbon-design-system/carbon/pull/3654 let us know if this isn't the case!
