### ISSUE TITLE
The prop `small` for Button has been deprecated in favor of `size`. Please use `size="small"` instead.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3656]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

After upgrading to latest version of carbon-react, I have this warning for buttons even if I don't set up the size attribute!

> The prop `small` for Button has been deprecated in favor of `size`. Please use `size="small"` instead.

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No warning!

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?
7.2.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

It happened after upgrading to latest version:
![image](https://user-images.githubusercontent.com/26740851/62515851-288e5880-b82c-11e9-96e7-f640b3b2e1c6.png)

Sandbox:
https://codesandbox.io/s/reverent-firefly-pyc03

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Strange, I can't get it to reproduce locally but I'm seeing the issue on your CodeSandbox... taking a deeper look

**Comment by tay1orjones** [comment]
I'm also running into this issue while working to update from `10.3.1` to `10.4.1`. It doesn't appear consistently for all buttons. I haven't yet been able to isolate why only some of the buttons in our addons lib see this warning. 

Edit: 
The deprecation helper was added to Button in 10.4, but [10.4.1 does not contain](https://github.com/carbon-design-system/carbon/blob/v10.4.1/packages/react/src/components/Button/Button.js#L208) the [removal of the default prop for `small`](https://github.com/carbon-design-system/carbon/pull/3415), which should resolve this.

**Comment by asudoh** [comment]
OK sounds that it'll be fixed in the next release, but please don't hesitate to speak up otherwise!

**Comment by zbeedatm** [comment]
That's OK. Not critical. Thanks

**Comment by joshblack** [comment]
Going to close this out as I believe it's been addressed, leave a comment if not and I can re-open!

**Comment by Saad-Malik** [comment]
Is this issue fixed? I can still see the same warning in datatable.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) for easier testing and debugging?
