### ISSUE TITLE
Carbon Component-Angular - Table

### ISSUE THREAD

**Issue by prateek04** [carbon-design-system/carbon#3657]
Hi Team,
Need Help- Angular - Table
I am facing one issue in Table Component on using Carbon Components where on click of checkbox I am not able to fetch the row data neither the index of the row. Please find the attached screenshot having the UI of the table component.
Basically, there is no handler on the checkbox.
Also, below is the code for calling the table component.
<table [model]="model" (sort)="customSort($event)" [showSelectionColumn]="true"></table> (edited) 

On click of a checkbox, I want to call a handler so that I can have the row data of the selected checkbox

**Comment by asudoh** [comment]
Hi 👋 would you want to report this at https://github.com/IBM/carbon-components-angular/issues?
