### ISSUE TITLE
OverlowMenu,  OverflowMenuItem itemText full text not shown for long text 

### ISSUE THREAD

**Issue by geechia** [carbon-design-system/carbon#3660]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
OverflowMenuItem with A long text ,  'itemText='a very long name app usage' 
click on the menu item,  see "'a very long name app...",  shows truncated text with ellipse as expected.  When hovering on the menu item,  expects to see  full text, "a very long name app usage".

> Is this issue related to a specific component?
<OverflowMenuItem>
> What did you expect to happen? What happened instead? What would you like to
> see changed?
Allow user to see full text , "a very long name app usage"  when hovering on the menu (via title attribute)
> What browser are you working in?
Firefox
> What version of the Carbon Design System are you using?
 "carbon-components": "10.4.1",
  "carbon-components-react": "7.4.1",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
August 30

## Steps to reproduce the issue
See sandbox link below.  

1. Click on the overflow menu
2. Menu item,  A very long name ... is displayed
3. Hover on the menu item,  full text was not displayed

> Please create a reduced test case in CodeSandbox
> 
https://codesandbox.io/s/codesandbox-nkrtn

> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! `itemText` prop of `<OverflowMenuItem>` can take React node, where you can put `<div className="bx--overflow-menu-options__option-content" title="your long text">your long text</div>`.

**Comment by geechia** [comment]
Thank you! the suggestion works!

**Comment by tw15egan** [comment]
Going to close this as it seems the issue was resolved! 👍

**Comment by geechia** [comment]
I think the <OverflowMenuItem> can be improved to support title, this should help ease of use of the component. Thanks!
