### ISSUE TITLE
OverflowMenu not working inside Modal (v10)

### ISSUE THREAD

**Issue by sally-c-milson** [carbon-design-system/carbon#3665]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Trying to upgrade to v10. We are using `OverflowMenu` inside `Modal` as seen in the screenshot below. (Open in top left corner of picture). The click event is being blocked by something. I compared `OverflowMenuComponent` inside and outside the modal. Looking at the event listeners it seems like the event is being blocked by something called `focusTrap`.

> Is this issue related to a specific component?
Interaction between `OverflowMenuItem` and `Modal`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect the click event to get to the handler. It does not.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^10.0.0",
"carbon-components-react": "^7.0.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
I work on Voice Agent, and we planned on finishing the upgrade to v10 for our August release.

## Steps to reproduce the issue

1. Step one
Create a `Modal` with an `OverflowMenu` inside it.
2. Step two
Have an `OverflowMenuItem` item with an `onClick` handler.
3. Step three
Click on the menu item to see it doesn't work.

## Additional information

- Screenshots or code
![model-overflow](https://user-images.githubusercontent.com/32376909/62577730-8a22e700-b86d-11e9-8213-53266dd88586.PNG)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Would you create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by sally-c-milson** [comment]
@asudoh Here it is: https://codesandbox.io/s/codesandbox-c46yh

**Comment by asudoh** [comment]
Thanks - Would you try adding `focusTrap={false}` to `<Modal>`? Your CodeSandbox seems to be working this way.

**Comment by sally-c-milson** [comment]
Thanks! I wasn't aware of that property.

Could there be any negative effects of just turning off focusTrap? (as opposed to moving the open menu to be inside the focusTrap.) I tried tabing out of the modal and everything seemed to be fine, but I was wondering if there were any other possible effects I should be aware of.

**Comment by asudoh** [comment]
The only difference I'm aware of is `focusTrap={true}` supports reverse-focus-wrap (the behavior with shift-tab).

**Comment by abbeyhrt** [comment]
I'm going to close this since it seems like the issue was addressed, feel free to comment if you feel like it hasn’t been addressed yet!
