### ISSUE TITLE
Missing property and style for active HeaderMenuItem in HeaderNavigation

### ISSUE THREAD

**Issue by nxn-4-wdf** [carbon-design-system/carbon#3674]
## What package(s) are you using?
- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description
In the UI Shell, the currently active SideNavLink element (using properties `element={Link}` and `isActive={true}`) automatically gets a blue border on the left.

For an active HeaderMenuItem, the Carbon page https://www.carbondesignsystem.com/components/UI-shell-header/styledocumentation recommends the following: 
![image](https://user-images.githubusercontent.com/52698706/62628375-763dba80-b92b-11e9-8ec0-06563bfa0ce2.png)

Unfortunately, property `isActive` (or `active`) does not work with HeaderMenuItem, I need to programmatically set it with code like `aria-current={ checkActive() ? "page" : "" }`.

Then, a blue border as in picture above is missing. I tried with a simple override:
```
.bx--header__nav a.bx--header__menu-item[aria-current='page'] {
  background-color: $active-secondary;
  border-bottom-color: $focus;
  border-bottom-width: $spacing-02;
  color: $text-04;
  @include carbon--font-weight('semibold');
}
```

Result is:
![image](https://user-images.githubusercontent.com/52698706/62629173-f87aae80-b92c-11e9-9705-47a577a5db06.png)

Zooming in, we see that much more is required than the few lines above:
![image](https://user-images.githubusercontent.com/52698706/62629566-abe3a300-b92d-11e9-9ecf-050f4576bb31.png)

Especially, the blue border is a trapez, not a rectangle, and the text is a few pixels above the base line.

Expected are:
1. HeaderMenuItem should corrrecty accept property `isActive` with `element={Link}` or `element={NavLink}`.
2. Property `aria-current="page"` should be generated accordingly.
3. Style for active HeaderMenuItem shall include a blue bottom border.

## Steps to reproduce the issue
UI Shell with header navigation. 

## Additional information
See screenshots above.

**Comment by nxn-4-wdf** [comment]
Code reproducing the problem on : https://codesandbox.io/s/headernav-x4wyk

Result : https://x4wyk.csb.app/#/

**Comment by eknowles** [comment]
I also have the same problem, thank you for starting this issue.

the links you have is out of date.

this is the problem file.
https://github.com/carbon-design-system/carbon/blob/33584bd83b6e80835c350846fdadf4fe2d2671e7/packages/react/src/components/UIShell/HeaderMenuItem.js

this is the documentation
https://www.carbondesignsystem.com/components/UI-shell-header/style#menu-item
