### ISSUE TITLE
Icons with text in ContentSwitcher

### ISSUE THREAD

**Issue by rax-it** [carbon-design-system/carbon#3676]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

<img width="358" alt="Screen Shot 2019-08-07 at 11 21 14 AM" src="https://user-images.githubusercontent.com/14324480/62635636-0a952680-b906-11e9-8893-8f85f385384e.png">

I have a requirement about something like this, where we have icons and text both Inside the Switch. The current implementation is using V9 which supports rendering of icons using `icon` prop. But I didn't find a way to that in V10, I have implemented this using custom CSS on our side. But it would be convenient if this functionality is provided natively in Carbon React components.
 
### Justification

Business reason is same as above pic. Sometimes, a combination of text and icon is more intuitive to use.

### Desired UX and success metrics

The example I used is already available in V9 so not sure why it was removed in V10.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
@carbon-design-system/design I'm under an impression that we deliberately removed "icon in content switcher button" capability, but please speak up if I'm wrong here... Thanks!

**Comment by tw15egan** [comment]
According to the usage guidelines:

> Icons are not permitted in tab labels.

https://www.carbondesignsystem.com/components/tabs/usage#text

**Comment by asudoh** [comment]
Thanks @tw15egan! Let's close this based on our guideline. Please feel free to re-open if anybody thinks the guideline should be changed!
