### ISSUE TITLE
Date Picker - Browser autocomplete behavior isn't disabled

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon#3680]
### Describe in detail the issue you're having.
When the datepicker popup shows, you would still see the default browser autocomplete boxes showing up.

### Is this issue related to a specific component?
Datepicker

### What would you like to see changed?
Adding `autocomplete="off"` to the `<input />` should solve the issue by hiding the default autocomplete behavior.

### What browser are you working in?
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

## Additional information
![image](https://user-images.githubusercontent.com/14989804/62641247-3a95f700-b911-11e9-9bd1-813e370365b0.png)

![image](https://user-images.githubusercontent.com/14989804/62641234-323dbc00-b911-11e9-8c94-3fa008f1d939.png)

**Comment by tw15egan** [comment]
I don't think we disable this by default on any of our text inputs. You should just be able to pass `autocomplete="off"` to the component inside your own application. I'd prefer to leave this configurable rather than disabling it for all users.

**Comment by theiliad** [comment]
I can see that work only if we shifted the top part of the picker to be fully visible when the autocomplete box shows up.

Also, it could be `off` by default and still be configurable

**Comment by tw15egan** [comment]
I don't see the autocomplete box pop up as it is, do you have steps to replicate the behavior? I'm also using Chrome latest... Can't get it to show up even if I directly enable it. 

I think it makes more sense to retain parity with other inputs and just let the user pass down `autocomplete="off"` if it is unwanted.

**Comment by theiliad** [comment]
I don't do anything specific to enable it. Just running on:
`Chrome Version 75.0.3770.142 (Official Build) (64-bit)`

**Comment by tw15egan** [comment]
>makes more sense to retain parity with other inputs and just let the user pass down autocomplete="off" if it is unwanted.
