### ISSUE TITLE
Syntax errors in carbon-components.css

### ISSUE THREAD

**Issue by nxn-4-wdf** [carbon-design-system/carbon#3688]
## What package(s) are you using?

- [x] `carbon-components`

Version in `package.json`: `"carbon-components": "^10.4.1",`

## Detailed description

There are syntax errors for a few statements in `carbon-components/css/carbon-components.css`, which are displayed in the Mozilla Firefox console logs (Developer Tools -> Console)

1. Line 182, it is contra**s**t, not contra**c**t: `@media screen and (-ms-high-contract: active) {`

2. Line 3279, `Found invalid value for media feature`: `@media (min-width: breakpoint("sm")) {`

3. `Ruleset ignored due to bad selector`:
  - line 7184: `.bx--data-table th:first-of-type:not(.bx--table-expand th) {`
  - line 14264: `.bx--tag.bx--skeleton:after:hover, .bx--tag.bx--skeleton:after:focus, .bx--tag.bx--skeleton:after:active {`
  - line 14220: `.bx--tag.bx--skeleton:after:before {`

4. Line 13866, `Error in parsing value for ‘max-height’.  Declaration dropped.`. It seems value `max-height: auto;` is not allowed.

**Comment by tw15egan** [comment]
Some of these are pretty strange... 

Doing a search in the repo I can't find `contract`, but it seems like it's this line that is being compiled to `contract` for some reason?

https://github.com/carbon-design-system/carbon/blob/3850475d8826d7126694c6176699fd00c45f5e82/packages/components/src/globals/scss/vendor/@carbon/elements/scss/icons/mixins.scss#L13


Taking a look at the rest 👍
