### ISSUE TITLE
import all icons from @carbon/icons-react

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#3692]
When I use icons under node_modules/carbon-icons, I can use following code to 'import' all icons and access them dynamically: 

import  * as carbonIcons from 'carbon-icons';

var iconName = "iconChevronDown";
carbonIcons[iconName],

The icons under node_modules/@carbon/icons-react/es spread in different files, is there a way to do the similar thing as above - importing all icons and accessing them dynamically?

**Comment by asudoh** [comment]
Hi 👋 would #3078 address your need?

**Comment by zhenwan** [comment]
#3078  does not provide an example to show how to do it. 
BTW, it seems @carbon/icons-react is not ready for testing now. I try it by following the readme at https://github.com/carbon-design-system/carbon/tree/master/packages/icons-react
, and got an error from code below:

import { Add24 } from '@carbon/icons-react';



ERROR in ./src/js/renderers/React/IconFactory.js
Module not found: Error: Can't resolve '@carbon/icons-react' in '/Users/ibmadmin/Documents/temp/HA-AC/Projects/project_programs/CarbonCopy/src/

**Comment by asudoh** [comment]
`carbon-components-react` code has been using `@carbon/icons-react` for quite some time. That said, would you just try doing similar thing to [`carbon-components-react` code](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/react/src/components/Dropdown/Dropdown.js#L13)? Though the `main` entry point thing is a valid point, it does not make the library completely unusable.

**Comment by denizkenan** [comment]
this is still the case:
it fails during build:
> Failed to compile.
> ./node_modules/carbon-components-react/es/components/Icon/Icon.js
> Module not found: Can't resolve 'carbon-icons' in '~/app/node_modules/carbon-components-react/es/components/Icon'

**Comment by wannymiarelli** [comment]
> `carbon-components-react` code has been using `@carbon/icons-react` for quite some time. That said, would you just try doing similar thing to [`carbon-components-react` code](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/react/src/components/Dropdown/Dropdown.js#L13)? Though the `main` entry point thing is a valid point, it does not make the library completely unusable.

This works, but I think that this should be stated in the docs.

**Comment by nappalm** [comment]
Work for me in react

```
import * as Carbon from '@carbon/icons-react';
const Icon = (props) => {
 const iconName = props;
 const Base = Carbon[iconName]

 return <Base />
} 

export default Icon;
```
