### ISSUE TITLE
Resources: Design resources: Add Plex and IDL cards.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#3694]
@jeanservaas 

Seems odd to have these as test links surrounded by other resource cards.

<img width="431" alt="Screen Shot 2019-08-09 at 2 17 52 AM" src="https://user-images.githubusercontent.com/32881239/62736826-f5c2ab00-ba4b-11e9-9de8-f9081a14da01.png">

**Comment by jeanservaas** [comment]
Can you add more context here, I'm not sure what you mean.

**Comment by mjabbink** [comment]
I had more context but information deleted.

I think this was for Typography page. To use same card and copy as in IDL and this link
https://github.com/IBM/plex/releases/latest. The current is 404.

In old IDL we customized all the resource cards to have better breaks

**Comment by mjabbink** [comment]
Should not be stale. Link to Plex Git is 404.

**Comment by mjabbink** [comment]
the old IDL site had breaks to help the text read and sit better in the card. That was lost in migration and now there is no reference. We’ll have to get specific and describe where the breaks should happen across the cards.
