### ISSUE TITLE
NumberInput: Can add leading zeros before the number.

### ISSUE THREAD

**Issue by q1401030115** [carbon-design-system/carbon#3697]
For the component **NumberInput**,  user can enter values with several leading zeros, which is not correct.

![image](https://user-images.githubusercontent.com/27209340/62764122-b635a680-babf-11e9-99e1-f3ce9c2d4192.png)

**Comment by tw15egan** [comment]
Is this causing a problem when reading the value? As soon as you increase/decrease the value, it gets reset anyways

**Comment by q1401030115** [comment]
@tw15egan No, it doesn't have effect on reading value, and it will get normal when  increase/decrease the value,  but it does make the UI look not so well, and  we hope that user can't add the leading zeros.

**Comment by laurenmrice** [comment]
not stale
