### ISSUE TITLE
Elements masked by header when getting to them with internal anchors

### ISSUE THREAD

**Issue by nxn-4-wdf** [carbon-design-system/carbon#3700]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

App uses the Carbon UI-Shell with header navigation and react-router-dom Link components, which lead to different pages sorted by a HashRouter. In order to enable navigation to internal page anchors, app uses HashLink components from react-router-hash-link.

## Detailed description

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When clicking onto a link to an internal page anchor, the browser scrolls to the corresponding target element. Unless it is at the very bottom of the page, this target then displays on the top of the viewport. But then, it is masked by the UI-Shell Header.

One would expect the browser to scroll the target element, so that it is displayed just below the header.

> Is this issue related to a specific component?

No.

> What browser are you working in?

Firefox and Chrome on Windows 10 both display the problem

> What version of the Carbon Design System are you using?
10.4

## Steps to reproduce the issue

See example app on CodeSandBox: https://37eph.csb.app/#/

1. Reduce the browser window height, for example to less than 600px. Example screenshot:
![image](https://user-images.githubusercontent.com/52698706/62768711-c2a60900-ba97-11e9-9dd3-f7bd2c0743d1.png)

2. Click on button "Scroll to middle of page". Result:
![image](https://user-images.githubusercontent.com/52698706/62768787-eec18a00-ba97-11e9-9657-442b4c93819b.png)

The target element is hidden by the navigation bar. You need to manually scroll again (vertical browser scrollbar, mouse roll button, ...) to see the target element. Expected result:
![image](https://user-images.githubusercontent.com/52698706/62769277-e61d8380-ba98-11e9-86b4-9f6670690d49.png)

> Please create a reduced test case in CodeSandbox

Code is on: https://codesandbox.io/s/skiptocontent-37eph

## Additional information

Note: the problem looks difficult to fix, it is probably a mix of CSS and Javascript:
1. Adapt CSS `margin` and `padding` values for Content and Header components?
2. Discover links to local anchors. With HashRouter and HashLink, these links all seem to have `href="#/#anchor-id"`, therefore a `document.querySelectorAll("a[href^='#/#']")` would find them. I did not check other React Routers, maybe other are relevant ?
3. Adding a click event listener could work? Something like :
```js
function scrollTo( targetElement ) {
  var headerHeightOffset = document.querySelector( ".bx--header" ).offsetHeight + 4;
  targetElement.scrollIntoView();
  var toTop = targetElement.getBoundingClientRect().top;
  if (toTop < headerHeightOffset) {
    window.scrollBy( 0, toTop - headerHeightOffset );
  }
}
```
(you probably need to disable default link behaviour too)

**Comment by tw15egan** [comment]
Hmm, this seems like it will need to be fixed in user-land on a link click. Since it is `position: fixed`, you'll need something that navigates to the position of the anchor plus the height of the header. 

If you have any solutions you think we could add to the header, we are always open to PR's. Thanks!
