### ISSUE TITLE
Search does not sit well next to other inputs

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#3701]
The default search component is 48 px tall while the default dropdown is 40px

Only a `small` variant of the search input exists (32px). We should at the very least offer a field sized variant. Ideally our inputs would align on height by default.

![Screen Shot 2019-08-09 at 10 41 11 AM](https://user-images.githubusercontent.com/4078018/62791270-6c829700-ba92-11e9-9282-2c661b56e804.png)

**Comment by tw15egan** [comment]
Going to close as this seems like a dup of https://github.com/carbon-design-system/carbon/issues/3457
