### ISSUE TITLE
[Date picker] Change input filed to fluid width

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3712]
Currently, date picker is fixed with to always match the width of the calendar dropdown. This is not scalable, and we'd like to change it to fluid width so it fills 100% of parent container, **behaving like text inputs** .

_Current_ 

![image](https://user-images.githubusercontent.com/15144993/62883302-5de9e900-bcf9-11e9-9313-b33c9b819468.png)

_Should be_

![image](https://user-images.githubusercontent.com/15144993/62884277-bcb06200-bcfb-11e9-894c-26cab0351cc5.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design is this still valid? Not sure how we would have it be a fluid width, but have the default be exactly `288px`

**Comment by aagonzales** [comment]
I think by default it should stay the width of the calendar but then it should have the option to be other widths (if that's possible).

Updated:
Oh that's literally what the first comment says, so yes I think this is still valid.

**Comment by aagonzales** [comment]
I also think this scenario is a little weird but maybe it depends on the context.

![image](https://user-images.githubusercontent.com/11670886/74677332-9d4c3300-517d-11ea-8dc7-1c43137c8e6c.png)

**Comment by laurenmrice** [comment]
yeah, sometimes you would need to expand it to align with other fields in a form or something so  this would make sense

**Comment by tw15egan** [comment]
> I think by default it should stay the width of the calendar but then it should have the option to be other widths (if that's possible).

@aagonzales  We could remove the max-width, but teams will have to manually override it to be 100% (will default to a `width: 288px`). Not really a way to get it to default to exactly the dropdown width, but then expand if there is more space unless they override.

**Comment by aagonzales** [comment]
Ok let's just set a min-width and no max width then people can just adjust it to whatever size they need. And if we can't have it displayed at `width:288px` by default then lets default it to the min `width: 144px`. 

![image](https://user-images.githubusercontent.com/11670886/74755011-1ad47980-5238-11ea-8bb5-4e84d52b8738.png)

**Comment by tw15egan** [comment]
We can do `min-width: 144px` and `width: 288px` by default, and then all a user would need to do is change `width: 100%`  👍
