### ISSUE TITLE
FileUploader invalid option

### ISSUE THREAD

**Issue by eglepuo** [carbon-design-system/carbon#3719]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

FileUploader component have invalid option ( like error with red borders and text ) shown in documentation, but when I open react documentation there is no that kind of option and I have to make invalid option with my css, I think if you have that kind of option shown in documentation, there should be possibility to use it :) . I am using the newest one carbon-components-react version (7.4.1)

## Additional information

![image](https://user-images.githubusercontent.com/36009566/62923193-e0d07980-bdb5-11e9-9e13-91b3f81cbbc9.png)

**Comment by emyarod** [comment]
you can refer to the documentation for `FileUploaderItem` for the invalid upload CSS class

https://carbon-components-react.netlify.com/?path=/story/fileuploader--fileuploaderitem
