### ISSUE TITLE
Javascript conflict between Carbon Datatable component and Angular's module "AuthGuard"  

### ISSUE THREAD

**Issue by dessty** [carbon-design-system/carbon#372]
## Detailed description
Bug: Data table does not expand information when I hit the arrow icon of a row of the table.
I use data table carbon component in my angular application. The expand row feature used to work fine. But since I added Angular routing mechanism to my application using AuthGuard module, any javascript related action from the datatable or other carbon components fails to work.
The console does not display any error message. 
I'm thinking about maybe a conflict between the 2 libraries (carbon-component vs AuthGuard && CanActivate@angular/router)

> Is this issue related to a specific component? 
datatable, interiorLeftNav, but potentially any interactive carbon components (I just haven't tried any other yet)

> What did you expect to happen? What happened instead? What would you like to see changed?
The row should expand and display the collapsed information. Instead, nothing happens when I click on the arrow.

> What browser are you working in? 
Version 61.0.3163.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using? 
7.22.1

## Steps to reproduce the issue

1. Run an empty shell angular 4 app
2. Implement AuthGuard routing system
3. Load a left-navigation or datatable component into the app

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for taking the time to report this issue. If you could help us out by creating a sample repo with the issue, or a live playground through codesandbox, codepen, jsbin, etc we can help with debugging the issue here!

**Comment by marijohannessen** [comment]
Closing this issue due to lack of response from issue creator. Please feel free to re-open if needed.

**Comment by dessty** [comment]
Re created an issue with sample project that reproduces the bug #441

**Comment by joshblack** [comment]
Sounds good, thanks @dessty!
