### ISSUE TITLE
Tooltip onHover

### ISSUE THREAD

**Issue by eglepuo** [carbon-design-system/carbon#3720]
### Summary

Tooltip works only onClick, it doesn't work on hover and for having tooltip on hover I have to use TooltipDefinition component. But if I want to open tooltip on the same information icon  then I get warning that TooltipDefinition should be used only with strings. I think Tooltip component should have option to work on hover or on click.

### Justification

Most of the people use tooltips on hover and not all the tooltips goes on the text, sometimes they go on icons too.

### "Must have" functionality

Tooltip open option -> onClick or onHover

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Actually it was out conscious decision, where our design dictates that interactive tooltip with richer (especially interactive) contents should be opened by interaction, and definition tooltip shouldn't have a richer content. Some discussion is going on (where it was completely slipped my mind) wrt something like bold text can be in definition tooltip. CC @carbon-design-system/design

**Comment by elizabethsjudd** [comment]
There is a whole conversation about the contents of the different types of tooltips starting here that explains why rich text is **not** allowed within definition tooltips: https://github.com/carbon-design-system/carbon/pull/3476#issuecomment-518670586
