### ISSUE TITLE
FileUploader button options

### ISSUE THREAD

**Issue by eglepuo** [carbon-design-system/carbon#3721]
### Summary

1. FileUploader ( not FileUploaderButton, because they look different ) don't have option to change button size ( it is small by default and I can make it bigger only with my own css)
2. FileUploader ( again not FileUploaderButton ) don't have possibility to be disabled, so I have again to change all the style manually.
3. I don't really understand why FileUploader have the same onClick event on file finder open and on file remove ( of course it is possible to use it like this, but it is not really convenient, probably would be better to have another method called on file removing)

### Justification

FileUploader have option to change buttonKind, so I think we should have possibility to disable or change size too, because it would be logical.

### "Must have" functionality

1. Possibility to change button size on FileUploader component
2. Possibility to make button disabled on FileUploader component

**Comment by asudoh** [comment]
@emyarod Do you have the latest with the React variant...? Thanks!

**Comment by ross-rosario** [comment]
Not sure why this issue is being marked stale.

The question is simple here. Can FileUploader component support `disabled` property? Thanks

**Comment by emyarod** [comment]
it looks like these are not properly supported in the legacy file uploader but they are in the drag and drop variant

**Comment by eglepuo** [comment]
So could you fix that? :)

**Comment by ross-rosario** [comment]
This UI system is useless.
