### ISSUE TITLE
[Condensed grid] Math doesn't add up

### ISSUE THREAD

**Issue by kosruben** [carbon-design-system/carbon#3722]
## Detailed description

When using the condensed grid to layout tiles across the page, there seems to be an inconsistency with the use of a gutter. According to the documentation, the columns should get a `1px` gutter on both sides, resulting in a visual `2px` divider between the tiles.

However, if this is true, the outer margin of `16px` on both sides of the canvas would increase to `17px`, resulting in inconsistency with other components on a page that might use background colour / image.

I am aware this is nitpicking, but I do prefer my designs to be as perfect as possible. If this is the recommended route, I am of course happy to use it as is.

## Steps to reproduce the issue

1. Visit the documentation for the condensed grid [here](https://carbon-elements.netlify.com/grid/examples/preview/#condensed-grid).

## Additional information

An example created in Sketch with the use of the `XLG - 1312px - 16 columns` template results in the following:

![xlg-1312px-16 column](https://user-images.githubusercontent.com/47223306/62928237-11151980-bdb0-11e9-93f5-91006287f13d.png)

**Comment by joshblack** [comment]
cc @jeanservaas does this match you expect on the design side?

> I am aware this is nitpicking, but I do prefer my designs to be as perfect as possible

Totally fair! And we do too 😄

**Comment by joshblack** [comment]
Hey there! :wave: Closing this out due to inactivity, feel free to comment and I can re-open!
