### ISSUE TITLE
Overriding font in number input

### ISSUE THREAD

**Issue by bleush38p** [carbon-design-system/carbon#3725]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Hi, I'm on a team where we're using the carbon components package along with a custom theme. In particular we are changing the typeface used. We are able to successfully override the typeface in every carbon component except for the number input.

I wanted to ask if there is a recommended solution to achieve this customization so that we do not need to edit the component source or whether it is possible to change the values returned by the `carbon--font-family()` function.

## Relevant information

We are setting all of the typography tokens in carbon prior to importing the carbon styles, for example:

```scss
$body-short-01: (
  font-family: $custom-font-stack,
  font-size: carbon--rem(14px),
  font-weight: 400,
  line-height: carbon--rem(20px),
  letter-spacing: 0.15px,
);
```

However the number input font does not seem to use any of these text styles; it is set in two places:

[_number-input.scss:29](https://github.com/carbon-design-system/carbon/blob/c4b003b4764efa3e36d537f25a14129af9f8971f/packages/components/src/components/number-input/_number-input.scss#L29)

[_form.scss:57](https://github.com/carbon-design-system/carbon/blob/c4b003b4764efa3e36d537f25a14129af9f8971f/packages/components/src/components/form/_form.scss#L57)

As far as I can tell these are the only places in any components where font-family is specified, everywhere else it is pulled from the tokens we can set.

Our default sans-serif font has tabular figures, so we don't want to use a different font for the number input.

Thank you!

**Comment by asudoh** [comment]
Hi 👋 the style you referred to is to use the monospace font for number. You can do CSS override to change the font.
