### ISSUE TITLE
React Data Table incorrect json rendering

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon#3728]
## Issue description
We are using carbon components in react, we have component which imports all necessary table components from carbon-components-react. All is working fine with json file, but if we are using json file, where object element is **Id** not as default **id**, table is rendering all rows with last object data. Is there any hack to resolve this?

## What package(s) are you using?
- [ ^16.8.6] `react`
- [^10.3.2 ] `carbon-components`
- [^7.3.2 ] `carbon-components-react`

## Detailed description
Working json (when table renders 2 rows with specific values): 
`[`
`    { `
`        "id": 1,`
`        "name":"Peter"`
`    },`
`    { `
`        "id": 2,`
`        "name":"Robert"`
`    },`
`]`

Bad json (when table renders 2 rows with same values from the last object in each row):
`[`
`    { `
`        "Id": 1,`
`        "name":"Peter"`
`    },`
`    { `
`        "Id": 2,`
`        "name":"Robert"`
`    },`
`]`

In component table row code:
` <TableBody>` 
                   `  {rows.map(row => (` 
                       `  <TableRow key={row.id}>` 
                       `  {row.cells.map(cell => (` 
                            ` <TableCell key={cell.id}>{cell.value}</TableCell>` 
                       `  ))}` 
                        ` </TableRow>` 
                   `  ))}` 
                   `  </TableBody>` 

Is there any solution to get work with bad json file, or the only way is to set Id to id? 
Regards, Reinis

**Comment by asudoh** [comment]
Hi 👋 sounds that you need to transform the data before passing it along to data table?

**Comment by reinisg** [comment]
> 
> 
> Hi 👋 sounds that you need to transform the data before passing it along to data table?

Okay, thanks for answer. 
I will try to transform to id.
