### ISSUE TITLE
$overlay-01 color is not right in the dark themes

### ISSUE THREAD

**Issue by johnjesse** [carbon-design-system/carbon#3738]
> Describe in detail the issue you're having.

When in a dark theme the overlay used for modal dialog backgrounds doesn't provide sufficient contrast.

We're using carbon colour tokens for our theming and have matched our usages off those tokens to the carbon-design system.

In the white theme with a modal dialog open, we have something that looks like this 

![image](https://user-images.githubusercontent.com/6839660/63097676-ff2aa680-bf68-11e9-9f0a-369aec79b314.png)

But in the dark or gray90 or the gray100 themes it looks more like this

![image](https://user-images.githubusercontent.com/6839660/63097742-208b9280-bf69-11e9-9a91-fc5b5ea59235.png)

The `$overlay-01` token has not changed it's value between themes - at least according to the documentation here

https://www.carbondesignsystem.com/guidelines/color/usage

Either the documentation is wrong, or the token needs a different value in the dark themes as the current value does not provide reasonable contrast with ui-background ui-01 and ui-02, and doesn't fade out text very much

**Comment by johnjesse** [comment]
Having a bit of a play around with it, I think it's the opacity of the overlay color that really needs to change to be more opaque in the darker themes, it doesn't do much to fade out the background or text that might be there.

**Comment by asudoh** [comment]
@carbon-design-system/design Any thoughts...? Thanks!

**Comment by aagonzales** [comment]
Hi, can you confirm what tokens/values you're using. Below is what the official color combinations are for modal and overlay in the Gray 90 and Gray 100 themes. They look a little different than what I'm seeing in the screen shot above. The modal background should be using `$ui-01`
https://www.carbondesignsystem.com/components/modal/style

![image](https://user-images.githubusercontent.com/11670886/63182335-fc3abf00-c017-11e9-8ccc-e92a8ecf01a5.png)

**Comment by johnjesse** [comment]
@aagonzales 

You were right the colour of our modal was slightly wrong, I've corrected it - so its ui-01 (#282828 in the carbon-gray-100 theme), in our UI but there still seems to be an issue

e.g.

Dark themed page
![image](https://user-images.githubusercontent.com/6839660/63276857-26041800-c29c-11e9-80b9-694817b70f29.png)

Dark themed page with modal
![image](https://user-images.githubusercontent.com/6839660/63276878-31efda00-c29c-11e9-9700-b7b936136fcc.png)

If you compare that to the same page with carbon-gray-10 you can see that the overlay makes much more of an impression
![image](https://user-images.githubusercontent.com/6839660/63276941-4df37b80-c29c-11e9-839f-a8510a6ff53a.png)

**Comment by aagonzales** [comment]
@johnjesse Can you check what the alpha for the overlay is. It looks like its too light still, I'm trying to figure out if its a bug with the value. It should at 70% for the Gray 90 and Gray 100 themes. 

This is what it should look like with text behind it. 
![image](https://user-images.githubusercontent.com/11670886/63380378-092f1980-c35c-11e9-975c-92c8a375e70e.png)

**Comment by johnjesse** [comment]
So, the rgba values that we are using for overlay are


gray90 and gray100 - `rgba(23,23,23,0.3)`
white and gray10 - `rgba(23,23,23,0.5)`

Reading what you've said, it might be that we've interpreted the 70% as 70% transparency rather than opacity... it looks much better if I set it to `rgba(23,23,23,0.7)`

**Comment by aagonzales** [comment]
ooo yup that's probably it. Mistranslation with alpha transparency vs. opacity.

**Comment by johnjesse** [comment]
Awesome, I'll update our translation of the tokens and close this, thanks for the help :)
