### ISSUE TITLE
Date Picker: calendar not being invoked

### ISSUE THREAD

**Issue by alejandrogomez314** [carbon-design-system/carbon#374]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

I am working with a NodeJS Watson Conversation Service app. On the conversation, I invoke the date picker on a specific instance. However, when I click on the date picker the calendar does not show up. I have the css and js files included. No error is shown. Have tried to initialize it like this (since the element is dynamically created) but no luck yet: 
`$("body").bind("DOMSubtreeModified", function() { $(this).find('.bx--form-item').selectorInit; });`

> Is this issue related to a specific component? 
Date Picker

> What did you expect to happen? What happened instead? What would you like to see changed?
I would like for it to display the calendar when I click on the the date picker.

> What browser are you working in? 
Chrome

> What version of the Carbon Design System are you using? 
7.22.2

## Steps to reproduce the issue
1. see [this conversation bot](https://conversation-simple.mybluemix.net) for an example of what my app looks like
2. After conversing with the app, a date picker is injected using javascript.
3. I click on the date picker but the calendar does not appear

## Additional information

* Screenshots or code

This is for a project and I need help ASAP :) thank you so so so much. Carbon is great and I use it for all my front end projects! 👍

**Comment by tw15egan** [comment]
Have you tried manually instantiating it like this? https://codepen.io/team/carbon/pen/BwjZZN

**Comment by alejandrogomez314** [comment]
Thank you! that worked like a charm.

**Comment by tw15egan** [comment]
Awesome, glad I could help 😄
