### ISSUE TITLE
File uploader component - Only allow single uploaded file

### ISSUE THREAD

**Issue by m-lukas** [carbon-design-system/carbon#3747]
## Summary

I have tried to implement the "File uploader" HTML component from the latest version of Carbon Design Components. The integration with the upload works quite well and I also added an extension check to the input-field. However, while the user can only select one file at a time, he can add multiple files in a row which show up in the file container.
That's why I wanted to ask if I can limit the number of uploaded files to 1, so that the user can only add and submit one single file?

## Relevant information

_Implementation:_
```html
<div class="bx--file" data-file>
    <label for="photoUpload" class="bx--file-btn bx--btn bx--btn--primary" role="button" tabindex="0">Take photo</label>
    <input type="file" accept="image/*" class="bx--file-input" id="photoUpload" data-file-uploader data-target="[data-file-container]" />
    <div data-file-container id="fileContainer" class="bx--file-container"></div>
</div>
```

_Import (using CDN):_
```html
<link rel="stylesheet" href="https://unpkg.com/carbon-components@10.2.0/css/carbon-components.css"/>
<script src="https://unpkg.com/carbon-components/scripts/carbon-components.min.js"></script>
```

**Comment by asudoh** [comment]
Hi 👋 given you seem to be using our vanilla code, one way I can think of is hooking `onchange` event of the `<input>` and remove the UI for the old file.

**Comment by m-lukas** [comment]
Thank you @asudoh!

I solved the issue now by calling this function in `onchange=` of the `<input>`:
```
function clearFileContainer() {
    $('#fileContainer').children().remove()
} 
```
