### ISSUE TITLE
Table Component - using Checkbox - Unable to select the whole row element

### ISSUE THREAD

**Issue by prateek04** [carbon-design-system/carbon#3748]
Hi Team,

I am having multi-select checkbox in the table. On each selection of checkbox, I want to get the index of the row. basically, I want to get the whole row data on checkbox selection.

<table [model]="model"  [showSelectionColumn]="true" [striped] = "true" (click)="onRowSelect($event)"></table>

Please help how can I achieve that.

**Comment by asudoh** [comment]
Hi 👋 are you using our React variant or our vanilla JavaScript library?
