### ISSUE TITLE
Toaster in Carbon component react is not reopening once closed.

### ISSUE THREAD

**Issue by rahullohakare20** [carbon-design-system/carbon#3752]
Please refer 
http://react.carbondesignsystem.com/?path=/story/notifications--toast

The issue is with Toaster of carbon component react.

Below is the code which I have used.

I have added toaster to my code its working fine at first attempt but once it closes after time out it is not reopening next time. 

Below is the code :

  public handleClick() {
    this.setState({ open: false });
  }

render() {
      return (
      <React.Fragment>

        {**this.state.open** &&
      (<ToastNotification
          className='toaster-custom'
          kind="info"
          title=""
          subtitle={"Title test"}
          iconDescription=""
          caption=""
          style={style}
          hideCloseButton={true}
          timeout={1000}
          key={this.count}
          onCloseButtonClick={() => {
            this.handleClick();
          }}
        ><div className="cls--btn" onClick={() => this.handleClick()}>
            &#10006;
          </div>
       </ToastNotification>)}
      </React.Fragment>
    );
  }

**Comment by asudoh** [comment]
Hi 👋 as you found, application code has no control over the `open` state. Probably you want to re-create the component via `key`?

**Comment by asudoh** [comment]
Let's merge this to #3801.
