### ISSUE TITLE
[ui-shell]: Skip to content and header name focus style inconsistant

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#3756]
There's inconsistency in the header name and skip to content focus styles both in color and width.

The header name also looks like it's not reaching the full height.

![Screen Shot 2019-08-16 at 12 50 03 PM](https://user-images.githubusercontent.com/4078018/63187428-7ffaa880-c024-11e9-97fe-0810bdb9865a.png)
![Screen Shot 2019-08-16 at 12 50 08 PM](https://user-images.githubusercontent.com/4078018/63187429-7ffaa880-c024-11e9-9357-d28b159b3135.png)

**Comment by joshblack** [comment]
This should be addressed! Let me know if you still run into this 😄
