### ISSUE TITLE
Jest testing issue with React components and mount

### ISSUE THREAD

**Issue by jlpatrick** [carbon-design-system/carbon#3759]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
We are in the process of migrating to Carbon 10 and have run into Jest errors with tests that previously passed. The failing tests use Enzyme **mount** to get a full rendering with child components, some of which are Carbon React components. (Tests that use **shallow** are OK and still pass.) The failure is:

 **Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.**

I am also seeing this stack trace reported with the error for a Modal:

    The above error occurred in the <button> component:
        in button (created by Modal)
        in div (created by Modal)
        in div (created by Modal)
        in div (created by FocusTrap)
        in FocusTrap (created by Modal)
        in Modal (created by ModalComponent)
        in ModalComponent (created by WrapperComponent)
        in WrapperComponent

> Is this issue related to a specific component?
Modal, AccordionSkeleton

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The existing tests to continue to pass after migration.

> What browser are you working in?
N/A

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.5.0",
    "carbon-components-react": "7.5.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Acoustic Content (the product formerly known as Watson Content Hub)

## Steps to reproduce the issue

I have created a simplified repo to show the issue with the Modal component.
1. Pull this repo:
https://github.com/jlpatrick/carbon-modal-test-app
2. Run **npm install**
3. Run **npm test**
4. Examine the test file to see if we are doing something incorrectly:
https://github.com/jlpatrick/carbon-modal-test-app/blob/master/src/ModalComponent.test.js

**Comment by joshblack** [comment]
Hi @jlpatrick! 👋 It seems like this issue is coming from the jest config, `@carbon/icons-react` is being treated as a stub and so `Close20` isn't correctly being resolved as a result 👍

**Comment by jlpatrick** [comment]
@joshblack Thanks for looking into this issue. I believe that stub was needed on the older version of Carbon that we were using and does indeed look to be the problem now.
