### ISSUE TITLE
[ui-shell] 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#3763]
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Can't use the keyboard to access the submenu items in the left hand navigation.

> Is this issue related to a specific component?

UI Shell - SideNav

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect to be able to select a submenu item using the keyboard only.

> What browser are you working in?

Firefox (works fine in Chrome)

**Comment by emyarod** [comment]
currently <kbd>Tab</kbd>, <kbd>Space</kbd>, and <kbd>Enter</kbd> are all functional for navigating through side nav items and submenu items with the keyboard
