### ISSUE TITLE
Modal: deprecated mixin and class

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#3768]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

There is a mixin and associated class that may be deprecated.

### `modal--color` mixin
We’re doing some work with the Modal and I’m curious if the `modal--color` mixin is still relevant.
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/_mixins.scss#L14

The mixin adds a border color to the bx--modal-container class, but the border on that element is set to 0px, I believe via the `reset` css. Because there is no border width, no color is visible in the component. It seems like that top border may have been a v9 style that didn’t get retained in the latest IDL styles of v10.

Am i correct that that top-bar color is no longer part of Carbon's modal?

### bx--danger--modal

This would also seem to mean that the class `bx--danger--modal` may not have any affect when applied to the modal. It's [listed in as a modifier for bx--modal](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/README.md#modifiers) but [in the Sass file](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/_modal.scss#L68), it only calls `modal--color`

I can't find any instance where the className is used, other than it being applied in the React modal, but it doesn't seem to have any JS functionality or add styling.

Is it correct that this className may not be needed?

thanks!

**Comment by tw15egan** [comment]
@scottnath Seems like it was just something that was leftover from the v9 days, nice catch. I'll make a PR to remove the extra code
