### ISSUE TITLE
<Icon> has breaking changes between carbon-react v6 and v7

### ISSUE THREAD

**Issue by SidneyJiang** [carbon-design-system/carbon#3771]
Based on npm-shrinkwrap.json, we were:
```
"carbon-components": {
	"version": "9.68.16",
},
"carbon-components-react": {
	"version": "6.80.1"
}
```
now we are
```
"carbon-components": {
	"version": "10.5.1",
},
"carbon-components-react": {
	"version": "7.5.0",
}
```

The following code used to work
https://github.ibm.com/org-ids/pipeline-ui/blob/master/lib/shared/components/Common/MessageHelper.jsx#L46, now it complains that `height of undefined`, I added height, it then complains that `icon.svgData undefined` or something like that, then `icon.viewBox`, basically they all turned out to be required. So I had to use `import { Information16  } from '@carbon/icons-react';` instead.

I made it working, but my main complain is that the migration doc only says `The name prop has been removed`, but didn't say how to fix it.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Using `@carbon/icons-react` is the right way to go. An alternative is using icon data in `<Icon>`: https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/react/src/components/Icon/Icon.js#L186-L194

BTW do you have a link to the document you referred to so we can see if it can be improved?

**Comment by SidneyJiang** [comment]
Search for Icon here https://github.com/carbon-design-system/carbon/blob/master/packages/react/docs/migration/migrate-to-7.x.md, you will see it is poorly documented.
