### ISSUE TITLE
Icons are being generated incorrectly

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3778]
@conradennis brought up that several icons are being rendered incorrectly on our site, this issue is for figuring out the issue in our underlying build logic and updating accordingly:

- User x-ray
- warning--alt--inverted--filled
- warning-square--filled
- undefined--filled
- unknown--filled

![image](https://user-images.githubusercontent.com/3901764/63443273-1bf82b80-c3fa-11e9-9df5-33b66e10ad47.png)

![image](https://user-images.githubusercontent.com/3901764/63443336-392cfa00-c3fa-11e9-8698-0c8a55baa3af.png)

![image](https://user-images.githubusercontent.com/3901764/63443296-261a2a00-c3fa-11e9-8c7f-459fb06c9484.png)

![image](https://user-images.githubusercontent.com/3901764/63443304-29151a80-c3fa-11e9-83d7-137ac8164905.png)

**Comment by laurenmrice** [comment]
Adding to this issue:
- Only a problem for 16px, seems like in elements there isn't a 16 add?
![Artboard.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/c81522bf-7ea8-440a-a916-07e69344690b)

- Alphanumeric numbers need to be filled not outlined in all sizes
![Artboard Copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/a70afad8-2e1b-46ff-9f9d-e437bee4cf54)

**Comment by tw15egan** [comment]
From #3847 

> a handful of icons are missing their site (knocked out) element.
> 
> <img alt="Screen Shot 2019-08-27 at 4 08 29 PM" width="201" src="https://user-images.githubusercontent.com/32881239/63804503-4d369700-c8e5-11e9-921f-4c22add2ab9e.png">
> 
> <img alt="Screen Shot 2019-08-27 at 4 08 15 PM" width="221" src="https://user-images.githubusercontent.com/32881239/63804504-4d369700-c8e5-11e9-90f7-b0a53da43464.png">
> 
> <img alt="Screen Shot 2019-08-27 at 4 08 11 PM" width="758" src="https://user-images.githubusercontent.com/32881239/63804505-4d369700-c8e5-11e9-9110-c0dfdafcea13.png">

**Comment by joshblack** [comment]
Looking at this now, doing an audit log of places it could be going wrong:

- ✅  Assets render correctly on the elements preview
- ✅ Assets render correctly on React preview
- ✅ Assets render correctly on website build with linked react preview
- ❌ Assets render correctly on website build without linked react

It seems like this issue will be resolved with the updated icon packages 👍 FYI @vpicone

**Comment by joshblack** [comment]
@laurenmrice is this on the main site, or in the design kit?

**Comment by laurenmrice** [comment]
@joshblack  this is happening in the design kit
