### ISSUE TITLE
August 2019 Endgame

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#3780]
This is the endgame schedule for our [August 2019](https://github.com/carbon-design-system/carbon/issues/3403) iteration, which includes the following projects:

- Support
- [Icons](https://github.com/orgs/carbon-design-system/projects/20)
- [Patterns curriculum workshop](https://github.com/orgs/carbon-design-system/projects/15)
- [Carbon website content audit and strategy](https://github.com/orgs/carbon-design-system/projects/23)
- Contribution model 
- IDL Site QA and Release

## Schedule

- Endgame leader: @jnm2377 
- Endgame sidekicks: @joshblack  (dev), @designertyler  (design)
- 08/23: Code freeze (EOD)
- 08/29: Endgame done
- 08/29: Expected release date

### Friday 08/23

- [x] Set endgame-specific branch protection rules
- [x] Coordinate delivery or resolution of the following items:
  - [x] TBD
- [x] Start code freeze (EOD)

### Monday 08/26

- [x] First Release Candidate cut
- [x] Complete first round of smoke tests
- [x] Share with Carbon Insiders for first round of testing

### Tuesday 08/27

- [ ] Collect first round of feedback from Carbon Insiders (if available)
- [ ] Triage release-specific issues and bucket them into two categories:
  - [ ] Stop release
  - [ ] Ship with known issues
- [ ] Coordinate merging of bug fixes related to release
- [ ] Cut next Release Candidate, if applicable
  - [ ] Share newest release with Carbon Insiders for additional rounds of testing

### Wednesday 08/28

- [ ] Cut next Release Candidate, if applicable
  - [ ] Share newest release with Carbon Insiders for additional rounds of testing

### Thursday 08/29
- [ ] Release next minor version

**Comment by aagonzales** [comment]
# Design kit updates
August release updates
https://github.com/carbon-design-system/carbon-design-kit/releases
- [ ] Need to update file on repo for release date

## New

### Components

- **Notification:** 
    - Added `low contrast` variation [#141](https://github.com/carbon-design-system/carbon-design-kit/issues/141)
    - Added `with action` variation. [#166](https://github.com/carbon-design-system/carbon-design-kit/issues/166) 
- **Radio button**: added horizontal group symbols, added category of "vertical group" [#164](https://github.com/carbon-design-system/carbon-design-kit/issues/164)
- **Text input**: 
    - added `with icon` variation [#143](https://github.com/carbon-design-system/carbon-design-kit/issues/143)

### Elements

- **Spacers**: added `layout` spacers [#155](https://github.com/carbon-design-system/carbon-design-kit/issues/155)
- **Type tokens**: [#169](https://github.com/carbon-design-system/carbon-design-kit/issues/169)
    - Added `$productive-heading-06`
    - Added `$productive-heading-07`
    - renamed all headings to have prefix "productive-"
- **Color tokens**: [#138](https://github.com/carbon-design-system/carbon-design-kit/issues/138)
    - Added `$inverse-focus-ui`
    - Added `$inverse-hover-ui`
    - Added `$inverse-link` [#147](https://github.com/carbon-design-system/carbon-design-kit/issues/147)

## Enhancements (updated)

### Components

- **Data table**: 
    - Selectable: added `selectable - hover` states for cell and row [#124](https://github.com/carbon-design-system/carbon-design-kit/issues/124)
    - enabled override for icon in `selectable` cell to allow for single select controls [#133](https://github.com/carbon-design-system/carbon-design-kit/issues/133)
- **Form**: [#164](https://github.com/carbon-design-system/carbon-design-kit/issues/164)
    - replaced all "form / ... / item" to be standard component symbols 
    - Form / modal: replaced custom buttons with buttons from modal component
- **Icon button**: [#134](https://github.com/carbon-design-system/carbon-design-kit/issues/134#issuecomment-506345218)
    - Added overrides for default background
    - Added `selected` state
- **Search**: 
    - updated typesize in large variation to use `$body-short-01` [#172](https://github.com/carbon-design-system/carbon-design-kit/issues/172)
    - Added override to allow the underline to be hidden [#149](https://github.com/carbon-design-system/carbon-design-kit/issues/149)
- **Structured list**: updated type title to use `body-long-01` [#146](https://github.com/carbon-design-system/carbon-design-kit/issues/146)
- **Text area**: added `label + helper text` category and states [#144](https://github.com/carbon-design-system/carbon-design-kit/issues/144)

### Elements

- **Spacers**: [#155](https://github.com/carbon-design-system/carbon-design-kit/issues/155)
    - Updated scale to match [spacing tokens](https://www.carbondesignsystem.com/guidelines/spacing#spacing-scale)
    - Update visual style to match spec-ing style
- *Color tokens*: [#167](https://github.com/carbon-design-system/carbon-design-kit/issues/167)
    - (White, Gray 10) Updated `interactive-02` value in to `Gray 80` (effects secondary buttons) 
    - (Gray 10, Gray 90, Gray 100) Updated `$highlight` value
    - (Gray 100) Updated `$skeleton-02`

## Bugs 

- **Code snippet**: enabled overrides for background color [#139](https://github.com/carbon-design-system/carbon-design-kit/issues/139)
- **Data table**
    - Action bar: replaced custom ghost buttons with primary button symbols [#170](https://github.com/carbon-design-system/carbon-design-kit/issues/170)
    - (Gray 90, Gray 100) added in various missing symbols [#152](https://github.com/carbon-design-system/carbon-design-kit/issues/152)
- **Date picker**: 
    - (Gray 10, Gray 90, Gray 100) added missing drop shadow to calendar menu in [#171](https://github.com/carbon-design-system/carbon-design-kit/issues/171)
    - (White) Added missing error state [#154](https://github.com/carbon-design-system/carbon-design-kit/issues/154)
- **Dropdown**: 
    - Fixed text box resizing issue [#159](https://github.com/carbon-design-system/carbon-design-kit/issues/159)
    - Inline: fixed vertical alignment [#173](https://github.com/carbon-design-system/carbon-design-kit/issues/173)
- **Modal**: update background and field colors [#164](https://github.com/carbon-design-system/carbon-design-kit/issues/164)
- **Progress indicator / vertical**: fixed resizing issue [#160](https://github.com/carbon-design-system/carbon-design-kit/issues/160)
- **Tab**: (Gray 100) fixed missing overrides [#156](https://github.com/carbon-design-system/carbon-design-kit/issues/156)
- **Tile / expandable**: (Gray 90, Gray 100) fixed pinning issue with chevron [#157](https://github.com/carbon-design-system/carbon-design-kit/issues/157)
- **Tool tip**: fixed scaling issue with shark fin [#151](https://github.com/carbon-design-system/carbon-design-kit/issues/151)

**Comment by shixiedesign** [comment]
# Charts

Please note @jnm2377 these development is done by Carbon-charts team and they are not sync'ed up with our release cycles. So these info are just for our reference, and might not be appropriate for blogpost except the last section on pages for `carbon-website`, but I will let you decide! 

`Carbon-charts` repo is getting continuously re-skinned to match the new IBM Design Language. PRs lined up to be pushed are:

### in PR
- Area chart contribution from Andrew Nelson! https://github.com/carbon-design-system/carbon-charts/pull/315
- Restyle: pie / donut chart https://github.com/carbon-design-system/carbon-charts/pull/288
- Restyle: all tooltiops https://github.com/carbon-design-system/carbon-charts/pull/307

### Implementation in progress
- A overall refactor is happening to prepare the grounds for further grid/typography restyling of all charts: https://github.com/carbon-design-system/carbon-charts/pull/275

### Designs completed
- Restyle: legends https://github.com/carbon-design-system/carbon-charts/issues/287
- Time series: https://github.com/carbon-design-system/carbon-charts/issues/299

### Design in progress
- Reveal axis label on hover https://github.com/carbon-design-system/carbon-charts/issues/314
- Annotations styling https://github.com/carbon-design-system/carbon-charts/issues/329
- Toolbar / filter / zoom bar styling & layout https://github.com/carbon-design-system/carbon-charts/issues/330
- Gauge / meter design

### Documentation (Carbon-website)
- Completed IA and scope of work of Data visualization website content for next project cycle. https://github.com/carbon-design-system/carbon-website/issues/208

**Comment by joshblack** [comment]
# Icons

- Introduced an updated Sketch kit for the IBM Design Language with a full set of icons generated from code
- Official introduction of `@carbon/icons-react` package, with support for all icons from the IBM Design Language
- Official introduction of `@carbon/pictograms-react` package, with support for all pictograms from the IBM Design Language
- Official launch of our updated iconography section on our website, with support for searching by alias, category, and icon name

**Comment by alisonjoseph** [comment]
# IBM Design Language website QA/launch

- New IBM Design Language website launched utilizing the `gatsby-carbon-website` theme package.
- 80+ issues/bugfixes were closed out
- https://www.ibm.com/design/language

**Comment by jnm2377** [comment]
# Contribution model

- Submitted an RFC with our proposed component contribution model based on our research: https://github.com/carbon-design-system/carbon/pull/3769
    - proposes a monorepo for custom components
    - proposes a space to surface these components on our website
    - proposes a process to potentially contribute custom components to core carbon
- Updated code of conduct
- Updated general contribution docs (bug fixes)
- Explore potential models for patterns contributions (which will be continued next release)

**Comment by janchild** [comment]
# Carbon website content audit and strategy

Members: @janchild,  @connor-leech, @jillianhowarth

- Conducted a quantitative audit to determine current breadth of components and patterns in other design systems and internal pattern libraries.
- Created standardized content templates of content needed (guidelines, images) for components and patterns.
- Updated governance documentation 
- Updated experimental Overview page with patterns coming soon
- Created Strawman IA
- Content Strategy planning
- Removed duplicate content between IBM Design Language and IBM Carbon sites

**Comment by aagonzales** [comment]
# Patterns curriculum workshop

- Presented to the ECP bootcamp
   - Overview of system
   - Workshop on "how to design with Carbon"

**Comment by jnm2377** [comment]
# Support

### Notable elements fixes
- **`css-reset`**: apply box-sizing reset to all descendants (#3884)
- **Grid**: update margin at max breakpoint (#3824) 
- **Type**: add default type with feature flag (#3742) 

### Notable component fixes
- **Sidenav**: fixes rails variation collapsed-state bugs and tabbing (#3626) 
- **File uploader**: add in disabled styles (#3799) 
- **Tabs**: update token values, allows it to be theme-able (#3828)

### Notable a11y fixes
- **Tile**: a11y fixes for expandable tile when collapsed (#3785) 
- **TableToolbarSearch**: adds support for back-tab (#3836) 
- **Dropdown, ComboBox**: adds listener to open/close menu on enter (#3862) 
- **Breadcrumb**: removes terminating slash for current page, means it doesn't just rely on color for a11y (#3750)

**Comment by joshblack** [comment]
Released in https://github.com/carbon-design-system/carbon/releases/tag/v10.6.0
