### ISSUE TITLE
CSS Reset mixin only applies `box-sizing` rule to immediate children

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#3786]
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

The css reset currently only applies `box-sizing: inherit` (which, in turn, applies `box-sizing: border-box`) to its immediate children: 

```scss
@mixin reset {
  @if variable-exists(css--reset) == false or $css--reset == false {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font-family: inherit;
    vertical-align: baseline;

    & > *,
    & > *:before,
    & > *:after {
      box-sizing: inherit;
    }
  }
}
```

This causes issues for folks who don't use the reset globally. For instance, in the case of the `ComboBox` -- even though the underlying `ListBox` has the reset mixin applied to the parent element, the `box-sizing` rule doesn't apply to children beyond the menu *container*, so you get a situation where options inside the menu don't have the correct box-sizing applied, cause extra space at the end of the menu like this:

![Screen Shot 2019-08-21 at 3 14 27 PM](https://user-images.githubusercontent.com/9057921/63465376-bb331800-c426-11e9-937a-1b63166c0f3d.png)

If the reset mixin were to be altered so that it could apply `box-sizing` to all descendants, not just immediate children, then `box-sizing` could be directly applied to the list box menu options in this case (and perhaps there are other components where descendant are missing out on `box-sizing` due to this issue -- but again, you'd only notice if you had `$css--reset: false`).

**Comment by jendowns** [comment]
Please note that I updated the title & description after looking into this issue a bit, now that I (maybe) understand the cause better 🤔

**Comment by joshblack** [comment]
I think we could 100% update this to be more broad, I think `& *` would be the intended use-case anyways versus direct descendants and we could treat this as a bug instead of a layout breaking change.

**Comment by jendowns** [comment]
Thanks @joshblack! I created a PR for that here: https://github.com/carbon-design-system/carbon/pull/3884
