### ISSUE TITLE
Add pictogram generation logic to Sketch package

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3794]
Once we have our pictogram packages merged in, we should look into adding a pictogram command to our Sketch plugin that supports rendering pictograms in the same way we render icons.

**Comment by chrisconnors-ibm** [comment]
keepalive[bot]

**Comment by chrisconnors-ibm** [comment]
we really need someone to pick this up urgently, so we can publish our package/repo asset based IDL Sketch Library that is a 1:1 functional replacement for the hand managed IDL library.
then we can:
1) Deprecate the hand crafted IDL library
2) update our theme libraries to refer to the new asset based, generated IDL
3) rule the world

**Comment by chrisconnors-ibm** [comment]
keepalive[bot]

**Comment by chrisconnors-ibm** [comment]
how did this get stalebotted in 8 days? @joshblack

**Comment by joshblack** [comment]
Hmm, not sure. Maybe it's going from the 15day mark? Versus the re-open time
