### ISSUE TITLE
Document some code snippets to make use of the grid

### ISSUE THREAD

**Issue by ajdaniel** [carbon-design-system/carbon#38]
## Overview

When I look at the Grid overview page, I understand the concepts, but I don't know how to put it into practice. How do I implement a grid in my UI?

```gherkin
Feature: Grid
  As a developer
  I want to know how to implement grids
  So that I can make use of them
```

**Comment by marijohannessen** [comment]
Hi Andrew! I am going to add some guidelines around this on our website by the end of this week. I'll keep you updated here, thanks!

**Comment by azinod** [comment]
Hello, any updates on this?

**Comment by marijohannessen** [comment]
Hi @azinod , a grid example is currently in a PR https://github.com/carbon-design-system/carbon-components/pull/45. I just need to add a few more examples before merging but feel free to take a look at the code there in the mean time. Thanks!
