### ISSUE TITLE
Incorrect Info32 icons-react import resolves

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#3808]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] "@carbon/icons-react": "^10.4.1", (also tested on 10.5)

## Detailed description

`import Info from '@carbon/icons-react/lib/information/32';` provides the correct 32x32 icon
`import { Info32 } from '@carbon/icons-react';` provides incorrect 16x16 icon

@joshblack pointed out that I should be importing `Information32` instead of `Info32`. 
Using `Information32` does fix the issue for me, though `Info32` _does_ resolve. It seems this might not be intended behavior.

## Steps to reproduce the issue

1. Import these icons
2. Add as a `renderIcon` to a `Tooltip`
3. See the discrepancy

https://codesandbox.io/s/codesandbox-16p7d

![image](https://user-images.githubusercontent.com/3360588/63603887-1af90280-c590-11e9-8276-70974d3f8702.png)

**Comment by tw15egan** [comment]
Weird! After doing some digging, it seems like that 16px `Info` icon is just the default. If you change the CodeSandbox to 

```jsx
import { Test } from "@carbon/icons-react";

<Tooltip renderIcon={Test}>incorrect?</Tooltip>
```

It also renders the 16px icon. It seems like we provide the `Information` icon as default

https://github.com/carbon-design-system/carbon/blob/3e99fc7a9388999ee21ffa1b4f8b7cca200bc1d6/packages/react/src/components/Tooltip/Tooltip.js#L195

**Comment by joshblack** [comment]
Ah yeah, that makes sense. `Info32` ended up being `undefined` so the fallback is used ☝️

**Comment by tw15egan** [comment]
I wonder if the fallback should be an error icon?

**Comment by joshblack** [comment]
Not sure, info seems like a helpful default but not sure what's typical in product.

**Comment by joshblack** [comment]
Going to close this for now, let us know if you have any more questions @tay1orjones!
