### ISSUE TITLE
[grid] Grid max breakpoint's margin differs from docs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#3810]
## What package(s) are you using?

- [x] `@carbon/grid`

## Detailed description

I'm seeing a difference between the specs on the carbon website, and sketch files, and the grid code. On the website it says the max breakpoint margin is `24px`, but in the code it maintains at `16px`.

## Steps to reproduce the issue

What I see in sketch and the [website](https://www.carbondesignsystem.com/guidelines/layout#breakpoints).

![image](https://user-images.githubusercontent.com/3793636/63609773-72519f80-c59d-11e9-8ac2-df2c24bee440.png)

What I see in the [code](https://carbon-elements.netlify.com/grid/examples/preview/)

![image](https://user-images.githubusercontent.com/3793636/63610201-792ce200-c59e-11e9-85a8-6aeae21ca52a.png)

## Additional information

- https://sketch.cloud/s/ngV7z
- https://www.carbondesignsystem.com/guidelines/layout#breakpoints
- https://carbon-elements.netlify.com/grid/examples/preview/

**Comment by joshblack** [comment]
cc @jeanservaas which value is correct here? Do we need to update in code or on the site for the correct value?

**Comment by jeanservaas** [comment]
max breakpoint margin is 24px -- that's correct. If the grid package is not reflecting that we need to update it. 

sorry for the delay!

**Comment by joshblack** [comment]
PR'd #3824 to update 👍
