### ISSUE TITLE
[React Dropdown] Carry over a11y updates from Vanilla 

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3815]
a11y updates were made in the vanilla version of Dropdown that need to be carried over to React

https://github.com/carbon-design-system/carbon/pull/3586

**Comment by emyarod** [comment]
the vanilla and React dropdowns don't map 1 to 1 because the React dropdown along with ComboBox and MultiSelect extend the Listbox component. We probably need to update the listbox markup first before making any changes to the React dropdown

**Comment by abbeyhrt** [comment]
I'm gonna close this issue. The accessibility additions that dropdown needs are documented in other PRs and our Vanilla and react versions do not have complete parity. We will defer to our other issues for accessibility fixes to dropdown.
