### ISSUE TITLE
SelectableTile: can not read event property

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#3829]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

https://codesandbox.io/s/codesandbox-s3wvp
when capturing the event using `handleKeyDown`, the following error is thrown:
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `isPropagationStopped` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

> Is this issue related to a specific component?

Yes, `SelectableTile`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

it should be the event object

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

![image](https://user-images.githubusercontent.com/10108576/63715327-8dc4e080-c811-11e9-90e4-23718162f5cf.png)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Cloud pak for data

## Steps to reproduce the issue

https://codesandbox.io/s/codesandbox-s3wvp

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/codesandbox-s3wvp

**Comment by emyarod** [comment]
closed by https://github.com/carbon-design-system/carbon-components-react/pull/2408

**Comment by nelsonchen90** [comment]
@emyarod I saw the last v9 version is published on July 25. can we publish another one to include this and other fixes?
