### ISSUE TITLE
Export pixel values with `breakpoints` object

### ISSUE THREAD

**Issue by showell215** [carbon-design-system/carbon#3833]
### Summary

The [breakpoints export](https://github.com/carbon-design-system/carbon/blob/e5ae58647d32aaae687e811d3f61e988cab1c302/packages/layout/src/index.js#L41) from the `@carbon/layout` package exports breakpoint values as `rem`s. For use in JavaScript it would be nice to be able to reference the pixel value as well.

### Justification

I've encountered a couple of cases where I'd like to set application state in my React app based the current screen size. It would be nice to have those static breakpoint pixel values available from Carbon instead of hard-coding them or converting the `rem` values back to pixels. 

### Desired UX and success metrics

Breakpoints pixel values are available in the `breakpoints` object alongside the `rem` values.

### "Must have" functionality

See above

### Specific timeline issues / requests

n/a

### Available extra resources

I could put up a PR if desired.

**Comment by asudoh** [comment]
Hi 👋 do you want to something similar to (reverse of) https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/layout/src/index.js#L17-L19 using https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/layout/src/index.js#L10?

**Comment by showell215** [comment]
Hi @asudoh, thanks for having a look at this.

That would work, or alternatively those pixel width values (I.e. 672, etc) could just be added as a property to each entry in the ‘breakpoints’ object. That may be simpler since it wouldn’t require another conversion.

Thanks!

**Comment by asudoh** [comment]
We'll monitor how common the use case there is. The issue description seems to imply that the application is attempting to perform JavaScript-based layout query (my apologies if it's not the case), which is known with adverse effect to performance.

**Comment by showell215** [comment]
OK, yes that's pretty much what we're doing, though not as a general rule. We just have a one-off case where we need to set the value of a `prop` in our React app depending on the currently applied breakpoint, so just comparing two static values in JS - `window.offsetWidth` to a statically defined Carbon breakpoint pixel value. And given that Carbon defines those breakpoints already, we'd rather not redefine them within our code.

Not sure how common of a use case this is - like I said, it's kind of a one-off for us - but we'd rather use the source of truth if possible.

Thanks!

**Comment by joshblack** [comment]
Hi @showell215! 👋 The exports provided from `@carbon/layout`'s JS should be treated as unstable, most likely, and they'll 100% change to allow for more flexible unit representations like you're requesting.

In the meantime, converting from rem to pixel would be preferred and we'll 100% track this use-case when expanding the functionality 😄

**Comment by showell215** [comment]
Great, thanks for that info @joshblack
