### ISSUE TITLE
_tooltip.scss is exported into globals folder

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#3834]
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

Noticed in my node_modules that the `_tooltip.scss` partial is exported into the globals folder in addition to it's usual spot in `/components/tooltip`. I assume this is not intentional. If it is intentional, is there a relevant thread to understand why?

## Steps to reproduce the issue

1. install carbon-components 10.4.1 (I searched and didn't see an issue regarding this, but have not checked 10.5)

## Additional information

![image](https://user-images.githubusercontent.com/3360588/63722790-7be73b80-c819-11e9-8237-4114def041b3.png)

**Comment by asudoh** [comment]
Hi @tay1orjones thank you for bringing this up! `_tooltip.scss` in `globals` folder is for reusable part of the tooltip (e.g. hover-over text for other components), whereas `_tooltip.scss` in `components` folder is the original part of the tooltip (interactive/definition/icon tooltips). CC @emyarod

**Comment by emyarod** [comment]
as @asudoh mentioned, this new partial in `globals` contains mixins which are reused across our tooltip variants

related #2366 #2732 #2781 #2783 #2923 #3115 #3151 #3739
