### ISSUE TITLE
[Floating Menu Vanilla] returns focus to trigger when it shouldn't

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3835]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Bug found when working with interactive tooltips: https://github.com/carbon-design-system/carbon/pull/3476/commits/5c99d3f683f0a475a123cb4de68e99c0f136b79a#diff-403280a2b19d0244d2181571626e05a5L183

When the user clicks on an focusable element and a floating menu is open, the trigger of the floating menu is being focused instead of the element the user clicked on. This causes the user to have to click twice to focus the correct element.

there is a bug with setting `relatedTarget` for when a user clicks on a focusable element. In that instance, the target should retain focus but close the floating menu. Currently, it's keeping the `relatedTarget` as an element within the floating menu so it's passes `this.element.contains(event.relatedTarget)` and there is no way to differentiate between a "mouse click" and "keyboard focus". 

> Is this issue related to a specific component?

Any component that uses floating menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

If the user clicks on a focusable element that element should get focus without clicking twice. However the the current behavior for keyboard users should be retained.

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

10.5

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

This can be tested by adding a text input anywhere on the interactive tooltip demo in a location the user can click on when the menu is open

**Comment by elizabethsjudd** [comment]
Test for bug:
```
it('Should hide the tooltip upon focusing an external element and focus moves to external element', function() {
  element.dispatchEvent(new CustomEvent('click', { bubbles: true }));

  const input = document.createElement('input');
  input.type = 'text';
  input.id = 'example-input';
  document.body.appendChild(input);

  document
    .getElementById('example-input')
    .dispatchEvent(new CustomEvent('focus', { bubbles: true }));
  expect(floating.classList.contains('bx--tooltip--shown')).toBe(false);
  expect(document.activeElement).toEqual(input);
});
```

**Comment by asudoh** [comment]
Thank you for reporting @elizabethsjudd! Recommended to add some code to see if the focus went to focus sentinel vs. other elements to determine if the focus should go back to the trigger button.

**Comment by joshblack** [comment]
Hey there! :wave: Closing this out due to inactivity, feel free to comment and I can re-open!
