### ISSUE TITLE
Add alignment to the Carbon's tooltip component

### ISSUE THREAD

**Issue by haydaralrikabi** [carbon-design-system/carbon#3837]
### The problem
The tooltip overflows a parent modal when the tooltip label is near the edge of that modal.
This restricts the designer to place the label away from the edges of a parent container.

![image](https://media.github.ibm.com/user/204120/files/d0107f80-c25d-11e9-89ad-8f7fff078e3e)

![image](https://media.github.ibm.com/user/204120/files/19f96580-c25e-11e9-93bd-d3f264c26337)

### The solution
The tooltip component should accept a default prop to align its tooltip to the start / centre / or end of the tooltip label (just like the tooltipDefinition component).
The caret should always point to the centre of the tooltip label.

![image](https://media.github.ibm.com/user/204120/files/f33b2f00-c25d-11e9-96de-3b90eebfc43b)

![image](https://media.github.ibm.com/user/204120/files/0948ef80-c25e-11e9-9629-df2dee0b982b)

### Additional information
This can be a partly fix for the above scenario, because the other part of it is when the label is in the end of a line within a container (when the default alignment is set to ‘start’).

**Comment by emyarod** [comment]
just want to double check with @carbon-design-system/design that we want to support this in the interactive tooltip (we currently only support this functionality in definition and icon tooltips)

**Comment by aagonzales** [comment]
Yes, I think if we're doing it for the other two types of tooltips then we should do it for interactive tooltip as well.

**Comment by elizabethsjudd** [comment]
not stale

**Comment by zacharydmoore** [comment]
Has there been any progress on this? I'd like this functionality as well!
