### ISSUE TITLE
Icon library (Carbon and IDL): Some icons are missing the inside (white/compound) element

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#3847]
a handful of icons are missing their site (knocked out) element.

<img width="201" alt="Screen Shot 2019-08-27 at 4 08 29 PM" src="https://user-images.githubusercontent.com/32881239/63804503-4d369700-c8e5-11e9-921f-4c22add2ab9e.png">

<img width="221" alt="Screen Shot 2019-08-27 at 4 08 15 PM" src="https://user-images.githubusercontent.com/32881239/63804504-4d369700-c8e5-11e9-90f7-b0a53da43464.png">

<img width="758" alt="Screen Shot 2019-08-27 at 4 08 11 PM" src="https://user-images.githubusercontent.com/32881239/63804505-4d369700-c8e5-11e9-9110-c0dfdafcea13.png">

**Comment by tw15egan** [comment]
Going to close this as it seems to be tracked over in https://github.com/carbon-design-system/carbon/issues/3778
