### ISSUE TITLE
invalid textarea width

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon#3848]
in the examples on https://www.carbondesignsystem.com/components/text-input/code/ the invalid (validity error) textarea example is 24px wider than the others.  I assume this is a mistake

**Comment by alisonjoseph** [comment]
I think this is actually an issue w/ the component. The invalid class adds padding, which is making it wider than normal.

**Comment by emyarod** [comment]
I think this is a non issue unless we want to set a fixed default width on the component

**Comment by tw15egan** [comment]
Can't we just add the extra padding to the basic textarea? 

Curious what @carbon-design-system/design thinks of this solution

<img width="542" alt="Screen Shot 2019-08-27 at 2 09 32 PM" src="https://user-images.githubusercontent.com/11928039/63808335-916d6b80-c8d4-11e9-8119-7a37291914f1.png">

**Comment by emyarod** [comment]
I believe we wanted to avoid the extra right padding for valid textareas (from a discussion...back when I added the invalid icon during the v10 update), but maybe our stance has changed on that

**Comment by aagonzales** [comment]
I'm not sure how it should technically work but if this was in a form we wouldn't want the invalid field to be longer than the valid fields. Will the invalid state always increase in width? If yes, then I think we need to re-think the internal padding.

**Comment by tw15egan** [comment]
Unless a smaller width is specified on the container (`bx--form--item`), the invalid will be larger when there is no width specified. [Link to example](https://codesandbox.io/s/codesandbox-7rhrg)

<img width="624" alt="Screen Shot 2019-09-04 at 11 19 03 AM" src="https://user-images.githubusercontent.com/11928039/64280407-e9742580-cf05-11e9-9d13-36e32fe68131.png">

A user could fix this by adding width to their form items. Here is an example with a specified `300px` width on form items:

<img width="399" alt="Screen Shot 2019-09-04 at 11 19 58 AM" src="https://user-images.githubusercontent.com/11928039/64280475-0a3c7b00-cf06-11e9-817e-b5c388a6796e.png">

**Comment by aagonzales** [comment]
Ok, I'm wondering if we should just specify it in the example so users know that the invalid and valid widths should have width parity.

**Comment by tw15egan** [comment]
Since `TextArea` is now full width of the container (https://github.com/carbon-design-system/carbon/pull/4995), this shouldn't be an issue anymore. Will be reflected on the website once the package is updated. 


<img width="535" alt="Screen Shot 2020-01-28 at 12 57 00 PM" src="https://user-images.githubusercontent.com/11928039/73304755-b3de1a80-41cd-11ea-99a3-025ebed24688.png">
