### ISSUE TITLE
Tab Control Mobile Consistency 

### ISSUE THREAD

**Issue by tomdev10** [carbon-design-system/carbon#3852]
### Summary

I wonder if it's possible to expose the mobile design as a prop in the tabs component? To choose if you want to collapse them in a drop down? 

### Justification

Needless to say if you have more than 3 tabs it makes sense, but arguably if you have 3 or less, especially if you have icons on the tabs rather than words, it's better for UX consistency if the tabs hold the same structure?

### Desired UX and success metrics

Desired UK is to maintain the horizontal tab structure on mobile displays

### "Must have" functionality

An exposed prop, "dropdown" maybe, that can be set to false (optionally) so that the horizontal tab structure can be maintained.

### Specific timeline issues / requests

Nope! 👍 It is possible to work around this by overriding the styles, but it would be far far cleaner to do this with props.  

### Available extra resources

Happy to assist working on this :)

**Comment by tomdev10** [comment]
<img width="713" alt="Screenshot 2019-08-28 at 11 13 30" src="https://user-images.githubusercontent.com/48121926/63847068-ee285f00-c984-11e9-9371-2d210fbfe525.png">

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by designertyler** [comment]
We actually just implemented horizontally scrolling tabs on our website so there's no pushback from the design side. 👍 

![Aug-28-2019 14-44-22](https://user-images.githubusercontent.com/19270502/63966183-4aac7c80-ca60-11e9-985c-df99ea4a6aa5.gif)

**Comment by tomdev10** [comment]
Okay that's good to know. How are they implemented? Is my suggestion solution a way of making this easier?

**Comment by shixiedesign** [comment]
Hi @tomdev10 I think your idea of keeping tab's structure when possible make sense. @designertyler I just verified that our website's tabs doesn't have the same behavior as our component `Tabs`, which still turns into a dropdown on mobile. 

@tomdev10 @tw15egan Do you think it's possible to implement some width-awareness logic, so that "dropdown" format kicks in when the tabs' total width exceeds container width? I'm a bit reluctant to expose the responsive behavior as a knob because we are working towards build-in responsiveness to all components. Though this can be discussed. Perhaps we can expose a knob to turn it off, and keeping default behavior to turn into dropdown on mobile. Lemme know if building in a width-awareness is possible. Thanks!

**Comment by asudoh** [comment]
Weighing in; What I know in this problem space is that getting up-to-date information of element (container) width requires [Resize Observer](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to be supported in all browsers we support, and getting around that limitation tends to be tough.

Update: I now remembered a person coined an idea of ["element query"](https://tomhodgins.github.io/element-queries-spec/element-queries.html), but [CSS standard guys seem to have a performance concern](https://gist.github.com/davatron5000/bbede54cf189bf53e4de#concerns-and-current-thinking).

**Comment by shixiedesign** [comment]
Thank you Akira! I will bring this issue up at design critique later this week to see what we can do at the meanwhile. Sounds like we cannot implement the ideal width-aware tabs just yet, but we can incorporate horizontal scroll, and expose that as an alternative to dropdown for our users. Will update issue with what design team come up with later.

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Going to fold this under: https://github.com/carbon-design-system/carbon/issues/3852 if that's okay with everyone! Let me know if not 😄
