### ISSUE TITLE
HeaderMenu does not close when opening another HeaderMenu

### ISSUE THREAD

**Issue by chrisbygrave** [carbon-design-system/carbon#3853]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The HeaderMenu component contains a bunch of event handlers intended to close the menu when you click away from it. It works for me in all cases other than when I open up another HeaderMenu.

> Is this issue related to a specific component?

HeaderMenu.

> What browser are you working in?

Chrome (but consistent cross-browser).

> What version of the Carbon Design System are you using?

10.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This is ICP4I, but it isn't a pressing or blocking issue.

## Steps to reproduce the issue

https://codesandbox.io/s/codesandbox-6pyvj?fontsize=14

1.  Click menu one and you see the menu containing 'item one'.
2. Click anywhere outside the menu (except for menu two) and menu one will close.
3. Open menu one again.
4. Click menu two and you see the menu containing 'item two', but menu one is still open beneath it.

## Additional information

<img width="318" alt="Screenshot 2019-08-28 at 11 11 42" src="https://user-images.githubusercontent.com/3779290/63846906-a570a600-c984-11e9-81ca-aded5e81afdd.png">

**Comment by asudoh** [comment]
Seems that the problem is no longer seen at https://codesandbox.io/s/codesandbox-6pyvj?fontsize=14 - Assuming that it's been fixed. Feel feel to let us know if anybody finds otherwise.
