### ISSUE TITLE
Carbon Grid class bx--col doesn't include top or bottom padding

### ISSUE THREAD

**Issue by mattalco** [carbon-design-system/carbon#3860]
## What package(s) are you using?

- [ x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Our team wraps the Carbon Grid classes into a component and I've noticed what I think is an inconsistency between the code and the documentation.

The documentation (links and screenshots below) states that there's a standard 16px padding on Items (that's how I read it, which may be incorrect). When I look at the `bx--col` class, I only see padding on the left and right.

> Is this issue related to a specific component?

This issue is related to the Grid classes. Specifically `bx--col`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected a standard padding to be applied on all sides of elements tagged with the `bx--col` class instead of just the left and right.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.5.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

I work within IBM on the IBM Marketplace.

## Steps to reproduce the issue

1. Create a simple Grid and with a Row and Columns. I have a link below.

2. https://codesandbox.io/embed/carbon-components-getting-started-u9dmm

## Additional information
- See padding section in https://www.carbondesignsystem.com/guidelines/layout/#grid-behaviors
<img width="233" alt="Screen Shot 2019-08-29 at 11 32 22 AM" src="https://user-images.githubusercontent.com/13972013/63954191-b850ac80-ca50-11e9-871b-fc2a39cec7e4.png">

<img width="1268" alt="Screen Shot 2019-08-29 at 9 49 22 AM" src="https://user-images.githubusercontent.com/13972013/63946074-820c3080-ca42-11e9-947b-e974c17e4a68.png">

**Comment by joshblack** [comment]
cc @jeanservaas would we want the grid code to ship with vertical padding? Right now we only have padding specified for gutters versus adding 16px padding to descendants in columns

**Comment by jeanservaas** [comment]
Weird, you kind of read my mind, I was noticing this discrepancy yesterday. Ideally, I think the answer to your question is yes... the grid code should ship with vertical padding that matches the side padding... 

Chiu's grid guidance examples with padding had both the vertical and the left and the right. 

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/43144260/64033614-6d976900-cb12-11e9-9632-75b25db13dcf.png">


<br>

Whereas the examples I've been creating for grid code tab follow what you've done for the grid demo and only have the left and the right shown.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/43144260/64032918-09c07080-cb11-11e9-841d-57b20a8f884f.png">

But, I do want to make the point, that if people are using the 32px, the 16px or the 2px scenarios on say a dashboard situation, they want to also keep their vertical padding consistent with that choice.

**BUT:**
My question is, if we attach it to the grid package... is that going to be a problem for Mixed use scenarios? I'm trying to think of a case where i might be an issue -- let's talk in person about it!

**Comment by mattalco** [comment]
@joshblack I just wanted to followup here given the work being done over at https://github.com/carbon-design-system/carbon/pull/3892/ to see if a consensus has been reached.

**Comment by joshblack** [comment]
@mattalco I definitely think we'll look into adding vertical padding helpers for this use-case, I don't think we'll want columns to define these by default, however.

**Comment by mattalco** [comment]
@joshblack Thanks! We're super excited about the Carbon Grid component and can't wait to use it.
