### ISSUE TITLE
Column names are out of line in compact line mode

### ISSUE THREAD

**Issue by taleixo** [carbon-design-system/carbon#3865]
Column names are out of line in compact line mode when the column name is too large and when there are multiple columns in the table

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
**When the column name is too large and when there are multiple columns in the table, the column names are out of line in compact line mode**

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?
**The table row contemplate all the text**

> What browser are you working in?
**Chrome v76.0.3809.132 and Firefox v68.0.2**

> What version of the Carbon Design System are you using?
**10.5.1**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Include a column name too large
2. Select the compact mode in the table

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

![image](https://user-images.githubusercontent.com/54679554/63957997-de317d80-ca5f-11e9-8996-0ba65c7e300d.png)

![image](https://user-images.githubusercontent.com/54679554/63958009-e7224f00-ca5f-11e9-9274-61f8b6f26611.png)

**Comment by tw15egan** [comment]
Do you have any custom styles being applied there? Testing locally I'm seeing the header row expand based on content:

<img width="733" alt="Screen Shot 2019-08-29 at 11 43 28 AM" src="https://user-images.githubusercontent.com/11928039/63967437-45e0cc00-ca52-11e9-90a0-3c7f696a8c45.png">

<img width="1140" alt="Screen Shot 2019-08-29 at 11 43 13 AM" src="https://user-images.githubusercontent.com/11928039/63967451-4ed19d80-ca52-11e9-81db-bda32fa0e88a.png">

**Comment by tw15egan** [comment]
Would be helpful to provide a codesandbox link reproducing your issue so we are able to debug more efficiently

**Comment by taleixo** [comment]
We avoid customizing the carbon elements as much as possible, but let's analyze to make sure

**Comment by joshblack** [comment]
Hi there! Going to close this one due to inactivity. If you could provide a codesandbox with steps to reproduce that'd be awesome and we can re-open this!
