### ISSUE TITLE
October 2019 Planning

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#3871]
# Timeline

- **September 2nd, 2019**: Start release cycle
- **September 27th, 2019**: Code freeze for the endgame
- **September 30th - October 4th, 2019**: Release Candidate cuts and smoke tests
- **October 8th, 2019**: Release, Endgame done

# Projects

#### Squad
- @chrisconnors-ibm (lead), @jeanservaas , @aledavila , @jnm2377, @joshblack 

#### Primary goals
- Nick Hahn's Summit (late September)
- Alignment, validation, technical point of view, but no design action
- Operational CLA (Code of conduct?) needs to go up on the site (Need content review)

#### Stretch goals
- TBD

#### Deferred goals
- High fidelity designs for community contribution experience on Carbon site

#### Squad
- @tw15egan, @alisonjoseph, @mattrosno, @shinytoyrobots 

#### Squad
- @joshblack (lead), @emyarod 
#### Primary goals
- Enable theming through CSS Custom Properties behind a feature flag
- Code up rules and constraints for how tokens are used together, for example icon size with type
- Consolidate all theme-able properties into one map

#### Stretch goals
- Pull out styles into a styles package

#### Deferred goals
-

#### Squad
- @dakahn (lead), @aledavila, @abbeyhrt, @asudoh 

#### Primary goals
- clear high and medium priority issues in a11y project backlog
- general a11y team advocacy and training throughout the project

#### Stretch goals
- per component accessibility documentation
- system to track/monitor turnaround time on a11y issues

#### Deferred goals
- TBD

#### Squad
- @vpicone (lead), @jnm2377 

#### Primary goals
- Native, client side search (theme)
- Improved table component (theme)
- Vertical rythem/spacing normalization (theme)
- No Vimeo video?

#### Stretch goals
- Gated/protected paths (need design/ux)
- Enhanced Image Gallery [#237](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/237)

#### Deferred goals
- Alternative data source

#### Squad
- @janchild (lead), @jeanservaas (lead) @alisonjoseph, @aagonzales, @connor-leech, @laurenmrice,  @shixiedesign, @designertyler, @jillianhowarth

#### Primary goals

**Content:**
- Content website content audit and strategy (Jan)
-- navigation explorations
-- design systems high-level audits of content covered and content approaches
-- write up the plan
- Support audit
-- create data table of support questions and answers
-- look for trends and identify areas requiring future work
-- identify areas where existing content in answers can be re-used to supplement existing guidance
- Charts page content support (Connor) https://github.com/carbon-design-system/carbon-website/issues/346
- ~Axure tool page up on site (Connor)~

**Patterns:**
- Triage Patterns by quality and importance (Tyler, Jan, Jeannie) https://github.com/carbon-design-system/carbon-website/issues/189 
- Patterns status on Overview page (cupcake with no icing version) (Connor) https://github.com/carbon-design-system/carbon-website/issues/344
- Patterns contribution guidance enhancements plus MDX template for contribution content (Connor and Jan) https://github.com/carbon-design-system/carbon-website/issues/345
- Cloud Integrations Patterns up on site https://github.com/carbon-design-system/carbon-website/issues/87 (Connor) 

**Layout:**
- Layout page code tab; reorganize and skin Josh's grid demo and incorporate layout guidance  (Jeannie, dev resource TBD)

**Components:**
- Explore theme / variant switcher component display window (Anna)
- Comparative component usage guidance audits (Jillian)
-- create a template for component guidance
-- map current content against template to find shortcomings

**Charts:**
- Charts pages scope https://github.com/carbon-design-system/carbon-website/issues/208 
- Charts pages work tracking https://github.com/carbon-design-system/carbon-website/issues/239

#### Stretch goals
- Replace CarbonDocs with mardkown/mdx
- Elements docs on website
- Sass docs on website
- MVP of integrated component page using Jillian's template (Anna)
- Wires and prototyping tertiary / on-page nav for Carbon site to better accommodate contribution vs. placing everything in 'Experimental' (Jan and Scott)

#### Deferred goals
- Use react instead of Vanilla in code examples
- Production guidelines to accompany mdx guidance

#### Squad
-  @shixiedesign (lead), @aagonzales, @laurenmrice 

#### Primary goals
- shipping color palette V2 (Shixie) See https://github.com/carbon-design-system/carbon/issues/3904 for details
- IDL kit
  - Completion / clean-up of any bugs from plugin (Lauren)
  - Add pictograms when ready from dev (Lauren)

- Carbon kit get library swap from the new IDL and library kits (Lauren leads, Anna support)(Jillian to learn structure of kits)

#### Stretch goals
- TBD

#### Deferred goals
- TBD

#### Squad
-  @laurenmrice (lead), @asudoh 

#### Primary goals
- Feature enhancements (Lauren leads)
  - Determine priority

#### Stretch goals
  - Spec'ing

#### Deferred goals
- TBD

**Comment by joshblack** [comment]
Do we not have any designers on theming @chrisconnors-ibm @shinytoyrobots ?

**Comment by shixiedesign** [comment]
And we need a developer on website! Someone help me put Charts on pages please 🙏 @chrisconnors-ibm @shinytoyrobots

**Comment by alisonjoseph** [comment]
I'm on website this cycle @shixiedesign!
