### ISSUE TITLE
Notification: red needs white icon

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#3886]
@jeanservaas 

![EE24F732-0475-44C5-BA28-70B307E0BAFF](https://user-images.githubusercontent.com/32881239/64089940-912b0100-cd16-11e9-9947-7441dfb76492.jpeg)

**Comment by mjabbink** [comment]
Green needs to be black I think too?

**Comment by mjabbink** [comment]
And the usage page need to be updated

**Comment by jeanservaas** [comment]
These issues at least partially cover what you're talking about here I think. Just making sure there's not overlap.

https://github.com/carbon-design-system/carbon/issues/3452

https://github.com/carbon-design-system/carbon/issues/2926
