### ISSUE TITLE
TooltipIcon maxwidth

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3887]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

The tooltip width is not enough for the text inside (aria-label).

tried setting the maxwidth to none but it didn't help:

> .bx--tooltip__label {
  max-width: none;
}

**Comment by asudoh** [comment]
Hi 👋 if you go to https://the-carbon-components.netlify.com/component/tooltip--icon.html, right-click on one of the tooltip trigger icons and select Inspect Element, select the parent `<button>`, click on `:hov` icon, check off `:hover`, and hover over some of the DOM nodes inside `<button>`, you'll see that `<span class="bx--assistive-text">` is the tooltip body. If you keep inspecting the style there, you'll see [`.bx--tooltip__trigger.bx--tooltip--left .bx--assistive-text`, etc. selectors](https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/components/src/globals/scss/_tooltip.scss#L89) dictate the style.

**Comment by zbeedatm** [comment]
I can see the bx-assistive-text in ::after part:

![image](https://user-images.githubusercontent.com/26740851/64152588-ab0f3580-ce35-11e9-9e68-4492f22e2f90.png)

but setting the max-width for it didn't help as well

**Comment by asudoh** [comment]
Probably you want to provide your reduced case?

**Comment by zbeedatm** [comment]
pls check this sandbox:

https://codesandbox.io/s/fragrant-morning-267l5

**Comment by asudoh** [comment]
OK if you select the (pseudo) element in question and go to Computed tab, you can see `width` is equal to `max-width`. If you hover-over the `width`, and click on the right-arrow icon (with circle), you'll see the style rule dictating `width`. If you uncheck all the rules setting `width` there and change `max-width`, you'll get your `max-width` in effect. Hope this helps!

**Comment by zbeedatm** [comment]
Hi asudoh, sorry but still couldn't fix this issue:

![image](https://user-images.githubusercontent.com/26740851/69867115-97e1f980-12ae-11ea-8ae4-4581f8c5a3e0.png)

As you can see the text in white is overlapping over the project component, but the black background is still inside the project component border.

I tried doing:

`.bx--assistive-text {
  max-width: none;
  width: 100%
}`

**Comment by asudoh** [comment]
Probably you wanted a specific width (or `width:auto`) rather than `100%`?

**Comment by zbeedatm** [comment]
I had tried all of that already, tried all compenations... but didn't help!

Tried as well using:  `position: relative;` in Project component div and `position:absolute;` in bx--assistive-text

**Note: The problem is when there is a long word (with no spaces)**

**Comment by asudoh** [comment]
OK do you want to go to https://codesandbox.io/s/fragrant-morning-267l5, right-click the tooltip trigger button and select Inspect, right-click on the parent `<button>` and select Force state - `:hover`, select `<span class="bx--assistive-text" id="icon-tooltip-20">` and add `max-width: none; width: 640px` to `element.style` section?

**Comment by zbeedatm** [comment]
It's there already. You can look for "bx--assistive-text" in App.css
