### ISSUE TITLE
Change Tooltip color

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3888]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
How to change A Tooltip color?

![image](https://user-images.githubusercontent.com/26740851/64106267-82793400-cd80-11e9-8e82-2c2999e562a0.png)

tried the following, but it's not taking affect:

> .bx--tooltip__trigger .White path {
  fill: white;
}

## Relevant information
Sandbox: https://codesandbox.io/s/reverent-firefly-pyc03

**Comment by asudoh** [comment]
Hi 👋 you need a style that overrides the one [here](https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/components/src/components/tooltip/_tooltip.scss#L326-L328). BTW if you put that component in dark theme, the color will be changed automatically. You can see that at https://the-carbon-components.netlify.com/?nav=tooltip where you can see the UI to change the theme at the top right.

**Comment by zbeedatm** [comment]
this works:

> .bx--tooltip__trigger svg {
  fill: white;
}

thanks
