### ISSUE TITLE
 Should Interactive tooltips support hover behavior

### ISSUE THREAD

**Issue by xinlihai** [carbon-design-system/carbon#3893]
### Summary
right now i can just use interactive tooltip which support click to show some rich text
but when i want to hover and show these things i can't find a solution.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. Rich interactive content being handled with click-only interactive tooltip is what our design dictates, but our designers are open for something like bold text, etc. in definition/icon tooltips. Please see #3840 for more details.

**Comment by xinlihai** [comment]
@asudoh Thanks, but this can be used only in react not vue, can carbon-component-vue definition tooltip add this feature?

**Comment by asudoh** [comment]
For Vue enhancements, please go to https://github.com/carbon-design-system/carbon-components-vue. Thanks!
