### ISSUE TITLE
Contribution: NPS

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#3895]
### Summary

We needed a new component to create those circular elements we use in our feedback form. We call them "Digit Bubbles":
![digit bubble](https://user-images.githubusercontent.com/38980986/64163743-1b23b880-ce42-11e9-9af7-93f17e8a4b4a.jpg)

## Explain the rationale
Since we built this as a React component we'd be more than happy to contribute these back to Carbon as we couldn't find anything similar.

## Detail the intended behavior
The component itself displays a number in the middle of a circle. When clicked, it becomes blue. When clicked again, it gets deselected.

## Clarify whether it’s a variation of an existing component, or a new asset
It's a new asset

## Mockups

This is how they look like embedded into a feedback form example
![feedback form](https://user-images.githubusercontent.com/38980986/64163778-2971d480-ce42-11e9-8357-e6fc6adfd2f2.jpg)

### Justification

It's useful for teams which need a component like this, so they save time and won't have to build it on their own..

## Question

Would this be interesting for the Carbon team? If so, what are the steps required to contribute?

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if the team has an interested in this as a core component, or as a community-level component, or something else (e.g. BU-level).

**Comment by ghost** [comment]
@asudoh That link gives me a 404

**Comment by aagonzales** [comment]
I don't really see just the bubbles being added as a component, but I could see the whole pattern being contributed for a NPS type of component.

**Comment by ghost** [comment]
Think it would be no problem to contribute that as a component. What would be the steps to get this started in case you're interested?

**Comment by aagonzales** [comment]
Check out our contribution guidelines, but the next step would be flesh out the designs. Show and spec all the states of the component. 
https://www.carbondesignsystem.com/contributions/component/

**Comment by laurenmrice** [comment]
not stale

**Comment by rebecca-m-l** [comment]
Specs attached
[Feedback.form.-.specs.pdf](https://github.com/carbon-design-system/carbon/files/4045143/Feedback.form.-.specs.pdf)

**Comment by ghost** [comment]
@aagonzales What are your thoughts on the specs?
See https://github.com/carbon-design-system/carbon/issues/3895#issuecomment-542160189

**Comment by aagonzales** [comment]
The only thing the spec is missing is specs around padding/spacing of the objects.

**Comment by rebecca-m-l** [comment]
![69358146-49b17280-0c7e-11ea-9b9f-5a3061f8a000](https://user-images.githubusercontent.com/56588740/72146416-4a1fdd00-3394-11ea-933d-5c472e7f974a.png)

**Comment by ghost** [comment]
@aagonzales Is the updated spec sufficient now?

**Comment by designertyler** [comment]
Thank you for the proposal and specs. We reviewed this as a team and agreed that it is too specific to this one use case to add and support in the core component library.
