### ISSUE TITLE
[Skeleton states] several enhancements

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3897]
**Problem 1**: Both visual and animations are not designed specifically for V10. They are designed in V9 and only got color update since V10 release. The visual design and animation should be revisited to reflect Light and space modal of the new IBM design language look and feel. 

**Problem 2**: Skeleton states currently do not match the structure and sizing of the components, creating jumps in user's page layouts when the components load in. 

**Problem 3**: Add support for `prefers-reduced-motion media query`
https://github.com/carbon-design-system/carbon/issues/2440

**Comment by tw15egan** [comment]
#3905 will take care of #3

**Comment by tw15egan** [comment]
I believe these issues have all been resolved, happy to reopen if not the case
