### ISSUE TITLE
Triage security team's user feedback

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3898]
I met with Cameron Calder, Jimmy Dyer, and Jen Downs to check-in on how is Carbon working for **IBM Security**. There are a lot of gaps still, see below. I'm currently in the process of creating individual issues to capture the specific work to be done here. 

### Skeleton states needs work - https://github.com/carbon-design-system/carbon/issues/3897
- inconsistency of how it is implemented in components

### Some components cannot support large amount of data
- eg. combo box 
- need design guidance on how to visually handle large data loading (view more link? Pagination?)
- having a loading state for such components 

### UI Content writing
- guidance on how to write labels/titles on the components FYI @janchild 

### When & how to use containers (layout)
- gutter spacing usage, is there a point of view? 
- grouping of one object, 1px
- when to use 16px? 
- overview, eg. Thread intelligence report, 32px

### Grid guidance on how to implement hang/no-hang 
- it is a unique concept unfamiliar to back-end developers, often remote
- FYI @joshblack I suspect we already have this content based on our grid package. Is there more general guidance that would apply to more frameworks? 

### Accordion 
- Position of the chevron has always been on the left in Security products. This is a discrepancy from Carbon main branch.
- Need a knob (currently have to be a custom override)
- Document guidance on when to use which variant

### Exporting react stories - #2570
- consistency carbon react stories 
- make security's preview updated, linked to Carbon
- Jen told me you are already aware @joshblack 

### Fluid buttons
- Security team will be contributing

### Search bar
- Would like a version that include primary action, search icon on the left
- intent is to take user to a new page to display search results. This requires a more deliberate "search" action where a primary button is more important. 

### Big numbers 
- type scale needed @jeanservaas 
- how to handle ratio, percentage (should it be superscript) 
- delta (up by 6%, down 5 points)

### Loading 
- loading component need a "queued" state

# How do you decide when to come to Carbon for help

I asked them when do they come to Carbon team vs doing custom overrides, below is the answer:

- Check if something is available first. They do not ask for features any more because it just takes way too long to get anything done. Often they are under the deadline of having to ship in 2 weeks.
- Would get design feedabck if possible, but **Wake is not useful, we get the wrong type of feedback**
- People are afraid to use Wake
- 2 year old post still getting comments "why is this using old header, etc" even though the description clearly states this is a wireframe.

**Comment by joshblack** [comment]
@shixiedesign we do have a hang example in our docs if we want to point them there, I think we're going to see a shift though based on what @jeanservaas has been working on / thinking through so might help to wait? Let me know though, always happy to help 👍

**Comment by shixiedesign** [comment]
Oh yes we should definitely waiting for Jeannie's pass on this guidance. I think once that is up, I will bring it back to them and see if that's sufficient.
