### ISSUE TITLE
DataTable.TableToolbarSearch should support default value

### ISSUE THREAD

**Issue by dpalmier** [carbon-design-system/carbon#3900]
### Summary

The DataTable.TableToolbarSearch should be enhanced to support a default value.  Ideally, it should be exposed as the defaultValue property, so that it is consistent with the defaultValue property of the Search component.

I am requesting both design and development.

### Justification

The Cloud Identity product, which consumes Carbon V10, supports bookmarking pages that include search criteria.  The search criteria is extracted from the browser location, but it cannot be used to populate an initial value in the DataTable.TableToolbarSearch.  This produces a less than ideal user experience, as it is not obvious to the user that initial search criteria has been applied.

### Desired UX and success metrics

The user should see the default value in the DataTable.TableToolbarSearch search field.

### "Must have" functionality

The DataTable.TableToolbarSearch should support a property that specifies the default value that is displayed in the search field.

### Specific timeline issues / requests

Ideally, this enhancement should be available by September 30, 2019, as that is the date when the Cloud Identity product is scheduled to deliver UI to customers that is dependent on this enhancement.  If that is not achievable, it would be as soon as possible after that date, so as to minimize the time during which the less-than-ideal user experience is exposed to Cloud Identity customers.

### Available extra resources

No resources are available to assist this effort.

**Comment by dpalmier** [comment]
Is anyone on the Carbon team looking into implementing this enhancement request?

**Comment by dpalmier** [comment]
Can someone update this issue to indicate if/when something will be done about it?

**Comment by asudoh** [comment]
A PR that implements the requested feature will be welcome - Thanks!
