### ISSUE TITLE
[InlineLoading]: If I try and use an inline loading with a TooltipDefinition I get a console error

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#3901]
This is in the carbon-components-react project implementation of InlineLoading.  Can we use a <div> instead of a <p> to render the InlineLoading message?

To reproduce, simply use InlineLoading and a TooltipDefinition together

backend.js:1 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by TooltipDefinition)
    in TooltipDefinition (created by SummaryDashboardCard)
    in p (created by InlineLoading)
    in div (created by InlineLoading)
    in InlineLoading (created by SummaryDashboardCard)
    in div (created by Summary

```
 <InlineLoading
              description={
                <TooltipDefinition
                  className={tooltipStyles.tooltip}
                  tooltipText={formatMessage(messages.preparingTooltip)}>
                  {formatMessage(messages.preparing)}
                </TooltipDefinition>
              }
            />
```

**Comment by asudoh** [comment]
@carbon-design-system/design Is putting definition tooltip into the status text of inline loading OK from design perspective...? Thanks!

**Comment by aagonzales** [comment]
Do you have an image/design of what you're trying to do? Just so we're clear

**Comment by scottdickerson** [comment]
yeah I do: 

![image](https://user-images.githubusercontent.com/6663002/64559099-1ca22480-d30b-11e9-90b1-1fc7248159b7.png)

**Comment by scottdickerson** [comment]
here's the rendered html causing the issue

![image](https://user-images.githubusercontent.com/6663002/64559709-8969ee80-d30c-11e9-9cb1-f66642e867d3.png)

**Comment by aagonzales** [comment]
Yup, we think that's acceptable ux!
