### ISSUE TITLE
Link component is using incorrect color token

### ISSUE THREAD

**Issue by mattalco** [carbon-design-system/carbon#3902]
## What package(s) are you using?

- [ x] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The link component, according to the documentation here (https://www.carbondesignsystem.com/components/link/style/) should be using `$interactive-01` instead of `$link-01` as its text color.

> Is this issue related to a specific component?

`Link` component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see overrides to `$interactive-01` picked up in the `Link` component.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.5.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Marketplace

## Steps to reproduce the issue

Use http://themes.carbondesignsystem.com/?nav=link and change `$interactive-01` to any custom color. This custom color is not reflected in the `Link` element because it's using the wrong token.

## Additional information

It looks like there are a few discrepancies here comparing the code to the docs.
 
<img width="728" alt="Screen Shot 2019-09-04 at 3 24 06 PM" src="https://user-images.githubusercontent.com/13972013/64284743-497bc380-cf28-11e9-8b84-26147aaf2b11.png">
<img width="899" alt="Screen Shot 2019-09-04 at 3 25 09 PM" src="https://user-images.githubusercontent.com/13972013/64284744-497bc380-cf28-11e9-8f9f-49b9da01525a.png">

**Comment by shixiedesign** [comment]
Ooh good catch. Website's wrong in this case! We created `$link-01` for....links. I will make a PR to correct that.
