### ISSUE TITLE
Class names for type tokens?

### ISSUE THREAD

**Issue by mstudio** [carbon-design-system/carbon#3906]
## What package(s) are you using?
- [x] `carbon-components` "^10.3.1"
- [x] `carbon-components-react`"^7.4.1"

## Summary

Hi there. I'm working on an internal project for IBM (I don't have access to the Slack channels) and I'm loving the tokens which can be used within my scss.

Here's what I'm doing:
```
@import 'carbon-components/scss/globals/scss/vendor/@carbon/type/scss/font-family.scss';
@import 'carbon-components/scss/globals/scss/typography.scss';

p {
   @include type-style('productive-heading-05');
}
```

What I'm wondering is if there are relevant classes that I can apply directly to my markup, e.g.:

```
<p className="productive-heading-05">Text here</p>
```

I know that the above doesn't work, but I'm wondering if there's something similar. 

Thanks in advance!

**Comment by asudoh** [comment]
Hi 👋 your former code will be the preferred approach, for the sake of separation of concern between markup semantics vs. type tokens. We had a discussion wrt whether we should have OOTB style like the former, but where it was completely slipped my mind (sorry).

**Comment by tw15egan** [comment]
Going to close this as resolved, feel free to reopen if you feel your question has not been addressed.
