### ISSUE TITLE
Link component needs underline option

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#3908]
@alisonjoseph @joshblack 
color alone is not enough to identify links. They must have a primary option with underline especially for inline situations. This is a priority item if not already resolved.

**Comment by joshblack** [comment]
@mjabbink I believe the current link component presents a non-color designator on hover/focus

![demo](https://user-images.githubusercontent.com/3901764/64363950-7b982e80-cfd7-11e9-80cc-73b0104cd8ab.gif)

Is the suggestion here that the underline always be visible, especially in body text?

**Comment by mjabbink** [comment]
Yes, we need an option where the underline is always visible for accessibility. Color cannot be an identifier as a link given one may not likely see it so the underline indicated a link. Especially for likes within text. 

We need the current states but we need to add an option with underlines on all the time.

**Comment by joshblack** [comment]
@mjabbink I don't believe it is an accessibility violation as long as a non-color designator is visible on hover/focus and the text color has 3:1 contrast with outside text (when used in body copy), it definitely could be considered a usability problem but I'm not sure what a11y requirement this would hit. If it does violate some requirement, could you link it so we can refer to it in our tests?

**Comment by mjabbink** [comment]
I thought it was. How would a color blind person know to hover on the text if they cannot see any difference between it and the rest of the text? I though @vpicone had dug something up but will double check with him.

**Comment by joshblack** [comment]
I would assume the contrast ratio requirement would help cover that, but let me know if not 👍

**Comment by mjabbink** [comment]
I think we need underline. I was chatting with Bo Campbell regarding this and he recommends underline. Otherwise we need to make sure we have the contrast ration between blue link and text which I’m pretty sure we currently do not.The blue to grey 100 (or black) does not meet contrast ratio.

**Comment by mjabbink** [comment]
@vpicone @jeanservaas We need to get crystal on this but I’m almost certain the contrast ratio between a link (blue 70) and text (grey 100 or black) is not compliant. Meaning we need a solution for inline links which I think is to have the underline visible.
