### ISSUE TITLE
`Tabs` component maintains invalid `selected` state

### ISSUE THREAD

**Issue by pinakidey** [carbon-design-system/carbon#3909]
## Title line template: [Title]: Brief description

`Tabs` component maintains invalid `selected` state (see detailed description for more)

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
```
<Tabs>
    {conditionA && (
        <Tab label={"TabA"}>
            {getTabAContent()}
        </Tab>)}
    <Tab label={"TabB"}>
        {getTabBContent()}
    </Tab>
</Tabs>
```

Say, you have 2 tabs, `TabA`, `TabB`.

if `(conditionA == true)` you show `TabA`. `TabB` is always to be shown.

`Tabs` Component maintain a selected state whose value is the index of the `Tab` inside `Tabs` . Initial `selected` value (default `0`) can be provided to `Tabs` as props (note `props`, we have no control over its `state`).

On PageLoad, say, `conditionA==true` satisfies & both tabs are shown, with `TabA` as the selected-tab. At this point, `Tabs.state.selected = 0`.

Now you click on `TabB`. This makes `Tabs.state.selected = 1`.

You do some operation, under `TabB`, that changes `conditionA` to `false`. (But does not perform a full page reload, which would hamper usability.)
Now, `TabA` gets hidden. However, `Tabs.state.selected = 1` remains unchanged.

At this stage, since the `Tabs` DOM contains only 1 tab, `TabB`, `Index:1` is non-existent.
So, `TabB` contents gets hidden.

> Is this issue related to a specific component?

Yes, `Tabs` & `Tab`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

`TabB` content should **NOT** be hidden. i.e. `Tabs.state.selected` should be `0` (or `maxChildrenCount - 1`). 

> What browser are you working in?

Firefox (70.0b2 (64-bit))

> What version of the Carbon Design System are you using?
```
"carbon-components": "9.81.5",
"carbon-components-react": "6.106.0",
```

## Steps to reproduce the issue

Environment to reproduce on CodeSandbox:
https://codesandbox.io/embed/infallible-raman-fbec8

**Steps:**
1. click "tab 2"
2. click "Click me"
(You'll see, `Content for tab 2` getting `hidden`)

The above is using the latest `carbon-components-react` (v7) with `carbon-components` v10. Would like to have the fix back-ported to v6 as well.

**Comment by asudoh** [comment]
Hi 👋 I don't think the tabs/tab code was written to be able to cope with conditional rendering for a specific tab, unfortunately. One workaround I can imagine is hiding the tab via CSS, instead of clobbering.

**Comment by emyarod** [comment]
closing this issue as a CSS workaround is possible. we may consider this component behavior for upcoming refactors
