### ISSUE TITLE
DataTable with sticky header has reduced width

### ISSUE THREAD

**Issue by gmoehler** [carbon-design-system/carbon#3911]
## Brief description: 
Tables that use the sticky header option have reduced width. I did not investigate what is responsible for this, though.

## What package(s) are you using?
latest

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When using the appropriate styles in Vanilla JS or the new stickyHeader flag in the react component (https://github.com/carbon-design-system/carbon/issues/3875) the width of the table is reduced.

> Is this issue related to a specific component?
DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?
table width should stay the same with or without sticky header

> What browser are you working in?
chrome / firefox

> What version of the Carbon Design System are you using?
latest 

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud SQL Query

## Steps to reproduce the issue

1. Select DataTable in storyboard
2. In Knows turn on the sticky header option
3. The table has a scroll bar, but also a reduced width

**Comment by tw15egan** [comment]
Seems like we are adding a `max-width: 900px` when using sticky header.

https://github.com/carbon-design-system/carbon/blob/f5325f71f27aba48a22bd852bbf1f075e5677c7d/packages/components/src/components/data-table/_data-table-core.scss#L529

@carbon-design-system/design , is there any reason why we have a max-width for sticky header, but not for normal data tables? Should we remove this max-width, or should we add a max-width to the regualr data-table? 

cc @asudoh wondering if you have any background.

**Comment by asudoh** [comment]
CC @jnm2377 who authored the code - Great if you have any background on this. Thanks!

**Comment by aagonzales** [comment]
I don't see any reason for sticky header to have a max-width.

**Comment by aledavila** [comment]
@asudoh hey just found the problem. It is coming from 

https://github.com/carbon-design-system/carbon/blob/25ab3f2286a2ea7a72d727ccfc54fd3fbb285c75/packages/components/src/components/data-table/_mixins.scss#L7-L14

and like TJ said. We then add a max-width. Can you give background on that mixin and can we just remove the one line in `_data-table-core.scss` or this a more complex issue?
