### ISSUE TITLE
Invalid hooks calls in storybook

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#3914]
Storybook is failing both in netlify and locally, probably due to the recent package version bumps?

The [netlify error](https://user-images.githubusercontent.com/8265238/64345246-99549c00-cfb5-11e9-9033-7725cdbc5f62.png) doesn't provide much information but building the storybook locally will return invalid hooks call errors for multiple stories

![image](https://user-images.githubusercontent.com/8265238/64345848-aa51dd00-cfb6-11e9-92ae-c927af788d4c.png)

rolling back the package versions works as a temporary workaround (v5.1.9 seems to be the last known good version for us)

**Comment by joshblack** [comment]
@emyarod I vote we just specify a top-level `resolutions` like:

```json
  "resolutions": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-test-renderer": "^16.9.0"
  },
```
