### ISSUE TITLE
datable compost: Replace straight quotes with apostrophe

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#3920]
https://www.carbondesignsystem.com/components/data-table/code

@alisonjoseph 

see below: "Maureen’s VM Groups..."
<img width="413" alt="Screen Shot 2019-09-05 at 11 34 02 AM" src="https://user-images.githubusercontent.com/32881239/64356628-29540f00-cfd1-11e9-9c8f-efee8dd3bd90.png">

**Comment by joshblack** [comment]
Seems like this conflicts with prettier rules which is what handles text formatting, would cause issues in our codebase and for downstream folks as it would try and format the apostrophe to a straight quote, would we still want to go forward with this?

**Comment by vpicone** [comment]
@joshblack The only reason that string was double quotes was to allow for the dumb quote in the middle without breaking it up. Using the 'smart quote' in the string actually means we can use single quotes to wrap the string (prettier's setting and the format for the rest of the file).
