### ISSUE TITLE
Nested Accordions incorrectly display as open

### ISSUE THREAD

**Issue by jinhei** [carbon-design-system/carbon#3921]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When nesting accordions, inner accordion items are open if the parent is.

> Is this issue related to a specific component?
AccordionItem

## Steps to reproduce the issue

[CodeSandbox](https://codesandbox.io/s/codesandbox-k5q9x)

1.  Create parent accordion with child accordion
2.  Open parent accordion
3.  Try toggling the child accordion. It does not work.

## Additional information

The issue is css-related -- the selectors for active state need to be more specific, so as not to match the child accordion + items.

**Comment by tw15egan** [comment]
I don't think nested Accordions are a [supported pattern](https://github.com/carbon-design-system/carbon/issues/3096#issuecomment-504853577) cc @carbon-design-system/design
