### ISSUE TITLE
Accordion closed items taking up space in parent container

### ISSUE THREAD

**Issue by spgill** [carbon-design-system/carbon#3931]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Using 
`carbon-components @ 10.5.0`
`carbon-components-react @ 7.5.1`

Browser is Chrome 77

Using the `<Accordion />` component, when the child `<AccordionItem />`'s have very tall content (several items with height over 1000px); when all of the accordion rows are closed, even though the content is not visible, it still overflows and takes up space in the parent element and triggers a scrollbar (with the parent's `overflow-y` set to `auto`).

I'm working with this component to include in a 4Q release of IBM Storage Insights.

## Steps to reproduce the issue

1. Create an `<Accordion />` with at least one `<AccordionItem />` containing an element with a height greater than the parent element, and with `overflow-y: auto` on the parent element.
2. Parent element should scroll even with the accordion closed.

## Incomplete solution
I've created a quick fix in my local environment using the following CSS rules. This breaks the opening and closing animations, but it demonstrates what i believe is the cause; that non-active content is only visually obscured, while the geometry is left intact.

```css
.bx--accordion__item .bx--accordion__content {
  display: none;
}
.bx--accordion__item.bx--accordion__item--active .bx--accordion__content {
  display: block;
}
```

## Additional information

Screenshot of the accordion in question in my dev environment. The screenshot encompasses the entire containing element. Note the scrollbar on the right.
<img width="899" alt="Screen Shot 2019-09-06 at 14 52 29" src="https://user-images.githubusercontent.com/4942920/64457655-c9d12e80-d0b8-11e9-8ea6-1140ee38b7f5.png">

**Comment by asudoh** [comment]
Hi 👋 I see a style rule to prevent the symptom you described from happening: https://github.com/carbon-design-system/carbon/blob/v10.6.0/packages/components/src/components/accordion/_accordion.scss#L102

That said, I guess you have a style rule that overrides it or makes it non-effective? If you cannot figure out you may want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox to get more help.

**Comment by joshblack** [comment]
Hi @spgill! 👋 Thanks so much for taking the time to make an issue! Going to close this for now as it's been a couple of months, feel free to comment if there are any steps you could offer to help us reproduce!

**Comment by kaplanmichael** [comment]
@asudoh Just a heads-up that this issue is occurring for me in @carbon/react: ^1.46.1.  I had to set `overflow:hidden` on `.cds--accordion__wrapper` in order to resolve the issue.

**Comment by tw15egan** [comment]
Was a recent bug that was reintroduced but was fixed via https://github.com/carbon-design-system/carbon/pull/15423. Should be working properly on the latest version, but let us know if that is not the case
