### ISSUE TITLE
Icon-only button doesn't align with others when they are next to each other

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3938]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When an icon-only button is next to a standard button with text I'd expect the tops of the buttons to be aligned

> Is this issue related to a specific component?

Button

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The tops of the buttons align

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.6.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. have button with text and icon-only button next to each other

> Please create a reduced test case in CodeSandbox

https://codepen.io/elizabethsjudd/pen/qBWprrm

## Additional information

<img width="438" alt="Screen Shot 2019-09-09 at 10 19 17 AM" src="https://user-images.githubusercontent.com/1275779/64538991-a5a96380-d2eb-11e9-9d87-5a83944d883f.png">

**Comment by emyarod** [comment]
does setting `vertical-align` to your needs resolve this issue?

**Comment by elizabethsjudd** [comment]
@emyarod verified that setting `vertical-align` top does resolve this (code pen has been updated). Can it be added to Carbon so individual offerings don't have to apply this change manually.

**Comment by emyarod** [comment]
@elizabethsjudd just want to research further into the issue and see if there are any other solutions first. for example would making the parent a flex container also work?

**Comment by elizabethsjudd** [comment]
@emyarod I updated the code-pen to show both solutions.

**Comment by emyarod** [comment]
@elizabethsjudd I'm leaning towards this being an app level fix. unless I'm mistaken, this seems to be default behavior for buttons right?

**Comment by elizabethsjudd** [comment]
@emyarod it just seems weird that ONLY icon-only button would have a different alignment than the others. If it was truly default behavior they would all be aligned but there is obviously something in the styling that makes this not true.

**Comment by emyarod** [comment]
@elizabethsjudd what I mean is with the same markup and all the styles (except for the `height` rule) removed, the same behavior would appear

**Comment by elizabethsjudd** [comment]
I think I figured out what's going on: browser default behavior is to align on baseline but the text in icon-only is positioned absolute and smaller making the misalignment.  I still don't understand why this couldn't be fixed in Carbon since buttons are expected to be the same height has others in line with it because now all offerings that have text buttons next to icon-only buttons would have to add a fix but if it's opposed that much we can fix it in our PAL.

**Comment by emyarod** [comment]
right that's what I was referring to when I mentioned default behavior and suggested the `vertical-align` fix earlier as a workaround

for more clarity: even though this is a quick one line fix we want to make sure we're fully aware of all the effects resulting from adding this rule to the base styles. but in the meantime the fix I presented could be implemented on the app side so it's not a hard blocker

in any case I'll be adding that rule in a PR
