### ISSUE TITLE
Vertical scroll disappears after opening a Modal when updating to newer carbon-components version

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3945]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

After updating to newer version of carbon-components I started facing a weird symptom when opening a modal (from any component - it doesn't matter).
The vertical scroll of the browser is disabled after opening a modal, and when closing the modal it doesn't come back and I can't navigate in the screen up/down!!!

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome / Firefox

> What version of the Carbon Design System are you using?

10.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/fragrant-morning-267l5

1.  From the menue of any Project component choose action that opens a modal
2.  Choose "Duplicate" for example
3.  The Modal window is opened
4.  The vertical scroll disappears!
5. Close the Modal window, the scroll is still gone

## Additional information

You can compare between package.json.old and the new package.json that I'm using

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

**Comment by zbeedatm** [comment]
Kindly update regard this issue... it's critical

**Comment by asudoh** [comment]
The code seen in CodeSandbox seems to clobber the modal when it's closed, which deprives our modal code of cleaning-up `bx--body--with-modal-open` class when it's closed. `bx--body--with-modal-open` disables `<body>`'s `overflow` style to address #3187.

That said, a couple of choices I can think of:

1. Avoid clobbering modal when it's closed (You can still clobber its content, though)
2. Cleaning-up `bx--body--with-modal-open` class manually

**Comment by a-roberts** [comment]
Seeing this as well, how do we prevent "clobbering" or, how would we clean the class manually? Can you provide an example please @asudoh?

**Comment by asudoh** [comment]
In `Project.js` in the CodeSandbox link in the issue description here, we see code doing conditional rendering of `<ComposedModal>` like:

```javascript
{ this.state.openDuplicateProject ?
  <ComposedModal ...>
    ...
  </ComposedModal>
: null}
```

Instead, they should render `<ComposedModal>` always, like:

```javascript
<ComposedModal open={this.state.openDuplicateProject} ...>
  ...
</ComposedModal>
```
