### ISSUE TITLE
The password input can cause scroll bars to appear in a modal dialog

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#3952]
## What package(s) are you using?

@carbon/vue but it also affects core carbon as per example.

- [x] `carbon-components`
- [ ] `carbon-components-react`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

When the password input is used as the last component in a modal it adds a scroll bar. Note: mac users may not see this, depending on system settings.

It is the tooltip that causes this.

> Is this issue related to a specific component?

text-input for passwords used in a modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome on Mac

> What version of the Carbon Design System are you using?
10.6.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A

## Steps to reproduce the issue

1. Show a modal dialog with a password input field
2. Note the scroll bars

https://codepen.io/lee-chase/pen/qBWYRdK

## Additional information
![image](https://user-images.githubusercontent.com/15086604/64701344-86076c00-d4a0-11e9-9e76-3b7687e6f30d.png)

**Comment by asudoh** [comment]
@emyarod Do you this the issue is specific to password input instead of text input in general...?

**Comment by lee-chase** [comment]
@asudoh It will be any component where a popup/dropdown is in the same stacking context. E.g. an expanded dropdown.

Not sure how to solve other than move all popup/dropdowns out to the root level.

**Comment by emyarod** [comment]
I believe this is related to the overflow rules on `.bx--modal-content`, possibly related to this ticket https://github.com/carbon-design-system/carbon/issues/3841 ?

as a temp workaround I believe you can specify the direction and alignment of the tooltips, but for a dropdown this may need a deeper look

**Comment by emyarod** [comment]
issue appears to be resolved, can be tested on the provided codepen which uses the latest version of Carbon
