### ISSUE TITLE
Datepicker is off by one day if using the Y-m-d format

### ISSUE THREAD

**Issue by ericmartens** [carbon-design-system/carbon#396]
## Detailed description
If I set the data-date-format on the datepicker component to "Y-m-d" then the date selected is always one day off. For example, picking October 21, 2017 from the calendar popup will always set the text in the input to 2017-10-20. HTML here:

`<input type="text" id="date-picker-3" class="bx--date-picker__input" placeholder="yyyy-mm-dd"
        data-date-picker-input data-date-format="Y-m-d"/>`

Reproduced on Chrome and Firefox.

**Comment by tw15egan** [comment]
Hmm this is strange. I'm also able to reproduce this issue. I'm going to see if this is an issue on our end, or if it is an issue with `flatpickr`. As a workaround, `Y/m/d` seems to work correctly 🤷‍♂️
