### ISSUE TITLE
cv-data-table overflow menu clicking jumps the whole table up

### ISSUE THREAD

**Issue by naftali-ibm** [carbon-design-system/carbon#3963]
## What package(s) are you using?
2.10.0

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
cv-data-table (which is bigger than the screen and need to scroll down to see lower rows) and when overflow-menu clicked the whole table “jumped” up to the first row.
> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
all
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
open page with a table larger than the screen
2. Step two
scroll down 
3. Step three
press overflow menu - the table jump to the first line

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 is this issue against Carbon's Vue variant? If so, could you enter an issue at https://github.com/carbon-design-system/carbon-components-vue/issues? Thanks!

**Comment by naftali-ibm** [comment]
done
