### ISSUE TITLE
OverflowMenu disabled property is not working!!

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3964]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

setting the disabled property of OverflowMenu but it's not taking affect!!!

## Relevant information

https://codesandbox.io/s/fragrant-morning-267l5

**Comment by timrbula** [comment]
@zbeedatm The disabled prop is for the `OverflowMenuItem` component, not the `OverflowMenu` itself. [OverflowMenuItem](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/OverflowMenuItem/OverflowMenuItem.js) vs [OverflowMenu](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/OverflowMenu/OverflowMenu.js)

**Comment by zbeedatm** [comment]
This is what I did in the meantime. But don't you think that it should have?! why to do it for all items if I want to disable it at first place... sounds redundant.

Thanks anyway
