### ISSUE TITLE
Carbon vanilla's Overflow menu breaks in IE 11

### ISSUE THREAD

**Issue by akash-srivastava-ibm** [carbon-design-system/carbon#3978]
[overflow.zip](https://github.com/carbon-design-system/carbon/files/3608754/overflow.zip)
Hi,

We are using carbon vanilla - carbon-components.js to create UI components. We have used the overflow menu component in our UI. And it doesn't open when the web UI is opened in IE 11.

I am attaching a zip for reference. It includes the same overflow component from the https://www.carbondesignsystem.com website. It works fine in other browsers except IE 11.

**Comment by tw15egan** [comment]
Hi, I'm wondering if you are including the IE11 polyfills mentioned here:
https://www.carbondesignsystem.com/get-started/develop/vanilla/#polyfills-for-older-browsers

This should resolve the issue, but feel free to reopen if you are still experiencing problems.

**Comment by shanuakash** [comment]
Apologies for not closing this earlier. Yes, the polyfills worked for me.
