### ISSUE TITLE
Add support for different base elements in TooltipDefinition

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#3985]
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

currently we hard code `button`s as the trigger element for `<TooltipDefinition>`s, but we should allow for different base elements for greater flexibility when defining the trigger element

refs #3840

**Comment by aledavila** [comment]
Can I close this due to the outcome of the previous conversation in the PR ? @emyarod

**Comment by tw15egan** [comment]
Closing, but feel free to reopen
