### ISSUE TITLE
Design Needed to signify 'selected' item (current value) in List Box and other controls.

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#3988]
### Summary

List box currently uses focus ring to indicate current value. need a design to indicate current value that doesn't collide with focus. see https://github.com/carbon-design-system/carbon/pull/3124 for context.

**Comment by laurenmrice** [comment]
### Design spec: ###

**Hover state:**
Add a 2px border on top of the hover that is the same color (`hover-ui`) so the border will appear in high contrast mode but visually blend in with the hover color in normal.

**Selected state:**
Add a checkmark icon inline with the selected row. The checkmark icon should be color `icon-01`. Make sure the selected row is color `selected-ui`. Ref open issue for dropdown enhancement: #3531 

![Artboard](https://user-images.githubusercontent.com/43969356/65172471-996f8580-da12-11e9-9b69-22ed35300f26.png)

**Comment by laurenmrice** [comment]
NOT stale

**Comment by asudoh** [comment]
Refs #4374
