### ISSUE TITLE
Is FileUploaderDropContainer released already?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3992]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I tried using the FileUploaderDropContainer after upgrading to :
"carbon-components": "^10.4.1",
    "carbon-components-react": "^7.4.1",

But couldn't find it there. Is it in a formal release already?

**Comment by asudoh** [comment]
@emyarod I think it's in `10.6.x`, is it correct...? Thanks!

**Comment by emyarod** [comment]
@asudoh I think it has yet to be released

**Comment by asudoh** [comment]
OK thanks @emyarod! @zbeedatm Please stay tuned for our upcoming release... Thanks!

**Comment by zbeedatm** [comment]
Can you please estimate when it will happen? We have a release soon, and I need to know if It will be till then.

Thanks

**Comment by asudoh** [comment]
@zbeedatm We have monthly-ish release schedule. Stay tuned!

**Comment by zbeedatm** [comment]
Kindly reminder. I tried again yesterday but it wasn't there yet.

**Comment by emyarod** [comment]
were you on `v7.7.0` when you tried? it should be in that release

**Comment by zbeedatm** [comment]
was on:  "carbon-components-react": "^7.6.4",
ran npm update again and now I have 7.7.0

But it's not clear from storybook how to use it!
I tried:

> <FileUploaderDropContainer
                                                        labelText="Drag and drop files here or click to upload"
                                                        name=""
                                                        multiple
                                                        accept={['.dfproj']}
                                                        disabled={false}
                                                        role=""
                                                        tabIndex={0}
                                                        onChange={e => this.handleFileChanged(e)}
                                                    />

and this what I got:
![image](https://user-images.githubusercontent.com/26740851/66576902-2a083400-eb81-11e9-85a3-7d1b0a70cb97.png)

without border.. and when selecting a file, it wasn't shown in the list!
What I'm I missing?

**Comment by emyarod** [comment]
my guess is you are only importing the component and not adding any logic for sending requests although I'm not sure with the limited information you've provided

you can refer to the storybook [example application](http://react.carbondesignsystem.com/?path=/story/fileuploader--drag-and-drop-upload-container-example-application) ([source](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/FileUploader/stories/drop-container.js)) for more info on how to use the component (moved it into a codesandbox here https://codesandbox.io/s/github/emyarod/carbon/tree/dnd-uploader-codesandbox/packages/react/examples/drag-and-drop-file-uploader)

**Comment by zbeedatm** [comment]
Thanks emyarod. I tried using the the sandox that you provided, but It still doesn't look as it was expected... can you please take a look at my sandbox:

https://codesandbox.io/s/brave-voice-bdrx0
