### ISSUE TITLE
[Type package] Remove italics form helper text style

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3999]
> I removed the "italic" mention in the spec, but looks like I was unable to remove the italic in the example. Welp!

This is pulling styles directly from the type package. Has it been updated there?

_Originally posted by @alisonjoseph in https://github.com/carbon-design-system/carbon-website/pull/315#issuecomment-531839381_

# Remove italics form helper text style

After the new palette update, helper text should use color token `$text-05` and not be italic. 

![image](https://user-images.githubusercontent.com/15144993/64981467-b9bc0a80-d881-11e9-80b6-7f7df900aa35.png)

**Comment by alisonjoseph** [comment]
FYI our type tokens don't include color currently, I'll remove the italic. I did a search inside the code so I could see if I needed to update the color token and it doesn't appear we are even using that type-token anywhere.
