### ISSUE TITLE
Ensure CSS custom properties are correctly declared

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#4005]
Refs #4001 #4002

As we are looking to add support for CSS Custom Properties in our codebase, we would like to ensure that they are being correctly used (given the syntax outlined in #4001 and #4002)

```diff
.#{$prefix}--component-name {
-  color: $token-01;
+  color: var(--token-01, $token-01);
}
```

We can achieve this via linter rules, CI tests, or other options which require further exploration

**Comment by asudoh** [comment]
One thought; In addition to automating the addition of fallback value in Sass like #4001, can we automate generating the after-version of this issue from the before-version?

**Comment by joshblack** [comment]
Do we need this anymore based on our new direction @emyarod? Documenting this over in: https://github.com/carbon-design-system/carbon/issues/4033

**Comment by emyarod** [comment]
yeah we can close this based on the revised requirements
