### ISSUE TITLE
ibm-tooltip-icon component hidden by select component

### ISSUE THREAD

**Issue by vvsby** [carbon-design-system/carbon#4009]
## Detailed description

> Describe in detail the issue you're having.

When I try to use **ibm-tooltip-icon** component as tooltip, I expect to see it under all other elements. But at this moment it has less priority than **ibm-select** component.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

ibm-tooltip-icon

> What did you expect to happen? What happened instead? What would you like to see changed?

Change z-index

> What browser are you working in?

Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.5.1",
    "carbon-components-angular": "^3.15.3",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
no
## Steps to reproduce the issue

1) Create simple table with 2 or more rows.
2) Add some ibm-select components for all rows and columns.
3) For one or more ibm-select add tooltip bigger than select element. 
```
 <ibm-tooltip-icon [content]="specificationRow.lessGreater" class="dropdown__middle">
      <div class="dropdown__middle">
         <ibm-select placeholder="Select" (selected)="tableChanged()" [id]="'lessGreater'+i"                                [(ngModel)]="specificationRow.lessGreater">
              <option   *ngFor="let factorValue of factorValues; index as factorValueIndex"     [value]="factorValue">
                                    {{factorValue}}
                </option>
            </ibm-select>
       </div>
 </ibm-tooltip-icon>
```
 4) Try to see tooltip text in first row (not last).

## Additional information
Was redirected to you from angular-components team: https://github.com/IBM/carbon-components-angular/issues/743
![image](https://user-images.githubusercontent.com/25610620/64697440-87896200-d4a9-11e9-9c94-665c22fe498b.png)

**Comment by asudoh** [comment]
Hi 👋 would you want to enter an issue at https://github.com/IBM/carbon-components-angular instead of this repo? Thanks!

**Comment by asudoh** [comment]
Quickly tried putting the markup of Carbon select component next to the markup of Carbon tooltip in vanilla dev env and didn't reproduce the problem. @cal-smith Do you have a template to create a reduced case of Carbon Angular library...? Please let me know if you can reproduce the problem. Thanks!

**Comment by cal-smith** [comment]
I don't ... @vvsby, would you be able to create a stackblitz/codesandbox to replicate the issue? 

Carbon Angular doesn't add any styles to either of those components, so I'm not sure where the issue is coming from.

**Comment by asudoh** [comment]
You are right @cal-smith I suspect the issue is not specific to the Angular variant. As you brought up, having a reduced case would be the best way to see what's going on.

**Comment by vvsby** [comment]
Please look at difference between top and bottom placement. Top placement works correct. Bottom - does not.

**Comment by asudoh** [comment]
Hi 👋 given we don't have a way to reproduce the problem it's hard to identify where the problem is. That's why we think having a reduced case is the best way you'd get help. In case it's what you are suspecting, we don't have difference in z-order for top placement vs. bottom placement, as far as I can see in the code.

**Comment by joshblack** [comment]
Hi there! :wave: Going to close this out due to inactivity. If you could provide steps to reproduce with a codesandbox then we can re-open this and help out!
