### ISSUE TITLE
Use cx- prefix instead of bx-

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#402]
Now that the `Bluemix` brand is deprecated, could you consider replacing the `bx` prefix with something like `cx` (Carbon uX) or `cc` (Carbon Components) or `cd` (Carbon Design)?

**Comment by tw15egan** [comment]
There aren't any immediate plans to update to a different prefix (big breaking change), but we will keep this in mind as we plan our roadmap to Version 9.

**Comment by joshblack** [comment]
@tw15egan maybe in scss we could do what LDS does with a prefix set as a variable that people could update if they want?

**Comment by tw15egan** [comment]
That could work 👍

**Comment by gmosx** [comment]
Now, that sounds fantastic! (what is LDS btw?)

**Comment by tw15egan** [comment]
@gmosx LDS = https://www.lightningdesignsystem.com/ 😄

**Comment by bsonefeld** [comment]
Closing this as it is something the Carbon team will put into consideration.
