### ISSUE TITLE
Tag component doesn't offer internationalization / localization hook

### ISSUE THREAD

**Issue by KCollender** [carbon-design-system/carbon#4025]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Need to provide a localized version of the title for the filtered tag. Currently always shows `clear filter`

> Is this issue related to a specific component?

Tag component.
The same issue is also present in the multiselect component, where the text `clear all selected items` cannot be overridden. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

A prop to accept a localized string that will be used for the title element.

> What browser are you working in?

Firefox / Chrome

> What version of the Carbon Design System are you using?

carbon-components-react": "7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Agile service manager RTM 21/10/2019

## Additional information
Multiselect component 

![image](https://user-images.githubusercontent.com/55497727/65160400-8ae29780-da2d-11e9-9e9c-bb50ef1b1114.png)

Tag component
![image](https://user-images.githubusercontent.com/55497727/65160445-9d5cd100-da2d-11e9-93fc-4fb20b36bfa3.png)

**Comment by asudoh** [comment]
Hi 👋 do you want to introduce a prop for that purpose? PR will definitely be welcome!
