### ISSUE TITLE
Stop serving Helvetica Neue, even in deprecated packages

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#4039]
As of 6/30/2020, the license for Helvetica Neue will lapse. We need to stop serving Helvetica Neue at that point, so that there is no accidental continued usage by IBM product teams.

We also need to stop serving Helvetica Neue even in fully deprecated versions of Carbon (so v7, v8).

We also need to clarify (documentation at a minimum) that use of Helvetica Neue by any user outside of IBM is not currently web-safe, unless they have a Helvetica Neue license for their own usage.

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/_css--font-face.scss#L32

https://github.com/carbon-design-system/carbon/tree/master/packages/components/src/globals/fonts

**Comment by mattrosno** [comment]
In doing so, make sure that Helvetica is not listed in any font families as fallbacks.

**Comment by vpicone** [comment]
We should consider updating our font stack to fallback on system fonts instead:

https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/

**Comment by shinytoyrobots** [comment]
Reopening, need to add the stalebot exclusion label!

**Comment by shinytoyrobots** [comment]
Adding Sev 1 - as this is high severity but not instantly high priority. It **must** be resolved in prod well before 6/30/2020 though.
