### ISSUE TITLE
Notification Title text is dark text against dark background

### ISSUE THREAD

**Issue by jk6** [carbon-design-system/carbon#4042]
- [x ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Am getting dark Title text against a dark background in the Notification component.

> Is this issue related to a specific component?  

Notification component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect to see white title text against the dark background, such as the text in the subtitle, which displays correctly. Would like to see color: $inverse-01 added to .#{prefix}--toast-notification__title carbon-components/scss/components/notification/_toast-notification.scss.

> What browser are you working in?

Confirmed this behavior in Chrome, Safari, and Firefox

> What version of the Carbon Design System are you using?

v 10

## Steps to reproduce the issue

Cause a notification to pop up

## Additional information

![image](https://user-images.githubusercontent.com/2753311/65265501-1c5e1200-dadf-11e9-8513-268c4027b7a0.png)

- Notes

**Comment by abbeyhrt** [comment]
Closing since contrast issues with the notifications are documented [here](https://github.com/carbon-design-system/carbon/issues/4282)!
