### ISSUE TITLE
[Feature Request] Support printing in DataTable component in React

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4044]
### Summary

Currently, DataTable component in react shows a horizontal scrollbar if the page is printed, and the content outside the view is not shown on the print view.

### Justification

Although this can be handled by writing custom printer friendly views but some other frameworks I have used in past had printer support out of the box.

### Desired UX and success metrics

All the data in the table should be visible in the print view 

### Specific timeline issues / requests

A release of our product is due in 6 weeks (31st Oct, 2019). It would be much appreciated if the functionality is released before the date.

![image](https://user-images.githubusercontent.com/54859354/65283456-cb5d1680-dafc-11e9-91a2-01b2f20c2fdc.png)

**Comment by asudoh** [comment]
We'll monitor the amount of requirements for printing like this. In the meantime, I'd suggest you implement print-specific styles that is tailored for your printing preference.
