### ISSUE TITLE
Password input toggle translation

### ISSUE THREAD

**Issue by trusinaj** [carbon-design-system/carbon#4047]
### Summary

Hey, could be possible to add prop to password input that would translate or gives us a way to change password tooltip text?

### Justification

We need to be able to translate texts so our users arent suprised by diff. language

### Current code

![image](https://user-images.githubusercontent.com/26432590/65327545-7ed51200-dbb4-11e9-9125-f7518289ca2a.png)

### Possible solution

![image](https://user-images.githubusercontent.com/26432590/65327960-7f21dd00-dbb5-11e9-8d21-6017e7a8d5ab.png)

![image](https://user-images.githubusercontent.com/26432590/65328018-9e206f00-dbb5-11e9-85bb-6ff5798254e6.png)

![image](https://user-images.githubusercontent.com/26432590/65328046-a9739a80-dbb5-11e9-8cdb-8f21e421c828.png)

**Comment by asudoh** [comment]
@emyarod What do you think of adding two props for the texts for shown/hidden states? Thanks!

**Comment by emyarod** [comment]
sure that would be fine
