### ISSUE TITLE
[Tokens] Implement lighten/darken method for color change across states. Deprecate Hover tokens.

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#4049]
New color palette is implemented here https://github.com/carbon-design-system/carbon/issues/3904 . The only place where this change is not carrying through are in the Hover states because those colors are hard coded. 

- Implement lighten/darken method for color change on hover states. 
- Deprecate Hover tokens

**Comment by vpicone** [comment]
Brand prioritized

**Comment by sadekbazaraa** [comment]
@vpicone here's the Sketch file that we went over outlining the (L)ightness value adjustments for the V2 palette hover states. 

[IBM V2 Hover Colors.zip](https://github.com/carbon-design-system/carbon/files/4136832/IBM.V2.Hover.Colors.zip)

And here's a sample from the file for reference. In this example you can see that the hover value for Red 60 has an adjusted lightness value of -8%.

<img width="463" alt="Screen Shot 2020-01-30 at 5 48 35 PM" src="https://user-images.githubusercontent.com/33162280/73501065-1a0f9c80-438a-11ea-9e17-cef3c8d9eac0.png">

**Comment by vpicone** [comment]
@carbon-design-system/developers-system

Right now the interactive tokens are hard coded which means when we shifted to v2 colors, they remained the same. 

These colors don’t exist in either pallet, adding them would require increasing the resolution of the pallet and doubling the amount colors. This defeats the purpose of a restricted pallet. 


Opened #5269 to address this

**Comment by vpicone** [comment]
example use `color` library https://codesandbox.io/s/loving-mclean-5mdqg
