### ISSUE TITLE
Font Performance in v8

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#405]
There was an issue brought up in `carbon-components-react` that is also a general question for Carbon in general that I figured I'd copy over here. The issue specifically is: https://github.com/carbon-design-system/carbon-components-react/issues/305

Quoting the issue:

> If you just go to your story book:
> http://react.carbondesignsystem.com/?selectedKind=Modal&selectedStory=transactional&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel
> open modal, you can see text is not loaded straight forward.
> The same thing happens to our product after changed to the latest version.

From a carbon perspective, it seems like we could provide guidance or point consumers to guidance around how to performantly load Plex fonts.

For context, there's an RFC for performant loading for IBM/Type here: https://github.com/IBM/type/pull/46 but it's far from finished.

**Comment by joshblack** [comment]
cc @seejamescode for guidance from the IBM/type perspective

**Comment by seejamescode** [comment]
Possibly related to https://github.com/IBM/type/issues/34, but I have only seen it in Safari.

This is not scoped to my current sprint, but would love help on it.

**Comment by joshblack** [comment]
@seejamescode landed a PR in IBM/type that dramatically improves performance here: https://github.com/IBM/type/releases/tag/v0.4.3
