### ISSUE TITLE
Accordion component: chevron should stay align with first line

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#4051]
> moved from https://github.com/IBM-Design/idr/issues/98

Chevron inside of accordion should stay top aligned if title wraps to more than one line. per @mjabbink comments https://github.com/IBM-Design/idr/issues/98

**Comment by emyarod** [comment]
I have a solution in the works but I need some clarification on the kind of behavior we want when the accordion heading text is larger than default but still just a single line, for example in the last accordion panel item

![image](https://user-images.githubusercontent.com/8265238/65773353-c4886200-e101-11e9-9af9-e0dbc889be97.png)
