### ISSUE TITLE
NumberInput custom spinner's event context should be on the input instead of the svg

### ISSUE THREAD

**Issue by mven** [carbon-design-system/carbon#406]
## Detailed description

using the `onClick()` method on the `<NumberInput />` component , the target is referencing the svg that had been clicked, instead of the `input`, something that that the "stock" spinner provides.

> Is this issue related to a specific component? 

`<NumberInput />`

> What browser are you working in? 

Chrome latest

> What version of the Carbon Design System are you using? 

v7

**Comment by tw15egan** [comment]
Is this referring to the React or Vanilla repo? Just curious, with the `<NumberInput />` syntax I want to make sure this gets addressed correctly 😄

**Comment by mven** [comment]
Aw crap - thought I was in the react repo :)

**Comment by mven** [comment]
created new issue over there https://github.com/carbon-design-system/carbon-components-react/issues/311

**Comment by tw15egan** [comment]
Just wanted to make sure, thanks for creating a new one!
