### ISSUE TITLE
October 2019 Endgame

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#4060]
This is the endgame schedule for our October 2019 iteration, which includes the
following projects:

- [Community Contribution](https://github.com/orgs/carbon-design-system/projects/12)
- [Support](https://github.com/orgs/carbon-design-system/projects/14)
- [Theming](https://github.com/orgs/carbon-design-system/projects/28)
- [Accessibility](https://github.com/orgs/carbon-design-system/projects/17)
- [Brand/website](https://github.com/orgs/carbon-design-system/projects/27)
- [Patterns](https://github.com/orgs/carbon-design-system/projects/24)
- [Website](https://github.com/orgs/carbon-design-system/projects/30)
- [Tooling](https://github.com/orgs/carbon-design-system/projects/26)
- [Components](https://github.com/orgs/carbon-design-system/projects/3)

## Schedule

- Endgame leader: @designertyler 
- Endgame sidekicks: @jnm2377 
- 09/27: Code freeze (EOD)
- 10/04: Endgame done
- 10/08: Expected release date

### Monday 09/30

- [x] Set endgame-specific branch protection rules
- [x] Coordinate delivery or resolution of the following items:
  - [ ]
- [x] Start code freeze (EOD)
  - [x] Announce code freeze on final day before the endgame
  - [x] Enable code freeze branch protection on relevant repos

### Tuesday 10/01

- [x] First Release Candidate cut
- [ ] Complete first round of smoke tests
- [ ] Share with Carbon Insiders for first round of testing

### Wednesday 10/02

- [x] Collect first round of feedback from Carbon Insiders (if available)
- [x] Triage release-specific issues and bucket them into two categories:
  - [x] Stop release
  - [ ] Ship with known issues
- [x] Coordinate merging of bug fixes related to release
- [x] Cut next Release Candidate, if applicable
  - [x] Share newest release with Carbon Insiders for additional rounds of
        testing

### Thursday 10/03

- [x] Collect second round of feedback from Carbon Insiders (if available)
- [x] Coordinate merging of bug fixes related to release
- [x] Cut next Release Candidate, if applicable
  - [x] Share newest release with Carbon Insiders for additional rounds of
        testing

### Friday 10/04

- [x] Collect final round of feedback from Carbon Insiders (if available)
- [x] Run final smoke tests on release
- [x] Make determination to release on following Monday

### Monday 10/07

- [x] Release Monday morning
- [ ] Coordinate release communications on Slack and Twitter
- [x] Summarize top-level release notes for next blog post

**Comment by designertyler** [comment]
## Theming
Introduced a feature flag to enable CSS Custom Property support. This new feature will allow full runtime theming (light and dark mode support!) and will lead to advanced theme techniques like zoning.

- adds new sass generator types that allow us to export CSS custom property theme maps #4065 
- moved generated files into a generated directory and introduced helpers for determining if custom properties should be emitted and for actually emitting the custom properties themselves #4082 
- was an intermediate step for emitting custom properties #4094 
- build on top of the previous PRs to enable outputting custom properties behind a feature flag #4100

## Carbon website
### Website content audit and strategy
The website content audit and strategy work has been focused around determining "what does a design system need to be complete?" 
Stakeholder interviews
Audits of design systems
IA and navigation explorations
Drawing up a plan of work
Comparative component usage guidance 
New template for component guidance
Mapping of current content against template to find shortcomings
Introduced a Data visualization section to the website


### Patterns
Triaged and sorted 282 community patterns by quality and importance
Created and maintained a status table on the Experimental>Overview page
Patterns contribution guidance enhancements plus MDX template for contribution content
Introduced ten experimental patterns, all from community contribution
Layout page code tab; reorganize and skin Josh’s grid demo and incorporate layout guidance
Explore theme / variant switcher component display window (Anna)


### Support audit
Compiled thousands of support questions and answers into a data table  
Looked for trends and identified areas requiring future work
Identified areas where existing content in answers can be re-used to supplement guidance


## Tooling
### V2 color palette
- V2 color palette updated in all theme kits (updated layer styles)
- V2 color palette clr file updated

### IDL kit
- Bugs fixes
- New color tokens
- V2 color palette will be added.
- The carbon themed kits have been updated with Icons from the new icon libraries so we will no longer have to manually replace icons when fixes have been made.
- Pictograms added

**Comment by jnm2377** [comment]
# Brand

- Introduced a native site-wide search for `gatsby-theme-carbon` that replaces Algolia search [#384](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/384)
- Officially released the pictogram package [#4098](https://github.com/carbon-design-system/carbon/pull/4098)
- Added a pictogram [library](https://www.carbondesignsystem.com/guidelines/pictograms/library) page to the Carbon & IDL websites
- Updated individual page metadata for both the Carbon site and Gatsby theme site
- Updated the Gatsby theme video component to use native controls instead of Vimeo controls for better a11y [#418](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/418)
- Lots of other bug fixes 🐛 🎉
