### ISSUE TITLE
font-weight not interpolated by sass

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#4062]
font-weight not interpolated by sass after importing `carbon-components/scss/globals/scss/typography` and using `@include type-style`

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

After updating from carbon-components@10.2.0 + carbon-components-react@7.2.0 to 
carbon-components@10.6.2 + carbon-components-react@7.6.2 we noticed font-weights were no longer applied in our app. Throughout our app we import `carbon-components/scss/globals/scss/typography` and use `@include type-style` to mixin carbon font styles.

After updating, we can see in Chrome dev tools that the font-weights were no longer being interpolated by sass:

![image](https://user-images.githubusercontent.com/15637876/65458586-e9d45200-de1b-11e9-90af-c46581e3b0a1.png)

## Steps to reproduce the issue

https://codesandbox.io/embed/broken-font-weight-yrjtb

**Comment by emyarod** [comment]
the `carbon--font-weight` function seems to be contained in `_font-family.scss`, does importing that resolve the issue? https://codesandbox.io/s/broken-font-weight-rktp3

**Comment by justindm234** [comment]
I see the same problem when importing `@carbon/type/scss/styles` in another file.

In both cases, importing `_font-family.scss` before `typography`/`styles` solves the problem, though that feels like something `typography`/`styles` should be doing.
