### ISSUE TITLE
Breaking change to ContentSwitcher onChange callback during minor version update

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon#4063]
Breaking change introduced at ContextSwitcher minor version update - ContentSwitcher onChange callback arguments changed from event object to number index

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

After updating from carbon-components@10.2.0 + carbon-components-react@7.2.0 to 
carbon-components@10.6.2 + carbon-components-react@7.6.2 we noticed our ContentSwitchers were broken because the onChange callback functions arguments changed from an event object (with a name property) to a Switch index (a number)

https://github.com/carbon-design-system/carbon/blob/10b9d2c07584e490aad463dcda580f9454d166eb/packages/react/src/components/ContentSwitcher/ContentSwitcher.js#L88
vs
https://github.com/carbon-design-system/carbon/blob/5616f31413736121f2d321d5efe704d4328a3b3d/packages/react/src/components/ContentSwitcher/ContentSwitcher.js#L56

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon-website/issues/119 https://github.com/carbon-design-system/design-language-website/issues/273
