### ISSUE TITLE
[Dropdown] Scroll missing in non-chrome browsers

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#4067]
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

In non-chrome browsers, when a dropdown has more than 6 options in it and has been opened, the scroll is missing, all the content is visible, and only the first 6 options have a background

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
chrome, safari, firefox, ie11, edge

> What version of the Carbon Design System are you using?
10.6x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson-Health

## Steps to reproduce the issue

1. Add more than six items to a dropdown
2. view in non-chrome browser (seen in Safari, Firefox, IE11, Edge)
3. open dropdown
4. see missing scroll and end of background color

## See an example

https://codepen.io/scottnath/pen/OJLdpar

## Additional information

* *left image: chrome*
* *right image: safari*
![Screen Shot 2019-09-23 at 5 48 55 PM](https://user-images.githubusercontent.com/216931/65465625-c49b1000-de2a-11e9-937f-386eefc398bc.png)

**Comment by jendowns** [comment]
Yeah I can confirm this as well. Currently seeing the same list in Safari.

It looks like the short-hand syntax `overflow: hidden auto` used for `.bx--dropdown-list` is not supported in Safari:
![Screen Shot 2019-09-27 at 4 21 16 PM](https://user-images.githubusercontent.com/9057921/65803067-1f8e7900-e143-11e9-946f-304921c445b1.png)

EDIT: appears fine in Firefox though
