### ISSUE TITLE
[Feature Request - React] - Expand/Collapse All Rows with a click in DataTable 

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4068]
### Summary

Apparently, there is no way to expand/collapse all rows with one click in the DataTable control.

### Justification

Just like a checkbox to select all the rows is put in the header of a table with select-able rows, the expandable row tables should have an expand/collapse all rows button in the header.

I would appreciate if someone can comment about any other way this can be done.

**Comment by asudoh** [comment]
Hi 👋 is http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-expansion close to what you had in your mind?

**Comment by tahaimt** [comment]
Oh thanks. I dont know how I missed it!
