### ISSUE TITLE
Calendar icon in the date range picker has inconsistent behavior

### ISSUE THREAD

**Issue by cwgormanIBM** [carbon-design-system/carbon#4069]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

What is the expected behavior of the calendar icon in the date range picker?

![image](https://user-images.githubusercontent.com/11217351/65528605-b0a2ed00-dec2-11e9-9bb8-b5b316449a5f.png)

With focus in the first input, pressing tab moves focus to this calendar icon, but it doesn't seem to do anything. The second calendar icon is not interactive at all. 

You can also click the first calendar icon to open the calendar dropdown, but not the second calendar icon.

This is inconsistent and seems like a bug.

I'm not sure what the exact correct behavior is, but I would expect that the calendar icon would behave the same as clicking the input itself (ie "pass through" the click), and not be a separately focusable element at all -- the same behavior as the spyglass icon in the search component.

The behavior is also inconsistent between the vanilla, React, and Angular implementations.

**Comment by joshblack** [comment]
Hi @cwgormanIBM! :wave: I believe this issue is addressed in later versions of Carbon. Let us know if this is not the case!
