### ISSUE TITLE
max total number of items for React Pagination component

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#4070]
What is the max number of "total number of items" for React Pagination component?

 http://react.carbondesignsystem.com/?path=/story/pagination--pagination 

if I entered 500000 to the "Total number of items" field, this component response very slow when I click the next page button. if the number is over 1,000,000 the storybook page crashed.

![image](https://user-images.githubusercontent.com/14806866/65531032-a5e65900-debe-11e9-8628-771095c3eafe.png)

**Comment by asudoh** [comment]
Hi 👋 we don't define that. One question; Why did you wonder about such number...?

**Comment by zhenwan** [comment]
@asudoh I need to know such number so that I won't misuse this component.

**Comment by asudoh** [comment]
OK I was asking more of your use case, but if your application really have such large number of pages (the only use case I can imagine is something like email apps, and again we don't have a defined threshold), I'd recommend using `pagesUnknown={true}`.

**Comment by zhenwan** [comment]
@asudoh Thank you, good to know  pagesUnknow={true} can be used for large number of pages.

I just did a quick test, and see if pagesUnknown={true}, the page number button does not response to mouse click. should this button be disabled if the page number is unknown?

![image](https://user-images.githubusercontent.com/14806866/65700753-c7be1800-e045-11e9-890d-a3c0c3c15bb4.png)

**Comment by asudoh** [comment]
> I just did a quick test, and see if pagesUnknown={true}, the page number button does not response to mouse click. should this button be disabled if the page number is unknown?

Sounds so. Great to have a separate issue for that. Thank you for reporting!

**Comment by nictownsend** [comment]
Hi, sorry to reopen but we have hit this problem in our product.

We have a large number of Kafka messages and we created a paginated browser view. This could result in 1000000 items (which is 100000 pages of 10).

Trying to render this in the pagination component causes the browser to crash, as the `<select>` item has over 100000 `<option>` elements.

I appreciate that the `pageInputDisabled` prop is a solution to avoid this - but it then means the user can't easily jump between pages.

Ideally, the storybook should warn about a max size - and then we may need a new approach for handling the large page input changing.

**Comment by asudoh** [comment]
Hi 👋 seems a separate issue, as you seem to be requesting for better UI to select a specific page in large list of pages. Feel free to enter an issue for that. Thanks!

**Comment by nictownsend** [comment]
Hi, am happy to open an issue if it doesn't already exist for the change in UX.

But, I'm also asking that the storybook/readme for the component is updated to warn that a large number of pages will crash the web browser.
