### ISSUE TITLE
Modals do not have correct layout in RTL

### ISSUE THREAD

**Issue by bragusa** [carbon-design-system/carbon#4071]
<!-- Feel free to remove sections that aren't relevant.

Element alignment is not implemented correctly when displaying Modals in RTL 

- [ ] `carbon-components`
- [ X ] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Any
> What version of the Carbon Design System are you using?
v10
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
Open any implementation of Modal (Carbon storybook is fine)
inspect document and set dir="rtl" on HTML  element

- Screenshots or code
![image](https://user-images.githubusercontent.com/25152845/65531914-eb0f8880-dec8-11e9-8adc-8fdda45c2e56.png)

**Comment by asudoh** [comment]
Hi 👋 we have our issue template for a good reason, great to have filled out. Thanks!
