### ISSUE TITLE
Checkbox checkmark icon is incorrectly sized when `box-sizing: border-box` reset is applied

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4074]
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

We apply a `box-sizing` reset and checkboxes imported from Carbon have incorrectly sized checkmark icons as shown here in our storybook environment: 

![Screen Shot 2019-09-24 at 2 47 23 PM](https://user-images.githubusercontent.com/9057921/65545068-40a06100-deda-11e9-9ad1-665853c38556.png)

## Steps to reproduce the issue

You can reproduce in Carbon's storybook environment by going here: http://react.carbondesignsystem.com/?path=/story/checkbox--checked

And then adding a `box-sizing: border-box` rule to the checkmark icon:

![Screen Shot 2019-09-24 at 2 42 13 PM](https://user-images.githubusercontent.com/9057921/65544899-e6070500-ded9-11e9-9bb8-805b4d800ac4.png)

**Comment by asudoh** [comment]
Hi 👋 a question; Does your reset style apply directly to the pseudo element, or does it work in a slightly different manner? I can see changing `box-sizing` at the `::after` of the `<label>` causes the styling problem, but wanted to know more on how exactly it happened. Thanks!

**Comment by jendowns** [comment]
Hey @asudoh I think the problem is has a couple different threads -- 

For one, the checkbox has a `box-sizing: border-box` applied as a single style rule (so it's not using the reset mixin as intended): https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/checkbox/_checkbox.scss#L63

And even though there IS a reset mixin used in this component, it's applied to the checkbox label. So technically that label's `::after` and `::before` aren't affected by this because they aren't children of the element where the reset is applied: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/_css--reset.scss#L25

Also this block doesn't include `:before` or `:after`: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/_css--reset.scss#L194

I have a small PR for this I'll open shortly. Please let me know what you think! (Also to answer your question, we just use a box-sizing rule in our storybook styles and leave it up to users to apply the Carbon reset mixin if they want/need. The box sizing rule is just `* { box-sizing: border-box }` I believe)

**Comment by asudoh** [comment]
I see, the problem seems with `$css--reset` not set. Thanks @jendowns for clarifying!
