### ISSUE TITLE
Radio button behavior in storybook is confusing (not interactive, can only 'check' with knob)

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4076]
## What package(s) are you using?

- [x ] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

http://react.carbondesignsystem.com/?path=/story/radiobutton--default

Try selecting the `RadioButton` (not using knobs) -- it doesn't show a "checked" state with a circle in the center 🤔

You can only "check"/select a `RadioButton` using the `checked` prop in the storybook knobs.

I just wanted to flag this with you all because this confused me at first, and I'm relatively familiar with storybook knobs & this library... and I wonder if it confuses others who maybe don't have the same context I have.

I would expect the `RadioButton` to be interactive in the component preview. The knobs are great to have but I don't think they should take away from interacting with the component. What do you think?

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Given what we see, I'm open for removing the knob.
