### ISSUE TITLE
Inconsistency between vanilla breadcrumbs and react breadcrumbs format

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#408]
## Detailed description

The format for breadcrumbs in http://carbondesignsystem.com/components/breadcrumb/code shows the last page in the breadcrumbs string as non-hyperlink text, without trailing "/".

The format for breadcrumbs in http://react.carbondesignsystem.com/?selectedKind=Breadcrumb&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel shows last page in the breadcrumb string as hyperlink text, with trailing "/".

> Is this issue related to a specific component? 

Breadcrumbs

> What did you expect to happen? What happened instead? What would you like to see changed?

No specific expectation of one or the other, but would request consistency between vanilla and React format.

**Comment by tw15egan** [comment]
@tay-aitken @aagonzales Which is the correct pattern (or are they both correct?)

On the website, we show examples of both: 

http://www.carbondesignsystem.com/components/breadcrumb/code
http://www.carbondesignsystem.com/components/breadcrumb/style

**Comment by tay-aitken** [comment]
The one on the style tab is correct. The last crumb is supposed to be the page title (h1) text on the page.

**Comment by tay-aitken** [comment]
@shinytoyrobots thanks for bringing this to our attention!
