### ISSUE TITLE
[DataTable] with batch actions, batch actions covers TableToolbarContent, unable to use Search after selection

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#4083]
## Description

Issue is related with DataTable, TableToolbarContent, TableBatchActions and TableToolbarSearch.

When at least one row is selected, TableBatchActions are covering TableToolbarContent, which means there isn't possible to use search (TableToolbarSearch) anymore.

Try: http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions

## Background

IBM application would like to use paginated DataTable with Search input, for tables with 1000+ rows, e.g. 
1. Search for **gender**, select
2. Search for **city**, select
etc.

## Steps to reproduce the issue

**Scenario I:**
1. Search for '1'
2. Select Load Balancer 1
Result: Batch actions are covering toolbar content, you are not able to clear search input and search for different value e.g. '3'

**Scenario II:**
1. Select Load Balancer 1
Result: Batch actions are covering toolbar content, you are not able to use search e.g. to find '3'

![image](https://user-images.githubusercontent.com/17591704/65584144-bbbc5280-df80-11e9-82b6-1014085bf48f.png)

## What package(s) are you using?

    "carbon-components": "10.5.0",
    "carbon-components-react": "7.5.0",
    "carbon-icons": "7.0.7",

**Comment by asudoh** [comment]
@carbon-design-system/design Any thoughts...? Thanks!

**Comment by abbeyhrt** [comment]
bump @carbon-design-system/design

**Comment by andreagmann** [comment]
Same as https://github.com/carbon-design-system/carbon/issues/5511

**Comment by joshblack** [comment]
Going to close in favor of #5511 which is an enhancement issue. It's not something that we're currently taking on but I've labeled as "help wanted" in case someone wants to take it on 👀
