### ISSUE TITLE
[DataTable] How to get information that selection changed inside DataTable ?

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#4085]
## Description

In IBM application, I would like to call action (function) every time selection changes inside DataTable, together with latest **selectedRows** information. Scenario is very similar to other components like Dropdown or RadioButtonGroup, where **onChange** is called whenever the selection changes, to communicate to a consuming component what kind of internal state changes are occurring.

Example use cases:
- Enable button in Modal component (outside component) when there is at least one row selected in DataTable
- Get DataTable selected rows when button is clicked in Modal (outside component)
- Modify outside component state just after selection in DataTable changes

I didn't found a way to achieve this in DataTable, especially be informed that selection changed. It seems selectedRows data are available only in DataTable render and batch actions internally.

Slack nick: Tomasz Kania

## What package(s) are you using?

    "carbon-components": "10.5.0",
    "carbon-components-react": "7.5.0",
    "carbon-icons": "7.0.7"

**Comment by tomkdgun** [comment]
It seems point 3) from this slack post also mentioned this problem:
https://ibm-analytics.slack.com/archives/C2K6RFJ1G/p1530819362000214?thread_ts=1530800070.000147

**Comment by asudoh** [comment]
Hi 👋 the selection event handler gives you the row ID. I imagine you'd keep track of row selection data with the update of selection/de-selection state coming from the selection event handler.

**Comment by tomkdgun** [comment]
@asudoh, Does it mean that I have to implement my own selection handlers, and add this handlers for each table row and select all component, to track in my own state, what is selected ?
I'm looking for cleaner solution which doesn't require the creation and maintaining of my own state.

**Comment by asudoh** [comment]
You are right basically - You need to implement the state management logic.
