### ISSUE TITLE
FileUploader onClick registers outside of FileUploaderButton

### ISSUE THREAD

**Issue by rickysway** [carbon-design-system/carbon#4086]
**Issue**
FileUploader onClick event is fired when clicking inside outside of the button (but inside the form element it is defined in)

**Recreate issue**
Using `https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox`

1. Add Dependency `carbon-components`
2. Update `index.js`
```
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```
3. Inside ./src with index.js, create a file called `App.js` with the following code
```
import React, { Component } from "react";
import { FileUploader } from "carbon-components-react";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      fileUploaded: false
    };
  }

  toggleUpload = () => {
    this.setState({ fileUploaded: !this.state.fileUploaded });
  };

  render() {
    const { fileUploaded } = this.state;
    return (
      <div>
        <FileUploader
          buttonLabel={fileUploaded.toString()}
          buttonKind="tertiary"
          filenameStatus="edit"
          onClick={this.toggleUpload}
          onChange={this.toggleUpload}
        />
      </div>
    )
  }
}

export default App;
```
4. Clicking the button should change the text between `true` and `false`. However, clicking outside of the button in its `bx--form-item` (If you inspect elements) causes it to register the buttons onClick (See image below for area)

<img width="1440" alt="Screenshot 2019-09-25 at 14 16 45" src="https://user-images.githubusercontent.com/22493970/65604874-15804500-dfa0-11e9-9372-bfb5976885a9.png">

The github code indicates this is not a desired effect:
https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/FileUploader/FileUploader.js#L307

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Our file uploader will have lots of improvement in next minor release. Stay tuned! CC @emyarod

**Comment by joshblack** [comment]
Hey there! :wave: Closing this out due to inactivity, feel free to comment and I can re-open!
