### ISSUE TITLE
Modal: `selectorPrimaryFocus` doesn't work, when used together with `focusTrap`

### ISSUE THREAD

**Issue by elbrus** [carbon-design-system/carbon#4088]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I want to focus specific element by using provided `selectorPrimaryFocus`. But it doesn't work if I use `focusTrap` as well.

> Is this issue related to a specific component?

Modal

> What did you expect to happen?

custom element should be focused

> What happened instead?

close button was focused

> What would you like to see changed?

```javascript
focusTrapOptions={{ initialFocus: this.initialFocus }}>
```
`initialFocus` from focus trap library doesn't have any arguments, which makes `this.initialFocus` to skip handling `selectorPrimaryFocus` (line#223)

> What browser are you working in?

any browser

> What version of the Carbon Design System are you using?

latest

## Steps to reproduce the issue

1. https://codesandbox.io/s/codesandbox-lwl17
2. input will be focused (_might need to refresh inside code sandbox to see input inside modal focused_)
3. change `focusTrap` to be `true` and refresh
4. close button will be focused

## Additional information

not related, but you have different refs assigned to the same variable:
* line#313 `ref={this.button}`
* line#362 `inputref={this.button}`

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - And good findings. Contributions welcome!
