### ISSUE TITLE
Request: Change Catalog Icon

### ISSUE THREAD

**Issue by Celand887** [carbon-design-system/carbon#4091]
#### 1. Team name
IBM Digital Sales
#### 2. Icon name
Change Catalog
#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.
For the user to change the catalog which they have previously selected within a mobile application and will sit within a top navigation bar.
#### 4. Box Link

Add in a box link (or other cloud) link to your completed Icon Contribution Template sketch file. Please make sure the permissions are set so anyone can view the icon.

#### 5. Screen Shot
I was thnking something along the lines of one of these but am open to suggestions:

<img width="224" alt="Screenshot 2019-09-25 at 11 58 30" src="https://user-images.githubusercontent.com/53057274/65595114-efe94080-df8b-11e9-896a-eb490714e032.png">

<img width="244" alt="Screenshot 2019-09-25 at 11 58 27" src="https://user-images.githubusercontent.com/53057274/65595122-f4adf480-df8b-11e9-9625-b8ec24b4527b.png">

Please add the following screen shots to this issue:

1.  Close-up screen shot of the icon with the pixel grid turned on
2.  Screen shot of the icon in context with your use case.

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
Can I ask @Celand887 please populate your profile? 
The fastest path to resolving this is you or your team proposing and executing the icon yourself; if we don't know who you are we can't help you in that endeavor.

**Comment by Celand887** [comment]
@chrisconnors-ibm of course, apologies am new to this process. I have updated profile and happy to provide more info if required.

**Comment by Celand887** [comment]
Hi @chrisconnors-ibm have I provided you with all the information you need or is there something else blocking this? Thanks

**Comment by chrisconnors-ibm** [comment]
The icons themselves. If you want branding (cc @conradennis ) to actually make them, that's an as available priority basis. I don't know what their backlog looks like.

**Comment by conradennis** [comment]
@Celand887 @chrisconnors-ibm I'm recommending this as the most feasible solution:

![Screen Shot 2019-10-21 at 5 06 53 PM](https://user-images.githubusercontent.com/16782944/67243269-3d3ebd80-f425-11e9-8c10-81cd3d516b1f.png)

at 100%

![Screen Shot 2019-10-21 at 5 07 08 PM](https://user-images.githubusercontent.com/16782944/67243284-4465cb80-f425-11e9-8461-303426db9a71.png)
