### ISSUE TITLE
bug(pictograms): YML friendly_names are all sentence case

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon#4096]
Referencing this PR: https://github.com/carbon-design-system/carbon-website/pull/389

The regex caused each title to be sentence case even though a fair number of them contain acronyms or capital letters in the second word.

Examples:

    "IBM z"
    Api

This file must be changed manually:
https://github.com/carbon-design-system/carbon/blob/81049808150288602e55b13957df31e7350cbd55/packages/pictograms/metadata.yml

**Comment by joshblack** [comment]
Hey @connor-leech! :wave: We're going through and cleaning up the backlog, was going to close this one out since it seems like it's been a bit but can 100% re-open if this is a mistake 👍
