### ISSUE TITLE
Carbon UI Shell Header with HeaderMenu don't show in chrome sometimes

### ISSUE THREAD

**Issue by cxc0210** [carbon-design-system/carbon#4103]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
    
    The component of HeaderMenu with HeaderMenuItem do not show the panel sometimes in Chrome.  it is works well in Firefox and Edge

> Is this issue related to a specific component?
    
  HeaderMenu 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
   
   When click the HeaderMenu , the hover panel is displayed.

> What browser are you working in?

  Chrom

> What version of the Carbon Design System are you using?

  "carbon-components": "^10.3.0",
  "carbon-components-react": "^7.3.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
 No

> Please create a reduced test case in CodeSandbox

please see the official website: https://www.carbondesignsystem.com/components/UI-shell-header/code, scroll to **Header with actions and nav**,  click the 'Link 4', and the panel show, and disappear.

ps: with latest Chrome Version 77.0.3865.90 (Official Build) (64-bit)

## Additional information

- Screenshots or code
- Notes

**Comment by aledavila** [comment]
Hi there! 

Closing this as it is not an issue in react when checking the actual component in storybook. If you feel this is an issue feel free to comment here. Although it seems like a website issue than a component issue.
