### ISSUE TITLE
bug (pictograms): YML category incorrect for 'Petri cultures'

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4113]
Referencing this PR: carbon-design-system/carbon-website#389

- The pictogram 'Petri cultures' should be under the category 'Life Science'. It is currently under a category called 'Life Sciences' but that seems to be a category duplicate that is just pluralized. 

- In the YML file, there is not a category specified for this pictogram which may be causing the problem.

Current:
![Screen Shot 2019-09-26 at 1.56.04 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/8fa3dabf-0e5c-4f9c-b0e8-71064fa771b2)

Should live:
![Screen Shot 2019-09-26 at 1.56.18 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/e3459b72-d8fa-4a13-ba44-084363b26a84)

**Comment by joshblack** [comment]
Going to close this out as I believe it's been addressed!

https://github.com/carbon-design-system/carbon/blob/master/packages/pictograms/categories.yml#L319

![image.png](https://images.zenhubusercontent.com/5618bf72638e718c995dadc6/50453443-e591-4264-9057-048ff40e4d91)

Let me know if not and I can re-open!
