### ISSUE TITLE
Couldn't find package "carbon-components-react" on the "npm" registry

### ISSUE THREAD

**Issue by JuliusKoronci** [carbon-design-system/carbon#4115]
## Outdated documentation all over the place
Following all the getting started guides I am unable to even install carbon, looks like carbon-components-react was removed but all tutorial use it so not sure what would be the correct way of setting it up

## What package(s) are you using?

- [ ] `carbon-components`
- [ x ] `carbon-components-react`

## Detailed description

> trying to install following the information on github, teh website etc. but fails on a missing npm package

**Comment by asudoh** [comment]
Hi 👋 would you want to follow https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox to see how the NPM package can be installed?

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - We fix it, thanks to @joshblack
