### ISSUE TITLE
Scaled Pictograms on Pictograms library produces unexpected results

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#4121]
on https://www.carbondesignsystem.com/guidelines/pictograms/library

48x48 px pictograms are currently scaled 33% to 64x64 which produces unexpected results esp on @1x screens.

Instead, please scale them to an even multiple of their native size 48x48 (96x96) and the results are significantly better
![image](https://user-images.githubusercontent.com/35537391/65793892-e818d000-e134-11e9-887b-4d0754f38568.png)

Having their size be distinct from the size of icons reinforces that they are different from icons.

**Comment by vpicone** [comment]
Our design docs have two sizes between 48 and 96. And we talk about them as being scaleable to any size. Are we sure this isn’t related to the .72 stroke-width multiplier we’re applying at all sizes?

![C00417C7-FA61-48EA-B456-3D80D908449B](https://user-images.githubusercontent.com/4078018/65782006-631cbf00-e112-11e9-8ed4-b13434f9a173.png)

**Comment by chrisconnors-ibm** [comment]
Scale them to an even multiple of 48 (96x96) and the results are significantly better

monitors have pixels, we need to use that as an advantage, not a liability

**Comment by laurenmrice** [comment]
closing because this is resolved
