### ISSUE TITLE
[DatePicker] There is a way to determine if the user didn't select any date on the calendar?

### ISSUE THREAD

**Issue by Ovidiu01** [carbon-design-system/carbon#4123]
## What package(s) are you using?

"carbon-components": "^9.91.0",
"carbon-components-react": "^6.114.0",
"carbon-icons": "^7.0.7"

## Summary

When the user changes the date from DatePicker (i.e. by clicking a date on the calendar), the onChange handler is called, but if the user changes his mind and doesn't choose any date and clicks outside the calendar the OnChange is not trigger, but the input is filled automatically with a date(is the first day available from respective month).
I want that input to not be automatically filled if no date is chosen.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Let's continue the discussion at: #2692
