### ISSUE TITLE
[Pictograms] Add all pictogram assets into plugin

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4130]
Need to add all pictograms into the carbon plugin so we can generate them into the idl kit/libraries.

**Comment by laurenmrice** [comment]
not stale. need this to be on next release planning if not this releae

**Comment by laurenmrice** [comment]
NOt stale

**Comment by chrisconnors-ibm** [comment]
definitely not stale

**Comment by laurenmrice** [comment]
Things to be done in order of importance:
1. Add support for pictograms and ensure they render properly once uploaded into the kit
2. Add new icons that have been added since we released that last update (~September)
3. Fix known bugs with existing icons

Things to consider moving forward:
- Set a regular cadence for when the plugin should be updated (Example: every 2 months?). This way we can ensure the kits will be updated with the latest assets on a schedule.
- Can we get more than one dev familiar with how to update/run this plugin?

**Comment by chrisconnors-ibm** [comment]
on the last point, it would be great if we can get it to the point where anyone could run the plugin on their repo if necessary. even better that we release it in the wild, as it adds real value to our team and could add value broadly - and be a feather in our cap
