### ISSUE TITLE
ContentSwitcher context switch causes focus on keypress

### ISSUE THREAD

**Issue by rickysway** [carbon-design-system/carbon#4137]
**Issue**
ContentSwitcher context switch becomes focus on keypress after first context switch.
This occurs during re-renders such as during setState of TextInput value.

**Recreate issue**
Using https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

1. Replace index.js with the following code
```
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```

2. Inside ./src with index.js, create a file called App.js with the following code
```
import React, { Component } from "react";
import { ContentSwitcher, Switch, TextInput } from "carbon-components-react";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      page: 0,
      value: ""
    };
  }

  toggle = index => {
    this.setState({ page: index });
  };

  setValue = event => {
    this.setState({ value: event.target.value });
  };

  render() {
    return (
      <div>
        <ContentSwitcher onChange={this.toggle}>
          <Switch text="Form" />
          <Switch text="Blank Page" />
        </ContentSwitcher>
        <TextInput
          onChange={this.setValue}
          value={this.state.value}
        />
      </div>
    );
  }
}

export default App;
```

3. Enter text into the TextInput
![image](https://user-images.githubusercontent.com/22493970/65888743-eef34d00-e397-11e9-8a04-049e50db81f4.png)

4. Click the 'Blank Page' tab and enter text into the TextInput.
![image](https://user-images.githubusercontent.com/22493970/65888896-3548ac00-e398-11e9-9d26-d1c45d0a45b8.png)
The focus automatically moves to the ContextSwitcher per keypress in TextInput and should not be expected behaviour

**Comment by jnm2377** [comment]
@joshblack would this be something that was fixed when we reverted the breaking changes?

**Comment by joshblack** [comment]
@jnm2377 yup! Closing as this has been reverted, and so this behavior should be restored. Let us know if this is not the case!
