### ISSUE TITLE
[colors] Deprecate yellow-20 and keep yellow-30 with v2 color palette update

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4141]
Need to deprecate yellow-20 and keep yellow-30 for v2 color palette.

![Screen Shot 2019-09-30 at 3.26.46 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/aa5cb311-3522-4f1d-96c3-205ddd1bb2f1)

Right now we have two yellow colors in elements. Yellow-20 is from the old color palette. Yellow-30 is the new color that will replace it.

**Comment by AlexanderLyon** [comment]
@laurenmrice is this across all components? It looks like the only place yellow-20 is currently being used is in a mix to create the warning notification background color

**Comment by laurenmrice** [comment]
Yes, the yellow-30 should be used in that mixin .
