### ISSUE TITLE
TableToolbarSearch - Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `Search`, expected `string`.

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#4153]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

`Search` is not provided an `id` prop of type `string` from `TableToolbarSearch`. It is provided a number.

> Is this issue related to a specific component?

`TableToolbarSearch`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

`setupGetInstanceId()` returns a number, which is used for the `id` prop on `Search`.

https://github.com/carbon-design-system/carbon/blob/1a435757c9f5b69d6f21f9a5269bb8ba0c24747c/packages/react/src/tools/setupGetInstanceId.js#L15

https://github.com/carbon-design-system/carbon/blob/b2636f786592dfbfbee2bf05f55c40719db15f0b/packages/react/src/components/DataTable/TableToolbarSearch.js#L45

https://github.com/carbon-design-system/carbon/blob/b2636f786592dfbfbee2bf05f55c40719db15f0b/packages/react/src/components/DataTable/TableToolbarSearch.js#L93

This should be converted to a `string`, to match proptypes for `Search`

This overall manifests as a proptype warning in our project:
```
Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `Search`, expected `string`.
```

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

```
"carbon-components": "^10.6.4",
"carbon-components-react": "^7.6.4",
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson IoT PAL - It causes our storybook snapshot tests to fail. Was noticed while upgrading from 10.4

**Comment by cookcm** [comment]
This error still exist with :
 "carbon-components": "10.51.0",
    "carbon-components-react": "7.51.0",

as shown on this sandbox : https://codesandbox.io/s/carbon-datatable-4k05i

**Comment by tay1orjones** [comment]
@cookcm I don't see the same error in the sandbox. There is a similar one though

```
Warning: Failed prop type: Invalid prop `persistent` of type `string` supplied to `TableToolbarSearch`, expected `boolean`.
```

This is because in your example the `persistent` prop is configured with a string instead of a boolean.

```diff
- persistent="true"
+ persistent={true}
```
