### ISSUE TITLE
Wrapped headers do not have proper padding in carbon-react data table component

### ISSUE THREAD

**Issue by sjhowell** [carbon-design-system/carbon#4170]
## Title line template: [Title]: Brief description
Wrapped headers do not have proper padding in carbon-react data table component

## What package(s) are you using?
- [ x] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using a carbon-react Data Table with sorting, if a column header has text which is too long for the column width, resulting in the text wrapping, there is no padding underneath the column heading, which looks unclean, and also does not look like the wrapped heading in a normal carbon 10 data table.

> Is this issue related to a specific component?

Yes - DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected there to be some grey padding underneath the column heading. Instead the heading touches the bottom edge of the column header row. 

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Netcool Agile Service Manager UI

## Steps to reproduce the issue

1. Go to http://react.carbondesignsystem.com/?path=/story/datatable--with-sorting
2. Make the browser narrow until the "Attached Groups" column header wraps
3. Observer the lack of bottom padding:

![image](https://user-images.githubusercontent.com/40432849/66051741-4d026a80-e527-11e9-8c03-f62f14ae1452.png)

4. Compare to the wrapped header text on https://www.carbondesignsystem.com/components/data-table/code:

![image](https://user-images.githubusercontent.com/40432849/66051816-702d1a00-e527-11e9-9bff-62a56ad934e9.png)

**Comment by emyarod** [comment]
I'm not able to reproduce this issue

![image](https://user-images.githubusercontent.com/8265238/66662355-4900d780-ec0e-11e9-82ac-5fc8e7f1ce40.png)

**Comment by emyarod** [comment]
you can modify the `height` rule in `bx--table-sort` to include the additional padding, but I'm not sure if this is a change we should make in our stylesheet. need to see how it affects all of the other table variants first

```css
.bx--table-sort {
  height: auto;
}
```

**Comment by ZrianinaMariia** [comment]
@sjhowell what Firefox version are you using? I was not able to reproduce it in Chrome Version 77.0.3865.90, Safari (Version 13.0.2 (14608.2.40.1.2)) or Firefox 69.0.3 (64-bit).

**Comment by sjhowell** [comment]
Hi @ZrianinaMariia 
I am using Firefox ESR 60.9.0. I tried on Chrome and Edge and, like you, I find it is okay on them. So.. maybe this is only a problem on Firefox.
It would be preferable for Carbon-React to be supported on the ESR versions of Firefox, because these are heavily used by IBM customers who have to control the software on their operators desktops, and hence cannot cope with the rapid upgrades of the normal Firefox releases, and hence stick to the ESRs.

**Comment by sjhowell** [comment]
FYI... thanks for the suggestion about:

```
.bx--table-sort {
  height: auto;
}
```

However, whilst this fixes the padding issue, it leaves a problem of sort buttons on non-wrapped columns being the wrong height - see dark hover in screen shot below:

![image](https://user-images.githubusercontent.com/40432849/66902683-f7cf5a00-eff8-11e9-9328-095bc85f36e6.png)

**Comment by tw15egan** [comment]
This issue seems to be resolved in latest Carbon. Closing, but feel free to reopen if you are still experiencing problems!
