### ISSUE TITLE
[Data Table] Unable to toggle Zebra striping on Data Table using built-in configs

### ISSUE THREAD

**Issue by lucasmccomb** [carbon-design-system/carbon#4205]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When using the Data Table component, there's no way to toggle the Zebra striping using built-in configs and the user is forced to override styling in order to do so. This is a **bummer**. Please add a way to toggle the Zebra striping since it is a main style feature of the Data Table that should be able to be toggled on/off. Thanks!

**Comment by jendowns** [comment]
Hey @lukemccomb, are you able to use the `useZebraStyles` prop?
https://github.com/carbon-design-system/carbon/blob/9b8a4619f20716d1f440d09afdbeb4e182a229bb/packages/react/src/components/DataTable/Table.js#L53-L57

You can experiment with it here in the storybook knobs: http://react.carbondesignsystem.com/?path=/story/datatable--default
<img width="837" alt="Screen Shot 2019-10-08 at 9 00 32 AM" src="https://user-images.githubusercontent.com/9057921/66402284-371efa80-e9aa-11e9-9ca3-9c64044155b6.png">
