### ISSUE TITLE
Date Picker - Keyboard navigation issues

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon#4207]
## Environment

> Chrome 77.0.3865.90

> Keyboard navigation (tabbing and arrow keys)

## Detailed description

> Varient 

Date Picker range with calendar and min/max dates

> What version of the Carbon Design System are you using?

React 7.7.0-rc

> What did you expect to happen?

I expected to be able to tab or arrow into the calendar. 

> What happened instead?

If I tab it goes to the next date input and closes the calendar. If I try to arrow nothing happens 

## Steps to reproduce the issue

1. Tab into the starting date
2. Try to arrow into the calendar.
3. Try to tab into it.

**Comment by asudoh** [comment]
@aledavila Thank you for reporting! One question; Did you try down-arrow?
