### ISSUE TITLE
ToastNotification: when using timeout in toastnotification, the notification can't be rendered the second time.

### ISSUE THREAD

**Issue by Zhaosu** [carbon-design-system/carbon#4211]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> I'm using `ToastNotification` in carbon, and I'm using timeout to make the notification disappear by itself. The first time the notification will show and disappear after several seconds, but the second time the notification will not show up. When I don't use `timeout`, the notification will get rendered in the second time.

> Is this issue related to a specific component?
 This issue is related to `Toast Notification`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I want to see that the notification will get rendered in the second time and third and so on, also disppear by itself.

> What browser are you working in?
Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Datastage Flow Designer, we have a release in October

> Please create a reduced test case in CodeSandbox
> Here is a simple case: https://codesandbox.io/s/codesandbox-y7gl1
 When click one button, notification will show, but if click button again, no notification showed n up.
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Workaround: Re-creating the notification, e.g. with `key`

**Comment by Zhaosu** [comment]
Thanks! Solved!
