### ISSUE TITLE
Icon for the text area component in the right bottom corner  to increase size of the text area

### ISSUE THREAD

**Issue by Anna-zh** [carbon-design-system/carbon#4212]
Hi

In "text area component" in right bottom corner handle is image, not an sag icon.
I'm attaching svg icon, I've recreated based on this image
[text_field_corner_handle-01.svg.zip](https://github.com/carbon-design-system/carbon/files/3688387/text_field_corner_handle-01.svg.zip)
.

**Comment by asudoh** [comment]
Hi 👋 we don't have a straight-forward control over the resize handle and thus we are using browser's native one. Hope this helps!
