### ISSUE TITLE
carbon-components-react Pagination should not reset page number to 1 when itemsPerPage choices change

### ISSUE THREAD

**Issue by stvcisco** [carbon-design-system/carbon#4217]
## What package(s) are you using?
- [x] `carbon-components-react`

## Detailed description
The Pagination component will reset the current `page` to 1 during `getDerivedStateFromProps` if `pageSizesChanged` is true. 

## Steps to reproduce the issue

1. Initialise a Pagination object with pageSizes = [10, 20, 30]
2. change to page 3 (or any page above page 1)
3. render again with a different value for `pageSizes` (see example code)
4. See that page is reset to 1

See behaviour in this sandbox:
https://codesandbox.io/s/codesandbox-i55sv?fontsize=14

## Additional information
I understand that the page number should reset to 1 if the pageSize changes, but not if it's only pageSizes (the array of choices) changes.

**Comment by stvcisco** [comment]
Here is a fix proposal (I don't have authority to create a branch for a PR):
Change the return statement for `getDerivedStateFromProps` in this file
`carbon-components-react/lib/components/Pagination/Pagination.js`

```
      return !pageSizesChanged && !pageChanged && !pageSizeChanged ? null : {
        page: pageSizeChanged ? 1 : pageChanged ? page : currentPage,
        pageSize: pageSizesChanged ? pageSizes[0] : pageSizeChanged ? pageSize : currentPageSize,
        prevPageSizes: pageSizes,
        prevPage: page,
        prevPageSize: pageSize
      };
```

The only change is in the 2nd line changing:
    ` page: pageSizesChanged ? 1 : pageChanged ? page : currentPage`
to this:
    ` page: pageSizeChanged ? 1 : pageChanged ? page : currentPage`

This means we reset the page value to 1 only if the pageSize changed rather than the choices of page sizes.

**Comment by asudoh** [comment]
Hi 👋 thank youfor reporting - You can create a fork, create a branch in your fork, and then send a PR from there. Looking forward to having one!

**Comment by stvcisco** [comment]
PR created: https://github.com/carbon-design-system/carbon-components-react/pull/2420

**Comment by stvcisco** [comment]
new PR created: https://github.com/carbon-design-system/carbon/pull/4239
