### ISSUE TITLE
Regression bug: Vanilla Tooltip focus management

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#4232]
I submitted these PRs (https://github.com/carbon-design-system/carbon/pull/3476 and https://github.com/carbon-design-system/carbon/pull/3148) which corrected a11y bugs on Tooltips in Carbon vanilla and in the latest version of Carbon this behavior is no longer working

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

 - Tooltips without interactive elements should focus the tooltip on open so that screen reader users have access to the content
- The user should be able to click inside the tooltip without it closing the tooltip

> Is this issue related to a specific component?

Interactive tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- The tooltip (when there are not interactive elements within it) should receive focus
- The user could select content that was within the tooltip without it closing

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.6.4

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library. We have a release early Nov

## Steps to reproduce the issue

1. Open the tooltip in the demo below
2. the tooltip should receive focus (there is a white border that displays when it gets focus)

https://codepen.io/elizabethsjudd/pen/oNNNgpM?editors=1000

**Comment by asudoh** [comment]
Hi @elizabethsjudd thank you for reporting - Would you want to send a PR with Karma test cases for those? Thanks!

**Comment by elizabethsjudd** [comment]
@carbon-design-system/developers can you assign this issue to me and I'll make the fix and add tests for this issue.

**Comment by elizabethsjudd** [comment]
@asudoh I'm running in to issues with a similar interaction as this bug I logged: https://github.com/carbon-design-system/carbon/issues/3835

on `track-blur.js` line 45, we need to know if the user clicked within the element and if so, we don't want to close the tooltip.  Right now we have no way of knowing that information from the `event` object.  Do you have any thoughts on how we could test for this use-case as I know Carbon doesn't want me to add a click event to the document (which is how WH handled the same interactions).

**Comment by asudoh** [comment]
My knee-jerk reaction to that is the caller code `handleBlur(event)` can test if a certain element contains `event.target`. BTW having this question made me wonder if your draft PR hasn't fixed the issue yet...?

**Comment by elizabethsjudd** [comment]
@asudoh the `event.target` is whatever was in the tooltip that had focus so even if i click outside of the tooltip it would be the same thing.  The issue is that I have no way of knowing what the "new" target would be since this is a blur event not a click event.  My draft PR does not fix the issue but I wanted to have the demos live on netlify for you to see.

**Comment by asudoh** [comment]
`track-blue.js` uses `focus`/`focusin` for its most part IIRC.

**Comment by elizabethsjudd** [comment]
it uses `focusin/focus` for part of it and then `focusout/blur` for the other part which is the event listener that is being called for this particular use case.

**Comment by asudoh** [comment]
I see, thank you for clarifying! `relatedTarget` then?

**Comment by elizabethsjudd** [comment]
`relatedTarget` is `null` in both instances
