### ISSUE TITLE
Complete css is not getting generated from SASS file

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon#4236]
Hi,

I am an IBM'r and used the channels for my question and as I dint get any response trying out over here.

## What package(s) are you using?
carbon-components@^9.59.0
carbon-components-react@^6.55.5

- [ 9.59.0] `carbon-components`
- [6.55.5] `carbon-components-react`

## Summary
We use sass for building our css. And when we include some of the carbon css, the complete css for a component is not getting created. For example when we import @import 'carbon-components/scss/components/breadcrumb/breadcrumb', it includes only css which is part of **@mixin breadcrumb** and does not include css from **@mixin breadcrumb--x**, because of which all the styles are not working. Can someone help us in knowing how to get them included

**Comment by asudoh** [comment]
Hi :wave: `--x` `@mixin`s were for experimenting `v10` styles in `v9` codebase. That said, if you want code from those mixins looks that you should upgrade to `v10`.
