### ISSUE TITLE
Export lower level components with carbon-components-react

### ISSUE THREAD

**Issue by rakshith-pibm** [carbon-design-system/carbon#4249]
### Summary

There are various components that are in carbon-components-react which are currently only internal or dependent components. It would be valuable if these components are exported as individual components too.
Some of the examples of such components are:
* ListBox
* Selection
ans many more

### Justification

One of the things defined in the Filter pattern defined by react in https://www.carbondesignsystem.com/patterns/filtering/#multiple-categories is to show selection count and clear selection which is part of MultiSelect - but this component is a classic drop down filter - but we are trying to implement a page filter like defined in  the pattern. 
![image](https://user-images.githubusercontent.com/46721470/66343816-0b503600-e912-11e9-8eb2-3a2791a23809.png)

**Comment by asudoh** [comment]
Makes sense to me, let's see what others think.

**Comment by joshblack** [comment]
Would be great to expose some of this stuff! Might be a good candidate for hooks, too, depending on the behavior 😄
