### ISSUE TITLE
bug(tooltip): Alignment on tooltip is inconsistent

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon#4252]
In the react.carbondesignsystem.com Storybook, right and left tooltips are inconsistently offset from the icon

Browser: Firefox 69.0.1
OS: MacOS 10.14.6
### Default (right)
<img width="435" alt="image" src="https://user-images.githubusercontent.com/44656921/66353302-5294f180-e927-11e9-8905-00d3a63c19cf.png">

### Default (left)
<img width="360" alt="image" src="https://user-images.githubusercontent.com/44656921/66353333-60e30d80-e927-11e9-9099-6168c4567b1b.png">

**Comment by asudoh** [comment]
I no longer see the problem of caret position at https://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom - @connor-leech Please don't hesitate to speak up otherwise!
