### ISSUE TITLE
Bug(TableSelectRow): the checked prop is blocking the rows

### ISSUE THREAD

**Issue by fabienchn-zz** [carbon-design-system/carbon#4253]
##TableSelectRow checked prop is blocking the rows

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The `TableSelectRow`'s `checked` prop is marked as required. But when we use it inside a DataTable and with the `getSelectionProps` and `onSelect` and so on, it's not needed. It works very well without setting the `checked` props at all.
When I set the `checked` props thought to `true` or `false`, because otherwise I get a console error, it checks/unchecks all rows by default and blocks them so that it's impossible to uncheck/check them manually (by clicking on the boxes in the UI).

Can we make this `checked` prop optional instead of required ?

## Sandbox
Here is a sandbox to see a live example. Try unselecting a row.
https://codesandbox.io/s/codesandbox-y4umm

**Comment by emyarod** [comment]
can you provide code snippets or a [code sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) example that shows the issue just for additional context?

**Comment by fabienchn-zz** [comment]
@emyarod good idea. I just added a sandbox to the issue, thank you

**Comment by emyarod** [comment]
@fabienchn just for clarification, the issue is that a prop type warning is emitted so you added the `checked` prop to address it (which breaks functionality)?

**Comment by fabienchn-zz** [comment]
@emyarod exactly

**Comment by emyarod** [comment]
@fabienchn when I remove the `checked` attribute in your example, no prop type warnings are emitted since it seems to receive the attribute from `getSelectionProps`

**Comment by fabienchn-zz** [comment]
Aw yeah, you are right ! This was actually due to my tests not having the getSelectionProps.. 
Sorry about that !
Thank you for your quick responses
