### ISSUE TITLE
Ability to add text to the overflow menu

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon#4256]
### Summary

> Please describe your request in one or two sentences.

We would like the ability to add text to the overflow menu, before or after the icon, to help the user understand what the menu is. 
We are mainly looking for designs and approval from the carbon team.

### Justification

> Provide the business reasons for this request.

We have designs for a tab overflow menu, but we want the ability to add the text 'More' after the icon for clearer meaning to the user as to what it is. Our current path is to edit the overflow menu as a custom component, but It would be better if this functionality enhancement could benefit other carbon users.

### Desired UX and success metrics

> Describe the full user experience for this feature. Also define the metrics by which we can measure success/failure for the user.

User will see text as a part of the overflow menu dropdown, either before or after the icon. We don't not have metrics at this time but we would aim to see more users using items in the overflow menu.

### "Must have" functionality

> Highlight any "must have" needs and functionality for the request.

A component 'knob' with a text input for the text

### Specific timeline issues / requests

> Do you want this work within a specific time period? Is it related to an upcoming release?

None

### Available extra resources

> What resources do you have to assist this effort?

We have designs, as part of a tab overflow menu. We are also willing to provide development work on the Vue component.
<img width="827" alt="Screenshot 2019-10-08 at 10 49 30" src="https://user-images.githubusercontent.com/9937136/66479983-8857e880-ea95-11e9-89c4-3661d53e0c22.png">

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Would you want to bring up your design to discuss with @carbon-design-system/design?

**Comment by mrsideshowjack** [comment]
<img width="827" alt="Screenshot 2019-10-08 at 10 49 30" src="https://user-images.githubusercontent.com/9937136/66479983-8857e880-ea95-11e9-89c4-3661d53e0c22.png">

**Comment by asudoh** [comment]
@carbon-design-system/design Is this a use case that we want to support...? Thanks!

**Comment by chrisconnors-ibm** [comment]
Overflow menu is for a specific use case: space constraint. Adding a label is at odds with that.
