### ISSUE TITLE
[Dropdown]: codepen does not match netlify

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#4259]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The [codepen example for dropdown--inline](https://codepen.io/team/carbon/pen/OGMNRY) does not match what was it in [the dropdown--inline part of the netlify deployment of carbon-components](https://the-carbon-components.netlify.com/component/dropdown--inline.html). The focus styles are different between the two.

> Is this issue related to a specific component?
 Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

they should match styling

> What version of the Carbon Design System are you using?
latest/master

### codepen

<img width="1178" alt="11dcbd00-e9a7-11e9-8918-ba42e245d591" src="https://user-images.githubusercontent.com/216931/66413127-cf29dd80-e9c4-11e9-9cd9-2c3c03136fa5.png">

### netlify

![Screen Shot 2019-10-08 at 12 12 33 PM](https://user-images.githubusercontent.com/216931/66413217-f7194100-e9c4-11e9-86f9-dd3a714cd84d.png)

**Comment by emyarod** [comment]
refs #3586

just wondering @jnm2377 @alisonjoseph are the hacktoberfest and help wanted labels meant to go on assigned tickets?

**Comment by elizabethsjudd** [comment]
@jnm2377 Is there an ETA on this since I don't see it assigned to any projects.

**Comment by elizabethsjudd** [comment]
@carbon-design-system/developers Is this issue being worked on for the 10.8 release? If not can we get it assigned to either me or @vincentsnagg so we can contribute the fix. This is blocking a release of ours.
