### ISSUE TITLE
React SideNav with null child throws error

### ISSUE THREAD

**Issue by st004547** [carbon-design-system/carbon#4261]
If a child of SideNav (or SideNavItems) is conditionally added, when React evaluates the child to null, the SideNav throws an error during runtime.

## Using 
"carbon-components": "^10.5.1",
"carbon-components-react": "^7.5.1",

## Detailed description
Within our SideNav, certain options are only available to users within specific attributes/roles. We use `{ hasRole && <SideNavLink>Link Name</SideNavLink>` to control the display of these options. In these cases, React adds a null value into the `children` array. When rendered, The SideNav component loops through these elements (via `map()`) and calls `React.cloneElement()` on each. When one of the elements is `null` a runtime error is thrown: `React.cloneElement(...): The argument must be a React element, but you passed null.` 

```
const allowSecret = false;
const App = () => (
  <SideNav isPersistent expanded isChildOfHeader={false}>
    <SideNavItems>
      <SideNavLink>Link 1</SideNavLink>
      <SideNavLink>Link 2</SideNavLink>
      {allowSecret && <SideNavLink>Secret Link</SideNavLink>}
    </SideNavItems>
  </SideNav>
);
```

> - React:
>  https://r3fde.csb.app/

**Comment by alisonjoseph** [comment]
@vpicone

**Comment by vpicone** [comment]
I think we should definitely be checking if an element exists before cloning it.

As a workaround, you can do something like the following:

```jsx
const publicLinks = ['link 1', 'link 2'];
const secretLinks = ['link 3', 'link 4'];

const links = allowSecret ? [...publicLinks, ...secretLinks] : publicLinks;

const App = () => (
  <SideNav isPersistent expanded isChildOfHeader={false}>
    <SideNavItems>
      {links.map(link => (
        <SideNavLink>{link}</SideNavLink>
      ))}
    </SideNavItems>
  </SideNav>
);
```

**Comment by s100** [comment]
`<HeaderMenu>` has [exactly the same problem](https://github.com/carbon-design-system/carbon/blob/8b042359b625869c3e8fddb39b5183b334bd0e6d/packages/react/src/components/UIShell/HeaderMenu.js#L215) where it's trying to `React.cloneElement` a child which could be `null`. It also has exactly the same workaround.

**Comment by Kimi1020** [comment]
I have also encountered this issue during my implementation. Below method can also be a workaround. 

const App = () => (
  <SideNav isPersistent expanded isChildOfHeader={false}>
    <SideNavItems>
      <SideNavLink>Link 1</SideNavLink>
      <SideNavLink>Link 2</SideNavLink>
      **{allowSecret ? <SideNavLink>Secret Link</SideNavLink> : <></>}**
    </SideNavItems>
  </SideNav>
);

However, I also suggest carbon team can fix it by filtering the null child before cloning element.

**Comment by Kimi1020** [comment]
I have also encountered this issue during my implementation. Below method can also be a workaround.
const App = () => (
  <SideNav isPersistent expanded isChildOfHeader={false}>
    <SideNavItems>
      <SideNavLink>Link 1</SideNavLink>
      <SideNavLink>Link 2</SideNavLink>
      {allowSecret ? <SideNavLink>Secret Link</SideNavLink> : <></>}
    </SideNavItems>
  </SideNav>
);

However, I also suggest carbon team can fix it by filtering the null child before cloning element.

**Comment by joshblack** [comment]
I believe this was closed over in: https://github.com/carbon-design-system/carbon/pull/4623 If this isn't the case, leave a comment and I can 100% re-open!
