### ISSUE TITLE
NumberInput doesn't honor min and max

### ISSUE THREAD

**Issue by xpander53** [carbon-design-system/carbon#4264]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
You can enter number smaller or larger than the max and min.

> Is this issue related to a specific component?
NumberInput

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "10.4.1",
"carbon-components-react": "7.4.1",
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson for Clinical Trial Matching

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/codesandbox-n204q

You can see in on the storybook as well.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! As you found, and similar to `<input type="number">`, our number input code does not block user from entering values that goes out of min .. max range. You can, however, listen to `onChange` event and set `invalid`, etc. props upon the new value.

**Comment by abbeyhrt** [comment]
Thank you for making this issue! This problem has thankfully been addressed in recent versions of Carbon in https://github.com/carbon-design-system/carbon/pull/4817
