### ISSUE TITLE
[Notification] Low contrast style bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#4282]
There are some style bugs with the **low contrast** variation of notification

- [x] Inline notifications in `White` and `Gray 10` themes need to add color border and remove the drop-shadow. See spec section below 
   - **As-is:**
   - ![image](https://user-images.githubusercontent.com/11670886/66516423-95c99e80-eaa6-11e9-9900-f8621c74b945.png)

- [ ] Gray 90 and Gray 100 low contrast notifications are completely wrong and should look like the specs in next section
   - **As is:** 
   - ![image](https://user-images.githubusercontent.com/11670886/66516282-4d11e580-eaa6-11e9-8fdb-9cb6bbdc3029.png)

# Specs

Sketch file: https://ibm.box.com/s/wlqdd8ayfcvf4omy7616ldzs2elei9bv

**To-be:**

| Gray 100             |  Gray 90 |
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11670886/66515548-eb04b080-eaa4-11e9-8561-d92d0a74461b.png) | ![](https://user-images.githubusercontent.com/11670886/66515967-acbbc100-eaa5-11e9-858b-1c1e52a6c40b.png) |

| White            |  Gray 10 |
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/11670886/66516330-67e45a00-eaa6-11e9-8e23-bee934b1d257.png) | ![](https://user-images.githubusercontent.com/11670886/66516351-72065880-eaa6-11e9-9eab-5c4277311bfe.png) |

**Comment by aledavila** [comment]
was this solve in https://github.com/carbon-design-system/carbon/pull/4299? @aagonzales

**Comment by aagonzales** [comment]
It is partially resolved. The low contrast notification in the Gray 90 and Gray 100 theme are not to spec but is blocked by component level theming (or something to that effect, there's a dev blocker). They are at least now legible and usable. 

As-is:
![image](https://user-images.githubusercontent.com/11670886/74774815-06a17400-525a-11ea-8430-d1657bf1beeb.png)

To-be:
![image](https://user-images.githubusercontent.com/11670886/74774838-1325cc80-525a-11ea-98a8-01bc7465c13b.png)

**Comment by emyarod** [comment]
this is still blocked by compnent level theming right? for a workaround would we want to add a component level token or should we continue holding off until component level theming has been implemented?

**Comment by aagonzales** [comment]
@emyarod Actually it looks like the low contrast notifications in the dark theme are showing correctly now in the storybook. I'm not sure when it was resolved. 

![image](https://user-images.githubusercontent.com/11670886/110372541-6b25a180-801c-11eb-8ce4-ce78b54ebbaa.png)

**Comment by emyarod** [comment]
resolved in https://github.com/carbon-design-system/carbon/pull/7808
