### ISSUE TITLE
Virtual column icon

### ISSUE THREAD

**Issue by rebeccaurry15** [carbon-design-system/carbon#4285]
### Summary
This virtual column icon is used in DQ and should be added to the Carbon library.
[virtual-column.zip](https://github.com/carbon-design-system/carbon/files/3709332/virtual-column.zip)

### Justification
This icon doesn't exist yet.

![image](https://user-images.githubusercontent.com/56367262/66518915-1f736f00-ea9b-11e9-97b6-c119d8adb9da.png)

**Comment by conradennis** [comment]
Hi @rebeccaurry15 just saw your two icon issues, could you slack me directly @ ctennis with some more detail/context about what these icons are used for? Artwork for both looks ok, might need some minor tweaks
