### ISSUE TITLE
Got some security issues after scaned by AppScan on Cloud

### ISSUE THREAD

**Issue by Bin-Xiong** [carbon-design-system/carbon#4288]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
We used ASoC to scan open source libs we are packaging in our product, some security issues reported by ASoC.
main issues reported:
- Insecure Use of setAttribute
![图片](https://user-images.githubusercontent.com/40814512/66465503-8a30a480-eab3-11e9-9164-ddbc8679cf61.png)
- Insecure HTTP Communication
![图片](https://user-images.githubusercontent.com/40814512/66465432-6cfbd600-eab3-11e9-82ca-939132b06e1e.png)
- Query Insecure Manipulation of Child Node
![图片](https://user-images.githubusercontent.com/40814512/66465455-75eca780-eab3-11e9-87c0-a9e06c2bc392.png)
- Insecure random number
![图片](https://user-images.githubusercontent.com/40814512/66465474-7d13b580-eab3-11e9-9a6c-25122aea46d9.png)

> Is this issue related to a specific component?
No.
> What did you expect to happen? What happened instead? What would you like to
> see changed?
No security issue reported by ASoC because we package carbon in our product.
> What browser are you working in?
N/A
> What version of the Carbon Design System are you using?
10.6
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Service Management Unite
## Steps to reproduce the issue
1. Login ASoC: https://cloud.appscan.com
2. Upload source code
3. Scan
4. Download report

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by abbeyhrt** [comment]
Hi @Bin-Xiong thank you for making this issue! We are not able to independently verify this as the logging into ASoC seems to be broken. Is this a blocking issue for your team and could you provide more context about ASoC?

**Comment by asudoh** [comment]
Had a chat with @Bin-Xiong yesterday, we saw that none of them is directly affecting his team, but we agreed that we avoid `Math.random()` usage for pre-caution.
