### ISSUE TITLE
The v10.6.4 tag does not match the v10.6.4 release

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4292]
If we view the v10.6.4 tag in GitHub we see the following class name: https://github.com/carbon-design-system/carbon/blob/v10.6.4/packages/components/src/components/file-uploader/_file-uploader.scss#L51

However, in our release, this is not present: https://unpkg.com/browse/carbon-components@10.6.4/scss/components/file-uploader/_file-uploader.scss

This issue is to determine the root cause of the tag generation issue and hopefully address it 👍

**Comment by joshblack** [comment]
cc @jnm2377 @abbeyhrt

**Comment by jnm2377** [comment]
hmm. Yeah I'm not sure how that got included. This is also the release that we had a lot of issues with (wrote up the post mortem). So do we just need to delete the tag and create a new one? @joshblack

**Comment by joshblack** [comment]
@jnm2377 yeah, that might be simplest way to revert the change.
