### ISSUE TITLE
[React] MultiSelect count of items selected through initialSelectedItems is wrong and other issues

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4297]
## What package(s) are you using?

- [x] `carbon-components-react` 7.8.0-alpha.5887

## Detailed description

MultiSelect is not showing correct count of initialSelectedItem, neither is it updating on the state update of the variable fed in initialSelectedItem.

## Steps to reproduce the issue

1. On page load, the count of initialSelectedItems is wrong (2 selected but the control shows 1).
2. None of the items are shown as selected in the expanded selection dropdown.
3. After 3 second of page load, the state used in initialSelectedItem is changed (count of selected items is changed from 3 to 2), however the change does not reflect in the control.

## Link for CodeSandBox

Please take a look at the codesandbox link to view the bug in action [CodeSandBox Link](https://codesandbox.io/s/codesandbox-nbxxn)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - As the name says, `initialSelectedItem` is for the initial state only and not for subsequent updates (which means programmatic control over the list of selected items). For such advanced use case, I'd suggest using the underlying presentational components behind `<MultiSelect>` for now (you'll need #4249 for that).

**Comment by tahaimt** [comment]
Are underlying presentational components exposed in recent versions?

**Comment by asudoh** [comment]
No, but feel free to enter a PR for that!
