### ISSUE TITLE
CheckmarkFilled icon is not filled on Windows

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#4302]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

The CheckmarkFilled icon is not filled.  I can repro in the Sandbox on Windows.  @alisonjoseph can not repro in Sandbox on Mac.

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.6.0",
    "carbon-components-react": "^7.6.0",
@carbon/icons-react@10.6.0.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of? OpenPages

## Steps to reproduce the issue

See code sandbox.  Looks fine to Mac users.  Not on Windows.
https://codesandbox.io/s/codesandbox-2y25j

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
can you provide more information on the issue you're seeing? this is what I see on windows

![image](https://user-images.githubusercontent.com/8265238/66658842-f0c6d700-ec07-11e9-804a-da49d80b6e2b.png)

**Comment by kglickman** [comment]
Sorry about this.  The button was not a good example.  It looks fine when I look at the icon by itself.  We had a merge conflict in our code, which caused my confusion.  You can close this.
