### ISSUE TITLE
Name of color palette

### ISSUE THREAD

**Issue by sethjohnsonIBM** [carbon-design-system/carbon#4312]
Having the color palette show up as **IBM_Colors_RGB_HEX_V02** in my application means... not much, and looks pretty janky. v02 is referring to what?

<img width="393" alt="Screen Shot 2019-10-11 at 6 51 11 PM" src="https://user-images.githubusercontent.com/32574988/66690818-301d1400-ec58-11e9-8d8b-67f05c97c03f.png">

<img width="428" alt="Screen Shot 2019-10-11 at 6 51 23 PM" src="https://user-images.githubusercontent.com/32574988/66690822-37442200-ec58-11e9-928d-26abdcdbd160.png">

**Comment by joshblack** [comment]
cc @carbon-design-system/design to help answer a question around color palette.

Note: who should we defer color questions to?

**Comment by laurenmrice** [comment]
The V02 refers to the new IBM color palette we just released. We could get rid of the `hex` part

**Comment by chrisconnors-ibm** [comment]
@sethjohnsonIBM you can resize the Color Picker Palette to accomodate the name:
![image](https://user-images.githubusercontent.com/35537391/66762500-1ce69000-ee74-11e9-8172-faaa488b67b4.png)

And you can rename the swatch:
![image](https://user-images.githubusercontent.com/35537391/66762606-528b7900-ee74-11e9-8efd-3fcc1c565fef.png)
![image](https://user-images.githubusercontent.com/35537391/66762673-6f27b100-ee74-11e9-8f79-36ada002c51e.png)

The decision to encode the version in the .clr filename was made to accomodate a shortcoming in ColorPicker: if you open a .clr file that's the same name it doesn't replace the swatch, it adds another swatch with a number after it. 
<img width="326" alt="Screen Shot 2019-10-14 at 11 25 57 AM" src="https://user-images.githubusercontent.com/35537391/66763217-77342080-ee75-11e9-90f7-de40414b7513.png">



To make sure people can determine they successfully added the newest, and to remove the older ones, we keep the version metadata in the filename, to hopefully make a little easier (possible) the (unavoidable) housekeeping after the fact.

**Comment by joshblack** [comment]
Would we want the above guidance to live anywhere?

**Comment by chrisconnors-ibm** [comment]
My concern was that I don't want us to be in the "how to work with macOS Color Picker" support business, but sure I suppose :) maybe as a "pro tip" or something

**Comment by chrisconnors-ibm** [comment]
@connor-leech fyi possible docs addition

**Comment by joshblack** [comment]
Closing as this seems resolved, let us know if you have any other questions @sethjohnsonIBM!!

**Comment by sethjohnsonIBM** [comment]
I was less concerned with how it looks and more concerned with the versioning. If Carbon is on v10 — shouldn't I expect one of its main components, the color palette, to be v10 as well? (Or, to put it another way: how do I know I have the most up-to-date color palette? v2 suggests I don't, since Carbon is on v10. Maybe I'm missing something!)

**Comment by chrisconnors-ibm** [comment]
Would naming it `IBM_Colors_RGB_HEX_V10.2.clr` make it clearer? Which would appear as IBM_Colors_RGB_HEX_V10.2 in the menu?
<img width="223" alt="Screen Shot 2019-10-14 at 2 32 52 PM" src="https://user-images.githubusercontent.com/35537391/66774455-963fac00-ee8f-11e9-9ea8-965d79d43102.png">

**Comment by sethjohnsonIBM** [comment]
Yes, that would help. I think it would also be useful if the Carbon site also labeled its elements with version numbers so the user doesn't have to download and look at the filename to know "what's the most current version of this element?" 

<img width="383" alt="Screen Shot 2019-10-14 at 2 05 39 PM" src="https://user-images.githubusercontent.com/32574988/66776386-dbfa7580-ee8b-11e9-8498-5fc2b6ea92b8.png">

<img width="1062" alt="Screen Shot 2019-10-14 at 2 05 48 PM" src="https://user-images.githubusercontent.com/32574988/66776392-def56600-ee8b-11e9-9cd0-4da52cd9003c.png">

**Comment by chrisconnors-ibm** [comment]
We can change the name of what the Zip Expands to easily but if we change the name of the actual binary file that is downloaded (`IBM_Colors.zip`), _every reference to it on every page in multiple, separate websites would require update whenever it was altered_.

**Comment by chrisconnors-ibm** [comment]
[Rename .clr, .ase files to include V10.x metadata in the expanded file's names ](https://github.com/carbon-design-system/carbon/issues/4393)
[Consider adding version, date modified data to resource tiles](https://github.com/carbon-design-system/carbon/issues/4394)

@sethjohnsonIBM the first is already in a PR.
