### ISSUE TITLE
Document requirements for IBM Digital Design

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4328]
This issue is for documenting the requirements that exist for the expressive theme as found by IBM Digital. Using the sketch file below, we'll capture all the differences that exist that we want to support for theming and document them to form an ad-hoc editorial theme.

Sketch file: [IBM Digital Design (Expressive White theme).sketch.zip](https://github.com/carbon-design-system/carbon/files/3726585/IBM.Digital.Design.Expressive.White.theme.sketch.zip)

Sketch file differences of Carbon and Digital:  https://ibm.ent.box.com/file/543750761684

**Comment by joshblack** [comment]
cc @laurenmrice let me know if you made one for this already!

**Comment by laurenmrice** [comment]
i didnt ! thanks for making this :)

**Comment by joshblack** [comment]
Some of the differences we're noting that might not need to be changed:

### Code Snippet

- In single line code snippet, the icon area should be flush to the panel unlike in multi line where there is separation

### Date Picker

- The calendar month header uses`expressive-heading-01`. We should use `productive-heading-01` and let them override to expressive.

### Data table
- The data table titles use `expressive-heading-04`. I think we should use `productive-heading-03` and adjust the value.
- The data table column headers use `expressive-heading-02`. We should use `productive-heading-01` with 16/22 values and let them override to expressive.

### File Uploader

- File Uploader label uses `expressive-heading-02`. We should use `productive-heading-02` and let them override to expressive.
- Digital will adopt our file invalid state.

**Comment by laurenmrice** [comment]
Made this audit between Digital and Carbon relating to what container sizes we may want to tokenize and which containers each component is using.

![Artboard](https://user-images.githubusercontent.com/43969356/67695337-dcf2d300-f972-11e9-8d93-3cc3f74f81a5.png)
