### ISSUE TITLE
Tabs/ContentSwitcher issue rendering in IE

### ISSUE THREAD

**Issue by Zack-Layne** [carbon-design-system/carbon#433]
## Detailed description
When using the Tabs component which calls on code from ContentSwitcher and evented-state, pages are unable to be rendered in Internet Explorer. 
Seems the use of CustomEvent (not supported in IE) in the evented-state class is the root cause. 
Also noticed that when CustomEvent issue is fixed (can polyfill the constructor functionality) tabs are not properly given event listeners, and in my case they are all set to selected. 

## Additional information
In IE, tabs can be seen not working here: http://carbondesignsystem.com/components/tabs/code

**Comment by tay-aitken** [comment]
@Zack-Layne also included these images in the email he sent us.

![m2](https://user-images.githubusercontent.com/29312997/32786852-a95d886c-c91a-11e7-95f9-b94caef6d3e0.png)
![m3](https://user-images.githubusercontent.com/29312997/32786855-a97e9a98-c91a-11e7-9d30-11f93f2dd018.png)

**Comment by tw15egan** [comment]
@asudoh, correct me if I'm wrong, but this is because we no longer bundle IE11 polyfills with the Vanilla repo? If so, @Zack-Layne that would most likely be the root cause of this issue

**Comment by Zack-Layne** [comment]
@tw15egan @asudoh If so, would this also be the cause for tabs in IE to not work properly when clicked? (As seen in link in description)

**Comment by tw15egan** [comment]
If it's not getting the polyfill, the javascript to handle toggling would not be working correctly, which would lead to the behavior you are experiencing. I'm not too familiar with how the polyfills work, however, so I'll defer that to @asudoh

**Comment by asudoh** [comment]
Right beginning V7 carbon-components does not include polyfills. See https://github.com/carbon-design-system/design-system-website/pull/88/files for the details. If http://carbondesignsystem.com/components/tabs/code is not working for IE11 it should be fixed.

**Comment by tw15egan** [comment]
@Zack-Layne can you confirm that this is an IE11 bug?

**Comment by Zack-Layne** [comment]
Yes in our current implementation we are unable to use the tabs component in IE. As seen in the Carbon Design sample.

**Comment by tw15egan** [comment]
Strange. Running the components locally, they work fine in IE11. The example on the website, however, does not seem to be working.

**Comment by Zack-Layne** [comment]
@tw15egan Not sure your thoughts on that issue. Seems like the Tabs component might not set the tab items to selected properly in IE?

**Comment by tw15egan** [comment]
I'm able to correctly switch tabs when I run the components locally and test them with BrowserStack running IE11. Which version of IE are you referring to?

**Comment by Zack-Layne** [comment]
I'm seeing the issue in IE11

**Comment by tw15egan** [comment]
Can you try pulling the components down locally and testing that those work for you as well? Might help determine if the problem is from the components or a missing polyfill

**Comment by Zack-Layne** [comment]
Just pulled and tested locally and it works fine for me as well.

**Comment by Zack-Layne** [comment]
Hey was wondering if you have a tentative date for this fix? Our team has already DCUT for GA release, so we are a bit short on time. Thanks

**Comment by asudoh** [comment]
Hi @Zack-Layne my apologies if things made you feel that we overlooked this issue. First, the fix for http://carbondesignsystem.com/components/tabs/code has been in https://github.com/carbon-design-system/design-system-website/pull/87, which I believe have been deployed to carbondesignsystem.com [as of November 17](https://github.com/carbon-design-system/design-system-website/pull/90).

The same fix has to be applied user-land. It means that your application needs to load the polyfills described in “Polyfills for older browsers” section of http://www.carbondesignsystem.com/getting-started/developers before loading Carbon JS code. Feel free to contact me if you need further help on this. Thanks!

**Comment by Zack-Layne** [comment]
Thanks so much for the help. We have loaded the polyfills, and everything seems to be working as expected!

**Comment by tw15egan** [comment]
That's great to hear, @Zack-Layne! I'm going to close this issue for now, but feel free to re-open it or submit a new issue if you run into any more problems 😄 Happy Thanksgiving!
