### ISSUE TITLE
Document situations where our component styles break with type changes

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4330]
After we complete #4328 and complete the work needed to check type styles in #4329, design and development on the Theming November 2019 project should go through and document each instance in our styles where component styles break when type styles have changed.

**Comment by joshblack** [comment]
### Summary

- body-long-01 -> 16/22
- code-02 -> 16/24
- Icons should grow
- Backgrounds should grow
- caption-01 stays the same
- label-01 stays th e same

---------------------------------------------------------------------------------------------------
### Accordion #4401

- Icon should be centered when the panel is closed, and stay in the same place when the panel is open.
- As text grows, panel size should grow
- Anything above 14/20 should go to 48px
- Icon size
  - 14/20 -> 16
  - Anything above goes to 20
- Spacing between panel title and body most likely needs to grow to 16

Questions:
- Where is the disabled story???
- Skeletons??? Should match exactly ours, or should it match type size?

---------------------------------------------------------------------------------------------------
### Breadcrumbs #4402

- ~~Separators should grow with type size~~ https://github.com/carbon-design-system/carbon/pull/4407

---------------------------------------------------------------------------------------------------
### Button #4403

- Type is growing but background size stays the same

48px button
- button should be 48px tall, it seems like border-width of 3px is causing it to be 50px, 16/22
- Icon grows to 20
- `body-short-01` at 16/22

40px button
- Icon grows to 20
- `body-short-01` at 16/22

---------------------------------------------------------------------------------------------------
### Checkbox

- Target area will increase to 20
- Text should be `body-short-01`16/22
- There should be the same 8px spacing between the target and the label
- Should we use the icons instead of doing it custom? (what was the original reason for doing custom?)

Questions:
- What should the size of the checkbox be?
- Checkbox groups story?

---------------------------------------------------------------------------------------------------
### Code snippet

- Single line
  - Overflow scrollbar breaking styles https://github.com/carbon-design-system/carbon/issues/2060
  - Icon grows to 20
  - Text should be `code-01` at 14/20 #4440
  - Size of code snippet background should go to 48

- Multi line
  - Icon grows to 20

- Inline
  - Size of inline code snippet background should go to 20
  - Text should be `code-01` at 14/20 #4440
  - Feedback is not relative to size https://github.com/carbon-design-system/carbon/issues/4463

---------------------------------------------------------------------------------------------------
### Content switcher

- Panel grows to 48 when type is larger than 14/20
- Panel should be 48
- Text should be `body-short-01` at 16/22
---------------------------------------------------------------------------------------------------
### Date picker

- The input backgrounds grow to 48
- Input text uses `code-02` at 16/24 #4440
- Open calendar panel stays the same size as well as the text
- Can we have icons in inputs disappear if text grows larger than 14/20?
- We are not going to use expressive-heading-01, they can override. Use `productive-heading-01` at 14/18

---------------------------------------------------------------------------------------------------
### Time picker

- Icons grows to 20
- Number input is `code-02` at 16/24 #4440
- Select 1 and 2 are `body-short-01` at 16/22
- Background goes to 48

---------------------------------------------------------------------------------------------------
### Dropdown

- Icon grows to 20
- Text is `body-short-01` at 16/22
- Background goes to 48 and background of each item is 48

---------------------------------------------------------------------------------------------------
### File uploader

- Carbon bug fixes https://github.com/carbon-design-system/carbon/issues/3587
  - [Bug] add files button goes to 48
  - [Bug] file added should be 40 height
- File itself goes up to 48
- Icons grow to 20
- Text goes to `body-short-01` at 16/22
- Digital will be following our invalid state

---------------------------------------------------------------------------------------------------
### Link

- ~~[Bug] `body-long-01` should be `body-short-01`~~ #4407
- If paired with an icon, should go to 20 with 8px spacing between text and icon

Questions:
- Icon paired with link

---------------------------------------------------------------------------------------------------
### List (Ordered and Unordered)

- [Carbon Bug #4433](https://github.com/carbon-design-system/carbon/issues/4433) ] should have 4px spacing between items
- Text should use `body-short-01` at 16/22
- Spacing should be the same once the carbon bug is fixed

---------------------------------------------------------------------------------------------------
### Loading

- Loader / icon size changes to 20

**Comment by emyarod** [comment]
~~add `productive-heading-03`, `productive-heading-03` tokens~~ #4387 
~~remove `expressive-heading` tokens~~ #4387 

### Modal 

* Not making this heading expressive-heading-04. Heading should be `productive-heading-03` 28/36, they can override to expressive.
* Body text should be `body-long-01` 16/24

---------------------------------------------------------------------------------------------------
### MultiSelect

* All icons grow to 20 (chevron, close, invalid)
* Input text and option text will be `body-short-01` 16/22
* Background goes to 48 and the background of each item is 48
* ~~close icon should be to the right of invalid icon in invalid state (Carbon bug #4418 )~~ #4419

---------------------------------------------------------------------------------------------------
### Notification

* Header should be `productive-01` 16/22. They can override to expressive.
* Subtitle should be `body-short-01` 16/22
  * If there is "action" button, same rule as subtitle text
* Close icon should be 20 (remove height and width rules) (Carbon bug) [#4436](https://github.com/carbon-design-system/carbon/issues/4436)
* ~~title should be using `productive-heading-01` (Carbon bug)~~ #4387

---------------------------------------------------------------------------------------------------
### Number input

* Icons go to 20 (up and down carets and alert icon for invalid state)
* Text should be `code-02` 16/24
* Background goes to 48

---------------------------------------------------------------------------------------------------
### Overflow menu

* Overflow icon goes to 20
* Text should be `body-short-01` 16/22
* Background of trigger button and options go to 48

---------------------------------------------------------------------------------------------------
### Pagination

* Text goes to `body-short-01` 16/22 
* Background size remains the same

---------------------------------------------------------------------------------------------------
### Progress indicator

* Text should be `body-short-01` to 16/22
* Icons go to 20

---------------------------------------------------------------------------------------------------
### Radio button

* Text should be `body-short-01` to 16/22
* Same spacing rules

---------------------------------------------------------------------------------------------------
### Select

* Inline variant broken (Carbon bug [#4423](https://github.com/carbon-design-system/carbon/issues/4423) https://github.com/carbon-design-system/carbon/pull/4465

* Text should be `body-short-01` 16/22
* Icons go to 20 (chevron, alert icon for invalid)
* Background goes to 48

---------------------------------------------------------------------------------------------------
### Slider
* Carbons number input and start/value text should use code-02 14/20 (Carbon bug #4425 )

* Text should be `code-02` 16/24
* Input field grows to 48
* Same spacing rules apply

**Comment by emyarod** [comment]
### Structured List
* ~~productive-heading-01 16/22 (Carbon bug -- we're using heading-01)~~ #4387
* Icons grow to 20 (checkmarks on selected and hover state)

--------------------------------------------------------------------------------------------------
### Tabs

* padding for content (Carbon bug [#4437](https://github.com/carbon-design-system/carbon/issues/4437) )
* ~~productive-header-01 16/22 (Carbon bug -- we're using wrong token)~~ #4387
* tab height grows to 48px

--------------------------------------------------------------------------------------------------
### Text area

* Text uses `body-short-01`at 16/22
* invalid state alert icon goes to 20

--------------------------------------------------------------------------------------------------
### Text input

* Input field goes to 48px
* Text uses `body-short-01` at 16/22
* Invalid state alert icon goes to 20
* Toggle password icon goes to 20

--------------------------------------------------------------------------------------------------
### Tile

* Icons go to 20 (checkmark for selectable state and chevron for expandable state)

--------------------------------------------------------------------------------------------------
### Toggle

Text next to toggles uses `body-short-01` at 16/22

--------------------------------------------------------------------------------------------------
### Tooltip

* Interactive tooltip
  * Text uses `body-long-01` 16/24
  * Inherit 16/22 link
  * Inherit 40px  button with 16/22 text

* Icon tooltip
  * Text uses `body-short-01` 16/22
  * Background increases to 28px

* Definition tooltip
  * Text uses `body-short-01` 16/22

--------------------------------------------------------------------------------------------------

TBD
### Data table

* table heading productive-heading-03 28/36
* table subtitle and cell text body-short-01 16/22
* column header/row height values (relationship between different heights/variants) TBD

**Comment by laurenmrice** [comment]
Sketch file for specs between Digital and Carbon: https://ibm.ent.box.com/file/543687227887

**Comment by laurenmrice** [comment]
**Priority list of components:**
* [ ] Button
* [ ] Link
* [ ] Tabs
* [ ] Checkbox
* [ ] Pagination
* [ ] Modal
* [ ] Tag
* [ ] Search
* [ ] Horizontal rule (dotcom library)  
* [ ] Tooltip
