### ISSUE TITLE
Customized theme tokens not being used for components

### ISSUE THREAD

**Issue by patricklowry** [carbon-design-system/carbon#4331]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

With `carbon-components` version `10.7.0` custom theme tokens are not being used for component styles, although they don't appear to be getting permanently reset. For example, if I set `$interactive-01` to `#ff0000` I would expect the primary button to be `#ff0000`. With `class="bx--btn bx--btn--primary"` the button is blue, but with a local class with the background-color set to `$interactive-01` the button is `#ff0000`.

> Is this issue related to a specific component?

It doesn't appear to be. I verified that it is an issue for buttons and accordions (having overridden `$focus`), which are imported sufficiently far apart for sampling.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the components to use the custom values that I set for the theme tokens. The components used the default theme values, although using the tokens in my own scss _did_ yield the correct values. I would like my custom theme to be used to style the components.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

`10.7.0`

## Steps to reproduce the issue

1. In a variables scss file (to be imported in the main scss file), import `@carbon/themes/scss/theme`
2. Set `$carbon--theme` to `$carbon--theme--g10`
3. Call `carbon--theme` mixin
4. Override the base theme, e.g. set `$interactive-01` to `#ff0000`
4. In the main scss file, import `carbon-components/scss/globals/scss/styles` after the variables import
5. Use a Carbon component that uses `$interactive-01`, create a local class that uses `$interactive-01`, and compare

## Additional information
Top button: `bx--btn bx--btn--primary interactive-01-button"` where that additional class (which I define) uses `$interactive-01` for the background color
Bottom button: `class="bx--btn bx--btn--primary"`
<img width="326" alt="Screen Shot 2019-10-14 at 8 03 58 PM" src="https://user-images.githubusercontent.com/18539365/66792703-eaff1900-eec7-11e9-98c0-66260959f737.png">

**Comment by patricklowry** [comment]
In light of this and https://github.com/carbon-design-system/carbon/issues/3570, would it be possible to create a deploy preview with Netlify that uses a custom theme? 

It could be something as simple as taking the base theme and overriding the tokens with obviously differing values for comparison. This may be helpful on pull requests that modify the theme, be it via the themes package or in carbon-components etc.

**Comment by joshblack** [comment]
Hi @patricklowry! :wave: Most likely this value is not being set in `$carbon--theme` which is what is causing the reset. The ideal way to update the theme would be:

```scss
$carbon--theme: map-merge($carbon--theme--white, (
  interactive-01: #ff0000,
));
@include carbon--theme();
```

Hope this helps!
