### ISSUE TITLE
Are there any sample usages in react for Triggering Filtering pattern : 

### ISSUE THREAD

**Issue by jagdishkumar1** [carbon-design-system/carbon#4332]
https://www.carbondesignsystem.com/patterns/filtering#triggering-filters 

Basically we want to achieve something like below:

<img width="68" alt="image" src="https://user-images.githubusercontent.com/2225196/66800126-ab6d1700-ef31-11e9-8b60-a688c7bb3089.png">

Clicking on above should open something like :
<img width="234" alt="image" src="https://user-images.githubusercontent.com/2225196/66800145-bd4eba00-ef31-11e9-871c-3114050721c0.png">

**Comment by jagdishkumar1** [comment]
@asudoh Any updates on this ?

**Comment by asudoh** [comment]
Hi 👋 probably you would start with http://react.carbondesignsystem.com/?path=/story/modal--default?

**Comment by prince737** [comment]
@asudoh You mean to modify modal's behaviour to suit the given requirement?

**Comment by asudoh** [comment]
Hi 👋 probably this clarifies some; We don't control the modal content. Applications can put in the stuff it desires.
