### ISSUE TITLE
[DataTable] Performance: Select All takes 5 - 30 s for tables with 1000+ rows

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#4338]
[DataTable] Performance: Select All takes 5 - 30 s for tables with 1000+ rows

https://codesandbox.io/embed/codesandbox-1lumy

For DataTable with 5000 rows and **only 10 rendered**, "Select All" (checkbox selection) takes **5 seconds**. You can play with MyDataTable.js (contructor) to change number of variables.
For 30000 rows it hangs for over **30 seconds**.

I'm assuming that this could be related with DataTable.setAllSelectedState implementation.
Maybe cloning using `JSON.parse(JSON.stringify(obj));` will be faster.

## What package(s) are you using?

    "carbon-components": "10.7.0",
    "carbon-components-react": "7.7.0",
    "carbon-icons": "7.0.7",
    "@carbon/layout": "10.5.0",
    "@carbon/themes": "10.7.0",

## Steps to reproduce the issue

1. Go to codesandbox I've created 
2. Try to select or unselect "Select all" checkbox (table header)

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/embed/codesandbox-1lumy

**Comment by asudoh** [comment]
Great if somebody can try simple `for` loop or a like that doesn't require rest/spread for each row.

**Comment by tomkdgun** [comment]
Any update on this issue ?

**Comment by ljitendra** [comment]
For a DataTable with radio selection having multiple columns having their own cell renderers, it takes more than 60 seconds to load 15000 rows. And the page becomes responsive. Need to check this scenario as well when defect is being addressed.

**Comment by tymerica** [comment]
This is happening on production builds on our system, 4.5k items causes 15 seconds on my computer but on weaker computers it just locks up for minutes

**Comment by dezkareid** [comment]
did you try react-virtual?

**Comment by tomkdgun** [comment]
We had pagination with only 30 items displayed, so problem is with some internal state handling inside DataTable.
