### ISSUE TITLE
[DataTable]: Header expands on Firefox past it's line height if the table has a height applied

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#4339]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If I set a height on the datatable in firefox, the header expands.  This doesn't happen in Chrome

> Is this issue related to a specific component?
[DataTable]

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Consistent behaviors between Chrome and Firefox

> What browser are you working in?
Firefox

> What version of the Carbon Design System are you using?
I've tried this usecase on both v7 and v6 react

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Open this code sandbox in both Firefox and Chrome and notice the difference:
https://codesandbox.io/s/reverent-jennings-p7gxx
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information
![image](https://user-images.githubusercontent.com/6663002/66848562-ed4e8b00-ef3a-11e9-9dbc-dee18b460807.png)

**Comment by andreancardona** [comment]
@scottdickerson Hi Scott! I know this is quite late but I wanted to get you a response as well as to the fix that was included in this issue. 

We do recommend using custom CSS styles to target the specific element. One way to test this is by targeting the `TableHeader` component. You can see below screenshots of both the Chrome & FF examples: 

Chrome: 
<img width="1340" alt="Screen Shot 2020-07-07 at 9 48 12 AM" src="https://user-images.githubusercontent.com/32720851/86791385-78c2fb80-c037-11ea-964a-04ad73e23d15.png">


Firefox: 
<img width="1437" alt="Screen Shot 2020-07-07 at 9 49 00 AM" src="https://user-images.githubusercontent.com/32720851/86791413-7fea0980-c037-11ea-9fca-a44aff1a5ab7.png">

Please let us know if you have any other questions! Closing issue.
