### ISSUE TITLE
Styles - incorrectly passing hex values (instead of rgb values) to rgba() color function 

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4345]
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

The `rgba()` color function accepts rgb values, not hex codes (see: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value). For example:

```css
// this is valid:
color: rgba(0, 0, 0, 0.5);

// this is invalid:
color: rgba(#000000, 0.5);
```

There are a couple places where theme tokens, which are almost all hex code values, are being passed into the `rgba()` function in order to create an overlay effect:

![Screen Shot 2019-10-15 at 3 52 50 PM](https://user-images.githubusercontent.com/9057921/66869246-91006100-ef64-11e9-9853-baf11bb51279.png)

I addressed the `CodeSnippet` one indirectly here, with the `light` styles refactor: https://github.com/carbon-design-system/carbon/pull/4342#pullrequestreview-302137223

However for those other components shown in the screenshot, the desired overlays are not taking effect. You can see this happening for the `Loading` overlay, for example, if you look at storybook (http://react.carbondesignsystem.com/?path=/story/loading--default), enable the `withOverlay` prop in the knobs, and just add some content behind it:

![Screen Shot 2019-10-15 at 4 03 38 PM](https://user-images.githubusercontent.com/9057921/66869610-5fd46080-ef65-11e9-85f7-e8205b76e713.png)

And if you update the background color to a valid rgb value, you get the right overlay --

![Screen Shot 2019-10-15 at 4 04 34 PM](https://user-images.githubusercontent.com/9057921/66869706-8abeb480-ef65-11e9-9e4e-98703e753bfc.png)

## Proposed solution
It's worth noting that there is currently only one `$overlay-01` token, and it's pretty dark. In the `Loading` component example above, it wouldn't work well for any of the themes (it would look like a `Modal` overlay color, which doesn't seem like the intention here?)

And it wouldn't make sense to turn these `rgba()` color function calls to use hard-coded `rgb` values, due to theming.

So IMO that leaves one option...

### Add a new `$overlay-02` token that is a "lighter" overlay.
That would take care of the `Loading` overlay for sure 🤔 And perhaps any others in the future. (Any component needing a dark overlay color can use `$overlay-01`? Unless that's not dark enough for some of these components? 😅 )

**Comment by joshblack** [comment]
@jendowns are you noticing this with our CSS Custom Properties flag enabled? I thought by default sass transforms `rgba(hex, alpha)` to the appropriate representation?

![image](https://user-images.githubusercontent.com/3901764/66933245-6c58c780-effe-11e9-8e72-a3e92b200173.png)

**Comment by jendowns** [comment]
@joshblack It looks like we aren't setting the custom properties flag at all 🤔 (So whatever the default is, that's what we get, I believe)
Though in the example above, I was seeing that in the `carbon-components-react` storybook environment. (In the case of the `Loading` overlay color, with the custom properties flag updated, would that color show up?)

**Comment by joshblack** [comment]
@jendowns right, we actually are using the CSS Custom Properties flag under the hood which is causing this 😬 So thankfully won't impact anyone using stable carbon today

**Comment by joshblack** [comment]
Going to close this out in favor of #4426 that we're using to track this 👀
