### ISSUE TITLE
[eslint-config-carbon]: latest changes not released to npm

### ISSUE THREAD

**Issue by scottnath** [carbon-design-system/carbon#4350]
## What package(s) are you using?

- [x] `eslint-config-carbon`

## Detailed description

The latest changes to the eslint config package don't seem to have been released to NPM.

last changed three months ago:
https://github.com/carbon-design-system/carbon/tree/master/packages/eslint-config-carbon

last release 2 years ago:
https://www.npmjs.com/package/eslint-config-carbon

## Question

I noticed this module is not used by any current carbon packages. Are the rules still valid for code produced by Carbon? If not, are there current rules which Carbon uses which can be used by other teams?

thanks!
Scott

**Comment by joshblack** [comment]
Hi @scottnath! 👋 We just use this package internally for linting and weren't intending on publishing it, specifically in:

https://github.com/carbon-design-system/carbon/blob/ac0bfd6ae8a60004c08072ba1127bea1fb38e81b/package.json#L130-L134

**Comment by scottnath** [comment]
Hi @joshblack 

As this module is already published by Carbon, could changes to this package please continue to be released to the already-existing NPM module?

We still use this set of rules in our code. It's important for us so that we can ensure the code we write is linted to the expected specifications of Carbon development. This makes it less time consuming to contribute back to Carbon among many other reasons.

It also looks like the module has been exponentially gaining popularity since August, so it would stand to reason that we're not the only team who would like our code to be written according to Carbon's specifications.

cheers

**Comment by joshblack** [comment]
@scottnath it's definitely a tough situation from my perspective, the npm package was last published two years back by the prior group of developers for use in repos under the org at the time. It wasn't until recently with the monorepo push that we finally consolidated rulesets for this specific repo. 

Really the only concern with publishing it is maintaining semver, I wasn't sure if that came across so just wanted to make that clear. We're trying to fix our current release process to make sure we're following semver and I hope you understand why we'd be hesitant to add more surface area to that process given our current state.

**Comment by scottnath** [comment]
Thanks @joshblack ...does this mean you're keeping the number of released packages low, or specifically that the existing `eslint-config-carbon` package is in a state that would make it difficult to release?

If it's the latter...possible to create a _new_ module to release the Carbon ruleset? (asking cause we are currently adding more ES6 to our repo and those new files are showing the cracks in the existing rules so we gotta figure out a new set.)

If it's the former...when Carbon's semver/release process is ironed out, do you plan to re-institute releases of the  `eslint-config-carbon` module?

**Comment by joshblack** [comment]
@scottnath definitely just trying to keep released package count low so our release surface area is smaller. Definitely could see it being public in the future, potentially alongside a style guide, but don't have any plans until we feel solid in our core releases.
