### ISSUE TITLE
Time picker issue

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#4352]
@alisonjoseph @joshblack 
I made this issue once before but cannot locate it so making a new one. It’s been like this for months now. Mobile view is likely not a priority but this needs to be addressed regardless.

 1. Time Picker hh:mm getting cropped on left side (see image below)
— Safari (Version 12.1.2) and Chrome (Version 77.0.3865.90)
— iPhone 10 Safari and Chrome

<img width="419" alt="Screen Shot 2019-10-16 at 10 09 28 AM" src="https://user-images.githubusercontent.com/32881239/66932694-9d84c800-effd-11e9-9415-9135886cff12.png">

————
~2. In mobile the components are broken in "Single date picker" and "single no date picker"~
— type not appearing 
— icon cropped
— default looking iOS

![IMG_4546](https://user-images.githubusercontent.com/32881239/66932798-c60cc200-effd-11e9-8798-f0d9d97414cc.jpg)

![IMG_4547](https://user-images.githubusercontent.com/32881239/66932799-c60cc200-effd-11e9-87cc-4970dc58be29.jpg)

**Comment by aledavila** [comment]
This is a vanilla issue or a website issue as its not present on mobile react. The only issue left is the Time Picker component time is not centered.

**Comment by aledavila** [comment]
No longer an issue
