### ISSUE TITLE
[Icons] Add new and remove deprecated icons into the sketch plugin

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4357]
Get these into the sketch plugin
Generate these assets from the plugin and into the idl sketch kit/icon kits:
- [x] Add new icons
- [ ] Remove deprecated icons
- [ ] Update edited icons

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Just sent over a quick sanity check sketch file to @laurenmrice!

**Comment by laurenmrice** [comment]
Went through all the icons

Here are some bugs that are not in other issues we have open. Wanted to document them all in one place here:

-------------------------------------------------------------------------------------------------

- [x] `32/MP4` (all sizes)
No fill on the 4
<img width="270" alt="Screen Shot 2020-03-20 at 9 35 04 AM" src="https://user-images.githubusercontent.com/43969356/77173818-19dc7500-6a8e-11ea-92cd-d14b0139577d.png">

-------------------------------------------------------------------------------------------------

- [x] `32/accessibility--color--filled` (all sizes)
No inverse eye visible
<img width="272" alt="Screen Shot 2020-03-20 at 9 39 46 AM" src="https://user-images.githubusercontent.com/43969356/77174381-f7972700-6a8e-11ea-9607-0979fc390a71.png">

-------------------------------------------------------------------------------------------------

- [x] `32/Q/composer-edit` (all sizes)
Multiple artboards of same icon for all sizes
<img width="920" alt="Screen Shot 2020-03-20 at 9 59 39 AM" src="https://user-images.githubusercontent.com/43969356/77176204-beac8180-6a91-11ea-8fef-842fdf65ce19.png">

 -------------------------------------------------------------------------------------------------

- [x] `32/task--view` (all sizes)
Inner fill not showing in eye
<img width="267" alt="Screen Shot 2020-03-20 at 1 19 34 PM" src="https://user-images.githubusercontent.com/43969356/77194188-7b600c00-6aad-11ea-8441-1e3644b8594e.png">

-------------------------------------------------------------------------------------------------

- [x] `32/thunderstorm--severe` (all sizes)
Inner fill not showing in warning icon
<img width="256" alt="Screen Shot 2020-03-20 at 1 24 40 PM" src="https://user-images.githubusercontent.com/43969356/77194608-499b7500-6aae-11ea-9460-953c29bd78af.png">

-------------------------------------------------------------------------------------------------

- [x] `32/user--x-ray` (all sizes)
Inner fill not showing in box
<img width="249" alt="Screen Shot 2020-03-20 at 1 31 18 PM" src="https://user-images.githubusercontent.com/43969356/77195109-19080b00-6aaf-11ea-8cce-d4f6db284b1c.png">

-------------------------------------------------------------------------------------------------

**Comment by laurenmrice** [comment]
Also I have a question about duplicate icons. I noticed in places we have the same icon set that have different naming conventions and live in different categories. Was wondering if that's a mistake and we need to:

1. make sure the two are the same (file/paths etc)
2. add ’duplicate` to deprecated.yml
3. but we leave both for now so anyone using ‘duplicate’ doesn’t get broken

Some examples are:
- [x] `32/checkbox--indeterminate` vs `32/checkbox--undeterminate` (deprecated undeterminate)
- [x] `32/sun` vs `32/sunny` (ddeprecated sunny)
- [ ] `32/misuse--alt` vs `32/misuse--outline`
- [x] `32/arrows--vertical` vs `32/arrows` (deprecated arrows)

**Comment by laurenmrice** [comment]
Looks like all that is left to solve in this issue is:

- [x] deprecate`misuse--alt` in favor of misuse--outline 
- [x] deprecate`edit--filter` in favor of filter--edit

Almost there!
