### ISSUE TITLE
$ui-03` and `$ui-02` are the same in dark themes

### ISSUE THREAD

**Issue by johnjesse** [carbon-design-system/carbon#4362]
## What package(s) are you using?

- [x] `carbon-themes`

## Detailed description
From https://www.carbondesignsystem.com/guidelines/color/usage
`$ui-02` is the token for "primary page background" or "secondary container background"
`$ui-03` is the token for "tertiary container background"

In the dark themes - Gray 90 and Gray 100 - these tokens refer to the same color. This seems like a bug, as you cannot use a tertiary container on the page background... or on a secondary background

This bug manifests itself in the data-table component - where the header background color is `$ui-03` - which won't show up in dark themes :(

There was a similar bug raised here #2439  which has since been closed, which is why I'm opening this new bug

Also - it was discussed somewhat on slack too, but only really relating to border colors - see https://ibm-security.slack.com/archives/C0M053VPT/p1570692607023400

**Comment by johnjesse** [comment]
We could really do with getting a response to this... we are shipping a product soon with these themes and it doesn't work as intended 

See - panel header on light theme using ui03 - as per data table component
![image](https://user-images.githubusercontent.com/6839660/67282092-d2df5900-f4c8-11e9-95aa-9256a93ea3b5.png)


Same thing in the dark themes using ui03 - as per data table component
![image](https://user-images.githubusercontent.com/6839660/67282134-edb1cd80-f4c8-11e9-91c6-820d9e01ffa3.png)

**Comment by abbeyhrt** [comment]
We're going to address this in the original issue that is now reopened (#2439) since it contains more context. Closing this to remove any duplicates.
