### ISSUE TITLE
DataTable: disabled styles are missing

### ISSUE THREAD

**Issue by sabov** [carbon-design-system/carbon#4364]
### Summary

Sketch library allows to use disabled cells: 
<img width="747" alt="Screenshot 2019-10-17 at 15 26 11" src="https://user-images.githubusercontent.com/1277720/67012889-778d1f80-f0f2-11e9-9aab-8d38a49e272e.png">

However, these styles are not available in the `DataTable` component. 

Only development is required. 

### Justification

We need a way to show that some rows are not selectable.

### Desired UX and success metrics

Users can understand that a row/cell is not selectable.

### Available extra resources
Theme libraries
https://www.carbondesignsystem.com/resources#theme-libraries

**Comment by josh-tt** [comment]
This is not stale. Sketch libraries show states for the tables, but there are no examples I can find in code on Carbon site.
