### ISSUE TITLE
Data table header is not vertically aligned with row cells

### ISSUE THREAD

**Issue by vladbalanescu** [carbon-design-system/carbon#4366]
## Title line template: The data table header is not vertically aligned with the row cells content, please see the image below for more info
![image](https://user-images.githubusercontent.com/16047402/67018255-dfdc0100-f0f2-11e9-99c5-1691f97587e2.png)

## What package(s) are you using?

We are using `carbon-components-react v7.7.0` and `carbon-component v10.0.0`

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> This is happening on all browsers and in order to replicate the issue you just need to use the `DataTable` component with sorting capabilities

## Important 
There's been no CSS styling added to the actual `DataTable` element itself, please see the below code-snippet for confirmation:

```
<PlatformContext.Consumer>
  {context => (
    <React.Fragment>
      <TableToolbar>
        <TableToolbarContent>
          <TableToolbarSearch />
        </TableToolbarContent>
      </TableToolbar>
      <DataTableSkeleton />
    </React.Fragment>
    <DataTable
      rows={tableRows}
      headers={headers}
      sortRow={customSortRow}
      render={({ rows,
        headers,
        getHeaderProps,
        getRowProps,
        onInputChange
      }) => (
        <React.Fragment>
          <TableToolbar>
            <TableToolbarContent>
              <TableToolbarSearch onChange={onInputChange} />
              <div className='bx--toolbar-action'>
                <OverflowMenu className='bx--filter-menu' renderIcon={Filter16} flipped >
                  <ToolbarTitle title='Capability types' />
                  <ToolbarOption>
                    <Checkbox id='apiconnect' labelText={i18n.components.api_lifecycle.category} onChange={this.capabilityApplied} checked={this.state.capabiltyFilters.indexOf('apiconnect') > -1} />
                  </ToolbarOption>
                </OverflowMenu>
              </div>
            </TableToolbarContent>
          </TableToolbar>
          <Table>
            <TableHead>
              <TableRow>
                {headers.map(header => (
                  <TableHeader {...getHeaderProps({ header, isSortable: true })}>
                    {header.header}
                  </TableHeader>
                ))}
                <TableHeader />
              </TableRow>
            </TableHead>
            <TableBody>
              {this.paginateData(rows).map((row, index) => {
                return <TableRow key={index} {...getRowProps({ row })}>
                  {row.cells.map(cell => (
                    <TableCell key={cell.id}>
                      {cell.value}
                    </TableCell>
                  ))}
                  <TableCell>
                  </TableCell>
                </TableRow>
              })}
            </TableBody>
          </Table>
        </React.Fragment>
      )}
</PlatformContext.Consumer>
```

**Comment by asudoh** [comment]
Hi 👋 `v10.0.0` of `carbon-components` sounds quite old. Would you want to try `v10.7.0`?

**Comment by vladbalanescu** [comment]
![image](https://user-images.githubusercontent.com/16047402/67197883-aeff1300-f3f5-11e9-8198-6a8573de54d9.png)

@asudoh I just updated to the latest version, which is `v10.7.0` and I can see by default you're adding a `padding-left: .75rem` which then it gets overriden by `padding-left: 1rem` inside the `<td>` element

**Comment by asudoh** [comment]
In case you are saying your problem was not solved with `v10.7.0`, would you try making sure your React code matches the code seen at https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/DataTable/stories/default.js?

**Comment by tom-youd** [comment]
So this seems to be an issue with the sorting...The minute we add the isSortable property the padding is added to the headings. Is there a reason why the padding is required? 
![Screenshot 2019-10-22 at 09 03 53](https://user-images.githubusercontent.com/56865994/67269170-1a0c2080-f4ae-11e9-91fb-f4eff699e95d.png)

**Comment by asudoh** [comment]
Would you take a look at http://react.carbondesignsystem.com/?path=/story/datatable--with-sorting?

**Comment by tom-youd** [comment]
I copied the render function from here - https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/DataTable/stories/with-sorting.js
Then put it into our application and the styles are still off...see below
![Screenshot 2019-10-23 at 14 01 07](https://user-images.githubusercontent.com/56865994/67395663-4a32ec80-f59e-11e9-9b09-892664cb3d26.png)

Is there a newer/different version of carbon we should be using
We are currently using - 
```
    "carbon-components": "^10.7.0",
    "carbon-components-react": "^7.7.0",
```

**Comment by asudoh** [comment]
Would you want to clone this repo and check out `v10.7.0`, then run:

```sh
> yarn install
> yarn build
> cd packages/react
> yarn storybook
> open -a 'Google Chrome' 'http://localhost:9000/?path=/story/datatable--with-sorting'
```

To and see the difference in computed styles (in Chrome DevTools) between your app and our storybook?

**Comment by tom-youd** [comment]
After doing a diff against the storybook code and our code, there was a prop missing against the DataTable component....isSortable.
This seems to have resolved the problem, but would be interested to know what this does, is it adding more classes to certain elements?

**Comment by asudoh** [comment]
Cool, `isSortable` for enabling the sortable version of table header column's UI.

**Comment by vladbalanescu** [comment]
@asudoh You cannot close this issue as this is not resolved. What is the reasoning behind adding a css rule once you add that redundant `isSortable` property on the `DataTable`. It would be nice to know what's causing this padding to appear once the property is not added and a fix should be implemented because this shouldn't happen by including/excluding a property

**Comment by asudoh** [comment]
Given the problem you described is not seen at http://react.carbondesignsystem.com/ - Would you want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?
