### ISSUE TITLE
IE Rendering Issues with Tabs and ContentSwitcher

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#437]
_From the initial report:_

> I am writing to see if there are any known issues with Internet Explorer and some of the Carbon Components. In our product we use the new Tabs component, and have since not been able to render our UI in IE. Looking through the code it seems Tabs calls on code from content-switcher and evented-state, and becasue evented-state uses the following: 

![image](https://user-images.githubusercontent.com/3901764/32857475-9351da8e-ca0d-11e7-999a-2d5fca848dc3.png)

> it is not rendered, as CustomEvent is not supported in IE.

> I used a polyfill to work around this issue, and although the page would now render properly, all of the tab items were styled as selected and were not linked to anything on a click event.

> Just wondering if this is a known problem, or if it is most likely a misuse on our end.

**Comment by tay-aitken** [comment]
Hey @joshblack this issue was already created, issue #433. Going to close this one and continue tracking it there.
