### ISSUE TITLE
Carry over showing selected option in Dropdown from React

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#4371]
## What package(s) are you using?
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The React dropdown shows the selected option within the dropdown menu list.  This functionality should be in Carbon Vanilla for consistency

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Behavior in https://github.com/carbon-design-system/carbon/issues/1936 also is in Vanilla

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.6.4

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. Select an option in the dropdown
2. the options should remain visible in the menu list

## Additional information
@carbon-design-system/developers We have a patch for this in WH that we can contribute to Vanilla if this is assigned to me

**Comment by asudoh** [comment]
@elizabethsjudd Thank you for your willingness for contribution 🎉 !  One question; Does your code have backward-compatibility? Which is, existing application works as-is, and your fix applies only to applications who chooses newer selection option?

**Comment by elizabethsjudd** [comment]
@asudoh I didn't realize that the React version had the option any more to not have the selected item display which is why I labelled this as a bug and was just going to update the stylings but we can certainly add a new class to the dropdown that when applied will this do this update.

**Comment by asudoh** [comment]
You are right, at the beginning of `v10` React shipped with the new selection model while vanilla shipped with old selection model. Thinking of ensuring no sudden UI change happens with minor release.
