### ISSUE TITLE
Carbon in AngularJS

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#438]
_From the initial report_:

> I'm trying to integrate the use of carbon design into a portal that is built using AngularJS (1.x). I've included the `./node_modules/carbon-components/scripts/carbon-components.min.js`
and
`"./node_modules/carbon-components/css/carbon-components.min.css"`

> However, my initial component (date picker) is not being triggered. I'm also missing the calendar icon. Can you tell me if I need to do anything on my angular ctrl, once the SPA view loads?

![image](https://user-images.githubusercontent.com/3901764/32857649-1ffdea5e-ca0e-11e7-828f-8ac4f77bfb7a.png)

**Comment by javadude24** [comment]
I think issue is related to loading the template for view (in SPA) that contains the carbon component. I had loaded the carbon-components.min.js in the main index.html. So, I see there is a way to disable autoInit (CarbonComponents.settings.disableAutoInit = true), but is there a function I can call when my Angular CTRL loads?

**Comment by tw15egan** [comment]
@javadude24 you should be able to disable the auto init, then init it yourself by following something like this example: https://codepen.io/team/carbon/pen/BwjZZN

**Comment by javadude24** [comment]
@tw15egan: I think the key thing in that example is 
CarbonComponents.ProgressIndicator.init();  Correct?

I've even tried adding this to my initial index.html, after ./node_modules/carbon-components/scripts/carbon-components.min.js is loaded and it cannot find CarbonComponets
<script>
	CarbonComponents.settings.disableAutoInit = true;
</script>

**Comment by asudoh** [comment]
@javadude24 `carbon-components.min.js` defines global `CarbonComponents` object. If you cannot find the global object then `carbon-components.min.js` is not loaded property or has not been loaded.

BTW - The best practice using a JavaScript framework with our vanilla `carbon-components` is creating “wrapping components” described in the very bottom section in: http://www.carbondesignsystem.com/getting-started/developers

For Angular1/`DatePicker` particular case, you can refer to: https://codepen.io/asudoh/pen/OOOMdB

**Comment by javadude24** [comment]
@asudoh The Angular1/DatePicker codepen helped and my issues resovled. Thanks

**Comment by tw15egan** [comment]
Thanks for checking back in with us, glad your issue is resolved!
