### ISSUE TITLE
Datatable id property

### ISSUE THREAD

**Issue by windgaucho** [carbon-design-system/carbon#4380]
- [x] `carbon-components`
- [ X] `carbon-components-react`

Is any way to use an int id in as a row key identifier a Datatable ?

**Comment by asudoh** [comment]
Hi 👋 I suggest you convert the data to make ID string before sending it to our data table.

**Comment by windgaucho** [comment]
Yes I am already doing that way, but I wanted to know if it was a restriction or may be I was doing somthing wrong.
Thanks.
