### ISSUE TITLE
MultiSelect using lodash.isequal for initialSelectedItems

### ISSUE THREAD

**Issue by GabrieleBarboni** [carbon-design-system/carbon#4383]
## What package(s) are you using?

- [X] `carbon-components` 9.91.3
- [X] `carbon-components-react` 6.115.4

## Detailed description

Using lodash.isequal for checking initialSelectedItems does not allow to specify only the id of the initial selected items, but the whole object is required, including text field.
This result in issues with globalization for initial selected items, since the same items (same id) but with different text field (due to globalization) will not be selected as initial selected items. 

> Is this issue related to a specific component?

MultiSelect

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like to pass as initialSelectedItems only the list of the ids of the items

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - As you reviewed the code, you can see that our `<MultiSelect>` merely is a wrapper of Downshift library. That said, you can create your own variant of `<MultiSelect>` that meets your needs. I personally would be open for introducing comparer as a prop, a PR is welcome.

**Comment by GabrieleBarboni** [comment]
Hi,
I have created the comparer as a prop but I'm not authorized to upload the branch and create a pull request. Any help on this?
remote: Permission to carbon-design-system/carbon-components-react.git denied to GabrieleBarboni.

**Comment by asudoh** [comment]
You can fork this repo: https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#start-contributing
