### ISSUE TITLE
onClose event handler missing on DatePicker (carbon-components-react 6.x branch)

### ISSUE THREAD

**Issue by GabrieleBarboni** [carbon-design-system/carbon#4384]
## What package(s) are you using?

- [X] `carbon-components` 9.91.3
- [X] `carbon-components-react` 6.115.4

## Detailed description

onClose event handler missing on DatePicker

> Is this issue related to a specific component?

DatePicker

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Add onClose event handler on DatePicker on carbon-components-react 6.x branch
Latest: https://github.com/carbon-design-system/carbon-components-react/blob/v6.116.1/src/components/DatePicker/DatePicker.js

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - A PR porting #3300 to `6.x` is welcome. BTW the repo will be https://github.com/carbon-design-system/carbon-components-react.

**Comment by jaknas** [comment]
Hey there @asudoh , I've made a PR for this issue at https://github.com/carbon-design-system/carbon-components-react/pull/2422, hope that's fine 😃

**Comment by emyarod** [comment]
closed via https://github.com/carbon-design-system/carbon-components-react/pull/2422
