### ISSUE TITLE
Select Component is not updating to hidden value after state update

### ISSUE THREAD

**Issue by geoangelotti** [carbon-design-system/carbon#4385]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

After clicking submit in a Form the Select Component has the last picked value and not the value from the state that was updated.

> Is this issue related to a specific component?

Yes it is an issue with the Select Component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected that the Select Component would reset to the hidden value.

> What browser are you working in?

I am working on Firefox 70.0.0 (64-bit).

> What version of the Carbon Design System are you using?

`"carbon-components-react": "^7.6.4"` from package.json

## Steps to reproduce the issue

1. Select a scope _//Submit button is inactive if no selection_.
2. Click Submit.
3. See on Console that the state is updating but the Select is not updating to the hidden value SelectItem.

[Sandbox](https://codesandbox.io/embed/codesandbox-72kq6)

## Additional information
_no additional info_

**Comment by abbeyhrt** [comment]
Hi 👋@geoangelotti. thanks for making this issue! Taking a look at your sandbox, it seems like Select is mirroring the value that state is set to, could you help me understand what needs to change?

**Comment by aledavila** [comment]
Closing as we haven't received a response. Feel free to open if more information can be provided. Thanks!
