### ISSUE TITLE
tooltip position on small viewports is incorrect

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#4388]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Tooltips that are near the right edge of small viewports have incorrect position.  There are a few different options with this from a UX perspective:
- the tooltip would extend past the right edge of the viewport and the user would need to scroll
- the caret shifts using JavaScript so that it's aligned with the trigger even if it's not perfectly centered on the tooltip.

This is happening in both the React and Vanilla versions of Carbon.

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The tooltip should look like it's aligned properly with the trigger

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.7.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. tooltip trigger should be centered in a small viewport
2. open the tooltip
3. see the misalignment of the caret with the trigger

## Additional information
Was able to use Carbon's default codepen and storybook examples to re-create the issue

<img width="1440" alt="Screen Shot 2019-10-18 at 10 27 32 AM" src="https://user-images.githubusercontent.com/1275779/67103435-1cf7d000-f193-11e9-99ef-921e6424dcc6.png">
<img width="1439" alt="Screen Shot 2019-10-18 at 10 29 03 AM" src="https://user-images.githubusercontent.com/1275779/67103437-1cf7d000-f193-11e9-863d-ec38fe0a9a60.png">

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon/issues/4252

**Comment by emyarod** [comment]
closing in favor of #4252
