### ISSUE TITLE
Datatable filter with pagination

### ISSUE THREAD

**Issue by windgaucho** [carbon-design-system/carbon#4389]
- [x] `carbon-components`
- [ X] `carbon-components-react`

I am using the DataTable with Pagination components and the TableToolbarSearch. 
I have many pages of rows but the filter is doing the search only in the current page, is any way to search in all of the pages? 
Is any way to execute a server search using the TableToolbarSearch ?

**Comment by nictownsend** [comment]
The `<TableToolbarSearch>` has an `onChange` method. Rather than hooking that into the `onInputChange` render prop in the `<DataTable>` you can instead use it to fire a server search instead - and use that to update the set of results you are paginating over.

**Comment by bitfede** [comment]
Your approach makes sense @nictownsend ,but if I have certain selected rows that I want to keep selected, updating the data to render in the table will make me lose the selection every time I apply a new search/filter correct?

**Comment by nictownsend** [comment]
When you updated the data in the table - each row data object can have a `selected` property set - so if you maintain your list of "selected" outside of the table, when you need to render a new set of data you just need to preprocess it to add the selected property to rows.
