### ISSUE TITLE
Side panel

### ISSUE THREAD

**Issue by windgaucho** [carbon-design-system/carbon#4397]
- [ ] `carbon-components`
- [X ] `carbon-components-react`

Hello, in the experimental section in https://www.carbondesignsystem.com there is a Create flows page that show a basic creation flow pattern using a Side Panel. I tried to find the Side Panel component but I can't find it, there is such component or any plan to include it in the framework?

**Comment by zigzactly** [comment]
I have this same question for creation workflow type screens. Seems like its still experimental.

Just in case anyone stumbles on this, AFAIK there is a Header Panel that kind of achieves a side panel but not quite.

Also, a modified modal might be able to achieve the same effetc.
