### ISSUE TITLE
Add or fix missing prop types for components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4398]
While doing a `propType` audit of the codebase, I came across several components that were seemingly missing `propTypes` definitions or were written in a way such that they were not statically accessible for auditing. This issue is to address ones where they make sense, particularly for components that have no prop type information.

Missing prop types and should be added:

- [x] `TableExpandHeader`
- [x] `TableToolbar`
- [ ] ~`BreadcrumbSkeleton`~
- [ ] ~`CheckboxSkeleton`~
- [ ] ~`FileUploaderSkeleton`~
- [ ] ~`ProgressIndicatorSkeleton`~
- [x] `RadioButtonSkeleton`
- [ ] ~`TabsSkeleton`~
- [ ] ~`TagSkeleton`~

Missing propTypes due to how the component is exported (either IIFE or `React.forwardRef`):

- IIFE
  - [ ] `NumberInput` has missing `propTypes`
  - [ ] `OverflowMenu`
  - [ ] `RadioButton`
  - [ ] `Tooltip`
- `React.forwardRef` (is this possible to rewrite for class components?)
  - [ ] `HeaderMenu`
  - [ ] `SideNavMenu`

**Comment by jendowns** [comment]
@joshblack which prop types are missing from these skeleton components listed above?

- BreadcrumbSkeleton
- CheckboxSkeleton
- FileUploaderSkeleton
- ProgressIndicatorSkeleton
- ~RadioButtonSkeleton~ Just noticed this one takes an `id` prop
- TabsSkeleton
- TagSkeleton

Currently it looks like none of them accept/use props, unless I'm missing something? At a minimum, they could accept a `className` prop?

**Comment by jendowns** [comment]
I can help with the skeleton components in particular -- I noticed a number of them are classes and wanted to convert them to functional components anyway, so I could do both at the same time. I'm just not 100% sure which props are missing from most of these. 🤔 (Except for `RadioButtonSkeleton`)

**Comment by jendowns** [comment]
I created two quick PRs that I think will help with this one -- let me know what you think!

* #4484 addresses the skeleton components listed above... while I couldn't find any missing prop info, I did notice they were all classes, so I converted them to functional components, which I think will help with future auditing, in general? Also removed the unnecessary `id` prop from `RadioButtonSkeleton`

* #4486 adds prop type documentation for `TableToolbar`'s `children` prop. In the process, I noticed there's a hard-coded `aria-label` attribute, so I added a prop + documentation for that one as well.

**Comment by joshblack** [comment]
Thanks @jendowns! Just updated the list after your comment, seems like something was up with the collection script I wrote 🤔 

Also thanks again for the PRs! Definitely agreed on the function components too btw, in general I hope we can start working towards that goal as a whole 👀

**Comment by justindm234** [comment]
Please consider also adding statically accessible PropTypes for `DataTable`'s `render` prop function. We have found our code is more readable when we implement our `DataTable` `render` function separately...

```
  const renderTable = ({ rows, headers, getTableProps, getHeaderProps, getRowProps, onInputChange }) => (
    <TableContainer id={tableLabelId} title={tableTitle} description={tableDescription}>
      ...
    </TableContainer>
  )

  return (
    <div className='bx--grid'>
      <div className='bx--row'>
        <div className='bx--col'>
          <DataTable rows={allRows} headers={columns} isSortable render={renderTable} />
        </div>
      </div>
    </div>
  )
```

However, this causes our linter to complain about missing propTypes on the function/component (react/prop-types). To get around with we have temporarily defined what we think the render propTypes are (see below), but ideally we would like to get these from the DataTable component, which would have official documentation for these properties...

```
/* DataTable render prop row object; Shape based on DataTable/tools/normalize.js */
const rowPropType = PropTypes.shape({
  id: PropTypes.string,
  isSelected: PropTypes.bool,
  isExpanded: PropTypes.bool,
  disabled: PropTypes.bool,
  cells: PropTypes.arrayOf(PropTypes.shape({
    id: PropTypes.string,
    value: PropTypes.any,
    isEditable: PropTypes.bool,
    isEditing: PropTypes.bool,
    isValid: PropTypes.bool,
    errors: PropTypes.any,
    info: PropTypes.shape({
      header: PropTypes.string
    })
  }))
})

const renderPropTypes = {
  rows: PropTypes.arrayOf(rowPropType),

  // Shape based on DataTable/tools/normalize.js
  headers: PropTypes.arrayOf(PropTypes.shape({
    key: PropTypes.string,
    header: PropTypes.node,
    isExpanded: PropTypes.bool,
    isSelected: PropTypes.bool,
    disabled: PropTypes.bool
  })),

  selectedRows: PropTypes.arrayOf(rowPropType),

  // Prop accessors/getters
  getHeaderProps: PropTypes.func,
  getExpandHeaderProps: PropTypes.func,
  getRowProps: PropTypes.func,
  getSelectionProps: PropTypes.func,
  getBatchActionProps: PropTypes.func,
  getTableProps: PropTypes.func,
  getTableContainerProps: PropTypes.func,

  // Custom event handlers
  onInputChange: PropTypes.func,

  // Expose internal state change actions
  sortBy: PropTypes.func,
  selectAll: PropTypes.func,
  selectRow: PropTypes.func,
  expandRow: PropTypes.func,
  expandAll: PropTypes.func,
  radio: PropTypes.bool
}

...

renderTable.propTypes = renderPropTypes 
```

Please let me know if I should open a separate issue for this request.

Thank you

**Comment by joshblack** [comment]
Hi @justindm234! 👋 Definitely can understand with separating it out, would you expect an export on the library side like `DataTablePropTypes` that would help with this that you could use for prop types?

**Comment by justindm234** [comment]
Hi @joshblack A `DataTablePropTypes` export would be perfect

Thanks again!

**Comment by emyarod** [comment]
aside from the `DataTablePropTypes` export is the original list still up to date?
