### ISSUE TITLE
Update breadcrumb styles to work with themed token updates

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4402]
We observed the following discrepancies when adjusting type size in https://github.com/carbon-design-system/carbon/issues/4330:

- Separators should grow with type size

**Comment by emyarod** [comment]
it looks like the separators grow with `body-short-01`, is this incorrect?

**Comment by joshblack** [comment]
Yeah, I think it needs to match the breadcrumb which is body-long-01
