### ISSUE TITLE
Update button styles to work with themed type tokens

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4403]
We observed the following discrepancies when adjusting type size in https://github.com/carbon-design-system/carbon/issues/4330:

- Type is growing but size stays the same
- button should be 48px tall, it seems like border-width of 3px is causing it to be 50px, 16/22
- Icons should grow to 20
- 40px button with 16/22

**Comment by emyarod** [comment]
based on our conversations yesterday this component (and possibly others) require some reexamination, marking as blocked
