### ISSUE TITLE
Resolve tooltip component sizing for theming 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4410]
Ref audit of #4330 

- Need to make design decision if the tooltip component will be changing or not.

--------------------------------------------------------------------------------------------------------

### Carbon tooltip specs:
![Tooltip Copy 2](https://user-images.githubusercontent.com/43969356/67431389-ce3ea180-f5a9-11e9-8227-59d88bf2d302.png)

**Comment by laurenmrice** [comment]
### Conclusion for Digital specs:
![Tooltip Copy](https://user-images.githubusercontent.com/43969356/67431423-dc8cbd80-f5a9-11e9-8bcf-1888be9ca1c5.png)

**Comment by aledavila** [comment]
@laurenmrice is this now a dev issue ?

**Comment by laurenmrice** [comment]
oh sorry, this was for the theming project, we can close this for now and open again whenever we come back to theming if it is still relevant
