### ISSUE TITLE
[select] inline dropdown bug

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4423]
A couple bugs with Select- inline dropdown

- [x] The chevron icon needs to be aligned with the type inside of the hover, right now it is far away and too low. 
Ex:
![Screen Shot 2019-10-22 at 9.54.05 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/4794bc85-0c86-4cb4-8b3a-225708a0faaa)
---------------------------------------------------------------------------------------------------
- [ ] The chevron should be 8px away from the type. I can't remember if there was a technical reason why this couldn't be achieved. But for inline select, if there isn't a visible background we want to have the 8px relationship with the icon, so the icon doesn't look like its floating on the page.
---------------------------------------------------------------------------------------------------
- [x] The invalid state has too many borders.
- [ ] Also check the spacing on the select dropdown (without inline) when its invalid state is on. The alert icon and chevron icon should be 8px away from eachother.
Ex:
![Screen Shot 2019-10-22 at 9.57.54 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/c440d1b1-8161-4479-9c8f-ad16bd1bd8bf)
---------------------------------------------------------------------------------------------------
- [x] If invalid and disabled are turned on, a hover interaction happens. There should be no hover.
Ex:
![Screen Shot 2019-10-22 at 1.41.19 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/b8bf253c-9515-451d-8d77-910ebe944195)
---------------------------------------------------------------------------------------------------
Ref: #4330

**Comment by emyarod** [comment]
>  The chevron should be 8px away from the type. I can't remember if there was a technical reason why this couldn't be achieved. But for inline select, if there isn't a visible background we want to have the 8px relationship with the icon, so the icon doesn't look like its floating on the page.

regarding this point, we had a previous discussion about it here https://github.com/carbon-design-system/carbon/issues/1958. we wouldn't be able to implement this without some extra JS which I'm not sure we want to include

**Comment by emyarod** [comment]
> The invalid state has too many borders.
> Also check the spacing on the select dropdown (without inline) when its invalid state is on. The alert icon and chevron icon should be 8px away from eachother.
Ex:

I'm unable to replicate these two issues locally or on our netlify previews
