### ISSUE TITLE
Modal dialog jumps when opened/closed

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#4435]
The modal dialog turns off body scrolling when displayed. In the case where a scroll bar is displayed in the background (optional on Mac) the modal dialog can be seen to jump left to right on display and right to left on hide.

## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> The modal dialog jumps which is distracting.

> Modal dialog

> Dialog should not jump

> Chrome latest

> 10.7

> @Carbon/Vue

## Steps to reproduce the issue

1. Ensure scroll bars are always displayed on mac.
![image](https://user-images.githubusercontent.com/15086604/67414202-82e0bf00-f5ba-11e9-8f0c-79b9b08aa9b6.png)
2. yarn dev in the mono repo
3. Show any of the modal dialogs - note the dialog jumps right as it's displayed
4. Hide the dialog - note it jumps left as it's hidden.

NOTE:  A vertical jump would also happen if a horizontal scroll bar was shown.

HINT: Replace
```
right: 0;
bottom: 0;
```

with
```
width: 100vw;
height: 100vh;
```

**Comment by hamoody-omar** [comment]
Having the same issue. When the dialog opens and closes , you can't scroll up or down. the whole page kinda freezes. Any update?

**Comment by emyarod** [comment]
I am not seeing the modal jump after enabling that setting in macOS, would you mind recording the issue you are describing?

**Comment by lee-chase** [comment]
On display the removal of the scroll bar causes the page to jump and modal to drop.
On close the modal jumps left and then rises.
![ModalJump](https://user-images.githubusercontent.com/15086604/72382265-cd349080-3710-11ea-8b2e-7d162b5141a6.gif)

**Comment by emyarod** [comment]
got it, thanks for recording with the 10% slowdown

**Comment by tw15egan** [comment]
Somewhat related (system scroll bar issue: https://github.com/carbon-design-system/carbon/issues/5101)
