### ISSUE TITLE
[tabs] incorrect spacing between tab header and tab content

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4437]
Current example:
![Screen Shot 2019-10-23 at 12.39.42 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/a690ec33-d141-4987-9605-cfd9b933e538)

There needs to be more spacing (16px) between the header and content below it.

--------------------------------------------------------------------------------------------------------

Spec:
![Screen Shot 2019-10-23 at 12.58.44 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/fb81d7ab-de69-46c2-bfa6-4cfb686b6188)

--------------------------------------------------------------------------------------------------------

Ref: #4330 need to fix this bug before theming

**Comment by emyarod** [comment]
would this be a change in our components or just in storybook? I remember there was a similar issue/PR that applied this change to the component story only (https://github.com/carbon-design-system/carbon/commit/fd92bfb15b49ae9f6e8967fcf9b9f03e62ede366)

**Comment by laurenmrice** [comment]
If its appearing currently like this in our component we should fix it. If its just the storybook we should still fix it. We can use `body-long-01` for the content type.
