### ISSUE TITLE
File uploader uploaded states V10 - close button issue

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon#4444]
Hello,
I'm using vanilla minified js and simple html components, I cause an file uploader close button error.
I checked file uploader demo example in codepen https://codepen.io/team/carbon/pen/xeVVBW , there is also an issue, if I press that close button icon, nothing happens, only console shows - **NotFoundError: Node was not found**

Is it possible to avoid from this error?
And another small question, if I choose file what I want to upload, then shows up that file box, but there is no close button, if I want remove it, I inspect that uploaded file block with file name is generated in code, is there possibility to add close icon?

Regards, Reinis.

**Comment by asudoh** [comment]
Hi 👋 would you want to try `v10.7.0` where there is more feature-complete file uploader? BTW to use our file uploader, you need your application logic to dictate where the files should be uploaded, to, etc. An example code can be found at: https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/components/demo/js/file-uploader-demo-state-manager.js

**Comment by reinisg** [comment]
Okay, thank you for answer. I hope I will find the solution, to use v10.7.0 component.
Just for advice: if there is new feature update all links, because f.e. https://www.carbondesignsystem.com/components/file-uploader/code/ is v10.7.0 component, but if I click on codepen, there is an old one v10.0.0 component.
Thanks, best regards Reinis.
