### ISSUE TITLE
Console Warning when using the Dropwdown component on Carbon React

### ISSUE THREAD

**Issue by fabienchn-zz** [carbon-design-system/carbon#4446]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Everytime I use the Dropdown component, I get the following console Warning:
```
Warning: Failed prop type: Invalid prop `children` of type `ListBoxMenuItem` supplied to `ListBoxMenu`, expected each child to be a `ListBoxMenuItem` component.
```
And since I use it a lot, my console is flooded by these warnings.

Any idea that this could be fixed ?

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Not seeing this at http://localhost:9000/?path=/story/dropdown--default, would you want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by fabienchn-zz** [comment]
Hi @asudoh , okay that's wierd. I tried it on the Sandbox and don't get the warning.
https://codesandbox.io/s/codesandbox-zlirj

Any idea what this could be linked to ? It happens when I open the dropdown. 
I have the latest versions of carbon-components & carbon-omponents-react

**Comment by asudoh** [comment]
Thanks, but not seeing it at https://codesandbox.io/s/codesandbox-zlirj or https://zlirj.csb.app/, either - Do you see the problem yourself there?

**Comment by fabienchn-zz** [comment]
@asudoh That's what I meant. I don't see it on the sandox. But I have it on my project.

**Comment by asudoh** [comment]
I see, the best way to get help is creating a minimum application that reproduces the problem.

**Comment by taitelman** [comment]
I see that too when using DropdownV2

```
backend.js:6 Warning: Failed prop type: Invalid prop `children` of type `ListBoxMenuItem` supplied to `ListBoxMenu`, expected each child to be a `ListBoxMenuItem` component.
    in ListBoxMenu (created by Downshift)
    in Downshift (created by DropdownV2)
    in DropdownV2 (created by MySettings)
```

**Comment by taitelman** [comment]
```backend.js:6 Warning: Failed prop type: Invalid prop `children` of type `ListBoxMenuItem` supplied to `ListBoxMenu`, expected each child to be a `ListBoxMenuItem` component.
    in ListBoxMenu (created by Downshift)
    in Downshift (created by DropdownV2)
    in DropdownV2 (created by MySettings)```

**Comment by joshblack** [comment]
I believe this is most likely related to usage of `react-hot-loader`, so will close and mark as a duplicate in favor of: https://github.com/carbon-design-system/carbon/issues/2630

Let me know if these aren't quite the same issue and I can re-open!
