### ISSUE TITLE
dropdown list label is truncated

### ISSUE THREAD

**Issue by zhuzmzm** [carbon-design-system/carbon#4447]
This is an example when using dropdown component, please help take a look. Thanks!
![2](https://user-images.githubusercontent.com/42019585/67469960-91dd7500-f67f-11e9-95ba-348eb27a3c30.png)

## Environment

> Operating system

> Browser

> Automated testing tool and ruleset

> Assistive technology used to verify

## Detailed description

> What version of the Carbon Design System are you using?

> What did you expect to happen?

> What happened instead?

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 would you want to elaborate what the problem is?
