### ISSUE TITLE
[Tabs] Would like to see global event triggers for React tabs

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#4454]
### Summary

Currently, the events `tab-selected` and `tab-beingselected` are only available in the vanilla version of Tabs. Would like to see this for the React versions as well.

In addition, if it's possible would like to also have a `tab-loaded`, where it gets triggered when a tab component is initialized.

### Justification

This is a request coming from the IBM analytics team, where they would like to track these events whenever an IBM.com application adopter utilizes the tabs fro Carbon. The IBM.com library team will be creating analytics triggers from these events.

### Desired UX and success metrics

This is for tracking tabs usage across all of IBM.com.

### "Must have" functionality

Event triggers for Tabs must haves:
- tab-selected
- tab-loaded

### Specific timeline issues / requests

Ideally will have this functionality in place before the vast majority of adopters being switching over to Carbon for IBM.com.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

If necessary, we can schedule work from the IBM.com Library team to PR it back.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Given the nature of React, we have [`onSelectionChange()`](https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/Tabs/Tabs.js#L58-L63) (available in `<Tabs>`) instead of firing DOM custom events for the purpose of propagating events to application code. It may not be what you are looking for given you seems to be trying to leverage event bubbling, and in such case, some research would be needed for the problem space.

**Comment by photodow** [comment]
@asudoh I think going that route would require us (dotcom) to wrap and repackage these components for npm delivery for our adopters to use. I think we're trying to avoid duplicating components between dotcom and carbon, so adopters know if they need tabs they go here and don't have to choose between the two. When we saw in your documentation on the website that y'all were emitting events we were pretty excited.

```javascript
import { Tabs } from 'carbon-components'
```
```javascript
import { Tabs } from '@carbon/ibmdotcom-react' // same as carbon just analytics are included
```

You mentioned research might be necessary. What type of research are you thinking will need to be done?

**Comment by jeffchew** [comment]
> @asudoh I think going that route would require us (dotcom) to wrap and repackage these components for npm delivery for our adopters to use. I think we're trying to avoid duplicating components between dotcom and carbon, so adopters know if they need tabs they go here and don't have to choose between the two. When we saw in your documentation on the website that y'all were emitting events we were pretty excited.

To this point, nothing is stopping IBM.com adopters to use the Carbon components directly (and this is what we have been telling our adopters when migrating over to Carbon). If they use those, there would be no way for us to track those analytics events.

Adding @mattrosno to the conversation.

**Comment by asudoh** [comment]
> You mentioned research might be necessary. What type of research are you thinking will need to be done?

Research should be around how widely-used React components exposes its change in state to analytics, or how analytics handles widely-used React components, e.g. MDC React, React Bootstrap, Lightening React. One thing I can imagine is doing it in application space rather than component library space.

**Comment by jeffchew** [comment]
Please keep open, would still like this ability for the sake of analytics tracking across IBM.com.

**Comment by joshblack** [comment]
Coming back to this as a part of our proposal pipeline:

It seems like for analytics our tendency will be to not use custom events in our React components and instead provide props/hooks for how to register to these events happening.

Going to close this proposal out for now as a result from above, let me know if it'd be helpful to chat here or on Slack/Webex to talk more!

**Comment by jeffchew** [comment]
Hi @joshblack , would like to reconsider reopening. We aren't asking for something bespoke for IBM.com, but would like parity of the event listeners that are currently in place with the vanilla carbon components.
