### ISSUE TITLE
[Modal] Would like to see global event triggers for React Modal

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#4455]
### Summary

Currently, the events `modal-shown` and `modal-hidden` are only available in the vanilla version of Tabs. Would like to see this for the React versions as well.

### Justification

This is a request coming from the IBM analytics team, where they would like to track these events whenever an IBM.com application adopter utilizes the modal from Carbon. The IBM.com library team will be creating analytics triggers from these events.

### Desired UX and success metrics

This is for tracking Modal usage across all of IBM.com.

### "Must have" functionality

Event triggers for Tabs must haves:
- modal-shown
- modal-hidden

### Specific timeline issues / requests

Ideally will have this functionality in place before the vast majority of adopters being switching over to Carbon for IBM.com.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

If necessary, we can schedule work from the IBM.com Library team to PR it back.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Given the nature of React, we tend to use `onSomething()` instead of firing DOM custom events for the purpose of propagating events to application code. It may not be what you are looking for given you seems to be trying to leverage event bubbling, and in such case, some research would be needed for the problem space.

**Comment by photodow** [comment]
@asudoh see https://github.com/carbon-design-system/carbon/issues/4454#issuecomment-550397684 for response.

**Comment by jeffchew** [comment]
Please keep open, would still like this ability for the sake of analytics tracking across IBM.com.

**Comment by joshblack** [comment]
Coming back to this as a part of our proposal pipeline:

It seems like we'll want to keep with the traditional React patterns described above. We can definitely add these props in (`onClose`, `onChange`, `onOpen`, etc), and then teams can customize them to dispatch events if necessary. Unfortunately, I don't think we'll be looking to add custom events for the React components.

Going to close this proposal out for now as a result from above, let me know if it'd be helpful to chat here or on Slack/Webex to talk more!
