### ISSUE TITLE
AAT Violations for carbon -  rpt.g1110.widgetLabels

### ISSUE THREAD

**Issue by pkegbeto** [carbon-design-system/carbon#446]
## Detailed description

Carbon component violation

#### Error message:

```
Message: rpt.g1110.widgetLabels
XPath: /html[1]/body[1]/div[1]/div[1]/div[2]/nav[1]/ul[1]/li[1]/ul[1]
Snippet: <ul aria-hidden="true" class="left-nav-list left-nav-list--nested" role="menu">
```

#### AAT violation
```
 https://aat.w3ibm.mybluemix.net/token/ce020aa2-f761-46a8-8925-2deeda4c9f69/a763761a-383e-4445-8e73-dbf86b61c844/latest/doc/w3/help/en-US/idhi_accessibility_check_g1156.html
```

#### Affected code
![screen shot 2017-11-20 at 12 50 30 pm](https://user-images.githubusercontent.com/29408678/33033338-144d0c66-cdf2-11e7-99bc-08d2643b2a41.png)

## Additional information
![screen shot 2017-11-20 at 12 55 07 pm](https://user-images.githubusercontent.com/29408678/33033344-1acdae9c-cdf2-11e7-932d-d66b16e8cb4e.png)

**Comment by marijohannessen** [comment]
Hi, I'm not quite sure what the problem is here as the role is specified on the elements. Can you please provide some more information on what we need to fix? Thanks! https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus

**Comment by marijohannessen** [comment]
Closing this issue due to our inactivity policy. Please feel free to re-open if needed.

**Comment by pkegbeto** [comment]
Per the rule mentioned above that was violated, the custom roles needs role label.

>To help users navigate a page, WAI-ARIA widgets must have an accessible name specified with aria-label, aria-labelledby or the widget's inner text.
The following example shows a tree widget labelled with an aria-label.


Please follow the link for more information about the violation.

``` 
https://aat.w3ibm.mybluemix.net/token/ce020aa2-f761-46a8-8925-2deeda4c9f69/a763761a-383e-4445-8e73-dbf86b61c844/latest/doc/w3/help/en-US/idhi_accessibility_check_g1156.html
```
