### ISSUE TITLE
[Pagination]: Prev/Next buttons cause page reload when component is wrapped in a <form> element

### ISSUE THREAD

**Issue by vronjec** [carbon-design-system/carbon#4460]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The `<button>` elements inside the React Pagination component are missing the `type="button"` attribute. When this attribute is omitted, `<button>` elements default to `type="submit"`. Pressing a `<button>` with `type="submit"` will work fine when the component is not inside a `<form>` element, but in case it is, it will cause an unintended page reload and render the Pagination component unusable.

See CodeSandbox for demo: https://codesandbox.io/s/codesandbox-7tcue

## Proposed solution

Add `type="button"` to every `<button>` element in the React Pagination component.

**Comment by emyarod** [comment]
in the meantime a workaround for this would be to pass `event => event.preventDefault()` as a click handler into the pagination component
