### ISSUE TITLE
[Pagination]: Incorrect hover trigger causes jank

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#4464]
### Hovering issue
![screen](https://user-images.githubusercontent.com/4078018/67582749-ecbead00-f70f-11e9-96ca-8218432a9b7d.gif)

**Comment by jendowns** [comment]
Replicated here: https://codepen.io/jendowns/pen/VwwzmBd

Appears to be caused by ~`background-color: transparent`~ a `transition: background-color` with a change in `background-color` on hover.
