### ISSUE TITLE
[Combo box] Allow filtering or hide non-matching options

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#4468]
# Allow filtering (or hide non-matching options) for Combo box

### Current

Right now combo box does not hide options that do not match user input text. To increase usibility, component should reduce the number of options when user input some text to only the matching ones. 

![image](https://user-images.githubusercontent.com/15144993/67695387-fac03800-f972-11e9-9176-400d2dc1b4e8.png)

### Ideal state + justifications

Country selection is a common use case for combo box. Number of countries make the dropdown extremely long and difficult to use. Allowing type in + filtering helps to bring all the relevant options into view, hide all the other options. If there is no filtering in below example, users can miss out on the existence of other matching options below the fold. 

Notice the blue text highlighting is a nice to have enhancement. 

![image](https://user-images.githubusercontent.com/15144993/67694551-80db7f00-f971-11e9-86d9-674a5677d9c1.png)

### Research / academic backup 

https://baymard.com/blog/drop-down-usability

**Comment by guigueb** [comment]
I think this one can be closed.
I'm not sure when shouldFilterItem was added but I think it will do what this enhancement is wanting.

  /**
   * Specify your own filtering logic by passing in a `shouldFilterItem`
   * function that takes in the current input and an item and passes back
   * whether or not the item should be filtered.
   */
  shouldFilterItem: PropTypes.func,

**Comment by tw15egan** [comment]
As @guigueb pointed out, it seems like this functionality has been included in `ComboBox` at least dating back to the beginning of the monorepo: [commit](https://github.com/carbon-design-system/carbon/commit/a5601a729517b960675ae72cfff7d00d311afca0#diff-9dc1e5ff8ae860267e0515d35b8ef26c310972783dd63d0cf37d8a2adb8a7d25R110-R115)

A possible future enhancement would be adding color highlighting to the filtered results, but I believe that should be captured in a new issue.
