### ISSUE TITLE
Progress Indicator label text does not display ellipsis on IE11

### ISSUE THREAD

**Issue by kbondanza** [carbon-design-system/carbon#4470]
#4000  What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The ellipsis does not display for label text on IE11

> Is this issue related to a specific component?
Progress Indicator

> What browser are you working in?
IE11

> What version of the Carbon Design System are you using?
carbon-components-react 7.7.0

## Steps to reproduce the issue

To reproduce go to http://localhost:9000/?path=/story/progressindicator--default in IE 11

## Additional information

<img width="1277" alt="Screen Shot 2019-10-27 at 2 59 56 PM" src="https://user-images.githubusercontent.com/8070092/67639846-4919fc00-f8cb-11e9-888e-672744c5f173.png">

**Comment by tw15egan** [comment]
It seems to be an issue with the way IE11 paints the DOM on the initial render. If you interact with the element at all, the ellipsis shows up 🤷‍♂ 

<img width="684" alt="Screen Shot 2020-02-04 at 1 54 27 PM" src="https://user-images.githubusercontent.com/11928039/73790827-ff587180-4755-11ea-8f61-98915106128e.png">


Going to close this as this seems like a general IE11 browser bug, thus unlikely to be fixed. If you stumble across a fix that can get it to paint correctly on initial render, we'd happily accept a PR!
