### ISSUE TITLE
side-nav does not use the theme and is hardcoded to white

### ISSUE THREAD

**Issue by treyhuffine** [carbon-design-system/carbon#4471]
I am trying to use Carbon in dark mode, and the side nav is hardcoded to white. Is this intended or should I send a PR to use background of the chosen theme?

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_theme.scss#L156

Applying the dark theme using the following feels like an unintentional bug for the UI.

```
@import '@carbon/themes/scss/themes';
$carbon--theme: $carbon--theme--g100;
@include carbon--theme();

@import 'carbon-components/scss/globals/scss/styles.scss';

```

<img width="1280" alt="Screen Shot 2019-10-27 at 5 07 59 PM" src="https://user-images.githubusercontent.com/11709986/67642680-5ee3ed00-f8dc-11e9-920f-3029f3e19ae6.png">

**Comment by joshblack** [comment]
Hi there! :wave: It's currently not possible to theme the UI Shell, however we have an open issue to revisit our usage of private tokens here to allow for theming: https://github.com/carbon-design-system/carbon/issues/4839

I'm going to close this for now and point folks over to that feature issue for theming UI Shell. Hope this helps!
