### ISSUE TITLE
readonly prop not passed correctly to textarea

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#4474]
#4000  What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

`<TextInput readonly="true" value="This is read only" />
    <TextInput
      readonly={readonlyMode ? true : undefined}
      value="This is still read only"
    />
    <TextArea readonly="true">This is also read only</TextArea>
    <TextArea readonly={readonlyMode ? true : undefined}>
      This is not read only but should be
    </TextArea>`

https://codesandbox.io/s/codesandbox-cq0om?fontsize=14

**Comment by emyarod** [comment]
have you tried using camel cased `readOnly` attribute? https://codesandbox.io/s/codesandbox-erkm4

**Comment by richardpilot** [comment]
Interesting to see that working.

Given `readOnly` is not a react prop of TextArea or TextInput then I'd expect it to follow the w3 spec and use standard notation.

**Comment by emyarod** [comment]
DOM attributes are written in camelCase in React to match the underlying DOM API https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes
