### ISSUE TITLE
[Button] - variation with href + disabled state is still interactive

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4479]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When a `Button` has `disabled={true}`, it shouldn't be interactive.

But if a `Button` has `href="something"` (which makes it a link that looks like a button) + `disabled={true}`, you can still click on that button and navigate to whatever the `href` value is.

In this case, I would expect this type of `Button` component to behave like a disabled `Link`. (That is, it cannot be clicked / interacted with.)

## Steps to reproduce the issue

1. Go to storybook: http://react.carbondesignsystem.com/?path=/story/buttons--default
2. Check `disabled` prop in the Knobs
3. Click on the second button that says "Link" (which is a link that looks like a button, and has `href="#"` passed to it)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! I'd be open for `pointer-events: none` for that kind of the case. CC @emyarod

**Comment by jendowns** [comment]
OH thanks @asudoh, I didn't see your comment before submitting a PR 😆 
What do you think of the approach of rendering as a button element if `disabled={true}`? I can also go with pointer events if you prefer.
