### ISSUE TITLE
[NumberInput] crashes if you remove the value from the input field

### ISSUE THREAD

**Issue by ptaunton** [carbon-design-system/carbon#4483]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
When using the NumberInput component, if you remove the value from the input field (i.e. hit backspace or delete), then move focus away from the field it will crash and be completely unusable until refresh the browser page.

The console log issue the following error:
```
Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.
    in input (created by NumberInput)
    in div (created by NumberInput)
    in div (created by NumberInput)
    in div (created by NumberInput)
    in NumberInput (created by ForwardRef(NumberInput))
```
and
```
The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
```

After this error has occurred, any attempt to type a new value in the input field fails with a repeat of the second message. Any use of the up/down arrows also fails with the same message. There appears to be no way to recover the input control without a full browser reload of the page.

Browser: Chrome latest
carbon-components: 10.7.0
carbon-components-react: 7.7.0

## Steps to reproduce the issue

1. Place a NumberInput in the page (use min and max 0, 9 - the numbers don't really matter)
2. Focus into the field and remove the zero
3. Focus away from the field, or press tab to focus onto the up/down button
4. Observe the error described above.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Running `v10.7.0` does not seem to reproduce the problem. Would you create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by abbeyhrt** [comment]
Hi @ptaunton! Are you still able to reproduce this issue? We are not able to on our side. If you could provide a code sandbox that reproduces the error, that would be great! Thank you!

**Comment by tw15egan** [comment]
Closing as not reproducible, please feel free to reopen if you are still experiencing an issue 🙂
