### ISSUE TITLE
How to prevent modal from being closed when pressing anywhere on the screen?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#4493]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

How to prevent closing the modal popup when clicking with the mouse outside the popup screen?

**Comment by emyarod** [comment]
I'm not sure if that is recommended UX for the modal but you should be able to override this behavior with the `onRequestClose` prop

**Comment by zbeedatm** [comment]
I tried adding it to my modal, but it's not taking affect!
I mean it's not reaching that method (handleCloseModal) :

`                        <ComposedModal
                                            open={this.state.openImportProject}
                                            onClose={() => {
                             
                                                this.toggleImportProjectModal(false)
                                            }}
                                            height={500}
                                            // className="not-closable"
                                            onRequestClose={this.handleCloseModal}
                                        >`

**Comment by asudoh** [comment]
Seems that `<ComposedModal>` and `<Modal>` have different set of APIs there - Would you try hooking `onClose()` and returning `false` there?

**Comment by zbeedatm** [comment]
hi, it didn't do the trick. any other ideas?
Is it possible to hook it by css?

**Comment by emyarod** [comment]
can you create a reduced test case in CodeSandbox?

https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by zbeedatm** [comment]
Can you use this sandbox please instead (I have it already ready for use):
https://codesandbox.io/s/fragrant-morning-267l5

You can choose from the menu of each Project component the: "Rename" or "Duplicate" option

**Comment by emyarod** [comment]
you're closing the rename modal with `this.toggleRenameProjectModal(false);` on L927 of `src/components/Project.js`

**Comment by zbeedatm** [comment]
sorry, didn't save my change.
Even after disabling the `this.toggleRenameProjectModal(false);` it's still the same behavior

**Comment by emyarod** [comment]
you need to `return false;` as @asudoh [mentioned](https://github.com/carbon-design-system/carbon/issues/4493#issuecomment-548145217)

**Comment by zbeedatm** [comment]
But then I will not be able to close it by clicking on the "X" button!!!
I want to prevent the close when pressing with mouse outside the screen only.

**Comment by asudoh** [comment]
I see, would you create a separate issue for letting `onClose` called with the event object? In this way you can inspect `event.target` to detect if it's from click-outside.

**Comment by zbeedatm** [comment]
Opened #4516
