### ISSUE TITLE
Blue version of the Tag Filter Component in Vue?

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon#4494]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Summary

Our team are in the process of implementing an approved design which makes use of the ‘Tag Filter’ carbon component. We specifically are needing to use a blue version of the ‘Tag Filter’, which our design team has used in their designs, given that they can be found within the carbon sketch library. However, the website (carbondesignsystem.com) for this component seems to only have the black tag filter available, with the coloured versions only being available for regular tags, not tag filters. These designs have been user tested, so we are really hoping that we can match them. How can we access the blue tag filter in vue?

**Comment by william-glasse** [comment]
![image](https://user-images.githubusercontent.com/56296356/67868429-e40d1300-fb23-11e9-8220-de8080136d0a.png)
This second image shows the design we are looking for.
![image](https://user-images.githubusercontent.com/56296356/67868582-17e83880-fb24-11e9-82a3-93279672e1dd.png)

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon/issues/3318, currently pending design feedback
