### ISSUE TITLE
Building in Docker causes Invalid US-ASCII character "\xF0"

### ISSUE THREAD

**Issue by alohr51** [carbon-design-system/carbon#4496]
In this specific example I am using Docker (and jekyll) to build the site, but I believe the problem lies with the encoding the os in the Docker image is using. I am specifically using the `ruby:2.6.5` docker image, but other images may provide the same error too.

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

The primary cause of this is the use of emoji's in the scss comments.

```
      Jekyll Feed: Generating feed for posts
           Assets:  Invalid US-ASCII character "\xF0"
         Asset File /app/node_modules/carbon-components/scss/globals/scss/styles.scss:9
  Liquid Exception: Sass Error in /_layouts/default.html
/usr/local/bundle/gems/jekyll-assets-3.0.12/lib/jekyll/assets/tag.rb:211:in `e_sass': Sass Error (Sass::SyntaxError)
```

The above error is specific for the [globe emoji in the comments in styles.scss](https://github.com/carbon-design-system/carbon/blob/v10.7.3/packages/components/src/globals/scss/styles.scss#L9)

Removing the emoji gets past the error, until the next file with an emoji is handled. 

> Is this issue related to a specific component?

Any component with emojis in the scss comments

> What version of the Carbon Design System are you using?

`"carbon-components": "^10.7.2"`

## Steps to reproduce the issue

1. Clone from https://github.com/kabanero-io/kabanero-landing
2. Comment out `ENV LANG C.UTF-8` in the Dockerfile 
3. run `./ci/build.sh`
4. The error appears in the build. Uncomment the ENV line from step 2 and it will work successfully.

## Additional information

This issue is more informational since the workaround/fix is to add that ENV var in the dockerfile for UTF-8 Encoding (see steps to reproduce). It might make sense to not include emojis in the scss comments as they do sometimes provide Docker build issues like this one and don't really offer much value.

**Comment by alohr51** [comment]
Commenting again to highlight a workaround / fix

For my specific image, `ruby:2.6.5` I was able to add this env var to my Dockerfile before I built my site
```
ENV LANG C.UTF-8
```

This allowed the build to understand the encoding of the emojis and build successfully.

Found from https://github.com/docker-library/docs/blob/master/ruby/content.md#encoding

**Comment by joshblack** [comment]
Glad you found a workaround, unsure of how to handle the issue outside of setting the text encoding as you noted. Let me know if you have any other ideas and I'd be happy to re-open! Since there seems to be a workaround will go ahead and close this out.

**Comment by alohr51** [comment]
@joshblack the second way to fix this is to remove all emojis from the scss comments - just making sure you're aware of the options.

**Comment by joshblack** [comment]
@alohr51 for sure! We would also run into this issue with any non-ASCII characters, right?

**Comment by alohr51** [comment]
@joshblack I believe so
