### ISSUE TITLE
Checkbox component needs lineheight adjusted.

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon#4498]
As discussed here -> https://ibm-studios.slack.com/archives/C0M053VPT/p1572463045365100

The line height needs adjustment to improve readability when a checkbox item wraps.

@aagonzales 's suggestion is to remove the extra line-height attribute to resolve;

![image](https://user-images.githubusercontent.com/51379566/67892372-fa6a9d00-fb2a-11e9-99cd-012bb9abf466.png)

**Comment by asudoh** [comment]
Removing `line-height` there seems to break the alignment between check box and the text, given the type token dictates `1.125rem` line height rather than `1.5rem`.

**Comment by marceltrautmann** [comment]
I'll defer to @aagonzales on the solution.

**Comment by aagonzales** [comment]
@marceltrautmann can you post the original problem and Akira can look into how to solve it. It was just an educated guess that we should remove the line-height but it sounds like that will break things.

**Comment by marceltrautmann** [comment]
@asudoh 
Please see the following image which show's the origional design intent from the carbon designers (as shown in the sketch kit)...  You'll notice that the space between each item's text is different that there where a single item's text wraps to two lines.
![image](https://user-images.githubusercontent.com/51379566/68147716-ae43a200-ff08-11e9-99e0-10773ddb11cd.png)


How in the actual (react) version this distinction isn't present, and therefore makes the legibility difficult.  From what I can tell from the sketch kit the line height should be 18px (unsure how that translates to how you work)
![image](https://user-images.githubusercontent.com/51379566/68147868-f82c8800-ff08-11e9-8340-25915acac03b.png)

I trust this is enough detail?

**Comment by joshblack** [comment]
Closed by: https://github.com/carbon-design-system/carbon/pull/7373 I believe! Let me know if not 👍
