### ISSUE TITLE
Explore container and icon tokens in several components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4500]
This issue is for exploring adding container and icon tokens to better support customization of the design system through theming. The idea for these tokens is as follows:

```scss
// Container tokens
$container-01: 2rem;
$container-02: 2.5rem;
$container-03: 3rem;
$container-04: 4rem;

// Icon tokens
$icon-01: 1rem;
$icon-02: 1.25rem;
```

For this experiment, we're going to want to explore adding these tokens to the following components, working with design at each stage to see how it works:

- Accordion
- Button

This experiment doesn't need to look into adding things into carbon themes or worrying about supporting our theming strategy for both CSS Custom Properties and default value. It can use any browser features without worrying about an appropriate fallback.

This could mean that CSS Custom Properties by default could work:

```scss
$container-01: var(--cds-container-01, 2rem);
```

This experiment could also look into extending our existing storybook panels to add support for modifying these containers, as needed, if it'd be helpful.

---

For usage with teams like dotcom, the idea would be that these tokens would be updated in the following way:

```diff
// Container tokens
$container-01: 2rem;
-$container-02: 2.5rem;
+$container-02: 3rem;
$container-03: 3rem;
$container-04: 4rem;

// Icon tokens
-$icon-01: 1rem;
+$icon-01: 1.25rem;
-$icon-02: 1.25rem;
+$icon-02: 1.5rem;
```

**Comment by laurenmrice** [comment]
**Container size audit**
![Container](https://user-images.githubusercontent.com/43969356/68224689-b3f6c180-ffb4-11e9-88ef-1e006cc53cfc.png)

---------------------------------------------------------------------------------------------------

**Icon size audit**
![Icon](https://user-images.githubusercontent.com/43969356/68224759-d8eb3480-ffb4-11e9-95d1-74ce67132674.png)
