### ISSUE TITLE
[data bable] "enableSingleSelect“=true does not tack effect in angular ibm-table component

### ISSUE THREAD

**Issue by Kalenzhu** [carbon-design-system/carbon#4506]
![图片](https://user-images.githubusercontent.com/23475326/67914123-2d17a280-fbca-11e9-8715-a31ec207eace.png)
we set "enableSingleSelect“=true in datatable. but when we click one row in in the data table,
the selected row cn not be captured.
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 did you mean to report this issue to https://github.com/IBM/carbon-components-angular? Thanks!

**Comment by joshblack** [comment]
Going to go ahead and close this issue as we believe it was meant for the link shared above 👍
