### ISSUE TITLE
[Inline Notification]: close icon is invisible (white) when lowContract

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon#4508]
## What package(s) are you using?

- [x] `carbon-components` 10.7.3
- [x] `carbon-components-react` 7.7.3
- [x] `@carbon/icons-react` 10.6.0

## Detailed description

> Describe in detail the issue you're having.

When I use inline notification with lowContract mode, close icon is almost not visible because it is white.

> Is this issue related to a specific component?

Yes, ToastNotification

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect to easily see close icon.

> What browser are you working in?

Chrome Version 77.0.3865.120

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Hyper Protect team, one of the services is going GA (end of November).

## Steps to reproduce the issue

1. Just look at the Toast Notification component

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/codesandbox-516tr

## Additional information

![image](https://user-images.githubusercontent.com/5481483/67956318-2ef65b80-fbf4-11e9-9542-25200e15a2ad.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Addressed by: #4299

**Comment by ZrianinaMariia** [comment]
Thank you so much @asudoh!
