### ISSUE TITLE
"Notificaiton" typo

### ISSUE THREAD

**Issue by aavetis** [carbon-design-system/carbon#451]
## Detailed description

On the[ Toast Notifications](http://www.carbondesignsystem.com/components/notification/code) page, all the toasts say _Notificaition_ instead of Notification

## Additional information
![image](https://user-images.githubusercontent.com/3076502/33458008-8223d97e-d5f2-11e7-968b-7504b2535e59.png)

**Comment by tw15egan** [comment]
Whoops, thanks for catching that 😅  Fix is up in a PR: https://github.com/carbon-design-system/carbon-components/pull/452
