### ISSUE TITLE
cv-tag filter breaks when using text with length bigger than the width of the tag

### ISSUE THREAD

**Issue by skaparelos1** [carbon-design-system/carbon#4511]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

Our team uses tags to present content generated by others. The problem we have is long text in tags doesn’t seem to be handled correctly. 

> Is this issue related to a specific component?

yes

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected: To add ellipsis syntax (3 dots like `...`) and `x` icon to remain same size
Happens: Keeps the text in the screen and `x` icon gets smaller

> What browser are you working in?

Firefox 

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

1. Open vue storybook for cv-tag filter (http://vue.carbondesignsystem.com/?path=/story/components-cvtag--filter). Also tested in react storybook
2. Set the `tag label` to `South Georgia and the South Sandwich Islands`
3. Resize the width of the window (using the `Responsive Design Mode` from the dev tools or otherwise) to emulate a smaller div where this tag would be placed in

## Additional information

- Screenshot

A screenshot can be seen below from the vue storybook (I’ve highlighted the text using my mouse):

<img width="321" alt="image" src="https://user-images.githubusercontent.com/57231101/67969599-83540800-fc01-11e9-8f3e-30eec00637ad.png">

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Is this a specific issue with Carbon Vue variant, or something seen with other framework variants? CC @lee-chase

**Comment by skaparelos1** [comment]
Hello, I am able to reproduce this in the react storybook as well (http://react.carbondesignsystem.com/?path=/story/tag--filter).
Here's a screenshot (Highlighted text with my mouse): 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/57231101/68018054-12a7fc80-fc90-11e9-8f44-b51ab56b4570.png">

**Comment by lee-chase** [comment]
This appears to be an issue with the underlying DOM/CSS which I could not find a pure CSS way of fixing. Submitted PR with possible fix.
