### ISSUE TITLE
Tooltip content gets truncated when anchor text too close to window border

### ISSUE THREAD

**Issue by natmasse** [carbon-design-system/carbon#4514]
## What package(s) are you using?

- [ ] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When the tooltip anchor text is too close to the window border, when the user clicks on the anchor the tooltip text opens but is truncated.
Can see the same behaviour in the Carbon storybook

![image](https://user-images.githubusercontent.com/40840777/67988276-ddef6300-fc05-11e9-8bbe-ad28ad155fd1.png)

![image](https://user-images.githubusercontent.com/40840777/67988041-3e31d500-fc05-11e9-9923-97b28479ef0c.png)
> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I would expect the width and/or position of the tooltip to be adjusted so it shows in its entirety and is not truncated.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v9 and V10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Docs microservice

## Steps to reproduce the issue

1. Create tooltip with anchor text positioned close to the window border 
2. Click on anchor to open tooltip
3. Tooltip opens but text is truncated

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Seems that many of the screenshots in the description here is closer to definition/icon tooltips rather than interactive tooltip. Definition/icon tooltips support different alignment options.

**Comment by abbeyhrt** [comment]
Our tooltip now supports different alignments so this issue can be addressed by setting the direction so the tooltip fully appears on the screen. Closing this since it's been addressed!
