### ISSUE TITLE
DataTable toolbar and action bar should have option for size="small" to match design toolkit 

### ISSUE THREAD

**Issue by gcate** [carbon-design-system/carbon#4515]
The Carbon Sketch design toolkit provides both "large" and "small" versions of action bar and tool bar.  It would be nice if the React DataTable tool bar and action bar components supported this.
![image](https://user-images.githubusercontent.com/4819973/67991167-8517ce80-fbf5-11e9-89ae-14827ae592e5.png)

In the react component, we can control the table row height with  the property size="short" but it seems we need to modify CSS to get the action bar and toolbar to match the smaller height that design toolkit provides.
I am wondering if we can have similar properties to change height of tool bar and action bar?
 
### Summary
Request to development: a "small" property for datagrid tool bar and action bar so we can match what is provided in design kit.

### Justification
These are elements that designers are designing with.  If each dev team doesn't have to create css to do this for themselves we save effort!! :)

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see this is something our designers are interested in.

**Comment by laurenmrice** [comment]
@asudoh Yes we should have that option in code for the 24 and 32 rows
