### ISSUE TITLE
ComposedModal - Letting onClose called with the event object 

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#4516]
### Summary

Letting onClose called with the event object of ComposedModl, will allow to inspect event.target to detect if it's from click-outside or by clicking on the "x" button to close that modal.

### Justification

Need to prevent closing Modal (ComposedModal in my case) when clicking with the mouse outside the popup screen.

### Desired UX and success metrics

I need to prevent closing Modal (ComposedModal in my case) when clicking with the mouse outside the popup screen.

**Comment by zbeedatm** [comment]
Thanks for the fix. Is it part of a new release already?

**Comment by asudoh** [comment]
I suppose not, but stay tuned for: https://github.com/carbon-design-system/carbon/releases

**Comment by zbeedatm** [comment]
Hi,
I updated to 10.7.4 (which includes #4622) and used:
`onClose = { e => this.closeImportProjectModal(e)}`

`closeImportProjectModal(e) {
        if (e) {
            console.log(e.target)
        }`

Currently behavior, if I press on the Cancel button of Modal footer e.target is populated.
But when pressing on the "X" button or clicking with the mouse outside, (e) event is undefined!

How can I distinguish between them? Am I missing something?

**Comment by asudoh** [comment]
Do you have a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by zbeedatm** [comment]
reduced in : https://codesandbox.io/s/fragrant-morning-267l5
(The import project modal)

**Comment by asudoh** [comment]
Opening https://codesandbox.io/s/fragrant-morning-267l5, clicking Import button and clicking somewhere outside, I see that modal shows something like `<div height="500" role="presentation" class="bx--modal" tabindex="-1">` in Chrome DevTools console.

**Comment by zbeedatm** [comment]
I captured the screen, I don't get any div when clicking outside!
PSB this video:
https://drive.google.com/drive/u/0/folders/1XCDEFE03nWzLyksdUcbfm2OAcP5GAJbI

**Comment by asudoh** [comment]
Seems that the fix is not in [`v10.7.4` code](https://github.com/carbon-design-system/carbon/blob/v10.7.4/packages/react/src/components/ComposedModal/ComposedModal.js#L102) whereas it's in [`master`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ComposedModal/ComposedModal.js#L108). Sorry and stay tuned for an upcoming release!
