### ISSUE TITLE
Style rules imported out of order

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#4527]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Our style rules are being imported out of order which is causing visual regressions where some components to appear broken

related https://github.com/carbon-design-system/carbon/pull/4438

> Is this issue related to a specific component?

So far I've only identified this in icon-only button, but it may also be present in other components which rely on style cascading

## Steps to reproduce the issue

1. [open the React icon-only button story](https://carbon-components-react.netlify.com/?path=/story/buttons--icon-only-buttons)
2. [open the vanilla icon-only button example](https://the-carbon-components.netlify.com/?nav=button)
3. compare the appearance of the component examples. in dev tools you can see that the order of the style rules does not match despite the markup being identical

**Comment by joshblack** [comment]
This should be addressed now that we switched from this strategy! Let me know if not 👍
