### ISSUE TITLE
Not able to tab through MultiSelect component

### ISSUE THREAD

**Issue by mathioli** [carbon-design-system/carbon#4528]
The MultiSelect component does not support tabs to switch through options. Tapping on tab after opening the multiselect dropdown is moving the focus out of the component.

## Environment

> Browser
    Chrome v78.0.3904.70

> What version of the Carbon Design System are you using?
    v9.91.5

> What did you expect to happen?
    Tapping on the tab button should show the focus on the item within the dropdown

## Steps to reproduce the issue

1. Open any multiselect dropdown
2. Hit tab button and see the focus moving out of the component

This issue can be seen in the storybook as well - http://react.carbondesignsystem.com/?path=/story/multiselect--default

**Comment by asudoh** [comment]
Hi 👋 this is by design - We use up/down arrow keys for that purpose. If you turn of VoiceOver on Mac, the component specifically announces what keys you can navigate menu items with.
