### ISSUE TITLE
Unable to show the modal with JavaScript (Angular 5.0)

### ISSUE THREAD

**Issue by rahulsethione** [carbon-design-system/carbon#453]
## Unable to show the modal with JavaScript (Angular 5.0)

I am trying to open an instance of modal component within an Angular component. I have initialed the modal instance using OnInit component life cycle hook. I want to open a modal conditionally with my business logic on a click event.

```
Modal.init(document.querySelector('[data-modal]'))
```

The above returns an empty string and not the instance for the modal. Hence, the method 'show' does not work.

Please assist in resolving the issue.

**Comment by asudoh** [comment]
@rahulsethione What you may have wanted is `Modal.create(document.querySelector('[data-modal]'))`, which returns a component instance with `.show()` method. Hope it helps.

**Comment by marijohannessen** [comment]
Closing this issue as it appears to be resolved. Feel free to re-open if needed.
