### ISSUE TITLE
Unable to use File Upload for subsequent uploads

### ISSUE THREAD

**Issue by DaniDimitrova** [carbon-design-system/carbon#454]
## Detailed description

After uploading one file with the FileUploader and closing it, I can't upload a second file. It appears to let me upload one because the file dialog opens but then the file name label doesn't show up. 

> Is this issue related to a specific component? 
FileUploader 

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected that after closing a file that I decided I did not want to use, I would be able to upload a second file. 

> What browser are you working in? 
Chrome.

> What version of the Carbon Design System are you using? 
```
"carbon-components": "^7.13.0",
"carbon-components-react": "^3.9.0"
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM's Project Livegrid

## Steps to reproduce the issue

1. Upload a file
![image](https://user-images.githubusercontent.com/15187407/33612700-6d79cac2-d9a0-11e7-96c5-743d2fc7359f.png)
2. Click the 'x' to remove that file and upload a different one, which view wise brings me to the original state
![image](https://user-images.githubusercontent.com/15187407/33612994-53e7174e-d9a1-11e7-89a0-ea2bce5b74bb.png)
3. Select another file to upload
![image](https://user-images.githubusercontent.com/15187407/33613087-a9a0867a-d9a1-11e7-9c3b-5a01c0377d40.png)
4. The file does not appear in the component
![image](https://user-images.githubusercontent.com/15187407/33613123-c5c53bac-d9a1-11e7-8c1b-ce65350c3162.png)

## Add labels
I don't have permission to add labels so I'll just add it here:
bug

**Comment by asudoh** [comment]
@tw15egan Should we move this to https://github.com/carbon-design-system/carbon-components-react/issues?

**Comment by marijohannessen** [comment]
Yes, @DaniDimitrova do you mind re-opening this issue in the `carbon-components-react` repo? Thanks!

**Comment by marijohannessen** [comment]
Issue moved to [carbon-design-system/carbon-components-react #845](https://github.com/carbon-design-system/carbon-components-react/issues/845) via [**ZenHub**](https://www.zenhub.com/)
