### ISSUE TITLE
[checkbox]: Checkbox can not default to indeterminate

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#4544]
Rather than `defaultChecked` we should expose a `defaultState` which allows for `checked`, `unchecked`, or `indeterminate`

**Comment by vpicone** [comment]
Not stale

**Comment by joshblack** [comment]
@vpicone is this what the `indeterminate` prop is used for?

**Comment by joshblack** [comment]
Going to close this due to inactivity, let me know if the above response doesn't address the issue! If you think this should be a component level change for v11, definitely understand and might be worth adding over the v11 issue for React?
