### ISSUE TITLE
Yarn Install Incompatible with Node 8.9.1

### ISSUE THREAD

**Issue by slipperypenguin** [carbon-design-system/carbon#455]
## Detailed description

When installing/updating carbon components, we are getting the error:
 `error carbon-components@8.1.12: The engine "node" is incompatible with this module. Expected version "6.x || 7.x || 9.x".`

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected carbon-components to be compatible with the current [Node LTS](https://nodejs.org/en/) version (8.9.1)

> What version of the Carbon Design System are you using? 

8.1.12

## Additional information

![screen shot 2017-12-05 at 12 02 16 pm](https://user-images.githubusercontent.com/3655354/33619860-3c1c3546-d9b4-11e7-9253-15f0cc0a82a3.png)

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment]
Hi there @slipperypenguin! Sorry about this hiccup, it should be fixed in the latest release 😄 

Feel free to re-open if that's not the case!
