### ISSUE TITLE
Type styles don't include font-family

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon#4551]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

We are attempting to bring in Carbon type styles using, for example:

`@include carbon--type-style('body-long-02')`

However, that does not include `font-family` ([source](https://github.com/carbon-design-system/carbon/blob/9582635104a9a19623b0946a94b814d1a5331f0e/packages/components/src/globals/scss/vendor/%40carbon/elements/scss/type/_inlined/_styles.scss#L73)) even though it's mentioned in the [documentation](https://www.carbondesignsystem.com/guidelines/typography/productive).

> Is this issue related to a specific component?

No.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect using `carbon--type-style()` to also define the `font-family`.

> What browser are you working in?

The good ones.

> What version of the Carbon Design System are you using?

`"carbon-components": "~10.7.3"`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Discovery

**Comment by joshblack** [comment]
Hey @jhpedemonte! :wave:

Going through older issues today (so sorry about the delay) and definitely see what you're describing. I believe the intent is that they would inherit from the body copy, in particular through the type reset if I remember correctly.

https://github.com/carbon-design-system/carbon/blob/master/packages/type/scss/_reset.scss#L17

Hope this helps! Going to close this out for now, but feel free to comment and I can re-open!
