### ISSUE TITLE
[condensed grid] wrapping columns collapse

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#4555]
## What package(s) are you using?

- [ ] `@carbon/grid`
- [ ] `carbon-components`

## Detailed description

When using the condensed grid the vertical spacing is put on the `bx--row` class. This doesn't allow for wrapping of columns. For instance when you have `16` columns setup at `(1, 16)`, and on the medium breakpoint they fall back to `(1, 8)`. To get this the columns begin to wrap. You now have 2 rows of 8, but because the `bx--row` doesn't wrap with it the spacing in between the columns collapse and butt up against each other.

This is actually two rows of wrapped columns that demonstrates the problem.
![image](https://user-images.githubusercontent.com/3793636/68149716-04faad00-ff04-11e9-8ef9-642944b5108e.png)

> Is this issue related to a specific component?

condensed grid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect each column to manage the vertical spacing so when they wrap, they get the proper spacing.

Thinking out loud here we could replace [L323-L329](https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss#L323-L329) with something like this...

```scss
.#{$prefix}--grid--condensed [class*='#{$prefix}--col-'] {
    padding-top: $condensed-gutter / 2;
    padding-bottom: $condensed-gutter / 2;
}
```

> What version of the Carbon Design System are you using?
10.6.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Dotcom

## codesandbox example

https://codesandbox.io/s/unruffled-raman-6rl7u?fontsize=14

**Comment by tay1orjones** [comment]
Looks like this was resolved back in https://github.com/carbon-design-system/carbon/pull/4960

https://codesandbox.io/s/serene-williams-s6pgw?file=/src/index.js
