### ISSUE TITLE
Data Tables with Expandable Rows

### ISSUE THREAD

**Issue by UxCloudSecurity** [carbon-design-system/carbon#456]
1. Zebra stripes and expanding rows are not mutually exclusive.
We need a way to use zebra stripes with expanding rows.
As I see it, there are 2 solutions to this issue:

- Have the expanding section in a third and different color than either color of the zebra stripes.

- Have the expanding section be in the color of the row, so it would sometimes be white and sometimes grey.

2. The expanding section needs some more features – 
We often need a separation into subheaders – see attached image
![acm_my_certificates_2](https://user-images.githubusercontent.com/34280748/33620009-53e98bde-d9ef-11e7-90fa-39c01c644dcf.png)
, where “Status” and “Details” are subheaders within the expanded table row.

3. How will expandable rows with an action menu (ellipsis) work ? I’m assuming that once the row has been expanded, the ellipsis appears. Is this a correct assumption ?

**Comment by tw15egan** [comment]
@UxCloudSecurity In regards to 2) this can be accomplished with the current component. The `expandable` sections are just `div` containers. You can add whatever you'd like to them, please see https://codepen.io/tjegan/pen/YEMxXB for an example. I'll let @carbon-design-system/design weigh in on the rest

**Comment by bsonefeld** [comment]
1. I would recommend the following: 

> Have the expanding section be in the color of the row, so it would sometimes be white and sometimes grey.

3. This would follow our current pattern for the overflow menu on rows, it would appear whenever the user hovers over the row. If the row is expanded, the overflow menu will still appear on hover.

**Comment by marijohannessen** [comment]
Closing this as it seems to be resolved, feel free to re-open if necessary.
