### ISSUE TITLE
[Inline Notification]: warning icon when lowContract

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon#4564]
## What package(s) are you using?

- [x] `carbon-components` 10.7.3
- [x] `carbon-components-react` 7.7.3
- [x] `@carbon/icons-react` 10.6.1

## Detailed description

> Describe in detail the issue you're having.

Warning notification icon has white `!` when it should have black.

> Is this issue related to a specific component?

InlineNotification

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect to see the same icon as on carbondesignsystem website.

> What browser are you working in?

Chrome Version 78.0.3904.70 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Hyper Protect, release Q4

## Steps to reproduce the issue

1. Open codesandbox and check the icon

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/codesandbox-hpfhg

## Additional information

Codesandbox: 
![image](https://user-images.githubusercontent.com/5481483/68220890-d571a080-ffe8-11e9-87e7-4082ee817251.png)

Carbon design system website: 
![image](https://user-images.githubusercontent.com/5481483/68220921-dc98ae80-ffe8-11e9-8a4d-a3bd2781c314.png)

**Comment by asudoh** [comment]
#3377 should address this - You can get the fix by upgrading Carbon.
