### ISSUE TITLE
Overflow menu popover in a table gets hidden under table footer

### ISSUE THREAD

**Issue by grengaster** [carbon-design-system/carbon#457]
I have an overflow menu for each row of the table. If there is only one row on the table, the popover for the overflow menu gets hidden under the table footer.

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component? 
Overflow menu component

> What did you expect to happen? What happened instead? What would you like to see changed?
The popover for the overflow menu should be visible

> What browser are you working in? 
Chrome and Firefox

> What version of the Carbon Design System are you using? 
  "carbon-addons-catalog-react": "0.1.8",
    "carbon-components": "7.17.0",
    "carbon-components-react": "3.14.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Armada UI

![image](https://user-images.githubusercontent.com/8367040/33671928-e771cdc6-da76-11e7-96fe-d88c87c4ef68.png)

![image](https://user-images.githubusercontent.com/8367040/33671829-b0e0b8c6-da76-11e7-85cc-24b22980d425.png)
In the second image attached, I have clicked on the overflow menu, but I don't see the "Delete" menu item because the popover is hidden beneath the table footer.

**Comment by joshblack** [comment]
Hi @grengaster! 👋  Thanks so much for taking the time to make this issue 😄

I'm assuming that you're using the `OverflowMenu` component from the React library given your dependencies, I think to resolve this issue all you need to do is pass in the `floatingMenu` prop to the component and it should resolve the issue you're seeing.

Let me know if that helps!

**Comment by grengaster** [comment]
Thank you for the response @joshblack ! Sure enough, your suggestion fixed the issue! Closing.
