### ISSUE TITLE
AVT 1 - Modal React Component has DAP violations

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon#4574]
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP IBM Accessibility 1.8.0.0 Sept 2019 Ruleset

## Detailed Description
Go to the React Component 
Run DAP and activate the modal. The following violations are present (see screenshot) in all Modal components except Input Modal:
<img width="1346" alt="modal" src="https://user-images.githubusercontent.com/21676914/68240906-5756cf00-ffd3-11e9-96f1-303052ccf859.png">

Input Modal has the following violations:
<img width="1295" alt="input-modal" src="https://user-images.githubusercontent.com/21676914/68240914-5b82ec80-ffd3-11e9-98b6-0c07e365ea0f.png">

**Comment by joshblack** [comment]
When looking at this, it seems like `Modal` violation is either gone or no longer applies. The reference issue seems to refer to a node that exists earlier on in the markup

![image](https://user-images.githubusercontent.com/3901764/69462555-e9ced080-0d3e-11ea-8184-5087cb6a6346.png)

Note the content class and the earlier `<h2>` with the corresponding label.

For input modal, these will refer to the underlying controls and should not be an issue with Modal.

Closing this as it seems like this is addressed, feel free to comment if I'm missing out steps to reproduce!

cc @dakahn
