### ISSUE TITLE
[Accordion] add `align` prop to align chevron to "start" of heading

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4584]
## Summary

We recently wrapped Carbon's `Accordion` component to add an `align` prop. This prop allows user's to decide whether the `Accordion` chevron should be aligned at the start of the heading (which is *our* default) or at the end of the heading (which is Carbon's default).

So I was wondering if you'd like for me to contribute this upstream to `carbon-components-react`. The one difference would be, whereas our default is `start` alignment, yours would be `end` just due to the current state of your `Accordion`.

### Example of `align='start'`:

![Screen Shot 2019-11-06 at 9 33 04 AM](https://user-images.githubusercontent.com/9057921/68312310-7bb8b700-0078-11ea-9314-bc5e4ce63c8b.png)

## Justification

There are instances in the IBM Security portfolio where we need either `start` or `end` alignment.

`start` is our default because from the get-go, we needed to deviate a bit from the current Carbon `Accordion` that aligns at the `end`. 

By adding an option for users to specify alignment with a prop, there's no need for them to add style overrides like we (originally) did. 

## Available extra resources

I can contribute this update. 👍

**Comment by jendowns** [comment]
@carbon-design-system/design I'm curious what the design team things about this! ☝️ 
Let me know if you need any product examples or so forth & I can send you info on Slack.

**Comment by jendowns** [comment]
I'm going to go ahead and open a PR for this shortly 👍 
Happy to talk more about this update here or in the PR

**Comment by aagonzales** [comment]
(late to the game here but) I think if its an easy to add and switch between the two in code than its good with design to add. We'll need to maybe think up some guidance on how the two should be used and if there's a usage difference or if its just an aesthetic chose a product can make and then consistently use.
