### ISSUE TITLE
Truncated overflow menu

### ISSUE THREAD

**Issue by nullhook** [carbon-design-system/carbon#459]
@asudoh 

I get a truncated overflow menu no matter wherever I place. 

![image](https://user-images.githubusercontent.com/8665427/33719860-1ff67644-db88-11e7-8dcf-0d2bacebc10a.png)

here is the flip class you asked me to add: https://github.com/rehat101/carbon/blob/master/src/overflowmenu.component#L14

**Comment by asudoh** [comment]
@rehat101 The class should be [`bx--overflow-menu--flip`](https://github.com/carbon-design-system/carbon-components/blob/e5dca27/src/components/overflow-menu/_overflow-menu.scss#L130-L136) - Two dashes between `menu` and `flip`. Probably Mac’s automatic conversion to “fancy dash” came across to our conversation and my apologies if it’s the case.

**Comment by nullhook** [comment]
@asahlin - Thanks, works on the table nicely as you can see above. 

![image](https://user-images.githubusercontent.com/8665427/33808411-be519726-de0b-11e7-89be-826e31e1cfe5.png)


However, I have a menu on the header and the dropdown still overlaps the edge of the browser. Below is the full screenshot

![image](https://user-images.githubusercontent.com/8665427/33808419-d72f9e5a-de0b-11e7-885c-eb08d926f427.png)

**Comment by asudoh** [comment]
@rehat101 Great that you finally got right-aligned overflow menu. Wrt the 2nd screenshot - I’m afraid you’ll meed to move the trigger button slightly to the left.

**Comment by marijohannessen** [comment]
Closing this issue as it seems to be resolved.
