### ISSUE TITLE
Modal getting clipped when placed inside TableToolbarContent - Carbon 10

### ISSUE THREAD

**Issue by aniruddhj** [carbon-design-system/carbon#4592]
## What package(s) are you using?
[ x ] `carbon-components`
[ x ] `carbon-components-react`

## Detailed description

I have a DataTable with TableToolbarContent (Carbon 10). The button on the toolbar should open a modal for user action. When I click on the button, the modal does open but it only appears on TableToolbar region. Attaching a screen capture for the same.

![apikey-modal](https://user-images.githubusercontent.com/10608566/68324368-3eaeed80-0095-11ea-9ef4-d825fc5b8638.gif)

 - React CodeSandbox: 
https://codesandbox.io/embed/dank-rain-c6bh3?fontsize=14

Steps to reproduce: 
1. Click on the Open Modal button below the search bar inside the DataTable.
2. Right click and inspect the element. The Modal will be only restricted to the TableToolbarContent region

**Comment by asudoh** [comment]
Hi 👋 you need to put `<Modal>` at the top-level of your app (your React render), whereas you can keep the launcher button in `<TableToolbarContent>`. Hope this helps!

**Comment by Akaike0** [comment]
That is a bad solution, why do we need to do the extra work if every other UI libraries fixed issues like that? I'm talkin' about material-ui, ant-design.
