### ISSUE TITLE
Refactor Combobox in Accordance with W3C Authoring Practices Guidelines

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#4595]
closes #3416 
closes #3418 
closes #3419 
closes #3740 

The current implementation of our Combobox has serious usability/accessibility issues across all the screen readers we're tracking for our requirements. A refactor in accordance with the [W3C Authoring Practices Guidelines 1.2 example](https://raw.githack.com/w3c/aria-practices/aria1.2-combobox-proposal/examples/combobox/combobox-autocomplete-list.html) for a Combobox is the the way forward here.

Other notes:
_I'm not sure how much we're getting from Downshift anymore and it's removal would help simplify maintenance and accessibility work._

**Comment by snidersd** [comment]
@dakahn I was recently advised that there is a new [ARIA Authoring Practices 1.2 ](https://www.w3.org/TR/wai-aria-practices-1.2/#combobox) pattern for Combobox that you might want to take a look at.
