### ISSUE TITLE
(code snippet) Need to inherit tooltip component for feedback message.

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4604]
Currently the tooltip that appears for the feedback message does not have the correct spacing and the text is very close to the container.

Example:
![Screen Shot 2019-11-07 at 11.57.13 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/61f0b786-c95e-4fb0-81a3-eaaa7f937abf)

We need to be using the tooltip component in these scenarios for code snippet.

**Comment by emyarod** [comment]
going to split this into multiple PRs: one to address copy button (which single and multiline code snippet consumes), one to address single and multiline code snippet (after the copy button changes), and one to address inline code snippet

**Comment by laurenmrice** [comment]
okay 👍
