### ISSUE TITLE
[Modal] Design enhancements - Ready

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#4607]
Introducing new modal enhancements and variations.
Check indicates dev delivered. 

- Sizes: https://github.com/carbon-design-system/carbon/issues/4607#issuecomment-551198387
   - [x] 4 sizes
   - [x] Responsive widths
   - [x] Max heights
   - [x] Overflow content
   - [x] Margin-right
- Types: https://github.com/carbon-design-system/carbon/issues/4607#issuecomment-551959471
   - [x] Passive
   - [x] Transactional
   - [x] Danger
   - [x] Input
   - [ ] Progress (formerly Linear) 
- Button groups: https://github.com/carbon-design-system/carbon/issues/4607#issuecomment-551996283
   - [x] 1 button
   - [x] 2 buttons
   - [x] 3 buttons
- Examples: https://github.com/carbon-design-system/carbon/issues/4607#issuecomment-552002580
- Docs

**Sketch file:**
https://ibm.box.com/s/38r605b633kvmpt5qcv67owqn6imfmhk

**Comment by aagonzales** [comment]
# Modal sizes
- XS
- Small
- Default
- Large

## Widths 
![image](https://user-images.githubusercontent.com/11670886/68413537-13d79e80-0154-11ea-9708-53cb3a99fe5a.png)

The width's will vary based on breakpoint

Breakpoint | XS  | Small | Default | Large 
-- | -- | -- | -- | --
1584 | 24% | 36% | 48% | 72%
1312 | 24% | 36% | 48% | 72%
1056 | 32% | 42% | 60% | 84%
672 | 48% | 60% | 84% | 96%
320 | 100% | 100% | 100% | 100%

% corollate to an approximate column count

% | ~# of columns
-- | --
72% | 12
60% | 10
48% | 8
42% | 7
36% | 6
24% | 4

## Heights 

![image](https://user-images.githubusercontent.com/11670886/68435333-b0b03100-0180-11ea-9666-9c1b0a691eab.png)

Modal size | Max-height
-- | --
XS | 48%
Small | 72%
Default | 84%
Large | 96%

### Overflow content
Use a fade to indicate there is content below the fold

![image](https://user-images.githubusercontent.com/11670886/68436605-194cdd00-0184-11ea-847c-8cf34919783d.png)


## Margin-right

- If modal is **smaller** than 32% then the margin-right should be **16px/1rem**
- If modal is **greater** than 32% then the margin-right should be **20% of the modal width**

![image](https://user-images.githubusercontent.com/11670886/68416226-b0506f80-0159-11ea-85c6-ce4408975d5b.png)

- **Note:** Margin-right padding rules only apply to body copy. Other components, such as input fields can span the full width of the modal.

![image](https://user-images.githubusercontent.com/11670886/68416702-9d8a6a80-015a-11ea-95e7-c8fde4d14a1f.png)

**Comment by aagonzales** [comment]
# Modal Types

![Modal - types-2](https://user-images.githubusercontent.com/11670886/68509227-10b4df00-0236-11ea-88e7-af5f5492350b.png)

### Changes from existing modal
- Title can be used as the primary message in passive and transactional modal. It can also be used as the input label if only one action is being preformed (see example section). 
- New: Linear direction modal with built in progress indicator.

**Comment by aagonzales** [comment]
# Button groups

![Modal - button groups](https://user-images.githubusercontent.com/11670886/68511845-7015ed80-023c-11ea-8967-90b135bcb5ad.png)

**Guidance:** 
- Modals can have 1, 2 or 3 buttons. 
- 4 Buttons is not allowed.
- 3 Buttons should only be used a rare scenarios
- If a "cancel" is needed outside of the 2 button set scenario than it should be a ghost button and left aligned. 
- Button are sticky to the bottom of the modal window
- Never inset (add padding to the bottom and side) buttons on modal. 
- Modals with more than 2 buttons is not recommend for mobile. (potential solution is split button)

**Comment by aagonzales** [comment]
# Examples
![Example 1](https://user-images.githubusercontent.com/11670886/68512962-6f328b00-023f-11ea-9597-55493b41c1bc.png)
![Example 2-a](https://user-images.githubusercontent.com/11670886/68512963-6f328b00-023f-11ea-8291-88101717e651.png)
![Example 3a](https://user-images.githubusercontent.com/11670886/68512964-6fcb2180-023f-11ea-8b83-483eccf07b55.png)
![Example 4](https://user-images.githubusercontent.com/11670886/68512966-6fcb2180-023f-11ea-97b1-03d2bf226515.png)
![Example 5](https://user-images.githubusercontent.com/11670886/68512967-6fcb2180-023f-11ea-9e6a-b57c4fd575ee.png)

**Comment by elizabethsjudd** [comment]
@emyarod I'm guessing these enhancements are only being made to React. Are their plans to carry them down to Vanilla (specifically the change so users can not click outside the transactional modal to close it)?

**Comment by elizabethsjudd** [comment]
@aagonzales looking at this comment (https://github.com/carbon-design-system/carbon/issues/4607#issuecomment-551959471), what's the expected behavior of a keyboard users when they press `ESC` for a transactional modal?

**Comment by aagonzales** [comment]
Pressing `ESC` on a transactional modal would close the modal without saving or submitting any data and return the user/focus to the main page.

**Comment by emyarod** [comment]
@elizabethsjudd the visual changes should appear for both vanilla and React. I don't think the UX changes have been implemented yet in either library but I can port it to vanilla when it's done

**Comment by elizabethsjudd** [comment]
Thank you @emyarod!

**Comment by grahamharper** [comment]
+1 for support for the 3 button modal, both flush-left and left-aligned "Cancel" variants.

How should this behave in a narrow viewport? Buttons stack?
![image](https://user-images.githubusercontent.com/2853295/106159070-554ed200-617c-11eb-9424-e29accb38467.png)
