### ISSUE TITLE
React warnings in console with ExpandableTile

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#4609]
Here's a code sandbox.  You can see all the versions in there.
https://codesandbox.io/s/codesandbox-gx69y?fontsize=14

Here's a screen shot of the error in the code sandbox.  The console is not expanded by default.  You have to click on the error number.
![image](https://user-images.githubusercontent.com/30597411/68417005-9025ae00-0163-11ea-85b3-a781796cca83.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Likely that we need to exclude those props from the "misc props" list: https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/Tile/Tile.js#L462-L471 - A PR for that is appreciated.

**Comment by jendowns** [comment]
I can help with this one 👍 

Similarly, when running locally, I can see another error related to `maxHeight` on the component:

```
Warning: `NaN` is an invalid value for the `maxHeight` css style property.
    in div (created by ExpandableTile)
    in ExpandableTile (created by Container)
    in div (created by Story)
    in Story (created by Container)
    in div (created by Container)
    in StrictMode (created by Container)
    in Container (created by storyFn)
    in storyFn
```

It appears as though `maxHeight` is first `NaN` (before a real number is added) because `tilePadding` has no default value? 🤔 I can also address this in the PR.

**Comment by kglickman** [comment]
I'm still seeing this issue with carbon-components 10.7.4 and carbon-components-react 7.7.4.  How can I figure out which version the fix is going into?

**Comment by asudoh** [comment]
Hi 👋 you can go to https://github.com/carbon-design-system/carbon/releases to see a release contains a specific fix.
