### ISSUE TITLE
MultiSelect checkboxes are not carbon checkbox

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4612]
I noticed that in the [sandbox ](https://codesandbox.io/s/codesandbox-5mvwn)of the latest version of the library styles are not imported as they are in the react tutorial. However, in my local app in which the following components are used

    "carbon-components": "^10.7.3",
    "carbon-components-react": "^7.7.3",

I have to load styles in index.scss like below for styles to work. But even after this, the checkbox in MultiSelect are native checkboxes rather than carbon checkbox. Screenshot below.

```
@import 'carbon-components/scss/components/button/button';
@import 'carbon-components/src/components/multi-select/multi-select.scss';
```

![image](https://user-images.githubusercontent.com/54859354/68425009-cdda0500-016a-11ea-82ea-221e429509d4.png)

Can someone please point out what I am doing wrong???

**Comment by tahaimt** [comment]
@asudoh can you please take a look at this?

**Comment by tahaimt** [comment]
I noticed that in the sandbox html markup, there are a _:before_ and _:after_ element is inserted in the label of the checkbox, however in my local project they are not present. I am wondering if I am not loading the latest version of carbon-component-react even though they are the latest in package.json because this behavior seems like something that would come with JS MultiSelect classes rather than stylesheets.

**Comment by jendowns** [comment]
Hey @tahaimt! In the sandbox environment, the `MultiSelect` uses the correct checkbox styling because inside `./public/index.html`, the sandbox environment is importing all component styles via minified compiled css.

However, in your project, you are importing individual scss files for each component. And it looks like the checkbox styles are not being imported into the multi-select styles. This causes your multi select to have unstyled checkboxes.

This is a bug. 🤔 I can fix propose a fix if you like?

**Comment by tahaimt** [comment]
That'd be great @jendowns. I just noticed that I am indeed missing checkbox styles from my main scss.

**Comment by tahaimt** [comment]
That fixed it. Thanks.

**Comment by tahaimt** [comment]
Can you take a look at my other issues please @jendowns ? Do you mind if I tag you in them?

**Comment by tahaimt** [comment]
I would like to point out an issue in documentation related to MultiSelect. If you visit the [demo for Multiselect](http://react.carbondesignsystem.com/?path=/story/multiselect--default) then under knobs check the option for _Filterable (`<MultiSelect.Filterable>` instead of `<MultiSelect>`)_. Now open readme on the top right and you will notice that the story source now shows **FilterableMultiSelect** which is not a valid component.

**Comment by jendowns** [comment]
Oh thanks @tahaimt! You are right -- the component is `MultiSelect.Filterable`, not `FilterableMultiSelect`. 🤔 It looks like the display name is wrong. I have an idea to fix that one so I'll open a PR for it.
