### ISSUE TITLE
Pubish build-info.json in @carbon/icons

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#4613]
Since we're moving out from the monorepo we still need access to the `build-info.json` to generate our components. Ideally we should be able to continue `require`ing this from `@carbon/icons` ... definitely open to other options, but this seems like the most compatible 👍 

CC @joshblack

**Comment by joshblack** [comment]
@cal-smith definitely agreed, I think right now it's ignored but we could definitely unignore it for this use-case.

**Comment by cal-smith** [comment]
Awesome, sounds good 👍
