### ISSUE TITLE
Console log error for combo box where type is non multi

### ISSUE THREAD

**Issue by eddieibm** [carbon-design-system/carbon#4618]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [x] `carbon-components-angular`

## Detailed description

> Describe in detail the issue you're having.

The error message shows `Cannot read property 'content' of undefined` as following:
![1](https://user-images.githubusercontent.com/47797763/68432122-c114db80-0181-11ea-9bb0-eb61328cb581.png)

Because no item is selected when you first time access the page, so the `selected` is [] and `selected[0]` is null 
![2](https://user-images.githubusercontent.com/47797763/68432126-c540f900-0181-11ea-9a66-226effa11d67.png)

> Is this issue related to a specific component?
combo box

> What did you expect to happen? What happened instead? What would you like to
> see changed?
no console errors and empty value or null check should be in place

> What browser are you working in?
chrome
> What version of the Carbon Design System are you using?
latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
OMS BUC

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Did you mean to report it to https://github.com/IBM/carbon-components-angular?

**Comment by eddieibm** [comment]
that's right, sorry, let me close and report over there. thank you!
