### ISSUE TITLE
Visited Links do not show active style when clicked

### ISSUE THREAD

**Issue by vincentsnagg** [carbon-design-system/carbon#4620]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Visited Links do not display an active style when they are clicked (Links without the visited style are fine)

> Is this issue related to a specific component?

Links

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Visited links should also have an active state when clicked (black text and underline)

> What browser are you working in?

Chrome 78 but also Firefox + Safari

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health

## Steps to reproduce the issue

1. Access Link component (e.g., https://the-carbon-components.netlify.com/?nav=link or Carbon website)
2. Click on Link to induce visited state
3. Go back to Link to view visited state (https://the-carbon-components.netlify.com/?nav=link)
4. Click Link without releasing to see that the active state does not show

## Additional information

Link in Visited State
<img width="723" alt="Screen Shot 2019-11-07 at 5 45 09 PM" src="https://user-images.githubusercontent.com/3158307/68435485-61223300-0189-11ea-9797-1d1223bc1506.png">
Hover
<img width="738" alt="Screen Shot 2019-11-07 at 5 45 23 PM" src="https://user-images.githubusercontent.com/3158307/68435484-61223300-0189-11ea-8e84-c4a74256925f.png">
Mousedown (should have black text and black underline)
<img width="721" alt="Screen Shot 2019-11-07 at 5 44 59 PM" src="https://user-images.githubusercontent.com/3158307/68435486-61223300-0189-11ea-9afd-337cbe042f4b.png">
States from Carbon Design Kit (enabled, hover, focus, active, visited, disabled)
<img width="852" alt="Screen Shot 2019-11-07 at 5 50 49 PM" src="https://user-images.githubusercontent.com/3158307/68435531-82831f00-0189-11ea-8925-0cc77eaa1ccd.png">
(The focus state is also not the same in code and the Kit, but I agree with the coded implementation)

**Comment by jendowns** [comment]
Hey there! It looks like the color rule for `:active:visited` links is being overridden by the color rule for `:visited:hover`, which comes later in the link stylesheet. Here's how that looks in Chrome's dev tools:

![Screen Shot 2019-11-08 at 10 34 45 AM](https://user-images.githubusercontent.com/9057921/68494122-78a5fe00-0213-11ea-83f6-536e947632bb.png)
 

I can open a PR to propose a resolution 👍
