### ISSUE TITLE
files state of FileUploaderDropContainer is remembered and not cleaned up!

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#4637]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I used the FileUploaderDropContainer from this component ProjectDropContainer:
Sandbox: https://codesandbox.io/s/brave-voice-bdrx0

but I used it inside a Modal this time.
After selecting a file, and closing the Modal then reopining it again the last selected file is still shown there!
despite there is this line of code that should clean it:

`const [files, setFiles] = useState([]);`

**Comment by asudoh** [comment]
@emyarod Any thoughts? One thing that comes my mind is providing application control over the files array, assuming we haven't done that (yet). Another thing is just letting application re-mount stuffs in file uploader.

**Comment by emyarod** [comment]
@asudoh doesn't the application already have control of the files array? the codesandbox link doesn't reflect the text description of the issue at all for me, but my guess is that the application is not clearing the files array when the modal is closed

**Comment by asudoh** [comment]
@zbeedatm Given @emyarod believes application has control over the files array (thanks @emyarod!), would you try simply resetting the files array?

**Comment by zbeedatm** [comment]
I tried before opening the issue but will try again to figure out.
To explain, the main application has the Modal, inside the Modal I'm using the the < ProjectDropContainer> component, and the **files** is a property of the DropContainer component and not the main application.
I'm sending back the files to the main application by a callback event.

When I tried cleaning it up by such a code but with no luck:

`// function useForceUpdate(){
//     const [files, setFiles] = useState([]);
//     return () => setFiles(files); // toggle the state to force render
// }`

`function ProjectDropContainer(props) {
    const [files, setFiles] = useState([]);
    // console.log("files: ", files)

    //TODO - to clean up previous selected files
    // useForceUpdate();

    //TODO - cause to reset the files even when I select a new one
    // setFiles([])`

**Comment by emyarod** [comment]
you should have full control of the `files` array regardless. `ProjectDropContainer` is not exported by Carbon, it's an example application you copied that uses the file uploader. in your case it should probably contain your modal logic as well

it looks like the callback you tried to use returned a function but did not actually call it. but in any case your code sandbox doesn't reflect what you are describing so debugging is quite difficult

**Comment by zbeedatm** [comment]
Please use this sandbox:
https://codesandbox.io/s/fragrant-morning-267l5

Flow:
1) Press on Import button
2) Select a file
3) Close the Modal
4) Reopen the Modal (step 1)

The last selected file still apear!


BTW, I still have another issue when dropping the file (Issue #4519) :~, when browsing it's working fine... but when dropping a strange behavior occurs.

Will appreciate your help.

**Comment by emyarod** [comment]
again the selected files are not clearing because you are not clearing the list of selected files array. it is controlled by the application and does not happen automatically. here is a reduced example https://codesandbox.io/s/drag-and-drop-file-uploader-wlj05

a workaround for #4519 is to supply a value for the `accept` attribute

**Comment by asudoh** [comment]
Closing as a valid answer has been provided.

**Comment by zbeedatm** [comment]
Thanks a lot.
I used a hook for ComponentWillUnmout and cleared the files inside:

`function ProjectDropContainer(props) {
    const [files, setFiles] = useState([]);

    // useEffect(() => {
    //     console.log('mounted')
    // }, []);

    useEffect(() => {
        return () => {
            // console.log('will unmount');
            setFiles([])
        }
    }, []);`
