### ISSUE TITLE
November 2019 Endgame

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#4646]
This is the endgame schedule for our November 2019 iteration, which includes the
following projects:

- [Design System Support and website support](https://github.com/orgs/carbon-design-system/projects/14)
- [Theming(colors, type tokens, and size-related constraints)](https://github.com/orgs/carbon-design-system/projects/33)
- [Accessibility](https://github.com/orgs/carbon-design-system/projects/17) 
- [Patterns](https://github.com/orgs/carbon-design-system/projects/24) 
- Component Documentation 
- [Icons](https://github.com/orgs/carbon-design-system/projects/20) 

# Schedule

- Endgame leader: @abbeyhrt 
- Endgame sidekicks: @jillianhowarth, @aledavila 
- 11/08: Code Freeze (EOD)
-  11/11: Release Candidate
- 11/18: Production Deploy 
- 11/20 - Publicly announce  

## Monday 11/11

- [x] Cut release candidate from master 
- [ ]  Reach out to teams and figure out critical dependencies that are ship/no-ship criteria
- [x] ask teams to comment project outcomes in endgame issue (set hard deadline)
- [ ] Complete first round smoke tests 
- [ ] Share with Carbon Insiders for first round of testing

## Tuesday 11/12

- [ ]  Collect first round of feedback from Carbon Insiders (if available)
- [ ] Triage release-specific issues and bucket them into two categories:
       - [ ] Stop release
       - [ ] Ship with known issues
- [ ] Coordinate merging of bug fixes related to release
- [ ] Cut next Release Candidate, if applicable
       - [ ] Share newest release with Carbon Insiders for additional rounds of
        testing

## Wednesday 11/13

- [ ] Collect second round of feedback from Carbon Insiders (if available)
- [ ] Coordinate merging of bug fixes related to release
- [ ] Cut next Release Candidate, if applicable
  - [ ] Share newest release with Carbon Insiders for additional rounds of
        testing

## Thursday  11/14 & Friday 11/15
- [ ] Collect final round of feedback from Carbon Insiders (if available)
- [ ] Run final smoke tests on release
- [ ] Make determination to release on following Monday

## Monday 11/18 
- [ ] Release Monday morning
- [ ] Coordinate release communications on Slack and Twitter
- [ ] Summarize top-level release notes for next blog post

**Comment by jnm2377** [comment]
# Brand
- Global spacing updates in Gatsby Theme
- Update the IDL Colors page to v2 color palette
- Fix image gallery bugs in IDL and Carbon site
- Fix accordion padding bug in Gatsby Theme
- Deprecate `berlin-brandenburg` pictogram for `berlin-brandenburg-gate` (new)
- Update IDL side navigation: renamed `Logos` to `IBM Logos`
- Continued work for Carbon website live component demo
