### ISSUE TITLE
Dark themes: ui-02 and ui-03 have same values.

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4647]
Need to figure out what values need to be represented for the Dark themes so they don't blend in together when being used together.

Currently we are finding we are having issues with Data table, Overflow menu, for light variants (could be more components). The rules and headers blend in with the background.

Example:

![Screen Shot 2019-11-11 at 11.10.11 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/81164931-a1da-4e58-a785-02f95a15d150)

**Comment by laurenmrice** [comment]
Currently the values for ui-03 in Gray 90 and Gray 100 are the same as the values for ui-02. One way we could get around this could be by changing the ui-03 values in the dark themes to be a step lighter than the ui-02?

Need to see if this value change will work fine for other places where we use ui-03 in our components

Example:
![Artboard Copy 4](https://user-images.githubusercontent.com/43969356/68695562-e8342a00-0540-11ea-9857-98d6b17be13b.png)

**Comment by aagonzales** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon/issues/2439

**Comment by tw15egan** [comment]
@aagonzales should we close this or #2439?

**Comment by aagonzales** [comment]
Let's kill this on in favor of the original.
