### ISSUE TITLE
Required TextInput shows red border before user has had a chance to interact with it

### ISSUE THREAD

**Issue by dpalmier** [carbon-design-system/carbon#4658]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If the TextInput component is included with required=true, the input field is initially rendered with a red border at the bottom, implying that there is a validation error.  According to our IBM UX Design team (e.g., dignum@us.ibm.com and Cassie.Sharp@ibm.com), fields should not initially indicate validation errors.  Instead, validation errors should only be indicated after the user has had a chance to interact with the component / page.

> Is this issue related to a specific component?
In this case, we observe the problem with the TextInput component, but I suspect it may also exist with other components (e.g., TextArea and others??) where required=true can be specified.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The recommendation from our IBM UX Design team is that the field should not initially render the red border.  Rather, the red border should be rendered only under the following conditions:
1. onBlur and the field is empty.
2. The user updates the field such that it used to have a value and it is now empty (e.g., they delete the last remaining character).

> What browser are you working in?
Chrome, Firefox, and Edge.

> What version of the Carbon Design System are you using?
7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
I work on IBM Cloud Identity. The product is continuously integrated / delivered. This is a current problem in production.

## Steps to reproduce the issue

1. Include a TextInput component on a page, and specify required=true.
2. When the page loads, observe that the TextInput field initially shows a red border on the bottom.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - A quick glance at the code doesn't reveal any code in `<TextInput>` that handles `required` prop. The red border typically is handled by `invalid` prop instead, which effectively relegates such "required" check to application code.

If you still believe the `<TextInput>` code has a problem, would you create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by aledavila** [comment]
Hi there! I'm gonna go ahead and close this issue. If you still believe this is a bug with our component please go ahead and create a reduced case with the link Akira provided. Thanks
