### ISSUE TITLE
Carbon React Modal goes super tall when the width goes below 840px

### ISSUE THREAD

**Issue by xpander53** [carbon-design-system/carbon#4663]
## What package(s) are you using?
"carbon-components": "10.4.1",
"carbon-components-react": "7.4.1",

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Not go super tall but continue to just decrease in width.

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson for Clinical Trial Matching

You can see it here - make the built in browser go narrow:
https://codesandbox.io/s/codesandbox-n204q

**Comment by jendowns** [comment]
Hey @xpander53! What you see in narrow screen sizes is the mobile-first style rules applied to the `Modal`, which makes the component fill 100% of the screen when the available space is small (like for a mobile device).

You can see the media queries being applied for larger screen sizes (see the 2 rule blocks for `min-width: 66rem` and `min-width: 42rem` media queries below):
![Screen Shot 2019-11-12 at 3 19 23 PM](https://user-images.githubusercontent.com/9057921/68711833-12e1ab00-0560-11ea-9db9-940a28145390.png)

The breakpoints are applied here:
https://github.com/carbon-design-system/carbon/blob/61c5ca0606a6e3550e436d890cffb6a174f4019c/packages/components/src/components/modal/_modal.scss#L85-L101

**Comment by joshblack** [comment]
Thanks so much for the response @jendowns! This is exactly right and should be the intended behavior. Let us know if this is an issue!
