### ISSUE TITLE
Toast Notification: timeout prop

### ISSUE THREAD

**Issue by josefaidt** [carbon-design-system/carbon#4666]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

Toast notification runs `onCloseButtonClick` handler on timeout. When the timeout is achieved, I notice the behavior of it also running the click handler. This may be unintended. Am I using the component as expected? I'd rather not push the bounds of the component, though to me the behavior seems odd.

## Relevant information

If I have a notification state that gets updated when clicking the toast's close button - for example, marking the notification as "read" -  the intended user experience is to see the notification toast timeout, but still appear as "unread" in the notification drawer. If the toast times out, the notification should remain unread - e.g. click handler should not be executed since I'm not clicking on the button in which the handler is attached.

## Workaround

Leveraging the same idea of a toast timeout, I am conditionally rendering the notification. This way the click handler will not be executed.

```js
const Notification = ({ children, data, ...rest }) => {
  const [isShown, setIsShown] = React.useState(true);
  const { date, type, title, text: description, id } = data;
  const timeStamp = date.toLocaleTimeString();

  React.useEffect(() => {
    const timer = setTimeout(() => {
      setIsShown(false);
    }, 5 * 1000);
    return () => clearTimeout(timer);
  }, []);

  if (isShown) {
    return (
      <StyledToastNotification
        {...rest}
        className="lvp--notification-toast"
        caption={timeStamp}
        hideCloseButton={false}
        iconDescription="Close Notification"
        kind={type}
        notificationType="toast"
        role="alert"
        subtitle={description}
        timeout={0}
        title={title}
      >
        {children}
      </StyledToastNotification>
    );
  } else return null;
```

**Comment by josefaidt** [comment]
For reference, https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Notification/Notification.js#L330

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting, and good catch - From what I see, it seems to have been a naming mistake, it simply should have been `onClose()`. Given the callback initiated by timer doesn't have the event object in the arg, application code can detect if it comes from user gesture or from timer.

**Comment by josefaidt** [comment]
Would this naming change also affect the click handler? Or add another prop called `onClose`?  In my opinion I think it'd be beneficial to have both, and perhaps rename `onClose` to `onRequestClose` to follow the nomenclature of props on `<Modal />`. 

I may be able to make this change and open a PR if that's something yall would be interested in, though I'm not versed on Storybook enough to confidently make changes to the documentation as well.

**Comment by asudoh** [comment]
Having a proposed change will be nice, just a few:

* My thought is on just renaming, because the timeout as well as close-on-click both "closes" the notification
* The naming change is a breaking change, and thus we should keep the older name. You can search for `import deprecate from '../../prop-types/deprecate'` in the codebase to see how to cope with that
* `onRequestClose()` name in `<Modal>` is because `<Modal>` doesn't actually close itself (It's application code to close it)

If you search for `addon-actions` in `*-story.js`, you'll find how to cope with that name change in the story. Thanks!
