### ISSUE TITLE
Data Viz Palette - Line graph colors difficult to read

### ISSUE THREAD

**Issue by ncaudell** [carbon-design-system/carbon#467]
### Data Viz Color Palette - General Issue

For a Carbon line graph with multiple lines, the recommendation is to use primary-01 and then -02 and then -03 etc. However it is very difficult to read the different between primary-01 and primary-02 (as an average sighted user) when the two are on a line graph together.

Ex: In Carbon_Design-Kit_8.0.0.sketch, the line graph example showing Six Month Taco Consumption by Restaurant has El Chilito & Pueblo Viejo, but the colors of the two lines are difficult to tell apart in the graph itself

![screen shot 2017-12-11 at 10 28 02 am](https://user-images.githubusercontent.com/24572503/33852043-8fcbe97e-de7e-11e7-902f-a2fc026f3562.png)

A quick fix would be to skip primary-02 and use primary-01 with primary-03 or 04, so maybe just switching up with build order for line graphs would work so you get the most contrast between the two colors. (The analogous colors look great with donuts or bar charts, but having extremely different colors on line graphs is easier to read than analogous.)

![screen shot 2017-12-11 at 2 27 28 pm](https://user-images.githubusercontent.com/24572503/33852269-749f0a90-de7f-11e7-9dd8-c8f572e3a2ed.png)
(the same issue occurs with the scatter plot)

(I work on APM for DevOps (formerly Bluemix Availability Monitoring) within Hybrid Cloud)

**Comment by tay-aitken** [comment]
Hi @ncaudell I promise we haven't forgotten about this issue. Thanks for bringing it to our attention! Will let you know when we have updates on this. If you have any color palette suggestions feel free to share.

**Comment by tw15egan** [comment]
FWIW, on the code side, we shifted the palette down 1 so that the greenish color appears first: 

<img width="974" alt="screen shot 2018-05-14 at 10 09 42 am" src="https://user-images.githubusercontent.com/11928039/40006027-f6cd3af2-575e-11e8-8a6c-82bdebb405db.png">

**Comment by JennyLanier-UXDesign** [comment]
I am working on VPC and Dmitri brought up an issue with color accessibility for our data viz. This is his message:

> As you can see in the attached screenshot, the colors we use for our monitoring graphs are all very similar. They are all dark, and they include only two greens, a blue, and a blue so dark it is nearly black, and black. They are very difficult to tell apart.
> 
> We would like to have colors that are easier to tell apart and more visually appealing. We must use colors that are acceptable by modern accessibility standards which must have a certain amount of contrast and must be different for people with color blindness.

![image 5](https://user-images.githubusercontent.com/40404432/41617634-a6e9fa78-73c6-11e8-8293-9f984b4055d8.png)

When would be the earliest we could get revised colors? We need to make this change soon since it's in VPC.

**Comment by tw15egan** [comment]
There is currently no one working on this (to my knowledge), and it has not been slated on an upcoming sprint. If you would like to recommend a palette of accessible colors, we would gladly take those into consideration. Feel free to sync up with @tay-aitken who did a lot of research into these colors. 

All of the Data Viz components accept an `array` of colors, so the change can be made today without any dev work on our end.

**Comment by tay-aitken** [comment]
@JennyLanier-UXDesign and I did a sync on slack!
