### ISSUE TITLE
Dropdown Menu Not Visible in Modal

### ISSUE THREAD

**Issue by PatrickDuncan** [carbon-design-system/carbon#4684]
## Brief description

Similar issue to #1064 where dropdowns don't work in modals.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Dropdown menu is not visible when nested inside of a modal. It displays correctly outside of a modal.

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the dropdown menu to be visible inside of the modal

> What browser are you working in?

Chrome 78.0.3904.70

> What version of the Carbon Design System are you using?

- `carbon-components 10.7.3`
- `carbon-components-react 7.7.3`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Monitoring. This is definitely a blocking issue as the designs I'm following require a dropdown inside a modal dialogue.

## Steps to reproduce the issue

1. Check out https://codesandbox.io/s/codesandbox-cnn1z

## Definition of Done

- [ ] Dropdown menu is visible and selectable
- [ ] It would nice if there was a unit test that had a dropdown in a modal and selected an option from it. But I guess programmatically it wouldn't be hard to select.

**Comment by PatrickDuncan** [comment]
I played around with the css and found that if you remove `flex-direction: column;` from `.bx--modal-container`  you can see the dropdown menu, but that breaks the modal's layout.

I don't think the z-index is the issue this time around.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - It's an inherit limitation in non-floating types of menus whose menu body is placed within the menu's container element. The container element `<div class="bx--modal-content">` should be changed to show the menu body in your particular case (`overflow:visible`).

**Comment by PatrickDuncan** [comment]
Thanks @asudoh 

Here's the solution he provided: https://codesandbox.io/s/codesandbox-u5y7q

The dropdown is cut off heavily and it's getting a little hacky.

**Comment by asudoh** [comment]
You can do the same for `<div "bx--modal-container">`, too.

**Comment by PatrickDuncan** [comment]
Thanks again @asudoh! I need to learn more about css floats haha

FYI to future readers:
Add `overflow:visible` to:
`bx--modal-content` to make the dropdown menu visible
`bx--modal-container` to make the dropdown menu float above the modal, removing the border clipping
https://codesandbox.io/s/codesandbox-bgdj5
