### ISSUE TITLE
Dropdown component does not automatically drop up vs. down like native Select element

### ISSUE THREAD

**Issue by dpalmier** [carbon-design-system/carbon#4686]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If the Dropdown component is placed at the bottom of a page, clicking to open it displays the contents downward, causing those contents to be only visible if you scroll down on the page.  Note that I am not talking about scrolling through the dropdown items themselves, I am talking about having to scroll on the main page containing the Dropdown component.

> Is this issue related to a specific component?
This issue is related to the Dropdown component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Ideally, the Dropdown component should behave like the native HTML Select element, whereby the contents are displayed either downward or upward, depending on whether or not there is enough space to display the contents downward on the page.

> What browser are you working in?
Chrome, Firefox, and Edge.

> What version of the Carbon Design System are you using?
7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
I work on IBM Cloud Identity. The product is continuously integrated / delivered. This is a current problem in production.

## Steps to reproduce the issue

1. Create a page that has vertical scrolling.
2. Include the Dropdown component on the page such that it is at the bottom of the page.
3. When the page is displayed, click to open the Dropdown component.  Observe that you cannot see the contents of the Dropdown component unless you scroll down on the main page.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by dpalmier** [comment]
Please consider implementing this enhancement.

**Comment by sstone2423** [comment]
Still broken. Our team tried changing the stack index to no avail.

![Screen Shot 2020-03-18 at 2 33 47 PM](https://user-images.githubusercontent.com/25177649/76999967-8c7e1100-6925-11ea-8eff-36ce95d871ec.png)
![Screen Shot 2020-03-18 at 2 33 33 PM](https://user-images.githubusercontent.com/25177649/76999968-8c7e1100-6925-11ea-9dd1-cae8b24aeed3.png)
