### ISSUE TITLE
Table settings menu

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#4687]
### Summary

We are requesting a data table settings menu component based on the design mocked up here https://www.carbondesignsystem.com/components/data-table/usage. 

<img width="1416" alt="Screen Shot 2019-11-14 at 10 37 25 AM" src="https://user-images.githubusercontent.com/39408106/68897311-df835580-06f2-11ea-99ba-1338d0bf8b26.png">

In addition to displaying row height it would also allow the user to hide and show columns. 

**Proposed design:**

![image](https://user-images.githubusercontent.com/39408106/70924434-1b118800-1fef-11ea-83e1-220363115b4c.png)

![image](https://user-images.githubusercontent.com/39408106/72372729-802ecb00-36cc-11ea-8122-a9fa36751c32.png)

![image](https://user-images.githubusercontent.com/39408106/73031417-a3aaf180-3e01-11ea-9f58-7fe75702191c.png)

![image](https://user-images.githubusercontent.com/39408106/73031401-9c83e380-3e01-11ea-9129-eabfe79d4b82.png)

### Justification

Over a third of IBM Cloud tables are based on a Softlayer table that offer edit column functionality. If we don't add this functionality to the Carbon data table, users will lose that existing functionality when our platform moves to Carbon X. We also have research showing that users would like to be able to edit their columns, especially on heavily used tables such as device or resource list (we can share quotes as needed). For example, one user had an internal site that only used private IPs, and he wanted to hide public IPs. Editable columns were also a frequently mentioned functionality by platform and service teams alike.

### Desired UX and success metrics

The desired UX is that users can see the columns that make sense for the job(s) they are trying to complete. For users that already enjoy this feature on Softlayer tables, the goal is to preserve existing functionality. We will track clicks on the setting menu as well as the number of users who edit columns on a given table.

### "Must have" functionality

- A user can select row height options
- A user can select and deselect columns
- User can scroll if there are more column options than fit the dropdown
- Must meet accessibility standards
- A designer can choose to ONLY include row height or edit columns 
- After settings menu reaches it's **max height** (496px), edit columns section should **scroll**
- Responsive (see design above)

Nice to have: 
- **_After_** a user closes the settings menu, any checked columns move to top of edit columns section and appear there the next time they open the menu.
- User can reset to default (design needs to add this to mockup)

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables in January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.

### Available extra resources

Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

**Comment by vsnichols** [comment]
@loganmccaul @holmansze ^

**Comment by holmansze** [comment]
There is no existing Carbon React component that supports the edit columns menu in the above design.  The closest one being `MultiSelect`.

The `MultiSelect` component is designed for a flat list of items and it has an input field for filtering.  The edit columns menu has no input field.  It uses an icon as the trigger, and has groups of form items (radios, checkboxes).  It is really a form in a menu.

Instead of overloading `MultiSelect` with something that is fundamentally different from its nature, I would like to propose a new component called `FormMenu`.  I will send a PR for comments/reviews when it is ready.

**Edit Columns Menu (in the above design):**
![image](https://user-images.githubusercontent.com/30137991/69093241-12438b80-0a1c-11ea-80d4-787663eb6040.png)

**MultiSelect (existing Carbon React component):**
![image](https://user-images.githubusercontent.com/30137991/69093295-2c7d6980-0a1c-11ea-9e52-7834f3293448.png)

**Comment by asudoh** [comment]
The closest seems http://react.carbondesignsystem.com/?path=/story/deprecated-toolbar--default, but #4097 seems to deprecate it and I cannot see something similar in data table stories.

@carbon-design-system/design Does anybody know any background? Is it something that should still exist...? Thanks!

**Comment by holmansze** [comment]
Thanks @asudoh for your input.  That helps!

As discussed with @joshblack , `Toolbar` isn't supposed to be brought along into Carbon 10 and was hence deprecated.  The biggest reason was that `TableToolbar` superseded this component use-case.

For @vsnichols 's design I just need `ToolbarTitle` and `ToolbarOption` from the deprecated `Toolbar`, which are both very lightweight/simple.  I will port these to `TableToolbar` and include that in my PR.

It will look something like this:
![image](https://user-images.githubusercontent.com/30137991/69206183-f9210480-0b19-11ea-886e-eacb803a30b6.png)

**Comment by sstrubberg** [comment]
You can do with [Popover](https://react.carbondesignsystem.com/?path=/story/components-popover--auto-align) now or use these...

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowheightsettings--default-settings-usage-story

https://carbondesignsystem.com/patterns/disclosures-pattern/#settings-and-filter-menus
