### ISSUE TITLE
Animated z-index on Modal leads to visual issues

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#4690]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary
In the carbon-components styles, the `z-index` property of the Modal component is transitioned. This leads to visual issues when other "high" components are in play (such as a sidebar) - see example at the bottom.

is this transition intentional or can we remove it?

## Relevant information

![carbon-modal](https://user-images.githubusercontent.com/28265588/68931489-efea0d80-0790-11ea-850d-0dd042bc82cc.gif)
Code: https://codesandbox.io/s/carbon-modal-z-index-issue-etl35

**Comment by sabov** [comment]
Another issue with animating `z-index` prop is that it forces browsers to re-paint each frame:

https://csstriggers.com/z-index

> Changing z-index does not trigger any geometry changes, which is good. But since it is a visual property, it will cause painting to occur. Painting is typically a super expensive operation, so you should be cautious.
