### ISSUE TITLE
No tooltip when components are disabled

### ISSUE THREAD

**Issue by tom-youd** [carbon-design-system/carbon#4691]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When an OverflowMenuItem, Link or HeaderMenuItem component is disabled it is not apparent why it is disabled. You should be able to pass in a prop so the user knows why the component is disabled and how it be enabled.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Explained above

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
We work in the ICP4I team we have a release coming up but it's not 'stop ship' because of this issue. We would want this to be fixed ASAP

## Steps to reproduce the issue

1. Add a title and disabled attribute to these components
2. view in a browser, no tooltip is displayed

## Additional information

- n/a

**Comment by tom-youd** [comment]
Any progress on this?

**Comment by aledavila** [comment]
Hi there sorry there is no current work being done on this it is currently in the backlog. Being open source we do accept contributions to our project.

**Comment by tw15egan** [comment]
> Expanding on @tw15egan 's point. If you're using a tooltip to communicate to your users _why_ a form element is disabled you have created accessibility issues for any non-mouse users. Screen readers in particular will **totally ignore** a `disabled` form element.

Closing this as it is working as expected, and there are no plans to add functionality to disabled items. 

Ref https://github.com/carbon-design-system/carbon/issues/5865#issuecomment-615399417
