### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon#4692]
### Summary

Need an alert component to list and manage notifications from different sources and different level of importance.

Request for both design and development

### Justification

This alert mechanism is to provide a complete user journey within specific context.
It will help many product teams, manage notifications coming from various sources and with various level of importance.

### Desired UX and success metrics

Upon page load an alert indicator is shown in the banner, to indicate there are one or multiple notifications of interest related to the page content.
Metrics to measure success of this component can be calculate with the CTR (click thru rate), and the count# of notifications accessed.

### "Must have" functionality

Must have a clear alert visual, with proper placement, visual weight and cohesiveness with the rest of the UI.
Must show a list of notifications, with title and source.

### Specific timeline issues / requests

1Q2020

### Available extra resources

TBD

### Attached image

![image](https://user-images.githubusercontent.com/11738743/68958017-41969600-0799-11ea-96ba-f1f4d966a6b0.png)

**Comment by designertyler** [comment]
Hi @aiproulx thank you for this submission. I wanted to follow up and see if you and your team went ahead and moved forward with these designs and if you could share anything in addition to what is in the original issue.

We're adding this feature to our backlog and any specs or insights you might have gained since this issue was opened would be helpful.

**Comment by aiproulx** [comment]
Hi @designertyler we implemented our own custom component. We are in the midst of a full app redesign. We are not sure yet if we will need this component in the new app.
