### ISSUE TITLE
(inline notification) The action button is misalligned

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4697]
The action button is riding very high in the top of notifications when it is present.  It should be aligned inside the container with the type  

![Screen Shot 2019-11-15 at 12.32.10 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/787ee0dd-ee3e-4a0a-bfa2-0fa985d343e3)

**Comment by jendowns** [comment]
Hey @laurenmrice I believe this was fixed in #4569 but even though it has been merged, I don't think it has been released yet 🤔

**Comment by laurenmrice** [comment]
Okay thanks Jen for clarifying!! I am gonna keep this open in the meantime and close once its been released. 👍

**Comment by laurenmrice** [comment]
resolved
