### ISSUE TITLE
(search) 40px search is not in react?

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4699]
We need to add the 40px search into react (it is in vanilla). 

I thought we did this awhile ago according to this PR: https://github.com/carbon-design-system/carbon/pull/4238 but seems like for some reason its no longer there.

Ref: https://github.com/carbon-design-system/carbon/pull/4237#issuecomment-539266146

**Comment by asudoh** [comment]
Hi @laurenmrice I think #4238 addresses this. Would you clone the latest master and run that, or try https://deploy-preview-4238--carbon-components-react.netlify.com/?path=/story/search--default? Thanks!

**Comment by laurenmrice** [comment]
@asudoh I do not see it currently live in React. Are you saying that it just has not been released yet ?

**Comment by asudoh** [comment]
@laurenmrice Seems so. I guess it'll be in next feature release (`v10.8.0`).

**Comment by laurenmrice** [comment]
resolved
