### ISSUE TITLE
Data table - first row has incorrect hover effect 

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#47]
I noticed the left and right border/outline is missing when hovering over the first table row.

![screen shot 2017-04-27 at 8 17 50 am](https://cloud.githubusercontent.com/assets/17085131/25483053/4127a96c-2b22-11e7-8b9b-f1e0267dfe9c.png)

**Comment by chrisdhanaraj** [comment]
Hey @alisonemiller, what version of the components are you on? Looks like the example on the website has the left-right border - http://carbondesignsystem.com/components/data-table/code

**Comment by ghost** [comment]
Is the documentation site up to date? I thought a fix was put in to have a border around the table, which I don't see in the example.

Related PR: https://github.com/carbon-design-system/carbon-components/pull/41
