### ISSUE TITLE
Enable Skeleton Screens

### ISSUE THREAD

**Issue by jakobleonard** [carbon-design-system/carbon#470]
Huge benefit would be to leverage the concept of skeleton screens for the IBM Carbon Design...

Sure that your team has looked into or consider this, but I work on a Product at IBM and I know our team would be immediately interested in introducing these concepts.

We find users complaining about the load time of our app and have done much to speed it up...but there is also the perception side introduced by the UX that we would like fix. Hoping to have a discussion on incorporating skeleton screens into IBM design

https://www.sitepoint.com/how-to-speed-up-your-ux-with-skeleton-screens/

**Comment by bsonefeld** [comment]
Hey @jakobleonard ! Thanks for your feedback, we love the idea of skeleton states as well! It's definitely something we've looked into, but just haven't had the resources to implement it within our components. If you have any other articles or research, please send them our way!

**Comment by alisonjoseph** [comment]
closing this as skeleton states have been added
