### ISSUE TITLE
BreadcrumbItem only works if href property is provided

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon#4705]
If you want to actually use the BreadcrumbItem then you need to provide an href property on each item. Without the href the BreadcrumbItem causes an error. You can render your own anchor tag as a child of the BreadcrumbItem but the link is rendered as if it's disabled. This does not work well for those who want to use react-router for client routing, and have a BreadcrumbItem with only an onClick and no href. Setting href to `javascript:void(0)` might work in the short-term but when react starts disallowing javascript URLs this will not be an option. So there are probably two issues involved: the `bx--link` renders as disabled if the `href` property is missing, and the BreadcrumbItem requires an `href` or it breaks.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Unable to create a usable BreadcrumbItem (or any link at all really) without an href property.

> Is this issue related to a specific component?

BreadcrumbItem (and probably Link)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I think the BreadcrumbItem should allow either an href or an onClick (or both), and the link should not be disabled if either is provided.

> What browser are you working in?

Latest chrome

> What version of the Carbon Design System are you using?

v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Kubernetes Service

We are currently working around the issue by not using the BreadcrumbItem, and instead using our own anchor tag without the `bx--link` class applied to it, in addition to styling fixes so the link appears the way it should.

## Steps to reproduce the issue
Create a BreadcrumbItem or Link without an href property. It will either cause an error or will be disabled. See CodeSandbox example linked below.

https://codesandbox.io/s/codesandbox-gmf7d

**Comment by jendowns** [comment]
Hey @jrpomeroy! In your CodeSandbox, the "Page 5" and "Page 6" anchors are styled as `disabled` because they are not valid links

```
<BreadcrumbItem>
     <a onClick={() => {}}>Page 5</a>
</BreadcrumbItem>
```

Anchors must have an `href` attribute to be valid, otherwise they are just text. 

Looks like CodeSandbox even has a linting note about it in their UI as well:

![Screen Shot 2019-11-18 at 11 19 33 AM](https://user-images.githubusercontent.com/9057921/69074605-52434800-09f5-11ea-8322-50b340f5b662.png)

If you need something that looks like a link but has an `onClick` instead of an `href`, you can use a ghost `Button` -- http://react.carbondesignsystem.com/?path=/story/buttons--default (use knobs to select kind as "ghost" to see)

Here's a great resource on the difference between anchors and buttons: https://marcysutton.com/links-vs-buttons-in-modern-web-applications

**Comment by jrpomeroy** [comment]
@jendowns Thanks for the update.  I understand the standpoint that the links are not considered "valid" in this case if they don't have an href.  But the problem remains that I cannot create a BreadcrumbItem that will work with react-router.  Even if I use a "ghost" type button I still have to set an href or it renders as disabled, and it also has different styling that would need to be overridden.  I added a Page 8 and Page 9 to the CodeSandbox example so you can see what I mean.  https://codesandbox.io/s/codesandbox-gmf7d

Assuming the carbon stance remains that all anchor tags must have an href value in order to be valid, what is the path going forward when react disallows setting href to `javascript:void(0)`?  I don't think it's always going to be as simple as replacing the anchor with a ghost button.

**Comment by jendowns** [comment]
Thanks @jrpomeroy -- 
So this is definitely something.... that inner `Button` component (and `<button>` element) should NOT render with `:disabled` styles in this situation, as it is still interactive. 

It looks like `BreadcrumbItem` adds `.bx--link` class no matter what, which beats out the ghost `Button` styling & applies a specific `:not(...)` rule 🤔 

![Screen Shot 2019-11-18 at 1 39 29 PM](https://user-images.githubusercontent.com/9057921/69084260-7c066a00-0a09-11ea-8e61-4f2c234fabdf.png)

Note that I'm not 100% sure if it's just specificity and/or the import order of link and button styles, but either way the button styles are getting beaten. 😲 

Anyway... this isn't how active/interactive ghost buttons are meant to be styled. And you can imitate this style specificity bug in storybook too if you inspect the first button & add `.bx--link` to it: http://react.carbondesignsystem.com/?path=/story/buttons--default 👀 

I just opened a quick PR for this here: https://github.com/carbon-design-system/carbon/pull/4709

-----

> Assuming the carbon stance remains that all anchor tags must have an href value in order to be valid, what is the path going forward when react disallows setting href to javascript:void(0)? 

@dakahn I was wondering if you have an official answer for this (https://github.com/carbon-design-system/carbon/issues/4705#issuecomment-555169093), or know who does?☝️

**Comment by joshblack** [comment]
Just taking a look real quick, when do we run into the following issue:

> Assuming the carbon stance remains that all anchor tags must have an href value in order to be valid, what is the path going forward when react disallows setting href to javascript:void(0)? I don't think it's always going to be as simple as replacing the anchor with a ghost button.

It seems like from above due to integration with react router, is that the case? Was trying to dive into `react-router-dom` recently and it seemed like in their examples they were passing an `href` but just wanted to confirm when it was showing up!

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and I can 100% re-open!

**Comment by arloduff** [comment]
I would add that not everyone necessarily wants every breadcrumb to link somewhere. There are plenty of valid use cases for having some breadcrumbs contain links, but not all of them. I would like to see the `href` property be optional.
