### ISSUE TITLE
jQuery event to dinamically created content

### ISSUE THREAD

**Issue by lucacrippa88** [carbon-design-system/carbon#471]
I'm trying to create dinamically a table (http://carbondesignsystem.com/components/data-table/code) by appending blocks via jQuery (after AJAX calls).

The problem is, obviously, that the overflow menu is not working, because the table roews are created dinamically.

How can I solve it? Here's the code:

				var block = "<tr><td><b>"+maincontent.text1+"&ensp;</b>"+draft+"</td><td>"+obj.posted+"</td><td>"+obj.updated+"</td><td>"+obj.select1+"</td><td>"+obj.select2+"</td><td class='bx--table-overflow'><div data-overflow-menu tabindex='0' aria-label='Overflow menu description' class='bx--overflow-menu'><svg class='bx--overflow-menu__icon' width='4' height='20' viewBox='0 0 4 20' fill-rule='evenodd'><circle cx='2' cy='2' r='2'></circle><circle cx='2' cy='10' r='2'></circle><circle cx='2' cy='18' r='2'></circle></svg><ul class='bx--overflow-menu-options bx--overflow-menu--flip'><li class='bx--overflow-menu-options__option'><button class='bx--overflow-menu-options__btn'>Modifica post</button></li><li class='bx--overflow-menu-options__option'><button class='bx--overflow-menu-options__btn'>Visualizza post</button></li><li class='bx--overflow-menu-options__option bx--overflow-menu-options__option--danger'><button class='bx--overflow-menu-options__btn'>Elimina post</button></li></ul></div></td></tr>";
$('#add-post-table-here').append(block);

**Comment by asudoh** [comment]
As written in http://www.carbondesignsystem.com/getting-started/developers, Carbon components defined in DOM elements that are created after `DOMContentLoaded` event need to be initialized (and released) manually. You can do it e.g. by `OverflowMenu.init(document.querySelector('#add-post-table-here'));`. Hope it helps.

**Comment by lucacrippa88** [comment]
Thank you, I understand the principle, but in my example I do not get what element I have to inizialize manually.
#add-post-table-here is only the element that will contain the dynamically created table, that contains the overflow menu.

Many thanks

**Comment by asudoh** [comment]
@lucacrippa88 My apologies for being late on this - Behind the scene, `OverflowMenu.init(elem)` searches for DOM elements with `data-overflow-menu` attribute (in the given `elem`) and instantiates overflow menus for them. Hope this answers your question.

**Comment by marijohannessen** [comment]
Closing this issue as it seems to be resolved. Feel free to re-open if needed.

**Comment by lucacrippa88** [comment]
Hi, I put:
<script>
var overflow = document.querySelector('[data-overflow-menu]');
CarbonComponents.OverflowMenu.init(overflow);
</script>
at the end of my html page, but I did not understand what do I have to put instead of [data-overflow-menu]. This gives me the error "Uncaught TypeError: c.className.indexOf is not a function".

Thank you

**Comment by asudoh** [comment]
@lucacrippa88 Carbon codebase does not seem to have any code referring to `.className.indexOf()`. You may want to see where the error is thrown from?
