### ISSUE TITLE
Icon Library Link error

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#4712]
I am trying to access the icon library from the design toolkit but the linked landing page is not a viable link

## What package(s) are you using?

- [x ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The links associated with the pages in the 'grid, colors and icons' section do not work. FOr example, the 32 px icon library tile opens another webpage linked to this URL: sketch://add-library/cloud/2bwkM which provides the following error on Firefox: "Firefox doesn’t know how to open this address, because one of the following protocols (sketch) isn’t associated with any program or is not allowed in this context."
> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected an icon library to open that allowed me to download icon files for business use

> What browser are you working in?
Firefox
> What version of the Carbon Design System are you using?
https://www.carbondesignsystem.com/resources/?&_ga=2.264133836.1994293651.1574110363-1084280677.1566493208#theme-libraries
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
Access this link https://www.carbondesignsystem.com/resources/?&_ga=2.264133836.1994293651.1574110363-1084280677.1566493208#theme-libraries
2. Step two
Try to access any of the icon libraries
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi @ndeangelo! Most likely this happens because you do not have the application [Sketch](https://www.sketch.com/) installed. After installing, you should see the following prompt:

![image.png](https://images.zenhubusercontent.com/5618bf72638e718c995dadc6/fa2f200a-4d91-4ecc-9815-3130d1f2dbba)

Hope this helps!
