### ISSUE TITLE
DataTable : "Object doesn't support property or method 'values'" error in IE11

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#4719]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I used the DataTable component and it's working in all browser except of IE11.
I'm geting this error: Object doesn't support property or method 'values'

pointing to this line of code:

`_defineProperty(DataTable, "translationKeys", Object.values(translationKeys));

export { DataTable as default };`

## Steps to reproduce the issue

open an app that uses the DataTable in IE11

## Additional information

https://stackoverflow.com/questions/58911232/getting-headers-is-undefined-in-ie11

**Comment by asudoh** [comment]
Hi 👋 you need `Object.values()` polyfill. For the list of polyfills you need, please refer to [our getting started guide](https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/README.md#getting-started).
