### ISSUE TITLE
[DataTable] batch actions menu localization issue

### ISSUE THREAD

**Issue by jiamaoIBM** [carbon-design-system/carbon#4720]
## What package(s) are you using?

```
    "carbon-addons-cloud-react": "^1.10.2",
    "carbon-components": "^9.91.3",
    "carbon-components-react": "^6.114",
    "carbon-icons": "^7.0.7",
```

## Issue Details

When selecting 0 items in the DataTable, the batch actions menu shows ``0 item selected``.

![image](https://user-images.githubusercontent.com/15993804/69132110-6b7bef80-0aee-11ea-94a0-f2b0d94b50df.png)

However, according to the IBM translation center, 0 is Plural in English and thus the menu should show ``0 items selected``.

The same goes with a few other local languages:

Singular/Plural Rules for Number "0" in G1 languages:

en: 0 is Plural.
de: 0 is Plural.
es: 0 is Plural.
it: 0 is Plural.
fr: 0 is Singular.
pt-br: 0 is Plural.
zh-cn: Don't distinguish between Singular and Plural.
zh-tw: Don't distinguish between Singular and Plural.
ja: Don't distinguish between Singular and Plural.
ko: Don't distinguish between Singular and Plural.

CLDR reference:
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

![image](https://user-images.githubusercontent.com/15993804/69131977-2788ea80-0aee-11ea-85fd-c6d05340feca.png)

**Comment by asudoh** [comment]
Hi 👋 we have `totalSelected` prop that is API-compatible with `i18next` library. You can refer to [here](https://www.i18next.com/translation-function/plurals) to see how to cope with plurals.

**Comment by jiamaoIBM** [comment]
Got it. Thanks a lot!

**Comment by jiamaoIBM** [comment]
@asudoh The strings on the datatable would display ``t('carbon.table.batch.items.selected')`` when plural number of items are selected, while for singular numbers, ``t('carbon.table.batch.item.selected')`` is displayed. 

```
"batch": {
        "items": {
          "selected": "{{totalSelected}} items selected"
        },
        "item": {
          "selected": "{{totalSelected}} item selected"
        },
        "cancel": "Cancel"
      }
```

The problem here is that the datatable counts 0 as singular and thus uses ``t('carbon.table.batch.item.selected')`` for all languages. However, in many languages such as English, 0 is Plural and thus shoud display  ``t('carbon.table.batch.items.selected')`` instead.

Therefore, can we re-open this issue?

**Comment by asudoh** [comment]
Agreed that differentiating more than one vs. 0/1 with different `carbon.table.batch.item.selected`/`carbon.table.batch.item.selected` localizable strings is an error. i18next can handle it with a single localizable string, as [the i18next document](https://www.i18next.com/translation-function/plurals) explains.

You can get it around by applying the same set of translations to both. OTOH merging the two localizable strings out side is a breaking change.

**Comment by jiamaoIBM** [comment]
@asudoh I'm afraid I don't quite understand how to get around this issue. i,e, to achive the following in the datatable:

```
Display 0 as plural, 1 as singular, and then every number larger than 1 as plural for English and apply the corresponding rules for other languages.
```

The method describled in https://www.i18next.com/translation-function/plurals requires that the number field be named as ``count``. And since the datatable componenet names the number field as ``totalSelected``, I'm not quite sure how to apply this method in this situation.

**Comment by asudoh** [comment]
Oh great point, reopening this issue. Meanwhile, looks that you can get it around by:

```javascript
<TableBatchActions translateWithId={(id, state) => translateWithId(id, {
  ...state,
  count: state.totalSelected,
})}>
```

**Comment by jiamaoIBM** [comment]
I see. Thanks a lot!
