### ISSUE TITLE
OverflowMenu: dropdown menu items with overflow text do not have consistent padding between menu items.

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon#4722]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

In scenarios whereby the text of a dropdown list item is really long, whereby the text overflows to multiple lines, the padding between menu items is inconsistent.

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect that in instances whereby the menu item is long enough that it spreads multiple lines, then the list item itself should dynamically increase in height to facilitate the text.

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

2.18

## Steps to reproduce the issue

1. Step one - Visit an isolated sandbox environment, at https://codesandbox.io/s/carbonvue-overflow-menu-multiline-menu-items-4y7uh
2. Step two - Observe that the second item spans two lines, whilst the fourth item is so long that is spans 3 lines. 
3. Step three - Observe that the text becomes illegible.

## Additional information

<img width="269" alt="Screenshot 2019-11-14 at 15 24 25" src="https://user-images.githubusercontent.com/56296356/68870521-ef9b3500-06f2-11ea-877e-f1c947bf92fd.png">

As a temporary fix, we have been using: 
```
.my-overflow-item {
  &.bx--overflow-menu-options__option {
    // replace height from core carbon
    height: initial;
    min-height: 2.5rem;
  }

  .bx--overflow-menu-options__btn {
    height: initial;
  }

  .bx--overflow-menu-options__option-content {
    white-space: initial;
    overflow: initial;
    text-overflow: initial;
    margin: 0.7rem 0;
  }
}
```

**Comment by asudoh** [comment]
@carbon-design-system/design Looks that we should use ellipsis for the 2nd/4th items. Is it correct...? Thanks!

**Comment by laurenmrice** [comment]
If text wrapping is necessary, you can wrap up to two lines and provide an ellipses for the overflow content. Text should not wrap more than two lines.

**Comment by asudoh** [comment]
Thanks @laurenmrice for clarifying! AFAIK CSS cannot do two-line content with ellipsis, so probably one line with ellipsis makes more sense...?

**Comment by laurenmrice** [comment]
Combobox is currently doing a one line ellipses here: http://react.carbondesignsystem.com/?path=/story/combobox--custom-text-input-handling

**Comment by asudoh** [comment]
I see that latest https://react.carbondesignsystem.com/?path=/story/overflowmenu--basic has long menu item, which implements ellipsis.
