### ISSUE TITLE
Replace single straight quotes with apostrophes in data table component

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#4728]
https://www.carbondesignsystem.com/components/data-table/code

<img width="1093" alt="Screen Shot 2019-11-19 at 4 56 09 PM" src="https://user-images.githubusercontent.com/32881239/69194078-ded13180-0aed-11ea-84da-82b430699945.png">

**Comment by tw15egan** [comment]
Seems like they were removed completely, so going to close this out

**Comment by mjabbink** [comment]
It’s why I changed the issue to “replace” from remove. I realized it may be confusing language. It’s now wrong as it needs an apostrophe but the correct one.
