### ISSUE TITLE
DataTable select all checkbox 

### ISSUE THREAD

**Issue by Potato-W** [carbon-design-system/carbon#4732]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I am using `DataTable` with search in toolbar.  When I search something and then click select all checkbox, I found it will select all data actually.  In my opinion, in this situation, the search result data usually be selected. So my question is after typing something in search bar, which is better, select all data or select all search result data? Or I used this component by mistake?

**Comment by asudoh** [comment]
@carbon-design-system/design Any thoughts on the desired UX around "select all" within search result...? Thanks!

**Comment by aagonzales** [comment]
I can't say off the top of my head, I'd have to do a little research to see what the expected interaction would be and if there are any constraints due to the connected data base. 

@changshunwang have you done any competitive analysis to see what the industry norm for this interaction is?

**Comment by Potato-W** [comment]
@aagonzales . Sorry, I didn't do any competitive analysis. Because my team member and UX designer all think the "select all" checkbox should select all items within visual range.  Here is [another example ](https://ant.design/components/table/#components-table-demo-row-selection-and-operation)from Alibaba frontend framework. But it's really an interesting question, so if you need a analysis or anything else, could you please tell me how to do that? where could I search information, doc? I am very glad to join.

**Comment by joshblack** [comment]
Any additional thoughts @aagonzales?

**Comment by aagonzales** [comment]
I'm not seeing in the Alibaba example where you search and select all in a table. But following what Gmail does I believe only the filtered content is being selected when triggering select all. Which makes sense in my limited knowledge of the scenario.

**Comment by chrisconnors-ibm** [comment]
If I understand the description, there's a data set (_m_) represented in a table, and a search operation filters that set down to some smaller set of results (_m-n_).

If the table is displaying the result set (_m-n_) as a result of any user operation, including search (or filtering) then the **Select all** checkbox should select the results (_m-n_) not the entire data set (_m_).

**Comment by Potato-W** [comment]
@chrisconnors-ibm @aagonzales YES,  this is what I mean.  Select all check box should select the filter/search results not the entire data. 

But now, the check box will select entire data. It doesn't make sense. 
@asudoh so, could you please add this issue in carbon?

**Comment by emyarod** [comment]
this issue should be resolved by https://github.com/carbon-design-system/carbon/pull/4430 and https://github.com/carbon-design-system/carbon/pull/5840
