### ISSUE TITLE
Explore using React context in ui-shell, data table, tabs

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#4735]
Relevent pr: https://github.com/carbon-design-system/carbon/pull/3340

motivation:
- Context permits custom custom shell components that interact with shell state
- Allows for components outside of the shell to react and inform shell behavior.
- The ergonomics for using such components is a big improvement over prop getters
- Opportunity to remove children mapping/imperitive prop application

**Comment by joshblack** [comment]
What would this look like for tabs? @vpicone
