### ISSUE TITLE
Forward refs for a few more components: HeaderGlobalAction, HeaderPanel

### ISSUE THREAD

**Issue by paul-sachs** [carbon-design-system/carbon#4737]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We'd like header panels to be closable by clicking outside of the panel, to do so we need a ref for the panels (and potentially the action).

> Is this issue related to a specific component?

Yes, HeaderGlobalAction, HeaderPanel

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When attaching a ref property, it should be populated with the html node.

> What browser are you working in?

Any

> What version of the Carbon Design System are you using?

10

**Comment by joshblack** [comment]
@psachs21 would we want to bake this functionality into the component itself instead of having consumers needing to manage it?

**Comment by paul-sachs** [comment]
@joshblack potentially, but i also think it's a good practice to expose as many refs on these components as we can, so maybe we can have another issue with regards to the click outside functionality.

**Comment by joshblack** [comment]
Any particular reason for exposing `ref`s in general? Would love to learn more

**Comment by paul-sachs** [comment]
For things like controlling scroll and focus, it's the only way to manage things. Also, any kind of code that measures the size of elements. All of these functionalities require a dom ref.

**Comment by joshblack** [comment]
@psachs21 got it, it would seem like not everything would need to have refs for scroll/focus though, correct? Definitely agreed for elements where this makes sense, in particular `<button>`s or `<input>`s.

For size measurements, is this a frequent enough use-case? Seems like this would be a user space solution for this in the form of the wrapper div approach but could easily be missing out on how often this is happening in product 👍

**Comment by paul-sachs** [comment]
We use measurements for things like our tooltip library (popper.js) which requires a ref for positioning. But in this particular instance, I'm just using it to detect a click outside the element. If you feel it would be better to just put that functionality into the component itself, i'll change my PR to do that instead.

**Comment by joshblack** [comment]
@psachs21 tooltips is an interesting case, I think there are criteria for what should be allowed to have a tooltip alongside the required ARIA to wire them up correctly.

Looking at the popper.js.org website, it seems like these tooltips aren't implemented using the required a11y techniques so screen readers would be unable to relate the tooltip and the content in question. Could easily be missing things though so let me know, just did a quick VO check on the site.

**Comment by paul-sachs** [comment]
popper.js itself doesn't handle the accessibility, it just handles the positioning (i think they have a tooltip library that does handle it but not sure). We've implemented a wrapper (itself a wrapper around react-popper) which adds the required accessibility labels. Our wrapper actually used similar logic to carbon's tooltip but with the added functionality provided by popper.js.

**Comment by joshblack** [comment]
Got it, my mistake @psachs21!
