### ISSUE TITLE
UI locks up when user selects sideNavLink and a modal is displayed (smaller screen width)

### ISSUE THREAD

**Issue by lisadier** [carbon-design-system/carbon#4739]
UI locks up when user selects sideNavLink and a modal is displayed (smaller screen width):
Clicking a sideNavLink that results in a modal being displayed locks up the screen. 

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I am using the SideNav with SideNavLink components.  In a smaller screen width where the hamburger menu is shown: when the user clicks the SideNavLink, and some error occurs (i.e. can't connect to server or some other backend issue) then I am displaying an error modal on the page.  The problem is that the user cannot click ok/cancel or the sidenav or anything to continue with the application.  The screen is basically locked up.  
In case it helps with debug: I have noticed that pressing the Esc key allows the user to proceed, but that is unlikely to be found by most users.

> Is this issue related to a specific component?
SideNav, SideNavLink, smaller screen size (hamburger menu shown), and Modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The user should be able to close the error dialog.

> What browser are you working in?
Chrome.

> What version of the Carbon Design System are you using?
    "carbon-components": "10.7.3",
    "carbon-components-react": "7.7.3",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Demo at beginning of Jan 2020.

## Steps to reproduce the issue

See https://codesandbox.io/s/codesandbox-bzbid
1. Open the hamburger menu for navigation
2. Notice that you can navigate between "Main" and "User" just fine
3. Click "Page with error on loading"
4. Notice that nothing can be clicked.  (Pressing escape will get you 'unlocked' but that should not be required.)

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/codesandbox-bzbid

**Comment by asudoh** [comment]
Late on this, but I see the problem is caused by placing `<Modal>` not at the top-level in the React tree. Observed that mangling the DOM to move the modal DOM elements at the top-level fixes the problem.

**Comment by lisadier** [comment]
Thanks for the response.  This has been fixed in a later version after I reported the problem.  The problem no longer exists on current versions.
