### ISSUE TITLE
Assign a function to onClick at TableBashActions Cancel button  or an onClose function

### ISSUE THREAD

**Issue by fjpedrosa** [carbon-design-system/carbon#4742]
## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?
feature request / general issue
> Is this issue related to a specific component?
Yes, to TableBashActions at DataTable
> What did you expect to happen? What happened instead? What would you like to
> see changed?
I would like to hace the possibility to modify a state variable (this variable is used to make the table selectable or not) once the cancel button of TableBashActions is clicked.
> What browser are you working in?
Chrome Versión 78.0.3904.108 (Build oficial) (64 bits)
> What version of the Carbon Design System are you using?

## Steps to reproduce the issue
I have a DataTable which is selectable or not based on a variable stored in the component state (isSelectable). I have a toolBar with a button that set isSelectable to true, and the DataTable shows the checkbox to select the rows. If a row is selected, the tableBashActions appears in the toolbar.

I would like to set isSelectable to false when the user clicks on the cancel button of the tableBashActions

Thanks in advance.

**Comment by asudoh** [comment]
Hi 👋 `<TableBatchAction>` [sends misc props to the `<button>` in it](https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/DataTable/TableBatchAction.js#L13). So I guess you can simply set `onClick`?

**Comment by fjpedrosa** [comment]
Yes but I need to send that onClick to the cancel button in <TableBatchActions> (with s). I see that there is an onCancel prop but if I set this:

```
onCancel={() => {
  this.setState({
    isSelectable: false
  });
}}
```

Then the ToolBash doesn't dissapear when no items are selected.

At the moment the soltion I found was to set onClick like this: 

```
onClick={e => {
  if (e.target.innerHTML === 'Cancel') {
    this.setState({
      isSelectable: false
    });
  }
}}
```

but I'm sure there is a more elegan way to do this.

**Comment by asudoh** [comment]
I see. Probably you are looking for `onCancel` of `<TableBatchActions>`?

**Comment by aledavila** [comment]
Closing as we never got a response. If this is still an issue please feel free to comment with further information. Thanks
