### ISSUE TITLE
[React] SideNav behaving unexpectedly on mobile when expanded by tap and not expand button

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4743]
## What package(s) are you using?

- [x] `carbon-components`: Latest as of 11/21/2019
- [x] `carbon-components-react`: Latest as of 11/21/2019

## Detailed description
On mobile, SideNav control misbehaves only when it is expanded by tapping on it rather than the HeaderMenuButton. Clicking on a SideNavLink or SideNavMenuItem does not fire the click event, it rather collapses all the expanded SideNavMenu's. After that if you click on a SideNavMenu to expand it, all other SideNavMenu's that were in expand state before they were collapsed get back to their prior state of expanded. A screen grab is attached below for your reference. Again, this only happens when you tap or hover over the SideNav and it goes to the expanded state.

[Screen Grab Video Link: https://photos.app.goo.gl/rc7NvgrSeah3f9RR6](https://photos.app.goo.gl/rc7NvgrSeah3f9RR6)
I tried to attach a gif but github changed it to png.

![image](https://user-images.githubusercontent.com/54859354/69354263-6d0bfb80-0c45-11ea-98c7-3def75f27ef9.png)

## Steps to reproduce the issue

Open the react demo site for carbon on a mobile browser and repeat the steps as performed in the attached screen grab.

**Comment by tahaimt** [comment]
While this is fixed, can someone please tell me if there is a way to disable on hover expand action of the SideNav?

**Comment by tahaimt** [comment]
@asudoh  can you please take a look at this, or forward it to someone?

**Comment by tahaimt** [comment]
I just noticed on my app that the sidebar is glitchy even on desktop. Find the attached screen grab [here](https://drive.google.com/file/d/1lfS7Tp2FfdT710me64YZgoGAn9xqQgrk/view?usp=sharing). The code for the sidebar is also pasted below for your reference.

		<SideNav
                aria-label="Side navigation"
                expanded={isSideNavExpanded}
                isRail
              >
                <SideNavItems>
                  <SideNavLink element={Link} to="/" isActive={props.location.pathname === "/"} renderIcon={Analytics32}>
                    Trends
                  </SideNavLink>
                  <SideNavLink element={Link} to="/dashboard" isActive={props.location.pathname === "/dashboard"} renderIcon={Collaborate32}>
                    Entity
                  </SideNavLink>
                  <SideNavMenu title="Member"
                    defaultExpanded={true} 
                    isActive={[
                      "/DuplicateReport",
                      "/DuplSummStats",
                      ].includes(props.location.pathname)}
                      renderIcon={Connect32}>
                    <SideNavMenuItem element={Link} isActive={props.location.pathname === "/DuplSummStats"} to="/DuplSummStats" renderIcon={TableSplit32}>
                      Duplicate Summary Statistics
                    </SideNavMenuItem>
                    <SideNavMenuItem element={Link} to="/DuplicateReport" isActive={props.location.pathname === "/DuplicateReport"}>
                      Same Source Autolink
                    </SideNavMenuItem>
                  </SideNavMenu>
                  <SideNavMenu title="Task" 
                    defaultExpanded={true} 
                    isActive={[
                      "/TaskMgmtOverview",
                      "/TaskMgmtDetails",
                      ].includes(props.location.pathname)}
                      renderIcon={Task32}
                  >
                    <SideNavMenuItem element={Link} to="/TaskMgmtOverview" isActive={props.location.pathname === "/TaskMgmtOverview"} renderIcon={InventoryManagement32}>
                    Task Management Overview
                    </SideNavMenuItem>
                    <SideNavMenuItem element={Link} to="/TaskMgmtDetails" isActive={props.location.pathname === "/TaskMgmtDetails"} renderIcon={FolderDetails32}>
                      Task Management Details
                    </SideNavMenuItem>
                    <SideNavMenuItem element={Link} to="/LinkMgmtOverview" isActive={props.location.pathname === "/LinkMgmtOverview"} renderIcon={TextLink32}>
                      Linkage Management Overview
                    </SideNavMenuItem>
                    <SideNavMenu title="Task Creation Detail" 
                      defaultExpanded={true} 
                      isActive={[
                        "/PotentialDuplicates",
                        "/PotentialLinkages",
                        "/PotentialOverlays",
                        "/ReviewIdentifiers"
                        ].includes(props.location.pathname)}
                        renderIcon={DocumentAdd32}
                      >
                      <SideNavMenuItem element={Link} to="/PotentialDuplicates" isActive={props.location.pathname === "/PotentialDuplicates"}>
                        Potential Duplicates
                      </SideNavMenuItem>
                      <SideNavMenuItem element={Link} to="/PotentialLinkages" isActive={props.location.pathname === "/PotentialLinkages"}>
                        Potential Linkages
                      </SideNavMenuItem>
                      <SideNavMenuItem element={Link} to="/PotentialOverlays" isActive={props.location.pathname === "/PotentialOverlays"}>
                        Potential Overlays
                      </SideNavMenuItem>
                      <SideNavMenuItem element={Link} to="/ReviewIdentifiers" isActive={props.location.pathname === "/ReviewIdentifiers"}>
                        Review Identifier
                      </SideNavMenuItem>
                      <SideNavMenuItem element={Link} to="/PreMerge" isActive={props.location.pathname === "/PreMerge"}>
                        Pre Merge
                      </SideNavMenuItem>
                    </SideNavMenu>
                  </SideNavMenu>
                  <SideNavLink element={Link} to="/dashboard" renderIcon={QOperationGauge32}>
                    Operational
                  </SideNavLink>
                </SideNavItems>
              </SideNav>

**Comment by tw15egan** [comment]
For some reason, this was due to the use of `will:change: transform` on the SVG elements, and was fixed in this PR: https://github.com/carbon-design-system/carbon/pull/5274/files

Should be fixed in `v10.10.0` when released
