### ISSUE TITLE
Notification component (Angular) support buttons/links similar to React version

### ISSUE THREAD

**Issue by awackygamer** [carbon-design-system/carbon#4744]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Notification component in Angular is missing a much needed ability to launch some actions.  Either by rendering buttons or links.  Support for using any component in the notification.

### Justification

UX team has designed several scenarios that have buttons or email links.

### Desired UX and success metrics

Success for our product would be buttons or links that can be clicked/linked back to the JS.

### "Must have" functionality

Buttons in the notification component for Angular.

### Specific timeline issues / requests

Next release is mid January.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

None at this time.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by joshblack** [comment]
Hi @awackygamer! 👋 Might help to make this issue over on the Angular repo: https://github.com/IBM/carbon-components-angular

**Comment by awackygamer** [comment]
Moving to angular github
