### ISSUE TITLE
Table export functionality

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#4749]
### Summary

We are requesting the ability to easily export table content using an optional "export" tool on the table toolbar (table consumers would decide whether or not to include it in their toolbar). 

The export tool would export all table content, regardless of pagination. If filters had been applied, it would export only content matching those filters. Exports would be rendered as a .csv download.

This issue is related to 

- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4748

### Justification

Over a third of IBM Cloud tables are based on a Softlayer table that offers optional export functionality. If we don't add this functionality to the Carbon data table, users will lose that existing functionality when our platform moves to Carbon X. We have heard extensive user feedback about the importance of being able to export tables for offline resource management. Exports allow users to "slice and dice" as well as annotate their table content without being constrained by pagination. The ability to export lists of non-lite resources has also been cited by multiple users as an important tool for cost management.

**Proposed design:**

![image](https://user-images.githubusercontent.com/39408106/72372622-3e9e2000-36cc-11ea-9830-ecfb97a3019e.png)

### Desired UX and success metrics

The user will be able to export any table with the export tool to a .csv file compatible with Excel, Google, and other spreadsheet apps. Design teams can easily instrument analytics to track downloads, however the frequency with which teams implement the export tool would also be an important success metric.

### "Must have" functionality

- Export must product a .csv (as opposed to a pdf) so that users are able to manipulate it.
- Must export whole table not just current page
- Must take into account any filters applied to table

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables in January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.

### Available extra resources

Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

**Comment by asudoh** [comment]
Hi 👋 this doesn't look an area of Carbon that is meant to implement our design language, given the requested feature is of downloading data that application has. Please let us know if you just meant to contribute an icon. Thanks!

**Comment by jendowns** [comment]
In `@carbon/ibm-security`, one of our Security devs @sbutler2901 contributed a `TableToolbarDownload` component that can be added to a data table toolbar for downloading data to a csv. It's a short component but it did require an extra dependency (for the csv file generation).

Storybook: https://ibm-security.carbondesignsystem.com/?path=/story/components-datatable--with-toolbar
Source: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/DataTable/TableToolbarDownload.js

@asudoh What's your opinion on us contributing the `TableToolbarDownload` upstream to `carbon-components-react`? 

(Alternatively, they could use `TableToolbarAction` to add their own icon + `onClick` and then roll their own csv generation/download)

**Comment by joshblack** [comment]
@jendowns definitely would depend on surface area of the contribution, if it's a lot of complexity it'll be harder for us to take on 😞

**Comment by jendowns** [comment]
@joshblack Yeah the more I think about it, the more it make sense to use a `TableToolbarAction` out of the box, add use a download icon, and then have the `onClick` be tied to generating & downloading a CSV based on row + header data, using whatever CSV tool/package the consumer wants to use 😅

**Comment by asudoh** [comment]
@jendowns Right - [`<TableToolbarAction>` in `v9`](http://v6-react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20toolbar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel), in case it's what you meant, is the right way to go. With that, as you said, application can integrate the CSV exporter library of their choice.

**Comment by designertyler** [comment]
We're going to close this for now. I think we've already had a good discussion on this issue. Appropriate at this point for implementation at the PAL level, rather than the core Carbon level, and can discuss long term support and integration at a future date.
