### ISSUE TITLE
Reorder table columns

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#4750]
### Summary

We are requesting the ability for users to reorder columns in their table. 

**Proposed design:**

![image](https://user-images.githubusercontent.com/39408106/69386104-348d1180-0c87-11ea-8407-795847ce5619.png)

### Justification

Over a third of IBM Cloud tables are based on a Softlayer table that offer reorder column functionality. If we don't add this functionality to the Carbon data table, users will lose that existing functionality when our platform moves to Carbon X. 

While not as urgent as the ability to edit columns, the ability to reorder columns to show the most relevant columns first is something users expect when dealing with tables. The ability to reorder columns also  supports the related functionality of editable columns.

Related issues:
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4749

### Desired UX and success metrics

Of users we tested with, all expected to be able to drag and drop directly on the table to reorder columns. The user would click, **hold**, and drag the column to the desired location (if the user clicks without holding it would sort the column). On hold the cursor would change to a "move" icon.

Letting go of the mouse or trackpad would release the column.

Since drag and drop is not accessible, we would also offer a keyboard and screen reader accessible option that would allow users to capture and reorder columns using their keyboard. 

[Design provide link to accessibility flow]

### "Must have" functionality

- Reorder columns must meet accessibility requirements

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables in January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.
### Available extra resources

What resources do you have to assist this effort?
Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

**Comment by designertyler** [comment]
We're going to close this for now. I think we've already had a good discussion on this issue. Appropriate at this point for implementation at the PAL level, rather than the core Carbon level, and can discuss long term support and integration at a future date.

**Comment by Ragha100** [comment]
Hi Team
Where can I see this feature in Carbon Design System, is it available in the Sketch documentation/Carbon's Website. Is it available in Carbon Angular or any tentative time line.

**Comment by lordsfantasy** [comment]
Hi, what is the current status on this?
