### ISSUE TITLE
Resize table columns

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#4751]
### Summary

We are requesting the ability for a user to resize column width within a table. This functionality is related to the ability to edit and reorder columns.

**Proposed design:**

![image](https://user-images.githubusercontent.com/39408106/69386733-090b2680-0c89-11ea-9695-127722fd4f33.png)

**Related issues:**
- https://github.com/carbon-design-system/carbon/issues/4750
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4749

### Justification

This functionality will support the ability to edit and reorder columns, functionality that is currently offered by the Softlayer table used by a third of IBM Cloud pages - functionality which we do not want users to lose. Many of our customers use small desktops or multiple windows side by side, so this will allow them to optimize their view.

**Proposed design:** 

![image](https://user-images.githubusercontent.com/39408106/69387880-d400d300-0c8c-11ea-8d23-78ae5720a52f.png)

![image](https://user-images.githubusercontent.com/39408106/69387894-e11dc200-0c8c-11ea-9520-d721de3ee6b3.png)

### Desired UX and success metrics

The column divider would show up if a user hovers within the hover target. If the user then hovers over the divider they would get an "adjust width" browser icon. The user could then click to drag the divider right or left.

Letting go of the mouse or trackpad would release the divider.

Since drag and drop is not accessible, we would also offer a keyboard and screen reader accessible option that would allow users to adjust column width using their keyboard.

[Design provide link to accessibility flow]

### "Must have" functionality

- Resize column width must meet accessibility requirements

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables in January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.

### Available extra resources

What resources do you have to assist this effort?

Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

**Comment by tay1orjones** [comment]
We're also working on this for the Watson IoT PAL. https://github.com/IBM/carbon-addons-iot-react/issues/135

It seems that the appropriate way to do this would require having refs forwarded for each `<th>`, so we can declaratively set the width on them vs. imperatively assigning width inside mouseMove/Up handlers via event.target.closest('th') or something.

We also don't want to break table semantics wrapping `<th>`s with a container element.

I've opened #4876 to address the forward ref.

**Comment by gmoehler** [comment]
Could you please consider supporting the `sticky-header` option in the implementation, since our `DataTable` uses the `sticky-header` feature.

**Comment by gmoehler** [comment]
Since i need this functionality soon, I have worked on it and opened a PR (https://github.com/carbon-design-system/carbon/pull/5214) that does the resizing (also works for sticky header tables). Please take a look.

**Comment by gmoehler** [comment]
I have completely reworked my earlier PR and have opened a new one: https://github.com/carbon-design-system/carbon/pull/5288. It minimizes the impact to the existing code and has a more natural resizing algorithm.

**Comment by designertyler** [comment]
We're going to close this for now. I think we've already had a good discussion on this issue. Appropriate at this point for implementation at the PAL level, rather than the core Carbon level, and can discuss long term support and integration at a future date.
