### ISSUE TITLE
OverflowMenu should scroll with its container

### ISSUE THREAD

**Issue by EAlexRojas** [carbon-design-system/carbon#4755]
### Summary

When the overflow menu is open and you scroll, the menu stays fixed in the page. I think it should  move along with the container.

### Justification

When using overflow menus in tables, this causes a non desirable behaviour.

### Desired UX and success metrics

The open OverflowMenu should stick to the element that opened it even when the container scrolls up or down.

### "Must have" functionality

There should be a way to specify the OverflowMenu container and it should base its positioning from there.
Open OverflowMenu should scroll with its container.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

It would be good to have it on 2020 Q1, so it could be used in the next release of our product.

### Available extra resources

Here a code sandbox showing the current (non-desirable) behaviour: https://codesandbox.io/s/codesandbox-z2snz
Here a GIF with current (non-desirable) behaviour:
![overflow](https://user-images.githubusercontent.com/2373303/69446547-ee9e7f00-0d54-11ea-877f-5bfc0aec79a3.gif)

Ideas to address the issue:
- Currently the menu is being always added to the same level as 'body', it should be a property to specify the container where the menu is added.
- Don't use `getBoundingClientRect as it gives positioning relative to viewport.
- Taking into account the previous two points, it should be easy to position the menu relative to its container using top/bottom left/right properties.

**Comment by asudoh** [comment]
Hi 👋 you can set `data-floating-menu-container` attribute to the scrolling container to solve the problem.

**Comment by EAlexRojas** [comment]
Hi @asudoh, I already tried that, but it does not work as expected.
The menu scrolls with the content, right, but the positioning is not correct, it does not appear under the "trigger" button (you can try it in the codesandbox I pasted in the description).
 
I think this is mainly because the base positioning is using `getBoundingClientRect` which gives positioning relative to viewport.

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/OverflowMenu/OverflowMenu.js#L309

**Comment by asudoh** [comment]
Two things you can try when you think you got a wrong position:

* Change [`menuOffset`](https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/OverflowMenu/OverflowMenu.js#L160-L169). The default one can be found at: https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/OverflowMenu/OverflowMenu.js#L53-L94
* Set `position:relative` to the menu container

**Comment by EAlexRojas** [comment]
I also played around with the `menuOffsetFlip` prop (as I'm using the flipped version), but it's not fixing the issue.
I could come up with a value that works when the container has not scrolled yet, in that case the menu scrolls with the container correctly.
But if open the overflow menu after scrolling in container, for example to reach the items at the end of the table, the positioning is not correct:

![scroll-overflow2](https://user-images.githubusercontent.com/2373303/69542390-a3ba7c80-0f8b-11ea-82bb-cf01ee7b0613.gif)

The thing is that the offset is passed, along with the menu position to the `FloatingMenu` component, which calculate the positioning of the menu based on those values.
I see two problems with that:
1) The menu position is calculated using `getBoundingClientRect` which is relative to viewport and not relative to the container.
2) The `FloatingMenu` does not take into account the scroll of the container, it uses `window. pageXOffset`.

**Comment by asudoh** [comment]
Have you tried something like this?

```diff
--- original.js	2019-11-26 07:20:06.000000000 +0900
+++ updated.js	2019-11-26 07:19:58.000000000 +0900
@@ -124,7 +124,7 @@
               <TableHeader />
             </TableRow>
           </TableHead>
-          <TableBody>
+          <TableBody data-floating-menu-container>
             {rows.map(row => (
               <TableRow {...getRowProps({ row })}>
                 <TableSelectRow {...getSelectionProps({ row })} />
@@ -132,7 +132,7 @@
                   <TableCell key={cell.id}>{cell.value}</TableCell>
                 ))}
                 <TableCell>
-                  <OverflowMenu flipped>
+                  <OverflowMenu flipped menuOffsetFlip={{ top: -135 }}>
                     <OverflowMenuItem primaryFocus>Action 1</OverflowMenuItem>
                     <OverflowMenuItem>Action 2</OverflowMenuItem>
                     <OverflowMenuItem>Action 3</OverflowMenuItem>
```

**Comment by EAlexRojas** [comment]
Yes, I tried that and it causes the problem shown in the GIF in my previous comment.

The overflow menu opens correctly for the items in the table when there is no scroll.

But if you scroll first to the end of the table and then you try to open an overflow menu, the position is not correct. 

Here a codesandbox with the change you suggested: https://codesandbox.io/s/codesandbox-wqbpp

**Comment by asudoh** [comment]
I see, would you want to try something like this?

```javascript
<OverflowMenu
  flipped
  menuOffsetFlip={(menuBody, menuDirection, menuEl) => {
    const container = menuBody.closest(
      "[data-floating-menu-container]"
    );
    return { top: -133 + container.scrollTop, left: -63 };
  }}
>
```

**Comment by EAlexRojas** [comment]
Thanks @asudoh that is working!

It's still a bit tricky to get the correct values for top and left, but I guess that will depend on each case.

For my case in our project, I managed to get the "top" value using the `offsetTop` property of the container and the "left" value, I used the ones in the default function pointed out by you in a previous comment.

It would be good to add something in the documentation about the `data-floating-menu-container` property and the use of the `menuOffsetFlip` / `menuOffset` functions.

**Comment by abbeyhrt** [comment]
Since it seems like a solution was reached, I'm going to close this issue!

**Comment by sstone2423** [comment]
Is it possible to add this to the storybook docs? My coworker and I were trying to debug this on our end for a while and after a lot of digging, we finally came across this issue. @abbeyhrt @asudoh

**Comment by JoelArmendariz** [comment]
I was able to fix this by adding `data-floating-menu-container` and `position: relative` to the container that I wanted the menu to be positioned relative to. This placed the menu back into the DOM tree where we would expect it to be. 
The problem here is that the menu is rendered as a `float` (https://reactjs.org/docs/portals.html) which causes it to be positioned relative to the body rather than the expected container that is written into.
I hope this saves someone some time.
