### ISSUE TITLE
Select box svg out of place if label is wider than select

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#4757]
carbon-components 10.7.4
carbon-components-react 6.116.2
carbon-icons 7.0.7

We are using the Select component from carbon-components-react.

If the label text is wider than the select box, the svg caret is outside of the dropdown box.
If the label text is not as wide, the svg caret displays where it should.

Also note that we had to add the css below to make the arrow appear in the box, instead of above the box:
_.bx--select__arrow {
  bottom: 1rem;
}_

******
Here is the code that is created by using Select in React:
<div>
<div class="bx--form-item">
<div class="bx--select">
<label for="questionType" class="bx--label">In what direction of travel?</label>
<select id="questionType" class="bx--select-input">
<option class="bx--select-option" value="North">North</option>
<option class="bx--select-option" value="South">South</option>
<option class="bx--select-option" value="East">East</option>
<option class="bx--select-option" value="West">West</option>
</select>
<svg class="bx--select__arrow" fill-rule="evenodd" height="5" role="img" viewBox="0 0 10 5" width="10" aria-label="open list of options" alt="open list of options">
<title>open list of options</title>
<path d="M0 0l5 4.998L10 0z"></path>
</svg>
</div>
</div>
<br>
</div>

Screenshot below to show a select that doesn't look right and one on the same page that does.

![Screen Shot 2019-11-22 at 1 23 10 PM](https://user-images.githubusercontent.com/58083960/69450492-47592200-0d2b-11ea-983e-04c2f1e26401.png)

**Comment by jendowns** [comment]
I have an idea for a solution 👍 
Opening a PR shortly
