### ISSUE TITLE
[Modal- Title only example]: close button overlaps text

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#4759]
When looking at the modal at https://carbon-components-react.netlify.com,  I found that, when changing the size of the window, the `X` icon overlaps the content pretty severely at times.  

<img width="727" alt="Screen Shot 2019-11-22 at 11 34 45 AM" src="https://user-images.githubusercontent.com/17281178/69451789-d4997800-0d25-11ea-8504-1fa9f93fe9b3.png">

Or the focus for the button will overlap the text: 

![Screen Shot 2019-11-22 at 12 45 27 PM](https://user-images.githubusercontent.com/17281178/69451851-fc88db80-0d25-11ea-83de-5eb211aff24d.png) 
the 's' in 'lines' is covered by the button.

**Comment by abbeyhrt** [comment]
@asudoh would you have time to look into this? Not sure if it's the storybook implementation for the title only example or the code that's causing this.

**Comment by joshblack** [comment]
bump @asudoh
