### ISSUE TITLE
Code snippet fade effect is inconsistent in Safari

### ISSUE THREAD

**Issue by sltclss** [carbon-design-system/carbon#4769]
## What package(s) are you using?

Mac os Catalina 10.15.1
Safari 13.0.3
carbon-components 10.7.4
carbon-components-react 7.7.4

## Detailed description

The ::after pseudo element of the code snippets are a dark gray.

## Is this issue related to a specific component?
Yes, the single and multi-line code snippets

## What did you expect to happen? What happened instead? What would you like to see changed?
The pseudo element for the text fade effect blends with the background

## What browser are you working in?
Safari

## Steps to reproduce the issue
1. Step one - Using safari browser http://react.carbondesignsystem.com/?path=/story/codesnippet--multi-line

## Additional information

- Screenshots or code
<img width="817" alt="Screen Shot 2019-11-25 at 7 52 20 AM" src="https://user-images.githubusercontent.com/6990260/69542389-58877600-0f59-11ea-8605-3d903040240a.png">
<img width="866" alt="Screen Shot 2019-11-25 at 7 52 42 AM" src="https://user-images.githubusercontent.com/6990260/69542393-5b826680-0f59-11ea-8de6-fbdca5f0dccf.png">

**Comment by jendowns** [comment]
I can help with this one 👍 Opening a PR shortly.
