### ISSUE TITLE
Curious how to implement the Batch Filter example from Patterns on the website

### ISSUE THREAD

**Issue by agmcleod** [carbon-design-system/carbon#4774]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

Hi there, following the example on the filtering page here: https://www.carbondesignsystem.com/patterns/filtering#batch-filter. I'm wondering how this can be done. Looking over the components, I tried to have the menu come up with side by side containers like in the example, by using a grid within a OverflowMenu. But I realized pretty quickly that OverflowMenu is an un-ordered list, so that fell down pretty quickly. How can I implement this sort of pop over? For implementing the filtering itself, I can cover that without issue, it's more on the styling side.

**Comment by asudoh** [comment]
Hi 👋 you don't have to use overflow menu and you can come up with a component from scratch, e.g. with a traditional menu pattern whose menu body has absolute positioning and 100% top.

**Comment by asudoh** [comment]
BTW #4687 seems to be close to this.

**Comment by agmcleod** [comment]
ah okay, so there's nothing i can build on top of?

**Comment by asudoh** [comment]
Probably you can jump in the discussion of: #4771
