### ISSUE TITLE
Dropdown/Combox box input box and menu items should show tooltips 

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#4788]
### Summary
We have some dropdowns with long items.  The default styles truncate them with an ellipsis.  However, if you hover over the item, there is no way to see the full string.  The exception is Safari, which I assume it is handling itself, as I didn't see any code in Carbon to handle it.

I've implemented itemToElement so that I can add the title attribute and this works fine for the menu items.  However, when you actually select one of these long items, I have good no way to set the title attribute on the input box.

![image](https://user-images.githubusercontent.com/30597411/69740873-18b2c100-1108-11ea-8424-d380bc94d571.png)

**Comment by emyarod** [comment]
This should be fully resolved for dropdown (ref https://github.com/carbon-design-system/carbon/pull/5519). Combobox menu items currently support this, so the feature just needs to be added to the combobox input

**Comment by laurenmrice** [comment]
Yep! As Andrew said, Dropdown should be resolved.

Open item would be for us to add the same kind of hover in the combobox input for overflow text. Since this is more of an input and not an item in a dropdown, we won't show the ellipsis.
