### ISSUE TITLE
IBM Plex font loading issues

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#479]
When using the new IBM Plex font, the text on the page appears gradually and very slowly. It's almost unusable. Maybe a CDN issue?

**Comment by asudoh** [comment]
@gmosx Is your carbon-components version later than [8.1.7](https://github.com/carbon-design-system/carbon-components/releases/tag/v8.1.7) which has https://github.com/carbon-design-system/carbon-components/pull/427?

**Comment by gmosx** [comment]
Ah, was using an older version, everything works OK on 8.1.15

**Comment by asudoh** [comment]
Good to hear that the new version works well!
