### ISSUE TITLE
[modal] inputs/components should be able to span full width

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#4790]
Currently the modal has a padding-right of 25%. However, this padding-right should only apply to text in a modal and not restrict other components like form inputs and tables. Those should be able to span the full width of the modal container. 

**As-is:**
![image](https://user-images.githubusercontent.com/11670886/69752713-ced5d500-111f-11ea-9313-3a27c9e1b803.png)

**To-be:**
![image](https://user-images.githubusercontent.com/11670886/69752696-c382a980-111f-11ea-9fb6-0163bddb6196.png)

**Comment by asudoh** [comment]
Hi @aagonzales [does “trap focus” story](https://github.com/carbon-design-system/carbon/blob/3994637dc700a98913128c2062e0f2f20f54bf59/packages/react/src/components/Modal/Modal-story.js#L156-L189) address this issue? react.carbondesignsystem.com may be stale, but I think local clone shows the full width input when we shrink the browser's width. Thanks!

**Comment by aagonzales** [comment]
@asudoh I'm not sure, I can't tell from just the code, I'd have to see it.

**Comment by asudoh** [comment]
@aagonzales Does https://deploy-preview-4657--carbon-components-react.netlify.com/?path=/story/modal--trap-focus work? You'll see full width text box when you shrink the browser window. Please let me know if you have any questions - Thanks!

**Comment by jz2cao** [comment]
@asudoh 
I think @aagonzales was requesting if it is possible for carbon to allow user to utilize the full width of the modal for customized design elements (e.g. it makes sense to have the padding if we simply showing the header and content in the modal, we would also want to flexibility to use the full width if we want to put something like a form into the modal)

thanks

**Comment by aagonzales** [comment]
(oops sorry for the very delayed response)
If `bx--modal-content` is just text should have the 20% padding right but the `bx--modal-content bx--modal-content--with-form` should have padding-right: 16px, so span the full width of the modal.

In the react storybook it was actually just the "default" size that wasn't doing this. The large one was also spanning the full width of the modal.

![image](https://user-images.githubusercontent.com/11670886/72277090-e9440f00-35f6-11ea-8ff8-d34b5b35b781.png)

![image](https://user-images.githubusercontent.com/11670886/72277065-e0533d80-35f6-11ea-98e1-311e30bcc091.png)

**Comment by asudoh** [comment]
Thank you for clarifying @aagonzales @jz2cao! Created #5046.
