### ISSUE TITLE
Data table row sizes not applied when expanded content used

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#4796]
Setting the row size to compact or small using bx--data-table--short or bx--data-table--compact only shrinks the head row.

## What package(s) are you using?

- [x] `carbon-components`

I would assume all are affected

## Detailed description

> Describe in detail the issue you're having.
Compact size produces
![image](https://user-images.githubusercontent.com/15086604/69802324-3bf57300-11d1-11ea-9019-aa768de0cf5d.png)

> Is this issue related to a specific component?
CvDataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?
All rows including expanded content respect the row size.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.7

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
None

## Steps to reproduce the issue

1. Go here http://react.carbondesignsystem.com/?path=/story/datatable--with-expansion
2.Set row height to compact

## Additional information

- Screenshots or code
- Notes

**Comment by jnm2377** [comment]
@lee-chase I have a PR up that fixes some issues with different size expandable tables, but I couldn't reproduce any issues in terms of row size. When I added the size variation stories, the chevron was already aligned, and rows were the right height. I just had to update some left padding for the child expandable row.
