### ISSUE TITLE
Dropdown implementation for navigation dropdown types

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#48]
I'm using the dropdown component in a scenario where one option navigates to a new page, while the other opens a modal window. I've set `data-dropdown-type="navigation"`. However, I've noticed if I select the option that opens the modal, then close the modal, that option is removed from the dropdown list.

I took a quite peek at the `dropdown.js` source, and I'm wondering if it makes sense to add this logic on line [156](https://github.com/carbon-design-system/carbon-components/blob/master/src/components/dropdown/dropdown.js#L156), or if you have any other suggestions.

```
      if (this.element.dataset.dropdownType !== 'navigation') {
        itemToSelect.classList.add(this.options.classSelected);
      }
```

**Comment by asudoh** [comment]
I'm under an impression that L150-L156 should be in the same block as L146. Need to dig into our history to see that.

**Comment by ghost** [comment]
Thanks - I appreciate it!

**Comment by asudoh** [comment]
Digging into our old history I got under impression that the L156 was added due to error in merging. Fixed: https://github.com/carbon-design-system/carbon-components/pull/51
