### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sichangi** [carbon-design-system/carbon#4809]
### Summary
This enhancement improves support for development of the project on the windows operating system.

### Justification
Fixes build & development issues related to the windows OS, making for an easier means of entry into the code base for other contributors down the line.

### Desired UX and success metrics
- Easier means to entry on the project on the Windows OS
- Fixes build issues on windows

### "Must have" functionality
- Consistent build output on the windows OS and any other Operating System.

### Specific timeline issues / requests
ASAP

**Comment by dakahn** [comment]
Hey there! We do officially support Windows development with [WSL](https://docs.microsoft.com/en-us/windows/wsl/about).

We've provided getting started documentation here:
https://github.com/carbon-design-system/carbon/blob/master/docs/guides/setup/windows.md

**Comment by sichangi** [comment]
Oh Wow, I didn't see that, probably have it a little out in the open.

**Comment by sichangi** [comment]
Hey @dakahn,
Now that #4823 was merged, windows development can be done without using WSL.
