### ISSUE TITLE
MultiSelect - ability to have more control over and clear selected items

### ISSUE THREAD

**Issue by kabeaty** [carbon-design-system/carbon#4812]
### Summary

I would like to request that the MultiSelect component be updated so that it's possible to have more control over the selection of items and clearing of already selected items, including clearing all selected items at once. Something similar was previously discussed in this issue that I found with a solution that I ended up using for now for my use case (https://github.com/carbon-design-system/carbon/issues/2623). Also in that issue, the implementation for this requested enhancement that was floated as possibly being the way to go was surfacing Downshift's action props to help with clearing selection/items/etc.

### Justification

This came up in our project when we needed to be able to clear all selections in the MultiSelect component for our Watson Discovery React components from one button that also clears all selections across other components, which use Carbon's Checkbox. You can see the related pull request here, which has more detail, if it helps: https://github.com/watson-developer-cloud/discovery-components/pull/11

### Desired UX and success metrics

The desired UX is that a developer who uses the MultiSelect React component is able to control the component's selections, both selecting and deselecting, from a button or other component instead of one at a time by the user. We can measure the success for the developer if it's possible to do this with props, and there is no longer any need to reference the DOM, as in the solution included in the previous issue above ^.

### "Must have" functionality

Ability to clear all selected items at once is the "must have" functionality for this request.

### Specific timeline issues / requests

No, but I wanted to surface this since it's a question that was asked in the past for a similar use case to get it back on the team's radar.

### Available extra resources

I am a front-end developer who would be able/willing to help with implementing these changes. I wanted to first open this feature request and get feedback from the Carbon team though before proceeding. Please let me know any additional details/info I can provide, thank you!

**Comment by abbeyhrt** [comment]
Hi @kabeaty! 👋 Thanks for making this enhancement request! On our side, we would love to support this work if you would like to contribute it! We do give users the ability to forward downShift props to the MultiSelect and we have a PR in the works to upgrade our Downshift dependency to its latest version which might provide more functionality for what you're trying to do!

**Comment by tw15egan** [comment]
> Here's an example on sandbox:
> https://codesandbox.io/s/modest-merkle-fzltr

**Comment by caritaou** [comment]
We are seeing the same problem, scenario is documented here: https://github.com/elyra-ai/canvas/issues/510

We are using a checkbox to modify the values of the `items` that are passed to the Multiselect. In doing so, if there were any previous `initialSelectedItems`, we are trying to clear that. But as mentioned in this issue, we are not able to do so. 

I was able to make slight progress by modifying the state directly, but that doesn't work anymore as soon as the user select another option. We are not able to reset the selected options after a user makes a selection.

![image](https://user-images.githubusercontent.com/1628100/109206979-6a0f8d00-775d-11eb-911b-82b4bd7bcd4b.png)
From the above image, we can see that there are no selected options passed into the Multiselect control, but there are still items shown as selected: 
![image](https://user-images.githubusercontent.com/1628100/109207005-7398f500-775d-11eb-98fb-17352b67e5e8.png)

**Comment by sali2801** [comment]
any update on this please?

**Comment by dhebert-dev** [comment]
I am also running into an issue with programmatically selecting an existing item when the user attempts to import information into a form which contains this component.

**Comment by gipscoh** [comment]
Hi
I have the same problem.

I can't control value in multi-select (select All value, set current values, reset value). 

THIS PROBLEM SINCE THE 2019 YEAR. AND the Carbon team didn't do anything.

I don't want to wait and I made a component based on React-multi-select-component with styles carbon.

Now I use my custom component:
https://codesandbox.io/s/react-multi-select-component-example-forked-o594c?file=/src/index.js



PS CARBON TEAM - Please stop the closed topics without solving the problem.

**Comment by gipscoh** [comment]
Hi everyone
I found the solution how to set the new value to Multiselect based on initialSelectedValue props:

https://codesandbox.io/s/carbon-design-programmly-setting-value-mfoy6

**Comment by galilmori** [comment]
> Hi everyone I found the solution how to set the new value to Multiselect based on initialSelectedValue props:
> 
> https://codesandbox.io/s/carbon-design-programmly-setting-value-mfoy6

The thing is that everytime you are updayting the value (this is the proposed workaround from carbon team)  you also update your key which rerenders the component. The problem with that of you want to  dynamically update your list according to what you choose the component will rerender and the selection overflow menu will close. Also this is a suboptimal way to use react. You should not rerender a component everytime you click on something!

**Comment by dezkareid** [comment]
I have the same issue, to solve this one I change the useSelection hook to include a value property this one is used like a flag to know if component is controlled or uncontrolled by the user.

Apparently is working fine, I would like to be assigned to this issue, you can check the code of my approach on this [PR](https://github.com/dezkareid/carbon/pull/1)

<img width="1090" alt="Screen Shot 2021-12-04 at 17 44 21" src="https://user-images.githubusercontent.com/1269896/144727984-17de464a-1352-4831-ae07-e072bee2403d.png">

**Comment by arloduff** [comment]
Can someone please clarify if this is working, or if it isn't? https://github.com/carbon-design-system/carbon/pull/10236 makes me think this should be working, but I have the latest carbon-components-react installed (8.16.0 according to the NPM registry) and the selected items are not being updated when I call `setSelectedItems`.
