### ISSUE TITLE
[Breadcrumb] Truncated items support

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#4815]
### Summary

From [the website](https://www.carbondesignsystem.com/components/breadcrumb/style/#recommended),
> “Truncated breadcrumbs are not currently built into the breadcrumb component.“

We've been working towards adding this functionality to our Watson IoT PAL react library ([WIP PR here](https://github.com/IBM/carbon-addons-iot-react/pull/767)), based on the '[threshold implementation](https://angular.carbondesignsystem.com/?path=/story/components-breadcrumb--model)' from [`carbon-components-angular`'s breadcrumb](https://github.com/IBM/carbon-components-angular/blob/master/src/breadcrumb/breadcrumb.component.ts#L18).

[Further discussion on this internal issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/18)

I'd like to discuss lifting our work up to instead contribute directly to `carbon-components-react`.

### Justification

This has been identified as an important reusable piece for IoT products, particularly those with an emphasis on mobile.

### Desired UX and success metrics

![image](https://user-images.githubusercontent.com/3360588/70173691-fafdd280-1698-11ea-90e7-43722d1bdcdc.png)

The design/interaction is already well defined on the website. Breadcrumb items can "collapse" or "truncate" into an overflow menu. I think the main topic for discussion is how the overflow menu items are controlled/collapsed via the implementation.

I do want to confirm with design - an ellipsis character should be used, instead of an icon, [as discussed here](https://github.com/carbon-design-system/carbon/issues/1105)? The first and last breadcrumb items could additionally be given ellipsis via `text-overflow: ellipsis;` when space is even more limited (320px example above).

### "Must have" functionality

Our ideal implementation would be responsive based. The breadcrumb container would be aware of its size, and automatically push/pop breadcrumb items from the overflow menu as space was available to display them. That level of logic for container query functionality may not be feasibly contained here. 

At the very least we could provide the control by which breadcrumb items are put in the overflow menu, with some additional rules:

1. The first and last breadcrumb items can not be put into the overflow menu
1. The overflow ellipsis is always placed second in the breadcrumbs (can not be 3rd, 4th, last, etc)

This is the overall idea of the `threshold` approach, though there might be a better prop name/interface. `threshold` is the number of breadcrumb items that should be displayed. If the amount of children is greater than threshold, items are placed into the overflow menu.

In a product, usage of the prop would likely coincide with a resize event to increase/decrease the threshold based on container/viewport size.

### Specific timeline issues / requests

We can work on this immediately. This has already been identified as a high priority for the Watson IoT PAL, based on the needs of product teams’ deadlines. 

### Available extra resources

@changshunwang has already worked on [an initial implementation](https://github.com/IBM/carbon-addons-iot-react/pull/767). If the implementation agreed to in this issue is close to our existing WIP, we can rework it to move it to a PR here. I will assist in any case.

**Comment by aagonzales** [comment]
Hello! We'd love to have this contributed. I am double checking with Mike Abbink on the ellipse question.

**Comment by kyjak** [comment]
On behalf of the knowledge center, I also upvote this feature, we need it.

**Comment by tay1orjones** [comment]
Our implementation of this relies on `ResizeObserver` and so needs a polyfill for certain [browsers without support](https://caniuse.com/#feat=resizeobserver) (IE11 and Firefox ESR). We don't provide the polyfill in `carbon-addons-iot-react`, and put a warning in the console if the current environment doesn't support RO and the truncation is turned on.

https://github.com/IBM/carbon-addons-iot-react/blob/master/src/components/Breadcrumb/Breadcrumb.jsx

Happy to extract it and open a PR, but would like to discuss first is this a valid direction for implementation in `carbon-components-react`?

**Comment by kyjak** [comment]
Depends on the rules for the project. Are polyfills acceptable?

**Comment by kyjak** [comment]
@jeffchew what do you think?

**Comment by jeffchew** [comment]
> @jeffchew what do you think?

Hey @kyjak. If you're speaking specifically about the IBM.com Library, our team doesn't officially support IE11, so we wouldn't see a need to include a polyfill for this. However, if Knowledge Center still needs to support IE11, you can include a polyfill on your end.

**Comment by tay1orjones** [comment]
Our implementation uses the `use-resize-observer` package/hook, which was recently added to `carbon-components-react` in https://github.com/carbon-design-system/carbon/pull/5854/

@joshblack @asudoh I think it's safe to say that ResizeObserver via `use-resize-observer` is the direction to take for components like this that need to respond to resize events?

**Comment by kyjak** [comment]
Ok, so if there are no blockers, lets copy this functionality into carbon ...

**Comment by asudoh** [comment]
@tay1orjones Yes, it's my thought. A caveat is that we should avoid overusing it - Using `ResizeObserver` for this use case sounds fine, though.

**Comment by ljcarot** [comment]
@kyjak You mentioned the need for this on our call today.  Are you able to find what you need here -> https://github.com/carbon-design-system/carbon/pull/5854

**Comment by laurenmrice** [comment]
Closing because we have this in code now:
https://carbon-components-react.netlify.app/?path=/story/components-breadcrumb--breadcrumb-with-overflow-menu 

👍
