### ISSUE TITLE
DatePicker calendar using appendTo prop is badly positioned if ancestor has padding

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#4818]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

We had an issue where the calendar popup of the DatePicker did not scroll when the input box scrolled.  This is fixed by supplying the appendTo prop and setting it's positioning of that appendTo element to relative.  

However, if there is any padding or margins on ancestors of that appendTo element, the calendar popup does not render in the right place.  If you comment out the padding, it's fine.

Also, if the DatePicker is rendered in a portal, clicking the calendar icon does not work at all.  When I try in my local environment, I get an error about cal not being defined.  In the Code Sandbox, it just silently fails.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
   "carbon-components": "^10.7.0",
    "carbon-components-react": "^7.7.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
OpenPages

## Steps to reproduce the issue
https://codesandbox.io/s/codesandbox-fyj49

**Comment by dakahn** [comment]
We're going to use this issue to track the first problem and roll the portal problem into another issue 👍

**Comment by kglickman** [comment]
The new issue title is inaccurate.  The calender is scrolling correctly now that we've added the appendTo.  However, it is not positioned correctly underneath the input element.

**Comment by asudoh** [comment]
@kglickman Thank you for trying to correct - Would you want to suggest a new subject, or directly edit it if you can? Thanks!
