### ISSUE TITLE
Tile Component Warnings  for Exapanded and onBeforeClick

### ISSUE THREAD

**Issue by electrostaticfleece** [carbon-design-system/carbon#4821]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

**Getting errors in the console for Carbon 10 supported attributes:** 

> "Warning: Received false for a non-boolean attribute expanded".
expanded is a bool and yet throws error expecting a string
> "Warning: Unknown event handler property onBeforeClick. It will be ignored."
Yet it's supposed to be supported.

**Is this issue related to a specific component?**

This is related to the Tile component

**What version of the Carbon Design System are you using?**

Carbon v10.7.0 
Carbon Components React v7.7.0

**Comment by abbeyhrt** [comment]
Hi @electrostaticfleece! Thanks for making this issue! Would you be able to provide a code sandbox reproducing the problem you are having? I am not able to on my end. Thank you!

**Comment by electrostaticfleece** [comment]
@abbeyhrt Thanks for responding! This looks like this was fixed in https://github.com/carbon-design-system/carbon/pull/4630 and can be closed.

**Comment by asudoh** [comment]
Thank you for verifying @electrostaticfleece!
