### ISSUE TITLE
DatePicker Calendar icon not clickable in a portal (cal not defined!)

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#4825]
derived from #4818 

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

"...if the DatePicker is rendered in a portal, clicking the calendar icon does not work at all. When I try in my local environment, I get an error about cal not being defined. In the Code Sandbox, it just silently fails."

> What browser are you working in?

Chrome (latest?)

> What version of the Carbon Design System are you using?

"carbon-components": "^10.7.0",
"carbon-components-react": "^7.7.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

https://codesandbox.io/s/codesandbox-fyj49

**Comment by asudoh** [comment]
Seems not reproducible. I can see a positioning problem (described by #4818) the second date picker (you have to scroll down after date picker is opened to see it), but no NPE. The behavior seems the same for clicking the `<input>` as well as clicking the calendar icon.
