### ISSUE TITLE
Theming UI Shell

### ISSUE THREAD

**Issue by snovak7** [carbon-design-system/carbon#4827]
## What package(s) are you using?
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary
Is it possible to change various colors to particular ui-shell components via @carbon/themes ?

**Comment by joshblack** [comment]
Hi @snovak7! 👋 It's currently not possible to theme the UI Shell, unfortunately, but it's definitely on our road map! I went ahead and made this issue to help track this feature: https://github.com/carbon-design-system/carbon/issues/4839 hope this helps!

**Comment by joshblack** [comment]
Going to close this out in favor of #4839, if you're curious about progress definitely subscribe to that issue!
