### ISSUE TITLE
Visual updates to Terminal component

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon#483]
Ref https://github.ibm.com/Bluemix/carbon-issues/issues/189

Anna wrote:

- I think if we can control the scroll bar then it should be on the inside of the container. 
- Icon should be white and get a brand-01 filled background on hover (essentially a ghost button but without text).

![image](https://media.github.ibm.com/user/380/files/c817c116-befa-11e7-8a15-3922b2004bcc)

**Comment by alisonjoseph** [comment]
closing this since this component was updated with v9 release
