### ISSUE TITLE
Latest styles for CopyButton/Tile components published?

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#4832]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

I'm working with scss files from carbon-components and referencing the React storybook. It seems that some newly updated styles in the `CopyButton` and `Tile` components are not yet published.

For example, the `Tile` component now supports the `light` prop. The scss selector ends with `--tile--light`.

Although [_tile.scss in the master branch](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/tile/_tile.scss#L37) contains these styles, the published ones do not:

**Unpkg:**

- [10.7.4](https://unpkg.com/browse/carbon-components@10.7.4/scss/components/tile/_tile.scss)
- [10.7.0](https://unpkg.com/browse/carbon-components@10.7.0/scss/components/tile/_tile.scss)

## Additional Info

I've tried installing the exact version (10.7.0) for carbon-components as listed in the [package.json on the master branch](https://github.com/carbon-design-system/carbon/blob/master/packages/components/package.json#L4).

I've also opened the React storybook on my local machine and can confirm that the new styles appear as expected.

**Comment by joshblack** [comment]
Hi @metonym! 👋 What is in `master` will be reflected in our next release which should be over the next couple of weeks 😄 Hope this helps!

**Comment by metonym** [comment]
@joshblack Ah, understood! Thank you for clarifying.
