### ISSUE TITLE
Warning state for InlineLoading component

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#4835]
### Summary

We need a warning state in addition to the success and error states currently present in the InlineLoading component.

### Justification

To show the user an appropriate message when their action didn't successfully complete but it's a non-critical fail, an optional step or additional action is required in order to complete it.

### "Must have" functionality

- [ ] `warning` prop for InlineLoading component with appropriate styling

### Available extra resources
*Design Proposal and sample use case*

**Success / Finished**
![success](https://user-images.githubusercontent.com/28265588/70424592-ea21d800-1a6f-11ea-9161-0cbe33e30ee8.gif)

**Error**
![error](https://user-images.githubusercontent.com/28265588/70424569-e2faca00-1a6f-11ea-9077-7bf244dffb3d.gif)

**Warning**
![warning](https://user-images.githubusercontent.com/28265588/70424435-b181fe80-1a6f-11ea-8742-b59a4af65f18.gif)

PR opened: #4810

**Comment by tomlroach** [comment]
I could also see these same message styles being useful without the loading component. Just when the user needs to be informed they have some misconfiguration, or warning on something which doesn't have a synchronus load associated with it. Perhaps with the option to include a resolving action. 

https://ibm-analytics.slack.com/archives/C0M053VPT/p1582566093010200

![image](https://user-images.githubusercontent.com/6569324/75258365-f7677c80-57ab-11ea-9644-28073924728d.png)

**Comment by jillianhowarth** [comment]
Thanks for opening the issue! We are not going to pursue it at this time. We are looking into a status component outside of the loading component.
