### ISSUE TITLE
Dropdown carbon component overrides background colour in modal dialogs

### ISSUE THREAD

**Issue by tom-youd** [carbon-design-system/carbon#4837]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When a Dropdown is used in a modal dialog, the background colour is defaulted to white rather than leaving it as a light grey.

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Expecting the background colour to be light grey and not white.
When you click the dropdown to select and option, the background colours are light grey was makes it look very inconsistent too.
Can you not have an override or let the developers specify the 'inline' dropdown component instead as this has a white background

## Steps to reproduce the issue

1. Place a dropdown in a modal dialog
2. Open the dialog and see the dropdown component

## Additional information
![Screenshot 2019-12-09 at 12 47 39](https://user-images.githubusercontent.com/56865994/70436850-22321680-1a82-11ea-8119-bad89dc6a509.png)

**Comment by joshblack** [comment]
Hi @tom-youd! 👋 I believe this is intentional in the latest version, at least it appears that way when looking at our style guidance: https://www.carbondesignsystem.com/components/modal/style

I think the important bit is that we will need to hit 3:1 contrast ratio between the field color and its background which may be, in part, why this is happening 👍

**Comment by joshblack** [comment]
Hi there! 👋 Going to close this issue out since it's been a while since the last response. Feel free to comment and I can re-open!
