### ISSUE TITLE
Update UI Shell to use our theming tokens

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4839]
Currently, the UI Shell set of components use their own private theming tokens. We should revisit this component and consider how we could either expose these private theming tokens, or how to retrofit UI Shell to our existing theme tokens.

**Comment by aagonzales** [comment]
Agreed! We need to decided add more unique shell tokens to allow for each theme to have a default and high contrast version or if like Josh said we just don't allow for the Shell to deviate from the product (is which case we need to define and update to the system tokens). 

@joshblack so is it official the we'll not be trying to do inline theming with the UI shell?

**Comment by joshblack** [comment]
@aagonzales your call! I'm up for either. I think UI Shell is definitely big enough if we want to go down the component token route, but if we wanted to stay systematic and try and do inline theming I think we're setup for that too in the next version.

**Comment by cwgormanIBM** [comment]
What does "inline theming" mean?

**Comment by joshblack** [comment]
@cwgormanIBM inline theming is an idea we've been thinking about to allow product teams to change the theme of a portion of a page, or for a component. In this case, it would mean that while the page is on the G100 theme, the UI Shell could be themed to be on the white/g10/g90 theme 👍

**Comment by rac0316** [comment]
is it possible to add !default flags to these variables for now so we can overwrite them until a long-term solution gets put in place?

**Comment by joshblack** [comment]
@rac0316 I think the hesitation with `!default` would be that it would be considered part of the public API and we'd have to maintain it as a result 😞 (at least until we could remove it in the next major version)

@aagonzales would this be something we could scope into February or March? Or is it a larger effort?

**Comment by aagonzales** [comment]
I think we can scope it in if we see it as a priority, its on the 2020 design priority list to do we just need to figure out when to do it. UI Shell actually has a whole bucket of work.

**Comment by aagonzales** [comment]
# UI Shell themes

Each Carbon theme will have a set of ui shell themes within it which are surfaced as variations within the ui shell component. Not all options are equal  across themes but vary based on visual aesthetics. Each Carbon theme will have a default shell theme (tbd).

Sketch file: https://ibm.box.com/s/woz3wthxfoqp0pf1kpl20z3kixsoyqdf

## White theme
1. High contrast
2. Mixed contrast
3. Alternate 
4. Mono

![image](https://user-images.githubusercontent.com/11670886/77577357-a038f280-6ea4-11ea-9e91-bc83ed6c6a6a.png)
![image](https://user-images.githubusercontent.com/11670886/77577368-a929c400-6ea4-11ea-97fb-51546fd040b9.png)

## Gray 10 theme
1. High contrast
2. Mixed contrast
3. Alternate 
4. Mixed

![image](https://user-images.githubusercontent.com/11670886/77577672-30773780-6ea5-11ea-995f-e4eab9f0cf0c.png)
![image](https://user-images.githubusercontent.com/11670886/77577725-4553cb00-6ea5-11ea-9281-45bf7bd0acd5.png)

## Gray 90 theme

1. Alternate 
2. Mixed
3. Mono

![image](https://user-images.githubusercontent.com/11670886/77577742-513f8d00-6ea5-11ea-9e68-23b0353e737c.png)
![image](https://user-images.githubusercontent.com/11670886/77577832-8055fe80-6ea5-11ea-8bb4-97086d973330.png)

## Gray 100 theme

1. Alternate 
2. Mixed
3. Mono

![image](https://user-images.githubusercontent.com/11670886/77577859-8946d000-6ea5-11ea-95df-1d55571470e9.png)
![image](https://user-images.githubusercontent.com/11670886/77577883-9663bf00-6ea5-11ea-89e5-c07511297fa1.png)

**Comment by aagonzales** [comment]
## Component by theme break down

### Header
![Header](https://user-images.githubusercontent.com/11670886/87334662-9f37d980-c504-11ea-8240-4a1e9eb92643.png)

### Left nav
![Left nav](https://user-images.githubusercontent.com/11670886/87334670-a2cb6080-c504-11ea-804f-7d66ba0139af.png)

### Right panel
![Right panel](https://user-images.githubusercontent.com/11670886/87334671-a363f700-c504-11ea-89be-87078d235b02.png)

**Comment by janhassel** [comment]
Are there any updates on this issue?

**Comment by aagonzales** [comment]
UI Shell with new token spec can be found here: https://github.com/carbon-design-system/carbon/issues/8102
