### ISSUE TITLE
[UI Shell] Is the font size of the header too small?

### ISSUE THREAD

**Issue by cwgormanIBM** [carbon-design-system/carbon#4841]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

On the Carbon Design System website, the font size in the header is `1rem` (16px):
![image](https://user-images.githubusercontent.com/11217351/70465110-39770100-1a8e-11ea-9d17-9c74cf532ce4.png)

But in the styles, [the font size is set to `body-short-01`, or `0.875rem`](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_header.scss#L116).

![image](https://user-images.githubusercontent.com/11217351/70465295-a8545a00-1a8e-11ea-9ded-8b23d0c85699.png)
 This looks a bit small for a header, in my opinion.

So is this intentional? I asked a designer on our team and he believed it to be a bug in the styles.

**Comment by joshblack** [comment]
Hi @cwgormanIBM! 👋 I believe the font size is intended for products using the UI Shell. If the experience is a digital one, then the larger font size is needed 👍 Hope this helps!

**Comment by cwgormanIBM** [comment]
>If the experience is a digital one

What do you mean by this?

**Comment by joshblack** [comment]
Sorry about the confusion! Digital is typically what we refer to as the marketing side of IBM.com 👍

**Comment by cwgormanIBM** [comment]
Ah I see. So for product use, the small font is correct, then?

**Comment by joshblack** [comment]
Yup! Exactly.

**Comment by cwgormanIBM** [comment]
Do we know the reasoning behind that? If it's too small for Digital, why isn't too small for products?

**Comment by joshblack** [comment]
@cwgormanIBM I believe the rationale is that products tend to be denser in their spatial model and so real estate is more valuable and therefore things are smaller/more condensed. Definitely not a designer so might help to ask over in #carbon-design-system on Slack for feedback from the design group!

**Comment by cwgormanIBM** [comment]
Sounds good! I'll close this. Thanks for your responses!
