### ISSUE TITLE
[UI Shell] Top-level sidenav items don't get a gray background when selected

### ISSUE THREAD

**Issue by cwgormanIBM** [carbon-design-system/carbon#4842]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

https://codesandbox.io/s/fixed-sidenav-n3wlw

![image](https://user-images.githubusercontent.com/11217351/70467164-abe9e000-1a92-11ea-80cc-343aa60d977b.png)

I'm assuming this is unintentional, since it does not match the behavior on the Carbon Design System site: 
![image](https://user-images.githubusercontent.com/11217351/70467207-c58b2780-1a92-11ea-905c-29dfa71ee878.png)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by jendowns** [comment]
I proposed for a fix for this here: https://github.com/carbon-design-system/carbon/pull/4980
