### ISSUE TITLE
Update Sketch Icon Library with new assets

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4849]
We've had several PRs that update the icon library assets and we need to synchronize these additions/changes with the Sketch library.

**Comment by chrisconnors-ibm** [comment]
this tranche of icons from @conradennis last PR is also on our websites but not yet surfaced in our kits: https://github.com/carbon-design-system/carbon/pull/4789

**Comment by lnajjar** [comment]
Yes, when you update the icons on the Carbon Design System Web site, will you please update the icons in the Sketch library? For example, there are [Web site icons](https://www.carbondesignsystem.com/guidelines/icons/library) for "Undo" and "Redo" that do not appear in the Sketch library.

**Comment by chrisconnors-ibm** [comment]
> Yes, when you update the icons on the Carbon Design System Web site, will you please update the icons in the Sketch library? For example, there are [Web site icons](https://www.carbondesignsystem.com/guidelines/icons/library) for "Undo" and "Redo" that do not appear in the Sketch library.

@lnajjar are you using [the correct Libraries](https://www.carbondesignsystem.com/get-started/design/sketch#get-the-kit)? They're both there already.
![image](https://user-images.githubusercontent.com/35537391/75696305-63008c80-5c79-11ea-9732-9a1d2824760e.png)

![image](https://user-images.githubusercontent.com/35537391/75696220-3cdaec80-5c79-11ea-909f-3ba7b278abbb.png)

**Comment by lnajjar** [comment]
@chrisconnors-ibm , you're right. I did not install the "IBM Icons" because I was not designing an application for IBM. Thank you for telling me where to find the icons.
