### ISSUE TITLE
(tile) clickable tile should not have blue text

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#4850]
The text inside a clickable tile should not be a link, the tile itself should be the link. This is what the storybook currently is doing:
![Screen Shot 2019-12-10 at 1.32.39 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/bbf52512-16e2-432c-a480-514fed07cc2d)

The text should be `text-01`.

**Comment by joshblack** [comment]
@laurenmrice I believe this is happening because the tile is built out as a link, if we want to change the color/underline what should we do to accommodate link requirements?

**Comment by laurenmrice** [comment]
I would think we could just use a similar implementation as the carbon clickable tile we use on the website? 

Ex:
![Jan-13-2020 11-49-48](https://user-images.githubusercontent.com/43969356/72279028-d5021100-35fa-11ea-9208-f49efbae89e9.gif)
