### ISSUE TITLE
How correct way to change `$carbon--font-families` map and add Chinese fonts support?

### ISSUE THREAD

**Issue by Garfield550** [carbon-design-system/carbon#4855]
## What package(s) are you using?

- [x] `carbon-components` `^10.7.4`
- [x] `carbon-components-react` `^7.7.4`

## Summary

I use `carbon-components-react` to build my website, but I found the default `$body-font-family` settings are not perfectly displayed Chinese fonts in browsers, so I changed `$carbon--font-families` value, and add some Chinese fonts e.g. `'PingFang SC', 'DengXian', 'Microsoft YaHei UI', 'Source Han Sans SC', 'Noto Sans SC', 'Noto Sans CJK SC', 'Microsoft YaHei', 'WenQuanYi Micro Hei'`, but it is not working.

I create `global.scss` file and use [`sass-resources-loader`](https://github.com/shakacode/sass-resources-loader) to inject it in any `scss` files.

```js
{
  loader: 'sass-resources-loader',
  options: {
    resources: './src/styles/global.scss',
  },
},
```

In `global.scss` file, I use [`map-extend`](https://www.sitepoint.com/extra-map-functions-sass/) sass function modifiy original `$carbon--font-families` value.

```scss
// global.scss
@import '~carbon-components/scss/globals/scss/vendor/@carbon/type/scss/_inlined/_font-family.scss';
@import 'functions';

$override--font-families: (
  'carbon--font-families': (
    'mono':
      unquote(
        "'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', Courier, monospace"
      ),
    'sans':
      unquote(
        "'IBM Plex Sans', 'Helvetica Neue', Arial, 'PingFang SC', 'DengXian', 'Microsoft YaHei UI', source-han-sans-simplified-c, 'Source Han Sans SC', 'Noto Sans SC', 'Noto Sans CJK SC', 'Microsoft YaHei', 'WenQuanYi Micro Hei', sans-serif"
      ),
    'sans-condensed':
      unquote("'IBM Plex Sans Condensed', 'Helvetica Neue', Arial, sans-serif"),
    'sans-hebrew':
      unquote(
        "'IBM Plex Sans Hebrew', 'Helvetica Hebrew', 'Arial Hebrew', sans-serif"
      ),
    'serif': unquote("'IBM Plex Serif', 'Georgia', Times, serif"),
  ),
);

$carbon--font-families: map-extend(
  $carbon--font-families,
  map-get($override--font-families, 'carbon--font-families'),
  true
);
```
My `app.scss` is looked like this:

```scss
$feature-flags: (
  ui-shell: true,
);

@import '~carbon-components/scss/globals/scss/styles.scss';
```

The build result is not changed anything, override font-family settings is not working.

![image](https://user-images.githubusercontent.com/3471836/70588828-f55c3b80-1c08-11ea-9e34-ff0c7b60f28a.png)

**Comment by joshblack** [comment]
Hi @Garfield550! 👋 Thanks so much for taking the time to write out this question and provide so much info, really appreciate it and it really helps when answering questions on our end 🙏 

I'll definitely try and take a look to figure out what's going on, something seems off with how our type reset is reading from the list of families so will dig into this!
