### ISSUE TITLE
CodeSnippet component breaks container below certain width

### ISSUE THREAD

**Issue by Daniel-Schulz-Private** [carbon-design-system/carbon#4858]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

We use the Single-line-CodeSnippet (React) component in our project.
However, the behavior can also be reproduced on the carbon design system [website](https://v9.carbondesignsystem.com/components/code-snippet/code/)

I expect the CodeSnippet Component to be contained within its containers at all times.

This behavior occurs on Firefox (71) as well as Chrome (78).

Carbon Design System v9 (it is fixed with v10)

## Steps to reproduce the issue

1. open carbon design system page https://v9.carbondesignsystem.com/components/code-snippet/code/
2. reduce browser width manually or use simulation to reduce size to size of iPhoneX for example.
3. See the CodeSnippet component breaking its container

## Additional information
![image](https://user-images.githubusercontent.com/51151716/70624334-60653c80-1c20-11ea-9f00-0507cf7c7879.png)

**Comment by joshblack** [comment]
Hi @Daniel-Schulz-Private! 👋 Thanks so much for taking the time to make this issue 🙏 

Given that this is on v9 of Carbon, we won't be able to prioritize a fix for this but would gladly accept any contributions that help to address this!
