### ISSUE TITLE
[InlineNotification]: Action button is misaligned when close button is hidden

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#4864]
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When I pass `hideCloseButton` prop to `InlineNotification` and have an action button set up, the button is too far to the right so that its background is flush to the right side when hovering.

## Steps to reproduce the issue

1. Visit storybook at http://react.carbondesignsystem.com/?path=/story/notifications--inline
2. Select knob `hideCloseButton`
3. Hover over "Action" buttton
(better visible when `lowContrast` is also selected)

## Additional information

![image](https://user-images.githubusercontent.com/28265588/70703118-b644ed80-1ccf-11ea-86a3-edbb7bcafadc.png)
![image](https://user-images.githubusercontent.com/28265588/70703144-c5c43680-1ccf-11ea-8a4e-a6adf6f19e46.png)

**Comment by jendowns** [comment]
I can propose a fix for this 👍 Though it really depends on how much spacing @carbon-design-system/design would like to see on the right side?

**Comment by aagonzales** [comment]
@jendowns I think `8px` would do it.
