### ISSUE TITLE
Submission solution for making community driven work visible/available (*Draft*)

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#4869]
_This epic requires significant more definition before it is actionable, but is here as an outline of intent._

**Intent**

Create a robust solution so that any team can make their universal patterns broadly visible and available to all. It is also important that this is done in a way that the Carbon team is not a bottleneck for submission.

- @mattrosno is gathering feedback from stakeholders to validate the right method (e.g. "submission site") for such a portal, and additional functionality requirements.
- Solution must include:
  * Must allow self-submission
  * Submission not dependent on Carbon feedback or approval (but *will* include post-submission quality checks, including path to potential "promotion" clearly popular/high-usage patterns)
  * Checklist/template to ensure consistency of submissions (analagous to checklist Apple uses for submissions to App store
- Scope for evolution to include submission options for component extensions or new components, and greater categorization

**Comment by joshblack** [comment]
Going to close this one out due to inactivity!
