### ISSUE TITLE
Unable to select the to-date in the Range Date Picker

### ISSUE THREAD

**Issue by arunchris** [carbon-design-system/carbon#487]
Unable to select the to-date in the Range Date Picker. 

[https://codepen.io/team/carbon/pen/aVLbNx](url)

**Comment by asudoh** [comment]
Found that `Flatpickr` assumes single `<input>` - It attempts to set `1/9/2018 to 1/10/2018` to the `<input>`. Need to see if we can work around it or propose a simple change in `FlatPickr` code.

**Comment by arunchris** [comment]
Working fine with 8.2.2. Thank you!
