### ISSUE TITLE
Improved blues in the default color scheme

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#488]
How about replacing that pale blue color in the default scheme, with the more modern 'electric' blue color used on ibm.com or even in the new carbondesignsystem site?

**Comment by tay-aitken** [comment]
Hello @gmosx. Please follow the issue template when creating a new issue in one of the Carbon repos. You have three days to re-comment following the issue template, if not this issue will be closed. Thank you.

**Comment by bsonefeld** [comment]
Closing issue as it does not follow our issue template guideline.
