### ISSUE TITLE
How to use sass tokens in user defined components?

### ISSUE THREAD

**Issue by simula-r** [carbon-design-system/carbon#4883]
Hello I am using create-react-app and I am unable to use the sass tokens provided by importing "carbon-components/scss/globals/scss/styles.scss";

I am assuming the package is setup so a user can use varaibles like $spacing-03 in their own component sass files. However this is not possible unless you import both the globals/scss/styles.scss and your components/customcomponent.scss in the same file which causes a massive (40+ second) recompile everytime you make an edit to customcomponent.scss. 

The React tutorial outlines how to import these files to avoid that recompile time however when I implement this in create-react-app it breaks the import and gives me an `undefined varibale: "$spacing-03";

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

**Comment by asudoh** [comment]
Hi 👋 `styles.scss` merely is an entry-point. You can pick and choose the imports behind it, e.g. choosing components to use, and using our variables/mixins, etc. If you search for `$spacing-03` in `/path/to/your/project/node_modules/carbon-components/scss`, you'll see:

```
Searching 259 files for "spacing-03:"

...

/path/to/my-project/node_modules/carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/layout/_spacing.scss:
   24  /// @access public
   25  /// @group @carbon/layout
   26: $carbon--spacing-03: carbon--mini-units(1) !default;
   27  
   28  /// 0.75rem (12px) spacing with default mini unit
   ..
  115  /// @group @carbon/layout
  116  /// @alias carbon--spacing-03
  117: $spacing-03: $carbon--spacing-03 !default;
  118  
  119  /// @type Number
  ...
  285  /// @access public
  286  /// @group @carbon/layout
  287: $carbon--fluid-spacing-03: 5vw;
  288  
  289  /// 10vw fluid spacing
  ...
  320  /// @group @carbon/layout
  321  /// @alias carbon--fluid-spacing-03
  322: $fluid-spacing-03: $carbon--fluid-spacing-03 !default;
  323  
  324  /// @type Number

...
```

Which means you can do:

```scss
import 'carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/layout/spacing';
```
