### ISSUE TITLE
Duplicate files in FileUploader when uploading the same file

### ISSUE THREAD

**Issue by flyHe** [carbon-design-system/carbon#4884]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`
- [x] `@console/pal`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

http://react.carbondesignsystem.com/?path=/story/fileuploader--fileuploader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

only one file should be shown

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

http://react.carbondesignsystem.com/?path=/story/fileuploader--fileuploader

1. select one file
2. select the same file

## Additional information

- Screenshots or code
- Notes
![Kapture 2019-12-16 at 14 24 00](https://user-images.githubusercontent.com/10543919/70884055-c6323980-200f-11ea-90a2-ce6eabfe7600.gif)

**Comment by aledavila** [comment]
Hi there thanks for bringing this up. However after discussion, this is logic that should be handled at the application level. Closing. If you have further questions feel free to ask here thanks.
