### ISSUE TITLE
Slider "stepMultiplier" prop is incorrectly named "stepMuliplier"

### ISSUE THREAD

**Issue by jharvey10** [carbon-design-system/carbon#4897]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The Slider component has a prop in the docs called `stepMultiplier`, however in the react storybook, as well as in the code, the prop is erroneously named `stepMuliplier`.

> Is this issue related to a specific component?

Yes, the "Slider" component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

n/a

> What browser are you working in?

n/a, but Chrome.

> What version of the Carbon Design System are you using?

Whatever the public website's React storybook is backed by. Locally, I'm using version 7.7.4.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Z HMC/SE

## Steps to reproduce the issue

[CodeSandbox](https://codesandbox.io/s/modest-archimedes-mx94d?fontsize=14&hidenavigation=1&theme=dark)

## Additional information

n/a

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

component: slider
package: react
type: bug

**Comment by jharvey10** [comment]
In terms of helping out with this issue, I think the refactor itself would be pretty straightforward, but I'd need to know how to handle the old prop name, since unless the carbon-components-react major version number is bumped, it would not make sense to remove the old prop name.

**Comment by asudoh** [comment]
Hi 👋 thank you for your offer to help, and good question - The most important part is making both old/new prop name work. Then you can mark the old prop name as deprecated in a similar way to: https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/react/src/components/Button/Button.js#L133-L140
