### ISSUE TITLE
Interior left nav collapse element bottom margin issue

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon#490]
## Detailed description

For some reason the interior left nav collapse element has a bottom margin on it that's causing it to not be flush to the bottom of the page.

> Is this issue related to a specific component? 

Yes, interior left nav.

> What did you expect to happen? What happened instead? What would you like to see changed?

The expectation is the collapse element is flush to the bottom of the page.

> What browser are you working in? 

Chrome 63

> What version of the Carbon Design System are you using? 

7.17

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Container Service

## Additional information

![image](https://user-images.githubusercontent.com/18622709/34682727-64fdc31e-f465-11e7-91aa-a334c98aa307.png)

![image](https://user-images.githubusercontent.com/18622709/34682678-3c1f33c4-f465-11e7-85b6-2b6241a03a31.png)

**Comment by marijohannessen** [comment]
Hi @jrpomeroy , I'm unable to reproduce this. Are you still experiencing this issue? If so, please feel free to re-open this issue!
