### ISSUE TITLE
Modal does not overflow correctly in IE11

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4900]
If you visit our transactional modal page in IE11, the modal does not correctly overflow. This issue is to address this visual regression.

![image](https://user-images.githubusercontent.com/3901764/71022385-f89e6e00-20c5-11ea-9611-789317937c4b.png)

**Comment by kgibb** [comment]
I was able to partially resolve this by enabling CSS Grid in autoprefixer.

```autoprefixer({grid: "autoplace"})```

Some additional IE11 specific styling is still required where autoprefixer can't successfully map the rule.

```
.#{$prefix}--modal-container {
	-ms-grid-columns: 100%;
}
.#{$prefix}--modal-footer {
	-ms-grid-column: 1;
	-ms-grid-row: 4;
}
```
