### ISSUE TITLE
CodeSnippet with type="multi" truncates strings with many lines after clicking "Show more"

### ISSUE THREAD

**Issue by abvte** [carbon-design-system/carbon#4903]
If you insert a string into the CodeSnippet with many lines and new lines, eventually the CodeSnippet component will start truncating the text after clicking the "Show more" button. Many scripts have a lot of new lines for organization.

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react@7.7.4"`

> Is this issue related to a specific component?

CodeSnippet with type="multi" passed in.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I'd expect to see the entire text. It's misleading to me to click the "Show more" then have the text stop at a point without being able to click "Show more" again to see more of the script.

> What browser are you working in?

Chrome 75.0.3770.142 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

V10

## Steps to reproduce the issue

https://codesandbox.io/s/flamboyant-torvalds-31gc7

Click the "Show more" in the CodeSnippet, you'll see that half of the text is truncated

**Comment by jendowns** [comment]
I have an idea to resolve this one. 👍 I can propose a fix shortly.
