### ISSUE TITLE
DynamicRows component not exported from carbon-components-react

### ISSUE THREAD

**Issue by RandyJ1** [carbon-design-system/carbon#4908]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?
General Issue, can't import the package.

> Is this issue related to a specific component?
Yes, it's only happened with the DynamicRows components so far, all other data table components have worked.

> What version of the Carbon Design System are you using? v10

## Steps to reproduce the issue

1.  import {DynamicRows} from "carbon-components-react";
2. run application.
3. Should get error saying DynamicRows isn't exported from carbon-components-react.

**Comment by joshblack** [comment]
Hi @RandyJ1! 👋 Are you referring to the storybook story? The component itself is meant for demo purposes so we won't export this functionality, but you can view the source code here! https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/stories/with-dynamic-content.js#L44

Hope this helps! Going to close this for now, but feel free to comment and I will gladly re-open!
