### ISSUE TITLE
Tooltip is not browser aware and is clipped

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4909]
When visiting a tooltip example that runs to the edge of the screen, we observe this behavior:

![image](https://user-images.githubusercontent.com/3901764/71038365-4d061580-20e7-11ea-9ad8-90f2222808dc.png)

This issue is to determine whether or not we need to make the tooltip positioning browser-aware or if there is another solution we could use that would not clip the text in the tooltip.

**Comment by asudoh** [comment]
Recommended to introduce alignment options like definition/icon tooltips, in case interactive tooltip does not have one.

**Comment by joshblack** [comment]
@asudoh what is the recommendation to detect when placement needs to be updated? Like, in this case, we'd want to move it to the right when the browser becomes small or if viewing from a mobile device.

**Comment by asudoh** [comment]
Just in case my above commend was not clear enough; Definition/icon tooltip has alignment options so that tooltip caret can be positioned at the left/right of the tooltip body so the the left of tooltip body is close or aligned to the trigger button/icon, etc.

**Comment by joshblack** [comment]
Right, I follow that there are alignment options for tooltips. My question was around how would a user understand that the current alignment option would be clipped by the browser due to its placement and update it dynamically 👍

**Comment by asudoh** [comment]
I wouldn't recommend OOTB automatic alignment option due to the complexity around it. It may be different for PALs/applications using Carbon.

**Comment by joshblack** [comment]
I definitely understand if we don't want to do this out-of-the-box, I'm curious what we would recommend to teams then who are encountering this issue.

**Comment by asudoh** [comment]
No recommendation in particular; PALs/applications can use regular techniques to detect element positions/sizes.

**Comment by TannerS** [comment]
I am also having this issue

**Comment by ngtiffan** [comment]
Can we add this as an optional feature? Like it's implemented but it won't be turned on unless we specify that it does via some attribute. I can see this being really useful in a lot of situations. If the tooltip goes out of bound on the left, move the placement to the right. If it goes out of bounds on the bottom side, move it to the top and vice versa.

**Comment by maniax89** [comment]
@asudoh is there a chance that https://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom will adopt the same alignment options as https://react.carbondesignsystem.com/?path=/story/tooltipdefinition--default ? right now it seems like we don't have control over the interactive one

**Comment by asudoh** [comment]
The effort is tracked separately at #3837.

**Comment by andreancardona** [comment]
This issue no longer exists. Closing. :)
