### ISSUE TITLE
Dropdown component doesn't support component label. 

### ISSUE THREAD

**Issue by Kimi1020** [carbon-design-system/carbon#4913]
## Title line template: [Title]: Brief description
**I want to show the component label after selecting a component option for dropdown.** 

## What package(s) are you using?
**carbon-components-react**

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
**Yes, carbon/packages/react/src/components/Dropdown/Dropdown.js**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
For dropdown component, if I use itemsToElement to make option an component, after select it, it will show itemToString function's result.  I think it should show the component as well.

After I checked the source code of **Dropdown.js**, I found below code. It use itemToString function to render the label. In my circumstance, I want to use itemToElement to render the label. Shall we support it for this dropdown component?

 `  {selectedItem ? itemToString(selectedItem) : label}`              
Source: carbon/packages/react/src/components/Dropdown/Dropdown.js

> What browser are you working in?
**chrome v79**
> What version of the Carbon Design System are you using?
**carbon-components-react": "^7.7.3"**

**Comment by Kimi1020** [comment]
If I set itemToString={itemToElement},  below  key={itemToString(item)} will report object key warning.
`<ListBox.MenuItem
                      key={itemToString(item)}
                      isActive={selectedItem === item}
                      isHighlighted={
                        highlightedIndex === index || selectedItem === item
                      }
                      {...getItemProps({ item, index })}>
                      {itemToElement ? (
                        <ItemToElement key={itemToString(item)} {...item} />
                      ) : (
                        itemToString(item)
                      )}
                    </ListBox.MenuItem>`

**Comment by jendowns** [comment]
I can help with this 👍 PR coming shortly

UPDATE: PR is here https://github.com/carbon-design-system/carbon/pull/4977
