### ISSUE TITLE
Replace magnifier icon on the Search component

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#4918]
**As I'm using**

- [x] `carbon-components`

- [x] `carbon-components-react`

**I would like to**

Replace the magnifier icon on the [Search](http://react.carbondesignsystem.com/?path=/story/search--default) component for React with another icon from the same library.

**So I request**

Help, suggestion or any tip to do so or find a workaround this.

**Comment by asudoh** [comment]
@carbon-design-system/design Would we be OK to allow using alternate icon for search? Thanks!

**Comment by aagonzales** [comment]
@mazafederico What icon would you want to replace it with? I don't think we'd want to replace the search icon in the search component with any other icon.

**Comment by ghost** [comment]
@aagonzales, would be superb to be able to use the `plane` icon from the [Carbon Icons](https://www.carbondesignsystem.com/guidelines/icons/library/) at least.

Is this possible? Is there a way to send an icon as a `prop` to that component?

**Comment by aagonzales** [comment]
@mazafederico Are you still using the component as a search or do you just want a text field where you can add a custom icon? If it's a search component then its best practice to use the search icon.

**Comment by chrisconnors-ibm** [comment]
In the interest of consistency, we use (and include) the magnifying glass as the 'search' icon (which is also the case for the majority of other properties our users encounter). We don't want users to have to interpret a handful, or even two, icons for the same task/goal.

'plane' is frequently used as a metaphor for 'send' or sometimes 'submit', but that is not the task here.

Is this a localization issue?

**Comment by ghost** [comment]
I just want to get the flexibility to create a different UX on the site as the one you can see in these cases:

- [KAYAK](https://www.kayak.com.ar/?ispredir=true)
- [Despegar](https://www.despegar.com.ar/)
- [Booking](https://booking.kayak.com/?sid=dbdc93adfd8d7f41ba153bf7b162113d&aid=378266&label=booking-name-IquAp*EbiLS6jPVl_he8yQS267778093600%3Apl%3Ata%3Ap1%3Ap22%2C581%2C000%3Aac%3Aap1t1%3Aneg%3Afi%3Atikwd-65526620%3Alp1000037%3Ali%3Adec%3Adm)

Although [American Airlines](https://www.aa.com/homePage.do?locale=es_AR&c=SEM|GOOG|01012018|MKT|MKT|TXT|american%20airlines|LAC_Argentina;_TRAN_SEM_SEARCH2018&gclid=CjwKCAiA3OzvBRBXEiwALNKDP7tw0cALtHIpRq8envl1Gnbd28Upyx505aYVIMTQZAqYaf4x3p0ynRoCO-4QAvD_BwE&mkwid=sIaMKSVT3_333309105118_american%20airlines_e_c&mtid=18702yov37034&slid=&product_id=&targetids=kwd-295226130849&adgroupid=48955041765&cp=;) do respect the pattern you are mentioning, I don't really see the benefit on locking the magnifier icon when a simple change on the implementation could give the component much more flexibility to adapt to different situations or _markets patterns_ as in this case.

**Comment by chrisconnors-ibm** [comment]
![image](https://user-images.githubusercontent.com/35537391/71211326-e4e93800-227c-11ea-8850-d3f795f62f08.png)
![image](https://user-images.githubusercontent.com/35537391/71211371-f8949e80-227c-11ea-9bd3-6adf0eadbb93.png)
![image](https://user-images.githubusercontent.com/35537391/71211398-08ac7e00-227d-11ea-91f0-d09b685c77ea.png)
![image](https://user-images.githubusercontent.com/35537391/71211445-27ab1000-227d-11ea-868a-bdee6f08e592.png)

**Comment by chrisconnors-ibm** [comment]
Like these 4, our component is for generalized search operations. 

A specific field type/icon is the type of component we'd look to a team who needed it to design, implement, and hopefully submit back.

**Comment by aagonzales** [comment]
Ok, so its actually a facet inside of a larger advanced search that you'd want to have the custom icon for a filter search. I think that's an important thing to note. Each of these still have a search icon present as the primary search trigger. Having duplicate search icons could be confusing in those instances. 

![image](https://user-images.githubusercontent.com/11670886/71213094-596da800-2278-11ea-8cf0-95e231f03d0d.png)
![image](https://user-images.githubusercontent.com/11670886/71213118-6ab6b480-2278-11ea-82ae-21fee504be8b.png)
![image](https://user-images.githubusercontent.com/11670886/71213147-74d8b300-2278-11ea-8841-444c9f88b6a9.png)

**Comment by ghost** [comment]
@chrisconnors-ibm, I would be pleased to contribute by making those changes if you point me in the right direction.
