### ISSUE TITLE
Breadcrumb visited link color issue

### ISSUE THREAD

**Issue by nitishjain07** [carbon-design-system/carbon#4920]
Hi Team,

As per latest carbon design CSS, visited link has a different color(#8A3FFC) then default link color(#0F62FE). Because of this breadcrumb show links with different colors sometimes as you can see in the attached screenshot. As discussed in carbon-design-system slack channel (https://ibm-cognitive-engage.slack.com/archives/C0M053VPT/p1576687676025800?thread_ts=1576687465.025500&cid=C0M053VPT), raising a issue for this.

<img width="1264" alt="Screenshot 2019-12-18 at 10 08 51 PM" src="https://user-images.githubusercontent.com/18714593/71145754-9e79e600-2248-11ea-99ef-15a8ae0f556d.png">

**Comment by asudoh** [comment]
@carbon-design-system/design Any guidance on this...? Thanks!

**Comment by aagonzales** [comment]
Yes, the breadcrumb should not have the `visited` state applied. It would actually be ideal if the `link` component could have the `visited` state be optional/configurable because it is common not to have the visited style while in a product.

**Comment by asudoh** [comment]
Thanks @aagonzales! I think this can be done by changing style of `.bx--breadcrumb-item .bx--link:visited`.

**Comment by jendowns** [comment]
I can help with this! PR coming up shortly 👍 

EDIT: PR here https://github.com/carbon-design-system/carbon/pull/4976
