### ISSUE TITLE
Change the width of a DatePicker component

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#4922]
**As I'm using**

- [x]  carbon-components
- [x]  carbon-components-react

**I would like to**

Change the width of a [DatePicker](http://react.carbondesignsystem.com/?path=/story/datepicker--simple) component for React.

**So I request**

Help, suggestion or any tip to do so or find a workaround this.

**Comment by asudoh** [comment]
Hi 👋 thank you for asking - You can definitely do it via CSS.

**Comment by ghost** [comment]
I have tried a couple of approaches @asudoh before asking.

Apparently the component does not expand to fill all the width available, as a block type element for example.

Which is your recommendation in this case?

**Comment by asudoh** [comment]
In Chrome, if you right-click on the `<input>` and select Inspect, and go to Styles tab and change the `width` property in `.bx--date-picker.bx--date-picker--simple .bx--date-picker__input` ruleset, you'll see the width increases. Does it answer your question...?

**Comment by ghost** [comment]
After trying that @asudoh, what I get is either one of the following scenarios after setting `width: 100%` on the following elements:

- `bx--date-picker bx--date-picker--range bx--date-picker--nolabel`
- `bx--date-picker-container bx--date-picker--nolabel`
- `bx--date-picker-input__wrapper`
- `bx--date-picker__input flatpickr-input`

**Scenario 1**

<img width="480" alt="Screen Shot 2019-12-20 at 17 21 46" src="https://user-images.githubusercontent.com/48722556/71290072-a8d1d800-234d-11ea-9371-814ff0aaa79c.png">

**Scenario 2**

<img width="1140" alt="Screen Shot 2019-12-20 at 17 21 12" src="https://user-images.githubusercontent.com/48722556/71290092-b2f3d680-234d-11ea-9948-e8f32957b7d4.png">

**Comment by ghost** [comment]
Any suggestions @aagonzales? Is this a bug on the component wrapper?

**Comment by asudoh** [comment]
Would you want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox to explain where you are at?

**Comment by ghost** [comment]
Sure @asudoh.

As you can see in the following code sandbox the `Search` component expands to fill all the available space working as a flex element, but the `DatePicker` component has a fixed width.

[![Edit magical-lalande-rjjvb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-lalande-rjjvb?fontsize=14&hidenavigation=1&theme=dark)

**Comment by asudoh** [comment]
Do you want to add something like the following to you app's style?

```css
.your-date-picker-container .bx--date-picker__input {
  width: auto;
  max-width: none;
  flex: 1;
}

.your-date-picker-container .bx--date-picker-input__wrapper {
  width: 20rem;
}
```

**Comment by ghost** [comment]
Could you add that to the code sandbox to see the resulting behavior, please?
