### ISSUE TITLE
Tabs component with aria-label does not pass IBM DAP tool

### ISSUE THREAD

**Issue by mattalco** [carbon-design-system/carbon#4924]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
Yes, the Tabs component

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The aria-label added to the Tabs component is not where the IBM DAP tools expects it.

> What browser are you working in?
Google Chrome

> What version of the Carbon Design System are you using?
~~10.5.1~~ 10.7.4 and 7.7.4 (react components)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
No

## Steps to reproduce the issue

https://codesandbox.io/s/unruffled-snow-0r5vh

1.  View the element in the Elements tab and see the aria-label is added one level beneath the top level component. This seems to be what DAP is upset about. Adding the aria-label manually to this top level component resolves the DAP error.

## Additional information

DAP
--

<img width="666" alt="Screen Shot 2019-12-19 at 1 01 27 PM" src="https://user-images.githubusercontent.com/13972013/71197521-cb85c300-225f-11ea-84ec-a742f0acc73b.png">

Element in DOM
--

<img width="660" alt="Screen Shot 2019-12-19 at 12 58 42 PM" src="https://user-images.githubusercontent.com/13972013/71197522-cb85c300-225f-11ea-824f-c0882ce0a30b.png">

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

**Comment by abbeyhrt** [comment]
@mattalco Thanks for making this issue! Are you able to reproduce the DAP violation using the latest version of Carbon? That would be 10.7.4 for `carbon-components` and 7.7.4 for `carbon-components-react`

**Comment by mattalco** [comment]
My fault, I'm actually already on 10.7.4 for carbon-components and 7.7.4 for carbon-components-react. I got that initial value from the `package.json` and forgot to double check what I had locally.

**Comment by kkomprakash** [comment]
I have reproduced the issue with latest carbon version in this codesandbox https://codesandbox.io/s/crazy-brahmagupta-s34y4 .

Screenshot of error: 

![image](https://user-images.githubusercontent.com/38567891/74681676-dd5ce700-5178-11ea-875b-465e0a63b995.png)


Issue happens when there are more than one navigation elements present in the page along with the Tabs component. When we add `aria-label` attribute to the `bx--tabs` div, then issue gets fixed.

**Comment by joshblack** [comment]
If you supply `aria-label` to `Tabs` instead of `ariaLabel`, does that address the violation that you're experiencing?

**Comment by kkomprakash** [comment]
yes. That seems to work fine for me

**Comment by joshblack** [comment]
Yay! Glad to hear it 😄 

Going to close this one out then, let me know if I should re-open!
