### ISSUE TITLE
User assistance widget

### ISSUE THREAD

**Issue by asfordmatt** [carbon-design-system/carbon#493]
## Detailed description

Enhancement request for a user assistance widget, that can provide embedded help plus one or two links to external URLs

> Is this issue related to a specific component? 

Could possibly addressed by the tooltip component, or a new component.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM App Connect

## Additional information

Here one example of the tooltip approach, but other options might include a regular tooltip plus a passive modal:

![image](https://user-images.githubusercontent.com/14233261/34730401-35ccc4f8-f557-11e7-8beb-74439eb8de95.png)

**Comment by alisonjoseph** [comment]
Closing this. Would be best addressed in an addon if a team is willing to build it.
