### ISSUE TITLE
[Clickable Tile and Link]: Order Import Changes Visuals

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#4937]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Is anyone else seeing this issue we're having with the `ClickableTile`? For some reason `.bx--link` is being applied to the `ClickableTile`, which is causing some unexpected behaviors. If I use it out of the box it looks one way, if I use it in conjunction with the `Link` component I get another look depending on the order of the `SCSS` imports. Check out what I mean below...

Here is just the `ClickableTile`
https://codesandbox.io/s/clickabletile-basic-m1o9s?fontsize=14&hidenavigation=1&theme=dark

Adding in the `Link`
https://codesandbox.io/s/clickabletile-with-link-yo9ji?fontsize=14&hidenavigation=1&theme=dark

Changing order of imports
https://codesandbox.io/s/clickabletile-with-link-change-order-c96i1?fontsize=14&hidenavigation=1&theme=dark

It appears as if the inconsistency is stemming from the addition of `.bx--link`. I'm wondering why this is there, if it's a mistake, and if it can be removed or not. If not I'm wondering if there is another solution to maybe stabilize this component a little better. Maybe pull in the `Link` `SCSS` with the `Tile` `SCSS`? I don't know if it would solve for all edge cases though.

I don't know... Any thoughts?

**Comment by asudoh** [comment]
Seems that the addition was for the theme-ability: #3270 If #3270 can be addressed without adding `.bx--link` it may be our way to go.

**Comment by joshblack** [comment]
Closed by: https://github.com/carbon-design-system/carbon/pull/8159 I believe!
