### ISSUE TITLE
Active Search implementation

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#4939]
Is there any place to see how to implement an [Active Search](https://www.carbondesignsystem.com/patterns/search-pattern#active-search)?

**Comment by asudoh** [comment]
Basically not, but I remember IBM Cloud core console has a similar UI, or at least used to have. Tapping the team may help.

**Comment by NateAGeek** [comment]
I mean this with no offense, I greatly appreciate the work done on the carbon system. However, I am finding it challenging reading the suggested patterns, only to find that elements are not in the React Library clearly. It might be useful to add the patterns to the examples folder, or update the documentation to contain the primitive components required to achieve the encouraged patterns.
