### ISSUE TITLE
DatePickerInput onChange prop does not fire when date is selected from DatePicker

### ISSUE THREAD

**Issue by simula-r** [carbon-design-system/carbon#4943]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Possible bug/general issue.

When selecting a date from the DatePicker's calendar the DatePickerInput's value changes however the onChange prop does not fire. How can one go about setting the DatePicker as a controlled input via state so that it stores the current value of the DatePickerInput. I want to store the formatted Date (i.e "01/02/2020") inside the DatePickerInput.

> Is this issue related to a specific component?

DatePicker and DatePickerInput

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon components react = 7.7.4

## Additional information

```
<DatePicker
    dateFormat="m/d/Y"
    datePickerType="single"
      id="date-picker"
     locale="en"
     short={true}
>
                    <DatePickerInput
                      className="some-class"
                      iconDescription="Date Calendar icon"
                      id="date-picker-input"
                      invalid={false}
                      invalidText="A valid due date is required"
                      labelText="Due Date"
                      pattern="\d{1,2}/\d{1,2}/\d{4}"
                      placeholder="mm/dd/yyyy"
                      type="text"
                      defaultValue={dueDate} //this is my state variable
                      onChange={e=>{setDueDate(e.target.value)}} //attempting to update state with the datepicker input's value however it does not trigger unless manually set
                    />
</DatePicker>
```

**Comment by asudoh** [comment]
Seems that the change from date picker dropdown can be captured via `onChange` in `<DatePicker>` instead of one in `<DatePickerInput>`.

**Comment by asudoh** [comment]
Closing as a solution has been provided. Let us know if this doesn't solve the problem - Thanks!
