### ISSUE TITLE
Need danger button alternatives

### ISSUE THREAD

**Issue by mitchellbernstein** [carbon-design-system/carbon#4945]
## Need danger button alternatives:
Our team requires secondary, tertiary, and ghost versions of the danger buttons. The primary version draws too much attention in the interface.

## Detailed description

The current implementation of carbon excludes what carbon 9 had for the danger button (secondary, tertiary, and ghost versions) which we would like to reintroduce due to their reduced emphasis on exposing dangerous controls where there are lots of actions to take. We don't want to show a ton of blinding red buttons everywhere.

**Is this issue related to a specific component?**
The Danger button

**What would you like to see changed?**
We would like to reintroduce the secondary, tertiary, and ghost versions of the danger button itno carbon.

**What version of the Carbon Design System are you using?**
Latest

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**

- Watson Studio / IBM Cloud Pak for Data
- Shipping updates by Q2

## Additional information
- Here is an instance where we wish to use the ghost or at least the tertiary (outline) version:
![image](https://user-images.githubusercontent.com/748263/71682375-83859680-2d5d-11ea-91d9-8643e3be883d.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design  Any there plans on supporting variations of the Danger button?

**Comment by aagonzales** [comment]
We've talked about adding an outlined and ghost button version. I will add it to the list of component enhancements.

**Comment by AlexanderLyon** [comment]
@tw15egan I'd love to work on this task, can you assign me to it?

**Comment by aagonzales** [comment]
The approved design spec for ghost button variations are in issue: https://github.com/carbon-design-system/carbon/issues/5610
