### ISSUE TITLE
Contribution: Toolbar low and high contrast

### ISSUE THREAD

**Issue by m-battelli** [carbon-design-system/carbon#4948]
**Brief description**

I have designed a new pattern using standard components of the Carbon Design System (V10).
It is an useful pattern, easily standardable to be included in the Carbon library and easily customizable based on the use cases.
Essentially, the toolbar could be part of the widest range of products where it is necessary a main actions set ready to use and positionable in the most suitable way on the screen.
I have explored visually the low and high contrast versions for consistency with the rest of standard components. 

**White theme**
![Toolbar White](https://user-images.githubusercontent.com/47557215/71736129-8ca36000-2e50-11ea-9c90-bead02dc7831.png)

**Gray 10 theme**
![Toolbar Gray 10](https://user-images.githubusercontent.com/47557215/71736151-a0e75d00-2e50-11ea-80dc-91b9da6091b2.png)

**Gray 90 theme**
![Toolbar Gray 90](https://user-images.githubusercontent.com/47557215/71736192-bb213b00-2e50-11ea-9ca7-d5f6a4081ceb.png)

**Gray 100 theme**
![Toolbar Gray 100](https://user-images.githubusercontent.com/47557215/71736221-cffdce80-2e50-11ea-9b62-db44dd0b6af1.png)

**Use case**
I have adopted this pattern to build and interact with diagram model.
This use case is available within Cloud Pak for Automation / Decisions.
<img width="816" alt="Screenshot 2020-01-03 at 17 10 27" src="https://user-images.githubusercontent.com/47557215/71736485-721db680-2e51-11ea-945e-1648dd5dda35.png">

<img width="815" alt="Screenshot 2020-01-03 at 17 10 44" src="https://user-images.githubusercontent.com/47557215/71736500-82359600-2e51-11ea-9810-c9022e591e0a.png">

**Comment by aagonzales** [comment]
This is awesome! I only have one piece of feedback:

The dividers between sections should be a color instead of a cap, like the original toolbar. \
![image](https://user-images.githubusercontent.com/11670886/72098223-a5de5d80-32e3-11ea-980e-2d564fb31717.png)

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-website #1690](https://github.com/carbon-design-system/carbon-website/issues/1690) via [**ZenHub**](https://www.zenhub.com/)
