### ISSUE TITLE
Dropdown: Provide support to disable specific values in the dropdown

### ISSUE THREAD

**Issue by kkomprakash** [carbon-design-system/carbon#4949]
## What package(s) are you using?

- [ ] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

Yes. Dropdown component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expecting a prop that can help us to disable  specific value(s) in the dropdown. It is not there in Dropdown component 
> What browser are you working in?

Chrome, Firefox, Safari

> What version of the Carbon Design System are you using?

v9

**Comment by tomkdgun** [comment]
This feature would be very helpful in IBM project I'm working on.
