### ISSUE TITLE
List box: Desire to match dropdown item height with the one of trigger button

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#4951]
From @vpicone in #4928:

Also wondering if the dropdown options should be the same size as the field. @carbon-design-system/design 

![Screen Shot 2020-01-03 at 3 52 07 PM](https://user-images.githubusercontent.com/4078018/71751573-9ffaff00-2e41-11ea-9f14-eb19e74684cc.png)

**Comment by aagonzales** [comment]
Yes, the menu item height should match the height of the input field, so this image should have 32px menu items.

**Comment by asudoh** [comment]
Merging to: #5070
