### ISSUE TITLE
CodeSnippet's copy button is not positioned correctly

### ISSUE THREAD

**Issue by abvte** [carbon-design-system/carbon#4954]
The CodeSnippet's copy button is not positioned correctly in `single` mode. It looks like the `.bx--copy-btn` class is overriding the `position` style to `relative` rather than the old value of `absolute`.

Using:
Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
`carbon-components@10.9.0`
`carbon-components-react@7.9.0`

Screenshot:
<img width="454" alt="Screen Shot 2020-01-06 at 10 18 55 AM" src="https://user-images.githubusercontent.com/16497214/71829204-1716da00-3072-11ea-85b4-c55e1002f648.png">

It looks like the style is coming from the `CopyButton` component. My import order is:
```
...
@import 'carbon-components/scss/components/code-snippet/code-snippet';
@import 'carbon-components/scss/components/copy-button/copy-button';
...
```

**Comment by abvte** [comment]
Reversing those two imports fixed the issue, so it looks like the copy-button styles should be scoped down further so that it doesn't affect the CodeSnippet copy button or the CodeSnippet styling should have a higher selector specificity to override the CopyButton styling.

**Comment by abbeyhrt** [comment]
Hi @abvte! Thank you for bringing this to our attention, would you be able to provide a code sandbox recreating the problem?

**Comment by abvte** [comment]
Hi @abbeyhrt, I do not. I don't have a code sandbox with a webpack + scss build process on hand. If you arrange the import order like above, you will see the same issue. Styling in the `copy-button` stylesheet is overriding what's in the `code-snippet` stylesheet
