### ISSUE TITLE
[text input]: Disabled text area using the wrong color token

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#4964]
It looks like the disabled text area may be using the wrong color token. It should be using `$disabled-01` so it appears white in this instance.

The current state in the [website](https://www.carbondesignsystem.com/components/text-input/code/) 
![image](https://user-images.githubusercontent.com/19270502/71918254-8d394080-3147-11ea-9032-e5930bd7a132.png)

It should appear white like this

![image](https://user-images.githubusercontent.com/19270502/71918228-75fa5300-3147-11ea-88e6-c8e9d6a9f70e.png)

**Comment by joshjohn99** [comment]
Hey, I added a patch to PAL.  I added the class that need to be changed below: 

`
 .#{$prefix}--text-area:disabled {
  cursor: not-allowed;
  outline: none;
  background-color: $disabled-background-color;    <===
  border-bottom: 1px solid transparent;
}
`
