### ISSUE TITLE
Passing in tabIndex values to Menu Items and Links

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/carbon#4965]
### Summary

We need to be able to pass in tabIndex values to `SideNaveMenuItem` and `SideNavLink` in order to control keyboard traversal order and accessibility. 

This is a request for development and enhancement of existing components.

### Justification

We are working on a multi-layered LeftNav component for use on the IBM Brand Center site. Controlling keyboard traversal and focusability with up to four layers of navigation information is our goal.

### Desired UX and success metrics

Success: being able to control which layers of the LeftNav user can access and traverse at any given time by setting tabIndex.

Failure: forcing users to tab through navigation items on hidden layers when using the keyboard.

### Specific timeline issues / requests

We are looking to incorporate this into a release on 1/31/2020.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by dakahn** [comment]
Can you provide an example of what you're describing here (maybe a spec screen shot?). I'm having difficulty picturing what four layers of navigation look like in a side nav. We talking dropdowns?

**Comment by SilverFox70** [comment]
@dakahn Here is a link to a dual layer nav example: https://ibmbrandpublisher-stage.mybluemix.net/brand/?hash=left-nav-animation-6

The link will time out for you after three minutes of inactivity. Although it only depicts two layers of navigation, I think it will provide a good jumping off point for imagining a third or fourth layer.

Here is another example of a multi-layer nav, just for reference as to what these things look like: https://github.com/omerkhan8/react-multilevel-sidebar/blob/master/example/Sidebar.config.js

**Comment by joshblack** [comment]
Hey there! While going through our proposal process, it seems like we're not going to be moving forward with this addition to the codebase.
