### ISSUE TITLE
[TextInput]: Error icon blocks entity value text

### ISSUE THREAD

**Issue by angella-qian** [carbon-design-system/carbon#4967]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

When a user produces a validation error with an invalid entity value, the error icon blocks the text behind it.

> Is this issue related to a specific component?

The issue is related to the `TextInput` component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect the entity value to cut off with ellipses and/or just generally have some spacing between the text and the error icon.

> What browser are you working in?

Chrome Version 78.0.3904.97 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

"carbon-components": "10.7.4"
"carbon-components-react": "7.7.4"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Assistant

## Steps to reproduce the issue

1.  Open an existing entity
2.  Try to add a new value, but make the text very long to produce error message/icon
3.  Observe that the error icon blocks the text behind it

## Additional information
<img width="955" alt="Screen Shot 2020-01-07 at 1 30 40 PM" src="https://user-images.githubusercontent.com/36805013/71936339-fe83ee00-315d-11ea-8c64-8816cfcbb443.png">

**Comment by emyarod** [comment]
can you create a reduced test case in CodeSandbox? https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

this is how the component currently appears in storybook

![image](https://user-images.githubusercontent.com/8265238/71993901-7e14ca00-31fd-11ea-8385-860536e4fe1d.png)

**Comment by angella-qian** [comment]
@emyarod Nevermind, found that the bug was caused by some additional styling previously added
