### ISSUE TITLE
Header with checkbox in DataTable has a hover state

### ISSUE THREAD

**Issue by IdanAdar** [carbon-design-system/carbon#4971]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
I have a DataTable with selection, and so the headers also contain a checkbox (for select all). This header has a hover state, which IMO is not needed as the header is not clickable, only the checkbox in it.

This issue happens only in Carbon 10 and was not present in prior releases.
Can be demoed by hovering the checkbox header in the story: https://react.carbondesignsystem.com/?path=/story/datatable--with-selection

**Comment by laurenmrice** [comment]
yes this is a bug, it should not be getting a hover change.
