### ISSUE TITLE
Tab/ProgressIndicator items has max-width specified even when space is available

### ISSUE THREAD

**Issue by prince737** [carbon-design-system/carbon#4973]
## What package(s) are you using?
"carbon-components": "10.9.0",
"carbon-components-react": "7.9.0"

through Cloud Pal: 1.40.8

## Detailed description
Tab/ProgressIndicator component has max-width specified for its items, which makes it difficult for the user to know what the entire string is. It is worse in multilingual environments (eg: German). Ideally, it should show the entire title or at least provide a way for the user to view the entire title. Our tabs are two words in total, it makes sense and is reasonable to support this

## Component affected
Tabs, ProgressIndicator

> What did you expect to happen? What happened instead? What would you like to
> Entire tab/progress indicator name to be visible when the width is available

## Additional information

- Screenshots or code
<img width="777" alt="Screenshot 2020-01-08 at 6 26 18 PM" src="https://user-images.githubusercontent.com/31027320/71979719-66acff80-3244-11ea-9151-83e5a141cc1a.png">

![image](https://user-images.githubusercontent.com/31027320/72049666-67e23900-32e5-11ea-9edc-3924f8270e3d.png)

**Comment by emyarod** [comment]
will need design input on what the default tab widths should be, but a temp fix would be to add `width: 100%` to `.bx--tabs__nav-link` (not sure if this is the same selector for v9)

**Comment by prince737** [comment]
Just noticed the same behaviour with ProgressIndicator component. Updated the issue accordingly.

**Comment by aagonzales** [comment]
In the new design language each tab (or section of progress indicator) is an equal width with 16px padding on the left and right. To incorporate more room for text the tabs need to be made wider. 

The progress indicator can be stretched to fill a wider area and that will help give the text more room to display.

**Comment by prince737** [comment]
@aagonzales Got it. But the question is will carbon support wider tabs, or we need to override?

**Comment by aagonzales** [comment]
What if we have the min-width set at 120 but enabled tabs to grow larger as long as each tab in the set have equal widths? I have no clue how to technically achieve this. @emyarod do you have any ideas?

**Comment by alon24** [comment]
I too in appid dashboard suffer from this, we need this to handle our informative tab/progress bar labels.
the idea to have the same length as the longest is fine by me.

We should also remember that in localizations, often text changes length and so this need to be responsive, we cannot account for text size in advance

**Comment by emyarod** [comment]
> What if we have the min-width set at 120 but enabled tabs to grow larger as long as each tab in the set have equal widths? 

@aagonzales this is feasible, but how strongly are we tied to the requirement that all tabs are the same width?

**Comment by alon24** [comment]
why do you realy need all tabs to be the same size? i mean just fit content and size it,.

**Comment by aagonzales** [comment]
@alon24 It is an aesthetic choice made for brand vision. It helps with alignment and layout structure. We want to keep equal width tabs. 

Its not an uncommon pattern. Chrome browser tabs do this (i'm looking at them right now).

**Comment by alon24** [comment]
Any thoughts about when this will be fixed, we can't realy deploy to production like this.

**Comment by henshkedi** [comment]
@aagonzales The case of Chrome and ours is different.
Chrome is about navigating between different sites. So the focus is on one site.
In our case, it is a control of the same screen so the tabs exchange different views for the same object.
I think you want to compare it with a Google product. you should compare it to the results page (different view for the same thing).

using Polsky language emphasize that
![image](https://user-images.githubusercontent.com/15678031/73605833-e1e7a400-45ab-11ea-92d6-d5e911292842.png)

**Comment by aagonzales** [comment]
This was an aesthetic band decision that was made. We'd have to consult to @mjabbink about changing it but the tabs being equal sizes is the original intended design aesthetic. The equal sizing offers alignment on the page and create an equal visual weight among tabs, this is especially important for the container tabs. I think the style of our tabs being left alignment and not centered like the google product example also benefits from the equal tab sizes.

**Comment by aagonzales** [comment]
For now we can do what I proposed in this comment: https://github.com/carbon-design-system/carbon/issues/4973#issuecomment-574359895. And set a min-width but no max width. That is all I'm comfortable with changing at the moment.

**Comment by alon24** [comment]
@aagonzales will this allow me to put texts or varient sizes? meaning if internalization text is bigger it will show ok?
If so please do this, we are waiting

**Comment by aagonzales** [comment]
The size of the tabs should be based off the longest string of text.

**Comment by aagonzales** [comment]
@alon24 You are welcomed to make a PR that fixes this if you are waiting. Otherwise when it gets done is up to our team. Carbon should not be a blocker for you. If you need to build something custom in the mean time then you are welcomed to.
