### ISSUE TITLE
[Modal] - 7.9.0, extra padding is added always to last modal content child.

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#4979]
## After migration 7.7.4 -> 7.9.0, extra padding is added always to last modal content child.

This affects look visual appearance, especially on modals scroll content.
Setting hasScrollingContent to true, doesn't help match. Actually in some cases it prevents clicks on list items (not able to click through bx--modal-content--overflow-indicator).

## What package(s) are you using?

    "carbon-components": "10.9.0",
    "carbon-components-react": "7.9.0",
    "carbon-icons": "7.0.7",

## Detailed description

![image (18)](https://user-images.githubusercontent.com/17591704/72006969-01134000-3251-11ea-9783-7014d18e53e7.png)
![image (19)](https://user-images.githubusercontent.com/17591704/72006970-01abd680-3251-11ea-867f-0b818de9913b.png)

On more complicated modals, padding is added e.g. to aside content (right hand side section)
![image (20)](https://user-images.githubusercontent.com/17591704/72007063-2d2ec100-3251-11ea-830c-9f8a83665a42.png)
When I will wrap everything in one div padding will be always added, and it will be gap between scrolls and buttons section (footer).

**Comment by abbeyhrt** [comment]
Hi @tomkdgun, thank you for making this issue! This has been partially addressed in #5267. The padding to the last child will only be added if `hasScrollingContent` is set as true.  We are still working on a solution to the padding preventing click on the last element.

**Comment by tomkdgun** [comment]
@abbeyhrt Why we need to prevent clicks on last element ?

**Comment by joshblack** [comment]
I believe this should be addressed with `pointer-events: none` specified on the overlay! Going to close this out, feel free to comment and I can re-open if this is an issue in latest 👀
