### ISSUE TITLE
Accordion element is bugged.

### ISSUE THREAD

**Issue by AbrahamMunguia** [carbon-design-system/carbon#498]
## The Accordion/collapsable element has a bug.

First of all, good day.

The reason why I open this issue is due to an error that shows up when you work with the collapsible element. I think the error shows up when the body/content is updated or refreshed but, my console doesn't throw an error, is like if it stopped working suddenly. This error is also visible on the main page of [Carbon.](http://carbondesignsystem.com/)

## Steps to reproduce the issue

>Enter to http://carbondesignsystem.com/

>Open a collapsible box (Either Styles, Components, any works as long as it has nested elements)

>Search for something on the 'Search bar' I noticed that searching for 'Header' gives the best result for the bug replication.

>Click the header highlighted option.

>Now, click the 'X' on the search bar or, manually delete what you write. If you try to open a 'combo box' or 'accordion' you won't be able to open them, some might be bugged but the options inside won't work.

## Additional information
* Chrome
![error_chrome](https://user-images.githubusercontent.com/33528172/34881535-6f84c47e-f779-11e7-83cb-a7abb32ce07a.gif)
* Mozilla
![error](https://user-images.githubusercontent.com/33528172/34881556-7f704a48-f779-11e7-90f2-6d528626fc90.gif)

## Add labels
[bug ]

**Comment by tw15egan** [comment]
cc @marijohannessen

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/design-system-website #128](https://github.com/carbon-design-system/design-system-website/issues/128) via [**ZenHub**](https://www.zenhub.com/)
