### ISSUE TITLE
Tooltip: Misaligned if tooltip is in extreme right of the screen.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon#4987]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I am using <Tooltip> component and its by default center aligned. As in below screen grab when tooltip is on the right edge of the screen the tooltip notch is misaligned and doesn't stay below the tooltip icon.
Expected behavior is the tooltip notch should automatically change the alignment to end/center/start based on its position on the screen .

![image](https://user-images.githubusercontent.com/22093326/72040891-fe0b6480-32cf-11ea-85f8-6b588cbe32df.png)

**Comment by emyarod** [comment]
can you provide a reduced test case in [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) showing this issue?

**Comment by kalyanixraut** [comment]
Below codesandbox shows the tooltip text overflowing. I am expecting the tooltip to align itself in this case without overflowing.
https://codesandbox.io/s/sharp-dust-5vfh1
I will try replicating the notch alignment issue as well and share the details.

**Comment by emyarod** [comment]
the tooltip will not change direction based on its position in the screen, but you can use the `direction` prop in your application

**Comment by emyarod** [comment]
closing in favor of #4252, #4388 also related

**Comment by kalyanixraut** [comment]
@emyarod, I have gone through the issues that you have mentioned, but couldn't find the fix for this issue. I have already tried with **direction** prop, the issue exists with that as well. 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/22093326/72583372-20befe00-390c-11ea-99b2-3564508aab98.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/22093326/72583389-2b799300-390c-11ea-9158-289482793664.png">
