### ISSUE TITLE
Sketch Library: IBM Icons (16px, 20px) showing wrong icon asset for 'filter'

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#4990]
![image](https://user-images.githubusercontent.com/35537391/72090460-200ae400-32dc-11ea-85f8-90c507143d23.png)

![image](https://user-images.githubusercontent.com/35537391/72090174-7f1c2900-32db-11ea-902d-751ed4bfa7d0.png)

`packages/icons/svg/16/filter.svg` was moved to `packages/icons/svg/16/settings--adjust.svg`.

There is no `packages/icons/svg/16/filter.svg` anymore.

**Comment by chrisconnors-ibm** [comment]
related: https://github.com/carbon-design-system/carbon/issues/4130
https://github.com/carbon-design-system/carbon/issues/4849

**Comment by chrisconnors-ibm** [comment]
keepalive_bot this is still an issue: 
![image](https://user-images.githubusercontent.com/35537391/74564884-0b0a1c00-4f3e-11ea-8d1b-aa93641bcd92.png)

**Comment by lukefirth** [comment]
Hey, is there any update as to where this falls on the roadmap/pipeline? 

Its been plaguing us over in IoT where we've got a lot of filtering going on, and this issue is 2 months old without an assignee or estimated fix date, which makes me a little skittish 😄

**Comment by chrisconnors-ibm** [comment]
it was dependent on other under the hood work in elements which just shipped - maybe @joshblack can update.

**Comment by joshblack** [comment]
@chrisconnors-ibm one thing we should call out is that the library can be updated, it's just a manual process without the tooling in place.

Currently, I'm taking a look at our Sketch plugin again. Unfortunately, it seems like the rendering logic being used for the SVGs is rendering assets incorrectly. I will try and see how to resolve but in the meantime we can always hand update the design kit if there is anything pressing.

**Comment by laurenmrice** [comment]
fixed 🎉! will be in next update of the sketch icon libraries

**Comment by chrisconnors-ibm** [comment]
reopening because no one has updated the libraries, this is still asked about frequently
https://ibm-watsonhealth.slack.com/archives/C0M053VPT/p1604613965233300

**Comment by sstrubberg** [comment]
hey @chrisconnors-ibm, we updated this in our Sketch kits. Let me know if it's still a thing.

**Comment by chrisconnors-ibm** [comment]
> hey @chrisconnors-ibm, we updated this in our Sketch kits. Let me know if it's still a thing.

@sstrubberg I don't even have a Sketch License anymore to check! 🤣
