### ISSUE TITLE
TextArea react component not inheriting the width from it's container

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon#4994]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Text area is not inherting it's parent's width which is the set through className props on the component.  
![Screen Shot 2020-01-09 at 3 24 47 PM](https://user-images.githubusercontent.com/17915105/72106131-653b1000-32f4-11ea-873f-def48047827a.png)

It used to on v9 
![Screen Shot 2020-01-09 at 3 25 05 PM](https://user-images.githubusercontent.com/17915105/72106138-68ce9700-32f4-11ea-8e98-bf678ae992c0.png)

> Is this issue related to a specific component?
TextArea

> What did you expect to happen? What happened instead? What would you like to
> see changed?
can control the width

> What browser are you working in?
Chrome Version 79.0.3945.88 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
carbon-components-react: 7.9.0
carbon-components: 10.9.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/dawn-snow-2zc94
## Additional information

- Screenshots or code
- Notes

**Comment by jendowns** [comment]
I can help with this one 👍 
Just opened a small PR here: https://github.com/carbon-design-system/carbon/pull/4995
