### ISSUE TITLE
NumberInput: Initial value cannot be empty string due to PropTypes

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#4996]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

PropTypes for both value and defaultValue are set to Number so you cannot have it's initial value as an empty string despite the allowEmpty property. The following is logged to the console:

`Warning: Failed prop type: Invalid prop `value` of type `string` supplied to 'NumberInput', expected 'number'.`

## Additional information

https://codesandbox.io/s/pensive-dhawan-wh9vs

**Comment by jendowns** [comment]
~Proposed a fix for this here: #5004~

UPDATE: Going to defer to @abbeyhrt instead 👍
