### ISSUE TITLE
Make watch mode default for Carbon bundle

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#500]
“How to instantiate components on DOM elements that are dynamically created?” is the top (and far more than 2nd) question for Carbon vanilla. To address that, I’d like to propose making [“watch mode”](https://github.com/carbon-design-system/carbon-components/pull/213) the default option for Carbon bundle (carbon-components.js). Given it has slight performance impact, we should provide a way to turn it off - I’d propose doing it by `CarbonComponents.settings.disableAutoInit` option.

Given those are breaking changes, I’d like to do it in next major release.

**Comment by marijohannessen** [comment]
@asudoh any update here?

**Comment by asudoh** [comment]
Hi @marijohannessen think you for pinging - Considered it for V9, but didn’t make it - So something to consider for V10.

**Comment by asudoh** [comment]
Better documentation around component instantiation API seems to have caused much less questions in this area - Closing this for now. We can re-open if we get more questions here.
