### ISSUE TITLE
Carbon 10 Grid should support item with various height (Pinterest style)

### ISSUE THREAD

**Issue by jz2cao** [carbon-design-system/carbon#5008]
Carbon 10 Grid currently not able to do the following layout

![image](https://user-images.githubusercontent.com/15077843/72171541-2d3dd680-33a1-11ea-8872-db33c512d785.png)

**Comment by dakahn** [comment]
Interesting problem! Have you thought about flexbox here? something like this maybe?
https://codepen.io/estherj-hsu/pen/bVXOMY

**Comment by joshblack** [comment]
Hi @jz2cao! 👋 Most likely this won't be something that we can ship out of the box as it will require some JS or decision making by the product team for how to leverage flexbox or other techniques to achieve it. The grid itself will help with vertical alignment on the columns but unfortunately how things get arranged in rows will be left up to the product team for now.
