### ISSUE TITLE
Tag component doesn't look like a tag when there is only one character

### ISSUE THREAD

**Issue by ashpc** [carbon-design-system/carbon#5009]
## What package(s) are you using?

- [ ] `carbon-components`  10.9.0
- [ ] `carbon-components-react` 7.9.0

## Detailed description

> Describe in detail the issue you're having.
We are using Tag component to show the count of roles a user can have and when it's in single-digit the component looks like a ball instead of tag. There should a min width provided to make it look like a tag.

> Is this issue related to a specific component?
Tag

> What did you expect to happen? What happened instead? What would you like to see changed?
We are using Tag component to show the count of roles a user can have and when it's in single-digit the component looks like a ball instead of tag.

> What browser are you working in?
FF
Chrome
Safari

> What version of the Carbon Design System are you using?

- carbon-components 10.9.0
- carbon-components-react 7.9.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud

## Steps to reproduce the issue

1. Use a single character in a tag component and see the issue

![Screen Shot 2020-01-10 at 11 12 59 AM](https://user-images.githubusercontent.com/1907155/72172106-f1534300-3399-11ea-9967-4824f0cb6236.png)
![Screen Shot 2020-01-10 at 11 13 03 AM](https://user-images.githubusercontent.com/1907155/72172107-f1534300-3399-11ea-9d3d-452b1cfd1adf.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design we could add a `min-width` property to ensure single character tags still maintain a pill shape

**Comment by aagonzales** [comment]
I did talk to the design team and we do like the pill shape better for a single digital but I think technically if we set a `min-width` on tag, say 32px, then the text will be off centered, which is not ideal.
![image](https://user-images.githubusercontent.com/11670886/72381101-6301f880-36dc-11ea-8217-d5d031710a4e.png)

**Comment by tw15egan** [comment]
@aagonzales It seems like we can center the single-digit without it affecting the other variations

https://codesandbox.io/s/codesandbox-x5etc

<img width="220" alt="Screen Shot 2020-01-14 at 2 51 58 PM" src="https://user-images.githubusercontent.com/11928039/72389536-72357600-36dd-11ea-97e5-de3faddf7446.png">

**Comment by aagonzales** [comment]
Oh noice! You're a genius TJ.

**Comment by tw15egan** [comment]
If this is okay, I'll go ahead and make a PR 👍

**Comment by aagonzales** [comment]
Yup, approved ✅
