### ISSUE TITLE
Animated dropdown causes scrollbar to temporarily appear

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#502]
## Animated dropdown causes scrollbar to temporarily appear

When expanding the dropdown to select an item, the css causes it to animate open by quickly increasing it's height. The problem is that the smaller height adds a scrollbar until it's at full height. If the expanded height then doesn't need a scrollbar it then disappears on animation complete. This looks a little weird.

Reproducable via the samples:
http://carbondesignsystem.com/components/dropdown/code

**Comment by tw15egan** [comment]
Hm, I'm not seeing it. Are you on Windows machine or a Mac? If you are on a Mac, what setting do you have set here (Settings --> General): 

![screen shot 2018-01-15 at 11 27 20 am](https://user-images.githubusercontent.com/11928039/34954715-1c8c8ffc-f9e7-11e7-84ec-f11ab6c60811.png)

**Comment by richardpilot** [comment]
Window 10
Chrome -  63.0.3239.132

**Comment by richardpilot** [comment]
![dropdown](https://user-images.githubusercontent.com/13081745/34956098-8348e794-fa1f-11e7-9f2d-d92a5e74e42a.gif)

Captured on my home laptop. On my work laptop, which is slightly slower, the effect is more pronounced.
