### ISSUE TITLE
Grey 10 theme ghost buttons have the wrong icon color

### ISSUE THREAD

**Issue by yumeforever** [carbon-design-system/carbon#5029]
## Detailed description

Hello guys, `Grey 10` text and icon `01 enabled` `Ghost buttons` have the wrong icon color:

![image](https://user-images.githubusercontent.com/3612533/72353380-4c5f9f80-36e4-11ea-98e8-4cf8accd225a.png)

#### Names
1. button / 04 ghost / default / 02 text and icon / 01 enabled
2. button / 04 ghost / medium / 02 text and icon / 01 enabled
3. button / 04 ghost / small / 02 text and icon / 01 enabled

**Comment by aagonzales** [comment]
@yumeforever Is this in the Sketch library or in code?

**Comment by yumeforever** [comment]
This is `Sketch library` – Sorry forgot to mentoned that :)

**Comment by yumeforever** [comment]
A general question about bugs on the Sketch library:
Is there a way I could make a "push request"? – This for example is something easy to fix, I feel bad to ask someone to just correct correct if I can help already by PR a fix.

**Comment by aagonzales** [comment]
Unfortunately, no there's no way to push to the kit. Hopefully, one day we'll have Abstract or something like it. I'd really like for this to be possible.

**Comment by laurenmrice** [comment]
The master kits do not have this color change for ghost button so this is most likely a sketch problem.

With the next kit update we enabled the icon color for button in the overrides panel, so you can change back the color :)

**Comment by yumeforever** [comment]
Thank you!! I just noticed this was implemented ♥️ thanks!
