### ISSUE TITLE
Why does the checkbox component has a top: -2px rule?

### ISSUE THREAD

**Issue by IdanAdar** [carbon-design-system/carbon#503]
## Detailed description

We have noticed that with version 5.5 of carbon components that the checkbox components has the rule `top: -2px`.

In our service, this caused the checkbox to appear misaligned in a table row:

![screen shot 2018-01-16 at 10 14 28](https://user-images.githubusercontent.com/7255583/34978191-13476a56-faa6-11e7-8946-f1fa150a0718.png)

> Is this issue related to a specific component? 

Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?

For the checkbox to appear horizontally aligned/centered. 

> What browser are you working in? 

Chrome stable (latest)

> What version of the Carbon Design System are you using? 

8.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Certificate Manager

## Steps to reproduce the issue

1. In stage1, visit the catalog and create a new instance of the "Certificate Manager" service
2. Save the attached .gif file and rename its extension to **.pem** (![valid](https://user-images.githubusercontent.com/7255583/34978292-6e6355e4-faa6-11e7-9eaf-bffe81a46f45.gif))
3. From the service UI, import the file to populate the certificates table.
4. Expend the certificate row and inspect the checkbox component
5. In the Chrome DevTools, tick off the `margin-top: -0.4rem` line in **.bx--checkbox-label**

**Comment by asudoh** [comment]
@IdanAdar Does this sound the same? https://github.com/carbon-design-system/carbon-components-react/issues/470

**Comment by IdanAdar** [comment]
On the surface it sounds similar. The fix is different than ours so I don't know if the end result will be the same. Once the fix is public we can verify and either close or keep this issue open.
