### ISSUE TITLE
Left Nav Bar: more than 2 levels of navigation.

### ISSUE THREAD

**Issue by bkribbs15** [carbon-design-system/carbon#5031]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

I guess you can call it a mix of design and development.  Mainly just looking for more than the two levels of navigation in the left side bar. 

<img width="257" alt="Screen Shot 2020-01-14 at 9 48 50 AM" src="https://user-images.githubusercontent.com/4122319/72359027-266dd700-36b3-11ea-8efb-869da825c196.png">

It would be great to have sub-levels to a topic such as the containers one in the picture above. 

### Justification

This would make it easier to easily navigate larger pages and quickly jump to certain parts of a page or it may just be necessary with the amount of information provided.  

### Desired UX and success metrics

For example, from the picture above we have a concepts section and within that we cover containers and within containers there may be multiple kinds of containers that have their own pages (docker, code-ready, etc.) Instead of having one larger page covering them all, we may want each to have their own independent pages.

### "Must have" functionality

Not a must have, just a beneficial feature for myself and others in the future.

### Specific timeline issues / requests

No, timeline required.

### Available extra resources

I can help modify the javascript if needed. Just want to make sure I do it properly within the standards the team is using.

**Comment by dakahn** [comment]
> This would make it easier to easily navigate larger pages and quickly jump to certain parts of a page or it may just be necessary with the amount of information provided.

Are you thinking that like each heading in an article would need it's own distinct list item in the drop down? 
![](https://user-images.githubusercontent.com/4122319/72359027-266dd700-36b3-11ea-8efb-869da825c196.png)
Like each example ^ there is the title of a page. Then each subsection (with a heading) would have _another drop down menu_. Is this only for the case of longer articles?

In any case this problem could be solved more elegantly with some top level _in page_ navigation I'd think. 

[Here's an example of what i'm tallking about](https://www.gov.uk/blind-persons-allowance)

[Wikipedia also famously uses this design technique](https://en.wikipedia.org/wiki/Tree) to distill articles of great complexity to a easily navigable table of contents

**Comment by bkribbs15** [comment]
@dakahn Not quite, I know I used that as a small example, but more of pages under that category.  

Here's an example of nav-items.yaml that I am thinking of.

<img width="546" alt="Screen Shot 2020-01-14 at 11 40 32 AM" src="https://user-images.githubusercontent.com/4122319/72367945-b8c9a700-36c2-11ea-9f4b-844c3d2cbcfb.png">

Here is an example of the site itself. I want to be able to have the `kubernetes` section under the `concepts` section.

<img width="257" alt="Screen Shot 2020-01-14 at 11 43 18 AM" src="https://user-images.githubusercontent.com/4122319/72368202-34c3ef00-36c3-11ea-82e7-1e8518f5c949.png">

Each item in the `kubernetes` section is a different page.

**Comment by bkribbs15** [comment]
This may already be possible, but I have tried playing with the nav-items.yaml and it keeps erroring out when I try the example above.

**Comment by asudoh** [comment]
Refs: https://github.com/carbon-design-system/carbon/issues/4871#issuecomment-574304920

**Comment by dakahn** [comment]
@bkribbs15 if further more granular navigation is needed tabs or a list should be utilized in the page itself.
https://www.carbondesignsystem.com/components/UI-shell-left-panel/usage/#behavior
