### ISSUE TITLE
Rendering many OverFlowMenu's causes pages to lock up.

### ISSUE THREAD

**Issue by ritch** [carbon-design-system/carbon#5044]
### Summary

Rendering a `DataTable` with many (~500) `<OverflowMenu />`s causes page lock ups and other performance degradation. Eg. clicking on an input and typing can be laggy / slow.

The enhancement requested is to look at this use case and try and improve the stability and performance or overhead of using an `<OverflowMenu />`.

### Justification

Performance of all `DataTable`s with overflow menus will be impacted by this.

### Desired UX and success metrics

I think we should be able to render very large DataTables with overflow menus (~500 items) rows and not see page lock up issues or responsiveness issues.

**Comment by ritch** [comment]
I think this is a good place to start looking:

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/internal/ClickListener.js#L31

We create a `<ClickListener />` with a unique `document.addEventListener` for each `<OverflowMenu />`.

Perhaps we can try a singleton listener which can notify each instance of `ClickListener` instead of a unique listener per instance, which ultimate does the same exact thing.

**Comment by asudoh** [comment]
Hi 👋 we recommend data table used with pagination component, instead of putting every table row as active DOM elements. Doing so eliminates general performance concerns of having too many DOM elements. Event delegation may be worth considering and happy to accept PRs if it can be done as a simple fix, but I suggest that pagination is considered first.

**Comment by ritch** [comment]
Good point, but we already have pagination. Right now we allow for page sizes of up to 500 items though.

And we'd like to push that page size higher in the future.

**Comment by ritch** [comment]
I think this is more of a fundamental issue with the `ClickListener` approach.

In the react tools profiler I can see every `<OverflowMenu />` triggering an update (not sure if its just props or causing a render()) when clicking on other content in the table.

Since all of these menus are closed I don't see why any updates would be required.

I have a video of this that I can share on IBM slack - ping @ martori.

**Comment by ritch** [comment]
Here is a screenshot showing the react tools "Highlight updates when components render."

The yellow border boxes mean many updates have been made.

All I've done to cause this is click the rest of the table a few times.

<img width="553" alt="Screen Shot 2020-01-14 at 5 05 20 PM" src="https://user-images.githubusercontent.com/462228/72396086-6d2df200-36f0-11ea-875c-c3436eb0f616.png">

**Comment by abbeyhrt** [comment]
This has been addressed by #5336!
