### ISSUE TITLE
Forward refs for TableHeader <th> in case of sorting<th>  and moving property (...rest) from button to <th> for appling all rest properties on <th>

### ISSUE THREAD

**Issue by sunilkotiyaibm** [carbon-design-system/carbon#5047]
### Summary

In developing column resizing for the data table for Watson IoT PAL, we're unable to set width on <th> elements. This is handled in #4876 few days back, but in this case <ref> is also need to applied on sorting <th>. Also we are moving the property (...rest) from <button> to <th> for applying all rest properties on <th> during resizing, currently it is applying on button.   
Project: react
Component: datatable

TableHeader is a function component so we're unable to use the ref attribute on it. We're unable to wrap these with a container without breaking table semantics, and the styling for table headers as well.

### Justification

Multiple Watson IoT products require the use of resizable columns.

### Specific timeline issues / requests

This work is in progress already. I'd like to get this in ASAP to avoid re-implementing TableHeader ourselves.

### Available extra resources

I can submit a PR

**Comment by joshblack** [comment]
I believe this should be addressed in https://github.com/carbon-design-system/carbon/pull/5204 !

Going to close this out, let me know if this is still an issue 😄
