### ISSUE TITLE
Support DataTable (sticky header) with truncated cell text

### ISSUE THREAD

**Issue by gmoehler** [carbon-design-system/carbon#5048]
### Summary

The current implementation of the `DataTable` will expand its cells when a long text is displayed. Since there are cases in which we cannot control the cell content we need a way to display arbitrarily long cell text.
One possible solution is to truncate the cell text using an ellipsis. The full content is shown in a tooltip when hovered over the abbreviated cell text.

### Justification

We (IBM Cloud SQL Query) need to switch from ap-components to the Carbon `DataTable`component. Since we show arbitrary data from the Cloud Object store the table cell content can be far too large for a cell.

We need to use the `DataTable` component with a **sticky header flag** and expanded to full width and height

### Desired UX and success metrics

When a long text is provided for a table cell, the text is abbreviated and shown with an ellipsis. On mouse hover a tooltip is shown with the full (or at least expanded) content. 
The tooltip should be visible in all cases. E.g. it cannot be to the bottom of the last currently displayed row.

### "Must have" functionality

- Long cell content does not "explode" the table
- A user has a simple way (e.g. tooltip) to see the full (or at least much more of the) content

### Specific timeline issues / requests

We need to replace our ap-component table iwith `DataTable` in the weeks to come.

### Available extra resources

A first solution is available at https://codesandbox.io/s/datatable-sticky-6-ref-u8j4s

**Comment by dakahn** [comment]
Arbitrarily long cell text (especially as table heads) should be avoided if at all possible. That said when it's absolutely unavoidable the design intent is to have the header wrap to two lines -- and then if two lines isn't adequate the cell should begin to scroll. Cells in the table body should scroll and never wrap. 

That said obviously our current implementation needs a little work getting it in line with design's spec and while we're not pursuing this particular proposal improvements are planned to handle the use case you describe.

A ticket has been opened for this bug fix. You can follow it's progress [here](https://github.com/carbon-design-system/carbon/issues/5131)

**Comment by dakahn** [comment]
Reopening as per the discussion in #5131 

Now for an _alternative truncation pattern_ rather than an update to default

**Comment by dakahn** [comment]
No longer pursuing.
