### ISSUE TITLE
New Data Table Bug

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#505]
For some reason tables are showing up with a double checkmark in [CodePen](https://codepen.io/taitke20/pen/vpVEKP)

<img width="1393" alt="screen shot 2018-01-16 at 2 30 17 pm" src="https://user-images.githubusercontent.com/29312997/35012301-ff135c4c-face-11e7-80dd-26fa2b78392b.png">

**Comment by marijohannessen** [comment]
Fixed! 👍

**Comment by tay-aitken** [comment]
woo! thanks @marijohannessen 🎉
