### ISSUE TITLE
ToggleSmall not "taking" correct amount of space

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#5064]
Using carbon-components-react latest version I see that the ToggleSmall component is taking too much space. also the on/off text is overflowing.
The toggle should grow and shrink based on the actual width of the component (because of translations )
(as seen in this codesandbox)
https://codesandbox.io/s/distracted-meadow-31quy?fontsize=14&hidenavigation=1&theme=dark

Speaking to @asudoh  it seems that:
1. this solves the overflow issue: 
```
.bx--toggle-input--small + .bx--toggle-input__label {
  .bx--toggle__switch {
    display: inline-flex;
    align-items: center;
    width: auto;
  }
  .bx--toggle__text--on,
  .bx--toggle__text--off {
    position: relative;
    top: auto;
    -webkit-transform: none;
    transform: none;
  }
}
.bx--toggle-input--small:not(:checked) + .bx--toggle-input__label {
  .bx--toggle__text--on {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    border: 0;
    visibility: visible;
    white-space: nowrap;
  }
}
.bx--toggle-input--small:checked + .bx--toggle-input__label {
  .bx--toggle__text--off {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    border: 0;
    visibility: visible;
    white-space: nowrap;
  }
}
```

2. Still the bx--form-item is grabbing too much space so adding this fixes it:
```
 .bx--form-item {
    flex: 0;
   }
```

**Comment by asudoh** [comment]
Note: I believe `.bx--form-item` is working as designed and applications needs to override it by themselves. But I agree that the label going outside the box of small toggle's container is undesirable.

**Comment by tw15egan** [comment]
This should be resolved via https://github.com/carbon-design-system/carbon/pull/5393
