### ISSUE TITLE
Tabs story fails to load when we use it from a remote build

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#5067]
## Description
We've included the Carbon components react stories in our storybook to help unify our components and the Carbon components into one view, but some of the story scss files are missing in our builds
The Tabs.story file is failing to load due to a require for a non-existent file Tabs-story.scss

ERROR in ./node_modules/carbon-components-react/lib/components/Tabs/Tabs-story.js
Module not found: Error: Can't resolve './Tabs-story.scss' in '/Users/scottsd/Documents/GitHub/carbon-addons-iot-react/node_modules/carbon-components-react/lib/components/Tabs'
 @ ./node_modules/carbon-components-react/lib/components/Tabs/Tabs-story.js 15:0-28
 @ ./src/components/Tabs/Tabs.story.jsx
 @ ./src/components sync \.story\.jsx$

The combobox story also fails to load because it has a hardcoded dependency on react docgenInfo existing on the ComboBox component
ControlledComboBoxApp.__docgenInfo = _objectSpread({}, _ComboBox.default.__docgenInfo, {
  props: _objectSpread({}, _ComboBox.default.__docgenInfo.props)
});
(0, _react2.s

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?
Carbon react 7.9.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

**Comment by abbeyhrt** [comment]
@scottdickerson Hi 👋 Thanks for taking the time to make this issue! Consuming our stories is not something we support and they also might not be exported in future bundles of react. Since there has been demand for this, we are tracking this enhancement in this issue (#2570) and may tackle it in the future! Let us know if you'd like to help out!
