### ISSUE TITLE
[dropdown] size variants need to have same size drawer items

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5070]
The three different size variants should have the same size drawer items as they do for the top input field. 

Also XL size isnt working in react.

-------------------------------------------------------------------------------------------------
Spec:
![Screen Shot 2020-01-16 at 10 56 24 AM](https://user-images.githubusercontent.com/43969356/72545664-fa875880-384e-11ea-9fb6-7aa0352e36bd.png)

**Comment by asudoh** [comment]
Thank you for entering @laurenmrice - The XL size (of the trigger button) was fixed in #4928.
