### ISSUE TITLE
Multiselect inline icon error

### ISSUE THREAD

**Issue by andysherman2121** [carbon-design-system/carbon#5073]
The inline multi select component has an error when you have an invalid selection. The error icon is misaligned

## What package(s) are you using?

- [ ] `carbon-components-react`

## Detailed description

> Is this issue related to a specific component? Yes the multiselect component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in? Chrome

## Steps to reproduce the issue

1. Step one
Select the inline version of the multiselect
2. Step two
Check the invalid selection box

- Screenshots or code
![Screen Shot 2020-01-16 at 2 40 53 PM](https://user-images.githubusercontent.com/56688604/72557497-dd628200-386e-11ea-88b7-c0eb7cc9a230.png)

**Comment by andysherman2121** [comment]
@tw15egan Is this targeted for a specific release of Carbon Components?

**Comment by tw15egan** [comment]
It will be included in the next release, not sure if we have a date locked down.

cc @joshblack

**Comment by andysherman2121** [comment]
Great thanks for the update
