### ISSUE TITLE
Create over 300 Tooltip or OverflowMenu, page is not responsive

### ISSUE THREAD

**Issue by unidevel** [carbon-design-system/carbon#5079]
After I created a DataTable with some cell using Tooltip(in canbon9) and OverflowMenu, after the total widget count is over 300(e.g. 30 rows with 10 cols ), the page is not very responsive, each time I click, I need to wait about 2-3 seconds.

The root cause is that Tooltip and OverflowMenu are using `ClickListener` which registers the click event for each widget.

I suggest that only use ClickListener after the menu or tooltip is opened or use react's own event handling to avoid this issue.

Related code => 

OverflowMenu
https://github.com/carbon-design-system/carbon/blob/5513126a1f63a4acd757c3a82a0a6dd98ea386a3/packages/react/src/components/OverflowMenu/OverflowMenu.js#L548

Tooltip
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tooltip/Tooltip.js#L433

ClickListener
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/internal/ClickListener.js#L31

**Comment by unidevel** [comment]
FYI, here is a temporary solution I'm using to fix for carbon 9.x without modifying carbon code 
```
import React from 'react';
import { Tooltip } from 'carbon-components-react';
import debounce from 'lodash.debounce';

export default class TooltipFix extends Tooltip {
  render() {
    const { open } = this.state;
    const node = super.render();
    if (open) {
      return node;
    }
    const clickListener = node.props.children[0];
    const floatMenu = node.props.children[1];
    const content = React.cloneElement(clickListener.props.children);
    return (
      <>
        {content}
        {floatMenu}
      </>
    );
  }
}
```

```
import React from 'react';
import { OverflowMenu } from 'carbon-components-react';

export default class OverflowMenuFix extends OverflowMenu {
  render() {
    const { open } = this.state;
    const node = super.render();
    if (open) {
      return node;
    }
    const content = React.cloneElement(node.props.children);
    return <>{content}</>;
  }
}
```

**Comment by asudoh** [comment]
Looks a non-major use case given we recommend pagination with much smaller number of rows per page, but agreed that there may be some room to better optimize our code.

**Comment by vpicone** [comment]
We'd like to add an overflow menu to each icon, for the icon library page. https://github.com/carbon-design-system/carbon-website/issues/766#issuecomment-583545372 

However, when a even few hundred of these components exist on the page, the page crashes with the following error: 

```
TypeError
target.matches is not a function
```

A component shouldn't cause the page to crash whether there's 1 or 10,000.

Reproduction: https://codesandbox.io/s/quizzical-wiles-jrssh
