### ISSUE TITLE
Update dependency on Node.js to 9.x

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#508]
Currently, the project is working off of Node 6.x. This issue is to update references of Node 6.x to Node 9.x 😄

**Comment by asudoh** [comment]
IIUC most consumers of Carbon would stick to LTS - So 8.x?

**Comment by eddiemonge** [comment]
Why? Node 9 is unstable version. It should be to update to Node 8 which is lts

**Comment by joshblack** [comment]
@eddiemonge down for either version 😄  Right now the project is using v6 so just reached for the new version.

In terms of LTS vs non-LTS versions, since we're using it for development I think we should be okay using whichever version we feel comfortable with since it's being used at build/publish time. Sound reasonable?

**Comment by joshblack** [comment]
Should also clarify this suggestion is for setting `devEngines` versus `engines`!
