### ISSUE TITLE
Publish the storybook addon carbon-addon-theme as a package for use by other frameworks and projects

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#5087]
### Summary

The current source base has added a storybook addon to allow the theme to be manipulated in a storybook. This is really nice and would be great if it were published as a package and usable in other projects and frameworks.

This is a development activity

### Justification

It will allow other storybook users be they projects or framework implementations to work test their themes with their storybook prototypes.

### Desired UX and success metrics

As per current nightly React components storybook be able to make use 
![Screenshot 2020-01-17 at 19 28 15](https://user-images.githubusercontent.com/15086604/72640330-90aaa400-395f-11ea-9630-56fa965f6d88.png)

https://carbon-components-react.netlify.com/?path=/story/search--default

1. The ability to install the packge from npm
2. The ability to use the package in a React project other than the core component library.
3. The ability to use the package in Vue, Angular or other framework.

### Available extra resources

What resources do you have to assist this effort?

Will add and test in Vue component projects.

**Comment by asudoh** [comment]
I agree that it'll be a nice addition. Not sure if the team wants to maintain such Storybook add-on in this core repo, but if it can be maintained in another Carbon repo it sounds super.

**Comment by dcwarwick** [comment]
I've looked through the addon, and it's well structured and I think can be used exactly as is by other projects. So all that would be needed would be to split the files out from the react package into their own package to publish. This might also help with developing the theme panels further as there are people who might be able to help (eg me). I'll draw up a PR for review.

**Comment by joshblack** [comment]
Going to close this out as I believe this is now covered by Storybook directly through `globalTypes`!
