### ISSUE TITLE
Modal dialog not working on IE 11

### ISSUE THREAD

**Issue by kwchan22** [carbon-design-system/carbon#509]
Create Modal dialog programmatically not working

## Detailed description

const modal = new Modal(this.mainDiv.nativeElement, { attribInitTarget: 'modal-' + this.id, eventAfterHidden: 'modal-hidden-' + this.id });
modal.show(); // Throws Object not supported on IE

The same code works on Chrome and Firefox but not on IE 11.

> Is this issue related to a specific component? 
Modal

> What did you expect to happen? What happened instead? What would you like to see changed?
Expect to open the modal dialog.

Instead I got this error on IE 11:
Error details:
TypeError: Object doesn't support this action
at changeState (http://192.168.4.3:3001/common.chunk.js:9795:9)
at show (http://192.168.4.3:3001/common.chunk.js:9682:9)
...

> What browser are you working in? 
IE 11

> What version of the Carbon Design System are you using? 
8.6.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Watson Business Solutions Expert Assist. Shipping soon.

## Steps to reproduce the issue
const modal = new Modal(this.mainDiv.nativeElement, { attribInitTarget: 'modal-' + this.id, eventAfterHidden: 'modal-hidden-' + this.id });
modal.show(); // Throws Object not supported on IE

**Comment by asudoh** [comment]
@kwchan22 Tries our latest code, but couldn't reproduce it at our end. "Polyfills for older browsers" section in [our developer guide](http://carbondesignsystem.com/getting-started/developers) may help. Otherwise, it'd be nice you can put your app to somewhere we can access to. Thanks!

**Comment by kwchan22** [comment]
I was missing the Polyfills. Thanks!
