### ISSUE TITLE
Datatable with StickyHeader: Row data in the table gets misaligned with scroll bar.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon#5101]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I am able to reproduce the issue in the story book.
Go to https://carbon-components-react.netlify.com/?path=/story/datatable--default and click on Knobs tab at the bottom or at the right, and check off Sticky header (experimental) knob. I find the row data shifts to the left because of the scroll in the tbody and hence looks misaligned. 
This issue is linked to the System settings for scroll property which makes it to behave like that. I have recorded the below video to show it. This demonstrates that if scroll bar is set to be shown always the misalignment happens whereas as if its set to When scrolling then its different.

![stickyheaders](https://user-images.githubusercontent.com/22093326/72729373-078caa80-3bb5-11ea-8480-eefbf956518a.gif)

**Comment by asudoh** [comment]
Issue against an experimental feature, and may require deep analysis of the problem. Thank you for reporting BTW!

**Comment by tw15egan** [comment]
Seems to be resolved on the latest version, please feel free to reopen if that is not the case! 👍
