### ISSUE TITLE
[Tabs]: React component has commented out & unused prop `hidden`

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#5105]
## Detailed description

The `Tabs` component has a prop called `hidden` that appears to be (accidentally?) commented out due to missing `*/` closing line:

https://github.com/carbon-design-system/carbon/blob/6f2c7214039c8eae76be0137bd2f8ae19817e791/packages/react/src/components/Tabs/Tabs.js#L37-L40

At the same time, it appears as though this prop is not used anywhere in the component. 

Questions --

* Is this a deprecated prop, and should it be removed completely?
* Or should it be commented back *in* for now? (This seems invalid syntax in general so it may be a good idea to add the closing tag, if you don't want to remove the prop completely.)

**Comment by abbeyhrt** [comment]
@joshblack any thoughts?

**Comment by asudoh** [comment]
`hidden` seems to go to [the top-level `<div>`](https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/react/src/components/Tabs/Tabs.js#L264). Wrt `PropTypes` thing, I guess it was an error in merge.

**Comment by jendowns** [comment]
Thank you! I just opened a small PR to fix this: #5120
