### ISSUE TITLE
a11y: Dropdown uses link rather than button as part of it's template

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#512]
We've just moved to using Carbon for our UI and this was picked up by our accessibility tests that look for links where they shouldn't be.

Confirmed by the example, each option for the dropdown uses a link rather than a button
http://carbondesignsystem.com/components/dropdown/code

Given it's best practice to only use link as navigational elements rather than functional / form elements, can this be changed to be a button (we have now done so for our templates)

**Comment by tw15egan** [comment]
I'll let the @carbon-design-system/design part of the team weigh in regarding the UX, but I believe the `dropdown` _is_ supposed to be used for navigation, while the `select` component is the traditional form element. 

We can update on our end if a `button` would be more suitable, but if anyone is currently using this component for navigation it will break them. Could we perhaps add an aria role or label for `a11y` enhancements?

**Comment by bsonefeld** [comment]
@CptPilot , could you post a screenshot of what your use case looks like when using the Dropdown?

**Comment by richardpilot** [comment]
Thanks for the pointer @tw15egan . Everyone had been referring to it as a dropdown in our design meetings that I hadn't spotted there was a Select component that meets our needs exactly. Apologies for the confusion, completely my fault. Closing.

**Comment by tw15egan** [comment]
Happy to help 🙂
