### ISSUE TITLE
Hand icon on the Donut charts when mouse pointer is hovered over them

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon#5127]
### Summary

Mouse pointer on the Donut chart doesn't change to hand cursor on hovering. In some of the graphs, they have a drill down capability. Having hand cursor on hover would be appropriate.

This will be an enhancement

### Justification

Having the hand icon gives the user a feeling that there might be some functionality associated with it.

**Comment by asudoh** [comment]
HI 👋 do you want to report this to https://github.com/carbon-design-system/carbon-charts? Thanks!

**Comment by arnajdas1992** [comment]
Oh, yeah right, Should have created it there. Thanks. Created https://github.com/carbon-design-system/carbon-charts/issues/475
