### ISSUE TITLE
Pagination "totalItems" bigger then 2000000 is blocking whole application

### ISSUE THREAD

**Issue by kokavec** [carbon-design-system/carbon#5129]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

In my application, I'm using carbon react component "pagination".  In the pagination component I'm using "totalItems" property I'm  combination with itemRangeText function. When number of totalitems is very big in my situation close to 2 000 000 whole application is blocked.

> Is this issue related to a specific component?

"Pagination" Component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Firefox and Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "^10.7.0",
"carbon-components-react": "^7.7.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

It is easy to reproduce even on official Stroybook

1. Open link with Pagination component in Storybook
http://react.carbondesignsystem.com/?path=/story/pagination--pagination
2. Click on "Knobs" tab
3. In the input field "Total number of items (totalitems)" put number 2000 000.
4. leave the input field and everything is blocked.
.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Workaround

It is possible to use property "pageInputDisabled" in combination with function "itemText" and just manually put total items.

**Comment by asudoh** [comment]
Seems very close to #4365 - Let us know if you don't think it's the case and we can re-open. Thanks!
