### ISSUE TITLE
Fail to yarn install --offline in root package

### ISSUE THREAD

**Issue by xxxle0** [carbon-design-system/carbon#5132]
## What package(s) are you using?

- [x] `carbon`

## Relevant information
my terminal show this error when i follow instruction of contribute guide ( step 5 ). Please help. Thanks 
![Screen Shot 2020-01-23 at 1 08 54 AM](https://user-images.githubusercontent.com/18297839/72921100-348bb980-3d7d-11ea-913c-8a4148be90fc.png)

**Comment by tw15egan** [comment]
A couple of questions: 

- Which step of the tutorial are you on? 
- Which exact command did you run when you got this error? 
- Which version of Node are you on?

**Comment by xxxle0** [comment]
- step 5 [Link](https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#5-build-and-start-the-development-server)
- yarn or yarn install --offline
- v10.18.1

**Comment by xxxle0** [comment]
hi @tw15egan, this issue still exists

**Comment by asudoh** [comment]
Not sure it's the case for this issue author, but issue# 1337 at `node-gyp` repo seems to tell that version `2.x` of Python is necessary. Some SO Q&A seems to tell that node.js version may be in play.

**Comment by xxxle0** [comment]
yeah @asudoh you are right. We should install python2
