### ISSUE TITLE
Hover background color for Select component is wrong in G10 theme

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/carbon#5136]
I render the Select component like the following in my code:

```
<Select id="some-id"
    labelText="some label" light={true}>
      <SelectItem key="1" text="name1" value="value1"/>
      <SelectItem key="2" text="name2" value="value2"/>
      <SelectItem key="3" text="name3" value="value3"/>
</Select>
```

In G10 theme with `light` prop set to `true`, if I hover the Select component, the background color will become white and this is clashing with the white background color of my component.

Background color without hover:
![image](https://user-images.githubusercontent.com/12156672/72923099-57d24c80-3d1c-11ea-8cb7-5949e731e5b2.png)

Background color when hover:
![image](https://user-images.githubusercontent.com/12156672/72923199-923be980-3d1c-11ea-9c4c-378f3aa3c9d7.png)

The DOM of the Select component when hover
![image](https://user-images.githubusercontent.com/12156672/72922951-ff9b4a80-3d1b-11ea-87bd-ccbd97c8227f.png)

**Comment by asudoh** [comment]
@carbon-design-system/design Any input? Thanks!

**Comment by laurenmrice** [comment]
The hover color should be `hover-ui` token (Gray 10 hover #e5e5e5)
