### ISSUE TITLE
UI Shell click icon for dropdown

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#5138]
## What package(s) are you using?

- [ ] `carbon-components`
- [ x ] `carbon-components-react`

## Summary
I am using the header from UI Shell: http://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation-and-actions

For the action buttons on the right, is there a way to add a dropdown to them like the `link 4` in the navigation section to the left? Or is there a way for the headermenu to display an icon rather than a text?

Currently the headermenu only supports text, i.e. provide text as prop `menuLinkName`.

**Comment by sakshigoyal007** [comment]
Hi @gptt916 , I am working on the same. Did you find any solution for this?
