### ISSUE TITLE
[icon library] remove logo--google icon from repo and library

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/carbon#5153]
Recently was brought to our attention that the `logo--google` icon in the `Brand > Social` category is not legally compliant and should be removed from the repo and as soon as possible.

Background: Google plus is no longer and active social platform (Google shut it down) and we do not need the Google G in the icon library.

DOD:
Remove the Google G from the icon library (on Carbon and on Design Language)

![Screen Shot 2020-01-23 at 11 55 19 AM](https://user-images.githubusercontent.com/16782944/73005623-400bce80-3dd7-11ea-8476-acf16dcb1d7b.png)

![54a9a3a1-2b00-4c85-9947-753829e4c8a2](https://user-images.githubusercontent.com/16782944/73006456-afce8900-3dd8-11ea-89b6-7edb558df860.jpeg)

**Comment by mjabbink** [comment]
Hold on this issue

**Comment by mjabbink** [comment]
This is a use case we’re currently designing for. Signing in with Google account. In this case we could use the google “G”

![image (37).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fd892af1-00c9-4823-a57d-c665343bd5ad)

**Comment by mjabbink** [comment]
![image (40).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/5f945a8a-fa34-460a-86b5-412cd52e7008)

![image (38).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fc5354f5-8539-4a17-97a6-c22b827831d2)

![image (40).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/aa4927ea-260e-4bb0-b251-650acb013b5f)

**Comment by mjabbink** [comment]
proceed

**Comment by conradennis** [comment]
issue moved to here: https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/issues/carbon-design-system/gatsby-theme-carbon/694

**Comment by conradennis** [comment]
I'm adding a batch of icons into the repo this week, can probably handle this one myself.

**Comment by conradennis** [comment]
PR with `logo--google` icon removal: https://github.com/carbon-design-system/carbon/pull/5342

**Comment by joshblack** [comment]
Closing as this was removed in #5342
