### ISSUE TITLE
Header Base w/navigation not displaying navigation at breakpoint width 1056px

### ISSUE THREAD

**Issue by fsegu002** [carbon-design-system/carbon#5157]
## What package(s) are you using?

- [x] `carbon-components@10.9.1`
- [x] `carbon-components-react@7.9.1`

## Describe the bug
When screen width is at exactly 1056px (breakpoint transition) navigation is not visible.

## To Reproduce

* Open browser and navigate to [Header Base w/navigation demo page](http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation)
* Open developer tools
* Set "Responsive" mode and width to 1056px
* No navigation links are displayed
* Expected behavior
* Layout should display desktop navigation links from this breakpoint and greater.

![image](https://user-images.githubusercontent.com/3401787/73016303-984ccb80-3deb-11ea-8bee-40ad9408a4a9.png)

**Comment by asudoh** [comment]
Tried http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation today. With smaller real screen estate as this issue describes, it now shows hamburger icon at the left and clicking on that will show the nav content. Let us know if it's not the case and we can reopen.

**Comment by fsegu002** [comment]
> Tried http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation today. With smaller real screen estate as this issue describes, it now shows hamburger icon at the left and clicking on that will show the nav content. Let us know if it's not the case and we can reopen.

Thanks @asudoh, but this issue persist. The problem here can be reproduced at width 1056px exactly, like I specified in the issue. Please try that.
