### ISSUE TITLE
[File Uploader] FileUploaderDropContainer fails on Mac when using Finder

### ISSUE THREAD

**Issue by edavidj** [carbon-design-system/carbon#5158]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using FileUploaderDropContainer on Mac, I am able to drag and drop images into the container, but an error will be thrown upon trying to do the same by clicking and using the file Finder.

I thought it might be my own setup but I was able to reproduce the error in the [storybook docs](http://react.carbondesignsystem.com/?path=/story/fileuploader--fileuploaderdropcontainer).

> Is this issue related to a specific component?

`FileUploader/FileUploaderDropContainer`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the file uploader to accept the file upon either drop or selection through OS File Finder. When using Finder to open a file, nothing happens post selection (i.e. there is no visual error and no file selected). Upon opening the console you can see the following error:
```
Uncaught TypeError: Cannot read property 'files' of undefined
    at FileUploaderDropContainer.js:46
    at handleChange (FileUploaderDropContainer.js:65)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at qa (react-dom.production.min.js:15)
    at react-dom.production.min.js:16
    at wa (react-dom.production.min.js:16)
    at Aa (react-dom.production.min.js:17)
    at ya (react-dom.production.min.js:17)
    at Ba (react-dom.production.min.js:17)
    at Pd (react-dom.production.min.js:85)
```

> What browser are you working in?

Chrome - Version 79.0.3945.130

> What version of the Carbon Design System are you using?

`carbon-components: ^10.7.1`
`carbon-components-react: ^7.9.2`

## Steps to reproduce the issue

1. Click on the container to open Finder
2. Select a file and click 'Open'
3. Open console to see aforementioned error message.

See:
https://codesandbox.io/s/agitated-bouman-5ecqx

## Additional information

- This error occurred on two colleagues machine with roughly the same setup described above.

**Comment by emyarod** [comment]
this is resolved in #4936 which will be in an upcoming release

related #4899
