### ISSUE TITLE
External filters for data table

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5162]
### Summary

We are requesting an "external filter" component for the Carbon data table. This filter component can be used for up to 2 filters and is integrated into the table toolbar.

**Proposed design:** 

![image](https://user-images.githubusercontent.com/39408106/73024017-4bb8be80-3df2-11ea-9438-418f263f9239.png)

### Justification

Filtering is a core table functionality, but Carbon lacks a table filtering component. As a result, teams have implemented filters in conflicting ways, causing user confusion and highlighting internal divisions.

This component acts as a complement to our primary filter contribution, the [filter panel](https://github.com/carbon-design-system/carbon/issues/5161). A large number of use cases on IBM Cloud require only 1-2 filters, and in many cases, infrastructure tables MUST be pre-filtered to a specific region for technical reasons. In these cases, the pre-filtered state must be visible.

The external filter addresses this use case.

### Specs

This component should only be used for 1-2 filters. If there is only 1 filter displayed a divider line should still separate it from the search field.

This component is responsive and has optimized layouts for tablet and mobile.

**Desktop:**

![image](https://user-images.githubusercontent.com/39408106/73024273-def1f400-3df2-11ea-8d8f-443a79ef3324.png)

With only one filter

![image](https://user-images.githubusercontent.com/39408106/73024456-3abc7d00-3df3-11ea-9595-cfbe9ca38474.png)

With text acting as an inline label before the filter:

![image](https://user-images.githubusercontent.com/39408106/73025034-7a379900-3df4-11ea-8544-5118b658a17a.png)

**Tablet (672px):**

![image](https://user-images.githubusercontent.com/39408106/73024302-edd8a680-3df2-11ea-890b-9cb077b595e5.png)

**Mobile (320px):**

![image](https://user-images.githubusercontent.com/39408106/73024370-1496dd00-3df3-11ea-8925-55e62c8382e3.png)

### Desired UX and success metrics

The desired UX is that users can easily discover, apply, and view their filters. Users should be able to see and easily remove one or all of their filter selections. They should be able to know if a filter has been 

For users that already enjoy this feature on Softlayer tables, the goal is to preserve existing functionality. As a success metric for this feature, we will track clicks on the filter icon, as well as use amplitude to track the number of users who use filters on pages where this panel has been implemented.

### "Must have" functionality

- Works with single and multiselect filters
- Designer can use with 1 or 2 filters showing
- Optional knob to show 14px label text before the inline filter dropdown (see above)
- Responsive layouts (see above)
- Keyboard and screen reader accessible

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables at end of January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.

### Available extra resources

Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

**Comment by laurenmrice** [comment]
Spoke with Virginia, this is already made and in the Connected Components of Cloud pal, so going to close 👍🏻

**Comment by AlanGreene** [comment]
This would be very useful to Carbon consumers who do not have access to Cloud PAL (i.e. anyone outside of IBM developing applications with Carbon, including other open source IBM-led projects). It's a very common requirement when working with large amounts of data in a table and as stated in the description consumers currently have to implement this themselves, often in inconsistent ways.

**Comment by interJamesy** [comment]
Would have been nice for the rest of us :(
