### ISSUE TITLE
field Button - long text overflows button borders

### ISSUE THREAD

**Issue by mike-zuliani** [carbon-design-system/carbon#5164]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I was testing Button behavior for excessively long labels (just because) and noticed weirdness when size='field'.
The text and hover targets overflow above and below the button. 
(I know these are extreme edge cases and buttons should “never” have labels this long.)

### Component?

```
Button
size='field'
```

> What did you expect to happen? 

Text would be truncated from the end and replaced with ... 

> What happened instead?

Text overflowed above and below the button on Firefox and overflowed below the button on Chrome. Truncated the second line of text in Safari (macOS and iOS).
The overflow text responds to hover and click even through it is outside of the button rectangle.

> What would you like to see changed?

More graceful failure when the text is too long and height is constrained by the `size='field'` property. For example, truncate the text and make it visible on hover.

> What browser are you working in?

- Firefox 72.0.2 on macOS
- Chrome Version 79.0.3945.130 on macOS
- Safari Version 13.0.4 (15608.4.9.1.3) on macOS

> What version of the Carbon Design System are you using?

Vanilla Components version ^10.9.0
React Components version ^7.9.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Engineering Lifecycle Management - nothing pressing

## Steps to reproduce the issue

1. Go to the code page: https://www.carbondesignsystem.com/components/button/code/
2. Select the **field** size
3. Type or paste a really long label in the source code window
4. Text overflows out of the button, top or partially truncated.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

Chrome
![Button field size in Chrome 2020-01-23_17-20-45](https://user-images.githubusercontent.com/11927321/73029100-eae6b180-3e04-11ea-81ca-86100bbcda7f.png)

Safari
![Button field size in Safari](https://user-images.githubusercontent.com/11927321/73029112-f1752900-3e04-11ea-9ee2-e3cc12febf25.png)

Firefox
![Button field size in Firefox](https://user-images.githubusercontent.com/11927321/73029116-f3d78300-3e04-11ea-9c90-6bbd2c850cd2.png)

```
      import React from 'react';
      import { render } from 'react-dom';
      import 'carbon-components/css/carbon-components.min.css';
      import { Button } from 'carbon-components-react';
    
      const App = () => (
        <Button size='field'>Hello World How does overflow text work? In a very strange way. Is this not what you expected? Why would anyone want a button with a super-long label anyway?</Button>
      );

      render(<App />, document.getElementById('root'));
    
```

**Comment by asudoh** [comment]
@carbon-design-system/design Does the design guidance of field button allow extremely long text...? Thanks!

**Comment by laurenmrice** [comment]
We recommend not having more than three words for a button label. But if a button label is long like this the container should be expanding proportionally with the label text. Should respond how the default size is for example:

![Screen Shot 2020-01-24 at 9 22 28 AM](https://user-images.githubusercontent.com/43969356/73080222-17dda780-3e8b-11ea-91b4-b73d4b9b2409.png)
