### ISSUE TITLE
Have extra fields in Row of Datatable.

### ISSUE THREAD

**Issue by moficodes** [carbon-design-system/carbon#5171]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I am trying to use the datatable component.

What I want to have is to have access to row content that is not being shown to the screen. 

For example. 

row = [a,b,c,d,e]

header = [a, b, c]

so only a b c show up as cell. 

but in selectedRow prop I would like to have access to d or e, which are metadata useful for me but not useful for the user to see.

Is this possible in an easy way?

**Comment by dakahn** [comment]
Just to clarify -- you have a row where every cell isn't under a corresponding header? Is this because of overflow or is this by design?

**Comment by moficodes** [comment]
say i have some data. 

```
	AccountID       
	ResourceInstanceID 
	ResourceGroupID   
	Month         
	PricingCountry   
	BillingCountry     
	CurrencyCode     
	PlanID             
	ResourceID         
	Billable           
	PricingPlanID  
	Region            
	Usage       
```

Lets take the above list of columns. Some of those data are metadata, and not data I would want to show to user. so I ignore those in the header and with that those gets ignored in the row. But on batch actions or actions on row the meta datas are useful for me to be able to say make api calls and such.

**Comment by dakahn** [comment]
Our table is only responsible for rendering what it's given; have you tried to do a lookup with the row ID to get to that metadata info you want?

**Comment by tw15egan** [comment]
@moficodes if possible, it would be great if you could attach a CodeSanbox demonstrating what you are trying to accomplish so that we can help out 👍

**Comment by moficodes** [comment]
thanks @dakahn and @tw15egan 

I have got this to work with making a new dictionary where the rowid is the 🔑  of the data passed. 

This work well enough. closing.

**Comment by tw15egan** [comment]
Thanks for the update and glad you've got it working 🎉
