### ISSUE TITLE
MultiSelect.Filterable component has bug with search box outline

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon#5177]
carbon 10.9.0

the `<MultiSelect.Filterable` react component seems to have a bug when the search box is active. (not the dropdown itself, it looks fine) if you select an item, and then click on the search box, the outline clips the number and it looks wrong:

![image](https://user-images.githubusercontent.com/10033254/73087423-1bc3f680-3e98-11ea-985c-1e6193b10bba.png)

**Comment by emyarod** [comment]
it doesn't appear in our component storybook. can you create a reduced test case in [code sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox)? 

![image](https://user-images.githubusercontent.com/8265238/73087900-d653f900-3e98-11ea-8d2d-d633814151a0.png)

**Comment by amortiz** [comment]
I apologize, i was missing some SCSS from the combo-box component, it seems to work fine now
