### ISSUE TITLE
Accordion not working after refresh in browser

### ISSUE THREAD

**Issue by chaithanya** [carbon-design-system/carbon#518]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?
Hi, i have used Accordion in the component, it is working after routing, but when i refresh the same page, then Accordion is not working

> Is this issue related to a specific component? 
No

> What did you expect to happen? What happened instead? What would you like to see changed?
Accordion should work even after refresh

> What browser are you working in? 
chrome and mozilla

> What version of the Carbon Design System are you using? 
8.7.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
working on a new project. release dates are very near

## Steps to reproduce the issue

1. Step one
perform an advance search, shows the multiple records in table, select any record, opens another page, which contains Accordion, click on the Accordion, it expands.
2. Step two
refresh the same page, now Accordion does not expand

## Additional information

* Screenshots or code
<ul data-accordion class="bx--accordion">
  <li data-accordion-item class="bx--accordion__item">
    <a class="bx--accordion__heading" aria-expanded="false" aria-controls="pane1">
      <svg class="bx--accordion__arrow" width="8" height="12" viewBox="0 0 8 12" fill-rule="evenodd">
        <path d="M0 10.6L4.7 6 0 1.4 1.4 0l6.1 6-6.1 6z"></path>
      </svg>
      <p class="bx--accordion__title">Section 1 title </p>
    </a>
    <div id="pane1" class="bx--accordion__content">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </li>
</ul>

In component.ts
import {Accordion} from 'carbon-components';
ngOnOnit(){ Accordion.init(); }
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment]
Hi @chaithanya as stated in http://www.carbondesignsystem.com/getting-started/developers, the best way to make sure the components work with AJAX frameworks is creating “wrapping components”. You can see an example for Angular4 with slider in https://codepen.io/asudoh/pen/VryJBO. Hope this helps.

**Comment by chaithanya** [comment]
i have installed carbon-components using npm install --save carbon-components
and used as
import {Accordion} from 'carbon-components';
ngOnOnit(){ Accordion.init(); }

will this does not work ?

**Comment by asudoh** [comment]
@chaithanya If you are looking for an easier way, you may want to try `CarbonComponents.watch()`.

**Comment by chaithanya** [comment]
Hi Sudoh,

where should i call CarbonComponents.watch()

**Comment by asudoh** [comment]
@chaithanya I guess in `ngOnInit()` is fine.

**Comment by chaithanya** [comment]
Hi Sudoh,
when i write Accordion.watch() in ngOnInit(), i am getting error saying that TypeError: missing argument 1 when calling function WEBPACK_IMPORTED_MODULE_4_carbon_components__a.watch

**Comment by asudoh** [comment]
@chaithanya Seems that you are having trouble integrating Carbon to your build toolchain. I cannot give direct solution because I don't know about your your specific toolchain, but here are some hints: The ECMAScript module is at [`node_modules/carbon-components/es/globals/js/watch.js`](https://github.com/carbon-design-system/carbon-components/blob/221e5e2/src/globals/js/watch.js). The file contains a [default export](https://github.com/carbon-design-system/carbon-components/blob/221e5e2/src/globals/js/watch.js#L42) which I referred to as `CarbonComponents.watch()`. It takes two arguments but both have the default values that should work fine for most of applications.

Hope this helps for you to debug further.

**Comment by chaithanya** [comment]
i am using webpack and angular-cli.
so should i write Accordion.watch() ? if i write CarbonComponents.watch(), its showing error in UI itself

**Comment by asudoh** [comment]
@chaithanya No `Accordion` does not have `.watch()`. It instead is one of the exports in Carbon bundle: https://github.com/carbon-design-system/carbon-components/blob/1c4cc0c/src/bundle.js

**Comment by chaithanya** [comment]
now i exported watch successfully, so when i write CarbonComponents.watch() , it says cannot find name CarbonComponents

**Comment by asudoh** [comment]
@chaithanya `CarbonComponents` global variable is there only when you use bundled version of Carbon (e.g. `carbon-components.js`). Otherwise you'd want to use the default export of [`watch.js`](https://github.com/carbon-design-system/carbon-components/blob/221e5e2/src/globals/js/watch.js) instead.

**Comment by chaithanya** [comment]
can you put code in the plunker that Accordion should work in two ways
1) after routing
2) page refresh

**Comment by asudoh** [comment]
@chaithanya The `watch.js` code supports both scenario. Given it appears that you are having trouble integrating our code - Probably you may want to tap us via Slack in case you are an IBMer.

**Comment by chaithanya** [comment]
yes i am an IBMer

**Comment by chaithanya** [comment]
can you give me the link how can i reach out to slack

**Comment by asudoh** [comment]
@chaithanya I cannot given this is a public GitHub repo - You can search my name in blue pages and email me asking for the link to the Slack channel. Thanks!

**Comment by chaithanya** [comment]
sure thanks

**Comment by marijohannessen** [comment]
Closing this as it was resolved outside of this issue 😄
