### ISSUE TITLE
Building carbon scss fails due to Invalid null operation: "null plus null"

### ISSUE THREAD

**Issue by dzaqb** [carbon-design-system/carbon#5187]
## What package(s) are you using?
    "carbon-components": "^10.9.2",
    "carbon-components-react": "^7.9.2",

- [X ] `carbon-components`
- [X ] `carbon-components-react`

## Detailed description
The build of WKC project is failing because of error inside carbon-component library. 

````
Fatal error: Error: Invalid null operation: "null plus null".
        on line 216 of node_modules/carbon-components/scss/components/select/_select.scss, in mixin `select`
        from line 251 of node_modules/carbon-components/scss/components/select/_select.scss, in mixin `@content`
        from line 23 of node_modules/carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/import-once/import-once.scss, in mixin `exports`
        from line 250 of node_modules/carbon-components/scss/components/select/_select.scss
        from line 126 of node_modules/carbon-components/scss/globals/scss/styles.scss
>>     padding-right: $spacing-09 + $spacing-03; // 3.5rem
````

The issue occurs with carbon-component 10.9.x
It doesn't occur with version carbon-component 10.7.3

Problem occurs only when carbon  themes are imported before importing carbon styles E.g.:

````
@import "~@carbon/themes/scss/themes.scss";
@import "~carbon-components/scss/globals/scss/styles.scss";
````

The problem is caused by $spacing tokens set to null. 
These tokens are reset to null each time carbon--theme() mixin is running.
````carbon-components/scss/vendor/@carbon/elements/scss/themes/generated/_mixins.scss````
This mixin sets the tokens to null in lines:
````
  $spacing-01: map-get($theme, 'spacing-01') !global;
  $spacing-02: map-get($theme, 'spacing-02') !global;
  ....
````

Carbon themes defined in carbon-components do not contain these spacing tokens and that's why
this mixin assigned null to them. 

I found the workarounds
1. Add missing spacing token to the theme.
2 Or  enable feature flag:
````
$feature-flags: (
    enable-css-custom-properties: true,
);
````

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - One question; What Sass toolchain are you using?

**Comment by dzaqb** [comment]
webpack sass-loader

**Comment by asudoh** [comment]
Created a quick setup at https://codesandbox.io/s/github/asudoh/carbon-components/tree/codesandbox-webpack/packages/components/examples/codesandbox-webpack, but the problem doesn't seems to reproduce there. Probably you want to fork from there and complete your reduced case?

**Comment by dzaqb** [comment]
I won't be able to reproduce there. 
I already found the root cause which is mismatch between tokens defined in the theme and the mixin. 
Mixin contains spacing tokens which are not part of themes. 
Not sure  why spacing tokens are part of themes. Is it expected? 
I would expect to either remove spacing tokens from the carbon--theme() mixin  
or
add these tokens to themese (however, then all the themes would need to have it , even those which were defined outside of carbon-components lib)

**Comment by asudoh** [comment]
In such case, I recommend creating a reduced case by yourself. Reduced case works as a best communication tool for common understanding of the problem you are facing and what you found in your environment as you described above. More information why reduced case is important can be found at: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases

**Comment by sandrodesantis** [comment]
Hi, I'm facing the same issue, look:

Follow my package.json, maybe it can help you identify the issue.

Failed to compile.

./src/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/styles/index.scss)
SassError: Invalid null operation: "null plus null".
        on line 216 of node_modules/carbon-components/scss/components/select/_select.scss, in mixin `select`
        from line 251 of node_modules/carbon-components/scss/components/select/_select.scss, in mixin `@content`
        from line 23 of node_modules/carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/import-once/import-once.scss, in mixin `exports`
        from line 250 of node_modules/carbon-components/scss/components/select/_select.scss
        from line 126 of node_modules/carbon-components/scss/globals/scss/styles.scss
        from line 8 of src/styles/_carbon.scss
        from line 1 of /Users/ssantis/ibm/projects/cai/sellershub-carbon/cai-sellershub-fe/branchs/auth/cai-sellershub-fe/src/styles/index.scss
>>     padding-right: $spacing-09 + $spacing-03; // 3.5rem

   -------------------^

=============
My package.json
=============

{
  "name": "teste",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@carbon/icons": "10.8.2",
    "@carbon/icons-react": "10.8.2",
    "@carbon/themes": "10.9.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "auth0-js": "^9.12.2",
    "axios": "^0.19.2",
    "carbon-components": "10.9.3",
    "carbon-components-react": "7.9.3",
    "cfenv": "^1.2.2",
    "cross-env": "^7.0.0",
    "crypto": "^1.0.1",
    "crypto-js": "^4.0.0",
    "dompurify": "^2.0.8",
    "idtoken-verifier": "^2.0.2",
    "node-sass": "^4.13.1",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-ga": "2.7.0",
    "react-iframe": "1.8.0",
    "react-redux": "7.2.0",
    "react-router-dom": "5.1.2",
    "react-scripts": "3.4.0",
    "redux": "^4.0.5",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "export HTTPS=true && react-scripts start",
    "test": "react-scripts test",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "copyStatic": "cp static/* build"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6"
  }
}

about the workarounds, It's not clear to me how can I apply, could you help me?

$feature-flags: (
    enable-css-custom-properties: true,
);

**Comment by dzaqb** [comment]
With regards to workaround, try something like this:

````
@import "~@carbon/themes/scss/themes.scss";
$feature-flags: (
    enable-css-custom-properties: true,
);
@import "~carbon-components/scss/globals/scss/styles.scss";
````

**Comment by sandrodesantis** [comment]
tks !!!

**Comment by tw15egan** [comment]
Seems like you've found a workaround, so I'm going to mark this as closed. If you would like us to take a deeper look into the issue, I'd recommend creating a reduced test case on CodeSandbox that illustrates the problem, as the link provided by @asudoh works properly for me. Thanks!

**Comment by asudoh** [comment]
Thanks @tw15egan! One of the suspect is the issue is specific to Dart Sass. So if any people in this thread is using Carbon Angular variant please let us know. Still hoping that somebody can create a reduced case.
