### ISSUE TITLE
Clicking on the Tooltip TriggerText doesn't open the tooltip

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#5188]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If I use the triggerText property to label a tooltip, clicking or tapping on the triggerText doesn't actually open the Tooltip

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected for the Tooltip to open when clicking on triggerText

> What browser are you working in?

> What version of the Carbon Design System are you using?

**Comment by emyarod** [comment]
not sure if this behavior is intentional, just want to double check with @carbon-design-system/design

**Comment by aagonzales** [comment]
@scottdickerson which tooltip are you using? I'm not sure I'm understanding the problem.

These variations allow you to click on the text as the trigger for the icon.
http://react.carbondesignsystem.com/?path=/story/tooltip--no-icon
http://react.carbondesignsystem.com/?path=/story/tooltipdefinition--default

**Comment by scottdickerson** [comment]
Sorry @aagonzales its the Tooltip with Icon and triggerText

**Comment by aagonzales** [comment]
Can you explain the scenario around why it needs to work this way? 

The tooltip is opening from the icon so I feel like keeping the trigger target exclusively on the icon seems more natural, versus clicking on the label and having a tooltip open elsewhere. If the label could trigger the tooltip then why have the icon? The label also could potentially have a different function that the tooltip icon, like this example from github. These are just my initial thoughts, I'm going to look into this more and see what some ux best practices are and I'll talk to the rest of the team about this as well. 

![Jan-27-2020 13-16-40](https://user-images.githubusercontent.com/11670886/73205906-829b1700-4107-11ea-95b0-657db26f3b05.gif)

**Comment by scottdickerson** [comment]
That makes sense I think the primary confusion was around the prop name “triggerText” I was assuming that the text would trigger the tooltip

**Comment by emyarod** [comment]
seems like it was [introduced in v7](https://github.com/carbon-design-system/carbon/commit/316f39dcf989f32109a453fccc262db8c407473e), and we can look into renaming the prop to reflect the current component behavior more accurately for v11
