### ISSUE TITLE
Type Bug: Missing colon at inline notifications

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon#519]
@havesomeleeway commented on [Fri Jan 19 2018](https://github.com/carbon-design-system/design-system-website/issues/138)

### On the site

![screenshot-2018-1-20 carbon design system](https://user-images.githubusercontent.com/25948209/35178982-0798cec4-fdcc-11e7-9d63-fe05b79d4136.png)

### On Sketch

![screen shot 2018-01-20 at 10 24 14 am](https://user-images.githubusercontent.com/25948209/35178988-1d3393e0-fdcc-11e7-8e3d-fb0527aa73e5.png)

---

@marijohannessen commented on [Mon Jan 22 2018](https://github.com/carbon-design-system/design-system-website/issues/138#issuecomment-359475337)

Hi @havesomeleeway , thanks for creating this issue! This needs to be updated in the actual component since we're just pulling them directly from the repo, so I'm going to move this issue over to that repo. Thanks!

**Comment by bsonefeld** [comment]
Hi @havesomeleeway , this is actually a bug in the Design Kit, which we're updating with the newest release. We recently did a large content overhaul on the components, so we're still in the process of making updates. Look for this change to be reflected in the latest version of the Design Kit, which should be released within the next few weeks. 

To be clear, there should be no `:` colon within the notification title. 

Let us know if you have any more questions!

**Comment by havesomeleeway** [comment]
@bsonefeld, @marijohannessen thanks for following up on this. Meanwhile, should I just go ahead and assume that the components reflected on the carbon design website are more accurate than the kit itself?

**Comment by bsonefeld** [comment]
We try to keep them as in-sync as possible, but yes the website is usually the place to look for the most up-to-date resources.
