### ISSUE TITLE
[Notification]: add info icon to info inline and toast notifications

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#5190]
## [Notification]: add info icon to info inline and toast notifications

- [ ] update component package

- [ ] update kit

No reason not to have icons on all four notification types, it adds consistency and visual interest to the info notification. 

**The icon color will take the $support-04 token (it will be Blue 70 in the light themes and Blue 50 in the dark themes)**

Toast notification: all structural specs and tokens match the other 3 notifcations (both inline and toast) that have icons. Nothing new here, but provided visuals for reference.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/4e786638-ebcf-41d4-b2b7-43618afe13c9)

Inline notification:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/5af027a2-3877-4160-947d-b878ba719339)

**Comment by jeanservaas** [comment]
related to 
https://github.com/carbon-design-system/carbon/issues/5055

**Comment by asudoh** [comment]
Hi @jeanservaas thank you for writing this up! Is this dev-ready?

**Comment by laurenmrice** [comment]
yes its dev ready ^
