### ISSUE TITLE
Collapse/Expand function does not work with an accordion inside an accordion

### ISSUE THREAD

**Issue by gutakeda** [carbon-design-system/carbon#5191]
## What package(s) are you using?

- [ ] `carbon-components`
- [X ] `carbon-components-react`

## Detailed description

The issue is related to Accordion and AccordionItem components.
When using an accordion inside an accordion, the collapse/expand function does not work. Nothing happens when the arrow to collapse/expand is clicked.

Apparentelly this issue was already fixed (see links below), but I could not see these changes (on master) on _accordion.scss file.
https://github.com/carbon-design-system/carbon/pull/1309
https://github.com/carbon-design-system/carbon/issues/1262

Codesandbox test:
https://codesandbox.io/embed/dazzling-wood-tl8wo?fontsize=14&hidenavigation=1&theme=dark

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - It looks the same as: #4768
