### ISSUE TITLE
DatePicker disabled dates do not show as 'disabled'

### ISSUE THREAD

**Issue by cknabe** [carbon-design-system/carbon#5210]
carbon-components-react

On supplying a minDate and maxDate, the DatePicker properly keeps you from selecting outside the range. However, you cannot visually tell what is enabled/disabled.

In the below picture you should not see any date before the 29th as selectable.
![image](https://user-images.githubusercontent.com/13582620/73396612-6209c300-42a7-11ea-93e0-5a0954498c82.png)

A disabled class used to be applied to the disabled dates( .bx--date-picker__day.disabled, .flatpickr-day.disabled).
e.g. 
![image](https://user-images.githubusercontent.com/13582620/73396670-7cdc3780-42a7-11ea-9aaa-b5f9dfb684dc.png)

Example usage:
```
import {
  Checkbox,
  DatePicker,
  DatePickerInput,
  Select,
  SelectItem,
  SkeletonText,
  Tooltip,
} from '@console/pal/carbon-components-react';
      <DatePicker
        className={'time-component'}
        dateFormat={dateFormat}
        datePickerType="single"
        disabled={isImmediate}
        id="date-picker"
        key="date-picker"
        light={true}
        locale={locale}
        minDate={minDate}
        maxDate={maxDate}
        onChange={this.setSelectedDate}
      >
        <DatePickerInput
          defaultValue={selectedDateUtc}
          disabled={isImmediate}
          iconDescription={t('MaintenanceWindow.datePickerLabel')}
          id="maintenance-window-date-picker-input"
          labelText={t('MaintenanceWindow.datePickerLabel')}
          placeholder={placeholder}
        />
      </DatePicker>
```

Possibly the light={true} is messing with it somehow?

**Comment by tw15egan** [comment]
This should be resolved with https://github.com/carbon-design-system/carbon/pull/5085 when `10.9.3` is released. Going to close this, but feel free to reopen if you don't see the fix when the update is released.

**Comment by cknabe** [comment]
This has been resolved for me
![image](https://user-images.githubusercontent.com/13582620/73665190-4c5d1a80-4666-11ea-977b-49138cb474fc.png)
