### ISSUE TITLE
ProgressIndicator mobile UI

### ISSUE THREAD

**Issue by Tokscull** [carbon-design-system/carbon#5212]
## What packages are you using?

- [x] `carbon-components: "^10.9.2"`
- [x] `carbon-components-angular: "^3.35.4"`

## Detailed description

Progress Indicator have default minimal width and on a phones with small width (iPhone 5,SE) he does not scale to screen size of mobile phone.

![BlueBlueCar](https://user-images.githubusercontent.com/46087056/73428697-e3666180-434a-11ea-9304-b4e563b400e2.png)

If I remove min-width and change width in '.bx--progress-step' class and change width in '.bx--progress-line' class this solves the problem. But i haven't possibility to do it from my code, only from element inspector in browser.

**Comment by tw15egan** [comment]
@carbon-design-system/design do we have any guidance for mobile sizing?

**Comment by designertyler** [comment]
There's no guidance for mobile sizing for the progress indicator so thanks for bringing it to our attention @Tokscull 

We've recently explored designs to accommodate the tabs on narrow screens and the progress indicator and should give the same attention to the progress indicator (not necessarily the same solution, though).

We'll explore some possible design solutions and see what we can do to make the progress indicator work at this size.

**Comment by janhassel** [comment]
@designertyler Hey, I stumbled across this issue when looking for guidance on a mobile progress indicator and wanted to see if there are any updates so far? Are the design explorations shared somewhere?

**Comment by designertyler** [comment]
Hi @janhassel this is the work that was finalized for the tabs https://github.com/carbon-design-system/carbon/issues/4758#issuecomment-579347916

@aagonzales Did we ever explore the same solution for progress indicator? Do you think it would work the same way or would it need a different approach?
