### ISSUE TITLE
[text-area] set input type to body-long-01

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5213]
Since the text input component and text-area component are separate react stories, can we adjust the text-area input type to be `body-long-01` instead of short? Reason is because people will be using this component specifically to display long type on multiple lines which would make more sense to use the body-long-01 type instead.

--------------------------------------------------------------------------------------------------

Comparison:
![Artboard](https://user-images.githubusercontent.com/43969356/73465857-9f715d80-4346-11ea-9baf-514b922af900.png)

**Comment by tw15egan** [comment]
According to the code, it is currently set to `body-long-01`

https://github.com/carbon-design-system/carbon/blob/132dbfb46c590d2edab5b7fb405e74025b8c2782/packages/components/src/components/text-area/_text-area.scss#L25

In the React storybook, I am seeing Textarea with `1.25rem` line-height, and `1.125rem` line-height for text input, which seems like the only difference between short and long. 

Going to close this as resolved, but if we need to update it to something else just let me know 👍

**Comment by laurenmrice** [comment]
ahh well perfect ! thank you will update in our kits 👍🏻
