### ISSUE TITLE
[icons-react] `Interactions`, `Nominal`, and `Ordinal` are only exported as 16px

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#5224]
To replicate: download the latest @carbon/icons-react, go to es/ordinal: the only exported size is `16.js`

**Comment by vpicone** [comment]
looks like they weren't added to categories.yml in this PR: https://github.com/carbon-design-system/carbon/pull/5015/files

**Comment by chrisconnors-ibm** [comment]
marked closed related issues 'duplicate'

**Comment by chrisconnors-ibm** [comment]
> looks like they weren't added to categories.yml in this PR: https://github.com/carbon-design-system/carbon/pull/5015/files

They got added Dec 9, they're there now @ packages/icons/categories.yml L605, L612, L613

https://github.com/carbon-design-system/carbon/commit/dce56816e35055fe861b15d29d2f2d1eddbfeb53#diff-a5af4dfdc5ccb1cd4e99170826a08c45

merged file contained them: https://github.com/carbon-design-system/carbon/pull/5015/files

(expand the contracted sections and they're there L605, L612, L613)

**Comment by janhassel** [comment]
Hey, just checking on the status of this one. Any updates?

**Comment by joshblack** [comment]
@janhassel still WIP! Sorry about the delay 🤦‍♂

**Comment by aledavila** [comment]
Thanks for waiting on this. They are going to be in icons-react v10.9.0. Here is an example for ordinal in the [release candidate](https://unpkg.com/browse/@carbon/icons-react@10.9.0-rc.0/es/ordinal/). Not sure what happened.
