### ISSUE TITLE
Typescript definition for carbon-components-react is missing Link prop

### ISSUE THREAD

**Issue by rampadc** [carbon-design-system/carbon#5228]
## What package(s) are you using?

- [x] `carbon-components-react`
- [x] `@types/carbon-components-react`
- [x] `@types/react-router-dom`

## Detailed description

Typescript definition for carbon-components-react is missing Link prop.

> Is this issue related to a specific component?

Yes

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the following 2 lines to pass Typescript compilation.

```javascript
<HeaderName element={Link} to="/" prefix="IBM">Carbon Tutorial</HeaderName>
<HeaderMenuItem element={Link} to="/repos">Repositories</HeaderMenuItem>
```

What happened instead:

Each line above produced this error:

```
Type 'typeof Link' is not assignable to type 'string | ((props: Pick<{}, never>) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null) | (new (props: Pick<...>) => Component<...>) | undefined'.
  Type 'typeof Link' is not assignable to type 'new (props: Pick<{}, never>) => Component<Pick<{}, never>, any, any>'.
    Types of parameters 'props' and 'props' are incompatible.
      Property 'to' is missing in type 'Pick<{}, never>' but required in type 'Readonly<LinkProps<any>>'.ts(2322)
```

```
Link.d.ts(6, 5): The expected type comes from property 'element' which is declared here on type 'IntrinsicAttributes & Pick<{}, never> & LinkPropsBase<{}> & HeaderNamePropsBase & { children?: ReactNode; }'
```

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

None

## Steps to reproduce the issue

1. Create a new Typescript react project with create-react-app script.
2. Use Typescript and follow the tutorial step 1: https://www.carbondesignsystem.com/tutorial/react/step-1/#add-routing

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - The TypeScript type is a community project, maintained in http://github.com/DefinitelyTyped/DefinitelyTyped - Could you please report there? Also given the community project nature, a PR there will be much appreciated - Thanks!

**Comment by tw15egan** [comment]
Given this is a community project, and changes need to be made upstream at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react/lib/components/Link, I'm going to close this out.
