### ISSUE TITLE
[Select] Add size variants

### ISSUE THREAD

**Issue by Tokscull** [carbon-design-system/carbon#5229]
## What packages are you using?

- [x] `carbon-components: "^10.9.2"`
- [x] `carbon-components-angular: "^3.35.4"`
## 
Please add to [select](https://angular.carbondesignsystem.com/?path=/story/components-select--documentation) possibility to change size like it implemented in dropdown

**Comment by tw15egan** [comment]
@carbon-design-system/design should `select` have the same size variations as `dropdown`?

**Comment by aagonzales** [comment]
Yes, that seems to make sense.
