### ISSUE TITLE
How do I disable IBM Plex Font to load?

### ISSUE THREAD

**Issue by nullhook** [carbon-design-system/carbon#523]
Can I make the whole application use system fonts or fonts other than IBM Plex ? 

We're building an application using DoneJS which takes time to load fonts because of so many scripts and meanwhile the scripts get loaded user cannot see any text on the screen. I tried setting the body to use system fonts but this doesn't apply to all carbon components.

**Comment by asudoh** [comment]
@rehat101 Other Carbon folks may want to chime in, but IIUC the quickest way is building our CSS by yourself with your Sass toolchain ([`styles.scss`](https://github.com/carbon-design-system/carbon-components/blob/25f6afe/src/globals/scss/styles.scss) is the entry point) and override [several variables dictating the font family](https://github.com/carbon-design-system/carbon-components/blob/42e1110/src/globals/scss/_typography.scss#L3-L6). Hope this helps.

**Comment by marijohannessen** [comment]
Yes, that is the way to go! Feel free to re-open this issue if that doesn't solve your problem - thanks!
