### ISSUE TITLE
[NumberInput] Mobile variant width sizing issue

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon#5231]
Visual issue with mobile variant knob on number input

## What package(s) are you using?
- [X] `carbon-components-react`

## Detailed description
The number input mobile variant knob, when used in a form, does not size/justify well with other components (text, dropdown, ext) and causes a visual "rag"
See screen shots:
![Screen Shot 2020-01-31 at 9 17 47 AM](https://user-images.githubusercontent.com/21066152/73546118-a5307700-440a-11ea-81e9-b83ec9ef4455.png)
![Screen Shot 2020-01-31 at 9 18 09 AM](https://user-images.githubusercontent.com/21066152/73546125-a8c3fe00-440a-11ea-981f-05bc380625b7.png)

> Is this issue related to a specific component?
NumberInput, Mobile Variant Knob
https://react.carbondesignsystem.com/?path=/story/numberinput--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Component should be the same width as others when placed within a container

> What browser are you working in?
Chrome, FF
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Maximo, March first D-cut of Application Suite

**Comment by emyarod** [comment]
quick edit in storybook looks like this (depending on the width of the viewport)

![image](https://user-images.githubusercontent.com/8265238/73578687-de3a0d00-4445-11ea-8fdd-ff13e40ec217.png)

can you create a reduced test case in Code Sandbox for this?

**Comment by priyankitshukla** [comment]
Hi @emyarod ,
Please find below link to reproduce,
https://pages.github.ibm.com/maximo-app-framework/graphite/reference-app/#/dataFormatting

Please choose third Tab Single Smart Edit to see mentioned defect.


Thanks

**Comment by emyarod** [comment]
the behavior you are describing seems to be affected by the `align-items` rule on your container div
