### ISSUE TITLE
[structured list] selection variant needs peristent background for selected state

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5232]
For the selected state, the background needs to stay with the checkmark. The background color of the selected state should be `$layer-selected`.

--------------------------------------------------------------------------------------------------

Spec:
![Artboard](https://user-images.githubusercontent.com/43969356/227539649-675b23fc-9cd9-44f8-93da-3935c6ed5787.png)

**Comment by tw15egan** [comment]
Seems like this is a larger bug with the actual implementation of the React StructuredList, rather than a simple styling bug. The problem does not exist in vanilla. 

Can be bundled in with any changes based on the outcome of discussion regarding larger Structured List updates

https://github.com/carbon-design-system/carbon/issues/5065

**Comment by asudoh** [comment]
@tw15egan Just curious, is there any specific place in code where got an impression that this problem stems from how React StructuredList is implemented? Thanks!

**Comment by tw15egan** [comment]
Just a quick look at it, I'm seeing that it mainly just renders `children`, so the issue will be with getting the `checked`  value back up to `StructuredListRow`. Can probably map over children and pass in a ref, but if there are plans to update this component then I'm not too sure how much time we wanted to spend on it right now.

**Comment by asudoh** [comment]
Thanks @tw15egan for clarifying! I think we can listen to `change` event on `<StructuredListRow>` by letting the event bubble, but doing so causes an issue with programmatic control of the checked state. So agreed that it may involve a breaking change.

**Comment by tw15egan** [comment]
@asudoh I've been messing around with this one this afternoon, but I'm running into problems with programmatic controls like you said. Wondering if you have ideas on a possible solution to this issue, as well as https://github.com/carbon-design-system/carbon/issues/1937

**Comment by sstrubberg** [comment]
Need to update specs to v11.
