### ISSUE TITLE
Documentation references bx--text__input which is incorrect

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon#5237]
Carbon website Form documentation references bx--text__input which is incorrect. Should be .bx--text-input

<!-- Feel free to remove sections that aren't relevant.

**Comment by tw15egan** [comment]
Seems like a bunch of these FAQs is out of date on the website. Wondering if they should just be removed..? 

Wondering what @carbon-design-system/developers think

**Comment by joshblack** [comment]
I'd be down!

**Comment by asudoh** [comment]
> Wondering if they should just be removed..?

Yeah makes sense. Thank you for jumping in @tw15egan!

**Comment by tw15egan** [comment]
Do we want to remove them from the repo completely, or do we just want to hide them on the website?

**Comment by asudoh** [comment]
Good question, I think we can remove this, given we can bring the content back any time from the Git history.
