### ISSUE TITLE
Typescript error with 'aria-label' prop

### ISSUE THREAD

**Issue by sbiswas2** [carbon-design-system/carbon#5241]
According to the docs, the prop 'aria-label' is now required.   However, I am trying to pass multiple props into our Modal component like this:

<img width="641" alt="Screen Shot 2020-01-31 at 3 06 06 PM" src="https://user-images.githubusercontent.com/23437807/73575354-a0d18180-443d-11ea-8e15-56477d297838.png">
<img width="223" alt="Screen Shot 2020-01-31 at 3 06 21 PM" src="https://user-images.githubusercontent.com/23437807/73575363-a4fd9f00-443d-11ea-876d-124330257df1.png">

I am coding in React and trying to use the spread operator.

However, I keep getting a typescript error when trying to pass in props to the Modal component because of the dash (-) in 'aria-label'.  Would like to suggest that the prop name be changed to ariaLabel to avoid typescript error.

As a temporary solution, I am going to use modalAriaLabel for now to get an aria-label onto the browser to avoid a11y errors.  But would rather not have 'aria-label' prop changed, or not required, so I don't have to continue to see warnings about prop types.

**Comment by emyarod** [comment]
does this remove the error?

```js
const modalProps = {
  ...
  ['aria-label']: t('manage-orgs:modals.add-domain.heading'),
}
```

**Comment by sbiswas2** [comment]
Yes that seemed to work, my prettier plug-in changed it to this and it still works:
```
'aria-label': t('manage-orgs:modals.add-domain.heading'),
```

Thank you
