### ISSUE TITLE
Question about demos

### ISSUE THREAD

**Issue by jshuadvd** [carbon-design-system/carbon#5244]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-ibm-security`

## Summary
Hello, just a quick question as to where I can actually see some of the live demos of the products in the gallery of the docs page located [here](https://www.ibm.com/design/language/gallery/) like [this](https://www.ibm.com/design/language/3848c9434118d5b71e65ab6521b6d1f4/IBM_Security_Cloud_Prototype.gif), and [this](https://www.ibm.com/design/language/static/IBM_Security_Threat-Intel-Dash-a98137b2df330b6ea2fe7dba913cc699.mp4), as well as the images [here](https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#alignments) in the image above the linked section?

Adding Images here for reference as well.

Any help would be appreciated. 

![Image_5](https://user-images.githubusercontent.com/7577457/73985907-3d3dcd00-48f1-11ea-83a7-e0ed1d7510e3.jpg)

![Image_8](https://user-images.githubusercontent.com/7577457/73985966-5f374f80-48f1-11ea-9f43-80639ba073d4.jpg)

![IBM_Watson_Health](https://user-images.githubusercontent.com/7577457/73985980-652d3080-48f1-11ea-8c29-8addaefcfd16.jpg)

![2_1-1_ProductandWeb1](https://user-images.githubusercontent.com/7577457/73985997-724a1f80-48f1-11ea-856c-dd71391bd9d9.png)

![ThreatLandscape-Default](https://user-images.githubusercontent.com/7577457/73986001-74ac7980-48f1-11ea-96d2-4fc0f3ac428b.png)

**Comment by tw15egan** [comment]
@carbon-design-system/maintainers Any idea where these could be located?

**Comment by tw15egan** [comment]
@jendowns do you have any ideas where these come from / where they can be viewed?

**Comment by jendowns** [comment]
Hey @tw15egan! Looks like we had a similar issue opened here as well: https://github.com/carbon-design-system/ibm-security/issues/353

Here's where someone can get more info about CloudPak for IBM Security: https://www.ibm.com/products/cloud-pak-for-security

**Comment by tw15egan** [comment]
Sweet, thanks! 

Going to close this out as links have been provided, but more coded demos would definitely be helpful it seems.
