### ISSUE TITLE
Data Table - Styling issue with sticky header

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#5245]
I enabled sticky header in the table component.

Issue:
- Seems like having issue with size: short. Extra space is coming after header row.
- Its only working fine for normal: size

![image (4)](https://user-images.githubusercontent.com/29912424/73641640-56970d00-4696-11ea-8fc6-876671187870.png)

**Comment by emyarod** [comment]
can you create a reduced test case in [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by abhisheksinghrana** [comment]
Seems like issue with only Angular components. Creating same on carbon angular repo.
