### ISSUE TITLE
Data Table - Need Horizontal scrolling with sticky header.

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#5246]
Right now table component only support vertical scrolling with sticky header.

Issue:
- Without horizontal scroll support with sticky header, columns overlap each other.

![image (5)](https://user-images.githubusercontent.com/29912424/73642516-d1145c80-4697-11ea-90c0-cfbd1894944b.png)

Requirement:
- Need horizontal scroll support with sticky header.

**Comment by dakahn** [comment]
Closing as a duplicate 
https://github.com/carbon-design-system/carbon/issues/4748
