### ISSUE TITLE
side-nav--fixed class is not applied if IsFixedNav is set to true in NavBar

### ISSUE THREAD

**Issue by shahbazshueb** [carbon-design-system/carbon#5252]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
- `side-nav--fixed` class has to be manually set. The class disables expansion on hover when the navbar is collapsed as can be seen over [here](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_side-nav.scss#L113).

> Is this issue related to a specific component?
 - SideNav

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- I expected the `side-nav--fixed` class to be applied when I set the isFixedNav prop as true.

**Comment by aledavila** [comment]
Hi the reason is that `side-nav--fixed` is no longer being used in react but rather only in the vanilla version. When `IsFixedNav` is set to true `side-nav--collapsed` is what gets set.

**Comment by joshblack** [comment]
Going to close this one out, let me know if there are any other questions!
