### ISSUE TITLE
responsive issue on table action bar

### ISSUE THREAD

**Issue by eddielca** [carbon-design-system/carbon#5253]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
when we shrink browser to a certain width, the action buttons in the acrtion toolbar will overlap and become hidden because they are wrapped to second row

> Is this issue related to a specific component?
we also like to have this feature available: https://github.com/carbon-design-system/carbon/issues/4515

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
![1](https://user-images.githubusercontent.com/47797763/73692389-35d4b480-46a2-11ea-9ffd-2abb8eb96d2d.png)
- Notes

**Comment by asudoh** [comment]
@carbon-design-system/design Do we have a guidance where application may have lots of action buttons in table toolbar...? Thanks!

**Comment by aagonzales** [comment]
We have not yet seen a data table with that many batch actions. Is this a real use-case or just a stress test? I would maybe evaluate if all those action we're needed or if there was a way to present them differently. I would also advise your design team to take a look at this and suggest a solution. We have none in place at the moment. One idea maybe be to use a combo button but I'm not sure if that would test well in a batch action bar.

**Comment by eddielca** [comment]
this is an actual use case, we have a list of orders displayed in the table and we can do a number of actions to each of the orders selected. We also can run into this problem even with a few actions but action names are long such as `reassign pending orders`, might be even longer when translated into another language

**Comment by aagonzales** [comment]
@eddielca can you ask you design team to investigate? I don't think there's a quick fix for this without some trials. That or we can add this to our backlog to look into.
