### ISSUE TITLE
How to initialize all component at once? 

### ISSUE THREAD

**Issue by nullhook** [carbon-design-system/carbon#526]
How do I initialize all the components at once? 

I currently have to initialize the components individually like this
`CarbonComponents.DataTableV2.init()`

**Comment by asudoh** [comment]
Though it may not the exact thing you asked for, but you can use `CarbonComponents.watch()` API - Not only does it initialize all components, but also it tracks DOM changes and initialize/release components automatically.

Hope this helps.

**Comment by marijohannessen** [comment]
@rehat101 Did this answer your question?

**Comment by nullhook** [comment]
@marijohannessen Yep. Thanks.
