### ISSUE TITLE
[button] focus should be 2px border

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5263]
The focus border of the button needs to be 2px. Right not it is a lot thicker than it should be.

In Code now:
![Screen Shot 2020-02-04 at 9 59 39 AM](https://user-images.githubusercontent.com/43969356/73762237-877a4f00-4735-11ea-8b77-010b8ada592b.png)

Spec:
![Artboard](https://user-images.githubusercontent.com/43969356/73762036-3f5b2c80-4735-11ea-876a-555c786f80c6.png)

**Comment by xxxle0** [comment]
<img width="203" alt="Screen Shot 2020-02-05 at 8 29 50 AM" src="https://user-images.githubusercontent.com/18297839/73802910-b35b0a80-47f1-11ea-93f8-eb5728a8184c.png">
Is it that you expected ?  @laurenmrice

**Comment by xxxle0** [comment]
<img width="141" alt="Screen Shot 2020-02-05 at 8 32 13 AM" src="https://user-images.githubusercontent.com/18297839/73803014-0a60df80-47f2-11ea-80b3-79213c7f13c9.png">
after change the border to 2px 
Is it what you expected ? @laurenmrice

**Comment by laurenmrice** [comment]
The white/transparent space between the button and the border should be 1px. and the focus border should be 2px. Is there a pr for this?

**Comment by xxxle0** [comment]
ok let me create a PR for it but let me ask the dev team before create it. 
Did we implement any button property in theme for the focus width ? We are using $button-outline-width (1px) in theme for the focus width.

**Comment by tw15egan** [comment]
@xxxle0 Looks like we can change `$button-border-width` to `2px` and `$button-outline-width` to `2px` in `src/globals/scss/_theme-tokens.scss`

I'm going to assign this issue to you if you are willing to submit a PR 🙂 Feel free to remove it if you aren't able to work on it.

**Comment by xxxle0** [comment]
hi @tw15egan, if we change $button-outline-width to 2px -> it will effect to outline tooltip of button. I think we can create a PR that make easier to review.

**Comment by xxxle0** [comment]
#5290 this is my PR follow @tw15egan suggestion

**Comment by asudoh** [comment]
@laurenmrice @tw15egan Do you think this has been fixed by #5618? I see #5290 has been incorporated to `master`, but wanted to double-check with you. Thanks!

**Comment by laurenmrice** [comment]
Yes this has been fixed !
