### ISSUE TITLE
enhancement[helper text]: move helper text below input fields and dropdowns

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#5279]
### Problem:

- Product designers are having UI alignment issues with the helper text below the label

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/a5cf57c4-4cdb-4d53-bd3f-78314e240618)

<br>

- The stacking of the helper text under the label and the subtle color shift between the two pieces of type is fussy and not differentiated enough. $label-01 token value had to be pushed from Gray 70 to Gray 80 to make the label stand apart from the helper text; the stacking under the label also creates weird ragging

<br>

- after a brief competitive analysis, many other best-in-practise design systems use the arrangement we are proposing including: Material, Atlassian, Patternfly and Quickbooks to name a few; not only is it more intuitive for uses but it's a better design.

<br>

- We wanted to do this earlier but were worried about screen readers semantically reading label > help text > input in order; however you can set the screen reader order apparently to avoid that issue according to elizabeth judd this should not be a blocker.

<br>

- [x] Move helper text below input fields and drop down

<br>

- [x] Change value of $text-02 to Gray 70... both labels and helper text can now use $text-02

<br>

- [x] Remove right padding on helper text in mobile breakpoint

<br>

**Proposed spec:**

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/1c3ea94e-13e7-4b92-89e7-5578ed744e80)

Dropdowns with helper text will function the same way, and cover the helper text when it is open... we don't believe this is a problem:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/5e53d2eb-2fe5-40be-b4ba-75b9f7110990)

**Motion specs:**

Error message will animate to replace helper text; when you start to retype your input to correct the error the helper text will reappear. Material has a much better example of this than I can animate:

https://material.io/components/text-fields/#anatomy

![helper_text)_example.gif](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/856fdb7c-8705-42d3-befd-711c4464f9f5)

We will use our productive standard easing curves.

**Comment by tw15egan** [comment]
@jeanservaas what should `text-02` be changed to across all 4 themes?
