### ISSUE TITLE
[Overflow Menu]: Options are not selectable with mouse on Mac (Firefox or Safari)

### ISSUE THREAD

**Issue by gian1200** [carbon-design-system/carbon#5280]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When opening the overflow menu inside a table (in a row) and selecting one of the options, the event associated to the option is not triggered.

> Is this issue related to a specific component?

Overflow Menu (inside Data Table)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The Option should receive correctly the focus so that onclick events should work correctly

> What browser are you working in?

Chrome, Firefox, Safari, Edge

> What version of the Carbon Design System are you using?

10.9.3

The error appeared on v10.6.0. Version 10.5.1 doesn't have the issue.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Internal IBM Product - End of sprint: Feb 11th, 2020

## Steps to reproduce the issue

1. Load a table with overflow menu on Mac + Firefox
2. Open the menu
3. Click any option

> Please create a reduced test case in CodeSandbox

Reproducible at Vainilla Carbon demos on section `Data Table (with visible overflow menu triggers)`
https://vanilla.carbondesignsystem.com/?nav=data-table

Small sandbox (copied from demo): 
https://codesandbox.io/s/quirky-lalande-fglu4

## Additional information

- Screenshots or code:
Expected behaviour when clicking (screenshot from sandbox):
![image](https://user-images.githubusercontent.com/405347/73892898-1bd3d700-4846-11ea-87aa-00db5cb12e93.png)
- Notes:
    - The error appeared on v10.6.0. Version 10.5.1 doesn't have the issue.
    - This issue is happening only on a Mac on Firefox or Safari.
    - It works on Windows (Chrome, Firefox, Edge) and Mac + Chrome
    - Might be related to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

**Comment by asudoh** [comment]
Added the following code to the Sandbox, and it seems to work:

```javascript
document.addEventListener('click', event => {
  const menuItem = event.target.closest('.bx--overflow-menu-options__option');
  if (menuItem) {
    console.log('Menu item clicked:', menuItem);
  }
});
```

Please let us know if it's not the case for you - Thanks!

**Comment by gian1200** [comment]
Hi, I asked a friend who have a Mac and tested it on Firefox and Safari but it didn't work.

On Safari `event.target` is Body while on Firefox the listener is not even triggered.
- Safari:
![image](https://user-images.githubusercontent.com/405347/74171351-6f567400-4bfc-11ea-9e5c-29ce68a26e52.png)

- Firefox:
![image](https://user-images.githubusercontent.com/405347/74171333-6a91c000-4bfc-11ea-9f62-1970921f1876.png)

- On Chrome and Windows' browsers it is `bx--overflow-menu-options__option` as expected
![image](https://user-images.githubusercontent.com/405347/74171470-9dd44f00-4bfc-11ea-97da-0f7d8a5b4b8d.png)


------------------------------------------

Is this the recommended implementation or just a workaround? Although it helps catch the event, it feels "hacky". This may work for single overflow menu option on the screen, but will be tough to implement for many ones (multiple options in multiple overflow menus in multiple screens). If I understand correctly, the idea here is to catch the event and trigger the click event manually, or trigger the function that is supposed to be called for the option, right?

By default, on Windows it triggers the event 2 times. It is possible to prevent the default action, but it is an extra layer of complexity to the code that we'd prefer to avoid (to handle manual events, prevent infinite loops, handle data associated to the row that contains the menu), Ideally, we'd like to use as much "native code" as possible. The demo I built was using "onclick" for simplicity, but we are using AngularJS and `ng-click` is expected to be triggered as well.

Another question is how this "addEventListener" would affect the demo located at `Data Table (with visible overflow menu triggers)` https://vanilla.carbondesignsystem.com/?nav=data-table . That one faces the same issue as well

**Comment by asudoh** [comment]
Hi 👋 first, vanilla overflow menu does not have a custom event for item selection like [one in dropdown](https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/src/components/dropdown/dropdown.js#L386-L392). That said, capturing the raw `click`, etc. event is the only way to detect a selection is made. This applies to overflow menu in data table, too.

Given you found `click` event does not indicate the correct `event.target` for some browsers, you can use `mousedown` instead. BTW the you can listen to the event on any ancestor element of the overflow menu.

**Comment by gian1200** [comment]
Hi 👋, thanks for your answer. Maybe I didn't express myself correctly, I wasn't looking for a "custom event", just to check why a functionality stopped working on some browsers after a Carbon upgrade.

I did a little bit of "archeology" and found out a few lines that are responsible for this behaviour. When I remove them from `carbon-components.js`, the click event starts working again.

https://github.com/carbon-design-system/carbon/blame/master/packages/components/src/globals/js/mixins/track-blur.js#L38
```
_this.manage(on(_this.element.ownerDocument, focusoutEventName, function (event) {
    if (!event.relatedTarget) {
        _this.handleBlur(event);
    }
}, !hasFocusin));
```

I'm not really sure about the reason behind these lines, but by using `event.target` instead of `event.relatedTarget`, the overflow menu options seem to work fine.

Original PR: https://github.com/carbon-design-system/carbon/pull/3476
Maybe this is somehow related to https://github.com/carbon-design-system/carbon/issues/3835 (?)

**Comment by asudoh** [comment]
The code you referred to seems to ensuring the keyboard focus goes back to the trigger button when the overflow menu is closed, but disabling that code doesn't seem to let you get `event.target` in `onclick`. You can get it via `mousedown`, though.
