### ISSUE TITLE
Checked knobs for checkbox

### ISSUE THREAD

**Issue by ketanthakkar** [carbon-design-system/carbon#5284]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> When using checked in knobs for checkbox component we can't check/uncheck.

> **Expected:**
When user click on check box it should check/uncheck

## Steps to reproduce the issue

1. Set checked knobs for checkbox component.
2. Try to check/uncheck checkbox
3. Only show focus instead of check/uncheck

## Additional information

![image](https://user-images.githubusercontent.com/44302674/73950421-31a3d380-48fc-11ea-94ca-1bc37df9adbe.png)

**Comment by xxxle0** [comment]
Weird. I can reproduce it in my storybook, i dont have knobs check.

**Comment by tw15egan** [comment]
Not sure which storybook you are looking at, but we do not have a `checked` knob... We have a `checked` and `unchecked` story, and both of them seem to be working properly. Those focus styles are also not Carbon, so I'm guessing you are using an addon repo. I would recommend filing an issue with that addon.
