### ISSUE TITLE
[DatePicker mobile UI]: Size variants, theme, text position

### ISSUE THREAD

**Issue by Tokscull** [carbon-design-system/carbon#5297]
## What packages are you using?

- [x] `carbon-components: "^10.9.3"`
- [x] `carbon-components-angular: "^3.39.1"`

## Detailed description

- **Text:**  On the mobile phones the text is positioned at the top of the DatePicker, not in middle. 
- **Theme:**  On the iPhone 'light' theme doesn't work.
- **Size variants:** Maybe you add some size variants to DatePicker or remove default width or find some other ideas. Because in some situations it is look really bad. (On first screenshot I want to have DatePicker with width like search fields or even less).

**iPhone SE:**
![BlueBlueCar](https://user-images.githubusercontent.com/46087056/74015280-5b630600-49a1-11ea-976b-0f666c93562c.png)

**Xiaomi Redmi Note5:**
![Screenshot_2020-02-07-11-37-15-087_com android chrome](https://user-images.githubusercontent.com/46087056/74015290-60c05080-49a1-11ea-9530-ee6e16a6f065.jpg)

**Comment by tw15egan** [comment]
It seems like the application is not using an autoprefixer, as I am able to render the DatePicker component fine on my iPhone

![IMG_BE1BFD2A409B-1](https://user-images.githubusercontent.com/11928039/74063344-15a83c80-49a5-11ea-8d3f-b7f79dc04423.jpeg)

![IMG_C80FB1EDF90C-1](https://user-images.githubusercontent.com/11928039/74063484-599b4180-49a5-11ea-9ca8-6c01f945273b.jpeg)

**Comment by Tokscull** [comment]
I'm using Angular Carbon Design System 

![Storybook](https://user-images.githubusercontent.com/46087056/74131018-8002ec00-4bf4-11ea-9124-5b7be6c0f29e.png)

**Comment by tw15egan** [comment]
I'd suggest creating an issue over at https://github.com/IBM/carbon-components-angular, since this seems like an issue specific to the Angular storybook

**Comment by Tokscull** [comment]
But what about size variants? I think this problem not specific  only to the Angular storybook
