### ISSUE TITLE
Truncation issue about Tooltip

### ISSUE THREAD

**Issue by wangqunOne** [carbon-design-system/carbon#5298]
Now our project import the tooltip component. And we are using the version is v10.9.0. 
But it happen this issue and the screenshot is the following:
![ttt](https://user-images.githubusercontent.com/15885127/74116167-48dd0c80-4bed-11ea-9b68-1e7c6d2a7001.gif)

If the tooltip is on the right. I click it. Our message  character string will be cut off. I think you should confirm the stage can show normally. Thanks.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Did you mean to upload a screenshot?

**Comment by wangqunOne** [comment]
@asudoh I think the  blackbox of showing message should move to the left a little. Thanks.

**Comment by asudoh** [comment]
Thank you for updating the screenshot. The best option that's available as of today is changing the width of tooltip body via CSS, however, the request looks very close to what #3837 requests for.
