### ISSUE TITLE
Thank you for this project!

### ISSUE THREAD

**Issue by veeral-patel** [carbon-design-system/carbon#5306]
Hi! I don't have a feature request; I just wanted to thank you for creating and open sourcing this project. It has many well-designed components and it's really well documented. 

It's a project that'll save me a lot of time in my own projects.

Thank you so much! You've created a lot of value for the community by releasing Carbon.

(Feel free to close.)

**Comment by xxxle0** [comment]
🎉

**Comment by joshblack** [comment]
Hi @veeral-patel! 👋 Thanks so much for the kind words, we really appreciate it! 🙏
