### ISSUE TITLE
carbon-react Tooltip component's className prop has no effect

### ISSUE THREAD

**Issue by dicksonf** [carbon-design-system/carbon#5309]
Setting className prop on the Tooltip component has not effect on the outputted HTML.

The following code:
```
<Tooltip **className="some-class"**>
 <p>some text</p>
</Tooltip>
```

should generate the following div as :
`<div id="__carbon-tooltip-trigger_37za7e2cyiw" class="bx--tooltip__label **some-class**">...</div>`

But it generated the following where the **some-class** is missing in the class attribute:
`<div id="__carbon-tooltip-trigger_37za7e2cyiw" class="bx--tooltip__label">...</div>`

**Comment by tw15egan** [comment]
If you're trying to add a class to the trigger, it looks like you need to pass down the class via `triggerClassName`. `className` will add it to the actual tooltip element.
