### ISSUE TITLE
[icon button] add ghost icon button functionality to react

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5312]
We need to add a ghost icon button. This type of button is being used a lot within UIs when it's not the primary call to action on the page (provisioning experiences, options within a data table row @marceltrautmann ). The icon needs to have a default `icon-01` color with the option to switch to `icon-02` as well. 

---------------------------------------------------------------------------------------------------

Spec:
![md-672px-8 column](https://user-images.githubusercontent.com/43969356/74285348-4365ec00-4ceb-11ea-9e41-38736c8af1b8.png)

**Comment by tw15egan** [comment]
This should already exist, but let me know if we're missing something:

(knobs --> button kind --> ghost)
https://react.carbondesignsystem.com/?path=/story/buttons--icon-only-buttons

**Comment by laurenmrice** [comment]
Yeah I think we just want to not have the icon blue by default for the icon only button and have a icon-01 and icon-02 option.

People are using these throughout their designs and we recommend they use these token values for this kind of button rather than always using blue.

**Comment by tw15egan** [comment]
Okay, so for icon only ghost buttons, we want it to always be `icon-01`?  We can update the styles so that it defaults to that instead of blue when it is just the icon.

**Comment by laurenmrice** [comment]
correct!

**Comment by tw15egan** [comment]
PR incoming 🚀
