### ISSUE TITLE
UI shell components missing from XD file

### ISSUE THREAD

**Issue by veeral-patel** [carbon-design-system/carbon#5315]
Hey! I downloaded Carbon's XD file and noticed that the UI shell components missing:

https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base

Is this intentional? The UI shell is a fundamental part of any UI so it's important this is included!

**Comment by laurenmrice** [comment]
The Adobe XD kit is managed by Adobe, and I believe they are working on adding this to the kit. Next time we talk to them I will bring this up!

**Comment by veeral-patel** [comment]
@laurenmrice Thank you! Feel free to close.

As a workaround, I downloaded the Sketch files and imported them into Figma (didn't have a Sketch license).
