### ISSUE TITLE
Dropdown/Multiselect: Element within parent

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon#5318]
## What package(s) are you using?
Carbon React, current version

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description
Gif of issue
![Untitled](https://user-images.githubusercontent.com/21066152/74242670-54dbd380-4cac-11ea-953a-c4052427f11e.gif)
You can also see this occurring on the on the Carbon Design site itself, https://www.carbondesignsystem.com/components/dropdown/code
![dropdown](https://user-images.githubusercontent.com/21066152/74243019-f2370780-4cac-11ea-88db-40b65c8a0b74.jpg)

> Is this issue related to a specific component?
Multi-select, dropdown
> What did you expect to happen? What happened instead? What would you like to
> see changed?
Dropdown menus should not cause internal scrolls within their containers, but instead, appear on top of anything below them
> What browser are you working in?
Chrome, Safari, Firefox
> What version of the Carbon Design System are you using?
Current
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Maximo

**Comment by tw15egan** [comment]
You should be able to override the `overflow-y: auto` on .`bx--modal-content` as well as the `overflow: hidden` on `bx--modal-container`. Unsure if unsetting this on our end will have unintended consequences, but should resolve your situation.

**Comment by JordanWSmith15** [comment]
@tw15egan I'm a UX designer, not a developer, but I wanted to report this on behalf of my dev team. I guess I'm concerned that we need more of a "global" fix to this problem. The example in the Carbon Design System site, for example, wouldn't be fixed that way.

**Comment by abbeyhrt** [comment]
Talked with design about this problem and they agree that the dropdown should open on top of anything below them. There is also another issue tracking allowing the dropdowns to open up instead of down https://github.com/carbon-design-system/carbon/issues/4686

**Comment by JordanWSmith15** [comment]
Seems that the ability to open the combobox upwards is implemented, but not for the [Filterable version](https://carbon-addons-iot-react.com/?path=/story/multiselect--filterable), which is the one my product uses, so this issue is still valid. Any updates?

**Comment by tw15egan** [comment]
Good catch @JordanWSmith15, will add that in now
