### ISSUE TITLE
[NumberInput] Performance issue

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon#5319]
## What package(s) are you using?
https://react.carbondesignsystem.com/?path=/story/numberinput--default

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
This issue is effecting my product code, but it reproducible at https://react.carbondesignsystem.com/?path=/story/numberinput--default.

Desktop:
1. Go to https://react.carbondesignsystem.com/?path=/story/numberinput--default.
2. Click on the "Up" carrot five times at a medium speed to try to bring the value to 100. 
3. Click on the down carrot 10 times to bring the value back down to zero. 
Result: You will see that performance is slow. First click updates the value immediately, but more clicks cause a larger and larger lag

Mobile:
1. Go to https://react.carbondesignsystem.com/?path=/story/numberinput--default using a tablet or phone (actual device)
2. Change knob to "Mobile variant"
3. Click on the "Up" carrot five times at a medium speed to try to bring the value to 100. 
4. Click on the down carrot 10 times to bring the value back down to zero. 
Result: Performance is very poor and causes the browser to become frozen for up to 10 seconds. Some clicks are not registered.

> Is this issue related to a specific component?
NumberInput
> What did you expect to happen? What happened instead? What would you like to
> see changed?
It is very common for users to do quick taps when interacting with such a component, so performance should be smooth.
> What browser are you working in?
Firefox, Chrome
> What version of the Carbon Design System are you using?
Current
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Maximo

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - The stack trace in Performance tab in Chrome DevTools running such case shows it's from [`addon-actions`](https://www.npmjs.com/package/@storybook/addon-actions) Storybook add-on, notably one at [`src/containers/ActionLogger/index.tsx`](https://github.com/storybookjs/storybook/blob/next/addons/actions/src/containers/ActionLogger/index.tsx#L60-L72) that emits fired events from our component to add-ons pane.

That said, I believe Carbon `<NumberInput>` itself doesn't have a performance problem. You can see it at https://react.carbondesignsystem.com/iframe.html?id=numberinput--default. Feel free to let us know you still believe there is a problem in Carbon code.
