### ISSUE TITLE
Using animated svg icons

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon#5324]
### Summary
We need to use animated svg icons to show status in Cloud Pak for Data. 

### Justification
We have 3 animated svg icons need to be used as 'In progress' 'Loading' and 'Pending' in Cloud Pak for Data. How do we add/contribute these icons to Carbon?
User testing shows that using animated svgs help our users understand some of the statuses better. We are trying to find existing icons from Carbon's icon library that matches our use case but couldn't find any animated icons that can be used in our product. 

### Desired UX and success metrics

The animated svg icons are used as interim icons and will be changed to static icons when the process is done. They help users understand the current status of the progress. For example, 'In progress' icon needs to tell users the process is running properly. It will be changed to a 'Completed' or 'Failed' icon when the process is done. 

### "Must have" functionality

Svgs can be animated with embedded code that doesn't require developers to do extra work. 

### Specific timeline issues / requests

We are using our own animated svgs for 'In progress', 'Loading', and 'Pending' status in CPD for our April release. We can update these icons post-April if new icons are available by the end of March.

### Available extra resources

Our current status icons are posted in this GitHub page:
https://github.ibm.com/Sam-Ting/icpd-visuals/blob/gh-pages/Components/status-icons/_status-icons.md

**Comment by joshblack** [comment]
cc @laurenmrice for icon contribution :eyes:
