### ISSUE TITLE
Review status icons

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon#5325]
### Summary
Review status icons used in Cloud Pak for Data

### Justification
We have 10 status icons (including 3 animated svg icons to be used as 'In progress' 'Loading' and 'Pending') in Cloud Pak for Data.  We have tried to find existing icons from Carbon's icon library that matches our use case but couldn't find all the icons we need.

### Desired UX and success metrics

The animated svg icons are used as interim icons and will be changed to static icons when the process is done. They help users understand the current status of the progress. For example, 'In progress' icon needs to tell users the process is running properly. It will be changed to a 'Completed' or 'Failed' icon when the process is done. 

In most cases, only 3 - 5 status icons will be used in the same page. 
Running (static) and In progress (animated) use the same graphic but they will not appear on the same UI so there's no accessibility issue.

### Specific timeline issues / requests

We are using our own svgs in CPD for our April release. We can update these icons post-April if new icons are available by the end of March.

### Available extra resources

Our current status icons are posted in this GitHub page:
https://github.ibm.com/Sam-Ting/icpd-visuals/blob/gh-pages/Components/status-icons/_status-icons.md

**Comment by joshblack** [comment]
Hey there! :wave: Closing this out due to inactivity, feel free to comment and I can re-open!
