### ISSUE TITLE
[Pictograms]: "Chart bar" is inconsistent with other chart pictograms

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#5327]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The pictogram "Chart bar" doesn't have any axes whereas the  other chart pictograms have some.

![image](https://user-images.githubusercontent.com/28265588/74325336-b5404300-4d88-11ea-9c35-fcaeee39ab5c.png)

> What version of the Carbon Design System are you using?

10.9.3

## Steps to reproduce the issue

1. Visit https://www.carbondesignsystem.com/guidelines/pictograms/library
2. Search for "chart"

**Comment by joshblack** [comment]
cc @conradennis

**Comment by janhassel** [comment]
Hey, just following up. Are there any plans to adjust this pictogram?

**Comment by joshblack** [comment]
Hey @janhassel! 👋  This work is managed by brand, will try and forward it along!

cc @dudley-ibm

**Comment by dudley-ibm** [comment]
@conradennis these three bars are exactly one pixel away from the bottom grid. To add the axis lines would require some shuffling. I'll create an option.

**Comment by dudley-ibm** [comment]
@conradennis would either of these options work?
<img width="698" alt="Screen Shot 2020-07-01 at 7 38 42 PM" src="https://user-images.githubusercontent.com/54119397/86300969-9412ae80-bbd2-11ea-95da-5c696a1251ac.png">

**Comment by janhassel** [comment]
@conradennis @dudley-ibm Will one of the two options be included in an upcoming release?

**Comment by dudley-ibm** [comment]
@janhassel I'll include option 02 unless @conrad comments otherwise.

**Comment by janhassel** [comment]
@dudley-ibm Was this delivered yet? I just checked the Carbon Website and it still shows the one without axes.

**Comment by dudley-ibm** [comment]
@janhassel  Shortly after our discussion in August, we went through a structural breaking change for all the pictos. Looks like I only processed our Enterprise issues, which is why this particular issue in Carbon slipped through the cracks. The next scheduled release is in about a weeks time, so I'll make sure that outdated artwork that's up there right now gets replaced with our updated artwork.

**Comment by janhassel** [comment]
@dudley-ibm Great, thank you!

**Comment by dudley-ibm** [comment]
PR: https://github.com/carbon-design-system/carbon/pull/7718
