### ISSUE TITLE
Ghost button text should be left aligned

### ISSUE THREAD

**Issue by jsloyer** [carbon-design-system/carbon#5329]
## Title line template:
The button component with kind `ghost` has the button text center aligned. The text should be left aligned.

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
According to design the text in the ghost button should be left aligned.

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
all

> What version of the Carbon Design System are you using?
v10

## Additional information

![image (5)](https://user-images.githubusercontent.com/154126/74359413-3a2f5a80-4d91-11ea-82a2-e43678a42fc0.png)

**Comment by jrpomeroy** [comment]
I think this is actually an issue with the padding on the small ghost button, which is different from the other button types. You can see in this image the small ghost button underneath a small tertiary button and the text does not align.

![image](https://user-images.githubusercontent.com/18622709/74362197-e111f780-4d8d-11ea-892c-06c3657bd068.png)

The left padding on the small tertiary button is 12px and the left padding on the small ghost button is 16px (1rem).
