### ISSUE TITLE
Inline dropdown style inconsistency

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#534]
From https://github.com/carbon-design-system/carbon-components-react/issues/550

@bsonefeld 

## Detailed description

The Inline Dropdown hover state in code is inconsistent with the design specs.

> Is this issue related to a specific component?

[Inline Dropdown](http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=inline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

> What did you expect to happen? What happened instead? What would you like to see changed?

The Inline Dropdown hover should get a background color fill of `$field-01`.

### Expected Interaction: 
![dropdown-style-6](https://user-images.githubusercontent.com/11233508/35574819-755d4df0-05a0-11e8-908c-fd4af5da83c2.png)

### Current interaction: 
![fields](https://user-images.githubusercontent.com/11233508/35574872-94dd30a0-05a0-11e8-8e29-45eef2bbd121.gif)

CC: @tay-aitken

**Comment by tay-aitken** [comment]
This is a bug that needs to be fixed in code :)
