### ISSUE TITLE
Single buttons on modals should be half width

### ISSUE THREAD

**Issue by kylembrake** [carbon-design-system/carbon#5346]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

A single primary button inside a modal takes up the entire width of the modal. We've confirmed that the screenshot attached shows the correct styling of the button and the documentation on full-length buttons is incorrect.

> Is this issue related to a specific component?

Modals and Buttons 

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.7.4",
    "carbon-components-react": "^7.7.4",
## Additional information
![carbon-modal-bug](https://user-images.githubusercontent.com/39499740/73199465-e3742080-4102-11ea-8fef-cbe5d4825d39.png)

Our overriding styling: 
```
.bx--modal-footer {
  justify-content: flex-end;
  button.bx--btn--primary {
    max-width: 50%;
  }
}
```

**Comment by laurenmrice** [comment]
@asudoh It should not be full width if its one button in a modal, it should be 50%. The content needs to be updated on our website here.

**Comment by asudoh** [comment]
@laurenmrice Yeah I heard of spec update somewhere recently and my apologies for my stale memory on the spec.
