### ISSUE TITLE
Content behind open Modal is scrollable

### ISSUE THREAD

**Issue by mattalco** [carbon-design-system/carbon#5348]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
**When a Modal is in a class component and that class component is used in another component, the class mentioned above does not get added to the `body` tag. This might not be the only way to reproduce this case, but it was one I found that reproduced reliably.**

> Is this issue related to a specific component?
**Yes, `Modal`**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
**I expected the class `bx--body--with-modal-open` to be added to the `body`, which in turn contains `overflow: hidden` to prevent scrolling while the modal is open.**

> What browser are you working in?
**Edge (Chromium)
Chrome
Safari**

> What version of the Carbon Design System are you using?
**10.9.2 (latest)**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
**N/A**

## Steps to reproduce the issue
I have created two sandboxes to demonstrate a few things.

Case 1
-- 

1. This first sandbox almost works as expected. I see the class being added to `body` but it doesn't contain any styling to prevent the overflow. This might be because the sandbox is doing something weird, but I include this base case because I see the class getting in added.

https://codesandbox.io/s/react-carbon-modal-r1oq6

In my product code, in a case where the modal works properly, I see the class and the appropriate overflow styling.

<img width="560" alt="Screen Shot 2020-02-13 at 2 32 49 PM" src="https://user-images.githubusercontent.com/13972013/74472326-bdbf7900-4e6f-11ea-9565-6c02864c0369.png">

Case 2
--

2. In this second sandbox, I've created a class component that contains a modal, and then I use that class component on another page. I expect the `bx--body--with-modal-open` to be added to the `body`, but it isn't.

https://codesandbox.io/s/carbon-components-react-d70oo

## Additional Information
Thanks for looking at this. I don't *think* I've missed anything with using `Modal` properly, but that's always a possibility :)

**Comment by emyarod** [comment]
it looks like you are importing an outdated stylesheet (v10.3.2), but [the relevant fix](https://github.com/carbon-design-system/carbon/pull/3237) was released in v10.4

https://codesandbox.io/s/proud-voice-0e8h1

**Comment by mattalco** [comment]
Thanks @emyarod. Sorry that sandbox was so far out of date - I didn't think to check its package.json. We're using 10.9.2 in our product but still have the issue. Your sandbox works just fine however which points to it being something else.
