### ISSUE TITLE
ContentSwitcher inside form causes onClick on Enter

### ISSUE THREAD

**Issue by trusinaj** [carbon-design-system/carbon#5354]
**Issue**
If ContentSwitcher is used inside form, it became focused and clicks first value of first ContentSwitcher whenever we type Enter into textInput.

**Recreated issue**
https://codesandbox.io/s/great-mahavira-gp5sw

I guess ContentSwitcher wasnt intended for form use, but this behavior doesnt seem right. Is there possibility this could be fixed?

Thanks

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Would you try adding `type="button"` to each `<Swtich>` and see if it solves the problem for you?

**Comment by trusinaj** [comment]
That solved my problem, thanks for reply. I wasnt quite sure on why is this happening, but thanks for providing solution.

**Comment by tw15egan** [comment]
Going to close this as resolved, but feel free to reopen if you feel there is anything else you’d like us to do! 😊
