### ISSUE TITLE
IE11 Polyfills

### ISSUE THREAD

**Issue by sgurin** [carbon-design-system/carbon#5355]
Hi guys,

How to add IE11 polyfills into project. 
I found link for folder https://github.com/carbon-design-system/carbon/tree/master/packages/components/demo/polyfills but I cannot find that folder after  npm install -S carbon-components

Thanks a lot..

**Comment by asudoh** [comment]
Hi 👋 you can look for the corresponding polyfills for each. e.g. https://www.npmjs.com/package/custom-event-polyfill - Hope this helps!

**Comment by sgurin** [comment]
Hi @asudoh 

Thank you for your answer.

Can we use https://github.com/zloirock/core-js polyfill bundle? It is almost 600kb and I am worried about performance with so huge bundle.

I thought that we could add https://github.com/carbon-design-system/carbon/blob/master/packages/components/demo/polyfills/index.js from the demo but did not have luck with so many imports :(

**Comment by asudoh** [comment]
Though an application could import the whole `core-js`, I wouldn't recommend doing so, for the performance concern you pointed out.

BTW https://github.com/carbon-design-system/carbon/blob/master/packages/components/demo/polyfills/index.js has only 7 polyfills and 3 of them are just of `core-js`?

**Comment by sgurin** [comment]
@asudoh Yeap, 3 of them are for Core.js and others are custom. That is why I trying to find out how to import all recommend polyfill pack with one click into a project and not to import one by one from unsecured sources.

**Comment by sgurin** [comment]
@asudoh Hi

We found the solution and do not know is it correct or not.

What have we done:

- Thrown NPM we installed 3 packages: 

  https://www.npmjs.com/package/core-js 
  https://www.npmjs.com/package/custom-event
  https://www.npmjs.com/package/classlist-polyfill

- We took index.js file form there https://github.com/carbon-design-system/carbon/blob/master/packages/components/demo/polyfills/index.js and put that imports inside it https://prnt.sc/r4jpm6 so at the end we got polyfills.js https://codepen.io/JustCoded/pen/qBdNzZO

- Also we replaced imports with require (that was our main blocker) https://prnt.sc/r4jrau

Because of ES6 we include polyfill.js file into our Gulp WSK for Babel will transpile our ES6 into ES5 for browser that do not support ES6  https://prnt.sc/r4jthp

It works, and now the bundle is ~ **60kb**

From my point of view it would be better if all of the polyfills with main.js filed would be as NPM package that you can easily import into your project.

**Comment by asudoh** [comment]
You don't have to bring in all `core-js` polyfills, as the required ones are clearly listed at: https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/demo/polyfills/index.js

**Comment by sgurin** [comment]
Yep, we imported only polyfills from the list https://prnt.sc/r52g0g but I hove no idea how ES6 imports in Carbon Starter should work. We had to replace ES6 imports with Require because they did not work :(

**Comment by asudoh** [comment]
We use module bundlers, like WebPack/Rollup, to resolve the `import`s.

**Comment by sgurin** [comment]
We used our WSK https://github.com/justcoded/web-starter-kit but had no luck to import

**Comment by asudoh** [comment]
Seems that https://github.com/justcoded/web-starter-kit  is using `browserify` which doesn't seem to support ESM?

**Comment by sgurin** [comment]
Browserify supports ESM. There is an example of ESM in our WSK https://github.com/justcoded/web-starter-kit/blob/master/src/js/app.js that works :)
