### ISSUE TITLE
[Number Input] incorrect position with no label 

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#5358]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
 When reviewing PR https://github.com/carbon-design-system/carbon/pull/5347
We noticed that the number input jumps out of the div when No Label is selected and there is a value for the label and we lose 6px somewhere.

Ideally having no label selected would be visually the same no matter if there's a value in the label or not.

![image](https://user-images.githubusercontent.com/19270502/74554586-81e3ec80-4f1f-11ea-9c9c-477c9c1b5a7a.png)

## Steps to reproduce the issue

1. Go to https://react.carbondesignsystem.com/?path=/story/numberinput--default
2. Check `No label (hideLabel)`
3. See that the number input has moved up too far (outside div)
4. Delete everything in `Label(label)` and see that the number input has moved to the correct position.

**Comment by tw15egan** [comment]
It seems to have something to do with how the `bx--visually-hidden` classes position the visually hidden label content. When there is no label altogether, it is correctly positioned (however, I'm guessing that is an a11y violation)

**Comment by asudoh** [comment]
I saw a similar thing; When the label has `position:absolute` which is part of `bx--visually-hidden`, the top of helper text goes above the top of the number input's container. Seems that the helper text has a [negative margin](https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/src/components/form/_form.scss#L102), presumably to better align between label text and helper text. Probably it shouldn't be applied in "no label" scenario?
