### ISSUE TITLE
[TableToolbarSearch]: Visual bug around X when there is an input value

### ISSUE THREAD

**Issue by loganmccaul** [carbon-design-system/carbon#5370]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
<img width="676" alt="image" src="https://user-images.githubusercontent.com/7374889/74675835-13e73180-517a-11ea-9561-b8d778efe8d5.png">

There is a small visual bug when the TableToolbarSearch is `persistent` and there is content in the input. A white border should probably not exist next to the X.

Here's a CodeSandbox to reproduce
https://codesandbox.io/s/pedantic-resonance-ffc7n

**Comment by tw15egan** [comment]
Should be fixed in `v10.10.0` via https://github.com/carbon-design-system/carbon/pull/5145 👍

**Comment by tw15egan** [comment]
<img width="1189" alt="Screen Shot 2020-02-18 at 12 35 55 PM" src="https://user-images.githubusercontent.com/11928039/74732791-3f861c80-524b-11ea-9f55-d8070d5d8f0d.png">

**Comment by joshblack** [comment]
Going to close this out since v10.10 is released! Let us know if there are any other questions about this 😄
