### ISSUE TITLE
Contribution: City Icon Hamburg - Elbphilharmonie

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon#5371]
#### 1. Team name
IBM Studios Hamburg

#### 2. Icon name
City Icons / Hamburg / Elbphilharmonie

#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.
The alternative city icon is derived from the world famous Elbphilharmonie located at Hamburg harbour. It should be used for IBM Developer / IBM Garage location Hamburg.

#### 4. Box Link
https://ibm.box.com/s/5z49kionp55gnhs3x9uy2tcpo8ypouph

#### 5. Screen Shot

1.  Close-up screen shot of the icon with the pixel grid turned on
<img width="786" alt="Screenshot 2019-12-07 at 01 36 04" src="https://user-images.githubusercontent.com/47037236/70365919-2f89ae00-1894-11ea-8aed-b8bb2e7109e4.png">

**Comment by fabianklonsdorf** [comment]
@vpicone @joshblack that's the repo stated on that website: https://www.ibm.com/design/language/iconography/pictograms/contribute/#contribution-process

**Comment by joshblack** [comment]
Definitely not your mistake @fabianklonsdorf! Just something I needed to PR a fix for 😄 

PR up @vpicone https://github.com/carbon-design-system/design-language-website/pull/442

**Comment by silviohajdin** [comment]
@vpicone @joshblack - great, as this particular issue is now completed and can be closed.

**Comment by joshblack** [comment]
@silviohajdin I believe we'll want to add this into the pictogram library right?? Let me know if not. If that's the case we can use this issue to capture adding it to the library. If it's not, then totally fair!

**Comment by silviohajdin** [comment]
@joshblack - yes indeed, moved the commit of the pictogram into task https://github.ibm.com/brand/pictograms/issues/24 and we'll commit to the master pictogram library through there.

**Comment by joshblack** [comment]
Awesome! Sounds good 😄
