### ISSUE TITLE
Button size naming

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#5374]
Just a minor thing: Carbon has three button sizes (if you ignore the full-bleed version in the modals).
Where "Default" and "Small" are consistently used to describe the - well - default and small sizes 😀, the middle one is has three names:

*In the Sketch kit it's "Medium"*
![image](https://user-images.githubusercontent.com/28265588/74718655-f7f39680-5232-11ea-9e48-e54dc88e6a15.png)

*In code it's "Field"*
![image](https://user-images.githubusercontent.com/28265588/74718769-23768100-5233-11ea-9473-e0a64a001011.png)

*On the carbon website it's "Inline"*
![image](https://user-images.githubusercontent.com/28265588/74718799-338e6080-5233-11ea-8c1b-634d81edd8ef.png)

I can see that is hard to change the name in either the Sketch kit or code since it'd be a breaking change (although in code there could be a deprecation warning for a while).

**Comment by tw15egan** [comment]
This should also map to the text input / select / dropdown sizing conventions, which in `v11` will be `small`, `medium` / ` ` (default),  and `large` 

Related reading:

https://github.com/carbon-design-system/carbon/pull/5311
https://github.com/carbon-design-system/carbon-website/pull/845#issuecomment-577939803
https://github.com/carbon-design-system/carbon/pull/5076

**Comment by janhassel** [comment]
Thanks for the links!

**Comment by tw15egan** [comment]
PR is up: https://github.com/carbon-design-system/carbon/pull/8459
