### ISSUE TITLE
Table height variations for new data table features

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5377]
### Summary

This issue is to support short (32px) row heights for the new data table features referenced here:

- https://github.com/carbon-design-system/carbon/issues/5162
- https://github.com/carbon-design-system/carbon/issues/5161
- https://github.com/carbon-design-system/carbon/issues/4749
- https://github.com/carbon-design-system/carbon/issues/4687

We have designs and developer resources for this contribution. 

### Designs: 

**Filter display bar**

<img width="950" alt="Screen Shot 2020-02-18 at 9 09 27 AM" src="https://user-images.githubusercontent.com/39408106/74748598-671abc00-522e-11ea-8341-926bb9019155.png">

**Filter toolbar**

Row height adjustments should happen automatically since our toolbar is based on Carbon's toolbar.

**External filters**

<img width="1162" alt="Screen Shot 2020-02-18 at 9 12 32 AM" src="https://user-images.githubusercontent.com/39408106/74749782-4bb0b080-5230-11ea-80a6-2d406d0d12c9.png">

### Justification

The new data table offers users the ability to adjust row height, and the existing Carbon data table has several pre-built row heights. Any new data table functionality needs to accommodate the most common heights: 32px, 48px (default), and 64px.

Since we already built the 48px height, and 64px uses the same components, the main row height support we need to add is for the 32px table.

### Desired UX and success metrics

If a user switches the row height on a data table that is using new components such as the new filter panel and display bar, the entire table (including new components) must switch row heights.

### "Must have" functionality

Short (32px) and tall (64px) versions of the following new table components:

- [ ] Filter display bar
- [ ] Filter toolbar
- [ ] External filters

### Specific timeline issues / requests

This should be part of the expanded data table work for CloudPAL adoption and should be completed as soon as possible.

### Available extra resources

The dev lead for this project is @holmansze

**Comment by connor-leech** [comment]
Hey @vsnichols!

It looks like this is addressed and accepted in this issue: https://github.com/carbon-design-system/carbon/issues/4515 but I want to be sure this is what you need before closing this proposal.

**Comment by joshblack** [comment]
Hi there! 👋 Going to go ahead and close this one out since we haven't heard back in a bit. Feel free to comment and we can re-open!
