### ISSUE TITLE
Interactive tooltip not closing consistently on click across different browsers

### ISSUE THREAD

**Issue by Daniel-Schulz-Private** [carbon-design-system/carbon#5378]
## React tooltip

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> The tooltip is not closing when I click the button within the tooltip on Chrome.
> It does close (as expected?) on Firefox.

> I think the behavior should be consistent across browsers.
> I assume it is supposed to close.

> Tested on FF, Chrome

> carbondesignsystem version: whatever is leveraged here currently https://react.carbondesignsystem.com

## Steps to reproduce the issue

1. Navigate here https://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom
2. Open tooltbox
3. Click "Create" button
4. should do the same on Firefox and Chrome.

Not sure about the expectation. I think in the past clicking the button closed the tooltip window. This behavior stopped recently on Chrome.

## Additional information

- Try to click the button (red rectangle in screen shot)

![image](https://user-images.githubusercontent.com/51151716/74749281-35bfe180-526a-11ea-81ec-884eadfcde31.png)

**Comment by emyarod** [comment]
on Firefox 75 and Chrome 82 I see the same behavior after clicking the button inside the tooltip (the tooltip remains open)

does the issue occur for you on https://carbon-components-react.netlify.com/?path=/story/tooltip--default-bottom?

**Comment by Daniel-Schulz-Private** [comment]
I double checked. It seems
- on Mac: chrome and FF behave differently (FF does close, chrome doesn't)
- on Win: chrome and FF behave the same (both don't close)

**Comment by asudoh** [comment]
Just to add more context; @emyarod and myself ran some tests, and we found that tooltip is kept open with latest `master` whereas it's closed (upon content click) with some browsers in react.carbondesignsystem.com.

That said, wanted to double-check what you tested against is carbon-components-react.netlify.com instead of react.carbondesignsystem.com?

**Comment by Daniel-Schulz-Private** [comment]
I wasn't aware of the netlify page, here is what I see:
- carbon-components-react.netlify.com
  - MacOS: does not close on both FF and chrome
  - Win: does not close on both FF and chrome
- react.carbondesignsystem.com - MacOS: chrome and FF behave differently (FF does close; chrome doesn't)

**Comment by asudoh** [comment]
OK it confirms that the latest `master` has the expected behavior. Would you try our latest release? If it still closes the tooltip please wait for the next release that will come soon - Thanks!

**Comment by Daniel-Schulz-Private** [comment]
Just to make sure - what is the expected behavior? That the tooltip stays open?
Thanks!

**Comment by asudoh** [comment]
> what is the expected behavior? That the tooltip stays open?

Yes.

**Comment by Daniel-Schulz-Private** [comment]
I see.
Thank you for the fast response!
