### ISSUE TITLE
Progress Indicator Progress Step always truncates step label

### ISSUE THREAD

**Issue by samgoulden28** [carbon-design-system/carbon#5381]
### Summary

We are trying to implement a Progress Indicator but find the truncated text on labels to limit usability. As far as we could see there is no way to remove the truncation and have the steps fit the label size. 

This will be a design and development choice I believe. 

### Justification

Required by IBM designers, please contact me within IBM for more details.

### Desired UX and success metrics

The progress steps should display all the text input to the label if required.

### "Must have" functionality

The progress steps should display all the text input to the label if required.

### Specific timeline issues / requests

Yes, please contact me within IBM for more details. 

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

I have created a pull request with the required changes: 

https://github.com/carbon-design-system/carbon/pull/5380

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by reeteshsingh93** [comment]
Is this issue fixed?

**Comment by tw15egan** [comment]
PR is in progress (#5635)

**Comment by reeteshsingh93** [comment]
@tw15egan When can we expect this pr to be in?

**Comment by tw15egan** [comment]
The PR is still failing CI checks by an outsider contributor

**Comment by reeteshsingh93** [comment]
@tw15egan I see the CI checks are fixed now.

**Comment by reeteshsingh93** [comment]
In which version i can see this change?

**Comment by tw15egan** [comment]
It will be bundled in with the next minor release

**Comment by reeteshsingh93** [comment]
I tried pulling carbon-components@10.11.2 but still the label is truncated:

![image](https://user-images.githubusercontent.com/46310374/80562889-c18e8080-8a06-11ea-9a63-63907120c7f2.png)

**Comment by tw15egan** [comment]
Can you link to a CodeSandbox illustrating the problem?

**Comment by reeteshsingh93** [comment]
https://codesandbox.io/s/pensive-banach-fvq3o?file=/src/index.js
Text is getting trimmed in sandbox as well.
![image](https://user-images.githubusercontent.com/46310374/81888352-ccc4dd00-95be-11ea-9e41-d7896065e17d.png)

**Comment by tw15egan** [comment]
It is currently available the the `10.12.0-rc.2` release. Example: https://codesandbox.io/s/jolly-fog-lq0f3?file=/src/index.js
