### ISSUE TITLE
White theme variation data table

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5384]
### Summary

This issue is to support the creation of white themed version for the data table as well as new data table features referenced here:

- https://github.com/carbon-design-system/carbon/issues/5162
- https://github.com/carbon-design-system/carbon/issues/5161
- https://github.com/carbon-design-system/carbon/issues/4749
- https://github.com/carbon-design-system/carbon/issues/4687

We have designs and developer resources for this contribution. 

### Designs

**Table settings menu**

![image](https://user-images.githubusercontent.com/39408106/74761697-16ad5980-5242-11ea-8324-75221b6f82df.png)

**Filter panel**

![image](https://user-images.githubusercontent.com/39408106/74761666-09906a80-5242-11ea-8f70-750fa5372fea.png)

**Filter display bar**

![image](https://user-images.githubusercontent.com/39408106/74761675-0d23f180-5242-11ea-98cc-982b91b68c1e.png)

**External filters** (may not need work as should inherit toolbar coloring)

![image](https://user-images.githubusercontent.com/39408106/74761649-04cbb680-5242-11ea-8e90-e8c42777eb32.png)

### Justification

There are a number of cases on IBM Cloud where a table must appear on a white background. We want to make sure that any new data table features support this use case.

### Desired UX and success metrics

Users are able to filter and adjust table settings on a white themed table in the same way that they would on a gray10 theme table.

### "Must have" functionality

We need white theme support for the following components:

- [ ] Table settings menu
- [ ] Filter panel
- [ ] Filter display bar
- [ ] External filters (may not need work as should inherit toolbar coloring)

### Specific timeline issues / requests

This should be part of the expanded data table work for CloudPAL adoption and should be completed as soon as possible.

### Available extra resources

The dev lead for this project is @holmansze

**Comment by sstrubberg** [comment]
hey @vsnichols, now that we have released v11 with support for [in-line theming](https://carbondesignsystem.com/migrating/guide/design#inline-theming) it should give you the exact control you are looking for using data table.
