### ISSUE TITLE
Incorrect padding with small ghost Button

### ISSUE THREAD

**Issue by PatrickDuncan** [carbon-design-system/carbon#5387]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The inner padding is incorrect with the Button only when `size="small"` and `kind="ghost"`. When a normal button and the small ghost button are vertically aligned the padding difference is visible.

> Is this issue related to a specific component?

`Button`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the left padding to be the same for all buttons. As you can see the top buttons are aligned with the default of field size. Small has different padding

![Screen Shot 2020-02-18 at 12 31 56 PM](https://user-images.githubusercontent.com/6889074/74761793-a9ea8d00-524a-11ea-9a9f-1015a7e1af38.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.9.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IKS and design would like this to be fixed ASAP. It's quite easy to fix just remove the padding from:
```css
.bx--btn--ghost.bx--btn--sm
```

## Steps to reproduce the issue

1. Render a Button with `size="small"` and `kind="ghost"`

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/goofy-sanderson-0ybx0?fontsize=14&hidenavigation=1&theme=dark

**Comment by emyarod** [comment]
this will be resolved by #5334
