### ISSUE TITLE
What size should text be?

### ISSUE THREAD

**Issue by veeral-patel** [carbon-design-system/carbon#5388]
Hi, do you have any guidelines on choosing a text size? Is it just "choose the text size that seems appropriate"?

I have a page title and I can guess what its text size should be, but I was wondering if teams at IBM follow any specific rules on this.

https://www.carbondesignsystem.com/guidelines/typography/overview/#scale

**Comment by tw15egan** [comment]
The tokens used on [this page](https://www.carbondesignsystem.com/guidelines/typography/productive) are what we recommend using for web-based product design. 

Specifically, for headings, you can use [these tokens](https://www.carbondesignsystem.com/guidelines/typography/productive#headings)




As far as choosing which token to use, it would depend on where on the page the text is being placed, i.e. Headings towards the top (`h2` - 
`$productive-heading-04`) would use a larger token than a subheading (`h3` - `$productive-heading-03`) below it. Perhaps the usage on our website can be used as an example?

**Comment by veeral-patel** [comment]
@tw15egan Thanks! And how would I make use of these tokens when designing? I didn't notice components for each text size.

I've imported your Sketch file into Figma, if that helps.

**Comment by tw15egan** [comment]
I'll leave that one up to @carbon-design-system/design to answer 🙂

**Comment by aagonzales** [comment]
In Sketch the type tokens are saved as "text styles". I don't not know if Figma imports Sketch text styles. You can get the spec for each type token on the website however if you have to do it manually. 

You might find the getting start Sketch guide useful:
https://www.carbondesignsystem.com/get-started/design/sketch/#text-styles

![image](https://user-images.githubusercontent.com/11670886/74958296-5739de00-53ce-11ea-915e-bbf1e40a4593.png)

**Comment by veeral-patel** [comment]
@aagonzales Thanks!
