### ISSUE TITLE
Error install package

### ISSUE THREAD

**Issue by rcauchon** [carbon-design-system/carbon#539]
## Bug while running npm install on this package
bug in the package.json file

"dependencies": {
    "@hybrid-cloud/cirrus-styles-for-carbon": "^1.0.2",
    "carbon-icons": "^6.0.4",
    "flatpickr": "2.6.3",
    "lodash.debounce": "^4.0.8",
    "warning": "^3.0.0"
  },

2905 verbose stack Error: 404 Not Found: @hybrid-cloud/cirrus-styles-for-carbon@^1.0.2
2905 verbose stack     at fetch.then.res (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
2905 verbose stack     at tryCatcher (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
2905 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
2905 verbose stack     at Promise._settlePromise (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
2905 verbose stack     at Promise._settlePromise0 (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
2905 verbose stack     at Promise._settlePromises (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
2905 verbose stack     at Async._drainQueue (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
2905 verbose stack     at Async._drainQueues (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
2905 verbose stack     at Immediate.Async.drainQueues (C:\Users\rcauchon\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
2905 verbose stack     at runCallback (timers.js:672:20)
2905 verbose stack     at tryOnImmediate (timers.js:645:5)
2905 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
2906 verbose cwd C:\IBM-Bluemix\Carbon-Design-System\carbon-components
2907 verbose Windows_NT 6.3.9600
2908 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rcauchon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
2909 verbose node v6.11.3
2910 verbose npm  v5.6.0
2911 error code E404
2912 error 404 Not Found: @hybrid-cloud/cirrus-styles-for-carbon@^1.0.2
2913 verbose exit [ 1, true ]

> Is this issue related to a specific component? 

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in? 

> What version of the Carbon Design System are you using? 
This is happening on the master branch

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
It seems the error: `2905 verbose stack Error: 404 Not Found: @^1.0.2` is being caused by this line: `"": "^1.0.2",`.
