### ISSUE TITLE
Multiselect selection count not centered

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#5404]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

after making a selection in the multiselect component, the selection count chip is no longer vertically centered in all browsers

![image](https://user-images.githubusercontent.com/8265238/74933566-e41e7080-53a9-11ea-961d-8d8cfd8ea4f1.png)

related https://github.com/carbon-design-system/carbon/pull/5362

**Comment by dakahn** [comment]
Worth mentioning is this doesn't seem to be a problem in Windows 10 🤦‍♂ -- which explains why I didn't see it. dang

**Comment by emyarod** [comment]
my screenshot is from Windows 10 (see scroll bar)
