### ISSUE TITLE
Data table component styling tweaks

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5406]
## Data table component styling tweaks

This issue is to document styling tweaks for the new data table components being contributed to Carbon / CloudPAL by the Toronto dev squad.

## Issues to fix

**Note:** Holman these comments assume that we should show the gray 10 theme table by default (and that therefore rows etc should be white). 

**General:**
- [x] Rows and toolbar should be white 
- [x] Search should be left-aligned, and open/ enabled with hint text "Search table..." (except with external filters) 

**Settings toggle** 
[Please change name to "Settings menu"]

- [x] Settings menu should have white background
- [x] Icon and menu background should be one shape; fix dropshadow division
- [ ] Menu should not close if user clicks "reset" - COULD NOT CHANGE
- [ ] Menu reopens when try to close it by clicking settings icon
- [x] Change "Reset" to "Reset to default"

**External filters** 
Can we break this into two examples? One with 2 single select dropdowns and one with 2 multiselect dropdowns? Should not mix single select and multiselect.

- [x] Add labels to all filters
- [x] No spacing between label and filter
- [x] Filters (or their background colors) seem slightly misaligned with toolbar
- [x] Columns jump when apply and remove BOTH filter and search - CARBON expected behavior

**Filter display bar**
- [ ] Filter selection tags should use (very dark) "gray" tags from Gray 90 theme
- [x] Get rid of "clear filters" text and use standard right-aligned "x" 
- [ ] User needs to click on "x" click target to dismiss (not anywhere on tag) - CARBON issue https://github.com/carbon-design-system/carbon/issues/5419
- [ ] Tag "x" disappears on hover, should have background change - CLOUDPAL? Issue https://github.ibm.com/ibmcloud/pal/issues/1133
- [x] Spacing between tags should be 8px
- [x] Fix display bar padding

**Filter panel**
- [x] Search should be on left and should be open and enabled by default
- [ ] When filter panel is open, clicking on filter icon or outside panel should close it
- [x] Dropdown should not resize when a selection is made
- [x] Buttons should be 16px apart
- [x] If filter icon is last item in toolbar, grey line to right of icon should not appear when panel is open
- [x] Filter icon tooltip is missing it's pointer

---
### General: Rows and toolbar should be white

Actual: Rows and toolbar are gray

<img width="919" alt="Screen Shot 2020-02-20 at 9 06 40 AM" src="https://user-images.githubusercontent.com/39408106/74947367-5a2dd200-53c0-11ea-8130-e16c96416a90.png">

Expected: Rows and toolbar are white

<img width="848" alt="Screen Shot 2020-02-20 at 9 08 06 AM" src="https://user-images.githubusercontent.com/39408106/74947474-877a8000-53c0-11ea-8aae-bdd3f850c9e9.png">

### General: Search should be left-aligned, open/ enabled, with hint text "Search table..." 

Actual:

<img width="919" alt="Screen Shot 2020-02-20 at 9 06 40 AM" src="https://user-images.githubusercontent.com/39408106/74947573-aa0c9900-53c0-11ea-9831-c89e51f589e3.png">

Expected: (except with external filters)

<img width="848" alt="Screen Shot 2020-02-20 at 9 08 06 AM" src="https://user-images.githubusercontent.com/39408106/74947637-c14b8680-53c0-11ea-9a42-aac372eaaefc.png">

----

### Settings: menu should have white background (when used with gray 10 themed table)

Actual

<img width="272" alt="Screen Shot 2020-02-20 at 8 58 16 AM copy" src="https://user-images.githubusercontent.com/39408106/74947863-1c7d7900-53c1-11ea-9505-a284f20c54be.png">

Expected

<img width="218" alt="Screen Shot 2020-02-20 at 9 12 46 AM" src="https://user-images.githubusercontent.com/39408106/74948178-8bf36880-53c1-11ea-8935-6b5b62052b01.png">

### Settings: Icon and menu background should be one shape; fix dropshadow division

Actual

<img width="272" alt="Screen Shot 2020-02-20 at 8 58 16 AM copy" src="https://user-images.githubusercontent.com/39408106/74948364-d83ea880-53c1-11ea-827c-9b81d4ba6da7.png">

Expected

<img width="226" alt="Screen Shot 2020-02-20 at 9 21 36 AM" src="https://user-images.githubusercontent.com/39408106/74948806-6c107480-53c2-11ea-879f-ce915e8b9c7a.png">

### Settings: Menu should not close if user clicks "reset"

Actual

![menu reset close](https://user-images.githubusercontent.com/39408106/74948420-ebea0f00-53c1-11ea-8117-2d112f3a15cc.gif)

Expected: Keep menu open when user clicks reset

### Settings: Change "Reset" to "Reset to default"

Actual: 

<img width="247" alt="Screen Shot 2020-02-20 at 9 20 01 AM" src="https://user-images.githubusercontent.com/39408106/74948673-3f5c5d00-53c2-11ea-9e4d-1948814c4d07.png">

Expected:

<img width="226" alt="Screen Shot 2020-02-20 at 9 21 36 AM" src="https://user-images.githubusercontent.com/39408106/74948815-703c9200-53c2-11ea-99bc-981fd78df9b4.png">

### Settings: Menu reopens when try to close it by clicking settings icon

Actual:

![Settings close bug](https://user-images.githubusercontent.com/39408106/74948845-7af72700-53c2-11ea-8805-5314d7d3def0.gif)

Expected: Menu should close when user clicks settings icon

----

### External filters: Add labels to all filters

Actual: 

<img width="918" alt="Screen Shot 2020-02-20 at 9 23 21 AM" src="https://user-images.githubusercontent.com/39408106/74949015-be519580-53c2-11ea-9346-927c1efb110c.png">

Expected: Add label

<img width="523" alt="Screen Shot 2020-02-20 at 9 24 33 AM" src="https://user-images.githubusercontent.com/39408106/74949056-d1fcfc00-53c2-11ea-844c-cc657aaa7df1.png">

### External filters: No spacing between label and filter

Actual: It looks like there may be a little space between label and filter

<img width="918" alt="Screen Shot 2020-02-20 at 9 23 21 AM copy" src="https://user-images.githubusercontent.com/39408106/74949173-fb1d8c80-53c2-11ea-90c9-1da6d7b8651d.png">

Expected: Remove space if it exists

### External filters: Filters seem slightly misaligned with toolbar

<img width="892" alt="Screen Shot 2020-02-20 at 9 30 11 AM" src="https://user-images.githubusercontent.com/39408106/74949705-bb0ad980-53c3-11ea-91d2-89208fb1506f.png">

Expected: The toolbar edge should be smooth 

### External filters: Columns jump when apply and remove BOTH filter and search

Actual

![jumping column filter](https://user-images.githubusercontent.com/39408106/74949793-d4138a80-53c3-11ea-88a9-15251d56d318.gif)

![Jumping columns](https://user-images.githubusercontent.com/39408106/74949799-d70e7b00-53c3-11ea-8829-540d74c84a7c.gif)

Expected: Columns should stay in place when actions are performed

-----

### Filter display bar: Selection tags should use "gray" tags from Gray 90 theme

Actual:

<img width="920" alt="Screen Shot 2020-02-20 at 9 33 30 AM" src="https://user-images.githubusercontent.com/39408106/74949973-12a94500-53c4-11ea-9607-8a7ebce3ac9a.png">

Expected:

<img width="668" alt="Screen Shot 2020-02-20 at 9 33 51 AM" src="https://user-images.githubusercontent.com/39408106/74950007-1e950700-53c4-11ea-8f16-a4fb4f39eed7.png">

### Filter display bar: Get rid of "clear filters" text and use standard right-aligned "x" 

Actual

<img width="920" alt="Screen Shot 2020-02-20 at 9 33 30 AM copy" src="https://user-images.githubusercontent.com/39408106/74950087-39677b80-53c4-11ea-97ea-40acbf0a1a9a.png">

Expected

<img width="730" alt="Screen Shot 2020-02-20 at 9 34 57 AM" src="https://user-images.githubusercontent.com/39408106/74950272-79c6f980-53c4-11ea-9645-b897b063c419.png">

### Filter display bar: User needs to click on "x" click target to dismiss (not anywhere on tag)

Actual

![Tag click bug](https://user-images.githubusercontent.com/39408106/74950312-86e3e880-53c4-11ea-90a6-56d9e5f290a5.gif)

Expected: User needs to click on the "x" area click target to remove tag - THIS MAY BE CARBON

### Filter display bar: Tag "x" disappears on hover, should have background change

Actual:

![Tag disappearing x](https://user-images.githubusercontent.com/39408106/74951111-7f710f00-53c5-11ea-85b1-06fb2a4f21c6.gif)

Expected:

![carbon filter tag hover](https://user-images.githubusercontent.com/39408106/74951202-8435c300-53c5-11ea-93ba-8969d58dab1a.gif)

### Filter display bar: Spacing between tags should be 8px

Actual

<img width="920" alt="Screen Shot 2020-02-20 at 9 33 30 AM" src="https://user-images.githubusercontent.com/39408106/74951926-ac252680-53c5-11ea-9716-1d8ab5eed676.png">

Expected

<img width="699" alt="Screen Shot 2020-02-20 at 9 46 01 AM" src="https://user-images.githubusercontent.com/39408106/74952408-d4148a00-53c5-11ea-8f44-1f835516febc.png">

### Filter display bar: Fix display bar padding

Actual

<img width="163" alt="Screen Shot 2020-02-20 at 9 46 34 AM" src="https://user-images.githubusercontent.com/39408106/74952458-e5f62d00-53c5-11ea-932f-75c27e11bd5e.png">

Expected

<img width="280" alt="Screen Shot 2020-02-20 at 9 47 02 AM" src="https://user-images.githubusercontent.com/39408106/74952501-f6a6a300-53c5-11ea-9595-aeb3aedb6f9d.png">

----

### Filter panel: Search should be on left and should be open and enabled by default

Actual

<img width="894" alt="Screen Shot 2020-02-20 at 9 48 20 AM" src="https://user-images.githubusercontent.com/39408106/74952666-31104000-53c6-11ea-87a3-cde6a5da3e3d.png">

Expected

<img width="988" alt="Screen Shot 2020-02-20 at 9 49 00 AM" src="https://user-images.githubusercontent.com/39408106/74952726-47b69700-53c6-11ea-91cf-0d4c9fad3479.png">

### Filter panel: When filter panel is open, clicking on filter icon or outside panel should close it

Actual

![filter panel close](https://user-images.githubusercontent.com/39408106/74952882-88aeab80-53c6-11ea-8db4-b05acc340276.gif)

Expected: Filter panel should close if click on filter icon OR if click outside panel

### Filter panel: Dropdown should not resize when a selection is made

Actual:

![jumping dropdown](https://user-images.githubusercontent.com/39408106/74953061-c90e2980-53c6-11ea-9494-497dbf0a041f.gif)

Expected: Dropdown should not resize 

### Filter panel: Buttons should be 16px apart

Actual:

<img width="922" alt="Screen Shot 2020-02-20 at 9 53 55 AM" src="https://user-images.githubusercontent.com/39408106/74953630-813bd200-53c7-11ea-93d3-ea7ee2796278.png">

Expected

<img width="348" alt="Screen Shot 2020-02-20 at 9 54 36 AM" src="https://user-images.githubusercontent.com/39408106/74953641-84cf5900-53c7-11ea-9c70-5e1447b2dc73.png">

### Filter panel: If filter icon is last item in toolbar, grey line to right of icon should not appear when panel is open

Actual

<img width="140" alt="Screen Shot 2020-02-20 at 9 55 23 AM" src="https://user-images.githubusercontent.com/39408106/74953649-88fb7680-53c7-11ea-854e-343b2e8a4c70.png">

Expected

<img width="448" alt="Screen Shot 2020-02-20 at 9 57 02 AM" src="https://user-images.githubusercontent.com/39408106/74953674-9284de80-53c7-11ea-98d2-ff48286415d5.png">

### Filter panel:  Filter icon tooltip is missing it's pointer

Actual

<img width="156" alt="Screen Shot 2020-02-20 at 9 58 50 AM" src="https://user-images.githubusercontent.com/39408106/74953819-c6f89a80-53c7-11ea-9487-718a535c82a3.png">

Expected

<img width="444" alt="Screen Shot 2020-02-20 at 10 00 33 AM" src="https://user-images.githubusercontent.com/39408106/74953864-da0b6a80-53c7-11ea-9de5-0438d0e0524c.png">

**Comment by tw15egan** [comment]
Should this be broken into two issues, one for enhancements and one for bug fixes?

**Comment by joshblack** [comment]
Hey there! Going to close this one out since this component lives in Cloud PAL. Feel free to comment if this was done in error and I can re-open!
