### ISSUE TITLE
[disabled colors] investigate disabled-02 text "legibility" 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5407]
Several people have requested we make the disabled-02 token have a higher contrast so its more "legible" (in quotes because it still won't pass accessibility). Need to investigate the it for all themes.

![image](https://user-images.githubusercontent.com/11670886/74956611-fb6e5580-53cb-11ea-8cdc-481f19eadb69.png)

![image (31)](https://user-images.githubusercontent.com/11670886/74956631-032dfa00-53cc-11ea-9eb2-6a2db25fbef6.png)

![image](https://user-images.githubusercontent.com/11670886/74956962-7b94bb00-53cc-11ea-8a18-1d63dc84af4f.png)
https://ibm-studios.slack.com/archives/C0M053VPT/p1581442800399100

**Comment by aagonzales** [comment]
## Conclusion
Only need to update disabled-03 in the dark theme to address Mike's concern. Leaving the light themes as is for now.

| Token | Gray 90 | Gray 100 |
| ------ | -------- | ---------|
| `disabled-03`| Gray-40 `#A8A8A8`| Gray-50 `#8D8D8D`|

## To-do:
- [x] update kit tokens
- [x] create PR

**Comment by andreagmann** [comment]
@aagonzales Hi, folks on my team have been commenting on the lack of contrast of disabled elements on the gray 10 background. Could you please speak to that? [Here's an issue](https://github.ibm.com/PrivateCloud-analytics/Zen/issues/14353) that was opened against our devs.

**Comment by aagonzales** [comment]
Hey @andrea-gm. According to IBM Accessibility disabled states do not have to met contrast minimum. You can read about it in this slack post on their channel https://ibm-studios.slack.com/archives/C036P1CTN/p1549289845286600?thread_ts=1549264906.285600&cid=C036P1CTN

The visuals of disabled states is a fine line. It needs to look obviously disabled so the user doesn't mistakenly link on it and get frustrated with why is not working. Disabled states will also no be read by a screen reader so making them visual accessible will still not resolve it being accessibly to all users. I hope this answers your question.
