### ISSUE TITLE
[@carbon/type] Productive Heading 06 applies wrong values

### ISSUE THREAD

**Issue by rafaelmaiach** [carbon-design-system/carbon#5408]
## What package(s) are you using?
- [x] `@carbon/elements 10.9.3`
- [x] `carbon-components 10.9.2`
- [x] `@carbon/vue 2.22.0`

## Detailed description

> Describe in detail the issue you're having.

When applying the `productive-heading-06` mixin, it applies values different from the carbondesignsystem specification

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the css values are applied as they are specified in the carbon design system site

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

The latest

## Steps to reproduce the issue

1. Include productive-heading-06 to an element `@include carbon--type-style('productive-heading-06');` 
2. Check the CSS Styles applied for it and compare with the Carbon Design System specifications

## Additional information

Specification:
![image](https://user-images.githubusercontent.com/13542718/74963694-ea840b00-53f0-11ea-86d0-6025215f61be.png)

Styles applied:
![image](https://user-images.githubusercontent.com/13542718/74963713-f53ea000-53f0-11ea-8a98-9c9014461df1.png)

PS: The productive-heading-07 maybe is wrong too, as shown below:

Styles applied:
![image](https://user-images.githubusercontent.com/13542718/74963840-27500200-53f1-11ea-8e39-125076e36d38.png)

Specification:
![image](https://user-images.githubusercontent.com/13542718/74963855-2dde7980-53f1-11ea-9d2b-56673018bc8a.png)

**Comment by joshblack** [comment]
Hi @rafaelmaiach! :wave: I believe the website is out-of-date and the code packages should be considered the source of truth. We will make sure the website gets updated! Hope this helps!
