### ISSUE TITLE
[structured list] add background option

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5410]
Have an option to add a background to structured list.

![Artboard](https://user-images.githubusercontent.com/43969356/201714552-a8cb375f-0470-4637-b7d3-556e87e41f7d.png)

**Comment by laurenmrice** [comment]
Discussion in Slack:
![Screen Shot 2020-02-20 at 1 56 32 PM](https://user-images.githubusercontent.com/43969356/74973310-d2a88900-53e8-11ea-9a06-4030ddea5a55.png)

**Comment by tw15egan** [comment]
Blocked by: 

https://github.com/carbon-design-system/carbon/issues/1937
https://github.com/carbon-design-system/carbon/issues/2820
https://github.com/carbon-design-system/carbon/issues/5065

**Comment by tay1orjones** [comment]
Right now this has a `background: transparent;` on the parent/containing element. We just need to update it to use `$layer`.
