### ISSUE TITLE
[TableExpandedRow]: Unable to use nested <td>'s, does not retain layout of <tr>

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#5411]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When trying to nest `<td>`'s in the expanded section of a data table, the layout is not preserved from the parent `<tr>` and we get the following message in the console:
`Warning: validateDOMNesting(...): <td> cannot appear as a child of <div>.`

> Is this issue related to a specific component?

`<TableExpandedRow />`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Before upgrading Carbon, the layout of the table columns was the same as the parent `<tr>`

> What browser are you working in?

Chrome and Firefox

> What version of the Carbon Design System are you using?

v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

VPC UI

## Additional information

Link to line causing console message
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/TableExpandedRow.js#L45

### Before upgrade
<img width="1129" alt="Screen Shot 2020-02-20 at 10 54 32 AM" src="https://user-images.githubusercontent.com/7707326/74975985-eefef280-53f5-11ea-8ed4-77403072b092.png">
<img width="546" alt="Screen Shot 2020-02-20 at 10 54 25 AM" src="https://user-images.githubusercontent.com/7707326/74976002-f4f4d380-53f5-11ea-91fa-74ff202a0d36.png">

### After upgrade
<img width="1158" alt="Screen Shot 2020-02-20 at 10 54 44 AM" src="https://user-images.githubusercontent.com/7707326/74976017-fd4d0e80-53f5-11ea-8ca7-5058ef2cdb08.png">
<img width="615" alt="Screen Shot 2020-02-20 at 3 38 43 PM" src="https://user-images.githubusercontent.com/7707326/74976643-228e4c80-53f7-11ea-8602-35669cb0eae7.png">

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. Like https://github.com/carbon-design-system/carbon/issues/5131#issuecomment-578224594 shows - The expanded row is designed to span the whole row. I see some teams have come up with an alternate table UI, e.g. #2580, but they are rather seen as enhancements.

**Comment by emyarod** [comment]
would you be able to provide a reduced test case in Code Sandbox which shows this issue? it would help with creating a workaround, but it doesn't seem like we are supporting this use case out of the box

**Comment by asudoh** [comment]
Closing as inactivity and a guidance provided. Let us know if further assistance is needed. Thanks!
