### ISSUE TITLE
Contribution: Accessibility Pictogram Set 

### ISSUE THREAD

**Issue by varusgarcia** [carbon-design-system/carbon#5414]
#### 3. For our team at Aperto (part of IBM iX) we needed a pictogram set similar to[ microsoft inclusive toolkit](https://www.microsoft.com/design/inclusive/) in the IBM style. 

We ended up with twelve pictograms with most of them in female and male variation. They are based on the **Retail>Customer Service** and **People>Advocate** pictograms from the carbon system with a minor change:
![woman_gemetric](https://user-images.githubusercontent.com/9051787/75032515-0c40c900-54a9-11ea-821d-0c88b276ab47.png)
In red the **Retail>Customer Service** pictogram, in black the modified template for the female pictogram we used. We changed it because the body was squeezed and was different than the  **People>Advocate** pictogram.

Maybe it can be fixed/unified?
here is a sketch with some new versions where the body is not so squeezed:
[retail_customer-service.zip](https://github.com/carbon-design-system/carbon-icons/files/4236074/retail_customer-service.zip)

#### 4. Box Link
Sketch and SVGs: [accessibility-pictograms-set.zip](https://github.com/carbon-design-system/carbon-icons/files/4236157/accessibility-pictograms-set.zip)

#### 5. Screen Shot

1.  Grid: [accessibility-pictograms_grid.zip](https://github.com/carbon-design-system/carbon-icons/files/4236160/accessibility-pictograms_grid.zip)

2.  Context: [accessibility-pictograms_context.zip](https://github.com/carbon-design-system/carbon-icons/files/4236119/accessibility-pictograms_context.zip)

Here is an alternative [Mega link](https://mega.nz/#!08wS1YSQ!8c63dUpEoXMy7sztVZBwWB6i4Eh_SlcdDB8mTGyHxBI) with everything just in case :)

**Comment by varusgarcia** [comment]
Oh, ok. 
just fyi the link from the [pictogram-contribute page](https://www.carbondesignsystem.com/guidelines/pictograms/contribute) links to a [new issue](https://github.com/carbon-design-system/carbon-icons/issues/new) in the  carbon-icons repo

**Comment by joshblack** [comment]
cc @conradennis

**Comment by joshblack** [comment]
Going to close this out since it's been a while, for pictograms this is something the brand team can help out with!
