### ISSUE TITLE
UX bug: Filterable tag should have separate click behavior for tag body and "x"

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5419]
## Filterable tag should have separate click behavior for tag body and "x"

Carbon's filterable tag currently seems to use a single click behavior for the entire tag, which is problematic because in some use cases we want to be able to click on the tag body separately.

**Actual:** 

On the new data table filter display bar, clicking on the tag body (as opposed to the x) removes the tag. But this is not the experience a user would expect:

![Tag click bug](https://user-images.githubusercontent.com/39408106/75074513-782f2b80-54c1-11ea-8940-42878d954abb.gif)

In the future, we may want users to be able to click on a filterable tag to see all other items with that tag - and that is a use case that Watson Knowledge currently has.

Expected:

Only clicking on the "x" click target would result in tag being removed.

Consumer of component can decide what action if any results when click on tag body.

**Comment by aagonzales** [comment]
Agreed, only clicking the x should close/dismiss the tag.

**Comment by tdayton** [comment]
I agree with the need for separate controls for the separate behaviors. The current appearance supports the current behavior, by this looking like a single control with a two-part label. If the behaviors are separated, the appearances must be changed to make these look like separate controls. Maybe just a vertical bar separating the two labels?
