### ISSUE TITLE
Inline notification width does not honor page zoom

### ISSUE THREAD

**Issue by IdanAdar** [carbon-design-system/carbon#5426]
## What package(s) are you using?

- [x] `carbon-components` 10.9.2
- [x] `carbon-components-react` 7.9.2

## Detailed description

> Describe in detail the issue you're having.

When zooming the page, the inline notification size is not changing with the page, unlike other elements.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

For the inline notification size to update accordingly.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud

## Additional information

- Screenshots or code

Zoom at 100%
<img width="936" alt="df471d00-5719-11ea-93d9-7990656cb333" src="https://user-images.githubusercontent.com/7255583/75183856-09193780-574c-11ea-8e64-a19461afa02a.png">

Zoom at 110%
<img width="960" alt="e53cfe00-5719-11ea-8026-c603bbdc459f" src="https://user-images.githubusercontent.com/7255583/75183862-0b7b9180-574c-11ea-9787-8b0ab2e391c8.png">

**Comment by emyarod** [comment]
Can you create a [reduced test case](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) showing this issue? I am unable to replicate it

![Kapture 2020-02-24 at 14 34 33](https://user-images.githubusercontent.com/8265238/75189124-27167600-5713-11ea-8ecc-4727903d3792.gif)

**Comment by IdanAdar** [comment]
@emyarod See here: https://codesandbox.io/s/cool-williamson-8jvhn?fontsize=14&hidenavigation=1&theme=dark

1. Open preview in a new window
2. Here I needed to get to 160% for the issue to surface

**Comment by emyarod** [comment]
@IdanAdar you'll probably want to adjust the `max-width` values in your stylesheet

ref https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/notification/_inline-notification.scss#L31-L46

**Comment by IdanAdar** [comment]
We don't have any. Are you saying we should add max-width on the form or on the inline notification?

**Comment by emyarod** [comment]
yeah in order to override the component defaults (ref https://github.com/carbon-design-system/carbon/pull/1372 )

**Comment by asudoh** [comment]
Closing as a solution provided. Please let us know if further assistance is required. Thanks!
