### ISSUE TITLE
CodeSnippet action feedback tooltip truncated

### ISSUE THREAD

**Issue by Daniel-Schulz-Private** [carbon-design-system/carbon#5428]
## CodeSnippet component

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When I specify a longer text as feedback for the CodeSnippet component, the text gets truncated.

I tested with latest Firefox and latest Chrome.

I am seeing this issue with whatever version of Carbon/React is exposed here: https://react.carbondesignsystem.com/?path=/story/codesnippet--inline

## Steps to reproduce the issue

1. browse to https://react.carbondesignsystem.com/?path=/story/codesnippet--inline
2. In section "Knobs", field "Feedback text" enter a longer text
3. click the sample code snippet above labeld "node -v"
4. see the tooltip pop up.

The tooltip is truncated; it should not be truncated.

## Additional information

![image](https://user-images.githubusercontent.com/51151716/75249328-65c13480-57d6-11ea-8b74-ae0b9a48c80a.png)

**Comment by tw15egan** [comment]
Seems like we have a `max-width` on the tooltip text, not sure why that is there. PR incoming 🚀
