### ISSUE TITLE
HTTP 404 - route does not exist

### ISSUE THREAD

**Issue by ppillai7777** [carbon-design-system/carbon#5440]
When I'm navigating in the https://www.carbondesignsystem.com/, once in a while I will get the following error:

![image](https://user-images.githubusercontent.com/60336208/75294459-572a4b80-57dd-11ea-99c9-819bf55658d9.png)

**Comment by laurenmrice** [comment]
Sometimes this can happen because an update is being made to the site, bug fix, etc.. Depending on how it’s deployed, the site could go down for a few seconds at the time of publishing a new build. This should happen rarely though.
