### ISSUE TITLE
[number input] add 48px and 32px size options

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5441]
We need to have three different size options for number input since we are doing this for other form components.

--------------------------------------------------------------------------------------------------
![md-672px-8 column](https://user-images.githubusercontent.com/43969356/75294964-4c78b200-57ef-11ea-8880-17864db24119.png)

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/5374
