### ISSUE TITLE
A flat carbon-components-react entrypoint is not tree-shakeable

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5442]
While verifying v10.10 over in #5398, we noticed a regression in bundle size when using `carbon-components-react` along with Webpack. Notably, when we were using babel to compile our components then webpack picked up on `sideEffects: false` for module file paths and correctly inferred that they had no side effects.

In a single entrypoint, we run into a set of problems with assignment expressions. Consider the following situations:

_Note: all situations can be run in a Terser sandbox [here](https://rl6kl.csb.app/) to verify output_

```js
// Input
!function() {
  const MyComponent = function () {};
  MyComponent.propTypes = {};
}();

// Output (correct)
```

```js
// Input
!function() {
  const MyComponent = function () {};
  MyComponent.propTypes = {};
  MyComponent.defaultProps = {};
}();

// Output (multiple assignments deopts)
// https://github.com/terser/terser/issues/293
!function() {
    const MyComponent = function() {};
    MyComponent.propTypes = {}, MyComponent.defaultProps = {};
}();
```

```js
// Input
!function() {
  const MyComponent = React.forwardRef(
    function () {}
  );
}();

// Output (unable to infer if getter has side-effect)
React.forwardRef(function() {});
```

```js
// Input
!function() {
  const MyComponent = /*#__PURE__*/ React.forwardRef(
    function () {}
  );
}();

// Output (#__PURE__ annotation correctly tree-shakes)
```

```js
// Input
!function() {
  const MyComponent = /*#__PURE__*/ React.forwardRef(
    function () {}
  );
  MyComponent.propTypes = {};
}();

// Output (Assignment expression deopts)
/* */ React.forwardRef(function() {}).propTypes = {};
```

---

As a result of these situations, we need to update our build process before we can ship a single entrypoint generated by Rollup for our ESM and CJS bundles. We would need to make the following changes:

- Use a babel plugin or author components such that `propTypes` are assigned based on environment (`NODE_ENV === 'development'`) so that they are stripped in production builds
  - https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types with `unsafe-wrap` option
- Move to default arguments over `defaultProps`

**Links & Resources**

- Material UIs babel config: https://github.com/mui-org/material-ui/blob/master/babel.config.js#L29
- Tree shaking and static properties: https://github.com/alex996/react-css-spinners/issues/1
- https://github.com/naver/babel-plugin-no-side-effect-class-properties

**Comment by joshblack** [comment]
We're going to proceed with a non-flat entrypoint for the foreseeable future and leverage the `sideEffects` flag for webpack interop.

**Comment by leximarie** [comment]
@joshblack What does this mean for consumers? Do we need to import everything from "carbon-components-react/es/{componentPath}" for tree shaking to work? For large applications this seems like a burden.

Also it seems like if importing from "carbon-components-react" imports all of the components combined AND the individual modules.
<img width="603" alt="Screen Shot 2021-04-12 at 10 04 14 AM" src="https://user-images.githubusercontent.com/11201028/114416587-723d5380-9b76-11eb-91ef-2f75070910b9.png">

**Comment by joshblack** [comment]
Hi there @leximarie!

The project is currently set up to be tree-shaken with webpack because of the `sideEffects` flag. Most likely if something is not being dropped, there is some configuration issue or some CommonJS module that is being included.

Here's the result of a build using the stock create-react-app tool along with importing button:

**Snippet**
```js
import { Button } from 'carbon-components-react';

// Used in App component
```


![image](https://user-images.githubusercontent.com/3901764/114434410-999d1c00-9b88-11eb-8874-c7d4f562efd8.png)

![image](https://user-images.githubusercontent.com/3901764/114434440-a02b9380-9b88-11eb-89e4-4d57713ff274.png)

**Comment by leximarie** [comment]
@joshblack It looks like it works if I am only importing Button (possibly others, but I can't test every component), so are there components that break tree-shaking?

**Comment by joshblack** [comment]
@leximarie it may be that a component being used is dependent on `DatePicker` internally versus the application specifying it explicitly. If you could share some steps to reproduce the bundle/tree-shake deopt I can definitely take a look!
