### ISSUE TITLE
Process Indicator label width

### ISSUE THREAD

**Issue by ppillai7777** [carbon-design-system/carbon#5443]
How do I increase the spacing of the label? The label is Upload Documents but it is cut off.

See below:
![image](https://user-images.githubusercontent.com/60336208/75295520-ae312000-57df-11ea-8632-e6e71be1cd31.png)

**Comment by asudoh** [comment]
Hi 👋 you can do it by overriding our CSS. You can see what CSS to override by inspecting DOM: https://developers.google.com/web/tools/chrome-devtools/css/

**Comment by ppillai7777** [comment]
Yes, I already tried to override in my class as shown below. This works but with !important rule. Any other suggesion?
 
Style:
.cd-progress-step {
    width: 10rem !important;
}

Markup:
<ProgressIndicator currentIndex={currentDocTypeStepId}>
                    <ProgressStep
                        description="Step 1: Upload Documents"
                        label="Upload Documents"
                        className="cd-progress-step"
                    />

**Comment by ppillai7777** [comment]
I guess the markup was removed from the message so here is screenshot. 
![image](https://user-images.githubusercontent.com/60336208/75388611-23f9c200-589a-11ea-9c06-ff141156f257.png)

If possible I don't want to specify !important rule everywhere.

**Comment by ppillai7777** [comment]
I've resolved the issue by adding parent selector class.
