### ISSUE TITLE
Grid example page does not load

### ISSUE THREAD

**Issue by dstanich** [carbon-design-system/carbon#5454]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

We need some additional details on the grid classes that are available.  On the [Grid package README](https://github.com/carbon-design-system/carbon/tree/master/packages/grid) it refers to a live demo site which does not currently load: https://carbon-elements.netlify.com/grid/examples/preview/

## Steps to reproduce the issue

1. Open the Grid live demo site: https://carbon-elements.netlify.com/grid/examples/preview/

Console errors:
```
The stylesheet https://carbon-elements.netlify.com/grid/examples/preview/styles.scss was not loaded because its MIME type, “text/x-scss”, is not “text/css”. preview
SyntaxError: import declarations may only appear at top level of a module index.js:1
```

## Additional information

- Screenshots or code
- Notes

**Comment by Josh-Meurer** [comment]
It looks like this is still not working

**Comment by joshblack** [comment]
Hi there! 👋 Sorry about the delay, should be good to go now!
