### ISSUE TITLE
Proposal: Support for 48px versions of a wider range of components

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon#5455]
### Summary

'Tall' (sometimes also called 'extra large') styling support for some component types is available for _some_ components today, mostly inputs via the 'field size' feature (referenced in a sibling issue: #5448 ). This issue requests extending similar support for other interactive components.

### Justification

A good number of our matured products in Watson IoT that have traditionally not been Carbon, are moving towards full adoption. However, a portion of those larger offerings also have small-screen and touch requirements. 

Many of these requirements look like they can be met near immediately through use of the field size features 'extra-large' option referenced in issue #5448 , where others without this type of feature would also benefit from a larger size option for bigger targets.

### Desired UX and success metrics

The set identified where 48px versions would be immediately beneficial:

- [ ] Accordion
- [x] Buttons (default already available at 48px)
- [x] Content switcher
- [x] Date picker
- [x] Dropdowns (already seems to support xl which is 48px input)
- [ ] Overflow menu items
- [x] Number input
- [x] Searchbar (already seems to support xl which is 48px input)
- [ ] Tabs (default - container is already 48px)
- [x] Text input (already seems to support xl which is 48px input)

![Artboard Copy 2](https://user-images.githubusercontent.com/30671949/75388436-9bcfe880-58aa-11ea-9d9b-c9ad154e9619.png)

Note: We'd also make two minor optional recommendations for these 'larger' versions that:

- The spacing between the label and any input is adjusted from the current 8px to 16px, see below:
![Artboard](https://user-images.githubusercontent.com/30671949/75386334-1eef3f80-58a7-11ea-880e-a9a009b191d3.png)

- The default icon sizes used be set to 20px, rather than 16px
![Artboard Copy](https://user-images.githubusercontent.com/30671949/75386542-7db4b900-58a7-11ea-843f-bf48f4d88e40.png)
_(This also gets us around the thicker rendering of the 16px '+' icon at the default 48px button size)_

Note: As with #5448 , a naming convention would be beneficial for describing these various 'versions' of the inputs. Eg: Data table uses 'tall' for scales above the default, and I would recommend that this convention is used here too (rather than the 'extra-large' used currently in the field size prop). 

I can provide more extensive examples, sketch files with these already mocked up and in use in a library etc if required, as well as an internal repo issue link with more extensive documentation.

### "Must have" functionality

- The ability to set the above list of components to a size based on 48px height.

### Specific timeline issues / requests

Timelines being defined by the primary team in our unit that has these as a requirement. Like with everything, always, the sooner the better.

### Available extra resources

The IoT PAL team has a number of development resources working to support requests like these on its own timeline. Naturally when this requirement becomes 'due' we would like to ensure we are able to do this with core Carbon, rather than in the IoT PAL. CC @davidicus

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/5441

**Comment by tw15egan** [comment]
As stated here, in `v11` we definitely plan on using a consistent naming convention between components in regards to sizing: https://github.com/carbon-design-system/carbon/issues/5374#issuecomment-587497335

**Comment by lukefirth** [comment]
🎉 Great!

Could I get some insight into the scope of the plans around this? I interpret that we're going to get good coverage of 48px tall variants soon for the inputs (text, dropdown, number, date etc) through the addition of the small and large versions.

Should I split out the request currently bundled in this issue for the other non-input components, namely:
- Accordion
- Content switcher
- Overflow menu items
- Tabs

Or keep them together here with the rest?

**Comment by tw15egan** [comment]
I believe most of these components now support a variety of sizes, so I'm going to close this out. Feel free to reopen if we need to take another look.
