### ISSUE TITLE
HeaderNavigation disappears < 1057px

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5457]
Forget my own setup. Even in the Carbon website the demo for header navigation, the menu just entirely disappears on widths < 1057px

https://codesandbox.io/s/header-with-nav-v07hj?from-embed

Not sure why that is or if there is a prop to change this behavior, but unfortunately the API isn't very well documented at all so I wouldn't know. Please help.

**Comment by tw15egan** [comment]
Might be helpful to take a look at the storybook example located here:

https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation-and-actions

**Comment by ghost** [comment]
That's really weird ngl. Yet in the React tutorial it shows an example with no side menu

**Comment by ghost** [comment]
https://react-step-2--carbon-tutorial.netlify.com/

**Comment by tw15egan** [comment]
Seems like the tutorial is just using an older version of Carbon if I update to `10.9.3` and `7.9.3` the repositories link goes away on smaller screen sizes.

**Comment by ghost** [comment]
Well then the docs really need to be updated. Like I said there's a lot of holes in the documentation. I have to follow the tutorial in order to know I can use a react-router `Link` in `HeaderMenuItem` instead of the default HTML href. I'm assuming UI shell is no longer experimental considering the fact the SCSS styles work right out of the box. I'm not sure if the grid has to be explicitly installed to work either. There's just way too many holes.

The biggest problem is that for each "component" in the side menu:

a. There's nothing regarding expected/available props. We need a fully documented API so that we know HeaderName accepts a prefix and the actual text as a child not a prop, for example. I shouldn't have to follow an outdated tutorial in order to understand a single use case for a component.

b. Several "components" like Header and DataTable are comprised of several smaller components. And to be honest source examples only show specific use cases so I'm never going to know what is available and at my disposal. A set of components shouldn't be abstracted to a single component, nor should I have to dig into storybook to find a hidden link to a github readme and do this whole run around to get some basic docs on DataTable for example. Like MUI docs there should be a component examples/usage and component API or you can add a tab in addition to code/usage/etc. for a full documented API on all sub components related to that component group.

**Comment by joshblack** [comment]
Closing this as I believe @tw15egan has updated the tutorial! Let me know if this was done in error and I can re-open.
