### ISSUE TITLE
Max width grid does not appear centred on screen

### ISSUE THREAD

**Issue by gindik** [carbon-design-system/carbon#546]
Within the grid system: http://carbondesignsystem.com/style/grid/design

The option to restrict the width of the grid to 1600px by using the "max" class results in the grid being shifted to the left.

The issue can be seen/explored here: https://codepen.io/gabrielindik/pen/jZMKxX

**Comment by tw15egan** [comment]
As a workaround, you can just add `margin: 0 auto` to the `.max` class

**Comment by alisonjoseph** [comment]
I think you want to only add the `margin: 0 auto` at the largest breakpoint, otherwise you lose the 5% margin on the left/right at smaller screen sizes.
