### ISSUE TITLE
[DataTable] Possibility to apply custom filter for rows with Select All functionality - React

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#5465]
Possibility to apply custom filter for rows with Select All functionality.
Currently there is an option to provide custom filter function.
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/DataTable.js
![image](https://user-images.githubusercontent.com/17591704/75448777-24fb2400-596c-11ea-9eac-e1678d3561d1.png)

Function is called when filterInputValue is provided.

![image (20)](https://user-images.githubusercontent.com/17591704/75448916-5ecc2a80-596c-11ea-9e70-00f68de30e90.png)

This impacts how Select All works, when filterInputValue provided, it will unselect all rows, and selects only filtered rows.
![image (21)](https://user-images.githubusercontent.com/17591704/75449195-da2ddc00-596c-11ea-8d9f-334761086c5c.png)

I would like to **apply custom filter** function to DataTable, e.g. show only selected rows, filter by some custom row type (e.g. show rows with value under column ABC to be equal e.g. 'string' or 'number'), and any combination of these e.g. show selected rows with type string or number,
**and**
to have this custom filter function taken into account in handleSelectAll function.

Functionality is required in one of IBM product.

Please **provide information** how to achieve described behaviour with current DataTable implementation, or please **move this to feature requests**.

## What package(s) are you using?

    "carbon-components": "10.9.3",
    "carbon-components-react": "7.9.3",
    "carbon-icons": "7.0.7",

**Comment by tomkdgun** [comment]
Could someone answer this question, or modify to defect/enhancement ?

**Comment by tomkdgun** [comment]
Any update on this ? I just need a solution which calls custom **filterRows** function, even when **filterInputValue** is not set.
This could be new prop (boolean or custom object), which will be checked in similar way as currently filterInputValue.

**Comment by tw15egan** [comment]
I believe this issue is identical to another issue that was answered at the time:

https://github.com/carbon-design-system/carbon/issues/5605#issuecomment-598744901

> it might be more practical to implement this in a custom state manager and build with the table UI components (`Table`, `TableHeader`, `TableBody`, `TableRow`, `TableCell`, etc). I'm not sure if we will bake this into the `DataTable` component's state manager with the way it is currently architected, at least not before a major release

Going to close this one in favor of #5605

**Comment by marek5050** [comment]
Hello @tw15egan for some reason the solution in #5605 does not work anymore. Do we have another example? :D
