### ISSUE TITLE
[Tabs]: Design kit tabs do not match live code tabs

### ISSUE THREAD

**Issue by voranouth** [carbon-design-system/carbon#5467]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The tab in sketch design kit does not match the live coded tab--specifically the space from the baseline of the text to the top of the underline and both of the enabled and selected underline heights.

![image](https://user-images.githubusercontent.com/13204370/75461968-1f401700-5949-11ea-9d21-9ce320319c6e.png)
_This image is showing: Current (code), align:center, align:bottom, line-height:26px, design kit component_

Originally i thought it was because the text wasn’t aligned center vertically within the text box, but when I tried it out in code where i changed `display: flex`, `align-items: center`, and changed the border bottom from 3 px (live code) to 2 px (design kit), it still doesn’t match. 

> What browser are you working in?
- I am using `Google Chrome Version 80.0.3987.122`. Devs are using `Chrome` & `Firefox`.

> What version of the Carbon Design System are you using?
- I am using Carbon Design System version 10.9.0 design kit.
- Devs are using `carbon-components: 10.9.3` and `carbon-components-react: 7.9.3`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
- An important release date to keep in mind for `Watson Studio on CP4D 3.0` is **March 17**.

**Comment by laurenmrice** [comment]
- [x] The tabs should have a 2px/.125 rem bar underline, not 3. 
- [x] The text should be using `body-short-01` for inactive tabs and `productive-heading-01` for the active tab. 
- [ ] There should be 8px/.5rem spacing between the tab label and the bar underline.
