### ISSUE TITLE
[Modal] Code examples do not follow Style tab's structure

### ISSUE THREAD

**Issue by agrajag1042** [carbon-design-system/carbon#5468]
## Detailed description

On the Modal component page, the Style tab indicates a 48px/3rem bottom-margin on the content.  (On the second example shown, it's the 48/3 blue area below Placeholder Text).

On the Modal component page's Code tab, both the Vanilla and React examples do not follow this structure.  Instead there is a 2-rem padding-bottom on the last child of the content, and the content itself has a margin-bottom of 2.5rem.

I am implementing the Carbon design in an unsupported framework.  I need to know which is correct: the Style tab or the Code tab?  Is there a general rule to follow in situations like this?

**Comment by asudoh** [comment]
@carbon-design-system/design Any guidance...? Thanks!

**Comment by laurenmrice** [comment]
The style tab image is correct. We should be using a`spacing-09`token
