### ISSUE TITLE
Danger Buttons Updates

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#548]
- [ ] Remove the `small button with icon` and `button with icon` from the danger button section of the buttons page.
- [ ] Add in `primary danger button` only (not the icon based one) as well as `small primary`

**Comment by marijohannessen** [comment]
Issue moved to [carbon-design-system/design-system-website #173](https://github.com/carbon-design-system/design-system-website/issues/173) via [**ZenHub**](https://www.zenhub.com/)
