### ISSUE TITLE
Data table columns jump when user filters table using search (or new filter panel)

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5483]
## Data table columns jump when user filters table using search (or new filter panel)

This seems to be an issue with the base component, and can be observed in the react storybook if you try to search a table with a toolbar. https://carbon-components-react.netlify.com/?path=/story/datatable--with-toolbar

## Actual

![jumping columns - carbon react](https://user-images.githubusercontent.com/39408106/75555685-50c8e900-5a02-11ea-8735-4fef59cc84cf.gif)

I am not sure why it happens and it doesn't seem like expected behavior. The same thing happens when you filter using the new filter panel and it makes things feel jumpier than necessary.

![jumping column filter](https://user-images.githubusercontent.com/39408106/75555736-6c33f400-5a02-11ea-8231-efd41321cb54.gif)

## Expected

Columns stay in place when filter is applied.

**Comment by tw15egan** [comment]
Pointed out in slack that this is most likely due to the table columns being determined by the longest string of text. When you remove the largest string, it’s going to have to rerender the column widths based on the new longest string. Not sure if there is a way to prevent this unless we specifically set a width on each `td` cell

**Comment by joshblack** [comment]
Yeah, to echo what @tw15egan most likely this is browser-related for rendering the table and isn't something we can control without moving away from table markup and aligning to the grid or explicitly setting the width of cells.

I'm going to go ahead and close this out and label as wont fix. If we think this is something we need to revisit then we can definitely re-open and chat about it with everyone!
