### ISSUE TITLE
Not able to change color of filterable tag in Carbon react storybook

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5484]
## Not able to change color of filterable tag in Carbon react storybook (browser: firefox)

The color switcher knob works for the normal tag, but not for the filterable one. https://carbon-components-react.netlify.com/?path=/story/tag--filter

## Actual

<img width="1515" alt="Screen Shot 2020-02-28 at 8 31 58 AM" src="https://user-images.githubusercontent.com/39408106/75557136-1b71ca80-5a05-11ea-9b58-2876fb39cf09.png">

## Expected

Should be able to switch colors

**Comment by tw15egan** [comment]
Currently, the filterable tag is specifically set to `tag-theme($inverse-02, $inverse-01);`

@carbon-design-system/design, should filterable version have all color options available?

**Comment by emyarod** [comment]
ref https://github.com/carbon-design-system/carbon/issues/3318

I have been blocked on this issue for a while now, but https://github.com/carbon-design-system/carbon/pull/5382 was opened recently and is currently undergoing revisions

**Comment by laurenmrice** [comment]
Yes, the filter tag should have all color options. working on it in the #5382 pr. Eventually we will also be updating the hover colors to the calculations that Vince and Sadek come up with.

**Comment by tw15egan** [comment]
Going to close this in favor of https://github.com/carbon-design-system/carbon/issues/3318 then 👍
