### ISSUE TITLE
Firefox/ overflowmenu keep openning

### ISSUE THREAD

**Issue by haoyue2020** [carbon-design-system/carbon#5486]
## What package(s) are you using?

    "carbon-components": "^10.9.1",
    "carbon-components-react": "^7.9.1"

## Detailed description

In firefox 73.0 we use mouse click on overflow menu button, it opens, and we use mouse to re-click the same button, it will keep opening ( which should be able to be closed).

![overflowmenu](https://user-images.githubusercontent.com/61596754/75570265-13db1180-5a57-11ea-9ce2-8a1b6c0a20f3.gif)

**Comment by emyarod** [comment]
I'm unable to reproduce this in Firefox 73+ or other evergreen browsers on macOS and Windows. can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

![overflow menu trigger](https://user-images.githubusercontent.com/8265238/75581869-01011680-5a30-11ea-8bd3-5b7cd1750c54.gif)

**Comment by vsnichols** [comment]
@emyarod

You can see the problem in Firefox if you go to https://pages.github.ibm.com/ibmcloud/pal/carbon-components-react/data-table/code and click the settings icon on the first table in the page (settings).

**Comment by tw15egan** [comment]
I see the problem on the page, but I'm unable to reproduce locally. The menu opens on the first click and closes on the second. 

Without a link to a reproducible example on CodeSandbox there isn't much else we can do as it seems like an implementation issue.

**Comment by asudoh** [comment]
The problem doesn't reproduce in FF with the corresponding development environment of the page @vsnichols brought up. So I assume upgrading that page to the latest version of their code will fix the problem.
