### ISSUE TITLE
Dropdown - Disabled options and tooltips

### ISSUE THREAD

**Issue by PatrickDuncan** [carbon-design-system/carbon#5491]
### Summary

Hey, I would like `Dropdown` to have the ability for items to be disabled with a message attached as a tooltip. Currently, with `itemToElement` the various `Tooltip` components are cut off and it's not possible for an item to be unclickable.

Design and development

### Justification

The designs for the component I'm building required this feature. I have a workaround, but the design is preferred.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

The user would open a dropdown and see some items that are greyed out. When the user tries to click the greyed out item nothing happens. When the user hovers over the greyed out item they will see a message detailing succintly why it's disabled.

### "Must have" functionality

- [ ] Items must be disableable
- [ ] A tooltip should appear when hovered
  - It would be nice if the message could be item specific, but that's not a requirement for our design

### Specific timeline issues / requests

The workaround should be good enough for now.

### Available extra resources

I can get you in contact with our designers.

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon/issues/4949

**Comment by asudoh** [comment]
Hi 👋 seems that our designers are against the notion of disabled dropdown item. They have alterenatives for several possible use cases in this area. So @PatrickDuncan (apologies for being late on this) would you want to have your designer in sync with our designers? We can come back here with conclusions (once they are available) for others' reference.

**Comment by PatrickDuncan** [comment]
Hey @asudoh , thanks our designer is @roninnanaki. Our current workaround is to remove/filter all the items we want to disable. We then added a helperText label stating that it happened.

**Comment by asudoh** [comment]
Seems that inline notification is another alternative depending on the reason why the items should be filtered out. CC @aagonzales

**Comment by PatrickDuncan** [comment]
We thought of that as an alternative since it provides more visibility. It didn't go anywhere though

**Comment by tw15egan** [comment]
I believe due to a11y concerns, this is unlikely to be added. A keyboard user would not be able to view any tooltip on a disabled item since it would be removed from the tab order. Going to close this as resolved but feel free to reopen if you have an alternate solution
