### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [carbon-design-system/carbon#5494]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by aledavila** [comment]
Hi Dimitri thanks for including us! We consider Carbon a design system, and we actually do have sketch kits for not only our different themes, icons and other design resources.  You can take a look here https://www.carbondesignsystem.com/resources#theme-libraries. Let me know if you have other questions.

**Comment by dimitropoulos** [comment]
ahh! yes! what a silly thing for me to miss given the focus of your project! sorry bout that, heh.

all fixed up now :)

https://github.com/dimitropoulos/react-ui-roundup/commit/69d3cee11290866ae5c3574292c58f1ffb667846

**Comment by tw15egan** [comment]
@dimitropoulos thanks for stopping by to let us know! You've put in an awesome effort to consolidate resources from across the design system world. 

One other thing I'd like to point out is that we do have support theming / "Dark Mode". Here are a few links to our resources on the matter:

- [Using our themes](https://www.carbondesignsystem.com/guidelines/themes/#default-theme) 
- [Theme Package](https://github.com/carbon-design-system/carbon/tree/master/packages/themes)
- [Component Example](https://www.carbondesignsystem.com/components/data-table/code)

We also have spent some time on creating a "Theme sandbox", although it does need some updating. Maybe this will help to get us around to updating our theme playground. You can see it in action here:

- Theme Sandbox (https://themes.carbondesignsystem.com/?nav=button)

You can change themes/input custom colors buy hitting the menu icon in the top right. 

Related issue: https://github.com/carbon-design-system/carbon/issues/3460

Feel free to reach out if you need anything else. Going to close this out, but we really appreciate the shoutout 

![](https://media.giphy.com/media/ui1hpJSyBDWlG/giphy.gif)

**Comment by dimitropoulos** [comment]
ok, wow.  So, I think actually I _had_ seen the `themer` page via google while I was researching but I didn't see the light grey button in the top right so I concluded that the page was not a themer (like the others in the roundup).  I have a 32 inch monitor so for me, hahah, that button is over in the distance compared to the rest of the content on the left.  This definitely qualifies for a themer (I added it [here](https://github.com/dimitropoulos/react-ui-roundup/commit/077feff04b984d68363e16ad13ff92c87c30b2a1#diff-689359a243bbf68875a58dd2a07261ac), as well as the update to darkTheme - sorry bout that as well!) but if nothing else, I'd suggest maybe just forcing that drawer that's behind the button to be open by default (or at all times).  Looking at the other themers in the roundup, they all do this.

Also, thank _you_ for the care and dedication you've put into this projects.  I'm no designer, but I really really appreciate projects like this one that are much more than a set of tools, it's a set of design philosophies in action that evolve and adapt.  It's been nothing but a pleasure to get more exposure to many of these libraries but looking at your work has been especially fun for me.

Thanks!

**Comment by tw15egan** [comment]
100% agree with the feedback! Our old sandbox had that functionality ([see here](https://v9-themes.carbondesignsystem.com/?nav=accordion)), so it makes sense that the new one should have it as well. Thanks again for the kind words. Cheers!

**Comment by dimitropoulos** [comment]
oh wow this old one is great!  For me, and I may not be a representative sample of your target users, it's really great to just have all the components in one place in one page so I can see how they interact (rather than individual pages to click through).  Although, I can absolutely see how, the individual pages to click through the examples are really helpful, but perhaps you can do both by keeping the current themer but just adding one more page that is a "kitchen sink" assemblage?

If you want a ux test-dummy for anything like this in the future please feel free to drop me a line!
