### ISSUE TITLE
need VanillaJS docs to integrate Carbon components with blazor!

### ISSUE THREAD

**Issue by mouadcherkaoui** [carbon-design-system/carbon#5496]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

**Comment by mouadcherkaoui** [comment]
Hi,
I found those pages about [Carbon HTML components](https://the-carbon-components.netlify.com/?nav=data-table) but seems no-js related, however, I did some experiments on the browser console:
```
const bxDataTable = CarbonComponents.DataTableV2;
const bxOverflowMenu = CarbonComponents.OverflowMenu;
const bxModal = CarbonComponents.Modal;

var element = document.getElementById('my-table');
var table = bxDataTable.create(elment, {}); // need to investigate source files to know about the options

// for example for data table overflow menu to work you should also 
// initialize the OverflowMenu components

bxDataTable.init();
bxOverflowMenu.init();

var modal_element = document.getElementById("my-modal");
var modal = bxModal.create(modal_element, {});

bxModal.init();
modal.show({});
```

I didn't pay attention to this section [Get started Vanila](https://www.carbondesignsystem.com/get-started/develop/vanilla)

a demo of the data table!
https://nlayersapp-demo.azurewebsites.net/manage/users

and here is a page for the DataTableV2 components in blazor:

[NLayersApp.SampleProject.Shared.components.BxDataTableV2](https://dev.azure.com/cherkaouimouad/_git/NLayersApp.SampleProject?path=%2FNLayersApp.SampleProject%2FShared%2Fcomponents%2FBxDataTableV2.razor)

thanks!

**Comment by tw15egan** [comment]
Seems like you've got it working 👍 

Going to close this but feel free to leave a comment if you need us to do anything else 🙂

**Comment by mouadcherkaoui** [comment]
awesome framework 🥇
