### ISSUE TITLE
Please Help: SideNav Overlaps with Content

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5498]
I'm literally following the tutorial verbatim and I'm still getting overlap with the side navigation menu. 

![image](https://user-images.githubusercontent.com/11995299/75643011-8c82cf00-5c0b-11ea-8cd4-fbd0f3c64bd1.png)

I don't understand what's the point of a `Content` component that apparently doesn't automatically shift the content of the page to the side of the `SideNav` if expanded. Why do I need to specify some kinda of offset that doesn't even work

**Comment by asudoh** [comment]
Hi 👋 would you want to compare what you got with https://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation-actions-and-sidenav ? You can try using Chrome DevTools to inspect computed styles of various elements. Also would you want to try creating a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox?

**Comment by ghost** [comment]
Literally when I copy and paste the sample from the docs called header with sidenav that's what I'm getting

**Comment by ghost** [comment]
Ok apparently I had to remove the scss `$feature-flags` in order for it to work as expected. Even the appearance of the SideNav has drastically changed between the current version and the version in the examples. The documentation clearly needs a HUGE update. Too many breaking changes. Furthermore what's the point of a Content component which is a sibling to Header in  HeaderContainer if I have to manually use some grid class to move it from underneath?

**Comment by vpicone** [comment]
@jibberishclient thanks for bringing this up! 

We had a large number of folks go through the tutorial when it was first launched, but the number has tapered a bit sense. Having folks like yourself go through the tutorial is extremely valuable to us. While working on new features and bug fixes, it can be difficult to make time to freshen up older tutorials/docs. 

If you feel like chipping in, there’s an “edit in GitHub” link at the bottom of each page. Clicking it will get you right where you need to be for a quick PR.

**Comment by ghost** [comment]
I don't see how I can meaningfully contribute if my understanding is
derived entirely from trivial and error.

**Comment by vpicone** [comment]
@jibberishclient it looks like you resolved your issue here? Maybe open a PR with those changes, that way we have a starting point for discussions/revisions.

**Comment by ghost** [comment]
Basically I didn't specify the `$feature-flags` for `ui-shell` but that's only one of two issues. See #5523

**Comment by vpicone** [comment]
Thanks for opening the issues! If you need help getting started with a PR don’t hesitate to reach out. Otherwise, we’ll triage and get someone assigned to it when we have availability.

**Comment by ghost** [comment]
Not really familiar with any of that.

**Comment by tw15egan** [comment]
Dupe of #5611
