### ISSUE TITLE
A lot of the scss imports are incorrect.

### ISSUE THREAD

**Issue by selodev** [carbon-design-system/carbon#5499]
## What package(s) are you using?
carbon

- [ latest] `carbon-components`
- [ latest] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When compiling scss files to css using sass --watch, a lot of the scss file imports are incorrect. 
> Is this issue related to a specific component?
Nope.
> What did you expect to happen? What happened instead? What would you like to
> see changed?
I changed the name that are without underscore to underscore file name 
for example  @import '@carbon/layout/scss/breakpoint'; to  @import '@carbon/layout/scss/_breakpoint';
> What version of the Carbon Design System are you using?
latest
inside node_modules  running sass --watch scss:new_css

**Comment by asudoh** [comment]
Looks that this topic is of one from https://sass-lang.com/documentation/at-rules/import#partials:

>  You can leave off the _ when importing a partial.

Feel free to speak up if you are talking about anything else - Thanks!
