### ISSUE TITLE
Any plans to publish to `@carbon/icon-build-helpers` to npm?

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#5501]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Summary

In the README of the [`carbon/packages/icon-build-helpers`](https://github.com/carbon-design-system/carbon/tree/master/packages/icon-build-helpers) repo, it states that it is a private module. Would you consider publishing the module to `npm` so that it can be consumed externally?

**Comment by joshblack** [comment]
Hi @metonym! 👋 We've definitely considered it and would not mind at all making it public. Any specific features of this package that you're looking to leverage? 👀

**Comment by metonym** [comment]
Thank you for the quick response @joshblack 

For `carbon-icons-svelte`, we use the `build-info.json` file in conjunction with the `@carbon/icon-helpers` package to generate the Svelte icon components. We are following the same approach by [`carbon-icons-angular`](https://github.com/carbon-design-system/carbon-icons-angular/blob/36f07b01a69df428bbf60185c22db7abeb1c1f24/src/generate.js).

---

I suppose one solution would be to manually download and inline `@carbon/icon-build-helpers` in `node_modules`.

**Comment by joshblack** [comment]
@metonym sorry if I'm misunderstanding things here, what are you hoping to use from the icon-build-helpers package again? 👀

**Comment by metonym** [comment]
@joshblack We use the metadata from `build-info.json` to generate the Svelte components. The `build-info.json` was previously available in `@carbon/icons` v10.9.0.1-rc.0 and below.

Specifically, we rely on the following fields:

```
descriptor: { attrs, content },
moduleName
```

and pass them to the following methods from `@carbon/icon-helpers`:

```
import {
  formatAttributes,
  getAttributes,
  toString
} from '@carbon/icon-helpers';
```

**Comment by joshblack** [comment]
Ah got it, so the hope is to use the vanilla builder from that package to get the `build-info.json` that is needed?

**Comment by metonym** [comment]
@joshblack yes

**Comment by joshblack** [comment]
Got it! Sorry that took a bit 😂 I think we could go down the route of continuing to expose `build-info.json` if that'd be helpful. I think the only thing is that we can't confirm that it follows semver as it's primarily used for internal builds.

Publishing `icon-build-helpers` might be doable but wanted to check-in on the option above first!

**Comment by metonym** [comment]
That would be great.

Exposing `build-info.json` in `@carbon/icons` would definitely solve the problem, without having to publish the internal `icon-build-helpers`!
