### ISSUE TITLE
CodeSnippet focus indicator has pseudo element overlaying it

### ISSUE THREAD

**Issue by electrostaticfleece** [carbon-design-system/carbon#5507]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the code snippet component the focus indicator appears to be covered by a pseudo-element.

<img width="972" alt="Screen Shot 2020-03-02 at 3 42 34 PM" src="https://user-images.githubusercontent.com/16194732/75720640-7ec95a00-5c9c-11ea-9819-b47a84028a46.png">

> Is this issue related to a specific component?

Code Snippet

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect the pseudo-element to not cover the focus outline.

> What browser are you working in?

Chrome Version 80.0.3987.122 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

`10.10.0`

> What offering/product do you work on? 

IBM Cloud

## Steps to reproduce the issue

This is verifiable on the carbon components react storybook site here. Just click on the code snippet to focus it:

https://react.carbondesignsystem.com/?path=/story/codesnippet--single-line

**Comment by emyarod** [comment]
the most up to date preview can be seen here https://carbon-components-react.netlify.com/?path=/story/codesnippet--single-line

![image](https://user-images.githubusercontent.com/8265238/75721730-796d0f00-5c9e-11ea-869a-5fed5a82ba1e.png)

**Comment by emyarod** [comment]
closing as this is not reproducible on the latest version of Carbon (https://carbon-components-react.netlify.com/?path=/story/codesnippet--single-line)
