### ISSUE TITLE
As a user I would like to select items for batch processing matching multiple search criteria.

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#5511]
### Summary

As a user, I would like to be able to select for batch processing rows found using different search criteria.

Design issue, as the current UX does not allow search to be changed when a batch items are selected.

### Justification

Request in @carbon/vue components https://github.com/carbon-design-system/carbon-components-vue/issues/847

### Desired UX and success metrics

The search criteria can be changed after selecting an item for batch processing.

### "Must have" functionality

The search criteria can be changed after selecting an item for batch processing.

**Comment by joshblack** [comment]
cc @aagonzales should we treat this as a proposal or do you feel like we could answer now?

**Comment by aagonzales** [comment]
We don't have a current solution for this but it is something that is needed so I think we should accept the proposal and add it to our backlog to work on.

**Comment by andreagmann** [comment]
@aagonzales I was wondering if there has been any more thought or progress on this issue?

In CPD we have a use case for this in our Open Source Management piece, where the user will have hundreds of repos to choose from.

**Comment by aagonzales** [comment]
No, there has been no work on this. It is currently a low priority issue for us.

**Comment by sstrubberg** [comment]
This feels edge case as well as super gnarly from an implementation standpoint. Closing for now.
