### ISSUE TITLE
Progress Bar step labels look like a link tag but nothing happens when clicking on it

### ISSUE THREAD

**Issue by sabinead** [carbon-design-system/carbon#5515]
This is a usability issue. The labels of a step look like a link tag. As a user I would expect more information when clicking on the step label but nothing happens.

**Comment by emyarod** [comment]
one idea we could implement is remove the link hover styles unless we know that the progress steps can be interacted with, but I will defer to @carbon-design-system/design on what the desired behavior should be

**Comment by joshblack** [comment]
cc @laurenmrice

**Comment by laurenmrice** [comment]
I would be fine with removing the link hover style on the text if you can not interact with the progress steps. If you can interact with each step, then they should be present.
