### ISSUE TITLE
TextInput placeholder text needs ellipsis for long text

### ISSUE THREAD

**Issue by andrewvanheuklon** [carbon-design-system/carbon#5517]
The placeholder text does not get truncated when it overflows the input. It should overflow with ellipsis and have a tooltip the user can use to see the full text.

## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

In some languages, the placeholder text we are using overflows the TextInput, and there is no ellipsis to clue the user of a run-off. Nor can the user hover and view the full text.

> Is this issue related to a specific component?

TextInput

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?
Carbon react 7.9.0

## Steps to reproduce the issue

https://codesandbox.io/s/epic-herschel-s4ef8

## Additional information

![image](https://user-images.githubusercontent.com/22668712/75809338-42563680-5d4e-11ea-9605-928aede9ea35.png)

**Comment by emyarod** [comment]
cc @carbon-design-system/design about the tooltip behavior for overflowing placeholder text

**Comment by tw15egan** [comment]
For reference, if we want to implement this:

[Is it possible to ellipse placeholders/watermarks in HTML5?
](https://stackoverflow.com/questions/10556365/is-it-possible-to-ellipsize-placeholders-watermarks-in-html5/22178139#22178139)

**Comment by laurenmrice** [comment]
We would want to implement a hover to show the full text, like we did with dropdown items. But we won't show the ellipsis for inputs specifically.

**Comment by tw15egan** [comment]
Should the hover effect be for the placeholder or the actual text? We can add this in by just having a `title={placeholder}`, but not sure if this is something we want to be enabled by default.

<img width="403" alt="Screen Shot 2020-03-13 at 10 08 20 AM" src="https://user-images.githubusercontent.com/11928039/76643598-a1683800-6512-11ea-8970-6f4323f55aac.png">

**Comment by laurenmrice** [comment]
Oh, I would prefer to only show it if there is already text filled inside of the input that is overflowing. Not for placeholder. In general people should not be using really long placeholder text, but with translation I wonder if it would be an issue still?

**Comment by tw15egan** [comment]
Hmm, well the text input in uncontrolled, so we don't have access to the value inside the text input. Plus, the text input itself can scroll, so not sure its necessary unlike a static component like a dropdown. 

So do we just want to add ellipse to the placeholder text?

**Comment by laurenmrice** [comment]
ok. I wouldn't mind it showing up for both placeholder and filled in text if that is harder to control. I do not want to show an ellipsis.

**Comment by tw15egan** [comment]
Unless we want to make every single text input controlled, not sure this is possible. 

We do not handle the value of the text component, we let the HTML element "control" itself. To render the current text inside the title attribute, we would have to manage state for the component, and then pull it into the title attribute from there. 

Not sure this is worth the added value because the text input is scrollable thus any text can always be scrolled in to view.

**Comment by laurenmrice** [comment]
ohh okay got it 👍🏻, then I agree with you .

**Comment by tw15egan** [comment]
Trying to think of a solution for the original issue:

1) Ellipse the placeholder when it gets too long, provide placeholder tooltip when hovered over
2) DO NOT ellipse the placeholder, but provide placeholder tooltip when hovered over

Which would you prefer?

**Comment by laurenmrice** [comment]
2!
