### ISSUE TITLE
Data Table Sortable Header

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5518]
![image](https://user-images.githubusercontent.com/11995299/75813095-62d9bd00-5d5d-11ea-9f86-a67c5c8d5193.png)

If I set isSorted on DataTable this is what I'm getting contrary to the docs. Please help

**Comment by ghost** [comment]
There shouldn't be this offset on the sides

**Comment by joshblack** [comment]
Hi @jibberishclient! 👋 Could you help us identify the issue by filling out the template/providing steps to reproduce?

**Comment by ghost** [comment]
I literally copied and pasted from the docs.

**Comment by tw15egan** [comment]
Could you link to a CodeSandbox that illustrates the issue you're encountering?

**Comment by ghost** [comment]
Oh nevermind then, it looks like that offset is supposed to be there. I was expecting all the table headers to be directly adjacent with each other and flush to one another.

https://codesandbox.io/s/elated-cray-mk4of

**Comment by ghost** [comment]
While we're here though I would like to ask a few questions on the DataTable:

1. Is there a reason why row IDs have to be strings? My API returns integers.
2. Is there a nowrap prop of some sort?
3. The overflow of content isn't properly managed.

![image](https://user-images.githubusercontent.com/11995299/76634698-cb265c80-651c-11ea-8ef0-ebd229aaeb14.png)

**Comment by tw15egan** [comment]
**1)** Seems like we use a proptype of `string` for `id` throughout the codebase. Is there any reason why the integer can't be stored as a string? If you'd like to change the proptype to something else, you can throw up a PR to start a discussion around a possible prop name change. 

**2)** There isn't any prop to specify no wrap. You can add `whitespace: nowrap` if you don't want something to wrap. If you think it would be helpful to have this as a prop, and design signs off on the idea, a PR to add this functionality would be helpful!

**3)** Thanks for pointing out. Seems like we have an issue already documenting this (#4998).

**Comment by ghost** [comment]
I don't really use typescript but I'd imagine you can just make the id: any. There's no reason to constrict that.

**Comment by ghost** [comment]
https://react.carbondesignsystem.com/?path=/story/datatable--with-sorting

Wait aren't the headers supposed to be flush with one another?
