### ISSUE TITLE
Content switcher: Add example of Content Switcher with icons

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon#552]
Ref https://github.com/carbon-design-system/carbon-components/pull/549#pullrequestreview-95872785

The example can be in the same HTML file as the original Content Switcher as it's not really a variation but an enhancement. So, on the website, it can like in the same section as the old Content Switcher.

**Comment by alisonjoseph** [comment]
added in v8.15.0 of `carbon-components`
