### ISSUE TITLE
Danger buttons do not pass the color contrast check on $ui-02

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon#553]
<img width="380" alt="screen shot 2018-02-12 at 1 27 15 pm" src="https://user-images.githubusercontent.com/5447411/36115449-bcd0d212-0ff8-11e8-84a4-6f00d4684ffa.png">

Noticed that this does not pass during the React a11y audit.

**Comment by bsonefeld** [comment]
@tay-aitken something to keep in mind as we're looking through colors!

**Comment by tay-aitken** [comment]
@marijohannessen Im addressing this in my color epic in carbon-issues [#546](https://github.ibm.com/Bluemix/carbon-issues/issues/546)

**Comment by tay-aitken** [comment]
@marijohannessen Im addressing this in my color epic in carbon-issues [#546](https://github.ibm.com/Bluemix/carbon-issues/issues/546)
