### ISSUE TITLE
Nightly Release has been failing for a couple of weeks

### ISSUE THREAD

**Issue by Dani7B** [carbon-design-system/carbon#5530]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

I don't know if anyone noticed but I keep receiving an e-mail warning me every night that the night released failed (https://github.com/carbon-design-system/carbon/actions/runs/49168646).

**Comment by joshblack** [comment]
Hi @Dani7B! 👋 Definitely have noticed this and am trying to figure out why 😞 are you receiving these notifications from watching the repo or from a fork that you have made?

**Comment by joshblack** [comment]
Hopefully made a fix upstream, going to close this out and will re-open if it fails again tonight!

**Comment by Dani7B** [comment]
Hi @joshblack , I was receiving the notification form a fork but also noted it on the main project. The fix upstream seems to work for me. Thanks 👍

**Comment by Dani7B** [comment]
And they're back... :-(

**Comment by joshblack** [comment]
Noticed this too 😭 you can definitely disable actions on your local fork while we try and figure this out upstream!
