### ISSUE TITLE
Tooltips: Port over hoverable tooltip support to Carbon Vanilla

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#5534]
https://github.com/carbon-design-system/carbon/issues/3616 contains the request. It was added to Carbon React in https://github.com/carbon-design-system/carbon/pull/5323.

Can this feature be added to the Vanilla package so non-React users can have the same UX.

**Comment by emyarod** [comment]
the PR you referenced (#5323) adds the feature to vanilla. is there an issue with the implementation?

**Comment by elizabethsjudd** [comment]
@emyarod , Is there a place I can verify this? I tested on the site and it didn't work and th vanilla.carbondesignsystem.com site was returning a 403.

**Comment by emyarod** [comment]
yeah our vanilla netlify previews were disabled recently, but here is a code sandbox I made with the latest vanilla version: https://codesandbox.io/s/naughty-engelbart-0pdog @elizabethsjudd

**Comment by elizabethsjudd** [comment]
I still can't seem to hover over the tooltip well. (I can' kind of hover over the caret but that's such a small target).
[Screen Recording 2020-03-06 at 11.30.28 AM.mov.zip](https://github.com/carbon-design-system/carbon/files/4299301/Screen.Recording.2020-03-06.at.11.30.28.AM.mov.zip)

**Comment by emyarod** [comment]
my mistake, there was a bug with how I instantiated the components in my sandbox, the demo should be correct now

![tooltipdefn](https://user-images.githubusercontent.com/8265238/76103929-247c1200-5f98-11ea-8966-4ed1bec2e773.gif)

**Comment by elizabethsjudd** [comment]
@emyarod which browser are you using? I've cleared cache and still can not replicate the behavior you're demoing. I'm using Chrome v80.0.3987.132

**Comment by emyarod** [comment]
@elizabethsjudd the previous recording was on Windows 10 (either Firefox 75 or Chrome 80), here is the Code Sandbox on Chrome 80 on macOS (same behavior in local dev env as well for both Firefox and Chrome)

![Kapture 2020-03-09 at 13 18 57](https://user-images.githubusercontent.com/8265238/76244721-9eb2cd80-6208-11ea-9f3a-04a9881f0683.gif)

**Comment by elizabethsjudd** [comment]
@emyarod I'm still not having any luck replicating this. Can you hit me up on slack (`@liz.byrne`) so we could do a quick screen share or something.

**Comment by tw15egan** [comment]
FWIW I'm also able to select the text using @emyarod's CodeSandbox link

**Comment by emyarod** [comment]
closing as resolved after discussing with @elizabethsjudd earlier!
