### ISSUE TITLE
Pictogram Contribution

### ISSUE THREAD

**Issue by mdesign-github** [carbon-design-system/carbon#5539]
Hello to whom know concern, I am a design team lead in MSC-Japan, one of designer in my team created a new pictogram icon of "gift box". Please check the attached file, and If possible please put it into the IDL. If it's works well, we'd like to keep contributing for designing icons, cause we will have same opportunity to create new icons in our daily work. Thank you!
[gift box.svg.zip](https://github.com/carbon-design-system/carbon/files/4290542/gift.box.svg.zip)

Hiro

**Comment by emyarod** [comment]
cc @carbon-design-system/design

**Comment by laurenmrice** [comment]
@conradennis

**Comment by conradennis** [comment]
@mdesign-github thanks for your contribution. The proportions of the pictogram need some work but we can get this into the library once it's refined. Just a heads up, the pictogram production team has a large backlog of pictos and new contributions likely will not be added to the library for some time

**Comment by mjabbink** [comment]
@conradennis we need to move the issue here:
https://github.ibm.com/brand/pictograms/issues

**Comment by conradennis** [comment]
@mjabbink issue moved to the picto repo: https://github.ibm.com/brand/pictograms/issues/29

**Comment by mdesign-github** [comment]
Hi there, Thanks for open the new issue.

**Comment by joshblack** [comment]
Hi there! Going to close this issue out due to inactivity. Feel free to comment and I can re-open!

**Comment by chrisconnors-ibm** [comment]
dupe of https://github.ibm.com/brand/pictograms/issues/29
