### ISSUE TITLE
CSS reset should also replace with Watson defaults

### ISSUE THREAD

**Issue by ollie-o** [carbon-design-system/carbon#554]
Original issue here: https://github.com/carbon-design-system/carbon-components-react/issues/601

We have had problems in our project with the over-zealous file [_css--reset.scss](https://github.com/carbon-design-system/carbon-components/blob/f307229a33bd751ead73285d1412c81c4200f4f9/src/globals/scss/_css--reset.scss). It seems to have been copied-and-pasted from http://cssreset.com/scripts/eric-meyer-reset-css/.

The original author of the reset script says:
> I don’t particularly recommend that you just use this in its unaltered state in your own projects. It should be tweaked, edited, extended, and otherwise tuned to match your specific reset baseline. **Fill in your preferred colors for the page, links, and so on.**

I would definitely suggest following the author's advice. The file should perform 2 roles to ensure consistency:
1) Cancel out default browser styles
2) Override those styles with the preferred Watson style

However, for many tags, it only performs (1) and fails to perform (2).

There is a good example of a previous fix [here](https://github.com/carbon-design-system/carbon-components/issues/532). Unfortunately that was only for the `<sup>` tag.

It would prevent many future issues (and we would be very grateful) if you could take a moment to check what other html tags could have this problem. A list from my personal experience is:
- `<li>`
- `<pre>`

But I'm sure there are more, so please take a look!

**Comment by ollie-o** [comment]
@shinytoyrobots @marijohannessen Just wondering why nothing was ever done with this issue.

As far as I can tell it's actually a pretty valid concern. If you check the discussion on the original issue here, you can see that there was a consensus that it's worth handling: https://github.com/IBM/carbon-components-react/issues/601

@joshblack Had said in February:

> Thanks so much for making that issue! We really appreciate it 😄
> Hopefully we'll have that fixed soon!

So what changed? Why no action on this one?

**Comment by asudoh** [comment]
@oliverodaa While other people may have better background wrt your question, a couple from mine - You can set `$css—reset: false` to disable our reset style, and you can apply your preferred reset style. Though changing reset style tends to be breaking changes and we cannot do in our minor releases, feel free to send PR(s) in our way so we can see if there will be a better reset style for ours. Thanks!
