### ISSUE TITLE
Simplification of developer onloading with Gitpod

### ISSUE THREAD

**Issue by JesterOrNot** [carbon-design-system/carbon#5540]
### Summary

Simplify contributor onboarding with Gitpod a free online IDE based on VSCode

### Justification

This will allow new contributors to see the README click the link and start coding with an editor ready, dependencies and tests will also run immediately or even before see [the prebuild documentation](https://www.gitpod.io/docs/prebuilds/)

### Desired UX and success metrics

The UX is for the contributor to be able to contributor to well contribute without the friction of setting up the development environment

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

* A `.gitpod.yml` file will be checked into source control to define the experience
* And a `.gitpod.Dockerfile` for cross-env

### Specific timeline issues / requests

I can have this done within in a few days, but potential merging can be delayed as needed

### Available extra resources

If you want to check it out see [the docs](https://www.gitpod.io/docs/)

**Comment by tw15egan** [comment]
This seems pretty interesting. I'm unfamiliar with Gitpod, but the potential benefits sound really great. If you have time to submit a PR to check it out that would be great 👍

**Comment by JesterOrNot** [comment]
Hey, question do you have any VSCode extensions you would want me to add?

**Comment by JesterOrNot** [comment]
Just let me know. I'll send the PR, to give a bit of a baseline

**Comment by JesterOrNot** [comment]
Hmm..wait when adding the badge to the README it breaks the tests

**Comment by joshblack** [comment]
Closing based off comment on Pull Request 👍
