### ISSUE TITLE
viewBox is removed when it's "0 0 width height"

### ISSUE THREAD

**Issue by carsonb** [carbon-design-system/carbon#5542]
It looks like the default `svgo` process is to remove any viewbox that is `0 0 width height` as a way to save bytes. When the viewbox isn't specified, it makes resizing SVGs a lot more difficult.

It would be swell if the [gulp command](https://github.com/carbon-design-system/carbon-icons/blob/master/gulp-tasks/shared/build.js) disabled the `removeViewBox` plugin.
Happy to offer a PR if you're cool with a third party contributing one!

**Comment by joshblack** [comment]
Hi @carsonb! 👋 Unfortunately `carbon-icons` is our older project for iconography and has been replaced by [`@carbon/icons`](https://github.com/carbon-design-system/carbon/tree/master/packages/icons) and [`@carbon/icons-react`](https://github.com/carbon-design-system/carbon/tree/master/packages/icons-react)

In these setups, we do have `removeViewBox` disabled which should help to address this! https://github.com/carbon-design-system/carbon/blob/master/packages/icon-build-helpers/src/builders/vanilla/svgo.js#L137

**Comment by carsonb** [comment]
Understood. Thanks for the info! Will switch to [`@carbon/icons`](https://github.com/carbon-design-system/carbon/tree/master/packages/icons) as I wanted v10 icons all along.
Edit: [the website references carbon-icons](https://www.carbondesignsystem.com/guidelines/icons/usage/#svg-icons), which is why I started there.
