### ISSUE TITLE
Progress Indicator full with attribute

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon#5543]
### Summary

The progress indicator steps are limited to a specific width (8rem). Our designs were made with a progress indicator stretching over the full available width, which is useful to prevent overflow or at least have more space for content.
Add an attribute to use full available width for the progress indicator

![image](https://user-images.githubusercontent.com/3808948/75975583-0bf8f280-5ed9-11ea-8bf0-df231657dd23.png)

### Justification

Product design team, specified the progress indicator like this within a modal.

![image](https://user-images.githubusercontent.com/3808948/75975495-e79d1600-5ed8-11ea-8b2b-0389f329f66b.png)
(I replaced the actual content)

### Desired UX and success metrics

-

### "Must have" functionality

Ability/Attribute to set the progress indicator to full width.

### Specific timeline issues / requests

Within the next 3 Months

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

See image above

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by emyarod** [comment]
cc @carbon-design-system/design regarding this enhancement

in the meantime a workaround would be

```css
.bx--progress-step,
.bx--progress-line {
  width: 100%;
}
```

**Comment by tw15egan** [comment]
Pretty sure this PR is going to take care of this

https://github.com/carbon-design-system/carbon/pull/5380

**Comment by ConradSchmidt** [comment]
Great - thanks for linking the PR

**Comment by RichardsonWTR** [comment]
In adition to @emayrod's comment, here is the code fixing the  labels sizes too.
```scss
.bx--progress-step,
.bx--progress-line {
  width: 100%;
}

.bx--progress-label {
  max-width: 100%;
  padding-right: 1rem;
}


```
Got the padding from #5380 [laurenmrice's comment](https://github.com/carbon-design-system/carbon/pull/5380#pullrequestreview-361327331)

**Comment by tw15egan** [comment]
Prop added in with this PR https://github.com/carbon-design-system/carbon/pull/5635

**Comment by RichardsonWTR** [comment]
I'd opened the storybook and I haven't noticed that the `spaceEqually` property was already there. Thanks @tw15egan for commenting and closing the issue!
