### ISSUE TITLE
Font Weights not working correctly 

### ISSUE THREAD

**Issue by andysherman2121** [carbon-design-system/carbon#5548]
Using Expressive-Heading-05, the font weight should be 300 on larger breakpoints but it's staying on 400 throughout all breakpoints. Should only be 400 on smallest screen size. Similar issue with. Expressive-Heading-03. The font size should be fluid throughout breakpoints but is not working accordingly. 

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Would like to see the font weights adjusted correctly and the fluid font sizes fixed.
This issue describes the problems in detail.
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1188
> What browser are you working in? Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of? Digital Designs squad

## Steps to reproduce the issue

1. Step one:
http://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image
2. Step two:
select Centered under the type knob.

**Comment by tw15egan** [comment]
Can you try using `@include carbon--type-style('expressive-heading-03', true);` where you are declaring the type styles?

**Comment by andysherman2121** [comment]
That's how we're declaring it currently

<img width="510" alt="Screen Shot 2020-03-05 at 2 41 39 PM" src="https://user-images.githubusercontent.com/56688604/76019277-7321a180-5eef-11ea-9ce9-5d39dbbdb08f.png">

**Comment by tw15egan** [comment]
🕵 On the case. 

It looks like we might need to update the definitions to make sure they are what is displayed on the website. I'm not seeing any `font-weight` changes on larger breakpoints in `scss` definitions. 

<img width="455" alt="Screen Shot 2020-03-05 at 1 00 48 PM" src="https://user-images.githubusercontent.com/11928039/76025546-005df980-5ee2-11ea-91e3-3d16158f95bb.png">

Code: https://github.com/carbon-design-system/carbon/blob/7bb841305b9e0b5d0cc1a4a9825d057cec32dd8b/packages/type/scss/_styles.scss

However, I _do_ see them in the `js` definitions...

<img width="391" alt="Screen Shot 2020-03-05 at 1 01 00 PM" src="https://user-images.githubusercontent.com/11928039/76025538-fd630900-5ee1-11ea-96b0-3f30132f0b46.png">

Code: https://github.com/carbon-design-system/carbon/blob/7bb841305b9e0b5d0cc1a4a9825d057cec32dd8b/packages/type/src/styles.js

As well as seeing the intended type changes in the local dev environment

![type-changes](https://user-images.githubusercontent.com/11928039/76025498-ede3c000-5ee1-11ea-9645-dfb1967cc1dd.gif)

@joshblack, I'm assuming both of these files should match, correct? Is there any flag that needs to be enabled to get the fluid typestyles? Not sure what we have enabled in the dev environment that is outputting the correct styles.

@andysherman2121, which version of the components and type package are you running?

**Comment by andysherman2121** [comment]
The component version is 10.9.0 and the type package is 10.5.1

**Comment by joshblack** [comment]
@tw15egan ah sorry, yeah the files should match. I believe the JS is treated as the source of truth (this is what Jeannie edits) but we have been having to port the changes over to Sass since we haven't set up auto-generating the sass like in the other packages yet.

@jeanservaas is the light font weight intended for `expressive-heading-05` starting on md for `expressive-heading-05`? What about for `expressive-heading-03`?
