### ISSUE TITLE
Pictograms have extra padding

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon#5550]
## What package(s) are you using?

- [ ] `carbon-pictograms`

## Detailed description

> Describe in detail the issue you're having.

The [pictograms](https://github.com/carbon-design-system/carbon/blob/master/packages/pictograms/svg/desktop.svg) have a much larger padding around them than expected from the specs on the IDL documentation
**Example of SVG**
<img width="158" alt="Screen Shot 2020-03-05 at 3 55 42 PM" src="https://user-images.githubusercontent.com/45692622/76024839-ca2c7400-5ef9-11ea-96d7-f9dbd0316b3e.png">

**Expected padding**
<img width="198" alt="Screen Shot 2020-03-05 at 3 54 04 PM" src="https://user-images.githubusercontent.com/45692622/76024740-9f422000-5ef9-11ea-85d7-f20819a8bbcb.png">

The extra padding is causing alignment issues between the pictograms and text because the artwork doesn't span to the edge of the container as it did before.
**Design intent** 
using 1px border specs 
<img width="1029" alt="Screen Shot 2020-03-05 at 2 48 27 PM" src="https://user-images.githubusercontent.com/45692622/76020006-a87abf00-5ef0-11ea-9470-a9bef2c9ca0c.png">

**What is happening** 
using svg from pictogram package
<img width="782" alt="Screen Shot 2020-03-05 at 2 47 09 PM" src="https://user-images.githubusercontent.com/45692622/76020117-da8c2100-5ef0-11ea-9873-1b1da9cd247e.png">
[link to storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgrouppictograms--default)

> Is this issue related to a specific component?

All pictogram svg files

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Is the extra padding around the pictograms an intended, permanent change to the pictogram svgs that designers need to account for? 

I would have thought the pictograms would adhere to the size they were drawn to, accounting for the 1px padding [specified on the IDL page](https://www.ibm.com/design/language/iconography/pictograms/design)
<img width="453" alt="Screen Shot 2020-03-05 at 1 35 44 PM" src="https://user-images.githubusercontent.com/45692622/76019504-d3184800-5eef-11ea-949b-ce44ccdadab4.png">

> What browser are you working in?

All browsers

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Digital Design System and Web simplification – launching May 2020

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by laurenmrice** [comment]
@conradennis ^

I do not have permissions to move this into the pictogram repo, otherwise I would have .

**Comment by conradennis** [comment]
@laurenmrice thanks for the heads up, the repo is still private and is mostly intended for artwork creation and contribution so it might be worth keeping this one here.

@oliviaflory thanks for calling attention to this issue. The extra padding around the pictogram is intentional and is actually the corresponding container size for the pictograms as in the image shown below.

<img width="600" alt="Screen Shot 2020-03-06 at 4 56 18 PM" src="https://user-images.githubusercontent.com/16782944/76125734-6d00f300-5fcb-11ea-929c-b56af73c8128.png">

While the intent is to include this extra space for container shapes in the SVG file for ease of use, it seems like the inclusion of the container space is causing issues with alignment when a container is not needed. I'm not sure how we might address this issue in code but it's something I can bring up with the production team on the brand side and it'll be good to get some perspective from the Carbon folks on how we can avoid this issue moving forward.

**Comment by conradennis** [comment]
Russ to set up a meeting between Brand team and Carbon to discuss how to deal with this issue.

**Comment by ghost** [comment]
@conradennis Hey, can you include Olvia Flory in the meeting, please? We are getting questions around this one a lot, we'd like to stay tuned as well.

**Comment by conradennis** [comment]
@wonilsuhibm yup will let Russ know to include her. Thanks!

**Comment by joshblack** [comment]
Looking into this, it seems like the artboard is being drawn at 48x48 but the path is not growing to fill the entire space:
 
![Screen Shot 2020-03-20 at 12 43 38 PM](https://user-images.githubusercontent.com/3901764/77191096-70ef4380-6aa8-11ea-976e-4a0984bbe9af.png)

![Screen Shot 2020-03-20 at 12 43 32 PM](https://user-images.githubusercontent.com/3901764/77191156-849aaa00-6aa8-11ea-93a0-1a304300d8ba.png)

**Comment by joshblack** [comment]
Closing this in favor of #5693! We're going to move forward with processing the SVGs to be in a 32x32 artboard in code and Sketch 👍
