### ISSUE TITLE
@carbon/icons replacing carbon-icons?

### ISSUE THREAD

**Issue by davefp** [carbon-design-system/carbon#5551]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

The main `carbon-components` package lists `carbon-icons` as a dependency, but according to the answer given in #5542 this package is superseded by `@carbon/icons`.

My questions:
1. Is there a workflow for using `@carbon/icons` with `carbon-components`? FWIW the icon docs still reference `carbon-icons` here: https://www.carbondesignsystem.com/guidelines/icons/usage/#svg-icons
1. Are there plans on replacing the old icon dependency with the new one in `carbon-components`?

## Relevant information

We're integrating the vanilla js/sass package with Ruby on Rails by referencing the svgs in the `dist` subfolder and inlining them using the [inline_svg](https://github.com/jamesmartin/inline_svg) gem

**Comment by asudoh** [comment]
Hi 👋 thank you for asking - `carbon-icons` hosts `v9` icons, and `@carbon/icons` hosts `v10` icons. Hope it clarifies.

**Comment by davefp** [comment]
I see. I've now integrated with`@carbon/icons` and it works for the most part. There seem to be a couple of buggy SVGs but I'll raise that separately.

One of my original questions is still outstanding though: Is there a roadmap for replacing `carbon-icons` with `@carbon/icons` as a dependency of the main `carbon-components` package?
