### ISSUE TITLE
what about a port as Blazor library

### ISSUE THREAD

**Issue by mouadcherkaoui** [carbon-design-system/carbon#5554]
Hi there! 👋 Hope everything is going okay using projects from the Carbon Design
System.

## Summary

recently I was amazed by the Carbon Design framework, also I did some experiments to use it in an aspnetcore-blazor project, and found the integration is quite simple and easy, and the idea of porting Carbon components as a Blazor library, actually I need guidance rules and recommendations to publish it as a contribution !?

**Comment by joshblack** [comment]
Hi @mouadcherkaoui! 👋 That's so exciting to hear! Thanks for reaching out and telling us about it 😄 

With respect to blazor, I think we'd be happy to point to it as part of the Carbon community/ecosystem if you would like to start up a project. Similarly, we do this for the following libraries/frameworks:

- http://github.com/ibm/carbon-components-svelte
- http://github.com/ibm/carbon-components-angular
- https://github.com/carbon-design-system/carbon-components-vue

**Comment by mouadcherkaoui** [comment]
Hi Josh,
thanks for the reply, I saw those different implementations, and actually started to port some of the components, and seems it is easy since the library is well designed and self-descriptive, it is not stable as a package but I'm working to make a first mvp here is the code on github [https://github.com/mouadcherkaoui/bxblazor/](https://github.com/mouadcherkaoui/bxblazor/).
the updated version is on azure repos:
https://dev.azure.com/cherkaouimouad/_git/BxBlazor

**Comment by joshblack** [comment]
That's so exciting! Thanks for sharing :pray: Whenever you feel solid about it, feel free to reach out and I think we'd be happy to add it to a community section or something on the README of the project :smile:

**Comment by mouadcherkaoui** [comment]
sure, I'll do my best! 👍 
thanks 🍡
