### ISSUE TITLE
Docs: DataTable Batch Actions Search Bar

### ISSUE THREAD

**Issue by jeff-arn** [carbon-design-system/carbon#5569]
## Issue

In the [DataTable documentation](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/README.md#batch-actions) for batch actions, the `TableToolbarSearch` component is not listed as a child of `TableToolbarContent`. However, in the running examples in Storybook, it is rendered as a child of `TableToolbarContent`.

![image](https://user-images.githubusercontent.com/4694018/76146893-1516ca80-6065-11ea-8546-11743b506970.png)

Not making it a child of `TableToolbarContent` causes incorrect behavior and causes the search button to still render when the select all batch action menu is rendered. If this is indeed a mistake in the docs, I can make a PR fixing it.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. I agree with you that it's an error in the docs. A PR will be appreciated!

**Comment by jeff-arn** [comment]
Sounds good, I should be able to open up later today!
