### ISSUE TITLE
Accessibility for Internal Left Hand Nav: flagged by accessibility for not having enough contrast 

### ISSUE THREAD

**Issue by ktitsworth** [carbon-design-system/carbon#557]
## Detailed description

In IBM Cloud, for the Identity and Access section of Manage, we received a ticket stating the navigation did not have enough contrast for moderately low vision users.

> Is this issue related to a specific component? 

Left hand nav

> What did you expect to happen? What happened instead? What would you like to see changed?

Expect Carbon to be accessible compliant.

> What browser are you working in? 

See original ticket: https://github.ibm.com/IAM/access-management/issues/4165

> What version of the Carbon Design System are you using? 

Current

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
 IBM Cloud

## Steps to reproduce the issue

    

1. Go to https://dev-console.stage1.ng.bluemix.net/
2. Login with IBM id
3. Click Manage
4.  Click Identity & access -> Platform API Keys

## Additional information
Please see original ticket submitted to IBM Bluemix/Cloud access management git board. 
https://github.ibm.com/IAM/access-management/issues/4165

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
Not sure this is a problem on our end, this is black text on a white background. Seems like the DAP tool is throwing an unnecessary error, so I'm going to close this one.

![screen shot 2018-02-13 at 11 13 41 am](https://user-images.githubusercontent.com/11928039/36163415-f942229e-10ae-11e8-880e-5cb4e4106d11.png)
