### ISSUE TITLE
Dependency Version Mismatch -- scss-to-json in npm but not GitHub

### ISSUE THREAD

**Issue by virkt25** [carbon-design-system/carbon#5571]
## What package(s) are you using?

- [x] `carbon-components: 10.10.1`
- [ ] `carbon-components-react`

## Detailed description

In the source code on GitHub there is no dependency called `scss-to-json` in the latest release. 

Source Code Reference: https://github.com/carbon-design-system/carbon/blob/master/packages/components/package.json#L68

In the code installed via `npm`, there is a dependency called `scss-to-json`.

![image](https://user-images.githubusercontent.com/3311536/76169129-c3953b00-614b-11ea-8af5-c861ed1d5e08.png)

This dependency in turn installs `node-sass` which becomes the default SCSS compiler if present in `node_modules` in an Angular project.

It seems like `scss-to-json` shouldn't have been in the release bundle based on GitHub code. Also generally a bad practice to have `npm` code out of sync with git commit history. 

## Solution

A new release based on the code in GitHub which will remove `scss-to-json` and hence `node-sass` from my dependency tree.

**Comment by asudoh** [comment]
#5476 removed `scss-to-json` dependency. @cal-smith Any insights wrt why this is a problem with Angular starter? Or would we need more info from the issue author? Thanks!

**Comment by virkt25** [comment]
@asudoh I know the dependency was removed, which is great but the latest version on `npm` still lists `scss-to-json` as a dependency.

The fix is to literally do a new release so it's no longer a dependency

**Comment by joshblack** [comment]
@virkt25 we ship releases on a time-based format pulling from what's available in `master` 👍 

Our next release should include this fix, the time period for it is detailed over in https://github.com/carbon-design-system/carbon/wiki/Release-radar The one exception to this rule are hotfixes which can occur between timed releases but are reserved for extreme cases.

Hope this helps!

**Comment by virkt25** [comment]
Thanks for the info @joshblack -- I'll wait for the next release which should have that dependency dropped :)

**Comment by vprasanth** [comment]
I think this can be closed now, 10.10.2 contains the PR to remove this dependency.
