### ISSUE TITLE
Write documentation around icon metadata and expected usage

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5579]
We should write out the purpose and expectations around contributing to the icons metadata in a way that designers and developers can understand when contributing an icon.

Ideally, this content would live in `packages/icons/docs/contributing.md` and cover the following topics:

- What is `icons.yml`, how does it work, and why/how would I edit it?
- What is `deprecation.yml` used for and why/how would I edit it?

We should include @chrisconnors-ibm as one of the reviewers to help validate that we covered these topics and didn't skip over any relevant information

**Comment by chrisconnors-ibm** [comment]
Thanks Josh. This is important for @conradennis, @laurenmrice, or anyone who adds new icons, edits their synonyms, renames an icon, or initiates the process to remove one.
