### ISSUE TITLE
UI Shell header menu onBlur not working

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#5581]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Using the UI Shell header with multiple sub menus, the onblur doesn't close some intended dropdowns, and sometimes they will be stuck opened until I manually click on the menu button to close it.

> Is this issue related to a specific component?
Yes, UI Shell

> What did you expect to happen? What happened instead? What would you like to
> see changed?
When focus drops from a submenu, it should close.

> What browser are you working in?
Firefox

> What version of the Carbon Design System are you using?
Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Docs, looking to release Mid April

## Steps to reproduce the issue
1. Click on one menu to show the dropdown
2. Click on a second menu to show the dropdown
3. Both menus are opened (is this expected? or should the first menu close?)
4. Click anywhere else on the page, the first menu stays open.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

Sandbox links are broken, can be reproduced using code from storybook and adding an additional submenu so there are 2.

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Which version of the components are you on? I'm not seeing the behavior when testing locally 🤔 

![shell nav](https://user-images.githubusercontent.com/11928039/76333639-24895400-62af-11ea-8ea6-0185a1bfc491.gif)

**Comment by gptt916** [comment]
7.9.1, I thought this was the latest version. I just tried 7.10.1 and this is what I get
<img width="940" alt="image" src="https://user-images.githubusercontent.com/20601623/76334794-f6653d80-62c9-11ea-84ea-06da1d7503e6.png">

**Comment by tw15egan** [comment]
Have you also updated the styles to `10.10.1`? There were associated style changes that would cause the issue you are seeing

**Comment by gptt916** [comment]
I just updated both, looks like the issue is solved with the latest releases, thank you!

**Comment by tw15egan** [comment]
Woo! Glad to hear. Going to close this out but feel free to reopen if you run into any other issues 👍
