### ISSUE TITLE
Add a Primary Button version of the Danger Button

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon#559]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

Need an option other than the current danger button that has the secondary button style.

> Is this issue related to a specific component? 

We intend to use the primary danger button within modals. There may be other appropriate applications.

> What did you expect to happen? What happened instead? What would you like to see changed?

We expect to have a primary version of the danger button and all of its variants (such as disabled)

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

V8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Containers

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by davidmenendez** [comment]
related to https://github.com/carbon-design-system/carbon-components/pull/556

**Comment by SpencerReynolds18** [comment]
![36161079-668bf1b0-10a8-11e8-8d1c-c918c6601432](https://user-images.githubusercontent.com/19826147/36171573-c1cd1912-10c8-11e8-8271-ff34c478f937.png)
