### ISSUE TITLE
Code snippet tooltip cut off on Safari

### ISSUE THREAD

**Issue by snrubnomis** [carbon-design-system/carbon#5595]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The "copied" tooltip that appears whe you click the copy button on a CodeSnippet looks cut off on Safari.  It looks like Safari doesn't handle the `width: max-content` setting properly.  An override of `width: auto` fixes the issue.

> Is this issue related to a specific component?

CodeSnippet

> What did you expect to happen? What happened instead? What would you like to
> see changed?

You should be able to see the full "copied" tooltip

> What browser are you working in?

Safari 13

> What version of the Carbon Design System are you using?

carbon-components: 10.9.3
carbon-components-react: 7.9.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Using Safari, go to https://react.carbondesignsystem.com/?path=/story/codesnippet--single-line
2. Click the copy button
3. See "copied" tooltip cut off

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

Problem can be seen in the react storybook

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
I don't think we can replace the `width` value with `auto` as that will affect multiline tooltip width but I will need to look into this more
