### ISSUE TITLE
Evaluate 16, 20 and 24 icons for redundancy

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#5597]
Last batch of icons to evaluate for elimination!:

- [ ] apps https://carbon-elements.netlify.app/icons/examples/preview/#Apps16
- [ ] arrow--down https://carbon-elements.netlify.app/icons/examples/preview/#ArrowDown16
- [ ] arrow--left https://carbon-elements.netlify.app/icons/examples/preview/#ArrowLeft16
- [ ] arrow--right https://carbon-elements.netlify.app/icons/examples/preview/#ArrowRight16
- [ ] arrow--right 20 https://carbon-elements.netlify.app/icons/examples/preview/#ArrowRight20
- [ ] arrow--right 24 https://carbon-elements.netlify.app/icons/examples/preview/#ArrowRight24
- [ ] arrow--up https://carbon-elements.netlify.app/icons/examples/preview/#ArrowUp16
- [ ] asleep https://carbon-elements.netlify.app/icons/examples/preview/#Asleep16
- [ ] awake https://carbon-elements.netlify.app/icons/examples/preview/#Awake16
- [ ] checkmark--filled https://carbon-elements.netlify.app/icons/examples/preview/#CheckmarkFilled16
- [ ] checkmark--filled 20 https://carbon-elements.netlify.app/icons/examples/preview/#CheckmarkFilled20
- [ ] checkmark--filled 24 https://carbon-elements.netlify.app/icons/examples/preview/#CheckmarkFilled24
- [ ] checkmark 20 https://carbon-elements.netlify.app/icons/examples/preview/#Checkmark20
- [ ] checkmark 24https://carbon-elements.netlify.app/icons/examples/preview/#Checkmark24
- [ ] chevron--down https://carbon-elements.netlify.app/icons/examples/preview/#ChevronDown16
- [ ] chevron--left https://carbon-elements.netlify.app/icons/examples/preview/#ChevronLeft16
- [ ] chevron--mini https://carbon-elements.netlify.app/icons/examples/preview/#ChevronMini16
- [ ] chevron--right https://carbon-elements.netlify.app/icons/examples/preview/#ChevronRight16
- [ ] chevron--sort--down https://carbon-elements.netlify.app/icons/examples/preview/#ChevronSortDown16
- [ ] chevron--sort--up https://carbon-elements.netlify.app/icons/examples/preview/#ChevronSortUp16
- [ ] chevron--sort https://carbon-elements.netlify.app/icons/examples/preview/#ChevronSort16
- [ ] chevron--up https://carbon-elements.netlify.app/icons/examples/preview/#ChevronUp16
- [ ] close--filled https://carbon-elements.netlify.app/icons/examples/preview/#CloseFilled16
- [ ] download https://carbon-elements.netlify.app/icons/examples/preview/#Download16
- [ ] error--filled https://carbon-elements.netlify.app/icons/examples/preview/#ErrorFilled16
- [ ] error--filled 20 https://carbon-elements.netlify.app/icons/examples/preview/#ErrorFilled20
- [ ] error--filled 24 https://carbon-elements.netlify.app/icons/examples/preview/#ErrorFilled24
- [ ] error--outline https://carbon-elements.netlify.app/icons/examples/preview/#ErrorOutline16
- [ ] export https://carbon-elements.netlify.app/icons/examples/preview/#Export16
- [ ] fade https://carbon-elements.netlify.app/icons/examples/preview/#Fade16
- [ ] help https://carbon-elements.netlify.app/icons/examples/preview/#Help16
- [ ] information https://carbon-elements.netlify.app/icons/examples/preview/#Information16
- [ ] interactions https://carbon-elements.netlify.com/icons/examples/preview/#16%2Finteractions
- [ ] launch https://carbon-elements.netlify.com/icons/examples/preview/#16%2Flaunch
- [ ] light https://carbon-elements.netlify.app/icons/examples/preview/#Light16
- [ ] list--bulleted https://carbon-elements.netlify.com/icons/examples/preview/#16%2Flist--bulleted
- [ ] maximize https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fmaximize
- [ ] menu https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fmenu
- [ ] menu 20 https://carbon-elements.netlify.com/icons/examples/preview/#20%2Fmenu
- [ ] menu 24 https://carbon-elements.netlify.com/icons/examples/preview/#24%2Fmenu
- [ ] minimize https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fminimize
- [ ] misuse--outline https://carbon-elements.netlify.app/icons/examples/preview/#MisuseOutline16
- [ ] misuse https://carbon-elements.netlify.app/icons/examples/preview/#Misuse16
- [ ] misuse 20 https://carbon-elements.netlify.app/icons/examples/preview/#Misuse20
- [ ] misuse 24 https://carbon-elements.netlify.app/icons/examples/preview/#Misuse24
- [ ] new-tab https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fnew-tab
- [ ] nominal https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fnominal
- [ ] notifications--off https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fnotification--off
- [ ] notifications https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fnotification
- [ ] ordinal https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fordinal
- [ ] pause--outline--filled https://carbon-elements.netlify.app/icons/examples/preview/#PauseOutlineFilled16
- [ ] pause--outline https://carbon-elements.netlify.app/icons/examples/preview/#PauseOutline16
- [ ] pause https://carbon-elements.netlify.app/icons/examples/preview/#Pause16
- [ ] play--filled https://carbon-elements.netlify.app/icons/examples/preview/#PlayFilled16
- [ ] play--outline--filled https://carbon-elements.netlify.app/icons/examples/preview/#PlayOutlineFilled16
- [ ] play--outline https://carbon-elements.netlify.app/icons/examples/preview/#PlayOutline16
- [ ] play https://carbon-elements.netlify.app/icons/examples/preview/#Play16
- [ ] power https://carbon-elements.netlify.app/icons/examples/preview/#Power16
- [ ] redo https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fredo
- [ ] redo 20 https://carbon-elements.netlify.com/icons/examples/preview/#20%2Fredo
- [ ] redo 24 https://carbon-elements.netlify.com/icons/examples/preview/#24%2Fredo
- [ ] restart https://carbon-elements.netlify.com/icons/examples/preview/#16%2Frestart
- [ ] save https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fsave
- [ ] save 20 https://carbon-elements.netlify.com/icons/examples/preview/#20%2Fsave
- [ ] save 24 https://carbon-elements.netlify.com/icons/examples/preview/#24%2Fsave
- [ ] search https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fsearch
- [ ] settings https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fsettings
- [ ] star--filled https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fstar--filled
- [ ] star--half https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fstar--half
- [ ] star https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fstar
- [ ] stop--filled https://carbon-elements.netlify.app/icons/examples/preview/#StopFilled16
- [ ] stop--outline--filled https://carbon-elements.netlify.app/icons/examples/preview/#StopOutlineFilled16
- [ ] stop--outline https://carbon-elements.netlify.app/icons/examples/preview/#StopOutline16
- [ ] stop https://carbon-elements.netlify.app/icons/examples/preview/#Stop16
- [ ] undo https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fundo
- [ ] undo 20 https://carbon-elements.netlify.com/icons/examples/preview/#20%2Fundo
- [ ] undo 24 https://carbon-elements.netlify.com/icons/examples/preview/#24%2Fundo
- [ ] unlocked https://carbon-elements.netlify.com/icons/examples/preview/#16%2Funlocked
- [ ] upload https://carbon-elements.netlify.app/icons/examples/preview/#Upload16
- [ ] user--avatar https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fuser--avatar
- [ ] user https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fuser
- [ ] view--off https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fview--off
- [ ] view https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fview
- [ ] warning--alt https://carbon-elements.netlify.app/icons/examples/preview/#WarningAlt16 
- [ ] warning--filled https://carbon-elements.netlify.app/icons/examples/preview/#WarningFilled16
- [ ] warning--filled 20 https://carbon-elements.netlify.app/icons/examples/preview/#WarningFilled20
- [ ] warning--filled 24 https://carbon-elements.netlify.app/icons/examples/preview/#WarningFilled24
- [ ] warning https://carbon-elements.netlify.app/icons/examples/preview/#Warning16
- [ ] zoom--in https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fzoom--in
- [ ] zoom--out https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fzoom--out

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity, feel free to comment and I can re-open!

**Comment by chrisconnors-ibm** [comment]
@conradennis could also evaluate these. otherwise I'll try to chip away at these!

**Comment by laurenmrice** [comment]
Reopening to finish this.

**Comment by conradennis** [comment]
duplicate icons with different names in the library:
- awake, light, sun
- misuse--alt, misuse--outline, close--outline
- close--filled, misuse

updated icons to reduce need for redundancy:
- arrow--down
- arrow--left
- arrow--right
- arrow--up
- download
- error--outline
- error--filled
- export
- information
- information--filled
- information--square--filled
- launch
- new-tab
- notification
- notification--off
- play
- redo
- restart
- search
- undo
- upload
- user--avatar
- warning--alt
- warning--alt--filled
- zoom--in
- zoom--out

there are also a few icons that can be reworked to render better at smaller sizes but when proper tweaks are made they just look worse/unbalanced compared to their original versions. I'll need to work with these a bit more: 
- maximize
- minimize
- play--filled
- play--outline
- play--outline--filled

any icons I update will be included in my next batch PR later this week so once I make that issue I'll reference it here and then when it's merged we should be able to close this one.

**Comment by laurenmrice** [comment]
Thank you, Conrad! 🙌🏻

**Comment by conradennis** [comment]
PR including all updated icons mentioned above: https://github.com/carbon-design-system/carbon/pull/7126

we should be able to remove all of the icons Connors listed and close the issue
