### ISSUE TITLE
Need gradient support for Carbon bar graph

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5599]
## Description
Several prominent page designs in IBM Cloud use bar graphs with gradient, including the dashboard and the new billing overview page. Currently however the code does not support use of gradients. These pages are set to be released before THINK.
 
Use of gradients with bar graphs fits the Carbon accessibility guides. We would like to add gradient support to this specific type of graph. 

The turnaround for this is fairly tight - please let us know what we can do to move the issue forward.

## Example

<img width="618" alt="Screen Shot 2020-03-11 at 10 55 23 AM" src="https://user-images.githubusercontent.com/39408106/76436943-d6478400-6386-11ea-8b9d-932b583d1c7b.png">

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-charts #531](https://github.com/carbon-design-system/carbon-charts/issues/531) via [**ZenHub**](https://www.zenhub.com/)
