### ISSUE TITLE
Add a gray button - both primary and secondary

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon#560]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component? 

Could be a general addition of the gray button. The issue that surfaced it was the danger modal: https://github.com/carbon-design-system/carbon-components/pull/556

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Containers

**Comment by davidmenendez** [comment]
related to https://github.com/carbon-design-system/carbon-components/pull/556

**Comment by SpencerReynolds18** [comment]
![36161079-668bf1b0-10a8-11e8-8d1c-c918c6601432](https://user-images.githubusercontent.com/19826147/36171578-c956feb4-10c8-11e8-8ba8-92d4f37df559.png)

**Comment by tay-aitken** [comment]
Please see our internal repo to track the progress on this [#541](https://github.ibm.com/Bluemix/carbon-issues/issues/541)
