### ISSUE TITLE
Could icons source code be improved?

### ISSUE THREAD

**Issue by coremyslo** [carbon-design-system/carbon#5600]
## What package(s) are you using?
- [x] icons

## Summary

Hi, I'm interested to use icons package as a dependency in my open source project.
I was trying to build icon font based on SVG's, and faced several issues, listed below. Not sure if they can be reported as bugs, since not sure anyone else has the same.

## Relevant information

1. Could `<styles>` block can be replaced with relevant icon attributes?
My Icon font generator build icon as

<img width="45" alt="" src="https://user-images.githubusercontent.com/20535974/76438643-ef225a80-63c3-11ea-9cef-e46056784a89.png">

Instead of

<img width="40" src="https://user-images.githubusercontent.com/20535974/76443309-e4b78f00-63ca-11ea-8de5-ca39f67e1553.png">

Which is caused by using inline `<style>` tag with **fill** value.
```html
<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
    <defs>
        <style>.cls-2{fill:none;}</style>
    </defs>
    ...
    <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-2" width="32" height="32"/></svg>
```
Syntax below would fix the issue:
```html
<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
    ...
    <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" fill="none" width="32" height="32"/></svg>
```

NOTE: actually `<rect id="_Transparent_Rectangle_">` is not needed for production code.  

2. Some icons has not needed svg tags, which sometimes breaks display
Example:
Icon
<img width="47" src="https://user-images.githubusercontent.com/20535974/76439994-e6328880-63c5-11ea-926a-b5c9f55fcd89.png">
In some conditions can be rendered as
<img width="50" src="https://user-images.githubusercontent.com/20535974/76439894-c4d19c80-63c5-11ea-83e1-fb073deaf42d.png">
Which is cased by issue described in (1), also because svg has not used element

```html
<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
    <defs>
        <style>.cls-1{fill:#fff;}.cls-2{fill:none;}</style>
    </defs>
    <title>MP4</title>
    <!-- not needed
    <polygon class="cls-1" points="27.5 22.5 27.5 18.5 22.5 18.5 22.5 9.5 23.5 9.5 23.5 17.5 27.5 17.5 27.5 9.5 28.5 9.5 28.5 17.5 29.5 17.5 29.5 18.5 28.5 18.5 28.5 22.5 27.5 22.5"/>
    -->
    <path d="M28,10v8h0V10m1-1H27v8H24V9H22V19h5v4h2V19h1V17H29V9Z"/>
    <path d="M14,23H12V9h6a2,2,0,0,1,2,2v5a2,2,0,0,1-2,2H14Zm0-7h4V11H14Z"/>
    <polygon points="8 9 6.49 14 6 15.98 5.54 14 4 9 2 9 2 23 4 23 4 15 3.84 13 4.42 15 6 19.63 7.58 15 8.16 13 8 15 8 23 10 23 10 9 8 9"/>
    <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-2" width="32" height="32"/>
</svg>
```

3. Some icons use transform which sometimes brakes display
Icon "alarm"
<img width="41" alt="зображення" src="https://user-images.githubusercontent.com/20535974/76440749-00209b00-63c7-11ea-9fbb-2fbf46e5cafa.png">
In some conditions can be rendered as
<img width="68" src="https://user-images.githubusercontent.com/20535974/76440815-1595c500-63c7-11ea-9667-d26c95f0bcdd.png">
Because of using "transform".

```html
<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
    <defs>
        <style>.cls-1{fill:#010101;}.cls-2{fill:none;}</style>
    </defs>
    <title>alarm</title>
    <path d="M16,28A11,11,0,1,1,27,17,11,11,0,0,1,16,28ZM16,8a9,9,0,1,0,9,9A9,9,0,0,0,16,8Z"/>
    <polygon points="18.59 21 15 17.41 15 11 17 11 17 16.58 20 19.59 18.59 21"/>
    <rect class="cls-1" x="3.96" y="5.5" width="5.07" height="2" transform="translate(-2.69 6.51) rotate(-45.06)"/>
    <rect class="cls-1" x="24.5" y="3.96" width="2" height="5.07" transform="translate(2.86 19.91) rotate(-44.94)"/>
    <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-2" width="32" height="32"/>
</svg>
```

Could elements using transform be flatten?

**Comment by joshblack** [comment]
Hi there @coremyslo! 👋 The SVGs available in the package are the raw SVG assets currently and are not optimized. The icons shipped in our packages are optimized, however.

We do have a ticket open for optimizing the output of the SVGs available in this directory over in #5568 if you would like to follow along with that progress!

**Comment by coremyslo** [comment]
Hi, thank you for the quick response. Issues reported above definitely related to that ticket and after some investigation, confirming they can be fixed using svgo. I will move any further communication to that ticket.

**Comment by coremyslo** [comment]
@joshblack I missed that issue in (2) not relates to optimization
Let me show more visual
<img width="1424" src="https://user-images.githubusercontent.com/20535974/76508240-bda69f00-6456-11ea-88e9-ad42bc6d8402.png">
There is tag with `#fff` color which is overlapped by another element. After removing overlapping element:
<img width="1415" src="https://user-images.githubusercontent.com/20535974/76508416-02323a80-6457-11ea-9b11-c43d94416ade.png">

Which causes an issue when creating iconfont using `svgicons2svgfont` (module that used in almost all open source icon font generators):
<img width="74" src="https://user-images.githubusercontent.com/20535974/76509153-3d813900-6458-11ea-8e99-dc7ac92b5f52.png">
Reported here
https://github.com/nfroidure/svgicons2svgfont/issues/94

Affected icons: `mp4`, `add--filled`

This can't be fixed using SVGO.

**Comment by joshblack** [comment]
Hi @coremyslo! What I meant by optimization is that these extra attributes (e.g. fill and stroke) are removed by SVGO when they are being optimized 👍
