### ISSUE TITLE
Update spacing scale and deprecate our layout scale

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5602]
When talking to @jeanservaas and @vpicone, it came up that it would be worth consolidating the values of layout into our spacing scale and deprecating the layout scale that we currently have.

This issue is to handle implementing any changes to the spacing scale that need to happen along with deprecating the layout scale.

**Comment by tw15egan** [comment]
Just for clarification, would this entail the following?

- Changing any instances of `$layout-xx` to `$spacing-xx`
- Adding the larger `layout` values to the end of `spacing`
    - i.e. `$layout-05` becomes `$spacing-10`
- Adding a deprecation warning to `components/src/globals/scss/_spacing` variables
