### ISSUE TITLE
Codesandbox starter template

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5604]
Is there a Codesandbox starter to help replicate errors for issues?

**Comment by asudoh** [comment]
Hi 👋 you can find ones at https://github.com/carbon-design-system/carbon/blob/v10.10.0/.github/ISSUE_TEMPLATE/bug-report.md - Hope this helps!

**Comment by ghost** [comment]
The link says the sandbox can not be found

**Comment by emyarod** [comment]
both links appear to be working properly at the moment

not sure what sort of issue you are facing, but the Code Sandboxes are imported from subdirectories in the repository. unless GitHub or Code Sandbox is experiencing issues, the links will display our template
