### ISSUE TITLE
Component Inheritance Performance

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#561]
Because of the known inheritance performance issues, I propose that we change the base Component class to be factory functions instead. Once you start inheriting more than 1 or 2 levels there is a performance hit, so I'd avoid creating small classes that save minimal lines of code that are inherited by all components.  A solution would be to create factory functions that can be used by components to generate this repeated code without actually inheriting. When creating a new component instead of writing:

```
class MyComponent extends Component {
...
}

// Common JavaScript
class Component {
   init() {...}
   create() {...}
   ....
}
```

Developers would call the factory function instead the class:
```
class MyComponent {
   Component.createAPI(MyComponent);
}

// Common JavaScript for components
Component = {
   createAPI(proto) {
        proto.init = () => { ... }
        proto.create = () => { ... }
        ...
   }
}
```
The factory functions support both static and non-static methods/properties.

This would not change the end-user experience of consumers but will take in to consideration the performance hit of inheritance and be more friendly to consumers as this framework is absorbed by other frameworks/applications.

Working example: https://github.ibm.com/Watson-Health/design-system/tree/develop/src/components/tooltip and https://github.ibm.com/Watson-Health/design-system/blob/develop/src/global/scripts/component.js

> Is this issue related to a specific component? 
No

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
WHDS - Initial launch is end of Q1

**Comment by elizabethsjudd** [comment]
References around issue:
From MDN:
```
The lookup time for properties that are high up on the prototype chain can have a negative 
impact on the performance, and this may be significant in the code where performance is
critical. Additionally, trying to access nonexistent properties will always traverse the
full prototype chain.
```
There's another article that goes in to more depth: https://www.toptal.com/javascript/javascript-prototypes-scopes-and-performance-what-you-need-to-know

---

I do not have benchmark/side-by-side comparisons to show the improvements as I’ve known about the issues for a while (i’ve been writing prototype JS for years) and just didn’t do it based on what I read. I also think that historically inheritance with prototype was not as straight forward and due to it’s learning curve some developers stayed away from it. I think that changed with the introduction of classes and people starting to think that JavaScript is now an Object orientated language causing more conversation about the topic beyond the two references above.

However with using the inheritance approach, that means every component has a minimum of 3 levels of inheritance from the get go `(Object > Base Component > Specific Component)`. I would recommend saving inheritance for components that have a lot more similarities to avoid getting even bigger chains. Those base component properties are ones that are accessed more often too. I feel like it does not save the developer that much work to not have the base component versus calling a function that generates most of the properties/methods.

As a framework that is consumed by other applications/frameworks, performance could become an even bigger issue as carbon classes get extended and only adding to the level of nesting.  Currently within WH we are looking at a chain like: Carbon > WHDS > WHDS Payer Provider > Applications.
This chain is necessary to provide the needed support for the applications and has been discussed at length across teams. This means that there is a lot of areas where there can be added inheritance along that pipeline if someone needs to extend a class. I think Carbon needs to be VERY aware of how people intend to use Carbon and it needs to be as performant as possible. Our applications deal with a lot of big data so we don't want to limit applications or add performance hits knowingly. I think with proper documentation the factory function is quite easy to pick up and implement.

**Comment by elizabethsjudd** [comment]
Carry over comments from original Issue from @asudoh:
* My knee-jerk reaction was that why Justin Fagnani has the statge1 proposal for mix-in if the prototype inheritance has performance problems.

* Refs: https://draft.li/blog/2016/12/22/javascript-engines-hidden-classes/ https://github.com/davidmarkclements/v8-perf/blob/master/readme.md#removing-properties-from-objects

**Comment by joshblack** [comment]
Hi @elizabethsjudd! Thanks so much for taking the time to copy this over from the old repo 😄  really appreciate this.

Just to frame how we look to evaluate performance suggestions, we take the following items into account:

- Is the performance regression identifiable and demonstrable
- Is the performance regression a common path for a library consumer
- Does the suggested fix appropriately address the first part of this list without significant drawbacks to other parts of the code
- Does the suggested fix align with best practices and can be easily understood and contributed

An aspect of the issue that you've raised is that we would need to verify the first part of this checklist as we look to evaluate the component base class performance characteristics. This is where the benchmarks come in as it's important to identify the following characteristics:

- The prototype chain impacts some aspect of performance during some part of an application lifecycle, whether that's parsing, initializing, mounting, unmounting, or other runtime characteristics
- The impact is something that causes a poor experience for the end user, the developer, or both
- The impact is something that occurs during typical/standard usage for a carbon adopter

Benchmarks also help us verify that browsers aren't already optimizing typical JS usage patterns under the hood. We've often seen theoretical performance cases (like `O(n)` in a prototype chain lookup) that often don't match the implementation. 

@asudoh did some interesting research here, namely with respect to the internals of modern JavaScript engines that suggest that _if_ the prototype lookup path is hot for a component that the lookup cost ends up being `O(1)` [Link](https://draft.li/blog/2016/12/22/javascript-engines-hidden-classes/#The-Property-Access-Problem-Dynamic-Lookups-are-Slow). If that's the case, then thankfully this shouldn't be a realistic bottleneck in an application that uses Carbon 😄 

However, as we stated above, we need numbers to verify that the cost associated with dynamic property access is significant. This cost also needs to be something that's incurred regularly enough to flag this as a potential bottleneck in a typical application.

**Comment by joshblack** [comment]
@asudoh was auditing IBM Cloud console last night on his older Mac to see what the initialization cost was and ended up sharing the screenshot below. I believe (correct me if I'm wrong here, Akira) that the highlighted section points to the actual initialization cost of the components on that page, which in this case is around `~32ms`, or two frames.

Would be interesting to see runtime performance characteristics as well 😮 

![image](https://user-images.githubusercontent.com/3901764/36225361-0c296cdc-1190-11e8-837a-9fff1d3ac61d.png)

**Comment by elizabethsjudd** [comment]
To my understanding the hit would show up more during runtime.  I'd also be curious as to know what components where on the page, how many, etc as that would also have a large input on the initialization time.

I was thinking about this the other day and I really would like to do some comparison tests but we don't really have WHDS set with enough for it to be a real comparison. I could test Ink, as it also doesn't use inheritance, but I also know there is some bloat with patches currently and again don't know how accurate the results would be. I think if we had just carbon tooltips we could compare it with WHDS tooltips.

**Comment by joshblack** [comment]
Another good resource for this discussion: https://medium.com/@tverwaes/setting-up-prototypes-in-v8-ec9c9491dfe2

Namely:

> Prototypes have 2 main phases: setup and use. Prototypes in the setup phase are encoded as dictionary objects. Stores to prototypes in that state are really fast, and do not necessarily need to enter the C++ runtime (a boundary crossing which is pretty expensive).

> Any direct access to the prototype, or access through a prototype chain, will transition it to use state, making sure that all such accesses from now on are fast.

> In short, the ideal way to setup prototypes is as follows:
> ```
> var proto = func.prototype = Object.create(…);
> proto.method1 = …
> proto.method2 = …
> ```
