### ISSUE TITLE
Tooltip text is forced to be bold

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon#562]
## Detailed description

When trying to use the tooltip within our tables, it is making the text for the items that are tool-tipped in the table bold. This is throwing off our hierarchy. 

<img width="1115" alt="screen shot 2018-02-09 at 10 41 58 am" src="https://user-images.githubusercontent.com/19826147/36174355-b23c151c-10d1-11e8-96c1-113c0da23f34.png">

> Is this issue related to a specific component? 
yes, Tooltips

> What did you expect to happen? What happened instead? What would you like to see changed?

The ability to place a tooltip without the text being forced bold. 

> What version of the Carbon Design System are you using? 
V8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Containers

**Comment by marijohannessen** [comment]
@bsonefeld @aagonzales should we make it possible to not have bold text for our tooltips?

**Comment by bsonefeld** [comment]
I would vote yes, the user should be able to change the tooltip text style.

**Comment by aagonzales** [comment]
Agreed

**Comment by tay-aitken** [comment]
@carbon-design-system/ui was this ever fixed on the code side? If not @aledavila, can you add this capability into the new tooltips PR #714 for v9?

**Comment by aledavila** [comment]
Ok I’ll take a look at it. I don’t know if it was fixed

**Comment by aledavila** [comment]
Fixed in #714
