### ISSUE TITLE
build-info.json missing from @carbon/icons since 10.9

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#5620]
Hey! Just working on updating icons-angular and I noticed that `build-info.json` disappeared in `10.9.0` ... I use this in the component generation, and it's really handy to be able to just pull it directly from the package.

**Comment by joshblack** [comment]
Hey @cal-smith ! We got a report of this for the svelte team over in: https://github.com/carbon-design-system/carbon/issues/5501 and fixed it in: https://github.com/carbon-design-system/carbon/pull/5536

Should be in the next release IIRC! Sorry about the mixup here 🤦‍♂️

---

Side-note, should we go ahead and remove the icons package from this repo and link out to the new location for the package??

**Comment by cal-smith** [comment]
> Side-note, should we go ahead and remove the icons package from this repo and link out to the new location for the package??

Yeah that sounds like a good idea ... no reason to keep the old codebase around 👍
