### ISSUE TITLE
Tabs component responsiveness bug, button off screen

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#5624]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The tabs component has a responsiveness issue, when reducing the screen size, the last few items are cut off before the responsiveness design changes the layout to a dropdown.

> Is this issue related to a specific component?

Yes, Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When the window size is smaller than the component (starts to cut off), change to dropdown.

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Docs, looking to release Mid April

## Steps to reproduce the issue
1. go to https://react.carbondesignsystem.com/?path=/story/tabs--default
2. keep reducing the window size by expanding the leftnav
3. Notice right most button is cut off (off screen) before the layout changes to a dropdown.
4. This is worse if there are more labels as those buttons will be cut off as well.

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Related https://github.com/carbon-design-system/carbon/issues/4758
