### ISSUE TITLE
Support for TableSelectRow Indeterminate

### ISSUE THREAD

**Issue by a3leong** [carbon-design-system/carbon#5627]
# Summary
I am requesting development for enabling TableSelectRow to have an indeterminate prop that allows the checkbox to have an indeterminate state. This is included in the image below, but I am using 3 tables side by side and they follow a hierarchical view (database has schemas which have tables). In this case, there would be times when not all of the tables of a database are shown thus the reason for requesting this feature.

### Justification
I am trying to implement a design given to me by a design team. The involved screen looks like this

<img width="966" alt="Screen Shot 2020-03-13 at 3 58 34 PM" src="https://user-images.githubusercontent.com/7402877/76665081-ca54f100-6543-11ea-8260-aeeb5d526134.png">

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### Specific timeline issues / requests

It would be ideal to have this by April 15 or at least have a response before then to know whether I should try to implement my own solution instead.

**Comment by asudoh** [comment]
Hi 👋 the underlying [`<InlineCheckbox>` supports `indeterminate` prop](https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/components/InlineCheckbox/InlineCheckbox.js#L37-L40), so I you can create your own version of `<TableSelectRow>` so it propagates `indeterminate` to `<InlineCheckbox>`.

Determining if we should do so our end would require more information wrt the UX your designer gave you. What your designer wanted to communicate user with a table row checkbox with indeterminate state?

**Comment by a3leong** [comment]
I'm going to close this issue, after thinking about the use case for the issue, I think it makes more sense to implement my own version of `<TableSelectRow />` since it seems like handling state between multiple tables of data isn't a common case
