### ISSUE TITLE
[Buttons] Stacking primary and secondary CTA on mobile

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#5636]
### Summary

WHASSSSUUUP CARBON!!! <3 

Current suggested layout for [side-by-side CTAs on mobile](https://www.carbondesignsystem.com/components/modal/style#mobile) is to keep them side by side. Unfortunately this is unrealistic for a lot of products with long button labels. I believe stacking primary and secondary CTAs can be an acceptable alternative.

This suggestion applies to both **fluid** and **fixed** buttons. 

#### Justifications: 
1. To avoid truncating CTA labels - bad UX, bad accessibility...
2. Most teams do not have a content writer. Allowing more text on CTA to spell out what the button will do is better than confusing one word labels. 
3. Translation.
4. Keep the system scalable. People will have one less reason to break from it. 

### Examples

Fixed button stacking 

![image](https://user-images.githubusercontent.com/15144993/76790447-3a0dea80-6795-11ea-9aa6-30f77984c152.png)

Fluid buttons stacking

![image](https://user-images.githubusercontent.com/15144993/76791526-7e9a8580-6797-11ea-9f42-284a915855f3.png)

Another example of long labels on CTAs. As you can see, in this situ, `Cancel` alone will be a very confusing label on any of the buttons. 

![image](https://user-images.githubusercontent.com/15144993/76791604-a2f66200-6797-11ea-9887-c0cab8aff3fe.png)

### Desired UX and success metrics

Reduced production time as developers would not have figure out a way to "hack" the system. 

### Specific timeline issues / requests

Checkout team is required to deliver the new visual design by Q2 2020. Implementation is currently going on. ASAP is always great but we can also retrospectively update the implementation when official feature becomes available. 

### Available extra resources

If possible, we would be happy to contribute this feature. Dev lead on Checkout is @Norm-Sherman

**Comment by dakahn** [comment]
Proposal accepted! :)

**Comment by laurenmrice** [comment]
Closing because this has been added 👍🏻
