### ISSUE TITLE
Modal close button text says "close the modal" instead of "Close"

### ISSUE THREAD

**Issue by cjcarpen** [carbon-design-system/carbon#5639]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The default hover text for the Close button in a modal says "close the modal". 

https://github.com/carbon-design-system/carbon/blob/12c17f126e620db5a6cb2342d8fcb87159037137/packages/react/src/components/Modal/Modal.js#L172

<img width="293" alt="image" src="https://user-images.githubusercontent.com/12972763/76792442-70e5ff80-6799-11ea-925a-3af7b176308c.png">

> Is this issue related to a specific component?

Modal. Might affect other components with the same close button.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The default hover text should just be "Close" according to the Carbon action labels: https://www.carbondesignsystem.com/guidelines/content/action-labels/#C

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

9, 10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud platform (public)

@cdmauney Just an FYI since we've discussed in the past

**Comment by emyarod** [comment]
cc @carbon-design-system/content should we also address any other instances of incorrect default `iconDescription` values? https://github.com/carbon-design-system/carbon/search?l=JavaScript&q=icondescription
