### ISSUE TITLE
Columns in the table should be draggable and repositioned according to user requirement

### ISSUE THREAD

**Issue by Ragha100** [carbon-design-system/carbon#5643]
Hi Team,

We are working on ISD web application, need some customisation options which is columns should be draggable and repositioned according to the user requirement in the table format and as well adjustable column width when dragged from the column corner. currently this option is not available in the Carbon design. Please provide a design and code for this feature.

Thank & regards,
Raghavendar Rao (Raghu) Jukalkar
UX/UI Designer, Advanced Sales Analytics (Strategic Projects)

**Comment by emyarod** [comment]
> I think we've already had a good discussion on this issue. Appropriate at this point for implementation at the PAL level, rather than the core Carbon level, and can discuss long term support and integration at a future date.

quoting @designertyler from this related issue https://github.com/carbon-design-system/carbon/issues/4751
