### ISSUE TITLE
Flexibility to freeze columns during scroll.

### ISSUE THREAD

**Issue by Ragha100** [carbon-design-system/carbon#5644]
Hi Team,

We are working on ISD web application, need some customisation option in the table format, currently this option is not available in the Carbon design. We are facing issue with Frozen column in the table format for example first few columns have been frozen and will remain in position as scroll horizontally. Please provide design and code for this feature.

see the example (external website):
https://adazzle.github.io/react-data-grid/docs/examples/frozen-columns

Thank & regards,
Raghavendar Rao (Raghu) Jukalkar
UX/UI Designer, Advanced Sales Analytics (Strategic Projects)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Seems this is essentially the same as #4748. Don't hesitate to let us know otherwise!

**Comment by Ragha100** [comment]
Hi Team
Where can I see this feature in Carbon Design System, is it available in the Sketch documentation/Carbon's Website. Is it available in Carbon Angular or any tentative time line.
