### ISSUE TITLE
Select drop down does not expand with only one item

### ISSUE THREAD

**Issue by JoelArmendariz** [carbon-design-system/carbon#5647]
## Detailed description

in carbon components react:

When using the Select component that is only populated by one item, it doesn't expand far enough and becomes cluttered with the content under it.

> What browser are you working in?
Firefox

- Screenshots or code

![DropdownBug](https://user-images.githubusercontent.com/53092833/76894737-b1f31800-685c-11ea-83ee-3621cdd78d7e.png)

**Comment by emyarod** [comment]
this is the default `<select>` behavior on macOS (open menu appears on top of the trigger element)
