### ISSUE TITLE
Carbon v10.10.1 NumberInput shouldnot allow aphabets, space and special characters

### ISSUE THREAD

**Issue by sakthi-nathiarasan** [carbon-design-system/carbon#5658]
Hi,
NumberInput is allowing aphabets, space and special characters. Ideally NumberInput should accept only numbers 

Packages:
carbon-components=10.10.1
carbon-components-react=7.10.1

You can reproduce in carbon website https://www.carbondesignsystem.com/components/number-input/code

@asudoh  @amuqeetkhan

**Comment by asudoh** [comment]
Hi 👋 it's UA-specific. If you take a look at [(native) `<input type="number">` example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number), you can type non-number in Firefox, but not in Chrome. So it doesn't make sense to fix it in our code.

**Comment by tw15egan** [comment]
Closing as this is something that can be handled on the user's end.
