### ISSUE TITLE
Create public API matchers for teams to use in test suites

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5660]
We've recently had IBM Security and Watson IoT adopt our testing strategy for a React's component public API. This opens up an opportunity for us to explore shipping custom matchers or helpers to be used by these teams that we also support. In addition to exposing the Public API helper shown in the two PRs below, we might also consider the following situations:

- Verifying `package.json` changes
  - Major use-case is specifying adding a `peerDependency` as a breaking change
- Verifying stable sass paths
  - For paths that the package intends to expose, make sure the paths don't change and verify that they can compile
- Verifying sass public exports
  - Check that sass public exports are available and match the expected type (if possible)

There are also additional matchers that would be useful to expose, for example:

- Accessibility matchers
  - `toHaveNoAxeViolations`
  - `toHaveNoDAPViolations`

https://github.com/carbon-design-system/ibm-security/pull/429
https://github.com/IBM/carbon-addons-iot-react/pull/980

**Comment by joshblack** [comment]
FYI @SimonFinney @tay1orjones

**Comment by SimonFinney** [comment]
This would be awesome! We have also recently incorporated accessibility matchers which also come from Carbon, which I believe other teams may get value from
