### ISSUE TITLE
Accordion child inside another accordion parent is always open

### ISSUE THREAD

**Issue by OmarSherif96** [carbon-design-system/carbon#5666]
Hello,

I am trying to add an Accordion Components inside an Accordion Parent.

However the child components are always open and can't be closed, so is there a certain prop I should fix or is this feature isn't currently enabled ?

Here is what is happening 
![image](https://user-images.githubusercontent.com/46057697/77104211-53789600-6a24-11ea-9c99-6bad0a3c14cf.png)

Thanks

**Comment by asudoh** [comment]
Hi 👋 we don't support nested accordion, please refer to: #4768
