### ISSUE TITLE
UI-shell Header - Vanilla JS

### ISSUE THREAD

**Issue by rac0316** [carbon-design-system/carbon#5668]
## What package(s) are you using?
- [X] `carbon-components`

## Summary

Trying to implement the vanilla js version of ui-shell header but i'm unable to really find any example to get going. Can someone point me in the right direction? All of the examples [here](https://www.carbondesignsystem.com/components/UI-shell-header/code) use React.

Experimental flag for 'ui-shell' have been set to true and I've grabbed html from the only reference I can find, located [here](https://the-carbon-components.netlify.com/?nav=ui-shell), but shouldn't there be some JS initialization somewhere?

Thanks,
Robert

**Comment by asudoh** [comment]
Unfortunately our JSDoc doesn't capture UI Shell code, but you can refer to https://github.com/carbon-design-system/carbon/tree/v10.10.0/packages/components/src/globals/js/mixins to see how to instantiate vanilla JS classes. The vanilla JS classes for UI Shell can be found at `.js` files in https://github.com/carbon-design-system/carbon/tree/v10.10.0/packages/components/src/components/ui-shell (except `ui-shell.config.js`).
