### ISSUE TITLE
Typed error: ‘tabindex=“-1”’ in line 480 of Tooltip.js

### ISSUE THREAD

**Issue by Kimi1020** [carbon-design-system/carbon#5676]
For latest version of Tooltip.js, it seems that tabindex is typed wrong. I check the source code this js file. And I found ‘tabindex=“-1”’ in line 480, which will cause a waring ’Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex` in the browser.

**Comment by asudoh** [comment]
Hi 👋 @Kimi1020 thank you for reporting - Seems the same as #5673, great to have a quick PR!
