### ISSUE TITLE
 Footer - a11y focus issue on version number link and "issue" link.

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#568]
When tab focus moves to the footer of http://carbondesignsystem.com the first link it reaches (currently says "8.10.1") it only performs a color shift on focus and does not show a highly visible focus indicator. I would recommend choosing one appearance for focus indicators on text actions and use it throughout. 

You currently have:

- A solid dark blue border on tabs at the top of the page.
- Browser default focus indicator on the "Email us" <button>  (which is not technically accessible since in some browsers is too light of a blue outline)
- Also have browser default focus indicators on the left menu items. 

I think applying your solid border treatment throughout would be fine. 

> What version of the Carbon Design System are you using? 

8.10.1

## Steps to reproduce the issue

1. Tab to the footer links

## Add labels
a11y

**Comment by bsonefeld** [comment]
Moved to [#168](https://github.com/carbon-design-system/design-system-website/issues/168)
