### ISSUE TITLE
Carbon site - a11y issues on left menu

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#569]
On http://carbondesignsystem.com the left menu has some keyboard interaction issues.

1. After tabbing past the "Search" field the "Getting Started" text does only a color shift to indicate focus which is not a significant enough change to consider it a highly visible focus indicator. 
2. On your second tab the "What's New" text gets a browser default focus indicator which is not technically accessible since in some browsers it is too light of a blue outline.
3. Third tab moves focus to "Guidelines" which is again only a color change.
4. Fourth tab and 5 tabs on "Style" and "Components" are color changes.
5. After tabbing past "Components" the focus disappears, it's technically moving through the sub-menu items of Components but it should have moved instead to the next node of "Add-Ons"
6. After going through all of "Component's" sub-menu items it shifts to "Add-Ons" with a color change. It does not cycle through "Add-Ons" sub-menu items so that is good.
7. Tabbing past "Add-Ons" results in browser default focus indicators on "Component Status" "Themes" and "Resources.

I would suggest using a treatment like a solid dark border similar to your Tab treatment at the top of each page for a focus indicator across the site. 

> What version of the Carbon Design System are you using? 
8.10.1

## Add labels
a11y

**Comment by bsonefeld** [comment]
Moved to [#167](https://github.com/carbon-design-system/design-system-website/issues/167)
