### ISSUE TITLE
[Pictograms]: the vector shape under the “A” of Language-04 should be transparent

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#5691]
I made an issue for this several months ago and can’t seem to find it any longer. Not sure what happened to it but still needs to be fixed

https://www.ibm.com/design/language/iconography/pictograms/library

This one does not need to be shown in the library

![Screen Shot 2020-02-19 at 11.02.09 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/9f427c7e-c10c-4528-a434-33408af2505d)

**Comment by vpicone** [comment]
@joshblack think this has something to do with us removing/changing white rectangles maybe? It's used here to try and mask the bottom part of the A, not sure if this technique is used in any other pictos. 

Would prob wanna address the it at the root (svg processing) if so.

**Comment by joshblack** [comment]
Hmm, yeah just seems like an extra path in the SVG that should be removed. @conradennis @laurenmrice who would this work end up falling on??

**Comment by laurenmrice** [comment]
I believe Michael Dudley owns the final pictogram production files.

**Comment by vpicone** [comment]
@joshblack I think it turning black might be an indication something is off with our svg processing here. This might be happening for other icons/pictos and the rectangle is just less noticeable.

But yeah ideally it's properly masked, not just a white block. That block would show up on any transparent background.

**Comment by joshblack** [comment]
@vpicone I definitely agree the color is 100% coming from it being a path in the SVG 👍 Not sure about the processing step but happy to take a look.
