### ISSUE TITLE
Create shared styles for icon stroke

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5692]
We need to author shared styles similar to how we do now for IDL and our tokens but specifically targeting icon stroke. This issue is for creating the command and code necessary for generating these shared styles.

The naming convention for this feature is: `color / border / <color> / <grade>`

We have a couple of options when it comes to commands, but we could add it to existing color sync commands or do a standalone command. Either works!

**Comment by laurenmrice** [comment]
here is a sketch file with an example of how the color styles should be:
https://ibm.box.com/s/uz7nrdlt1o9szlzb6rz96kti1q8u4fnp

-------------------------------------------------------------------------------------------------

Trying to decide which naming convention makes more sense from a code and sketch perspective. `border` or `stroke`. From a sketch perspective, border makes more sense, is this the terminology you are using in code?

**Comment by emyarod** [comment]
in code it's a stroke but I named it border in my draft PR and will probably keep that since that's what it's called in Sketch

**Comment by laurenmrice** [comment]
ok cool lets go with border
