### ISSUE TITLE
Update pictograms from 48x48 to 32x32

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#5693]
Related to #5550, we would like to update Pictograms in Sketch and in code to _not_ include the 8px padding around the 32x32 artboard.

This issue will involve updating the following parts of our codebase:

- `pictograms`, `pictograms-react`
  - Update exported assets from the default of 48x48 to 32x32
- `sketch`
  - When we have our pictogram command, make sure they render at 32x32 without the padding

**Comment by laurenmrice** [comment]
Also make sure Pictograms are rendering correctly into sketch from the plugin. 

For example: If i download the pictogram `advocate` from the website it looks different from the one generated by sketch.

<img width="948" alt="Screen Shot 2020-03-25 at 11 56 36 AM" src="https://user-images.githubusercontent.com/43969356/77563773-b4bec000-6e8f-11ea-94a1-2285865f994e.png">






The svgs are correct.

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/78822420-a64cca00-79a0-11ea-949f-dc0f4ff7dafe.png)


Running into the above issue with resizing assets, it seems like we might be resizing from a 48x48 canvas which is what is causing it to appear smaller than expected. Reaching out to brand now to see if they can help us identify if this is the case.
