### ISSUE TITLE
Carbon site Search field - a11y issue of placeholder text contrast

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#570]
You have the placeholder text for the word "Search" using the browser default color which is rendering the contrast between it and your background color of #ebf0f7 at a ratio of 2.2:1 in my Firefox on PC browser. Chrome on PC displays a darker passing color value. 

If a user was unable to read that text they may miss knowing there is a search feature on the site at all. 
I would recommend applying some cross-browser consistent CSS to make that color meet contrast requirements. 

Try some styles like these.
::-webkit-input-placeholder {
	font-weight: 300;
	color: #777677;
	font-style: italic;
	font-size: 16px;
}

:-moz-placeholder { /* Firefox 18- */
	font-weight: 300;
	color: #777677;
	font-style: italic;
	font-size: 16px;
}

::-moz-placeholder {  /* Firefox 19+ */
	font-weight: 300;
	color: #777677;
	font-style: italic;
	font-size: 16px; 
}

:-ms-input-placeholder {  
	font-weight: 300;
	color: #777677;
	font-style: italic;
	font-size: 16px;  
}

> What version of the Carbon Design System are you using? 
8.10.1

## Steps to reproduce the issue

1. Use a color contrast tool on the Search text compared to its background.

## Add labels
a11y

**Comment by tw15egan** [comment]
Thanks for making these issues! Just going to port them over to the Design System Website repo

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/design-system-website #166](https://github.com/carbon-design-system/design-system-website/issues/166) via [**ZenHub**](https://www.zenhub.com/)
