### ISSUE TITLE
Add optional character count to text input

### ISSUE THREAD

**Issue by kaylarakower** [carbon-design-system/carbon#5702]
### Summary

Text input with optional character count

![label + character count](https://user-images.githubusercontent.com/48567372/77562853-edae6300-6e96-11ea-94f7-38e039f8783c.jpg)

[Image and sketch file](https://ibm.box.com/s/z6h89nz5nrx5h6j9ajq7ubns75qvzlpe)

### Justification

To create and edit pages on IBM.com, content authors need to know the character limit for all pieces of text, whether it is a single line of text or a paragraph. Currently, character counts are only supported for a text area, Issue #1672  (However, it is missing in [storybook](https://react.carbondesignsystem.com/?path=/story/textarea--default) ). 

When a user is typing into a form field which has a maximum value, that value is communicated to the user, and if the limit is reached, they are informed whilst typing.

### "Must have" functionality
(Copied from #1672 )
Tell the user ahead of time what the value is
Tell the user clearly when they have hit the limit (and stop them entering text)

### Contributors
Team: Marketing Platforms - CMS - EASE
Designer: Kayla Rakower, kayla.rakower@ibm.com

**Comment by emyarod** [comment]
this feature is all but finished. the required component changes to correctly implement this were not merged in and this effort was deprioritized, but when this becomes a focus in a project cycle the work is most of the way there with a few updates (related https://github.com/carbon-design-system/carbon/pull/2745 https://github.com/carbon-design-system/carbon/pull/3054 https://github.com/carbon-design-system/carbon/pull/3106 https://github.com/carbon-design-system/carbon/pull/3097)

**Comment by Mikadv** [comment]
Ah year back now. Any news on this?

**Comment by TannerS** [comment]
Bump, is this actively being worked on? @joshblack  or @tay1orjones ? like is this in the works or road map for carbon or cloud pal?

**Comment by TannerS** [comment]
https://github.com/carbon-design-system/carbon/issues/5702

**Comment by joshblack** [comment]
Hi there @TannerS and @Mikadv! 👋  This is not currently on our roadmap but it is a candidate for Q2 2022 after we ship our v11 release 👍

**Comment by TannerS** [comment]
Issue has been merged

**Comment by tay1orjones** [comment]
@TannerS Great! In the future if you use the specific [autolinking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) GitHub will auto close the related issue(s) when the PR is merged.

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/10442

**Comment by TannerS** [comment]
> @TannerS Great! In the future if you use the specific [autolinking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) GitHub will auto close the related issue(s) when the PR is merged.

Thanks. I didn't know this, will do for the future. Much appreciated!
