### ISSUE TITLE
Image uploader variation

### ISSUE THREAD

**Issue by kaylarakower** [carbon-design-system/carbon#5706]
### Summary

Image uploader variation. Ideal when there is limited space and suitable for uploading a maximum of 1 images as well as multiple images. 

![File uploader](https://user-images.githubusercontent.com/48567372/77577133-a632d180-6eac-11ea-8c38-3e00f1f7eb99.png)

### Justification

We found the following problems with the existing image uploader. Most of the problems were as a result of another:
- When the image uploader is in a small container, the current design takes up too much space
- When in close proximity to a text field, the "item" looks like a text field.
- When I used the ghost button with text and icon, there was too much padding. The link component is ideal, but does not have an option with an icon (should this be a separate contribution?)

Our product with the feature is in development, so please contact me, Kayla Rakower, for more information pertaining to the use case.

Would like to discuss the difference / if we need there to be a difference between the single and multi image uploader with the carbon team.

### "Must have" functionality

- Add image
- Remove individual file
- IF I have added the maximum number of files allowed, THEN "Add file" is disabled.
     - IF I added the maximum number of files AND I remove a file THEN "Add file" is enabled
- Error message persists when a file does not meet requirements AND "Add file" is enabled
- IF there are no files uploaded THEN "Add file" is enabled

An interaction to reorder files is also important, but need to do research on different use cases.

### Contributors
Team: Marketing Platforms - CMS - EASE
Designer: Kayla Rakower, kayla.rakower@ibm.com

**Comment by vpicone** [comment]
@kaylarakower It looks like the proposal is to add an option for a ghost button in the file uploader. I don't think that it would take up "less space" though? 

Could you show an example design where a small ghost button would be preferred?

**Comment by vpicone** [comment]
Gonna close this out, feel free to reach out if it comes up again!
