### ISSUE TITLE
Tree Structure data in the Data table.

### ISSUE THREAD

**Issue by ppillai7777** [carbon-design-system/carbon#5717]
I don't see a way to render tree structure data in DataTable component. There is no such example in react story book.

I would like display tree structure data shown in Ant Design Table component here:
https://ant.design/components/table/#components-table-demo-expand-children

**Comment by abbeyhrt** [comment]
Hi @ppillai7777! We have plans in the works to add a tree data structure. The accepted proposal is documented here: #5180 , let me know if this answers question! Thanks!

**Comment by ppillai7777** [comment]
Thanks for your response.
From the proposal, I'm not sure if Tree Component will be supported in DataTable component. That is our requirement.  Please see the screenshot below. I implemented a tree structure within Ant Design Table.

![image](https://user-images.githubusercontent.com/60336208/77697202-a80f9a00-6f6b-11ea-87c1-0a7e8db5b7e9.png)

**Comment by ppillai7777** [comment]
Could you please confirm that tree view component proposal will also support tree structure data in the Data table component as well?
What is ETA for tree view component? 

I'm part of IBM ECM group and we are working on new product. The UX design requires tree structure data in DataTable component as shown in above screenshot.

**Comment by tw15egan** [comment]
@ppillai7777 there are no current plans support tree structure in the data table component

**Comment by felixair** [comment]
Hi is this '**_Tree Structure data in the Data table. #5717_**' support for now?
Thank you for telling me.
