### ISSUE TITLE
Skills Gateway - New Icons Request

### ISSUE THREAD

**Issue by afields1** [carbon-design-system/carbon#5721]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Please describe your request in one or two sentences.
The Skills Gateway business https://www.ibm.com/services/learning/ would like to modify the existing Skills Level icon into three distinct skills levels (such as Basic, Intermediate and Advance).

There is no icon for individual skills levels. I would like to request a new icon based on the current skill level icon with filled in bars for each skill level.

Current Skill Level:
<img width="319" alt="Screen Shot 2020-03-26 at 12 44 59 PM" src="https://media.github.ibm.com/user/55959/files/fa00f180-6f64-11ea-9135-ba40b2bff78c">
Advance SKill Level:
<img width="319" alt="Advance Skill Level" src="https://media.github.ibm.com/user/55959/files/0cc9f500-6f6a-11ea-9788-9d5a2aa4e6d3">
Intermediate Skill Level:
<img width="319" alt="Intermediate Skill Level" src="https://media.github.ibm.com/user/55959/files/105d7c00-6f6a-11ea-8a31-12751086ca0f">
Basic Skill Level:
<img width="319" alt="Basic Skill Level" src="https://media.github.ibm.com/user/55959/files/bf01bc80-6f6a-11ea-988f-960d8b0213b3">
[skill-level.svg.zip](https://github.ibm.com/Training-Skills/pipeline/files/530664/skill-level.svg.zip)

Clarify if you are asking for design, development, or both design and
development.
I am asking for development.  I have included the designs above.

### Justification

Provide the business reasons for this request.
Use case:
These icons are needed for consistency across all the learning applications course skill levels such as follows: Skills Gateway course : https://www.ibm.com/services/learning/course/ZZ870G

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.
The icon will be in synch with the verbage for each skill level.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?
We would like to release this within our next sprint around April 10th.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._
I do not have Sketch for building these icons.  I will need assistance.

**Comment by afields1** [comment]
@conradennis Can you assist me with this request?

**Comment by afields1** [comment]
@joshblack Can you help me get this issue assigned?

**Comment by joshblack** [comment]
Hey @afields1! 👋 @conradennis will be the point of contact for this request 👀

**Comment by conradennis** [comment]
will post them shortly, I can provide the SVGs as soon as today and can add them to the repo with my next batch some time next week

**Comment by conradennis** [comment]
@afields1 finals are shown below, I can deliver the SVGs on slack

<img width="1166" alt="Screen Shot 2020-04-02 at 1 18 27 PM" src="https://user-images.githubusercontent.com/16782944/78278723-76a34b00-74e4-11ea-8a7c-4e15df6972d8.png">

**Comment by conradennis** [comment]
made the icons, will include in PR for next batch of icons. @joshblack issue can be closed
