### ISSUE TITLE
Element property is Hidden, selenium not able to click or select the element even X-path is correct

### ISSUE THREAD

**Issue by vinakred** [carbon-design-system/carbon#5729]
@asudoh 

When we try to enter the text in search box which is hidden element, selenium is not able to find the element even x-path is correct. selenium throws not able to find the element.
Hidden element property changes to false when we click, and when we click out side element property again changes to true.

Please find the screen shot for the same.

![image](https://user-images.githubusercontent.com/62745227/77744526-bfb85280-703f-11ea-97b0-59f332199058.png)

**Comment by asudoh** [comment]
The screenshot provides a little context on what component you got such markup from... Anyhow, Selenium (WebDriver) provides plenty of APIs such as [running JavaScript code in browser](https://selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebDriver.html#executeScript) (e.g. to change the DOM e.g. to add/remove attributes). Would you want to try?

In general, changing UI component code for the sake of E2E testing should be avoided and the case having to do that is very, very rare.

**Comment by tw15egan** [comment]
@vinakred does the suggestion from @asudoh work for you?

**Comment by vinakred** [comment]
> @vinakred does the suggestion from @asudoh work for you?

Hi Egan, sorry for late reply, I tried and it worked for me, I was able to click the search tool bar and enter the text to it using java script. if is there any other alternative also please let us know. 
since we run this code in docker environment, we expect it should work with out any extra installations.

**Comment by asudoh** [comment]
Thank you for your confirmation @vinakred!
