### ISSUE TITLE
[Inline-Notification Bug]: Lacks responsive design to long action labels (On Mobile)

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon#5730]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

In our application, we make use of a carbon inline notification to allow our users to provide feedback about their experience. The call to action label on the notification is long - 'Give us your feedback'. On mobile, this causes the notification to produce undesirable effects, namely:
- The main content (i.e. the subtitle) is has a small width, resulting in the notification stretching down the page. This is difficult to read.
- The `Close` button is outside of the Notification box, (functionally fine, but looks scrappy)

https://codesandbox.io/s/zen-wright-f9px3

> Is this issue related to a specific component?

Inline Notification

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.10.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Work for IBM CIO team, with our release date being 27th March.
Note, as a temporary fix for our project, we have overwritten the inline notification class
```
.bx--inline-notification {
  min-width: 20rem;
  max-width: none
}
```
 
## Steps to reproduce the issue

1. https://codesandbox.io/s/zen-wright-f9px3
2. Change the viewport to a mobile screen.

## Additional information

- Screenshots or code
<img width="349" alt="Screenshot 2020-03-27 at 14 38 50" src="https://user-images.githubusercontent.com/56296356/77767298-c1324c80-7038-11ea-8e48-18f94e76488e.png">
<img width="351" alt="Screenshot 2020-03-27 at 14 38 41" src="https://user-images.githubusercontent.com/56296356/77767308-c42d3d00-7038-11ea-932f-4bcb90732724.png">
- Notes

**Comment by tw15egan** [comment]
@carbon-design-system/design How should we handle these situations on mobile? Here is what our current example looks like on iPhone (chrome dev tools)

<img width="483" alt="Screen Shot 2020-03-27 at 9 55 26 AM" src="https://user-images.githubusercontent.com/11928039/77780411-2ffbaf80-7011-11ea-8bf1-576702b76968.png">

**Comment by aagonzales** [comment]
The action should reflow to be positioned under the subtitle text. 

![image](https://user-images.githubusercontent.com/11670886/77797878-d8286d00-703f-11ea-9122-11f2c5d6fba3.png)
