### ISSUE TITLE
By default if using the FileUploader component(s) files can be DnD-ed everywhere

### ISSUE THREAD

**Issue by modean** [carbon-design-system/carbon#5732]
### Summary

If using the `FileUploaderDropContainer` component the default behaviour is as follows:

1. Files, e.g. text files can be dropped onto the drop area which is correct. The logic that is wired to the drop area will kick-in which is also correct.
2. If DnD-ing a text file it is by default also possible to drop it anywhere in the user agent's (browser) real estate. The user agent will then render the contents of the text file.

Instead if a SPA (web site) is making use of a `FileUploaderDropContainer` component it should be considered that in that case dropping files outside the drop area must not be possible. If doing so this would (A) prevent accidental drops and thus requiring the user to browser back cause the context of the application just vanished and (B) it also makes it more clear where files can be dropped and where not.  

### Justification

Improved usability. See above under summary.

**Comment by emyarod** [comment]
this is default browser behavior and not affected by the Carbon component directly. if I understand correctly the fix for this would be at the application level: https://codesandbox.io/s/hungry-pascal-6xnt5

```jsx
const handleDrop = e => {
  e.preventDefault();
};
const handleDragover = e => {
  e.preventDefault();
};
useEffect(() => {
  document.addEventListener("drop", handleDrop);
  document.addEventListener("dragover", handleDragover);
  return () => {
    document.removeEventListener("drop", handleDrop);
    document.removeEventListener("dragover", handleDragover);
  };
}, []);
```

**Comment by modean** [comment]
Note that of course this is the default behaviour. That was not my point. The point was to raise the question whether the component itself could implement what otherwise would need to be implemented by every consumer of the component. As a matter of fact we already implemented a listener on the window object that checks whether during dragOver the file is over the dropzone or over something else.

So indeed the feature request question was whether what you did in the sample app above wrt/ to the `drop` and `dragover` listeners shall be part of the component itself.

**Comment by emyarod** [comment]
I think this is up to the application developer to handle, since if we make this assumption out of the box it may interfere with applications that have other drag and drop behavior or applications that contain draggable elements in general
