### ISSUE TITLE
feat(structured-list): Add React component support for the condensed structured list styles

### ISSUE THREAD

**Issue by zJag** [carbon-design-system/carbon#5736]
### Summary

The `carbon-components` repo has styles for a condensed structured list using the class `{prefix}--structured-list--condensed`. The React component `StructuredListWrapper` should have a prop that toggles this class, similar to how there are props to change the sizing of `Button` and `DataTable`.

The styles can currently be added by manually including the class under the className prop.

### Justification

Since `carbon-components` have the styles, it should be supported in `carbon-components-react`.

### Desired UX and success metrics

A user can set a prop to toggle the class on the StructuredListWrapper.

### "Must have" functionality

An easy way to add the condensed class to the React component.

### Specific timeline issues / requests

As there is a workaround to add this feature, there is no specific timeline.

### Available extra resources

I've added this feature in my forked carbon repo already. I will be able to submit a PR to add this feature.

**Comment by asudoh** [comment]
Hi 👋 seems that adding that support makes sense, unless our designer considers that mode is a legacy one. CC @carbon-design-system/design
