### ISSUE TITLE
a11y - "Danger" buttons are using color alone to indicate danger

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#574]
On the Buttons page there is an example showing "Danger buttons" where their text and border color is red and achieved by using a specific class on the button tag. 

http://carbondesignsystem.com/components/button/code

I would suggest not using color alone to indicate warnings or danger. Add an additional danger icon with sufficient contrast in addition so that the danger is relayed more inclusively. 

> Is this issue related to a specific component? 
Buttons

> What version of the Carbon Design System are you using? 
8.10.1

## Add labels
a11y

**Comment by koolamusic** [comment]
can this be done ?

**Comment by tay-aitken** [comment]
Color is the secondary indicator in this case. The text on the button should indicate that the action the user is taken can be dangerous (i.e. delete, remove, etc.).

We will also make sure the button has a danger aria label.
