### ISSUE TITLE
SCRIPT1014: Invalid character error on IE11

### ISSUE THREAD

**Issue by jdcai** [carbon-design-system/carbon#5740]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

IE11 is giving me this error SCRIPT1014: Invalid character and links to the file
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/js/settings.js

It complains about the \` character for `selectorTabbable:` and `selectorFocusable:`
IE11 doesn't support it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

> Is this issue related to a specific component?

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/js/settings.js

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Should be changed so that it works in IE which means switching to something equivalent that doesn't use the ` character
> What browser are you working in?

IE11
> What version of the Carbon Design System are you using?

"carbon-components": "10.10.2"

## Steps to reproduce the issue
I'm not sure how I got it to happen but one way to see the error is to
make a html file with the settings js file <script src="settings.js"></script> and open in IE11

**Comment by asudoh** [comment]
Hi 👋 the code in `src` is not meant to be directly be used by applications (honestly, I believe shipping that directory was a mistake). You can use code in `es` directory instead, which is a Babel-transpiled version and thus the template literals are transpiled to plain strings.
