### ISSUE TITLE
a11y - Large Loading spinner is very light in color

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#575]
Could you use a darker color value for the large loading spinner so it has more contrast against a light background? 

While not yet a requirement in WCAG there are suggestions of at least a 3:1 ratio for graphic elements.

https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

> What version of the Carbon Design System are you using? 
8.10.1

## Add labels
a11y

**Comment by tay-aitken** [comment]
We will be addressing this in our v9 release coming June 1st. Thanks for making an issue.
