### ISSUE TITLE
How to use Grid in react?

### ISSUE THREAD

**Issue by klower** [carbon-design-system/carbon#5751]
I cannot import :
import { Grid, Row, Column } from 'carbon-components-react';
I have installed by:
npm install carbon-components carbon-components-react carbon-icons @carbon/icons-react

**Comment by joshblack** [comment]
Hi @klower! 👋  Here's a codesandbox that shows a quick way to get started: https://codesandbox.io/s/fervent-euler-6o6yn There is also a storybook example if you would like to see all the different ways you can use this component [here](https://react.carbondesignsystem.com/?path=/story/grid--auto-columns)

To use this in your project, you'll need to make sure that the styles for grid are included and that you're using `carbon-components-react` v10.9.0 or newer.

Hope this helps!

**Comment by moficodes** [comment]
@joshblack what would the import for grid look like.

`import {Grid, Row, Column} from "carbon-components-react";` fails saying it is not exported.

**Comment by DrankoLQ** [comment]
Hi! 

I've had problems importing Grid, Row and Column too and, if I'm not wrong, looks like its Typescripts types are missing

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react/lib/components

Are you folks using Typescript too?

**Comment by joshblack** [comment]
Hey @moficodes! 👋 Most likely you'll need to update your version of Carbon to a newer version if they're unavailable (I think they're in v10.9 or v10.10, forgot which!)

Hey @DrankoLQ! 👋 Unfortunately, we don't maintain the TypeScript binding for the library so it is a community-driven effort. I would follow the process for contributing types to the package through DefinitelyTyped if you're interested in using these components 👀

**Comment by DrankoLQ** [comment]
Hey @joshblack , thanks for the quick reply! 

We are currently using Carbon in a few projects and migrating to Typescript so we are interested. I'm happy to help as much as I can with that 👏

Btw, the latest version for `carbon-components` listed in npm is `10.11.2`, the one I'm currently using cc @moficodes
