### ISSUE TITLE
DataTable knobs are not taking affect!

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#5753]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I updated to latest version (7.10.3) and I'm trying to use some features of the DataTable; Like:
size="short"
  stickyHeader
  useZebraStyles

But it's not taking affect!

## Relevant information

https://codesandbox.io/s/codesandbox-s4osh

**Comment by joshblack** [comment]
Hi there @zbeedatm! 👋 I believe you need to use `getTableProps` and apply it to `Table` in order to get these settings to apply. Here is a link to the updated codesandbox with this applied: https://codesandbox.io/s/codesandbox-lvyy5

Just a quick note, `stickyHeader` is an experimental feature and is not guaranteed to follow semver 👍

Hope this helps!

**Comment by zbeedatm** [comment]
Hi,
The `stickyHeader ` still doesn't take affect (I believe it's still experimental).
Any planes for this feature release soon?

Regards.

**Comment by zbeedatm** [comment]
Hi,
It seems that few months later, the `stickyHeader` is still experimental.
I started using it, but having issue with the height of the table which shrink when using this property!

tried overcome it by customizing:

> .bx--data-table {
    max-height: none;
}

But it caused loosing the sticky header functionality.

Can you please try to help to find a way using it without loosing the orginal height?

[Sandbox](https://codesandbox.io/s/codesandbox-uqj3o)

**Comment by zbeedatm** [comment]
> .bx--data-table--sticky-header {
   display: inline-table;
}

(instead of original display: block)

gave good results, despite having the columns header names cut with "..."
tried to fix it by:

> .bx--table-header-label {
    overflow-x: visible;
}

(instead of original overflow-x:  hidden;)
But didn't help.
![image](https://user-images.githubusercontent.com/26740851/87400747-dc15d600-c5c1-11ea-8f3d-085152624010.png)
