### ISSUE TITLE
[icons] rendering problems with sketch

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5758]
The actual icon asset is rendering a little off when be put into sketch. This may be something Conrad will need to look into.

--------------------------------------------------------------------------------------------------

`16/help--filled` Has an uneven circle in the question mark
<img width="817" alt="Screen Shot 2020-03-30 at 11 30 39 AM" src="https://user-images.githubusercontent.com/43969356/77937450-f7124380-7279-11ea-9948-ef134e75a427.png">

`16/information--filled` and `16/information` Have uneven circle in the i.
<img width="626" alt="Screen Shot 2020-03-30 at 11 31 33 AM" src="https://user-images.githubusercontent.com/43969356/77937613-3345a400-727a-11ea-8741-a630e846db46.png">

`16/notification`and `16/notification--off` gets weird rendering around corners
<img width="798" alt="Screen Shot 2020-03-30 at 10 24 14 AM" src="https://user-images.githubusercontent.com/43969356/77930594-b104b200-7270-11ea-981b-1890911e4ffe.png">

16px only: `play` `play--outline` gets weird rendering around corners
<img width="740" alt="Screen Shot 2020-03-30 at 10 27 56 AM" src="https://user-images.githubusercontent.com/43969356/77930990-2f615400-7271-11ea-81d1-fd5440e0b613.png">

`20/redo` gets weird rendering on arrow line
<img width="479" alt="Screen Shot 2020-03-30 at 10 36 33 AM" src="https://user-images.githubusercontent.com/43969356/77931932-73a12400-7272-11ea-8265-6ce293895928.png">

 `16/save` is getting weird rendering on corners.

<img width="793" alt="Screen Shot 2020-03-30 at 11 48 52 AM" src="https://user-images.githubusercontent.com/43969356/77939210-70129a80-727c-11ea-8e75-208786843369.png">

`16/star`  and `20/star` are getting weird rendering on corners.
<img width="1005" alt="Screen Shot 2020-03-30 at 11 52 53 AM" src="https://user-images.githubusercontent.com/43969356/77939621-1199ec00-727d-11ea-97d6-9519a00fb4e2.png">

`16/view` and `16/view--off` has cutoff ends and weird rendering.
<img width="966" alt="Screen Shot 2020-03-30 at 12 00 04 PM" src="https://user-images.githubusercontent.com/43969356/77940285-16ab6b00-727e-11ea-8274-e294414f98f1.png">

`16/warning--alt--filled` and `16/warning--alt`are getting weird rendering on corners.
<img width="872" alt="Screen Shot 2020-03-30 at 12 06 31 PM" src="https://user-images.githubusercontent.com/43969356/77940854-e7492e00-727e-11ea-8a73-42ecf47b5a0d.png">

`16/warning--filled` has an uneven circle of the exclamation point.

<img width="823" alt="Screen Shot 2020-03-30 at 12 05 54 PM" src="https://user-images.githubusercontent.com/43969356/77940927-02b43900-727f-11ea-83f3-cdcd7e38e605.png">

`16/asleep` gets weird rendering around corners
<img width="669" alt="Screen Shot 2020-03-30 at 11 23 24 AM" src="https://user-images.githubusercontent.com/43969356/77936791-0349d100-7279-11ea-9baa-464f470e2053.png">

**Comment by joshblack** [comment]
cc @conradennis would you have time to sync up on some of these rendering issues that we're noticing?

**Comment by conradennis** [comment]
@joshblack for sure, feel free to put some time on my calendar

**Comment by laurenmrice** [comment]
closing  🎉 Pr fix: https://github.com/carbon-design-system/carbon/pull/7126
