### ISSUE TITLE
[slider text input] Can't enter desired number when minimum is specified

### ISSUE THREAD

**Issue by djlalwet** [carbon-design-system/carbon#5766]
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
It is impossible to enter a number below the minimum in the text input field. If the minimum is 10, and I would like to enter 19, this is not possible by deleting the text input contents and entering "1" then "9".

> Is this issue related to a specific component?
Slider

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Entering a number below the minimum is possible until finalized. An invalid number below the minimum should update to the minimum when finalized (pressing enter, clicking elsewhere).

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.10.3",
    "carbon-components-react": "^7.10.3",

## Steps to reproduce the issue

1. Create a slider with a minimum value of 10 and text input is not hidden
2. Delete text in text input
3. Enter single digit number

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - I think this is the same as #3107, feel free to let us know otherwise.
