### ISSUE TITLE
UX Query - DataTable, batch actions and pagination

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#5769]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Summary

When using a DataTable with batch actions each row has a checkbox. With row(s) selected should the user be able to change the page or page size? If so are the items still selected and batch actions still shown?

## Relevant information

![image](https://user-images.githubusercontent.com/15086604/78126824-083e8a00-740b-11ea-8611-038cb0a6a32f.png)
![image](https://user-images.githubusercontent.com/15086604/78126879-1e4c4a80-740b-11ea-87cd-ab3b56420f2e.png)

Should any row still be selected?

or 
![image](https://user-images.githubusercontent.com/15086604/78127011-52277000-740b-11ea-86ee-87811ae31a28.png)
![image](https://user-images.githubusercontent.com/15086604/78127038-5ce20500-740b-11ea-84f8-879593896e23.png)

Should row 7 still be selected?

**Comment by joshblack** [comment]
> With row(s) selected should the user be able to change the page or page size? 

I think the intent would be _yes_ ideally

> If so are the items still selected and batch actions still shown?

I think the hope would be that the selection would be tied to the item's `id` (however that's computed) and the change in page size would have them stay selected and have the bar still shown.

---

@laurenmrice let me know if this is off!

**Comment by laurenmrice** [comment]
Yes to what Josh said above ^ . You should be able to change pages when the batch action is activated. When you change pages, the selection(s) you made on a previous page should still be selected.
