### ISSUE TITLE
Add-Ons > Order Summary > Two mystery tab stops in interaction

### ISSUE THREAD

**Issue by arbydev** [carbon-design-system/carbon#577]
On the Order Summary example
http://carbondesignsystem.com/add-ons/order-summary/code

When you tab through this interaction the tab order starts correctly at the upper left for the pricing menu.
Pressing tab again appears to do nothing. Nor does a second tab. 
On the third tab the focus is moved to the "Create Cluster" button. 

Could you eliminate the two tab stops in-between?

> What version of the Carbon Design System are you using? 
8.10.1

## Add labels
a11y

**Comment by marijohannessen** [comment]
Hi @arbydev ! Thanks for making this issue, I noticed this when I did an a11y audit of our React components. I will make sure we fix this in both repos 👍

**Comment by marijohannessen** [comment]
It seems like this is because of the Dropdown component, and the tab index on each dropdown item. We'll need to add some logic in the javascript that changes the tab index from -1 to 1 when the menu is open.
