### ISSUE TITLE
Toggle labels display on 2 lines when too long

### ISSUE THREAD

**Issue by cdouine39** [carbon-design-system/carbon#5771]
## What package(s) are you using? 
![image](https://user-images.githubusercontent.com/23524780/78159015-47d49880-7442-11ea-873e-1679074485f1.png)

## Detailed description

> Describe in detail the issue you're having.

When i use a toggle with long labels, they appear on 2 lines while there is a lot of space to display them on 1 line : 
![image](https://user-images.githubusercontent.com/23524780/78159119-69358480-7442-11ea-9cab-dc3562d7f906.png)

> Is this issue related to a specific component?

Yes, Toggle component 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the label to be displayed on 1 line like this : 
![image](https://user-images.githubusercontent.com/23524780/78159197-8702e980-7442-11ea-8176-2355cc88a912.png)

> What browser are you working in?

Chrome 80

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/carbon-components-react-qojzy

**Comment by emyarod** [comment]
it looks like your dependencies are out of date and this is a fixed issue in newer package versions (ref #5392 #5393)

the workaround for you would be to add this to your stylesheet:

```css
.bx--toggle__text--left,
.bx--toggle__text--right {
  white-space: nowrap;
}
```
