### ISSUE TITLE
Carbon Grid - best practice

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon#5777]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

I'm trying to implement a layout from the Carbon site:
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#mix-and-match
My approaches were the following (my preferred one is the 3rd):
(please ignore the usage of `<br />` in the examples, because they are only used to reduce CSS)
1. everything in one grid:
which seems wrong because the “side panel” (aside) is separate from the main content
Example: https://codepen.io/conradschmidt/pen/d662b0b3f92461445eeb69119c14f94f

2. main content in a grid and the “side panel” as influencer:
but then the grid overlay is not fitting, because an influencer is separate from the main grid
Example:: https://codepen.io/conradschmidt/pen/6b22d83610764ea43f029bed20f96667
Example (withoverlay): https://codepen.io/conradschmidt/pen/8d6cd6183e83f0406bcd515349925965

3. 2 grids next to each other:
but then the column definitions are “off” - a col-md-4 is using 3 cols, instead of 4
Example: https://codepen.io/conradschmidt/pen/366af7c925afb2aa2273fab5ba169c03
Example (with overlay): https://codepen.io/conradschmidt/pen/498831043a7c521d90893cb0613a0c4c

Here is an image of the "off" column definition (3rd approach):
![image](https://user-images.githubusercontent.com/3808948/78167881-802ea380-744f-11ea-9192-9d660831ebca.png)

## Questions

Is there another approach to this layout?
If not, can these "off" columns definitions be avoided?
Is there any plan to implement the layouts on the Carbon site, to provide better guidance on the grid?

**Comment by joshblack** [comment]
Hi @ConradSchmidt! 👋 These are great points for grid usage and definitely highlights some of the challenges with leveraging the grid 😞 

I think the hope with this layout is that you could have one conceptual grid and then can mix-and-match at the row level if you need to switch "grid modes" (like going to condensed) but as you noted this doesn't really work when the hierarchy of the markup is off.
