### ISSUE TITLE
[Dropdown] - initialSelectedItem prop doesn't add selected styles

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#5778]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When you have a dropdown with an initial selected item, the item doesn't receive the selected styles until you click on it or on another option, which is not how an initial selected item should work.

https://codesandbox.io/s/wispy-water-t6s3c

#### initial selected item doesn't have styles
<img width="965" alt="Screen Shot 2020-04-01 at 2 21 58 PM" src="https://user-images.githubusercontent.com/32556167/78177740-2fee1c00-7424-11ea-90c8-7e327f26e088.png">

#### initial selected item after clicking on it 
<img width="968" alt="Screen Shot 2020-04-01 at 2 22 06 PM" src="https://user-images.githubusercontent.com/32556167/78177741-311f4900-7424-11ea-89bc-cadbc2d6d86d.png">

**Comment by asudoh** [comment]
Hi 👋 @jnm2377 `initialSelectedItem` should be object reference of one of the `items`. That said, `initialSelectedItem={items[1]}` makes your example work.

**Comment by tw15egan** [comment]
Thanks for solving this for us @asudoh 👍
