### ISSUE TITLE
OverflowMenu issue with accessible name mismatch

### ISSUE THREAD

**Issue by darosale** [carbon-design-system/carbon#5779]
DAP is flagging the OverflowMenu with:
Accessible name does match or contain the visible label text.

The component is being built with a hardcoded aria-label for the icon. This forces the aria-label of the button to include that string in order to satisfy the guidelines.
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/OverflowMenu/OverflowMenu.js#L216

Furthermore, when the menu is open, the visible label text changes value and the button label needs to accommodate that as well.

![image](https://user-images.githubusercontent.com/3640410/78187955-05588f00-7435-11ea-8f39-832d3c961a10.png)

**Comment by asudoh** [comment]
HI 👋 thank you for reporting. Given [the code you referred to](https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/components/OverflowMenu/OverflowMenu.js#L216) is React `defaultProps`, you can change the corresponding React prop (`iconDescription`) that should change `aria-label` as well as `title`.
