### ISSUE TITLE
Code Snippet react component has a strange gradient also apparent on hover

### ISSUE THREAD

**Issue by IdanAdar** [carbon-design-system/carbon#5790]
Carbon 10.10.3

Here's a screen shot:

<img width="772" alt="Screen Shot 2020-04-02 at 18 59 39" src="https://user-images.githubusercontent.com/7255583/78272574-5ab89d00-7516-11ea-8707-4d4ad26fbba4.png">

**Comment by emyarod** [comment]
related #5507

this is not reproducible in our storybook (https://carbon-components-react.netlify.com/?path=/story/codesnippet--single-line)

can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by joshblack** [comment]
@emyarod seems like it might have been addressed in a later release? It's currently visible on latest stable.

**Comment by emyarod** [comment]
yes this should be resolved

**Comment by joshblack** [comment]
Reached out in Slack! Should be resolved in v10.11
