### ISSUE TITLE
[CodeSnippet]: single-line variant's scroll gradient clips through focus outline

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#5801]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

<img width="853" alt="Screen Shot 2020-04-03 at 8 45 42 AM" src="https://user-images.githubusercontent.com/9057921/78367848-54fb9f80-7588-11ea-929f-37eb2f5f18f9.png">

When you click inside the single-line variant of the `CodeSnippet`, the scroll/overflow gradient clips through the focus outline.

## Steps to reproduce the issue

Go to storybook & click inside the single-line `CodeSnippet`: https://react.carbondesignsystem.com/?path=/story/codesnippet--single-line

**Comment by jendowns** [comment]
I created a PR for this here: https://github.com/carbon-design-system/carbon/pull/5802

**Comment by emyarod** [comment]
ref https://github.com/carbon-design-system/carbon/issues/5790 https://github.com/carbon-design-system/carbon/issues/5507

this issue should already be resolved. it seems this is only present in an older build as this is not reproducible in the latest storybook (https://carbon-components-react.netlify.com/?path=/story/codesnippet--single-line)

**Comment by jendowns** [comment]
thank you! I will go ahead & close this out
