### ISSUE TITLE
Scrollbar for Dropdown

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5807]
## Problem
Only three options are displayes and there's no indicator that there's more options available

## Solution
Scrollbar for Dropdown

## Screenshot
![Screenshot (159)](https://user-images.githubusercontent.com/59839368/78418728-b42ae400-765c-11ea-9f2a-18f51f5ee44f.png)

**Comment by jakubfaliszewski** [comment]
FYI: Scrollbar visibility was set that way only in docs:
![image](https://user-images.githubusercontent.com/25402419/78545216-b5dede00-77fb-11ea-898c-d171db7c71f8.png)

When you're using Dropdown in your project it works fine.
![image](https://user-images.githubusercontent.com/25402419/78545294-dd35ab00-77fb-11ea-8c90-36c337eb685a.png)

**Comment by ghost** [comment]
there's no reason for it to be that way in docs.

could you change that?

**Comment by jakubfaliszewski** [comment]
Yeah, I'm not Carbon team member, but why not 😄 
But, please, create Issue for this [here](https://github.com/carbon-design-system/carbon-website/issues ), in docs repo, and ask Carbon Team for this. I guess that they had some reasons for disabling visibility of scrollbar.

**Comment by emyarod** [comment]
closing due to this issue being opened in the correct repo here https://github.com/carbon-design-system/carbon-website/issues/1095
