### ISSUE TITLE
Show more button does not appear when code snippet is put in a tab

### ISSUE THREAD

**Issue by Donisius** [carbon-design-system/carbon#5819]
## What package(s) are you using?

```
    "carbon-components": "10.9.3",
    "carbon-components-react": "7.9.3",
```

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If you put a code snippet in the very first tab that is opened with overflow content, the show more button appears, putting the code snippet in other tabs prevents the button from appearing. 

> Is this issue related to a specific component?

Code snippet and tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Show more button should appear.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.9.3

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?
