### ISSUE TITLE
MultiSelect initialSelectedItems

### ISSUE THREAD

**Issue by bourdakos1** [carbon-design-system/carbon#5821]
The `MultiSelect` component has an `initialSelectedItems` prop that can only be set once.

usage:
```react
const [selected, setSelected] = useState(["cat"])
<MultiSelect initialSelectedItems={selected}>
```
behavior: `cat` is selected

update selected state:
```react
setSelected(["dog", "fish"])
```
behavior: `cat` is selected
expected: `dog` and `fish` are selected

**Comment by emyarod** [comment]
related #4812

**Comment by bourdakos1** [comment]
@MaxShapiro32

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. Given the nature of `initialSomething` properties, it's not meant for after-creation updates. So looks that your request is same as #4812 as @emyarod pointed out.
