### ISSUE TITLE
Pictograms: Certain pictograms are missing

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon#5825]
## Detailed description

Java, JS, Mas, Mqa, SSO pictos are missing and instead displayed as api picto. 
The icons for the above mentioned topics should be displayed correctly.
Firefox, Chrome

## Steps to reproduce the issue

1. Step one: Go to carbondesignsystem.com
2. Step two: Click on Guidelines and then to pictograms
3. Step three: Go to one of the icons shown above
4. See the issue

## Additional information

<img width="1289" alt="Screenshot 2020-04-07 at 13 41 03" src="https://user-images.githubusercontent.com/47037236/78681230-be631180-78ec-11ea-856a-075c5fd52979.png">

**Comment by joshblack** [comment]
@conradennis it seems like in the SVG output that they try and use the font family IBM Plex Sans which is causing some of the issues. Would there be any way for the text to be a path instead of referring to the font or is that not do-able?

**Comment by conradennis** [comment]
@joshblack I'll ask the production team to take a look at the issue and make a decision. Prob should make the text a path
