### ISSUE TITLE
TileGroup ignores its className property

### ISSUE THREAD

**Issue by renmaddox** [carbon-design-system/carbon#5828]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

TileGroup.js documents a className property, but it doesn't use it.

**Comment by jakubfaliszewski** [comment]
What do you mean by that? Can you provide some demo?

Example of use:
https://codesandbox.io/s/gifted-brattain-l16nx?file=/index.js
![image](https://user-images.githubusercontent.com/25402419/78897527-9e5d5a80-7a72-11ea-8a3d-2de97fc6307c.png)
![image](https://user-images.githubusercontent.com/25402419/78897541-a3baa500-7a72-11ea-97bc-d8a9e4745c5c.png)

**Comment by renmaddox** [comment]
Never mind -- I was confused.
