### ISSUE TITLE
[pictograms] list of pictos that have circle fills

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5829]
If we can't get fills and borders to coexist in pictograms from code and/or change the container sizes to scale without the pictogram: I am thinking we should ask brand if we can have a specific export of the svgs on 32px container sizes with strokes expanded for product.

Otherwise these are a lot of pictograms that have fills and borders that are not rendering properly in sketch right now. And our color styles in Sketch will never match up consistently to the pictogram when changing its color :

`amsterdam--canal`
`app--developer`
`application`
`augmented--reality`
`bangalore`
`berlin cathedral`
`bulldozer`
`care`
`chart--scatterplot`
`console--wireless`
`console`
`conversation`
`data--backup`
`data--processing`
`design--and--development--01`
`design--and--development--02`
`dialogue`
`docker`
`door handle`
`enterprise--design--thinking`
`face--dissatisfied`
`face--neutral`
`face--satisfied`
`face--very--dissatisfied`
`face--very--satisfied`
`globe--locations`
`hail`
`hail--heavy`
`hail--mixed`
`hard--drive--network`
`hard--drive`
`intercom`
`lock--alt`
`lock`
`locked--network--alt`
`locked--network`
`london`
`london--expanded--base`
`madrid--cathedral`
`madrid--statue`
`magnify`
`melbourne`
`mobile--add`
`mobile--chat`
`mobile--devices`
`mobile--phone`
`nice`
`oil--pump`
`petri--culture`
`private--network--01`
`private--network--alt--01`
`private--network--alt`
`private--network`
`question--and--answer`
`question`
`robotics`
`saas--enablement`
`secure--profile`
`speech--to--text`
`stethoscope`
`target--area`
`target`
`text--to--speech`
`tone--analyzer`
`unlock--alt`
`unlock`
`video--chat`
`warning--alt`
`warning`
`washington--D.C.--capitol`
`web--developer`
`windows`
`wireless--modem`
`wrecking--ball`

**Comment by joshblack** [comment]
cc @dudley-ibm @conradennis do you all think this would be realistic to do? 👀

**Comment by dudley-ibm** [comment]
So that I understand, is the ask to create a second .svg export of every pictogram with expanded strokes?

**Comment by laurenmrice** [comment]
Yes and for them to be exported at 32px. I understand this was being done in general because pictograms can be used for larger scale, but for product specifically could we do this?

Since strokes are not expanded anymore, most of the pictograms come into sketch using a `border` instead of a `fill`. All of IDLs color palette colors are using `fill` color styles in sketch, so if you tried to attach a color style to a pictogram it will fill the pictogram with a block of color instead of the outlines. 

We tried to troubleshoot this with making an identical set of color styles for the IDL color palette using only `borders`. However, some of the pictograms (listed above in this issue^) have both border and fills because of the circles. Which then would not work for either color style properties., because we can't pick and choose which ones will show up as borders vs fills vs with both.

If the strokes were expanded, or if there was a setting that would make them come in as fills to sketch we could resolve this problem.

**Comment by dudley-ibm** [comment]
I'm in communication with my team to find out how best to approach this. It's not a quick process you're asking for. Steps would have to be taken for each pictogram after outlining, such as merging shapes to avoid a series of overlapping shapes, regrouping objects, renaming layers, etc. We would also then have two separate masters, since using strokes is the preferred approach for everyone else who uses these.

**Comment by joshblack** [comment]
Sounds good @dudley-ibm! 👍 Let me know if it'd be helpful to hop on a webex too with everyone. We could also set this up as a series of stages too, I think the big issue now is just that there is a mix of stroke and fill with the assets noted above.
