### ISSUE TITLE
Modal typings are out of date

### ISSUE THREAD

**Issue by starpit** [carbon-design-system/carbon#5831]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The Modal component has properties not supported by the typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/carbon-components-react/lib/components/Modal/Modal.d.ts

e.g. the component allows for a `size` property, but the typings do not. i think `onKeyDown` is also missing.

> Is this issue related to a specific component?
Modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Update typings.

> What version of the Carbon Design System are you using?

-  carbon-components-react@7.10.3
-  @types/carbon-components-react@7.6.15

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

https://github.com/IBM/kui

**Comment by joshblack** [comment]
Hi there @starpit! 👋 The typings for this project are community-driven so unfortunately we don't maintain them 😞 For updates I'd recommend following the process on DefinitelyTyped for resolving any issues with the types. Hope this helps!

**Comment by starpit** [comment]
thanks @joshblack 

for future reference: i submitted a PR to DefinitelyTyped, and was told that they are supporting carbon 10.7, not 10.10: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43770

so i'm at a bit of a loss as to what the story is for coding against carbon in typescript?

**Comment by joshblack** [comment]
@starpit honestly not sure, sorry I can't be more help here 😞 We're not involved with any of the types or TypeScript in general. Definitely understand how this can be frustrating, let me know if there is some kind of guidance we can offer to help make this easier on your end.
