### ISSUE TITLE
React slider component input decimal places

### ISSUE THREAD

**Issue by mattias0h** [carbon-design-system/carbon#5833]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> When slider step={} is given value with decimal places then input value is showing 15 decimal places on some values

> Issue is related to Slider component

> Value should be fixed to decimal places that come from component configuration

> Google Chrome

> "@types/carbon-components-react": "^7.7.1" but this issue seems to be in the latest version as well

## Steps to reproduce the issue

1. Go to https://codesandbox.io/s/gallant-architecture-bx09v OR https://www.carbondesignsystem.com/components/slider/code/
2. Insert step value 0.1
3. Make input field wider so you can see the full value
4. Move slider

> Please create a reduced test case in CodeSandbox
>
> - React:
>   https://codesandbox.io/s/gallant-architecture-bx09v

## Additional information

![Screenshot 2020-04-09 at 10 35 02](https://user-images.githubusercontent.com/9675673/78870246-7d830e00-7a4e-11ea-924a-a5d8095f2ca0.png)

**Comment by emyarod** [comment]
this seems like classic floating point arithmetic issues. off the top of my head I'm not sure of a solid way to avoid this on the library side without still exposing these limitations, but in the meantime it may be better to modify the application to avoid this problem

**Comment by jakubfaliszewski** [comment]
How about rounding the number to the `step` level for `input` in https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Slider/Slider.js#L557?

**Comment by emyarod** [comment]
I'm not sure how rounding would help with displaying floats here, can you explain that further?

**Comment by pdonev** [comment]
This issue still exists. I have the same problem.
