### ISSUE TITLE
How to clear DatePickerInput value for range DatePicker

### ISSUE THREAD

**Issue by AngelaChenBJ** [carbon-design-system/carbon#5837]
I'm using DatePicker widget(from 'carbon-components-react' Carbon X) with datePickerType is range, and I want to clear the input value after clicking one DatePickerInput when it has value, and leave the DatPickerInput value empty.
I see for DatePicker with range, it only needs 1 DatePicker by including 2 DatePickerInput, and DatePicker has a value attribute, I assign start time value(it has a start time parameter) for the value attribute.
When clicking DatePickerInput for start time, I have onClick event to reset start time parameter,
when clicking DatePickerInput for end time, I have onClick event to reset end time another parameter
Since I assign start time value for DatePicker widget's value, the behavior for clearing DatePickerInput value is not as expected.
Right now, when I click DatePickerInput for start time with value, it clears this input widget value BUT it clears DatePickerInput for end time value as well
When I click DatePicker for end time with value, nothing changes, the end time input widget still has value.
I wonder how can I only clear the DatePickerInput value that I want to clear? Thanks.

## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by AngelaChenBJ** [comment]
What I am trying to ask is that how I can clear one of DatePickerInputs for DatePicker with range.
Seems I am not familiar with how to save and share the writing example in sandbox, sorry for that.
The code is like this:
import React, {useState, useCallback } from 'react';
import { render } from 'react-dom';
import { DatePicker, DatePickerInput } from 'carbon-components-react';

const App = () => {
  const [startTime, setStartTime] = useState(undefined);
  const [endTime, setEndTime] = useState(undefined);

  const onDateChange = useCallback(
    () => date => {
      if (date.length === 1) {
        setStartTime(date[0].valueOf());
      } else {
        setEndTime(date[1].valueOf());
      }
    },
    [setEndTime, setStartTime],
  );

  const resetDate = useCallback(
    label => () => {
      if (label === 'start') {
        setStartTime(undefined);
      } else {
        setEndTime(undefined);
      }
    },
    [setEndTime, setStartTime],
  );

  return (
  <div>
    <DatePicker
      dateFormat="m/d/Y"
      datePickerType="range"
      onChange={onDateChange()}
    >
      <DatePickerInput
        id="date-picker-start"
        placeholder="mm/dd/yyyy"
        labelText="Start time"
        type="text"
        onClick={resetDate('start')}
      />
      <DatePickerInput
        id="date-picker-end"
        placeholder="mm/dd/yyyy"
        labelText="End time"
        type="text"
        onClick={resetDate('end')}
      />
    </DatePicker>
  </div>
);
}

render(<App />, document.getElementById('root'));

I have 2 variables, one is startTime, the other is endTime, when I select value from DatePicker calendar, I assign the selected to startTime or endTime, meanwhile, the DatePickerInput widget also displays the selected value, then I want to clear the DatePickerInput widget displayed value, for example, to clear the start time DatePickerInput widget value(at the same time, also reset my startTime variables)
<img width="363" alt="P1" src="https://user-images.githubusercontent.com/41713412/78972395-3e34ea00-7b40-11ea-909f-560e92d497fa.png">
How can I do to archive it?
I know for single DatePicker, I can set value for DatePicker, 
 <DatePicker
            key={startTime ? 'StartDP' : 'EmptyStartDP'}
            dateFormat="Y-m-d"
            datePickerType="single"
            light={false}
            locale="en"
            onChange={onDateChange('start')}
            short={false}
            value={startTime}
          >
            <DatePickerInput
              id="start-date"
              disabled={false}
              iconDescription="Icon description"
              invalid={false}
              invalidText="A valid value is required"
              labelText='Start time'
              pattern="d{1,2}/d{4}"
              placeholder="YYYY-MM-DD"
              type="text"
              onClick={resetDate('start')} // reset startTime variable
            />
</DatePicker>
But for range DatePicker, if I set value for DatePicker, as it has 2 DatePickerInput, which particular value I should assign to value attribute(I tried to assign startTime to value attribute for DatePicker, it clears 2 DatePickerInput display value when I click start time DatePickerInput widget)

**Comment by asudoh** [comment]
You can edit the [link that @emyarod shared](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) to have your use case, save it, and share the link with us. Thanks!

**Comment by AngelaChenBJ** [comment]
Actually, I want to do like this, I set start time and end time for DatePicker with range
<img width="329" alt="both" src="https://user-images.githubusercontent.com/41713412/78996155-925ac100-7b76-11ea-9892-6e3d8275c387.png">
Then I want to click start time DatePicker Input, and just clear the value of this DatePicker Input, like this:
<img width="326" alt="startempty" src="https://user-images.githubusercontent.com/41713412/78996526-55db9500-7b77-11ea-8f79-96228c63eff5.png">
Or based on both of the two have values, I want to click end time DatePicker Input, and just clear the value of this DatePicker input, like this:
<img width="331" alt="endempty" src="https://user-images.githubusercontent.com/41713412/78996596-7f94bc00-7b77-11ea-9e93-03a792d52d4f.png">
Can I do this for DatePicker with range?

**Comment by emyarod** [comment]
it sounds like you are looking to use the date picker as a controlled component. you could try passing in a value or array of values to the date picker after interacting with a button in your application

**Comment by AngelaChenBJ** [comment]
I wrote an example in sandbox, while I set value attribute for DatePicker with range only a particular value(startTime), no idea how to set an array of values to value attribute for DatePicker to control Start time and End time separately. 
https://codesandbox.io/s/weathered-worker-q20g7?file=/src/index.js
Would you please give me an example of how to pass in an array of values to DatePicker? So that it could largely help me better understand how to use it. Appreciated!

**Comment by emyarod** [comment]
https://codesandbox.io/s/reverent-elion-8kucn

I don't completely understand the initial request, but this looks like a pretty hacky situation

**Comment by AngelaChenBJ** [comment]
May I know what's expected behavior to clear value for DatePickerInput for range DatePicker?
When I use DatePicker with single, I have onClick for DatePickerInput to clear the selected value, while since it may be a little hacky situation for DatePicker with range to clear either start time or end time separately, right? 
Either clear both start time and end time together or keep the two with value together?

**Comment by emyarod** [comment]
not sure if this is what you are looking for but this may be a place to start https://codesandbox.io/s/busy-meitner-slj8i

**Comment by asudoh** [comment]
Closing - Let us know if you need further assistance. Thanks!
