### ISSUE TITLE
React tab component 'slectionMode' prop issue

### ISSUE THREAD

**Issue by sanjaykc** [carbon-design-system/carbon#5841]
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description
After taking latest carbon update getting 'selectionMode' prop warning message '**_React does not recognoze the 'selectionMode' prop on a DOM element_**.'

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
Issue with react Tab component

> What browser are you working in?
 Firefox, chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "^10.10.3",
    "carbon-components-react": "^7.10.3", 

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/3944650/78962876-285d0000-7b13-11ea-8974-7fd56c4d30ed.png)

- Notes

**Comment by joshblack** [comment]
Hi there @sanjaykc! 👋 Could you provide some steps to reproduce using the codesandbox link from the issue template?

**Comment by sanjaykc** [comment]
Hi @joshblack, sorry for the delayed response. I am not able to reproduce the issue now.
