### ISSUE TITLE
Checkbox+Label: Padding issue

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#5842]
There were appropriate gap between checkbox and its label.
Now after updating carbon, gap between them is very less compared to what we had before.

![image (6)](https://user-images.githubusercontent.com/29912424/78969074-bfca4f00-7b23-11ea-8ddf-b502d60ba5be.png)

Current versions:
“carbon-components”: “^10.10.3",
“carbon-components-angular”: “^3.48.3",
“@carbon/colors”: “^10.8.1",
“@carbon/icons-angular”: “^10.8.0",
“@carbon/layout”: “^10.8.2",
“@carbon/themes”: “^10.10.3"
“@carbon/type”: “^10.9.3"

Previous versions:
"carbon-components": "10.9.3",
"carbon-components-angular": "3.40.3"
"@carbon/colors": "10.7.2",
"@carbon/icons-angular": "10.8.0",
"@carbon/layout": "10.7.3",
"@carbon/themes": "10.9.3",
"@carbon/type": "10.8.3",

**Comment by laurenmrice** [comment]
I think this pr that was merged recently would solve this problem in our 10.11.0 release https://github.com/carbon-design-system/carbon/pull/5773

**Comment by joshblack** [comment]
@laurenmrice it seems like it's for a separate component (checkbox)

@abhisheksinghrana could you provide some steps to reproduce in a codesandbox using the link provided in the issue template?

Similarly, since this is for angular, might help to ask over in: https://github.com/ibm/carbon-components-angular

**Comment by tw15egan** [comment]
FWIW here is the latest master running locally

<img width="167" alt="Screen Shot 2020-04-10 at 10 34 53 AM" src="https://user-images.githubusercontent.com/11928039/79010516-f9488d80-7b16-11ea-9f8f-0ed6945aba97.png">

**Comment by laurenmrice** [comment]
Right ^ that is why I was confused to how that was happening, just looked similar to the multiselect issue recently.

**Comment by abhisheksinghrana** [comment]
@joshblack 
Seems like carbon angular team have to add new class "bx--checkbox-label-text" in their checkbox component.
Previously carbon is proving 26px padding-left on "bx--checkbox-label" class but now they are providing only 20px.
From v10.10.1 carbon, @tw15egan added new class "bx--checkbox-label-text" for extra 6px but carbon angular team is not aware of these class changes.
Now, I discussed with angular team and raised issue on angular repo.
