### ISSUE TITLE
Contribute articles to Carbon Medium site

### ISSUE THREAD

**Issue by thesurenk** [carbon-design-system/carbon#5845]
### Summary

How can i contribute articles to your Medium blog https://medium.com/carbondesign?

### Justification

I'm a programmer and a technical writer. While i try and use software, i enjoy writing about it. I can be drafting some articles about Carbon Design System and it's usage.

Some of my blogs:
- https://medium.com/techinpieces

**Comment by joshblack** [comment]
Hey @ksurendra! 👋 Thanks so much for reaching out! We'd love to learn more about what kinds of topics you're interested in writing about. If topics align we can definitely try and work things into our publication calendar 👀

**Comment by thesurenk** [comment]
Is there an email where can i send my topics/summary when they are ready?

**Comment by joshblack** [comment]
For sure! You can reach us at: carbon@us.ibm.com
