### ISSUE TITLE
Tooltip performance issue with click listener

### ISSUE THREAD

**Issue by chrisbygrave** [carbon-design-system/carbon#5848]
I'm using Tooltip components as part of field labels on a schema-generated form. Putting in a large schema I noticed rendering lag, which I tracked back to the Tooltip component, and in particular its use of the internal ClickListener. FYI this was with around 500 tooltips in total.

Tooltip is adding a mouse event listener in order to detect mouse clicks outside of an open tooltip in order to close the tooltip. However this ClickListener is created even when the tooltip isn't open, meaning I had 500 mouse event listeners active even without any open tooltips.

The most obvious fix here is to only render a ClickListener if the tooltip is open. A little local hacking showed this fixed the performance issue I was seeing, without any loss of functionality.

I can provide a PR tomorrow.

**Comment by emyarod** [comment]
related overflow menu issue for reference https://github.com/carbon-design-system/carbon/issues/5079 https://github.com/carbon-design-system/carbon/pull/5336

**Comment by chrisbygrave** [comment]
So, I implemented the above and it made me think I was off with my initial impression of where the time was being spent. I dug a little further, and oddly it seems to boil down to a [performance improvement](https://github.com/joshblack/carbon/commit/dcdc8eccfaca5de48e7856e17f3f562a90cedd1e) put in last year to wrap up calls to find the location on screen for floating menus inside `requestAnimationFrame`.

Here's the code running as is, rendering 1000 tooltips:
<img width="311" alt="Screenshot 2020-04-16 at 11 17 36" src="https://user-images.githubusercontent.com/3779290/79445098-fc8ac000-7fd3-11ea-9966-66143eb06de4.png">
<img width="819" alt="Screenshot 2020-04-16 at 11 18 06" src="https://user-images.githubusercontent.com/3779290/79445092-fac0fc80-7fd3-11ea-968e-2d1e10a8e4e9.png">

Replacing the `requestAnimationFrame` with a `setTimeout`:
<img width="308" alt="Screenshot 2020-04-16 at 11 24 12" src="https://user-images.githubusercontent.com/3779290/79445591-d31e6400-7fd4-11ea-94ce-210a84dc9dc6.png">
<img width="820" alt="Screenshot 2020-04-16 at 11 24 07" src="https://user-images.githubusercontent.com/3779290/79445601-d74a8180-7fd4-11ea-99ad-ce66f0139bb4.png">

Removing the `requestAnimationFrame` wrapper in `componentDidMount` in `Tooltip`:
<img width="309" alt="Screenshot 2020-04-16 at 11 19 49" src="https://user-images.githubusercontent.com/3779290/79445264-483d6980-7fd4-11ea-93ef-69f48b22f3b1.png">

I haven't included the call stack as there isn't anything Tooltip-related anywhere near the top of the list at this point.

@joshblack mentioning you here as you know best why we want the `getBoundingRect` calls to be async in the first place...

**Comment by asudoh** [comment]
Hi 👋 @chrisbygrave from your issue description seems that you are trying to make our code there from _O(n)_ to _O(1)_, is it correct? If so, would you want to share your latest code? If not, any reason not? Thanks!

**Comment by asudoh** [comment]
Hi 👋 @chrisbygrave do you have your reduced case? Also having your saved profile data will be nice. Thanks!

**Comment by chrisbygrave** [comment]
I don't believe I'm changing the O complexity of the code. I just made the very small simple change noted in the comment.

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tooltip/Tooltip.js#L217

In the first performance measurement, I ran a page that rendered 1000 Tooltips and left the code unchanged.

In the second run I replaced the block above with:
```
    setTimeout(() => {
      this.getTriggerPosition();
    }, 0);
```

And in the final performance run I replaced it with:
```
    this.getTriggerPosition();
```

Nothing more complex than that.

My point is, the `requestAnimationFrame` call was put in for a reason, and I'm asking what that reason is, and what regressions we would all see if it was removed, as the performance implications are pretty large.

**Comment by asudoh** [comment]
It was because we tried to avoid synchronous layout query upon `getBoundingClientRect()` being part of React lifecycle. Anyhow, would you want to try #5881?

**Comment by chrisbygrave** [comment]
Many thanks! I tried with the latest in master and the performance issue is resolved:

<img width="314" alt="Screenshot 2020-04-20 at 08 46 16" src="https://user-images.githubusercontent.com/3779290/79726940-7deb9680-82e3-11ea-8907-4bcc52b92925.png">
