### ISSUE TITLE
Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ComposedModal> & Readonly<ComposedModalProps> & Readonly<...>'.

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#5849]
## What package(s) are you using?

- [x ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

[at-loader] ./src/ts/reports/ShowDetailModal.tsx:71:11 
    TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ComposedModalProps>): ComposedModal', gave the following error.
    Type '{ children: any[]; open: boolean; size: string; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ComposedModal> & Readonly<ComposedModalProps> & Readonly<...>'.
      Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ComposedModal> & Readonly<ComposedModalProps> & Readonly<...>'.
  Overload 2 of 2, '(props: ComposedModalProps, context?: any): ComposedModal', gave the following error.
    Type '{ children: any[]; open: boolean; size: string; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ComposedModal> & Readonly<ComposedModalProps> & Readonly<...>'.
      Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ComposedModal> & Readonly<ComposedModalProps> & Readonly<...>'.

**Comment by emyarod** [comment]
this looks like a type error in TS, can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by zhenwan** [comment]
here is the link to Sandbox: https://codesandbox.io/s/boring-mcclintock-ie8xx?file=/src/test.tsx:215-230
![image](https://user-images.githubusercontent.com/14806866/79157182-c4983880-7d99-11ea-9862-82ec33b6fc40.png)

**Comment by emyarod** [comment]
it looks like this is a typedef issue, which should be opened against https://github.com/DefinitelyTyped/DefinitelyTyped (related https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43770 https://github.com/carbon-design-system/carbon/issues/5831)
