### ISSUE TITLE
Parameterize component markup to enable distribution of templates

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#585]
This proposal looks to add in a support model for:

-  building component markup using templates
- generating the corresponding `config` for the template
- distributing the template in a package

This work is heavily related to #579 and so am curious what @asudoh is thinking for that RFC.

The goal is to be able to allow teams to contribute templates, like dust or handlebars, and be able to read back from these templates in their own applications.

**Comment by joshblack** [comment]
cc @scottnath

Would be much better if we start with handlebars here, given the relative usage numbers and the fact that Watson Health can start contributing these now.

**Comment by scottnath** [comment]
agreed. 
https://npmcompare.com/compare/dust,ejs,handlebars,mustache,nunjucks
according to npm, handlebars is the most popular language according to downloads per month:

dust: ~2,000
handlebars ~12,000,000

**Comment by scottnath** [comment]
I broke down what the contents of a component should be here:
https://github.com/carbon-design-system/carbon/issues/8

for the generating of a config, there is this gherkin (added today)
```
  Scenario: component should generate a configuration for the template
    Given that I am incorporating a template into my build
    When I create configuration for that template
    Then I want that configuration to contain all data points required by the template
      And I want said configuration to conform to my project's needs
      And I want to request said configuration from the component's source
      And I want to include my project's content and configuration when I make said request
      And I want the component's source to return a full config with my project's config incorporated.
```
this scenario details a function that would be distributed with the component. This function would accept parameters, combine those parameters with the default component configuration, and return the combined config object for use by the build system using the component.

**Comment by alisonjoseph** [comment]
@joshblack is this work captured in the template work @asudoh did in our `v9` branch? Or is there more to it?

**Comment by joshblack** [comment]
So in theory we should also be doing the following to align with teams that use templates:

- [ ] generating the corresponding config for the template
- [ ] distribute templates in a package
