### ISSUE TITLE
When manually typing a date in a DatePickerInput, the value is not saved 

### ISSUE THREAD

**Issue by chenjher** [carbon-design-system/carbon#5855]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
When manually typing a date in a DatePickerInput, the DatePicker requires that user presses the Enter key for it to register the new date, if not presses the Enter key (move focus to other component), the value is not saved. It can reproduce in the sandbox => https://react.carbondesignsystem.com/?path=/story/datepicker--single-with-calendar

**Comment by asudoh** [comment]
Hi 👋 this is working as designed by Flatpickr. Wanted to have @laurenmrice and @carbon-design-system/design's thoughts to see if we want a change here.

**Comment by tay1orjones** [comment]
I'm also seeing this as working as intended in [storybook](https://react.carbondesignsystem.com/?path=/story/components-datepicker--single-with-calendar). It does not require a press of enter.


https://user-images.githubusercontent.com/3360588/164784378-1cfc1964-931c-432a-b273-9ac16068cbff.mov

Going to close, but let me know if I've missed something
