### ISSUE TITLE
Enhancement: Overflow content - Mid-line truncation

### ISSUE THREAD

**Issue by modean** [carbon-design-system/carbon#5856]
I have a little suggestion/feedback on using an ellipsis in the middle of a text as explained in the carbon styleguide. Per the following StackOverflow discussion this can be done using CSS only. Hence  what the styleguide states wrt/ middle-line truncation is not completely accurate cause there it reads that this can only be achieved using JS. 

https://stackoverflow.com/questions/27746218/css-crop-string-in-the-middle

Styleguide link: https://www.carbondesignsystem.com/patterns/overflow-content/#variations
Slack convo: https://ibm-analytics.slack.com/archives/C0M053VPT/p1586875004398900

![image](https://user-images.githubusercontent.com/659775/79241338-3bedcb00-7e73-11ea-9031-43d8c8e65a91.png)

**Comment by sstrubberg** [comment]
hey @modean thanks for the proposal. Is your proposal to make a mid-line truncation implementation that uses no Javascript so we can remove that line from the guidance? Also, are you interested in making a contribution? Let me know.
