### ISSUE TITLE
Expose OverflowMenu props in Storybook

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#5857]
### Summary

To properly understand how the `OverflowMenu` and `OverflowMenuItems` React components work, I rely on the props table in Storybook. Can we get the props table back into the story info section?

### Justification

Currently, there is not any documentation regarding the props of the overflow menu React components. For consumers, to successfully use components we need to easily access information regarding their props.

### Desired UX and success metrics

As a React components consumer, I can review props documentation regarding the `OverflowMenu` and `OverflowMenuItem`, so that I know what I need to do to consume these components successfully.

### "Must have" functionality

Overflow menu React props are documented in their stories' info.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release? No

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by emyarod** [comment]
maybe we should expose stories for OverflowMenu and OverflowMenuItem separately (not sure how useful they would be aside from the prop tables), or we may need to do a little digging around with storybook and multiple prop tables

**Comment by diego-codes** [comment]
Thank you @emyarod for the information. I think the low-hanging fruit is getting the props table to appear in the Storybook stories for the `OverflowMenu`. I was envisioning the same type of information you find in the `Accordion` component story.

**Comment by emyarod** [comment]
yeah taking a look further the issues I mentioned can be mostly avoided by breaking out the `OverflowMenuExample` into its individual components. there may still be issues with `forwardRef` but we should get the prop tables to show at least
