### ISSUE TITLE
Stacks icon for Cloud Pak for Apps

### ISSUE THREAD

**Issue by mdenby** [carbon-design-system/carbon#5859]
### Summary

I would like to add this icon for Stacks to the carbon icon library. We are using it in Cloud Pak for Applications in the rail navigation.

The design is done--and has been approved by the Cross-Pak team.

### Justification

I think other teams may have use for this icon. 

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

This should function the same way as the other icons.

Do you want this work within a specific time period? Is it related to an
upcoming release?

No, not related. It can be added anytime.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

This zip file containing two svgs (one at 16px and one at 32px)

[Archive.zip](https://github.com/carbon-design-system/carbon/files/4477122/Archive.zip)

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by joshblack** [comment]
cc @conradennis
