### ISSUE TITLE
The second Modal can not focus input when opening the second modal in first the Modal

### ISSUE THREAD

**Issue by zoyun** [carbon-design-system/carbon#5861]
## What package(s) are you using?

- [x] carbon-components-react@^7.3.0

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
    We should open the second Modal(Dialog Modal) in the modal, but the input of the second modal can not be focused. I trid to add selectorPrimaryFocus parameter, still faild.
   But when I trid to debug below of modal.js, the input of the second modal can be focused.
    _defineProperty(_assertThisInitialized(_this), "focusButton", function (focusContainerElement) {
      var target = _this.initialFocus(focusContainerElement);

      if (target) {
        target.focus();
      }
    });

> Is this issue related to a specific component?
   Yes, Modal.
> What did you expect to happen? What happened instead? What would you like to
    I expect can be used the input of the second modal. But the focus always on the first modal close button.
> see changed?

> What browser are you working in?
  Google Chrome is up to date
   Version 81.0.4044.92 (Official Build) (64-bit)
> What version of the Carbon Design System are you using?
   carbon-components-react@^7.3.0
> What offering/product do you work on? Any pressing ship or release dates we
   IBM Symphony  
   The release version is Lynx, the release date is May 30， 2020.
> should be aware of?

## Steps to reproduce the issue

1. Create the ModalWrapper as the first Modal.
2. Create the Modal as the second Modal with an input element.
3. Write a button or link in the first Modal for open second Modal
4. Open the second Modal and try to edit the input box.

**Comment by asudoh** [comment]
Hi 👋 we don't support nested modal and we encourage people to have UX discussions to figure out an alternate UX solution. Hope this shed some light.

**Comment by zoyun** [comment]
https://codesandbox.io/s/thirsty-franklin-6m89h?file=/index.js

**Comment by zoyun** [comment]
thx for your reply

**Comment by tw15egan** [comment]
LIke @asudoh said, nested Modals are not a supported pattern and we recommend taking a look at alternative ways to achieve this solution.
