### ISSUE TITLE
Feature request: Second layer navigation below UI shell header

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#5870]
### Summary

We propose designing a second navigation underneath the main UI shell header. 

Example:
![Do's and Don'ts Page Header](https://user-images.githubusercontent.com/63752979/79402876-0663e300-7f42-11ea-8383-663c21b8f9db.png)

### Justification

Displaying a second menu at this level was necessary because the left panel consist of pages with many complex layers. This method simplifies the navigation tremendously in comparison to nesting every single page within the left panel. 

Our usability study indicated that a muti-tiered single navigation with nested menus accompanied with icons increased cognitive overload, prevented a learnability and resulted in abandonment of the application.

The secondary navigation was designed to grant instant access to the content areas, expedite users workflows and help them meet their goals effortlessly. 

### Desired UX and success metrics

-Less time to reach page
-Easy discoverability of pages

### "Must have" functionality

---

### Specific timeline issues / requests

---

### Available extra resources

---

**Comment by designertyler** [comment]
Thanks for submitting this proposal and sharing the research that led to this design.

We recommend any new UI Shell enhancements be made by the platform or team requesting for now. The near term roadmap does not include component enhancements and we wouldn't want Carbon to be a blocker for implementing this request.

If your team pursues this new nav, please link to it from this issue so we can keep track of it in the future.

**Comment by tifftea** [comment]
@yayitsnatasha
