### ISSUE TITLE
Chart flyovers redesign

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#5875]
It is proposed that the flyover in charts is redesigned to be less visually complex.

Before: 
![intersecting colors](https://user-images.githubusercontent.com/63752979/79474649-85493200-7fbb-11ea-8c2e-28b109b998a8.png)

After:
<img width="207" alt="Screen Shot 2020-04-16 at 8 23 31 AM" src="https://user-images.githubusercontent.com/63752979/79474693-909c5d80-7fbb-11ea-8070-656e7a665709.png">

### Justification

Not enough distinction between the flyover and the chart creates an illusion of lines being connected doubles the cognitive overload. This visual complexity demands a longer time to process than the WoC design proposal.

The new flyover design is in a table format and calculates all datasets at a particular time. The chart for WoC is to be understood as a trend for users to act quickly. The use case and the relevance of this chart may not be as relevant for the WoC use cases. 

### Desired UX and success metrics

--

### "Must have" functionality

--

### Specific timeline issues / requests

--

### Available extra resources

--

**Comment by emyarod** [comment]
This issue may be more relevant over in https://github.com/carbon-design-system/carbon-charts

unfortunately it looks like I'm not able to transfer this issue over to that repository
