### ISSUE TITLE
 Data table search doesn't search links  

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#5884]
##  Data table search doesn't search links 

![image](https://media.github.ibm.com/user/211944/files/0edf2980-80ba-11ea-9378-7dd53d19646f)

The data table search doesn't search items in the Name column. We are assuming it is because they are links. 

We are looking to implement this feature in DNS.

**Comment by davidbater** [comment]
Having the same issue, with the difference that out first column - called Name as well - contains only regular strings. Filtering for any substring in different columns works fine.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by joshblack** [comment]
Gonna go ahead and close this out since we haven't heard back 👀 Feel free to comment and we can always re-open!
