### ISSUE TITLE
Support forward ref for TextInput.PasswordInput component

### ISSUE THREAD

**Issue by queeniema** [carbon-design-system/carbon#5893]
### Summary

I’m able to set focus for a normal `TextInput`  component, but not for a `TextInput.PasswordInput` component.

Test code:

```js
// this works
<TextInput
  ref={input => input && input.focus && input.focus()}
  type="text"
  labelText="Username"
  ...
/>

// this doesn't work
<TextInput.PasswordInput
  ref={input => input && input.focus && input.focus()}
  labelText="Password"
  ...
/>
```

The `ref` for `TextInput.PasswordInput` isn’t working as I see this warning:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

### Justification

A `PasswordInput` should have the same functionality as a `TextInput`.

**Comment by code-blooded-developer** [comment]
@emyarod I checked this and found the ref forwarding is not applied to PasswordInput function. Are you working on this? If not I am very much interested in working on this.

**Comment by emyarod** [comment]
@code-blooded-developer thanks, I was going to take a look near the end of the day but you can go ahead and open a PR

**Comment by queeniema** [comment]
Thanks for fixing this! Is there a release date planned for this?

**Comment by tw15egan** [comment]
@queeniema should be available in the next patch release (usually about a week between them)
