### ISSUE TITLE
File uploader button labelText changes to name of file when a new file is added

### ISSUE THREAD

**Issue by Donisius** [carbon-design-system/carbon#5894]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When a file is added using the FileUploaderButton it changes it's `labelText` to be the same as the file's name.

> Is this issue related to a specific component?
`FileUploaderButton`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I would like the `labelText` of the button to not change when a file is uploaded

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.10.3

## Steps to reproduce the issue

1. Use a file uploader button
2. Upload a file
3. See the `labelText` of the button change to the name of the file

> Please create a reduced test case in CodeSandbox
> - React:
>  https://codesandbox.io/s/elastic-hill-z6orq

**Comment by tw15egan** [comment]
FileUploaderButton will always change the text to be the file text, because it is not displayed anywhere else. Can you try using the regular `

```jsx
<FileUploader
  multiple={false}
  labelTitle="Im gonna change"
  buttonLabel= 'Add files'
  onChange={event => {
    onFileAdded(event.target.files);
  }}
/>
```

<img width="414" alt="Screen Shot 2020-04-20 at 11 12 52 AM" src="https://user-images.githubusercontent.com/11928039/79784944-e47aaf80-82f7-11ea-881f-faadb5bc8506.png">

**Comment by Donisius** [comment]
I initially did it manually using `FileUploaderButton` because I needed an event to bind to `onDelete` for the `FileUploaderItem`. I most likely missed something but I can't seem to find that event when using the regular `FileUploader`

**Comment by emyarod** [comment]
currently only the drag and drop file uploader has hooks for the delete event, related issue for the standard file uploader here https://github.com/carbon-design-system/carbon/issues/5851

**Comment by Donisius** [comment]
Cool, thanks for the reply! 😄

**Comment by emyarod** [comment]
I believe this issue can be closed given that the drag and drop file uploader has been released, the default file uploader has onDelete hooks (#5851), and the FileUploaderButton is behaving as intended
