### ISSUE TITLE
Tooltips are cut off in DataTable

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#5897]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

Issue is in DataTable Component when a cell contains a Tooltip component.  The tooltip is cut off when it hits near the edge it is cut off.

Tested in Safari.

This is for Aspera HSTS in ICP4I.

Removing overflow-x seems to fix the problem.  But not sure why that is there or what issues turning it off can cause.  We are not using locked headers

https://github.com/carbon-design-system/carbon/blame/master/packages/components/src/components/data-table/_data-table-core.scss#L22

## Steps to reproduce the issue
The tooltip will be cut off when last row is hovered over.
Test Code:
```
        <DataTable
          rows={this.props.rows}
          headers={this.headers}
          render={({ rows, headers, getHeaderProps }) => (
            <TableContainer>
              <Table>
                <TableHead>
                  <TableRow>
                    {headers.map(header => (
                      <TableHeader {...getHeaderProps({ header })}>
                        {header.header}
                      </TableHeader>
                    ))}
                    <TableHeader />
                  </TableRow>
                </TableHead>
                <TableBody>
                  {rows.map(row => (
                    <TableRow key={row.id}>
                      {row.cells.map(cell => (
                        <TableCell key={cell.id}>
                          {cell.value}
                        </TableCell>
                      ))}
                      <TableCell>
                        <TooltipIcon onClick={() => {}}  className="bx--overflow-menu" align="end" tooltipText={'Test'}>
                          <Report32 className="bx--overflow-menu__icon" />
                        </TooltipIcon>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        />
```

## Additional information
<img width="668" alt="Screen Shot 2020-04-17 at 1 52 10 PM" src="https://user-images.githubusercontent.com/8028956/79804834-d6965000-8332-11ea-806b-178f1108d243.png">
<img width="355" alt="Screen Shot 2020-04-17 at 2 05 23 PM" src="https://user-images.githubusercontent.com/8028956/79804836-d6965000-8332-11ea-8ecf-fb410a32ea24.png">

**Comment by asudoh** [comment]
Hi 👋 as you found, our non-interactive tooltip rely content outside the bounding box visible. I guess `overflow-x` is for containing many cells. That said feel free to remove it.

**Comment by dabrad26** [comment]
OK.So we should just remove it?  In the `carbon-components` Slack channel some other groups seem to say this was hacky which is concerning.  But if safe to remove I guess we will just remove it. We have found this to be an issue with a few designs provided by our team (also sorry, didn't realize my personal Github account was logged in).

Thanks

**Comment by asudoh** [comment]
Good point - Though I think removing `overflow-x` itself is safe, non-floating types of dropdowns/tooltips tend to have problems in table cells. That said, if your design come up with an alternate mean to tell the tooltip content, I think it's the best way forward.

**Comment by asudoh** [comment]
Closing - Let us know if you need further assistance. Thanks!
