### ISSUE TITLE
CDN hosting: What files do we need?

### ISSUE THREAD

**Issue by MattIPv4** [carbon-design-system/carbon#5899]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Hey folks, we're looking at hosting this package on [cdnjs](https://cdnjs.com) but aren't quite sure what files we should include?

## Relevant information

Currently, we're thinking to pull the files from `scripts/` into the root for ease of use, as these appear to be generated files with all the components in? And to then also include the `css/` and `umd/` dirs for those that need the styling or want to use individual components on the web.

Does that make sense, should we include anything else (the fonts from `src/globals/fonts/`, any of `html/`, etc.)?

**Comment by joshblack** [comment]
Hi there @MattIPv4! 👋 

Thanks so much for reaching out! For CDN files for `carbon-components`, I think you got basically all of them. For a full list I assume it'd be:

- `/css/carbon-components.css`
- `/css/carbon-components.css.map`
- `/css/carbon-components.min.css`
- `/css/carbon-components.min.css.map`
- `/scripts/carbon-components.js`
- `/scripts/carbon-components.min.js`
- `/umd` directory

Thanks again for reaching out, let us know if you have any more questions!

**Comment by MattIPv4** [comment]
Awesome, thank you! We were just concerned about some of those source only files such as the fonts. Glad to see we got the list right though :)

**Comment by joshblack** [comment]
Closing as this seems to be resolved. Thanks again for reaching out! 🎉
