### ISSUE TITLE
User feedback for Migration Overview page

### ISSUE THREAD

**Issue by baili-baili** [carbon-design-system/carbon#5900]
I want to use feedback module(above back to top icon) refer the module on carbondesign
when scroll, there will see an icon, click then have a form, there could provide feedback
is there guide to build this module?

**Comment by tw15egan** [comment]
There is no feedback module in the core library, but it may exist in the gatsby theme package.

@vpicone is this part of the gatsby theme package or is it custom-built? 

<img width="410" alt="Screen Shot 2020-04-21 at 9 30 55 AM" src="https://user-images.githubusercontent.com/11928039/79889403-d178e580-83b2-11ea-99fa-b919c23dd624.png">

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and I can re-open!
