### ISSUE TITLE
[pictograms] update dash naming structure

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5905]
We need to change the `pictogram` naming structure to follow the dash convention we use for `icons`, to help keep things consistent

Naming convention:
(-) for spaces
(--) for variants
 
-I made this update to the newest pictogram pr #5674 , so we just need to update the other pictograms in our package.

**Comment by emyarod** [comment]
this means we will also need to deprecate any renamed pictograms right?

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and I can re-open!
