### ISSUE TITLE
Data visualization content improvement

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#5911]
### Problem
The current data visualization section in the carbon website is inconsistent with the content structure of the other components and is not integrated with the rest of the site's information architecture. 

This makes the Carbon charts journey very convoluted.

An easy solution would be to cut out all Carbon charts documentation and move it to a separate gatsby site. A better solution would make the chart documentation more robust, consistent with the latest component template, and more integrated into Carbon's IA.

### As-is
The data viz section hosts:
- Basic and advanced chart and chart type examples
- Minimal usage guidelines
- No behavior documented
- No style documented
- Guidelines for chart elements (color)
- Overall chart anatomy
- Chart patterns (dashboard, legends, axes and labels)
![image](https://user-images.githubusercontent.com/19270502/79999581-b4f7ae80-8481-11ea-815f-e943a118a8cb.png)

Carbon chart tutorials are being added to the storybook
https://carbon-design-system.github.io/carbon-charts/?path=/story/tutorials--tabular-data-format

![image](https://user-images.githubusercontent.com/19270502/79999550-a7422900-8481-11ea-82ea-67d6b5d1f97e.png)

There is no single source for Carbon chart Sketch assets. 
![image](https://user-images.githubusercontent.com/19270502/79999640-c2ad3400-8481-11ea-8814-e9084f582221.png)

### Proposed to-be
- Chart documentation is consistent with other Carbon component documentation. 
- Chart related tutorials are discoverable with other Carbon tutorials.
- Chart resources are discoverable with other Carbon resources. 
- TBD

### Proposed next steps
- Audit existing Carbon chart docs and see if there is any unique needs for charts
- Create issues outlining the missing content to bring each chart's documentation up to the latest component template.
- TBD

**Comment by emyarod** [comment]
@jeanservaas are there any plans to update the data viz documentation similar to this?

**Comment by sstrubberg** [comment]
Being addressed with this issue.. https://github.com/carbon-design-system/carbon-platform/issues/1259
