### ISSUE TITLE
TextInput inline style

### ISSUE THREAD

**Issue by zoyun** [carbon-design-system/carbon#5915]
### Summary
label text and input should be inline. It looks as Select component inline style.
### Justification

Label text and input should be inline by UX design, and it's the usual style

### Desired UX and success metrics
It looks as Select component inline style.

**Comment by tw15egan** [comment]
@carbon-design-system/design do we have any plans to implement an inline text input?

**Comment by aagonzales** [comment]
@zoyun do you mean inline as in not having a visual background to the input or aligning the label and input horizontally?

**Comment by zoyun** [comment]
@aagonzales I mean aligning the label and input horizontally, thanks.

**Comment by aagonzales** [comment]
We don't have any current plans to implement this style but we're not saying its not allowed just that its not currently on our roadmap. We can add this to the back log.

**Comment by zoyun** [comment]
@aagonzales Thanks for your reply. I think I can try to contribute to this.
