### ISSUE TITLE
React tab component 'slectionMode' prop issue

### ISSUE THREAD

**Issue by sanjaykc** [carbon-design-system/carbon#5917]
After taking the latest carbon update getting 'selectionMode' prop warning message 'React does not recognize the 'selectionMode' prop on a DOM element.'
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
After taking the latest carbon update getting 'selectionMode' prop warning message 'React does not recognize the 'selectionMode' prop on a DOM element.'
code sandbox link: https://codesandbox.io/s/sweet-black-97cu5?file=/index.js
![selectionModeError](https://user-images.githubusercontent.com/3944650/80091563-f02bd780-857e-11ea-98fd-34858f43d356.PNG)

> Is this issue related to a specific component?
Issue with react Tab component

> What browser are you working in?
Firefox, chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^10.11.1",
"carbon-components-react": "^7.11.1",

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/sweet-black-97cu5?file=/index.js
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
this should be resolved in https://github.com/carbon-design-system/carbon/pull/5908
