### ISSUE TITLE
WarningAltFilled icon needs [data-icon-path="inner-path"]

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#5919]
Since the `WarningAltFilled` icon will likely be colored in `$support-03`, there needs to be a way to access the inner path (exclamation mark) to color it black.

`WarningFilled` already supports this by providing a path that is transparent by default and can be accessed with the `[data-icon-path="inner-path"]` selector.

**Comment by joshblack** [comment]
cc @conradennis

**Comment by janhassel** [comment]
Hi, @conradennis @joshblack  👋 
Just wanted to check in and ask if there are any updates. This is blocking #5918.

**Comment by conradennis** [comment]
@janhassel @joshblack hi sorry for the delay, just seeing this now! Yes this was resolved in April actually with PR #5888 which closed #4053

**Comment by janhassel** [comment]
@conradennis Ah, I haven't noticed that, sorry. In that case, I'll go ahead and close this issue. Thank you! 🙂
