### ISSUE TITLE
Simplify Icons Code

### ISSUE THREAD

**Issue by ameagol** [carbon-design-system/carbon#592]
Dudes, really ??

`<svg width='21' height='24' viewBox='0 0 21 24' fill-rule='evenodd'><path d='M9.5 1c.9 0 1.5.7 1.5 1.5S10.4 4 9.5 4C8.7 4 8 3.3 8 2.5S8.7 1 9.5 1zm0-1C8.2 0 7 1.1 7 2.5S8.2 5 9.5 5 12 3.9 12 2.5 10.9 0 9.5 0zM17 4l-3 1.7v2.4L10.3 6 5 9v3.6l-2-1.1-3 1.7v3.5l3 1.7 3-1.7v-1.1l4.5 2.4 5-3v-4.9l1.5.9 3-1.7V5.8L17 4zm-6.7 3.2l3.8 2.1-3.5 1.8-4-1.8 3.7-2.1zM5 16.1l-2 1.2-2-1.1v-2.3l2-1.2 2 1.1v2.3zm1-5.9l4 1.8v4.6l-4-2.2v-4.2zm5 6.3V12l3.5-1.8v4.2L11 16.5zm8-7.8l-2 1.2-2-1.2V6.3l2-1.2 2 1.2v2.4zM2.5 4C3.4 4 4 4.7 4 5.5S3.4 7 2.5 7 1 6.3 1 5.5 1.7 4 2.5 4zm0-1C1.1 3 0 4.1 0 5.5S1.1 8 2.5 8 5 6.9 5 5.5 3.9 3 2.5 3zm9 17c.8 0 1.5.7 1.5 1.5s-.6 1.5-1.5 1.5-1.5-.7-1.5-1.5.7-1.5 1.5-1.5zm0-1C10.1 19 9 20.1 9 21.5s1.1 2.5 2.5 2.5 2.5-1.1 2.5-2.5-1.1-2.5-2.5-2.5zm7-3c.8 0 1.5.7 1.5 1.5s-.7 1.5-1.5 1.5-1.5-.7-1.5-1.5.7-1.5 1.5-1.5zm0-1c-1.4 0-2.5 1.1-2.5 2.5s1.1 2.5 2.5 2.5 2.5-1.1 2.5-2.5-1.1-2.5-2.5-2.5z'></path></svg>`

**Icons Must be like:**

`<icon name="watson" size="large" /> `

**Comment by marijohannessen** [comment]
Hi @ameagol ! First off - we're not all dudes here 🙂  Thanks for your feedback regarding our icons - when we started writing code for Carbon, we made a conscious decision to align around SVG icons. Most of the reasons for using inline SVGs can be summed up here in this [CSS-Tricks article](https://css-tricks.com/icon-fonts-vs-svg/).

You basically have two options:

Use Inline SVG via carbon-icons: >located in dist
Use carbon-icons.svg, which is a sprite containing refs to all the SVGs.

You can read more about this in our [usage guidelines](https://github.com/carbon-design-system/carbon-icons/blob/master/docs/usage.md). Let me know if you have any questions regarding this, thanks!

**Comment by ameagol** [comment]
Hi @marijohannessen 
I was just looking for an Icon, and your answer has a paragraph with two external links. Things today has to be simplified. I'm not saying that based on my ordinary opinion, but based on the path that dev community is going too...Those frameworks exists to save development time, and make the code cleaner like the relative solutions as
Materialize, font awesome, Bootstrap CSS and you will know.

There's no reason to add a box, with a copy button, that gives us a huge line of code, or worst...Force us to spend time understanding the way to use SVG or what ever. 

Take this more like a feedback, not a concern

**Comment by joshblack** [comment]
@ameagol it's important to remember that the SVG code provided on the website is supposed to be all-purpose. Anyone can take it and use it if they wanted to without requiring any kind of build step or update to a stylesheet.

Unfortunately, there is no `icon` HTML tag so the closest that you could get is the `use` attribute for `svg` elements, or to embed the fonts in a webfont and use generated class names.

The former is actually how carbon-components used to surface its icons, but ultimately having an SVG sprite sheet to support the `use` attribute caused a ton of bloat and severely impacted initial load performance for pages that haven't downloaded the sprite sheet yet.

The latter suffers from very similar problems, namely that they can severely impact product performance.

You noted several libraries, let's take a look at how each of them does icons.

### [Bootstrap](https://getbootstrap.com/docs/4.0/extend/icons/)

Doesn't actually have any SVG icons supported in the library, and instead points you to external resources. The icons that are included in the docs are CSS-only. The libraries they link to are mostly webfonts, which the fallbacks are detailed above and in the Materialize example.

### [Materialize](http://materializecss.com/icons.html)

Materialize provides a link to a stylesheet that you can include, however this stylesheet includes a woff2 font file that is 49KB in size. This file type also isn't supported in all the browsers that Carbon targets, and so would require additional font files. This also requires you to use the `i` HTML tag and doesn't allow you to inline SVGs which, as [@marijohannessen](https://github.com/carbon-design-system/carbon-components/issues/592#issuecomment-367050950) mentioned, is a preferred practice here.

### [Font Awesome](https://fontawesome.com/get-started/web-fonts-with-css)

Follows a similar strategy to Materialize, however their sprite sheet is over 144KB in size which further compounds the first-time load performance of any product that decides to use this resource.

---

I hope this overview helps you to understand the technical challenges presented in this space, as well as the drawbacks to each approach. While I agree things could be simpler, I think something to remember is that the work here is intended to be used by anyone viewing the site, and they can use it in any tool or library, regardless of if we support it or not.

We also have to seriously take into consideration the performance impact of these icons, as Carbon services teams in every single business unit of IBM. If we surfaced the icons for all the BUs, we'd have even larger files than what was reported above.

For teams that use library/framework variants of Carbon, we actually have a very similar API to what you had proposed. You can view the corresponding Icon React component story [here](http://react.carbondesignsystem.com/?selectedKind=Icon&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

Hope this helps!

**Comment by ameagol** [comment]
HI @joshblack thanks to spare that time explaining.
