### ISSUE TITLE
[ComposedModal] Cannot read property 'querySelector' of null inside Jest

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#5923]
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If I render an open ComposedModal inside a Jest testcase, I get an error and the testcase fails.  This appears to be because the component relies on the focusButton ref to be set (which isn't guaranteed in JSDom).   I think it can be fixed with a null check before trying to focus the button

> Is this issue related to a specific component?

Composed Modal 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Forces me to mock the ref in test renderer to get the component to render
https://reactjs.org/docs/test-renderer.html#ideas

> What browser are you working in?

Jest/JSDom

> What version of the Carbon Design System are you using?
 
"carbon-components": "10.9.1",
    "carbon-components-react": "7.9.1",

## Additional information

![image](https://user-images.githubusercontent.com/6663002/80135689-2a3caf80-8566-11ea-83eb-94ace4b5b2ac.png)

**Comment by asudoh** [comment]
Ref: Issue# 7740 at facebook/react repo
