### ISSUE TITLE
Add 'light' prop to Toggle

### ISSUE THREAD

**Issue by clarebyrne** [carbon-design-system/carbon#5932]
## Detailed description

> Describe in detail the issue you're having.
Need to add light={true} prop to a toggle component.
eg. see TextArea component, has 'light' prop

> Is this issue related to a specific component?
-Toggle
-ToggleSmall

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Need to add prop for component to display correctly on a light background

## Additional information
Screenshot showing that toggles on light background do not display correctly
- Screenshots or code
<img width="625" alt="toggleimage" src="https://user-images.githubusercontent.com/59689747/80222145-4c096580-863e-11ea-84f9-075bbdc0ee96.png">

- Notes

**Comment by emyarod** [comment]
cc @carbon-design-system/design do we have a spec for themed toggles?

**Comment by tw15egan** [comment]
It seems like if we add a light variation we could simply swap `disabled-01` / `disabled-02` on the `::before` / `::after`. The normal appearance does not seem to have any issues, just when the toggle is disabled. 

<img width="716" alt="Screen Shot 2020-04-24 at 10 08 26 AM" src="https://user-images.githubusercontent.com/11928039/80238608-93c6c780-8613-11ea-80d4-81aee911c470.png">

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see their input.

**Comment by aagonzales** [comment]
We're looking into it. We might be adjusting the tokens vs adding a light prop. We'll report back.

**Comment by aagonzales** [comment]
Has been fixed in this PR: https://github.com/carbon-design-system/carbon/pull/8514
