### ISSUE TITLE
Object selection + shopping cart experience

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#5936]
### Summary

The DB2 team has designed an object selection + shopping cart experience.

### Justification

**Object selection widget**
Databases store many schemas while schemas store a multitude of tables. This widget allow users to search, browse, view and select objects within objects.

**Object shopping cart**
While databases can have hundreds of schemas and schemas can have thousands of tables, we created a fixed panel that acts as a shopping cart. This  shopping cart provides a broader view and allows users to manage the objects.

**Footer container for action buttons**
Our multi-step creation process has a fixed footer with the action buttons in a container. Some steps within the flow are more complex than others, involving multiple widgets that take up a good amount of real estate. Keeping the action buttons in a footer/container prevents the content from intersecting with the buttons.

**Screens:**

![3_1  Add tables](https://user-images.githubusercontent.com/63752979/80246835-edce8980-8621-11ea-9e97-33b84564097c.png)

![3_2  Add tables](https://user-images.githubusercontent.com/63752979/80246838-f0c97a00-8621-11ea-8714-b79e76de6c0a.png)

![3_3  Add tables](https://user-images.githubusercontent.com/63752979/80246847-f3c46a80-8621-11ea-82e9-1683cde21969.png)

![3_4  Add tables](https://user-images.githubusercontent.com/63752979/80246858-f757f180-8621-11ea-8bc7-2508e3e17c5a.png)

**Comment by tifftea** [comment]
@yayitsnatasha

**Comment by aledavila** [comment]
Thanks for the proposal! We will not be pursuing this as this seems like an uncommon pattern. 

We think this is more suitable in a PAL or sub-system library. We'll close this issue for its addition to the core Carbon library.
