### ISSUE TITLE
ComboBox - Items not visible and throws error on search

### ISSUE THREAD

**Issue by rejochandran** [carbon-design-system/carbon#5943]
## Packages

- carbon-components 10.10.2
- carbon-components-react 7.10.2

## Description
The ComboBox component does not display any items passed.
![image](https://user-images.githubusercontent.com/4696985/80374322-208fb080-88b4-11ea-891e-057f3a5e82dc.png)

and throws 
`Cannot read property 'toLowerCase' of undefined` when trying to search (guess this is because the items are not rendered)
![image](https://user-images.githubusercontent.com/4696985/80374625-8f6d0980-88b4-11ea-838c-3832fa2bab61.png)

## Steps to reproduce the issue

Code and preview [here](https://codesandbox.io/s/crazy-merkle-bgku4?file=/index.js)

Thank You!

**Comment by emyarod** [comment]
this should be resolved by adding the `itemToString` prop: `itemToString={item => (item ? item.text : '')}`
