### ISSUE TITLE
[Toggle] label is misplaced in RTL

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#5944]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

In RTL, the Toggle label sits inside the toggle instead of beside it.

![image](https://user-images.githubusercontent.com/3360588/80383915-d4b81980-8869-11ea-9c9c-5b469956a5fd.png)

> Is this issue related to a specific component?

Toggle

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The label should be displayed to the left of the toggle

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.10.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

`carbon-addons-iot-react`

## Steps to reproduce the issue

1. Load up the toggle in storybook
1. Trigger RTL mode 
    - We use the addon, so it's easy to see in our storybook https://carbon-addons-iot-react.com/?path=/story/toggle--toggled

We have an issue for this in our repo as well - https://github.com/IBM/carbon-addons-iot-react/issues/1121

**Comment by asudoh** [comment]
@tay1orjones Thank you for reporting - Just one question to help the team investigate further; Did you use a build toolchain like https://rtlcss.com/, or did you just change the UI direction (i.e. `dir="rtl"`)? We basically rely on the former: https://github.com/carbon-design-system/carbon/blob/v10.11.0/packages/components/docs/g11n.md

**Comment by tay1orjones** [comment]
Sorry for the delay in response @asudoh - the switch in our storybook just flips the direction. 

How would RTLCSS help here? There's no control directives declared in the styles

https://github.com/carbon-design-system/carbon/blob/46d64ccc0e2ef011f1fe3cf96b4c6a001ab2183e/packages/components/src/components/toggle/_toggle.scss#L30-L38

**Comment by asudoh** [comment]
@tay1orjones RTLCSS replaces `left`, etc. with `right`, etc. Though your code snippet above doesn't include those kind of CSS properties, there may be other style rules in such kind that affects toggle label.

**Comment by tay1orjones** [comment]
@asudoh Do you validate the RTLCSS output has the intended outcome with some automated testing? Do you run the css through RTLCSS as apart of your build pipeline for the storybook?

**Comment by asudoh** [comment]
AFAIK there is no automation tests for RTL in place in this repository.

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/8469, the auto-close syntax was just a bit wrong in the description so this was missed and left open.
