### ISSUE TITLE
[Pagination]: Overflows off screen on mobile size displays

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon#5953]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

Cannot use pagination on smaller/mobile screens without the component overflowing off the page

eg. https://codesandbox.io/s/carbonvue-pagenation-issue-83pn3?file=/src/App.vue

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect to be able to use the pagination on mobile without the component overflowing

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.11.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

no

## Steps to reproduce the issue

1. Use pagination on a small screen

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/inspiring-shockley-8s5p3?file=/index.html
> - React:
>   https://codesandbox.io/s/reverent-blackwell-41clh?file=/index.js
> - Vue:
>   https://codesandbox.io/s/carbonvue-pagenation-issue-83pn3?file=/src/App.vue

## Additional information

![79988649-cbfcc780-84a6-11ea-9925-77bf89bf795e](https://user-images.githubusercontent.com/9937136/80477157-60ea3f80-8943-11ea-8eb9-153f24a43c4b.png)

Issue was originally raised in `carbon-components-vue` https://github.com/carbon-design-system/carbon-components-vue/issues/872 but was suggested to raise here.

**Comment by tw15egan** [comment]
@carbon-design-system/design Do we have any mobile specs for pagination?

**Comment by joshblack** [comment]
@tw15egan in the interim should we have it follow the tab behavior that you were proposing for overflow? 👀

**Comment by tw15egan** [comment]
@joshblack that's a good stopgap, I can submit a PR
