### ISSUE TITLE
DataTable with Dynamic Content renders incorrectly

### ISSUE THREAD

**Issue by zacharydmoore** [carbon-design-system/carbon#5967]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
  My team is using the DataTable with dynamic content that includes the both TableExpandRows and TableSelectRow. We don't want or need a TableHead element, but removing it breaks the styling of the DataTable. Specifically, the column containing the checkboxes grows in width, adding unnecessary space between the checkbox and the next column.

> Is this issue related to a specific component?
Not sure if this is related to the DataTable itself, or the TableSelectRow.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the styling of the table to not change when not including a TableHead element in the DataTable. I would like to have the ability to utilize the DataTable with dynamic content and not have to have a TableHead and unused components in it.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components-react: 7.6.15
However, it also persists with the latest version

## Steps to reproduce the issue

Import the DataTable with dynamic content per the docs.
Delete the TableHead element along with its children

Here's an example in codesandbox.io
> - React:
https://codesandbox.io/s/frosty-framework-1wn6g?file=/src/index.js

- Screenshots 
Expected Behavior
![withTableHeader](https://user-images.githubusercontent.com/46874543/80550068-b4748180-8973-11ea-850c-8247b8012d6a.png)

Current Behavior
![No TableHeader](https://user-images.githubusercontent.com/46874543/80550206-395f9b00-8974-11ea-8840-2518bd0ef1b4.png)

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if we allow data tables without table header.

**Comment by laurenmrice** [comment]
Currently we don't allow taking off the column header. Just wondering, if you do have multiple columns of text what are they representing? Do you have a screenshot of the actual data that would be in there, just trying to understand the usecase.

**Comment by zacharydmoore** [comment]
@laurenmrice due to it being a company feature I can't send a screenshot, but essentially it is the dynamic content table with the expand caret, checkbox, and a single column with a sentence descriptor in each row. The images above work, just instead of 3 columns (foo, bar, baz), imagine one with 'this is a really long sentence someone could select'
