### ISSUE TITLE
Inline status of a resource or object in Data table

### ISSUE THREAD

**Issue by tvelingkar** [carbon-design-system/carbon#5974]
### Summary

Displaying the inline status of a resource or object in the Data table.
There are guidelines for showing notification icons but the same does not exist for the inline status of a resource or object.

### Justification

We have a list of requests which are displayed in the data table, we need a way to show the priority of the requests to the User. Also, we need to highlight the recent requests to the User so as to inform him/her about the newest requests.

### "Must have" functionality

* Highlighting most recent rows in the data table.
* Status dot in the table cell to show the priority of the resource or object.

### Available extra resources

![DataTable Status UI](https://user-images.githubusercontent.com/7437815/80591107-b9e8cf00-8a3a-11ea-8111-d5fdb7e13b46.png)

**Comment by tvelingkar** [comment]
Hey @chrisconnors-ibm 
Can you look into this request, please

**Comment by designertyler** [comment]
Thank you for the submission! We've added this to our backlog to further explore the design specs around this request.

To do:
- Check we are meeting color contrast requirements for the background color of the rows and the status dots.
- Hover colors for the 4 themes
- Selected state colors for the 4 themes
- Appearance when the table is using zebra stripes
- Sorting behavior when there are priority rows

**Comment by sstrubberg** [comment]
We have a Resource Status Indicator in [Cloud PAL]([pages.github.ibm.com/ibmcloud/pal/storybook/?path=/story/components-resourcestatusindicator--demo](https://pages.github.ibm.com/ibmcloud/pal/storybook/?path=/story/components-resourcestatusindicator--demo)).

We also have the [Status Indicators pattern](https://carbondesignsystem.com/patterns/status-indicator-pattern/).

**Comment by skcele** [comment]
There is also a [Status Icon component]( https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-status-icons-statusicon--default) in Carbon for IBM Products.
