### ISSUE TITLE
[Text input] Transient gray border shown when transitioning from disabled to enabled

### ISSUE THREAD

**Issue by yinglejia** [carbon-design-system/carbon#5979]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

This can be reproduced using the React playground: https://react.carbondesignsystem.com/?path=/story/textinput--default. The bug can be seen in both Chrome and FireFox.

![image](https://user-images.githubusercontent.com/34791554/80635048-5efaac00-8a29-11ea-9738-534df742448f.png)

Simply change the text input from disabled to enabled. To make it easier to see the transition, set the animation duration to a large value:

![image](https://user-images.githubusercontent.com/34791554/80635336-be58bc00-8a29-11ea-9999-0aef0bf8796d.png)

The text input component has a CSS transition for outline property: https://github.com/carbon-design-system/carbon/blob/f107c20fa1f661f6b1dd435c2ca289a8ae687978/packages/components/src/components/text-input/_text-input.scss#L35

For enabled state, the outline is `2px solid transparent`; for disabled state, the outline is `none`. It seems the transient gray border is shown when transitioning from `none` to `2px solid transparent`. We probably can fix it by using `2px solid transparent` for the disabled state too.

**Comment by asudoh** [comment]
CC @tw15egan @carbon-design-system/design

**Comment by laurenmrice** [comment]
I am not seeing that when I look in firefox or chrome. However If I toggle`disabled` on and off I do see a quick flash of that border line. 

-------------------------------------------------------------------------------------------------

#### Just to clarify:
The enabled state should only have the 1px underline using `ui-04`.
![enabled](https://user-images.githubusercontent.com/43969356/80713297-d3c8f700-8ab8-11ea-90b8-bf71afe9fbb2.png)


The disabled state should not have the underline.
![disabled](https://user-images.githubusercontent.com/43969356/80713309-da576e80-8ab8-11ea-96c3-aff501dd9d21.png)
