### ISSUE TITLE
[Accordion] increase height of header

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5983]
The header of accordion should be 40px tall not 32px. 

![image](https://user-images.githubusercontent.com/11670886/80651162-fddbd400-8a3a-11ea-99db-6a194f77b67f.png)

**Comment by tw15egan** [comment]
Will need to update website table as well (spec image seems correct)

<img width="1163" alt="Screen Shot 2020-04-30 at 12 31 32 PM" src="https://user-images.githubusercontent.com/11928039/80751414-98412380-8ade-11ea-8f39-aefa25c58d54.png">
