### ISSUE TITLE
MultiSelect menu height override to unset breaks drop down

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#5986]
We had this issue where the drop down for the multiselect would always be open and would not close. I found out the css we had was overriding the max-height inside .bx--list-box__menu from 0 to unset. This causes a break in the drop down.

I went on this sand box and went into the dev tools and changed the max-height from 0 to unset, from the .bx--list-box__menu and it broke the drop down menu for the multiselect 

https://codesandbox.io/s/damp-wildflower-9c58z?file=/src/index.js

I am not sure if this is even a bug or just a rule, but thought I should mention it and ask. I dont know why this was originally set to unset, I think to make the dropdown long as the content inside.

**Comment by emyarod** [comment]
the menu appears closed when the `max-height` is 0, so unsetting that value would cause the menu to be visible

**Comment by TannerS** [comment]
> the menu appears closed when the `max-height` is 0, so unsetting that value would cause the menu to be visible

Make sense, then not a bug I assume

**Comment by emyarod** [comment]
it seems to be intentional, but what kind of behavior were you expecting for the menu?

**Comment by TannerS** [comment]
For the menu to be large enough to not have scroll bar for the selections.
I originally didnt add that part of the css overriding it but it was there
before and then it just stopped working. Not sure why. Either way it
doesn't look like a bug so this can be closed :)
