### ISSUE TITLE
Progress icon request

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#5989]
The DB2 has requested to have a progress icon. This is the design they are proposing:

![progress notification](https://user-images.githubusercontent.com/63752979/80737421-51e0ca00-8ac8-11ea-9f7f-1abe3b80b9dc.png)
_(the blue 'i' icon)_

@yayitsnatasha

**Comment by tw15egan** [comment]
This icon is already available in the library under "Information filled"

https://www.carbondesignsystem.com/guidelines/icons/library

Hope this helps
