### ISSUE TITLE
Empty states and graphics

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon#5991]
Hi, are you planning to release empty states and graphics? If yes, please provide the timeline.

**Comment by robherley** [comment]
Here's a doc on the empty state patterns, not sure if this is what you're looking for: https://www.carbondesignsystem.com/patterns/empty-states-pattern/

**Comment by lordsfantasy** [comment]
Hello @robherley I am actually looking for the graphics similar to the ones provided in the https://www.carbondesignsystem.com/patterns/login-pattern 
https://ibm-security.carbondesignsystem.com/?path=/story/patterns-nonentitledsection--default

The isometric illustrations I mean. 

Illustrations for using it on login page and within the application when there is an empty state.

**Comment by laurenmrice** [comment]
We are providing general guidance on how to structure empty states for different use cases but we are leaving the graphic creation up to teams to create.

There are some great illustration guidelines that have been added recently by the brand team: https://www.ibm.com/design/language/illustration/overview/

Soon they will be coming out with a file that contains general building block illustrations, it just has not been released yet.

**Comment by tw15egan** [comment]
Marking this as resolved, feel free to reopen if there is something else we can help with 👍
