### ISSUE TITLE
[Dropdown] initialSelectedItem doesn't seem to work

### ISSUE THREAD

**Issue by rscoates** [carbon-design-system/carbon#5994]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When rendering a dropdown menu within a form (within a modal), I can't get the initial selected item prop to work. when I specify it as the selectedItem, it selects it fine, though obviously then the dropdown is not usable.
While replicating the code in a Sandbox is tricky, as it involves a complex Redux state, this is the relevant bit, with screenshots.
```
const initialItem = props.initiallySelectedItem && dropdownItems.findIndex((e) => e.id === props.initiallySelectedItem)
  return (
    <Dropdown
      items={dropdownItems}
      initialSelectedItem={isNumber(initialItem) && dropdownItems[initialItem]}
      label={props.attribute.name}
      titleText={props.attribute.name}
      ariaLabel={props.attribute.name}
      id={props.attributeTypeId}
    />
  )
```
![Screenshot 2020-04-30 at 22 02 10](https://user-images.githubusercontent.com/9936693/80758886-488a4880-8b2e-11ea-91ae-93dc3d4ec850.png)
![Screenshot 2020-04-30 at 22 01 38](https://user-images.githubusercontent.com/9936693/80758888-49bb7580-8b2e-11ea-9403-da50d3157599.png)

> Is this issue related to a specific component?

Yes, the Dropdown menu, possibly within a modal, and possibly because there are several different instances of the same component being rendered (though with different ids)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see 'Tel Aviv' selected in the dropdown, as it is when the same value is passed to the 'selectedItem' prop.

> What browser are you working in?

Brave Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

10.11.2. Same problem also in 10.11.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Shipping software to client on 22 May 2020. Internal test deadline of 11 May 2020

## Reproduce the issue

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/pensive-water-1xtgo
(Though it works correctly in here)

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
since the reduced test case works as expected, would you be able to replicate the issue with a simplified redux state in code sandbox?
