### ISSUE TITLE
[OverflowMenu]: Custom trigger doesn't block shadow completely

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#5998]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the OverflowMenu with a custom trigger that is wider than an icon, the box-shadow of the menu overlays into the trigger.

> Is this issue related to a specific component?

OverflowMenu

> What browser are you working in?

Chrome 80

> What version of the Carbon Design System are you using?

`carbon-components@10.11.2`
`carbon-components-react@7.11.3`

## Steps to reproduce the issue

1. Visit react storybook for custom trigger overflow menu: https://react.carbondesignsystem.com/?path=/story/overflowmenu--custom-trigger
2. Open menu, use arrow keys to change focused element to second item

## Additional information

![image](https://user-images.githubusercontent.com/28265588/80793858-8fad2380-8b98-11ea-9da5-c1f425db4091.png)

**Comment by oyin-k** [comment]
Hello @joshblack I want to start contributing to the team by working to fix this issue.

**Comment by sstrubberg** [comment]
@janhassel This still an issue?

**Comment by janhassel** [comment]
@sstrubberg Yes, this is still happening

**Comment by tw15egan** [comment]
The `::after` elements are sized based on the button `size` options. We'd need to change this to either a CSS variable that can be dynamically updated or use some filter effect to obscure the menu box shadow so it does not show a shadow on the button. Open to suggestions

Relevant code: https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/overflow-menu/_overflow-menu.scss#L135

**Comment by preetibansalui** [comment]
The link shared in the issue is not a valid link anymore, Also tried if we have any component named ' custom trigger overflow menu' but couldn't found any. Looks like its a very old component which is not available now So I am closing the Issue. Please feel free to raise a new issue with updated link if you still face it.
