### ISSUE TITLE
When viewing full render of Interior Left Nav label - link is inside table

### ISSUE THREAD

**Issue by andylyell** [carbon-design-system/carbon#6]
![image](https://cloud.githubusercontent.com/assets/15803315/24542830/10504764-15f5-11e7-8f03-38648a61377d.png)

Hey I don't know if this is a quick fix or not but the ```interor-left-nav.html``` link reside within the table which could be a mistake?

😄 love the project!

**Comment by marijohannessen** [comment]
Hey! Thanks for catching this, I will put in a fix for it asap. 😄

**Comment by marijohannessen** [comment]
The PR to fix this was just merged into master, so it will be updated on the website by the end of the day.

**Comment by marijohannessen** [comment]
The fix is now live.
