### ISSUE TITLE
Search component incorrect right offset of close icon with "lg" mod

### ISSUE THREAD

**Issue by imposibrus** [carbon-design-system/carbon#600]
https://github.com/carbon-design-system/carbon-components/blob/8c124924d5549850703fda87dde079b91964dd61/src/components/search/_search.scss#L88
`rem(100px)` looks good with icons:

![image](https://user-images.githubusercontent.com/3369328/36481321-8f93bf92-1720-11e8-85e1-253e7895f4da.png)

but without:

![image](https://user-images.githubusercontent.com/3369328/36481195-250a51b8-1720-11e8-8dd5-da2c6bee5dca.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design should the large search be used without icons? As you can see above, not supported in code. Would you recommend they use small search, or is large search without icons a supported pattern?

**Comment by bsonefeld** [comment]
Large search without icons should be a supported pattern.
