### ISSUE TITLE
[aspect-ratio] Latest aspect ratio broke aspect-ratio classes

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#6003]
https://github.com/carbon-design-system/carbon/pull/5255/files

The `bx--aspect-ratio-1x1` class no longer does anything.

reproduction:

Go here:
https://carbon-website-hxvmb5n2c.now.sh/data-visualization/chart-types

Add the css rule:
```
.bx--aspect-ratio--1x1 {
    padding-bottom: 100%;
}
```

This is the rule that was being applied before we updated Carbon.

**Comment by jeanservaas** [comment]
Affects major functionality of my heart... because my heart broke with this component.

**Comment by joshblack** [comment]
Talking about this on Slack, it seems like the website might not be using the `bx--aspect-ratio` class on these pages. It seems like it is using it on places like the front page

![image](https://user-images.githubusercontent.com/3901764/80840734-884f3f80-8bc3-11ea-981f-bb71bd687da7.png)

I believe adding it in will help fix the data viz pages!

![image](https://user-images.githubusercontent.com/3901764/80840764-9bfaa600-8bc3-11ea-905d-8f37bec807de.png)

**Comment by vpicone** [comment]
Looks like this component was built using the carbon-elements documentation which just recently added the `bx--aspect-ratio` class to the examples.

The sudden dependency on this class being required for any of the styles to work caught us off guard. Hopefully we were the only ones using the carbon elements grid documentation for aspect ratio!

Gonna close this for now since I'm not sure there's anything to be done about it.

**Comment by joshblack** [comment]
@vpicone to clarify, this was always the intended usage of these classes going back to the first implementation of this package. It is not a new requirement or sudden dependency.

**Comment by vpicone** [comment]
@joshblack I’m still not sure why the aspect ratio worked until recently, but definitely agree the base class should have been there from the start.
