### ISSUE TITLE
Numeric Input Placeholder

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon#6005]
### Summary
Similar to text or other inputs, my product requires a null value on Numeric input, and it would e nice to also display a placeholder. 
<img width="200" alt="Screen Shot 2020-05-04 at 9 35 34 AM" src="https://user-images.githubusercontent.com/21066152/80971372-aba80380-8dea-11ea-8bcb-26f8706d1b0b.png">

Clarify if you are asking for design, development, or both design and
development.
**Development**

### Justification

In my product, numeric fields are frequently optional, and therefore, forms load with a null value (note that zero is not a null value). We were able to pass a null value with the React component, but were unable to insert a placeholder. An empty box with no placeholder is inconsistent with other inputs.

### Desired UX and success metrics

• On-load, the input will appear similarly to a text input, with light grey text and a custom placeholder, in this case, two dashes. 
• User can either focus on the field (which will clear the placeholder and bring up the cursor) and use the keyboard to enter a value, or use the step buttons, which will also clear the placeholder on initial tap.
• User can select any text and hit delete to remove the value. De-focusing will bring the placeholder back

### Specific timeline issues / requests

October, 2020

### Available extra resources

My team attempted to do this change, but was unable to work around the Carbon base component. Seems that it needs to be done at a higher level.

**Comment by emyarod** [comment]
do you mean something like this? https://codesandbox.io/s/beautiful-galois-r2jk8

**Comment by JordanWSmith15** [comment]
@emyarod yes, that is very close. One of the dashes persists when I step-down.

**Comment by emyarod** [comment]
just to confirm, are you referring to the minus sign? stepping down from the empty value gives -1

**Comment by JordanWSmith15** [comment]
@emyarod ahh, yes, my mistake. This is correct!

**Comment by JordanWSmith15** [comment]
@emyarod any update on this?

**Comment by emyarod** [comment]
@JordanWSmith15 does [the example I gave previously](https://github.com/carbon-design-system/carbon/issues/6005#issuecomment-623517503) meet your use case? if not, what is still missing from it?

**Comment by JordanWSmith15** [comment]
@emyarod  No, this works, but is this a change we should make on our end, or something that my dev team should wait for in a future release of Carbon React?

**Comment by emyarod** [comment]
@JordanWSmith15 this is something you can do on your end right now using `placeholder` and `allowEmpty` just like the example

**Comment by tw15egan** [comment]
Going to close this as this issue seems to be resolved on the user end
