### ISSUE TITLE
Adding content into headers

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#6010]
### Summary

The HDM Yosemite team has proposed the idea of allowing content to be included within the local page headers. The reasoning behind this is that there's a lot of unnecessary white space consuming the screen that can be utilized for other functions/content.

![box-image](https://user-images.githubusercontent.com/63752979/81000617-650ed500-8dfb-11ea-9b7c-b4d68415e573.png)

For instance, adding open alerts to the header creates more space on the page to account for the graphic panel (consisting of an interactive 3D model) and the information panel (the overall system health and table of components). This change is necessary in order for users to be able to view and use the graphic and information panels with ease. 

![box-image-2](https://user-images.githubusercontent.com/63752979/81000631-6b04b600-8dfb-11ea-9399-1446da694fe7.png)

@Grace-Harkin1

**Comment by asudoh** [comment]
Wondering if this is something we'd allow - CC @carbon-design-system/design

**Comment by laurenmrice** [comment]
This is something teams can customize for their own usecases and is not something that we specifically would support.

IBM Cloud has aligned on different types of page headers that would work for their different usecases. They have created detailed guidelines around them which may be useful to look at: https://pages.github.ibm.com/ibmcloud/pal/components/page-header/usage

**Comment by tw15egan** [comment]
Closing this since it is not something we plan to support
