### ISSUE TITLE
Hardware overview - rack visualization experience

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#6011]
### Summary

The HDM Yosemite team has designed a graphical view to monitor hardware racks. Is this Carbon compliant?
 

This view allows users to quickly identify which hardware components are experiencing issues and need attention
Out of all possible system health statuses, unhealthy status types 'failed', 'warning', and 'unreachable' are shown in this view to improve scan-ability.
based on testing feedback, displaying information this way helped guide the user's attention
User feedback indicated that participants found it helpful to visually see their components if they were remotely located from the hardware they're monitoring,
Users can export the page/screenshot to communicate with service technicians for easy identification when onsite, and can also be shared with team members and management for reporting purposes.
On hover, the unhealthy components' text will highlight blue to indicate to the user that they can click. On click, a modal will pop up with more information on the component and an option to open the details page. 

![box-image-3](https://user-images.githubusercontent.com/63752979/81003738-334c3d00-8e00-11ea-8144-b7b1b8d43756.png)

User hovers over enclosure
![box-image-4](https://user-images.githubusercontent.com/63752979/81003754-36dfc400-8e00-11ea-9007-578cdbf6abf6.png)

User hovers over component with label 'Warning'
![box-image-5](https://user-images.githubusercontent.com/63752979/81003764-3a734b00-8e00-11ea-949b-5e2810810042.png)

User clicks on component with label 'Warning'
![box-image-6](https://user-images.githubusercontent.com/63752979/81003770-3cd5a500-8e00-11ea-9bf1-7175f9d2a1b0.png)

@Grace-Harkin1

**Comment by sstrubberg** [comment]
@tifftea let me know if any of these issues i'm closing are still valid. Happy to re-open and have a conversation :)
