### ISSUE TITLE
Switcher Dropdown

### ISSUE THREAD

**Issue by ksurya** [carbon-design-system/carbon#6016]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

The Carbon Components React website has component for 100% height right side panel.

Would the following be possible?

<img width="447" alt="image" src="https://user-images.githubusercontent.com/932927/81083811-090f8380-8ec3-11ea-9505-a292dabd5280.png">

**Comment by asudoh** [comment]
CC @carbon-design-system/design

**Comment by tw15egan** [comment]
>The right panel is invoked by icons on the right side of the header and remains anchored to that icon. Right panels have a consistent width, **span the full height of the viewport**, and are flush to the right edge of the viewport.

https://www.carbondesignsystem.com/components/UI-shell-right-panel/usage#anatomy

Going to close this as resolved 👍
