### ISSUE TITLE
Create code documentation for the Button component

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#6018]
We want to write out the documentation for the Button component over on the website. This documentation should live under the "Code" tab and should cover the following topics:

- Page description
  - "How to build a Button using React."
- Table of contents
  - Component usage
  - Component API
  - Reference
- Component usage
  - Introduction to this component
  - Cover the most common use-case for this component
  - Cover alternative common use-cases for this component
  - Cover ways this component may be used with other components (like a skeleton)
- Component API
  - Button prop types
  - Button skeleton prop types
- Reference
  - Cover any questions that may have been prompted by the work above

**Comment by joshblack** [comment]
Gonna close this out ahead of our sprint :eyes: Let me know if you want to sync up TJ!
