### ISSUE TITLE
Tabs component should use react to render the component

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#6019]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We have some components that rely on `element.clientHeight` and `element.scrollHeight` on mount and on update, however in the tabs component, all elements are rendered on start but the tabs that are not selected are hidden, resulting in both values being 0. 

> Is this issue related to a specific component?

Yes, Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Currently the Tabs component uses css to hide/show the child components that is passed to it. Instead they should be dynamically rendered based on tab selection. 

> What browser are you working in?

firefox

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Console Docs

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/busy-carson-wrue1

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Would you try hooking [`resizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to the `<TestTab>`? There is a [React hook-based wrapper](https://www.npmjs.com/package/use-resize-observer) for that, too. You can see code in #5854 for more details.

**Comment by gptt916** [comment]
Thanks for the info, I'll give it a try and report back.

**Comment by gptt916** [comment]
That worked very well for my use case, thank you, closing.
