### ISSUE TITLE
How to use grid package for development with yarn?

### ISSUE THREAD

**Issue by ericol** [carbon-design-system/carbon#6020]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [x] `carbon-components-svelte`
- [x] `@carbon/grid`
## Summary

I'm trying to use the grid package with `Yarn` to no avail.
## Relevant information

Hi, I'm trying to use the `@carbon/grid` package, but can't make it work.

Instructions say "Use the following command `yarn add @carbon/grid`" but from there on, there's no way (Or, I haven't been able to find it) to use it.

With `npm` for `.scss` the instructions around the web are to link the files under the `nodes_module` folder, but that's not possible (Or, at least, incredible cumbersome) to do in `yarn`.

Even thought the instructions are more complete in the `themes` package, I tried that and doesn't work either.

Adding the following:
```
<style type="text/scss">
	@import "@carbon/grid";
</style>
```
To my app component returns the following error:
`[!] (plugin svelte) Error: File to import not found or unreadable: @carbon/grid/.`

(The same happens if I use `@carbon/grid/scss` or `@carbon/grid/scss/index.scss`

**Comment by joshblack** [comment]
Hey there @ericol! 👋 I'm not too familiar with Svelte but I would imagine that there is likely a way to pass in options to the sass compiler. In particular, the `includePaths` option needs to include `node_modules`.

Once that's set up, you should be able to do:

```html
<style type="text/scss">
	@import "@carbon/grid/scss/grid";
</style>
```

**Comment by joshblack** [comment]
Going to close this out, let me know if you have any further questions!
