### ISSUE TITLE
keyboard focus lost on ComboBox after clearing current selection

### ISSUE THREAD

**Issue by jowen** [carbon-design-system/carbon#6030]
The keyboard focus is lost on ComboBox after clearing current selection.

Reproducible using react story book here:
https://react.carbondesignsystem.com/?path=/story/combobox--default

Steps to reproduce:

1) Select an item in the combo box using keyboard

![image](https://user-images.githubusercontent.com/802501/81213806-ec4b7c80-8fa4-11ea-8804-71a04bed483a.png)

2) Tab to the "x" button and activate it with the return key

![image](https://user-images.githubusercontent.com/802501/81213777-e2c21480-8fa4-11ea-866f-b19708bc694a.png)

3) Note that keyboard focus is no longer in the CombBox and it is now no longer possible to select a new value using the keyboard.

**Comment by emyarod** [comment]
is this a regression? it seems to match the example downshift behavior as it did before IIRC. for selecting a new value with the keyboard, I am still able to do so after clearing the input (<kbd>Shift</kbd>+<kbd>Tab</kbd> to move focus back to the input since the clear selection button is after the input field in the DOM)

**Comment by jowen** [comment]
@emyarod it's not clear where the focus goes after clicking the "x" as there is no longer a visible focus indicator anywhere on screen.  This can be seen more clearly if you place the ComboBox in a form.  

Focus should return to the CombBox input field just as it does after selecting an item.

**Comment by emyarod** [comment]
I am just confirming that this is not a regression since this seems to be the default downshift combobox behavior from what I see in their documentation example. that being said this additional focus behavior can be implemented

**Comment by jowen** [comment]
@emyarod thanks, i verified it was not working correctly in Carbon 9, so not a regression.
