### ISSUE TITLE
File browsing pattern

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#6032]
(From the HDM Data Virtualization team) 

Users need the ability to select from tables and files to virtualize. Files need to be found in a way that the user can search through folders. Users can either directly input the file path or browse for files folder by folder. Sometimes a file can be deep within a the structure, so we added navigational breadcrumbs (only within the file browsing basis) so the user can easily see the file path that was created. 

Screen:
![box-image-11](https://user-images.githubusercontent.com/63752979/81247952-1fefcc00-8fd0-11ea-8d58-9950dc18b454.png)

@fangshih you may want to provide an example of an interaction flow

**Comment by emyarod** [comment]
the left pane may be covered by the upcoming tree view component (https://github.com/carbon-design-system/carbon/issues/5180)

**Comment by fangshih** [comment]
I tried out the tree view component, I still have few questions about the design 
- Does tree view component provide a way for user to search and able to locate the folder directly? 
- In DV, sometimes a file can be deep within a structure, and with all the folders layering down, it's hard to see the full structure just by the tree view itself. should we still consider including the navigational breadcrumb? cause user could easily get lost in the long list of structure tree views. 
![Virtualize 5 - data tree](https://user-images.githubusercontent.com/4862573/81616024-5c447300-93a8-11ea-90f0-4f99542fee98.png)

**Comment by emyarod** [comment]
the tree view is still in progress but you can see some of the planned feature set here https://github.com/carbon-design-system/carbon/issues/5180 cc @designertyler

**Comment by aagonzales** [comment]
This pattern will need more documentation before Carbon can review it for submission to the Carbon core package. @tifftea please follow the pattern template found here https://www.carbondesignsystem.com/how-to-contribute/pattern. When fully documented please re-open and we will review again. Thanks!
