### ISSUE TITLE
'Noodle' connecter function

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#6033]
The HDM Data Virtualization team has proposed to have a function where two components can be connected by dragging and dropped one end of a line (the noodle) to another component and connect them. 

With this design, users can perform SQL joins without the need for coding. 

This design makes it possible to define table views across databases of different types and even geographically distributed. 

![box-image-12](https://user-images.githubusercontent.com/63752979/81249284-1d42a600-8fd3-11ea-8cac-5b6f8c4cf9da.png)

**Comment by connor-leech** [comment]
Hey @tifftea!

Thanks for the proposal. Before we can consider your proposal we'll need a some more detail. Do you have a design spec or working code? 

Is this something your team is already using, and if so, can you provide product flows and functioning examples?

**Comment by tifftea** [comment]
@fangshih

Can you provide what has been requested? Thanks!

**Comment by fangshih** [comment]
Hey @connor-leech, We do have this design exist in the product already. You can see how it works in the real build here: 
https://zen-cpd-zen.apps.ocp311new6-master-1.fyre.ibm.com/zen/#/dataVirtualization/console|myData
Admin / password 

Here is the design spec for join object: https://ibm.invisionapp.com/share/42NZHPKVXZ3#/screens/319361640

You can go to " My virtualized data" page and select two tables, and hit "Join". Right now we can only join two virtual objects. 
![VD landing page Copy 4](https://user-images.githubusercontent.com/4862573/82246642-aed2e180-990a-11ea-9cfe-b633c989928b.png)

Once you click the join button, it will bring you to the join virtual object view that you selected. 
Join virtual object means SQL join object, it takes multiple tables and join them on the join key, and merge the connection between those two and into one table. 
![join 1](https://user-images.githubusercontent.com/4862573/82246730-d75adb80-990a-11ea-88a6-447c0584addc.png)

You can click the row and drag into another row and join them. Once two keys are joined, you can also see it on the right side panel. you can preview the join keys by click the Preview button. and if you all set, you can click Next 
![Join flow 2](https://user-images.githubusercontent.com/4862573/82246831-05402000-990b-11ea-9b26-70b9e6a42fa1.png)

User will get one table from the two tables you join earlier, now they are one big table. And once you click Next, it will allow you to rename it and able to add it to the My virtualized data list. 

![Join flow 5](https://user-images.githubusercontent.com/4862573/82257860-69201400-991e-11ea-8e62-5640c3d1901e.png)



This join object view design makes it possible to define table views across databases of different types and users can perform SQL joins without the need for coding.

**Comment by jeanservaas** [comment]
Hi @fangshih and @tifftea 

Thanks so much for this proposal and all the background!

Carbon is working on a way to surface community components even when they don't have code attached. This is going to be a great way to highlight work like this, find out if there are other product teams approaching the problem differently and determine the demand for additions like this. Check out our progress at this link:

https://www.carbondesignsystem.com/community/component-index/

We think for now this will be a great place to showcase this work. At this time, unless there's a high demand from multiple product teams, Carbon doesn't have the dev resources to pick up this proposal.
