### ISSUE TITLE
Proposed design for editing column names in bulk

### ISSUE THREAD

**Issue by tifftea** [carbon-design-system/carbon#6034]
The HDM Data Virtualization has proposed having the ability to edit data table column header names inline.

In this particular use case, after joining two virtual objects, the user selects next to preview that table. They are given the option to edit the column names within the column header. 

Users need the ability to quickly edit multiple inputs in the table. Using a table format allows the user to have a familiar structure so they know what they are editing, while preserving a data preview, which provides context to help them determine what, if any, column names should be edited. 

Example: 

![box-image-13](https://user-images.githubusercontent.com/63752979/81250314-80cdd300-8fd5-11ea-9288-b45a6acdae90.png)

@fangshih

**Comment by emyarod** [comment]
do you have an existing spec for this proposal? if not our designers will need some additional time to create the component spec for this

**Comment by fangshih** [comment]
We have this existing spec. This page is like preview the objects you've joined. and it able to do multiple editing. We are currently using the input filed component on top of the column header. 

![inline editing01](https://user-images.githubusercontent.com/4862573/82711325-a7814000-9c4a-11ea-8c51-2a8741700bdc.png)
![inline editing02](https://user-images.githubusercontent.com/4862573/82711326-a8b26d00-9c4a-11ea-869e-f6af5060aa0d.png)
 
And once user reviews and done editing any of the column names. user can click "Next" for the next step of this process, and it will able to save it all. 
![inline editing03](https://user-images.githubusercontent.com/4862573/82711327-a94b0380-9c4a-11ea-802c-30d18b728912.png)

**Comment by sstrubberg** [comment]
Hey @tifftea, thanks for the issue and apologies for the super delayed response. This feels like an edge case and isn't a priority for our squad due to other priorities.
