### ISSUE TITLE
carbon-react: Slider not work well when updating value using keyboard if minimum value is not 0

### ISSUE THREAD

**Issue by chubbywhale** [carbon-design-system/carbon#6038]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When the minimum value is not 0, the slider will does not get updated correctly (visually and the actual value). I notice that when I press any direction key on keyboard, it will increase the value. Where I expect the value to decrease when I press LEFT or DOWN. Also, the value increase does not match what the step value that is specified.

> Is this issue related to a specific component?
Slider
> What did you expect to happen? What happened instead? What would you like to
> see changed?
Behaves correctly.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
The online storybook

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Go to https://react.carbondesignsystem.com/?path=/story/slider--default
2. Adjust the minimum value to 20 in the Knobs tab
3. Give focus to the slider knob by clicking on it
4. Press LEFT on keyboard and will see the value is increasing. The value should be decreasing instead of increasing. Press RIGHT will see the value increase more than the step specified.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
this issue should already be resolved (related #5945 #5982) 

you can confirm this by checking https://carbon-components-react.netlify.app/?path=/story/slider--default
