### ISSUE TITLE
Gradle build is failing when carbon-components is used as dependency.

### ISSUE THREAD

**Issue by RajaSreekanth** [carbon-design-system/carbon#604]
## Detailed description
 Failed to create MD5 hash for file '/home/jenkins/workspace/wdp-classifiers-ui_master-Y2UXLB4VWZBJ3NYAGQYCXWPG27AL752NDKFBJCVDXGUGJLT2XRFQ/node_modules/carbon-components/html/content-switcher/content-switcher???with-icon.html'

> Is this issue related to a specific component? 
The file, content-switcher--with-icon.html, is seen at couple of places. Everytime Jenkins is failing 
carbon-components/src/components/content-switcher/content-switcher???with-icon.html'
BTW, this was working earlier, not sure what else is changed.

> What did you expect to happen? What happened instead? What would you like to see changed?
Can we change this file's name?

> What version of the Carbon Design System are you using? 
I tried both 8.14.2 and 8.15.2

Thanks in advance,
Sreekanth

**Comment by RajaSreekanth** [comment]
@asudoh It is not clear if you've changed the file name from `content-switcher--with-icon.html` to `content-switcher-with-icon.html` Please confirm.

**Comment by RajkiranJogu** [comment]
The reported issue is solved now with "carbon-components": "^8.15.3", you can close this github issue.
Thanks
