### ISSUE TITLE
How to do vertical spacing using the Grid?

### ISSUE THREAD

**Issue by arcfide** [carbon-design-system/carbon#6042]
Is there any documentation or examples somewhere of managing Grid layouts using the 16-column grid with vertical spacing? The horizontal spacing seems fine, but, for example, doing the layout of a Login window in the center of a grid doesn't seem obvious from the vertical perspective. The main site just has some text indicating that they want to do a demo of vertical spacing, but there's no documentation on things that I can find.

**Comment by joshblack** [comment]
Hey there @arcfide! 👋 I don't believe there are any examples of doing vertical spacing, specifically for centering in the middle of a screen. I don't know if there is a single solution that we could offer that would address how folks would want to implement this, but if you have any ideas would love to hear them!

**Comment by arcfide** [comment]
Thanks, I think I'm also interested in any tooling that is provided for vertical spacing in general. There are a few times I've found myself needing to manually tweak things, and it would be helpful if there was more "automation" in vertical layouts.

**Comment by joshblack** [comment]
@arcfide I think really the only tools we offer for vertical rhythm are the spacing and layout tokens, if I remember correctly 👀 These should help with providing the values that one can use to vertically space objects on the page.

**Comment by arcfide** [comment]
Alright, sounds good. Thanks!

On May 12, 2020 at 16:09 GMT, Josh Black <notifications@github.com> wrote:

[@arcfide](https://github.com/arcfide) I think really the only tools we offer for vertical rhythm are the spacing and layout tokens, if I remember correctly 👀 These should help with providing the values that one can use to vertically space objects on the page.

**Comment by tw15egan** [comment]
Closing as resolved, feel free to reopen if you have more questions 👍

**Comment by wbudd** [comment]
@tw15egan I really don't see how this issue was in any way resolved at all, to be honest.
