### ISSUE TITLE
[DataTableSkeleton] Component adds extra, unwanted skeleton behaviour

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#6054]
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Issue #3032 updated the DataTableSkeleton component but that now breaks existing users of the components who weren't using all DataTable features. In our specific use case, we don't use DataTableContainer and thus don't have the title or description. When a user opens our page, it now jumps UI element around after loading.

Please either revert this to the previous behaviour or add optional props to inform the skeleton which parts should be shown.

A minor point, but this also now hides the table headers despite being passed to them as props.

## Expected

![image](https://user-images.githubusercontent.com/13081745/81452858-e65dc300-917f-11ea-925b-0573b9bcf17f.png)

## As-is

![image](https://user-images.githubusercontent.com/13081745/81452920-1c9b4280-9180-11ea-9532-7be6c4e0ad05.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. Same as #5993, let's discuss further there.
