### ISSUE TITLE
Modal Close button not working properly for BIDI (rtl )

### ISSUE THREAD

**Issue by andreabaader** [carbon-design-system/carbon#6056]
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description
Right to left behavior for Modal different then expected.

Is this issue related to a specific component?
-Modal

What did you expect to happen? What happened instead? What would you like to
- I would expect the Close button to adapt to direction rtl and move from right to left side. 

What browser are you working in?
 - Chrome , FireFox

What version of the Carbon Design System are you using?
 - carbon-components: 10.11.1
 - carbon-components-react: 7.11.3

What offering/product do you work on? Any pressing ship or release dates we
should be aware of?
- IBM Business Automation Workflow

## Steps to reproduce the issue

1. Step: Create a Modal 
2. Step: in App.scss  set direction to rtl

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/sweet-bird-t48vd?file=/src/index.js

## Additional information
![image](https://user-images.githubusercontent.com/46600663/81581704-5e5e0000-93af-11ea-916a-8f58d5064a4f.png)
- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - We rely on a toolstack that changes e.g. `left` to `right`, ([example](https://rtlcss.com)) to support BiDi. That said, do you have such kind of toolstack in place?

**Comment by andreabaader** [comment]
I do not understand the question. You can see in my sample I set the direction to "rtl" and the buttons in the footer change where the close button does not change its position. 

In my code I set the direction based on the language. And for most Carbon components this works fine, besides the problem in the Modal and the DataTable and the Structured list I saw a few problems with text alignment. 
Do you want to see my whole source code? I can not give you access to our product development github repository.

**Comment by asudoh** [comment]
To make the story short, your application needs to set up a toolchain, e.g. [RTLCSS](https://rtlcss.com/) to support RTL. In other words, `dir="rtl"` is not enough.

**Comment by sstrubberg** [comment]
@andreabaader is this still an issue?
