### ISSUE TITLE
Contribution: New UI icons for edge computing

### ISSUE THREAD

**Issue by livingston-john** [carbon-design-system/carbon#6065]
### Summary
Please describe your request in one or two sentences.
IBM Edge Application Manager has multiple resources that don't have an existing UI icon. I've done the design work in the attached SVGs, now I'm just looking to have this added to the Carbon Icons library.

### Justification
We are a new product in the edge computing space and we need some unique icons to represent our different resources in the UI. Anytime any other product related to edge computing can use these icons as well.

### Desired UX and success metrics

Looking to have these icons added to the Carbon Icons library in a new Edge category.

### Specific timeline issues / requests

Our next release of IBM Edge Application Manager is Version 4.1.0 on June 12, 2020

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Here are the icons for:

**Edge service**
![edge_service@6x](https://user-images.githubusercontent.com/65258688/81753630-d3960780-9479-11ea-999b-ed001be125ef.png)
![Screen Shot 2020-05-12 at 5 54 14 PM](https://user-images.githubusercontent.com/65258688/81753650-dee93300-9479-11ea-9f84-49d6b876a5bc.png)
[edge_service_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618868/edge_service_32x32.svg.zip)

**Edge device**
![edge_device@6x](https://user-images.githubusercontent.com/65258688/81753737-122bc200-947a-11ea-948c-68d5e0748280.png)
![Screen Shot 2020-05-12 at 5 53 39 PM](https://user-images.githubusercontent.com/65258688/81753750-1657df80-947a-11ea-9381-9a40641c61f1.png)
[edge_device_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618871/edge_device_32x32.svg.zip)

**Edge cluster**
![edge_cluster@6x](https://user-images.githubusercontent.com/65258688/81753782-2bcd0980-947a-11ea-9440-0d95c5b179ca.png)
![Screen Shot 2020-05-12 at 5 53 53 PM](https://user-images.githubusercontent.com/65258688/81753801-325b8100-947a-11ea-9eee-2be6c86994b8.png)
[edge_cluster_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618873/edge_cluster_32x32.svg.zip)

**Deployment policy**
![deployment_policy@6x](https://user-images.githubusercontent.com/65258688/81753844-5028e600-947a-11ea-8f75-5604ca2fb4db.png)
![Screen Shot 2020-05-12 at 5 54 38 PM](https://user-images.githubusercontent.com/65258688/81753856-574ff400-947a-11ea-9981-e66d78bb8fd5.png)
[deployment_policy_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618878/deployment_policy_32x32.svg.zip)

**Deployment pattern**
![deployment_pattern@6x](https://user-images.githubusercontent.com/65258688/81753904-7189d200-947a-11ea-8d35-c0d950814f30.png)
![Screen Shot 2020-05-12 at 5 54 27 PM](https://user-images.githubusercontent.com/65258688/81753911-76e71c80-947a-11ea-92ed-9218cccf7e6c.png)
[deployment_pattern_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618881/deployment_pattern_32x32.svg.zip)

Model
![model_1@6x](https://user-images.githubusercontent.com/65258688/81753943-8d8d7380-947a-11ea-810b-ac8bf6ab10c4.png)
![Screen Shot 2020-05-12 at 5 54 52 PM](https://user-images.githubusercontent.com/65258688/81753953-94b48180-947a-11ea-8e3d-001633707727.png)
[model_32x32.svg.zip](https://github.com/carbon-design-system/carbon/files/4618884/model_32x32.svg.zip)

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by aagonzales** [comment]
UI icons need to be submitted to the brand team for approval before adding them to the repo. 
You can submit an issue here fore review: https://github.ibm.com/brand/ui-icons/issues

**Comment by chrisconnors-ibm** [comment]
@conradennis

**Comment by conradennis** [comment]
@livingston-john please resubmit these icons to the UI icon repo here: https://github.ibm.com/brand/ui-icons/issues/new/choose

**Comment by conradennis** [comment]
issue was made in proper repo: https://github.ibm.com/brand/ui-icons/issues/29
@chrisconnors-ibm you can close this one
