### ISSUE TITLE
Sort icon on table headers in poor position (especially bad for wide columns)

### ISSUE THREAD

**Issue by Solly2** [carbon-design-system/carbon#6067]
Sort icon on table headers in poor position (especially bad for wide columns)

On sortable columns the sort icon sits aligned on the hard right ofthe cell.  This means that it is closer to the column to the right of the one which is actually being used for the sort.
![02b](https://user-images.githubusercontent.com/45822417/81813868-e82cdb00-951f-11ea-8fef-cedd97dd2181.png)

This can obviously lead to some usability issues with the user not being able to easily see which column is providing the sort.

As a fix I suggest either moving the icon to 16px to the right of the column header
![02b copy 2](https://user-images.githubusercontent.com/45822417/81814929-46a68900-9521-11ea-83cb-c37e19adeaea.png)

Or leaving the hover state on columns which have been sorted
![02b copy](https://user-images.githubusercontent.com/45822417/81815054-70f84680-9521-11ea-9145-9fdea5d92cd5.png)

**Comment by aagonzales** [comment]
The sorted data table row is actually supposed to keep the darker background color when applied. IBM Cloud brought this up a few months ago and I thought they were going to contribute the change but looks like it hasn't happened.

In general, the aligned is this way to reflect the IBM Language intent. Icons always align to the right side of container they are in. It is done like this through out the system. 

![image](https://user-images.githubusercontent.com/11670886/88109972-042ca880-cb71-11ea-88b9-1dfbf824cd05.png)

**Comment by tw15egan** [comment]
@aagonzales I'll put in a quick fix for the active sorting column so that it retains a selected background, but going to close the issue as won't fix re: icons
