### ISSUE TITLE
Searching on tables should be open always

### ISSUE THREAD

**Issue by Solly2** [carbon-design-system/carbon#6068]
Searching on tables is a primary function.  Hiding the search field behind an icon and interaction gets between the user and the content they are trying to find.

We will have tables which contain the objects a user has created, for example Queue Managers, which will range into the hundreds for a number of our customers.

As we are the Cloud Pak for Integration we don't want to tell all of the seperate engineering teams to be overriding Carbon as this will lead to greater inconsistency.

As such we would like to have the search bar on tables open by default in Carbon.

![03](https://user-images.githubusercontent.com/45822417/81815960-933e9400-9522-11ea-9c66-29fa7c7c1045.png)

**Comment by tw15egan** [comment]
@Solly2 there is a `persistent` prop on `TableToolbarSearch` that ensures the search by default is open, and cannot be closed. Would this be an acceptable solution?

**Comment by Solly2** [comment]
Hey @tw15egan  this sounds good - we can document usage in the cloud pak to use this property.

Does the search bar go all the way across the top of the table as in the image?  

Thanks!

**Comment by tw15egan** [comment]
Sure does!

<img width="1652" alt="Screen Shot 2020-05-14 at 11 23 25 AM" src="https://user-images.githubusercontent.com/11928039/81971079-5da6b300-95d5-11ea-96b9-06d17beb90dc.png">

<img width="737" alt="Screen Shot 2020-05-14 at 11 24 18 AM" src="https://user-images.githubusercontent.com/11928039/81971151-7c0cae80-95d5-11ea-957b-9a30dca96596.png">


I hope this has solved your issue. Going to close this as resolved, but feel free to reopen if you want us to provide any more info 👍
