### ISSUE TITLE
Forward ref for Link component

### ISSUE THREAD

**Issue by nsemml** [carbon-design-system/carbon#6069]
We render `HeaderNavigation` and it gives a console warning, pointing to `Link` component

```
Check the render method of `Link`.
    in NavLink (created by Link)
    in Link (created by ForwardRef(HeaderMenuItem))
    in li (created by ForwardRef(HeaderMenuItem))
    in ForwardRef(HeaderMenuItem) (created by HeaderNavigation)
    in ul (created by HeaderNavigation)
    in nav (created by HeaderNavigation)
    in HeaderNavigation (created by MainNavigation)
```

<img width="480" alt="refs" src="https://user-images.githubusercontent.com/45028998/81828209-d5bf9b00-9539-11ea-801b-2de12a1a9655.PNG">

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

carbon-components-react@7.11.3

I hope this information is sufficent, please do not hesitate to ask for more.

**Comment by joshblack** [comment]
Hey there @nsemml! 👋  Could you provide some code to help us reproduce this problem? You can use [codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) as a sandbox if that's helpful 👀

**Comment by nsemml** [comment]
Hey @joshblack, thank you for requesting further investigation. Only by trying to reproduce the code I have taken a closer look and noticed that `NavLink` is actually from `react-router-dom` dependency. We are passing it as `element` prop to `HeaderMenuItem`

So this is not an issue of carbon components react. I will close this issue and see if I re-raise it in the react-router-dom github.

Thank you and sorry for any effort this might have caused
