### ISSUE TITLE
Pagination (v2): doesn't support multi-digits numbers in select

### ISSUE THREAD

**Issue by imposibrus** [carbon-design-system/carbon#607]
## Detailed description

Select's arrow overflows number.

> Is this issue related to a specific component? 

Pagination (v2)

> What did you expect to happen? What happened instead? What would you like to see changed?

Select should have "elastic" width.

> What browser are you working in? 

- Safari TP Release 50 (Safari 11.2, WebKit 13606.1.5)
- Google Chrome 64.0.3282.167 

> What version of the Carbon Design System are you using? 

carbon-components@8.14.2

## Steps to reproduce the issue

1. Have more than 9 pages in pagination

## Additional information

![image](https://user-images.githubusercontent.com/3369328/36537477-4c7978ca-17e1-11e8-8754-44c6b002f588.png)

**Comment by petersandor** [comment]
I experience the same problem. 

Also, there are major performance and usability issues when there are hundreds or more pages (in case of server-side pagination).
