### ISSUE TITLE
bug(Dropdown Option)Fix extra right padding

### ISSUE THREAD

**Issue by DusanMilko** [carbon-design-system/carbon#6074]
## Dropdown extra padding

Dropdown has extra padding that isnt needed and would allow for longer text

Screenshots:

![Screen Shot 2020-05-13 at 4 24 12 PM](https://user-images.githubusercontent.com/302239/81867613-980d4300-9536-11ea-95bb-35d1ad935dbe.png)
![Screen Shot 2020-05-13 at 4 24 18 PM](https://user-images.githubusercontent.com/302239/81867625-9b083380-9536-11ea-989f-55839cd66788.png)

**Comment by tw15egan** [comment]
I believe that space is needed for Combobox selection, as now the text will lay under the checkmark. 

Perhaps this change should only affect rows that do not have the checkmark added?

<img width="365" alt="Screen Shot 2020-05-14 at 10 36 17 AM" src="https://user-images.githubusercontent.com/11928039/81966781-d6eed780-95ce-11ea-9deb-d0f3b72048f1.png">
