### ISSUE TITLE
Select - `size` is not required, yet does not have default value & generates warnings

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#6076]
## Detailed description

The `size` prop in the `Select` is not marked required, yet it does not have a default value.

If you attempt to use `Select` without specifying a value for the `size` prop -- that is, if you are trying to use a regular-sized `Select` -- you will get a lot of propType warnings in your developer console.

## Steps to reproduce

Just use `Select` in development, and don't pass it a `size` value (as if you are trying to use a non small, non x-large `Select`).

**See this example & view the console: https://codesandbox.io/s/agitated-sunset-cfvxs?file=/src/App.js**

![81719802-22747a80-9443-11ea-8f47-11f22b9e49d1](https://user-images.githubusercontent.com/9057921/81869050-f9361600-9538-11ea-9a8f-c770b1980d98.png)

**Comment by tw15egan** [comment]
Any idea why the warning does not throw when using our components rather than the security implementation? 

https://codesandbox.io/s/stoic-mestorf-rsvux?file=/src/App.js

**Comment by jendowns** [comment]
@tw15egan I'm not sure 🤔  it's not much of an implementation though. It's imported & exported here: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/Select/index.js

**Comment by jendowns** [comment]
@tw15egan AH wait a second, we are on version 7.10.0 👀 
I don't believe the error is present in 7.11.3 because it's been fixed since then 😆 

Thanks for looking into this -- I'm going to close out this issue as I think we need to update on our end to stop seeing this error 👍

**Comment by tw15egan** [comment]
😅phew! I was really hoping this was solved for good 🙏
