### ISSUE TITLE
Select looks bad on Windows and bold text is opposite from Mac

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#608]
## Detailed description
On Chrome on Windows, when you open the Select component, there is no whitespace between the top line of text and the border.  Also, the dropdown has one extra pixel on each side so it doesn't align with the box.  I would think you'd want it to align on the left, at least, or look like a more intentional mis-alignment, like on the Mac.

Also, on the Mac, the categories in the dropdown are grayed out and the options are bold.  On Windows, the categories are bold and the options are in plain text.

On IE11, there is a weird shadow on the placeholder text, and there is no whitespace at the top of the dropdown and lots of whitespace at the bottom of the dropdown.

> What version of the Carbon Design System are you using? 
8.11

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
OpenPages.  99% of our customers are on Windows.  

## Steps to reproduce the issue
Look on your own Storyboard on Windows.

## Additional information
Windows - Chrome
![image](https://user-images.githubusercontent.com/30597411/36552654-616c2f20-17c8-11e8-8b77-4c927fad12af.png)
Mac - Chrome
![image](https://user-images.githubusercontent.com/30597411/36552673-6dcc2022-17c8-11e8-9bf8-f014af418270.png)
Windows - IE11
![image](https://user-images.githubusercontent.com/30597411/36552865-e915076c-17c8-11e8-9390-17c753476f29.png)

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
As far as I know, these are the browser/system OS default select menu's. We try not to override styles on select elements as each vendor has a different implementation.

If you'd like a more polished version, you can always use the `dropdown` component, though we recommend using a `select` component if the element is being used in the context of a form

**Comment by kglickman** [comment]
Yes, it looks like you're right.  Can we do validation on the dropdown component like you can for a select?

**Comment by kglickman** [comment]
Actually, never mind about the validation.  It looks like there isn't any on the select, either.  We have a use case where it is required and we can't pre-select a default.  I guess we'll be rolling our own.

**Comment by tw15egan** [comment]
@kglickman Not on a dropdown, but you can do validation on a select element, [here is an example](https://codepen.io/tjegan/pen/OQwLvV)

The styles are looking for `select[data-invalid]` and then will look for a `bx--form-requirements` div (that you'll add) adjacent to the select element. [Here is a link to the source code as well](https://github.com/carbon-design-system/carbon-components/blob/master/src/components/form/_form.scss#L45)

I'm going to go ahead and close this, but feel free to ping me directly if you have any more concerns!
