### ISSUE TITLE
Institute CLA Policy for Carbon Contributors

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#6087]
From @claycrenshaw 

>Some contributors on GH have not filled out their identity information, and are only identifiable by a GH handle. This raises a number of problems, including the inability to put comments, PRs, etc. into a meaningful corporate context. If I need to reach out to someone on Slack, for instance, I have no way of knowing that person's real name. @joshblack

**Comment by joshblack** [comment]
@mattrosno I'm just going to move this over to monorepo so it doesn't get stale-botted lol

**Comment by tay1orjones** [comment]
Could this be extended to include other PAL/BU libraries under the `carbon-design-system` org?

**Comment by mattrosno** [comment]
@tay1orjones that's the plan!

**Comment by tw15egan** [comment]
@mattrosno any updates on this issue?

**Comment by mattrosno** [comment]
> @mattrosno any updates on this issue?

No update.

**Comment by joshblack** [comment]
Should be handled by https://github.com/carbon-design-system/carbon-dco !
