### ISSUE TITLE
Data table loading state misalignment

### ISSUE THREAD

**Issue by chloepoulterdesign** [carbon-design-system/carbon#6093]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

When the data table is loading, the table header text misaligns vertically (too high). Once the table is loaded, the table header text become correctly aligned.
The skeleton table does not preserve the height of the headers.

Chrome (and all other tested browsers)

Carbon v10.12.0
In this release of Carbon, the loading state headers take on the inline-loading style (like the table rows) however, the alignment issue is still there. 

We are IBM Event Streams in IBM Cloud Pak for Integration. This was initially raised by Arin Bhowmick in our 2019.4.1 release review, and persists, however will not be a stop-ship issue for our pending June release.

## Steps to reproduce the issue

1. Navigate to a table containing a table
2. While the table is loading, look at the table header
3. Note that the table headers are about 8px too high.

I'm afraid I don't code so can't create the codesandbox.

## Additional information

Screenshot (sorry, from previous release of carbon)
![image](https://user-images.githubusercontent.com/47979346/82074511-caec3e00-96d2-11ea-82fb-2b0feb109f03.png)
![image](https://user-images.githubusercontent.com/47979346/82074682-0ab32580-96d3-11ea-9cde-f79bdbbdb835.png)

Our vis thinks it's caused by an absence of <TableHeader /> when rendering headers in the following:
![image](https://user-images.githubusercontent.com/47979346/82074700-130b6080-96d3-11ea-8fad-75a1951994fc.png)
which is causing an absence of <span class="bx--table-header-label"> as child of the <th> component.

**Comment by emyarod** [comment]
>Our vis thinks it's caused by an absence of when rendering headers in the following:

>which is causing an absence of as child of the component.

I'm not able to reproduce this with our default table skeleton, but I'm also not sure what you're referring to as being absent in the description. it would be great if you could create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging, or have someone else create one that illustrates the issue
