### ISSUE TITLE
DatePicker - Date format is not correct based on locale.

### ISSUE THREAD

**Issue by swatpand158** [carbon-design-system/carbon#6099]
## Brief description
Using DatePicker Component - https://www.carbondesignsystem.com/components/date-picker/usage
Date format is not correct on the change of browser locale and component is accepting locale attribute.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> What did you expect to happen? What happened instead? What would you like to
> see changed?

DateFormat should be changed as per locale 
For example - 
FR date format is dd/mm/yyyy
RU date format is dd.mm.yyyy

> What version of the Carbon Design System are you using?

It happens with the latest version as well as tested here https://codesandbox.io/s/goofy-greider-dbk0g?file=/index.js

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

I have been working on wkc governance UI and got issue assigned which is using DatePicker component. 
https://github.ibm.com/wdp-gov/tracker/issues/27592

## Steps to reproduce the issue

1. Step one - Click on DatePicker component
2. Step two - Select date
3. Step three - It should be formatted based on what locale is.

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/goofy-greider-dbk0g?file=/index.js

## Additional information

- Screenshots or code
<img width="302" alt="Screenshot 2020-05-18 at 4 01 04 PM" src="https://user-images.githubusercontent.com/65540102/82203336-cf0d9b00-9920-11ea-9728-9ba0402f831f.png">

```
 <DatePicker
    dateFormat="m/d/Y"
    datePickerType="single"
    id="date-picker"
    locale="ru"
  >
    <DatePickerInput
      id="date-picker-input-id"
      labelText="Date Picker label"
      pattern="d{1,2}/d{4}"
      placeholder="mm/dd/yyyy"
      type="text"
    />
  </DatePicker>
```

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Have you tried changing `dateFormat` prop?

**Comment by swatpand158** [comment]
Hi @asudoh https://codesandbox.io/s/goofy-greider-dbk0g?file=/index.js in this example I have tried. let me know there is any other way of using it.

**Comment by asudoh** [comment]
I see `dateFormat="m/d/Y"` in the link... Probably you forgot to update the sandbox?

**Comment by swatpand158** [comment]
Let me know what is the correct way of using the dateFormat? I will try that out.

**Comment by asudoh** [comment]
Please refer to: https://flatpickr.js.org/options/

**Comment by swatpand158** [comment]
Hi @asudoh Can you try here working code https://codesandbox.io/s/goofy-greider-dbk0g?file=/index.js and let me know.. 

What is the use of locale prop then?

**Comment by asudoh** [comment]
Did you try `<DatePIcker dateFormat="m.d.Y">`?

**Comment by tw15egan** [comment]
Closing as resolved
