### ISSUE TITLE
NumberInput has 2 sets of arrows and the official set makes value undefined

### ISSUE THREAD

**Issue by nancywang1991** [carbon-design-system/carbon#6104]
Hi there,

I'm pretty new to frontend development and React so this might be a newbie issue. For some reason, the NumberInput has these two sets of arrows and when I use the inner arrow, it sets the value correctly for my onChange function but the outside one does not. Strangely, when clicking either set, they change the number display correctly. Can you please let me know what I can do to help solve this issue? 
<img width="159" alt="Screen Shot 2020-05-18 at 10 08 24 AM" src="https://user-images.githubusercontent.com/5560548/82240701-b8028500-98ef-11ea-8e04-e9f5b18c8be0.png">
`<div class="bx--number__input-wrapper"><input type="number" pattern="[0-9]*" id="epoch-input" max="100" min="0" step="1" aria-label="Numeric input field with increment and decrement buttons" value="1"><div class="bx--number__controls"><button class="bx--number__control-btn up-icon" type="button" title="Increment number" aria-label="Increment number" aria-live="polite" aria-atomic="true"><svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" width="8" height="4" viewBox="0 0 8 4" aria-hidden="true" class="up-icon"><polygon points="0,4 4,0 8,4"></polygon></svg></button><button class="bx--number__control-btn down-icon" type="button" title="Decrement number" aria-label="Decrement number" aria-live="polite" aria-atomic="true"><svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" width="8" height="4" viewBox="0 0 8 4" aria-hidden="true" class="down-icon"><polygon points="8,0 4,4 0,0"></polygon></svg></button></div></div>`

I have a similar issue with the select component but this time, it has no functional impact, only cosmetic. 

![image](https://user-images.githubusercontent.com/5560548/82240964-27787480-98f0-11ea-8523-b140ff720eba.png)

`<div class="bx--select"><label for="select-model" class="bx--label"></label><div class="bx--select-input__wrapper"><select id="select-model" class="bx--select-input" style="margin-left: 20px;"><option class="bx--select-option" value="--all_files--" selected="">All</option><option class="bx--select-option" value="file.pdf">file.pdf</option></select><svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" aria-hidden="true" class="bx--select__arrow"><polygon points="8,11 3,6 3.7,5.3 8,9.6 12.3,5.3 13,6"></polygon></svg></div></div>
`
Thank you!

**Comment by tw15egan** [comment]
Seems like you are missing an autoprefixer as part of your build process, here is our webpack config as an example:

https://github.com/carbon-design-system/carbon/blob/master/packages/react/.storybook/webpack.config.js#L145

**Comment by nancywang1991** [comment]
Thank you, it works now!

**Comment by nancywang1991** [comment]
Actually, it cosmetically looks good now but I'm still getting undefined for the number when I use the arrows ValueError: invalid literal for int() with base 10: 'undefined' , but it works fine if I manually type in a number. Help? :)

**Comment by tw15egan** [comment]
Do you have a link to a codesandbox for debugging purposes?
