### ISSUE TITLE
`pictograms-react` not rendering in latest release

### ISSUE THREAD

**Issue by ashharrison90** [carbon-design-system/carbon#6107]
## What package(s) are you using?

`@carbon/pictograms-react@10.11.0`

## Detailed description

> Describe in detail the issue you're having.

Pictograms don't render

> Is this issue related to a specific component?

any pictogram in `@carbon/pictograms-react`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

They would render.

> What browser are you working in?

Chrome Version 81.0.4044.129

> What version of the Carbon Design System are you using?

`@carbon/pictograms-react@10.11.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Import a pictogram
2. Use it as described in the `README`

see sandbox below...

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/zealous-darwin-ccotq?file=/src/index.js

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hey there @ashharrison90! 👋 Thanks so much for the report, definitely don't know what's going on and will investigate and see what the scope of the regression is. Have reverted back to 10.10.2 as latest in the interim so it should be working as-intended now.

**Comment by joshblack** [comment]
Ah, looking at it the problem seems to be that the assets expect to be filled by `stroke` and not `fill`. Example: https://codesandbox.io/s/relaxed-shannon-8lmvj

Let me see if we can default the value to `currentColor` as a fix. In previous versions, this value was hardcoded as a hex value (typically `#000`)
