### ISSUE TITLE
Multiselect - need full text on hover when item has ellipsis

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#6108]
We have some long elements in multi-select dropdowns that are displayed with an ellipsis.  However, there is no way to hover over the item to see the full text.  For dropdown, we implemented itemToElement and added the title attribute to the element.  However, multiselect does not have an itemToElement function.

## What package(s) are you using?

- [x ] `carbon-components-react`

![image](https://user-images.githubusercontent.com/30597411/82346377-5eb85580-99c4-11ea-82e9-69d2c1670324.png)

**Comment by tw15egan** [comment]
Do you have a link to a CodeSandbox showing this problem?

It seems to be enabled by default on our storybook: https://react.carbondesignsystem.com/?path=/story/multiselect--default

**Comment by kglickman** [comment]
Sorry.  I forgot to test in the latest version of Carbon.  I see it works in the story book.

**Comment by tw15egan** [comment]
Going to close this as resolved then, feel free to reopen if you need us to take another look
