### ISSUE TITLE
Webpack fails to build Carbon when it uses @IBM/Plex module

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#611]
## Webpack fails to build Carbon due to issue in IBM Plex
Using `v8.16.0` of Carbon results in the following errors:

![image](https://user-images.githubusercontent.com/6926228/36610761-5bc49db4-189f-11e8-9958-e9947ee80d37.png)

### Steps to reproduce the issue

1. Install `v8.16.0`
2. Build your app using Webpack

### Additional information

My Webpack SASS configuration:

**Note** that I still get the error with or without `includePaths` option.

```js
 {
        test: /\.s?css$/,
        use: [
          require.resolve('style-loader'),
          {
            loader: require.resolve('css-loader'),
            options: {
              importLoaders: 2,
            },
          },
          {
            loader: require.resolve('sass-loader'),
            options: {
              includePaths: [path.resolve(__dirname, 'node_modules')],
            },
          },
        ],
},
```

**Comment by seejamescode** [comment]
Oh duh! We should of added @ibm/plex as a dependency or peerDependency for those compiling their own Sass. My bad.

@Yohanna, this should resolve for you if you add the `@ibm/plex` package to your project.

Carbon maintainers, which one would you like it as?

**Comment by asudoh** [comment]
My bad, too, about my oversight! Thinking of `peerDependency` - @joshblack what do you think?

**Comment by marijohannessen** [comment]
My vote is for `peerDependency` as well

**Comment by Yohanna** [comment]
Thanks everyone :)
