### ISSUE TITLE
Tag component only sets title if filter

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#6111]
I have a Tag that contains long text, so it is truncated with an ellipsis.  I want to set the title attribute so that when the user hovers over the tag, they can see the full text.  

In "carbon-components-react": "7.9.0", if the tag is a filter tag, the title gets passed through.  Otherwise, the title is not used.  I don't want to use the filter just to get the title because it requires a lot of styling overrides.

In the latest code, title doesn't work for the filter version, either.

**Comment by kglickman** [comment]
Looks like we can handle this using .bx--text-truncate--end.  This can be closed.

**Comment by tw15egan** [comment]
`.bx--text-truncate--end` won't add a title on to the component. Would #6112 resolve your issue?

**Comment by kglickman** [comment]
Sorry, I gave a very incomplete explanation of our solution.  We fixed it by adding both the title attribute and the .bx--text-truncate-end to a child element inside the Tag.

#6112 would probably be helpful for the next person, though.
