### ISSUE TITLE
Title not passed down to for SideNavMenu

### ISSUE THREAD

**Issue by aviral2311** [carbon-design-system/carbon#6116]
## Title line template:
There is no tooltip for SideNavMenu for long text.

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
For long text in SideNavMenu, there is truncation in the end , but when we pass 'title' prop to the component that there is no tooltip on hover.

> Is this issue related to a specific component?
SideNavMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?
we expected tooltip to display full text. 

> What browser are you working in?
Chrome

**Comment by tw15egan** [comment]
Do you have a link to a reproducible example? I was able to set a title on `SideNavMenuItem` and have it appear 

```jsx
<SideNavMenuItem title="This is some really long text to test">
    This is some really long text to test
</SideNavMenuItem>
```

![ui-shell-title](https://user-images.githubusercontent.com/11928039/83560475-2daf4900-a4cb-11ea-8e79-d6c86c03e331.gif)

**Comment by aviral2311** [comment]
I think I need to edit this bug. The issue is with SideNavMenu component. In Your Case, Category Title.
