### ISSUE TITLE
[Skeletons] Animations not working on Safari

### ISSUE THREAD

**Issue by Tony9984** [carbon-design-system/carbon#6117]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using any Skeleton component for loading, they do not have animations on Safari. It only displays placeholder blocks, but they do not move like they are supposed to in other browsers

> Is this issue related to a specific component?

No, all skeleton components

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Have the animations working on safari

> What browser are you working in?

Safari 13.1

> What version of the Carbon Design System are you using?

7.11.3

**Comment by tw15egan** [comment]
Do you have a reproducible example? 

I'm viewing https://react.carbondesignsystem.com/?path=/story/datatableskeleton--default in safari and I am seeing the animations. Also using v13.1

**Comment by Tony9984** [comment]
Got it working... was a bug on my part. Sorry for the trouble, closing the issue
