### ISSUE TITLE
Are the sketch files public for carbon chart visualizations?

### ISSUE THREAD

**Issue by pranay01** [carbon-design-system/carbon#6123]
Hi 
I couldn't find the chart visualizations in Carbon sketch theme files. Are they public? Can someone share the sketch file link for these visualizations?

**Comment by laurenmrice** [comment]
The sketch file is not available yet but someone on our team is currently working on it to make it production ready. We will share it once it is finalized!

**Comment by joshblack** [comment]
Should be available here if I understand correctly! https://www.carbondesignsystem.com/data-visualization/getting-started/
