### ISSUE TITLE
Recent change affected multi-line accordion titles

### ISSUE THREAD

**Issue by tombrunet** [carbon-design-system/carbon#6127]
Our accordions changed recently, and I believe it's related to https://github.com/carbon-design-system/carbon/pull/5992
![image](https://user-images.githubusercontent.com/19577713/82462687-84576480-9a81-11ea-86d2-060cb02068fc.png)

In our working version, there is no height set on the heading, and the heading heights adjust for the text as expected. In an identical stage deployment, we're getting overlapping headings and the only change I can find is that a set height is assigned to the bx--accordion__heading. If I clear the height: 2.5rem from the heading, it works as expected again.

Excepted behavior:
![image](https://user-images.githubusercontent.com/19577713/82462967-d8fadf80-9a81-11ea-800e-52fab9dd084a.png)

Just to be clear, the left padding from the chevron is ours. This is just about the heading no longer adjusting height when the heading wraps.

As response to this in the PR, I was asked to open this as a new issue, and suggestion to change `height` to `min-height`

**Comment by tw15egan** [comment]
Thanks @tombrunet! Looks like @emyarod already has a fix in for it 👍
