### ISSUE TITLE
BUG: Number inputs without min and max values are broken

### ISSUE THREAD

**Issue by davefp** [carbon-design-system/carbon#6131]
## What package(s) are you using?

- [x] `carbon-components 10.12.0`
- [ ] `carbon-components-react`

## Detailed description

Using  a `NumberInput` without a max or min value will break the increment/decrement functionality respectively.

## Steps to reproduce the issue

1. Add a number input to the page. Use a template from here: https://the-carbon-components.netlify.app/?nav=number-input
2. Make sure the input itself has no `min` or `max` value set.
3. Visit the page in the browser and click the up or down arrows on the number inputs.
4. Observe that the up arrow doesn't increase the input value.
5. Observe that the down arrow sets the input value to zero.

Codesandbox here:

https://codesandbox.io/s/relaxed-dream-g2flm

## Additional information

- The offending code is here: https://github.com/carbon-design-system/carbon/blob/d738dbc6d0e1d1c9ab1a193dc0dd9f623c4685c9/packages/components/src/components/number-input/number-input.js#L50

Since the value of `numberInput.max` is the empty string, casting it to a `Number` makes it `0`.

**Comment by signoutday** [comment]
H

**Comment by signoutday** [comment]
J
