### ISSUE TITLE
[Question]Translation issue

### ISSUE THREAD

**Issue by zhuzmzm** [carbon-design-system/carbon#6135]
Currently carbon widget doesn't do any work on global translation. Do we have any plan to work on it?

**Comment by emyarod** [comment]
Would you mind providing some additional context to your question by filling out [one of our issue templates](https://github.com/carbon-design-system/carbon/tree/master/.github/ISSUE_TEMPLATE)?

**Comment by zhuzmzm** [comment]
Put a screenshot here for example. The red part are used common Carbon widget and don't do the translation.

![image](https://user-images.githubusercontent.com/42019585/82966957-9e9fbe00-9ffe-11ea-9572-a8d4072edc3c.png)

**Comment by emyarod** [comment]
I see, this looks like the data table and pagination components together, is that correct? The pagination component text should be configurable via props, but I don't believe the table toolbar can at the moment

**Comment by asudoh** [comment]
Weighing in; `n items selected` and `Cancel` words can be translated via [`translateWithId` prop in `<TableBatchActions>`](https://github.com/carbon-design-system/carbon/blob/v10.12.0/packages/react/src/components/DataTable/TableBatchActions.js#L36).
