### ISSUE TITLE
Accordion chevron always rendered right hand side

### ISSUE THREAD

**Issue by ukuhnhardt** [carbon-design-system/carbon#6136]
Documentation https://react.carbondesignsystem.com/?path=/story/accordion--default suggests the chevron can be rendered RHS or LHS depending on the `align` prop.

## What package(s) are you using?

-[x]    "carbon-components": "8.18.0",
-[x]    "carbon-components-react": "5.34.0",
-[x]    "carbon-icons": "6.3.2",
-[x]    "react": "16.2.0",
-[x]    "react-dom": "16.2.0",

## Detailed description

Accordion chevron always rendered right hand side
https://codesandbox.io/s/carbon-components-react-6tdio?file=/src/index.js even though `align='start'` is specified.

> Is this issue related to a specific component?
`Accordion`, `AccordionItem`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
When I specify `align='start'` the chevron should be rendered on the LHS

> What browser are you working in?
Chrome/FF

> What version of the Carbon Design System are you using?
??
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Goto https://codesandbox.io/s/carbon-components-react-6tdio?file=/src/index.js

**Comment by emyarod** [comment]
this is because your dependencies are out of date https://codesandbox.io/s/carbon-components-react-3z6ht

**Comment by joshblack** [comment]
Hi there @ukuhnhardt! 👋  it seems like you are using v8 of `carbon-components` and v5 of `carbon-components-react`. Unfortunately, this functionality is only available in v10 of `carbon-components` and v7 of `carbon-components-react`
