### ISSUE TITLE
Regression: Header border disappeared

### ISSUE THREAD

**Issue by virkt25** [carbon-design-system/carbon#6142]
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

`bx-header` class had a border on it before and it was removed. This really makes a page look wonky.

Before (version 10.10.3)
![image](https://user-images.githubusercontent.com/3311536/82962635-c0f9f300-9f8e-11ea-83e1-46825bbda07a.png)

After (latest)
![image](https://user-images.githubusercontent.com/3311536/82962651-cd7e4b80-9f8e-11ea-916f-f663f2932285.png)

Change in question:
https://github.com/carbon-design-system/carbon/commit/49e87c8e1e507c2a24075ad244e4a961f7db8d72#diff-f8c1a41d640bb6e6c4213525998e936eL30

> Is this issue related to a specific component?

UI-Shell

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like to see the border back because without it everything looks really messed up.

> What browser are you working in?

> What version of the Carbon Design System are you using?

Had to revert from latest to 10.10.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM CustomerSuccess360

**Comment by virkt25** [comment]
Any updates on this @tw15egan

**Comment by tw15egan** [comment]
Just put up a PR https://github.com/carbon-design-system/carbon/pull/6204
