### ISSUE TITLE
contrast ratio for "Filter table" is lower than the minimal text contrast requirement

### ISSUE THREAD

**Issue by pankaj-kumar34** [carbon-design-system/carbon#6144]
For smaller text: non-bold text that is less than 18 point and bold text that is less than 14 point, the contrast ratio is equal to or greater than 4.5:1.

The current ratio is 2.1:1.
![image](https://user-images.githubusercontent.com/18532515/82976201-13bdc400-9ffc-11ea-8fb7-5b706d9627e8.png)

Checkpoint 1.4.3 Contrast (Minimum): https://www.ibm.com/able/guidelines/ci162/contrast.html

===================
Configuration instructions to check contrast ratio of text with its background:
For Internet Explorer®:
Use the Web Accessibility Toolbar (WAT) Colour Contrast Analyser (CCA) to check the color contrast ratio of text with its background on the Web page. Another option is use the Colour Contrast Analyser as a standalone application - it can be used with the Firefox browser or any other application as well (refer to Configuration instructions to run standalone Colour Contrast Analyser).

From the WAT, select Colour from the browser toolbar menu.
Select Contrast Analyser [application] from the drop down menu to launch the Colour Contrast Analyser application.
Press F11 to open the eyedropper sampling tool, then use tool to hover over and select the prominent color for the foreground text.
Press F12 and repeat to select the prominent color for the text's background color.
Confirm that the contrast ratio passes per Checkpoint 1.4.3 Contrast (Minimum). Compliant ratios are based on the text size.

**Comment by dakahn** [comment]
Seems to be something off in Firefox. Opened a ticket here https://github.com/carbon-design-system/carbon/issues/6908

**Comment by pankaj-kumar34** [comment]
Hi, i see the issue is still not fixed 
![image](https://user-images.githubusercontent.com/18532515/102748360-06956780-4388-11eb-8332-488739435216.png)

Version used to test this fix.
@console/pal : 1.310.3

**Comment by deepika-bachu** [comment]
I am requesting to reopen this one as we are unable to see the fix at our end and - this affects our product's accessibility compliance due to the dependency. @emyarod  - Could someone please look into this?

**Comment by emyarod** [comment]
does your version of Carbon include #6914?
