### ISSUE TITLE
On / Off switch is not visiable after removing color from text

### ISSUE THREAD

**Issue by pankaj-kumar34** [carbon-design-system/carbon#6145]
![image](https://user-images.githubusercontent.com/18532515/82976288-49fb4380-9ffc-11ea-9814-4bfa40fa1168.png)
![image](https://user-images.githubusercontent.com/18532515/82976294-4ebff780-9ffc-11ea-915e-fa6aee6c6cf4.png)
Checkpoint 1.4.1 Use of Color: https://www.ibm.com/able/guidelines/ci162/color.html

================
To configure the browser to ignore colored text:
Firefox:
Select Tools>Options...
On the Content tab, in the Fonts & Colors section, select the Colors... button.
In the Colors dialog box, select the Use system colors checkbox and deselect the Allow pages to choose their own colors, instead of my selections above checkbox.
Select OK to save changes.
Select OK to exit the Options dialog box.

**Comment by dakahn** [comment]
If you're testing whether or not color is the sole means of conveying information removing colors through your browsers config isn't a reliable way to determine that.

That said, we have an existing issue tracking the Toggle components visual accessibility in High Contrast modes here #6882
