### ISSUE TITLE
DataTable: select all action is slow and block ui when the table has thousands of rows even with pagination

### ISSUE THREAD

**Issue by Aaron-Hu** [carbon-design-system/carbon#6146]
### Summary
I use DataTable to list my data, because there may have lots of rows, so i implement pagination for this table. For example 6000 rows.  The select all action is slow and block ui for about 6 seconds. If there are 50000 rows of data, the section all action can crash my browser. However, the other actions like search, sort, pagination is fast.
![image](https://user-images.githubusercontent.com/19277713/83005243-23acc680-a043-11ea-8e97-03eeb4711129.png)
The wired thing is, select one by one is fast. 
And the cancel action is slow even there is only one selected and may crash browser if has more data.
![image](https://user-images.githubusercontent.com/19277713/83005734-c1a09100-a043-11ea-87a3-7c92931c4a38.png)

Here is my pagination code. If without the pagination, the select all can be slow too. I think the select all may need optimization inside the DataTable. 
```
<TableBody>
                  {rows
                    .slice((page - 1) * pageSize, page * pageSize)
                    .map(row => (
                      <TableRow key={row.id}>
                        <TableSelectRow {...getSelectionProps({ row })} />
                        {row.cells.map(cell => getCell(cell))}
                      </TableRow>
                    ))}
                </TableBody>

```
### Justification

This issue has effect on the user experience of our product.

**Comment by ljitendra** [comment]
Not just Select All, even radio selection is very slow. Need to add this point to this defect's scope as well.

**Comment by sstrubberg** [comment]
@Aaron-Hu let me know if this is still needed. Happy to re-open.
