### ISSUE TITLE
[Button] incorrect focus spec

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon#6152]
In code, the focus state for button is 3px border + 1px gap, but it should be 2px + 1px gap. It is correct in the style tab and in the sketch kits

<img width="1257" alt="Screen Shot 2020-05-27 at 2 12 55 PM" src="https://user-images.githubusercontent.com/47458576/83062488-5bf0dc80-a024-11ea-84f3-020c77fe440c.png">

**Comment by emyarod** [comment]
would this change be closer to the spec?

![image](https://user-images.githubusercontent.com/8265238/83185022-f538f500-a0ef-11ea-89fe-53bc9cdc660e.png)

**Comment by peter-garvin** [comment]
yeah that looks correct to me
