### ISSUE TITLE
https://carbon-elements.netlify.com/grid/examples/preview/ is not loading.

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/carbon#6154]
gird example demo site is not working since couple of days. Please fix it asap.

**Comment by emyarod** [comment]
this was probably due to netlify build issues, but it seems to be up and working now

![image](https://user-images.githubusercontent.com/8265238/83181663-d3893f00-a0ea-11ea-8885-6585707f0b61.png)
