### ISSUE TITLE
DataTable - Ability to sort against multiple columns simultaneously 

### ISSUE THREAD

**Issue by areddon** [carbon-design-system/carbon#6155]
### Summary

Our users would like to be able to apply sorting across multiple columns at the same time and currently the Data Table only supports sorting by a single column at a time.

### Justification

We are building a new interface for our product that currently supports sorting on multiple columns. We can show the returned data in the sort order of the results, but as soon as they apply a sort after rendering, they can only do so on a single column.

### Desired UX and success metrics

- Visual indicators on table headers for sorts with the ability to distinguish between the order in which sorts were applied.

- Ability to apply sorts across multiple columns at once. ( This could be done via clicks/interactions with the table itself, but may require a dialog for multiple column sorting like in Excel)

### "Must have" functionality

- Visual indicators on table headers

### Specific timeline issues / requests

We would be ready to consume it in about 30-60 days from now and potentially earlier if available.

### Available extra resources

We do have IBM designers and developers that may be able to contribute and/or collaborate with the Carbon team. Please do not hesitate to reach out.

**Comment by jeanservaas** [comment]
@vsnichols I think I remember you and tracey showing designs for multiple column sorting but I'm not sure it made it into proposals. Is this something you guys explored or am I misremembering?

**Comment by vsnichols** [comment]
@jeanservaas @andreancardona Our filter panel on CloudPAL applies for filtering on multiple columns.

However the idea of sorting on multiple columns is a little confusing to me. 

You can't sort on two columns at the same level of hierarchy at the same time.

But you could sort on one column and then do a secondary sort on a second column? There is hierarchy involved I think, if you look at how excel and other spreadsheet programs handle this.

This would definitely be very cool but we didn't do any designs around it unfortunately.

**Comment by andreancardona** [comment]
@jeanservaas Hey hey! What do you feel the best next step would be?

**Comment by joshblack** [comment]
Hey there! Going through this issue in our proposal grooming process. Based on the feedback above, we're going to go ahead and close this issue. Feel free to comment if you think this is in error and I'd be happy to re-open!
