### ISSUE TITLE
DatePickerInput used with DatePicker throws two required prop types errors

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#6156]
## Title line template: [Title]: Brief description

If I use a DatePicker with DatePickerInput, I see these required proptypes errors in the logs.  Strangely it appears that the DatePickerInput eventually gets the id and labelText field set, so I think this is during the React.cloneElement code

## What package(s) are you using?

- [] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Here's the error thrown to the log

checkPropTypes.js?5679:19 Warning: Failed prop type: The prop `id` is marked as required in `DatePickerInput`, but its value is `undefined`.
    in DatePickerInput (created by DatePicker)
    in DatePicker (created by Container)
    
checkPropTypes.js?5679:19 Warning: Failed prop type: The prop `labelText` is marked as required in `DatePickerInput`, but its value is `undefined`.
    in DatePickerInput (created by DatePicker)
    in DatePicker (created by Container)

> Is this issue related to a specific component?

DatePickerInput

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.12.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Use DatePickerInput like this, you'll see the error in the console even though the id and labelText field is set on DatePickerInput
```
  <DatePicker id="date-picker" onChange={action('onChangeDate')} datePickerType="single">
              <DatePickerInput
                id="date-picker-input-id"
                className="some-class"
                labelText="Select day"
                pattern="d{1,2}/d{4}"
                placeholder="mm/dd/yyyy"
                invalidText="A valid value is required"
                iconDescription="Icon description"
                onClick={action('onClickDate')}
                onChange={action('onTextChange')}
              />
            </DatePicker>
```

**Comment by emyarod** [comment]
this seems to be [working as intended by React](https://github.com/facebook/react/issues/4494) but will look into potential workarounds
