### ISSUE TITLE
[Button] please implement the active state shown in the PAL with a property

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#6160]
### Summary

See the active state shown here:
https://www.carbondesignsystem.com/components/button/style/#ghost-button.

The carbon-components-react version 10.12.0 doesn't support adding the active state through a property

Please add the custom active class to the button based on a isActive property (or active property)

### Justification

Can be easily worked around with our own custom wrappers or classes, but would be good to have as a prop for consistent implementation

### Desired UX and success metrics

Users would like an indicator that a button is active:

![image](https://user-images.githubusercontent.com/6663002/83172239-e8f76c80-a0dc-11ea-9f0f-402a690984f6.png)

**Comment by emyarod** [comment]
I believe that by design, the active button styles are meant to appear only when the button is activated (just like `:active` styles in user agent stylesheets), but there are workarounds as you mentioned

**Comment by scottdickerson** [comment]
oh I misunderstood, apologies, I was thinking the button supported like a 'toggle' activated state. Lemme withdraw this request, thanks!
