### ISSUE TITLE
OverflowMenu in UI-Shell focus does not show on proper clicked item

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#6167]
## What package(s) are you using
- [ X] `carbon-components`
- [ X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When you use OverflowMenu in UIShell the focus is not showing on the proper item

> Is this issue related to a specific component?

UI Shell and OverflowMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Focus should show on clicked item.

> What browser are you working in?

Safari

> What version of the Carbon Design System are you using?

Carbon: 10.12.0
Carbon React: 7.12.0

## Steps to reproduce the issue

https://codesandbox.io/s/strange-cdn-3xm5q?file=/src/index.js:1399-1411
 1: Click an icon in right
2: click another icon.

Notice that the focus box shows on prior clicked item

![example](https://user-images.githubusercontent.com/8028956/83284857-4ce86680-a1ab-11ea-92d4-1f9f0aed5e69.gif)

**Comment by aledavila** [comment]
Closing as `Overflowmenu` isn't supported in `HeaderGlobalBar `  

Related: https://github.com/carbon-design-system/carbon/issues/5149
