### ISSUE TITLE
Tree shaking problem

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#6172]
Related to #4578
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `@carbon/icons-react`

## Detailed description

I'm using this framework as production, but I felt build time is so slow. The problem I found is about tree shaking. I tested small project using `create-react-app --typescript`.

1) `import { Content } from 'carbon-components-react'`
2) `import { Search16 } from '@carbon/icons-react`

I tested each case, and checked both case don't apply tree shaking at all. Both chunk files included all components/icons. I add `sideEffects: false` to `package.json` of both package, but it doesn't work.

## Questions

1) Is it the problem of CRA even if it is PURE CRA(not customized)?
2) I also tried full path import like [My SO question](https://stackoverflow.com/q/62098045/11789111) **but it cannot infer type.**

In this situation, what is solution?

**Comment by joshblack** [comment]
Hey there @baeharam ! 👋 

I tried to reproduce using the template you specified but it seems like it was tree-shaking as-intended:

**With `@carbon/icons-react`**
![image](https://user-images.githubusercontent.com/3901764/84402673-5d94d580-abca-11ea-9e4a-bc6efe6117bf.png)

**With `carbon-components-react`**
![image](https://user-images.githubusercontent.com/3901764/84402842-9c2a9000-abca-11ea-9daa-fd1714fcc4a9.png)

Could you share some steps to reproduce so we can help figure out what's going wrong with how you're trying to use these libraries? 👀

**Comment by baeharam** [comment]
Thanks for your experiment, it was my mistake. There were no problems for that packages, I used `ListBox` which cannot access publicly. And, I had to use `lib` than `es` to use that component which cannot be tree-shakable. For the future people, if you use component from `lib`, it will be not tree-shakable. I think it could be closed.
