### ISSUE TITLE
TextArea to allow HTML rendering

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#6180]
I was wondering if maybe there can be an improvement to allow html to be rendered in the text area for the value and default value. meaning, if the string contains html it will render it. It is probably a no, but worth asking.

**Comment by emyarod** [comment]
the `TextArea` component uses the native HTML `textarea` which cannot render HTML, but as we briefly discussed on Slack, you can accomplish this with a custom component based on a content editable div. if you are making a feature request, it would be helpful if you could fill out the [issue template ](https://github.com/carbon-design-system/carbon/blob/master/.github/ISSUE_TEMPLATE/feature-request-or-enhancement.md)to provide us with more information around your proposal and your use case

**Comment by TannerS** [comment]
@emyarod I missed that reply, will check now and ok! I will close this for now
