### ISSUE TITLE
[Modal]: Overflow fading does not work with css variables enabled

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6182]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When passing `$emit-custom-properties: true`, the gradient indicating a scrolling modal does not work since it resolves to `linear-gradient(to bottom, rgba(var(--cds-ui-01, #f4f4f4), 0), var(--cds-ui-01, #f4f4f4))` and `rgba(var(--cds-ui-01, #f4f4f4), 0)` isn't parsed correctly by CSS.

> Is this issue related to a specific component?

Modal

> What version of the Carbon Design System are you using?

`carbon-components@10.12.0`
`carbon-components-react@7.12.0`

## Steps to reproduce the issue

1. Add a modal with a lot of content and pass `true` for `props.hasScrollingContent`

## Additional information

CodeSandbox has connection issues for me right now. I'll try again later and add a link.

**Comment by emyarod** [comment]
related #4345, I believe we still need to come to a decision on how to proceed

**Comment by joshblack** [comment]
Hey there @janhassel! 👋 

This is currently a known issue and unfortunately is blocked by us moving to full CSS Custom property support in v11. If you have any suggestions for how to proceed in the interim, we'd love to hear them! Given that this is behind an experimental feature flag, it won't be prioritized on our end until we're closer to v11 (ETA October)

Going to close this out in favor of https://github.com/carbon-design-system/carbon/issues/4426

If you have suggestions for how we could support this in the interim definitely let us know! Would love to help coordinate anything that can help out with this 😄
