### ISSUE TITLE
Needs better support for alternate type/container/icon tokens

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#6183]
### Summary

Carbon has type tokens and introduced container/icon tokens last fall. However, many components are coded in a way where only specific values of those tokens works.

### Justification

This is required for ibm.com sites where it requires larger type/container/icon sizes.

### "Must have" functionality

Reduced hard-coded paddings/heights, etc.

### Specific timeline issues / requests

Hoping to have some improvements in 6 weeks.

**Comment by mattrosno** [comment]
Thanks for opening @asudoh. Can you share your latest exploration of what this could look like? Is this the right link?

https://github.com/carbon-design-system/carbon/compare/master...asudoh:alternate-type-space#diff-cfdf7d6a6baff15d13476bc700c119b9R393

**Comment by asudoh** [comment]
Thank you for asking @mattrosno - The latest code can be found at: https://github.com/carbon-design-system/carbon/compare/master...asudoh:alternate-type-space
