### ISSUE TITLE
DataTable Skeleton, have title and description skeleton as optional prop

### ISSUE THREAD

**Issue by SoSubtle** [carbon-design-system/carbon#6189]
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

Hello. The **latest** DataTableSkeleton includes a skeleton for the datatable title and description. I was wondering if its possible to make the datatable title and description skeleton parts optional. Following the PAL guidelines our datatable component does not have an attached title or description so including the title and desc skeleton looks a bit off. 

Please include a brief summary of what you would like to see changed here. 
It would be nice to have the option to render the datatable skeleton without the title and description.

What we want : https://codesandbox.io/s/suspicious-raman-hhnyx

The latest version : 
<img width="838" alt="Screenshot 2020-05-29 at 17 49 21" src="https://media.github.ibm.com/user/268771/files/df513000-a1d4-11ea-8589-f2a9597af60c">

**Comment by tw15egan** [comment]
Closing as dup of https://github.com/carbon-design-system/carbon/issues/5993, will get a PR up shortly.
