### ISSUE TITLE
[dropdown] change cropped option before scroll 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#6195]
When a dropdown is open, we need to change the crop of an option before scroll to the 6th option instead of the 4th option.

Spec:
![dropdown-usage-7 copy](https://user-images.githubusercontent.com/43969356/83683534-2b242080-a5ab-11ea-8a91-7c4126f50cea.png)

**Comment by mjabbink** [comment]
@laurenmrice Perfect! This will be much better.
