### ISSUE TITLE
Revert `@ibm/plex` peerDependency requirement

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#620]
We introduced `@ibm/plex` in a recent release which caused a lot of our production services to miss out on the Plex styles we introduced in our v8 release. This issue is to revert this added peerDependency in a patch release so that we're no longer breaking these services. This peerDependency should be included in a future major release.

**Comment by monte-hayward** [comment]
hi @joshblack 
would this fix an issue like the following?

```
{
  "status": 1,
  "file": "/path/my-project/node_modules/carbon-components/scss/globals/scss/_css--plex-core.scss",
  "line": 4,
  "column": 1,
  "message": "File to import not found or unreadable: @ibm/plex/scss/mono/italic/index.\nParent style sheet: /path/my-project/node_modules/carbon-components/scss/globals/scss/_css--plex-core.scss",
  "formatted": "Error: File to import not found or unreadable: @ibm/plex/scss/mono/italic/index.\n       Parent style sheet: /path/my-project/node_modules/carbon-components/scss/globals/scss/_css--plex-core.scss\n        on line 4 of node_modules/carbon-components/scss/globals/scss/_css--plex-core.scss\n>> @import '@ibm/plex/scss/mono/italic/index';\n   ^\n"
}
```

**Comment by joshblack** [comment]
Hi @monte-hayward, yes it should revert back the `@ibm/plex` changes which are causing this. Sorry about the issue you ran into!
