### ISSUE TITLE
Entire @carbon/icons-react/es is imported when just a single icon is used

### ISSUE THREAD

**Issue by DicyeDong** [carbon-design-system/carbon#6201]
Related to #4578

## What package(s) are you using?
"@carbon/icons-react": 
   "version": "10.11.0",

- [ √ ] `carbon-components`
- [ √ ] `carbon-components-react`

## Detailed description

I use the icon with below code:
import Close20 from '@carbon/icons-react/es/close/20';

I thought I should get only this icon relate file build into the production package,
but instead I got below after running the react builder analyze
![image](https://user-images.githubusercontent.com/3250313/83864345-34ea8700-a757-11ea-808d-1cbd13e438ab.png)
It makes the builder of app so big...

Any ideas about it?

**Comment by DicyeDong** [comment]
I have resolved this issue by myself, this issue is because the icon is import by different ways, like:
some of icons import with:
import Close20 from '@carbon/icons-react/es/close/20';
meanwhile some of icons import with:
import {Close20} from '@carbon/icons-react';

I changed all icon import with the same way:
**import {Close20} from '@carbon/icons-react';**

then the build which include with carbon icon become like this:
![image](https://user-images.githubusercontent.com/3250313/83988071-c3881f80-a974-11ea-9b84-8dae69b7c563.png)

This is pretty cool for me.

**Comment by tw15egan** [comment]
Glad you were able to fix this! Going to make this as closed but feel free to reopen if you have any other issues.
