### ISSUE TITLE
Title not set on truncated anchor tags in tabs

### ISSUE THREAD

**Issue by daka1510** [carbon-design-system/carbon#6210]
## What package(s) are you using?
- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description
Our test team raised an issue due to missing tooltips in truncated tab titles.
![image](https://user-images.githubusercontent.com/16404496/84016679-e5d26b00-a97d-11ea-8a22-83e7900d7f4d.png)

Without a fix in the Carbon library we need to fix this (as outlined under "Additional information") at several places for a consistent user experience.

I therefore suggest to allow for an optional `tooltip` prop in the  https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tab/Tab.js#L170 component that allows to set a tooltip if needed (or reuse the label prop and set it as title on the anchor tag).

## Additional information
With the existing props, it can be solved like below but requires every consumer to change:

```js
// without tooltip on anchor tag
<Tab label="My label">

// with tooltip on anchor tag
const renderAnchor = (label) => (defaultAnchorProps) => {
	const anchorProps = { ...defaultAnchorProps, title: label };
	return <a {...anchorProps}>{label}</a>;
};
<Tab renderAnchor={renderAnchor("My label")}>
```

**Comment by tw15egan** [comment]
Can you try adding the `title` attribute to the tab? It seems to allow passing the `title` down

```jsx
<Tab label="Tab 1" title="Tab 1">
```

https://codesandbox.io/s/codesandbox-c13gn?file=/src/index.js

**Comment by daka1510** [comment]
Thanks for the quick reply @tw15egan. I missed that the title is passed down via `...other` in the Tab component and thereby allows setting a `title` attribute on the `<li>` element. That works fine and I updated our code. This issue can be closed from my side but I'll leave it open as I saw you raised a related PR.

**Comment by tw15egan** [comment]
I just wanted to ensure your issue was resolved before closing. Thanks for confirming! 👍
