### ISSUE TITLE
Date picker using outdated color token for selected days in range

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#6214]
originally reported in Slack

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

when making a range selection in the date picker, the highlight color for the selection seems incorrect in the dark themes

> Is this issue related to a specific component?

date picker

## Additional information

![image](https://user-images.githubusercontent.com/8265238/84050729-bd457380-a973-11ea-99d0-e554ddf02b59.png)

**Comment by laurenmrice** [comment]
We need to update the following:

Range dates: need to use `highlight` token
Current day: needs to use `link-01` token to be light enough in dark themes
