### ISSUE TITLE
When using latest carbon-icons, ghost button does not render icon background properly

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon#6218]
Hi, we updated to the latest carbon components / icons, and we're having problems with our ghost button icons, the background color seems wrong. Here's a screenshot of what it looks like, i manually added a fill color of "white" on the SVG to contrast what it used to look like. 

see screenshot: 
![image](https://user-images.githubusercontent.com/10033254/84064420-3058e500-a988-11ea-9612-5616f057c082.png)

we're using the latest cloud pal version, which imports `carbon-components-react@7.12.0`

if we stay on 
    "@carbon/icons": "10.8.2",
    "@carbon/icons-react": "10.8.2",

things work fine, but as soon as we go to:

    "@carbon/icons": "10.11.0",
    "@carbon/icons-react": "10.11.0",

then you see the problem in the screenshot. This only seems to happen on the ghost button, the icons themselves seem to render fine.

**Comment by tw15egan** [comment]
Seems to still be an issue on `10.13.0` as well 

<img width="113" alt="Screen Shot 2020-06-09 at 1 34 05 PM" src="https://user-images.githubusercontent.com/11928039/84180699-c8b0a180-aa3c-11ea-85dc-f965d20e9840.png">
