### ISSUE TITLE
<ibm-select> tag is not working in angular reactive forms

### ISSUE THREAD

**Issue by bhmoolam** [carbon-design-system/carbon#6219]
I am using <ibm-select> with Angular reactive forms.
When page is loaded, unless click on the select box, other fields are not loading and getting the following error

![image](https://user-images.githubusercontent.com/66640953/84066438-8c9d2280-a9e3-11ea-849a-fbc5dce8124e.png)
![image](https://user-images.githubusercontent.com/66640953/84066460-9757b780-a9e3-11ea-99ca-130f960a90dd.png)
![image](https://user-images.githubusercontent.com/66640953/84066482-a0488900-a9e3-11ea-9a78-eef209b912fc.png)
Only on click of the select box, other elements are populated. Also select box option value is coming as null. When I tried with html select I am able to get the selected value

<ibm-select
	[theme]="dark"
    formControlName="sectorName">
        <option value="" disabled selected hidden>Select Sector name</option>
        <option *ngFor="let item of items" value="item">{{ item }}</option>
</ibm-select>

**Comment by joshblack** [comment]
Hey there! 👋 

This looks like an issue for `carbon-components-angular`, might help to ask over in: https://github.com/IBM/carbon-components-angular/issues as this project does not contain that package.

Hope this helps! Going to close this for now in preference of moving to the other repo 👀
