### ISSUE TITLE
<ibm-sidenav> with icons are not working

### ISSUE THREAD

**Issue by bhmoolam** [carbon-design-system/carbon#6220]
Hi All, I am trying use ibm-sidenav. But, by default there is a space for icons gets loaded.. I want side navigation without icons.  my code <ibm-sidenav [expanded]="active" [hidden]="true" (click)="onClickNavItem($event)">

Without any icons added, container for icons are getting loaded  by default. This create additional spaces in the left navigation

**Comment by joshblack** [comment]
Hey there! 👋 

This looks like an issue for `carbon-components-angular`, might help to ask over in: https://github.com/IBM/carbon-components-angular/issues as this project does not contain that package.

Hope this helps! Going to close this for now in preference of moving to the other repo 👀
