### ISSUE TITLE
Expose flatpickr plugins as a package

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#6221]
Plugins: https://github.com/carbon-design-system/carbon/tree/master/packages/react/src/components/DatePicker/plugins

We've been using some variation on these plugins in Carbon Angular for a while, and have modified them as needed to sort out issues we've found. It would be ideal if we could share these plugins across the framework implementations.

**Comment by joshblack** [comment]
Good point @cal-smith! cc @lee-chase would this be helpful on the Vue side, as well?

**Comment by lee-chase** [comment]
Not sure, I'd have to spool back in some of the flatpickr pain but as long as they're flatpickr plugins I see no reason they could not be used.
