### ISSUE TITLE
Toggle and ToggleSmall Skeleton broken

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#6222]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The skeleton for ToggleSmall appears to be broken. It looks identical to a ToggleSmall without any props and doesn't show the typical animated skeleton. Additionally it doesn't provide a smaller skeleton for the label like TextInput

https://react.carbondesignsystem.com/?path=/story/togglesmall--skeleton

**Comment by emyarod** [comment]
it doesn't seem like the toggle skeleton has changed much since it was introduced, cc @carbon-design-system/design is there a spec for this skeleton component?
