### ISSUE TITLE
Dropdown in `carbon-components-react@7.13.0` no longer passes ref correctly

### ISSUE THREAD

**Issue by ashharrison90** [carbon-design-system/carbon#6228]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react` @ 7.13.0

## Detailed description

> Describe in detail the issue you're having.

- `Dropdown` used to be a class component
- `7.13.0` changes it to a functional component but doesn't preserve the ability to pass a `ref` - **this is a breaking change**

> Is this issue related to a specific component?

- `Dropdown`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- A `ref` to be able to be passed to `Dropdown`, which is then forwarded to the same location it was previously

> What browser are you working in?

- Chrome 83.0.4103.61

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
cc @dakahn

**Comment by joshblack** [comment]
Hey there @ashharrison90! 👋   Having some trouble re-creating this issue, it seems like for:

> A ref to be able to be passed to Dropdown, which is then forwarded to the same location it was previously

I believe the `ref` was only available because it was a class instance (as you noted). The ref didn't point to any particular node, but instead referred to the class instance. Unfortunately this is a behavior of React that we can't really control, but typically we do define strict `ref` contracts where it should consistently point to the same node in the DOM tree. Passing `ref` to a class component isn't something that we expose as it typically will leak class implementation details that people use to invoke/call methods on the class instance.

**Comment by ashharrison90** [comment]
@joshblack so i'll tell you the use case and you can decide what makes most sense

currently (i.e. before 7.13.0) we pass a ref to `Dropdown`, and then use that ref to scroll to and focus the element in certain situations.

i agree that you can't really control that, but removing it feels like a breaking change. i'm not sure we particularly care where the ref ends up (either on the class instance or pointing to some specific node in the components DOM), so defining a strict ref contract where it always points to the clickable button-style `div` sounds fine 🤷

**Comment by joshblack** [comment]
@ashharrison90 got it, totally makes sense! Could you share the code that you were using to use the ref for things like focus? Just was curious what node or property the team was using so we could see how to add that ref support in for the function component 👍

**Comment by ashharrison90** [comment]
@joshblack sure, it's not particular complicated. we create a ref:

```es6
const inputRef = React.createRef()
```

pass it in to `Dropdown`:

```es6
<Dropdown
  ref={inputRef}
  ...
/>
```

then use that ref to find, scroll to and focus the element:

```es6
const dom = ReactDOM.findDOMNode(inputRef.current)
domNode.scrollIntoView({ behavior: 'smooth', block: 'center' })
domNode.focus()
```

looking at the code, i suspect we don't even need the `ReactDOM.findDOMNode`, as I'm pretty sure you can scroll to/focus the ref directly 🤔 

the resulting behaviour being that it scrolls to and focuses the dom node in the `Dropdown` responsible for opening/closing the dropdown (i.e. i can press spacebar immediately and the `Dropdown` will open).

**Comment by joshblack** [comment]
@ashharrison90 I think something in the above implementation is that the ref will point to the class instance and not a DOM node. `findDOMNode` then will take the class instance and return the outermost DOM node that it renders versus the input which one might be expecting.

Quick example of this: https://codesandbox.io/s/eloquent-lake-in92y?file=/src/App.js

![image](https://user-images.githubusercontent.com/3901764/85900374-5a523a00-b7c5-11ea-8afd-313daf61a00b.png)

**Comment by ashharrison90** [comment]
@joshblack sure, that makes sense.

it doesn't matter for our use case, so by all means forward it to the input.
