### ISSUE TITLE
Date picker disabled elements have incorrect styles

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#6231]
the existing disabled styles on our date picker are not correct. the disabled elements still have some changes on hover interaction, and the color tokens are at least 2 years out of date

found by @laurenmrice in #6217

> <img alt="Screen Shot 2020-06-09 at 11 01 44 AM" width="340" src="https://user-images.githubusercontent.com/43969356/84172049-2515c000-aa41-11ea-82fd-6e18dc9b6ce0.png">

**Comment by laurenmrice** [comment]
Spec:

![Date Picker - White theme](https://user-images.githubusercontent.com/43969356/84194296-6d91a580-aa62-11ea-9dad-267b57a73cb3.png)
