### ISSUE TITLE
IDL/Carbon site Latest releases of icon/pictograms to libraries are showing code names vs. friendly names

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#6237]
Carbon
https://www.carbondesignsystem.com/guidelines/icons/library

IDL
https://www.ibm.com/design/language/iconography/ui-icons/library

Examples:

<img width="963" alt="Screen Shot 2020-06-09 at 4 56 20 PM" src="https://user-images.githubusercontent.com/32881239/84205899-b4d46200-aa73-11ea-9efd-7bab6acb7d09.png">

<img width="220" alt="Screen Shot 2020-06-09 at 4 56 28 PM" src="https://user-images.githubusercontent.com/32881239/84205908-b9991600-aa73-11ea-84e8-398349bc8cc5.png">

<img width="797" alt="Screen Shot 2020-06-09 at 4 56 34 PM" src="https://user-images.githubusercontent.com/32881239/84205923-be5dca00-aa73-11ea-93de-e37cc16ab3bf.png">

Pictogram library:

<img width="983" alt="Screen Shot 2020-06-09 at 5 12 55 PM" src="https://user-images.githubusercontent.com/32881239/84206461-cec27480-aa74-11ea-95e0-e16d9ac3340f.png">

<img width="343" alt="Screen Shot 2020-06-09 at 5 13 12 PM" src="https://user-images.githubusercontent.com/32881239/84206485-d84bdc80-aa74-11ea-8f3e-79f4a952184c.png">

<img width="298" alt="Screen Shot 2020-06-09 at 5 13 17 PM" src="https://user-images.githubusercontent.com/32881239/84206496-df72ea80-aa74-11ea-9220-c781c3c64859.png">

**Comment by joshblack** [comment]
Hey there! 👋  I believe these assets had their friendly names generated for them in the metadata. For example, `heat-map--02`: https://github.com/carbon-design-system/carbon/blob/master/packages/icons/icons.yml#L3702-L3706

In order to fix this, someone will need to PR friendly names to update the generated ones.
