### ISSUE TITLE
What are the differences between CDN vs Sass vs CSS in Carbon?

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#6240]
Hi, I'm trying to decrease build time for sass, and tried 2 approaches.

1) Insert CDN link to `<head>`
2) Compile sass file to css and import it.

However, both cases were different from sass. My original import of sass file is this.
- Sass
```sass
@import 'carbon-components/scss/globals/scss/styles.scss'
```
And I did like below

-  CDN
```html
<link rel="stylesheet" href="https://unpkg.com/carbon-components/css/carbon-components.min.css" />
<link rel="stylesheet" href="https://unpkg.com/carbon-components@10.13.0/css/carbon-components.min.css.map" />
```

- CSS
```bash
node-sass styles.scss result.css
```
```sass
@import '../result.css'
```

What are differences within them?

**Comment by joshblack** [comment]
Hey there @baeharam! 👋 

The CDN CSS will include all of the styles from the package, but you will be unable to use any of the sass functionality offered by the sass package.

The sass package provides developers with a way to use tokens and helpers to build components with the IBM Design Language, for example using things like colors or type, without having to do it themselves.

Hope this helps!

**Comment by baeharam** [comment]
Got it, thanks.
