### ISSUE TITLE
DataTable with Selection: fails to update selections when rows update

### ISSUE THREAD

**Issue by gi** [carbon-design-system/carbon#6241]
## What package(s) are you using?

- [x] `carbon-components` `v10.12.0`
- [x] `carbon-components-react` `v7.12.0`

## Detailed description

> Describe in detail the issue you're having.

When rendering a `DataTable` with a selection column, the rows' selection cannot be updated after the initial render.

This seems to be due to the override of the `isSelected` field from the existing state's value if the row's ID already exists in the table.

https://github.com/carbon-design-system/carbon/blob/942c80dc02be23a8ce65688d09dd619209fd1861/packages/react/src/components/DataTable/tools/normalize.js#L44

> Is this issue related to a specific component?

DataTable with Selection.

> What did you expect to happen? What happened instead? What would you like to see changed?

The `DataTable` should react to the input's data: if the rows' `isSelected` property is updated and the Table is rerendered, the table should not override the `isSelected` with a possibly stale value.

> What browser are you working in?

Google Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

The product is to be released at the end of June 2020.

## Steps to reproduce the issue

https://codesandbox.io/s/nifty-germain-2emx2?file=/src/index.js

**Comment by emyarod** [comment]
unfortunately due to the state manager built into `<DataTable>` it does not rerender when the props have changed. one workaround is to build a table with a custom state manager using the exported components like `<Table>`, `<TableRow>`, `<TableCell>` , etc. rather than relying on the one built into `DataTable`, if that makes sense

**Comment by gi** [comment]
Yeah. 

I had thought about using the `react-table` library for this: https://github.com/tannerlinsley/react-table.

**Comment by gi** [comment]
However, I have to ask:
Why support (mutable) selection if there isn’t an easy, supported way to communicate that selection out of the table’s internal state?

https://github.com/carbon-design-system/carbon/issues/6260

**Comment by kalbert312** [comment]
Hitting this as well. I came up with a hack to get the selection data in the outer context of the DataTable using a ref and calling `getSelectedRows` in a `setTimeout` call but this is a blocking problem for me. I'm trying to align the selection state between two tables (one affects the other).

**Comment by rwibm** [comment]
Is there still no fix planned for this? This bug still affects Carbon v11 and makes the selection feature in data tables somewhat moot when you can't easily access the internal selection state either.

**Comment by tw15egan** [comment]
No fix is in the works, but we would welcome a PR to enhance the DataTable functionality.

**Comment by synthomat** [comment]
My workaround is: leave the `id` property of your data to the DataTable component, use a different, intermediate "id" prop in your rows instead!

* before passing rows to the DataTable, map your original `id` field to another name (e.g. `id_`). Populate `id` with a generated random value
* whenever you change a row: create a new object with a re-generate that `id` field; replace the old row with the new object (with the new id)

This way you can keep using the original component and don't have to worry about a custom state manager.
