### ISSUE TITLE
[pictograms] Some pictograms on website are showing fill and stroke

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#6242]
Some pictograms on the website for Carbon and IDL are rendering incorrectly. I believe certain elements are getting fills and strokes applied which is causing it to render weird.

(Since this could be an elements issue I wrote in this repo, but we can always transfer it to the website repo if we need to.)

Examples (the dots in pictograms are too large and some places are getting really thick weights):
<img width="891" alt="Screen Shot 2020-06-10 at 8 53 34 AM" src="https://user-images.githubusercontent.com/43969356/84276355-e1ca5880-aaf7-11ea-8e6d-7b1c7f318e4b.png">

<img width="300" alt="Screen Shot 2020-06-10 at 8 54 28 AM" src="https://user-images.githubusercontent.com/43969356/84276477-00c8ea80-aaf8-11ea-8b4d-c24665fdb134.png">

<img width="926" alt="Screen Shot 2020-06-10 at 8 54 02 AM" src="https://user-images.githubusercontent.com/43969356/84276417-f0b10b00-aaf7-11ea-8f00-6ab8269c0200.png">

<img width="1229" alt="Screen Shot 2020-06-10 at 8 45 20 AM" src="https://user-images.githubusercontent.com/43969356/84276074-89935680-aaf7-11ea-8537-65c275b69e48.png">

**Comment by joshblack** [comment]
Hey Lauren! 👋  What should they be rendered as? It seems like some of these are the same issue we saw earlier where the shapes are circles, rects, etc that require fill to be set versus stroke which is how they are being styled.

**Comment by laurenmrice** [comment]
The thing about the above is that in the past they did not look like this (on the website or when downloading into illustrator).

When I download a pictogram from the website and open it in illustrator, it also appears wrong in illustrator. The part that looks wrong (the dots) is getting a fill and stroke on it. 
<img width="414" alt="Screen Shot 2020-06-10 at 11 57 02 AM" src="https://user-images.githubusercontent.com/43969356/84296376-8b6a1380-ab11-11ea-9304-f8d790946f35.png">

**Comment by mjabbink** [comment]
It looks like the fills are getting strokes applied. I know Michael Dudley is making all new art for the Pictograms to be both types (expanded and stroked SVGs). Once he does this the problem will be solved I hope. In the meantime what can we do to solve this because it has been fine since the Pictogram library launched Oct 2019.

**Comment by joshblack** [comment]
Should be good to go with the pictogram updates!

**Comment by mjabbink** [comment]
👍
