### ISSUE TITLE
Pictograms' stroke-width is too thin for non-retina displays

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6245]
## Detailed description

Pictograms look all nice and sharp on high-density screens like the Retina screens on Macs but get blurry and deformed on anything not as high-density. This highly affects the aesthetic and overall perceived "quality" of the UI components they're placed in.

---

A few examples (taken on a screen with 117ppi)

![image](https://user-images.githubusercontent.com/28265588/84298994-5204c880-ab50-11ea-8840-6daae57aaca7.png)
![image](https://user-images.githubusercontent.com/28265588/84299026-62b53e80-ab50-11ea-935e-5911eca67967.png)
![image](https://user-images.githubusercontent.com/28265588/84299053-6ba61000-ab50-11ea-8877-41e30de7e264.png)

**Comment by joshblack** [comment]
cc @laurenmrice do you know who would be good to direct this towards on brand?

**Comment by laurenmrice** [comment]
I would say @dudley-ibm would be the best person.

**Comment by dudley-ibm** [comment]
Correct me if I'm wrong, @joshblack, but I think this issue will be corrected once we swap each asset out with the outlined versions of the svgs.

**Comment by joshblack** [comment]
@janhassel I think in terms of stroke width this got adjusted by defaulting to larger sizes of pictograms.

Unfortunately, at smaller sizes, it seems like something that will not be addressed by pictograms or icons given how Plex itself suffers from a similar issue on letters like `e`, `l`, etc.

I think for some assets we could see if they are not landing on the pixel grid, but outside of that, it seems like there won't be a way to address this.

Curious what you think @janhassel

**Comment by janhassel** [comment]
@joshblack I quickly tried out some pictograms with the new minimum size of pictograms (48px) and I'm wondering what the reason behind the fractional stroke widths is.

With a stroke width of 1.08px on a 48px pictogram, the line's width is almost indistinguishable compared to a stroke width of 1px, yet the fractions cause some half-pixel rendering. In this example, the top row of pictograms are 48px (=1.08px stroke width) where the bottom row is scaled to 44.44px (= roughly 1px stroke width).

![image](https://user-images.githubusercontent.com/28265588/106751658-c59c9e00-6629-11eb-982d-b50367b49a63.png)

As you can see, the "Duplicate file" pictogram appearance is greatly improved, the "Folder" pictogram actually is a bit more blurry (my first guess would be that due to the scaling, the horizontal lines are placed in between pixels). The screenshot is taken on a display with 109ppi.

Are there any downsides of designing pictograms on a 48x48 pixel grid with a 1px stroke width? It seems this could solve a lot rendering issues on non-retina screens.

**Comment by joshblack** [comment]
@janhassel definitely a great point, I'll defer to @dudley-ibm who is authoring the pictograms to see what he thinks 👀 

I think the current stroke guidance currently comes from the IDL which specifies the `0.72px` stroke: https://www.ibm.com/design/language/iconography/pictograms/design#strokes

**Comment by dudley-ibm** [comment]
@janhassel the pictograms actually "used" to be 48px, but the recent breaking change is such that all pictograms are 32px now. What did you mean when you said you were trying them out "with the new minimum size of pictograms (48px)" in your above note? I would point this conversation to Mike Abbink, but I cannot seem to tag him here.

**Comment by janhassel** [comment]
@dudley-ibm Sorry, I was referring to the usage guidelines and how they changed from stating 32px as the minimum size to 48px in July last year (https://github.com/carbon-design-system/carbon-website/pull/1438).

**Comment by dudley-ibm** [comment]
Gotcha. I suggest discussing this with Mike Abbink, but again I'm not able to tag him here.

**Comment by tw15egan** [comment]
cc @mjabbink

**Comment by mjabbink** [comment]
@janhassel The pictograms are intended for larger usage. 48px is a minimum but we recommend 64px and the IBM dotcom team will be implementing that size in their patterns for example. Pictograms stroke weight was determined to work well across a wide range of uses spanning across digital and print (web, social, videos, animations, merchandise, environments, events and signage systems). The stroke weight spans tons of weights within digital media alone. 

We increased a bit but 1px basically kills the entire concept along with the flexibility to communicate with the form. The UI icons are more for 48px and below and are much more suited for non-retina displays. Thinking in pixels was not intended for these not would I want it to be.

Concept for these ate to be light, delicate and robust to illustrate many varieties of concepts from simple to more complex. They are closer to functioning as illustrations more than they are icons. The .72pt to 1pt would cause many of pictograms to clunk up and challenge the integrity of the pictogram concept (like the city ones for example).

**Comment by janhassel** [comment]
@mjabbink I wasn't suggesting to change the stroke-width from 0.72px to 1px, but referring to the calculated stroke-width of pictograms at a 48px size, which is currently 1.08px (0.72px at 32px * 1.5 = 1.08px at 48px).

If pictograms would be designed with a 1px stroke-width on a 48x48px grid, the rendering on non-high-pixel-density displays could be vastly improved. Here is an example of the duplicate file pictogram at 48px, rendered at 100% on a display with 109ppi:
*(left: original (1.08px stroke-width), middle: 1px stroke-width, right: 1px stroke-width and aligned on pixel grid)*
![image](https://user-images.githubusercontent.com/28265588/107501002-229ed380-6b97-11eb-892f-750856729f71.png)

The middle example already looks a bit sharper than the original one due to the lack of bleeding into the next pixels. (top: original (1.08px), bottom: 1px)
![image](https://user-images.githubusercontent.com/28265588/107503313-16684580-6b9a-11eb-9ad1-7d398c84c64c.png)

The difference is in weight is quite marginal. (black is 1px stroke-width; blue is the currently additional 0.08px width)
![image](https://user-images.githubusercontent.com/28265588/107502457-f6845200-6b98-11eb-8d78-8a3ffd6ca280.png)

Let me know what you think!

**Comment by mjabbink** [comment]
I see what you saying. I misunderstood. I think your suggestion is a good one. **I wonder how it would effect the 64px size** recommendation? It would also likely improve. Hmm. Now the question is how to achieve without @dudley-ibm exploding into thousands of pieces. We just updated all the pictograms to be a different stroke weight and output.

@janhassel so what we we need to change the 32px source too? From .72pt to .XXpt

**Comment by janhassel** [comment]
@mjabbink Let me carefully ask the following while hoping to not making @dudley-ibm explore already. 😄

Is there are reason to design the pictograms on a 32x32px original size since the guidance changed and states 48px as the minimum size? 1px stroke width on 48px would result in a stroke width of ⅔px on 32px.
Using a 48x48px grid to design the original assets would enable one to place all lines on the pixel grid and rendering the pictograms at full sharpness for that size. However, for any size that is not a whole number multiplication of 48px, pixels will not align on the grid.

Here is a comparison between the original pictogram (top) and the modified one with 1px stroke and aligned on grid (bottom) for the sizes: 48px, 64px, 80px, 96px, 112px, 128px
![image](https://user-images.githubusercontent.com/28265588/107523562-26d9e980-6bb5-11eb-9a94-04cb90599198.png)

The modification seems to improve 48px, 80px, 96px and 128px, while 64px and 112px look better with the original asset imo.
There will be no solution that renders all pictograms perfectly on all sizes other than manually designing each pictogram for each size (which is completely unfeasible) or limiting the recommended sizes a pictogram is displayed at (with 48px as a base this would be 48px, 96px, 144px, ...) which will probably make a lot of teams unhappy .

In the end it probably comes down to which sizes should be prioritized due to their usage in applications.

**Comment by dudley-ibm** [comment]
Don't worry, fellas. I won't explode. 
@janhassel your example above uses a pictogram (Duplicate file) that reflects about 70% of current pictograms in the master (strokes only). Please excuse this if it's a silly question, but does any of this discussion affect the remaining percentage of pictograms in the master that are currently a combination of strokes and outlined shapes? 
<img width="1170" alt="Screen Shot 2021-02-10 at 10 04 02 AM" src="https://user-images.githubusercontent.com/54119397/107529872-55da6600-6b89-11eb-96a8-e517dfb317b3.png">
<img width="1170" alt="Screen Shot 2021-02-10 at 10 03 59 AM" src="https://user-images.githubusercontent.com/54119397/107529894-5a068380-6b89-11eb-9404-ce79522f9ad7.png">

**Comment by mjabbink** [comment]
@dudley-ibm Yes it would. If we do what @janhassel is suggesting it would require all the outlined bit to be renown. The live stoke elements would be an easy change. 

I’m not sure it makes a difference to change the original source file from 32x32 to 48x48 if we get eh stoke size right at 32x32 so if scaled or used at 48x48 the stroke would equal 1px. If we have to change the source artwork I think the project becomes out of scope.

**Comment by mjabbink** [comment]
@dudley-ibm The dots/circular outlines would not have to change though. Minor detail but would save a bunch of time. Only outlines based on stroke weight would have to be adjusted (mainly letters and some diagonal stroked lines we flattened the terminals on — e.g. bottom of the A)

**Comment by janhassel** [comment]
@mjabbink @dudley-ibm I agree that the filled shapes like circles mostly likely don't need to change.

Regarding the original artwork size: To achieve the perfect sharpness on 48px, the pictograms would need to be designed on a 48x48 pixel grid and the lines would need to align to that grid. If an artwork is created on a 32x32 pixel grid, it will result in placing the lines in between pixels when rendered at 48px, making them render blurry.

Example: to achieve the pixel grid alignment on 48px (top), the lines would need to placed at very specific values in between pixels on the source 32px artwork (bottom).

![image](https://user-images.githubusercontent.com/28265588/107641154-87c7f700-6c73-11eb-83f3-7673edf64610.png)
![image](https://user-images.githubusercontent.com/28265588/107641184-90b8c880-6c73-11eb-81b0-ff94f1ae7879.png)

---

There are two stages to an improvement in rendering though:
1. Changing the stroke-width to be 1px at 48px (⅔px on 32px)
2. Aligning the pictogram's lines and shapes on a 48x48 pixel grid


The first stage would get rid of the slight glow:
![image](https://user-images.githubusercontent.com/28265588/107503313-16684580-6b9a-11eb-9ad1-7d398c84c64c.png)

The second one would render the pictograms perfectly sharp at 48px.

Here is a scaled version of how each stage would render:
(left: current implementation, middle: stage 1, right: stage 2)
![stages](https://user-images.githubusercontent.com/28265588/107641872-716e6b00-6c74-11eb-9a0b-9906b9a1cb0c.png)

**Comment by mjabbink** [comment]
Thanks @janhassel This would require a complete redraw of over 1000 pictograms. I’m more in favor of adjusting the source stoke weight at 32 to achieve a better result at 48px

**Comment by mjabbink** [comment]
so 2/3px at 32. We need to translate to pt stroke weight.

**Comment by janhassel** [comment]
@mjabbink Sounds reasonable!

Maybe the redraw could also be a longer, staggered process. So updating some pictograms already to 48x48 for their source while others remain at 32x32 and pushing them over time.

Not sure if that could cause issues though for 
a) the designers working on differently sized source files
b) the pictogram generator scripts (@joshblack you'd probably have a better understanding on that than me)

Some pictograms would also probably be more work to adjust for 48x48 source files than others. With the "Duplicate file" used in the examples above, the change was rather minor (narrowing the boxes by 0.5px). Though doing this for over 1000 assets is still a tremendous amount of work – hence the idea about staggering it.

(blue: original pictogram, dark overlay: updated pictogram)

![image](https://user-images.githubusercontent.com/28265588/107668216-b86a5980-6c90-11eb-98b5-fa98ab49fcb1.png)

**Comment by mjabbink** [comment]
It would also require us to change the guidance. Currently it’s not pixel based but rather vector stroke driven. The stroke line snaps to the grid line and sits directly on it where as the UI icons are pixels based thinking and one essentially fills the boxes/pixels with black. Two different logics. It”s also why we’re recommending designers to use them larger like 64px. If used small they become less distinguishable from UI icons and less effective. So pushing them to be used larger helps create the distinction between them. Most cases I see are pictograms being misused in product. Website a bit better but also many cases of too small. Me saying this makes me wonder if we should change the guidance to 64px minimum size.

**Comment by janhassel** [comment]
> Me saying this makes me wonder if we should change the guidance to 64px minimum size.

I think this would make a lot of sense actually and further differentiates the intended usage of icons vs. pictograms by skipping the 48px step altogether.

**Comment by mjabbink** [comment]
Agreed

**Comment by janhassel** [comment]
@mjabbink @joshblack What would be the next steps for this? Is it just updating the guidance on the website or are there any other actions needed?

**Comment by mjabbink** [comment]
@janhassel Based on this image above https://github.com/carbon-design-system/carbon/issues/6245#issuecomment-776741104 I would recommend we do one of two things. 
a) Nothing since at 48 the fuzziness is livable for many pictograms and use cases
b) We adjust the source file stroke weight so that used at 48 it 1px to align better to pixels.

option b) will require @dudley-ibm to adjust the stroke weight over 1000 pictograms and manually adjust many expanded strokes that have had some adjustment. A lot of work and just after many weeks and hours of him recently changed the same elements to the current state. Basically duplicating the work effort immediately after completion of the same exact thing but different stroke weight spec.

Given other priorities and limited resources I cannot place this in any upcoming sprint so option b) will be placed in the back log.

In the meantime we can replace guidance to recommendation of 64px as minimum size. That will make some use cases we’ve seen break the rules and of course does not solve the fuzziness. I’m not sure that is the answer either. I’m leaning on living with fuzzy pictograms at 48px until we can execute option b).

**Comment by mjabbink** [comment]
@dudley-ibm Can you give me an estimate of your time to refactor all the pictograms with new stroke weight? I think the weight needs to still be specified at 32px so that at 48px it equals 1pt/1px.  I guess make a pictogram 48px and 1pc stroke then reduce to 32x32 again and see what the pt size is. Once you know this scope we can plan accordingly.

**Comment by dudley-ibm** [comment]
Yes, I'll provide an estimate @mjabbink @janhassel

**Comment by dudley-ibm** [comment]
Quick question for either @janhassel or @mjabbink: Based on the [above comment](https://github.com/carbon-design-system/carbon/issues/6245#issuecomment-777455703), are we requiring that the strokes of all pictograms when enlarged to the 48px grid size should fall between the grid lines in addition to having a 1px stroke weight?

**Comment by mjabbink** [comment]
Oh, that is. good question. If just adjusting the stroke weight does not improve the issue then we will not make any adjustments. We cannot do any redrawing.

**Comment by dudley-ibm** [comment]
The new point size would have to be .6667 at the current 32px grid size in order to achieve a 1px stroke weight when enlarged to the 48px (x1.5) grid size. 

Please correct me if I'm wrong, but the issue I'm finding is that any vertical and/or horizontal strokes that currently align on an _odd_ numbered grid line (away from the edge) at the 32px size resolve properly when enlarged (x1.5), but those that currently align on an _even_ numbered grid line (away from the edge) do not. 

It seems that redrawing will be necessary for the majority of the pictograms in order for everything to resolve between the grid lines.  

<img width="1631" alt="Screen Shot 2021-02-19 at 3 04 26 PM" src="https://user-images.githubusercontent.com/54119397/108555772-eddffa00-72c3-11eb-843d-70038a1f0b85.png">

**Comment by mjabbink** [comment]
I’m not saying it has to be between the lines. That means redraw. I’m suggesting we ONLY change weight so that the na pictogram is scaled to 48x48px the stroke is 1 pixel.

If that still renders fuzzy then we have no solution. Redraw is not an option.

**Comment by mjabbink** [comment]
The test that Jan did seems to have just changed the stroke weight above and it improves rendering. Correct me if I’m wrong @janhassel

**Comment by dudley-ibm** [comment]
Totally agree @mjabbink that redrawing every pictogram is not a feasible option.

I'm just trying to clarify with @janhassel that if all we do is achieve a 1pt line weight at the 48px size pictogram (by switching to .6667pt at 32px size pictogram) but that line still ends up directly on the grid line at the 48px size (essentially splitting the pixel grid), wouldn't that still render fuzzy?

[above](https://github.com/carbon-design-system/carbon/issues/6245#issuecomment-777455703): "to achieve the pixel grid alignment on 48px (top), the lines would need to placed at very specific values in between pixels on the source 32px artwork (bottom)"

**Comment by dudley-ibm** [comment]
<img width="1633" alt="Screen Shot 2021-02-19 at 4 59 03 PM" src="https://user-images.githubusercontent.com/54119397/108566153-f2acaa00-72d3-11eb-943c-b241928c2a13.png">
<img width="1633" alt="Screen Shot 2021-02-19 at 4 59 24 PM" src="https://user-images.githubusercontent.com/54119397/108566172-f7715e00-72d3-11eb-8185-ed3c4d2b59af.png">

**Comment by mjabbink** [comment]
If that’s the case then we must leave them as they are.

**Comment by janhassel** [comment]
@mjabbink @dudley-ibm I wouldn't bother updating any of the assets if the minimum size of the pictograms would be set to 64px, which I thought is what we were going for when you said
> Me saying this makes me wonder if we should change the guidance to 64px minimum size.

@mjabbink
