### ISSUE TITLE
Drop down options dont stick 

### ISSUE THREAD

**Issue by shaziajk** [carbon-design-system/carbon#6253]
Implemented drop down in a side bar on a UI and when you scroll the drop down options seem to follow the scroll. Investigated and looks to be more of a carbon specific bug than the way we implemented.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by shaziajk** [comment]
Sorry, just checked our codes over riding the component so it’s probably not an issue with the component
