### ISSUE TITLE
Infinite re-render with MultiSelect 10.13/7.13

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon#6259]
## What package(s) are you using?

- [x] `carbon-components` 10.13
- [x] `carbon-components-react` 7.13

## Detailed description

With latest carbon-components, MultiSelect within Formik result in an infinite re-render. This does not happen with v10.12/7.12.

## Steps to reproduce the issue

- https://codesandbox.io/s/silent-breeze-oxhne?file=/src/index.js
- Replace `"` in the text field with a different character
- Infinite re-render (you can open the browser inspector to see the never-ending `console.log`s)

**Comment by joshblack** [comment]
cc @dakahn

**Comment by joshblack** [comment]
@jhpedemonte I _think_ I tracked it down, seems like we had an effect that was being called when `onChange` was called. Have a PR up and will try and make sure to come up with a solid repro of the codesandbox for folks to try out before merging/shipping.

Sorry about the breakage here! 🤦‍♂️
