### ISSUE TITLE
TableToolbarSearch error ( Closed searchbar even though it has a value | Not Fixed with Persistent )

### ISSUE THREAD

**Issue by SoSubtle** [carbon-design-system/carbon#6264]
## Title line template: [SearchBar is closed even though it has a value in it]: Brief description
This is the scenario. If i search using the search bar and click an item in the results ( which brings me to a new page ) If i return to the page with the search bar ( by pressing the back button in browser or a breadcrumb etc ) the searchbar is closed even though it still has the value in it. I then see the close 'X'  icon crossed with the search icon. The results of the datatable are still correctly affected by the search value in the just the search bar is closed. It appears that the active css class is missing which closes the search bar. 

## What package(s) are you using?
- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description
As mentioned above the search bar is closed even though it has a value in it. It looks like this :
<img width="1375" alt="Screenshot 2020-06-12 at 16 28 43" src="https://user-images.githubusercontent.com/33182377/84527779-725e8f80-acd6-11ea-9fc9-6dc6d6e69631.png">
After inspecting the search bar it appears to simply be missing the active css class. "bx-toolbar-search-container-active". If i add this in then the search bar opens up and correctly displays the value it holds. 

> Is this issue related to a specific component?
TableToolbarSearch

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the search bar to stay open after navigating back the to the datatable page. 

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components-react": "7.11.3",
"carbon-components": "10.11.2",
 

## Steps to reproduce the issue

1. Step one : Enter a search term in the search bar
2. Step two : Click a result ( which brings you to a new page )
3. Step three : Click the back button 
4. Step four : Error is shown

In the video below i search edward, click a user, then click the back button.
![usersTable](https://user-images.githubusercontent.com/33182377/84536431-bb6a1000-ace5-11ea-8fdb-02b50ba0f698.gif)

##Code

`<TableToolbarContent>
          {this.props.search &&
            <TableToolbarSearch
              id={this.props.search.id}
              labelText={this.props.search.label}
              onChange={this.props.search.onChange}
              value={this.props.searchValue}
              placeHolderText={this.props.search.placeholder} />
            }`

**Comment by tay1orjones** [comment]
If you're unable to set initial state for a piece of the DataTable, you'll need to implement your own custom data table state handler and set the initial value for the TableToolbarSearch after you re-render the table. [Here's a codesandbox example](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v10/packages/react/examples/custom-data-table-state-manager) showing generally how to do this - you'll probably need some additional logic not applied in that codesandbox template for the TableToolbarSearch
