### ISSUE TITLE
[OverflowMenu] and [Button] have some style differences

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#6269]
Here's a picture of a iconOnly ghost button, and Overflow Menu button right next to each other
![image](https://user-images.githubusercontent.com/6663002/84550891-7b992d80-acd1-11ea-8f0e-61df7687d917.png)

They have two different focus states with different borders (I've temporarily focused on both to show the issue)

![image](https://user-images.githubusercontent.com/6663002/84550917-9370b180-acd1-11ea-8e5d-6beb207e2e83.png)

![image](https://user-images.githubusercontent.com/6663002/84550933-a08da080-acd1-11ea-951a-404e3e4027f2.png)

Can we unify the focus state across the two types of buttons?

In addition, the default size of the OverflowMenu doesn't match the IconOnly Button size, and is pretty small for a touch target (2 rem). Is it possible to match them?

**Comment by joshblack** [comment]
Hey there @scottdickerson! 👋  Would you mind sharing a codesandbox with the changes that you shared? I would love to dive in and see what's going on.

For the touch target size, definitely agreed. Let me bring this up to see how we can change it to match the 44x44px minimum that Apple's HIG mentions.

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity, feel free to comment and I can re-open!
