### ISSUE TITLE
Component level theming

### ISSUE THREAD

**Issue by cwqt** [carbon-design-system/carbon#6271]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary
Looked in all the issues for this but found no actual solution - is there a way to set component level themes? For example having the global theme be white, but ibm-tabs in a component use the g90 theme.

e.g. set global theme in styles.scss

```
@import '@carbon/themes/scss/themes';
@include carbon--theme();

@import 'carbon-components/scss/globals/scss/styles.scss';
```

then in `/components/something/something.component.scss`

```
@import '@carbon/themes/scss/themes';
@include carbon--theme($carbon--theme--g90) {
    ibm-tabs {
        // ???
    }    
}
```

Thanks.

**Comment by joshblack** [comment]
Hey there @athencxss! 👋 

Currently, there is no stable way to support component-level theming. We do have some experiments roped off behind feature flags that depend on CSS Custom Properties for this use-case, but unfortunately, this work won't be stable until our next major release later on this year.
