### ISSUE TITLE
Is it possible to change the icon of OverflowMenue?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6272]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I want to change the icon of the OverflowMenue, is it possible?
Searched foe such property Knobs but didn't find such one.

**Comment by joshblack** [comment]
Hey there @zbeedatm! 👋  You should be able to use a custom icon with the `renderIcon` prop. For example:

```js
import { Bee32 } from '@carbon/icons-react';
import { OverflowMenu } from 'carbon-components-react';

function MyComponent() {
  return <OverflowMenu renderIcon={Bee32}>...</OverflowMenu>
}
```

Hope this helps!

**Comment by zbeedatm** [comment]
Thanks.
but why the size is smashed when using render rather than using the icon as is.
In this example I used Menu24 and u can see the difference with size when I used it as a plain icon, and when I used it inside a renderIcon:

![image](https://user-images.githubusercontent.com/26740851/86731311-0f8fb800-c038-11ea-9073-4fdac17c1e43.png)
