### ISSUE TITLE
`yarn storybook` fails with `Error: Can't resolve 'carbon-components'`

### ISSUE THREAD

**Issue by lpender** [carbon-design-system/carbon#6283]
Hi 👋 

Following instructions here:

https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#5-build-and-start-the-development-server

When I run `yarn storybook` I get the issue:

```
ERROR in ./src/internal/FloatingMenu.js
Module not found: Error: Can't resolve 'carbon-components' in '.../carbon/packages/react/src/internal'
```

And the same for many other files inside `src/internal`.

I've run `yarn  install --offline` both in the base directory and in `packages/react` (although the latter is not specified in the docs).

When I run `yarn install --offline` in `packages/react` I see (among other things)

```
$ yarn build
yarn run v1.22.4
$ yarn clean && node scripts/build.js && rollup -c
$ rimraf es lib umd storybook-static build react-docgen.json

./src/index.js → umd/carbon-components-react.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@carbon/icons-react (imported by src/components/Accordion/Accordion.Skeleton.js, [many other files])
carbon-components (imported by src/internal/wrapFocus.js, [many other files])
```

Thanks!

**Comment by joshblack** [comment]
Hey there @lpender! 👋

You're going to want to run those command at the root level of the project, versus inside of the package itself. What this might look like is:

```bash
# At root of project
yarn install --offline
yarn build

cd packages/react
yarn storybook
```

Hope this helps!

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity, feel free to comment and I can re-open and keep helping out!

**Comment by AndrisJefimovs** [comment]
Hello everyone! If I run the `yarn install --offline` command, I get the error `Unknown Syntax Error: Unsupported option name ("--offline").`. I followed the [instructions for contribution](https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#5-build-and-start-the-development-server) but it didn't work out :(
