### ISSUE TITLE
Modal overflow

### ISSUE THREAD

**Issue by gyopak** [carbon-design-system/carbon#6288]
## Modal overflow

Seems that Modal component has an overflow which trims overflowing components inside (eg. dropdown, tooltip)

## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Steps to reproduce the issue

1. Create a modal
2. Place an overflowing component (eg. dropdown) inside

[CodeSandbox example](https://codesandbox.io/s/busy-shannon-fl6rf?file=/src/index.js)

## Additional information

opened (trimmed) dropbox inside the modal:
<img width="658" alt="Screenshot 2020-06-16 at 10 24 17" src="https://user-images.githubusercontent.com/25726935/84751106-77645d00-afbc-11ea-8dca-9c9d147a2b89.png">

expected result:
<img width="662" alt="Screenshot 2020-06-16 at 10 25 01" src="https://user-images.githubusercontent.com/25726935/84751616-0d988300-afbd-11ea-80b0-e260164c21b7.png">

**Comment by yrue** [comment]
I have similar issue, may I know the schedule of this fix?

**Comment by gyopak** [comment]
@yrue in the meantime you can manually overwrite these overflows. Check #6289 or #6290

**Comment by yrue** [comment]
Thanks @gyopak , but the fixes not work on my case.
I changed the `overflow: visible` to `bx--modal-container` and `overflow-y: visible` to `bx--modal-content` but still not work as below
![image](https://user-images.githubusercontent.com/5738032/91259003-32b92700-e7a0-11ea-91cc-25d9dcca815c.png)

Would it possible to add a props like `menuPortalTarget` of react-select ([ref](https://react-select.com/advanced#portaling))to attach the menu to specific element?

**Comment by ConradSchmidt** [comment]
Hi @gyopak,
I'm working on IBM Watson Knowledge Catalog and we are facing the same issue of dropdowns are truncated by the modal. The solution you provide (https://github.com/carbon-design-system/carbon/issues/6288#issuecomment-679847181) is working for small modals, where the actual content is not bigger than the modal. This is not always the case (on small screens or huge modals) as you can see in this example (I used your PRs and just duplicated the paragraphs):
![image](https://user-images.githubusercontent.com/3808948/93593073-aa4f3000-f9b3-11ea-8047-5faea504d936.png)
Here is the modal working for small content:
![image](https://user-images.githubusercontent.com/3808948/93593571-aa036480-f9b4-11ea-86df-4a88c1c93e52.png)

A smart workaround our DEV team did is adding a margin-bottom to the modal content to show 3 dropdown entries.
![image](https://user-images.githubusercontent.com/3808948/93593955-488fc580-f9b5-11ea-9e41-c0ceb5c8f4ec.png)


A solution to this would be, as @yrue already addressed, is to provide a property on dropdowns/overflow menu to attach the menu list to a different element (outside modal content) so it can't be truncated by the modal. I know this can be an accessibility issue, but this can be solved by keeping the normal menu and just disable/hide it.
I used this solution a lot within the [primeNg framework](https://www.primefaces.org/primeng/showcase/#/dropdown) - they provide a property called "appendTo" - maybe you can get some inspiration from their [solution](https://github.com/primefaces/primeng/blob/5e0e4cc2985172a83f43bad1b33ed12aa39d02a2/src/app/components/dropdown/dropdown.ts#L620).

**Comment by Yohanna** [comment]
I'm having the exact same issue with Dropdowns, but with `ComposedModal`.

Here's a repro of the problem: https://codesandbox.io/s/carbon-modal-dropdown-bug-ctbgc

See _gif_ below:

![Dropdown in Modal](https://user-images.githubusercontent.com/6926228/100389169-9dc20600-2ffa-11eb-8024-4bbdeb1718f2.gif)

**Comment by mateBe95** [comment]
@kevinsperrine  when it will be fixed?

**Comment by kevinsperrine** [comment]
@mateBe95 I'm not on the Carbon team, so I don't know. There are numerous outstanding issues related to this, but no prognosis or timeline yet. See:

https://github.com/carbon-design-system/carbon/issues/7565#issuecomment-786921600

**Comment by OmranAbazid** [comment]
I have a workaround for this for the composed modal react component that i use until the carbon team address this.

I basically have a classname (`overflowVisible`) that I enable when my modal has a dropdown or something the needs to overflow. I then apply the following styles:

```
.Modal.overflowVisible {
    overflow-y: auto;

    .cds--modal-container,
    .cds--modal-content {
      overflow: visible;
    }

    .cds--modal-container {
      max-height: max-content;
      height: max-content;
      margin: auto;
    }
  }
```

Beware that this workaround will make prevent scrolling inside the modal content. If the modal height is too big, the outer shell of the modal will become scrollable.

**Comment by marcellobarile** [comment]
@OmranAbazid thanks for the workaround; too bad that this bug has been here since 2020.

**Comment by tay1orjones** [comment]
Hey just wanted to mention this is part of a systemic issue with popovers and floating elements that we hope to fully address with https://github.com/carbon-design-system/carbon/issues/14139. I know it doesn't fix the issue for you now, but we hope to have a solid solution for this soon. Thanks for your patience and +1 for that workaround!
