### ISSUE TITLE
Having tags in Modal titles

### ISSUE THREAD

**Issue by diana-sun** [carbon-design-system/carbon#629]
## Detailed description

Feature request

> Is this issue related to a specific component? 
Modals

> What did you expect to happen? What happened instead? What would you like to see changed?
We wrote in a bandaid for allowing tags to be next to the modal titles, but was wondering if you guys could allow for this to happen? Proposal would be to update the Modal component to allow the modalHeading property to be either a string or a node.

> What browser are you working in? 
Chrome

> What version of the Carbon Design System are you using? 
v8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Containers. We put in a hack for it for now but it is for THINK.

## Additional information
![image 2](https://user-images.githubusercontent.com/10226935/36815332-06ee5050-1ca0-11e8-9a9a-0a5900127329.png)
* This is the context. We want to put in the modal what type of helm chart the user is looking at.

**Comment by asudoh** [comment]
@diana-sun Thank you for taking your time to enter this issue. One question - Is this issue against our React variant ([`carbon-coponents-react`](https://github.com/carbon-design-system/carbon-components-react)), or is this more of design question?

**Comment by bsonefeld** [comment]
I'm okay with this on the design side. @diana-sun which library are your developers using, React or Vanilla? Seems like a bug that we could tackle to get it taken care of before your THINK deadline.

**Comment by diana-sun** [comment]
Thanks @asudoh and @bsonefeld ! We're using React.
