### ISSUE TITLE
TextArea not calling onChange when erasing entire defaultValue text at once

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#6295]
## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

TextArea onChange not being called when erasing content populated with defaultValue.

> Is this issue related to a specific component?

TextArea

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I have a TextArea that is populated by it's defaultValue prop. If I go and select the entire textarea text (which was populated from the defaultValue), and erase it, it doesn't trigger the onChange, but if I remove a single char, add a space, or even select some selection of the text (but not the entire text) it does trigger onChange. I would assume selecting the entire text and erasing it would trigger onChange. 

> What browser are you working in?

 Firefox, Chrome

**Comment by tw15egan** [comment]
Do you have a link to a reproducible example? Quickly testing in our local environment and it seems to be firing the `onChange` event when I select the `defaultValue` and hit `esc`

![textarea](https://user-images.githubusercontent.com/11928039/84808032-f5286880-afbc-11ea-8dde-7b54d2a574b2.gif)

**Comment by TannerS** [comment]
@tw15egan Hey, I do not, its in produciton code that uses redux and hooks, they could be a contributing factor but I honestly have  no idea. I guess I can keep looking into it

**Comment by TannerS** [comment]
Looks like it may only be local, I can't see any other reason after doing a demo code with carbon and could'nt re-create. Will close this.
