### ISSUE TITLE
React components

### ISSUE THREAD

**Issue by timrbula** [carbon-design-system/carbon#63]
I apologize if this is not the correct place to ask about features, but I did not see another place on the carbon site to do so.

Are there plans to package up the components as React components or to provide any documentation for integrating these components with a React application? I really like the component library and would like to us in a React-based project. Thanks!

**Comment by chrisdhanaraj** [comment]
Hey @trb727! We have a React library completed, but it's still going through some legal processes to let us publish it on GitHub. Once it's through, I'll ping you directly to let you know. Thanks!

**Comment by timrbula** [comment]
Thanks @chrisdhanaraj! Sorry for the duplicate question, but thanks for the cordial reply! I will eagerly await legal approval.
