### ISSUE TITLE
DataTable with Pagination component does not wrap long words

### ISSUE THREAD

**Issue by feliperyba** [carbon-design-system/carbon#630]
## Detailed description
Currently working with DataTables, I noticed that the nowrap /wrap functions was not being applied into the columns.

Tried different types of approach using white-space and word-wrap and no results into the table.

This happens in any browser. Also, I tried the wrap  into different components and we can see the same behavior.

I was able to edit a code pen and made it work with the simple DataTable, but  this does not work in the DataTable with Pagination component.

## Additional information

![wrap-problem-datatable](https://user-images.githubusercontent.com/7002583/36899643-d357293c-1dfe-11e8-9512-648b72d76011.png)
![image](https://user-images.githubusercontent.com/7002583/36899651-d94ef7b6-1dfe-11e8-9863-7c1032f307e1.png)

**Comment by feliperyba** [comment]
it's important to say that in the second image I was also using the word-wrap : break-all;

But this only works with the min and max width set

**Comment by marijohannessen** [comment]
@bsonefeld do we have any guidelines around when the text should wrap in a table?

**Comment by bsonefeld** [comment]
@aagonzales I'm not sure if we had thought of a truncation patterns for table columns. Do we use the `...` for a specific character count?

**Comment by aagonzales** [comment]
The column headers should wrap but the content in the table should respond like the following:
- All columns should shrink to the smallest possible size without causing content to over flow to the next line. Once all columns are as small a width as possible then the tables triggers horizontal scroll and the user must scroll left and right to view content.
- This keeps the rows even heights which is important for scan-ability
- This is how the design is intended to work.
- Content should not truncate unless its non-important text then it can `...` 
   - If column content is regularly very long then consider putting that information in an expandable table instead.

**Comment by tay-aitken** [comment]
@carbon-design-system/ui this needs to be implemented now that guidelines have been created.

**Comment by joshblack** [comment]
Will bring it up and try and get it prioritized accordingly 👍

**Comment by dkaushik95** [comment]
I think if we add a scrolling behavior as a default it will solve this problem. If the string is small enough to overflow, it will behave normally, otherwise, it will start the scrolling behavior.
