### ISSUE TITLE
DataTable select all checkbox has wrong checked event value in some cases

### ISSUE THREAD

**Issue by veloware** [carbon-design-system/carbon#6302]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.  

When the DataTable has at least one row selected, but not all, i.e. the 'Select All' checkbox is shown as a dash '-', when you click on the 'Select All' checkbox to remove all selections it correctly removes all selection and correctly displays the Select All checkbox as unchecked, however the `e.target.checked` value in the onSelect callback is incorrectly set to true, it should be false
> Is this issue related to a specific component?  

Yes, DataTable - TableSelectAll component
> What did you expect to happen? What happened instead? What would you like to
> see changed?  

the onSelect event should have the e.target.checked value set to false when the checkbox is being cleared / unchecked

> What browser are you working in?  

Chrome
> What version of the Carbon Design System are you using?  

carbon-components@^10.13.0
carbon-components-react@^7.13.0
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?  

Spectrum discover

## Steps to reproduce the issue

1. Setup custom onSelect prop callback on TableSelectAll component
2. Select an item in the table
3. Uncheck the Select All checkbox (changing it from a dash '-', to unchecked)
4. Debug the onSelect callback, notice e.target.checked is true, it should be false

Codesandbox example - see console for logging of e.target.checked
https://codesandbox.io/s/affectionate-flower-fukbb?file=/index.js

**Comment by joshblack** [comment]
Hey there @veloware! 👋 

What you might be running into is if you're using `getSelectionProps` and `onSelect` then the component will not be updated. I believe you will need to use `onClick` with `TableSelectAll`, specifically like:

```jsx
<TableSelectAll
  ...getSelectionProps({
    onClick: event => { 
      console.log(event.target.checked);
    },
  })
/>
```

Hope this helps!

**Comment by veloware** [comment]
I am using `getSelectionProps()`, but I am also calling the `onSelect` function from `getSelectionProps()`

e.g.

`<TableSelectAll {...getSelectionProps()} onSelect={(e) => handleSelectAll(getSelectionProps().onSelect, e)}/>`

then - 

```
 const handleSelectAll = (onSelect, e) => {
        onSelect(e) // call the default onSelect function        
        setAllRowsSelected(e.target.checked) <-- incorrect value
    }
```

It's only an incorrect value for when the select all checkbox is a dash, I assume this is because it was never actually 'checked', it was set to a dash because one of the individual rows was checked. So then when I click the dashed selected all checkbox, I assume the checked property gets set to true, but it should be false?

**Comment by veloware** [comment]
I have added a codesandbox link to the main comment
https://codesandbox.io/s/affectionate-flower-fukbb?file=/index.js

You'll see checking and unchecking the select all prints the correct checked value, unless from the default state, you check a single row or rows and then try and deselect all using the select all checkbox

**Comment by zbeedatm** [comment]
I'm having the same... when part of the rows are selected, then click on the select-All checkbox it's unselecting all, but the checked value in this case is "true" and can't distinguish between the real select-All behavior and between this scenario.

In order to distinguish between them, I'm checking if the length of my selected items is greater than zero and I behave accordingly.  The question if you are attend to do a fix there?

**Comment by joshblack** [comment]
This is definitely a tricky one, unfortunately. The `e.target.checked` value that is shown in the example is the native checkbox event where-as what we're talking about is the state for the table selection. Unfortunately, this isn't a first-class API for this component and would need to be added. The intent here is that `selectedRows` should give you the information that you need, and `onClick` can be passed in to React to the user clicking on the checkbox for selecting all rows, but coordinating the two is currently not available.
