### ISSUE TITLE
`Radio Tile Group` outline disappear problem

### ISSUE THREAD

**Issue by ZhuoyueLyu** [carbon-design-system/carbon#6306]
Hi, I'm Zhuoyue from the IBM Watson Studio UI team and am currently working on developing UI for AutoAI.

The `Radio Tile Group`'s **outline disappears** under 70% Zoom or smaller. This seems to be the bug for Chrome alone, in the safari everything is fine.

**Safari**      
![image](https://media.github.ibm.com/user/286729/files/abbc4400-b0b6-11ea-8c76-1947e3014b68) 
**Chrome**
![image](https://media.github.ibm.com/user/286729/files/b37be880-b0b6-11ea-92b9-c3bea5708fca)

**Safari**      
![image](https://media.github.ibm.com/user/286729/files/1c189480-b0ba-11ea-8d9b-a3aae778da19)
**Chrome**
![image](https://media.github.ibm.com/user/286729/files/0d31e200-b0ba-11ea-9fe8-0435a76f45c6)

A temporary fix we are using is to add the following code inside the `tilesContainer` of the respective `.scss`, but this only partially solves the problem. If we zoom in 67% or less, we need an even smaller `outline-offset` to make sure the outline shows up correctly. But under smaller `outline-offset`, the 110% or more zoom in will looks weird. So I think this component should be updated for this situation. Thanks!

```css
:global(.bx--tile--is-selected){
	outline-offset: -1.5px !important;
}
```

**Comment by joshblack** [comment]
Hey @ZhuoyueLyu! 👋   Could you share your use-case for zooming out at 67% or lower?

**Comment by ZhuoyueLyu** [comment]
Hi, @joshblack  Yeah, 67% is a little bit extreme, but currently, this bug will appear at 90% or lower. (Which is still pretty common, I guess? I'm just wondering if there is any once-all-for-all solution other then change the `outline-offset` 😅 )
 <img width="1680" alt="Screen Shot 2020-06-18 at 11 42 27 AM" src="https://user-images.githubusercontent.com/42444790/85042704-83395600-b159-11ea-90bf-89ef32730e13.png">
<img width="1680" alt="Screen Shot 2020-06-18 at 11 42 25 AM" src="https://user-images.githubusercontent.com/42444790/85042712-86ccdd00-b159-11ea-8073-bcd18a06ae14.png">
<img width="1680" alt="Screen Shot 2020-06-18 at 11 42 22 AM" src="https://user-images.githubusercontent.com/42444790/85042720-89c7cd80-b159-11ea-9172-be08fb42d1df.png">

**Comment by joshblack** [comment]
@ZhuoyueLyu yeah, it's definitely a hard one. It seems like when we go smaller than 100% that Chrome will change the outline width to 1.11111px due to sub-pixel rendering 😞  we can definitely look and see what our options are, most likely switching over to border or box-shadow.

**Comment by ZhuoyueLyu** [comment]
@joshblack Okay, I see...agreed. I've tried the `border` actually, but I notice the tile will move a little bit when we switch selection between two adjacent tiles. I guess it's because the `border` has a certain `width`, which pushes the adjacent tile in the opposite direction. I haven't tried the `box-shadow`, maybe it will work. 😅

**Comment by andreancardona** [comment]
@ZhuoyueLyu Thank you for your patience on this! You should see a fix here: https://github.com/carbon-design-system/carbon/pull/8258
