### ISSUE TITLE
Add `light` prop / variant for `ContentSwitcher`

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/carbon#6309]
### Summary

The `ContentSwitcher` does not currently contrast visually on `ui-01` backgrounds:

![ContentSwitcher](https://user-images.githubusercontent.com/3846874/84994260-575ea600-b142-11ea-8a6b-4722ecda3a2c.png)

It may be that the tokens need to be adjusted, or that a `light` prop / variant should be included, similar to the `TextInput`.

**Comment by josh-tt** [comment]
I've run into this on several occasions as well. The only solution is to pull the switcher onto the background which eats up more vertical space and often not 'correct' if there is something sitting below that area. Seems like it's something that definitely should be addressed.
