### ISSUE TITLE
Code snippet copy button should have a pointer cursor style

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon#631]
## Detailed description

The copy button in [code snippets](http://www.carbondesignsystem.com/components/code-snippet/code) should have a [`pointer`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) cursor style like all other buttons in the system. It's a clear indication something is clickable, especially in this somewhat less obvious context that it's a clickable button.

> Is this issue related to a specific component? 
**Code Snippet**

> What browser are you working in? 
**Firefox + Chrome**

> What version of the Carbon Design System are you using? 
**Latest at this date**

**Comment by alisonjoseph** [comment]
Hi 👋 Our copy buttons already have this.
https://github.com/carbon-design-system/carbon-components/blob/master/src/components/code-snippet/_code-snippet.scss#L50

Can you provide any more detail on where you aren't seeing it? I checked on our storybook and website and see it on both. Thanks! 😄

**Comment by werdnanoslen** [comment]
Whoops, I actually didnt' test in Chrome, that works as expected (pointer icon + color change on hover). On firefox esr 52.6.0 (64-bit), the copy button here does neither: http://www.carbondesignsystem.com/components/code-snippet/code

I'd take a screenshot, but the cursor/hover style disappears when I do the thing.

It also wasn't working on some UI dev work I was reviewing, and since this example didn't work I figured it was the source.

**Comment by alisonjoseph** [comment]
Oh ok, thanks for clarifying, it seems we just need to update the cursor to be on the button and not the svg to make it work in FF.
