### ISSUE TITLE
Select input with a search box

### ISSUE THREAD

**Issue by RichardsonWTR** [carbon-design-system/carbon#6310]
### Summary

Include a search input in the Select Box.

### Justification

Sometimes there's a need to use a select box with a lot of values, e. g. 50+ full names in a select field (it could be person names, company names, etc.).
The user has to scroll this giant list to find the desired option.

Sometimes the user knows only a part of the name. In a stardard select box with a lot of values, the user has to scroll the list up and down several times until he finds what's the beginning of the sentence.

### Desired UX and success metrics

Use case example:
1. The user could click in the select box and the input catches the focus right away. 
2. The user could type only some part of the name, press up and down in the keyboard and press enter to select the desired option.
3. Then the focus will move to the next field of the page/form.

### "Must have" functionality

This should be implemented as an extension of the actual Select component.
The developer must be able to choose to turn this feature on and off.

### Specific timeline issues / requests

It would be nice to have this in the next release, as I think this is a very powerful and handy feature to have.

### Available extra resources

Examples from other Design Systems
* [Sandbox Select box from Ant Design System](https://codesandbox.io/s/urdnh). For docs, click [here](https://ant.design/components/select/)
* [Docs - Select input from Bold Design System](https://bold.bridge.ufsc.br/en/components/select/)

**Comment by tw15egan** [comment]
Does the `ComboBox` component fit this functionality? 

https://react.carbondesignsystem.com/?path=/story/combobox--default

**Comment by RichardsonWTR** [comment]
Thanks! This is the exact thing I was looking for!
I hadn't found it because I wasn't looking at the right place.

But this answer leads me to another questions:
* Shouldn't there be a section about  Comboboxes on the [Carbon Design System Components Overview page](https://carbondesignsystem.com/components/overview)?
* What's really the difference between a `Select` and a `Combobox` (apart from the implementation)? I mean, why call one `Select` and one `Combobox` instead of just simply calling  `Combobox`  "Select with search"? Is it a mistake ? Or a project decision?

**Comment by tw15egan** [comment]
Yeah, this is a difficult one, because, under the hood, it is built using the Downshift library, which powers all of our `Dropdown`-like components. That would be `Dropdown`, `MultiSelect`, and `ComboBox` ([Link on Carbon](https://carbondesignsystem.com/components/dropdown/usage#combobox)) This is in addition to our `Select` component, which is mainly left unstyled due to difficulty achieving cross-browser design parity. Since it is built with and is styled similarly to the Dropdown components, that is where it lives.

**Comment by RichardsonWTR** [comment]
Thank you for the information explaining this differences.
