### ISSUE TITLE
ExpandableTile collapsed unexpectedly when hitting Space key in an INPUT field

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/carbon#6314]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `ExpandableTile` component collapsed unexpectedly when I hit the Space key in the `TextInput` component in the tile. I tried to attach `onKeyDown` and onKeyUp` hook to stop the event propagation, but it does not help.

> Is this issue related to a specific component?

Yes. ExpandableTile component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect if I have form input fields in the ExpandableTile, the tile will remains expanded as I type through the form fields.

> What browser are you working in?

Chrome.

> What version of the Carbon Design System are you using?

`carbon-components-react` v7.12.0
`carbon-components` v10.12.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This happens in IBM Cloud Console and it's already in production.

## Steps to reproduce the issue

1. Toggle the ExpandableTile to expand the tile.
2. In the text input field, type ` ` (a Space key)

## Additional information

- Code

```
    stopPropagation = (e) => {
        e.stopPropagation();
    }
```
```
<ExpandableTile>
  <TileAboveTheFoldContent>
    <p className="expandable-tile-title">Some text</p>
    <p className="details-page-section-description">Some text</p>
  </TileAboveTheFoldContent>
  <TileBelowTheFoldContent>
    <TextInput id="a" onClick={this.stopPropagation} KeyUp={this.stopPropagation} KeyDown={this.stopPropagation} type="text"/>
    <TextInput id="b" onClick={this.stopPropagation} KeyUp={this.stopPropagation} KeyDown={this.stopPropagation} type="text"/>
  </TileBelowTheFoldContent>
<ExpandableTile>
```

- Screenshot:

![expandable-tile](https://user-images.githubusercontent.com/12156672/85074177-1f7b5100-b18a-11ea-9b31-12fabec828d9.gif)

- Notes

**Comment by emyarod** [comment]
do you have an alternative pattern for exposing that text input, or any more information on your use case? I discussed this with our designers and it seems that placing form inputs within expandable tiles is generally not recommended
