### ISSUE TITLE
𝗙𝗶𝗹𝗲 𝘂𝗽𝗹𝗼𝗮𝗱𝗲𝗿 𝗺𝘂𝗹𝘁𝗶𝗽𝗹𝗲 𝗳𝗶𝗹𝗲𝘀 | 𝗡𝗼𝘁 𝘄𝗼𝗿𝗸 𝗹𝗶𝘀𝘁𝗲𝗱 𝗶𝘁𝗲𝗺𝘀

### ISSUE THREAD

**Issue by MwSpaceLLC** [carbon-design-system/carbon#6321]
Hi there,

We can't render correct number at files:

![image](https://user-images.githubusercontent.com/29952045/85201724-f41b7200-b301-11ea-8403-7c767466de03.png)

**Comment by MwSpaceLLC** [comment]
File uploader reset file selection automaticly,

U must remove old item with `onDelete={()=>{}}`

**Comment by MwSpaceLLC** [comment]
es:

```js
    function openFileManager() {
        document.querySelector('.bx--file-container').innerHTML = null;
        // console.log(document.getElementById('id1').files)
    }

            <FileUploader name="files" multiple
                          accept={[
                              '.jpg',
                              '.png',
                              '.pdf'
                          ]}
                          buttonKind="ghost"
                          buttonLabel="Add files to case"
                          filenameStatus="edit"
                          iconDescription="Clear file"
                          size="field"
                          onChange={openFileManager}
                          // onDelete={checkFiles}
            />
```

**Comment by MwSpaceLLC** [comment]
Not work propery

**Comment by MwSpaceLLC** [comment]
Is very difficult to learn how to manage file list multiple.

When we user change file, the list not update

![image](https://user-images.githubusercontent.com/29952045/85203166-14502e80-b30c-11ea-9873-a4e12c3a3609.png)

**Comment by MwSpaceLLC** [comment]
Hi @dudley-ibm @joshblack @aledavila @tw15egan,

If we add a file by opening the file manager after having previously inserted files,

the system calculates in the input only the last selected file and does not delete the other files so we cannot understand how to make it work

![image](https://user-images.githubusercontent.com/29952045/85203394-d18f5600-b30d-11ea-92e7-8a8bed2c11b7.png)

**Comment by dudley-ibm** [comment]
Could you please clarify? I'm not sure which file nor from which pull request this issue arose.

**Comment by MwSpaceLLC** [comment]
Hi @dudley-ibm, thanks for reply.

When we add the multiple file field to our project, you can choose for example 3/4 files and the component generates the div of the files (FileUploaderItem) and so far everything works.

Aw we choose for example another file, another file uploader item is generated, but the total number of files is not increased. The content of all the files is reset and the input contains the last one entered dolefully.

This creates confusion and we can't figure out how to solve the problem.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by MwSpaceLLC** [comment]
shure: https://codesandbox.io/s/morning-waterfall-fpivs?file=/src/index.js

The file if u add files in 2/3 step, return only currenct select file and list not update and u lost old file selection.

![image](https://user-images.githubusercontent.com/29952045/85307109-c542fe80-b4af-11ea-892f-5863d0137e5a.png)

This simple return in onChangeFileTrigger function alweys last files but not all.

**Comment by MwSpaceLLC** [comment]
Hi there,

We have found another issue in this component.

When u attach in 2/3 times many file. If user add files with same name, when clicl on delete, the component delete all item with same name.

I think this is no correct, because the iterator must be a univoque id for item deleted.

![image](https://user-images.githubusercontent.com/29952045/85391270-3afba880-b54a-11ea-9f56-376b6425a07f.png)

**Comment by emyarod** [comment]
thanks for the sandbox link, can you reduce the test case down further to contain only the relevant portions and provide a clearer description about the issue(s) and how to replicate them?

**Comment by MwSpaceLLC** [comment]
shure @emyarod, u can find our example at https://codesandbox.io/s/elated-sky-56cqq?file=/src/index.js.

The full explanation is easy, the total number of files in the input file is wrong. This input always returns the total of files selected incorrectly, as you can see if you select multiple files by opening the file manager of your computer several times.

![ibm-files](https://user-images.githubusercontent.com/29952045/85440881-cc8d0980-b58e-11ea-8454-b95fb397be64.gif)

**Comment by MwSpaceLLC** [comment]
In the gif you can also see that the system deletes the selected file in a messy way by removing several files at the same time.

**Comment by emyarod** [comment]
these are all issues with your example application. you are overwriting the list of total files rather than adding them together

https://codesandbox.io/s/strange-worker-bm92j?file=/src/index.js

you are also not providing unique ids for your files so by default it uses names as identifiers. if you look at the example drag and drop file uploader application, you can see how the component is used

https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/drag-and-drop-file-uploader

**Comment by MwSpaceLLC** [comment]
Sorry for the inconvenience, it was an old development where we were just starting out with React. Surely today errors of this kind will not happen. Thanks for your patience
