### ISSUE TITLE
[icons] some icon SVGs downloaded from Carbon/IDL library pages are blank when opened in Illustrator

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/carbon#6324]
Have had a few people reach out to me with this issue. The following icons in particular:

<img width="377" alt="Screen Shot 2020-06-22 at 3 25 00 PM" src="https://user-images.githubusercontent.com/16782944/85327355-cb7baf80-b49c-11ea-90fc-09b62cd25df8.png">

<img width="296" alt="Data-share-knowledge" src="https://user-images.githubusercontent.com/16782944/86291612-39bb2300-bbbd-11ea-9b85-cf6bd7d8fb7d.png">

<img width="263" alt="User-collaborate" src="https://user-images.githubusercontent.com/16782944/86291626-40e23100-bbbd-11ea-9a31-07d81056c7ec.png">

It's likely there are more but I haven't looked into it. The icon SVGs open in browser fine but when opened in Illustrator there is a single point labeled "path" with nothing else in the layer and the rest of the canvas is blank as shown below:

<img width="724" alt="Screen Shot 2020-06-22 at 3 28 27 PM" src="https://user-images.githubusercontent.com/16782944/85327497-0ed61e00-b49d-11ea-9fab-31d324ca5e8f.png">

This is happening on both Carbon and IDL icon libraries and in both Chrome and Firefox.

**Comment by conradennis** [comment]
issue relates to #6354

**Comment by joshblack** [comment]
Going to close this in favor of: https://github.com/carbon-design-system/carbon-website/issues/1344 moving forward 👀
