### ISSUE TITLE
Cannot update a component (`App`) while rendering a different component (`Dropdown`).

### ISSUE THREAD

**Issue by MwSpaceLLC** [carbon-design-system/carbon#6327]
Hi there,

onChange function in dropdown not work. in this example u can see for our project, work only ComboBox:

https://codesandbox.io/s/eloquent-shtern-9uf35?file=/index.js

![image](https://user-images.githubusercontent.com/29952045/85421012-36e48080-b574-11ea-8748-fb411346db4f.png)

**Comment by tw15egan** [comment]
If you change the component structure to `const App = () => ` it properly logs the `onChange`


https://codesandbox.io/s/new-sky-ztmqn?file=/index.js

**Comment by MwSpaceLLC** [comment]
thanks @tw15egan,
We wanted to warn that an error appears in the console we did not want to say that it does not work. by mistake we wrote the demo wrong but the logical sense is that an error appears in the on-change function.

otherwise if you use the combobox component this error disappears

**Comment by justindm234** [comment]
My project (which is different from OPs) sees the same error in our application after upgrading to carbon-components-react@7.14.0 (from 7.10.3). Our Dropdown onChange handler dispatches a redux action to validate the form and handle two-way binding. The error appears to only occur the first time the Dropdown's value changes and was not seen in carbon-components-react@7.10.3.

    "carbon-components": "^10.14.0",
    "carbon-components-react": "^7.14.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",

**Comment by joshblack** [comment]
cc @dakahn

**Comment by joshblack** [comment]
Hey there! 👋  Thanks so much for filing a bug report, this should be addressed in the next release of Carbon.
