### ISSUE TITLE
User not able to distinguish UI elements if using system color

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon#6339]
Original issue here: https://github.ibm.com/alchemy-containers/argonauts-ui/issues/1245
@xiepingp

===== ENVIRONMENT =====
Browser: Firefox 68.8.0esr (64-bit)
IBM CI 162 Checkpoint Violation: Checkpoint 1.4.1 Use of Color
IBM Guidance: https://www.ibm.com/able/guidelines/ci162/color.html
Test Tool Type: Manually Check

===== STEPS TO REPRODUCE =====
Firefox->Preference->Colors
![Firefor color setting](https://media.github.ibm.com/user/277747/files/ea567980-ab5f-11ea-8cd9-20cf4990de8e)

Go to https://cloud.ibm.com/observe, check all pages with the above configuration

===== DEFECT DESCRIPTION =====
User not able to distinguish radio button selection:
![image](https://user-images.githubusercontent.com/18622709/85608531-c5134200-b61a-11ea-8aca-f38544990331.png)

Small Toggle is invisible
![671 - 02 Settings - Freeze toggle ](https://media.github.ibm.com/user/277747/files/0870a980-ab61-11ea-8889-a5cfd2ae72b3)

Toast notification close button
![671 - 03 Close button - Generate plan ](https://media.github.ibm.com/user/277747/files/0870a980-ab61-11ea-911a-f4683929209a)

===== EXPECTED RESULT =====
The intent of this Success Criterion is to ensure that all users can access information that is conveyed by color differences, that is, by the use of color where each color has a meaning assigned to it.
https://www.w3.org/WAI/WCAG21/Understanding/use-of-color

**Comment by joshblack** [comment]
Hey there @jrpomeroy! 👋  I believe this falls under the same support message for Firefox as the other HCM one: https://github.com/carbon-design-system/carbon/blob/master/docs/on-windows-hcm-support.md#firefox

Would love to hear your thoughts here!

**Comment by jrpomeroy** [comment]
@xiepingp any thoughts on this one?

**Comment by xiepingp** [comment]
Thanks @joshblack and @jrpomeroy for following up, happy to close it
