### ISSUE TITLE
Contents are missing in Windows High Contrast Mode

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon#6340]
Original issue here: https://github.ibm.com/alchemy-containers/argonauts-ui/issues/1246
@xiepingp

===== ENVIRONMENT =====
Browser: Firefox 77.0.1 (64-bit)
IBM CI 162 Checkpoint Violation: 
Checkpoint 1.1.1 Non-Text Content
Checkpoint 1.4.1 Use of Color
IBM Guidance: 
https://www.ibm.com/able/guidelines/ci162/non_text_content.html
https://www.ibm.com/able/guidelines/ci162/color.html
Test Tool Type: Manually Check

===== STEPS TO REPRODUCE =====
Pre-condition: Control Panel\Appearance\Display\Color and Appearance -> Color scheme as "High Contrast Black"
![WHCM](https://media.github.ibm.com/user/277747/files/36fcd480-af13-11ea-975a-ac9d4b573d58)

Go to https://cloud.ibm.com/observe, check all pages with the above configuration.

===== DEFECT DESCRIPTION =====
OverflowMenu icon, DropDown arrow icon, visited links
![HCM 01](https://media.github.ibm.com/user/277747/files/5c1bc380-b561-11ea-9eff-2c28165b4202)

Modal close button, DropDown arrow icon
![HCM 02 Configure platform logs](https://media.github.ibm.com/user/277747/files/8a999e80-b561-11ea-8057-cab358cbb083)

CodeSnippet copy button
![HCM 03 Edit log sources](https://media.github.ibm.com/user/277747/files/8ff6e900-b561-11ea-8d1b-c67ab9cc3321)

===== EXPECTED RESULT =====
The intent of this Success Criterion is to make information conveyed by non-text content accessible through the use of a text alternative. 
https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html

**Comment by joshblack** [comment]
Hey there @jrpomeroy! 👋  I believe we don't support WHCM on Firefox based on: https://github.com/carbon-design-system/carbon/blob/master/docs/on-windows-hcm-support.md

Specific section for Firefox: https://github.com/carbon-design-system/carbon/blob/master/docs/on-windows-hcm-support.md#firefox

**Comment by jrpomeroy** [comment]
FYI @xiepingp

**Comment by xiepingp** [comment]
@jrpomeroy, I think my question has the answer now 😄.
As it doesn't support HCM for Firefox and it works well in Chrome, I am happy to close this issue.
Thanks @joshblack for your explanation.
