### ISSUE TITLE
Hardware monitoring: Legend and visualization interaction

### ISSUE THREAD

**Issue by Grace-Harkin1** [carbon-design-system/carbon#6345]
### Summary

The HDM Yosemite team has designed an interactive graphical view to monitor hardware racks. Since the rack component statuses are indicated by a color overlay, we have incorporated a legend of the colors in the left “System health” panel. This legend interacts with the graphical view similarly to that of of the Carbon data visualization legends by acting as a filter on hover and select. However, we differentiated from the Carbon legend by adding a “Clear filters” button below the legend. 

### Justification

This "Clear filters" button not only clearly indicates to the user that the legend acts as a filter for the graphical view, but it allows them to easily reset their filters instead of having to click through each legend item in order to reset it. Without this addition, the user may have difficulty identifying the function of the legend. The legend was the best solution since having a legend and filters would be redundant because Carbon legends act as filters already. This solution is not only easier for the user but saves time as well.

### Desired UX and success metrics

This is the default screen.
![5 0 0a_HO graphical default 1312](https://user-images.githubusercontent.com/64492316/85637090-17625c00-b637-11ea-9433-972fd2a9833b.png)

The user hovers over the status "Failed" in the legend.
![5 0 1a_HO graphical syshealth hover 1312](https://user-images.githubusercontent.com/64492316/85637096-1b8e7980-b637-11ea-9eac-853be69214e7.png)

The user hovers over the status "Attention" in the legend.
![5 0 2a_HO syshealth hover 1312](https://user-images.githubusercontent.com/64492316/85637099-1cbfa680-b637-11ea-9a30-c95f39fc6196.png)

The user selects the status "Failed" in the legend.
![5 0 3a_HO graphical syshealth filtered 1312](https://user-images.githubusercontent.com/64492316/85637100-1d583d00-b637-11ea-811b-4d88c07c9303.png)

With one legend item already selected, the user hovers over another legend item.
![5 0 4a_HO syshealth hover 1312](https://user-images.githubusercontent.com/64492316/85637339-c737c980-b637-11ea-8e4e-6485769a8bba.png)

The user selects the status "Unreachable" in the legend.
![5 0 5a_HO syshealth filtered 1312](https://user-images.githubusercontent.com/64492316/85637102-1df0d380-b637-11ea-9c65-a3e13c6911e0.png)

The user hovers over a component within the graphical view. The component is highlighted (similar to a button interaction), and a tooltip appears surfacing the component name and status icon.
![5 0 5a_HO syshealth filtered 1312 Copy](https://user-images.githubusercontent.com/64492316/85637623-8db38e00-b638-11ea-8290-731fc56e7692.png)

The user selects the component, and a component details preview panel slides in from the right side.
![5 0 5a_HO syshealth filtered 1312 Copy 2](https://user-images.githubusercontent.com/64492316/85637619-8a200700-b638-11ea-92e7-da4c1419029a.png)

Entire graphical view experience: https://ibm.invisionapp.com/share/KRO00OSA52Z#/319586398_5-0-0a_HO-graphical-default-1312

### "Must have" functionality

The user must have a way to filter by component status.
The user must have a legend for the status color.
The user must be able to select a component within the graphical view to surface component information.

### Specific timeline issues / requests

The Yosemite is currently working to build this for the 1.0.9 release (GA is in August) based on the designs above.

**Comment by alisonjoseph** [comment]
@theiliad this might be a good discussion to have on the Wednesday data viz call?

**Comment by theiliad** [comment]
> @theiliad this might be a good discussion to have on the Wednesday data viz call?

I'm assuming we're talking about the legend here.

We can make the legend renderable on its own down the road (definitely not happening by August), however there might be an issue with sizing. Not sure if we'll be able to have the SVG component take up a dynamic amount of size. Usually SVGs need to have a specified height which will break styling in this case...

**Comment by Grace-Harkin1** [comment]
Yosemite ended up changing the design of this page to no longer include this behavior.
