### ISSUE TITLE
Helper text position control

### ISSUE THREAD

**Issue by dimitrihoffmann** [carbon-design-system/carbon#6347]
### Summary

I have noticed that the helper text of our input fields moved below the input element. I am wondering what the intent of this change was. In general, I see multiple issues with that:

1. From an information hierarchy aspect, this is a step backward. Especially when you have a helper text and a placeholder text it is not obvious how the reading order should be.
2. The validation text is replacing the helper text which could result in some unwanted behavior.
3. Related elements underneath an input field can fall "out of context" by adding a constant helper text between them.

### Justification

The current implementation is not flexible enough for many cases in actual products.

### Desired UX and success metrics

I can see why for some reason and some context it might be better to helper text at the bottom. However, I doubt that this is the perfect solution for all cases. Could we think about providing a flexible way to select if this helper text should be shown above or underneath the input element? Besides all of that, the sketch files are now out of sync with the actual implementation which leads to issues while designing complicated screens.

### "Must have" functionality

A way to control the position of the helper text.

**Comment by tw15egan** [comment]
Looks like this is unlikely to be supported as design direction states that the helper text goes below the input field

https://www.carbondesignsystem.com/components/form/usage#helper-text
