### ISSUE TITLE
Missing right-padding sortable data-table heading

### ISSUE THREAD

**Issue by Lc0rE** [carbon-design-system/carbon#6348]
## What package(s) are you using?

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Making a data-table sortable will result in a `padding-left: 0` for the button in the `<th>` element.
By inspecting the DOM, we can see that the `.bx--table-sort` class is responsible of this behavior.

The scss file `_data-table.sort.scss` contains the rules for the class `bx--table-sort` https://github.com/carbon-design-system/carbon/blob/808603fdaa8ac00097b042e0f807c3d5ac14149c/packages/components/src/components/data-table/_data-table-sort.scss#L43

The same class, in the live examples, has both the right and the left margin applied.
My current workaround is to apply a global override to the `bx--table-sort`:

```scss
.bx--table-sort {
  padding: 0 $spacing-05;
}
```

Is there something I'm missing? Even if I'm working on the angular library of the carbon-components, I think this is a possible issue with **carbon-components**.

> Is this issue related to a specific component?
**data-table**

> What version of the Carbon Design System are you using?
**10.14.0**

## Additional information

![image](https://user-images.githubusercontent.com/7023628/85759092-32090380-b711-11ea-811f-749475c72f31.png)

**Comment by tw15egan** [comment]
It seems like the padding should be coming in via the `bx--table-header-label` part of the `th`. Can you verify the text in the header is using that class? 

<img width="378" alt="Screen Shot 2020-06-29 at 11 48 52 AM" src="https://user-images.githubusercontent.com/11928039/86044150-91f7f680-b9fe-11ea-8b94-98d2898102b3.png">


Seems to render properly on latest, could be a mismatch in HTML structure between Angular and React versions 

<img width="358" alt="Screen Shot 2020-06-29 at 11 47 37 AM" src="https://user-images.githubusercontent.com/11928039/86044497-059a0380-b9ff-11ea-9ec2-25ca988cd53e.png">
