### ISSUE TITLE
DataTable > Pagination > Dropdown  item border on google chrome

### ISSUE THREAD

**Issue by vishalc129** [carbon-design-system/carbon#6352]
Thick black border is added to items in pagination dropdown on hover in google chrome.

using package -     carbon-components-react:    version "7.10.5"

![image](https://user-images.githubusercontent.com/38748244/85827786-95904100-b7a4-11ea-8d8d-334500c5b385.png)

**Comment by emyarod** [comment]
this is new in Chrome 83

https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

https://developers.google.com/web/updates/2020/05/nic83#forms

**Comment by vishalc129** [comment]
@emyarod  
Im using Google Chrome **Version 83.0.4103.116 (Official Build) (64-bit)**.
but still this issue is reproducible.

It works as expected in firefox but not in chrome. Please reopen and review this issue.
Please open [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select](url) this link in chrome and firefox you will see the difference in dropdown options css.

![image](https://user-images.githubusercontent.com/38748244/85979106-8e17a480-b9fd-11ea-9c10-e1642b9a0835.png)

**Comment by emyarod** [comment]
my original point was that this change was introduced in Chrome 83 and is part of the browser styles

**Comment by vishalc129** [comment]
@emyarod  is there a way to override that css and remove that black outline border on option hover.
Please advise.

**Comment by emyarod** [comment]
there may be a method by setting `-webkit-appearance: none` and adding in custom styles but that seems a bit brittle. as far as I know currently there is no straightforward workaround for browser styles in `<select>`
