### ISSUE TITLE
Datatable > Deep sub.key | multidimensional header from data

### ISSUE THREAD

**Issue by MwSpaceLLC** [carbon-design-system/carbon#6357]
Hi there, we have a .14 version of React component.

Today we want use Datatable component with this mok data:

```js
{
    attached_groups: "Maureens VM Groups",
    id: "b",
    name: "Load Balancer 1",
    port: 443,
    protocol: "HTTP",
    rule: {
      id: 36,
      name: "joe"
    },
    status: "Starting"
  }
```

We must take rule.name in datatable value. This example for test: https://codesandbox.io/s/lingering-rain-citj4?file=/index.js

U know if possible as a client? for our experience is the best choice.

**Comment by emyarod** [comment]
I don't quite understand your original question, would you mind clarifying what you are asking?

**Comment by MwSpaceLLC** [comment]
@emyarod shure!

We want to take this value on datatable. 

![image](https://user-images.githubusercontent.com/29952045/86046655-e37ba200-ba4d-11ea-986d-086ce080fd4d.png)

we have tried with `rule.name` in `header key` but not work

**Comment by tw15egan** [comment]
Can you check if the `value` is an object first before putting in the value? I changed the `headerData` key for `rule` to match the rest of the headers, then added a check in the row map

https://codesandbox.io/s/mystifying-rhodes-5npq3?file=/index.js

**Comment by MwSpaceLLC** [comment]
Thanks @tw15egan, but i don't think is possible check with this method.

We have many deep object. In official project we have many obj and  dinamc keys.

I want suggest the Datatable component header data futures as follow:

```js
const headerData = [
  {
    header: "Protocol Date",
    key: "name.protocol.date"
  },
  {
    header: "Protocol",
    key: "protocol"
  },
  {
    header: "Port Status Email",
    key: "port.email.status"
  },
  {
    header: "Rule Name",
    key: "rule.name"
  },
  {
    header: "Owner Email,
    key: "name.email"
  },
  {
    header: "Status",
    key: "status"
  },{
    header: "Protocol Date",
    key: "name.protocol.date"
  },
  {
    header: "Protocol",
    key: "protocol"
  },
  {
    header: "Port Status Email",
    key: "port.email.status"
  },
 {
    header: "Port Status Email",
    key: "port.email.status"
  },
  {
    header: "Rule Name",
    key: "rule.name"
  },
  {
    header: "Owner Email,
    key: "name.email"
  },
];
```

We have many deep data. We have also tried the type of checker. 

For the moment i think that we don't have any possibility ??

**Comment by maslof** [comment]
#6600
