### ISSUE TITLE
Carbon Design in VueJS -- CarvueJS

### ISSUE THREAD

**Issue by nicholaslee119** [carbon-design-system/carbon#636]
## Detailed description

Hi, guys, 
I really appreciate your works, Carbon Design is such great design.

And I am familiar with VueJS, so I implemented a UI components library according to Carbon Design with VueJS which name is Carvue

this is [REPO](https://github.com/carvuejs/carbon-components-vue)

and [Live Demo](https://carvuejs.github.io/)

To be honest, there is still so much work I should do, and I am still working on it. 

Just Let you know it exists

**Comment by asudoh** [comment]
The demo looks awesome! Great to see your effort and thank you for letting us know!

**Comment by tw15egan** [comment]
@nicholaslee119 This is great! Thanks for taking the time to work on this implementation! Looking forward to seeing the progress you make on this 🎉

**Comment by nicholaslee119** [comment]
Hi guys,
I am working on making a website for carbon design in VueJS, and here it is [CarvueJS](https://carvuejs.github.io/carvuejs-website/dist/index.html)

And I am wondering could I use some materials from http://carbondesignsystem.com/  
such as some icons, or some pictures?
