### ISSUE TITLE
Sorted and Searchable DataTable with Pagination from backend

### ISSUE THREAD

**Issue by illeatmyhat** [carbon-design-system/carbon#6373]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
The current DataTable is suitable for situations where you can download the entire dataset and use the built-in sorting mechanism.
However, with large enough datasets, you must stream the data in a page at a time to prevent overloading either the client or the server.
This is incompatible with the current built-in sorting mechanism, because it only sorts the _page_.
It's preferable to simply retrieve the current sort state, i.e. 
```tsx
const [sortHeader, setSortHeader] = useState('created');
const [sortDirection, setSortDirection] = useState('None');

const [page, setPage] = useState(1);
const [pageSize, setPageSize] = useState(10);
const start = pageSize * (page - 1)
const end = start + pageSize
const { data } = useSWR([start, end, sortHeader, sortDirection, 'myDataset'], getDataset, {suspense: true});
<DataTable 
    onSortChanged={(key: string, direction: 'ASC' | 'DESC' | 'None') => setSortHeader(key); setSortDirection(direction)}
    ...
/>
```
However, it doesn't seem to be possible to do so.
A similar story applies to search.
What is the best way to scale the DataTable component so that its various functionality works well when populated by a backend that can perform its own search/sort/etc?
## Relevant information
For the early stages of my work, I intend to just retrieve the entire dataset since it is still small.
In the future, a feature may end up being requested that requires this functionality.

**Comment by Sourtoast** [comment]
Agreed this is much needed feature

**Comment by RichardsonWTR** [comment]
In addition to this, I say that the `Pagination` component must not disable the Next Page button if the total number of pages is unknown - `pagesUnknown == true`.

We, the developers must disable the Next page button when we discover that we reached the end.

You can check the actual behavior in the  [Pagination - Storybook][1]

[1]: https://react.carbondesignsystem.com/?path=/story/pagination--multiple-pagination-components

**Comment by Sourtoast** [comment]
@illeatmyhat I think it's more of a "Feature request or enhancement 💡" than a question

**Comment by illeatmyhat** [comment]
Well, either way I cant update the label

**Comment by Sourtoast** [comment]
You could make a new one and mention it

**Comment by nigellima** [comment]
Any updates on this? I'm facing the same issue.

**Comment by emyarod** [comment]
most likely you would need to implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc. rather than using the built in state manager in `DataTable`, if that makes sense

**Comment by Daveiano** [comment]
This is indeed solved with a custom state manager, here is an actual example: https://github.com/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager
