### ISSUE TITLE
Make definition tooltip positioned relative to body, just like interactive tooltip

### ISSUE THREAD

**Issue by christek** [carbon-design-system/carbon#6379]
### Summary

Definition tooltip is positioned relative to link text. This causes definition tooltip to be clipped in situations where contained in an overflowed element. Requesting (if possible) to make it render positioned like interactive tooltip, so it is injected into DOM before end of body tag, and floating above all other elements (like interactive tooltip).

https://codesandbox.io/s/vigorous-shirley-5dzxb?file=/index.html

In the following exampe, interactive tooltip has the desired functionality.

![tooltips](https://user-images.githubusercontent.com/805889/86345636-15625380-bc5c-11ea-9edd-0e7784afebfd.png)

### Justification

In more complex layouts, such as a scroll-able table, this occurs. Overflowed content is quit common in layouts.

### Desired UX and success metrics

Requesting to make it render positioned like interactive tooltip, so it is inject in DOM before end of body tag, and floating above all other elements.

**Comment by emyarod** [comment]
I believe in these scenarios (tooltips within table cells), using the interactive tooltip is suggested for the reasons you mentioned
