### ISSUE TITLE
[Date Picker]: 'en' locale in Great Britain

### ISSUE THREAD

**Issue by JoelArmendariz** [carbon-design-system/carbon#6380]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The date format for `en-gb` is `dd/mm/yyyy`, however, if `DatePicker` is passed more than `en` it throws proptype errors.

> Is this issue related to a specific component?
DatePicker

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Passing `en` on its own gives `mm/dd/yyyy` format. There should be a way to use an english locale for Great Britain without getting proptype errors.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
 "carbon-components": "10.12.0",
 "carbon-components-react": "7.12.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Set browser to English - United Kingdom, and use the date picker.

**Comment by tw15egan** [comment]
It doesn't seem like Great Britain is [on the list](https://flatpickr.js.org/localization/) of supported locales for Flatpickr, as it must be lumped in with the American formatting. However, you can use the `dateFormat` prop to change the order to `dd/mm/yy`  

Link: https://flatpickr.js.org/formatting/
