### ISSUE TITLE
[data table] show two lines of text in a row

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#6382]
We should show what the XLG prop size would look like if there are two lines of text present. 

-----------------------------------------------------------------------------------------------------------------------------

### Spec
<img width="1157" alt="Frame 1" src="https://user-images.githubusercontent.com/43969356/229915458-39b8d20c-abd5-454a-9a1c-0660499a6b85.png">

**Comment by sstrubberg** [comment]
From DataTable Backlog Grooming call:

We have this in all our design kits, but not in implementation.

**Comment by tay1orjones** [comment]
I think the table supports this as is right now, we just need to add an example of it to one of the storybook stories.
