### ISSUE TITLE
Vanilla Dropdown Issue on Safari (arrow not closing menu on click)

### ISSUE THREAD

**Issue by vinicius-thaeds** [carbon-design-system/carbon#6384]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Using Safari, the dropdown has an issue when opened. If you click in the arrow area to close it, it will close and reopen. The close state is not working.

> Is this issue related to a specific component?

Dropdown component from Vanilla

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The dropdown up-arrow was supposed to close it. It reopens it. 

> What browser are you working in?

Safari

> What version of the Carbon Design System are you using?

v10.x

## Steps to reproduce the issue

1. Step one
Access the dropdown from Vanilla using the Safari browser.

2. Step two
Click on the dropdown and see the arrow change and the menu open.

3. Step three
Click on the dropdown title or the arrow to close it. It won't close.

> Please create a reduced test case in CodeSandbox

- Style and vanilla JS:
https://codesandbox.io/s/focused-sammet-93so8?file=/index.html

**Comment by joshblack** [comment]
Hi there! Unfortunately, we most likely won't be able to fix bugs in the Vanilla JS version of components. Much of our team's focus and attention is on the React side of the components nowadays. As a result, I'm going to close this issue but let me know if you have any questions!
