### ISSUE TITLE
node_modules/carbon-components-react/umd/carbon-components-react.js  invalidText: 'Provide invalidText'

### ISSUE THREAD

**Issue by rojarmj** [carbon-design-system/carbon#6385]
## What package(s) are you using?

- [  NumberInput ] `carbon-components-react`

## Detailed description
node_modules/carbon-components-react/umd/carbon-components-react.js  invalidText: 'Provide invalidText'
I Imported  NumberInput
import {
  Button,
  TextInput,
  MultiSelect,
  NumberInput,
  InlineNotification,
} from "carbon-components-react";

but when there is invalid input for  NumberInput it shows error like 'Provide invalidText',

**Comment by emyarod** [comment]
you can modify the error message through the `invalidText` prop on `NumberInput`
