### ISSUE TITLE
Button tooltip in TableToolbar seems to be hidden if it is rendered outside of the toolbar

### ISSUE THREAD

**Issue by akmalmzamri** [carbon-design-system/carbon#6386]
## What package(s) are you using?
- [x] `@carbon/icons-react - 10.13.0`
- [x] `carbon-components - 10.15.0`
- [x] `carbon-components-react - 7.15.0`

## Detailed description

> Describe in detail the issue you're having.  

Buttons tooltip is hidden if it is overflown. If the button is position to the left or to the right, it will be visible. But if it is position at the top or at the bottom of the button, it will be hidden. I have tried changing `bx--table-toolbar` class's `overflow` property to `visible` but it's not working.

> Is this issue related to a specific component?

TableToolbar

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect it to be visible regardless if it is overflown or not.

> What browser are you working in?

Tried in Chrome 83.0.4103.116

> What version of the Carbon Design System are you using?

10.15.0

## Steps to reproduce the issue
Please refer to this sandbox
https://codesandbox.io/s/carbon-components-react-lltj8?file=/src/index.js

**Comment by sstrubberg** [comment]
Appears to be fixed. Let us know and we can re-open

**Comment by hamid-mahmood-alpha** [comment]
> Appears to be fixed. Let us know and we can re-open

This issue is not fixed. Should be re-opened

**Comment by hamid-mahmood-alpha** [comment]
@sstrubberg can you please tell me in which release this issue was fixed?

**Comment by tw15egan** [comment]
@hamid-mahmood-alpha the codesandbox appears to be working and is using `carbon-components-react` `v7.15`. If you are still encountering this issue, I'd first try updating to the newest version, and if the issue still persists, create a new issue with a reproduction of your issue. Thanks.
