### ISSUE TITLE
[icons] new icons in Carbon/IDL libraries show code names, need friendly names added

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/carbon#6388]
Newer icons in Carbon/IDL libraries show code names and need friendly names added, they're peppered in throughout the library. Those that need friendly names pretty much map to my more recent icon batch PRs so will link those below for reference. Will need to do a sweep of the library and give friendly names to the icons showing code/repo names.

These PRs should account for all of the icons that need friendly names:
https://github.com/carbon-design-system/carbon/pull/6046
https://github.com/carbon-design-system/carbon/pull/5888

Preemptively, this batch of icons PR has yet to be merged but will also need friendly names once it's added:
https://github.com/carbon-design-system/carbon/pull/6371

Example screenshot showing code names mixed in with friendly names:

<img width="1072" alt="Screen Shot 2020-07-06 at 10 07 18 AM" src="https://user-images.githubusercontent.com/16782944/86602527-bdd02a80-bf70-11ea-8239-817d1f039135.png">

**Comment by LMapes** [comment]
@conradennis I'll need help navigating to this PR to correct these friendly name issues. Will ask @joshblack for help.

**Comment by LMapes** [comment]
@joshblack I added the new aliases to the icons.yml but was unable to commit the changes. So I selected all and saved to a word document: https://ibm.box.com/s/wbz3nlmfofj5cmkknc9iggw0s0mcs1zt
