### ISSUE TITLE
DataTable - icon is not displayed in TableToolbarAction

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6413]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

Trying to show an icon near to the itemText of TableToolbarAction but it's not working!

> <TableToolbarContent>
                                                <TableToolbarMenu>
                                                    <TableToolbarAction
                                                        // icon={TrashCan20}
                                                        // showIcon={true}
                                                        // icon={iconSettings}
                                                        // iconDescription="Show Records"
                                                        itemText="Show Records"
                                                        // onClick={action('TableToolbarAction - Settings')}
                                                    />

Is there a sandbox that i can take a look?

**Comment by tw15egan** [comment]
Can you try just passing in an icon as a child of `TableToolbarAction`? 

```jsx
<TableToolbarAction>
   <Delete /> Action 1
</TableToolbarAction>
```

**Comment by zbeedatm** [comment]
That's work for sure. But I tried following your readme in git!
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/README.md#filtering

Thanks anyway

**Comment by tw15egan** [comment]
Oof, good catch! I'll update the documentation now to reflect this. Thanks for bringing it to our attention 🙏
