### ISSUE TITLE
Change the css of two data tables to behave differently

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6421]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I'm trying to use the DataTable component of carbon-react, I have 2 instances of of DataTables: one is inside a Modal and one in other component, and I need to control 2 different sizes/behavior of them.

So I tried achieving it by css:

`#wide-table.bx--data-table-container {
    max-width: 1300px !important;
    max-height: 600px !important;
    width: 100% !important;
    height: 50% !important;
}

#narrow-table.bx--data-table-container {
    max-width: 850px !important;
    max-height: 400px !important;
    width: 100% !important;
    height: 50% !important;
}`

and then use the relevant Id in each table:

`<DataTable id="wide-table"`

But it's not taking affect.
How can i do it?

**Comment by tw15egan** [comment]
Do you have a link to a reproducible example on Codesandbox so we can help debug?

**Comment by zbeedatm** [comment]
See [Sandbox](https://codesandbox.io/s/codesandbox-9yn67)

I used 2 components:

1. ShowData - that has a DataTable with id="wide-table"
2. ShowData2 - that has a DataTable with id="narrow-table"

The first one is displayed in home page, and the second one need to press on the ShowData button to show it inside a modal.

Hope its clear enough!

**Comment by tw15egan** [comment]
1) I didn't see any imports of `App.css`, where those styles were defined, so I added that import to `MyApp.js`
![Screen Shot 2020-07-13 at 9 54 12 AM](https://user-images.githubusercontent.com/11928039/87331488-def3c680-c4ee-11ea-8845-de930661f42c.png)



2) It seems like if you want to attach an `id` to `bx--data-table-container`, you will need to pass it to `TableContainer`, not `DataTable`
![Screen Shot 2020-07-13 at 9 54 28 AM](https://user-images.githubusercontent.com/11928039/87331493-e2874d80-c4ee-11ea-8206-48eabfad518d.png)


3) Modal styles may need to be overridden to achieve the correct modal stylings.

Here is [your example](https://codesandbox.io/s/codesandbox-m6n1u?file=/src/index.js) updated with my fixes, I hope this helps!

**Comment by zbeedatm** [comment]
Great. thanks
