### ISSUE TITLE
Remove `tabIndex` from default props of `Button`

### ISSUE THREAD

**Issue by vladbalanescu** [carbon-design-system/carbon#6423]
## What package(s) are you using?
Carbon-components-react@^7.1.0
Carbon-components@^10.11.1

## Detailed description

> Describe in detail the issue you're having.
[This line](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Button/Button.js#L164) needs to be taken out so that if we have a use case in which we don't want to have the button focusable, we can define `tabIndex={undefined}` and the user won't be able to select that button via tabbing through

> Is this issue related to a specific component?
`Button`

> What browser are you working in?
Chrome, Firefox, Safari

## Additional information
Button is focusable even when the panel is shut:
![image](https://user-images.githubusercontent.com/16047402/87031621-4baf4e00-c1db-11ea-9e5e-b10c8a78fa7d.png)

**Comment by emyarod** [comment]
rather than `undefined` does setting it to a negative value or `null` work for you?

**Comment by vladbalanescu** [comment]
@emyarod if you mean on the consumer side, than the answer is no, if I set it to any of those values this component would use the default prop supplied, since the line above needs taking out for us to be able to have the ability to not focus it.

**Comment by emyarod** [comment]
here is the behavior when I use a negative tabindex https://codesandbox.io/s/frosty-bose-3yehv

can you create a reproducible example of negative tabindex being overwritten by the default prop value?

**Comment by vladbalanescu** [comment]
Works brilliant with a negative index, thank you
