### ISSUE TITLE
TootlipDefinition: Support other values than 'strings' in the children prop

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#6429]
### Summary

Change `TooltipDefinition` React component to support other value types of the `children` prop than `string`. 

### Justification

So we can show the TooltipDefinition on other UI elements like `h2`, `<p>` without any console warnings.

![image](https://user-images.githubusercontent.com/6926228/87069180-bf098d80-c1e4-11ea-9cfd-0a55871a6b59.png)

```jsx
<TooltipDefintion tooltipText="Banana">
  <h3>Hello</h3>
</TooltipDefintion>;
```

Unfortunately wrapping the `TooltipDefintion` definition in another component won't work as the tooltip is rendered as a button:

```jsx
<h3> // Doesn't work
  <TooltipDefintion tooltipText="Banana">Hello</TooltipDefintion>;
</h3>;

```

### Available extra resources

I can help make this change if it's accepted.

The PropType below will need to be changed to `PropTypes.node`

https://github.com/carbon-design-system/carbon/blob/36574d8cc68e46f00c7b52f230618eb1b1e3a131/packages/react/src/components/TooltipDefinition/TooltipDefinition.js#L97

**Comment by tw15egan** [comment]
Makes sense, we would welcome a PR to change this 🙏
