### ISSUE TITLE
Filterable Multiselect onClose

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#6434]
Is there any plans to have an onClose callback to the Filterable Multiselect? I have seen some cases where my team and others have wanted to make selections and then trigger some action after all selections have been made and dropdown has closed vs triggering the onChange after a single selection change.

**Comment by tw15egan** [comment]
No current plans on our end, but we would welcome a PR adding in this functionality

**Comment by bstncartwright** [comment]
I'm also interested in this and will start working on a PR merging in this functionality this week.

**Comment by tw15egan** [comment]
@munkurious Awesome! Would this recently merged PR handle this functionality https://github.com/carbon-design-system/carbon/pull/7288?

**Comment by bstncartwright** [comment]
I do not think so, it looks like the source for the `FilterableMultiSelect` is very different from the `MultiSelect` changed in that PR, but I will use the same prop of `onMenuChange` that was added as part of that PR.

In fact, it looks like `FilterableMultiSelect` and `MultiSelect` are separate components.
