### ISSUE TITLE
TextInput with Inlineloading.

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#6435]
In Carbon homepage, Inlineloading with TextInput is exist.

![image](https://user-images.githubusercontent.com/35518072/87117292-28f06880-c2b3-11ea-9ebb-d34f8a52ce27.png)

However, there is no option to add component inside TextInput. Is it intended? Then, how can I customize this? Is there any plan to add this option? Thanks

**Comment by tw15egan** [comment]
This doesn't exist out of the box, but you could use absolute positioning to render an `InlineLoading` inside of a `TextInput` component

**Comment by baeharam** [comment]
@tw15egan Thanks for the response! Then, is it only way to use `InlineLoading` inside `TextInput`? Do I have to copy original code and customize it?

**Comment by tw15egan** [comment]
You may be able to achieve it via css and relative/absolute positioning values without having to copy the original code

**Comment by baeharam** [comment]
Ah, Ok. But, I already solved it by copying original code...lol. Anyway, I got your point. Thanks @tw15egan ! It could be closed  I think.
