### ISSUE TITLE
[Tooltip]: focus lost after tabbing away from button in tooltip 

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#6443]
## Environment

> Operating system
Mac

> Browser
Chrome 

## Detailed description

> What version of the Carbon Design System are you using?

v10.15 and v7.15

> What did you expect to happen?

I would expect focus to go the next focusable item.

> What happened instead?

The screen jumps to the bottom of the page and nothing is focused. 

## Steps to reproduce the issue

You can see the problem at https://www.carbondesignsystem.com/components/tooltip/code if you tab into the tooltip and tab out. 

It's also affecting Cloud PAL's `ResourceTagArea` because it means a user can't focus the input after the tooltip is automatically opened by focus. https://pages.github.ibm.com/ibmcloud/pal/connected/resource-tag-area/code

**Comment by dakahn** [comment]
Seems like a website problem since I can't recreate on react.carbondesignsystem. I'm moving the issue, but we can move it back if I'm wrong here.

**Comment by dakahn** [comment]
Issue moved to [carbon-design-system/carbon-website #1405](https://github.com/carbon-design-system/carbon-website/issues/1405) via [**ZenHub**](https://www.zenhub.com/)
