### ISSUE TITLE
Grammer adjustment to a paragraph in the developer handbook

### ISSUE THREAD

**Issue by oyin-k** [carbon-design-system/carbon#6446]
I was going through the developer handbook as I am planning to start contributing to the React component library  and I came across this word that I think needs an adjustment.

__As a result, we use two pieces of tooling to help us **managing** installing dependencies and publishing our packages. These include:_

I think the word should be **manage**. I confirmed this on google docs.

**Comment by oyin-k** [comment]
The fix to this issue has been merged in #6447 therefore I would be closing this issue. Thank you very much

**Comment by tw15egan** [comment]
Thanks for contributing!
