### ISSUE TITLE
Warning: `<OverflowMenuItem>` detected missing `closeMenu` prop. 

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6448]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I'm getting this warning:

> 1.chunk.js:413611 Warning: `<OverflowMenuItem>` detected missing `closeMenu` prop. `closeMenu` is required to let `<OverflowMenu>` close the menu upon actions on `<OverflowMenuItem>`. Please make sure `<OverflowMenuItem>` is a direct child of `<OverflowMenu>

 despite all the < OverflowMenuItem> tags are associated with a parent < OverflowMenu> !!
And the menu is working fine when opening closing it!

**Comment by zbeedatm** [comment]
I found the root cause. It's happening when using < TableToolbarAction> ...

> <TableToolbar>
                                            
                                            <TableToolbarContent>
                                                <TableToolbarAction
                                                    onClick={() => {
                                                        service.emit('showRecordsEvent', this.props.project, this.state.table.Name, true)
                                                    }}
                                                >
                                                    <TableOfContents20 /> Show Records
                                                </TableToolbarAction>

related to issue #6413 

Reproduced in: [Sandbox](https://codesandbox.io/s/codesandbox-9yn67?file=/src/ShowData.js)

**Comment by tw15egan** [comment]
Hey there! Looks like you're not wrapping `TableToolbarAction` (`OverflowMenuItem`) in a `TableToolbarMenu` element (`OverflowMenu`). 

https://codesandbox.io/s/codesandbox-ds6bp?file=/src/ShowData.js:7166-7182

Going to close this, but feel free to reopen if you think there is a bug in the codebase.

**Comment by zbeedatm** [comment]
But this is not what I want!!!
I don't want to aggregate all of these actions under a menu, I want them as separated actions within the toolbar... i mean something like:

![image](https://user-images.githubusercontent.com/26740851/87392387-188f0500-c5b5-11ea-9d45-d3cfdb7c615a.png)

How can I achieve it?

**Comment by tw15egan** [comment]
You can taker a look at the Batch Actions example (https://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions) which has the icons show up in a toolbar when an item is selected.

There is no pattern/component for displaying icons in a toolbar at all times, so if that is what you want you'll likely have to build your own.
