### ISSUE TITLE
DataTable with stickyHeader styling of rows and headers regression

### ISSUE THREAD

**Issue by guychris** [carbon-design-system/carbon#6449]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
- Using a DataTable with the stickyHeader prop, there seems to have been a regression between 10.13 and 10.14, the position of header text and row text is no longer vertically centered in the row. The issue is visible in the storybook by toggling the stickyHeader knob - https://react.carbondesignsystem.com/?path=/story/datatable--default

- with stickyHeader:

    ![image](https://user-images.githubusercontent.com/11824031/87324484-25045680-c4fe-11ea-94b1-270e21f8295f.png)

- Without stickyHeader:

    ![image](https://user-images.githubusercontent.com/11824031/87324522-33527280-c4fe-11ea-94c4-4fdbd4db3931.png)

The styling with stickyHeader worked as expected in 10.13 / 7.13. CodeSandbox here: https://codesandbox.io/s/carbondatatablestickyheader-03096 , can change the dependency version in the sandbox to 10.15 / 7.15 to see the broken behaviour there as well.

> Is this issue related to a specific component?
- DataTable with stickyHeader prop

> What did you expect to happen? What happened instead? What would you like to see changed?
- Expected styling of header and row cells to be consistent with and without stickyHeader prop set. Would like styling to be restored so there is consistency.

> What browser are you working in?
- Chrome, firefox

> What version of the Carbon Design System are you using?
- issue in 10.14, 10.15 // 7.14, 7.15

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
- IBM Streams on CPD, a few months of leeway.

## Steps to reproduce the issue

1. Use DataTable with stickyHeader prop.

> Please create a reduced test case in CodeSandbox
- working with 10.13/7.13: https://codesandbox.io/s/carbondatatablestickyheader-03096 , switch dependency versions to 10.15/7.15 to see broken behaviour.

**Comment by tw15egan** [comment]
A fix is up over at https://github.com/carbon-design-system/carbon/pull/6452, let me know if that is rendering how you would expect it to 👍

**Comment by guychris** [comment]
Thanks @tw15egan , that fixes normal tables, but it looks like using expandable rows is broken as well:

https://deploy-preview-6452--carbon-components-react.netlify.app/?path=/story/datatable--with-expansion

![image](https://user-images.githubusercontent.com/11824031/87349303-16c93100-c524-11ea-8237-1abdee8de733.png)
