### ISSUE TITLE
[tooltip] definition tooltip enabled state bug

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#6450]
The enabled state for definition tooltip should have a gray underline.

Spec:
![Tooltip - White theme Copy](https://user-images.githubusercontent.com/43969356/87331380-79f49c80-c4ff-11ea-8298-55f0bf00f1c0.png)

**Comment by andreagmann** [comment]
In terms of documentation, it might be good to call out this information in the [Style tab](https://www.carbondesignsystem.com/components/tooltip/style).

**Comment by laurenmrice** [comment]
@andrea-gm yep I agree, we can add that once we start revising style tab docs for components 👍🏻
