### ISSUE TITLE
Bulk action from overflow menu

### ISSUE THREAD

**Issue by johnsun-ibm** [carbon-design-system/carbon#6455]
### Summary

Aspera hopes to provide our users with the ability to perform a bulk selection action by right-clicking on an item or through the overflow menu on a data table. The Aspera team would like to have this feature in development as well as design.

### Justification

This request pertains to a file management product. We’ve recently seen multiple customer requests come in asking for the ability to perform an action through a bulk selection by right-clicking or from the overflow menu (see screenshot). They have expressed this to be the expected behavior of how a file management system works based on their experience with Windows and Mac’s respective file systems. However, Carbon components weren’t designed that way. Currently, the only way to perform a bulk action is by clicking one of the buttons located at the top of the table after a selection has been made.

### Desired UX and success metrics

Selection of multiple items on a data table, the ability to click on a single overflow menu icon from within that bulk selection or perform a right-click, which would then present all available options that are the same as the buttons at the top of the table but without having to traverse up there to perform those actions. 

### Must-have functionality

Bulk selection action built into the overflow menu

### Specific timeline issues / requests

End of October 2019

### Available extra resources

A design in Sketch

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by vpicone** [comment]
Going to close this one out, please check our ongoing work on Disclosure for v11.
