### ISSUE TITLE
Demo overlaps container in dev enviornment

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#646]
<img width="1042" alt="screen shot 2018-03-08 at 11 09 10 am" src="https://user-images.githubusercontent.com/2753488/37165038-40b2bd2c-22c1-11e8-834a-9216efb87824.png">

cc @asudoh

**Comment by alisonjoseph** [comment]
It might make sense to just change the height to min-height. 

```
[data-renderroot] .component-example__live {
    height: 23rem;
} 
```
to
```
[data-renderroot] .component-example__live {
    min-height: 23rem;
}
```

**Comment by asudoh** [comment]
^ Bingo @alisonjoseph! Will send a PR soon.
