### ISSUE TITLE
Gray 10 Theme: Disabled tags have low / no contrast on white backgrounds

### ISSUE THREAD

**Issue by yung-christensen** [carbon-design-system/carbon#6462]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [x] `Gray 10 Sketch Library`

## Detailed description

> Describe in detail the issue you're having.
I am using tags in disabled state on a white background (i.e. tiles or tables). The disabled tags have a white background in Gray 10 theme. The background of the disabled tags disappear on the white background of the underlying component like a tile.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I'd like to have a light-grey background to the disabled tag, so there is enough contrast to the background of the underlying component

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Hyper Protect Services 

## Steps to reproduce the issue

1. Install Gray 10 Theme
2. Place a selectable tile from that theme on the artboard
3. Place a Tag on the tile
4. Choose "disabled" state of the tile

## Additional information

![image (2)](https://user-images.githubusercontent.com/22619657/87405948-63624a00-c5c0-11ea-8b04-0110a5ae3ee4.png)

**Comment by joshblack** [comment]
cc @aagonzales what would you recommend here for the contrast issues?

**Comment by aagonzales** [comment]
This is actually a problem across the board with `light` variants that used `$disabled-01`. We have no fix for it in v10 but we've solved this problem in v11 with the new layer tokens.
