### ISSUE TITLE
get latest focus-trap-react dependencies on both carbon-components-react v9

### ISSUE THREAD

**Issue by ChunxiAlexLuo** [carbon-design-system/carbon#6467]
## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

Can we update focus-trap-react dependencies here?

https://github.com/carbon-design-system/carbon-components-react/blob/master/package.json#L136

We always get this bug when using carbon-components-react, which is fixed in the latest focus-trap-react
https://github.com/davidtheclark/focus-trap/issues/81

**Comment by emyarod** [comment]
this package is no longer used in v10 (#5260) but we can update the v9 dependency

**Comment by ChunxiAlexLuo** [comment]
> #5260

Thank you!

**Comment by emyarod** [comment]
resolved in https://github.com/carbon-design-system/carbon-components-react/pull/2427 and released in [v6.116.4](https://github.com/carbon-design-system/carbon-components-react/releases/tag/v6.116.4)
