### ISSUE TITLE
Add text wrapping to Codesnippet

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#6473]
I have a request to show a long (single line of text - CRN) in a codesnippet .
I tried using type="multi" but the line does not break, and setting height does not help.

Need to add wrap, so that the text would wrap to multiline.
![image](https://user-images.githubusercontent.com/5415443/87563507-f8039f80-c6c7-11ea-95bb-da9693641cf1.png)

bonus: add max size, or a way to report how many columns are displayed so I can normalize my text from the outside

**Comment by echarpibm** [comment]
I just created the PR that implements this feature. https://github.com/carbon-design-system/carbon/pull/6960
