### ISSUE TITLE
Sticky header for data table with multiple rows in TableHead

### ISSUE THREAD

**Issue by sj-rai** [carbon-design-system/carbon#6476]
### Summary

I'm using dataTable component with stickyHeader prop set to true. I see that if I have multiple TableRow inside TableHead, it just renders the rows one after the other as a single header row, because flex direction isn't set for table head. Wouldn't it be helpful to support multiple header rows when stickyHeader is set to true. 

Modifying css in `.bx--data-table--sticky-header` should do. I would like to contribute and create a PR, if this is a valid requirement.

**Comment by tw15egan** [comment]
Do you have an example you can show where multiple rows would be used in a sticky header?

**Comment by sj-rai** [comment]
Yes. In my case Im trying to implement a search bar in my header and the table contents would be populated on search results. But I also need a row for the column heading. 
<img width="711" alt="Screenshot 2020-07-19 at 11 06 20" src="https://user-images.githubusercontent.com/36308078/87867954-5f16a200-c9af-11ea-92be-5d02627b2b50.png">

But if I enable sticky header, all my input fields which are in the second row will come after all my headings as a single row

**Comment by tw15egan** [comment]
We suggest placing the search above the table, see our example here https://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar
