### ISSUE TITLE
Checkbox focus state is cut off when inside a container with an overflow

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#6480]
## Detailed description

Whenever the `Checkbox` component sits inside a container with a non-default/initial overflow value (like `overflow: auto` or `overflow: hidden`, its focus outline is cut off at the edge of the container.

This is likely because the focus outline uses `box-shadow` & is not currently accommodating for the extra space needed.

Screenshots:

**With `overflow`**|**Without `overflow`**
--- | --- 
<img width="823" alt="Screen Shot 2020-07-16 at 8 52 11 AM" src="https://user-images.githubusercontent.com/9057921/87679501-e1019380-c741-11ea-8e67-5a6e55430166.png">|<img width="822" alt="Screen Shot 2020-07-16 at 8 52 22 AM" src="https://user-images.githubusercontent.com/9057921/87679514-e6f77480-c741-11ea-9b43-1cf3a9cf011a.png">

## Steps to reproduce the issue

1. Go to the storybook: https://carbon-components-react.netlify.app/?path=/story/checkbox--checked
2. Inspect `Checkbox` and find the wrapping `<fieldset>` element
3. In the browser inspector, change the `<fieldset>` to `overflow: auto` or `overflow: hidden`
4. Focus on a `Checkbox` to see the focus "outline" (i.e., box-shadow) is cut off.

**Comment by jendowns** [comment]
There are several approaches to fix this probably, but I do have a quick idea that involves added 2px to make up for the spacing needed for the `box-shadow`. I'll open a PR for that proposal momentarily 👍

**Comment by emyarod** [comment]
this issue is unresolved 

![image](https://user-images.githubusercontent.com/8265238/109031812-afaf5580-768a-11eb-9817-0c9429567de0.png)

https://codesandbox.io/s/spring-night-tnvxu?file=/index.js

ref #7620
related #7113
