### ISSUE TITLE
[Tooltip/TooltipDefinition] Support for hover or truncation with ellipses

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#6484]
### Summary
Can we have a prop added to allow hover support for the `Tooltip` component?

If not, I see the the `TooltipDefinition` does support hover. However, it's wrapped in a button tag which prevents it from being truncated with an ellipses when the screen size is smaller.

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/TooltipDefinition/TooltipDefinition.js#L76

Thanks!

**Comment by aagonzales** [comment]
- Hover + non-interactive tooltip is needed. Need to figure out how to do this from a dev perspective. Interactive tooltips should continue to not support the hover. 
- Is it just adding this example/use-case to the storybook?
- Add this to tooltip work for the next major release.

**Comment by spassvogel** [comment]
Hi there, is there any update on this? i.e. is it possible to have a tooltip that appears on hover, on top of everything (so not obstructed by `overflow: hidden` parents) and disappears when we hover out?  

Basically like the HTML `title` attribute, but then with a bit more styling?  Also, to be positioned left or right from the element that triggered it?

**Comment by emyarod** [comment]
you can insert a span as a child and style it as needed https://codesandbox.io/s/ecstatic-microservice-5jmqj?file=/src/style.scss

#7437 would update the `children` proptype to support this (or we could update the PR to wrap `children` in a span instead)
