### ISSUE TITLE
Could not retrieve the correct date from DatePicker if user don't press enter key 

### ISSUE THREAD

**Issue by meggie7788** [carbon-design-system/carbon#6487]
Title: Request to enhance the DatePicker behavior

> Operating system
Mac OS. 

> Browser
Chrome

## Detailed description
After the user input the new date, if they don’t press the return key but they move the mouse to another place, from the screen the user feels like the date has been changed but it's not internally.

> What version of the Carbon Design System are you using?
7.10.2

> What did you expect to happen?
What date displayed on the screen is the date retrieved from the internal system

> What happened instead?
The date range could be calculated correctly. 

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Step one: manually type the date, but not press the enter key
2. Step two: mouse over to other place, continue whatever need to do. 
3. Step three: console.log to display the value for DatePicker component. It proof the issue. 
4. etc.

- Screenshots
pic-1: date changed manually to 6/13 but I can see that the calendar's blue block still on 6/15... User thinks the new date is ok but not updated internally.  
pic-2: after hit the enter key, the blue block is on 6/13. system also updated internally, user can get the correct value eventually. 
![Screen Shot 2020-07-13 at 11 14 39 AM](https://user-images.githubusercontent.com/26446044/87727040-0eb40000-c775-11ea-8c51-a034101690c6.png)
![Screen Shot 2020-07-13 at 11 16 49 AM](https://user-images.githubusercontent.com/26446044/87727049-12e01d80-c775-11ea-8e6d-82a7d1f57c57.png)

**Comment by dakahn** [comment]
This is doable for sure with a fully controlled component. Here's some docs demonstrating specifically form validation https://react.carbondesignsystem.com/?path=/story/datepicker--fully-controlled

Closing this up for now but we can reopen if I'm missing something.
