### ISSUE TITLE
[ProgressIndicator]: Vertical Indicator secondaryLabel fails to handle long strings of text

### ISSUE THREAD

**Issue by electrostaticfleece** [carbon-design-system/carbon#6497]
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

10.11.2

When feeding text to a vertical progress indicator's secondary label, the component fails to gracefully handle long strings of text and instead overlaps the text over the next item. This will occur if the ProgressIndicator's parent element has a specified width:

<img width="271" alt="Screen Shot 2020-07-17 at 1 21 34 PM" src="https://user-images.githubusercontent.com/16194732/87818981-20f37400-c831-11ea-9de4-56a456492832.png">

> Is this issue related to a specific component?

ProgressIndicator

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the ProgressIndicator to do one of two things:

1) Allow for the indicator to have a dynamic vertical height that is auto-adjusted to the content.
2) Allow for the indicator to truncate text after a certain height.

Option 1 is much more preferable IMHO. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

`10.11.2`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Docs.

## Steps to reproduce the issue

1. Set the ProgressIndicator to have a `vertical` property. And place the element in a parent element with a defined width.
2. Add multiple ProgresSteps
3. Add labels for each step
4. Add a `secondaryLabel` to one of the steps and use a long string of text that forces the text to wrap.

**Comment by tw15egan** [comment]
@carbon-design-system/design would we prefer this to grow dynamically with the content, or truncate after a certain height?

**Comment by emyarod** [comment]
this should be the default component behavior:

![image](https://user-images.githubusercontent.com/8265238/88682178-fff41400-d0b7-11ea-80db-9b7597552ac6.png)

can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by laurenmrice** [comment]
Yes, agreed with @emyarod , I think the text should grow with content.

**Comment by emyarod** [comment]
yeah this should already be the case, at least in our storybook example which the screenshot is from. I haven't been able to reproduce the issue yet so a code sandbox example would help with debugging!
