### ISSUE TITLE
"Sample file" pictogram renders wronlgy

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6498]
## Detailed description

The "Sample file" pictogram's label is rendered pretty thick and looks out-of-place compared to the other pictorgams.
![image](https://user-images.githubusercontent.com/28265588/87919676-7077b100-ca78-11ea-818b-89c8bf897e0b.png)

## Steps to reproduce the issue

1. Visit https://www.carbondesignsystem.com/guidelines/pictograms/library
2. Search for "sample"

**Comment by janhassel** [comment]
This also seems to be an issue with "Inspect data" pictogram.
![image](https://user-images.githubusercontent.com/28265588/87919860-b3d21f80-ca78-11ea-85db-309aa0647933.png)

---
(update 2)
There are several other pictograms that have a stroke and a fill which seems unintentional.
<details>
  <summary>"Code syntax" (window controls)</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943278-1558b500-ca9e-11ea-9ef2-f4d83eba9567.png)
</details>
<details>
  <summary>"Dialogue"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943373-3b7e5500-ca9e-11ea-8965-757eb60e34a4.png)
</details>
<details>
  <summary>"Language 04"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943416-4df88e80-ca9e-11ea-8c02-9291e1d2c55e.png)
</details>
<details>
  <summary>"Question and answer"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943478-649ee580-ca9e-11ea-9e8a-50b9bf594aee.png)
</details>
<details>
  <summary>"App developer"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943532-7aaca600-ca9e-11ea-974e-958a6b9d3534.png)
</details>
<details>
  <summary>"User interface"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943554-81d3b400-ca9e-11ea-93a0-fd603c184850.png)
</details>
<details>
  <summary>"Web developer"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943576-8730fe80-ca9e-11ea-8709-dcf8540385bb.png)
</details>
<details>
  <summary>"Windows"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943603-8ef0a300-ca9e-11ea-9026-0fb08a4f7da5.png)
</details>
<details>
  <summary>"QR code"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943243-0a058980-ca9e-11ea-9af9-ff7dfeee2ad8.png)
</details>
<details>
  <summary>"Video chat"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943723-bb0c2400-ca9e-11ea-9d46-ab3b9bc90b81.png)
</details>
<details>
  <summary>"Question"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943745-c6f7e600-ca9e-11ea-871d-07191e4a3972.png)
</details>
<details>
  <summary>"Warning"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943762-cc553080-ca9e-11ea-8e22-e0425ffacc79.png)
</details>
<details>
  <summary>"Warning alt"</summary>
  
  ![image](https://user-images.githubusercontent.com/28265588/87943782-d1b27b00-ca9e-11ea-810b-f23d30f4294c.png)
</details>

**Comment by laurenmrice** [comment]
Yes this is incorrect. We are figuring out a way to fix this in the assets themselves so they will show up correctly.

**Comment by janhassel** [comment]
Are there any updates on this one? We're using some of these pictograms and they look really awkward next to other "normal" pictograms.

**Comment by joshblack** [comment]
bump @laurenmrice do you know if this sprint's pictogram work would cover this?

**Comment by laurenmrice** [comment]
I am assuming yes if we will be updating the packages with Michael Dudleys new pictogram assets.

**Comment by emyarod** [comment]
we just received a second update to the updated pictograms late last week so we are currently in the process of diffing them against the current set of pictograms and updating metadata accordingly

related #6923

**Comment by emyarod** [comment]
this issue can now be closed as resolved ref: https://github.com/carbon-design-system/carbon/issues/6923 #7272
