### ISSUE TITLE
When height of window is larger than left nav menu, overflow is not set to allow all items to be shown.

### ISSUE THREAD

**Issue by JoeHughes-IBM** [carbon-design-system/carbon#65]
Left navigation doesn't have overflow setup when it's larger than height of window and it also hides the expand/contract on the bottom when it's height isn't perfect. Attached image, can give visual demo if needed as well. Please contact Dale Hille on IBM slack for if a demo is needed.

![pasted image at 2017_05_05 01_08 pm](https://cloud.githubusercontent.com/assets/21244279/25756368/8cfaf808-3194-11e7-9f74-0d37d43c078f.png)

**Comment by hellobrian** [comment]
Hey, @JoeHughes-IBM sorry for the late response.
I found a small fix for this and made a PR https://github.com/carbon-design-system/carbon-components/issues/94

Once this is merged, expect a patch release for this soon.
