### ISSUE TITLE
UI shell: Left navigation

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon#6500]
When left navigation panel is opened, user is forced to select 'X' in order to close the navigation panel. An expected user behavior is to also be able to click anywhere outside of the panel to close it.
Can the behavior of clicking outside of the left panel also close the navigation be added?

**Comment by dakahn** [comment]
This is an enhancement proposal to for the non-fixed sidenav to close on blur.

**Comment by dakahn** [comment]
The sidenav has the prop addFocusListeners, which let's you detect if the user has clicked away (blurred) and close if you'd like.

Closing as resolved, but I can reopen if there is something i've missed.
