### ISSUE TITLE
Link inside the header isn't working

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#6508]
Hey upstream friends,

Our our <Header> isn't allowing any clicks to head back to the root of the site. You can see this on the [Gatsby Theme site](https://gatsby-theme-carbon.now.sh/)

![image](https://user-images.githubusercontent.com/15822070/88072802-17bd1c80-cb3b-11ea-8607-b35ca74ecdce.png)

The Theme is currently running the following..

```
"carbon-components": "^10.11.2",
"carbon-components-react": "^7.11.3",
```

**Comment by tw15egan** [comment]
Any idea what could be causing this? Running it locally I'm able to navigate via the header...
