### ISSUE TITLE
Notification Component: After closing Toast notification, the component does not render on following renders.

### ISSUE THREAD

**Issue by sj-rai** [carbon-design-system/carbon#6509]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

After the toast notification is closed, if I try to render the component again, it doesn't render.
Is this behaviour expected?
## Relevant information

I noticed that `onCloseButtonClick` would set the state of `open` to `false` on closing. So this means that when render the component again it would have `open` set to `false`
```
if (!this.state.open) {
      return null;
}
```
So it doesn't render the notification again.

Im trying to render a notification on a button click. But due to this, it only renders the notification on first click. After closing the notification, `open` is set to `false`. Hence I don't see the notification on subsequent clicks.

**Comment by tw15egan** [comment]
@sj-rai could you recreate a reduced test case on [CodeSandbox](https://codesandbox.io/s/black-moon-2oeko) so we can help debug the issue you're facing?
