### ISSUE TITLE
Does carbon components work with Vuejs?

### ISSUE THREAD

**Issue by nicksarafa** [carbon-design-system/carbon#651]

**Comment by asudoh** [comment]
@nicksarafa While Carbon team only maintains React and vanilla variants, your application can interact with our vanilla version once the corresponding DOM is in place. More details can be found at: http://www.carbondesignsystem.com/getting-started/developers#wrapping-a-component-with-javascript-framework-of-your-choice

Also, I have heard that there is a community-based Carbon variant written in Vue: https://github.com/nicholaslee119/carbon-components-vue

**Comment by nicksarafa** [comment]
thanks @asudoh! we're going to check out both options. Appreciate all the hard work, and pointing us in the right direction!

**Comment by asudoh** [comment]
@nicksarafa Pleasure to help!
