### ISSUE TITLE
Add support for narrow grid mode and update gutter classes

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6510]
We should implement the [narrow grid mode](https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#the-narrow-grid) in a similar way to our condensed grid mode. We should also update our gutter classes from `left` and `right` to `start` and `end` which are flipped for RTL.

**Comment by ZhiboMZhang** [comment]
Hi team, our implemention is currently blocked by missing this grid layout in carbon version 10.16.0. Anyone know when will this change get in a new release? Thanks!
