### ISSUE TITLE
Disabled SelectItem in Firefox: needs styling improvements

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#652]
@emmafull commented on [Fri Mar 09 2018](https://github.com/carbon-design-system/carbon-components-react/issues/703)

## Detailed description

> Describe in detail the issue you're having.

In Firefox, when a SelectItem is disabled it is missing the visual cue that it is disabled, like the light grey font color seen for disabled SelectItems in Chrome.

> Is this a feature request (new component, new icon), a bug, or a general issue?

General issue.

> Is this issue related to a specific component?

Yes, SelectItem.

> What did you expect to happen? What happened instead? What would you like to see changed?

When the SelectItem is disabled in Firefox it is unclickable but the text color remains the same as in enabled state. I expected to see the text for the SelectItem change to light grey like it does in Chrome. I'd like to see that behavior in Firefox.

> What browser are you working in?

Firefox 58.0.2 (64-bit)

> What version of the Carbon Design System are you using?

    "carbon-components": "~8.1.11",
    "carbon-components-react": "~5.4.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I'm working on a new offering and our early release will be available in 10 days.

## Steps to reproduce the issue

1. Implement a Select component with a disabled SelectItem and an enabled SelectItem.
2. View the UI in Firefox and Chrome.
3. Notice the disabled SelectItem is not visually distinguishable from the enabled SelectItem in Firefox, however, it is clear in Chrome.

**Comment by joshblack** [comment]
Following up on this, which component is this referring to? Having a hard time figuring out which one is `SelectItem`. Thanks!
