### ISSUE TITLE
Proposal for a overflow menu with a multiselect interaction

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6525]
### Summary

For use in toolbars, the proposal is for an icon button that reveals a dialog with a multiselect interaction inside of it. This feature request is for design and development.
![image](https://user-images.githubusercontent.com/40970507/88244034-0158b300-cc58-11ea-95f4-792d7d8187d4.png)

### Specific timeline issues / requests

This is a request from the IBMa team for immediate inclusion in an upcoming version of the Accessibility Checker tool

**Comment by joshblack** [comment]
Closing as we will use this issue as an umbrella for this use-case: https://github.com/carbon-design-system/carbon/issues/6633
