### ISSUE TITLE
Progress Indicator doesn't take up space vertically due to absolute positioning of secondary labels

### ISSUE THREAD

**Issue by bryanvpham** [carbon-design-system/carbon#6526]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Progress Indicator doesn't take up space vertically due to absolute positioning of secondary labels

> Describe in detail the issue you're having.

Progress Indicator doesn't take up space vertically due to absolute positioning of secondary labels so I have to adding custom padding/margins below but the problem is if you have long secondary labels and user window sizes, word wrapping makes the height less predictable.

> Is this issue related to a specific component?

ProgressIndicator

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Positioning is relative so thee full component takes up vertical space.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Use secondary label and add something after. Only primary label takes up space.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
https://codesandbox.io/s/white-cherry-nme5n?file=/index.js
- Notes

**Comment by tw15egan** [comment]
Could you try setting a `min-height` on the `bx--progress` container?  Removing the absolute positioning seems to cause quite a bit of issues with the component

**Comment by bryanvpham** [comment]
So I'm setting min height or padding on the labels as a temporary solution but it does have issues when resizing the window because if ur label is long it wraps and starts taking up extra lines of space and it's position attribute prevents it from growing it's parent div. 

I'm fine with it for my project, but I don't think that behaviour is desirable in general. I think the component should be reworked to take up space vertically correctly when features are enabled so people don't have to worry about floating text that also may or may not wrap.
