### ISSUE TITLE
inline loading within Modal component

### ISSUE THREAD

**Issue by apuzyrevsky** [carbon-design-system/carbon#6527]
- [x] `carbon-components` "10.12.0"
- [x] `carbon-components-react` "7.12.0"

## Summary
Hi guys, first of all, I want to say that I am using your design system in my project, which I really liked and want to say thank you for your work.
Right now I am working on adding inline loading to my solution and during the researching component, it's storybook and usage example I am wondering how can I add it to the existing modal window component considering that in modal window component I don't have access to the submit button itself, only for action onSubmit. Would be glad for any help, thank you.

**Comment by tw15egan** [comment]
@apuzyrevsky sorry for the late response, you are correct it does not seem possible as it currently stands. Just to clarify, you are trying to make the submit button behave similarly to [this example](http://localhost:9000/?path=/story/inlineloading--ux-example)?

**Comment by justindm234** [comment]
My team would also be interested InlineLoading support for Modal buttons (as seen [here](https://react.carbondesignsystem.com/?path=/story/inlineloading--ux-example))

**Comment by emyarod** [comment]
would integrating that inline loading UX example in a ComposedModal work for you?

**Comment by justindm234** [comment]
Hi @emyarod,
That would work for my team.

**Comment by emyarod** [comment]
awesome, and I think that would be the solution for this for the original issue submitter as well. Closing this unless there is a substantial reason for including this flow as an option in our default Modals
