### ISSUE TITLE
`0.1875rem*rem/px isn't a valid CSS value` causing module build failure.

### ISSUE THREAD

**Issue by RE-codes** [carbon-design-system/carbon#6534]
When attempting to perform a webpack build of a React app utilizing node-sass 4.14.1 and node 14.5.0 I receive this error:
```
ERROR in ./static/js/landing_app/app.scss
Module build failed: ModuleBuildError: Module build failed: 
  @return ($px / $base-font-size) * 1rem;
         ^
      0.1875rem*rem/px isn't a valid CSS value.
      in /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/@console/pal/vendor/carbon-components/scss/globals/scss/_typography.scss (line 30, column 11)
```

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
- Previous build was using node 12. Changed the `"engines": { "node": "~14.5.0" }. Updated local version of node to 14.5.0. Ran `npm install` and began receiving the above error. Deleted node_modules and package-lock.json and reran `npm install`. No change. Updated `carbon-components`, `carbon-components-react`, and `node-sass` one at a time and reran the build. No change. Unable to get a successful webpack build.

> Is this issue related to a specific component?
- The failure occurs when attempting to build our landing_app component which utilizes a `app.scss` file as noted above.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
- Expected webpack to build successfully.

> What version of the Carbon Design System are you using?
- Carbon 10. package.json is currently using 10.16. The working version of our app is utilizing node 12.16.1, carbon-components 10.9.3, carbon-compnents-react 7.10.3. We need to upgrade to node 14.5.0.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
- This is for IBM Cloud Cloud Foundry Enterprise Environment (CFEE). This is to fulfill a PSIRT due by July 31.

- Screenshots or code
```
ERROR in ./static/js/landing_app/app.scss
Module build failed: ModuleBuildError: Module build failed: 
  @return ($px / $base-font-size) * 1rem;
         ^
      0.1875rem*rem/px isn't a valid CSS value.
      in /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/@console/pal/vendor/carbon-components/scss/globals/scss/_typography.scss (line 30, column 11)
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/neo-async/async.js:8069:18)
    at options.error (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/node-sass/lib/index.js:294:32)
 @ ./static/js/landing_app/index.js 8:0-20

ERROR in ./static/js/landing_app/app.scss
Module build failed: ModuleBuildError: Module build failed: 
  @return ($px / $base-font-size) * 1rem;
         ^
      0.1875rem*rem/px isn't a valid CSS value.
      in /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/@console/pal/vendor/carbon-components/scss/globals/scss/_typography.scss (line 30, column 11)
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/neo-async/async.js:8069:18)
    at options.error (/Users/richeldridge/devFolder/github/cf-admin-ui/node_modules/node-sass/lib/index.js:294:32)
 @ ./static/js/landing_app/app.scss
 @ ./static/js/landing_app/index.js
```

- Notes

**Comment by tw15egan** [comment]
Is there somewhere in your code where you are trying to use the `rem` function with a `rem` value like:  `rem(1rem)`? 

I just tested locally by updating to Node `v14.6.0` and didn't see any errors, and everything loaded properly. However, I tested the error by changing a style from `rem(32px)` to `rem(2rem)` and I was able to generate the error you're seeing.

I'd start by searching your codebase for all instances of `rem(` and make sure you are only passing in `px` values.

**Comment by RE-codes** [comment]
Thanks for the reply. I did take a look at the file to which the error references (app.scss), and there were no instances of `rem(`. I will expand my search and see what pops up.

**Comment by tw15egan** [comment]
🤔  Might try doing a global search for `0.1875rem` as well, as that is what is being passed to the function

**Comment by RE-codes** [comment]
That pattern shows up in literally hundreds of places, but nowhere within our source code. All occurrences I could find are within node_modules: almost exclusively in carbon related components. Here is a list of every file within my node_modules directory that contains that pattern:
```
carbon-addons-cloud/css/styles.min.css
carbon-addons-cloud/css/styles.css
carbon-components/css/carbon-components.min.css
carbon-components/css/carbon-components.css
@carbon/charts/styles/vendor/carbon-components/css/carbon-components.min.css
@carbon/charts/styles/vendor/carbon-components/css/carbon-components.css
@console/pal-docs-components/node_modules/carbon-components/css/carbon-components.min.css
@console/pal-docs-components/node_modules/carbon-components/css/carbon-components.css
@console/pal/Connected/lib/ResourceTagArea/_styles.scss
@console/pal/Connected/lib/DataRetentionPanel/_styles.scss
@console/pal/Connected/ResourceTagArea/_styles.scss
@console/pal/Connected/DataRetentionPanel/_styles.scss
@console/pal/node_modules/carbon-components/css/carbon-components.min.css
@console/pal/node_modules/carbon-components/css/carbon-components.css
@console/pal/Components/TagArea/_styles.scss
@console/pal/Components/CatalogTile/_styles.scss
@console/pal/Components/lib/TagArea/_styles.scss
@console/pal/Components/lib/CatalogTile/_styles.scss
@console/pal/vendor/carbon-components/css/carbon-components.min.css
@console/pal/vendor/carbon-components/css/carbon-components.css
@console/pal/vendor/@carbon/charts/styles/vendor/carbon-components/css/carbon-components.min.css
@console/pal/vendor/@carbon/charts/styles/vendor/carbon-components/css/carbon-components.css
@console/pal/src/Connected/ResourceTagArea/_styles.scss
@console/pal/src/Connected/DataRetentionPanel/_styles.scss
@console/pal/src/Components/TagArea/_styles.scss
@console/pal/src/Components/CatalogTile/_styles.scss
@console/pal/src/vendor/carbon-components/css/carbon-components.min.css
@console/pal/src/vendor/carbon-components/css/carbon-components.css
@console/pal/src/vendor/@carbon/charts/styles/vendor/carbon-components/css/carbon-components.min.css
@console/pal/src/vendor/@carbon/charts/styles/vendor/carbon-components/css/carbon-components.css
```

**Comment by tw15egan** [comment]
Seems like you're pulling from @console/pal, perhaps the issue is with that package? I wasn't able to replicate the issue in our codebase when updating to node `14.5`

**Comment by RE-codes** [comment]
Thanks for checking. I'll see what I can come up with on the `pal` front. We can close for now.
