### ISSUE TITLE
Selectable Tile is not controllable

### ISSUE THREAD

**Issue by bryanvpham** [carbon-design-system/carbon#6537]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

SelectableTile has a `selected` field that's not respected.

> Is this issue related to a specific component?

SelectableTile

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect it to stay selected because you are forcing it to be selected by setting it to true but it doesn't. It seems like it's maintaining it's own state instead of listening to the "state" passed to it.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Add a selectable tile with `selected` starts of selected but if you click it no longer selected.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

https://codesandbox.io/s/sharp-swanson-qi0hl?file=/index.js

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Are you saying that if you pass down `selected`, you don't expect a user to be able to unselect that option?

**Comment by bryanvpham** [comment]
@tw15egan I want to be able to have full control over the component if I'm passing in a "selected" value and what happens when it's clicked. So the component should look selected (with the check) depending on if "selected" is true. So currently if I say the component is "selected" I believe it's maintaining its own state and only uses the "selected" value on initial setup. 

In the example code above, I expect when I try to deselect it will stay selected because I explicitly told the component it's selected.


So in my parent component I can have the state variable of say `selection`.

and I want to be able to do like

```html
<SelectableTile selected={this.state.selection === 'someValue'} handleClick ={() => { this.state({selection: 'someValue'})}} />
```

component only shows selected when I say it is and the handleClick is what  controls the selection changes.

**Comment by bryanvpham** [comment]
I expected it to work like dropdown:

https://react.carbondesignsystem.com/?path=/story/dropdown--fully-controlled

This has a `selectedItem` instead but when you don't pass this value, it will do every thing itself,  but if you tell it explicitly something is selected it will present itself that way and then you change use onChange to change what is selected.
