### ISSUE TITLE
Modal Overflow Indicator does not work with the enable-css-custom-properties feature flag 

### ISSUE THREAD

**Issue by kgibb** [carbon-design-system/carbon#6539]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The overflow gradient is not rendered when the `enable-css-custom-properties` feature flag is enabled. The CSS rule for the gradient has an invalid value.

```background-image: linear-gradient(to bottom, rgba(var(--cds-ui-01, #f4f4f4), 0), var(--cds-ui-01, #f4f4f4));```

`rgba` expects four arguments so will not work with the `var` syntax.

> Is this issue related to a specific component?

`Modal`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

As there is an issue using `transparent` as the start color in Safari, could another color custom property be added that has a `rbga` value? 

```
--cds-ui-01: #f4f4f4;
--cds-ui-01-transparent: rgba(244, 244, 244, 0);
```

```
-   background-image: linear-gradient(to bottom, $ui-01, $ui-01);
+   background-image: linear-gradient(to bottom, $ui-01-transparent, $ui-01);
```

> What version of the Carbon Design System are you using?

`10.14.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health - Application Framework

> Please create a reduced test case in CodeSandbox

Modal with scrolling content
https://the-carbon-components.netlify.app/?nav=modal

## Additional information

![image](https://user-images.githubusercontent.com/12196391/88381032-84cfec80-cd9d-11ea-92bb-48398997823b.png)

**Comment by emyarod** [comment]
related #4345 https://github.com/carbon-design-system/carbon/issues/4426

**Comment by yuriybelike** [comment]
Looks like this issue appears now in the docs site too: https://www.carbondesignsystem.com/components/modal/code/

The "With scrolling content" variant appears with no overflow indicator

![image](https://user-images.githubusercontent.com/60257988/151261506-6b3b6fa6-454c-485b-a489-5b69f2e10ef7.png)

**Comment by sstrubberg** [comment]
Is this still an issue?
