### ISSUE TITLE
src/components/form/_form.scss has unnecessary margin

### ISSUE THREAD

**Issue by AndySeymour2904** [carbon-design-system/carbon#654]
This CSS in /src/components/form/_form.scss;

.bx--form-item {
font-family: "ibm-plex-sans", Helvetica Neue, Arial, sans-serif;
flex: 1;
margin-right: 1rem;
margin-bottom: 1.5rem; }
.bx--form-item:last-of-type {
margin-right: 0;
margin-bottom: 0; }

Seems unnecessary and is actually counter-productive. I have to remove the margin, is there any use case which actually needs this CSS?

**Comment by alisonjoseph** [comment]
These margins were added to ensure there is correct spacing between form elements. You should be able to remove the class where you don't need the spacing or override the css as needed.
