### ISSUE TITLE
Determine how feasible it would be to use MDX for our storybook and for code pages on site

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6548]
We currently are torn between authoring MDX on the site and storybook. This issue is for evaluating how feasible it would be to author MDX for our components in storybook and use or transform it, to work on the site.

Challenges

- How do we automatically generate prop tables for the site?
- How do we use tools like `remark` to change the AST of a story from storybook to one that works for our site?

**Comment by alisonjoseph** [comment]
After team discussion decided to keep docs in storybook and link out to them from the website. not worth time/effort to duplicate / import content currently.
