### ISSUE TITLE
ui shell/left pane seems to have the wrong color in Carbon Gray 90

### ISSUE THREAD

**Issue by myan9** [carbon-design-system/carbon#6558]
Hi! I found the ui shell/left pane has the same color theme in Carbon Gray 10 and 90, e.g. the font-color is dark and the background color of selected Sub-menu Item is light. I wonder why the colors in Gray 10 and 90 are not inverted. Is this intended? Thanks!

**Comment by AlanGreene** [comment]
I think this is covered by https://github.com/carbon-design-system/carbon/issues/4839

I used the styles referenced in that issue to override the colours for use in my app. Hopefully the Carbon team will add theming support to the UI shell components soon so we can remove our custom overrides 🤞

**Comment by tw15egan** [comment]
Theming is not currently supported for the UI shell as it stands today but will be fixed when #4839 is prioritized.
