### ISSUE TITLE
Update components to work in new Storybook setup

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6562]
As mentioned in: https://github.com/carbon-design-system/carbon/pull/6532, the new storybook settings brought up a couple of issues with the following components that need to be resolved:

- [x] Components that don't have a displayName or prop types picked up by addons-docs
  - [x] NumberInput
  - [x] [OverflowMenu](https://github.com/carbon-design-system/carbon/issues/7169)
  - [x] RadioButton
  - [x] TextInput
  - [x] [Tooltip](https://github.com/carbon-design-system/carbon/issues/7168) - this issue mentions some storybook updates needed for `Tooltip` & `Forms`: https://github.com/carbon-design-system/carbon/issues/7164
- [x] Components that render prop type comments with HTML
  - [x] TextArea
  - [x] RadioTile
  - [x] Button.Skeleton
  - [x] Button
  - [x] Copy
  - [x] CopyButton
  - [x] FileUploader
  - [x] FileUploaderDropContainer
  - [x] Link
  - [x] ListItem
  - [x] ProgressIndicator
  - [x] RadioButton
  - [x] RadioButtonGroup
  - [x] Search
  - [x] Select
  - [x] Tab
  - [x] ControlledPasswordInput
  - [x] PasswordInput
  - [x] TextInput
  - [x] TileGroup
  - [x] TimePicker
  - [x] Toggle.Skeleton
  - [x] Toggle
  - [x] ToggleSmall
  - [x] HeaderMenuItem
  - [x] HeaderName
  - [x] HeaderPanel
  - [x] SideNav
  - [x] SideNavDetails
  - [x] Switcher
  - [x] SwitcherDivider
  - [x] SwitcherItem
  - [x] UnorderedList
- [x] Stories that do not work
  - [x] ToggleSkeleton
  - [x] ToggleSmallSkeleton

**Comment by tw15egan** [comment]
Just verified that the outstanding components now have working prop tables
