### ISSUE TITLE
Datatable's page selector icon overlaps with the page number in FF

### ISSUE THREAD

**Issue by chubbywhale** [carbon-design-system/carbon#657]
[Title]: Datatable's page selector icon overlaps with the page number in FF

When viewing the datatable with pagination page selector in Firefox, will notice that the icon (triangle) beside the number will overlap with the current page number.
The issue is noticable on both Mac and Windows.
It looks well on Chrome though.

Even the sample on the carbon-components.com site is having the issue:
http://carbondesignsystem.com/components/data-table/code

It looks worst when the current page number is two (or more) digits...

![image](https://user-images.githubusercontent.com/37340587/37423382-0fbba54e-2794-11e8-8ee5-fc7a285732a6.png)

**Comment by joshblack** [comment]
Going to close this due to inactivity, and also I believe this was addressed in recent updates. There are still some style inconsistencies with Pagination, but I think there are other issues left to tackle those. Let me know if this isn't the case, and feel free to re-open!
