### ISSUE TITLE
Icons: Many 16px icons are blurry on non-high-density screens

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6575]
Since icons are designed on a 32px base grid with 2px stroke width, the downsized 16px versions (which are most common in the UI) often have trouble since the (then 1px thick) stroke is rendered in between pixels. Any screen that is not high-density (like MacBook retina screens) displays these icons blurry by trying to render a part of the stroke on each adjacent pixel.

<details>
<summary>Some examples (display's pixel density: 117ppi)</summary>

![image](https://user-images.githubusercontent.com/28265588/88796104-686af000-d1a1-11ea-97aa-774f1ea1c86d.png)
![image](https://user-images.githubusercontent.com/28265588/88796114-6f91fe00-d1a1-11ea-836f-2e89e18a9c51.png)
![image](https://user-images.githubusercontent.com/28265588/88796130-74ef4880-d1a1-11ea-8d4d-c8ab405ba0d0.png)
![image](https://user-images.githubusercontent.com/28265588/88796161-833d6480-d1a1-11ea-9e7f-3c80ec2bd4f6.png)
![image](https://user-images.githubusercontent.com/28265588/88796184-8cc6cc80-d1a1-11ea-8561-5de9a3649d85.png)
![image](https://user-images.githubusercontent.com/28265588/88796220-99e3bb80-d1a1-11ea-893c-9bbfe43017d8.png)
![image](https://user-images.githubusercontent.com/28265588/88796255-a536e700-d1a1-11ea-9a99-9477de319d00.png)
![image](https://user-images.githubusercontent.com/28265588/88796312-b7b12080-d1a1-11ea-82cf-4290142002c4.png)
![image](https://user-images.githubusercontent.com/28265588/88796366-c992c380-d1a1-11ea-91ea-634e7589013a.png)
![image](https://user-images.githubusercontent.com/28265588/88796424-e4653800-d1a1-11ea-9049-406fd50a73c9.png)
![image](https://user-images.githubusercontent.com/28265588/88796438-e8915580-d1a1-11ea-9e09-3b634bb1e175.png)
![image](https://user-images.githubusercontent.com/28265588/88796450-ef1fcd00-d1a1-11ea-90b7-29e600dda962.png)
![image](https://user-images.githubusercontent.com/28265588/88796467-fcd55280-d1a1-11ea-8521-b5356113b418.png)
![image](https://user-images.githubusercontent.com/28265588/88796622-41f98480-d1a2-11ea-8eda-3f9d89239e0f.png)

</details>

On a dark background it's sometimes even more noticeable. 
![image](https://user-images.githubusercontent.com/28265588/88796806-93097880-d1a2-11ea-8dd4-c0cd0aade138.png)

**Comment by joshblack** [comment]
cc @conradennis if you have a sec!

**Comment by hugo-dlb** [comment]
Very striking on my Full HD monitor.
![image](https://user-images.githubusercontent.com/3577405/95390258-6639b600-08f5-11eb-8353-83b090d772fc.png)

**Comment by joshblack** [comment]
@conradennis @janhassel  I know over in #6245 there was some conversation around what we could do for this type of issue, is there anything similar we can do for icons or is this basically a "won't fix" based on brand guidelines? 🤔
