### ISSUE TITLE
[Dropdown] Including a way to remove selection for optional dropdowns 

### ISSUE THREAD

**Issue by dianasanborn** [carbon-design-system/carbon#6581]
### Summary

There is a need for users to have a way to clear the selection for **optional** dropdowns. 

**For example:** 
If a user made a selection on an optional field, but wanted to remove the selection and keep it blank.

We are looking to include a "Select" option in the dropdown to allow the user to revert back to a _null_ option, but would love the Carbon team's thoughts on this as well. 

<img width="623" alt="Screen Shot 2020-07-29 at 2 40 41 PM" src="https://user-images.githubusercontent.com/43549567/88839768-7de41800-d1a9-11ea-9018-e79e91785d47.png">

It would be helpful if this guidance was also included in the [dropdown component](https://www.carbondesignsystem.com/components/dropdown/usage) as well.

**Comment by AlexanderLyon** [comment]
@tw15egan @laurenmrice I'd like to take a stab at this enhancement if nobody else is already on it!

Would this also require a new `optional` prop? I don't currently see any existing functionality in the docs to make this component optional

**Comment by tw15egan** [comment]
@AlexanderLyon Awesome! I'll let @laurenmrice chime in with design / UX specs for you to follow. 

I'm thinking we'd want this functionality to be tied to a new prop. Based on our WIP naming conventions for our next major release, I think this new prop would make sense as `isOptional`. 

@joshblack What do you think?

**Comment by AlexanderLyon** [comment]
I opened a PR in the meantime with one possible solution for this, but I'd love some feedback if there's some more detailed specs to be followed!

**Comment by laurenmrice** [comment]
We are going to use Dianas UX approach. (this has been tested with user research)

Here is the spec below @AlexanderLyon :

![dropdown (optional)](https://user-images.githubusercontent.com/43969356/102382185-c43ae780-3f8f-11eb-82e5-125b23b0a6e2.png)

**Comment by laurenmrice** [comment]
@joshblack created a [Codesandbox](https://codesandbox.io/s/optimistic-glitter-mpizz?file=/src/index.js) that demonstrates that we can achieve this implementation with our current codebase. A prop won't be needed.
