### ISSUE TITLE
[DataTable]: Disabled batch action buttons are visually too prominent

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6588]
## Detailed description

> Describe in detail the issue you're having.

When a button in the data table batch action bar is disabled, it draws the user's attention more than the actions they are able to perform. Also it looks a bit out-of-place in general and might be confusing to the user since the background color is close to the "selected row" background color.

> Is this issue related to a specific component?

`DataTable.TableBatchAction`

> What version of the Carbon Design System are you using?

`carbon-components@10.16.0`
`carbon-components-react@7.16.0`

## Steps to reproduce the issue

1. Open demo: https://6t41j.csb.app/
2. Select at least one row

## Additional information

![image](https://user-images.githubusercontent.com/28265588/88920619-6ff7cb00-d26d-11ea-86d9-de9226d3f5b7.png)

It seems there is also an inconsistency in the text color compared to the sketch kit, although that's not the issue I think. 😄 

![image](https://user-images.githubusercontent.com/28265588/88920658-80a84100-d26d-11ea-99ee-231c5c83054c.png)

**Comment by janhassel** [comment]
@laurenmrice Seems like the inconsistency between spec and implementation was fixed in the linked PR. My concern was actually about the visual appearance though as I think the disabled action stands out as the most prominent one which seems counter-intuitive.

Can we re-open this issue?

**Comment by laurenmrice** [comment]
Reopening to explore visual design of disabled button in the batch action table bar

**Comment by aagonzales** [comment]
This has recently come up again in Slack. We agree the disabled button is too prominent here. The recommendations from the Carbon designers is that we make a custom disabled button here for the table batch action bar. Here are the two options. Neither has any good token options unfortunately. 

![image](https://user-images.githubusercontent.com/11670886/132416547-7d087ef4-afd0-4ab1-8a52-e279d416aefd.png)

**Comment by jnm2377** [comment]
Added this to our backlog since the enhancement has been accepted w/ design specs provided. I am not sure when this will be prioritized, but until it has been included, the current workaround for anyone running into this issue would be to override disabled styles w/ the proposed changes.
