### ISSUE TITLE
[DataTable]: Expansion clickable area is not up to specification

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6589]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

According to the [DataTable guidance on the Carbon website](https://www.carbondesignsystem.com/components/data-table/usage#interactions), the clickable / interactive area to expand a row is a square filling the entire height of the row, meaning with the default row height of 48px, the clickable area is 48px by 48px.

Currently in react implementation, this interactive area is 16px by 16px.

> Is this issue related to a specific component?

`DataTable.TableExpandRow`

> What browser are you working in?

Chrome 84

> What version of the Carbon Design System are you using?

`carbon-components@10.16.0`
`carbon-components-react@7.16.0`

## Steps to reproduce the issue

1. Visit react storybook (https://react.carbondesignsystem.com/?path=/story/datatable--with-expansion)
2. Try to click "around" the chevron

## Additional information

Click targets according to Carbon website:
![image](https://user-images.githubusercontent.com/28265588/88924125-1a262180-d273-11ea-9d86-14d11ea8c300.png)

Screen recording of react storybook:
![Screen Recording 2020-07-30 at 14 44 03](https://user-images.githubusercontent.com/28265588/88924248-480b6600-d273-11ea-880e-9246ea7f6285.gif)

**Comment by tw15egan** [comment]
@emyarod are you still working on this?

**Comment by emyarod** [comment]
yes still WIP after getting updated spec
