### ISSUE TITLE
Incorrect style for disabled items in OverflowMenu when hover.

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#659]
@Chengxuan commented on [Thu Mar 15 2018](https://github.com/carbon-design-system/carbon-themes/issues/32)

## Detailed description
Hovering on a disabled item in OverflowMenu component uses the same style as on an enabled item:
![tile-disabled](https://user-images.githubusercontent.com/5425125/37471595-126866a0-2862-11e8-9bee-ad0b9b1d0b4a.png)

In the image above, both `Edit` and `Delete` option are disabled in the menu and the cursor is hovering on `Delete`.

---

@aagonzales commented on [Thu Mar 15 2018](https://github.com/carbon-design-system/carbon-themes/issues/32#issuecomment-373437487)

Changes needed:
- [ ] Dev task: remove hover backgrounds from disabled item in menu. Add `not-allowed` cursor should be used/added to the disabled items on hover.
- [ ] Design task: re-evaluate system text disabled state. Decrease opacity more?

**Comment by alisonjoseph** [comment]
Believe this was taken care of in this PR https://github.com/carbon-design-system/carbon-components/pull/699
