### ISSUE TITLE
Add extra prop to Switch component which can disable it

### ISSUE THREAD

**Issue by marekdano** [carbon-design-system/carbon#6594]
### Summary

We use Switch with ContentSwicher and we have a case when we need to disable one of the switches depending on some conditions. 
We checked the doc and there is no prop in the Switch component for disabling the switch. It'll be very useful for us if the disabled prop is available in the component.

**Comment by emyarod** [comment]
even though it isn't explicitly documented in the Switch proptypes, the `disabled` prop should already be working as expected since it is spread into the underlying button element

**Comment by marekdano** [comment]
That's great. Thanks for adding it to the doc.
