### ISSUE TITLE
How to import Search component from carbon components into react code?

### ISSUE THREAD

**Issue by KruthikaMalyala** [carbon-design-system/carbon#660]
I want to use the 'Search' component of carbon design system in a react application.
I have done this earlier with a DataTable. But i dont wanna use this search bar for a table now.
I'm trying to import the component in the following way

 import Search from 'carbon-components-react'

But the error i'm getting is the following one.

"export 'default' (imported as 'Search') was not found in 'carbon-components-react'

I really need help here!

**Comment by tw15egan** [comment]
Can you try `import { Search } from 'carbon-components-react'`?

**Comment by KruthikaMalyala** [comment]
@tw15egan It is working!!
Thanks a lot :)

**Comment by tw15egan** [comment]
Great! Glad I could help 😄
