### ISSUE TITLE
Tooltip is not showing text when in modal

### ISSUE THREAD

**Issue by kz4151** [carbon-design-system/carbon#6601]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When I'm using a tooltip in a modal, I noticed that the text does not show when I click on the tooltip icon as shown below:

![Screen Shot 2020-07-31 at 4 45 14 PM](https://media.github.ibm.com/user/149566/files/51690100-d34d-11ea-8b01-3162b76fb8dd)

Tooltip shows up fine though when it's not in a modal. I'm thinking that it's possibly a z-index issue. 

> Is this issue related to a specific component?

`Tooltip`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Tooltip text should show when being clicked in modal. 

> What browser are you working in?

Google Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "10.16.0",
"carbon-components-react": "7.16.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

`IBM Cloud Catalog`

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by kz4151** [comment]
Hi. I created a similar scenario here with a sandbox: https://3he8m.csb.app/ 
Try clicking on the tooltip. The text does not show. Let me know if you need anymore information.

**Comment by emyarod** [comment]
when I move your code sandbox example into storybook the issue does not appear, so I think this definitely is a z-index issue although I am still looking into why the example appears different in the storybook vs code sandbox environment. (but a quick  temporary workaround in the meantime would be to increase the z-index value of the tooltip)

**Comment by kz4151** [comment]
Hi. Yea that's what I'm doing for now as a temporary workaround.

**Comment by tw15egan** [comment]
Tested running this in our local storybook and also working as expected. Not sure why CodeSandbox is having a problem, but going to close this as resolved.

**Comment by kz4151** [comment]
Hi. It's not only CodeSandbox that is having this problem. Our app that uses this component also has this issue. Can we reopen this issue?

**Comment by kz4151** [comment]
We have a workaround for now (increasing the z-index value) for the tooltip but would like a permanent solution.
