### ISSUE TITLE
Combo box: Selection by default

### ISSUE THREAD

**Issue by granall** [carbon-design-system/carbon#6619]
### Summary

The Sterling Fulfillment Optimizer team is using the combo box component to filter a data table. The first option in the combo box, the aggregate of all store data, is selected by default. From there, users can open the combo box to search and select specific stores. The data would then refresh to show stats specific to that store.

The issue we are having is that the "X" is visible when the default option (the aggregate) is selected. Nothing happens when the user selects "X" because it's already in the default state. [See video](https://ibm.box.com/s/e5dx9r4qaof6949o9g2g31p5yw0v4sdl)

I am asking for development.

### Justification

It's a confusing user experience to have the "X" present when the combo box is already in its default state. 

### Desired UX and success metrics

What happens today (as-is):
The "X" shows by default because the default selection (the aggregate) is selected. Selecting "X" has no outcome.

The ideal experience as discussed by the SFO team (to-be):
Remove the "X" by default because it doesn't have a functional purpose. It can cause confusion for the user. 

### "Must have" functionality

Our ideal would be to remove the "X" when there is a default selection.

### Specific timeline issues / requests

It has been releases as-is, so preferably sooner rather than later. 

### Available extra resources

There might be development resources from SFO that could help, but I'd have to reach out to Chetan Jadhav to verify. There are two SFO UX designers that could help if needed. 

Note: This issue was originally raised in [Carbon Angular #1430
](https://github.com/IBM/carbon-components-angular/issues/1430)

**Comment by tw15egan** [comment]
Do you have any screens or flows that you could share with @carbon-design-system/design to ensure this is a valid pattern?

The `X` can be hidden via CSS in the interim if needed

**Comment by granall** [comment]
@tw15egan is the video referenced above enough to show the use case?

**Comment by tw15egan** [comment]
Does the ComboBox search/filter on non-matching results?

**Comment by aagonzales** [comment]
This is interesting. I'm curious how normal it is to have a x trigger a reset to default vs clearing all selection. I wonder if that would be confusing to user. I guess removing the x would make it clearer they can't clear the default values.

**Comment by granall** [comment]
> Does the ComboBox search/filter on non-matching results?

@tw15egan
 For our purposes, the search/filter would only return matching results. 


> This is interesting. I'm curious how normal it is to have a x trigger a reset to default vs clearing all selection. I wonder if that would be confusing to user. I guess removing the x would make it clearer they can't clear the default values.

@aagonzales 
The scenario that led us to this solution: "Store aggregate" appears by default —> user selects "StoreA" —> user clears "StoreA" —> auto-select "Store aggregate" (default) for the user. Having an X to clear the default wouldn't make sense because an option has to be selected in order to see data. 

 I could definitely see "clearing all sections" working, but I don't think it'd be as valuable of an experience.

**Comment by chrisconnors-ibm** [comment]
A combo box is a text entry field that can take any entered value, with an accompanying menu that has a list of proscribed values. If the user types characters contained within the values in the proscribed list of values, the focus moves to that value on a per character basis. the list of values is not 'filtered' or shortened.

Can a user type any value there? or only pick from the items in the menu. In your video what happens if they type "Bananas Foster"? (A combo box should take the input value, but the table would only show results containing "Bananas" within the scope of the search, which honestly I couldn't tell from the video, since the Menu values were not column headings, or field values in the table).

**Comment by chrisconnors-ibm** [comment]
If arbitrary values aren't required (or actually supported) have you considered just using a menu here? you would still get the type to value of menu item behavior without the "clear the field" baggage a combo box requires.
