### ISSUE TITLE
Add interaction option for selecting row in data table

### ISSUE THREAD

**Issue by rgblee** [carbon-design-system/carbon#6621]
### Summary

Currently, rows in the data table component allow selection by clicking the checkbox. However, teams from CPD services such as WKC and WS would like the additional option to select the row by hovering and then clicking on it.

### Justification

Currently, the row enters a hover status when the cursor is on it. Selecting the row requires the user to move the cursor to the left to find the checkbox.

### Desired ux and success metrics
The desired ux is for the users to be able to select the the row by clicking on the empty space of a row. This is without having to find the checkbox. We argue that this is an understandable enhancement since an obvious next step to reading the content of a row is to select it. This is in addition to existing checkbox selection functionality.

### “Must have” functionality
The functionality described above is simply an enhancement to the hover state by adding interactivity. This would exist alongside checkbox selection functionality. Clicking the empty space of a selected row would unselect it.
 
### Specific timeline issues / requests
Services have already implemented this or are targeting their fall releases for it. We would like for it to be formally recognized by carbon as an option for compliance reasons.

**Comment by andreancardona** [comment]
We are accepting the proposal - however, there cannot be any interactive elements within the selected row. @rgblee

**Comment by sstrubberg** [comment]
From Backlog Grooming call:

This feels like an edge-case and not appropriate for core Carbon. There are also accessibility con  Also accessibility concerns around the interactions with the rows.
