### ISSUE TITLE
[Pagination] The footer should be singular if only one item/page

### ISSUE THREAD

**Issue by amberfeinerman** [carbon-design-system/carbon#6624]
## Detailed description

> Describe in detail the issue you're having.

An [issue was raised](https://github.ibm.com/ibmcloud/security-compliance/issues/1273) in my product team's repo regarding the pagination footer showing `items` if there was only one item and `pages` if there was only one page. I confirmed in lines [148](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Pagination/Pagination.js#L148) and [312](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Pagination/Pagination.js#L312) in `Pagination.js` that it was a Carbon issue.

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Add conditional logic so that if `max === 1` or `totalPages === 1` the singular version of their noun shows.

## Additional information
![Screen Shot 2020-08-05 at 11 22 02 PM](https://user-images.githubusercontent.com/8129061/89490421-7b1d9000-d772-11ea-93da-955d9d76dd8c.png)

**Comment by emyarod** [comment]
as an FYI this can be resolved by passing in a custom `pageRangeText` function to handle the grammatical changes (which would be necessary for any i18n efforts anyway)
