### ISSUE TITLE
IE11 Bug - Modal content overflow when max-height on parent is reached

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#663]
@Noodles006 commented on [Sun Mar 18 2018](https://github.com/carbon-design-system/carbon-components-react/issues/722)

Step to reproduce:

1. Open http://www.carbondesignsystem.com/components/modal/code
2. Narrow down the height of the window
3. Click a `Transactional Modal`
4. You will see part of the modal is overlaped 

![1](https://user-images.githubusercontent.com/8025633/37576957-f7737dcc-2b26-11e8-962b-5254f1d1d2da.png)

---

@joshblack commented on [Mon Mar 19 2018](https://github.com/carbon-design-system/carbon-components-react/issues/722#issuecomment-374292700)

Hi @Noodles006! 👋 Thanks so much for taking the time to make this issue. Going to move this over to `carbon-components` since that's where the styles are defined.

**Comment by Noodles006** [comment]
@joshblack Is anyone looking at this issue now?

**Comment by joshblack** [comment]
Hi @Noodles006, currently we haven't had time to evaluate this due to a two sprint effort that the core team is going through. We are definitely open to accept PRs that fix bugs in the meantime in order to make sure that changes can make it through when needed 😄

**Comment by alisonjoseph** [comment]
Spent some time looking into this. This has to do with a flexbox bug(s) in IE11 and overflow not rendering correctly. Strangely if you resize the browser the styles fix themselves. I haven't been able to find a workaround that fixes this.

Possible Workaround (not ideal)
-Hard code a height/max-height on to .bx-modal-content

Possible fix
-Complelety refactor the modal styles to find a way to not use flexbox

**Comment by colingm** [comment]
Is this related to seeing behavior like the below image when you either have too much overflow in the content or just a short window and buttons are pushed off the modal?

![image](https://user-images.githubusercontent.com/11670266/43174674-fa32e944-8f80-11e8-9c50-1f3e1bf053dd.png)

**Comment by alisonjoseph** [comment]
@colingm Is your issue only happening in IE11?

**Comment by colingm** [comment]
@alisonjoseph No this is an issue in Chrome even just on main storybook

**Comment by alisonjoseph** [comment]
This issue I believe is only related to IE11, do you mind opening a new issue outlining what you are seeing with steps to reproduce? Thanks!

**Comment by colingm** [comment]
@alisonjoseph Of course! just wanted to check before throwing another issue on there 😄

**Comment by enakatani** [comment]
@alisonjoseph Any plan to fix this bug?

**Comment by asudoh** [comment]
@enakatani While we don't have immediate plan to fix this issue, applications can do style adjustments, etc. to meet the requirements for specific applications. The closest I have is https://github.com/IBM/carbon-components/compare/master...asudoh:bring-back-tall-modal, though the code hasn't reached to the point that works for all applications/platforms. Thanks!
