### ISSUE TITLE
Disclosure Component

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6633]
We've seen a use-case crop up for a generic component that combines a trigger and a pop-up to enable a variety of use-cases. This primitive can be used by teams to build a variety of accessible functionality in their product.

At its core, this component would have two pieces:

- A trigger that the user interacts with by clicking or using their keyboard to disclose the content of the component
- A pop-up that contains the content 

Depending on the type of content, it may be useful for the pop-up to contain a way to close the pop-up (like a `X` present in a modal). Similarly, focus may need to be placed on the first item for certain cases like in a dialog pattern.

In terms of focus order, the content in the pop-up should appear **after** the trigger. This means that a user can do the following:

- Tab to the trigger
- Press spacebar
- Press tab to go into the content of the pop-up
- Press tab to get out of the content of the pop-up (note: this does not dismiss the pop-up)

2021 Release: 
- Accessibility Primitives:[ Disclosure](https://github.com/carbon-design-system/carbon/issues/8293)

**Comment by joshblack** [comment]
As an example, GitHub uses this pattern across their site to drive the following parts of their experience:

**Nav menus**

![image](https://user-images.githubusercontent.com/3901764/89581394-83baa880-d7fc-11ea-87f3-6c948f53ae1f.png)

**Disclosure buttons**

![image](https://user-images.githubusercontent.com/3901764/89581441-992fd280-d7fc-11ea-9164-faef50d0622e.png)

**Branch switcher**

![image](https://user-images.githubusercontent.com/3901764/89581455-a056e080-d7fc-11ea-80bd-0f166c5160ca.png)

This pattern includes nested components like a combobox and content switcher / tabs

**Action buttons**

For cases like sorting

![image](https://user-images.githubusercontent.com/3901764/89581510-b9f82800-d7fc-11ea-969d-e046994334ad.png)

Or filtering

![image](https://user-images.githubusercontent.com/3901764/89581652-f4fa5b80-d7fc-11ea-91c9-81a31b5fadb5.png)

**Comment by janhassel** [comment]
Are there any plans on pursuing this? I've seen a lot of teams using an OverflowMenu to achieve such interfaces which mostly results in invalid HTML (by not using `<li>` as direct children of `<ul>`) and comes with considerable accessibility violations.

I think a component like this which would allow for a wider range of use cases is desperately needed.

**Comment by joshblack** [comment]
@janhassel yes! 100%. I think the plan is to see if we can get it into the next sprint and tackle the exact case that you mentioned.

Let me know if you want to help out at all with it! Happy to loop you in on any conversations if you're interested 😄

**Comment by laurenmrice** [comment]
<img width="443" alt="Screen Shot 2021-01-25 at 1 12 13 PM" src="https://user-images.githubusercontent.com/43969356/105767906-44565480-5f21-11eb-8cf6-d0cc36413abb.png">
<img width="414" alt="Screen Shot 2021-01-25 at 1 13 29 PM" src="https://user-images.githubusercontent.com/43969356/105767914-45878180-5f21-11eb-8d19-58011d82bfb0.png">

**Comment by joshblack** [comment]
@janhassel just a heads up, we have a related component to this (Popover) that will be used in conjunction with the Disclosure component. Let me know if you want to help us test it out!

**Comment by laurenmrice** [comment]
# Design specs
## Icon button
![Disclosure — Icon button](https://user-images.githubusercontent.com/43969356/118216938-0b8fac00-b43a-11eb-8d36-e53cf2d7e214.png)

## Text
![Disclosure — Text](https://user-images.githubusercontent.com/43969356/118216986-311cb580-b43a-11eb-946b-9f4df85f04c8.png)

## Menus
![Disclosure — Menus](https://user-images.githubusercontent.com/43969356/118217055-53163800-b43a-11eb-8c11-9d9d1db8d697.png)

## Dismissable
![Disclosure — Dismissable](https://user-images.githubusercontent.com/43969356/118217166-8658c700-b43a-11eb-808e-3f2bf04cc6a7.png)

**Comment by laurenmrice** [comment]
## Avatar example
![Disclosure — Avatar](https://user-images.githubusercontent.com/43969356/118217379-f7987a00-b43a-11eb-94c4-32b279f79b95.png)

## Text button
![Disclosure — Button with text](https://user-images.githubusercontent.com/43969356/118219994-37159500-b440-11eb-8de6-0784e5b8fc8e.png)

![Disclosure — Combo button](https://user-images.githubusercontent.com/43969356/118220001-3a108580-b440-11eb-989a-ce9a3bc758d5.png)

## Settings
TBD - still refining design
