### ISSUE TITLE
Contribution: Keybase Logo

### ISSUE THREAD

**Issue by Jerome1337** [carbon-design-system/carbon#6635]
#### 1. Team name

N/A

#### 2. Icon name

Keybase Logo

#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.

Monochrome Keybase Logotype

#### 4. Box Link

https://drive.google.com/file/d/1lFRSl1QimaUQKKotuLJybI6zXiNgix3c/view?usp=sharing

#### 5. Screen Shot

Please add the following screen shots to this issue:

1.  Close-up screen shot of the icon with the pixel grid turned on

![image](https://user-images.githubusercontent.com/7968649/89524687-4bf43680-d7e5-11ea-834e-f03fa580d527.png)

2.  Screen shot of the icon in context with your use case.

![image](https://user-images.githubusercontent.com/7968649/89534677-9da4bd00-d7f5-11ea-8a24-24dd58acb871.png)

**Comment by joshblack** [comment]
cc @conradennis @laurenmrice

**Comment by conradennis** [comment]
found the source SVG for the logo and scaled it to fit the 32px grid:

<img width="682" alt="Screen Shot 2020-08-13 at 12 02 10 PM" src="https://user-images.githubusercontent.com/16782944/90158313-dc3df880-dd5c-11ea-8b18-a7a8ed7e0419.png">

**Comment by conradennis** [comment]
here's the SVG, will include it with the next batch of icons I add to the repo

[logo--keybase.svg.zip](https://github.com/carbon-design-system/carbon/files/5070148/logo--keybase.svg.zip)

**Comment by conradennis** [comment]
@joshblack we can close if everything looks ok to you

**Comment by Jerome1337** [comment]
@ConradSchmidt Do you have an ETA for the next batch of icons?
