### ISSUE TITLE
ModalWrapper causes issues when inside of TableToolbarContent

### ISSUE THREAD

**Issue by dhebert-dev** [carbon-design-system/carbon#6646]
When ModalWrapper is placed inside of TableToolbarContent it causes issues with the blue bar that appears when batch rows are selected. This is an ideal spot for us to place ModalWrapper. If we use a regular button to trigger ModalWrapper it will still cause the same issue. If we use a button to trigger Modal rather than ModalWrapper we lose some of the functionality that ModalWrapper has. For example, we lose the cancel button functionality.

**Comment by tw15egan** [comment]
Could you provide a reproducible example via [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox
) so we can help debug and figure out a solution? Thanks!
