### ISSUE TITLE
IE 11 Bug: ellipsis not showing when text-overflow: ellipsis with ibm-plex-sans font

### ISSUE THREAD

**Issue by flyHe** [carbon-design-system/carbon#665]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

a long name should be hidden with ellipsis, but ellipsis was not showing in IE11, and I found the `ibm-plex-sans` font make the ellipsis in mess, if I remove the `ibm-plex-sans`, it worked as normal

> Is this issue related to a specific component? 

no
> What did you expect to happen? What happened instead? What would you like to see changed?

ellipsis should be shown in IE11 with long name when `text-overflow: ellipsis `

> What browser are you working in? 

IE 11

> What version of the Carbon Design System are you using? 

"carbon-components": "^8.10.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

`ibm-plex-sans`
<img width="830" alt="screen shot 2018-03-20 at 4 31 44 pm" src="https://user-images.githubusercontent.com/10543919/37643701-62710140-2c5c-11e8-9365-02f930d61d7f.png">
<img width="1017" alt="screen shot 2018-03-20 at 4 32 12 pm" src="https://user-images.githubusercontent.com/10543919/37643702-62a560de-2c5c-11e8-9001-54aa74afdc71.png">

Without `ibm-plex-sans`
<img width="925" alt="screen shot 2018-03-20 at 4 36 47 pm" src="https://user-images.githubusercontent.com/10543919/37643880-ecb8b492-2c5c-11e8-91d6-9d754e921ecd.png">

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
Is this a problem with the font itself? If so, it may be better to open an issue here: https://github.com/IBM/plex

**Comment by flyHe** [comment]
@tw15egan I am not sure if this is an issue with the font itself, the font is imported by carbon using `$css--plex: true;`, and I also have opened a same issue in https://github.com/IBM/plex/issues/150

**Comment by flyHe** [comment]
a related issue https://github.com/IBM/plex/issues/110,

**Comment by alisonjoseph** [comment]
closing, fix included in this PR https://github.com/IBM/plex/pull/160

**Comment by damorossi** [comment]
this is not a font matter
