### ISSUE TITLE
Rendering dynamic content in DataTable

### ISSUE THREAD

**Issue by maxjowett** [carbon-design-system/carbon#6655]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

I'm having trouble figuring out how to conditionally render content inside rows in a `DataTable`. A super simple example to illustrate my point - say the row data I have looks something like this:

```
const rows = [
  { id: 1, task: 'Mow lawn', complete: false},
  { id: 1, task: 'File ticket', complete: true}
]
```

In the table I'd like to be able to conditionally render a `Tag` for each complete value. As far as I can tell, I pass the rows to DataTable like so:

```
<DataTable rows={rows} />
```

further into the DataTable component looks something like:

```
{rows.cells.map(cell => (
  <TableCell>{cell.value}</TableCell>
))}
```

How can I programmatically look at `cell.value` to render some content conditionally?

**Comment by tw15egan** [comment]
Haven't tested this, but could you check inside of the `map`?

```jsx
{rows.cells.map(cell => {
   if (cell.value === "foo") {
      return  <TableCell>{cell.value}</TableCell>
   } else {
      return  <TableCell>{cell.value}<Tag /></TableCell>
   }
}))}
```

**Comment by maxjowett** [comment]
Thanks @tw15egan for the quick response..

I think I did a poor job explaining my problem. So I'll take a stab at a better example: say I am trying to render the following JSON in `DataTable`:

```
const rows = [
  {foo: 'bar', baz: 1, complete: false, inProgress: true},
  {foo: 'bar', baz: 1, complete: true, inProgress: false},
]
```

When there are multiple columns rendering boolean values, you could imagine in one I might want to render a `Checkbox` to toggle the value, and in another a `Tag` to simply display the value.

I think what I'm trying to achieve here is having finer control over how each column renders `cell.value`.

**Comment by joshblack** [comment]
I think what TJ outlined above should work with detecting each cell's values and then branching to determine which output to render 👀  For row-level information, you could also look in the row to determine if all of the cells are of a certain type of not. Hope this helps!
