### ISSUE TITLE
Toggle on-disabled just looks disabled

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon#6659]
@Roninnanaki commented on [Wed May 27 2020](https://github.com/carbon-design-system/carbon-website/issues/1227)

Hi, 

I am looking at creating an experience using toggles to determine if a service is going to be installed, active, off, or forced on. I continue to get feedback from my team and potential end-users that the toggles that are _on and disabled_ just look like they are _disabled_. 

Here is an example of the design that we are looking to implement. The last item for Auditing is on and disabled because the user cannot change this due to another setting or policy in the account.

![example](https://user-images.githubusercontent.com/1606224/83040647-7f5c5d00-a00d-11ea-8411-7cc28e67835a.jpg)

I did take a look at the [toggle page](https://www.carbondesignsystem.com/components/toggle/usage) in carbon and didn't see any documentation for the on-disabled state. I found this state through the Sketch library. 

![sketch-library](https://user-images.githubusercontent.com/1606224/83041650-b5e6a780-a00e-11ea-89e7-9e23f2e4e5a8.png)

Lastly, just to share an exploration here is some idea I put together as a solution based on the feedback/suggestions I heard from my design team. 

![potential-solution](https://user-images.githubusercontent.com/1606224/83041862-ef1f1780-a00e-11ea-9565-73f770eeb844.jpg)

---

@eraymond25 commented on [Wed May 27 2020](https://github.com/carbon-design-system/carbon-website/issues/1227#issuecomment-634826388)

+1 to this

here is another available option
<img width="243" alt="Screen Shot 2020-05-27 at 12 37 40 PM" src="https://user-images.githubusercontent.com/12436158/83053782-dfa3cc80-a016-11ea-90f5-1a74f63e07d4.png">

and heads up we're trying to release this in the next few months so would love to collab on a more clear disabled on state asap

**Comment by emyarod** [comment]
This proposal has been accepted, just need component spec updates from our designers before development begins

**Comment by aagonzales** [comment]
Let's go with the below direction. Add checkmark to disabled:on using `$disabled-01` color.

![image.png](https://images.zenhubusercontent.com/5bb3952995c5721e7c272998/328e828c-18d6-4b8c-80b9-70195a3856f3)

**Comment by luizamendes** [comment]
Hello. I would like to take this issue, if that's okay. This will be my first time contributing, what should I do next? Thanks

**Comment by tw15egan** [comment]
Awesome @luizamendes ! I'd start by taking a look at https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#start-contributing

**Comment by luizamendes** [comment]
@tw15egan I have forked the repo and followed the instructions. How can I have this issue assigned to me?

**Comment by tw15egan** [comment]
Done 👍
