### ISSUE TITLE
[MultiSelect]: options aria-selected attribute always false

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#6661]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `MultiSelect` component options are not changing their `aria-selected` attribute regardless of the checked status of the option

> Is this issue related to a specific component?

Yes, the `MultiSelect`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect that the `aria-selected` attribute on the `MultiSelect` options is set to `"true"` when the option is selected and `"false"` when the option is not selected.

> What browser are you working in?

Chrome Version 84

> What version of the Carbon Design System are you using?

7.17.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Data Explorer

## Steps to reproduce the issue

1. Go to any of the [`MultiSelect` component stories](https://react.carbondesignsystem.com/?path=/story/multiselect--default)
2. Click to expand the `MultiSelect` to display options
3. Inspect one of the options in the browser dev tools
4. Notice the `aria-selected` attribute on the option element
5. Toggle the selected state of that option by click in on it
6. Notice that the `aria-selected` attribute on the option is always set to `"false"` regardless of the selected state

## Additional information

![Kapture 2020-08-13 at 10 41 05](https://user-images.githubusercontent.com/5973294/90155946-87e14b80-dd51-11ea-837f-9441d9472449.gif)

**Comment by joshblack** [comment]
cc @dakahn when doing the downshift work, was it that `aria-selected` doesn't mean "selected" but instead was for the hover? Forgot what it was for that surprised us at the time 🤔

**Comment by dakahn** [comment]
Right, yeah aria-selected refers to what currently has focus on hover or with keyboard. This is an a11y affordance for multiselects 👍

**Comment by joshblack** [comment]
Thanks @dakahn!

@diego-codes I think the way that it was explained to me is that `aria-selected` couldn't mean what is currently selected as a listbox doesn't require it's options to be rendered all the time. As DA said, `aria-selected` is:

> [placed] on an option in the listbox when it is visually highlighted


[The example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html) from WAI ARIA I think shows this behavior:

![demo](https://user-images.githubusercontent.com/3901764/90303828-1dc2c680-de77-11ea-8952-76d5db9f4827.gif)

**Comment by diego-codes** [comment]
Ah! I misunderstood the meaning of selected. Thanks for the explanation 👍

**Comment by joshblack** [comment]
@diego-codes same! It's so confusing 🤦
