### ISSUE TITLE
Sidenav and overflow menu z-index overlap

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#6662]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using an overflowmenu with overflowmenuitems in a sidenav component, the z-index has it set such that the overflowmenuitem is behind the sidenav component, and isn't clickable (or visible, depending on style set).

sidenav has z-index of 8000.
overflowmenuitem has z-index ofo 6000.

> Is this issue related to a specific component?

Yes, sidenav and overflowmenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

overflowmenuitem should be clickable and/or visible.

> What browser are you working in?

Firefox.

> What version of the Carbon Design System are you using?

10.16.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one Createt a sidenav component
2. Step two Create an overflowmenu in the sidenav component
3. Step three Unclickable
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
@carbon-design-system/developers should this be an application-level fix or should the Overflow menu have a higher z-index than the side-nav at all times? Not sure if this will have unintended consequences.

**Comment by vpicone** [comment]
@tw15egan the component page refers to the Header as "[the highest level of navigation"](https://www.carbondesignsystem.com/components/UI-shell-header/usage#general-guidance)". To me, that sounds like the `z` direction. I suppose it could mean in the `y` direction, but "first level of navigation" would make more sense if that were the case.

**Comment by joshblack** [comment]
@tw15egan definitely makes sense to me if we want overflow to go over side-nav 👍  However, I'm surprised that there would be an overflow menu _inside_ of the side nav which is what is causing this to happen 🤔  Had thought that it would be triggered from the content area instead of inside the side nav.

**Comment by gptt916** [comment]
Here is my component heirarchy that caused the issue:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/20601623/90818770-0a8f7b00-e2fd-11ea-83f9-05686225c355.png">

**Comment by gptt916** [comment]
Any updates on this issue?

**Comment by tw15egan** [comment]
For now, you can simply set a higher `z-index` on the overflow menu that is nested inside the UI Shell side nav.

@carbon-design-system/developers is this a supported pattern? If not, then this should just remain an application-level override if needed.

**Comment by scottdickerson** [comment]
I'm having a similar issue with overflowmenus inside modals not showing.  I don't see an overflow menu floatingmenu child when it's expanded and contained in a modal

I think due to this snippet in layout.scss (see floating and modal)

```
$z-indexes: (
  modal: 9000,
  overlay: 6000,
  dropdown: 6000,
  header: 8000,
  footer: 5000,
  hidden: - 1,
  overflowHidden: - 1,
  floating: 6000,
);
```

**Comment by gptt916** [comment]
Maybe the z-index of the overflow menu needs to be reconsidered in the overall z-index higherarchy, as is currently is, they won't show for modal and header elements, and for several others will depend on the document tree order.

**Comment by tw15egan** [comment]
It's difficult because we also don't want an open overflow menu on a page to appear on top of a modal (if the overflow menu was not contained inside the modal).

I think it would be helpful to have a CodeSandbox showing a few use cases like 

- modal with a tooltip/overflow,
- tooltip overflow on the main page but modal opens on top
- header with an overflow menu

And then we can test against each scenario and make sure we don't break other scenarios. And as always, all z-indexes can be overridden on the application level to accommodate one-off scenarios.

**Comment by scottdickerson** [comment]
Here's a potential fix for a carbon modal with overflow menus inside it:  https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1595

**Comment by joshblack** [comment]
bump @tw15egan is there a good action item for this issue?

**Comment by tw15egan** [comment]
We could possibly add an overflow menu specific z-index override inside the modal and sidenav styles, but I wouldn't change the overall z-index map.

**Comment by sstrubberg** [comment]
Fix in https://github.com/carbon-design-system/carbon/pull/12185
