### ISSUE TITLE
Safari's input[disabled] text is too faded

### ISSUE THREAD

**Issue by 1mku** [carbon-design-system/carbon#6673]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Safari's input[disabled] text is too faded

> Is this issue related to a specific component?

TextInput

> What browser are you working in?

Safari Version 13.1.1
Chrome Version 83

> What version of the Carbon Design System are you using?

7.17.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

`
<TextInput disabled value="value" labelText="Label text" />
`

## Additional information

Similar issue https://github.com/jgthms/bulma/issues/2355

It looks like one solution is patching:

`
.bx--text-input {
-webkit-text-fill-color: currentcolor;
}
`

![Screen Shot 2020-08-14 at 15 54 32](https://user-images.githubusercontent.com/20165886/90258198-79c22680-de48-11ea-9457-9d4db6a60a82.png)

**Comment by kubijo** [comment]
I've updated to `carbon-components-react@npm:7.39.0` and the same issue is still present in safari@14 (Tested in Big Sur)... @mkuschov is my colleague, so the same project ;-)
