### ISSUE TITLE
ClickableTile component with clickable elements inside does not work as expected 

### ISSUE THREAD

**Issue by azizamagerramova** [carbon-design-system/carbon#6674]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When there is a button element inside clickableTile, for example remove button, when user clicks on the remove button the onClick event is triggered for both remove button handler and clickableTile onClick handler. This can be avoided on the client side with event.stopPropagation, but feels like it should be handled by carbon. 
We expected carbon to handle propagation of component events that are children of ClickableTile.

## Steps to reproduce the issue

1. Create ClickableTile with onClick event
2. Add a button as a child of ClickableTile with onClick event
3. Click on a button
4. Observe both events triggered instead of just button's one.

test case in react https://codesandbox.io/s/wandering-butterfly-bbm8k?file=/src/index.js

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
given that there is a way to handle event propagation at the app level, would preventing the event propagation at the library level be a hindrance in certain use cases?
