### ISSUE TITLE
ToastNotification usage

### ISSUE THREAD

**Issue by maxjowett** [carbon-design-system/carbon#6687]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

How can I use `ToastNotification` to render like so:

![05_toast_context_608](https://user-images.githubusercontent.com/33435443/90554006-20a90a00-e14a-11ea-8019-46a9b963e8db.png)

## Relevant information

The approach below just renders the component inline.

```
const App = () => {
  const [isToastVisible, toggleToast] = useState(false)

  return (
    <>
      <Button onClick={() => toggleToast(!isToastVisible)}>Render Toast</Button>
      {isToastVisible && <ToastNotification kind="info" title="title" subtitle="subtitle" />}
    </>
  )
}
```

**Comment by tw15egan** [comment]
Not sure where exactly you want to position it on the page, but you should be able to just add some CSS to handle this

```css
.bx--toast-notification {
   position: fixed;
   right: 0;
   top: 1rem;
}

**Comment by maxjowett** [comment]
Thanks @tw15egan I will give this a shot.

Two remaining questions:
1. Is there a timeout prop I can pass in the react component? I'm not seeing anything in the storybook.
2. Is functionality like this baked into the react library or does this take additional CSS? (see below)

![72466199-0830d580-379e-11ea-8255-4271d503c18b](https://user-images.githubusercontent.com/33435443/90557405-484ea100-e14f-11ea-8b86-3a9d7fbbf664.gif)

**Comment by tw15egan** [comment]
1) You should be able to specify a custom timeout via the `timeout` prop. This should be specified in the Storybook `props` table. 

2) No, you'll need to add any animations yourself.

Hope this helps!
