### ISSUE TITLE
Overflow using renderIcon throws error in Firefox on click outside

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#6705]
When using renderIcon the overflow sometimes throws an error when clicked outside

```
TypeError: target.matches is not a function
var target = event.target;
  259 |   var triggerEl = _this._triggerRef.current;
  260 | 
> 261 |   if (!menuBody.contains(target) && triggerEl && !target.matches(".".concat(prefix, "--overflow-menu,.").concat(prefix, "--overflow-menu-options"))) {
```

## What package(s) are you using?

- [ X ] `carbon-components`
- [ X ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Error occurs on click outside.

Using renderIcon

> What browser are you working in?

Firefox 79.0, 64bit

> What version of the Carbon Design System are you using?

    "carbon-components": {
      "version": "10.17.0",
    "carbon-components-react": {
      "version": "7.17.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Aspera

## Steps to reproduce the issue

1. Open overflow
2. Click outside
3. It might happen it might not. When it does happen it will happen every time you click outside until reload.

https://codesandbox.io/s/lucid-franklin-pedx0?file=/index.js

## Additional information

<img width="1466" alt="Screen Shot 2020-08-20 at 7 06 05 PM" src="https://user-images.githubusercontent.com/8028956/90834862-34ef3180-e319-11ea-99fa-af2c92a4cbe7.png">

**Comment by dabrad26** [comment]
Found the case.  Click outside of the view port then click back in the browser

1. Open Overflow
2. Click on your destop or finder or whatever
3. Click back in viewport
- Expect: Overflow closes
- Results: Error

Which explains why I was seeing it so much earlier as I was going into dev tools over and over

**Comment by dabrad26** [comment]
My assumption is that Firefox is returning an event for the prior clicks outside of the window or something funky and they don't have the expected data.  To be safe probably validate `matches` is a function before trying to call it.

**Comment by tw15egan** [comment]
Glad you were able to track down the cause, many thanks! Just threw up a PR if you want to verify 👍

**Comment by dabrad26** [comment]
I see similar target.matches in 
- pagination-nav
- init-component-by-search
- init-component-by-event
- init-component-by-launcher
- ui-shell/product-switcher
- dropdown
- data-table

Maybe should have this check for all the cases.  IDK what init-component is for, but I assume the others are similar to what overflow was doing.
