### ISSUE TITLE
DataTable Content overflow-auto property cuts expanded content off

### ISSUE THREAD

**Issue by monoxane** [carbon-design-system/carbon#6706]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
The `DataTable` class `bx--data-table-content` has `overflow-y: auto;`, which causes a `Dropdown` within the bottom most `TableExpandedRow` to overflow the component and become hidden at the bottom of the `DataTable`

Currently the `Dropdown` overflows like so:
![Screen Shot 2020-08-21 at 3 30 40 pm](https://user-images.githubusercontent.com/16844830/90855608-5f95c480-e3c3-11ea-8b53-35565f958e1e.png)

With the CSS property changed to `visible` the `Dropdown` overflows and content is visible: 
![Screen Shot 2020-08-21 at 3 32 15 pm](https://user-images.githubusercontent.com/16844830/90855715-98359e00-e3c3-11ea-84e6-3dbab74bc695.png)

This issue persists on Firefox, Safari, Chrome, and Edge.

Using Carbon versions:
"carbon-components": "^10.9.3",
"carbon-components-react": "^7.9.3"

My product does not have a deadline, the issue is non-critical.
[Internal bug tracking for this issue is here](https://phabricator.boreal.systems/T69)

## Steps to reproduce the issue

[CodeSandBox]( https://codesandbox.io/s/peaceful-grass-sqhcl?file=/src/index.js)
Expand table row and open the Controller Panel Mapping dropdown.

**Comment by tw15egan** [comment]
Catching a few edge-cases that are breaking a potential fix on our end, so it seems like it may be best if you just override this on the application level to suit your needs. Thanks!

**Comment by monoxane** [comment]
Understandable, will patch in my application. Thanks!
