### ISSUE TITLE
Modal Content overflow-auto property cuts expanded content off

### ISSUE THREAD

**Issue by monoxane** [carbon-design-system/carbon#6713]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
The `Modal` class `bx--modal-content` has `overflow-y: auto;`, which causes a `DropDown` with more than 1 item to be cut off when placed at the bottom of a modal.

Currently:
![Screen Shot 2020-08-25 at 2 04 39 am](https://user-images.githubusercontent.com/16844830/91068845-2fc31700-e678-11ea-80d5-19a7598d1b53.png)

Optimally:
![Screen Shot 2020-08-25 at 2 05 47 am](https://user-images.githubusercontent.com/16844830/91068882-41a4ba00-e678-11ea-85b5-f555e7088e20.png)

This issue persists on Firefox, Safari, Chrome, and Edge.

Using Carbon versions:
"carbon-components": "^10.9.3",
"carbon-components-react": "^7.9.3"

My product does not have a deadline, the issue is non-critical.
[Internal bug tracking for this issue is here](https://phabricator.boreal.systems/T90)

## Steps to reproduce the issue

[CodeSandBox](https://codesandbox.io/s/sparkling-bird-2dwjp)
1: Click ComboBox
2: Observe Overflow
3: ???
4: Profit Proceeds

**Comment by tw15egan** [comment]
Related https://github.com/carbon-design-system/carbon/issues/6288

**Comment by monoxane** [comment]
Apologies for the dupe, I didn't search well enough when I submitted this at 2am...

**Comment by monoxane** [comment]
Going to assume that this will be the same as my other overflow issue, will patch locally in my application.
