### ISSUE TITLE
Data table - Sortable does not look good

### ISSUE THREAD

**Issue by JoseJesusOchoaTorres** [carbon-design-system/carbon#6715]
## What package(s) are you using?

-  [x] `carbon-components: 10.18.0`
- [x] `carbon-components-react: ^7.18.0`
- [x] `carbon-icons: ^7.0.7`

## Summary

Approximately two weeks ago we detected that the styles in our Sortable Data Table look odd, I mean the arrow icons and text are not correctly aligned or distributed.

**How it looks for me:**

![image](https://user-images.githubusercontent.com/8441759/91119829-d815b300-e659-11ea-8068-2150ce81de04.png)

**How it looks at the carbon design system page** [Link](https://www.carbondesignsystem.com/components/data-table/code/)

![image](https://user-images.githubusercontent.com/8441759/91120677-d0570e00-e65b-11ea-8a94-361d37785d8b.png)

**How it looks at the official react storybook** [Link](https://react.carbondesignsystem.com/?path=/story/datatable--with-sorting#installation)

![image](https://user-images.githubusercontent.com/8441759/91119851-ec59b000-e659-11ea-97ec-3290c434b203.png)

## Relevant information

This is my test "Data table" component code:

````js
import React from 'react';
import { DataTable } from 'carbon-components-react';

const { TableContainer, TableRow, Table, TableHead, TableHeader, TableBody, TableCell } = DataTable;

const rows = [
  {
    id: 'a',
    foo: 'Foo a',
    bar: 'Bar a',
    baz: 'Baz a',
  },
  {
    id: 'b',
    foo: 'Foo b',
    bar: 'Bar b',
    baz: 'Baz b',
  },
  {
    id: 'c',
    foo: 'Foo c',
    bar: 'Bar c',
    baz: 'Baz c',
  },
];

const headers = [
  {
    key: 'foo',
    header: 'Foo',
  },
  {
    key: 'bar',
    header: 'Bar',
  },
  {
    key: 'baz',
    header: 'Baz',
  },
];

const TestComponent = () => {
return (
    <DataTable
      isSortable
      rows={rows}
      headers={headers}
      render={({ rows, headers, getHeaderProps }) => (
        <TableContainer title="DataTable">
          <Table>
            <TableHead>
              <TableRow>
                {headers.map((header) => (
                  <TableHeader key={header.key} {...getHeaderProps({ header })}>
                    {header.header}
                  </TableHeader>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {rows.map((row) => (
                <TableRow key={row.id}>
                  {row.cells.map((cell) => (
                    <TableCell key={cell.id}>{cell.value}</TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    />
  );
};

export default TestComponent;
````
As you can see, I am using the `isSortable` prop but I'm missing the `bx--data-table--sort` class on my table tag.

![image](https://user-images.githubusercontent.com/8441759/91120102-7dc92200-e65a-11ea-9dc0-ce45c7f347ed.png)

If we add that class, it works properly, so the questions here are, Did I do something wrong? Am I implementing it incorrectly?

![image](https://user-images.githubusercontent.com/8441759/91120228-cda7e900-e65a-11ea-9ba4-5ddf9ca52f39.png)

I'll appreciate a lot the support guys. 🙏

**Comment by JoseJesusOchoaTorres** [comment]
Sorry, I found my error, and I could fix my issue; but for some reason, the carbondesignsystem page was not rendering correctly the table and that confused me.

**Comment by starpit** [comment]
for future reference (and just cribbing here from the referenced merged fix), if you see this, then you may not be applying the <DataTable>'s getTableProps() to the nested `<Table>` component:

```typescript
<DataTable render={opts => <Table {...opts.getTableProps()}/>}>
```

this will give the needed `bx--data-table--sort` property on the `<table>` element
