### ISSUE TITLE
DataTable sticky header has problem on Safari

### ISSUE THREAD

**Issue by yrue** [carbon-design-system/carbon#6716]
---

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I set stickyHeader of `DataTable` component. But the header is hidden as below if I scroll to bottom after adding around 8 new rows on `Safari` (Chrome, Firefox works fine). 
![image](https://user-images.githubusercontent.com/5738032/91119664-5445e000-e6c6-11ea-8d10-0dab3506d51c.png)

> Is this issue related to a specific component?

yes, DataTable 

> What did you expect to happen? What happened instead? What would you like to

expected behavior:
When setting stickyHeader on `Safari`, both the table header and the toolbar session should be always there when scrolling.
![image](https://user-images.githubusercontent.com/5738032/91120565-89ebc880-e6c8-11ea-927e-50705e6fe755.png)

> What browser are you working in?
Safari 13.1.2

> What version of the Carbon Design System are you using?

carbon-components "10.15.0"
carbon-components-react "7.15.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM QRadar User Behavior Analytics

## Steps to reproduce the issue

1. Go to carbon storybook: https://react.carbondesignsystem.com/?path=/story/datatable--with-dynamic-content
2. click setting icon
3. click add row to create around 8 rows
4. observed

**Comment by emyarod** [comment]
I believe this is a Safari/webkit issue, currently not sure of a workaround

**Comment by sstrubberg** [comment]
Is this still an issue?
