### ISSUE TITLE
Icon only Button tooltip issues

### ISSUE THREAD

**Issue by chamberOfUnderstanding** [carbon-design-system/carbon#6718]
## What package(s) are you using?
- [x] `carbon-components` - 10.12.0
- [x] `carbon-components-react` - 7.12.0

## Detailed description

I have a tree view structure where the expand/collapse buttons are Carbon's Icon only Buttons. I noticed the following issues with respect to the tooltip - 

- The tooltip pops up instantly while moving the mouse over them. This gets intrusive as the buttons are adjacent to each other. It would be convenient to have a delay for these tooltips.
- The tooltip seems to be clickable and it triggers the button's onClick action.
- The tooltip is retained after an on click action (As long as the button stays in focus).

**Comment by emyarod** [comment]
The tooltip delay should be modifiable with CSS. I'm not able to replicate the second point, so can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

and for the 3rd point, this is expected behavior and matches our a11y requirements for tooltips

**Comment by chamberOfUnderstanding** [comment]
I was unable to reproduce the second issue in code sandbox. I see that the carbon components storybook does not have this issue. May be it was fixed in a later version?

**Comment by emyarod** [comment]
yes that's possible although I'm not sure if it was an issue in previous versions either

**Comment by chamberOfUnderstanding** [comment]
For the tooltip delay, animation-delay property was not working, so I have used animation-duration. Not as elegant as delay, but it works.  
Since Issue 2 is not reproducible in the storybook, I assume it got fixed in a later version.

**Comment by chamberOfUnderstanding** [comment]
Is there a better approach to tooltip delay than overriding animation-duration?

**Comment by emyarod** [comment]
> For the tooltip delay, animation-delay property was not working

ideally animation-delay would be more preferable than animation-duration in your use case but it's not clear as to why it was not working in your previous tests

**Comment by chamberOfUnderstanding** [comment]
I came across an [enhancement](https://github.com/carbon-design-system/carbon/issues/6178) with the same use case as mine.
As per the discussions in it, delay property does not work. Is it still the case or is there any other work around?

**Comment by joshblack** [comment]
bump @emyarod if you have any thoughts on the above comment!

**Comment by emyarod** [comment]
more research needs to be done on why the delay cannot be manipulated by itself. my guess is somewhere in the stylesheet there is a shorthand style rule that's overriding things

**Comment by sstrubberg** [comment]
Is this still an issue?
