### ISSUE TITLE
[RFC] Add @carbon/telemetry package

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6723]
This issue is for adding a `@carbon/telemetry` private package. This package is a part of our metrics-oriented push in Q3, and the hope for it is to emulate existing behavior in Gatsby or Next.js to provide a variety of anonymized statistics that we can use to influence our roadmap. In particular, this package should:

- [ ] Be runnable from the command line in a package's `postinstall` step, for example:

```json
{
  "name": "my-library",
  "scripts": {
    "postinstall": "telemetry track"
  },
  "dependencies": {
    "@carbon/telemetry": "0.1.0"
  }
}
```

_Note: this should only run in CI_

- [ ] Be configurable with options to track, including any arguments that they take (like a list of components)
- [ ] Report anonymized information to a default endpoint (should this be configurable too?)
- [ ] Any failures in the script should **not** fail the user's CI
- [ ] The user's CI should **not** be dependent on the script to finish the install step

**Optional**
- [ ] Provide an exported instance of the telemetry client to send additional data

**Open questions**

- What kind of usage information should we trick?
  - Components
    - Frequency of component in codebase
    - Prop frequency of use with components
  - Packages
    - Which carbon packages are used, and which version (ideally from lockfile)
  - For internal teams
    - Where is it being used? (`git remote`)
    - We have to change a component, who does this impact?
- How do we anonymize usage information while still making the info valuable to team?
- How should teams who use this package view the reported data?
  - This could be our Carbon for IBM app and we can associate maintainers to packages so that they can view analytics
- What kind of additional meta information would be worth tracking? (anonymously)

**Links and Resources**

- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-telemetry/src
- https://github.com/vercel/next.js/tree/canary/packages/next/telemetry

**Comment by loganmccaul** [comment]
Yes! To all of the questions.

One additional requirement I would add is that the telemetry script spawns a new process to run in so we don't increase the normal CI build times.

Open questions:
1. Agreed with the info you have. Additionally, if possible, capturing the route to a github repo (using `git remove -v`) will help us better understand keep track of specific repos, and files using Cloud PAL. I'd also consider tracking CSS overrides.
2. I think we'll want to have an idea of what codebases are doing what so we can follow up with the teams if changes or updates are needed. We are currently using this information to make breaking changes and then work with the teams to update the components without having to go through a deprecation strategy. I don't believe github repo urls will be PII, but just in case having an option to restrict tracking to packages pulled from IBM GHE might be helpful. Additionally, we should always provide an opt out.
3. Becca Ellsworth has a lot of good ideas in this area and could help bring those up to the Carbon level as well.
