### ISSUE TITLE
Allow Search component to include children or optionally remove landmark search role

### ISSUE THREAD

**Issue by electrostaticfleece** [carbon-design-system/carbon#6724]
### Summary

Currently, I have not found a way to use the Search component alongside a listbox in a manner that is a11y for things like suggestions, auto-complete, results, etc. In order for the landmark role to contain the list box, I would like to request the option to remove the landmark role, so we may hoist it higher on our own OR allow the search component to take children in order to include something like a nested list box. I believe this would just require development effort.

If there is an accessible way to do this that I am missing please let me know, and I'll happily close the issue. 

### Justification

This will allow my team to stay consistent with the Carbon Design System's guidelines for Search while also allowing us to build a Search bar with suggestions, results, etc. 

### Specific timeline issues / requests

This is tied to an a11y issue for [IBM Cloud Docs](https://cloud.ibm.com/docs) that we would like to have resolved sooner rather than later.

**Comment by dakahn** [comment]
Discounting the AC error for a `<div>` having the `aria-expanded` attribute, maybe you could checkout how we got this done in our [Carbon Gatsby Theme](https://github.com/carbon-design-system/gatsby-theme-carbon/blob/main/packages/gatsby-theme-carbon/src/components/GlobalSearch/GlobalSearch.js)?
