### ISSUE TITLE
<datatable> is not sorting toggle component when sorting.

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon#6727]
version: carbon-components-react@7.16.0.

When we have a Toggle component in one of the column with some being On and some Off. When we try to sort the table by clicking on the table row, the toggle components does not get sorted. On debugging I see that the toggle component is rendered properly but the css which was applied on the cell earlier does not change and hence On switch looks Off and vice-versa. 

Created the issue in sandbox. 
Click on ID to sort and you will see that Status field is not getting sorted.
https://codesandbox.io/s/frosty-elion-w223g?file=/src/index.js

**Comment by emyarod** [comment]
This is because you are not passing in row props to your table rows in your code sandbox example

https://codesandbox.io/s/nameless-field-d4i3j

**Comment by PAnilReddy** [comment]
@emyarod , Thank you for pointing out. We did use that in our code and I missed to put that in sandbox. 
But still it does not work in our code and we are not using **Datatable** directly.
We are using **DataTableHOC** which is a component from cloudpal. Let me check with them

**Comment by PAnilReddy** [comment]
@emyarod, it still looks as an issue. Figured out why it was not sorting.
Can you reopen the issue.

Here is it, in the sandbox example, it does work, but there is a catch in the below line
<DataTable.TableRow key={rowindex} {...getRowProps({ row })}>
if your code has the above line it works but if you switch the params it stops working. in the below change I moved the key as the last parameter and now it does not sort the toggle component.

<DataTable.TableRow  {...getRowProps({ row })} key={rowindex}>

**Comment by tw15egan** [comment]
Can you just simply put the `key` prop before the ` {...getRowProps({ row })}`?

**Comment by PAnilReddy** [comment]
@tw15egan , Agree that it works but to figure out the issue I had to spend couple of days.
What I understand form the issue is, if the give the key property at the end its overriding the key property of the rowProp and causing the issue.
Either the component should be ignoring the attibute if given or use that attribute. If nothing is possible atleast it should be documented so that others dont spend time in figuring out the issue as its a a very minute setting.
