### ISSUE TITLE
"Copy" icon and functionality for a normal string

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon#673]
Currently carbon supports placing a copy icon within the code snippet component: http://www.carbondesignsystem.com/components/code-snippet/code

There are other situations where it would be helpful to tag the "Copy" icon and functionality onto another string. In kubernetes for example, a user might want to copy a cluster or node id from the UI and paste it into the cli. 

Can we create a copy component that allows developers to add the "copy" icon to a specific string?

<img width="1004" alt="screen shot 2018-03-26 at 2 20 18 pm" src="https://user-images.githubusercontent.com/19826147/37927929-ea6f6cfa-3100-11e8-9c0a-be747e8f89c6.png">

**Comment by asudoh** [comment]
Thank you for asking @SpencerReynolds18! Though standalone copy-button doesn’t seem to be in carbondesignsystem.com, we have an example of standalone copy-button in our internal dev env: https://github.com/carbon-design-system/carbon-components/blob/2612b2d/src/components/copy-button/copy-button.html

CC’ing @carbon-design-system/design to see above usage is good.

**Comment by tay-aitken** [comment]
Yes, I think this is a good use case for this! We will have to talk and see what it would take to get this as a component.

**Comment by shixiedesign** [comment]
Icon button is merged! Closing issue but feel free to reopen if you feel icon button does not address the need here. Thanks!
