### ISSUE TITLE
Is it possible to avoid including the heading global styles?

### ISSUE THREAD

**Issue by ferdelamad** [carbon-design-system/carbon#6732]
## What package(s) are you using?

- [x] `carbon-components - 10.12.0`
- [x] `carbon-components-react - 7.12.0`

## Summary
Hi Carbon team 👋
I was wondering is it was possible to opt-out of the default `heading` global styles?

I removed the css resets by doing this:
```
$css--reset: false !default;
$css--body: false !default;
```
I was hoping there was a similar mechanism to avoid including the `heading` globals.

Thank you 🙏!

**Comment by joshblack** [comment]
Hey there @ferdelamad! 👋 

Which styles are you hoping will be excluded? It's hard to tell based on the issue and I wanted to double-check 👀

**Comment by ferdelamad** [comment]
Hi @joshblack, thank you for the quick response, these are the styles I'm trying to exclude:
```
h1 {
  font-size: 2.625rem;
  font-weight: 300;
  line-height: 3.125rem;
  letter-spacing: 0; }

h2 {
  font-size: 2rem;
  font-weight: 400;
  line-height: 2.5rem;
  letter-spacing: 0; }

h3 {
  font-size: 1.75rem;
  font-weight: 400;
  line-height: 2.25rem;
  letter-spacing: 0; }

h4 {
  font-size: 1.25rem;
  font-weight: 400;
  line-height: 1.625rem;
  letter-spacing: 0; }

h5 {
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.375rem;
  letter-spacing: 0; }

h6 {
  font-size: 0.875rem;
  font-weight: 600;
  line-height: 1.125rem;
  letter-spacing: 0.16px; }

p {
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5rem;
  letter-spacing: 0; 
}
```

**Comment by joshblack** [comment]
@ferdelamad perfect, for this you can use the `$css--default-type` flag to disable the default type that you shared above. Specifically:

```scss
$css--default-type: false;

@import 'path-to-carbon';
```

Hope this helps!

**Comment by tw15egan** [comment]
Closing as resolved, but feel free to reopen if you've got any more questions!

**Comment by ferdelamad** [comment]
That worked, thanks you very much @joshblack for the help!
