### ISSUE TITLE
The button should be resized to avoid text wrapping.

### ISSUE THREAD

**Issue by mashenka123** [carbon-design-system/carbon#6735]
Could you please help fix? Thank you!
If the text reachs the max width, perhaps providing a tooltip is better than wrapping.
![060 060 004_layout_jpn](https://media.github.ibm.com/user/21419/files/3029e380-e746-11ea-883e-b7c05da578d8)

**Comment by emyarod** [comment]
you can update the `max-width` CSS rule on the button to prevent text wrapping, the initial value exists mostly as a guideline

**Comment by GoldenFishe** [comment]
Wrap your text in `span` with:
```
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```

**Comment by tw15egan** [comment]
Going to close this as there are overrides available at the application level
