### ISSUE TITLE
Icon only Button tooltip has a gap

### ISSUE THREAD

**Issue by chamberOfUnderstanding** [carbon-design-system/carbon#6737]
## What package(s) are you using?

- [x] `carbon-components` - 10.12.0
- [x] `carbon-components-react` - 7.12.0

## Detailed description

Icon only Button tooltip has a gap between the triangular tip and the rectangular body.  
![tooltip has a gap2](https://user-images.githubusercontent.com/59013274/91422213-7c734180-e874-11ea-9d38-3c7f35abb078.png)
I can see this issue in the carbon components storybook itself. 
OS - Windows 
Browsers - Chrome 84.0.4147.135, Firefox 78.2.0esr (Needs 110% zoom), Edge 84.0.522.63

**Comment by emyarod** [comment]
This is caused by the increased zoom, and it will be visible in all of the tooltip components in the library

**Comment by chamberOfUnderstanding** [comment]
As I mentioned, increased zoom applies only to Firefox. In case of Chrome and Edge, I see it with the default zoom level. I checked other tooltips, and none of them get it in the default zoom level.

**Comment by emyarod** [comment]
this may be screen resolution dependent, since this is what Chrome and Edge both look like at default zoom for me

![image](https://user-images.githubusercontent.com/8265238/91580867-52249100-e913-11ea-949b-0d78e9e8b498.png)

**Comment by chamberOfUnderstanding** [comment]
I agree, resolution is causing this. I tried out other resolutions and it was not visible in some of them. Even if it was visible in a different resolution, changing the Windows recommended text size gets rid of it.

**Comment by mike-zuliani** [comment]
As a counter-argument, for accessibility reasons, shouldn't the UI work properly regardless of browser magnification or OS text magnification?

**Comment by tw15egan** [comment]
I mean, it is still working properly, there is just a 1px artifact at different zoom levels. It doesn't seem to be affecting the readability of the actual message. 

If anyone has a fix to prevent this from happening on different zoom levels we'd happily accept a PR.
