### ISSUE TITLE
Disabled number input (light mode) is the wrong background color

### ISSUE THREAD

**Issue by quarryboy** [carbon-design-system/carbon#6741]
We have the number input set up properly in our environment but it is rendering incorrectly. We're using `light` settings but the background is showing up as white; causing it to be invisible. [Matt Howard](https://w3.ibm.com/bluepages/profile.html?uid=7D5311897) is our dev on this.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

It renders like this... 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3935853/91492947-1ee2f300-e87c-11ea-8158-88b852d6268d.png">

But in storybook, it looks like this...
<img width="300" alt="image" src="https://user-images.githubusercontent.com/3935853/91493093-5b165380-e87c-11ea-8742-4c32657b0c96.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/3935853/91493293-b5afaf80-e87c-11ea-8650-e1c8e7ba9e0e.png">

> Is this issue related to a specific component?

Yes, the Number stepper 
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

This is browser agnostic as it appears in all browsers this way.

> What version of the Carbon Design System are you using?

current.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Modeler Flows for Watson Studio / Elyra canvas

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by tw15egan** [comment]
Which version of the components is this coming from? ~On the latest, I'm not seeing the `bx--text-input--light:disabled` selector anywhere...~


![Screen Shot 2020-08-27 at 2 03 31 PM](https://user-images.githubusercontent.com/11928039/91494731-27343180-e86e-11ea-8224-733b43b75cbc.png)

**Comment by emyarod** [comment]
I think he was comparing the differences with the disabled light text input

**Comment by matthoward366** [comment]
Correct.  The textinput has the disabled light selector.  The numberinput control doesn't have this selector.  
```
"carbon-components": "^10.14.0",
"carbon-components-react": "^7.14.0",
```

**Comment by tw15egan** [comment]
Gotcha. Seems like we are explicitly setting a background that takes precedence over the light background, so I'd make sure that your number input matches this selector:

![Screen Shot 2020-08-27 at 2 12 12 PM](https://user-images.githubusercontent.com/11928039/91495421-60b96c80-e86f-11ea-9142-6fe2e5413bb5.png)

**Comment by matthoward366** [comment]
This is coming directly from https://react.carbondesignsystem.com/?path=/story/numberinput--default.  This seems to be coming from the carbon styling.
![Screen Shot 2020-08-27 at 4 15 32 PM](https://user-images.githubusercontent.com/21126000/91495697-8b5ff100-e880-11ea-9f59-b104ced51ad1.png)

**Comment by matthoward366** [comment]
I think there needs to be a light variant for disabled on the number control.

**Comment by tw15egan** [comment]
Gotcha, so the issue is that the `light` disabled styles are identical to the non-`light` disabled styles. I originally thought that you were _getting_  this but expecting the normal disabled background. 

![image](https://user-images.githubusercontent.com/11928039/91496224-9874e400-e870-11ea-90ae-5fcd1026e64a.png)

**Comment by matthoward366** [comment]
That's correct.

**Comment by emyarod** [comment]
it looks like the labels and helper text also are not receiving disabled styles so I can make that change
