### ISSUE TITLE
copy-to-clipboard feedback text of CodeSnippet component is cut off

### ISSUE THREAD

**Issue by daniel-schulz-privat** [carbon-design-system/carbon#6746]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
1. browse to https://www.carbondesignsystem.com/components/code-snippet/usage
2. In the Live-Demo section, select _Single line_
3. In the markup of the component, add a feedback-attribute to the <CodeSnippet> component like so:
  feedback="123456789012345678901234567890"
4. select the copy-to-clipboard icon and spot the truncated text.

The text is truncated.
I expect the text to be not truncated.

I tested on latest Firefox.

I used the latest version of carbon/carbon react. As pointed out, it can be reproduced on the official carbondesignsystem website.

Please note that I filed a similar issue a few months ago (https://github.com/carbon-design-system/carbon/issues/5428). It was fixed with that issue. So it seems it is a regression.

![image](https://user-images.githubusercontent.com/20154051/91716162-5ceb5a00-eb8f-11ea-9443-c703179b6f78.png)

**Comment by emyarod** [comment]
@carbon-design-system/design should this enhancement be added to the copy button/code snippet spec? I imagine it would be like the icon and definition tooltip positioning and alignment options

this does not look like a regression though, the issue and PR referenced doesn't address the scenario when the tooltip overflows off the screen, it only unset the max width of the tooltip

**Comment by vpicone** [comment]
This is a problem with the container, either add padding to the container or remove the overflow hidden attribute. The Copy button itself can't control the styles of it's wrapper/parent
