### ISSUE TITLE
Enhance the Tag component with tooltip support

### ISSUE THREAD

**Issue by gracelo** [carbon-design-system/carbon#6747]
### Summary

The Tag component currently does not support Tooltip on hovering.

### Justification

The design team of my UI wants to show tooltip on the tags.

I prefer the support like TooltipDefinition which allows the direction, the align attribute and the tooltipText.  The tag is quite small so the caller properly needs flexibility to where to place the tooltip.  Thank you.

**Comment by gracelo** [comment]
The designer has changed the design so this is not as urgent.  But I will leave it for the carbon team to decide if it is a to-do item.  Thank you.

**Comment by vpicone** [comment]
Considering the interactive tab when disabled isn't tab selectable, we should consider supporting tooltips as if they are buttons.
