### ISSUE TITLE
Data table V2: Canceling batch action doesn't remove selected class from rows

### ISSUE THREAD

**Issue by faulke** [carbon-design-system/carbon#675]
## Detailed description

When a batch action is canceled, all rows are deselected, but the selected class (e.g., `bx--data-table-v2--selected`) remains on all `tr` elements that were previously selected.

**Is this issue related to a specific component?** 
Data table V2

**What did you expect to happen? What happened instead?**
Expected: 
> Rows are deselected and selected class is removed from all rows.

Actual: 
> Rows are deselected, but the selected class remains on all rows that were previously selected.

**What browser are you working in?** 
Chrome 65.0.3325.181

**What version of the Carbon Design System are you using?** 
v8.10.0

## Steps to reproduce the issue
1. Select the checkbox for a table row.
2. Click the Cancel button in the table toolbar next to # items Selected.

## Additional information
![gcj9tmjtkb](https://user-images.githubusercontent.com/15271347/37932924-a14fc710-30fe-11e8-8891-28ec953813b1.gif)

**Comment by joshblack** [comment]
Hi @faulke! 👋 Thanks so much for taking the time to make this issue. cc'ing @asudoh in case he has any thoughts on this.

**Comment by alisonjoseph** [comment]
@joshblack can we not just loop through the selected classes and remove them when clicking the cancel button?
