### ISSUE TITLE
I created my own component through Gatsby theme repo, next steps?

### ISSUE THREAD

**Issue by helmutgranda** [carbon-design-system/carbon#6750]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Using Gatsby Theme is great but need to figure out the workflow when it comes to incorporating custom components. 

## Relevant information

I am creating our own UI version of our components using https://github.com/carbon-design-system/gatsby-theme-carbon and I have created a couple of components to test the workflow, pretty straight forward. Now, I want to have those components as part of the mininfied CSS and JS since we are going vanilla and that is where I got stuck since gatsby-theme-carbon does not provide the tools to do so, does that mean that I have to somehow incorporate this work with gatsby-theme-carbon?

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/gatsby-theme-carbon #981](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/981) via [**ZenHub**](https://www.zenhub.com/)
