### ISSUE TITLE
Is there a way I can stop closing bx--navigation when anywhere is clicked on content?

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#6771]
Vanilla.js

- [x] `carbon-components` bx--header

## Summary

Hi! 

I want bx--navigation to not close whenever somewhere in content is being clicked and only close it when the user clicks the [X] in the left corner. Is there any way I can do that? I've searched for a long time but can't find it.

Thank you in advance!

**Comment by joshblack** [comment]
Hi there, @joseph00! 👋  I don't believe there is a way to do this with the vanilla components as far as I know 😞

**Comment by ghost** [comment]
Hi @joshblack ! Thank you for your response, that's unfortunate, thank you for your reply.
Is there a way that I can use a side <nav> which opens and closes the same way as the bx--navigation opens and closes?

Kind regards

**Comment by joshblack** [comment]
@joseph00 sorry for the delay! If I remember correctly, this should be do-able with React components but not as far as I'm aware for Vanilla. There totally could be a way, but nothing is coming to mind. Unfortunately, Vanilla is not as actively maintained as the React components which is causing some of the trouble here😞
