### ISSUE TITLE
Motion: export duration variables in JavaScript with the carbon/motion package

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#6779]
### Summary

Currently the `@carbon/motion` package exports `carbon--motion` JavaScript function with easings. But as far as I know, there isn't a way to also import any specific timing values (like the equivalent of SCSS variable `$duration--fast-02`) as JavaScript variables from this package.

### Justification

When creating JavaScript-based animations, it is helpful to be able to import these variables from Carbon instead of doing workarounds and/or redefining the variables ourselves.

If these values actually do exist in a package right now, please let me know! I just didn't see a way to grab these motion duration values currently. Thank you!

**Comment by joshblack** [comment]
Closed by https://github.com/carbon-design-system/carbon/pull/7782
