### ISSUE TITLE
Skeleton loading - Screen Freeze

### ISSUE THREAD

**Issue by nikolasmach23** [carbon-design-system/carbon#6781]
## What package(s) are you using?

- [10.19.0] `carbon-components`
- [ 7.19.0] `carbon-components-react`

## Relevant information

Hello, i would like to ask you if it is option to "freeze" screen while Skeleton loading is in progress. 
For example don`t allow to click on menu:
![image](https://user-images.githubusercontent.com/26468068/92208572-c1f2c880-ee8b-11ea-9044-e30c0cebb23f.png)

**Comment by tw15egan** [comment]
There is no pre-configured option to handle this, but you could use CSS and add `pointer-events: none` to any items you don't want to be interacted with while loading
