### ISSUE TITLE
Allow non-carbon projects to use ALL the carbon-component's required styles, without interfering with their own styles

### ISSUE THREAD

**Issue by JessNah** [carbon-design-system/carbon#6783]
### Summary and Justification
Right now it is possible to use: $css--reset: false, so that the global styles such as for p,div,body,h1,h2,ul,etc do not load from the carbon style-sheet and do not clash with the styles a product might be using for their own project.
But this results in carbon-components not looking right, the focus can be off, margins, padding, even the fonts on the carbon-components themselves aren't right.

There is a big use-case for non-carbon projects, to want to retain their own stylings but use carbon-components for certain pieces, and have those carbon-components retain the true and consistent carbon stylings - from fonts to border-line to margins, etc (All of which is lost when setting css--reset: false )

Unfortunately a-lot of these stylings are all non-prefixed, which is why projects have to use $css--reset... Is it not possible for carbon to also prefix and use all these other tags in their css?
So that non-carbon projects trying to use carbon-components, can get the correct consistent styling that is intended?

**Comment by emyarod** [comment]
I'm not sure if I fully understand your question, but users should be able to apply their own styles on top of a CSS reset

**Comment by asudoh** [comment]
I think she's simply looking for a way to avoid Carbon style from clashing application's style (or another design system's style). Though there may be some hacks like `.some--style-scope { @import '/path/to/carbon/sass'; }` (which has an issue of change in selector specificity), Shadow DOM is the only solution I know it works well.
