### ISSUE TITLE
Insufficient Line heights in Carbons Typography

### ISSUE THREAD

**Issue by johnjesse** [carbon-design-system/carbon#6786]
# Insufficient Line heights in Carbons Typography

## Detailed description

The line-heights defined in the carbon typography page here - https://www.carbondesignsystem.com/guidelines/typography/overview struggle with text that includes large descenders and ascenders. Typically text with large ascenders or descenders are accented letters - (the case is worse when the letters are capitals) - or specical characters - for instance emoji

This can cause issues where
* Text is overflowing the container boundary
* lines of text overlap

## Steps to reproduce the issue

See code sandbox here - https://codesandbox.io/s/carbon-typography-issues-hd924?file=/src/index.js - this is a contrived example just using letters - but it illustrates that most Carbon type styles have the issue - the only ones that don't appear to be
* body-long-02
* expressive-heading-02

This feels like a big issue -> surely all the line-heights should be coping with the text including long ascenders and descenders

here are a couple examples of the issues
![image](https://user-images.githubusercontent.com/6839660/92379185-f4582c00-f0fe-11ea-833c-806f45c0a957.png)
![image](https://user-images.githubusercontent.com/6839660/92379229-033ede80-f0ff-11ea-87a7-90ba0fd8a972.png)
![image](https://user-images.githubusercontent.com/6839660/92379281-1c478f80-f0ff-11ea-9b83-d92b55227aa4.png)

**Comment by joshblack** [comment]
cc @jeanservaas @aagonzales curious what you all think the next steps should be here, or if we should meet together to talk about this and figure it out together 👀

**Comment by johnjesse** [comment]
FYI - we did a bit of our own investigation for this - the main issues appear to only happen in the plex fonts for the capital letters with double accents - whilst most languages don't use these characters, they are more often used in tonal languages

Having said that - one that does this is Vietnamese e.g. https://vietnamesetypography.com/tone-marks/

We were unable to find other languages that caused the same issues (but hadn't done an exhaustive search) - so we moved to a line-height of 1.5 everywhere - with the known issue that Vietnamese would cause our UI issues.

**Comment by aagonzales** [comment]
I haven't full read this issue but just want to make a note that changing line heights will effect a lot of internal padding across components.

**Comment by aagonzales** [comment]
Also if its a problem with the font itself we are in a unique place to be able to influence and change the fonts. Maybe this is also an issue for the IBM Plex repo. 
https://github.com/IBM/plex/issues

**Comment by mjabbink** [comment]
Vertical heights will need to be defined per use case. Vietnamese may require more line-height compared to Latin due to the double accents. The same issue will come up for usage with Plex Devanagari, and Japanese for example.

**Comment by mjabbink** [comment]
<img width="778" alt="Screen Shot 2021-06-01 at 4 52 04 PM" src="https://user-images.githubusercontent.com/32881239/120394949-cc969d00-c2f9-11eb-9edd-a8a3360dffd8.png">

**Comment by mjabbink** [comment]
Body long will probably cover the taller vertical heights required in a few non-Latin scripts like Japanese, Korean, and Devanagari. We should probably double-check this for body copy because we may need to have a similar construct for those. i.e long becomes the “short” version for those scripts and we add an extralong (if you will) for the body copy in those scripts. 


<img width="561" alt="Screen Shot 2021-06-01 at 5 02 11 PM" src="https://user-images.githubusercontent.com/32881239/120395864-52ffae80-c2fb-11eb-827f-8092a62a9782.png">

**Comment by mjabbink** [comment]
Actually, I think this is not a Plex issue so no need to recreate the issue there.

**Comment by sstrubberg** [comment]
if someone uses Vietnamese, you're going to have to bump the line-height.
