### ISSUE TITLE
[Data table] Expand all for tables

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon#679]
## Detailed description

Based on a discussion had here: https://github.ibm.com/alchemy-containers/armada-ui/issues/2666#issuecomment-5288447

We had a need to expand all of the expandable rows in our tables. We ended up pulling out the information that the user had wanted to see and resolved the issue, but there still may be a need from us or another team in the future to have the ability to expand all of the rows. 

> Is this issue related to a specific component? 
Data Table

**Comment by joshblack** [comment]
cc @IBM/carbon-designers do we want to support this UX pattern?

**Comment by chrisconnors-ibm** [comment]
@SpencerReynolds18 ALL rows in the table, or all rows in the current view, or…

One of the main drivers for the expanding rows is to stash expensive to get (slow) details there, so for teams taking advantage of that pattern, a 'toggle all' switch would be the 'show me all the spinners' switch.

**Comment by aagonzales** [comment]
I think this is something that we can still add.

**Comment by shixiedesign** [comment]
### Adding a chevron to header for Expanding/collapsing all function
- chevron size 16x16
- center aligned with text
- 16px from left 
- this chevron should not be available by default, but a knob product designer may turn on if situation is appropriate. 
### 📖 Guidance to add
In our guidance, we should warn the potential down side of this pattern: 
> One of the main drivers for the expanding rows is to stash expensive to get (slow) details there, so for teams taking advantage of that pattern, a 'toggle all' switch would be the 'show me all the spinners' switch.

### Spec images

Expandable data table with expand-all-chevron 

![image](https://user-images.githubusercontent.com/15144993/57668928-b9a7b780-75ce-11e9-899c-626283d6fbe8.png)

Expandable & selectable data table with expand-all-chevron 

![image](https://user-images.githubusercontent.com/15144993/57672204-c92dfd00-75dc-11e9-8c10-0201559b58ac.png)
