### ISSUE TITLE
Add light variant on Toggle

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#6794]
Just like `TextArea` and `TextInput`, we would also need a light variant for `Toggle` when it's being used in white background, for example:
when using a disabled Toggle on white background:
![image](https://user-images.githubusercontent.com/10108576/92513005-a403cb80-f1dd-11ea-9190-b6af8fa80c69.png)

while the expectation is:
![image](https://user-images.githubusercontent.com/10108576/92513094-c3025d80-f1dd-11ea-90b1-73b43df43186.png)

development.

### "Must have" functionality

Able to see the background of the toggle, it should not blend in to the white background when it's disabled

Internal issue: https://github.ibm.com/wdp-gov/tracker/issues/31292

**Comment by jnm2377** [comment]
cc: @carbon-design-system/design

**Comment by aagonzales** [comment]
From this issue looks like there disabled toggle in data table should have a different value so it works correctly. https://github.com/carbon-design-system/carbon/issues/7351

I actually think we can just make this change across the board on disabled toggle and not need a `light` variant at all. 

![image](https://user-images.githubusercontent.com/11670886/116116073-5a8ac280-a680-11eb-909a-b6efd9d4c0c3.png)


Related issue: https://github.com/carbon-design-system/carbon/issues/5932

**Comment by tw15egan** [comment]
@aagonzales should we be using the new tokens?
