### ISSUE TITLE
TreeView for vanilla JS?

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#6795]
Vanilla JS

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Is the TreeView in vanilla JS available soon? I'm really looking forward in working with it. I know it's released as a react component but for vanilla JS only the scss was included in the download.

Thank you in advance! And I love the work you guys are doing.

Kind regards,

**Comment by emyarod** [comment]
this likely will not be implemented until the official release of the TreeView component at the earliest, since the component is still in an experimental phase and undergoing extensive research and testing

**Comment by ghost** [comment]
Alright! Thank you for your reply

Do you have any idea when it will be released? I guess there is no telling hu?

**Comment by emyarod** [comment]
there is currently no time table as it depends heavily on some accessibility research, and the current component is still in experimental stage. You can track its progress under the [treeview label](https://github.com/carbon-design-system/carbon/labels/component%3A%20treeview) in the Carbon GitHub issue tracker and over at https://github.com/w3c/aria/issues/1311

**Comment by ghost** [comment]
Thanks! :)
