### ISSUE TITLE
Passing size as props for Modal component does not work

### ISSUE THREAD

**Issue by Shubha999** [carbon-design-system/carbon#6796]
## What package(s) are you using?

- [ ] `carbon-components`
- [7.5.1 ] `carbon-components-react`

## Summary
I am using Modal component from carbon components react in my project and want to pass props for size, so that modal can be sized differently as per business requirements. 
I tried all the size types listed in the modal component, i.e "sm", "", "lg" but none is working.

Can you please help on how to fix this issue for passing size to modal component.

## Relevant information

Attaching sample code below for reference:

<Modal
        {...this.props}
        size="lg"
></Modal>

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by Shubha999** [comment]
Thanks for following up, I added the code here: https://codesandbox.io/s/cocky-meninsky-n1jw0?file=/src/index.js
and that seems to be working fine. 
I might be need to debug the code for my project which is acting weird. 
I will close the issue, thanks.
