### ISSUE TITLE
Can i use Carbon Design System in ASP.NET Core?

### ISSUE THREAD

**Issue by mitulsrv** [carbon-design-system/carbon#6800]
I am ASP.NET CORE developer and i want to use carbon design system in my apps, so any ways so that i can use it?
Thank you

**Comment by emyarod** [comment]
you can import the stylesheets to your application, or I assume you can try something like [this](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio) if you want to use the React components

**Comment by mitulsrv** [comment]
Okay will do, carbon design system proviede html template for it?

**Comment by emyarod** [comment]
Carbon only provides UI components and not templates

**Comment by mitulsrv** [comment]
okay
