### ISSUE TITLE
Use of --ibm as a custom property name prefix may not be suitable for all

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#6812]
https://github.com/carbon-design-system/carbon/blob/9470f86386ae6e4eb00113b99a10f3ff69bb7b1a/config/stylelint-config-carbon/rules/limit-language-features.js#L56

```
    // Custom property
    // Specify a pattern for custom properties.
    'custom-property-pattern': 'ibm-.+',
```

Any products using the carbon config will be forced to prefix custom properties with 'ibm' this will confuse these properties with carbons own properties.

Alternatively or in addition to updates we should tell the user what the pattern is e.g. 
```
    // Custom property
    // Specify a pattern for custom properties.
    'custom-property-pattern': [
      'ibm-.+',
      {
        message: "custom-property-pattern: Carbon expects '--ibm' prefix'",
      },
    ],
```

**Comment by joshblack** [comment]
Hey @lee-chase! 👋 

Totally agree, let's get rid of this. If anything our project would use `c-` and not `ibm-`, as well.
