### ISSUE TITLE
[Large loading component]: Loading has different size to defined on carbondesignsystem website

### ISSUE THREAD

**Issue by djj-ashton** [carbon-design-system/carbon#6814]
## What package(s) are you using?

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

The Carbon Design Website Defines the .bx--loading class as having a width/height of 88px/5.5rem.

The value defined for .bx--loading in the file packages/components/src/components/loading/_vars.scss is 10.5rem

It looks like the ultimate displayed spinner is the correct size as there is a padding of 40px (which times 2) reduces the spinner size down to 88px.

However, it does not explain the discrepancy between the .bx-loading class value defined on the website and the value for the same class used in the code.

**Comment by djj-ashton** [comment]
I have noticed that the small-loading spinner has a similar issue

**Comment by emyarod** [comment]
cc @carbon-design-system/design any thoughts about this discrepancy in loading spinner size?

**Comment by laurenmrice** [comment]
The large loader should be 88px/5.5 rem and the small loader should be 16px/1rem. There should be no extra padding
