### ISSUE TITLE
AccordionItem children inherit parent's state

### ISSUE THREAD

**Issue by hannah-austin93** [carbon-design-system/carbon#6821]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When you try and nest a series of AccordionItems the child components inherit their parent's state and remain active. 

> Is this issue related to a specific component?
Accordion, AccordionItem

> What did you expect to happen? What happened instead? What would you like to
> see changed?
We expected each Accordion to be separately expandable but instead child Accordions inherit their parent's open state. We expected that we would be able to create a Tree View for example like in Material UI https://material-ui.com/components/tree-view/

> What browser are you working in?
Google Chrome v85

> What version of the Carbon Design System are you using?
7.15.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Offering IBM iX client project. 

## Steps to reproduce the issue

1. Add an Accordion and an AccordionItem
2. Add another AccordionItem as a child of the first AccordionItem

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/winter-dew-k8lnp?file=/src/index.js

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/61142875/92902519-3e038800-f419-11ea-9016-db22ee7cb8bb.png)

- Notes

**Comment by hannah-austin93** [comment]
By adding the following code you can get the children to expand and contract but the chevron is stuck upside down. 
`& .bx--accordion__item--collapsing .bx--accordion__content {
    display: none;
  }`

**Comment by tw15egan** [comment]
I do not believe nested Accordions are a supported pattern in the Carbon library. We are working on a `TreeView` component that is more suited for this use-case

**Comment by motou** [comment]
We have encountered a similar issue with Accordion. If a Dropdown is placed in AccordionItem, then after collapsing the accordion, the dropdown stays and the accordion cannot be closed.

**Comment by tw15egan** [comment]
@motou that seems like a bug, do you mind creating a reduced test case on CodeSandbox and creating a new issue for that? 

Going to close this issue as resolved (`TreeView`) / unsupported (nested accordions)
