### ISSUE TITLE
Publish storybook config including theme and type addons

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#6828]
### Summary

In developing component libraries extending or utilizing Carbon it would be useful to be able to include a common storybook config. It would be incredibly useful to be able to utilize the theme and type storybook addons.

This likely only involves development

### Justification

Each component library created using Carbon as a basis currently has to implement its own addons for theme and type if they wish to be able to demonstrate components using these themes.

This project does not have theme switching - https://github.com/carbon-design-system/ibm-cloud-paks
This project has it's own implementation - https://github.com/carbon-design-system/ibm-security

### "Must have" functionality

Theme addon

**Comment by sstrubberg** [comment]
Let me know if this is still applicable. Happy to re-open.
