### ISSUE TITLE
Component proposal: Context menu

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#6830]
Related: #3764 #6426

# Summary

This proposal is to discuss the addition of a context-menu (right-click menu) component / pattern. It may also be used as an ehanced overflow menu in case a product team does not want to override the browser's context menu for various reasons.

### Justification

Complex and data-heavy web applications have reached a state where they often replace desktop applications or are the main touchpoint for a given workflow. In web terms, overflow menus (mostly indicated by a meatball icon) are the substituion for most interactions a native application would use the context menu for. In many cases this model is not sufficient since it requires an additional interaction by the user, clicking away from the context they want options for. Also, placing an overflow menu trigger in the UI is often not feasible due to special layouts such as a data grid where the user has multiple options for a cell.

There are some examples of web applications that use a custom context menu due to the above mentioned reasons. Among others, these examples include:

<details>
<summary>Box</summary>

![box](https://user-images.githubusercontent.com/28265588/93094235-efb4ea00-f6a1-11ea-8f59-0217a060c1c2.gif)
</details>

<details>
<summary>G Suite (Google Docs, Sheets, etc.)</summary>

![google-sheets](https://user-images.githubusercontent.com/28265588/93094304-078c6e00-f6a2-11ea-9b1b-a6df302be3f0.gif)

</details>

<details>
<summary>Slack (web)</summary>

![slack](https://user-images.githubusercontent.com/28265588/93094364-1d9a2e80-f6a2-11ea-8ecd-ebf341dcf51c.gif)
</details>

<details>
<summary>CodeSandbox</summary>

![codesandbox](https://user-images.githubusercontent.com/28265588/93094412-2db20e00-f6a2-11ea-8a9e-70a5e18656ab.gif)
</details>

<details>
<summary>Pages, Keynote and Numbers for iCloud</summary>

![icloud-pages](https://user-images.githubusercontent.com/28265588/93094522-4e7a6380-f6a2-11ea-849e-3eba4b52d581.gif)
</details>

### Desired UX and success metrics

The user has a nested list of options related to their current context. If applicable, the sortcut / keyboard command to trigger an action is displayed next to the action to progressively educate the user on how to become more efficient with the web application.
Options that have children cannot be disabled themselves so that the user can always explore the options (in other words: if all child options are disabled, the parent option is still availble to expand).
Options can be a selection (radio behaviour).

### "Must have" functionality

Visibility / rendering of component can be controlled by code. Absolute position of the component on the screen can be controlled by code.

### Available extra resources

Sample mockup to illustrate proposal
![mockup](https://user-images.githubusercontent.com/28265588/93094873-bfba1680-f6a2-11ea-9fa1-fde7e9590154.png)

We should be able to support the implementation and design of this component with a bit of help from the Carbon team.

**Comment by joshblack** [comment]
Hey @janhassel!

We took a look at this during our proposal grooming session this sprint and love the component 🔥 

I think the only feedback from the session was around visuals, @laurenmrice do you have a second to list out any changes that you would hope to see for it? Then either your team @janhassel could put something together or we could try and get this added to a sprint (which might take a bit)

**Comment by janhassel** [comment]
@joshblack Good to hear! If we get a list of visual changes and feedback I'll try to secure some time for this and come back to you once I know more about if, how and when we can support this effort.

**Comment by laurenmrice** [comment]
Hey Jan 👋 

Here are the design specs for the context menu! Basically the same thing as you have above but just detailing out the increments, etc. We can have you pair up with a dev on our team while you are contributing the code in case you have any questions.

Would you also be able to provide dev/design documentation guidance for the context menu? We can help revise any content that is written.


### Styles spec
---------
![Context menu - 32px row and 16px padding](https://user-images.githubusercontent.com/43969356/97744611-ed75e600-1abd-11eb-84b7-1fd75f1f04e4.png)

### Structure spec
---------
![Context menu - 32px row and 16px padding - spec](https://user-images.githubusercontent.com/43969356/97743530-3167eb80-1abc-11eb-9ed5-f093c141b90e.png)

### UI example
---------
![body-short-01 (no icon)](https://user-images.githubusercontent.com/43969356/97745511-5ca00a00-1abf-11eb-8809-0016eec3b158.png)

**Comment by janhassel** [comment]
@laurenmrice Thanks a lot for the detailed visual specs, looks great!
Before I start working on this, what would be the preferred strategy here? Should this be a separate component called `ContextMenu` or should this be an update and extension to the existing `OverflowMenu`? I see use cases where a nested overflow menu would make a lot of sense for teams and visually they're relatively close. What do you think?

**Comment by laurenmrice** [comment]
This should be a separate component called `Context Menu`. Just curious, is this the typical standard name for this kind of component (Context menu, contextual menu, control menu)?  @janhassel

**Comment by janhassel** [comment]
Hey @laurenmrice, I was able to push a first version of this component with PR #7350. Which developer could I reach out to discuss the implemenation and remaining steps?

**Comment by davidicus** [comment]
Hey all! The AI apps organization is definitely interested in consuming this ASAP. Is there any ETA on when this would be available. I see in the PR that there hasn't been a response since before the holidays. Thanks for the great work on this component!

**Comment by laurenmrice** [comment]
@davidicus  Yes! Definitely still interested in getting this in! Jan opened a PR and it is going through some reviews at the moment. 👍🏻

**Comment by gillibrand** [comment]
Any status updates on this?

**Comment by laurenmrice** [comment]
@gillibrand The context menu is still going through some accessibility reviews in the PR that is open. You can follow the most recent updates on it here: https://github.com/carbon-design-system/carbon/pull/7350
