### ISSUE TITLE
Carbon Tabs and Tab Styles broken 

### ISSUE THREAD

**Issue by Pramodnagarajarao** [carbon-design-system/carbon#6835]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Hi Team. 
1. I'm using Carbon and Carbon-components-react for my UI product development. The versions I have in my package.json are:
```
    "carbon-components": "^10.15.0",
    "carbon-components-react": "7.15.0",
```
2. For the Tabs and Tab component I see a text with a `V` added breaking the code/build we have. 
<img width="420" alt="Screen Shot 2020-09-14 at 3 51 50 PM" src="https://user-images.githubusercontent.com/8497954/93145888-54704480-f6a2-11ea-8aa6-ce03cbf4d5e1.png">
3. The reason being the following CSS media query isn't present:

```
@media (min-width: 42rem)
.bx--tabs-trigger {
    display: none;
}
```
4. Seems like it's similar to https://github.com/carbon-design-system/carbon/issues/6798

> Is this issue related to a specific component?

Carbon `<Tabs />` and `<Tab />`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

It would be great if you can hide this.

> What browser are you working in?

Chrome and Safari

> What version of the Carbon Design System are you using?

```
    "carbon-components": "^10.15.0",
    "carbon-components-react": "7.15.0",
```

## Additional information

- Screenshots or code
**index.js**
<img width="1654" alt="Screen Shot 2020-09-14 at 4 02 56 PM" src="https://user-images.githubusercontent.com/8497954/93146524-e9c00880-f6a3-11ea-9db1-93a2e0f79732.png">

**package.json**
<img width="1505" alt="Screen Shot 2020-09-14 at 4 03 24 PM" src="https://user-images.githubusercontent.com/8497954/93146529-edec2600-f6a3-11ea-9006-e4a24ebe1a3e.png">

Please take a look. Thank you.

**Comment by emyarod** [comment]
I wasn't able to reproduce this when I recreated it in code sandbox, can you provide a link to your code sandbox example?

**Comment by Pramodnagarajarao** [comment]
Hi there,

Thanks a lot for taking a look. I can reproduce this on my sandbox. I work for IBM at SVL and also can consistently reproduce on the IBM Product I'm currently working on (both on dev/prod). This is same as https://github.com/carbon-design-system/carbon/issues/6798.

1. Link for the sandbox: https://codesandbox.io/s/adoring-forest-phpmr?file=/src/index.js
2. If you can't access above Sandbox, then all I have in the above Sandbox is an edit to `package.json` and `index.js` files from the basic sandbox Carbon provides. Have pasted the content of those 2 files below for your reference.

**`package.json`**
```
{
  "name": "codesandbox",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "carbon-components": "^10.15.0",
    "carbon-components-react": "7.15.0",
    "carbon-icons": "latest",
    "react": "16.10.2",
    "react-dom": "16.10.2",
    "react-scripts": "2.1.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "browserslist": [">0.2%", "not dead", "not ie <= 11", "not op_mini all"]
}
```
**`index.js`**

```
import React from "react";
import { render } from "react-dom";
import { Tabs, Tab } from "carbon-components-react";

const App = () => (
  <div>
    <Tabs>
      <Tab id="tab-1" label="Tab label 1"></Tab>
      <Tab id="tab-2" label="Tab label 2"></Tab>
    </Tabs>
  </div>
);

render(<App />, document.getElementById("root"));
```

**Resulting HTML:**
![image](https://user-images.githubusercontent.com/8497954/93374090-15113780-f80b-11ea-83bc-1a821e8349e0.png)


Please let me know if you have any queries. Thank you.

**Comment by emyarod** [comment]
this seems to be a case of having outdated styles or components, here is what it looks like on the latest versions: https://codesandbox.io/s/optimistic-grass-pe9zg

**Comment by tw15egan** [comment]
Seems like its because the styles are being updated to `10.19.0` and the react package is pinned at `7.15.0`.
```
    "carbon-components": "^10.15.0",
    "carbon-components-react": "7.15.0",
```

I would ensure your styles / react pacakge are locked to the same verison number, either `10.15.0` / `7.15.0` or `10.19.0` / `7.19.0`
