### ISSUE TITLE
Pagination component hung up when totalitems is a big number

### ISSUE THREAD

**Issue by fred104** [carbon-design-system/carbon#6836]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the `Pagination` react component, if you set the `totalitems` to a big number, i.e. 999999, the page will be hung up and has no response.

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Should work well.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.15.0. Also tested on the [react storybook.](https://react.carbondesignsystem.com/?path=/story/pagination--multiple-pagination-components) 

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Resilient. 10/20 code freeze.

## Steps to reproduce the issue

1. Go to [`Pagination` component storybook](https://react.carbondesignsystem.com/?path=/story/pagination--multiple-pagination-components)
2. Set `totalitems` to 99999 and you will see browser is not getting any response now.
![image](https://user-images.githubusercontent.com/1077859/93180859-51408b80-f76a-11ea-9191-bb92ee590fe6.png)

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

Sandbox is created, but it won't render. https://codesandbox.io/s/vibrant-napier-8cufe?file=/src/index.js
![image](https://user-images.githubusercontent.com/1077859/93181458-11c66f00-f76b-11ea-9939-ba92e96fbd5e.png)

## Additional information

- Screenshots or code
```jsx
    <Pagination
      totalItems={99999999}
      page={1}
      pageSize={10}
      pageSizes={[10, 20]}
    />
```
- Notes

**Comment by fred104** [comment]
Looks like there is a limitation to `select` which the number of `option` can't be over 10000 on the browser. 

Ref: https://chromium.googlesource.com/chromium/blink.git/+/master/Source/core/html/HTMLSelectElement.cpp#77

**Comment by fred104** [comment]
We created another issue for pagination enhancement. Probably a better way to deal with this issue. 

https://github.com/carbon-design-system/carbon/issues/6884

**Comment by KCollender** [comment]
This is a work around that our team is currently using for this issue.
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Pagination/Pagination.js#L245-L255

The fix limits the selector to max 50 pages.

```
renderSelectItems = (total) => {
    const maxPages = 50;
    let counter = 1;
    let itemArr = [];
    let finalTotal = total;
    if (total > maxPages) {
        finalTotal = maxPages;
    }
    while (counter <= finalTotal) {
        itemArr.push(
            <SelectItem key={counter} value={counter} text={String(counter)} />
        );
        counter++;
    }
    return itemArr;
};
```

**Comment by joshblack** [comment]
Hey there! 👋  As noted above, this is a browser limitation due to the native `<select>` element. I'm going to go ahead and close this out since we can't do much about it, but feel free to comment if you feel like this was closed in error!
