### ISSUE TITLE
Multi Select not working on IBM website and vanilla.js components 

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#6839]
## Title line template: [Title]:Multi Select not working on IBM website and vanilla.js components 

-->

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

When is copy and paste the code for the multiselect it's not working.
It's also not working on the IBM website.

> Is this issue related to a specific component?
Multiselect 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Have it work

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
Latest version 

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox) for easier testing and debugging?
