### ISSUE TITLE
Property '$$typeof' is missing in type 'CarbonIconType' but required in type 'ForwardRefReturn<unknown, unknown>'.ts(2741)

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#6847]
See error when using the sample code of Custom icon Tooltip 
https://react.carbondesignsystem.com/?path=/story/tooltip--only-custom-icon

![image](https://user-images.githubusercontent.com/14806866/93274896-0d0cb580-f781-11ea-9cc3-48add5731a55.png)

![image](https://user-images.githubusercontent.com/14806866/93274916-18f87780-f781-11ea-8eca-d0d295ed5721.png)

**Comment by joshblack** [comment]
Hi there @zhenwan! 👋 

Unfortunately, we don't ship any TypeScript types for the components from Carbon. They are community-contributed over on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react) and so any changes would need to be made by the community there.

Hope this helps!
