### ISSUE TITLE
[NumberInput] Missing docs for props

### ISSUE THREAD

**Issue by jonguenther** [carbon-design-system/carbon#6848]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
The storybook for `carbon-components-react` has no documentation / missing props description for `NumberInput` ever since storybook version was updated.

On a related note, the code examples for components often don't really help in the new storybook, since the props are spread in and thus not viewable by external developers. An example from `NumberInput`:

```jsx
() => {
const { numberInputArrowTranslationIds, ...rest } = props();
return (
  <NumberInput
    translateWithId={(id) => numberInputArrowTranslationIds[id]}
    {...rest}
  />
);
}
```
Link: https://react.carbondesignsystem.com/?path=/docs/numberinput--default

**Comment by tw15egan** [comment]
Prop table is working as expected now, just pushed up a PR (https://github.com/carbon-design-system/carbon/pull/7940) that will resolve the latter part of the issue. Closing this as resolved.
