### ISSUE TITLE
icons-react has incomplete icon library

### ISSUE THREAD

**Issue by dghelm** [carbon-design-system/carbon#6857]
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Icons library does not match with icons-react library. Missing at least PageScroll and StackedScrolling1.

> Is this issue related to a specific component?

icons-react library

> What version of the Carbon Design System are you using?

10.17.0 of @carbon/icons-react from npm

**Comment by tw15egan** [comment]
So, after taking a look, it seems like we're surfacing the wrong data for some of the icons. In this particular instance, you're looking for 

`WatsonHealthStackedScrolling_132` and `WatsonHealthPageScroll32`

https://codesandbox.io/s/ecstatic-ptolemy-rm28l?file=/src/index.js:199-223

Understandably, these are not the friendliest of names! We'll create an issue to fix some of these names, and surface the correct names on the website.

For now, I'd use this list as a reference: https://github.com/carbon-design-system/carbon/blob/master/e2e/icons-react/__snapshots__/PublicAPI-test.js.snap

Closing this as resolved, but feel free to reopen if you've got any other issues 👍
