### ISSUE TITLE
how to work Pagination in data table

### ISSUE THREAD

**Issue by nbt1234** [carbon-design-system/carbon#6863]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

**Comment by tw15egan** [comment]
@nbt1234 can you please elaborate so we can better assist you? Thanks!

**Comment by LukaszGrela** [comment]
There is no clear enough example in the storyboards on the datatable with pagination usage. I've found [this page](https://www.carbondesignsystem.com/developing/react-tutorial/step-3#add-pagination) Which I already done myself with trial and error. However this is not a built in solution like [this](https://www.carbondesignsystem.com/components/data-table/usage) would suggest (Pagination table bar). There is also a problem with using pagination in that way, the filtering (Search) only affects the data from `rows` which the pagination sliced, so it searches only current page not whole results. Overriding the `filterRows` wont help as it operates on the `rows` data.

I think a built in table solution is missing here, that will work along with other table features. e.g. `TablePagination` that will be part of the table. Obviously we can only use `Table` to render rows and do filter/pagination outside of it but then the table is somewhat missing the functionality.
