### ISSUE TITLE
CopyButton is inaccessible in Windows High Contrast Mode

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6875]
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

The code snippet copy buttons in singleline and multiline are inaccessible in both Edge and Firefox

Singleline
![image](https://user-images.githubusercontent.com/40970507/93831063-7ab05a00-fc37-11ea-8443-1b60f5cf6d28.png)

Multiline
![image](https://user-images.githubusercontent.com/40970507/93831070-80a63b00-fc37-11ea-9f13-87685cfdf5a8.png)

**Comment by tw15egan** [comment]
Fixed on latest: 
![Screenshot 2021-03-04 181329](https://user-images.githubusercontent.com/11928039/110057366-55ab3180-7d15-11eb-864d-a13703359680.png)
