### ISSUE TITLE
Content Switcher is inaccessible in Windows High Contrast Mode

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6877]
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

The active section in the content switcher is inaccessible in Windows High Contrast Mode
![image](https://user-images.githubusercontent.com/40970507/93832839-910ce480-fc3c-11ea-8cef-0e6e12ad6b21.png)

**Comment by tw15egan** [comment]
![Screenshot 2021-03-04 174957](https://user-images.githubusercontent.com/11928039/110055563-0f080800-7d12-11eb-8370-9312757ae9ed.png)

Looks like this is resolved 👍🏻
