### ISSUE TITLE
Various advanced DataTable features are inaccesible in Windows High Contrast Mode

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6878]
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

Various advanced features of the DataTable are inaccessible in Windows High Contrast Mode
- the overflow menu elipsis
![image](https://user-images.githubusercontent.com/40970507/93833619-bb5fa180-fc3e-11ea-82b4-abd6e973cc0e.png)

- various iconography in toolbar
![image](https://user-images.githubusercontent.com/40970507/93833629-c3b7dc80-fc3e-11ea-8d18-2f2081be8e85.png)

- the chevron icon for expansion
![image](https://user-images.githubusercontent.com/40970507/93833640-ca465400-fc3e-11ea-9f8d-9eb7d400d396.png)

- the headers used for sorting are indistinguishable
![image](https://user-images.githubusercontent.com/40970507/93833645-d16d6200-fc3e-11ea-8b17-f616562b4918.png)

**Comment by tw15egan** [comment]
Verified fixed on latest

![expansion](https://user-images.githubusercontent.com/11928039/110993893-cad9c080-832c-11eb-9f23-16d8e240508c.png)
![overflow](https://user-images.githubusercontent.com/11928039/110993895-cad9c080-832c-11eb-98d8-df0d730f7473.png)
![sorting](https://user-images.githubusercontent.com/11928039/110993896-cb725700-832c-11eb-916b-49168bb31d5d.png)
![toolbar](https://user-images.githubusercontent.com/11928039/110993897-cb725700-832c-11eb-9650-c0ac8736b738.png)
