### ISSUE TITLE
Leaking background in date picker when a day is selected in the first weeks of the next month

### ISSUE THREAD

**Issue by petersandor** [carbon-design-system/carbon#688]
## Detailed description

Background colour of a selected day in the datepicker calendar is leaking when the selected day is in one of the first weeks of the following month. See gif below 👇 

![carbon-datepicker-bug](https://user-images.githubusercontent.com/3933866/38420700-f8f4ba6c-39a4-11e8-9127-d527eacb307e.gif)

You can clearly see a blue line below day `31` which is in fact the background colour of day `7` from next month.

This can be reproduced in example section of the date picker documentation - http://carbondesignsystem.com/components/date-picker/code

> Is this issue related to a specific component? 

Yes, datepicker.

> What did you expect to happen? What happened instead? What would you like to see changed?

No backgrounds should leak from selected days in following month from the bottom of the datepicker calendar.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

8.16.8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Product, shipping May 1st.

## Steps to reproduce the issue
See gif above. ☝️

**Comment by aledavila** [comment]
Closing. Date picker has since been updated and issue is no longer persistent.
