### ISSUE TITLE
FileUploader is inaccessible in Windows High Contrast Mode

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6881]
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

The X icon for removing an added file is innaccessible 
![image](https://user-images.githubusercontent.com/40970507/93834161-7a688c80-fc40-11ea-8116-e27b45647b43.png)

**Comment by tw15egan** [comment]
Resolved on latest: 
![Screenshot 2021-03-04 181224](https://user-images.githubusercontent.com/11928039/110057280-2eecfb00-7d15-11eb-8b4f-0908f8faa42b.png)
