### ISSUE TITLE
expandable table row, does not have a way to create <td> as mentioned in the documentation

### ISSUE THREAD

**Issue by PAnilReddy** [carbon-design-system/carbon#6885]
How should we use the expandable table to achieve the below layout. The expanded row columns should also be align with the headers. I see that <TableExpandedRow> has colSpan but that creates only one <td> with colspan mentioned. But in this case I want to get multiple values aligned to header.
I have written a sandbox code, so if someone can help me in achieving this layout. Thank you
https://codesandbox.io/s/withered-dream-6kvyp?file=/index.js
Its mentioned on the documentation at the following location
https://www.carbondesignsystem.com/components/data-table/usage/

![image](https://user-images.githubusercontent.com/44162180/93875939-937e4580-fcf3-11ea-89a0-b80932fb6b55.png)

@josh ( Josh Black)
Discussed the same on slack and here is the conversation
Hi Anil! That’s a great question, and thank you so much for putting together a codesandbox, it really helps
For your layout question, I think there was a change that for some reason added in an inner td. In the past, you were able to drop in td values that would align to the table columns but it looks like they might not be possible right now.
Thanks for bringing this up, let me go make an issue and look into it and circle back on this

**Comment by sstrubberg** [comment]
Hey @PAnilReddy, thanks for drumming up the issue. Anything you're wanting to do with the <td>, you'll need to write custom styles. What you're seeing in the docs is just a visual example.
