### ISSUE TITLE
Can someone point us to research/validation around the wording for "compact" and "short" in the context of sizes

### ISSUE THREAD

**Issue by andreagmann** [carbon-design-system/carbon#6887]
## Summary

We have concerns around the user's understanding of the words "compact" and "short" and how they are different, and which one is actually smaller than the other.

## Relevant information

As seen here https://www.carbondesignsystem.com/components/data-table/usage#sizing

**Comment by juliabamford** [comment]
Another concern that I see is that we don't know how these would be translated. We could end up with some odd or confusing results. 

I would strongly recommend that we update the labels to be:
- Extra short
- Short
- Medium (default)
- Tall

In this scheme, the relationship between the sizes is clearly defined.

**Comment by jnm2377** [comment]
We are actually updating all our size props to be consistent across our components, and these are being deprecated in data table for `xs, sm, md, lg, xl`.  You can view the PR here: https://github.com/carbon-design-system/carbon/pull/8452
