### ISSUE TITLE
Bug: V1 data table

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#689]
## Detailed description
V1 table bug in firefox.
https://github.ibm.com/carbon/issues/issues/305#issuecomment-5399316

This may not actually be a problem anymore. Its an old issue from a different repo and its on the deprecated  version of data tables.

> Is this issue related to a specific component? 

V1 Data tables

> What browser are you working in? 

Firefox

**Comment by joshblack** [comment]
Closing as this was closed upstream. Feel free to re-open!
