### ISSUE TITLE
Character limit in tabs impossible to override

### ISSUE THREAD

**Issue by colsonrice** [carbon-design-system/carbon#6898]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
We need more than 17 characters for a tab in our UI. When we try to override the CSS inline, it will never let us go over that character limit. 

> Is this issue related to a specific component?
Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?
We expected the ability to determine the amount of characters in a tab, but our tab title is always truncated. 

> What browser are you working in?
Google Chrome

> What version of the Carbon Design System are you using?
Carbon 10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Spectrum Discover - next ship date is in November. 

## Steps to reproduce the issue

1. Go to https://codesandbox.io/s/gpcnc?file=/index.js
2. Attempt to change CSS to allow for more characters in tab title.

**Comment by emyarod** [comment]
are you looking for something like this? https://codesandbox.io/s/immutable-breeze-9n2o5

you should be able to use CSS to adjust the tab width, provided the tab list container has `flex-shrink: 0;` and  `width: auto;`

**Comment by colsonrice** [comment]
Hey, this works! Thanks so much!

**Comment by tw15egan** [comment]
Closing as resolved, feel free to reopen if you've got any other issues!
