### ISSUE TITLE
HeaderMenu component not align properly in the Header for Chrome browser and Firefox browser looks fine

### ISSUE THREAD

**Issue by Incarnation** [carbon-design-system/carbon#6899]
CodeSanbox URL: https://codesandbox.io/s/header-with-actions-and-nav-forked-32xkg

The HeaderMenu on the top right corner is not aligned properly in the Header shown below screenshot and this happen in Chrome browser only and Firefox seem to be working fine

Chrome: 
![image](https://user-images.githubusercontent.com/5199303/94054049-157c7600-fda9-11ea-9a6b-3637c85fedcf.png)

Firefox seems to be fine:
![image](https://user-images.githubusercontent.com/5199303/94054092-2927dc80-fda9-11ea-9ed1-5ed7c519649d.png)

**Comment by tw15egan** [comment]
I believe `HeaderMenu` is only supported nested under `HeaderNavigation` out of the box.

Quick workaround would be to add `.bx--header__global { align-items: flex start; }`
