### ISSUE TITLE
Dropdown hover: color bug

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/carbon#690]
## Detailed description

> Is this issue related to a specific component? 

Dropdown.

> What did you expect to happen? What happened instead? What would you like to see changed?

The Dropdown for Multiselect and Regular dropdown are different. 

Dropdown = `$brand-01` at 100%. 
Multiselect Dropdown = `$brand-02` @ 10%. 

All Dropdown drawer hovers should be `$brand-02` @ 10%. 

> What browser are you working in? 

Chrome.

**Comment by tw15egan** [comment]
Does this mean the text does not switch to `inverse-01` on hover anymore?

![screen shot 2018-04-11 at 9 35 06 am](https://user-images.githubusercontent.com/11928039/38623569-a24de4e8-3d6b-11e8-86cc-dcac1b4f2608.png)

**Comment by bsonefeld** [comment]
@tw15egan Yes, the text should be `text-01` with an underline on hover.
