### ISSUE TITLE
[Cloud Pak for Data System] Inline filtering results

### ISSUE THREAD

**Issue by Grace-Harkin1** [carbon-design-system/carbon#6902]
### Summary

The Cloud Pak for Data System design team has explored  a pattern of listing filter results to the right of inline filters.

### Justification

Since our users are filtering vast amounts of information, showing them the results quickly gives them an overview of what items they can further investigate. This helps the user save time especially if the filter produces many results. 

### Desired UX and success metrics

The user should be able to apply multiple filters and then see a list of how many items and what kind of items the filters apply to. For example, if the user is filtering hardware components, and are allowed to filter by health status and by component type, their results may be "15 server nodes, 1 spine switch" etc.

### Specific timeline issues / requests

We have provided this design to our development team and they are working to include it in our November release.

![1 4 4_Hardware overview_graphical_filter_selected](https://user-images.githubusercontent.com/64492316/94085114-0bb03e00-fdbc-11ea-9b66-9a6de4f80526.png)

[Redlines](https://pages.github.ibm.com/Tiffany-Tran/hdm-design/CDPS_Hardware%20overview_Graphical_1.0.7.4/index.html#artboard2)

**Comment by tw15egan** [comment]
I believe this pattern already exists under Filterable Multiselect, with the `inline` prop passed into the component. [Here is an example](http://localhost:9000/iframe.html?id=multiselect--filterable&knob-MultiSelect%20ID%20(id)=carbon-multiselect-example&knob-Title%20(titleText)=Multiselect%20title&knob-Helper%20text%20(helperText)=This%20is%20helper%20text&knob-UI%20type%20(Only%20for%20`%3CMultiSelect%3E`)%20(type)=inline&knob-Field%20size%20(size)=undefined&knob-Dropdown%20direction%20(direction)=bottom&knob-Label%20(label)=MultiSelect%20Label&knob-Form%20validation%20UI%20content%20(invalidText)=Invalid%20Selection&knob-Warning%20state%20text%20(warnText)=Selecting%20more%20items%20may%20increase%20processing%20time&knob-Listbox%20menu%20icon%20translation%20IDs%20(for%20translateWithId%20callback)={%22close.menu%22:%22Close%20menu%22,%22open.menu%22:%22Open%20menu%22,%22clear.all%22:%22Clear%20all%22,%22clear.selection%22:%22Clear%20selection%22}&knob-Selection%20feedback=top-after-reopen). Let me know if that helps!

**Comment by Grace-Harkin1** [comment]
@tw15egan Hm is there another link possibly? That one isn't working for me.

**Comment by tw15egan** [comment]
🤦 I linked my local dev environment. [This one should work!](https://react.carbondesignsystem.com/iframe.html?id=multiselect--filterable&knob-MultiSelect%20ID%20(id)=carbon-multiselect-example&knob-Title%20(titleText)=Multiselect%20title&knob-Helper%20text%20(helperText)=This%20is%20helper%20text&knob-UI%20type%20(Only%20for%20`%3CMultiSelect%3E`)%20(type)=inline&knob-Field%20size%20(size)=undefined&knob-Dropdown%20direction%20(direction)=bottom&knob-Label%20(label)=MultiSelect%20Label&knob-Form%20validation%20UI%20content%20(invalidText)=Invalid%20Selection&knob-Warning%20state%20text%20(warnText)=Selecting%20more%20items%20may%20increase%20processing%20time&knob-Listbox%20menu%20icon%20translation%20IDs%20(for%20translateWithId%20callback)={%22close.menu%22:%22Close%20menu%22,%22open.menu%22:%22Open%20menu%22,%22clear.all%22:%22Clear%20all%22,%22clear.selection%22:%22Clear%20selection%22}&knob-Selection%20feedback=top-after-reopen)

**Comment by Grace-Harkin1** [comment]
@tw15egan Do any existing patterns provide the results of the filter? We were providing them to the right of the "Clear all" button

**Comment by tw15egan** [comment]
No, there are no patterns available to handle that, but you should be able to hook into the filterable multi-select `onChange`, and pull the values and do calculations based on the filtered results from there and place them wherever you'd like 👍
