### ISSUE TITLE
Paginator performance/crash issue

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon#6905]
The paginator is not designed to be used with many pages. We have results that have up to 100k results,
and the best the paginator does is to create a really long delay in page rendering.
If we tried 500k results, the paginator crashed on stack. Do you have a recursion there?
This needs to work in miliseconds, not delay page renders and not crash.

try this on any page and measure response time.
<Pagination
        page={1}
        pageSize={20}
        itemsPerPageText="Items per page:"
        pageSizes={[10, 20, 30, 40, 50]}
        onChange={(e) => {
          console.log('pagination changed');
        }}
        totalItems={123456}
      />

![image](https://user-images.githubusercontent.com/15310250/94154586-572b2080-fe7e-11ea-9b80-a41e9209fdd0.png)

**Comment by mattrosno** [comment]
Possible duplicates:

* https://github.com/carbon-design-system/carbon/issues/6836
* https://github.com/carbon-design-system/carbon/issues/5129
* https://github.com/carbon-design-system/carbon/issues/6146

Related:

* https://github.com/carbon-design-system/carbon/issues/4365

Possible workarounds:

* https://github.com/carbon-design-system/carbon/issues/6884
* https://github.com/carbon-design-system/carbon/issues/5546

**Comment by tw15egan** [comment]
Closing as duplicate
