### ISSUE TITLE
🎃  Hacktoberfest 2020 🎃

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#6913]
List of issues for Hacktoberfest 2020

![dancing](https://i.giphy.com/media/3oriNYMXEh2K5l4D9C/giphy.webp)

**Comment by andreancardona** [comment]
https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/reports/release?release=5f185c45ccda2753d030c742

**Comment by TheNoim** [comment]
You also need to add the topic "Hacktoberfest" to the repo. Otherwise, contributions are not counted.
