### ISSUE TITLE
Tabs component: need ability to scroll to the selected tab

### ISSUE THREAD

**Issue by gracelo** [carbon-design-system/carbon#6917]
When the Tabs component has a long list of tabs inside and the page is first rendered with a selected tab, the selected tab may not be shown.  The user has to press the < or > arrows to look for the selected tab.

I am using carbon-components 10.20.0 and carbon-components-react 7.20.0.

Example is like this:
When I load the page, it shows the list of tabs:
![image](https://user-images.githubusercontent.com/25369764/94300419-fad80780-ff36-11ea-9bad-96e176814ce2.png)

But have to scroll to see the selected tab:
![image](https://user-images.githubusercontent.com/25369764/94300473-117e5e80-ff37-11ea-9395-fca37f63d822.png)

I think it will cause usability issue from end users.

**Comment by tw15egan** [comment]
This seems like a sensible enhancement, what do you think @emyarod?

**Comment by emyarod** [comment]
yep, I was the one who asked them to report it here on GitHub for issue tracking!

**Comment by emyarod** [comment]
will await the outcome of https://github.com/carbon-design-system/carbon/pull/6974 before continuing with this issue
