### ISSUE TITLE
TableToolbarSearch is not sticked when using stickyHeader attribute of the table

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6929]
### Summary

TableToolbarSearch is not sticked when using stickyHeader attribute of the table

### Justification

when scrolling the search toolbar (I guess the whole TableToolbarContent too) disappears while working with stickyHeader mode.

### Desired UX and success metrics

The toolbar should be pined.

### Specific timeline issues / requests

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by vpicone** [comment]
This looks to be resolved, please open if that isn't the case. Please include screen shots or a replication for future issues.
