### ISSUE TITLE
PasswordInput: unintended misalignment of toggle button in FluidForm

### ISSUE THREAD

**Issue by josefaidt** [carbon-design-system/carbon#6934]
## [PasswordInput] unintended misalignment of toggle button in FluidForm

Hi all, I'm working on the Svelte implementation of FluidForm (ref [issue](https://github.com/IBM/carbon-components-svelte/issues/285)) and came across an unintended behavior of the toggle button's alignment.

## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

Input visibility toggle button is misaligned in an error state

**Default State**
![image](https://user-images.githubusercontent.com/5033303/94608463-0f800c80-0263-11eb-8bc3-d8b4b5f587f8.png)

**Invalid State with existing CSS**
![image](https://user-images.githubusercontent.com/5033303/94608555-29215400-0263-11eb-9447-06ea5ff571fd.png)

**Invalid State with removed CSS**
![image](https://user-images.githubusercontent.com/5033303/94609344-40ad0c80-0264-11eb-9ecf-9b535034fa97.png)

[SCSS line in question](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/form/_form.scss#L113). The `display: block` declaration is removing the `flex` property and therefore not aligning items to the center

> Is this issue related to a specific component?

`FluidForm` > `PasswordInput`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Button remained aligned center

> What browser are you working in?

Chrome Version 85.0.4183.121 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

v10.19

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

`carbon-components-svelte` and no pressing ship/release dates that I know of 🙂

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox

n/a

## Additional information

- WIP [FluidForm story](https://github.com/josefaidt/carbon-components-svelte/blob/285-textinput-add-fluid/src/FluidForm/FluidForm.Story.svelte)
- [PasswordInput button](https://github.com/josefaidt/carbon-components-svelte/blob/285-textinput-add-fluid/src/TextInput/PasswordInput.svelte#L173-L184)

**Comment by emyarod** [comment]
I'm not able to replicate this issue in the current component, can you provide more details or a reduced test case? https://carbon-components-react.netlify.app/?path=/story/textinput--toggle-password-visibility
