### ISSUE TITLE
Show selected items first in the multi-select dropdown list

### ISSUE THREAD

**Issue by CynZhang** [carbon-design-system/carbon#6953]
### Summary

We use the multi-select dropdown a lot in our application. The length of the list is not always predictable and can get long. 
We'd like the multi-select dropdown list to reorder the items and show the selected ones at the top. When the list gets long, it generally takes longer for the user to find specific item in case of making a correction. 

### Desired UX and success metrics

_Current component_
The tag shows there are 4 items selected. To find a specific item, the user may need to scroll to search for it. Although the component also supports filter, but it's difficult for user to have to recall complex name strings. 
![image](https://user-images.githubusercontent.com/46002772/94854427-ded2db00-03fa-11eb-860d-e7463fae8bb8.png)

_Proposal_
Always show the selected items at the top, so that deselection of any item becomes easier. 
The reordering should happen upon closing the menu, and the selected items appear at the top when the user opens the dropdown the next time. 
![image](https://user-images.githubusercontent.com/46002772/94854459-edb98d80-03fa-11eb-8221-fc0ed02b8132.png)

### Specific timeline issues / requests

It'd be ideal to have this improvement ready for our next release sometime at the end of this year.

**Comment by gjunming** [comment]
@CynZhang , I'd like your proposal，but I think this already been there.
https://react.carbondesignsystem.com/?path=/story/multiselect--default

![image](https://user-images.githubusercontent.com/45077/104156008-413c6e00-5423-11eb-8c97-b360baf278cf.png)

**Comment by tw15egan** [comment]
Like @gjunming pointed out, this is the default behavior. Closing as resolved. 

<img width="375" alt="Screen Shot 2021-01-20 at 12 33 56 PM" src="https://user-images.githubusercontent.com/11928039/105231443-c4dd1580-5b1b-11eb-90a6-ab6a13e452c4.png">
