### ISSUE TITLE
CONTRIBUTING.md is not corresponding to Husky's config

### ISSUE THREAD

**Issue by luizamendes** [carbon-design-system/carbon#6956]
## Detailed description 

As I was reading the guideline files to make my first contribution to Carbon, I noticed that in the [CONTRIBUTING.md](https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#commit-tip) file
the option `style` is listed as one of the options to `<type>` of the commit message. 

As the `style` type seemed the right choice for me, I tried to use it, but husky didn't let me. 
I noticed that on husky's configuration on [package.json](https://github.com/carbon-design-system/carbon/blob/master/package.json#L99), there is no `style` option. 

Husky has some options that CONTRIBUTING.md does not list and vice versa. 
I believe one of them should be updated, and I would like to do so, as my second attempt to contribute to carbon.

**Comment by tw15egan** [comment]
Whoops! Seems like we forgot it in the config file. Let's update that so that we can use the `style` commit message 🙂
