### ISSUE TITLE
[Tooltip] tooltips are misbehaving with some Chrome extension 

### ISSUE THREAD

**Issue by kentokage** [carbon-design-system/carbon#6958]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When there are multiple tooltip components, tapping on a tooltip while the other is open closes the other, but the one tapped opens and closes very quickly

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The first tooltip should close. The second tooltip should remain open.

> What browser are you working in?

Browser: [chrome, firefox, safari]

## Steps to reproduce the issue

Replicated with this sandbox
https://codesandbox.io/s/magical-fermat-nkowh?file=/index.js

1. Go to https://codesandbox.io/s/magical-fermat-nkowh?file=/index.js
2. Click on Tooltip label
3. Without closing the tooltip for Tooltip label, click on Tooltip label 2

## Additional information

![Oct-01-2020 16-19-49](https://user-images.githubusercontent.com/206663/94872626-f3ff3800-0401-11eb-9990-abae606092b6.gif)

**Comment by tw15egan** [comment]
I believe if you add an id to each, it should work properly, see https://codesandbox.io/s/great-firefly-q8rvw?file=/index.js

Since that isn't explicit, should we make the `id` prop a required one? cc @carbon-design-system/developers

**Comment by kentokage** [comment]
> I believe if you add an id to each, it should work properly, see https://codesandbox.io/s/great-firefly-q8rvw?file=/index.js
> 
> Since that isn't explicit, should we make the `id` prop a required one? cc @carbon-design-system/developers 

Yes this did it for me. Thanks! I agree that we should make "id" required. Can we repurpose this issue or create a new one?

**Comment by tw15egan** [comment]
@knyto2 updated the title to better address the root problem 👍

**Comment by emyarod** [comment]
we already have logic to autogenerate an id if a user does not provide one IIRC, so this may just be an issue with the component's existing logic (rather than making the `id` prop required)

**Comment by tw15egan** [comment]
@emyarod good point, changed it

**Comment by emyarod** [comment]
@knyto2 I'm actually not able to replicate the issue using your sandbox or our storybook and it seems like our autogenerated `id`s are working as expected. Can you provide more info about which browser you are using and maybe try testing without browser extensions to see if any of those are interfering with the component behavior?

**Comment by kentokage** [comment]
@emyarod that is strange, I'm using Chrome with extensions enabled and it is no longer reproducible. Can't explain it, but I'm going to close this since it's working for me. Thanks for the help!
