### ISSUE TITLE
Modal footer mis-aligns on large modals - IE

### ISSUE THREAD

**Issue by arunchris** [carbon-design-system/carbon#696]
When we have large content in the modal - like a large form, the modal content does not do overflow-y (IE only) and the footer goes out of the screen. Example below. 

[Codepen](https://codepen.io/arunchris/pen/zWXrZM)

**Comment by asudoh** [comment]
Hi @arunchris thank you for trying to report the issue! Seems that the codepen misses the polyfills for IE - Would you want to add polyfills listed in http://www.carbondesignsystem.com/getting-started/developers#polyfills-for-older-browsers into your codepen?

**Comment by arunchris** [comment]
Hi @asudoh - I haved added polyfill for the codepen.

**Comment by alisonjoseph** [comment]
Spent sometime looking in to this. Confirmed this is a bug. This has to do with a flexbox bug(s) in IE11 and overflow not rendering correctly. Strangely if you resize the browser the styles fix themselves. I haven't been able to find a workaround that fixes this.

Possible Workaround (not ideal)
- Hard code a height/max-height on to `.bx-modal-content` 

Possible fix
- Complelety refactor the modal styles to find a way to not use flexbox

**Comment by alisonjoseph** [comment]
Closing. duplicate #663
