### ISSUE TITLE
Re-enable All-Contributors to help recognize public maintainers of Carbon

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#6963]
Back in the day, we had the `all-contributors` [plugin](https://github.com/all-contributors/all-contributors) enabled that would populate our readme with a nice grid of our contributors and their contributions. 
> Link: https://www.npmjs.com/package/carbon-components#contributors

![Screen Shot 2020-10-02 at 10 31 58 AM](https://user-images.githubusercontent.com/11928039/94952237-82bf9380-049a-11eb-976d-2565b9b237b6.png)

Coupled with an effort to showcase individuals who help maintain Carbon on the main Carbon website, this could be used as the source of truth. I would imagine we would also enable this plugin on the `carbon-website` repo as well.

Plugin: https://github.com/all-contributors/all-contributors
Possible automation: https://allcontributors.org/docs/en/bot/overview

**Comment by NishithP2004** [comment]
Hi, I would like to work on this, could you please assign me to this issue?
