### ISSUE TITLE
File Uploader Component is removing both first and second file on adding second file in Internet Explorer

### ISSUE THREAD

**Issue by dishantsikka** [carbon-design-system/carbon#6967]
## What package(s) are you using?

- [x] `carbon-components-angular`

## Summary

I am trying to use File Uploader component in Angular. Requirement is to upload a Single File in Internet Explorer v10 or v11.
Adding a first file is working fine, but adding a second file is removing both first and second file.
Expectation is that on adding the second file, first file should be removed and second file should be added.
This is working as expected in Chrome, but is not working in Internet Explorer.

I am not sure if this is a problem or I am doing something wrong. that's why I have raised this as a question.

It would be great help, if someone please help with this issue.

## Relevant information

Steps :
User clicks on Add file. First file is uploaded successfully.
Now the user has changed his mind, and wants to add some other file.
If the User clicks on Add file again.
It removes the First file, which is fine, but it does not add second file.

In order to verify, that I am not doing something wrong, I have tried this with minimum properties of File Uploader component.
I am using below code:

<ibm-file-uploader
[multiple]=false>
</ibm-file-uploader>

**Comment by tw15egan** [comment]
Hey there @dishantsikka ! I would try creating an issue over at https://github.com/IBM/carbon-components-angular

**Comment by dishantsikka** [comment]
Thanks @tw15egan , please let me know, in case any information is needed.
For information, I am using Angular 9 and have tried it with Carbon v10.14.0 and v10.21.0

**Comment by tw15egan** [comment]
@dishantsikka I cannot transfer this issue over to that repo, so you will need to make an issue over at that link. This repo does not contain the angular components. Thanks!

**Comment by dishantsikka** [comment]
Thanks, I have created https://github.com/IBM/carbon-components-angular/issues/1562.
