### ISSUE TITLE
Add Button iconPosition prop

### ISSUE THREAD

**Issue by albertms10** [carbon-design-system/carbon#6970]
### Summary
Add an `iconPosition` prop to the Button component in order to position its icon to the left or to the right.

### Justification
Some icon buttons need to be positioned to the left of its label rather than on the other side, for context meaning purposes.

### Desired UX and success metrics

When the `iconPosition` is set to `'left'`, the button icon should be placed on the left of the label. The (current) default behaviour would be achieved by setting it to the `'right'`.

### "Must have" functionality
- [ ] Add `iconPosition` and change its styles accordingly (left/right margins)

### Specific timeline issues / requests

It is not related to any release.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by tw15egan** [comment]
I don't believe design allows for the icon to be placed on the left of the text.

https://www.carbondesignsystem.com/components/button/usage#buttons-with-icons

![Screen Shot 2020-10-06 at 10 23 00 AM](https://user-images.githubusercontent.com/11928039/95238129-eb21b400-07bd-11eb-9a54-41958259be9a.png)


cc @carbon-design-system/design is this guidance still correct?

**Comment by albertms10** [comment]
[_sic_]
cc @carbon-design-system/carbon is this guidance still correct?

**Comment by laurenmrice** [comment]
Yes, the icon should always remain to the right of the text in a button. This is the icon guidance that we follow from the IBM Design Language. This allows for better vertical text alignment on the page between elements.

**Comment by tw15egan** [comment]
Closing as resolved, thanks for chiming in @laurenmrice!
