### ISSUE TITLE
StructuredList with selection usage

### ISSUE THREAD

**Issue by maxjowett** [carbon-design-system/carbon#6983]
- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

It is unclear how to use the `StructuredList` component with selection enabled.

## Relevant information

The `onChange` prop for `StructuredListInput` looked promising but it doesn't seem to trigger any actions when clicking on the row/cell. Is there a simple example someone can point me towards?

**Comment by emyarod** [comment]
are you passing in a callback for `onChange` on `StructuredListInput`? 
for easier debugging, can you create a [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) that shows what you attempted?

**Comment by maxjowett** [comment]
@emyarod thanks for the response, check out [this sandox](https://codesandbox.io/s/gracious-pasteur-hxr1j?file=/src/index.js).

**Comment by emyarod** [comment]
@maxjowett I believe `StructuredListRow` needs the `label` prop

https://codesandbox.io/s/gracious-mclean-opjt7

**Comment by maxjowett** [comment]
Thank you, it might be worth including this in the doc/example [here](https://www.carbondesignsystem.com/components/structured-list/usage). As far as I can the `label` prop is not mentioned, making the selection not function at all.
