### ISSUE TITLE
[(ngModel)] not working in ibm-table-toolbar-search even though while inspect, ng-reflect-model="000UJB" has correct value

### ISSUE THREAD

**Issue by krishnashree-roy** [carbon-design-system/carbon#6985]
I need to display the previous searched value in the ibm-table-toolbar-search when I come back to the page. So I used below code. But it is not binding the value in ibm-table-toolbar-search where as the normal input field binding is working fine.
<ibm-table-toolbar-search  [skeleton]="skeleton" [placeholder]="placeholder" [tableSearch]="true"
    [(ngModel)]="searchedValue" ngDefaultControl name="searchVal"     (valueChange)="searchValueChange($event)" (clear)="clear()">
</ibm-table-toolbar-search>

[(ngModel)] not working in ibm-table-toolbar-search even though when I did inspect, ng-reflect-model="000UJB" has correct value as highlighted in the screenshot
![(ngModel)  issue in ibm-table-toolbar-search](https://user-images.githubusercontent.com/52851838/95292370-f7c20d00-088e-11eb-9068-cf6cef99dfb5.png)

**Comment by emyarod** [comment]
you may want to ask this over at the [carbon-components-angular](https://github.com/ibm/carbon-components-angular) repo instead!
