### ISSUE TITLE
Investigate adding copy functionality by default to CodeSnippet

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#6995]
Wondering if there is any downside to including something like [react copy to clipboard](https://www.npmjs.com/package/react-copy-to-clipboard) as a dependency so users do not have to add in their own copy functionality.

**Comment by guigueb** [comment]
There is also this react hook...
https://github.com/streamich/react-use/blob/master/docs/useCopyToClipboard.md

**Comment by guigueb** [comment]
This issue is a duplicate of https://github.com/carbon-design-system/carbon/issues/4448.

Please read the conditions I described in its comments about not overriding but to propagate the onClick.
