### ISSUE TITLE
In the case of a big horizontal scroll, there should be an option to fix the first column of the table.

### ISSUE THREAD

**Issue by amirkhan064** [carbon-design-system/carbon#6996]
In the case of a big horizontal scroll, there should be an option to fix the first column of the table.

### Summary

in the case of a big horizontal scroll, we can fix the first column and let scroll the rest of the table. So the user will always know which id's data he is viewing currently.

### Justification

we have a case where we have a big horizontal scroll and the user always has to scroll to the left to check which id's data he is viewing. So it will be good if we can "fix the first column" and let scroll the rest of the table. So the user will always know which id's data he is viewing currently.

### Specific timeline issues / requests

it'll be good if we can have this functionality in the next few weeks.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of the desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by LukaszGrela** [comment]
I would add that it should be possible (very useful) to mark any column as fixed.

**Comment by elycheea** [comment]
@sstrubberg This should be covered in Carbon for IBM Products frozen columns. Will post the link once the story is renamed. 🙌
