### ISSUE TITLE
Tag not setting the correct title attribute value

### ISSUE THREAD

**Issue by WilliamHolmes** [carbon-design-system/carbon#6998]
The `<Tag />` component doesn;'t see to honor the `title` prop. Instead it uses the child node (text).
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The child prop is being used for the title attribute instead of the title prop.

> Is this issue related to a specific component? `Tag`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in? 
All

> What version of the Carbon Design System are you using?

> What offering/product do you work on? 
IBM Cloud - Security & Compliance

> Please create a reduced test case in CodeSandbox

https://react.carbondesignsystem.com/?path=/story/tag--default

>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
I believe the title is only passed down when you use the filter variant, and it will show when you hover the close icon. 

The title for a normal tag will always just show the text, and I don’t think you would ever want to show different text, or is there a use-case I am overlooking here?
