### ISSUE TITLE
[Discussion] Add @carbon/test to the monorepo

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7]
This issue is to talk about any underlying testing mechanisms, techniques, tooling, etc that might need to be shared between core projects, in addition to consumers.

**Comment by asudoh** [comment]
Some candidates:

* https://github.com/carbon-design-system/carbon-components/tree/master/tests/utils
* Some portions of: https://github.com/carbon-design-system/carbon-components/blob/master/tests/karma.conf.js
* Some in: https://github.com/carbon-design-system/carbon-components-react/tree/master/config/jest
