### ISSUE TITLE
[button] add `xl` and `large` button size variant

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7003]
# Background

In the new creation flow pattern we need larger `80px` height [button](https://react.carbondesignsystem.com/?path=/story/button--default). I think we should also add the modal's `64px` buttons to the button component as well for consistency.

**Reasoning:** 
the smaller buttons at the bottom right of the page can easily get lost or overlooked. Having the option for a larger button can add weight and help with usability. It will also stay in proportion to how buttons are treated elsewhere (like modal). 

![image](https://user-images.githubusercontent.com/11670886/95513714-c75e9980-0988-11eb-8be7-fe0cdd39b882.png)

# Task

**Add new button size variants:**
- [x] `height: 80px / 10rem` =  `xl`
- [x] `height: 64px / 8rem` = `large`

# Spec
![image](https://user-images.githubusercontent.com/11670886/95515063-07bf1700-098b-11eb-97c1-3f9ab448fc18.png)

**Comment by Abdul-Sen** [comment]
Hi @aagonzales , As I understand the issue, you want a dev to impliment the `xl` varient to the current button based on the spec provided. If that is the task, then please assign me this issue as I would love to work on it.

**Comment by adhammo** [comment]
Hello,
I want to work in this issue. can you assign it to me?

What names would you want for those button variants? "primary-large", "primary-large"? and would you like them for each button type (secondary, danger, ...etc) ?

**Comment by Abdul-Sen** [comment]
Hi @aagonzales , I've taken some time to setup the project locally and familiarize myself with different parts of this monorepo. I noticed that the button is implimented as both an SCSS partial (under [carbon/packages/components/src/components/button/](https://github.com/carbon-design-system/carbon/tree/master/packages/components/src/components/button) ) and a react component under [carbon/packages/react/src/components/Button](https://github.com/carbon-design-system/carbon/tree/master/packages/react/src/components/Button). 

Does this issue encompass implementing this feature to both react button and vanilla JS button separately? Sorry if this is an ignorant question 😅

**Comment by aagonzales** [comment]
@Abdul-Sen Hello! Thanks for picking this up. We only require the React version to be built but the Vanilla JS would be extra credit. 

And yes adding the `xl` variant is the task. There is also a task of adding the `large` variant as well at 64px.

**Comment by dianasanborn** [comment]
Hey @aagonzales is this fixed button concept primarily for page wizard flows? Or does this apply to forms as well?
