### ISSUE TITLE
Define the "completion" metadata for components

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon#7008]
To some extent, a "definition of done". The intent here is to provide baseline consistency and quality measures - for our own components but also (and perhaps even more relevantly) community submitted components.

What does a "complete" component need to have;

- follow the component documentation template (@janchild)
- adhere to production guidelines (@jeanservaas)
- have an accessibility check
- have code
- etc...

This is not to say that a component can't be made available/visible *without* all this data, but that this data can provide clear guidance on completion/excellent, and can be used as a way to filter.

(we'll need to also do likewise for charts and for patterns in future)

**Comment by shinytoyrobots** [comment]
@jillianhowarth - is this something you might want to take a lead in drawing up?

**Comment by sstrubberg** [comment]
https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#type-enhancement-

🔥
