### ISSUE TITLE
datatable crashed when rows decrease

### ISSUE THREAD

**Issue by dxhdong** [carbon-design-system/carbon#7013]
currently if rows length in props decrease, this datatable will crash because rows in render function still use old data, it will change in componentdidupdate, but the rows in  render function should be changed before render.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/72720243/95701610-a0e87900-0c7c-11eb-8360-142df01e689c.png">

This is caused by getDerivedStateFromProps should be called in static getDerivedStateFromProps instead of componentdidupdate, if possible could you help to patch fix to some earlier version, currently we use version https://github.com/carbon-design-system/carbon/tree/v10.18.0/packages/react

**Comment by joshblack** [comment]
Hi there @dxhdong! 👋  Could you use a [Codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) to provide some steps to reproduce the issue? Thanks!
