### ISSUE TITLE
Pagnation size select and Page number select should not be enabled/disabled at the same time.

### ISSUE THREAD

**Issue by xiaolixu** [carbon-design-system/carbon#7014]
## What package(s) are you using?

- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

 Now Pagnation size select and Page number select are be enabled/disabled at the same time by variable pageInputDisabled and disabled.   However,  Page size select can be enabled and page number select should be disabled in the serverPagination  scenario.

> Is this issue related to a specific component?

Pagnation

> What version of the Carbon Design System are you using?

7.20.0

**Comment by joshblack** [comment]
Hi there @xiaolixu! 👋 Could you use a Codesandbox to provide some steps to reproduce the issue? Thanks!

**Comment by tw15egan** [comment]
@xiaolixu since we haven't heard back in some time, I'm going to close this out. Feel free to reopen if you are able to provide a Codesandbox illustrating your issue. Thanks!
