### ISSUE TITLE
[breadcrumb] needs to have an overflow option

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7019]
Breadcrumb needs to be able to have an overflow option.

Spec:
![Artboard Copy 2](https://user-images.githubusercontent.com/43969356/96639458-be0def00-12ef-11eb-96cb-175ea06aaf46.png)

**Comment by tw15egan** [comment]
I believe this is currently possible by just putting an `OverflowMenu` inside of a `BreadcrumbItem`

https://codesandbox.io/s/dazzling-germain-644hs?file=/src/index.js

@laurenmrice would we be able to do something as styling an overflow menu icon that is nested in a `BreadcrumbItem`?

https://codesandbox.io/s/sweet-leftpad-dcyr7?file=/src/styles.scss

**Comment by laurenmrice** [comment]
The second link you sent is more of what we would want (with the horizontal overflow menu icon). What we originally design is what looks like the overflow menu, but without the container attachment to the overflow icon. Instead it would have the same sharkfin that we have for tooltip. 

Like this:
![Artboard Copy 2](https://user-images.githubusercontent.com/43969356/96639526-cfef9200-12ef-11eb-916f-749b97255ec7.png)





I noticed this team on IOT has built it https://github.com/carbon-design-system/carbon-addons-iot-react/issues/719

**Comment by tw15egan** [comment]
Ah okay, gotcha! Shouldn't be too much extra work, I can work on this sometime this week. I know this has been asked about for a while
