### ISSUE TITLE
Move Aspect Ratio code from Grid to Layout

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7020]
Transfer Aspect Ratio code (variables, mixins) from the Grid package over to Layout

- Move Sass values over to Layout and make sure that they're still called in Grid
  - Add test to `packages/grid/__tests__/mixins-test.js` for `carbon--aspect-ratios` and `carbon--aspect-ratio` mixin to check for existence
  - Add `scss/_aspect-ratio.scss` file over to `@carbon/layout` and include [Variables](https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss#L239) and [Mixin](https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss#L261)
  - Remove these values from [grid mixin file](https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss)
  - Add import for aspect ratio to [grid mixin file](https://github.com/carbon-design-system/carbon/blob/master/packages/grid/scss/_mixins.scss)
- Update `layout/scss/layout.scss` to include aspect ratio file

Add JavaScript values for aspect ratios and use in Layout package

- Add the `aspectRatios` exports to `src/index.js`
-  Use the `aspectRatios` exports in `tasks/build.js` to generate a `generated/_aspect-ratio.scss` file
- Import the scale into `scss/_aspect-ratio.scss`

<details>
<summary>Original</summary>

```scss
$carbon--aspect-ratios: (
  (16, 9),
  (9, 16),
  (2, 1),
  (1, 2),
  (4, 3),
  (3, 4),
  (1, 1)
);
```
</details>

<details>
<summary>JavaScript</summary>

```js
const unstable_aspectRatios = [
  [16, 9],
  [9, 16],
  [2, 1],
  [1, 2],
  [4, 3],
  [3, 4],
  [1, 1],
];
```
</details>

**Comment by joshblack** [comment]
cc @photodow would be interested in tackling this 👀

**Comment by photodow** [comment]
@joshblack yeah, let me see what I can do.
