### ISSUE TITLE
BreadcrumbItem link hover behaviour inconsistent across browsers

### ISSUE THREAD

**Issue by daynss** [carbon-design-system/carbon#7023]
BreadcrumbItem link seems to have an inconsistent behaviour in different browsers. 
When we hover over the current breadcrumb item link in chrome, it changes color to blue.
When we hover over the current breadcrumb item link in firefox, it does not change color, which is expected behaviour according to the documentation.

## What package(s) are you using?

- [x] `carbon-components`  "10.10.3"
- [x] `carbon-components-react`  "7.10.3"

## Detailed description

> Describe in detail the issue you're having.
BreadcrumbItem link seems to have an inconsistent behaviour in different browsers. 
When we hover over the current breadcrumb item link in chrome, it changes color to blue.
When we hover over the current breadcrumb item link in firefox, it does not change color, which is expected behaviour according to the documentation. Strange is, that it is not happening in every case. We are able to reproduce it on just couple of screens. No use of custom styling, pure carbon.

> Is this issue related to a specific component?
 BreadcrumbItem

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I would like the BreadcrumbItem link to act consistently in all browsers

> What browser are you working in?
Chrome, Firefox, Safari, Edge

> What version of the Carbon Design System are you using?
 "carbon-components": "10.10.3",
 "carbon-components-react": "7.10.3",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Docs

> Please create a reduced test case in CodeSandbox
> - React:
https://codesandbox.io/s/awesome-joliot-9m00l?file=/src/index.js
- as mentioned above, this issue is not happening in every case. In this sandbox, for example, it works fine. But this is the same code we have in our project, and we do have the issue on couple of screens.

## Additional information
Please, check this website:
https://ibmdocs-dev.mybluemix.net/en/SSCSJL
1. open e.g. the page https://ibmdocs-dev.mybluemix.net/en/SSCSJL in FF
2. hover on the second breadcrumb IBM Cloud Pak for Applications
3. check the blue color of the text
4. open the same page in Chrome
5. hover the second breadcrumb

- Screenshots
<img width="295" alt="breadcrumb-link-code" src="https://user-images.githubusercontent.com/33804471/95772895-be8a0280-0cbd-11eb-9e0b-1adce667f09a.PNG">
<img width="230" alt="firefox - breadcrumb link not changing color on hover" src="https://user-images.githubusercontent.com/33804471/95772901-c2b62000-0cbd-11eb-9ec0-cac3d1c13a2c.PNG">
<img width="267" alt="chrome - breadcrumb link changing color on hover" src="https://user-images.githubusercontent.com/33804471/95772908-c649a700-0cbd-11eb-87c8-679aefc03901.PNG">

Thank you

**Comment by tw15egan** [comment]
I'm seeing the same colors in both browsers. Could you possibly have some extension enabled that may be conflicting with this? 

![Screen Shot 2020-10-12 at 11 08 09 AM](https://user-images.githubusercontent.com/11928039/95777547-413d9e00-0c7b-11eb-9866-cb60bf64f399.png)

![Screen Shot 2020-10-12 at 11 10 53 AM](https://user-images.githubusercontent.com/11928039/95777743-9da0bd80-0c7b-11eb-9e69-ca859ea6147a.png)

**Comment by daynss** [comment]
Hello, please check the exact url I sent in the bug report:  https://ibmdocs-dev.mybluemix.net/en/SSCSJL .  There, the current breadcrumb is IBM Cloud Pak for Applications ( not 4.3x ). Check it in chrome and ff, hover over it. in FF, it stays black, in Chrome, it changes color to blue. Thank you

**Comment by tw15egan** [comment]
I'm still unable to reproduce the issue, and I'm not seeing any issues in the storybook. I've verified the hover colors are the same, so closing this as not able to reproduce. 

![firefox](https://user-images.githubusercontent.com/11928039/96024481-a2df4300-0e08-11eb-96f1-bd5a487e0449.gif)
