### ISSUE TITLE
[OrderedList] - custom Carbon counter prevents native ol styles from starting in order, Firefox only

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#7027]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We are running into an issue in the Gatsby Theme (https://github.com/carbon-design-system/gatsby-theme-carbon/issues/949) where the ordered lists are starting at a random number in Firefox. 

A while back we had some issues with ol and realized that Carbon styles don't use the native `decimal` styles for ordered list, but rather have a `::before` element for the numbers/letters. 

<img width="309" alt="Screen Shot 2020-10-12 at 3 16 04 PM" src="https://user-images.githubusercontent.com/32556167/95786810-ecf7e580-0c9d-11eb-92d6-87898b628c89.png">
<img width="461" alt="Screen Shot 2020-10-12 at 3 16 13 PM" src="https://user-images.githubusercontent.com/32556167/95786813-ed907c00-0c9d-11eb-8a28-329ac3073413.png">

We needed to use the native styles for a specific feature (https://github.com/carbon-design-system/gatsby-theme-carbon/pull/893), and overrode the Carbon styles. Later, we realized there's still a custom style that is breaking lists on FF: `counter-reset: item`. We tried overriding the style (see screenshots below), but overriding doesn't work, rather removing the style completely does. 

We need an option to use native ordered list decimals (without the custom counter, and `::before` element). Currently, there is no workaround for this bc overriding the styles doesn't work.

> Is this issue related to a specific component?

Ordered list

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Be able to use native ordered list without pseudo elements and custom counters

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

latest

## Steps to reproduce the issue

1. Notice the ordered list starting at 7, this only happens on Firefox. It's coming from the style `counter-reset: item`
<img width="974" alt="Screen Shot 2020-10-12 at 3 00 37 PM" src="https://user-images.githubusercontent.com/32556167/95786386-0d737000-0c9d-11eb-99b9-69fa7dc58119.png">

2. Trying to override the style doesn't do anything
<img width="988" alt="Screen Shot 2020-10-12 at 3 01 17 PM" src="https://user-images.githubusercontent.com/32556167/95786399-119f8d80-0c9d-11eb-9700-ddbb551613df.png">
<img width="982" alt="Screen Shot 2020-10-12 at 3 01 39 PM" src="https://user-images.githubusercontent.com/32556167/95786400-119f8d80-0c9d-11eb-9b4a-08d4a769a63d.png">

3. The only way for it to work correctly is if the style is removed completely from the carbon stylesheet
<img width="978" alt="Screen Shot 2020-10-12 at 3 00 54 PM" src="https://user-images.githubusercontent.com/32556167/95786397-119f8d80-0c9d-11eb-9f57-0615ecc917ff.png">

**Comment by tw15egan** [comment]
This goes hand in hand with this issue: https://github.com/carbon-design-system/carbon/issues/5487

The reason we aren't using them is that design specified that the numbered list should be right-aligned. The default ordered list is left-aligned.

**Comment by reiv** [comment]
According to [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1545746#c5) on Bugzilla, specifying

`counter-reset: item;`

by itself is wrong because it overrides the browser stylesheet without resetting the implicit [`list-item` counter](https://drafts.csswg.org/css-lists-3/#list-item-counter) too (the one incremented by `<li>`). To reset both counters, the syntax would be

`counter-reset: list-item item`

Not sure why Firefox is the only browser affected, but apparently it's following the spec so the current behavior is "correct".
