### ISSUE TITLE
Increase side navigation levels from 1 to 2

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#7028]
### Summary
The Left nav as-is is not two levels. It’s one level, where some of the items can be hidden under a collapsing label.

### Justification

Two Level navigation requires the ability to select a parent, with a result of that selection in the view. 
![image](https://user-images.githubusercontent.com/35537391/95788469-998b9480-0ca9-11eb-8a78-76b6cf0af959.png)

Otherwise you get states like this:
![image](https://user-images.githubusercontent.com/35537391/95770668-c333c400-0c87-11eb-9a38-92ca81661b3e.png)

Where user has clicked on "Contributing", but selection remains on "Tabs"

Additionally there have been requests for 3rd level navigation in the left nav; the bulk of these requests are speaking to the lack of a true second-level navigation in the left nav, rather than a need for a third.

### Desired UX and success metrics

Left nav has 1st order nodes, and children of those nodes. all first order nodes are selectable and drive a view, whether they have children or not.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by joshblack** [comment]
Hey @chrisconnors-ibm! :wave: We were taking a look at this during proposal grooming and I wanted to leave a couple notes/questions from that session.

The primary question is if this is for the website specifically or a general enhancement for the left nav?

On the implementation side, we wanted to leave a note that this would require us to split out the button into two pieces: one part for the link and one for the expansion.

**Comment by chrisconnors-ibm** [comment]
Hi @joshblack, a general enhancement for everybody that carbon design system would hopefully take advantage of, but those are separate questions/efforts.

**Comment by vpicone** [comment]
This is something that we've put in a lot of time exploring in the Gatsby theme, but we've yet to find a tertiary navigation solution that is both accessible and doesn't encourages a clear, flat information architecture. We would need a proposal with more information and research leading to a sufficient spec.
