### ISSUE TITLE
[Cloud Pak for Data System] Visualization navigation

### ISSUE THREAD

**Issue by Grace-Harkin1** [carbon-design-system/carbon#7030]
### Summary

Cloud Pak for Data System has recently implemented an interactive server rack visualization into our console. In this view, the user can zoom and pan within the canvas either by using the toolbar and/or clicking and dragging to pan. Most screen sizes accommodate for viewing up to 4 racks at once at the default zoom level. 

CPDS is anticipating having to support systems of up to 20 racks in the near future. In order to accommodate for this, we explored having a way to navigate the racks. Our exploration is similar to a carousel and also similar to a map. The gray rectangles represent the racks in the user's system. The user can click-and-drag on the blue rectangle to change which racks are surfaced in the canvas. The right and left arrows in the canvas shift the view over by one rack in whichever direction you choose.

### Justification

CPDS will be supporting systems of 20 racks, and therefore the racks must be visualized. The pagination options that Carbon currently provides do not indicate strongly enough the system size. It's important that the user clearly sees how many racks there are total so that they can check the health of all of their components. 

### Desired UX and success metrics

**Default**
![5 0_Hardware overview_graphical_default](https://user-images.githubusercontent.com/64492316/95806444-87ffb800-0cbc-11eb-9ebd-f9df624d0acb.png)

**After clicking the right canvas arrow**
![5 0 1_Hardware overview_graphical_navigation_arrow](https://user-images.githubusercontent.com/64492316/95806462-92ba4d00-0cbc-11eb-80d6-e85c8a84f99d.png)

**Clicking and dragging on the map**
![5 1 0_Hardware overview_graphical_navigation_hover](https://user-images.githubusercontent.com/64492316/95806477-9a79f180-0cbc-11eb-80da-7a248dfc3686.png)

![5 1 1_Hardware overview_graphical_navigation_drag](https://user-images.githubusercontent.com/64492316/95806486-9d74e200-0cbc-11eb-91c1-8d95cebd3633.png)

**Panning by clicking on the toolbar arrows**
![5 2 4_Hardware overview_graphical_panning_hover](https://user-images.githubusercontent.com/64492316/95806513-b2ea0c00-0cbc-11eb-9809-0e31dc431174.png)
![5 2 5_Hardware overview_graphical_panning_hover](https://user-images.githubusercontent.com/64492316/95806535-c006fb00-0cbc-11eb-90ae-e80722b41961.png)

**Filtering**
The map view filters so that it always matches what is being shown in the canvas.
![5 4 2_Hardware overview_graphical_filter_selected](https://user-images.githubusercontent.com/64492316/95806543-c6957280-0cbc-11eb-9994-9ed6872f2e12.png)

### "Must have" functionality

The user must be able to navigate to all 20 racks. The user must be able to view and select components within the rack at any view. The user must know how many racks are within their system.

### Available extra resources

Our development team is currently building this for our February release.

**Comment by aagonzales** [comment]
Hey @Grace-Harkin1! Thanks for submitting. However, this feature is too unique for the Carbon common team to build. Your team is welcomed to build and publish it at your PAL level. We are closing the issue but we'd be willing to advise on design if needed. Let us know if you have any questions or would like to schedule a design review. Thanks!
