### ISSUE TITLE
Issue: Filterable Multiselect inline property not displaying correctly

### ISSUE THREAD

**Issue by ttan-ibm** [carbon-design-system/carbon#7041]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The filterable Multiselect component does not look "inline" when you apply the inline property to it.

<img width="710" alt="Screen Shot 2020-10-13 at 4 03 11 PM" src="https://user-images.githubusercontent.com/52932479/95925166-f6508300-0d6d-11eb-8901-67dcbd95890f.png">

> What did you expect to happen? What happened instead? What would you like to
> see changed?

It should look like an inline multiselect like:
![image](https://user-images.githubusercontent.com/52932479/95925224-1c762300-0d6e-11eb-9b73-5b5f806bc9c2.png)

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v7.20.0 - https://react.carbondesignsystem.com/?path=/story/multiselect--filterable

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Cloud Pak for Data

> Please create a reduced test case in CodeSandbox
> Go to https://react.carbondesignsystem.com/?path=/story/multiselect--filterable and select Inline knob

**Comment by emyarod** [comment]
it looks like you are expecting the inline filterable light multiselect styling

![image](https://user-images.githubusercontent.com/8265238/96014476-0c148580-0e0c-11eb-8d1a-2676c9677de7.png)

**Comment by ttan-ibm** [comment]
@emyarod

> it looks like you are expecting the inline filterable light multiselect styling

Lauren (@laurenmrice) mentioned in the carbon design slack channel that there shouldn't be a background box. I would expect it to not have the bottom-border either but I'll let her confirm.

https://ibm-analytics.slack.com/archives/C0M053VPT/p1602260600298500

**Comment by laurenmrice** [comment]
The filterable multiselect inline variant should not get a field background color for the default state or light prop.

Spec:

![multiselect- filterable (inline)](https://user-images.githubusercontent.com/43969356/96457091-5b342f00-11ed-11eb-8838-ba5be0a0830f.png)
