### ISSUE TITLE
DataTable[Search Bar] add prop to prefil search query in search bar

### ISSUE THREAD

**Issue by SoSubtle** [carbon-design-system/carbon#7044]
## Feature Request Summary

Please include a brief summary of what you would like to see changed here. 
Hello. Would it be possible to have a prop to fill the search bar on the datatable. For example if a user searched for a term 'test' then without clearing the search bar left the page and returned it would be nice to have the search query still in place as the user did not delete it. 

## Justification
This is needed to improve the UX of the IAM-UI Users datatable.

## Desired UX and success metrics
- user searches for 'tester' in search bar of users datatable
- user leaves the page ( perhaps clicked a button located in one of the rows of the returned users)
- user comes back to the page
- search bar should contain prefilled user query

## Additional context
We have our own state management store, we just need a prop available to pass in the prefilled query to the search bar.

**Comment by emyarod** [comment]
are you looking for something other than the `defaultValue` prop?

**Comment by SoSubtle** [comment]
> defaultValue

Hello. Is the defaultValue prop part of the TableToolbarSearch component ? I cant find it. Thanks.

**Comment by emyarod** [comment]
it's a React attribute, this may be helpful to look through https://reactjs.org/docs/uncontrolled-components.html#default-values
