### ISSUE TITLE
Multiselect.Filterable not showing initiallySelectedItems

### ISSUE THREAD

**Issue by brittanykvanvig** [carbon-design-system/carbon#7047]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We are passing in initialSelectedItems to the component, and it doesn't always select the items correctly. The first time passing values works. The second time nothing is preselected (screenshots below). The third time, occasionally will show the 2nd option preselected, other times nothing is preselected like the second time.

> Is this issue related to a specific component?

Yes - MultiSelect.Filterable

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected when passing initialSelectedItems, those items are selected in the component.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

7.16.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IAM UI - no pressing dates.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
<img width="1434" alt="Screen Shot 2020-10-14 at 11 11 48 AM" src="https://user-images.githubusercontent.com/3605386/96020073-1d14c500-0e13-11eb-93e2-f878dfad7900.png">
<img width="378" alt="Screen Shot 2020-10-14 at 11 10 34 AM" src="https://user-images.githubusercontent.com/3605386/96020083-21d97900-0e13-11eb-8886-4978022fd3cd.png">
<img width="1457" alt="Screen Shot 2020-10-14 at 11 10 24 AM" src="https://user-images.githubusercontent.com/3605386/96020106-2aca4a80-0e13-11eb-8377-35c14741da8a.png">

- Notes

**Comment by brittanykvanvig** [comment]
please let me know if you need any more details or the codebox case and I can try to provide those.

**Comment by TannerS** [comment]
I am having same issue

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by emyarod** [comment]
in the meantime I believe rendering the component with a `key` each time should resolve this issue

**Comment by motherchucker** [comment]
The issue is still present
