### ISSUE TITLE
The contrast ratio on links when being hovered

### ISSUE THREAD

**Issue by Lucinda94** [carbon-design-system/carbon#7051]
The contrast ratio on links when being hovered
---
The contrast ratio on links when being hovered are 3.98 when it needs to be over 4.5 to align with WCAG standards for accessible text.

Visuals
---
![image](https://user-images.githubusercontent.com/49566004/96106095-b22ac300-0ed2-11eb-98e6-af5a32dbead6.png)

**Comment by tw15egan** [comment]
@Lucinda94 do you have an example we could take a look at? Seems like it is occurring on a DataTable with the white theme enabled?

**Comment by Lucinda94** [comment]
Hi we are using the G10 theme, I can email you the URL and credentials to see the example

**Comment by dakahn** [comment]
Tested with our Link element using Colour Contast Analyser 
![image](https://user-images.githubusercontent.com/40970507/97235726-7f75aa00-17b1-11eb-84e9-811035c4ccd6.png)

Seems like on hover our links don't meet contrast spec. This could be potentially a problem for that whole theme.
