### ISSUE TITLE
When expand the top level accordion the nested accordion chevrons also point upwards

### ISSUE THREAD

**Issue by hongcbjch** [carbon-design-system/carbon#7052]
I am using a nested accordion, when I expand the top level accordion, the nested accordion chevrons also point upwards.

Expected result:
when I expand the top level accordion, the nested accordion chevrons point downwards. when I expand the nested accordion, the chevrons point upwards.

Screenshots:
![image](https://user-images.githubusercontent.com/42921827/96109065-defdcb00-0f10-11eb-8124-65503e2168db.png)

**Comment by tw15egan** [comment]
Nested accordions are not a supported pattern, so you'll need to make the CSS overrides on your end. Hope that helps!

**Comment by hongcbjch** [comment]
@tw15egan can you please provide more information on CSS overrides? It seems the it is controlled by internal state.

```
 const classNames = classnames(
      {
        [`${prefix}--accordion__item--active`]: this.state.open,
      },
      `${prefix}--accordion__item`,
      className
    );
```

**Comment by hongcbjch** [comment]
Can somebody help on this? Thanks so much.

**Comment by hongcbjch** [comment]
@joshblack Hi Josh, thanks for help reopening this defect.

**Comment by tw15egan** [comment]
You can target the nested svg icon with a selector like 

```css
.bx--accordion__item--active > .bx--accordion__item .bx--accordion__arrow { 
    transform: rotate(0); 
}
```

but since this is not a supported pattern your mileage may vary. If possible, I would look into using a different pattern to display this information, as nested accordions are not a valid pattern, and thus, not supported.

**Comment by jiahouping** [comment]
I also meet this issue in our project. And I've tried 

> .bx--accordion__item--active > .bx--accordion__item .bx--accordion__arrow { 
>     transform: rotate(0); 
> }
But it seems not work.

**Comment by hongcbjch** [comment]
@tw15egan Can you please help on this issue? The workaround doesn't work. I know it is not supported for now, but nested accordions is a required usage in our project . Thank you!
