### ISSUE TITLE
Is there any list of which components support renderIcon?

### ISSUE THREAD

**Issue by arloduff** [carbon-design-system/carbon#7057]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

Hi, I've noticed that some of the components allow specifying which icon to render, such as https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L28

However, it seems not all components support this. For example, https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/TextArea/TextArea.js#L100 uses the WarningFilled component, which hard codes its own SVG data.

My question is, is there any place which documents which components support the `renderIcon` prop so this can be easily referenced?

**Comment by joshblack** [comment]
Hey there, @arloduff! I don't believe there is an official list for the `renderIcon` prop, a quick scan of the codebase seems like the following support it:

- OverflowMenu
- TableToolbarMenu
- TableBatchAction
- SideNavMenu
- Tooltip
- SideNavHeader
- Button
- NotificationButton
- SideNavLink
- ModalWrapper
- Pagination

Hope this helps!

**Comment by arloduff** [comment]
Thanks! That does help!

I would suggest that maintaining consistency around all components being able to accept this property would be helpful, and if not, then maintaining a list of which components support it. But this is good for now. Thanks for finding it!
