### ISSUE TITLE
Carbon Component Razor Library? 

### ISSUE THREAD

**Issue by mouadcherkaoui** [carbon-design-system/carbon#7069]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

launching new repository for carbon design component using blazor

### Justification

I was working on porting carbon components as microsoft razor library to be used in blazor webassembly projects, I just started with the DataGrid the Shell Accrodion etc ... , I hope that there is a possibility to contribute to the project by working on these components in a way that respect contribution guidelines and being a part of the carbon design ecosystem: 

https://github.com/mouadcherkaoui/bxblazor
https://bxblazor.z22.web.core.windows.net/components/bx-datatable
https://www.nuget.org/packages/BxBlazor/

### Available extra resources

What resources do you have to assist this effort?

maybe I need more documentation on the team members developed their compoenent using the HBS templates and how the VanillaJS version works, though I'll be able to completly replace javascript codebehind by c# one.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by dakahn** [comment]
Hello! A community contributed Razor implementation would be awesome and any work you can throw in is greatly appreciated. Our HBS/Vanilla version is a community project itself (though it started as internal IBM maintained). Feel free to use our question template to ask any questions you may have. There are plenty of HBS template maintainers still hanging around. 👍

**Comment by mouadcherkaoui** [comment]
Great,

I was working on porting carbon components as microsoft razor library to be used in blazor webassembly projects, I just started with the DataGrid the Shell Accrodion etc ... , I hope that there is a possibility to contribute to the project by working on these components in a way that respect contribution guidelines and being a part of the carbon design ecosystem:

https://github.com/mouadcherkaoui/bxblazor
https://bxblazor.z22.web.core.windows.net/components/bx-datatable
https://www.nuget.org/packages/BxBlazor/

all I need, is an official repo and some documentation based on which I'll do a plan and continue working respecting IBMs experts recommendations and best practices, and maybe trying to find some enthusiast around there to work on and join the community!

thanks in advance!

**Comment by sstrubberg** [comment]
@mouadcherkaoui If this is still something you're interested in. Hit me up!
