### ISSUE TITLE
Missing outbound link icon

### ISSUE THREAD

**Issue by weeblr** [carbon-design-system/carbon#7071]
### Summary

I can't seem to find the outbound link/ external link icon in the Carbon icon set. Strangely, that icon is present in multiple places on https://www.carbondesignsystem.com/. 
For instance the Github menu item at the end of the left sidebar menu has that outbound link SVG icon.

Did I miss it?

### Justification

Many sites, including https://www.carbondesignsystem.com/, want to stress out the fact a link is outbound/opens in a new tab using this icon.

**Comment by tw15egan** [comment]
I believe you're looking for the "launch" icon

![Screen Shot 2020-10-19 at 12 08 11 PM](https://user-images.githubusercontent.com/11928039/96500502-d7d20800-1203-11eb-955d-3017c7570693.png)

Looks like it will match with these terms:

![Screen Shot 2020-10-19 at 12 09 52 PM](https://user-images.githubusercontent.com/11928039/96500621-04861f80-1204-11eb-9a4f-23a4fd943312.png)

I'll update this list to include `link` `external` and `outbound`. Would you recommend any other additions to help discoverability of this icon?

**Comment by weeblr** [comment]
Hi @tw15egan 

Thanks for pointing this out. I'd say external link is the primary usage of the icon indeed so those 3 keywords will help discovery.

Thanks for adding them.
