### ISSUE TITLE
ComboBox in expand/open mode is fully displayed

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#7074]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

I'm trying to use Combox and right after that I have a SplitPane, the problem is when opening the combo... the list of items shrunken!
![image](https://user-images.githubusercontent.com/26740851/96436036-85e2af80-120e-11eb-93eb-9918c38ae554.png)

Tried to fix it by css `bx--list-box__menu` but didn't manage.

If I use other dropdown (like Symantic for example) the list is opened as expected over the SplitPane.

## Relevant information
Sandbox:
https://codesandbox.io/s/lucid-https-65srb?file=/src/App.js

**Note**: when I enable the import of carbon-react Combobox the sandbox is corrupted with error:
Maximum call stack size exceeded !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by tw15egan** [comment]
@zbeedatm what do you mean "shrunken"? Can you show a video of the issue if you are having trouble with CodeSandbox?

**Comment by zbeedatm** [comment]
Sent to you.

**Comment by zbeedatm** [comment]
I had to set the container div as fixed and the one contains the combo as relative to make it work.
