### ISSUE TITLE
Can't select Date when opening picker results in scroll bar

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#7075]
I was able to reproduce this using the Carbon Story book  https://react.carbondesignsystem.com/?path=/story/datepicker--single

1.  Click the button to open the canvas in new tab
![image](https://user-images.githubusercontent.com/30597411/96450003-a6e1db00-11e3-11eb-9851-91fb5e33b97a.png)

2.  Decrease the size of the window so the calendar appears fully but such that the calendar popup doesn't have room to open.
![image](https://user-images.githubusercontent.com/30597411/96450151-d264c580-11e3-11eb-8013-bcddccd0b469.png)

3.  Click on the calendar image so the calendar popup opens.  This causes a scrollbar to appear.
![image](https://user-images.githubusercontent.com/30597411/96450266-f88a6580-11e3-11eb-982d-ec1ec9f42536.png)

4.  Dates at the end of the month are not visible, so use the scroll bar to to try to scroll the date into view.

Every time you go to the scrollbar, the popup loses focus and closes.  You can't select dates that are scrolled out of view.

Workaround:  Use the scroll wheel on the mouse, which does not cause focus to be lost.  However, I don't think all of our users are aware of the scroll wheel.

**Comment by gptt916** [comment]
This seems like a problem with flatpickr right? Looking at the source carbon isn't handling blur or component state for open/close
