### ISSUE TITLE
Tabs does not respond to container resizing

### ISSUE THREAD

**Issue by starpit** [carbon-design-system/carbon#7083]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If Tabs is placed in a container that supports resizing (e.g. a container with a `resize: both` css rule), the `Tabs` component does not respond to container resizing. Looking at the source, I see that it only responds to window-level resizing.

The fix would be to use a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver), and attach it to the Tabs ref, e.g. via

```typescript
const observer = new ResizeObserver(entries => {
   doResize(entries[0].contentRect.width, entries[0].contentRect.height)
})
observer.observe(theTabsDom)
```

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

```jsx
<div style={{resize: 'both', overflow: 'auto'}}>
  <Tabs>...</Tabs>
</div>
```

> What browser are you working in?

Electron 7, Firefox, Chrome, ...

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Kui

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

i'd love to create a sandbox, but your template seems to be broken.

## Additional information

- Screenshots or code
- Notes

**Comment by starpit** [comment]
https://codesandbox.io/s/quirky-resonance-4j78i

**Comment by emyarod** [comment]
thanks for the example. we won't be able to use ResizeObserver until we drop IE support and I'm not sure if we would want to polyfill it. There may be an existing solution by watching the `resize` event but I don't know if that's supported in React

**Comment by starpit** [comment]
I guess my suggestion would be that, by supporting all-but-IE, the IE support remains as it is today. I.e. we won't be degrading the IE experience, by fixing the bugs everywhere else.

**Comment by emyarod** [comment]
yeah I can see that, may look into this further after some of the currently open Tabs issues have been resolved

**Comment by sstrubberg** [comment]
We've done a lot work to Tabs with v11. Let me know if this is still an issue and we can re-open.
