### ISSUE TITLE
Switching Tabs still causes vertical scrolling.

### ISSUE THREAD

**Issue by starpit** [carbon-design-system/carbon#7084]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Switching tabs can still (even with the fix for 7.22 https://github.com/carbon-design-system/carbon/pull/6974) cause vertical scrolling. See my comments here on the original issue for more detail and gif examples:

https://github.com/carbon-design-system/carbon/issues/6973#issuecomment-710725056
https://github.com/carbon-design-system/carbon/issues/6973#issuecomment-710726143

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Switching Tabs should never cause vertical scrolling.

> What browser are you working in?

Any

> What version of the Carbon Design System are you using?

7.22

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Kui

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by starpit** [comment]
i'd love to help there, but i get only 

> InternalError too much recursion

from your sandboxes.

**Comment by emyarod** [comment]
it looks like this is a current issue in Code Sandbox. we'll have to wait for them to resolve it https://github.com/codesandbox/codesandbox-client/issues/5022

**Comment by emyarod** [comment]
as an alternative you could also try recreating the issue in [jsfiddle](https://jsfiddle.net/) or [codepen](https://codepen.io/)

**Comment by starpit** [comment]
https://codesandbox.io/s/quirky-resonance-4j78i

**Comment by starpit** [comment]
@emyarod Here is a sandbox that demonstrates the vertical scrolling bug. https://codesandbox.io/s/nifty-water-3i8br

**Comment by emyarod** [comment]
thanks for the example, I believe this will be resolved in #7111
