### ISSUE TITLE
Component to support phone number with country code search ability

### ISSUE THREAD

**Issue by sanjitbauli** [carbon-design-system/carbon#7089]
### Summary

A component to search and select one value from a list and show label from the list.
It may involve design and development.

### Justification

basically, i am looking for a component where a user can find the phone number country code by searching with the country name.

Proposed design:
<img width="420" alt="Screenshot 2020-10-20 at 11 31 55 AM" src="https://user-images.githubusercontent.com/272230/96548173-fe0eab00-12ca-11eb-839f-3e8b59a0097a.png">

<img width="461" alt="Screenshot 2020-10-20 at 11 32 06 AM" src="https://user-images.githubusercontent.com/272230/96548367-5c3b8e00-12cb-11eb-9f59-9d8bae57e069.png">

<img width="426" alt="Screenshot 2020-10-20 at 11 32 27 AM" src="https://user-images.githubusercontent.com/272230/96548376-62ca0580-12cb-11eb-922f-a0a1fd5b5e70.png">

**Comment by vpicone** [comment]
As a component library, we can't really own that country code data. This can be accomplished by pairing a dropdown of your supported country codes along with a standard TextInput

**Comment by aagonzales** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon/issues/3948
