### ISSUE TITLE
Data Table: Allow alternative locations for expand chevron button

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#7098]
### Summary

At the moment, the expand chevron button in Data Table rows is always positioned at the left edge of the row. This request is to provide an option to have the expand chevron button available on the right edge of the row.

### Justification

1. There are times when the expansion of a data table row is not a primary action, and therefore could do with less prominence than when provided on the leading edge.
1. In Right-to-Left languages, the leading edge would in fact be on the right. This would then allow better internationalisation.
1. From a visual consistency of actions, allowing the option to have the expansion button be on the same side of the table as the toolbar buttons (which are already right-aligned) would allow for easy eye-tracking and a potentially better user experience.

### Desired UX and success metrics

Rather than always presenting the expand chevron button on the left, allow it to be presented on the right end of a data table row.

### "Must have" functionality

Allow the developer to specify the location of the expand chevron buttons for a data table. A default option of left-hand side can be used to provide backwards compatibility with existing implementations and designs.

### Specific timeline issues / requests

No specific timeline requested.

### Available extra resources

Limited at this time.

### Screenshots

Current implementation as of v10.22.0 (taken from Storybook):

<img width="1157" alt="Screenshot 2020-10-21 at 08 20 38" src="https://user-images.githubusercontent.com/14542757/96686435-71212b80-1376-11eb-89dd-2c5502867602.png">

**Comment by emyarod** [comment]
cc @carbon-design-system/design regarding positioning the table row expansion button on the right as an option

**Comment by aledavila** [comment]
Hi thanks for submitting this. Would you mind giving us an example of how it would be used in context please.
