### ISSUE TITLE
Migration from bluemix-components to carbon is not easy

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#71]
I tried to move from bluemix to carbon components. 
It does not fair well

1. in ver 6:<body class="bx--global-light-ui" ---> bx--body
2. ver 6: app.sccs would import many things (at least in the app i got from atlas), and now 
@import '../../../node_modules/carbon-components/scss/globals/scss/styles';
It is important to document how to use the code, and how to migrate to it

3. There needs to be a central file, which takes an item from ver6, like button and shows it in ver 7.
because ver6 used <a> and now you use button and different names for styles.

There needs to be one html file which shows differences examples

I will update with more scenarios as I do more work.

**Comment by hellobrian** [comment]
Hey @alon24, thanks for posting this issue. You raised some great points and we merged a couple of PRs based on your feedback. 

As for migration guides, we provide a [migrate-to-7.x.md](https://github.com/carbon-design-system/carbon-components/blob/master/src/components/button/migrate-to-7.x.md) in every src/components subfolder. 

We can definitely do more iterations on these in the future to make it less painful to upgrade to future major releases.

For the most part, every component comes with modified HTML, SCSS and sometimes JS.
As a baseline for migrating over, some of the baseline steps for upgrading are:
- Copy and paste the new HTML
- Import the new SCSS file for that component
- Import the new JS for that component (use new JS from these built folders: `es`, `umd` or `scripts`)
