### ISSUE TITLE
ComposedModal does not remove preventCloseOnClickOutside property from div

### ISSUE THREAD

**Issue by renagerie** [carbon-design-system/carbon#7100]
[Title]: The recently added `preventCloseOnClickOutside` property is not properly handled in ComposedModal. Compare with Modal for proper handling. This results in a browser warning about the property not being recognized for a div.

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Simple use case. Using the ComposedModal component with the preventCloseOnClickOutside property results in a warning in the browser console. Note that there appears to be no behavioral defect; the property does function correctly.

**Comment by emyarod** [comment]
I'm not sure if `preventCloseOnClickOutside` will remain since the use case can be handled in `onRequestClose` already, but you should be able to properly implement the behavior in `onRequestClose` instead

**Comment by renagerie** [comment]
`preventCloseOnClickOutside` was added as a convenience after discussion despite `onRequestClose` allowing the behavior. It works correctly in `Modal` and the same behavior should be ported to `ComposedModal`. It seems strange to remove it after having just added it.

**Comment by emyarod** [comment]
yep, what I meant was while the issue exists with the newly added prop (and discussions on the future of the modal props aside), you should be able use `onRequestClose` in the meantime to avoid running into the issue

**Comment by renagerie** [comment]
Indeed. In fact, I was looking to remove our existing `onRequestClose` wrapper since it would no longer be needed thanks to this property. However, that results in console errors for `ComposedModal`, so I will hold off on that change awaiting a fix for this issue.

**Comment by renagerie** [comment]
Thanks!
