### ISSUE TITLE
Tabs: content of nested tabs appears on the side instead of below the tab

### ISSUE THREAD

**Issue by Antonio-Maranhao** [carbon-design-system/carbon#7102]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When using nested `<Tabs>`, the contents of an inner tab shows up on the right side instead of below the tab.

> Is this issue related to a specific component?

Tabs / Tab

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Tab content is displayed below the tab. It used to work before so my guess is it's related to the recent changes to use 'scrollable tabs'.

> What browser are you working in?

Chrome 86.0.4240.75

> What version of the Carbon Design System are you using?

carbon-components-react 7.22

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Cloudant. You can see how we use nested tabs at https://cloud.ibm.com/catalog/services/cloudant

## Steps to reproduce the issue

See sandbox code below

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/loving-fermi-rr3i6?file=/src/index.js

## Additional information

Screenshot from sample code above where you can see the content of the inner tab shows up on the right side instead of below the tab.
![image](https://user-images.githubusercontent.com/30349380/96732093-f8c26680-1385-11eb-80ef-ae84a6c80ba6.png)

**Comment by emyarod** [comment]
I don't know if nested tabs is a supported use case, but the workaround for this would be adding `flex-direction: column` to your inner tabs component

**Comment by Antonio-Maranhao** [comment]
@emyarod Thanks for the workaround. 

I'd say that's an essential requirement for a component like Tabs which is one of the building blocks for more complex layouts.

**Comment by emyarod** [comment]
I believe this is resolved by https://github.com/carbon-design-system/carbon/pull/7109

**Comment by Antonio-Maranhao** [comment]
Confirmed on Sandbox that the bug is fixed on `carbon-components-react@7.23.0`. Thanks for the fix @emyarod 
Closing.
