### ISSUE TITLE
Allow the end user to move/reposition modal dialogs

### ISSUE THREAD

**Issue by tom-poulin** [carbon-design-system/carbon#7112]
### Summary

When you open a [modal dialog](https://www.carbondesignsystem.com/components/modal/usage/), its position is fixed, obscuring whatever is behind it. The end user should have the ability to reposition it within the window.

### Justification

The user may need to peak around what the modal is obscuring, for example, some context in the page in the background. Today there's no way of doing that short of closing the modal, returning to the originating page, and then re-opening the modal.

### Desired UX and success metrics

The user should be able to drag the modal by its heading elsewhere on the page, away from it's originally centered position, revealing portions of the page that were covered.

### Specific timeline issues / requests

This request was raised for ELM in [518687: New Smart People picker can not be moved](https://jazz.net/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/518687).

**Comment by laurenmrice** [comment]
Hello 👋, Thanks for opening this issue.

For the modal dialog component we have in Carbon, we won't be moving forward with adding the functionality for a user to move or reposition it. I think this would be a usecase for a `modeless

**Comment by laurenmrice** [comment]
Hello 👋, Thanks for opening this issue.

For the modal dialog component we have in Carbon, we won't be moving forward with adding the functionality for a user to move or reposition it. Modals are supposed to command attention to the user to make a decision. Modals also have an overlay behind them to bring the modal dialog into primary focus, setting it apart from the rest of the UI to demonstrate the importance to take action. I think moving it out of the way would mean maybe a modal should not be used for the given usecase.

I think this would be more of a usecase for a `modeless dialog`.
