### ISSUE TITLE
Additional Motion Guidance for design-dev collaboration

### ISSUE THREAD

**Issue by lisakaiser** [carbon-design-system/carbon#7114]
### Summary

We have some [motion guidance](https://pages.github.ibm.com/ibmcloud/pal/design-guidelines/motion/overview) we wrote for Cloud PAL that we think might be useful for Carbon users and wanted to see if the Carbon team thought it would fit with the existing motion guidance. Some is redundant with what is already on the Carbon site, but some of the content around collaboration between designers and developers might be useful. We also have a section on Accessibility specifically around motion that we think would be useful for others.

### Justification

We have some guidelines around accessibility in motion design that is important to consider when designing for all.

We also have some techniques that help designers and developers collaborate on motion specifications that help bridge the gap between designing motion and implementing in product.

### Desired UX and success metrics

Resources and guidance will help designers and developers better collaborate together, as well as help developers implement motion in their code. Guidance around accessibility will help ensure designers and developers are designing an inclusive experience when working with motion.

Some possible ways to measure success/failure might be downloads of the motion specifications template, feedback from designers and developers, and ideally more contributions of components with motion.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline or deadline - we will be updating the motion guidance on Cloud PAL if this is accepted for Carbon to avoid redundancy.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Reach out to Lisa Kaiser and Stephanie Cree if you need any help - happy to help rewrite/reshape as needed to fit the Carbon tone.

**Comment by andreancardona** [comment]
@johnbister to look into it :)

**Comment by johnbister** [comment]
Thanks again for this @lisakaiser and I'm happy to hear it's on Cloud PAL :)
