### ISSUE TITLE
Visited link style(s) no longer appear

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#7115]
When applying the `visited` prop to the `Link` component, the link remains blue.

The expected behavior is that the link should turn purple.

- [x] `carbon-components`
- [x] `carbon-components-react`

In the [React storybook](https://react.carbondesignsystem.com/?path=/story/link--default), toggle the knob "Allow visited styles" in the Link story.

When inspecting the CSS, the "bx--link--visited" class is applied as expected, but the purple color nows sits behind a `:visited` pseudoselector. Is this a regression or a progression?

<img width="149" alt="Screen Shot 2020-10-22 at 9 07 01 AM" src="https://user-images.githubusercontent.com/10718366/96899904-5322fc00-1446-11eb-8ea4-dc19390a057a.png">

**Comment by emyarod** [comment]
may be related to https://github.com/carbon-design-system/carbon/issues/3581 https://github.com/carbon-design-system/carbon/pull/5239

**Comment by metonym** [comment]
@emyarod Thanks for the clarification
