### ISSUE TITLE
Module not found: Can't resolve '@carbon/icons-react'

### ISSUE THREAD

**Issue by zoranid** [carbon-design-system/carbon#7127]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [] `'@carbon/icons-react'`

## Relevant information

Trying to go trough carbon/react tutorial on mac os 10.15.7. I can not pass the step 
src/components/TutorialHeader/TutorialHeader.js

import {
  AppSwitcher20,
  Notification20,
  UserAvatar20,
} from '@carbon/icons-react';

./src/components/TutorialHeader/TutorialHeader.js
Module not found: Can't resolve '@carbon/icons-react' in '/Users/zoran@ibm.com/erdm/uiapp/carbon-tutorial/src/components/TutorialHeader'

Manual import also fails
Zorans-MacBook-Pro:carbon-tutorial zoran@ibm.com$ yarn add carbon-icons@7.0.7
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > carbon-components-react@7.3.0" has incorrect peer dependency "carbon-components@10.3.0-rc.2".
warning "carbon-components-react > downshift@1.31.16" has unmet peer dependency "prop-types@>=15".
[4/4] 🔨  Building fresh packages...
[1/2] ⠁ fsevents
warning Error running install script for optional dependency: "/Users/zoran@ibm.com/erdm/uiapp/carbon-tutorial/node_modules/react-scripts/node_modules/fsevents: Command failed.

**Comment by tw15egan** [comment]
can you try running `yarn add @carbon/icons-react`

**Comment by zoranid** [comment]
A few days ago that did not work, but somehow worked yesterday. At the moment I have problem with git push described here: https://github.com/carbon-design-system/carbon-tutorial/issues/6041
