### ISSUE TITLE
DataTable: Is it possible to filter columns when they contain controllers and not only a plain text?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#7128]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

If DataTable columns contains controllers (like: TextInput, DropDown) the filter doesn't work. It has to be a plain text.
is there a way to customize it and enable the filter to the content of the column controllers?

**Comment by dakahn** [comment]
Could you provide a code sandbox (in the issue template) demonstrating this issue? Do you mean form elements in column headers?

**Comment by zbeedatm** [comment]
elements in cells, not in column headers.
I'm asking in general at this stage, is it possible to customize the filter behavior to look into TextInput text for example and retrieve it if there is a match?!
Currently the filter is working for me only if cells includes plaint text.

**Comment by zbeedatm** [comment]
Kindly update with your response.

**Comment by tw15egan** [comment]
@zbeedatm currently there is no way to filter a DataTable based on what is contained in a TextInput in an individual cell. Hope that clears it up.

**Comment by zbeedatm** [comment]
Ok thanks.
