### ISSUE TITLE
Carbon Tabs classes duplicated

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#7129]
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The current 7.22.0 version of the tabs has two levels of div with bx--tabs--scrollable

![image](https://user-images.githubusercontent.com/15086604/97171277-17a96a00-1785-11eb-933d-aee58d167896.png)

This is probably a mistake.

## Steps to reproduce the issue

1. View source code https://react.carbondesignsystem.com/?path=/story/tabs--default

**Comment by emyarod** [comment]
resolved in https://github.com/carbon-design-system/carbon/pull/7109
