### ISSUE TITLE
all-contributors

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#7135]

**Comment by tw15egan** [comment]
@all-contributors please add @tw15egan for documentation and code

**Comment by tw15egan** [comment]
@all-contributors please add @joshblack @emyarod @dakahn @asudoh @aledavila @andreancardona @jnm2377 @vpicone @rjhenriquez @sstrubberg  for code

**Comment by tw15egan** [comment]
womp womp can only add 1 at a time

**Comment by vpicone** [comment]
@tw15egan dont give up!

**Comment by tw15egan** [comment]
@vpicone used the CLI version to [get the initial list](https://github.com/carbon-design-system/carbon/pull/7140/files), we can use the bot for future ones 🎉
