### ISSUE TITLE
Not possible to use Plex Sans Medium Weight

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon#7147]
### Summary
Today carbon only supports three font weights of Plex:  Light, Regular, and SemiBold. Our requirement in Maximo modernization is to support Medium weights. IBMPlexSans-Medium,sans-serif is currently not available.

Clarify if you are asking for design, development, or both design and
development.

### Justification
Design team has decided to use medium weights on their deliverables

### Desired UX and success metrics
Medium weight is shipped within Carbon React base

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

Today carbon only supports three font types: 

	font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;
	font-family: 'IBM Plex Serif', 'Georgia', Times, serif;
	font-family: 'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', Courier, monospace;

With three IBM Plex Weights (Did not implement medium and bold weights):
		IBM Plex Light, Regular, and SemiBold 

Link: https://www.carbondesignsystem.com/guidelines/typography/overview

There is a requirement from our design team to implement Plex Sans size 20 with weight of Medium and Plex Sans size: 16 for Medium and bold.
The results are noticeably different when we tried to use comparable medium and bold weight on the currently supported carbon IBM Plex style

**For font size: 20 and with medium weight when :**
font-family: IBMPlexSans-Medium,sans-serif: (not currently available)
![image](https://user-images.githubusercontent.com/21066152/97317881-abd90700-1841-11eb-9a9d-b32f4a86df94.png)

font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif; with font-weight: 500:
![image](https://user-images.githubusercontent.com/21066152/97317890-af6c8e00-1841-11eb-9aae-f768780fe60b.png)

**For font size: 16 and with medium  weight:**
font-family: IBMPlexSans-Medium,sans-serif: (not currently available)
![image](https://user-images.githubusercontent.com/21066152/97317923-b5626f00-1841-11eb-872d-935817ec1153.png)

font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif; with font-weight: 500
![image](https://user-images.githubusercontent.com/21066152/97317939-bc897d00-1841-11eb-80ab-d231b1058760.png)

**For font size: 16 with bold weight:**

font-family: IBMPlexSans-Bold,sans-serif; (not currently available)
![image](https://user-images.githubusercontent.com/21066152/97318033-d034e380-1841-11eb-84ad-dc7e8ebdb95d.png)

font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;
![image](https://user-images.githubusercontent.com/21066152/97318052-d6c35b00-1841-11eb-83d7-5c0400ad08bb.png)
	 
At the end we decided to set medium to weight semibold and bold to weight of 900

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?  March, 2021 (Maximo Asset Suite 8.4)

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?
We do not have resource available
_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by aagonzales** [comment]
@JordanWSmith15 Can you share some screens where the medium weight is being used? Right now it is also not within any of our type styles. We can discuss with the @mjabbink and @jeanservaas once you share examples.

**Comment by mjabbink** [comment]
I would need to see the examples of Medium and learn more about “why” you want to use that weight. Is this an IBM product?

**Comment by JordanWSmith15** [comment]
Retracting this request!
