### ISSUE TITLE
Text/NumberInput and Select components have different height

### ISSUE THREAD

**Issue by showeimer** [carbon-design-system/carbon#715]
## Detailed description

We are rendering the NumberInput and Select components side by side on a form on ICP and the height of the Select component is taller than the NumberInput and is causing a design defect.

> Is this issue related to a specific component? 

TextInput/NumberInput and Select components

> What did you expect to happen? What happened instead? What would you like to see changed?

Form components should have consistent styling.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

    "carbon-components": "^8.6.0",
    "carbon-components-react": "^5.29.5",
    "carbon-icons": "^6.2.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ICP

## Additional information

<img width="750" alt="screen shot 2018-04-19 at 1 55 42 pm" src="https://user-images.githubusercontent.com/26075187/39009422-9317ff4e-43d9-11e8-81b1-f2cebd3e0310.png">

---

<img width="594" alt="screen shot 2018-04-19 at 1 43 28 pm" src="https://user-images.githubusercontent.com/26075187/39009252-2300dc44-43d9-11e8-94a3-b8acba41a859.png">
<img width="620" alt="screen shot 2018-04-19 at 1 43 45 pm" src="https://user-images.githubusercontent.com/26075187/39009255-2481fce2-43d9-11e8-9322-ec40b3f39c48.png">

**Comment by tw15egan** [comment]
@marijohannessen should we bundle this in with the input updates, or a separate fix?

**Comment by ghost** [comment]
@tw15egan i upgraded to the latest carbon version with your change, but the select still looks slightly off to me when used in the same row as the number input.

<img width="527" alt="screen shot 2018-05-23 at 9 45 59 am" src="https://user-images.githubusercontent.com/17085131/40429284-52faac66-5e70-11e8-96c0-8b00c88e25a1.png">

**Comment by alisonjoseph** [comment]
@alisonemiller I quickly dropped these in a codepen and they are lining up correctly. (in chrome and FF) https://codepen.io/alisonjoseph/pen/ZoZPaR?editors=1100

**Comment by ghost** [comment]
thanks, @alisonjoseph. yes, i think this is on us actually. i was able to pinpoint the problem. sorry for the false alarm!
