### ISSUE TITLE
`TooltipDefinition` does not account for long strings

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/carbon#7153]
## `TooltipDefinition` does not account for long strings

https://codesandbox.io/s/currying-dew-8jedb

![TooltipDefinition](https://user-images.githubusercontent.com/3846874/97431424-2e30fc00-1912-11eb-8c8d-1d82a2c29472.png)

**Comment by emyarod** [comment]
the `max-width` is set as a guideline based on our design recommendations for tooltip content length, but it can be overridden with CSS

**Comment by SimonFinney** [comment]
That makes sense - in this case I believe the issue is how the word breaking is (or isn’t) handled, but perhaps that’s something that should also vary on a case-by-case basis

**Comment by tw15egan** [comment]
We could add `word-break: break-all` by default if we want to handle this a bit more gracefully

https://codesandbox.io/s/youthful-taussig-m7ju3?file=/src/index.js

**Comment by SimonFinney** [comment]
I'm good with that!

**Comment by emyarod** [comment]
cc @carbon-design-system/design would this be okay to proceed with?

**Comment by aagonzales** [comment]
Just to clarify, we're keeping the max width but adding in a feature for word wrapping? Yeah I'm good with that.
