### ISSUE TITLE
button: need of a select/active property settable via the API

### ISSUE THREAD

**Issue by ptoussaint** [carbon-design-system/carbon#7157]
context: we are using the ghost buttons to populate our text toolbar, we need to indicate that certain properties are active or not based on the text selection: for example, bold or or italic; 
the candidate applied style is to have the background color set to "ui-selected"

Regardless of the applied style, at the API level, we need to be able to set a property on the button, similar to the "kind" one, for instance,

**Comment by laurenmrice** [comment]
Under the hood I believe that these components that look like icon/ghost buttons are actually coded as menu items. So they would already include the selected state using the `selected-ui` token. They would not need an active state in this case. Tagging @joshblack for a more technical clarification if needed.
