### ISSUE TITLE
[code snippet] single line and multi-line bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7159]
There are a couple different bugs with the `single line` and `multi-line` code snippets.

-------------------------------------------------------------------------------------------------------------------------

**Single line:**
- The active state is not showing up when clicking on the copy button. It should be active-ui on click.
![code snippet active](https://user-images.githubusercontent.com/43969356/97491064-08b6e900-1938-11eb-85bf-e58eab973b89.gif)

- The horizontal scroll does not have a fade style. (This may be resolved with Andrews fix for horizontal tab scrolling.)
- When the light prop is active, the dark themes have incorrect hover states for the copy button and show more button. They should be using `hover-light-ui` for hover. (this is also happening for inline code snippet)
-------------------------------------------------------------------------------------------------------------------------

**Multi-line:**
- The active state is not showing up when clicking on the copy button (same problem with single line above^). 
- When the light prop is active, the dark themes have incorrect hover states for the copy button and show more button. They should be using `hover-light-ui` for hover.
- The copy button should have a 8px top and right padding within the field background so that it vertically aligns with the chevron icon in the show more button below it. 
![Artboard](https://user-images.githubusercontent.com/43969356/97491037-ffc61780-1937-11eb-94f4-e05246ce5469.png)

**Comment by tw15egan** [comment]
I'm also wondering if we should investigate adding in copy functionality by default (https://github.com/carbon-design-system/carbon/issues/6995)

**Comment by emyarod** [comment]
makes sense, if we're all on board with it then I can investigate that as well. I guess the biggest thing to look into would be browser and OS support

**Comment by tw15egan** [comment]
It looks like `clipboard` has gained quite a bit of native browser support (at least for copy), we may even be able to just handle this natively without an external library: 

https://caniuse.com/clipboard

https://stackoverflow.com/questions/39501289/in-reactjs-how-to-copy-text-to-clipboard

**Comment by emyarod** [comment]
for the light button hover styles, it looks like we are already using the `hover-ui-light` token https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/code-snippet/_code-snippet.scss#L373. Should the value of that token be changed? (draft PR here https://github.com/carbon-design-system/carbon/pull/7214)

and for the overflow indicators, what should the color tokens be? I have this ready to put in a separate PR but just need clarification on the colors

**Comment by laurenmrice** [comment]
## **Hover issue:**

- The current values for the `hover-light-ui` token are correct. The color is not displaying correctly on hover for the dark themes.

### Example of what is happening now:
![Nov-06-2020 12-34-42](https://user-images.githubusercontent.com/43969356/98402314-130e6c80-2035-11eb-8623-0bbe3b7f3baa.gif)

---------
### This is what it should look like:
![Artboard](https://user-images.githubusercontent.com/43969356/98402622-9e87fd80-2035-11eb-8e4f-e9ed80db0630.png)

**Comment by laurenmrice** [comment]
## Overflow issue (horizontal scroll)
- The fade style should be the same as what we currently use for the `modal` component when a modal scrolls vertically.

### Spec:
![lg-1056px-16 column](https://user-images.githubusercontent.com/43969356/98405448-50c1c400-203a-11eb-922e-59d36392c5bf.png)
