### ISSUE TITLE
Tooltip and Forms misleading documentation + storybook defects

### ISSUE THREAD

**Issue by andreagmann** [carbon-design-system/carbon#7164]
The Tooltip story suggests that the interactive tooltip should be used with the info icon, which is often used in form field labels. https://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom

The Tooltip documentation doesn't really address the info icon usage - whether it should show on hover or on click.

The Forms documentation has a small line of text regarding the tooltip usage: "Tooltip appears on hover (desktop) and on click (tablet and mobile)." https://www.carbondesignsystem.com/patterns/forms-pattern#offering-help

The Form story does not show any form field with a tooltip. But the Form Label story shows a "With Tooltip" example. The tooltip comes up on click, not on hover. https://react.carbondesignsystem.com/?path=/story/formlabel--with-tooltip

Not having seen the small print in the Forms documentation, the storybook examples are very misleading, especially for developers who are not checking pattern documentations.

Requests:

1. Showcase the info icon example in the Tooltip story using the correct component - Icon Tooltip?
2. Include documentation that specifies when it could make sense to have an interactive tooltip with an info icon.
3. Highlight the fact that tooltips in Forms should appear on hover and use the correct component - Icon Tooltip?
4. Correct the Form Label "With Tooltip" story to appear on hover.

**Comment by andreancardona** [comment]
@andrea-gm This issue has been documented and noted in: https://github.com/carbon-design-system/carbon/issues/6562. & closing out :)

**Comment by andreagmann** [comment]
@andreancardona will https://github.com/carbon-design-system/carbon/issues/6562 cover the updates to the documentation or only code changes?
