### ISSUE TITLE
Would like for the AccordionItem to span the entire width of the Accordion

### ISSUE THREAD

**Issue by MarcelPoirier** [carbon-design-system/carbon#7174]
### Summary
Currently the Accordion component forces left and right padding (right is 25% of the width) on its content.  While this makes sense if you have text in the accordion our UX thinks that if you have other components (e.g. Input control) that they should span the entire width of the accordion.

Clarify if you are asking for design, development, or both design and
design & development.

### Justification
In Cognos Analytics we sometimes use the Accordion to bucket properties.  Our UX thinks that those properties should span the entire width of the accordion.  For example
![image](https://user-images.githubusercontent.com/31481145/97610188-edf17c80-19ea-11eb-85db-fa15ae8b51a9.png)

### Desired UX and success metrics
New property on the Accordion or AccordionItem to specify that you want the content to span the entire width.
![image](https://user-images.githubusercontent.com/31481145/97610281-0d88a500-19eb-11eb-990f-3c95fa617aec.png)

### Specific timeline issues / requests
We will most likely override the Carbon CSS for our upcoming release, but would like this ASAP

**Comment by vpicone** [comment]
That padding is there for the base, common case (typography). If you're supplying components, they can go all the way to 16px padding. Use a padding that is appropriate for your content. This would be a case where you could feel free to override our style.

**Comment by aagonzales** [comment]
This is similar to what happens in Modal 
https://carbondesignsystem.com/components/modal/usage#alignment
