### ISSUE TITLE
Hover state on icons/glyphs? 

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon#719]
Hey y'all.

We have a "launch" icon (glyph?) that is clickable in our product. We're trying to figure out

1) If it should have a hover state, when it is used as part of a hyperlink.
2) If so, where should the style be set for the hover state (by Carbon? By our team?)

See the comment here: https://github.ibm.com/alchemy-containers/armada-ui/issues/1810#issuecomment-5582715

From @jpomero:

"Color: The carbon bx--link class only updates the color of the link, not the fill color for any SVG elements. Our fix would be to override their class so therefore this should get punted to carbon.

Size: We are using the correct icon, but we are setting a size of 15x15 on it. I don't have a strong feeling about making this 16x16 as long as it looks fine. Also, this should be the same thing we're doing anywhere this icon is displayed, not specific to this link."

What do you think?

**Comment by tw15egan** [comment]
@carbon-design-system/design If a link is wrapping an SVG, should the hover styles also be applied to the icon? I'm guessing if we would add this, it would get the `hover-primary-link` styles?


![image](https://user-images.githubusercontent.com/11928039/39371217-a7884640-4a06-11e8-9a14-c45a45346511.png)

**Comment by aagonzales** [comment]
Yes, the associated icon should also have the same hover style applied.
