### ISSUE TITLE
[Ghost button] Add support for the selected state (pushed)

### ISSUE THREAD

**Issue by cheer021** [carbon-design-system/carbon#7190]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Please describe your request in one or two sentences.
- Currently, the button does not support a `selected` state, it has style for active and focus state. The enhancement/ask is to support `selected` state. 
eg. when the button is selected, even we move the focus away from the button, the background colour is xx color.

Clarify if you are asking for design, development, or both design and
development.
- It depends. If the selected state has a unified UX design, we need both design and development. If carbon can provide a css class name for the selected state or callback so consumers can style it, only development is needed.

### Justification

Provide the business reasons for this request.
- Support for IBM Cognos analysis UX requirement

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by tw15egan** [comment]
Related https://github.com/carbon-design-system/carbon/issues/7157

**Comment by jnm2377** [comment]
Maybe I'm missing something, but is this not what you're looking for?

<img width="662" alt="Screen Shot 2021-04-23 at 9 16 01 AM" src="https://user-images.githubusercontent.com/32556167/115884450-8b66bf80-a414-11eb-866b-ef516eaadae5.png">

**Comment by tw15egan** [comment]
@jnm2377 I believe it's pretty strict in regards to which variants it can be used for, it looks like it's only allowed on [icon-only ghost buttons](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Button/Button.js#L136)

@carbon-design-system/design is this something we would want to extend to other variants?

**Comment by aagonzales** [comment]
Yes, its only allowed for icon-only ghost button for scenarios like a tool bar. 

Most of the time buttons are used to trigger actions instantly and don't required a selected state. One exception we have found is the toolbar scenario but the icon only button. @cheer021 What is the use-case for needing a regular button to have a selected state? Could you provide an in-context image?

**Comment by vpicone** [comment]
Going to close this one out, let us know if something changes. Also recommend checking out the Toggle component.
