### ISSUE TITLE
Wrong links in API Documentation sections in README files

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#7191]
The `API Documentation` section in some packages READMEs has wrong links.

For example, the [@carbon/layout ](https://www.npmjs.com/package/@carbon/layout) package has [this link](https://github.com/carbon-design-system/carbon/tree/master/packages/layout/blob/HEAD/docs/sass.md) which doesn't exist in the repo. It has an extra path at the end `blob/HEAD/docs/sass.md`
![image](https://user-images.githubusercontent.com/6926228/97747416-50697c00-1ac2-11eb-8a00-6d23e073e78e.png)

Same thing for:

- [@carbon/type](https://www.npmjs.com/package/@carbon/type)
- [@carbon/grid](https://www.npmjs.com/package/@carbon/grid)
- [@carbon/colors](https://www.npmjs.com/package/@carbon/colors)

There might be other packages with the same issue but those are the ones I checked.

**Comment by emyarod** [comment]
this seems to be an issue with how npm resolves relative links in READMEs. we already have defined the `repository` field in our `package.json` files according to this thread from a couple years ago https://npm.community/t/relative-links-in-npm-readme-markdown-not-functional/1525

**Comment by tw15egan** [comment]
@emyarod any action we can take then?

**Comment by emyarod** [comment]
I thought about hard coding the links but it may be better to raise this issue against npm instead, since most if not all of our documentation links use relative paths which not only work on GitHub but also in editors like VS Code

**Comment by dbrugger** [comment]
not sure if this is the reason but `https://github.com/carbon-design-system/carbon/tree/master/packages/layout` in https://github.com/carbon-design-system/carbon/blob/master/packages/layout/package.json might technically not be a repository but a directory within one ... could try use use the `directory` property instead? https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository
