### ISSUE TITLE
[content switcher] double focus in firefox

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7203]
**Bug in firefox:**

The content switcher is receiving our custom focus plus the default firefox focus state at the same time.
![image](https://user-images.githubusercontent.com/11670886/97923693-067fd080-1d24-11eb-9db6-757b7fe4c5a2.png)

**Comment by emyarod** [comment]
is this related to a browser or OS setting? I'm not able to replicate this on macOS or Windows in Firefox 82 or Firefox 84

![image](https://user-images.githubusercontent.com/8265238/98261100-b1bd9f00-1f49-11eb-86ec-c331d8c7df36.png)

**Comment by tw15egan** [comment]
Also unable to reproduce in Firefox 82 🤔

**Comment by aagonzales** [comment]
Oh i'm in Firefox 72.0.2 let me update.

**Comment by aagonzales** [comment]
Ok yeah once I updated it don't see it so that was it.

**Comment by tw15egan** [comment]
🎉
