### ISSUE TITLE
Link focus style is inconsistent between implementation and sketch kit

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#7208]
The focus style for links is a 1px blue outline in the implementation but a 3px blue underline in the sketch kit.
![image](https://user-images.githubusercontent.com/28265588/97968678-45af2f80-1dbf-11eb-8ad6-22993bc260e2.png)
![image](https://user-images.githubusercontent.com/28265588/97968949-a474a900-1dbf-11eb-9b26-89be55b0de7e.png)

Personally, I think the outline works better as it matches most other Carbon focus styles and it has a higher differentiation to the inline link with its 1px blue underline.
![image](https://user-images.githubusercontent.com/28265588/97968967-a8083000-1dbf-11eb-96ab-429f14ee3099.png)

In either case it'd be great if the implementation and sketch kit would use the same styling to prevent incosistencies in the screens designers produce vs. the implemented product.

**Comment by joshblack** [comment]
@laurenmrice when you have a sec could you help us confirm which style is correct? 👀

**Comment by laurenmrice** [comment]
@joshblack It is correct in code according to this issue https://github.com/carbon-design-system/carbon/issues/3059 and this merged PR https://github.com/carbon-design-system/carbon/pull/3225. 

We have an issue to update this in the design kit repo 👍🏻
