### ISSUE TITLE
Collapsing SideNav via button inside SideNav in Chrome causes focus ring to prevent expansion/collapse until clicking away

### ISSUE THREAD

**Issue by KyeMaloy97** [carbon-design-system/carbon#7209]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When trying to collapse or expand the sidebar in Chrome, the focus ring appears on the initial click and the opening/closing animation does not play and the sidenav doesn't change. When you click elsewhere on the page, the button loses focus and the animation plays and the sidebar collapses/expands. 

This is not happening in Firefox or Safari. These browsers also don't show the focus ring on the initial click on the button. 
sign System are you using?

Would ideally be fixed before a Q1 2021 release.

## Steps to reproduce the issue

1. Go to the codeine example
2. Click on the button in the bottom left to collapse the sidenav

You'll see the button get a blue highlight in Chrome and then you'll need to click somewhere else on the page to get the sidebar to collapse. You can click the button over and over in Chrome and it won't collapse or expand until its lost focus.

Here is the link to the codesandbox example: https://codesandbox.io/s/awesome-dew-8duk1

Try opening that link in both chrome and safari to see the bug.

### Chrome
![Chrome](https://user-images.githubusercontent.com/24469095/98010660-da7d5180-1dee-11eb-8430-e3e57e8162db.gif)

### Safari
![Safari](https://user-images.githubusercontent.com/24469095/98010791-0bf61d00-1def-11eb-92c5-45a80777dc1c.gif)

**Comment by aledavila** [comment]
Thanks for submitting this!


For carbon: We need to implement/ update SideNavFooter
