### ISSUE TITLE
DataTables default sorting

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#7213]
Is there a way to sort a column by default in the carbon DataTables? I have read about the customer sorting 

https://react.carbondesignsystem.com/?path=/docs/datatable-sorting--usage#custom-sorting

and that only seems to work when you click on a sortable header. The programming sorting

https://react.carbondesignsystem.com/?path=/docs/datatable-sorting--usage#programmatic-sorting

doesnt seem to work for me, it causes a lot of refreshes which crashes the app, and I am not even sure where the proper place to call it when the header prop is available.

So is there a way to do this?

**Comment by emyarod** [comment]
> Is there a way to sort a column by default in the carbon DataTables?

would rendering data that's presorted on the column you want work for you?

**Comment by TannerS** [comment]
It's possible. For the code base we are using, I don't control that part.
But if that is the only way to do it then I can bring it up :)

**Comment by emyarod** [comment]
yeah I don't think it's possible to define a custom sort since we assume the application has control of the data they are passing to the component

**Comment by tw15egan** [comment]
Closing this out, but feel free to reopen if you've got any other issues @TannerS
