### ISSUE TITLE
NumberInput value type for Typescript

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#7225]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Summary

I read code for `NumberInput.js` and storybook for this component. When I turn on `allowEmpty` option for this component, I have to be able to pass `empty value` to `value` prop. It is possible in storybook because it is javascript which doesn't check type. (just using propTypes)

Of course, I'm using `@types/carbon-components-react`, but type definition of `value` is also `number`. It should be `number | string` to pass `empty value`. How can I solve this problem? There are several options.

1) Open PR to Definitely-Typed repo → I think it takes a lot of time to be merged.
2) Extend existing type definition for `NumberInput` → I tried, but it's failed. If you know how to, plz let me know.
3) Port `NumberInput.js` to `NumberInput.tsx` which is typescript version **(what I'm doing is this)**

## Relevant information

Type definition of `@types/carbon-components-react`.

```typescript
...
interface InheritedProps extends
    Omit<ReactInputAttr, ExcludedAttributes>,
    EmbeddedIconProps,
    InternationalProps<NumberInputTranslationKey>,
    RequiresIdProps,
    ThemeProps,
    ValidityProps,
    RefForwardingProps<HTMLInputElement>
{
    value: number,
}

export interface NumberInputProps extends InheritedProps {
    allowEmpty?: boolean,
    helperText?: React.ReactNode,
    hideLabel?: boolean,
    label?: React.ReactNode,
    isMobile?: boolean,
    size?: Extract<CarbonInputSize, "sm" | "xl">,
}
...
```

**Comment by joshblack** [comment]
Hi there @baeharam! 👋 

Unfortunately for TypeScript we defer to the community to maintain the types over at DefinitelyTyped for `@types/carbon-components-react`. We don't work with the TypeScript types themselves over on our end 😞  There may be a chance for us to update the source to use TypeScript for our next major release, but unfortunately aren't able to make the update now.

Hope this helps!

**Comment by baeharam** [comment]
@joshblack Thx for response. Then, it is the best way to open PR to DefinitelyTyped? and does PR permitted to be merged if I'm not IBM person?

**Comment by baeharam** [comment]
I opened [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49391) for this

**Comment by baeharam** [comment]
Solved by above PR
