### ISSUE TITLE
Vue code sample for cv-date-picker has incorrect event listener specified

### ISSUE THREAD

**Issue by john-maddock** [carbon-design-system/carbon#7238]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Im using the cv-date-picker in Vue Carbon components library. 
i took the sample code below from the documentation here 
http://vue.carbondesignsystem.com/?path=/info/components-cvdatepicker--default

<cv-date-picker kind="short" pattern="\d{1,2}/\d{2}" placeholder="mm/yy" @onChange="actionChange"> </cv-date-picker>

I noticed the 'change' event was firing when i modified the date but the docs specify '@onChange'. This doesnt work .... The docs should be changed to '@change' which works.

> Is this issue related to a specific component?
cv-date-picker 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components-vue #1072](https://github.com/carbon-design-system/carbon-components-vue/issues/1072) via [**ZenHub**](https://www.zenhub.com/)
