### ISSUE TITLE
Datatable to support light variation 

### ISSUE THREAD

**Issue by shroffsmiti** [carbon-design-system/carbon#7241]
### Summary
Datatable to support light variation similar to other component like dropdown.

### Justification
Lot of time we get request from our design team to have a white background for datatable.

**Comment by brandones** [comment]
Related to https://github.com/carbon-design-system/carbon/issues/4120 and its corresponding PR https://github.com/carbon-design-system/carbon/pull/4549 .

This is a common request for my team as well.

**Comment by vpicone** [comment]
This will be possible in v11 with changes to theming.
