### ISSUE TITLE
When OverflowMenu has a OverflowMenuItem with a tooltip, it clicks it by default

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon#7242]
It seems like on the latest carbon, if a OverflowMenuItem has a tooltip it will attempt to click it, which causes all sorts of problems. On some cases, the tooltip is open by default. In other cases, it auto-closes the menu.

see this sandbox for how to recreate:
https://codesandbox.io/s/affectionate-cherry-9godh 

also see this screenshot for the problematic behavior in our code base:

![image](https://user-images.githubusercontent.com/10033254/98396665-b48cc280-2023-11eb-8a3d-6958008a3e39.png)

@andreancardona

**Comment by andreancardona** [comment]
@amortiz 

Hello! Just got a response from our design team: 

`I would recommend not putting a tooltip inside of an overflow menu. It is too many layers to work with.`

Let us know if you have any other questions! Also feel free to reopen the issue if I'm misunderstanding!
