### ISSUE TITLE
Create new pictogram image for an IBM Z HMC

### ISSUE THREAD

**Issue by djfitzgerald** [carbon-design-system/carbon#7243]
### Summary

I am using carbon design elements for an external presentation to an IBM customer.  I need a pictogram to represent an IBM Z HMC (Hardware Management Console).  The Z logo with a tree underneath it would be good; this would symbolize a Z CPC and the individual HMC partitions on that CPC.

I am asking for design.

### Justification

I am providing an external presentation on how a new software architecture works, and need a carbon symbol to represent an HMC managed Z CPC.

### Desired UX and success metrics

Literally just an image, which I have already designed.  I felt it would serve more use if I could contribute the final product to the carbon community so that others would be able to use it.

### "Must have" functionality

N/A

### Specific timeline issues / requests

None.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

I have already designed a new SVG asset that merges the `ibm--z.svg` pictogram wit the `locked--network--alt.svg` pictogram.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by djfitzgerald** [comment]
Can somebody assign this issue to me?

**Comment by andreancardona** [comment]
> Can somebody assign this issue to me?

Hello @djfitzgerald - feel free to submit the icon here: https://github.ibm.com/brand/Pictograms/issues/new/choose for a single pictogram 

and please make sure to mention @dudley-ibm - thanks!

**Comment by dudley-ibm** [comment]
and please also mention @conradennis when you submit. Thanks!
