### ISSUE TITLE
Combobox inteligent width adjustments

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon#7245]
The design in IBMDOCS required setting an auto/intelligent width for a combobox.
In the storybook for this component, and how this behaves so far we tried, is the combobox expects either
a container with a fixed size, or setting a fixed size to the combobox.
What was expected from our designer is:
- able to set a minimum combobox width, ie. 200px
- if the items are larger then minimum width, combobox should scale up the width up to the size of the parent container
links to try - one with small one with large item 
https://ibmdocs-dev.mybluemix.net/en/SSLTBW_2.4.0
https://ibmdocs-dev.mybluemix.net/en/P8DEA

for this to work we had to employ a resize event and calculate the combobox width manually and set it in style.
browsers expected FF,Chrome,Edge

**Comment by joshblack** [comment]
Hi there, @kyjak! 👋  I think what you observed is spot-on, the component currently will expand to fit the full width. I think the situation you described is how we would expect folks to modify this component given that it spans full width, but I'm curious what kind of enhancements you think we could add to make this experience better on your end 👀
