### ISSUE TITLE
Link in tooltip has incorrect color

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7247]
When interacting with a link inside of a nonmodal dialog tooltip, the color goes dark instead of to white which seems to be the intended

![tooltip-blackonclick](https://user-images.githubusercontent.com/3901764/98567570-b4840100-2275-11eb-9e81-f792247d3a9d.gif)

**Comment by emyarod** [comment]
is this related to a browser or OS setting? I'm not able to reproduce this in Firefox, Chrome, or Safari on macOS or Windows

![Kapture 2020-11-09 at 10 34 26](https://user-images.githubusercontent.com/8265238/98568900-388ab880-2277-11eb-99d0-ccea982ce9b4.gif)

**Comment by joshblack** [comment]
@emyarod I think it's coming from visited styles:

![image](https://user-images.githubusercontent.com/3901764/98834490-e2e41680-2404-11eb-9ee1-d2fe2d3dafbb.png)

**Comment by emyarod** [comment]
still trying to replicate this since we already use the correct color token for active visited links in the tooltip styles, will try some more tests

![image](https://user-images.githubusercontent.com/8265238/98855249-5005a500-2421-11eb-8d93-317a155fe64d.png)

edit: I think I have a fix
