### ISSUE TITLE
[Enhancement] Support secondary or multi-column sorting on tables

### ISSUE THREAD

**Issue by showeimer** [carbon-design-system/carbon#725]
Requesting an enhancement on the Carbon tables to support secondary sorting or more.  We have an issue open on ICP where the user is having UX issues on one of our tables.  

The data being generated for one specific table is all being created at ICP installation; so they all share the same timestamp.  All of our tables default to sorting by time of creation.  We are doing API calls about every 5 seconds, so the data that is getting returned starts shifting in random order each call because the timestamps are all the same.  

We may default this table to sort by the name field for now, but we prefer to have the newest information always available to the user at the top by default.  It would be great to be able to sort by time first and name second.  The user who opened the issue on ICP provided the screenshots below:

#### First View:

![first](https://user-images.githubusercontent.com/26075187/39309294-a0cda060-4935-11e8-8efd-3ffd45a29eac.png)

#### After API call:

![second](https://user-images.githubusercontent.com/26075187/39309308-a6e14e98-4935-11e8-9727-1dd1ae82ad03.png)

**Comment by joshblack** [comment]
Hi @showeimer! 👋 Thanks for taking the time to suggest this enhancement 🙂

Definitely agreed that multi sort would be valuable! Unfortunately this isn’t something immediately on our roadmap, as we are working on table edits currently, but we would gladly accept PRs that add in this behavior!
