### ISSUE TITLE
Event Documentation for Interior left nav

### ISSUE THREAD

**Issue by darroughw** [carbon-design-system/carbon#726]
Please provide event documentation for for the Interior left nav events on carbondesignsystem.com. For example 'left-nav-beingtoggled'

**Comment by asudoh** [comment]
Issue moved to [carbon-design-system/carbon-addons-cloud-vanilla #27](https://github.com/carbon-design-system/carbon-addons-cloud-vanilla/issues/27) via [**ZenHub**](https://www.zenhub.com/)
