### ISSUE TITLE
Tooltips disappearing when clicking different tooltips

### ISSUE THREAD

**Issue by queeniema** [carbon-design-system/carbon#7260]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When there are multiple tooltips and one tooltip is open, clicking on another tooltip causes the second tooltip to briefly appear and then disappear.

> Is this issue related to a specific component?

Yes, the `Tooltip` component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the second tooltip to stay open after clicking on it.

> What browser are you working in?

Google Chrome Version 86.0.4240.193

> What version of the Carbon Design System are you using?

`carbon-components`: 10.23.2
`carbon-components-react`: 7.23.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See this sandbox: https://codesandbox.io/s/tooltips-kpcbk?file=/src/index.js

1. Click on the tooltip next to **Text input (tooltip with no id) 1**. Notice that the tooltip stays visible.
2. Click on the tooltip next to **Text input (tooltip with no id) 2**. Notice that the tooltip appears for a brief moment and then disappears.

![Screen Recording 2020-11-10 at 9 39 23 AM](https://user-images.githubusercontent.com/2454818/98710715-e316e000-2338-11eb-8558-d5aed8b1fb92.gif)

This was discussed in this [Slack thread](https://ibm-analytics.slack.com/archives/C2K6RFJ1G/p1603316421150500), where it was suggested to add unique `id` props to each `Tooltip`. I tried this and it _did_ fix the disappearing tooltip issue (play around with the **Text input (tooltip with id)** tooltips to see this), but it causes accessibility issues where you can no longer tab between text inputs (from tooltip to text input and so forth). In the case where tooltips do not have `id` props, tabbing is fine.

![Screen Recording 2020-11-10 at 9 40 41 AM](https://user-images.githubusercontent.com/2454818/98710954-2f622000-2339-11eb-9572-c681502bcc4f.gif)

**Comment by emyarod** [comment]
rather than `id` can you try setting `tooltipId` instead? https://codesandbox.io/s/tooltips-forked-wmduk

**Comment by queeniema** [comment]
Using `tooltipId` still causes tooltips to disappear.


![Screen Recording 2020-11-19 at 8 11 10 AM](https://user-images.githubusercontent.com/2454818/99692940-af763d00-2a3f-11eb-9387-9270106e2647.gif)
