### ISSUE TITLE
TextInput requires 280+ properties

### ISSUE THREAD

**Issue by matias-quezada** [carbon-design-system/carbon#7271]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Hi there! we at [Hack&Craft](https://hackandcraft.com/) have started using Carbon Design System with React and found this weird issue with `TextInput` where the field requires 280+ properties to be required.

I assume there's an error since it doesn't sound right to require so many properties for an input field.

```
Type '{ value: string; }' is missing the following properties from type 'Pick<PropsWithChildren<TextInputProps>, "form" | "slot" | "style" | "title" | "pattern" | "children" | "type" | "defaultChecked" | "defaultValue" | ... 281 more ... | "invalidText">': id, labelText
```

### Versions
- `carbon-components`: 10.22.0
- `carbon-components-react`: 7.22.0
- `typescript`: 3.7.5

### Code to reproduce:

```ts
import { TextInput } from 'carbon-components-react';

export function Test() {
  return <TextInput value="test" />
}
```

### Screenshot

![Screenshot 2020-11-11 at 17 15 56](https://user-images.githubusercontent.com/44360321/98840710-6d4d6a00-2447-11eb-89af-e225aefd23ca.png)

**Comment by tw15egan** [comment]
Hey there @matias-quezada! That does seem odd... Seems like this is an issue with the defined types for typescript. We don't maintain the typings so I'm wondering if an update needs to be made on that end? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react

**Comment by matias-quezada** [comment]
Thanks for your time, I'll contact DefinitelyTyped team to see what can we do with this 👍
