### ISSUE TITLE
[component audit] data table bug v2 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7283]
- [x] **Toolbar**: Set overflow menu to use `light` variant. Similar to what we changed with [rows](https://github.com/carbon-design-system/carbon/issues/7219#issuecomment-724304479) 
- [x] **Expansion**: in the expanded panel the left padding should be `48px` instead of 52px to align to type.
![image](https://user-images.githubusercontent.com/11670886/98994456-739a1f80-24f5-11eb-8664-62aa680a231a.png)
- [x] **Expansion**: focus on chevron should be 2px not 1px
![image](https://user-images.githubusercontent.com/11670886/98994716-da1f3d80-24f5-11eb-914e-878d46c18d84.png)
- [x] **Filtering**: there is a [filter story](https://react.carbondesignsystem.com/?path=/story/datatable-filtering--usage) in storybook but I'm not seeing any filtering happening

**Comment by tw15egan** [comment]
@aagonzales I'm able to filter in Chrome, is this not working in a different browser?  

![filter](https://user-images.githubusercontent.com/11928039/99007614-6b43e380-24f9-11eb-837f-2031ae33bcf2.gif)

**Comment by aagonzales** [comment]
ooo I thought it was supposed to be some sort of filter selection under the settings gear. I didnt release it was "search as filter"
