### ISSUE TITLE
Add ability to not import any icons

### ISSUE THREAD

**Issue by theskillwithin** [carbon-design-system/carbon#7286]
Would very much like a feature where I can disable loading any icons.  my gatsbyjs project is loading all the icons in a way that takes up 80% of the loaded bundles.

However we are not using any of these Icons, so a way to disable importing them would help me

**Comment by joshblack** [comment]
Hi there @theskillwithin! 👋 

The icons should be tree-shaken when not used by your project. Most likely there is some kind of usage happening that is causing this behavior to deopt and include all the icons. If you can provide some steps to reproduce where the icons are included in the bundle I would be happy to help out with debugging!

**Comment by theskillwithin** [comment]
@joshblack thank you, i changed from importing from lib folder to es folder.  problem sovled!!!!!
