### ISSUE TITLE
Angular JS 1.8.x & Carbon

### ISSUE THREAD

**Issue by sbodese** [carbon-design-system/carbon#7289]
## Summary
Is AngularJS 1.8.x actual working with the carbom js lib? 
## Relevant information
Hi Folks, im only interested on this question that AngularJs 1.8. is working fine with -and supports- the whole carbon design features ? 

Thanks and Greetings

Steve

**Comment by tw15egan** [comment]
Hey there @sbodese! I'd recommend checking out https://github.com/IBM/carbon-components-angular. They should be able to answer your questions in regards to which specific versions of Angular Carbon is compatible with. Hope this helps!
