### ISSUE TITLE
Should improve carbon compilation time

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#7294]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

There were several issues related to build/compile time problems

- https://github.com/carbon-design-system/carbon/issues/3348
- https://github.com/carbon-design-system/carbon/issues/6198

I don't know why they were closed, anyway it is very serious problem. Therefore, I hope **this issue should not be closed until problem is totally solved.**

From above issues, suggested solutions don't work

- **[Use fast-sass-loader](https://github.com/carbon-design-system/carbon/issues/6198#issuecomment-648408615)** : it causes lots of compilation problems and it is [wrong implementation](https://github.com/webpack-contrib/sass-loader/issues/848#issuecomment-636805292)
- **[Use only-needed style files following guide](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/sass.md#optimizing-your-sass-builds)** : What if I have to use almost all files? and how can I know exactly what files I have to use...when I import files which only I use, time to take was almost same.

Is there other ways to solve compilation time? If not, plz consider it as higher priority. Moreover, if someone uses `dart-sass` as sass compilation implementation, it becomes slower than now. Thanks. Every comments to solve this issue will be helpful to many people.

**Comment by joshblack** [comment]
Hi there @baeharam! 👋 

Unfortunately, there isn't much that we can do for this problem until our next major release (we just announced this [last week](https://medium.com/carbondesign/whats-coming-to-carbon-in-2021-39a4c7d1762a)). Changes that we would look to make would be a breaking change for those who are already using the system 😞 

As you noted, our recommendation in most cases has been to use `fast-sass-loader`, at least for development. We use it in our storybook development environment for the components. Definitely get what you mean though in that it's not a perfect solution. This is where including only what you need, or separating our "vendor" styles from "application" styles has been helpful for teams to figure out how to avoid recompilations of Carbon's sass files.

For context, when we profiled this problem earlier we found that `node-sass` tends to give reasonable compile times when used directly (although it's far from ideal) at around ~4-5s depending on the machine. Here's a quick measurement from my machine for compiling all the package styles:

```bash
npx node-sass src/globals/scss/styles.scss output.css  4.69s user 0.23s system 100% cpu 4.879 total
```

As a result, the slow down appears to exist over in `sass-loader` but it could also totally be another part of the bundle pipeline for applications.

What we can do in the interim is help you out if you can provide a minimal reproduction of the slowdown that you're experiencing and offer advice for how to minimize it. We definitely understand how disruptive this can be, especially when compile times shoot upwards of a minute, and want to help out here in anyway that we can.

**Comment by baeharam** [comment]
@joshblack Thanks for your answer! 😄 

1) `fast-sass-loader` is not helpful to our development.
2) I know that `sass-loader` is bottleneck for speed issue, but there is no way to improve this till now.
3) Before reproduction, how can I know which sass files have to be needed for specific react component? For example, if I need `<TextInput />` component, I thought that I only need `carbon-components/scss/components/TextInput/TextInput.scss`. But, it doesn't work correctly and cannot know what other files/flags should be included.(like below codes)

```scss
// Your entrypoint for including sass files from Carbon
$css--font-face: true;
$css--helpers: true;
$css--body: true;
$css--use-layer: true;
$css--reset: true;
$css--default-type: true;
$css--plex: true;

// Include defaults typically provided through the `styles.scss` entrypoint
@import 'carbon-components/scss/globals/scss/_css--reset.scss';
@import 'carbon-components/scss/globals/scss/_css--font-face.scss';
@import 'carbon-components/scss/globals/scss/_css--helpers.scss';
@import 'carbon-components/scss/globals/scss/_css--body.scss';
```

In the perspective of user which uses Carbon, I don't know what is `$css-body` or `_css-font-face.scss` etc. I think docs should explain what file is needed for specific cases. Because of this lacking, I cannot import specific files that only I need, but I have to import global scss file which is the cause of compilation time issue.

I hope you have clean instruction for this problem!

**Comment by joshblack** [comment]
> In the perspective of user which uses Carbon, I don't know what is $css-body or _css-font-face.scss etc

Great point! Most of the relevant ones should be detailed over in: https://github.com/carbon-design-system/carbon/blob/master/docs/guides/sass.md#global-flags if you find one missing definitely let me know and I can help out!

>  I thought that I only need carbon-components/scss/components/TextInput/TextInput.scss

This is surprisingly the reasoning behind how the project was structured and why things have gotten slower over time, unfortunately 😞  The hope was to make this possible (one import would bring in everything you needed without duplication) but unfortunately that doesn't work out the way that you expect.

In general, this structure should get you where you need to go:

```scss
//-------------------------
//  Global
//-------------------------

$css--font-face: true;
$css--helpers: true;
$css--body: true;
$css--reset: true;
$css--default-type: true;
$css--plex: true;

@import '~carbon-components/scss/globals/scss/theme';

// Set your theme (if different than carbon--theme--white)
$carbon--theme: $carbon--theme--g10;
@include carbon--theme();

@import '~carbon-components/scss/globals/scss/feature-flags';
@import '~carbon-components/scss/globals/scss/vars';
@import '~carbon-components/scss/globals/scss/colors';
@import '~carbon-components/scss/globals/scss/mixins';
@import '~carbon-components/scss/globals/scss/layout';
@import '~carbon-components/scss/globals/scss/layer';
@import '~carbon-components/scss/globals/scss/spacing';
@import '~carbon-components/scss/globals/scss/typography';
@import '~carbon-components/scss/globals/scss/css--reset';
@import '~carbon-components/scss/globals/scss/css--font-face';
@import '~carbon-components/scss/globals/scss/css--helpers';
@import '~carbon-components/scss/globals/scss/css--body';
@import '~carbon-components/scss/globals/grid/grid';

//-------------------------
// Components
//-------------------------

@import '~carbon-components/scss/components/button/button';
// ...
```

Hope this helps!

**Comment by baeharam** [comment]
@joshblack The conclusion is that I have to `@import` almost every files. 🤔  I understood. But, I found that there are way to speed up by compiling first.

By above explanation, anyone who use Carbon should import global scss file which includes every utils/components style files. Therefore, it is big bottleneck of compilation when `sass-loader` loads. If `index.scss` import global scss file, I can compile it first by `node-sass` which is much faster than `sass-loader`. Then, it will be faster by importing output css file.

Conclusion, someone who are looking for to speed up compilation time can use this strategy.

1) First, compile `index.scss` which includes global scss file into `index.css` by `node-sass`.
2) If `App.tsx` import `index.scss`, change it into `index.css`.
3) Then compile it by `yarn start` or `yarn build`.

It depends on Carbon version and your overriding styles, but it is only way to speed up until now. I hope it could be helpful to someone.

**Comment by hungdev** [comment]
Thank @baeharam  for the idea.
run: 
`npx node-sass ./node_modules/carbon-components/scss/globals/scss/styles.scss output.css`
and import `output.css` to App.js
re-run!
