### ISSUE TITLE
Masthead and Footer content not getting translated.

### ISSUE THREAD

**Issue by sabhareesan** [carbon-design-system/carbon#7300]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
By changing the locale in the LocaleModel component, the Masthead and Footer content is not getting translated.

> Is this issue related to a specific component?
Locale Model

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The content in the Masthead and Footer needs to be translated when the locale is changed in the Locale Model component 

> What browser are you working in?
FireFox, Chrome, Safari

> What version of the Carbon Design System are you using?
"@carbon/ibmdotcom-react": "^1.12.0"
"carbon-components": "^10.23.2"
"carbon-components-react": "^7.23.2"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Application: IBMid Profile UI (already in Production)
https://www.ibm.com/ibmweb/myibm/profile

## Steps to reproduce the issue
1. Open ProfileUI Page in Firefox (https://www.ibm.com/ibmweb/myibm/profile)
2. Change the locale in Locale Model component

## Additional information

screenshot from the Profile UI page 
![image](https://user-images.githubusercontent.com/23634668/99386861-16d5a500-28f9-11eb-8f12-a8769319e3a8.png)

**Comment by sabhareesan** [comment]
This issue is related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom repo, can some one help me in transferring this issue.

**Comment by ljcarot** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-dotcom #4505](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4505) via [**ZenHub**](https://www.zenhub.com/)
