### ISSUE TITLE
'headers' prop in DataTableSkeleton component is not working

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#7302]
According to the [DataTableSkeleton ](https://react.carbondesignsystem.com/?path=/docs/datatableskeleton--default) docs, the `headers` prop should specify the displayed headers. But whatever I pass to the prop doesn't change what's being rendered.

> Is this issue related to a specific component?

- DataTableSkeleton 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The DataTableSkeleton should show the specified headers.

> What browser are you working in?

- Chrome `86.0.4240.198 (Official Build) (64-bit)`

## Steps to reproduce the issue

- https://codesandbox.io/s/datatable-skeleton-headers-bug-8mifu?file=/src/index.js

**Comment by dakahn** [comment]
seeing them not working as expected on our Storybook as well
https://react.carbondesignsystem.com/?path=/story/datatableskeleton--default
