### ISSUE TITLE
Bug: @carbon/icons-vue doesn't work with Vue 3

### ISSUE THREAD

**Issue by TimonLukas** [carbon-design-system/carbon#7310]
## What package(s) are you using?
- [x] `@carbon/icons-vue`

## Detailed description

> Describe in detail the issue you're having.
Importing an icon from `@carbon/icons-vue` and adding it to a template in a project using Vue 3 results in the following error message: 
![image](https://user-images.githubusercontent.com/18093957/99520527-7f716000-2993-11eb-8295-a1ce8d15ec2b.png)

> What version of the Carbon Design System are you using?
`@carbon/icons-vue` is 10.21.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Absolutely not pressing.

## Steps to reproduce the issue

1. Generate a new Vue project using `@vue/cli`, and choose Vue 3 as the version.
2. Install `@carbon/icons-vue` into the newly created project, import an icon and add it to a template.

## Additional information

I believe that this is caused by the [removal of the `functional: true` SFC option](https://v3.vuejs.org/guide/migration/functional-components.html#overview), which is used [in the builder](https://github.com/carbon-design-system/carbon/blob/master/packages/icon-build-helpers/src/builders/vue.js#L135).

**Comment by tw15egan** [comment]
@lee-chase, can we simply remove this line from the builder?

https://github.com/carbon-design-system/carbon/blob/master/packages/icon-build-helpers/src/builders/vue.js#L135

**Comment by TimonLukas** [comment]
I think that won't work, the implementation of functional components [changed more deeply than that](https://v3.vuejs.org/guide/migration/functional-components.html#overview). Something that might work would be to conditionally export either the current component definition if Vue 2 is used, and if it's Vue 3 instead export a function that takes over attributes like props from the Vue 2-defined component and wraps the render function. Something like this:

```javascript
import Vue from 'vue';

const definition = {
  name: '${moduleName}',
  functional: true,
  props: ['title'],
  render(createElement, context) {
    // render code
  },
};

if (Vue.version.startsWith('2')) {
  export default definition;
} else {
  import { h } from 'vue';
  const IconComponent = (props, context) => definition.render(h, { ...context, props });
  for (const key in definition) {
    if (!['functional', 'render'].includes(key)) {
      IconComponent[key] = definition[key];
    }
  }
  export default IconComponent;
}
```

It is possible that this will not work quite that easily, as the [VNode props format](https://v3.vuejs.org/guide/migration/render-function-api.html#vnode-props-format) for the `h` function changed as well. But even for that it should be relatively easy to write a conversion function.

**Comment by lee-chase** [comment]
I believe functional components have gone away in Vue 3, largely because the performance gained in using them became negligible. 

I like our approach Timon but would need to find time to analyze this. Things that need verifying include:
- staticClass and class are applied correctly
- styles are merged with the default
- listeners work

**Comment by lee-chase** [comment]
I think the above PR works @TimonLukas @tw15egan.

I have tested building locally but it would be nice to get a second opinion perhaps when there is a build @TimonLukas and I can install.
