### ISSUE TITLE
[dropdown] component audit bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7325]
Assorted bugs that were found from the component audit for dropdown, combobox and mutli-select.

## Dropdown
- [x] **Light prop:** `hover-light-ui` color token needs to be used for the hover states.
- [ ] **Warning state:** warning icon needs a `black` inner fill for all themes.
- [ ] **Invalid state:** alert icon needs a `black` inner fill for dark themes.
- [x] **Inline variant:** is not available to interact with in the playground story. 

## Combobox
- [x] **Light prop:** `hover-light-ui` color token needs to be used for the hover states of the options in the menu.
- [ ] **Warning state:** there is currently no warning state for combobox, but it should be added.
- [ ] **Invalid state:** alert icon needs a `black` inner fill for dark themes.
- [x] The top input field should not have a hover color change, only a cursor change to type.
- [x] The close icon should be `icon-01`.

## Multi-select
- [x] **Light prop:** `hover-light-ui` color token needs to be used for the hover states.
- [ ] **Warning state:** warning icon needs a `black` inner fill for all themes.
- [ ] **Invalid state:** alert icon needs a `black` inner fill for dark themes.
- [x] The entire tag right now is clickable which clear the selection. Only the close icon in the tag should clear the items selected.
- [x] Tag hover color for the close icon needs to be `inverse-hover-ui` color token.
- [x] Tag focus border needs to be around the close icon, not the entire tag. The focus color should be `inverse-focus-ui` color token.

**Comment by tw15egan** [comment]
Seems like the outstanding issues are resolved with https://github.com/carbon-design-system/carbon/pull/8092
