### ISSUE TITLE
fix[accordion]: nested Accordions not working as expected

### ISSUE THREAD

**Issue by jpbyrne** [carbon-design-system/carbon#7328]
# fix[accordion]: nested Accordions not working as expected

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Vanilla Carbon Accordions are not functional when placed inside of another Accordion. Nested Accordions do not expand and collapse.

> Is this issue related to a specific component?

Yes. Accordion.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

That Carbon Accordions can be placed one within another and function normally.

> What browser are you working in?

Chromium Edge (but applicable to all!)

> What version of the Carbon Design System are you using?

v10.24.0 (latest)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Social Program Management

## Steps to reproduce the issue

1. Update `carbon/packages/components/src/components/accordion/accordion.hbs` to include one Accordion component within another.
2. Run `yarn dev`.
3. Navigate to `http://localhost:3000/demo/accordion`.
4. Observe that nested Accordions.

## Additional information
| Example of current behaviour |
|-|
| ![nested-accordion-example](https://user-images.githubusercontent.com/2652501/99810229-57246580-2b3b-11eb-96c3-ec9c4f547353.gif) |

**Comment by dakahn** [comment]
Changed this to a proposal instead of a bug report since this feature is specifically unsupported by our system.

@aagonzales I know when nested accordions have come up in the past we've decided against support for this feature. With a Carbon Treeview coming soon I assume that's still the case. I don't actually know if a Vanilla Treeview implementation is being worked on in parallel to the React though.

**Comment by aagonzales** [comment]
@jpbyrne Can you share a screenshot of design that uses the nested accordion for context please.

**Comment by jpbyrne** [comment]
Sure thing @aagonzales.

In SPM we have a UI templating system called UIM which our customers use to build custom interfaces. We're currently in the process of migrating the output of UIM to Carbon components.

| ![image](https://user-images.githubusercontent.com/2652501/99947984-a99a9780-2d70-11eb-8660-8f5995a09b79.png) |
|-|

Customers use something called a UIM `CLUSTER` element to create multi-column layouts. The default variant of Cluster comes with a collapsible header. We were planning to reimplement our Cluster using Carbon grid and Accordion components.

| <img width="1110" alt="Screenshot 2020-11-23 at 09 13 33" src="https://user-images.githubusercontent.com/2652501/99948873-0cd8f980-2d72-11eb-90bd-dd3e47a381e8.png"> |
|-|

However, as it's possible to nest Cluster elements one inside another, Accordions would also need to support this capability for use to use them in this way.

**Comment by vpicone** [comment]
Going to close this one out for inactivity. This is really challenging for user's content discoverability and accessibility. We recommend flattening your information architecture as much as possible.
