### ISSUE TITLE
FileUploader: Default selection shows files with other extension than listed in accepted types

### ISSUE THREAD

**Issue by miriam-g** [carbon-design-system/carbon#7339]
## What package(s) are you using?
- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description
The FileUploader of carbon-components-react provides a property called "accepted". On Windows it works fine, but on Mac it shows also files with other extensions: if "zip" is included in the list of accepted file types, I can also choose "pptx" and "docx" files.

I expect to just get the accepted files selectable.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Carbon X
carbon-components": "10.21.0"
carbon-components-react": "7.21.0"

## Additional information

![image](https://user-images.githubusercontent.com/29945789/100102695-412ce280-2e64-11eb-869a-856817c7348b.png)

These are the accepted file types:
`const acceptedFiles = ['.zip', '.bpmn', '.xml'];`

## How to reproduce

To reproduce this issue you can go to
https://react.carbondesignsystem.com/?path=/story/fileuploader--drag-and-drop-upload-container-example-application
add, ".zip" to the accepted file extensions and click on "Drag and drop files here or click to upload". 
Browse to a folder that contains pptx or docx files.

**Comment by dakahn** [comment]
it shows unsupported files but when they're selected the user gets an error
![image](https://user-images.githubusercontent.com/40970507/100948578-c603a600-34cd-11eb-8b78-8110fc1520f2.png)

is this an enhancement proposal to have this component filter unsupported files in some way?

**Comment by miriam-g** [comment]
My understanding is that this is what the property "accept" is for:
From carbon documentation: _"Accepted MIME types or file extensions (accept)"_
And I see that all other unsupported files are greyed out.

**Comment by dakahn** [comment]
I think we're saying that if the selected file matches the accepted filetype an error wont be thrown. Is there something i'm missing here @joshblack

**Comment by dakahn** [comment]
Closing this up as resolved. Let me know if I'm missing something and I can reopen.
