### ISSUE TITLE
Bug - Checkbox component loading skeleton appears to be static

### ISSUE THREAD

**Issue by SharonOBoyle** [carbon-design-system/carbon#7348]
### Affected component:
https://ibm-security.carbondesignsystem.com/?path=/story/components-checkbox–skeleton

We inherit the skeleton styling directly from Carbon. It appears to be the same color across all components for the Gray 100 theme.

### Expected behavior -
Clearly see the skeleton loading when page is being loaded

### Actual behavior -
Contrast on the skeleton component is not enough, so that you can only tell it is loading after zooming in multiple times

### Steps for reproducing

1. View the component here: https://ibm-security.carbondesignsystem.com/?path=/story/components-checkbox–skeleton
2. Check does it look like it's actually loading dynamically when you refresh the brower page

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/39183672/100452630-711cf580-30b1-11eb-9128-28c3c83ceba9.png">

**Comment by tw15egan** [comment]
cc @carbon-design-system/design we may need to look into changing the `$skeleton-01` and `$skeleton-02` loading colors on dark themes

Can change theme [here](https://deploy-preview-7229--carbon-components-react.netlify.app/?path=/story/checkbox--skeleton) to see an example

**Comment by laurenmrice** [comment]
Yes, agreed. We have an open design issue ([3335](https://github.com/carbon-design-system/carbon/issues/3335)) to investigate skeleton tokens.

**Comment by laurenmrice** [comment]
Yes, agreed. We have an open design issue ([3335](https://github.com/carbon-design-system/carbon/issues/3335)) to investigate skeleton tokens.

**Comment by tw15egan** [comment]
Will be fixed via #7699
