### ISSUE TITLE
UX/Visual: Input error validation placement redesign

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon#736]
## Detailed description
_*UX/Visual question*_

When validation is triggered form input error messages are currently rendered below the input field where the error occurred. In areas where there is not enough space to accommodate this added element you get a jump in the layout. 

![image](https://user-images.githubusercontent.com/1590966/39379490-06f7d3ce-4a21-11e8-8cbd-dbe7a0407e3f.png)

This seems to be a common issue/annoyance for consumers as some people have been asking for guidance on how to deal with this layout jump. I wanted to share my team's solution which has been to absolutely position the error message to the top and then translate up 100% to deal with different lengths of message. Super long messages are still handled but not ideal. Feedback on whether this is an acceptable pattern and whether any improvements could be thought of would be appreciated. 

> Proposed solution

![image](https://user-images.githubusercontent.com/1590966/39379471-f5c791de-4a20-11e8-8544-1d89cb505abc.png)

![image](https://user-images.githubusercontent.com/1590966/39380260-889e2fca-4a23-11e8-84cc-6f3d17ad9268.png)

> Is this issue related to a specific component? 

Form Inputs

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

latest

## Add labels
Visual

**Comment by joshblack** [comment]
cc @carbon-design-system/design if you all have any input/typical guidance for these kinds of discussions!

**Comment by aagonzales** [comment]
So we ran into a similar issue when doing inline edit in a data table. This is the solution we came up with:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/11670886/39947175-8e828ad0-5536-11e8-8c7e-2a8ca4cd7071.png">

The error icon is always there but the validation message "tooltip" only appears on field focus or when the user hover/focuses on the error icon. Also not the greatest solution since you have to focus to see the message and its hidden on focus-off.

**Comment by davidicus** [comment]
That is interesting. I like this approach. Only being visible on focus would probably be an issue in certain uses cases. I do like the flexibility to allow for larger error messages.

**Comment by tw15egan** [comment]
I'm going to close this simply because work on inline data-table editing has been halted, and the jumping should be solved with the new input fields. We can reopen this if this becomes a more pressing need
