### ISSUE TITLE
Create a cli command for scaffolding out components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7360]
This issue falls under [this KR](https://app.zenhub.com/workspaces/okrs-5eef636e504e9d001694ba22/issues/carbon-design-system/okrs/93)

We would like to add a new command to `@carbon/cli` that our team, and others at IBM, could use to scaffold out a component. This scaffold should include a minimal set of conventions that we encourage for teams authoring components, in particular the folder scheme and test conventions.

In addition to generate a standalone folder as an option, this command should include a `--lib` option (or similarly named) for scaffolding out a component package. This option should be configurable for the following conventions:

- Testing (Jest)
- Building (Rollup)
- Development (Storybook)
- Linting (ESLint, StyleLint)
- Commit hooks

**Comment by mattrosno** [comment]
@joshblack if a component package, can we also include a `carbon` object in the package.json? If a component folder, would that be a carbon.json or something? What goes in there? Not sure... but eventually information that would replace component index YML files? E.g. https://github.com/carbon-design-system/carbon-website/blob/master/src/data/index/dot-com/callout-media.yml

The `carbon` config would allow component maintainers to self-document that component's "completeness" (e.g. status, if it's the canonical implementation, how accessible it is, who maintains, etc. Anything of value that would help a user understand the component's history and if it's the right component for their "job".)

Some related concepts:

* From https://github.com/carbon-design-system/carbon-spec/pull/13, possible component status definitions: https://github.com/carbon-design-system/carbon-spec/blob/ffea894324da8f3a993319e98a4bd652e8145a15/docs/component-status.md#legend

**Comment by mattrosno** [comment]
As for the folder scheme, we've discussed that containing specific markdown files (or structured data somehow) to codify component / pattern templates to assist documentation standardization across the ecosystem.

* https://www.carbondesignsystem.com/contributing/component
* https://www.carbondesignsystem.com/contributing/pattern#how-to-write-a-pattern

**Comment by joshblack** [comment]
@mattrosno definitely could add that metadata and include it baked-in, makes a lot of sense to me 👍
