### ISSUE TITLE
Enhancement for page selector of Pagination

### ISSUE THREAD

**Issue by kaushalnavneet** [carbon-design-system/carbon#7378]
The existing page input selector looks a little odd - "1 ↓ (dropdown) Page 1":

![Screen Shot 2020-12-01 at 2 14 19 PM](https://user-images.githubusercontent.com/44249850/100786041-8e1e3500-33df-11eb-8284-d79ca52eaba5.png)

It would be a great enhancement if we can show the dropdown to the right of "Page", instead of showing the "1" twice. (It may also be confusing for people with cognitive issues)

something like this-

![Screen Shot 2020-11-26 at 11 55 56 AM](https://media.github.ibm.com/user/277955/files/b45a6400-2fde-11eb-8aa4-3b9cb1e9d306)

What is expected from this feature request? =>
**If there is more than one page, it should show "Page 1↓ of [n]". And, if there is only 1 page, it's better to hide the page input selector.**

**Comment by tay1orjones** [comment]
Hey @kaushalnavneet! The default text provided after the dropdown attempts to meet this need and clearly state the current page alongside the total number of pages. 

![image](https://user-images.githubusercontent.com/3360588/134947643-e0f6d434-d0f1-401f-bcc8-5ec6a509d4c8.png)

Have you come across some users that couldn't use the control in it's default state, or found it confusing? We'd be interested to see any research research you can provide to guide how we could tackle this.
