### ISSUE TITLE
Using a newer version of Gridish for experimental grid.

### ISSUE THREAD

**Issue by j1mie** [carbon-design-system/carbon#738]
Some class names have been added, removed or changed in [CSS Gridish](https://github.com/IBM/css-gridish/), from when you guys added it behind an experimental flag.

I'd be happy to open a PR with a more recent version of Gridish, using your values. Would you guys consider generating the grid as part of your build process, or would that be a little overkill?

**Comment by joshblack** [comment]
@j1mie definitely would want to generate it as part of our build process! The only thing is that the project generates more files than we need, would be helpful to support: https://github.com/IBM/css-gridish/issues/20

**Comment by j1mie** [comment]
@joshblack Was thinking this too - although generated markdown and sketch files look like they'd be excluded from being published to NPM with your current file settings. 

Our team is hoping to use CSS Gridish going forward so I could help with IBM/css-gridish#20

**Comment by shinytoyrobots** [comment]
Closing as this is really a question / enhancement within the gridish repo.
