### ISSUE TITLE
Is it possible to add a bootstrap to Carbon Modal to be Draggable and Resizable?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#7386]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
Need to make the Modal draggable and resizable

## Relevant information
Like in:
https://www.npmjs.com/package/react-modal-resizable-draggable#demo
http://jsfiddle.net/iamakshay04/xmrxbL9f/

**Comment by tw15egan** [comment]
There's nothing built into the component to handle dragging/resizing, so you'll have to find an eternal package to handle this for you

**Comment by zbeedatm** [comment]
Hi,
I used the [react-draggable](https://www.npmjs.com/package/react-draggable) component on top of ComposedModal and it worked fine, expect of the gray background that was moving within the modal, so I changed it to transparent via css:

`.bx--modal.is-visible {
    background-color: transparent;
}`

Will be thankful if you can give a tip how to keep the gray background while dragging the modal, this symptom doesn't happen when using other component for example:
https://www.npmjs.com/package/drag-modal

**Comment by tw15egan** [comment]
The draggable element should be `bx--modal-container` not `bx--modal`, which should resolve that issue. Glad you've got it working!
