### ISSUE TITLE
AccordionItem passes any object title into button component

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#7391]
I noticed the AccordionItem uses it's title prop as a child in a div element and can be anything. In some code we had, we passed in html as the title prop and this worked fine since it just became a child element within the div as shown here. 

https://github.com/carbon-design-system/carbon/blob/0797f3112f8a97636d05d81a3457482884364528/packages/react/src/components/Accordion/AccordionItem.js#L86

however, we noticed when hovering over the AccordionItem, it said [Object object]. Inspecting the html, there was a button component that had a title set to [Object object]. I looked at the source and noticed the props also get passed into a button component here 

https://github.com/carbon-design-system/carbon/blob/0797f3112f8a97636d05d81a3457482884364528/packages/react/src/components/Accordion/AccordionItem.js#L18

So it looks like the title for the AccordionItem could be any object, but it also gets used in the button which has to be a string. 

Not sure if this was a defect, by design, but thought I would post it.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by TannerS** [comment]
> can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

So i am trying to do so, in our local code data base, the behavior happens, we do use an older version of the react components for carbon. But, when doing a test run with the sand box above i can't re-create it, even though I think l the source code that I am looking at in master should be doing what i saw happen in our code base. I am not sure, let me keep poking at it

**Comment by emyarod** [comment]
yeah I figured it would be related to an older version of Carbon since this doesn't seem to be present in the current version of the library

**Comment by TannerS** [comment]
@emyarod  yup! that was my bad, it was an old version which I re-created here 

https://codesandbox.io/s/modern-sun-6hce5

but this was fixed, i will go a head and close this!
