### ISSUE TITLE
[NumberInput] Label doesn't get the disabled class when the rest of the component does

### ISSUE THREAD

**Issue by SrfHead** [carbon-design-system/carbon#7398]
When a NumberInput component is disabled, the label still shows with regular styling

- [ ] `carbon-components`
- [x] `carbon-components-react`

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging? this is not present in the storybook
