### ISSUE TITLE
Code for icons in Step-1 and Step-4 of Tutorial are incorrect and the code checking bot is flagging the correct code as an error.

### ISSUE THREAD

**Issue by tylerw8** [carbon-design-system/carbon#7407]
I already mentioned this in the tutorial slack channel.  The React tutorial has a mistake in the code for the icons in step 1 and step 4.  The screen shots below show the code from the tutorial commented out and the correct code below it.  The tutorial works with the fixed code and doesn't with the code from the tutorial, but when this code is submitted to be checked the bots flag the correction as a mistake.  Both the tutorial and the code checker bot needs updating.  Thanks!

![Screen Shot 2020-12-04 at 11 17 15 AM](https://user-images.githubusercontent.com/9169939/101228014-bd86a900-364e-11eb-89a6-4dd34eb63320.png)

![Screen Shot 2020-12-04 at 4 02 24 PM](https://user-images.githubusercontent.com/9169939/101227997-b069ba00-364e-11eb-9303-dfdb066decc8.png)

**Comment by tw15egan** [comment]
Hey @tylerw8 , thanks for reporting this!

The syntax below is actually correct, but we have a problem in the tutorial where the dependencies get out of sync between steps. [Here's an example](https://codesandbox.io/s/wizardly-darkness-ye6n3?file=/src/index.js) of them working correctly.

```js
import {
  AppSwitcher20,
  Notification20,
  UserAvatar20,
} from '@carbon/icons-react';
```

I'm currently working on updating all the tutorial steps to use the latest versions, as well as pinning the packages at the current version so these inconsistencies are less likely to occur.

For now, using your syntax above will get them to work, but you can also try running `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install` to see if you can get the packages in sync.

**Comment by tylerw8** [comment]
Hi TJ,
Can you mark my Step 4 as correct so I can get the badge?
Thanks!
Tyler

**Comment by tw15egan** [comment]
@tylerw8 Will take a look now 👍

**Comment by tw15egan** [comment]
Seems to be resolved by deleting the `lockfile` and running `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install`
