### ISSUE TITLE
Matrix icon missing.

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/carbon#7419]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon/icons-react`

## Detailed description

The PR, https://github.com/carbon-design-system/carbon/pull/5425, deprecated the research--matrix icon with the reason was that it was a duplicate of Matrix, however, this icon is not available in carbon-icons-react.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

For Matrix to be available.

https://codesandbox.io/s/thirsty-grothendieck-z0cd5?file=/src/index.js

**Comment by joshblack** [comment]
Hi there, @richardpilot! 👋  Are you potentially looking for `QMatrix16` versus `Matrix16`? That may be the source of the confusion, as the matrix.svg is under the `Q` namespace: https://github.com/carbon-design-system/carbon/blob/master/packages/icons/src/svg/32/Q/matrix.svg

Hope this helps!

**Comment by tw15egan** [comment]
Closing as resolved 👍
