### ISSUE TITLE
How to access user selected rows in Carbon Data Table

### ISSUE THREAD

**Issue by dhebert-dev** [carbon-design-system/carbon#7428]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I am using a Carbon Data Table in my React project and I need the user to be able to select a row and download the data from that row into an excel file. I am using BatchActionToolbar but how do I access the specific rows that the user selected? I noticed that the BatchActionToolbar renders the number of rows selected so I have been digging around there to try and figure out how to access the data that the user selected. 

## Relevant information
Using Data Table and BatchActionToolbar
Also I want to note that we are attempting to have a download feature purely built from the front end with no backend involvement.

**Comment by emyarod** [comment]
most likely you would need to implement this with a custom state manager rather than relying on the default `DataTable` (https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager)

**Comment by dhebert-dev** [comment]
Thank you for the information. This helps a lot.

**Comment by tw15egan** [comment]
Going to close this as resolved, but feel free to leave another message if you need us to reopen! 👍
