### ISSUE TITLE
hidden attribute should not be used to hide content

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#743]
## Detailed description

The use of hidden to hide content in a tabbed dialog is specifically called out in the spec as a case where hidden should not be used. This is in part because it is a weak attribute that can be overridden in css by display: flex for instance.

https://www.w3.org/TR/2011/WD-html5-20110525/editing.html#the-hidden-attribute

> Is this issue related to a specific component? 

The content-switcher

> What did you expect to happen? What happened instead? What would you like to see changed?

If the content should be hidden then a class e.g. 'bx--contnet--hidden' should be used to remove or hide the content.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 
8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment]
Great to see how this discussion goes: https://twitter.com/schofeld/status/990319497482563585

**Comment by tw15egan** [comment]
We do not provide any styling for the `hidden` container, but merely add the hidden tag via js through the `data-target` attribute. If a style rule overriding [hidden] is in the application (non-Carbon code), the fixing the problem is the responsibility of the application.
