### ISSUE TITLE
Pagination not displaying as expected

### ISSUE THREAD

**Issue by bradbooth** [carbon-design-system/carbon#7444]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description
On carbon-components `^10.24.0` onwards, Pagination component looks like
![image](https://user-images.githubusercontent.com/16762848/101919175-41cdb480-3b98-11eb-8e1a-55bb5346347e.png)

The same component on `10.24.0` looks like
![image](https://user-images.githubusercontent.com/16762848/101919392-7fcad880-3b98-11eb-913d-002ffa81b8b2.png)
which is expected.

## Steps to reproduce the issue

CodeSandBox - https://codesandbox.io/s/carbon-components-angular-forked-e1ysg?file=/package.json

Steps to reproduce:
1. Set `"carbon-components"` version to `"^10.24.0"` -> issue is there
2. Set `"carbon-components"` version to `"10.24.0"` -> issue isn't there

**Comment by emyarod** [comment]
this should be resolved in https://github.com/carbon-design-system/carbon/pull/7427
