### ISSUE TITLE
[file uploader] component audit bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7448]
## General fixes

**Content**
- [x] Header and description of the component should say the following:
![copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/323a1b6e-53b9-4f54-99cc-4b441cbaf3cd)
----
**File focus state**
- [x] Can we make the focus around the close focus border `24px`?
![focus](https://user-images.githubusercontent.com/43969356/101954498-d6004180-3bc1-11eb-8bc7-217a544aa679.png)
----
**File invalid state**

- [x] There is a slight shift down of the file label when the invalid state is applied.
![error](https://user-images.githubusercontent.com/43969356/101954048-0dbab980-3bc1-11eb-9d2c-ff8a3b787350.gif)

- [x] Invalid state does not adjust with different heights of the file.
![error](https://user-images.githubusercontent.com/43969356/101955411-5a9f8f80-3bc3-11eb-939b-a2a16760c031.png)

- [x] Error message text should be `caption-01`.
- [ ] Alert icon needs a `black` inner fill for dark themes.

----

## File uploader button story
-Why do we have a `file uploader button` story? We do not want to encourage people to upload a file inside of a button container. Is this something we can deprecate?

## File uploader and File uploader item story
- [x] For the demo of this story, the width of the file should be 288px. Right now its changing dynamically based on the length of the word. People can edit the size of this if they want to on their end.
![size](https://user-images.githubusercontent.com/43969356/101955696-e6192080-3bc3-11eb-8951-3481de978889.png)

## Drag and drop container example application story

The disabled state is not correct.
- [x] The header and description need to be `disabled-02`.
- [x] The container needs to be `disabled-02`.

**Comment by emyarod** [comment]
>  Alert icon needs a `black` inner fill for dark themes.

for the black fill within alert icons on dark themes, we run into the same issue with notifications from before (https://github.com/carbon-design-system/carbon/issues/3216) except we're not able to force file uploaders to be on dark backgrounds. alternatively we can just apply the black fill across the board on all themes if that's fine

>  The container needs to be `disabled-02`.

can you clarify which container this is referring to?

**Comment by laurenmrice** [comment]
>  Alert icon needs a `black` inner fill for dark themes.

I will make a separate issue to figure out how to address the inner fill problems. (Since this could be a bigger issue than just file uploader) 👍🏻

>  The container needs to be `disabled-02`.

This is referring to the drag and drop dashed box. Currently the dashed box is very faint in color and is having a clicking glitch on disabled.

![Dec-17-2020 09-49-53](https://user-images.githubusercontent.com/43969356/102510510-55bc5f00-404d-11eb-9700-926ed57d209a.gif)


This is the spec of how it should be and how it will look across themes
![Artboard](https://user-images.githubusercontent.com/43969356/102510575-6371e480-404d-11eb-80ce-6202a86ea94a.png)
