### ISSUE TITLE
JAWS reads out "Type and text" for CodeSnippets

### ISSUE THREAD

**Issue by ashleylord8** [carbon-design-system/carbon#7454]
## Environment

> Operating system
Running Windows 10 VMware (on MacOS Catalina)

> Browser
Firefox

> Assistive technology used to verify
JAWS

## Detailed description

> What version of the Carbon Design System are you using?
"carbon-components": "^10.20.0",
"carbon-components-react": "^7.20.0",

> What did you expect to happen?
JAWS to NOT read out "type and text" when CodeSnippet is in focus.

> What happened instead?
With JAWS, CodeSnippets read out “Type and text” like other input fields, which I think is wrong since we’re not asking any the user to type anything here.

**Comment by alisonjoseph** [comment]
I wasn't able to replicate this in the latest version, and no defects were reported in our recent a11y audit by our QA team. Please re-open if we've missed something.
