### ISSUE TITLE
Loading indicator svg for batch actions

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#7459]
### Summary

Batch actions in the grid often take a few seconds.  I'd like a good way to indicate this.  If a put a Loading indicator above or below the grid, there is bounce in the UI when the action completes.  Instead, I'd like to show the loading indicator in the batch action toolbar.

I tried doing this and it basically does what I want, but the svg doesn't render nicely on the blue background.

![image](https://user-images.githubusercontent.com/30597411/102226179-17406c00-3eb6-11eb-83eb-496bd8f97fb0.png)

**Comment by emyarod** [comment]
are you able to use the InlineLoading component for this use case? can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by kglickman** [comment]
The InlineLoading component seems to use the same svg so I doubt it will help.  I will try to make a reduced test case soon.

**Comment by andreancardona** [comment]
@kglickman just wanted to follow up here on a potential sandbox to test this - thank you. :)

**Comment by kglickman** [comment]
I'm totally swamped right now.  It will have to wait a few weeks.

**Comment by kglickman** [comment]
This seems to be fixed in carbon-components-react: 7.28.2.  I had originally experienced it in 7.23.2.

**Comment by emyarod** [comment]
thanks for the update, it may have been resolved in https://github.com/carbon-design-system/carbon/pull/7447
