### ISSUE TITLE
Overflow menu danger class gets support token

### ISSUE THREAD

**Issue by DusanMilko** [carbon-design-system/carbon#7467]
In the overflow menu the danger class gets the support-01 token. When doing theming the danger and support-01 can potentially be different colors. It makes more sense to me for overflow menu danger class to get danger token instead of support-01.

On my team the colors in custom themes can sometimes be different between the tokens and from our perspective the danger menu options should inherit the danger token color.

![Screen Shot 2020-12-16 at 9 17 30 AM](https://user-images.githubusercontent.com/302239/102367561-88982180-3f7f-11eb-8282-ad0340ea4d73.png)

**Comment by tw15egan** [comment]
@laurenmrice in white/g10, `support01` and `danger01` are the same (`red60`)

However, in g90/g100 `support01` is `red40`/`red50` and danger01 is `red60`.

Currently, it is set to `support-01`. Can you confirm the color change is intentional when the overflow menu is used in a dark theme?

**Comment by laurenmrice** [comment]
The overflow menu danger option should be updated to use the `danger-01` token. It will be the same color across all themes. The support-01 token gets too light for the dark themes when paired with the usage of white text on top of it.

![danger](https://user-images.githubusercontent.com/43969356/102375560-47583f80-3f88-11eb-93da-54fb4a4e1390.png)
