### ISSUE TITLE
CSS stlying is not property for disabled select item in firefox

### ISSUE THREAD

**Issue by yaoterry** [carbon-design-system/carbon#7475]
firefix does not support to set the opacity for select item, https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/select/_select.scss#L164

it's not a grey out styling for the disabled select item in firefox.

https://stackoverflow.com/questions/58437806/why-wont-firefox-grey-out-my-disabled-select-options

**Comment by emyarod** [comment]
thanks for reporting! this seems to affect all browsers, and the component should no longer modify opacity for the disabled state

**Comment by nictownsend** [comment]
https://react.carbondesignsystem.com/?path=/story/components-select--default - If I view this in Firefox Mac - it is still not working. The CSS color overrides set on `bx--select-optgroup` and `bx--select-option` are stopping Firefox from rendering the default disabled value.

**Comment by nictownsend** [comment]
Or conversely, Chrome is ignoring the user overrides and applying the user agent
