### ISSUE TITLE
Inconsistent Modal scrolling behavior 

### ISSUE THREAD

**Issue by fangshih** [carbon-design-system/carbon#7479]
## The modal scrolling position is not reset when the user reopens the modal, and it only happens when the user sets the system text size to large.

- [X ] `carbon-components`
- [X ] `carbon-components-react`

## Detailed description

This behavior occurs with Windows and Mac both FF and Chrome. When the system text size changes to large, the scroll position is not reset. it seems like there is some inconsistent behavior. We would like to know if there is anything we can do to fix this. 

**Component**: Modal
**Browser**: Chrome, Firefox
**Theme**: Carbon 10
**Product name:** Data virtualization 

## Steps to reproduce the issue

Change the system resolution to large text > click the modal > scroll the content > close the modal > repone the modal  - the scroll bar is not reset to top 

**Component**: Modal
**Browser**: Chrome, Firefox
**Theme**: Carbon 10
**Product name:** Data virtualization 
**Component link**: 
https://www.carbondesignsystem.com/components/modal/code

![image](https://user-images.githubusercontent.com/4862573/102527543-d89be480-4062-11eb-9559-ebc3346a93e0.png)

**Comment by emyarod** [comment]
opening and closing the modal doesn't affect scroll position, but you can add a workaround for this at the application level. cc @carbon-design-system/design should the user expect the modal scroll position to reset when reopening the modal?

**Comment by liuljun** [comment]
@emyarod Is there plan for Carbon to change the current behavior?

**Comment by emyarod** [comment]
no plans at the moment but any potential changes would be dependent on feedback from our designers first
