### ISSUE TITLE
[BREAKING CHANGE] Danger button

### ISSUE THREAD

**Issue by DusanMilko** [carbon-design-system/carbon#7485]
Discovered a breaking change. If using carbon-components 10.23.2 and @carbon/themes 10.16.0, the danger button styles break. This is because the danger button tries to use $danger-01 but doesn’t exist in 10.16.0 theme. Can we have it default to use $danger if $danger-01 does not exist?? to avoid breaking changes

**Comment by emyarod** [comment]
wasn't something similar resolved in #7179 (after you opened #7178)? it should be contained in [@carbon/themes v10.22.1](https://github.com/carbon-design-system/carbon/releases/tag/v10.23.1)

**Comment by tw15egan** [comment]
Closing as resolved (in #7179), but feel free to reopen if there's something else that needs to be done
