### ISSUE TITLE
Easier access to default translations for component labels to use as a fallback.

### ISSUE THREAD

**Issue by kalbert312** [carbon-design-system/carbon#7492]
### Summary

Asking for: development

The issue: 
It would be helpful to have access to the default `translationWithId` function carbon defines in many component's `defaultProps` as a fallback to use.
Translations for keys may not exist for a couple of reasons:
1. Key(s) not yet localized for a particular language.
2. Carbon package was upgraded in project that brought new translation keys (circling back to 1)

Passing a custom `translateWithId` function loses the default translation values.

### Justification

To effectively provide translations where possible without needing to maintain copies of the default carbon english translations. It will more easily allow upgrading carbon and filling in the translation gaps at later times.

### Desired UX and success metrics

My desire is to have the implementation for our custom `translateWithId` to look like this:

```typescript
// NEW: defaultTranslateWithId
const customTranslateWithId = (messageId: string, args: { [key: string]: string } | undefined, defaultTranslateWithId: (key: string) => string) => {
  if (i18nextInstance.hasKey(messageId)) {
    return i18nextInstance.get(messageId);
  }
  return defaultTranslateWithId(messageId);
}
```

If every `translateWithId` function in carbon has this or a similar signature then I can write a single function that accepts an i18next instance an returns the above function to pass to each carbon component. The function only needs to be defined once and will work across all carbon components because each individual component will pass its `defaultTranslateWithId` dynamically.

~~An alternative solution: allow returning `null` in a custom `translateWithId` function. When `null` is returned, carbon internally falls back to the default `translateWithId`.~~

### Specific timeline issues / requests

No timeline. I have a workaround: manually composing all the component's `Component.defaultProps.translateWithId` into a single function but this needs to be manually maintained and updated.

What resources do you have to assist this effort?

I may be able to submit a PR for this time permitting.

**Comment by kalbert312** [comment]
`docs/g11n.md` states: 

> Some components have `translateWithId` props, that is API-compatible with
  [`react-i18next`](https://github.com/i18next/react-i18next) library. Search
  for
  [`translationIds`](https://github.com/IBM/carbon-components-react/search?q=translationIds&unscoped_q=translationIds)
  or
  [`translationKeys`](https://github.com/IBM/carbon-components-react/search?q=translationKeys&unscoped_q=translationKeys)
  to see the list of string IDs.

The translation function of i18next has args signature of `(key, options)` so introducing the initially proposed change is likely not ideal especially if users are passing the i18n function directly to `translateWithId`.

Maybe an exported single object with entries being the translation key and default translation?
For my usage I'm fine with calling `defaultProps.translateWithId` as a fallback.

**Comment by sstrubberg** [comment]
hey @kalbert312, thanks for submitting the issue. Sorry it's taken so long to get back to you. Is this functionality still something you're interested in pursuing?
