### ISSUE TITLE
[link] audit bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7498]
- [ ] Active state for inline link should be `text-01`

**Comment by emyarod** [comment]
the active link colors should already be `text-01` (https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/link/_link.scss#L38-L43), are you seeing something different?

**Comment by aagonzales** [comment]
@emyarod it shows up correctly for the default link but the inline link isn't showing it as text-01.  
https://github.com/carbon-design-system/carbon/blob/32e7ee970f40152b92006345f2eca164d88b7e11/packages/components/src/components/link/_link.scss#L78-L89

**Comment by emyarod** [comment]
the lines I referenced should be applied but it looks like the hover color is taking precedence #7503

**Comment by tw15egan** [comment]
Closing as fixed in #7503
