### ISSUE TITLE
TableToolbarSearch needs to custom placeholder

### ISSUE THREAD

**Issue by Pramodnagarajarao** [carbon-design-system/carbon#7500]
### Summary
Hi Team. Happy New Year! 
I work for IBM. We have a requirement to change the placeholder `TableToolbarSearch` component.
https://carbon-components-react.netlify.app/?path=/story/datatable--with-toolbar

### Justification
Need an option where the user can set their own placeholder string instead of `Filter table`.

### Specific timeline issues / requests

Anything sooner will be really helpful.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources
_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by sp2703** [comment]
Can I work on this?

**Comment by emyarod** [comment]
sure @sp2703, go for it

**Comment by tw15egan** [comment]
It looks like this already exists with the `placeHolderText` property. This is a bit confusing though, as `placeholder` is used throughout the rest of the repo. Going to push up a PR to alias them and deprecate the old prop.
