### ISSUE TITLE
[css]the select component display different style between Firefox and Firefox esr using globals scss style

### ISSUE THREAD

**Issue by yonghuay** [carbon-design-system/carbon#7507]
## What package(s) are you using?

- [x] `carbon-components` "^10.25.0", 
- [x] `carbon-components-react` "^7.25.0", 

## Detailed description

> Describe in detail the issue you're having.

I followed the carbon react tutorial import carbon-component **scss** style. I realize that the select component displayed differently between firefox esr and firefox.
I tested it on the codepen with the carbon css and the carbon scss, and I got different results.

> Is this issue related to a specific component?

the select component with globals **scss** style

> What browser are you working in?

Firefox esr

## Additional information

- Screenshots or code

![Screenshot 2021-01-06 at 10 00 25](https://user-images.githubusercontent.com/32554015/103787506-8d5b6d00-5035-11eb-9d78-ac80fe09955b.png)
<img width="1225" alt="Screenshot 2021-01-06 at 09 57 13" src="https://user-images.githubusercontent.com/32554015/103787515-90565d80-5035-11eb-9fe2-9119712b164d.png">

- Notes

**Comment by tw15egan** [comment]
Can you ensure you are using an autoprefixer as part of your build process? I've tested in both Firefox and Firefox ESR and I'm not able to reproduce

<img width="733" alt="Screen Shot 2021-01-20 at 10 33 18 AM" src="https://user-images.githubusercontent.com/11928039/105219216-0f09cb00-5b0b-11eb-8433-1e69f0a1f671.png">
<img width="763" alt="Screen Shot 2021-01-20 at 10 33 09 AM" src="https://user-images.githubusercontent.com/11928039/105219223-103af800-5b0b-11eb-99f6-e028e3187bd4.png">


Feel free to reopen if you believe there is still an error

**Comment by yonghuay** [comment]
Great,
thanks for the suggestion. After installed the **autoprefixer**, the issue is fixed in Firefox esr 
<img width="1234" alt="Screenshot 2021-01-21 at 08 40 45" src="https://user-images.githubusercontent.com/32554015/105325475-8b141980-5bc4-11eb-8f3b-0261c514a8d4.png">
