### ISSUE TITLE
ComboBox highlights all items after selection

### ISSUE THREAD

**Issue by ask-42** [carbon-design-system/carbon#7514]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When passing in an array of items to `ComboBox`, if the items don't have `id`s on them, after selecting one, all items are given the `bx--list-box__menu-item--highlighted` class and highlighted.

I believe this is because of this line here https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ComboBox/ComboBox.js#L451

If neither item has an `id`, `undefined === undefined` and it is considered highlighted.

> Is this issue related to a specific component?

ComboBox (And possibly other listboxes?)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I want to be able to select objects that use a different unique field for identifying them - the Storybook docs don't mention the `id` field is required on object items, and simply say "We try to stay as generic as possible here to allow individuals to pass in a collection of whatever kind of data structure they prefer", so I'd think it should support items of any structure.

Perhaps an `itemToId` function could be passed in as a prop to allow mapping a different field to id for highlighting, that defaults to `item => item.id`

I currently work around this by modifying data from the api and injecting the missing `id` prop, but ideally I should be able to pass it in unchanged.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Present as of
```
"carbon-components": "^10.25.0",
"carbon-components-react": "^7.25.0",
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

No currently pressing ship dates, but it would be nice to fix.

## Steps to reproduce the issue

1. Create a ComboBox selecting from Object items that do not have `id` props
2. Select an item
3. Open the ComboBox again
4. The other displayed items are also highlighted.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/sleepy-rain-69vkt

## Additional information

- Screenshots or code

<img width="881" alt="Screen Shot 2021-01-06 at 7 58 17 PM" src="https://user-images.githubusercontent.com/47505079/103850621-927fe280-505c-11eb-9ef3-d363462f7bd9.png">

```
import React from "react";
import { render } from "react-dom";
import { ComboBox } from "carbon-components-react";
import "carbon-components/css/carbon-components.css";

const items = [
  { label: "item1" },
  { label: "item2" },
  { label: "item3" },
  { label: "item4" },
  { label: "item5" }
];

const App = () => (
  <div>
    <ComboBox id="demo" items={items} />
  </div>
);

render(<App />, document.getElementById("root"));
```

**Comment by emyarod** [comment]
this seems to be present since the earliest iterations of this component several years ago
