### ISSUE TITLE
'autocomplete' prop in the ComboBox is not transparent

### ISSUE THREAD

**Issue by matheusarthus** [carbon-design-system/carbon#7528]
## Environment

> Operating system
macOS Big Sur 11.1

> Browser
Chrome

## Detailed description
Hello, guys! I need to be able to access the input autocomplete prop within the comboBox to solve this problem:

![image](https://user-images.githubusercontent.com/59973242/104235126-44d7f100-5433-11eb-80c3-ed09158dc962.png)

This prop is currently not transparent. Perhaps displaying a flag for that would solve the problem.
Thank you in advance for your help.

> What version of the Carbon Design System are you using?
"carbon-components": "10.24.0"
"carbon-components-react": "7.24.0"

**Comment by dakahn** [comment]
@matheusarthus We need a little more from you to get this triaged. Can you recreate the issue in the Codesandbox provided in the template? Are you using our Carbon React combobox in your screen shot there? 

Is this a bug or are you asking for an enhancement to combobox?

**Comment by matheusarthus** [comment]
Hi @dakahn! Thanks for your response.

Yes, I am using Carbon React Combobox in my screenshot.

I think it would be more like an improvement.

What I need exactly is to turn off the autocomplete input prop inside the Combobox. Watch the video below.

I need to remove this autocomplete suggestion that appears in the Combobox.

https://user-images.githubusercontent.com/59973242/104952201-ccc57a00-59a2-11eb-8b8c-a80f56a7e606.mov

**Comment by tay1orjones** [comment]
Ref https://github.com/carbon-design-system/carbon/pull/9157
