### ISSUE TITLE
Filterable MultiSelect changes from uncontrolled to controlled

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7529]
When using `MultiSelect.Filterable`, the component will change from uncontrolled to controlled based on an uninitialized `highlightedIndex` prop. This issue was initially reported in Slack.

Codesandbox: https://codesandbox.io/s/affectionate-joliot-lb9sb?file=/src/App.js

**Comment by ganisback** [comment]
+1

**Comment by ronnie152147** [comment]
+1

**Comment by dima19972525** [comment]
+1
