### ISSUE TITLE
[tile] expandable tile with links

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7552]
A product team wants to be able to put links in an expandable tile. They want to be able to trigger the link instead of it triggering the expansion of the tile. Is there a current solution for this they can implement on their end?

## Code sandbox for reference:
https://codesandbox.io/s/serverless-pine-en5lm?file=/index.js:442-484

## Visual reference:
![xlg-1312px-16 column](https://user-images.githubusercontent.com/43969356/104516626-48e24b00-55ba-11eb-88cb-d309ea23bf28.png)

**Comment by emyarod** [comment]
this can be resolved at the application level by adding `onClick={evt => evt.stopPropagation}` on the links
