### ISSUE TITLE
Provide option to specify OverflowMenu element type

### ISSUE THREAD

**Issue by queeniema** [carbon-design-system/carbon#7561]
By default, it is rendered as a `<button>`. This causes issues when I specify a `Button` component for the `renderIcon` prop. See sandbox [here](https://codesandbox.io/s/button-overflowmenu-nxfvj?file=/src/index.js).

![Screen Shot 2021-01-13 at 5 35 13 PM](https://user-images.githubusercontent.com/2454818/104533042-6e755180-55c6-11eb-98d6-fcc022b87d8a.png)

```javascript
<OverflowMenu
  className="export-button"
  menuOptionsClass="export-button-menu"
  renderIcon={() => (
    <Button iconDescription="Export" renderIcon={Upload16}>
      Export
    </Button>
  )}
>
  <OverflowMenuItem itemText="CSV" />
  <OverflowMenuItem itemText="JSON" />
</OverflowMenu>
```

**Comment by emyarod** [comment]
the error appears because the menu trigger element is already a button and you are trying to nest buttons. could you render the icon itself without wrapping it in another button?

**Comment by queeniema** [comment]
Thanks for the suggestion. I added the `bx--btn bx--btn--primary` and `bx--btn__icon` classes to get the same look and feel as a `Button`.
