### ISSUE TITLE
Loading bar as well as loading circle

### ISSUE THREAD

**Issue by CJMeek** [carbon-design-system/carbon#7567]
### Summary

Both design and development of a loading bar to show loading progress aswell as a loading circle.

### Justification

I find that when producing solution to show progress of loading page sometimes the loading circle can be a bit intrusive. For example if I wanted to show loading progress of a table whilst im still waiting for the api request to come in, i'd prefer to have a bar sat above the table to show that the table is loading.

### Desired UX and success metrics

A bar that works almost exactly like the loading circle but instead its a bar that can be resized horizontally and vertically to suit many different designs.

### "Must have" functionality

Same functionality as the loading circle

### Specific timeline issues / requests

No specificed time period

**Comment by tay1orjones** [comment]
Hi @CJMeek - Could you show a use case where the loading circle is too intrusive to frame this request? Perhaps a screenshot or something would be helpful. 

Also would the experimental [ProgressBar](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-progressbar--progress-bar) meet any of the need you outline?

**Comment by tay1orjones** [comment]
Closing this as we anticipate the ProgressBar should meet this use case
