### ISSUE TITLE
[number input] audit bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7570]
- [ ] We need to change the caret controls to a plus and a minus. Here is the final design spec [5417](https://github.com/carbon-design-system/carbon/issues/5417#)
![Number input (fixed) - White theme.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/dfcf736c-3bd3-469a-8ade-693960e4dad0)
![Number input (fixed) — Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/e5c58c57-a2e0-49a4-881e-78b2f5835f16)

- [ ] There needs to be a 12px space between the control icons and the end of the field container.
![md-672px-8 column](https://user-images.githubusercontent.com/43969356/104628133-7d5b1300-565d-11eb-9fc5-4c146f67db3b.png)

- [ ] In Safari, the input text is the wrong color for the disabled state in the dark themes. Should be `disabled-02`.
<img width="496" alt="Screen Shot 2021-01-14 at 11 32 18 AM" src="https://user-images.githubusercontent.com/43969356/104627056-2bfe5400-565c-11eb-8a3f-d1e2b26874ff.png">

- [ ] The mobile variant will be the same as the enabled state for the regular number input.
![md-672px-8 column copy](https://user-images.githubusercontent.com/43969356/104628178-8a780200-565d-11eb-93f5-79fbc6ab464a.png)

**Comment by emyarod** [comment]
#7687 will address the input controls overhaul, and after that is resolved we can deprecate the mobile input variant
