### ISSUE TITLE
DataTable unable to determine or set state of selected row

### ISSUE THREAD

**Issue by patrickml** [carbon-design-system/carbon#7573]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I have attempting to figure out how to set the state of a selected row as well as accurately update my components state to know that the row is tracked. What I have noticed, which I could be wrong, but the usage of onSelect will allow you to control the action of selection so the row wont be selected, however I did also notice that the `row` argument that comes from `rows` provided by `DataTable` will not have additional object properties on it, i.e. if i have a hidden field called `selected` which is put into the `data` prop I will not be able to access it to attempt to set the checkbox status to `selected`.

## Relevant information

```js
const data = [
    {
        id: 1,
        name: 'System A',
        selected: false,
    },
    {
        id: 2,
        name: 'System B',
        selected: false,
    },
    {
        id: 3,
        name: 'System C',
        selected: false,
    }
];
```

```
{
    rows.map((row) => (
        <TableRow key={row.id} {...getRowProps({ row })}>
            <TableSelectRow {...getSelectionProps({ row })} onChange={this.handleChange(row)} />
            {row.cells.map((cell) => (
                <TableCell key={cell.id}>{cell.value}</TableCell>
            ))}
        </TableRow>
))}
```

```
handleChange = (row) => (selected, id, event) => {
    console.log(selected, id, event, row, this.datatableRef)
}
```

**Comment by patrickml** [comment]
I was able to get the individual checkbox to work but not the select all. Here is a video showing what is happening

https://user-images.githubusercontent.com/7581369/104655079-22d8ab80-568b-11eb-9a71-0ac7978dc9de.mp4

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

most likely you would need to implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc. rather than using the built in state manager in `DataTable`, if that makes sense

**Comment by patrickml** [comment]
Hey @emyarod I will work on setting one up. I currently do have my own state manager. I'll attempt to replicate this within the sandbox. It may be tomorrow before I am able to create the sandbox.

**Comment by patrickml** [comment]
@emyarod so interestingly enough with this sandbox it looks as if the external state isn't able to control the selected status.

https://codesandbox.io/s/carbon-tables-test-case-row-selection-bx3ey?file=/src/index.js

Take a look at your console to see what should be selected.

**Comment by patrickml** [comment]
So i went with the route of building my own table using the atomic components. I ended up with something like this
```jsx
<DataTable
    data={children}
    columns={columns}
    rowIsSelected={this.rowIsSelected}
    rowIsDisabled={this.rowIsRequired}
    rowIsExpanded={this.rowIsExpanded}
    onRowSelect={this.handleRowSelect}
    onRowExpand={this.handleRowExpand}
    expanded={ExpandedRow}
/>
```

Might be worth adding this to the datatable? I also added `updateAllRows` `updateRow` as props

**Comment by emyarod** [comment]
it looks like you are still using the built in state manager in your code sandbox. can you try implementing a custom table like the sandbox I linked earlier? 

[custom state manager example](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager) using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc.
