### ISSUE TITLE
CodeSnippet: there should be a way to set the number of rows when in closed and expanded mode

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#7579]
This request got interpreted as a way to set the maximum number of rows.
Its intention was to set the number of rows, both min and max, when closed and expanded.
I have created [#8056](https://github.com/carbon-design-system/carbon/issues/8056) for the minimum number of rows.
Please when adding props for this keep in mind they are for the maximum number of rows.
So use props like  maxClosedNumberOfRows and maxExpandeNumberOfRows.

### Summary

CodeSnippet: there should be a way to set the maximum number of rows when in closed and expanded mode

Currently in closed mode the CodeSnippet shows a maximum of 15 rows.
Currently in expanded mode the CodeSnippet shows a maximum of unlimited, it grows to fit the rows in the data.

### Justification

If the client wants to use the component in a spot where space is limited they will want/need to control the number of rows shown.
If the client does not want to show all the rows in expanded mode there is no way (other than controlling the container it is in) to control the expanded displayed rows.

### Desired UX and success metrics

When not given these are the default values to match the current values:
maxClosedNumberOfRows: 15
maxExpandedNumberOfRows: undefined (this is unlimited; which has unpredictable results - it should have a cap)

New prop maxClosedNumberOfRows - to control the maximum number of rows shown when closed:
- defaults to 15 (existing behavior)
- if < 1 then maxClosedNumberOfRows === 100%

New prop maxExpandedNumberOfRows - to control the maximum number of rows shown when expanded:
- if undefined, 100% (existing behavior, [TBD] we may want to set this)
- if <= maxClosedNumberOfRows then the number of rows shown for both closed and expanded are the same
-- the showMore/showLess buttons are not shown
-- navigation for overflows are controlled via scrolling both horizontally and vertically

`0` Zero below means any value less then 1

Testcase - closed maximum of 15, expanded maximum of unlimited (the default):
{  maxClosedNumberOfRows: (15 || undefined), maxExpandedNumberOfRows: (`0` || undefined) }
The 'Show more'/'Show less' button is available.

Testcase - closed maximum of 10, expanded maximum of unlimited:
{  maxClosedNumberOfRows: 10, maxExpandedNumberOfRows: (`0` || undefined) }
The 'Show more'/'Show less' button is available.

Testcase - closed maximum of 15, expanded maximum of 20:
{  maxClosedNumberOfRows: (15 || undefined), maxExpandedNumberOfRows: 20 }
The 'Show more'/'Show less' button is available.

Testcase - closed maximum of 10, expanded maximum of 20:
{  maxClosedNumberOfRows: 10, maxExpandedNumberOfRows: 20 }
The 'Show more'/'Show less' button is available.

Testcase - always show at most 12 rows:
{  maxClosedNumberOfRows: 12, maxExpandedNumberOfRows: 12 }
The 'Show more'/'Show less' button is **not** available.

Testcase - always show at most unlimited rows:
{  maxClosedNumberOfRows: `0`, maxExpandedNumberOfRows: (`0` || undefined) }
The 'Show more'/'Show less' button is **not** available.

### "Must have" functionality

The props to set the rows is a must have for this.
The scrolling both horizontally and vertically are existing bugs and can be addressed as such. 

### Specific timeline issues / requests

Without the control over the layout on the screen IBM Cognos can not use CodeSnippet.
Initially we tried to work with the closed 15 row size but it is too big for our layout.
And in expanded mode, because it is unlimited, the layout is not controlable.

### Available extra resources

IBM Cognos may be able to help implement this.

**Comment by guigueb** [comment]
This enhancement is described in https://github.com/carbon-design-system/carbon/issues/7551

**Comment by tw15egan** [comment]
@carbon-design-system/design this is the other half of what is described in https://github.com/carbon-design-system/carbon/pull/7582. This also makes sense to me as there are applications that will not want their expanded CodeSnippet to fill its entire height if it contains many lines of code. This would set a `max-height` on the CodeSnippet when expanded

**Comment by tw15egan** [comment]
Closed via #8085
