### ISSUE TITLE
An issue about Accordion -- The title and content are not shown

### ISSUE THREAD

**Issue by whwangp** [carbon-design-system/carbon#758]
## Detailed description

When I copy the code for Accordion to my vue project, the title and content can't be shown as below:
<img width="406" alt="default" src="https://user-images.githubusercontent.com/31472308/39856776-baac0cc2-5463-11e8-8807-6f4af2e7ba47.png">

> Is this issue related to a specific component? 
Accordion

> What did you expect to happen? What happened instead? What would you like to see changed?
I need to show the title and contents. 

> What browser are you working in? 
Firefox

> What version of the Carbon Design System are you using? 
"carbon-components": "^8.18.13",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
<img width="1057" alt="default" src="https://user-images.githubusercontent.com/31472308/39856903-28e8c39c-5464-11e8-95fc-daa65157d6e2.png">

The following code is for main.js
<img width="460" alt="default" src="https://user-images.githubusercontent.com/31472308/39856941-4864f4ac-5464-11e8-8bab-0e187af42781.png">

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment]
Hi @whwangp thank you for trying to report an issue. Did you want to enter this issue against https://github.com/nicholaslee119/carbon-components-vue first?

**Comment by whwangp** [comment]
@asudoh Thanks for your replying. That's right. This issue is about carvue. I just changed it ca-accordion. And it is normally running now.
