### ISSUE TITLE
A question about Dropdown

### ISSUE THREAD

**Issue by whwangp** [carbon-design-system/carbon#759]
How should I set the default value for the dropdown list? 

## Detailed description
The default value is always 'Dropdown label' as below:
<img width="1276" alt="default" src="https://user-images.githubusercontent.com/31472308/39859922-0aefc8fe-546e-11e8-95b7-3a457bf52b41.png">
 I try to set defaultText, but it is not working.

## Additional information
<img width="806" alt="default" src="https://user-images.githubusercontent.com/31472308/39859990-4a9dda90-546e-11e8-9aef-d07cdbd1f236.png">

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment]
Hi there @whwangp! 👋 Tried digging into the code to see if this was a capability, but couldn't find anything immediately that might match. cc'ing @asudoh just in case I missed something to verify!

**Comment by asudoh** [comment]
`<li class="bx--dropdown-text">Dropdown label</li>` is the one - You can see it in the screenshot is in too. Feel free to reopen if it’s not the case. Thanks!

**Comment by whwangp** [comment]
@asudoh Thank you so much. I ignored this line before. It works fine now.
