### ISSUE TITLE
Is there a dashboard template where to start?

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#7591]
## What package(s) are you using?

 
- [x] `carbon-components`
- [x] `carbon-components-react`

## Relevant information

Is there an example of a basic dashboard in React or a template where to start?
Thanks.

**Comment by dakahn** [comment]
Took the liberty of started a discussion based on this question in our new Github Discussions section.

**Comment by Robokishan** [comment]
Looking for same in react

**Comment by Robokishan** [comment]
I found one for angular https://github.com/petter-ka/youpez-admin
but I was looking for react specifically as I am able to build datatable using docs. But it is not responsive and storybook examples don't elaborate enough about responsiveness.
