### ISSUE TITLE
add[illustration]: When React storybook like in shared users see a v9 Carbon graphic

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon#7593]
## This is the offending image:

![image](https://user-images.githubusercontent.com/43144260/105052699-ca603000-5a35-11eb-8e4a-4e63ac926255.png)

If you see a storybook link pasted in Slack, you see this old v9 Carbon image.
https://react.carbondesignsystem.com/?path=/story/datatable--usage

## Specs for image

1200 x 630px is the size of some of the other images we're using for previews (see below), it's a little soft at 72 dpi so I'd go
**2400 x 1260px** 

## Background information and inspiration:

This is the image we are currently using on the Carbon website that shows in some of our other previews. 
https://www.carbondesignsystem.com/static/ogimage-324e43fd3b74f4ece4582018a067eb27.png

But, I think it's time to start freshening these images up and having a little more fun with them. Anything we make can be repurposed for other uses, like medium articles or Slack communications in the future. 

- We have the Carbon expressive pictograms now too (file below) 
- We have this pictorgram grid that we've played with before (file below)

![image](https://user-images.githubusercontent.com/43144260/105055487-bbc74800-5a38-11eb-8e8f-b98f208a457d.png)

https://medium.com/carbondesign/whats-coming-to-carbon-in-2021-39a4c7d1762a

<img width="760" alt="Screen Shot 2020-11-16 at 10 18 13 AM" src="https://user-images.githubusercontent.com/43144260/105063583-807d4700-5a41-11eb-8769-85c7134a3841.png">

![image](https://user-images.githubusercontent.com/43144260/105063712-a99dd780-5a41-11eb-99b3-273df2b5af39.png)

![image](https://user-images.githubusercontent.com/43144260/105063730-b15d7c00-5a41-11eb-82dd-a0e7544cd90d.png)

## Files

You can download the IDL Master pictogram file here too:
https://www.ibm.com/design/language/iconography/pictograms/design

[carbon_expressive_pictos.ai.zip](https://github.com/carbon-design-system/carbon/files/5837266/carbon_expressive_pictos.ai.zip)

[Carbon_messaging_template.ai.zip](https://github.com/carbon-design-system/carbon/files/5837276/Carbon_messaging_template.ai.zip)

![smiley_build](https://user-images.githubusercontent.com/43144260/105065033-09e14900-5a43-11eb-9b93-bd6104378d4c.png)

[carbon_illustrations.zip](https://github.com/carbon-design-system/carbon/files/5837310/carbon_illustrations.zip)

**Comment by mjabbink** [comment]
Love the illustration with icons and grids above. Very nice and I can image more of that exact thing across other elements. transitioning from wireframes and specs to the final full color thing.

**Comment by tay1orjones** [comment]
This was fixed in https://github.com/carbon-design-system/carbon/pull/7893 🎉
