### ISSUE TITLE
TableToolbarSearch is firing onSearch twice for every input

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#7595]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?
To see the issue simply render a TableToolbarSearch and then type into it
 <TableToolbarSearch
                placeHolderText={i18n.searchPlaceHolderText}
                onChange={onSearch}
                className={`${iotPrefix}--tile-catalog--tile-canvas--header--search`}
              />

> What browser are you working in?
Chrome and Jest

> What version of the Carbon Design System are you using?
"carbon-components": "^10.26.0",
    "carbon-components-react": "^7.26.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See this codesandbox to see the issue:
https://codesandbox.io/s/carbon-components-react-forked-5q8de?file=/src/index.js

If you type into search field and check the console.log you'll see two entries for each button press

**Comment by tw15egan** [comment]
This will be fixed via https://github.com/carbon-design-system/carbon/pull/7613
