### ISSUE TITLE
Breaking change in datepicker invalid styles

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#7597]
This issue was opened against us recently: https://github.com/IBM/carbon-components-angular/issues/1702

Searching through the PRs it appears this regression was introduced here: https://github.com/carbon-design-system/carbon/pull/7368/files#diff-5fb559b76ba102f4c0d66bf638fd5268c8fdd6b2b995b70db368248fabf2b2a9L81-L83

It seems reasonable to re-introduce `.#{$prefix}--date-picker-input__wrapper,`. We have a fix in progress, however that won't help the rather large number of adopters that will upgrade `carbon-components` in the meantime and have broken datepicker styles.

I can submit a fix if needed, would like to get this resolved in the next Carbon patch release.

**Comment by tw15egan** [comment]
Sorry about that @cal-smith! I can push up a change adding that class back in

**Comment by cal-smith** [comment]
Thanks @tw15egan!
