### ISSUE TITLE
[Tooltip]: Controlled tooltip should still invoke onChange callback when clicked

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#7598]
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
See this code sandbox to reproduce:
https://codesandbox.io/s/carbon-components-react-forked-sx6v2?file=/src/index.js

Notice as soon as I set the tooltip to 'open' to make it controlled, I lose the click events.  Cliick on the first tooltip and you'll notice no event is thrown in the console.  Click on the second and you'll see the click events

https://codesandbox.io/s/carbon-components-react-forked-sx6v2?file=/src/index.js

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by dakahn** [comment]
Thanks for reporting. Moved to backlog. 👍🏽
