### ISSUE TITLE
Validation symbol still uses Helvetica instead of Plex

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon#760]
The `Component/Select/Select/States/Validation` symbol still uses Helvetica instead of Plex.

![image](https://user-images.githubusercontent.com/764090/39884593-5abf5b94-5458-11e8-936b-04b9fc220e79.png)

**Comment by werdnanoslen** [comment]
Also I think the character spacing should not be 0.5 in Plex? Looks weird with it

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-design-kit #40](https://github.com/carbon-design-system/carbon-design-kit/issues/40) via [**ZenHub**](https://www.zenhub.com/)
