### ISSUE TITLE
Which validation library is compatible with Carbon?

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#7628]
Which validation library is compatible with Carbon?

**Comment by tw15egan** [comment]
Hey there @biapar do you have any more information that you could provide us so we can help answer your question? What are you trying to validate?

**Comment by biapar** [comment]
Hi, I create a form with more fields and so I need to validate input from client side before to save. I used Formik, but there isn’t anything included with Carbon.

**Comment by tw15egan** [comment]
You'll need to handle the validation yourself. All Carbon form elements have an `invalid` and `invalidText` property to handle displaying the errors. Hope that helps!

**Comment by biapar** [comment]
yes, I solved in that manner. thanks.

**Comment by tw15egan** [comment]
Great to hear! Going to close this out but feel free to reach out with any other questions you may have 🙂
