### ISSUE TITLE
[tag] fix hover and focus for filterable tag

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7630]
- The current hover and focus states are slightly off for our filterable tag component.
- Since we are also adding a `small` tag variation, we need to make an adjustment to these states so they are consistent across both sizes. 

![Artboard Copy 4](https://user-images.githubusercontent.com/43969356/105515696-9d608700-5c9a-11eb-9578-3a6a3faa7328.png)

------
![Artboard Copy 5](https://user-images.githubusercontent.com/43969356/105515705-a05b7780-5c9a-11eb-8d23-b1757b1591f3.png)

**Comment by emyarod** [comment]
also impacts https://github.com/carbon-design-system/carbon/pull/7518

**Comment by emyarod** [comment]
small tag will be addressed by #7619, so we can just track the default tag updates here!
