### ISSUE TITLE
A new dropdown variant with title and subtitle as an entry

### ISSUE THREAD

**Issue by manujt1** [carbon-design-system/carbon#764]
So, this a an issue for a new dropdown variant where is the entries would be a combination of title and subtitle. This was a requirement where I wanted to represent a set of audience NAME and ATTRIBUTE pairs as shown below

> Is this issue related to a specific component? 
Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?
There is no provision for having a subtitle for the entries in the dropdown.

> What browser are you working in? 
NA

> What version of the Carbon Design System are you using? 
8.1.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
App Launch from IBM Mobile India. No pressing release date yet.

<img width="418" alt="screen shot 2018-05-11 at 12 39 25 pm" src="https://user-images.githubusercontent.com/2443368/39911246-60c5f6f4-5518-11e8-8416-2e91d0c9f74d.png">

Will be adding my solutions in the replies so that we can work on it together. Looking forward to your response on this.
Thanks

**Comment by manujt1** [comment]
One of the proposed solutions was.
<img width="973" alt="screen shot 2018-05-10 at 12 08 00 pm" src="https://user-images.githubusercontent.com/2443368/39920058-5c53ce50-5533-11e8-8210-b35e82fcdd11.png">
<img width="512" alt="screen shot 2018-05-10 at 12 34 23 pm" src="https://user-images.githubusercontent.com/2443368/39920069-626304f0-5533-11e8-85a3-38797da10e41.png">

**Comment by tay-aitken** [comment]
@yumeforever

**Comment by yumeforever** [comment]
Hey guys, sorry the delay.
We too have the use-case for the multi-line dropdown.
It will be the widget saying in which context you currently are and how to switch to another context.
In this case, IBM Cloud Functions "Namespace"

As we learn, the majority of people have from 0-5 namespaces, but a huge portion also has up to 12, so we are considering adding a search.
But I really like  @manujt1 Recent and All categories :D we also had it!
The specs are not there yet. I will try to use the ones Manuj was using. 


![screen shot 2018-05-16 at 13 56 38](https://user-images.githubusercontent.com/3612533/40115529-128455f6-5911-11e8-95bd-17a09f778079.png)

**Comment by manujt1** [comment]
Hi worked on the component design taking inspration from Morgana's version. Review and feedback appreciated. Also let me know if it can be implemented or not. Thanks

Tried to fit the component height to 48px and explored different versions of the dropdown.

<img width="887" alt="screen shot 2018-05-25 at 2 03 46 pm" src="https://user-images.githubusercontent.com/2443368/40535062-a325b97c-6025-11e8-96f9-f7879a839427.png">
<img width="653" alt="screen shot 2018-05-25 at 2 09 17 pm" src="https://user-images.githubusercontent.com/2443368/40535063-a357c3ea-6025-11e8-9a33-e16cd8329f58.png">

**Comment by tay-aitken** [comment]
Hello! Wanted to circle back and see how the work was going on this!

**Comment by manujt1** [comment]
The work on the component is paused due to other project commitments. However, in the previous post I tried to compress the component to the height of 48px. Also worked on the feedbacks given by @tay-aitken
Following the guidelines here http://www.carbondesignsystem.com/getting-started/contributing
and trying to find a developer who can assist in developing the component. Will update you on the progress. Thanks

**Comment by tay-aitken** [comment]
Thanks @manujt1!
