### ISSUE TITLE
Tooltip component -> popup div location issue

### ISSUE THREAD

**Issue by travis1111** [carbon-design-system/carbon#765]
I am using the tooltip component on an icon, we need to place the icon at the top right corner of the page.  We would like to have a tooltip popup div (below the icon) when mouse hover on the icon.

The problem is, the triangle is always centred to the popup box and the popup box looks ugly.

Please see screen cap below.

> Is this issue related to a specific component? 

Yes, tooltip component

> What did you expect to happen? What happened instead? What would you like to see changed?

See attached image

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Microclimate

## Steps to reproduce the issue

1. Create a tooltip icon at the top right corner of the page.
2. Mouse hover on it the first time, you will see pic 1
3. Mouse hover away then back, you will see pic 2
4. Mouse hover away again, then back you will see pic 3
5.  Mouse hover away then back again, you will always see pic 3
6.  What we would like to see is pic 4.

## Additional information

* Screenshots or code
* Notes

## Add labels
tooltip, position, popup

![image](https://user-images.githubusercontent.com/35569780/39928448-5e4534f4-5503-11e8-866f-001286c69e5a.png)

![image](https://user-images.githubusercontent.com/35569780/39928503-7de44da4-5503-11e8-9229-a7fa0941dd38.png)

![image](https://user-images.githubusercontent.com/35569780/39928540-9cbccfd0-5503-11e8-941d-cca09f2b637f.png)

![image](https://user-images.githubusercontent.com/35569780/39928578-be53f2fe-5503-11e8-9e5d-3ba31bb65b81.png)

**Comment by asudoh** [comment]
Hi @travis1111 thank you for entering this issue! Tooltip has an option to adjust the menu position. Before providing you with the specifics, are you using our vanilla JavaScript version or our React version?

BTW - In case you are an IBMer creating IBM Cloud service UI, my recommendation as of now is using our standard service for the header. Ping me via our internal Slack if you have further questions here. Thanks!

**Comment by travis1111** [comment]
we are using vanilla js.

we have tried the top/right/bottom/left options, but we were not able to make it look it PIC 4.

I will send you an email and try to ping you on slack tonight.

**Comment by asudoh** [comment]
Hi @travis1111 vanilla version has `objMenuOffset` option, which takes either of:

* An object with `top`/`left` properties
* A function returning an object above

Make sure you can turn off automatic instantiation of Carbon components, and instantiate the tooltip with above option. Please refer to http://www.carbondesignsystem.com/getting-started/developers#javascript for more details. Thanks!

**Comment by travis1111** [comment]
Thanks @asudoh  do you have any samples?  For me there are two positions I want to change, one is the popup tooltip box, another one is the little triangle, which by default it is placed in the centre of the popup, so which offset this option can take care of?  and what is the option (if there is) for the other offset?

thanks

**Comment by asudoh** [comment]
@travis1111 here it is: https://codepen.io/asudoh/pen/LmBXQg

**Comment by travis1111** [comment]
@asudoh Thank you!!!!!!

**Comment by travis1111** [comment]
@asudoh Thanks for providing the code sample, it really helps!  Now I am facing a resize problem.  In your codepen example, if you adjust the browser window width the popup doesn't look right anymore.  So how I I respond to the event?  (try to adjust the browser windows size from the right edge of the window and move to left so the width is reduced).

thanks!

**Comment by travis1111** [comment]
Another issue is, you can first maximum the windows, refresh codepen sample page, the tooltip works prefect at this moment.  If you click restore button (browser's restore size button, between minimize and maximize), the window size changes, then if you hover mouse icon on the tooltip icon, you will see it readjust the popup size, still not prefect, you will have to move mouse cursor on and off a few times in order to get the prefect view.

**Comment by asudoh** [comment]
@travis1111 I’d recommend hooking `resize` events on `window` and change the `top`/`left` styles of the menu.

**Comment by travis1111** [comment]
@asudoh can you please elaborate?  I tried this but did not work (your code pen demo)

```sh
window.addEventListener('resize', function(event){
    console.log("resize");
  var Tooltip = CarbonComponents.Tooltip;
    var elem = document.querySelector('[data-tooltip-trigger]');
 var defaultOptions = Tooltip.options;
    
  tooltip.options.objMenuOffset = function (menuBody) {
      var offset = defaultOptions.objMenuOffset.apply(this, arguments);
      var geom = menuBody.getBoundingClientRect();
      
      offset.left += -geom.width / 2 + 22;
      return offset;
    }
  });

```
But it is not working.

**Comment by asudoh** [comment]
@travis1111 The Carbon `Tooltip` cannot change the position once it’s shown. You may want to try something like ``window.addEventListener('resize', () => { menuBody.style.left = `${adjustedLeft}px`; });``.

**Comment by travis1111** [comment]
@asudoh thanks but I cannot get it working... can you please paste complete code on codepen using your existing example?  Thanks

**Comment by asudoh** [comment]
@travis1111 Wondering what code you came up with which is not working, but here are some tips - Carbon vanilla code merely deals with HTML/CSS/DOM to create the UI. The (floating) menu is positioned with its style attribute. You can see it by looking at the DOM in Chrome DevTools, if you focus on almost the end of `<body>`. The first step is finding such menu, force it's shown, and fiddling with such style attribute to get the right position. Then you can write `resize` event handler to do the same thing. Hope it helps!

**Comment by travis1111** [comment]
@asudoh 

I added this

```sh
window.addEventListener('resize', () => { 
  console.log("resize");
  var element = document.getElementById('unique-tooltip');
  element.style.left='10px;'; 
  
    var style = window.getComputedStyle(element);
    var left = style.getPropertyValue('left');
  console.log(left);
  
                                        });
```

console log shows different left value, not 10px...

is this correct?  Or somewhere else in the Carbon component is overwriting the left property too?

**Comment by asudoh** [comment]
> Or somewhere else in the Carbon component is overwriting the left property too?

Not that I’m aware of, but you can inspect it via the DOM inspector in Chrome DevTools to see that.

**Comment by travis1111** [comment]
@asudoh yes, I checked it in chrome debugger that is why I say it is not working.  so the code I pasted is the one you were thinking?

**Comment by asudoh** [comment]
The reason why I brought up the DOM inspector in Chrome DevTools is that it tells what style (yours or ours) is effective for the computed style. Also you can directly edit the style or the attribute there - In this way you can see how change in style affects the UI.
