### ISSUE TITLE
carbon-components-react/es/components/UIShell/HeaderGlobalAction.js does not export 'default'

### ISSUE THREAD

**Issue by rscoates** [carbon-design-system/carbon#7650]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I'm using Parcel with --experimental-tree-hoisting (because the icons are clogging our package - #4847)

> Is this issue related to a specific component?
Possibly related to UIShell specifically, but it might be more general

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expected Parcel to bundle without errors.
Instead, received error: `🚨  ../node_modules/carbon-components-react/es/index.js does not export 'default'`

> What version of the Carbon Design System are you using?
7.27.0

## Steps to reproduce the issue

1. Create a project with Parcel
2. Run `parcel build --experimental-scope-hoisting`

**Comment by joshblack** [comment]
Hi there, @rscoates! 👋 

Sorry to hear about Parcel and icons, it does seem like `--experimental-tree-hoisting` helps with tree-shaking them, at least.

For the error that you're experiencing, could you share the code and ideally a CodeSandbox that reproduces the problem? Happy to take a look to see what's going on!

**Comment by rscoates** [comment]
It looks like this is an issue with React `lazy`. At least, that seemed to fix it when we didn't use it.

**Comment by joshblack** [comment]
Sounds good! Going to go ahead and close this issue out, if this is in error definitely let me know and I can re-open!
