### ISSUE TITLE
[loading] audit bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7655]
Loading
- [ ] In Safari the background of the "small" modifier is not appearing
   - Chrome: 
   ![image](https://user-images.githubusercontent.com/11670886/105894555-6532ae80-5fe2-11eb-8e09-d8e4d4965df4.png)
   - Safari 
   ![image](https://user-images.githubusercontent.com/11670886/105894587-6ebc1680-5fe2-11eb-9018-4cfc69d822eb.png)

**Comment by tw15egan** [comment]
It looks like [safari does not suppor](https://stackoverflow.com/questions/37246113/svg-stroke-dashoffset-not-working-on-safari)t negative `stroke-dashoffset`, which we have in the background. 

<img width="236" alt="Screen Shot 2021-01-26 at 2 11 19 PM" src="https://user-images.githubusercontent.com/11928039/105912635-9f9b4c00-5fe0-11eb-8396-7f8258d31743.png">


Investigating workarounds
