### ISSUE TITLE
[Table] Closing Overflow menu set focus to wrong node

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon#7660]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When the overflow menu closes it sets the keyboard focus to the button that opened it. This makes sense for closing with the keyboard (esc), but not for mouse clicks. Whatever is clicked on should gain focus, not the last overflow menu button.

## Steps to reproduce the issue

- Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--simple-stateful-example-with-column-overflow-menu
- Click an OverflowMenu button in a header.
- Without closing the menu click a different overflow menu button. The keyboard focus goes to the previous menu button.

This same happens when clicking other elements that should gain focus, like a button.

**Comment by tw15egan** [comment]
Hey, @gillibrand thanks for reporting! Do you have a link to a reproducible example on CodeSandbox? I'm unable to reproduce the behavior on our storybook, and unsure if this is an issue with our Overflow menu or the IoT variant: https://react.carbondesignsystem.com/?path=/story/datatable--with-overflow-menu (hover over the row to get them to display)

**Comment by gillibrand** [comment]
I can reproduce in carbon-component@10.12 + carbon-components-react@7.12 but not in the latest release, so I'll close this.
https://codesandbox.io/s/overflowmenu-focus-stealing-srjln?file=/src/index.js
