### ISSUE TITLE
Sidenav toggle behavior with vanilla js

### ISSUE THREAD

**Issue by aveltras** [carbon-design-system/carbon#7662]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Hi, I'm trying to figure out how to get the same behavior related to side navigation as is visible on the website [https://www.carbondesignsystem.com/](https://www.carbondesignsystem.com/).
- no hamburger menu icon while on large screen
- hamburger menu icon when on smaller screen with toggling sidenav on/off

I haven't succeeded so far to get the toggling behavior as I can't find which data-attribute or class should be present or where they should be.
I'm using the full vanilla js bundle from the package (carbon-components/scripts/carbon-components.js).
Also looking at examples from : [https://the-carbon-components.netlify.app](https://the-carbon-components.netlify.app) and from [https://react.carbondesignsystem.com/](https://react.carbondesignsystem.com/) to get a hint of what should the html tree structure look like.
The examples featured on [https://the-carbon-components.netlify.app/component/ui-shell--default.html](https://the-carbon-components.netlify.app/component/ui-shell--default.html) has a completely separate navigation tree (at the end of the html source) which I'm not sure is the way to go.

Is it a current limitation with the vanilla js implementation or am I missing something ?

## Relevant information

Using carbon-components v 10.26.0

**Comment by joshblack** [comment]
Hi there, @aveltras! 👋 

Unfortunately, the vanilla variant of components isn't kept up-to-date like the React variants. Most of our time as maintainers is spent on the React components nowadays.

For vanilla components, there is the community support Web Components package over at: https://github.com/carbon-design-system/carbon-web-components that might be a better-supported alternative.

Sorry again about the lack of information, but I hope this helps!

**Comment by aveltras** [comment]
I see, thanks for pointing me to the web-components library.
