### ISSUE TITLE
helper-mixins do not respect css custom properties

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#7665]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using css custom properties to emit a carbon theme, the helper mixins do not respect these values and default to the ones form the white theme.

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

helper mixins should respect css custom properties

> What browser are you working in?

Chrome 87

> What version of the Carbon Design System are you using?

`carbon-components@10.27.0`

## Steps to reproduce the issue

1. Emit `g100` theme with css custom properties
2. Import `carbon-components/scss/globals/scss/helper-mixins`
3. Use the `focus-outline` mixin

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/delicate-microservice-tvkge

## Additional information

With the codesandbox example from above, the focus outline of the component is blue 60.
![image](https://user-images.githubusercontent.com/28265588/106025404-009e4f00-60c9-11eb-9231-c8a251e142fd.png)

The focus color in both dark themes should be white. Manually adding `outline-color: var(--cds-focus);` to the focus selector in the component corrects the color.
![image](https://user-images.githubusercontent.com/28265588/106025761-596de780-60c9-11eb-95d6-62c1e01bb4f0.png)

**Comment by dakahn** [comment]
Gonna change this one over to a feature/enhancement request. 👍🏽

**Comment by tay1orjones** [comment]
> helper mixins should respect css custom properties

This will be coming in v11 with the new Inline Theming functionality. Closing, but let us know if there's something else to address here @janhassel
