### ISSUE TITLE
Modal with long selectable data-table in modal body : selecting a row causes modal to content overflow

### ISSUE THREAD

**Issue by galilmori** [carbon-design-system/carbon#7682]
## What package(s) are you using?

- [x] @console/pal v1.337.5

## Detailed description
Creating a modal with a table inside with selectable rows .
if you have a lot of selectable rows selecting the last row will cause the content to overflow outside of the modal.
causing a blank modal content

## Steps to reproduce the issue

- create a modal with long table content with selectable rows
- scroll to the last element
- select last element
- content disappears

 sandbnox replication of the issue : https://codesandbox.io/s/dark-bush-dedz7?file=/index.js

## Additional information

![image](https://user-images.githubusercontent.com/50196414/106137915-b7530b80-616b-11eb-940f-3212403d8100.png)

## Suggestions for fixing this
- it appears that this can be fixed by adding position: relative to bx--modal-content currently its inheriting a static position in css

**Comment by wkeese** [comment]
This fix causes regressions: dropdowns are clipped by the edge of the `bx--modal-content` node.   Additionally, I think the real issue here is what I listed in #9403.  Since #9403 is fixed this change should presumably be rolled back.
