### ISSUE TITLE
Form errors accessibility

### ISSUE THREAD

**Issue by hvlawren** [carbon-design-system/carbon#769]
## Detailed description

When viewing any form with a built in error that is not activated with data-invalid with VoiceOver the error messages are read even though the error is not displayed visually and no text is in the date picker.

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected: No error message to be read when not in error state
Actual: Error message read "Invalid Date Format"

> What browser are you working in? 

Safari with VoiceOver

> What version of the Carbon Design System are you using? 

Currently 8.19. Replicated on http://carbondesignsystem.com/components/date-picker/code page

## Steps to reproduce the issue

1. Navigate to date picker in screen reader (or any other input with an error)
2. Proceed to next element after date input box
3. "Invalid Date Format" is read by screen reader

## Additional information

Adding display: none style when error should not be read aloud should fix this... or aria-hidden="true" in html if you want to preserve the margin

**Comment by hvlawren** [comment]
I looked through the date-picker.js code. I didn't see anything that actually causes the errors to be displayed visually. Is there some case that I didn't see where the errors are displayed?

**Comment by tw15egan** [comment]
I think it works similar to how other inputs work. If you scroll down to the bottom here, you can see: http://carbondesignsystem.com/components/form/code


The date-picker needs `data-invalid` to show the error

**Comment by hvlawren** [comment]
Ah, I see. This error also occurs on the form page, so it's likely everywhere that uses that style of error in Carbon.

I've updated the title and description.

**Comment by hvlawren** [comment]
closed by #807
