### ISSUE TITLE
Reinitialize carbon datatable

### ISSUE THREAD

**Issue by maximkatsuba** [carbon-design-system/carbon#77]
I'm using AngularJS and  Carbon Datatable. I have already did part of code to init Datatable only when page is ready (when ng-repeat complete work).
`
if (scope.$last){
            var dataTable = document.querySelector('[data-responsive-table]');
            CarbonComponents.DataTable.init(dataTable);
 }
`

 But now I want to know how to correctly refresh datatable when I did some operations with rows (add new, hide, remove). Currently after deleting rows - all DataTable becomes broken.

Here are some error messages:
```
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.nn._toggleRowExpand 
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
```

When I'm trying to refreshRows manually by using ref to datatable and method tableref.refreshRows() I get next error:

`Uncaught TypeError: e.zebraStripe is not a function(…)`

**Comment by asudoh** [comment]
@chrisdhanaraj Is it `.refreshRows()` that should run after addition/deletion of rows?

**Comment by chrisdhanaraj** [comment]
Heyo, can you tell me what version of the library you're on? The latest v7.4.2 fixes the issue with refreshRows

**Comment by maximkatsuba** [comment]
Thank you!
I didn't notice that it is old version of library in the project.
I updated it and the issue was fixed.
