### ISSUE TITLE
Carbon Design System typography type scale is wrong

### ISSUE THREAD

**Issue by SaltedCaramelCoffee** [carbon-design-system/carbon#770]
## Detailed description

http://www.carbondesignsystem.com/style/typography/overview

type scale actual size is not accurate.

> Is this issue related to a specific component? 

No

> What did you expect to happen? What happened instead? What would you like to see changed?

Actual size column does not show how the font would look in actual size. Please change them to reflect actual size.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

This is in the Carbon Design System website

## Steps to reproduce the issue

1. go to http://www.carbondesignsystem.com/style/typography/overview
2. Scroll down to typography
3. For the column actual size, inspect the element.
4. Check and you'll see the font size displayed is not the same as what it should be

## Additional information

![screen shot 2018-05-14 at 5 30 47 pm](https://user-images.githubusercontent.com/10778821/40026945-2eb22b1a-579d-11e8-8a6b-ba05798a8d1e.png)

**Comment by asudoh** [comment]
Team - Do you think we should fix our website, or our component library? Thanks!

**Comment by marijohannessen** [comment]
Issue moved to [carbon-design-system/design-system-website #211](https://github.com/carbon-design-system/design-system-website/issues/211) via [**ZenHub**](https://www.zenhub.com/)
