### ISSUE TITLE
Contributing Link With Icon from Carbon for IBM.com

### ISSUE THREAD

**Issue by guilhermelMoraes** [carbon-design-system/carbon#7708]
### Summary

As per [issue ticket number 4416 from Carbon for IBM.com](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4416), we're willing to contribute our [Link With Icon component](http://ibmdotcom-react.mybluemix.net/?path=/story/components-linkwithicon--default) from the React package to the core Carbon. 

### "Must have" functionality

Pretty much all the visuals and behavior present in the Storybook story (link above).

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/8361
