### ISSUE TITLE
Locale support(DatePicker) needs better locale support

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#7709]
### Summary

There needs to be more supported locales, and better logic in determining which locale to use.

This is a development request.
This issue was encountered when working with DatePicker but there are many components that need to be localized.

### Justification

To be an international player our products need to be internationalized.

### Desired UX and success metrics

The options for each locale need to be adhered to...
- display and input dates using the requested locale settings
- display and input numbers using the requested locale settings
- display and input time using the requested locale settings 

There needs to be better logic to choose a fall back locale, when a requested locale does not exist.

### "Must have" functionality

This came about specifically when using DatePicker.
But this is an issue for any Component that displays and/or inputs data that can be localized.

### Specific timeline issues / requests

Our next release this quarter - which has been Carbonized - will not be able to support all the locales that we did in the past.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

TBD

**Comment by guigueb** [comment]
There needs to be better logic to choose a fall back locale, when a requested locale does not exist.

Suggested fall back logic... given “xx-yy-zz”...

1. if “xx-yy-zz” exists use it
2. if not, use “xx-yy” if it exists
3. if not, use “xx" if it exists
4. if not, use the default locale - (may need a defaultLocale prop - initially set to 'en')

**Comment by joshblack** [comment]
@guigueb as far as I understand, localization/internationalization is relegated to product teams to determine the correct translations for their product. Most often in the components this is implemented either through props (like `labelText`) or through a `translateWithId` that is a function which takes in the message identifier.

For DatePicker, we are specifically limited by `flatpickr` which lists the following locales: https://github.com/flatpickr/flatpickr/tree/master/src/l10n

**Comment by guigueb** [comment]
To be clear - this is not a string localization issue.
The issue is flatpickr is too limited in the date locales it supports.

This issue has two parts.

One part is extending the locales...
We have several locales our product currently supports (kk, nb, etc) that we will loose using Carbon's date picker.
As well, we support many sub-locales (pt-br, zh-cn, zh-tw, etc) that we will also loose support for.
Maybe we need to contribute to flatpickr and add locales, or maybe we need to find another date library.

The other part is handling what locale to use when the chosen locale is not supported.
If given a locale that is not supported the date picker should not fail... it should default to the best locale it can.
My comment from Feb 2nd.

**Comment by tw15egan** [comment]
> We have several locales our product currently supports (kk, nb, etc) that we will lose using Carbon's date picker.


`kk` is `kz` (Kazakh), `nb` is `no` (Norwegian Bokmål) inside of Flatpickr. Should be easy enough to check if the provided value is either `nb` or `no`, and pass `no` to `Flatpickr`. 

---

> As well, we support many sub-locales (pt-br, zh-cn, zh-tw, etc) that we will also lose support for.

I believe `zh-cn` is simply `zh`, and `zh-tw` is `zh_tw` in flatpickr. Again, we can probably see what is passed to our `DatePicker` and send the correct one to `Flatpickr`

I don't see support for `pt-br`, but contributing back to Flatpickr should be easy enough. My wife is Norwegian so she was able to help me make one for Norwegian Nynorsk `nn-no` - Here's a [PR I made to Flatpickr](https://github.com/flatpickr/flatpickr/pull/2423)

---

> If given a locale that is not supported the date picker should not fail... it should default to the best locale it can.

`DatePicker` shouldn't fail, it looks like it[ already defaults to `en`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DatePicker/DatePicker.js#L278).  Outside of the omission of `pt-br`, it seems like most of the other locales are supported. If we can ensure we are passing in the right locale, we should be able to avoid the need for extraneous fallbacks. 

Hope that helps!

**Comment by dcostantino** [comment]
Currently DatePicker can pick up a locale property (which isn't actually a full locale string standard to browsers) which only sets the language used for displaying dates as well as a dateFormat property that can be customized, but does not impact the date format input or placeholder text. An internationalized solution should not draw a distinction between the locale property and browser language. Additionally in the example of the browser language being set to en-GB its not clear how to map that to the locale used by DatePicker.

**Comment by Majavita** [comment]
@tw15egan which version of `carbon-components-react` do we need to be on to pickup `zh_tw` and do you know if there is an existing git issue opened requesting Flatpickr support of `pt-br` ?

**Comment by tw15egan** [comment]
`zh_tw` Should be included in `10.30.0`

You can request `pt-br` from Flatpickr by creating an issue [here](https://github.com/flatpickr/flatpickr/issues)

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/pull/7834 added some modifications to DatePicker allowing full locale objects to be passed in. I think it covers most of what's been requested here. We can reopen this if there are additional items to address
