### ISSUE TITLE
Dropdown component should support filter like MultiSelect.Filterable

### ISSUE THREAD

**Issue by yuecchen** [carbon-design-system/carbon#7714]
### Summary

Dropdown component should support filter like MultiSelect.Filterable.

This is for design and development

### Justification

Sometimes the candidates in a dropdown list would be very long, to support a filterable input is required for users. If it is possible for Multiselect to support filterable input, it should be possible for dropdown to do so. 

### Desired UX and success metrics

when do selection on dropdown list, the first element could be a input bar, and all dropdown list items followed.
when user input text in the input bar, the dropdown list items filtered with the input text.

### "Must have" functionality

NA

### Specific timeline issues / requests
We are going to release at March 2021. 

### Available extra resources

NA

**Comment by joshblack** [comment]
Hi there, @yuecchen! I believe this is where a [ComboBox](https://react.carbondesignsystem.com/?path=/story/combobox--combobox) would come into play. Does this work for your use-case? 👀
