### ISSUE TITLE
`ibm-table` component with checkbox input overflows page with restricted height in chrome.

### ISSUE THREAD

**Issue by pranjulps3** [carbon-design-system/carbon#7715]
# Description 

Observed the issue in Angular carbon tables that when using ibm-table component with showSelectionColumn set as true and tbody having a fixed height (scroll enabled), in chrome the table starts overflowing (works fine on FF). The overflow is due to the checkbox input having position: absolute css property enabled without the display being none. As a hack, setting the css property of bx--checkbox class (input class) to display: none works fine. This issue is only seen on Chromium based browsers.

![j5Cq7uz4vM](https://user-images.githubusercontent.com/24963104/106610496-dea34180-658c-11eb-9b9d-b6bf64e91bcb.gif)

This the issue in action. The input view is overflowing the table.

**Comment by joshblack** [comment]
Hey there @pranjulps3! 👋  Thanks so much for taking the time to make this issue.

Could you provide some steps to reproduce through the issue template, there should be a [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) link available for our template that we use (can also use the link there directly)

I don't remember if we do fixed height on tables in React but if so having an example to work with will help out a ton with figuring out how to address this issue.

Thanks!

**Comment by pranjulps3** [comment]
Hey @joshblack, Sorry for the late response but the issue stated above is related to Angular Carbon and was identified as a CSS issue by the Angular carbon team. We noticed it in one of our products the way it is shown above. I can attempt reproducing the issue in one CodeSandbox if there is one for Angular.

**Comment by joshblack** [comment]
No sweat @pranjulps3! Basically anything you can offer in terms of reproducing would help out a ton 🙏

**Comment by pranjulps3** [comment]
The IBM project that I am working on has the issue, we can sync up if you want and I can walk you through the complete issue. @joshblack

**Comment by joshblack** [comment]
@pranjulps3 would be incredibly helpful to isolate the issue in a Codesandbox. Unfortunately, when diving into product code it's hard to tell if the issue is product-related or library-related.

**Comment by pranjulps3** [comment]
Okay @joshblack , I will try and reproduce it in a sandbox in a couple of days and let you know of it. I haven't tried doing it yet so let me see If I am able to reproduce it or not.

**Comment by pranjulps3** [comment]
Unable to reproduce the issue locally, will investigate further on reproducing it. Closing the issue for now.
