### ISSUE TITLE
Range data picker doesn't disappear after clicking elsewhere on page

### ISSUE THREAD

**Issue by reedshea** [carbon-design-system/carbon#772]
## Detailed description

Clicking in to the start or end date pickers works fine - a dropdown showing the current month appears, and clicking outside of that dropdown causes it to disappear.

If I click on the calendar icon to the right of the date pickers, though, the dropdown shows up and then remains. Only by clicking in to the date selector and then on the page background can I make the dropdown go away.

I'm using Chrome 66.0.3359.139 on Mac OS X 10.13.3, viewing the example code here: http://www.carbondesignsystem.com/components/date-picker/code

## Steps to reproduce the issue

1. Click on the calendar icon to the right of the date pickers
2. Click to try and dismiss the dropdown box

## Additional information
* Screenshot:![image](https://user-images.githubusercontent.com/4605293/40074907-f941a6de-5848-11e8-9afd-df85bb588dcd.png)
* Screen capture in ZIP file: [Carbon Date Picker Bug.zip](https://github.com/carbon-design-system/carbon-components/files/2006155/Carbon.Date.Picker.Bug.zip)

**Comment by asudoh** [comment]
Thanks @reedshea for reporting! Will see if there is a simple fix for that - Meanwhile if you have an idea to fix feel free to contribute!
