### ISSUE TITLE
FluidForm specification and compatibility with input components

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#7737]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`
- [x] {`carbon-components-svelte`}

## Detailed description

Where is the behavior and functionality of `FluidForm` specified? I saw it implemented in the React and Svelte packages but it is not mentioned anywhere in the docs.

I found that the `Select` component has a broken layout when using in a `FluidForm` in both of these packages (https://github.com/IBM/carbon-components-svelte/issues/502)

So, is that supposed to work and if not, what is the purpose of `FluidForm` if it does not support all basic input components?

## Steps to reproduce the issue

1. Add a `Select` as a child of `FluidForm`.
2. Set `labelText` of `Select` and add `SelectItem` children to see the overlapping texts.

[codesandbox](https://codesandbox.io/s/brave-newton-qstu5)

## Additional information

![image](https://user-images.githubusercontent.com/834235/106809632-3369b980-666c-11eb-9ead-2d581cfac761.png)

**Comment by tw15egan** [comment]
Hey there @brunnerh, unfortunately, FluidForm hasn't been fully developed as of yet and only supports `TextInput`. 

The issue containing all the design specs can be found here https://github.com/carbon-design-system/carbon/issues/5416

**Comment by brunnerh** [comment]
@tw15egan Oh, so it is simply a work in progress. Thanks!
