### ISSUE TITLE
Number Input doesn't return right value

### ISSUE THREAD

**Issue by AshwinTayson** [carbon-design-system/carbon#7742]
## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If the <NumberInput /> has "min" value and "max" value and you enter a range beyond them, then the value gets reset within the range. But the value returned in the onChange handler is still the invalid value.

> Is this issue related to a specific component?

Yes, NumberInput

> What did you expect to happen? What happened instead? What would you like to see changed?

If max={10} and you type 25, the component will display 10 but event.target.value or event.imaginaryTarget.value returns "25" instead of "10"

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

7.25.0

## Steps to reproduce the issue

1. Create component with <NumberInput min={1} max={10} />
2. Type 25 into the component
3. In the component the value will reset to 10 because that the max value. But event.target.value or event.imaginaryTarget.value still returns "25".

> Please create a reduced test case in CodeSandbox
> - React:
>   https://codesandbox.io/s/quirky-snyder-13819

**Comment by tw15egan** [comment]
Does the input need to be controlled? As a workaround, you could keep it uncontrolled and use `invalidText` to provide an error message when the numbers are outside of the min/max https://codesandbox.io/s/kind-northcutt-1ohgv?file=/src/index.js

Otherwise, you may need to handle number validation in your `onChange` function to set the state to the `min` / `max` values if the number entered is above or below those numbers

**Comment by AshwinTayson** [comment]
I will add the validation in onchange. But don't you think the value returned and the value displayed in the component should be the same?

**Comment by joshblack** [comment]
Unfortunately, I think for the uncontrolled variant the behavior mirrors what the native behavior is for this input. In other words, if you have an `input` with `max` and `onChange` the number input will emit the onChange event for numbers greater than that max.

Hope this helps!
