### ISSUE TITLE
Interacting with selects on DataTable on Chrome causes the page to disappear

### ISSUE THREAD

**Issue by JensenAlexander** [carbon-design-system/carbon#7744]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We have a DataTable with radio selects in a modal. When we select a row, the table and the rest of the content in the modal will disappear. This only occurs while using chrome. Testing the table with Safari and FireFox results in the correct behavior.

Using Chrome before Select:
![image](https://user-images.githubusercontent.com/29494579/106958997-1a164b00-6708-11eb-8203-18cefa43ba46.png)

Using Chrome after Select:
![image](https://user-images.githubusercontent.com/29494579/106956384-82632d80-6704-11eb-9ad1-eb6e23a26692.png)

Using Safari (desired results):
![image](https://user-images.githubusercontent.com/29494579/106956615-da9a2f80-6704-11eb-9a9a-3bf73da4f48c.png)

> Is this issue related to a specific component?

DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the behavior to be like the behavior in the third screenshot.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

7.26.0

Not sure if it is related or will help with this issue, but if you go to https://react.carbondesignsystem.com/?path=/docs/datatable-filtering--usage on Chrome and click the gear icon on the right side of the table, then it produces something similar so what I think is happening with our table.

**Comment by tw15egan** [comment]
I believe this is a similar issue to https://github.com/carbon-design-system/carbon/issues/7340 and was just fixed via https://github.com/carbon-design-system/carbon/pull/7698

Can you try updating to `7.28.0`/`10.28.0` and see if the issue still exists ?
