### ISSUE TITLE
Select or Dropdown with type ahead function or search

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#7748]
### Summary

Support of type ahead or search function
 
### Justification

Provide the business reasons for this request.

### Desired UX and success metrics

 The user can type words into select or dropdown to filter data.

**Comment by emyarod** [comment]
does the [filterable multiselect](https://carbon-components-react.netlify.app/?path=/story/multiselect--filterable) or [combobox](https://carbon-components-react.netlify.app/?path=/story/combobox--combobox) help with your use case?

**Comment by biapar** [comment]
Yes. Filterable help me. I suggest that you update the documentation on the site because people like me start from there.
Thanks.

**Comment by emyarod** [comment]
awesome! and for future reference the filterable multiselect is captured in the documentation here https://www.carbondesignsystem.com/components/dropdown/usage#multiselect

**Comment by biapar** [comment]
Ops... I’m visit every days your site to buil a dashboard for a project, but I did not seen that. Sorry.
