### ISSUE TITLE
CarbonTag component has incorrect focus style

### ISSUE THREAD

**Issue by andreavelner** [carbon-design-system/carbon#7749]
- [x] `CarbonTag`

## Detailed description

> Describe in detail the issue you're having.
I was working on the Cloud PAL TagList component ( https://pages.github.ibm.com/ibmcloud/pal/components/tag-list/code/) where I had to fix various incorrect focus styles. 
But I had a problem with the `pal--tag-list--tag-counter` element - the focus style is incorrect, the div which contains the element is bigger in focus style. If I click on the item, it is okay but as soon as I go between the different tabs with `Tab` it will not work.

> Is this issue related to a specific component?
CarbonTag component

> What browser are you working in?
Latest Chrome, Safari and Mozilla Firefox

## Steps to reproduce the issue

1. go to https://pages.github.ibm.com/ibmcloud/pal/components/tag-list/code
2. scroll down to the Tag List
3. click on the first Tag (i.e. the one labelled "test:tag")
4. notice the nice blue "pill-shaped" focus outline style
5. now press the Tab key until you get to the "+4" tag
6. notice that it has an incorrect square styling and it highlights the outer div (also it's a square focus, not a rounded one)

## Additional information

How it should look like in every focus:
<img width="272" alt="Screenshot 2021-02-05 at 14 27 50" src="https://user-images.githubusercontent.com/68517736/107039754-953a3880-67be-11eb-9541-cca2cd581134.png">

How it looks like when I hover over the outer div and click on it:
<img width="272" alt="Screenshot 2021-02-05 at 14 28 39" src="https://user-images.githubusercontent.com/68517736/107039829-b1d67080-67be-11eb-8d39-984c0bf9ee0f.png">

How it looks like when I reach the tag using the Tab key:
<img width="154" alt="Screenshot 2021-02-05 at 14 29 04" src="https://user-images.githubusercontent.com/68517736/107039877-bdc23280-67be-11eb-88ff-5c5d94dd556e.png">

**Comment by emyarod** [comment]
this seems to be an issue with the Cloud PAL library. the focus outline you are seeing is from the tooltip trigger

**Comment by andreavelner** [comment]
@emyarod yes the third picture is because of the tooltip trigger but it should be the same as the first one since the same style is applied to both of them. The second picture is the one why I originally opened the issue, that's how it looked like.

**Comment by emyarod** [comment]
the second picture is directly caused by PAL styles

![image](https://user-images.githubusercontent.com/8265238/107082463-d1b76580-67b9-11eb-8f16-008a043be689.png)
