### ISSUE TITLE
Text area bug

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#775]
## Detailed description

When changing the height of the text area I realized you can actually shrink it past the initial height of the original area. You can shrink it even smaller than the height of a traditional text input.

> Is this issue related to a specific component? 

Text Area.

> What did you expect to happen? What happened instead? What would you like to see changed?

When shrinking the text area after expanding it, I expected it to only shrink back to the original size of the text area. The size it was when I first encountered it.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

Seen on the carbon website > which I believe is on 8.18.16

## Steps to reproduce the issue

1. Resize text area so its taller
2. Resize text area so its shrinks, smaller than initial height

## Additional information

<img width="598" alt="screen shot 2018-05-14 at 4 29 41 pm" src="https://user-images.githubusercontent.com/29312997/40130936-11bb12a8-58fe-11e8-9b2a-bcaf9dc1cbc6.png">

**Comment by alisonjoseph** [comment]
I don't believe we have any control over this with the default browser resize property. Our only other option would be to set it to none by default or implement a javascript fix, which I believe would be overkill for this. 

`resize: none|both|horizontal|vertical|initial|inherit;`

**Comment by tw15egan** [comment]
Agree with @alisonjoseph, this is the default HTML behavior for `textarea` and adding any other features would require javascript
