### ISSUE TITLE
Toggle buttons (active/pressed state)

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#7757]
### Summary

Buttons should allow for an active/pressed state to indicate a feature/function/option is turned on or off, effectively working as a toggle.

### Justification

A big use case for this is for icon-only buttons, for example to indicate text formatting, sidepanel statuses or options:

**Examples**

Keynote
![image](https://user-images.githubusercontent.com/28265588/107227693-01fe3e80-6a1c-11eb-9f88-f5bd247c54a6.png)

Sketch
![image](https://user-images.githubusercontent.com/28265588/107227726-0c203d00-6a1c-11eb-9165-feba958e09a0.png)

VSCode
![image](https://user-images.githubusercontent.com/28265588/107227849-3245dd00-6a1c-11eb-8082-c6fde34940c6.png)

Slack
![image](https://user-images.githubusercontent.com/28265588/107228051-7a64ff80-6a1c-11eb-9f32-d645ec4c2751.png)

Spotify
![image](https://user-images.githubusercontent.com/28265588/107228218-b009e880-6a1c-11eb-8b77-cc39b6b18ec5.png)

### "Must have" functionality

A prop for the button component (like `active`, `toggled`, `pressed` or something like this) to enable and disable the respective styling.
The `aria-pressed` attribute must be set accordingly (https://www.w3.org/TR/wai-aria-practices-1.1/#button, https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#toggle_buttons)

### Available extra resources

Quick exploration with the [text toolbar pattern](https://www.carbondesignsystem.com/patterns/text-toolbar-pattern):
![image](https://user-images.githubusercontent.com/28265588/107228727-4938ff00-6a1d-11eb-9354-5659aeef8b61.png)

From other libraries:
- [Toggle button on Material Design](https://material.io/components/buttons#toggle-button)
- [Toggle button on FluentUI](https://developer.microsoft.com/de-de/fluentui#/controls/web/button) (last example)
- [Selected button on Atlassian Design System](https://atlassian.design/components/button/examples#selected)
- [Dual stateful button on Lightning Design System](https://www.lightningdesignsystem.com/components/buttons/#Dual-Stateful-Button)
- [Toggle button on Bootstrap](https://getbootstrap.com/docs/5.0/components/buttons/#toggle-states)

I could submit a PR for this if the proposal is approved and the visual specification / color token to use is defined.

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by aagonzales** [comment]
Yup, I think this is something we would want to add either to the icon only ghost button or as a new component. 

There is also an issue open for icon only content switcher https://github.com/carbon-design-system/carbon/issues/6982

**Comment by mjabbink** [comment]
Totally think we should add this.

**Comment by tw15egan** [comment]
Closing as resolved with #7900 and #7784. Feel free to reopen if we need to take any more action
