### ISSUE TITLE
V9: Deprecate search icons

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#776]
## Overview
We are deprecating the filter and organization (grid/list) buttons from search. They can be added in by team in conjunction with search as necessary. We do not see them being used enough in product to continue including them in the component.

**Comment by alisonjoseph** [comment]
@tay-aitken  should we move this to carbon/issues to make sure it gets tracked in sprint planning?

**Comment by tay-aitken** [comment]
Yeah that would be great! I was going to bring it up yesterday day but then it got moved. Did it by any chance get sized? @alisonjoseph

**Comment by alisonjoseph** [comment]
Not yet, Sprint planning got moved to Monday because zenhub was down this morning.

**Comment by tay-aitken** [comment]
Got it, thanks, Ill move it now.
