### ISSUE TITLE
Dropdown filter on data table

### ISSUE THREAD

**Issue by rafaelamascaro-star** [carbon-design-system/carbon#7766]
### Summary

Include a dropdown in a data table row.

### Justification

Our project needs to filter columns based on information there're in each row. 

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Asap deployment is target for end of March

![image (12)](https://user-images.githubusercontent.com/64613838/107421157-6393db00-6af8-11eb-9313-49e9d9fa80a0.png)

**Comment by tw15egan** [comment]
Hey there @rafaelamascaro-star! It looks like the styles work pretty well out of the box, you would just need to implement your filtering logic based on the `onChange` of the `Multiselect.Filterable` Here is an example of what I was able to get it to look like, and the accompanying change to the `DataTable-filering-story.js` [file](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/stories/DataTable-filtering-story.js#L91). This feature is unlikely to be added in time for your March release, but I hope this helps get you started

<img width="1083" alt="Screen Shot 2021-02-09 at 1 06 57 PM" src="https://user-images.githubusercontent.com/11928039/107428577-b315df00-6ad7-11eb-97b3-3e00ff3bdc77.png">

<img width="782" alt="Screen Shot 2021-02-09 at 1 08 26 PM" src="https://user-images.githubusercontent.com/11928039/107428712-e7899b00-6ad7-11eb-8834-e13b16ffc189.png">
