### ISSUE TITLE
<Select> component automatically selects the first item.

### ISSUE THREAD

**Issue by AshwinTayson** [carbon-design-system/carbon#7781]
## What package(s) are you using?

- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If a **Select** component is created dynamically and you pass undefined or null it always select the first item by default. But the value of the first item is not updated in the **Select** component.

> Is this issue related to a specific component?

**Select**

> What did you expect to happen? What happened instead? What would you like to see changed?

First item should not be selected by default

> What browser are you working in?

Latest Chrome

> What version of the Carbon Design System are you using?

Latest Carbon

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/awesome-turing-jyqu2?file=/src/index.js

**Comment by AshwinTayson** [comment]
This is the bahaviour for normal select html tag as well. I guess this can be improvement that takes in a boolean, selectFirstOption is true by default and then we can make it false

**Comment by tw15egan** [comment]
As you said, this is the default behavior of the `Select` element in HTML. However, you can modify the jsx structure like so to have a placeholder value be the first item selected:

```jsx
<SelectItemGroup label="Choose an option">
   <SelectItem
      disabled
      hidden
      value="placeholder-item"
      text="Choose an option"
   />
</SelectItemGroup>
```

https://codesandbox.io/s/objective-knuth-vfm97?file=/src/index.js


Let me know if that resolves your issue 👍
