### ISSUE TITLE
add "breakpoints" property to expressiveParagraph01

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#7786]
### Summary

Unlike other type tokens with breakpoint values, the [`expressiveParagraph01` token does not contain a "breakpoints"](https://github.com/carbon-design-system/carbon/blob/master/packages/type/src/styles.js#L237) property. Instead, "lg" and "max" exist as top-level keys.

I'd like to request that a "breakpoints" field be added (which should not be a breaking change).

### Justification

This would make it easier to use the package programmatically.

My current use case is that I need to programmatically create type values using the `fluid` method from `@carbon/elements`.

Example:

```js
import * as elements from "@carbon/elements";

const fluid = elements.fluid(elements.expressiveParagraph01)

console.log(fluid);
```

**Current output:**

```js
{
  fontSize: '1.5rem',
  fontWeight: 300,
  lineHeight: 1.334,
  letterSpacing: 0,
  lg: { fontSize: '1.75rem', lineHeight: 1.29 },
  max: { fontSize: '2rem', lineHeight: 1.25 }
}
```

**Expected output (abridged):**

```js
{
  fontSize: '1.5rem',
  fontWeight: 300,
  lineHeight: 1.334,
  letterSpacing: 0,
  '@media (min-width: 82rem)': {
    // ...
  }
}
```

**Comment by tw15egan** [comment]
Makes sense, especially since we have that property in the `scss` [file](https://github.com/carbon-design-system/carbon/blob/master/packages/type/scss/_styles.scss#L306)
