### ISSUE TITLE
Announce selected item in ComboBox

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#7787]
@dakahn brought up in #7777 a great point that the options that are selected do not indicate that they are selected. We should annotate these options either by adding hidden text or labelling the "selected" icon (aka the checkmark) that is used to visually communicate the option that is selected.

**Comment by carmacleod** [comment]
This would add a lot of verbosity, and some screen readers already do say "selected", so you would be duplicating that.
In a single-select listbox (such as the one in a combobox), the currently focused item is the selected item, so hearing "selected" on every down arrow is something that screen reader users would want to turn off anyhow. :)
So please don't do this.

**Comment by joshblack** [comment]
Sounds good @carmacleod!
