### ISSUE TITLE
Table headers hover state is too narrow

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon#7791]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-components-angular`

Not affected:
- [x] `@carbon/vue`

## Detailed description

> Describe in detail the issue you're having.
Table headers having no or not enough spacing to the left when hovering. It is quite different over all the versions and use cases

### [Vanilla JS](https://the-carbon-components.netlify.app/?nav=data-table) (Select)
![image](https://user-images.githubusercontent.com/3808948/107754854-5b1ee880-6d22-11eb-8f40-959f13181657.png)
**8px instead of 16px**

### [React](https://react.carbondesignsystem.com/?path=/story/datatable--usage)
![image](https://user-images.githubusercontent.com/3808948/107755051-99b4a300-6d22-11eb-90ef-121771d8d762.png)
**0px instead of 16px**

### [Angular](https://angular.carbondesignsystem.com/?path=/story/components-table--basic)
![image](https://user-images.githubusercontent.com/3808948/107755190-c9fc4180-6d22-11eb-8b75-639a45a9a871.png)
this is good, but in [other uses cases](https://angular.carbondesignsystem.com/?path=/story/components-table--with-expansion) it is still broken:
![image](https://user-images.githubusercontent.com/3808948/107755405-0b8cec80-6d23-11eb-9b14-5f6797a63450.png)
**0px instead of 16px** - this is a custom header, but in the [next use case](https://angular.carbondesignsystem.com/?path=/story/components-table--with-dynamic-content) with the same "custom header" is fine again

#### [Vue](http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--name-only-sortable)
![image](https://user-images.githubusercontent.com/3808948/107755935-c0270e00-6d23-11eb-9c0e-61c099cf5946.png)
**this is good**

> Is this issue related to a specific component?

- [x] `DataTable`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Table headers should have 16px to left as described here:
https://www.carbondesignsystem.com/components/data-table/style#columns
and shown here:
https://www.carbondesignsystem.com/components/data-table/usage#sorting
![Hover spec](https://www.carbondesignsystem.com/static/fe75eed08eed65bfef928f8108c26bea/3cbba/datatable-sorting.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

- `carbon-components` : 10.28.0
- `carbon-components-react` 7.28.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Knowledge Catalog
No ship or release dates are effected by this

## Steps to reproduce the issue

1. Open the links
2. Hover over column header

## Additional information

N/A

**Comment by emyarod** [comment]
this should be resolved in #7726

**Comment by ConradSchmidt** [comment]
Oh sorry for the duplicate, I searched only in open issues...
I guess this fixes the react version, do you think it will resolve the others (vanilla and angular) as well? Or breaking the vue one to have 32px after the change? In vanilla there was a padding of 8px, not like the 0px as in react, maybe worth checking this out.
