### ISSUE TITLE
[Combobox] Allow item id to be integer

### ISSUE THREAD

**Issue by jonguenther** [carbon-design-system/carbon#7792]
### Summary

In `ComboBox` allow the `id` of an item to be of type `integer` additionally to `string`.

### Justification

Due to API changes, I am now getting numerical ids for elements. Passing these ids into combobox will cause following error: 
```
downShiftSelectedItem[currentId].trim is not a function
```

To circumvent the problem, I could parse the numbers to string, however, on callback I would then have to transform the ids back to integer. This would be doable using a wrapper for the component, but I think it'd be best if this could be natively supported by the component itself.

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by jonguenther** [comment]
Thanks for your reply @emyarod. Turns out it actually is an issue with `carbon-addons-iot-react` as seen in this [Stackblitz](https://stackblitz.com/edit/carbon-dummy-8mmckh?file=components%2FComboBox.jsx).

**Comment by jonguenther** [comment]
Created https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2041 for this issue.
