### ISSUE TITLE
How to perform validation for Radio Button component

### ISSUE THREAD

**Issue by dhebert-dev** [carbon-design-system/carbon#7795]
We are needing to perform validation on the Radio Button similar to how it is done for the Select Component where a red box will form around the element and red warning text will appear. I notice in the React Storybook that there is no invalid parameter for Radio. Is there no way to perform form validation for Radio Buttons just like it is performed for Select components? Thanks.

**Comment by emyarod** [comment]
you would need to add your own validation logic and probably just toggle the `invalid` prop on the `FormGroup` that you wrap your Radio Buttons with

**Comment by dhebert-dev** [comment]
Thanks. I attempted to pass in the invalid={true} prop to the formGroup that wraps the RadioGroup component as a test and it is not rendering the red outline like how the Select component does when given the invalid={true} or invalid={CUSTOM_VALIDATION_FUNCTION_CALL} prop. I am using similar custom logic that I made for the Select component which does work.
