### ISSUE TITLE
TileGroup - Allow for passing of HTML elements in addition to Carbon Tiles into a TileGroup

### ISSUE THREAD

**Issue by 3dfoster** [carbon-design-system/carbon#7797]
### Summary

Any element passed to the `<TileGroup>` component is rendered as a Carbon Tile. This prevents customizing the contents of the `<fieldset>` HTML element that gets rendered on the page:

<img width="485" alt="Screen Shot 2021-02-12 at 1 49 33 PM" src="https://user-images.githubusercontent.com/13704150/107815611-3bdf8580-6d39-11eb-830c-f9e28f894011.png">

### Justification

Allowing for the ability to add traditional HTML elements to the `fieldset` is ideal because it allows us to group elements underneath the fieldset's `legend` header, making it more WARIA compliant. 

As an example, our page currently renders like so:
```html
<h3>Scope</h3>
<p>...</p>
<fieldset>
  <legend style="display:hidden">Scope</legend>
</fieldset>
```
where we must hide the `legend` element to have the page render properly.

Additionally, this feature would bring us into compliance with the w3 spec for `fieldset`, which allows for "flow content" elements (like `<p>`) to exist inside `fieldset`: https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element.

### "Must have" functionality

Being able to add reasonable HTML elements to the TileGroup component.

### Specific timeline issues / requests

N/A

### Available extra resources

A PR has been created for this issue: https://github.com/carbon-design-system/carbon/pull/7798

**Comment by dakahn** [comment]
Flow content (like a `p` element) is allowed as a descendant of a `<fieldset>` tag. Worth noting here is that we'll need to be prescriptive about exactly what's allow to be embedded here as non [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content) could create problems from an accessibility tree standpoint. 

With _that_ said, I also assume this will require some design consideration @carbon-design-system/design

**Comment by abbeyhrt** [comment]
@3dfoster Any updates one the related PR?  I'm not sure how this makes TileGroup more WARIA compliant, are there any documents or explanations you could provide to explain the accessibility aspect?
