### ISSUE TITLE
[Toggle]: doesn't display label when we use it in the compact size (size="sm")

### ISSUE THREAD

**Issue by HafidZiti** [carbon-design-system/carbon#7803]
## Packages
"carbon-components": "10.26.0",
"carbon-components-react": "7.26.0",

## Detailed description
The toggle component doesn't display its label when is used in the compact size

- Standard size

![image](https://user-images.githubusercontent.com/24605755/107971914-5cb30f80-6fb3-11eb-892d-84fefeb4ec5c.png)

- Small size

![image](https://user-images.githubusercontent.com/24605755/107972017-85d3a000-6fb3-11eb-9bf4-0466bde752bf.png)

[CodeSandbox](https://codesandbox.io/s/modest-shannon-lldg4?file=/index.js)

**Comment by emyarod** [comment]
this should be resolved by https://github.com/carbon-design-system/carbon/pull/7752
