### ISSUE TITLE
Pagination component wider than 100% wide in Chrome, Edge

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon#7820]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The Pagination component is wider than 100% now in Chrome and Edge. If it's in a region that can scroll then there is always a horizontal scrollbar present. This is related to the Next/Previous Page tooltips somehow. In older releases there were no tooltips on those button and I didn't see this problem.

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome, Edge both show a similar problem.
NOT see in Firefox.

> What version of the Carbon Design System are you using?

carbon-components-react 7.17 - 7.27 (at least)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

ELM

> Please create a reduced test case in CodeSandbox

In Chrome a scrollbar appears at the bottom of the frame. You can scroll 1px. Hover over the Next Page button and the scrollbar disappears. (In a real application this sometimes gets into an endless loops of showing and hiding the scrollbar, but I can't reproduce that with a simple case so far.)

In Edge the scrollbar appears just under the component in this example.

https://codesandbox.io/s/100-width-pagination-sim26

**Comment by tw15egan** [comment]
PR: #7863
