### ISSUE TITLE
UI Shell Left Sidenav style: How to?

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#7829]
How to change the style of left sidenav? It not reflect the theme.
Thanks.

**Comment by tw15egan** [comment]
@biapar the UI shell does not currently support theming but is being tracked and will eventually be added

https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-764805539

https://github.com/carbon-design-system/carbon/issues/5302

https://github.com/carbon-design-system/carbon/issues/4839

Hope that helps!
