### ISSUE TITLE
vue - @carbon/icon-builder-helpers cause compiler warning on vue 2.x due to vue 3.x adaptation

### ISSUE THREAD

**Issue by oltdaniel** [carbon-design-system/carbon#7833]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

The line I'm talking about here can be found [in commit `aebf79e` line 9](https://github.com/carbon-design-system/carbon/commit/aebf79e433239061d76ab78dc1e8b8911de81d1f#diff-be769708c4f1685c1044e00822eb6509939573db0bc3ac5271780eeea47a1641R9) which causes an import warning when using vue 2.x. It will work fine for vue 3.x as this function has the intended use in vue 3.x but vue 2.x is still the goto version. Replacing this with:
```diff
- import { h } from 'vue';
+ const {h} = require('vue');
```
would fix the issue due to the non-evaluated export tree. `h` will stay `undefined` due to the `require` function definition as it is supposed to do.If I'm using the package in a wrong way, I'm looking forward to be corrected. Code example can be found below.

Caused error message:
```bash
# [...]
 warning  in ./node_modules/@carbon/icons-vue/es/utils-7a44a5de.js

export 'h' was not found in 'vue'
# [...]
```

## Steps to reproduce the issue

1. Create a new vue project.
2. Add `@carbon/vue` and `@carbon/icons-vue`.
3. Use the below `main.js`.

## Additional information
```js
import Vue from 'vue'
import 'carbon-components/css/carbon-components.css'
import CarbonComponentsVue from '@carbon/vue/src/index'

Vue.config.productionTip = false

Vue.use(CarbonComponentsVue)

import { CarbonIconsVue } from '@carbon/icons-vue'
import AppSwitcher20 from '@carbon/icons-vue/es/app-switcher/20'

Vue.use(CarbonIconsVue, {
  components: {
    AppSwitcher20
  }
})

import App from './App.vue'

new Vue({
  render: h => h(App),
}).$mount('#app')
```

**Comment by joshblack** [comment]
cc @lee-chase

**Comment by joshblack** [comment]
@oltdaniel @lee-chase I through up a PR in #7862 that might address this problem, just wanted to put it on your radar 👀

**Comment by lee-chase** [comment]
Unable to re-create here https://github.com/lee-chase/vue-2-carbon-icon-test not sure why.

**Comment by oltdaniel** [comment]
@lee-chase 

Probably because you haven't used my example code from above, which requires the import of utils. If you import them directly as you did in your example, the utils won't be importet.

**Comment by lee-chase** [comment]
> @lee-chase
> 
> Probably because you haven't used my example code from above, which requires the import of utils. If you import them directly as you did in your example, the utils won't be importet.

You'll have to forgive me but I really didn't expect the import of Bee via the index file to make a difference. Each of the components do pull in utils but specifically `import { c as createSVGComponent } from '../utils-7a44a5de.js';` instead of `import './utils-7a44a5de.js';`
