### ISSUE TITLE
Pagination - How to disable pageSelect only (Keep the Next/Previouse buttons)

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#7836]
How to disable the Page Select only without disabling the Next/Previous buttons in Pagination component?

My API doesn't support get a specific page, I can go only forward/backward.

**Comment by tw15egan** [comment]
You can use `pageInputDisabled`, but this has been deprecated and will be removed in v11. In V11 we also hope to formalize the `unstable_Pagination` component that is more composable (https://react.carbondesignsystem.com/?path=/story/unstable-pagination--with-a-page-selector) which will allow you to disable the elements seperately.

Hope that helps!
