### ISSUE TITLE
Tabs Component

### ISSUE THREAD

**Issue by pnadarajan** [carbon-design-system/carbon#7842]
- [ ] `carbon-components`
- [ ] `carbon-components-react` 10.23.0
- [ ] 

## Detailed description

We are using the tabs component in VPC UI. We have an issue related the individual tab strings are getting cut off. Especially with other language translations text.
The Idea is to use the tabs component is to avoid any css overwrites from our code. 
As per the screenshot attached, we have more space to accommodate tab string. But looks like it is truncated and uses a fixed width. If it reaches the max width then it can be truncated the string as it appears now. We would like to have solution from the components level instead of custom changes from our code.

<img width="1244" alt="2021-02-15_14-39-26" src="https://user-images.githubusercontent.com/79284896/108424116-c119dd00-7206-11eb-9939-33ed7e6c9377.png">

**Comment by tw15egan** [comment]
@pnadarajan by default, the tabs have a `width: 10rem` set on them. The `Tab` container itself has a `width: 100%` set on it, so you can just set `width: auto` or `width: 15rem` etc.. on `.bx--tabs--scrollable .bx--tabs--scrollable__nav-link`. 

We have a default width set on the tabs, but it is acceptable for teams to override this width to fit their use case.

Just curious, what type of prop would you expect the Carbon library to add to handle this use-case?
