### ISSUE TITLE
Create Russian Ruble icon

### ISSUE THREAD

**Issue by AndrisJefimovs** [carbon-design-system/carbon#7848]
### Summary

I wanted to use Carbon icons, but found out, there is no Russian Ruble icon, which I need.

I would like to have that icon, therefore I have created one and would like to contribute.

### Justification

Improve the internationalization.

---

It would be nice if someone could assign me to this.

**Comment by joshblack** [comment]
Going to close this out as it seems to be tracking in the Brand project on GHE 👀  https://github.com/carbon-design-system/carbon/pull/7853#issuecomment-782348622
