### ISSUE TITLE
Optimise skeleton state animations

### ISSUE THREAD

**Issue by grahamharper** [carbon-design-system/carbon#7850]
### Summary

Optimise the performance of skeleton state animations by refactoring to use `transform`.

### Justification

Carbon skeleton states animate CSS layout properties `left` and `right`, which trigger a browser repaint on the main thread.

Skeleton with Paint Flashing turn on in Chrome DevTools:
![skeleton-paint-flashing](https://user-images.githubusercontent.com/2853295/108523552-f76a6180-72c5-11eb-85cd-a9b8edf87eba.gif)

Intensive JS operations can cause CSS animations to stall. Animating `transform` instead along with the `will-change` property will allow modern browsers to optimise the animation using the Composite layer.

https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance

> - Where you can, stick to changing transforms and opacity.
> - Use `will-change` to ensure that the browser knows what you plan to animate.

### Desired UX and success metrics

Smooth, uninterrupted, performant animations at a high framerate. Maintain 60fps animation.

Here's an example Codepen:
https://codepen.io/grahamharper/pen/WNoOBOq

New skeleton animation doesn't cause repaint:
![skeleton-with-transforms](https://user-images.githubusercontent.com/2853295/108523723-297bc380-72c6-11eb-8ee6-96cf47afcedb.gif)

### "Must have" functionality

Maintain existing functionality.

### Specific timeline issues / requests

Ideally by early April 2021.

### Available extra resources

We have a developer who can work on this and will try submit an initial PR shortly.

**Comment by tw15egan** [comment]
This is great and definitely something we've been wanting to improve upon! Looking forward to the PR
