### ISSUE TITLE
Low contrast notification text uses the incorrect token when using the dark theme with CSS variables

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#7857]
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

After upgrading to carbon-components v10.29.0, the text color for a low contrast notification uses the `$text-01` token when I believe it should be `$inverse-01`.

**Note: This only happens when using a dark theme combined with CSS custom properties.** I've tested the g90/g100 themes without custom CSS properties and they work as expected.

The result is that the text is not legible:

<img width="356" alt="Screen Shot 2021-02-19 at 5 13 11 PM" src="https://user-images.githubusercontent.com/10718366/108577603-7c5d7700-72d6-11eb-83fe-128a4a8a0383.png">

When inspecting the styles using Chrome DevTools, the selector uses the `$text-01` token but falls back to the correct `$inverse-01` value (`#161616`)

<img width="280" alt="Screen Shot 2021-02-19 at 5 13 26 PM" src="https://user-images.githubusercontent.com/10718366/108577650-9d25cc80-72d6-11eb-8667-efb70dc69180.png">

## Steps to reproduce the issue

- Enable CSS custom properties and use a dark theme (g90 or g100)

Unfortunately, I don't have an isolated CodeSandbox, but this bug can be observed when comparing two snapshots of the Carbon Svelte documentation website. The only discernible difference between the snapshots is upgrading from `carbon-components` v10.28 to v10.29:

- Expected result using carbon-components@v10.28: https://carbon-components-svelte-4hwsgvakp.vercel.app/components/ToastNotification#low-contrast
- Unexpected result using carbon-components@v10.29: https://carbon-components-svelte-pavryf5kk.vercel.app/components/ToastNotification#low-contrast

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/pull/7808, https://github.com/carbon-design-system/carbon/pull/7801

**Comment by emyarod** [comment]
this should be resolved https://carbon-components-react.netlify.app/?path=/story/notifications--inline

**Comment by metonym** [comment]
Thank you, following the updated guidance in #7808 resolves my issue.
