### ISSUE TITLE
[icons] add a "location--filled.svg" in the travel category

### ISSUE THREAD

**Issue by alexojegu** [carbon-design-system/carbon#7858]
### Summary

In the category "Travel" add a new icon "location—filled.svg".

### Justification

In the "Travel" category, all the "location--*.Svg" icons have a filled version, except for the main "location.svg". And to use it over a map, the filled version seems better.

**Comment by tw15egan** [comment]
cc @conradennis @dudley-ibm

**Comment by dudley-ibm** [comment]
@tw15egan I really only handle pictograms to-date, and I don't believe we'd do a solid version of the location pictogram. @conradennis should be able to address this for you in the icons.

**Comment by alexojegu** [comment]
Yeah, I see a [location--filled.svg](https://github.com/carbon-design-system/carbon/blob/main/packages/icons/src/svg/32/location--filled.svg)
