### ISSUE TITLE
Support for custom css variables in javascript theme tokens

### ISSUE THREAD

**Issue by ashharrison90** [carbon-design-system/carbon#7902]
Hi. I've been using the experimental feature flag to enable custom css variables in theming as added by this PR: https://github.com/carbon-design-system/carbon/pull/4100

This works really well!

At the moment, we're considering switching to something like `styled-components`. I was wondering if there are any plans to support custom css variables in the javascript tokens, or what the recommended approach for using the javascript tokens is. I can see how to import the individual tokens from each theme, but I don't see a parallel between that and setting an overall theme like you can in scss?

Thanks!

**Comment by joshblack** [comment]
Hi there, @ashharrison90! 👋 

We'll definitely want to get this in for our next major release. Currently, we offer the tokens and their values in JS over in `@carbon/themes` but can definitely look into interop with Custom Properties. Would love any feedback/suggestions for what would work best in this space for you and your team!

**Comment by ashharrison90** [comment]
so yeah, i'm not entirely sure how the javascript tokens are intended to be consumed, and i might be missing something here... but in scss you just import the tokens and those token values are different depending on what theme you've set initially. in javascript, when you import the individual token values they're hardcoded to the white theme, and i can't see any way of changing that(?). i know you can import tokens from the themes themselves, but i think that means that if later you wanted to change theme, you'd have to change all your imports to import the tokens from a different theme. 😕 

in terms of custom properties, i think just offering a version of those tokens with custom variable support as different imports would be great, e.g. having something like:
```javascript
import { support01, support01Custom } from '@carbon/themes'
```
that would be similar to the behaviour in scss now where you have to set a feature flag to opt in to the behaviour.

**Comment by joshblack** [comment]
@ashharrison90 great points! In a React space, I think we would expect something like the following:

```jsx
import { white, g90 } from '@carbon/themes';
import { createContext, useContext } from 'react';

const ThemeContext = createContext(white);

function Theme({ children, theme }) {
  return (
    <ThemeContext.Provider value={theme}>
      {children}
    </ThemeContext.Provider>
  );
}

function useTheme() {
  return useContext(ThemeContext);
}

// Example components
function App() {
 return <Theme theme={g90}><Page /></Theme>; 
}

function Page() {
  const theme = useTheme();
  console.log(theme.support01);
  // ...
}
```

We could offer something similar for the exports, though. Or offer a method that creates the same scoping rules as you would expect in Sass.

For custom properties, definitely agreed that'd be nice. Another thing we've talked about is a dedicated entrypoint like:

```js
import { interactive01 } from '@carbon/themes/custom-properties';
```

But just having it be there on the package entrypoint would definitely be great.
