### ISSUE TITLE
Sidenav should allow extra props to be passed to the rendered component

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#7903]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Sidenav should pass additional props to the rendered component, similar to what some of the other components are doing , for example Tab: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tab/Tab.js#L165

Development effort.

### Justification

Allows for additional attributes to be passed to the component for greater control/accessibility compliance.

### Specific timeline issues / requests

Any time

### Available extra resources

I can open a PR if the proposal is accepted.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by emyarod** [comment]
passing props into the cloned sidenav child elements makes sense to me

**Comment by gptt916** [comment]
@emyarod Do you think this addition should be made across all the `SideNav{sub component}` components? or only `SideNav.js`

**Comment by emyarod** [comment]
@gptt916 I'm leaning towards only `SideNav.js` for the time being unless there is a case to be made for doing so across all sidenav sub components
