### ISSUE TITLE
Tooltip focus behavior, focusTrap not working as expected

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#7916]
## Tooltip focus behavior, focusTrap not working as expected

There are two issues here:

1.) Tooltip link is in focus state by default on tooltip open (design) 
2.) focusTrap behavior not working as expected (bug)

## What package(s) are you using?

Writing on behalf of dev, believe it is Carbon react but I can confirm if needed

## Detailed description

**1.) Tooltip link is in focus state by default on tooltip open (design)** 

- Focusing first element in a form makes sense as filling out fields is primary action and always begins with first field
- However tooltip is primarily informational. Focusing first link or action does not make sense
- Tooltip links / actions are optional and low priority because user is trying to complete primary task on page itself
- Putting the tooltip link in focus is visually distracting in general, draws user's eye away from the information that is the main point of tooltip, and suggests that the link is a primary action which it isn't
- If tooltip link appears in a text block the focus is visually disruptive

Coded tooltip on carbon site:

<img width="403" alt="Screen Shot 2021-02-22 at 3 26 20 PM" src="https://user-images.githubusercontent.com/39408106/109307505-5f5d0280-7806-11eb-8227-5ded48a2e178.png">

Some sample tooltips:

<img width="372" alt="Screen Shot 2021-02-23 at 2 35 44 PM" src="https://user-images.githubusercontent.com/39408106/109307577-7ac80d80-7806-11eb-81cc-79ad271ca7a8.png">

![a5143c80-7202-11eb-9a2f-8131c0dbc8c6](https://user-images.githubusercontent.com/39408106/109307579-7ac80d80-7806-11eb-8adb-f781b4515a9b.png)

**2.) focusTrap behavior not working as expected (bug)**

Screenshot describing issue:

<img width="872" alt="Screen Shot 2021-02-26 at 7 40 11 AM" src="https://user-images.githubusercontent.com/39408106/109307205-dfcf3380-7805-11eb-978e-4891b62bf7f4.png">

![tooltip](https://user-images.githubusercontent.com/39408106/109308015-18234180-7807-11eb-930a-b505a1b13788.gif)

It seems like focusTrap is not handling properly.

## Steps to reproduce issue

**Design where link is in focus by default:**

1. Go to carbon site
2. Click on component > tooltip > code
3. See default behavior is to have link focused

**focusTrap not handling properly**

1. See code sandbox: https://codesandbox.io/s/charming-boyd-03yvc?file=/src/index.js

**Comment by vsnichols** [comment]
From #carbon-components slack thread on this topic

<img width="389" alt="Screen Shot 2021-02-26 at 7 59 24 AM" src="https://user-images.githubusercontent.com/39408106/109309204-959b8180-7808-11eb-8820-9ceee6f81695.png">

**Comment by emyarod** [comment]
`selectorPrimaryFocus` needs to point to a focusable element, so you can focus on the link in your tooltip by updating the value of `selectorPrimaryFocus` to `.scop-desc a`

https://codesandbox.io/s/lucid-tesla-q1yl1
