### ISSUE TITLE
[Release Partner] Watson Assistant

### ISSUE THREAD

**Issue by lucasmccomb** [carbon-design-system/carbon#7933]
**What is your team's name?**

Watson Assistant

**Why would you like to join the Release Partner Program?**

To be aware of any changes to Carbon that might affect our product.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes.

**Who should we reach out to for more info?**

Slack — @ lucasm
Email — lemccomb@us.ibm.com

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
