### ISSUE TITLE
[Release Partner] <Cloud PAL>

### ISSUE THREAD

**Issue by adrianamorales** [carbon-design-system/carbon#7934]
**What is your team's name?**

Cloud PAL

**Why would you like to join the Release Partner Program?**

Cloud PAL is gearing for our next major release. Carbon 11 will be bundled and proxied in Cloud PAL 2.0, and we want the platform to upgrade at the same time. Participating in the release partner program will give us the ability to offer an experimental release for IBM Cloud early adopters. 

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

Slack handle: `@adriana` and `cloud-pal-squad` channel

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
