### ISSUE TITLE
[Release Partner] IBM Cognos Analytics

### ISSUE THREAD

**Issue by PaulJThompson** [carbon-design-system/carbon#7935]
**What is your team's name?**

IBM Cognos Analytics

**Why would you like to join the Release Partner Program?**

For our initial adoption in Cognos Analytics, Carbon was largely imposed on us. Moving forward, this needs to be a dialog so our needs can be incorporated into Carbon.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes please!

**Who should we reach out to for more info?**

paul.j.thompson on Slack
paul.j.thompson@ca.ibm.com on Email
PaulJThompson on GitHub

There are more than one Paul Thompson who works for IBM. The J is important. :)

Note that front end development organization in Cognos Analytics is large (100+ people) so I likely won't be the only one from my org.

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
