### ISSUE TITLE
[Release Partner] Watson Discovery (Tooling)

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon#7938]
**What is your team's name?**

Watson Discovery (Tooling)

**Why would you like to join the Release Partner Program?**

Preview upcoming Carbon changes and provide feedback for how those might work with our app and others.

**Are you interested in participating in biweekly feedback sessions for the release?**

> [biweekly](https://www.merriam-webster.com/dictionary/biweekly)
> 1 : occurring every two weeks : FORTNIGHTLY
> 2 : occurring twice a week

😆 

I assume you mean once every two weeks. If so, then yes.

**Who should we reach out to for more info?**

@jhpedemonte

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
