### ISSUE TITLE
Janet Willis

### ISSUE THREAD

**Issue by janetrwillis** [carbon-design-system/carbon#7947]
**What is your team's name?**

CIO Design // ERDM application

**Why would you like to join the Release Partner Program?**

I use Carbon design system on a daily basis, and I would like to be more involved. Also, interested in contributing and giving feedback.
**Are you interested in participating in biweekly feedback sessions for the release?**

Yes
**Who should we reach out to for more info?**

janetrwillis@gmail.com, Slack: janetrwillis

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
