### ISSUE TITLE
[Release Partner] IBM Cognos Analytics

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#7948]
**What is your team's name?**

Bill Guigue

**Why would you like to join the Release Partner Program?**

To be aware of, and contribute to, upcoming release changes.

**Are you interested in participating in biweekly feedback sessions for the release?**

Being aware of them would be nice, but just knowing what to review and how to contribute feedback would be enough.

**Who should we reach out to for more info?**

GitHub username: guigueb
email: william.guigue@gmail.com
Slack: Bill Guigue

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
