### ISSUE TITLE
[Release Partner] Carbon for IBM.com

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon#7959]
**What is your team's name?**

Carbon for IBM.com

**Why would you like to join the Release Partner Program?**

We are supporting many adopters that are currently on Carbon 10, plus we would need to better understand what our upgrade approach should entail, especially if this will be a major release for `Carbon for IBM.com` in the future to support this.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

jeffchew, kennylam. We may bring in others later on if that's ok.

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
