### ISSUE TITLE
[Release Partner] carbon-components-angular

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#7967]
We already chatted on slack, but filling this out for posterity 😉 

**What is your team's name?**

carbon-components-angular

**Why would you like to join the Release Partner Program?**

Getting a head start on the v11 release! 

**Are you interested in participating in biweekly feedback sessions for the release?**

Sure 👍 I'm going to loop @zvonimirfras in as well

**Who should we reach out to for more info?**

@cal-smith 😉

**Comment by joshblack** [comment]
Thanks so much for filling out the template! Excited to have you on board! 🥳
