### ISSUE TITLE
MultiSelect doesn't checkmark initialSelectedItems in dropdown menu

### ISSUE THREAD

**Issue by kylembrake** [carbon-design-system/carbon#797]
## Detailed description

The MultiSelect / MultiSelect.Filterable components have an initialSelectedItems parameter that does not checkmark the the items in the dropdown menu.

> Is this issue related to a specific component? 
MultiSelect / MultiSelect.Filterable

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect that the options I provide to initialSelectedItems would be checkmarked within the dropdown.

> What browser are you working in? 
Chrome Version 66.0.3359.139

> What version of the Carbon Design System are you using? 
"carbon-components-react": "^5.49.4"

## Additional information

https://codesandbox.io/s/yj61j6mlqx

**Comment by asudoh** [comment]
Hi @kylembrake did you mean to enter this issue to https://github.com/carbon-design-system/carbon-components-react/issues? Thanks!

**Comment by kylembrake** [comment]
@asudoh I did, my mistake. It looks like there was an identical issue created 3 days ago. I'll share my codesandbox on that issue since it's labelled as needing reproduction steps. Thanks!

**Comment by asudoh** [comment]
OK thank you for your quick reply @kylembrake!
