### ISSUE TITLE
Tabs Skeleton not rendering properly

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#7970]
Noticed while working on skeleton state performance updates.

<img width="560" alt="Screen Shot 2021-03-03 at 1 14 11 PM" src="https://user-images.githubusercontent.com/11928039/109873295-68910980-7c22-11eb-8807-f8e41d17b562.png">

@carbon-design-system/design do we have any specs for skeleton states for `Tabs`?

https://react.carbondesignsystem.com/?path=/story/tabs--skeleton

**Comment by aagonzales** [comment]
Hmm that's actually how its showing in the Sketch kit but it would be nice to have a little more details in them. Like this:

**Default tabs**:
![image](https://user-images.githubusercontent.com/11670886/109998864-a9028d00-7cdf-11eb-8e08-919435eee0a2.png)

**Container tabs**:
![image](https://user-images.githubusercontent.com/11670886/109999222-ff6fcb80-7cdf-11eb-952d-954fbc3e2506.png)
