### ISSUE TITLE
Compact Loading Spinner has a massive rotating background

### ISSUE THREAD

**Issue by vladbalanescu** [carbon-design-system/carbon#7978]
Background:
---
The compact loading spinner has a massive background and padding around just the little spinning circle. In the compact ResourcesTable, that leads to an unecessary vertical scroll bar, so the height/width of this compact loading spinner needs to be reduced.

Current workaround:
---
Increase `ResourcesTable` height from `3rem` to `3.5rem`

Visuals:
---
![Screenshot 2021-03-04 at 09 47 56](https://user-images.githubusercontent.com/16047402/109945148-ddba1880-7cce-11eb-93ec-5d556cede3dd.png)

![9afb0500-7a70-11eb-8418-912a1dd4dab2](https://user-images.githubusercontent.com/16047402/109945229-f32f4280-7cce-11eb-8fa1-8a2575ca5df8.gif)

**Comment by emyarod** [comment]
this should be resolved in https://github.com/carbon-design-system/carbon/pull/7968
