### ISSUE TITLE
'process is not defined' error in feature-flags package with 'enable-css-custom-properties'

### ISSUE THREAD

**Issue by moczolaszlo** [carbon-design-system/carbon#8007]
Hi,
We use Carbon with true `enable-css-custom-properties` variable, and with the latest version get this error after build:
```
Uncaught ReferenceError: process is not defined
    at eval (index.js?9f8b:11)
    at Module../node_modules/@carbon/feature-flags/es/index.js
```
Package versions:
```
    "carbon-components": "10.30.0",
    "carbon-components-react": "7.30.0",
```

If I downgrade back versions (10.29.0, 7.29.0), I don't get the error.
Probably this PR: https://github.com/carbon-design-system/carbon/pull/7802 ?

**Comment by bogy0** [comment]
same here

**Comment by joshblack** [comment]
Hey @moczolaszlo and @bogy0! Thanks so much for raising this. Could you share more about when you run into this error?

**Comment by bogy0** [comment]
hi @joshblack ,

we run into this issue one in our project where we use the `enable-css-custom-properties` as a custom flag and the error was present when we updated to the latest version of carbon-components and carbon-components-react as Laszlo mentioned in the issue description.

Our `index.scss` file looks like this:
```
@import '~carbon-components/scss/globals/scss/vars';

// $prefix: 'bx';
$css--font-face: true;
$css--helpers: true;
$css--body: true;
$css--use-experimental-grid: false;
$css--use-experimental-grid-fallback: false;
$css--use-layer: true;
$css--reset: true;
$css--typography: true;
$css--plex: true;
$carbon--font-display: 'swap';
$feature-flags: (
	enable-css-custom-properties: true
);

...
```

**Comment by joshblack** [comment]
@bogy0 hmm, something that's surprising is that this feature flag work is currently not a part of the Sass feature flag work. That system did not change in the update.

Most likely this issue is related to the bundler and whether or not a project uses UMD or not, I think. If you or @moczolaszlo could provide some steps to reproduce that would be awesome 🙏

**Comment by joshblack** [comment]
On our end, let me go push up a fix real quick to check on `process` instead of assuming it's defined by bundlers 👍

**Comment by alon24** [comment]
any ETA on this, I use PAL, and cannot move to latest because of this issue
