### ISSUE TITLE
Inline dropdown arrow is hidden on storybook

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/carbon#8012]
## Title line template: Inline dropdown arrow is hidden on storybook

When inspecting the storybook for [Inline Dropdown](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline), the arrow seems to be off. Don't know if it's a storybook issue or the component itself 

![Screen Shot 2021-03-08 at 12 05 50 PM](https://user-images.githubusercontent.com/12755042/110354882-a4531700-8006-11eb-89e1-6a341bceb45e.png)

## Solution
I've inspected the arrow SVG and there is no `top` CSS property assigned. 

## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

**Comment by andreancardona** [comment]
@AlexanderMelox Fixed by this PR :) 

https://github.com/carbon-design-system/carbon/pull/7990
