### ISSUE TITLE
IE 11: Basic grid functionality broken

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#802]
@rscarbon commented on [Wed May 23 2018](https://github.com/carbon-design-system/carbon-components-react/issues/914)

## Detailed description

We have two bx--cols inside a bx--row, as in this [codepen.](https://codepen.io/anon/pen/zjXLWe?editors=1100). The issue we are facing is that this does not work as expected on IE11.
 
This is the code:

![image](https://user-images.githubusercontent.com/39554441/40420889-7952bc46-5ea7-11e8-816e-be19e4590f82.png)

This is how the page appears on Chrome/Firefox:

![image](https://user-images.githubusercontent.com/39554441/40420931-9df22636-5ea7-11e8-9645-b5bf63c17815.png)

And this is how it looks on IE11:

![image](https://user-images.githubusercontent.com/39554441/40420960-b7112eaa-5ea7-11e8-8797-ec113ed2df2c.png)

We are using this version of carbon : 
``
    "carbon-components": "8.18.0",
    "carbon-components-react": "5.34.0",
``

To get the appearance on IE11 to be same as on Chrome/Firefox, we tried setting the following on IE11, for the bx--row class,
```-ms-flex-wrap: nowrap```
```flex-wrap: nowrap```

This makes the page appear as expected in IE11, but the page is no longer responsive and the columns do not stack when the page size is made small. Now responsiveness is broken in all browsers.

## Steps to reproduce the issue
1. Go to https://codepen.io/anon/pen/zjXLWe?editors=1000
2. Opening this on IE11 shows the odd behavior on the code on that browser. However, on Chrome/Firefox this works as expected. Unchecking `-ms-flex-wrap and flex-wrap` on IE11 corrects the appearance but removes responsiveness. 

---

@joshblack commented on [Wed May 23 2018](https://github.com/carbon-design-system/carbon-components-react/issues/914#issuecomment-391402094)

Hi @rscarbon! 👋 Moving this over to `carbon-components` as that is where styles live 👍

**Comment by scottvincent** [comment]
IE 11 ignores the `box-sizing: border-box` when display is flex. So it includes the padding, pushing it to the next line. A way to fix it is anywhere there is `flex-basis: 50%` you also define `max-width: 50%` This will break any flex-grow behaviour, but will give you the expected layout.

**Comment by stanislavgeorgiev** [comment]
I'm seeing the same broken behavior with @9.46.0

**Comment by stanislavgeorgiev** [comment]
There are many suggestions on IE11 quirks with flexbox on this page: https://github.com/philipwalton/flexbugs#flexbug-7

I did try the 7th one with setting `width` to the same `flex-basis` value and `flex-basis: auto`
