### ISSUE TITLE
[modal] incorrect token for body content 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#8043]
The modal body content should be `body-long-01`. Right now it is at `body-long-02` and is too big.
![Artboard](https://user-images.githubusercontent.com/43969356/110512336-ba2a1000-80ca-11eb-803f-d6d690bac73d.png)

**Comment by emyarod** [comment]
modal content already receives a style rule to make text content `body-long-01`, and the `body-long-02` styles in our story seem to be coming from the system wide rule placed on paragraphs
