### ISSUE TITLE
TM1Web and Websheets

### ISSUE THREAD

**Issue by CoriIBM** [carbon-design-system/carbon#8047]
**What is your team's name?**

TM1 Web / Websheets

**Why would you like to join the Release Partner Program?**

We are upgrading to Carbon 10

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes.  Absolutely.  100%.

**Who should we reach out to for more info?**

ryanco@us.ibm.com
Cori Ryan

**Comment by joshblack** [comment]
Thanks so much for reaching out! Super excited to have you join!
