### ISSUE TITLE
TextInput error styling

### ISSUE THREAD

**Issue by joannecl** [carbon-design-system/carbon#8052]
There may be other components in a similar situation but it would be good if there was an attribute to style the TextInput to stay the same size as a complete component when the error state is applied. Particularly with the error text below the component - if we don't need the helper text the  spacing changes a fair bit & may affect the alignment of a form.

At the moment to get around this, I'm putting an `&nbsp;` in the helperText property but this seems like a work around.

An example of the alignment issue is here: 
https://codesandbox.io/s/broken-sound-gvibw?file=/src/index.js

Thanks!

**Comment by sstrubberg** [comment]
hey @joannecl thanks for submitting this issue. Unfortunately, due to constraints with our roadmap and resource availability, we won't be able to take on your request at this time, but we'll happily review a PR if you submit one against this issue. Closing for now.
