### ISSUE TITLE
Data table on hover changing background colour from white to grey

### ISSUE THREAD

**Issue by AmirHussain93** [carbon-design-system/carbon#8055]
Hi, I have implemented a carbon component data table in my react application and somehow on hover its changing the background colour from white to grey. I am unable to stop this change. Can anyone of you help me with this ?

**Comment by emyarod** [comment]
this sounds like the default style for Carbon data tables, which you can override via CSS. if you find this is not the case, please provide some additional details on what you tried to resolve the issue as well as a reproducible test case [in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)

**Comment by AmirHussain93** [comment]
@emyarod  yes i am able to handle it now. I just figured out in Carbon data table "table cell" element has some default on hover background colour. And i was trying to give css on "table" element which was not working.

Thanks for lighting up on overriding css.
