### ISSUE TITLE
[Checkbox]: check in box is left-aligned 

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#8061]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When upgrading Cloud PAL to 10.30 and 7.30, noticed that the check in the `CheckBox` is now left-aligned instead of center. You can also see this in Carbon's storybook https://carbon-components-react.netlify.app/?path=/story/components-checkbox--checkbox. This might be intentional, so if it is feel free to close this issue! 

## Additional information

![Screen Shot 2021-03-10 at 2 58 10 PM](https://user-images.githubusercontent.com/17281178/110696765-18312300-81b1-11eb-8a30-346272a12f0b.png)

**Comment by tay1orjones** [comment]
Related https://github.com/carbon-design-system/carbon/pull/7887
