### ISSUE TITLE
Tutorial links 404'ing

### ISSUE THREAD

**Issue by ecumike** [carbon-design-system/carbon#8089]
All three tutorial links on this page are 404'ing:

https://www.carbondesignsystem.com/developing/get-started/

![image](https://user-images.githubusercontent.com/7328459/111182705-8bf27780-8585-11eb-9cb2-6fb81e0721ea.png)

**Comment by emyarod** [comment]
duplicate of https://github.com/carbon-design-system/carbon-website/issues/2178

**Comment by ecumike** [comment]
Woops, sorry.
