### ISSUE TITLE
[List] Dropdown control has a hard-coded "Open menu" and "Close menu" tooltip and not compatible with globalization 

### ISSUE THREAD

**Issue by cheer021** [carbon-design-system/carbon#8091]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

[List] List control has a hard-coded "Open menu" and "Close menu" tooltip and not compatible with globalization 

> Is this issue related to a specific component?

Dropdown control 
https://www.carbondesignsystem.com/components/dropdown/usage

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Either 
- remove the tooltips completely so consumers can pass their own string (MORE preferred) 
Or
- Read the user locale and translate the string (LESS preferred - because consumers should decide where to read the locale which can be different from browser locales) 

> What browser are you working in?

Chrome - this is a cross-browser issue

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cognos Analytics: This issue is not gating our release 

## Steps to reproduce the issue

1. Open the List control link
2. Hover over the arrow svg
3. See "Open menu"

## Additional information

![Screen Shot 2021-03-15 at 12 24 05 PM](https://user-images.githubusercontent.com/2319230/111202330-5a7bab00-8589-11eb-93cd-febe635e3ded.png)

**Comment by tw15egan** [comment]
The `ListBox` components should all accept a `translateWithId` prop that can be used to implement globalization. Here is a quick example:


```jsx
const listBoxMenuIconTranslationIds = {
  'close.menu': 'Translated Close text ',
  'open.menu': 'Translated Open text ',
  'clear.all': 'Clear all',
  'clear.selection': 'Clear selection',
};

<Dropdown
   ...
   translateWithId={(id) => listBoxMenuIconTranslationIds[id]}
/>
```

![Screen Shot 2021-03-15 at 11 36 01 AM](https://user-images.githubusercontent.com/11928039/111204157-17b6d480-8583-11eb-9230-7c5e00fa3d0b.png)

![Screen Shot 2021-03-15 at 11 40 37 AM](https://user-images.githubusercontent.com/11928039/111204695-a592bf80-8583-11eb-86b9-5ef203652fe9.png)

**Comment by emyarod** [comment]
this should already be handled by the translation IDs https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ListBox/ListBoxMenuIcon.js#L21-L24

here is an example of how to use it in the storybook

https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/MultiSelect/MultiSelect-story.js#L93-L101

https://carbon-components-react.netlify.app/?path=/story/components-multiselect--default
