### ISSUE TITLE
Docs: SassDoc link in React tutorial leads to a 404 page

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#8096]
The [SassDoc](https://github.com/carbon-design-system/carbon/blob/master/packages/layout/docs/sass.md) link in React's tutorial [Step 4](https://www.carbondesignsystem.com/developing/react-tutorial/step-4) is linking to a missing page:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6926228/111234149-4c974b80-85c4-11eb-81ac-74298c6a5ef0.png">

**Comment by emyarod** [comment]
this will be resolved by https://github.com/carbon-design-system/carbon-website/pull/2166

related https://github.com/carbon-design-system/carbon/pull/7710
