### ISSUE TITLE
[Design] UI Shell - new color token spec

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#8102]
Spec for the UI Shell using the [new color tokens](https://www.notion.so/carbondesignsystem/Final-List-of-new-tokens-fc5985c7331341baa6546064399d36da). 

![UI Shell – Header](https://user-images.githubusercontent.com/11670886/111354987-486b3c80-865d-11eb-8950-ffa0ab04f2bd.png)
![UI Shell – Side-nav](https://user-images.githubusercontent.com/11670886/111354990-4903d300-865d-11eb-82e3-820d2e3043a8.png)

**Comment by tw15egan** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/8579
