### ISSUE TITLE
columnsResizable attribute is not available in carbon-react datatable similar to carbon-angular

### ISSUE THREAD

**Issue by GokulPrasath** [carbon-design-system/carbon#8117]
In Carbon-react Datatable,i was not able to adjust the header column width dynamically in the screen according to the content in the cell. I need columnsResizable  attribute in  react-carbon similar to angular-carbon.

**Comment by tay1orjones** [comment]
Hi Gokul, resizable table columns as a feature was discussed in length in https://github.com/carbon-design-system/carbon/issues/4751:

> (It's) appropriate at this point for implementation at the PAL level, rather than the core Carbon level, and can discuss long term support and integration at a future date.

There are some data table implementations listed in our [community component index](https://www.carbondesignsystem.com/community/component-index/) that have this feature. Closing for now, let me know if you have any questions.
