### ISSUE TITLE
[Modal] Modal dialog's close button has hard-coded string 

### ISSUE THREAD

**Issue by cheer021** [carbon-design-system/carbon#8125]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

[Modal] Modal dialog's close button has hard-coded string "Close" 

> Is this issue related to a specific component?

Modal control 
https://www.carbondesignsystem.com/components/modal/

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Either 
- remove the tooltips completely so consumers can pass their own string (MORE preferred) 
Or
- Read the user locale and translate the string (LESS preferred - because consumers should decide where to read the locale which can be different from browser locales) 

> What browser are you working in?

Chrome - this is a cross-browser issue

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cognos Analytics: This issue is not gating our release 

## Steps to reproduce the issue

1. Open the Modal dialog
2. Hover over the close x svg
3. See "Close"

## Additional information

<img width="904" alt="Screen Shot 2021-03-18 at 2 26 51 PM" src="https://user-images.githubusercontent.com/2319230/111693318-16d9a900-87f6-11eb-8c3d-e99b4237f8cc.png">

**Comment by tw15egan** [comment]
The close button text can be changed via the `iconDescription ` prop 

You can test for yourself here, under knobs: https://react.carbondesignsystem.com/?path=/story/components-modal--playground
