### ISSUE TITLE
Modal without close and cancel button

### ISSUE THREAD

**Issue by moczolaszlo** [carbon-design-system/carbon#8128]
Hi Carbon team,

I need a `Modal` without close button and with disabled Cancel button (or without that). I know I can build it from `ComposedModal` elements. But I'm wondering, why the `Modal` doesn't have a `secondaryButtonDisabled` and a `hideCloseButton` property? 🤔 
What do you think? I can make a PR for this if you think it's worth it. :)

**Comment by emyarod** [comment]
you can render a single button for your modal (see the "Number of buttons" knob in this story https://carbon-components-react.netlify.app/?path=/story/components-modal--playground), but I believe the close button is a design and accessibility requirement

**Comment by moczolaszlo** [comment]
Hi @emyarod 
Thanks for your answer. Honestly I made the changes, it wasn't difficult. :)
We need a modal to force users to send a form, so I have to hack a modal somehow. It will be easier if it's a property.
What do you think if I send the PR and there you and the other code owners could make a judgement about that? 🤔

**Comment by emyarod** [comment]
you can go ahead and open a PR but I think it would be better to confirm that modal close buttons can be removed first cc @carbon-design-system/design

**Comment by moczolaszlo** [comment]
So @emyarod, is there any progress?

**Comment by emyarod** [comment]
after confirming with design, modals without close buttons are not supported in Carbon. ideally the user should have some way to dismiss a modal
