### ISSUE TITLE
IE11 overflow menu vertical offset is not correct

### ISSUE THREAD

**Issue by dawangdw** [carbon-design-system/carbon#814]
## Detailed description

I am meeting problem with `OverflowMenu` component on IE11 - when vertically scroll down the page a little bit, the overflow menu vertical offset is not correct.

> Is this issue related to a specific component? 

Yep, it is `OverflowMenu` component.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect to see correct behavior on IE11.

> What browser are you working in? 

IE11.

> What version of the Carbon Design System are you using? 

```
    "carbon-components": "^8.18.18",
    "carbon-components-react": "^5.44.0",
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ASAP.

## Additional information

* Screenshots

![overflow-issue](https://user-images.githubusercontent.com/16933250/40571675-f75ee31a-60cf-11e8-8f0b-3ea2d9a3d267.gif)

**Comment by asudoh** [comment]
Thanks @dawangdw for reporting! Sounds similar to https://github.com/carbon-design-system/carbon-components-react/issues/895 that signals investigation on that issue should consider vanilla, too. Meanwhile, vanilla version has similar `objMenuOffset` option, which is something you may want to try.

**Comment by asudoh** [comment]
Likely that the problem happens only with the React variant - Closing for the sake of carbon-components-react#895. Feel free to reopen if anybody disagrees. Thanks!
