### ISSUE TITLE
Investigate Cypress for visual testing in our React package

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8145]
Cypress is a tool that has been recommended to us as one that we could use to do visual testing on our components. This issue is for delivering an MVP integration with cypress with ideally one test suite (probably Accordion?) that demonstrates how we could bring this into the project.

This integration should consider the following:

- How simple is it to author tests?
- How simple is it for tests to run in CI?
  - Does running cypress dramatically increase CI time?
- How simple is it to bring in styles for our components?

**Comment by tay1orjones** [comment]
A couple stretch goal items here include
* Evaluation of `cypress-real-events` for better support of native events including `.type(tab)`, <kbd>space</kbd>, <kbd>esc</kbd> for testing keyboard navigation
* Visual regression testing w/ Percy through Cypress.
