### ISSUE TITLE
Dropdown - [CSS] the menu icon is not align the text when it is small or large

### ISSUE THREAD

**Issue by yonghuay** [carbon-design-system/carbon#8147]
## What package(s) are you using?

- [x] `carbon-components 10.31.0`
- [x] `carbon-components-react 7.31.0`

## Detailed description

> After I update the carbon to from 10.29.0 to 10.31.0, I found out that the menu icon is not aligned with label when I change it to small size or large

## Steps to reproduce the issue

1. update the carbon to 10.31.0

> Please create a reduced test case in CodeSandbox
>

> - Sample code:
>   https://codesandbox.io/s/5xrmq?file=/index.js:476-484

## Additional information

- Screenshots or code

![image](https://user-images.githubusercontent.com/32554015/111977361-8d2e2200-8afa-11eb-97e5-9953035a3caa.png)

- Notes

**Comment by emyarod** [comment]
this appears to be caused by #7990 which was attempting to resolve a similar positioning issue caused by #7777 and affects all of the listbox components
