### ISSUE TITLE
Update `size` prop in components to use consistent terms for size

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8151]
Currently size in component code are: 
![image](https://user-images.githubusercontent.com/11670886/107261025-cb6cf780-6a0c-11eb-89ea-d628da6c9693.png)

But should be:
- Small: 32px
- Medium/default: 40px
- Large: 48px

This issue is for updating the API of components that accept a `size` prop to follow this convention. If it's possible, it would be preferred to add these options in as part of the existing API and deprecate existing options before we remove them in v11.

**Comment by tw15egan** [comment]
~Just to clarify, the prop names will be `small`, `medium` (the default prop value), and `large`?~

~This will make it easier to maintain backward compatibility, as some current defaults are "lg" which would incorrectly map to `large` (existing xl) styles~

I don't think will be an issue and t-shirt sizes are more concise

**Comment by tw15egan** [comment]
List of components that use the size prop:

- [ ] Accordion
- [ ] Button 
- [ ] Listbox
   - [ ] Combobox
   - [ ] Dropdown
   - [ ] Multiselect
   - [ ] Filterable Multiselect
- [ ] Content Switcher
- [ ] DatePicker
- [ ] FileUploader
   - [ ] FileUploaderButton
   - [ ] FileUploaderDropContainer
   - [ ] FileUploaderItem
- [ ] Link
- [ ] Modal
   - [ ] ComposedModal
- [ ] Number Input
- [ ] Overflow Menu
- [ ] Search
- [ ] Select
- [ ] Tag
- [ ] Text Input
- [ ] Time Picker
- [ ] Toggle

Questions:
- Do we want to keep the `field` button size? 
- `Data Table` has a few sizes (`compact`, `short`, `normal`, `tall`). Do we want to change any of these? 
- Treeview has a size prop with `default` and `compact`. Do we want to change these?

**Comment by joshblack** [comment]
@tw15egan great questions, I'm down for `sm`, `md`, `lg` or `small`, `medium`, `large`, whatever makes more sense. 

@aagonzales what would you recommend for TJ's questions above for `field` on Button, `DataTable`, and `TreeView`? 👀

**Comment by tw15egan** [comment]
@joshblack looking into it a bit more, it seems like we should be good just sticking with the current t-shirt sizes vs. the full name. This will also give us a bit more flexibility for adding `xs` variants ( `extra-small` is a bit cumbersome)

**Comment by tw15egan** [comment]
All changes have been made with the exceptions for the following components:
- [ ] Button
- [ ] FileUploader
- [ ] Search

**Comment by joshblack** [comment]
Closed for https://github.com/carbon-design-system/carbon/issues/8370
