### ISSUE TITLE
DataTable custom state manager

### ISSUE THREAD

**Issue by spassvogel** [carbon-design-system/carbon#8152]
I'm using the DataTable component with selectable rows and a `<TableSelectAll>` to select all rows. I want to leverage as much from DataTables built-in behaviour so I'm using the render prop and `getSelectionProp` and everything. This is very nice because the `<TableSelectAll>` automatically receives the correct state (indeterminate, selected..)

But I cant figure out how to hook onto the selection change event. I can overwrite the `onSelect` of `<TableSelectAll>` and `<TableSelectRow>` but that overwrites the default behaviour.

As a work-around I'm doing the following:

```
<TableSelectAll {...getSelectionProps()} onSelect={(e) => { getSelectionProps().onSelect(e); handleCheckChange('all', (e.target as any).checked) }} />
```

but this seems rather clumsy... 

Some forum threads refer to a codesandbox: 
https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/custom-data-table-state-manager but this  codesandbox does not seem to exist anymore...

**Comment by emyarod** [comment]
this is the new link for the code sandbox: https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager

**Comment by spassvogel** [comment]
I'm getting the following error there:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/985892/112019116-6b9b5d80-8b2f-11eb-852c-3e1f9471d8a9.png">

**Comment by emyarod** [comment]
I believe you need to sign in to increase the rate limit (or wait if you are already signed in)

**Comment by spassvogel** [comment]
Right. I see now, it's not using the DataTables own logic for  determining the state of the `TableSelectAll`. I was hoping I could hook into some event to figure out if the internal state has changed without having to implement all that myself. Closing topic
