### ISSUE TITLE
Modal does not have affirmative exit motion

### ISSUE THREAD

**Issue by ishitatsuyuki** [carbon-design-system/carbon#8184]
### Summary

The [Carbon Motion Design Guideline](https://www.carbondesignsystem.com/guidelines/motion/choreography#consistency) states that "Use motion to reinforce meaning. Affirmative action here triggers a different exit motion for the modal than negation". However this is not implemented in the Modal component: it only has a [-24px transform variant](https://github.com/carbon-design-system/carbon/blob/8f3c2a122e42bbb0716f3ad7778f5617600beefb/packages/components/src/components/modal/_modal.scss#L83), so it always appear/disappear in the top direction.

Implementing this in CSS should be quite simple; all it needs is a class for +24px variant. However, I'm not sure what how one should design the component APIs/props for this.

**Comment by emyarod** [comment]
cc @johnbister should we add a separate animation for affirmative modal actions?

**Comment by johnbister** [comment]
@emyarod Yes! I'm surprised it's not already implemented.  @ishitatsuyuki do you want to take a shot at a PR? If not, we can tackle it.

**Comment by ishitatsuyuki** [comment]
I'm still new to React, so I'd appreciate if you could make the change.

**Comment by johnbister** [comment]
@emyarod do you mind if I take a shot at it? i'm still learning react, but this feels like a good issue to test out.

**Comment by emyarod** [comment]
sure @johnbister go for it, feel free to reach out if you have any questions

**Comment by johnbister** [comment]
@emyarod after messing around with it today i quickly realized this is way over my head... i apologize.

**Comment by sstrubberg** [comment]
@ishitatsuyuki thanks for the opening this PR and apologies it has taken this long for an appropriate response. Due to constraints with resources and our roadmap, we will be unable to take this work on at this time. If at any point you feel comfortable opening a PR against this issue, we would be more than happen to re-open and consider it.
