### ISSUE TITLE
Q2 2021 release: component color token specs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#8187]
# New color token component specs

- **Sketch files**: https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5
- **Note**: the layer styles have not been updated. Will update the symbols when we update the Sketch library. Follow the written spec annotations. 

**Index:**
- [Accordion](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807077132)
- [Breadcrumb](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807089627)
- [Button](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807089897)
- [Checkbox](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807090564)
- [Code snippet](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807091015)
- [Content Switcher](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807091241)
- [Date Picker](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807569144)
- [Dropdown](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-807569711)
- [File uploader](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809631663)
- [Link](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809631788)
- [List](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809631918)
- [Loading](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809632093)
- [Modal](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809737412)
- [Notifications](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-809737529)
- [Number input](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-810591698)
- [Overflow menu](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-810592361)
- [Pagination](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-810592711)
- [Progress indicator](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-810593021)
- [Radio button](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-813555186)
- [Search](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-813555299)
- [Select](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-813555546)
- [Slider](https://github.com/carbon-design-system/carbon/issues/8187#issuecomment-813555692)

**Comment by aagonzales** [comment]
![Accordion - White theme](https://user-images.githubusercontent.com/11670886/112511747-b6e88280-8d60-11eb-8580-7f5f6dabfebd.png)

**Comment by aagonzales** [comment]
![Breadcrumb - White theme](https://user-images.githubusercontent.com/11670886/112511796-c1a31780-8d60-11eb-989b-f4f5349b6cc9.png)

**Comment by aagonzales** [comment]
![Button default - White theme](https://user-images.githubusercontent.com/11670886/112511858-d089ca00-8d60-11eb-98d8-7b12c92e5540.png)

**Comment by aagonzales** [comment]
![Checkbox - White theme](https://user-images.githubusercontent.com/11670886/112511875-d4b5e780-8d60-11eb-86be-81b47de6f837.png)

**Comment by aagonzales** [comment]
![Code snippet — White theme](https://user-images.githubusercontent.com/11670886/112511925-e0091300-8d60-11eb-98ee-5772fe5adbb7.png)

**Comment by aagonzales** [comment]
![Content switcher — White theme](https://user-images.githubusercontent.com/11670886/112511954-e5fef400-8d60-11eb-9ab7-b06221b6b74f.png)

**Comment by aagonzales** [comment]
![Date Picker - White theme](https://user-images.githubusercontent.com/11670886/112548882-ee6c2480-8d8a-11eb-80fd-a958201610e3.png)

**Comment by aagonzales** [comment]
![Dropdown - White theme](https://user-images.githubusercontent.com/11670886/112548902-f62bc900-8d8a-11eb-862c-d302953b313f.png)
![Dropdown Combo box - White theme](https://user-images.githubusercontent.com/11670886/112548906-f75cf600-8d8a-11eb-8f89-9f9d141ea755.png)
![Dropdown Multi-select (regular) - White theme](https://user-images.githubusercontent.com/11670886/112548908-f7f58c80-8d8a-11eb-9369-22860229875d.png)

**Comment by aagonzales** [comment]
![File Uploader (default) - White theme](https://user-images.githubusercontent.com/11670886/112885893-e10aaf00-9096-11eb-90bd-6feb2cdf38d5.png)
![File Uploader (drag and drop) - Drag and drop - White theme](https://user-images.githubusercontent.com/11670886/112886006-ff70aa80-9096-11eb-867c-b7894feb9232.png)

**Comment by aagonzales** [comment]
![Link - White theme](https://user-images.githubusercontent.com/11670886/112886023-07c8e580-9097-11eb-88b6-71b1ab09cf0a.png)

**Comment by aagonzales** [comment]
![List - White theme](https://user-images.githubusercontent.com/11670886/112886060-0f888a00-9097-11eb-87b3-314ac4be0269.png)

**Comment by aagonzales** [comment]
![Loader - White theme](https://user-images.githubusercontent.com/11670886/112886087-157e6b00-9097-11eb-8934-db55b90da1e4.png)
![Inline loader - White theme](https://user-images.githubusercontent.com/11670886/112886098-18795b80-9097-11eb-936a-8d7dea2a5828.png)

**Comment by aagonzales** [comment]
![Modal - types](https://user-images.githubusercontent.com/11670886/112904628-d4925080-90ae-11eb-9e2a-58af5fe3fde1.png)

**Comment by aagonzales** [comment]
![Notification (high contrast) - White theme](https://user-images.githubusercontent.com/11670886/112904658-de1bb880-90ae-11eb-9dfd-7013bb05123a.png)
![Notification (low contrast) - White theme](https://user-images.githubusercontent.com/11670886/112904665-df4ce580-90ae-11eb-85a6-16f2f9b473e8.png)

**Comment by aagonzales** [comment]
![Number input - White theme](https://user-images.githubusercontent.com/11670886/113059849-898f4080-9175-11eb-9672-346633a973c7.png)

**Comment by aagonzales** [comment]
![Overflow menu - White theme](https://user-images.githubusercontent.com/11670886/113059959-ad528680-9175-11eb-8a78-722269db163b.png)

**Comment by aagonzales** [comment]
![Pagination](https://user-images.githubusercontent.com/11670886/113060037-c2c7b080-9175-11eb-8ff2-a56973a63c39.png)

**Comment by aagonzales** [comment]
![Progress Indicator - White theme](https://user-images.githubusercontent.com/11670886/113060117-da069e00-9175-11eb-881e-2d7270490304.png)

**Comment by aagonzales** [comment]
![Radio button - White theme](https://user-images.githubusercontent.com/11670886/113609571-939bbe00-9611-11eb-9d56-a6c614bf01a3.png)

**Comment by aagonzales** [comment]
![Search_light_theme_lrg](https://user-images.githubusercontent.com/11670886/113609606-9b5b6280-9611-11eb-9efa-d28b1ad51235.png)

**Comment by aagonzales** [comment]
![Select - White theme](https://user-images.githubusercontent.com/11670886/113609641-a9a97e80-9611-11eb-94c2-f94d856ece36.png)

**Comment by aagonzales** [comment]
![Slider - White theme](https://user-images.githubusercontent.com/11670886/113609663-b037f600-9611-11eb-83e8-9b8c82a5b925.png)

**Comment by joshblack** [comment]
Going to close this out since it seems like the spec is completed and this was in the sprint. Feel free to re-open if. that's not the case!
