### ISSUE TITLE
Tabs component width

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon#8194]
When we have multiple tabs and follow the 160px equal width guideline there are cases where for the “Default” tab variation the end result looks a bit weird if we have say a few single word labels mixed with multi-word labels _(see “Option A” in the attached comparison)_.

![Tabs width - question@2x](https://user-images.githubusercontent.com/1560160/112596929-25871800-8e15-11eb-99e9-fe3b1e5a53c7.png)

Could it be an option if instead of the fixed width we use a rule, similar to the one used for the Carbon buttons, where the tabs are variable width with 16px left padding and 64px right padding _(see “Option B” in the attached comparison)_? 

_Note, this question was posted on the #carbon-design-system Slack channel but no reply has been received yet - https://ibm-ai-apps.slack.com/archives/C0M053VPT/p1616484073114000_

**Comment by emyarod** [comment]
the fixed tab width is an intentional design decision (#4973 #6903 #7640), but you should be able to implement the behavior you described by modifying the `width` style rule on `.bx--tabs--scrollable__nav-link`

**Comment by joshblack** [comment]
Hi there! 👋  Going to close this issue out since it's been a bit since we've heard back and it seems like the comment above addresses the issues.
