### ISSUE TITLE
OverflowMenu does not size dynamically, resulting in truncation of menu items

### ISSUE THREAD

**Issue by tom-poulin** [carbon-design-system/carbon#8197]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Overflow menus (OverflowMenu) seem to be hard-coded to 10 rem (160 px) for width. This causes unwanted truncation on even rather short English menu items, which become more pronounced when translated to languages like German. Why don't these size dynamically to their content?

In tables, we work around it by just setting a larger width (CSS override). Of course it will never be perfect.

> Is this issue related to a specific component?

Yes: OverflowMenu. I suspect it applies to other menus too though (haven't verified).

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the width of the OverflowMenu to fit the menu items, up to some limit. As it is, the size is fixed, and not very wide at that.

> What version of the Carbon Design System are you using?

10.17.0 (7.17.0 carbon-components-react)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Engineering Lifecycle Management (ELM).

## Steps to reproduce the issue

This is readily observed in storybook: https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default.

## Additional information
Storybook showing truncated menu item "Edit routes and access":
![image](https://user-images.githubusercontent.com/70283126/112651081-48abca80-8e09-11eb-8477-90182adb7bd6.png)

From https://login.w3.ibm.com/usc/settings/security:
![image](https://user-images.githubusercontent.com/70283126/112651397-96c0ce00-8e09-11eb-97e8-dbeefb3c7422.png)

Sample menu items in DOORS Next that we're trying to Carbonize:
![image](https://user-images.githubusercontent.com/70283126/112651825-01720980-8e0a-11eb-8837-4940ecb338f4.png)

See also the Slack discussion in #ai-apps-pal: https://ibm-ai-apps.slack.com/archives/CDD01SREX/p1615412742097000

**Comment by tom-poulin** [comment]
@mzuliani-ibm @gillibrand FYI

**Comment by joshblack** [comment]
Thanks for taking the time to make this issue @tom-poulin! 🙏 

Let me include @carbon-design-system/design to see what they think 👀  We could totally offer separate modes, as well, for going between the fixed width version and a more dynamic version 👍

**Comment by tom-poulin** [comment]
@jnm2377, that's new, right? It may work, although I don't see knobs on Storybook where I can experiment with different (longer) menu labels to see if the width adjusts dynamically. Perhaps you have a CodeSandbox where I can try it? (I tried configuring one but encountered "Could not fetch dependencies" error.)

The other issue is that we're using the PAL (carbon-addons-iot-react) table, which uses OverflowMenu internally - so we can't just swap it out. However, I see your Storybook also has OverflowMenuV2. Is that intended as a potential replacement to OverflowMenu?

**Comment by tay1orjones** [comment]
@tom-poulin Sorry for the delay here, yes ContextMenu is new and currently unstable. We're working on defining the criteria to move to stable and we anticipate it being stable very soon, #11688.

I made a [codesandbox replica of the storybook story](https://codesandbox.io/s/smoosh-flower-o3oftk?file=/src/App.js) that you can try it out with.

OverflowMenuV2 is an experimental implementation of OverflowMenu using the `Menu` (same primitive component used by ContextMenu). We're unsure of the future there though, and for now it would probably be best to evaluate how you could use ContextMenu (or Menu) yourself to achieve what you're aiming for. 

I'm going to close this one out for now, but let us know if there's a reason this wouldn't work for your use case.
