### ISSUE TITLE
Unreadable text on InlineNotification

### ISSUE THREAD

**Issue by marcinmotNB** [carbon-design-system/carbon#8199]
## What package(s) are you using?

- [x ] `carbon-components 10.29.0`
- [ x] `carbon-components-react 7.29.0`

## Detailed description

Text of `InlineNotification` in darkmode is unreadable when using `lowContrast` mode.

## Additional information

dark mode
![image](https://user-images.githubusercontent.com/43094706/112666151-2727fe80-8e5c-11eb-8260-79e2f29105c3.png)

light mode
![image](https://user-images.githubusercontent.com/43094706/112666213-3909a180-8e5c-11eb-9305-119ea772fec2.png)

**Comment by joshblack** [comment]
Hi there @marcinmotNB! 👋 Thanks for much for taking the time to make this issue, could you share some steps to reproduce the problem you noted over in [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)? This will help us figure out what's going on here. Thanks!

**Comment by tw15egan** [comment]
I believe this has come up recently and should be fixed on latest: 

https://github.com/carbon-design-system/carbon/issues/7857
 - https://github.com/carbon-design-system/carbon/issues/7857#issuecomment-784463409


Updated guidance 
https://github.com/carbon-design-system/carbon/pull/7808

Similar: #8196

**Comment by marcinmotNB** [comment]
@joshblack I found this issue for notification https://github.com/carbon-design-system/carbon/pull/7808 and including those styles in our solution - notifications colors were fixed for dark mode.
But we would expect to import just `@carbon/themes/generated/tokens` as we do it currently to have them all.
