### ISSUE TITLE
Translation Bug - English Strings in a Chinese Language

### ISSUE THREAD

**Issue by abod-akhras** [carbon-design-system/carbon#8207]
Can you please fix the Translation Issue (English Strings) when the user has selected Chinese Language for the  (`items selected` and `cancel`) buttons?

![image](https://media.github.ibm.com/user/287811/files/f1a41a80-6568-11eb-8af6-1711874896cc)

## Components / Docs Affected

 
- [DataTable Component](https://pages.github.ibm.com/ibmcloud/pal/components/data-table/code/)

## Detailed Description
> English Strings appear when Chinese Language are selected.
> Those strings seems to be coming from the hardcoded value in:
`carbon-components-react/es/components/DataTable/TableBatchActions.js` line number 22- 25

![image](https://media.github.ibm.com/user/287811/files/02a15b80-656a-11eb-9e98-37644f9616f0)

## Context

Checked with the Pal team and they confirmed the issue is on the Carbon Design System: https://github.ibm.com/ibmcloud/pal/issues/3867#issuecomment-29176822

## Steps to reproduce the issue
1. [Create AppId Instance ](https://cloud.ibm.com/docs/appid?topic=appid-getting-started)
2. Switch to Simplified Chinese locale in your browser settings
3. Bring up the App ID dashboard.
4. Go to "Profiles and roles" -> "User Profiles"
5. Click Future users and check a user
6. Select one or more item from the table
7. You will see English Strings (`items selected` and `cancel`) in the Table Toolbar

OR

1. Create a new React App
2. Use the DataTable component
3. Populate some items in the table
4. Switch to Simplified Chinese locale in your browser settings
5. Select one or more item from the table
6. You will see English Strings (`items selected` and `cancel`) in the Table Toolbar

## Environment
- **@Console/Pal Version:** ^1.336.7
- **ReactJS Version:** 16.12.0

**Comment by emyarod** [comment]
the strings are configurable in your application via the `translateWithId` prop on `<TableBatchActions>`

```jsx
const translationKeys = {
  // use custom strings here
  'carbon.table.batch.cancel': 'Cancel',
  'carbon.table.batch.items.selected': 'items selected',
  'carbon.table.batch.item.selected': 'item selected',
};

const translate = (id, state) => {
  if (id === 'carbon.table.batch.cancel') {
    return translationKeys[id];
  }
  return `${state.totalSelected} ${translationKeys[id]}`;
};

<TableBatchActions translateWithId={translate}>
```

**Comment by joshblack** [comment]
Going to close this out as it seems the question was addressed 👀

**Comment by abod-ibm** [comment]
@emyarod @joshblack Can you please provide an example to configure those strings for different languages?

**Comment by emyarod** [comment]
you can refer to my previous comment https://github.com/carbon-design-system/carbon/issues/8207#issuecomment-809469658 for an example
