### ISSUE TITLE
feat(ComboBox) ComboBox need more/better support of downshift

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#8209]
### Summary

Carbon uses downshift to deliver ComboBox.
Carbon supports some of the downshift options directly as ComboBox props.
Carbon also supports a ComboBox.downshiftProps prop for additional downshift options.

The Carbon ComboBox use of downshift options is mixed, sometimes ignoring, sometimes using, sometime mis-using, them.

```
The Carbon Client should not have to search/read the Carbon ComboBox **CODE** to figure out what is possible.

Ideally, all downshift options should be supported.

However, if the Carbon ComboBox will not support a downshift option or if it modifies a downshift option... those downshift options should be well documented by Carbon.

This can be in the form of...
- a whitelist; listing specifically what downshift options are supported.
- Or a blacklist; listing specifically what downshift options are not supported.
```

### Justification

The support of the ComboBox.downshiftProps props is essential for client to control ComboBox. 
Clients need to have better control to support their applications, to support functionality, styling, and testing.
And in some cases to fix Carbon issues: see #8070.

### Desired UX and success metrics

This is a hard one.

From a Carbon point of view the internal use of downshift should have no impact at all.
The internal use of downshift by Carbon should deliver a working ComboBox as per the Carbon design.
The success metrics for this is that Carbon ComboBox works as per the Carbon design.

The issue is for the support of downshift within ComboBox.
So the effect on UX is completely based on the downshift options the Client passes to Carbon ComboBox.
The success metrics for this is that Carbon ComboBox accepts and reflects the downshift options supplied by the user.

### "Must have" functionality

The must have's is a hard list to determine.
It is based on what downshift options are deemed essential to support/pass on.
Ideally, every/any downshift option should be supported.

If there are some downshift options that are not supported, or modify the clients use of the downshift options...
...they should be well documents by Carbon.

The Carbon Client should not have to search/read the Carbon ComboBox code to figure out what is possible.

Some examples of some of the issues Carbon has with the downshift options...

1. the downshift getter-props should not be applied to <DownShift> but applied the the getter-props directly
2. some downshift options are supplied as direct props to ComboBox (presumably for convince), in this case they need to be 'looked for' as direct props and as downshiftProps.
3. when downshift options are used internally they need to take into account passed in downshift options (by either applying or calling them)
4. some downshift options are state options in ComboBox, making them completely inaccessible as downshift options
5. there may be others

```
I have created a PR to help show what the downshift issues with ComboBox are.
Within the PR, diffs are numbered corresponding to the issues mentioned above.
https://github.com/carbon-design-system/carbon/pull/8211
```

### Specific timeline issues / requests

na

### Available extra resources

na

**Comment by joshblack** [comment]
Copying over from #8211 

> I think that, unfortunately, support for full integration with downshift will be minimal. We ran into a tough situation this last release cycle (v10.x) when we exposed library APIs as part of our component APIs and it made updating dependencies incredibly difficult, especially for faster moving targets like Downshift. (For reference, Downshift has moved from v1 to v6 while we've stayed on v10.x) For the rest of v10.x, we'll likely keep support limited to the Component API for the Downshift component or equivalent hooks versus and not expose any of the prop getters.
>
> Our current thinking is that we'll reverse this API design decision and instead expose the listbox primitives we have for teams to use with downshift directly. This is definitely still a part of our v11 release planning though so it could change but just wanted to share our current thoughts here.
>
> I'll go update that issue and close out this PR and the issue. Let me know if this is a mistake though and I'd be happy to re-open them!
