### ISSUE TITLE
Data Table Overflow Menu is unintuitive on touch screens

### ISSUE THREAD

**Issue by hvlawren** [carbon-design-system/carbon#821]
> Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

When using a data table on a touch screen, you have to first click the row, then the button. It seems likely that some users won't realize this is an option.

> Is this issue related to a specific component? 

Data Table... and if there is a hidden overflow menu on other components?

> What did you expect to happen? What happened instead? What would you like to see changed?

The overflow menu should be apparent to all users, not just users likely to hover over rows.

> What browser are you working in? 

Tested on Android Chrome

> What version of the Carbon Design System are you using? 

Current version on carbondesignsystem.com

## Steps to reproduce the issue

1. Navigate to Data Table on mobile
2. No overflow menus visible
3. Tap row
4. Overflow menus visible

## Additional information

I spoke to @tw15egan about this on Slack. He first suggested a size media query, then he suggested this: https://css-tricks.com/touch-devices-not-judged-size/

**Comment by asudoh** [comment]
Let's continue the discussion at: #1156
