### ISSUE TITLE
Overflow menu are unnecessarily extended with extra pixels when they are launched from a primary button

### ISSUE THREAD

**Issue by brnnnfx** [carbon-design-system/carbon#8219]
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When you have an Overflow menu flyout off of a Primary button, you'll see additional elements (a small white bar / extra pixels) appear between the root of the menu and the button

> Is this issue related to a specific component?

Yes, the [Overflow menu](https://www.carbondesignsystem.com/components/overflow-menu/style/), when used in conjunction with [Primary button](https://www.carbondesignsystem.com/components/button/style)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Either a more elegant way to show that the menu is connected to that button, or no visual element at all at the root of the overflow menu.

> What browser are you working in?

- Firefox ESR 78.9.0esr (64-bit)

> What version of the Carbon Design System are you using?

carbon-components - 10.17.0
carbon-components-react - 7.17.0

> What offering/product do you work on? 

IBM Cognos Analytics

## Steps to reproduce the issue

_on an Button (primary) that is will launch an Overflow menu on select_

1. Select your primary Button
2. Look at the root of your overflow menu

> Please create a reduced test case in CodeSandbox
> (forthcoming)
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

![hereAlso](https://user-images.githubusercontent.com/12024098/112905882-39eb3f00-90b9-11eb-8709-cc7f020cca30.png)
![extraPixels](https://user-images.githubusercontent.com/12024098/112905891-3d7ec600-90b9-11eb-9004-869aab93a71f.jpg)
![hereToo](https://user-images.githubusercontent.com/12024098/112905892-3d7ec600-90b9-11eb-9175-ef7085fe35e8.jpg)

**Comment by emyarod** [comment]
since you are using a custom trigger element, the menu will need custom styling to match. the menu won't automatically detect the background colors of the trigger button so you will need to add styles to `.bx--overflow-menu-options::after`

**Comment by joshblack** [comment]
Seems like this has been addressed above, going to close this out. Feel free to comment and we can re-open!
