### ISSUE TITLE
`RadioButtonGroup` usability issue (renders it's own children regardless of given children types)

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#8225]
## Detailed description

> What version of the Carbon Design System are you using?

`carbon-components-react@npm:7.31.0`

> What did you expect to happen?

I've created a wrapper component for `RadioButton` to support our design addition of description text & then spent half an hour scratching my head as to why my component is not rendered.

It's because [you are rendering your version of `RadioButton` regardless of what is given as children](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/RadioButtonGroup/RadioButtonGroup.js#L90).

I'd consider this to be quite an ugly anti-pattern.
If you need to insist on using the only right component, why aren't you using data to render  (an array of records as a prop for `RadioButtonGroup`) instead of remapping children.

## Additional information

![image](https://user-images.githubusercontent.com/11244314/112972010-16bf9e80-9150-11eb-99d5-b1634665a2e6.png)

**Comment by vpicone** [comment]
@kubijo Definitely agree, the fact that this works is evidence of that haha. 

```
  <RadioButtonGroup>
    <h1
      id="radio-1"
      value="standard"
    />
    <html
      id="radio-2"
      value="default-selected"
    />
  </RadioButtonGroup>
```

Cloning the child rather than forcing our own RadioButton would likely be the best way forward here.

**Comment by vpicone** [comment]
@kubijo Definitely agree, the fact that this works is evidence of that haha. 

```
  <RadioButtonGroup>
    <h1
      id="radio-1"
      value="standard"
    />
    <html
      id="radio-2"
      value="default-selected"
    />
  </RadioButtonGroup>
```

Cloning the child rather than forcing our own RadioButton would likely be the best way forward here.

**Comment by andreancardona** [comment]
@kubijo going to implement a solution to close this! :)

**Comment by tw15egan** [comment]
Looks like this was introduced way back in [PR #124](https://github.com/carbon-design-system/carbon/commit/896a65d2b6f2fcf79a09984cd74e110651a3d67f), it's almost about to start kindergarten now 😂  Definitely due for a refactor!

**Comment by andreancardona** [comment]
PR can be seen here - will close once approved and merged: https://github.com/carbon-design-system/carbon/pull/8283
