### ISSUE TITLE
Time picker vs Date range picker - spacing

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon#8234]
We are exploring a custom field type which is a compound of a Text input + Select components. In Carbon there are two similarly constructed components - "Time picker" and "Date range picker".

I wanted to double check what should be the spacing between the two components - 1px or 2px? I noticed the spacing is not consistent in the following Sketch library assets:

![Time picker vs Date range picker - spacing@2x](https://user-images.githubusercontent.com/1560160/113026098-5e1a4f00-9191-11eb-9ee9-936d93ea2f0a.png)

**Comment by emyarod** [comment]
based on https://github.com/carbon-design-system/carbon/issues/6265 the spacing is intentional, cc @laurenmrice for confirmation

**Comment by joshblack** [comment]
bump @laurenmrice when you get a sec!

**Comment by laurenmrice** [comment]
I did not realize they were different from each other. After talking as a group with design, we have decided to keep a `1px` space instead of 2px. This follows the same spacing we have for the condensed grid gutter.

**Comment by joshblack** [comment]
Thanks @laurenmrice! Going to close this out since it seems like the question was addressed 👀

**Comment by joshblack** [comment]
@emyarod just a quick heads up, when you get a sec make sure that issues being tackled are added to the sprint/sized! I went ahead and did a rough pass for this one, feel free to update if I'm off!
