### ISSUE TITLE
Inline labels sometimes show above form controls

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#8250]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

_form.scss defines the CSS of

```
  .#{$prefix}--form-item {
    ...
    flex-direction: column;
  }
```

_text-input.scss "overrides" that with:

```
  .#{$prefix}--text-input-wrapper--inline {
    flex-flow: row wrap;
  }
```

However, the override has the same selectivity as the original CSS, so it only works if _form.scss is loaded before _text-input.scss.   This works in the React code but isn't working for us, likely because we needed to `@include` _form.scss in one of our SCSS files in order to `@extend` bx--label.

Does it make sense to increase the selectivity of the selector in _text-input.scss?

**Comment by tw15egan** [comment]
@wkeese `text-input.scss` should be pulling in `form.scss` ([code](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/text-input/_text-input.scss#L17)) so the styles should load in the correct order. 

Do you have a way to reproduce the issue in CodeSandbox? Changing the import order in the storybook isn't causing any issues, so I'm just wondering if there is a use-case I am missing. If so, we can update the selector to be `.#{$prefix}--form-item.#{$prefix}--text-input-wrapper--inline`

**Comment by wkeese** [comment]
I'll try to make a test case... but I'm not sure about your assumption that form.scss is only included once though.  I think for us it's getting included multiple times\:

<img width="455" alt="Screen Shot 2021-04-01 at 16 08 58" src="https://user-images.githubusercontent.com/69599/113256966-e66d3100-9304-11eb-9895-508658a2e51e.png">

I suspect that's due to code we have like this:

```
// Extend bx--label
@import "cirrus3rdparty/node_modules/carbon-components/scss/components/form/form";

@mixin carbonLabel() {
	@extend .#{$prefix}--label;
	@include type-style('body-short-01');
	margin: 0;
}
```

But again, I need to test that theory.

**Comment by tw15egan** [comment]
No, you are correct. I'm able to reproduce the behavior by modifying the `TextInput` story to import a custom scss file that imports `form.scss`, which causes the `inline` variant to render wrong. I just wanted to test that was the case before adding more specificity to the selector.

We just need to change the selector to`.#{$prefix}--form-item.#{$prefix}--text-input-wrapper--inline`

**Comment by wkeese** [comment]
Thanks!  It leaves open the question of whether our builds are bloated by multiple copies of form.scss... I think `@extend` is problematic like that... but anyway glad to have the selectivity thing fixed.
