### ISSUE TITLE
Updated "Number input" component questions

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon#8251]
Questions on the recently update “Number input” Carbon component https://www.carbondesignsystem.com/components/number-input/usage

* Is the old version with the up/down caret icons deprecated?

* Should we always use the “Number input” for the cases where a numerical input is expected or we can also use the “Text input” component. 

For example in IBM TRIRIGA we have a set of compound components for which we use the old “Number input” with up/down caret icons but the new version with the -/+ icon buttons require these inputs to be much wider and breaks some of our compound components.  

Here is a comparison of the different options when applied to our custom color picker component - notice how there is no space available for the actual numerical value when the updated "Number input" component is used. It wouldn't be really practical in our case to adjust the width of the whole compound component in order for the new “Number input” to hold 3 digits.

![TRIRIGA Color picker component@2x](https://user-images.githubusercontent.com/1560160/113125189-06c2c000-921f-11eb-908f-fe174a21b19e.png)

Please advice.

**Comment by laurenmrice** [comment]
Hey @ivanbachev  👋

> Is the old version with the up/down caret icons deprecated?

The design has changed for the existing number input component. It used to have caret icons for the stepper and now it has -/+ for the stepper. 


> Should we always use the “Number input” for the cases where a numerical input is expected or we can also use the “Text input” component.

I would say it is fair to use a text input component if you need to for instances like this when you are really tight on space instead of using the number input component. 👍

**Comment by laurenmrice** [comment]
Closing, because the question has been answered 👋
