### ISSUE TITLE
Button set does not reserve space when inline

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#8264]
When the button set is used with an inline display setting it fails to reserve enough space for itself when rendering.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

See title.

> Is this issue related to a specific component?

Button set

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Button Set should be usable inline

> What browser are you working in?

Chrome Version 89.0.4389.90 (Official Build) (x86_64)

> What version of the Carbon Design System are you using?

10.31/7.31

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See https://codesandbox.io/s/button-set-inline-issue-fonor

![image](https://user-images.githubusercontent.com/15086604/113280178-e442ac80-92db-11eb-9964-499d21efbd8c.png)

**Comment by emyarod** [comment]
I believe the reason for the rigid styles is because the current button set spec only supports 2 buttons, but I will check if this is due for an update. in the meantime the workaround would be to override the strict width and flex rules

**Comment by lee-chase** [comment]
Possibly @emyarod but it does not even reserve enough space for two buttons. The modal allows more but has specific styling to cope with this.

**Comment by emyarod** [comment]
while I still have not gotten any updates on button sets containing more than 2 buttons, the "space reservation" issue should be resolved by setting flex properties on your button set container (e.g. flex-grow)
