### ISSUE TITLE
Data Discovery Tour (CEDP)

### ISSUE THREAD

**Issue by rafaelamascaro-star** [carbon-design-system/carbon#8266]
### Summary

Our platform has many features and choice options, both in the landing / dashboard and in the internal tools. Because of this, to facilitate the understanding of the actions, we want to create an onboarding / tour process for each action.

### Justification

Many users have a hard time understanding how the platform and tools work and we need to facilitate this process.

### Example of layout and references

We would like for this tool to have this same functionality: https://reactour.js.org/

Follow attached some examples that we did.

![6](https://user-images.githubusercontent.com/64613838/113294108-fa953c00-92cc-11eb-924f-dcd885c7628c.jpg)
![7](https://user-images.githubusercontent.com/64613838/113294112-fb2dd280-92cc-11eb-9117-9252dd470117.jpg)
![8](https://user-images.githubusercontent.com/64613838/113294114-fbc66900-92cc-11eb-9cba-ca8bc44548b7.jpg)

![3](https://user-images.githubusercontent.com/64613838/113294095-f832e200-92cc-11eb-8ac6-af34df1bf334.jpg)
![4](https://user-images.githubusercontent.com/64613838/113294098-f8cb7880-92cc-11eb-888d-a4da6619c7f9.jpg)
![5](https://user-images.githubusercontent.com/64613838/113294104-f9fca580-92cc-11eb-9887-cd97bdf83725.jpg)

![2](https://user-images.githubusercontent.com/64613838/113294083-f49f5b00-92cc-11eb-9cb5-04222dd667fd.jpg)

**Comment by joshblack** [comment]
Hi there @rafaelamascaro-star! 👋  Thanks so much for taking the time to put this proposal/issue together!

Would love to hear what you are thinking the next steps would be based on what you shared above when you get a sec.

**Comment by rafaelamascaro-star** [comment]
Hello @joshblack! Thank you so much for your response. 😊

When you say next steps, you are talking about the next steps buttons or the nexts steps for implementation?

**Comment by rafaelamascaro-star** [comment]
We also would like some support for our Dev team who will be creating this new component. Do you perhaps have someone that can give us guidance during the process?  😊

**Comment by joshblack** [comment]
I think for the next steps it was trying to understand if the hope was for our team to implement this, or if this was a proposal for a pattern that your time was building that you might want to have on the website.

For assistance, we can definitely help out over in our Slack channels! Let me know if you're looking for something different 😄

**Comment by joshblack** [comment]
Going to close this out based on above, let me know if I'm misunderstanding!

**Comment by rafaelamascaro-star** [comment]
Hello @joshblack !

I was not able to talk to you this last weeks because I was on vacation
Can you reopen this issue? 

I'll need some approval from you, once this component is developed.
