### ISSUE TITLE
Space between icon and tooltip in Carbon tooltip component does not match sketch kit 

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon#8275]
## Space between icon and tooltip in Carbon tooltip component does not match sketch kit 

- Should have 8px between icon and tooltip but looks like has 0 or 1px

## What package(s) are you using?

- [X] `carbon-components-react`

### Actual in Carbon React

![image (2)](https://user-images.githubusercontent.com/39408106/113333598-3db0d880-92e8-11eb-816c-c650b6712747.png)

### Expected in Carbon Sketch it

<img width="324" alt="Screen Shot 2021-04-01 at 12 44 02 PM" src="https://user-images.githubusercontent.com/39408106/113333620-45707d00-92e8-11eb-950a-9c8d0adaa6b6.png">

**Comment by joshblack** [comment]
Hey @emyarod! Just a heads up, this is in the Sprint 7 issue for Andrea.
