### ISSUE TITLE
Content Switcher - NEED FOR V9

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#828]
The sections of the content switcher are not joined, there is a slight separation between each section. Happening on regular content switcher and one with icon

<img width="923" alt="screen shot 2018-05-31 at 12 35 04 pm" src="https://user-images.githubusercontent.com/29312997/40797881-363a7862-64cf-11e8-88d0-6813893b37bb.png">

Should look like this: 
<img width="372" alt="screen shot 2018-05-31 at 12 36 29 pm" src="https://user-images.githubusercontent.com/29312997/40797897-42b305be-64cf-11e8-81cc-65adc408441a.png">

**Comment by joshblack** [comment]
cc @carbon-design-system/ui

**Comment by alisonjoseph** [comment]
@tay-aitken I can't seem to replicate this error, what browser are you using? And where are you seeing it (website live, local? components? )

**Comment by tay-aitken** [comment]
Chrome. Its not doing it for me now either. I am going to close the issue for now, will reopen if it occurs again.
