### ISSUE TITLE
Incorrect slider thumb placement if value is 0 and min is <0

### ISSUE THREAD

**Issue by rampadc** [carbon-design-system/carbon#8287]
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

Given a slider configured as:

```js
<Slider
  labelText="Zoom"
  value={this.state.current}
  min={this.state.min}
  max={this.state.max}
  step={0.5}
  stepMultiplier={1}
/>
```

If the state is set as 

```js
state = {
 min: -8, max: 8, current: 0
}
```

The slider's thumb starting position is all the way to the left, which is -8, instead of being placed in the middle of the slider.

> Is this issue related to a specific component?

Slider

> What browser are you working in?

Chrome, Edge, Firefox

> What version of the Carbon Design System are you using?

```json
"carbon-components": "^10.31.0",
"carbon-components-react": "^7.31.0",
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Sooner is always better.

## Steps to reproduce the issue

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/confident-montalcini-gc6yq?file=/src/index.js

**Comment by emyarod** [comment]
one workaround for the time being would be to render your `Slider` with a `key`

**Comment by emyarod** [comment]
is there a reason behind modifying the initial state on app mount vs directly while initializing the state itself?

**Comment by rampadc** [comment]
The data for the slider is dynamic and can change multiple times between the state initialisation and after the components have been mounted
