### ISSUE TITLE
Need a clear button for the date component

### ISSUE THREAD

**Issue by AshwinTayson** [carbon-design-system/carbon#8288]
## Environment

> Operating system

Mac Os Big Sur
> Browser

Chrome latest canary

## Detailed description

> What version of the Carbon Design System are you using?

Latest
> What did you expect to happen?

Currently I don't see any documentation for date picker to reset/clear the currently selected date.
> What happened instead?

No such option available

## Steps to reproduce the issue

1. Click on the component and select a date
2. No x button to clear the date selected

> Please create a reduced test case in CodeSandbox
> - React:
>   https://codesandbox.io/s/sad-heisenberg-7o9pc

**Comment by emyarod** [comment]
cc @carbon-design-system/design is there a spec for this use case or would this be implemented at the application level?

**Comment by aagonzales** [comment]
I believe you can just select and delete the entry field to clear the date in the date picker component. I don't think a distinct clear button is necessary per say. 

@AshwinTayson could you elaborate on why specifically you need a clear button versus the function described above. Is it to satisfy a particular use-case that you have?

**Comment by AshwinTayson** [comment]
> I believe you can just select and delete the entry field to clear the date in the date picker component. I don't think a distinct clear button is necessary per say.
> 
> @AshwinTayson could you elaborate on why specifically you need a clear button versus the function described above. Is it to satisfy a particular use-case that you have?

Its a not a particular use case. It a use case we encounter in most date-picker components. I think its a common requirement in a form context where you want to clear a field you just selected. Lets say a date field is optional in a form. If you fill the date, then there's no way to clear it by default.

The expected behaviour is similar to the Combobox component in carbon design. The clear field should ideally be available to components similar to the textbox for a single click clear. It will obviously be an optional prop.

Examples for datepicker clearable
http://airbnb.io/react-dates/?path=/story/drp-input-props--with-clear-dates-button
https://reactdatepicker.com/#example-clear-datepicker-input
https://elemefe.github.io/element-react/#/en-US/date-picker

**Comment by aagonzales** [comment]
> I think its a common requirement in a form context where you want to clear a field you just selected.

I would challenge that. Text-inputs, dropdowns, selects, none of those normally include a clear action in the field. I think it would be more common in a filtering context to have a clear vs a form content. 

Looks like both the reacdatepicker and airbnb offer the clear as an option feature. Its not always required. I would be ok with adding a prop to add a clear for when scenarios need it but I don't think it would be the default.

**Comment by emyarod** [comment]
if we're on board with adding an option to allow a clear input button, we can implement it when there is a component spec

**Comment by AshwinTayson** [comment]
Yes it will be an optional field which will be false by default. @emyarod Can you explain what you meant by component spec?

**Comment by janchild** [comment]
I would challenge this as a common requirement also. Here's an article from the Nielsen Norman Group that discusses the problems for users with these types of interface additions. The article refers to "Reset" buttons but it is the same principle. Bottom line is that giving users all the options to clear sometimes makes things more difficult. 

Specifically: 

> Even when users do want to eliminate some of the data they have entered into a form, it may slow them down to have a dedicated button for doing so, since the extra button means that users have a choice:
> - edit the erroneous fields and replace the old text with the new text
> - click Reset and type the new text into nice clean fields
> 
> The extra choice requires extra thinking, and the time saved by using an optimal interaction technique is often smaller than the time wasted on having to think instead of just moving ahead with a single interaction technique that is always used. It takes at least one second and often two seconds to decide between two possible interaction techniques which is why it is usually better not to offer users a choice. (A second may not seem like much, but it translates into about $100 million in lost productivity per year world-wide.)

The article in full is here: 
https://www.nngroup.com/articles/reset-and-cancel-buttons/

Something to think about...

**Comment by emyarod** [comment]
@AshwinTayson the request for a component spec was meant for our designers (@aagonzales) but any design assets you can provide would be useful as well

**Comment by AshwinTayson** [comment]
@janchild I disagree with this. Giving multiple option to achieve something, lets user decide whichever one is easier for them to use. A simple copy paste has shortcut, menu option and button icons in any given interface. Multiple way to achieve simple functionality is empowering. Also reset button resets all the fields while I need to clear only the specific field. The same use case can be applied when using only the date component/text/drop-down to filter something. Adding additional button to clear the field might not be the best ui approach because the buttons especially from carbon occupy alot of real estate. And having an button icon outside the datepicker makes less sense than having it as part of the component.

Take a real life usecase
We have a table with tabs on the top left and date component, drop-down component on the top right. Having a huge reset button that clears both the field is not useful. But rather clear a individual field to get the right data. Adding those buttons will also looks cluttered. We want to keep buttons which achieves a primary goal/interaction.

I'm requesting a functionality that's already available in one component. The feature request has the same goal as the current implementation

**Comment by dakahn** [comment]
Removing the `a11y` tag as this isn't an accessibility requirement/bug. From an accessibility standpoint keyboard controls for clearing a text input/combobox are working as expected with browser native <kbd>ctrl/cmd</kbd>+<kbd>a</kbd>, <kbd>backspace</kbd>

An argument could be made that expecting a keyboard user to know and input this browser/OS default command is too much friction. In which case I suggest we implement <kbd>escape</kbd> to clear as we have in Multiselect and Combobox. Nesting a button inside a control wouldn't be expected by a screen reader user (as it's not a browser default for `<input type="text">` and hitting tab and not having the next form element receive focus but instead a secondary or trinary visual affordance to clear the text input could be potentially confusing.

From a mouse user's standpoint nesting buttons inside text-inputs is an interesting design solution to a problem I've never really had personally. Clicking a text box three times and pressing <kbd>backspace</kbd> or clicking once and dragging my mouse a inch or so then pressing <kbd>backspace</kbd> isn't something I've ever been frustrated with personally, but I'm only one mouse user so take this with a grain of 🧂.

It might have been mentioned already, but if the user has a beginning and ending date selected in the range variant of Datepicker and clears the first date (either by triple clicking or by click and dragging) the second date will clear on focus.
