### ISSUE TITLE
NumberInput has monospace font as opposed to sans in TextInput

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#8321]
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Is there any particular reason why [NumberInput](https://react.carbondesignsystem.com/?path=/story/components-numberinput--default) has monospace font while [TextInput](https://react.carbondesignsystem.com/?path=/story/components-textinput--default) has a normal one?

I've encountered this because we have our fonts and monospace variant is bolder, so `TextInput` & `NumberInput` alongside each other look starkly different

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by kubijo** [comment]
Also while we're at it ... there seems to be a inconsistency in props naming ... `TextInput` uses prop `labelText` for label while `NumberInput` has `label`

**Comment by tw15egan** [comment]
Agreed, the prop inconsistency is a known issue, see

https://github.com/carbon-design-system/carbon/issues/8150
https://github.com/carbon-design-system/carbon/issues/7538#issuecomment-776338805

**Comment by aagonzales** [comment]
Yes number input has mono space to account for non-numerical character that may be in a number input like increment names.  This way the spacing of the characters is equal for alignment purposes. 

The numerals themselves are actually the same glyphs in mono and sans (besides 0) so there isn't much of a visual difference unless you're using non-numerals.

Other components that use mono in the field include date picker for similar reasons.
