### ISSUE TITLE
Datatable sortable header icons should have options to always be visible and display before header text

### ISSUE THREAD

**Issue by John30013** [carbon-design-system/carbon#8333]
The default presentation of sortable datatables is to hide the "unsorted" sort icon until the header is hovered/focused. For visual users, this does not provide any affordance that the table is sortable until the user interacts with the column headers.

Also, for wide data columns with narrow header text, the right alignment of the sort icons makes it appear as if the icon applies to the _next_ column, as seen in this screen shot:
![image](https://user-images.githubusercontent.com/11495877/114040121-50c82900-9851-11eb-9e09-512b71b05409.png)
Note how the "Product" column's sort icon appear much closer to the "Cases" column (and in fact are the same distance from that column's heading as its own sort icon).

I would like to see the sort icons moved to the left (inline-start) of heading labels—or at least offer this as an option; and also offer an option to make the sort icons always visible (though at a reduced opacity; the screenshot above is using `opacity: .6`). Currently I'm overriding the Carbon CSS to make both of these things happen as follows:
```
  /* Display datatable sort icons to the left of the column headings. */
  .bx--table-sort__flex {
    justify-content: flex-start;
    > .bx--table-header-label {
      padding-left: 0;
    }
    > svg {
      order: -1;
      margin-left: 0.75rem;
    }
  }

  /* Make the "sortable" icon always visible. */
  .bx--table-sort__icon-unsorted {
    opacity: 0.6;
  }

``` 
with the following result:
![image](https://user-images.githubusercontent.com/11495877/114050135-039c8500-985a-11eb-9de3-35524ff01b02.png)

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by aagonzales** [comment]
> the right alignment of the sort icons makes it appear as if the icon applies to the next column, as seen in this screen shot

This is why it's only available upon hover, even if they were left alignment is a tight column arrangements it would be hard to tell which icon was associated with which column. Also having the icons on the right is a system standard that we can not change. It would create inconsistency in the system. 

The hover effect background change also helps to explain the relationship between the icon and the label. 
![image](https://user-images.githubusercontent.com/11670886/115445365-5f142e80-a1db-11eb-8c29-f91daf48ec6c.png)


It is fairly a universal pattern that sort if activated in the table column header, it would be the obvious first step to  check if seeking a sort function. Its pretty common in more table to have it hidden. Having them all show presents a lot of unnecessary visual clutter, especially in already dense data tables.  Other functions like overflow menus and sometimes row actions are also hidden until hover so it is an existing pattern else where in the tables. 


Have you been getting user feedback that user can't find the sort?

**Comment by aagonzales** [comment]
A good alternative to help users understand sorting available is to set a column to be sorted by default so there is the visual indicator present at the start and they user know they can change the sort. 

![image](https://user-images.githubusercontent.com/11670886/115445882-0e510580-a1dc-11eb-8008-6973325ac238.png)

**Comment by John30013** [comment]
@aagonzales Yes, I _have_ in fact been getting user feedback that they didn't understand that the table was sortable.

To your statement that having the icons on the right is a design standard that cannot be changed, I would direct you to several other Carbon components (e.g., the Accordion) that provide an option to put the icon on the left or the right.

Your suggestion to indicate the ability to sort the table by setting a default sort on one of the columns won't work in every situation. Also, it's not always the case that every column in the table is sortable, so setting a default sort on one column actually gives no reliable information on whether any of the other columns are sortable.

In any case, it's easy for me to override this myself, so if the Carbon design team doesn't think this is important enough to implement, then I'll just continue to use my own judgment in this regard and override the CSS as I need to. I appreciate your consideration of my request.

**Comment by aagonzales** [comment]
> To your statement that having the icons on the right is a system standard that cannot be changed, I would direct you to several other Carbon components (for example, the Accordion) that provide an option to place the icon on the left or the right.

This is for the purposes of right-to-left reading. Its not a style option.

**Comment by aagonzales** [comment]
Could you provide details of the user feedback, how many users, what was the context of the experience (provide screens or links if possible). Any direct user statements would also be appreciated as well.

**Comment by aagonzales** [comment]
As a reference that this is the common sort pattern for data tables here's a look at other design system examples:
- [Sales Force](https://www.lightningdesignsystem.com/components/data-tables/#Column-sorting)
- [Material](https://material.io/components/data-tables#anatomy)
- [Shopify](https://polaris.shopify.com/components/lists-and-tables/data-table#navigation)

**Comment by John30013** [comment]
Hi, @aagonzales,

The Salesforce data table has borders around the column headers, which clearly delineate each header, and the sort indicator immediately follows the header text—it's not aligned to the right end of the header content box:
![image](https://user-images.githubusercontent.com/11495877/115801372-9258e800-a3aa-11eb-93ff-c7a9a8750265.png)

The Material Design data table design document is inconsistent: when specifying the default sort column, the design example shows the sort indicator placed directly after the heading label text:
![image](https://user-images.githubusercontent.com/11495877/115801575-14e1a780-a3ab-11eb-8a7f-f37e7c33283c.png)
However, in the other design examples the sort indicator is placed to the left of the column header text, and appears to overlay the right end of the previous column (or the gap between columns, which would seem to be problematic if the first column needs to be sortable):
![image](https://user-images.githubusercontent.com/11495877/115801948-f039ff80-a3ab-11eb-8af1-33709179eb82.png)
I admit the visual designs are not entirely clear, but the text below the "reverse" sorted design example makes this clear (as does the image, if you look closely):
> A table sorted in reverse: the downward arrow shows that the **schedule column** is sorted in descending order.

_[emphasis is mine]_

Note that I didn't see an actual working example of the MD data table with sortable columns to see how it's actually implemented.

The Shopify example seems to show the sort indicators to the left of the header text (i.e., like my suggestion):
![image](https://user-images.githubusercontent.com/11495877/115802561-262bb380-a3ad-11eb-9d1a-807372778258.png)
Also note that in the sortable columns, the header text is aligned to the right of the header's content box—although it's not entirely clear that this isn't true for _all_ numeric data columns, since the two numeric columns that aren't sortable have header text that's wider than the data in the columns). But it _is_ clear that the heading on the first column (which isn't sortable in live example) is left-aligned.

So, overall, I don't find these examples persuasive to your argument.

**Comment by aagonzales** [comment]
> So, overall, these examples don't support your statement that right-aligning sort indicators in the header content box is a "universal" pattern. In fact, based on the examples you provided, it's not even a common pattern.

My examples weren't about the alignment but to address the point a sort needed to visual on every column. All these examples only have one column with the shown indicator. I believe you are recommending that we have it shown on every column. 


The second recommendation you made was to have it left vs right aligned. I think this is an aesthetic choice and as per the IBM Design Language parameters our icons always appears to the right of the text.

**Comment by chrisconnors-ibm** [comment]
Hello @John30013,

It in not uncommon to reveal sort controls on table columns only on hover; that's how **Google Sheets** works: 
![image](https://user-images.githubusercontent.com/35537391/116125883-0558ac00-a694-11eb-88ae-19520e0a2a79.png)

as well as **Microsoft Excel**:
![image](https://user-images.githubusercontent.com/35537391/116125977-1c979980-a694-11eb-9923-26f94b0f7147.png)

Our data suggests that users who expect columns to be interactive and provide sort functionality will try it, and as soon as their cursor enters the column header hit area, their assumption is confirmed. If it were 2000, a stronger case could be made for persistent sort control affordances visible all the time, but in 2021, the case is not compelling. Our experience confirms that the chosen implementation matches user's expectations based on other similar implementations for these interaction types.

This screenshot https://user-images.githubusercontent.com/11495877/114040121-50c82900-9851-11eb-9e09-512b71b05409.png showing possible confusion between the affordances and the labels is not a state our table can be put in without a lot of overrides, but does demonstrate why the decision was made to not show all affordances on all columns all the time.

As implemented the control/label grouping respects the proximity Gestalt bc it is not competing with the visual noise of all controls simultaneously visible, and bc the containment of the column header highlight changes the entire header and contents (label, icon) into a single perceptual entity.

![image](https://user-images.githubusercontent.com/35537391/116167736-dd3a6e80-a6ce-11eb-8395-b9a397fc78e9.png)

An IBM Product with these overrides would not pass our internal IBM Design Language reviews, since this expression is inconsistent both the language spirit as well as the preponderance of execution for similar controls. This may not be an issue in your case.

Thanks for taking the time to submit this issue, as it give us an opportunity to explain the rationale behind these decisions.
