### ISSUE TITLE
Time picker component - Time format and component size

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon#8358]
Is there a way for the Time picker component to handle a “hh:mm:ss” format? It looks like the current sets of Sketch library symbols and React storybook doesn’t allow such usage.

https://www.carbondesignsystem.com/components/date-picker/usage/#time-pickers
https://react.carbondesignsystem.com/?path=/story/components-timepicker--default

Also, can we have the Sketch library component available in the  small size - similar to how the Date picker component is available in small/default/large sizes.

**Comment by emyarod** [comment]
cc @carbon-design-system/design

**Comment by emyarod** [comment]
are you seeing the regex pattern not functioning correctly when you try to support hh:mm:ss formats in the time picker? I believe the coded component should function as expected, and this issue can be scoped to the Sketch library changes

**Comment by laurenmrice** [comment]
Hey Ivan!

I will make a separate issue in our carbon-design-kit repo to add the three sizes for the Timepicker component in Sketch. 👍
