### ISSUE TITLE
Chevron rotation animations are incosistent

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#8360]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Carbon uses a rotating chevron icon in a few places, the animation however is not consistent. Sometimes the icon rotates clockwise, sometimes counter-clockwise.

> Is this issue related to a specific component?

- Accordion
  - ![Screen Recording 2021-04-12 at 14 25 22](https://user-images.githubusercontent.com/28265588/114394152-2b158980-9b9b-11eb-862e-ab0d50fe3675.gif)
- SideNav
  - ![Screen Recording 2021-04-12 at 14 27 36](https://user-images.githubusercontent.com/28265588/114394304-57c9a100-9b9b-11eb-87d5-3bb087d6a9b8.gif)
- CodeSnippet (Multiline -> "Show more" button)
  - ![Screen Recording 2021-04-12 at 14 31 42](https://user-images.githubusercontent.com/28265588/114394852-fb1ab600-9b9b-11eb-85ad-9062a2e6614d.gif)
- ListBox (ComboBox, Dropdown, MultiSelect)
  - ![Screen Recording 2021-04-12 at 14 33 10](https://user-images.githubusercontent.com/28265588/114394977-1f769280-9b9c-11eb-8090-b501e8ef7c75.gif)
- DataTable (Expansion)
  - ![Screen Recording 2021-04-12 at 14 34 57](https://user-images.githubusercontent.com/28265588/114395411-9c097100-9b9c-11eb-930e-019d50667aeb.gif)
- Tile (Expandable)
  - ![Screen Recording 2021-04-12 at 14 39 08](https://user-images.githubusercontent.com/28265588/114395766-0e7a5100-9b9d-11eb-829c-a2624f73b4a4.gif)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Ideally, all chevrons would rotate the same way.
If there is a system behind those which I don't get, I apologize in advance 😄 

> What browser are you working in?
Chrome 89

> What version of the Carbon Design System are you using?

`carbon-components@10.32.1`
`carbon-components-react@7.32.1`

## Steps to reproduce the issue

Visit storybook for above mentioned components

**Comment by johnbister** [comment]
@emyarod @janhassel let’s do the chevrons rotating clockwise on expand and counter clockwise on collapse like shown below:

![114395411-9c097100-9b9c-11eb-930e-019d50667aeb](https://user-images.githubusercontent.com/70543333/114459371-4ed5d100-9b95-11eb-9149-e1dae8e36779.gif)


It seems like a slight majority of the components work this way already and it feels the most natural to me. 

@shixiedesign  do you have an opinion on this?
