### ISSUE TITLE
Dropdown component needs accessibility work

### ISSUE THREAD

**Issue by mchembur** [carbon-design-system/carbon#837]
When I run the JAWS screen reader against the the dropdown component page on Carbon design website http://carbondesignsystem.com/components/dropdown/code I am seeing the following -
i) the list items are read even without opening the dropdown
ii) the list items are read twice  (2nd time as links)

I used Window7 64 bits with Chrome 67 and IE11

**Comment by dakahn** [comment]
Closing this, but dropdown accessibility work can be tracked at #1147
