### ISSUE TITLE
NumberInput: Hide -/+ buttons

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#8386]
### Summary
Provide an attribute to hide `- | + `buttons in Number Input control
<img width="932" alt="Screen Shot 2021-04-13 at 9 35 51 AM" src="https://user-images.githubusercontent.com/25124000/114609504-bb170a00-9c53-11eb-88ec-c7e82ce35528.png">

**Comment by guigueb** [comment]
This issue - hiding the inc/dec icons/buttons - was briefly discussed in https://github.com/carbon-design-system/carbon/pull/7215.

The initial thought was to hide the inc/dec based on the step.
But step isn't really the right prop to use.

**Comment by tw15egan** [comment]
cc @carbon-design-system/design thoughts?

**Comment by aagonzales** [comment]
I would think the buttons would become `disabled` and not hidden especially if it's because of a user's action.
