### ISSUE TITLE
Should the tooltip for icon-only buttons receive pointer events?

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#8393]
### Summary

Currently (`carbon-components@10.32.1`/`carbon-components-react@7.32.1`), the label tooltip of icon-only buttons receive pointer events which also cuases them to stay open as long as the cursor is on the tooltip. This is contrary to a lot of tooltips from other websites and also to the native tooltips (at least on macOS).

It also means the user can click on the tooltip to perform the button's action. Depending on the length of the label (which is only controllable to a certain extent due to translation), this can drastically increase the button's click target and when paired close to other actions (which the tooltip then overlays) can also cause accidental triggers / clicks.

Current behaviour:
![Screen Recording 2021-04-14 at 13 28 32](https://user-images.githubusercontent.com/28265588/114703330-6fcd2c00-9d25-11eb-854a-4d0584fe2925.gif)

Compared to if tooltip wouldn't receiving pointer events:
![Screen Recording 2021-04-14 at 13 37 09](https://user-images.githubusercontent.com/28265588/114704238-aa839400-9d26-11eb-9a7a-c045d17f4ab3.gif)

Demo: https://sdjrj.csb.app/
(top – default Carbon behaviour; bottom – no pointer events for tooltip)

**Comment by joshblack** [comment]
@janhassel I believe that persisting the tooltip when the tooltip itself is hovered is a requirement of WCAG 2.1, specifically from [SC 1.4.13](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html)

> **The intent of this condition is to ensure that additional content which may appear on hover of a target may also be hovered itself.** Content which appears on hover can be difficult or impossible to perceive if a user is required to keep their mouse pointer over the trigger. When the added content is large, magnified views may mean that the user needs to scroll or pan to completely view it, which is impossible unless the user is able to move their pointer off the trigger without the additional content disappearing.

With respect to click, that's a great point, I do think that's a bug and should be addressed.

**Comment by joshblack** [comment]
@tw15egan went ahead and added this to the zenhub sprint btw! Wanted to make sure it got included since you opened that PR

**Comment by janhassel** [comment]
@joshblack @tw15egan I noticed that the `onClick` event doesn't fire anymore but the visuals still suggest that the button is being pressed.

![Screen Recording 2021-07-19 at 15 46 36](https://user-images.githubusercontent.com/28265588/126170020-f11465a0-8418-489c-badd-5d8654170510.gif)
