### ISSUE TITLE
overflow menu selectorPrimaryFocus should allow none value

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#8404]
### Summary

I would like to be able to use overflow menu without setting a default selection.  I also have not been able to set selectorPrimaryFocus successfully so default is always the first menu item. 

### Justification

When the overflow menu is used for only 2 actions, it is confusing UX for one item to be selected and then the other highlighted when you hover over it.  Everything looks selected. 

Please see UI at https://cloud.ibm.com/user/notifications

### Desired UX and success metrics

The overflow menu doesn't need a default selection highlighted. 

### "Must have" functionality

The overflow menu doesn't need a default selection highlighted. 

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests
N/A

### Available extra resources

N/A

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by emyarod** [comment]
the `selectorPrimaryFocus` prop appears to be functioning as expected, 
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) for easier testing and debugging?

as for disabling automatic focus within the menu, I believe this functionality is related to keyboard navigation and screen reader a11y requirements

**Comment by el-moshme** [comment]
@emyarod 
The user request was 'no default selection highlighted' since with 2 items, it makes the entire menu look lit up as you hover over the second item, especially with the red 'danger' highlighting.  Since that does not seem possible, based on your comment **_'related to keyboard navigation and screen reader a11y requirements'_** I am closing this issue.
