### ISSUE TITLE
Remove deprecated code from React package

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#8418]
Part of #8410 

This is an issue to track the effort to remove deprecated code from the React codebase

- Remove props that have been marked as deprecated
- Remove deprecated components
- Remove any code noted for removal for next major release

**Comment by tay1orjones** [comment]
Any prop marked deprecated in a `next/` should be double checked against the v10 version to understand if we should remove the deprecation in both or just v10. 

There are props we've marked as deprecated in v11, we're aiming to remove only the props deprecated currently in v10.

- [ ] `Accordion/Accordion.Skeleton.js`
- [ ] `Accordion/AccordionItem.js`
- [ ] `Button/Button.js`
- [ ] `Checkbox/Checkbox.js`
- [ ] `ContentSwitcher/ContentSwitcher.js`
- [ ] `DataTable/Table.js`
- [ ] `DataTable/TableExpandHeader.js`
- [ ] `DataTable/TableToolbarSearch.js`
- [ ] `DatePickerInput/DatePickerInput.js`
- [ ] `DatePickerInput/next/DatePickerInput.js`
- [ ] `Dropdown/Dropdown.js`
- [ ] `Dropdown/Dropdown.Skeleton.js`
- [ ] `InlineLoading/InlineLoading.js`
- [ ] `Modal/Modal.js`
- [ ] `Modal/next/Modal.js`
- [ ] `NumberInput/NumberInput.js`
- [ ] `NumberInput/next/NumberInput.js`
- [ ] `OverflowMenu/OverflowMenu.js`
- [ ] `OverflowMenuItem/OverflowMenuItem.js`
- [ ] `RadioTile/RadioTile.js`
- [ ] `Search/Search.js`
- [ ] `Search/next/Search.js`
- [ ] `Select/Select.js`
- [ ] `Slider/Slider.js`
- [ ] `StructuredList/StructuredList.js`
- [ ] `StructuredList/next/StructuredList.js`
- [ ] `Tab/Tab.js`
- [ ] `Tile/Tile.js`
- [ ] `Tile/next/Tile.js`
- [ ] `TimePicker/next/TimePicker.js`
- [ ] `TimePickerSelect/TimePickerSelect.js`
- [ ] `TimePickerSelect/next/TimePickerSelect.js`
- [ ] `Tooltip/next/DefinitionTooltip.js`

**Comment by tay1orjones** [comment]
### Remove deprecated components

- [ ] Icon
- [ ] SearchFilterButton/SearchFilterButton.js
- [ ] SearchLayoutButton/SearchLayoutButton.js
- [ ] TextInput/ControlledPasswordInput.js
- [ ] ToggleSmall/ToggleSmall.js
- [ ] Toolbar/Toolbar.js
- [ ] ToolbarSearch/ToolbarSearch.js
- [ ] TextInput.PasswordInput (need to just remove the namespaced export)
- [ ] MultiSelect.FilterableMultiSelect (need to just remove the namespaced export)

**Comment by tay1orjones** [comment]
### Remove any code noted for removal for next major release

* Defer the removal and move of `/next` folders, instead releasing with the v11 feature flag turned on.


- [ ] https://github.com/carbon-design-system/carbon/blob/6f7154a92cbb7968e6a91ae8669862b68b68c258/packages/react/src/components/CodeSnippet/CodeSnippet.js#L36
- [ ] https://github.com/carbon-design-system/carbon/blob/df28984b51589873eda02d209544371306b3da23/packages/react/src/components/ComboBox/ComboBox.js#L46
- [ ] https://github.com/carbon-design-system/carbon/blob/d545dd67206f1791e572e216db1098976cefc065/packages/react/src/components/Dropdown/Dropdown.Skeleton.js#L18
- [ ] https://github.com/carbon-design-system/carbon/blob/72731190d6bf854b09e3cdb5785799821908970f/packages/react/src/components/FormGroup/FormGroup.js#L22
- [ ] https://github.com/carbon-design-system/carbon/blob/addd1a738c3adb39d2c473ca6b1103bba0406ee5/packages/react/src/components/FormGroup/next/FormGroup.stories.js#L26
- [ ] https://github.com/carbon-design-system/carbon/blob/58b52021e00285c672805e6a0b6c58856f05daa1/packages/react/src/components/Notification/Notification.js#L137
- [ ] https://github.com/carbon-design-system/carbon/blob/c235676c508c5d3a9bb1fd50b64fe5e0ce59d408/packages/react/src/components/Slider/Slider.js#L215
- [ ] https://github.com/carbon-design-system/carbon/blob/c235676c508c5d3a9bb1fd50b64fe5e0ce59d408/packages/react/src/components/Slider/Slider.js#L224
