### ISSUE TITLE
Definition Tooltip styles

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#842]
The definition tooltip is currently positioned absolutely, however, the container element is not set to position relative which causes the positioning to be unpredictable. 

1. Set `position: relative;` to `.bx--tooltip--definition`
2. Use javascript to calculate height/position for `.bx---tooltip--definition__top` it needs to be set to `top: - "height of the text block"` and there is no way to know how tall this will be without javascript.

3. Come up with a css only solution I haven't thought of.

**Comment by joshblack** [comment]
For 3, could we do `transform: translateY(-100%)`?

**Comment by alisonjoseph** [comment]
I'll try it @joshblack !

**Comment by alisonjoseph** [comment]
Had to combine it with a negative margin equal to the text height, but it works. I'll create a PR. Thanks for the suggestion 🎉
