### ISSUE TITLE
SideNavDetails pass additional props to underlying container

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#8449]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Same as some other elements, pass additional props to the underlying container element.

### Justification

So the user can add additional attributes or functionalities.

### Desired UX and success metrics

Accept additional props, pass to underlying

### "Must have" functionality

Same as above

### Specific timeline issues / requests

Earlier the better.

### Available extra resources

Can make PR if proposal accepted.

**Comment by emyarod** [comment]
this enhancement makes sense to me, I think we can proceed with it @gptt916
