### ISSUE TITLE
Accessibility:The 3 dots icons are invisible when Windows high contrast mode is active.

### ISSUE THREAD

**Issue by yixjuan** [carbon-design-system/carbon#8458]
Component：OverflowMenu,OverflowMenuItem,
Screen capture:
<img width="118" alt="图片" src="https://user-images.githubusercontent.com/68119885/115343074-df3b9380-a1dd-11eb-8b6c-f3def0987ec5.png">
<img width="126" alt="图片" src="https://user-images.githubusercontent.com/68119885/115343087-e662a180-a1dd-11eb-905e-d681cb981c4a.png">

**Comment by tw15egan** [comment]
Hey there @yixjuan, can you confirm which browser are you using?

**Comment by yixjuan** [comment]
FireFox on Windows. and I use this component as follow.
```
<OverflowMenu type={'inline'} style={{ margin: '0 auto' }} flipped ariaLabel='open and close list of options'>
                                  <OverflowMenuItem requireTitle={true} itemText={'title'} onClick={this.onClick} />
  </OverflowMenu>
```

**Comment by tw15egan** [comment]
@yixjuan If you are on Firefox, you'll need to enable HCM as it is not supported out of the box. To do that, type `about:config` into the browser address bar, then search for `prefer-contrast` or `forced-colors` (recommended) and set that to true.

We have a PR updating our HCM media queries to use `forced-colors` as it has much better browser support than `prefers-contrast`. You can test the changes here https://github.com/carbon-design-system/carbon/pull/8489

Hope that helps!
