### ISSUE TITLE
Search Component Magnifier Icon Has Mixed Class Selectors

### ISSUE THREAD

**Issue by sjbeatle** [carbon-design-system/carbon#8460]
The latest version of carbon components (10.33.0) uses the following two selectors interchangeably in various areas of the CSS:
`bx--search-magnifier`
`bx--search-magnifier-icon`

The latest version of carbon angular components (4.48.2) and carbon react components (7.2.0) uses `bx--search-magnifier`, which worked correctly since at least carbon components `10.21.0` but is now broken in `10.33.0`.

Either carbon components will need to align on a single selector, or the framework libraries will need to update to accommodate both:
* https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Search/Search.js#L150
* https://github.com/IBM/carbon-components-angular/blob/master/src/search/search.component.html#L37

Any questions, please feel free to reach out. Thank you!

**Comment by tw15egan** [comment]
Rel #8101

**Comment by tw15egan** [comment]
I believe the easiest course of action would be for the Angular team to update the selector to `bx--search-magnifier-icon`. Normally, we reference both the old and new selectors in the styles and mark the old selector for removal in the next major release. This one seems like it slipped through the cracks. Going to transfer over to the Angular repo

**Comment by tw15egan** [comment]
Will be tracked in this issue: https://github.com/IBM/carbon-components-angular/issues/1821
