### ISSUE TITLE
Codify automated testing strategy for keyboard navigation

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#8464]
Currently the automated keyboard navigation testing is written in unit tests with Jest, typically using Enzyme, in a JSDOM environment.

> [JSDOM](https://github.com/jsdom/jsdom) is is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards, for use with Node.js. In general, the goal of the project is to emulate enough of a subset of a web browser to be useful for testing and scraping real-world web applications.

JSDOM is prone to unexpected behavior relating to focus, activeElement, etc. There's always a chance something hasn't yet been implemented or the implementation differs from what is available in some/most/all browsers. It stands to reason that if our tests are going to attempt to replicate the user's experience as much as possible, we should test keyboard navigation of components in a browser environment through an e2e testing framework like cypress, playwright, etc.

- What are the downsides of moving keyboard nav to an e2e setup? 
- Is it slow, unreliable (cypress native event support?), or other hurdles?
- Should we stick with JSDOM? Does it get us far enough to be reasonably confident knowing there's potential pitfalls?
- Document the outcome with reasoning and recipes in the testing section of `docs/style.md`

**Comment by joshblack** [comment]
Going to close this out as stale, feel free to re-open @tay1orjones!
