### ISSUE TITLE
Custom icon for UIShell header menu button

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#8467]
### Summary
I want to be able to customize the icon in the UIShell header menu button.

### Justification
The `HeaderMenuButton` component has hardcoded button icons `Menu20` and `Close20`. On larger screens, I want bigger icons. I cant't simply use CSS, otherwise the icon becomes unsharp.

(Screenshot: Left `Menu20` with css 32px width/height, right `Menu32` unchanged).
![css unsharp](https://user-images.githubusercontent.com/4472725/115522341-50398480-a28c-11eb-88f9-8c70ed30404d.png)

Others may want to have different icons.

I tried to replace the children of that component but the result remained unchanged.
```
return <HeaderMenuButton aria-label="Open menu" onClick={onClickSideNavExpand} isActive={isSideNavExpanded}>
    <span>foo</span>
</HeaderMenuButton>
```
```
const childrenPredefinedButton = <HeaderMenuButton aria-label="Open menu" onClick={onClickSideNavExpand} isActive={isSideNavExpanded}/>;
const childrenCustomizedButton = React.cloneElement(childrenPredefinedButton, null, React.createElement(Menu32, null));
return childrenCustomizedButton;
```

### "Must have" functionality
Customize the icon in the `HeaderMenuButton` component.

### Specific timeline issues / requests
The next possible minor release. E.g. 10.34.

**Comment by FabianPiconeDev** [comment]
I did a pull request with a possible solution https://github.com/carbon-design-system/carbon/pull/8468.
