### ISSUE TITLE
Improve test suite consistency with static analysis tooling

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#8475]
As we begin to refactor our test suite #8143, it would be nice if we could automate enforcement of a consistent test style, syntax, and best practices. This issue is to explore how we can further codify testing guidance (`docs/style.md`, #8144) via tools like eslint:

- Bring in `eslint-plugin-testing-library`
- Explore other rulesets and/or tooling

**Comment by tay1orjones** [comment]
`[eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest)` would also be a logicial addition here

**Comment by joshblack** [comment]
We currently use:

- `eslint-plugin-jest`
- `eslint-plugin-testing-library`
- `eslint-plugin-cypress`

Going to close this one out as I believe we've added those listed, let me know if I missed any!
