### ISSUE TITLE
Custom icon for search component

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#8480]
Actually the same issue as in #8467, but in the search component.

I would like to pass a custom icon for the search component. But in [Search](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Search/Search.js) the icon is hardcoded with icon `Search16`.

Maybe we can solve it like in https://github.com/carbon-design-system/carbon/pull/8468, or have you other suggestions?

**Comment by tw15egan** [comment]
cc @carbon-design-system/design
