### ISSUE TITLE
'@carbon/scss-generator@^10.13.0' is not in the npm registry.

### ISSUE THREAD

**Issue by henryennis** [carbon-design-system/carbon#8494]
Tried generating scss in @carbon/themes. This module is not available anymore. How would one go about customizing carbon css?

**Comment by joshblack** [comment]
Hi there, @xSCIven! 👋  What kind of customizations are you looking to apply?

**Comment by xSCIven** [comment]
Hi @joshblack. Thank you for your reply😊, apologies for the incorrect tagging. 

I am currently looking to change the spacing across all components, the colours and typography. Is this possible?

**Comment by joshblack** [comment]
@xSCIven no problem at all! Are you looking to update code specifically in `@carbon/themes` or overall in `carbon-components`?

For `@carbon/themes`, you can update the theme directly in Sass. For example:

```scss
$custom-theme: map-merge($carbon--theme--g100, (
  spacing-01: 4px,
  spacing-02: 8px,
  // etc
));
```

For `carbon-components`, you can specify the tokens directly as in:

```scss
$spacing-01: 4px;
$spacing-02: 8px;

@import 'path/to/carbon';
```

Or in a similar way to `@carbon/themes`, you can do the following:

```scss
@import 'path/to/carbon/scss/globals/theme-tokens';

$carbon--theme: map-merge($carbon--theme, (
  spacing-01: 4px,
  spacing-02: 8px,
));

@import 'path/to/carbon/components';
```

Hope this helps!

**Comment by joshblack** [comment]
Going to close this out as I believe the question has been addressed and we won't be publishing `@carbon/scss-generator` as an external package.

Feel free to comment or start up a discussion under the discussions tab if you'd like to chat more about this!
