### ISSUE TITLE
[Tooltip]: escape on button in tooltip propagates 

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#8502]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

If `Tooltip` is a child of a component that has an `onKeyDown` handler for 'Escape', escaping the Tooltip also calls the parent's `onKeyDown`. For example, when is a `Tooltip` in pal's `SidePanel` component, escaping the tooltip unexpectedly closes the panel. 

## Steps to reproduce the issue

You can see an example of this behavior here: 
https://codesandbox.io/s/frosty-fog-xuj18?file=/src/index.js
 where `onKeyDown` is called when you try to close the tooltip with escape.

**Comment by lji00** [comment]
With latest carbon version, the issue still exists in above sandbox example. https://codesandbox.io/s/frosty-fog-xuj18?file=/src/index.js

**Comment by abbeyhrt** [comment]
Per the comment above, it looks like the event is still propagating. Reopening to investigate.

**Comment by tay1orjones** [comment]
@edabe There is a workaround for this. Pass an `onKeyDown` prop the Tooltip and use `event.stopPropogation()` within the callback.

**Comment by lji00** [comment]
This specific issue has been fixed(Escape close the modal), but there is still an a11y issue with this fix as described in https://github.com/carbon-design-system/carbon/issues/9866
```When I tab to a tooltip on a modal and that tooltip contains an interactive element e.g. a link or a button, there is no way to tab out of the tooltip.```

**Comment by tay1orjones** [comment]
@lji00 This should be fixed via #10220, just published in v10.49.1. 

Here's two identical sandboxes demonstrating the fix with tooltip <kbd>esc</kbd> working as intended with both React v16 and React v17:

React 16: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react16-l1ih9
React 17: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react17-pydv4
