### ISSUE TITLE
[doc] List "persistent" prop for DataTable component on Storybook

### ISSUE THREAD

**Issue by marekdano** [carbon-design-system/carbon#8511]
### Summary

I found out from the implementation code that the TableToolbarSearch in DataTable can be expanded by adding `persistent` to `TableToolbarSearch` props. So a user won't need to click on the search icon to expand the search bar for typing a term.
 
It will be really useful if this is mentioned in Storybook.

I like that there is a prop for keeping the search bar expanded. Very useful!  

<img width="737" alt="Screenshot 2021-04-27 at 16 54 36" src="https://user-images.githubusercontent.com/1914165/116273419-a1a8ae80-a779-11eb-953e-25141f0fdc13.png">

**Comment by dezkareid** [comment]
I like to help with this one but I don't know if is a good approach add a story for controlled toolbar (adding some knobs to play with the component) and a section on Readme
