### ISSUE TITLE
Tile: Visual regression for selectable tiles

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#8523]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

`carbon-components@10.33.0` introduced a visual regression for selectable tiles. Every selected tile that is rendered after another selected tile misses its top border.

> Is this issue related to a specific component?

`SelectableTile`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The tiles should have a top border

> What browser are you working in?

Chrome 90

> What version of the Carbon Design System are you using?

`carbon-components@10.33.0`
`carbon-components-react@7.33.0`

## Steps to reproduce the issue

1. Use two or more `SelectableTile`s
2. Lay them out horizontally or with a spacing in between
3. Select them

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/stupefied-thunder-1qt2g

## Additional information

![Screen Recording 2021-04-28 at 11 05 42](https://user-images.githubusercontent.com/28265588/116378633-9e153600-a812-11eb-9208-664a835b596b.gif)

The visual design (horizontally layed out) is taken from the [Tile component usage guidelines](https://www.carbondesignsystem.com/components/tile/usage/#selectable)

**Comment by chriswatrous** [comment]
I see that this problem was fixed in https://github.com/carbon-design-system/carbon/pull/8529 but it looks like it was recreated in https://github.com/carbon-design-system/carbon/pull/9067.
