### ISSUE TITLE
TableToolbarSearch needs to be updated with latest magnifier classname

### ISSUE THREAD

**Issue by kaushalnavneet** [carbon-design-system/carbon#8535]
## Brief description
In the recent Carbon [feature update](https://github.com/carbon-design-system/carbon/pull/8101#issue-594014436), the previous `bx--search-magnifier` classname has been renamed to `bx--search-magnifier-icon`, however, the `TableToolbarSearch` [component](https://github.com/carbon-design-system/carbon-components-react/blob/c3bf0123a2a98ca84acfc7e86e69840eaf57a89e/src/components/DataTable/TableToolbarSearch.js#L64) is not updated accordingly and still using the old `bx--search-magnifier` classname.

- [x] `carbon-components-react`

> Is this issue related to a specific component? TableToolbarSearch

**Comment by tw15egan** [comment]
The commit you are linking to is over 2 years old. The `TableToolbarSearch` just renders a `Search` component, so the class name update is inherited. Here is a screenshot of the current markup.

![Screen Shot 2021-04-29 at 9 36 53 AM](https://user-images.githubusercontent.com/11928039/116586690-974bf900-a8ce-11eb-97f0-dfe48c8a7e9b.png)

Hope that helps!
