### ISSUE TITLE
Incorrect background color for UI Shell content element

### ISSUE THREAD

**Issue by nertzy** [carbon-design-system/carbon#8566]
This changes the background color for the UI Shell content tag.

Everywhere else, `$ui-01` is being replaced with `$layer`. This is the only place where `$ui-02` is being replaced. Is this an error?

_Originally posted by @nertzy in https://github.com/carbon-design-system/carbon/pull/8376#r625229281_

**Comment by tw15egan** [comment]
Determination was made [here](https://github.com/carbon-design-system/carbon/pull/8376#discussion_r613421974) to replace it with `$layer` since `$ui-02` will be deprecated in the next major release. Just want to get some confirmation from @aagonzales

**Comment by nertzy** [comment]
So, just to be clear, there was a conscious choice to change the background color here? I wasn't expecting a change of the variable name to actually lead to a user-facing color change, which then breaks things like inputs needing to be switched to the "light" variant in order to look correct. Does that make sense?

I'm wondering if it's actually incorrect for the main element to have a background color at all. It wasn't the sort of element that would get the "layer" background color treatment before, so I don't believe it should be getting it now either.

**Comment by aagonzales** [comment]
In layering of ui elements you should never go from `ui-background` to `ui-02`. In the Gray and White themes those token render as the same value but in the dark themes they are rendering as a different colors which makes it look like layer. 

I guess the question is, is this content are supposed to just be the page background or is it actually layer? 

![image](https://user-images.githubusercontent.com/11670886/118047991-3a762700-b341-11eb-825b-89632beff84c.png)
![image](https://user-images.githubusercontent.com/11670886/118048013-4235cb80-b341-11eb-9eca-bc6fdffbb143.png)

**Comment by tw15egan** [comment]
The token changes were reverted
