### ISSUE TITLE
Inconsistent camelcasing in datastore Icon

### ISSUE THREAD

**Issue by rabeehrz** [carbon-design-system/carbon#8572]
## What package(s) are you using?

- [x] `icons-react`

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/laughing-raman-xo5ke

The component should be DataStore instead of Datastore

I would be happy to open a PR if you could tell me where this needs to be changed if needed.

**Comment by emyarod** [comment]
given that the source is `datastore.svg` rather than `data-store.svg` I will need double check with design on whether or not that is intentional

**Comment by emyarod** [comment]
after checking with @conradennis, the naming for this asset is intentional and does not require an update!

**Comment by rabeehrz** [comment]
@emyarod I opened this issue because it was given as <DataStore32 /> in https://www.carbondesignsystem.com/guidelines/icons/library/. If you search for Data store and you copy the JSX, it copies DataStore32. Took me a while to figure out it was wrong. Maybe that needs to be changed. Thanks for looking into it <3

**Comment by emyarod** [comment]
yeah in the icon library the friendly names are displayed and they don't correspond with the naming convention of the source file, so we elected to leave it as-is
