### ISSUE TITLE
DatePicker: support custom mount point for the calendar widget + always visible

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#8574]
### Summary

We are currently trying to figure a paging/calendar widget implementation akin to what they are doing in Toggl / Google Ads

![image](https://user-images.githubusercontent.com/11244314/117000627-a7eedb80-ace1-11eb-9d7c-152f4ce4e257.png)
![image](https://user-images.githubusercontent.com/11244314/117000751-d967a700-ace1-11eb-9cc5-9678fd6d3c05.png)

We could probably make something from the ground up based on `FlatPickr` since it's already used in `carbon-components-react`, but I don't want to reinvent the wheel by trying to discover & fix everything you've already did on your side.

All that being said I tried to start flashing out something based on your implementation of range `DatePicker` with our usage in mind (no design document yet, just trying to feel out the problem domain) and got to a point where I think that it's doable if I'd be able to tell the `DatePicker` to render the widget into my container and to keep it always visible.

Here is a screenshot to illustrate my state of affairs. The idea is that something like this would be the whole pop-over content & the pink area is where the calendar widget would be rendered.
![image](https://user-images.githubusercontent.com/11244314/117001545-c6a1a200-ace2-11eb-8170-8ca237d63bad.png)

### Specific timeline issues / requests

Undefined on my side as far as I can tell…

**Comment by kubijo** [comment]
update: just got a preview of our upcoming design: 
![image](https://user-images.githubusercontent.com/11244314/117007174-9c9fae00-ace9-11eb-836c-6cce288b7f76.png)

**Comment by kubijo** [comment]
The first thing that I've tried was sifting through the sources and the [intended function of that prop seems to be in line with what I need](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DatePicker/DatePicker.js#L130), but [the implementation is only about shifting of the position](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DatePicker/plugins/appendToPlugin.js#L12) after the widget is rendered, but I need it inside the `div` with a static position to have a normal document flow in the final pop-over.

Also while we're at it ... you're doing [some pretty shady stuff inside the component](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DatePicker/DatePicker.js#L584)… it creates instances of `DatePickerInput` just to compare the `type` attribute.

This is ineffective and it produces validation errors if you're using the component in any other way than the simplest one from your storybook...

eg:
```tsx
<DatePicker datePickerType="range">
    <div className={css.half}>
        <Button … />
        <DatePickerInput … />
    </div>

    <div className={css.half}>
        <DatePickerInput … />
        <Button … />
    </div>
</DatePicker>

**Comment by emyarod** [comment]
since we don't currently export any date picker primitives it would be kind of hacky to try to implement the design you have with the current Carbon date picker rather than building something custom with flatpickr as you mentioned. not sure if there would be plans to support this kind of spec but will defer to @carbon-design-system/design on that

as for the date picker input type comparisons, that seems to stem from issues with react hot loader https://github.com/carbon-design-system/carbon/issues/2630 https://github.com/carbon-design-system/carbon/pull/5929/files#diff-cdd24749324fa3c96fd2449e36e26ded7dbbbfa2512feec1601b9752e6ef7fcc which can be discussed in a separate issue from this proposal

**Comment by kubijo** [comment]
> as for the date picker input type comparisons, that seems to stem from issues with react hot loader #2630 https://github.com/carbon-design-system/carbon/pull/5929/files#diff-cdd24749324fa3c96fd2449e36e26ded7dbbbfa2512feec1601b9752e6ef7fcc which can be discussed in a separate issue from this proposal

Will you triage this in accordance with your processes?
There are more instances of this kind of strange work (last time it was discarding the children of `RadioButtonGroup` and instantiating your own `RadioButton`)

It seems to me that leaning more into react context APIs would be beneficial in these places instead of trying to hack around the passed-in children since these kinds of solutions introduce complexities and hidden dependencies, and you are essentially creating a new bootstrap where consumers need to mirror **the right markup™** correctly

**Comment by emyarod** [comment]
yeah I have applied the open proposal label to this ticket. regarding radio button implementation and the lack of React Context usage, I believe those components predate the current context API but I agree there are components that can be targets for refactoring. one other aspect we need to consider though is how strictly the visual specs are intended to be, which would have also affected how the components were originally constructed

**Comment by kubijo** [comment]
> regarding radio button implementation and the lack of React Context usage, I believe those components predate the current context API

That was just an example of the top of my head since I've just upgraded `carbon-components-react` to version where a fix to that component has landed ;-)

**Comment by jnm2377** [comment]
Hi @kubijo 👋🏽 Thanks for opening this issue. At the moment, we have a lot of accessibility concerns with Flatpickr and are looking into moving away from it. As we sort through the accessibility issues, we'll take this design into consideration. Going to close this for now. 😄
