### ISSUE TITLE
[Expandable DataTable] - table cell border lines aren't visible enough on hover

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#8576]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

In all of our themes, the expandable data table border isn't distinguishable enough when you hover on the expanded row.
The hover token should probably be updated for this style (unsure what the new token should be).

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the border to be visibly darker or lighter, depending on the theme.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

latest

## Additional information

![Screen Shot 2021-05-04 at 11 49 04 AM](https://user-images.githubusercontent.com/32556167/117040242-4d4c8400-accf-11eb-9462-084bcb0387b5.png)
![Screen Shot 2021-05-04 at 11 48 54 AM](https://user-images.githubusercontent.com/32556167/117040244-4e7db100-accf-11eb-87be-8bf15487c6de.png)
![Screen Shot 2021-05-04 at 11 48 40 AM](https://user-images.githubusercontent.com/32556167/117040247-4f164780-accf-11eb-9edf-35576785f2e8.png)
![Screen Shot 2021-05-04 at 11 48 26 AM](https://user-images.githubusercontent.com/32556167/117040248-4f164780-accf-11eb-9ec2-c637a00fa2b6.png)

**Comment by jnm2377** [comment]
cc: @carbon-design-system/design any thoughts on this?

**Comment by aagonzales** [comment]
Lets do `adjustLightness(ui-03, -6)` for that border on hover. Not sure if that needs to be tied to a token or not. If it does then we need to make a new one. 

![image](https://user-images.githubusercontent.com/11670886/117169023-52bcd380-ad8e-11eb-9a7c-c1075550fca9.png)

**Comment by tw15egan** [comment]
🙂  somewhat related 🙃

Wonder if we need to update the zebra hover token?

![zebra-hover](https://user-images.githubusercontent.com/11928039/117191931-02497400-ad96-11eb-8be5-a7f087976382.gif)
