### ISSUE TITLE
Overflow menu links not working in safari

### ISSUE THREAD

**Issue by leseaubrey** [carbon-design-system/carbon#8582]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

**Describe in detail the issue you're having**
'a' tag links not working in Safari. When clicked the menu closes rather than navigating to the linked page.

**Is this issue related to a specific component?**
Overflow Menu

**What did you expect to happen?**
Browser navigates to linked page rather than closing the overflow menu.

**What browser are you working in?**
Safari Version 14.0.3

**What version of the Carbon Design System are you using?**
"carbon-components": "^10.28.0"

## Steps to reproduce the issue
Issue can be reproduced on the netlify UI Demo:
https://the-carbon-components.netlify.app/?nav=overflow-menu

**Comment by joshblack** [comment]
Hi there! 👋  Can confirm the issue but unfortunately, the vanilla codebase is not being actively maintained 😞 We're happy to accept any contributions to address this but our team won't be able to fix this issue. I'm going to label this as a wontfix and close the issue as a result. I'm so sorry about that 😞
