### ISSUE TITLE
PlayOutlineFilled32 icon doesn't render correctly when used in a Button

### ISSUE THREAD

**Issue by tomleah** [carbon-design-system/carbon#8583]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `@carbon/icons-react`

## Detailed description

> Describe in detail the issue you're having.

When using the PlayOutlineFilled32 icon within the Carbon Button component (React) the whole circle appears filled with only a slight outline of the play button. When I use the icon outside of the button component it renders with a clear play icon. (Easier to see in [the sandbox](https://codesandbox.io/s/playoutlinefilled32-mpie4?file=/src/App.js:210-222))

We are using a ghost button but the issue remains when using the default button kind.

> Is this issue related to a specific component?

React `<Button>` used with `renderIcon` 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The play icon within the circle to be clearer. 

> What browser are you working in?

Chrome (Version 90.0.4430.93)

> What version of the Carbon Design System are you using?

Reproduced in 10.34.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Robotic Process Automation 2Q release.
It's likely we can use another icon temporarily.

## Steps to reproduce the issue

Use the Button component with the renderIcon prop and add the PlayOutlineFilled32 icon
`<Button renderIcon={PlayOutlineFilled32}>`

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/playoutlinefilled32-mpie4

## Additional information

![image](https://user-images.githubusercontent.com/5465397/117153800-367f5d80-adb3-11eb-9732-300adcba043d.png)

**Comment by emyarod** [comment]
this appears to be due to the way the 32x32 SVG is constructed, the workaround for now would be to use the 16x16 asset

**Comment by joshblack** [comment]
I think something else that is contributing is the `fill: currentColor` being applied in CSS

https://user-images.githubusercontent.com/3901764/117166711-3ddf4080-ad8c-11eb-9e40-a1421244e73f.mov

**Comment by emyarod** [comment]
yeah I'm currently modifying that but there also seems to be a recent regression which I'm looking into

**Comment by tomleah** [comment]
@emyarod thanks for the work around! Will we use that in the meantime 😄
