### ISSUE TITLE
Border for Tag and InlineCodeSnippet in print mode

### ISSUE THREAD

**Issue by CeceliaYu** [carbon-design-system/carbon#8590]
### Summary

Tag and InlineCodeSnippet in print mode does not include any border. They looks perfectly ok, but under print(preview) mode, there's no boundary compared with the rest of plain text. This is particularly bad when there's more than one tag in paragraph. A sample code can be found via https://18fpe.csb.app/. Enter print preview mode with `Cmd + P`. It looks like this:

**---- browser view ----**
![image](https://user-images.githubusercontent.com/5575493/117265731-1de07780-ae87-11eb-9a30-b1a5150a3ad6.png)

**---- print preview ----**
![image](https://user-images.githubusercontent.com/5575493/117265764-2769df80-ae87-11eb-8a29-ab14373ebe63.png)

 

### Justification

App with Tag and InlineCodeSnippet in print mode needs boundary. 

### Available extra resources
To elaborate more, the implementation could be something like:
```
@media print {
  .bx--tag {
    background: #e0e0e0 !important; //optinal
    border: 1px solid #e0e0e0;
  }
}
```

**Comment by joshblack** [comment]
Hi there, @CeceliaYu! 👋 

Unfortunately, print mode is something that we're not currently supporting. This could definitely be something that we look at in the future, but right now it's not something that we're actively testing for / supporting.

**Comment by CeceliaYu** [comment]
Understand, thanks @joshblack, I'll add the css to our implementation then. Looking for later release with print mode support.
