### ISSUE TITLE
Shouldn't invalid inputs use ErrorFilled16 instead of WarningFilled16 icon?

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#8591]
Currently, all inputs that support an invalid state use the `WarningFilled16` icon.
![image](https://user-images.githubusercontent.com/28265588/117303785-62ffac00-ae7d-11eb-9711-9af2b1926074.png)

Error notifications use the `ErrorFilled16` icon whereas the `WarningFilled16` icon is used for warning notifications.
![image](https://user-images.githubusercontent.com/28265588/117303853-73b02200-ae7d-11eb-9481-140995fd9b63.png)
![image](https://user-images.githubusercontent.com/28265588/117304063-a22dfd00-ae7d-11eb-9ce0-ea7d06f62ca4.png)

What is the reason for this / is there guidance around when to use which icon?

**Comment by joshblack** [comment]
cc @carbon-design-system/design

**Comment by thyhmdo** [comment]
@janhassel there would be an update on this, but there are alias icons that may look the same but indicate different use cases. 

We would use Error to indicate a severe event that needs Indicates a severe event that needs immediate attention / Used for: critical situations, emergencies urgent alerts. Meanwhile, we use Warning to indicate an Error (often inline) that needs immediate attention / Used for: warnings, errors, alerts, failure
