### ISSUE TITLE
Tooltip on the PageHeader-Tag component does not close when clicked on the right of it

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/carbon#8593]
## What package(s) are you using?

- [ ] `carbon-components`
- [ X] `carbon-components-react`
- [ X ] 'IBM-cloud-cognitive'
## Detailed description

> Describe in detail the issue you're having.
Using a PageHeader with a list of tags, when they collapse becase too many and opening the Tooltip on the Tag component does not close when clicked on the right of it (appear also to be on the right of the main Grid container).

> Is this issue related to a specific component?
PageHeader (carbon/ibm-cloud-cognitive": "^0.31.0), Grid, Tag,

> What did you expect to happen? What happened instead? What would you like to
> see changed?
When clicked outside of it the tooltip close. Maybe even when clicked again the tag that open it.

> What browser are you working in?
Chrome Version 90.0.4430.93 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
10.25
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
Open the tooltip and close it in the 4 directions

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/shy-sun-0e2ww

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Hey there @ninjasun it seems like this issue may lie in the `ibm-cloud-cognitive` repo, as our `tag` component does not natively have a tooltip and may need to be fixed in the `TagSet` or `PageHeader` components.

**Comment by ninjasun** [comment]
I see. The PageHeader takes a list of tag as prop and it wrap them inside a TagSet. It will be great to have access to it for customization or maybe just pass the whole set.

**Comment by tw15egan** [comment]
Yes, I believe you'd want to create an issue over there. Here is a link: https://github.com/carbon-design-system/ibm-cloud-cognitive

Hope that helps!
