### ISSUE TITLE
NumberInput: type for imaginaryTarget

### ISSUE THREAD

**Issue by OlgaShishkanova** [carbon-design-system/carbon#8667]
## Detailed description

In NumberInput I try to get the new value in 'onChange' function using 'evt.imaginaryTarget.value' as it's described in Docs (https://react.carbondesignsystem.com/?path=/docs/components-numberinput--default). 

But I get the type error:
`Property 'imaginaryTarget' does not exist on type 'ChangeEvent<HTMLInputElement>'`

Could you please add the type for imaginaryTarget?

## Additional information

- Screenshots
<img width="490" alt="Screenshot 2021-05-12 at 17 12 54" src="https://user-images.githubusercontent.com/26384265/117999640-57acf480-b345-11eb-935f-73948cf5cf15.png">

- Codesandbox

https://codesandbox.io/s/epic-tu-3ogu2?file=/src/App.tsx

**Comment by andreancardona** [comment]
@OlgaShishkanova 

Hey Olga - do you mind putting this into a codesandbox? And I can look into it for you :) 

Thanks!

**Comment by OlgaShishkanova** [comment]
Hello @andreancardona 
I've edited the description and added the link to the Codesandbox :)

**Comment by MaxJaison** [comment]
Any updates on this?  I have similar issue in React app, i do not know what type to use for event property in onChange.
` onChange={(event: unknown) => updateTimeInterval(event)}`

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/blob/fdc54683ec9aeb204d82e208996d688705f76547/docs/migration/v11.md#L931-L933
