### ISSUE TITLE
Tabs in mobile version auto expanded

### ISSUE THREAD

**Issue by gracelo** [carbon-design-system/carbon#867]
## Detailed description

> Is this issue related to a specific component? 
Tabs component

> What did you expect to happen? What happened instead? What would you like to see changed?
1.  I go to:
http://react.carbondesignsystem.com/?selectedKind=Tabs&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

2.  Select Tab 1 by default.

3.  Select Tab 3.

4.  Narrow the browser so it is in mobile version.  The tabs become a dropdown list.
Note the list is auto-expanded.

I expect the list is collapsed at the beginning until I click on it.

> What browser are you working in? 
FF but same for other browsers.

> What version of the Carbon Design System are you using? 
    "carbon-components": "^8.18.3",
    "carbon-components-react": "^5.41.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
console

(I don't seem to see any labels that I can choose)

**Comment by jenschlot** [comment]
this one is making the new docs homepage design not look great in Mobile...and hindering the view of content.

![image 19](https://user-images.githubusercontent.com/11622088/41623253-c8819252-73d7-11e8-9408-85a1e64ab4bd.png)

Instead of collapsed by default, it is expanded.
