### ISSUE TITLE
Text Input - Invalid state

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/carbon#8680]
Hi there!

I'm a UXE on C&CS and currently working on building [common components/patterns for the C&CS library](https://github.com/carbon-design-system/ibm-cloud-cognitive).

I've been working a lot on the [Create patterns](https://www.carbondesignsystem.com/community/patterns/create-flows/) for modals and side panels and notice that with proper form validation, the `TextInput` components will push down /expand the height of the modal/panel.

This behavior isn't obvious if you have an `optionalText` prop because it replaces this text with the invalid text, however, if you do not utilize this prop, you can see the height change. 

My question is -- is there anyway to update the `TextInput` component so that it accounts for the additional space needed for the invalid text? This way it doesn't add additional height to whatever container the component is being used in?

**Comment by dakahn** [comment]
Hey! Thanks for reaching out. I'm not very familiar with the C&CS Create Patterns library, but to answer your question -- potentially a breaking change like that could be proposed. Could a fixed height be set on the text input's container?

**Comment by laurenmrice** [comment]
Do you have a working example in code that you could share?

The container size of the modal/side panel should not change in height if a text input inside has an invalid state change. The content within the modal/side panel should shift to accommodate the invalid state of the text input, and scrolling can be implemented if the content needs to overflow.

**Comment by sydrosa** [comment]
Hi! Here's an example of the behavior:

https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-released-createmodal--with-form-validation

If you are validating a modal, and you tab off of the required field, the invalid text appears. But it actually increases the height of the input field's container, which in turn increases the height of the modal. I'm sure there's some additional considerations to be made, but it _would_ be nice if there was already space in the input field to accommodate invalid text, which doesn't change the height of the input field's container.

**Comment by laurenmrice** [comment]
Thanks for the example! The invalid state is working how we intended: to push down content inside of the fixed modal container.

One thing you could do if you don't want content to shuffle based off of invalid states, is having a 32px height size for inputs and having 32px padding between them. This way, if an invalid state were to appear for an input, no content would be pushed down because it fits within the given space.
![Modal.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/f6a5bf16-568e-45f9-9bc9-d1a1e2e5922b)

**Comment by lee-chase** [comment]
Not sure I understand this workaround, surely the extra padding will also get pushed down.

Another workaround would be to set the helperText to something that is not visible to the user e.g. &nbsp; which reserves the vertical space needed for the invalidMessage.
