### ISSUE TITLE
NumberInput: Allow clients to supply an inc/dec value (not to be confused with the 'step' prop)

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#8689]
### Summary

NumberInput: Allow clients to supply an inc/dec value (not to be confused with the 'step' prop)

This issue is discussed/related to the following issues.
Issue [6930](https://github.com/carbon-design-system/carbon/issues/6930)/PR [7214](https://github.com/carbon-design-system/carbon/pull/7215) feat(numberinput): add support for "any" value for step prop
Issue [8386](https://github.com/carbon-design-system/carbon/issues/8386)/PR [8646](https://github.com/carbon-design-system/carbon/pull/8646) feat(number-input): add option to hide steppers

The mozilla definition of 'step' is for validating value (and for inc/dec the value... to the next valid value).
Examples:
step value of 1: value is valid only if it is an integer
step value of 10: value is valid only if it is an integer that is a multiple of 10
step value of 0.1: value must end in (.0, .1, .2, .3, .4, .5, .6, .7, .8, .9)
step value of 0.2: value must end in (.0, .2, .4, .6, .8)
[step is kinda like a modulus validator, value is only valid if value/step = zero]
[step is also used to inc/dec value... to the next valid value - given { value:"1.111", step:"1" } an increment will set value to "2" not "2.111"]

What is needed is an inc/dec value (not validating value), lets call it 'stepIncDec' for now.
Supplying 'stepIncDec' will...
- be the number by which value is incremented/decremented
- when set to zero disallows incremented/decremented (removing up/down button and key actions) `basically what hideSteppers does`
- if stepIncDec set, step is defaulted to 'any'

Examples:
stepIncDec set to 1.5;
- value 10 becomes 11.5,
- value 1 becomes 2.5,
- value 1.1 becomes 2.6,
- value 1.11 becomes 2.61

As long as we are here there should be another prop added to NumberInput... scale.
Reported in [8690](https://github.com/carbon-design-system/carbon/issues/8690) NumberInput: Allow clients to supply a scale prop

### Justification

IBM Cognos uses this in some of its widgets.
Allowing client to specify an inc/dec value.

### Desired UX and success metrics

- user supplies an inc/dec value for a widgets numeric input
- user uses the inc/dec icons, or the up/down keys in the numeric input
- user expects the value to be increased or decreased by the inc/dec value

### "Must have" functionality

pretty small set of requirements, so all of it.

### Specific timeline issues / requests

asap

### Available extra resources

maybe

**Comment by sstrubberg** [comment]
Closing out based on our conversation from Office Hours!
