### ISSUE TITLE
Add onOpen event handler to DatePicker

### ISSUE THREAD

**Issue by grahamharper** [carbon-design-system/carbon#8698]
### Summary

Add `onOpen` event handler to React DatePicker to allow hooking into when the date picker opens.

### Justification

Developers may want to trigger some custom cose based on the calendar picker being opened. DatePicker already exposes an `onClose` event handler and `onOpen` is a handler offered by Flatpickr.

For our specific use-case, we have a legacy application that renders modal content inside an iframe. Then content can contain a form with a DatePicker. If the modal content happens to be shorter than the height of the DatePicker, then the DatePicker is not usable. If we can know when the picker is open, we can add additional height to the iframe temporarily, to allow the picker be usable, restoring the original height when it's closed.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

`onOpen` event handler on React DatePicker

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

We have a small squad of developers available to contribute code to this.

**Comment by tay1orjones** [comment]
@grahamharper Sounds like a good idea to me 👍  I opened a PR for it https://github.com/carbon-design-system/carbon/pull/8705
