### ISSUE TITLE
1px gap with breakpoints & media queries

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#8699]
@carbon/elements@10.34.0

I am mainly using the grid classes for responsive behavior. But for some elements, I am using media queries that listens to the grid breakpoints:

```
@media (max-width: $carbon--grid-breakpoint-large-width) {
   // ...
}
@media (min-width: $carbon--grid-breakpoint-large-width) {
   // ...
}
```
I extract the variables like so
```
@import '~@carbon/elements/scss/layout/_breakpoint.scss';
$carbon--grid-breakpoint-large: map-get($carbon--grid-breakpoints, 'lg');
$carbon--grid-breakpoint-large-width: map-get($carbon--grid-breakpoint-large, 'width');
```
The problem is, both media queries are applied on one exact witdh (1056px, which is for the large breakpoint).

I simply would like to have a -1px calculation on the max-width media query. But I am receiving a **rem** value from the variable. I'm also not sure if rem/px calculation is even possible, i did not found a concrete working example for this. When I do a `calc($carbon--grid-breakpoint-large-width - 1px)`, the media query does not apply on any browser width. Tried also with `calc(#{$carbon--grid-breakpoint-large-width} - 1px)`.

As a workaround I hardcoded the breakpoint px value in a new variable, and subtracted 1px, generating a new variable.

Can you maybe just serve an extractable px value from the breakpoint variable tree, instead of only a calculated rem value? Or serve a reverse calculator like `carbon--px($remValue)`?
```
// '~@carbon/elements/scss/layout/_breakpoint.scss';
$carbon--grid-breakpoints: (
// ...
  lg: (
    columns: 16,
    margin: carbon--rem(16px),
    width: carbon--rem(1056px),
  ),
// ...
```
Or have you other suggestions?

**Comment by tay1orjones** [comment]
The `rem` function uses the `$base-font-size` as the root value for the calculation.

https://github.com/carbon-design-system/carbon/blob/428d3d5082dc7693f3685b279bd85bf170ea24e8/packages/layout/scss/modules/_convert.scss#L25

Would it work for you to extrapolate a pixel value from rems by stripping the units, multiplying, and then adding the px unit back?

```scss
.example {
     width: (($base-font-size / 1px) * ($some-rem-value / 1rem)) * 1px;
}
```

**Comment by FabianPiconeDev** [comment]
Yes that worked indeed 

```
@import '~@carbon/elements/scss/layout/_breakpoint.scss';
@import '~carbon-components/src/globals/scss/_typography.scss';
$carbon--grid-breakpoint-large: map-get($carbon--grid-breakpoints, 'lg');
$carbon--grid-breakpoint-large-width: map-get($carbon--grid-breakpoint-large, 'width');
$carbon--grid-breakpoint-large-width-px: (($base-font-size / 1px) * ($carbon--grid-breakpoint-large-width / 1rem)) * 1px;
$carbon--grid-breakpoint-medium-width-end-px: $carbon--grid-breakpoint-large-width-px - 1px;
```
`$carbon--grid-breakpoint-medium-width-end-px` then is compiled to `1055px` as expected.

Are you considering to add a function for reuse, in a next release?

**Comment by tay1orjones** [comment]
> Are you considering to add a function for reuse, in a next release?

I don't think so. I'd like to follow up on your root issue of configuring these media queries - does the `carbon--breakpoint()` function not work for your use case? It's provided to facilitate writing media queries using the built in breakpoint token values. 

https://github.com/carbon-design-system/carbon/blob/9e2fc02ae1d0758a28fbc48764ae34907fb183c7/packages/layout/scss/_breakpoint.scss#L236-L246

Usage typically looks something like this:

```scss
.simple-example {
    width: 1rem;
    
    @include carbon--breakpoint(md) {
      width: 2rem;
    }
  }
```

**Comment by FabianPiconeDev** [comment]
Yes, but with a drawback. When I do ..
```
@include carbon--breakpoint(md) {
    // ...
}
@include carbon--breakpoint(lg) {
    // ...
}
```
.. I have to deal with inherited rules. Both media queries would be applied on large screen because the function compiles to `min-width`. Example: I want an element to be positioned `absolute` only on `md`, so I would have to reset it to eg. `initial` on `lg`.

Using `carbon--breakpoint(..)` would generate the same phenomena that confused me a time ago, when using breakpoiont classes `bx--col-sm-4 bx--col-md-4 bx--col-lg-8`. Carbon overrides rules for `md` min-width when I am in `lg` state, where only `lg` is what I am interested in.

I would prefer a more isolated handling like described initially, with a min/max separation between the breakpoints.
Can I suggest a new function eg. `carbon--breakpoint-isolated(..)` as an alternative, which considers min-width and max-width for a specific breakpoint?

**Comment by tay1orjones** [comment]
@FabianPiconeDev There's actually one already, `carbon--breakpoint-between`

https://github.com/carbon-design-system/carbon/blob/9e2fc02ae1d0758a28fbc48764ae34907fb183c7/packages/layout/scss/_breakpoint.scss#L188-L192

There are other utility mixins as well - I recommend reading through the `_breakpoint.scss` source to view all of what's available.

**Comment by tay1orjones** [comment]
I'm going to close this as I think we've narrowed down the issue. Please reopen it if you feel this is unresolved. Thanks!

**Comment by FabianPiconeDev** [comment]
@tay1orjones Unfortunately this didn't work for me. How can I reopen the issue?

When I do
```
@import '~@carbon/elements/scss/layout/breakpoint';

@include carbon--breakpoint-between(md, lg, $carbon--grid-breakpoints) {
   // ..
}
```
it is compiled to 
```
@media (min-width: null) and (max-width: null) {
   // ..
}
```
I debugged the calculations
https://github.com/carbon-design-system/carbon/blob/d4512961a83cf1465fc4de536a3ce8e82be39ba5/packages/layout/scss/_breakpoint.scss#L201

https://github.com/carbon-design-system/carbon/blob/d4512961a83cf1465fc4de536a3ce8e82be39ba5/packages/layout/scss/_breakpoint.scss#L206

`$min-width`/`$max-width` are both `null`. When I remove the `+ 0.02` / `- 0.02` calculations, the results are `42rem`/`66rem`. For me this looks like a bug in the calculation. Or am I using the mixin wrong?
