### ISSUE TITLE
[Notification] Actionable/Persistent variant

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#8703]
### Summary

ToastNotification was updated as part of #8406 to use only an accessible `role` of `alert`, `status`, or `log` in v11. This change meant that Toast would no longer accept interactive elements/buttons/children. This leaves InlineNotification as the only notification component to allow action buttons.

This leaves a big gap for teams needing actionable notifications that mimic the visual styling of a Toast notification.

The proposal here is to add a new notification variant with the following requirements:

- Mimics the visual styling of Toast
  - has constrained width
  - has box shadow
  - is not `position: relative;`
- Action buttons are required, with potential visual design to indicate primary vs secondary actions
- Always has `role` of `alertdialog`
- Can optionally automatically take focus
- Can optionally be closed via pressing <kbd>esc</kbd>
- No `timeout` option
- Proposed naming includes `PersistentNotification`, `AlertDialogNotification`, `ActionableNotification`

I originally intended to deliver this as part of #8560, but it was clear this needed visual/ux design.

**Comment by kingtraceyj** [comment]
For now, we are going to constrain the amount of action buttons in the new toast to only one action. We had a [few iterations](https://app.mural.co/invitation/mural/ibm14/1622819962431?sender=traceyking&key=86333e9c-91f1-4e79-941e-e7480fa3c47d) of what two action buttons would look like but after much discussion we believe it would be best to stick to one for the time being. We couldn't find that many use cases for two and the ones we did, the actions seemed redundant. 

We will stick with ghost button like we do in inline notifications and the original toast design. It doesn't draw too much attention away from the user's main work flow like the primary or secondary. 

### Visual specs for toast with actions
Low contrast (uses light theme ghost button)
![image](https://user-images.githubusercontent.com/20582179/121111656-e68e1f00-c7d4-11eb-91fe-83605233452f.png)

High contrast (uses grey 90 ghost button)
![image](https://user-images.githubusercontent.com/20582179/121111669-ed1c9680-c7d4-11eb-8d09-3e7d031679e2.png)

**Comment by joshua-vaughn** [comment]
Cloud Pak for Data and the Cloud Pak Platform have already been including links in toast notifications as these are always accessible later from the Notification list page
