### ISSUE TITLE
DataTable: Controlled selection state

### ISSUE THREAD

**Issue by imp-dance** [carbon-design-system/carbon#8715]
### Summary

I'd be nice if there were any ways to control the selection state outside of the component. Passing in something like `selected` and `onSelect` would suffice. 

Just to follow the format and clarify, this is just a developer upgrade - not really a visual update. 

### Justification

Internally on our team, we're using a wrapper component for DataTable (as I would assume most implementations do). 

This component handles a lot of different stuff, and one of them is selection. I'm able to catch the click events of the selection by just doing something like `onSelect={(e) => { ...(some code)... getSelectionProps().onSelect(e); }`. 

The problem here is we also want to be able to clear that selection outside of the component - for example after changing the page (dynamically using a new fetch). 

Sometimes we also end up in a `0 items selected` state after removing selected items from the list - where the batch actions menu stays open even though there are no items selected. The only way I see possible to close the batch menu at that stage, is targetting the button using `document.querySelector().click()`. Here - it's easy to get into timing issues though - and so we need to actually put this on a small timeout.

This workaround feels very messy, and although *it works*, something much preferable would be just being able to control that state using local state outside of the component with props. 

### Desired UX and success metrics

Props like `selected` and `onSelect` on the DataTable component to control the selection state in a parent component. The batch actions menu should also keep on top of this external state, and automatically hide if no items are selected - much like the current implementation does. 

### "Must have" functionality

Props for controlling the selection state of the DataTable.

### Specific timeline issues / requests

Would obviously be nice to have, but like previously stated - our current solution *works*, it's just unfortunate to end up on the `0 items selected` state, and having to use `document.querySelector` to work around the current implementation.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Not much, at the minute - but I'd love to contribute at some point soon.

**Comment by emyarod** [comment]
most likely you would need to implement this with a [custom state manager](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager), meaning you would be implementing that logic using Carbon table primitives like `Table`, `TableHead`, `TableRow`,  etc. rather than using the built in state manager in `DataTable`, if that makes sense

**Comment by imp-dance** [comment]
I see! This makes sense, and I guess clears up my question/suggestion. Thanks @emyarod , I'll take a look at the Codesandbox and see if we can implement something similar.
