### ISSUE TITLE
Skeleton text should reflect the Carbon font setting

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#8722]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

The SkeletonText component has just two sizes default and large, however, there are many different Carbon font sizes and line heights. The SkeletonText component should be based on the current Carbon font settings.

Clarify if you are asking for design, development, or both design and
development.

This could be achieved by development alone.

### Justification

It looks bad when a font, other than the ones matching the size options, replace the skeleton. It causes pages to vertically jump and is visually distracting.

### "Must have" functionality

It must be possible to use a skeleton in place of productive-heading-06 without having to manually configure the height and vertical gaps between lines of text.

**Comment by theiliad** [comment]
Hi @lee-chase 👋🏻  thanks for reporting this

A possible solution could be that we use `font-size: inherit;` and/or `line-height: inherit;`

Would this work for you?

Let us know

**Comment by lee-chase** [comment]
Possibly @theiliad although it would be inefficient and potentially fragile to do this outside of the Carbon CSS

**Comment by lee-chase** [comment]
In that case @theiliad 

Matching the line-height for reserved space and the font-size or line-height for the skeleton animation is fine by me.

I think line-height for both reserved space and animation looks nicer.

**Comment by sstrubberg** [comment]
Hey @lee-chase thanks for submitting this proposal. Unfortunately, due to constraints with our roadmap and limited resources, we won't be able to take this proposal on at this time. I'm going to close this for now, but if you'd like to submit a PR against it, we'd gladly consider it and re-open the issue. Thanks again!
