### ISSUE TITLE
Multiple StructuredList with selection creates conflicts if the keys are the same

### ISSUE THREAD

**Issue by janamano** [carbon-design-system/carbon#8725]
If I have multiple StructuredList Components with selection enabled and the keys for the tables are the same, even though I have separate __independent__ components for each table, there is still a conflict when I try to select something from one table, it affects the other table.

I have the problem reproduced in here: https://codesandbox.io/s/autumn-pond-9qmw6

Have a look at the comments in lines 67-68 for where the duplicate keys come from.

Perhaps, I have a usage error, if so, please provide a snippet showing how I can achieve the correct behavior in which selection in one table doesn't affect the other table

**Comment by emyarod** [comment]
HTML `id` attributes should be unique, and the `for` attribute needs to correspond to the elements in the output. you are currently assigning the same values to both of the StructuredLists

see https://codesandbox.io/s/reverent-darwin-9oo9x

**Comment by janamano** [comment]
HTML `id` attributes should be unique and the `htmlFor` should correspond with the id (they have to be the same)
Is this correct?

**Comment by emyarod** [comment]
yes `htmlFor` is the React attribute that corresponds to `for`

**Comment by tw15egan** [comment]
Closing as resolved as all elements need unique id's
