### ISSUE TITLE
[OverflowMenu] Content is not within a landmark element

### ISSUE THREAD

**Issue by GodAImighty** [carbon-design-system/carbon#8730]
![image](https://user-images.githubusercontent.com/22669933/119039793-42a21800-b97a-11eb-88ef-fb98c7dfe03c.png)

This can be recreated by going to https://www.carbondesignsystem.com/components/overflow-menu/code and running the [IBM Equal Access Accessibility Checker](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp?hl=en-US) extension on the page.

**Comment by tw15egan** [comment]
Hey there @GodAImighty you just need to place the `OverflowMenu` inside of a proper HTML element that has an implicit landmarking role, or use the `role` attribute to define your own. Here is. an example that resolves the issue: https://codesandbox.io/s/admiring-violet-8ez94?file=/index.html

This type of fix will need to be handled on the user end, and cannot be fixed on the Carbon/OverflowMenu side of things. Hope that helps!
