### ISSUE TITLE
CSS issue under .bx-btn under .securitypanel-v2__footer  

### ISSUE THREAD

**Issue by yiwang2** [carbon-design-system/carbon#8732]
## What package(s) are you using?

- "@carbon/colors": "^10.3.0",
- "@carbon/ibm-cloud-cognitive": "^0.35.30",
- "@carbon/ibm-security": "1.37.0",
- "@carbon/icons-react": "^10.4.1",

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Found the drop down icon under the combobox button component is missing under the PanelV2.
<img width="355" alt="Screenshot 2021-05-21 at 10 54 12" src="https://user-images.githubusercontent.com/20241779/119119458-1db5af80-ba23-11eb-9dbe-76f0926673c7.png">

## Steps to reproduce the issue

1. The issue happens when .bx-btn under .securitypanel-v2__footer  
2. the padding calculation is: calc(0.875rem - 3px) 63px calc(0.875rem - 3px) 15px
3. If the padding is changed as : padding: calc(0.875rem - 3px) 0 calc(0.875rem - 3px) 15px; Then it works as nomal
4. It may be caused by the styling conflict between "@carbon/ibm-cloud-cognitive": "^0.35.30" and  "@carbon/ibm-security": "1.37.0",

## Additional information

- Screenshots or code 

If the padding is changed as : padding: calc(0.875rem - 3px) 0 calc(0.875rem - 3px) 15px; Then it works as nomal
<img width="1392" alt="Screenshot 2021-05-21 at 11 01 12 1" src="https://user-images.githubusercontent.com/20241779/119120508-438f8400-ba24-11eb-8877-07822390338d.png">

**Comment by joshblack** [comment]
Hi there @yiwang2! 👋 

Given that this issue is coming up with Security/Cloud & Cognitive, I would reach out to one of those PALs to see if the conflict could be addressed.

@SimonFinney does that seem like an appropriate next step or is this something on our end we need to address?

**Comment by SimonFinney** [comment]
> Hi there @yiwang2! 👋 
> 
> Given that this issue is coming up with Security/Cloud & Cognitive, I would reach out to one of those PALs to see if the conflict could be addressed.
> 
> @SimonFinney does that seem like an appropriate next step or is this something on our end we need to address?

Yeah, that's exactly right - we're working through compatibility options at the moment.

**Comment by joshblack** [comment]
Sounds good! I'll go and close this out and defer to those projects for the interop issues @yiwang2 👍
