### ISSUE TITLE
ComboBox doesn't use ref now.

### ISSUE THREAD

**Issue by ymitchanka-gomel-iba-by** [carbon-design-system/carbon#8744]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
We are using a ref in the ComboBox component. 
But now, as I right understand from March 2021, this component was rewritten from class to functional component.
We have the warning in the console about the ref and we can't use the ref in ComboBox now.

> Is this issue related to a specific component?
ComboBox 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Add ability to use a ref in ComboBox.
And the warning related to the ref should not appear.

> What browser are you working in?
Chrome, Mozilla Firefox

> What version of the Carbon Design System are you using?
7.35.0

## Steps to reproduce the issue

1. Add the ability to pass ref props to the ComboBox component (for example as it's done for the TextInput component  **https://github.com/carbon-design-system/carbon/blob/311c4ab776624d175d5a983b166083f37c57ba71/packages/react/src/components/TextInput/TextInput.js#L19).**

## Additional information
![image](https://user-images.githubusercontent.com/83288731/119343153-bc017980-bc9e-11eb-8edf-5d7336fa24d6.png)

```
import React from 'react';
import { render } from 'react-dom';
import { ComboBox } from 'carbon-components-react';

const items = [
  {
    id: 'option-1',
    text: 'Option 1',
  },
  {
    id: 'option-2',
    text: 'Option 2',
  }
];

const App = () => (
  <div>
    <ComboBox
      onChange={() => {}}
      id="carbon-combobox"
      items={items}
      itemToString={(item) => (item ? item.text : '')}
      placeholder="Filter..."
      titleText="ComboBox title"
      helperText="Combobox helper text"
      ref={()=>console.log('some ref here')}
    />
  </div>
);

render(<App />, document.getElementById('root'));
```

**Comment by davidicus** [comment]
Definitely interested in seeing this issue resolved. The lack of ref breaks extensions that our PAL has built on top of ComboBox component. We are unable to upgrade Carbon without breaking existing applications.
