### ISSUE TITLE
Update usage of `/` operator to use `math.div`

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8746]
The `/` operator will be deprecated in Dart Sass `2.0.0` as pointed out in: https://github.com/carbon-design-system/carbon/issues/8069#issuecomment-846009017

This issue tracks the updates needed in `@carbon/styles` to move away from the `/` operator to `math.div` as has been recommended in: https://sass-lang.com/documentation/breaking-changes/slash-div

Unfortunately, our current Sass targets include `node-sass` and I don't believe this is something we can address in our codebase today. it will, however, be addressed in our v11 release.

**Comment by kubijo** [comment]
Just a heads up that there's a automatic conversion tool that you could possibly use until the sources are generated in the new format (but you probably already knew about that)…

[Another options is (reportedly) this](https://github.com/patternfly/patternfly/issues/4096#issuecomment-859055362) if you want to keep compatibility with node-sass &/or older dart-sass implementations

**Comment by joshblack** [comment]
Seems like what bootstrap ended up doing is temporarily replacing `/` with multiplication as another option 👀

**Comment by kubijo** [comment]
I guess that is another option :laughing:
