### ISSUE TITLE
eslint-config-carbon package as published on npm is unusable

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/carbon#8774]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

None of the above: eslint-config-carbon

## Detailed description

In version 2.3.0 of eslint-config-carbon, `require.resolve('./rules/best-practices')` was added to base.js in PR #7761. Unfortunately, the file `./rules/best-practices` is not included in the published package, making the package as published onto npm unusable in versions 2.3.0 and 2.4.0.

## Steps to reproduce the issue

1. Install the package from npm as in the readme
2. Extend 'carbon' in eslint settings as in the readme
3. Run eslint, and the following errors are produced:
![image](https://user-images.githubusercontent.com/6385315/119756788-e3716580-be9b-11eb-8e04-3fb1330c78ae.png)

**Comment by joshblack** [comment]
Hi @dcwarwick! 👋 

Thanks for the report, let me see what's going on with that package. Most likely `rules` is not being included in the `files` array of the package which is causing it not to be published 👍

**Comment by dcwarwick** [comment]
Thanks @joshblack. I can confirm that eslint-config-carbon v2.5.0-rc.0 fixes the issue and works fine for us.
