### ISSUE TITLE
Needed to fix vertical positioning of the icon in date picker without label

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#878]
I'm using the react components (v6.1) and the minified CDN CSS of carbon components (https://unpkg.com/carbon-components/css/carbon-components.min.css).
My date picker doesn't have a label.
In my project, I had to fix the vertical positioning of the date picker icon by overwriting the class like this:

.some-parent .bx--date-picker__icon {
  top: 50%;
  transform: translateY(-50%);
}

Note: I don't use a label. If I use an label, then the positioning is wrong again ...

I didn't check, if it's an general issue, but at least you've got an hint.

https://github.com/carbon-design-system/carbon-components/blob/4d775ed2df630c1a85dcb786468df23162d27d5a/src/components/date-picker/_date-picker.scss#L110

**Comment by alisonjoseph** [comment]
Hi @IOIO72 I have a fix in a PR #879 however I would recommend for a11y purposes that you make sure you have a label somewhere describing your date picker if you are hiding the default label.

**Comment by alisonjoseph** [comment]
@IOIO72 a fix has been merged in. you will need to add a class of `.bx--date-picker--nolabel` to the date picker.
