### ISSUE TITLE
Search component from carbon-components-react needs IME support

### ISSUE THREAD

**Issue by hyungskim** [carbon-design-system/carbon#8782]
Search component from carbon-components-react needs IME support.

In the following slack thread, I asked, "Does the Search component in carbon-components-react support IME Japanese Kanji conversion?" We've noticed the Search component was problematic with IME Japanese Kanji conversion due to the IME tool uses Space and Enter to control converting Hiragana to Kanji after entering the search input text. 
Ken Matsuoka found a bug in React itself and React doesn't seem like caring the issue after all. So we're asking the carbon-component team to implement a work-around **at least for the Search component**. This issue is currently impacting every production where we use the Search component including Watson Knowledge Catalog UI.

The detail info is in this thread, https://ibm-analytics.slack.com/archives/C046Y0YUD/p1621990919057400

**Comment by hyungskim** [comment]
Hi. I just asked Masako from Japan to add detail info how to reproduce the issue using IME Japanese. Including a video clip.

**Comment by matsken** [comment]
@joshblack I've created a CodeSandbox (and there's not much to it - just a Search with `onChange`) - though it's really dependent on the client environment - you need to have at least an IME installed. https://codesandbox.io/s/brave-sun-h492w

**Comment by joshblack** [comment]
Thanks @matsken! 👋  Was trying to look at the Slack thread too for context but couldn't seem to find the workspace 🤔  Is there another way to share the thread through Slack, potentially?

**Comment by hyungskim** [comment]
This is the movie clip for this issue using IME (sent by Masako)
https://github.ibm.com/PrivateCloud-analytics/Zen/files/757070/henkan_movie.zip

**Comment by hyungskim** [comment]
Is someone really working on this issue? There's still customer waiting for the fix. https://github.ibm.com/PrivateCloud-analytics/Zen/issues/23861

**Comment by tay1orjones** [comment]
I can't view any of the links provided in this issue. I'm not sure what the problem here actually is. To take action on this we'll need more info, a reproduction we can view, and clear steps outlining the problem.
