### ISSUE TITLE
WarningAltFilled32 icon not supporting "inner-path" for two-tone colors

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon#8788]
## What package(s) are you using?

- [x]     "carbon-components": "latest",
- [x]    "carbon-components-react": "latest",
 - [x]   "carbon-icons": "latest",
- [x]   "@carbon/icons": "10.28.0",
 - [x]  "@carbon/icons-react": "10.28.0"

## Detailed description

> Describe in detail the issue you're having.

It looks like WarningAltFilled32 icon should support `[data-icon-path="inner-path"]` (two-tone) from this [issue](https://github.com/carbon-design-system/carbon/issues/5919) but it doesn't seem to be working. 

> Is this issue related to a specific component?

WarningAltFilled32
https://github.com/carbon-design-system/carbon/blob/main/packages/icons/src/svg/32/warning--alt--filled.svg?short_path=192d63c
The problem seems to be the name on this [line](https://github.com/carbon-design-system/carbon/blob/main/packages/icons/src/svg/32/warning--alt--filled.svg?short_path=192d63c#L9) 

It would be nice to add inner-path to the 16px version of `warning--alt--filled.svg`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
- Fix the `inner-path` on packages/icons/src/svg/32/warning--alt--filled.svg
- Add `inner-path` to the 16px sized SVG as well  packages/icons/src/svg/16/warning--alt--filled.svg

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson Assistant

## Steps to reproduce the issue

1. Go to the code sandbox
2. View three different icons (WarningAltFilled32, WarningAltFilled16, WarningFilled16)
3. Only one supports `inner-path` currently for two-tone colors

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/react-and-scss-forked-e0u7o?file=/src/index.js

## Additional information
<img width="261" alt="Screen Shot 2021-05-27 at 4 35 57 PM" src="https://user-images.githubusercontent.com/7145340/119893660-a3e16280-bf09-11eb-92b4-a53e694b533e.png">

**Comment by joshblack** [comment]
This looks like an issue in our icon pipeline where our [SVGO plugin](https://github.com/carbon-design-system/carbon/blob/main/packages/icon-build-helpers/src/metadata/extensions/output/optimizer.js#L66) is looking for exactly `inner-path` where-as the source asset uses `_inner-path_`. I think we can make a quick update to be more flexible here so that it can pick up either variant 👍

**Comment by emyarod** [comment]
if I'm not mistaken aren't the path names generated based on the layer name in Illustrator? if so, should we expect the names to be standardized during icon creation?

**Comment by joshblack** [comment]
Following up, @conradennis is going to update the assets to use the `inner-path` convention in his June batch of icons so this should be addressed by that 👍 

@emyarod removing this from the sprint since we're blocked on that PR 👀

**Comment by joshblack** [comment]
PR for this: https://github.com/carbon-design-system/carbon/pull/8960
