### ISSUE TITLE
NumberInput enhancement: have an option to allow integers only

### ISSUE THREAD

**Issue by jinzih** [carbon-design-system/carbon#8807]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
**NumberInput is a handy component to use, however, it will be good if it has an option to allow integer numbers only.**

Please describe your request in one or two sentences.
**NumberInput is a handy component to use, however, it will be good if it has an option to allow integer numbers only.**

Clarify if you are asking for design, development, or both design and
development.

**Development**

### Justification

Provide the business reasons for this request.
we use NumberInput for some cases that only allow integers. 

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by tay1orjones** [comment]
In https://github.com/carbon-design-system/carbon/pull/11230 an `onKeyUp` prop handler was added and can be used to validate/restrict the component to input integers-only. Let us know if this doesn't work for you.
