### ISSUE TITLE
Vanilla Carbon | HTML elements and JS binding gets lost

### ISSUE THREAD

**Issue by AbhishekShrivastava** [carbon-design-system/carbon#8813]
I am working on the ReactJS application and as a response to an AJAX call, I am getting the HTML content and the carbon-components.min.js JavaScript file URL embedded into it. The HTML content gets rendered properly at the UI but the carbon-components.min.js doesn't bind itself with the HTML elements although it gets loaded into the Network tab of the browser inspector window. I am using a dropdown element in the HTML which does not show the element list on click of dropdown because of this JS binding issue.

**Comment by emyarod** [comment]
you can refer to the vanilla [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox) for a better idea of how to initialize and bind the vanilla JS to the markup

**Comment by AbhishekShrivastava** [comment]
Thanks for sharing the info to initialize and bind the vanilla JS to the markup. It worked.
I have another issue: if the dropdown has some element pre-selected, it does not show the selected element in the dropdown. Although once I open the dropdown then the element shows as selected in the list. That means the root '**div**' element does not have any value of 'data-value' attribute although one '**li**' element has class as 'bx--dropdown--selected' in the list.
Please help and let me know if you need more information on it.

![image](https://user-images.githubusercontent.com/4821466/121002902-7c349a80-c752-11eb-86e7-5e51b4edd08f.png)

**Comment by emyarod** [comment]
most likely you need to call `Dropdown.select(<itemToSelect>)` when preselecting? 
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox) for easier testing and debugging?

**Comment by emyarod** [comment]
https://codesandbox.io/s/abhi-forked-mo79h

if you console.log `dr.select` you can see that it does exist even in your sandbox. it's erroring because you are passing in an invalid parameter and `Dropdown.select` expects `itemToSelect` to be an `HTMLElement`

to attach event handlers you can use the vanilla JS API methods i.e. `EventTarget.addEventListener()`
