### ISSUE TITLE
Website audit for color tokens and size props

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#8815]
Preform a website audit in order to locate all the pages where we mention ~color tokens or~ size props. This will allow us to update ~color tokens and~ size props consistently across the website. 
- [Notion table for audit](https://www.notion.so/carbondesignsystem/6dc11b2c3eb94e9ebfb2497d5baed4e5?v=dd5e92180f8a44b390f623d747a548aa)

**Step 1**
Go to each page on the website and review content for any mentions of ~color tokens or~ components sizes. When ~color token or~ size is mentioned add information into the Notion table. Divide the pages among yourselves. 

**Step 2**
Go through the [react storybook](https://react.carbondesignsystem.com/?path=/story/getting-started-welcome--welcome) and identify all components that have size variations and add them to the notion table. Sizes will most likely be found on the ["Playground"](https://react.carbondesignsystem.com/?path=/story/components-accordion--playground) tab.

**Comment by thyhmdo** [comment]
https://github.com/carbon-design-system/carbon-website/issues/2260
