### ISSUE TITLE
Date and time pickers text color

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#882]
## Brief description

The placeholder text for date and time picker needs to be switched from the placeholder color to the informational placeholder color. The formatting for these components needs to be seen by all users. If it is not readable they will not know the format they need to write the date/time in.

> Is this issue related to a specific component? 

All date and time pickers.

**Comment by tw15egan** [comment]
Hey @tay-aitken what did we ever decide with regards to this?

**Comment by tay-aitken** [comment]
Just to switch date picker to text-02, the rest should be set to text-03.
