### ISSUE TITLE
Text Inputs invisble in high contrast mode

### ISSUE THREAD

**Issue by dimipankratz** [carbon-design-system/carbon#883]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component? 

Text Input specific, cf. http://www.carbondesignsystem.com/components/text-input/code

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to see the text inputs but they are invisible in high contrast mode. I'd suggest to show, e.g., borders in HCM or have another elegant way to make them visible.

> What browser are you working in? 

Firefox

> What version of the Carbon Design System are you using? 

v9.0.2

## Additional information
Not HCM
![image](https://user-images.githubusercontent.com/14946295/41153721-e4a23cf2-6b17-11e8-9278-4e66e6753a2b.png)

HCM Black text & white background:
![image](https://user-images.githubusercontent.com/14946295/41153590-74349bae-6b17-11e8-8a67-81097d9d1cdc.png)

HCM White text & black background:
![image](https://user-images.githubusercontent.com/14946295/41153668-b3fbd342-6b17-11e8-8d76-53fd8ae98d33.png)

## Add labels
>Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

I'd say these two:
https://github.com/carbon-design-system/carbon-components/labels/a11y
https://github.com/carbon-design-system/carbon-components/labels/bug

**Comment by tw15egan** [comment]
@carbon-design-system/ui We need to add a `1px solid transparent` border to the inputs. I'm pretty sure this will show in HCM
