### ISSUE TITLE
Add compatibility for theme mixin to map v10 to v11 tokens

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8838]
We currently provide a mapping between v10 and v11 tokens in our [`theme-tokens.scss`](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/globals/scss/_theme-tokens.scss) file. For teams that may be using `carbon--theme` directly, whether from another Sass import or from `@carbon/themes`, this mapping is unavailable to them and their theming strategy no longer works.

This issue is to add an interop/compat mixin to the `carbon--theme` mixin directly. This should provide mappings from v10 token values to v11 tokens. Since `carbon--theme` is our current recommendation/practice for applying themes, this should allow existing code to work as intended with components in Carbon using the new tokens under the hood.

Another approach we could take is to toggle which tokens are used based on the feature flag being set.

**Comment by joshblack** [comment]
cc @tw15egan do you think this would be a good approach for that mapping strategy for the new tokens? Seems like it should solve the issue reported on Slack and could double up as work for backwards compatibility with v10 in v11 with the old tokens.

**Comment by tw15egan** [comment]
Yeah, that makes sense. We would just need to add the same mapping to the `theme` package, correct?
