### ISSUE TITLE
[elements] add new support tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#8839]
New support color tokens are needed for the status indicator pattern. Add these to the package. 

Token | Usage | White | Gray 10 | Gray 90 | Gray 100
-- | -- | -- | -- | -- | --
$support-caution-minor | Status minor caution | Yellow 30 | Yellow 30 | Yellow 30 | Yellow 30
$support-caution-major | Status major warning | Orange 40 | Orange 40 | Orange 40 | Orange 40
$support-undefined | Undefined status | Purple 60 | Purple 60 | Purple 50 | Purple 50

**Comment by joshblack** [comment]
@aagonzales is this in the full list of tokens too? https://www.notion.so/carbondesignsystem/Hybrid-List-of-new-tokens-c507394e43fe4daa9f0cd0eedb25d1e4 Just wanted to double-check for which one was the source of truth

**Comment by aagonzales** [comment]
@joshblack that has all the tokens except the news ones mentioned in this issue. I haven't added those yet.
