### ISSUE TITLE
Slider Component input box bug

### ISSUE THREAD

**Issue by lornakelly** [carbon-design-system/carbon#8842]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

There is a bug when trying to type in a number into the input box for the slider

> Is this issue related to a specific component?

Slider Component

> What did you expect to happen? What happened instead? 

If you, for example, have min 30, and your current value is 35, if you want to change it to 34, the box wont allow you to delete the ‘4’ as the value would be ‘3’, even though you are still editing the number.

> What would you like to see changed?

Might be better to delay the validation until the user has left the input box, or mark the box as invalid and not automatically change the value

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components:  10.35.0,
 carbon-components-react: 7.35.0

**Comment by joshblack** [comment]
Quick codesandbox to reproduce: https://codesandbox.io/s/serene-lake-xcqzy

Follow the steps above, enter in 35 and it updates correctly. Try to backspace and it won't let you.
