### ISSUE TITLE
Problem with carbon-telemetry on Windows platform

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/carbon#8846]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

No, actually `@carbon/telemetry`, version 0.0.0-alpha.6.

## Detailed description

> Describe in detail the issue you're having.

In package `@carbon/ibm-cloud-cognitive` we recently added `@carbon/telemetry` in order to get insight into the consumers of our Carbon-based components. One user (@richardpilot) of the package has since reported problems during install (running `yarn install` on a freshly created clone of `@carbon/ibm-cloud-cognitive` repo) as follows:

```console
error C:\WorkspacesGit\ibm-cloud-cognitive\node_modules\@carbon\ibm-cloud-cognitive: Command failed.
Exit code: 1
Command: carbon-telemetry collect --install
Arguments:
Directory: C:\WorkspacesGit\ibm-cloud-cognitive\node_modules\@carbon\ibm-cloud-cognitive
Output:
internal/modules/cjs/loader.js:1032
  throw err;
  ^
Error: Cannot find module 'C:\WorkspacesGit\ibm-cloud-cognitive\node_modules\node_modules\@carbon\telemetry\bin\carbon-telemetry.js'
```

Other users, including all of the core team, have not encountered this problem. @richardpilot is running on Windows, and it is possible (though we've not been able to verify) that the problem arises specifically on Windows, or perhaps owing to some other detail of his configuration. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

There shouldn't be any user-visible messages or disturbance from @carbon/telemetry.

Notice the path that is shown in the final error message: `'C:\WorkspacesGit\ibm-cloud-cognitive\node_modules\node_modules\@carbon\telemetry\bin\carbon-telemetry.js'`. This path does not look correct: it has a repeated "node_modules". @richardpilot has confirmed that the file carbon-telemetry.js *does* exist at the corrected path `'C:\WorkspacesGit\ibm-cloud-cognitive\node_modules\@carbon\telemetry\bin\carbon-telemetry.js'` on his system. That is where the tool should therefore be loading from, and there would appear to be a configuration problem.

## Steps to reproduce the issue

1. Clone the repo `@carbon/ibm-cloud-cognitive`
2. Run `yarn install`

As noted above, many users do not get an error. It may be specific to Windows, or to some other aspect of @richardpilot's environment.

## Additional information

A discussion of this issue can be found here: https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1622555612022300

**Comment by dcwarwick** [comment]
@joshblack @richardpilot FYI

**Comment by joshblack** [comment]
cc @dakahn @emyarod do you two have any idea about the windows specific part of this?

@richardpilot is there any additional windows environment info that you could give us?

Does this issue occur if you follow these steps:

- `npx create-react-app tmp-app`
- `cd tmp-app`
- `npm i carbon-components carbon-components-react carbon-icons`

Trying to narrow down if the issue is package-specific or if it's workspaces specific 👀 

@dcwarwick what version of Yarn are you all using for C&CS monorepo?

**Comment by emyarod** [comment]
I can replicate the issue as described in the original ticket body

```console
error E:\Users\admin\Documents\GitHub\ibm-cloud-cognitive\node_modules\@carbon\ibm-cloud-cognitive: Command failed.
Exit code: 1
Command: carbon-telemetry collect --install
Arguments:
Directory: E:\Users\admin\Documents\GitHub\ibm-cloud-cognitive\node_modules\@carbon\ibm-cloud-cognitive
Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'E:\Users\admin\Documents\GitHub\ibm-cloud-cognitive\node_modules\node_modules\@carbon\telemetry\bin\carbon-telemetry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
```

my guess is the installation command has a bug with pathfinding when it comes to Windows? I'm not familiar with the telemetry package so that would need some more investigation

on a separate note I tried the following steps as well and the installation worked as expected

> Does this issue occur if you follow these steps:
> 
>     * `npx create-react-app tmp-app`
> 
>     * `cd tmp-app`
> 
>     * `npm i carbon-components carbon-components-react carbon-icons`

**Comment by dcwarwick** [comment]
@joshblack fwiw we haven't locked the yarn version, so basically latest ie 1.22.10.

**Comment by joshblack** [comment]
@dcwarwick my guess is that if the package works by default (which it seems like from @emyarod's response it should) then there is something going on monorepo-wise that's causing some problems. We've had some challenges with Yarn in this space but on the 2.x release line, in particular with nested postinstall steps, and ended up going to the 3.0 RC to remedy them.

Maybe next steps here would be to find a minimal process to reproduce the issue, maybe setting up a monorepo with Yarn 1.x and seeing if that causes the issue? Seems like that will be the only way for us to isolate what is causing things to go wrong.

**Comment by dakahn** [comment]
Getting to this late but your user is on Node for Windows and not WSL I'm assuming for the logs. So we can narrow it down further there.

**Comment by fabpico** [comment]
When installing `packages/react` I get
```
Exit code: 1
Command: carbon-telemetry collect --install
Arguments:
Directory: C:\Users\......\carbon v10.34.0\node_modules\@carbon\icons-react
Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\.......\carbon v10.34.0\node_modules\node_modules\@carbon\telemetry\bin\carbon-telemetry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
```
