### ISSUE TITLE
Layout Scale Variables not defined

### ISSUE THREAD

**Issue by smandava** [carbon-design-system/carbon#885]
## Detailed description

I'm not able to use Layout scale variables such as  `$layout-2xs`,  `$layout-xs` etc as documented in the [spacing section ](http://www.carbondesignsystem.com/style/spacing) of style guide. I get `Undefined variable: "$layout-xs"` SCCS error.  

> What version of the Carbon Design System are you using? 

9.02

## Steps to reproduce the issue

* `git clone https://github.com/carbon-design-system/carbon-boilerplate.git`
* `cd carbon-boilerplate`
* `npm install` or `yarn`
* Specify padding as a $layout-xl in `app\scss\main.scss` as shown below

```
.container {
-  padding: 2rem 5% 0;
+  padding: $layout-xl 5% 0;
 }
```
* `npm run dev`
*  I'm getting the following error:
```
Error: app\scss\main.scss
Error: Undefined variable: "$layout-xl".
        on line 8 of app/scss/main.scss
>>   padding: $layout-xl 5% 0;
   -----------^
```

**Comment by alisonjoseph** [comment]
Hi @smandava thanks for catching this, I'm working on getting them added now.
