### ISSUE TITLE
Package eslint-config-carbon restricts users to old eslint version

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/carbon#8852]
## Problem

The package.json for eslint-config-carbon sets a peer dependency of:
```json
"eslint": "^6.0.0"
```

This means that a user of the package needs to supply eslint at version 6, but eslint moved to v7 over a year ago and is currently at v7.28.0. A user who has moved to eslint v7 will get an "incorrect peer dependency" warning from their package tool.

Also, eslint-config-carbon is using a very old version of eslint-plugin-jsdoc:
```json
    "eslint-plugin-jsdoc": "^20.3.1",
```

This version is eighteen months old, and itself sets a peer dependency of eslint as "^5.0.0 || ^6.0.0". So a user who has moved to eslint v7 will also get an "incorrect peer dependency" warning from their package tool for this. Note that eslint-plugin-jsdoc includes eslint v7 in its peer dependency setting since v25.0.0 (published about the same time as eslint v7), and the latest version of eslint-plugin-jsdoc is v35.1.3.

## Proposed solution

The package.json should be updated to set a peer dependency as follows:
```json
"eslint": "^6.0.0 || ^7.0.0"
```

Alternatively, the version range could be specified as ">=6.0.0", which will ensure that as and when eslint moves to v8 this issue will not be repeated.

The package.json should also be updated to use a more current version of eslint-plugin-jsdoc, at least v25.0.0, as follows:
```json
    "eslint-plugin-jsdoc": "^25.0.0",
```

(It might be useful to pull all the dependencies up to recent versions to ensure that improvements and bug fixes are being incorporated in a timely fashion)

**Comment by joshblack** [comment]
Hey @dcwarwick! 👋 

Great call with the eslint package stuff. Let me know if you're running into any other issues and we can try and get this package into a good spot. I'm not sure if we had users of it yet and so I'd love to work with you and see what we need to add in to get it to a good point.

In the interim, we'd definitely take in most contributions to update this stuff to the correct options if you're interested. I added it to our backlog, as well, and we'll see if we can pick it up in a future sprint.

**Comment by dcwarwick** [comment]
Thanks -- there are no real issues, and tbh the above only causes a couple of "incorrect peer dependency" warnings and no actual build-time problem. With c&cs we are sticking to the latest versions where possible of all our build dependencies. I did look at opening a PR to bring this package up to latest versions, which I think would be a good plan, but it does have some knock-on consequences -- a whole stack of minor linter issues would then need fixing in the carbon source code because of new features and changed options in the linters since the versions that are currently called for in package.json -- they all look very minor, but I didn't feel qualified to try and apply fixes for those in code I really do not know! I guess an interim step would be to pull versions forward enough to support the latest downstream versions but not enough to cause fresh linter issues, but I didn't get around to figuring out exactly what versions that would mean.

**Comment by dcwarwick** [comment]
ok, I can at least confirm that there isn't a "safe minimum" fix here: even pulling `eslint-plugin-jsdoc` forward minimally to version 25.0.0 already means about a dozen "missing @param" warnings are issued by `yarn lint` inside carbon! So I think the best thing is to pull everything forward to the latest and just sit down and fix up all the new linter warnings. This may possibly also help improve carbon's quality, as some of the linter warnings may point out actual problems! And then set the peer dependency to >=6.0.0, and that'll be great. Nothing urgent, but a useful chore for a rainy afternoon :-)

**Comment by joshblack** [comment]
@dcwarwick totally fair! I'll make sure this gets added to our next sprint, these deps have been due for an upgrade for a while 😂   anyways
