### ISSUE TITLE
Issue with shell component's notification dropdown when window is sized smaller hiding bottom of notification list

### ISSUE THREAD

**Issue by WesleyOgata** [carbon-design-system/carbon#8853]
Shows view all button hidden
![image-2021-05-20-14-10-51-513](https://user-images.githubusercontent.com/53269066/121062525-29c79e00-c793-11eb-9d4d-11decce79481.png)

The issue occurs on the bell icon when the window is resized to be smaller. Notifications list will resize up to a point and then will lock size. As a result the view all button at the bottom of the list becomes not visible and also the more the page is shrunk the more notifications will be hidden. 

max size screen can be resized to
<img width="1680" alt="Screen Shot 2021-06-07 at 1 44 20 PM" src="https://user-images.githubusercontent.com/53269066/121065704-0ef72880-c797-11eb-9c6d-03670735677e.png">

## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Hey there @WesleyOgata, do you have a link to a reproducible example on [CodeSandbox](https://codesandbox.io/s/vigilant-ramanujan-iis0q) so we can take a look?

**Comment by WesleyOgata** [comment]
Hello @tw15egan I don't at this point but I can try to take a look try and replicate it.

**Comment by joshblack** [comment]
Hi there! 👋  Going to close this out after 14 days of inactivity. Feel free to comment with more info and we can re-open and revisit this issue!

**Comment by WesleyOgata** [comment]
Hello sorry for the delay I've been trying to get an example on sandbox working but am unable to get that working. Specifically it's for the notifications section.
