### ISSUE TITLE
Search field hint text is barely legible

### ISSUE THREAD

**Issue by mastourehh** [carbon-design-system/carbon#8861]
### Summary

In the search component, the placeholder text color is barely legible.
The medium grey text on dark grey background is barely legible when you're using the Carbon theme.

### Justification
For people with low vision eye issues, this is hard to see.

**Comment by emyarod** [comment]
cc @carbon-design-system/design are the placeholder text tokens correct for the search component?

**Comment by laurenmrice** [comment]
The Search component placeholder text looks like the correct color to me. The placeholder text does not technically need to pass contrast as it is considered superfluous text, and will disappear as soon as a user starts typing.

**Comment by emyarod** [comment]
thanks for clarifying @laurenmrice!
