### ISSUE TITLE
DatePicker type 'range' - On second input ‘calendar icon’ click updates the date in the first input field.

### ISSUE THREAD

**Issue by SwapnilAhire** [carbon-design-system/carbon#8865]
BUG  - 
1. I am on @carbon/ibm-security version 1.41.0
2. I found an issue with date range picker component i.e `<DatePicker datePickerType="range">`

Description -
 - This issue is specific to second input field calendar icon click only.
 - Also this issue is reproducible on carbon documentation link too ( https://react.carbondesignsystem.com/?path=/story/components-datepicker--range ).
 - When I click on second input field's ‘calendar icon’ it updates the date in the first input field.
 - BUT when I click inside input field and select the date then it updates the date as expected inside input fields that I clicked.

```
<DatePicker datePickerType="range">
      <DatePickerInput
        id="date-picker-input-id-start"
        placeholder="mm/dd/yyyy"
        labelText="Start date"
      />
      <DatePickerInput
        id="date-picker-input-id-finish"
        placeholder="mm/dd/yyyy"
        labelText="End date"
      />
    </DatePicker>
```

Please refer attached screenshots for the reference.
![image](https://user-images.githubusercontent.com/6366084/121307300-7939d580-c91d-11eb-9cd8-24f1ef67ab61.png)

Actual implementation screenshots,
![image](https://user-images.githubusercontent.com/6366084/121307268-72ab5e00-c91d-11eb-82c7-8234f7e13b55.png)

Expected behavior -
 - When I click on the second input calendar icon, it should update the date in second field not first field

Actual behavior - 
 - On clicking second input calendar icon, it updates the date in first field.
 - It is incorrect.

Steps for reproducing -
(TRY it in both Chrome and Firefox)
https://react.carbondesignsystem.com/?path=/story/components-datepicker--range

Browsers
 - Not browser specific

Optional information
- None

**Comment by SwapnilAhire** [comment]
@joshblack @scottdickerson  Could you please help me with the list of packages that we need to update in order get this fix?

**Comment by SwapnilAhire** [comment]
@joshblack @scottdickerson Could you please let me know the list of packages needed to update for this fix?

**Comment by SwapnilAhire** [comment]
@joshblack This issue has been highlighted in our sprint and is a MUST FIX for me in-order to close the sprint. I am really looking forward to have some resolution for this. 

Could you please help me with some workaround for this issue or if it is fixed then the list of package which I need to update?

**Comment by antoinog** [comment]
We also see this issue where changing the end date changes the start date instead
![DateRange](https://user-images.githubusercontent.com/199594/131297505-cfeac002-1cd2-4ca9-9136-06ccd7787589.gif)

**Comment by antoinog** [comment]
Is this an issue that is planned to be fixed at any stage?  Or is it not thought of as an issue?

**Comment by joeweber** [comment]
We see the same issue. Is someone going to fix this?

**Comment by clu-7** [comment]
@joshblack @scottdickerson I am using the issue mentioned above. Is this being addressed right now or any workaround? Makes the range DatePicker unusable as is.

**Comment by tay1orjones** [comment]
Related #4476

**Comment by tay1orjones** [comment]
> This issue is specific to second input field calendar icon click only.

Yeah, the ranges work as intended when the input text is clicked/focused. The invalid behavior is present only from invoking the calendar from clicking the calendar icon.
