### ISSUE TITLE
[accordion] add flush alignment prop

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#8881]
## Flush alignment prop
- Add `flush alignment` prop to the accordion component.
  - Adding this will allow people to have the option between hanging accordion content or having the content flush on the page.
  - This use case has come up frequently with teams on Cloud when using the accordion component in side panel situations.
  - Use similar structure in react for the prop that we did for the [flush structured list variant](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--playground&args=isFlush:true).
  
------

## Specs
- All specs are the same besides taking out the padding-left before the text in the accordion. 
- Text should be aligned flush to the left end of the line dividers.
![Artboard](https://user-images.githubusercontent.com/43969356/121572537-e87cfb80-c9e9-11eb-9aa4-96273c9a13cc.png)

**Comment by vsnichols** [comment]
Wanted to add another vote for this on behalf of the Cloud & Cognitive Data table workstream - we would like to be able to use this for our side filter panel.

<img width="627" alt="Screen Shot 2021-09-14 at 10 53 15 AM" src="https://user-images.githubusercontent.com/39408106/133291645-acde26f0-dbc0-4f69-ab57-4f8c800496dd.png">

Without it we either have accordion lines running up against table lines, or misaligned text.

![image](https://user-images.githubusercontent.com/39408106/133291840-64a61bb1-d9bb-4498-a3b8-e2d4e0d612e2.png)

**Comment by jnm2377** [comment]
Hey @laurenmrice just wanted to get clarification on one thing. The `flush` styles would only be allowed if the accordion uses the default `align="end"` and the left padding should not change if it's using `align="start"` like the image below, correct?
<img width="1067" alt="Screen Shot 2022-08-26 at 12 05 28 PM" src="https://user-images.githubusercontent.com/32556167/186956573-7a2dab8c-ddc9-4667-b455-53462ed83168.png">

**Comment by laurenmrice** [comment]
Correct 👍 @jnm2377

**Comment by laurenmrice** [comment]
## Spec updates for flush accordion ✨

After finding some more use case examples and playing out the different interactions of hover and focus of the component, the designers needed to tweak the original spec from last year to make it work more seamlessly in these situations. 


**Changes**
- Chevron icon: There should be no right-padding and it should be flush with the divider rules.
- Hover and Focus states: These states need to have 16px padding on the left and right sides of the accordion.


---

![Accordion (flush) states](https://user-images.githubusercontent.com/43969356/188926611-4341e6ba-e37c-4bbb-8c0d-093364d5d2ea.png)

---
![Accordion (flush) specs](https://user-images.githubusercontent.com/43969356/188933049-bc85c5d4-c055-45ab-8acd-bc28f5a5d852.png)
