### ISSUE TITLE
TooltipDefinition within a <p> emits a React error in the console

### ISSUE THREAD

**Issue by John30013** [carbon-design-system/carbon#8884]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
> Describe in detail the issue you're having.
I have a paragraph that contains some text surrounded with a `<TooltipDefinition>`. React outputs the following error message in the developer console when it renders the `<TooltipDefinition>`:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by TooltipDefinition)
    in div (created by TooltipDefinition)
    in TooltipDefinition (at src/index.js:41)
    in IbmRepTooltip (at src/index.js:105)
    in p (at src/index.js:100)
    [...]
```

> Is this issue related to a specific component?
TooltipDefiniton

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Carbon shouldn't output invalid DOM structures. This seems like a relatively common use-case, that you would want to be able to apply a tooltip to some text inside a paragraph, list, or other semantic block-level DOM element.

> The easiest fix would be to replace the `<div>` with a `<span>` in the rendering of the `<TooltipDefinition>` component. If the element must display as a block, that can be accomplished via CSS. Note: I suspect this same issue applies to the other types of tooltip components, so it should be fixed the same way in those components too.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.37.0 / 7.37.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
None.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
See the TooltipDefinition in the paragraph below the first heading on this page: https://84zrl.csb.app/

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi there, @John30013! Thanks so much for making this issue. Definitely agreed, switching from `div` to `span` makes a lot of sense here.

We'll go investigate to see if we can make this kind of change without it seeming like a breaking change. If so, we'll update it as-is otherwise we'll try and find a strategy (maybe an `as` prop) in the interim to better support this 👍

**Comment by John30013** [comment]
HI, @joshblack. I see that the `<div>` has a CSS `display` property of `inline-flex`, so switching to a `<span>` shouldn't break anything visually, since `<span>` is already an inline element. That said, I understand (and agree and appreciate) that you must do your due diligence.
