### ISSUE TITLE
Update the React-Router example to the latest version i.e. v5 or v6

### ISSUE THREAD

**Issue by sohamsshah** [carbon-design-system/carbon#8885]
Currently the [React Router](https://github.com/carbon-design-system/carbon/tree/main/packages/react/examples/react-router) example is having version: `react-router-dom": "^4.3.1`.

### Summary

- Will update the example as there are some major API changes while migrating to v5 or above compared to v4.
- Will also include Private/Protected Routing in the example itself so the developers can get better understanding overall.
- Would love to add some newer components too in this example, so to keep things up to date.

### Justification

As a developer exploring any open source library, one of the first things one searches for is `example` folder. This PR will help to keep things up-to-date!

### Available extra resources

- Can you affirm what version shall I opt for? (v5 or v6) 
`v6` is going to be released soon and already have started being used by many.

- Can you affirm what must-add components shall I include in the example?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

Looking forward to be an active contributor to the community. Will be active in raising PR and fixing this.
Thanks,
sohamsshah

**Comment by emyarod** [comment]
hi @sohamsshah thank you for reporting this. you can update the existing React Router Carbon CodeSandbox example to `v6`. If you feel additional components can be included feel free to add those to your PR!

**Comment by sohamsshah** [comment]
Awesome! Thanks
