### ISSUE TITLE
[Breadcrumb] invalid styling for current page

### ISSUE THREAD

**Issue by rafaelmaiach** [carbon-design-system/carbon#8891]
# Description

When setting `isCurrentPage` for a React BreadcrumbItem, the class is added correctly but, the style isn't.
Looking at the following line, is it missing a comma at line 67?

https://github.com/carbon-design-system/carbon/blob/72c0172ef78d89cd5ab53c6af211dda682275c2f/packages/components/src/components/breadcrumb/_breadcrumb.scss#L67

**Comment by tw15egan** [comment]
Thanks for reporting @rafaelmaiach, checking the knob seems to be implementing the styles correctly in the storybook. Is this not what you are seeing, or were you expecting different behavior? 

<img width="498" alt="Screen Shot 2021-06-22 at 2 53 04 PM" src="https://user-images.githubusercontent.com/11928039/122983036-8e752200-d369-11eb-8545-f947984c750e.png">

**Comment by rafaelmaiach** [comment]
Oh, I found the problem @tw15egan , I'm using the `Link` component from `Next.js/Link` and Carbon lose track on the CSS. I've changed here for a native <a> tag and the color kept correctly.

About the line I mentioned on the issue, I noticed that is the indent style from prettier (i think) that added the rule to a new line for keep the max print width.

**Comment by tw15egan** [comment]
Great! Sounds like you've got it all working now, so I'm going to go ahead and close this issue. Let me know if there's something else you need us to take a look at and I'll reopen 🍻
