### ISSUE TITLE
Tooltip: padding

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#890]
There currently isn't any padding between the bottom of the tooltip icon, and the top of the tooltip itself. There should be `margin-top: 4px`

Current:
<img width="372" alt="screen shot 2018-06-14 at 11 01 23 am" src="https://user-images.githubusercontent.com/29312997/41424157-e53937d8-6fc2-11e8-871b-f40c42a19f1c.png">

Proposed: 
<img width="334" alt="screen shot 2018-06-14 at 11 05 32 am" src="https://user-images.githubusercontent.com/29312997/41424161-e9de3400-6fc2-11e8-856e-301808aa0d4d.png">

**Comment by aledavila** [comment]
Resolved #896
