### ISSUE TITLE
Flatten nested imports and add deprecation notice

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#8901]
Discussion: https://github.com/carbon-design-system/carbon/discussions/8642

This issue is for tackling the normalization of our export strategy. Currently, we export a mixed of named exports and exports only available as fields on these exports. For example: `TextInput` and `TextInput.ControlledPasswordInput`.

With this change, we would like all exports to be available as named exports. To get there, we will need to:

- [x] Identify all components that are exported as a field on another component
- [x] Determine their export name in the normalized approach
- [x] Add each component as an export using the normalized approach
- [x] Add a deprecation notice to the old import with a message instructing teams on how to migrate to the new import

**Comment by joshblack** [comment]
For deprecation notices, we may need to do something like:

```js
function deprecateOnField(object, field, Component) {
  Object.defineProperty(object, field, {
    enumerable: true,
    get() {
      // Add deprecation notice here
      return Component;
    },
  });
}

// ...

deprecateOnField(TextInput, 'ControlledPasswordInput', ControlledPasswordInput);
```

**Comment by tay1orjones** [comment]
I think these are the only components exported as a field on another component:

- `TextInput.ControlledPasswordInput`
- `TextInput.PasswordInput`
- `MultiSelect.Filterable`
- `ErrorBoundaryContext.Consumer`
- `ErrorBoundaryContext.Provider`

**Comment by joshblack** [comment]
@tay1orjones I think that tracks!

For the ErrorBoundary stuff, I think you're right. That should stay as consumer/provider
