### ISSUE TITLE
Horrible Documentation!

### ISSUE THREAD

**Issue by Joebeazelman** [carbon-design-system/carbon#891]
The documentation from a company once renowned for its outstanding documentation is absolutely atrocious!  Nice pages with pretty controls are nice, but that doesn't help anyone get their job done.  

With all the repos and pages you've generated, none of the documents explain how to create a vanilla Carbon Components project using SASS and plain HTML.  Also, the Angular repo has no files and the few examples you guys give are outdated and buried in some Slack session. Are we supposed to play hide and seek with the documentation?

You guys are the poster children of everything wrong with the software industry!  Mediocrity now reigns supreme and no one wants to put the work that's required for excellence. Before you tell me that this project is a freebie and I should be grateful, please let me educate you.  Back during the golden years of computing, there was a ton of small teams and individual developers who made a comfortable living writing quality software. They were able to write some amazing software by today's standards with a tiny fraction of the computing resources you have today.  They somehow managed to not only document their software properly, but they were able to provide great customer support. 

That industry is now gone thanks to open source and its race to the bottom philosophy.  There's no point in creating quality software, even for $1, when there's tons freebies that are just good enough to be functional.  This project is a depressing example of where the future is headed.

**Comment by asudoh** [comment]
Hi @Joebeazelman good to see that you jumped in and providing a feedback to us!

We know that we have many room for improving our documentation, but we have http://www.carbondesignsystem.com/getting-started/developers/vanilla and each component links in http://www.carbondesignsystem.com/components that explain how to use those components and make them work in your application - Many components pages have live CodePen examples even. Documentation PR is always welcome, either in https://github.com/carbon-design-system/design-system-website or this repo.

If you are an IBMer, an internal community has Angular version of Carbon that should work well - CC @petersandor @blazejpawlak. Also people in the internal Slack channel for `carbon-components` are willing to help you.

Hope those help! CC @joshblack

**Comment by tw15egan** [comment]
Thanks for your feedback! If you have actionable items you would like us to address, please feel free to reopen the issue.
