### ISSUE TITLE
Text color missing in class

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#892]
##Brief description

The text color on the following components is relying on body CSS, not CSS for a class in that specific component. Please add in `color: $text-01;` for the following: 

- [x] Text input
- [x] List
- [x] Structured list
- [x] Modal (text content)
- [x] Toggle > label
- [x] Interactive tooltip > tooltip text
- [x] Inline code snippet?
- [ ] Code snippet text
- [ ] Terminal snippet text

**Comment by tw15egan** [comment]
Going to leave out Terminal / Snippet text as this may be used with syntax highlighters
