### ISSUE TITLE
[Release Partner] IBM Social Program Management

### ISSUE THREAD

**Issue by grahamharper** [carbon-design-system/carbon#8928]
**What is your team's name?**

IBM Social Program Management

**Why would you like to join the Release Partner Program?**

We're a couple of weeks away from shipping our first implementation of Carbon in our product and will have many more to follow. We'd love to be more engaged in helping shape and contribute to the system.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes.

**Who should we reach out to for more info?**

gharper@ie.ibm.com or @gharper on slack.

**Comment by joshblack** [comment]
Thanks so much for signing up @grahamharper! 🥳 Added you to the channel 🚀
