### ISSUE TITLE
[Release Partner] Graphite

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon#8929]
**What is your team's name?**

Graphite

**Why would you like to join the Release Partner Program?**

We are probably the largest consumer of Carbon React components.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

sls@ca.ibm.com

**Comment by joshblack** [comment]
Thanks so much for signing up! 🥳 Added you to the channel 🚀
