### ISSUE TITLE
Is Carbon touch-friendly?

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#893]
## Is Carbon touch-friendly?

Thanks for holding a great Town Hall event yesterday. I'm quite new to IBM and Carbon and interested in using it for our upcoming projects. However, I noticed that the Toggle component cannot be swiped on a mobile device (see gif below, tested on iPhone and Desktop Chrome with mobile Emulation turned on).

Therefore, I asked on #carbon-design-system in Slack if Carbon is touch-friendly and got a reply that I should post an issue here and ask. So, here I am! :-)

Thanks and keep up the great work!

---
<img width="312" src="https://user-images.githubusercontent.com/38980986/41455840-dc4194b0-707e-11e8-9a8a-1b7210323ac1.gif" alt="">

**Comment by alisonjoseph** [comment]
Hi 👋 Currently Carbon doesn't have any mobile/touch enhancements built in. We're definitely open to PRs to add this though.
