### ISSUE TITLE
component: table for typography page

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon#8934]
This issue is for dev support in creating a table to be used on the Guidelines > Typography page to illustrate the differences between the productive and expressive experiences. 

The table would use a sticky content switcher with two tabs (labeled `Productive` and `Expressive`) allowing the user to switch to see the differences between the type sets. It would work in a similar way to the Color Usage tab, but the switcher would not span full width. 

We are still determining the behavior of the content switcher on scroll. Will update this issue shortly. @jeanservaas will be spec'ing this out. 

Invision prototype of table: https://projects.invisionapp.com/d/main?origin=v7#/console/21476859/453822548/preview?scrollOffset=0

Draft PR: https://github.com/carbon-design-system/carbon-website/pull/2410

Link to Notion table with type set information that is changing (descriptions, headings, intro paragraphs, and new type styles): https://www.notion.so/carbondesignsystem/type-set-info-cdd5e63d6dc9452c9f62b805637c6ca4

Note: The fluid heading slider should look like the [slider on the IDL site](https://www.ibm.com/design/language/typography/type-specs-ui#type-set), not the Carbon site. (Carbon site has a drop shadow that we don't want.) Thank you! 

Note: The descriptions of the type styles are being updated. Please let me know the best way to get the content to you. A Notion document?

**Comment by jeanservaas** [comment]
@janchild am working on this now. 

Just a quick comment about the content on the type set page.

At first glance there was something odd about the anchor link names:

![image](https://user-images.githubusercontent.com/43144260/123842739-1c5b8a80-d8df-11eb-9cc7-dd431b8e72ed.png)

My first feeling is, why does "Differences between the type sets" come before "The type sets" — it feels like they're being talk talked about before being introduced.

Seems like it's much clearer to just include all of this information under 'Overview' rather than making 'Differences between the type sets' an H2

![image](https://user-images.githubusercontent.com/43144260/123843345-d226d900-d8df-11eb-8dbe-a32ca0a0e5e9.png)

**Comment by janchild** [comment]
@jeanservaas Thank you! Yes, obvious now I look at it. Making the change now.

**Comment by jeanservaas** [comment]
## Design specs

@sstrubberg Here are the full layouts for the page with the content switcher (both how it looks with 'productive' selected and 'expressive' selected. Jan will probably have copy edits etc, but this is the correct structure.

### Productive

![content_switcher_productive](https://user-images.githubusercontent.com/43144260/124938028-ed779f80-dfd5-11eb-8c73-6a79661877c6.jpg)

### Expressive

![content_switcher expressive](https://user-images.githubusercontent.com/43144260/124938072-fa948e80-dfd5-11eb-9319-2beabb0e21d5.jpg)

#### content switcher spacing

![image](https://user-images.githubusercontent.com/43144260/124939680-53b0f200-dfd7-11eb-8d90-a28af44791c9.png)



## Sticky scroll behavior specs

![content_switcher_sticky_scroll](https://user-images.githubusercontent.com/43144260/124940244-cf12a380-dfd7-11eb-9e3f-63575ec9db6d.jpg)

<br>

When 'Expressive' is selected on the content switcher, the breakpoint slider will scroll up and attach to the content switcher. The sticky breakpoint slider will have the same behavior (gray 20 stroke, grid alignments etc) as it does on the IDL site here

https://www.ibm.com/design/language/typography/type-specs-ui 

![content_switcher_w_slider](https://user-images.githubusercontent.com/43144260/124941250-adfe8280-dfd8-11eb-952f-96b7f2c35f15.jpg)

<br>

![image](https://user-images.githubusercontent.com/43144260/124942215-6f1cfc80-dfd9-11eb-979a-330c7fc488a5.png)


## Grid alignment and breakpoints

**Comment by janchild** [comment]
@sstrubberg Some feedback from the team after our Big Carbon meeting... could you please remove the "fixed" suffix from all of the fixed heading names? We are going to only use a suffix (`fluid`) for the fluid styles. Thank you!

**Comment by janchild** [comment]
@sstrubberg, we had a review of all the content today and we have changed `Small styles` to `Utility styles` so if you want to make any changes on your side to match the new name for the "littlies", I guess now would be the time. 8-) 

And here is the final list of type token names, FYI. This has the removal of `fixed` as I mentioned earlier. (This is the list that @tw15egan is working from for the type token additions this sprint.) 

[Typography type token list.xlsx](https://github.com/carbon-design-system/carbon-website/files/6956640/Typography.type.token.list.xlsx)

**Comment by janchild** [comment]
@sstrubberg Hi Scott, there were a couple of meetings today with @tw15egan, @laurenmrice, @oliviaflory, and @aagonzales having a final discussions and review of the type styles. 

We decided to include `$helper-text-01` and `$helper-text-02` in the `Utility styles` section. The addition back is more about usage by designers and making sure that we communicate the type of information that should be included in each part of the UI. 

The values would be exactly the same as `$label-01` and `$label-02`. This should be the last change. Let me know if you have any questions at all! Thank you.

**Comment by tw15egan** [comment]
Dev PR is up for review at : https://github.com/carbon-design-system/carbon/pull/9480

Tokens can be see at: https://deploy-preview-9480--carbon-elements.netlify.app/type/examples/preview/

Right-click on the token example to inspect that the values are correct (I've gone ahead and matched them to the [notion doc](https://carbondesignsystem.notion.site/Type-tokens-82eab5cd3a7a4f8498f3dd4ec5e686bc) so they should be correct)
