### ISSUE TITLE
Toast notification timeout property not working

### ISSUE THREAD

**Issue by linhenry0417** [carbon-design-system/carbon#8962]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Toast notification timeout property not working. The notification would not disappear automatically when the timeout property is set.

> Is this issue related to a specific component?

Toast notification

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi there @linhenry0417! 👋  Could you provide some steps to reproduce the issue in a [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox), this will help us out a ton to figure out what's going on. Thanks!

**Comment by linhenry0417** [comment]
1. import a toastNotification component 
2. set timeout property to say 3 seconds (3000)
3. observe that the toast notification does not disappear after 3 seconds

**Comment by tw15egan** [comment]
Hey @linhenry0417! I've done you the favor of recreating the issue in a [CodeSandbox](https://codesandbox.io/s/funny-zhukovsky-5r806?file=/src/index.js). That being said, I'm unable to recreate the issue, so I'm going to close this out. 

If you can recreate your issue in CodeSandbox I'll happily reopen the issue and take another look.

**Comment by emyarod** [comment]
this was resolved in https://github.com/carbon-design-system/carbon/pull/8362
