### ISSUE TITLE
Component contribution - selectable tile + secondary selection (dropdown)

### ISSUE THREAD

**Issue by janellearita** [carbon-design-system/carbon#897]
## Carbon component contribution
Looking to contribute a selectable tile + secondary selection (dropdown) component back to Carbon. Component would be similar to Carbon's selectable tile component. 

## Detailed description
Component currently lives in production for our beta GC Infrastructure services (Virtual Servers, VPC, Subnet, and Floating IP) and will have more services utilizing this component for our GA release in September. 

![image](https://user-images.githubusercontent.com/5559524/41479578-3f20837c-7091-11e8-957c-7b78babf3d2d.png)

Component may contain a secondary selection through standard dropdown (select input)
![screen shot 2018-06-15 at 11 49 15 am](https://user-images.githubusercontent.com/5559524/41479852-269dbd8c-7092-11e8-9212-1ac39d9660b5.png)

Other services that would benefit from this contribution:
Classic Baremetal and Classic VSI provisioning pages:
https://console.bluemix.net/gen1/infrastructure/provision/vs?type=hourly
https://console.bluemix.net/gen1/infrastructure/provision/bm

Which currently utilizes an older version of this component:
![screen shot 2018-06-15 at 11 51 42 am](https://user-images.githubusercontent.com/5559524/41479980-810ed94a-7092-11e8-8197-b488cacf31c2.png)
![screen shot 2018-06-15 at 11 52 04 am](https://user-images.githubusercontent.com/5559524/41479997-94091dbc-7092-11e8-938c-c5a32b576ffe.png)

## Additional notes

Older version of component also was built in our Infrastructure Addons by Chris Moody who no longer is on our team and unable to update component. 
https://github.com/carbon-design-system/carbon-addons-infrastructure
![image](https://user-images.githubusercontent.com/5559524/41481100-55ece262-7096-11e8-9c7a-dcb6ee7caf56.png)

Current component on production built by Eduardo Abe's dev team.

**Comment by tw15egan** [comment]
Should we move these to the infrastructure repo?

**Comment by tay-aitken** [comment]
## Meeting notes:

**Infrastructure Add-ons repo**
- The following components are going in this [repo](https://github.com/carbon-design-system/carbon-addons-infrastructure):
   - Tile + icon + inline dropdown
   - Tile + data vis bars 
   - Eduardo has been added as an admin so he can add to this repo

**Light contribution**
  - Carbon agreed to the selected background color proposal > Eduardo will making a PR to the carbon-components repo. 
- I am going to make a PR with the style changes to the design-system-website repo & updating necessary images (going to have @janellearita shadow when I do this so she knows how to do it for next time :) )

**Other**
- @janellearita is going to add the PR link to this issue once its been created

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-addons-infrastructure #17](https://github.com/carbon-design-system/carbon-addons-infrastructure/issues/17) via [**ZenHub**](https://www.zenhub.com/)
