### ISSUE TITLE
[StructuredList]: List items that aren't selectable should use the standard text-01 token.

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#8976]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
In the Carbon website, when we use structured lists, we always override with text-01. This is primary text and as such should use text-01. The headers are already bolded to create distinction. 

The exception for this behavior might be for selectable rows to indicate they are selectable

![image (1)](https://user-images.githubusercontent.com/4078018/122804194-349f2a00-d28d-11eb-8e3e-b13906638d4b.png)
![image](https://user-images.githubusercontent.com/4078018/122804202-37018400-d28d-11eb-83f7-2477f76bf7dd.png)

**Comment by jeanservaas** [comment]
Yes, we want the default case to use $text-01!

**Comment by joshblack** [comment]
Hey @vpicone! 👋  What behavior are you seeing in the current components? I believe they're using `text-primary` at the moment (or don't make a decision at all) which should map to `text-01` in the old system. Let me know if you're seeing a different color and we can take a look 👀

**Comment by vpicone** [comment]
@joshblack I'm getting #525252 from `.bx--structured-list-td`.

<img width="559" alt="Screen Shot 2021-06-24 at 10 34 15 AM" src="https://user-images.githubusercontent.com/4078018/123291483-c306ec00-d4d7-11eb-8443-9ea3bd404a59.png">

**Comment by tw15egan** [comment]
Found the culprit, pushing up a fix

![Screen Shot 2021-06-24 at 11 47 08 AM](https://user-images.githubusercontent.com/11928039/123293356-e898f300-d4e1-11eb-836a-6c817950dcef.png)
