### ISSUE TITLE
Component contribution - Profiles selectable tile

### ISSUE THREAD

**Issue by janellearita** [carbon-design-system/carbon#898]
## Carbon component contribution
Looking to contribute a selectable tile (with graphs) component back to Carbon. Component would be similar to Carbon's selectable tile component and might be more applicable to be added to our Infrastructure add-ons.  

## Detailed description
Component currently lives in production for our beta GC Virtual Servers pages.
![screen shot 2018-06-15 at 12 04 03 pm](https://user-images.githubusercontent.com/5559524/41480480-41901c0a-7094-11e8-968d-cc97dce83c80.png)

Other services that would benefit from this contribution:
Classic Baremetal and Classic VSI provisioning pages:
https://console.bluemix.net/gen1/infrastructure/provision/vs?type=hourly
https://console.bluemix.net/gen1/infrastructure/provision/bm

Which currently utilizes an older version of this component:
![screen shot 2018-06-15 at 11 52 11 am](https://user-images.githubusercontent.com/5559524/41480505-5174c102-7094-11e8-9913-0c820bc51763.png)
![screen shot 2018-06-15 at 12 05 02 pm](https://user-images.githubusercontent.com/5559524/41480524-5ca8c762-7094-11e8-891f-0315880790e4.png)

## Additional notes

Older version of component also was built in our Infrastructure Addons by Chris Moody who no longer is on our team and unable to update component. 
https://github.com/carbon-design-system/carbon-addons-infrastructure
![image](https://user-images.githubusercontent.com/5559524/41481080-47c1ae2a-7096-11e8-83d8-18fa786e3516.png)

Current component on production built by Eduardo Abe's dev team.

**Comment by tw15egan** [comment]
I'm going to move these over to the Infrastructure addons repo

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-addons-infrastructure #15](https://github.com/carbon-design-system/carbon-addons-infrastructure/issues/15) via [**ZenHub**](https://www.zenhub.com/)
