### ISSUE TITLE
Line separators in the DataTable component disappear when move the cursor along the lines

### ISSUE THREAD

**Issue by aplachka** [carbon-design-system/carbon#8984]
## What package(s) are you using?

- [ ] `carbon-components`
- [x ] `carbon-components-react`

> Describe in detail the issue you're having.
Line separators in the DataTable component disappear when move the cursor along the lines

> Is this issue related to a specific component?
DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?
the line separators in the table should not disappear when you move the cursor over the lines

> What browser are you working in?
Chrome, Mozilla Firefox

> What version of the Carbon Design System are you using?
7.35.0

## Steps to reproduce the issue

1.Open DataTable component in storybook
2.Move the  mouse cursor along the lines

- Screenshots or code
![image](https://user-images.githubusercontent.com/65154889/122878230-2cec8d80-d340-11eb-8ec9-c7852c3f79d6.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design are y'all seeing any visual defects here? https://react.carbondesignsystem.com/?path=/story/components-datatable--usage

**Comment by johnbister** [comment]
@tw15egan @aplachka I'm having trouble reproducing the issue. It looks fine to me.

**Comment by aplachka** [comment]
See pictures below:

![image](https://user-images.githubusercontent.com/65154889/123046390-b796c080-d404-11eb-9d1c-2e0be181ed5b.png)

You need to move the cursor from top to bottom along the rows of the table and then the dividing lines disappear.

![DataTable](https://user-images.githubusercontent.com/65154889/123046663-08a6b480-d405-11eb-8aa0-296967c0f889.gif)

![DataTable2](https://user-images.githubusercontent.com/65154889/123046996-6cc97880-d405-11eb-8be0-df2253577164.gif)

**Comment by tw15egan** [comment]
I'm still unable to reproduce. What browser / OS are you on? Are any browser extensions possibly causing styling issues? 

![2021-06-23 11 18 11](https://user-images.githubusercontent.com/11928039/123123465-da30d580-d414-11eb-9f98-c9010a631a94.gif)

**Comment by aplachka** [comment]
Windows 10 Build 19042.1052, Microsoft Edge Version 91.0.864.54 (Official build) (64-bit).

**Comment by tw15egan** [comment]
@dakahn any chance you can try and confirm this?

**Comment by emyarod** [comment]
this seems to be an Edge issue. Version 93.0.932.0 on the left, Version 91.0.864.59 on the right

![edge](https://user-images.githubusercontent.com/8265238/123330383-9072e880-d503-11eb-9758-652ec6444c35.gif)

**Comment by vshyn** [comment]
The same issue for Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by tw15egan** [comment]
@vshyn I'm running the same version and not seeing the issue. Are you on Windows or Mac?

![Screen Shot 2021-06-25 at 9 43 26 AM](https://user-images.githubusercontent.com/11928039/123433760-cbbff680-d599-11eb-9e29-6d42478972ad.png)

@aplachka does updating your Edge browser resolve the issue?

**Comment by emyarod** [comment]
![chrome](https://user-images.githubusercontent.com/8265238/123438524-61f21d80-d596-11eb-85b3-3f913d5facbb.gif)

Chrome Version 91.0.4472.124 and Version 93.0.4553.2

**Comment by vshyn** [comment]
@tw15egan,
Windows 10 Pro 19042.1052
![image](https://user-images.githubusercontent.com/66630330/123583496-526a1300-d7e8-11eb-81bf-6337f2f5c3ed.png)

![f0UuXVdhy2](https://user-images.githubusercontent.com/66630330/123583603-90ffcd80-d7e8-11eb-89cf-e3788ec2ff15.gif)
