### ISSUE TITLE
Accordion Transition is Not Working properly (flickering)

### ISSUE THREAD

**Issue by abod-akhras** [carbon-design-system/carbon#8997]
## What package(s) are you using?
- [x] `carbon-components: v10.34.0`
- [x] `carbon-components-react v7.34.0`

## Detailed description

> Describe in detail the issue you're having.
Hi Team, we are trying to update Carbon Components from `v10.12.0` to `v10.34.0` (carbon-components-react `7.12.0` --> `7.34.0`) But I noticed that after the update the Accordion Transition is Not Working anymore, it’s flickering as shown below. (edited)

> Is this issue related to a specific component?
Yes, the Accordion: https://react.carbondesignsystem.com/?path=/story/components-accordion--playground

> What did you expect to happen? What happened instead? What would you like to
Expecting a smooth transition but got a flickering one.

> What browser are you working in?
Same issue on Chrome and Firefox

> What version of the Carbon Design System are you using?
10.34.0

## Additional information

- Screenshots or code
![ezgif-3-88075e92737d](https://user-images.githubusercontent.com/67692574/123089498-ec177600-d41e-11eb-97de-f5fb2d6a99b2.gif)

https://user-images.githubusercontent.com/67692574/123088834-246a8480-d41e-11eb-8200-01318edb4281.mov

**Comment by emyarod** [comment]
this is what appears in the component story for me

https://user-images.githubusercontent.com/8265238/123118460-46590c80-d408-11eb-85ac-e2ed53332d2d.mov

**Comment by joshblack** [comment]
@abod-ibm could you share any additional steps to reproduce? Is this happening on the storybook for you? If so, could you share a screen recording of that?

**Comment by abod-ibm** [comment]
@joshblack & @emyarod Thanks for getting back so quickly. The issue seems to be in our implementation as I discovered the root cause for the issue we are having that we are passing the open parameter as shown below. So removing that fixed the issue. 

```
const [showMore, setShowMore] = useState(false);

function changeViewMore() {
     setShowMore(!showMore);
}

<AccordionItem title={showMore ? t('onboard.viewless') : t('onboard.viewmore')}
					               onHeadingClick={changeViewMore}
					               open={showMore}>
<AccordionItem>
```
