### ISSUE TITLE
New update broke layout

### ISSUE THREAD

**Issue by Oliviadavis** [carbon-design-system/carbon#901]
## Detailed description

I am using the carbon design system for our Cloud Sales Enablement Calendar: https://tsenable.tivlab.raleigh.ibm.com/calendar/tabs.html?embed=true
A recent carbon update broke the layout I had. I am using tabs and form components, dropdown, and search. I had them all in a line to best fit the iframe we use in our community: https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/Wf58c4c538dbf_45b4_b7a7_5003d0ceb79b/page/Calendar . The update put them each on a different row and I can't figure out how to fix it.

> Is this issue related to a specific component? 
The layout used to be all inline and now each component is shown on a different row.

> What did you expect to happen? What happened instead? What would you like to see changed?
All of the components displayed in a single row.

> What browser are you working in? 
I am using firefox.

> What version of the Carbon Design System are you using? 
<link href="https://unpkg.com/carbon-components/css/carbon-components.min.css" rel="stylesheet">
<script src="https://unpkg.com/carbon-components/scripts/carbon-components.min.js"></script>

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
The calendar is our one collated source where Cloud Sellers see calls and events.

## Steps to reproduce the issue
I can't figure out how to get the components back in line.

## Additional information
![screen shot 2018-06-18 at 10 20 57 am](https://user-images.githubusercontent.com/13104759/41541800-516af56a-72e1-11e8-9f71-b0c6c6a5570b.png)

In the code.zip file the file i'm referring to is tabs.html
[code.zip](https://github.com/carbon-design-system/carbon-components/files/2111616/code.zip)

**Comment by Oliviadavis** [comment]
Sorry it's not letting me add the labels.

**Comment by tw15egan** [comment]
Which version were you on, and which version are you seeing these issues? 

Can you put the items in a flex container to align them all?  Or can you change the `flex-direction` to `row`, instead of column?

**Comment by Oliviadavis** [comment]
I'm not sure where to add that in the code. I recently lost my developer resource so my knowledge using these components is beginner level.

<img width="1057" alt="screen shot 2018-06-18 at 4 47 52 pm" src="https://user-images.githubusercontent.com/13104759/41561259-6a38e22e-7317-11e8-8a74-38df391e5ed1.png">

**Comment by tw15egan** [comment]
If you are trying to align the `bx--select`'s, then you will need to target `bx--detail-page-header--menu .bx--form-item` and set the `flex-direction: row;`. SInce this issue is not related to a problem with the components themselves, I'm going to close this issue. 

If you are still having issues, feel free to post in the `#carbon-components` channel on slack for more help!

**Comment by tw15egan** [comment]
The component `css` in the `head` of the document is also referring to `https://unpkg.com/carbon-components/css/carbon-components.min.css`, which will always pull the most revent version. 

This is not recommended for exactly this reason, as it will break your layout when major changes occur (we just switched from v8 to v9). 

I would try switching the `css` back to `https://unpkg.com/carbon-components@8.23.0/css/carbon-components.min.css`
