### ISSUE TITLE
Cant icon-build-helpers -- broken dependencies & outdated

### ISSUE THREAD

**Issue by henryennis** [carbon-design-system/carbon#9014]
I am trying to add some custom SVGs to be passed to renderIcon which is a property of some carbon components.

Trying to use this module to process the svgs into the react format. Runnning into many errors in the icon-build-helpers module.

Is this the right approach? If not how would one go about converting the SVGs to a consumable format?

Cheers

**Comment by joshblack** [comment]
Hi there, @xSCIven! 👋  The `icon-build-helpers` package is unfortunately an internal package that we don't ship. Feel free to use.

For custom icons, we definitely recommend sites like SVGR: https://react-svgr.com/playground/ that can make it easy to copy and paste SVG code and get back a React component.

Hope this helps!
