### ISSUE TITLE
Breadcrumbs change height when hovered in Firefox

### ISSUE THREAD

**Issue by k-nut** [carbon-design-system/carbon#902]
When a breadcrumb is hovered it creates a `border-bottom` of height `1px`.

In order for the content below not to jump, a transparent border of 1px is added by default so that the height of the element always remains the same.

In Firefox the `border-bottom` [is explicitly set to `none` though][1] so that the content below a breadcrumb jumps whenever someone hovers over it.

I made a [codepen][2] with a `hr` below the breadcrumbs to demonstrate this.

![screen recording](https://thumbs.gfycat.com/MediumElectricArabianhorse-size_restricted.gif)

[1]: https://github.com/carbon-design-system/carbon-components/blob/master/src/components/breadcrumb/_breadcrumb.scss#L60-L65
[2]: https://codepen.io/k-nut/pen/VdyYrv

**Comment by tw15egan** [comment]
Hmm, not sure why we have that override in there specifically for Firefox. Will remove shortly
