### ISSUE TITLE
GitHub cleanup

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#9050]
### As is

Currently, we have org-level projects that are super stale:

https://github.com/orgs/carbon-design-system/projects

And I started a dedicated repo for a system-wide quarterly backlog:

https://github.com/carbon-design-system/roadmap/projects/1

And also, we're wanting to track v11 beta release progress with this issue:

https://github.com/carbon-design-system/carbon/issues/9005

### To be

- [x] Org-level projects cleaned up
- [x] System-wide quarterly backlog as an org-level project
- [ ] Archive the `/roadmap` repo
- [ ] Populate v11 beta release milestone https://github.com/carbon-design-system/carbon/milestone/56
  - [ ] Description
  - [ ] Date
  - [ ] Status table
- [ ] Add v11 epics to the roadmap project and v11 beta milestone
- [ ] New issue template in `/carbon` repo for epics that contain summary, job stories, success metrics
- [ ] Move the `/roadmap` repo readme content to a website page that we'll use for further ecosystem definitions and classifications https://github.com/carbon-design-system/roadmap/blob/main/README.md
- [ ] Update website to link to quarterly roadmap and v11 beta milestone
- [ ] Draft upcoming milestones to round out v11, so we have an idea of remaining items and we can pencil in some dates

**Comment by joshblack** [comment]
Could we use the milestone for the timeline but an issue for planning / creating the status table? With the new task list stuff, it makes it way easier to draft out the issue, make issues from it, and have the table all in one go.
