### ISSUE TITLE
ComboBox not dismissing other open ComboBox or DropDown

### ISSUE THREAD

**Issue by IBMSbright** [carbon-design-system/carbon#9073]
## What package(s) are you using?

- [] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
We have a page which has some ComboBox and DropDown objects. When a user opens the DropDown or a ComboBox then clicks on the chevron to open another ComboBox the open item is not dismissed

> Is this issue related to a specific component?
This is happening only with the ComboBox. If we open a ComboBox and click the DropDown the ComboBox dismisses.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Opening a ComboBox should dismiss any other open objects

> What browser are you working in?
Occurs in both Chrome and Firefox

> What version of the Carbon Design System are you using?
10.37.0 (was working as expected in 10.23.2)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Product offering is IBM Planning Analytics

![After](https://user-images.githubusercontent.com/25464544/123989320-c813e180-d996-11eb-82c6-d411667b24b1.png)
![Before](https://user-images.githubusercontent.com/25464544/123989321-c8ac7800-d996-11eb-8299-86fefd8d1a95.png)

- Screenshots or code
- Notes

**Comment by dakahn** [comment]
Looks like clicking the chevron on the right doesn't actually move focus -- so it's not throwing blur. I'm taking a look at this today 👍🏽
