### ISSUE TITLE
Glyphs in icons are being generated incorrectly in output extension

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9079]
This issue ultimately derives from glyph icons being added back into the codebase. This caused some downstream issues in our builders, along with errors in our icon demo site. This issue is to figure out how we can correctly ship icon glyphs and make sure that each part of our icons stream works as expected.

**Comment by emyarod** [comment]
related #8786 #8787

**Comment by joshblack** [comment]
@emyarod I think for the Sketch issues with glyphs we made need to filter out glyph sizes as an interim step until we can figure out how to use the sizes from the `descriptor` to construct the artboard as-needed 🤔
