### ISSUE TITLE
Focus order for overflow menu is not working.

### ISSUE THREAD

**Issue by kavyanekkalapu** [carbon-design-system/carbon#910]
Our team is working on accessibility testing(AVT) issues and we noticed issue with overflow menu component.

**Issue**: On tabbing to Overflow menu  and pressing enter, the list of options are displayed. On tabbing to last option , when user tabs further, the focus moves to title of the page. This focus order is not meaningful. On tabbing, either the focus should move to the next interactive element on the page or the focus should keep moving within the same section of the list item

I observed same issue http://www.carbondesignsystem.com/components/overflow-menu/code and 
http://www.carbondesignsystem.com/components/data-table/code.

**Note:** Issue does not exist in http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel.

**For more info :** https://ibm.enterprise.slack.com/files/W4FRVREA1/FB9LQG9C2/overflowmenu-focus.mov

**Comment by kavyanekkalapu** [comment]
One observation  is, when i inspect options in overflow menu, ul and li elements are displaying at bottom of the page, so even if i keep tab order, it is not useful as it seems , that is the end of the page.
Where as in react components, ul and li elements are displaying along overflow component div.


<img width="1259" alt="screen shot 2018-06-19 at 10 38 13 am" src="https://user-images.githubusercontent.com/37085529/41604322-ee8db12c-73ac-11e8-9a2e-7599809150aa.png">
<img width="1247" alt="screen shot 2018-06-19 at 10 38 01 am" src="https://user-images.githubusercontent.com/37085529/41604325-eec02e2c-73ac-11e8-9806-7267c0cefe65.png">

react screenshot:

<img width="1383" alt="screen shot 2018-06-19 at 10 38 58 am" src="https://user-images.githubusercontent.com/37085529/41604365-080cdeac-73ad-11e8-95ba-c347bef340a3.png">

Hope this helps in fixing the issue, thanks.

**Comment by asudoh** [comment]
Thank you @kavyanekkalapu for reporting. Looks a good one and we’ll see what we can do.
