### ISSUE TITLE
No UIShell in package/styles

### ISSUE THREAD

**Issue by henryennis** [carbon-design-system/carbon#9108]
Why has the UIShell component been left out of the styles package?

If I was to develop some components what is the best method to do so? I have looked at the storybook but it is hard to access the scss that applies to each individual component. Maybe symlinking the scss from packages/components that corelates with the component would make development easier?

**Comment by tw15egan** [comment]
Hey there @xSCIven, the `packages/styles` is still a WIP. The UI SHell styles will be ported over along with the rest of the components. For now, please use the `carbon-components` entry point (`packages/components`)
