### ISSUE TITLE
Overflow menu doesn't scroll with page

### ISSUE THREAD

**Issue by travis1111** [carbon-design-system/carbon#911]
## Detailed description

I have a page has many cards, there is a overflow menu (three vertical dots) on each card.  I can click on the menu (three dots) to bring the drop down menu.  However if the page has scroll bar (too many cards to fit into one page), when I scroll down, the drop down menu stays where it was, it won't scroll with the card it attached too.

> Is this issue related to a specific component? 

Overflow menu

> What did you expect to happen? What happened instead? What would you like to see changed?

Should scroll with the menu icon (three dots)

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Microclimate

## Steps to reproduce the issue

see description;

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by travis1111** [comment]
![image](https://user-images.githubusercontent.com/35569780/41615643-d03dd572-73c9-11e8-881e-e53171cb2568.png)

**Comment by alisonjoseph** [comment]
Can you create a codepen to show the issue you are having. I am unable to duplicate. Thanks! https://codepen.io/team/carbon/full/MOEwjp/

**Comment by travis1111** [comment]
and probably similar issue:

its a screen recording, you need to unzip and play.  Github doesn't allow me to attach videos.
[bug.mp4.zip](https://github.com/carbon-design-system/carbon-components/files/2127747/bug.mp4.zip)

**Comment by travis1111** [comment]
You won;t be able to reproduce it if you just use stock sample.  See my screen shot, I have cards, at least 4 cards, and make the screen just fit for 3 and try it.  Please can you take a  look of the video I attached above.

**Comment by tw15egan** [comment]
Can you recreate the sample in something like codesandbox or codepen? I see the issue, but without actually being able to look at the code there is not much we can do to help

**Comment by travis1111** [comment]
Hi, it turns out something to do with overflow-y: auto settings on the div we have.

So we have something like this

```
header here
<div style="overflow-y:auto;">
...
...
card with overflow menus, many of them

</div>
footer
```

The result is, we create a sticky header and footer, so that only the div with overflow-y:auto is scrollable.  The overflow menu is in that scrollable view.  When we click the three dots, the menus (ul wiith li s) are created outside of that div, so i think that is the why the overflow menu doesn't scroll with the content of the div.

So is there a way to let overflow menu to be placed inside the div, e.g. close to the element contains three dots so that it could stay with the 3 dots menu when scrolling?

**Comment by asudoh** [comment]
@travis1111 Currently not - We know there is a need for “custom floating menu target” mechanism, though, e.g. https://github.com/carbon-design-system/carbon-components/issues/910 - Will see if we can come up with something simple.

**Comment by travis1111** [comment]
Thanks @asudoh  also did you see the video I pasted above? bug.mp4.zip, I think it is also related, the ul is placed outside of the scrollable area.

Do you have a rough timeline for when this can be fixed?

**Comment by asudoh** [comment]
@travis1111 Not at this moment - Meanwhile, feel free to copy `overflow-menu.js` and `floating-menu.js` code over to your project and customize them as your project desires. Thanks!

**Comment by asudoh** [comment]
Oops I totally forgot that the floating menu code [looks at an element with `data-floating-menu-container` attribute first before looking at `<body>`](https://github.com/carbon-design-system/carbon-components/blob/7c6b173/src/components/floating-menu/floating-menu.js#L130). Hope it helps some.

**Comment by asudoh** [comment]
Wrt the movie in the zip - It appears different from the issue with scrolling this PR is taking about. Feel free to open a separate issue if the problem still exists. Thanks!

**Comment by travis1111** [comment]
@asudoh thanks.  how do I use this attribute?  something like this?

```sh
<div class="parent">
<div data-overflow-menu data-floating-menu-container=".parent" .....
```

**Comment by asudoh** [comment]
@travis1111 You are right assuming the 1st `<div>` contains the 2nd `<div>`.

**Comment by travis1111** [comment]
hmm then it is not working...


here is the demo code (I forked from your official codepen):

https://codepen.io/anon/pen/XYwoVM

**Comment by asudoh** [comment]
Oops I had a oversight looking at your HTML - It should be:

```html
<div data-floating-menu-container>
  <div data-overflow-menu ...>
    ...
  </div>
</div>
```

**Comment by travis1111** [comment]
@asudoh Hi, i tried this

`<div data-floating-menu-container>
...
...`


Still not working.  here is an example:

https://codepen.io/anon/pen/QBgbVJ/

**Comment by asudoh** [comment]
Floating menu uses `position:absolute`. It means that it's positioned with respect the nearest ancestor with a `position` other than `static` (refs: https://www.w3.org/TR/css-position-3/#comp-abspos and https://www.w3.org/TR/css-position-3/#containing-block). Adding `position:relative` to the `div.data-floating-menu-container` in your CodePen seems to fix the issue you described. Hope it helps.

**Comment by travis1111** [comment]
thanks.  but the y position is off... I added one more, you can see y position is doubled...

https://codepen.io/anon/pen/QBgbVJ/

**Comment by asudoh** [comment]
There is an option in overflow menu for you, which is [`objMenuOffset`](https://github.com/IBM/carbon-components/blob/53bfbcf/src/components/overflow-menu/overflow-menu.js#L191). An object with `top` and `left` properties, or a function returning such object can be set there. In this way you can adjust the overflow menu’s position tailored for your application’s structure. Options in Carbon vanilla classes/instances can be set via the second argument when you instantiate it (the `.create()` API: https://github.com/IBM/carbon-components/tree/53bfbcf/src/globals/js/mixins#creation). Hope it helps.

**Comment by travis1111** [comment]
Thanks I have made this working

https://codepen.io/anon/pen/QBgbVJ/

But I don't understand why I had to add a callback to adjust the position.  Also do you mind check if the code I have on codepen makes sense?

Also I used the same code (as above) in our project, the ``objMenuOffset`` callback is not called at all.  Is there anything preventing it from calling?

**Comment by asudoh** [comment]
Hi @travis1111 good question - What floating menu, the underlining mechanism of overflow menu, does is getting the position of the trigger button relative to the top/left corner of the viewport via CSSOM API and setting the top/left position of the menu based on that. Though we know that this is not something that will work for every usage pattern of floating menu, we also know that an attempt to support every usage pattern is almost impossible and tend to cause bloated, error-prone code. From that reason, what we do is setting the position that works for the most common pattern and provide an API to adjust the menu position.

BTW I see `objMenuOffset` callback is called in your CodePen. Note that it's called when the menu opens.

**Comment by travis1111** [comment]
Thanks @asudoh

Yes, the callback in codepen works, but it did not work in our project.  Is there any settings to prevent it from calling?  is the callback only available in latest version?

**Comment by asudoh** [comment]
@travis111 The most possible cause is the component was instantiated already before you tried to instatiate it with the option. Static `components` property has all the instances mapped with DOM elements and you may want to look into that.

**Comment by travis1111** [comment]
Thanks but I have this code

```
parent.insertAdjacentHTML ("beforeend",html);
        var offset = function () {
        	    console.log("in offset");
        	    return {top:0, left:100};
        }
        var options = { objMenuOffset: offset };
        
        CarbonComponents.OverflowMenu.create(document.getElementById("overflowmenu-" + project.projectID), {objMenuOffset: offset });
```

and if I comment out `` CarbonComponents.OverflowMenu.create....`` then when I click the overflow menu (3 dots), nothing happens...

**Comment by asudoh** [comment]
@travis111 You may want try debugging: https://github.com/IBM/carbon-components/blob/b8276de/src/components/floating-menu/floating-menu.js#L156

**Comment by travis1111** [comment]
Still don't know why...

this is what shows in the debugger of my project:

![image](https://user-images.githubusercontent.com/35569780/43333730-39c1fee6-9199-11e8-9048-699cfd5e5034.png)

and step in:

![image](https://user-images.githubusercontent.com/35569780/43333565-8f9f8cb2-9198-11e8-81f8-7e1623090ecd.png)

and this is what shows in codepen:

![image](https://user-images.githubusercontent.com/35569780/43333595-af5ce2ca-9198-11e8-9ed9-67d83a7e16c6.png)


When the _changeState.apply is called, the codepen source has the correct offset object which is a callback I defined, but in my project it is replaced by ``getMenuOffset`` from carbon component.

**Comment by asudoh** [comment]
@travis1111 You may want to debug the `.create()` then: https://github.com/IBM/carbon-components/blob/0336425/src/globals/js/mixins/create-component.js#L45

Whether or not your `option` is applied or not will be determined by if there is an existing instance, as the code shows.

**Comment by travis1111** [comment]
@asudoh I changed the source code and ran it in the debugger, no existing components, as you can see from the debugger below.  So what I do next?

![image](https://user-images.githubusercontent.com/35569780/43404203-eaf9e942-93e4-11e8-964d-9383486543a3.png)

**Comment by asudoh** [comment]
@travis1111 I see you are using “flip mode” of floating menu. My apologies not imagining you using that, but the option to use for flip mode is `objMenuOffsetFlip` instead of `objMenuOffset`: https://github.com/IBM/carbon-components/blob/53bfbcf/src/components/overflow-menu/overflow-menu.js#L117-L119

**Comment by travis1111** [comment]
thanks change to ``objMenuOffsetFlip`` now it calls the call back, but the position is still not right.  When are you going to be online tomorrow?  do you mind I sametime you?

**Comment by asudoh** [comment]
Hi 👋 I recently got a document update, which you may want to refer to: https://github.com/IBM/carbon-components/tree/ad19b01/src/components/overflow-menu#example---changing-menu-position-by-8-pixels-vertically

You can search for channels with Carbon names in our internal communication tool to reach out to us internally.
