### ISSUE TITLE
Inline Select component needs background in Chrome/Windows

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#9112]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`
- [x] `carbon-components-svelte`

## Detailed description

In Chrome on Windows a `<select>` background needs to be set to fit the `<color>`, otherwise the options can become unreadable. This is very OS and browser-specific; e.g. it is not a problem for Firefox on Windows or Chrome on Mac.

Affected is the `<Select>` component with the inline class set without mouse hover in a dark theme. E.g. used in `<Pagination>`.

With hover (CSS sets background):
![image](https://user-images.githubusercontent.com/834235/124446455-b78dad80-dd80-11eb-9c6f-fb836ecb751e.png)

Without hover:
![image](https://user-images.githubusercontent.com/834235/124446575-d68c3f80-dd80-11eb-980d-3d98898e0785.png)

## Steps to reproduce the issue

1. Use dark theme
2. Add `<Pagination>`
3. Open one of the dropdowns
4. Move mouse away

The [official component page](https://www.carbondesignsystem.com/components/pagination/usage/) demonstrates this behavior.

## Additional information

Relevant CSS that seems to cause this:
```css
.bx--select--inline .bx--select-input {
    ...
    background-color: transparent;
    ...
}
```

The select already has an explicit background otherwise.

**Comment by dakahn** [comment]
still seeing this on Windows in Chrome latest
![image](https://user-images.githubusercontent.com/40970507/127352254-2b3d8cf7-9161-4f49-bf00-6dd5f567b846.png)

**Comment by brunnerh** [comment]
For me the problem is no longer there both with the Svelte components (which uses carbon-components `10.40.0`) and on the website, which shows:
```
Vanilla Components version ^10.40.0
React Components version ^7.40.0
```

🤔
