### ISSUE TITLE
Extra space in 3 button modal footer

### ISSUE THREAD

**Issue by weaseldotro** [carbon-design-system/carbon#9117]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
[Link to storybook](https://react.carbondesignsystem.com/iframe.html?id=components-modal--playground&knob-Number%20of%20Buttons=3&knob-Open%20(open)=true&knob-Modal%20heading%20(modalHeading)=Modal%20heading&knob-Optional%20label%20(modalLabel)=Label&knob-ARIA%20label,%20used%20only%20if%20modalLabel%20not%20provided%20(modalAriaLabel)=A%20label%20to%20be%20read%20by%20screen%20readers%20on%20the%20modal%20root%20node&knob-Primary%20focus%20element%20selector%20(selectorPrimaryFocus)=[data-modal-primary-focus]&knob-Size%20(size)=md&knob-Close%20icon%20description%20(iconDescription)=Close&knob-Prevent%20closing%20on%20click%20outside%20of%20modal%20(preventCloseOnClickOutside)=true&knob-Primary%20button%20text%20(primaryButtonText)=Primary%20button&knob-Secondary%20button%20text%20(secondaryButtonText%20in%20%3CModalFooter%3E)=Secondary%20button)

When using the 3 button modal, there is some extra space to the left of the footer. It looks like there should be 4 buttons, but there are only 3, and the first button is missing. 
I think the buttons should span all the available space, with each button having a width of 33.33%, so it would be consistent with the looks of the 2 button modal. Now this looks like those blank switches you see in cars who have some missing options.

I read the component guidance for modals https://carbondesignsystem.com/components/modal/usage/ and the PR https://github.com/carbon-design-system/carbon/pull/7775 but it doesn't say anything about the reasoning of this situation. I'm guessing it's because of symmetry, so that there's a clear distinction where the half point of the footer is?

On a phone this looks particularly bad, the first button container is squeezed so there is just some blank space at the left of the modal footer.

![9BE072DC-39C9-4E6D-8C39-3BF3AB108743](https://user-images.githubusercontent.com/1822852/124554402-9ab7af80-de3e-11eb-922f-57f519918c40.png)

**Comment by tw15egan** [comment]
[Rendering as designed](https://www.carbondesignsystem.com/components/modal/usage#transactional-modal)

![Screen Shot 2021-07-06 at 9 43 49 AM](https://user-images.githubusercontent.com/11928039/124610619-ac00bc00-de3e-11eb-9d6c-9757797dad2a.png)

cc @carbon-design-system/design for feedback
