### ISSUE TITLE
Inline Loading Component

### ISSUE THREAD

**Issue by loganmccaul** [carbon-design-system/carbon#912]
## Inline Loading
A new pattern for loading Create, Read, and Update actions

## Detailed description
Throughout the IBM Cloud Platform the existing Loading spinner is being used for small update interactions.

A primary example of this is within the Invite Users flow:
![flow_iam-invite-user](https://user-images.githubusercontent.com/7374889/41612747-6afbbbb2-73b9-11e8-83c1-b1cb7460d957.gif)

What started as feedback about performance from user's turned into a month long project looking at perceived performance within the platform. One of the major insights that we found was that the loading overlay for small actions seemed unnecessary.

"[It] was really fast, but didn't know why it needed to disable the whole page just to add a user."

However, user's also weren't sure how long the loading would take. In this case it's usually pretty fast, but many of the user's we talked to have been stuck on a loading overlay for over 30 seconds before.

With this new component our goal is to address some of the pain points uncovered.

- Remove the overlay so the user can navigate and interact with the page while the action is occurring
- Provide feedback so that the user knows when the action succeeds
- Adding text to provide context of the action taking place

This is the design that met our requirements and tested best with users.
Individually:
![inlineloadingsolo](https://user-images.githubusercontent.com/7374889/41620357-11819212-73cf-11e8-93ea-106796b39560.gif)

In Context: 
![inlineloadingincontext](https://user-images.githubusercontent.com/7374889/41555622-e6fefbb4-72fd-11e8-858a-125a8e9d50d8.gif)

Similar to https://github.com/carbon-design-system/carbon-addons-cloud-react/pull/11 this could also live in the carbon-addons-cloud repo, however since this one is a bit more generic, we feel it could be valuable to Carbon as a whole.

Furthermore we are not 100% tied to this design, if you think change could be made please share.

## Use
The Inline Loading component has multiple uses! However, we feel it works best when doing any Create, Update, or Delete actions. This could be in a table, after a primary or secondary button click, or even in a modal.

If using React, this is one way you can implement this component.
```
import React from 'react'
import InlineLoading from 'carbon-components-react' // Import InlineLoading from carbon

class example extends React.Component {
  constructor(props) {
    super(props);
    
     // Have two states, loading and success. By default both are false
     this.state = {
        loading: false,
        success: false
      }
  }

  submit() {
    // On submit button press set the loading state to true
    this.setState({
      loading: true
     });

    // Send of whichever requests needs to be done
    fetch("/get/data/please").then(() => {
      // On success set loading state to false, and set success state to true
      this.setState({
        loading: false,
        success: true
      });
    }).catch(() => {
      // On error reshow button
      this.setState({
        loading: false,
      });
    });
  }

  render () {
    const { loading, success } = this.state;

    return (
      {loading || success ? // If loading or success show the InlineLoading component
        <InlineLoading state={success ? 'SUCCESS' : 'LOADING'} /> // Check to see if success should be shown or not
      :
        <button onClick={() => this.submit()}>Example</button> // Trigger for to show the InlineLoading
      }
    );
  }
}
```
*Note The above code is untested written in Github. Use as a guideline more than anything.

The `SUCCESS` state of the Inline Loading component is active for 1.5 seconds before calling a optional function `onSuccess`. Use the `onSuccess` function to refetch new data, close a modal, or reset a form. If no function is specified the `SUCCESS` state will last indefinitely.

If an error occurs, the Inline Loading component should be hidden and a error notification should be added or error handling within a form should appear.

Text is optional, but encouraged. If you have limited room or find adding text to be unnecessary you can just run through the animations.

If the Inline Loading is being used to submit a form, the form fields should get disabled.

Furthermore the Inline Loading component should never be used to load a page or data.

**Comment by tay-aitken** [comment]
@loganmccaul we should sync up about adding in design guidelines for this.

**Comment by tw15egan** [comment]
The component has been merged. I'm going to close this, and we can start a new issue on the design system website repo for design guidelines
