### ISSUE TITLE
Known vulnerability in d3-colour 

### ISSUE THREAD

**Issue by gmc77** [carbon-design-system/carbon#9133]
## What package(s) are you using?
- [x] `carbon-components-react`

## Detailed description
As flagged by Snyk when we use Carbon in our product. 

```
Issues to fix by upgrading:
  Upgrade d3@5.16.0 to d3@7.0.0 to fix
  ✗ Regular Expression Denial of Service (ReDoS) (new) [Medium Severity][https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592] in d3-color@1.4.1
    introduced by d3@5.16.0 > d3-color@1.4.1 
```

See https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592 for details. It can be fixed by upgrading to later versions of d3 

## Steps to reproduce the issue
Run Snyk against a Carbon application

**Comment by emyarod** [comment]
can you confirm where d3-color is being used?

**Comment by gmc77** [comment]
Apologies, missed the question when it was raised.

We're not using it directly, and neither is Carbon, but in Carbon Charts imports d3, which imports d3-color

https://github.com/carbon-design-system/carbon-charts/blob/524c00d012f567799b35f834e57648273420adc2/yarn.lock#L3596

Have raised a carbon charts issue https://github.com/carbon-design-system/carbon-charts/issues/1069
