### ISSUE TITLE
Link not working on first click with Sandbox attached for example

### ISSUE THREAD

**Issue by LeviApp** [carbon-design-system/carbon#9137]
I am using the carbon-components and carbon-components-react dependencies

I am trying to create a style on an anchor's active state. While the style is applied if you click on the link twice, the style is not applied the first time it is clicked.

I am using the SideNav, with SideNavItems and SideNavItem links, but it could be a broader issue.

I am using
"@carbon/charts-react": "0.41.52",
"@carbon/icons-react": "10.29.0",

We are building a dashboard for IBM. We need it fixed as soon as possible.

Use Carbon's standard class names
Apply active style in scss
I am using a Windows 10 virtual machine.

https://codesandbox.io/s/fixed-sidenav-forked-276kl

**Comment by emyarod** [comment]
is this behavior what you are looking to accomplish? https://codesandbox.io/s/fixed-sidenav-forked-sd5yu

**Comment by LeviApp** [comment]
@emyarod 

I am needing the focus state to work the first time I click. I have to click on the link twice right now for the focus state to be implemented. The sandbox looks right except the focus state is overwritten when someone hovers over it. Not sure if that is normal or not.

**Comment by emyarod** [comment]
@LeviApp the focus state seems to be applying as expected even in your original Code Sandbox. you'll have to provide a screen recording or something for more info. as for focus color being overwritten during hover, this is also working as expected. you can modify that with CSS as well

**Comment by LeviApp** [comment]
@emyarod
Here is the demo of what is going on.

https://user-images.githubusercontent.com/38485877/125115336-70692a80-e0a8-11eb-8db2-4365dcd2decf.mp4

**Comment by emyarod** [comment]
I was just looking for a recording of the interaction itself but after skimming through the video this seems to be an application level issue, especially given how the interactions seem correct in code sandbox. can you debug which element receives focus after you click on the link once (checking what the value of `document.activeElement` is after clicking the link)?

**Comment by emyarod** [comment]
@LeviApp  I was just looking for a recording of the interaction itself but after skimming through the video this seems to be an application level issue, especially given how the interactions seem correct in code sandbox. can you debug which element receives focus after you click on the link once (checking what the value of `document.activeElement` is after clicking the link)?

**Comment by LeviApp** [comment]
@emyarod It looks like it is a refreshing issue with the links. If I disconnect the routes, the active works just fine. However, I need the links to route to the new url. Any suggestions, or anything you can do to fix this in Carbon?

**Comment by abbeyhrt** [comment]
Hey @LeviApp Sorry for the delay! Coming back to this, we aren't sure how to address this, the code sandbox is working on our end. Would you be able to share how this is working within your application?

**Comment by joshblack** [comment]
Going to close this out due to inactivity. Feel free to open up a new issue and we can continue this discussion!
