### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by Steakeye** [carbon-design-system/carbon#9144]
### Summary

Please describe your request in one or two sentences.
When bundling my application, I now get a lot of noise from the SCSS step because the latest version of Dart Sass is warning of deprecated Sass syntax in `@carbon/elements` scss files. Specifically, the issue lies with the use of `/` instead of `math.div` which is now preferred.

Essentially, this is a future technical debt task.

### Justification

This will need to be done at some point as the recommended Sass engine is now the Dart Sass engine, which is the main project in active development. As of Dart Sass 2.0.0, the use of `/` for mathematical operations will no longer be possible.

### Desired UX and success metrics

Desired UX would be that build steps aren't filled swith noisy warnings and everything works as before, in terms of CSS output.
Metrics would be measured in a significant decrease in STDOUT lines of warnings.

### "Must have" functionality

Carbon Elements work as before.

### Specific timeline issues / requests

Entirely up to you.

### Available extra resources

https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by joshblack** [comment]
Hi there! 👋  We're currently tracking this over in: https://github.com/carbon-design-system/carbon/issues/8746

**Comment by Steakeye** [comment]
Thanks for letting me know! I promise I tried to look for any duplicate before I added my request!
