### ISSUE TITLE
[TextInput] Invalid indicator out of TextInput when using marginBottom

### ISSUE THREAD

**Issue by lamualfa** [carbon-design-system/carbon#9150]
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

The Invalid Indicator of TextInput component will out of the `TextInput` when `marginBottom` was set.

Why i use `marginBottom` to give a gap between two form?

I don't know. I just follow Carbon React Storybook Sample. This is the [link](https://react.carbondesignsystem.com/?path=/story/components-formgroup--playground).

## Steps to reproduce the issue

1. Create a `TextInput` component.
2. Set the `invalid` & `invalidText` props of `TextInput` component.
3. Add `marginBottom` to `TextInput` component.

React:

https://codesandbox.io/s/wispy-rain-hdpfu?file=/index.js

## Additional information

- Screenshots or code

![image](https://user-images.githubusercontent.com/39755201/125039497-c34edc00-e0c0-11eb-88a4-6cf6bdb38895.png)

**Comment by tw15egan** [comment]
Hey there @lamualfa, it seems like you can avoid this issue by adding the `marginBottom` to the wrapper div, as opposed to the `TextInput` itself. Hope that helps!

**Comment by lamualfa** [comment]
> Hey there @lamualfa, it seems like you can avoid this issue by adding the `marginBottom` to the wrapper div, as opposed to the `TextInput` itself. Hope that helps!

Absolutely yes. I think in future, the use of `marginBottom` in Storybook Example must be replaced with the use of `marginBottom`  in wrapper.

**Comment by tw15egan** [comment]
Agreed, I will make a PR and update this. Thanks for catching it!
