### ISSUE TITLE
Progress Indicator Animations

### ISSUE THREAD

**Issue by lisakaiser** [carbon-design-system/carbon#9156]
### Summary

Requesting to enhance the progress indicator component with animations showing the blue line progressing as steps are completed and the icons change to help the user better understand their progress as they complete forms. Also, requesting a slight change to the "optional text" under each text to instead a show a summary of what the user selected in that step.

This would require motion design and development work.

### Justification

This would reduce the cognitive load of the user and help them better make connections between the steps. The addition of the "summary text" could also provide a "summary" step for our users - allowing them to review progress made without going back and taking additional steps. 

### Desired UX and success metrics

When a user completes a step, the progress line would animate to show their progress. At the same time, the summary text would fade in as well as the blue step indicator would transform to the check mark. Here's a mock up of how this could work:
![Horizontal Progress Tracker](https://user-images.githubusercontent.com/73298410/125118741-bed0f600-e0b5-11eb-9807-f0cdd2b52e94.gif)
![Progress Tracker 01](https://user-images.githubusercontent.com/73298410/125118831-df994b80-e0b5-11eb-93d0-294be96f5dd8.gif)

Success/failure could be measured through user testing the current implementation of this component with the proposed changes OR how current forms work without vs with and user's preferences. 

### "Must have" functionality

- Blue line/icons animating

Some additional functionality to consider:

- Creating anchor links in the indicator so users can easily revisit steps
- Showing error states in the progress indicator steps when users try to complete the form or miss a section

### Specific timeline issues / requests

no specific time line

### Available extra resources

What resources do you have to assist this effort?

I (@lisa-j-kaiser) am happy to help with any design/animation and @kristastarr (krista.starr@ibm.com) is working on development of this component to contribute back.

**Comment by lisakaiser** [comment]
Here's the mock up I shared at the design review yesterday as well exploring what might happen if a user skips a section: 
![Progress Tracker 01-2 2](https://user-images.githubusercontent.com/73298410/125120036-803c3b00-e0b7-11eb-853d-fc0da60fad7b.gif)

**Comment by jnm2377** [comment]
@johnbister will follow up with you on this. :)

**Comment by johnbister** [comment]
@lisakaiser @kristastarr Hey! This looks like a really cool effort and I apologize I was OOO when you presented to the larger Carbon group.  Let me know how I can help.

**Comment by kristastarr** [comment]
Awesome, thanks! I’m working on a modification to the existing component right now. I should have a demo app to show y’all soon- when everyone is happy with it, I could go ahead and submit a PR for review.

**Comment by laurenmrice** [comment]
Closing since we will not be maintaining the code for this according to #9340
