### ISSUE TITLE
InlineLoading inactive state animation is broken

### ISSUE THREAD

**Issue by yasotnik** [carbon-design-system/carbon#9163]
## Brief description
`InlineLoading` component inactive state animation is broken:

![image](https://user-images.githubusercontent.com/5897195/125266191-dc949a00-e305-11eb-8f04-b724b83dbd29.png)

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Looks like inactive state in `InlineLoading` component has some weird animation of circle spinning backwards (?).
Versions used:
carbon-components@10.29.0
carbon-components-react@7.29.0

Tested both in Firefox (89.0.2 (64-bit)) and Chrome (Version 91.0.4472.124 (Official Build) (64-bit))

## Steps to reproduce the issue

Have `InlineComponent` with `status='inactive'`.
You could reproduce it in react-components storybook e.g [InlineComponent](https://react.carbondesignsystem.com/?path=/story/components-inlineloading--inline-loading&knob-Description%20(description)=Active%20loading%20indicator)

## Notes:

Looks like it was introduced with` carbon-components-react 7.6.0`

**Comment by yasotnik** [comment]
Looks like when it was working it had just spinning animation in inactive state. 
Should not it be just a grey circle instead ? I am not a UX expert but from my perspective as a user it will be more natural.

**Comment by emyarod** [comment]
cc @carbon-design-system/design just to confirm, what should the inactive state inline loading indicator look like?

**Comment by yasotnik** [comment]
I guess bot added wrong label to the issue.
@emyarod
I am not part of the carbon team but what I have found so far there should not be an `INACTIVE` state at all. 
[Link](https://www.carbondesignsystem.com/components/inline-loading/usage/#states)
`The inactive loading state is when no data is being loaded. Inactive has no visual indicator.`

**Comment by aagonzales** [comment]
Yeah `inactive` just animates to no visual. I was working correctly in previous releases.
