### ISSUE TITLE
Update components to use new design tokens

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#9175]
Component tokens will need to be updated to use the new tokens. 

Notion doc: https://www.notion.so/carbondesignsystem/Final-List-of-new-tokens-fc5985c7331341baa6546064399d36da
Component specs: https://github.com/carbon-design-system/carbon/issues/8187
Previous Epic: https://github.com/carbon-design-system/carbon/issues/8148

The previous attempts can be used as a reference
https://github.com/carbon-design-system/carbon/pull/9064
https://github.com/carbon-design-system/carbon/pull/9065
https://github.com/carbon-design-system/carbon/pull/9066
https://github.com/carbon-design-system/carbon/pull/9067

List of SASS Component Refactors: 

- https://github.com/carbon-design-system/carbon/issues/8899

**Comment by andreancardona** [comment]
@tw15egan @dakahn 

Since these are assigned to us this sprint. Going to start looking at the following: 

- Accordion
- Breadcrumb
- Button
- Checkbox
- Codesnippet
- Combobox

**Comment by andreancardona** [comment]
Moving on to these: 

- Overflow menu
- Pagination
- Pagination nav
- Popover
- Progress indicator
- Radio button
- Search
- Select
- Slider
- Structured list
- Tabs

**Comment by tw15egan** [comment]
Going to work on porting over `ComboBox`, `Dropdown`, `Listbox` and `Multiselect` today, those will need to be updated to the new tokens once they are merged in
