### ISSUE TITLE
Issue with using ExpandableTile within a Tab

### ISSUE THREAD

**Issue by molyholy** [carbon-design-system/carbon#9187]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

>Describe in detail the issue you're having.

The ExpandableTile component's default "unexpanded" state does not have the correct height when the page first renders. The below screenshot shows how they're way too short.
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/23204596/125320972-3bf4a900-e30a-11eb-92f3-954ab267fd06.png">

And the tile boxed in red shows what it's actually supposed to look like, with some elements AboveTheFold. You can "fix" this bug by expanding and collapsing the tile, but the user shouldn't have to do that to achieve the desired appearance.
![image](https://user-images.githubusercontent.com/23204596/125321083-562e8700-e30a-11eb-9512-e81a81ae7d33.png)

-----------

After some poking around, it may have something to do with the Tabs and how the selected tab function works. By default, the first Tab ("Active") is selected, and the second "Upcoming" tab is not by default selected (and is where the ExpandableTiles are located). 

This is how the page loads right now, with the "Active" Tab being the default selected Tab. You can see how the ExpandableTiles under the "Upcoming" Tab have the incorrect collapsed height, which can be fixed by expanding/collapsing it.
![9d599280-db28-11eb-9e60-88e2a798e003](https://user-images.githubusercontent.com/23204596/125322327-a5c18280-e30b-11eb-86ee-7f5e416734cd.gif)

However, when the default selected Tab is "Upcoming," then the bug does not occur.
![6d11f400-db28-11eb-88e1-fb20ffab73d4](https://user-images.githubusercontent.com/23204596/125321931-2f248500-e30b-11eb-8443-facf6cca4df9.gif)

It might have something to do with [this](https://github.com/carbon-design-system/carbon/blob/e7ef150ba1d74e2e864a9d6d67e612e824dcbf51/packages/react/src/components/Tile/Tile.js#L516) line that calls `getBoundingClientRect()` because when I tried calling that function from the Inspector it always returned zeros for every dimension.

> Is this issue related to a specific component?
ExpandableTile and Tabs

> What browser are you working in?
Firefox

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
This is for the Commitments and Subscriptions page for the billing microservice.

## Steps to reproduce the issue

1. Go to https://test.cloud.ibm.com/billing/subscriptions
2. Login with username `orlando.mendoza1+sld_08@mail.test.ibm.com` and password `ServiceLD01!`
3. Click on the "Upcoming" Tab

## Additional information

[Link to another issue within IBM that documents this bug](https://github.ibm.com/ibmcloud/TOB/issues/124)

**Comment by dakahn** [comment]
Thanks for reporting with a thorough issue ticket!
