### ISSUE TITLE
Carbon DataTables — .bx--data-table tbody th, .bx--data-table td { padding-right

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#9196]
Hi 👋 I work in the Observability space of IBMCloud and I am wondering if we can allow for this padding to change.

Our tables have a lot of text content in them and I feel would benefit if we could set padding-right to zero.

<hr>

Here is how it currently looks with the default Carbon padding-right:

<img width="1364" alt="Screen Shot 2021-07-13 at 4 42 24 PM" src="https://media.github.ibm.com/user/273948/files/a8020a80-e3f9-11eb-9b3a-032be6fff537">

and here is how it looks with padding-right set to zero:

<img width="1375" alt="Screen Shot 2021-07-13 at 4 42 15 PM" src="https://media.github.ibm.com/user/273948/files/b2240900-e3f9-11eb-8be7-15a6c7f3b982">

I feel the tables are much more readable and more easily scannable with the padding-right set to zero.

<hr>

Another issue this amount of padding causes is at smaller screen sizes (or just when the browser window is a smaller width) this happens:

<img width="709" alt="Screen Shot 2021-07-13 at 4 14 22 PM" src="https://media.github.ibm.com/user/273948/files/ee576980-e3f9-11eb-848b-dd1ffd391803">
<img width="701" alt="Screen Shot 2021-07-13 at 3 33 02 PM" src="https://media.github.ibm.com/user/273948/files/f1eaf080-e3f9-11eb-90d3-b9e341d5e97d">
<img width="644" alt="we dont want" src="https://media.github.ibm.com/user/273948/files/f44d4a80-e3f9-11eb-96d1-7c01f0eaa172">

<hr>

Is there a way for Carbon to allow this to be zero? if not, is there a way that the amount of padding could be more responsive depending on the screensize?

**Comment by emyarod** [comment]
cc @carbon-design-system/design regarding the proposed padding changes. in the meantime, the workaround would be to add responsive styles to your application

**Comment by LaurenBrame** [comment]
@jrpomeroy can we do this^? add responsive styles

**Comment by LaurenBrame** [comment]
@emyarod thank you for the response! Do you think I should I report this issue in a different repo?

**Comment by emyarod** [comment]
@LaurenBrame this issue can remain open in this repo

**Comment by jrpomeroy** [comment]
@LaurenBrame You'll want to start a discussion with the PAL designers to see if we can get agreement on this. What we don't really want is for each individual service to override these carbon styles.

**Comment by LaurenBrame** [comment]
reported to PAL: https://github.ibm.com/ibmcloud/pal/issues/4799

**Comment by jnm2377** [comment]
@LaurenBrame it seems like this is being addressed in the PAL repo, so I'm closing this issue for now. Until we see more use cases for it, we'll consider adding it in Carbon. For now, we think handling it in the PAL repo is the best course of action.
