### ISSUE TITLE
Missing helperText feature in DatePicker component

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#9199]
## What package(s) are you using?

- [x] `carbon-components` 10.35.0
- [x] `carbon-components-react` 7.35.0

## Detailed description
Currently I am using [TextInput](https://www.carbondesignsystem.com/components/text-input/usage/#live-demo) and [NumberInput](https://www.carbondesignsystem.com/components/number-input/usage/#live-demo). Both provide the parameter `helperText`, for displaying a text below the input field. TextArea (documented in TextInput) also provides `helperText`.

Now I want to use [DatePicker](https://www.carbondesignsystem.com/components/date-picker/usage#live-demo). When I add a parameter `helperText` in DatePicker, I receive following error:
> Warning: React does not recognize the `helperText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `helpertext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

In the source code, neither in [DatePicker](https://github.com/carbon-design-system/carbon/blob/ea814ec692cf8554c8460553d7f5c22d39c9e1df/packages/react/src/components/DatePicker/DatePicker.js) nor in [DatePickerInput](https://github.com/carbon-design-system/carbon/blob/ea814ec692cf8554c8460553d7f5c22d39c9e1df/packages/react/src/components/DatePickerInput/DatePickerInput.js) i find something with `help`.

I would expect the same behavior like in TextInput or NumberInput, the helperText should appear below the DatePicker.

## Steps to reproduce the issue
1. Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox
2. Paste following Code in `index.js`
```
import React from 'react';
import { render } from 'react-dom';
import { TextInput, DatePicker, DatePickerInput } from 'carbon-components-react';

const App = () => (
  <>
    <TextInput 
      helperText="text input helper text" 
      id="text-input" 
      labelText="text input label"/>
    <DatePicker helperText="date picker helper text">
      <DatePickerInput 
        helperText="date picker input helper text"
        id="date-picker-input"
        labelText="date picker input label"/>
    </DatePicker>
  </>
);

render(<App />, document.getElementById('root'));
```

**Comment by emyarod** [comment]
cc @carbon-design-system/design the website shows some specs for date pickers with helper text but they differ from the pattern we use elsewhere in the system. is there an updated date picker spec that includes helper text?

**Comment by aagonzales** [comment]
Helper text should be below the input like so 
![image](https://user-images.githubusercontent.com/11670886/125828769-53244354-1a28-4efe-83fb-09aa7b5b1a41.png)
