### ISSUE TITLE
V9 tooltip does not show on hover or close on blur

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#920]
## Detailed description

Behaviour shown here https://codepen.io/team/carbon/pen/pdeLom

> Is this issue related to a specific component? 
Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

Interactive Tooltips can contain text and other interactive elements such as a Button or a Link. They appear on mouse click and are persistent until intentionally dismissed by clicking outside of the tooltip.

> What browser are you working in? 
Chrome

> What version of the Carbon Design System are you using? 
9.1.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

The issue can be seen as reported in codepen.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by alisonjoseph** [comment]
HI @lee-chase the tooltip was intentionally updated in `v9` to appear on click instead of hover. The usage docs can be found here http://www.carbondesignsystem.com/components/tooltip/usage . If you are looking for a tooltip with information on hover the definition tooltip may be the better fit.
