### ISSUE TITLE
Explain carbon components to a newbie

### ISSUE THREAD

**Issue by Blazing-Mike** [carbon-design-system/carbon#9216]
I'm an beginner in front-end development and would like to work with carbon and pure Javascript no frameworks. But there's no definitive guide on starting. Can you create a guide or tutorial on how to use carbon as a beginner?

**Comment by tay1orjones** [comment]
Hi @Blazing-Mike 👋 Thanks for reaching out about this. We unfortunately are primarily focused on the React implementation at the moment, there are no plans to make a vanilla tutorial. That said, there is some [documentation](https://the-carbon-components.netlify.app/) provided on an as-is basis for the vanilla components.
