### ISSUE TITLE
Blue border for Tab component in some cases

### ISSUE THREAD

**Issue by shizy818** [carbon-design-system/carbon#9217]
## What package(s) are you using?

- [x] `carbon-components` 10.39.0
- [x] `carbon-components-react` 7.39.0

## Detailed description

> Describe in detail the issue you're having.

Tab 1 can be selected and has a blue border.
![图片](https://user-images.githubusercontent.com/2142335/126054136-7f6f5101-29aa-4352-9ac1-4acc85d94902.png)

Tab 2 does not has the border.
![图片](https://user-images.githubusercontent.com/2142335/126054142-5ac2242a-4420-410e-a146-f2bc16f6cecd.png)

The diffenence seems that attribute `tabindex=0` is added for some tabs.
![图片](https://user-images.githubusercontent.com/2142335/126054191-40892c9a-2b64-4116-891c-93bd660c3031.png)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the tab behavior are consistent.

> What browser are you working in?

Firefox

## Steps to reproduce the issue

1.  https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox
2.  Paste following Code in index.js
```
import React from 'react';
import { render } from 'react-dom';
import { Tabs, Tab, Button } from 'carbon-components-react';

const App = () => (
<div>
  <Tabs>
    <Tab
      href="#"
      id="tab-1"
      label="Tab label 1"
    >
      <div className="some-content">
        <p>Content for first tab goes here.</p>
      </div>
    </Tab>
    <Tab
      href="#"
      id="tab-2"
      label="Tab label 2"
    >
      <div className="some-content">
        <p>Content for second tab goes here.</p>
        <Button>With a button</Button>
      </div>
    </Tab>
    <Tab
      href="#"
      id="tab-3"
      label='Tab label 3'
    >
      <div className="some-content">
        <p>Content for third tab goes here.</p>
      </div>
    </Tab>
  </Tabs>
</div>
);

render(<App />, document.getElementById('root'));

```

## Additional information

- Screenshots or code
- Notes

**Comment by tay1orjones** [comment]
In this case when a tab doesn't contain interactive content, focus should be applied to the tab container. This was implemented as part of https://github.com/carbon-design-system/carbon/pull/7894. Hopefully this is helpful to show this is intentional behavior.
