### ISSUE TITLE
Calendar in DatePicker is not positioned right

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#9220]
## What package(s) are you using?
- [x] `carbon-components` 10.35.0
- [x] `carbon-components-react` 7.35.0

## Detailed description
I am using [DatePicker](https://www.carbondesignsystem.com/components/date-picker/usage#live-demo) variant "single with calendar". I noticed that the width of the component is fixed to `18rem`, matching the calendar popup width. My inspection shows this predefined CSS.
```
.bx--date-picker.bx--date-picker--single .bx--date-picker__input {
    width: 18rem;
}
```
But my forms have dynamic input widths, so I made the DatePicker also with a dynamic width. The problem now is, that the calendar is positioned left, away from the calendar icon.

I would expect the calendar to remain right, where the calendar icon is.

This flatpickr calendar is somehow positioned outsite of the react app, appended in the `<body>`. Its CSS has some magic left positioning
```
// in codesandbox where no sorrounding padding exists
element.style {
    top: 66px;
    left: 0px;
    right: auto;
}
```
```
// in storybook where a padding around a story exists
element.style {
    top: 262px;
    left: 42.5px;
    right: auto;
}
```
It is anyways left aligned to the input field.

Is there any way to define the position? In the source code, neither in [DatePicker](https://github.com/carbon-design-system/carbon/blob/ea814ec692cf8554c8460553d7f5c22d39c9e1df/packages/react/src/components/DatePicker/DatePicker.js) nor in [DatePickerInput](https://github.com/carbon-design-system/carbon/blob/ea814ec692cf8554c8460553d7f5c22d39c9e1df/packages/react/src/components/DatePickerInput/DatePickerInput.js) I find something with `position`.

## Steps to reproduce the issue
1. Go to https://codesandbox.io/s/confident-black-cm74p?file=/src/MyFancyDatePicker.scss
2. Click on the calendar icon.

**Comment by tay1orjones** [comment]
Hi @FabianPiconeDev, this relates to the [fluid inputs proposal](https://github.com/carbon-design-system/carbon/issues/5416) that is approved but still a work in progress. The calendar remaining left aligned on a fluid width input is to spec based on the images in the linked issue.

> Is there any way to define the position?

The positioning is determined by the [appendToPlugin](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DatePicker/plugins/appendToPlugin.js) that is [passed to flatpickr](https://github.com/carbon-design-system/carbon/blob/f837fbcfbd250134a32ae36d38f4537c578bb3e9/packages/react/src/components/DatePicker/DatePicker.js#L353-L357). To modify positioning of the calendar you can target the `.flatpickr-calendar` class with custom CSS, or another potential route would be to customize the dom element that the flatpickr is inserted into via the [`appendTo` prop](https://github.com/carbon-design-system/carbon/blob/f837fbcfbd250134a32ae36d38f4537c578bb3e9/packages/react/src/components/DatePicker/DatePicker.js#L130). 

Let me know if this is helpful - I'm going to close this for now, but can always reopen if there's a continued issue. Thanks!
