### ISSUE TITLE
React Breadcrumb uncaught error if string without href

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#9224]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The breadcrumb has the option of last item being the current page. In this scenario the breadcrumb may well be a string with no href supplied. This however produces an unhandled error.

e.g.
```
    <BreadcrumbItem isCurrentPage={true}>
      The current page
    </BreadcrumbItem>
```

produces

![image](https://user-images.githubusercontent.com/15086604/126175034-0ec1c631-c0a5-4428-bec1-1ac02cacde90.png)

It is possible to work around this by wrapping the text in a an element e.g.

```
    <BreadcrumbItem isCurrentPage={true}>
      <span>The current page</span>
    </BreadcrumbItem>
```

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

BreadcrumbItem

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No unhandled error should occur

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.38

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Cognitive components package

## Steps to reproduce the issue

See above.

**Comment by lee-chase** [comment]
I suspect a but of ?. will help here 

![image](https://user-images.githubusercontent.com/15086604/126177557-01196cd6-d72e-48b9-9a8a-cfcfc15af3b6.png)

becoming

```
        className: cx(`${prefix}--link`, children?.props?.className),
```

**Comment by emyarod** [comment]
not sure if that will resolve the issue since the string without href still needs to be resolved as string and not as a React element, but I am taking a look at this
