### ISSUE TITLE
Slider component doesn't validate characters on Firefox.

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/carbon#9225]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When I try to use the `Slider` component on Firefox, I can't seem to validate against characters.

> Is this issue related to a specific component?

The `Slider` component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like the `Slider` component to not let me type characters. Only numbers between specified range.

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?
<img width="390" alt="Screen Shot 2021-07-19 at 10 47 47 AM" src="https://user-images.githubusercontent.com/8481567/126179384-578afdd4-90de-4fa3-8097-367ece96799b.png">

## Steps to reproduce the issue

1. Open the [sandbox](https://codesandbox.io/s/hardcore-gauss-1nwth?file=/src/App.js) on Firefox
2. Try entering characters instead of numbers

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/hardcore-gauss-1nwth?file=/src/App.js

**Comment by tay1orjones** [comment]
Hi @dkaushik95 - this is a limitation of the browser's default behavior regarding number inputs. Here's the open [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) for it with additional context.

**Comment by dkaushik95** [comment]
Thanks, @tay1orjones! I'll pass this info on.
