### ISSUE TITLE
Datepicker 'month label' format is not changing based on locale

### ISSUE THREAD

**Issue by LangQian** [carbon-design-system/carbon#9230]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
Same with [this](https://github.com/IBM/carbon-components-angular/issues/1853) Angular issue, but happens to React.

For Japanese, it should show "YYYY MM", but it actually shows the following:
![Screen Shot 2021-07-20 at 1 35 25 PM](https://user-images.githubusercontent.com/16005923/126371144-28d4f476-073b-4a21-98a0-1eb4fa76fbd2.png)

For Russian, month name has incorrect word form in the calendar. 
Expected: capitalized in nominative case.
Displayed:  non-capitalized in genitive case.
Displayed month+year is taken from complete date (day+month+year) by removing day part. However this does not work for Russian since another word form for month name is used in case month+year. 
![a5dfcf08-1f30-4187-80c1-528267da558d](https://user-images.githubusercontent.com/16005923/126371484-638fd51e-8a50-4763-933e-6e7a7d287ef0.png)
<img width="576" alt="60da4346-f3cb-4bf2-bf66-28601b5cb73a" src="https://user-images.githubusercontent.com/16005923/126371495-f9433da6-9097-4c6a-8ec5-58ae87c6d453.png">

**Comment by tw15egan** [comment]
We are utilizing `flatpickr` under the hood and it seems like some of these issues will need to be patched into [flatpickr](https://github.com/flatpickr/flatpickr) directly. Once the changes are made there, we can update our versions.  

Another note to add, please make sure you are passing in the `locale` and `dateFormat` props into `DatePicker` like so https://codesandbox.io/s/reverent-river-ki1s7?file=/src/index.js. I'm not sure if just changing the language settings in Firefox is enough

**Comment by LangQian** [comment]
We did specify the `locale` and `dateFormat` props, but they didn't affect the date format in DatePicker.

**Comment by tw15egan** [comment]
Then the issues will most likely need to be resolved upstream in the flatpickr repo

**Comment by joshblack** [comment]
Just wanted to check in here, was it the case that this was a flatpickr issue or is this someone on the Carbon side that we need to address? 👀

**Comment by jnm2377** [comment]
I agree with TJ that this is an upstream issue. For our `DatePicker`, all we really do with those props is create a calendar using flatpickr: https://github.com/carbon-design-system/carbon/blob/5b4efa9271a89519afd10f70aa2a2ace26516d85/packages/react/src/components/DatePicker/DatePicker.js#L339-L346

**Comment by jnm2377** [comment]
Closing this issue based on the comments above. This needs to be resolved [upstream](https://github.com/flatpickr/flatpickr) first and then we can include the fixes here.

**Comment by tay1orjones** [comment]
This is something we should take into consideration if/when the strategy for DatePicker is revisited https://github.com/carbon-design-system/carbon/issues/11967

**Comment by tay1orjones** [comment]
@LangQian did this work in a previous version? Or was this a new defect after updating to a new version of Carbon?

There may not be an action we can take here to resolve the issue if it is due to a flatpickr bug. It might be worth reporting this issue on their repository to see.
