### ISSUE TITLE
Add ReadOnly functionality to DatePicker component 

### ISSUE THREAD

**Issue by mkgallagher** [carbon-design-system/carbon#9256]
Add readOnly modifier for DatePicker component that would remove the ability to edit/change the date 

Once a user is done updating the field, and saves/confirms the change they shouldn't be able to change the date again. Thee user should only be able to review the dates if they choose to.

Currently I am implementing this by setting/checking a flag and returning a DatePicker when I want the user to be in edit mode, and returning a readOnly TextInput when I want the user to be in view mode.

**Comment by jnm2377** [comment]
Hey @mkgallagher 👋🏽 we have a workstream for read only inputs and will be working on adding this: https://github.com/carbon-design-system/carbon/issues/3018

**Comment by sstrubberg** [comment]
This is being tracked in https://github.com/carbon-design-system/carbon/issues/12241.
