### ISSUE TITLE
Document ModalWrapper in storybook

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#9258]
It's more an accessibility issue for a developer, not for an enduser.

I wanted to implement a [Modal](https://www.carbondesignsystem.com/components/modal/usage/), but the live demo shows a code snippet for `ModalWrapper` that renders a generic button first.
I was confused because by clicking on the [Storybook for react](https://react.carbondesignsystem.com/?path=/story/components-modal--default), there were only examples for `Modal` instead of `ModalWrapper`.

I suggest to replace the `ModalWrapper` snippet with a `Modal` snippet. You may add a story in [Storybook for react](https://react.carbondesignsystem.com/?path=/story/components-modal--default) for `ModalWrapper`.
Additionally, [Storybook for react](https://react.carbondesignsystem.com/?path=/story/components-modal--default) ist just so slow and overloaded, it would be more confortable to have a simple modal snippet in [Modal usage](https://www.carbondesignsystem.com/components/modal/usage) (and in consequence in [Modal code](https://www.carbondesignsystem.com/components/modal/code)).

**Comment by FabianPiconeDev** [comment]
The automatic `a11y` label was not intended.

**Comment by tay1orjones** [comment]
Thanks for pointing this out @FabianPiconeDev, this is a good point that we should update documentation to demo and describe ModalWrapper's functionality and intent in the storybook.

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/blob/f2f9e8d5b8ad178db1ee38930b83c426c6a05e8a/packages/react/src/components/ModalWrapper/ModalWrapper.js#L21

We've also added the 'with state manager' storybook example to the Modal storybook section to showcase how to wrap Modal with your own state manager.

I think this resolves what you were originally asking for here, so I'm going to close. Let me know if not!
