### ISSUE TITLE
Vertical Progress Indicator: missing spacing when flex wraps on narrow widths

### ISSUE THREAD

**Issue by zachhardesty7** [carbon-design-system/carbon#9261]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

when using the `ProgressIndicator` component with the `vertical` prop set to `true`, e.g. `<ProgressIndicator vertical />`, narrow container width causes an the SVG and text in each step to wrap. this is due to the `flex-wrap` CSS property. since the text of the step has no margin/padding, it sits directly against the vertical line. presumably, there should be some spacing. this definitely occurs in the newest Chrome Dev version but I haven't tested others yet. other browsers likely have the same issue.

## Steps to reproduce the issue

while the below reproduction steps are somewhat contrived, this can happen whenever the container is too small. so when `ProgressIndicator` is in a row, this can occur at much larger screen sizes. for example, in [@carbon/ibm-security](https://ibm-security.carbondesignsystem.com/?path=/story/patterns-wizard--default), our `Wizard` will cause overflow overlapping. in a specific example of ISV, we're seeing the flow-wrap at 707px.

1. open [Carbon React storybook to `ProgressIndicator`](https://react.carbondesignsystem.com/?path=/story/components-progressindicator--default)
2. open bottom drawer, select `Knobs` tab, and check the `vertical` prop
3. resize the visible area to less than 314px (using dev tools and making them really big or the device screen size simulator)
4. observe the SVGs and text splitting to separate lines and the lack of spacing on the left seen in the screenshot

## Additional information

- Carbon Storybook ![vertical progress indicator narrow](https://user-images.githubusercontent.com/20326398/126821963-a89c8376-2f90-4d35-8801-affbaced6f52.png)
- IBM Security `Wizard` 
![IBM Security `Wizard`](https://user-images.githubusercontent.com/20326398/126822026-4d7b2516-ebdb-4412-8f73-36e8bbac4156.png)
- ISV `Tearsheet` 
![ISV `Tearsheet`](https://user-images.githubusercontent.com/20326398/126821679-546d019a-d673-4fa8-bb0d-afa2e203043e.png)

**Comment by tay1orjones** [comment]
@zachhardesty7 thanks for opening this. We can take a look at improving this component's wrapping behavior down to smaller widths.
