### ISSUE TITLE
DataTable: Adding class to <TableHeader> assigns it to child element.

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#929]
## Detailed description

> Is this issue related to a specific component? 

`DataTable`

> What did you expect to happen? What happened instead? What would you like to see changed?

When adding a class to TableHeader, I expected it to add the class to `<th>`, not the child element.

## Additional information

![screen shot 2018-06-25 at 10 31 34 am](https://user-images.githubusercontent.com/7707326/41856745-d7281372-7863-11e8-90b8-2910cf558868.png)

<img width="545" alt="screen shot 2018-06-25 at 10 38 49 am" src="https://user-images.githubusercontent.com/7707326/41856921-3d8fba66-7864-11e8-9e73-7b65a2512e72.png">

<img width="379" alt="screen shot 2018-06-25 at 10 39 42 am" src="https://user-images.githubusercontent.com/7707326/41856925-40656fc4-7864-11e8-90db-739d3d84ddc5.png">

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components-react #1026](https://github.com/carbon-design-system/carbon-components-react/issues/1026) via [**ZenHub**](https://www.zenhub.com/)
