### ISSUE TITLE
bx--cloud-header has an inexplicable 2px horizontal padding

### ISSUE THREAD

**Issue by dglozic** [carbon-design-system/carbon#930]
The class `bx--cloud-header` has the following rule:

```
padding: 0 .125rem;
```

It messes up with the header content because:

1. Left padding pushes the content to the right by 2px
1. Right padding does not allow profile dropdown to be flush with the right window edge

**Comment by asudoh** [comment]
Issue moved to [carbon-design-system/carbon-addons-cloud #76](https://github.com/carbon-design-system/carbon-addons-cloud/issues/76) via [**ZenHub**](https://www.zenhub.com/)
