### ISSUE TITLE
Vertical alignment of sortable columns vs. non-sortable columns in XL tables

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#9311]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

With row-size set to XL, the vertical alignment of sortable columns vs. unsortable columns is slightly off.  Notice below how "Protocol" is slightly lower than "Name".

<img width="338" alt="Screen Shot 2021-07-26 at 12 25 55" src="https://user-images.githubusercontent.com/69599/126929210-74ac46d9-ce0c-467a-8ab6-cd7ccf164cd7.png">

(It is pretty subtle though, only a few pixels.)

This is on Carbon 10.37, tested on the latest versions of Chrome and Firefox on MacOS.

## Steps to reproduce the issue

See https://codesandbox.io/s/happy-minsky-n5i5s?file=/index.html.

**Comment by sstrubberg** [comment]
@wkeese I went and added the `bx--table-sort` classname to the div on that column and it straightened things right up.

![column](https://user-images.githubusercontent.com/15822070/128056342-e8d00d37-b574-405b-bbe7-6fffd6dabc5d.gif)

**Comment by wkeese** [comment]
@sstrubberg - Are you saying I should set `bx--table-sort` on unsortable columns too?   That seems counterintuitive at the least.

**Comment by sstrubberg** [comment]
@wkeese That's totally fair. I was just offering up a simple solution. Ideally, we could get a community contribution to update the `bx--table-header-label` with the proper style.
