### ISSUE TITLE
unstable_Pagination does not fire onChange for next and previous buttons

### ISSUE THREAD

**Issue by tusharcoepit** [carbon-design-system/carbon#9313]
Pagination component has a performance issue when data is huge.

#162

As an alternative we are trying to use unstable_Pagination, but it does not trigger onChange on click of next and previous buttons.

Any other alternatives to handle the performance issue with Pagination is also welcome.

We are on "@carbon/ibm-security": "1.41.0",

ibm-security issue reference -> https://github.com/carbon-design-system/ibm-security/issues/1051

**Comment by tay1orjones** [comment]
Thanks for reporting this @tusharcoepit, could you [create a reproduction codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) so this can be looked at more closely?

**Comment by tusharcoepit** [comment]
@tay1orjones Issue can be seen from Actions tab on https://react.carbondesignsystem.com/?path=/story/experimental-unstable-pagination--with-a-page-selector where event is triggered only on page change on not on next / previous. 
Let me know if sandbox is still needed.
