### ISSUE TITLE
Previous tab re-rendering on click using carbon-design-system

### ISSUE THREAD

**Issue by sakshigoyal007** [carbon-design-system/carbon#9335]
I am developing a react application using carbon-components. I am facing issue with tab component. I have two tabs, Tab A and Tab B, declared in a parent component,(Component C), and both of the tabs are defined in separate components with some functionalities. 
My active Tab is Tab B and I want to reload data of Tab A when I click on Tab A in ui. But it is not re-rendering the data on click. 
This is the sample code for the reference:
`<Tabs type="container">
<Tab id='tab-1' index={0} label="tab A"><ComponentA/></Tab>
<Tab id='tab-2' index={1} label="tab B"><ComponentB/></Tab>
 </Tabs>
`

Can anybody help me here?

**Comment by jnm2377** [comment]
Hi @sakshigoyal007 could you recreate your issue in a codesandbox so we can better help? https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox
