### ISSUE TITLE
NumberInput on blur is not getting triggered when focus is lost from step buttons

### ISSUE THREAD

**Issue by hrhrprasath** [carbon-design-system/carbon#9336]
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
> Describe in detail the issue you're having.

In the `NumberInput` component, On Blur event is not getting triggered whenever the focus is lost from step buttons it is getting triggered only when the focus is lost from the text field.

> Is this issue related to a specific component?

yes  `NumberInput`  https://react.carbondesignsystem.com/?path=/story/components-numberinput--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I was expecting the onBlur event should be triggered whenever the component lost its focus. Currently onBlur event is getting triggered only when the focus is lost from the text input field in the component its not getting triggered when focus is lost from step buttons.

> What browser are you working in?

Chrome 92

> What version of the Carbon Design System are you using?

10.39.0

## Steps to reproduce the issue
1. Open sandbox https://codesandbox.io/s/onblur-number-input-1iz79?file=/src/index.js:381-392
2. Change the value via text input.
3. Click on the area below with text check here !!!
4. Notice the `Value updated on blur  ` is updated.
5. Change the value via + / - button.
6. Click on the area below with text check here !!!
7. Notice the `Value updated on blur  ` is not getting updated

## Additional information
We use the onBlur event to store the user input number via API calls. Since the onBlur event is not getting triggered for step buttons we have to use the onChange event which results in multiple API call impacting heavily on performance.

**Comment by tay1orjones** [comment]
Hi @hrhrprasath, `onBlur` isn't part of the component API. It's being spread onto the input through `...other`

https://github.com/carbon-design-system/carbon/blob/71bc970364cab28379b7cdaee81902b764d94aa5/packages/react/src/components/NumberInput/NumberInput.js#L468-L477

`onChange` is designed to be the method by which changes to the input can be captured and acted upon, but there are some options available that you might try:

- Utilize `onClick` in tandem with `onBlur` to know when an API call should be made. `onClick` is only called when the increment/decrement buttons are interacted upon.
- Consider modifying your `onChange` handler to be aware of the previous input state and only make API calls when the value has changed or other logic.
- Debounce or throttle the `onChange` to reduce the amount of calls.
