### ISSUE TITLE
Slider component usability - support "stops" in addition to "step"

### ISSUE THREAD

**Issue by obai-1** [carbon-design-system/carbon#9338]
### Summary

In practice, a Slider that moves from 0 to 100 will not have same "step" value.
Here is an example:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/81330212/127215257-c03dd92b-c4c0-449e-944a-0c1cb0424d25.png">

### Justification

It is common for user to move from 1GB RAM to 2GB RAM
But it is not common for a user to move from 64 to 65 GB

So, having a single "step" value is not ideal.
It will be great if the Slider component can take an array of "stops" as well.
Then we can define a more natural increments for the Slider.

For example, I would define the "stops" for the above scenario as
```
stops = [1,2,4,8,12,16,24,32,64,96,112]
```

I cannot do that using the current Slider component. 

### Desired UX and success metrics

Pls see above.

**Comment by jnm2377** [comment]
Hey @obai-1 👋🏽 thanks for opening this issue. The UX of a slider is meant to be evenly distributed values. As a user, sliding to different values having the input jump away from the mouse or moving the mouse manually could result in a really awkward interaction. If the exact value is important then we suggest using a different control such as a dropdown.
