### ISSUE TITLE
Tabs provide API/callback to check if want to switch to new Tab

### ISSUE THREAD

**Issue by gjunming** [carbon-design-system/carbon#9342]
### Summary

Tabs now switch to new Tab when click the new Tab. but It is expected for Tabs to provide API/callback to check if want to switch to new Tab

### Justification

for multi-tab editing,  we want that before user go to new tab  they get to know they have unsaved changes.

**Comment by jnm2377** [comment]
@gjunming would the `onClick` handler not serve your needs for this? https://react.carbondesignsystem.com/?path=/docs/components-tabs--default#component-api

**Comment by joshblack** [comment]
Hi there! Going to close this out as it's been inactive for a couple of weeks 👀
