### ISSUE TITLE
Fix and refactor documentation irregularities

### ISSUE THREAD

**Issue by adamalston** [carbon-design-system/carbon#9347]
## Fix and refactor documentation irregularities

There are irregularities in the docs for various components. For example, in the template code for [Modal](https://react.carbondesignsystem.com/?path=/docs/components-modal--default) and [ComposedModal](https://react.carbondesignsystem.com/?path=/docs/components-composedmodal--default), `<Buttton>` elements are used instead of `<Button>`.

Although the example above highlighted one component there are other instances of the same issue.

Fixing these issues may create a better experience for users when interacting with documentation or the design system as a whole.

### Additional information

From the docs:
```js
<ComposedModal>
  ...
  <ModalFooter>
    <Button
      kind="secondary"
      onClick={() => { (Run some action...) setOpen(false); }}>
      Another button
    </Buttton>
    <Button
      kind="secondary"
      onClick={() => { (Run some action...) setOpen(false); }}>
      Secondary button
    </Buttton>
    <Button
      kind="primary"
      onClick={() => { (Run some action...) setOpen(false); }}>
      Priamry button
    </Buttton>
  </ModalFooter>
</ComposedModal>
```

**Comment by tw15egan** [comment]
Thanks for bringing this to our attention, @adamalston. For future reference, if you see any issues with the documentation, we link directly to the source code at the bottom of each `.mdx` file so anyone can easily update the documentation.

<img width="818" alt="Screen Shot 2021-07-28 at 10 58 04 AM" src="https://user-images.githubusercontent.com/11928039/127345283-176ba74b-8a0c-4330-8415-8ac73c7f348a.png">

**Comment by adamalston** [comment]
I was originally going to do that for the couple of cases that I could identify. When I started finding more inconsistencies (like in the JSDoc annotations), I thought it would be better to just download the repo and fix as many as I could identify in a single PR. Thanks
