### ISSUE TITLE
Static Files Theme Override

### ISSUE THREAD

**Issue by matt-jordan-1** [carbon-design-system/carbon#9351]
Hi,

One of the requirements our project has is to support the Carbon Components static files but with our own theming applied (colors, fonts modifications) without placing the additional dependency on SASS on the end user.  

With the help of a issues raised here, we were able to get the react & angular build working. 

This is what we have in our styles.scss file for the react/angular side of things: 
```
@import "@carbon/themes/scss/themes";
@import './typography';
@import './white.scss';

$carbon--theme: map-merge( $carbon--theme--white, $milliman--theme--white );
@include carbon--theme();

```
Ultimately, the user will import this styles.scss file and the carbon-components theme at the root of their project. 

I'm fairly new to SASS (I understand the basics concepts and how to get started) but not sure how to get started to build out the whole static file that contains the css for all the components.

Thanks in advance!

**Comment by jnm2377** [comment]
@joshblack @tw15egan could y'all help out here? I'm not sure how to build a static sass file.

**Comment by MJordanMilliman** [comment]
We ended up appending the following line to the styles.scss file and built the css file. I did compare files sizes from what we generated vs the latest uncompiled css hosted on the cdn and there's about a 100KB difference, so obviously something is missing, not sure what it might be. Is this the correct approach?

```
@import "carbon-components/scss/globals/scss/styles.scss";

```

**Comment by joshblack** [comment]
Hi there @MJordanMilliman! 👋  When you're looking at the size difference, are you comparing the minified stylesheet versus the generated CSS code that is not minified? If so, that could explain the difference. You can see this on unpkg with our `carbon-components.css` file and our `carbon-components.min.css` file, the latter of which is minified.

![image](https://user-images.githubusercontent.com/3901764/128361153-624c9afa-a6af-4f21-a753-2e0056b27b46.png)

Link: https://unpkg.com/browse/carbon-components@10.40.2/css/
