### ISSUE TITLE
What is the background color of a modal, in loading state, in light theme?

### ISSUE THREAD

**Issue by Sandrouille** [carbon-design-system/carbon#9359]
We can find examples of modals loading (task completion) in dark theme on the site (https://www.carbondesignsystem.com/patterns/dialog-pattern/#designing-with-dialogs)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/14088627/127491006-8bf21413-2df2-4cba-9af7-5be408ed3c65.png">

But what should be the background color of the modal in light theme?

**Comment by tw15egan** [comment]
cc @carbon-design-system/design
