### ISSUE TITLE
Update Carbon Tutorial following migration guidance

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9362]
After we release beta 1 on Thursday, July 29th, the plan is to follow our migration guidance and apply it to the Carbon Tutorial.

This work should be done in a `next` branch on the project located at: https://github.com/carbon-design-system/carbon-tutorial and should include:

- [ ] Updating the project to use the new `@carbon/react` package
- [ ] Updating styles to reference new paths from the `@carbon/react/scss` entrypoints
- [ ] Update import paths for JavaScript components
- [ ] Update Grid usage

Any issues that come up during the tutorial process should be documented in this issue for us to follow up on next sprint.

**Comment by tay1orjones** [comment]
@joshblack @tw15egan @sstrubberg Is this good to close? I think we got it all knocked out?
