### ISSUE TITLE
Type Token changes

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#9377]
This issue is for tracking changes that need to be made in the `@carbon/type` package

**Comment by tw15egan** [comment]
Website PR https://github.com/carbon-design-system/carbon-website/pull/2410

**Comment by janchild** [comment]
Here is the spreadsheet with type token names changes, as discussed in meeting with @tw15egan, @jeanservaas , @laurenmrice , @oliviaflory, and @janchild. 

[Typography type token list.xlsx](https://github.com/carbon-design-system/carbon/files/6908871/Typography.type.token.list.xlsx)
