### ISSUE TITLE
Tooltip component in angular doesn't have 'alignment' knob while VUE and React does.

### ISSUE THREAD

**Issue by ttliang** [carbon-design-system/carbon#9388]
Tooltip component don't have '**alignment**' knob while VUE and React does. Offset knob for tooltip in angular is not satisfied for alignment requirement.

![image](https://user-images.githubusercontent.com/12162531/127954002-f6332842-3d55-4a85-b6a1-26fd2e4f4a49.png)

**Comment by tw15egan** [comment]
Hi there @ttliang, this seems to be an issue with the Angular repo. Can you open an issue there? https://github.com/IBM/carbon-components-angular
