### ISSUE TITLE
Hovering over the selected item from a dropdown doesn't show the complete text

### ISSUE THREAD

**Issue by kaushalnavneet** [carbon-design-system/carbon#9397]
## What package(s) are you using?

- [x] `carbon-components-react`

## Description

> Is this issue related to a specific component?

`Dropdown`, `Combobox`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

It is expected to see the entire text when we hover over a selected option from the dropdown. Like it shows the full text when we hover over any option when the dropdown is open.

> What browser are you working in?

Chrome 

## Steps to reproduce the issue
For Dropdown:
1. Go to [Carbon Components React](https://react.carbondesignsystem.com/?path=/story/components-dropdown--default) portal, `Dropdown` page
2. Select the second option from the dropdown list - `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`
3. Because of its length the string is truncated and it is expected to show the entire string when we hover over it. But it is not the case in the current implementation. 

For Combobox:
1. Go to [Carbon Components React](https://react.carbondesignsystem.com/?path=/story/components-combobox--combobox) portal, `Combobox` page
2. Select the second option from the dropdown list - `An example option that is really long to show what should be done to handle long text`
3. Because of its length the string is truncated and it is expected to show the entire string when we hover over it. But it is not the case in the current implementation.

**Comment by tw15egan** [comment]
Hey there @kaushalnavneet, I'm unable to reproduce the issue. I'm able to see a browser tooltip on hover

<img width="450" alt="Screen Shot 2021-08-03 at 1 03 22 PM" src="https://user-images.githubusercontent.com/11928039/128056583-f59d408d-24e1-4487-8feb-ada91cd96acf.png">

<img width="473" alt="Screen Shot 2021-08-03 at 1 04 19 PM" src="https://user-images.githubusercontent.com/11928039/128056646-6ec2bd29-0f19-4101-b404-4a2dc27f8cc7.png">

**Comment by AlanGreene** [comment]
The issue is when one of those long values is selected and the dropdown / combobox is collapsed. There is no tooltip for the selected value.
