### ISSUE TITLE
SideNavLink element to support `<Button>`

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/carbon#9400]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Currently, the `SideNavLink` component accepts an `element` prop which is defaulted to an `a`. This is helpful when utilizing Gatsby, as you can set the element prop to `Link` and use the `to` attribute. However, in some instances, such as in [CreateTearsheet](https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-createtearsheet--with-view-all-toggle), the `SideNavLink` is used to bring you to different parts of the inner content of the modal. It would be great if you could set the element prop to a `Button` but currently all of the side nav link styles are only for `a` tags.

Clarify if you are asking for design, development, or both design and
development.

### Justification

A button here makes sense because we aren't redirecting or sending users' to another URL or location in the browser.

### "Must have" functionality

Prop for element accepts `Button` and applies all applicable styling

**Comment by jnm2377** [comment]
cc: @carbon-design-system/design is this an acceptable pattern for using `SideNavLink` or do we have other design recommendations for this UX? You can view the modal example by clicking the link above.

https://user-images.githubusercontent.com/32556167/128748033-6664b386-3de6-43fa-80d8-0ce6c1dbedda.mov
