### ISSUE TITLE
search is not coming properly in cv-datatable 

### ISSUE THREAD

**Issue by manik39654** [carbon-design-system/carbon#9412]
Search icon is not coming up properly while i deploy code to my VM.
![image](https://user-images.githubusercontent.com/86999228/128136895-8c81b804-e28b-4f8d-a0e4-76e0429cf938.png)

## What package(s) are you using?
    "@carbon/vue": "^2.37.1",
    "carbon-components": "^10.23.1",

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
 Yes. I am facing this issue in cv-datatable. Datatable earch is working fine on my local dev environment but as soon as i commit my code to VM the search icon gets distorted and i checked while inspecting the component some classes are not getting applied to search e.g bx--toolbar-search-container-active , bx--toolbar-search-container-expandable 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
 i checked on Chrome, Mozilla and IE

> What version of the Carbon Design System are you using?
   "carbon-components": "^10.23.1"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi there @manik39654! 👋  For Vue-related questions or issues, I'd make an issue over on: https://github.com/carbon-design-system/carbon-components-vue

Hope this helps!
