### ISSUE TITLE
IE11: Tabs component does not become active when clicking on it

### ISSUE THREAD

**Issue by bjakob01** [carbon-design-system/carbon#943]
## Detailed description

With Internet Explorer 11, the Tabs component does not show its content when clicking on it. 
We are using Angular 6 and the polyfills.ts file imports all polyfills needed by Angular.

Browser version:
Internet Explorer 11
Version: 11.0.9600.19035CO
Update Versions: 11.0.65 (KB4230450)
Product ID: 00150-20000-00003-AA459

In the IE Developer tool I cannot see any exceptions.

> What version of the Carbon Design System are you using? 
    "carbon-addons-cloud": "^2.1.0",
    "carbon-addons-cloud-vanilla": "^1.0.0",
    "carbon-components": "^9.0.14",
    "carbon-icons": "^7.0.7",

## Steps to reproduce the issue
By the way, the Tabs component does also not work for CodePen and IE11

1. open IE11
2. navigate to https://codepen.io/team/carbon/full/QOprdK/
3. click on any Tabs component 

### Expected result
clicked tab becomes active and its content will be shown

### Actual result
nothing happens ... nothing will be shown

**Comment by asudoh** [comment]
Hi @bjakob01 thank you for reporting - It appears that your CodePen missing `Object.assign()` polyfill (and possibly other polyfills)? Would you fix it...? Thanks!

**Comment by bjakob01** [comment]
I installed and imported the mdn-polyfills. Now, the Tabs are working fine, except:
- the clicked tab does not get underlined

@asudoh do you know which polyfill I need to get this problem fixed?

**Comment by asudoh** [comment]
The list of polyfills needed for `carbon-components` is listed here: http://www.carbondesignsystem.com/getting-started/developers/vanilla#polyfills-for-older-browsers - Hope this helps.

**Comment by bjakob01** [comment]
@asudoh thank you for your help. Now I have all needed polyfills installed and imported into my app. All is working fine now, also with IE11.
Except one problem: when I click on a tab, then the contents of this tab will be shown but the tab label will not become underlined. I will investigate ... but this issue can be closed.

**Comment by sgurin** [comment]
Hi @bjakob01 Can you please give me a hand with polyfill issue.

We imported https://github.com/carbon-design-system/carbon/tree/master/packages/components and cannot find polyfills folder there. How you have imported polyfills into your project.

Thanks a lot
