### ISSUE TITLE
JAWS can't read the content of tooltips

### ISSUE THREAD

**Issue by kaushalnavneet** [carbon-design-system/carbon#9430]
## Brief description
JAWS or any other screen reader tool is not able to read the content of tooltips. Figured out in [an issue](https://github.ibm.com/org-ids/roadmap/issues/17098) opened during an AVT Testing of an IBM Cloud - Pipeline page. 

## Environment

> Browser
Chrome

> Automated testing tool and ruleset

> Assistive technology used to verify
JAWS, Chrome Screen-reader

## Detailed description

> What version of the Carbon Design System are you using?
Latest

> What React component?
Tooltip

> Please create a reduced test case in CodeSandbox
Reusing a similar sample: https://codesandbox.io/s/bold-goodall-073cx?file=/src/index.js

**Comment by kaushalnavneet** [comment]
Similar issue: https://github.com/carbon-design-system/carbon/issues/7425

**Comment by xiepingp** [comment]
Below products have the same issue:
https://github.ibm.com/alchemy-containers/schematics-ui/issues/1970
https://github.ibm.com/coligo/ui/issues/2522
https://github.ibm.com/alchemy-containers/satellite-ui/issues/1443
https://github.ibm.com/alchemy-containers/armada-ui/issues/6973

Please note, the issue occurs when the tooltip content only includes plain text. If the tooltip content includes button or link, Jaws is reading the content well by using arrow keys:
![carbon 9430 asl 3 1443 - tooltip with button is read](https://user-images.githubusercontent.com/63960906/128838471-822a6c94-83c4-4b01-bc68-0c7c7a6a2546.png)

**Comment by mashenka123** [comment]
@andreancardona @jnm2377 Thank you for triage, could you please help confirm the fix plan? This is blocking our signoff for Satellite, Schematics, Code Engine and kubernetes. Thank you！

**Comment by kaushalnavneet** [comment]
Do we have any updates on the issue? Thanks

**Comment by reggeenr** [comment]
Hi, do we have any updates on this issue?

hi @andreancardona @jnm2377 do you see any chance to prioritize this issue?

**Comment by xiepingp** [comment]
Thanks for the fixing!! Jaws now reads the tooltip content correctly!
![Screen Shot 2021-12-10 at 09 34 29](https://user-images.githubusercontent.com/63960906/145502791-0c54056a-0cea-4317-a2ab-43f74723884f.png)
