### ISSUE TITLE
[Release Partner] e-ther-inc

### ISSUE THREAD

**Issue by 0-vortex** [carbon-design-system/carbon#9437]
**What is your team's name?**

e-ther-inc

**Why would you like to join the Release Partner Program?**

We are interested in open source IBM design guidelines and very thrilled about this major release. 
Would like to give version 11 a try for our internal documentation and public website :D

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

[@0-vortex](https://github.com/0-vortex) or [@tipuban](https://github.com/tipuban)

**Comment by joshblack** [comment]
Hi there! We created a space for release partners over on [Discord](https://discord.gg/5tDVQH98). If you let me know your Discord username over in that space, I can add the "Release Partner" role to your account and you'll see some of the channels that we have set up for this process.

Let me know if you have any questions! We're so happy that you reached out about this and excited to work with you 😄

**Comment by 0-vortex** [comment]
> Hi there! We created a space for release partners over on [Discord](https://discord.gg/5tDVQH98). If you let me know your Discord username over in that space, I can add the "Release Partner" role to your account and you'll see some of the channels that we have set up for this process.
> 
> Let me know if you have any questions! We're so happy that you reached out about this and excited to work with you 😄

Thank you so much, I am `vortex#2285` on discord!
