### ISSUE TITLE
HCDS

### ISSUE THREAD

**Issue by mikhak** [carbon-design-system/carbon#9438]
**What is your team's name?**

HCDS

**Why would you like to join the Release Partner Program?**

I already use the Carbon Design System in my courses at Harvard and wish to plan for my future courses more effectively. 

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes.

**Who should we reach out to for more info?**

Bakhtiar Mikhak
bam961@g.harvard.edu

**Comment by joshblack** [comment]
Hi there! We created a space for release partners over on [Discord](https://discord.gg/5tDVQH98). If you let me know your Discord username over in that space, I can add the "Release Partner" role to your account and you'll see some of the channels that we have set up for this process.

Let me know if you have any questions! We're so happy that you reached out about this and excited to work with you 😄

**Comment by mikhak** [comment]
Thank you, Josh. My handle on discord is bakhtiar#0817.

**Comment by mikhak** [comment]
I very much looking forward to working with you as well. Thank you again.

**Comment by joshblack** [comment]
Awesome! Added 😄

**Comment by mikhak** [comment]
Thank you!
