### ISSUE TITLE
TextInput focus not following cursor on Firefox

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#9441]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

on Firefox, when the width of the TextInput is 320px, the cursor moves beyond the focus area when user types 43rd and 46th character. but comes back on 47th and onward. 

It happens when string hits the edge no matter the width.

> Is this issue related to a specific component?

`TextInput`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Focus should away follow cursor 

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

carbon-components-react@v7.41.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson knowledge catalog

## Steps to reproduce the issue

use the codesandbox and type 33rd character

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/sweet-sunset-i150l?file=/src/index.js

**Comment by joshblack** [comment]
https://user-images.githubusercontent.com/3901764/128777471-9c2a09f7-c3fb-4f34-b2e8-a1352cb47e42.mov

Can confirm the issue (thanks so much for the codesandbox!)

This is wild, any idea why it might be happening? 🤔

**Comment by nelsonchen90** [comment]
I couldn't figure out what's causing this on FF. there is no issue with native `input` field on FF.

**Comment by aledavila** [comment]
@joshblack its happening becuase of the padding on the left that we added. For some reason it ignores the end there and only fixes itself when the charactes touch the edge of the input "behind" the padding if that makes sense. But I can't figure out a fix for it. Its not ignoring any charactes they are all there its just that delay per se.
