### ISSUE TITLE
Pass ref to a TableExpandRow component on React

### ISSUE THREAD

**Issue by martinscooper** [carbon-design-system/carbon#9443]
### Summary

Please describe your request in one or two sentences.
I am using `carbon-components-react`. I want to be able to pass a ref to the `TableExpandRow` component so I can use the `scrollIntoView` function on a particular row. 

Clarify if you are asking for design, development, or both design and
development.
development

### Justification

In my case, I have a line chart and a table bellow. Each x-label corresponds to a particular row. I want to let the user press a label and to be redirected to the corresponding table row. For that, I should be able to obtain a reference to the `tr` tag inside `TableExpandRow`.

### "Must have" functionality

As `TableExpandRow` is implemented a functional component, a ref can't be pass as a prop unless React.forwardRed is used. 

### Available extra resources

This issue is similar to #8744. 
Also, note that what is suggested [here](https://github.ibm.com/ASUDOH/faqs/tree/3348a35/carbon-components-react/grab-dom-without-ref) can't be done. Wrapping `TableExpandRow` inside a `div` would break a several carbon css selectors.

**Comment by martinscooper** [comment]
@sstrubberg I could work on this, the issue doesn't seem difficult to solve.

**Comment by sstrubberg** [comment]
hey @martinscooper, it's all you, my friend! Let us know if you need any support :D
