### ISSUE TITLE
Code snippet scroll hover blocks text

### ISSUE THREAD

**Issue by jenschlot** [carbon-design-system/carbon#946]
## Detailed description

Chrome: 
![image](https://user-images.githubusercontent.com/11622088/42104316-b3113de8-7b91-11e8-9caa-0f9d1984055f.png)

FF:
![image](https://user-images.githubusercontent.com/11622088/42104505-6c76a930-7b92-11e8-9939-97276c752a4c.png)

Safari:
![image](https://user-images.githubusercontent.com/11622088/42104534-871c0e2e-7b92-11e8-94e7-26bd55cfdfd5.png)

> Is this issue related to a specific component? Code snippets

> What did you expect to happen? What happened instead? What would you like to see changed? It should surround the whole code snippet box.

> What browser are you working in? 

> What version of the Carbon Design System are you using? 9.0.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Docs

## Steps to reproduce the issue

1. Go to https://console.stage1.bluemix.net/docs
2. Click on Tools tab in the homepage
3. Try to scroll one of the code blocks

**Comment by tw15egan** [comment]
Doesn't seem to be coming from our styles, as I am unable to replicate this with the examples on our website: http://www.carbondesignsystem.com/components/code-snippet/code

**Comment by jenschlot** [comment]
it's there...you're just using white, instead of blue:
![image](https://user-images.githubusercontent.com/11622088/42106598-348efe02-7b9a-11e8-8db6-dbeb604f612c.png)

**Comment by tw15egan** [comment]
What is the behavior you are expecting? I guess I am confused on the issue, as I don't see any content being blocked on the page you linked to, or in the examples posted above.

What would you like to see "surround the whole code snippet box."? Is this referring to the focus outline or the scroll bar?

**Comment by tw15egan** [comment]
Any updates on this? Wondering what the encountered vs desired behavior is

**Comment by jenschlot** [comment]
This is the example of what we are encountering in React/Carbon component: http://react.carbondesignsystem.com/?selectedKind=CodeSnippet&selectedStory=single%20line&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

![image 23](https://user-images.githubusercontent.com/11622088/42478529-a61e4f2a-839a-11e8-976e-215ed90f85a4.png)

The desired is that the focus outline would go around the outside of the code snippet box. Now it is on the scroll bar and it blocks text as you scroll.

**Comment by tw15egan** [comment]
The focus outline isn't actually blocking the text, it's just sliding underneath the `8px` of padding on the left side of the component, following the spec: 
![image](https://user-images.githubusercontent.com/11928039/42654702-2cf42d62-85df-11e8-9506-1ed8ef548f78.png)

If you hover over the component in the storybook, and scroll without clicking the snippet you will see that it cuts off at the same position
