### ISSUE TITLE
Update components to place `className`  on outer node

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9465]
We currently inconsistently place `className` for our components. In v11, we will have each component place the `className` prop on the **outermost** node. This issue is for updating components in a non-breaking way using the `useFeatureFlag` hook to place the `className` prop on the outermost node.

```jsx
function Demo() {
  const enabled = useFeatureFlag('enable-v11-release');

  // Figure out common pattern for placing `className` on outermost node
}
```

This issue is for filling out the list below of components that currently place `className` on the outermost node and for addressing this using the pattern described above.

A list of components that place `className` on the outermost node:

- [ ] TODO

**Comment by tw15egan** [comment]
Components that do not place `className` on the outermost node:

- [ ]
