### ISSUE TITLE
Do not provide accessible labels by default, for example: "Provide icon description" 

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9466]
There are several situations where we use `defaultProps` to provide a placeholder accessible label. In v11, these props should be treated as required with no default props.

```jsx
function TestComponent() {
  // ...
}

// From
TestComponent.propTypes = {
  iconDescription: PropTypes.string,
};

TestComponent.defaultProps = {
  iconDescription: 'Provide a description',
};

// To
TestComponent.propTypes = {
  iconDescription: PropTypes.string.isRequired,
};

TestComponent.defaultProps = {
};
```

This may be tricky to get right with feature flags and most likely will require using the top-level feature flag package instead of being able to use a hook 😞 

Below is a list of components that currently do this:

- [ ] FileUploader
- [ ] SelectItemGroup
- [ ] NumberInput
- [ ] Switch
- [ ] OverflowMenuItem

Note: there may have been some that have been missed, this was a quick search!

**Comment by tw15egan** [comment]
@joshblack do you have examples of how to use this with class-based components? Might this be easier to just switch to `.isRequired` on the `next` branch as we get close to release?

**Comment by abbeyhrt** [comment]
@joshblack Is it fair to assume that we only want to update the non-obvious ones? Like a 'Close' icon with a default iconDescription of 'close' or say CopyButton having a "Copy to clipboard" for the copy icon would be sensible defaults
