### ISSUE TITLE
[Tooltip] remains open when focus moves to other elements on the page

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon#9469]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If you have multiple tooltips on a page and you tab through them all tooltips will stay open after they've lost focus. Often, they overlap blocking one another.

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the tooltip to close when it no longer has focus.
> What browser are you working in?

Chrome 92.0.4515.131 

> What version of the Carbon Design System are you using?

10.41.0/7.41.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

[Minimal repo sandbox](https://codesandbox.io/s/agitated-northcutt-ypjhj)

## Additional information

<img width="1200" alt="123816423-4d2ec600-d8c5-11eb-969c-82ef563a2b19" src="https://user-images.githubusercontent.com/609466/129072110-3a387b61-1b84-404e-b3cd-5338ed757b5a.png">

- Notes

Also tracking in the iot repo here: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2437

**Comment by andreancardona** [comment]
@kevinsperrine Hello! 

Thank you for opening up this issue. I can't seem to reproduce the issue. Let me know if I'm not following your directions properly. Thanks! Happy to keep looking into it.


https://user-images.githubusercontent.com/32720851/130510152-b9118a6a-ba7c-44e2-9538-bbd1a59c3a13.mov

**Comment by kevinsperrine** [comment]
@andreancardona You're clicking the tooltip in your video. This issue is about tab-navigating to them for a11y purposes. If you click once in the example window and then press the `tab` button once to change focus to the first tooltip and then hit `tab` again to change focus to the second tooltip both will stay open.
![tooltip-focus](https://user-images.githubusercontent.com/609466/130510933-dda4ef77-b5fd-4a6f-8bd9-23e306b0716b.gif)

**Comment by andreancardona** [comment]
@kevinsperrine so sorry I misunderstood the `tabbing` I'll look into it :)

**Comment by kevinsperrine** [comment]
Thanks, @andreancardona!
