### ISSUE TITLE
[Button] Icon should top align when button label wrap to 2 lines

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#9478]
### Button icon should top align to 1st line of button label when the label wraps

Currently in some field height has this behavior, but not all. Especially missing from default field height (48px). This behavior (when label wrap, top align icon) should apply to all heights of the button.

Storybook: [button playground ](https://react.carbondesignsystem.com/?path=/story/components-button--playground)

![image](https://user-images.githubusercontent.com/15144993/129377296-48a04eae-3803-462b-bcab-bad2fd152e97.png)

Expecting icon to align to first line of text:

![image](https://user-images.githubusercontent.com/15144993/129377377-d09a1012-2416-4226-99db-f69acf25027f.png)

**Comment by tw15egan** [comment]
This seems to be happening because it is absolutely positioned. Setting a `top: 1rem` position fixes the issue when wrapping, but then throws off alignment in all the size variants as well as the single line variant. Will need to be tested at all sizes / lines of wrapping

**Comment by pratikkarad** [comment]
Hi @shixiedesign, @tw15egan, I am new to open source. I want to claim the issue. How do I claim it?

**Comment by pratikkarad** [comment]
I followed the 5 steps mentioned in the [contributing guidelines](https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md#start-contributing) and still not able to start a development server locally. I have also attached snapshots of my console logs. On running yarn storybook, it is infinitely stuck on the console. Any suggestions?

1. yarn install -
![yarn install](https://user-images.githubusercontent.com/32093370/159627226-bb0d8aea-db02-4d94-83fa-50b000121cb2.png)
2. yarn build -
![yarn build](https://user-images.githubusercontent.com/32093370/159627219-cf91df6b-b7f1-44c1-bbe2-3e54b991f2f3.png)
3. change directory to packages/react & yarn storybook -
![yarn storybook](https://user-images.githubusercontent.com/32093370/159627228-91447549-e9db-488b-a008-7bd336df5c61.png)

**Comment by pratikkarad** [comment]
Hi @joshblack, I had fixed this bug by checking out from the main branch. Since commits on Mar 25, 2022, I think carbon's folder structure got changed and also the UI of the storybook for different components. I tried to dig a little on this _packages/react/src/components/Button/Button-story.js_ file, but I guess this component is not being served on the button storybook. Could you please point me to the file location which is being used to show the Button storybook component on the storybook? Thanks!

**Comment by alisonjoseph** [comment]
Fixed https://github.com/carbon-design-system/carbon/pull/14193
