### ISSUE TITLE
[feat] pass a ref to the checkbox label 

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/carbon#9498]
Hello,
I need to show a tooltip when hover the label of a checkbox. The ref is targeting the input that is hidden and I would like to target the label to get the event.

Or maybe there is another way to trigger the tooltip?

use case example :

``` 
const [hoverref, isHover] = useHover()
  return (
    <div>
      <Tooltip open={isHover} showIcon={false}>
           <p>Timestamp cannot be applied to a process filter</p>
      </Tooltip>

      <Checkbox
              id="specific-timestamp"
              ref={hoverref}
              labelText="Select case starting from a specific timestamp"
              onChange={handleShowTimeOptions}
         />
   </div>
)
```
thanks for any help

**Comment by tw15egan** [comment]
@ninjasun would passing in a `TooltipDefinition` as the `labelText` fit your needs? You can override the dotted underline styles via css if you would like. Here is an example:

https://codesandbox.io/s/hopeful-haibt-fi0qs?file=/src/index.js

**Comment by ninjasun** [comment]
Hi @tw15egan with ToolDefinition I can make it work. I had to work around it coz passing the tooltip as props of the checkbox will lose the disabled style.
I did somethings like..
```
if (!showTooltip) {
    return (
      <Checkbox
        id={`${id}-checkbox`}
        labelText={labelText}
        disabled={disabled}
        checked={checked}
        onChange={handleChange}
      />
    );
  }
  return (
    <TooltipDefinition
      tooltipText={tooltipText}
      className="additional-options__tooltip"
      id={id}
    >
      <Checkbox
        id={`${id}-checkbox`}
        labelText={labelText}
        disabled={disabled}
        checked={checked}
      />
    </TooltipDefinition>
  );```

You can close. 
Thanks bro

**Comment by tw15egan** [comment]
Happy to help and glad we were able to figure out a solution for you 🙏🏻
