### ISSUE TITLE
Example of using Carbon Components in a Web app.

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#95]
It would be great to have an example demonstrating the use of Carbon Components
to build a web application using a standard server-side framework like ExpressJS or (even better) Kitura.

**Comment by tw15egan** [comment]
Hey @gmosx, this should cover what you're looking for: https://github.com/carbon-design-system/carbon-boilerplate

**Comment by gmosx** [comment]
Hmm, I was looking for a more advanced example.

E.g. how to use the tabs programmatically, how to have some kind of data-structure for the items that's rendered as tabs (with the correct selected tab)

Or how to use the 'module' markup to 'frame' arbitrary content, etc...

Still this boilerplate is kinda useful.
