### ISSUE TITLE
Select Component - Unable to use defaultValue in Select for mapped SelectItems

### ISSUE THREAD

**Issue by dhebert-dev** [carbon-design-system/carbon#9507]
## What package(s) are you using?

- [ x] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I am unable to use defaultValue in Select when my SelectItems are mapped. Each SelectItem receives values for the text and value property. One set of text and value contains "Process" as both the text and value but when I feed "Process" to defaultValue in Select the item does not change to Process. This works for hardcoded SelectItems but not for mapped items.
> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The Select component should render "Process" as the defaulted selected value even if the SelectItems are mapped.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
		"carbon-components": "^10.11.2",
		"carbon-components-react": "^7.17.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
SAP Evolution

## Steps to reproduce the issue

1. Implement <Select> and <SelectItem>
2. Map over data and set text and value properties for <SelectItem>
3. Feed one of the values from the map to defaultValue in <Select>. Since "Process" is an existing 
4. Observe behavior

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

`            <div>
                { 
                <Select defaultValue="Process">
                
                <SelectItem text={"Test1"} value={"Test1"} />
                <SelectItem text={"Test2"} value={"Test2"} />
                {this.props.projectItems.map((item) => {
                    console.log(item.id)
                    console.log(item.name)
                    return <SelectItem text={item.name} value={item.name} /> // one of the values in projectItems is "Process"
                })}
                </Select>
                }
            </div>`

``

- Notes

**Comment by dhebert-dev** [comment]
After digging around talking to a colleague we have discovered that using value instead of defaultValue works. The documentation in Carbon Storybook only lists defaultValue as a usable property for that purpose. If value is the correct property to use then the documentation should be updated.

**Comment by dbrugger** [comment]
i was also just running into this. @tay1orjones I feel this should be reopened.

**Comment by dbrugger** [comment]
FWIW I got it working by setting `selected` on the `SelectItem`, and this is probably the right way.
But I had to manually add `selected` as an optional property to the `SelectItemProps` TypeScript interface, not sure why it's not getting inherited from `HTMLAttributes<HTMLOptionElement>` that it extends.
