### ISSUE TITLE
Loading component: Animation abruptly stops when overlay is used

### ISSUE THREAD

**Issue by bananatranada** [carbon-design-system/carbon#951]
## Detailed description

Loading component: Animation abruptly stops when overlay is used.

## Steps to reproduce the issue

Comment out the overlay and run that, too.
https://codepen.io/BANANATRANADA/pen/LrqreZ

## Additional information

First, I'm not even sure if I'm using the loader properly. When should I use release, end or set/toggle? Are loaders typically done via adding and removing elements (as done in the project) instead of display none? Answers to these would be very much appreciated!

However, regardless of use, there isn't a way to gracefully stop a loader when an overlay is present. I'd be happy to make a PR once those questions are clarified!

**Comment by asudoh** [comment]
@carbon-design-system/design I thought “overlay spinner” does not have stopping animation (otherwise end-user has longer period of not being able to interact with the application - poorer end-user performance). Is it correct? Thanks!

**Comment by bananatranada** [comment]
Oh, it looks like it's been changed with this [PR](https://github.com/carbon-design-system/carbon-components/pull/145). I was wondering why there was a `background-color` transition on the overlay.

Wouldn't the original problem be fixed by calling `end()`? 

Anyway, this was brought to my attention because the overlay felt too blinky. I personally feel that the animation and background transition are warranted to give it a "professional" feel. But if the design calls for no animation for overlays, then I'll stop right here!

**Comment by asudoh** [comment]
Good question - I may probably had some oversight wrt `end()`, but the concern wrt user not being able to interact with the application during the animation period still applies.

**Comment by asudoh** [comment]
Another thing I can put here is that I personally no longer recommend overlay spinner. We introduced [skeleton states](http://www.carbondesignsystem.com/utilities/loading#skeleton-states) in our `9.0` release and it will be a good fit for many cases where overlay spinner was used.

**Comment by aagonzales** [comment]
Yes, @asudoh is correct. Whole page loads should be avoided. We have guidelines up on how to properly use different loading states: http://www.carbondesignsystem.com/utilities/loading

I'm not as familiar with the spinner. Do you have a more in-context example you can show illustrating the problem?

**Comment by bananatranada** [comment]
http://www.carbondesignsystem.com/utilities/loading#large-loader

I would like the overlay to blend in with the page once everything's finished loading instead of the blinking effect caused when the overlay disappears suddenly. However, I'll stop pressing the matter as the skeleton is the preferred way of showing a loading state. There's also the issue with how the loading animation "jumps" to the beginning of the stopping frame, and sometimes the jitter is fairly obvious. I'll just use the skeleton states :)
