### ISSUE TITLE
Product splash screen template

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#9520]
## Tasks
- Research what other companies do for splash screens (like adobe)
- Explore and create some potential product splash screens. 

**Outcome:**
- Need to be able to recommend a splash screen design to the email thread.

**Future:** 
- Eventually, we will like to develop this into a full pattern page on Carbon or Brand center site. But written guidance is not needed for this activity. 

## Existing IBM splash screen
**Includes:**
- IBM logo
- Product name 
- Version
- Legal content
- Supporting technology logo

![image](https://user-images.githubusercontent.com/11670886/130498904-ae4fd726-0e2e-4607-9e32-2ebabb2100f4.png)

## Brand inspiration:
Might be useful to consult with the Brand team (Conrad, Pete) once we have some option (playback in the Big Carbon meeting).
- https://www.ibm.com/brand/digital-banners

**Comment by thyhmdo** [comment]
@aagonzales do we know what size this could be?

**Comment by aagonzales** [comment]
I have no clue, we might be able to control/regulate that.

**Comment by kingtraceyj** [comment]
Legal update from Andrea Barbuto about general requirements:

> There are standard requirements, but each product will have some variations in the notices section of the splash screens based on what is in the product.  In this case the product uses Java (which is owned by Oracle) so we have legal requirements to provide notice of TM ownership under our agreement with Oracle.  Also Product names may have different trademark status.  Usually the product attorney responsible for the product reviews and manages the TM and notices section for the products they support.
> 
> I would suggest that anything you design be subject to final review and sign off by the product attorney to ensure proper legal notice and TM requirements.

**Comment by kingtraceyj** [comment]
from May about the the DB2 product:

> The Dev team says there should be the legal content in it.  I am trying to figure out who we can ask,
> The 3rd party logo, I got a response from the dev team, let me find that info
>  
>  Logos
>  1)Java is the only supporting technology, which needs to be added
>  2)The dev team also wants the OMEGAMON brand too.  I need to find that
> 
> I will need to do some work to find the answers.  So its fine to wait till next week.
> Thanks for addressing this.  I will connect with you next week
> 
> The Dev team wants to have the logo for OMEGAMON.
> The Java logo is needed

**Comment by kingtraceyj** [comment]
IBM Z on prem guidelines: http://ausgsa.ibm.com/projects/t/tivoli_visual_design/public/2014/ui_guidelines/branding.html#about

**Comment by kingtraceyj** [comment]
so there is definitely a template floating around out there but i have yet to find who owns it...

![image (62)](https://user-images.githubusercontent.com/20582179/132708564-ba16e0da-c1e3-4b6b-ab70-2aeb5b8852d8.png)
![M2](https://user-images.githubusercontent.com/20582179/132708574-0b1cb3e4-f231-4bfd-9c81-2ddacad06a11.png)
![image](https://user-images.githubusercontent.com/20582179/132708639-90e0e633-3961-4c05-b789-0a5dc2fd780c.png)

**Comment by kingtraceyj** [comment]
old templates: http://tlbgsa.ibm.com/projects/u/uibranding/ibm/splash.shtml

**Comment by kingtraceyj** [comment]
From May on legal content for DB2:

> There was still some outstandlng questions about the copyright for the splash screen.  I finally got answers from the lawyer.
> **It must be included". I think we should just use the same TEXT and just change the COPYRIGHT YEAR to 2022
> 
> DETAILS ABOUT COPYRIGHT
> Here is the Legal for Business Clients guidance page - https://w3.ibm.com/w3publisher/legal-for-business/copyright-notice-registration-archival/copyright-notice-process 
>  
> Notice on title screens for software:
> 
>     The Copyright Notice must appear on the first or most prominent display screen when a user first uses or accesses the program. Preferably the notice should appear on the same screen that the title appears on.
>     The notice should last long enough for a person to actually see it and understand it.
> 
> Usually, the splash screen is considered the first or most prominent display.
>  
> The additional information that certain Db2 components are not owned by IBM and licensed from third parties such as Oracle is also important to retain.
>  
> Additionally, the same copyright guidance can be seen in the latest Copyright Registration and Notices guidance, attached below. On page 6, it discusses the same information as above regarding displaying copyright notices on the user interface/display screen.
> <see: attachment>
> 
>  
> Regards,
> May Chu


[IBM Copyright Notices and Registration Policy - 12 August 2021 1.pdf](https://github.com/carbon-design-system/carbon/files/7203659/IBM.Copyright.Notices.and.Registration.Policy.-.12.August.2021.1.pdf)

**Comment by kingtraceyj** [comment]
Final specs for splash screens: https://ibm.box.com/s/95kmj4zzcywr34il4e9fw4k8r43ojvks

**Comment by KTKate** [comment]
I don't necessarily want to open an issue around this because I have a feeling there's not much more info out there but wondering if either of you @kingtraceyj or @aagonzales have any info around guidelines for the imagery in splash screens. We need to update a handful of Omegamon branded splash screens and want to make sure there isn't some kind of Carbon best practice for the imagery part.

**Comment by kingtraceyj** [comment]
@KTKate you can use these guidelines for illustration: https://www.ibm.com/design/language/illustration/overview/
