### ISSUE TITLE
TooltipDefinition and TooltipIcon are cut by modal overlay

### ISSUE THREAD

**Issue by alissa9090** [carbon-design-system/carbon#9524]
## What package(s) are you using?

- [x] `carbon-components`^1041.0
- [x] `carbon-components-react`^7.41.0

## Detailed description

TooltipDefinition and TooltipIcon are cut by modal overlay so that parts that are outside of modal are not shown.

## Steps to reproduce the issue

1. Create Modal
2. Render TooltipDefinition on the top of the modal
3. hover TooltipDefinition

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/kind-wright-q5xok?file=/src/index.js

## Additional information

![Screenshot 2021-08-24 at 08 49 01](https://user-images.githubusercontent.com/21106246/130569911-5b1a88cc-46e7-40f3-8df8-9cae80459c32.png)

**Comment by wkeese** [comment]
In my experience, this happens whenever you have a `position:relative` between the `position:absolute` node (i.e. the tooltip) and the scrollable node.  And in this test case, there are many `position:relative` nodes, starting with the (i) icon itself.

I'm having a similar clipping problem because the `bx--modal-content` node is `position:relative`.  In other words, a regression from 9dad020f739b0ab2531eeca9cf6c2a2d134dc1a7.

**Comment by alissa9090** [comment]
> In my experience, this happens whenever you have a `position:relative` between the `position:absolute` node (i.e. the tooltip) and the scrollable node. And in this test case, there are many `position:relative` nodes, starting with the (i) icon itself.
> 
> I'm having a similar clipping problem because the `bx--modal-content` node is `position:relative`. In other words, a regression from [9dad020](https://github.com/carbon-design-system/carbon/commit/9dad020f739b0ab2531eeca9cf6c2a2d134dc1a7).

**Comment by alissa9090** [comment]
> In my experience, this happens whenever you have a `position:relative` between the `position:absolute` node (i.e. the tooltip) and the scrollable node. And in this test case, there are many `position:relative` nodes, starting with the (i) icon itself.
> 
> I'm having a similar clipping problem because the `bx--modal-content` node is `position:relative`. In other words, a regression from [9dad020](https://github.com/carbon-design-system/carbon/commit/9dad020f739b0ab2531eeca9cf6c2a2d134dc1a7).

**Comment by alissa9090** [comment]
> In my experience, this happens whenever you have a `position:relative` between the `position:absolute` node (i.e. the tooltip) and the scrollable node. And in this test case, there are many `position:relative` nodes, starting with the (i) icon itself.
> 
> I'm having a similar clipping problem because the `bx--modal-content` node is `position:relative`. In other words, a regression from [9dad020](https://github.com/carbon-design-system/carbon/commit/9dad020f739b0ab2531eeca9cf6c2a2d134dc1a7).

I've tried, but setting `position:static` to `bx--modal-content` doesn't solve the problem.

`.bx--modal-container, bx--modal-content { overflow: visible; }` helps, but it breaks the layout if you have a content inside the modal that needs to be scrolled (like in my codesandbox example).

**Comment by wkeese** [comment]
IIRC in your example there are a bunch of `position:relative` nodes.

**Comment by tay1orjones** [comment]
Hey, just want to provide an update here. In v11, [DefinitionTooltip](https://react.carbondesignsystem.com/?path=/story/components-definitiontooltip--default) ships with many more options for alignment that would fix this issue.

Additionally, the Popover component that powers the DefinitionTooltip has an experimental `autoAlign` prop that aims to detect the container boundaries and reflow the tooltip to be totally visible.

**Comment by wkeese** [comment]
Hmm, I wouldn't say "fix", seting the alignment to "bottom" is more of a workaround that will look weird to the user.  The fix is to stop clipping the tooltip on the border of the modal's body.
