### ISSUE TITLE
Button `hasIconOnly` tooltip delaying hovering on preceding buttons in vertical toolbars

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/carbon#9538]
#### Affected packages

- [x] `carbon-components`
- [x] `carbon-components-react`

#### Description

In vertical toolbars, the tooltip is currently delaying hovering on preceding buttons when hovering from bottom to top:

|     |     |
| --- | --- |
| <img width="71" alt="1-2 toolbar" src="https://user-images.githubusercontent.com/3846874/130800089-57dae458-7df4-4eb9-9abd-f3b70285c4cb.png"> |  <img width="89" alt="2-2 toolbar" src="https://user-images.githubusercontent.com/3846874/130800120-2ffa5aa1-4eb7-4055-90dc-bdd5d4ae4dff.png">   |

#### Reproduction

https://codesandbox.io/s/wizardly-meninsky-co49r — hover over buttons from bottom to top and observe the tooltip delaying interaction with the next button.

**Comment by SimonFinney** [comment]
> Wondering if adding `tooltipPosition="right"` would be a viable solution? https://codesandbox.io/s/heuristic-https-vk8yk?file=/src/index.js

Apologies for the delay in responding — this is definitely a viable workaround for some scenarios. The design guidance I received for this use case was that the tooltip position should be on top. Is the recommendation that a `left` or `right` position should be used in all 'vertical' scenarios?

**Comment by laurenmrice** [comment]
@SimonFinney @tw15egan Yes, the tooltip direction should show up as `right` or `left` for vertical toolbar instances depending on which side of the page the toolbar is on. This way the tooltip will never cover up other options to select from in the vertical toolbar.

**Comment by jnm2377** [comment]
Based on the design guidance above, I'll go ahead and close this for now. We can re-open if necessary in the future. :)
