### ISSUE TITLE
[Toggle]: Variant with Label on the Left Side

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/carbon#9547]
### Summary

Design & Development:
I suggest adding a variant of the Toggle component that puts the State Label (On/Off) on the left side of the Toggle.

### Justification

This is especially helpful for designs that feature a Toggle on the right-side of the layout. The label can stay on the left of the Toggle component, and therefore changes in the text length will keep the Toggle consistently aligned on the right-side of the layout.

### Available extra resources

I can offer time and assistance as a front-end developer as needed.

I've hardcoded the position of the label in an existing Toggle in my project - however I think this can be done more elegantly from the Carbon side by offering a variant that displays the label before the Toggle component.

https://user-images.githubusercontent.com/3118961/131012922-260bd9fe-07a1-4212-b810-c963c8a54611.mov

**Comment by jnm2377** [comment]
Hi @lily-peng yes we are adding more support for RTL in v11. We actually have some experimental components for this, you can view the stories here: https://react.carbondesignsystem.com/?path=/story/experimental-unstable-text--layout-and-textv
