### ISSUE TITLE
Accessibility on Input field (design)

### ISSUE THREAD

**Issue by yumeforever** [carbon-design-system/carbon#956]
# Error and Disable states

## Detailed description

We were having a discussion here about the Error and Disable states for Input does not look accessible having only Color (in the case of error) or Transparency (in case of Disable).
Maybe would be better to add an Icon and .... line for disable?

If the person has any problems with vision, such as color blind or bad sight might get tricky on both states.

I made this exploration comparing both:
![image](https://user-images.githubusercontent.com/3612533/42231973-591fac52-7eed-11e8-978b-e21c2be87f67.png)

**Comment by aagonzales** [comment]
Thanks for proposing a solution and not just point out a problem 🙏 

Color isn't the only indicator. Errors are required to have a message below the field. The only messaging that ever goes below the field is error content.

That being said I think adding an icon inline is fine and does add visual weight/attention to error-ed element.

**Disabled states** are inaccessible by a keyboard and there for are seen a null items in terms of accessibility.

**Comment by yumeforever** [comment]
Oh nice!
One of the visual designers at Hybrid Cloud pointed out this to me yesterday, so we were talking about how would be usable for them. They are trying to incorporate Carbon on their UI as we speak. And this was a problem for them. 

About the disable state, the dashed line for the 50% opacity is for example used by Google apparently, to point disable fields not just with making them transparent. 

;)

**Comment by tw15egan** [comment]
Icon will also be added when input is updated in Carbon X, so going to close this now
