### ISSUE TITLE
Tooltip issue when aligned to right of screen

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#9561]
Noticed while reviewing https://github.com/carbon-design-system/carbon/pull/9556

<img width="300" alt="Screen Shot 2021-08-30 at 1 11 10 PM" src="https://user-images.githubusercontent.com/11928039/131338177-45261369-2e72-4a36-8891-9420b81b085c.png"> <img width="300" alt="Screen Shot 2021-08-30 at 1 11 33 PM" src="https://user-images.githubusercontent.com/11928039/131338182-e672967e-dd51-4cf6-914f-633c5e95f11c.png">

Additional info provided by @TuxedoFish confirming the issue was an existing bug

https://github.com/carbon-design-system/carbon/pull/9556#issuecomment-908284591

Possibly due to the storybook being inside of a flex container causing positioning issues when right-aligned

**Comment by TuxedoFish** [comment]
Update on this issue: it seems like if you do one update and then set a timeout and repeat the update for the _updateMenuSize function a second later it will adjust. Obviously not a fix, but 

https://user-images.githubusercontent.com/3999881/132138074-49fabdb9-0afb-4f52-9a36-d1219e254f6a.mov

Then a proposed solution is to add a callback into setState such that it refirest _updateMenuSize as an "adjustment" and instantly updates this. Thoughts on this?

<img width="1460" alt="Screenshot 2021-09-05 at 20 08 13" src="https://user-images.githubusercontent.com/3999881/132138614-3815e201-8fd1-4dff-b8ee-7aab6362bf6f.png">
