### ISSUE TITLE
UI shell scrollbar positioning

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#9584]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [x] `carbon-components-svelte`

## Detailed description

The header of the UI shell is fixed, so it does not scroll, but the scrollbar is not shown below the header but to its side.

Example from documentation page:

![image](https://user-images.githubusercontent.com/834235/131719267-43ec7b97-dfc3-436b-96b2-782588c01bb2.png)

This gets especially weird when building a Windows desktop version of an application (e.g. using Electron), where the header serves as the title bar. There should be nothing to the right of the close icon:

![image](https://user-images.githubusercontent.com/834235/131719164-a184ee27-6254-4fdb-9959-592e0315910b.png)

This is how it should be laid out as I see it:

![image](https://user-images.githubusercontent.com/834235/131722565-e5424b99-fdc6-4cb5-8dc7-60dccd0bd858.png)

(Maybe that kind of use of the header is unintended, but putting another bar on top of the already thick header would be a giant waste of space.)

Behavior is the same in Chrome and Electron's Chromium (looking at the CSS presumably everywhere else, too).
Carbon version is 10.40.0 (indirectly via `carbon-components-svelte`).

Only noticed this issue while working on some internal tooling, so this not exactly critical. I can override a few styles as a workaround.

## Steps to reproduce the issue

- Add a UI shell header
- Add enough content to make document scroll

[Example based on React Sandbox](https://codesandbox.io/s/scrollbar-next-to-fixed-header-gwzxj)
As noted, [the documentation page](https://carbondesignsystem.com/) itself also exhibits this behavior.

## Notes/Workaround

This might not be easy to apply universally depending on how and where elements are wrapped. Given this very flat hierarchy and these CSS overrides the scrollbar will be below:

```pug
html
  head
  body
    header.bx--header
    main.bx--content
```

```css
html,
body {
  height: 100%;
}
body {
  display: flex;
  flex-direction: column;
}

.bx--header {
  position: initial;
}
.bx--header ~ .bx--content {
  margin-top: 0;
}
.bx--content {
  overflow: auto;
}
```

[[Sandbox]](https://codesandbox.io/s/scrollbar-below-header-3y07p)

**Comment by joshblack** [comment]
I think this is more of a documentation/variant use case than a bug in the existing code. Definitely agreed that there are situations where one would like the header to span across the full page and have only the content be overflown 👍
