### ISSUE TITLE
Add the option of a tooltip to a tag

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#9587]
Raised based on 
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1223

### Summary

A user of @carbon/ibm-cloud-cognitive has requested the ability to supply an abbreviated tag and an associated tooltip. Add the option for a tooltip to the tag component.

NOTE: While it is possible to wrap a tag in an icon tooltip this interferes with styling in a list of tags. Specifically `.bx--tag:not(:first-child)`.

Development only

### Justification

See linked issue requesting the feature

### Desired UX and success metrics

This enhancement will be successful when it is possible to pass in a tooltipText attribute as part of each tag and have it display in the tooltip independently of the tag text

### Available extra resources

What resources do you have to assist this effort?

Happy to contribute if approved.

**Comment by lee-chase** [comment]
@tay1orjones I have asked the raiser of the original issue for designs, they are as yet to respond.

**Comment by joshblack** [comment]
Going to close this out due to inactivity. Feel free to reach out on Slack @lee-chase and I can re-open!
