### ISSUE TITLE
How to change the color of an icon?

### ISSUE THREAD

**Issue by SIRISHA-SHARON** [carbon-design-system/carbon#9588]
I'm using  Link16,

import { Link16 } from "@carbon/icons-react";

<Link16 className={`${prefix}--snippet__icon`} color="blue" />

The above isn't working.

**Comment by tw15egan** [comment]
You can set it via the css `fill property`

```css
.my-svg svg {
   fill: red;
}
```

https://codesandbox.io/s/compassionate-tree-0s519?file=/src/index.js
