### ISSUE TITLE
Code Snippet Show More button doesn't seem to be working

### ISSUE THREAD

**Issue by dbrandl28** [carbon-design-system/carbon#9592]
## What package(s) are you using?

"carbon-components": "^10.41.0",
"carbon-components-angular": "^4.54.1",

> Describe in detail the issue you're having.
I have quite a bit of output in a Code snippet box.  It is expanded on initial display.  There is a Show More button at the bottom, but clicking it just changes it to the Show Less button.  Clicking the Show Less button just collapses the last line.

> Is this issue related to a specific component?
This was working before we upgraded to Carbon V10.  Not sure when it broke.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the output to initially be collapsed and then expanded after clicking the Show More button.

> What browser are you working in?
Happens with both Firefox and Chrome.

> What version of the Carbon Design System are you using?  V10

> Please create a reduced test case in CodeSandbox
>
Your sandbox appears to have the same problem.
https://angular.carbondesignsystem.com/?path=/story/components-code-snippet--multi

## Additional information
![ShowMore](https://user-images.githubusercontent.com/23317227/131927637-b650dc06-7de3-4ff7-be0e-0dc606e54871.PNG)
![ShowLess](https://user-images.githubusercontent.com/23317227/131927644-c37c71c3-84a2-4d05-bd3f-e506b98a140b.PNG)

**Comment by tw15egan** [comment]
Hey there @dbrandl28, since this seems to be an issue with the Angular components, can you open the issue over on their repo? Here is the [link](https://github.com/IBM/carbon-components-angular), thanks!
