### ISSUE TITLE
[Release Partner] <Your Team Name>

### ISSUE THREAD

**Issue by mattbueh** [carbon-design-system/carbon#9594]
**What is your team's name?**

Matthieu

**Why would you like to join the Release Partner Program?**

My team and I have been using Carbon for the past 1 1/2 years and would like to be updated about the next releases. We are very committed to using carbon throughout all our products.

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

mabuh@synspective.com

**Comment by joshblack** [comment]
Hi there @mattbueh! 👋  Thanks so much for reaching out about this program!

We're currently using our [Discord server ](https://discord.gg/KAECRaWdzE) for release partners. Once you sign up there, let me know your username and I can add the Release Parter role to you and get you onboarded!

Looking forward to it!
