### ISSUE TITLE
IE11 support? Overflow menu in IE11 not working

### ISSUE THREAD

**Issue by travis1111** [carbon-design-system/carbon#960]
## Detailed description

> Is this issue related to a specific component? 

Overflow menu

> What did you expect to happen? What happened instead? What would you like to see changed?

In IE11

> What browser are you working in? 

IE11

> What version of the Carbon Design System are you using? 

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

![image](https://user-images.githubusercontent.com/35569780/42343970-d6acee1a-8068-11e8-81e3-af9a39c926a9.png)

or try this 

https://codepen.io/team/carbon/pen/MOEwjp/
in 

in IE11...
you will see errors in console.

In order for me to get to the overflow menu in out application, I had to add the following to my html's header:

```sh
if (!Element.prototype.matches) 
	Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector; 

if (typeof Object.assign != 'function') {
	  (function () {
	    Object.assign = function (target) {
	      'use strict';
	      // We must check against these specific cases.
	      if (target === undefined || target === null) {

	        throw new TypeError('Cannot convert undefined or null to object');
	      }
	 
	      var output = Object(target);
	      for (var index = 1; index < arguments.length; index++) {
	        var source = arguments[index];
	        if (source !== undefined && source !== null) {
	          for (var nextKey in source) {
	            if (source.hasOwnProperty(nextKey)) {
	              output[nextKey] = source[nextKey];
	            }
	          }
	        }
	      }
	      return output;
	    };
	  })();
	}
```

**Comment by asudoh** [comment]
From the screenshot of IE developer tools, it appears that your application does not have `CustomEvent` polyfill. For the complete list of polyfills required, please refer to: http://www.carbondesignsystem.com/getting-started/developers/vanilla#polyfills-for-older-browsers. Please feel free to reopen if it doesn't resolve your issue. Thanks!
