### ISSUE TITLE
[Release Partner] 9ntonio

### ISSUE THREAD

**Issue by 9ntonio** [carbon-design-system/carbon#9602]
**What is your team's name?**

9ntonio

**Why would you like to join the Release Partner Program?**

I would love to help test v11. I work for a small startup and I'm currently assessing design systems. 

**Are you interested in participating in biweekly feedback sessions for the release?**

Yes

**Who should we reach out to for more info?**

antonio@spacebase.one

**Comment by joshblack** [comment]
Hi there @9ntonio! 👋  Thanks so much for reaching out about this program!

Unfortunately, we're currently looking for teams who are already using Carbon today to help us smooth out our migration process. I really appreciate you reaching out and showing interest in this program and I'm sorry that we couldn't accommodate you 😞

**Comment by 9ntonio** [comment]
@joshblack Thanks for the reply. I appreciate the feedback. Good luck with v11.
