### ISSUE TITLE
Decide on convention of `type`, `kind`, and `variant` for v11

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9623]
**Background**

We would like to be consistent in our terminology with how a user can configure a component to render differently in terms of appearance. In our codebase currently, we use several style of props to indicate that a component can have different visual appearances, including:

- [`type`](https://carbon-react-explorer.vercel.app/props/type)
- [`kind`](https://carbon-react-explorer.vercel.app/props/kind)

In this proposal, we would like to define what the exact term used must be for components and when to use these other prop names, if at all.

**Links & Resources**

- Design Tools
  - [Framer](https://www.framer.com/support/using-framer/variants/)
    - A Variant is any visual state specified for a component. With Variants, components can be given unique states to which they can animate when an event is happening or has occurred.
- Design Systems
  - Components using `variant`
    - https://spectrum.adobe.com/page/button/
    - https://primer.style/react/Buttons

**Comment by joshblack** [comment]
- Button
  - Uses `kind` because `type` conflicts with `<button type="...">`

**Comment by joshblack** [comment]
**Figma Research**

Figma uses a term called a **Component Set** to describe a collection of components, called variants, that all share their properties. However, the variants will have different combinations of values for these properties.

A **Component Set** could be one-dimensional. For example, a `button` could have a `state` property with the values: `standard`, `hover`, `pressed`, or `disabled`.

Our **Button Component Set**, in this case, would contain the following variants:

![image](https://user-images.githubusercontent.com/3901764/132733643-23c5dd8a-9ff6-4bbc-be5f-cdb5634363b7.png)

In this case, the variants are specifically:

- Button with state: standard
- Button with state: hover
- Button with state: pressed
- Button with state: disabled

A **Component Set** could also be multi-dimensional. For example, a `button` could have several `type`s such as `primary` and `secondary`. In this case, our **Button Component Set** would look like:

![image](https://user-images.githubusercontent.com/3901764/132733964-12307bdf-3d63-4cdd-8efd-b7670d850648.png)

In this case, the variants are:

- Button, type: primary, state: standard
- Button, type: primary, state: hover
- Button, type: primary, state: pressed
- Button, type: primary, state: disabled
- Button, type: secondary, state: standard
- Button, type: secondary, state: hover
- Button, type: secondary, state: pressed
- Button, type: secondary, state: disabled

**Definitions**

**Design Systems**

**Links & Resources**

- https://www.youtube.com/watch?v=y29Xwt9dET0
- https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants

**Comment by joshblack** [comment]
**Figma Research (Migration)**

An interesting aspect of: https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants#Manage_variants is that the default name of the first property when creating variants will be: variant.

![image](https://user-images.githubusercontent.com/3901764/132735666-eb5171d4-c8e8-4b6f-be04-90aca2d5d8f2.png)

![image](https://user-images.githubusercontent.com/3901764/132735768-2145788e-2b62-4d88-863b-cff7db1547ae.png)


They also show renaming this automatic field to `type` later on:

![image](https://user-images.githubusercontent.com/3901764/132736201-a4a8e875-f763-4bf4-b035-319888229749.png)

**Comment by vpicone** [comment]
Great stuff! Thanks for putting in the time researching. Do we have any idea how many components might need to be renamed ala Notification? I'm wary of using a totally new component for a thing that could be a prop, but agree it makes sense in some cases.

**Comment by aagonzales** [comment]
I still worry about the term `type` in the larger context. It can mean different things depending on your context through the system:
- type = component "variant" 
- type = typography, text, type styles

Type (variant) and type (text) can be seen a lot on the same page through out component docs.

**Comment by joshblack** [comment]
@vpicone thankfully no name changes! And for ambiguity, I think we'll need to have a prop like `nativeType` or `htmlType` that will point to the underlying HTML Element type.

@aagonzales totally agreed

**Comment by aagonzales** [comment]
I another factor that we should consider is how these terms are being used in the ecosystem. This is what teams are using in their docs (not sure if its the same in their code).
- Jan said .com uses "variant" 
- Looks like [Cloud PAL](https://pages.github.ibm.com/ibmcloud/pal/components/card/usage#variations) uses "variations"
- AI Apps actually uses both "type" and "variant"
- [CC&C](https://pages.github.ibm.com/cdai-design/pal/components/page-header/usage#types) use "type"

**Comment by aagonzales** [comment]
I think we're missing a term somewhere. 

1. There are two [insert term] of notification components. `Inline` and `Toast`. This have major functional, behavioral, and style differences. 
![image](https://user-images.githubusercontent.com/11670886/133817716-c5149fed-38bb-4b40-b07c-5c2c12bfcd76.png)

2. Within inline notification there are four [insert terms] of inline notifications, `error`, `warning`, `info` and `success`. These most commonly only have usage differences. (This is the term we're missing)
![image](https://user-images.githubusercontent.com/11670886/133818055-3042a2d7-328c-47e3-a181-7ad18a485b7f.png)

3. Within an _success-inline-notification_ there are two [style modifiers], `high contrast` and `low contrast`. These are only aesthetic style differences.
![image](https://user-images.githubusercontent.com/11670886/133818638-3e344964-7896-48b8-8d4a-a19b3343efdb.png)

4. Within an inline notification you can add a [modifier] such as an action to enhance minor functionality. 
![image](https://user-images.githubusercontent.com/11670886/133818775-079c0a55-db3a-4699-ad49-bce4b4e53fad.png)


-------------------------

If 1. `Type` then is 2. `Kind`? Or is 1. Variant and 2. is type?

**Comment by joshblack** [comment]
@aagonzales here's one attempt at thinking about it:

> There are two types of notification components: Inline and Toast. These have major functional, behavioral, and style differences but still fall under the umbrella of notifications

> An inline notification component has a status/state/type property that can be one of error, warning, info, and success.

> The success-inline-notification by default uses a low contrast style. It has a high contrast property to create high contrast variants.

> Within an inline notification you can add a [modifier] such as an action to enhance minor functionality.

I think when we have items inside of a component it could fall under the umbrella of component composition versus types/variants of a component. The guidance then becomes around the types of content a component allows versus it being a variant distinction.
