### ISSUE TITLE
[Bug]:  [Edge] 'Show password' icon appear twice in Edge browser 

### ISSUE THREAD

**Issue by lukewang2018** [carbon-design-system/carbon#9627]
### Package

carbon-components-react

### Browser

Edge

### Package version

Version 93.0.961.38 (Official build) (x86_64)

### Description

Hi,

This is related to the component PasswordInput. We can see two 'show password' icon in Edge browser. The first is related to 'Reveal Password' function only in Edge. The second icon is from PasswordInput. Please help fix it. thanks.

<img width="240" alt="Screen Shot 2021-09-09 at 8 03 20 PM" src="https://user-images.githubusercontent.com/40848250/132686390-f17167dc-f303-472b-8f2e-6472c1433a1f.png">

<img width="246" alt="Screen Shot 2021-09-09 at 8 03 30 PM" src="https://user-images.githubusercontent.com/40848250/132686382-de08802b-f601-45b9-9d16-797933a38a49.png">

carbon/packages/react/src/components/TextInput/PasswordInput.js
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/TextInput/PasswordInput.js

### CodeSandbox example

https://codesandbox.io/s/gallant-varahamihira-mbrkb

### Steps to reproduce

Just type new password in the input area. It will show two 'Show password' icons as below.
<img width="240" alt="Screen Shot 2021-09-09 at 8 03 20 PM" src="https://user-images.githubusercontent.com/40848250/132686390-f17167dc-f303-472b-8f2e-6472c1433a1f.png">

<img width="246" alt="Screen Shot 2021-09-09 at 8 03 30 PM" src="https://user-images.githubusercontent.com/40848250/132686382-de08802b-f601-45b9-9d16-797933a38a49.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by visionmonster** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal

::-ms-reveal {
  display: none;
}

**Comment by lukewang2018** [comment]
thanks @visionmonster it works!

```
input::-ms-reveal{
  display:none;
}
```
