### ISSUE TITLE
[Bug]: autofill breaks dark themes

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#9645]
### Package

carbon-components

### Browser

Chrome

### Package version

10.37

### Description

Chrome has this presumptuous `!important` CSS that overrides both the color and background-color of autofilled form fields:

<img width="702" alt="Screen Shot 2021-09-11 at 8 42 35" src="https://user-images.githubusercontent.com/69599/132928393-6af8c3a8-5107-4433-90ed-5bb7e24bd39a.png">

(Other browsers may have something similar.)

Naturally, that `!important` browser CSS "breaks" Carbon's `g90` and `g100` themes for example:

<img width="1329" alt="Screen Shot 2021-09-11 at 8 51 07" src="https://user-images.githubusercontent.com/69599/132928493-9afc395b-820b-42dd-b23e-740b1a98379f.png">

You might think the solution is to set `autocomplete="off"` or similar on the `<form>`, but that doesn't work reliably.  Chrome and other browsers decided to give users what they want (i.e. autofill) rather than doing what most HTML pages say to do (i.e. no autofill).

To make matters worse there seems to be a Chrome bug that sometimes sets the auto-fill pseduo-class even when there's no prefilled value, in which case hovering and then unhovering the field clears it.

But basically, the issue is that Chrome's built-in CSS is overriding Carbon's.

### CodeSandbox example

https://codesandbox.io/s/carbon-autofill-7fkq6?file=/public/index.html

### Steps to reproduce

In our app, the autofill is happening just by loading the page.  I couldn't get a good example of that.  But I did create https://codesandbox.io/s/carbon-autofill-7fkq6?file=/public/index.html.  If you fill in your first name from Chrome's autofill dropdown, then Chrome will fill in all the other fields for you.   And all the fields will all have a light blue background

If you switch the theme to `g90` or `g100` (not sure how to do this in CodeSandbox, maybe you can show me), then the light blue background will still be there.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Thanks for reporting this @wkeese! I wonder if we can offer a custom style based on: https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ for autofill colors.

Let me tap design to see what they think here 👀

**Comment by wkeese** [comment]
Yah, I think so, except that you probably need to [add `!important` to override Chrome's default style](https://stackoverflow.com/a/61088671/112002).   I know you're never supposed to use `!important` but it seems we have no choice in this case.  Note that [MDN says that webkit cannot be overridden](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill), but I hope that's wrong.

You would also want a rule for [plain `:autofill`](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill), so that the behavior is consistent across browsers.

Design needs to decide what style you want.   I can see the argument for using a unique style for auto-filled fields to notify users that the value was auto-filled.   But probably something dark-ish for dark themes, like webkit's dark-mode `rgba(70, 90, 126, 0.4)`.
