### ISSUE TITLE
[Feature Request]: Button splitted with a dropdown?

### ISSUE THREAD

**Issue by frederikhors** [carbon-design-system/carbon#9647]
### Summary

Is there something like the below ["splitted" button with a dropdown](https://getbootstrap.com/docs/5.1/components/dropdowns/#split-button)?

![image](https://user-images.githubusercontent.com/41120635/132978970-203ad564-9301-4f8b-ad32-1a992bc6089f.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Nothing yet, but we have a proposal up over in https://github.com/carbon-design-system/carbon/issues/3371 and tracked in https://github.com/carbon-design-system/carbon/issues/5303

No ETA for you as it is not actively being worked on. Going to close as a duplicate.
