### ISSUE TITLE
[Feature Request]: Babel plugin to transform imports to subpackage imports

### ISSUE THREAD

**Issue by brandones** [carbon-design-system/carbon#9651]
### Summary

Asking for development of a babel plugin which would transform standard Carbon imports into subpackage imports.

### Justification

This would provide the best possible DX, since developers wouldn't have to worry about identifying the right way to do a subpackage import, which presently is not obvious.

This would also solve https://github.com/carbon-design-system/carbon/issues/9540, since Typescript would work on the main namespace import.

### Required functionality

The plugin should transform standard imports like 

```typescript
import { Button } from 'carbon-components-react';
```

into subpackage imports like

```typescript
import Button from 'carbon-components-react/lib/components/Button';
```

or

```typescript
import Button from 'carbon-components-react/es/components/Button';
```

Where a configuration option specifies whether to use `lib` or `es` (or any other option).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by brandones** [comment]
Oh apparently this used to exist: https://github.com/carbon-design-system/carbon/pull/3869 . My organization needs this. We're running Webpack 5 and Babel 7.

**Comment by joshblack** [comment]
Hi there @brandones! 👋  Teams should not require needing to do sub-package imports as the project is set up for tree-shaking out of the box. Are you / your team currently experience challenges with a large bundle? If so, could you share more details about what is being included?

**Comment by brandones** [comment]
Oh, this is interesting. I don't know at what point we decided that carbon-components-react wasn't tree shaking, but it seems not to be true, at least any more. I just did a bundle analysis and found no difference between the normal import and subpackage import.

I do have an unrelated question, though. What's going on with "bucket," here? This is [a sample project](https://github.com/openmrs/openmrs-esm-template-app) that has `carbon-icons` installed but doesn't actually use it:

![Screenshot from 2021-09-13 16-41-27](https://user-images.githubusercontent.com/1031876/133176121-0bd1464e-d78b-41ad-85a7-fe84bcac4e17.png)

And here's a breakdown from [a real project](https://github.com/openmrs/openmrs-esm-patient-chart/tree/master/packages/esm-patient-allergies-app) we have, which actually does use icons:

![Screenshot from 2021-09-13 17-48-15](https://user-images.githubusercontent.com/1031876/133176188-778c601f-0dbb-4201-813e-b3414d7ad1a9.png)

Maybe there's something wrong with how we're bundling `carbon-icons`?

**Comment by joshblack** [comment]
@brandones typically when all of the icons are included, there is a CommonJS import somewhere in the code. Here is a comment where we touched on this briefly: https://github.com/carbon-design-system/carbon/issues/6602#issuecomment-729207760

Hope this helps!

**Comment by brandones** [comment]
Yes, it appears that this app has an import from `carbon-components-react/lib`. Thanks for your help!
