### ISSUE TITLE
[Feature Request]: Modify Length of a Carbon Tab via Component API

### ISSUE THREAD

**Issue by kavinaravind** [carbon-design-system/carbon#9654]
### Summary

The current available component API's in [React Carbon Tabs](https://react.carbondesignsystem.com/?path=/docs/components-tabs--default) do not support customization for the length of the tab and CSS for the button must be modified in order to increase its size.

### Justification

There are cases where longer text may be required that exceeds `3rem` and having the ability to resize accordingly rather than truncating would look cleaner for the end experience. For example, `Watson Knowledge Catalog` truncates to the following and it would be nice to have the full offering name rather than having to pass in the acronym `WKC`.

![image](https://user-images.githubusercontent.com/10949859/133252470-51fa2a80-7b48-438c-8fb4-7ac3b4832c21.png)

### Desired UX and success metrics

- [ ] Supplying longer lengths (maybe small, medium, large?) or having the ability to specify a length and having that render properly in different device sizes

### Required functionality

```html
  <Tabs>
    <Tab id="tab-1" label="Watson Knowledge Catalog" length={"5rem"}>
      <p>Offering Details</p>
    </Tab>
  </Tabs>
```

Prop can be `length` and either `s/m/l` or a defined length can be passed in

### Specific timeline issues / requests

Would be nice to have it in Q4, 2021

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by theiliad** [comment]
@kingtraceyj we're wondering if this needs any design attention?

Pls read the `Desired UX and success metrics` section of the issue

Would we want to add a size/length prop to enable token-based sizing (e.g. small, medium, large)?

@kavinaravind are you able to customize the widths by using the `style` prop using custom css?

**Comment by joshblack** [comment]
Hi there! 👋 Going to close this out due to inactivity. Feel free to comment and we can re-open!
