### ISSUE TITLE
[Feature Request]: Scheduler component

### ISSUE THREAD

**Issue by GRawhideMart** [carbon-design-system/carbon#9658]
### Summary

There are many choices when a React (or other frameworks') developer start choosing the design system; not many of those, however, feature an integrated working **scheduler**. It would be not just a development matter, but also a way to provide businesses a way to schedule their appointments and meetings without installing other third party schedulers.

### Justification

As Carbon grows and has its own unique functional looks, it lacks the possibility to effectively integrate a scheduler component. For example I would need it, but the only existing equivalent is for MaterialUI.

### Desired UX and success metrics

See Google Calendar, and also [this component for MaterialUI](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/).

A user should be able to program their appointments and visualize them in a calendarized way by day, work week, week, month or year. Also a nice possibility would be to just have a visualization of upcoming events, without any calendarization (like an agenda). All within the beautiful Carbon UX scss code.

### Required functionality

From the developer's point of view the data flow should be intuitive enough, as to grab the main data about with a predefined fields set, and then either interact with state management libraries like Redux or Zustand, or to directly perform POST requests to a database

### Specific timeline issues / requests

No specific time period, it is just a mild suggestion.

### Available extra resources

https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by shivajivarma** [comment]
Hi @tay1orjones,

We are requesting a minimal design without any editable cells or actions on the calendar, so we can implement the component ourselves matching the styles.

Thanks,
Shivaji

**Comment by shivajivarma** [comment]
Hi @tay1orjones,

We are requesting a minimal design without any editable cells or actions on the calendar, so we can implement the component ourselves matching the styles.

Yes, we know that this is complex one, but this is the most used component on web applications.

Thanks,
Shivaji

**Comment by shivajivarma** [comment]
If anyone looking for design, you can refer below implementation which i did, following similar styling of carbon design. Hope it helps.

https://goatui.com/components/calendar/#
