### ISSUE TITLE
Flip up for "Overflow menu"

### ISSUE THREAD

**Issue by Wenpei** [carbon-design-system/carbon#966]
## Detailed description

"Overflow Menu" didn't support flipped up. My popover menu icon didn't show well when put it to bottom of page. 
I search doc of carbon and find nothing to support this.

> Is this issue related to a specific component? 

"Overflow menu"

> What did you expect to happen? What happened instead? What would you like to see changed?

Support flipped up if lay bottom of page automatic or let user set a props.

> What browser are you working in? 

All

> What version of the Carbon Design System are you using? 

"carbon-components": "^9.1.6",
    "carbon-components-react": "^6.5.2",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**Comment by Wenpei** [comment]
Thank you very much.
should I create a carbon-component-react issues also?

**Comment by asudoh** [comment]
Hi @Wenpei would you want to try https://github.com/IBM/carbon-components-react/pull/1118? Thanks!

**Comment by Wenpei** [comment]
Thank you. @asudoh
