### ISSUE TITLE
Broken Links on Components Overview page of https://www.carbondesignsystem.com/

### ISSUE THREAD

**Issue by CodeSharp5** [carbon-design-system/carbon#9660]
Image links on https://www.carbondesignsystem.com/components/overview/ tiles are all broken, as viewed from MS Edge browser.
Screenshot:
![image](https://user-images.githubusercontent.com/90721833/133318732-4bf76f34-242a-4cda-bafb-ac1df5f3f33b.png)

Screenshot with Developer Tools, showing broken link associated with component Breadcrumb:
![image](https://user-images.githubusercontent.com/90721833/133319708-ccfe55a4-3d84-45c8-849e-d397cdc71340.png)

Mouseover of `[object Module]` in `<img src="[object Module]" alt="Breadcrumb" ... >` shows as https://www.carbondesignsystem.com/components/overview/[object Module]

Thanks.  I'd have enjoyed the page if I could have seen even tiny pictures of what the components looked like.

**Comment by joshblack** [comment]
Hi there! This should be closed by: https://github.com/carbon-design-system/carbon-website/pull/2545

This issue is tracked in the website repo with: https://github.com/carbon-design-system/carbon-website/issues/2514
