### ISSUE TITLE
[Bug]: Postinstall script tries to run "carbon-telemetry"

### ISSUE THREAD

**Issue by boonware** [carbon-design-system/carbon#9668]
## Package
@carbon/icons-react

## Package Version
10.37.0

## Description
Running `npm prune --production` fails as a post install script is trying to run the command `carbon-telemetry`.

> @carbon/icons-react@10.37.0 postinstall node_modules/@carbon/icons-react
> > carbon-telemetry collect --install
> 
> sh: 1: carbon-telemetry: not found

## Dependencies
```
    "@babel/parser": "^7.15.3",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "carbon-components": "^10.41.0",
    "carbon-components-react": "^7.41.0",
    "carbon-icons": "^7.0.7",
    "d3": "^7.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "sass": "^1.38.1",
    "web-vitals": "^1.1.2"
```

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I checked the current issues for duplicate problems

**Comment by joshblack** [comment]
@boonware could you provide some additional steps to reproduce? I tried to re-create the issue but could not see the error that you encountered.


https://user-images.githubusercontent.com/3901764/133489531-ad9e6495-ca42-45f0-a7b5-bffc11009082.mov

**Comment by boonware** [comment]
@joshblack My apologies. Looks like I had a mistake in my process that unintentionally modified the `node_modules` directory. Many thanks for taking a look at this.

**Comment by joshblack** [comment]
No problem at all @boonware! Glad you figured out what was going on 🍻
