### ISSUE TITLE
Sprint 19: Blink One Eighty Brie 🧀

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#9669]
## ⚛️  React

- [ ] #9535 @joshblack @sstrubberg 
- [ ] #9466 @dakahn @abbeyhrt    
- [ ] #9712 @jnm2377 @sstrubberg 
- [ ] https://github.com/carbon-design-system/carbon/issues/8487 @tay1orjones @andreancardona 
- [ ] Tooltip @joshblack @andreancardona 
- [ ] ContentSwitcher @andreancardona @dakahn 

## 🚢  Migration

- [x] Update migration guide for Design tab with Beta 2 release items @laurenmrice @kingtraceyj 
- [ ] https://github.com/carbon-design-system/carbon/issues/9640 @joshblack @jnm2377 
  - [ ] Go through upgrade flow with design [NEEDS DESIGN REP]
  - [ ] Finalize initial upgrade flow
  - [ ] Implement package upgrade (preview, write)
  - [ ] Implement migration runner (preview, write)

## 🎨  Styles

- Figure out consistent spacing for form components @tay1orjones 

## 📝  Website

- [ ] Usage docs for Disclosure pattern @laurenmrice
- [ ] PR issue for Toggle tip @kingtraceyj 
- [x] Style doc for tile @thyhmdo 
_
- [x] https://github.com/carbon-design-system/carbon-website/pull/2519 @thyhmdo 

## 🎨 Design Kit

- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/429 @aagonzales 

**Figma**

- [ ] Figma project reviews @aagonzales @laurenmrice  

## 💬 Support

- [x] https://github.com/carbon-design-system/carbon/issues/9666 @abbeyhrt 
- [x] https://github.com/carbon-design-system/carbon/issues/9667 @andreancardona 
- [x] https://github.com/carbon-design-system/carbon/issues/9676 @abbeyhrt 
- [x] https://github.com/carbon-design-system/carbon/issues/9112 @aledavila 
- [ ] https://github.com/carbon-design-system/carbon/issues/9367 @dakahn
- [ ] https://github.com/carbon-design-system/carbon/issues/9444 @dakahn 
- [x] https://github.com/carbon-design-system/carbon/issues/9261 @tay1orjones  
- [ ] https://github.com/carbon-design-system/carbon/issues/9431 @sstrubberg 
- [x] https://github.com/carbon-design-system/carbon/issues/8373 @jnm2377 

## 🚀  Releases

- Release v10.45

## 🐝  Brand
- [ ] https://github.com/carbon-design-system/carbon/issues/9520 @kingtraceyj @thyhmdo 

## 🛠 Tooling

- [x] Update @carbon/cli to be workspace-agnostic for C&CS @joshblack 

## 📣 Communication

- [ ] Release Partners 9/30
- Blog post talking about style changes 9/30
  - Needs writer (@andreancardona, @abbeyhrt   + @joshblack ?)
  - Needs artwork
- [x] Publish the Beta 2 announcement @joshblack 9/21
- [ ] Blog post about tutorial migration 9/21 @jnm2377 
  - [x] Needs artwork
- [ ] Blog post about Toggle tip, tooltip, disclosure, pop-over @laurenmrice @kingtraceyj  
  - [ ] Needs artwork
- [ ] Finish draft for feature flags post @andreancardona 
  - [ ] Needs artwork

## 🏖️ **Vacations**
Lauren OOO: Oct 1 🚗🌵

**Comment by aagonzales** [comment]
# 📓 Planning

## ⚛️  React


## 🚢  Migration


## 🎨  Styles


## 👓 Visual Testing


## 📝  Website


## 🎨 Design Kit


## 💬 Support


## 🚀  Releases


## 🐝  Brand


## 🖥️ DPO


## 🛠 Tooling


## 📣 Communication


## 🏖️ **Vacations**

**Comment by joshblack** [comment]
## ⚛️  React

- Add auto-alignment to popover
- Add "isolated" feature for popover (portal)
- Add ToggleTip
- Refactor Definition Tooltip
- Add IconButton
- Breaking changes to Tabs


## 🚢  Migration

- Upgrade CLI
- Sample App
- Migration docs
  - Styles migration, common usage situations, etc


## 🎨  Styles


## 👓 Visual Testing


## 📝  Website

**Bugs**
- [x] https://github.com/carbon-design-system/carbon-website/issues/2540 - Dev bug


## 🎨 Design Kit


## 💬 Support


## 🚀  Releases


## 🐝  Brand


## 🖥️ DPO


## 🛠 Tooling


## 📣 Communication


## 🏖️ **Vacations**
