### ISSUE TITLE
[Feature Request]: Add a new tag option

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon#9670]
### Summary

The IBM Research design team created a customized tag component for their latest web design release. We'd like to contribute back to Carbon/request an update to the core component so that other teams can use.

### Details:

1. The tag has a white background
2. Black font-color
3. 1px black stroke 
4. The tag is also clickable and have a grey-10 hover state

Example of specs:
![Uploading Screen Shot 2021-09-15 at 4.34.25 PM.png…]()

### Justification

We decided to organize our web content using tags and therefore needed to create a visual system to differentiate the different content types. When using a lot of tags in one area, we found the color fills of the Carbon default tags created too much visual clutter (or rainbow effect). The simple black and white version allowed us to simplify the overall design and focus on the content and interactivity. 

### Required functionality

The tag works the same as all other tags but has a hover state (grey-10).

### Specific timeline issues / requests

No -- our devs already implemented the component [here](https://www.research.ibm.com/blog) and [here](https://www.research.ibm.com/publications).

### Available extra resources

We can provide the design and code 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
cc @carbon-design-system/design

**Comment by aagonzales** [comment]
Mike and I talked to Lara offline and we're good with adding in this variation.
