### ISSUE TITLE
[Bug]: Missed language translation Dropdown

### ISSUE THREAD

**Issue by mateBe95** [carbon-design-system/carbon#9682]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

The newest

### Description

There is missed translations on Dropdown component when  u hover on it
![image](https://user-images.githubusercontent.com/23103157/133611056-f4076553-40a7-4e51-a3d8-70ffa9046ce6.png)
Missing translations: 
			"eo",
			"de",
			"es",
			"fr",
			"it",
			"ja",
			"pt-BR",
			"ru",
			"sv",
			"zh",
			"zh-TW"

### CodeSandbox example

https://codesandbox.io/s/5xrmq

### Steps to reproduce

1. Change browser lang for example "russia"
2. Hover on dropdown in order to see missed translation ( u will see only english version).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @mateBe95! 👋 

Carbon does not provide translations out of the box as many labels will need to be contextual. On the development side, you can translate these components using the `translateWithId` prop.

Hope this helps!

**Comment by mateBe95** [comment]
ok, it will helps. thank you
