### ISSUE TITLE
`$expressive-paragraph-01` line height changed unexpected

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#9695]
### Package

@carbon/type

### Browser

Chrome

### Package version

v10.43

### Description

Trying to upgrade to v10.43 but noticed $expressive-paragraph-01 has an unexpected change in line height, causing some of our paragraphs to shrink on `sm` breakpoint: 

![Sep-17-2021 10-59-40](https://user-images.githubusercontent.com/15144993/133818194-858d628d-defb-430f-a924-eefc4b575967.gif)

Here’s the PR https://github.com/carbon-design-system/carbon/pull/9480/files#diff-05d3b50960b9db2e97460996f31cfe89a8d69432ba9edeee1dd4c9b57695d224R436
![image](https://user-images.githubusercontent.com/15144993/133817550-b1804cfe-f23e-4e17-aad4-2bdaf56013ee.png)

### CodeSandbox example

NA

### Steps to reproduce

1. See Carbon for IBM.com upgrade branch: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7070

2. See Percy results via testing box below or see https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/12686358?utm_campaign=538fc19a&utm_content=Carbon-for-IBM.com-Web-Components&utm_source=github_status_public

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
@shixiedesign @carbon-design-system/design what's the official value for the line heights for these tokens? Happy to make the change so that it's the correct value 👍
