### ISSUE TITLE
[Bug]: The bx--slider-text-input input field accepts invalid inputs including certain types of script injections

### ISSUE THREAD

**Issue by brnnnfx** [carbon-design-system/carbon#9696]
### Package

carbon-components

### Browser

Firefox ESR

### Package version

10.17

### Description

The `bx--slider-text-input` input field stores/caches invalid inputs including certain types of script injections

### CodeSandbox example

https://codesandbox.io/s/frosty-hamilton-so9n8

### Steps to reproduce

* In the attached code sandbox enter an alphanumeric string that looks like scientific notation but isn't, such as "6y7", into the input field
* Hit ENTER on your keyboard

🪲 **BUG - The invalid input is stored / cached**🪲

![stored1](https://user-images.githubusercontent.com/12024098/133836712-81c60b9c-aab2-405c-b02f-09ccd7318e97.jpg)

* In the attached code sandbox field paste the following injection that contains an esoteric attack vector into the input field 
`<META HTTP-EQUIV="Set-Cookie" Content="USERID=&lt;SCRIPT&gt;alert('XSS')&lt;/SCRIPT&gt">`
*  Hit ENTER on your keyboard

🪲 **BUG - The invalid inputs are stored / cached**🪲

![stored2](https://user-images.githubusercontent.com/12024098/133836727-a19e5a60-fc9a-4380-975d-6a44feb6a611.jpg)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
@brnnnfx I can't recreate this bug using our latest version. It looks like you're still on `10.17`, are you seeing this issue if you update?

**Comment by brnnnfx** [comment]
> @brnnnfx I can't recreate this bug using our latest version. It looks like you're still on `10.17`, are you seeing this issue if you update?

Hi @jnm2377 yes, I can. I can also reproduce the issue in a sandbox using the latest version of Carbon, and on the [Slider Usage page](https://www.carbondesignsystem.com/components/slider/usage
![liveDemo](https://user-images.githubusercontent.com/12024098/134061892-0ec83d72-9dff-4d08-914b-eb639bcf2688.jpg)

It appears the handling is different between browsers. The screenshots I've taken are from Firefox. Edge (Chromium) also has the issue(s), but the pasted content appears clipped at a certain amount of characters or something in the input field.

**Comment by jdharvey-ibm** [comment]
@brnnnfx Could you be more specific about what you expect the intended behavior to be?

In chrome, the only characters that I am allowed to type in the input field are ones that are part of valid numbers (including scientific notation). Pasting is similar in that only valid number characters will be pasted into the input. All other characters in the paste are discarded.

In Firefox, the behavior is slightly different in that you can type any character into the input box itself, but when you go to retrieve the `value` of the input element, the value will be `""` if the input text is not a valid number. Here's a relevant Firefox issue discussing that behavior and the justification of it: https://bugzilla.mozilla.org/show_bug.cgi?id=1398528

**Comment by brnnnfx** [comment]
> Could you be more specific about what you expect the behavior to be?

- I expect the response in this input field to be consistent across browsers and irrespective of input (paste or type); when the input is invalid, we should display the red border (see attached)
- I expect reasonable 'guards' against attempts to inject or execute malicious code
    - I am very flexible in terms of what solution is implemented, but I am curious that if the max value that will work with the slider is `100`, can we dismiss or cut off inputs that are < 3 characters?


![expected](https://user-images.githubusercontent.com/12024098/134956618-3e464bd5-ef2d-4aa1-9405-69e7ade884e1.jpg)

**Comment by jnm2377** [comment]
Dup: https://github.com/carbon-design-system/carbon/issues/9225
Closing this as it's a browser specific issue, as commented here https://github.com/carbon-design-system/carbon/issues/9225#issuecomment-882704153 and here https://github.com/carbon-design-system/carbon/issues/9696#issuecomment-927976755

For maintainers, here's a [slack discussion](https://ibm-studios.slack.com/archives/GD8JG6JR3/p1632767018016500) from our carbon-support channel.

**Comment by jnm2377** [comment]
rel: https://github.com/carbon-design-system/carbon/issues/7039
