### ISSUE TITLE
[Bug]: Tabs do not have left scroll button when scrolled to the right side

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#9698]
### Package

carbon-components, carbon-components-react

### Browser

Safari

### Package version

10.43.0, 7.43.0

### Description

When a user scrolls tabs the left scroll arrow does not appear unless a resize event happens to the page (when the scroll position for the tabs is not 0 on the left).  

I found that using older React (like Sandbox defaulted to) worked but would throw a ton of errors. Using latest react (17.0.2) did not have errors but did not show the arrow unless I resized.

See recording here:
![example3](https://user-images.githubusercontent.com/8028956/133861508-5bd6ed20-911c-4367-9552-bbd5240a11c1.gif)

Project reference: IBM Aspera

### CodeSandbox example

https://codesandbox.io/s/sleepy-ardinghelli-y8pry

### Steps to reproduce

Scroll list with either the right arrow or a trackpad. The left arrow does not appear when content goes off screen.  However, a resize event of window will trigger it to appear.  

Expected: The arrow appears as soon as Tabs container is not left scrolled at 0.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dabrad26** [comment]
I am seeing an issue with this fix.  Now when I scroll tabs left or right a few times the app crashes (this test app does not have an onError catcher like our prod apps).

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

```
The above error occurred in the <Tabs> component:

Tabs@https://localhost:3001/Aspera/aspera-starter/static/js/vendors~main.chunk.js:270510:81
div
AsperaTabs@https://localhost:3001/Aspera/aspera-starter/static/js/main.chunk.js:15900:10
withRouter(AsperaTabs)@https://localhost:3001/Aspera/aspera-starter/static/js/vendors~main.chunk.js:447428:36
div
```
![example1](https://user-images.githubusercontent.com/8028956/141538618-6b6092f6-3251-4e24-993c-e238c898c3ca.gif)

**Comment by joshblack** [comment]
Thanks so much for the heads up, @dabrad26. I went and changed our latest tag to point to the previous stable release until we can hotfix this on Monday.

**Comment by tay1orjones** [comment]
@mateBe95 I can't remember if we chatted on slack or not - if not, could you open a new issue for this and include a sandbox reproduction? Thanks!

**Comment by mateBe95** [comment]
The issue appear whenever user resize instead of scrolling @tay1orjones
