### ISSUE TITLE
[Bug]: Safari: legendText as a tooltip node is not working in Safari for component RadioButtonGroup

### ISSUE THREAD

**Issue by lukewang2018** [carbon-design-system/carbon#9711]
### Package

carbon-components-react

### Browser

Safari

### Package version

Version 14.1 (16611.1.21.161.6)

### Description

Steps:
1. Create a page using the component RadioButtonGroup, the legendText will be a tooltip node
2. Access the page in Safario , e.g. Version 14.1 (16611.1.21.161.6)
3. Hover on the tooltip icon

expect to see:
1. it's showing as a cursor and showing the tooltip after clicking.

Issue:
1. it's **NOT** showing as a cursor,  and **NOT** showing the tooltip after clicking.

### CodeSandbox example

Cannot create the sandbox.

### Steps to reproduce

Steps:
1. Create a page using the component RadioButtonGroup, the legendText will be a tooltip node

**code piece:**

```
import { Tooltip } from '@console/pal/carbon-components-react';
    const tooltipNode = (
      <Tooltip
        triggerId="test-tooltip"
        iconDescription="test desc"
        className={styles.toolTipText}
        direction="right"
        triggerText="test label"
        showIcon
      >
        "tooltip test"
      </Tooltip>
    );
...
        <RadioButtonGroup
          ...
          legendText={tooltipNode}
        >
          .....
        </RadioButtonGroup>

...

```

2. Access the page in Safario , e.g. Version 14.1 (16611.1.21.161.6)
3. Hover on the tooltip icon

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Repro: https://codesandbox.io/s/nifty-joana-p1f1k

Confirmed Safari 14.1.1 tooltip does not show


https://user-images.githubusercontent.com/3360588/134269378-a3ff1aa5-2b05-4fd6-8137-457f3bb941b3.mov

**Comment by aledavila** [comment]
I'm just gonna be adding notes here to keep track: 

- Tooltip isn't getting the attribute "aria-expanded" which is what makes is trigger. The same code sandbox does work in Firefox so this is an issue with safari specifically not getting that attribute when its being passed into the "legendText".
- 
<img width="712" alt="Screen Shot 2021-09-28 at 6 07 52 PM" src="https://user-images.githubusercontent.com/12533409/135177657-eb0c924b-91a6-4070-9bb6-17fc79c543e6.png">
 
<img width="629" alt="Screen Shot 2021-09-28 at 6 08 14 PM" src="https://user-images.githubusercontent.com/12533409/135177663-d3c03f77-5a3c-4048-b118-96d5c61acb7a.png">

**Comment by tay1orjones** [comment]
This should be fixed in v11. We will accept PRs for fixes for v10, but the recommendation here would be to use v11 packages, eg. `@carbon/react@1.x`
