### ISSUE TITLE
[Bug]: DataTable throws exception if the sorted column is not rendered

### ISSUE THREAD

**Issue by holmansze** [carbon-design-system/carbon#9713]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.7.0

### Description

DataTable throws an NPE when the cells being sorted do not exist.

### CodeSandbox example

https://ijsul.csb.app/

### Steps to reproduce

In the code sandbox, click "Port" column header to sort by Port, then click the blue button at the bottom to see the exception.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Would be great to have a proper fix, thanks for the PR!
