### ISSUE TITLE
Focus not visible when user navigated to currently selected option in combo-box

### ISSUE THREAD

**Issue by minnekanti** [carbon-design-system/carbon#9715]
### Steps to reproduce:

1. Navigate to live demo of [combo-box ](https://www.carbondesignsystem.com/components/dropdown/code)
2. Select an Option (ex: option 2)
3. Open the combo-box again and navigate though the options.

### Issue: Focus not shown when navigate to currently selected option (ex: Option 2) in combobox

This is a failure of Accessibility Checkpoint [2.4.7. Focus Visible](https://www.w3.org/TR/WCAG21/#focus-visible)

<img width="1429" alt="Screenshot 2021-09-22 at 07 38 03" src="https://user-images.githubusercontent.com/16116659/134294676-ae0d1de6-8c03-422c-b42d-33124aa42a95.png">

one way to improve this might be to remove the grey background from the selected item so that a grey background means "focussed"

**Comment by joshblack** [comment]
Hi there @minnekanti 

In the case of the dropdown component, it currently uses the listbox pattern. In this pattern, focus will move to the element with `role="listbox"` and remain there. The active item is communicated via `aria-activedescendant` to the screen reader. For comboboxes, focus will remain on the `<input>` with `role="combobox"`

In the case of the dropdown, the item with `role="listbox"` is the popup with the blue border around it. The selected item has `aria-selected` and the active item is related to the screen reader via `aria-activedescendant`.

In the case of mouse or keyboard users, there is a highlight used to indicate which item is "active".

I believe that this is not a violation of SC 2.4.7 but let me know if I'm missing some part of the pattern, Success Criterion, etc that we need to be adhering to.

**Comment by minnekanti** [comment]
@joshblack When you navigate the listbox using arrow keys once the currently selected item gets focus there is no indication to the user that it received the focus like other elements where back ground colour changes..

that's why i suggested to remove the background colour for selected option (since we have the Tick mark next to it indicating the selected item) and just change the background colour once it received the focus similar to other items

@carmacleod Please add in your comment if you disagree

**Comment by joshblack** [comment]
@minnekanti got it, it seems like you're referring specifically to the selected item having no visual indicator when a user is hovering over it or if a keyboard user navigates to it with arrow keys. Is that correct?

**Comment by minnekanti** [comment]
@joshblack Exactly that's the scenario i am referring to

**Comment by joshblack** [comment]
cc @laurenmrice just wanted to get your read on this, you might already have something for this in the spec/on the site but I wasn't sure so figured I'd double-check with you 👀

**Comment by minnekanti** [comment]
@laurenmrice I don't think that background colour difference will satisfy requirements for all users and also if you are in High Contrast mode, there is no way to tell the difference, so i would go with the option of removing the background for the selected item, and just have the tick mark and then when the item receives the focus, highlight it with the background colour same as for all the other options
