### ISSUE TITLE
[Bug]: Modals are clipping combobox dropdowns

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#9732]
### Package

carbon-components

### Browser

Chrome

### Package version

10.44

### Description

Modals are now clipping the combobox dropdown, or at least, forcing it to remain in the modal.

This is a regression from #7698, which is no longer needed because the real problem was fixed in #9418.

So, the solution here (I believe) is to roll back #7698.

### CodeSandbox example

https://codesandbox.io/s/cocky-lovelace-d95h5?file=/index.js

### Steps to reproduce

Open https://codesandbox.io/s/cocky-lovelace-d95h5?file=/index.js, scroll down to the combobox, and open the dropdown.

Note that it does not overlay the modal's "Cancel" and "Submit" buttons like it should.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This appears to also be related to #7565? Maybe not though since this doesn't mention scrollable areas inside modal, just the modal itself.

**Comment by francinelucca** [comment]
is this and https://github.com/carbon-design-system/carbon/issues/7565 the same issue? if so, should we close one?

**Comment by tw15egan** [comment]
Yeah @francinelucca they are encountering the same issue. It seems like the other issue has a bit more history / workarounds, so lets close this one in favor of that 👍🏻
