### ISSUE TITLE
[Bug]: OverflowMenu's onclick calls 2 times after each click

### ISSUE THREAD

**Issue by hungdev** [carbon-design-system/carbon#9744]
### Package

carbon-components-react

### Browser

Chrome

### Package version

carbon component react v7.44.2

### Description

OverflowMenu's onclick calls 2 times after each click, sometime it calls once, sometime it calls twice.

### CodeSandbox example

https://codesandbox.io/s/fancy-sun-ewd48?file=/src/App.js:361-373

### Steps to reproduce

Only click to OverflowMenu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by rzhekova** [comment]
Hello, I think I may have a solution to this issue. I can push up the changes if you don't mind assigning this to me. Thanks!
