### ISSUE TITLE
Overflow Menu Component Slowing Page on Firefox

### ISSUE THREAD

**Issue by MurAnn** [carbon-design-system/carbon#975]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?
general issue: When using a large number of overflow menu on the page, the navigation on this page gets too slow, and the more overflow components  I add, more slow it gets. But.... it happens only on Firefox, and is not just on my machine... All my co-workers experienced this. 
We need to use this component on our data tables, and, as all the rows will have this component, it's necessary that it be fixed, otherwise, it will be impossible to navigate on pages with tables, and it must work on Firefox, not just on Chrome... Could you guys take a look?

> Is this issue related to a specific component? 
Overflow Menu Components and possibly, other ones... 

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected the navigation to be normal on Firefox when having lots of overflow menus on it, as it happens on Chrome. Instead, I got a slow page, that depending on the number of overflow menus, gets inoperable. What I would like you guys to change, is that the component be usable on the Firefox too.

> What browser are you working in? 
Firefox

> What version of the Carbon Design System are you using? 
9.1.16

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
I'm working on a important app that must be release as soon as possible, once we have already exceeded the target date.

## Steps to reproduce the issue

1. Step one
First, add to a common page a small amount of overflow menus, like five of them. 
2. Add a input text on that same page.
3. Press and keep pressed any key, like 'a' and see the speed of the letters appearing in the text field. It will probably looks ok.
4. Now, add more 20 overflow menus, and try to type again on the text field. It will be slower. 
5. Now, add more 80 overflow menus. It will be almost inoperable. The texts will barely appear.

## Additional information

* Screenshots or code
See the Gif below:
![overslow](https://user-images.githubusercontent.com/25061327/42700134-38ee9aca-8699-11e8-86ca-b2aebebbaba5.gif)

* Notes
It's possible that this is happening with some other components also...

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
Is there any way you could link to your example showing this either on CodePen or CodeSandbox? It would help us reproduce the specific issue

**Comment by MurAnn** [comment]
I could send to you on CodePen, but I already try it and this problem doens't appear there.

**Comment by MurAnn** [comment]
I'm using carbon with angular 6

**Comment by tw15egan** [comment]
Hmm, could you try it in an Angular environment in CodeSandbox? https://codesandbox.io/s/angular

**Comment by MurAnn** [comment]
Sure! How can I use carbon components there?

**Comment by tw15egan** [comment]
Over on the left-hand side, you should see a `Add Dependency` Button. You can add Carbon that way, or use the CDN links found on [our website ](http://www.carbondesignsystem.com/getting-started/developers/vanilla)

**Comment by MurAnn** [comment]
Great, let me try.

**Comment by asudoh** [comment]
Hi @MurAnn thank you for entering this issue. Before I suggest a solution, quick question - Why does your application need many dozens of overflow menus? It signals having too many DOM elements active which itself slows down your app (e.g. requires heavy paint task). Thanks!

**Comment by MurAnn** [comment]
Hi @asudoh ! Actually, I need my data table to have one over flow per row, that's why I need I lot of them. I'm back now, I will check on codeSandBox.

**Comment by asudoh** [comment]
Hi @MurAnn have you considered using [the pagination UI](https://github.com/IBM/carbon-components/blob/e63b586/src/components/data-table-v2/data-table-v2--pagination.hbs#L356-L405)?
