### ISSUE TITLE
[Toggle] Text when Disabled does not provide enough contrast and is difficult to read

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/carbon#9750]
## Environment

All browsers

## Detailed description

Latest version of Carbon. We notice the colors chosen for when the Toggle component is disabled doesn't provide enough contrast to read the text. Furthermore, in our product specifically (SOAR Playbook Designer), we use Gray-90 as the background for the Toggle, and when disabled, the Toggle SVG's background matches the same color and isn't discernible.

> What WCAG 2.1 checkpoint does the issue violate?

Text contrast. Although disabled buttons are exempt from contrast requirements, we think it would still be beneficial to provide clearer contrast in these cases.

## Additional information

Example in product (SOAR Playbook Designer) Gray-90 background:
![image](https://user-images.githubusercontent.com/3118961/134032160-da4b2e64-67cb-4ad5-b7de-720d4733a53d.png)

Example in Storybook, white background:
![image](https://user-images.githubusercontent.com/3118961/134032241-111b1c96-6044-48ae-8512-c78e082acfe0.png)

**Comment by Spectre-ak** [comment]
Can I work on this?

**Comment by aagonzales** [comment]
> Text contrast. Although disabled buttons are exempt from contrast requirements, we think it would still be beneficial to provide clearer contrast in these cases.

If a user needs to be able to read the toggle then you should not be using the disabled component. Disabled components are not accessible by screen-readers and will be skipped and therefore increase the legibility contrast will only help sighted user with the disabled state. 

I'd advise exploring other ways to signal the ux interaction you're trying at achieve such as a read-only state as Lauren suggest or perhaps adding a lock icon beside the toggle to signify it can't be changed.
