### ISSUE TITLE
Update `light` prop usage with `Layer` component

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9763]
We currently use the `light `prop in situations where a component may live on different background colors (namely if it sits on `ui-background` and `field-01`.

However, as the number of layers grows (up to 4) we end up alternating using `light` or not in light themes. In dark themes, however, this striping is not possible as the colors should lighten.

In v11, we will use the `Layer` component to accomplish this. This issue is to setup the following components which have a `light` prop to work with the `Layer` component and deprecate usage of the `light` prop for v11. Specifically:

- In v11, the `light` prop will be deprecated (but not in v10)
- There should be stories for these components around how to use it with the `Layer` component

Below is the list of components impacted:

- [x] Select	
- [x] ListBox
- [x] TimePicker
- [x] RadioTile
- [x] Tile
- [x] ClickableTile
- [x] SelectableTile
- [x] ExpandableTile
- [x] TextInput
- [x] ControlledPasswordInput
- [x] PasswordInput
- [x] TextArea
- [x] Tabs
- [x] Slider
- [x] Search
- [x] OverflowMenu
- [x] NumberInput
- [x] FilterableMultiSelect
- [x] MultiSelect
- [x] Dropdown
- [x] DatePicker
- [x] ContentSwitcher
- [x] ComboBox
- [x] CodeSnippet

**Comment by tay1orjones** [comment]
@aledavila @abbeyhrt is there anything left for this one?
