### ISSUE TITLE
[Bug]: Dropdown menu should overlay Modal

### ISSUE THREAD

**Issue by alissa9090** [carbon-design-system/carbon#9766]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.43.0

### Description

I think that would be cool if dropdown menu will overflow modal so that you don't have to scroll to see the menu.

` .bx--modal-container, bx--modal-content {
    overflow: visible;
  }`  helps to solve the problem for modal that don't have scrolling content.

But I cannot find a good solution for the case when you do have scrolling content (like in my example in codesandbox).

That's how it looks now
![Screenshot 2021-09-29 at 10 52 33](https://user-images.githubusercontent.com/21106246/135237410-210f36bc-0ea7-46af-98d9-e1585c517a63.png)

That's how it should look like
![Screenshot 2021-09-29 at 10 56 43](https://user-images.githubusercontent.com/21106246/135237438-6e84928e-6cdb-490d-9f82-799d5de42ba1.png)

### CodeSandbox example

https://codesandbox.io/s/epic-cookies-emg02?file=/src/index.js

### Steps to reproduce

1) Create a modal
3) Create dropdown inside modal body
4) Click on dropdown to open menu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alissa9090** [comment]
Looks like a duplication of https://github.com/carbon-design-system/carbon/issues/9732

**Comment by dakahn** [comment]
closing as a dupe #9732 👍🏾
