### ISSUE TITLE
feat:(Pagination): Stand alone Small pagination

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#977]
@zerostatic commented on [Thu Jun 14 2018](https://github.com/IBM/carbon-components-react/issues/1004)

The design files show a secondary pagination example (shown below). Any plans to add this?
![comp](https://user-images.githubusercontent.com/209432/41430017-120526c4-6fcc-11e8-9a2e-4731f18584f0.png)

---

@tw15egan commented on [Fri Jul 13 2018](https://github.com/IBM/carbon-components-react/issues/1004#issuecomment-404892095)

There aren't any plans to add this in at this time, but if this is a component someone would like to tackle we would love contributions! We would probably want to start in the Vanilla repo, as that's where the styles would come from, so I'm going to move this one over there.

**Comment by Martskin** [comment]
Is there still interest in adding this new pagination variant as a component? @tw15egan

**Comment by tw15egan** [comment]
I don't think so at the moment, but @IBM/carbon-designers might have a better handle on that

**Comment by aagonzales** [comment]
Yes, I think its still a desired pattern.
