### ISSUE TITLE
Basic Tooltip / Hover Text

### ISSUE THREAD

**Issue by CoriIBM** [carbon-design-system/carbon#9780]
### Summary

Our team needs a very basic tooltip, like the kind that were very simple like what one might have used 8 years ago.  

<div id="a" class="grid">
  <div id="b" class="gridcell">123</div>
  <div id="c" class="gridcell">456</div>
  <div id="h" class="gridcell">789</div>
</div>

Say I want to put a block of text that looks like a tooltip when I click on my gridcell "b" that says "Only numbers less than 150 allowed" and the same to happen when I click on the gridcell "h" and say "Only values between 500 and 1000 allowed".

### Justification

Our TM1 Web uses this as a cor functionality.  The most common popups we have are telling the user things like "only numbers from 0 to 100 are allowed for this cell"

We have grids with thousands of cells and these cells have actions on them like edit and delete so they cannot be backwards coded into the current tooltip from Carbon.  The current tooltop from carbon includes both the tooltip and the target the tooltip is related to.

### Desired UX and success metrics

user is able to click/double click on a dom element and get the popup next to/under/above that dom element
user is able to close this by moving focus or by a specified gesture

### Required functionality

developer has these knobs:
* invocation type: click/tap, double click/double tap, hover
* destroy action: lose focus, click back on dom element, specified gesture
* text to be shown

tooltip
   targetElement: "myNode",
   invokationMethod: "hover",
   closeOn: "targetLosesFocus",
   text: "only numbers are allowed, not strings"

### Specific timeline issues / requests

We had asked for this a few months ago but were unaware of this system at the time.  We need it by the beginning of November 2021 to make the last release of the year so we can be accepted in to the cloud catalog.

### Available extra resources

I have 3 devs with me righ tnow, none who undestand UI, and I we are shortstaffed 4 developers.  I can personally spend time with you to go over demoing what we need to replace in our current app, meeting with you on visual design, and meeting with you on flushing out the functionality and API.  I have a degree in UX so I am very very empathetic to your cause and your process and want to make this as easy for you as possible.  I think my OM would also like to lend a hand along with me.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by dakahn** [comment]
Unless there's something i'm missing our Definintion Tooltip should satisfy your requirements as is
https://carbondesignsystem.com/components/tooltip/usage/#definition-tooltip
