### ISSUE TITLE
remove kubernetes UI icon

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/carbon#9781]
remove kubernetes icon from the UI icons repo - turns out we do not have the rights to have an icon of their logo.

<img width="248" alt="Screenshot 2021-09-28 at 16 48 26" src="https://user-images.githubusercontent.com/51086727/135099839-de1a1ec3-b70d-4b06-a977-73311919814a.png">

**Comment by alisonjoseph** [comment]
Hi @DianaStanciulescu this will need to get removed from the icons package

**Comment by DianaStanciulescu** [comment]
@alisonjoseph I am now getting in touch with kubernetes to see if we can after all, get approval. but can we at least .. not display it in the repo for now? does this mean just deleting the entry from the yml file?

**Comment by alisonjoseph** [comment]
@DianaStanciulescu We would need to update the yml file and remove the svg from the repo, publish a release, and then update the Carbon and IDL websites with the latest version. Did you want to go ahead and have us remove it, or wait and see if they are ok with us keeping it?

**Comment by DianaStanciulescu** [comment]
@alisonjoseph since it's a pretty big move, let's wait for a bit and hope nobody will notice we have it. if i do not receive an answer in a week, we should probably go ahead and remove it. thank you for your hep!

**Comment by mjabbink** [comment]
Probably can add their real logo in the section where we have some no?

**Comment by DianaStanciulescu** [comment]
We need to use the icon unaltered. I asked if it is ok to include it in our repo. As soon as I receive an aswer we can decide if we need to replace the current kube icon or remove it.

<img width="123" alt="kubernetes icon" src="https://user-images.githubusercontent.com/51086727/135819494-e0ad4855-f29f-4beb-8b34-4dcb69926f43.png">
.

**Comment by joshblack** [comment]
@conradennis @laurenmrice is there anything left that we need to do for this for icons? 👀

**Comment by DianaStanciulescu** [comment]
I kept waiting for a final answer from Kubernetes, and they did not get back to me. I think based on their response, we can replace our current Kubernetes icon with theirs. We should also move it from "systems" to "technology" and call it "Logo Kubernetes"


I attach here the ai file , @conradennis can you take a look, please?

[Kubernetes-logo.ai.zip](https://github.com/carbon-design-system/carbon/files/7711303/Kubernetes-logo.ai.zip)
