### ISSUE TITLE
Add isActive style for HeaderMenu

### ISSUE THREAD

**Issue by RianTavares** [carbon-design-system/carbon#9784]
### Summary

My suggestion is a design/development enhancement.
I would like to set a boolean prop to set a style for HeaderMenu when it's active like already is made for HeaderMenuItem component.

Example of enhancement result:
<img width="548" alt="isactive2" src="https://user-images.githubusercontent.com/8935295/135535831-91c2488b-db41-4588-b2b4-c748e1c00f0c.png">

### Justification

As described in one item of [W3 WAI (Web Accessibility Tutorials)](https://www.w3.org/WAI/tutorials/menus/styling/) it's important to:
"Convey menu items and their states by using color and other styling options. For example, alter the shape of a menu item, or add an icon, in addition to changing its color when it is selected."

I couldn't find a way to do this state change demonstration when a page inside the HeaderMenu is active, then I'm purposing this enhancement.

### Desired UX and success metrics

Clear and consistent styling allows users to find and recognize menus more quickly. Such styling includes consistency in the behavior, appearance, and relative location on pages across a website.

I believe this enhancement will contribute to the user experience with the Header Menu as described above and, as is already done in the HeaderMenuItem component.
Also, this provides best-practice guidance on implementing accessibility for Menus.

HeaderMenuItem example:
<img width="510" alt="tday" src="https://user-images.githubusercontent.com/8935295/135536441-757f1203-8d4c-4c5c-b0a7-5a6c95029815.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by RianTavares** [comment]
PR created for this enhancement #9785

**Comment by matbiit** [comment]
I strongly agree with this idea! It will be have a huge impact in our solutions that using Carbon as Design System! Congrats @RianTavares for the idea and contribution!

**Comment by JulianaBerdeville** [comment]
That's such an interesting point raised by @RianTavares. It would definitely make it easier, accessible and even more accordingly with UX/UI principles and ideas. 
I believe it would raise Carbon's excellency and facilitate the frontend development using Carbon as Design system.
Thanks for sharing the idea, @RianTavares! :)
