### ISSUE TITLE
[Bug]: NumberInput glitch when zooming in browser

### ISSUE THREAD

**Issue by kkckkc** [carbon-design-system/carbon#9786]
### Package

carbon-components, carbon-components-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v.7.44.2

### Description

When using the `NumberInput` component at size `sm` when zooming the browser to 80%, the borders on the stepper buttons are not correctly aligned to the bottom of the input itself. See screenshot (zoomed in to make the effect more apparent)

![image](https://user-images.githubusercontent.com/129546/135582211-7310d137-5272-41cb-8634-8ebb648639f4.png)

I understand that this is a niche issue, but, for various reasons, I rely on the browser zoom settings and I also use large numbers of `NumberInput` so this issue is a bit annoying to me 

The issue seem to be related to the following CSS

```
.bx--number__controls {
   top: 50%;
   transform: translateY(-50%);
}
```

This is here for IE11 compatibility I think, but when I remove the `top` and `transform` property then everything seem to work properly.

By the way, the same issue appears with `size = md` as well, but it shows up on different zoom levels 

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground
2. Set the size property to `sm`
3. See browser zoom level to 90%

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by dakahn** [comment]
Confirmed this in Edge on Ubuntu 
![image](https://user-images.githubusercontent.com/40970507/135929792-6af35a74-710c-4894-a58a-43d929761d8e.png)
