### ISSUE TITLE
Overflow menu does not position correctly if browser is zoomed in

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#979]
## Detailed description
The overflow menu checks assumes top, left, width, height and border-top-width will all be whole pixel values for a target pseudo element. 

.#{$prefix}--overflow-menu-options:before

This is an invalid assumption when zooming in and/or out the browser.

This
      [name]: Number((/^([\d-]+)px$/.exec(arrowStyle.getPropertyValue(name)) || [])[1]),
should read
      [name]: Number((/^([\d-.]+)px$/.exec(arrowStyle.getPropertyValue(name)) || [])[1]),

> Is this issue related to a specific component? 
Overflow menu although a similar test exists in tooltip.

> What did you expect to happen? What happened instead? What would you like to see changed?

Overflow menu positioned correctly

> What browser are you working in? 

Chrome 67

> What version of the Carbon Design System are you using? 
9.1.20

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
NOTE: Occurs here https://codepen.io/team/carbon/full/MOEwjp/
1. zoom in once
2. open overflow menu
3. Note the offset is not calculated correctly.

**Comment by asudoh** [comment]
Thanks alot for catching @lee-chase! Appreciated if you can submit a quick fix as you proposed.
