### ISSUE TITLE
[Feature Request carbon-components-react]: Extend allowEmpty to include undefined

### ISSUE THREAD

**Issue by jonguenther** [carbon-design-system/carbon#9796]
### Summary

Currently, when passing no value or `undefined` to `NumberInput`, the component will show `0` as value. However, this can be very confusing, when a form has optional fields which show `0` but should actually be empty. It would therefore be highly beneficial if there was an option to not show any data in `NumberInput`.

### Justification

Having the option to not show any value helps mitigating confusion with customers when dealing with optional inputs in forms.

### Required functionality

`NumberInput` should not show anything if `defaultValue` or `value` is `undefined` or add a prop that turns on/off this functionality.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hi @jonguenther - The `allowEmpty ` prop is intended to cover this type of use case. If that doesn't fully cover what you need, could you provide more details on the situation and a [codesandbox example](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)?

**Comment by jonguenther** [comment]
Hey @tay1orjones, thanks for the swift reply! You're right, `allowEmpty` works, but only if `value` is explicitely set to `null`. Could that be extended so that `NumberInput` would also be empty, if `value` is `undefined` or if `defaultValue` is set to `null` or `undefined`?

Here's a [codebox example](https://codesandbox.io/s/quiet-frost-ugsky?file=/src/index.js).

**Comment by pmweeks98** [comment]
Think this might be able to be closed

@sstrubberg see this sandbox https://codesandbox.io/s/frosty-cloud-tp7t8k?file=/src/index.js

**Comment by sstrubberg** [comment]
> Think this might be able to be closed
> 
> @sstrubberg see this sandbox https://codesandbox.io/s/frosty-cloud-tp7t8k?file=/src/index.js

@carbon-design-system/developers can i get confirmation on this?

**Comment by tw15egan** [comment]
Seems resolved
