### ISSUE TITLE
Data Table - checkbox focus state

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#9808]
Checkmarks within data table (that are not the select column) don't have consistent focus like the expandable and select buttons do.

### Discussed in https://github.com/carbon-design-system/carbon/discussions/9799

<div type='discussions-op-text'>

<sup>Originally posted by **half5cat** October  5, 2021</sup>
Is this intentional? If so, please elaborate on this.

Focus on Expandable Icon:
![image](https://user-images.githubusercontent.com/1887866/135988683-8aea2b17-1937-480e-b830-0226d3f2e3d7.png)

Focus on Checkbox:
![image](https://user-images.githubusercontent.com/1887866/135988910-031a98ac-3e87-45d9-8ab0-23484f4d842e.png)

Source for the above: https://react.carbondesignsystem.com/?path=/story/components-datatable-development--example 

Focus on Checkmark Column:
![image](https://user-images.githubusercontent.com/1887866/135989069-4c112814-3559-41cc-8668-58b2dad7a1fb.png)

Source: https://react.carbondesignsystem.com/?path=/story/components-datatable--with-checkmark-columns</div>

**Comment by jnm2377** [comment]
Question for @carbon-design-system/design, should the border radius match for these focus states in the data table?

**Comment by jnm2377** [comment]
Thanks for the info @laurenmrice Looks like our DataTable didn't get that update and the checkbox focus is still rounded. So looks like the action items are:
- remove border radius from data table checkbox
- do we also remove the padding around the checkbox + focus border? Previously @aagonzales had us make the checkbox border bigger to match the size of the expand btn border.
<img width="115" alt="Screen Shot 2021-12-16 at 11 29 55 AM" src="https://user-images.githubusercontent.com/32556167/146420154-efc5425b-1acd-462d-b70b-aa2cf7560557.png"><img width="122" alt="Screen Shot 2021-12-16 at 11 30 04 AM" src="https://user-images.githubusercontent.com/32556167/146420150-0746fbe5-e594-431b-9a1c-0d04bae6557f.png">
- if the padding is still the way to go, then the last action item would be to make all checkboxes within data table have this, not just the select column (currently, checkboxes in other columns don't get this padding)

**Comment by laurenmrice** [comment]
@jnm2377 Yes, the focus for the chevron and the checkbox should be the same size with the padding Anna mentioned. All checkboxes in the data table should get this padding. 

----

![Artboard](https://user-images.githubusercontent.com/43969356/146572327-cb53b7a0-e42a-4c60-84ea-5c6ba7bdfc97.png)
