### ISSUE TITLE
[slider] text input is too wide

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#9823]
### Question for Carbon

The text input to the right of the slider is too wide in code. Seems to be only appearing in Firefox.
**React screenshot:**
<img width="604" alt="Screen Shot 2021-10-08 at 10 16 48 AM" src="https://user-images.githubusercontent.com/43969356/136583105-ce2fec68-b77c-4f82-b9f6-1e336fe1de20.png">

--------

The text input should be a default width of 64px.
**Design spec:**
![Artboard](https://user-images.githubusercontent.com/43969356/136583306-e42e321f-fc86-45cb-837e-ca76df101c17.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
> The text input should be a default width of 64px

This makes this super easy to fix - I'll open a PR shortly. 

---

I did some research on why this is happening currently. It's a whole mess. It's a disagreement regarding the interpretation of the spec. Specifically around inputs with `width: auto` within nested flex containers. Chrome treats these one way, firefox a different way. Here's the [original bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1242914), the subsequent [chrome bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=581545) and finally a [large discussion](https://github.com/w3c/csswg-drafts/issues/5665) about what the spec should be moving forward.

If we wanted to keep the `width: auto`, the best we could do would be to place a `min-width: 0;` on the input in firefox which improves it slightly, but not the same as chrome.
Existing:
![Screen Shot 2021-10-08 at 3 58 40 PM](https://user-images.githubusercontent.com/3360588/136624091-07ec278a-b4d4-4862-9c44-fe0bf7df0046.png)

With the min-width applied:
![image](https://user-images.githubusercontent.com/3360588/136624113-c3cebb3b-8774-428e-a8ec-303248f5bb3d.png)

Chrome:
![Screen Shot 2021-10-08 at 4 01 21 PM](https://user-images.githubusercontent.com/3360588/136624386-58b09aba-edc0-4b4a-8fab-19d6e3b5ce03.png)
