### ISSUE TITLE
Dynamically place components within `<Layer>`s in storybook

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#9824]
With the recent addition of the `Layer` component, it would be nice to be able to easily view components/stories placed on different layers in storybook. This issue is to explore making a storybook addon to allow the user to select a story and then select an amount of `Layer`s to be wrapped in. This addon would be used in the `@carbon/react` storybook.

This feature tracks very closely to the [storybook addon tutorial](https://storybook.js.org/tutorials/create-an-addon/react/en/introduction/):
1. Provide a dropdown in the storybook story toolbar to select from a list of options (`Layer 1`, `Layer 2`, etc.)
2. When selected, the story would re-render with a decorator dynamically wrapping the story in the applicable amount of `Layer` components.

So the general idea being that for any given story, this dropdown selection would modify how the component is rendered.
```js
// default story renders something like this:
<Tile {...props}>{content}</Tile>
```
```js
// once the user selects "Layer 2" from the addon 
// dropdown, it renders something like this:
<Layer>
  <Layer>
    <Tile {...props}>{content}</Tile>
  </Layer>
</Layer>
```

**Comment by joshblack** [comment]
@tay1orjones should we defer this to post-v11?

**Comment by tay1orjones** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/12776

We're going to defer this and go a different direction - we think it's valuable to keep the layers nested in context to one another to provide context as to how Layers work.
