### ISSUE TITLE
Update `@carbon/react` storybook theme switcher dropdown icon

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#9825]
The theme switcher dropdown currently is just a blank round icon. This appears to be a default from storybook. I think this is something we should be able to customize. 

![image](https://user-images.githubusercontent.com/3360588/136584474-fa984089-a738-4faa-a4ed-23428a4e3c4a.png)

Ideally the icon button used to invoke the dropdown would be our `color palette` icon

<img src="https://user-images.githubusercontent.com/3360588/136584593-4075620d-b155-42b6-a2f1-200daec4b6f2.png" width="200" />

**Comment by joshblack** [comment]
I think we're currently using: https://storybook.js.org/docs/react/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation which only allows these icons: https://storybook.js.org/docs/react/faq#what-icons-are-available-for-my-toolbar-or-my-addon

**Comment by joshblack** [comment]
I went with `paintbrush` since mirror was already in use 👀
