### ISSUE TITLE
[Bug]: Batch checkbox in DataTable header is incorrectly sized and is clipped by the next table header when sorted

### ISSUE THREAD

**Issue by obambrough** [carbon-design-system/carbon#9837]
### Package

carbon-components

### Browser

Chrome, Firefox (probably all browsers)

### Package version

v10.45.0

### Description

The checkbox for the batch actions on the DataTable header is clipped by the next column. This isn't obvious until you add sorting which changes the background color of the next column.

![image](https://user-images.githubusercontent.com/1922249/136809917-fe809360-682e-4841-ba07-ab13d80d7d0d.png)

It's very obvious when using the derived @carbon/ibm-security library as the header background is opaque making the checkbox be clearly clipped (without needing sorting.)

![image](https://user-images.githubusercontent.com/1922249/136816489-2c561526-7762-4015-89b7-26731a4c87d4.png)

The provided codesandbox demonstrates the issue when you sort the column next to the checkbox column (it clips the checkbox) but again its not the sorting that's the issue, the checkbox column is incorrectly sized but its only noticeable using carbon-components when sorting is used.

### CodeSandbox example

https://codesandbox.io/s/2lx3v

### Steps to reproduce

Add batch actions and isSortable to a DataTable then sort by the column next to the batch action checkbox column - the sorted column header will then partially cover the batch action checkbox.

Or without sorting using the devtools view the width of the checkbox column and the column next to it, you'll see they overlap.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
I think we'll need some more info from @carbon-design-system/design - do we have a spec for the intended design when table checkbox selection is used in conjunction with sorting?
