### ISSUE TITLE
Performance: Duplicated CSS code

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#985]
## Detailed description

in the `_helper-mixins.scss` file `@keyframe skeleton` does not have an `import-once` wrapped around it . This causes the keyframe to be included every time the `helper-mixin` file is imported.  Within Carbon's minified CSS file it appears 91 times.

> Is this issue related to a specific component?

no

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the keyframe to only be exported once in the distributed files or when using Sass to create my own bundle. Currently this animation is in our bundled code 65 times and increases our un-minified file by almost 2000 lines.

> What browser are you working in? 

Chrome, Safari, Firefox, Edge, IE11

> What version of the Carbon Design System are you using? 

9.1.5

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Design System

## Steps to reproduce the issue

1. Search for `@keyframes skeleton` in carbon-components.css 
2. Note it appears 91 times

**Comment by joshblack** [comment]
Thanks for reporting this @elizabethsjudd! Definitely an issue on our end, will flag this as a bug and try and get it added to a sprint. Will also accept any/all PRs that address this, as well 😄
