### ISSUE TITLE
Truncation codepen arrows broken

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#987]
Arrows are the wrong size 
https://codepen.io/team/carbon/pen/KRoBQe

![screen shot 2018-07-19 at 9 31 25 am](https://user-images.githubusercontent.com/2753488/42949051-86f38bf8-8b36-11e8-8372-f3395a9cc71c.png)

This appears on the website here http://www.carbondesignsystem.com/utilities/overflow-content

**Comment by aledavila** [comment]
Solved check codepen link
