### ISSUE TITLE
[Bug]: .bx--content background disruptive for dark themes

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#9877]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.46.0

### Description

The [`.bx--content` container](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/ui-shell/_content.scss) which is part of the UI shell (not really documented properly anywhere and not used in the UI shell examples) has a background color that causes poor contrast/visibility in darker themes. For some components it clashes with existing colors.

Examples for the different themes:

![image](https://user-images.githubusercontent.com/834235/137582522-578c5be0-b3f3-4432-8ed4-f21f87e2a9c7.png)
![image](https://user-images.githubusercontent.com/834235/137582527-73509826-fdef-41e0-b405-c6f99fcb50b3.png)
![image](https://user-images.githubusercontent.com/834235/137582534-f852012c-ede6-4731-bc57-997132070c85.png)
![image](https://user-images.githubusercontent.com/834235/137582540-33f1322b-bdbd-4fc9-9352-9adc4bdbc550.png)

Maybe `.bx--content` should not set a background at all?

### CodeSandbox example

https://codesandbox.io/s/bx--content-l1bnj

### Steps to reproduce

- Set theme to g90 or g100
- Add a content container (`.bx--content`)
- Add components like `ProgressIndicator` to it which use conflicting colors

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by brunnerh** [comment]
> I'm not sure why it would be showing up in UI Shell either.

It performs layout in relation to the shell header and side-nav.

Introduced as part of the shell here:

https://github.com/carbon-design-system/carbon/commit/3ee76bdb4589fab631faab2aa26f45d5778c9bad#diff-4ea1e7accf7f77430fe69e984a086fe5fe13f048d2fe6de761960d3444cbb057

**Comment by jnm2377** [comment]
The PR you're linking to was just porting over existing UI Shell styles into our new `@carbon/styles` package that uses sass modules. Nothing new was introduced there. However, we did add theming into the v11 shell. It may be that it's using the wrong token for the background. I feel like I've ran into similar issues with things using the `$layer` token incorrectly.

**Comment by joshblack** [comment]
Just wanted to +1 what @brunnerh shared, the `Content` component uses the `$ui-02` background color @aagonzales.

I think the tl;dr for this component is that we wanted a way to wire up the "skip to content" links with the "main" content area on the page.

**Comment by metonym** [comment]
This issue was fixed by https://github.com/carbon-design-system/carbon/pull/10992 but was not auto-closed by GitHub.

Can an admin close this?

**Comment by brunnerh** [comment]
I can :)
