### ISSUE TITLE
Feature Request Search Component: Provide method to clear input and icon

### ISSUE THREAD

**Issue by StefanDoersam** [carbon-design-system/carbon#988]
eature request for Search component

The use case is:

    There is some text available in the Seach field and the "x-icon" to clear the Search field is displayed.
    The cursor is located in the Search field
    Now the ESCAPE key is pressed
    The ESCAPE key is catured in the appropriate java script code.
    Now the same behavior as when the "x-icon" is clicked should be processed. (search filed cleared, "x-icon" removed/hidden)

For this there should be a public method available ( e.g. clearSearch() )
which can be called form java script or typescript code.

As an alternative, ESC key handling is directly implemented within the Search component and can be anyhow switched on or of if should be handled or not.

**Comment by asudoh** [comment]
Hi @StefanDoersam what you requested may be a nice enhancement - Meanwhile you can do the same thing as: https://github.com/IBM/carbon-components/blob/f91ab13/src/components/search/search.js#L41-L43

**Comment by StefanDoersam** [comment]
Hi Akira,
many thanks for hat hint. 
Do you have an example how to call svgToggleClass from java script??
I have not idea what pass as "icon"
Tx in advance
Stefan

**Comment by asudoh** [comment]
Hi @StefanDoersam `svgToggleClass()` takes a [`SVGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement) as the first argument. That said, you can grab the SVG DOM element via DOM API.
