### ISSUE TITLE
[Bug]: Slider component onChange not called when deleting value in the input box

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/carbon#9898]
### Package

carbon-components-react

### Browser

Chrome

### Package version

^7.41.0

### Description

When we use the slider component and when we try to remove everything, it doesn't give an onChange and thus doesn't help us validate when the user removes the value. Check the sandbox and look at the console.log values. When we remove the number 45 the change shows up as:

```
setting value 45
setting value 4
```

the change should show up like this:
```
setting value 45
setting value 4
setting value 
```

### CodeSandbox example

https://codesandbox.io/s/late-cherry-dxehf?file=/src/index.js

### Steps to reproduce

- Change the input value to `45`
- press backspace two times one to remove `5` and another to remove `4`
- expect to see the `onChange` function be called twice.  

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jdharvey-ibm** [comment]
Hey all! I think I'm technically the one who "introduced" that behavior during a round of bug fixing and refactoring, so I'll provide a little context about it:

Here's a previous version of the slider:
https://deploy-preview-5356--carbon-components-react.netlify.app/?path=/story/slider--default

One of the things I fixed was that it was actually impossible to do what you describe in this issue. If deleting a number from the input would have caused the value to go below the minimum of the range, the input was instead updated to be **at** the minimum value in the range. So if the min was 10 and you currently had 10 in the box and wanted to type 11, it was impossible to do so. There's a bunch of similar cases to that effect as well having to do with the way the two-way binding behaved on the input field.

So _technically_ the old behavior was that you would never get `onChange` events fired for invalid values, but it was also impossible to put an invalid value into the input, at the expense of some usability.

With that said, the consensus in our dev slack channel seems to be that it makes the most sense given the current state of the input to allow the `onChange` event (and by extension the `onRelease` event) to fire when the input becomes empty.

**Comment by tw15egan** [comment]
It seems like this can now be achieved with the `onBlur` prop that was introduced in https://github.com/carbon-design-system/carbon/pull/1134

![2022-07-11 12 21 40](https://user-images.githubusercontent.com/11928039/178312110-23fe6569-5a15-47bd-a2ad-f547cb85e465.gif)
8
