### ISSUE TITLE
Initializing carbon components on reactive DOM update

### ISSUE THREAD

**Issue by mtn** [carbon-design-system/carbon#990]
This issue is related to #441, #518, and a few others.

I'm trying to use Carbon Components with Vue.js, but I'm having trouble with components not being properly initialized. I tried running `CarbonComponents.watch()`, but nothing changed. Similarly, in the update cycle, to try to get a data table to work, I tried:

```js
    let e = document.getElementsByClassName("bx--data-table-v2-container")[0];
    let a = CarbonComponents.DataTableV2.create(e);
    console.log(a);
```

However, the table created has 0 expandable rows and doesn't work at all, even though when I print out the table element (`e`), I can see that it was fully initialized with all rows an headers. What am I doing wrong? I also tried grabbing the element `bx--data-table-v2`, which didn't work (but I don't think that one is right).

Edit: I've also gotten e with `document.querySelector('[data-table-v2]')`, to get the container element, which didn't work

**Comment by mtn** [comment]
I should also include the error generated when I interact with my table:

```
Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at t._rowExpandToggle (carbon-components.min.js:2)
    at t.value (carbon-components.min.js:2)
    at t.value (carbon-components.min.js:1)
    at t._toggleState (carbon-components.min.js:2)
    at HTMLDivElement.<anonymous> (carbon-components.min.js:2)
```

I've also noticed that `expandableRows` doesn't seem to be updating correctly. I think it never expands beyond its initial size, but if I click something on the page that causes a rerender, if there are fewer rows the list doesn't get shorter -- rows are just overwritten. Is there any way I can get access to the `DataTableV2` object?

**Comment by mtn** [comment]
Ah, I see that I just have to call `refreshRows` and it works. What really confused me is that `create` wasn't doing anything to update the instance (as far as I can tell), just grabbing a reference and returning it.

I'm going to leave this issue open for a bit because I'd really appreciate correction if I've misinterpreted something, but will close it in a few days if I hear nothing.

**Comment by asudoh** [comment]
Hi @mtn great to see that you figured it out yourself! You are right that `.create()` is just a factory method to create a instance. `.refreshRows()` is a table-specific method, which has to be called upon any dynamic row addition/removal. Feel free to tell us if you need any further clarification/fix. Thanks!
