### ISSUE TITLE
[a11y]: Can't navigate radio buttons in an overflow menu with a keyboard

### ISSUE THREAD

**Issue by danielannan17** [carbon-design-system/carbon#9935]
### Package

carbon-components-react

### Browser

Firefox

### Package version

v7.45.0

### Description

When you open an overflow menu with radio buttons, you can't properly navigate through all the radio buttons with shift or the arrow keys.

### CodeSandbox example

https://erxr2.csb.app/

### Steps to reproduce

1. Open the overflow menu
2. Try to navigate through all of the radio buttons using only the keyboard
3. You can only select the first and last radio buttons

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and I can re-open!
