### ISSUE TITLE
Carbon Components React: MultiSelect not filterable - bug when typing if menu open

### ISSUE THREAD

**Issue by StuartMorris0** [carbon-design-system/carbon#9938]
Hello!

There is currently a bug with the `MultiSelect` component, when **not filterable**.

This can be reproduced in storybook here: https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

If you open the multiselect and begin typing (note: difficult in storybook due to shortcut commands), an error occurs.
```Uncaught TypeError: items.map is not a function```

The error relates to this code:
```
var _useSelect = (0, _downshift.useSelect)((0, _createPropAdapter.mapDownshiftProps)(_objectSpread(_objectSpread({}, downshiftProps), {}, {
    highlightedIndex: highlightedIndex,
    isOpen: isOpen,
    itemToString: function itemToString(items) {
      return Array.isArray(items) && items.map(function (item) {
        return _itemToString(item);
      }).join(', ') || '';
    },
    onStateChange: onStateChange,
    selectedItem: controlledSelectedItems,
    items: items
  }))),
```

The itemToString part fails due to `items` not being an array. Currently patching with the following:
```
return Array.isArray(items) && items.map(function (item) {
        return _itemToString(item);
      }).join(', ') || '';
```

One solution might be to remove the event listener from the Select when not filterable, unless there are keys used for opening/closing the menu in which case maybe more specific key down events.

**Comment by jnm2377** [comment]
@StuartMorris0 thanks for opening this issue. I think you're right that we could be more specific about which key events we're listening to for non-filterable multiselect. I will add this to our backlog.

**Comment by fabpico** [comment]
I ran in to the same issue which caused confusion. I would like to add custom behavior when typing, without errors/warnings from components which I can't control.

My versions: "react": "^16.8.6", "carbon-components": "^10.34.0", "carbon-components-react": "^7.34.0"

This is also reproducible in the official demo https://www.carbondesignsystem.com/components/dropdown/usage .

![Capture](https://user-images.githubusercontent.com/4472725/159503842-f9cdb76e-4844-4159-8286-0bc69c93d789.PNG)

Also reproducible in sandbox https://codesandbox.io/s/charming-bogdan-7fktd3?file=/src/index.js .

**Comment by imattyk** [comment]
Still present, now on @carbon/react@1.29.1, error when triggering any other key stroke other than spacebar and arrow keys (which are used for navigation through the options).
