### ISSUE TITLE
Is there a  way to customize sortStates in DataTable?

### ISSUE THREAD

**Issue by dawangdw** [carbon-design-system/carbon#996]
## Detailed description

Is there a way to customize [sortStates](https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/state/sorting.js#L8) to only support `ascending` and `descending`.

**Comment by asudoh** [comment]
The code the author points to is of  [`carbon-components-react`](https://github.com/IBM/carbon-components-react) - Issue moved to [IBM/carbon-components-react #1121](https://github.com/IBM/carbon-components-react/issues/1121) via [**ZenHub**](https://www.zenhub.com/)
