### ISSUE TITLE
Ship initial version of tooltip based on design guidance

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9966]
**About**

**Checklist**

- [x] Tooltip should use the Popover component
- [ ] It should support all alignments, including "auto" alignment
- [x] Tooltip should support both label and description
- [ ] Make sure we have styles that match design specs for the "standard tooltip"
- [ ] Only one tooltip should be visible at a time 

**Migration**

- The "interactive tooltip" will need to be updated to the Toggle Tip or an equivalent component
- The "tooltip" component now only receives non-interactive children
- The "definition tooltip" will still have the same usage but a different UX pattern
- The "icon tooltip" will now be the "icon button" component

**Questions**

- [ ] What is the max width of a tooltip in terms of characters or dimensions?

**Comment by tay1orjones** [comment]
Closed via https://github.com/carbon-design-system/carbon/pull/9997
