### ISSUE TITLE
Multi-line or multiple validation strings misaligns selection arrow

### ISSUE THREAD

**Issue by JPMardelli** [carbon-design-system/carbon#999]
## Detailed description

If you have a long validation string that wraps or have multiple validation strings, this causes the dropdown selection arrow to become improperly positioned . This happens because the SVG is positioned using `bottom` positioning

> Is this issue related to a specific component? 

Form component for selection

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected everything to stay aligned. Arrow was misaligned. Arrow to stay aligned.

> What browser are you working in? 

Chrome

> What version of the Carbon Design System are you using? 

9.0.2, tested also on 9.5.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Product, not blocking any ship

## Steps to reproduce the issue

1. Create a form component with validation set up
2. Set the `data-invalid` attribute on the selection.
3. Either provide it a very long string that will wrap or put multiple divs in the `bx--form-requirement` component with text in each

### Screenshot

![broken](https://user-images.githubusercontent.com/1316632/43161701-d3ee43ca-8f56-11e8-9e1f-b06db4ac0af5.png)

### Possible fix

I have a workaround which seems like it could work. I override `bx--select__arrow` and unset the bottom, then set `top: 2.5rem;`.

If you're worried about users not providing a label for their `bx--form-item`, you could have:

```
.#{$prefix}--select__arrow {
  fill: #6e32c9;
  position: absolute;
  right: 1rem;
  top: 1.125 rem;
  width: 0.625rem;
  height: 0.3125rem;
  pointer-events: none;
}

label ~ .#{$prefix}--select__arrow {
  top: 2.5rem;
}
```

This would require users to place the `label` tag before the `svg` tag, so documentation would need to be updated accordingly.

**Comment by asudoh** [comment]
@aagonzales @designertyler @tsaitsaitsai Is multi-line validation error message something we should allow...? Thanks!

**Comment by designertyler** [comment]
The validation messages should be succinct and only a word or two labeling the field as wrong. You can use the inline notification to give the user a better description and steps to resolve. Would this work for your use case? http://carbondesignsystem.com/components/form/usage#validation-and-errors

**Comment by JPMardelli** [comment]
We're dealing with a bit more complicated logic, where the validity of the options of one of our form fields depends on the number of inputs/outputs defined by the user in another field of the form.

E.g. The user selects `Option A` for the type field. Types of `Option A` must have:

- Exactly one output object
- At least one input object

We would either need multi-line validation or have multiple of the error objects in your example, which wouldn't be located near the invalid control and could cause confusion if other areas are also marked invalid.
